### ISSUE TITLE
Are these websites that offer WooCommerce extensions for $5 a scam?

### ISSUE THREAD

**Issue by manake** [woocommerce/woocommerce#21087]
I'm looking for extensions in Google and I found a link high in results (and then more similar ones on further search results pages):

- https://www.themecrack.net/items/woocommerce-ajax-enabled-enhanced-layered-navigation/
- https://srmehranclub.com/product/woocommerce-ajax-layered-navigation/
- https://gpl.life/product/woocommerce-ajax-layered-navigation-extension
- https://woocrack.com/download/woocommerce-ajax-layered-navigation/

They claim that WooCommerce extensions are GPL licensed and therefore free. Is that true?

The original: https://woocommerce.com/products/ajax-layered-navigation/

I need a license for bundling extensions with themes and you don't offer such license so I was looking for alternative plugins and then I found the above websites. Are they a scam?

**Comment by rodrigoprimo** [comment]
Please contact WooCommerce.com support for help regarding your question: https://woocommerce.com/contact-us/

This GitHub repository is used exclusively for WooCommerce core issues.

**Comment by claudiulodro** [comment]
Technically those sites are allowed to sell plugins like that as the GPL gives users "legal permission to copy, distribute and/or modify" as long as they follow the terms of the GPL (include the license when distributing the plugin, include the source code when distributing the plugin, etc.). 

You should know what you're getting into, though. They will likely offer no support for any plugins you purchase, and purchasing a plugin from on of those places does nothing to help support the developers that work hard creating and maintaining those plugins. 

Hope this clears things up.

**Comment by muli2** [comment]
www.wordpresstheme24.com
