### ISSUE TITLE
Payment timeout marks order as cancelled

### ISSUE THREAD

**Issue by ashishbrst** [woocommerce/woocommerce#21083]
Hello everyone,

I have a wordpress website using woocommerce and Buckaroo plugin. Payment gateway we are using is Buckaroo iDEAL. It works well usually but there are cases when it shows payment timeout error. 

In this case we receive the payment but order is marked as cancelled in order history. Is there anyone else facing the same issue?

Any help/suggestions would be greatly appreciated.

Thanks!

**Comment by rodrigoprimo** [comment]
I'm sorry, but we don't use GitHub issues for support, we use it exclusively for WooCommerce bugs, enhancements and feature requests. If you need support, you could try WooCommerce support forums on WordPress.org (https://wordpress.org/support/plugin/woocommerce). You could also try the support channels for the payment gateway that you are using.
