### ISSUE TITLE
Discrepancy in pricing when customer is_vat_exempt

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#21091]
**Describe the bug**
If prices are set to show including tax in the shop and cart and the logged in customer `is_tax_exempt` taxes still show for the products both in the shop and in the cart. This causes confusion to the users on the website as they see something like this:

![](http://cld.wthms.co/uDjpFR+)
Image Link: http://cld.wthms.co/uDjpFR

**To Reproduce**
1. Set taxes to show in the shop and cart in tax settings. 
1. Make sure you have tax rates.
1. Add item to cart. 
1. View cart and everything is correct.
1. Add below snippet to functions.php, or where you'd like. 
1. Refresh the cart.
1. Line item still shows tax, but total does not. 

```
add_action( 'init', function() {
	if ( isset( WC()->customer ) ) {
		WC()->customer->set_is_vat_exempt( true );
	}
} );
```
Hat tip to @bor0 for the snippet. 
This is spawned from https://github.com/woocommerce/woocommerce-eu-vat-number/issues/119 and  1274098-zen .

**Screenshots**
![](http://cld.wthms.co/1cpkjo+)
Image Link: http://cld.wthms.co/1cpkjo

**Expected behavior**
I would expect if a customer was exempt from vat/tax then all prices would show without vat/tax. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by peterfabian** [comment]
See #21292.
