### ISSUE TITLE
The standard fields in the Woo Commerce to Salesforce integration does not include the billing fields.  It lists the billing fields heading but does not list any of the actual billing fields.

### ISSUE THREAD

**Issue by roverdude64** [woocommerce/woocommerce#21097]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by peterfabian** [comment]
Hi, 

As Salesforce integration is not part of WooCommerce core, I'm afraid we can't really help you. I assume you're probably using a plugin or some kind of automation tool like Zapier? If you find a bug in WooCommerce core, don't hesitate to open a new issue, please include the steps to reproduce the problem and we will have a look at your report.

Thanks.
