### ISSUE TITLE
Remove all *.min.js versions of scripts

### ISSUE THREAD

**Issue by manake** [woocommerce/woocommerce#21096]
**Is your feature request related to a problem? Please describe.**
WooCommerce and its extensions bundle and load *.min.js versions of scripts but there is no reason for that. It only adds more files to the WooCommerce package. It's hard to edit the files in extensions when they add .min files.

**Describe the solution you'd like**
Remove all *.min.js versions of scripts from WooCommerce and prohibit them in all extensions.

WordPress, themes and plugins should not bundle or load any *.min.js files. This is a task of plugins, CloudFlare and CDNs. They all have capabilities of minifying scripts and we (users and developers) prefer that they minify things so that we're left with small size download package and 1 JS file to modify.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by kloon** [comment]
Minimizing files reduces their size and aid in helping sites load faster on production. You should never make changes to extension/theme files anyway as your changes will be overwritten when you update, it is always better to rather dequeue the files and enqueue your own copy from a location outside of the theme/plugin.

For contributing and troubleshooting we include the original unminified files as well which you can actually load when you define the SCRIPT_DEBUG constant as true in your wp-config.php file.

**Comment by rodrigoprimo** [comment]
I personally think that removing minified files from the repository is something that we should do and there is already an issue to refactor JS that includes it: https://github.com/woocommerce/woocommerce/issues/18395

This change is not currently in our roadmap, but it is one of the most voted feature requests so it is probably something that we will work on in the future.

**Comment by rodrigoprimo** [comment]
I just realized that I might have misunderstood this issue, we are considering removing minified files from the repository and not from WooCommerce releases. If we remove those files from the repository, we will generate the minified files in a build script, and the WooCommerce package will ship with them.
