### ISSUE TITLE
product calendar disappeared from the cart

### ISSUE THREAD

**Issue by marwasaaid** [woocommerce/woocommerce#21094]
Hello,
After updating my theme and woocommerce plugin,
the calendar associated to each product on the cart has disappeared.
This led to getting errors on orders, because it come without specific dates.
Any idea about this issue, please.

This is my cart with the issue:

![image](https://user-images.githubusercontent.com/42501580/44303203-da422a00-a33a-11e8-8ab9-176cec590d7a.png)

This is the normal cart that should appear:

![image](https://user-images.githubusercontent.com/42501580/44303227-8c79f180-a33b-11e8-922a-3e3be907ec9b.png)

This is the error code I get in the user account "order view" page. :

Notice: order_date was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/entrada/page.php'), get_template_part, locate_template, load_template, require('/themes/entrada/template-parts/content-page.php'), the_content, apply_filters('the_content'), WP_Hook->apply_filters, do_shortcode, preg_replace_callback, do_shortcode_tag, WC_Shortcodes::my_account, WC_Shortcodes::shortcode_wrapper, WC_Shortcode_My_Account::output, WC_Shortcode_My_Account::my_account, wc_get_template, include('/themes/entrada/woocommerce/myaccount/my-account.php'), do_action('woocommerce_account_content'), WP_Hook->do_action, WP_Hook->apply_filters, woocommerce_account_content, do_action('woocommerce_account_view-order_endpoint'), WP_Hook->do_action, WP_Hook->apply_filters, woocommerce_account_view_order, WC_Shortcode_My_Account::view_order, wc_get_template, include('/themes/entrada/woocommerce/myaccount/vi in /home/tourexegypt/public_html/wp-includes/functions.php on line 4161

**Comment by peterfabian** [comment]
Hi, 

the date selection for a product does not look like a WooCommerce core feature, so I'm afraid we can't really help you. If this functionality comes from [WooCommerce Bookings](https://woocommerce.com/products/woocommerce-bookings/), please [contact the support](https://woocommerce.com/contact-us/). If this is a 3rd party plugin, please reach out to the plugin author.

If you believe this is a bug in WooCommerce core, don't hesitate to create a new issue and please include the relevant information, including [System status report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) and steps to reproduce the problem on a WordPress installation with only WooCommerce plugin active, using the Storefront theme.

Thanks.
