### ISSUE TITLE
Possible slashing issue within tax fields.

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce#21107]
**Describe the bug**
Adding an apostrophe ( **'** ) to the city column within **Taxes > Standard Rates** causes a backslash to show upon saving.

![Screenshot](http://cld.wthms.co/Wx6qiH+)
Image Link: http://cld.wthms.co/Wx6qiH

**Comment by peterfabian** [comment]
See https://github.com/woocommerce/woocommerce/pull/21205.
