### ISSUE TITLE
max_allowed_packet after import of products - CPU stuck

### ISSUE THREAD

**Issue by grosssmutttr** [woocommerce/woocommerce#21100]
**Describe the bug**
While importing many products in a foreach statement the cpu fills up to 100% because of huge transients creations/updates/deletes.

So we are adding attributes and images as well but in short we are doing the following:
```

     foreach ($import_articles as $article) {
try {
        if ($article_type === 'simple') {
            if (empty($existing_wc_product_id) || $existing_wc_product_id <= 0) {
                $wc_product = new WC_Product_Simple();
                $wc_product->set_status('draft');
                 $wc_product->set_name($article_name);
                $wc_product->set_sku($article_sku);
                 $wc_product->set_short_description($article_short_desc);
                $wc_product->set_description($article_long_desc);
               $wc_product->set_price($article_price);
               $wc_product->set_regular_price($article_price);
                $wc_product->set_manage_stock(false);
               $wc_product->set_stock_status('instock');
               $wc_product->set_gallery_image_ids($gallery_image_ids);
                $wc_product_id = $wc_product->save();
             }
      }
} catch (Exception $ex) {
        write_log($ex->getMessage() . ' - sku: ' . $article_sku);
    }
 }
```

**Details:**
WordPress 4.9.8 
WooCommerce Version 3.4.4
12 Cores
36 GB RAM
SSD
max_allowed_packet set to 50 MB

If we set the max_allowed_packet to 200 MB the error doesn't occur but the import is getting really slow.
So for the first 50 products it needs about 20 minutes, for the next 50 it needs an hour and this is increasing exponentially.

The "prefix_options" table is increasing constantly with all these transients entries.

[proxy_fcgi:error] [pid 1557:tid 139961567274752] Got a packet bigger than 'max_allowed_packet' bytes f\xc3\xbcr Abfrage UPDATE `pef_options` SET `option_value` = 'a:6091:{i:1533885849;a:1:{s:28:\\"woocommerce_cleanup_sessions\\";a:1:{s:32:\\"40cd750bba9870f18aada2478b24840a\\";a:3:{s:8:\\"schedule\\";s:10:\\"twicedaily\\";s:4:\\"args\\";a:0:{}s:8:\\"interval\\";i:43200;}}}i:1533886581;a:1:{s:25:\\"delete_version_transients\\";a:1:{s:32:\\"8165c286e121ad181aa3a4d53a1d9e98\\";a:2:{s:8:\\"schedule\\";b:0;s:4:\\"args\\";a:1:{i:0;s:10:\\"1533886551\\";}}}}i:1533886583;a:1:{s:25:\\"delete_version_transients\\";a:1:{s:32:\\"07006b365c44a870541c4f56960fe504\\";a:2:{s:8:\\"schedule\\";b:0;s:4:\\"args\\";a:1:{i:0;s:10:\\"1533886553\\";}}}}i:1533886584;a:1:{s:25:\\"delete_version_transients\\";a:1:{s:32:\\"9c254a225ee7e2d3f8b5fc4eb2de79f8\\";a:2:{s:8:\\"schedule\\";b:0;s:4:\\"args\\";a:1:{i:0;s:10:\\"1533886554\\";}}}}i:1533886586;a:1:{s:25:\\"delete_version_transients\\";a:1:{s:32:\\"f1999f25443b43fea401c2a3b7813b9f\\";a:2:{s:8:\\"schedule\\";b:0;s:4:\\"args\\";a:1:{i:0;s:10:\\...\nPHP message: PHP Warning:  Error while sending QUERY packet. PID=51770 in /var/www/vhosts/mywebsite.com/httpdocs/wp-includes/wp-db.php on line 1924\n', referer: https://mywebsite.com/wp-cron.php?doing_wp_cron=1533899202.9100770950317382812500

So we are trying to import 20 000 products (also including variable products with variations).

I don't know what the intension of this wp-cron is - perhaps it is to cleanup the transients and wordpress couldn't handle it because there are too many transients in the prefix_options table?

As I'm debugging since 2 days and I have no solution found on how to avoid the cpu running out of power and getting the error mentioned above perhaps there is a woocommerce dev who simply sees the mistake and could improve this transients error source.

**Comment by grosssmutttr** [comment]
Just saw that it creates transients entries which all are in the past:

Example:
_transient_timeout_wc_term_counts | 1537365890

GMT: Wednesday, 19. September 2018 14:04:50
Your time zone: Mittwoch, 19. September 2018 16:04:50 GMT+02:00 DST

This was yesterday - so why are these transients created?

**Comment by rodrigoprimo** [comment]
This is likely the same issue that I briefly mentioned in this comment:

https://github.com/woocommerce/wc-smooth-generator/issues/14#issuecomment-413342136

This is the commit that I believe introduced this issue:

https://github.com/woocommerce/woocommerce/commit/2f8a3eae49949c9957d3408213b1339f12019498

It is on my list to work on a solution to this problem. Meanwhile, could you please test if commenting out the following line solves the issue for you?

https://github.com/woocommerce/woocommerce/blob/2f8a3eae49949c9957d3408213b1339f12019498/includes/class-wc-cache-helper.php#L155

This will stop WooCommerce from enqueueing a few cron events per product created. Just make sure to clear all transients after you are done importing products.

**Comment by rodrigoprimo** [comment]
See #21282

**Comment by seldimi** [comment]
> This is likely the same issue that I briefly mentioned in this comment:
> 
> [woocommerce/wc-smooth-generator#14 (comment)](https://github.com/woocommerce/wc-smooth-generator/issues/14#issuecomment-413342136)
> 
> This is the commit that I believe introduced this issue:
> 
> [2f8a3ea](https://github.com/woocommerce/woocommerce/commit/2f8a3eae49949c9957d3408213b1339f12019498)
> 
> It is on my list to work on a solution to this problem. Meanwhile, could you please test if commenting out the following line solves the issue for you?
> 
> [woocommerce/includes/class-wc-cache-helper.php](https://github.com/woocommerce/woocommerce/blob/2f8a3eae49949c9957d3408213b1339f12019498/includes/class-wc-cache-helper.php#L155)
> 
> Line 155 in [2f8a3ea](/woocommerce/woocommerce/commit/2f8a3eae49949c9957d3408213b1339f12019498)
> 
>  			wp_schedule_single_event( time() + 30, 'delete_version_transients', array( $version ) ); 
> This will stop WooCommerce from enqueueing a few cron events per product created. Just make sure to clear all transients after you are done importing products.

I have doen the above and commented everything related to delete_transients but I still get my wp_option('cron') flooded for some reason. I have even removed it from DB, but in a second or two, it re-appears.

My tem solution was to put on functions.php delete_option('cron') but its not ideal!

**Comment by pirex360** [comment]
I have the same issue.... saving products using WC_Product::save() method takes about 15 seconds per product in my case.
Note that i also save the images... about 4 images per product and wordpress is a lot slow to integrate a image in his library.

Without images my overall average is 3 seconds per product.



I too need to optimize this, i am building a plugin to read products from a webservice... and sync with woocommerce.

I read the webservice, its about 3MB Json file in 4-5 seconds... but saving the products...is a nightmare, i dont get it !!!



Tips that make a difference in my case:

- when creating product categories use first : wp_defer_term_counting(true); - this disable interactive counting for products in product categories (save me 1a2 seconds for each product)

- only after adding all the products, count and update the product categories numbers.

- when import a image... use :add_filter('jpeg_quality', function($arg){return 100;});
this stops image manipulation by WP, but you will not get lower image size optimization

- after all products import i put back in default : add_filter('jpeg_quality', function($arg){return 80;});

Has anybody pass for the same thing in WC/WP ?
