### ISSUE TITLE
Cart cookies will set 3 times on add-to-cart

### ISSUE THREAD

**Issue by danielhuesken** [woocommerce/woocommerce#21101]
**Describe the bug**
We have got a security audit for a WooCommerce installation. There was a message that the cookies will be set multiple times with different values.

They say:
Risk: If sensitive information in server responses is stored in the local browser’s cache, then this may be retrieved by other users who have access to the same computer at a future time.
Recommendation: Ensure that cookies are only sent once. If this is not possible, ensure the cookies always have the same values and flags set.

Headers off test installation:
![cart_cookies](https://user-images.githubusercontent.com/741847/44330773-29d24400-a468-11e8-8fb9-3ca1b67cedfc.PNG)

**To Reproduce**
Do a request to a existing product like: http://wc.localhost/product/test1/add-to-cart=1234

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

I can see on https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cart-session.php#L49-L54 that the `maybe_set_cart_cookies` method will be called 3 times if a product added to cart. Is this realy nessesary? The `woocommerce_add_to_cart` cart action produces the difference for the `woocommerce_cart_hash` cookie value. The `wp` and `shutdown` actions came allways after that action.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22666

**Comment by mklepaczewski** [comment]
@mikejolley Can we reopen the issue as #23355 reverted the #22666 fix?

**Comment by mklepaczewski** [comment]
RFC 6265 states that:

> Servers SHOULD NOT include more than one Set-Cookie header field in the same response with the same cookie-name.

**Comment by jonathan-dejong** [comment]
We've found that this is still an issue today so yes please reopen @mikejolley ?

**Comment by jassriver** [comment]
still an issue..

**Comment by andyhird** [comment]
Hi there, this is still an issue in 2024. Can this be reopened please.

**Comment by jonathan-dejong** [comment]
For those that just needs a solution now I would have liked to make this an open github repo but I don't have the time atm :) 
I'll come back here once that exists.. But here's the basic functionality that we made to resolve this as an MU plugin:

```<?php
/**
 * Plugin Name: Qala WooCommerce Cookie Handler
 * Description: A solution to poorly handled cookies in WooCommerce.
 * Author:      Angrycreative
 * Version:     0.0.3
 * License:     GNU General Public License v3 or later
 * License URI: http://www.gnu.org/licenses/gpl-3.0.html
 */

namespace qalaWoocommerceCookieHandler;

// Basic security, prevents file from being loaded directly.
if ( ! defined( 'ABSPATH' ) ) {
	die( 'Cheating uh?' );
}

class CookieHandler {
	/**
	 * Register the hooks.
	 *
	 * @return void
	 */
	public function __construct() {
		add_action( 'woocommerce_set_cart_cookies', [ $this, 'reset_cookies' ] );
	}

	/**
	 * reset_cookies
	 *
	 * When adding too many products to the cart at the same time, Varnish was returning a 503
	 * because the header response was too large due to duplicate cookies. This function
	 * checks for unique cookies, removes all Set-Cookie headers, and sets the unique ones.
	 *
	 * Ref to related Github issue https://github.com/woocommerce/woocommerce/issues/21101
	 *
	 * @param $set
	 * @return void
	 */
	public function reset_cookies( $set ) : void {
		// If the headers are already sent, then we are too late and should stop.
		if ( headers_sent() ) {
			return;
		}

		// Get all the Set-Cookie headers and make a list of unique cookies.
		$headers = headers_list();
		$cookies = [];
		foreach ( $headers as $header ) {
			list($key, $value) = explode( ': ', $header );
			if ( 'Set-Cookie' === $key ) {
				list($ckey, $cval) = explode( '=', $value );
				$cookies[ $ckey ]  = $value;
			}
		}

		// Remove all Set-Cookie headers and re-set the unique Set-Cookie headers.
		header_remove( 'Set-Cookie' );
		foreach ( $cookies as $cookie ) {
			header( 'Set-Cookie: ' . $cookie, false );
		}
	}
}

new CookieHandler();
```

We've had this running on a bunch of WC sites for years now without issues.
