### ISSUE TITLE
How to use WooCoomerce REST API on ports non 80?

### ISSUE THREAD

**Issue by lai32290** [woocommerce/woocommerce#21113]
I'm working on WordPress on my localhost port 8000 and I really can't to use port 80.

In the case, is there any way that I can set WC Rest API to request on port 8000?

**Comment by rodrigoprimo** [comment]
I'm sorry but we don't use GitHub issues for support, we use it exclusively for WooCommerce bugs, enhancements and feature requests. If you need support, you could try WooCommerce support forums on WordPress.org (https://wordpress.org/support/plugin/woocommerce).

You could also check the API documentation in case you haven't already: https://woocommerce.github.io/woocommerce-rest-api-docs/. I'm not sure if it mentions how to use the API when WordPress is running on a non-standard port, but I would assume that all you need to do is specify the port in the request URL:

https://localhost:8000/wp-json/wc/v2/orders

**Comment by lai32290** [comment]
That's weird, because I've tried to set the URl with port like:
```
<?php
require __DIR__ . '/vendor/autoload.php';

use Automattic\WooCommerce\Client;

$woocommerce = new Client(
    'http://localhost:8000', 
    'ck_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 
    'cs_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    [
        'wp_api' => true,
        'version' => 'wc/v2',
    ]
);
```

But it doesn't work to me, only works if my host port is 80

**Comment by rodrigoprimo** [comment]
@lai32290, I didn't realize you were using the WC API PHP Client (https://github.com/woocommerce/wc-api-php). I don't know how to specify a port using this client. The example I gave was using a client like Insomnia.
