### ISSUE TITLE
Phone number does not pass to PayPal Guest Checkout

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce#21110]
**Describe the bug**
Using PayPal Standard the phone number filled out on the checkout page isn't passed to PayPal guest checkout.

**To Reproduce**
1. Prefill checkout page fields
2. Choose PayPal Standard payment option and Proceed to PayPal
3. Select the **Pay with Debit or Credit Card** button on PayPal login page
4. See error no phone number is added to PayPal Guest Checkout fields.

**Screenshots**
![Screenshot](http://cld.wthms.co/gtkMxf+)
Image Link: http://cld.wthms.co/gtkMxf

**Comment by peterfabian** [comment]
Just tested this and I'm not sure we can do much about this. 

Our code generates a URL that the customer is redirected to and the information is included correctly according to [PayPal's documentation](https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/#auto-fill-paypal-checkout-page-variables). 

PayPal seems to ignore country and phone number from the request.

Example request: 
```
https://www.sandbox.paypal.com/cgi-bin/webscr?test_ipn=1&cmd=_cart&business=peter.fabian1000%2Buspaypaltest%40gmail.com&no_note=1&currency_code=EUR&charset=utf-8&rm=1&upload=1&return=http%3A%2F%2Flocal.wordpress.test%2Fcheckout%2Forder-received%2F1241%2F%3Fkey%3Dwc_order_5b97ba4bdcb58%26utm_nooverride%3D1&cancel_return=http%3A%2F%2Flocal.wordpress.test%2Fcart%2F%3Fcancel_order%3Dtrue%26order%3Dwc_order_5b97ba4bdcb58%26order_id%3D1241%26redirect%26_wpnonce%3D2b1f3d719c&page_style=&image_url=&paymentaction=sale&bn=WooThemes_Cart&invoice=WC-LOCALTEST1241&custom=%7B%22order_id%22%3A1241%2C%22order_key%22%3A%22wc_order_5b97ba4bdcb58%22%7D&notify_url=http%3A%2F%2Flocal.wordpress.test%2Fwc-api%2FWC_Gateway_Paypal%2F&first_name=Pedro&last_name=Vedro&address1=Old+road+123&address2=&city=London&state=&zip=WC2N+5DU&country=GB&email=test%40test.test&night_phone_b=1234567&address_override=0&no_shipping=0&shipping_1=5.40&item_name_1=Cap+x+1&quantity_1=1&amount_1=16&item_number_1=1241
```
You can see `country=GB` towards the end and also `night_phone_b=1234567`, as supplied on the checkout form, but not reflected in PayPal:
![paypal_info_missing](https://user-images.githubusercontent.com/2207451/45361582-e8e6ce80-b5d2-11e8-90bf-35208645f45a.png)

I also tried a similar request for customer from the US, where the phone number gets split into `night_phone_a`, `night_phone_b` and `night_phone_c`, but it does not get transferred either.

**Comment by peterfabian** [comment]
Okay, I actually made it working by entering phone number in the following format for US:
"123 456 78901", then this gets split as following:
- `night_phone_a=234`
- `night_phone_b=567` 
- `night_phone_c=8901`

**Comment by peterfabian** [comment]
Tried the following for a new UK paypal developer account, none of these worked:
- `night_phone_a=44&night_phone_b=12345678`
- `night_phone_a=044&night_phone_b=12345678`
- `night_phone_a=+44&night_phone_b=12345678`
- `night_phone_b=12345678`
- `night_phone_b=4412345678`
- `night_phone_b=+4412345678`
- `night_phone_b=04412345678`

but maybe that's because the country is not selected correctly, even though correct country code is sent to PayPal, so I'm not sure how to fix it at the moment.

**Comment by peterfabian** [comment]
@johndcoy what was the test number you used?

**Comment by peterfabian** [comment]
It's a bit confusing. Seems like it might depend on cookies as well, sometimes both country and phone number goes through ok. 
Additionally, at times, 'Pay with Debit or Credit Card' button is not available at all...

**Comment by johndcoy** [comment]
Sure! I used 1231231234, just like that. No symbols.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22693
