### ISSUE TITLE
[REST API] Adding and removing coupons from orders, with calculation

### ISSUE THREAD

**Issue by claudiosanches** [woocommerce/woocommerce#21119]
See https://github.com/woocommerce/wc-api-dev/issues/78

**Comment by kloon** [comment]
See #21327

**Comment by guilhermelirio** [comment]
Awesome! But, works to create a order, or only update?

**Comment by anoblet** [comment]
@claudiosanches @kloon Is there any way to implement this on the `subscriptions` endpoint?
