### ISSUE TITLE
[REST API] Shipping lines instance ID

### ISSUE THREAD

**Issue by claudiosanches** [woocommerce/woocommerce#21116]
See https://github.com/woocommerce/wc-api-dev/issues/113

**Comment by peterfabian** [comment]
Isn't this already in place?

![instance_id](https://user-images.githubusercontent.com/2207451/45218194-051efe80-b2a7-11e8-8d2e-29bc78f9c371.png)

**Comment by claudiosanches** [comment]
Missing on schema.

**Comment by obiebrown** [comment]
Is this fixed or how do I fix this?
As I am having this exact problem I can not set the "instance_id" when creating orders via API.
created_via rest-api
version 3.8.1

As this talks about 3.5.0 API and I am using 3.8.1 API I can not see why this would not work.
Any help would be greatly appreciated.
