### ISSUE TITLE
[REST API] Reports counts endpoint

### ISSUE THREAD

**Issue by claudiosanches** [woocommerce/woocommerce#21115]
Endpoint to list total of:

- [x] Orders by status
- [x] Products by type
- [x] Customers (paying customer or not)
- [x] Coupons
- [x] Reviews

**Comment by claudiosanches** [comment]
We already return total of products in categories, tags and attributes, like in `/wp-json/wc/v3/products/categories`.

**Comment by claudiulodro** [comment]
#21306
