### ISSUE TITLE
Breadcrumb's structured data are missing link for last item

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce#21112]
**Describe the bug**

The last item of the breadcrumb is missing the link in the structured data. It can be seen also on WooCommerce.com.

**To Reproduce**
1. Go to any product page on a site
2. View Source
3. Search for BreadcrumbList
4. See the error in the last item, having the ID not set to a URL.

**Screenshots**

![](http://d.wedj.at/sm6iQ2+)
**Image Link**: http://d.wedj.at/sm6iQ2+

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

Reported in #1360092-zen

**Comment by rodrigoprimo** [comment]
Coincidentally, I also noticed this yesterday and opened #21111 which should fix this problem. I don't know much about Structured Data so would be great if you could test my PR.
