### ISSUE TITLE
Upsells and Cross-sells  search on large database not working  

### ISSUE THREAD

**Issue by AbdulSamadKt** [woocommerce/woocommerce#21147]
When searching for products in Upsells or Cross-sells fields, the search is taking infinite time with a database size of 50MB. I have copied the website to my localhost. I am getting the same error on localhost  but when I change the database to a fresh one in wp-config.php file with same WordPress files, I am getting results for that ajax search as normal. 

**To Reproduce**
1. Go to 'single product page' from backend
2. Click on 'Linked Products' tab
3. Search for a product on either upsells or cross-sells search fields
4. The search takes infinite time

**Expected behavior**
Products list for matching the search term 

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: http://localhost/test2
Site URL: http://localhost/test2
WC Version: 3.4.4
Log Directory Writable: ❌ To allow logging
make C:\wamp\www\test2/wp-content/uploads/wc-logs/ writable or define a custom WC_LOG_DIR.

WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.9 (Win64) PHP/5.5.12
PHP Version: 5.5.12 - ❌ WooCommerce will run under this version of PHP
however
it has reached end of life. We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version

PHP Post Max Size: 3 MB
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.36.0
OpenSSL/1.0.1g

SUHOSIN Installed: –
MySQL Version: 5.6.17
Max Upload Size: 3 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from https://dev.maxmind.com/geoip/geoip2/geolite2/ to the path: . Scroll down to "Downloads" and download the "MaxMind DB binary
gzipped" file next to "GeoLite2 Country". Please remember to uncompress GeoLite2-Country_xxxxxxxx.tar.gz and upload the GeoLite2-Country.mmdb file only.

Total Database Size: 3.06MB
Database Data Size: 2.12MB
Database Index Size: 0.94MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_ewwwio_images: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.48MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

page: 3
post: 2
product: 12

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.4.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Shopkeeper
Version: 2.6.2
Author URL: https://www.getbowtied.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: shopkeeper/woocommerce/archive-product.php
shopkeeper/woocommerce/cart\cart-empty.php
shopkeeper/woocommerce/cart\mini-cart.php
shopkeeper/woocommerce/checkout\form-coupon.php
shopkeeper/woocommerce/checkout\form-login.php
shopkeeper/woocommerce/content-product.php
shopkeeper/woocommerce/content-product_cat.php
shopkeeper/woocommerce/content-single-product.php
shopkeeper/woocommerce/global\quantity-input.php
shopkeeper/woocommerce/global\sidebar.php
shopkeeper/woocommerce/global\wrapper-end.php
shopkeeper/woocommerce/global\wrapper-start.php
shopkeeper/woocommerce/loop\loop-end.php
shopkeeper/woocommerce/loop\loop-start.php
shopkeeper/woocommerce/loop\no-products-found.php
shopkeeper/woocommerce/myaccount\form-login.php
shopkeeper/woocommerce/order\form-tracking.php
shopkeeper/woocommerce/single-product\product-image.php
shopkeeper/woocommerce/single-product\product-thumbnails.php
shopkeeper/woocommerce/single-product\tabs\tabs.php
shopkeeper/woocommerce/single-product.php

`
```
</details>

**Comment by rodrigoprimo** [comment]
I don't believe the size of the database is the issue here. 50MB is a fairly small size. The size of one of the databases that I use to test WooCommerce on my local environment is 52GB, and the upsells and cross-sells search works as expected (although a bit slow).

Could you please elaborate on what you mean when you say that the search is taking an infinite time? Maybe you are getting an error back from the AJAX request used to search for products, and the error is not being handled by WooCommerce? If that is the case, could you please share what the response you get is? Or the AJAX request never completes?

I see that you are using a theme called Shopkeeper. Are you able to reproduce this issue using Storefront or one of the default WordPress themes?

Thanks

**Comment by AbdulSamadKt** [comment]
I am able to reproduce this issue with default theme also. 

Here is a screenshot of that ajax request with pending status. On the screenshot, you can see '0 B transferred'.  After a very long time, I am getting 404 error.  

![pasted_image_at_2018 08 21__7_24_pm](https://user-images.githubusercontent.com/18283199/44406369-15ca3780-a579-11e8-95a2-9f44386b3a5c.png)

**Comment by peterfabian** [comment]
this actually sounds quite similar to https://github.com/woocommerce/woocommerce/issues/21102

**Comment by kloon** [comment]
@AbdulSamadKt could you also provide what is shown in the response tab of the network request if any?

**Comment by AbdulSamadKt** [comment]
response tab is empty.

**Comment by kloon** [comment]
@AbdulSamadKt we found in #21102 that there might have been a query termination happening. Can you check your error logs? Particularly your mysql logs as that might give a clue.

**Comment by AbdulSamadKt** [comment]
I didn't get those errors. My database is MyISAM. Do you think that makes problem?  Do I have to change to InnoDB?

**Comment by AbdulSamadKt** [comment]
@kloon I found the product search in WordPress backend also very slow. I got the search result after a very long time. 
On query monitor plugin, when I search for a product in the backend, found the following query is very slow

Query: 
SELECT DISTINCT posts.ID as product_id, posts.post_parent as parent_id
FROM wp_posts posts 
LEFT JOIN wp_postmeta postmeta
ON posts.ID = postmeta.post_id 
WHERE posts.post_type IN ('product','product_variation') 
AND ( ( ( posts.post_title LIKE '%ray%')
OR ( posts.post_excerpt LIKE '%ray%')
OR ( posts.post_content LIKE '%ray%' )
OR ( postmeta.meta_key = '_sku'
AND postmeta.meta_value LIKE '%ray%' ) )) 
ORDER BY posts.post_parent ASC, posts.post_title ASC

Caller:
WC_Product_Data_Store_CPT->search_products()

Component:
Plugin: woocommerce

Rows
16

Time
323.1190

When I delete the wp_postmeta table data, I got search results at normal speed.

**Comment by AbdulSamadKt** [comment]
I have found the issue myself. The issue was with the index of wp_postmeta table. Primary key and index were lost somehow. So I give index to post_id and meta_key so the search is working now on linked product tab and on default product search.

Thanks for your valuable time.

**Comment by Kamalsurya** [comment]
Hi, My ajax request is working and returning data. But it is not returning the searched item in the upsells or cross-sells. Search is working for most of the items but not on some items/products. 
Can someone help on this.

wp-admin/admin-ajax.php?term=wlche100&action=woocommerce_json_search_products_and_variations&security=776c198c1d&exclude=25702
