### ISSUE TITLE
Google's new Breadcrumb requirement

### ISSUE THREAD

**Issue by sybrew** [woocommerce/woocommerce#21152]
**Describe the bug**
Google's Structured Data Testing Tool now (since ~4 days) tells testers to add the `@id` attribute to every breadcrumb item.

Now, the last breadcrumb (the visited product page) misses this attribute.

https://search.google.com/structured-data/testing-tool/

**To Reproduce**
1. Go to any product page.
2. Copy the URL of the page.
3. Paste it into the testing tool, and Run Test.
4. See error.

**Screenshots**
![image](https://user-images.githubusercontent.com/7662236/44438417-3ddc8980-a5bf-11e8-8433-c3e25aff583f.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only [the] WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
WC 3.4.4 |
WP 4.9.8
```
</details>

**Comment by kloon** [comment]
See #21111 for fix.

**Comment by salman-github** [comment]
Hello everyone,
I had the same issue. I'm using Woocommerce 3.4.5 with storefront theme. 

![screenshot 322](https://user-images.githubusercontent.com/42977864/45049060-1f848c80-b09b-11e8-849b-b4bf31327f19.png)

I used the following code in functions.php and it fixed the issue. But I'm waiting for a permanent fix in the next update. 

```
function remove_output_structured_data() {
  remove_action( 'wp_footer', array( WC()->structured_data, 'output_structured_data' ), 10 ); // Frontend pages
}
add_action( 'init', 'remove_output_structured_data' );
```

![screenshot 324](https://user-images.githubusercontent.com/42977864/45049344-f6b0c700-b09b-11e8-93d4-7a190daeca96.png)


![screenshot 323](https://user-images.githubusercontent.com/42977864/45049088-332ff300-b09b-11e8-8675-e62409b70f92.png)

**Comment by claudiulodro** [comment]
#21111
