### ISSUE TITLE
Filtering results doesn't load the correct thumbnail for variations

### ISSUE THREAD

**Issue by manake** [woocommerce/woocommerce#21151]
**Describe the bug**
I have a variable product that is "black" by default with uploaded "black" main picture and it has "white" variation with uploaded "white" picture.

On the shop page when I filter by "white" filter then the product's thumbnail should be set to that of variation ("white") and not default "black".

**To Reproduce**
1. Create a product called "Product  X" with "black" and "white" attributes used for variations.
2. Upload "black" picture for the main image.
3. Upload "white" picture for the variation.
4. Go to the shop page and filter products to show only "white" color.
5. "Product X" is among the results (this is correct) but it has "black" thumbnail (this is not correct)!

This is rather bad as any visitor thinks why there is a bug in this store and "white" filters shows some "black" images.

I think this is a serious issue, it creates a lot of confusion when most of my client's products come with multiple colors.

I think it should be fixed in core or if not then an official code snippet should be provided to filter and update that.

**Screenshots**
N/A

**Expected behavior**
If a variation has uploaded picture then the shop page should show that picture during filtering if the selected filters better match that picture.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by manake** [comment]
`return apply_filters( 'woocommerce_product_get_image', $image, $this, $size, $attr, $placeholder, $image );` has `$image` twice in abstract-wc-product.php.

**Comment by claudiulodro** [comment]
Hi,

This is currently a 'wontfix' item - I'll briefly explain why it's not possible to do this at this point.

Attributes (your colors) are terms.
- The terms are not directly tied to a 'variation', they are tied to a parent variable product.
- When querying products using widgets like layered nav, they look at the parents only. They cannot look at the variations because the variations are not assigned to the term.
- Since the query cannot look at the variation, it cannot check its image and display it.

In the future we may try to revisit this, but as it stands, looping over all variations during layered nav queries would be a massive bottleneck and would cause too large of a performance issue to warrant it's inclusion. It may be possible once product tables are in WooCommerce core, but right now it's not possible. Hope you understand.

Thanks.

**Comment by claudiulodro** [comment]
> return apply_filters( 'woocommerce_product_get_image', $image, $this, $size, $attr, $placeholder, $image ); has $image twice in abstract-wc-product.php.

Correct. [This is for backwards compatibility and the second `$image` will be removed in the future](https://github.com/woocommerce/woocommerce/pull/19934#pullrequestreview-118091057).

**Comment by manake** [comment]
Thanks for the response. I understand but...

No, visitors and my client don't understand and will never accept such response.

If I will forward this to them then they will call me a bad developer and fire me.

(And of course they are calling WooCommerce a bad platform every time I tell them that something is a WooCommerce bad design decision they are saying that maybe we should switch to Shopify or something else.)

They (rightfully) see this as a serious issue that makes everyone confused and they demand a fix.

So now I have to waste time and investigate WooCommerce core and consider many things to fix this because there is no solution.

This issue affects many stores, it's clearly a bug.

Maybe issue a temporary fix in your docs?

Thanks for your consideration.

P.S.
It's the same story with URLs like `https://apple.com/product-category/macbook` (WooCommerce generated URL) versus `https://apple.com/macbook` (a URL that is acutally needed). If I'm working for some solid company then it MUST be `https://apple.com/macbook/` or I'm a bad developer and they will find someone else who can make it `https://apple.com/macbook/`.

Please consider that we need solutions for people and they don't care that there is some limitation. They only care that it must make sense.

This page should be updated to contain the actual workaround/solution: https://docs.woocommerce.com/document/removing-product-product-category-or-shop-from-the-urls/

**Comment by peterfabian** [comment]
Not saying I tested this thoroughly or that all the sanitization is in place, but this approach might work:

1. You need a way to get correct variations, with possibly not specifying all attributes. Function `WC_Product_Data_Store_CPT::find_matching_product_variation` could do it, but it exits early when only a subset of attributes are specified. Therefore, if you create a very similar function, just allow it to use subset of attributes and return the first matching variation, you can end up with something like:
```
	public function find_partial_matching_product_variation( $product, $match_attributes = array() ) {
		$query_args = array(
			'post_parent' => $product->get_id(),
			'post_type'   => 'product_variation',
			'orderby'     => 'menu_order',
			'order'       => 'ASC',
			'fields'      => 'ids',
			'post_status' => 'publish',
			'numberposts' => 1,
			'meta_query'  => array(), // phpcs:ignore WordPress.VIP.SlowDBQuery.slow_db_query_meta_query
		);

		// Allow large queries in case user has many variations or attributes.
		$GLOBALS['wpdb']->query( 'SET SESSION SQL_BIG_SELECTS=1' );

		foreach ( $product->get_attributes() as $attribute ) {
			if ( ! $attribute->get_variation() ) {
				continue;
			}

			$attribute_field_name = 'attribute_' . sanitize_title( $attribute->get_name() );

			if ( ! isset( $match_attributes[ $attribute_field_name ] ) ) {
				continue; // this has been changed
			}

			// Note not wc_clean here to prevent removal of entities.
			$value = $match_attributes[ $attribute_field_name ];

			$query_args['meta_query'][] = array(
				'relation' => 'OR',
				array(
					'key'     => $attribute_field_name,
					'value'   => array( '', $value ),
					'compare' => 'IN',
				),
				array(
					'key'     => $attribute_field_name,
					'compare' => 'NOT EXISTS',
				),
			);
		}

		$variations = get_posts( $query_args );

		if ( $variations && ! is_wp_error( $variations ) ) {
			return current( $variations );
		} elseif ( version_compare( get_post_meta( $product->get_id(), '_product_version', true ), '2.4.0', '<' ) ) {
			/**
			 * Pre 2.4 handling where 'slugs' were saved instead of the full text attribute.
			 * Fallback is here because there are cases where data will be 'synced' but the product version will remain the same.
			 */
			return ( array_map( 'sanitize_title', $match_attributes ) === $match_attributes ) ? 0 : $this->find_matching_product_variation( $product, array_map( 'sanitize_title', $match_attributes ) );
		}

		return 0;
	}
```

2. Then, you can override the template function `woocommerce_get_product_thumbnail` in `includes/wc-template-functions.php` to get the image from the first matching variation, e.g.
```
function woocommerce_get_product_thumbnail( $size = 'woocommerce_thumbnail', $deprecated1 = 0, $deprecated2 = 0 ) {
		global $product;

		$image_size = apply_filters( 'single_product_archive_thumbnail_size', $size );

		// Translate filter_ to attribute_pa_.
		$filters              = array();
		$filter_prefix_length = strlen( 'filter_' );
		foreach ( $_REQUEST as $key => $value ) {
			if ( 0 === strpos( $key, 'filter' ) ) {
				$filters[ 'attribute_pa_' . substr( $key, $filter_prefix_length ) ] = $value;
			}
		}

		if ( count( $filters ) > 0 && is_a( $product, 'WC_Product_Variable' ) ) {
			$data_store   = WC_Data_Store::load( 'product' );
			$variation_id = $data_store->find_partial_matching_product_variation( $product, wp_unslash( $filters ) );
			$variation    = $variation_id ? new WC_Product_Variation( $variation_id ) : false;
			if ( $variation ) {
				return $variation->get_image( $image_size );
			}
		}

		return $product ? $product->get_image( $image_size ) : '';
	}
```
