### ISSUE TITLE
comments_popup_link disappears when WooCommerce enabled when WC support not declared

### ISSUE THREAD

**Issue by laurelfulford** [woocommerce/woocommerce#21161]
This is a duplicate of #20806, but with a different context. I thought it would make sense to open a new issue for it, but let me know if it’s better to reopen that one, and continue the discussion there! 

**Describe the bug**
When WooCommerce is enabled with a theme that doesn’t include `add_theme_support( 'woocommerce' );`,  comment counts no longer appear. 

**To Reproduce**
1. On a Business Plan WP.com site or self-hosted site, install a WordPress.com-theme that doesn't declare WooCommerce support (three from the above ticket include DailyMag, Dynamic News and Aquene, but I'm happy to provide others).
2. Make sure WooCommerce plugin is disabled.
3. View a post with comments and note where the theme displays the comment count.
4. Enable the WooCommerce plugin.
5. See that the comment count disappears.

**Expected behavior**
That the comment count would continue to show. 

**Screenshots**
This is from DailyMag:
![](https://cldup.com/fOkJRuZahb.png)

**Context**
We have a theme report related to this issue from a WP.com Business Plan site (2402-wpcom-premium-themes). This would also affect any other site using WooCommerce and one of the WP.com themes that doesn't declare support for it. 

We typically point users to one of our WC-supporting theme if their current theme does not handle WooCommerce-specific features well. But in this case, that seems like an odd solution, since the feature that stops working is in the blog. Is there another way to get these themes displaying the comment count with WooCommerce enabled?

**Edited to add:** I belatedly realized this was also discussed in #20140 --- please let me know if I should reopen that one and close this.

**Comment by claudiulodro** [comment]
Let's go with this issue instead of the other one, as your description of the problem is better. :)

I was able to reproduce this with a theme that doesn't declare WooCommerce support. The comment count should only be suppressed on WooCommerce pages on unsupported themes.

**Comment by claudiulodro** [comment]
#21191
