### ISSUE TITLE
On Sale doesn't work

### ISSUE THREAD

**Issue by kreativdenker** [woocommerce/woocommerce#21169]
**Describe the bug**
If you use the On Sale Shortcode, different products are displayed. However, not those products that have an offer price. Normal products and variants of products are shown. However, no discounted products.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by claudiulodro** [comment]
Hi there,

I tried the `[sale_products]` and  `[products on_sale="true"]` shortcodes on a site running only WooCommerce and both of those only displayed products that were on sale in my testing. If you have more information that can help us reproduce the issue please share it, but in the absence of further information I have to close this as non-reproducible. 

Thanks.

**Comment by maxbeech** [comment]
I think I might have worked out why this was hapenning. If you have just loaded a theme with some sample products on sale, you need to go into those products are hit the `Update` button for them to show up under the sale page.

**Comment by maxbeech** [comment]
I think I might have worked out why this was happening. If you have just loaded a theme with some sample products on sale, you need to go into those products are hit the Update button for them to show up under the sale page.
