### ISSUE TITLE
State IS mandatory but shown as optional

### ISSUE THREAD

**Issue by cristianciuberea** [woocommerce/woocommerce#21160]
Hi,

The state is mandatory but it is shown as optional 

Here's a printscreen http://prntscr.com/klsyqa

Thank you

**Comment by claudiulodro** [comment]
[According to Wikipedia](https://en.wikipedia.org/wiki/Address_(geography)#Romania), it looks like you are correct. It's been this way in WooCommerce for 7+ years. We'll make this change for version 3.5.

**Comment by cristianciuberea** [comment]
haha. cool :D

**Comment by kloon** [comment]
See #21180
