### ISSUE TITLE
Changing address in My Account does not reflect in Order

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce#21179]
1367802-zen

**Describe the bug**

User goes to My Account > Addresses and changes billing or shipping addresses. Admin checks order in backend (this one has not shipped/completed yet) and the change is not 

**To Reproduce**
1. Purchase a product so order is created
2. Go to My Account > Addresses page and make changes to existing address info
3. As admin, in the order on the backend, check if addresses have been changed
4. No change. Does update in customer's profile.

**Screenshots**
![](http://cld.wthms.co/TG3GYp+)
Link to screenshot: http://cld.wthms.co/TG3GYp

DOesn't chnage in backend:

![](http://cld.wthms.co/rljKUP+)
Link to screenshot: http://cld.wthms.co/rljKUP

**Expected behavior**
I'd expect it would change, esp if order has not been fulfilled yet....though this is a part "Question" bug report and wondering if the above is the expected behavior since order was already placed?

WC 3.4.4 only

**Comment by kloon** [comment]
This is intended, you cannot change existing order details when you change addresses or billing details on my account. Once you place/create an order with details that's the details that will be used for that order, automatically changing the address or billing details for existing orders have implications with shipping and even tax filing.
