### ISSUE TITLE
/checkout/ make <h3> be <h2> in the form

### ISSUE THREAD

**Issue by manake** [woocommerce/woocommerce#21173]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It's inconsistent with the rest of WordPress when the checkout form doesn't have `<h2>` tags but it starts with `<h3>`.

**Comment by rianrietveld** [comment]
+1 for making the heading order semantically right.
But upgrading the H3s to H2s will influence the way the headings are displayed and will have an impact on existing designs and that's not really a good idea IMHO.

One solution could be to add a visually hidden H2 heading above the form, with a title like for example:
`<h2 class="screen-reader-text">Your details and order</h2>
`
The `.screen-reader-text` class is present in the Woo CSS and will hide an element from vision, but will keep it in the HTML5. That way the heading structure will stay logical for screen reader users and search engines.

**Comment by willgorham** [comment]
This will definitely cause backwards compatible styling issues because those headings have no classes - forcing users to style them based on tag.

**Comment by manake** [comment]
I know it will.

How about using flags for all such features:
`add_theme_support( 'new-improvement' )`

And in the next major release the previous version would be removed.

Otherwise it will always stay at `<h3>` (which is not a bug but it's inconsistent) and more people will come here to report this sooner or later.

**Comment by kloon** [comment]
This is a breaking change and can only be considered for a major release, which the next one will be 4.0.

Thanks for the suggestion and seems there are some interest in this so we will table it for possible inclusion in the next major release.
