### ISSUE TITLE
New JS events when recalculating order totals in Edit Order page

### ISSUE THREAD

**Issue by daigo75** [woocommerce/woocommerce#21181]
**Current status**
A solution I developed to handle EU taxes needs to perform actions on the UI of Edit Order page (e.g. block elements, show information, etc), when the order totals are being recalculated. Currently, the JavaScript doesn't fire any event to intercept that operation.

**Solution**
I would propose to add a few JS events before and after the order total recalculation, so that they can be intercepted by 3rd parties. Specifically:
* `order-totals-recalculate-before`, before the Ajax request is fired.
* `order-totals-recalculate-success`, on the jQuery.ajax "success" event.
* `order-totals-recalculate-complete`, on the jQuery.ajax "complete" event.

These events will grant more flexibility, while keeping the original logic unchanged.

Pull request to follow.

**Comment by claudiulodro** [comment]
#21183
