### ISSUE TITLE
Remove esc_html() from filter woocommerce_rating_filter_count

### ISSUE THREAD

**Issue by manake** [woocommerce/woocommerce#21196]
`$count_html  = esc_html( apply_filters( 'woocommerce_rating_filter_count', "({$count})", $count, $rating ) );` in class-wc-widget-rating-filter.php should not have `esc_html` because it prevents wrapping the count in any `span`.

I think you meant to use `wp_kses()` which allows some HTML?

**Comment by manake** [comment]
Also, count should not be preceded by space on this line:

`printf( '<li class="%s"><a href="%s"><span class="star-rating">%s</span> %s</a></li>', esc_attr( $class ), esc_url( $link ), $rating_html, $count_html ); // WPCS: XSS ok.`

This is probably a good default (although it doesn't allow reordering HTML elements) (maybe this part should have a filter):
`printf( '<li class="%s"><a href="%s"><span class="star-rating">%s</span><span class="count">%s</span></a></li>', esc_attr( $class ), esc_url( $link ), $rating_html, $count_html ); // WPCS: XSS ok.`

**Comment by kloon** [comment]
See #21904 for fix.
