### ISSUE TITLE
Help text "leave blank to use the parent product's options" is wrong

### ISSUE THREAD

**Issue by gerdneuman** [woocommerce/woocommerce#21197]
**Steps to reproduce the behavior:**
1. I wanted to remove all stock management from a variable product.
2. Went to stock management tab of the parent product and unticked stock management.
3. Went to stock management of each variant.
4. Read the help text: "Enter a quantity to enable stock management at variation level, or leave blank to use the parent product's options."
5. Changed the number in the field to blank

See: 

https://github.com/woocommerce/woocommerce/blob/dc191b58a4f685a6ad42b9d4798c9fb8bc1d58ff/includes/admin/meta-boxes/views/html-variation-admin.php#L173

**Actual behavior:**
After saving there is always a `0` then the variant's stock management field, meaning "sold out" to the customer.

Turned out (took my a lot of playing around) that `leaving blank` is totally wrong, instead I had to untick the `Enable stock management` checkbox at the topbar of each variant.

**Expected behavior:**
The help text about "leave blank" is plain wrong. Maybe better: "Enter the variant's stock quantity. You can enable/disable stock management for the variant above, or use the prent product's options under the distinctive parent product's tab".

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by peterfabian** [comment]
Thanks for reporting. You're right. Even more so, that the field cannot really be left blank--it becomes 0 as soon as the user saves the changes, so any subsequent changes to variations means it's set to 0.

**Comment by peterfabian** [comment]
See https://github.com/woocommerce/woocommerce/pull/21204.
