### ISSUE TITLE
Update status change other settings

### ISSUE THREAD

**Issue by sebastianpisula** [woocommerce/woocommerce#21209]
When I buy products with more quantity value and run the script below then item quantities will change for 1. I think it is a bug because I update only order status using update_status() method. I think items quantities should be updated only when I use save() method.
    
    add_action( 'init', function () {
        $order = wc_get_order( 279 );
        $items = $order->get_items();

        foreach ( $items as $item ) {
            $item['qty'] = 1;
        }

        $order->update_status( 'pending', 'note' );
    } );

**Comment by claudiulodro** [comment]
It's not a bug. The method description explicitly says ["Updates status of order immediately"](https://github.com/woocommerce/woocommerce/blob/d0491072e8a7d0a4535db0ec2bae4a6d43ff64fd/includes/class-wc-order.php#L305). You can use [set_status](https://github.com/woocommerce/woocommerce/blob/d0491072e8a7d0a4535db0ec2bae4a6d43ff64fd/includes/class-wc-order.php#L254) if you don't want the automatic saving.
