### ISSUE TITLE
Attribute filter ignores WooCommerce Brands filter

### ISSUE THREAD

**Issue by eovel** [woocommerce/woocommerce#21201]
**Describe the bug**
When selecting an attribute in the WooCommerce attribute filter, brands get limited to those left available in the filtered result. Vice versa however, when selecting a brand, the WooCommerce attribute filter completely ignores the WooCommerce Brands filter and displays wrong results.

**To Reproduce**

1. Install WooCommerce Brands
2. Add attributes and brands to some products in a category
3. Assign an attribute filter and a brand filter widget to the sidebar
4. Navigate to said category in the frontend
5. Select a brand in the filter

**Screenshots**
Correct behavior from the WooCommerce Brands plugin after selecting an attribute:
![correct](https://user-images.githubusercontent.com/33128507/44655348-12a9ce00-a9f5-11e8-8900-1afd6104ca6b.png)

Wrong behavior from the WooCommerce Core after selecting a brand:
![wrong](https://user-images.githubusercontent.com/33128507/44655396-3bca5e80-a9f5-11e8-8b0b-2d4a1d3e1919.png)

**Expected behavior**
After selecting a brand, the WooCommerce attribute filter should process the brands filter and limit it's displayed results correctly.

**WordPress Environment**
3.4.4

**WooCommerce Brands Environment**
1.6.2

**Comment by peterfabian** [comment]
Hi, 

sorry, I don't really understand in what way is the behaviour incorrect, can you maybe elaborate a bit? Not sure if the products are simple or variable, I tried both types and added filters for brand & size, it seems to work ok. 

One thing I noticed, though, is that the core widget resets the filter set by Brands widget, i.e.
 
1. click on brand=Kappa, 
2. click on Size=medium
=> results in filter for size=medium, so the brand filter to get removed, 

while if done in the opposite order:
1. click on Size=medium
2. click on brand=Kappa
=> results in filter size=medium && brand=Kappa.

Is this the problem or is there something else you had in mind?

**Comment by eovel** [comment]
Hi @peterfabian 

I'll try explaining the issue by referencing to the second screenshot I've posted where I have selected the brand Alpha. As you can see all attributes (Länge) are still shown and indicate that there's 1 result for every option in the currently filtered result. However this is **not true**. The product shown (Album) has the attribute value of 30. Therefore the options 10 and 40 should not be displayed anymore OR have an indicator of 0 results. 

This works the other way around (when selecting an attribute first). The brands that are not included in the result anymore get removed.

Regarding your statement: Yes, clicking on an attribute resets the brand filter.

I hope this is a bit more clear for you to understand.

**Comment by claudiulodro** [comment]
Hi there.

Thanks for clarifying the issue. 

I recommend [contacting support](https://woocommerce.com/my-account/create-a-ticket/) and they can forward this bug to the WooCommerce Brands developers. 

We can't do anything about this in the WooCommerce core plugin in much the same way WordPress core can't change to accommodate a specific plugin. If the WooCommerce Brands plugin is not working correctly when combined with the WooCommerce filter widget, it is up to the WooCommerce Brands developers to ensure their features work on WooCommerce. Hope this clears things up.

Thanks.

**Comment by eovel** [comment]
Thank you @claudiulodro 

I thought this would be in the core developer's hands to fix, as changes seemed to be done in the core widget filter. Usually this wouldn't be done for external components I agree, but since it's an official WooCommerce extension, I thought compatibility should be granted in the core files.
I've forwarded this thread to the support team as suggested by you and hope they'll be able to adjust their plugin accordingly so it works as intended.

Thank you for the feedback.
