### ISSUE TITLE
Price filtering min/max issue with tax exclusive prices

### ISSUE THREAD

**Issue by RistoNiinemets** [woocommerce/woocommerce#21203]
**Describe the bug**
I've tested the current code and it seems that both "min" and "max" do not work properly in price filtering.

Inserting prices excluding tax
Showing prices including tax

Currently I have a category which has prices (without tax) from 227.55 to 1748.25. The price filter range widgets show range from 227 to 1749.
Tax is 20% to all products, so it would be 273.06 and 2097.9 accordingly.

When I submit price filter form without changing min/max values, so it would include full range (227-1749 via $_GET), price filter query sets SQL query as:
`( ( wp_postmeta.meta_key = '_price'
AND CAST(wp_postmeta.meta_value AS DECIMAL(10,2)) BETWEEN '272.4' AND '1399.2' ) )`

Minimum in 227 + 20% = 272.4, but as prices are entered without tax, it should be left as it, without any calculations. Not sure where the max value came, but here applies the same as min. So, I removed completely the extra calculation from `wc_get_min_max_price_meta_query()` and it now worked as supposed to:
https://github.com/woocommerce/woocommerce/blob/master/includes/wc-product-functions.php#L787-L807

After that, the query was:
`( ( wp_postmeta.meta_key = '_price'
AND CAST(wp_postmeta.meta_value AS DECIMAL(10,2)) BETWEEN '227' AND '1749' ) )`

Now both, minimum and maximum priced products were visible.

However, a completely different issue remains: price filter widget ranges are showing tax exclusive prices, so it is not respecting the settings.

I tried a quick fix to add taxes in price filter widget, and then in `wc_get_min_max_price_meta_query()` remove taxes for DB query, but tax calculation went wrong. So I tweaked tax calculation in 32ca6c7, but that didn't work as expected.

Related to PR #18174 and issue #18170.

**To Reproduce**
1. Insert prices excluding tax
2. Show prices including tax
3. Set up tax 20% for all products
4. Add price filtering widget

**Comment by kloon** [comment]
See #21942 for fix.
