### ISSUE TITLE
Conflict with Bootstrap 4.x

### ISSUE THREAD

**Issue by kowsar89** [woocommerce/woocommerce#21213]
New bootstrap 4+ has css class like this: col-1, col-2 etc

WooCommerce has the same css class ( eg col-1, col-2 etc ) used in checkout page. If any theme is built on Twitter Bootstrap 4+ then those css classes will make conflict and checkout page will be broken.

**Comment by claudiulodro** [comment]
WooCommerce has been around longer than Bootstrap's grid system, and the class names have to be kept for backwards compatibility. They may be updated in the future, but [there are some workarounds available in the meantime](https://github.com/woocommerce/woocommerce/issues/15793).
