### ISSUE TITLE
Regions text field not in line

### ISSUE THREAD

**Issue by rocketeer76** [woocommerce/woocommerce#21214]
**Describe the bug**
When adding a new shipping zone the Regions text field is not in line with Zone Name and Restrict by zip code.

**To Reproduce**
1. Go to shipping settings
2. Add a new shipping zone
3. See error

**Expected behavior**
Regions text field should be in line with the other fields.

**Comment by claudiulodro** [comment]
<img width="600" alt="screen shot 2018-08-28 at 1 34 18 pm" src="https://user-images.githubusercontent.com/7317227/44749354-186fe400-aac7-11e8-9eb0-0a6f13042eeb.png">

Either the other two fields need more interior padding or the regions field needs less interior padding. Thanks for the report.

**Comment by claudiulodro** [comment]
#21247
