### ISSUE TITLE
Bug in sale coupon restriction logic following the changes in #21219 

### ISSUE THREAD

**Issue by rynaldos** [woocommerce/woocommerce#21226]
Howdy!

WooCommerce will no longer, following the changes here (https://github.com/woocommerce/woocommerce/pull/21219) allow the use of the coupon with the item that is not on sale. Instead, it will remove the coupon and state the coupon cannot be used on a sale item even when one of the items in the cart is not a sale item

The issue initially surfaced here: https://wordpress.org/support/topic/current-release-3-4-5-breaks-coupons/#post-10639339

The user dug into this and found that the issue is with the `foreach` in `validate_coupon_sale_items` function, as we are not checking all items in the cart — as soon as we see an on-sale item, then we exit ( `break;` )

The code in question is in here: 

https://github.com/woocommerce/woocommerce/blob/76312d546f1acbf9caa0e9df55e9528f479dcc17/includes/class-wc-discounts.php#L766-L783

Cheers!

**Comment by claudiulodro** [comment]
Continuing discussion at #21227.
