### ISSUE TITLE
Improve `WC_Order::is_paid()` to not be solely determined by order's status

### ISSUE THREAD

**Issue by crstauf** [woocommerce/woocommerce#21223]
**Is your feature request related to a problem? Please describe.**
Using the order's status as the sole determining factor to whether the order has been paid is much too specific for custom use cases. An example is the _WooCommerce Anti-Fraud_ plugin, which set's an order's status to "on-hold" (for many reasons)... in that case, the order has technically already been paid for, but [`WC_Order::is_paid()`](https://docs.woocommerce.com/wc-apidocs/class-WC_Order.html#_is_paid) would return `false` because the order's status is "on-hold".

**Describe the solution you'd like**
Add an additional check to the `WC_Order::is_paid()` conditional, so that the order's status is not the single factor. I'm currently thinking checking `_date_paid` post meta could be sufficient, but will evaluate further.

**Comment by DavidAnderson684** [comment]
When a PayPal reversal occurs, funds are withdrawn from the seller, and WC puts the order 'on hold'. So in that case, the proposed change would wrongly give `true` rather than the current correct `false`.

**Comment by crstauf** [comment]
@DavidAnderson684 What are your thoughts on the function and its definition in general? It's (nearly) identical to `WC_Order::has_status( wc_get_is_paid_statuses() )`, which as described, does not accurately identify whether the order has been paid for.

**Comment by kloon** [comment]
IMO this is beyond core's functionality, core relies on order statuses to reflect if payment was made. These statuses get changed as refunds/returns etc happen. If a plugin like Anti-Fraud is modifying the behavior to not make use of the default payment statuses then it should hook into the woocommerce_order_is_paid filter and also include their functionality to make the order reflect that it was paid.

Order statuses should be sufficient for identifying whether an order is paid, perhaps Anti-Fraud should introduce their own status and add it as a paid status?

**Comment by crstauf** [comment]
@kloon Understood; I will submit the issue to the WooCommerce extensions team.
