### ISSUE TITLE
Issue on Product Listing with 'Related Products' Title distorted

### ISSUE THREAD

**Issue by Neenbeans** [woocommerce/woocommerce#21220]
I had disabled the review section within WooCommerce and it has now moved the title for 'Related Products' up the side of the product image. (As you can see below). It hasn't affected my other products for some reason. Please help!
![website issue](https://user-images.githubusercontent.com/42815712/44806794-cc549a80-abbf-11e8-802e-a44d37ae55c3.png)

**Comment by claudiulodro** [comment]
Hi there.

This is going to be a styling issue with the theme you are using. I recommend contacting the authors of the theme to make them aware of this issue. Closing this issue because it's not something we can solve in the WooCommerce plugin. Hope this clears things up.

Thanks.
