### ISSUE TITLE
Problem with Checkout

### ISSUE THREAD

**Issue by santyrubio** [woocommerce/woocommerce#21230]
Hello! Excuse my English, I am using a translator.
I have a problem with my site
When the client wants to pay, he is presented with an error that says "Invalid order".

Enable the log and it says the following:

[27-Aug-2018 22:49:32 UTC] PHP Fatal error:  Uncaught Exception: Producto no válido. in /home/santirub/public_html/cicade.com.ar/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php:149

Stack trace:
#0 /home/santirub/public_html/cicade.com.ar/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(156): WC_Product_Data_Store_CPT->read(Object(WC_Product))

#1 /home/santirub/public_html/cicade.com.ar/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php(133): WC_Data_Store->read(Object(WC_Product))

#2 /home/santirub/public_html/cicade.com.ar/wp-content/plugins/woocommerce-mercadopago/includes/WC_WooMercadoPago_BasicGateway.php(743): WC_Product->__construct(6231)

#3 /home/santirub/public_html/cicade.com.ar/wp-content/plugins/woocommerce-mercadopago/includes/WC_WooMercadoPago_BasicGateway.php(978): WC_WooMercadoPago_BasicGateway->build_payment_preference(Object(WC_Order))

#4 /home/santirub/public_html/cicade.com.ar/wp-content/plugins/woocommerce-mercadopago/includes/WC_WooMercadoPago_BasicGatewa in /home/santirub/public_html/cicade.com.ar/wp-content/plugins/woocommerce/includes/data-stores/class-wc-product-data-store-cpt.php on line 149

I need help please

**Comment by claudiulodro** [comment]
Hi there.

Does the product the customer is paying for still exist, or has it been deleted? The error logs show that the payment gateway is trying to load a product that does not exist, and that is causing errors. You'll have to contact the authors of the MercadoPago gateway (cc @claudiosanches), as this error is caused by code in the gateway. We can't fix it in the WooCommerce plugin. Hope this clears things up.

Thanks.

**Comment by santyrubio** [comment]
The product was not removed, it is strange because it uses an older version of woocommerce works, the problem is presented with the latest versions of the add-on, I need help please
