### ISSUE TITLE
WooCommerce randomly adding products to orders

### ISSUE THREAD

**Issue by willo-the-wisp** [woocommerce/woocommerce#21239]
My client has reported that their WooCommerce store occasionally adds extra items to orders.
These items DO NOT show up in the customer's basket (and were not added by the customer). The customer is charged the correct amount for the items they've ordered.
However, in the Orders page within WooCommerce, the extra items appear in the Order summary.

This does not happen with every order. It's not the same product which gets added every time, or the same number of products. We can't find any commonality at all between any of the orders.
We also can't reliably reproduce it. It happens on some orders and not others, apparently randomly.

As a background; this is a site that I've inherited from another developer. I've now taken over the site, moved it to a different server, and developed a custom theme for it. The client has had this problem for a long time - long before I took over. The old developer couldn't understand it either.

I've attached a screenshot showing an order which this has happened to today.
The top product, 115mm Fascia Brackets was NOT ordered.
The bottom 3 products *were* ordered. They add up to the correct total of £303.46 including the VAT. But the top product is an anomaly.
![image](https://user-images.githubusercontent.com/42866637/44911113-a513df80-ad1d-11e8-9251-2c8565bac0d3.png)

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: https://castironsuperstore.co.uk
Site URL: https://castironsuperstore.co.uk
WC Version: 3.4.3
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.0.31 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 512 MB
PHP Time Limit: 0
PHP Max Input Vars: 8000
cURL Version: 7.60.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 10.1.31-MariaDB-cll-lve
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.3
WC Database Prefix: wp_
Total Database Size: 57.47MB
Database Data Size: 42.09MB
Database Index Size: 15.38MB
wp_woocommerce_sessions: Data: 0.04MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 1.00MB + Index: 0.47MB
wp_woocommerce_order_itemmeta: Data: 6.35MB + Index: 4.43MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_comments: Data: 1.18MB + Index: 0.34MB
wp_layerslider: Data: 0.06MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_newsletter: Data: 0.00MB + Index: 0.00MB
wp_newsletter_emails: Data: 0.00MB + Index: 0.00MB
wp_newsletter_sent: Data: 0.00MB + Index: 0.00MB
wp_newsletter_stats: Data: 0.00MB + Index: 0.00MB
wp_newsletter_user_logs: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 1.81MB + Index: 0.15MB
wp_pmxe_exports: Data: 0.30MB + Index: 0.00MB
wp_pmxe_google_cats: Data: 0.26MB + Index: 0.05MB
wp_pmxe_posts: Data: 0.19MB + Index: 0.08MB
wp_pmxe_templates: Data: 0.01MB + Index: 0.00MB
wp_pmxi_files: Data: 0.01MB + Index: 0.00MB
wp_pmxi_history: Data: 0.01MB + Index: 0.00MB
wp_pmxi_images: Data: 0.05MB + Index: 0.00MB
wp_pmxi_imports: Data: 1.23MB + Index: 0.00MB
wp_pmxi_posts: Data: 1.01MB + Index: 0.82MB
wp_pmxi_templates: Data: 0.10MB + Index: 0.00MB
wp_postmeta: Data: 19.54MB + Index: 6.64MB
wp_posts: Data: 6.45MB + Index: 0.91MB
wp_revslider_css: Data: 0.01MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
wp_revslider_settings: Data: 0.00MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.00MB + Index: 0.00MB
wp_revslider_slides: Data: 0.00MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.01MB + Index: 0.03MB
wp_term_relationships: Data: 0.12MB + Index: 0.27MB
wp_term_taxonomy: Data: 0.01MB + Index: 0.01MB
wp_usermeta: Data: 0.96MB + Index: 0.61MB
wp_users: Data: 0.04MB + Index: 0.05MB
wp_vtprd_purchase_log: Data: 0.00MB + Index: 0.00MB
wp_vtprd_purchase_log_product: Data: 0.00MB + Index: 0.00MB
wp_vtprd_purchase_log_product_rule: Data: 0.00MB + Index: 0.00MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wfBadLeechers: Data: 0.00MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.00MB + Index: 0.00MB
wp_wfBlocks: Data: 0.00MB + Index: 0.00MB
wp_wfBlocksAdv: Data: 0.00MB + Index: 0.00MB
wp_wfConfig: Data: 0.01MB + Index: 0.01MB
wp_wfCrawlers: Data: 0.00MB + Index: 0.00MB
wp_wfFileMods: Data: 1.07MB + Index: 0.34MB
wp_wfHits: Data: 0.05MB + Index: 0.01MB
wp_wfHoover: Data: 0.00MB + Index: 0.00MB
wp_wfIssues: Data: 0.01MB + Index: 0.00MB
wp_wfLeechers: Data: 0.01MB + Index: 0.01MB
wp_wfLockedOut: Data: 0.00MB + Index: 0.00MB
wp_wfLocs: Data: 0.00MB + Index: 0.00MB
wp_wfLogins: Data: 0.04MB + Index: 0.01MB
wp_wfNet404s: Data: 0.00MB + Index: 0.00MB
wp_wfReverseCache: Data: 0.00MB + Index: 0.00MB
wp_wfScanners: Data: 0.00MB + Index: 0.00MB
wp_wfStatus: Data: 0.07MB + Index: 0.03MB
wp_wfThrottleLog: Data: 0.00MB + Index: 0.00MB
wp_wfVulnScanners: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_table_rates: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 2333
customize_changeset: 2
nav_menu_item: 52
page: 88
post: 2
postman_sent_mail: 217
product: 1028
product_variation: 1537
project: 21
revision: 747
shop_coupon: 1
shop_order: 823
sidebar: 1
woo_discount_cart: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

LayerSlider WP: by Kreatura Media – 6.0.5
Newsletter: by Stefano Lissa & The Newsletter Team – 5.6.1
Postman SMTP: by Jason Hendriks – 1.7.2
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.14.11

WooCommerce Product Feed: by WebAppick – 2.2.18 – Not tested with the active version of WooCommerce
Woo Discount Rules: by Flycart Technologies LLP – 1.6.8
WooCommerce WorldPay Gateway: by Add On Enterprises (Andrew Benbow) – 3.5.3 – 3.6.5 is available – Not tested with the active version of WooCommerce
WooCommerce Table Rate Shipping: by WooThemes – 3.0.1 – 3.0.9 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.4.3 – 3.4.5 is available
WordPress Importer: by wordpressdotorg – 0.6.4
WP All Export Pro: by Soflyy – 1.5.3
WP All Import Pro: by Soflyy – 4.5.4
WP All Import - User Import Add-On: by Soflyy – 1.1.1
WP All Import - WooCommerce Add-On Pro: by Soflyy – 2.4.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #10087 - /shop/
Basket: #10088 - /basket/
Checkout: #10089 - /checkout/
My account: #10090 - /my-account/
Terms and conditions: #3044 - /terms-and-conditions/

### Theme ###

Name: Cast Iron Superstore 2018
Version: 1.0
Author URL: https://www.redkiteit.co.uk
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: cis2018/woocommerce/archive-product.php version 3.3.0 is out of date. The core version is 3.4.0
cis2018/woocommerce/auth/footer.php
cis2018/woocommerce/auth/form-grant-access.php
cis2018/woocommerce/auth/form-login.php
cis2018/woocommerce/auth/header.php
cis2018/woocommerce/cart/cart-empty.php
cis2018/woocommerce/cart/cart-item-data.php
cis2018/woocommerce/cart/cart-shipping.php
cis2018/woocommerce/cart/cart-totals.php
cis2018/woocommerce/cart/cart.php
cis2018/woocommerce/cart/cross-sells.php
cis2018/woocommerce/cart/mini-cart.php
cis2018/woocommerce/cart/proceed-to-checkout-button.php
cis2018/woocommerce/cart/shipping-calculator.php
cis2018/woocommerce/checkout/cart-errors.php
cis2018/woocommerce/checkout/form-billing.php
cis2018/woocommerce/checkout/form-checkout.php
cis2018/woocommerce/checkout/form-coupon.php
cis2018/woocommerce/checkout/form-login.php
cis2018/woocommerce/checkout/form-pay.php
cis2018/woocommerce/checkout/form-shipping.php
cis2018/woocommerce/checkout/order-receipt.php
cis2018/woocommerce/checkout/payment-method.php
cis2018/woocommerce/checkout/payment.php
cis2018/woocommerce/checkout/review-order.php
cis2018/woocommerce/checkout/terms.php
cis2018/woocommerce/checkout/thankyou.php
cis2018/woocommerce/content-product.php
cis2018/woocommerce/content-product_cat.php
cis2018/woocommerce/content-single-product.php
cis2018/woocommerce/content-widget-product.php
cis2018/woocommerce/content-widget-reviews.php
cis2018/woocommerce/emails/admin-cancelled-order.php
cis2018/woocommerce/emails/admin-failed-order.php
cis2018/woocommerce/emails/admin-new-order.php
cis2018/woocommerce/emails/customer-completed-order.php
cis2018/woocommerce/emails/customer-invoice.php
cis2018/woocommerce/emails/customer-new-account.php
cis2018/woocommerce/emails/customer-note.php
cis2018/woocommerce/emails/customer-on-hold-order.php
cis2018/woocommerce/emails/customer-processing-order.php
cis2018/woocommerce/emails/customer-refunded-order.php
cis2018/woocommerce/emails/customer-reset-password.php
cis2018/woocommerce/emails/email-addresses.php
cis2018/woocommerce/emails/email-customer-details.php
cis2018/woocommerce/emails/email-downloads.php
cis2018/woocommerce/emails/email-footer.php
cis2018/woocommerce/emails/email-header.php
cis2018/woocommerce/emails/email-order-details.php
cis2018/woocommerce/emails/email-order-items.php
cis2018/woocommerce/emails/email-styles.php
cis2018/woocommerce/emails/plain/admin-cancelled-order.php
cis2018/woocommerce/emails/plain/admin-failed-order.php
cis2018/woocommerce/emails/plain/admin-new-order.php
cis2018/woocommerce/emails/plain/customer-completed-order.php
cis2018/woocommerce/emails/plain/customer-invoice.php
cis2018/woocommerce/emails/plain/customer-new-account.php
cis2018/woocommerce/emails/plain/customer-note.php
cis2018/woocommerce/emails/plain/customer-on-hold-order.php
cis2018/woocommerce/emails/plain/customer-processing-order.php
cis2018/woocommerce/emails/plain/customer-refunded-order.php
cis2018/woocommerce/emails/plain/customer-reset-password.php
cis2018/woocommerce/emails/plain/email-addresses.php
cis2018/woocommerce/emails/plain/email-customer-details.php
cis2018/woocommerce/emails/plain/email-downloads.php
cis2018/woocommerce/emails/plain/email-order-details.php
cis2018/woocommerce/emails/plain/email-order-items.php
cis2018/woocommerce/global/breadcrumb.php
cis2018/woocommerce/global/form-login.php
cis2018/woocommerce/global/quantity-input.php
cis2018/woocommerce/global/sidebar.php
cis2018/woocommerce/global/wrapper-end.php
cis2018/woocommerce/global/wrapper-start.php
cis2018/woocommerce/loop/add-to-cart.php
cis2018/woocommerce/loop/loop-end.php
cis2018/woocommerce/loop/loop-start.php
cis2018/woocommerce/loop/no-products-found.php
cis2018/woocommerce/loop/orderby.php
cis2018/woocommerce/loop/pagination.php
cis2018/woocommerce/loop/price.php
cis2018/woocommerce/loop/rating.php
cis2018/woocommerce/loop/result-count.php
cis2018/woocommerce/loop/sale-flash.php
cis2018/woocommerce/myaccount/dashboard.php
cis2018/woocommerce/myaccount/downloads.php
cis2018/woocommerce/myaccount/form-add-payment-method.php
cis2018/woocommerce/myaccount/form-edit-account.php
cis2018/woocommerce/myaccount/form-edit-address.php
cis2018/woocommerce/myaccount/form-login.php
cis2018/woocommerce/myaccount/form-lost-password.php
cis2018/woocommerce/myaccount/form-reset-password.php
cis2018/woocommerce/myaccount/lost-password-confirmation.php
cis2018/woocommerce/myaccount/my-account.php
cis2018/woocommerce/myaccount/my-address.php
cis2018/woocommerce/myaccount/my-downloads.php
cis2018/woocommerce/myaccount/my-orders.php
cis2018/woocommerce/myaccount/navigation.php
cis2018/woocommerce/myaccount/orders.php
cis2018/woocommerce/myaccount/payment-methods.php
cis2018/woocommerce/myaccount/view-order.php
cis2018/woocommerce/notices/error.php
cis2018/woocommerce/notices/notice.php
cis2018/woocommerce/notices/success.php
cis2018/woocommerce/order/form-tracking.php
cis2018/woocommerce/order/order-again.php
cis2018/woocommerce/order/order-details-customer.php
cis2018/woocommerce/order/order-details-item.php
cis2018/woocommerce/order/order-details.php
cis2018/woocommerce/order/order-downloads.php
cis2018/woocommerce/order/tracking.php
cis2018/woocommerce/product-searchform.php
cis2018/woocommerce/single-product/add-to-cart/external.php
cis2018/woocommerce/single-product/add-to-cart/grouped.php
cis2018/woocommerce/single-product/add-to-cart/simple.php
cis2018/woocommerce/single-product/add-to-cart/variable.php
cis2018/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
cis2018/woocommerce/single-product/add-to-cart/variation.php
cis2018/woocommerce/single-product/meta.php
cis2018/woocommerce/single-product/photoswipe.php
cis2018/woocommerce/single-product/price.php
cis2018/woocommerce/single-product/product-attributes.php
cis2018/woocommerce/single-product/product-image.php
cis2018/woocommerce/single-product/product-thumbnails.php
cis2018/woocommerce/single-product/rating.php
cis2018/woocommerce/single-product/related.php
cis2018/woocommerce/single-product/review-meta.php
cis2018/woocommerce/single-product/review-rating.php
cis2018/woocommerce/single-product/review.php
cis2018/woocommerce/single-product/sale-flash.php
cis2018/woocommerce/single-product/share.php
cis2018/woocommerce/single-product/short-description.php
cis2018/woocommerce/single-product/stock.php
cis2018/woocommerce/single-product/tabs/additional-information.php
cis2018/woocommerce/single-product/tabs/description.php
cis2018/woocommerce/single-product/tabs/tabs.php
cis2018/woocommerce/single-product/title.php
cis2018/woocommerce/single-product/up-sells.php
cis2018/woocommerce/single-product-reviews.php
cis2018/woocommerce/single-product.php
cis2018/woocommerce/taxonomy-product_cat.php
cis2018/woocommerce/taxonomy-product_tag.php

Outdated Templates: ❌
					
					
						Learn how to update
`
```
</details>

**Comment by peterfabian** [comment]
Hi, 

Can you maybe check this bug report if the symptoms are similar? https://github.com/woocommerce/woocommerce/issues/17660

E.g. is the product added to order X missing from order X-1 or X+1?

**Comment by willo-the-wisp** [comment]
I've just found this issue which is similar: https://github.com/woocommerce/woocommerce/issues/15671

**Comment by willo-the-wisp** [comment]
For anyone else with this problem, I worked it out with a lot of assistance from WooCommerce Happiness Engineer, Etienne!
The previous muppet developers had 'accidentally' deleted a load of records relating to orders from the posts table, but there were still lots of related records in the order_items table. So the IDs had become way out of sync. That was the root of the problem.
To resolve it, I got the highest ID from the order_items table, then set the index of the wp_posts table to order_items.ID+1. This resolved the problem! Just in case it helps anyone else (take a DB backup before you do ANYTHING).

**Comment by andreastannah** [comment]
Hi I am having this issue with Wordpress 4.9.8 after upgrade, at first the issue was sporadic but now every order. The website only has one product but every order that is created has an extra product added (which I guess must be an old version of the product as it has the same name but old price). The customer is charged the correct amount. Have tried all the usual disabling plugins, caching etc. Am reluctant to try the fix above because to my knowledge nobody has been meddling with the database in the past. Any one found the problem or a fix?

**Comment by peterfabian** [comment]
If it's happening for each order, then it should be easier to reproduce for us. Please [create a new issue](https://github.com/woocommerce/woocommerce/issues/new/choose) and fill in the template for bug report, if you haven't done that already.

**Comment by diamondes3** [comment]
> For anyone else with this problem, I worked it out with a lot of assistance from WooCommerce Happiness Engineer, Etienne!
> The previous muppet developers had 'accidentally' deleted a load of records relating to orders from the posts table, but there were still lots of related records in the order_items table. So the IDs had become way out of sync. That was the root of the problem.
> To resolve it, I got the highest ID from the order_items table, then set the index of the wp_posts table to order_items.ID+1. This resolved the problem! Just in case it helps anyone else (take a DB backup before you do ANYTHING).

Wilo - Could you elaborate on how you set the index of the `wp_posts` table?  Is their a UI interface or did you do this via TSQL?

**Comment by baderdevgit** [comment]
Hey, I'm pretty much experiencing the same issue @willo-the-wisp, I know its been a while since you've had this issue but how exactly did you 'set the index of the wp_posts table' in phpmyadmin? Do you mean set the next created post ID to that order_id+1?

**Comment by baderdevgit** [comment]
It looks like that was exactly the issue. For the longest time I was convinced it was a caching issue but the post table's id was wayy behind the order_items id. All I needed to do was reset the AUTO_INCREMENT value for the posts table by performing: `ALTER TABLE ldd_posts AUTO_INCREMENT = whatever your max order_items id is + 1`

**Comment by adamxwr** [comment]
Hi, I seem to be having this issue also where a product (the exact same product) is being added to every order received! Not visible in the customers basket but visiable in the admin...also seeing a duplicate of the postage amount! Please could you let me know exactly how you reset the table to fix...I have access to phpmyadmin but need some guidance. Thank you.

**Comment by baderdevgit** [comment]
> rodu

Hey there, we had a couple products being added to random orders, not the same product being added to every order so it might be a different issue. For us one of our developers imported WooCommerce orders using two different plugins which set the post table's value to a value way less than the highest existing order_items id which was causing woocommerce to add random products from previous orders where the current order's id matched the old order's order_items id. I believe your issue might be unrelated.

**Comment by adamxwr** [comment]
ok im not sure either to be honest, my order numbers are at #7500 and my post ids are at 2000 so thought this was similar? I have check through files, turned plugins off and reverted to default thems but every order has the same product added in line 1 and an additional postage line if 2 items were order.

**Comment by baderdevgit** [comment]
I would take a backup before doing this, but it try setting your next post id to your highest order_item id + 1. My guess is that the order is adding products from older orders. The sql command is in a previous message but Ill paste it again here `ALTER TABLE ldd_posts AUTO_INCREMENT = whatever your max order_items id is + 1` so I guess in your case it would be 7501

**Comment by adamxwr** [comment]
Hi, thank you I will give this a try.... Please could you confirm the command 'ldd_posts' in correct and not a spelling error?
ALTER TABLE ldd_posts AUTO_INCREMENT = whatever your max order_items id is + 1 so I guess in your case it would be 7501

**Comment by baderdevgit** [comment]
Thats just the name of a particular site's post table. You should replace that with whatever your database'
s post table is named.

**Comment by adamxwr** [comment]
Hi, I have tried this however im not getting any results when running the code, the report is;

MySQL returned an empty result set (i.e. zero rows). (Query took 0.0051 seconds.)
ALTER TABLE 'example'_posts AUTO_INCREMENT = 2581

Am I doing something wrong?
wp_posts = 7002
order_items_id = 2580

**Comment by bigonlocal** [comment]
Hi
If the Posts ID is far greater than the order_items ID
can you set the AUTO_INCREMENT the opposite way ie on example above

MySQL returned an empty result set (i.e. zero rows). (Query took 0.0051 seconds.)
ALTER TABLE 'example'_posts AUTO_INCREMENT = 2581

Am I doing something wrong?
wp_posts = 7002
order_items_id = 2580

the order_items_id set to 7001

NB - MySQL returned an empty result set (i.e. zero rows). (Query took 0.0051 seconds.) - you can set the ID lower than it already is

**Comment by misteraitch1** [comment]
We are having the same issue. When a customer adds an item to their basket an additional product (always the same one so far) is added at checkout although they are not charged for it. Following the thread I have checked the database but I am unclear about which fields to look at. 

In the table xxxx_posts, latest post ID  is 17352. 
In the table xxxx_woocommerce_order_items, order_item_ID for the latest post is 621, and order_ID for the latest post is 17920

Which ID do I need to alter to fix the problem?
All help appreciated!!
