### ISSUE TITLE
Product classes

### ISSUE THREAD

**Issue by Trafikbyran** [woocommerce/woocommerce#21238]
in wc_get_product_class this part dosen't seem to work as explained.

// Include attributes and any extra taxonomy.
if ( apply_filters( 'woocommerce_get_product_class_include_taxonomies', false ) ) {
	$taxonomies = get_taxonomies( array( 'public' => true ) );
	foreach ( (array) $taxonomies as $taxonomy ) {
		if ( is_object_in_taxonomy( $post->post_type, $taxonomy ) && in_array( $taxonomy, array( 'product_cat', 'product_tag' ), true ) ) {
			$classes = array_merge( $classes, wc_get_product_taxonomy_class( (array) get_the_terms( $post->ID, $taxonomy ), $taxonomy ) );
		}
	}
}

// Categories.
$classes = array_merge( $classes, wc_get_product_taxonomy_class( $product->get_category_ids(), 'product_cat' ) );

// Tags.
$classes = array_merge( $classes, wc_get_product_taxonomy_class( $product->get_tag_ids(), 'product_tag' ) );

shouldn't the "&&" in "&& in_array( $taxonomy, array( 'product_cat', 'product_tag' ), true )" be "&!" so that it checks for taxanomies that isn't the regular ones?

**Comment by peterfabian** [comment]
Hi, 

I think you're right, good find. E.g. if I set a shipping class for a product and filter `woocommerce_get_product_class_include_taxonomies` to return true, the shipping class is not included in the list of classes.

Would you like to create a Pull Request to fix the problem?

Thanks.

**Comment by Trafikbyran** [comment]
Pull Request posted. 
I belive that this function could be done better.
Maybe the filter could have an option to controll the array of ( 'product_cat', 'product_tag') so that if you have multiple custom taxonomies on a product but only want one of them to be listed as classes then you have that option.

**Comment by dcelsey** [comment]
Thanks for finding that one - I use the product taxonomy classes for specific css styling and was trying to work out how to get them back. I found the filter but couldn't get it to work either. 

Here is a workaround if needed by anyone else finding this thread - it should add the taxomony classes back into post objects. Add to functions.php

`add_filter ('post_class' , 'my_post_class',10,3);

function my_post_class($classes, $class, $post_id)
{
	if(get_post_type($post_id) == 'product')
	{
		$post = get_post($post_id);
		
		$taxonomies = get_taxonomies( array( 'public' => true ) );
		foreach ( (array) $taxonomies as $taxonomy ) {
		  if ( is_object_in_taxonomy( $post->post_type, $taxonomy ) & !in_array( $taxonomy, array( 'product_cat', 'product_tag' ), true ) ) {
			$classes = array_merge( $classes, wc_get_product_taxonomy_class( (array) get_the_terms( $post->ID, $taxonomy ), $taxonomy ) );
		  }
		}	
	}
	
	return $classes;
}`

**Comment by claudiulodro** [comment]
https://github.com/woocommerce/woocommerce/pull/21381
