### ISSUE TITLE
Base64 images is filtering, when editing products with api

### ISSUE THREAD

**Issue by davutkara** [woocommerce/woocommerce#21246]
**Describe the bug**
I use woocommerce api with nodejs plugin, data comes clearly but, base64 image parts is filtering on woocommerce-wordpress side.

**To Reproduce**
I send data like this for description: `....src="data:image/png;base64,iVBO....`
But data is filtering, on wordpress-woocomerce side.
When I read data, it comes like this:  `....src="image/png;base64,iVBO....`
So image is broken.

**Expected behavior**
Dont filter `data:` text for base64 images.

**Comment by kloon** [comment]
This is probably related to #21259

**Comment by peterfabian** [comment]
It is a bit related. In this case, though, the data is removed before saving to the database. I would be inclined to remove the `wp_filter_post_kses` from `WC_REST_Products_Controller::prepare_object_for_database`, as e.g. when saving post in admin, this is not running either. However, it provides additional level of protection that could be useful. 
Opinions, @rodrigoprimo @claudiosanches ?

As an interim solution, perhaps adding a filter should do the trick:

```

function allow_data_protocol_urls( $allowed_protocols ) {
	return array_merge( $allowed_protocols, array( 'data' ) );
}

add_filter( 'kses_allowed_protocols', 'allow_data_protocol_urls', 10);


```

**Comment by rodrigoprimo** [comment]
Some background on why WP core does not allow data URI scheme:

https://core.trac.wordpress.org/ticket/19354

I'm inclined to think we shouldn't allow it as well as WP core doesn't but I don't know enough about it to be sure.
