### ISSUE TITLE
rtl emails get cropped in gmail on mobile

### ISSUE THREAD

**Issue by amirgroisman** [woocommerce/woocommerce#21250]
Hello,
I noticed that when I make a purchase and I get the order's receipt to my email, when the language is English the mail looks fine when my phone rotated horizontally and also when its vertical, but when I send the email in Hebrew which is rtl, the email gets cropped on vertical mode and I have to rotate the phone horizontally for the email to show as intended (and see all the details of the message).

I checked the email-styles.php and played a bit with the 'width' and 'min-width' property but I couldn't make any change.

Also, I noticed that when I send a couple of emails [in Hebrew] in a short time, Gmail gather the emails into one conversation and then it shows a link "Show quoted text" and if I click on it, it fixes the dimensions of the message as it should be, but of course it's not a solution as if I reopen the message it is cropped again.

Screenshot: https://i.imgur.com/sgKoHOA.jpg of the cropped email.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

</details>

Thank you,
Amir

**Comment by amirgroisman** [comment]
Hi guys, I wanted to update that I found a solution after some searching in the code.
So the problem is in **woocommerce\templates\emails\email-header.php**
I removed the: `dir="<?php echo is_rtl() ? 'rtl' : 'ltr'?>"from the element <div id="wrapper">` [line 31]
attribute and moved it to the table element below. (first child) [line 32]
like this:

`<table border="0" cellpadding="0" cellspacing="0" height="100%" width="100%"  dir="<?php echo is_rtl() ? 'rtl' : 'ltr'?>">`

And that fixed it!
I now receive Hebrew [rtl] emails which are perfectly formatted.
You can test it and fix it if you like.

Best Regards,
Amir

**Comment by kloon** [comment]
@amirgroisman when you test this are your computer set to RTL? The reason it may look off to you is that you might be trying to read it on a computer/browser that is set up as LTR as appose to RTL when you are viewing RTL content.

**Comment by mikejolley** [comment]
I tried to replicate this with both RTL tester and Hebrew language. All emails were the same regardless of that chance, and the cropping was present--but thats not due to RTL. WC emails are not yet responsive. Responsive emails are on the roadmap but I cannot give an ETA.

Thanks
