### ISSUE TITLE
Updating product Geodata causes maximum function nesting fatal error

### ISSUE THREAD

**Issue by ediamin** [woocommerce/woocommerce#21257]
I'm working on a Geolocation plugin based on WooCommerce, where I need to add/update product `geo_latitude` and `geo_longitude` meta data. According to [Codex guideline](https://codex.wordpress.org/Geodata), we should save these two meta values in `float` data type. But, WC has a filter `WC_Post_Data::update_post_metadata()` which ensures float meta values are converted to strings based on PHP locale. So, problem arises when we try to sanitize the above two meta into float value. I'm also using Jetpack in my WordPress setup and it has a geo location module which register `geo_latitude` and `geo_longitude` with [sanitize_callback](https://github.com/Automattic/jetpack/blob/master/modules/geo-location/class.jetpack-geo-location.php#L85), type: float. Hence, every time I try to update `geo_latitude` or `geo_longitude` meta values for any product, I got this following fatal error,
```
PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in /Users/ediamin/www/woocommerce/wp-includes/cache.php on line 523
```

**To Reproduce**
1. Install WooCommerce and Jetpack
2. Try to update `geo_latitude` and/or `geo_longitude` meta for any product,
```php
// suppose we have a product which has id 123
update_post_meta( 123, 'geo_latitude', 20.1234 );
```
3. Got error in debug.log
```
PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in /Users/ediamin/www/woocommerce/wp-includes/cache.php on line 523
```

**Expected behavior**
Meta values for above two meta keys should be saved in float.

**Isolating the problem:**
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

Home URL: http://localhost/woocommerce
Site URL: http://localhost/woocommerce
WC Version: 3.4.5
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.12 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2j

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 4.61MB
Database Data Size: 3.45MB
Database Index Size: 1.16MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_dokan_announcement: Data: 0.02MB + Index: 0.00MB
wp_dokan_orders: Data: 0.02MB + Index: 0.03MB
wp_dokan_refund: Data: 0.02MB + Index: 0.00MB
wp_dokan_shipping_zone_locations: Data: 0.02MB + Index: 0.00MB
wp_dokan_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_dokan_vendor_balance: Data: 0.02MB + Index: 0.00MB
wp_dokan_withdraw: Data: 0.02MB + Index: 0.00MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 2.27MB + Index: 0.05MB
wp_postmeta: Data: 0.23MB + Index: 0.13MB
wp_posts: Data: 0.13MB + Index: 0.06MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_weforms_entries: Data: 0.02MB + Index: 0.02MB
wp_weforms_entrymeta: Data: 0.02MB + Index: 0.03MB
wp_wpuf_subscribers: Data: 0.02MB + Index: 0.02MB
wp_wpuf_transaction: Data: 0.02MB + Index: 0.06MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 81
customize_changeset: 5
nav_menu_item: 15
page: 30
post: 4
product: 62
revision: 6
tribe_events: 2
tribe_organizer: 2
tribe_venue: 2
wpuf_contact_form: 1
wpuf_forms: 2
wpuf_input: 41
wpuf_profile: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

Jetpack by WordPress.com: by Automattic – 6.4.2
WooCommerce: by Automattic – 3.4.5

### Settings ###

API Enabled: –
Force SSL: –
Currency: BDT (৳ )
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #69 - /shop/
Cart: #70 - /cart/
Checkout: #71 - /checkout/
My account: #72 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
</details>

**Comment by kloon** [comment]
I think the Codex just means you need to save it in a float format and not pass it on as a float value to the post_meta functions. The post meta table only saves values as strings as the field in the DB is a varchar so that is why it is trying to covert it.

You will achieve the same results if you use `update_post_meta( 123, 'geo_latitude', '20.1234' );` So try casting the value as a string when passing it on to update_post_meta and see if that works for you.

**Comment by ediamin** [comment]
@kloon thanks for the feedback. But, actually I'm having this issue when Jetpack is active. As I mention in my original post Jetpack registers `geo_latitude` and `geo_longitude` using `register_meta` function with type: float casting. In their point of view, they are also right, since, they are just following codex guidelines. So, I think, WC should introduce some condition that checks if any meta is using type casting or not in `WC_Post_Data::update_post_metadata()` function.
