### ISSUE TITLE
define more mail content hooks

### ISSUE THREAD

**Issue by matthiaswagnerwy** [woocommerce/woocommerce#21256]
I'm always frustrated when i find out that texts in the mail templates have changed and therefore my translations get lost and clients get texts that are different from those i would like them to read. 

I'd like to have at least one more hook for the text between the heading and the line with order number and date.

One alternative would be to override the whole template, but that requires to have an eye on the updates and watch if anything changed in core. The other alternative is to work with translation plugins, but this is also not update safe, since texts change from time to time in core.

Is there any better way to handle this or would a hook be fine here?

I guess this is not the right place for this additional question but maybe you can lead me to some resources on this: why is this translation system of wordpress not update safe at all? wouldn't it be better to have only string ids in the core files and then use translations from this id to all the different languages?

**Comment by kloon** [comment]
Unfortunately, the way the WordPress translation system works is that it requires translations to be approved first before actually being available for download. WooCommerce translations are all community driven and although we release beta releases well in advance on WordPress.org the translations, unfortunately, do not get approved well in advance before the release.

I just want to note that approval of translations are done by community members and not WooCommerce and these people are not always checking every day to approve translations, each language also has its own group of approvers also.

Another way around the translation issue is to override the templates and define it in the site's language, but as you said, when a new template update goes out you will need to manually make the changes in your overrides.

Alternatively, you can install a plugin like Loco Translate and add your own translations for the untranslated strings, or use the gettext filter via code to translate your own strings.

Using hooks will, unfortunately, deliver the same results, translations currently in WordPress is essentially a hook around the text called gettext.

**Comment by matthiaswagnerwy** [comment]
hy @kloon and thanks for answering.

i'm afraid maybe we are talking of different things. i thought it would be best to have the text output in the mail template done inside an action hook. so one could just remove the default action and hook his own text output without having to care about translations at all.
because when you look at `https://github.com/woocommerce/woocommerce/blob/master/templates/emails/customer-on-hold-order.php`, in line 28 this is the only direct output in this file, everything else is done with hooks?!

i already use loco translate by now. but as soon as the original string changes, my translations for that won't be shown anymore although the translation-files are stored in an upgrade-safe location (since the relation is missing of course). that's what i wanted to state with my last paragraph.
i guess we won't be able to change wordpress translation system here - just wanted to be sure that there is no better way to handle this so far...

matt
