### ISSUE TITLE
wp_kses_post() in cart.php remove modifies base64 string

### ISSUE THREAD

**Issue by radykal** [woocommerce/woocommerce#21259]
**Describe the bug**
I am setting a custom thumbnail in the cart using the "woocommerce_cart_item_thumbnail" filter. But in one of the last updates in woocommerce you added this code in the cart.php:

`if ( ! $product_permalink ) {
	echo wp_kses_post( $thumbnail );
} else {
	printf( '<a href="%s">%s</a>', esc_url( $product_permalink ), wp_kses_post( $thumbnail ) );
}
`

The wp_kses_post removes the "data: part" of a base64 image string. Right now I add a JS script that adds the missing string again,  but I want to know if there is workaround to do that with pure PHP, because when the cart page loads you will see an error in the web console.

Thanks

**Comment by rodrigoprimo** [comment]
Some background on why WP core does not allow `data` URI scheme:

https://core.trac.wordpress.org/ticket/19354

**Comment by peterfabian** [comment]
For a workaround in PHP, please see: https://github.com/woocommerce/woocommerce/issues/21246#issuecomment-418152159. 

I'm not sure we'll be changing this as there are reasons it's not enabled by default, as mentioned by Rodrigo.

**Comment by claudiulodro** [comment]
You'll have to use the workaround to add support for the protocol to wp_kses_post if you want it. It's not safe to allow it enabled by default, so we shouldn't allow it by default.
