### ISSUE TITLE
Order not showing attributes, variations, products addons, gravity forms

### ISSUE THREAD

**Issue by glauciolacerda** [woocommerce/woocommerce#21255]
We don't offer technical support on GitHub so we recommend using the following:

**Reading our documentation**
Usage docs can be found here: https://docs.woocommerce.com/

If you have a problem, you may want to start with the self help guide here: https://docs.woocommerce.com/document/woocommerce-self-service-guide/

**Technical support for premium extensions or if you're a WooCommerce.com customer**
 from a human being - submit a ticket via the helpdesk
https://woocommerce.com/contact-us/ 

**General usage and development questions**
- WooCommerce Slack Community: https://woocommerce.com/community-slack/
- WordPress.org Forums: https://wordpress.org/support/plugin/woocommerce
- The WooCommerce Help and Share Facebook group

**Comment by glauciolacerda** [comment]
I have a lot of attributes, variations and a gravity form in my product. All are ok until I finish the order. 
In my cart all attributes, variations and forms appears, but when I close the order, they disappear in my backend order and in the email that the client received.

**Comment by peterfabian** [comment]
Hi, 

please provide steps to reproduce the issue without Gravity forms, as we don't resolve issues caused by 3rd party plugins. 
Alternatively, I would suggest trying to contact Gravity forms support.

Thanks.

**Comment by glauciolacerda** [comment]
**test user**

 =>  Já está cadastrado? Clique aqui para entrar  (Already registered? Click here to enter)

Nome de usuário ou e-mail *  (name/login)     **glaucio2**

Senha * (password)           **howcanibuy**

you can change the email.

**Comment by kloon** [comment]
@glauciolacerda we do not provide support on this platform. For support please get in touch with our support department at https://woocommerce.com/contact-us/ If you purchase the extension from us you are entitled to support from our support staff who will assist you with finding what might cause this.

If I test this using just WooCommerce and a default theme my orders contain the variation data underneath the product as it should so not an issue with WooCommerce core.
