### ISSUE TITLE
NEW ORDER email not coming 

### ISSUE THREAD

**Issue by gauravk3** [woocommerce/woocommerce#21253]
Hi , 

after the update of 3.4.5  i have stopped getting new order emails , i do get 1 out of 10 emails when i receive a new order on my website. It happened just after updating woocommerce 

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by MfxSorin** [comment]
Same problem, just it was already happening to us in the previous update.

**Comment by kloon** [comment]
Please read through the Emails FAQ which addresses why emails does not arrive, the latest release did not make any changes to emails so not the cause. https://docs.woocommerce.com/document/email-faq/

I suggest you look into using an email server to deliver your emails as the built in email sending functionality of WordPress is not very reliable and are prone to make your emails get stuck in spam filters.
