### ISSUE TITLE
Back from Payment processor hangs on IOS

### ISSUE THREAD

**Issue by charlespageza** [woocommerce/woocommerce#21258]
**Describe the bug**
After the latest Woo update  (3.4.5) we are experiencing a hang on IOS when user presses back twice on the payment screen.  We have stripped the staging site down to only Twenty Seventeen, Woocommerce, the payment gateway (Payfast) and Really Simple SSL.  

**To Reproduce**
1. Go to https://legwear.co.za/staging  (On IOS device)
2. Select any product, and proceed to checkout
3. Fill in info, and proceed to payment.  Processing screen pops up followed by payment processor
4. Use Browser back button (twice to get past processing screen) and it hangs with the little ajax circle spinning

**Screenshots**
There is a video of the issue here: https://legwear.co.za/Video.mp4

**Expected behavior**
On all other platforms, doing the above appears to come back to a cart option without circle.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

Home URL: |   | https://legwear.co.za/staging
-- | -- | --
Site URL: |   | https://legwear.co.za/staging
WooCommerce version: |   | 3.4.5
Log directory writable: |   | /usr/www/users/legwexkrsd/staging/wp-content/uploads/wc-logs/
WordPress version: |   | 4.9.8
WordPress multisite: |   | –
WordPress memory limit: |   | 512 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_ZA
External object cache: |   | –

Server environment
--
Server info: |   | Apache
PHP version: |   | 7.0.31-1+0~20180725100222.2+jessie~1.gbp8e8a8b  - We recommend using PHP version 7.2 or above for greater performance  and security. How to update your PHP version
PHP post max size: |   | 64 MB
PHP time limit: |   | 90
PHP max input vars: |   | 5000
cURL version: |   | 7.38.0, OpenSSL/1.0.1t
SUHOSIN installed: |   | –
MySQL version: |   | 5.5.5-10.0.36-MariaDB-1~jessie
Max upload size: |   | 64 MB
Default timezone is UTC: |   |  
fsockopen/cURL: |   |  
SoapClient: |   |  
DOMDocument: |   |  
GZip: |   |  
Multibyte string: |   |  
Remote post: |   |  
Remote get: |   |  

Server environment
--
Server info: |   | Apache
PHP version: |   | 7.0.31-1+0~20180725100222.2+jessie~1.gbp8e8a8b  - We recommend using PHP version 7.2 or above for greater performance  and security. How to update your PHP version
PHP post max size: |   | 64 MB
PHP time limit: |   | 90
PHP max input vars: |   | 5000
cURL version: |   | 7.38.0, OpenSSL/1.0.1t
SUHOSIN installed: |   | –
MySQL version: |   | 5.5.5-10.0.36-MariaDB-1~jessie
Max upload size: |   | 64 MB
Default timezone is UTC: |   |  
fsockopen/cURL: |   |  
SoapClient: |   |  
DOMDocument: |   |  
GZip: |   |  
Multibyte string: |   |  
Remote post: |   |  
Remote get: |   |  

Server environment
--
Server info: |   | Apache
PHP version: |   | 7.0.31-1+0~20180725100222.2+jessie~1.gbp8e8a8b  - We recommend using PHP version 7.2 or above for greater performance  and security. How to update your PHP version
PHP post max size: |   | 64 MB
PHP time limit: |   | 90
PHP max input vars: |   | 5000
cURL version: |   | 7.38.0, OpenSSL/1.0.1t
SUHOSIN installed: |   | –
MySQL version: |   | 5.5.5-10.0.36-MariaDB-1~jessie
Max upload size: |   | 64 MB
Default timezone is UTC: |   |  
fsockopen/cURL: |   |  
SoapClient: |   |  
DOMDocument: |   |  
GZip: |   |  
Multibyte string: |   |  
Remote post: |   |  
Remote get: |   |  

</details>

Any assistance would be greatly appreciated.

Kind regards
Charles

**Comment by kloon** [comment]
@charlespageza the issue seems to be related to the PayFast extension. Since we only deal with WooCommerce core issues on here I am going to have to ask you to please contact support for assistance with this https://woocommerce.com/contact-us/

From what I can see though, it is caused by the way the PayFast gateway initiates the redirect to PayFast.
