### ISSUE TITLE
shop page doesn't scroll

### ISSUE THREAD

**Issue by trendywatch** [woocommerce/woocommerce#21263]
Since the last woocommerce update our shop page doesn't work optimal. We can only see one page with our products in stead off 5. It is not possible to scroll further. See screenshot below. Do you know what the problem is?

![image](https://user-images.githubusercontent.com/42936752/44986657-ce827480-af84-11e8-8829-3b9da852073e.png)

**Comment by kloon** [comment]
Please go through the questions when you opened the issue. This is likely an issue with your theme or a plugin on your site.
