### ISSUE TITLE
Global Attribute sorting by name returns results sorted by custom order

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#21269]
**Describe the bug**
When creating a global product attribute we have the option to sort the attributes by either of these sort methods:

- Custom Ordering
- Name
- Name (Numeric)
- Term ID

When we select sorting by Name it still sorts according to the Custom Order.

**To Reproduce**
1. Create a global attribute with the terms Small, Medium, Large
2. Sort the attributes so they have a custom order defined as Small, Medium, Large
3. Set the attribute sorting method to Name
4. Create a variable product with all these attributes, and a variation for each.
5. On the frontend the attributes are still sorted using the custom order.

**Screenshots**
![image](https://user-images.githubusercontent.com/11388669/45030219-0819b500-b043-11e8-8622-f4f2bb96992d.png)

**Expected behavior**
If the sorting method is set to Name I would expect the order to be Large, Medium, Small

If I inspect the query "when skipping the cache" I can see it's creating the following query to load the sizes:

```
SELECT t.*, tt.*, tm.meta_value
FROM wp_terms AS t 
INNER JOIN wp_term_taxonomy AS tt
ON t.term_id = tt.term_id
INNER JOIN wp_term_relationships AS tr
ON tr.term_taxonomy_id = tt.term_taxonomy_id
LEFT JOIN wp_termmeta AS tm
ON (t.term_id = tm.term_id
AND tm.meta_key = 'order_pa_size') 
WHERE tt.taxonomy IN ('pa_size')
AND tr.object_id IN (1463) 
GROUP BY t.term_id
ORDER BY tm.meta_value+0 ASC, t.name ASC
```

In the query we can see that it's using the meta value (custom sort order) and then the name to sort the results. This is added by the following function: https://github.com/woocommerce/woocommerce/blob/3.4.5/includes/wc-term-functions.php#L520

When we sort using the custom sort order we remove the default orderby, see: https://github.com/woocommerce/woocommerce/blob/3.4.5/includes/wc-term-functions.php#L126
So since the default to orderby is 'name', there doesn't seem to be a way in the filter to differentiate between the two sort methods. Which is why it adds the custom sort order in both cases.
Is there a better way to handle this?

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

```
WooCommerce 3.4.5
WordPress 4.9.8
Storefront 2.3.3
```

</details>

**Comment by claudiulodro** [comment]
I was able to reproduce this. We'll have to do some refactoring around that logic. Good catch @mikkamp !

**Comment by claudiulodro** [comment]
#21408
