### ISSUE TITLE
Gutenberg products block Uncaught TypeError: withAPIData is not a function

### ISSUE THREAD

**Issue by manake** [woocommerce/woocommerce#21275]
https://wordpress.org/plugins/woo-gutenberg-products-block/

```
products-block.js?ver=1.1.1:2514
Uncaught TypeError: withAPIData is not a function
```

**Comment by kloon** [comment]
@manake please log issues relating to the product block on the product block repo https://github.com/woocommerce/woocommerce-gutenberg-products-block

Thanks!
