### ISSUE TITLE
Getting 405 Not Allowed after inserting 3000+ records using Rest Apis

### ISSUE THREAD

**Issue by Kamalsurya** [woocommerce/woocommerce#21271]
![image](https://user-images.githubusercontent.com/10720992/45034996-8774ac00-b076-11e8-8439-5fb41d23c08d.png)

<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.14.0</center>
</body>
</html>

**To Reproduce**
RestAPI rest = new RestAPI(url, ck, cs);
WCObject wc = new WCObject(rest);
List<Product > simplifiedListOfProducts = 5500 items
foreach (var item in simplifiedListOfProducts){
Product p = new Product()
{
   name = item.name
};
await wc.Product.Add(p);
}
 
**Expected behavior**
Need to insert data without any error

 
**WordPress Environment**
Version 4.9.8

 
<details>

### WordPress Environment ###

Home URL: https://
Site URL: https://
WC Version: 3.4.5
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 5.4.45 - ❌ WooCommerce will run under this version of PHP
however
it has reached end of life. We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version

PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: 5.6.39-83.1
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 24.01MB
Database Data Size: 16.58MB
Database Index Size: 7.43MB
wp_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_comments: Data: 0.00MB + Index: 0.01MB
wp_failed_jobs: Data: 0.00MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_mailchimp_carts: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 7.60MB + Index: 1.45MB
wp_postmeta: Data: 7.47MB + Index: 5.11MB
wp_posts: Data: 1.32MB + Index: 0.44MB
wp_queue: Data: 0.00MB + Index: 0.00MB
wp_social_users: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.17MB + Index: 0.35MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.01MB
wp_usermeta: Data: 0.01MB + Index: 0.01MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_yith_wcwl: Data: 0.00MB + Index: 0.00MB
wp_yith_wcwl_lists: Data: 0.00MB + Index: 0.01MB

### Post Type Counts ###

attachment: 10
blocks: 8
customize_changeset: 10
featured_item: 8
nav_menu_item: 38
page: 85
post: 11
product: 4164
revision: 58
shop_order: 1
wpcf7_contact_form: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (16) ###

Akismet Anti-Spam: by Automattic – 4.0.8
Contact Form 7: by Takayuki Miyoshi – 5.0.3
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.1.0
Jetpack by WordPress.com: by Automattic – 6.4.2
MailChimp for WooCommerce: by MailChimp – 2.1.9 – Not tested with the active version of WooCommerce
MOJO Marketplace: by Mike Hansen – 1.3.4
Nextend Social Login: by Nextendweb – 3.0.12
OptinMonster API: by OptinMonster Team – 1.5.0
Woo Product Remover: by Mohammad Farhat – 1.1.0 – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.3
WooCommerce Services: by Automattic – 1.15.1
WooCommerce Square: by WooCommerce – 1.0.32
WooCommerce: by Automattic – 3.4.5
WooSidebars: by WooCommerce – 1.4.5
WPForms Lite: by WPForms – 1.4.7.2
YITH WooCommerce Wishlist: by YITHEMES – 2.2.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #81 - /shop/
Cart: #80 - /cart/
Checkout: #79 - /checkout/
My account: #78 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Flatsome
Version: 3.6.2
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

`
</details>

**Comment by kloon** [comment]
The only time WooCommerce will return a 405 is when you are trying to access an endpoint that has no crud functionality tied to it, by default all the endpoints shipped with core has functionality tied to it.

The only other scenario would be that your server, nginx, is returning that code for some reason. I would start there and investigate why.

Also, you have not provided any details as what the actual endpoint and underlying code your script is calling? I assume you are using a library here? If so which one?

I would also test by disabling all plugins except WooCommerce and switch to a default theme like Twenty Seventeen and run the test again.

I am unable to reproduce this by running API requests using cURL and Postman to the products endpoint.
