### ISSUE TITLE
Product Variation - Variations with a Custom Attribute set to 'Any' not showing

### ISSUE THREAD

**Issue by awebsterx** [woocommerce/woocommerce#21285]
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

I have setup a product with variations using custom attributes. There are 4 custom attributes, one of which is set to 'Any'. However, on the front end that attribute appears to be empty. Why would this not populate with all attribute options (if set to any)?

All variations have a regular price set to '0'.

I manage to fix the issue by changing a value in the variation and 're-save'. It begins to work for that variation only. 

Its as if the variation bulk insert I do sets an empty value for this particular attribute perhaps?

## Expected/actual behavior

- [X ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ X] I can reproduce this bug consistently using the steps above

## WordPress Environment
WordPress 4.9.8
WooCommerce 3.4.4

<details>

WordPress environment

Home URL: |   | https://cartmyart.com.au
-- | -- | --
Site URL: |   | https://cartmyart.com.au
WooCommerce version: |   | 3.4.4
Log directory writable: |   | /home2/wag5q40acxzk/public_html/wp-content/uploads/wc-logs/
WordPress version: |   | 4.9.8
WordPress multisite: |   | –
WordPress memory limit: |   | 256 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –

Server info: |   | Apache
-- | -- | --
PHP version: |   | 7.1.13 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP post max size: |   | 64 MB
PHP time limit: |   | 30
PHP max input vars: |   | 1000
cURL version: |   | 7.19.7, NSS/3.27.1
SUHOSIN installed: |   | –
MySQL version: |   | 5.6.32-78.1
Max upload size: |   | 64 MB

WooCommerce database version: |   | 3.4.4
-- | -- | --
Database prefix |   | wpdf_
Total Database Size |   | 44.89MB
Database Data Size |   | 30.56MB
Database Index Size |   | 14.33MB

</details>

**Comment by peterfabian** [comment]
Hi, 

I'm not sure I understand what you mean by attribute that appears to be empty. Is the dropdown not displayed? Or does it have no options? 

I tried to set up a variable product with 4 custom attributes, generated 27 variations for 3 * 3 * 3 variations for 3 attributes, having the 4th attribute set to Any, but I'm not sure what you mean. Can you provide a link to your website or a screenshot where this would be visible?

Have you tried to rule out theme and plugin conflict using the [self-service guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/)?

**Comment by claudiulodro** [comment]
I'm not sure exactly what the setup you are describing is, either. Can we please get some screenshots of your variation settings so that we are able to reproduce the issue? If we are unable to reproduce the issue we will be unable to investigate it. Thanks.

**Comment by awebsterx** [comment]
Hi Peter

In the attached screenshots you will see the variations are setup with four custom attributes. The 'Profile' attribute is set to any.

If you look at the next screenshot, you will see that the profile attribute has no values showing in it.

Regards

Alex

CUSTOM ATTRIBUTES:
![custom attributes](https://user-images.githubusercontent.com/19404643/45201508-0c4f0800-b2b9-11e8-92ab-9db85f710286.png)

ACTIVE VARIATIONS:
![variations](https://user-images.githubusercontent.com/19404643/45201521-225cc880-b2b9-11e8-9639-9877c0739bdf.png)

FRONTEND (PROFILE ATTRIBUTE IS EMPTY)
![frontend](https://user-images.githubusercontent.com/19404643/45201628-8bdcd700-b2b9-11e8-86ff-f56995f14c61.png)

**Comment by peterfabian** [comment]
I'm sorry, I can't reproduce this problem. Have you tried to replicate this with only WooCommerce active using Storefront theme?

**Comment by awebsterx** [comment]
Hi Peter 
Thank you for looking into this. After further investigation on my end I believe it’s an issue with the bulk insert plugin I am using that is not populating the value correctly. Sorry for the inconvenience.
Regards
Alex
