### ISSUE TITLE
Getting JS error on missing #stripe-iban-element

### ISSUE THREAD

**Issue by therealgilles** [woocommerce/woocommerce#21280]
I am getting this new error recently on my Woocommerce site:

```
Uncaught Error: The selector you specified (#stripe-iban-element) applies to no DOM elements that are currently on the page.
Make sure the element exists on the page before calling mount().
```

I do not use IBAN on my site, so I am a bit puzzled. This could well be a Stripe problem, not sure. Wondering if anyone else is seeing this too.

**Comment by peterfabian** [comment]
Hi, 

thanks for reporting the problem. It seems like this is related to the Stripe payment gateway. Could you please create an issue in the repository for Stripe plugin?

https://github.com/woocommerce/woocommerce-gateway-stripe/issues

Thanks!

**Comment by therealgilles** [comment]
Done!
