### ISSUE TITLE
Remove jQuery dependance

### ISSUE THREAD

**Issue by Jab2870** [woocommerce/woocommerce#21286]
**Is your feature request related to a problem? Please describe.**
No, an enhancement idea

**Describe the solution you'd like**
It would be nice if WooCommerce didn't rely on jQuery. It is a large library that (personally) I don't think is really necessary any more. Vanilla JS has come on a long way.

**Describe alternatives you've considered**
Vanilla JS

**Comment by peterfabian** [comment]
Thanks for your idea. 

We already have plans to do so. Please vote for this idea by giving it a 👍 here: https://github.com/woocommerce/woocommerce/issues/18395.
