### ISSUE TITLE
Variation names of a variable product showing as Any in Edit Product page

### ISSUE THREAD

**Issue by menakas** [woocommerce/woocommerce#21294]
**Describe the bug**
When a Variable Product is created, with an attribute name having an upper case letter, the variations created show up as Any.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Add new product' in admin dashboard.
2. In the 'Product Data' meta box, choose 'Variable Product'
3. In the Attributes tab, create an attribute with an uppercase - eg. Color: ![](https://cldup.com/gP3a6-Dqou.png)
4. In the Variations tab, create variations to see 'Any Color' displayed : ![](https://cldup.com/tRDQtfebvp.png)

**Expected behaviour**
Expect to see the attribute names (in this case, Green and Yellow ) in the variations tab.

**Isolating the problem :**

It looks like the issue stems from #21074 and [this commit](https://github.com/woocommerce/woocommerce/commit/4d2530ef454dfd1942754f7b96b772ffe03035f8)

`sanitize_title()` converts the attribute name to lowercase whereas `sanitize_text_field()` retains the case. This seems to cause this issue.

**WordPress Environment**

WordPress version: 4.9.8

This bug is seen in the latest master branch of WC but not in v3.4.5

**Comment by claudiulodro** [comment]
#21403
