### ISSUE TITLE
" (quote) in attribute name displayed as &quot; in filter widget dropdown (select2)

### ISSUE THREAD

**Issue by dtugend** [woocommerce/woocommerce#21295]
**Describe the bug**
 `"` in attribute name displayed as `&quot;` in filter widget

**To Reproduce**
Create an attribute with `"` in the name.

**Expected behavior**
Quote  `"` should be displayed, not `&quot;`.

**Reason in code**
[layered_nav_dropdown uses $any_label as argument to placehold for select2](https://github.com/woocommerce/woocommerce/blob/d9b5cf7b6f859066cfb73105fb0348c29d3d8c75/includes/widgets/class-wc-widget-layered-nav.php#L296): `placeholder: '" . esc_js( $any_label ) . "',` which is usually from [`$taxonomy_label = wc_attribute_label( $taxonomy );`](https://github.com/woocommerce/woocommerce/blob/d9b5cf7b6f859066cfb73105fb0348c29d3d8c75/includes/widgets/class-wc-widget-layered-nav.php#L227), which is already HTML [escaped by wp_kses_post function in wp-core-functions.php on woocommerce_attribute_label filter](https://github.com/woocommerce/woocommerce/blob/d9b5cf7b6f859066cfb73105fb0348c29d3d8c75/includes/wc-core-functions.php#L41), causing the bug.

**Suggested fix**
Since plugins might relay on the wc_attribute_label function being used and other WooCommerce code might expect the label to be HTML escaped, I suggest to change line [296](https://github.com/woocommerce/woocommerce/blob/d9b5cf7b6f859066cfb73105fb0348c29d3d8c75/includes/widgets/class-wc-widget-layered-nav.php#L296) to `placeholder: '" . esc_js( wp_specialchars_decode( $any_label ) ) . "',` in order to somewhat reverse the escaping.

**Comment by kloon** [comment]
See #21312

**Comment by dtugend** [comment]
@kloon Thank you! I added a comment there, because I think esc_js needs to be executed after the decode, as I suggested above, otherwise it might be not properly escaped for JS.
