### ISSUE TITLE
no-indexed WooCommerce pages not excluded from sitemap

### ISSUE THREAD

**Issue by strarsis** [woocommerce/woocommerce#21297]
**Describe the bug**
WooCommerce pages which are no-index (my account, cart and payment pages) 
are still included in Yoast sitemap.

Google Search Console also reports this as an error because the 
pages are listed in sitemap but are no-indexed individually.

**To Reproduce**
- Install + activate WooCommerce plugin.
- Install + activate Yoast SEO plugin

**Expected behavior**
The WooCommerce no-indexed page being excluded from the sitemap.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

This is probably caused by WooCommerce injecting the no-index meta/header separately from Yoast.
The WooCommerce pages can be excluded from sitemap using the [`wpseo_exclude_from_sitemap_by_post_ids`](https://kb.yoast.com/kb/sitemap-shows-excluded-posts-pages/) filter.

**Comment by glagonikas** [comment]
The no-index and sitemap are both parts of Yoast SEO, so it's unlikely this bug is caused by WooCommerce. Have you reached out to their support?

Also, i'm unable to reproduce this on our setup where we use Yoast SEO Premium. Whenever i set a product to "no-index", it automatically get removed from the sitemap.

**Comment by claudiulodro** [comment]
Hi there.

This is something Yoast would have to handle in their plugin, as sitemaps are not part of the WooCommerce plugin. I would reach out to them. Hope this clears things up.

Thanks.
