### ISSUE TITLE
Grammatical error.

### ISSUE THREAD

**Issue by slyk-style** [woocommerce/woocommerce#21308]
This is driving me insane. Is it possible to change the woocommerce terminology for sorting product by the newest products? "Newness" is a poor use of grammar and I hate having to add a file to each project or changing the default and forcing projects not to update because grammar is incorrectly used. I don't know when this changed but it should be fixed to what most websites use. Can it be changed to say sort by latest or sort by newest? preferably the former. 

The file is
wp-content/plugins/woocommerce/includes/wc-template-functions.php
Line 1301

**Comment by kloon** [comment]
See #21311

**Comment by claudiulodro** [comment]
[FWIW newness is a real word.](https://www.merriam-webster.com/thesaurus/newness) :)
