### ISSUE TITLE
Order_item_id changes when change payment method

### ISSUE THREAD

**Issue by Mike242** [woocommerce/woocommerce#21318]
Hi,

I have installed WooCommerce and WC Marketplace on a site.

When someone checks out and select for example paypal, he is redirected to a page to pay. At that time entries are created in both wcmp_vendor_orders and woocommerce_order_items tables with the same order_id and same order_item_id. Now if the user regrets and goes back and chooses a different payment method (Cash on Delivery for example), the order_id remains the same in both tables, but woocommerce_order_items table increase the order_item_id. Whereas in wcmp_vendor_orders table the order_item_id remains the same for that order. 

So there is no consistent between those 2 tables this way. I tried this in a fresh installation with only 

Which table is right and which wrong?

Please see the video I prepared: https://www.youtube.com/watch?v=6UW8aAd17GM&feature=youtu.be regarding this issue

Thank you

**Comment by kloon** [comment]
Can you test this with just WooCommerce without the Marketplace functionality as I am unable to find any issue with the core code and functionality?

Unfortunately, this issue tracker is only for issues related to WooCommerce **core** and not plugins/extensions. For that you will need to contact the plugin/extension author, if you purchased it through WooCommerce.com then you can get in contact here http://woocommerce.com/contact-us/

If you are able to recreate this using just WooCommerce core we can reopen this issue.
