### ISSUE TITLE
Secondary checkout page using checkout shortcode is evaluated as false when checking if its a checkout page

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce#21321]
**Describe the bug**
When you create a separate page with the shortcode `[woocommerce_checkout]` that is not set as the checkout page in settings, some scripts will not fire. Initially reported here https://github.com/woocommerce/woocommerce-gateway-stripe/issues/730

NOTE: billing field has nothing to do with it from that report.

This line here will evaluate to false https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-frontend-scripts.php#L512

In turn will mean this trigger never fires
https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/checkout.js#L55

**To Reproduce**
1. Create a page and add shortcode `[woocommerce_checkout]`
2. Go to that checkout page and debug `is_page( wc_get_page_id( 'checkout' ) )` and you will see it evaluates to false because it is not what is set in the setting.

**Expected behavior**
To evaluate as true when asking if the current page is a checkout page.

**Possible solution**
Instead of using `is_page( wc_get_page_id( 'checkout' ) )` perhaps use `is_checkout()` to determine if the page is a checkout page?

**Comment by kloon** [comment]
See #21328
