### ISSUE TITLE
List all product categories

### ISSUE THREAD

**Issue by taich001** [woocommerce/woocommerce#21330]
Woo REST API List all categories does not work properly. I have no idea but some of my about 30 categories simply wont get listed.

If I send a request for just one (not listed) category by id I get a proper answer.

curl https://example.com/wp-json/wc/v2/products/categories \
    -u consumer_key:consumer_secret

`
### WordPress Environment ###

Home URL: https://vitula.1w.at
Site URL: https://vitula.1w.at
WC Version: 3.4.5
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.30-0ubuntu0.16.04.1 - Wir empfehlen
PHP Version 7.2 oder höher für mehr Leistung und Sicherheit zu verwenden. So aktualisierst du deine PHP-Version

PHP Post Max Size: 64 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.36-MariaDB-1~xenial
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Datenbank-Gesamtgröße: 1.90MB
Datenbank-Datengröße: 0.97MB
Datenbank-Indexgröße: 0.93MB
wp_woocommerce_sessions: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Daten: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB
wp_comments: Daten: 0.02MB + Index: 0.09MB
wp_duplicator_pro_entities: Daten: 0.02MB + Index: 0.02MB
wp_duplicator_pro_packages: Daten: 0.02MB + Index: 0.02MB
wp_iwp_backup_status: Daten: 0.02MB + Index: 0.00MB
wp_links: Daten: 0.02MB + Index: 0.02MB
wp_mclean_refs: Daten: 0.02MB + Index: 0.00MB
wp_mclean_scan: Daten: 0.02MB + Index: 0.00MB
wp_odb_logs: Daten: 0.02MB + Index: 0.00MB
wp_options: Daten: 0.22MB + Index: 0.03MB
wp_postmeta: Daten: 0.08MB + Index: 0.06MB
wp_posts: Daten: 0.05MB + Index: 0.06MB
wp_termmeta: Daten: 0.02MB + Index: 0.03MB
wp_terms: Daten: 0.02MB + Index: 0.03MB
wp_term_relationships: Daten: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Daten: 0.02MB + Index: 0.03MB
wp_usermeta: Daten: 0.02MB + Index: 0.03MB
wp_users: Daten: 0.02MB + Index: 0.05MB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 3
custom_css: 1
customize_changeset: 1
nav_menu_item: 57
page: 3
post: 2
product: 6
revision: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

InfiniteWP - Client: von Revmakx – 1.8.5
Add From Server: von Dion Hulse – 3.3.3
Disable All WordPress Updates: von Oliver Schlöbe – 1.6.3
Duplicator Pro: von Snap Creek – 3.7.6
Limit Login Attempts Reloaded: von wpchefgadget – 2.7.1
Media Cleaner: von Jordy Meow – 5.0.2
Media File Manager: von Atsushi Ueda – 1.4.2
Datenbank bereinigen und optimieren: von CAGE Web Design | Rolf van Gelder
Eindhoven
Niederlande – 4.6.3

Scripts n Styles: von unFocus Projects – 3.4.4
Soliloquy - Carousel Addon: von Soliloquy Team – 2.2.1
Responsive WordPress Slider - Soliloquy Lite: von Soliloquy Team – 2.5.3
Soliloquy - WooCommerce Addon: von Soliloquy Team – 1.1.3 – Nicht getestest mit der aktiven WooCommerce-Version
Soliloquy: von Soliloquy Team – 2.5.5
Storefront Footer Text: von Wooassist – 1.0.1
Storefront Header Picker: von Wooassist – 1.0.2
Storefront Site Logo: von Wooassist – 1.2.3
Title Toggle for Storefront Theme: von Wooassist – 1.2.4
TinyMCE Advanced: von Andrew Ozz – 4.8.0
WooCommerce Product Attachment: von multidots – 1.1.4 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Catalog Visibility Options: von Lucas Stark – 3.2.0
WooCommerce: von Automattic – 3.4.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop-Basis: #58 - /produkte/
Warenkorb: ❌ Seiten-ID ist gesetzt
aber die Seite existiert nicht

Kasse: ❌ Seiten-ID ist gesetzt
aber die Seite existiert nicht

Mein Konto: ❌ Seiten-ID ist gesetzt
aber die Seite existiert nicht

Allgemeine Geschäftsbedingungen: ❌ Seite nicht festgelegt

### Theme ###

Name: Storefront Child Theme
Version: 1.0.0
Author URL: http://stuartduff.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.3.3
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: storefront-child-theme-master/woocommerce/loop/sale-flash.php
storefront-child-theme-master/woocommerce/single-product/sale-flash.php
storefront-child-theme-master/single-product.php

`

**Comment by claudiulodro** [comment]
Hi there,

Most likely you need to use the [per_page parameter](https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-product-categories) and make sure it's large enough to get all the categories at once. You haven't really provided any further information about the API call you are making, so I have to assume that is the issue. Hope this helps.

Thanks.
