### ISSUE TITLE
Maxmind GeoIP db not being recognised by Woocommerce

### ISSUE THREAD

**Issue by just-us** [woocommerce/woocommerce#21331]
**Describe the bug**
When checking the Woocommerce status tab, the entry for the Maxmind GeoIP database issues a warning saying "The MaxMind GeoIP Database does not exist - Geolocation will not function.". When I checked the uploads folder, it is sitting there, ready to be used.

**To Reproduce**
None

**Expected behavior**
The database to be recognised by Woocommerce as being in the folder and therefore available.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://studioessence.co.uk
Site URL: https://studioessence.co.uk
WC Version: 3.4.5
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.21 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 20 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.34

SUHOSIN Installed: –
MySQL Version: 5.6.41-84.1
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from https://dev.maxmind.com/geoip/geoip2/geolite2/ to the path: . Scroll down to "Downloads" and download the "MaxMind DB binary
gzipped" file next to "GeoLite2 Country". Please remember to uncompress GeoLite2-Country_xxxxxxxx.tar.gz and upload the GeoLite2-Country.mmdb file only.

Total Database Size: 13.34MB
Database Data Size: 11.45MB
Database Index Size: 1.89MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_event_hours: Data: 0.00MB + Index: 0.00MB
wp_layerslider: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 3.48MB + Index: 0.06MB
wp_postmeta: Data: 1.52MB + Index: 0.83MB
wp_posts: Data: 5.52MB + Index: 0.28MB
wp_revslider_css: Data: 0.13MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.02MB + Index: 0.00MB
wp_revslider_slides: Data: 0.06MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.03MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_shipping_methods: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 111
cmsms_contact_form: 48
cmsms_like: 60
content_template: 38
custom_css: 1
events: 15
google_maps: 1
jetpack_migration: 2
nav_menu_item: 29
page: 16
post: 6
product: 30
product_variation: 111
profile: 4
project: 12
revision: 696
shop_coupon: 2
shop_order: 21
sidebar: 1
timetable_weekdays: 7
tribe_organizer: 9
tribe_venue: 5
wpcf7_contact_form: 2
wpgmapembed: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

LayerSlider WP: by Kreatura Media – 5.6.2
Admin Menu Editor Pro: by Janis Elsts – 2.6.6
All-in-One WP Migration: by ServMask – 6.75
Classic Editor: by WordPress Contributors – 0.4
CMSMasters Contact Form Builder: by cmsmasters – 1.3.5
CMSMasters Content Composer: by cmsmasters – 1.5.7
CMSMasters Mega Menu: by cmsmasters – 1.2.4
Contact Form 7: by Takayuki Miyoshi – 5.0.4
Envato Market: by Envato – 2.0.1
GoCardless Payment Gateway for WooCommerce: by Outerbridge – 1.0 – Not tested with the active version of WooCommerce
GoCardless for WordPress: by Outerbridge – 2.1.1
Jetpack by WordPress.com: by Automattic – 6.5
One-Click Child Theme: by tychay – 1.6
PayPal Donations: by Tips and Tricks HQ
Johan Steen – 1.9.5

Slider Revolution: by ThemePunch – 5.4.8
Server IP & Memory Usage Display: by Apasionados
Apasionados del Marketing – 2.1.0

Simple CSS: by Tom Usborne – 1.1
Simple Page Sidebars: by Cedaro – 1.2.1
Timetable Responsive Schedule For WordPress: by QuanticaLabs – 4.0
WooCommerce: by Automattic – 3.4.5
WooSidebars: by WooCommerce – 1.4.5
Yoast SEO: by Team Yoast – 8.2
WordPress Toolbar Editor: by Janis Elsts – 1.2.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #6643 - /shop/
Basket: #3840 - /cart/
Checkout: #3837 - /checkout/
My account: ❌ Page not set
Terms and conditions: #7452 - /terms-conditions/

### Theme ###

Name: Studio Essence
Version: – 0 is available
Author URL: 
Child Theme: ✔
Parent Theme Name: Yoga Fit
Parent Theme Version: 1.1.9
Parent Theme Author URL: http://cmsmasters.net/
WooCommerce Support: ✔

### Templates ###

Overrides: yoga-fit/woocommerce/archive-product.php version 3.3.0 is out of date. The core version is 3.4.0
yoga-fit/woocommerce/checkout/form-shipping.php
yoga-fit/woocommerce/checkout/thankyou.php
yoga-fit/woocommerce/content-product.php version 3.0.0 is out of date. The core version is 3.4.0
yoga-fit/woocommerce/content-single-product.php version 3.0.0 is out of date. The core version is 3.4.0
yoga-fit/woocommerce/content-widget-product.php
yoga-fit/woocommerce/global/sidebar.php
yoga-fit/woocommerce/global/wrapper-end.php
yoga-fit/woocommerce/global/wrapper-start.php
yoga-fit/woocommerce/loop/loop-start.php
yoga-fit/woocommerce/loop/pagination.php
yoga-fit/woocommerce/single-product/meta.php
yoga-fit/woocommerce/single-product/product-image.php
yoga-fit/woocommerce/single-product/product-thumbnails.php
yoga-fit/woocommerce/single-product/review.php
yoga-fit/woocommerce/single-product/tabs/tabs.php
yoga-fit/woocommerce/single-product-reviews.php
yoga-fit/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update
`
</details>

**Comment by claudiulodro** [comment]
What is the name of the GeoIP file you have? It should be `GeoLite2-Country.mmdb`

**Comment by kloon** [comment]
Where are you placing the file? It should be in the wp-content/uploads folder, unless you are using code to modify the path to the uploads folder, then it needs to be placed in the location you set your new uploads folder to.

**Comment by rodrigoprimo** [comment]
Closing due to lack of feedback.
