### ISSUE TITLE
Error in includes/class-wc-order-item.php on line 190

### ISSUE THREAD

**Issue by domlat** [woocommerce/woocommerce#21332]
After adding a new table rate shipping method the edit order page displayed incorrectly.

[12-Sep-2018 10:26:42 UTC] PHP Catchable fatal error:  Object of class stdClass could not be converted to string in /home/williamg/public_html/wp-content/plugins/woocommerce/includes/class-wc-order-item.php on line 190

The object was:
```
    (
      [id] => 966374
      [key] => description
      [value] => stdClass Object
        (
          [scalar] => <p><em>4-6 Days</em></p>
        )
    )
```
My solution was to add an is_object() check in the preceeding lines, similar to the is_array() check:
```
    if ( empty( $meta->id ) || "" === $meta->value || is_array( $meta->value ) || is_object( $meta->value ) 
      || ( $hideprefix_length && substr( $meta->key, 0, $hideprefix_length ) === $hideprefix ) ) {
      continue;
    }
```

**Comment by domlat** [comment]
Ummm... even if it *is* a problem with a theme or another plugin, would it not be a good idea to code defensively and perform this check anyway?

**Comment by kloon** [comment]
This problem does not seems to exist in the latest release anymore, there is a ! is_scalar check as part of that if statement.

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-order-item.php#L265-L267

**Comment by domlat** [comment]
Great news, thanks.
