### ISSUE TITLE
Don't allow spaces in endpoint fields.

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/woocommerce#21334]
**Is your feature request related to a problem? Please describe.**
I was curious if it was possible to validate the endpoint fields users can change in the Advanced tab? If so we shouldn't allow spaces to be entered. Perhaps rather replace spaces with a dash?

![http://cld.wthms.co/LVIjke](http://cld.wthms.co/LVIjke+)
Image link: http://cld.wthms.co/LVIjke

**Describe the solution you'd like**
Ideally we can update the endpoints descriptions and also validate the fields to check for spaces (or any additional bad characters). This came out of a scenario where if the endpoints have spaces and an order is placed you are taken back to an empty cart page. It was a but confusing for the customers and store owner, until they realized the endpoints had spaces in them.
 
**Describe alternatives you've considered**
At minimum it would be easy to say DON'T USE SPACES in the endpoints descriptions.

**Comment by kloon** [comment]
See #21355
