### ISSUE TITLE
WooCommerce canceling orders "time limit reached" but payment has been received

### ISSUE THREAD

**Issue by magcfc** [woocommerce/woocommerce#21339]
The last four orders on our website (from 9/7/18-9/12/18) have been canceled by WooCommerce saying "unpaid order cancelled - time limit reached. Order status changed from Pending Payment to Cancelled." However, we have received payment for each of these orders (verified in our accounts with Stripe and PayPal), either through PayPal or Stripe. These four customers have had payment processed, but aren't getting the product. All products are digital downloads that would have a link sent to them in the invoice email if WooCommerce showed the order as completed. I have not changed anything in WooCommerce settings during this time, and I am using the latest updated version for all plugins.

**To Reproduce**
It has happened to the last four order purchasers.

**Screenshots**
![screen shot 2018-09-12 at 5 54 00 pm](https://user-images.githubusercontent.com/43223391/45458628-207c7600-b6ba-11e8-9afa-88d1a7b1635d.png)

**Expected behavior**
Prior to 9/7/18, customers received an invoice with the link to download content immediately after purchasing. For some reason, WooCommerce isn't getting "the message" from Stripe and PayPal when payment is processed.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

### WordPress Environment ###

Home URL: https://www.createfamilyculture.com
Site URL: https://www.createfamilyculture.com
WC Version: 3.4.5
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 5.6.37 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 64 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 7.60.0
OpenSSL/1.0.2k

SUHOSIN Installed: ✔
MySQL Version: 10.0.36-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.5
WC Database Prefix: wp_shq8db
MaxMind GeoIP Database: ✔
Total Database Size: 15.44MB
Database Data Size: 13.82MB
Database Index Size: 1.62MB
wp_shq8dbwoocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_shq8dbwoocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_shq8dbwoocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_shq8dbwoocommerce_downloadable_product_permissions: Data: 0.05MB + Index: 0.05MB
wp_shq8dbwoocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_shq8dbwoocommerce_order_itemmeta: Data: 0.08MB + Index: 0.09MB
wp_shq8dbwoocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_shq8dbwoocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_shq8dbwoocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_shq8dbwoocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_shq8dbwoocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_shq8dbwoocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_shq8dbwoocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_shq8dbwoocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_shq8dbcommentmeta: Data: 0.05MB + Index: 0.03MB
wp_shq8dbcomments: Data: 0.06MB + Index: 0.09MB
wp_shq8dbdownload_log: Data: 0.08MB + Index: 0.02MB
wp_shq8dblinks: Data: 0.02MB + Index: 0.02MB
wp_shq8dboptions: Data: 3.17MB + Index: 0.06MB
wp_shq8dbpostmeta: Data: 3.48MB + Index: 0.42MB
wp_shq8dbposts: Data: 6.14MB + Index: 0.13MB
wp_shq8dbpum_subscribers: Data: 0.02MB + Index: 0.06MB
wp_shq8dbtermmeta: Data: 0.02MB + Index: 0.03MB
wp_shq8dbterms: Data: 0.02MB + Index: 0.03MB
wp_shq8dbterm_relationships: Data: 0.02MB + Index: 0.02MB
wp_shq8dbterm_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_shq8dbusermeta: Data: 0.11MB + Index: 0.14MB
wp_shq8dbusers: Data: 0.02MB + Index: 0.05MB
wp_shq8dbwc_download_log: Data: 0.02MB + Index: 0.03MB
wp_shq8dbwc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_shq8dbyoast_seo_links: Data: 0.13MB + Index: 0.02MB
wp_shq8dbyoast_seo_meta: Data: 0.05MB + Index: 0.00MB

### Post Type Counts ###

amn_exact-metrics: 1
attachment: 283
dlm_download: 9
dlm_download_version: 11
mc4wp-form: 1
nav_menu_item: 19
page: 23
popup_theme: 6
post: 39
product: 9
responsive_accordion: 1
revision: 422
shop_coupon: 3
shop_order: 85
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Akismet Anti-Spam: by Automattic – 4.0.8
Download Monitor: by Never5 – 4.1.1
Envato Market: by Envato – 2.0.1
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 5.3.5
jQuery Pin It Button for Images: by Marcin Skrzypiec – 2.4.3
MailChimp Forms by MailMunch: by MailMunch – 3.1.1
Responsive Accordion And Collapse: by wpshopmart – 2.0.3
ShortPixel Image Optimizer: by ShortPixel – 4.11.2
Social Pug: by DevPups
Mihai Iova – 1.4.9

tagDiv Composer: by tagDiv – 2.3 | built on 10.08.2018 17:39
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.14.13

Woo Checkout for Digital Goods: by Multidots – 2.3
WooCommerce Stripe Gateway: by WooCommerce – 4.1.9
WooCommerce: by Automattic – 3.4.5
Yoast SEO: by Team Yoast – 8.2
WP Super Cache: by Automattic – 1.6.4
WPForms Lite: by WPForms – 1.4.8.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #279 - /shop/
Cart: #280 - /cart/
Checkout: #281 - /checkout/
My account: #282 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Newspaper
Version: 9.0.1
Author URL: http://themeforest.net/user/tagDiv/portfolio
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: Newspaper/woocommerce/archive-product.php
Newspaper/woocommerce/single-product.php

`

**Comment by kloon** [comment]
This is a common issue that can be caused by numerous things such as your site URL, other plugins or even your theme, have a read and try the suggestions https://docs.woocommerce.com/document/paypal-standard/#section-14
