### ISSUE TITLE
How to find the ID Name for a CART ITEM Woocommerce

### ISSUE THREAD

**Issue by marwasaaid** [woocommerce/woocommerce#21342]
I want to use css to disable Adults element for a certain cart item/product. and I don't know where to locate the product ID name to use it.

This photo illustrates what I need:

I want to apply css for the circled element, in this item only. But i don't find it's ID name (unique identifier) while inspecting code on google chrome.
![image](https://user-images.githubusercontent.com/42501580/45482019-4141db80-b74d-11e8-8745-e362ed3fe17e.png)

**Comment by claudiulodro** [comment]
Hi there,

That element doesn't have a unique ID in the core WooCommerce templates. You can specify a new cart template that gives a unique ID to it with template overrides if you are developing a custom theme, but by default all quantity inputs will have the same class names. Hope this clears things up.
