### ISSUE TITLE
Woocommerce zoomimg not working in product page

### ISSUE THREAD

**Issue by bubbledesign** [woocommerce/woocommerce#21349]
Woocommerce zoomImg not working in product page, when you hover product image there is no zoom in on hover. Why zoomImg not in the class?

functions.php

`function u_setup() {
    add_theme_support( 'woocommerce' );
    add_theme_support( 'wc-product-gallery-zoom' );
    add_theme_support( 'wc-product-gallery-lightbox' );
    add_theme_support( 'wc-product-gallery-slider' );
}
add_action( 'after_setup_theme', 'u_setup' );`

See screenshot: [Single Product page](https://i.stack.imgur.com/mYSJD.png)

**Comment by kloon** [comment]
I'd start by checking for any JS errors as that might be usually the cause. WooCommerce uses Flexslider, Photoswipe, and the jQuery Zoom plugin to offer swiping, lightboxes and other neat features, these all are JS libraries and an issue with your JS can cause these not to load.

Unfortunately, I am unable to replicate this on a clean WooCommerce install so has to be something in your theme or perhaps a plugin causing this.
