### ISSUE TITLE
[WC 3.5.0-beta.1] Mixed languages in emails

### ISSUE THREAD

**Issue by Chrystll** [woocommerce/woocommerce#21348]
## Plugins & theme activated
WooCommerce 3.5.0-beta.1 
Storefront 2.3.3

## Issue description

The New account, New order and the Order on-hold emails are not fully sent in the language site. Some emails items are still in English.

I didn't reproduce this issue with WooCommerce 3.4.5.

## Steps to reproduce

Note: I didn't modify the Subject or the Email heading in WooCommerce > Settings > Emails.

1. Go to Settings > General > Site Language: set 'Français' for example.

2. Go to WooCommerce > Settings > Account & Privacy tab > Account creation: check "Allow customers to create an account during checkout"

3. Go to the Shop front as new customer > add a product to your cart > go to checkout > fill the billing form > check the create an account option > then place order

4. The New account body text is in English instead of being in French as shown here:
![new-account-email](https://user-images.githubusercontent.com/19824724/45493335-c5588b00-b76e-11e8-8ba0-6e7fe870a910.png)

5. The New order subject and some body text are in English instead of being in French as here:
![new-order-email](https://user-images.githubusercontent.com/19824724/45493349-cb4e6c00-b76e-11e8-8b28-5cbcc4c08886.png)

6. The Oder on-hold body text is in English instead of being in French as here:
![order-on-hold-email](https://user-images.githubusercontent.com/19824724/45493364-d4d7d400-b76e-11e8-9084-2eacca160b86.png)

**Comment by claudiulodro** [comment]
This is going to be because beta was just released and translations for all languages have not been completed yet. Translations are done by the volunteer community and should be ready by the time the actual release happens or shortly after.
