### ISSUE TITLE
Price filter is not working properly and displaying results outside of set parameters

### ISSUE THREAD

**Issue by nailbrain** [woocommerce/woocommerce#21350]
We're getting a strange issue on our WooCommerce website (https://laurenbagliore.com/) whereby the price filter is returning results outside of the set parameters.

We have the price set in WooCommerce's variations settings to 1095, however, when 990 is set to max it still returns this item in the results.

Here's a screenshot: https://prnt.sc/kqwds7

**Comment by kloon** [comment]
You are saying variations. Does any of the variation for that specific product perhaps have a price under or equal to 990? If so then it will show up in the filter, as a variation for that product matches the price range.

If you can reassure me that there are no variations for that product that matches the price range and have also tested with a default WooCommerce theme like Storefront or Twenty Seventeen with all plugin except WooCommerce enabled I will gladly reopen the issue and look into this further.
