### ISSUE TITLE
Products which have been set as draft showing up in related products

### ISSUE THREAD

**Issue by stuartduff** [woocommerce/woocommerce#21356]
**Describe the bug**

When a product is set to Draft those products seem to still be displayed within the related products.

**To Reproduce**
1. Go to products and set a previously related product to draft
2. Look at a product where this draft product was displaying as related and refresh the page several times

**Screenshots**

**Draft Product**
<img width="1364" alt="9hrkgx" src="https://user-images.githubusercontent.com/1190565/45540734-187d1d00-b805-11e8-97ba-9025e3b4af76.png">

**Draft product displaying within related products**
![aw6gbw](https://user-images.githubusercontent.com/1190565/45540779-38acdc00-b805-11e8-81e1-1ba260f879b1.gif)

**Expected behaviour**
I expected products which had been set as a draft to be immediately excluded from related products and not display on any section of the site.

**Comment by kloon** [comment]
Are you logged in as the Administrator/Author perhaps? Try viewing the product logged out and see if you still get the recommendations?

**Comment by invadersim** [comment]
Once you've changed the status to draft, make sure you hit update to confirm the change and report back on whether you still see the bug.

You should see 'save draft' and 'publish' rather than 'update' on the side menu.

**Comment by claudiulodro** [comment]
The actual query to get related products [will only get products in publish status](https://github.com/woocommerce/woocommerce/blob/1b405c2c12294470b32db53892bc8aa517391f2a/includes/data-stores/class-wc-product-data-store-cpt.php#L1178). The results are [cached for 1 day](https://github.com/woocommerce/woocommerce/blob/0cc137be1ede11561848bec5c85b321cf5771d47/includes/wc-product-functions.php#L913), so if you switch a published product to draft it will show up in the related products until the cache expires.

There isn't really a good way of programmatically deleting the appropriate product transients when a product status changes, as each product has its own transient and there isn't a way of querying those transients based on their cached content. We can maybe explore some sort of solution in the future, though.

**Comment by davewoodhall** [comment]
> Are you logged in as the Administrator/Author perhaps? Try viewing the product logged out and see if you still get the recommendations?

Sorry for the late comment, just faced the same issue. In my case, setting as a Draft was not enough, I had to set my product as Private.

**Comment by britandrews** [comment]
I just ran into this exact thing too. Has this ever been addressed or fixed? I did notice that viewing the same page in a private browser will not show the draft-mode related product. But, what would be the need for an Admin to still see a product if it was purposely set to Draft?

**Comment by leecollings-sb** [comment]
I don't think this issue should have been closed as I've just run into this now, and my products are certainly saved as 'Draft'. They are now showing up in Related Products, and I can add them to the basket and continue, which should not be allowed to happen.

@stuartduff Can you please advise as you were the one who closed the issue?

**Comment by davewoodhall** [comment]
> I don't think this issue should have been closed as I've just run into this now, and my products are certainly saved as 'Draft'. They are now showing up in Related Products, and I can add them to the basket and continue, which should not be allowed to happen.

In my case, I had to set them as Private (or only available if you are logged in); perhaps this would solve your issue?

Also, make sure you have no caching plugins enabled, sometimes they are tricky like that. I'd also try in a Private Window, just in case _something_ is cached in there, _somehow_.

**Comment by pixelstorm** [comment]
i have the same issue. this causes many 404 errors because the links in related products go to a 404 as they are linking to an unpublished product. I tried adding 
`add_filter( 'woocommerce_output_related_products_args', 'pxs_related_products_args', 20 );
function pxs_related_products_args( $args ) {
  $args['posts_per_page'] = 4; 
  $args['post_status'] = 'publish';
	return $args;
}
`
but still the issue remains
