### ISSUE TITLE
[3.5-beta.1] Custom placeholders don't resize in customizer.

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce#21359]
**Describe the bug**
Related to #20644.

In the Customizer, the defined placeholder image does not resize dynamically (see "No pic" in the screenshot):

<img width="1294" alt="screen shot 2018-09-14 at 10 09 47 am" src="https://user-images.githubusercontent.com/7317227/45564792-63e3fb00-b806-11e8-9972-b238660bece5.png">

On the frontend it resizes correctly. The issue is limited to the Customizer.

**To Reproduce**
1. Go to WooCommerce > Settings > Products and set a placeholder image.
2. Go to customizer and change aspect ratio. Observe placeholder doesn't resize.
3. Save aspect ratio settings. Observe placeholder is sized correctly on frontend.

**Expected behavior**
The placeholder should dynamically resize in the Customizer like the other product images.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by GlennMartin1** [comment]
@claudiulodro Thanks for opening this issue.

The issue you described here is distinct from what I reported on the Develop WooCommerce post.

Try this: If you set the placeholder image **by URL**, the aspect ratio doesn't work in front-end or back-end.

**Comment by claudiulodro** [comment]
@GlennMartin1 when you set it by URL there isn't much WooCommerce can do about resizing the image. The image may or may not be an attachment image located on the server, and even if it is an attachment image WooCommerce can't figure out which one it is using only the URL.

**Comment by GlennMartin1** [comment]
@claudiulodro Yes, it's on the server itself, but no problem - I'll just specify the ID.

**Comment by claudiulodro** [comment]
See. #21407
