### ISSUE TITLE
New 'tax "pretty" name' for tax rates

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#21357]
Nowadays when creating rates on WooCommerce there's only one field to identify the rate, the "Tax name" field:

![image](https://user-images.githubusercontent.com/6853605/45543819-7f9ecf80-b80d-11e8-886c-fdea08459fe9.png)

In order to integrate with external services, like invoicing APIs, for example, sometimes we'll need to use this field for the ID of the tax rate on the external service, as the only way to link the WooCommerce tax rate with the external API tax rate:

![image](https://user-images.githubusercontent.com/6853605/45543898-bd035d00-b80d-11e8-98cc-d318b297d050.png)

Because of this, we end up with ugly stuff like this on the website:

![image](https://user-images.githubusercontent.com/6853605/45544039-21beb780-b80e-11e8-8aa5-24dd0ad5a4b1.png)

I recommend that a new 'tax "pretty" name' field is created. That new field would be used to show on the website, emails, etc... whenever it is populated, instead of `$tax->label`. This would not be a mandatory field and would default to the current tax name when outputting to the website visitor.

Alternatively a filter for `$tax->label` could be implemented on `templates/cart/cart-totals.php`, `includes/admin/meta-boxes/views/html-order-items.php`, `templates/checkout/review-order.php`, etc, but only at the very last moment before outputting to the HTML. Anyway, I don't think this is the best solution.
A filter on `WC_Order_Item_Tax->get_label()` is not a solution because we would lost the ability to use the original name for the API integrations.

**Comment by kloon** [comment]
This sounds very plugin specific to me. Why does the plugin doing the integration not add the field? The plugin in question can also instead of using a new filed just convert the name field to a format that is accepted by the external service, ie running it through something like sanitize_title to remove spaces etc.

Sorry but to me this is very specific to a plugin and can be solved by that plugin as well, adding something like this to WooCommerce core will have no advantage, just add a field that is not used by default.

**Comment by kloon** [comment]
You can use the filter `woocommerce_get_settings_pages` to override the tax settings page in WooCommerce with your own. So in your plugin create a new WC_Settings_Tax class based on the one in core and just include it via that filter, in your new class you can add the additional fields you require, as long as the original fields are still intact you should not have any issues in your new tax class.
