### ISSUE TITLE
cart rest api not save with user id

### ISSUE THREAD

**Issue by nayanphpd** [woocommerce/woocommerce#21361]
The issue is we call add to cart API its work but not add this cart to the particular user.
Means first we call login API. the user will logged in. after we add the product to cart. but this product does not synchronize with the user because add to cart method use session data and with API it’s not possible.

**Comment by kloon** [comment]
WooCommerce core does not have an add to cart API, you should be managing cart/session inside your application and then when creating the order through the API assign the user to the order.
