### ISSUE TITLE
Add hook for variation header in variations list when editing a product

### ISSUE THREAD

**Issue by kinging123** [woocommerce/woocommerce#21362]
**Is your feature request related to a problem? Please describe.**
Developers right now don't have the ability to add custom information/buttons to the variation list in product editing page.

![image](https://user-images.githubusercontent.com/5137073/45587578-2f5c6600-b910-11e8-82bf-ad371ed66d38.png)

Currently, there is no hooks at all there:
https://github.com/woocommerce/woocommerce/blob/ea9aa8cd59c9fa735460abf0ebcb97fa18f80d03/includes/admin/meta-boxes/views/html-variation-admin.php#L15-L51

**Describe the solution you'd like**
Added a new action called `woocommerce_variation_header` to the variations list in product editing screen, in the variation header (`h3` tag) after all the actions (e.g. remove, sort, etc.).

This would allow developers to add their own actions or information to the variation list.

For example:
![image](https://user-images.githubusercontent.com/5137073/45587622-dfca6a00-b910-11e8-9d3f-4cbb24c76ccc.png)

I have opened a pull request, #21341, which adds this hook under the name of `woocommerce_variation_header`:

https://github.com/woocommerce/woocommerce/pull/21341/files#diff-bd366a57ec65442d32cc3ee82b5be405

**Comment by lkraav** [comment]
I wonder if core could also include an example use case with this PR

```php
        /**
         * Admin variation list needs clarity.
         *
         * @param \WP_Post $variation .
         * @see https://github.com/woocommerce/woocommerce/issues/21362
         * @since 2018.10.23
         */
        add_action( 'woocommerce_variation_header', function( \WP_Post $variation ) {

            $variation = wc_get_product( $variation->ID );
            $sku       = $variation->get_sku();

            if ( $sku ) {
                printf( 'SKU: <strong>%s</strong>', esc_attr( $sku ) );
            }

        } );
```

**Comment by kloon** [comment]
Added in #21341
