### ISSUE TITLE
Unit tests: Don't use assertEquals where type and equality are important.

### ISSUE THREAD

**Issue by birgire** [woocommerce/woocommerce#21363]
Regarding the unit test documentation for WooCommerce:
https://github.com/woocommerce/woocommerce/tree/master/tests

it says that:

> Prefer assertsEquals() where possible as it tests both type & equality

I think this is meant to be `assertSame()` as `assertEquals()` doesn't actually test the type.

These assertions will pass successfully: 

```
$this->assertEquals( null, false );
$this->assertEquals( null, '' );
$this->assertEquals( null, 0 );
$this->assertEquals( true, 99999 );
$this->assertEquals( true, -1 );
$this->assertEquals( false, 0 );

```
But these will fail:

```
$this->assertSame( null, false );
$this->assertSame( null, '' );
$this->assertSame( null, 0 );
$this->assertSame( true, 99999 );
$this->assertSame( true, -1 );
$this->assertSame( false, 0 );

```

These are just examples, where in general one would use `assertFalse`, `assertTrue `and `assertNull `for explicit `false`, `true `and `null `assertions.

As an example from WooCommerce this assertion:

`$this->assertEquals( '', $query->get( 'total' ) );
`

will allow the get method to return either `false`, `''` or `null`.

There seems to be very few `assertSame` in use:

https://github.com/woocommerce/woocommerce/search?q=assertSame&unscoped_q=assertSame

compared to the many cases of `assertEquals`. 

PS: There's also a typo in that documentation , the function is `assertEquals()`, not `assertsEquals()`.

**Comment by kloon** [comment]
Thanks for logging, seems like a good first issue for someone to take on that want to contribute. At least just update the readme with the correct details, we can take on the existing tests later if not part of the first PR.

**Comment by devdrops** [comment]
I'll handle this :wink:
