### ISSUE TITLE
Unit tests: Use assertCount for count assertions

### ISSUE THREAD

**Issue by birgire** [woocommerce/woocommerce#21365]
The `assertCount` is available for count assertions, since PHPUnit 3.5, so instead of e.g.

`$this->assertEquals( 2, count( $products ) );
`

we could use:

`$this->assertCount( 2, $products );
`

The `assertCount` is actually used in few other unit tests in WooCommerce, so this change would make the count assertions more consistent over all

**Comment by claudiosanches** [comment]
See https://github.com/woocommerce/woocommerce/pull/21366
