### ISSUE TITLE
Image upload to different directory than uploads

### ISSUE THREAD

**Issue by taich001** [woocommerce/woocommerce#21367]
Is it possible to upload media files like images in a different directory like "/wp-content/uploads/item/id3028/".

The reasons for this are:
1.) you are running out of file names. If you have a lot product images it ist very likely that you already have an image with the same name. With all images in one directory this will lead to a name conflict.

2.) 2000 products in a shop will have at least 2000 images, and this leads to 8000 or even more image files. All this in one directory is very confusing.

I think it would be a good idea to expand REST API and have an additional parameter like "target_dir" where the uploaded image file should be stored.

**Comment by kloon** [comment]
WooCommerce uses the standard WordPress upload functionality. If you want to change the location and names of uploads you will need to hook into the WordPress media uploaded system and change it there.

Have a look at this StackExchange with details on how to achieve this for a specific post type. You will need to apply this to products https://wordpress.stackexchange.com/questions/76895/different-upload-directory-based-on-post-type-in-a-theme

**Comment by taich001** [comment]
Well, finally I decided to make it directly in database. Insert the image in wp_posts and wp_postmeta and you are done. This is faster, easier and more relyable for me.
