### ISSUE TITLE
'Description' and 'Additional Information' displaying TWICE

### ISSUE THREAD

**Issue by sanjanapai** [woocommerce/woocommerce#21364]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. See ScreenGrab 01 - When you click on the individual product, the Product Image and Product Description is showing as usual
2. See ScreenGrab 02 - Product Image & Description is displaying AGAIN under 'Description' section
3. See ScreenGrab 03 - Actual data displaying under 'Description' section is showing here

## Expected/actual behavior
Data in ScreenGrab 03 should show under data in ScreenGrab 01

When I follow those steps, I see...
ScreenGrab02

I was expecting to see...
ScreenGrab03

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>
![screengrab 01](https://user-images.githubusercontent.com/43310818/45594038-1788ee80-b9b1-11e8-83b9-b1b90d7b1193.PNG)
![screengrab 02](https://user-images.githubusercontent.com/43310818/45594039-1788ee80-b9b1-11e8-934a-ab9dd4286390.PNG)
![screengrab 03](https://user-images.githubusercontent.com/43310818/45594040-18218500-b9b1-11e8-980f-bef2735231e3.PNG)

**Comment by kloon** [comment]
This is most probably an issue with your theme and or a plugin you have active. To test disable all plugins except just WooCommerce and then switch your theme to a default one like Storefront or Twenty Seventeen and test again.

I am unable to replicate this with a default theme and just WooCommerce active.
