### ISSUE TITLE
Product pagination does not reflect product sorting oder

### ISSUE THREAD

**Issue by geeklore** [woocommerce/woocommerce#21375]
**Describe the bug**
With the Product Pagination enabled for the Product Page and the sort order set to `Default sorting (custom ordering +name)` the sort order is displayed on the shop page as expected. But the pagination does not paginate according to the sort order. It's looks like it's by publish date, but sometimes there are no products loaded into the pagination.

**To Reproduce**
1. Please test with the Storefront thme. Go to **Appearance -> Customization -> WooCommerce -> Product Catalog** and make sure that **Default product sorting** is set to `Default sorting (custom ordering + name)`.
2. Go to **Appearance -> Customization -> Product Page** and make sure **Product Pagination** is enabled.
3. Go to the Products page and click on the sorting option and drag and drop to create an order.
4. Visit the Shop page and confirm that the order is as expected.
5. Click on a product and then look for the previous and next links for the previous and next products.
6. You should see that the order does not reflect the sorting.

**Screenshots**
![see screen shot](http://cld.wthms.co/UOKRG4+)
Link: http://cld.wthms.co/UOKRG4

![see screen shot](http://cld.wthms.co/MSbzxa+)
Link: http://cld.wthms.co/MSbzxa

![see screen shot](http://cld.wthms.co/ftKZU5+)
Link: http://cld.wthms.co/ftKZU5

**Expected behavior**
The expectation is that the pagination order would follow the same as the sorted order.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: https://sellanything.blog
Site URL: https://sellanything.blog
WC Version: 3.4.5
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.31 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.61.0
OpenSSL/1.1.0f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.17-MariaDB
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.5
WC Database Prefix: wp_
Total Database Size: 29.54MB
Database Data Size: 21.27MB
Database Index Size: 8.27MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.13MB + Index: 0.14MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB
wp_cart_notices: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.09MB + Index: 0.09MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB
wp_followup_email_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_email_orders: Data: 0.06MB + Index: 0.09MB
wp_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB
wp_followup_followup_history: Data: 0.08MB + Index: 0.05MB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 2.19MB + Index: 0.06MB
wp_postmeta: Data: 11.48MB + Index: 5.97MB
wp_posts: Data: 1.31MB + Index: 0.38MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_snippets: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.05MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.06MB + Index: 0.05MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.03MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_bundled_itemmeta: Data: 0.03MB + Index: 0.03MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_exported_csv_items: Data: 0.14MB + Index: 0.02MB
wp_woocommerce_gpf_google_taxonomy: Data: 2.02MB + Index: 0.00MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_wpml_mails: Data: 2.52MB + Index: 0.00MB
wp_wp_optimisation_sizes_info: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 111
bookable_person: 8
bookable_resource: 10
custom_css: 1
customize_changeset: 19
event_ticket: 17
follow_up_email: 8
jetpack_migration: 2
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
nav_menu_item: 28
oembed_cache: 1
page: 31
post: 1
product: 114
product_variation: 993
revision: 81
scheduled-action: 103
shop_coupon: 7
shop_order: 46
shop_order_refund: 3
shop_subscription: 3
wc_booking: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.4.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #3 - /
Cart: #4 - /cart/
Checkout: #5 - /checkout/
My account: #6 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.2 – 2.3.3 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: storefront/woocommerce/emails/admin-new-order.php
`
```
</details>

**Comment by kloon** [comment]
@geeklore I just tested this now with the 3.5 Beta version and Storefront 2.3.3 as well as Twenty Seventeen and it works as expected for me. If I set two product under each other menu order one 100 and the other -1, the 100 one shows on page 2 and the -1 first on page one.

Can you perhaps test using the 3.5 beta as well as with the latest version of Storefront? I'll gladly reopen the issue if there are replicable steps.

**Comment by geeklore** [comment]
@kloon I just tested with both, but I am having the same issue. I am testing here. I can send you the login if you would like. https://sellanything.blog/

**Comment by AashikP** [comment]
@kloon I could replicate it with the latest pre-release and Storefront 2.3.3

![https://cld.wthms.co/QFLZra+](https://cld.wthms.co/QFLZra+)
Full Image: https://cld.wthms.co/QFLZra+

**Comment by AashikP** [comment]
Ticket 1410174-zen is back on top of the queue. I just realized that there are no labels on the report. Setting `High-bug` for now since this effects everyone.

**Comment by kloon** [comment]
Thanks for the images, from that it looks like this is not related to the default pagination but something unique to Storefront or a plugin perhaps?

**Comment by cphansson** [comment]
Hi @geeklore 

I had the same problem. I'm using OceanWP theme and done the usual theme/plugin conflict test with the same outcome..

I posted directly on Woo's support desk. Here's part of their reply

_"Thank you so much for your patience on waiting for this bug to be fixed. We have already reported this to our devs and it is currently in the developer's list of bugs to resolve.
Since this might take a couple of weeks though, I will go ahead and close this ticket for now. You can follow the progress of this report by clicking on the subscribe button on the **bug report page**."_

That was over 2 weeks ago, the link to the bug report brought me here...

**Comment by geeklore** [comment]
@kloon The above report is with a different theme. Testing with default themes is difficult because the pagination like Storefront does is not super common. I am happy to file a bug with Storefront if you think this is a bug with out Storefront and other themes that paginate like Storefront handle this.

**Comment by kloon** [comment]
Shane, yes please open a issue on Storefront as this is not standard pagination.

Thanks!

**Comment by kloon** [comment]
Closing this as the code that fetches the links is part of the theme and not WooCommerce core, this will have to be fixed inside the themes.
