### ISSUE TITLE
WooThemes mentions

### ISSUE THREAD

**Issue by corsonr** [woocommerce/woocommerce#21371]
**Describe the bug**
It's not a bug by itself, but the `bn` value in PayPal params is still mentioning WooThemes: 

https://github.com/woocommerce/woocommerce/blob/d0491072e8a7d0a4535db0ec2bae4a6d43ff64fd/includes/gateways/paypal/includes/class-wc-gateway-paypal-request.php#L125

It doesn't bug me that much, but I just wanted to point this out.

**Comment by kloon** [comment]
@pmaiorana is this save to change to something else?

**Comment by pmaiorana** [comment]
No, it's not safe to change—we'll need to coordinate with PayPal, and I don't think it's a high priority right now. Recommend closing as a `wontfix`.

**Comment by kloon** [comment]
Thanks Paul.
