### ISSUE TITLE
The string "Local Pickup" does not exist making it not possible to implement Multi lingual translation with a plugin like polylang

### ISSUE THREAD

**Issue by spraveenitpro** [woocommerce/woocommerce#21376]
**Is your feature request related to a problem? Please describe.**
The string "Local Pickup" does not exist making it not possible to perform multi lingual translation with a plugin like [polylang](https://en-ca.wordpress.org/plugins/polylang/).

**Describe the solution you'd like**
The string "Local Pickup" to be made available in order to perform multilingual translation with a plugin like [polylang](https://en-ca.wordpress.org/plugins/polylang/).

**Comment by kloon** [comment]
Definitely translatable see it part of the Spanish translation https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/es/default?filters%5Bterm%5D=Local+Pickup&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc
