### ISSUE TITLE
External/Affiliate Product Button attempts to add to cart, does not redirect to specified URL

### ISSUE THREAD

**Issue by astupidmoose** [woocommerce/woocommerce#21387]
**Describe the bug**
When adding an "External/Affiliate Product" you can specify a link that is the external URL. The expected behaviour is for the button that is generated to link to an external site, or a page specified. 

As of the latest version of woocommerce, these links are broken and now attempt to add a product to the cart, however since its not a product it simply returns you to an empty cart. 

**To Reproduce**
1. Create a External/Affiliate Product
2. Specify URL
3. Visit Product Page
4. Click the button to be redirected, see that cart is being called instead. 

**Expected behavior**
Button being clicked should redirect you to a new url, specific to product settings. 

**Isolating the problem (mark completed items with an [x]):**
- [X] I can reproduce this bug consistently using the steps above.

**Comment by astupidmoose** [comment]
I ended up finding the issue, in templates/single-product/add-to-cart/external.php:22

Submitted a fix by removing the cart class:
https://github.com/woocommerce/woocommerce/pull/21388

**Comment by claudiulodro** [comment]
Discussion at #21388
