### ISSUE TITLE
GUID is not unique for product_variation

### ISSUE THREAD

**Issue by manake** [woocommerce/woocommerce#21380]
**Describe the bug**
GUID is not unique for `product_variation`.

**Expected behavior**
GUID is unique.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by claudiulodro** [comment]
Thanks for the report. I've confirmed the issue. Variations have the URL for the parent product as the GUID.

**Comment by kloon** [comment]
See #22324
