### ISSUE TITLE
[3.5-beta.1] issue when deleting all the terms from the Attributes tab

### ISSUE THREAD

**Issue by Chrystll** [woocommerce/woocommerce#21383]
## Plugins & theme activated
WooCommerce 3.5.0-beta.1 
Storefront 2.3.3

## Issue description

In the product Attributes tab, if you delete all the terms from the global attribute metabox, this metabox disappears. And I'm not able to select it again in the list since the attribute is greyed. I don't reproduce this behavior with WooCommerce 3.4.5.

## Steps to reproduce

1. Create a simple product
2. Go to Attributes tab > add a global attribute here 'Color' > add a term as here:
![screenshot-localhost-2018 09 18-15-38-02](https://user-images.githubusercontent.com/19824724/45691420-e9461300-bb58-11e8-8052-4ff04ca793d1.png)

3. Remove the term and save your changes: the 'Color' metabox has disappeared and 'Color" is greyed in the attributes list as shown below:
![capture du 2018-09-18 15-39-43](https://user-images.githubusercontent.com/19824724/45692570-62df0080-bb5b-11e8-93af-a79347c77594.png)

In WooCommerce 3.4.5 the 'Color' metabox is still there after removing all the terms.

**Comment by kloon** [comment]
See #21446
