### ISSUE TITLE
Wocommerce API request - error 500

### ISSUE THREAD

**Issue by swietnegranie** [woocommerce/woocommerce#21394]
I use bundle Automattic\WooCommerce to connect with my woocommerce shop api and now I have an error 500 'Sorry, but you can not view this resource.'  when I send request GET to my shop api. 

Perhaps this is due to blocking the port on the server after which requests to the api are received. What is the port for api in woocommerce?

Thanks for every help.

**Comment by kloon** [comment]
Check your error logs to see what the error message is. 500 Server errors are fatal errors usually caused by syntax errors in your code.

I am unable to replicate a 500 error accessing the API using the latest version of WooCommerce. Will gladly reopen if I have steps to replicate this.
