### ISSUE TITLE
Quick editing a product: setting stock quantity to 0 saves NULL to database

### ISSUE THREAD

**Issue by Rayken** [woocommerce/woocommerce#21392]
**Describe the bug**
If you set a products stock quantity to 0 using quick edit, NULL gets saved to the database instead of the actual 0. However, setting it to 0 using the inventory tab works as expected - storing 0 to the database instead of NULL.

**To Reproduce**
1. Go to products
2. Click on quick edit
3. Set stock to 0
4. Update the product
5. Check post meta and see NULL instead of 0

**Expected behavior**
Stocks should be numerical. They could be negative, they could be positive and surely zero too! If I manually set the stock to 0 using quick edit, I expect it to be 0 and not NULL.

**Isolating the problem (mark completed items with an [x]):**
- [ X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ X ] I can reproduce this bug consistently using the steps above.

_ Latest WordPress and WooCommerce _

**Findings**
This occurs because there is a check against `$_REQUEST['_stock']` being `empty()` and because a value of 0 will return true the check fails.

The check that is faulty:
https://github.com/woocommerce/woocommerce/blob/48a0045373816d179bcc6344b32d52bf417e532b/includes/admin/class-wc-admin-post-types.php#L408

**A fix**
So instead of using empty on, what I believe only should be numerical values since the input is "number", we use `is_numeric`. This does allow an empty value as before and falls back to being NULL. But, fixes 0 not being 0.

```PHP
$stock_amount = 'yes' === $manage_stock && is_numeric( $_REQUEST['_stock'] ) ? wc_stock_amount( $_REQUEST['_stock'] ) : '';
```

If this fix isn't applicable or something else needs to be done, the actual line where the value gets set to NULL is:
https://github.com/woocommerce/woocommerce/blob/48a0045373816d179bcc6344b32d52bf417e532b/includes/abstracts/abstract-wc-product.php#L950

**Implications**
If your e-commerce builds on manually managing stock and allowing backorders, backordering becomes a huge part of the business. How many items do we need to restock to fill the backorders? Now the implication is this; if a product has NULL stock, and a customer orders 200 items through backorder, 200 - NULL is still NULL and that shows as 0 - meaning it's a false representation of the backorders (even though they're actual orders). This happened. Thankfully I caught this bug before things got way out of hand. It is however a very specific chain of circumstance, it only applies to products manually having been set to 0 through quick edit and any ordering of that product after would have an invalid stock. Just thought I'd add this in here, maybe it will bump the importance of the fix somewhat. In our case, we had a product that should've been -213 but was 0 which obviously caused confusion. Thanks!

**Comment by rodrigoprimo** [comment]
I was able to reproduce this problem, and we will work on a fix unless you would prefer to submit a PR? I haven't put much thought into this but your suggestion to use `is_numeric()` looks good to me.

This bug was introduced after the change below that was introduced in WooCommerce 3.3.0:

https://github.com/woocommerce/woocommerce/commit/8f37ea33edae4a3d9df045b636a5e4e98b29149a#diff-a116210e8adc50b0853846ba935daaadL1073

Thanks for your contribution.

**Comment by Rayken** [comment]
Thanks for confirming the bug. You go ahead and work on a fix you find suitable!

**Comment by kloon** [comment]
See #21447
