### ISSUE TITLE
Woocommerce API function taking long time for update variable product Quantity  

### ISSUE THREAD

**Issue by sarun007** [woocommerce/woocommerce#21390]
Hi i am using woocommerce API function for updating the 1000 variations quantity. For updating 1000 variation product it taking more than 15 minutes time. why it taking so many time ? How to reduce the execution time ? How i update lot of product variation with less execution time ?
Following are my code 

```
function update_variation_inventory($sku, $new_stock_qty) {
    global $woocommerce;
    $product_search_data = [
      'sku' => $sku
    ];

    $json_object = $woocommerce->get('products', $product_search_data);

    $array = json_decode(json_encode($json_object),true);
   // var_dump($array);
    $variation_ID = $array[0]["id"];
    $parent_ID = $array[0]["parent_id"];
   echo $sku_id = $array[0]["sku"];

    $new_product_data = [
        'stock_quantity' => $new_stock_qty
    ];
     //$woocommerce->put('products/' . $parent_ID . '/variations/' . $variation_ID, $new_product_data);
if($parent_ID){
    $woocommerce->put('products/' . $parent_ID . '/variations/' . $variation_ID, $new_product_data);

    echo 'Updated product with ID:' . $variation_ID . ' Sku:' . $sku .
          ' with new qty: ' . $new_stock_qty . "<br />";
    }else{
    echo 'No Product with this SKU : '.$sku. "<br />";
    }
}

```

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: http://woocommerce-188476-557452.cloudwaysapps.com
Site URL: http://woocommerce-188476-557452.cloudwaysapps.com
WC Version: 3.4.3
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.31-1~dotdeb+8.1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 10 MB
PHP Time Limit: 0
PHP Max Input Vars: 5000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.60-0+deb8u1 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 459.69MB
Database Data Size: 280.33MB
Database Index Size: 179.36MB
wp_woocommerce_sessions: Data: 0.14MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 1.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_cf_forms: Data: 0.02MB + Index: 0.02MB
wp_cf_form_entries: Data: 0.02MB + Index: 0.06MB
wp_cf_form_entry_meta: Data: 0.02MB + Index: 0.03MB
wp_cf_form_entry_values: Data: 0.02MB + Index: 0.05MB
wp_cf_pro_messages: Data: 0.02MB + Index: 0.00MB
wp_cf_tracking: Data: 0.02MB + Index: 0.00MB
wp_cf_tracking_meta: Data: 0.02MB + Index: 0.03MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_csv_data: Data: 0.02MB + Index: 0.00MB
wp_duplicator_packages: Data: 0.02MB + Index: 0.02MB
wp_frm_fields: Data: 0.02MB + Index: 0.03MB
wp_frm_forms: Data: 0.02MB + Index: 0.02MB
wp_frm_items: Data: 0.02MB + Index: 0.08MB
wp_frm_item_metas: Data: 0.02MB + Index: 0.03MB
wp_hidemysiteSecure: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mail_bank: Data: 0.02MB + Index: 0.00MB
wp_mail_bank_email_logs: Data: 0.08MB + Index: 0.00MB
wp_mail_bank_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB
wp_nf3_action_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_chunks: Data: 0.02MB + Index: 0.00MB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB
wp_nf3_field_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB
wp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB
wp_nf3_upgrades: Data: 0.05MB + Index: 0.00MB
wp_options: Data: 5.14MB + Index: 1.05MB
wp_pmxe_exports: Data: 0.08MB + Index: 0.00MB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB
wp_pmxe_posts: Data: 6.52MB + Index: 0.00MB
wp_pmxe_templates: Data: 0.02MB + Index: 0.00MB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB
wp_pmxi_images: Data: 1.52MB + Index: 0.00MB
wp_pmxi_imports: Data: 1.52MB + Index: 0.00MB
wp_pmxi_posts: Data: 15.48MB + Index: 11.03MB
wp_pmxi_templates: Data: 0.23MB + Index: 0.00MB
wp_postmeta: Data: 218.75MB + Index: 145.42MB
wp_posts: Data: 22.48MB + Index: 15.92MB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.11MB + Index: 0.14MB
wp_terms: Data: 0.13MB + Index: 0.16MB
wp_term_relationships: Data: 5.52MB + Index: 4.45MB
wp_term_taxonomy: Data: 0.13MB + Index: 0.16MB
wp_usermeta: Data: 0.06MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
_mig_wpmdb_alter_statements: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

acf: 1
al_product: 1
attachment: 7119
cf7_style: 12
custom_css: 2
et_pb_layout: 1
frm_form_actions: 2
frm_styles: 1
nav_menu_item: 11
page: 14
post: 1
product: 1150
product_variation: 55497
revision: 51
shop_order: 2
wcpa_pt_forms: 2
wpcf7_contact_form: 1
wpforms: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (33) ###

ManageWP - Worker: by ManageWP – 4.6.2
AJAX Search for WooCommerce: by Damian Góra – 1.1.7 – Not tested with the active version of WooCommerce
All-in-One WP Migration: by ServMask – 6.70
Autoptimize: by Frank Goossens (futtta) – 2.3.4
Breadcrumb NavXT: by John Havlik – 6.1.0
Breeze: by Cloudways – 1.0.10
Caldera Forms: by Caldera Labs – 1.7.2
Carousel Slider: by Sayful Islam – 1.8.8 – Not tested with the active version of WooCommerce
CMB2: by CMB2 team – 2.4.2
Contact Form 7: by Takayuki Miyoshi – 5.0.2
Divi Builder: by Elegant Themes – 2.8
Force Regenerate Thumbnails: by Pedro Elsner – 2.0.6
GA Google Analytics: by Jeff Starr – 20180506
Hide My Site: by Justin Saad – 2.0.5
Kirki Toolkit: by Aristeides Stathopoulos – 3.0.33
MailChimp for WordPress: by ibericode – 4.2.3
PW WooCommerce Bulk Edit: by Pimwick
LLC – 2.47 – Not tested with the active version of WooCommerce

Really Simple SSL: by Rogier Lankhorst – 3.0.2
Search Engine Visibility: by GoDaddy – 0.5
Show Current Template: by JOTAKI Taisuke – 0.3.0
TWP Shortcodes: by Themes4WP – 1.0.12 – Not tested with the active version of WooCommerce
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.14.11.24

WooCommerce Dynamic Pricing & Discounts: by RightPress – 2.2.6 – Not tested with the active version of WooCommerce
Woocommerce Custom Product Addons: by  – 3.4.3 – Not tested with the active version of WooCommerce
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.18 – 1.10.19 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.4.3 – 3.4.5 is available
WordPress Importer: by wordpressdotorg – 0.6.4
WP All Export Pro: by Soflyy – 1.5.3
WP All Import Pro: by Soflyy – 4.5.4
WP Mail, Email Logs, Gmail SMTP, PHP Mailer - Mail Bank: by Tech Banker – 3.0.64
Smush: by WPMU DEV – 2.7.9.1
WP All Import - WooCommerce Add-On Pro: by Soflyy – 2.4.1 – Not tested with the active version of WooCommerce
YITH WooCommerce Ajax Product Filter: by YITHEMES – 3.5.1 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Divi Child
Version: 3.4.1.1532338531
Author URL: http://www.elegantthemes.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.4.1
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by sarun007** [comment]
why there is no response form your side ?

**Comment by claudiulodro** [comment]
Hi there,

To reduce execution time you can use the [batch update](https://woocommerce.github.io/woocommerce-rest-api-docs/#batch-update-products) which will reduce the number of API requests you need to make. Your code seems to make 3 API requests for each product, so it will naturally take a long time as you are making 3000 API requests.

Closing this issue, as we can't provide developer support on GitHub and only investigate bugs. For support with custom development I recommend [the forums](https://wordpress.org/support/plugin/woocommerce/).

Thanks.
