### ISSUE TITLE
woocommerce variation error

### ISSUE THREAD

**Issue by guru75** [woocommerce/woocommerce#21404]
We don't offer technical support on GitHub so we recommend using the following:

**Reading our documentation**
Usage docs can be found here: https://docs.woocommerce.com/

If you have a problem, you may want to start with the self help guide here: https://docs.woocommerce.com/document/woocommerce-self-service-guide/

**Technical support for premium extensions or if you're a WooCommerce.com customer**
 from a human being - submit a ticket via the helpdesk
https://woocommerce.com/contact-us/ 

**General usage and development questions**
- WooCommerce Slack Community: https://woocommerce.com/community-slack/
- WordPress.org Forums: https://wordpress.org/support/plugin/woocommerce
- The WooCommerce Help and Share Facebook group

**Comment by claudiulodro** [comment]
Hi there,

I recommend visiting one of the support links in the issue you've created to get further help on your issue. We cannot provide support on GitHub for setting up a shop.

Thanks.
