### ISSUE TITLE
Dimensions in RTL Languages are displayed incorrectly on single product pages

### ISSUE THREAD

**Issue by joelwills** [woocommerce/woocommerce#21406]
**Describe the bug**

In LTR a dimension section on a single product page is displayed as e.g:

`10 x 10 x 5 in`

![Screenshot](http://joelwills.com/LQfIiM+)

Link to image: http://joelwills.com/LQfIiM

In any RTL language, it's:

`x 10 x 5 in 10`

![Screenshot](http://joelwills.com/UkWW8q+)

Link to image: http://joelwills.com/UkWW8q

When it should be:

`in 10 x 10 x 5`

**To Reproduce**
1. Go to any product that displays dimensions
2. Under Settings > Site Language in WordPress set the language to an RTL language
3. View product and see dimensions are displayed incorrectly

Tested with just Storefront and latest master of WooCommerce active (Version 3.5.0-beta.1).

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by kloon** [comment]
See #21633 for fix.
