### ISSUE TITLE
Anomalies in the i18n continents and country data  

### ISSUE THREAD

**Issue by Vusys** [woocommerce/woocommerce#21413]
1. Netherlands Antilles is listed in the list of countries in the [continents file](https://github.com/woocommerce/woocommerce/blob/0566708744e109c6b50e630f8099a4735eac33a9/i18n/continents.php#L208) but not the countries file. I believe this is an oversight from [this change](https://github.com/woocommerce/woocommerce/commit/135316033067046dad462d86b50c2f7bcaa2b24b#diff-7af2f76a23c1a0a116c8e8a480ad55fe). I would just remove it from the file and submit a PR, but I'm not sure if there would be any unintended consequences of me doing so. 

2. Cyprus is listed twice in the continents file. [Once in Europe](https://github.com/woocommerce/woocommerce/blob/0566708744e109c6b50e630f8099a4735eac33a9/i18n/continents.php#L157) and then [again in Asia](https://github.com/woocommerce/woocommerce/blob/0566708744e109c6b50e630f8099a4735eac33a9/i18n/continents.php#L101). It's probably correct to remove it from Asia, but again, not sure what would happen if I did.

**Comment by kloon** [comment]
See #21449 for the NA fix. Regarding Cypress, it seems it can be seen as in both continents https://www.worldatlas.com/articles/is-cyprus-in-europe-or-asia.html so leaving that as is.
