### ISSUE TITLE
Placeholder image size is wrong on the single product page

### ISSUE THREAD

**Issue by pierrebuet** [woocommerce/woocommerce#21415]
When using an attachment ID for the placeholder image, the thumbnail size of it is displayed on the single product page, not the size for single product image ( woocommerce_single ). Using wc_placeholder_img_src('woocommerce_single') in a template override doesn't work, since the actual wc_placeholder_img_src function translates the size in an array of dimensions, where woocommerce_single doesn't have an height.

**Comment by claudiulodro** [comment]
#21416
