### ISSUE TITLE
When product price changed in admin - bad price on thank you page

### ISSUE THREAD

**Issue by MajkieS** [woocommerce/woocommerce#21418]
Hello,

I am using latest woocommerce 3.4.5 with theme Storefront, no modules (only testing).

The thing is: You have a product A, for 50$, customer adds it into cart and starts checkout. While he fills in all his details and is about to click "Submit order" button. In that moment he has everything filled in (so no additional refresh (Ajax)) is happening and only the button click is remaining, you as admin set price from $50 to $55. (The customer has chosen cash on delivery). So instead of ordering for $50, he clicks that buttons, but "Thank you page" says $55 because the product was edited.

It does not affect already created orders (there it is okay and doesn't change)

I know this is an unlikely event to happen, but is it a bug, or normal behavior?

Thank you!

**Comment by claudiulodro** [comment]
This is normal behavior. Any changes you make to taxes, shipping, price, etc. will be updated each time the customer's cart is recalculated. The final price is set in the order when the checkout is processed and will not change when prices are changed after that. Hope this clears things up.
