### ISSUE TITLE
woocomerce stock variation

### ISSUE THREAD

**Issue by guru75** [woocommerce/woocommerce#21411]
I need a stock management system like describe below:-

Sleeve | Color | Size | Stock
-- | -- | -- | --
Full Sleeves | Red | XL | **3**
Full Sleeves | Blue | XS | 6
Half Sleeves | Red | XL | 1
Half Sleeves | Blue | XS | 4

I am selling product by variation like:- Type, Color, Design Color, Size
If customer purchase “full sleeve – red – blue-XL” then I want that the from whole stock  “full sleeve-red-blue-xl” get subtracted 
So I get the following

Sleeve | Color | Size | Stock
-- | -- | -- | --
Full Sleeves | Red | XL | **2**
Full Sleeves | Blue | XS | 6
Half Sleeves | Red | XL | 1
Half Sleeves | Blue | XS | 4

**Comment by soft79** [comment]
That's exactly how WC works.

**Comment by claudiulodro** [comment]
As @soft79 this is exactly how WC works if you have variations set up with sleeves, color, and size attributes. Hope this clears things up.

We can only investigate bug reports on GitHub, so in the future please direct questions or support inquiries to [the support forums](https://wordpress.org/support/plugin/woocommerce/). Thanks.
