### ISSUE TITLE
Using "quick edit" doesn't refresh the terms on FILTER PRODUCTS BY ATTRIBUTE WIDGET

### ISSUE THREAD

**Issue by ifede84** [woocommerce/woocommerce#21429]
**Describe the bug**

Using "quick edit" feature to set item out of stock the filter products by attribute widget doesn't refresh the terms it is showing.  Using tools like "Term counts" or "woocommerce transient" don't solve the issue. The only way to fix it is to enter the item via the standard admin interface and click on "save attributes".

Third part widget plugins like " YITH WooCommerce Ajax Product Filter" are not affected by the issue.

**To Reproduce**
Set up FILTER PRODUCTS BY ATTRIBUTE WIDGET, assign some attributes to item and use "quick edit" feature on an item to set stock quantity to 0 

**Screenshots**
I've recorded a little screencast, available here ---> https://youtu.be/VlMCpB1lwho

**Expected behavior**
Using quick edit the widgets should refresh the terms

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

I've reproduced the issue using a woocommerce store made from scratch

**WordPress Environment**
`
### WordPress Environment ###

Home URL: https://supermarketdellascarpa.eu/test
Site URL: https://supermarketdellascarpa.eu/test
WC Version: 3.4.5
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.10
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.60.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.41-cll-lve
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.5
WC Database Prefix: wpb1_
MaxMind GeoIP Database: ✔
Total Database Size: 4.50MB
Database Data Size: 3.76MB
Database Index Size: 0.74MB
wpb1_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB
wpb1_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wpb1_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wpb1_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wpb1_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wpb1_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wpb1_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wpb1_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wpb1_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wpb1_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wpb1_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wpb1_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wpb1_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wpb1_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wpb1_commentmeta: Data: 0.00MB + Index: 0.00MB
wpb1_comments: Data: 0.00MB + Index: 0.01MB
wpb1_links: Data: 0.00MB + Index: 0.00MB
wpb1_options: Data: 0.23MB + Index: 0.03MB
wpb1_postmeta: Data: 0.83MB + Index: 0.49MB
wpb1_posts: Data: 0.09MB + Index: 0.04MB
wpb1_termmeta: Data: 0.00MB + Index: 0.01MB
wpb1_terms: Data: 0.00MB + Index: 0.01MB
wpb1_term_relationships: Data: 0.06MB + Index: 0.12MB
wpb1_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wpb1_usermeta: Data: 2.54MB + Index: 0.01MB
wpb1_users: Data: 0.00MB + Index: 0.01MB
wpb1_wc_download_log: Data: 0.00MB + Index: 0.00MB
wpb1_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wpb1_wpmelon_advbedit_temp: Data: 0.01MB + Index: 0.01MB

### Post Type Counts ###

attachment: 1
customize_changeset: 2
page: 6
post: 2
product: 403

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce: by Automattic – 3.4.5
YITH WooCommerce Ajax Product Filter: by YITHEMES – 3.5.1 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /negozio/
Cart: #6 - /carrello/
Checkout: #7 - /checkout/
My account: #8 - /mio-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by rodrigoprimo** [comment]
I was able to reproduce this issue. The same problem happens when changing product stock using WC API.

**Comment by rodrigoprimo** [comment]
See #22029. Thanks for your report.
