### ISSUE TITLE
[3.5-beta.1] Notices is missed

### ISSUE THREAD

**Issue by wayheming** [woocommerce/woocommerce#21428]
**Describe the bug**
Hello, after the form was confirmed, error notifications were no longer displayed. I think that the problem appeared after this commit https://github.com/woocommerce/woocommerce/commit/efe06cb14752bdfe2c18274783eac221cbeea5ff#diff-eac1259920df49bd4bc45d508ad1e40f 
I noticed a problem on the my account page, but maybe there is a problem on other pages that the commit has touched. And as i can see in some files version does not change to 3.5.0

Theme: Twenty Fifteen

**To Reproduce**
1. Go to my account page
2. Click on submit

**Screenshots**
https://prnt.sc/kxyetr
https://prnt.sc/kxyezf

**Comment by kloon** [comment]
@wayheming I get the message when I test using the master branch which is the latest beta version http://cld.wthms.co/bceinE

Can you check if you have any template files that are perhaps overidden? Also test with a default theme like Storefront or Twentyseventeen.

**Comment by kloon** [comment]
See #21445

**Comment by wayheming** [comment]
@kloon  OK, thank you.
