### ISSUE TITLE
Timestamp in log files is incorrect when WordPress timezone is not UTC

### ISSUE THREAD

**Issue by siliconforks** [woocommerce/woocommerce#21422]
**Describe the bug**
In WooCommerce log files, each line begins with a timestamp, for example:
```
2018-09-23T04:24:30+00:00 INFO ...
```
The timezone offset in the timestamp is always `+00:00` but the time in the timestamp is actually local time.

**To Reproduce**
1. In the WordPress admin section, go to Settings -> General and set the timezone to something other than UTC (and which does not have the same time as UTC), e.g., America/Toronto.
2. Cause something to be logged to a WooCommerce log file.  For example, you can add this code to a custom plugin/theme:
```php
add_action( 'after_setup_theme', function () {
	if ( function_exists( 'wc_get_logger' ) ) {
		$log = wc_get_logger();
		$log->info( 'this is the after_setup_theme action' );
	}
} );
```
3. In the admin section, go to WooCommerce -> Status -> Logs
4. Look at the timestamps in the log file - they will have a timezone offset of  `+00:00` but the time will be in the timezone selected in step 1.

**Expected behavior**
If the timezone offset is `+00:00`, I would expect the time to be UTC.

Alternatively, the timezone offset could be logged correctly (using the example of America/Toronto above which is currently in Eastern Daylight Time, I would expect it to be `-04:00`).  However, this is not recommended (logging in UTC is better).

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

Note: the status report has an entry "Default Timezone is UTC" which is somewhat misleading - it doesn't actually refer to the timezone configured in WordPress (which I have set to America/Toronto as in the example above).

<details>

### WordPress Environment ###

Home URL: http://host.invalid/wordpress-woocommerce-git
Site URL: http://host.invalid/wordpress-woocommerce-git
WC Version: 3.5.0
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.34 (Win32) OpenSSL/1.0.2o PHP/5.6.37
PHP Version: 5.6.37 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 64 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.59.0
OpenSSL/1.0.2o

SUHOSIN Installed: –
MySQL Version: 5.6.39-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 1.86MB
Database Data Size: 1.02MB
Database Index Size: 0.84MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 0.48MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

page: 6
post: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

LOG BUG: by  –
WooCommerce: by Automattic – 3.5.0-beta.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
</details>

**Comment by kloon** [comment]
See #21981
