### ISSUE TITLE
REST API: Add meta_data property for product categories

### ISSUE THREAD

**Issue by erikderzweite** [woocommerce/woocommerce#21423]
While working with REST API for Woocommerce it occurred to me that product categories do not have a meta_data property. The property is also absent from documentation.

I use Yoast SEO plugin for Woocommerce and would like to add/edit the _yoast_wpseo_metadesc property among others. However, meta_data is absent for product categories. So, I can set the meta description for a product, but not for a category.

It would be great to have this property added to the product categories.

**Comment by claudiosanches** [comment]
You can use the regular taxonomy endpoint from WordPress REST API to edit any Yoast related meta field, see that WooCommerce REST API works on top of WordPress REST API, so there is no reason to not use the WordPress REST API too.
