### ISSUE TITLE
API - Create Order With Float Quantity

### ISSUE THREAD

**Issue by sathish5566** [woocommerce/woocommerce#21420]
Hi Team,
In my shop user can define the product weight and actually product weight as a quantity. I'm trying to make a order but float quantity values is not accept. Could you please help me for this solution.

`$woocommerce->post('orders', $getData);`

**Comment by claudiulodro** [comment]
Hi there,

I'm not exactly sure what you're trying to do with orders and weight, [as there are no order properties that deal in weight](https://woocommerce.github.io/woocommerce-rest-api-docs/#orders). [In the API docs product weight is listed as a string, not a float.](https://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties) I recommend casting your float to a string before sending the request if you're trying to update a product weight. Hope this clears things up.

In the future, please use [the support forums](https://wordpress.org/support/plugin/woocommerce/) for support requests, as GitHub is for bugs. Thanks.
