### ISSUE TITLE
Address line 2 included in shipping destination summary

### ISSUE THREAD

**Issue by dechov** [woocommerce/woocommerce#21430]
In most cases, the shipping address summary in the cart omits the street address, reflecting the limited set of fields present in the "Change address" form here:

<img width="424" alt="screen shot 2018-09-24 at 9 55 53 am" src="https://user-images.githubusercontent.com/1867547/45958572-c77bde80-bfe5-11e8-8e7d-38aade012409.png">

However, if an address line 2 is present in the session (entered from the checkout page):

<img width="417" alt="screen shot 2018-09-24 at 9 56 39 am" src="https://user-images.githubusercontent.com/1867547/45958692-1b86c300-bfe6-11e8-9660-f1b7d19debbf.png">

...then it shows up in the summary on the cart page:

<img width="418" alt="screen shot 2018-09-24 at 9 56 54 am" src="https://user-images.githubusercontent.com/1867547/45958714-26d9ee80-bfe6-11e8-9861-3a6f1af17490.png">

Though I had expected the street address to be omitted intentionally, on closer inspection the reason line 1 doesn't appear seems to be a mismatch ([code](https://github.com/woocommerce/woocommerce/blob/60fafd821d3fff2e7e57df9892c90102650dbe68/templates/cart/cart-shipping.php#L22)) between key names: `address` in the destination address array vs. `address_1` expected by the format template.

**Comment by claudiulodro** [comment]
#21493
