### ISSUE TITLE
Version 3.5 Beta 1 - Uncaught ReferenceError: woocommerce_admin is not defined

### ISSUE THREAD

**Issue by a3rev** [woocommerce/woocommerce#21432]
**Describe the bug**
Version 3.5 Beta 1

Not a big issue

With the Debug Bar plugin installed it is reporting this JavaScript 'Uncaught ReferenceError' : woocommerce_admin is not defined.

wp-content/plugins/woocommerce/assets/js/admin/woocommerce_admin.js?ver=3.5.0 line 346

**To Reproduce**
1. Install / activate the Debug Bar plugin https://wordpress.org/plugins/debug-bar/
2. Click on 'wp Dashboard'
3. You will see the DEBUG bar in top right of the admin bar turn red - look at the JavaScript menu to see the message

**Screenshots**
[![Image from Gyazo](https://i.gyazo.com/5c69f6415b7fef92a9659bfb6961223d.png)](https://gyazo.com/5c69f6415b7fef92a9659bfb6961223d)

**Comment by kloon** [comment]
@a3rev I am not getting this error when I test with the master branch, can you perhaps try the master branch and see if you are still getting this error? If so then please also make sure you have no other plugins active and you are testing on a default theme like Storefront or Twentyseventeen.

Will gladly reopen the issue if the problem persists and you can provide steps to reproduce this on my end.

**Comment by f3bruary** [comment]
I'm getting this too in the developer console. I'm not using that plugin though. I haven't tested with the default theme (yet).
