### ISSUE TITLE
Product title changes to current page title

### ISSUE THREAD

**Issue by BernardV** [woocommerce/woocommerce#21435]
**Describe the bug**
When you have a variable product it's possible that the (parent) product name will be empty or changes to the current post title.

**To Reproduce**
1. Basic install of wordpress and only woocommerce as plugin on a basic theme.
2. Add a variable product with a variation.
3. In functions.php (or anywhere else in the code) add:
`new WC_Product_Variation(<variable_product_id>);`
So add the parent product id in the function, not one of the variations.
4. The product title is changed to the current post title

**Expected behavior**
The product title will be left unchanged.

**Isolating the problem (mark completed items with an [x]):**
When passing a variable product in the constuctor of a product variation it will load the the data store with a $parent_object with id 0:
`$parent_object   = get_post( $product->get_parent_id() );`
The get_posts() function will return the $globals['post'] when empty($post) is true, and empty(0) is true.
So the data store will be loaded with a parent_object of the current post.

**WordPress Environment**
Latest version, latest woocommerce.
Also verified on WC 3.4.3

**Comment by kloon** [comment]
I tried to replicate this but unable, also see my WP Shell results when calling get_post with 0

```
wp> get_post( 0 );
=> NULL
```

You might have something that is polluting your global post var, did you tests with all plugins except WooCommerce disabled as well as your theme switched to a default one like Twentyseventeen or Storefront?

If possible please provide the example code you have tested this with as well.

**Comment by kloon** [comment]
Closing due to lack of feedback and not able to replicate.
