### ISSUE TITLE
Getting API 401 connection error

### ISSUE THREAD

**Issue by dallasbrands** [woocommerce/woocommerce#21441]
**Describe the bug**
The domain is thrivette.com and we have HTTPS setup. Everything works when the key and secret are passed within the URL, but the application I'm using (3rd party iOS app) won't accept this type of URL. 

I keep getting the following message:
{"code":"woocommerce_rest_cannot_view","message":"Sorry, you cannot list resources.","data":{"status":401}}

I've connected in Postman without an issue. I've tried all the plugins I could find, disabled all existing plugins, changed the theme, but still can't seem to get it working. 

This is a brand new Wordpress install and all plugins are up to date. PHP version 7.1

**Comment by claudiulodro** [comment]
Hi there,

The 401 error means that you are not getting properly authenticated when trying to connect with the API, and this will happen if your app does not support the authentication method. If supported by the app, you can also try [the OAuth protocol](https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-http).

If the app supports none of those, there isn't much we can do. Authentication is important for protecting your store's data and for preventing other people from making unwanted changes to your store. Hope this clears things up.
