### ISSUE TITLE
Woo can't multiply correctly product values

### ISSUE THREAD

**Issue by redmaciej** [woocommerce/woocommerce#21451]
**Describe the bug**
There is a multiplying error on the order summary page which results in a wrongly calculated sum for payment.

**To Reproduce**
Create a product with 145 selling price, set VAT to 5% and add 2 products to cart. 

**Screenshots**
<img width="448" alt="image" src="https://user-images.githubusercontent.com/43605736/46078426-68a89780-c194-11e8-85e0-1574445771ac.png">

**Expected behavior**

138,10 zł  × 2 = 276,20 -> NOT 276,19 zł !

The value is calculated wrong probably because the real net price of the product calculated for 1 item is 138.095238095238095, then multiplied by 2 to give 276.19047619047619 and only then rounded to give the wrong sum value of 276.19. 

Either a lower precision to calculate net price of an item should be used (2 digits would give correct net price of 138.10) or it should be multiplied with selling price and only then the VAT should be calculated. 

Whatever the resolution, the problem is BIG when you are not able to issue a correct invoice which would match the paid value of the order!

-- | -- | --

**Isolating the problem (mark completed items with an [x]):**
- [X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

### WordPress Environment ###

Home URL: https://zdroweoleje.pl
Site URL: https://zdroweoleje.pl
WC Version: 3.4.5
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: ❌ 40 MB - Rekomendujemy ustawienie co najmniej 64MB. Zobacz: Zwiększenie pamięci dla PHP
WP Debug Mode: –
WP Cron: ✔
Language: pl_PL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.37-0+deb8u1 - Rekomendujemy używanie PHP w wersji 7.2 lub wyższej w celu osiągnięcia większej wydajności oraz bezpieczeństwa. Jak zaktualizować wersję PHP
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.0.36-MariaDB-0+deb8u1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Całkowity rozmiar bazy danych: 34.79MB
Rozmiar bazy danych: 31.74MB
Rozmiar indeksu bazy danych: 3.05MB
wp_woocommerce_sessions: Dane: 0.06MB + Indeks: 0.02MB
wp_woocommerce_api_keys: Dane: 0.02MB + Indeks: 0.03MB
wp_woocommerce_attribute_taxonomies: Dane: 0.02MB + Indeks: 0.02MB
wp_woocommerce_downloadable_product_permissions: Dane: 0.02MB + Indeks: 0.05MB
wp_woocommerce_order_items: Dane: 0.02MB + Indeks: 0.02MB
wp_woocommerce_order_itemmeta: Dane: 0.08MB + Indeks: 0.09MB
wp_woocommerce_tax_rates: Dane: 0.02MB + Indeks: 0.06MB
wp_woocommerce_tax_rate_locations: Dane: 0.02MB + Indeks: 0.03MB
wp_woocommerce_shipping_zones: Dane: 0.02MB + Indeks: 0.00MB
wp_woocommerce_shipping_zone_locations: Dane: 0.02MB + Indeks: 0.03MB
wp_woocommerce_shipping_zone_methods: Dane: 0.02MB + Indeks: 0.00MB
wp_woocommerce_payment_tokens: Dane: 0.02MB + Indeks: 0.02MB
wp_woocommerce_payment_tokenmeta: Dane: 0.02MB + Indeks: 0.03MB
wp_woocommerce_log: Dane: 0.02MB + Indeks: 0.02MB
wp_commentmeta: Dane: 0.02MB + Indeks: 0.03MB
wp_comments: Dane: 0.02MB + Indeks: 0.09MB
wp_es_deliverreport: Dane: 0.02MB + Indeks: 0.00MB
wp_es_emaillist: Dane: 0.02MB + Indeks: 0.00MB
wp_es_notification: Dane: 0.02MB + Indeks: 0.00MB
wp_es_sentdetails: Dane: 0.02MB + Indeks: 0.00MB
wp_links: Dane: 0.02MB + Indeks: 0.02MB
wp_options: Dane: 1.13MB + Indeks: 0.05MB
wp_postmeta: Dane: 6.52MB + Indeks: 0.42MB
wp_posts: Dane: 5.52MB + Indeks: 0.09MB
wp_slim_events: Dane: 0.19MB + Indeks: 0.13MB
wp_slim_events_archive: Dane: 0.02MB + Indeks: 0.02MB
wp_slim_stats: Dane: 17.55MB + Indeks: 1.52MB
wp_slim_stats_archive: Dane: 0.02MB + Indeks: 0.02MB
wp_termmeta: Dane: 0.02MB + Indeks: 0.03MB
wp_terms: Dane: 0.02MB + Indeks: 0.03MB
wp_term_relationships: Dane: 0.02MB + Indeks: 0.02MB
wp_term_taxonomy: Dane: 0.02MB + Indeks: 0.03MB
wp_usermeta: Dane: 0.05MB + Indeks: 0.03MB
wp_users: Dane: 0.02MB + Indeks: 0.05MB
wp_wc_download_log: Dane: 0.02MB + Indeks: 0.03MB
wp_wc_webhooks: Dane: 0.02MB + Indeks: 0.02MB
wp_woocommerce_tpay: Dane: 0.02MB + Indeks: 0.00MB
wp_wpgdprc_access_requests: Dane: 0.02MB + Indeks: 0.00MB
wp_wpgdprc_consents: Dane: 0.02MB + Indeks: 0.00MB
wp_wpgdprc_delete_requests: Dane: 0.02MB + Indeks: 0.00MB

### Post Type Counts ###

attachment: 67
customize_changeset: 1
es_template: 3
nav_menu_item: 14
page: 31
popup_theme: 6
post: 13
product: 17
product_variation: 24
revision: 313
shop_coupon: 2
shop_order: 33
wpcf7_contact_form: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Popup Maker: przez WP Popup Maker – 1.7.30
Redux Framework: przez Zespół Redux – 3.6.11
All in One SEO Pack: przez Michael Torbert – 2.8
Breadcrumb NavXT: przez John Havlik – 6.2.0
Contact Form 7: przez Takayuki Miyoshi – 5.0.4
Email Subscribers & Newsletters: przez Icegram – 3.5.11
Page Builder by SiteOrigin: przez SiteOrigin – 2.8.2
SiteOrigin Widgets Bundle: przez SiteOrigin – 1.13.0
Tiva Widgets: przez TivaTheme – 1.0
Zgoda na Cookies: przez Catapult_Themes – 2.3.11
Widget Importer & Exporter: przez churchthemes.com – 1.5.3
Płacę z PayU: przez PayU SA – 1.2.6 – Nietestowane z używaną wersją WooCommerce
tpay.com Woocommerce payment module: przez tpay.com – 2.6.51 – Nietestowane z używaną wersją WooCommerce
WooCommerce: przez Automattic – 3.4.5
WordPress Importer: przez wordpressdotorg – 0.6.4
WP GDPR Compliance: przez Van Ons – 1.4.2
Slimstat Analytics: przez Jason Crouse – 4.7.8.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: PLN (zł)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Strona sklepu: #37 - /shop/
Koszyk: #38 - /cart/
Zamówienie: #39 - /checkout/
Moje konto: #40 - /my-account/
Regulamin: #151 - /regulamin/

### Theme ###

Name: Scara
Version: 1.0
Author URL: http://tivatheme.com/
Child Theme: ❌ – Jeśli modyfikujesz WooCommerce lub motyw nadrzędny
którego nie jesteś autorem
polecamy używanie motywu potomnego. Zobacz: Jak tworzyć motywy potomne

WooCommerce Support: ✔

### Templates ###

Archive Template: Twój motyw zawiera plik woocommerce.php
nie możesz zmodyfikować szablonu woocommerce/archive-product.php
ponieważ woocommerce.php ma wyższy priorytet niż archive-product.php. Ma to na celu zapobieganie problemów z wyświetlaniem.

Overrides: scara/woocommerce/archive-product.php wersja 2.0.0 jest nieaktualna. Bazowa wersja to 3.4.0
scara/woocommerce/cart/cart-shipping.php wersja 3.1.0 jest nieaktualna. Bazowa wersja to 3.2.0
scara/woocommerce/cart/cart.php wersja 3.1.0 jest nieaktualna. Bazowa wersja to 3.4.0
scara/woocommerce/cart/cross-sells.php
scara/woocommerce/cart/mini-cart.php wersja 3.1.0 jest nieaktualna. Bazowa wersja to 3.3.0
scara/woocommerce/checkout/form-checkout.php
scara/woocommerce/checkout/form-pay.php wersja 2.5.0 jest nieaktualna. Bazowa wersja to 3.4.0
scara/woocommerce/checkout/payment.php wersja 2.5.0 jest nieaktualna. Bazowa wersja to 3.4.0
scara/woocommerce/checkout/thankyou.php wersja 3.0.0 jest nieaktualna. Bazowa wersja to 3.2.0
scara/woocommerce/content-product.php wersja 3.0.0 jest nieaktualna. Bazowa wersja to 3.4.0
scara/woocommerce/content-product_cat.php
scara/woocommerce/content-single-product.php wersja 3.0.0 jest nieaktualna. Bazowa wersja to 3.4.0
scara/woocommerce/loop/add-to-cart.php wersja 3.0.0 jest nieaktualna. Bazowa wersja to 3.3.0
scara/woocommerce/loop/orderby.php wersja 2.2.0 jest nieaktualna. Bazowa wersja to 3.3.0
scara/woocommerce/loop/pagination.php wersja 2.2.2 jest nieaktualna. Bazowa wersja to 3.3.1
scara/woocommerce/loop/price.php
scara/woocommerce/loop/rating.php
scara/woocommerce/loop/result-count.php wersja 3.0.0 jest nieaktualna. Bazowa wersja to 3.3.0
scara/woocommerce/loop/sale-flash.php
scara/woocommerce/myaccount/form-add-payment-method.php wersja 3.0.0 jest nieaktualna. Bazowa wersja to 3.4.0
scara/woocommerce/myaccount/my-orders.php
scara/woocommerce/order/order-details-customer.php wersja 3.0.0 jest nieaktualna. Bazowa wersja to 3.4.4
scara/woocommerce/order/order-details-item.php
scara/woocommerce/order/order-details.php wersja 3.0.0 jest nieaktualna. Bazowa wersja to 3.3.0
scara/woocommerce/product-searchform.php wersja 2.5.0 jest nieaktualna. Bazowa wersja to 3.3.0
scara/woocommerce/single-product/add-to-cart/grouped.php wersja 3.0.7 jest nieaktualna. Bazowa wersja to 3.4.0
scara/woocommerce/single-product/price.php
scara/woocommerce/single-product/product-image.php wersja 3.1.0 jest nieaktualna. Bazowa wersja to 3.3.2
scara/woocommerce/single-product/rating.php
scara/woocommerce/single-product/related.php
scara/woocommerce/single-product/tabs/additional-information.php
scara/woocommerce/single-product/tabs/description.php
scara/woocommerce/single-product/tabs/tabs.php
scara/woocommerce/single-product/up-sells.php
scara/woocommerce/single-product-reviews.php wersja 2.3.2 jest nieaktualna. Bazowa wersja to 3.2.0

Outdated Templates: ❌
					
					
						Dowiedz się jak zaktualizować

</details>

**Comment by BernardV** [comment]
Try looking at woocommerce->settings->tax and then "Rounding [] - Round tax at subtotal level, instead of rounding per line"

**Comment by redmaciej** [comment]
OK, I did change this and now in the basket I have a situation like this which is already wrong:

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/43605736/46085600-aa423e00-c1a6-11e8-8203-f354d33a6c52.png">

and:

<img width="247" alt="image" src="https://user-images.githubusercontent.com/43605736/46085722-ef667000-c1a6-11e8-91f3-c6f1a6606e13.png">


and when I put 2 pcs, the sums are still wrong:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/43605736/46085838-3c4a4680-c1a7-11e8-8318-b3363355525e.png">



so changing the tax rounding DOES NOT solve the problem.

**Comment by mikejolley** [comment]
The values in the backend are stored with precision exclusive of tax, but displayed rounded to your store dp setting. 

The actual stored value cannot be rounded as it would affect the amount of tax calculated per line.

If you manually increase the qty, the only value it can use is the value stored with precision, not a rounded value.

Solutions:

1. Edit the line and adjust the total/tax to the desired amount.
2. Use tax excl. prices in the store so the values don't require such high precision for recalculations.
3. Add the product to the order again with 2 qty and remove the existing line. This will recalculate the line price based on the tax incl. price in the store and give the correct result.

Thanks
