### ISSUE TITLE
Search argument in WC_Product_Query и wc_get_products? And Args can be applied to variations?

### ISSUE THREAD

**Issue by jensen6720185** [woocommerce/woocommerce#21450]
**Describe the question**
Is there any way to use search by product title or custom meta with new functions? because with wp_query we can use it like that:
`$query = new WP_Query( array( 's' => 'keyword' ) );`

or like alternative we can get products with wp_query and add ids to include

For example if we create ajax search with fields: search, date range, sku, price, etc 
Search Ids by s field if we get it earlier...

```
$somekeywords = 'Some Product Name';
$main_args = '';

if ($somekeywords != '') {
	$args = array(
		'post_type' => 'product',
		's' => $somekeywords, 
		'fields' => 'ids'
	)
	
	$products = new WP_Query( $args );
	
	$main_args ['include'] = $products->posts;
}

$main_args = array(
	'orderby' => 'date',
	'order' => 'desc',
	return' => 'ids'
);

$products = wc_get_products( $args );
```

PS Change from WP_Query doesn't make sense because all attributes like tags, categories, price, sku etc don't work with variations, only for parent products.

**Comment by claudiulodro** [comment]
Hi there,

You can use [`WC_Product_Data_Store_CPT::search_products`](https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-data-store-cpt.php#L1362) to do a product search similar to the `s` param on `WP_Query`.

`wc_get_products` does not support partial title search, but it does [have support for custom params](https://github.com/woocommerce/woocommerce/wiki/wc_get_products-and-WC_Product_Query#adding-custom-parameter-support) if you want to add this functionality to whatever you are doing.

Hope this clears things up. Thanks.

**Comment by cody-rees** [comment]
For anyone else (and likely myself while googling this problem again) who needs a more straightforward resolution to this problem feel free to use the following code snippets. 
    
/**
 * Add support for 'search_term' query var (Add to functions file)
 */
function support_search_term_query_var( $query, $query_vars ) {
    if( empty( $query_vars['search_term'] ) ) {
        return $query;
    }

    $query['s'] = $query_vars['search_term'];
    return $query;
 }
 add_filter( 'woocommerce_product_data_store_cpt_get_products_query', 'support_search_term_query_var', 10, 2 );



 /**
  * Usage
  */
 $my_search_term = $_POST['search'];
 $products = wc_get_products([
    'limit'          => 10,   
    'post_type'      => 'product',
    'search_term'    => $my_search_term,
    'visibility'     => 'catalog',
]);

**Comment by claudiulodro** [comment]
Sorry! In retrospect that wasn't a super helpful response because the line I linked to now points to a different thing. :) Thanks for adding the snippet.

For reference, this is what my recommendation looks like as a snippet:

```
$data_store = WC_Data_Store::load( 'product' );
$search_results = $data_store->search_products( 'my-search-term' );
```

**Comment by erikdemarco** [comment]
> For anyone else (and likely myself while googling this problem again) who needs a more straightforward resolution to this problem feel free to use the following code snippets.
> 
> ```
> /**
>  * Add support for 'search_term' query var (Add to functions file)
>  */
> function support_search_term_query_var( $query, $query_vars ) {
>     if( empty( $query_vars['search_term'] ) ) {
>         return $query;
>     }
> 
>     $query['s'] = $query_vars['search_term'];
>     return $query;
>  }
>  add_filter( 'woocommerce_product_data_store_cpt_get_products_query', 'support_search_term_query_var', 10, 2 );
> 
> 
> 
>  /**
>   * Usage
>   */
>  $my_search_term = $_POST['search'];
>  $products = wc_get_products([
>     'limit'          => 10,   
>     'post_type'      => 'product',
>     'search_term'    => $my_search_term,
>     'visibility'     => 'catalog',
> ]);
> ```

We can't use order id as the search term. It will return zero result.

**Comment by yossefEl** [comment]
This code is a part of my custom search endpoint, its results are similar to woocommerce REST API endpoint 
**/products?search=keyword**
 ```
$args = array(
            'post_type' => 'product',
            'posts_per_page' => 10,
            'paged' => $page,
            's' => $request['s'],
            'paginate' => true,
            'meta_query' => array(
                array(
                    'key' => '_sku',
                    'value' => $request['s'],
                    'compare' => 'LIKE',
                ),
                array(
                    'key' => '_title',
                    'value' => $request['s'],
                    'compare' => 'LIKE',
                ),
            ),
        );

        $query = wc_get_products($args);
        //get products 
       $products=  $query->products
```

**Comment by noknokcody** [comment]
> For anyone else (and likely myself while googling this problem again) who needs a more straightforward resolution to this problem feel free to use the following code snippets.
> 
> ```
> /**
>  * Add support for 'search_term' query var (Add to functions file)
>  */
> function support_search_term_query_var( $query, $query_vars ) {
>     if( empty( $query_vars['search_term'] ) ) {
>         return $query;
>     }
> 
>     $query['s'] = $query_vars['search_term'];
>     return $query;
>  }
>  add_filter( 'woocommerce_product_data_store_cpt_get_products_query', 'support_search_term_query_var', 10, 2 );
> 
> 
> 
>  /**
>   * Usage
>   */
>  $my_search_term = $_POST['search'];
>  $products = wc_get_products([
>     'limit'          => 10,   
>     'post_type'      => 'product',
>     'search_term'    => $my_search_term,
>     'visibility'     => 'catalog',
> ]);
> ```

Thanks past me
