### ISSUE TITLE
[3.5-beta.1] Variations are not correctly created when using custom attributes

### ISSUE THREAD

**Issue by Chrystll** [woocommerce/woocommerce#21453]
## Plugins & theme activated
WooCommerce 3.5.0-beta.1
Storefront 2.3.3

## Issue description

The variations are not correctly created when using custom attributes. I get this result:

![variations-tab](https://user-images.githubusercontent.com/19824724/46093501-ce5a4b00-c1b7-11e8-8785-ecba3a586eec.png)

I didn't reproduce this issue with WooCommerce 3.4.5

## Steps to reproduce the issue

1. Create a variable product then add a custom product attribute and custom terms as here:
![attributes-tab](https://user-images.githubusercontent.com/19824724/46093513-d2866880-c1b7-11e8-886f-a04fba2c6b1f.png)
2. Go to the Variations tab then create the variations by using "Create variations from all attributes": the variations are not correctly created, I get "Any ...".

**Comment by claudiulodro** [comment]
Thanks for the report. Fixed in https://github.com/woocommerce/woocommerce/pull/21403
