### ISSUE TITLE
Error after updation

### ISSUE THREAD

**Issue by Ashishsanon** [woocommerce/woocommerce#21469]
I am getting an error:

Notice: price was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Cart_Session->get_cart_from_session, apply_filters('woocommerce_get_cart_item_from_session'), WP_Hook->apply_filters, AtBookingFormBase->filter_woocommerce_get_cart_item_from_session, AtBookingFormBase->get_product_date_specific_price, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong Please see Debugging in WordPress for more information. (This message was added in version 3.0.) in /home1/predicu0/public_html/sacredexplorations/home/wp-includes/functions.php on line 4161

**Comment by kloon** [comment]
It seems like you are running a plugin or theme that is still using outdated WooCommerce methods. I'd suggest you test by disabling all plugins except WooCommerce and also switching to a default theme like Twentyseventeen or Storefront and then test by enabling plugins one by one and then finally switching your theme back to find the offending plugin or theme.
