### ISSUE TITLE
Filter to remove variation from product title in checkout and order details.

### ISSUE THREAD

**Issue by kmob2** [woocommerce/woocommerce#21466]
Hello,

I can't seem to find a filter that allows me to filter the product title inside the order details page and the email. I'm trying to remove a certain variation name from the product title once it's in the cart, checkout, order details and email.

Current Title: "Apple MacBook Pro 15 - China, 16GB Ram, 512GB SSD"
Required Title: "Apple MacBook Pro 15 - 16GB Ram, 512GB SSD"

I managed to remove it from the title when it's inside the cart and checkout page, using this code:

    function remove_variation_from_product_title( $title, $cart_item, $cart_item_key ) {
    	$_product = $cart_item['data'];
    
    	if ( $_product->is_type( 'variation' ) ) {
    
    		$replace = array( 'China,', 'China' );
    		$title = str_replace( $replace, '', $title);
    
    		return apply_filters( 'woocommerce_product_variation_title', $title );
    	}
    
    	return $title;
    }
    add_filter( 'woocommerce_cart_item_name', 'remove_variation_from_product_title', 10, 3 );

But as you can see from the filter, it only removes it from the cart. Once the order is made, the full title with variations are being shown again in the order details page as well as in the email that is sent from the customer.

I did come across another filter called [`woocommerce_order_items_meta_display`][1], but failed to get anywhere with it.

Does anyone know how I could filter the product title across the entire store, and not just in the cart and checkout page? Is there such a filter or should I just give up looking for a solution?

Thanks.

  [1]: https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-order-item-meta.php#L67-L110

**Comment by kmob2** [comment]
Found it. `woocommerce_order_item_name` did the trick. It also applies it to the email that is sent to the customer.

```
function remove_variation_from_product_title_order( $title, $item, $is_visible ) {

	$_product = $item['data'];
	$replace = array( 'China,', 'China' );
	$title = str_replace( $replace, '', $title);

	return apply_filters( 'woocommerce_product_variation_title', $title );

}
add_filter( 'woocommerce_order_item_name', 'remove_variation_from_product_title_order', 10, 3 );

```

**Comment by DiogoMelo-CodexDesign** [comment]
Hi,

I'm looking for a similar code, from all ive seen, yours is the closest for what i need:

I need to remove a specific selected variation from order details (cart, checkout, emails..) 

Could you please help me? :)

Thank you,
Diogo Melo, Portugal
