### ISSUE TITLE
District of Columbia Misspelling

### ISSUE THREAD

**Issue by mattecodistricts** [woocommerce/woocommerce#21473]
The city "District of Columbia" is misspelled on the dropdown menu when selecting city. It is spelled "District of Colombia" and I cannot change this myself. 

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by lindelius** [comment]
It's actually spelled "District of Columbia." This issue is incorrect.

**Comment by mattecodistricts** [comment]
On my instance it is spelled "Colombia" in two of the drop down menus.

![screen shot 2018-10-01 at 1 14 06 pm](https://user-images.githubusercontent.com/43754525/46313183-ff51cb80-c57b-11e8-8c0a-f5c05141f23d.png)

**Comment by lindelius** [comment]
You might have an older version, then? The current version has the correct spelling.

**Comment by kloon** [comment]
I checked now and can confirm what @lindelius says, in the current version it is spelled Columbia. You perhaps have an old version or a translation loaded where it is misspelled.
