### ISSUE TITLE
Get orders belonging to a custom id

### ISSUE THREAD

**Issue by Johnny99211** [woocommerce/woocommerce#21476]
Because of my bachelor project I need help from you. I've searched a lot but I can't find the solution. 
I'm trying to edit a WooCommerce function named

> woocommerce_account_orders

I've added the field

> mycustom_id

to the function because I need to get all orders which has the current logged in user in the field mycustom_id. This is my code:

```
function woocommerce_account_orders( $current_page ) {
    $current_page    = empty( $current_page ) ? 1 : absint( $current_page );
    $customer_orders = wc_get_orders( apply_filters( 'woocommerce_my_account_my_orders_query', array(
        'customer' => get_current_user_id(),
        'mycustom_id' => get_current_user_id(),
        'page'     => $current_page,
        'paginate' => true,
    ) ) );

    wc_get_template(
        'myaccount/orders.php',
        array(
            'current_page'    => absint( $current_page ),
            'customer_orders' => $customer_orders,
            'has_orders'      => 0 < $customer_orders->total,
        )
    );
}
```
How can I add this feature to the function a smart way and how can I search for my custom parameter? I've saved the parameter as an order_meta attribute:

```
[5] => WC_Meta_Data Object (
[current_data:protected] => Array (
[id] => 3477
[key] => mycustom_id
[value] => 2
)
```
Thank you for your help. I've tried so much but I'm new in PHP and must lurn a lot..

**Comment by claudiulodro** [comment]
[Here is an example of using custom meta with wc_get_orders.](https://github.com/woocommerce/woocommerce/wiki/wc_get_orders-and-WC_Order_Query#adding-custom-parameter-support) Hope it helps.

In the future please only open bug reports on GitHub and not development or support questions. For support and development questions I recommend [the support forums](https://wordpress.org/support/plugin/woocommerce/). Thanks.
