### ISSUE TITLE
Should WooCommerce WebHooks treat an HTTP/302 response as a failure?

### ISSUE THREAD

**Issue by thiscouldbejd** [woocommerce/woocommerce#21490]
Whilst experimenting with writing a simple webhook handler using Google Apps Script, it seems that WooCommerce Webhooks are getting regularly 'disabled' due to >5 'failed' deliveries.

A Google Apps Script (acting as a web-server to process the HTTP POSTs from the WooCommerce WebHook) returns an HTTP/302 redirect as part of its normal operation (it is part of the way authentication is handled I believe). Once this redirect is followed, an HTTP/200 is returned to indicate a normal success condition.

This works absolutely perfectly, and the Apps Script receives the POST payload and can deal with it appropriately.

However, the WooCommerce Webhook / API interprets the initial 302 response (which is also the response recorded in the WebHook logs) as a failure, despite the fact, there is a subsequent 200 response once the redirect has been followed. So, it works 5 times, then fails (as per the failure counter).

I would have thought this wasn't really desired behaviour, and perhaps this following [check line](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-webhook.php#L445):

```
// Track failures.
if ( intval( $response_code ) >= 200 && intval( $response_code ) < 300 ) {
	$this->set_failure_count( 0 );
	$this->save();
} else {
	$this->failed_delivery();
}
```

Could be amended to **explicitly check** for a 302, and handle it as a non-failure?

If there isn't a reason (that I am not aware of) for it being handled as a failure condition, I am happy to submit a pull request.

Thanks

JD.

**Comment by claudiulodro** [comment]
Seems reasonable. Easiest fix is probably to change the code to `intval( $response_code ) < 303` so it also allows 301s.

**Comment by claudiulodro** [comment]
Happy to review a pull request if you want to make the change.

**Comment by thiscouldbejd** [comment]
Hi Claudiu,

Many thanks - completely agree on including 301 Codes as well - pull request above.

Yours,

JD

**Comment by claudiulodro** [comment]
#21491
