### ISSUE TITLE
DB Log entries are not deleted by wc_cleanup_logs

### ISSUE THREAD

**Issue by ictbeheer** [woocommerce/woocommerce#21509]
**Describe the bug**
When using WC_Log_Handler_DB as log handler old log entries are not deleted by wc_cleanup_logs.
This happens because the time of the log entry is stored as a string: `date( 'Y-m-d H:i:s', $timestamp )` but the delete query uses a timestamp.

**To Reproduce**
1. Make sure that WC_Log_Handler_DB is the log handler using the filter `woocommerce_register_log_handlers`
2. Add a log entry (e.g. using `wc_get_logger()->log()`
3. Set the log retention to 0 days using filter `woocommerce_logger_days_to_retain_logs`
4. Run wc_cleanup_logs (e.g. using WP Crontrol).
5. Check if all log entries are deleted.

**Expected behavior**
Old DB log entries are correctly deleted

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

Home URL: https://www.siw.nl
Site URL: https://www.siw.nl
WC Version: 3.4.5
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 384 MB
WP Debug Mode: –
WP Cron: –
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.32 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 16 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: 5.6.41
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.5
WC Database Prefix: wp_
Total Database Size: 103.42MB
Database Data Size: 69.24MB
Database Index Size: 34.18MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.11MB + Index: 0.16MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.47MB + Index: 0.08MB
wp_cf_forms: Data: 0.02MB + Index: 0.02MB
wp_cf_form_entries: Data: 0.02MB + Index: 0.06MB
wp_cf_form_entry_meta: Data: 0.02MB + Index: 0.03MB
wp_cf_form_entry_values: Data: 0.02MB + Index: 0.05MB
wp_cf_pro_messages: Data: 0.02MB + Index: 0.00MB
wp_cf_tracking: Data: 0.02MB + Index: 0.00MB
wp_cf_tracking_meta: Data: 0.02MB + Index: 0.03MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.14MB + Index: 0.09MB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB
wp_icl_languages_translations: Data: 0.19MB + Index: 0.09MB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB
wp_icl_node: Data: 0.02MB + Index: 0.00MB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB
wp_icl_strings: Data: 0.02MB + Index: 0.05MB
wp_icl_string_positions: Data: 0.02MB + Index: 0.02MB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB
wp_icl_string_translations: Data: 0.02MB + Index: 0.02MB
wp_icl_translate: Data: 0.02MB + Index: 0.02MB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB
wp_icl_translations: Data: 1.52MB + Index: 3.81MB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB
wp_icl_translation_status: Data: 0.02MB + Index: 0.02MB
wp_imagify_files: Data: 0.02MB + Index: 0.08MB
wp_imagify_folders: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 10.41MB + Index: 3.02MB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB
wp_pmxi_history: Data: 0.13MB + Index: 0.00MB
wp_pmxi_images: Data: 0.02MB + Index: 0.00MB
wp_pmxi_imports: Data: 0.14MB + Index: 0.00MB
wp_pmxi_posts: Data: 1.48MB + Index: 0.33MB
wp_pmxi_templates: Data: 0.05MB + Index: 0.00MB
wp_postmeta: Data: 33.53MB + Index: 20.67MB
wp_posts: Data: 13.47MB + Index: 1.22MB
wp_strong_views: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.05MB + Index: 0.03MB
wp_terms: Data: 0.31MB + Index: 0.39MB
wp_term_relationships: Data: 4.27MB + Index: 2.11MB
wp_term_taxonomy: Data: 0.31MB + Index: 0.36MB
wp_usermeta: Data: 0.06MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wppusher_packages: Data: 0.02MB + Index: 0.00MB
wp_wysija_campaign: Data: 0.00MB + Index: 0.00MB
wp_wysija_campaign_list: Data: 0.00MB + Index: 0.00MB
wp_wysija_custom_field: Data: 0.00MB + Index: 0.00MB
wp_wysija_email: Data: 0.88MB + Index: 0.00MB
wp_wysija_email_user_stat: Data: 0.39MB + Index: 0.38MB
wp_wysija_email_user_url: Data: 0.04MB + Index: 0.04MB
wp_wysija_form: Data: 0.00MB + Index: 0.00MB
wp_wysija_list: Data: 0.00MB + Index: 0.00MB
wp_wysija_queue: Data: 0.03MB + Index: 0.07MB
wp_wysija_subscriber_ips: Data: 0.02MB + Index: 0.02MB
wp_wysija_url: Data: 0.01MB + Index: 0.00MB
wp_wysija_url_mail: Data: 0.00MB + Index: 0.00MB
wp_wysija_user: Data: 0.25MB + Index: 0.15MB
wp_wysija_user_field: Data: 0.00MB + Index: 0.00MB
wp_wysija_user_history: Data: 0.00MB + Index: 0.00MB
wp_wysija_user_list: Data: 0.04MB + Index: 0.04MB

### Post Type Counts ###

agenda: 23
attachment: 505
kadslider: 2
mapplic_map: 3
nav_menu_item: 32
page: 45
portfolio: 12
product: 2104
product_variation: 4246
redirect_rule: 173
revision: 52
shop_coupon: 2
shop_order: 120
shop_order_refund: 1
testimonial: 56
vacatures: 36
vfb_entry: 1
wpm-testimonial: 24
wysijap: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (32) ###

WPML Multilingual CMS: by OnTheGoSystems – 4.0.7
Redux Framework: by Team Redux – 3.6.11
The SEO Framework: by Sybre Waaijer – 3.0.6
BBQ Pro: by Jeff Starr – 2.1
Black Studio TinyMCE Widget: by Black Studio – 2.6.2
Caldera Forms: by Caldera Labs – 1.7.2
CMB2: by CMB2 team – 2.4.2
Enhanced E-commerce for Woocommerce store: by Tatvic – 1.2.2 – Not tested with the active version of WooCommerce
Enhanced Media Library: by wpUXsolutions – 2.7.2
Envato Market: by Envato – 2.0.1
Imagify: by WP Media – 1.8.2
Limit Login Attempts Reloaded: by wpchefgadget – 2.7.1
Mapplic: by sekler – 4.2
Members: by Justin Tadlock – 2.1.0
Mollie Payments for WooCommerce: by Mollie – 3.0.6
Safe Redirect Manager: by 10up – 1.9
Page Builder by SiteOrigin: by SiteOrigin – 2.8.2
SIW Functionaliteit: by Maarten Bruna – 1.8.2
Strong Testimonials: by Chris Dillon – 2.32
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.15.2

WooCommerce MultiStep Checkout: by Kole Roy – 2.9.2 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.4.5
WP All Import Pro: by Soflyy – 4.5.4
WP Crontrol: by John Blackbourn & contributors – 1.6.2
WP Rocket: by WP Media – 3.0.5.1
WP Rollback: by WordImpress – 1.5.1
WordPress Sentry: by Alex Bouma – 2.4.0
WP All Import - WooCommerce Add-On Pro: by Soflyy – 2.4.1
WP Pusher: by WP Pusher – 2.4.6
MailPoet 2 Premium: by MailPoet – 2.7.9
MailPoet 2: by MailPoet – 2.9
YITH WooCommerce Ajax Product Filter: by YITHEMES – 3.5.1 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #11 - /groepsprojecten/
Cart: #12 - /winkelmand/
Checkout: #13 - /aanmelden/
My account: #14 - /my-account/
Terms and conditions: #54 - /inschrijfvoorwaarden-groepsvrijwilligerswerk/

### Theme ###

Name: SIW
Version: 3.2.1
Author URL: 
Child Theme: ✔
Parent Theme Name: Pinnacle Premium
Parent Theme Version: 2.2.7
Parent Theme Author URL: https://www.kadencethemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: pinnacle_premium/woocommerce/archive-product.php
siw/woocommerce/checkout/payment-method.php
siw/woocommerce/checkout/terms.php
pinnacle_premium/woocommerce/content-product.php
pinnacle_premium/woocommerce/content-product_cat.php
pinnacle_premium/woocommerce/content-single-product.php
siw/woocommerce/emails/admin-new-order.php
siw/woocommerce/emails/customer-on-hold-order.php
siw/woocommerce/emails/customer-processing-order.php
siw/woocommerce/emails/email-footer.php
siw/woocommerce/emails/email-header.php
pinnacle_premium/woocommerce/loop/loop-end.php
pinnacle_premium/woocommerce/loop/loop-start.php
pinnacle_premium/woocommerce/loop/rating.php
pinnacle_premium/woocommerce/loop/sale-flash.php
pinnacle_premium/product-searchform.php
pinnacle_premium/woocommerce/single-product/add-to-cart/variable.php
pinnacle_premium/woocommerce/single-product/product-image.php
pinnacle_premium/woocommerce/single-product/product-thumbnails.php
pinnacle_premium/woocommerce/single-product/related.php
pinnacle_premium/woocommerce/single-product/up-sells.php
pinnacle_premium/woocommerce/single-product.php
pinnacle_premium/woocommerce/taxonomy-product_cat.php
pinnacle_premium/woocommerce/taxonomy-product_tag.php

</details>

**Comment by claudiulodro** [comment]
#21523
