### ISSUE TITLE
Shop managers have access to erasure settings but not erasure tools

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce#21515]
**Describe the bug**
A shop manager has access to the WC erasure settings which include a link to the erasure tools https://github.com/woocommerce/woocommerce/blob/master/includes/admin/settings/class-wc-settings-accounts.php#L92:L112

The privacy tools in WP require the `manage_privacy_options` to access the erasure tools https://github.com/WordPress/WordPress/blob/master/wp-admin/tools.php#L12 .

Secondly, The `desc_tip` for those settings are not escaped.

**To Reproduce**
0. Log in as a shop manager
1. Go to Accounts & Privacy Settings
2. Click on Click on one of the `account erasure requests`
3. Get the `Sorry, you are not allowed to access this page.` message.

**Expected behavior**
In addition to correcting the escaping issue, in this situation I would normally have a version of the description without the link for users without the `manage_privacy_options` cap.

If that sounds good, let me know & I will do a PR.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Should not be necessary in this case.

**Comment by claudiulodro** [comment]
@rrennick Good catch. Your solution sounds like the way to go. We'd be happy to review a pull request if you want to give it a shot. Thanks!
