### ISSUE TITLE
Cart message – error calculating amount for free shipping

### ISSUE THREAD

**Issue by matteobaro** [woocommerce/woocommerce#21514]
Hello
i try to display how much left for free shipping.
but with diffferent plugin (officiale cart messages reperible from woocommerce site) and also other plugin from other developers that do the same, display the wrong value without taxes.

this is an example:
free shipping with 150 €
i have a product that cost 81,97 € (with 22% vat customer pay 100 €)
cart messages display that left € 68.03 (but the corrent value it should be € 50)

I am testing it in a clean installation with woocommerce with no other plugin activated, only woocommerce and storefront theme

how i can i fix that?

**Comment by claudiulodro** [comment]
Hi there,

Free shipping does not take taxes into account. The merchant does not get to keep the taxes, so it would not really be wanted for free shipping with a minimum order amount to add taxes towards free shipping.

Hope this clears things up. Thanks.

**Comment by matteobaro** [comment]
Sorry but i not understand,
When cart notice has to display, free shipping is not already in use...
The plugin use a manual value for calculate free shipping
