### ISSUE TITLE
Discourage 'woocommerce_loaded' usage and log notice about issue with it

### ISSUE THREAD

**Issue by thenbrent** [woocommerce/woocommerce#21524]
The order in which the `'woocommerce_loaded'` hook is triggered depends on the WooCommerce plugin's folder name used on the site. That means when it is triggered can change depending on the site it's installed on, making it inconsistent. This issue is covered in more detail in https://github.com/woocommerce/woocommerce/issues/13426.

Mike mentioned in https://github.com/woocommerce/woocommerce/issues/13426#issuecomment-283798434:

> if you find it in the codebase it's clear where/when it's triggered.

I agree it's clear _where_ it's triggered. I disagree that it's clear _when_ it's triggered.

That is for two reasons:

1. the stack trace to see when it is called spans multiple functions and files. Specifically at the moment, the trace is:
    1. `'woocommerce_loaded'` is triggered on line 158 of `class-woocommerce.php` in `WooCommerce::__construct()`
    1. `WooCommerce::__construct()` is called via `new self()` on line 115 of `class-woocommerce.php`  in `WooCommerce::instance()` 
    1. `WooCommerce::instance()` is called via `wc()` on line 38 of `woocommerce.php`
    1. `wc()` is called on line 42 of `woocommerce.php` when its assigned to `$GLOBALS['woocommerce']`
1. even once you understand the above, to know that `woocommerce.php` plugin file can be loaded at different times (and therefore know where/when it's triggered) requires an understanding of how WordPress loads plugins, and in particular, that WordPress loads plugins in alphabetical order of the plugin's folder and file name, as mentioned in https://github.com/woocommerce/woocommerce/issues/13426#issuecomment-283784546

That to me is not something that will be clear to many developers.

Furthermore, when the hook is triggered _after_ a certain plugin, but only on certain sites, it can be very hard to diagnose why a certain callback isn't being called just on some sites and the behaviour can present in very unexpected ways, as seen in the thread on https://github.com/Prospress/woocommerce-subscriptions/issues/2960

### Proposed Solution

The issue here is the potential for misuse, and the difficultly diagnosing that misuse. Not that the hook is triggered.

To solve that could simply require logging an error when misuse is detected. That would still make life easier for the poor souls who encounter it, but avoid throwing deprecated notices on a few million sites by deprecating the hook.

To do that would require something like monitoring calls to `add_action()` for the `'woocommerce_loaded'` hook. I can't see how to do that with a quick skim of WP's code, but I'm sure it's possible in some capacity, even if it meant doing something crazy like storing all callbacks added when `'woocommerce_loaded'` is first called, and then comparing that to the callbacks added when `'plugins_loaded'` is called to see if there is any discrepancy.

### Alternative Solution

Originally, this _Issue_ proposed the following solution, including a submission via PR #21525. This was removed inline with this comment: https://github.com/woocommerce/woocommerce/issues/21524#issuecomment-452165133

> To address this, I think `'woocommerce_loaded'` usage should be actively discouraged by deprecating it and logging a notice explaining the potential issues with it.

> I understand this is a core hook and deprecating it is a major step; however, in line with the above issues, I think it's warranted. This will also introduce documentation into the code so developers can see issues with it without having to RTFM.

> Displaying this notice now will also make it possible to remove the hook in a future major release (as it would break backward compatibility majorly) if that is considered necessary. I don't see that topic necessary as part of this conversation though. For now, I think it's enough to have WC notify developers of the issue to prevent gotchas.

**Comment by lkraav** [comment]
Yep, a log warning about gotchas with this hook would've saved us 2 days of dev time in that particular bug chase.

**Comment by helgatheviking** [comment]
Could we replace this with an alternative? What if WooCommerce triggered a hook on `plugins_loaded` that was specifically for loading WooCommerce-reliant extensions....

It would probably be in the WooCommerce class, but loosely something like:
```
function woocommerce_extensions_init() {
   do_action( 'woocommerce_extensions_init' );
}
add_action( 'plugins_loaded', 'woocommerce_extensions_init' ), 20;
```

**Comment by helgatheviking** [comment]
Relatedly, is there anything we can do to make the deprecation notice actually tell you _where_ the deprecated call is coming from?

**Comment by thenbrent** [comment]
> is there anything we can do to make the deprecation notice actually tell you where the deprecated call is coming from?

@helgatheviking yep, that's possible. If #21525 isn't closed and is determined to be the best solution (I'm not convinced it is, and wouldn't be surprised if it is close), then I'll spend more time on it to adding that.

**Comment by kloon** [comment]
Would it not be more beneficial to rather move `$GLOBALS['woocommerce'] = wc();` to the plugins_loaded hook? That way plugins can continue to use woocommerce_loaded and it will not break anything, and then it will always load at a specific time during the page load? I have not tested it so it is possible that it might break other things when doing this, but something to look into.

**Comment by helgatheviking** [comment]
@kloon I like that and while I haven't tested it extensively, I can confirm that:

```
add_action( 'plugins_loaded', 'wc', 0 );
```
does resolve the reliability issue of ZZZ-plugin.php not running anything on the `woocommerce_loaded` hook in multisite (due to the WooCommerce already having fired the `woocommerce_loaded` hook before ZZZ-plugin.php is ever loaded). 

The priority doesn't have to be 0, but doing so automatically fixes all my plugins using `woocommerce_loaded` without any modification. 

That does leave a need to define `$GLOBALS['woocommerce'] = wc();` elsewhere.

**Comment by thenbrent** [comment]
> Would it not be more beneficial to rather move `$GLOBALS['woocommerce'] = wc();` to the `plugins_loaded` hook?

That would be the best approach for the code if it didn't have legacy. It's a much more widespread breaking change now though. It would lead to fatal errors with any code relying on `$woocommerce` prior to `plugins_loaded`.

In a more rare case, it would also lead to issues with code _expecting_ `woocommerce_loaded` to be run prior to `plugins_loaded`.

**Comment by willgorham** [comment]
Considering this is already targeted for 4.0, a major release, wouldn't taking the best approach for code make the most sense?

**Comment by thenbrent** [comment]
I've closed my original PR for this. The alternative approach mentioned at the bottom of this comment is a better approach than the one proposed there: https://github.com/woocommerce/woocommerce/pull/21525#issuecomment-429173262

I've also updated the **Proposed Solution** in the description on this issue to propose that.

**Comment by helgatheviking** [comment]
What if we move `woocommerce_loaded` to a super early priority on `plugins_loaded`


function woocommerce_extensions_init() {
   do_action( 'woocommerce_loaded' );
}
add_action( 'plugins_loaded', 'woocommerce_extensions_init', 0 )

**Comment by rrennick** [comment]
A priority of `0` would reduce the number of conflicts but not eliminate them.

How effective would a dashboard notice be if it was displayed when the plugin folder was not `woocommerce`?

**Comment by helgatheviking** [comment]
@rrennick The plugin folder being named something other than `woocommerce` was not the issue for me, though I've seen it in the past. The issue I saw with this hook was that in multisite, any plugin that runs after woocommerce (such as a zzz-plugin.php as it appears to go in alpha order) does not run code attached to `woocommerce_loaded` since the hook is fired before the zzz-plugin.php is loaded.

Priority `-999`? Just spitballing here. I suspect whatever happens, something is going to break somewhere. But I do like the idea of a reliable, uniform way to launch all the plugins that rely on WooCommerce (which I had previously thought _was_ `woocommerce_loaded`) so I hope we can come up with a solution.

**Comment by rrennick** [comment]
> The issue I saw with this hook was that in multisite, any plugin that runs after woocommerce (such as a zzz-plugin.php as it appears to go in alpha order)

Single sites work the same. This issue would be more common in multisite because multisite owners tend to be more creative in ways to get a variety of functionality to co-exist. The dashboard notice wouldn't fix anything but serve as a warning that there might be issues.

Hopefully, any developer writing an extension for WC is going to do it with WC installed in the default folder and it should work regardless of what the folder name is.

One situation that was reported was a multisite where multiple versions of WC were in use where custom code was being used to chose which version of WC was active on any site. The notice would help in that situation.

**Comment by mikejolley** [comment]
I'm not sure if it's still the case @helgatheviking, but there used to be a bug in WP where hooking into an action during that action would fail. i.e. If I added actions to `plugins_loaded` whilst `plugins_loaded` was running, the action would not add. By moving `woocommerce_loaded` to `plugins_loaded` that case would occur.

Would need confirming, but if that is indeed still a WP issue, deprecation is the only viable path.

**Comment by rrennick** [comment]
In 5.0.X, only the second inside function executes

```
add_action( 'init', function() {
	add_action( 'init', function() {
		echo '<!-- test 5 -->';
	}, 5 );
	add_action( 'init', function() {
		echo '<!-- test 10 -->';
	} );
}, 5 );
```

**Comment by mikejolley** [comment]
Moving discussion to https://github.com/woocommerce/woocommerce/pull/22536 which should solve this, but needs more feedback.
