### ISSUE TITLE
Ship to specific countries: can't add corresponding shipping zone

### ISSUE THREAD

**Issue by corsonr** [woocommerce/woocommerce#21527]
**Describe the bug**
Here is the scenario to replicate: I'm selling my products in France and Spain, and I want my products to be shipped to France, Spain and to Belgium

Here's my config:

![](http://cld.wthms.co/l10J18+)

and when I want to add shipping zones, **Belgium** isn't available in the list:

![](http://cld.wthms.co/KVESIr+)

**To Reproduce**

*see screenshots above*

**Screenshots**

*see screenshots above*

**Expected behavior**

I was expecting **Belgium** to be listed in the list when trying to add a shipping zone. **The only available countries are countries listed in the "Sell to specific countries" field.**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
latest WC version, local install, no other add-on, 2017 theme

**Comment by kloon** [comment]
See #22126 for fix.
