### ISSUE TITLE
Tax issue on order update status 3.5 RC1

### ISSUE THREAD

**Issue by kreamweb** [woocommerce/woocommerce#21521]
**Describe the bug**
There's an issue when I change the order status manually. For example if I have an order in pending payment with taxes and then I change the status to complete, a notice appear on error.log and the taxes are removed.

**To Reproduce**
1. Create an order with taxes
2. Open the order in backend
3. Change the status of order

**WordPress Environment**
WC 3.5 RC1

Here the notice:

[10-Oct-2018 13:32:23 UTC] PHP Warning:  array_map(): Argument #2 should be an array in /srv/www/multisite/public_html/wp-content/plugins/woocommerce/includes/class-wc-order-item-product.php on line 154

**Comment by claudiulodro** [comment]
Thanks for the report. Fixed in https://github.com/woocommerce/woocommerce/pull/21503
