### ISSUE TITLE
Problem with encoding and special chars in attributes in product editor

### ISSUE THREAD

**Issue by Pottypotsworth** [woocommerce/woocommerce#21529]
This issue https://github.com/woocommerce/woocommerce/issues/2644 was closed but the problem was only fixed for the front end.

If I create any custom product attribute and try and use ascii/URL encoded characters then they are stripped out as the attribute is saved. As others have mentioned this affects foreign language attributes along with any URLs that may have encoding (useful for storing manufacturer URL or such).

The issue is replicable when editing any product and adding an attribute with URL encoding.

Thanks

**Comment by Pottypotsworth** [comment]
Hey @rodrigoprimo,

If you try and create a new custom attribute on a product which holds a URL such as http://www.example.com?something=1&somethingelse=2 then the result will be that the attribute is stripped to http://www.example.comsomething1somethingelse2 - thus the URL becomes entirely useless.

If you are using URLs to reference an manufacturer website, or affiliate redirect, or anything like that then the stripping of the encoded characters means that the URL becomes nonsense.

Let me know if you need further clarity.

**Comment by rrennick** [comment]
I wrote a PR for another issue that will address this one as well - https://github.com/woocommerce/woocommerce/pull/21864

**Comment by Pottypotsworth** [comment]
Great, thanks for the update @rrennick

**Comment by rrennick** [comment]
This was fixed for me in 3.5.3. If you still have an issue with that version please re-open with details including how to reproduce & status report.
