### ISSUE TITLE
WooCommerce randomly adding products to orders - similar to issue #21239

### ISSUE THREAD

**Issue by andreastannah** [woocommerce/woocommerce#21528]
Hi I am having this issue with Wordpress 4.9.8 after upgrade, at first the issue was sporadic but now every order. The website only has one product but every order that is created has an extra product added (which I guess must be an old version of the product as it has the same name but old price). The customer is charged the correct amount. Have tried all the usual disabling plugins, caching etc. Am reluctant to try the fix above because to my knowledge nobody has been meddling with the database in the past. Any one found the problem or a fix?

**Comment by kloon** [comment]
@andreastannah can you please complete the tests and provide the system status page as asked when you opened the issue, the information is required to help us trouble shoot, without that we are in the dark.

I am unable to replicate this so I assume this is possibly a issue with a conflicting theme/plugin on your site, perhaps something caching related?

I will gladly reopen this issue when you can provide steps to replicate this with just WooCommerce and a default theme active.

**Comment by andreastannah** [comment]
Hi sorry for the scant detail. I have now resolved the issue by starting
with a fresh wordpress install and database and rebuilding the site so
assuming it was some corrupt data. So no longer possible to replicate.

Thanks for your help.

Andrea
