### ISSUE TITLE
Webhook Payload adds slashes to JSON 

### ISSUE THREAD

**Issue by icircletech** [woocommerce/woocommerce#21539]
I have setup webhooks for Product Updates.  The primary issue I am having is that it adds slashes to the JSON payload.   I can’t seem to find what is generating the slashes.   They appear to be trying to escape the double quotes (“). 

Any help or suggestions would be appreciated. 

Thank you! 

I am running latest WooCommerce / WordPress & PHP 7

TRUE: I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.

TRUE: This bug happens with a default WordPress theme active

**Comment by kloon** [comment]
JSON is a standard format which needs to be decoded on the receiving end before use https://www.freeformatter.com/json-escape.html
