### ISSUE TITLE
Percentage coupon excluding sales does not work in mixed cart

### ISSUE THREAD

**Issue by melindahelt** [woocommerce/woocommerce#21533]
zd-1486321

What  I expected to happen:
Coupon to work and apply to regular priced items, regardless of what was in the cart

What happened instead:
Coupon will not work if _any_ sale items are in the cart

![](http://cld.wthms.co/qEdZzV+)Image Link: http://cld.wthms.co/qEdZzV

![](http://cld.wthms.co/pvRdc7+)Image Link: http://cld.wthms.co/pvRdc7

![](http://cld.wthms.co/G3h1la+)Image Link: http://cld.wthms.co/G3h1la

This text  could be slightly misleading:

> Check this box if the coupon should not apply to items on sale. Per-item coupons will only work if the item is not on sale. Per-cart coupons will only work if there are items in the cart that are not on sale.

I read that as "you must have a regular price item in the cart  for the coupon to work" -- and that makes sense. However, WooCommerce could mean "you can't use a regular price coupon if a sale priced item is in the cart too" which seems to be wrong.

Tested with WooCommerce 3.4.5

**Comment by claudiulodro** [comment]
Fixed in 3.4.6 which was just released: https://woocommerce.wordpress.com/2018/10/11/woocommerce-3-4-6-security-fix-release-notes/
