### ISSUE TITLE
issue by displaying price with vat

### ISSUE THREAD

**Issue by SencilloDS** [woocommerce/woocommerce#21532]
Hi, there is a problem by displaying price incl vat on shop page. At first my client wanted to enter the price of the products without vat and also show the price in shop, cart and checkout without vat. I did this selections, created an own archive-template for products with elementor pro, and everything worked fine.
After 1 month my client wanted to show all products with vat, also he wanted to enter the prices with vat. I changed the settings, changed all prices for each product (with vat) and now the prices are still without vat in frontend. But after you add some product to cart (then view the cart and go back to e.g. shop page) all prices are with vat – and this forever – till you clear your browser-cache. What can I do now? There is no conflict with other plugins (I tested it out - deactivated all - now all are activated again - the website is live) and before changing all the selections, the shop worked fine without problems.

I use latest wordpress and latest woocommerce - all plugins have latest version

System Status: 
`
### WordPress Environment ###

Home URL: https://www.xn--brombelzentrale-ctb2h.at
Site URL: https://www.xn--brombelzentrale-ctb2h.at
WC Version: 3.4.5
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.10
PHP Post Max Size: 200 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.59.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.7.21
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.5
WC Database Prefix: gb_
Datenbank-Gesamtgröße: 11.68MB
Datenbank-Datengröße: 11.14MB
Datenbank-Indexgröße: 0.54MB
gb_woocommerce_sessions: Daten: 0.48MB + Index: 0.02MB
gb_woocommerce_api_keys: Daten: 0.00MB + Index: 0.00MB
gb_woocommerce_attribute_taxonomies: Daten: 0.00MB + Index: 0.00MB
gb_woocommerce_downloadable_product_permissions: Daten: 0.00MB + Index: 0.00MB
gb_woocommerce_order_items: Daten: 0.00MB + Index: 0.00MB
gb_woocommerce_order_itemmeta: Daten: 0.02MB + Index: 0.02MB
gb_woocommerce_tax_rates: Daten: 0.00MB + Index: 0.01MB
gb_woocommerce_tax_rate_locations: Daten: 0.00MB + Index: 0.00MB
gb_woocommerce_shipping_zones: Daten: 0.00MB + Index: 0.00MB
gb_woocommerce_shipping_zone_locations: Daten: 0.00MB + Index: 0.00MB
gb_woocommerce_shipping_zone_methods: Daten: 0.00MB + Index: 0.00MB
gb_woocommerce_payment_tokens: Daten: 0.00MB + Index: 0.00MB
gb_woocommerce_payment_tokenmeta: Daten: 0.00MB + Index: 0.00MB
gb_woocommerce_log: Daten: 0.00MB + Index: 0.00MB
gb_adtribes_my_conversions: Daten: 0.00MB + Index: 0.00MB
gb_aelia_dismissed_messages: Daten: 0.02MB + Index: 0.00MB
gb_aelia_exchange_rates_history: Daten: 0.02MB + Index: 0.00MB
gb_commentmeta: Daten: 0.00MB + Index: 0.01MB
gb_comments: Daten: 0.01MB + Index: 0.01MB
gb_crony_jobs: Daten: 0.00MB + Index: 0.00MB
gb_crony_logs: Daten: 5.69MB + Index: 0.02MB
gb_links: Daten: 0.00MB + Index: 0.00MB
gb_options: Daten: 0.93MB + Index: 0.10MB
gb_postmeta: Daten: 3.04MB + Index: 0.19MB
gb_posts: Daten: 0.88MB + Index: 0.08MB
gb_simple_auction_log: Daten: 0.00MB + Index: 0.00MB
gb_termmeta: Daten: 0.00MB + Index: 0.01MB
gb_terms: Daten: 0.00MB + Index: 0.01MB
gb_term_relationships: Daten: 0.00MB + Index: 0.01MB
gb_term_taxonomy: Daten: 0.00MB + Index: 0.01MB
gb_usermeta: Daten: 0.04MB + Index: 0.03MB
gb_users: Daten: 0.00MB + Index: 0.01MB
gb_wcpdf_invoice_number: Daten: 0.00MB + Index: 0.00MB
gb_wc_download_log: Daten: 0.00MB + Index: 0.00MB
gb_wc_webhooks: Daten: 0.00MB + Index: 0.00MB
gb_yoast_seo_links: Daten: 0.01MB + Index: 0.00MB
gb_yoast_seo_meta: Daten: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 262
custom_css: 1
elementor_font: 1
elementor_library: 10
nav_menu_item: 14
page: 12
post: 2
product: 27
product_variation: 4
revision: 407
shop_coupon: 1
shop_order: 10
wppb-ul-cpt: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

Booster Plus for WooCommerce: von Algoritmika Ltd – 4.0.0 – Nicht getestest mit der aktiven WooCommerce-Version
Crony Cronjob Manager: von Scott Kingsley Clark – 0.4.7
Google Tag Manager for Wordpress: von Thomas Geiger – 1.9
Elementor Pro: von Elementor.com – 2.1.10
Elementor: von Elementor.com – 2.2.5
Granular Controls Elementor: von Zulfikar Nore – 1.0.5
Loco Translate: von Tim Whitlock – 2.1.5
Profile Builder - WooCommerce Sync Add-on: von Cozmoslabs
Adrian Spiac – 1.5.2 – Nicht getestest mit der aktiven WooCommerce-Version

Profile Builder Pro: von Cozmoslabs – 2.8.6
Cookie Consent: von Catapult_Themes – 2.3.11
UpdraftPlus - Backup/Restore: von UpdraftPlus.Com
DavidAnderson – 2.15.2.24

Aelia Foundation Classes for WooCommerce: von Aelia – 1.8.10.180315 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Product Feed PRO: von AdTribes.io – 3.6.7 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce EU VAT Assistant: von Aelia – 1.8.1.180802 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce PayPal Checkout Gateway: von WooCommerce – 1.6.4 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Stripe-Gateway: von WooCommerce – 4.1.10 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Simple Auktion: von wpgenie – 1.2.25 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Table Rate Shipping: von Bolder Elements – 4.1.3 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce: von Automattic – 3.4.5
Yoast SEO: von Team Yoast – 8.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: auction (auction)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop-Basis: #10 - /shop/
Warenkorb: #11 - /warenkorb/
Kasse: #12 - /kasse/
Mein Konto: #13 - /mein-konto/
Allgemeine Geschäftsbedingungen: #3 - /datenschutzerklaerung/

### Theme ###

Name: Bulk
Version: 1.0.8
Author URL: https://themes4wp.com/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Archive Template: Dein Theme hat eine woocommerce.php-Datei
was dazu führt
dass du das Template woocommerce/archive-product.php nicht überschreiben kannst
da woocommerce.php höher gewichtet wird als archive-product.php. Das ist beabsichtigt
um Darstellungsprobleme zu verhindern.

Overrides: /home/.sites/137/site9671445/web/wp-content/plugins/pb-add-on-woocommerce/templates/myaccount-edit-profile.php Version - ist veraltet. Die Hauptversion ist 3.4.0
Outdated Templates: ❌
					
					
						Erfahre
wie du aktualisieren kannst

`

**Comment by kloon** [comment]
Seems like local caching and saved cart sessions. Cart sessions only get updated when you modify the cart of proceed to checkout, so the customer will see the correct pricing at checkout.

As for local caching, you will have to clear your site caching if you make big changes to your site like changing copy or prices for it to show immediately, caches does expire depending on the host so either do a force clear or wait a couple of days for the caches to be cleared.

I assume the issue should be resolved for you by now, so closing the issue, feel free to let me know if you are still experiencing this and I will try and replicate locally.
