### ISSUE TITLE
Database error when updating to 3.5.0

### ISSUE THREAD

**Issue by rodrigoprimo** [woocommerce/woocommerce#21534]
There might be a database error when updating to 3.5.0 as reported in https://github.com/woocommerce/woocommerce/pull/21245#issuecomment-420194220 introduced by the way I handled the new indexes on wp_woocommerce_sessions in #21245. I'm creating this issue to make sure we check this before tagging 3.5 rc2.

This is the error that @shivapoudel reported:

```
[11-Sep-2018 08:32:04 UTC] WordPress database error Multiple primary key defined for query ALTER TABLE wp_woocommerce_sessions ADD PRIMARY KEY  (`session_id`) made by activate_plugin, do_action('activate_woocommerce/woocommerce.php'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Install::install, WC_Install::create_tables, dbDelta
```

I haven't had time yet to test it properly. When I created #21245, I was under the impression that `dbDelta()` didn't handle index changes and that is why I created `wc_update_350_change_woocommerce_sessions_schema`, but maybe I was wrong? Probably worth checking.

**Comment by kloon** [comment]
dbdelta does handle creating keys, it does not however drop old keys. So my suggestion would be to leave the key creation to DB delta and then just use the update routine to drop the old key instead.

**Comment by rodrigoprimo** [comment]
@kloon, were you able to reproduce the issue that @shivapoudel reported? For some reason, I'm not. I don't get any errors on debug.log when dbDelta() is called or when I trigger the database update routine.

I believe that #21561 doesn't work. On my local environment, if I run the database update routine after applying the changes from #21561, the table `wp_woocommerce_sessions` is left unchanged. In other words, `session_key` is still the primary key and `session_id` is a unique index. cc @claudiulodro as you reviewed #21561 in case you get different results than what I'm getting.

**Comment by kloon** [comment]
Did you change the db version back to 3.4 before running the update routine?

**Comment by rodrigoprimo** [comment]
@kloon, yes. I'm dropping and importing a 3.4.6 database before testing.

I'm starting with WC 3.4.6 codebase and the following in my database:

```
MySQL [wccore]> select * from wp_options where option_name IN ('woocommerce_db_version', 'woocommerce_version');
+-----------+------------------------+--------------+----------+
| option_id | option_name            | option_value | autoload |
+-----------+------------------------+--------------+----------+
|       496 | woocommerce_db_version | 3.4.6        | yes      |
|       424 | woocommerce_version    | 3.4.6        | yes      |
+-----------+------------------------+--------------+----------+
2 rows in set (0.00 sec)

MySQL [wccore]> desc wp_woocommerce_sessions;
+----------------+---------------------+------+-----+---------+----------------+
| Field          | Type                | Null | Key | Default | Extra          |
+----------------+---------------------+------+-----+---------+----------------+
| session_id     | bigint(20) unsigned | NO   | UNI | NULL    | auto_increment |
| session_key    | char(32)            | NO   | PRI | NULL    |                |
| session_value  | longtext            | NO   |     | NULL    |                |
| session_expiry | bigint(20) unsigned | NO   |     | NULL    |                |
+----------------+---------------------+------+-----+---------+----------------+
4 rows in set (0.00 sec)
```

After I switch to the master branch and run the update routine the WC version is updated in the database but `wp_woocommerce_sessions` remains unaltered:

```
MySQL [wccore]> select * from wp_options where option_name IN ('woocommerce_db_version', 'woocommerce_version');
+-----------+------------------------+--------------+----------+
| option_id | option_name            | option_value | autoload |
+-----------+------------------------+--------------+----------+
|       513 | woocommerce_db_version | 3.5.0        | yes      |
|       500 | woocommerce_version    | 3.5.0        | yes      |
+-----------+------------------------+--------------+----------+
2 rows in set (0.00 sec)

MySQL [wccore]> desc wp_woocommerce_sessions;
+----------------+---------------------+------+-----+---------+----------------+
| Field          | Type                | Null | Key | Default | Extra          |
+----------------+---------------------+------+-----+---------+----------------+
| session_id     | bigint(20) unsigned | NO   | UNI | NULL    | auto_increment |
| session_key    | char(32)            | NO   | PRI | NULL    |                |
| session_value  | longtext            | NO   |     | NULL    |                |
| session_expiry | bigint(20) unsigned | NO   |     | NULL    |                |
+----------------+---------------------+------+-----+---------+----------------+
4 rows in set (0.00 sec)
```

Do you get different results?

**Comment by rodrigoprimo** [comment]
Related WP core ticket about `dbDelta()` being unable to change primary keys, create AUTO_INCREMENT columns and handle other index changes: https://core.trac.wordpress.org/ticket/40357

I will work on a PR to perform the `wp_woocommerce_sessions` index changes before `dbDelta()` is called.

**Comment by rodrigoprimo** [comment]
See #21601
