### ISSUE TITLE
Hide Outdated WooCommerce Templates notification

### ISSUE THREAD

**Issue by wayheming** [woocommerce/woocommerce#21543]
Hello, how can I hide this [notification](http://prntscr.com/l5bj2i) using a filter or a function, the thing is that I am a theme developer and my clients are very nervous when your plugin updates and they see this notification. As a developer, I know that if I changed your files, then I have to support them, but it happens that there is no need to update the file, and I only need to change the version of the file. It would be great for you to add such an opportunity for developers or if it already exists, tell me how I can hide the notification.

**Comment by claudiulodro** [comment]
You can use the [`woocommerce_show_admin_notice `](https://github.com/woocommerce/woocommerce/blob/d0491072e8a7d0a4535db0ec2bae4a6d43ff64fd/includes/admin/class-wc-admin-notices.php#L180) filter to suppress any of the core notices. Hope this clears things up.

**Comment by wayheming** [comment]
@claudiulodro yes it works thanks =)

**Comment by Buildbetter** [comment]
Hi can you write the exact filter to use with snippet?

**Comment by yakupseymen** [comment]
> 

https://gist.github.com/yakupseymen/3b1c87af11b956438c4215ac495fe539

**Comment by fbentele** [comment]
If anyone stumbles upon this, here is the code-and-paste snippet for your functions.php file:
```
add_filter( 'woocommerce_show_admin_notice', function ( $show, $notice ) {
	if ( 'template_files' === $notice ) {
		return false;
	}

	return $show;
}, 10, 2 );
```
