### ISSUE TITLE
Product Import error: Invalid file type. The importer supports CSV and TXT file formats.

### ISSUE THREAD

**Issue by lindamork** [woocommerce/woocommerce#21548]
**Describe the bug**

Importing products with a CSV file displays the error message:  `Invalid file type. The importer supports CSV and TXT file formats.`

I successfully imported updated products in a CSV file earlier today on a test site running 3.4.5 successfully. I updated to 3.4.6 and received the error when attempting to import the same csv file after a user reported having trouble. After rolling back to 3.4.5, I was able to import the file without trouble.

![screen shot on 2018-10-12 at 14-38-48](https://user-images.githubusercontent.com/16885584/46895469-677e9800-ce2d-11e8-8da3-62dafa0ffec5.png)

**Expected behavior**
I expected the csv file to import the updated products as it did running 3.4.5

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**Comment by grigorijurasov** [comment]
I can confirm this. 1490189 - zen

**Comment by grigorijurasov** [comment]
And one more 1489296 - zen

**Comment by rezzap** [comment]
I've been trying to do some testing on a test site for a user and can report the same behaviour. Import either from the import tool or using the top inline 'Import' option on the Product page returns the same error. Files are CSV format and they are not over the 2MB.

**Comment by onsens** [comment]
I can confirm.

Found workaround for now:
https://wordpress.org/support/topic/woocommerce-3-4-6-cannot-import-products-in-wamp-server-on-windows/

**Comment by claudiulodro** [comment]
This seems to be a side-effect of a change in 3.4.6 that checks to make sure import files are located in the WP directory for security. We'll investigate and patch if necessary. For now, the check can be easily disabled by adding this snippet to your functions.php (or wherever you add snippets):
```
add_filter( 'woocommerce_product_csv_importer_check_import_file_path', '__return_false' );
```

What sort of hosting/server are you folks using? It seems to be limited to certain types of servers.

**Comment by rezzap** [comment]
My sites are all atomic sites, so what you mention makes sense and is probably due to the restrictions on that.

**Comment by claudiulodro** [comment]
Tweaked the check in #21573 to stop this issue from happening on certain servers.

**Comment by carladoria** [comment]
reported also on 7297660-hc
