### ISSUE TITLE
woocommerce_terms_page_id doesn't update

### ISSUE THREAD

**Issue by attilabacso** [woocommerce/woocommerce#21551]
When try to save the Privacy Policy page on Woocommerce / Settings / Accounts & Privacy page, the Woocommerce doesn't update the Privacy page post_id to wp_options table woocommerce_terms_page_id row.

**Comment by claudiulodro** [comment]
Hi there,

The `woocommerce_terms_page_id` option is used for the Terms and Conditions page. The `wp_page_for_privacy_policy` option is used for the Privacy Policy page. Hope this clears things up.

Thanks.
