### ISSUE TITLE
date_on_sale_to and date_on_sale_to_gmt of the Products, they are not working.

### ISSUE THREAD

**Issue by guilherme-oliveria** [woocommerce/woocommerce#21566]
date_on_sale_to when set value, it arrives empty, and date_on_sale_to_gmt when set value over write value of date_on_sale_from, on product REST.

**Comment by guilherme-oliveria** [comment]
date_on_sale_from is okay.

**Comment by rodrigoprimo** [comment]
Could you please open another issue using one of the bug issue template (https://github.com/woocommerce/woocommerce/issues/new?template=Bug_report.md)? This will provide us with valuable information to understand the problem and how to reproduce it. Please include examples of how to reproduce the problem, expected results and actual results. Thanks.
