### ISSUE TITLE
3.5: `$product->get_image()` no longer applying additional attributes

### ISSUE THREAD

**Issue by ktmn** [woocommerce/woocommerce#21578]
**Describe the bug**
In my `mini-cart.php` template I used 

```php
$thumbnail = apply_filters('woocommerce_cart_item_thumbnail', $_product->get_image('woocommerce_thumbnail', array(
    'class' => 'my custom classes',
)), $cart_item, $cart_item_key);
```

In short, `$_product->get_image('woocommerce_thumbnail', array('class' => 'my custom classes'))` instead of `$_product->get_image()`, to get a thumbnail with custom classes applied.

But in 3.5 these classes are no longer applied.

I'm not sure what `get_image()` function is being used, I think this is the old implementation: https://docs.woocommerce.com/wc-apidocs/source-class-WC_Product.html#1793-1812

but in 3.5 I can only find this implementation:

https://github.com/woocommerce/woocommerce/blob/f1a77924544e371735cca04823ced3ccc66ed30c/includes/abstracts/abstract-wc-product.php#L1823-L1836

which seems to only pass the `$attr` to a filter, but not do anything with it.

It changed from `get_the_post_thumbnail` to `wp_get_attachment_image`, but both seem to accept the `$attr` variable so why not make use of it?

**Comment by claudiulodro** [comment]
This behavior seems to have been lost in https://github.com/woocommerce/woocommerce/commit/64b589f0325a729a1914942801f4b2cae929e013. It just needs the attributes passed into `wp_get_attachment_image`.
