### ISSUE TITLE
Stuck when create new variations from attribute

### ISSUE THREAD

**Issue by lucx11** [woocommerce/woocommerce#21572]
Having Problem with woocommerce products variations when adding attributes and after click on the button "create new variations from attribute" would just stuck on the spinning ball loading icon, it also happen when adding attributes.

I see the error log of woocommerce but can't see any error. :S

Php memory limit 512MB
PHP version 7.2 (I try with 7 and 7.1, same error)
All wp, wp plug-in and woocommerce are updated

P.s: I tried now on my MAMP server with 1GB memory limit (i5 ssd blablabla) with fresh installation of wp and woocommerce, the same problem

**Comment by zakaryafactory** [comment]
Hello,
I'm having a similar problem when I want to add or remove an attribute to a product.
The loading ball turns endlessly.
It seems that the database registration is still done.
No error in woocommerce log

**Comment by mikejolley** [comment]
Closing due to lack of feedback. The server error log rather than the WC one may provide more useful information.

Thanks
