### ISSUE TITLE
Fatal error when saving account details on a multisite network site other than the one the user was originally registered for

### ISSUE THREAD

**Issue by JakePT** [woocommerce/woocommerce#21580]
**Describe the bug**
WooCommerce throws a fatal error when attempting to update an Address from the My Account page on a multisite network site other than the site that the user originally registered on.

**To Reproduce**
1. Create a multisite network with at least 2 sites.
2. Install WooCommerce and complete the setup wizard on each site.
3. Enable _Allow customers to create an account on the "My account" page_.
4. Sign out, or use incognito mode, visit the _My Account_ page on one of the sites, and register an account.
5. Go to _Addresses_ and add a billing address.
6. Visit the _My Account_ page on the another site on the network, and go to _Addresses_. At this stage you will notice a _"You have not set up this type of address yet."_ message, even though addresses are user meta and should be set across all sites on the network.
7. Click _Edit_ to add a billing address. Despite the previous message, the fields will all have the correct values as saved on the other site.
8. Click _Save address_. Regardless of whether or not any change was made, the following fatal error will be thrown:

> **Fatal error:** Uncaught WC_Data_Exception: Please provide a valid email address. in C:\laragon\www\woocommerce\wp-content\plugins\woocommerce\includes\data-stores\class-wc-customer-data-store.php:109 Stack trace: #0 C:\laragon\www\woocommerce\wp-content\plugins\woocommerce\includes\class-wc-data-store.php(166): WC_Customer_Data_Store->create(Object(WC_Customer)) #1 C:\laragon\www\woocommerce\wp-content\plugins\woocommerce\includes\abstracts\abstract-wc-data.php(210): WC_Data_Store->create(Object(WC_Customer)) #2 C:\laragon\www\woocommerce\wp-content\plugins\woocommerce\includes\class-wc-form-handler.php(173): WC_Data->save() #3 C:\laragon\www\woocommerce\wp-includes\class-wp-hook.php(286): WC_Form_Handler::save_address('') #4 C:\laragon\www\woocommerce\wp-includes\class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #5 C:\laragon\www\woocommerce\wp-includes\plugin.php(453): WP_Hook->do_action(Array) #6 C:\laragon\www\woocommerce\wp-includes\template-loader.php(12): do_action('template_redire...') #7 C:\laragon\www\wo in **C:\laragon\www\woocommerce\wp-content\plugins\woocommerce\includes\data-stores\class-wc-customer-data-store.php** on line **109**

**Expected behavior**
The user should be able to see their address as entered on the other site, and be able to change it without a fatal error occurring.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

Home URL: http://woocommerce.test/site-1
Site URL: http://woocommerce.test/site-1
WC Version: 3.4.6
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.25 (Win64) OpenSSL/1.0.2k PHP/7.1.5
PHP Version: 7.1.5 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 36000
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.7.18
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.6
WC Database Prefix: wp_2_
MaxMind GeoIP Database: ✔
Total Database Size: 5.54MB
Database Data Size: 3.00MB
Database Index Size: 2.54MB
wp_2_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_2_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_2_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_2_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_2_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_2_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_2_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_2_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_2_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_2_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_2_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_2_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_2_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_2_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_2_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_2_comments: Data: 0.02MB + Index: 0.08MB
wp_2_links: Data: 0.02MB + Index: 0.02MB
wp_2_options: Data: 0.42MB + Index: 0.02MB
wp_2_postmeta: Data: 0.02MB + Index: 0.03MB
wp_2_posts: Data: 0.02MB + Index: 0.06MB
wp_2_termmeta: Data: 0.02MB + Index: 0.03MB
wp_2_terms: Data: 0.02MB + Index: 0.03MB
wp_2_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_2_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_2_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_2_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_3_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_3_comments: Data: 0.02MB + Index: 0.08MB
wp_3_links: Data: 0.02MB + Index: 0.02MB
wp_3_options: Data: 0.42MB + Index: 0.02MB
wp_3_postmeta: Data: 0.02MB + Index: 0.03MB
wp_3_posts: Data: 0.02MB + Index: 0.06MB
wp_3_termmeta: Data: 0.02MB + Index: 0.03MB
wp_3_terms: Data: 0.02MB + Index: 0.03MB
wp_3_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_3_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_3_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_3_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_3_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_3_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_3_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_3_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_3_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_3_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_3_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_3_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_3_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_3_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_3_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_3_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_3_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_3_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_blogs: Data: 0.02MB + Index: 0.03MB
wp_blog_versions: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 0.44MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_registration_log: Data: 0.02MB + Index: 0.02MB
wp_signups: Data: 0.02MB + Index: 0.06MB
wp_site: Data: 0.02MB + Index: 0.02MB
wp_sitemeta: Data: 0.08MB + Index: 0.03MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB

### Post Type Counts ###

page: 5
post: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.4.6

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #3 - /shop/
Cart: #4 - /cart/
Checkout: #5 - /checkout/
My account: #6 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
</details>

**Comment by JakePT** [comment]
Ok, so I've played around a bit more and logging out and logging in resolves the issue. The issue appears to be that the user has not been properly added to the second site on the network, as the site doesn't appear in the _Sites_ column until logging out and logging back in (this works when logging in through the My Account page). So the issue seems to really be that the user is able to view and use the My Account page without being properly added to that site on the network.

**Comment by rodrigoprimo** [comment]
This is the commit that introduced this bug: https://github.com/woocommerce/woocommerce/commit/2ca2cc0f6ccfb607a1ae403e10e3ee97181982c1

**Comment by mikejolley** [comment]
Related code https://github.com/woocommerce/woocommerce/blame/c3334302bd334f4c314230fb298fb52b333b794d/includes/data-stores/class-wc-customer-data-store.php#L152

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22448
