### ISSUE TITLE
set_props not including meta data tags

### ISSUE THREAD

**Issue by DennisMatise** [woocommerce/woocommerce#21582]
**Describe the bug**

When creating an order by using the data function of woocommerce there is an exception for the `meta_data` tag. There is an if statement but it's blocking the setter for this property with the `continue;` statement.  You can find the function in `/includes/abstracts/abstract-wc-data.php` and then the `set_props` function.

**To Reproduce**

1. Call the add_product with the right ID.
2. Give the add_product a `meta_data` array following the right props

**Expected behavior**

By calling the add_product function you should be able to add a new meta_data to the product. This is now being blocked by the `continue;` statement. If you remove this it works properly.

I'm creating a own order by using the WC class obstructor and the `wc_create_order()` function.

**Comment by claudiulodro** [comment]
See #21583
