### ISSUE TITLE
Variable Subscription: Product type not recognized during a CSV import

### ISSUE THREAD

**Issue by absoluteweb** [woocommerce/woocommerce#21584]
**Describe the bug**
It is not possible to import subscription variations from the CSV import, the product type is not recognized.

Example with 1 product and 3 variations:
Import complete! 1 product imported. Failed to import 3 products. View import log
Import log:
Product | Reason for failure
Mon produit importé test 2 - 6 mois, ID 20054 | Invalid product type.

**To Reproduce**
1. Go to Products > Import Products
2. Import this file (it is an export from WooCommerce):
[import-fail.txt](https://github.com/woocommerce/woocommerce/files/2482527/import-fail.txt)
3. See error

**Comment by claudiulodro** [comment]
Hi there,

Is the Subscriptions plugin active when you are trying to import these? Subscriptions are not one of the core WooCommerce product types, so any importer support would have to be added by the Subscriptions plugin. Hope this clears things up.

Thanks.

**Comment by absoluteweb** [comment]
Hi,
Yes the Subscriptions plugin is active when I try to import file. Are you saying that I need to contact WooCommerce Subscriptions support for this problem? 
Nicolas.

**Comment by claudiulodro** [comment]
Hi Nicolas,

Yes, I recommend contacting them. I am unsure whether the Subscriptions plugin has CSV import support or not.

Thanks.
