### ISSUE TITLE
[WC Beta Tester] Duplicate index on table woocommerce_sessions in "3.5.0-rc.2"

### ISSUE THREAD

**Issue by thomas-zg** [woocommerce/woocommerce#21592]
**Describe the bug**
After updating the 3.4.6 database to 3.5.0-rc2, there is a duplicate index for the column session_key in wc_sessions table. One is the primary key, the other one an index named session_key.
<img width="806" alt="grafik" src="https://user-images.githubusercontent.com/25877146/47048657-5c17cd80-d19b-11e8-8eec-e5f70bff4fbe.png">

**To Reproduce**
1. Use a 3.4.x database for updating to 3.5.0-rc2
2. Run the database updater in the backend
3. Check the indexes in the database tool

**Screenshots**
After update:
<img width="806" alt="grafik" src="https://user-images.githubusercontent.com/25877146/47048691-7356bb00-d19b-11e8-87cf-b206530cf50d.png">

**Expected behavior**
Cleanup the indexes on table woocommerce_session in the database updater to 3.5

**Isolating the problem (mark completed items with an [x]):**
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

Startseiten-URL.: https://beta.firewoodshop.ch
Seiten-URL.: https://beta.firewoodshop.ch
WooCommerce Version.: 3.5.0
Protokoll-Verzeichnis: /home/zuegerpi/www/beta.firewoodshop.ch/wp-content/uploads/wc-logs/
Ist das Protokoll-Verzeichnis beschreibbar?: yes
WordPress Version.: 4.9.8
Ist es eine WordPress Multisite?: no
WordPress Speicher-Limit.: 536870912
Ist der WordPress Debug Modus aktiviert?: yes
Sind WordPress Cron Jobs aktiviert?: yes
WordPress Sprache.: de_CH
External object cache: no
Server Info.: Apache/2.4
PHP Version.: 7.2.11
PHP max. post Grösse.: 16777216
PHP max. Ausführungszeit.: 30
PHP max input vars.: 1000
cURL Version.: 7.61.1, OpenSSL/1.0.2p
Ist SUHOSIN installiert?: no
Maximale Uploadgrösse.: 16777216
MySQL Version.: 5.5.5
MySQL-Versions-String.: 5.5.5-10.1.35-MariaDB
Standard-Zeitzone.: UTC
Ist fsockopen/cURL aktiviert?: yes
Ist die SoapClient Klasse aktiviert?: yes
Ist die DomDocument Klasse aktiviert?: yes
Ist GZip aktiviert?: yes
Ist mbstring aktiviert?: yes
Remote POST erfolgreich?: yes
Remote-POST Antwort.: 200
Remote GET erfolgreich?: yes
Remote-GET Antwort.: 200

### Plugins ###

WooCommerce Advanced Product Labels: by BeRocket - 1.1.11 - Not tested with the active version of WooCommerce
Classic Editor: by WordPress Contributors - 0.4 - 
Contact Form 7: by Takayuki Miyoshi - 5.0.4 - 
Disable Emails: by WebAware - 1.3.0 - 
Email Address Encoder: by Till Krüss - 1.0.7 - 
WooCommerce Delivery Slots by Iconic: by Iconic - 1.7.12 - Not tested with the active version of WooCommerce
Limit Login Attempts Reloaded: by wpchefgadget - 2.7.1 - 
Storefront Powerpack: by WooCommerce - 1.4.12 - 
WooCommerce Custom Invoice BACS Gateway: by Thomas Zueger - 1.0.4 - Not tested with the active version of WooCommerce
WooCommerce Round Numbers: by Thomas Zueger - 1.2 - Not tested with the active version of WooCommerce
WooCommerce Shop Helper: by Thomas Zueger - 1.2 - Not tested with the active version of WooCommerce
User Switching: by John Blackbourn &amp; contributors - 1.4.0 - 
WooCommerce Dynamic Pricing &amp; Discounts: by RightPress - 2.2.8 - Not tested with the active version of WooCommerce
Mindestbestellmenge: by Morning Train Technologies ApS - 2.3.0 - Not tested with the active version of WooCommerce
WooCommerce Advanced Shipping - Advanced Pricing: by Jeroen Sormani - 2.2.1 - Not tested with the active version of WooCommerce
WooCommerce Advanced Shipping Zones: by Jeroen Sormani - 1.1.2 - Not tested with the active version of WooCommerce
WooCommerce Advanced Shipping: by Jeroen Sormani - 1.0.14 - Not tested with the active version of WooCommerce
WooCommerce Beta Tester: by WooCommerce - 2.0.0 - Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce - 4.1.10 - Not tested with the active version of WooCommerce
WooCommerce PDF Invoices &amp; Packing Slips: by Ewout Fernhout - 2.2.1 - Not tested with the active version of WooCommerce
WooCommerce PDF Invoices &amp; Packing Slips Premium Templates: by Ewout Fernhout - 2.5.7 - Not tested with the active version of WooCommerce
WooCommerce TM Extra Product Options: by themeComplete - 4.6.9.4 - Not tested with the active version of WooCommerce
WooCommerce: by Automattic - 3.5.0-rc.2 - 
REST API Log: by Pete Nelson - 1.6.5 - 

### Theme ###

Name: Storefront Child Theme
Version: 1.0
Author URL: http://woothemes.com
Child Theme: YesParent theme name: Storefront
Parent theme version: 2.3.4
Parent theme author URL: https://woocommerce.com/

WooCommerce Support: Yes

</details>

**Comment by thomas-zg** [comment]
Just downloaded the latest master, still the same result. Furthermore, the session_id should be the primary key. The database system is MySQL-Versions-String.: 5.5.5-10.1.35-MariaDB

**Comment by claudiulodro** [comment]
Hi there.

Thanks for the report. This is a known issue and should be patched in https://github.com/woocommerce/woocommerce/pull/21601.

Thanks.
