### ISSUE TITLE
Missing customer order note field from edit order in wp-admin (WC 3.4.6)

### ISSUE THREAD

**Issue by BodnarAgnes** [woocommerce/woocommerce#21598]
After update to 3.4.6 when we edit an order in wp-admin the field where we can edit the customer note comes from checkout is completely missing.

**Comment by claudiulodro** [comment]
Hi there,

I'm not sure exactly what you are saying here. Is this field missing for you?
<img width="309" alt="screen shot 2018-10-17 at 8 34 24 am" src="https://user-images.githubusercontent.com/7317227/47098113-88593b80-d1e7-11e8-8ac4-1c2f65e52985.png">

Can you please explain the issue more? The more information you give us the better we can identify the problem. Thanks.

**Comment by kloon** [comment]
Have not had any feedback so closing the issue. We are unable to replicate this, but will gladly reopen if we have steps to reproduce.
