### ISSUE TITLE
Can't fill in First and Last name in Checkout Form Woocommerce

### ISSUE THREAD

**Issue by zinodegroot** [woocommerce/woocommerce#21604]
**Describe the bug**
People cant type their names in the required fields

**To Reproduce**
1. Go to Shop
2. Click on Add to cart for one of the products
3. Click on the Checkout button
4. Try to fill in your name and you'll see you can't

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] I can reproduce this bug consistently using the steps above.

Home URL: http://zinodegroot.com
Site URL: http://zinodegroot.com
WC Version: 3.4.6
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.31 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 5000
cURL Version: 7.38.0
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.34-MariaDB-1~jessie
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.6
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 13.85MB
Database Data Size: 12.72MB
Database Index Size: 1.13MB
wp_woocommerce_sessions: Data: 8.02MB + Index: 0.05MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_blc_filters: Data: 0.00MB + Index: 0.00MB
wp_blc_instances: Data: 0.00MB + Index: 0.00MB
wp_blc_links: Data: 0.01MB + Index: 0.01MB
wp_blc_synch: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_comments: Data: 0.00MB + Index: 0.01MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_gglcptch_whitelist: Data: 0.02MB + Index: 0.00MB
wp_huge_itportfolio_images: Data: 0.00MB + Index: 0.00MB
wp_huge_itportfolio_portfolios: Data: 0.00MB + Index: 0.00MB
wp_huge_itslider_images: Data: 0.00MB + Index: 0.00MB
wp_huge_itslider_params: Data: 0.00MB + Index: 0.00MB
wp_huge_itslider_sliders: Data: 0.00MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 2.51MB + Index: 0.35MB
wp_pollsa: Data: 0.00MB + Index: 0.00MB
wp_pollsip: Data: 0.00MB + Index: 0.01MB
wp_pollsq: Data: 0.00MB + Index: 0.00MB
wp_postmeta: Data: 0.77MB + Index: 0.15MB
wp_posts: Data: 0.61MB + Index: 0.07MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_revslider_css: Data: 0.30MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.00MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.01MB + Index: 0.00MB
wp_revslider_slides: Data: 0.02MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
wp_sg_action: Data: 0.00MB + Index: 0.00MB
wp_sg_config: Data: 0.00MB + Index: 0.00MB
wp_sg_schedule: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.00MB + Index: 0.01MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.01MB
wp_usermeta: Data: 0.01MB + Index: 0.02MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wdi_feeds: Data: 0.00MB + Index: 0.00MB
wp_wdi_themes: Data: 0.00MB + Index: 0.00MB
wp_wpmm_subscribers: Data: 0.00MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 258
customize_changeset: 7
flamingo_contact: 24
flamingo_inbound: 36
jetpack_migration: 2
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
jp_vid_sitemap: 2
nav_menu_item: 8
page: 9
polylang_mo: 1
portfolio: 18
post: 5
product: 1
revision: 164
shop_order: 6
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (30) ###

Akismet Anti-Spam: by Automattic – 4.0.8
Backup: by BackupGuard – 1.1.69
Jetpack Support Debug Tool: by Brandon Kraft – 0.1.0
Broken Link Checker: by Janis Elsts
Vladimir Prelovac – 1.11.5

Contact Form 7: by Takayuki Miyoshi – 5.0.4
Contact Widgets: by GoDaddy – 1.5.2
Dani Core: by Spab Rice – 1.6
Flamingo: by Takayuki Miyoshi – 1.9
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 5.3.5
Google Captcha (reCAPTCHA) by BestWebSoft: by BestWebSoft – 1.37
Google XML Sitemaps: by Arne Brachhold – 4.0.9
Instagram Feed: by Smash Balloon – 1.10.1
Jetpack by WordPress.com: by Automattic – 6.6.1
Klarna Checkout for WooCommerce: by Krokedil – 1.7.2
Mollie Payments for WooCommerce: by Mollie – 5.0.2
Page Links To: by Mark Jaquith – 3.0.1
Post Types Order: by Nsp Code – 1.9.3.9
POWr Social Media Icons: by POWr.io – 1.6.4
Quick Page/Post Redirect Plugin: by anadnet – 5.1.8
Slider Revolution: by ThemePunch – 5.3.0.2
Use Any Font: by Dinesh Karki – 5.0
Woo Checkout Field Editor Pro: by ThemeHiGH – 1.2.8
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.4
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.2.1
WooCommerce Services: by Automattic – 1.16.1
WooCommerce: by Automattic – 3.4.6
Yoast SEO: by Team Yoast – 8.4
WP Edit: by Josh Lobe – 4.0.4
WP Maintenance Mode: by Designmodo – 2.2.1
WP-Polls: by Lester 'GaMerZ' Chan – 2.73.8

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #737 - /shop/
Cart: #738 - /cart/
Checkout: #739 - /checkout/
My account: #740 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Dani
Version: 1.6
Author URL: http://www.spab-rice.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: dani/woocommerce/archive-product.php
dani/woocommerce/cart/cart-item-data.php
dani/woocommerce/cart/cart-totals.php
dani/woocommerce/cart/cart.php
dani/woocommerce/cart/mini-cart.php
dani/woocommerce/checkout/form-billing.php
dani/woocommerce/checkout/form-checkout.php
dani/woocommerce/checkout/form-coupon.php
dani/woocommerce/checkout/form-login.php
dani/woocommerce/checkout/form-shipping.php
dani/woocommerce/checkout/payment.php
dani/woocommerce/checkout/thankyou.php
dani/woocommerce/content-product.php
dani/woocommerce/content-single-product.php
dani/woocommerce/global/quantity-input.php
dani/woocommerce/loop/add-to-cart.php
dani/woocommerce/loop/loop-end.php
dani/woocommerce/loop/loop-start.php
dani/woocommerce/loop/pagination.php
dani/woocommerce/loop/sale-flash.php
dani/woocommerce/myaccount/form-login.php
dani/woocommerce/myaccount/my-address.php
dani/woocommerce/order/order-details-customer.php
dani/woocommerce/order/order-details.php
dani/woocommerce/product-searchform.php
dani/woocommerce/single-product/add-to-cart/grouped.php
dani/woocommerce/single-product/meta.php
dani/woocommerce/single-product/price.php
dani/woocommerce/single-product/product-image.php
dani/woocommerce/single-product/product-thumbnails.php
dani/woocommerce/single-product/related.php
dani/woocommerce/single-product/review-meta.php
dani/woocommerce/single-product/review.php
dani/woocommerce/single-product/sale-flash.php
dani/woocommerce/single-product/share.php
dani/woocommerce/single-product/short-description.php
dani/woocommerce/single-product/tabs/additional-information.php
dani/woocommerce/single-product/tabs/description.php
dani/woocommerce/single-product/tabs/tabs.php
dani/woocommerce/single-product/up-sells.php
dani/woocommerce/single-product-reviews.php
dani/woocommerce/single-product.php

### Klarna Checkout ###

Orders created via API callback: 0% (0 of 0) of all orders paid via Klarna Checkout were created via API callback during the last month. This is a fallback order creation feature. You should aim for 0%.
`

**Comment by WillBrubaker** [comment]
This is an issue with the theme. Disabling this ![see screen shot](http://cld.wthms.co/paiY3T+) bit of CSS allows one to enter a value in the "First name" field. Contact the theme author for support.
