### ISSUE TITLE
Multisite roles limited to "customer"

### ISSUE THREAD

**Issue by EdithAllison** [woocommerce/woocommerce#21600]
When activating WooCommerce on multisite, the only available role for users is "customer". No other roles are available in dropdown despite being listed in database. Deactivating WooCommerce restores the role selection to the standard dropdown list. 

Tested with WooCommerce 3.4.6
WordPress 4.9.8

Screenshot with WooCommerce active = only role is "customer"
<img width="386" alt="bildschirmfoto 2018-10-17 um 16 42 57" src="https://user-images.githubusercontent.com/19706428/47094568-c0826d80-d22b-11e8-97bc-cfdb826b909d.png">

Screenshot with WooCommerce deactivated = all roles available in dropdown
<img width="448" alt="bildschirmfoto 2018-10-17 um 17 13 09" src="https://user-images.githubusercontent.com/19706428/47096715-0e997000-d230-11e8-92a4-015cb6ac9b28.png">

Screenshots are from subsite wp admin > Users > Add New User

**Comment by claudiulodro** [comment]
Hi there,

Thanks for the report. This is a known issue. Please see [this comment](https://github.com/woocommerce/woocommerce/issues/21579#issuecomment-430303125) for more information about the patch.

Thanks.
