### ISSUE TITLE
Changing the "No shipping methods available message to custom a message"

### ISSUE THREAD

**Issue by xsivnz** [woocommerce/woocommerce#21606]
Hi all im looking to change the "No shipping method available" message in woo commerce to a custom message " please contact me on "email address" or "phone number"  
i use weight based shipping and in an order is over the max weight it comes up with "no shipping method available"

i thought it be easier to copy the file into my child theme and change the text. 

question 
what file is this message stored in. 

many thanks

**Comment by christixnnl** [comment]
The message is located in /cart/cart-shipping.php

**Comment by xsivnz** [comment]
Thank u
