### ISSUE TITLE
3.4.6 causes multisite to not have any other user roles than Customer.

### ISSUE THREAD

**Issue by slash1andy** [woocommerce/woocommerce#21611]
**Describe the bug**
Upon updating to 3.4.6, all user roles are gone on multisites except Customer. Deactivating WooCommerce or rolling back to 3.4.5 fixes it. 

**To Reproduce**
1. Have a multisite with 3.4.6
2. Go to add user.
3. Only role available is customer

**Screenshots**
![](http://cld.wthms.co/xjDWXq+)

**Expected behavior**
I expected to have all user roles.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

CC; @LaurenaRehbein for helping me track this down.

**Comment by claudiulodro** [comment]
Fixed in 3.4.7 which was just released a few minutes ago.

**Comment by slash1andy** [comment]
Nice, thanks @claudiulodro
