### ISSUE TITLE
Credit card graphics are HUGE in Square for Woocommerce

### ISSUE THREAD

**Issue by oneinfiveadmin** [woocommerce/woocommerce#21615]
We're currently using the Square for Woocommerce plugin for checkout, as our only method of payment.

However, the credit card graphics from the plugin are ridiculously large.

![screen shot 2018-10-19 at 11 51 32 pm](https://user-images.githubusercontent.com/44294616/47219721-5ae4db80-d3fb-11e8-890f-8de02a452400.png)

Assistance with this would be much appreciated, thanks!

**Comment by rodrigoprimo** [comment]
This forum is for WooCommerce core bugs, enhancements and feature requests. The Square extension that you use is the one developed by Automattic, please use the link below to report your problem:

https://woocommerce.com/contact-us/
