### ISSUE TITLE
bulk edit of product categories not working

### ISSUE THREAD

**Issue by davisfamille** [woocommerce/woocommerce#21610]
When trying to change additional category for a product, will not 'stick' during bulk edit.  Change category, update, and change does not happen.

1. Go to products
2. Filter by category
3. Select all products returned 
4. Bulk actions = 'Edit'
5. Change category (one category remains the same, the one I sorted using the filter.  The other category needs to be removed.)
6. Update
7. No change

Wordpress 4.9.8

**Comment by rodrigoprimo** [comment]
This functionality is provided by WordPress and not WooCommerce. It only supports adding categories when bulk editing posts (or any other custom post type like products). It doesn't support removing categories or viewing already selected ones.

There is a WordPress core ticket to track this issue: https://core.trac.wordpress.org/ticket/11302

Unfortunately, I don't think there is anything we can do on WooCommerce side.
