### ISSUE TITLE
PayPal validation rule for decimals

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce#21627]
**Is your feature request related to a problem?**

Yes, sometimes PayPal Standard throws an error `Payment error: Amounts do not match` when user have **Number of Decimals** set to 0.

class-wc-gateway-paypal-ipn-handler.php does have a validation rule to resolve that without setting **Number of Decimals** set to 2:

```
if ( number_format( $order->get_total(), 2, '.', '' ) !== number_format( $amount, 2, '.', '' ) ) {
```

https://github.com/woocommerce/woocommerce/blob/9351d0c9373740f419bade942515573f91c5b238/includes/gateways/paypal/includes/class-wc-gateway-paypal-ipn-handler.php#L155

While [class-wc-gateway-paypal-pdt-handler.php](https://github.com/woocommerce/woocommerce/blob/master/includes/gateways/paypal/includes/class-wc-gateway-paypal-pdt-handler.php) does not.

**Describe the solution you'd like**

Add the same validation rule to class-wc-gateway-paypal-pdt-handler.php as well.

**Additional context**
It was reported by customer:

> You can make the same corrections to the class-wc-gateway-paypal-pdt-handler file that you made to the class-wc-gateway-paypal-ipn-handler file
namely if (number_format ($ order-> get_total (), 2, '.', '')! == number_format ($ amount, 2, '.', ''))
without this amendment, for people who have the Number of decimals = 0 parameter set when paying via PayPal, an error occurs. Payment error: Amounts do not match
Thank you very much, otherwise I constantly have to update this file manually, after each update of woocommerce

Would you consider adding this? Is there any limitations for that?

Thanks a lot for looking into it :)

**Comment by kloon** [comment]
See #21729
