### ISSUE TITLE
products act like hidden even if visible

### ISSUE THREAD

**Issue by wegastudios** [woocommerce/woocommerce#21620]
Hi guys, I’ve a strange problem with my woocommerce:
I use WP All Import to sync store products with a CRM and all works fine except for products where I update the stock: those products doesn’t appear in the catalog and in the search even if in every product the status is not updated or forcely updated to “visible” by All Import.

If i go in the product manager and change it in hidden then i put it visible again the store shows the product rightly.

I’ve tried to export an xml file of the product before and after this move, but it looks identical.

**Comment by rodrigoprimo** [comment]
I'm sorry, but we use GitHub issues exclusively for WooCommerce core bugs, enhancements and feature requests. We don't provide support for WooCommerce core or other WordPress plugins. If you believe you found a WooCommerce core bug, please open another issue following the bug template (https://github.com/woocommerce/woocommerce/issues/new?template=Bug_report.md). For support, you could try WooCommerce support forum on WP.org (https://wordpress.org/support/plugin/woocommerce) or WP All Import. If you are a WooCommerce.com customer, you could contact our support at https://woocommerce.com/contact-us/.
