### ISSUE TITLE
Calling or adjusting product variation gives a 404

### ISSUE THREAD

**Issue by LucSpan** [woocommerce/woocommerce#21626]
**My Code**

Calling a product with variations,

`product = uk_wcapi.get('products/51369').json()`

this works fine.

This product has several variations,

`print(product['variations'])`
gives all the variations: https://gist.github.com/LucSpan/8185fa540cdd4267744f6c49f4b2a698

**Problem**

I can't seem to call or edit product variations.

Following the explanation in the REST API documentation, when I try to edit `51369`'s first product variation with id `52548`, i.e.

`product_variation_1 = uk_wcapi.get('products/51369/variations/52548').json()`

the `product_variation_1` equals,

`{'code': 'rest_no_route',
 'data': {'status': 404},
 'message': 'No route was found matching the URL and request method'}`

I get the above error for any product variation of any of the products with variations.

What am I doing wrong?

**Comment by leventesen** [comment]
I have a similiar issue.
I can't create a product variation with Node.js, it gives me 'rest_no_route' error too.

**Comment by leventesen** [comment]
I am first creating a product, then trying to create a variation with the created product id but I get 404 error.

**Comment by leventesen** [comment]
I found the reason of my problem.
Api connection parameter was `version: 'wc/v1'`, after change to `version: 'wc/v2'` the problem is resolved.

**Comment by rodrigoprimo** [comment]
I'm sorry but this is not a support channel. For support, you could try WooCommerce support forum on WP.org: https://wordpress.org/support/plugin/woocommerce. If you believe you found a WooCommerce core bug, please open another issue following the bug template: https://github.com/woocommerce/woocommerce/issues/new?template=Bug_report.md. Thanks.
