### ISSUE TITLE
No Payment Options to Click when using Stripe on iPhone 8

### ISSUE THREAD

**Issue by SGRJon** [woocommerce/woocommerce#21625]
**Describe the bug**
User cannot enter credit card information using Stripe in WooCommerce storefront without scrolling way down.  The Credit Card icons are very large on mobile and when you click the stripe option they gray out and you have to scroll way down to find the CC entry fields.  

**To Reproduce**
1. Go to the checkout and choose "Credit Card (Stripe)" as the payment option
2. there is nothing to click on
**Screenshots**
![img_2068](https://user-images.githubusercontent.com/44331461/47262670-d22a7600-d4b4-11e8-9f35-b5b21fb5c55f.PNG)

**Expected behavior**
User should be able to enter CC information

- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by SGRJon** [comment]
Issue was resolved by setting the height of the payment requests icons from 44 to 10

**Comment by SGRJon** [comment]
This is still happening on sovereigngracerevolution.com on mobile iPhone 8 with WooCommerce StoreFront theme.

**Comment by claudiulodro** [comment]
Hi there,

This issue actually seems to be coming from the Jetpack plugin. Looking at the site, this style overrides the WC/Stripe gateway card image styles:
<img width="417" alt="screen shot 2018-10-22 at 10 15 02 am" src="https://user-images.githubusercontent.com/7317227/47307293-8cb89680-d5e3-11e8-8d09-8eb21daee5c5.png">
And is coming from the stylesheet at `https://sovereigngracerevolution.com/wp-content/plugins/jetpack/modules/minileven/theme/pub/minileven/style.css?ver=4.9.8` which is [the Jetpack mobile theme](https://jetpack.com/support/mobile-theme/). I recommend opening an issue at [the Jetpack repo](https://github.com/Automattic/jetpack/issues). Easiest temporary solution for your site would be to disable the Jetpack mobile theme and use the Storefront theme's regular mobile styling (which should look great!). Hope this clears things up.

Thanks.

cc @roykho in case he wants to add special styling to the Stripe gateway to handle the Jetpack mobile theme.
