### ISSUE TITLE
SSL notice caused by Linux cron

### ISSUE THREAD

**Issue by dvershinin** [woocommerce/woocommerce#21621]
**Describe the bug**
The following notice being displayed in admin despite store being fully SSL:

> Your store does not appear to be using a secure connection. We highly recommend serving your entire website over an HTTPS connection to help keep customer data secure

**To Reproduce**
1. Configure Wordpress cron to be run as real Linux cron, e.g.: `* * * * * /usr/bin/php /var/www/html/wp-cron.php`
2. Wait until it runs

**Screenshots**

![screenshot 2018-10-20 12 22 19](https://user-images.githubusercontent.com/250071/47253912-f2314980-d462-11e8-9b38-aacdeda5e78a.png)

**Expected behavior**
Woocommerce should not be adding the notice. It should not rely on results of `is_ssl` without checking context first (CLI or web).

**Comment by lkraav** [comment]
@dvershinin curious, does this also happen when using a more solid WP-CLI-based cron runner, such as `*/5 * * * * WP_CLI_CONFIG_PATH="$WP_PATH/wp-cli.yml" /usr/local/bin/wp --path="$WP_PATH" cron event run --due-now > /dev/null`

**Comment by jobthomas** [comment]
Another potential one: 1519340-zen

**Comment by jobthomas** [comment]
Another potential one: 7584582-hc

**Comment by kloon** [comment]
See #21728
