### ISSUE TITLE
Extensions: Notice button styles incorrect on WooCommerce.com Subscriptions screen

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce#21637]
**Describe the bug**
The height and padding of notice buttons is incorrect on the Extensions > WooCommerce.com Subscriptions screen

**To Reproduce**
1. Have at least one notice present
2. Navigate to the Extensions > WooCommerce.com Subscriptions screen
3. See bad styles

**Screenshots**

<img width="1030" alt="screen shot 2018-10-23 at 3 39 41 pm" src="https://user-images.githubusercontent.com/1595739/47395120-35e1b880-d6da-11e8-8c20-762487e359a1.png">

<img width="1027" alt="screen shot 2018-10-23 at 3 39 59 pm" src="https://user-images.githubusercontent.com/1595739/47395121-367a4f00-d6da-11e8-8196-6cb0ba458861.png">

**Expected behavior**
I expected the notice button styles to be consistent across wp-admin.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.

Home URL: |   | https://www.allensnook.com
-- | -- | --
Site URL: |   | https://www.allensnook.com
WooCommerce version: |   | 3.5.0
WordPress version: |   | 4.9.8
WordPress multisite: |   | –
WordPress memory limit: |   | 256 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –

```
</details>

**Comment by kloon** [comment]
See #21708
