### ISSUE TITLE
3.4.7 Upgrade took down site: Fatal error: Class 'WC_Payment_Gateway' not found

### ISSUE THREAD

**Issue by Espresso366** [woocommerce/woocommerce#21632]
Upgraded from 3.4.6 to 3.4.7 and immediately received a Fatal Error on both front and backend of site:

`Fatal error: Class 'WC_Payment_Gateway' not found in /homepages/.../wp-content/plugins/woo-rfq-for-woocommerce/includes/classes/gateway/wc-gateway-gpls-request-quote.php on line 18`

Line 18 of wc-gateway-gpls-request-quote.php:
`class WC_Gateway_GPLS_Request_Quote extends WC_Payment_Gateway`

**To Reproduce**
I installed WooCommerce 3.4.6 and activated WooCommerce Gateway to Stripe, but did not setup a Stripe account or do any additional setup.
Then I upgraded to WooCommerce 3.4.7 and the entire site was taken down. 

Any website under the main domain produces this error. 

**WordPress Environment**
Wordpress version 4.9.8 using 'Photograph 1.1.5' theme

**Workaround**
By manually reverting back to WooCommerce 3.4.6 from the GitHub release repository here: https://github.com/woocommerce/woocommerce/releases I was able to get the dashboard site (wp-admin) to respond. This showed that WooCommerce was again at 3.4.6, but was not activated. Once activating the main site was restored. 

I then deactivated Woo Commerce Gateway for Stripe, and Deleted it. Then I was able to upgrade to 3.4.7 without issue. I have not tried to install Stripe again.

**Comment by claudiulodro** [comment]
That seems to be an issue in the `woo-rfq-for-woocommerce` plugin where the code may not be set up to properly handle things if WooCommerce is not present (e.g. while the WooCommerce plugin is in the process of downloading/installing the updated version) and not an issue in the WooCommerce core plugin.

If you look at the [updated code from WC 3.4.6 to WC 3.4.7](https://github.com/woocommerce/woocommerce/compare/3.4.6...3.4.7) you will see that it is only about 20 lines of code none of which have to do with payment gateways, so the update could not possible have introduced a bug that breaks the payment gateway. Hope this clears things up.

Thanks.
