### ISSUE TITLE
Woocommerce Making the Region/State Field Required in shipping address

### ISSUE THREAD

**Issue by xsivnz** [woocommerce/woocommerce#21638]
Hi all. 
im using WooCommerce Table Rate Shipping this site. It calculates the rates via the region field. i could change it to Postcode but the over heads in managing them is a pain. 

I have a child theme set up. with a fuctions.php file in it. The code below was entered into the fuction.php file but i dont see the flied changing to required. Even after i have cleared the temp int files
does any one have the right code for this.  or am i missing this. 
many thanks 

/**
 * WooCommerce Extra Feature
 * --------------------------
 *
 * Make "state" field required on checkout
 *
 */
 
add_filter( 'woocommerce_default_address_fields' , 'optional_default_address_fields' );
function optional_default_address_fields( $address_fields ) {
$address_fields['postcode']['required'] = true;
$address_fields['Region']['required'] = true;
return $address_fields;
}

**Comment by xsivnz** [comment]
Got it sorted. i have added this to my child fuctions.php file

  $locale['NZ'] - this is where i sell 2


add_filter('woocommerce_get_country_locale', 'custom_nz_locale');
function custom_nz_locale($locale){
  $locale['NZ']['state']['required'] = true;
  return $locale;
}

**Comment by claudiosanches** [comment]
Hi there. GitHub is primarily for reporting bugs and is not a support forum. We don’t support custom development here. You could ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce
