### ISSUE TITLE
Restrict to download the virtual product if its path(upload directory) exposed

### ISSUE THREAD

**Issue by abdullah1908** [woocommerce/woocommerce#21630]
**Describe the bug**
We are running a marketplace where we sell the virtual(downloadable) products. There should be an option to enable the anti-hot-linking for the virtual products so anonymous couldn't download the product. This is a very critical bug and it should be fixed ASAP.

**To Reproduce**
1. Simply go to the Product detail page from the admin
2. Copy the URL of the file(Downloadable Product)
e.g (https://siteurl/wp-content/uploads/woocommerce_uploads/2018/10/product_name.zip)
3. Open the file URL in private window or any-other browser where you are not logged-in
4. It'll download the product

**Expected behavior**
It should give some error like "Invalid Link or You don't have permission to access this URL." and stop from downloading the product.

**WordPress Environment**
WP Version: 4.9.8
WooCommerce Version: 3.4.7

**Comment by claudiulodro** [comment]
Hi there,

When customers purchase your downloadable products those downloads will be handled by WooCommerce's download handler, and the download handler enforces permissions. As the direct file link (e.g. https://siteurl/wp-content/uploads/woocommerce_uploads/2018/10/product_name.zip) is just a file sitting on a server, WordPress does not get loaded when you go to that link so we cannot enforce permissions on it. There are two things you can do if you are worried about people discovering and downloading your downloadable files:
- Give the files a hard-to-guess name (e.g. `product_name_ab110783e021.zip`), and nobody will be able to discover it unless they already have the file URL. Alternately, you can host the downloads offsite on S3 or somewhere else like that.
- Control those file permissions at the server level by e.g. modifying your htaccess file if your site runs on Apache.

Hope this clears things up.

Thanks.

**Comment by abdullah1908** [comment]
@claudiulodro Thanks for your quick response but anti hot linking should be deploying by default instead of following hard & fast rules or implementations.

**Comment by abdullah1908** [comment]
This is very critical bug and I've reported it on HackerOne.
