### ISSUE TITLE
Edit Product Page No Longer Works Correctly

### ISSUE THREAD

**Issue by CDMAdministrator** [woocommerce/woocommerce#21631]
**Describe the bug**
We upgraded to WooCommerce 3.4.7 on the weekend.  Today when we are trying to update products the Product data section is not giving us the option to update any of the sections.  Clicking on the General, Inventory, Shipping, etc. links used to switch to different sections. Now these links are not doing anything. 

**To Reproduce**
1. Go to Product List.'
2. Click on any product'
3. Scroll down to product data'

**Screenshots**
![image](https://user-images.githubusercontent.com/44379408/47314854-e2576800-d610-11e8-9d2a-6188b3cc8e16.png)

**Expected behavior**
Click on the different links under Product Data should show different fields for editing product information..

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WordPress version
4.9.8
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
Nothing happens when the Get system report button is clicked.
</details>

**Comment by kloon** [comment]
Not able to reproduce http://cld.wthms.co/vsUIkn

Check the user role of the user you are logged in with, either administrator of shop manager roles need to be used.

Also test with all plugins except WooCommerce disabled and your theme switched to a default one like Storefront or Twentyseventeen, if that fixes the issues then enable the plugins one by one again and finally switch your theme back, testing in between to find the plugin or if the theme is causing your issues, chances are it is a permission issue and you need to change your user role, we did roll out a security fix to prevent roles that should not edit things to not be able to.

**Comment by CDMAdministrator** [comment]
This was corrected by restoring the database and files from a backup. We suspect that a plugin update did not complete correctly on the server and corrupted the code.
