### ISSUE TITLE
$array_key can be zero and IF condition fails

### ISSUE THREAD

**Issue by jamsheerkrd** [woocommerce/woocommerce#21640]
Refering line: https://github.com/woocommerce/woocommerce/blob/4ad0fbd5217e8fc7ecb454fbed049b6092b28464/includes/abstracts/abstract-wc-data.php#L448 
The `$array_key` can be `0` if the` $meta_id` is the first item in `$this->meta_data`. Then the logic fails here.
We are facing issues with our plugin due to this.

**Comment by kloon** [comment]
See #21641
