### ISSUE TITLE
get_transient_version ignores woocommerce_delete_version_transients_limit filter

### ISSUE THREAD

**Issue by glagonikas** [woocommerce/woocommerce#21644]
On https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L147 the function get_transient_version requests to delete the version transients but doesn't take into account any rules applied using the woocommerce_delete_version_transients_limit filter (https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L178)

On websites where the woocommerce_delete_version_transients_limit is set to 0, you'd immediatelly end up with loads of crons scheduled.

This would result in behaviour similar to the one described on #19890

**Comment by glagonikas** [comment]
@rodrigoprimo this is a follow up to your comment from https://github.com/woocommerce/woocommerce/issues/19890#issuecomment-432604813

**Comment by rodrigoprimo** [comment]
@glagonikas, for WC 3.6.0, I'm planning to make some changes to the versioned transients code that should address this and other issues we had with this system. There is a work in progress PR open if you would like to take a look: #21282. Closing this issue for now, but please leave a comment and I will reopen it if you believe the PR that I mentioned won't fix the problem you described here.
