### ISSUE TITLE
PayPal Product Metadata urlencoded

### ISSUE THREAD

**Issue by pascalknecht** [woocommerce/woocommerce#21643]
When creating a new order and paying via PayPal the line items will be urlencoded which is not nice for the customer.

1. Create an order with a lot of meta information
2. Pay via PayPal
3. See the order items with urlencoded text

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/8436238/47422995-4babb800-d784-11e8-898c-f678ee7218ab.png)

**Expected behavior**
Human readable text

I checked the logs and from the sender side everything seems to be ok (no encoding of the URL).

**Comment by kolyasapphire** [comment]
Seems related to #21463

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/21463
