### ISSUE TITLE
3.5.0 custom fields on the checkout page are not sorted by attribute data-priority

### ISSUE THREAD

**Issue by kolyadams** [woocommerce/woocommerce#21642]
![screen](https://user-images.githubusercontent.com/44404459/47421431-4604a100-d789-11e8-8372-af46c9bfee7e.png)

**Comment by DionGrendelman** [comment]
Same problem here, the data-priority has 0 effect.

**Comment by kloon** [comment]
See #21733

**Comment by DionGrendelman** [comment]
@kloon Is there already a fix for this, or am i seeing it over me head?

**Comment by kloon** [comment]
Yes there is, it is in the PR I linked to above.

**Comment by DionGrendelman** [comment]
@kloon Thanks for your response. Just tbh! I'm kinda new to this way of implementing a fix thruh github. Could you explain how? I tried to paste the $( '#billing_country' ).trigger( 'change' );, but without succes/

**Comment by kloon** [comment]
You are going the right route, but you will need to add it to the address-i18n.min.js file since that is what is usually served on production sites. Alternatively, you can just add `define( 'SCRIPT_DEBUG', true );` to your wp-config.php file and it will load the non-minified scripts instead.
