### ISSUE TITLE
post_author issues after WC 3.5 database update

### ISSUE THREAD

**Issue by rodrigoprimo** [woocommerce/woocommerce#21656]
**Describe the bug**
When working on the data migration routine on PR #17895 to improve the performance of the WC queries that filter orders by customer ID, I assumed that WC before 3.5 always set post_author to 1 (see https://github.com/woocommerce/woocommerce/issues/17087#issue-263398846) for every order. But @stianandreassen has brought to my attention (see their comments starting here https://github.com/woocommerce/woocommerce/pull/17895#issuecomment-432635912) that this assumption is wrong and that WC before 3.5 will set post_author to the current WP user ID when orders are created manually via wp-admin.

This has two different consequences depending on how the database update routine is triggered. This because the `wc_update_350_order_customer_id()` function uses two different strategies to migrate the customer ID from `_customer_user` postmeta to `post_author` depending on whether the process was started via the WP-CLI command or the wp-admin interface.

- If the process was started via the WP-CLI command, the data will be migrated successfully and WC will display the correct information about the customer, but the IDs of the WP users, usually shop managers, that manually created the orders (that was previously stored in the post_author field) will be lost. WC never used or exposed those IDs so, although we didn't anticipate that this would happen, I don't think we need to fix it (the only way I can see to fix this is to revert #17895 and keep using postmeta to store the customer ID).

- If the database update routine was started via the wp-admin interface, the [query that gets the IDs of the orders that need to be updated](https://github.com/woocommerce/woocommerce/blob/245e1768f9674391a2deb5b2b44943e515a8eb98/includes/wc-update-functions.php#L1905) ignores entries created manually via the wp-admin interface by users other than user ID 1. This means that after the 3.5 database update, the post_author field for the orders ignored by the query are not updated and remain with the ID of the user that manually created the order instead of the customer ID. As a result, for those orders, WooCommerce will display the wrong customer. Luckily, the correct information is still stored in the old `_customer_user` postmeta and probably the easiest solution is to write another update routine that will migrate the data for the orders that are displaying the wrong customer.

**To Reproduce**
1. Make sure you are running WC < 3.5 and that the database version is also < 3.5 (check the value of the options `woocommerce_version` and `woocommerce_db_version`).
2. Create a shop_manager and a customer user.
3. Login with the shop_manager user and manually create an order setting the customer of that order as the user named customer.
4. Check in the order page that "customer" is correctly identified as the customer of that order.
5. Update to WC 3.5.0 and run the database update routine via the wp-admin interface.
5. Reload the order page, and WC will show "shop_manager" as the customer of the order.

**Screenshots**
Screenshots provided by @stianandreassen

![woo_350_1](https://user-images.githubusercontent.com/77215/47453117-45c4cf80-d7a2-11e8-8dc8-8e44178968a4.png)

![woo_350_2](https://user-images.githubusercontent.com/77215/47453134-49f0ed00-d7a2-11e8-8f3d-49d720f54129.png)

**Expected behavior**
WC should display customer as the customer of the order instead of shop_manager.

**Comment by kloon** [comment]
I did some testing and it seems the issue is only with the upgrade routine. When I create a new order with 3.5 via wp-admin and assign the customer it stays as that customer. So for a fix if we can perhaps ship a new upgrade routine to fix the affected orders that would be great.

I assume we still have the _customer_user meta and can use that to compare and update where needed, might be a bit slower but a way to fix this.

**Comment by NickGreen** [comment]
Hello All, we have a situation where this appears to be affecting subscriptions created by Woo Subscriptions, which are a custom order type. Orders and subscriptions created before a certain date, regardless of `created_via` value, are showing the `post_author` as the customer. There are currently over 8,000 orders on this particular site which are showing up under the admin user. This is an increased scope from what was initially reported just being affected by orders created via admin area.

I see that the proposed fix is going to be limited to orders and those created via the admin area. We may need to come up with an additional fix on the Woo Subscriptions end, so any input about your fix here might be helpful.

With my testing, overwriting the `post_author` with the `_customer_user` manually solves the problem.  We could certainly come up with our own fix for this particular site, but if this becomes a widespread issue among all Subscriptions sites, a widespread data migration update may need to be considered that affects more than just orders created by admin.

**Comment by rodrigoprimo** [comment]
Hi @NickGreen, thanks for reaching out. There is another issue with this update routine that happens only when Subscriptions is active. Could you please take a look and see if that is the problem that you experienced?

https://github.com/woocommerce/woocommerce/issues/21687

Workaround to fix the problem: https://github.com/woocommerce/woocommerce/issues/21687#issuecomment-433429494

**Comment by rodrigoprimo** [comment]
See #21673
