### ISSUE TITLE
Data-priority not working

### ISSUE THREAD

**Issue by DionGrendelman** [woocommerce/woocommerce#21650]
**Describe the bug**
The priority for the billing is not working in any case.

**To Reproduce**
Try to change the prio with: 

add_filter("woocommerce_checkout_fields", "custom_override_checkout_fields", 1);
function custom_override_checkout_fields($fields) {
    $fields['billing']['billing_total_name']['priority'] = 1;
    $fields['billing']['billing_company']['priority'] = 3;
    $fields['billing']['billing_country']['priority'] = 4;
    $fields['billing']['billing_state']['priority'] = 5;
    $fields['billing']['billing_address_1']['priority'] = 6;
    $fields['billing']['billing_address_2']['priority'] = 7;
    $fields['billing']['billing_city']['priority'] = 8;
    $fields['billing']['billing_postcode']['priority'] = 9;
    $fields['billing']['billing_email']['priority'] = 1;
    $fields['billing']['billing_phone']['priority'] = 11;
    debug_to_console($fields);
    return $fields;
}

**Screenshots**

![afbeelding](https://user-images.githubusercontent.com/22094225/47439841-647c9380-d7ad-11e8-89a4-81e15505e459.png)

**WordPress Environment**
Newest

**Comment by claudiulodro** [comment]
Thanks for the report. This was previously reported in #21642, so I'm closing in favor of that issue.
