### ISSUE TITLE
Variations Titles Being Updated During Certain Actions

### ISSUE THREAD

**Issue by HowdyMcGee** [woocommerce/woocommerce#21651]
**Is your feature request related to a problem? Please describe.**
At different points all variations titles are being updated. Whenever you click the variations tab on a product the database updates variation post titles. Whenever you export products the database updates variation post titles.

**To Reproduce**
1. Create 4+ Attributes
2. Create a variation product with 1 variation with selected 4 attributes
3. Update variation post title ( via database or PHP )
4a. Reload edit product, click variation tab
4b. Export products
5. View database to see the updated title reverted to original state

**Describe the solution you'd like**
This seems like a large amount of overhead if a product has many variations. It also seems unnecessary since variations are not related by their post title.

Variation titles are unimportant except whenever they're exported. It seems like there's certain rules in place that if a product variation has less than 3 selected attributes those attributes display in the post title. Otherwise the variation post title ends up the exact same as the product title which whenever exporting makes for a very confusing CSV. One could certainly argue that IDs and SKUs circumvent this issue but visually it's easier for non-technical to manage variations when the selected variations are in the post title.

I believe that post titles should either be controlled by the developer or plugin or WooCommerce should include all selected variations into the variation post title. I do not believe that there's a need or point to update the variation post title whenever variations are loaded or exported. 

**Describe alternatives you've considered**
Maybe a hook during the export process to change or modify product titles.

**Comment by kloon** [comment]
Variation titles with attributes are useful for SEO purposes or when you link to a specific attribute via a product link. We have a limit which is controllable via the woocommerce_product_variation_title_include_attributes, the default is 2 attributes as not to cause performance issues, some users want this functionality, so if you do not then please use the filter and set it to false to disable it completely.
