### ISSUE TITLE
Manual order in Backend

### ISSUE THREAD

**Issue by Fit4home** [woocommerce/woocommerce#21666]
**Describe the bug**
Hi there!
I would like to create an order manually in the backend. I click on "Add product" and enter the first letters. Before the update came a long list of all available products and all variants of it. Now only a few products to choose from, sometimes completely without variation. For example, I have a product in 15 different flavors. Now comes, if at all, only the mother product to choose from. I have many products with many different variants. I need the old version of the "add product" option, please.

**To Reproduce**
1. Go to '...' Woocommerce - Order
2. Click on '....'Add new order
3. Scroll down to '....' add products

**Screenshots**

**Expected behavior**
After having entered the first letters, all corresponding products with the corresponding variants are displayed. This is necessary to be able to create correct orders with the correct variants. Just as it was always possible with Woocommerce.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by kloon** [comment]
Have you tried typing the variations value of the product you area searching as part of the search string? Ie if you have a product called shirt with different colours as variations you can type in shirt blue to bring up the blue shirt variation.

**Comment by Fit4home** [comment]
I have a lot of orders which contain a main product in 10 different variants. The customers who shop in my stationary shop, wait until I have created the bill with the purchased products. If I have to enter each of the 10 variants separately, it takes a lot longer to create the bill than already. 

So you simply entered the main product and all variants were displayed in a long list, klick – hold the ctrl button and klick every variation you need in one step - this makes working much easier and faster. Unfortunately, I can not see any improvement from these changes - for my use it is an absolute deterioration. Is it possible to make the step "Add Product" as it always was?

 

 

Von: Gerhard Potgieter <notifications@github.com> 
Gesendet: Donnerstag, 25. Oktober 2018 11:34
An: woocommerce/woocommerce <woocommerce@noreply.github.com>
Cc: Fit4home <office@fit4home.at>; Author <author@noreply.github.com>
Betreff: Re: [woocommerce/woocommerce] Manual order in Backend (#21666)

 

Have you tried typing the variations value of the product you area searching as part of the search string? Ie if you have a product called shirt with different colours as variations you can type in shirt blue to bring up the blue shirt variation.

**Comment by kloon** [comment]
Try using the filter woocommerce_json_search_limit to increase the number of results that get returned. You can achieve this by adding the code to your themes's functions.php file

```
// Increase the search limit to 50 results.
function wc_increase_json_search_limit( $limit ) {
    return 50;
}
add_filter( 'woocommerce_json_search_limit', 'wc_increase_json_search_limit' );
```

Unfortunately, that is all I can give you, make it return more results. Hopefully that helps with your issue.
