### ISSUE TITLE
Call to undefined method WC_Product_Simple::set_date_created_gmt()

### ISSUE THREAD

**Issue by 1000camels** [woocommerce/woocommerce#21660]
**Is your feature request related to a problem? Please describe.**
I have stumbled onto a missing method, as best as I can tell. It occurs on line 669 in 
woocommerce/includes/api/class-wc-rest-products-controller.php

I have extended the API and I am updating a product, including updating its dates. This error is only happening with my API, but I am pretty sure that the method WC_Product_Simple::set_date_created_gmt() does not exist.

**Describe the solution you'd like**
Mostly I do not want the error ;-)
I am not sure whether WC_Product_Simple needs that method of the call needs to be changed.

**Describe alternatives you've considered**
I am continuing to explore why this error is only encountered in my code, in order to bypass it.

**Additional context**
None

**Comment by kloon** [comment]
See #21675
