### ISSUE TITLE
"Resend new order notification" omits Shipping address when the Order is created manually

### ISSUE THREAD

**Issue by Luminus** [woocommerce/woocommerce#21665]
**The bug**
When you create an order manually in the WP-Admin, the "Resend new order notification" feature sends an email to the Admin containing the Billing Address but is missing the Shipping Address even though you entered both of them.

The experience is the same regardless of whether this is a new customer or a customer with an existing account. It is also the same whether you use the "copy billing address" link or you enter the Shipping Address manually.

**To Reproduce**
1. Go to **WooCommerce → Orders**
2. Click on **Add Order**
3. Fill out both the Billing and Shipping addresses and add 1 product to the order.
4. Click **Create**
5. In the **Order actions** meta box, select **Resend new order notification**
6. Check your email. The email will contain only a billing address and no shipping address

**Screenshots**

**Screenshot of the order showing that both addresses are filled in:**
![no-ship-order](https://user-images.githubusercontent.com/248077/47482789-7acb3380-d82f-11e8-9262-a567071de139.png)

**Screenshot showing that the email is missing the shipping address:**
![no-shipping](https://user-images.githubusercontent.com/248077/47482722-4a839500-d82f-11e8-9d21-8f734b5253dd.png)

**Expected behavior**
The notification email should contain both the billing and the shipping addresses

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by kloon** [comment]
Does not look like you have shipping on that order? Can you confirm if you get the same with an order that has shipping on it as well.

**Comment by Luminus** [comment]
Good catch @kloon.

Adding shipping to the order sorted it out.

**Added in shipping**
![now-shipping](https://user-images.githubusercontent.com/248077/47490649-1618d480-d841-11e8-8ec5-3b7a445c9362.png)

**Shiping Address now shows in Email**
![now-shipping-email](https://user-images.githubusercontent.com/248077/47490686-2c269500-d841-11e8-92a7-2d1082c3e2a8.png)

I'll go ahead and close this out.
