### ISSUE TITLE
Downloads Endpoint Creates /download slug for all pages

### ISSUE THREAD

**Issue by damiannep** [woocommerce/woocommerce#21677]
**Describe the bug**
In WooCommerce > Settings > Advanced in WP Admin,  when downloads is set as an endpoint to be used, if I add /downloads to the link for any page on the user’s site, it creates a dynamic page with the same content e.g. https://rocketroseart.com/about/downloads/ is the same page as https://rocketroseart.com/about but with the heading Downloads.

**To Reproduce**
1. Go to any page on a site with WooCommerce installed
2. Append /downloads to the URL

A page is dynamically created with all the content of the page in step 1 with the heading Downloads on the page.

**Images**
Screenshot showing https://rocketroseart.com/about: http://cld.wthms.co/bZammg
Screenshot showing https://rocketroseart.com/about/downloads: http://cld.wthms.co/mTrRJ1

**Expected behavior**
A page not found error should exist if there is no Downloads page created except for /my-account/downloads.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
@claudiulodro confirmed the issue on his local install

**Comment by lemacarl** [comment]
@damiannep @claudiulodro This appears to happen for all the query vars that are added as endpoints in `WC_Query`

**Comment by claudiulodro** [comment]
@lemacarl thanks for investigating and posting your findings here!

**Comment by mikejolley** [comment]
https://codex.wordpress.org/Rewrite_API/add_rewrite_endpoint does not allow appending endpoints to only certain pages - it's all or nothing.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22631
