### ISSUE TITLE
woocommerce_output_all_notices() problem in 3.5.0

### ISSUE THREAD

**Issue by andreiglingeanu** [woocommerce/woocommerce#21671]
**Is your feature request related to a problem? Please describe.**
The [`woocommerce_output_all_notices()`](https://github.com/woocommerce/woocommerce/blob/4ad0fbd5217e8fc7ecb454fbed049b6092b28464/includes/wc-template-functions.php#L3362) function (which was introduced in 3.5.0) has 2 problems:

1. It emits and empty div `.woocommerce-notices-wrapper` even when no notification is present
2. The output of this function is not filterable, which means I have to remove existing template hooks (~10 of them for now) & re-add them but with another helper -- this is very tedious and error prone.

**Describe the solution you'd like**

1. Check for notifications presence before `echo`ing `.woocommerce-notices-wrapper`
2. An easy filter for the output of this function, just like other Woo helpers have.

**Describe alternatives you've considered**
The alternative for now is to remove existing template hooks (~10 of them for now) & re-add them but with another user-defined helper -- this is very tedious and error prone.

I can submit a PR for this if it gets approved.

**Comment by claudiulodro** [comment]
Sounds reasonable. Happy to review a PR if you want to give it a shot. Thanks!

**Comment by kloon** [comment]
See #21682

**Comment by andreiglingeanu** [comment]
@kloon There's nothing in there - just the PR is closed :) Is that normal?

**Comment by kloon** [comment]
Sorry, just closing issues with open PR's. The fix for this issue is in that PR so it is being addressed, that is why I am closing the issue.

**Comment by andreiglingeanu** [comment]
Ah, sure.
