### ISSUE TITLE
No Customer Login API?

### ISSUE THREAD

**Issue by VasApps** [woocommerce/woocommerce#21683]
Hello there.

How can I allow WooCommerce customers to simply login. I see that the [CUSTOMER API ](http://woocommerce.github.io/woocommerce-rest-api-docs/?php#customers) allows for customer creation but no where do I see the ability to get a customer by email/username & password? Why? This makes no sense. How can there be an account create but no login? 

I'm building an iOS & Android application that syncs with WooCommerce stores and will need existing customers to be able to login and view their orders but it seems you guys provide no secure way to make this happen.

Others have suggested to grab the customer ID by the email but this is not secure because you could just get any ID from any email. I understand I could send out an e-mail verification but this would be an email sent by my domain and would confuse users who are trying to login into "Salleys Store" but are getting an email from me. Is there an API to send an e-mail on behalf of the authorized store?

Any suggestions? 

Some advice would go a long way.

Thanks!

**Comment by kloon** [comment]
There is no login/session/cart APIs as the API is meant to be used on a store level and not a customer level. It would be up to the app developer to implement session handling that takes care of this, there are endpoints to retrieve users and their details.

**Comment by SeyedAbdollahi** [comment]
It helped me to login

[https://stackoverflow.com/a/41423221/5950387](https://stackoverflow.com/a/41423221/5950387)
