### ISSUE TITLE
Strange Warning/Error: undefined variable 'Packaging' from class-wc-eval-math.php 

### ISSUE THREAD

**Issue by ravinsharma7** [woocommerce/woocommerce#21685]
**Describe the bug**
Strange error: Warning: undefined variable 'Packaging' in /home/user/webapps/apps-dev/wp-content/plugins/woocommerce/includes/libraries/class-wc-eval-math.php on line 321

**To Reproduce**
1. Install woocommerce
2. Select any product
3. Open devtools
4. See error in ajax.

**Screenshots**

**Expected behavior**
I expect this warning to not appear.

**Isolating the problem (mark completed items with an [x]):**
- [X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

Home URL: [CONFIDENTIAL]
Site URL: [CONFIDENTIAL]
WC Version: 3.5.0
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.34 (Unix) OpenSSL/1.0.2g
PHP Version: 7.1.19 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 256 MB
PHP Time Limit: 60
PHP Max Input Vars: 10000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.21-MariaDB-1~xenial
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.5
WC Database Prefix: xoxzo_
MaxMind GeoIP Database: ✔
Total Database Size: 8.54MB
Database Data Size: 7.45MB
Database Index Size: 1.09MB
xoxzo_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
xoxzo_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
xoxzo_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
xoxzo_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
xoxzo_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
xoxzo_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB
xoxzo_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
xoxzo_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
xoxzo_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
xoxzo_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
xoxzo_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
xoxzo_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
xoxzo_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
xoxzo_woocommerce_log: Data: 0.02MB + Index: 0.02MB
xoxzo_commentmeta: Data: 0.02MB + Index: 0.03MB
xoxzo_comments: Data: 0.06MB + Index: 0.09MB
xoxzo_duplicator_packages: Data: 0.02MB + Index: 0.02MB
xoxzo_failed_jobs: Data: 0.02MB + Index: 0.00MB
xoxzo_links: Data: 0.02MB + Index: 0.02MB
xoxzo_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
xoxzo_mail_bank: Data: 0.02MB + Index: 0.00MB
xoxzo_mail_bank_email_logs: Data: 5.23MB + Index: 0.00MB
xoxzo_mail_bank_meta: Data: 0.02MB + Index: 0.00MB
xoxzo_options: Data: 1.20MB + Index: 0.05MB
xoxzo_postmeta: Data: 0.19MB + Index: 0.22MB
xoxzo_posts: Data: 0.05MB + Index: 0.06MB
xoxzo_queue: Data: 0.02MB + Index: 0.00MB
xoxzo_termmeta: Data: 0.02MB + Index: 0.03MB
xoxzo_terms: Data: 0.02MB + Index: 0.03MB
xoxzo_term_relationships: Data: 0.02MB + Index: 0.02MB
xoxzo_term_taxonomy: Data: 0.02MB + Index: 0.03MB
xoxzo_usermeta: Data: 0.06MB + Index: 0.03MB
xoxzo_users: Data: 0.02MB + Index: 0.05MB
xoxzo_wc_download_log: Data: 0.02MB + Index: 0.03MB
xoxzo_wc_webhooks: Data: 0.02MB + Index: 0.02MB
xoxzo_woocommerce_xoxzo_error: Data: 0.02MB + Index: 0.00MB
xoxzo_woocommerce_xoxzo_status: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 3
customize_changeset: 2
page: 7
post: 2
product: 2
shop_order: 46
shop_order_refund: 13

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Settings ###

API Enabled: –
Force SSL: –
Currency: MYR (RM)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.3 – 2.3.5 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
</details>

**Comment by kloon** [comment]
I am not able to replicate this, are you sure you are not running any other plugins, WooCommerce should at least be in that list? Also I see your Storefront theme is a bit outdated, could you update that as well and test again?

**Comment by ravinsharma7** [comment]
Hi @kloon. 

I did what you mentioned. I upgraded the storefront theme. Make sure all the plugins are disabled except for woocommerce plugin. I even removed woocommerce and installed it back. I still have it appearing.

**Comment by ravinsharma7** [comment]
Found out the problem using a profiler.

Woocommerce does not  validate if a shipping cost value is numeric before using it. Something placed a non-numeric value ('Packaging') into the "Flat Rate Method" cost which caused the error. Changing it back to numbers solved the problem.

Case closed.

**Comment by kloon** [comment]
Thanks for the update, must be something that added it dynamically as we do not allow non-numeric inputs on the interface.
