### ISSUE TITLE
Extensions: WooCommerce.com Subscriptions: Tags rendered as text in sorry to see you go message on disconnecting from woocommerce.com

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce#21684]
**Describe the bug**

HTML strong tags rendered as text in sorry to see you go message on disconnecting from woocommerce.com

**To Reproduce**
1. Disconnect from woocommerce.com
2. See error

**Screenshots**

<img width="1016" alt="screen shot 2018-10-25 at 3 09 00 pm" src="https://user-images.githubusercontent.com/1595739/47533449-9b63af80-d868-11e8-8f68-a1366fd99637.png">

**Expected behavior**

Tags to be interpreted, not rendered as text.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WooCommerce 3.5.0 on WordPress 4.9.8

**Comment by kloon** [comment]
See #21690
