### ISSUE TITLE
Gallery Images/Featured Video Won't Refresh

### ISSUE THREAD

**Issue by lyndalogan** [woocommerce/woocommerce#21680]
When creating a product in my new WooCommerce store, the first image/video that is loaded is saved as expected (default no image, gallery images, linked video, etc). If I edit or delete the gallery images or featured video at any point after that, the original images are not changed or deleted. If I replace the original featured video link with a second featured video link, it will continue to link to the first one loaded with disregard to the updated link.

**To Reproduce**
1. Create a new product in WooCommerce with a video and/or gallery image.
2. Click on 'Save Draft'
3. Click on "Preview" or the "permalink" to see the product page live and verify images/video appear. Close preview when done.
4. Leave the Product detail page by clicking on "All Products." Return to the new product detail page you just created.
5. Edit or delete featured video and or gallery images.
6. Click on 'Save Draft'
7. Click on "Preview" or the "permalink" to see the product page live. Verify whether images/video has changed. (There is no change to the images or videos.)

**Expected behavior**
I expect that the gallery images and/or featured video will change upon saving the product information.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

Note: We have not had any issues with images/videos until adding WooCommerce a few days ago.

**WordPress Environment**
Custom Theme (developed by Workhorse)
```
Home URL: |   | http://www.colinshope.org
-- | -- | --
Site URL: |   | http://www.colinshope.org
WooCommerce version: |   | 3.5.0
Log directory writable: |   | /var/www/html/CH-WordPress/wp-content/uploads/wc-logs/
WordPress version: |   | 4.9.8
WordPress multisite: |   | –
WordPress memory limit: |   | 256 MB
WordPress debug mode: |   | –
WordPress cron: |   | –
Language: |   | en_US
External object cache: |   | –
```

**Comment by lyndalogan** [comment]
<img width="1097" alt="screen shot 2018-10-25 at 3 52 25 pm" src="https://user-images.githubusercontent.com/44481076/47529974-f00a2900-d86e-11e8-84c8-ae3afca2a2be.png">
<img width="903" alt="screen shot 2018-10-25 at 3 53 17 pm" src="https://user-images.githubusercontent.com/44481076/47529975-f00a2900-d86e-11e8-8b11-081dbf8ba642.png">

**Comment by corsonr** [comment]
Also, on some servers, it seems that creates an error 524. I couldn't replicate myself, but a couple customers reported this.

**Comment by kloon** [comment]
524 is Cloudflare related. @lyndalogan, when you change it, does it show correctly on the admin side? IE. is the issue only the frontend not updating? If so it could be related to caching, especially since @corsonr is reporting some users get a 524 error, it could be related to Cloudflare caching.

Could you also please attach your full system status report? I also presume you did test this with just WooCommerce active and a default theme like Twentyseventeen or Storefront?

**Comment by lyndalogan** [comment]
Yes, the problem is on the frontend. The images show correctly on the admin side.

I have tried clearing the cache to see if it changes the end result. Images still won't appear on the frontend correctly.

I am working on getting a dev environment set up by our host for more testing. Up until now, I have been working in production. Therefore, I am hesitant to change the theme until I have a safe environment to do so. We are currently running a custom theme developed by Workhorse and do not use Cloudflare.

Full Status Report:
`
### WordPress Environment ###

Home URL: http://www.colinshope.org
Site URL: http://www.colinshope.org
WC Version: 3.5.0
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.34 (Amazon) OpenSSL/1.0.2k-fips PHP/5.6.38
PHP Version: 5.6.38 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 12 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.53.1
NSS/3.28.4

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.61 - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 12 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ❌ Your server does not support the mbstring functions - this is required for better character encoding. Some fallbacks will be used instead for it.
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 54.62MB
Database Data Size: 38.93MB
Database Index Size: 15.69MB
wp_woocommerce_sessions: Data: 4.02MB + Index: 0.14MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_blc_filters: Data: 0.02MB + Index: 0.00MB
wp_blc_instances: Data: 0.13MB + Index: 0.05MB
wp_blc_links: Data: 1.48MB + Index: 0.19MB
wp_blc_synch: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
wp_gf_entry: Data: 1.52MB + Index: 0.17MB
wp_gf_entry_meta: Data: 1.52MB + Index: 3.55MB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB
wp_gf_form: Data: 0.02MB + Index: 0.00MB
wp_gf_form_meta: Data: 0.17MB + Index: 0.00MB
wp_gf_form_view: Data: 0.31MB + Index: 0.25MB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB
wp_icl_languages_translations: Data: 0.20MB + Index: 0.14MB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB
wp_icl_node: Data: 0.02MB + Index: 0.00MB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB
wp_icl_strings: Data: 0.02MB + Index: 0.03MB
wp_icl_string_positions: Data: 0.02MB + Index: 0.02MB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB
wp_icl_string_translations: Data: 0.02MB + Index: 0.02MB
wp_icl_translate: Data: 0.02MB + Index: 0.02MB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB
wp_icl_translations: Data: 0.02MB + Index: 0.06MB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB
wp_icl_translation_status: Data: 0.02MB + Index: 0.02MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 3.02MB + Index: 0.08MB
wp_postmeta: Data: 3.50MB + Index: 3.95MB
wp_posts: Data: 5.52MB + Index: 0.34MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_quiz_geo_code: Data: 0.16MB + Index: 0.00MB
wp_quiz_log: Data: 1.52MB + Index: 0.00MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.16MB + Index: 0.00MB
wp_rg_form_view: Data: 0.25MB + Index: 0.22MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 1.52MB + Index: 0.14MB
wp_rg_lead_detail: Data: 1.52MB + Index: 2.64MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.06MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_waterguardian_log: Data: 0.02MB + Index: 0.00MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedCommentLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 2.02MB + Index: 0.00MB
wp_wfBlocks: Data: 0.02MB + Index: 0.02MB
wp_wfBlocks7: Data: 0.02MB + Index: 0.05MB
wp_wfBlocksAdv: Data: 0.02MB + Index: 0.00MB
wp_wfConfig: Data: 1.23MB + Index: 0.00MB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_wfFileChanges: Data: 0.02MB + Index: 0.00MB
wp_wfFileMods: Data: 4.52MB + Index: 0.00MB
wp_wfHits: Data: 1.02MB + Index: 2.09MB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB
wp_wfIssues: Data: 0.02MB + Index: 0.06MB
wp_wfKnownFileList: Data: 1.52MB + Index: 0.00MB
wp_wfLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB
wp_wfLockedOut: Data: 0.02MB + Index: 0.00MB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_wfLogins: Data: 0.16MB + Index: 0.06MB
wp_wfNet404s: Data: 0.02MB + Index: 0.02MB
wp_wfNotifications: Data: 0.06MB + Index: 0.00MB
wp_wfPendingIssues: Data: 0.02MB + Index: 0.06MB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_wfScanners: Data: 0.02MB + Index: 0.00MB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wp_wfStatus: Data: 0.13MB + Index: 0.09MB
wp_wfThrottleLog: Data: 0.02MB + Index: 0.02MB
wp_wfTrafficRates: Data: 0.02MB + Index: 0.00MB
wp_wfVulnScanners: Data: 0.02MB + Index: 0.00MB
wp_wpdatacharts: Data: 0.02MB + Index: 0.00MB
wp_wpdatatables: Data: 0.02MB + Index: 0.00MB
wp_wpdatatables_columns: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.09MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

acf: 8
acf-field: 60
acf-field-group: 8
amn_mi-lite: 2
attachment: 502
customize_changeset: 1
event: 9
jetpack_migration: 2
nav_menu_item: 59
oembed_cache: 4
page: 67
post: 64
product: 9
product_variation: 5
revision: 919
story: 3
tablepress_table: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (19) ###

Gravity Forms: by rocketgenius – 2.3.6
ACF Content Analysis for Yoast SEO: by Thomas Kräftner
ViktorFroberg
marol87
pekz0r
angrycreative
Team Yoast – 2.1.0

Advanced Custom Fields: Date and Time Picker: by Per Soderlind – 2.1.5
Advanced Custom Fields: Options Page: by Elliot Condon – 2.1.0
Advanced Custom Fields: Repeater Field: by Elliot Condon – 2.1.0
Advanced Custom Fields: by Elliot Condon – 5.7.7
BackWPup Pro: by Inpsyde GmbH – 3.6.2
Broken Link Checker: by Janis Elsts
Vladimir Prelovac – 1.11.5

Check Email: by Chris Taylor – 0.5.5
Featured Video Plus: by Alexander Höreth – 2.3.3
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.2.0
Gravity Forms No CAPTCHA reCAPTCHA: by John Parks - Folkhack Studios – 1.0.7
Jetpack by WordPress.com: by Automattic – 6.6.1
Mailchimp for WooCommerce: by Mailchimp – 2.1.11 – Not tested with the active version of WooCommerce
Mailgun: by Mailgun – 1.6.1
Quick Page/Post Redirect Plugin: by anadnet – 5.1.8
Simple Custom Post Order: by Colorlib – 2.3.3
SKT Skill Bar: by SKT Themes – 1.5
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.4 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #581 - /shop/
Cart: #582 - /cart/
Checkout: #583 - /checkout/
My account: #584 - /my-account/
Terms and conditions: ❌ Page visibility should be public

### Theme ###

Name: Colin's Hope Theme
Version: 1.0
Author URL: http://www.workhorse-digital.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –
`

**Comment by claudiulodro** [comment]
Are you still encountering this issue @lyndalogan? I haven't been able to reproduce it in my testing.

**Comment by mikejolley** [comment]
This does sound related to caching; gallery images are stored in meta and are pulled using the same functions on frontend and backend. For this to not match, one would have to be viewing a cached version of the page. I was unable to replicate the same problem on localhost (running no cache).

To confirm it's caching you can do a quick test - add a unique string after the URL, e.g. `yoursite.com/product-url/?test=12345` That extra query string might bust the cache and show the updated results.

Anyhow, if it's not solved and you can help us reproduce this issue (without caching) please commend back and we'll take another look.

Thanks
