### ISSUE TITLE
3.5 data update failing, but setting DB version as though successful

### ISSUE THREAD

**Issue by rogercoathup** [woocommerce/woocommerce#21687]
**Describe the bug**
Data update for 3.5 generates an error updating the customer information 
However, update routine thinks it has completed successfully, and sets the DB version to 3.5
As a result customer for each order / subscription is not set correctly (all show the customer as user ID  1 in wp-admin)

**To Reproduce**
1. Run wp wc update from the CLI
2. Goto admin - all subs / orders now show user ID 1 as the customer for those orders / subscriptions

**Screenshots**
roger@woo3:/var/www/html/xxxx/public_html$ wp wc update
Calling update function: wc_update_350_order_customer_id
WordPress database error You are using safe update mode and you tried to update a table without a WHERE that uses a KEY column for query UPDATE sj_posts JOIN customers_map ON sj_posts.ID = customers_map.post_id SET sj_posts.post_author = customers_map.customer_id WHERE post_type IN ('shop_order', 'shop_subscription') made by include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner->process, WP_CLI\Runner->start, WP_CLI\Runner->_run_command_and_exit, WP_CLI\Runner->run_command, WP_CLI\Dispatcher\Subcommand->invoke, call_user_func, WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}, call_user_func, WC_CLI_Update_Command::update, wc_update_350_order_customer_id
Calling update function: wc_update_350_reviews_comment_type
Calling update function: wc_update_350_db_version
Success: 3 updates complete. Database version is 3.5.0

**Expected behavior**
Shouldn't report success when the update has failed!

**Isolating the problem (mark completed items with an [x]):**

**Comment by rogercoathup** [comment]
How do we force the update run again, as it now thinks the DB is at the correct version?

**Comment by kloon** [comment]
@rodrigoprimo interesting one, since you are busy fixing another bug relating to this.

**Comment by rogercoathup** [comment]
Let me know if you need more info -- initially, I thought our DB had safe mode enabled, but it isn't. I noticed the update routine turns on safe mode before making the call.

**Comment by rodrigoprimo** [comment]
@rogercoathup, I'm not able to reproduce this error so could you please share your system report status so that I can check if this is MySQL version dependent problem or something like that?

Anyway, as far as I can see, `SET sql_safe_updates=1` was included in this update routine by mistake so we should fix it. While I was working on this update routine (#17895), I did some explorations to see if it was necessary to disable it (so `SET sql_safe_updates=0` instead of `SET sql_safe_updates=1`) before running the update query. My conclusion was that it was not necessary to disable safe updates as this particular query uses a key column (`post_type`) in the `WHERE`. What I'm failing to see is why this error would happen in some installs and not in others.

Could you please share the output of the following query?

```
show indexes from wp_posts;
```

Could you also please try to rerun the update routine without the sql safe update mode? Ideally try this first on a staging or testing environment. To rerun the update routine:

- Edit [includes/wc-update-functions.php](https://github.com/woocommerce/woocommerce/blob/d1c90c5972b691d72c0c7a351d7ae8b96cc7c6e0/includes/wc-update-functions.php#L1886) and remove the line that sets sql_safe_update or change it to set it to zero.
- Run the following WP-CLI commands:

```
wp option update woocommerce_db_version 3.4.7
wp wc update
```

The first command will change the option that WC uses to know its database version and the second will make all WC 3.5 databases updates to run again.

**Comment by rogercoathup** [comment]
@rodrigoprimo -- 
Thanks for the feedback and comprehensive instructions.

Have emailed the status report (from our staging server) to your gmail address.  We are seeing the problem on our staging and production servers.

I'll modify wc-update-functions.php now and report back on that.

Results of the indexes query:
mysql> show indexes from sj_posts;
+----------+------------+------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table    | Non_unique | Key_name         | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+----------+------------+------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| sj_posts |          0 | PRIMARY          |            1 | ID          | A         |      241330 |     NULL | NULL   |      | BTREE      |         |               |
| sj_posts |          1 | type_status_date |            1 | post_type   | A         |          28 |     NULL | NULL   |      | BTREE      |         |               |
| sj_posts |          1 | type_status_date |            2 | post_status | A         |          68 |     NULL | NULL   |      | BTREE      |         |               |
| sj_posts |          1 | type_status_date |            3 | post_date   | A         |      225236 |     NULL | NULL   |      | BTREE      |         |               |
| sj_posts |          1 | type_status_date |            4 | ID          | A         |      241330 |     NULL | NULL   |      | BTREE      |         |               |
| sj_posts |          1 | post_parent      |            1 | post_parent | A         |       49224 |     NULL | NULL   |      | BTREE      |         |               |
| sj_posts |          1 | post_author      |            1 | post_author | A         |       34122 |     NULL | NULL   |      | BTREE      |         |               |
| sj_posts |          1 | post_name        |            1 | post_name   | A         |      176067 |      191 | NULL   |      | BTREE      |         |               |
+----------+------------+------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
8 rows in set (0.00 sec)

**Comment by rogercoathup** [comment]
Note: we went from 3.4.4 direct to 3.5; we didn't go from 3.4.7

**Comment by rogercoathup** [comment]
Can confirm that it works successfully if if the sql_safe_update line is removed from includes/wc-update-functions.php 

`roger@korchnoi:/var/www/html/nnnn.com/public_html$ wp wc update
Calling update function: wc_update_350_order_customer_id
Calling update function: wc_update_350_reviews_comment_type
Calling update function: wc_update_350_db_version
Success: 3 updates complete. Database version is 3.5.0`

And, the customer is set correctly on the subscriptions

**Comment by rogercoathup** [comment]
@rodrigoprimo -- good that you were able to replicate.

I think (from reading earlier) that with `sql_safe_updates` enabled, the MySql engine tries to make a guess about the impact of a specific query.  That might explain why it doesn't allow the query to proceed on larger databases, but did on smaller.

**Comment by stelladex** [comment]
Hi all
 
I’m really not technical, just the site owner, but we have two completely identical sites and one is much smaller than the other in terms of subscribers and how long it’s been running (Feb 18 start).
 
It has affected this site too in just the same way.

**Comment by rodrigoprimo** [comment]
See #21740
