### ISSUE TITLE
"Over to you." text in admin order confirmation email

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce#21698]
**Describe the bug**
In 3.5, admin order confirmation email shows "Over to you." text at the bottom. 

**Screenshots**
![](http://cld.wthms.co/fZBeji+)
Link to screenshot: http://cld.wthms.co/fZBeji

**Expected behavior**

To not have it 

Getting reports recently. Here's a few I've found:

https://wordpress.org/support/topic/3-5-0-weird-text-on-bottom-of-order-confirmation/
1517013-zen
1518073-zen

**Comment by claudiulodro** [comment]
That text is there on-purpose, but it doesn't seem to be popular. Let's go with something less slang-ey or remove it altogether.

**Comment by nishitlangaliya** [comment]
@claudiulodro , Do we need to completely remove it or required something else text there ?

**Comment by webdados** [comment]
Kill it with fire :-)

**Comment by webdados** [comment]
Not completely related, but we should really and seriously think in, once and for all, move the hardcoded email notifications texts to the settings... Copying stuff to the (child) theme is never the better solution, because of updates.

**Comment by corsonr** [comment]
I had a couple people complaining about this too. It doesn't add any value.

**Comment by leonwagner** [comment]
Get rid of this. It adds nothing and makes people stop and wonder what it could possibly mean.

**Comment by StefsterNYC** [comment]
We thought we were hacked. I don't know who's responsible for this but if there was no need for it then why was it added? You really gave us a scare.

**Comment by rwaynick** [comment]
In 1434356-hc user thought that the text was odd so they removed it in the code.

**Comment by claudiulodro** [comment]
Patch in https://github.com/woocommerce/woocommerce/pull/21709 for 3.5.1 releasing this week. We'll remove it since people hate it.

**Comment by claudiulodro** [comment]
Better customization of e-mail text is a feature that should be coming in 2019.

**Comment by razorfrog** [comment]
This is crazy, we thought we were hacked. Please remove this text.

**Comment by claudiulodro** [comment]
@razorfrog it was removed in WC 3.5.1

**Comment by yulumadavid** [comment]
We have 3.5.1 but still see the text, only the text did change after the update to:
"Thank you for shopping with us"
I would love to see this removed or find a hook to hide it.

**Comment by StefsterNYC** [comment]
@yulumadavid you could hook it to remove it like so. 

function hd_filter_edit_shop_order_views( $views ) { 
    // Unset the Mine option. 
    unset( $views['mine'] );
    return $views; 
}; 
add_filter( 'views_edit-shop_order', 'hd_filter_edit_shop_order_views' );

**Comment by claudiulodro** [comment]
Literally the only change was [removing the text](https://github.com/woocommerce/woocommerce/pull/21709/files). We haven't replaced it with different text or anything like that.

**Comment by yulumadavid** [comment]
I mixed two things up. There was a text in the mail to the website owner and there is a mail to the person who has ordered.

For now we have put the template in the Child folder and removed the text in the 'thank you for your order' template. I think this is de best solution for now.

Thanx for you answers!
