### ISSUE TITLE
With Gallery Slider off, Variable Images are small thumbnails

### ISSUE THREAD

**Issue by kadencethemes** [woocommerce/woocommerce#21699]
**Describe the bug**
If you use the filter "woocommerce_single_product_flexslider_enabled" to turn off the slider or theme support is not on for "wc-product-gallery-slider" then variable product images are small thumbnails.

**To Reproduce**
1. Using Storefront theme add an empty child theme and set the "woocommerce_single_product_flexslider_enabled" filter to false.
2. Navigate to a variable product with images assigned to variations.
3. Select a variation and view the main product image.

**Expected behavior**
The image should be the size of the main product image, not the thumbnails.

Thanks for looking into this!

**Comment by claudiulodro** [comment]
I believe this was fixed in #21655. Let us know if it's still happening on recent versions of WooCommerce, and we'll reinvestigate.
