### ISSUE TITLE
Extensions: Add hooks for connection, subscription changes

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce#21701]
**Is your feature request related to a problem? Please describe.**

Code that depends on knowing when the user has connected to (or disconnected from) WooCommerce.com right now has to monitor an options hook.

Similarly, when a given product subscription is activated (or deactivated) on a site, it would be good to have hookable actions for that as well.

**Describe the solution you'd like**

Hookable actions for connecting, disconnecting, activating and deactivating in WC_Helper.

**Describe alternatives you've considered**

I am presently using an options hook for `update_option_woocommerce_helper_data` to monitor changes to the connection status. It tightly couples my code to the internal structure of that option, which makes me nervous. Hooks would be less tightly coupled.

**Comment by mikejolley** [comment]
Going through the code there are some hooks already perhaps overlooked:

```
woocommerce_helper_connected
woocommerce_helper_disconnected
```

Those cover the connection and disconnection events from woo.com.

Looks like we just need to add some extra ones for the product subscriptions.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23041 - please comment there if you require further changes.
