### ISSUE TITLE
Fatal error: Uncaught WC_Data_Exception: Please provide a valid email address.

### ISSUE THREAD

**Issue by nishitlangaliya** [woocommerce/woocommerce#21712]
**Describe the bug**
With multisite. When I tries to update account details I am getting below error.
`( ! ) Fatal error: Uncaught WC_Data_Exception: Please provide a valid email address. in /app/public/wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-data-store.php on line 109
--`
`( ! ) WC_Data_Exception: Please provide a valid email address. in /app/public/wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-data-store.php on line 109
--`

**To Reproduce**
1. Go to subsite from multisite and go to my my-account page.
2. Click on  account details
3. See error

**Screenshots**

https://www.useloom.com/share/0d1acc338a714e5ea12ac7dc18b0660b

**Expected behavior**
It should work fine same as with single site works. with proper message without error

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: http://wc35.local/m2
Site URL: http://wc35.local/m2
WC Version: 3.5.0
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.10.1
PHP Version: 7.2.0
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.0
WC Database Prefix: wp_3_
MaxMind GeoIP Database: ✔
Total Database Size: 1.54MB
Database Data Size: 0.87MB
Database Index Size: 0.67MB
wp_3_woocommerce_sessions: ❌ Table does not exist
wp_3_woocommerce_api_keys: ❌ Table does not exist
wp_3_woocommerce_attribute_taxonomies: ❌ Table does not exist
wp_3_woocommerce_downloadable_product_permissions: ❌ Table does not exist
wp_3_woocommerce_order_items: ❌ Table does not exist
wp_3_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_3_woocommerce_tax_rates: ❌ Table does not exist
wp_3_woocommerce_tax_rate_locations: ❌ Table does not exist
wp_3_woocommerce_shipping_zones: ❌ Table does not exist
wp_3_woocommerce_shipping_zone_locations: ❌ Table does not exist
wp_3_woocommerce_shipping_zone_methods: ❌ Table does not exist
wp_3_woocommerce_payment_tokens: ❌ Table does not exist
wp_3_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_3_woocommerce_log: ❌ Table does not exist
wp_3_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_3_comments: Data: 0.02MB + Index: 0.08MB
wp_3_links: Data: 0.02MB + Index: 0.02MB
wp_3_options: Data: 0.45MB + Index: 0.02MB
wp_3_postmeta: Data: 0.02MB + Index: 0.03MB
wp_3_posts: Data: 0.02MB + Index: 0.06MB
wp_3_termmeta: Data: 0.02MB + Index: 0.03MB
wp_3_terms: Data: 0.02MB + Index: 0.03MB
wp_3_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_3_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_blogs: Data: 0.02MB + Index: 0.03MB
wp_blog_versions: Data: 0.02MB + Index: 0.02MB
wp_registration_log: Data: 0.02MB + Index: 0.02MB
wp_signups: Data: 0.02MB + Index: 0.06MB
wp_site: Data: 0.02MB + Index: 0.02MB
wp_sitemeta: Data: 0.06MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

page: 5
post: 3
product: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.5.0-rc.1 – 3.5.0 is available

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #3 - /shop/
Cart: #4 - /cart/
Checkout: #5 - /checkout/
My account: #6 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by rodrigoprimo** [comment]
I was not able to reproduce this error. I tried both on the main site of a multisite install and on a secondary site. In both cases, I'm able to successfully update user details.

Checking the stack trace extracted from the video you created (see below), one thing caught my attention. For some reason, in your install, `WC_Customer->save()` is calling `WC_Data_Store->create()` and it should be calling `WC_Data_Store->update()` instead as you are updating an existing user. I guess that for some reason, `WC_Customer` constructor is not returning the object for the user that you are editing when it is called in the line below:

https://github.com/woocommerce/woocommerce/blob/897af8d20ef24e58164376ef65d980d2759f5956/includes/class-wc-form-handler.php#L292

Would you be able to debug the method `WC_Form_Handler::save_account_details()` to see if you figure out if that is indeed happening and, if so, why? Thanks.

![screenshot from 2018-10-30 14-05-25](https://user-images.githubusercontent.com/77215/47736578-b873f600-dc4d-11e8-89ba-c6b315aeece1.png)

**Comment by nishitlangaliya** [comment]
@rodrigoprimo,

Thanks for review issue. Sure I will debug as per your suggestion and provide my findings here.  Currently closing this issue. If it will require to reopen I will do for the same.

**Comment by rodrigoprimo** [comment]
@nishitlangaliya see #21712. I believe the step we were missing to reproduce the issue is that the fatal error will happen on a site other than the one that the user originally registered on.

**Comment by n00145964** [comment]
Hi Guys. 

I was getting this error also after I cloned my domain and installed it on the localhost, I disabled the plugin and this worked for me. Must need to setup again, as it took my test dummy email address, and it didn't like it, line 875..

Thanks.
