### ISSUE TITLE
PayPal API Signature field is not secure on display.

### ISSUE THREAD

**Issue by angelleye** [woocommerce/woocommerce#21714]
In the PayPal standard gateway configuration there is a section to add your API credentials, which includes a username, password, and signature.  

The signature is a sensitive value, and should not be displayed on screen, much like a password.  However, it is currently set to text, so it's displaying the value when you type/paste it in:

![image](https://user-images.githubusercontent.com/629241/47603258-6dd54e00-d9af-11e8-9502-76588793ed72.png)

This needs to be adjusted so that it's set to field type "password" the same as the actual password field.

**Comment by claudiulodro** [comment]
Fixed in #21715
