### ISSUE TITLE
"Orders" page in WooCommerce (edit.php?post_type=shop_order) very slow

### ISSUE THREAD

**Issue by thistehneisen** [woocommerce/woocommerce#21717]
**Describe the bug**
Currently I have tried pretty much everything on my mind, including:

1. Optimizing, repairing all of the database tables
2. Disabling all of the plugins, except WooCommerce
3. Due to only thing seen in Network debugger was admin-ajax.php request via XHR - disabled Heartbeat.
4. Clearing all WooCommerce caches, including sessions
5. Switching between Apache FastCGI, FPM and nginx - pretty much the same result.
6. Removing existing plugins/woocommerce/ and git cloning a fresh one into it. (By the way, if the version is 3.5.0-rc1, WordPress asks to update to 3.5.0, seems not right)

Still, the load time is six minutes to partially load the orders page (not all orders are being displayed, neither the pagination on bottom is loaded).
Screenshot of the Network: https://www.nils.digital/orders.png

Currently the PHP is set to 30G memory_limit, so it has to be a strong memory leak.

Please, inform me of any further details required to resolve this issue.

Request to the page:
```
Request URL: https://*.com/wp-admin/edit.php?post_type=shop_order
Referrer Policy: strict-origin-when-cross-origin
Provisional headers are shown
Referer: https://*.com/wp-admin/options-general.php?page=heartbeat_control_settings
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
X-DevTools-Emulate-Network-Conditions-Client-Id: 0F9469D317A73A557D0E787D1249A9FF
post_type: shop_order
```

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
WC Version: 3.5.0
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 30 GB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.13.8
PHP Version: 7.2.11
PHP Post Max Size: 1 GB
PHP Time Limit: 360
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.0h

SUHOSIN Installed: –
MySQL Version: 5.7.24-0ubuntu0.18.04.1
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.0
WC Database Prefix: 1aC6THc9do_
MaxMind GeoIP Database: ✔
Total Database Size: 8.46MB
Database Data Size: 7.33MB
Database Index Size: 1.13MB
1aC6THc9do_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB
1aC6THc9do_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
1aC6THc9do_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_woocommerce_order_items: Data: 0.02MB + Index: 0.01MB
1aC6THc9do_woocommerce_order_itemmeta: Data: 0.26MB + Index: 0.09MB
1aC6THc9do_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_woocommerce_log: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_commentmeta: Data: 0.05MB + Index: 0.02MB
1aC6THc9do_comments: Data: 0.19MB + Index: 0.09MB
1aC6THc9do_failed_jobs: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_links: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_mailchimp_carts: Data: 0.09MB + Index: 0.00MB
1aC6THc9do_options: Data: 1.62MB + Index: 0.14MB
1aC6THc9do_postmeta: Data: 3.43MB + Index: 0.58MB
1aC6THc9do_posts: Data: 0.84MB + Index: 0.10MB
1aC6THc9do_pps_countries: Data: 0.01MB + Index: 0.00MB
1aC6THc9do_pps_modules: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_pps_modules_type: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_pps_popup: Data: 0.60MB + Index: 0.00MB
1aC6THc9do_pps_popup_show_categories: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_pps_popup_show_pages: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_pps_statistics: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_pps_subscribers: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_pps_usage_stat: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_queue: Data: 0.02MB + Index: 0.00MB
1aC6THc9do_revslider_css: Data: 0.09MB + Index: 0.00MB
1aC6THc9do_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_revslider_navigations: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_revslider_sliders: Data: 0.01MB + Index: 0.00MB
1aC6THc9do_revslider_slides: Data: 0.02MB + Index: 0.00MB
1aC6THc9do_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_smush_dir_images: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_termmeta: Data: 0.01MB + Index: 0.02MB
1aC6THc9do_terms: Data: 0.01MB + Index: 0.02MB
1aC6THc9do_term_relationships: Data: 0.01MB + Index: 0.01MB
1aC6THc9do_term_taxonomy: Data: 0.01MB + Index: 0.01MB
1aC6THc9do_usermeta: Data: 0.03MB + Index: 0.02MB
1aC6THc9do_users: Data: 0.00MB + Index: 0.01MB
1aC6THc9do_wc_download_log: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_wc_webhooks: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_wooup_offers: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_wooup_stats: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_wooup_view_stats: Data: 0.00MB + Index: 0.00MB
1aC6THc9do_wsf: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 393
custom_css: 1
customize_changeset: 1
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 26
oembed_cache: 1
page: 19
post: 3
product: 34
product_variation: 53
revision: 66
scheduled-action: 6
shop_coupon: 7
shop_order: 175
shop_order_refund: 3
woo_discount: 1
wpautoterms_page: 1
wpcf7_contact_form: 1
ywar_reviews: 19

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

AfterShip - WooCommerce Tracking: by AfterShip – 1.9.2 – Not tested with the active version of WooCommerce
ARG Multistep Checkout for WooCommerce: by ARG Themes – 3.6 – Not tested with the active version of WooCommerce
Beeketing For WooCommerce: by Beeketing – 3.7.14 – Not tested with the active version of WooCommerce
Cardinity Payment Gateway: by Cardinity – 1.3.0 – Not tested with the active version of WooCommerce
Checkout Countdown for WooCommerce: by Extra Woo
Morgan Hvidt – 2.2 – Not tested with the active version of WooCommerce

Contact Form 7: by Takayuki Miyoshi – 5.0.4
Divi Booster: by Dan Mossop – 2.7.9
PayPal Express Checkout for WooCommerce: by wpgateways – 3.0.3 – Not tested with the active version of WooCommerce
Gutenberg: by Gutenberg Team – 4.1.1
Heartbeat Control: by Jeff Matson – 1.2.5
PixelYourSite: by PixelYourSite – 5.3.2 – Not tested with the active version of WooCommerce
Slider Revolution: by ThemePunch – 5.4.5
Woo Discount Rules: by Flycart Technologies LLP – 1.6.18 – Not tested with the active version of WooCommerce
Advanced Order Export For WooCommerce: by AlgolPlus – 2.0.0
WooCommerce Photo Reviews: by VillaTheme – 1.0.9.9 – Not tested with the active version of WooCommerce
WooCommerce Currency Switcher: by realmag777 – 2.2.5.1 – Not tested with the active version of WooCommerce
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.2.3
WooCommerce Shipping Tracking: by Lagudi Domenico – 15.3 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.5.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: #6916 - /terms-and-conditions/

### Theme ###

Name: Divi Child
Version: 1.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.15
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: Divi-child/woocommerce/cart/cart-shipping.php version 3.2.0 is out of date. The core version is 3.5.0
Divi-child/woocommerce/cart/cart-totals.php
Divi-child/woocommerce/cart/cart.php version 3.4.0 is out of date. The core version is 3.5.0
Divi-child/woocommerce/cart/mini-cart.php version 3.3.0 is out of date. The core version is 3.5.0
Divi-child/woocommerce/cart/proceed-to-checkout-button.php
Divi-child/woocommerce/checkout/form-billing.php
Divi-child/woocommerce/checkout/form-checkout.php version 2.3.0 is out of date. The core version is 3.5.0
Divi-child/woocommerce/checkout/review-order.php
Divi-child/woocommerce/myaccount/form-login.php version 3.4.0 is out of date. The core version is 3.5.0
Divi-child/woocommerce/single-product/add-to-cart/grouped.php
Divi-child/woocommerce/single-product/price.php

Outdated Templates: ❌
					
					
						Learn how to update
```
</details>

**Comment by rodrigoprimo** [comment]
6 minutes to load the orders pages, especially for a store with a relatively small number of orders is not normal and not expected as well. It is unlikely that WooCommerce core alone is causing this. Would you be able to install [query-monitor](https://wordpress.org/plugins/query-monitor/) or any other tool that would tell you where the server is spending time? I'd be curious to know the page generation time, peak memory usage and database query time. If it is spending a significant amount of time running queries, which are the slowest queries?

**Comment by rodrigoprimo** [comment]
Thanks for the heads up regarding the WC version in the master branch. PR #21755 should fix it.

**Comment by MattMski** [comment]
Having a similar issue on my main shop page, had to downgrade to 3.4.7 and it's fine

**Comment by thistehneisen** [comment]
I'm not sure that Query Monitor functions properly, [as it doesn't load fully together with the Orders page](https://www.nils.digital/wc_qm.png). From what it did retrieve, [this is the only slow query that appeared](https://www.nils.digital/wc_query.png). Not sure that is related to the Orders page entirely, but might give a hint.

```
SELECT SUM( meta__order_total.meta_value) as total_sales,SUM( meta__order_shipping.meta_value) as total_shipping,SUM( meta__order_tax.meta_value) as total_tax,SUM( meta__order_shipping_tax.meta_value) as total_shipping_tax, posts.post_date as post_date
FROM 1aC6THc9do_posts AS posts
INNER JOIN 1aC6THc9do_postmeta AS meta__order_total
ON ( posts.ID = meta__order_total.post_id
AND meta__order_total.meta_key = '_order_total' )
INNER JOIN 1aC6THc9do_postmeta AS meta__order_shipping
ON ( posts.ID = meta__order_shipping.post_id
AND meta__order_shipping.meta_key = '_order_shipping' )
INNER JOIN 1aC6THc9do_postmeta AS meta__order_tax
ON ( posts.ID = meta__order_tax.post_id
AND meta__order_tax.meta_key = '_order_tax' )
INNER JOIN 1aC6THc9do_postmeta AS meta__order_shipping_tax
ON ( posts.ID = meta__order_shipping_tax.post_id
AND meta__order_shipping_tax.meta_key = '_order_shipping_tax' ) 
WHERE posts.post_type IN ( 'shop_order' ) 
AND posts.post_status IN ( 'wc-completed','wc-processing','wc-on-hold','wc-refunded') 
AND posts.post_date >= '2018-10-01 00:00:00' 
AND posts.post_date < '2018-11-01 01:34:24' 
GROUP BY YEAR(posts.post_date), MONTH(posts.post_date), DAY(posts.post_date)
ORDER BY post_date ASC
```

Regarding the suggestion of @MattMski — downgrade to 3.4.7 didn't solve the issue.

**Comment by kloon** [comment]
The system status report is showing 19 active plugins and you checked that you tested it with all plugins except WooCommerce disabled and also with your theme switched to a default one. Can you please confirm you did, in fact, test it with all plugins except WooCommerce disabled and also using a default theme?

A plugin, your theme or some custom code could be trying to add information to one of the fields being displayed and doing it inefficiently which might cause the slowdown.

We have this version of WooCommerce running on WooCommerce.com and the orders page loads normal as it did prior to the upload, no where near 6 minutes, more like a couple of seconds.

**Comment by thistehneisen** [comment]
I did de-activate the plugins first time, don't remember whether I changed the themes, so I did it again now. The difference now is that it almost immediately outputs 502 Bad Gateway.

From the server log perspective, this is what it tells me:
```
2018-10-31 16:19:18 | Error | 213.226.*.* | 502 | GET /wp-admin/edit.php?post_type=shop_order HTTP/2.0 |   |   | 568 | nginx SSL/TLS access
-- | -- | -- | -- | -- | -- | -- | -- | --
2018-10-31 16:19:18 | Error | 213.226.*.* |   | 15439#0: *7257472 recv() failed (104: Connection reset by peer) while reading response header from upstream
```

Inform me if any additional information is required.

**Comment by rodrigoprimo** [comment]
> I'm not sure that Query Monitor functions properly

Under normal circumstances, Query Monitor shouldn't break your site.

> Not sure that is related to the Orders page entirely, but might give a hint.

How long did this query take to run?

> The difference now is that it almost immediately outputs 502 Bad Gateway.

Anything on the PHP error log?

So far it seems to me that there is a problem that is specific to your install and, if that is the case, there is not much we can do to help as this is not a support forum.

**Comment by thistehneisen** [comment]
Query Monitor doesn't break the site, it just doesn't function on the Orders page, as due to the error we're trying to solve here — the page isn't loading fully (thus, neither Query Monitor loads fully).

PHP Error log is above for the 502 erorr.

**Comment by mikejolley** [comment]
@thistehneisen https://github.com/woocommerce/woocommerce/issues/21717#issuecomment-434705341 looks to be the server access log rather than the server error log. If query monitor is failing it's almost certainly an error or an infinite loop somewhere.

I'd suggest the following if diagnosing this yourself:
- Again, disabling plugins to make this easier to diagnose
- Finding the PHP error log and looking in there for listed errors
- enabling the WP debug log, and checking that file after the orders page fails to load https://codex.wordpress.org/WP_DEBUG

Without being able to replicate this issue I can only put it down to a conflict, and/or some corrupted data in one of the displayed orders. Hopefully the PHP error log proves more useful.

If you need more help, consider either posting to the help desk (support ticket) or hiring someone to debug this for you--without access to the store we can only guess and/or point to the logs at this time, and we cannot gain access via GitHub.

If you can narrow down the cause or provide steps to reproduce this on another install, I'll reopen this issue and provide a fix. Please note comments remain open if you have any further comments or clues to share.

Thanks!
