### ISSUE TITLE
URL and breadcrumbs not consistent with multiple categories

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/woocommerce#21716]
**Describe the bug**

When assigning multiple categories to a product, I'd expect the breadcrumbs and the URL slugs to have the same structure. This is not the case. 

**To Reproduce**

1. Add several categories to a product
2. Review the product - the URL and breadcrumbs do not always have the same structure

(I say not always, because it still sometimes happens by accident.)

**Screenshots**

![http://cld.wthms.co/Iwppps](http://cld.wthms.co/Iwppps+)
Link to image here: http://cld.wthms.co/Iwppps.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

@mdmoore  was also able to reproduce

**Comment by rrennick** [comment]
> I'd expect the breadcrumbs and the URL slugs to have the same structure. 

This is not how the WordPress rewrite system works for taxonomies. Create a post and add multiple categories then look at the URL on the front end of the site.
