### ISSUE TITLE
extract argument pollution in wc_get_template

### ISSUE THREAD

**Issue by kimhf** [woocommerce/woocommerce#21721]
**Describe the bug**
When wc_get_template is used to get single-product/review.php it has a argument names 'args'.
This results in extract in wc_get_template() is overwriting $args, and a number of actions and filters receives the wrong args.

$args in templates are inconsistently referring to either the wc_get_template $args or the extracted args as with single-product/review.php.

**To Reproduce**
1. Use the wc_get_template filter
2. Try to access the $args when filtering the single-product/review.php template
3. $args has at this point been polluted and is now the comment args.

**Expected behavior**
The filters and actions in wc_get_template should always return the unpolluted arguments.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
N/A

**Comment by kloon** [comment]
See #21722 for fix
