### ISSUE TITLE
Option to calculate coupon discounts sequentially has no effect (v3.5.0)

### ISSUE THREAD

**Issue by alendev** [woocommerce/woocommerce#21720]
**Describe the bug**
Even when the option "Calculate coupon discounts sequentially" is checked, it's still calculating each coupon based on original product prices.

**To Reproduce**
1. Go to 'Woocommerce->Settings'
2. Click on 'Calculate coupon discounts sequentially' to enable it
3. Save settings changes.
4. Apply first -500$ discount to order, then apply second -30% discount.
5. If an initial order net price is ex. 1200$, apply first discount of -500$ will leave it as 700$ net total (so far so good). Apply second discount of -30%, will calculate -30% from initial 1200$ (not from 700$ as it should like as we enabled "Calculate coupon discounts sequentially").

**Expected behavior**
Should change the coupon calculation logic to apply coupons in sequence on top of one another, rather than basing them on the original product prices.

**Comment by kloon** [comment]
I am not able to reproduce this, see my tests http://cld.wthms.co/97fmlf with two coupons, a 20% off and a 10% off.

In my tests the total is 18 without discounts, then I apply the 10% which is 1.80 off, then I apply the 20% which is then 3.24 which is correct as that is ((18-1.8)/100)*20 which is equal to 3.24.

**Comment by alendev** [comment]
Regarding the environment, everything except Woocommerce (3.5.0) is disabled. Theme is Twentyseventeen. Sending you some screenshots to clarify further.

**Initial order:**
https://snag.gy/MQsIVe.jpg

**Applying 500 EUR coupon:**
https://snag.gy/OJTLXB.jpg

**Applying 30% coupon:**
https://snag.gy/HLTozX.jpg

Both coupons are applied to the initial net price (1.582,90 EUR), instead of a sequential order.

1.582,90 EUR - 500 EUR = 1.082,90 EUR
1.582,90 EUR * 0.3 (30%) = 474,87 EUR

Expected result should be (based on my understanding):

1.582,90 EUR - 500 EUR = 1.082,90 EUR
1.082,90 EUR * 0.3 (30%) = 324,87 EUR

This behavior would be fine if the option "_Calculate coupon discounts sequentially_" where not enabled.

The order from the screenshot is manually created over the Admin Panel, but I get the same behavior when creating it over the REST API (v3).

**Comment by rrennick** [comment]
The sequential calculation only applies to multiple percentage coupons. 

If one is a fixed amount & the second is a percentage then do the calculation where the percentage is applied first then the fixed discount.

**Comment by alendev** [comment]
@rrennick 
How should this behavior be treated in this case - Bug? 

After seeing and checking the option to calculate coupon discounts sequentially, I expected and relied on it, therefore I would classify it as a bug. In the end, it didn't do what it said it would. 

Overall, this sounds like a minor change, right?

**Comment by rrennick** [comment]
If the percentage discount is added by the customer first & the fixed second then the calculation is as I described. The change you are describing would result in having a different discount total depending on the order the coupons were added to the cart.

**Comment by alendev** [comment]
> The change you are describing would result in having a different discount total depending on the order the coupons were added to the cart.

That's correct, this is what I was hoping to achieve with the option `calculate discounts sequentially` enabled.

Maybe it's just me, so if it's working as you expected let's close the ticket.

**Comment by kloon** [comment]
As @rrennick says, if you have mixed type coupons it will cause different discounts depending on the order the customer applies the coupons. The option unfortunately only applies to percentage based coupons and not a mixture of the two because of that exact reason.

**Comment by MauriceW2** [comment]
Can someone please tell me what the status on this one is?

I use WooCommerce v3.5.3 and I have two percentage based coupons.

When both are applied,  I encounter the same bug that the coupons are **not** processed sequentially, but both are based on the initial amount.

**Comment by alendev** [comment]
You unfortunately need to implement your own solution, or programmatically calculate the discount yourself, and apply it as a fix-cost discount.

**Comment by KVNHNF** [comment]
having the same issue here, that's annoying (sequentially calculated coupon option enabled)

If initial price is $1,000 and you give two coupon A before a fixed amount discount and B being a % discount, then depending on how coupons are redeemed in the cart, the total will be different: 

$1,000 - 10% = $900 - $150 = $750 (User first redeeming coupon B then coupon A)
$1,000 - $150 = $750 - 10% = $675 (User first redeeming coupon A then coupon B)

What would be the best way to fix this?

**Comment by kloon** [comment]
I am reopening this issue so we can take another look at the reported scenarios.

**Comment by alendev** [comment]
The option "sequentially calculation of coupons" does what it should do - applies coupons in user specific order, what would result in having different totals depending on the order (in case of fix + percentage discounts). The initial Bug was that fixed discounts were always calculated first, followed by percentage discounts.

@KVNHNF therefore, what you are reporting is expected behaviour. Disable the option to get same totals regardless of order.

**Comment by claudiosanches** [comment]
I just checked that "Fixed cart discount" doesn't take "sequentially calculation of coupons" in account, but works just fine "Fixed product discount" with "Percentage discount", because "Percentage discount" also take in account products instead of the sum of all products in the cart.
So it's the expected behavior.

**Comment by alendev** [comment]
@claudiosanches have you checked the order? Which discount is applied first? 

1000$ cart total - 500$ first discount - 50% second discount, should be a total of 250$

Issue was/is that it applies the 50% first (regardless of user input/order), which ends up to 0$.
