### ISSUE TITLE
Downloadable file link available before buying

### ISSUE THREAD

**Issue by PidgeyBE** [woocommerce/woocommerce#21732]
Hi all!

I'm investigated if I can use woocommerce API as backend for a webstore I'm trying to make (integrated into other software).
I'm using the latest wordpress with latest Woocommerce + Dokan multivendor plugin installed.
I'm using JWT Authentication plugin to get access to the API.

The store I'm trying to build will contain downloadable items only. However I face a few issues with the way permissions are handled in the Woocommerce API: 

* First of all any logged in user can view all products in the store via the `/wp-json/wc/v3/products` endpoint. Even if the product is labeled "private" via the wordpress UI.
* Secondly this same endpoint (`/wp-json/wc/v3/products`) simply shows the original link of the downloadable files (via the `downloads` key) BEFORE the product is bought. So a customer doesn't need to buy a product to see the original download link.
* Thirdly, there is an endpoint `wp-json/wc/v3/customers/<user-id>/downloads` to get the "real" download URLs, which hide the public external link to the file. The problem is, this endpoint is only viewable by the administrator of the Wordpress install. If a normal customer tries to access it, he'll get a "403". So how to retrieve the download_url for a customer who has bought an item?

Am I doing something wrong? Or is this normal behaviour?

## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. put a downloadable product in the store
2. retrieve `/wp-json/wc/v3/products`  endpoint, when authenticated as normal customer
3. => downloadable file information is visible

## Expected/actual behavior

=> Downloadable file information is visible without actually having bought the product.
=> Download file info should be hidden, and only be retrievable when the product is actually bought.

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

Home URL: http://localhost:8000
Site URL: http://localhost:8000
WC Version: 3.5.0
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.25 (Debian)
PHP Version: 7.2.11
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.7.23
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from https://dev.maxmind.com/geoip/geoip2/geolite2/ to the path: . Scroll down to "Downloads" and download the "MaxMind DB binary
gzipped" file next to "GeoLite2 Country". Please remember to uncompress GeoLite2-Country_xxxxxxxx.tar.gz and upload the GeoLite2-Country.mmdb file only.

Total Database Size: 3.12MB
Database Data Size: 2.21MB
Database Index Size: 0.91MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_dokan_announcement: Data: 0.02MB + Index: 0.00MB
wp_dokan_orders: Data: 0.02MB + Index: 0.03MB
wp_dokan_refund: Data: 0.02MB + Index: 0.00MB
wp_dokan_vendor_balance: Data: 0.02MB + Index: 0.00MB
wp_dokan_withdraw: Data: 0.02MB + Index: 0.00MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 1.44MB + Index: 0.05MB
wp_postmeta: Data: 0.06MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 6
customize_changeset: 1
page: 11
post: 2
product: 7
shop_order: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (4) ###

Dokan: by weDevs
LLC – 2.9.2

Jetpack by WordPress.com: by Automattic – 6.6.1
JWT Authentication for WP-API: by Enrique Chavez – 1.2.4
Mailchimp for WooCommerce: by Mailchimp – 2.1.11 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by kloon** [comment]
The API is consumed with shop manager capabilities and not from a customer directly. It would be up to your application to ensure the correct endpoints is returning the correct data to customers if you are building something customer facing, also the API has not session handing meaning customers cannot log in, add to cart etc, that will all need to be handled by your application.

> First of all any logged in user can view all products in the store via the /wp-json/wc/v3/products endpoint. Even if the product is labeled "private" via the wordpress UI.

This is not true, not any logged in user can view this endpoint. This endpoint is only accessible to accounts that has API credentials. Customers will not log in and call your endpoints, your application will do this via a single API account.

> Secondly this same endpoint (/wp-json/wc/v3/products) simply shows the original link of the downloadable files (via the downloads key) BEFORE the product is bought. So a customer doesn't need to buy a product to see the original download link.

Since the API is consumed from a shop manager perspective and not a customer, this endpoint would be for managing products and also displaying product specific information in your application. This is not to retrieve downloads for customers, your app should not be using it for that purpose.

> Thirdly, there is an endpoint wp-json/wc/v3/customers/<user-id>/downloads to get the "real" download URLs, which hide the public external link to the file. The problem is, this endpoint is only viewable by the administrator of the Wordpress install. If a normal customer tries to access it, he'll get a "403". So how to retrieve the download_url for a customer who has bought an item?

Not true, in order for a customer to get assigned a download you will need to create an order with the specific product in question, once that order is created and assigned to the customer they will also get access to the download via the link that gets returned from this. Customers will need to log into your shop in order to download via the link, they need to have an account on your store when you assign them an ID.

Like most people opening API issues you are confusing the way the API is built to be consumed, your application is the once consuming the API and does it with shop manager permissions of either read, write or both, so it would be up to your application to make decisions on what needs to happen with what endpoints data.
