### ISSUE TITLE
Widget Layered Nav is wrapping unwanted speech marks around placeholder text for dropdown

### ISSUE THREAD

**Issue by willfre** [woocommerce/woocommerce#21735]
File: `woocommerce\includes\widgets\class-wc-widget-layered-nav.php`
Line: `296`

The layered nav widgets have started to display `"` around placeholders since version 3.5.

The exact problem seems to be when the string `$any_label` is decoded and encoded. This wasn't the case in previous versions: 

3.4.6: `placeholder: '" . esc_js( $any_label ) . "',`
3.5: `placeholder: '" . wp_json_encode( (string) wp_specialchars_decode( $any_label, ENT_QUOTES ) ) . "',`

I am using Filter by Attribute widget.

Wordpress version: 4.9.8
Woocommerce version: 3.5
PHP: 7.2

![capture](https://user-images.githubusercontent.com/36623127/47652851-fa823680-db7e-11e8-92db-56828e51a647.PNG)

**Comment by kloon** [comment]
See #22185 for fix.
