### ISSUE TITLE
Order Meta Issues after WC 3.5 database update

### ISSUE THREAD

**Issue by princebhalani143** [woocommerce/woocommerce#21731]
**Describe the bug**
It's changing supplied meta data order without making any change.

**To Reproduce**
1. Go to 'WooCommerce > Orders > Add order'
2. Click on 'Add Item(s) > Add Product(s) > Search for the product and Add it with Any quantity'
3. Edit Item using small pencil on the right side of the total
4. Add multiple meta data with Name & Value (Hit Save) and see everything in correct order like (1,2,3,4,5 field)
5. Click on update button (See the meta field is coming in same order) you'll see everything in different order it's not same order as how you have added in step 4

**Screenshots**
Before update
<img src="https://i.imgur.com/MXC35Wc.jpg">
After update
<img src="https://i.imgur.com/gZAeT42.jpg">

**Expected behavior**
It needs to stay the same like what we're supplying in the same order (Nights, Days, Requirements, Summary)

**WordPress Environment**
Basic Wordpress Installation + WooCommerce plugin no other hacks.

**Comment by zwiesman31** [comment]
Confirmed this bug as well: 

Screencast: http://cld.wthms.co/RdcfV4

CC: @claudiosanches as this looks like a quick fix.

**Comment by jamsheerkrd** [comment]
This bug is related to the same issue https://github.com/woocommerce/woocommerce/pull/21641 which is already closed. Hope this issue can also close now

**Comment by bcwebsitedesigner** [comment]
latest update also disabled my reorder function, possibly due to the same shift in meta.

**Comment by claudiulodro** [comment]
#21641 seems to solve this issue. If it's still happening in testing on the `master` branch let me know and I'll re-investigate, but I can't reproduce this any more on the latest `master`.
