### ISSUE TITLE
manual subscription user Issues after WC 3.5 database update

### ISSUE THREAD

**Issue by Arinrockcy** [woocommerce/woocommerce#21734]
**Describe the bug**
Manually created subscription is getting mapped only to Admin User.

**To Reproduce**
1. WooCommerce->subscription->add new
2. change customer
3 . update / create

**Screenshots**
before submitting 

![image](https://user-images.githubusercontent.com/25791376/47648053-d2a2cb00-db9e-11e8-8ece-df69762c640b.png)

after submitting
![image](https://user-images.githubusercontent.com/25791376/47647908-78096f00-db9e-11e8-9729-c615b6fab0b2.png)

**Comment by kloon** [comment]
Related to #21656
