### ISSUE TITLE
Uncaught ReferenceError: wc_tokenization_form_params is not defined  - in shopping cart and checkout

### ISSUE THREAD

**Issue by sharon-shaked** [woocommerce/woocommerce#21739]
**Describe the bug**
When a product has already been placed before into the cart, and you come back to the cart, this error appears:
tokenization-form.min.js?ver=3.5.0:1 Uncaught ReferenceError: wc_tokenization_form_params is not defined
    at new o (tokenization-form.min.js?ver=3.5.0:1)

UPDATE: had to revert the client site to v3.4.7 and the issue is gone.

**To Reproduce**
1. Place product in cart. 
2. go to cart and proceed to checkout
3. don't pay, and go back to homepage.
4. go back to shopping cart and click "checkout" (see JS error in console)

**Expected behavior**
error does not show up and all other JS code runs as usual.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```

סביבת וורדפרס
--
כתובת דף הבית: |   | https://coverme.co.il
כתובת האתר: |   | https://coverme.co.il
גרסת WooCommerce: |   | 3.5.0
ספריית יומן הניתנת לכתיבה: |   | /home/shakeddi/coverme.co.il/wp-content/uploads/wc-logs/
גרסאת WordPress: |   | 4.9.8
רשת אתרים של WordPress: |   | –
מגבלת זכרון של WordPress: |   | 256 MB
מצב איתור באגים של WordPress: |   | –
WordPress cron: |   |  
שפה: |   | he_IL
מטמון של אובייקט חיצוני: |   | –

סביבת וורדפרס
--
כתובת דף הבית: |   | https://coverme.co.il
כתובת האתר: |   | https://coverme.co.il
גרסת WooCommerce: |   | 3.5.0
ספריית יומן הניתנת לכתיבה: |   | /home/shakeddi/coverme.co.il/wp-content/uploads/wc-logs/
גרסאת WordPress: |   | 4.9.8
רשת אתרים של WordPress: |   | –
מגבלת זכרון של WordPress: |   | 256 MB
מצב איתור באגים של WordPress: |   | –
WordPress cron: |   |  
שפה: |   | he_IL
מטמון של אובייקט חיצוני: |   | –
סביבת שרת
פרטי שרת:		Apache
גרסת PHP:		7.0.28 - אנחנו ממליצים להשתמש ב-PHP גרסה 7.2 ומעלה מטעמי אבטחה וביצועים. כיצד לעדכן את גירסת ה-PHP שברשותך
גודל מרבי של פוסט PHP:		8 MB
מגבלת זמן של PHP:		30
וריאציות קלט מרביות של PHP:		1000
גרסת cURL:		7.58.0, OpenSSL/1.0.2n
SUHOSIN מותקן:		–
גרסת MySQL:		5.6.38
גודל העלאה מקסימלי:		8 MB
אזור הזמן המוגדר כברירת מחדל הוא UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
מחרוזת מרובת בתים:		
פרסום מרחוק:		
קבלה מרחוק:		
מסד נתונים
גרסת בסיס נתונים של WooCommerce:		3.5.0
קידומת מסד נתונים	 	wp_
מסד הנתונים GeoIP של MaxMind:		 /home/shakeddi/coverme.co.il/wp-content/uploads/GeoLite2-Country.mmdb
הגודל הכולל של בסיס הנתונים	 	9.11MB
גודל הנתונים של בסיס הנתונים	 	7.71MB
גודל האינדקס של בסיס הנתונים	 	1.40MB
wp_woocommerce_sessions	 	נתונים: 0.05MB + אינדקס: 0.02MB
wp_woocommerce_api_keys	 	נתונים: 0.02MB + אינדקס: 0.03MB
wp_woocommerce_attribute_taxonomies	 	נתונים: 0.02MB + אינדקס: 0.02MB
wp_woocommerce_downloadable_product_permissions	 	נתונים: 0.02MB + אינדקס: 0.05MB
wp_woocommerce_order_items	 	נתונים: 0.02MB + אינדקס: 0.02MB
wp_woocommerce_order_itemmeta	 	נתונים: 0.02MB + אינדקס: 0.03MB
wp_woocommerce_tax_rates	 	נתונים: 0.02MB + אינדקס: 0.06MB
wp_woocommerce_tax_rate_locations	 	נתונים: 0.02MB + אינדקס: 0.03MB
wp_woocommerce_shipping_zones	 	נתונים: 0.02MB + אינדקס: 0.00MB
wp_woocommerce_shipping_zone_locations	 	נתונים: 0.02MB + אינדקס: 0.03MB
wp_woocommerce_shipping_zone_methods	 	נתונים: 0.02MB + אינדקס: 0.00MB
wp_woocommerce_payment_tokens	 	נתונים: 0.02MB + אינדקס: 0.02MB
wp_woocommerce_payment_tokenmeta	 	נתונים: 0.02MB + אינדקס: 0.03MB
wp_woocommerce_log	 	נתונים: 0.02MB + אינדקס: 0.02MB
wp_aryo_activity_log	 	נתונים: 0.27MB + אינדקס: 0.00MB
wp_bv_fw_requests	 	נתונים: 0.02MB + אינדקס: 0.00MB
wp_bv_lp_requests	 	נתונים: 0.02MB + אינדקס: 0.00MB
wp_commentmeta	 	נתונים: 0.00MB + אינדקס: 0.00MB
wp_comments	 	נתונים: 0.00MB + אינדקס: 0.01MB
wp_links	 	נתונים: 0.00MB + אינדקס: 0.00MB
wp_ninja_table_items	 	נתונים: 0.02MB + אינדקס: 0.00MB
wp_options	 	נתונים: 0.73MB + אינדקס: 0.08MB
wp_postmeta	 	נתונים: 4.55MB + אינדקס: 0.57MB
wp_posts	 	נתונים: 1.65MB + אינדקס: 0.18MB
wp_termmeta	 	נתונים: 0.02MB + אינדקס: 0.03MB
wp_terms	 	נתונים: 0.00MB + אינדקס: 0.01MB
wp_term_relationships	 	נתונים: 0.01MB + אינדקס: 0.02MB
wp_term_taxonomy	 	נתונים: 0.00MB + אינדקס: 0.01MB
wp_toolset_post_guid_id	 	נתונים: 0.02MB + אינדקס: 0.02MB
wp_usermeta	 	נתונים: 0.01MB + אינדקס: 0.01MB
wp_users	 	נתונים: 0.00MB + אינדקס: 0.01MB
wp_wc_download_log	 	נתונים: 0.02MB + אינדקס: 0.03MB
wp_wc_webhooks	 	נתונים: 0.02MB + אינדקס: 0.02MB
wp_wdi_feeds	 	נתונים: 0.02MB + אינדקס: 0.02MB
wp_wdi_themes	 	נתונים: 0.02MB + אינדקס: 0.02MB
ספירות של סוגי פוסטים
acf	 	1
attachment	 	534
custom_css	 	1
customize_changeset	 	54
elementor_library	 	12
elementor-popup	 	1
hm_custom_javascript	 	33
nav_menu_item	 	12
ninja-table	 	1
page	 	42
post	 	3
product	 	161
product_variation	 	142
revision	 	569
shop_order	 	3
vendor	 	2
wdi_instagram	 	1
wp-types-group	 	1
אבטחה
חיבור מאובטח (HTTPS):		
הסתר שגיאות ממבקרים		
תוספים פעילים (19)
יומן פעילות	 	מאת Activity Log Team – 2.5.1
WordPress Backup & Security Plugin - BlogVault	 	מאת Backup by BlogVault – 1.78
Custom CSS and Javascript	 	מאת Potent Plugins – 2.0.9
Custom Related Products for WooCommerce	 	מאת Scott Nelle – 1.3 – הפריט לא נבדק עם גרסה פעילה של WooCommerce
שכפול הודעות	 	מאת אנריקו בטוחי – 3.2.2
Elementor Pro	 	מאת Elementor.com – 2.1.11
אלמנטור	 	מאת Elementor.com – 2.2.7
סליקת פלאקארד בווקומרס	 	מאת עידו פרידלנדר – 1.3-iCount+EZcount – הפריט לא נבדק עם גרסה פעילה של WooCommerce
PopBox For Elementor	 	מאת Zulfikar Nore – 1.0.7
Ninja Tables	 	מאת WPManageNinja – 2.4.1
PixelYourSite	 	מאת PixelYourSite – 5.3.2 – הפריט לא נבדק עם גרסה פעילה של WooCommerce
סרגל נגישות	 	מאת סרגל נגישות – 2.0.3
Pojo Custom Fonts	 	מאת Pojo Team – 1.0.5
Pojo Lightbox	 	מאת Pojo Team – 2.0.8
Pojo Sidebars	 	מאת Pojo Team – 1.0.3
Under Construction	 	מאת WebFactory Ltd – 3.15
Instagram Feed by 10Web	 	מאת 10Web – 1.3.7
Open Graph for Facebook, Google+ and Twitter Card Tags	 	מאת Webdados – 2.2.4.2 – הפריט לא נבדק עם גרסה פעילה של WooCommerce
ווקומרס	 	מאת חברת אוטומטיק – 3.5.0
הגדרות
API מופעל:		–
הכרח SSL:		–
מטבע		ILS (₪)
מיקום סימון מטבע		left
מפריד אלפים		,
מפריד עשרוני		.
מספר הספרות העשרוניות		2
טקסונומיות: סוגי מוצרים		external (external), grouped (grouped), simple (simple), variable (variable)
טקסונומיות: נראות המוצר		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
עמודי WooCommerce
בסיס חנות:		#1866 - /%d7%97%d7%a0%d7%95%d7%aa/
עגלת קניות:		#195 - /%d7%a2%d7%92%d7%9c%d7%aa-%d7%a7%d7%a0%d7%99%d7%95%d7%aa/
תשלום:		#204 - /%d7%aa%d7%a9%d7%9c%d7%95%d7%9d/
החשבון שלי:		#207 - /%d7%94%d7%97%d7%a9%d7%91%d7%95%d7%9f-%d7%a9%d7%9c%d7%99/
תנאים והתניות:		#1265 - /%d7%aa%d7%a7%d7%a0%d7%95%d7%9f/
תבנית
שם:		Poza Child
גרסא:		1.0.0
URL מחבר:		http://pojo.me/
ערכת עיצוב בת:		
שם תבנית האב:		Poza
גרסת תבנית אב:		5.0.1
כתובת האתר של יוצרי תבנית האב:		http://pojo.me/
תמיכת ווקומרס:		
תבניות
תבנית ארכיון:	 	ערכת העיצוב כוללת קובץ woocommerce.php, לא תהיה אפשרות לעקוף את התבנית המותאמת אישית woocommerce/archive-product.php מאחר של-woocommerce.php יש עדיפות על-פני archive-product.php. מצב זה הוא מכוון כדי למנוע בעיות תצוגה.
עקיפה	 	poza/woocommerce/content-product.php, 
poza/woocommerce/content-product_cat.php
</details>

**Comment by kloon** [comment]
Please deactivate all plugins except WooCommerce and switch your theme to a default one like Storefront or Twentyseventeen and test again.

In my tests on a clean install, I was unable to replicate this. Closing, I will reopen when I have steps that can reproduce this on a clean install.

**Comment by sharon-shaked** [comment]
While I understand your point, still I encountered a situation in which there is an error
tokenization-form.min.js?ver=3.5.0:1 Uncaught ReferenceError: wc_tokenization_form_params is not defined
at new o (tokenization-form.min.js?ver=XXXX

now, while it is not a WooCommerce fault, it might happen if the "correct mix" of themes and plugins exists.
bottom line, I have it fixed on my own installation by checking if this wc_tokenization_form_params is defined, and if not - define it and place "null" into it. 
it does not effect the UI and lets users buy products rather than get stuck.
I think you should consider adding this check to the code on your side.
