### ISSUE TITLE
Fatal error when modifying `label_class`

### ISSUE THREAD

**Issue by keefyhub** [woocommerce/woocommerce#21730]
https://github.com/woocommerce/woocommerce/commit/87054ece9a4c05db72e139730ed1764c63fab635#diff-03a6101815a8b39c1ff4ee2815fedc1aR666

Should this have been an array instead of a string to be inline with the `class` attribute below? I am adding my own class names to both fields and labels but now getting a fatal error as `label_class` is a string.

```
$field['class'][] = 'my-class';
$field['label_class'][] = 'my-class';
```

or should I be using `$field['label_class'] .= ' my-class';` for the label class only?

**Comment by rodrigoprimo** [comment]
See #21757. Thanks for your contribution. Please let us know if you find any issues with the proposed solution.
