### ISSUE TITLE
Infinite loop when calling get_cart() from woocommerce_add_to_cart_validation filter

### ISSUE THREAD

**Issue by superdav42** [woocommerce/woocommerce#21746]
**Describe the bug**
When the "Order Again" button is used and a woocommerce_add_to_cart_validation filter is set an infinite loop will occur if get_cart() is called from that filter. This is done in [WooCommerce Min Max Quantities](https://github.com/woocommerce/woocommerce-min-max-quantities/blob/master/woocommerce-min-max-quantities.php#L520) to count how many items are the card as part of its validation. I would assume other extensions might try to do similar things so I think this is best fixed is WooCommerce Core.

This bug was introduced in WC 3.5 in https://github.com/woocommerce/woocommerce/commit/f89724b71803be768c8ed9fc3a30930521147839 and https://github.com/woocommerce/woocommerce/commit/759b99ad143bbe2a8cc7d156829dd5628ddfa616#diff-7bafcb4ec4e2600c4c4c5d2145ad8f8eR270

When the code was moved from the WC_Form_Handler class to the WC_Cart_Session class. I have no idea why it was changed this way. It make much more sense for this code to live in the Form Handler as is basically handling a form. 
 
**To Reproduce**
Add a filter like 
```php
add_filter('woocommerce_add_to_cart_validation', function ($pass) {
foreach( WC()->cart->get_cart() as $item ) {

}
} );
```
Find an existing complete order in your account page on the frontend. Click "Order Again" button on the bottom of the page. Page will hang, 500 error or Xdebug will say maximum nesting level reached.

**Expected behavior**
No infinite loop.

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by thomas-zg** [comment]
The WooCommerce Advanced Quantity plugin also end up in a infinit loop.

**Comment by kloon** [comment]
See #21749 for fix.

**Comment by mikejolley** [comment]
@superdav42 The order again functionality was one of the performance bottlenecks solved by moving the code and updating how items are added back to the cart. Before, it would add each item in the order back to the cart individually which would mean that for every item added, not only would stock levels need to be checked, validation ran, but plugins would also run logic for each and every item. 

The example above is a perfect example; for every item added back, you're saying it would need to validate and loop over the entire cart. Thats fine when you're adding one item to the cart in the catalog, but this is in bulk.

There was some talk about it in https://github.com/woocommerce/woocommerce/issues/21845

There are hooks fired once the job is complete. This would be the perfect time to run validation and adjust items if needed once you know the full cart's contents.

> woocommerce_ordered_again should be suitable for that because it fires once all items are added to the cart array. Order again cannot fully mimic regular cart adds because of the performance issue that causes.

Hope this makes sense.
