### ISSUE TITLE
New Order template says "Over to you."

### ISSUE THREAD

**Issue by bondimedical3** [woocommerce/woocommerce#21747]
**Describe the bug**
After the last Woocommerce update email template wording has been changed and the New Order template has the words "Over to you." on the bottom.

**To Reproduce**
1. Place an order and scroll to the bottom of the order confirmation email.

**Expected behavior**
Order processing and Order complete templates are fine with a comment such as "Thank you for your business" but a comment such as "Over to you." has no meaning to 95% of people.

**Comment by nishitlangaliya** [comment]
Hi @bondimedical3

This issue has been fixed in ref #
https://github.com/woocommerce/woocommerce/pull/21709 so you can close this out.

Related #21698


Thanks
