### ISSUE TITLE
PHP Notice:  Trying to get property of non-object on invalid /feed URLs

### ISSUE THREAD

**Issue by glagonikas** [woocommerce/woocommerce#21756]
**Describe the bug**
For the past few versions of WooCommerce as well as v3.5.0, we've been getting some notices when someone tries to access a page that doesn't exist.

> PHP Notice:  Trying to get property 'ID' of non-object in /home/site/public_html/wp-includes/class-wp-query.php on line 3736
PHP Notice:  Trying to get property 'post_title' of non-object in /home/site/public_html/wp-includes/class-wp-query.php on line 3738
PHP Notice:  Trying to get property 'post_name' of non-object in /home/site/public_html/wp-includes/class-wp-query.php on line 3740

**To Reproduce**
1. Install WordPress v4.9.8
2. Install Storefront or keep Twenty Seventeen
3. Make sure you enable WP_DEBUG and WP_DEBUG_LOG.
4. Go to any invalid URL followed by "/feed/" like /something-random-that-makes-an-invalid-url/feed/
5. Check debug.log. It should be empty/missing
6. Install and activate WooCommerce v3.5.0 or v3.4.7
7. Repeat step 4.
8. Check debug.log. It should have some notices

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

Home URL: https://www.example.com
Site URL: https://www.example.com
WC Version: 3.5.0
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.11
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.0.2p

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.36-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 0.49MB
Database Data Size: 0.41MB
Database Index Size: 0.08MB
wp_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_comments: Data: 0.00MB + Index: 0.01MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 0.40MB + Index: 0.02MB
wp_postmeta: Data: 0.00MB + Index: 0.01MB
wp_posts: Data: 0.01MB + Index: 0.01MB
wp_termmeta: Data: 0.00MB + Index: 0.00MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.00MB + Index: 0.00MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_usermeta: Data: 0.00MB + Index: 0.01MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

page: 2
post: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.5.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page not set
Basket: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

</details>

**Comment by glagonikas** [comment]
Found a (possibly) related response, although i didn't test.

> It comes from Woocommerce wc_prevent_adjacent_posts_rel_link_wp_head function which is actioned by the template_redirect hook.
> It does a call to is_singular('product') which gets the queried object and if the query is for a feed it comes back NULL and therefore is not an object.

source: https://stackoverflow.com/a/51049909 from user itinerant

**Comment by rrennick** [comment]
This is a bug in WP vs one in WooCommerce. Any plugin calling `is_singular()` is going to produce these debug messages under those reproduce conditions. Once the first query object has been loaded, `is_singular()` should process without generating any notices.

**Comment by pranksinatra** [comment]
Yep, this also happens in other plugins (e.g. Yoast SEO) when `is_front_page()` is called in a `template_redirect` action when an invalid feed URL is entered.

**Comment by rrennick** [comment]
Reference: https://core.trac.wordpress.org/ticket/45811#ticket

**Comment by glagonikas** [comment]
Ah, great! Thanks for opening a ticket on trac. Let's close the WC ticket and hope the one on WP gets resolved soon.

**Comment by glagonikas** [comment]
This ticket is a duplicate of #11778
