### ISSUE TITLE
Hook for filtered attributes

### ISSUE THREAD

**Issue by shiziksama** [woocommerce/woocommerce#21752]
I want to make filters on category page like this:
![image](https://user-images.githubusercontent.com/425254/47726421-20810700-dc63-11e8-9739-2fe5ded416fd.png)

But i cannot submit form with checkboxes, i must make $_GET-parameters like "filter_size=large,small"

I want to use my own filter and just send simple form with $_GETparameters like "filter_size[]=large&filter_size[]=small"

as alternative i suggest to make filter in WC_Query::get_layered_nav_chosen_attributes

was:
`$filter_terms = ! empty( $_GET[ 'filter_' . $attribute ] ) ? explode( ',', wc_clean( wp_unslash( $_GET[ 'filter_' . $attribute ] ) ) ) : array(); `
my suggestion
```
$filter_terms = apply_filters('get_layered_nav_chosen_attributes_'.$attribute,NULL);
if(!isset($filter_terms)){
	$filter_terms = ! empty( $_GET[ 'filter_' . $attribute ] ) ? explode( ',', wc_clean( wp_unslash( $_GET[ 'filter_' . $attribute ] ) ) ) : array(); 
	}

```

**Comment by mikejolley** [comment]
@shiziksama The filter sounds like a good workaround. Please raise a PR and we'll take a look and get it in 3.6.0. Please make sure the new filter has a `woocommerce_` prefix.

Thanks
