### ISSUE TITLE
Adding a manual order has no shipping

### ISSUE THREAD

**Issue by bondimedical3** [woocommerce/woocommerce#21762]
**Describe the bug**
Whenever you create an order yourself there is no option to add shipping.

**To Reproduce**
1. Create an order manually

**Expected behavior**
Option for shipping should be present

**Comment by kloon** [comment]
Since the order is created manually you will need to add shipping manually as you would with the products. When you click on Add Item(s) http://cld.wthms.co/3rBrRm there is an Add Shipping button http://cld.wthms.co/IM8v35
