### ISSUE TITLE
custom port numbers with web hook delivery urls #2

### ISSUE THREAD

**Issue by matteobaro** [woocommerce/woocommerce#21768]
i read this https://github.com/woocommerce/woocommerce/issues/9350

but i have try the method that your team have linked but it doesn't work
can you help me?

**Comment by rodrigoprimo** [comment]
I'm sorry, but we don't use GitHub issues for support, we use it exclusively for WooCommerce bugs, enhancements and feature requests. If you need support, you could try WooCommerce support forums on WordPress.org (https://wordpress.org/support/plugin/woocommerce).  If you are a paying WooCommerce.com customer, you can contact their support: http://woocommerce.com/contact-us
