### ISSUE TITLE
Order "recalculation" is not working correctly when created over REST API

### ISSUE THREAD

**Issue by alendev** [woocommerce/woocommerce#21767]
**Describe the bug**
Using REST API (v3) within Woocommerce 3.5.0 version.

When applying a negative value fee to an order, the automatic recalculation is not working correctly. For example, put a negative value larger than the order total, expected result would be to show an order total of 0,00 EUR. Currently, the order total shows a negative value until you manually (over the Admin Panel) trigger the recalculate button.

For example:
1. We create a order which sums up to 1.000,00 EUR order total value. 
2. We apply a -3.000,00 EUR fee to the order.
3. The JSON response already shows a negative order total value (same value shown on Admin Panel). 

Once you manually "recalculate" the order over the Admin Panel button, it adjusts the fee correctly - drops the total order value down to 0,00 EUR. This is a problem if you create orders over REST API which are set as paid because the email containing the total and subtotals are part of it.

Example of JSON response with a negative total value:
https://snag.gy/OhTaNn.jpg

Order before manual recalculation:
https://snag.gy/3YzH6M.jpg

Order after manual recalculation:
https://snag.gy/XHzIoB.jpg

**Comment by alendev** [comment]
Due to lack of knowledge about Woocommerce architecture, this is just a workaround that worked for me and should help demonstrate the issue. If anyone has a better solution, please suggest and commit. Thanks.

WC_Abstract_Order::calculate_totals() line 1449: 

`
// Sum fee costs.
foreach ( $this->get_fees() as $item ) {			
	$amount = $item->get_amount();
	
	if ( 0 > $amount ) {
		$item->set_total( $amount );
		$max_discount = round( $cart_total + $fee_total + $shipping_total, wc_get_price_decimals() ) * -1;

		if ( $item->get_total() < $max_discount ) {
			$item->set_total( $max_discount );
		}
		
		continue;
	}
	
	$total_costs 			= $fee_total + $cart_total + $shipping_total;
	$total_costs_forecast 	= $fee_total + $cart_total + $shipping_total + $item->get_total();
	
	if( $total_costs_forecast <= 0 ) {
		$discount = round($total_costs, wc_get_price_decimals()) * -1;
	} else {
		$discount = 0;
	}
	
	$item->set_total($discount);
	$fee_total += $discount;			
}
`

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/22782
