### ISSUE TITLE
Multiple entries of same item in woocommerce order

### ISSUE THREAD

**Issue by nomi416** [woocommerce/woocommerce#21777]
**Describe the bug**
Adding items in editable order manually from admin panel is creating duplicate entries. Like if we add same item twice, it is creating two entries of that item and not updating its quantity.

**To Reproduce**
1. Go to 'Admin pnael -> Woocommerce -> Orders'
2. Open any 'editable order'
3. Add new item (which is already in order)
4. It is creating new entry

**Expected behavior**
It should modify the already added item

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
All plugins and wordpress are updated
</details>

**Comment by rodrigoprimo** [comment]
If you click the "Add new item" button, WooCommerce will add a new item as you described. If you want to change the quantity of an item that is already in the order, you should click in the "Edit item" icon:

![screenshot from 2018-11-01 11-14-05](https://user-images.githubusercontent.com/77215/47857022-5e973b80-ddc7-11e8-9c6f-ba8166a113b7.png)
