### ISSUE TITLE
WC Extensions randomly switched from 'Active' to 'Inactive'

### ISSUE THREAD

**Issue by willgorham** [woocommerce/woocommerce#21774]
**Describe the bug**
I'm not sure if this is the appropriate place to report this, but I've noticed when doing plugin updates that sometimes official WC extensions show 'this plugin is not available for automatic update' on the plugins screen. When I go to /wp-admin/admin.php?page=wc-addons these plugins are set as Inactive, even though they have been Active in the past and nobody has changed their state. 

This has occurred with Facebook for WooCommerce, ShipStation Integration, and Role Based Payment / Shipping Methods, Product Bundles, and WC Subscriptions as far as I can remember.

It's low priority, but this issue halts batch updates and forces me to manually re-enable extension subscriptions before continuing, which slows down site maintenance.

**To Reproduce**
No good steps to reproduce this unfortunately, but it has happened on multiple sites on different servers.

**Expected behavior**
I expect _Active_ extensions to remain _Active_.

**Comment by mikejolley** [comment]
Sounds odd. I've never seen this happen and can find no code in core which would de-activate plugins. Ones that do deactivate would only do so if WC was not detected.

Can you raise a support ticket on woocommerce.com please? One of the happiness engineers and/or extension developers may need to investigate further which is not something we can do over GitHub.

Thanks
