### ISSUE TITLE
Template page thankyou.php repeating info

### ISSUE THREAD

**Issue by rickslayer** [woocommerce/woocommerce#21771]
In thankyou page after payment all information are repeating.
Billing address, shipping address and order details.
![repeating](https://user-images.githubusercontent.com/17550778/47809969-e6763a80-dd20-11e8-90f9-e2f00f055684.png)

**Comment by rodrigoprimo** [comment]
I'm not able to reproduce this problem on a clean WooCommerce install using Storefront. On my test, the addresses are displayed only once below the order details. This is likely an issue on a custom template or something like that. If you believe that is not the case, please leave a comment sharing your status report as requested in the bug report template (https://github.com/woocommerce/woocommerce/issues/new?template=Bug_report.md).
