### ISSUE TITLE
Stop payment options to open and close too much on checkout

### ISSUE THREAD

**Issue by pierrebuet** [woocommerce/woocommerce#21770]
**Is your feature request related to a problem? Please describe.**
There is a lot of movements on the checkout page with the payment boxes of the payment option closing and sliding down at init and then on each change of a payment method. Since the checkout is the page where you want your customer not to be distracted and click on purchase, we should really only change something if we need.

**Describe the solution you'd like**
On init and on change/click of a payment method, the payment box slides down revealing Information but is made inaccessible. After a time ( the ajax call ), the box is then closed and slides down again wit the same information. The box should not open, then close and then reopen again but a single opening should be enough.

**Additional context**
If needed, I would be happy to submit a PR for checkout.js. This can be achieved witha  small change in the finction init_payment_methods of checkout.js.

**Comment by mikejolley** [comment]
@pierrebuet Feel free to submit a PR next time for small tweaks like this. Sounds good - PR incoming.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22459
