### ISSUE TITLE
Pending Payments and stock releasing on back end but not on front end

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce#21772]
ticket: 1527930-zen

**Describe the bug**

When product goes from say `on-hold` or `processing` then to `pending payment` (for one reason or another), stock shows that it gets released back:

![](http://cld.wthms.co/INjOF2+)
Link to screenshot: http://cld.wthms.co/INjOF2

However, on the user facing side, for the next customer, it shows that all products are instock until they go to cart:

![](http://cld.wthms.co/f5U3Nl+)
Link to screenshot: http://cld.wthms.co/f5U3Nl

**To Reproduce**
1. Add a product and enable stock for say 5 products.
2. Complete checkout (order status can be onhold, complete, processing)
3.  Purchase 4 of the 5 items, then in the order, change to pending payment.
4. In notes looks like stock goes back and you should be able to purchase 5 next time
5. As a new customer, purchase 2 product. Product page shows 5 are available
6. However, on cart, it will now say there is not enough in stock 

**Expected behavior**
I'm a bit unclear on what the correct behavior is:

1. Should stock go back when an order is pending?
2. Or Should stock still be "on hold" for that order and product should show the amount that is available?

WC 3.5.1

**Comment by jas8522** [comment]
I'm encountering this same problem. And we have the 'hold stock' configuration value blank, so this definitely shouldn't be happening.

Even for those who *do* have 'hold stock' enabled, there needs to be *something* on the product's stock/inventory page in the admin indicating the number of this item that's currently being held due to pending orders. But that's probably a feature request and we should stay focused on the issue that the 'hold stock' config is being ignored in this instance.

**Comment by vhfilgueiras** [comment]
Happening to me as well. 

[Copy pasta from the plugin support page](https://wordpress.org/support/topic/not-variable-product-showing-as-out-of-stock/): All plugins deactivated except Woo, same result, still saying the product is out of stock (-8 products in the message alert but with 2 manual setted up in the product page) with hold stock disabled, CloudFlare in dev mode.

**Comment by jas8522** [comment]
This is pure conjecture at the moment, but it may be [related to this change](https://github.com/woocommerce/woocommerce/pull/20260). Will keep digging.

**Comment by madeincosmos** [comment]
PS Looks like **Pending Payment** orders used to fully reduce product stock in the past, but now they don't and are only counted when product is in cart in a bit different way.

**Comment by apooley** [comment]
In many of the cases we're seeing, the order was placed, the authorization for the card transaction was declined, and the order was set into Pending Payment by WooCommerce - not by the shop owner or any manual action. Would you not want it to release the items for sale at this point? This seems like something the store owner could/would decide with the Hold Stock option - which is disabled in our particular case.

**Comment by jfacemyer** [comment]
I've got this same issue. We use Pending Payment for shipped-but-unpaid invoices (surely others do too?) and have been for years. This is definitely a change in 3.5 which has created a holdover stock miscalculation on update.

**Comment by plxrisa** [comment]
I have  the same issue too. I use "Pending Payments" for unpaid invoices, so I don't have these products in stock anymore.

But, when I change the stock status to "Pending Payment", shows these products again back in stock. So, if a customer would buy any of these products, I don't have stock to send them.

**Comment by yukikatayama** [comment]
reported also in 1535719-zen

**Comment by LaurenaRehbein** [comment]
Reported also in 1567468-zen

**Comment by agaleski** [comment]
Here a quickfix that we used to avoid this issue until this bug is fixed by the WC team:

```
add_filter('woocommerce_product_get_manage_stock', 'fix_check_cart_item_stock', 11, 2);
/**
 * Attempt to fix WC_Cart->check_cart_item_stock() to old behaviour aka
 * NOT taking into account "stock" from pending orders.
 * Also avoiding the (for large shops very painful) held-quantity check.
 *
 * @param bool $manageStock
 * @param null|\WC_Product $product
 *
 * @return bool $manageStock
 */
function fix_check_cart_item_stock($manageStock = true, $product = null)
{
    try {
        if ($manageStock && ! is_admin() && is_object($product) && $product->get_stock_quantity() >= 1) {
            $manageStock = false;
        }
    } catch (\Exception $e) {
        error_log(print_r($e, true));
    }

    return $manageStock;
}
```

Why did we do this?
a) We have a lot pending orders as we do not clean them up so far.
b) The function `wc_get_held_stock_quantity()` is really intensive on our large DBs at **every** cart page load...

**Comment by agaleski** [comment]
The check
```
// Check stock based on all items in the cart and consider any held stock within pending orders.
			$held_stock     = ( $hold_stock_minutes > 0 ) ? wc_get_held_stock_quantity( $product, $current_session_order_id ) : 0;
```
is also missing in class-wc-shortcode-checkout.php => This issue also prevents form-pay.php to load correctly.
https://github.com/woocommerce/woocommerce/blob/master/includes/shortcodes/class-wc-shortcode-checkout.php#L152

**Comment by LaurenaRehbein** [comment]
Needs developer confirmation, but I believe this is fixed in the latest release, WC 3.5.2:

* https://github.com/woocommerce/woocommerce/pull/21797

@claudiulodro perhaps you could confirm if this can be closed?

**Comment by gpadilha** [comment]
I'm facing the same issue here. The thing is when the order is "Pending" the quantity of this order is kept "on holding"; however, seems like WooCommerce doesn't consider the held quantity when displaying the available stock on the admin and when the method get_stock_quantity() is called. 

On the WC documentation the description for the method get_stock_quantity() is: "Return number of items available for sale".
If held items are not available for sale, why is the method returning the held quantity as stock quantity?

**Comment by claudiulodro** [comment]
I believe this was fixed in https://github.com/woocommerce/woocommerce/pull/21797. Let me know if you are still experiencing this issue and we will reopen this and investigate further.
