### ISSUE TITLE
Wrong item quantity after click "add to cart"

### ISSUE THREAD

**Issue by tlqmhs** [woocommerce/woocommerce#21773]
**Describe the bug**
site url: https://myheatsinks.com/store/
For example, a test product on store website, first add 20 of "TestProduct1" to cart, then the item quantity in cart page is 20, second go back to product page and add 10 of "TestProduct1" to cart, then check the quantity on cart page again, the new quantity in cart is 10 instead of 30. It's just an example for description, this kind of situation appears on all products. ("Add to cart" behaves like a "Update cart" button)
The only amount which get correctly result is 1, if I try to add 1 of "TestProduct1" to cart, the new item quantity in cart become 21. But if I input 2, 3, 4.....I will get wrong quantity in cart.

I've tried to clear all the code I wrote in child theme's function.php, and testedwith same procedure, it still happens. 
Also tried to deactivate all plugins with functions related to cart action or filter, still get wrong quantity. 
Tested with default Twenty Seventeen theme, still happens. 

I think it's not because of woocommerce plugin itself, another website with same version of woocommerce works fine, but I can't figure out which part cause this problem. If anyone can help, I'm very appreciated

**Expected behavior**
The correct amount should be quantity already in cart + quantity added to cart

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://myheatsinks.com/store
Site URL: https://myheatsinks.com/store
WC Version: 3.5.1
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.11
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.59.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.40-84.0-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.1
WC Database Prefix: mstore_
MaxMind GeoIP Database: ✔
Total Database Size: 8.10MB
Database Data Size: 6.17MB
Database Index Size: 1.93MB
mstore_woocommerce_sessions: Data: 1.20MB + Index: 0.02MB
mstore_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
mstore_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
mstore_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
mstore_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
mstore_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
mstore_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
mstore_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
mstore_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
mstore_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
mstore_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
mstore_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
mstore_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
mstore_woocommerce_log: Data: 0.02MB + Index: 0.02MB
mstore_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB
mstore_atum_order_items: Data: 0.02MB + Index: 0.02MB
mstore_aws_cache: Data: 0.02MB + Index: 0.00MB
mstore_aws_index: Data: 0.16MB + Index: 0.00MB
mstore_commentmeta: Data: 0.02MB + Index: 0.03MB
mstore_comments: Data: 0.02MB + Index: 0.09MB
mstore_failed_jobs: Data: 0.02MB + Index: 0.00MB
mstore_links: Data: 0.02MB + Index: 0.02MB
mstore_loginizer_logs: Data: 0.00MB + Index: 0.01MB
mstore_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
mstore_options: Data: 2.08MB + Index: 0.08MB
mstore_postmeta: Data: 0.20MB + Index: 0.25MB
mstore_posts: Data: 0.09MB + Index: 0.06MB
mstore_ppc_exceptions: Data: 0.02MB + Index: 0.05MB
mstore_ppc_exception_items: Data: 0.02MB + Index: 0.03MB
mstore_ppc_roles: Data: 0.02MB + Index: 0.03MB
mstore_pp_groups: Data: 0.02MB + Index: 0.02MB
mstore_pp_group_members: Data: 0.02MB + Index: 0.05MB
mstore_queue: Data: 0.02MB + Index: 0.00MB
mstore_termmeta: Data: 0.02MB + Index: 0.03MB
mstore_terms: Data: 0.02MB + Index: 0.03MB
mstore_term_relationships: Data: 0.02MB + Index: 0.02MB
mstore_term_taxonomy: Data: 0.02MB + Index: 0.03MB
mstore_usermeta: Data: 0.06MB + Index: 0.03MB
mstore_users: Data: 0.02MB + Index: 0.05MB
mstore_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB
mstore_wc_download_log: Data: 0.02MB + Index: 0.03MB
mstore_wc_webhooks: Data: 0.02MB + Index: 0.02MB
mstore_woof_query_cache: Data: 0.02MB + Index: 0.02MB
mstore_wsal_metadata: Data: 1.52MB + Index: 0.41MB
mstore_wsal_occurrences: Data: 0.08MB + Index: 0.08MB
mstore_wsal_options: Data: 0.02MB + Index: 0.00MB
mstore_yith_wcwl: Data: 0.02MB + Index: 0.02MB
mstore_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB

### Post Type Counts ###

attachment: 12
atum_supplier: 1
custom_css: 1
customize_changeset: 16
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 2
jp_sitemap_master: 2
nav_menu_item: 6
page: 7
post: 2
product: 57
revision: 9
shop_order: 3
wccaf: 2
wcccf: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

Adminimize: by Frank Bültge – 1.11.4
Advanced Woo Search: by ILLID – 1.54
ATUM Inventory Management for WooCommerce: by Stock Management Labs™ – 1.4.17
Capability Manager Enhanced: by Jordi Canals
Kevin Behrens – 1.5.10

Admin Columns: by AdminColumns.com – 3.2.7
Flexible Shipping UPS: by WP Desk – 1.2.1
Guest Order Tracking for WooCommerce: by Algoritmika Ltd – 1.0.1 – Not tested with the active version of WooCommerce
Jetpack by WordPress.com: by Automattic – 6.6.1
Loginizer: by Raj Kothari – 1.4.0
Mailchimp for WooCommerce: by Mailchimp – 2.1.11 – Not tested with the active version of WooCommerce
Press Permit Core: by Agapetry Creations LLC – 2.5
SG Optimizer: by SiteGround – 4.0.7
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.15.3

WC Fields Factory: by Saravana Kumar K – 3.0.3 – Not tested with the active version of WooCommerce
Woo Checkout Field Editor Pro: by ThemeHiGH – 1.2.9
WooCommerce Bulk Discount: by Rene Puchinger – 2.4.5 – Not tested with the active version of WooCommerce
WooCommerce Customizer: by SkyVerge – 2.6.0 – Not tested with the active version of WooCommerce
WooCommerce Extra Product Sorting Options: by SkyVerge – 2.7.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Clean Commerce Pro Child
Version: 1.0.1539292756
Author URL: http://wenthemes.com/
Child Theme: ✔
Parent Theme Name: Clean Commerce Pro
Parent Theme Version: 1.0
Parent Theme Author URL: http://wenthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by rodrigoprimo** [comment]
I'm sorry, but we don't use GitHub issues for support, we use it exclusively for WooCommerce bugs, enhancements and feature requests. If you need support, you could try WooCommerce support forums on WordPress.org (https://wordpress.org/support/plugin/woocommerce). If you are a paying WooCommerce.com customer, you can contact their support: http://woocommerce.com/contact-us
