### ISSUE TITLE
'get_plugins_with_header' will always return an empty array

### ISSUE THREAD

**Issue by enventa** [woocommerce/woocommerce#21780]
**Issue**
**`get_plugins_with_header()`** function will always return an empty array because adding proprietary headers (like "**`WC requires at least`**" and "**`WC tested up to`**" ) to a plugin's main file has no effect if you retrieve those headers using **`get_plugins()`** function from WP, which only returns WP recognized headers (which are: Name, PluginURI, Version, Description, Author, AuthorURI, TextDomain, DomainPath, Network, Title and AuthorName).

Thus, adding those headers to any plugin won't make it have version check support from WC.

It will have version check support only if its name contains the "woocommerce" string, because **`get_plugins_for_woocommerce()`** comes into play.

**To Reproduce**
1. Create and install a plugin without the "woocommerce" string within its name
2. Install a version of WC like 3.3.3, so you get the update message
3. Go to the "Plugins" page in the WP Dashboard and locate WooCommerce
4. See how your plugin is not listed under the "compatibility list" added by WC below its note of "update available"

**Expected behavior**
A plugin for WC having a name without the "woocommerce" string should be listed under the "extensions_warning" list when a WC update is available.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
4.9.8

**WooCommerce Environment**
3.3.3 (checked latest code and it has not changed since version 3.3.3).

**Comment by rodrigoprimo** [comment]
cc @claudiulodro could you please take a look since, if I remember correctly, you worked on this?

**Comment by siananda** [comment]
I think this **get_plugins_with_header()** this function return correct plugin info arrays. If plugins have **WC tested up to** header value **get_plugins_with_header()** function return plugins info.

![plugins bug testing wordpress - copy](https://user-images.githubusercontent.com/10962969/47867948-380beb80-de2d-11e8-9165-e8054917e41d.png)

![plugins bug testing 2](https://user-images.githubusercontent.com/10962969/47867990-4c4fe880-de2d-11e8-9c64-d5b41d31c40f.png)

**Comment by enventa** [comment]
Hmm... I also did a `print_r()` but didn't get that fields... In fact, I got an empty array. I tested it having installed other plugins for WC which declare WC headers but they didn't get retrieved by that function either. I'm gonna install WC 3.4.5 (the version that @siananda has installed) to check if that might be something that got fixed between 3.3.3 and 3.4.5.

**Comment by enventa** [comment]
I've updated WC to 3.4.5 and checked again and I still get an empty array when checking `$matches` contents...

**Comment by siananda** [comment]
@enventa please check you added header tag properly. From my end, it's working properly.

![header tag](https://user-images.githubusercontent.com/10962969/47926382-9e0a7880-deea-11e8-9ca6-4926b37d28be.png)

**Comment by enventa** [comment]
Hi @siananda,

I've checked, not only in my plugin but also in others, like this one from Yith:

The header is there:
![screenshot_2018-11-02 edit plugins molongui plugins wordpress](https://user-images.githubusercontent.com/18630142/47929431-4576b380-dec9-11e8-852f-31f524c6f677.png)

The function doesn't retrieve WC headers:
![image](https://user-images.githubusercontent.com/18630142/47929420-3d1e7880-dec9-11e8-869a-4d309f490e32.png)

And the plugin is listed because of the "woocommerce" string on its name (version listed as "unknown"):
![screenshot_2018-11-02 plugins molongui plugins wordpress](https://user-images.githubusercontent.com/18630142/47929555-aacaa480-dec9-11e8-8c4a-3b8ae240852f.png)

Might it be some WC configuration I don't have set properly?

**Comment by kloon** [comment]
The function works as it should, the function get_plugins should however not be called too early which will cause issues, this seems related to that which was fixed in https://github.com/woocommerce/woocommerce/pull/21669
