### ISSUE TITLE
Maintain original usage tracking setting after disconnecting helper

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce#21785]
**Is your feature request related to a problem? Please describe.**

If I choose to "Help WooCommerce improve with usage tracking" (i.e. during the setup wizard) and if I then connect and disconnect from WooCommerce.com, I am **always** opted out after disconnecting.

**Describe the solution you'd like**

If I choose to "Help WooCommerce improve with usage tracking" (i.e. during the setup wizard), that choice should be preserved if I disconnect from WooCommerce.com.

**Describe alternatives you've considered**

N/A

**Additional context**
See https://github.com/woocommerce/woocommerce/blob/d0491072e8a7d0a4535db0ec2bae4a6d43ff64fd/includes/admin/helper/class-wc-helper.php#L794

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/22890
