### ISSUE TITLE
Hide Shipping Calculator (and address) on cart page

### ISSUE THREAD

**Issue by melindahelt** [woocommerce/woocommerce#21787]
1535692-zen

In WooCommerce 3.4.7, the address was not displayed on the card page by default (address saved in under account). User would like to have the option to not display that address, as was done previously when the shipping calculator was hidden on the cart page.

Shipping Settings:
![](http://cld.wthms.co/ECiRD9+)Image Link: http://cld.wthms.co/ECiRD9

Cart page of WooCommerce 3.4.7
Logged in with an address in account
![](http://cld.wthms.co/9zmIpU+)Image Link: http://cld.wthms.co/9zmIpU

Cart page of WooCommerce 3.5.1
Logged in with an address in account
![](http://cld.wthms.co/SMzLNp+)Image Link: http://cld.wthms.co/SMzLNp

Cart page of WooCommerce 3.5.1
Incognito window
![](http://cld.wthms.co/uvGVAB+)Image Link: http://cld.wthms.co/uvGVAB

User would like to know why checkbox is not being respected and would like to have the option to not show this address on the cart, even when customer is logged into site.

**Comment by kloon** [comment]
Originally it always showed, then we changed it and got complaints as people would use the cart page calculator for estimates. See #21360

If they want to hide the shipping calculator on the cart page then they need to check the box just above the one they think should do it called "hide shipping calculator on cart page" that way the shipping will only be available to select on the checkout page.

**Comment by melindahelt** [comment]
@kloon 

The heart of the issue is:

>User would like to know why checkbox is not being respected and would like to **have the option to not show this address on the cart, even when customer is logged into site**.

User does not want to show the address on the cart page. Is that a separate issue than the calculator?

**Comment by seanreloaded** [comment]
@kloo

I have a user with the same issue (zd-1562988). Even if the **Enable the shipping calculator on the cart page** option is disabled, there should not be any "Estimate for..." text displayed there.

**Comment by jobthomas** [comment]
Another one: 9408176-hc

I've been able to confirm this. Even with the option enabled a shipping cost is shown:

![http://cld.wthms.co/kQRQLQ](http://cld.wthms.co/kQRQLQ+)
Link to image here: http://cld.wthms.co/kQRQLQ.

Incognito window with guest user (so no address added anywhere):

![http://cld.wthms.co/BtgJcN](http://cld.wthms.co/BtgJcN+)
Link to image here: http://cld.wthms.co/BtgJcN.

I'd expect this to show either no shipping section, or just mention "the shipping will be calculated in the checkout"

**Comment by mikejolley** [comment]
@jobthomas thats fine given your settings. You have the calculator disabled, but you're not disabling the visibility or existance of shipping. 

This ticket is about the 'hide shipping costs until address is entered' setting. If thats ENABLED, I'd expect no shipping cost to show unless the user has an account and address already. If in the case of the OP there is an address, because the user is logged in, shipping **should** display.

It's wrong to compare the output of the quoted address against versions before 3.5 however, because prior versions did not have this output under any circumstances. It can be hidden with CSS.

**Comment by mikejolley** [comment]
I've confirmed the setting is working.

With these settings:
![woocommerce settings test s galore wordpress 2019-01-15 17-04-49](https://user-images.githubusercontent.com/90977/51196771-bb46c480-18e7-11e9-8103-0e89969affc3.png)

In incognito:
![cart test s galore 2019-01-15 17-04-38](https://user-images.githubusercontent.com/90977/51196784-c00b7880-18e7-11e9-9b9e-acc22d4c8b98.png)

No shipping is shown until checkout.

With a logged in user, they have an address, so shipping should display.

Hope that clears things up.

**Comment by jobthomas** [comment]
:disappear:
