### ISSUE TITLE
Bad order statuses after create order – both for customer and admin

### ISSUE THREAD

**Issue by tomaskavalek** [woocommerce/woocommerce#21784]
**Describe the bug**
After update from `3.4.7` to `3.5.1`, there is problem with e-mails which system send after receiving new order. Same problem in `3.5.0`.

After creating new order admin receive e-mail with subject [{site_title}] Order failed (XXXX) instead of New order (1) od {site_title} ({order_date}). Same for customer – Payment received for your order instead of Your {site_title} order receipt from {order_date}.

It seems there is some bug in order states.

**To Reproduce**
1. Make standard order.
2. Check customer mailbox.
3. Check admin mailbox.

**Screenshots**
Not neccessary.

**Expected behavior**
Described at the top.

Admin receive e-mail about cancelled order – BAD.
Customer receive e-mail about payed order – BAD.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by tomaskavalek** [comment]
Now tested on clean WordPress with only WooCommerce plugin active. Same issue.

**Comment by kloon** [comment]
In 3.5 we update the email copy, which is the emails are different for you. The copy changes is an improvement to the copy that was there, it is now more humanized in the sense that the customer, as well as store owner, has a better understanding of what the email is about.

This is not a bug but an enhancement. You are welcome to modify the emails to your own liking by overriding the templates. SellWithWP did an article on how to do this not so long ago https://www.sellwithwp.com/customizing-woocommerce-order-emails/

**Comment by tomaskavalek** [comment]
I don't understand why administrator of e-shop (store owner) recive e-mail that order has failed after customer made order. What enhancement if order really not failed?

**Comment by kloon** [comment]
You will receive the email if the order failed. Go look in wp-admin for the specific order and see the order notes, it will tell you why it failed. Could be due to non payment on the customer side.

**Comment by tomaskavalek** [comment]
If customer made order with COD payment, then he receive e-mail with Subject "Payment received for your order", and store owner received "Order failed". How the order can failed, if it still waiting for payment? Why customer receive e-mail that Payment received, if he doesn't pay any money yet?

Sorry, but I don't understand this enhancement. Can you explain it? Thanks a lot.

**Comment by tomaskavalek** [comment]
Works well again in 3.5.7.
