### ISSUE TITLE
Preview Changes Button Not Appearing

### ISSUE THREAD

**Issue by popidev** [woocommerce/woocommerce#21781]
**Describe the bug**
In the Publish meta area there is no longer the button to preview changes.

**To Reproduce**
Go to any product edit page on latest version of WooCommerce.

**Screenshots**
https://imgur.com/a/RT8XwO1

**Expected behavior**
The Preview Changes button to be there.

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
`
### WordPress Environment ###

Home URL: https://popitest.popidev.net
Site URL: https://popitest.popidev.net
WC Version: 3.5.0
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.29 (Unix) mod_hive/6.6 OpenSSL/1.0.1e-fips mod_fastcgi/2.4.6
PHP Version: 5.6.38 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 32 MB
PHP Time Limit: 45
PHP Max Input Vars: 1000
cURL Version: 7.59.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.36-82.1-log
Max Upload Size: 24 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.0
WC Database Prefix: wplp_
MaxMind GeoIP Database: ✔
Total Database Size: 1.88MB
Database Data Size: 1.04MB
Database Index Size: 0.84MB
wplp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wplp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wplp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wplp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wplp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wplp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wplp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wplp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wplp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wplp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wplp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wplp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wplp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wplp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wplp_commentmeta: Data: 0.02MB + Index: 0.03MB
wplp_comments: Data: 0.02MB + Index: 0.08MB
wplp_links: Data: 0.02MB + Index: 0.02MB
wplp_loginizer_logs: Data: 0.00MB + Index: 0.00MB
wplp_options: Data: 0.50MB + Index: 0.02MB
wplp_postmeta: Data: 0.02MB + Index: 0.03MB
wplp_posts: Data: 0.02MB + Index: 0.06MB
wplp_termmeta: Data: 0.02MB + Index: 0.03MB
wplp_terms: Data: 0.02MB + Index: 0.03MB
wplp_term_relationships: Data: 0.02MB + Index: 0.02MB
wplp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wplp_usermeta: Data: 0.02MB + Index: 0.03MB
wplp_users: Data: 0.02MB + Index: 0.05MB
wplp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wplp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

page: 5
product: 3
product_variation: 2
revision: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Loginizer: by Raj Kothari – 1.4.0
SG Optimizer: by SiteGround – 4.0.7
WooCommerce: by Automattic – 3.5.0 – 3.5.1 is available
WordPress Starter: by SiteGround – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #2 - /shop/
Cart: #3 - /cart/
Checkout: #4 - /checkout/
My account: #5 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by rodrigoprimo** [comment]
Hi,

It was removed on published products because most WooCommerce product fields are not set up to work with the "Preview Changes" feature of WordPress, so the button did not really do anything. You can read more at #20641. Hope this clears things up.

Thanks.
