### ISSUE TITLE
3rd party REST authentication broken since 3.5+

### ISSUE THREAD

**Issue by larssn** [woocommerce/woocommerce#21789]
**Describe the bug**
We're been using https://github.com/WP-API/OAuth1 for quite a while. But since WC 3.5, WC seems to have taken over the authentication process, meaning it runs before the OAuth1 plugin runs, which result in denied requests.

So a request like `GET https://site.sk/wp-json/wc/v2/orders/123` would now fail, since WC is trying to handle it before the OAuth1 plugin.

As a temporary workaround, we've commented out the following line:
https://github.com/woocommerce/woocommerce/blob/d0491072e8a7d0a4535db0ec2bae4a6d43ff64fd/includes/api/class-wc-rest-authentication.php#L42

That allows data to still be gotten.

Our initial investigation hasn't yielded much, but it looks like the filter at: https://github.com/woocommerce/woocommerce/blob/d0491072e8a7d0a4535db0ec2bae4a6d43ff64fd/includes/api/class-wc-rest-authentication.php#L41
which, for whatever reason, _seems_ to run way to early, even though it has priority 15.

The same filter runs in OAuth1 server, where it has priority 10.

Not sure what has changed. Hoping you guys have more insight, as we have **a lot** of sites running WC that is affected by this.

**To Reproduce**
Install the OAuth1 plugin, and set up it.
Do some `GET`'s from a secured non-WC endpoint, to verify that it's running.
Now do a GET from a WC endpoint, which will get denied with a `woocommerce_rest_authentication_error` error.

**Expected behavior**
Prior to WC 3.5, the OAuth1 plugin were allowed to determine the user.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active. **Note**, that the OAuth1 plugin needs to be enabled.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by larssn** [comment]
I'll post more info if we find something interesting.

**Comment by claudiosanches** [comment]
Thanks for reporting it.
See https://github.com/woocommerce/woocommerce/pull/22013
