### ISSUE TITLE
After 3.5 update default emails are not translated fully when site language is changed

### ISSUE THREAD

**Issue by geeklore** [woocommerce/woocommerce#21791]
**Describe the bug**
After 3.5 update default emails are not translated fully when site language is changed. For example set the site language to Mexico Spanish.

**To Reproduce**
1. Go to *Settings -> General -> Site Language* and set the site language to `Español de México`
2. Create a test order.
3. Check the email.
4. ❌ Email is partially translated.

**Screenshots**
This is a screenshot of a default email in `3.5.1`.

![see screen shot](http://cld.wthms.co/sMS7n9+)
Link: http://cld.wthms.co/sMS7n9

**Expected behavior**
I would expect all of the email to be translated.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by tjuris** [comment]
Hi, thats probably because some new strings are not yet translated in that language.
Here's where you can help translate them: https://translate.wordpress.org/locale/es-mx/default/wp-plugins/woocommerce

**Comment by kloon** [comment]
What @tjuris said. Translations are a community effort and after we release a new version it takes a week or two for translations to get updated by the community. You can also translate it yourself with a plugin like loco translate.
