### ISSUE TITLE
woocommerce_hold_stock_minutes ignored when checking cart item stock.

### ISSUE THREAD

**Issue by jdmadison** [woocommerce/woocommerce#21796]
**Describe the bug**
The setting for 'woocommerce_hold_stock_minutes' is no longer checked when comparing required stock against available stock in the view cart and checkout screens. Prior to 3.5.0, `$held_stock` was only calculated if `woocommerce_hold_stock_minutes` was set to a value greater than zero and backorders were disabled for a particular product. In 3.5.0, the query for calculating the number of a product held in pending orders was moved to a utility function `wc_get_held_stock_quantity`, and `woocommerce_hold_stock_minutes` condition was removed. 

Even with the "hold stock" option left unset, if the quantity of a product being held in `wc-pending` orders exceeds available stock, the following error is displayed in the cart/checkout screens: "Sorry, we do not have enough "product name" in stock to fulfill your order (-123 available)."

**To Reproduce**
1. In **WooCommerce > Settings > Products > Inventory** enable **Manage Stock** and leave **Hold Stock (minutes) empty.**
2. Install PayPal payment gateway & configure w/ Sandbox Credentials 
3. Create a simple product with stock management enabled, stock quantity of 10, and backorders disallowed.
4. Add 10 of the newly created product to your cart and enter the PayPal checkout flow to create an order with a status of wc-pending (do not complete checkout).
5. In a separate incognito browser window, add the newly created product to your cart.
6. Go to the view cart screen.

**Screenshots**
![screenshot 2018-11-02 12 03 30](https://user-images.githubusercontent.com/3507910/47935375-5c041700-de97-11e8-9562-13fe6a83531c.png)

**Expected behavior**
Normal checkout flow.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

Home URL: http://localhost:8080
Site URL: http://localhost:8080
WC Version: 3.5.1
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.25 (Debian)
PHP Version: 7.2.8
PHP Post Max Size: 50 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.7.18
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from https://dev.maxmind.com/geoip/geoip2/geolite2/ to the path: . Scroll down to "Downloads" and download the "MaxMind DB binary
gzipped" file next to "GeoLite2 Country". Please remember to uncompress GeoLite2-Country_xxxxxxxx.tar.gz and upload the GeoLite2-Country.mmdb file only.

Total Database Size: 1.88MB
Database Data Size: 1.04MB
Database Index Size: 0.84MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 0.50MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

page: 6
post: 2
product: 1
shop_order: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /?page_id=5
Cart: #6 - /?page_id=6
Checkout: #7 - /?page_id=7
My account: #8 - /?page_id=8
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
</details>

**Comment by conschneider** [comment]
I can confirm this. Worked on this via: https://woothemes.zendesk.com/agent/tickets/1514543 - screencast showing behaviour change v3.4.7 >> v3.5.x: http://somup.com/cFX1lbn1EN

**Comment by rwkyyy** [comment]
@claudiulodro This is still present on 3.6.5; just as described by @conschneider .

**Comment by rwkyyy** [comment]
@claudiulodro @conschneider there is still a problem that I think it's related to this.

In my setup, I have 60 minutes threshold, a product with 3 general inventory, and 4 different variations (each with 1 stock) and if you add to cart any variation, you get the same notice.

If you deactivate the hold stock (leave empty) the notice goes away.

p.s. I do not have any orders in pending with this product, only two completed.
