### ISSUE TITLE
WC_Cart::add_fee amount changes to $0 if subtotal is $0

### ISSUE THREAD

**Issue by zaderade** [woocommerce/woocommerce#21799]
**Describe the bug**
Cart fees are set to zero if the subtotal is also zero. This can happen if the only item in your cart is a Subscription product.

**To Reproduce**
1. Create subscription product with a recurring fee but no one-time fee.
2. Use WC()->cart->add_fee( "Surcharge", 100 );

**Screenshots**
https://my.cl.ly/content/9500320dd953

**Expected behavior**
The surcharge should still apply, regardless of the subtotal amount.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by kmg-yrabelo** [comment]
@zaderade,

This is a WooCommerce Subscriptions issue, not a WooCommerce problem.
I had the same problem a couple of weeks ago and opened a ticket on Github asking for a way to do exactly what you are trying to do via a filter.

The pull request has been closed but it hasn't been released yet. I was told it would be in the next release so you'll be able to do that.

**Comment by kloon** [comment]
Agree with @kmg-yrabelo, I tested this with a free product using only WooCommerce core and it applies the fee fine.

Please contact support for help with this since we only deal with WooCommerce core related issues on here. https://woocommerce.com/contact-us/
