### ISSUE TITLE
Lost Password error messages not beign displayed

### ISSUE THREAD

**Issue by Pratik-Jain12** [woocommerce/woocommerce#21792]
**Describe the bug**
On WooCommerce lost password page the error messages are not displaying.

**To Reproduce**
1. Go to 'Lost Password Page'
2. Click on 'Reset Password' button
3. Page refresh but no error message are displaying. 

**Expected behavior**
Error message should be displayed.
I have debug the issue and found that WooCommerce add the error via 'wc_add_notice' in this function 'retrieve_password' but it is not displaying.

When we use this action do_action( 'lostpassword_post', $errors ); some third party plugin error are not also going to be display.

Lost Password should have action to display 'wc_print_notices'.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by kloon** [comment]
I am unable to recreate this, works fine for me when I tested an error http://cld.wthms.co/ldvBR1 as well as a success http://cld.wthms.co/5k64P1

**Comment by Pratik-Jain12** [comment]
Hi @kloon 
I have checked your screenshot http://cld.wthms.co/ldvBR1 and it looks like that you are using Store Front theme.

I am checking with WordPress default theme. I am using Twenty Twelve theme.

I have checked it with Store Front theme and yes, it display error messages. I have debug the issue and found that theme uses this action 'storefront_content_top' to display Shop messages.

Please check with WordPress default theme and you will be able to reproduce the issue.

Kind Regards,

**Comment by siananda** [comment]
I tested it default twenty seventeen theme. Error message not showing. Please check the video.

https://youtu.be/O8UDZMLAwtk

**Comment by kloon** [comment]
See #22001

**Comment by melindahelt** [comment]
I just re-tested this with WooCommerce 3.5.4 and Twenty-Nineteen and when entering an incorrect password on this page, the page re-loads but no error message is shown:

![](http://cld.wthms.co/tTyTyw+)Image Link: http://cld.wthms.co/tTyTyw

The error does show up on Storefront:
![](http://cld.wthms.co/Bdl0H9+)Image Link: http://cld.wthms.co/Bdl0H9

We should have this working for default themes.

**Comment by mikejolley** [comment]
This is a different form. See https://github.com/woocommerce/woocommerce/issues/22601 (duplicate).
