### ISSUE TITLE
Move Thumbnail Images Below Main Image - Not Overlaid

### ISSUE THREAD

**Issue by co50** [woocommerce/woocommerce#21794]
**Is your feature request related to a problem? Please describe.**
When using a main image with a dark background and alternate images with dark backgrounds, the thumbnails blend in and are difficult to see.

**Describe the solution you'd like**
The thumbnails should adhere to common e-commerce best practices and be moved off of the main image, preferably below the main image so users can better identify additional images and select them. Might also make sense to enlarge them by at least 25% as they appear microscopic on 4k displays.

**Describe alternatives you've considered**
A white border around the thumbnails, though this could make the thumbs appear as part of the image on white bg main images.

**Additional context**
![git](https://user-images.githubusercontent.com/11934431/47924870-2ceba680-de93-11e8-8859-e75e14d0297a.PNG)

**Comment by willgorham** [comment]
This is most definitely your theme, not default WooCommerce behavior.

**Comment by co50** [comment]
WOW, you're right sir. Never thought my theme - one of the more popular ones - would make such a bonehead layout error. My apologies.
