### ISSUE TITLE
the square plugin is not working failed 

### ISSUE THREAD

**Issue by pha1000** [woocommerce/woocommerce#21806]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
`
### WordPress Environment ###

Home URL: https://stesee.com
Site URL: https://stesee.com
WC Version: 3.5.1
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.32 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.0.2p

SUHOSIN Installed: –
MySQL Version: 5.6.41-84.1
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.1
WC Database Prefix: _IZU_
MaxMind GeoIP Database: ✔
Total Database Size: 8.27MB
Database Data Size: 8.01MB
Database Index Size: 0.26MB
_IZU_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB
_IZU_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
_IZU_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
_IZU_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
_IZU_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
_IZU_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
_IZU_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
_IZU_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
_IZU_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
_IZU_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
_IZU_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
_IZU_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
_IZU_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
_IZU_woocommerce_log: Data: 0.00MB + Index: 0.00MB
_IZU_commentmeta: Data: 0.00MB + Index: 0.01MB
_IZU_comments: Data: 0.00MB + Index: 0.01MB
_IZU_links: Data: 0.00MB + Index: 0.00MB
_IZU_options: Data: 7.73MB + Index: 0.09MB
_IZU_postmeta: Data: 0.13MB + Index: 0.06MB
_IZU_posts: Data: 0.13MB + Index: 0.03MB
_IZU_termmeta: Data: 0.00MB + Index: 0.01MB
_IZU_terms: Data: 0.00MB + Index: 0.01MB
_IZU_term_relationships: Data: 0.00MB + Index: 0.01MB
_IZU_term_taxonomy: Data: 0.00MB + Index: 0.00MB
_IZU_usermeta: Data: 0.01MB + Index: 0.01MB
_IZU_users: Data: 0.00MB + Index: 0.01MB
_IZU_wc_download_log: Data: 0.00MB + Index: 0.00MB
_IZU_wc_webhooks: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

amn_wpforms-lite: 2
attachment: 16
feedback: 2
jetpack_migration: 2
jp_img_sitemap: 3
jp_sitemap: 3
jp_sitemap_master: 3
nav_menu_item: 6
oembed_cache: 1
page: 12
pf_contact: 1
post: 2
product: 4
revision: 25
shop_coupon: 3
shop_order: 3
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

Akismet Anti-Spam: by Automattic – 4.0.8
Jetpack by WordPress.com: by Automattic – 6.6.1
MOJO Marketplace: by Mike Hansen – 1.3.4
OptinMonster API: by OptinMonster Team – 1.5.1
Free & Simple Contact Form Plugin - Pirateforms: by WPForms – 2.5
Orbit Fox Companion: by Themeisle – 2.6.3
WooCommerce Services: by Automattic – 1.17.1
WooCommerce Square: by WooCommerce – 1.0.33
WooCommerce: by Automattic – 3.5.1
WPForms Lite: by WPForms – 1.4.9

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #9 - /terms-2/

### Theme ###

Name: ZBlackbeard
Version: 1.0.10
Author URL: https://themeisle.com
Child Theme: ✔
Parent Theme Name: Zerif Lite
Parent Theme Version: 1.8.5.47
Parent Theme Author URL: https://themeisle.com
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: –
Array
(
[0] => stdClass Object
(
[category] => AUTHENTICATION_ERROR
[code] => UNAUTHORIZED
[detail] => This request could not be authorized.
)

)
Order status changed from Pending payment to Failed.

`

**Comment by rodrigoprimo** [comment]
Closing as no description was provided. Please open another issue following the bug report template and providing detailed instructions on how to reproduce the problem. Please keep in mind that this repository is used only for WooCommerce core problems.

**Comment by pha1000** [comment]
Thanks ,  reloading the square app
Solved the issue 

Thomas V Elia RPh
