### ISSUE TITLE
Cash on delivery fee is not applied to failed orders

### ISSUE THREAD

**Issue by pavelekNET** [woocommerce/woocommerce#21805]
**Describe the bug**
When I choose as payment method for example PayPal and the payment is marked as failed then customer is allowed to pay for the order again (url checkout/order-pay/{order_number}). If customer choose "Cash on Delivery" payment method that includes fee, no fee is applied.

**To Reproduce**
1. Set fee for "Cash on Delivery" payment method
2. Go to checkout
3. Choose payment method PayPal and create the order
4. Cancel the payment
5. Click on "Pay for order" button
6. Choose "Cash on Delivery"

**Screenshots**
selected "Cash on delivery" on checkout page that calculate with fee:
https://ibb.co/gJQFNf

step 6 (no fee is included):
https://ibb.co/d3F4F0

**Expected behavior**
When customer select payment method "Cash on Delivery" or other payment method that contains fee, the fee will be included in the total order price

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
`
### WordPress Environment ###

Home URL: http://sandbox.itemy.cz
Site URL: http://sandbox.itemy.cz
WC Version: 3.5.1
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: cs_CZ
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.27 - Doporučujeme používat verzi PHP 7.2 nebo vyšší pro nejlepší výkonnost a zabezpečení. Jak aktualizovat verzi PHP
PHP Post Max Size: 40 MB
PHP Time Limit: 120
PHP Max Input Vars: 30000
cURL Version: 7.45.0
OpenSSL/1.0.2n

SUHOSIN Installed: –
MySQL Version: 5.7.21
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.1
WC Database Prefix: itemy_
MaxMind GeoIP Database: ✔
Celková velikost databáze: 63.61MB
Velikost dat databáze: 51.34MB
Velikost indexu databáze: 12.27MB
itemy_woocommerce_sessions: Data: 0.02MB + index: 0.00MB
itemy_woocommerce_api_keys: Data: 0.00MB + index: 0.01MB
itemy_woocommerce_attribute_taxonomies: Data: 0.00MB + index: 0.00MB
itemy_woocommerce_downloadable_product_permissions: Data: 0.00MB + index: 0.00MB
itemy_woocommerce_order_items: Data: 0.15MB + index: 0.11MB
itemy_woocommerce_order_itemmeta: Data: 1.03MB + index: 0.94MB
itemy_woocommerce_tax_rates: Data: 0.00MB + index: 0.01MB
itemy_woocommerce_tax_rate_locations: Data: 0.00MB + index: 0.00MB
itemy_woocommerce_shipping_zones: Data: 0.00MB + index: 0.00MB
itemy_woocommerce_shipping_zone_locations: Data: 0.00MB + index: 0.00MB
itemy_woocommerce_shipping_zone_methods: Data: 0.00MB + index: 0.00MB
itemy_woocommerce_payment_tokens: Data: 0.00MB + index: 0.00MB
itemy_woocommerce_payment_tokenmeta: Data: 0.00MB + index: 0.00MB
itemy_woocommerce_log: Data: 0.00MB + index: 0.00MB
itemy_atum_order_itemmeta: Data: 0.02MB + index: 0.03MB
itemy_atum_order_items: Data: 0.02MB + index: 0.02MB
itemy_aws_index: Data: 0.00MB + index: 0.00MB
itemy_commentmeta: Data: 0.00MB + index: 0.01MB
itemy_comments: Data: 0.25MB + index: 0.12MB
itemy_gopay_inline_log: Data: 0.20MB + index: 0.00MB
itemy_links: Data: 0.00MB + index: 0.00MB
itemy_napostu: Data: 0.60MB + index: 0.03MB
itemy_newsletter: Data: 0.00MB + index: 0.00MB
itemy_newsletter_emails: Data: 0.00MB + index: 0.00MB
itemy_newsletter_sent: Data: 0.00MB + index: 0.00MB
itemy_newsletter_stats: Data: 0.00MB + index: 0.00MB
itemy_options: Data: 8.95MB + index: 2.87MB
itemy_postmeta: Data: 14.14MB + index: 5.10MB
itemy_posts: Data: 7.31MB + index: 0.63MB
itemy_redirection_404: Data: 2.18MB + index: 0.68MB
itemy_redirection_groups: Data: 0.00MB + index: 0.00MB
itemy_redirection_items: Data: 0.00MB + index: 0.01MB
itemy_redirection_logs: Data: 0.00MB + index: 0.01MB
itemy_revslider_css: Data: 0.13MB + index: 0.00MB
itemy_revslider_layer_animations: Data: 0.02MB + index: 0.00MB
itemy_revslider_navigations: Data: 0.02MB + index: 0.00MB
itemy_revslider_sliders: Data: 0.05MB + index: 0.00MB
itemy_revslider_slides: Data: 0.13MB + index: 0.00MB
itemy_revslider_static_slides: Data: 0.02MB + index: 0.00MB
itemy_termmeta: Data: 0.10MB + index: 0.08MB
itemy_terms: Data: 0.04MB + index: 0.08MB
itemy_term_relationships: Data: 0.13MB + index: 0.29MB
itemy_term_taxonomy: Data: 0.05MB + index: 0.05MB
itemy_usermeta: Data: 0.50MB + index: 0.33MB
itemy_users: Data: 0.03MB + index: 0.03MB
itemy_wc_download_log: Data: 0.02MB + index: 0.03MB
itemy_wc_points_rewards_user_points: Data: 0.02MB + index: 0.03MB
itemy_wc_points_rewards_user_points_log: Data: 0.02MB + index: 0.05MB
itemy_wc_webhooks: Data: 0.02MB + index: 0.02MB
itemy_woocommerce_bundled_itemmeta: Data: 0.02MB + index: 0.03MB
itemy_woocommerce_bundled_items: Data: 0.02MB + index: 0.03MB
itemy_woof_query_cache: Data: 0.13MB + index: 0.14MB
itemy_woof_stat_buffer: Data: 0.02MB + index: 0.00MB
itemy_woof_stat_tmp: Data: 0.02MB + index: 0.00MB
itemy_wpml_mails: Data: 14.59MB + index: 0.02MB
itemy_wpmm_subscribers: Data: 0.00MB + index: 0.00MB
itemy_yith_wcwl: Data: 0.02MB + index: 0.02MB
itemy_yith_wcwl_lists: Data: 0.02MB + index: 0.03MB
wp_commentmeta: Data: 0.02MB + index: 0.03MB
wp_comments: Data: 0.02MB + index: 0.08MB
wp_links: Data: 0.02MB + index: 0.02MB
wp_options: Data: 0.11MB + index: 0.02MB
wp_postmeta: Data: 0.02MB + index: 0.03MB
wp_posts: Data: 0.02MB + index: 0.06MB
wp_termmeta: Data: 0.02MB + index: 0.03MB
wp_terms: Data: 0.02MB + index: 0.03MB
wp_term_relationships: Data: 0.02MB + index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + index: 0.03MB
wp_usermeta: Data: 0.02MB + index: 0.03MB
wp_users: Data: 0.02MB + index: 0.05MB

### Post Type Counts ###

amn_smtp: 1
attachment: 2875
custom_css: 7
customize_changeset: 14
home_slider: 1
it_epoll_poll: 1
jetpack_migration: 2
mc4wp-form: 2
ml-slide: 2
ml-slider: 1
nav_menu_item: 29
nectar_slider: 7
page: 24
post: 1
product: 681
product_variation: 164
revision: 357
shop_coupon: 8
shop_order: 23
shop_order_refund: 7
static_block: 3
wcps: 2
wpcf7_contact_form: 1
ywar_reviews: 1

### Security ###

Secure connection (HTTPS): ❌
					Váš obchod nepoužívá HTTPS. Zjistěte více o HTTPS a SSL certifikátech.
Hide errors from visitors: ❌Chybová hlášení by neměla být zobrazována návštěvníkům.

### Active Plugins (45) ###

Redux Framework: o Tým Redux – 3.6.14
Antispam Bee: o pluginkollektiv – 2.9.0
České služby pro WordPress: o Pavel Hejn – 0.6-alpha
Contact Form 7: o Takayuki Miyoshi – 5.0.5
Custom Order Status for WooCommerce: o Algoritmika Ltd – 1.4.5
Electro Extensions: o MadrasThemes – 2.0.10 – Nebylo testováno s aktivní verzí WooCommerce
Envato Market: o Envato – 2.0.1
Facebook for WooCommerce: o Facebook – 1.9.6 – Nebylo testováno s aktivní verzí WooCommerce
Favicon by RealFaviconGenerator: o Philippe Bernard – 1.3.13
Feed Them Social (Facebook, Instagram, Twitter, etc): o SlickRemix – 2.5.9
Social Login Buttons by Heateor: o Team Heateor – 1.1.2
WPBakery Page Builder: o Michael M - WPBakery.com – 5.5.2
Loco Translate: o Tim Whitlock – 2.1.5
MailChimp for WordPress: o ibericode – 4.2.5
Mobile Address Bar Changer: o Anshul Labs – 3.0
Redirection: o John Godley – 3.6.1
Regenerate Thumbnails: o Alex Mills (Viper007Bond) – 3.0.2
Slider Revolution: o ThemePunch – 5.4.8
Shortcode in Menus: o Gagan Deep Singh – 3.4
Super Socializer: o Team Heateor – 7.12.2
UpdraftPlus - Backup/Restore: o UpdraftPlus.Com
DavidAnderson – 1.15.3

User Shortcodes Plus: o Kyle B. Johnson – 2.0.1
Woo Custom Stock Status: o Softound Solutions – 1.1.1 – Nebylo testováno s aktivní verzí WooCommerce
Woo Doprava: o Vladislav Musílek – 1.5.6 – Nebylo testováno s aktivní verzí WooCommerce
Woo Fakturoid: o Vladislav Musílek – 1.4.6 – Nebylo testováno s aktivní verzí WooCommerce
Woo GoPay Inline: o Vladislav Musílek – 1.6.3 – Nebylo testováno s aktivní verzí WooCommerce
Woo Na Poštu: o Vladislav Musílek – 1.1.5 – Nebylo testováno s aktivní verzí WooCommerce
Woo Sledování: o Vladislav Musílek – 1.1.7 – Nebylo testováno s aktivní verzí WooCommerce
WooCommerce AJAX Cart: o Moises Heberle
Alex Szilagyi (contributor) – 1.2.6 – Nebylo testováno s aktivní verzí WooCommerce

WooCommerce Auto Restore Stock: o Gerhard Potgieter – 1.0.1 – Nebylo testováno s aktivní verzí WooCommerce
WooCommerce Cart popup premium: o XootiX – 1.3 – Nebylo testováno s aktivní verzí WooCommerce
WooCommerce Cost of Goods: o SkyVerge – 2.8.1
WooCommerce Currency Switcher: o realmag777 – 1.2.6
WooCommerce AdWords Conversion Tracking: o Wolf+Bär Agency – 1.4.12 – Nebylo testováno s aktivní verzí WooCommerce
WooCommerce Points and Rewards: o WooCommerce – 1.6.15
WooCommerce Product Bundles: o SomewhereWarm – 5.8.0
WooCommerce Product Stock Alert: o WC Marketplace
The Grey Parrots – 1.5.1 – Nebylo testováno s aktivní verzí WooCommerce

WOOF - WooCommerce Products Filter: o realmag777 – 2.2.2
WooCommerce Stock Manager: o Vladislav Musílek – 1.2.7 – Nebylo testováno s aktivní verzí WooCommerce
Woocommerce Zásilkovna: o Vladislav Musílek – 1.6.1 – Nebylo testováno s aktivní verzí WooCommerce
WooCommerce: o Automattic – 3.5.1
WP Log Viewer: o Maxwell Berkel – 1.2.1
WP Mail Logging: o Christian Zöller – 1.8.5
WP Mail SMTP: o WPForms – 1.3.3
WP Maintenance Mode: o Designmodo – 2.2.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: CZK ( Kč)
Currency Position: left
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Obchod: #7 - /shop/
Košík: #8 - /cart/
Pokladna: #1734 - /doprava-a-platba/
Můj účet: ❌ Stránka neobsahuje shortcode.
Obchodní podmínky: #1738 - /obchodni-podminky/

### Theme ###

Name: Electro Child
Version: 1.4.21
Author URL: https://madrasthemes.com/
Child Theme: ✔
Parent Theme Name: Electro
Parent Theme Version: 2.2.1
Parent Theme Author URL: https://madrasthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: electro/woocommerce/archive-product.php
electro-child/woocommerce/emails/customer-on-hold-order.php
electro-child/woocommerce/emails/customer-processing-order.php
electro/woocommerce/global/quantity-input.php

### Product Bundles ###

Database Version: 5.8.0
Template Overrides: –
`

**Comment by kloon** [comment]
I am unable to replicate this, if the order fails and I select to pay it again via my-account the COD Delivery shipping option is selected with the correct shipping value, and I can select COD payment option.

Unless you are talking about a different fee, in which case I am not where it is coming from since WooCommerce does allow the option out of the box to add a fee to a payment method. Out of the box COD only has the option to limit certain shipping methods to be selected when you select COD, which is what I tested and demonstrated with my screenshot, and that works as it should.

Please test by disabling all plugins except WooCommerce and switching your theme to a default one like Twentyseventeen or Storefront.

Closing as I am unable to replicate, if you can provide steps to replicate with a default theme and all plugins disabled I will gladly reopen and debug further.
