### ISSUE TITLE
Setup Wizard: Needs accessibility improvements

### ISSUE THREAD

**Issue by claudiosanches** [woocommerce/woocommerce#21814]
**Describe the bug**

Currently it's not possible to go to all steps on the setup wizard using only `tab`, for example not possible to setup offline payments using `tab` and `space` keys.

**To Reproduce**
1. Go to the Setup Wizard
2. Try navigate without our mouse there.
3. Try enable and disable everything there using `space`.

**Expected behavior**

Should allow enable and disable everything using `space`, and you should hit any option using `tab`.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@claudiosanches The reason for the issue with the offline payments is that the checkbox is hidden and overlayed with a non-focusable but clickable element. Can we get some feedback from UI/Accessibility folks on how to best address this?

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/22936
