### ISSUE TITLE
 Bug search product in a order

### ISSUE THREAD

**Issue by M1ckael** [woocommerce/woocommerce#21811]
hi,
If you add a new order and you search a product, the stock statu are always "in stock" !!

I creat a new order in the admin panel .
I click on button add product.
I search a product with this name and after a few seconde the result appear.
But all product are "In-Stock" Hummm

I don't have all in stock. why the search display "In stock" ?

**Comment by M1ckael** [comment]
![sans-titre-1](https://user-images.githubusercontent.com/14013881/48112669-c29e8180-e257-11e8-8e2e-f9aebdce6e92.jpg)

**Comment by kloon** [comment]
I am unable to replicate, if I have no stock it shows 0 stock http://cld.wthms.co/aXwpi6

Can you please test with all plugins except WooCommerce disabled and also with a default theme enabled like Twentyseventeen or Storefront.

I will reopen if you can provide step by step instructions on how to replicate as my own tests does not seem to deliver the same results as yours.

**Comment by M1ckael** [comment]
Hi , thank's for your reply.
I have disabled all plugin and add StoreFont and the  problem are here.
`
### WordPress Environment ###

WC Version: 3.5.1
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache/2.2
PHP Version: 7.0.29 - Nous recommandons d’utiliser PHP 7.2 ou supérieur pour optimiser les performances et la sécurité. Comment mettre à jour votre version de PHP ?
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 10000
cURL Version: 7.38.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.13-MariaDB-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.1
WC Database Prefix: prpdev_
MaxMind GeoIP Database: ✔
Taille totale de la base de données: 21.78MB
Taille de la base de données: 16.21MB
Taille de l’index: 5.57MB


### Post Type Counts ###

attachment: 1554
customize_changeset: 2
nav_menu_item: 95
page: 21
post: 2
product: 476
product_variation: 3
revision: 65
shop_coupon: 1
shop_order: 21
ticket: 2
ticket_history: 3
ticket_reply: 1
wpforms: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: par Automattic – 3.5.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Base de la boutique: #13 - /boutique/
Panier: #19 - /panier/
Validation de la commande: #20 - /commande/
Mon compte: #21 - /mon-compte/
