### ISSUE TITLE
[3.5] REST API regression when querying by customer

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#21823]
**Describe the bug**
When querying orders (seems to affect any post object though) by customer, results are no longer scoped to the provided customer ID. The `'customer'` param is listed as the [preferred way to limit the returned results](https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-orders), yet this param no longer works. 

Note that this _does_ work if using `'customer_id'` instead, which is not documented, and the previous 
(and documented) behavior should be maintained.

**To Reproduce**
1. Using WooCommerce 3.4.x, make a request to the `wc/v2` endpoint for orders, using a customer ID to limit the returned objects to orders from that customer.
   - [ ] Note that the results return orders only for that customer, as expected.
1. Using WooCommerce 3.5.1, make a request to `wc/v2` endpoint for orders using the `'customer'` param again.
   - [ ] See that the response does not filter orders by the customer.

**Expected behavior**

The REST API should not break between WooCommerce versions.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

-----

A quick note that WC 3.5 also broke querying by `'customer'` for user memberships via REST API v2, and given both the Memberships API and orders API extend the posts controller, my best guess is that the issue is somewhere in the post controller or the classes it extends (potentially with the flip flopping between querying for post author vs `_customer_user` meta), but I haven't been able to narrow this down.

**Comment by claudiosanches** [comment]
Not able to reproduce it on WooCommerce 3.5.1.

Testing with `wp-json/wc/v2/orders?customer=4`, also works for guests using `wp-json/wc/v3/orders?customer=0`.
Maybe some related to 3.5, since we made a few changes about `post_author` on orders, but we reverted it on 3.5.1.
Also @rodrigoprimo have tried to reproduce it with no success.

**Comment by bekarice** [comment]
@claudiosanches thanks for the doublecheck here, looks like indeed 3.5.1 is fine, misread on my part of the merchant status while working on their site. sorry for the false alarm!
