### ISSUE TITLE
Conflicting same filter hook on 2 different "my-account" templates

### ISSUE THREAD

**Issue by lomars** [woocommerce/woocommerce#21828]
The filter hook `woocommerce_lost_password_message` located on 2 different templates in "my-account" subfolder, is filtering 2 different text contents. So it's not possible to use it just to make changes on one template. 

The related templates are:

1) On the template `my-account/form-lost-password.php` (version 3.4.0) at line 24 we have:

`<p><?php echo apply_filters( 'woocommerce_lost_password_message', esc_html__( 'Lost your password? Please enter your username or email address. You will receive a link to create a new password via email.', 'woocommerce' ) ); ?></p><?php // @codingStandardsIgnoreLine ?>`

2) On the template `myaccount/lost-password-confirmation.php.` (version 3.5.0) at line 25 we have:

`<p><?php echo esc_html( apply_filters( 'woocommerce_lost_password_message', __( 'A password reset email has been sent to the email address on file for your account, but may take several minutes to show up in your inbox. Please wait at least 10 minutes before attempting another reset.', 'woocommerce' ) ) ); ?></p>`

> The filter hook should be renamed `woocommerce_lost_password_confirmation_message` on this last template .

**Comment by kloon** [comment]
see #21829 for fix.
