### ISSUE TITLE
Regression - Order rows not selectable in WooCommerce 3.5.1

### ISSUE THREAD

**Issue by ben72** [woocommerce/woocommerce#21837]
I updated WooCommerce 3.4.5->3.5.0 and now I can’t select rows on orders in backend. Before when clicking a row the background turned pink and the buttons Increase stock and Decrease stock appeared. This was a really good feature. Is it gone by purpose or is this a fault?
I don't see any mention of changes to this behavior in the changelog. Was the feature dropped by accident or on purpose?

**To Reproduce**
1. Make a new order.
2. Go edit the order.
3. Try to highlight an order row.
This is not possible in WooCommerce 3.5.1 but it was possible in 3.4.5!

**Video**
https://www.useloom.com/share/49cfdf78527b4ed6b0e24281f2803e18

**Expected behavior**
It should work as before, it was a great feature!
Examples of usage:
1. When picking the order it was a way to keep track of progress.
2. Put a returned item back into stock when for instance changing to another size and get the action logged at the same time.
3. Remove an item from stock if replacing a faulty item and get the action logged at the same time.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: http://bentrix.com/test1
Site URL: http://bentrix.com/test1
WC Version: 3.5.1
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.11
PHP Post Max Size: 50 MB
PHP Time Limit: 120
PHP Max Input Vars: 50000
cURL Version: 7.60.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.39-cll-lve
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.1
WC Database Prefix: wpx1_
MaxMind GeoIP Database: ✔
Total Database Size: 0.56MB
Database Data Size: 0.46MB
Database Index Size: 0.10MB
wpx1_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB
wpx1_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wpx1_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wpx1_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wpx1_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wpx1_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wpx1_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wpx1_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wpx1_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wpx1_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wpx1_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wpx1_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wpx1_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wpx1_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wpx1_commentmeta: Data: 0.00MB + Index: 0.00MB
wpx1_comments: Data: 0.00MB + Index: 0.01MB
wpx1_links: Data: 0.00MB + Index: 0.00MB
wpx1_options: Data: 0.44MB + Index: 0.03MB
wpx1_postmeta: Data: 0.01MB + Index: 0.01MB
wpx1_posts: Data: 0.01MB + Index: 0.01MB
wpx1_termmeta: Data: 0.00MB + Index: 0.01MB
wpx1_terms: Data: 0.00MB + Index: 0.01MB
wpx1_term_relationships: Data: 0.00MB + Index: 0.00MB
wpx1_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wpx1_usermeta: Data: 0.00MB + Index: 0.01MB
wpx1_users: Data: 0.00MB + Index: 0.01MB
wpx1_wc_download_log: Data: 0.00MB + Index: 0.00MB
wpx1_wc_webhooks: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

page: 6
post: 2
product: 1
shop_order: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.5.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: SEK (kr)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
````
</details>

First reported here: https://wordpress.org/support/topic/regression-cant-select-order-rows/#post-10854033

**Comment by rekkitatu** [comment]
We were also using this feature a lot. The feature was present up to WC version 3.4.7 but is gone now after 3.5.0 and later. I really hope this gets added back quickly.

**Comment by rekkitatu** [comment]
8261cffaa7aa69846f7f32d25e73117bae2ad25c it was this commit that dropped the support for increasing and reducing the stock when editing the order items. What was the intented purpose of this change @mikejolley 

Could this feature be returned?

**Comment by kloon** [comment]
Curious to know how you have been using the options previously? Was it just to decrease stock when handling manual orders?

The reason the buttons were removed was due to the new automatic stock handling that was introduced in the admin area, which was previously not present hence the buttons. So now if you create manual orders you need to follow the order statuses and once processing or completed the stock will automatically be reduced, and when you refund the stock will be restored again.

**Comment by kloon** [comment]
Closing as there is already an open issue where we can continue discussing #21754

**Comment by ben72** [comment]
@kloon Please see "Examples of usage" in my original report. I never do manual orders.

The most useful thing with selecting order rows is when picking orders to know where you are. Like yesterday picking 62 items in one order. Just restoring the order to select/deselect rows would be great! The buttons are secondary to me but useful at times. For instance when a customer should pre-pay an order but cancels and I need to get all back in stock but not refund as nothing was paid.
