### ISSUE TITLE
Countries Shown In Address

### ISSUE THREAD

**Issue by danpastori** [woocommerce/woocommerce#21857]
## Bug Description
After we updated to Woocommerce 3.5.1, the country is being displayed on all of the emails where we export a formatted address (both shipping and billing). We have our store set to US:IL which is in Illinois in the United States. This means that any customer that orders a product from our store should not have the country listed in the formatted address.

## To Reproduce
Send any email where the method `get_formatted_address()` is used in a partial.

## Where the Issue Lies
In Woocommerce 3.5.1 there's a method in the `/includes/class-wc-countries.php` on line 524. In that method, on line 550 it determines whether we should show the country in the formatted address or not. This is based of of the store location. The part of the method is here:
```
// Country is not needed if the same as base.
		if ( $country === $this->get_base_country() && ! apply_filters( 'woocommerce_formatted_address_force_country_display', true ) ) {
			$format = str_replace( '{country}', '', $format );
		}
```
We haven't updated anything on our end, but the country is now appearing in all formatted addresses.

## Expected behavior
The country should not appear on any receipt for anyone who orders an item in the United States. 

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**Comment by claudiulodro** [comment]
Fixed in either #21865 or #21933. If you have preference for either of those specific behaviors please leave a comment at the appropriate pull request.
