### ISSUE TITLE
Undefined index: priority ... includes/wc-core-functions.php on line 1526

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#21851]
**Describe the bug**
Notice is being thrown:
```
PHP Notice:  Undefined index: priority in .../woocommerce/includes/wc-core-functions.php on line 1526
```
This is happening [in this chunk](https://github.com/woocommerce/woocommerce/blob/3.5.1/includes/wc-core-functions.php#L1517-L1542), and is due to [this chunk of code](https://github.com/woocommerce/woocommerce/blob/3.5.1/includes/class-wc-checkout.php#L224-L246). The account fields are not being created with a priority, so they get the index notice when trying to sort by it. 

```
    [account] => Array
        (
            [account_username] => Array
                (
                    [type] => text
                    [label] => Account username
                    [required] => 1
                    [placeholder] => Username
                )

            [account_password] => Array
                (
                    [type] => password
                    [label] => Create account password
                    [required] => 1
                    [placeholder] => Password
                )

        )
```

**To Reproduce**
1. Make sure debugging/logging is on
1. Add item to cart
1. Go to checkout
1. View log

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by claudiulodro** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/21801
