### ISSUE TITLE
Emailing Order Invoice in Plain Text Results in 500 Error

### ISSUE THREAD

**Issue by druesome** [woocommerce/woocommerce#21863]
**Describe the bug**
Sending an invoice to a customer in Plain Text format via "Order actions" > "Email invoice / order details to customer" results in a 500 error.

**To Reproduce**
1. In wp-admin, go to WooCommerce > Settings > Emails tab
2. Click on "Customer invoice / Order details"
3. Make sure "Plain text" is selected under "Email type"
4. Go to WooCommerce > Orders
5. Click on any existing order
6. On the right sidebar, under "Order actions", select "Email invoice / order details to customer"
7. Click the right arrow button to send.

**Screenshots**
<img src="http://cld.wthms.co/gRQm6y+" width="600" />

**Expected behavior**
I expected the invoice to be sent without errors.

**Actual behavior**
Invoice is not sent.  Instead I am met with this error:

`Using $this when not in object context in /wpcom-141992377/wp-content/plugins/woocommerce/templates/emails/plain/customer-invoice.php:37`

Line 37 looks like:

`echo sprintf( esc_html__( 'Here are the details of your order placed on %s:', 'woocommerce' ), esc_html( wc_format_datetime( $this->object->get_date_created() ) ) ) . "\n\n";`

Switching `$this->object->get_date_created()` to `$order->get_date_created()` resolves the issue.

**Notes**
Error happened on two test sites hosted on Hostgator and WordPress.com.  The issue does not happen when invoice is sent in HTML format.

Thank you!

**Comment by kloon** [comment]
See #21882 for fix.
