### ISSUE TITLE
Order Detail Page - Item highlight missing in v3.5.1

### ISSUE THREAD

**Issue by theprofessor101** [woocommerce/woocommerce#21866]
## Steps to reproduce the issue

Previous to v3.5.1, on the Order Detail Page you could click on an item row and the row would become highlighted.

This was very helpful as we picked orders. Once an item was placed in the box, the picker would highlight the row and move onto the next item. It was a fail-safe method to ensure each item was picked and nothing missed on the order. Very helpful for long orders.

With v3.5.1 the ability to highlight a row is no longer functional.

## Expected/actual behavior

I was expecting when I click on an item row that the row would become highlighted.

**Comment by kloon** [comment]
Ties in with #21754, this was part of the stock reduction/increment functionality. Closing this in favor of that issue.
