### ISSUE TITLE
Twenty Nineteen could use some styling love.

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#21868]
Reported here https://github.com/WordPress/twentynineteen/issues/484, things are not looking too nice on the next default WordPress theme.

Here's an example for what was done on twenty-sixteen: https://github.com/woocommerce/woocommerce/commit/d88ba80f844619aea791b05c8719c0c672ff8910#diff-6dc35feb54bb1cfdd2e3e847f6dd77cc

**Comment by kloon** [comment]
This is on our todo list, we have not tested with Twentynineteen yet.

**Comment by WPprodigy** [comment]
Fwiw, it is probably best to wait a little while, as things like https://github.com/WordPress/twentynineteen/issues/460 can have a big impact.

**Comment by kloon** [comment]
See #21970
