### ISSUE TITLE
Woocommerce 3.5.0+ showing HTML in product titles

### ISSUE THREAD

**Issue by phyx1u5** [woocommerce/woocommerce#21878]
**Describe the bug**

My site is in English and Thai so I have the need to include both in my product title, and I style the thai words with a custom font using a span element. I also have css icons in some of my product titles as well.
The problem started when I upgraded from 3.4.7 to 3.5.0 I immediately noticed that in certain areas the HTML in the product title was clearly visible. This makes it unsightly to the customer as they are seeing a whole bunch of gibberish. However when I roll back to 3.4.7 the problem goes away. 
Now I am basically stuck because I want to upgrade my WC but i cant because it breaks my product titles, so I am currently stuck using 3.4.7 unless someone has a quick fix that I can implement.
All help is greatly appreciated, thanks in advance.

**To Reproduce**
1. update WooCommerce to 3.5.0+
2. create new product
3. Put HTML in title
4. Checkout
5. View order in wp-admin
6. notice HTML is visible in product title (see screenshot attached)
7. Roll back to WooCommerce 3.4.7
8. go back to order in wp-admin
9. notice HTML no longer visible in product title (see screenshot attached)

(interestingly if you place an order in 3.4.7 then upgrade to 3.5.0+ the product title continues to not show HTML)

**Screenshots**
attached showing order details in WC 3.5.1 and then rollback to WC 3.4.7. Note the difference in Product title. The screenshots are taken from a live order on a staged site.
![order-wc-3 5 1](https://user-images.githubusercontent.com/44924644/48303898-2b7d4680-e543-11e8-80ee-ea743d9e32ff.jpg)
![order-wc-3 4 7](https://user-images.githubusercontent.com/44924644/48303900-2d470a00-e543-11e8-8a97-cc6f3ce95c99.jpg)

**Expected behavior**
The product title should be like in WooCommerce 3.4.7 where HTML is not visible in Product Title

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://tropicalplantation.co
Site URL: https://tropicalplantation.co
WC Version: 3.5.1
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.38 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.59.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.40-84.0-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.1
WC Database Prefix: tp01_
MaxMind GeoIP Database: ✔
Total Database Size: 3.74MB
Database Data Size: 2.77MB
Database Index Size: 0.97MB
tp01_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
tp01_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
tp01_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
tp01_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
tp01_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
tp01_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
tp01_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
tp01_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
tp01_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
tp01_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
tp01_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
tp01_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
tp01_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
tp01_woocommerce_log: Data: 0.02MB + Index: 0.02MB
tp01_commentmeta: Data: 0.02MB + Index: 0.03MB
tp01_comments: Data: 0.02MB + Index: 0.09MB
tp01_links: Data: 0.02MB + Index: 0.02MB
tp01_loginizer_logs: Data: 0.00MB + Index: 0.01MB
tp01_options: Data: 2.05MB + Index: 0.05MB
tp01_postmeta: Data: 0.09MB + Index: 0.09MB
tp01_posts: Data: 0.05MB + Index: 0.06MB
tp01_social_users: Data: 0.02MB + Index: 0.02MB
tp01_termmeta: Data: 0.02MB + Index: 0.03MB
tp01_terms: Data: 0.02MB + Index: 0.03MB
tp01_term_relationships: Data: 0.02MB + Index: 0.02MB
tp01_term_taxonomy: Data: 0.02MB + Index: 0.03MB
tp01_usermeta: Data: 0.02MB + Index: 0.03MB
tp01_users: Data: 0.02MB + Index: 0.05MB
tp01_wc_download_log: Data: 0.02MB + Index: 0.03MB
tp01_wc_point_of_sale_cache: Data: 0.02MB + Index: 0.00MB
tp01_wc_point_of_sale_sale_reports: Data: 0.00MB + Index: 0.00MB
tp01_wc_poin_of_sale_tabs: Data: 0.02MB + Index: 0.00MB
tp01_wc_poin_of_sale_tabs_meta: Data: 0.02MB + Index: 0.00MB
tp01_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 16
customize_changeset: 1
jetpack_migration: 2
jp_sitemap: 1
jp_sitemap_master: 1
page: 6
pos_temp_register_or: 1
post: 2
product: 12
revision: 2
shop_order: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Loginizer: by Raj Kothari – 1.4.0
SG Optimizer: by SiteGround – 4.0.7
WooCommerce: by Automattic – 3.5.1
WP Rollback: by WordImpress – 1.5.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: THB (฿)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by dariovar** [comment]
Same issue here…
Worst release ever!

**Comment by phyx1u5** [comment]
> Same issue here…
> I have downgraded the WooCommerce version, but many issue with database.
> In addition, using Subscriptions plug-in mixed with PayPal Standard Payment gateway, WooCommerce creates a double order!!!
> Please, give us a solution ASAP.
> Thanks!

Hi dariovar I feel your frustration and would highly suggest you start a new thread including all the info required such as steps to repeat and screenshots etc, so that the devs have more info to be able to respond to your issues.
As for the fix, try rolling back to WC 3.4.7 for now, that seems to be working for me. However an actual fix would be much appreciated.

**Comment by dariovar** [comment]
I follow your steps:
in table wp_woocommerce_order_items = product name as HTML
in table wp_posts = product name as HTML
in table wp_woocommerce_order_itemmeta = product name as text + " &times; 1"

**Comment by phyx1u5** [comment]
@Michaelh818 I have followed your steps but the problem persists. 3.5.0 is pulling the entire HTML data from the databse where as 3.4.7 seems to be excluding the HTML data

**Comment by claudiulodro** [comment]
Patch in https://github.com/woocommerce/woocommerce/pull/21936 for WC 3.5.2
