### ISSUE TITLE
Add billing address field ABN/VAT Number

### ISSUE THREAD

**Issue by galbaras** [woocommerce/woocommerce#21876]
**Is your feature request related to a problem? Please describe.**
When selling to companies in Australia, the company ID, called ABN (Australian Business Number), is sometimes required during checkout and/or order processing. Adding it as a custom field requires several filters and mostly includes it in the wrong place and/or format.

I imagine this is also the case with EU VAT Number, NZ NZBN and others.

**Describe the solution you'd like**
Cater for a company identifier field within the normal handling of billing addresses, allow store admins to enable it and allow them to change its title.

**Describe alternatives you've considered**
Using custom fields, whether through filters/actions or plugins.

**Additional context**
This field should always follow "Company" and be handled similarly, e.g. skipped if empty in emails.

**Comment by kloon** [comment]
This is not something every store needs and as such we do not include it as part of the core software. There are tutorials available online that shows you how to add the field, we also have a premium extension available that adds the required functionality for EU stores https://woocommerce.com/products/eu-vat-number/

**Comment by galbaras** [comment]
@kloon Australia is not in the EU and from what I see, the plugin doesn't actually do what I need, while doing things I don't need.

To me, WooCommerce makes assumptions about billing addresses that are too strong and doesn't provide a simple filter structure to extend or modify it. I think it's nice to charge the entire EU a bit of money for an extension, but I suspect that enough stores need to adapt their billing addresses in a consistent way to warrant support for it in core.

Actually, this will make the extension a lot easier to write for those that don't code anyway.

**Comment by galbaras** [comment]
@kloon Alternatively, can you suggest a way to output a custom billing field in a particular spot within the formatted billing address?
