### ISSUE TITLE
Incorrect rounding of multiple tax rates per location

### ISSUE THREAD

**Issue by RobertoDonPedro** [woocommerce/woocommerce#21871]
**Description of the issue**
If you have multiple tax rates per location (=tax rates have different priorities) and the tax setting is NOT set to "Round tax at subtotal level" (=round on item level), then the cart shows an incorrect product price at the second decimal place. This price is inconsistent with the subtotal- and total price shown on the same cart page (please see the screenshots).

This means, if you round on the tax rate item level for the subtotal price, then you also need to round on the tax rate item level for the product price, otherwise the prices are inconsistent.

**To Reproduce**
- Create a product priced at $79 excl. tax.
- Do exactly the same tax settings like in the screenshot
- Create a tax class with exactly the same rates and priorities like in the screenshot and apply it to the product

**Screenshots**
![rounding issues](https://user-images.githubusercontent.com/19687084/48257758-b2330600-e413-11e8-8472-7dbb6559a6d8.jpg)
![tax settings](https://user-images.githubusercontent.com/19687084/48257775-bced9b00-e413-11e8-8c1c-58d6d6919fd4.JPG)
![multiple tax rates](https://user-images.githubusercontent.com/19687084/48257781-c2e37c00-e413-11e8-8526-b8117b40fde7.JPG)

**Comment by mikejolley** [comment]
I've added a patch in https://github.com/woocommerce/woocommerce/pull/22416 thanks
