### ISSUE TITLE
Woocommerce shop manager role breaks WPBakery Page Builder roles.

### ISSUE THREAD

**Issue by phlegx** [woocommerce/woocommerce#21886]
**Describe the bug**
I use the **latest Woocommerce** version and also the **latest WPBakery Page Builder**. Like described [here (docs.woocommerce.com)](https://docs.woocommerce.com/document/roles-capabilities/) I have installed Wordpress plugin Members to give a user with role `editor` also the role `shop_manager`. For the user with roles `editor` and `shop_manager`, the WPBakery Page Builder disappear (is no more available) in edit post or page.

**To Reproduce**
1. Install WPBakery Page Builder.
2. Install Woocommerce.
3. Install Members.
4. Activate WPBakery Page Builder for role `editor`: Individually -> page and posts.
5. Go to users and edit a user with role `editor`.
6. Add additional role `shop manager` to the user with role `editor` and save it.
7. Edit a post or page -> WPBakery Page Builder is disabled! :(

**Expected behavior**
If the user with role `editor` and `shop manager` edits a post or page, WPBakery Page Builder should be activated and available because role `editor` has this capability (see step 4.). If I remove role `shop manager` from the user, all works fine like expected.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active (partially correct: I need WPBakery Page Builder and Members for this issue)
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/). -> Only Wordpress backend problem.
- [x] I can reproduce this bug consistently using the steps above and on different Website instances.

**WordPress Environment**

```
Wordpress: 4.9.8
WooCommerce-Version: 3.5.1 all green!
WPBakery Page Builder: 5.5.2
Members: 2.1.0
```

**Comment by gottschild** [comment]
I have the same issue.

**Comment by kloon** [comment]
WPBakery probably required additional capabilities to function? Perhaps reach out to the team at WPBakery and enquire what capability is required to have the menu visible? Once they provide you with that, you can use the Members plugin again and just add that capability to the shop manager role to have the menu show up.

**Comment by gottschild** [comment]
kloon, can you please reopen this ticket? Your presumption is not helpful. Last Woocommerce version and last WPBakery Page Builder (highly popular Plugins) are not compatible with user role shop manager (probably also a very popular user role). I reached out to WPBakery, but they are ignoring this issue. Thank you!

**Comment by phlegx** [comment]
Here's an update of WPBakery:

> Hi,
> Thanks for sharing. We have received reports regarding this issue from the buyers and it is already added onto our list so that it can be checked prior to the upcoming release.

So, this problem could be solved in the next release. :smile:

**Comment by gottschild** [comment]
_WPBakery Page Builder_ Version 5.6 still doesn't work with user Role _Shop Manager_

**Comment by jogoyo** [comment]
Having the same issue, where is the fix? My clients with shop manager role need ability to edit with the page builder.

**Comment by webgmclassics** [comment]
> Having the same issue, where is the fix? My clients with shop manager role need ability to edit with the page builder.

@jogoyo @gottschild @phlegx Contact WP Bakery Support. I've contacted them and got the usual run around "we'll fix this in a future release." If more people contact them, maybe they will realize the seriousness of their mistake. It has been a major disruption to our workflow. https://support.wpbakery.com/

**Comment by PauloCarrasco** [comment]
Got the same problem here. The shop manager role is configured to allow the use of the Page Builder in the Product Post Type but it doesn't work. My client has lots of products to edit and this is a vital feature for him! Please help.

WordPress 4.9.8, WooCommerce 3.5.2, WPBakery Page Builder 5.6

**Comment by Peps03** [comment]
Same problem! When is a fix expected?

**Comment by Nicoduweb** [comment]
Same problem here !
Can't believe this required more than 1 month to be fixed ....
I'm so disappointed !

I'm a big fan of elementor ... here is one more reason !

**Comment by webgmclassics** [comment]
Has anyone figured out a fix to this yet? We're going on the third month of this bug here... Cloning the shop manager role seems to be a fix, but it breaks too much other functionality for us.
Be sure to contact their support https://support.wpbakery.com/tickets

**Comment by mkerstner** [comment]
Same issue here - did anybody find a solution?

**Comment by webgmclassics** [comment]
Still no solution...

**Comment by mkerstner** [comment]
Unfortunately not (...), here's the response from the support:

> Hi,
> 
> ​We are aware of this issue and it is already on our bug-fix list to be checked in near future. As soon as we have a quick-fix regarding it, we will be able to share it with you.

**Comment by webgmclassics** [comment]
Same canned response here... I've been contacting them once every two weeks or so... Exceptionally terrible service.

**Comment by AngeIII** [comment]
Works fine for me with latest wordpress and WPBakery Page Builder

**Comment by AngeIII** [comment]
*update*
found an issue, it was related to WooCommerce update in newer version editable_roles was setup incorrectly.

In line: wp-content/plugins/woocommerce/includes/wc-user-functions.php:397
$shop_manager_editable_roles = apply_filters( 'woocommerce_shop_manager_editable_roles', array( 'customer' ) );

shop_manager role is not set as editable_role but it setup'ed a some other role "customer" and this causes an issue when opening the edit page/post view.

Fix will be available in next relaase of  WPBakery Page Builder,
quick fix is:
```
add_filter('woocommerce_shop_manager_editable_roles', function($roles) {
  $roles[]='shop_manager';
  return array_unique($roles);
});
```

cc @webgmclassics  @phlegx @gottschild @jogoyo

**Comment by mirzavu** [comment]
The fix is not working for me, seems they havnt solved the issue yet.
