### ISSUE TITLE
Introduce a filter for the "Reviews Title"

### ISSUE THREAD

**Issue by wpexplorer** [woocommerce/woocommerce#21894]
**Is your feature request related to a problem? Please describe.**
The reviews title currently includes the current product name as such: "x review for y" - including the current product name is redundant and most "real" shops don't include this. Most sites use simple headings like "x Customer Reviews".

**Describe the solution you'd like**
Introduce a filter such as "woocommerce_product_reviews_title" so the title can be tweaked easily.

**Describe alternatives you've considered**
The only current alternatives is to override the entire file via a child theme or use javascript.

**Additional context**
Thank you for considering ;)

**Comment by claudiulodro** [comment]
Introduced in #21918
