### ISSUE TITLE
Using SVG as thumbnail in product category

### ISSUE THREAD

**Issue by snaks12** [woocommerce/woocommerce#21899]
Hello,

i wanted to use SVG for my product category but the selection return this error TypeError: attachment.sizes is undefined. 

I saw that the issue #9592 had the same problem, and a correction to class-wc-admin-taxonomies.php resolve the current issue.

replacing this line in the file at 158,160 & 268,271

`var attachment_thumbnail = attachment.sizes.thumbnail || attachment.sizes.full;`
....
`jQuery( '#product_cat_thumbnail' ).find( 'img' ).attr( 'src', attachment_thumbnail.url);`

to

`var url = attachment.sizes && attachment.sizes.thumbnail ? attachment.sizes.thumbnail.url : attachment.url;`
...
`jQuery( '#product_cat_thumbnail' ).find( 'img' ).attr( 'src', url );`

Pull request  #21900

**Comment by kloon** [comment]
PR #21900

**Comment by ArneSaknussemm** [comment]
Oh, thank you so much @snaks12 ,I've been struggling with this for hours.
It's weird since I've been using svg files on product categories on others WooCommerce installations and never faced this issue.
When I can find some time I will find what's going on.
