### ISSUE TITLE
Error Attempting to Import Product Variations

### ISSUE THREAD

**Issue by evcoin** [woocommerce/woocommerce#21891]
I have been having issues with variable item options.  According to 
http://woocommerce.github.io/woocommerce-rest-api-docs/#create-a-product
this is the format of adding a product variation.
            'options' => [
                'S',
                'M'
            ]

Here is my code 
                'options' => [
                $spread_array[$i],
                'none'
                ]
And my output shows 
            [2] => Array
                (
                    [id] => 3
                    [position] => 2
                    [visible] => 1
                    [variation] => 1
                    [options] => Array
                        (
                            [0] => -101
                            [1] => none
                        )

                )

However I keep getting the error below. 
Fatal error: Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: Error: Invalid parameter(s): attributes [rest_invalid_param] in C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php:348 Stack trace: #0 C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php(378): Automattic\WooCommerce\HttpClient\HttpClient->lookForErrors(Object(stdClass)) #1 C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php(414): Automattic\WooCommerce\HttpClient\HttpClient->processResponse() #2 C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\Client.php(56): Automattic\WooCommerce\HttpClient\HttpClient->request('products', 'POST', Array) #3 C:\xampp\htdocs\odds.php(372): Automattic\WooCommerce\Client->post('products', Array) #4 {main} thrown in C:\xampp\htdocs\vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php on line 348
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ]X The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

- [ X] This bug happens with only WooCommerce plugin active
- [ X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ X] I can reproduce this bug consistently using the steps above

**Comment by kloon** [comment]
Seems like your issue text is messed up so cannot really see the code you are using. The gist of creating variable products using the API is this part of the request body

```
'attributes' => [
        [
            'id' => 6,
            'position' => 0,
            'visible' => false,
            'variation' => true,
            'options' => [
                'Black',
                'Green'
            ]
        ],
        [
            'name' => 'Size',
            'position' => 0,
            'visible' => true,
            'variation' => true,
            'options' => [
                'S',
                'M'
            ]
        ]
    ],
    'default_attributes' => [
        [
            'id' => 6,
            'option' => 'Black'
        ],
        [
            'name' => 'Size',
            'option' => 'S'
        ]
    ]
```

From the error, it seems you are omitting the attributes array or are defining it incorrectly.

The attributes array should contain all the attributes of your product and indicate if it should be used for variations. The default_attributes array should match attributes defined in attributes array for variations and will give you the variable product options.

When dealing with global attributes you need to specify a valid ID of a global attribute, if you want to use custom attributes then omit the id element from the array.
