### ISSUE TITLE
REST API V2/3 cannot add meta_data to line_item when creating new order

### ISSUE THREAD

**Issue by kalanyuz** [woocommerce/woocommerce#21890]
**Describe the bug**
Making a post request to /orders endpoint with "meta_data" result in meta_data value not saved.
My product has variations with 2 fields where 1 is fixed and the other field is selectable. 
![image](https://user-images.githubusercontent.com/999784/48353351-901adb80-e6d2-11e8-8524-06e957fde1ba.png)
When I create order with product id and variation id the fixed value appears in meta_data but the value I want to set manually via REST api is not recognized.

**To Reproduce**
1. Insomnia request to /wp-json/wc/v3/orders
2. Create order with the following line_items:
```
"line_items": [
    {
      "product_id": 795,
      "variation_id": 796,
      "quantity": 1,
			"meta_data": [{"size":"52"}]
    }
  ]
```
3. submit
4. Json response will return empty size value with its variation's fixed value
```
"meta_data": [
	{
	       "id": 122,
		"key": "size",
		"value": ""
	},
	{
		"id": 123,
		"key": "gold",
		"value": "18KWG"
	},
        ......
```

**Expected behavior**
Specified meta_data value appears in JSON response

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### Theme ###

Name: Storefront
Version: 2.3.3 – 2.3.5 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by kloon** [comment]
The key should just be meta and not meta_data and each meta item needs to contain `key`, `label` and `value` properties. Please see https://woocommerce.github.io/woocommerce-rest-api-docs/v3.html#products-meta-items-properties for format.

Also be sure to pass the content-type header as application/json when making your request.
