### ISSUE TITLE
"Order" word not translated anymore in email-order-details.php

### ISSUE THREAD

**Issue by t-bo** [woocommerce/woocommerce#21898]
Since the last commit in this file: emails/email-order-details.php
Using WPML. The word "Order" is not translated anymore probably due to the added brackets []
https://github.com/woocommerce/woocommerce/commit/679399b4b249827ee0f68b799ced23bc18d1aa1b#diff-e39a9512d67eab87610375f317a08d33

**Comment by rodrigoprimo** [comment]
The translation for Woocommerce is done by https://translate.wordpress.org/projects/wp-plugins/woocommerce. If you're using the most current version, the string might not be already translated and that is why it is being displayed in English.
