### ISSUE TITLE
Capitalize dashboard widget titles

### ISSUE THREAD

**Issue by jessuppi** [woocommerce/woocommerce#21909]
The Dashboard widgets generated by WooCommerce should be capitalized to fall more in line with WordPress Core, universal plugin norms, and general English grammar...

Specifically, these have bugged me for years:

- Change `WooCommerce status` to `WooCommerce Status`
- Change `WooCommerce recent reviews` to `WooCommerce Recent Reviews`

OCD users and Grammar Nazis the world over will especially thank you for your cooperation.

Estimated time required: 30 seconds.

K thanks. ( ͡° ͜ʖ ͡°)

**Comment by kloon** [comment]
See #21913 for fix
