### ISSUE TITLE
Button to add note doesn't work since last update

### ISSUE THREAD

**Issue by vsbnjmn** [woocommerce/woocommerce#21919]
I can't add client note nor private note, the button doesn't respond. I also can't edit the products, because this menu alsto stopped working.
 
![capture](https://user-images.githubusercontent.com/34044268/48512553-827f6600-e838-11e8-8732-0f0edfa4d7a4.PNG)

**Comment by kloon** [comment]
Check for JS errors and please follow the guide we provided when you opened the issue. Chances are you have a theme/plugin conflict.

The functionality works fine for me using a standard theme like Storefront and Twentyseventeen.
