### ISSUE TITLE
Structured data problem with non-Latin characters in URLs

### ISSUE THREAD

**Issue by MoeMauhphie** [woocommerce/woocommerce#21914]
Hi,

Sorry for not using the template to create this topic. This is a general issue about structured data and you can easily reproduce it with the following code. Persian characters in URLs create problems in structured data. Please check this snippet in testing tool:

`<script type="application/ld+json">{"@context":"https:\/\/schema.org\/","@graph":[{"@context":"https:\/\/schema.org\/","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"item":{"name":"\u062e\u0627\u0646\u0647","@id":"https:\/\/tennisfa.com\/shop"}},{"@type":"ListItem","position":2,"item":{"name":"\u0633\u0627\u06a9 \u062a\u0646\u06cc\u0633","@id":"https:\/\/tennisfa.com\/shop\/product-category\/%d8%b3%d8%a7%da%a9-%d8%aa%d9%86%db%8c%d8%b3\/"}},{"@type":"ListItem","position":3,"item":{"name":"\u0633\u0627\u06a9 \u062a\u0646\u06cc\u0633 \u0647\u062f Tour Team Wimbledon 12R Monstercombi","@id":"https:\/\/tennisfa.com\/shop\/product\/%d8%b3%d8%a7%da%a9-%d8%aa%d9%86%db%8c%d8%b3-%d9%87%d8%af-tour-team-wimbledon-12r-monstercombi\/"}}]},{"@context":"https:\/\/schema.org\/","@type":"Product","@id":"https:\/\/tennisfa.com\/shop\/product\/%d8%b3%d8%a7%da%a9-%d8%aa%d9%86%db%8c%d8%b3-%d9%87%d8%af-tour-team-wimbledon-12r-monstercombi\/","name":"\u0633\u0627\u06a9 \u062a\u0646\u06cc\u0633 \u0647\u062f | Tour Team Wimbledon 12R Monstercombi","image":"https:\/\/tennisfa.com\/shop\/wp-content\/uploads\/2018\/11\/htourteamwimbledon12r.jpg","description":"<p dir=\"rtl\">\u0633\u0627\u06a9\u00a0Tour Team Wimbledon \u0647\u0645\u0627\u0646 \u0633\u0627\u06a9\u06cc \u0627\u0633\u062a \u06a9\u0647 \u0646\u0648\u0627\u06a9 \u062c\u0648\u06a9\u0648\u0648\u06cc\u0686 \u0628\u0627 \u0622\u0646 14\u0640\u0645\u06cc\u0646 \u0639\u0646\u0648\u0627\u0646 \u06af\u0631\u0646\u062f \u0627\u0633\u0644\u0645 \u062e\u0648\u062f \u0631\u0627 \u062f\u0631 \u0645\u0633\u0627\u0628\u0642\u0627\u062a \u0648\u06cc\u0645\u0628\u0644\u062f\u0648\u0646 2018 \u0628\u062f\u0633\u062a \u0622\u0648\u0631\u062f. \u0631\u0646\u06af\u200c\u0647\u0627\u06cc \u0633\u0641\u06cc\u062f \u0648 \u0633\u0628\u0632 \u0627\u06cc\u0646 \u06a9\u06cc\u0641 \u062e\u0627\u0635\u060c \u062c\u0644\u0648\u0647\u200c\u06cc \u0632\u06cc\u0628\u0627\u06cc\u06cc \u0628\u0647 \u0622\u0646 \u0628\u062e\u0634\u06cc\u062f\u0647 \u0627\u0633\u062a. \u0627\u06cc\u0646 \u0633\u0627\u06a9 \u062f\u0627\u0631\u0627\u06cc 3 \u0628\u062e\u0634 \u0628\u0632\u0631\u06af \u0627\u0633\u062a \u0648 \u062f\u0631 \u0645\u062c\u0645\u0648\u0639 12 \u0631\u0627\u06a9\u062a \u0631\u0627 \u0645\u06cc\u200c\u062a\u0648\u0627\u0646\u062f \u062f\u0631 \u062e\u0648\u062f \u062c\u0627\u06cc \u062f\u0647\u062f.<\/p>\n","sku":"283108","offers":[{"@type":"Offer","price":"1550000","priceSpecification":{"price":"1550000","priceCurrency":"IRT","valueAddedTaxIncluded":"false"},"priceCurrency":"IRT","availability":"https:\/\/schema.org\/InStock","url":"https:\/\/tennisfa.com\/shop\/product\/%d8%b3%d8%a7%da%a9-%d8%aa%d9%86%db%8c%d8%b3-%d9%87%d8%af-tour-team-wimbledon-12r-monstercombi\/","seller":{"@type":"Organization","name":"\u0641\u0631\u0648\u0634\u06af\u0627\u0647 \u062a\u0646\u06cc\u0633 \u0641\u0627","url":"https:\/\/tennisfa.com\/shop"}}]}]}</script>`

As you can see in the result, 'product' data are mixed into 'breadcrublist'. Interestingly that happens because of this line:
`@type":"Product","@id":"https:\/\/tennisfa.com\/shop\/product\/%d8%b3%d8%a7%da%a9-%d8%aa%d9%86%db%8c%d8%b3-%d9%87%d8%af-tour-team-wimbledon-12r-monstercombi\/",
`
If you remove a "dash" from those gibberish characters, it surprisingly starts to work as expected!

I'm using the latest version of Woocommerce.

Regards,

**Comment by rodrigoprimo** [comment]
On a quick look, I was not able to reproduce. I pasted the provided snippet into Google Structured Data Testing Tool and, as far as I can see, the result is correct and data is not mixed.

Could you please detail what you expected to see and what you are actually seeing? Also, could you please share the product data you are using so that I can create a product myself with the same information to try to reproduce?

Thanks

**Comment by MoeMauhphie** [comment]
Thanks for your reply Rodrigo,

Actually the problem has nothing to do with the non-Latin characters, I have started a thread here:
https://wordpress.org/support/topic/structured-data-bug-2/#post-10904321
Please have a look. 

Regards,
