### ISSUE TITLE
Update Products Block notice for WP 5.0

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce#21915]
[Here we check if the Gutenberg feature plugin is active to determine whether to show the Products Block plugin notice](https://github.com/woocommerce/woocommerce/blob/d0491072e8a7d0a4535db0ec2bae4a6d43ff64fd/includes/admin/class-wc-admin-notices.php#L370-L386). This needs to be updated to check if WP version is >= WP 5.0, and show the notice if it is.

**Comment by kloon** [comment]
See #21930
