### ISSUE TITLE
Make links (URLs) in costumer notes emails clickable

### ISSUE THREAD

**Issue by gerdneuman** [woocommerce/woocommerce#21925]
**Is your feature request related to a problem? Please describe.**
Very often I send customers a note using the "customer notes email" feature. Very often I need to send them a link (URL) to the order payment page (often a payment bounced or was forgotten, so I send a reminder with a link to this page so that customers can pay there). Now this link (which is lengthy with lots of query params) is just included as normal text and is not clickable.

So customer always has to copy'n'paste text to browser's address bar.

I guess I mean something like #695 (which has no description and was closed immediately ;) 

**Describe the solution you'd like**
Parse the text and automatically convert all URLs like `https://examplepetstore.com` in there to an `<a href="https://examplepetstore.com" target="_blank" rel="noopener">https://examplepetstore.com</a>`
 

**Describe alternatives you've considered**
Usually mail programs are nowadays intelligent enough to do the linking themselves but in this case it does not work. I tested in Thunderbird 60 and in current K9-Mail (Android). Maybe because the text of a customer note is in a `<blockquote>` or more likely because it is an HTML mail where the mail programs' autolinking does not work (I think only in text).

**Additional context**
I would not recommend to write your own regex here as it is very error prone. Rather use a lib like https://github.com/iamcal/lib_autolink or https://bitbucket.org/kwi/urllinker/ for this (maybe there are also others)

**Comment by kloon** [comment]
See #21927 for fix.
