### ISSUE TITLE
Just visiting the checkout on a site on a Multisite Network can change a user's country

### ISSUE THREAD

**Issue by JakePT** [woocommerce/woocommerce#21920]
**Describe the bug**
Just visiting the checkout on a site on a Multisite Network can change a user's address. 

If a user has registered on Site **A** of a Multisite Network, and their address' country is, say, Australia, then if they visit Site **B** on the network, and site B is configured to only ship or sell to the United States, then merely visiting the checkout will change the country of the user's saved address to the United States. 

When the users then returns to Site **A** and goes to check out or edit their address , they will see that the country has changed.

**To Reproduce**
1. Create a multisite network with 2 sites, **A** & **B**.
2. Add a user to both sites.
3. Configure site **B** to only sell to a single country.
4. Set the new user's address to be in any country that site **B** does not sell to.
5. Sign into site **B**, add a product to the cart, and proceed to checkout. _Don't check out._ The Country field will not be a dropdown, and will be set to the only country that site B sells to.
6. Leave the checkout and go to the _My Account > Addresses_ page. The country in their address will have changed to the country that site B sells to.
7. Sign into site **A** and go to the _My Account > Addresses_ page. The country in their address will have changed to the country that site B sells to.

**Screenshots**

**Expected behavior**
Site **B** should not let the user complete checkout, because the site does not sell to their address, but it should not permanently change the user's address without their input.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

Home URL: http://multisite.test
Site URL: http://multisite.test
WC Version: 3.5.1
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.25 (Win64) OpenSSL/1.0.2k PHP/7.1.5
PHP Version: 7.1.5 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 36000
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.7.18
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 3.19MB
Database Data Size: 2.37MB
Database Index Size: 0.82MB
wp_woocommerce_sessions: ❌ Table does not exist
wp_woocommerce_api_keys: ❌ Table does not exist
wp_woocommerce_attribute_taxonomies: ❌ Table does not exist
wp_woocommerce_downloadable_product_permissions: ❌ Table does not exist
wp_woocommerce_order_items: ❌ Table does not exist
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: ❌ Table does not exist
wp_woocommerce_tax_rate_locations: ❌ Table does not exist
wp_woocommerce_shipping_zones: ❌ Table does not exist
wp_woocommerce_shipping_zone_locations: ❌ Table does not exist
wp_woocommerce_shipping_zone_methods: ❌ Table does not exist
wp_woocommerce_payment_tokens: ❌ Table does not exist
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: ❌ Table does not exist
wp_blogs: Data: 0.02MB + Index: 0.03MB
wp_blog_versions: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.05MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.48MB + Index: 0.02MB
wp_postmeta: Data: 0.28MB + Index: 0.17MB
wp_posts: Data: 0.20MB + Index: 0.06MB
wp_registration_log: Data: 0.02MB + Index: 0.02MB
wp_signups: Data: 0.02MB + Index: 0.06MB
wp_site: Data: 0.02MB + Index: 0.02MB
wp_sitemeta: Data: 0.06MB + Index: 0.03MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

attachment: 61
nav_menu_item: 51
page: 24
post: 41
product: 19
product_variation: 7

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.5.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Cascade
Version: – 0 is available
Author URL: https://www.magicdust.com.au
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: cascade/woocommerce/product-searchform.php version - is out of date. The core version is 3.3.0
Outdated Templates: ❌
					
					
						Learn how to update
```
</details>

**Comment by rrennick** [comment]
> Site B should not let the user complete checkout, because the site does not sell to their address...

As a Canadian, I should be able to make a purchase from a UK only shop & have the item shipped to my cousin in the UK.

In your steps above are you referring to the billing address or shipping address.

**Comment by JakePT** [comment]
> As a Canadian, I should be able to make a purchase from a UK only shop & have the item shipped to my cousin in the UK.

If the store has configured the _Selling location(s)_ and _Shipping location(s)_ settings in WooCommerce to only Canada, then _no_, you absolutely shouldn't.

I'm not arguing business models here, I'm talking about how configuring one store on a Multisite Network a certain way can result in a customer's details being changed across the network without their input.

Regardless, a business might not ship to certain countries for any number of reasons. They could have a local store that ships to specific countries, so the user needs to go there, or the store might have business arrangements with local partners that have exclusive rights to sell or ship the product to specific countries.

> In your steps above are you referring to the billing address or shipping address.

It can happen to both. It happens whenever the _Country_ dropdown in the checkout is disabled. This happens when there's only one option available. So the billing address would be affected if the _Selling location(s)_ setting were set to a single country, and it would affect the shipping address if the _Shipping location(s)_ setting were set to a single country.

For example, if I have _Selling location(s)_ set to _Sell to all countries_ but _Shipping location(s)_ only set to _Canada_, then if I check out the Country dropdown will be replaced in the Shipping Address form with bold text that reads _Canada_. This makes sense because the store doesn't ship anywhere else, so there's no point letting them select a country.

The problem is that when this happens the relevant address is updated in the database, just by viewing the checkout page, so even if I don't check out, when I go to the My Account page, and look at my addresses, the address' country will be changed to the store's single shipping location.

On a single site install this normally wouldn't be a noticeable problem, because there wouldn't be any circumstances under which the user _could_ have selected another country (unless the store's shipping locations had changed during the life of the site). On Multisite however this can be a problem because addresses are user meta, and thus shared across all sites on the network.

So this all leads to the bug I'm describing: If a user on a multisite network attempts to check out on a store that does not sell _or ship_ to their country, then just by viewing the checkout one or both of their addresses will have its country incorrectly changed across the entire network.

**Comment by kloon** [comment]
This is unfortunately due to the way WordPress stores users in a MS. Users are shared across all sites and since address details are stored on the user profile when a user changes them on the checkout page it will load the last entered address the user used on any of the MS stores.

Why do we save the address details? On page load? Because the store only ships to one country we load that country as part of the address and this triggers the save. Because the checkout page does reloads for taxes, shipping options and payment details and we need to have the details the customer entered stored to ensure they do not need to retype eveything.

I am open to suggestion for a solution but the we we have it now means the customer do not have to try and figure out why it could maybe says "Your country not supported", then they get curious and want to see what country does it ship to. Simply updating checkout with the one supported country makes the most sense in that case.

**Comment by rrennick** [comment]
> I am open to suggestion for a solution

The addresses could be moved from user_meta to user_settings (screen options are user settings) but I wouldn't switch all installs over to that. A multisite only setting could be added (either per each WC site or 1 per network) to switch from user meta to settings.

**Comment by JakePT** [comment]
Having addresses be per-site makes a certain amount of sense, because the orders made with those addresses – being posts – are themselves per-site. 

I think the problem is that the way WordPress stores 'user options' is just by prefixing the user meta key with the site's prefix. Looking at the data store classes it seems like the exact meta keys and address type prefixes etc. are all coded in such a way that would make changing them to work with user options a fair amount of work.

>but the we we have it now means the customer do not have to try and figure out why it could maybe says "Your country not supported", then they get curious and want to see what country does it ship to. Simply updating checkout with the one supported country makes the most sense in that case.

I just think that in a multisite context, changing a user's address across the network is more confusing and unexpected that displaying an error that the store does not ship/sell to their address. In fact, I think that in a multisite context an error like this is _desirable_, especially if the multisite network is a network of similarly branded stores that just sell to different markets.

It might even be preferable on a single-site store too. If a user has managed to enter an address that the store does not sell to, then that must mean that the store has changed which countries it sells to. In that situation just changing the user's address also seems more confusing that having any sort of error that might explain what's going on.

**Comment by mikejolley** [comment]
Should also be resolved by https://github.com/woocommerce/woocommerce/pull/22392 which pulls checkout address from account (user meta) rather than the session.
