### ISSUE TITLE
Undefined variable: changes in woocommerce/includes/wc-stock-functions.php on line 279

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#21926]
In some situations, this warning shows up on the logs, because the $changes array is not declared/initialized.

Function: wc_increase_stock_levels
Line: 279

If you take a look at wc_reduce_stock_levels line 152 you can see the variable initialized before the foreach loop. The same should be done in wc_increase_stock_levels.

**Comment by kloon** [comment]
See #21928 for fix.
