### ISSUE TITLE
Incompatibility when multiple sites share a database

### ISSUE THREAD

**Issue by dchenk** [woocommerce/woocommerce#21937]
**Describe the bug**
A standard WordPress feature involves using different strings for the `$table_prefix` to host [multiple sites on the same database](https://codex.wordpress.org/Editing_wp-config.php#table_prefix). For example, you can have the prefix `wp1_` for one site, and `wp2_` for another site, and some other prefix for another site. However, in MySQL a foreign key constraint [name cannot be re-used](https://dev.mysql.com/doc/refman/5.7/en/create-table-foreign-keys.html) on multiple tables. Currently, WooCommerce attempts to add a FK constraint named "fk_wc_download_log_permission_id" to each site's "wc_download_log" table upon plugin update, using the query:
```
ALTER TABLE `{$wpdb->prefix}_wc_download_log`
ADD CONSTRAINT `{$constraint_prefix}wc_download_log_permission_id`
FOREIGN KEY (`permission_id`)
REFERENCES `{$wpdb->prefix}_woocommerce_downloadable_product_permissions` (`permission_id`) ON DELETE CASCADE;
```
in the file [includes/class-wc-install.php](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-install.php), where `{$constraint_prefix}` is either "fk_" (on non-multisite as well as on the main site of multisite systems) or else the sub-site's table prefix on multisite.

This `ALTER TABLE` fails on all sites which use a database which already has a constraint named "fk_wc_download_log_permission_id". The recent fix for multisite compatibility (https://github.com/woocommerce/woocommerce/pull/21836) does not address this issue.

**To Reproduce**
1. Install a site with any `$table_prefix`.
2. Install another site using the same database but with a different `$table_prefix`.
3. Install a non-current version of WooCommerce on each site (to simulate having a site simply running the previous version of WooCommerce).
4. Update the first site to the latest version of WooCommerce.
5. Update the other site to the latest version of WooCommerce. Notice that the `ALTER TABLE` query fails with the MySQL error 1022: "Can't write; duplicate key in table '#sql-67e1_6d5b8'".

**Expected behavior**
Upon the update of WooCommerce, it should be checked if the site's "wc_download_log" table already has a constraint named "fk_{$wpdb->prefix}wc_download_log_permission_id":
 - If the table has this constraint, nothing needs to be done in this step of the update.
 - If the table does not have this constraint:
   - If the table has a constraint named "fk_wc_download_log_permission_id" then this constraint needs to be dropped and an equivalent one needs to be created with the name "fk_{$wpdb->prefix}wc_download_log_permission_id".
   - If the table has no such constraint, simply create one named "fk_{$wpdb->prefix}wc_download_log_permission_id".

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by kloon** [comment]
See #21940 for fix.
