### ISSUE TITLE
Select2 needs updating

### ISSUE THREAD

**Issue by Roy-Orbison** [woocommerce/woocommerce#21939]
Running into [this bug](https://github.com/select2/select2/issues/4514) which is at least partially fixed in the current version.

**WordPress Environment**
WooCommerce version: 3.5.1

**Comment by kloon** [comment]
We have a custom implementation of Select2 called SelectWoo which has added accessibility functionality and namespacing. Can you please open an issue on the SelectWoo repo so we can look into getting the fork in sync again? https://github.com/woocommerce/selectWoo

Thanks!
