### ISSUE TITLE
Import of escaped Excel injection formulas in product attributes are not unescaped

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce#21935]
**Describe the bug**
Related to #21457. See also https://github.com/woocommerce/woocommerce/pull/21864#issuecomment-439119643

In the CSV export, fields that begin with `=`, `+`, `-` or `@` are escaped with a leading `'` so that the importing spreadsheet program will treat the field as a literal string and not a formula. 

The trailing `'` is not needed. 
The CSV import does not remove the leading or trailing `'` from the imported data before inserting/updating the DB resulting in the `'` being added to the field.

**To Reproduce**
1. Go to Product Attributes.
2. Add an attribute.
3. Add a term to the attribute where the name begins with a `+`.
4. Edit a variable product.
5. Add the attribute to the product & select the term beginning with the `+`.
6. Export variable products.
7. Delete the term beginning with the `+`.
8. Import the CSV you exported.

**Screenshots**
https://user-images.githubusercontent.com/343847/48564410-b7d59380-e8cc-11e8-85cd-65fef6c1e662.png

**Expected behavior**
The fields that need escaping should be prepended with the `'`.
Import should remove the escape `'` where it precedes `=`, `+`, `-` or `@`.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Latest versions of Storefront, WC & WP.

**Comment by kloon** [comment]
PR #21938
