### ISSUE TITLE
WooCommerce doesn't pass the HTML validation test

### ISSUE THREAD

**Issue by manake** [woocommerce/woocommerce#21957]
https://themes.woocommerce.com/storefront/product/stainless-steel-professional-blender/

https://validator.w3.org/nu/?doc=https%3A%2F%2Fthemes.woocommerce.com%2Fstorefront%2Fproduct%2Fstainless-steel-professional-blender%2F

Can you fix this, please?

This affects all websites.

Thanks

**Isolating the problem (mark completed items with an [x]):**
* [x]  I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
* [x]  This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
* [x]  I can reproduce this bug consistently.

**Comment by manake** [comment]
Any chance of having this for 3.5.2?

Seems like a very easy fix.

You would only need to change like 3 words.

**Comment by rrennick** [comment]
This was fixed in #22333.
