### ISSUE TITLE
QuanitySpinners disappear after add to cart in cart is clicked.

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#21950]
Hi

i have a weird issue. After the add to cart button is clicked in the cart page for items you might also like the spinners disappear.

I am using the quantity spinner plugin https://nl.wordpress.org/plugins/woocommerce-quantity-increment/

![afbeelding](https://user-images.githubusercontent.com/6078370/48626713-e88ff880-e9b2-11e8-8d1d-23982a3ef397.png)

You can see it here in action http://kaptinlin.com/themes/wooshop/cart

Is there another event that is fired that the plugin does not handle?

how to fix this?  Please advice.

**Comment by BackuPs** [comment]
It seems to me that the add to cart button in the cart page does not trigger any event.  Could this be a woo bug that got into one of the latests build?

**Comment by BackuPs** [comment]
You can download the updated files here

save this as wc-quantity-increment.js https://pastebin.com/D17NQwnp

save this as wc-quantity-increment.min.js https://pastebin.com/h3Jfx2Ft

replace by ftp these same two files in the plugins folder called

wp-content\plugins\woocommerce-quantity-increment\assets\js

**Comment by kloon** [comment]
Seems like a plugin issue, please contact the plugin developer for support.

In the future please also follow the steps when opening the issue such as testing with all plugins disabled and your theme switched to a default one and filling out the template we provide as that helps us a lot in troubleshooting and isolating the issue.

**Comment by BackuPs** [comment]
LOL. The developer is as far as i know part of the woo team. or used to be !
