### ISSUE TITLE
Unable to edit/open orders

### ISSUE THREAD

**Issue by kitcat3** [woocommerce/woocommerce#21965]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by kitcat3** [comment]
Blank page, HTTP Error 500 when opening placed order

**Comment by kloon** [comment]
Check your error logs, might be a plugin/theme conflict. Unable to replicate using just WooCommerce and a default theme like Twentyseventeen.
