### ISSUE TITLE
WP 5.0 - Misleading deprecated notice for edit_form_after_title

### ISSUE THREAD

**Issue by pierrebuet** [woocommerce/woocommerce#21962]
**Describe the bug**
With Wordpress 5.0 and when editing a standard post with the block editor, deprecated notices are printed out for the hook edit_form_after_title. Woocommerce uses this hook for the coupon form in admin.

**To Reproduce**
1. Edit a standard post with the new block editor and woocommerce activated and look in the console.

**Expected behavior**
Try not to confuse users with this misleading notice. To do so, Woocommerce should not hook and then check the post type, but only hook on a given screen ID.

**Comment by kloon** [comment]
PR #21485
