### ISSUE TITLE
Product Image Gallery Class

### ISSUE THREAD

**Issue by ontiuk** [woocommerce/woocommerce#21960]
A relatively simple enhancement, which some people may find useful. I needed to tweak the css of the woocommerce-product-gallery tag based on whether there was gallery thumbnails or not. No straightforward solution atm. 

Solution is to add a --with-gallery and --without-gallery wrapper class, similar to the already provided --with-images wrapper class in the single-product/product-image.php template file.

Add a new line of code below the --with-images / --without-images wrapper class:
`
'woocommerce-product-gallery--' . ( $product->get_gallery_image_ids() ? 'with-gallery' : 'without-gallery' ),
`

This will generate the .woocommerce-product-gallery--with-gallery, or .woocommerce-product-gallery--without-gallery class depending on the presence of gallery images. CSS can then be easily tied to the new tag.

Thanks

**Comment by kloon** [comment]
It seems like a simple solution yes, but it will break a lot of sites relying on the class that is currently in use. Yes we can add more classes but that will just add more data to the element, it already has a lot of classes.

IMO, there should be enough ways at present to achieve what you are trying to achieve without having to add a css class. CSS selectors are pretty robust and you can select just about any element(s) with what is available there at present.

You can also change the layout by overriding the template or parts thereof, or you can use javascript to also do the changes.

**Comment by ontiuk** [comment]
"but it will break a lot of sites relying on the class that is currently in use. " I'm not saying remove anything?

Yes, I can override the layout, as I did. That's because there's currently no default way to know if the gallery wrapper contains gallery thumbnails or not, but one to say whether it has a featured image or not.

"IMO, there should be enough ways at present to achieve what you are trying to achieve without having to add a css class." Did you look?

But, as you will.

**Comment by ontiuk** [comment]
Not images, as in featured image, just gallery thumbnails. I was putting a coloured background on the 
< figure > parent container, but didn't want it on the display with thumbnails, where it was to remain transparent. The wrapper class for --with-images is for the featured image. Nothing for the presence of thumbnails / product gallery. Could have gone down the convoluted javascript path of checking for thumbnails or the injected figure flex container. But much easier just to add a gallery wrapper class which allows for easy cascade css selectors. Pretty simple really. Don't know why it's not already there.
