### ISSUE TITLE
Add custom shipping zone location

### ISSUE THREAD

**Issue by sebastianpisula** [woocommerce/woocommerce#21964]
I would like to add new field for Shipping Location. Map where user can print area where is shipping zone.

To adding new field I can use woocommerce_shipping_zone_after_methods_table action. For saving I can use woocommerce_before_shipping_zone_object_save action. I would like to use these code:

```$zone->add_location( 'details', 'custom_area');```

But I can't because here exist function: wp-content/plugins/woocommerce/includes/class-wc-shipping-zone.php:336

I think there should be filter for example:

	public function is_valid_location_type( $type ) {
		$types = apply_filters( 'woocommerce_valid_location_types', array(
			'postcode',
			'state',
			'country',
			'continent'
		), $this );

		return in_array( $type, $types, true );
	}

**Comment by kloon** [comment]
There is a filter `woocommerce_valid_location_types`? Just hook into that to add your location type as a new type and it should pass the validation.

**Comment by sebastianpisula** [comment]
@kloon no, these filter not exists - this is my suggestion for new filter.

**Comment by kloon** [comment]
Ah, sorry about that, thought you quoted the function as is. Will repoen and work on a patch with the new filter.

**Comment by kloon** [comment]
See #21969
