### ISSUE TITLE
Cannot Disable Account Creation on Cart and Product Pages, etc.

### ISSUE THREAD

**Issue by reneezipp** [woocommerce/woocommerce#21977]
Although all the boxes are un-checked for account creation. Anyone can still create an account - the pop-up form is on al the product pages and the cart page. Since my client exclusively sells to wholesale businesses and they must apply to see prices, etc., this is a huge problem for us, because they cannot fulfill the small, random orders to individuals.

I've disabled account creation, but it's still available throughout the site.

Please help!! Thank you!!

<img width="1440" alt="screen shot 2018-11-19 at 4 08 22 pm" src="https://user-images.githubusercontent.com/45185956/48743188-d0201800-ec16-11e8-8468-c3e454328aa1.png">
<img width="965" alt="screen shot 2018-11-19 at 4 10 56 pm" src="https://user-images.githubusercontent.com/45185956/48743189-d0201800-ec16-11e8-84d6-6ddf03430d97.png">

**Comment by kloon** [comment]
That is not standard WooCommerce functionality. Please test with all plugins disabled except WooCommerce and with your theme switched to a default one like Twentyseventeen or Storefront.
