### ISSUE TITLE
Large Quantity Add to Cart Issue in Woo Commerce

### ISSUE THREAD

**Issue by jordantbraz** [woocommerce/woocommerce#21975]
**Describe the bug**
Having an issue ordering large quantities from our online store. We tested with OUR theme AND Storefront. We narrowed down the issue with hosting but they can only supply a temporary fix. We're hoping you can come up with a better one? Notes from hosting support below: Hello Jordan, Thanks for the follow-up! I was able to reproduce the error with the link you provided. I took a look at the response headers and it looks like the POST request is setting a lot more cookies than usual, which is why we're hitting the response header limit. Here's what I'm seeing: http://flywheel.link/9a8ee5286108 (screenshot of Response Headers when adding 9 items. It sets a ton of cookies) http://flywheel.link/9d543a3fee9e (this is another Woocommerce site on flywheel, it only sets two in the response headers, despite adding 15 products) I am going to escalate this to our Hosting Platform team to raise the limit. We have to emphasize that this is a *temporary* solution, as it's manually put in place and will be reverted by the next server software update. Sorry about that! We don't have any way of knowing when that next update might be, but they're relatively frequent; I wouldn't count on it being more than a few weeks at most. I would advise contacting Woocommerce support to see if they have any ideas on how to reduce the response headers. I'll let you know once we have the temporary limit increase in place. Thanks! Joey

**WordPress Environment**

**Happens in custom theme AND Storefront with all Plugins Turned off except Woo Commerce.
Temporary fix from host is in place so you can't really duplicate the issue.

<details>
`
### WordPress Environment ###

Home URL: https://sorrentinos.com
Site URL: https://sorrentinos.com
WC Version: 3.4.4
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Flywheel/4.1.0
PHP Version: 7.1.22-1+ubuntu16.04.1+deb.sury.org+1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 300 MB
PHP Time Limit: 0
PHP Max Input Vars: 4000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.6.32-1+deb.sury.org~precise+0.1
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.5
WC Database Prefix: wp_2b885o6kvs_
MaxMind GeoIP Database: ✔
Total Database Size: 157.82MB
Database Data Size: 127.31MB
Database Index Size: 30.51MB
wp_2b885o6kvs_woocommerce_sessions: Data: 1.84MB + Index: 0.05MB
wp_2b885o6kvs_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_2b885o6kvs_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_2b885o6kvs_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_2b885o6kvs_woocommerce_order_items: Data: 0.23MB + Index: 0.14MB
wp_2b885o6kvs_woocommerce_order_itemmeta: Data: 1.74MB + Index: 1.15MB
wp_2b885o6kvs_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_2b885o6kvs_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_2b885o6kvs_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_2b885o6kvs_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
wp_2b885o6kvs_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_2b885o6kvs_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_2b885o6kvs_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.01MB
wp_2b885o6kvs_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_2b885o6kvs_commentmeta: Data: 0.42MB + Index: 0.53MB
wp_2b885o6kvs_comments: Data: 11.52MB + Index: 1.38MB
wp_2b885o6kvs_gf_addon_feed: Data: 0.02MB + Index: 0.02MB
wp_2b885o6kvs_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
wp_2b885o6kvs_gf_entry: Data: 0.23MB + Index: 0.06MB
wp_2b885o6kvs_gf_entry_meta: Data: 1.52MB + Index: 0.86MB
wp_2b885o6kvs_gf_entry_notes: Data: 0.11MB + Index: 0.03MB
wp_2b885o6kvs_gf_form: Data: 0.02MB + Index: 0.00MB
wp_2b885o6kvs_gf_form_meta: Data: 0.11MB + Index: 0.00MB
wp_2b885o6kvs_gf_form_view: Data: 0.09MB + Index: 0.09MB
wp_2b885o6kvs_links: Data: 0.02MB + Index: 0.02MB
wp_2b885o6kvs_options: Data: 2.33MB + Index: 1.06MB
wp_2b885o6kvs_postmeta: Data: 33.56MB + Index: 19.02MB
wp_2b885o6kvs_posts: Data: 4.52MB + Index: 2.55MB
wp_2b885o6kvs_rg_form: Data: 0.02MB + Index: 0.00MB
wp_2b885o6kvs_rg_form_meta: Data: 0.09MB + Index: 0.00MB
wp_2b885o6kvs_rg_form_view: Data: 0.08MB + Index: 0.03MB
wp_2b885o6kvs_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_2b885o6kvs_rg_lead: Data: 0.20MB + Index: 0.03MB
wp_2b885o6kvs_rg_lead_detail: Data: 0.45MB + Index: 0.77MB
wp_2b885o6kvs_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_2b885o6kvs_rg_lead_meta: Data: 0.09MB + Index: 0.11MB
wp_2b885o6kvs_rg_lead_notes: Data: 0.11MB + Index: 0.03MB
wp_2b885o6kvs_termmeta: Data: 0.02MB + Index: 0.03MB
wp_2b885o6kvs_terms: Data: 0.02MB + Index: 0.03MB
wp_2b885o6kvs_term_relationships: Data: 0.19MB + Index: 0.17MB
wp_2b885o6kvs_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_2b885o6kvs_usermeta: Data: 1.52MB + Index: 1.98MB
wp_2b885o6kvs_users: Data: 0.05MB + Index: 0.06MB
wp_2b885o6kvs_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_2b885o6kvs_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_2b885o6kvs_wpml_mails: Data: 65.92MB + Index: 0.11MB
wp_2b885o6kvs_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_2b885o6kvs_yoast_seo_meta: Data: 0.11MB + Index: 0.00MB

### Post Type Counts ###

acf-field: 222
acf-field-group: 23
attachment: 1826
culinary_team: 5
events: 47
ign_voucher: 1
jetpack_migration: 2
locations: 8
nav_menu_item: 6
page: 25
popup: 3
popup_theme: 7
post: 1
product: 738
product_variation: 31
revision: 1110
shop_coupon: 171
shop_order: 1962
shop_order_refund: 1
ticket-meta-fieldset: 1
tribe_events: 370
tribe_organizer: 2
tribe_rsvp_tickets: 1
tribe_venue: 10
tribe_wooticket: 2473
wcccf: 3
wccpf: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (26) ###

Gravity Forms: by rocketgenius – 2.3.4
Advanced Custom Fields PRO: by Elliot Condon – 5.7.6
BackUpWordPress: by XIBO Ltd – 3.7.2
Custom Post Type UI: by WebDevStudios – 1.5.8
Duplicate Post: by Enrico Battocchi – 3.2.2
Event Tickets Plus: by Modern Tribe
Inc. – 4.8.1

Event Tickets: by Modern Tribe
Inc. – 4.8.1

Force Regenerate Thumbnails: by Pedro Elsner – 2.0.6
Gravity Forms MailChimp Add-On: by rocketgenius – 4.3
Gravity Forms Meta Recovery Utility: by rocketgenius – 0.1
WooCommerce Gift Certificates Pro: by IgniteWoo.com – 3.5.39 – Not tested with the active version of WooCommerce
Jetpack by WordPress.com: by Automattic – 6.7
Popup Maker: by WP Popup Maker – 1.7.30
Post Types Order: by Nsp Code – 1.9.3.9
The Events Calendar: Filter Bar: by Modern Tribe
Inc. – 4.5.8

The Events Calendar: by Modern Tribe
Inc. – 4.6.23

WC Fields Factory: by Saravana Kumar K – 3.0.2
WooCommerce Shipping Method Display Style: by Multidots – 2.6 – Not tested with the active version of WooCommerce
Woocommerce CSV Import: by Allaerd Mensonides – 3.3.5 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.1.12
WooCommerce MailChimp: by Saint Systems – 2.1.12 – Not tested with the active version of WooCommerce
WooCommerce Name Your Price: by Kathy Darling – 2.8.3 – 2.9.3 is available
WooCommerce Volume Discount Coupons: by itthinx – 1.4.0 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.4.4 – 3.5.1 is available
Yoast SEO: by Team Yoast – 9.1
WP Mail Logging: by Christian Zöller – 1.8.5

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #1447 - /shop/
Cart: #1448 - /cart/
Checkout: #1449 - /checkout/
My account: #1450 - /my-account/
Terms and conditions: #2715 - /terms-conditions/

### Theme ###

Name: Sorrentinos
Version: – 0 is available
Author URL: http://jordan@creativeanvl.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: srg/woocommerce/cart/cart-empty.php version 2.0.0 is out of date. The core version is 3.1.0
srg/woocommerce/cart/cart-item-data.php
srg/woocommerce/cart/cart-shipping.php version 2.5.0 is out of date. The core version is 3.2.0
srg/woocommerce/cart/cart-totals.php
srg/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.4.0
srg/woocommerce/cart/cross-sells.php version 1.6.4 is out of date. The core version is 3.0.0
srg/woocommerce/cart/mini-cart.php version 2.5.0 is out of date. The core version is 3.3.0
srg/woocommerce/cart/proceed-to-checkout-button.php
srg/woocommerce/cart/shipping-calculator.php version 2.0.8 is out of date. The core version is 3.4.0
srg/woocommerce/checkout/cart-errors.php
srg/woocommerce/checkout/form-billing.php version 2.1.2 is out of date. The core version is 3.0.9
srg/woocommerce/checkout/form-checkout.php
srg/woocommerce/checkout/form-coupon.php version 2.2 is out of date. The core version is 3.4.4
srg/woocommerce/checkout/form-login.php version 2.0.0 is out of date. The core version is 3.4.0
srg/woocommerce/checkout/form-pay.php version 2.5.0 is out of date. The core version is 3.4.0
srg/woocommerce/checkout/form-shipping.php version 2.2.0 is out of date. The core version is 3.0.9
srg/woocommerce/checkout/payment-method.php
srg/woocommerce/checkout/payment.php version 2.5.0 is out of date. The core version is 3.4.0
srg/woocommerce/checkout/review-order.php version 2.3.0 is out of date. The core version is 3.3.0
srg/woocommerce/checkout/terms.php version 2.5.0 is out of date. The core version is 3.4.0
srg/woocommerce/checkout/thankyou.php version 2.2.0 is out of date. The core version is 3.2.0
srg/woocommerce/content-product.php version 2.6.1 is out of date. The core version is 3.4.0
srg/woocommerce/content-single-product.php version 1.6.4 is out of date. The core version is 3.4.0
srg/woocommerce/emails/admin-cancelled-order.php
srg/woocommerce/emails/admin-failed-order.php
srg/woocommerce/emails/admin-new-order.php
srg/woocommerce/emails/customer-completed-order.php
srg/woocommerce/emails/customer-invoice.php
srg/woocommerce/emails/customer-new-account.php
srg/woocommerce/emails/customer-note.php
srg/woocommerce/emails/customer-on-hold-order.php
srg/woocommerce/emails/customer-processing-order.php
srg/woocommerce/emails/customer-refunded-order.php
srg/woocommerce/emails/customer-reset-password.php
srg/woocommerce/emails/email-addresses.php
srg/woocommerce/emails/email-customer-details.php
srg/woocommerce/emails/email-downloads.php
srg/woocommerce/emails/email-footer.php
srg/woocommerce/emails/email-header.php
srg/woocommerce/emails/email-order-details.php
srg/woocommerce/emails/email-order-items.php
srg/woocommerce/emails/email-styles.php
srg/woocommerce/emails/plain/admin-cancelled-order.php
srg/woocommerce/emails/plain/admin-failed-order.php
srg/woocommerce/emails/plain/admin-new-order.php
srg/woocommerce/emails/plain/customer-completed-order.php
srg/woocommerce/emails/plain/customer-invoice.php
srg/woocommerce/emails/plain/customer-new-account.php
srg/woocommerce/emails/plain/customer-note.php
srg/woocommerce/emails/plain/customer-on-hold-order.php
srg/woocommerce/emails/plain/customer-processing-order.php
srg/woocommerce/emails/plain/customer-refunded-order.php
srg/woocommerce/emails/plain/customer-reset-password.php
srg/woocommerce/emails/plain/email-addresses.php
srg/woocommerce/emails/plain/email-customer-details.php
srg/woocommerce/emails/plain/email-downloads.php
srg/woocommerce/emails/plain/email-order-details.php
srg/woocommerce/emails/plain/email-order-items.php
srg/woocommerce/global/breadcrumb.php
srg/woocommerce/global/form-login.php version 2.1.0 is out of date. The core version is 3.3.0
srg/woocommerce/global/quantity-input.php version 2.5.0 is out of date. The core version is 3.4.0
srg/woocommerce/global/sidebar.php
srg/woocommerce/global/wrapper-end.php version 1.6.4 is out of date. The core version is 3.3.0
srg/woocommerce/global/wrapper-start.php version 1.6.4 is out of date. The core version is 3.3.0
srg/woocommerce/loop/add-to-cart.php version 2.5.0 is out of date. The core version is 3.3.0
srg/woocommerce/loop/loop-end.php
srg/woocommerce/loop/loop-start.php version 2.0.0 is out of date. The core version is 3.3.0
srg/woocommerce/loop/no-products-found.php
srg/woocommerce/loop/orderby.php version 2.2.0 is out of date. The core version is 3.3.0
srg/woocommerce/loop/pagination.php version 2.2.2 is out of date. The core version is 3.3.1
srg/woocommerce/loop/price.php
srg/woocommerce/loop/rating.php version 2.0.0 is out of date. The core version is 3.0.0
srg/woocommerce/loop/result-count.php version 2.0.0 is out of date. The core version is 3.3.0
srg/woocommerce/loop/sale-flash.php
srg/woocommerce/myaccount/dashboard.php
srg/woocommerce/myaccount/downloads.php version 2.6.0 is out of date. The core version is 3.2.0
srg/woocommerce/myaccount/form-add-payment-method.php version 2.6.0 is out of date. The core version is 3.4.0
srg/woocommerce/myaccount/form-edit-account.php version 2.6.0 is out of date. The core version is 3.4.0
srg/woocommerce/myaccount/form-edit-address.php version 2.6.0 is out of date. The core version is 3.4.0
srg/woocommerce/myaccount/form-login.php version 2.6.0 is out of date. The core version is 3.4.0
srg/woocommerce/myaccount/form-lost-password.php version 2.6.0 is out of date. The core version is 3.4.0
srg/woocommerce/myaccount/form-reset-password.php version 2.6.0 is out of date. The core version is 3.4.0
srg/woocommerce/myaccount/lost-password-confirmation.php
srg/woocommerce/myaccount/my-account.php
srg/woocommerce/myaccount/my-address.php
srg/woocommerce/myaccount/my-downloads.php
srg/woocommerce/myaccount/my-orders.php
srg/woocommerce/myaccount/navigation.php
srg/woocommerce/myaccount/orders.php version 2.6.0 is out of date. The core version is 3.2.0
srg/woocommerce/myaccount/payment-methods.php
srg/woocommerce/myaccount/view-order.php version 2.6.0 is out of date. The core version is 3.0.0
srg/woocommerce/order/form-tracking.php version 1.6.4 is out of date. The core version is 3.4.0
srg/woocommerce/order/order-again.php
srg/woocommerce/order/order-details-customer.php version 2.4.0 is out of date. The core version is 3.4.4
srg/woocommerce/order/order-details-item.php version 2.5.0 is out of date. The core version is 3.0.0
srg/woocommerce/order/order-details.php version 2.6.0 is out of date. The core version is 3.3.0
srg/woocommerce/order/tracking.php
srg/woocommerce/single-product/add-to-cart/external.php version 2.1.0 is out of date. The core version is 3.4.0
srg/woocommerce/single-product/add-to-cart/grouped.php
srg/woocommerce/single-product/add-to-cart/simple.php version 2.1.0 is out of date. The core version is 3.4.0
srg/woocommerce/single-product/add-to-cart/variable.php version 2.5.0 is out of date. The core version is 3.4.1
srg/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php version 2.5.0 is out of date. The core version is 3.4.0
srg/woocommerce/single-product/add-to-cart/variation.php
srg/woocommerce/single-product/meta.php
srg/woocommerce/single-product/price.php version 2.4.9 is out of date. The core version is 3.0.0
srg/woocommerce/single-product/product-attributes.php
srg/woocommerce/single-product/product-image.php
srg/woocommerce/single-product/product-thumbnails.php version 2.6.3 is out of date. The core version is 3.3.2
srg/woocommerce/single-product/rating.php version 2.3.2 is out of date. The core version is 3.1.0
srg/woocommerce/single-product/related.php
srg/woocommerce/single-product/review-meta.php version 2.6.0 is out of date. The core version is 3.4.0
srg/woocommerce/single-product/review-rating.php version 2.6.0 is out of date. The core version is 3.1.0
srg/woocommerce/single-product/review.php
srg/woocommerce/single-product/sale-flash.php
srg/woocommerce/single-product/share.php
srg/woocommerce/single-product/short-description.php version 1.6.4 is out of date. The core version is 3.3.0
srg/woocommerce/single-product/tabs/additional-information.php version 2.0.0 is out of date. The core version is 3.0.0
srg/woocommerce/single-product/tabs/description.php
srg/woocommerce/single-product/tabs/tabs.php
srg/woocommerce/single-product/title.php
srg/woocommerce/single-product/up-sells.php
srg/woocommerce/single-product-reviews.php version 2.3.2 is out of date. The core version is 3.2.0
srg/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update
`
</details>

**Comment by kloon** [comment]
Logged in #21101 already. Will continue discussions there.
