### ISSUE TITLE
_.indexBy was replaced or deprecated. _.indexBy was renamed to _.keyBy by lodash

### ISSUE THREAD

**Issue by tom-nguyen** [woocommerce/woocommerce#21978]
the issue happened in two shipping zone javascript file.

/woocommerce/assets/js/admin/wc-shipping-zones.min.js
/woocommerce/assets/js/admin/wc-shipping-zone-methods.min.js

replace **_.indexBy** to **_.keyBy** will help

**Comment by kloon** [comment]
See #21980

**Comment by mikejolley** [comment]
WooCommerce/WordPress uses underscores, not lodash.
