### ISSUE TITLE
Help with warning

### ISSUE THREAD

**Issue by fabiolaleonl** [woocommerce/woocommerce#21979]
I have a warning sign at the responde url of woocommerce that says:

Warning: number_format() expects parameter 1 to be float, string given in /home/glockcr/public_html/wp-content/plugins/woocommerce-payme-gateway/response.php on line 164

How can i fixed it?
Thank you so much for all the help

**Comment by kloon** [comment]
@fabiolaleonl we do not offer technical support on here, but in short your payment gateway seems like it is using the number_format function and passing a string to it where it should be passing a float value instead.
