### ISSUE TITLE
Disable scroll on delet product from cart in cart page

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#21988]
when deleting a item in the cart page after clicking the X for the product the page start scrolling when teh product is deleted.

How to prevent this from happening? Is this intentionally build in? If so cant it be turned off?  

Thank you

**Comment by kloon** [comment]
Yes, this is intentional so the customer can see the message displayed at the top, it scrolls to the message which will state the product has been removed from the cart.

**Comment by BackuPs** [comment]
Can there please be a filter or variable added to be set so it can be disabled?

**Comment by asha23** [comment]
+1 - It's actually counter-productive if you have a fixed header and actually scrolls until the message is hidden.

There should be an option to disable it.

**Comment by kloon** [comment]
Feel free to add a filter in a PR if you have some time.

**Comment by BackuPs** [comment]
HUH?  I am asking woo to do this. Should i unload the woo js and add my own ?  Bizar answer !

**Comment by arslion** [comment]
> HUH? I am asking woo to do this. Should i unload the woo js and add my own ? Bizar answer !

Got this working on update cart using this code:

```
var timeout;
 
jQuery( function( $ ) {
	$('.woocommerce').on('change', 'input.qty', function(){
 
		if ( timeout !== undefined ) {
			clearTimeout( timeout );
		}

		timeout = setTimeout(function() {
			$("[name='update_cart']").trigger("click");
			document.location.reload(true);
	});
});

```

**Comment by the-alex-mark** [comment]
```php
remove_action('woocommerce_before_cart', 'woocommerce_output_all_notices', 10);
```

**Comment by jpedrosas2** [comment]
> ```
> remove_action('woocommerce_before_cart', 'woocommerce_output_all_notices', 10);
> ```

So far the quickest fix and solution for removing the auto-scroll to top after updating quantity.

**Comment by 1stwebdesigns** [comment]
@the-alex-mark @jpedrosas2 the problem is, whilst this removes the cart notice from the cart page, the notice then appears on the next page that you view (for example a product category).  To make matters worse, if you update or delete say 10 items in your cart, when you go to the product category page you will then see 10 cart notice messages stacked up.
