### ISSUE TITLE
3.5.1: if theme fails to `add_theme_support woocommerce`, we should probably still avoid flushing permalinks on every request

### ISSUE THREAD

**Issue by lkraav** [woocommerce/woocommerce#21993]
**Is your feature request related to a problem? Please describe.**

Scenario:
* `plugins/woocommerce` is activated
* theme does **not** declare `add_theme_support woocommerce` (for whatever reason, for example the user is testing different themes)

https://github.com/woocommerce/woocommerce/blob/3.5.1/includes/class-wc-post-types.php#L293 causes permalinks to get flushed on every request, causing major slowdown via `update_option()`, object cache updates etc.

I file it as an enhancement, not a bug, since I'm not sure it's a scenario we should worry about much, but something seems off about it for sure.

**Describe the solution you'd like**

Not sure. Should probably **not** flush permalinks on every request, regardless of the situation.

Code comment `// If theme support changes, we may need to flush permalinks since some are changed based on this flag.` is very vague and doesn't describe "why".

Maybe when we detect this scenario, we should display an admin warning, at minimum, to raise awareness.

**Describe alternatives you've considered**

Same as above.

**Additional context**

I happened to come across this because I'm developing a new theme, and simply hadn't implemented `add_theme_support woocommerce` yet. But page load speeds were worryingly slow on a blank theme, so I Xdebugged it.

**Comment by lkraav** [comment]
Hm. 2 things may be in play:

1. object cache via https://github.com/tillkruss/redis-cache/
2. mu-plugin from https://github.com/Automattic/vip-go-mu-plugins-built/blob/master/misc.php#L68-L85

Your thoughts?

**Comment by rrennick** [comment]
Not the vip plugin. The `updated_option` hook is only fired if the option is changed - https://github.com/WordPress/WordPress/blob/master/wp-includes/option.php#L422

There might be an issue with one of the caching plugins but caching plugins provide the underlying layer of `wp_cache_*` functionality vs any of the `*_option` functionality.

**Comment by lkraav** [comment]
Yes, indeed, I missed that part before. Another vector in play:

* multiple themes available, switchable via https://github.com/Rarst/toolbar-theme-switcher
* main theme has declared `add_theme_support woocommerce`
* new theme, cookie-activated, did not (that's how I discovered slowdown)
* there's a 5-minute interval WP-CLI cron job running, that I believe would be triggering main theme (because why wouldn't it?)

So perhaps this combo is the reason there would a constant back-and-forth `update_option()` and rewrite rule flush.

I'm starting to suspect this is a local configuration issue instead and upstream logic is actually doing the best it can do. Tyvm for pointing out the `update_option()` conditional details.

**Comment by rrennick** [comment]
You're welcome. I'm glad you were able to track ti down.
