### ISSUE TITLE
Fix display of notices in My Account

### ISSUE THREAD

**Issue by edwardkay** [woocommerce/woocommerce#21996]
**Is your feature request related to a problem? Please describe.**
https://github.com/woocommerce/woocommerce/pull/19794/ moved the output of notices to a hook.

The priority of `add_action( 'woocommerce_account_content', 'woocommerce_output_all_notices', 10 )` is the same as `add_action( 'woocommerce_account_content', 'woocommerce_account_content' )`, i.e. 10.

Since the `woocommerce_output_all_notices` call is added later in the code, any notices on the My Account dashboard (e.g. 'Are you sure you want to log out?) are shown at the bottom of the screen, not the top where they used to be.

This means they're easily missed by users.

**Describe the solution you'd like**
Adjust the priorities so the notices are output before the account content.

e.g. `add_action( 'woocommerce_account_content', 'woocommerce_output_all_notices', 5 )`

**Comment by kloon** [comment]
@edwardkay how have you tested this? Notices display fine for me before the content. What theme have you tested this with?

**Comment by edwardkay** [comment]
I've tested with a fresh install - just TwentySeventeen and vanilla WooCommerce plugin. Nothing else.

See attached screenshot - the notices are shown below the my account content. It looks OK here as there's not much content on the dashboard. But on the main site I found this on, the dashboard has a lot more info (memberships, events, custom messages). The notice is easily lost at the bottom. Changing the priority of the hooks fixes it and puts the notices at the top.

![screenshot 2018-11-21 at 11 53 59](https://user-images.githubusercontent.com/299935/48839835-adac0d00-ed84-11e8-9bf6-7a1997dcb2c6.png)

**Comment by edwardkay** [comment]
BTW, before https://github.com/woocommerce/woocommerce/pull/19794 the `wc_print_notices()` call was made before `do_action( 'woocommerce_account_navigation' )`.

This resulted in the notices taking the full-width of the container, rather than in the smaller area aside the account navigation.

Another solution would be to add a new action to the top of the `myaccount/my-account.php` template and change the `add_action( 'woocommerce_account_content', 'woocommerce_output_all_notices', 10 ) hook to match this new action.

**Comment by edwardkay** [comment]
Any further thoughts on this @kloon (or others)?

As it stands, I've had to change the priorities in my version of WooCommerce. This is far from ideal when it comes to updating...

**Comment by kloon** [comment]
@edwardkay as mentioned before I am unable to replicate this. Could you perhaps zip up your theme as is and provide it to me so I can take a look? I am also testing with twentyseventeen.

**Comment by edwardkay** [comment]
@kloon Sure - https://www.dropbox.com/s/7uzfnfup1blxez8/woo-issue-21996-wp-content.zip?dl=0

This is the full `wp-content` folder to show it happens with just WooCommerce and Twenty Seventeen.

Good examples are `/my-account/customer-logout` (without the nonce), or going to account details and saving without required fields – see the error is placed at the bottom.

![my account woo](https://user-images.githubusercontent.com/299935/49715137-58f30800-fc47-11e8-84b7-76fd8e87806e.png)

**Comment by omoikane** [comment]
I can confirm the problem.

The solutions are these, but require a modification of WooCommerce:
1. Change the priority as suggested by @edwardkay 
2. Change the code execution order (before the notices, then the rest)

Waiting for an official solution, you can deactivate and reactivate the hook with a different priority:

```php
add_action('init', function () {
    remove_action( 'woocommerce_account_content', 'woocommerce_output_all_notices');
    add_action( 'woocommerce_account_content', 'woocommerce_output_all_notices', 5 );
}, 100);
```

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/22445

**Comment by edwardkay** [comment]
👍 Thanks @mikejolley
