### ISSUE TITLE
Improve Woocommerce tax and refund reports

### ISSUE THREAD

**Issue by karofairy** [woocommerce/woocommerce#22007]
**Is your feature request related to a problem? Please describe.**

Refunds create discrepancy in the woocommerce tax report. I saw several tickets here reporting similar problems.

The problem that is happening for me is the following:
I sell product A, price 360€ including 10% VAT (32,72€)
On the same day, I've made a partial refund for product B, 175€ in total (of which VAT = 15,91€)

However, in the woocommerce daily tax report, the sales column displays the total sales as 185€ (=360€ - 175€, the sum total of sales and refunds) BUT the VAT column shows 32,72€ (the VAT for the sales that day, i.e. does not deduct the VAT from the refund). This is very, very confusing accounting-wise because the numbers do not match up. The report should be consistent and have 185€ for sales and 16,81€ VAT. Or, even better, the  tax report should be improved to clearly distinguish sales and refunds on a day-by-day basis as well as have a breakdown of sales by the VAT % (see below).

The tax reports are confusing also because the woocommerce report area has no reports of the refunds made that month. So it's impossible to check at-a-glance on what date I have made refunds. And in the woocommerce orders the orders are listed according to order date, so if I have made several refunds in a given month, I have to manually go through all of them to find out what days they were made on, to check the numbers in the tax report and ensure everything adds up.
Moreover, for clarity, the daily tax report should show a breakdown of daily sales and refunds. 

**Describe the solution you'd like**

Have a report showing the breakdown of the refunds made in that month (day, sum, taxes, etc)

Improve the Woocommerce daily tax report, for example like this (with each date having 3 lines):

[Date]
Line 1: Sales    [Total net sales]      [Total VAT]           [Total gross sales]
Line 2: Refunds   [Total net refunds]       [Total refunded VAT]            [Total gross refunds]
Line 3: Sum total (= Line 1 - Line 3)

--> clear, concise, consistent tax reports that accountants (and your woocommerce customers!) will love!! This should not be very difficult to do, it's pretty basic excel stuff.

In addition, it would be great if the tax report creates distinct reports based on the VAT %. For example first listing all sales (and refunds), as above, that have VAT 10%. Then the following section has all sales and refunds that have VAT 24%.

**Describe alternatives you've considered**

Not refunding orders via woocommerce because refunds create such problematic tax reports.

**Additional context**

**Comment by claudiulodro** [comment]
Closing in favor of #21779, as the issue seems to be basically the same.
