### ISSUE TITLE
update woocommerce from 3.1 to 3.5

### ISSUE THREAD

**Issue by yanuardev** [woocommerce/woocommerce#22003]
**Describe the bug**
I use woocommerce 3.1 in wpmu sites and it works great until update to 3.5. the database update keeps failing and give me this error:

ALTER TABLE `wp_4_wc_download_log` ADD CONSTRAINT `fk_wc_download_log_permission_id` FOREIGN KEY (`permission_id`) REFERENCES `wp_4_woocommerce_downloadable_product_permissions` (`permission_id`) ON DELETE CASCADE	Error Code: 1022. Can't write; duplicate key in table '#sql-1fa6_7ca5e0'

I think it's because wc use same constraint for all sub sites (fk_wc_download_log_permission_id) and make fk_count condition failed so alter table executed and failed. This sql run in init hook makes my resource full.

**To Reproduce**
1. Install WC 3.1
2. Update to WC 3.5
3. Update WC database

I hope this help and please point me to the correct instruction if I did it wrong. thanks

**Comment by kloon** [comment]
This will be fixed in 3.5.2 which is due to be release in the next week. See #21836
