### ISSUE TITLE
Cart: missing validation to fields for changing the address 

### ISSUE THREAD

**Issue by MartaPawlonka** [woocommerce/woocommerce#22016]
When I want to change the address on the Cart page, by changing only the Country I am able to click 'Update'. But after that nothing happens and I still see the same address as before.

1. Go to 'Cart'
2. Click on 'Change address'
3. Change only 'Country' field.
4. Click 'Update' button.

http://take.ms/xGwgE
http://take.ms/ZcFklj - still UK

It's really confusing. I suggest adding the validation to not be able to click the 'Update' button. And mark all the fields as required fields to change.

- [ ] I have deactivated other plugins and confirmed this bug occurs when the only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

All Wordpress Environments

**Comment by mikejolley** [comment]
I get this:

![cart test s galore 2019-01-17 11-42-52](https://user-images.githubusercontent.com/90977/51316608-0dedc100-1a4d-11e9-81a4-c99a65116075.png)

Validation is performed.
