### ISSUE TITLE
Display exc and inc tax for Prizes and Prize Range for variation

### ISSUE THREAD

**Issue by mexgui** [woocommerce/woocommerce#22014]
Problem is: Currently Worpress has options to display prizes as including tax or excluding tax.

Pro
Problem for seller: Seller can sell both Companies and Inviduals, so they need to display both prizes in shop, cart, and all the places where prize and prize range for variation are displayed.

Currently woocommerze displays like this:

10 € (excluding tax)
10 - 100 € (excluding tx for variations)
or
12,4 € (Including 24% VAT)
12,4 - 124 € (including 24% VAT)

But we who sell tilexample mostly to businesse but sometimes inviduals also buy, we need to display both prizes.

Output:
10 € VAT excluded
12,4 € VAT included

and for variations

10 - 100 € VAT excluded
12,4 - 124 € VAT included

So please add obtion to display both prizes and add text to not inclusion and inclusing vat prizes for localization.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mikejolley** [comment]
You can add a 'suffix' in tax options and include the inc/ex price there. See the help tooltip for info.

This works in most places with the exception of variable product range because with those it's not possible to know the tax options of the individual variations. Try it and you'll see.

Thanks
