### ISSUE TITLE
WooCommerce batch update webhooks not working.

### ISSUE THREAD

**Issue by saifrehman15** [woocommerce/woocommerce#22019]
WooCommerce batch update webhooks not working.

I am trying to create webhooks programatically using the WooCommerce's Rest API with Laravel library( https://packagist.org/packages/automattic/woocommerce).

I can successfully can retrieve orders, products etc . But unable to create batch webhook which is menction at https://woocommerce.github.io/woocommerce-rest-api-docs/#batch-update-webhooks.

Here is the php script that I have written:
$data = [
    'create' => [
    [
        'name' => 'Round toe',
        'topic' => 'coupon.created',
        'delivery_url' => 'http://requestb.in/1g0sxmo1'
    ],
    [
        'name' => 'Customer deleted',
        'topic' => 'customer.deleted',
        'delivery_url' => 'http://requestb.in/1g0sxmo1'
    ]],
    'delete' => [
        143
    ]
];

print_r($woocommerce->post('webhooks/batch', $data));

Here is th error message that i got from woocommerce api.

{ "error": "Error: No route was found matching the URL and request method [woocommerce_api_no_route]"

}

**Comment by rrennick** [comment]
I updated the test data to be consistent with the documentation & it worked for me

```json
{"create":[{"name":"Round toe","topic":"coupon.created","delivery_url":"http://requestb.in/1g0sxmo1"},{"name":"Customer deleted","topic":"customer.deleted","delivery_url":"http://requestb.in/1g0sxmo1"}],"delete":[143]}
```

**Comment by saifrehman15** [comment]
Thanks for replying. It means there is a problem on my side. Kindly share your code sample with me that worked for you.

**Comment by kloon** [comment]
@rrennick shared the sample JSON he used, I tested and confirms it works. A quick look at your code the data seems fine, the error indicates the endpoint you are calling does not exists, or you are not authenticating the request, my gut is telling me it is the latter.

Cannot really tell much since it seems like you are using some sort of library so the issue could be there. I would say make sure you are authenticating your requests as this enpoint will require a write permission authenticated call.

Here is the cURL I tested with on my local dev environment
```
curl -X POST \
  'https://wc.local/wp-json/wc/v3/webhooks/batch?oauth_consumer_key=ck_0a9e22d1d03bfe64d8090017406309ebeabf07a1&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1542959694&oauth_nonce=OL2uvMrd0wh&oauth_version=1.0&oauth_signature=gtjOCVpDzTppah4WBLFw7gbzSJI=' \
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache' \
  -d '{"create":[{"name":"Round toe","topic":"coupon.created","delivery_url":"http://requestb.in/1g0sxmo1"},{"name":"Customer deleted","topic":"customer.deleted","delivery_url":"http://requestb.in/1g0sxmo1"}],"delete":[143]}'
```

**Comment by saifrehman15** [comment]
Thank you for quick reply. I can grab everything using the library i-e order , product also can create customers as well. I also can create the individual web-hook as well using woocommerce rest api. I have both read/write access. 
I also have made the curl call like you and receive the following error. 

{"code":"woocommerce_rest_cannot_batch","message":"Sorry, you are not allowed to batch manipulate this resource.","data":{"status":401}}

My wordpress site is hosted on http not https. I think this could be an issue.

**Comment by kloon** [comment]
Check your API user permissions, I believe you need it tied to a admin user for webhooks.

**Comment by saifrehman15** [comment]
I am already trying it with admin user. I am able to "Create a webhook" but still unable to "Batch update webhooks".

**Comment by amirvenus** [comment]
This issue is still there! I am not able to send batch request to update products even though I am an administrator.

`{"code":"woocommerce_rest_cannot_batch","message":"Sorry, you are not allowed to batch manipulate this resource.","data":{"status":401}}`

**Comment by jayantsr83** [comment]
Is it necessary to send `deliver_url` like `http://requestb.in/1g0sxmo1` . Can't I send the direct URL of my website?
