### ISSUE TITLE
WP CLI Sample Data Import

### ISSUE THREAD

**Issue by NenadObradovic** [woocommerce/woocommerce#22020]
Hi guys,

Could you please test your sample_products.xml file when you try to import demo content via WP CLI?

I have the problem with attributions, where during the import no attributes are imported, I used this code below for it

`wp import wp-content/plugins/woocommerce/sample-data/sample_products.xml --authors=create`

Also it will be great if you could extend your wc tool command with initial setup steps (Run The Setup Wizard feature) in order to configure whole WooCommerce through command line 

Thanks for your time

Best regards,
Nenad

**Comment by rrennick** [comment]
I am able to reproduce this in a new install. It looks like the issue is that the terms & taxonomies associated with product attributes are not being created if they don't exist.

**Comment by kloon** [comment]
There are some issues with the XML file we are aware of and in progress to fix #21727
