### ISSUE TITLE
Structured Data for Products since Woo 3.4.5.+ under Breadcrumbs!

### ISSUE THREAD

**Issue by Bart-DS** [woocommerce/woocommerce#22024]
Structured Data for Products since Woo 3.4.5.+ under Breadcrumbs! Effect on SEO is tremendous!

**To Reproduce**
You can test a Woo 3.4.5.+ via https://search.google.com/structured-data/testing-tool
The “product” structure data is now in the Breadcrumbs data instead of being on top and causes enormous decline in SEO results!!!

**Screenshots**
Good/old Woo version:
https://i.postimg.cc/RhYVDhb7/QIP-Shot-Screen-3731-20-11-18.jpg

Bad/3.4.5. or higher version:
https://i.postimg.cc/j5RtjP7q/QIP-Shot-Screen-3733-20-11-18.jpg 

**Expected behavior**
Getting it fixed asap

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
The priority on those hooks in the template have not changed since 3.4.0

https://github.com/woocommerce/woocommerce/blob/master/templates/archive-product.php#L26:27
https://github.com/woocommerce/woocommerce/blob/3.4.0/templates/archive-product.php#L26:L27

**Comment by Bart-DS** [comment]
Hi, could be.... than it is a older problem or has to do with something else in Woo. 
We are not the only ones who experience this... see for instance:
https://wordpress.org/support/topic/problem-with-structured-data-2/
https://wordpress.org/support/topic/structured-data-bug-2/
https://wordpress.org/support/topic/no-structured-data-for-products-since-woo-3-4-5/

**Comment by Bart-DS** [comment]
There are always updates for our theme.. But with Storefront its the same problem... 
Ps. the Woocommerce Storefront demo shop is an old Woo version... has not that problem)

**Comment by rrennick** [comment]
> the Woocommerce Storefront demo shop is an old Woo version... has not that problem)

Unfortunately, the CSS is minified so I'm not able to determine what the theme version is.

**Comment by hannahswain** [comment]
I was able to check the Storefront demo:
https://themes.woocommerce.com/storefront/

`
WC Version: 3.2.1
WP Version: 4.9.8
Name: Storefront Version: 2.3.3 – 2.3.5 is available
`

Full system status log available here: https://cld.wthms.co/YX16pO

**Comment by MoeMauhphie** [comment]
The problem, as explained [here](https://webmasters.stackexchange.com/questions/119064/json-ld-problem-with-non-latin-characters-product-appears-as-last-item-of-bread/119115#119115), is related to @id in structured data. Breadcrumb and Product should not have the same id.

**Comment by Bart-DS** [comment]
> 
> 
> I was able to check the Storefront demo:
> https://themes.woocommerce.com/storefront/
> 
> ```
> WC Version: 3.2.1
> WP Version: 4.9.8
> Storefront Version: 2.3.3 – 2.3.5 is available
> ```
> 
> Full system status log available here: https://cld.wthms.co/YX16pO

Tnx, and yes that is the  WC version as a mentioned before... the problem is in the newer ones.

**Comment by Bart-DS** [comment]
> 
> 
> The problem, as explained [here](https://webmasters.stackexchange.com/questions/119064/json-ld-problem-with-non-latin-characters-product-appears-as-last-item-of-bread/119115#119115), is related to @id in structured data. Breadcrumb and Product should not have the same id.

Tnx, hope it will be solved asap... because it has a hugs impact on the SEO for shops.

**Comment by claudiulodro** [comment]
Should be solved in #22045

**Comment by rrennick** [comment]
> This does not appear to be working.

The fix for this will be included in 3.5.3.
