### ISSUE TITLE
Wrong price calculation after percent based coupon applied

### ISSUE THREAD

**Issue by mariusmateoc** [woocommerce/woocommerce#22034]
**Describe the bug**
Order wrong calculation after applied the percent based coupon. After you reproduce the behavior you will receive this results:

```€2,69 × 25 = €67,28 ``` **(WRONG)**

```€0,30 x 25 = €7,47 ``` **(WRONG)**

Item total is not calculated based on rounded item price which is shown and respect the number of decimals option set.

When I send the order data to other API's, they receive other results than the customer has paid for.

**To Reproduce**
1. Create a product with the price: 2.99
2. Create a coupon based on percent discount: 10%
3. Create an order where you add the product with 25 quantity
4. Apply the coupon to the order
5. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/2094443/48967698-e5b18b00-efe4-11e8-8f58-edf4a7d37d2d.png)

**Expected behavior**
Since "Number of Decimals: 2" I expected that the result(total) should be calculated with the product rounded price not calculating with 4 decimals.

Item total expected to be: product cost multiplied by quantity but keeping in mind the number of decimals. (total should be calculated after the product price was rounded to a number of decimals set)
```€2,69 × 25 = €67,25``` **(Expected)**

Same goes for applied discount.
```€0,30 x 25 = €7,50``` **(Expected)**

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

```
### WordPress Environment ###

Home URL: http://example.test
Site URL: http://example.test/wp
WC Version: 3.5.1
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.15.6
PHP Version: 7.2.12-1+ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 25 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.19-MariaDB-10.2.19+maria~xenial
Max Upload Size: 25 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 1.88MB
Database Data Size: 1.04MB
Database Index Size: 0.84MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 0.50MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

customize_changeset: 1
page: 8
post: 2
product: 1
revision: 2
shop_coupon: 1
shop_order: 6

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.5.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

```

</details>

**Comment by rrennick** [comment]
I tested this in 3.5.1 and am seeing the correct calculations.

<img width="713" alt="screen shot 2018-11-28 at 3 09 29 pm" src="https://user-images.githubusercontent.com/343847/49175972-2b8d8c80-f320-11e8-8d89-5081f17f63d8.png">
<img width="713" alt="screen shot 2018-11-28 at 3 08 45 pm" src="https://user-images.githubusercontent.com/343847/49175973-2b8d8c80-f320-11e8-9b11-5b7ee5c4bfc3.png">

**Comment by mariusmateoc** [comment]
Thanks @rrennick for looking at this. But using the first example you give, for my point of view is still wrong:

Item calculation:  `2.42 x 25 = 60.53` ---> Result should be: **$60.50**
Discount calculation:  `0.27 x 25 = 6.72` ---> Result should be: **$6.75**

I send the item price to another API along with the quantity to generate the invoice and they calculate the total based on this things but they get another amount on the invoice to what they paid in woocommerce.

**Comment by rrennick** [comment]
> Result should be: $6.75

10% of 67.25 is 6.72 (or 6.73 if rounded up).

**Comment by rrennick** [comment]
There are several discount plugins (ex. https://wordpress.org/plugins/woo-discount-rules/) that might provide you with the custom calculation you want.

**Comment by mariusmateoc** [comment]
Thanks, @rrennick I will give a try to that plugin.

Now regarding the order UI maybe we should put a note if a discount is applied to not confuse the user with that calculation like: "Discount is applied to the total amount before taxes and calculations are made using 4 decimals."

To not clutter the UI I think just an info icon below last item or on product item since the discount can be applied to products and categories.

![image](https://user-images.githubusercontent.com/2094443/49493251-b65c1300-f85b-11e8-937c-9551550da8a9.png)

Also, I think that a filter where you can set if you want to apply the discount to the product itself or product total.

**Comment by mikejolley** [comment]
Added clarification in https://github.com/woocommerce/woocommerce/pull/22421
