### ISSUE TITLE
checkout_fields PHP undefined index

### ISSUE THREAD

**Issue by krbvroc1** [woocommerce/woocommerce#22038]
**Describe the bug**
I believe the following are related - 
1) PHP Notice:  Undefined index: priority in /opt/www/stpdev/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 1526
2) PHP Warning:  uasort(): Array was modified by the user comparison function in /opt/www/stpdev/wp-content/plugins/woocommerce/includes/class-wc-checkout.php on line 245

Code was added in 3.5.1 to 'sort' based on priority. However the account and order sections do not have a priority (only billing and shipping).

**To Reproduce**
1. Peform an action that triggers checkout field display such as checking out

**Isolating the problem (mark completed items with an [x]):**
- [] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
WP 4.9.8 and WC 3.5.1
```
</details>

**Comment by krbvroc1** [comment]
I was pointing to the specific issue in the code (account and order sections not getting a priority) but as far as reproducing, both 'woocommerce_registration_generate_username' and ''woocommerce_registration_generate_password'  options being set to 'no' will add 'account' fields (in class-wc-checkout.php) without a priority. That probably maps to checking out as a guest, but maybe some other scenarios too.

**Comment by rrennick** [comment]
@krbvroc1 Thanks. I should have a chance to look at that later today.

**Comment by rrennick** [comment]
This one was fixed in https://github.com/woocommerce/woocommerce/commit/800ed5fe739f6cdec474b9d60da2e158f55c6ad7#diff-c49e4a77afbd1a753435a745896942a2 .
