### ISSUE TITLE
Failed braintree payment forwards to cart-errors.php and thus gives a cryptic error to customer.

### ISSUE THREAD

**Issue by Nigelje** [woocommerce/woocommerce#22030]
A failed card payment directs to cart-errors.php. As the wc_print_notices() has been removed and the error text changed. This leads to a very confusing situation for the customer. There is no indication that it's an issue with the card and the error text will make the customer thinks its a site issue.

**Describe the solution you'd like**
A more appropriate error message to the customer, as previously displayed with wc_print_notices

**Comment by mikejolley** [comment]
There has been a PR for next minor WooCommerce release to add the notice output function back to checkout. This does however need to be reported to braintree extension developer or the help desk as it's a problem specific to a gateway not core and may required testing on it's side.

Thanks
