### ISSUE TITLE
Redirect to checkout with wc_add_notice (error) fails

### ISSUE THREAD

**Issue by sandrodz** [woocommerce/woocommerce#22048]
Following code:
```
wc_add_notice( __( 'Payment failed.', 'gateway' ), 'error' );
wp_safe_redirect( wc_get_page_permalink( 'checkout' ) );
```

Will display this error:
<img width="956" alt="screen shot 2018-11-26 at 8 47 46 pm" src="https://user-images.githubusercontent.com/8479569/49028755-92923080-f1bc-11e8-86d1-91c8bfa1e919.png">

If I redirect to cart instead errors will show fine, and checkout will be accessible again, after error has been cleared.

```
wc_add_notice( __( 'Payment failed.', 'gateway' ), 'error' );
wp_safe_redirect( wc_get_page_permalink( 'cart' ) );
```

<img width="1135" alt="screen shot 2018-11-28 at 12 31 20 am" src="https://user-images.githubusercontent.com/8479569/49109758-fabc4180-f2a4-11e8-853e-9e4ee3210059.png">

Redirecting to checkout with errors is useful when payment gateway fails, e.g. insufficient funds.

A lot of the payment plugins I've seen in the wild actually redirect to checkout with errors, so at some point this was working correctly. Is this a regression? For example: https://github.com/woocommerce/woocommerce-gateway-stripe/blob/master/includes/class-wc-stripe-order-handler.php#L197

I also looked at other gateways included in the WooCommerce and it seems `simplify-commerce` redirects to `cart` not `checkout`.

So it is a mixed beg, either WooCommerce team should provide a clear guideline on this, or both cases should work as expected. e.g. redirecting with errors on cart or checkout.

**Comment by sarun007** [comment]
Hello is there any update for this issue ??

**Comment by sandrodz** [comment]
@sarun007 I've asked around on slack channel. No response. I think we should update plugins to redirect to cart with error. This is the only solution atm.

**Comment by jjcoffee** [comment]
I think this is related to [this](https://github.com/woocommerce/woocommerce/issues/21861) issue I opened? It looks like it's something to do with the removal of direct calls to wc_print_notices here https://github.com/woocommerce/woocommerce/commit/efe06cb14752bdfe2c18274783eac221cbeea5ff#diff-e0339102757f25bb408b014dbef0ee41L221

**Comment by sandrodz** [comment]
@jjcoffee seems like. As wording of the error suggests https://github.com/woocommerce/woocommerce/commit/efe06cb14752bdfe2c18274783eac221cbeea5ff#diff-08b82e20f5eabb631774c0773ce27eefR21, they want us to redirect users to cart with error it seems and avoid checkout. It kinda makes sense, if you have no money and card was declined, why redirect to checkout? cart makes sense, so client can remove some products.

I started updating my payment plugins. I hope someone from Woo will shed light on the direction of these changes.

**Comment by jjcoffee** [comment]
@sandrodz Possibly, but I think it looks more accidental than anything. They're just not handling the case where the checkout reloads with messages to display - this happens and is handled fine for ajax payment errors, it's only when the checkout needs to reload there is nowhere for errors to output, hence the redirect to the cart errors page.

**Comment by moduca** [comment]
I am experiencing exactly the same problem.

I am using WordPress Versión 5.0.2 with WooCommerce  3.5.3.

**Comment by progcode** [comment]
I am experiencing exactly the same problem. Please fix asap.

**Comment by elzix** [comment]
I discovered a workaround:

In my scenario, I do not have a cart page. If a customer proceeds to payment website (external) and cancels, they are taken back to the website with `$_REQUEST['cancelled']` set. On that page I had:
```
if ( isset( $_REQUEST['cancelled'] ) ) {
    wc_add_notice( __( 'Transaction cancelled. Please try again.', 'woothemes' ), 'error' );
    wp_redirect( add_query_arg( 'cancelled', 'true', wc_get_checkout_url() ) );exit;
}
```

Then I realized that my notices were not getting through the redirect. I did searches online to find that the error display on checkout was removed ages ago, forcing people to display them on the cart. This means I'd need to edit the plugin to bring it back...

That's when it hit me! Why not pass along the request:
```
if ( isset( $_REQUEST['cancelled'] ) ) {
    wp_redirect( add_query_arg( 'cancelled', 'true', wc_get_checkout_url() ) );exit;
}
```
Then on the template file `/checkout/form-checkout.php` in the theme, above the form:
```
if ( isset( $_REQUEST['cancelled'] ) )
    wc_add_notice( __( 'Transaction cancelled. Please try again.', 'woothemes' ), 'error' );
```

I hope this helps someone.

**Comment by KenPov** [comment]
Thank you a lot @elzix 
I spent my time to find it for whole day.
