### ISSUE TITLE
List of Greek states not shown in English

### ISSUE THREAD

**Issue by glagonikas** [woocommerce/woocommerce#22041]
**Describe the bug**
It appears the list of states for the Greek region is written only in Greek and there's no English translation on them.

On other regions like Iran (https://github.com/woocommerce/woocommerce/blob/master/i18n/states/IR.php) and China (https://github.com/woocommerce/woocommerce/blob/master/i18n/states/CN.php) the English translation of the region is show next to the local one.

**Side issue**
When comparing the Iranian and Chinese regions, the local name is not shown on the same format. One has the local version inside brackets ( ) and the other separated by forward slash / Ideally, WooCommerce should enforce a standard format.

**Comment by glagonikas** [comment]
@teomaragakis as you've previously made a number of changes on the affected file, you might want to have a look at this issue and the linked PR in case it affects any of your projects.

**Comment by franticpsyx** [comment]
@glagonikas wondering if you could check out https://github.com/woocommerce/woocommerce/pull/21945

Might be a good idea to consolidate the discussion there.

> When comparing the Iranian and Chinese regions, the local name is not shown on the same format. One has the local version inside brackets ( ) and the other separated by forward slash / Ideally, WooCommerce should enforce a standard format.

I guess the main thing to discuss here is whether the default text should contain a translation, or not. As you said, WooCommerce is currently not very consistent with this: While countries are always in English by default, states/regions are sometimes localized, and sometimes there's both an English+localized version in the default text string.

IMO when there's a standardized (ISO) English version of a region, the default text string should utilize that one.

**Comment by teomaragakis** [comment]
> @teomaragakis as you've previously made a number of changes on the affected file, you might want to have a look at this issue and the linked PR in case it affects any of your projects.

No, I'm good, thank you for the consideration though, much appreciated.

**Comment by glagonikas** [comment]
Oh i missed this PR, sorry.

@franticpsyx Your PR is better for me, but to avoid any breaking changes for existing Greek stores, i opted for the approach followed on the CN and IR countries.

As you've already made some progress on this, we can close this issue and my PR, but should probably create a new issue regarding standardisation of the states

**Comment by franticpsyx** [comment]
> should probably create a new issue

Probably! A few years ago I was in charge of a fulfillment team -- I remember being challenged by this issue because sometimes the shipping address would contain characters that our DHL integration couldn't handle. Had to translate the localized regions back to english, and it sure took a while!

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/21945
