### ISSUE TITLE
woocommerce-additional-variation-images plugin is too outdated

### ISSUE THREAD

**Issue by manake** [woocommerce/woocommerce#22059]
**Describe the bug**
This plugin https://woocommerce.com/products/woocommerce-additional-variation-images/ (version 1.7.14) doesn't work.

Issues in that plugin:
1. It initializes `$( this ).wc_product_gallery();` which is double initialization of PhotoSwipe and it breaks PhotoSwipe that way.
2. It runs AJAX and initialization right after opening the page when there is no need? Why? This is a bug.
3. On switching variation in select it does some weird things. E.g. the image is becoming instantly replaced but then the second loading happens and replaces all images again?
4. It contains code for WooCommerce pre-2.3 and pre-3.0. Please remove this.
5. It has wrong `gallery_images_class` CSS selector and doesn't work with WooCommerce 3.5.1 anymore. The loading indication doesn't appear.
6. When I switch variations - `variation A` to `variation B` - and then back `variation B` to `variation A` then PhotoSwipe still shows me pictures from `variation B`.

Conclusion: That plugin is currently broken.

Issues in WooCommerce:
1. Your `wp-content/plugins/woocommerce/assets/js/frontend/single-product.js` has a bug that it doesn't prevent double initialization.
2. In `wp-content/plugins/woocommerce/assets/js/frontend/single-product.js` it would be good if you created a `destroy()` function.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by claudiulodro** [comment]
Hi,

Thanks for the report, but we can't support other plugins at this GitHub repo, only the core WooCommerce plugin. Please [open a support ticket](https://woocommerce.com/my-account/create-a-ticket/) with this information, and the team for that plugin will investigate.

Thanks.

**Comment by manake** [comment]
Well, if you didn't do a mistake then the plugin would be almost working. So, it's primarily your problem.

Also, why is `reset_image` called on page load? This seems to be another WC bug. Nothing is being reset but the event is being triggered.

**Comment by claudiulodro** [comment]
We'll investigate whether we broke backwards compatibility.

**Comment by mikejolley** [comment]
This has since been updated https://dzv365zjfbd8v.cloudfront.net/changelogs/woocommerce-additional-variation-images/changelog.txt
