### ISSUE TITLE
Fix for error Warning: explode() expects parameter 2 to be string, array given 

### ISSUE THREAD

**Issue by vladletnabov** [woocommerce/woocommerce#22065]
I received error when try to see product category
`Warning: explode() expects parameter 2 to be string, array given in wp-content/plugins/woocommerce/includes/class-wc-query.php on line 448`

For fixing this problem i modified class-wc-query.php

[class-wc-query.zip](https://github.com/woocommerce/woocommerce/files/2624215/class-wc-query.zip)

Archive include patch for check $orderby_value on array

**Comment by rodrigoprimo** [comment]
See #22066
