### ISSUE TITLE
Price filter dissapears when out of range

### ISSUE THREAD

**Issue by ljackl** [woocommerce/woocommerce#22063]
The price filter widget disappears when a refinement is made which does not contain a product. Users then must then use the browsers back button or navigate to Home > Store to return to previous state.

Link to Wordpress forum post: 
https://wordpress.org/support/topic/price-filter-dissapears-when-out-of-range/#post-10921292

**Comment by ljackl** [comment]
> The price filter widget disappears when a refinement is made which does not contain a product. Users then must then use the browsers back button or navigate to Home > Store to return to previous state.

Link to Wordpress forum post: 
https://wordpress.org/support/topic/price-filter-dissapears-when-out-of-range/#post-10921292

**Comment by jakerambo** [comment]
Any word on resolving this? This is a pretty serious issue.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22303 We'll aim for 3.5.5
