### ISSUE TITLE
PHP Fatal error: Uncaught Error: Call to a member function get_image() on boolean

### ISSUE THREAD

**Issue by wcjonathan** [woocommerce/woocommerce#22068]
When attempting to view a list of products in WooCommerce administration panel, the list does not load. I'm not sure on how to reproduce this, however i do have a screenshot of the error in the logs.

![screenshot 2018-11-28 at 16 08 11](https://user-images.githubusercontent.com/20682216/49165267-ae1a4a00-f328-11e8-868d-fed7501f07c8.png)
![screenshot 2018-11-28 at 16 12 58](https://user-images.githubusercontent.com/20682216/49165277-b1153a80-f328-11e8-80f1-16349b241928.png)

I would expect to see a list of products here.

- [ X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).

I am currently using the latest Wordpress and WooCommerce installs.

**Comment by rrennick** [comment]
How long ago did you update WC?

**Comment by wcjonathan** [comment]
Hi, i updated today.

Thanks

**Comment by rrennick** [comment]
Can you try reinstalling the update?

**Comment by wcjonathan** [comment]
I've been able to find out why this is happening. 

If a product has a parent_id assigned to it in the wp_posts table, it tries to find the parent product to fetch its image. However if this parent no longer exists, the error occurs.

Setting the get_image function to this, resolves the issue. However i'm not sure how the products came to have a parent_id that no longer exists.
```

public function get_image( $size = 'woocommerce_thumbnail', $attr = array(), $placeholder = true ) {
                 if ( $this->get_image_id() ) {
                         $image = wp_get_attachment_image( $this->get_image_id(), $size, false, $attr );
                 } elseif ( $this->get_parent_id() ) {
                                 $parent_product = wc_get_product( $this->get_parent_id() );
                                 if($parent_product) {
                                         $image          = $parent_product->get_image( $size, $attr, $placeholder );
                                 } else {
                                         $image = '';
                                 }

                } elseif ( $placeholder ) {
                         $image = wc_placeholder_img( $size );
                 } else {
                         $image = '';
                 }

                return apply_filters( 'woocommerce_product_get_image', $image, $this, $size, $attr, $placeholder, $image );
        }

```
Thanks

**Comment by wcjonathan** [comment]
Or this works too..
```

public function get_image( $size = 'woocommerce_thumbnail', $attr = array(), $placeholder = true ) {
		if ( $this->get_image_id() ) {
			$image = wp_get_attachment_image( $this->get_image_id(), $size, false, $attr );
		} elseif ( $parent_product = wc_get_product( $this->get_parent_id() ) ) {
				$image          = $parent_product->get_image( $size, $attr, $placeholder );
		} elseif ( $placeholder ) {
			$image = wc_placeholder_img( $size );
		} else {
			$image = '';
		}

		return apply_filters( 'woocommerce_product_get_image', $image, $this, $size, $attr, $placeholder, $image );
	}
```
