### ISSUE TITLE
CSS Classname fixes for My Account Template 

### ISSUE THREAD

**Issue by Jonathlee** [woocommerce/woocommerce#22077]
template\my-account\form-login.php

line 49
```
<p class="woocommerce-form-row form-row">
```
fixes ("woocommerce-form-row")
```
<p class="form-row">
```

---------------------------------------

line 101 : 
```
<p class="woocommerce-FormRow form-row">
```
fixes ("woocommerce-form-row")
```
<p class="woocommerce-form-row form-row">
```

---------------------------------------

Please check if line 56
```
<p class="woocommerce-LostPassword lost_password">
```

require fixes ("woocommerce-lost-password")

```
<p class="woocommerce-lost-password lost_password">
```

**Comment by claudiulodro** [comment]
Hi there,

Thanks for the suggestion, but we cannot just change classes in the template files without breaking themes. The classes need to be maintained for backwards compatibility. I posted a little more about this at https://github.com/woocommerce/woocommerce/pull/22082#issuecomment-445999092
