### ISSUE TITLE
Turn the US Minor Outlying Islands state field into a dropdown.

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/woocommerce#22070]
**Is your feature request related to a problem? Please describe.**
I just ran into the issue of someone checking out and using the US Minor Outlying Islands as their country (they meant to choose the US) and entered TX in the state field. Checkout worked just fine but the problem is that they weren't charged sales tax. Our setup normally will charge them sales tax if the customer is from Texas.

**Describe the solution you'd like**
If someone selects the US Minor Outlying Islands country dropdown, the state field should be a predefined list of those states as well. That eliminates anyone from accidentally entering Texas or any other proper U.S. state.

**Comment by mikejolley** [comment]
If a country has an ISO code, we shoulnd't add it as a state. Whilst this would make it "easier" for some services like USPS, it's not officially a state and doing so would have implications for services like gateways which handling them correctly as countries.

The idea about the islands could be viable.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22468
