### ISSUE TITLE
Product Search Backend

### ISSUE THREAD

**Issue by FuneralParlour** [woocommerce/woocommerce#22089]
I have been having a very hard time searching for products, especially when creating an invoice and having to add a product. Even though I type in the exact product name, I get unrelated results.
This is because its searching through the entire description, excerpt, title, sku etc.
There is no need for all of this.

Making a hook or an option to remove searching titles and excerpts drastically speeds up the search, AND gives proper results, impossible to get with the way it is setup.

From WooCommerce Booster Trying to Help
*******************************************************************************************************
As promised I've searched today for a way to exclude product descriptions from WooCommerce "Search for a product..." box. I've discovered that the code that runs the search is in \wp-content\plugins\woocommerce\includes\data-stores\class-wc-product-data-store-cpt.php file in search_products() function which starts on line 1362. Unfortunately there are no filters there, but for a start we could (for testing purposes) try to remove searching by description directly in WooCommerce code to see if this really decreases the search time significantly. So could you please try modifying line 1402.

Initially the line is:

$term_group_query .= $wpdb->prepare( " {$searchand} ( ( posts.post_title LIKE %s) OR ( posts.post_excerpt LIKE %s) OR ( posts.post_content LIKE %s ) OR ( postmeta.meta_key = '_sku' AND postmeta.meta_value LIKE %s ) )", $like, $like, $like, $like ); // @codingStandardsIgnoreLine.

To exclude searching by description we need to replace this line with (i.e. remove OR ( posts.post_content LIKE %s )​ part):

$term_group_query .= $wpdb->prepare( " {$searchand} ( ( posts.post_title LIKE %s) OR ( posts.post_excerpt LIKE %s) OR ( postmeta.meta_key = '_sku' AND postmeta.meta_value LIKE %s ) )", $like, $like, $like, $like ); // @codingStandardsIgnoreLine.

Then we could also try exclude searching by excerpt (i.e. remove OR ( posts.post_excerpt LIKE %s)​ part):

$term_group_query .= $wpdb->prepare( " {$searchand} ( ( posts.post_title LIKE %s) OR ( postmeta.meta_key = '_sku' AND postmeta.meta_value LIKE %s ) )", $like, $like, $like, $like ); // @codingStandardsIgnoreLine.
*******************************************************************************************************

This last line works perfectly
$term_group_query .= $wpdb->prepare( " {$searchand} ( ( posts.post_title LIKE %s) OR ( postmeta.meta_key = '_sku' AND postmeta.meta_value LIKE %s ) )", $like, $like, $like, $like ); // @codingStandardsIgnoreLine.

I've tried it and very happy, but they cannot implement it into Booster cause there is no hook, and I just updated woocommerce and the change is gone, and also on a different line now. I was still able to make the change, but since it is quite a simple thing to do, can you implement this as an option, or hook so it can be done properly, without losing the changes as well after updates.

THANKS

Matt

**Comment by rodrigoprimo** [comment]
Thanks for your suggestion. Please see #22165. Any feedback there is welcome.
