### ISSUE TITLE
customizr theme image size larger than original 

### ISSUE THREAD

**Issue by mkmaskara** [woocommerce/woocommerce#22093]
When using Customizr theme, on Product Catalog page the thumbnail image size appears larger than the original size.
My original dimensions of the image are : 
Width : 156
Height : 192
Pixels : 96 px / inch
I want to have the same sizes to appear on my website's shop catalogue page which is viewed list wise after applying the plugin "WooCommerce Grid / List toggle"
I have tried with this coding in functions.php but am helpless.

_**function iconic_modify_theme_support() {
    $theme_support = get_theme_support( 'woocommerce' );
    $theme_support = is_array( $theme_support ) ? $theme_support[0] : array();
 
    $theme_support['single_image_width'] = 800;
    $theme_support['thumbnail_image_width'] = 156;
 
    remove_theme_support( 'woocommerce' );
    add_theme_support( 'woocommerce', $theme_support );
}
add_action( 'after_setup_theme', 'iconic_modify_theme_support', 10 );**_

I have even tried all the options under **_Appearance > Customize > WooCommerce > Product Images_** but that too are not working.

I have tried the options posted on **https://iconicwp.com/blog/manage-woocommerce-product-image-sizes-3-3/**
I am using WooCommerce 3.3+
Please advise.
Manoj

**Comment by rodrigoprimo** [comment]
Closing as this is not a support forum, if you require support then please use the WordDress.org forums (https://wordpress.org/support/plugin/woocommerce) or, if you are a paying WooCommerce.com customer, you can contact support http://woocommerce.com/contact-us for assistance.
