### ISSUE TITLE
REST API 401 

### ISSUE THREAD

**Issue by muctobi** [woocommerce/woocommerce#22095]
I am trying to connect a service to my WooCommerce for Fulfillment.

For some reasons i get a 401 response, with the App as well if i am testing with Postman

{
    "code": "woocommerce_rest_cannot_create",
    "message": "Entschuldigung, Sie haben keine Berechtigung, um Ressourcen zu erstellen.",
    "data": {
        "status": 401
    }
}

It seems that the Keys i create in WooCommerce seem to be not authorized or valid.
All my Wordpress and Woocommerce is updated to the latest version.

I had an old service connected through API which was working just fine. I don't know if this problem appeared through the last WooCommerce update or not.

REQUEST:

URL: 'https://xxx.yyy/wp-json/wc/v2/webhooks/batch'

HEADERS:
{'Content-Length': '1794', 'Accept-Encoding': 'gzip, deflate', 'accept': 'application/json', 'user-agent': 'WooCommerce API Client-Python/1.2.1', 'Connection': 'keep-alive', 'content-type': 'application/json;charset=utf-8', 'Authorization': 'Basic <HIDDEN KEY>'}

BODY:
{"create": [{"topic": "order.created", "secret": "<HIDDEN SECRET>", "name": "ZZZ 2359bb4f-358c-486f-b011-5ce663d7d8e7 order.created", "delivery_url": "https://ZZZ.cloud/v2/shop/merchants/woocommerce/2359bb4f-358c-486f-b011-5ce663d7d8e7/<HIDDEN SECRET>/webhook"}, {"topic": "order.updated", "secret": "<HIDDEN SECRET>", "name": "ZZZ 2359bb4f-358c-486f-b011-5ce663d7d8e7 order.updated", "delivery_url": "https://ZZZ.cloud/v2/shop/merchants/woocommerce/2359bb4f-358c-486f-b011-5ce663d7d8e7/<HIDDEN SECRET>/webhook"}, {"topic": "order.deleted", "secret": "<HIDDEN SECRET>", "name": "ZZZ 2359bb4f-358c-486f-b011-5ce663d7d8e7 order.deleted", "delivery_url": "https://ZZZ.cloud/v2/shop/merchants/woocommerce/2359bb4f-358c-486f-b011-5ce663d7d8e7/<HIDDEN SECRET>/webhook"}, {"topic": "product.created", "secret": "<HIDDEN SECRET>", "name": "ZZZ 2359bb4f-358c-486f-b011-5ce663d7d8e7 product.created", "delivery_url": "https://ZZZ.cloud/v2/shop/merchants/woocommerce/2359bb4f-358c-486f-b011-5ce663d7d8e7/<HIDDEN SECRET>/webhook"}, {"topic": "product.updated", "secret": "<HIDDEN SECRET>", "name": "ZZZ 2359bb4f-358c-486f-b011-5ce663d7d8e7 product.updated", "delivery_url": "https://ZZZ.cloud/v2/shop/merchants/woocommerce/2359bb4f-358c-486f-b011-5ce663d7d8e7/<HIDDEN SECRET>/webhook"}, {"topic": "product.deleted", "secret": "<HIDDEN SECRET>", "name": "ZZZ 2359bb4f-358c-486f-b011-5ce663d7d8e7 product.deleted", "delivery_url": "https://ZZZ.cloud/v2/shop/merchants/woocommerce/2359bb4f-358c-486f-b011-5ce663d7d8e7/<HIDDEN SECRET>/webhook"}]}

RESPONSE:

HEADERS:
{'X-Robots-Tag': 'noindex', 'X-Content-Type-Options': 'nosniff', 'X-Powered-By': 'PHP/7.1.24', 'Transfer-Encoding': 'chunked', 'Access-Control-Expose-Headers': 'X-WP-Total, X-WP-TotalPages', 'Server': 'nginx', 'Connection': 'keep-alive', 'Link': '<https://xxx.yyy/wp-json/>; rel="https://api.w.org/"', 'Date': 'Fri, 23 Nov 2018 09:31:55 GMT', 'Access-Control-Allow-Headers': 'Authorization, Content-Type', 'Content-Type': 'application/json; charset=UTF-8'}

RESPONSE:
{"code":"woocommerce_rest_cannot_batch","message":"Entschuldigung, Sie haben nicht die Berechtigung diese Ressource zu manipulieren.","data":{"status":401}}

**Comment by rrennick** [comment]
That request body worked fine for me. In your request headers you need a hash on your authorization

```
'Authorization': 'Basic {base64_encoded authorization}'
```

**Comment by rodrigoprimo** [comment]
What @rrennick mentioned above should help. Please note that this is not a support forum, if you require support then please use the WordDress.org forums (https://wordpress.org/support/plugin/woocommerce) or, if you are a paying WooCommerce.com customer, you can contact support http://woocommerce.com/contact-us for assistance.
