### ISSUE TITLE
Importing attributes via built in importer allows free editing of attribute values instead of selection fields.

### ISSUE THREAD

**Issue by conschneider** [woocommerce/woocommerce#22097]
**Describe the bug**
When using the built in importer to import a product with set product attributes and defined attribute values, the attribute values can be freely edited instead of having selection fields. Editing the value causes escape backslashes to be added to special characters such as apostrophes.

**To Reproduce**
1. Import custom attributes that have special characters in value fields. Preferably an apostrophe. [test_CSV - Sheet1.csv.zip](https://github.com/woocommerce/woocommerce/files/2634470/test_CSV.-.Sheet1.csv.zip)
2. Go to imported product and examine imported attribute. For the attached test CSV, examine "Review". 
3. Observe free editing of post meta field (Select All, Select None, Add New (attribute) buttons missing completely). Edit any value. Save attributes, update product. 
4. Find apostrophes in the front end, backslashes have been added to them. 
5. Add same attribute via WooCommerce product tab to see intact selection fields and correct attribute value handling. 

**Screencast**
http://somup.com/cFXvbNn6IN

**Expected behavior**
To not be able to freely edit attribute values as text so that no false escape backslashes get produced.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

WooCommerce version:		3.5.2
WordPress version:		4.9.8

**Comment by rrennick** [comment]
The `Attribute ## Global` is a flag indicating whether it is an attribute under the Attributes menu or just one specific to the product.

**Comment by chcdigital** [comment]
Thanks for setting this up @conschneider!

@rrennick, the product attributes are determined at the product level i.e. Product > Product Data > Attributes. I am not sure as to why the Attribute ## Global would cause woocommerce to add escape backslashes to be added to special characters such as apostrophes. 

Any ideas are very welcome.

**Comment by rrennick** [comment]
> the product attributes are determined at the product leve

I was referring to the column in your CSV spreadsheet. Your sheet has the attributes all set to be local.
