### ISSUE TITLE
Order duplication: $order->calculate_totals()

### ISSUE THREAD

**Issue by gordonup** [woocommerce/woocommerce#22092]
Order duplicated with success. Now, I'd like to change its total by adding a discount. I have seen there is a whole host of methods including hooks on order get_price or cart before/during calculations but the following two seem to work ok:
```
$item_id = wc_add_order_item($order_id, 
array( 'order_item_name' => "The discount",  'order_item_type' => 'fee' ) );
wc_add_order_item_meta( $item_id, '_line_total', wc_format_decimal(5) );
```
or

`update_post_meta($order_id, '_line_total', 5);`

with "_line_total" being substituted for "_cart_discount", "_order_discount", "_sale_price" and maybe even "fee" or similar.
Anyway, I finally add the discount line for the duplicated order but $order->calculate_totals() doesn't want to include its value to calculate the desired discounted total.

In the end, I had to change the total "manually" by

`update_post_meta( $order_id, '_order_total',  $discounted_total ); 
`

which is fine but I think either I am missing something in the order duplication (product price correct yet) or there is something else behind total not being recalculated ($order->save() applied).

**Comment by rodrigoprimo** [comment]
Closing as this is not a support forum, if you require support then please use the WordDress.org forums (https://wordpress.org/support/plugin/woocommerce) or if you are a paying WooCommerce.com customer you can contact support http://woocommerce.com/contact-us for assistance.
