### ISSUE TITLE
Single product image zooming

### ISSUE THREAD

**Issue by reardestani** [woocommerce/woocommerce#22091]
**Describe the bug**
Sometimes, product single zooming is not working on first hover. It works as expected on second hover. Check the video, for 3rd and 5th images, you can see the problem.

**Screenshots**
Custom theme: http://take.ms/CcChk
Default WP theme: http://take.ms/oTd4Z

**Expected behavior**
It should work for all images correctly on first hover.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
Can you provide URLs where the example images you used can be downloaded?

**Comment by willgorham** [comment]
Might be related to this #21959

**Comment by reardestani** [comment]
@rrennick Unfortunately no. I think any high quality image will do the job.
@willgorham Thanks, it seems related.

**Comment by mikejolley** [comment]
Dupe of https://github.com/woocommerce/woocommerce/issues/21959
