### ISSUE TITLE
Doing i18n wrong in an include

### ISSUE THREAD

**Issue by tobifjellner** [woocommerce/woocommerce#22098]
**Describe the bug**
Hi,

I just tried to do a bit of translation for WooCommerce… and got stuck.

The place I stumbled upon is in /woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_WPCLI_QueueRunner.php
Around line 30:
```
public function __construct( ActionScheduler_Store $store = null, ActionScheduler_FatalErrorMonitor $monitor = null, ActionScheduler_QueueCleaner $cleaner = null ) {
	                if ( ! ( defined( 'WP_CLI' ) && WP_CLI ) ) {
	                        throw new Exception( __( 'The ' . __CLASS__ . ' class can only be run within WP CLI.', 'action-scheduler' ) );
	                }
```

To en English eye this may look normal. But this is impossible to translate into most languages.
You raise two strings for translation here:
“The ” Which in itself, without context means nothing, even when you add a space after it.

And: “class can only be run within WP CLI.” But without any indication that a Class name will be injected before it.

Obviously, one needs to tie this all together into one phrase that means something. And the right way to do it is even visible in the same very file. Just scroll down to line 137-138, for instance:
```
               /* translators: %s refers to the action ID */
	                WP_CLI::log( sprintf( __( 'Started processing action %s', 'action-scheduler' ), $action_id ) );
```
This is so much better: a comment to the translator so they’ll know what’s being inserted. And then the whole phrase, so that the German can put their verb towards the end and the Russians can use the right forms of all words.

I know this is imported code. But I guess you may know better than me where a PR is needed, etc.

**Comment by rrennick** [comment]
I've copied this over to the Action Scheduler repo. This issue can be closed.

**Comment by rodrigoprimo** [comment]
Closing. Thanks, @rrennick.
