### ISSUE TITLE
Batch Update API taking too much time

### ISSUE THREAD

**Issue by SwapnilNakhate** [woocommerce/woocommerce#22106]
Hi,

I am trying to batch update and create woocommerce product by using the woocommerce API in NodeJs : products/batch. When i trying to create 10 products by using WooCommerce API batch update function, it is taking too much time like 4-5 minutes. But when I am trying to update same quantity of products using same batch API, it is taking 5-6 seconds. Why it is taking so much time. I need to create more than 30000 products using API. I am going to create products in a batch of 100 in each batch call. But with this performance, It will take too much time.
Can you help me on this How can I improve performance ? Why is it taking too much time to create compared to update product.

Here's is my configuration :
<details>
WooCommerce Version : Version 3.2.4
Wordpress Version : Version 4.9.1
WP memory limit:  512MB
PHP version: 7.1.8
PHP post max size: 40MB
PHP time limit: 120
PHP max input vars: 1000

NPM Package NodeJS : "woocommerce-api" = 1.4.2
API Version : wc/v2
</details>

Thanks

**Comment by rrennick** [comment]
Have you tried to test this with the latest version of WooCommerce?

**Comment by SwapnilNakhate** [comment]
Hi,
Thanks for your quick reply. No, I haven't tried by upgrading WooCommerce. I will try and let you know.

**Comment by rodrigoprimo** [comment]
Besides what @rrennick, could you please check if the problem you are having is related to issue #21538? If so, we are working on a solution to this problem which should land in WC 3.6 (see #21282). Meanwhile, there is a workaround described here https://github.com/woocommerce/woocommerce/issues/21100#issuecomment-414666449.

**Comment by SwapnilNakhate** [comment]
Hi @rrennick , I have tried upgrading to woocommerce as well as Wordpress. Now performance is improved but just a little bit. I was expecting more.

Before WooCommerce Update :
10 products - 2.1557 min - 129343 ms
20 products - 4.5776 min - 274676 ms

After WooCommerce Update :
10 products - 1.84 min - 110983 ms
20 products - 4.42 min - 265515 ms

Can you help me what should I do to improve performance.

**Comment by rrennick** [comment]
> could you please check if the problem you are having is related to issue #21538?

Did you have a look at the related issue?

**Comment by rodrigoprimo** [comment]
Closing due to lack of feedback. Please leave a comment if you are still experiencing the problem and you have confirmed that it is not related to #21538 and I will reopen it.
