### ISSUE TITLE
woocommerce_package_rates not triggered everytime

### ISSUE THREAD

**Issue by vasikgreif** [woocommerce/woocommerce#22100]
I have a custom function, that gets the shipping prices from Fedex API. This works fine most of the time, but there's a problem in one specific situation:

- I create an order as a new customer, choose to create an account
- in the same window I add new product to the cart and go to checkout, the `woocommerce_package_rates` is not called at all

I think this is because of the shipping calculation caching in the `calculate_shipping_for_package` function, specifically this part of the code:

```php
			$package_hash = 'wc_ship_' . md5( wp_json_encode( $package_to_hash ) . WC_Cache_Helper::get_transient_version( 'shipping' ) );
			$session_key  = 'shipping_for_package_' . $package_key;
			$stored_rates = WC()->session->get( $session_key );

			if ( ! is_array( $stored_rates ) || $package_hash !== $stored_rates['package_hash'] || 'yes' === get_option( 'woocommerce_shipping_debug_mode', 'no' ) ) {

```

Is there a way to force the shipping recalculation every time? I tried to do on `template_redirect`

```php
	function delete_shipping_cache() {
		foreach ( WC()->session->get_session_data() as $key => $item ) {
			if (strpos($key, 'shipping_for_package_') !== false) {
			    WC()->session->__unset( $key );
			}
		}
    }

```

That did not help though.

**Comment by rrennick** [comment]
If you enable debug logging in WC, does that cause the rate filter to be called every time?

**Comment by vasikgreif** [comment]
Hello,
yes, enabling the shipping Debug mode fixed the issue and the shipping was calculated correctly. This is obviously not a fix for live site though.

**Comment by rrennick** [comment]
Thanks, I wanted to check that because enabling debug mode disables the caching (& confirms your thoughts).

**Comment by progcode** [comment]
I have same issue too. Unfortunately I unable to trigger update shipping rates on checkout page via ajax or without ajax. With debug mode works well, but this is not production ready.

Woocommerce 3.4.3 / WP. 4.9.7

`### WordPress Environment ###

Home URL: https://af2.delocal.hu
Site URL: https://af2.delocal.hu
WC Version: 3.4.3

WP Version: ❌ 4.9.7 - A WordPress újabb verziója elérhető (5.0)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: hu_HU
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.38-2+0~20181015120829.6+stretch~1.gbp567807 - Javasoljuk a PHP 7.2 vagy afeletti verzió használatát a jobb teljesítmény és biztonság érdekében. Hogyan frissíthetjük a PHP verziót
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.37-MariaDB-0+deb9u1
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.3
WC Database Prefix: af_
Teljes adatbázis mérete: 127.27MB
Adatbázis adatok mérete: 71.23MB
Adatbázis index mérete: 56.04MB
af_woocommerce_sessions: Adat: 0.09MB + Index: 0.02MB
af_woocommerce_api_keys: Adat: 0.02MB + Index: 0.03MB
af_woocommerce_attribute_taxonomies: Adat: 0.02MB + Index: 0.02MB
af_woocommerce_downloadable_product_permissions: Adat: 0.02MB + Index: 0.05MB
af_woocommerce_order_items: Adat: 1.52MB + Index: 0.44MB
af_woocommerce_order_itemmeta: Adat: 9.52MB + Index: 10.03MB
af_woocommerce_tax_rates: Adat: 0.02MB + Index: 0.06MB
af_woocommerce_tax_rate_locations: Adat: 0.02MB + Index: 0.05MB
af_woocommerce_shipping_zones: Adat: 0.02MB + Index: 0.00MB
af_woocommerce_shipping_zone_locations: Adat: 0.02MB + Index: 0.03MB
af_woocommerce_shipping_zone_methods: Adat: 0.02MB + Index: 0.00MB
af_woocommerce_payment_tokens: Adat: 0.02MB + Index: 0.02MB
af_woocommerce_payment_tokenmeta: Adat: 0.02MB + Index: 0.03MB
af_woocommerce_log: Adat: 0.02MB + Index: 0.02MB
af_commentmeta: Adat: 0.06MB + Index: 0.03MB
af_comments: Adat: 2.52MB + Index: 1.48MB
af_ewwwio_images: Adat: 4.52MB + Index: 4.84MB
af_itsec_distributed_storage: Adat: 0.02MB + Index: 0.02MB
af_itsec_lockouts: Adat: 0.02MB + Index: 0.08MB
af_itsec_logs: Adat: 0.02MB + Index: 0.09MB
af_itsec_temp: Adat: 0.02MB + Index: 0.06MB
af_iwp_backup_status: Adat: 0.06MB + Index: 0.00MB
af_iwp_file_list: Adat: 0.02MB + Index: 0.02MB
af_links: Adat: 0.02MB + Index: 0.02MB
af_newsletter_subscriptions: Adat: 0.20MB + Index: 0.00MB
af_options: Adat: 1.36MB + Index: 0.09MB
af_postmeta: Adat: 21.56MB + Index: 21.06MB
af_posts: Adat: 11.52MB + Index: 3.67MB
af_qp_hammering_log: Adat: 1.52MB + Index: 0.00MB
af_qp_tasks: Adat: 0.17MB + Index: 0.02MB
af_relevanssi: Adat: 0.52MB + Index: 0.81MB
af_relevanssi_log: Adat: 0.02MB + Index: 0.02MB
af_relevanssi_stopwords: Adat: 0.02MB + Index: 0.00MB
af_termmeta: Adat: 0.06MB + Index: 0.06MB
af_terms: Adat: 0.06MB + Index: 0.03MB
af_term_relationships: Adat: 0.27MB + Index: 0.16MB
af_term_taxonomy: Adat: 0.09MB + Index: 0.03MB
af_usermeta: Adat: 8.52MB + Index: 11.03MB
af_users: Adat: 0.45MB + Index: 0.42MB
af_vtprd_purchase_log: Adat: 0.02MB + Index: 0.02MB
af_vtprd_purchase_log_product: Adat: 0.02MB + Index: 0.02MB
af_vtprd_purchase_log_product_rule: Adat: 0.02MB + Index: 0.02MB
af_wc_download_log: Adat: 0.02MB + Index: 0.03MB
af_wc_webhooks: Adat: 0.02MB + Index: 0.02MB
af_wfBadLeechers: Adat: 0.02MB + Index: 0.00MB
af_wfBlockedCommentLog: Adat: 0.02MB + Index: 0.00MB
af_wfBlockedIPLog: Adat: 0.02MB + Index: 0.00MB
af_wfBlocks: Adat: 0.02MB + Index: 0.02MB
af_wfBlocks7: Adat: 0.02MB + Index: 0.05MB
af_wfBlocksAdv: Adat: 0.02MB + Index: 0.00MB
af_wfConfig: Adat: 0.44MB + Index: 0.00MB
af_wfCrawlers: Adat: 0.02MB + Index: 0.00MB
af_wfFileChanges: Adat: 0.02MB + Index: 0.00MB
af_wfFileMods: Adat: 1.52MB + Index: 0.00MB
af_wfHits: Adat: 1.52MB + Index: 0.52MB
af_wfHoover: Adat: 0.02MB + Index: 0.02MB
af_wfIssues: Adat: 0.06MB + Index: 0.06MB
af_wfKnownFileList: Adat: 1.52MB + Index: 0.00MB
af_wfLeechers: Adat: 0.20MB + Index: 0.00MB
af_wfLiveTrafficHuman: Adat: 0.02MB + Index: 0.02MB
af_wfLockedOut: Adat: 0.02MB + Index: 0.00MB
af_wfLocs: Adat: 0.02MB + Index: 0.00MB
af_wfLogins: Adat: 0.19MB + Index: 0.06MB
af_wfNet404s: Adat: 0.02MB + Index: 0.02MB
af_wfNotifications: Adat: 0.02MB + Index: 0.00MB
af_wfPendingIssues: Adat: 0.02MB + Index: 0.06MB
af_wfReverseCache: Adat: 0.02MB + Index: 0.00MB
af_wfScanners: Adat: 0.06MB + Index: 0.00MB
af_wfSNIPCache: Adat: 0.02MB + Index: 0.05MB
af_wfStatus: Adat: 0.13MB + Index: 0.09MB
af_wfThrottleLog: Adat: 0.02MB + Index: 0.02MB
af_wfVulnScanners: Adat: 0.02MB + Index: 0.00MB
af_woocommerce_pickup_locations_geodata: Adat: 0.02MB + Index: 0.05MB
af_woocommerce_termmeta: Adat: 0.02MB + Index: 0.03MB
af_yoast_seo_links: Adat: 0.02MB + Index: 0.02MB
af_yoast_seo_meta: Adat: 0.08MB + Index: 0.00MB

### Post Type Counts ###

adatk_nyilatkozat: 3
aszf: 1
attachment: 2109
banner: 1
esemeny: 113
galeria: 18
jelentkezes: 919
kezeles: 23
nav_menu_item: 282
page: 76
popup: 6
post: 40
product: 332
product_variation: 4
revision: 1436
shop_coupon: 987
shop_order: 3666
shop_order_refund: 1
szalon: 88
vtprd-rule: 1
wafs: 2
wc_order_email: 2
wc_order_status: 10
wc_pickup_location: 1
wpcf7_contact_form: 1
yith-wccos-ostatus: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌A hiba üzenetek nem jelenhetnek meg a látogatók számára.

### Active Plugins (44) ###

WP AFC Coupon Restrict: írta Kovacs Daniel / Delocal  – 0.1.1
iThemes Security: írta iThemes – 7.0.3
Categories Images: írta Muhammad Said El Zahlan – 2.5.4
CC Cookie Consent: írta WebPositive  – 1.6.0
Contact Form 7: írta Takayuki Miyoshi – 5.0.2
WP Google MapTracking: írta Kovacs Daniel Akos / Delocal  – 0.1.0
Simple product search: írta Kovacs Daniel / Delocal  – 0.1.0
Duplicate Post: írta Enrico Battocchi – 3.2.2
E-mail template editor: írta Auretto Works – 1.0
EWWW Image Optimizer: írta Shane Bishop – 4.2.2
Galéria metabox: írta Auretto Works – 2.14
Multiple Post Thumbnails: írta Chris Scott – 1.7
Nav Menu Roles: írta Kathy Darling – 1.9.2
PixelYourSite: írta PixelYourSite – 5.3.1 – Nincsen tesztelve a Woocommerce aktív verziójával
qTranslate slug: írta Carlos Sanz Garcia
Pedro Carvalho – 1.1.18

qTranslate-X: írta qTranslate Team – 3.4.6.8
Quick Page/Post Redirect Plugin: írta anadnet – 5.1.8
Regenerate Thumbnails: írta Alex Mills (Viper007Bond) – 3.0.2
Relevanssi: írta Mikko Saari – 4.0.11
Simple Custom Post Order: írta Colorlib – 2.3.2
String Locator: írta Clorith – 2.3.0
Category Order and Taxonomy Terms Order: írta Nsp-Code – 1.5.4
Woo OnePage Checkout: írta Kovacs Daniel Akos / Delocal  – 0.1.0
Advanced Order Export For WooCommerce: írta AlgolPlus – 2.0.0
WooCommerce Advanced Free Shipping: írta Jeroen Sormani – 1.1.3 – Nincsen tesztelve a Woocommerce aktív verziójával
WooCommerce Extended Coupon Features: írta Soft79 – 2.6.2 – Nincsen tesztelve a Woocommerce aktív verziójával
WooCommerce Checkout Field Editor: írta WooThemes – 1.4.10 – 1.5.15 elérhető – Nincsen tesztelve a Woocommerce aktív verziójával
WooCommerce Dynamic Pricing: írta Lucas Stark – 3.1.6 – 3.1.10 elérhető – Nincsen tesztelve a Woocommerce aktív verziójával
Woocommerce Futár: írta Kovacs Daniel / Delocal  – 1.0.0 – Nincsen tesztelve a Woocommerce aktív verziójával
WooCommerce First Data Latvia Gateway: írta First Data Latvia – 1.0.0 – Nincsen tesztelve a Woocommerce aktív verziójával
GLS csomagpont: írta Terebesi Dénes – 4.3.3
WooCommerce Group Coupons: írta itthinx – 1.8.1 – 1.9.0 elérhető
WooCommerce Order Status Manager: írta SkyVerge – 1.9.2 – 1.9.3 elérhető
WooCommerce & qTranslate-X: írta qTranslate Team – 1.3 – Nincsen tesztelve a Woocommerce aktív verziójával
WooCommerce Role Based Methods: írta WPBackOffice – 2.0.2 – 2.3.10 elérhető – Nincsen tesztelve a Woocommerce aktív verziójával
WooCommerce Local Pickup Plus: írta SkyVerge – 2.3.14 – 2.3.16 elérhető
WooCommerce: írta Automattic – 3.4.3
WordPress Importer: írta wordpressdotorg – 0.6.4
WP AFC Custom: írta Kovacs Daniel / Delocal  – 0.1.2
WP Crontrol: írta John Blackbourn & contributors – 1.6.2
Wp Export Categories & Taxonomies: írta timersys – 1.0.3
WP Mobble: írta Kovacs Daniel Akos (kovacsdanielakos@progweb.hu) – 1.0.0
WP-SCSS: írta Connect Think – 1.2.4
WP Media Protector: írta Auretto Works – 1.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: HUF (Ft)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: simple (simple)
grouped (grouped)
variable (variable)
external (external)

**Comment by progcode** [comment]
Hey @rrennick can you test this issue?

**Comment by rrennick** [comment]
I'll have a look at it sometime in the next few days.

**Comment by rrennick** [comment]
> in the same window I add new product to the cart and go to checkout, the `woocommerce_package_rates` is not called at all

In my testing it's called each time a product is added or removed from the cart. From that point on the cached value is used.

If you want to force this to be called on checkout I'd suggest using one of the checkout hooks: https://docs.woocommerce.com/wc-apidocs/hook-docs.html .

**Comment by rrennick** [comment]
> `if (true || ...`

That's always going to make the entire condition true. 

> In the original code the cache not invalidating when payment method changing.

Can you describe why the shipping rates cache should be invalidated when the payment method is changing?

**Comment by progcode** [comment]
Yes. Because we use multiple shipping rates based on payment method. For example, if user first select the COD payment we well add an fee to shipping rate, but if he switch back we remove this fee. And not, we wouldn't want use the fee api for this.

**Comment by rrennick** [comment]
Have you tried https://wordpress.org/plugins/flexible-shipping/ ?

**Comment by vasikgreif** [comment]
Following this, and I'm not sure if there's some solution for this. I need to be able to disable the cache and recalculate shipping everytime.  I don't care about some minor performance downside. Any way to do that?

**Comment by rrennick** [comment]
> I don't care about some minor performance downside. Any way to do that?

Caching is disabled when the shipping debug setting is enabled.

**Comment by vasikgreif** [comment]
Yes, but that also displays the debug notices on checkout...

**Comment by mikejolley** [comment]
Jumping in, you are wanting to disable the cache. Talking about being production ready, thats probably not a good idea when you're dealing with carier rates because it will query the rates on every request. 

This is not a bug. Caching is there for a reason.

If you add a custom variable to the `woocommerce_cart_shipping_packages` array, let's say the selected payment method, that will change the key used for the cache. So you could potentially cache still, just less frequently. 

https://github.com/woocommerce/woocommerce/blob/981ddcfe341697d17c887e672c27803207811823/includes/class-wc-cart.php#L1308

Thanks

**Comment by progcode** [comment]
LOL. This a bug, but okay, closed this. Ugly woocommerce.

**Comment by mikejolley** [comment]
Cache is a bug, ok. 👏

**Comment by vasikgreif** [comment]
@mikejolley Well, we slipped away from the original problem - `woocommerce_package_rates ` not being triggered everytime, making it impossible to properly calculate the shipping. I'm not sure I'm following your comment about `woocommerce_cart_shipping_packages ` array, can you please give me and others an example?

Anyway, I still think the filter `woocommerce_cart_shipping_packages ` really *should* be triggered everytime.

**Comment by mikejolley** [comment]
As I said, if `woocommerce_package_rates` was triggered every time, it would mean no cache can exist. Think about sites running carrier rates like USPS, FEDEX etc. Expensive API queries which must be cached.

`woocommerce_cart_shipping_packages` determines what is being shipped. The items inside, the destination. This is what the caching generates a key from. If `woocommerce_cart_shipping_packages` does not change, shipping does not need to be recalculated. If something inside `woocommerce_cart_shipping_packages` changes, the cache key changes, and cache is invalidiated.

If you're doing something special, such as changing shipping prices with fees based on some critieria, you can insert this into the `woocommerce_cart_shipping_packages` array to force the caching to be unique.

Example, say I'm adding a $5 surcharge to shipping if 'paypal' is used. In that case, to prevent caching the $5 vs regular shipping cost, I could insert a new array item into `woocommerce_cart_shipping_packages` .

```
'custom_payment_method' => 'paypal'
```

There will be a different cache used for each different `custom_payment_method` in that example.

Or to be really hacky like @progcode (`true ||` ha) you could insert something random into `woocommerce_cart_shipping_packages` to invalidate the cache at all times, but I don't recommend that as it won't scale, especially when using APIs for shipping rates.

**Comment by vasikgreif** [comment]
Thanks for the workaround, but it does not seem to work. I tried to add random array to the packages:

```php
add_filter( 'woocommerce_cart_shipping_packages', array( $this, 'disable_shipping_rates_cache' ), 10, 2 );
function disable_shipping_rates_cache($packages) {
        $packages[] = [
                rand() => rand()
        ];

        return $packages;
    }
```

I end with an error message `No shipping method has been selected. Please double check your address, or contact us if you need any help.`

**Comment by vasikgreif** [comment]
@mikejolley Hello, any chance to get a guide on to how disable the payment cache? As noted above, adding a random value to the shipping array does not work.

**Comment by mikejolley** [comment]
The code you shared above did not modify an existing package, it added a new package with no data but `rand` and the key for that is invalid.

Modify the existing package in the array. Append the random value.

**Comment by alexminza** [comment]
There is some ambiguity to the way the `woocommerce_package_rates` filter is called when modifying product quantity (and thus the cart contents and order) in the two different available ways:
* When adding a product to cart and the modifying product quantity in the cart (and clicking the Update Cart button) the `woocommerce_package_rates` filter is called each time
* When adding more items of the same product by clicking the Add to cart button on the product details page several times - the `woocommerce_package_rates` is not called each time

This makes impossible to properly use the `woocommerce_package_rates` filter to calculate rates based on items quantity in cart/order for example.

**Comment by mikejolley** [comment]
@alexminza The hash is based on item contents, so if the qty changes the hash must also change? qty is part of the hashed cart.

**Comment by CrazyFretz** [comment]
Apologies for reviving an old thread, but I hope this helps someone as I just figured out the issuse of 'no shipping method'. When adjusting the rates using `woocommerce_package_rates`, if you create a new array and return it, it will produce the error when submitting the cart for payment of `No shipping method has been selected. Please double check your address, or contact us if you need any help.`. However, if you instead modify the $rates array instead of return a new array, it will no longer give that error of no shipping method when you try to pay for the cart.

My situation was that I only wanted one shipping method shown due to a custom checkout I had made. So either delivery using table rates, or just pick up. So for me I ran a loop in the function for `woocommerce_package_rates` like so:

`
foreach ( $rates as $rate_id => $rate ) {
  if(WC()->session->get('delivery_prefs') == 'pickup'){
    if(strpos($rate_id, 'betrs_shipping') !== false){ 
      unset($rates[$rate_id]);
    }
  }elseif(WC()->session->get('delivery_prefs') == 'delivery'){
    if(strpos($rate_id, 'local_pickup') !== false){
      unset($rates[$rate_id]);
    }
  }
}
return $rates;
`

Hope this helps someone, because in googling this issue I found 2 results and this thread was one of them, but it didn't explain how to get around the 'no shipping method selected' problem.

**Comment by rockpradeep143** [comment]
@mikejolley 
Thanks for the solution
I have used the ups shipping plugin and client wanted to convert the rates from CADs to usd, I searched and found your comment to execute the woocommerce_package_rates hook every time and as you said  I modified the key to assign the random value and now hook working everytime.
Here is the code I used to update the existing package. 
add_filter( 'woocommerce_cart_shipping_packages', 'disable_shipping_rates_cache' , 10, 2 );
function disable_shipping_rates_cache($packages) {
   $packages[0]['contents'][0]['key']=rand(); 
   return $packages; 
 }  
can you please let me know that updating key doesn't impact to other functionality.

**Comment by fippy** [comment]
For me, woocommerce_package_rates does not fire on cart update, or change of address using shipping calculator. Even though (if I understand @mikejolley correctly) woocommerce_cart_shipping_packages has changed and so the hash would have changed and the cache would be invalidated.

In fact even with debugging mode on which should bypass the shipping rate cache, woocommerce_package_rates still does not fire on cart update or address change.

**Comment by wss-chadical** [comment]
@vasikgreif I'm totally on board with your position on this.
It's broken. Cache carrier stuff all you want - but there are multiple ways to break shipping and payments calc's based on this behavior. 

We have dependencies between Shipping and Payment options - they need to talk to each other.

@mikejolley Have to say it - I strongly disagree with your position. We lost money on this deal for sure. It wasn't until more testing and obscure clicking, going back and forth that we were able to determine that yes, the woocommerce_package_rates is not called when it should be.

Also, pretty sure UPS and fedex can handle it. I'd rather beat up their api's then lose money, create customer experience issues, and create more work for our service teams. (All of the above has happened).

At a minimum...
There could be switch to disable cache - other than turning on Debug.
or
(For us)... Pass in the available shipping rates into woocommerce_available_payment_gateways? 

Probably will patch core on this one.

**Comment by bmcclure** [comment]
There are many possible, completely valid, reasons why this should be called when _any_ checkout information changes, but cached when it doesn't.

For example: Adding a custom checkout field for whether to pack a product in ice. It's possible only certain shipping methods are compatible with this option, but since `woocommerce_package_rates` is only called when the cart or shipping address changes, changing this custom field value does not cause the `woocommerce_package_rates` filter to fire so there seems to be no way to remove the invalid shipping methods.

Using the hacky solution of modifying the package is not ideal, and signifies a deficiency in WooCommerce. When the checkout data changes, I think that `woocommerce_package_rates` should be called again. Or at a minimum, there should be a way to indicate which checkout fields are related to shipping calculation so that those can automatically invalidate the cache when changed.

**Comment by gillesgoetsch** [comment]
I do experience similar issues that the 'woocommerce_package_rates' is not being triggered when the checkbox 'ship_to_different_address' field is checked. It does happen when I i.e. change ZIP-Code, but not on the checkbox.

Here is a workaround function from @vasikgreif with the feedback integrated.

I do isolate disabling the cache as much as possible to lower the impact on efficiency.

```


/**
 * FIX
 * There is an issue (unwanted behaviour) where 'woocommerce_package_rates' is not being triggered when the ship_to_different_address gets checked
 * When the field is checked the available shipping methods should change based on the logic in the 'woocommerce_package_rates' hook
 * https://github.com/woocommerce/woocommerce/issues/22100
 */

// only do this when its the actual ajax 'update_order_review' call and the shipping box was ticked
if(isset($_GET['wc-ajax']) && $_GET['wc-ajax'] == 'update_order_review') {

  $post_data = [];
  parse_str( $_POST['post_data'], $post_data );

  // if address is the same
  if($post_data['ship_to_different_address']) {
    add_filter( 'woocommerce_cart_shipping_packages', 'disable_shipping_rates_cache', 10, 2 );
  }

}

// add random value to existing array to disable cache
function disable_shipping_rates_cache($packages) {
    $packages[0][rand()] = rand();
    return $packages;
}

```

**Comment by gillesgoetsch** [comment]
Now I tackled the issue from another direction and now in the code clearing transient cache like this:

```
add_action( 'after_setup_theme', function() {
    WC_Cache_Helper::get_transient_version( 'shipping', true );
} );
```

I could add an if statement to isolate checkout and specific POST values. But for demonstration go with the example.

Now I have the issue that on the checkout and in the POST Data the shipping method is correct, but on the thank you page and therefore in the order it will not take the selected method but instead use the default first method shown without the extra logic.

I also deactivated all the shipping related plugins and the issue persists.
I double checked the actual POST Request which contains the correct shipping method. It seems like when I'm disabling the cache on the checkout it won't have anything to refeer to in the actual order and therefore just defaults to the first availably shown shipping method otherwise. 

Any idea how to get this working?

**Comment by onsterionkubey** [comment]
Same problem here woocommerce_package_rates is not triggering properly 👍 

2 years are passed, any solution?


Regards,

**Comment by akshuvo** [comment]
```
/**
 * Clear Shipping Rates Cache
 */
add_filter('woocommerce_checkout_update_order_review', 'clear_wc_shipping_rates_cache');
function clear_wc_shipping_rates_cache(){
    $packages = WC()->cart->get_shipping_packages();

    foreach ($packages as $key => $value) {
        $shipping_session = "shipping_for_package_$key";

        unset(WC()->session->$shipping_session);
    }
}
```

This code saved me. Credit goes to https://gist.github.com/chuckmo/9c2a57f64cf60ee0d9d3#gistcomment-1805437

**Comment by ewijdemans** [comment]
A workaround could also be to disable this specific cache by doing this:
`add_filter('transient_shipping-transient-version', function($value, $name) {
            return false;
        }, 10, 2);`

**Comment by Entretoize** [comment]
> A workaround could also be to disable this specific cache by doing this:
> `add_filter('transient_shipping-transient-version', function($value, $name) { return false; }, 10, 2);`

That works !

**Comment by matanbakshi** [comment]
> For me, woocommerce_package_rates does not fire on cart update, or change of address using shipping calculator. Even though (if I understand @mikejolley correctly) woocommerce_cart_shipping_packages has changed and so the hash would have changed and the cache would be invalidated.
> 
> In fact even with debugging mode on which should bypass the shipping rate cache, woocommerce_package_rates still does not fire on cart update or address change.
> 
> In fact, for me it seems to work the opposite as outlined by @alexminza in that:
> 
> * When adding a product to cart and the modifying product quantity in the cart (and clicking the Update Cart button) the woocommerce_package_rates filter is **NOT** called each time
> * When adding more items of the same product by clicking the Add to cart button on the product details page several times - the woocommerce_package_rates is called each time

I have this exact same issue, did manage to workaround it?

**Comment by abhishek-pokhriyal** [comment]
I also fell into this yesterday. I dug in to see how WooCommerce itself deals with the issue and found that it invalidates the "shipping" transients:

https://github.com/woocommerce/woocommerce/blob/02981cfbc9b6c36d7c622c3bbebdb8634fb36e2e/includes/class-wc-ajax.php#L2965

So, I believe a similar fix can be used by Woo extensions.

1. Identify the events after which the package rates need to be recalculated
2. On each of these events, invalidate the "shipping" transients (using the code I linked above)

**Comment by Semaho** [comment]
> https://github.com/woocommerce/woocommerce/blob/02981cfbc9b6c36d7c622c3bbebdb8634fb36e2e/includes/class-wc-ajax.php#L2965

In my case, I'm calculating fees on `woocommerce_cart_calculate_fees` hook. Using the quoted line at the beginning of my function did the trick ! Thank you @abhishek-pokhriyal

**Comment by dokker** [comment]
> A workaround could also be to disable this specific cache by doing this:
> `add_filter('transient_shipping-transient-version', function($value, $name) { return false; }, 10, 2);`

I can confirm that this is a working solution. Thanks.

**Comment by ObliviousHarmony** [comment]
I'd like to dive a bit deeper into [Mike's earlier comment with a solution](https://github.com/woocommerce/woocommerce/issues/22100#issuecomment-455128064). As noted, whether or not the cache is used depends on the packages array returned from `WC()->cart->get_shipping_packages()`. It uses information about each package to be shipped to track when it may need recalculated. In order to invalidate the cache, you need to make a change one (or all) of the packages in the array.

This is a snippet that adds a random number to every package. This will result in the cache being invalidated during every request:

```php
<?php

function woocommerce_shipping_rate_cache_invalidation( $packages ) {
	foreach ( $packages as &$package ) {
		$package['rate_cache'] = wp_rand();
	}

	return $packages;
}
add_filter( 'woocommerce_cart_shipping_packages', 'woocommerce_shipping_rate_cache_invalidation', 100 );
```

My recommendation would be to use this approach, but replace the `wp_rand()` with something useful. For instance, maybe there's a parameter that, when changed, you want to trigger an update. You could store that value in the packages, and when it changes, the rates will be pulled again.

**Comment by infokiftikhar** [comment]
**Hides specific shipping rate when order total is more than $1.**

	function new_method( $rates ) {

		$order_total = WC()->cart->get_subtotal();
		if ($order_total > 1) {
			foreach ($rates as $rate_id => $rate) {
				if ('free_shipping' === $rate->get_method_id()) {
					unset($rates[$rate_id]);
				}
			}
		}

		return $rates;
	}
	add_filter( 'woocommerce_package_rates', 'new_method', 100 );

	add_action( 'after_setup_theme', function() {
	    WC_Cache_Helper::get_transient_version( 'shipping', true );
	} );

**Comment by myalban** [comment]
I've tested all of solutions but none of them are working on my side , the filter "woocommerce_package_rates "wan't be triggered !
I don't understand why there is no way to directly update the shipping price as  WC()->cart->set_shipping(...)

**Comment by coycash** [comment]
Here's my problem

1.  Add items to cart
2. Go to checkout and my 'woocommerce_package_rates' hook removes certain shipping options 
3. Come back the next day
4. Cart is still full but 'woocommerce_package_rates' isn't run when I visit the checkout page and all the options are visible.

Anyone else experience this?  Is there a shipping cache timeout vs a cart timeout?
