### ISSUE TITLE
Hold stock causing isses

### ISSUE THREAD

**Issue by envisionops** [woocommerce/woocommerce#22105]
Hi there,
With latest woocommerce version
We're often getting this message on cart page.

Sorry, we do not have enough "XXX product" in stock to fulfil your order (-2 available). We apologise for any inconvenience caused.

We checked hold stock option is blank.

Not sure if this is a bug, but can you check. It's busy store with 150-200 sessions at a time.

Many thanks,
S

**Comment by plxrisa** [comment]
I can confirm that I have also seen this message and I have checked that I didn't have manage stock enabled, but I don't have find out yet what is problem.

**Comment by plxrisa** [comment]
@rrennick As I wrote above, I can see this issue but still can't understand which is the main reason for this. So, I can't provide details to reproduce it yet.

**Comment by mikejolley** [comment]
Consolodating duplicate issue reports into https://github.com/woocommerce/woocommerce/issues/22544

Thanks
