### ISSUE TITLE
change stock on holded orders for additional or edited amount also

### ISSUE THREAD

**Issue by oblaum** [woocommerce/woocommerce#22107]
**Describe the bug**
with the latest wc 3.5.x version the stock is calculated automatically which is great, in some cases customers wanted to change the product or the quantity after the order.
at the moment by adding a product or changing the amount of the existing product order the stock is not changed proper.

there is a workaround by changing the status to cancel then set it to complete, only with theses steps the stock is handeled proper.

**To Reproduce**
1. check the stock of a product (lets name it LADYBUG) or set it to 10
2. check the stock of a product (lets name it FOREST)  or set it to 10
3. order product LADYBUG
4. order it e.g. bank transfer
5. open the holded order (e.g. /wp-admin/post.php?post=8936&action=edit)
6. click on "add item(s)" then add product FOREST
7. additionally change the product amount for LADYBUG from 1 to 2
8. change the status to complete and safe
9. check the stock of FOREST (should be 9)
10. check the stock of LADYBUG (should be 8)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: http://beta.skibaumarkt.de
Site URL: http://beta.skibaumarkt.de
WC Version: 3.5.2
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 384 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.12
PHP Post Max Size: 100 MB
PHP Time Limit: 240
PHP Max Input Vars: 5000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.7.24-2
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.2
WC Database Prefix: ski_
Total Database Size: 485.72MB
Database Data Size: 341.24MB
Database Index Size: 144.48MB
ski_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
ski_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
ski_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
ski_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
ski_woocommerce_order_items: Data: 1.52MB + Index: 1.52MB
ski_woocommerce_order_itemmeta: Data: 40.55MB + Index: 15.03MB
ski_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
ski_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
ski_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
ski_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
ski_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
ski_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
ski_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
ski_woocommerce_log: Data: 0.02MB + Index: 0.02MB
ski_commentmeta: Data: 0.06MB + Index: 0.06MB
ski_comments: Data: 4.52MB + Index: 5.92MB
ski_duplicator_pro_entities: Data: 0.02MB + Index: 0.02MB
ski_duplicator_pro_packages: Data: 0.06MB + Index: 0.02MB
ski_hook_list: Data: 0.02MB + Index: 0.00MB
ski_icl_content_status: Data: 0.02MB + Index: 0.02MB
ski_icl_core_status: Data: 0.02MB + Index: 0.02MB
ski_icl_flags: Data: 0.02MB + Index: 0.02MB
ski_icl_languages: Data: 0.02MB + Index: 0.03MB
ski_icl_languages_translations: Data: 0.20MB + Index: 0.14MB
ski_icl_locale_map: Data: 0.02MB + Index: 0.02MB
ski_icl_message_status: Data: 0.02MB + Index: 0.03MB
ski_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB
ski_icl_node: Data: 0.02MB + Index: 0.00MB
ski_icl_reminders: Data: 0.02MB + Index: 0.00MB
ski_icl_strings: Data: 7.52MB + Index: 12.58MB
ski_icl_string_packages: Data: 0.02MB + Index: 0.00MB
ski_icl_string_pages: Data: 1.52MB + Index: 1.52MB
ski_icl_string_positions: Data: 3.52MB + Index: 1.52MB
ski_icl_string_status: Data: 0.02MB + Index: 0.02MB
ski_icl_string_translations: Data: 3.52MB + Index: 1.52MB
ski_icl_string_urls: Data: 0.02MB + Index: 0.02MB
ski_icl_translate: Data: 8.52MB + Index: 0.39MB
ski_icl_translate_job: Data: 0.11MB + Index: 0.06MB
ski_icl_translations: Data: 1.52MB + Index: 1.55MB
ski_icl_translation_batches: Data: 0.05MB + Index: 0.00MB
ski_icl_translation_status: Data: 2.52MB + Index: 0.02MB
ski_itsec_distributed_storage: Data: 0.02MB + Index: 0.02MB
ski_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB
ski_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB
ski_itsec_lockouts: Data: 0.02MB + Index: 0.08MB
ski_itsec_log: Data: 3.52MB + Index: 0.61MB
ski_itsec_logs: Data: 58.58MB + Index: 2.38MB
ski_itsec_temp: Data: 0.02MB + Index: 0.06MB
ski_links: Data: 0.02MB + Index: 0.02MB
ski_nf3_actions: Data: 0.02MB + Index: 0.00MB
ski_nf3_action_meta: Data: 0.02MB + Index: 0.00MB
ski_nf3_chunks: Data: 0.02MB + Index: 0.00MB
ski_nf3_fields: Data: 0.02MB + Index: 0.00MB
ski_nf3_field_meta: Data: 0.02MB + Index: 0.00MB
ski_nf3_forms: Data: 0.02MB + Index: 0.00MB
ski_nf3_form_meta: Data: 0.02MB + Index: 0.00MB
ski_nf3_objects: Data: 0.02MB + Index: 0.00MB
ski_nf3_object_meta: Data: 0.02MB + Index: 0.00MB
ski_nf3_relationships: Data: 0.02MB + Index: 0.00MB
ski_nf3_upgrades: Data: 0.02MB + Index: 0.00MB
ski_nf_objectmeta: Data: 0.02MB + Index: 0.00MB
ski_nf_objects: Data: 0.02MB + Index: 0.00MB
ski_nf_relationships: Data: 0.02MB + Index: 0.00MB
ski_ninja_forms: Data: 0.02MB + Index: 0.00MB
ski_ninja_forms_fav_fields: Data: 0.05MB + Index: 0.00MB
ski_ninja_forms_fields: Data: 0.02MB + Index: 0.00MB
ski_options: Data: 3.17MB + Index: 0.11MB
ski_postmeta: Data: 24.55MB + Index: 24.06MB
ski_posts: Data: 2.31MB + Index: 0.83MB
ski_rac_abandoncart: Data: 0.02MB + Index: 0.00MB
ski_rac_email_logs: Data: 0.02MB + Index: 0.00MB
ski_rac_templates_email: Data: 0.02MB + Index: 0.00MB
ski_snippets: Data: 0.02MB + Index: 0.00MB
ski_taxonomymeta: Data: 0.02MB + Index: 0.03MB
ski_termmeta: Data: 0.05MB + Index: 0.03MB
ski_terms: Data: 0.11MB + Index: 0.13MB
ski_term_relationships: Data: 0.19MB + Index: 0.13MB
ski_term_taxonomy: Data: 0.11MB + Index: 0.14MB
ski_usermeta: Data: 1.03MB + Index: 0.03MB
ski_users: Data: 0.02MB + Index: 0.05MB
ski_wcpdf_credit_note_number: Data: 0.02MB + Index: 0.00MB
ski_wcpdf_invoice_number: Data: 0.05MB + Index: 0.00MB
ski_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB
ski_wcpdf_proforma_number: Data: 0.05MB + Index: 0.00MB
ski_wc_download_log: Data: 0.02MB + Index: 0.03MB
ski_wc_webhooks: Data: 0.02MB + Index: 0.02MB
ski_woocommerce_shipping_zone_shipping_methods: Data: 0.02MB + Index: 0.00MB
ski_woocommerce_termmeta: Data: 0.02MB + Index: 0.03MB
ski_yoast_seo_links: Data: 0.13MB + Index: 0.05MB
ski_yoast_seo_meta: Data: 0.06MB + Index: 0.00MB
x-bak-27092055__ski_commentmeta: Data: 0.06MB + Index: 0.06MB
x-bak-27092055__ski_comments: Data: 4.52MB + Index: 5.91MB
x-bak-27092055__ski_duplicator_pro_entities: Data: 0.02MB + Index: 0.02MB
x-bak-27092055__ski_duplicator_pro_packages: Data: 0.36MB + Index: 0.02MB
x-bak-27092055__ski_hook_list: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_icl_content_status: Data: 0.02MB + Index: 0.02MB
x-bak-27092055__ski_icl_core_status: Data: 0.02MB + Index: 0.02MB
x-bak-27092055__ski_icl_flags: Data: 0.02MB + Index: 0.02MB
x-bak-27092055__ski_icl_languages: Data: 0.02MB + Index: 0.03MB
x-bak-27092055__ski_icl_languages_translations: Data: 0.20MB + Index: 0.14MB
x-bak-27092055__ski_icl_locale_map: Data: 0.02MB + Index: 0.02MB
x-bak-27092055__ski_icl_message_status: Data: 0.02MB + Index: 0.03MB
x-bak-27092055__ski_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB
x-bak-27092055__ski_icl_node: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_icl_reminders: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_icl_strings: Data: 6.52MB + Index: 12.58MB
x-bak-27092055__ski_icl_string_packages: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_icl_string_pages: Data: 1.52MB + Index: 0.50MB
x-bak-27092055__ski_icl_string_positions: Data: 3.52MB + Index: 1.52MB
x-bak-27092055__ski_icl_string_status: Data: 0.02MB + Index: 0.02MB
x-bak-27092055__ski_icl_string_translations: Data: 3.52MB + Index: 1.52MB
x-bak-27092055__ski_icl_string_urls: Data: 0.02MB + Index: 0.02MB
x-bak-27092055__ski_icl_translate: Data: 7.52MB + Index: 0.38MB
x-bak-27092055__ski_icl_translate_job: Data: 0.09MB + Index: 0.06MB
x-bak-27092055__ski_icl_translations: Data: 1.52MB + Index: 1.55MB
x-bak-27092055__ski_icl_translation_batches: Data: 0.05MB + Index: 0.00MB
x-bak-27092055__ski_icl_translation_status: Data: 2.52MB + Index: 0.02MB
x-bak-27092055__ski_itsec_distributed_storage: Data: 0.02MB + Index: 0.02MB
x-bak-27092055__ski_itsec_lockouts: Data: 0.02MB + Index: 0.08MB
x-bak-27092055__ski_itsec_log: Data: 3.52MB + Index: 0.61MB
x-bak-27092055__ski_itsec_logs: Data: 55.58MB + Index: 2.23MB
x-bak-27092055__ski_itsec_temp: Data: 0.06MB + Index: 0.06MB
x-bak-27092055__ski_links: Data: 0.02MB + Index: 0.02MB
x-bak-27092055__ski_nf3_actions: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_nf3_action_meta: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_nf3_chunks: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_nf3_fields: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_nf3_field_meta: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_nf3_forms: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_nf3_form_meta: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_nf3_objects: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_nf3_object_meta: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_nf3_relationships: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_nf3_upgrades: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_nf_objectmeta: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_nf_objects: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_nf_relationships: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_ninja_forms: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_ninja_forms_fav_fields: Data: 0.05MB + Index: 0.00MB
x-bak-27092055__ski_ninja_forms_fields: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_options: Data: 2.52MB + Index: 0.11MB
x-bak-27092055__ski_postmeta: Data: 27.55MB + Index: 23.06MB
x-bak-27092055__ski_posts: Data: 2.52MB + Index: 0.84MB
x-bak-27092055__ski_rac_abandoncart: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_rac_email_logs: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_rac_templates_email: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_snippets: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_taxonomymeta: Data: 0.02MB + Index: 0.03MB
x-bak-27092055__ski_termmeta: Data: 0.05MB + Index: 0.03MB
x-bak-27092055__ski_terms: Data: 0.11MB + Index: 0.09MB
x-bak-27092055__ski_term_relationships: Data: 0.17MB + Index: 0.13MB
x-bak-27092055__ski_term_taxonomy: Data: 0.11MB + Index: 0.14MB
x-bak-27092055__ski_usermeta: Data: 3.52MB + Index: 4.03MB
x-bak-27092055__ski_users: Data: 0.14MB + Index: 0.14MB
x-bak-27092055__ski_wcpdf_credit_note_number: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_wcpdf_invoice_number: Data: 0.05MB + Index: 0.00MB
x-bak-27092055__ski_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_wcpdf_proforma_number: Data: 0.05MB + Index: 0.00MB
x-bak-27092055__ski_wc_download_log: Data: 0.02MB + Index: 0.03MB
x-bak-27092055__ski_wc_webhooks: Data: 0.02MB + Index: 0.02MB
x-bak-27092055__ski_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
x-bak-27092055__ski_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
x-bak-27092055__ski_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
x-bak-27092055__ski_woocommerce_log: Data: 0.02MB + Index: 0.02MB
x-bak-27092055__ski_woocommerce_order_itemmeta: Data: 39.55MB + Index: 15.03MB
x-bak-27092055__ski_woocommerce_order_items: Data: 1.52MB + Index: 1.52MB
x-bak-27092055__ski_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
x-bak-27092055__ski_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
x-bak-27092055__ski_woocommerce_sessions: Data: 0.09MB + Index: 0.02MB
x-bak-27092055__ski_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
x-bak-27092055__ski_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_woocommerce_shipping_zone_shipping_methods: Data: 0.02MB + Index: 0.00MB
x-bak-27092055__ski_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
x-bak-27092055__ski_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
x-bak-27092055__ski_woocommerce_termmeta: Data: 0.02MB + Index: 0.03MB
x-bak-27092055__ski_yoast_seo_links: Data: 0.13MB + Index: 0.08MB
x-bak-27092055__ski_yoast_seo_meta: Data: 0.06MB + Index: 0.00MB

### Post Type Counts ###

amn_exact-metrics: 1
attachment: 923
blocks: 30
extra_product_tab: 5
nav_menu_item: 26
nf_sub: 118
page: 38
post: 22
product: 434
product_variation: 166
shop_coupon: 8
shop_order: 2796
shop_order_refund: 9
vtmin-rule: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (39) ###

WPElite Plugins Updater: by WPElite Plugins – 1.0.0
WPML Multilingual CMS: by OnTheGoSystems – 4.0.7
Code Snippets: by Shea Bunge – 2.12.1
Cookie Notice: by dFactory – 1.2.45
Duplicator Pro: by Snap Creek – 3.7.9
Envato Market: by Envato – 2.0.1
Force Regenerate Thumbnails: by Pedro Elsner – 2.0.6
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 5.3.7
iThemes Security Pro: by iThemes – 5.5.3
Ninja Forms: by The WP Ninjas – 3.3.19.1
No Page Comment: by Seth Alling – 1.2
Optimus: by KeyCDN – 1.6.0
Performance Tester: by Anthony Fourneau – 0.1.3
PHPEnkoder: by Michael Greenberg – 1.14.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.0.2
Vendidero Helper: by Vendidero – 1.2.1
WooCommerce - Minimum/Maximum Quantities: by WPElitePlugins – 2.0.6 – Not tested with the active version of WooCommerce
Woocommerce Product Tab Pro: by Proword – 2.9 – Not tested with the active version of WooCommerce
WooCommerce Composite Products: by SomewhereWarm – 3.14.6
WooCommerce Email Customizer: by cxThemes – 3.22 – Not tested with the active version of WooCommerce
WooCommerce Germanized Pro: by Vendidero – 1.9.7
WooCommerce Germanized: by Vendidero – 2.2.4
WooCommerce Multilingual: by OnTheGoSystems – 4.3.7
WooCommerce Pay for Payment: by Karolína Vyskočilová – 2.0.10
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.2.4
WooCommerce PDF Invoices & Packing Slips Professional: by Ewout Fernhout – 2.2.8
WooCommerce PDF Invoices & Packing Slips Premium Templates: by Ewout Fernhout – 2.5.6 – Not tested with the active version of WooCommerce
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.12.2
WooCommerce Table Rate Shipping: by Bolder Elements – 4.1.3 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.5.2
WooSidebars: by WooCommerce – 1.4.5
WordPress Importer: by wordpressdotorg – 0.6.4
Yoast SEO Premium: by Team Yoast – 9.2.1
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.2.6

WPML Media: by OnTheGoSystems – 2.3.7
WPML String Translation: by OnTheGoSystems – 2.8.7
WPML Translation Management: by OnTheGoSystems – 2.6.7
WP Overnight Sidekick: by Jeremiah Prummer
Ewout Fernhout
Michael Kluver – 2.0.3

Yoast SEO: WooCommerce: by Team Yoast – 9.2

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #2761 - /uebersicht/
Cart: #2783 - /warenkorb/
Checkout: #2785 - /kasse/
My account: #2804 - /mein-konto/
Terms and conditions: #2793 - /agb/

### Theme ###

Name: Skibaumarkt.de
Version: 1.0
Author URL: http://www.oblaum.com
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.7.1
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php version 3.5.0 is out of date. The core version is 3.5.2
/usr/www/users/oblaum/beta_skibaumarkt.de/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/admin-cancelled-order.php
/usr/www/users/oblaum/beta_skibaumarkt.de/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/admin-failed-order.php
/usr/www/users/oblaum/beta_skibaumarkt.de/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/admin-new-order.php
/usr/www/users/oblaum/beta_skibaumarkt.de/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/customer-completed-order.php
/usr/www/users/oblaum/beta_skibaumarkt.de/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/customer-invoice.php
/usr/www/users/oblaum/beta_skibaumarkt.de/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/customer-new-account.php version 3.5.0 is out of date. The core version is 3.5.2
/usr/www/users/oblaum/beta_skibaumarkt.de/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/customer-note.php
/usr/www/users/oblaum/beta_skibaumarkt.de/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/customer-on-hold-order.php
/usr/www/users/oblaum/beta_skibaumarkt.de/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/customer-processing-order.php
/usr/www/users/oblaum/beta_skibaumarkt.de/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/customer-refunded-order.php
/usr/www/users/oblaum/beta_skibaumarkt.de/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/customer-reset-password.php
/usr/www/users/oblaum/beta_skibaumarkt.de/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/email-addresses.php
/usr/www/users/oblaum/beta_skibaumarkt.de/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/email-customer-details.php
/usr/www/users/oblaum/beta_skibaumarkt.de/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/email-downloads.php
/usr/www/users/oblaum/beta_skibaumarkt.de/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/email-footer.php
/usr/www/users/oblaum/beta_skibaumarkt.de/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/email-header.php
/usr/www/users/oblaum/beta_skibaumarkt.de/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/email-order-details.php
/usr/www/users/oblaum/beta_skibaumarkt.de/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/email-order-items.php
/usr/www/users/oblaum/beta_skibaumarkt.de/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/email-styles.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

### Composite Products ###

Database Version: 3.14.6
Template Overrides: –
`
</details>

**Comment by rrennick** [comment]
This should be addressed in #22012.

**Comment by willgorham** [comment]
I think what's being requested here is different. Instead of simply going back to allowing manual stock management for order editing (#22012), this request is to expand *automatic* stock management to order editing. I do see the value for allowing manual control, but I think integrating automatic stock control into all store management processes would be ideal.

**Comment by oblaum** [comment]
yes, this would be great to go onward with automatic stock management for this scenario.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/22329
