### ISSUE TITLE
Woocommerce changes my .po edits

### ISSUE THREAD

**Issue by FrutosTayen** [woocommerce/woocommerce#22102]
Hello everyone! So I have woocommerce in Spanish and in the Checkout Page theres a box under Company Name to fill out. In Spanish is "Nombre de la Empresa" which I have no use for so I edited with .po edit and changed it to RUT which is ID number (we use it for shipping details). But the system keeps reverting my editing to the original .po which is "Nombre de la Empresa". 

Any ideas on how to stop this from happening? I guess it could be related to some plugin. I can not use checkout field editor or such plugins because they couse my states menu to crush :(

The page is:
https://tayen.cl/checkout/

Any help will be much appreciated!

**Comment by rrennick** [comment]
You need to compile your .po file into a .mo file. Upload the .mo into you languages folder.

**Comment by FrutosTayen** [comment]
Hi rrennick! Thank you for your answer. And that´s what I do. Po edit generates both po and mo files. Then I eliminate the ones on wordpress and replace them with the newly generated.

**Comment by rrennick** [comment]
> But the system keeps reverting my editing to the original .po which is "Nombre de la Empresa".

If you have deleted & replaced the file but it's getting reverted back to the original file I would suggest you contact your hosting support.

**Comment by FrutosTayen** [comment]
Will do. Thanks a bunch!
