### ISSUE TITLE
Attributes containing "pa_" are not managed properly

### ISSUE THREAD

**Issue by Kerfred** [woocommerce/woocommerce#22101]
**Describe the bug**
If an attribute contains "pa_" in its slug, it is not managed correctly. The cause is that WooCommerce replaces all occurrences of "pa_" instead of replacing only if the taxonomy starts with "pa_".
In the code: str_replace('pa_', '') is used instead of preg_replace('/^pa_/', '').

One consequence is that the attribute name is wrong. For example, the attribute "SPA test" is displayed as "stest" in the backend and in the frontend.

**To Reproduce**
1. Create an attribute named "SPA test" with the slug "spa_test" (with an underscore)
2. Create a variable product - Go to Attributes section
3. Add the "SPA test" attribute
4. The attribute name displayed is "stest" instead of "SPA test" (backend and frontend)

**Screenshots**
See the attached 3 screenshots.

**Expected behavior**
WooCommerce should not remove "pa_" in the attribute name.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
WordPress 4.9.8
WooCommerce 3.5.2
```
</details>
![test product test import](https://user-images.githubusercontent.com/4131401/49338195-d2bf3c00-f61e-11e8-81d5-9f31dd894d72.png)
![edit product test import wordpress 2](https://user-images.githubusercontent.com/4131401/49338196-d357d280-f61e-11e8-8046-1ca0ad07f39f.png)
![attributes test import wordpress](https://user-images.githubusercontent.com/4131401/49338197-d357d280-f61e-11e8-8a68-1522ca5fa82c.png)

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22112
