### ISSUE TITLE
Refund doesn't reload order page when hash (#) is in URL

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce#22115]
**Describe the bug**
After clicking "Refund" on an admin order page, the refund is processed but the page is never reloaded if a hash is in the URL.  This is expected Javascript behavior, but doesn't work if a React router is being used.

**To Reproduce**
1. Install and activate [WC Admin](https://github.com/woocommerce/wc-admin/releases)
2. Go to any order page in the dashboard.
3. Refund any amount.
4. Note the page doesn't reload and the spinner spins indefinitely.

**Screenshots**
<img width="1185" alt="screen shot 2018-12-04 at 10 08 20 am" src="https://user-images.githubusercontent.com/10561050/49413942-91f52d80-f7ac-11e8-98f6-2f01f83108a7.png">

**Expected behavior**
Expected page to reload after refund was processed.

**Comment by rodrigoprimo** [comment]
Similar to #22113

**Comment by rodrigoprimo** [comment]
Closing as there is a PR already (#22116)
