### ISSUE TITLE
JS Page reload not working when there's hash in URL

### ISSUE THREAD

**Issue by kinging123** [woocommerce/woocommerce#22113]
**Describe the bug**
When the cart updates, the JS code in `cart.js` specifies how to handle the updates.
If the cart is empty, and the checkout element is on the same page as the cart page, the code should refresh the page.
See:

https://github.com/woocommerce/woocommerce/blob/d0491072e8a7d0a4535db0ec2bae4a6d43ff64fd/assets/js/frontend/cart.js#L73-L76

The problem with this code,  is that the line 
`window.location.href = window.location.href;`
only works when there's no hash on the page URL.
For example, when the URL is `http://domain.com/checkout#cart`, the refresh with href=href wouldn't work.
A better way to refresh would be to call `window.location.refresh()`.

**Comment by rodrigoprimo** [comment]
See #22114

Thanks for your contribution.
