### ISSUE TITLE
Pre-filled email address in check out

### ISSUE THREAD

**Issue by origamicrow** [woocommerce/woocommerce#22111]
**Describe the bug**
After choosing product and going to check out, the email for the buyer is prefilled with the system email for wordpress, yes it can be typed over but im afraid customers wont do this and we will be missing a vital part of the information
**To Reproduce**
1. Go to check out
3. Scroll down to email*

**Screenshots**
<a href="https://imgur.com/uH94y7b"><img src="https://i.imgur.com/uH94y7b.png" title="source: imgur.com" /></a>

**Expected behavior**
to be empty and make the user enter their own address to check out

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

### WordPress Environment ###

Home URL: http://celebritysendins.com
Site URL: http://celebritysendins.com
WC Version: 3.5.2
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.6
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.39-cll-lve
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 2.02MB
Database Data Size: 1.60MB
Database Index Size: 0.42MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.03MB + Index: 0.02MB
wp_comments: Data: 0.03MB + Index: 0.02MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB
wp_nf3_action_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_chunks: Data: 0.02MB + Index: 0.00MB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB
wp_nf3_field_meta: Data: 0.06MB + Index: 0.00MB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB
wp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB
wp_nf3_upgrades: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 0.78MB + Index: 0.05MB
wp_postmeta: Data: 0.15MB + Index: 0.05MB
wp_posts: Data: 0.12MB + Index: 0.02MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.00MB + Index: 0.01MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_usermeta: Data: 0.05MB + Index: 0.01MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

accordions: 1
attachment: 21
customize_changeset: 15
nav_menu_item: 4
page: 11
post: 2
product: 16
product_variation: 4
revision: 38
shop_order: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (7) ###

Accordions: by PickPlugins – 2.1.6 – Not tested with the active version of WooCommerce
Contact Widgets: by GoDaddy – 1.5.2
Ninja Forms: by The WP Ninjas – 3.3.19.1
Page Builder by SiteOrigin: by SiteOrigin – 2.9.2
SiteOrigin Widgets Bundle: by SiteOrigin – 1.13.3
Under Construction: by WebFactory Ltd – 3.25
WooCommerce: by Automattic – 3.5.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: #301 - /waiver/

### Theme ###

Name: Customizr
Version: 4.1.22
Author URL: https://presscustomizr.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by rrennick** [comment]
If you are logged in, the field is pre-populated with your email address.

**Comment by origamicrow** [comment]
>           If you are logged in, the field is pre-populated with your email address.

I'm sorry super new to woocommerce, what do you me by "logged in", I do not want any accounts for the site, or anyone to have to log in, I have unchecked any boxes for the account process and in testing nothing askes for information.  I have looked at the html and it shows this address as its value for the box.  or will this show a value for the user as different?

**Comment by rrennick** [comment]
> I do not want any accounts for the site, or anyone to have to log in

As a store manager/administrator, you are seeing an email address pre-populated because you are logged in.

**Comment by origamicrow** [comment]
Gotcha TY
