### ISSUE TITLE
Checkout locale hidden fields shown after initialization

### ISSUE THREAD

**Issue by vendidero** [woocommerce/woocommerce#22119]
The `init_checkout` function within checkout.js misses a call (trigger `country_to_state_changing`)  to check the fields for any hidden fields. That was accomplished through:

`$( '#billing_country, #shipping_country, .country_to_state' ).change();`

within older Woo version. Missing that call means that fields marked as "hidden" (through locale settings) are not hidden after initialization of the checkout. If you choose another country and then switch back to the original country the fields are being updated (through the `country_to_state_changing` binding within address-i18n.js) and therefor hidden accordingly. 

**To Reproduce**
1. Use a country with some hidden fields as default country, e.g. Angola (has hidden post code)
2. Go to the checkout - post code field is shown after initialization
3. Switch to another country and back
4. Post code field is hidden

**Comment by oblaum** [comment]
i need this fix as i use a plugin for the uid tax field in the eu. at the moment all customer gets this uid field and is confusing for them. it should hide for the base country.

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/22444
