### ISSUE TITLE
"I have read and agree to the website %s" always in English for multi language sites

### ISSUE THREAD

**Issue by BaltasarParreira** [woocommerce/woocommerce#22127]
I think this a bug since I tried with so many different themes and also the official Storefront,

Having a multi language site the phrase "I have read and agree to the website %s" near the checkbox at the end of the checkout page is always in English.

This can be resolved putting this in the child theme functions.php file:

```
if (!function_exists('My_terms_and_conditions_checkbox_text')) {
    function My_terms_and_conditions_checkbox_text( ) {
        return sprintf( __( 'I have read and agree to the website %s', 'woocommerce' ), '[terms]' ) ;
    }
}
add_filter('woocommerce_get_terms_and_conditions_checkbox_text', 'My_terms_and_conditions_checkbox_text', 10, 3);
```

**Comment by rodrigoprimo** [comment]
I was not able to reproduce this on a clean WooCommerce install using Storefront. I tested setting the site language to Brazilian Portuguese, and the string you mentioned is properly translated in the checkout page.

Closing for now as it doesn't look like this is a WooCommerce core bug. Maybe the problem is caused by the plugin you are using to set up a multi-language site? If you still believe this is a WooCommerce core bug, please open another issue following the bug report template (https://github.com/woocommerce/woocommerce/issues/new?template=Bug_report.md).

**Comment by BaltasarParreira** [comment]
I see, but just to let you know I'm using the following free plugins:

- Polylang
- Hyyan WooCommerce Polylang Integration

Apart this ones what is the alternative you recommend so I can have a multilingual shop and stop having this kind of missing translations problems?

**Comment by rodrigoprimo** [comment]
I also heard about WPML but I don't have experience with multi language stores so I can't vouch for it.

**Comment by emrec76** [comment]
Thanks @BaltasarParreira . It helped me 3 years later. For those who don't know, this is a bug caused by the theme and this code works perfectly.

**Comment by pjrfigueiredo** [comment]
It worked for me!
 thanks @BaltasarParreira

**Comment by Houzvicka** [comment]
It works for me too!
Thanks to @BaltasarParreira

**Comment by chonline507** [comment]
> I think this a bug since I tried with so many different themes and also the official Storefront,
> 
> Having a multi language site the phrase "I have read and agree to the website %s" near the checkbox at the end of the checkout page is always in English.
> 
> This can be resolved putting this in the child theme functions.php file:
> 
> ```
> if (!function_exists('My_terms_and_conditions_checkbox_text')) {
>     function My_terms_and_conditions_checkbox_text( ) {
>         return sprintf( __( 'I have read and agree to the website %s', 'woocommerce' ), '[terms]' ) ;
>     }
> }
> add_filter('woocommerce_get_terms_and_conditions_checkbox_text', 'My_terms_and_conditions_checkbox_text', 10, 3);
> ```
Excelente, este me funciono! gracias

**Comment by andrew0g** [comment]
For anyone who still steps upon this issue:

**WooCommerce does not always use translations for the Terms & Conditions checkbox text.**

`wc_terms_and_conditions_checkbox_text()` first checks the stored option
`woocommerce_checkout_terms_and_conditions_checkbox_text`.

If this option exists in the database (e.g. set via Customizer in the past), it overrides translations, so tools like Loco Translate will have no effect.

The default translated string is only used when the option is empty or not set.

**Fix:**

- Go to Appearance > Customize > WooCommerce > Checkout
- Update the "Terms and conditions checkbox text"
- Or remove/update the option directly (woocommerce_checkout_terms_and_conditions_checkbox_text)
- Or override it via the `woocommerce_get_terms_and_conditions_checkbox_text` filter

That’s why the text may stay in English even though translations are correctly loaded.
