### ISSUE TITLE
Configurin Shipping zones:  Postal codes 

### ISSUE THREAD

**Issue by jdivins** [woocommerce/woocommerce#22124]
Adding a new shipping zone from Portugal, with postalcodes: 10*  and selectig a free shiping method. 
When calculating shipping costs to Portugal potalcode 1000, woocommerce give me an error:

> Please enter a valid postcode / ZIP.

The postal code is correct as you can see in: https://en.wikipedia.org/wiki/Postal_codes_in_Portugal

Why I get invalid postal code and in consecuence the shipping cost configured in backend doesn't work?

1. Create new shipping zone to Portugal with postalcodes 10* and shipping method free
2. Add product to cart
3. Use cart shipping cost calculator with Portugal as country and 1000 as postalcode
4. See error: Please enter a valid postcode / ZIP. 
5. See that your shipping costs aren't calculated for your Portugal zone

**Screenshots**
<img width="988" alt="captura de pantalla 2018-12-04 a les 19 46 12" src="https://user-images.githubusercontent.com/1632358/49465241-677f9080-f7fd-11e8-95b4-aba49199dc13.png">

**Expected behavior**
I expect that calculator show shipping cost of the Portugal shipping zone

Does this happens with other regions?

**Comment by rrennick** [comment]
I tested this with Canadian postal codes & the correct rate was applied for `E*` when it was at the top of the shipping zone list.

**Comment by jdivins** [comment]
Try with Portugal

**Comment by jdivins** [comment]
I have tried now in store front with the full postalcode, 1000-120 instead of 1000, and it works.

**Comment by rrennick** [comment]
It also worked for me. This one can be closed.

**Comment by jdivins** [comment]
Yes! Thank you
