### ISSUE TITLE
Keeping prices the same regardless of tax rate Woocommerce not effecting manually added orders (in wp-admin)

### ISSUE THREAD

**Issue by FadiNouh1** [woocommerce/woocommerce#22135]
In Woocommerce, I am keeping prices the same regardless of tax rate using the filter:

    add_filter( 'woocommerce_adjust_non_base_location_prices', '__return_false' )

This is effecting the total calculations only on front end (which is fine), but when I am adding an order manually (in Wordpress backend wp-admin) this filter is not taking any effect.

tax rate : 19%

taxes option set to be (price of product including taxes)

**Frontpage (checkout):**

https://i.stack.imgur.com/OakPh.png

**backend (order summery):**

https://i.stack.imgur.com/OFV90.png

Is there any other filter doing the same function but on manually added orders in backend? 

Woocmmerce version 3.4.5

**Comment by rrennick** [comment]
The explanation for why it can't be done in the admin is on #19083.
