### ISSUE TITLE
Sorry, it seems the coupon "save50" is not yours - it has now been removed from your order.

### ISSUE THREAD

**Issue by hkalantari** [woocommerce/woocommerce#22133]
**Describe the bug**
A coupon exists which grants 50% discount and there is no restriction. If a customer applies that code on the cart, it validates and applies as expected. Entering an email address on checkout that does not match the restriction should result in "Sorry, it seems the coupon "some coupon code" is not yours - it has now been removed from your order.

**To Reproduce**
1. Go to https://ladderartspace.com.au/product-category/social-painting-workshops/
2. add one of the product to your chart
3. go to chart and apply the SAVE50 coupon
4. try to proceed, it doesnt work. for example, try paypal, and proceed, then you will receive this error:
Sorry, it seems the coupon "save50" is not yours - it has now been removed from your order.

**Screenshots**
https://drive.google.com/open?id=1u2SVPh8hMGc9YrevtFm9mwdBV5qC6Wxo

**Expected behavior**
works

**Comment by rrennick** [comment]
> A coupon exists which grants 50% discount and there is no restriction ... Entering an email address on checkout that does not match the restriction

You can't have a coupon that both has no restrictions & has an email restriction. You will need to clarify the problem you are describing.

**Comment by kloon** [comment]
That is how email restriction coupons work. Since at the cart we do not know the user email yet we allow the input of the coupon. We do however at checkout get the email before completing the order and then do the email restriction checks for the coupons, if the restriction then fail we return the error at checkout.

**Comment by pramodhanu** [comment]
I am facing the same problem. 
Sorry, it seems the coupon "ring" is not yours.

how to fix this bug. or how to properly configure coupon in woo-commerce in WordPress.

**Comment by mholubowski** [comment]
Yo what's up, I landed here with this problem and then eventually figured it out for myself. Maybe this will help someone.

I'm not claiming this is what's happening to the others in this thread...it's what happened on my end.

Make sure the "Allowed Emails" field is blank within the Coupon settings:

![image](https://user-images.githubusercontent.com/2035619/141599767-fca0b321-784a-418e-90c3-accd43cfbd7a.png)

Hope this helps other WooCommerce developers. - Mike from Solid Affiliate.
