### ISSUE TITLE
woocommerce some products not showing

### ISSUE THREAD

**Issue by devrieswouter** [woocommerce/woocommerce#22134]
I've done many searching, but can't find any solution...

I use Woocommerce for my shop, in the backend I have 420 products. But on my shop page, only 402... So 18 products are not displaying.
The individual links to the products pages do work. But they didn't appear on category pages, search pages and shop page.

I've tried to update, deactivate plugins, change permalinks, and change the display settings. Everything looks good. (stock is positive)

Has anyone any more options to try?

**Comment by rodrigoprimo** [comment]
I'm sorry, but we don't use GitHub issues for support, we use it exclusively for WooCommerce bugs, enhancements and feature requests. If you need support, you could try WooCommerce support forums on WordPress.org (https://wordpress.org/support/plugin/woocommerce) or, if you are a WooCommerce.com paying customer, please contact their support (https://woocommerce.com/my-account/create-a-ticket/).
