### ISSUE TITLE
WooCommerce 3.4.7 of wp.org is different from release of Github

### ISSUE THREAD

**Issue by lwxbr** [woocommerce/woocommerce#22138]
Good day, I noticed that the version of wp.org doesn't have the hook in version **3.4.7** (zip of wp.org) , The filter is called in 3.4.7 **woocommerce_checkout_skip_cart_is_empty_check** and was renamed to **woocommerce_checkout_redirect_empty_cart** afterwards. I found it in a commit of 23/05/2018: f7ec8c22de76cbbf53db9a6b8b0c9289dbe20d0f. And the version 3.4.7 was released second to Github in 18/10/2018 and the release commit is 141e20a18365c1a896407db734ba958e1270288a, note that commit is untagged. Which version I should rely on? The Github version or wp.org version?

**Comment by lwxbr** [comment]
Strange that when I read the history of the file **class-wc-shortcode-checkout.php** from release 3.4.7, the most recent commit that involves this file is this: 6bdf345b680dda0f6e8d66e0187ddfad11f0fe22. Why it didn't appear f7ec8c22de76cbbf53db9a6b8b0c9289dbe20d0f?

**Comment by kloon** [comment]
All the wp.org releases are based on the GitHub releases. We just remove certain development files and minify files when we release but the code is the same. So you can rely on both versions as the code is the same.

As for the version bump, that is just how we do our branching, we will create a new branch before starting to work on a new release cycle and then update the version in there before we kick off work. From that branch we will create releases and tags.

As for the hook, it was added in https://github.com/woocommerce/woocommerce/commit/f7ec8c22de76cbbf53db9a6b8b0c9289dbe20d0f but then the author later renamed the hook in https://github.com/woocommerce/woocommerce/commit/38185988114808ffb338c80a70410bfb2aab61a1

See commit history https://github.com/woocommerce/woocommerce/search?q=woocommerce_checkout_skip_update_order_review_expired&type=Commits
