### ISSUE TITLE
PayPal Standard doesn't return a changed shipping address.

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/woocommerce#22136]
**Describe the bug**
1620421-zen

I'm not certain if this is by design, but if so or a bug it doesn't work as you'd expect. :)

If a customer checks out with PayPal Standard and changes their shipping info on PayPals site this new shipping address doesn't seem to be returned to WooCommerce. 

**To Reproduce**
1. Go to pay for an order via PayPal Standard
2. Once logged in change your shipping address
3. Complete payment and return to your store
4. See error in the order, it has the shipping address entered before changing it on PayPal.com

**Expected behavior**
It would make sense that if the shipping address can be changed on PayPal.com that it would then be returned to WooCommerce and updated in the order.
**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
This is a limitation of PayPal. See https://www.paypal.com/us/smarthelp/article/why-can't-i-change-the-shipping-address-for-my-transaction-faq1354.
