### ISSUE TITLE
Order edit details - Add new item - Search Product && WP_DEBUG = true

### ISSUE THREAD

**Issue by gordonup** [woocommerce/woocommerce#22141]
If WP_DEBUG = true, cannot search products in order edit details page while adding a new item to a order.

**Comment by kloon** [comment]
Please check your error log and test by disabling all plugins except WooCommerce and switch to a default theme like Storefront or Twentyseventeen. I have WP_DEBUG enabled and the search works fine for me.

This is likely a plugin/theme conflict causing the issue for you.

Closing as I am unable to replicate.
