### ISSUE TITLE
User account country different from shop allowed shipping countries

### ISSUE THREAD

**Issue by nigel-wells** [woocommerce/woocommerce#22144]
**Describe the bug**
When a user edits their profile inside the WordPress dashboard they have the option to set the shipping country to any variable regardless of the specified allowed shipping countries. When this user then makes their way through to the checkout screen the country is forced to be one of the specified allowed countries yet the state/region selections reflect the country on their profile. If the country is limited to a single option there is no select box to change country which would then refresh the state/region field. The end result is you, as the user, are stuck on this screen as you can't select an appropriate state/region as the variables reflect a different country.

**To Reproduce**
1. Setup WooCommerce to ship to a single country only i.e. "New Zealand"
2. Create a user account (or use admin)
3. Go to the user profile area within WordPress
4. Set the shipping country to a country other than entered above i.e. "Australia"
5. Set the region to one of the available options
5. Go to the front end of the website
6. Add something to your cart
7. Go to the checkout screen
8. Tick the box to ship to another address
9. You will see the country has been set as a label (rather than a drop down box) as only one country was selected. It will reflect your setting above as to which country the shop can ship to
10. The state/region options will reflect the country in your user profile account and NOT the country displayed in step 9.
11. Attempting to submit the form will fail as the regions available are not applicable to the country mentioned in step 9

**Expected behavior**
The regions in step 10 should always reflect what has been displayed in step 9 and not rely on what was in the users profile.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://jupiter.apexdigital.co.nz
Site URL: https://jupiter.apexdigital.co.nz
WC Version: 3.5.2
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.13.8
PHP Version: 7.2.12
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.34

SUHOSIN Installed: –
MySQL Version: 5.5.60-MariaDB
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.2
WC Database Prefix: Xc9V5KoV_
MaxMind GeoIP Database: ✔
Total Database Size: 8.37MB
Database Data Size: 6.94MB
Database Index Size: 1.43MB
Xc9V5KoV_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
Xc9V5KoV_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
Xc9V5KoV_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
Xc9V5KoV_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
Xc9V5KoV_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
Xc9V5KoV_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
Xc9V5KoV_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
Xc9V5KoV_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
Xc9V5KoV_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
Xc9V5KoV_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
Xc9V5KoV_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
Xc9V5KoV_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
Xc9V5KoV_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
Xc9V5KoV_woocommerce_log: Data: 0.02MB + Index: 0.02MB
Xc9V5KoV_commentmeta: Data: 0.02MB + Index: 0.03MB
Xc9V5KoV_comments: Data: 0.02MB + Index: 0.09MB
Xc9V5KoV_defender_lockout: Data: 0.02MB + Index: 0.00MB
Xc9V5KoV_defender_lockout_log: Data: 0.05MB + Index: 0.00MB
Xc9V5KoV_gf_addon_feed: Data: 0.02MB + Index: 0.02MB
Xc9V5KoV_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
Xc9V5KoV_gf_entry: Data: 0.02MB + Index: 0.03MB
Xc9V5KoV_gf_entry_meta: Data: 0.02MB + Index: 0.05MB
Xc9V5KoV_gf_entry_notes: Data: 0.02MB + Index: 0.03MB
Xc9V5KoV_gf_form: Data: 0.02MB + Index: 0.00MB
Xc9V5KoV_gf_form_meta: Data: 0.05MB + Index: 0.00MB
Xc9V5KoV_gf_form_view: Data: 0.02MB + Index: 0.03MB
Xc9V5KoV_instapage_debug: Data: 0.02MB + Index: 0.00MB
Xc9V5KoV_instapage_options: Data: 0.02MB + Index: 0.00MB
Xc9V5KoV_instapage_pages: Data: 0.02MB + Index: 0.00MB
Xc9V5KoV_links: Data: 0.02MB + Index: 0.02MB
Xc9V5KoV_options: Data: 4.05MB + Index: 0.05MB
Xc9V5KoV_postmeta: Data: 1.39MB + Index: 0.13MB
Xc9V5KoV_posts: Data: 0.39MB + Index: 0.06MB
Xc9V5KoV_rg_form: Data: 0.02MB + Index: 0.00MB
Xc9V5KoV_rg_form_meta: Data: 0.05MB + Index: 0.00MB
Xc9V5KoV_rg_form_view: Data: 0.02MB + Index: 0.03MB
Xc9V5KoV_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
Xc9V5KoV_rg_lead: Data: 0.02MB + Index: 0.03MB
Xc9V5KoV_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
Xc9V5KoV_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
Xc9V5KoV_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
Xc9V5KoV_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
Xc9V5KoV_smush_dir_images: Data: 0.02MB + Index: 0.03MB
Xc9V5KoV_termmeta: Data: 0.02MB + Index: 0.03MB
Xc9V5KoV_terms: Data: 0.02MB + Index: 0.03MB
Xc9V5KoV_term_relationships: Data: 0.02MB + Index: 0.02MB
Xc9V5KoV_term_taxonomy: Data: 0.02MB + Index: 0.03MB
Xc9V5KoV_usermeta: Data: 0.02MB + Index: 0.03MB
Xc9V5KoV_users: Data: 0.02MB + Index: 0.05MB
Xc9V5KoV_wc_download_log: Data: 0.02MB + Index: 0.03MB
Xc9V5KoV_wc_webhooks: Data: 0.02MB + Index: 0.02MB
Xc9V5KoV_wpfront_ure_options: Data: 0.02MB + Index: 0.00MB
Xc9V5KoV_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
Xc9V5KoV_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 33
nav_menu_item: 9
page: 10
portfolio: 2
post: 1
product: 2
revision: 79
shop_order: 5
wdf_scan: 2
wdf_scan_item: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.5.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: NZD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #96 - /shop/
Cart: #104 - /cart-2/
Checkout: #105 - /checkout-2/
My account: #106 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by nigel-wells** [comment]
I've also been able to replicate the same issue without having a valid account if the "Default customer location" set to "Geolocate". In the description example if the user came in from an Australian IP then the country would be set to Australia which would then only return the valid Australian regions instead of the New Zealand regions.

**Comment by mikejolley** [comment]
The checkout issue is fixed in https://github.com/woocommerce/woocommerce/pull/22357

Regular customers don't have access to admin/profile page so I don't think that requires a patch. The account pages limit the available countries as needed.

Thanks
