### ISSUE TITLE
non numerical value warning on cart page

### ISSUE THREAD

**Issue by PaintingSilence** [woocommerce/woocommerce#22142]
**Describe the bug**
Hey!

I am looking for help regarding the below error message. I am trying to use the measurement price calculator plugin in connection with the woo commerce product table plugin. This error comes on the cart page when entering a quantity in the product table:

Warning: A non-numeric value encountered in /homepages/9/d19272688/htdocs/NW/wp-content/plugins/woocommerce-measurement-price-calculator/classes/class-wc-price-calculator-cart.php on line 760

Warning: A non-numeric value encountered in /homepages/9/d19272688/htdocs/NW/wp-content/plugins/woocommerce-measurement-price-calculator/classes/class-wc-price-calculator-cart.php on line 760

I have tried the following: 
changing line 760: 
$weight += $item['data']->get_weight() * $this->get_item_quantity( $item );
To:
$weight += ((int)$item['data']->get_weight() * (int)$this->get_item_quantity( (int)$item ));

Which makes the error disappear but does not solve the problem due to same behavior. 

Thank you much for you help, hugely appreciated!

**To Reproduce**
1. Go to 'https://kraeutergarten-muenchen.de/NW/shop/'
2. 'enter quantity for product and add to cart'
3. 'go to cart page'
4. See error: 
Warning: A non-numeric value encountered in /homepages/9/d19272688/htdocs/NW/wp-content/plugins/woocommerce-measurement-price-calculator/classes/class-wc-price-calculator-cart.php on line 760

**Screenshots**
product table page
![image](https://user-images.githubusercontent.com/45639889/49542793-c9f88f80-f8d6-11e8-8087-b89a4ec1ce1f.png)

Quantity is not added correctly (should be 4, instead is 1)
![image](https://user-images.githubusercontent.com/45639889/49542914-1774fc80-f8d7-11e8-8e37-41ba8f629c1e.png)

Check out cart displays error: 
![image](https://user-images.githubusercontent.com/45639889/49542944-2eb3ea00-f8d7-11e8-922b-36bcbe96d2fb.png)

**Expected behavior**
quantity is not added to cart due to error

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only Measurement price calculator and Product Table plugin are active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
4.9.8–de_DE
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
`
### WordPress Environment ###

Home URL: https://kraeutergarten-muenchen.de/NW
Site URL: https://kraeutergarten-muenchen.de/NW
WC Version: 3.5.2
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.12
PHP Post Max Size: 64 MB
PHP Time Limit: 50000
PHP Max Input Vars: 5000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.60-0+deb7u1-log - Wir empfehlen mindestens MySQL-Version 5.6. Siehe: WordPress-Anforderungen
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.1
WC Database Prefix: kgm_
MaxMind GeoIP Database: ✔
Datenbank-Gesamtgröße: 3.15MB
Datenbank-Datengröße: 2.86MB
Datenbank-Indexgröße: 0.29MB
kgm_woocommerce_sessions: Daten: 0.07MB + Index: 0.01MB
kgm_woocommerce_api_keys: Daten: 0.00MB + Index: 0.00MB
kgm_woocommerce_attribute_taxonomies: Daten: 0.00MB + Index: 0.00MB
kgm_woocommerce_downloadable_product_permissions: Daten: 0.00MB + Index: 0.00MB
kgm_woocommerce_order_items: Daten: 0.00MB + Index: 0.00MB
kgm_woocommerce_order_itemmeta: Daten: 0.00MB + Index: 0.00MB
kgm_woocommerce_tax_rates: Daten: 0.01MB + Index: 0.01MB
kgm_woocommerce_tax_rate_locations: Daten: 0.00MB + Index: 0.00MB
kgm_woocommerce_shipping_zones: Daten: 0.00MB + Index: 0.00MB
kgm_woocommerce_shipping_zone_locations: Daten: 0.00MB + Index: 0.00MB
kgm_woocommerce_shipping_zone_methods: Daten: 0.00MB + Index: 0.00MB
kgm_woocommerce_payment_tokens: Daten: 0.00MB + Index: 0.00MB
kgm_woocommerce_payment_tokenmeta: Daten: 0.00MB + Index: 0.00MB
kgm_woocommerce_log: Daten: 0.00MB + Index: 0.00MB
kgm_commentmeta: Daten: 0.00MB + Index: 0.00MB
kgm_comments: Daten: 0.00MB + Index: 0.01MB
kgm_eg_grids: Daten: 0.00MB + Index: 0.00MB
kgm_eg_item_elements: Daten: 0.00MB + Index: 0.00MB
kgm_eg_item_skins: Daten: 0.60MB + Index: 0.01MB
kgm_eg_navigation_skins: Daten: 0.03MB + Index: 0.01MB
kgm_failed_jobs: Daten: 0.00MB + Index: 0.00MB
kgm_links: Daten: 0.00MB + Index: 0.00MB
kgm_mailchimp_carts: Daten: 0.00MB + Index: 0.00MB
kgm_options: Daten: 1.61MB + Index: 0.10MB
kgm_postmeta: Daten: 0.22MB + Index: 0.07MB
kgm_posts: Daten: 0.17MB + Index: 0.03MB
kgm_queue: Daten: 0.00MB + Index: 0.00MB
kgm_revslider_css: Daten: 0.09MB + Index: 0.00MB
kgm_revslider_layer_animations: Daten: 0.00MB + Index: 0.00MB
kgm_revslider_navigations: Daten: 0.00MB + Index: 0.00MB
kgm_revslider_sliders: Daten: 0.02MB + Index: 0.00MB
kgm_revslider_slides: Daten: 0.02MB + Index: 0.00MB
kgm_revslider_static_slides: Daten: 0.00MB + Index: 0.00MB
kgm_termmeta: Daten: 0.00MB + Index: 0.01MB
kgm_terms: Daten: 0.00MB + Index: 0.01MB
kgm_term_relationships: Daten: 0.00MB + Index: 0.00MB
kgm_term_taxonomy: Daten: 0.00MB + Index: 0.00MB
kgm_UPCP_Catalogues: Daten: 0.00MB + Index: 0.00MB
kgm_UPCP_Catalogue_Items: Daten: 0.00MB + Index: 0.00MB
kgm_UPCP_Categories: Daten: 0.00MB + Index: 0.00MB
kgm_UPCP_Custom_Fields: Daten: 0.00MB + Index: 0.00MB
kgm_UPCP_Fields_Meta: Daten: 0.00MB + Index: 0.00MB
kgm_UPCP_Items: Daten: 0.00MB + Index: 0.00MB
kgm_UPCP_Item_Images: Daten: 0.00MB + Index: 0.00MB
kgm_UPCP_SubCategories: Daten: 0.00MB + Index: 0.00MB
kgm_UPCP_Tagged_Items: Daten: 0.00MB + Index: 0.00MB
kgm_UPCP_Tags: Daten: 0.00MB + Index: 0.00MB
kgm_UPCP_Tag_Groups: Daten: 0.00MB + Index: 0.00MB
kgm_UPCP_Videos: Daten: 0.00MB + Index: 0.00MB
kgm_usermeta: Daten: 0.02MB + Index: 0.01MB
kgm_users: Daten: 0.00MB + Index: 0.01MB
kgm_wc_download_log: Daten: 0.00MB + Index: 0.00MB
kgm_wc_webhooks: Daten: 0.00MB + Index: 0.00MB
kgm_yoast_seo_links: Daten: 0.00MB + Index: 0.00MB
kgm_yoast_seo_meta: Daten: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 12
custom_css: 1
customize_changeset: 21
jetpack_migration: 2
nav_menu_item: 14
o-discount: 2
o-list: 2
page: 26
post: 4
product: 7
revision: 78
shop_coupon: 1
shop_order: 2
woo_discount_cart: 1
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (35) ###

Booked: von Boxy Studio – 2.2.1
Child Theme Configurator: von Lilaea Media – 2.3.0.4
Contact Form 7: von Takayuki Miyoshi – 5.0.5
DHL for WooCommerce: von DHL – 1.3.7 – Nicht getestest mit der aktiven WooCommerce-Version
Essential Grid: von ThemePunch – 2.2.5
Flexible Shipping: von WP Desk – 3.0.6
Gutenberg: von Gutenberg-Team – 4.6.1
PHP code snippets (Insert PHP): von Will Bontrager Software
LLC 
Webcraftic  – 2.0.6

Instagram Feed: von Smash Balloon – 1.10.2
Jetpack von WordPress.com: von Automattic – 6.8
WPBakery Page Builder: von Michael M - WPBakery.com – 5.5.5
Klarna Payments for WooCommerce: von krokedil
klarna
automattic – 1.6.3

Mailchimp for WooCommerce: von Mailchimp – 2.1.11 – Nicht getestest mit der aktiven WooCommerce-Version
Slider Revolution: von ThemePunch – 5.4.8
Tabby Responsive Tabs: von cubecolour – 1.2.3
ThemeREX Utilities: von ThemeREX – 3.2
All In One Addons for WPBakery Page Builder (formerly Visual Composer): von Sike – 3.5.0
Woocommerce delete product images: von Husain Ahmed – 1.0.2 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Blocks: von Automattic – 1.2.0
WooCommerce Discounts Plus: von Fahad Mahmood – 3.0.6 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Extra Product Sorting Options: von SkyVerge – 2.7.3
WooCommerce PayPal Checkout Gateway: von WooCommerce – 1.6.5
WooCommerce Stripe-Gateway: von WooCommerce – 4.1.13
WooCommerce Germanized: von Vendidero – 2.2.4
WooCommerce Raster / Listen Schalter: von James Koster – 1.2.1 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Preisberechner für Abmessungen (Fläche, Gewicht, Volumen): von SkyVerge – 3.13.6
WooCommerce Product Table: von Barn2 Media – 2.3
WooCommerce Services: von Automattic – 1.17.1
WooCommerce: von Automattic – 3.5.2
Yoast SEO: von Team Yoast – 9.2.1
WP-Dateimanager: von mndpsingh287 – 3.7
WP Instagram Widget: von Scott Evans – 2.0.3
WP-Members: von Chad Butler – 3.2.4.2
WPGlobus Mobile Menu: von WPGlobus – 1.2.2
WPGlobus: von WPGlobus – 1.9.30

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop-Basis: #14 - /shop/
Warenkorb: #15 - /shop/warenkorb/
Kasse: #16 - /shop/kasse/
Mein Konto: #17 - /shop/mein-konto/
Allgemeine Geschäftsbedingungen: #10 - /shop/agb/

### Theme ###

Name: TheLeaf
Version: 1.7
Author URL: http://ancorathemes.comt/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

</details>

**Comment by thomas-zg** [comment]
It looks like that the warning is raised by the woocommerce-measurement-price-calculator. The best way would be to contact the owner of the plugin to get support. The warning is not caused by the WC Core.

**Comment by PaintingSilence** [comment]
Hi Thomas! I think so too, but was not able to find a measurement-price-calculator thread here at GitHub (I am very new to this board) so I thought this comes closest. Could you kindly redirect me to an existing thread or can I open a new one regarding this plugin? I have contacted the support, already, but want to reach out broadly. 

Thank you very much!

**Comment by thomas-zg** [comment]
You wouldn't find a public repository on GitHub, the only and correct way is to contact the product support.

**Comment by kloon** [comment]
As @thomas-zg pointed out. Please contact support for issues on paid plugins. We only deal with WooCommerce core bugs on this repository.

Could you please contact us at <a href=" https://woocommerce.com/my-account/create-a-ticket/?form=ticket”>WooCommerce.com > My Account > Tickets</a>? You may need to create an account.  We will be able to help you further there.
