### ISSUE TITLE
Cart Shipping Destination text redundant for Free shipping only stores.

### ISSUE THREAD

**Issue by WM4362** [woocommerce/woocommerce#22150]
Commit [a1f927d4f796b6dbc5b963e95735a4716b066dfa](https://github.com/woocommerce/woocommerce/commit/a1f927d4f796b6dbc5b963e95735a4716b066dfa#diff-a2906a568be9742118afb5adc6402c23R46) introduced a "bug" (_more of a quirk_) whereby if a store is setup with ENTIRELY/ONLY Free Shipping, the Cart page Shipping field now displays either "_This is only an estimate. Prices will be updated during checkout._" or "_Estimate for LOCATION._" under the "Free Shipping" text (depending on what the Woocommerce>Settings>General>"Default customer location" is set to).

For entirely "Free Shipping" stores (_where typically the Shipping Calculator is also disabled on the Cart page_), this can be confusing/unnerving for customers (who are typically _expecting_ free shipping) and it's also a bit redundant/naff looking! :-)

I haven't tested it, but I suspect these messages will also be displayed for stores where Free Shipping is available (amongst other options) and yet all the conditions to receive Free Shipping have been met.

1. Setup a store with ENTIRELY/ONLY Free Shipping (i.e. 1 or more Shipping Zones/Regions with the only Shipping method set being "Free shipping" with "Free shipping requires..." set to "N/A").
2. Add something to the Cart.
3. Visit the Cart page.
4. Behold - the `p.woocommerce-shipping-destination` text!

**Expected behavior**
Ideally, when the conditions for 'free_shipping' have been met (be it is the ONLY shipping method or otherwise) then the `p.woocommerce-shipping-destination` paragraph would not be displayed within the Shipping field on the Cart page.

Some further conditional checks for 'free_shipping' in the cart-shipping.php template should do it. A simple workaround for now is to set `p.woocommerce-shipping-destination` to `display: none;` within the child style.css.

If anything's not clear, just let me know! :-)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
WordPress environment
Home URL: 		http://localhost/woomaster
Site URL: 		http://localhost/woomaster
WooCommerce version: 		3.5.2
Log directory writable: 		/var/www/html/woomaster/wp-content/uploads/wc-logs/
WordPress version: 		4.9.8	
WordPress multisite: 		–
WordPress memory limit: 		256 MB	
WordPress debug mode: 		–
WordPress cron: 		
Language: 		en_AU
External object cache: 		–
Server environment
Server info: 		Apache/2.4.25 (Debian)
PHP version: 		7.0.30-0+deb9u1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version	
PHP post max size: 		8 MB
PHP time limit: 		30
PHP max input vars: 		1000
cURL version: 		7.52.1, OpenSSL/1.0.2l
SUHOSIN installed: 		–
MySQL version: 		5.5.5-10.1.26-MariaDB-0+deb9u1	
Max upload size: 		8 MB
Default timezone is UTC: 		
fsockopen/cURL: 		
SoapClient: 		Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.	
DOMDocument: 		
GZip: 		
Multibyte string: 		
Remote post: 		
Remote get: 		
Database
WooCommerce database version: 		3.3.5
Database prefix 	  	wp_	
MaxMind GeoIP database: 		/var/www/html/woomaster/wp-content/uploads/GeoLite2-Country.mmdb
Total Database Size 	  	2.52MB
Database Data Size 	  	1.67MB
Database Index Size 	  	0.85MB
wp_woocommerce_sessions 	  	Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys 	  	Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies 	  	Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions 	  	Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items 	  	Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta 	  	Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates 	  	Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations 	  	Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones 	  	Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations 	  	Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods 	  	Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens 	  	Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta 	  	Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log 	  	Data: 0.02MB + Index: 0.02MB
wp_commentmeta 	  	Data: 0.02MB + Index: 0.03MB
wp_comments 	  	Data: 0.02MB + Index: 0.09MB
wp_email_log 	  	Data: 0.02MB + Index: 0.00MB
wp_links 	  	Data: 0.02MB + Index: 0.02MB
wp_options 	  	Data: 1.05MB + Index: 0.02MB
wp_postmeta 	  	Data: 0.08MB + Index: 0.03MB
wp_posts 	  	Data: 0.02MB + Index: 0.06MB
wp_termmeta 	  	Data: 0.02MB + Index: 0.03MB
wp_terms 	  	Data: 0.02MB + Index: 0.03MB
wp_term_relationships 	  	Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy 	  	Data: 0.02MB + Index: 0.03MB
wp_usermeta 	  	Data: 0.02MB + Index: 0.03MB
wp_users 	  	Data: 0.02MB + Index: 0.05MB
wp_wc_download_log 	  	Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks 	  	Data: 0.02MB + Index: 0.02MB
Post Type Counts
attachment 	  	16
page 	  	7
post 	  	2
product 	  	12
revision 	  	2
shop_order 	  	1
Security
Secure connection (HTTPS): 		Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors 		
Active plugins (1)
WooCommerce 	  	by Automattic – 3.5.2
Settings
API enabled: 		
Force SSL: 		–
Currency 		AUD ($)
Currency position 		left
Thousand separator 		,
Decimal separator 		.
Number of decimals 		2
Taxonomies: Product types 		external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomies: Product visibility 		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
WooCommerce pages
Shop base:		#5 - /shop/
Cart:		#6 - /cart/
Checkout:		#7 - /checkout/
My account:		#8 - /my-account/
Terms and conditions:		Page not set
Theme
Name: 		Storefront
Version: 		2.3.5
Author URL: 		https://woocommerce.com/
Child theme: 		– If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme	
WooCommerce support: 		
Templates
Overrides: 	  	–
```
</details>

**Comment by el-presidente** [comment]
This seems to pop up once in awhile - I also had a customer who were confused.

I removed it with:

`.woocommerce-shipping-destination {
display:none;
}`

**Comment by mouligreenlaw** [comment]
Adding another ticket to this 1703047-zen

**Comment by mikejolley** [comment]
For the time being, there is a filter named `woocommerce_shipping_estimate_html` which can control the text "This is only an estimate. Prices will be updated during checkout.".

I think we can solve this by generalizing the text slightly. I'll submit a PR.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22467
