### ISSUE TITLE
why i am not update my products stock

### ISSUE THREAD

**Issue by saddamSaifi1992** [woocommerce/woocommerce#22151]
why i am not update my products stock. before and after woocommer edit product page one error which 

**"The stock has not been updated because the value has changed since editing."**
how can I resolve this issue please provide me solution.

**Comment by saddamSaifi1992** [comment]
![image](https://user-images.githubusercontent.com/30666676/49576336-eba35680-f96a-11e8-87b5-f483c5f3276d.png)

**Comment by rodrigoprimo** [comment]
I'm closing this issue as you didn't provide all the information requested in the [bug report template](https://github.com/woocommerce/woocommerce/issues/new?template=Bug_report.md). Please open another issue and follow the template. Thanks.
