### ISSUE TITLE
Country Name is no longer displayed in Billing and Shipping addresses on Order Page after updating to WC 3.5.2

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#22158]
**Describe the bug**

Country Name is no longer displayed in Billing and Shipping addresses on Order Page after updating to WC 3.5.2. This only happens if the Shop Base country set in General Settings is the same as the Shipping and Billing Address Country of the order placed. 

**To Reproduce**
1. Activate WooCommerce 3.5.1.
2. Set the Store Address country to United States (as an example):

![](https://cloudup.com/cjRbQJESCGY+)
Image Link: https://cloudup.com/cjRbQJESCGY

3. Place an order on the site and specify the country of the Billing and Shipping Addres to be the United States as well.
4. Check the order and you will see that the country is being disaplyed in the Address:

![](https://cloudup.com/c677k3bC0jI+)
Image Link: https://cloudup.com/c677k3bC0jI

5. Update WooCommerce to 3.5.2. 
6. Keep the settings as is.
7. Check the same order number as in step 4 and you will see the country is no longer being disaplayed:

![](https://cloudup.com/cmN30waX98g+)
Image Link: https://cloudup.com/cmN30waX98g

Note that if you change the Store Address country to United Kingdom for example, the country will be visible in the Shipping and Billing address on the order page. 

**Screenshots**

See above. 

**Expected behavior**

I expected the country name to be displayed in the Shipping and Billing address on the order page even if it matches the country specified in the Store Address fields of the General WooCommerce settings. 

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: https://jamosova.mystagingwebsite.com
Site URL: https://jamosova.mystagingwebsite.com
WC Version: 3.5.2
Log Directory Writable: ✔
WP Version: 4.9.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.32 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.61.1
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.17-MariaDB
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 7.46MB
Database Data Size: 4.27MB
Database Index Size: 3.19MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.11MB + Index: 0.13MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.13MB + Index: 0.09MB
wp_groups_capability: Data: 0.02MB + Index: 0.03MB
wp_groups_group: Data: 0.02MB + Index: 0.02MB
wp_groups_group_capability: Data: 0.02MB + Index: 0.02MB
wp_groups_user_capability: Data: 0.02MB + Index: 0.02MB
wp_groups_user_group: Data: 0.02MB + Index: 0.02MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.41MB + Index: 0.06MB
wp_postmeta: Data: 1.50MB + Index: 1.86MB
wp_posts: Data: 0.33MB + Index: 0.09MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.06MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_recommendations: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_session_activity: Data: 0.05MB + Index: 0.00MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 98
bookable_person: 2
bookable_resource: 3
course: 3
jetpack_migration: 2
jp_img_sitemap: 3
jp_sitemap: 3
jp_sitemap_master: 3
lesson: 6
nav_menu_item: 18
order_shipment: 8
page: 16
post: 4
product: 45
product_variation: 66
quiz: 6
revision: 22
scheduled-action: 2
shop_coupon: 2
shop_order: 98
shop_subscription: 10
wc_booking: 11
wc_membership_plan: 3
wc_order_status: 8
wc_user_membership: 9
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.5.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #3 - /
Cart: #4 - /cart/
Checkout: #5 - /checkout/
My account: #6 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.5 – 2.4.0 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by siananda** [comment]
`// Country is not needed if the same as base.
if ( $country === $this->get_base_country() && ! apply_filters( 'woocommerce_formatted_address_force_country_display', true ) ) {
	$format = str_replace( '{country}', '', $format );
}`

**Comment by siananda** [comment]
### Conflict code
`// Country is not needed if the same as base.
if ( $country === $this->get_base_country() && ! apply_filters( 'woocommerce_formatted_address_force_country_display', false ) ) {
	$format = str_replace( '{country}', '', $format );
}`

The country does not show if the base country and billing or shipping country are same.

`if ( $country === $this->get_base_country() && ! apply_filters( 'woocommerce_formatted_address_force_country_display', true ) ) ` 

In WooCommerce version 5.0.1 this condition always false. Because 

! apply_filters( 'woocommerce_formatted_address_force_country_display', **true** ) is **false**

But In WooCommerce version 5.0.2 this conditon will be false if and only if the base country and billing or shipping country are not same
`if ( $country === $this->get_base_country() && ! apply_filters( 'woocommerce_formatted_address_force_country_display', false ) )`

! apply_filters( 'woocommerce_formatted_address_force_country_display', **false** ) is **true**

**Comment by rrennick** [comment]
This was just changed for #21857. We can't have this work so everyone has the default behaviour. The filer names indicates that by default country display is off when the customer is in the same country as the store.

To be consistent with the filter name if a store owner wants to force the country display then this can be used

`add_filter( 'woocommerce_formatted_address_force_country_display', '__return_true' );`

**Comment by PhilipVerbeek** [comment]
Hi. I tried adding :  add_filter( 'woocommerce_formatted_address_force_country_display', '__return_true');
This doesn't seem to work for me. I run WC 4.2.1. Did something change to this behaviour?
Love to hear it. Thanks

**Comment by kdta91** [comment]
@rrennick saved my day. The filter works for WC 4.9.8

**Comment by danicastejic** [comment]
@rrennick you are a lifesaver! Thank you!

**Comment by hamster2116** [comment]
Any news on this? Still happening in Version 6.8.2

**Comment by rupert-quaderer** [comment]
Same Issue here...any suggestions?
