### ISSUE TITLE
Coupon email restriction not working correctly

### ISSUE THREAD

**Issue by contremaitre** [woocommerce/woocommerce#22161]
**Describe the bug**
I create a test coupon, with restriction on email adress test@gmail.com
If a customer with an email adresse like xxx-test@gmail.com (anything ending by test@gmail.com) makes an order, it will accept the coupon

**To Reproduce**
1- Create a coupon and add a restriction by email adress test@gmail.com
2- Create a new order, with billing email xxxtest@gmail.com
3- apply the coupon
4- validate the order

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by robertpop** [comment]
This bug is still present and doesn't seem to have been fixed :(

**Comment by claudiosanches** [comment]
@robertpop please start a bug report and provide steps to reproduce, I'll be happy to test and check it. Thanks.
