### ISSUE TITLE
order note send email issue!

### ISSUE THREAD

**Issue by Brucehanyf** [woocommerce/woocommerce#22175]
Dear woocommerce team,

I have  a issue for using rest api  [ /wp-json/wc/v3/orders/<id>/notes ] to create an notes:
the order is created manually 
![image](https://user-images.githubusercontent.com/29501667/49683638-f85ab280-fb02-11e8-9026-6256c7a3676d.png)
![image](https://user-images.githubusercontent.com/29501667/49683641-00b2ed80-fb03-11e8-8dfc-fef2508b311f.png)
hope you will reply soon 
Best Regards
Bruce

**Comment by rrennick** [comment]
Can you provide the data you are including in the API request?

**Comment by Brucehanyf** [comment]
> Can you provide the data you are including in the API request?
Dear rrennick , 
I have resolved it, just add a header ["Content-type","application/json"]
thanks for your reply!
Best Regards
