### ISSUE TITLE
Total stock of variable products in the admin table/list of products.

### ISSUE THREAD

**Issue by ralphonz** [woocommerce/woocommerce#22174]
**Is your feature request related to a problem? Please describe.**
Total stock of variable products is not shown in the admin table/list of products.  When stock is managed at the variation level no total stock is show as illustrated in this screenshot:
<img width="1680" alt="screenshot 2018-12-07 at 20 31 58" src="https://user-images.githubusercontent.com/5305856/49671327-65b50780-fa5f-11e8-85dd-6acb6d4f9642.png">

**Describe the solution you'd like**
However, the total stock of all variations should be added together and displayed in brackets next to the text as it is for simple products illustrated in this screenshot:
<img width="1680" alt="screenshot 2018-12-07 at 20 33 49" src="https://user-images.githubusercontent.com/5305856/49671380-8da46b00-fa5f-11e8-97af-df2ca50d915b.png">

This would allow for better management of stock at a glance.

**Comment by kloon** [comment]
This complicates things as variable products can manage stock on a variation level as well as a variable level. This will also have an impact on performance as you will need to look up stock levels for each variation, some stores have hundreds of variation combinations per a single variable product. As you can imagine, that can slow things down quite a lot.

Thanks for the suggestion however and we will be sure to consider and evaluate it for a future release.

**Comment by ralphonz** [comment]
> This complicates things as variable products can manage stock on a variation level as well as a variable level. 

Thanks for the response.  Could you explain the above statement for me?  Do you mean they can manage stock on a variable level and a product level?  Is this not a simple check to see if "Enable stock management at product level" is on or off?  Presumably this check is already taking place.

**Comment by kloon** [comment]
Unfortunately it is not that simple since you can have a combination of stock at a parent level and certain variations at the variation level for that specific product. This involves looping through variations just to show a simple count slowing things down.
