### ISSUE TITLE
Checkout option to require Phone field does not work 

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce#22173]
**Describe the bug**
When choosing the option to require phone field under **Appearance > Customize > WooCommerce > Checkout**, the field still shows as optional and allows for the order to process without content in it.

![Screenshot](http://cld.wthms.co/KLwDsx+)
Image Link: http://cld.wthms.co/KLwDsx

**Comment by rrennick** [comment]
Can you switch to the Storefront theme & deactivate all plugins except WooCommerce to see if you still have the issue?

**Comment by kloon** [comment]
Not able to replicate this with Twentyseventeen or Storefront http://cld.wthms.co/ovC3HP, possibly a conflict issue @johndcoy

**Comment by menakas** [comment]
I could see this error when WooCommerce PayPal Checkout Gateway plugin is activated.
