### ISSUE TITLE
Product schema has missing fields 

### ISSUE THREAD

**Issue by UttamSharma007** [woocommerce/woocommerce#22188]
google structured data testing tool showing the warnings in case of product schema markup. some markup values are missing like gtin8, gtin12, gtin13, gtin14, mpn, isbn, review, sku etc.

Steps - 
Go to the Google structured data testing tool and test your single product page.

Screenshots -
https://goo.gl/8y76SE

**Comment by rrennick** [comment]
Fixed in #22045
