### ISSUE TITLE
Variation name not always showing on api request

### ISSUE THREAD

**Issue by tmblog** [woocommerce/woocommerce#22180]
**Describe the bug**
Using the V2 API the line items sometimes contain the variation name and at times it doesn't I am baffled as I cannot find out why, for example if products are using the attributes as variations then at times it is suffixed onto the line items for some products then there are times when it isn't.
**Here's an example of an order from the API using PHP.**

```
foreach($val->line_items as $item){
echo "<strong>".$item->quantity."x ".$item->name."</strong> - ".$item->subtotal."<br>";
foreach($item->meta_data as $variation){
echo ucwords(str_replace(["_","-","pa"], " ", $variation->key)).": ";
echo ucwords(str_replace("-", " ", $variation->value))."<br>";
}
```

```
1x Tikka Masala - 7.25
Dish: Chicken
```
Dish is the meta_data, in this instance the variation didn't show automatically.
**Here is another example:**
```
1x Rogan Josh - Lamb - 5.95
Dish: Lamb
```
In this instance the variation (meta_data) has been added to the end of the product (Lamb) by default.

**To Reproduce**
Create some products with variations, and see which ones show with meta_data attached and which ones dont. I though it was because some products had custome attributes but it's actually not, in the above example both are using the dish attribute which was created in the attributes section.

**Update:**
I believe the bug is reproduced when only a few of the items in the attributes are only selected as variation e.g. Attribute Size has S,M,L,XL
If **all** is selected to be used for variation then it shows by default however if only a **subset** is chosen for variation e.g. S and M then a loop is needed to show the meta_data.

**Expected behavior**
Either it should show meta_data for all products or not.

**Isolating the problem (mark completed items with an [x]):**
This isn't dependant on any plugins as it is calling API independantly from a PHP script.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WC Version: 3.5.2
Log Directory Writable: ✔
WP Version: ❌ 4.9.8 - There is a newer version of WordPress available (5.0)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.2.12
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.60.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 10.1.37-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.2
WC Database Prefix: wp_
Total Database Size: 5.10MB
Database Data Size: 4.36MB
Database Index Size: 0.74MB
wp_woocommerce_sessions: Data: 1.18MB + Index: 0.04MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.01MB + Index: 0.01MB
wp_woocommerce_order_itemmeta: Data: 0.13MB + Index: 0.06MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.01MB
wp_comments: Data: 0.02MB + Index: 0.02MB
wp_layerslider: Data: 0.00MB + Index: 0.00MB
wp_layerslider_revisions: Data: 0.00MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 0.93MB + Index: 0.05MB
wp_postmeta: Data: 1.30MB + Index: 0.39MB
wp_posts: Data: 0.74MB + Index: 0.05MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.01MB + Index: 0.03MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_usermeta: Data: 0.03MB + Index: 0.02MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.01MB + Index: 0.01MB
wp_yoast_seo_meta: Data: 0.00MB + Index: 0.01MB

### Post Type Counts ###

attachment: 30
avia_framework_post: 10
nav_menu_item: 8
page: 10
post: 1
product: 155
product_variation: 95
revision: 1
shop_coupon: 3
shop_order: 34

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (7) ###

WooCommerce Extended Coupon Features FREE: by Soft79 – 3.0.5
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.3.5 – 1.5.0 is available – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.1.13
WooCommerce Opening Hours / Delivery Times: by DavidAnderson – 1.10.4
WooCommerce: by Automattic – 3.5.2
Yoast SEO: by Team Yoast – 9.2.1
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.2.6


### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: ❌ Page not set
Basket: #618 - /basket/
Checkout: #619 - /checkout/
My account: #620 - /my-account/
Terms and conditions: #47 - /terms-conditions/

### Theme ###

Name: Livemenu
Version: – 0 is available
Author URL: 
Child Theme: ✔
Parent Theme Name: Enfold
Parent Theme Version: 4.4.1
Parent Theme Author URL: https://kriesi.at
WooCommerce Support: ✔

### Templates ###

Overrides: livemenu/woocommerce/emails/customer-completed-order.php
`
```
</details>

**Comment by rrennick** [comment]
Can you provide the steps including both attribute setup & api requests to reproduce the issue?

**Comment by tmblog** [comment]
Do you mean how to add attributes in WooCommerce?
To do that go to Products>attributes> created using that and then added by configuring terms
In the product choose variable product then on the attributes tab select the required attribute then choose which terms are required then create variations from each (if required e.g. each one different price) and set price.
Is that what you mean.
What are you expecting for the api request?

**Comment by rrennick** [comment]
> Do you mean how to add attributes in WooCommerce?

I'm asking you to provide the details necessary to reproduce this issue without having to guess at what steps were taken.

> What are you expecting for the api request?

For example, in the description of #22177, the reporter provided the data submitted to the API.

**Comment by tmblog** [comment]
To reproduce you'll need to have attributes setup with a few terms, I have around 6 terms, let some products have all the terms and another product with only 2 or 3 of those terms from the same attribute. these products need to be variable, each with or without separate skus/pricing.

I requested get order with the api, this happens with get all orders in any status e.g. processing/completed and even if you request a single order by id the response is the same. 

API aside, you can actually see the results if you add those products to the cart then navigate to the basket, some show attributes next to it whilst others do not.

**Comment by kloon** [comment]
If the variation contains 3 or more attributes we do not include it in the title as it becomes too long. Have a look at the `generate_product_title` method to see the criteria.

**Comment by kloon** [comment]
It is possible that the product without the attribute in the name was set up in an older version of WooCommerce prior to the title change. Try the following, open the product that is missing the attribute from the title and then just resave it, it should then generate new titles.

**Comment by tmblog** [comment]
That didn't work. I can confirm that it wasn't set up in previous versions also that it's happening across multiple sites. Are you not able to replicate it?

**Comment by kloon** [comment]
Please go look at the function I posted about above, from there you will see all the criteria. We limit it for obvious reasons as to not have titles that are too long.

A comment from that function `// Do not include attributes if an attribute name has 2+ words and the` So that is the reason, the work Tika Masala matches the two or more rule and thus we do not include it.

**Comment by tmblog** [comment]
Hello Kloon I know very old issue but your last comment doesn't make sense especially if you look at my very first comment. 

> So that is the reason, the word Tika Masala matches the two or more rule and thus we do not include it.

This has two words so how come it was included?

`1x Rogan Josh - Lamb - 5.95
Dish: Lamb`

I'm just trying to figure out how to overcome it in php, because right now it doesn't seem to have a logical sequence. Cheers!
