### ISSUE TITLE
In Basket/Checkout rounding incorrect

### ISSUE THREAD

**Issue by JoeyXPOLE** [woocommerce/woocommerce#22196]
**Describe the bug**
In basket and at checkout, subtotal is rounding a £9.99 product to £10.00

**To Reproduce**
1. Select add prices exclusive of tax
2. Set woocommerce to display two decimals places on front end pricing
2. Add a product that costs £8.3250
3. Product displays as £9.99
4. Add to cart
5. When viewing in cart, line item shows as £9.99, but subtotal displays as £10.00

**Expected behavior**
Expected to see a subtotal of £9.99

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```

`
### WordPress Environment ###

Home URL: http://xpoleaxdev.wpengine.com
Site URL: http://xpoleaxdev.wpengine.com
WC Version: 3.5.2
Log Directory Writable: ✔
WP Version: ❌ 4.9.8 - There is a newer version of WordPress available (5.0)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.32-4+ubuntu18.04.1+deb.sury.org+1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.23-24-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 66.76MB
Database Data Size: 30.41MB
Database Index Size: 36.35MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.09MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_affiliate_wp_affiliatemeta: Data: 0.02MB + Index: 0.03MB
wp_affiliate_wp_affiliates: Data: 0.02MB + Index: 0.02MB
wp_affiliate_wp_campaigns: Data: 0.00MB + Index: 0.00MB
wp_affiliate_wp_creatives: Data: 0.02MB + Index: 0.02MB
wp_affiliate_wp_customermeta: Data: 0.02MB + Index: 0.03MB
wp_affiliate_wp_customers: Data: 0.02MB + Index: 0.03MB
wp_affiliate_wp_payouts: Data: 0.02MB + Index: 0.02MB
wp_affiliate_wp_referrals: Data: 0.02MB + Index: 0.02MB
wp_affiliate_wp_rest_consumers: Data: 0.02MB + Index: 0.02MB
wp_affiliate_wp_visits: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB
wp_gf_form: Data: 0.02MB + Index: 0.00MB
wp_gf_form_meta: Data: 0.03MB + Index: 0.00MB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB
wp_gf_form_view: Data: 0.05MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 2.31MB + Index: 0.13MB
wp_postmeta: Data: 14.52MB + Index: 21.08MB
wp_posts: Data: 1.52MB + Index: 0.44MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.03MB + Index: 0.00MB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wp_stream: Data: 2.52MB + Index: 2.48MB
wp_stream_meta: Data: 7.52MB + Index: 10.55MB
wp_termmeta: Data: 0.06MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.08MB + Index: 0.06MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_tinvwl_items: Data: 0.02MB + Index: 0.00MB
wp_tinvwl_lists: Data: 0.02MB + Index: 0.00MB
wp_usermeta: Data: 0.27MB + Index: 0.17MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wplc_chat_msgs: Data: 0.02MB + Index: 0.00MB
wp_wplc_chat_ratings: Data: 0.02MB + Index: 0.00MB
wp_wplc_chat_sessions: Data: 0.02MB + Index: 0.00MB
wp_wplc_chat_triggers: Data: 0.02MB + Index: 0.00MB
wp_wplc_custom_fields: Data: 0.02MB + Index: 0.00MB
wp_wplc_departments: Data: 0.02MB + Index: 0.00MB
wp_wplc_offline_messages: Data: 0.02MB + Index: 0.00MB
wp_wplc_roi_conversions: Data: 0.02MB + Index: 0.00MB
wp_wplc_roi_goals: Data: 0.02MB + Index: 0.00MB
wp_wplc_webhooks: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.17MB + Index: 0.00MB

### Post Type Counts ###

acf-field: 228
acf-field-group: 31
attachment: 464
client: 6
da_image: 3
faq: 88
nav_menu_item: 37
oembed_cache: 4
page: 53
post: 16
product: 350
product_variation: 436
revision: 3
shop_coupon: 1
shop_order: 32
testimonial: 4
woo_product_tab: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.5.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
x-stages and accessories (x-stages-and-accessories)


### WC Pages ###

Shop base: #122 - /shop/
Basket: #123 - /cart/
Checkout: #124 - /checkout/
My account: #125 - /my-account/
Terms and conditions: #1037 - /privacy-cookie-policy/

### Theme ###

Name: Twenty Seventeen
Version: 1.3 – 1.8 is available
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`

```
</details>

**Comment by JoeyXPOLE** [comment]
![screenshot 2018-12-11 at 16 57 52](https://user-images.githubusercontent.com/45796856/49816523-edec2300-fd65-11e8-8e01-80c181076947.png)

**Comment by mdmoore** [comment]
I can confirm this report.  The tax rate here is 20.0000%.  Here's the cart: 

![http://cld.wthms.co/pG1lnU](http://cld.wthms.co/pG1lnU+)
Full Image: http://cld.wthms.co/pG1lnU+

Tax should be $1.665.  **Round tax at subtotal level, instead of rounding per line** is unchecked.

**Comment by JoeyXPOLE** [comment]
Furthermore, with another product that features a .99 price (£19.99), the issue doesn’t occur and the subtotal displays correctly.

**Comment by kloon** [comment]
This is because you have a product price entered with 3 decimals. What happens when you shorten that price to two decimals?

**Comment by JoeyXPOLE** [comment]
Hi. 

When using two decimals, Woo rounds the product price to £10.00. 

The product is priced at £9.99 and must be displayed with the correct price.

**Comment by DavidAnderson684** [comment]
> The product is priced at £9.99 and must be displayed with the correct price.

In the screenshot given, the product *is* displayed with the price of £9.99. It's the sub-total that gets rounded. That's actually what HMRC (UK) guidance says should happen; after all line-item VAT has been added, you then round half-pennies up for the total VAT: https://www.gov.uk/hmrc-internal-manuals/vat-trader-records/vatrec12030

It's very counter-intuitive, of course; few customers will understand from the cart page how that works. You'd likely get what you want to see if you chose to enter prices inclusive of VAT.

**Comment by JoeyXPOLE** [comment]
Thanks David,

But as Woo should only be using two decimals, should it now come out to £9.99?

Forgive my ignorance on this matter, but all I want is to charge the customer the correct price.

**Comment by DavidAnderson684** [comment]
What is the "it" that you're particularly referring to at this point?

**Comment by JoeyXPOLE** [comment]
'It' being the basket subtotal; If I have a product priced at £9.99, and it's the only product in the basket, I need to the basket subtotal to show £9.99, not £10.00, as it's terribly confusing for customers.

**Comment by DavidAnderson684** [comment]
The basket subtotal is a penny higher because the VAT is rounded to the nearest penny which is actually legally correct in the UK; HMRC don't permit total VAT to be charged in fractions of a penny. So, if the line items total to a fraction of a penny, it has to be rounded.

**Comment by mikejolley** [comment]
David is correct. We cannot charge a fraction of tax, so it is rounded during totalling. The apparent lack of consistentcy is because sometimes it rounds up, sometimes it rounds down, sometimes there is no fraction. This is a math issue caused by prices at 3dp.

Various tax calculations are explained in https://github.com/woocommerce/woocommerce/wiki/How-Taxes-Work-in-WooCommerce

For your case (9.99 prices) you need to avoid using 3dp. With tax exclusive prices, getting 9.99 with your tax rate with just 2dp is mathmatically not possible, so you should consider switching to defining prices inclusive of tax. That way the 9.99 amount is fixed, and the tax amount is calculated backwards to make everything add up. 

cc @mdmoore

**Comment by JoeyXPOLE** [comment]
Hi @mikejolley 

Thanks for your comment, but it's a little crazy that we can't have £9.99 (or derivatives of .99 pricing) with prices exclusive of tax in WooCommerce.

I'm sure there are many users who work this way and need for the system to be able to display a product at checkout without adding another penny/cent to the price, which looks pretty suspicious to someone checking out.

**Comment by rrennick** [comment]
@JoeyXPOLE In a price includes tax (regardless of the tax rate) there are prices that cannot be calculated from a tax exclusive price. These prices occur when the tax switches from being rounded down to rounded up. In your example

8.32 x 1.20 = 9.98
8.33 x 1.20 = 10.00
