### ISSUE TITLE
Short free products checkout without billing 

### ISSUE THREAD

**Issue by MathiasPriebe** [woocommerce/woocommerce#22190]
**Is your feature request related to a problem? Please describe.**
Why shall one send or receive a bill for free products? We always wondered if it would be possible to just "Send" a free order instead of "Buy" it. 

**Describe the solution you'd like**
If we offer something for free we would like to checkout the user just like sending a form. 

**Describe alternatives you've considered**
We've considered certain Wordpress forms but obviously we would loose track of our affiliate referrals and could not handle the products within WooCommerce.

**Additional context**
Please compare it with a supermarket where something is offered for free in front. No one would send people all the way through the rows of shelves to the cashier, just to allow the free coke ;-) 
This request combined with One Page Checkout would make us buy it. 
Thank you in advance!

**Comment by kloon** [comment]
Most stores want that information for marketing purpose, you can unset billing fields via code snippets if you want. Have a look at this article https://www.skyverge.com/blog/how-to-simplify-free-woocommerce-checkout/

Combining that with a check if a free product is in your cart will give you what you want. So definitely doable already, but not a function of WooCommerce core and not one we will likely explore.

Thanks for the suggestion.
