### ISSUE TITLE
Promote the Facebook Integration in the Setup Wizard

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce#22198]
Copy: The official Facebook extension makes it easy to reach the people who matter to your business and track the results of your advertising across devices.

Target release: We need these changes to land in WC 3.5.3

p7bbVw-2Oa-p2

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22218

**Comment by allendav** [comment]
Why was this closed?
