### ISSUE TITLE
Export products by product category (arabic slug)

### ISSUE THREAD

**Issue by Ohadidy** [woocommerce/woocommerce#22197]
1. Create a product taxonomy (product_cat) in Arabic name and have a slug in Arabic.
2. Add products to this category (product_cat)
3. Go to export link of products in Woocommerce
4. Field option (In which category should be exported?) select Arabic category
5. Click Generate CSV
6. Open the csv file you will find empty

The problem is in the wc_clean function
wocommerce/includes/export/class-wc-product-csv-exporter.php line <del>78</del> 89
## WordPress Environment

<details>
`
### WordPress Environment ###
WC Version: 3.5.2
Log Directory Writable: ✔
WP Version: 5.0
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.14 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: 5.6.41-84.1
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.2
WC Database Prefix: dp5q_
MaxMind GeoIP Database: ✔
Total Database Size: 20.62MB
Database Data Size: 14.66MB
Database Index Size: 5.96MB
### Post Type Counts ###

attachment: 1452
custom_css: 1
nav_menu_item: 212
page: 54
post: 3
product: 328
product_variation: 75
revision: 88
shop_coupon: 1
shop_order: 13
static_block: 23
wpcf7_contact_form: 3

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.5.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: SAR ()
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
package (package)
product_pack (product_pack)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #3853 - /shop/
Cart: #4905 - /cart/
Checkout: #4906 - /checkout/
My account: #4907 - /my-account/
Terms and conditions: #5517 - /terms-and-conditions/

### Theme ###

Name: Twenty Nineteen
Version: 1.0
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

</details>

**Comment by claudiulodro** [comment]
Fixed in #22320 for WC 3.5.4
