### ISSUE TITLE
"Related products" does not respect Customizer setting...

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/woocommerce#22195]
**Describe the bug**
The "Related products" section does not respect the "Products per row" setting in the Customizer.

**To Reproduce**
1. Go to **Customizer** > **WooCommerce** > **Product Catalog** > **Products per row**
2. Choose four (or any number other than three).
3. On the front-end, go to any product that has "Related products"
4. Note there is always three "Related products" in the row.

**Expected behavior**
Like the rest of the shop, the "Related products" should respect the "Products per row" setting.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
The Storefront theme sets the related products to 3 - https://github.com/woocommerce/storefront/blob/master/inc/woocommerce/class-storefront-woocommerce.php#L187

**Comment by GlennMartin1** [comment]
@rrennick I will raise this issue with Storefront. Thanks for your help.

**Comment by GlennMartin1** [comment]
https://github.com/woocommerce/storefront/issues/1032
