### ISSUE TITLE
Wrong tax calculation

### ISSUE THREAD

**Issue by nemovich** [woocommerce/woocommerce#22194]
Hello dear Woo devs

I've spent a lot time looking for an answer anywhere I can but I don't seem to find one. I have my tax options set to price including tax and I sell to both categories of customers B2C and B2B. 
I know that woocommerce uses `tax_amount = price - ( price / ( ( tax_rate_% / 100 ) + 1 ) )`  to calculate the tax so not to "tax the tax". The problem is when a B2B transaction is involved, I have to remove the 21% tax for EU customers outside Belgium and the tax calculation becomes weird, here is an example:

Item cost inc 21% tax : 100€

At checkout the system displays : 82,64€ (ex. VAT) and VAT = 17,36€ ( which is right according to the formula)

Now when the EU customer provides the VAT number to be exempt from taxes (I'm using an automated VAT verification), the system removes 17,36€ and displays the total of 82.64€.

This does not seem right as the customer sees 100€, he is expecting to pay only 79€ at checkout (21€ off)

Am I missing something ?

Thank you very much

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently.

**WordPress Environment**
4.9
```
Woocommerce 3.3.0

**Comment by kloon** [comment]
What are you using for the VAT exemption? This seems like a bug in that code. We have an official WooCommerce extension that handles this fine and displays the correct totals for VAT exempt customers. https://woocommerce.com/products/eu-vat-number/

Also, you seem to be running a quite outdated version of WooCommerce, we are at 3.5.2 now which is a few versions ahead.

Personally, I do not see this as a WooCommerce core issue but an issue with your VAT integration, as mentioned the official extension works as expected to discount the price and totals correctly.

**Comment by nemovich** [comment]
I'm using the YITH WooCommerce EU VAT plugin but the problem occurs even when I disable all the plugins but Woocommerce, the tax calculation stays the same. I think the YITH plugin only removes the tax that the system already calculated so I don't think it's the culprit. 

I don't understand why the system needs to do so much gymnastics (formula) to  re-calculate the tax when it already knows it's included in the price, just make a simple calculation to display the price and tax separately at checkout ( at least that's how I see it : )  ).

 I just updated to Woocommerce 3.5.2 and still the same issue. you can probably reproduce this on your end with the "price including tax" option and your EU VAT number plugin.

Thank you

**Comment by kloon** [comment]
> you can probably reproduce this on your end with the "price including tax" option and your EU VAT number plugin

No, I can't, as mentioned our extensions does the calculations correctly. Try contacting the developer of your extensions for support as this is definitely an issue in the extension and not WooCommerce core.

**Comment by nemovich** [comment]
Ok so I tried with your official EU VAT plugin v2.3.11, I set my base to belgium with 21% standard rate and at checkout I give it a valid french VAT number and I choose France from the list, after that the system applies the exemption successfully but instead of giving a total of  79€ ( 21% off 100€ ), it displays 82,64€.
To make sure it's not my theme or wordpress installation, I've gone ahead and installed a fresh copy of Wordpress, Storefront, Woocommerce and the official EU VAT plugin, still the same problem.

here is the fresh installation if it helps : [http://www.wc.nemovich.odns.fr](url)

BTW, if I choose the option "prices exclusive of taxes" everything works fine but now I have to enter prices without taxes which is not ideal because I sell B2C as well. Even the prices including taxes at the front end will look funny ( e.g 149,99 + 21% = 181,48€ )

Thank you for your help
