### ISSUE TITLE
Webhook status update through the API using wrong sanitizing function.

### ISSUE THREAD

**Issue by claudiulodro** [woocommerce/woocommerce#22200]
When updating the status of a webhook through the API, the [sanitizing function defined in the schema](https://github.com/woocommerce/woocommerce/blob/e1255de71709d9e7cd8caa143c56fb4d60ab7101/includes/api/v2/class-wc-rest-webhooks-v2-controller.php#L115) is `wc_is_webhook_valid_topic`. This is not a good choice, since a webhook status will never ever be a valid webhook topic.

The sanitizing callback should be a new function `wc_is_webhook_valid_status`, and should check whether the status is valid using [wc_get_webhook_statuses](https://github.com/woocommerce/woocommerce/blob/b0b3ddccb0cf6964e2ff1c70b85dbd3b9764fa85/includes/wc-webhook-functions.php#L98). Unit tests would be nice too. :)

**Comment by claudiulodro** [comment]
cc @jessepearson

**Comment by kloon** [comment]
See #22205
