### ISSUE TITLE
i m getting issue with sale tag in woocommerce

### ISSUE THREAD

**Issue by shwetakatiyar31** [woocommerce/woocommerce#22207]
when i am wrtiting ?type=freeinstallation after any product URL its is converting sale tag to free installation
it is happening with my whole website. 

example
https://www.hardwoodgiant.ca/product/exotic-walnut-sanora
https://www.hardwoodgiant.ca/product/exotic-walnut-sanora?type=freeinstallation

**Comment by kloon** [comment]
Not able to reproduce this using Storefront or the Twentyseventeen theme. Most likely a conflict with your theme or another plugin. Please test as requested prior to open by disabling all plugins except WooCommerce and switching your theme to a default one like Storefront or Twentyseventeen to test.
