### ISSUE TITLE
API v3 - Retrieve Refund returns incorrect quantity for line item refund and Restock Refunded Items is unchecked

### ISSUE THREAD

**Issue by zfwjs** [woocommerce/woocommerce#22203]
**Describe the bug**
When retrieving a refund via the API the "line_items" -> "quantity" shows -1 regardless of whether the "Restock refunded items" checkbox is checked or not. This applies to line item refunds. With box checked, the item is restocked and the quantity returned by the API  is -1 in the refund. With the box unchecked, the item is not restocked and the quantity returned by the API is still -1. I do not see any other field that would indicate whether a restock had occurred as a result of the refund.  

**To Reproduce**

**When box is checked**
1. Create a manual order, item stock is decreased by 1
2. Refund the manual order by incrementing the line item box by 1 
3. Check the "Restock refunded items" checkbox, then complete the refund
4. Verify that a note appears referencing the restocking of the item; also verify item was restocked
4. Retrieve the refund via the API using /wp-json/wc/v3/orders/<order-id>/refunds

Returns:
```
  {
    "id": 13004,
    "date_created": "2018-12-11T21:38:09",
    "date_created_gmt": "2018-12-12T03:38:09",
    "amount": "34.00",
    "reason": "",
    "refunded_by": 1,
    "refunded_payment": false,
    "meta_data": [],
    "line_items": [
      {
        "id": 6039,
        "name": "Product Name",
        "product_id": 10113,
        "variation_id": 0,
        "quantity": -1,
        "tax_class": "",
        "subtotal": "-32.00",
        "subtotal_tax": "-2.00",
        "total": "-32.00",
        "total_tax": "-2.00",
        "taxes": [
          {
            "id": 1,
            "total": "-2",
            "subtotal": "-2"
          }
        ],
```

**When box is UN-checked**
1. Create a manual order, item stock is decreased by 1
2. Refund the manual order by incrementing the line item box by 1 
3. Un-check the "Restock refunded items" checkbox, then complete the refund
4. Verify that a note does not appear referencing the restocking of the item; also verify item was not restocked
4. Retrieve the refund via the API using /wp-json/wc/v3/orders/<order-id>/refunds

Returns:
```
  {
    "id": 12993,
    "date_created": "2018-12-11T21:35:50",
    "date_created_gmt": "2018-12-12T03:35:50",
    "amount": "34.00",
    "reason": "",
    "refunded_by": 1,
    "refunded_payment": false,
    "meta_data": [],
    "line_items": [
      {
        "id": 6035,
        "name": "Product Name",
        "product_id": 10113,
        "variation_id": 0,
        "quantity": -1,
        "tax_class": "",
        "subtotal": "-32.00",
        "subtotal_tax": "-2.00",
        "total": "-32.00",
        "total_tax": "-2.00",
        "taxes": [
          {
            "id": 1,
            "total": "-2",
            "subtotal": "-2"
          }
        ],

```
**Screenshots**

**Expected behavior**
Quantity returned by /refunds endpoint should show 0 for items not restocked, or there should be an additional field indicating the item was not restocked ('restocked": "false")

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details open>

WC Version: 3.5.2
Log Directory Writable: ✔
WP Version: 5.0
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.0.32-0ubuntu0.16.04.1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.24-0ubuntu0.16.04.1
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

**Comment by kloon** [comment]
The refund line_items qty does not represent the actual stock in your store. All that means is that one item has been refunded, ie the full item. If you do a partial refund, ie only refunding part of the price of an item, the qty field should not be -1.

Stock tracking happens on the products and not on orders or refunds. The product stock quantity is updated as order and refunds happen, if you have the restock option enabled and then do a full item refund the qty field on the *product* will increase, if you do not have it checked it will not increase.

**Comment by stevenbrookes** [comment]
@kloon  I think you've misunderstood the problem.  This is about the number of items to be restocked based on the refund and is affected by the restock flag in the admin UI.  I believe there needs to be an extra flag on the API call response to indicate whether the item(s) should be returned to stock or not.
