### ISSUE TITLE
H2 headings on product pages are too small with Twenty Nineteen

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce#22211]
**Describe the bug**
H2 headings on product pages are too small with Twenty Nineteen

**To Reproduce**
1. Create a test product and add `<h2>` header to the description
2. You'll see that `<h2>` smaller than `<h3>` because of this CSS property: 

```
.woocommerce-tabs .panel h2 {
font-size: 1em;
}
```

![http://cld.wthms.co/k0PEzq](http://cld.wthms.co/k0PEzq+) 
Full Size: http://cld.wthms.co/k0PEzq

With Storefront, it's `2em`:

![http://cld.wthms.co/W1zfDV](http://cld.wthms.co/W1zfDV+) 
Full Size: http://cld.wthms.co/W1zfDV

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by faisal-alvi** [comment]
Here is the [PR](https://github.com/woocommerce/woocommerce/pull/22223)

**Comment by faisal-alvi** [comment]
#22223

**Comment by tiagonoronha** [comment]
https://github.com/woocommerce/woocommerce/pull/22225
