### ISSUE TITLE
fix: warning generate when settings pages are not available

### ISSUE THREAD

**Issue by jitendrabanjara1991** [woocommerce/woocommerce#22210]
**Describe the bug**
When I install any WooCommerce Add-on then it generates Warning if WC settings page is not available.

**To Reproduce**
1. Install `Advance Ecommerce Tracking` WooCommerce add-on
2. Goto cart page from front-side.
3. Click on `edit page` link that is available in admin menu
4. See Warning `Warning: Invalid argument supplied for foreach() in path/wp-content/plugins/woocommerce/includes/class-wc-api.php on line 367`

**Screenshots**
![cart-error](https://user-images.githubusercontent.com/30429982/49931359-b360c280-feec-11e8-8f63-420ecc2c8a92.png)

**Expected behavior**
I expect not to display that warning in cart page of admin-area.

**Isolating the problem:**
- [ ] `Warning` should not display when WooCommerce add-on is activated and settings pages are not available.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: http://localhost/projects/pro_plugin_support
Site URL: http://localhost/projects/pro_plugin_support
WC Version: 3.5.2
Log Directory Writable: ✔
WP Version: 5.0.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.23 (Win64) PHP/7.0.10
PHP Version: 7.0.10 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.50.1
OpenSSL/1.0.2h

SUHOSIN Installed: –
MySQL Version: 5.7.14
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.2
WC Database Prefix: wp_
Total Database Size: 1.12MB
Database Data Size: 0.93MB
Database Index Size: 0.19MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.01MB
wp_comments: Data: 0.00MB + Index: 0.01MB
wp_import_excel_state_tbl: Data: 0.00MB + Index: 0.00MB
wp_import_excel_zipcode_tbl: Data: 0.00MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_menu_manager_plus: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 0.72MB + Index: 0.04MB
wp_postmeta: Data: 0.13MB + Index: 0.06MB
wp_posts: Data: 0.03MB + Index: 0.02MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.00MB + Index: 0.01MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_usermeta: Data: 0.01MB + Index: 0.01MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wcextraflatrate_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_wcextraflatrate_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_wcextraflatrate_user_zone: Data: 0.00MB + Index: 0.00MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_wpfp_questions: Data: 0.00MB + Index: 0.00MB
wp_wpfp_questions_options: Data: 0.00MB + Index: 0.00MB
wp_wpfp_wizard: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 23
page: 7
post: 2
product: 21
product_variation: 7
revision: 1
wc_afrsm: 13
wc_conditional_fee: 7

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (9) ###

Advance Ecommerce Tracking: by Multidots – 1.4.3 – Not tested with the active version of WooCommerce
Advanced Flat Rate Shipping For WooCommerce Pro: by Multidots – 3.1.1 – Not tested with the active version of WooCommerce
WooCommerce Blocks: by Automattic – 1.2.0
WooCommerce Product Attachment Pro: by multidots – 1.1 – Not tested with the active version of WooCommerce
WooCommerce Product Finder Pro: by Multidots – 1.0.8 – Not tested with the active version of WooCommerce
WooCommerce Conditional Product Fees for Checkout Pro: by Multidots – 1.3.2 – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.5
WooCommerce Services: by Automattic – 1.18.0
WooCommerce: by Automattic – 3.5.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page visibility should be public

### Theme ###

Name: Twenty Nineteen
Version: 1.0
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by rrennick** [comment]
Which other extensions did you install?

**Comment by rrennick** [comment]
> When I install any WooCommerce Add-on 

If the only extension you have installed is Enhanced Ecommerce Tracking WooCommerce then you can ask about the warning at https://wordpress.org/support/plugin/enhanced-e-commerce-for-woocommerce-store.

**Comment by rrennick** [comment]
Closing this as it doesn't appear to be an issue with WC.
