### ISSUE TITLE
REST API - How to add/pass taxes in create order API?

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [woocommerce/woocommerce#22215]

**Comment by rodrigoprimo** [comment]
I'm sorry, but we don't use GitHub issues for support, we use it exclusively for WooCommerce bugs, enhancements and feature requests. If you need support, you could try WooCommerce support forums on WordPress.org (https://wordpress.org/support/plugin/woocommerce) or, if you are a WooCommerce.com paying customer, please contact their support (https://woocommerce.com/my-account/create-a-ticket/).
