### ISSUE TITLE
The button to reduce or increase stock is gone? How do I get it back.

### ISSUE THREAD

**Issue by Anarchrist** [woocommerce/woocommerce#22217]
So for manual orders, I used to be able to click the order and some buttons would slide out to increase/decrease stock levels. I updated WooCom and this feature is gone. Is this normal? Was it intentionally removed?? I have disabled all plugins to test and swapped the theme to default and it is still not working.

If this is part of the update my questions are:
Why was this removed?

What is the new process?

Is there a plugin to bring this feature back?

**To Reproduce**
1. Go to orders
2. Click on new order
3. Scroll down to products and add one, click on newly added product
4. buttons dont show :(

**Screenshots**
![image](https://user-images.githubusercontent.com/20581408/49959743-5a058d00-ff06-11e8-97f8-3ca6353b9a93.png)

WooCommerce 3.5

**Comment by rrennick** [comment]
Please don't create duplicate issues. https://github.com/woocommerce/woocommerce/issues/21754#issuecomment-447066898

The PR for #21754 is scheduled to be added to WC 3.5.3.
