### ISSUE TITLE
Return Product of any types

### ISSUE THREAD

**Issue by Tekrajs** [woocommerce/woocommerce#22220]
Now, wither we need to provide the product type as type that we want to get or it is provided as 'simple','variable','grouped' or ,'external' by default. 
Can we make wc_get_product($args) return product even when there is no product_type, for all post having post_type as 'product' ?
Why is it compulsory to define a product's type ? If no type is selected simply distinguished it as simple.

Again if woo-commerce provides only 4 types and if I add custom product_type as 'abc',for those imported products which doesn't have product_type, and ask wc_get_product($args) to fetch the product as :

                 $args = array(
                  'limit' => -1,
                  'status' => 'publish',
                  'type' => array('abc'),
                  'category' => array('hoodies'),
                );
             
                $products = wc_get_products($args);
                echo "<pre>";
                print_r(($products));
                echo "</pre>";
                exit();
It returns product with type abc as simple product.
Does this make any sense ?

**Comment by kloon** [comment]
A product has to have a type. Why create a new product type and then not do anything with it? In that case, you can just assign the types as simple to the product.

Also there is no need to specify the type when you query products using wc_get_products, it will revert to including all product types when you omit that argument. As long as your new product type is registered correctly it will get included in that query. To register your product type use the product_type_selector filter.

**Comment by Tekrajs** [comment]
But why can't wc_get_product simply return all post with post_type product even if product_type is not assigned for that product ?
