### ISSUE TITLE
Rest API: Sale Price on orders

### ISSUE THREAD

**Issue by fahaadsheikh** [woocommerce/woocommerce#22224]
**Is your feature request related to a problem? Please describe.**
When requesting orders through the REST API withing the line items we have the price attribute only. Not the sale_price attribute. There is no way of actually knowing how much off did a user get when the product was on sale.

**Describe the solution you'd like**
Within `line_items` there should be an attribute by the name `sale_price` and `price` should always be the regular price

**Comment by rrennick** [comment]
The `price` on the order is the price paid by the customer. Store managers can change the price of any product to any amount on an order prior to the order being paid so there is no direct relation between the price on the order & the product prices. 

If you need the 2 prices on the product then you'll need to retrieve those through a second api call.

**Comment by fahaadsheikh** [comment]
@rrennick 
If a product was sold on a sale price but not on a regular price. Shouldn't the sale price be shown within `line_items` in the orders?

**Comment by rrennick** [comment]
Sale price is an attribute of the product vs an attribute of the order. The price on the order is a calculated amount which sometimes coincides with either the regular or sale price of the product. 

If I were going to add the product prices to the order in the api then I would want the naming would reflect that: `product_sale_price`, `product_price`, `price` (that actual price paid for the item(s). The second decision that would need to be made is whether the product prices were the prices at the time the order was paid or the current prices of the product.
