### ISSUE TITLE
Checkout: error on Fields Order - bug at address-i18n.js

### ISSUE THREAD

**Issue by renatonagliati** [woocommerce/woocommerce#22227]
**Describe the bug**
On checkout page: if you reorder checkout fields using sequences as 1,2,3,4...7,8... when you change the Country field, the "country_to_state_changing" is triggered and the rows.sort occurs incorrectly.

Reason: in lines 117 and 118 of address-i18n.js it is necessary to transform the "priority" attribute into integer - parseInt(). As this is not done, the script understands that "7" is greater than "10", for example.

**To Reproduce**
1. Go to checkout page;
2. Change the Country;
3. See error: the layout will be broke;
PS.: this occurs only when the priorities of checkout fields is changed by another theme or plugin using sequences as 1,2,3,4,5. If uses 10, 20, 30, 40 the error not occurs.

**Screenshots**
N/A

**Expected behavior**
The fields order must be maintained.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://wordpressexpress.com.br/matrizdamente
Site URL: https://wordpressexpress.com.br/matrizdamente
WC Version: 3.5.2
Log Directory Writable: ✔
WP Version: ❌ 4.9.9 - Há uma nova versão do WordPress disponível (5.0.1)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: pt_BR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.30 - Nós recomendamos o uso do PHP versão 7.2 ou superior para maior performance e segurança. Como atualizar a versão do seu PHP
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: 5.6.41-84.1
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Tamanho total do banco de dados: 1.39MB
Tamanho dos dados do banco de dados: 1.22MB
Tamanho do índice do banco de dado: 0.17MB
wp_woocommerce_sessions: Dados: 0.01MB + Índices: 0.00MB
wp_woocommerce_api_keys: Dados: 0.00MB + Índices: 0.00MB
wp_woocommerce_attribute_taxonomies: Dados: 0.00MB + Índices: 0.00MB
wp_woocommerce_downloadable_product_permissions: Dados: 0.00MB + Índices: 0.00MB
wp_woocommerce_order_items: Dados: 0.00MB + Índices: 0.00MB
wp_woocommerce_order_itemmeta: Dados: 0.00MB + Índices: 0.00MB
wp_woocommerce_tax_rates: Dados: 0.00MB + Índices: 0.00MB
wp_woocommerce_tax_rate_locations: Dados: 0.00MB + Índices: 0.00MB
wp_woocommerce_shipping_zones: Dados: 0.00MB + Índices: 0.00MB
wp_woocommerce_shipping_zone_locations: Dados: 0.00MB + Índices: 0.00MB
wp_woocommerce_shipping_zone_methods: Dados: 0.00MB + Índices: 0.00MB
wp_woocommerce_payment_tokens: Dados: 0.00MB + Índices: 0.00MB
wp_woocommerce_payment_tokenmeta: Dados: 0.00MB + Índices: 0.00MB
wp_woocommerce_log: Dados: 0.00MB + Índices: 0.00MB
wp_commentmeta: Dados: 0.00MB + Índices: 0.00MB
wp_comments: Dados: 0.01MB + Índices: 0.01MB
wp_correios_postcodes: Dados: 0.00MB + Índices: 0.00MB
wp_links: Dados: 0.00MB + Índices: 0.00MB
wp_nextend2_image_storage: Dados: 0.00MB + Índices: 0.00MB
wp_nextend2_section_storage: Dados: 0.05MB + Índices: 0.01MB
wp_nextend2_smartslider3_generators: Dados: 0.00MB + Índices: 0.00MB
wp_nextend2_smartslider3_sliders: Dados: 0.02MB + Índices: 0.00MB
wp_nextend2_smartslider3_sliders_xref: Dados: 0.00MB + Índices: 0.00MB
wp_nextend2_smartslider3_slides: Dados: 0.04MB + Índices: 0.00MB
wp_options: Dados: 0.95MB + Índices: 0.04MB
wp_postmeta: Dados: 0.04MB + Índices: 0.03MB
wp_posts: Dados: 0.06MB + Índices: 0.03MB
wp_sysmatriz_combinacoes_possiveis_grupos: Dados: 0.00MB + Índices: 0.00MB
wp_sysmatriz_execucao_cronograma: Dados: 0.01MB + Índices: 0.00MB
wp_sysmatriz_execucao_planos_acao: Dados: 0.00MB + Índices: 0.00MB
wp_sysmatriz_matriz: Dados: 0.01MB + Índices: 0.00MB
wp_sysmatriz_modulos: Dados: 0.00MB + Índices: 0.00MB
wp_sysmatriz_notas_questionario: Dados: 0.00MB + Índices: 0.00MB
wp_sysmatriz_notificacoes: Dados: 0.00MB + Índices: 0.00MB
wp_sysmatriz_planos_acao: Dados: 0.01MB + Índices: 0.00MB
wp_sysmatriz_questionario: Dados: 0.00MB + Índices: 0.00MB
wp_sysmatriz_resultado_questionario: Dados: 0.00MB + Índices: 0.00MB
wp_sysmatriz_saudes: Dados: 0.00MB + Índices: 0.00MB
wp_termmeta: Dados: 0.00MB + Índices: 0.01MB
wp_terms: Dados: 0.00MB + Índices: 0.01MB
wp_term_relationships: Dados: 0.00MB + Índices: 0.00MB
wp_term_taxonomy: Dados: 0.00MB + Índices: 0.00MB
wp_usermeta: Dados: 0.01MB + Índices: 0.02MB
wp_users: Dados: 0.00MB + Índices: 0.01MB
wp_wc_download_log: Dados: 0.00MB + Índices: 0.00MB
wp_wc_webhooks: Dados: 0.00MB + Índices: 0.00MB

### Post Type Counts ###

acf-field: 7
acf-field-group: 3
attachment: 12
customize_changeset: 5
depoimento: 5
nav_menu_item: 12
page: 19
post: 12
product: 3
revision: 76
shop_coupon: 2
shop_order: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

Duplicate Post: por Enrico Battocchi – 3.2.2
Smart Slider 3: por Nextend – 3.3.11
WooCommerce Correios: por Claudio Sanches – 3.7.1 – Não testado com a versão ativa do WooCommerce
WooCommerce Extra Checkout Fields for Brazil: por Claudio Sanches – 3.6.1 – Não testado com a versão ativa do WooCommerce
WooCommerce PagSeguro: por Claudio Sanches – 2.13.1 – Não testado com a versão ativa do WooCommerce
WooCommerce: por Automattic – 3.5.2
WP Crontrol: por John Blackbourn & colaboradores – 1.6.2
Sistema Matriz (WordPressExpress): por Renato Nagliati – 1.0
WPForms Lite: por WPForms – 1.5.0.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: BRL (R$)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Base da loja: #23 - /loja/
Carrinho: #24 - /carrinho/
Finalizar compra: #25 - /finalizar-compra/
Minha conta: #26 - /minha-conta/
Termos e condições: ❌ Página não definida

### Theme ###

Name: WordPressExpress Matriz da Mente
Version: 1.0
Author URL: http://wordpressexpress.com.br/
Child Theme: ❌ – Recomendamos você utilizar um tema filho no caso de você estiver personalizando o WooCommerce em um tema ascendente. Veja como criar um tema filho
WooCommerce Support: ✔

### Templates ###

Overrides: wpexp_tema_matrizdamente/woocommerce/checkout/form-checkout.php
wpexp_tema_matrizdamente/woocommerce/checkout/form-coupon.php
wpexp_tema_matrizdamente/woocommerce/checkout/payment.php
wpexp_tema_matrizdamente/woocommerce/checkout/thankyou.php

`
</details>

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/22444
