### ISSUE TITLE
wc_product_attribute()->get_name() return int or string?

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [woocommerce/woocommerce#22234]
**Describe the bug**
I think **get_name()** method of **wc_product_attribute** class return String instead Int.

**Expected behavior**
This method was return String but in documents and source code return type of this method is Int.

[Link of line in the file](https://github.com/woocommerce/woocommerce/blob/f13a0bc9eb49dad87b93e5b3ac019838e43b1404/includes/class-wc-product-attribute.php#L232)

**Comment by faisal-alvi** [comment]
#22244
