### ISSUE TITLE
OBW: Avoid case of required shipping method input on disabled zone

### ISSUE THREAD

**Issue by dechov** [woocommerce/woocommerce#22232]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

In the onboarding wizard's "Shipping" step, disable a shipping zone, then switch the shipping method from "Free shipping" to "Flat rate", then try to "Continue" – browsers supporting HTML5 validation will prevent it. Tested with Chrome.

<img width="664" alt="screen shot 2018-12-14 at 4 52 17 pm" src="https://user-images.githubusercontent.com/1867547/50029414-a6ad9e80-ffc0-11e8-86ff-6c5e26ba5f65.png">

This is the code that sets the `required` property on this input: https://github.com/woocommerce/woocommerce/blob/f13a0bc9eb49dad87b93e5b3ac019838e43b1404/assets/js/admin/wc-setup.js#L104-L108

## Expected/actual behavior

Expected either:
- disabling the method dropdown when the zone is disabled,
- enabling the zone when the method dropdown changes, or
- only setting the "required" field to required if the zone is enabled

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by rrennick** [comment]
@dechov Can you provide more details on reproducing this issue?

**Comment by rrennick** [comment]
@dechov Thanks, I was able to reproduce the issue.
