### ISSUE TITLE
[Question] Running 3.6.0-dev but getting 3.5.0 in status report

### ISSUE THREAD

**Issue by willgorham** [woocommerce/woocommerce#22231]
I'm running the latest 3.6.0-dev master branch, and on the Plugins screen the 3.6.0-dev version appears correctly. However, the status report is showing 3.5.0 (and database version 3.5.0). I'm just looking for clarification if this is normal due to the repo branching structure, or an actual code issue. Thanks!

<details>
<summary>Status report for example:</summary>
`
### WordPress Environment ###

Home URL: https://woocommerce-master.test
Site URL: https://woocommerce-master.test
WC Version: 3.5.0
Log Directory Writable: ✔
WP Version: 5.0.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.15.5
PHP Version: 7.2.11
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
LibreSSL/2.6.4

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.10-MariaDB
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.0
WC Database Prefix: wp_
Total Database Size: 3.92MB
Database Data Size: 2.87MB
Database Index Size: 1.05MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.05MB + Index: 0.05MB
wp_postmeta: Data: 0.23MB + Index: 0.14MB
wp_posts: Data: 0.05MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB

### Post Type Counts ###

attachment: 47
customize_changeset: 1
nav_menu_item: 1
page: 7
post: 2
product: 18
product_variation: 7
revision: 6
shop_coupon: 2
shop_order: 2
shop_order_refund: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

User Switching: by John Blackbourn & contributors – 1.4.0
WooCommerce Blocks: by Automattic – 1.2.0
WooCommerce: by Automattic – 3.6.0-dev

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #71 - /shop/
Cart: #72 - /cart/
Checkout: #73 - /checkout/
My account: #74 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.4.2
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by rrennick** [comment]
> if this version isn't bumped then database update routines on patch releases aren't triggered in master, right?

Yes. There may be more DB updates in upcoming changes so bumping the DB version is left to as late as possible in the dev cycle. In this case there is an upcoming 3.5.3 milestone so we definitely wouldn't want the DB version to be changed to 3.6.0 prior to any 3.5.X release.

**Comment by willgorham** [comment]
This seems like it might cause minor unexpected issues testing the master branch, if spinning up a master branch dev site doesn't force the latest/patch database updates? What about bumping the version to the latest patch release? I trust you guys know what you're doing, I'm honestly just curious here. Thanks again for the explanation.

**Comment by rodrigoprimo** [comment]
Thanks for bringing this up, @willgorham. So far we bumped the WC version in `class-woocommerce.php` whenever we add the first database update routine to the next minor release (examples: 77b73e05c84a9b3b1268e1a3ea1a595310edfa8f and 245e1768f9674391a2deb5b2b44943e515a8eb98). I think this is not ideal as often, when creating the first database update routine, we lose time trying to understand why it is not running just to realize that the problem is the WC version.

I suggest we start bumping the WC version in class-woocommerce.php together with the readme.txt version and the woocommerce.php (PR #21755 bumped versions when WC 3.5 was released) right after a new minor or major release. cc @woocommerce/proton for your input on this.

>  In this case there is an upcoming 3.5.3 milestone so we definitely wouldn't want the DB version to be changed to 3.6.0 prior to any 3.5.X release.

I believe @willgorham is referring to the version in the master branch and the 3.5.x releases are created from the releases/3.5 branch, so this is not an issue (for patch releases we cherry-pick commits from master to the release branch).

**Comment by claudiulodro** [comment]
Historically we've updated the version when development for the next version begins, which makes sense since we don't want the version in the master branch to be 3.6 if 3.6 is not in the works.

We should update the version in `class-woocommerce.php` since development on 3.6 has begun. Thanks for the heads up.

**Comment by claudiulodro** [comment]
https://github.com/woocommerce/woocommerce/commit/3c3894b676f3112db1474a9749f084011eae46d9
