### ISSUE TITLE
Can't Upload File Woocommerce

### ISSUE THREAD

**Issue by 987654321MNBVCXZ** [woocommerce/woocommerce#22233]
Help Me Please

![image](https://user-images.githubusercontent.com/45889208/50038299-ebcce180-004f-11e9-95a0-57149259941c.png)

How to Fix it ?

**Comment by Ohadidy** [comment]
this error from WordPress v 5.0.1 core, not woocommerce...
I created a ticket about this issue https://core.trac.wordpress.org/ticket/45655

**Comment by 987654321MNBVCXZ** [comment]
Hello

I MEAN IMPORT , NOT EXPORT, AND I DO NOT UNDERSTAND WHY ITS HAPPEN

Pada tanggal Sab, 15 Des 2018 pukul 11.30 Omar Hadidy <
notifications@github.com> menulis:

**Comment by jaapalberts** [comment]
![dummydata](https://user-images.githubusercontent.com/45895879/50042569-078eb280-0065-11e9-8757-e18cd7ad9ef5.png)

Same problem here. Want to import the dummy data.csv from wordpress, i get an error message. Please help

**Comment by claudiulodro** [comment]
More info and workarounds in https://github.com/woocommerce/woocommerce/issues/22208.
