### ISSUE TITLE
Shipping Zones are not loading and saving

### ISSUE THREAD

**Issue by Lucas8407** [woocommerce/woocommerce#22242]
When i click on add a new shipping zone, i try to add a shipping method, but when i click to add a shipping method, load for like 4 seconds and nothing happens and also i can´t save the changes. What should i do? I ve alrealdy tried to desactivate all the plugins and to re activate the woocomerce, but it didn´t work. It s similiar to this problem: https://github.com/woocommerce/woocommerce/issues/11912#issue-176634818. Thank you.

**SYSTEM STATUS REPORT**
### WordPress Environment ###

Home URL: http://demdecoracoes.com.br/dem
Site URL: http://demdecoracoes.com.br/dem
WC Version: 3.5.2
Log Directory Writable: ✔
WP Version: ❌ 4.9.9 - There is a newer version of WordPress available (5.0.1)
WP Multisite: –
WP Memory Limit: ❌ 13 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.10 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 240
PHP Max Input Vars: 10000
cURL Version: 7.19.7
NSS/3.21 Basic ECC

SUHOSIN Installed: ✔
MySQL Version: ❌ 5.5.43-log - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 7.19MB
Database Data Size: 6.26MB
Database Index Size: 0.93MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_comments: Data: 0.04MB + Index: 0.01MB
wp_easy_pie_contacts: Data: 0.02MB + Index: 0.02MB
wp_easy_pie_cs_entities: Data: 0.02MB + Index: 0.00MB
wp_easy_pie_cs_subscribers: Data: 0.02MB + Index: 0.00MB
wp_easy_pie_emails: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 0.77MB + Index: 0.19MB
wp_pagseguro_wp_ecommerce_shopping_cart: Data: 0.00MB + Index: 0.00MB
wp_postmeta: Data: 3.98MB + Index: 0.22MB
wp_posts: Data: 1.14MB + Index: 0.18MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.00MB + Index: 0.01MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.01MB
wp_usermeta: Data: 0.01MB + Index: 0.01MB
wp_users: Data: 0.00MB + Index: 0.02MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wpsc_also_bought: Data: 0.00MB + Index: 0.00MB
wp_wpsc_cart_contents: Data: 0.00MB + Index: 0.00MB
wp_wpsc_checkout_forms: Data: 0.00MB + Index: 0.00MB
wp_wpsc_claimed_stock: Data: 0.00MB + Index: 0.00MB
wp_wpsc_coupon_codes: Data: 0.00MB + Index: 0.00MB
wp_wpsc_currency_list: Data: 0.02MB + Index: 0.01MB
wp_wpsc_download_status: Data: 0.00MB + Index: 0.00MB
wp_wpsc_meta: Data: 0.00MB + Index: 0.01MB
wp_wpsc_product_rating: Data: 0.00MB + Index: 0.00MB
wp_wpsc_purchase_logs: Data: 0.00MB + Index: 0.00MB
wp_wpsc_region_tax: Data: 0.00MB + Index: 0.00MB
wp_wpsc_submited_form_data: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 668
custom_css: 1
customize_changeset: 52
elementor_library: 5
nav_menu_item: 26
page: 15
post: 10
product: 11
product_variation: 28
revision: 404
wpcf7_contact_form: 1
wpsc-product: 15

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (8) ###

Autoptimize: by Frank Goossens (futtta) – 2.4.1
Contact Form 7: by Takayuki Miyoshi – 5.0.5
Custom Fonts: by Brainstorm Force – 1.0.5
Elementor: by Elementor.com – 2.2.7
Ocean Extra: by OceanWP – 1.4.29
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.15.2

Use Any Font: by Dinesh Karki – 5.0
WooCommerce: by Automattic – 3.5.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: BRL (R$)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #2757 - /loja/
Cart: #2759 - /carrinho/
Checkout: #2761 - /finalizar-compra/
My account: #2763 - /minha-conta/
Terms and conditions: ❌ Page not set

### Theme ###

Name: OceanWP
Version: 1.5.30 – 1.5.32 is available
Author URL: https://oceanwp.org/about-me/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: oceanwp/woocommerce/cart/mini-cart.php
oceanwp/woocommerce/content-single-product.php
oceanwp/woocommerce/loop/loop-start.php
oceanwp/woocommerce/single-product/title.php

`

**Comment by rrennick** [comment]
> WP Memory Limit: ❌ 13 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP

You need to contact your hosting support.
