### ISSUE TITLE
Why images from product-gallery is not display all sizes?

### ISSUE THREAD

**Issue by Steffi3rd** [woocommerce/woocommerce#22240]
In my single page product, i have 2 images (one main image and one from product gallery)
which are both link to the same real url.

I noticed that images from product gallery are blurry. I checked the source code, the code is not the same.

Code generated from product images doesn't have `srcset` etc...

Why? How to fix that please?

![s](https://user-images.githubusercontent.com/814410/50055517-7ac12300-0150-11e9-8ea0-6a2f87ef3165.jpg)

**Comment by rrennick** [comment]
Can you provide download URLs for the 2 images?

**Comment by Steffi3rd** [comment]
> Can you provide download URLs for the 2 images?

There is only one image, but used twice by different way. The first is the `main` image, and the second image is from `image gallery`

That's why I ask why the code not generated the code with `srcset`

**Comment by rrennick** [comment]
Thanks for the  clarification. Can you provide a URL for the image?

**Comment by mikejolley** [comment]
The images without srcset look to be dynamically generated by whatever slider/zoom plugin is active. This is theme dependent.
