### ISSUE TITLE
The character encoding of the plain text document was not declared. ( Product Pages )

### ISSUE THREAD

**Issue by WolvesInChains** [woocommerce/woocommerce#22259]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by WolvesInChains** [comment]
On the Firefox debuger shows this message when you are inside woocomerce single products " 

The character encoding of the plain text document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the file needs to be declared in the transfer protocol or file needs to use a byte order mark as an encoding signature. " 


I have tested with a couple of themes , and it happens with the most of them , but not with all .

**Comment by rodrigoprimo** [comment]
@WolvesInChains, does this happen with Storefront or one of the official WordPress themes (like Twenty Nineteen for example)?

**Comment by mikejolley** [comment]
I'm not seeing any such warning in firebug console on a product page. Without more details, I don't think this is a problem we can resolve nor do I think it would be a WC specific issue because WC controls the page content, not the HEAD section of the page etc.
