### ISSUE TITLE
Force shipping address On Virtual Product Orders

### ISSUE THREAD

**Issue by OccamsGilette** [woocommerce/woocommerce#22256]
I have physical gift cards that get mailed out via Woocommerce. So I built a virtual product which solved the free shipping/no taxes and then forced the "shipping" field to be available on checkout by adding this code to functions.php

add_filter( 'woocommerce_cart_needs_shipping_address', '__return_true', 50 );

The problem is that when printing the invoice/delivery note the shipping field is not shown, only the billing address. Is there a way to again force that to show up for virtual product based invoices?

**Comment by rodrigoprimo** [comment]
I'm sorry, but we don't use GitHub issues for support, we use it exclusively for WooCommerce bugs, enhancements and feature requests. If you need support, you could try WooCommerce support forums on WordPress.org (https://wordpress.org/support/plugin/woocommerce) or, if you are a WooCommerce.com paying customer, please contact their support (https://woocommerce.com/my-account/create-a-ticket/).
