### ISSUE TITLE
`updateCartPage()` makes two ajax get requests to the same URL, could be changed to be only one request

### ISSUE THREAD

**Issue by bonny** [woocommerce/woocommerce#22260]
**Is your feature request related to a problem? Please describe.**

If the JS action `added_to_cart` is triggered on the cart page then the JS function `AddToCartHandler.prototype.updateCartPage()` is called and two ajax requests are performed to fetch new content. 

The first request is to update the cart contents table and the second request is to update the cart totals table. Both requests are performed to the same URL, so I believe that this is one ajax request to many. It should be able to solve this with only one request.

**Describe the solution you'd like**

Do a check to see if `.shop_table.cart` or `.cart_totals` exists on the page and if then make one ajax call to get new content and update one or both of the tables. This way the tables are updated faster and there is less work for the server to perform.

**Additional context**

This is how how I triggered `added_to_cart`  btw:
`$( document ).trigger('added_to_cart')`

**Comment by rrennick** [comment]
Content can be added between the shop table & cart totals by custom templates in the theme of by an extension. Reducing the 2 calls to one would remove that added content from the page.

**Comment by bonny** [comment]
Yes, I didn't mean that all content should be overwritten by a single Ajax request. I think there could be one request that after the request is done updates the two tables separately.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22629
