### ISSUE TITLE
401 unauthorized in Postman on `read_private_posts` permission

### ISSUE THREAD

**Issue by cgsmith** [woocommerce/woocommerce#22262]
**Describe the bug**
I receive the frequent 401 unauth response on the API. This one has me stumped and seems different though. It fails the permission check for `read_private_posts` or so it seems.

```
{
    "code": "woocommerce_rest_cannot_view",
    "message": "Sorry, you cannot list resources.",
    "data": {
        "status": 401
    }
}
```

**To Reproduce**
1. Launch VVV and install WooCommerce
1. Create a REST user
1. Use Postman to create a request to `http://one.wordpress-default.test/wp-json/v2/orders`
1. Use `Basic Auth` for the consumer key and secret
1. See error as shown above.

I found this code to be where the permission check is failing: woocommerce\includes\wc-rest-functions.php L:263. Here is the `var_dump($cap,$post_type_object,$permission);die;` 
what I saw on my machine.

```
string 'read_private_posts' (length=18)

object(WP_Post_Type)[480]
  public 'name' => string 'shop_order' (length=10)
  public 'label' => string 'Orders' (length=6)
  public 'labels' => 
    object(stdClass)[475]
      public 'name' => string 'Orders' (length=6)
      public 'singular_name' => string 'Order' (length=5)
      public 'add_new' => string 'Add order' (length=9)
      public 'add_new_item' => string 'Add new order' (length=13)
      public 'edit_item' => string 'Edit order' (length=10)
      public 'new_item' => string 'New order' (length=9)
      public 'view_item' => string 'View order' (length=10)
      public 'view_items' => string 'View Posts' (length=10)
      public 'search_items' => string 'Search orders' (length=13)
      public 'not_found' => string 'No orders found' (length=15)
      public 'not_found_in_trash' => string 'No orders found in trash' (length=24)
      public 'parent_item_colon' => null
      public 'all_items' => string 'Orders' (length=6)
      public 'archives' => string 'Orders' (length=6)
      public 'attributes' => string 'Post Attributes' (length=15)
      public 'insert_into_item' => string 'Insert into post' (length=16)
      public 'uploaded_to_this_item' => string 'Uploaded to this post' (length=21)
      public 'featured_image' => string 'Featured Image' (length=14)
      public 'set_featured_image' => string 'Set featured image' (length=18)
      public 'remove_featured_image' => string 'Remove featured image' (length=21)
      public 'use_featured_image' => string 'Use as featured image' (length=21)
      public 'filter_items_list' => string 'Filter orders' (length=13)
      public 'items_list_navigation' => string 'Orders navigation' (length=17)
      public 'items_list' => string 'Orders list' (length=11)
      public 'item_published' => string 'Post published.' (length=15)
      public 'item_published_privately' => string 'Post published privately.' (length=25)
      public 'item_reverted_to_draft' => string 'Post reverted to draft.' (length=23)
      public 'item_scheduled' => string 'Post scheduled.' (length=15)
      public 'item_updated' => string 'Post updated.' (length=13)
      public 'menu_name' => string 'Orders' (length=6)
      public 'edit' => string 'Edit' (length=4)
      public 'parent' => string 'Parent orders' (length=13)
      public 'name_admin_bar' => string 'Order' (length=5)
  public 'description' => string 'This is where store orders are stored.' (length=38)
  public 'public' => boolean false
  public 'hierarchical' => boolean false
  public 'exclude_from_search' => boolean true
  public 'publicly_queryable' => boolean false
  public 'show_ui' => boolean true
  public 'show_in_menu' => boolean true
  public 'show_in_nav_menus' => boolean false
  public 'show_in_admin_bar' => boolean true
  public 'menu_position' => null
  public 'menu_icon' => null
  public 'capability_type' => string 'shop_order' (length=10)
  public 'map_meta_cap' => boolean true
  public 'register_meta_box_cb' => null
  public 'taxonomies' => 
    array (size=0)
      empty
  public 'has_archive' => boolean false
  public 'query_var' => boolean false
  public 'can_export' => boolean true
  public 'delete_with_user' => null
  public '_builtin' => boolean false
  public '_edit_link' => string 'post.php?post=%d' (length=16)
  public 'cap' => 
    object(stdClass)[478]
      public 'edit_post' => string 'edit_shop_order' (length=15)
      public 'read_post' => string 'read_shop_order' (length=15)
      public 'delete_post' => string 'delete_shop_order' (length=17)
      public 'edit_posts' => string 'edit_shop_orders' (length=16)
      public 'edit_others_posts' => string 'edit_others_shop_orders' (length=23)
      public 'publish_posts' => string 'publish_shop_orders' (length=19)
      public 'read_private_posts' => string 'read_private_shop_orders' (length=24)
      public 'read' => string 'read' (length=4)
      public 'delete_posts' => string 'delete_shop_orders' (length=18)
      public 'delete_private_posts' => string 'delete_private_shop_orders' (length=26)
      public 'delete_published_posts' => string 'delete_published_shop_orders' (length=28)
      public 'delete_others_posts' => string 'delete_others_shop_orders' (length=25)
      public 'edit_private_posts' => string 'edit_private_shop_orders' (length=24)
      public 'edit_published_posts' => string 'edit_published_shop_orders' (length=26)
      public 'create_posts' => string 'edit_shop_orders' (length=16)
  public 'rewrite' => boolean false
  public 'show_in_rest' => boolean false
  public 'rest_base' => boolean false
  public 'rest_controller_class' => boolean false

boolean false
```

**Expected behavior**
I expected a clear error message on the error and also for the request to go through. The capabilities of the user is an admin user.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

Home URL: http://vvv.test
Site URL: http://vvv.test
WC Version: 3.5.2
Log Directory Writable: ✔
WP Version: 5.0.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.15.7
PHP Version: 7.2.13-1+ubuntu14.04.1+deb.sury.org+1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.11-MariaDB-1:10.3.11+maria~trusty
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.1
WC Database Prefix: wp_
Total Database Size: 71.65MB
Database Data Size: 61.77MB
Database Index Size: 9.88MB
wp_woocommerce_sessions: Data: 30.59MB + Index: 1.10MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.30MB + Index: 0.14MB
wp_woocommerce_order_itemmeta: Data: 1.82MB + Index: 1.43MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.05MB + Index: 0.04MB
wp_comments: Data: 2.18MB + Index: 0.74MB
wp_ff_cache: Data: 0.00MB + Index: 0.00MB
wp_ff_image_cache: Data: 0.00MB + Index: 0.00MB
wp_ff_options: Data: 0.00MB + Index: 0.00MB
wp_ff_posts: Data: 0.00MB + Index: 0.00MB
wp_ff_snapshots: Data: 0.00MB + Index: 0.00MB
wp_ff_streams: Data: 0.00MB + Index: 0.00MB
wp_ff_streams_sources: Data: 0.00MB + Index: 0.00MB
wp_gf_draft_submissions: Data: 0.00MB + Index: 0.00MB
wp_gf_entry: Data: 0.26MB + Index: 0.03MB
wp_gf_entry_meta: Data: 1.01MB + Index: 0.79MB
wp_gf_entry_notes: Data: 0.00MB + Index: 0.00MB
wp_gf_form: Data: 0.00MB + Index: 0.00MB
wp_gf_form_meta: Data: 0.05MB + Index: 0.00MB
wp_gf_form_view: Data: 0.09MB + Index: 0.04MB
wp_itsec_distributed_storage: Data: 0.00MB + Index: 0.00MB
wp_itsec_fingerprints: Data: 0.00MB + Index: 0.00MB
wp_itsec_geolocation_cache: Data: 0.00MB + Index: 0.00MB
wp_itsec_lockouts: Data: 0.00MB + Index: 0.01MB
wp_itsec_logs: Data: 2.44MB + Index: 0.06MB
wp_itsec_temp: Data: 0.00MB + Index: 0.01MB
wp_layerslider: Data: 0.03MB + Index: 0.00MB
wp_layerslider_revisions: Data: 0.00MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_mr_integrator_log: Data: 5.17MB + Index: 0.26MB
wp_mr_wc_dump_requests: Data: 0.72MB + Index: 0.14MB
wp_mr_wc_imports: Data: 0.07MB + Index: 0.01MB
wp_mr_wc_log: Data: 0.22MB + Index: 0.01MB
wp_mr_wc_stats: Data: 1.07MB + Index: 0.33MB
wp_options: Data: 3.23MB + Index: 0.08MB
wp_postmeta: Data: 8.97MB + Index: 3.27MB
wp_posts: Data: 1.04MB + Index: 0.24MB
wp_rg_form: Data: 0.00MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.05MB + Index: 0.00MB
wp_rg_form_view: Data: 0.05MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.00MB + Index: 0.00MB
wp_rg_lead: Data: 0.11MB + Index: 0.02MB
wp_rg_lead_detail: Data: 0.43MB + Index: 0.47MB
wp_rg_lead_detail_long: Data: 0.00MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.00MB + Index: 0.00MB
wp_rg_lead_notes: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.01MB + Index: 0.03MB
wp_term_taxonomy: Data: 0.01MB + Index: 0.01MB
wp_usermeta: Data: 0.86MB + Index: 0.48MB
wp_users: Data: 0.03MB + Index: 0.04MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_gpf_render_cache: Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_gpf_google_taxonomy: Data: 0.86MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.03MB + Index: 0.01MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 511
avia_framework_post: 7
cp_recipe: 44
ctct_forms: 1
ctct_lists: 13
jetpack_migration: 2
nav_menu_item: 53
oembed_cache: 3
page: 51
post: 26
product: 126
recipe: 1
shipping_option: 1
shop_order: 1265
shop_order_refund: 4

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.5.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #2411 - /shop/
Cart: #2412 - /cart/
Checkout: #2413 - /checkout/
My account: #2414 - /my-account/
Terms and conditions: #1930 - /terms/

### Theme ###

Name: Twenty Seventeen
Version: 1.8
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
</details>

**Comment by claudiosanches** [comment]
>  I expected a clear error message on the error and also for the request to go through. The capabilities of the user is an admin user.

The message is clear, you don't have permissions, this sound something custom, since I'm testing here I can't reproduce this problem. You said that you tested without all plugins deactivated, but capabilities are stored in the database, maybe need to restore the capabilities for your user.

This is the function that checks for user permissions when fetching anything on the REST API: https://github.com/woocommerce/woocommerce/blob/b0b3ddccb0cf6964e2ff1c70b85dbd3b9764fa85/includes/wc-rest-functions.php#L236-L263

**Comment by cgsmith** [comment]
@claudiosanches thanks for taking a peak at the issue. Query string auth works after trying that. I will double check user caps in the DB.
