### ISSUE TITLE
All orders not display

### ISSUE THREAD

**Issue by mumaromania** [woocommerce/woocommerce#22272]
Right after updating to wordpress 5.0.2, i have an overnight issue. In all orders tab, there is no order displaying. Otherwise, in every other tab, i can see the orders by status.
Any ideea why this happened? This is an overnight appeared issue

ALL ORDERS TAB
![image](https://user-images.githubusercontent.com/38977997/50282340-1f967580-045b-11e9-9801-110559ac2641.png)

IN PROCESS TAB
![image](https://user-images.githubusercontent.com/38977997/50282372-39d05380-045b-11e9-842f-d7d07c2e2ecc.png)

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by najdanovicivan** [comment]
I can also confirm that I have the same issue on multiple wocommerce installations

**Comment by rrennick** [comment]
duplicate of #22271.

**Comment by mumaromania** [comment]
Thank you, i don't post here usually and i didn't find it from what i have searched. I will keep following that post.
