### ISSUE TITLE
Billing / Shipping Address Issue

### ISSUE THREAD

**Issue by gilesholder** [woocommerce/woocommerce#22275]
**Describe the bug**
Hi there, I have a site which is set to only sell within the UK. It has just been brought to my attention by a customer of a potential bug/issue. The client is based in Ireland (Not UK) however wants to ship to a UK address. It seems, however, it won't let her purchase due to an Irish address for billing. Stripe is used for payment which validates the billing address against the bank so can't fake the address either.

**To Reproduce**
1. Set a non-UK billing address
2. Set a UK based shipping address

**Expected behaviour**
The expected behaviour would be the client allowed to complete the order as the Shipping address is UK and the Billing address which is non UK has no say in the matter.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
Need to configure selling locations without a limitation, and shipping locations to UK only to allow for this setup. If selling location is UK only, billing address must be UK.
