### ISSUE TITLE
White screen of death after

### ISSUE THREAD

**Issue by DmitryD19** [woocommerce/woocommerce#22283]
Hello! After the update, the website stopped working. Disconnected through the hosting, plugins, themes,...not helping. The staff hosting copied the theme and filled again. Damn(( In the browser the store is visible, but then the directory does not get returns on the home.
https://napitkistore.ru

**Comment by mikejolley** [comment]
Github is our bug tracker, not a place to get product support.

If you need help with core, use our [support forum](https://wordpress.org/support/plugin/woocommerce) or if you need help with a WooThemes premium plugin, use our [helpdesk](https://support.woothemes.com).

Thanks
