### ISSUE TITLE
Do not show shipping cost of 0.00 for customer pickup (behaves like free shipping)

### ISSUE THREAD

**Issue by gerdneuman** [woocommerce/woocommerce#22285]
**Current situation:**

For free shipping the shipping cost of `€0.00` is not shown (great and expected!), but local pickup it is:

![image](https://user-images.githubusercontent.com/12525563/50342918-533dd200-0525-11e9-9056-54321504255c.png)

**Expected behaviour:**

If the shipping cost for local customer pickup is `0.00` (which it might be in 99.9%) then do not print this. It's obivious if I pick up myself instead of shippment, then there are no cost. Programmatically WooCommerce could even check and if `local_pickup` has zero cost then do not print it. Same as free shipping.

For customer it is confusing that `0.00` is printed next to `Customer pickup`: Why is it not printed as well for `Free shipping`, does this cost extra or why would the shop owner print it in one case but not in the other?

At the moment one cannot really work around this. One can only hide the `0.00` with CSS, but then the `:` at the end of `Customer pickup:` is still visible making it look strange.

**Comment by gerdneuman** [comment]
In my case the settings for costs for local pickup is even left blank. See input field for `Kosten` (meaning `Costs`), the `0` that is visible is just the placeholder, the field is empty:

![image](https://user-images.githubusercontent.com/12525563/50343648-027ba880-0528-11e9-9bcf-5d693a7c059b.png)

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/18624 for background.

@rrennick Closing https://github.com/woocommerce/woocommerce/pull/22310 - rather than that we could consider targetting local pickup method directly, how free shipping is handled. That would leave prices in places for the scenarios reported in the other thread.

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/22446
