### ISSUE TITLE
Additional filter hook to remove item from the session cart

### ISSUE THREAD

**Issue by alessandromorelli** [woocommerce/woocommerce#22289]
**Is your feature request related to a problem? Please describe.**
When the cart is recovered from the session, item are checked and removed if they are no longer purchasable or have been changed.
In this case the customer receives an error notice and gets redirected to the cart via an interstitial page.
It isn't possible to bypass these notices and redirects and the checkout flow cannot be customized.

**Describe the solution you'd like**
The items should be passed through a filter to be flagged for removal, without raising notices, so that a customization can raise ad-hoc notices or trigger a different behaviour.

**Describe alternatives you've considered**
There are no alternatives, as the notices are raised when the cart is loaded from the session and the existing integration hook gets called after the notices are raised.

**Additional context**
The use case that prompted this issue goes like this:
- The customer clicks on a link that builds a complete cart for him or her and redirects directly to the checkout page (a variation on the 1-click purchase pattern)
- The cart contains one or more items that are available only on the first purchase, e.g. a free or reduced price item for new customer.
- The customer wasn't a new customer, but he or she wasn't logged in, so he or she appeared new to the site
- the customer logs in from the checkout page
- After the login, items available only to new customer are removed from the cart
- The customer reviews the cart and proceed with the payment

With the current setup, the checkout flow gets interrupted with an error message an the customer is redirected back to the cart page.
With an alternative filtering mechanism, we can remove or replace some items and use a different notification scheme, keeping the customer on track in a streamlined checkout process.

**Comment by rodrigoprimo** [comment]
Closing as the author submitted a PR implementing the suggested filter (see #22290).
