### ISSUE TITLE
Product export html causing bug

### ISSUE THREAD

**Issue by DionGrendelman** [woocommerce/woocommerce#22280]
**Describe the bug**
When doing a export, with products that have breaks (enters) in the product desc the export file goes mad, and makes new lines, this causes the file to break on import and in other softwares.

**To Reproduce**
1. Export products with product desc with divs or breaks
2. Check file

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/22094225/50305363-e11cad00-0492-11e9-850c-4210279511df.png)

**Expected behavior**
Normal export list.

**Isolating the problem (mark completed items with an [x]):**
- Atm i just removed all the divs and breaks, but the breaks arent going away, only way to fix this is to keep the product desc in 1 straight line

**WordPress Environment**
Newest...
</details>

**Comment by JayWood** [comment]
Seems to be valid - [Raw CSV Example](https://gist.githubusercontent.com/JayWood/de08d5c18dfe9996d448e554d182eef3/raw/b930a165fc329313dbcf597e8fe05cf3a2174c44/wc-product-export-20-12-2018-1545352538369.csv)

WP 5.0.2
WC 3.5.3

Product information in admin for testing.
![dbe4fdac5f106ec9996c3c2c33355760](https://user-images.githubusercontent.com/2303074/50318395-e972e900-048e-11e9-90d5-3c54a58d2bbd.png)

Error message on upload?
![2c25a37d949ad0bf72884fc23e4cd1ce](https://user-images.githubusercontent.com/2303074/50318445-2a6afd80-048f-11e9-861d-ff094d514f9e.png)

**Comment by rrennick** [comment]
> Error message on upload?

The CSV upload issue is separate from this issue. See #22208 .
