### ISSUE TITLE
Restricted Content Options Not Showing up in WP 5.0.2

### ISSUE THREAD

**Issue by KendallRogersD1** [woocommerce/woocommerce#22288]
Hey guys -- I am using the new Gutenberg editor in the new Word Press 5.0.2, and for whatever reason, my two premium options are not showing up in the Easy Restricted Access section (screenshot included). When I click back to the classic look, they both show up. 

Any ideas?

<img width="293" alt="screen shot 2018-12-21 at 12 22 20 pm" src="https://user-images.githubusercontent.com/42068351/50361662-07415c00-052a-11e9-9c31-77ae1b725124.png">

**Comment by KendallRogersD1** [comment]
Just a heads up -- this is fine on mobile with Gutenberg. It's just on desktop on Chrome or Safari for Mac OS Mojave.

**Comment by GlennMartin1** [comment]
What version of WooCommerce are you using?

**Comment by rodrigoprimo** [comment]
Hi @KendallRogersD1,

We use this GitHub issue tracker exclusively for WooCommerce core issues. It seems that the problem you are describing is related to one of the WooCommerce extensions, but it is not clear to me which extension.

If the extension is hosted on WooCommerce.com, please contact [their support](https://woocommerce.com/contact-us/).

Closing this issue for now but please leave a comment if I missed something and you believe the problem you are describing is in WooCommerce core. If that is the case, please include in your comment all the information that is requested in the [bug report template](https://github.com/woocommerce/woocommerce/issues/new?template=Bug_report.md).
