### ISSUE TITLE
Subscription list is empty

### ISSUE THREAD

**Issue by murtdagi** [woocommerce/woocommerce#22287]
When we launch Subscritptions page on the admin UI, the subscription list is empty. However the subscription list is shown when clicking the filters active/expired etc.
This issue is very similar to the order list issue fixed in the latest release.

**Comment by ancabogdan** [comment]
me too :(

**Comment by rrennick** [comment]
This should be fixed with WCS 2.4.6.

**Comment by murtdagi** [comment]
Thanks for the update
