### ISSUE TITLE
Shop page reverts to non archive page when rewrite rules are flushed

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#22286]
### Describe the bug
This isn't an easy one to reproduce but we have seen it across various sites. Basically what happens is that the rewrite rules get flushed when a there is a theme switch detected between a theme that supports WooCommerce and one that doesn't. Once this gets triggered we end up with the shop page being a non archive page. Because it is no longer an archive page the Shop page doesn't show any products (blank shop page).

We see this happen in an environment where there are two themes in use. For example with the [WPtouch](https://wordpress.org/plugins/wptouch/) plugin. This allows a separate theme to be used when loading the site on mobile pages.

We also see this happening on sites with the [AMP](https://wordpress.org/plugins/amp/) plugin. AMP pages/posts can also be displayed using a different theme (which doesn't declare WooCommerce support). Although AMP pages/posts seem to be cached so I haven't been able to reproduce this with AMP. But we do have a case where this is happening for a site where the product page goes blank after being left alone for a day or so, see: 1652662-zen

### To Reproduce

1. Install and active the WPtouch plugin: https://wordpress.org/plugins/wptouch/
2. Activate Storefront as the theme
3. Make sure WP Cron is setup normally so it will trigger tasks to be run when a page on the site is viewed.
4. The next part is best reproduced on a site without traffic, so a local site which has been without page views for a little while is best to use. The reason we need to have a site without page views is because we are trying to trigger a frontend request which coincides with a WP cron task running. Since WooCommerce now has the Action Scheduler built in we should have a cron task which is set to run every minute, so we would just need to wait till this is queued to run.
5. Next we view the home page on a mobile device (or in a simulated mobile view in chrome dev tools). Since we have WPtouch active the home page will be loaded with a theme that does not declare WooCommerce Support.
6. At the same time as the home page is generated, a separate cron task will run. This cron task will see that Storefront is set as the active theme (which does declare WooCommerce Support).
7. Both of these two separate tasks detect a switch between themes and trigger a flush of the rewrite rules. Because of the way WordPress updates rewrite rules it only gets updated once and we end up with a set of rewrite rules for a theme that does not declare WooCommerce Support.
8. If we now load the Shop page through a normal request using the Storefront theme, the page is not an archive page and we see no products (this remains this way until the rewrite rules are flushed again).

The problem seems to come from this bit of code: https://github.com/woocommerce/woocommerce/blob/3.5.3/includes/class-wc-post-types.php#L286-L295

Since we get two processes running at the same time, we get the following differences:

#### PHP process for generating mobile page
Uses a generic mobile theme so `current_theme_supports( 'woocommerce' )` returns false. Which in turn sets $has_archive to false.
Since the previous theme was Storefront we update the option `current_theme_supports_woocommerce` and force a flush of the rewrite rules to happen on the hook `woocommerce_after_register_post_type`
Since the flush has $has_archive set to false we registered the post_type products without an archive page (shop page). Which means the following rewrite rules are not registered:

```
shop/?$    index.php?post_type=product
shop/feed/(feed|rdf|rss|rss2|atom)/?$    index.php?post_type=product&feed=$matches[1]
shop/(feed|rdf|rss|rss2|atom)/?$    index.php?post_type=product&feed=$matches[1]
shop/page/([0-9]{1,})/?$    index.php?post_type=product&paged=$matches[1]
```

#### PHP process for the cron task
This process will use the Storefront theme again. So `current_theme_supports( 'woocommerce' )` returns true. Which sets $has_archive to 'shop'. Since the previous process updated `current_theme_supports_woocommerce` we update it here again because we are back to a theme that supports WooCommerce. This again triggers the flush of the rewrite rules to happen again.

I haven't been able to track down completely what happens when two processes try to flush the rewrite rules at the same time, so I'm not sure if it's a race condition or it just only allows it to update once. But on my test site this ends up with the rewrite rules from the first process where there was no archive page.

So when we go to view the Shop page in Storefront it's no longer detected as an archive page and we get the empty Shop page showing.

### Expected behavior
I would expect the rewrite rules to always reflect the right status so the Products don't go missing from the shop page.

I understand that there wouldn't be a lot of users running into this because there wouldn't be many who use WPTouch with two themes. However the fact that it also happens with AMP means there are probably a lot more sites that could be affected by this.

Considering that in this scenario it's possible to force a flush of the rewrite rules from the frontend of the site without any admin touching the site. Made it very hard to track down as it seems like it happened just at random.

Should the rewrite rules ever need to be flushed from a frontend request?

Also, is it necessary to turn the shop page into a non archive page when the theme does not declare WooCommerce support? Wouldn't it still need to show an archive of products?

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

## WordPress Environment
<details>

```
### WordPress Environment ###

Home URL: https://woo.test
Site URL: https://woo.test
WC Version: 3.5.3
Log Directory Writable: ✔
WP Version: 5.0.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.14.0
PHP Version: 7.2.10-0ubuntu0.18.04.1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.0g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.34-MariaDB-0ubuntu0.18.04.1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 3.67MB
Database Data Size: 2.75MB
Database Index Size: 0.92MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.06MB + Index: 0.05MB
wp_postmeta: Data: 0.08MB + Index: 0.03MB
wp_posts: Data: 0.09MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 13
nav_menu_item: 13
page: 9
post: 4
product: 5
product_variation: 1
shop_order: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce: by Automattic – 3.5.3
WPtouch Mobile Plugin: by WPtouch – 4.3.34

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.4.2
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
```

</details>

**Comment by rrennick** [comment]
The solution to this is to `add_theme_support( 'woocommerce' )` in the mobile theme (or create a small plugin that has that line of code). If all the features of WC were added to all themes then `add_theme_support` would serve no useful purpose.

**Comment by madeincosmos** [comment]
Ideally the shop page should load correctly even if the theme doesn't declare WooCommerce support. We have no control over what theme any particular user will install, so declaring WooCommerce support on behalf of 3rd parties is not an option.

**Comment by davodavodavo3** [comment]
I have the same issue in my custom archive-page.php template, but I realy can't catch why shop page revert to non archive page. So after some page refreshes body class doesn't show that page is archive instead it add page id and page-template-default page.


WooCommerce version: |   | 3.5.3
WordPress version: |   | 5.0.2

**Comment by rrennick** [comment]
> Basically what happens is that the rewrite rules get flushed ... Once this gets triggered we end up with the shop page being a non archive page.

The rewrite rules are flushed at least as often as creating a post, page, product, category, tag, etc. This is unrelated to rewrite rules being flushed. The WC shop page is a real WP page that once created will be in the rewrite rules and work as a default page even if WC was removed from the install. 

Secondly, I tested this with by removing the `add_theme_support` from the Storefront theme and the shop page loads the shop content. Removing the theme support does make some changes in the markup (ex. theme support adds CSS classes) so the non-supporting theme may need additional styling.

Can you provide more detailed steps to reproduce this issue?

**Comment by rrennick** [comment]
Sorry, it didn't occur to me that your shop page may have been deleted. If it's been deleted then the products page does not show at the `shop` permalink. In that case, create & publish a new shop page then select it in the WC -> Settings -> Products.

I'm going to close this. If you can provide steps to reproduce this when the shop page exists and is selected in WC, please re-open.

**Comment by rrennick** [comment]
> Doing this is what causes the following rewrite rules to go missing:

When I remove the theme support in Storefront then visit the Settings -> Permalinks screen to ensure the rewrite rules are flushed, the shop page continues to have the same content it had when the rewrite rules were present.

> Would you be able to clarify why this issue was closed?

WooCommerce has been developed with documented explicit requirements for themes. This issue effectively requests that one of those explicit requirements be eliminated. 

With a few lines of code (may vary by theme) you can dynamically add the theme support if the request is being handled by your mobile theme.
