### ISSUE TITLE
WC_Widget_Product_Categories "Show hierarchy" error with child / grand child category

### ISSUE THREAD

**Issue by EdithAllison** [woocommerce/woocommerce#22281]
**Describe the bug**
In widget "Product Categories", the child categories are shown / hidden differently depending on whether "Show hierarchy" is ticked / unticked. Bug only affects child categories with no products of their own that have grand child categories with products.  

**To Reproduce**
1. Set up product category structure with parent (no products), child (no products), grandchild (products)
2. Enable Widget "Product Categories" 
3. Do NOT tick "Show hierarchy"
=> child category is missing 

now to see expected behaviour:
4. Tick "Show hierarchy"
=> child category is showing 

**Screenshots**
<img width="1274" alt="tree-01" src="https://user-images.githubusercontent.com/19706428/50306645-5a69cf00-0496-11e9-95a9-8d3ae1bda862.png">

<img width="357" alt="widget-01" src="https://user-images.githubusercontent.com/19706428/50306658-605fb000-0496-11e9-9b7a-492056117212.png">

<img width="935" alt="category-01" src="https://user-images.githubusercontent.com/19706428/50306661-648bcd80-0496-11e9-9bd2-48c5c85b22a5.png">

**Expected behavior**
Expected behaviour is to see child category in both scenarios
Actual behaviour is that child category is missing when hierarchy is unticked 

**Isolating the problem**
I've tested the behaviour with 2019 theme, but screenshots are taken with Storefront theme as it's easier to show. 

**WordPress Environment**
WP 5.0.2
WooCommerce 3.5.3
Storefront 2.4.2
Vanilla install, no other plugins

**Comment by rrennick** [comment]
If you use the same setup with Posts & Post Categories (or any hierarchical taxonomy in WP), you will find the same behaviour. In your example, `Grand child` is a descendant of, but not a child of, `Parent`.

**Comment by rrennick** [comment]
Closing as this is default WordPress handling of hierarchical taxonomies.
