### ISSUE TITLE
Checkout: Singapore problem with Town / City field

### ISSUE THREAD

**Issue by MartaPawlonka** [woocommerce/woocommerce#22292]
After choosing Singapore, the Town / City field is not showing. I need to refresh the page to see it.

Before refresh: http://wpde.sk/mp/hliwh.png
After refresh: http://wpde.sk/mp/un51u.png

**Comment by rrennick** [comment]
Add the following to you theme functions file

```
function sgh_show_town_state( $locales ) {
	$locales['SG']['city']['hidden'] = false;
	return $locales;
}
add_filter( 'woocommerce_get_country_locale', 'sgh_show_town_state' );
```

**Comment by willgorham** [comment]
The 'City' field is intentionally hidden for Singapore: #21016/#21018

The fact that it is shown after refresh might be related to this issue: https://github.com/woocommerce/woocommerce/issues/22119

**Comment by mikejolley** [comment]
Closing in favour of https://github.com/woocommerce/woocommerce/issues/22119
