### ISSUE TITLE
{price_including_tax} doesn't work on Variable products when all variations have same price

### ISSUE THREAD

**Issue by AashikP** [woocommerce/woocommerce#22294]
**Describe the bug**
If you have a variable product where the variations all have the same price and you use a price display suffix set to {price_including_tax}, you’ll never see the price including tax after choosing from the available variations.

**To Reproduce**
1. Set Price display suffix to `{price_including_tax}` under **WooCommerce > Settings > TAX**
2. Create a Variable Product and set the same price for all variations
3. You won't be able to view the suffix at all

**Screenshots**
![https://cld.wthms.co/dfqu5d+](https://cld.wthms.co/dfqu5d+)
*Direct Link: https://cld.wthms.co/dfqu5d*

**Expected behavior**
Display suffix irrespective of  - if the variable products are priced same, or different.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
ANY

**Comment by rrennick** [comment]
Add this line to your theme functions.php

`add_filter( 'woocommerce_show_variation_price', '__return_true' );`

**Comment by PositivelyHazo** [comment]
Great! That worked!  Thank you.
This has fixed the issue with same price products not displaying the suffix. The display now works the same as products with variable prices. 
I do have another question however: I would like the suffix to display on the category page, and for the large value at the top of the product page (they both seem to be the same element/function)
To elaborate: 
https://rockcity.co.uk/crobes/ - the value shows no suffix
https://rockcity.co.uk/rockcity-crobes-l-xl/ - The value shows no suffix, however once a colour is selected, a different element appears with the suffix.

I would like that value with the suffix to display as that bold text value as it does for simple products (https://rockcity.co.uk/pro-wall-bundles/) Yes, they're bundle products, but they still have the same functionality as the simples do. 

Is there another filter for this?

**Comment by rrennick** [comment]
> I do have another question however: I would like the suffix to display on the category page, and for the large value at the top of the product page (they both seem to be the same element/function)

Github is for reporting bugs. For support, contact https://woocommerce.com or the support forum https://wordpress.org/support/plugin/woocommerce.

**Comment by AashikP** [comment]
@rrennick Thank you for the workaround. However, as @PositivelyHazo  reported, this does work for the single-product page, but not on category archives:

![http://cld.wthms.co/GUhspb+](http://cld.wthms.co/GUhspb+)
*Direct Link: http://cld.wthms.co/GUhspb*

~ Reopening since the woraround does not completely eliminate the behavior.

**Comment by AashikP** [comment]
A workaround for the single product page - problem with variable product not displaying the price with VAT without selecting a variation would be to set up a default variation as @PositivelyHazo [reported](https://github.com/woocommerce/woocommerce/issues/22294#issuecomment-452647798).

![http://cld.wthms.co/znKzKI+](http://cld.wthms.co/znKzKI+)
*Direct Link: http://cld.wthms.co/znKzKI*

*Note: This is a workaround that works only with @rrennick's snippet in `functions.php` file - such that one of the variations is already selected, and you're able to see price inclusive of tax on loading the product page:*

![http://cld.wthms.co/l0H4IS+](http://cld.wthms.co/l0H4IS+)
*Direct Link: http://cld.wthms.co/l0H4IS*

**Comment by mikejolley** [comment]
This functionality is turned off at VARIABLE product level because it's not possible to "know" the prices including/excluding tax. Prices come from variations. Variations can have different tax classes. So it's not possible to know what rate to apply to which price.

e.g. I have a variable product with 2 variations. Both are priced at $10, however, one variation has a tax rate of 20% and one has a reduced rate of 10%. What is the price including tax?

This is only documented inline here https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-product-variable.php#L132-L147

One can customise this method via the filter hooks if needed for variable products.

As for variations (the price revealed when you've selected a variation), those do support suffixes because variations do have a tax class/rate.

Thanks

**Comment by jkdeleteme** [comment]
this snipped didn't work for me.
However, I found this article with longer and more detailed code that already works.

https://jarnoan.com/2017/11/13/how-to-restore-price-suffix-for-variable-product-in-woocommerce/
