### ISSUE TITLE
Fee API - Multiple fees (positive / negative) issue

### ISSUE THREAD

**Issue by Johnny99211** [woocommerce/woocommerce#22305]
**Describe the bug**
I'm trying to add two fees to my cart. One fee is a positive fee (a provision) and the other fee is a negative fee (a special vip discount). When I set now the tax settings for the cart to **Excluding Tax** and add the two fees, the first one displays the set value in the code but the second one has an absolute strange value. The second one displays the tax for the first one (19% of the first fee) including the negative value set in the code:

**To Reproduce**

1. Go to WooCommerce -> TAX settings and exclude the TAX from the cart / checkout
2. Do the stuff below:

float(6002.5) 
float(300.125)

**This is how I set the positive fee:**
```
add_action( 'woocommerce_cart_calculate_fees', 'set_provision_and_vip_discount', 10, 1 );
function set_provision_and_vip_discount( $cart ) {
    $cart->add_fee( __( 'Provision', 'woocommerce' ), 6002.5, true );
    $cart->add_fee( sprintf( __( '%s VIP-Bonus', 'woocommerce' ), $vip_percent . '%' ), -300.125, true );
}
```
This is the result in the cart:

![image](https://user-images.githubusercontent.com/43766368/50497941-a986a580-0a3c-11e9-994f-a9c283b162de.png)

I'm expecting here a positive fee like defined and a negative fee of  **-300.13 €**

When I enable now the TAX for the cart / checkout in the WooCommerce settings and change the last `true` in both fee's to `false` the result is like I expect it:

```
add_action( 'woocommerce_cart_calculate_fees', 'set_provision_and_vip_discount', 10, 1 );
function set_provision_and_vip_discount( $cart ) {
    $cart->add_fee( __( 'Provision', 'woocommerce' ), 6002.5, false);
    $cart->add_fee( sprintf( __( '%s VIP-Bonus', 'woocommerce' ), $vip_percent . '%' ), -300.125, false);
}
```

![image](https://user-images.githubusercontent.com/43766368/50498002-6416a800-0a3d-11e9-8666-a463475fa3ff.png)

**Screenshots**

First TAX settings:

![image](https://user-images.githubusercontent.com/43766368/50498070-c8d20280-0a3d-11e9-8a74-fd9ca4903be0.png)

Second TAX settings:

![image](https://user-images.githubusercontent.com/43766368/50498061-c079c780-0a3d-11e9-973a-a661ba1f527b.png)

**Expected behavior**
I expect the correct fee amount in the cart / checkout!!

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://www.enwikuna.de
Site URL: https://www.enwikuna.de
WC Version: 3.4.5
Log Directory Writable: ✔
WP Version: ❌ 4.9.9 - Es ist eine neuere Version von WordPress verfügbar (5.0.2)
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: –
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.10-0ubuntu0.18.04.1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 3000
cURL Version: 7.58.0
OpenSSL/1.1.0g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.34-MariaDB-0ubuntu0.18.04.1
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Dein Server verfügt nicht über eine lauffähige Version der SoapClient Klasse - einige Zahlungsschnittstellen
welche SOAP nutzen
funktionieren unter Umständen nicht korrekt.

DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Datenbank-Gesamtgröße: 10.82MB
Datenbank-Datengröße: 9.28MB
Datenbank-Indexgröße: 1.54MB
wp_woocommerce_sessions: Daten: 0.05MB + Index: 0.02MB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Daten: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB
wp_aborted_applications: Daten: 0.02MB + Index: 0.00MB
wp_aborted_jobs: Daten: 0.02MB + Index: 0.00MB
wp_accepted_jobs: Daten: 0.02MB + Index: 0.00MB
wp_accepted_jobs_to_clean: Daten: 0.02MB + Index: 0.00MB
wp_aiowps_events: Daten: 0.02MB + Index: 0.00MB
wp_aiowps_failed_logins: Daten: 0.02MB + Index: 0.00MB
wp_aiowps_global_meta: Daten: 0.02MB + Index: 0.00MB
wp_aiowps_login_activity: Daten: 0.02MB + Index: 0.00MB
wp_aiowps_login_lockdown: Daten: 0.02MB + Index: 0.00MB
wp_aiowps_permanent_block: Daten: 0.02MB + Index: 0.00MB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB
wp_comments: Daten: 0.16MB + Index: 0.09MB
wp_crellyslider_elements: Daten: 0.02MB + Index: 0.00MB
wp_crellyslider_sliders: Daten: 0.02MB + Index: 0.00MB
wp_crellyslider_slides: Daten: 0.02MB + Index: 0.00MB
wp_degrees: Daten: 0.02MB + Index: 0.02MB
wp_developer_rating: Daten: 0.02MB + Index: 0.00MB
wp_failed_jobs: Daten: 0.02MB + Index: 0.00MB
wp_job_applications: Daten: 0.02MB + Index: 0.00MB
wp_lead_form: Daten: 0.02MB + Index: 0.00MB
wp_lead_form_data: Daten: 0.02MB + Index: 0.00MB
wp_lead_form_extension: Daten: 0.02MB + Index: 0.00MB
wp_lead_form_options: Daten: 0.02MB + Index: 0.00MB
wp_links: Daten: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Daten: 0.02MB + Index: 0.00MB
wp_options: Daten: 2.23MB + Index: 0.08MB
wp_postmeta: Daten: 0.34MB + Index: 0.16MB
wp_posts: Daten: 5.11MB + Index: 0.06MB
wp_queue: Daten: 0.02MB + Index: 0.00MB
wp_skills: Daten: 0.02MB + Index: 0.02MB
wp_sm_sessions: Daten: 0.02MB + Index: 0.02MB
wp_termmeta: Daten: 0.02MB + Index: 0.03MB
wp_terms: Daten: 0.02MB + Index: 0.03MB
wp_term_relationships: Daten: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Daten: 0.02MB + Index: 0.03MB
wp_th_popup: Daten: 0.02MB + Index: 0.00MB
wp_toolset_post_guid_id: Daten: 0.02MB + Index: 0.02MB
wp_usermeta: Daten: 0.09MB + Index: 0.06MB
wp_users: Daten: 0.02MB + Index: 0.05MB
wp_wcpdf_invoice_number: Daten: 0.02MB + Index: 0.00MB
wp_wc_avatars_cache: Daten: 0.02MB + Index: 0.09MB
wp_wc_comments_subscription: Daten: 0.02MB + Index: 0.06MB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB
wp_wc_follow_users: Daten: 0.02MB + Index: 0.13MB
wp_wc_phrases: Daten: 0.02MB + Index: 0.02MB
wp_wc_users_voted: Daten: 0.02MB + Index: 0.06MB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB
wp_wpc_comments_subscription: Daten: 0.00MB + Index: 0.00MB
wp_wpc_phrases: Daten: 0.00MB + Index: 0.01MB
wp_wpc_users_voted: Daten: 0.00MB + Index: 0.00MB
wp_wpfd_statistics: Daten: 0.02MB + Index: 0.00MB
wp_wpfd_tokens: Daten: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Daten: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Daten: 0.02MB + Index: 0.00MB
wp_yobro_attachments: Daten: 0.02MB + Index: 0.00MB
wp_yobro_blocked_conversation: Daten: 0.02MB + Index: 0.00MB
wp_yobro_conversation: Daten: 0.02MB + Index: 0.00MB
wp_yobro_deleted_conversation: Daten: 0.02MB + Index: 0.00MB
wp_yobro_logs: Daten: 0.02MB + Index: 0.00MB
wp_yobro_messages: Daten: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 45
cred-form: 1
custom_css: 2
nav_menu_item: 20
page: 23
post: 1
product: 34
revision: 212
shop_coupon: 1
shop_order: 5
ticket: 13
ticket_history: 35
ticket_reply: 6
um_directory: 1
um_form: 4
wp-types-group: 1
wpdiscuz_form: 1
wpfd_file: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Fehlermeldungen sollten Besuchern nicht angezeigt werden.

### Active Plugins (26) ###

Advanced Cron Manager: von BracketSpace – 2.3.6
Awesome Support: von Awesome Support Team – 5.8.0
GDPR Cookie Consent: von WebToffee – 1.7.2
Toolset Forms Commerce: von OnTheGoSystems – 1.8.1
Toolset Forms: von OnTheGoSystems – 2.0
Crelly Slider: von Fabio Rinaldi – 1.3.4
Divi Builder: von Elegant Themes – 2.15
Google Analytics Dashboard for WP (GADWP): von ExactMetrics – 5.3.7
Intercom: von Intercom – 2.6.1
Lead Form Builder: von ThemeHunk – 1.3.6
One Click Demo Import: von ProteusThemes – 2.5.1
ThemeHunk Customizer: von ThemeHunk – 2.1.2
Toolset Types: von OnTheGoSystems – 2.3.5
Ultimate Member: von Ultimate Member – 2.0.35
Ultimate Member - Google reCAPTCHA: von Ultimate Member – 2.0.2
User Role Editor: von Vladimir Garagulya – 4.47
WooCommerce PayPal Checkout Gateway: von WooCommerce – 1.6.5
WooCommerce Germanized: von Vendidero – 2.2.3
WooCommerce PDF Invoices & Packing Slips: von Ewout Fernhout – 2.2.5
WooCommerce Services: von Automattic – 1.17.1
WooCommerce: von Automattic – 3.4.5 – 3.5.3 ist verfügbar
Yoast SEO: von Team Yoast – 9.3
WP File Download: von Joomunited – 4.3.28
WP First Letter Avatar: von Dev49.net – 2.2.8
wpDiscuz: von Team gVectors (A. Chakhoyan
G. Zakaryan
H. Martirosyan) – 5.2.2

YoBro Pro: von redqteam – 2.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: android (android)
css (css)
external (external)
grouped (grouped)
html (html)
ios (ios)
java (java)
jsf (jsf)
mysql (mysql)
php (php)
react (react)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
visible (visible)

### WC Pages ###

Shop-Basis: #197 - /auftraege/
Warenkorb: #17 - /warenkorb/
Kasse: #18 - /kasse/
Mein Konto: #19 - /kontouebersicht/
Allgemeine Geschäftsbedingungen: #23 - /agb/

### Theme ###

Name: Enwikuna
Version: 1.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Enwikuna
Parent Theme Version: – 0 ist verfügbar
Parent Theme Author URL: 
WooCommerce Support: ✔

### Templates ###

Overrides: enwikuna/woocommerce/archive-product.php
enwikuna/woocommerce/checkout/form-coupon.php
enwikuna/woocommerce/checkout/review-order.php
enwikuna/woocommerce/content-product.php
enwikuna/woocommerce/emails/admin-cancelled-order.php
enwikuna/woocommerce/emails/admin-failed-order.php
enwikuna/woocommerce/emails/admin-new-order.php
enwikuna/woocommerce/emails/customer-completed-order.php
enwikuna/woocommerce/emails/customer-invoice.php
enwikuna/woocommerce/emails/customer-note.php
enwikuna/woocommerce/emails/customer-processing-order.php
enwikuna/woocommerce/emails/customer-refunded-order.php
enwikuna/woocommerce/emails/email-addresses.php
enwikuna/woocommerce/emails/email-customer-details.php
enwikuna/woocommerce/emails/email-downloads.php
enwikuna/woocommerce/emails/email-footer.php
enwikuna/woocommerce/emails/email-header.php
enwikuna/woocommerce/emails/email-order-details.php
enwikuna/woocommerce/emails/email-order-items.php
enwikuna/woocommerce/emails/email-styles.php
enwikuna/woocommerce/emails/plain/admin-cancelled-order.php
enwikuna/woocommerce/emails/plain/admin-failed-order.php
enwikuna/woocommerce/emails/plain/admin-new-order.php
enwikuna/woocommerce/emails/plain/customer-completed-order.php
enwikuna/woocommerce/emails/plain/customer-invoice.php
enwikuna/woocommerce/emails/plain/customer-new-account.php
enwikuna/woocommerce/emails/plain/customer-note.php
enwikuna/woocommerce/emails/plain/customer-on-hold-order.php
enwikuna/woocommerce/emails/plain/customer-processing-order.php
enwikuna/woocommerce/emails/plain/customer-refunded-order.php
enwikuna/woocommerce/emails/plain/customer-reset-password.php
enwikuna/woocommerce/emails/plain/email-addresses.php
enwikuna/woocommerce/emails/plain/email-customer-details.php
enwikuna/woocommerce/emails/plain/email-downloads.php
enwikuna/woocommerce/emails/plain/email-order-details.php
enwikuna/woocommerce/emails/plain/email-order-items.php
enwikuna/woocommerce/myaccount/dashboard.php Version - ist veraltet. Die Hauptversion ist 2.6.0
enwikuna/woocommerce/myaccount/form-edit-account.php
enwikuna/woocommerce/myaccount/form-edit-address.php
enwikuna/woocommerce/myaccount/my-account.php
enwikuna/woocommerce/myaccount/my-address.php
enwikuna/woocommerce/myaccount/orders.php
enwikuna/woocommerce/myaccount/view-order.php
enwikuna/woocommerce/order/order-details-item.php
enwikuna/woocommerce/order/order-details.php
enwikuna/woocommerce/single-product/meta.php
enwikuna/woocommerce/single-product/price.php
enwikuna/woocommerce/single-product/short-description.php Version - ist veraltet. Die Hauptversion ist 3.3.0
enwikuna/woocommerce/single-product/tabs/tabs.php
enwikuna/woocommerce/single-product/title.php

Outdated Templates: ❌
					
					
						Erfahre
wie du aktualisieren kannst

`
</details>

**Comment by rrennick** [comment]
What is the price of the item(s) that were in the cart for the example above?

Have you tried this in a dev install with the latest version of WooCommerce?

**Comment by Johnny99211** [comment]
I've tried it with the WooCommerce version before the current one. But I've checked the changelog and there is nothing related to this error.

The price at the top is in this case 100k and also a netto price. The provision is calculated with 6% of the item price ( 100.000 * 6 / 100 = 6.000 + 2.5 <- always added ). The negative fee below is in this case 5% of the provision ( 6.002,5 * 5 / 100 = 300,125 ).

**Comment by rrennick** [comment]
Following your instructions the first code snippet produces
<img width="439" alt="screen shot 2018-12-28 at 1 31 41 pm" src="https://user-images.githubusercontent.com/343847/50523213-36654980-0aa5-11e9-86b4-29ec2e1809c1.png">

**Comment by Johnny99211** [comment]
This is so strange... Why this don't works on my side? I don't understand this. You've set the TAX cart settings to non taxable right? Can you disable shipping? Just to be sure. And you added the fees with add_fee right?

**Comment by Johnny99211** [comment]
Thanks for bringing me on the right way. I've disabled the plugin WooCommerce Germanized which causes this problem. You can close this bug now. Sorry that you've spent your time on this. I'm searching since 3 days for this issue in my customization.

**Comment by rrennick** [comment]
Glad you found it :)

**Comment by Johnny99211** [comment]
Oh yes! I'm very happy now 🥇
