### ISSUE TITLE
Fixing email layout in the iOS native email app

### ISSUE THREAD

**Issue by cynepkot** [woocommerce/woocommerce#22308]
**Is your feature request related to a problem? Please describe.**
All standard Woocommerce emails are being rendered incorrectly in the latest as of today 12.1 iOS (and possibly some other iOS versions) native email app in portrait mode. There are empty paddings and the table sticks to the screen's left side and does not fill the full width. The issue is observed on a wide range of Woocommerce versions and has been confirmed with the 3.5.3 on a clean WP install. While it may look not so horrible when emails are styled with white background, the colored one makes things ugly:
![img_2023](https://user-images.githubusercontent.com/32467153/50517677-6ff87d80-0ac2-11e9-9c18-6d1affdc7cbc.PNG)

**Describe the solution you'd like**
The solution was found [here](https://emails.hteumeuleu.com/what-you-need-to-know-about-apple-mail-in-ios-10-c7031f6d704d): applying _padding: 0;_ to the _body_ does fix the issue. Test with some popular email apps and web email apps shows no evidence of any negative impact of this style rule upon the email layout.

Fixed layout in the iOS app:
![img_2024](https://user-images.githubusercontent.com/32467153/50518116-029a1c00-0ac5-11e9-9432-d0e3ddb34671.PNG)

**Describe alternatives you've considered**
Writing a separate plugin just to add a single style rule to make this available to the broad audience of Woocommerce users seems a bit like an overkill.

**Comment by rodrigoprimo** [comment]
@cynepkot, from the screenshots you added to the issue description it seems that you are using a custom theme. Are you able to reproduce this problem using Storefront or one of the default WP themes?

**Comment by cynepkot** [comment]
Thats just a color and background styling, as this emphasizes the problem. See the shots from a clean WP install, Twenty Seventeen, 3.5.3
Smaller iPhone:
![img_2032](https://user-images.githubusercontent.com/32467153/50855066-df5e4f00-1397-11e9-87d1-5b97cb5068cf.PNG)
Medium iPhone:
![woomail](https://user-images.githubusercontent.com/32467153/50855096-f69d3c80-1397-11e9-81de-35d927a3f58a.jpg)
Don't have access to all sizes of iPhone at the moment, though inclined to believe it would be misaligned the same way.
