### ISSUE TITLE
Product page slash

### ISSUE THREAD

**Issue by Mapteg34** [woocommerce/woocommerce#22307]
**Describe the bug**
Woocommerce create item links like /shop/itemid without slash at end. But wordpress redirect it to /shop/itemid/ with slash in end (user_trailingslashit in redirect_canonical). Page available, but in canonical we see /shop/itemid without slash at end. It problem for seo. How to fix this behavior?

**To Reproduce**
1. Create product, see link /shop/itemid
2. Click on product, see redirect to /shop/itemid/ and product page on /shop/itemid/
3. View page source and see  /shop/itemid in canonical

**Comment by rrennick** [comment]
> Click on product, see redirect to /shop/itemid/ and product page on /shop/itemid/

That doesn't happen in my install. If you have a SEO or redirect plugin installed, one of those might be causing this issue.

**Comment by mikejolley** [comment]
Ditto, I see a slash so it's likely the config of an SEO plugin you're running.
