### ISSUE TITLE
Form Submits/Order Submits when "Enter" is pressed in "Shipping to a different address?"

### ISSUE THREAD

**Issue by EricaKuschel** [woocommerce/woocommerce#22302]
**Describe the bug**

Theme: Storefront
WC: 3.5.3
WP: 4.9.9 and 5.0.2
Payment Gateway: COD (for pick up at location), Cheque, any inline payment gateway where you have put in the credit card information.
Ticket: 1668089-zen

An order is submitted after completing the mandatory "Ship to a different address?" fields and pressing "Enter". The Terms and Conditions box had been checked too. This also occurs if "Enter" is pressed after a filled out Billing form. 

Customer did not mean to submit the order. Is this expected behavior? As a consumer, I would be surprised that the order went through without selecting the "Place Order" button.

**To Reproduce**
1. Add a physical item to the cart. 
2. Select your shipping.
3. Go to the checkout page. 
4. Select the Terms and Conditions checkbox.
5. Fill out Billing information.
6. Select "Ship to a different address?" checkbox.
7. Fill out Shipping information. 
8. When information is filled out for required fields, press "Enter".
9. Order will submit without order button being pressed. 

**Screenshots**

Filled out Billing: 

![image](https://user-images.githubusercontent.com/6961918/50489901-f1bbae80-09cf-11e9-8f89-91db5fe001a1.png)

Filled out Stripe with Terms of Service Checked: 

![image](https://user-images.githubusercontent.com/6961918/50489933-14e65e00-09d0-11e9-8a11-a234bf115855.png)

Filled out Shipping:

![image](https://user-images.githubusercontent.com/6961918/50489962-3b0bfe00-09d0-11e9-9a61-48aea0621775.png)

Without pressing the Place Order button: 

![image](https://user-images.githubusercontent.com/6961918/50490301-0c8f2280-09d2-11e9-80b5-093164370600.png)

**Expected behavior**

That the order will not be placed until the Place Order button is selected. 

Not sure this working as intended due to accessibility, but several people I talked to mentioned that this seems dishonest/sketchy (as people can submit orders before they are ready to).

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
4.9.9 and 5.0.2
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```

**4.9.9**

`
### WordPress Environment ###

WC Version: 3.5.3
Log Directory Writable: ✔
WP Version: ❌ 4.9.9 - There is a newer version of WordPress available (5.0.2)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.33 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.62.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.17-MariaDB
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.3
WC Database Prefix: wp_
Total Database Size: 7.99MB
Database Data Size: 4.92MB
Database Index Size: 3.07MB
wp_woocommerce_sessions: Data: 0.31MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.11MB + Index: 0.09MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.06MB + Index: 0.03MB
wp_comments: Data: 0.06MB + Index: 0.09MB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.03MB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB
wp_followup_email_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_email_orders: Data: 0.02MB + Index: 0.09MB
wp_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB
wp_followup_followup_history: Data: 0.02MB + Index: 0.05MB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.34MB + Index: 0.08MB
wp_postmeta: Data: 1.50MB + Index: 0.50MB
wp_posts: Data: 0.19MB + Index: 0.09MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.05MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_wps_hit: Data: 0.02MB + Index: 0.14MB
wp_wps_index: Data: 0.22MB + Index: 0.34MB
wp_wps_key: Data: 0.02MB + Index: 0.02MB
wp_wps_object_type: Data: 0.02MB + Index: 0.08MB
wp_wps_query: Data: 0.02MB + Index: 0.02MB
wp_wps_uri: Data: 0.02MB + Index: 0.02MB
wp_wps_user_agent: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 61
bookable_resource: 3
event_ticket: 2
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 5
order_shipment: 2
page: 13
post: 1
product: 44
product_variation: 51
revision: 18
scheduled-action: 24
shop_coupon: 5
shop_order: 36
wc_booking: 9
wc_pickup_location: 1
wccc: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Stripe Gateway: by WooCommerce – 4.1.13
WooCommerce: by Automattic – 3.5.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #16 - /shop/
Cart: #17 - /cart/
Checkout: #18 - /checkout/
My account: #19 - /my-account/
Terms and conditions: #223 - /test-page/

### Theme ###

Name: Storefront
Version: 2.4.2
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
---

WP 5.0.2 (diff testing site)

### WordPress Environment ###

WC Version: 3.5.3
Log Directory Writable: ✔
WP Version: 5.0.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.13.12
PHP Version: 7.2.4
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
LibreSSL/2.6.4

SUHOSIN Installed: –
MySQL Version: 5.7.22
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.3
WC Database Prefix: wp_
Total Database Size: 15.24MB
Database Data Size: 8.12MB
Database Index Size: 7.12MB

### Post Type Counts ###

attachment: 151
bookable_resource: 8
custom_css: 1
global_product_addon: 1
nav_menu_item: 13
page: 15
post: 5
product: 1006
product_variation: 89
revision: 51
scheduled-action: 42
shipping_package: 2
shop_coupon: 9
shop_order: 32
warranty_request: 1
wc_booking: 6
wc_membership_plan: 1
wc_product_tab: 2
wc_user_membership: 1

### Security ###

Secure connection (HTTPS): ❌
                    Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (12) ###

WooCommerce Advanced Shipping Packages: by Jeroen Sormani – 1.1.5
WooCommerce Bookings: by Automattic – 1.12.2
WooCommerce Composite Products: by SomewhereWarm – 3.15.0
WooCommerce Stripe Gateway: by WooCommerce – 4.1.13
WooCommerce Product Add-ons: by WooCommerce – 3.0.4 – 3.0.5 is available
WooCommerce Product Bundles: by SomewhereWarm – 5.9.0
WooCommerce Shipment Tracking: by WooCommerce – 1.6.12
WooCommerce UPS Shipping: by WooCommerce – 3.2.14
WooCommerce USPS Shipping: by WooCommerce – 4.4.19
WooCommerce Square: by WooCommerce – 1.0.34
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.12 – 3.0.13 is available
WooCommerce: by Automattic – 3.5.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #91 - /shop/
Cart: #92 - /cart/
Checkout: #93 - /checkout/
My account: #94 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Petshop
Version: 1.1.5
Author URL: https://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.4.2
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –
Template Overrides: –

</details>

**Comment by rrennick** [comment]
> Is this expected behavior?

It's the default behaviour for how web browsers handle the Enter key on a checkbox. Edit your profile in the WP dashboard, make some change to your profile then tab to one of the checkboxes and hit Enter. If you leave your profile, then load it again you'll see that the change you made has been saved.

**Comment by zhuzh1** [comment]
The issue I have been reporting (whether it is a browser default or not) may result in unintended order completion with incorrect shipping method and payment method (see the scenario I described in the ticket). Therefore, I don't know why this issue can be closed by arguing it is the "default behavior" of browswers. In fact, if it is the default behavior, extra effort should be made to "overwrite" it so that unintended order completions will not occur.

I strongly request to reopen this ticket, until the behavior is changed or A CONVINCING ARGUMENT IS MADE THAT THIS BEHAVIOR WOULD NOT CAUSE UNINTENDED ORDER COMPLETION (thus order cancellation etc)

**Comment by rodrigoprimo** [comment]
cc @woocommerce/woo-core-design for input on this issue

**Comment by willgorham** [comment]
I don't think the issue reported here is "how web browsers handle the Enter key on a checkbox," but that filling out any part of the form and pressing ENTER submits the form. 

Isn't this how basically all forms on the internet work?

**Comment by jameskoster** [comment]
> Isn't this how basically all forms on the internet work?

It's certainly the _default_ behaviour in my experience.

The problem with the issue that @zhuzh1 describes is that there's no way for WooCommerce to determine when a customer has selected the "correct" shipping or payment method. So to solve the issue it seems we'd need to disable the `Enter` key on the checkout entirely. But that creates a huge accessibility problem in that keyboard users wouldn't be able to check out.

Choosing the payment / shipping method is a customer action. We cannot account for mistakes made in that process. Pressing the `Enter` key is a universally recognised pattern for submitting a form. It's a commitment to placing the order, no different than clicking the "Place order" button. What I'm saying is that it seems unlikely that disabling the `Enter` key would magically make customers recognise their mistakes. More likely they'd just get frustrated and leave.

Disabling the `Enter` key is quite a simple modification @zhuzh1, a quick Google returns many options if you'd like to add this customisation to your store.

**Comment by rodrigoprimo** [comment]
Closing after input from the design team.
