### ISSUE TITLE
9 digit zip code for sales taxes

### ISSUE THREAD

**Issue by dmebersolesr** [woocommerce/woocommerce#22313]
I have read the woocommerce docs and could not find the answer to this question.

Washington State has 15,000+ sales tax locations each with different rates. The tables provided by the State utilize the 5 digit Zip+4. 
Is there a way to add and recognize the +4 digits to get the accurate sales tax to be collected? 

Thank you.

Dave E

**Comment by mikejolley** [comment]
Hi Dave,

We don't support Zip+4. I also believe it would be odd/difficult to expect customers to enter this themselves during checkout.

I'd recommend you look into the automated tax plugins such as Tax Jar to handle this for you. It will mean you don't need to manage tax rate tables in complex states.

Thanks
