### ISSUE TITLE
How to handle login session on front-end

### ISSUE THREAD

**Issue by appify-waheed** [woocommerce/woocommerce#22314]
Hi, I am new with woocommerce api's so please don't mind if i ask something stupid about this.
I am Integrating woocommerce api's in a mobile app which is react-native based and the problem is i need to handle user login like if user logged in first time then he shouldn't see the login screen untill he logout from app, Normally we do in react-native application token based authentication and we have some parameter along with token we only check the token validity before user showing login screen and if it valid we show some home screen or other screens but i am confused about woocommerce how can i handle this with woocommerce currently i am using this `dashboard/app_api/customers/check_login.php` to login the user and on every time user needs to login to access other screen.
Any help will be highly appreciated.

**Comment by mikejolley** [comment]
Hi,

Our API does not cover customer logins. The API is there only to manipulate/view your store's data and needs to only be accessed by a trusted user.

Thanks
