### ISSUE TITLE
Extra pargraph tags generated in store source

### ISSUE THREAD

**Issue by westsyde** [woocommerce/woocommerce#22326]
I've already written up some detailed posts on this bug so I've linked to them here.

https://github.com/WordPress/gutenberg/issues/13147
https://wordpress.org/support/topic/potential-store-page-bug/

**Comment by westsyde** [comment]
Awesome.. Thanks Ron..

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22334
