### ISSUE TITLE
Error 'Invalid tax class' when trying to update line_items meta_data via api

### ISSUE THREAD

**Issue by DaveClissold** [woocommerce/woocommerce#22323]
**Describe the bug**
I am trying to update the line_items meta_data for an order, but the api returns an error.
```
{
    "code": "order_item_product_invalid_tax_class",
    "message": "Invalid tax class",
    "data": {
        "status": 400
    }
}
```

**To Reproduce**
Am using RESTv3 with the following payload
https://www.audiovitamins.com/wp-json/wc/v3/orders/12469?consumer_key=**KEY**&consumer_secret=**SECRET**
```
{
	"id": 12469,
        "line_items": { 
          {
            "id": 3682,
           "product_id": 6597,
           "tax_class": "",
            "meta_data": [
              {
                "key": "PurchaseID",
                "value": "21291482"
              },
              {
                "key": "PurchaseCODE",
                "value": "tzcbVae5ta"
              }
            ]
          }
     }     
}
```
The tax codes are set to standard and I have followed the suggestion here and changed the tax classes and resaved the product - [https://github.com/woocommerce/woocommerce/issues/15287](https://github.com/woocommerce/woocommerce/issues/15287) 

**Expected behavior**
The api to return the order with updated meta_data for the appropriate line_item

**WordPress Environment**
Wordpress 5.02 & WooCommerce 3.5.3
```
`
### WordPress Environment ###

Home URL: https://www.audiovitamins.com
Site URL: https://www.audiovitamins.com
WC Version: 3.5.3
Log Directory Writable: ✔
WP Version: 5.0.2
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.33 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.24-0ubuntu0.16.04.1
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
```
</details>

**Comment by rrennick** [comment]
Github is for reporting bugs, not for requesting support. For support go to https://woocommerce.com or the support forums at https://wordpress.org.

The api documentation is at http://woocommerce.github.io/woocommerce-rest-api-docs/#update-an-order

A `PUT` of the following worked for me

```json
{"line_items":[{"id":93,"product_id":4255,"meta_data":[{"key":"PurchaseID","value":"21291482"},{"key":"PurchaseCODE","value":"tzcbVae5ta"}]}]}
```

**Comment by rrennick** [comment]
Closing this. Please re-open if you can provide details on reproducing this issue.
