### ISSUE TITLE
Multisite cart filled with products of second site

### ISSUE THREAD

**Issue by luflow** [woocommerce/woocommerce#22322]
**Describe the bug**
After introducing the mulitsite cart functionality in https://github.com/woocommerce/woocommerce/issues/12534 (PR https://github.com/woocommerce/woocommerce/pull/15513) there is now an issue with reading and writing the session data for the cart in the db.

In rare occasions the cart from another site in the multisite network is loaded because of the ambiguous session key `cart` in the serialized session data in the db which is not suffixed with the blog id like the `_woocommerce_persistent_cart_` meta.

**To Reproduce**
1. Set up a multisite with shared login, two sites in network, woocommerce installed on each
2. Create a product
3. Create a user account (e.g. User ID 1)
4. Log into first site
5. Put something into cart
6. Log in into second site -> session data is loaded based on customer id
session_key in `woocommerce_sessions` is looked up based on user id see
https://github.com/woocommerce/woocommerce/blob/13744479f14818f201caaae126b54b3ec96d901c/includes/class-wc-session-handler.php#L286
7. Cart displays products previously added on the other site – normally it should be empty.

Will provide a PR for this in some minutes.

**Comment by mikejolley** [comment]
Why is the sessions table shared? Shouldn't there be one per site?

**Comment by mikejolley** [comment]
I'm not sure why you'd see this occur unless the shared-user plugin is doing something here, but if you look at a clean multisite install, you'll see a session table for every site. 

`wp_*_woocommerce_sessions`

Since there is a table per store/site, this conflict cannot occur, and so the prefix and upgrade routine is not needed.

You may want to look into what is causing you to have a shared table instead.

Thanks

**Comment by luflow** [comment]
Hi Mike!

Yes indeed, we have a shared user base and it's not a clean multisite install. Thought the shared session table would be the default case - but thats totally ok for me, I can work around this in our installation.

Just a question at this point: Don't you think a filter for the persistent cart suffix would be easier to maintain for own implementations? If so I would at least take some of the commits and create a new pull request. Its duplicate code anyway. 

I mean this commit:
https://github.com/woocommerce/woocommerce/pull/22328/commits/02725bd86e11bc0e6153f2cb238b81ce65c80193

**Comment by mikejolley** [comment]
@luflow Can you explain why a filter would be needed if the suffix is already unique? Or am I missing something..?
