### ISSUE TITLE
Coupons - problem with exclude sale items

### ISSUE THREAD

**Issue by MartaPawlonka** [woocommerce/woocommerce#22321]
I set my coupon in this way:
http://wpde.sk/mp/ql6ks.png
http://wpde.sk/mp/q40q6.png
http://wpde.sk/mp/4lote.png

Products on sale: http://wpde.sk/mp/u5dnu.png

As I understand, the coupon should not work when the cart has an item on sale.
But when I add two normal items and one on sale, the coupon has been applied successfully - http://wpde.sk/mp/vib9n.png - why?

For one item on sale and three items on sale in the cart, this coupon is not working (so this is proper behavior): http://wpde.sk/mp/9jg7c.png, http://wpde.sk/mp/dnj52.png

**Comment by rrennick** [comment]
Coupons are applied per item. The $18 item is not on sale. 20% of $18 is $3.60.

**Comment by MartaPawlonka** [comment]
But I set this coupon to not working for items on sale. So why this coupon working for this situation:
I add two normal items and one on sale and the coupon has been applied successfully - http://wpde.sk/mp/vib9n.png

**Comment by rrennick** [comment]
Closing this. Please re-open if you can provide details on reproducing this issue.
