### ISSUE TITLE
Color Attribute Doesn't Save

### ISSUE THREAD

**Issue by thenadia33** [woocommerce/woocommerce#22336]
**Describe the bug**
When creating a new product or editing an existing product and adding color attribute - after hitting save and updating the product - the color does not save. Therefore it is impossible to add colors as an attribute to products. 

**To Reproduce**
1. Go to the wordpress dashboard and select "Products > add new" (alternatively you can also edit an existing product)
2. Scroll down to the product data module and select "attribute" - then add the color attribute - choose the colors - then hit save attribute. 
3. Update the product
4. Scroll back to product data - click on attributes - See error (color attribute did not save). Any variations created with color attributes also do not save.

**Expected behavior**
Expect the big to be fixed so we can add color attributes and variations. 

**Isolating the problem (mark completed items with an [x]):**
- this bug occurs with all products we tested and across multiple browsers and users.

**WordPress Environment**
Updated to the latest version of wordpress. Have also updated all plug ins and themes.
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by rrennick** [comment]
Deactivate all plugins except WooCommerce & switch to a default theme or Storefront. If you can still reproduce the issue then add your status report in a comment.

**Comment by kloon** [comment]
Color attributes are not standard WooCommerce functionality and likely added functionality from an extension. Please contact the developers of the extension for support on this, testing regular attributes works fine for me.
