### ISSUE TITLE
Unable to retain cart item price

### ISSUE THREAD

**Issue by vasikgreif** [woocommerce/woocommerce#22338]
I created a plugin, that allows user to add a free gift to the cart. For that I use `before_calculate_total` and `calculate_totals` actions, like this:

```php
add_action('woocommerce_before_calculate_totals', array($this, 'change_price'), 1);
add_action('woocommerce_calculate_totals', array($this, 'calculate_totals'), 1);

/**
* Change the free item price
* @param $cart
*/
function change_price($cart)
{

	foreach ($cart->get_cart() as $key => $item) {
		if (isset($item['_wfg_gift']) && $item['_wfg_gift'] == 1) {
			$item['data']->set_price(0);
		}
	}
}

/**
* Set the free gift price and quantity
*/
function calculate_totals($cart)	{
	if (WC()->cart->subtotal || WC()->cart->subtotal == 0) {
		foreach ($cart->get_cart() as $key => $value) {
			if (isset($value['_wfg_gift']) && $value['_wfg_gift'] == 1) {
				if (!isset($_POST['wfg_action']) && !$this->validate_gift($value['product_id'])) {
					WC()->cart->remove_cart_item($key);
					return;
				}
				$value['data']->set_price(0);
				WC()->cart->cart_contents[$key]['quantity'] = 1;
			}
		}
	}
}
```

Now, I created another plugin for setting discounts based on user group. That uses the `woocommerce_product_get_price` filter to adjust the price:

```php
add_filter( 'woocommerce_product_get_price', array( $this, 'maybe_apply_discount' ), 10, 2 );

/**
 * @param $price
 * @param $product \WC_Product
 *
 * @return float
 */
public function maybe_apply_discount( $price, $product ) {
	$_product            = new Product( $product->get_id(), $this->groups, $this->settings );
	$user                = new User( get_current_user_id(), $this->groups );
	$discounts           = $_product->get_discounts();
	$discount_percentage = 0;
	// Global
	foreach ( $discounts['global'] as $discount ) {
		if ( $user->is_group_member( $discount['group'] ) ) {
			$discount_percentage = $discount['discount'];
		}
	}
	// Category
	if ( ! empty( $discounts['category']['groups'] ) ) {
		foreach ( $discounts['category']['groups'] as $groups ) {
			foreach ( $groups as $group_id => $discount ) {
				if ( $user->is_group_member( $group_id ) ) {
					$discount_percentage = $discount;
				}
			}
		}
	}
	// Product
	if ( ! empty( $discounts['product']['groups'] ) ) {
		foreach ( $discounts['product']['groups'] as $group_id => $discount ) {
			if ( $user->is_group_member( $group_id ) ) {
				$discount_percentage = $discount;
			}
		}
	}
	if ( $discount_percentage ) {
		$price = round( ( ( 100 - $discount_percentage ) / 100 ) * $product->get_regular_price(), wc_get_rounding_precision() );
	}
	return $price;
}
```
When using the two plugins together, the free cart item price does not persist in cart and checkout. When debugging this, I found out that the `$product->get_price()` is called everywhere - in the cart table, order review table etc. 

That does not seem to make sense - I'd imagine that once the item is in cart, it should retain it's data - it does relate to the original product, but it does not make sense to recalculate the price from the product price everytime.

Am I missing something, or is this wrong design and it's going to change sometime?

**Comment by rrennick** [comment]
> Am I missing something, or is this wrong design and it's going to change sometime?

Github is for reporting bugs. For support contact https://woocommerce.com or the support forums https://wordpress.org/support/plugin/woocommerce .

**Comment by vasikgreif** [comment]
Well, if this is not my mistake, than I'd say it's a bug.

**Comment by Mobashir1995** [comment]
I am facing the same issue. I think It is a bug in the WooCommerce codebase. Can anyone please add a fix for this?

**Comment by NTShop** [comment]
I have code with similar functionality to add a free item to the cart, I'm using the "woocommerce_get_cart_item_from_session" hook to set the price to zero.
