### ISSUE TITLE
Some orders placed with fake paypal payments

### ISSUE THREAD

**Issue by gerasimone** [woocommerce/woocommerce#22343]
**Describe the bug**
I've found 3 fake orders placed in a site with woocommerce 3.4.7. In the apache log I've found some strange call made by the attacker's IP, for example:

[22/Dec/2018:07:16:28 +0100] "POST /?wc-ajax=update_order_review HTTP/2.0" 200 5740
[22/Dec/2018:07:16:34 +0100] "POST /?wc-ajax=checkout HTTP/2.0" 200 213
[22/Dec/2018:07:19:05 +0100] "POST /?wc-ajax=update_order_review HTTP/2.0" 200 5740
[22/Dec/2018:07:19:10 +0100] "POST /?wc-ajax=checkout HTTP/2.0" 200 623
[22/Dec/2018:07:21:36 +0100] "POST /?wc-ajax=get_refreshed_fragments HTTP/2.0" 200 164
[22/Dec/2018:07:21:40 +0100] "GET /checkout/order-received/134927/?key=wc_order_xxxxxxxxxxxxxx&utm_nooverride=1 HTTP/2.0" 200 35960
[22/Dec/2018:07:21:45 +0100] "GET /checkout/order-received/134927/?key=wc_order_xxxxxxxxxxxxxxx&utm_nooverride=1 HTTP/2.0" 200 35647
[22/Dec/2018:07:21:52 +0100] "GET /checkout/order-received/134927/?key=wc_order_xxxxxxxxxxxxxx&utm_nooverride=1 HTTP/2.0" 200 35647
And later some other calls to reset account password by mail

I've replaced the order with xxxxxxxxxxxxx

**To Reproduce**
I don't know how to reproduce, probably is a security issue

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by mikejolley** [comment]
The order won't progress from pending payment - the IPN callbacks won't validate the transaction. We cannot block someone attempting the above.

**Comment by gerasimone** [comment]
yeah, but in paypal account there aren't transaction in that day

**Comment by mikejolley** [comment]
Does not matter. The customer, attacker or legitimate, could have abandonned the payment process.

If you look at the order in the admin area, you should see it's PENDING. i.e. not paid. The order will cancel itself in due time, or you can remove it manually.

**Comment by gerasimone** [comment]
Hi mike,
probably my english is not perfect and I've not explained the issue the right way. The orders appears as payd, the attacker gained access to the digital content and probably downloaded it.
in wp_postmeta i have _payment_method=paypal, an empty _transaction_id, the post status is wc-processing.

**Comment by mikejolley** [comment]
If you're using PayPal IPN, in live mode, that shouldn't be possible because we do a post to PAYPAL which then tells your store if the payment actually happened.

Check the order again; view the order notes.
Check your paypal gateway is setup with the correct payment email and is not in sandbox mode.
Also confirm it's not PENDING PAYMENT (many users get these statuses confused).

Also we're assuming PayPal standard but you didn't post your system status so I cannot confirm.

**Comment by gerasimone** [comment]
In the paypal transaction logs i do not have track of post from paypal server to me, so the problem is not there. But what i can see from apache logs is that i have strange POST request sending data to:
"POST /?wc-ajax=checkout HTTP/2.0"
and many of those
"POST /?wc-ajax=get_refreshed_fragments HTTP/2.0"
is there any issues with get_refreshed_fragments?

**Comment by mikejolley** [comment]
Nope and those are unrelated to PayPal. Those are cache-busting mechanisms for the store pages. I don't think there is a PayPal issue here :)

If you need further advice on this you may want to post a support ticket.

Thanks
