### ISSUE TITLE
Variation issues - Back Orders created when "no back orders" is selected

### ISSUE THREAD

**Issue by DrNukeLear** [woocommerce/woocommerce#22340]
Variations which allow no back orders are creating back orders

To reproduce

1. Create a product with multiple variations (each with stock management and no back orders allowed).
2. Set one variation to have 1 stock and another to have 3 stock.
3. Order 3 items of the variation with a stock level of 1 and it's stock level will be reduced to -2.

**Expected behavior**
Stock level shouldn't be reduced below 0 and customer should be prevented from ordering more than the current stock level.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
You will need to provide more detailed steps to reproduce this. 

- When the variation with 1 in stock was selected I could not increase the quantity from 1.
- When the variation with 3 in stock was selected I could increase the quantity to 3. I then changed the dropdown to the 1-in-stock variation. Add to cart was blocked with a message that I could not order more than 1.

**Comment by rrennick** [comment]
Closing this one for lack of feedback. Please reopen if you can provide steps to reproduce this.
