### ISSUE TITLE
Product position within a woo category trought REST API

### ISSUE THREAD

**Issue by yulumadavid** [woocommerce/woocommerce#22356]
While working with the Woo REST API for 1,5 years now I was wondering why the position of a product (ordering) within a WooCommerce category is not in the object. What I would like to achieve:
Whenever a product gets an new ordering within our POS system we would like to communicate that position to WooCommerce.

**Describe the solution you'd like**
If the object Product - Categories properties within https://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties would be extended with a 'position' or 'order' this could fix this.

**Describe alternatives you've considered**
I can imagine that there also could be another object within the REST API to update the position of products within their categories.

**Comment by rrennick** [comment]
Products have an existing order field `menu_order` per http://woocommerce.github.io/woocommerce-rest-api-docs/#update-a-product which can be used to order any product query.

**Comment by yulumadavid** [comment]
@rrennick I don't understand how that would make me update the ordering for this product in all it's Woo categories ;-) Nor do I understand how it would change the menu_order because the product could be shown in different menu's right?

**Comment by yulumadavid** [comment]
Thanx, but than still I would love to order products per category like in the interface of Woo ;-)

**Comment by rrennick** [comment]
> I would love to order products per category like in the interface of Woo

Can you clarify where in the interface you are referring to?

**Comment by yulumadavid** [comment]
http://prntscr.com/m5een4

In this way I can sort products for the category 'Digitaal'

**Comment by rrennick** [comment]
Thanks for the screenshot. This looks like it is terminology confusion. If you want to add to create (or update) a product with one or more categories then the API currently supports that. The field is `categories`.

**Comment by yulumadavid** [comment]
Hi @rrennick. I know. 

I am looking for a way to **sort** the products withing their categories ;-) Ordering, sorting. The position within the category. Sorry if I use the wrong terms here ;-)

**Comment by rrennick** [comment]
In my previous comment I asked where you see them ordered per the issue's original description. The dropdown in your screenshot is a filter. It does not sort/order the products. 

The way you sort/order within a category is using the menu_order field & a custom query as I described in my previous responses.

**Comment by yulumadavid** [comment]
@rrennick I do not understand you, sorry.

Let's say we have a category named 'Shoes' and 'The red Shoe' is on position 5. All this within our POS system wich has 'Categories' and 'Products'.

I woul like to achieve that 'The red Shoe' is also on position 5 within the WooCommerce category 'Shoes'.

**Comment by rrennick** [comment]
> I woul like to achieve that 'The red Shoe' is also on position 5 within the WooCommerce category 'Shoes'.

You do that with the menu order field & a custom query on your category archive.

I'm closing this issue. Github is for reporting bugs. For assistance with customization use https://wordpress.org/support/plugin/woocommerce .

**Comment by yulumadavid** [comment]
Let me refrase:

What API call should we use to put 'The red Shoe' on position 5 in cat A and what API call should we use to put 'The red Shoe' on position 2 in cat B?

This question is specific about the API and not about customization of Woo ;-)

**Comment by rrennick** [comment]
> This question is specific about the API and not about customization of Woo ;-)

A site needs customization to implement the ordering you are describing. The menu_order field can be changed in the dashboard, via the api or through another plugin.
