### ISSUE TITLE
Woocommerce order template

### ISSUE THREAD

**Issue by masilat** [woocommerce/woocommerce#22358]
In the 3.4 version of woocommerce the customer processing order template body message was:
"Your order has been received and is now being processed. Your order details are shown below for your reference"

But in the 3.4 version that message changed with:
"Just to let you know — your payment has been confirmed, and order #%s is now being processed"
Even subject also changed.

I want to know it is an error or woocommerce changed it completely? Because In cash on delivery scenario people don't get payment in advance

**Comment by masilat** [comment]
Yes, I am.

**Comment by mikejolley** [comment]
Duplicate of https://github.com/woocommerce/woocommerce/issues/22037
