### ISSUE TITLE
Grouped product price is lowest priced variation in structured data

### ISSUE THREAD

**Issue by ntindicator** [woocommerce/woocommerce#22362]
**Is your feature request related to a problem? Please describe.**
The grouped product specifies 1 price in the structured data, which is the lowest priced variation. For me this doesn't work, as the way the grouped product is structured is so that a simple product is the main product, and a variable product is a supplementary product that is only displayed when the user clicks to display it. I want the price in the structured data to reflect the simple product, not the lowest priced variation. 

Another problem I have that is also related, is that I need to remove the breadcrumb from structured data, as it displays in search. I only want to use the breadcrumb on the site at this time, and use the page url in search.

**Describe the solution you'd like**
To be able to set a price for the grouped product itself, independently of how the child products are priced, or be able to do this by using the simple product price rather than a variation price.

**Describe alternatives you've considered**
I looked for functions to override, but I couldn't find anything that will change the structured data. I could modify the HTML, but this would only solve part of the problem. 

**Additional context**
<img width="405" alt="pricedata" src="https://user-images.githubusercontent.com/30362690/50814004-4239f100-136c-11e9-8a50-2d38b1372b30.png">

**Comment by rrennick** [comment]
Have you tried the `woocommerce_structured_data_product` filter?

**Comment by ntindicator** [comment]
Thanks, I hadn't tried that. It's fixed the problem for me.
