### ISSUE TITLE
Infinite loop in shop page when you use a theme that does not support WooCommerce

### ISSUE THREAD

**Issue by avnexter** [woocommerce/woocommerce#22379]
Bug is in file woocommerce/includes/class-wc-template-loader.php:460

To reproduce bug, add following code and go to shop page.

WP Theme should not support woocommerce.

`
add_action( 'woocommerce_product_query', function () {
    $p = get_posts( [
        'post_type' => 'post',
        'orderby' => 'rand',
        'posts_per_page' => 5
    ] );
} );
`

Line 460 starts an infinite “WC_Query::product_query” calls loop, if handler has at least one post request

`
add_action( 'pre_get_posts', array( wc()->query, 'product_query' ) );
`

**Comment by rrennick** [comment]
You should not call `get_posts()` (or any function that instantiates a `WP_Query` object) inside of the `woocommerce_product_query` (or `pre_get_posts`) hook. Here's some examples of things you might do in `woocommerce_product_query`  https://www.kathyisawesome.com/woocommerce-modifying-product-query/

Closing this as your code is creating the infinite loop.

**Comment by avnexter** [comment]
Why can't I make a request inside a "woocommerce_product_query" hook? 

For example, my "product filters" plugin loads project post (custom post type) inside "woocommerce_product_query" hook. Then it takes options from metadata and filters  main product query.

In addition, if you make a request in "the_content" hook, an bug will also appear.

`
add_action( 'the_content', function () { $p = get_posts( [ 'post_type' => 'post', 'orderby' => 'rand', 'posts_per_page' => 5 ] ); } );
`

**Comment by avnexter** [comment]
@rrennick Also an error may occur if post request is made inside any hook from class "WC_Shortcode_Products" [http://prntscr.com/m533db](http://prntscr.com/m533db)
