### ISSUE TITLE
Default attribute value lost when modifying the term slug

### ISSUE THREAD

**Issue by Chouby** [woocommerce/woocommerce#22382]
**Describe the bug**
If I modify the slug of a global attribute term, all variable products using this term as default value loose their default attribute value. Related: #4077

**To Reproduce**
1. Create a global attribute "Color" with 1 term "Red"
2. Create a variable product, add the attribute "Color" and its term "Red".
3. Create a variation and assign "Red" as the default form value
4. Go to the Attributes panel and modify the slug for "Red" from "red" to "red-test"
5. Go back to the Product page and check the default form value. It displays "No default Color...". 

**Expected behavior**
I was expecting that the default from value was being unchanged and was displaying "Red". 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WP 5.0.2 + WooCommerce 3.5.3 + Storefront.

**Comment by rrennick** [comment]
I was able to reproduce this in master.
