### ISSUE TITLE
How to change number of related products output unlimit number ?

### ISSUE THREAD

**Issue by shangdev** [woocommerce/woocommerce#22393]
Just like this example: [Change number of related products output](https://gist.github.com/woogists/6f7142aebbaa98a0cf24b04a59ca8bfa#file-wc-change-number-of-related-products-php), He does not work.

So i changed a way, He can work normally, but there is a problem:
```
add_filter( 'woocommerce_output_related_products_args', function ( $args ) {
	$args = [
		'posts_per_page' => 8,
		'columns'        => 3,
		'orderby'        => 'rand', // @codingStandardsIgnoreLine.
    ];

    return $args;
}, 20 );
```

If set 'posts_per_page' value is -1, I didn't get all the related product.
If i want get all the related product, How to do?

**Comment by rrennick** [comment]
Github is for reporting bugs. For customization use the support forums https://wordpress.org/support/plugin/woocommerce .
