### ISSUE TITLE
Cannot filter products by sku REST API

### ISSUE THREAD

**Issue by amirvenus** [woocommerce/woocommerce#22407]
**Describe the bug**

When using the `wp-json/wc/v3/`products endpoint, sku filter is not respected and is completely ignored. 

**To Reproduce**
1. Create a `wp-json/wc/v3/products` request 
2. set the following parameters:

per_page=100&stock_status=instock&status=publish&sku=YOURSKUHERE

3. All products matching the following parameters are returned:

per_page=100&stock_status=instock&status=publish

and `sku `filter is completely ignored. 

**Expected behavior**
Only product(s) matching the SKU should return. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
I'm not able to reproduce this in my install. A request to `https://ron.localhost/wp-json/wc/v3/products/?per_page=100&stock_status=instock&status=publish&sku=123-00851` returns only the product with that SKU.

Can you provide your system status report?

**Comment by mikejolley** [comment]
Working here also, and documented in http://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products so it's valid.

We'll need more details to look into this further. If you test with a rest API client such as Insomnia or Postman you can screenshot the request/response also to show it happening.

Thanks
