### ISSUE TITLE
Check if curl is active

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce#22406]
**Is your feature request related to a problem? Please describe.**

Had a customer where their SS was showing that curl was not working. They checked with Flywheel and curl is definitely enabled and working.

**Describe the solution you'd like**

Flywheel suggested we change how we check if cURL is active.

```
if (!extension_loaded('curl')) { 
echo 'failed'; 
} else { 
echo 'loaded'; 
}
```

instead of checking for `curl_init`.

**Additional context**

1679735-zen

**Comment by kloon** [comment]
See #22414
