### ISSUE TITLE
Issue #22208 still persists

### ISSUE THREAD

**Issue by Woralo** [woocommerce/woocommerce#22400]
This issue has been closed as it has been stated that the issue is solved with the Wordpress 5.0.3. release, however this issues still persists and the problem has not been solved.

I am still unable to import products and I am still seeing the same error saying I do not have permission to upload this file type. Happens on multiple domains with everything up to date and no Mime-check plugins enabled.

https://github.com/woocommerce/woocommerce/issues/22208

**Comment by mikejolley** [comment]
It's working my end after updating to 5.0.3. Certain you've upgraded? Did you try to apply any patches from 22208 which are no longer needed?

To test:

- Go to products, export. Export CSV
- Go to products, import, import CSV. No error.
- Rename CSV file to .txt. Import. No error.

Seems to be working my end after the patch, so it's either what I said above, or the file itself you're trying to import has a different mime type. You'd need to share that file to check, and it may be worth responding on trac if you're certain it's not fixed https://core.trac.wordpress.org/ticket/45615

This is not a WooCommerce bug. It's the checking in WordPress that (was) at fault.

Thanks cc @claudiulodro @kloon

**Comment by nitrokevin** [comment]
Im also on 5.0.3 and still seeing this issue

**Comment by rrennick** [comment]
> It's working my end after updating to 5.0.3.

The fix for this was punted to WP 5.1 - https://core.trac.wordpress.org/ticket/45615#comment:53

**Comment by claudiulodro** [comment]
That stuff punted to 5.1 seems to be for **additional** mime types. 

I see in my testing, [in the release notes](https://wordpress.org/news/2019/01/wordpress-5-0-3-maintenance-release/), and [in the repo](https://github.com/WordPress/WordPress/commit/ac1ff028151e9ff0490fa43b28b8698142347d09) that CSV uploading should be fixed in 5.0.3.

**Comment by rrennick** [comment]
Broken for me. I'll do some more investigation in the morning.

**Comment by rrennick** [comment]
> Broken for me.

It was my import file.

**Comment by paxxshoes** [comment]
Hi, I'm having a similar issue importing csv.   My version is  5.4.2, and woo states all plugins are up to date.  I previously imported a csv with products and it uploaded correctly.  I am using the same csv, with added products and the new additions are being seen as 'invalid'. The previous products are being acknowledge as duplicates and are correct.
