### ISSUE TITLE
Filter by attribute doesn't work with greek characters

### ISSUE THREAD

**Issue by plxrisa** [woocommerce/woocommerce#22403]
**Describe the bug**
When I add an attribute with greek slug and remove a term from this attribute from a product, it still shows up in the sidebar and I can still see this product if I filter by this term. I opened in August an issue about this #21026, but still there is no solution.
I tested again today in my localhost with WP 5.0.3 and WC 3.5.3.

@rodrigoprimo wrote this commit 4d2530e that solves this issue, but this wasn't added in any latest version, so the issue remains. 

**To Reproduce**
Please follow the procedure in my previous issue #21026.

**Screenshots**
Here you can see a short video of the issue.
https://www.useloom.com/share/92033b6536f043b1b7d04f32563e6713

**Expected behavior**
The terms must remove from sidebar if I remove them from the product (if there only one product with this attribute). If there are more products with this attribute, then the term must not show this product if someone filter it.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: http://localhost/woo
Site URL: http://localhost/woo
WC Version: 3.5.3
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: el
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.35 (Win64) PHP/7.2.10
PHP Version: 7.2.10
PHP Post Max Size: 8 MB
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.59.0
OpenSSL/1.1.0i

SUHOSIN Installed: –
MySQL Version: 5.7.23
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Συνολικό μέγεθος βάσης δεδομένων: 0.59MB
Μέγεθος βάσης δεδομένων: 0.50MB
Μέγεθος ευρετηρίου βάσης δεδομένων: 0.09MB
wp_woocommerce_sessions: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_api_keys: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rates: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Δεδομένα: 0.00MB + Index: 0.00MB
wp_commentmeta: Δεδομένα: 0.00MB + Index: 0.00MB
wp_comments: Δεδομένα: 0.00MB + Index: 0.01MB
wp_links: Δεδομένα: 0.00MB + Index: 0.00MB
wp_options: Δεδομένα: 0.49MB + Index: 0.02MB
wp_postmeta: Δεδομένα: 0.00MB + Index: 0.01MB
wp_posts: Δεδομένα: 0.01MB + Index: 0.01MB
wp_termmeta: Δεδομένα: 0.00MB + Index: 0.01MB
wp_terms: Δεδομένα: 0.00MB + Index: 0.01MB
wp_term_relationships: Δεδομένα: 0.00MB + Index: 0.00MB
wp_term_taxonomy: Δεδομένα: 0.00MB + Index: 0.00MB
wp_usermeta: Δεδομένα: 0.00MB + Index: 0.01MB
wp_users: Δεδομένα: 0.00MB + Index: 0.01MB
wp_wc_download_log: Δεδομένα: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Δεδομένα: 0.00MB + Index: 0.00MB

### Post Type Counts ###

page: 6
post: 2
product: 2

### Security ###

Secure connection (HTTPS): ❌
					Το κατάστημά σας δε χρησιμοποιεί HTTPS. Μάθετε περισσότερα σχετικά με το HTTPS και τα πιστοποιητικά SSL.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: από τον/την Automattic – 3.5.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Βάση καταστήματος: #5 - /index.php/shop/
Καλάθι: #6 - /index.php/cart/
Ταμείο: #7 - /index.php/checkout/
Ο λογαριασμός μου: #8 - /index.php/my-account/
Όροι και Προϋποθέσεις: ❌ Η σελίδα δεν ορίστηκε

### Theme ###

Name: Twenty Sixteen
Version: 1.8
Author URL: https://wordpress.org/
Child Theme: ❌ – Αν κάνετε μετατροπή του WooCommerce πάνω σε ένα γονικό θέμα που δεν δημιουργήσατε εσείς προσωπικά
τότε σας προτείνουμε να χρησιμοποιήσετε ένα θέμα απόγονο. Δείτε: Πως να δημιουργήσετε ένα θέμα απόγονο

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by rodrigoprimo** [comment]
I did a quick test, and it seems that the change that I implemented on #21074 was reverted by #21403. I'm not sure if that was intentional or not. @claudiulodro, could you please take a look?

**Comment by Chouby** [comment]
In my opinion, there is a flaw in accepting special characters in the slug of taxonomy attributes names. 

Indeed, the slug is used to register a taxonomy name. And it's not rare that WordPress applies the function `sanitize_key()` when manipulating taxonomy names. See for example: https://github.com/WordPress/WordPress/blob/5.0.3/wp-admin/includes/ajax-actions.php#L111 or https://github.com/WordPress/WordPress/blob/5.0.3/wp-admin/includes/ajax-actions.php#L942

Probably a lot of plugins are doing the same. So I would suggest not accepting anything but lowercase alphanumeric characters in the slug of the taxonomy attributes.

**Comment by mikejolley** [comment]
@claudiulodro ping

**Comment by claudiulodro** [comment]
#21074 introduced big bugs (see #21294), so it wouldn't work.

#21403 fixed the new bugs and appears to have solved half of the issue (filtering with Greek chars now works correctly).

`sanitize_key` looks like it may be a good solution, but we'll need to do further testing and investigation to see.

**Comment by mikejolley** [comment]
Moving to .5

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/22740 targetted at 3.6.0
