### ISSUE TITLE
Manully Add product in order problem

### ISSUE THREAD

**Issue by svenms** [woocommerce/woocommerce#22405]
The Add Products form in the Order information is not working on woocommerce 3.5.3
It seems they changed the form to a new one where you can search and enter the product and the quantity of items you want on the same form...but it is not adding any item to the order...
[Image 1 ](https://imgur.com/81Lfdx2)

I've rolled back woocommerce to the version 3.4.7, where the Add products form was just a line where you selected the item and it works fine.
 [Image 2](https://imgur.com/kYIZVgH
)

**Does anyone knows how to make it work again on the new version of Woocommerce?**
I've tried disabling all plugins, disabling Cloudflare and changing my Theme.

**Comment by rrennick** [comment]
I'm not able to reproduce this in my install with WP 5.0.3 & WC 3.5.3. Can you submit your system status report?

**Comment by svenms** [comment]
I created a new site and it is true, with those configurations in a new site is does work correctly.
So I started activating some things to check what broke it. I enabled all plugins, same Cloudflare conf and it works...but it does not in my site yet :/

Woocommece System Status (not working site): https://www.chilevapo.cl/wp-content/uploads/2019/01/not-working.txt

Woocommerce new site working: https://www.chilevapo.cl/wp-content/uploads/2019/01/1-working.txt

What would you recommend me to do ?

Best regards,

**Comment by rrennick** [comment]
Does your browser console have any errors?

**Comment by svenms** [comment]
No, no errors on the console: [Image](https://imgur.com/9n2zibE)
What I see different is the location of the quantity box, but I do not know if that does matter: [Image](https://imgur.com/M85kEO1)

Another thing that is different, is that in the working site, when you choose an item, automatically it appears a new line to choose another product down. But in my site it does not appears that new line.

**Comment by svenms** [comment]
In fact there are other differences at the CSS code:

Working site: [Image](https://imgur.com/cUrmD34)
Not working: [Image](https://imgur.com/ftT9vHr)

Best regads,

**Comment by rrennick** [comment]
I suggest you reinstall WP. Check it. If that doesn't fix it then try re-installing WC.

**Comment by svenms** [comment]
I did both, but nothing :c

**Comment by mikejolley** [comment]
- Clear browser caches and retry
- Try a different browser to rule out caching

It looks like you may be missing scripts, and/or those scripts are erroring. It is specific to your install as this is the only report and we're unable to reproduce the issue.

If the above does not work we would need to login and look at your install so you'll need to contact the helpdesk to allow that - we cannot provide this support over GitHub as it's public. 

Thanks
