### ISSUE TITLE
WC_Order get_shipping_methods->get_method_id doesn't return instance

### ISSUE THREAD

**Issue by hedqvist** [woocommerce/woocommerce#22413]
**Describe the bug**
If we have setup a shipping method flate_rate via settings.

On a WC_Order object we can fetch the shipping methods via ```$order->get_shipping_methods()```

If we do the following: ```$method_id = reset( $order->get_shipping_methods() )->get_method_id();```

That returns: flate_rate

Earlier this returned the instance of said shipping method, for example: flate_rate:2

**Expected behavior**
Expected to get ```flate_rate:2```

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
The instance part of the method name wasn't consistent across gateways FWIW - it was optional. So relying on this could cause issues. The dedicated field for instance ID is standard across all shipping methods.

You'll need to switch over to the get_instance_id() method in this case.

Thanks

**Comment by hedqvist** [comment]
This is what I thought,I will use get_instance_id() to grab the instance aswell! Thanks for the reply! :)
