### ISSUE TITLE
Woocommerce stripping out sms: code in short description

### ISSUE THREAD

**Issue by JonathanBaldwin8** [woocommerce/woocommerce#22428]
Hey team,

I have a mobile number that I would like to link using `<a` `href="+61400444444"></a>` code for iOS devices, and it works throughout the website, but every time I go to save it in the short description on the product pages woocommerce strips out the ‘sms:” code in the html, so it causes a 404 error.

Can you look into what may be causing this issue and how we can fix it?

Warm regards,
Jonathan.

**Comment by kloon** [comment]
Hi, you probably are using the visual mode when saving the short description. Ensure you have the editor set to Text http://cld.wthms.co/IUMLWO

**Comment by JonathanBaldwin8** [comment]
That's not true, I'm not using visual mode. I am only using the text mode and it is still stripping it out.

**Comment by JonathanBaldwin8** [comment]
Just checking in again to see if this ticket can be reopened.
