### ISSUE TITLE
Please make billing details, shipping address and contact phone number optional for downloadable virtual products.

### ISSUE THREAD

**Issue by songproducer** [woocommerce/woocommerce#22433]
Please make billing details, shipping address and contact phone number optional for downloadable virtual products.

Issue:
Woocommerce currently shows and requires billing, address and phone number details for downloadable products.

While billing details may be required for legacy payment providers to enforce identity requirements and protect against fraudulent transactions, crypto currencies work very differently. 

Proposal:
Please consider allowing the billing details, shipping address and contact phone number to be site-wide toggle options for downloadable virtual products. It will make digital commerce easier for both consumers and merchants.

**Comment by bruceleeroy18** [comment]
I agree. There is no need for personal information.

**Comment by songproducer** [comment]
I was recommended these plugins:
https://wordpress.org/plugins/woo-checkout-for-digital-goods/
https://wordpress.org/plugins/woo-checkout-field-editor-pro/

Which together provide a working temporary solution for virtual items, however it's not a permanent solution because I'm trying to sell both physical & virtual items and when someone tries to buy physical items, the address/name/email fields are optional.

**Comment by kloon** [comment]
There are a lot of tutorials and extensions available to enable this for you, the plugins you listed are some of them. This is not something we will add to WooCommerce core as some stores sell a mix of physical and digital products and want this information or some store selling just digital products want to collect this information for some reason.

**Comment by songproducer** [comment]
Here is the code that resolved it for me:

```
add_filter( 'woocommerce_checkout_fields' , 'bbloomer_simplify_checkout_virtual' );
 
function bbloomer_simplify_checkout_virtual( $fields ) {
     
    $only_virtual = true;
     
    foreach( WC()->cart->get_cart() as $cart_item_key => $cart_item ) {
        // Check if there are non-virtual products
        if ( ! $cart_item['data']->is_virtual() ) $only_virtual = false; 
    }
     
    if( $only_virtual ) {
				

       echo '
            <style>
                .woocommerce-billing-fields h3 {
                    display: none;
                }
            </style>
       ';
		
		unset($fields['billing']['billing_first_name']);
        unset($fields['billing']['billing_last_name']);
		unset($fields['billing']['billing_company']);
        unset($fields['billing']['billing_address_1']);
        unset($fields['billing']['billing_address_2']);
        unset($fields['billing']['billing_city']);
        unset($fields['billing']['billing_postcode']);
        unset($fields['billing']['billing_country']);
        unset($fields['billing']['billing_state']);
        unset($fields['billing']['billing_phone']);
        add_filter( 'woocommerce_enable_order_notes_field', '__return_false' );
    }
     
    return $fields;
}
```
