### ISSUE TITLE
Multisite, wocommerce only on the first site, php error

### ISSUE THREAD

**Issue by mpally** [woocommerce/woocommerce#22430]
**Describe the bug**
There is only a woocommerce installation at the first site. When I access the dashboard, this line gets written in the error log file:
2019/01/12 12:23:24 [error] 15125#15125: *929112 FastCGI sent in stderr: "PHP message: WordPress-Database-Error Table 'grischunshop.wp_873492_2_woocommerce_order_items' doesn't exist for SELECT order_item_type, order_item_id, order_id, order_item_name FROM wp_873492_2_woocommerce_order_items WHERE order_id = 2597 ORDER BY order_item_id; from require('wp-blog-header.php'), wp, WP->main, WP->parse_request, do_action_ref_array, WP_Hook->do_action, WP_Hook->apply_filters, rest_api_loaded, WP_REST_Server->serve_request, WP_REST_Server->dispatch, WC_REST_Network_Orders_V2_Controller->network_orders, WC_REST_CRUD_Controller->get_items, WC_REST_Orders_V2_Controller->prepare_object_for_response, WC_REST_Orders_V2_Controller->get_formatted_item_data, WC_Order->get_data, WC_Abstract_Order->get_items, WC_Data_Store->__call, Abstract_WC_Order_Data_Store_CPT->read_items" while reading response header from upstream, client: 83.76.157.213, server: www.grischun.shop, request: "GET /wp-json/wc/v2/orders/network?_wpnonce=fb0a57da22&network_orders=true&blog_id=2 HTTP/1.0", upstream: "fastcgi://unix:/var/run/php7-fpm-grischunshop.sock:", host: "www.grischun.shop", referrer: "https://www.grischun.shop/wp-admin/index.php"

The table grischunshop.wp_873492_2_woocommerce_order_items does not exist, because at site 2, there is no woocommerce installation.

Also the dashboard widget 'network orders' makes no sense for me, because there is only one woocommerce installation at tha main site 1.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WP 4.9.9 ; woocommerce v3.5.3 ; Kinsta hosting
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by kloon** [comment]
Can confirm, seems like there is no place in check when retrieving the blog ids to make sure WooCommerce is installed and active on the blog before fetching the data.

**Comment by kloon** [comment]
See #22439 for fix.
