### ISSUE TITLE
REST API and deletion of product image(s)

### ISSUE THREAD

**Issue by RagusaTech** [woocommerce/woocommerce#22447]
**Describe the bug**
Cannot delete a product image or product category image from the media library.

**To Reproduce**
- Create a new product (in a completely empty store in my case)
- Adds a new image as a product image from the media library, where the image is uploaded when I select it for the article.
- Publish the article.
- The picture is attached to the new article in the media library.

So far all good ...

Delete the item and delete from the trash so it is permanently removed.
The image is still in the media library!

It is the same if you instead do this via the REST API.

How to delete images from the media library in an automated way?

In my case, I have many hundred products that are updated via REST API several times a day. Without being able to delete images when an product is deleted, or when an product changes image etc, the media library will quickly become full of images that I do not use, which takes a lot of space and makes the media library difficult to overlook.

Is there any way to automatically delete images from the media library in connection with updating / deleting product (and product category) via REST API?

**Expected behavior**
The image in the media library should have been deleted while the article was deleted.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
> The image in the media library should have been deleted while the article was deleted.

Unfortunately that isn't the way WordPress handles media. Use the same steps with a post or page and you will see the same result. 

https://wordpress.org/plugins/dx-delete-attached-media/ might provide you with the behaviour you prefer.
