### ISSUE TITLE
REST API and image name for a product category

### ISSUE THREAD

**Issue by RagusaTech** [woocommerce/woocommerce#22449]
**Describe the bug**
The image name for a product category always seems to be the same as the file name from "src", not what is given in "name" when you insert / update a product category via the REST API.

**To Reproduce**

PUT/POST https://example.com/wp-json/wc/v3/products/categories/9
{
  "description": "All kinds of clothes.",
  "image": 
    {
      "src": "http://example.com/wordpress/wp-content/uploads/groupimg/Amino-acids.jpg",
      "name": "This is my name for this image",
      "alt": "And this is alt"
    }
}

results in name being set to "Amino-acids.jpg" and not "This is my name for this image".

"Alt" seems to be set to "And this is alt" though.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by RagusaTech** [comment]
If I use "title" (not documented?) instead of "name" it seems to work...

**Comment by rrennick** [comment]
I confirmed this in my dev install. A PUT of 

`{"id":62,"image":{"id":3481,"title":"Example Title"}}`

returns

```
  "image": {
    "id": 3481,
    "date_created": "2018-12-03T18:22:53",
    "date_created_gmt": "2018-12-03T18:22:53",
    "date_modified": "2019-01-16T10:58:08",
    "date_modified_gmt": "2019-01-16T14:58:08",
    "src": "https://ron.localhost/wp-content/uploads/2018/12/test.jpg",
    "name": "Example Title",
    "alt": ""
  },
```

**Comment by claudiosanches** [comment]
See #22553
