### ISSUE TITLE
Tax calculation problem when VAT exempt

### ISSUE THREAD

**Issue by roopemerikukka** [woocommerce/woocommerce#22456]
**Describe the bug**

I'm not quite sure if this is a bug but at least for me it seems like so.

The problem occurs when I set customer to be VAT exempt and then after payment I need to modify the order a bit and recalculate the order totals. I set the customer to be VAT exempt and I assume that it's the way to go as all of the available plugin also do it in that way. Now when I'm calculating the totals it uses `calculate_taxes` function [in here](https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-order.php#L1317-L1348). The problem is that when doing so, the function checks the VAT exempt state from the order:

```php
$is_vat_exempt = apply_filters( 'woocommerce_order_is_vat_exempt', 'yes' === $this->get_meta( 'is_vat_exempt' ), $this );
```

I can change the status by using that filter given but I would assume that the default value wouldn't come from the order but from the customer.

The situation why I'm doing this is that I need to programmatically split the order in two separate orders after the payment and then re-calculate the prices of both orders.

**To Reproduce**
1. Install WooCommerce and Storefront
2. Create test product with 24% (or any other tax rate)
3. Add these to functions.php:

```php
add_action( 'init', function(){
  global $woocommerce;
  if( $woocommerce->customer ) {
    $woocommerce->customer->set_is_vat_exempt( true );
  }
});

add_action( 'woocommerce_thankyou', function( $order_id ) {
  $order = wc_get_order( $order_id );
  // Do some editing to the order here.
  $order->calculate_totals();
});
```
3. Buy the test product
4. See error with prices in admin

**Screenshots**

---

![screenshot 2019-01-15 at 11 38 34](https://user-images.githubusercontent.com/1453463/51171985-ebc43980-18ba-11e9-8d5d-51503249f232.png)

---

![screenshot 2019-01-15 at 11 38 41](https://user-images.githubusercontent.com/1453463/51171997-f41c7480-18ba-11e9-9cc9-e36759804ef2.png)

---

![screenshot 2019-01-15 at 11 39 04](https://user-images.githubusercontent.com/1453463/51172069-16ae8d80-18bb-11e9-8605-eede2c8f82e4.png)

---

![screenshot 2019-01-15 at 11 39 13](https://user-images.githubusercontent.com/1453463/51172076-1910e780-18bb-11e9-9ebe-29b3e0f9dace.png)

---

![screenshot 2019-01-15 at 11 39 26](https://user-images.githubusercontent.com/1453463/51172080-1ca46e80-18bb-11e9-9b4e-8d67daa88540.png)

---

![screenshot 2019-01-15 at 11 39 37](https://user-images.githubusercontent.com/1453463/51172084-1f9f5f00-18bb-11e9-8df5-fc52e336e6a8.png)

---

![screenshot 2019-01-15 at 11 39 46](https://user-images.githubusercontent.com/1453463/51172089-2201b900-18bb-11e9-9b64-a663a6108343.png)

---

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

Home URL: http://woo-test.local
Site URL: http://woo-test.local
WC Version: 3.5.3
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.12.1
PHP Version: 7.1.16 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 15 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.59.0
OpenSSL/1.0.2n

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.9-MariaDB-1:10.3.9+maria~bionic
Max Upload Size: 15 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from https://dev.maxmind.com/geoip/geoip2/geolite2/ to the path: . Scroll down to "Downloads" and download the "MaxMind DB binary
gzipped" file next to "GeoLite2 Country". Please remember to uncompress GeoLite2-Country_xxxxxxxx.tar.gz and upload the GeoLite2-Country.mmdb file only.

Total Database Size: 2.91MB
Database Data Size: 2.06MB
Database Index Size: 0.85MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.48MB + Index: 0.02MB
wp_postmeta: Data: 0.06MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

page: 5
post: 2
product: 1
shop_order: 7

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.5.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.4.2
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by kloon** [comment]
Thanks for report. Added a fix in #22458, what it will do is when you place an order via checkout it will set the is_vat_exempt status of the order to that of the customer at time of checkout, that will result in the orders honoring the VAT exempt status when calculations are done after the order was created for some reason like in yours.

As a workaround for now you can manually set the VAT status of the order to that of the customer in your code with something like below, please note I have not tested the code.

```
$order = wc_get_order( $order_id );
$customer = new WC_Customer( $order->get_customer_id() );
$customer_vat_exempt = $customer->get_is_vat_exempt();
$order->set_meta( 'is_vat_exempt', $customer_vat_exempt );
// Do some editing to the order here.
$order->$order->calculate_totals();
```
