### ISSUE TITLE
Trigger 'updated_cart_totals' JS event when cart is emptied

### ISSUE THREAD

**Issue by mattLummus** [woocommerce/woocommerce#22453]
**Is your feature request related to a problem? Please describe.**
We use the 'updated_cart_totals' JS event to do some things on the cart page. One small issue is that this event is not triggered when the last item is removed from the cart. I think logically it make sense that changing the cart total from any dollar amount to $0.00 is still an update to the cart total and is part of the reason I assumed this event would fire here.

**Two Disclaimers:**
- Please correct me if this should already be firing and is specific to our codebase, and I will retest on a vanilla install, though from what I've seen in cart.js this lines up with my understanding of the code. (I will want to retest later on a fresh install anyways but wanted to get this issue written in the meantime)
- This was more of a gotcha that took up some time to troubleshoot/investigate than something we absolutely can't work around.

**Describe the solution you'd like**
When the last item is removed from the cart, trigger the 'updated_cart_totals' event as otherwise would happen on cart updates.

**Describe alternatives you've considered**
- We can listen for 'updated_wc_div' on the frontend and do our own checks.

**Additional context**
Using a /cart url with [woocommerce_cart] to render this page.

**Comment by waltercruz** [comment]
wc_cart_emptied is not available on woocommerce 3.5.6 yet. When it will be available?

**Comment by cbernard** [comment]
Same question as @waltercruz - When will it be available ?
