### ISSUE TITLE
Phone number field needs Parameters set for SMS

### ISSUE THREAD

**Issue by Mondueo1** [woocommerce/woocommerce#22454]
We are trying to use a SMS service to text customers when their order is ready, but the phone field is a free for all...Anything goes.  So customers put in their numbers in any format they please.  SMS can not be sent if the Customer enters the wrong phone format. There needs to be a standard in order to send SMS. Can you add an option to force a phone format or set one?   Currently anything goes in your field, 1234567890, 123-456-7890, 123-4567, and so one. There needs to be rules in place for this.  Area codes and country codes all need to be handled. Currently we are using a customized PHP but ideally would like to see this integrated in WC.  

Here is a example of what the field might look like blank:
+1(xxx) xxx-xxxx

**Comment by kloon** [comment]
Your application should have helper functions that converts the number in the correct format that your SMS gateway expects. We have this present in official WooCommerce SMS extensions. Have a look at this Stack Exchange for an example https://stackoverflow.com/questions/4708248/formatting-phone-numbers-in-php

Putting too many restrictions on a field makes it more difficult for a customer to checkout, which can result in lost sales for a store. Also, each country has a different way of how they write phone numbers which complicates it even more, that is why I would rather have the code that makes use of the phone number to format it correctly the way it needs to be.

Another example of formatting the phone number in WooCommerce is the PayPal gateway where it strips out all spaces, dots, dashes and brackets https://github.com/woocommerce/woocommerce/blob/d0491072e8a7d0a4535db0ec2bae4a6d43ff64fd/includes/gateways/paypal/includes/class-wc-gateway-paypal-request.php#L204
