### ISSUE TITLE
Json-ld product markup when using shortcodes

### ISSUE THREAD

**Issue by SvenJob** [woocommerce/woocommerce#22462]
Hey everyone, i try to use the woocommerce product shortcode to display a product category in a blog post. It works like expected the selected category is shown in the blog post. Unfortunately the Json-ld Product Markup is not generated on this Page.

I try it in some variation and it seem to be that the woocommerce shortcode does not support generating this json-ld meta data. Cann somebody confirm this behavior or is it something that i  can fix?

**Comment by rrennick** [comment]
I answered this question in slack after seeing it in Slack but before seeing this issue. As I explained there, The json+ld data is added to single product & product archive pages.
