### ISSUE TITLE
No address selected error at checkout

### ISSUE THREAD

**Issue by purtungsten** [woocommerce/woocommerce#22463]
<img width="1208" alt="screen shot 2019-01-15 at 9 35 11 am" src="https://user-images.githubusercontent.com/46716300/51187197-481e5d80-18a9-11e9-9448-b0eeca1f2627.png">
I have the latest version of Woocommerce, and when users are on the checkout page and fill in all the required information and click "place order", an error saying "no address selected" occurs.

**Comment by mikejolley** [comment]
The error states no shipping METHOD has been selected. It's not reffering to the address. You need to setup some shipping methods in WC > Settings > Shipping.

https://docs.woocommerce.com/document/setting-up-shipping-zones/

**Comment by purtungsten** [comment]
Thanks!
