### ISSUE TITLE
query() function not found in WC_Data_Store

### ISSUE THREAD

**Issue by danielStanciuCG** [woocommerce/woocommerce#22460]
**Describe the bug**
Hello,

I've tried using the get_products() funtion from the WC_Product_Query class but it kept returning an empty array even though my queries were perfectly fine.

I then looked at the source code of the get_products() function. It's trying to call a method called query() from WC_Data_Store which does not exist.

In addition, there's an unhandled exception in get_products().

**To Reproduce**
1. Open class-wc-data-store.php
2. Search for query() function

**Screenshot**
![image](https://user-images.githubusercontent.com/33576064/51180884-8de72000-18c1-11e9-807d-685b4a227561.png)

**Expected behavior**
It should query the database.

WooCommerce version: 3.5.3

**Comment by mikejolley** [comment]
Hi.

The hinting in your editor is not looking in the correct place. `wc_data_store::load` is returning the product data store, which itself has a `query` method found here: 

https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-data-store-cpt.php#L1794

So it's querying, but whatever query you're running is returning no results.

Thanks

**Comment by danielStanciuCG** [comment]
> Hi.
> 
> The hinting in your editor is not looking in the correct place. `wc_data_store::load` is returning the product data store, which itself has a `query` method found here:
> 
> https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-data-store-cpt.php#L1794
> 
> So it's querying, but whatever query you're running is returning no results.
> 
> Thanks

Oh ok, I see, thanks for your quick reply!
