### ISSUE TITLE
WooCommerce template hierarchy diagram

### ISSUE THREAD

**Issue by rizkysyazuli** [woocommerce/woocommerce#22465]
I'm looking to design a theme for WooCommerce, but I need some sort of reference where i can see a list of all the available pages. Something like [WordPress' template hierarchy](https://developer.wordpress.org/themes/basics/template-hierarchy/#visual-overview) diagram.

I've been looking around with no result. So I assume you guys don't have it.

I do believe a similar diagram in your docs would be very helpful for theme designers. I'd gladly do it, if only I understand how the files in the "templates" folder is organized.

**Comment by kloon** [comment]
While WooCommerce's template system is based on the WP one it is not the same, it has some similarities but we always suggest theme authors not override the WooCommerce core templates as it brings in complications for theme users when WooCommerce core updates a template.

We do have a [Theme Developer handbook](https://docs.woocommerce.com/document/woocommerce-theme-developer-handbook/) which has some best practices and details on how to add WooCommerce compatibility to your theme, and also be sure to read the Theming section on the sidebar of our [GitHub Wiki](https://github.com/woocommerce/woocommerce/wiki) for more details on how to add WooCommerce compatibility to your theme.
