### ISSUE TITLE
Line items not adding up to subtotal after percent discount

### ISSUE THREAD

**Issue by victorwtorres** [woocommerce/woocommerce#22472]
**Describe the bug**
There is an issue when applying a percentage discount coupon. I have experienced this when having a product in my cart, with the quantity of 2 or more. I have looked through the open/close issues and have seen a lot of similar issues, but nothing that exactly is the same. 
This is a problem because we have certain things that validate orders, and they have failed because (price * quantity != subtotal).

**Screenshots using 2% discount**
![screenshot_2019-01-15_17-08-49](https://user-images.githubusercontent.com/8550162/51220478-41640a80-18ea-11e9-9230-0dabc805112c.png)

**Expected behavior**
I'm not sure what the expected behavior should be. Currently I believe this is how it works, though I may be wrong and it might just be some different rounding issue.
1. Take percent discount from line items price and do some rounding.
2. Check if there is any coupon remainder left, in this case since its 1 cent add it to the line items subtotal.

This makes sense, but we are experiencing issues because of it. I am not sure of how to correctly handle this, as there is no perfect solution. A possible fix for us is to comment out this line https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-discounts.php#L395 and the user ends up not getting 100% of the discount.

**Comment by mikejolley** [comment]
It's not possible to resolve this one because items are not discounted per item, they are discounted per line. The line discount may not round nicely as you're hoping.

e.g. If I have a $10 discount across 3 items, the discount per item is `3.3333333333...`. Rounding that would either cause more than $10 discount, or less than $10 discount.

If running validation, validate the line prices, not the line / qty. 

Hope this makes some sense.

Thanks

**Comment by victorwtorres** [comment]
It makes sense, but the problem still exists. We use zapier to create invoices in quickbooks, and thats where we run into the problem

line_amount: 14.15
line_item_qty:	2
line_item_price: 7.08

This is from the order that experienced us issues, and the error was `Amount is not equal to UnitPrice * Qty. Supplied value: 14.15`. If nothing can be done on woocommerces end, I guess I should talk to zapier?

**Comment by mikejolley** [comment]
I doubt much can be done zapier side? 

If quickbooks cannot ignore line price validation, cannot support higher precision, your only option would be to send the item price same as the line price and send qty 1 so this never happens.
