### ISSUE TITLE
Option to disable hold stock time limit for manual order pending payment

### ISSUE THREAD

**Issue by therealgilles** [woocommerce/woocommerce#22473]
**Is your feature request related to a problem? Please describe.**
I have the hold stock time limit set to 10 minutes, but I do not want customers to keep products in their cart for longer than this. Yet, when I create a manual order for a customer, I want to leave more time for the customer to pay the invoice (maybe 24 hours).

**Describe the solution you'd like**
It would be great if there was an option to disable the hold stock time limit for manual orders pending payment.

**Describe alternatives you've considered**
My current solution is to disable the Hold Stock time limit every time I have manual order pending payment. But it's not a very workable solution.

**Comment by kloon** [comment]
Yes, as per the code there is already a check in place for this. Closing, but can reopen if you have a working example of this code not working as it should.
