### ISSUE TITLE
Provide a way to increase/decrease stock when editing product instead of setting a specific inventory count

### ISSUE THREAD

**Issue by therealgilles** [woocommerce/woocommerce#22474]
**Is your feature request related to a problem? Please describe.**
When the store is open and customers are able to buy products, it would be great to have a way to increase/decrease inventory instead of having to set a specific number when editing a product. The best way would be able to increase/decrease by any value.

**Describe the solution you'd like**
Add a way to increase/decrease stock when editing a product or its variations.

**Describe alternatives you've considered**
There is no way right now to avoid race conditions with ongoing purchases.

**Comment by kloon** [comment]
See #22475
