### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function get_attribute() on string

### ISSUE THREAD

**Issue by borombombero** [woocommerce/woocommerce#22482]
Hi,
I'm having errors 500 everytime in many URL. According to the registry log in my server it is a programming issue, Attached you have a screenshot with the log information for that error.

I do not know why in some pages it works and in others it fails, but that log registry indicates that something in the content of each one causes something different in the execution.

There are many URLs that give me that error 500. And every time I make a new post (Woo product) the problem repeats itself after a certain time.

I know the problem is when trying to get some values from woocommerce atributes. Products with issue has a lot of shortcodes (wpsm_custom_meta)

### **Steps to reproduce the behavior:**
Just creating a new Woo product and after some hours o days 
http://prntscr.com/m87kcy

![image](https://user-images.githubusercontent.com/7613516/51289556-f688e680-1a00-11e9-8dec-b1474a28e93a.png)

### Isolating the problem:
As a curiosity. 
- [x] The following is very curious. To fix that problem I edit the Woocommerce product. Next (in HTML mode) I cut (Ctrl + X) all the content and I save it. Now and without body content that URL is shown prefectly. After that I paste (always in HTML mode a) the content previously cut and inexplicably sometimes not always the URL is loaded without further problems.

That would be fine but what happens is that after several hours (sometimes more than a day) error 500 reappears. I can use this fix with any URL that fails in error 500 and the failure reoccurs after several hours, sometimes after 1 or 2 days.
- [x] I have done everything. I have deleted all the plugins and reinstalled. I have activated the parent theme, other childs, etc, etc. and the problem continues. However **when I activate the themes that WordPress brings by default that problem does not appear**.
- [x] I can reproduce this bug consistently using the steps above.

### last answer from theme developer:

> Product with issue has a lot of wpsm_custom_meta shortcodes.

**Seriously, I can not have many calls to attributes in a row?**

### WordPress Environment
<details>
WooCommerce > System Status in WordPress admin

2019-01-17T00:51:48+00:00 CRITICAL Uncaught Error: Call to a member function get_attribute() on string in /var/www/vhosts/mydomain.com/httpdocs/wp-content/themes/rehub/shortcodes/shortcodes.php:3533
Stack trace:
#0 /var/www/vhosts/mydomain.com/httpdocs/wp-includes/shortcodes.php(319): wpsm_get_custom_value(Array, '', 'wpsm_custom_met...')
#1 [internal function]: do_shortcode_tag(Array)
#2 /var/www/vhosts/mydomain.com/httpdocs/wp-includes/shortcodes.php(197): preg_replace_callback('/\\[(\\[?)(wpsm_b...', 'do_shortcode_ta...', '\nLo primero que...')
#3 /var/www/vhosts/mydomain.com/httpdocs/wp-content/themes/rehub/shortcodes/shortcodes.php(348): do_shortcode('\nLo primero que...')
#4 /var/www/vhosts/mydomain.com/httpdocs/wp-includes/shortcodes.php(319): wpsm_titlebox_shortcode(Array, '\nLo primero que...', 'wpsm_titlebox')
#5 [internal function]: do_shortcode_tag(Array)
#6 /var/www/vhosts/mydomain.com/httpdocs/wp-includes/shortcodes.php(197): preg_replace_callback('/\\[(\\[?)(amazon...', 'do_s en /var/www/vhosts/mydomain.com/httpdocs/wp-content/themes/rehub/shortcodes/shortcodes.php en la línea 3533
```

**Comment by peterfabian** [comment]
Hi, 

As you mentioned, 
> when I activate the themes that WordPress brings by default that problem does not appear.
so I assume this is caused by some code in the theme you are using. I would suggest to check with the theme developer. 

Thanks.

**Comment by borombombero** [comment]
Hi,

I already checked with the theme developer your answer is always the same

> Product with issue has a lot of wpsm_custom_meta shortcodes.

So I know that in the body text I have many theme's shortcodes calling to parse product attributes, however I can't believe having many calls to attributes in a row may crash the post to error 500

I trust theme developer. The theme developer must be a really good programmer (50+K selled themes) that's why I wanted to check here is someone in the community has or had the same issue with Rehub theme using its shortcodes (wpsm_custom_meta.....) or with another theme when call for so many attributes in a single paragraph of body text

Thanks,

**Comment by peterfabian** [comment]
I'm sorry, but we don't have the theme code, we don't know how it's using WooCommerce, so it's impossible for us to even guess where the problem might be. `wpsm_custom_meta` is not a WooCommerce shortcode, so we have no idea what it is doing, therefore we can't really tell why it's failing. 

I'm not saying the theme developer is not a good one, but no code is bug-free, perhaps not even ReHub. Additionally, the type of error you see does suggest that there's a bug in the code.

Does this happen only with WooProducts or if you create a page/post with the same amount of `wpsm_custom_meta` shortcodes, does it cause a similar issue? I've created a product with description having 50 shortcodes (the WC ones, like `[featured_products]` or `[sale_products]`) and it seems to work ok so far (although a bit slow).

Also, it seems like other have encountered a similar error with ReHub: https://themeforest.net/comments/19488865
