### ISSUE TITLE
Localisation for country Latvia

### ISSUE THREAD

**Issue by guntarspolisasteris** [woocommerce/woocommerce#22485]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by guntarspolisasteris** [comment]
Please remove "State" field for country LATVIA

**Comment by peterfabian** [comment]
Hi, according to https://en.wikipedia.org/wiki/Address#Latvia, the municipality is an optional part of the address and e.g. also http://www.pasts.lv/lv/uzzinas/adrese/ list their address with Municipality. 

Therefore, my suggestion would be to make the field optional, but still displayed.

In case you would like to hide it in your shop, I suggest using filter `woocommerce_states` to add an empty array for 'LV' country code.
