### ISSUE TITLE
woocommerce_new_order hook is not called

### ISSUE THREAD

**Issue by ethan-tqa** [woocommerce/woocommerce#22484]
**Describe the bug**
As I am developing a plugin, I wanted to hook into the event woocommerce_new_order, in order to run additional actions after an order is created in the admin panel. However, the hook is never fired. After stepping through the code, I found that WC_Order_Data_Store_CPT::create was not called, because the 
`if ( $this->get_id() )` condition inside WC_Order::save is always true. This appears to be caused by the auto-draft feature of Wordpress.

**To Reproduce**
1. Set breakpoint in class-wc-order-data-store-cpt, function create( &$order )
2. This breakpoint never hits when a new order is created on the admin panel

**Screenshots**
No screenshots needed.

**Expected behavior**
The hook woocommerce_new_order is fired.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Home URL: http://localhost/wordpress
Site URL: http://localhost/wordpress
WC Version: 3.5.3
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –
```
</details>

**Comment by mikejolley** [comment]
This won't be possible, because as you identified, orders are not created by WC, but as drafts in WP. 

There are ways around this. If you want to target only admin orders, use the hooks WP fires when new posts are created.

Or, you can target save events instead of create events. e.g. woocommerce_before_order_object_save

Hope that helps.

**Comment by ethan-tqa** [comment]
Sounds pretty strange to me, if it is not possible, then what is the purpose of WC_Order_Data_Store_CPT::create and the hook woocommerce_new_order?
