### ISSUE TITLE
VAT is calculated from the wrong price when partially refunding order

### ISSUE THREAD

**Issue by Eptick** [woocommerce/woocommerce#22496]
**Describe the bug**
The vat displayed is wrong when refunding a order partially. It is still calculated from item prices before the refund.

**To Reproduce**
1. Put an item in the card
2. Apply a discount percentage coupon
3. buy and pay the product
4. refund partially 
5. The VAT displayed is calculated from

**Screenshots**
![image](https://user-images.githubusercontent.com/8373912/51383772-a30abb80-1b1a-11e9-8b2d-fe20cfa3f152.png)

**Expected behavior**
It should recalculate the tax after the refund, because our invoice does not match the tax displayed.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Note: This is a local enviroment used for testing, it also consistently breaks on a live server.
<details>
`
### WordPress Environment ###

Home URL: http://localhost
Site URL: http://localhost
WC Version: 3.4.5
Log Directory Writable: ✔
WP Version: ❌ 4.9.9 - There is a newer version of WordPress available (5.0.3)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.37 (Win32) OpenSSL/1.1.1a PHP/7.3.0
PHP Version: 7.3.0
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.1.1a

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.37-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.5
WC Database Prefix: ecg_
MaxMind GeoIP Database: ✔
Total Database Size: 2.91MB
Database Data Size: 2.06MB
Database Index Size: 0.85MB
ecg_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
ecg_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
ecg_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
ecg_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
ecg_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
ecg_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
ecg_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
ecg_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
ecg_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
ecg_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
ecg_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
ecg_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
ecg_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
ecg_woocommerce_log: Data: 0.02MB + Index: 0.02MB
ecg_commentmeta: Data: 0.02MB + Index: 0.03MB
ecg_comments: Data: 0.02MB + Index: 0.09MB
ecg_links: Data: 0.02MB + Index: 0.02MB
ecg_options: Data: 1.48MB + Index: 0.02MB
ecg_postmeta: Data: 0.06MB + Index: 0.03MB
ecg_posts: Data: 0.02MB + Index: 0.06MB
ecg_termmeta: Data: 0.02MB + Index: 0.03MB
ecg_terms: Data: 0.02MB + Index: 0.03MB
ecg_term_relationships: Data: 0.02MB + Index: 0.02MB
ecg_term_taxonomy: Data: 0.02MB + Index: 0.03MB
ecg_usermeta: Data: 0.02MB + Index: 0.03MB
ecg_users: Data: 0.02MB + Index: 0.05MB
ecg_wc_download_log: Data: 0.02MB + Index: 0.03MB
ecg_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

page: 6
post: 2
product: 1
shop_coupon: 1
shop_order: 5
shop_order_refund: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (4) ###

Classic Editor: by WordPress Contributors – 1.3
Klarna Payments for WooCommerce: by krokedil
klarna
automattic – 1.6.3

WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.6
WooCommerce: by Automattic – 3.4.5 – 3.5.3 is available

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 1.7 – 2.0 is available
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by Eptick** [comment]
![image](https://user-images.githubusercontent.com/8373912/51393310-ad877e00-1b37-11e9-8956-83757cfcd3e3.png)
Image from the latest woocommerce version

**Comment by rrennick** [comment]
@Eptick Can you provide your tax related settings?

**Comment by Eptick** [comment]
![image](https://user-images.githubusercontent.com/8373912/52407042-7c172800-2acf-11e9-85ba-4495420b60d3.png)
![image](https://user-images.githubusercontent.com/8373912/52407062-86d1bd00-2acf-11e9-98aa-9d78a96f0a05.png)
Anything else?

**Comment by mikejolley** [comment]
I can see whats happened here.

If you look at the order, you'll notice the taxes are calculated per line item. When you go to refund you'll also notice something like this:

![edit order test wordpress 2019-02-22 13-18-53](https://user-images.githubusercontent.com/90977/53245025-79f2c300-36a4-11e9-9b4d-b8dbaa42584f.png)

If you refund an item in the area circled you can choose the number of items to refund and/or update the taxes manually. This would result in a correct total.

If however you refund via the bottom "Refund amount" box exclusively, it cannot recalulcate the taxes because it doesn't know what items have been refunded, or what proportion of those taxes are no longer applicable. The order as a whole doesn't have taxes, the items do.

I'm going to push a commit to make that box read-only so this cannot happen.

**Comment by Eptick** [comment]
That makes perfect sense. Thank you so much.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22820
