### ISSUE TITLE
WooCommerce Taco Test Plugin failed activation

### ISSUE THREAD

**Issue by rickmgithub** [woocommerce/woocommerce#22491]
**Describe the bug**
Error "activating" plugin during bookings "Taco" test

**To Reproduce**
1) Downloaded link provided on https://woosupport.wordpress.com/2019/01/11/bookings-taco-release-call-for-testing/
2) Imported to richardmidson.com via Calypso (not wp-admin).
3) Clicked to "activate"
3) System reported:
Fatal error: Uncaught Error: Class 'WC_Admin_Notices' not found in /wpcom-155316181/wp-content/plugins/woocommerce-bookings/woocommerce-bookings.php:68 Stack trace: #0 /wordpress/core/5.0.3/wp-includes/class-wp-hook.php(286): woocommerce_bookings_activate('') #1 /wordpress/core/5.0.3/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #2 /wordpress/core/5.0.3/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #3 /wordpress/core/5.0.3/wp-admin/plugins.php(174): do_action('activate_woocom...') #4 {main} thrown in /wpcom-155316181/wp-content/plugins/woocommerce-bookings/woocommerce-bookings.php on line 68
4) Since WooCommerce was already installed I deleted the existing plugin and attempt to reinstall with the same error resulting as above.
5) Tried to load same zip file on another AT site https://ricksstoretestsite.home.blog/ and the plugin loaded without an error first time.

**Expected behavior**
The plugin to install.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Unable to get system status report from plugin as plugin hasn't installed.

**Comment by kloon** [comment]
Hey Richard, as per the previous issue, this repository is not for issues relating to plugins or themes but just WooCommerce core. I see you are doing your trial, would probably be good to touch base with your contact person to find out how you should go about getting these issues resolved for you and the correct place to log any issues you spot.

Good luck with your trial :)
