### ISSUE TITLE
Can't update Cart

### ISSUE THREAD

**Issue by EmilioLarocca** [woocommerce/woocommerce#22498]
Hi,
On the Shop Page of my website (https://www.nilasphere.com/) I've tried to delete items or order 0 products and clicking on "Update Cart" afterwards but nothing changes. 

Can you help me please to solve it?
It's very urgent.

Kind Regards,
Emilio Larocca Conte

**Comment by JohnTendik** [comment]
This sounds a lot like a caching issue. DId you check this article out? https://docs.woocommerce.com/document/configuring-caching-plugins/

It looks like you're using w3 to cache your website, I saw a lot of mem and disk cached files coming through. I don't know exactly if this is the issue or not but it would be worth making sure that your cart/checkout/my-account pages are not being cached by your plugin :)

**Comment by EmilioLarocca** [comment]
Hi John, thanks for your help. Yep, mfunc is ignored on my W3 and cart/checkout/my-account pages are not cached but the problem is still here. I tried also deactivating all the plugins and changing theme but there are not such kind of conflicts :(

**Comment by EmilioLarocca** [comment]
As you can see there are some template overrides...do you think it might be the issue?

**Comment by rrennick** [comment]
Github is for reporting bugs. For support contact https://woocommerce.com or the support forums https://wordpress.org/support/plugin/woocommerce .
