### ISSUE TITLE
New "decimals" filter / function just for tax calculations

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#22497]
When setting the "Number of decimals" this affects both the calculations and the formatting of prices on the frontend (and backend for all that matters).

Although this is fine for most cases, and WooCommerce should work out of the box "for most cases", there are specific situations where this can lead into problems, and I believe there's should be a way to fix for those situations.

Let's see this example:
- WooCommerce set to 2 decimal numbers and to round per line

![image](https://user-images.githubusercontent.com/6853605/51389383-1c5adc00-1b24-11e9-9f9c-9cc1e8523d6a.png)

Because WooCommerce will round to 2 decimals on each line, we get a total of 17,37 of VAT.

But when we integrate the order into the invoicing system, it does the tax calculation also on each line, but it uses 10 decimals. Only at the very end, the total is rounded to the 2 decimals required by law, and we get 17,36 of VAT.

It's true that if we set WooCommerce to "Round tax at subtotal level, instead of rounding per line" it will fixe most issues, but it's still not 100% correct, because the external invoicing system is indeed doing the calculation on a line basis, it just uses a greater precision.

My proposal is that a new `wc_get_price_calc_decimals()` (or something similar) function is created that returns the current `wc_get_price_decimals()` value but with an additional `wc_get_price_calc_decimals` filter applied.
This new function would then replace the original one only where it's being used for calculations, and not for formatting prices for presentation (where the original one should be used).

This would be completely transparent for most use cases, because the filter is not used, but useful for developers who need to have more exact calculations, for whatever reason (like 3rd party invoicing and ERP integrations).

There are previous issues regarding very similar issues that were never fixed, like #4514 for example.

**Comment by arnofo** [comment]
Thank you for referencing this issue, i was having problems with decimals calculations but could not figure out why. I was experiencing the problem you described.

As a quick fix and until this gets resolved i fixed it with this :

```php
/**
 * This fixes the bug described in
 * https://github.com/woocommerce/woocommerce/issues/22497.
 *
 * This is a temporary fix until a solution is found and merged in woocommerce master.
 *
 * This forces woocommerce to display prices with 2 decimals but still use
 * the number of decimals specified in BO `woocommerce_price_num_decimals`
 * for calculations.
 *
 * You can use parameter `force_decimals` when using function wc_price
 * to still force a different number of decimals manually
 */
add_filter('wc_price_args', 'wc_force_decimals_for_price_display');
function wc_force_decimals_for_price_display($args)
{
    if (isset($args['force_decimals'])) {
        $args['decimals'] = $args['force_decimals'];
    } else {
        $args['decimals'] = 2;
    }

    return $args;
}
```
Then i set the number of decimals in "Woocommerce >Settings > General > Number of decimals" to **3** (could be increased for more precision i guess)

![Screenshot](https://i.imgur.com/X90LE7T.jpg)

**Comment by webdados** [comment]
Although this is the opposite of what I suggested (have a filter for calculation), this will also work (have a filter for display).

**Comment by rrennick** [comment]
> Because WooCommerce will round to 2 decimals on each line, we get a total of 17,37 of VAT.

There is a checkbox in the tax settings to have tax rounded at the subtotal instead of per line.

I'm closing this. Please re-open if you have a pull request for this that we could review.
