### ISSUE TITLE
Json+ld Structured Data not Outputting Correctly for Products

### ISSUE THREAD

**Issue by wcgooner** [woocommerce/woocommerce#22494]
I'm starting a new thread on this topic because a previous topic (https://github.com/woocommerce/woocommerce/issues/15045) resolved some of these issues but the ones below still remain.

1.) Is there a way to just make Woocommerce output only the main description for the "description" field in the structured data? Currently with the code I've used from the linked thread, the structured data output has 2 "description" fields: 1 that uses the product short description and the other that uses the main description. (WooCommerce seems to default to the short description field)

2.) How to we get woocommerce to pull the brand & sku attribute for the "brand" and "sku" structured data fields? I notice it does it pulls 1 or none (rarely both) of these depending on the product. I assume there's some code that can instruct it exactly where to pull the info from?

3.) For variable products, the woocommerce code never pulls the single price of the variation; it labels it an "Aggregate Offer" (as the "@type") with a "lowPrice" and "highPrice". This confuses google and makes it seems that the price for a product variation is not specified. Anyone know how to make a variation output as just an "Offer" for the "@type" and pull that variations single price?

**Comment by noelmcg** [comment]
As per the title, I believe html tags should be stripped from the description in the products structured data.

Propose using ```wp_filter_nohtml_kses``` as opposed to ```wpautop```

woocommerce/includes/class-wc-structured-data.php
Line 213:

```
$markup['description'] = wpautop( do_shortcode( $product->get_short_description() ? $product->get_short_description() : $product->get_description() ) );
```

**Comment by mikejolley** [comment]
All schema can be customised/replaced/removed via the hooks (`woocommerce_structured_data_product` being the main one here).

I'd suggest asking these questions within one of the developer communties, or posting a project for someone to work on this for you. We don't provide customisations here.

Thanks
