### ISSUE TITLE
Shipping address doesn't appear in emails for manual orders

### ISSUE THREAD

**Issue by mdmoore** [woocommerce/woocommerce#22493]
**Describe the bug**
When creating a manual order with both billing and shipping address, the emails sent to the customer and admin don't include the shipping address.

**To Reproduce**
1. Go to WooCommerce > Orders > Add New
2. Choose a customer
3. Load Billing and Shipping Address (maybe use a different billing address so you can view the customer email)
4. Set the order to Processing
5. Add a product
6. Save the order 
7. Try resending Custom Invoice
8. Check emails

**Screenshots**
![http://cld.wthms.co/wvE4qt](http://cld.wthms.co/wvE4qt+)
Full Image: http://cld.wthms.co/wvE4qt+

**Expected behavior**
I would expect to see Shipping Information beside Billing Information

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

Home URL: https://woocommerce.dev
Site URL: https://woocommerce.dev
Log Directory Writable: ✔
WP Version: 5.1-beta1-44640
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.13
PHP Post Max Size: 30 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2q

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.21-MariaDB
Max Upload Size: 25 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.3
WC Database Prefix: wp_
Total Database Size: 42.80MB
Database Data Size: 36.12MB
Database Index Size: 6.68MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_downloadable_product_permissions: Data: 0.01MB + Index: 0.03MB
wp_woocommerce_order_items: Data: 0.07MB + Index: 0.05MB
wp_woocommerce_order_itemmeta: Data: 0.52MB + Index: 0.37MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_ariadminer_connections: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.03MB + Index: 0.02MB
wp_comments: Data: 0.87MB + Index: 0.41MB
wp_email_log: Data: 14.16MB + Index: 0.02MB
wp_followup_coupons: Data: 0.00MB + Index: 0.01MB
wp_followup_coupon_logs: Data: 0.00MB + Index: 0.00MB
wp_followup_customers: Data: 0.00MB + Index: 0.01MB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.01MB
wp_followup_customer_notes: Data: 0.00MB + Index: 0.00MB
wp_followup_customer_orders: Data: 0.01MB + Index: 0.01MB
wp_followup_email_coupons: Data: 0.00MB + Index: 0.00MB
wp_followup_email_excludes: Data: 0.00MB + Index: 0.00MB
wp_followup_email_logs: Data: 0.09MB + Index: 0.04MB
wp_followup_email_orders: Data: 0.94MB + Index: 0.11MB
wp_followup_email_order_coupons: Data: 0.00MB + Index: 0.00MB
wp_followup_email_tracking: Data: 0.01MB + Index: 0.02MB
wp_followup_followup_history: Data: 0.25MB + Index: 0.02MB
wp_followup_order_categories: Data: 0.01MB + Index: 0.03MB
wp_followup_order_items: Data: 0.02MB + Index: 0.04MB
wp_followup_subscribers: Data: 0.00MB + Index: 0.01MB
wp_followup_subscribers_to_lists: Data: 0.00MB + Index: 0.00MB
wp_followup_subscriber_lists: Data: 0.00MB + Index: 0.01MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 11.94MB + Index: 1.14MB
wp_postmeta: Data: 5.38MB + Index: 3.18MB
wp_posts: Data: 1.46MB + Index: 0.62MB
wp_say_what_strings: Data: 0.00MB + Index: 0.00MB
wp_snippets: Data: 0.01MB + Index: 0.00MB
wp_termmeta: Data: 0.01MB + Index: 0.02MB
wp_terms: Data: 0.01MB + Index: 0.02MB
wp_term_relationships: Data: 0.16MB + Index: 0.33MB
wp_term_taxonomy: Data: 0.01MB + Index: 0.01MB
wp_usermeta: Data: 0.07MB + Index: 0.04MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wcpv_commissions: Data: 0.00MB + Index: 0.00MB
wp_wcpv_per_product_shipping_rules: Data: 0.00MB + Index: 0.00MB
wp_wc_booking_relationships: Data: 0.00MB + Index: 0.00MB
wp_wc_deposits_payment_plans: Data: 0.00MB + Index: 0.00MB
wp_wc_deposits_payment_plans_schedule: Data: 0.00MB + Index: 0.00MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_points_rewards_user_points: Data: 0.00MB + Index: 0.01MB
wp_wc_points_rewards_user_points_log: Data: 0.00MB + Index: 0.01MB
wp_wc_warranty_products: Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_bundled_itemmeta: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_bundled_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_per_product_shipping_rules: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_table_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_software_activations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_software_licenses: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_subscription_downloads: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 220
bookable_person: 8
bookable_resource: 7
course: 1
custom_css: 1
event_ticket: 4
event_ticket_email: 1
follow_up_email: 59
global_product_addon: 1
jetpack_migration: 2
lesson: 1
nav_menu_item: 14
page: 30
post: 7
product: 290
product_variation: 597
quiz: 1
revision: 56
scheduled-action: 189
shop_coupon: 28
shop_order: 623
shop_order_refund: 7
shop_subscription: 36
tribe_events: 1
tribe_organizer: 1
tribe_venue: 1
tribe_wooticket: 2
warranty_request: 1
wc_booking: 19
wc_membership_plan: 2
wc_order_status: 8
wc_user_membership: 2
wc_zapier_feed: 2
wishlist: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

WooCommerce Stripe Gateway: by WooCommerce – 4.1.14
WooCommerce: by Automattic – 3.5.3

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
external (external)
grouped (grouped)
mix-and-match (mix-and-match)
photography (photography)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 2.0
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by peterfabian** [comment]
Hi, 

It seems you actually need to add shipping item to your order, otherwise the code assumes there is no need to display the shipping address as it has no shipping info attached to the order.

When creating your order, please try to add shipping line item and select anything but local pickup:
1. Add items -> Add shipping
<img width="1338" alt="screenshot 2019-01-21 at 17 10 44" src="https://user-images.githubusercontent.com/2207451/51486042-eb86db00-1d9f-11e9-8659-c82ee40138d4.png">

2. Edit shipping info:
<img width="1338" alt="screenshot 2019-01-21 at 17 11 09" src="https://user-images.githubusercontent.com/2207451/51486057-f5a8d980-1d9f-11e9-9b10-2c389df0c3bb.png">

3. Add shipping type, cost and hit `Save` button:
<img width="1338" alt="screenshot 2019-01-21 at 17 11 34" src="https://user-images.githubusercontent.com/2207451/51486068-fccfe780-1d9f-11e9-9e08-b8298a366203.png">

If you would like to change this, please submit a feature request.
Thanks.

**Comment by KoolPal** [comment]
@peterfabian Please revisit this issue. All steps provided in this issue has been followed and yet the Shipping address is not seen

![image](https://user-images.githubusercontent.com/454883/55461852-1cdb1d00-5613-11e9-8fbf-615237a020f8.png)

**Comment by peterfabian** [comment]
@KoolPal 
Tested it now with latest stable WC, it seems to work fine. According to your screenshot, it seems the customer has no shipping address, so I assume that might be the reason why it's not present in the email?

**Comment by KoolPal** [comment]
@peterfabian Sorry, I completely missed this while focusing on some other critical items.

I am on:

WooCommerce version: 3.6.4
WordPress version: 5.2.1

I created a manual order as shown below:

![image](https://user-images.githubusercontent.com/454883/59350642-3ea2ff80-8d3a-11e9-9137-fcddf85a84a0.png)

On creating the Order, you will notice Shipping section shows: Address: No shipping address set.

![image](https://user-images.githubusercontent.com/454883/59350733-7ca02380-8d3a-11e9-82b8-1375361d1f71.png)

I have recreated the steps as shown in your comment [https://github.com/woocommerce/woocommerce/issues/22493#issuecomment-456127058] and YET found consistent issue with Shipping Address NOT being seen: 

![image](https://user-images.githubusercontent.com/454883/59350942-e5879b80-8d3a-11e9-8361-3c59dc209688.png)

The received email shows ONLY the Billing address:
![image](https://user-images.githubusercontent.com/454883/59351060-28497380-8d3b-11e9-8967-ec93baf3a006.png)

Please let me know in case I should do any additional step.

Thanks

**Comment by peterfabian** [comment]
Hi @KoolPal 

Please try this with only WooCommerce plugin active and please include steps to reproduce and your shipping settings. I can't reproduce this in latest WC, please see the video when following steps from the original post: 
https://youtu.be/sCIs7pfr7ug

**Comment by KoolPal** [comment]
@peterfabian Thank you for your response. I have tested this with only Woocommerce. The difference in my use case versus your video is that you have created a manual order for a **registered customer** whereas I am trying to make this for a **guest user**.

Can you please test using my use case and then see if there is something amiss?

Thanks

**Comment by peterfabian** [comment]
@KoolPal I still can't reproduce, please see the following: https://youtu.be/moOYUqg9ui8

**Comment by KoolPal** [comment]
@peterfabian Let me try to replicate your steps EXACTLY (I notice you fill the address to quite an extent)

Let me get back.

Having said this, is there any linkage to this? **The shipping address & billing address doesn't appear on the order received page if you're checking out as a guest** #23864

Thanks

**Comment by cancolpan** [comment]
We have same issue.

**Comment by peterfabian** [comment]
@cancolpan As this issue seems to actually include 2 different workflows (creating order for existing vs guest customer), it's not clear to me which problem you're facing. 
Therefore, it would help us, if you could provide your status report, steps to reproduce and let us know if you tested this with only WooCommerce plugin active, please. Feel free to open a new issue and fill in the template.

**Comment by jtobiesen** [comment]
Because of zen-5677301, tested adding zero shipping cost (the merchant would like shipping address to show even if there is free shipping) to the shipping information when creating the manual order. Confirmed both billing and shipping address show on confirmation email.
