### ISSUE TITLE
Products block: Description does not cover the entire width of the screen

### ISSUE THREAD

**Issue by arunsathiya** [woocommerce/woocommerce#22507]
**Is your feature request related to a problem? Please describe.**
The `Products block` activation message does not make use of the full screen width. It gets chopped off in the middle.

**Describe the solution you'd like**
The description `We noticed you have the block editor available: Try the WooCommerce Products Block for a powerful new way to feature products in posts.` covers the entire width of the screen/display.

**Describe alternatives you've considered**
NA

**Additional context**

<img width="1745" alt="screenshot 2019-01-20 at 21 06 26" src="https://user-images.githubusercontent.com/18581859/51441478-23d2de80-1cf8-11e9-854a-c3cd489f49e7.png">

I think this repository is the best place to suggest this enhancement, or should I move this to https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues, let me know!

**Comment by rrennick** [comment]
The paragraph max-width is not particular to the products block notice. It applies to all the WC notices
<img width="1127" alt="screen shot 2019-01-21 at 8 39 21 am" src="https://user-images.githubusercontent.com/343847/51475226-22d19980-1d58-11e9-946f-88a5f661f7c2.png">

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22652
