### ISSUE TITLE
Add new product feature image issue

### ISSUE THREAD

**Issue by parmarhardip** [woocommerce/woocommerce#22508]
**Describe the bug**
When I added the Custom product table and Data migrate using CLI and after creating a new product and set the feature image in a new product that time feature image not set.

Also, When I again update the Feature image then successfully updated.
https://woocommerce.wordpress.com/2018/07/17/woocommerce-custom-product-tables-beta/

**To Reproduce**
1. Go to 'Download the latest custom product table plugin on GitHub and migrate a data.'
2. Click on 'After adding new Product and set the feature image.'
3. See error Not showing a feature image.

I have troubleshot the Custom product plugin and Woocomerce plugin and I have found that the Woocommerce "wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php" file path in '`public static function save( $post_id, $post ) {`' function under the "`set_props`" function isn't set the "image_id" in the first time.

Also, I have tested in the latest version of WooCommerce.

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by rodrigoprimo** [comment]
Closing in favor of https://github.com/woocommerce/woocommerce-product-tables-feature-plugin/issues/139. Could you please edit https://github.com/woocommerce/woocommerce-product-tables-feature-plugin/issues/139 description and include the information you provided here? Thanks.
