### ISSUE TITLE
Missing Product Schema

### ISSUE THREAD

**Issue by techmarkm** [woocommerce/woocommerce#22528]
I'm currently using woocommerce 3.5.3 with wordpress 5.0.3. However the product schema does not show up when testing with Google Structured Data: https://imgur.com/a/6H3tuZV.

My URL is: https://newtechshop.vn/samsung-galaxy-note-8-han-quoc-fullbox

Could anyone please suggest if there's a solution to add the schema? Thanks!

**Comment by mikejolley** [comment]
Looks like a theme issue. I'm not seeing the problem locally.

Your theme is either missing the `wp_footer` hook where schema markup is injected, or the theme/a plugin is removing it. Go through the debugging steps in the new issue template.

Thanks
