### ISSUE TITLE
Fixed Coupon rounding issue with multiple products

### ISSUE THREAD

**Issue by Tofandel** [woocommerce/woocommerce#22532]
**Bug**
I have a fixed cart coupon only applied when the customer has more than 3 products in the cart using the Minimum number of Category option set to 3

My taxes are set to 20% and I'm using WC 3.5.4 (desactivated other woocommerce plugins and the issue persists)

If I set the price of the coupon to 15€ and set woocommerce_prices_include_tax to true,
then it works correctly and I get a 15€ discount applied.

But things complicate because in the shop prices are not entered with taxes hence the option is set to false,
I then have to set the price of the coupon without taxes to 12.5€ (15/1.2) as suggested here https://wordpress.org/support/topic/coupons-adding-sales-tax-to-coupon-amount/

But now the coupon applied is of 16€ instead of the desired 15€

Dumping the content of the cart I found that the price of the coupon is rounded to 13 and the taxes rounded to 3 giving an incorrect price

I found how to fix the 12.5 rounding issue in WC_Discounts on line 475
by replacing the `absint()` to
`$per_item_discount = wc_round_discount( $amount / $item_count, wc_get_rounding_precision() ); // round it down to the nearest cent.`

But I did not manage to find where the tax rounding issue occurs

**Feature request**
I would also suggest adding a checkbox option on coupons : price include tax which would override the woocommerce global option (like on products) as I'm not the only one having issues with coupons (because you don't expect that they would be taxed)

**Comment by rrennick** [comment]
Can you provide the WooCommerce settings used related to pricing & taxes?

**Comment by Tofandel** [comment]
![image](https://user-images.githubusercontent.com/6115458/51612483-d5a12380-1f21-11e9-9310-1cf9124d028b.png)
![image](https://user-images.githubusercontent.com/6115458/51612513-e6519980-1f21-11e9-9598-5e82c34ec141.png)
![image](https://user-images.githubusercontent.com/6115458/51612569-02553b00-1f22-11e9-949d-77273f2b0612.png)
Does this help? Or do you need specific options?

**Comment by Tofandel** [comment]
I tried with the Rounding option enabled and disabled, it didn't change anything

**Comment by Tofandel** [comment]
If I set the number of decimals to 1 then it works as expected, but you would expected the number of decimals to matter only for the final price displayed and not for the prices in between calculation

**Comment by rrennick** [comment]
Closing this. Given your settings, the rounding issue occurs in places other than coupons. For example, a product or cart total priced at 23.00

Tax: 23 * .2 = 4.6 rounded to 0 decimal places is 5.00
Cart total: 23 + 5 = 28 

If you need the pricing to have 0 decimal places then using tax inclusive pricing would address rounding issues except edge cases.

**Comment by Tofandel** [comment]
This is still an issue to me, the rounding of decimals should occur after calculations, not before.

It's the same for shipping, say I have a 27% tax I put a shipping at 46,15€ without tax, the price is rounded and then the tax added from the rounded price 46 * 1.27 = round(58,42) = 58€ but it should be 46.15 * 1.27 = round(58.6) = 59€

That causes the prices to be wrong

**Comment by Tofandel** [comment]
For future reference, the desired effect without having calculation problems can be achieved using this filter and setting the decimals to 2 (or higher depending on your needs)

```php
add_filter( 'wc_price_args', function ($args) {
	$args['decimals'] = 0;
	return $args;
} );
```
