### ISSUE TITLE
Adding custom field to product in manual order creation?

### ISSUE THREAD

**Issue by Lippiun** [woocommerce/woocommerce#22535]
Hello,

I'm trying to manually add an order from the admin section and would like to be able to add data into a custom field for each product i'm adding into the order. However, when i click 'Add Products' i only get two fields, 'product name' and 'qty'. How would i go about adding custom data for each product I'm adding? 

I've created the custom fields to be shown on my products page but am struggling to find any hook / action so I can add it into the screen where I manually create orders?

**Comment by rrennick** [comment]
Custom fields (meta) on products are stored in a different location than meta for order items. The hook reference is at https://docs.woocommerce.com/wc-apidocs/hook-docs.html. There is a section Admin Hooks.
