### ISSUE TITLE
Problems sending character ‘+’ in user_id parameter (POST Request)

### ISSUE THREAD

**Issue by hendrik244** [woocommerce/woocommerce#22548]
**Describe the bug**
Hi all,

I’m currently using the /wc-auth/v1/authorize endpoint to create and get the API keys for the appropriate user.
I’m using the user_id for internal reference. Sometimes the user_id parameter includes a ‘+’ character.
Theres no way to avoid this.
Unfortunately this ‘+’ is replaced by ‘ ‘, when I receive the callback with the created keys and so on.
That makes it impossible for me to identify the user. Although because I don’t know if more characters are getting replaced in the callback. Maybe the ‘+’ character is only one of many characters, that are getting replaced? I just want to be sure, that I get the userid parameter in the same way as I passed it…

That’s what i pass:
ak58coGVNMH+TwY6qvpGuMVnE9P40Gh0BhBZAAXxsnE=

That’s what i receive:
ak58coGVNMH TwY6qvpGuMVnE9P40Gh0BhBZAAXxsnE=

Best regards,
Hendrik

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
`
### WordPress Environment ###

Home URL: https://staging.roasting365.com
Site URL: https://staging.roasting365.com
WC Version: 3.5.4
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.26 - Wir empfehlen
PHP Version 7.2 oder höher für mehr Leistung und Sicherheit zu verwenden. So aktualisierst du deine PHP-Version

PHP Post Max Size: 16 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.36

SUHOSIN Installed: –
MySQL Version: 5.5.60-MariaDB
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.4
WC Database Prefix: 0h2JSjthD8_
MaxMind GeoIP Database: ✔
Datenbank-Gesamtgröße: 68.05MB
Datenbank-Datengröße: 55.86MB
Datenbank-Indexgröße: 12.19MB
0h2JSjthD8_woocommerce_sessions: Daten: 0.05MB + Index: 0.02MB
0h2JSjthD8_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB
0h2JSjthD8_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB
0h2JSjthD8_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.05MB
0h2JSjthD8_woocommerce_order_items: Daten: 0.02MB + Index: 0.02MB
0h2JSjthD8_woocommerce_order_itemmeta: Daten: 0.06MB + Index: 0.03MB
0h2JSjthD8_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB
0h2JSjthD8_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB
0h2JSjthD8_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB
0h2JSjthD8_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB
0h2JSjthD8_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB
0h2JSjthD8_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB
0h2JSjthD8_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB
0h2JSjthD8_woocommerce_log: Daten: 0.02MB + Index: 0.02MB
0h2JSjthD8_commentmeta: Daten: 0.02MB + Index: 0.03MB
0h2JSjthD8_comments: Daten: 0.05MB + Index: 0.09MB
0h2JSjthD8_et_bloom_stats: Daten: 0.02MB + Index: 0.00MB
0h2JSjthD8_failed_jobs: Daten: 0.02MB + Index: 0.00MB
0h2JSjthD8_icl_content_status: Daten: 0.02MB + Index: 0.02MB
0h2JSjthD8_icl_core_status: Daten: 0.02MB + Index: 0.02MB
0h2JSjthD8_icl_flags: Daten: 0.02MB + Index: 0.02MB
0h2JSjthD8_icl_languages: Daten: 0.02MB + Index: 0.03MB
0h2JSjthD8_icl_languages_translations: Daten: 0.19MB + Index: 0.11MB
0h2JSjthD8_icl_locale_map: Daten: 0.02MB + Index: 0.00MB
0h2JSjthD8_icl_message_status: Daten: 0.02MB + Index: 0.03MB
0h2JSjthD8_icl_mo_files_domains: Daten: 0.02MB + Index: 0.02MB
0h2JSjthD8_icl_node: Daten: 0.02MB + Index: 0.00MB
0h2JSjthD8_icl_reminders: Daten: 0.02MB + Index: 0.00MB
0h2JSjthD8_icl_strings: Daten: 5.52MB + Index: 7.02MB
0h2JSjthD8_icl_string_packages: Daten: 0.02MB + Index: 0.00MB
0h2JSjthD8_icl_string_pages: Daten: 1.52MB + Index: 1.52MB
0h2JSjthD8_icl_string_positions: Daten: 0.02MB + Index: 0.02MB
0h2JSjthD8_icl_string_status: Daten: 0.02MB + Index: 0.02MB
0h2JSjthD8_icl_string_translations: Daten: 3.52MB + Index: 1.52MB
0h2JSjthD8_icl_string_urls: Daten: 0.02MB + Index: 0.02MB
0h2JSjthD8_icl_translate: Daten: 0.03MB + Index: 0.02MB
0h2JSjthD8_icl_translate_job: Daten: 0.02MB + Index: 0.02MB
0h2JSjthD8_icl_translations: Daten: 0.06MB + Index: 0.13MB
0h2JSjthD8_icl_translation_batches: Daten: 0.02MB + Index: 0.00MB
0h2JSjthD8_icl_translation_status: Daten: 0.09MB + Index: 0.02MB
0h2JSjthD8_links: Daten: 0.02MB + Index: 0.02MB
0h2JSjthD8_mailchimp_carts: Daten: 0.02MB + Index: 0.00MB
0h2JSjthD8_options: Daten: 4.22MB + Index: 0.14MB
0h2JSjthD8_podsrel: Daten: 0.02MB + Index: 0.06MB
0h2JSjthD8_postmeta: Daten: 0.50MB + Index: 0.39MB
0h2JSjthD8_posts: Daten: 39.06MB + Index: 0.22MB
0h2JSjthD8_queue: Daten: 0.02MB + Index: 0.00MB
0h2JSjthD8_termmeta: Daten: 0.02MB + Index: 0.03MB
0h2JSjthD8_terms: Daten: 0.02MB + Index: 0.03MB
0h2JSjthD8_term_relationships: Daten: 0.02MB + Index: 0.02MB
0h2JSjthD8_term_taxonomy: Daten: 0.02MB + Index: 0.03MB
0h2JSjthD8_usermeta: Daten: 0.05MB + Index: 0.03MB
0h2JSjthD8_users: Daten: 0.02MB + Index: 0.05MB
0h2JSjthD8_wcj_track_users: Daten: 0.02MB + Index: 0.00MB
0h2JSjthD8_wc_download_log: Daten: 0.02MB + Index: 0.03MB
0h2JSjthD8_wc_webhooks: Daten: 0.02MB + Index: 0.02MB
0h2JSjthD8_woocommerce_bundled_itemmeta: Daten: 0.02MB + Index: 0.03MB
0h2JSjthD8_woocommerce_bundled_items: Daten: 0.02MB + Index: 0.03MB
0h2JSjthD8_woocommerce_subscription_downloads: Daten: 0.02MB + Index: 0.00MB
0h2JSjthD8_yoast_seo_links: Daten: 0.02MB + Index: 0.02MB
0h2JSjthD8_yoast_seo_meta: Daten: 0.02MB + Index: 0.00MB

### Post Type Counts ###

_pods_field: 2
_pods_pod: 2
attachment: 182
custom_css: 1
customize_changeset: 3
et_pb_layout: 8
invoice: 10
nav_menu_item: 7
page: 18
post: 2
product: 14
project: 1
revision: 639
scheduled-action: 30
shop_order: 12
shop_subscription: 12
wc_membership_plan: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (28) ###

WPML Multilingual CMS: von OnTheGoSystems – 4.1.3
Addendio PLUS: von Addendio – 1.1.1
Akismet Anti-Spam: von Automattic – 4.1
Bloom: von Elegant Themes – 1.3.8
Classic Editor: von WordPress-Mitwirkende – 1.3
Cookie Notice: von dFactory – 1.2.45
Mailchimp for WooCommerce: von Mailchimp – 2.1.12 – Nicht getestest mit der aktiven WooCommerce-Version
NinjaFirewall (WP+): von The Ninja Technologies Network – 3.8.1
NinjaScanner: von The Ninja Technologies Network – 1.3.3
Pods - Custom Content Types and Fields: von Pods Framework Team – 2.7.12
Specify a Vary: Accept-Encoding Header: von LithiumSixteen – 1.0.0
Vendidero Helper: von Vendidero – 1.2.1
WooCommerce Blocks: von Automattic – 1.3.1
WooCommerce Stripe-Gateway: von WooCommerce – 4.1.14
WooCommerce Germanized Pro: von Vendidero – 1.9.9
WooCommerce Germanized: von Vendidero – 2.2.7
WooCommerce Memberships: von SkyVerge – 1.12.3
WooCommerce Multilingual: von OnTheGoSystems – 4.3.7
WooCommerce Product Bundles: von SomewhereWarm – 5.9.0
WooCommerce Subscribe All the Things: von Prospress Inc. – 2.1.4
WooCommerce Subscription Downloads: von WooCommerce – 1.1.17
WooCommerce Subscriptions: von Prospress Inc. – 2.4.7
WooCommerce: von Automattic – 3.5.4
Yoast SEO Premium: von Team Yoast – 9.4
WP SVG images: von KubiQ – 3.0
WPML Media: von OnTheGoSystems – 2.4.1
WPML String Translation: von OnTheGoSystems – 2.9.1
WPML Translation Management: von OnTheGoSystems – 2.7.2

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop-Basis: #53528 - /shop/
Warenkorb: #53529 - /warenkorb/
Kasse: #53530 - /kasse/
Mein Konto: #53531 - /mein-konto/
Allgemeine Geschäftsbedingungen: #53798 - /agb/

### Theme ###

Name: Divi
Version: 3.19.7
Author URL: http://www.elegantthemes.com
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Memberships ###

Restriction mode:: Hide content only
Public content:: –
Excluded from discounts:: –
Membership plans:: 2
_SYSTEM:: Members: 0Access method: Manual assignment onlyAccess length: Unlimited Subscription: No
CORE:: Members: 0Access method: Manual assignment onlyAccess length: Unlimited Subscription: No

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ❌ Staging
Subscriptions Live URL: https://roasting365.com
Subscription Statuses: trash: 1
auto-draft: 3
wc-active: 6
wc-cancelled: 2

WooCommerce Account Connected: ✔ Yes
Active Product Key: ✔ Yes
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: Deutschland

### Subscriptions by Payment Gateway ###

other: trash: 1
wc-active: 3

Stripe: wc-active: 3
wc-cancelled: 2

### Payment Gateway Support ###

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
pre-orders

Stripe SEPA Lastschrift: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
pre-orders

### Product Bundles ###

Database Version: 5.9.0
Template Overrides: –
`

**Comment by rrennick** [comment]
WordPress does not allow `+` character in the username field. See screenshot
<img width="614" alt="screen shot 2019-01-24 at 9 39 47 am" src="https://user-images.githubusercontent.com/343847/51681827-31b88600-1fbc-11e9-87ab-0144a44dffc0.png">

If you are storing the `user_id` in a different field can you provide the endpoint ans an example payload you are using?

**Comment by hendrik244** [comment]
Thank you for your answer. Helped me. Do you know, if its only the '+' character, which isn't allowed?

**Comment by rrennick** [comment]
@hendrik244 See https://developer.wordpress.org/reference/functions/sanitize_user/
