### ISSUE TITLE
Bulk edit products or orders NOT WORKING

### ISSUE THREAD

**Issue by xrahat2011** [woocommerce/woocommerce#22549]
**Describe the bug**
When you try to bulk edit products or orders, after refreshing nothing has happened.

**To Reproduce**
1. Go to 'Woocommerce -> orders'
2. Click on 'Tick marks of more than 2 orders'
3. Scroll down to 'bottom'
4. Select "move to bin"
5. Press "Apply"

**Screenshots**
NONE

**Expected behavior**
It should move those orders to bin but it does not

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: https://a1megastore.com
Site URL: https://a1megastore.com
WC Version: 3.5.4
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.14 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: 5.6.41-84.1
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 1.53MB
Database Data Size: 1.24MB
Database Index Size: 0.29MB
wp_woocommerce_sessions: Data: 0.49MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.01MB + Index: 0.01MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_adsw_ali_meta: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_comments: Data: 0.01MB + Index: 0.01MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 0.45MB + Index: 0.07MB
wp_postmeta: Data: 0.21MB + Index: 0.12MB
wp_posts: Data: 0.03MB + Index: 0.02MB
wp_smush_dir_images: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.00MB + Index: 0.00MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_usermeta: Data: 0.02MB + Index: 0.01MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.00MB + Index: 0.00MB
wp_yoast_seo_meta: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 11
custom_css: 1
customize_changeset: 1
jetpack_migration: 2
nav_menu_item: 5
page: 5
post: 1
product: 6
product_variation: 101

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (27) ###

BIALTY - Bulk Image Alt Text (Alt tag, Alt Attribute) with Yoast SEO + WooCommerce: by Pagup – 1.1.1 – Not tested with the active version of WooCommerce
Async JavaScript: by Frank Goossens (futtta) – 2.18.12.10
Autoptimize: by Frank Goossens (futtta) – 2.4.4
Better Robots.txt  - Index, rank & SEO booster + Woocommerce: by Pagup – 1.2.2 – Not tested with the active version of WooCommerce
Webcraftic Clearfy – WordPress optimization plugin: by Webcraftic  – 1.5.0
Dropship Me: by Vitaly Kukin – 0.9.9
Favicon by RealFaviconGenerator: by Philippe Bernard – 1.3.14
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 5.3.7
Hostgator WalkMe Plugin: by Snappy – 1.0
Webcraftic Hide login page: by Webcraftic  – 1.0.8
Leverage Browser Caching: by Rinku Yadav – 1.7
Preloader by WordPress Monsters: by WordPress Monsters – 1.2.3
Prevent XSS Vulnerability: by Sami Ahmed Siddiqui – 0.2
External Links: by Denis de Bernardy & Mike Koepke – 6.8.1
Storefront Footer Text: by Wooassist – 1.0.1
Storefront Site Logo: by Wooassist – 1.2.3
Theme Customisations: by WooThemes – 1.0.0
Proxy Cache Purge: by Mika Epstein – 4.7.3
WooCommerce Blocks: by Automattic – 1.3.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.6
WooCommerce Services: by Automattic – 1.18.0
WooCommerce: by Automattic – 3.5.4
Yoast SEO: by Team Yoast – 9.5
WP Disable: by optimisation.io - jody nesbitt – 1.5.21
WP Mail SMTP: by WPForms – 1.4.1
Smush: by WPMU DEV – 3.0.2
WP Super Cache: by Automattic – 1.6.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #4 - /shop/
Basket: #5 - /basket/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.4.2
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by rrennick** [comment]
I was not able to reproduce this in my install. I was able to bulk delete and restore 2 orders.

The bulk actions are primarily handled by WordPress not WooCommerce. If this is occurring with all plugins deactivated then I'd suggest you create a couple of test draft posts/pages and try to bulk move to trash those. If you encounter the same problem then I'd suggest reinstalling WordPress.

I'm closing this. If you can further isolate the problem and provide steps to reproduce please re-open.

**Comment by xrahat2011** [comment]
Screenshot:
![x](https://user-images.githubusercontent.com/30789881/51739934-90612b00-20b4-11e9-96dd-13acb5f6e349.gif)

Even did this with my other 2 sites, PAGES and POSTS bulk edit is working fine but PRODUCTS & ORDERS of WooCommerce is not, tried with 2 of my sites and with all plugins disabled

**Comment by xrahat2011** [comment]
When deleting through BULK ACTIONS, nothing happens, just a page refresh but when you do each order/product MANUALLY to bin, it works. :/

**Comment by mikejolley** [comment]
I've also just tried this and was not affected. Must be a conflict with a plugin.

Check the console for errors;

1. Add `define( 'SCRIPT_DEBUG', true );` to your wp-config.php file.
2. In chrome, right click the page, inspect, and view console tab
3. Interact with bulk actions. See what error if any appears in console.

**Comment by xrahat2011** [comment]
> I've also just tried this and was not affected. Must be a conflict with a plugin.
> 
> Check the console for errors;
> 
> 1. Add `define( 'SCRIPT_DEBUG', true );` to your wp-config.php file.
> 2. In chrome, right click the page, inspect, and view console tab
> 3. Interact with bulk actions. See what error if any appears in console.

None! :(

**Comment by mikejolley** [comment]
You should rule out a plugin conflict, particulary with those that mention javascript. We're unable to replicate our side so it must be site-specific.

**Comment by xrahat2011** [comment]
> You should rule out a plugin conflict, particulary with those that mention javascript. We're unable to replicate our side so it must be site-specific.

Okay,
I use OPTIMISED WORDPRESS HOSTING by HostGator -> It comes with Proxy Cache Purge and WP Super Cache -> What I just had to do was to "PURGE VARNISH CACHE OF ALL PAGES" or "PURGE CACHE (All Pages) -> Problem solved now, sorry for bothering you, maybe someone else will get helped out by this. So, I posted now. Thanks!

**Comment by xrahat2011** [comment]
> Thanks for the update.

No, thank you for your time all, and sorry I bothered but I'm sure someone else will be helped out, so usually, it's related to CACHE CLEAR problems and also, CAN YOU PLEASE MARK THIS AS SOLVED, I don't know much about GitHub, if it already has been then don't reply. Thank you!

**Comment by xrahat2011** [comment]
> > Thanks for the update.
> 
> No, thank you for your time all, and sorry I bothered but I'm sure someone else will be helped out, so usually, it's related to CACHE CLEAR problems and also, CAN YOU PLEASE MARK THIS AS SOLVED, I don't know much about GitHub, if it already has been then don't reply. Thank you!

Alright! Got it! It's one of the following:
1. Prevent XSS Vulnerability (98% probability)
2. Proxy Cache Purge (10% probability)
3. Yoast SEO (10% probability)

The thing is, in my initial debugging of fiddling with multiple plugins, turning them on and off, these 3 in a weird combination would disrupt the BULK ACTIONS of WordPress. However, disable all 3 definitely fix the issue. Right now, I'm running Proxy Cache Purge and Yoast SEO and it's going stable, tried on multiple browsers in normal mode and incognito modes, even on mobile browsers.

Thought this extended answer might help someone someday,

**Comment by webenadam** [comment]
I have none of this plugins, and still can't bulk edit products!
