### ISSUE TITLE
$fields['billing']['billing_state']['required']   = true; no longer working correctly

### ISSUE THREAD

**Issue by jpknz** [woocommerce/woocommerce#22542]
In the latest version 3.5.4 setting the billing_state field to required has unexpected/changed results.

Using the below code
```
add_filter('woocommerce_checkout_fields', 'override_checkout_fields');
function override_checkout_fields( $fields ) {
$fields['billing']['billing_state']['required']   = true;
return $fields;
}
```
In versions prior to 3.5.4 this would work correctly as described below. Example uses New Zealand as the country.
- 'Region (Optional)' would become 'Region *'
- If not selected and the checkout form submitted then notice displayed with 'Billing Region is a required field.'

In version 3.5.4
- 'Region (Optional)' remains as is (possibly briefly changes to 'Region *' before changing back to 'Region (Optional)' - only managed to see this once however).
- If not selected and the checkout form submitted then notice displayed with 'Billing Region is a required field.'

**Isolating the problem (mark completed items with an [x]):**
- [* ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ * - with both twentynineteen and storefront] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [* ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
`
### WordPress Environment ###

Home URL: http://[...]
Site URL: http://[...]
WC Version: 3.5.4
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.31 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 40 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.2o

SUHOSIN Installed: –
MySQL Version: 5.7.23
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 3.92MB
Database Data Size: 3.04MB
Database Index Size: 0.88MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.50MB + Index: 0.05MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

page: 6
post: 2
product: 1
revision: 2
scheduled-action: 5

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (6) ###

stopAds WooCommerce Functions: by  –  – Not tested with the active version of WooCommerce
WooCommerce Blocks: by Automattic – 1.3.1
WooCommerce Stripe Gateway: by WooCommerce – 4.1.14
WooCommerce Services: by Automattic – 1.18.0
WooCommerce Subscriptions: by Prospress Inc. – 2.4.7
WooCommerce: by Automattic – 3.5.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #9 - /shop/
Basket: #10 - /basket/
Checkout: #11 - /checkout/
My account: #12 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.4.2
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: http://[...]/
Subscription Statuses: –
WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United Kingdom (UK)

### Payment Gateway Support ###

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
pre-orders

`

**Comment by mikejolley** [comment]
This is because a locale exists for NZ within which state is not required. The fix in .4 correctly applies the locale when the checkout loads. This worked for you before because this first load was broken in .3.

`woocommerce_get_country_locale` is the filter you need to adjust the NZ locale in. 

https://github.com/woocommerce/woocommerce/blob/99f663ad5c5815baa327b3c3f97b0ad563f2bb50/includes/class-wc-countries.php#L1068-L1076

If this locale is wrong, and state is required for NZ for all addresses, suggest code via a pull request and it can be updated.

Thanks
