### ISSUE TITLE
Need to filter list of database tables in system report

### ISSUE THREAD

**Issue by dchenk** [woocommerce/woocommerce#22543]
On the Status sub-page of the WooCommerce plugin, you can view the list of database tables in the database the site is using. For non-multisite websites, _all_ of the tables are listed, even those that do not have the same `$table_prefix` as the site.

Any number of WordPress sites can share one database and have different table prefixes. Those tables that don't have the current site's prefix should not be shown to users in the system report.

The current behavior is a huge security loophole, so I hope this gets fixed as soon as possible. Thanks in advance.

**Comment by rrennick** [comment]
> The current behavior is a huge security loophole

Providing site administrators information about the environment the site is running in is not a security loophole.

The most secure way to isolate multiple CMS installs sharing a database is to create a separate database user for each install and restrict each DB user's access to the DB resources related to its respective install.

I'm leaving this open for others to comment. However, I have worked on projects where WP had a legitimate reason to read tables maintained by a separate process that did not have the WP table prefix and am ambivalent on restricting the table list.

**Comment by mikejolley** [comment]
I think I agree @rrennick. Nothing forces a plugin/script to use the WP prefix so showing those tables does make sense. 

> The current behavior is a huge security loophole, so I hope this gets fixed as soon as possible. Thanks in advance.

The loophole is that different users sites can read/write to different tables. They should be separated and have correct permissions as @rrennick suggested.

Thanks
