### ISSUE TITLE
Pending Payments And Stock Bug

### ISSUE THREAD

**Issue by plxrisa** [woocommerce/woocommerce#22544]
**Describe the bug**
I open this issue because the issue #21772 remains in WC 3.5.4 and I think that somehow it's also the main reason for #22105.

1. When we have a product with stock (2) and someone order all of them or some of them and the order has "pending payment" status, then in the backend we still see that this product has still "2 on stock". However in the frontend a new client can still add this 2 products in his cart but when he will go to cart page, a message appears that inform him (Sorry, we don't have enough stock to fulfill your order).

2. The same thing happens when you change the status of an excisting order to "pending payment" status.

3. Also, if you have set "hide out of stock products", you can still see this product in the frontend.

4. If you try to add an order manually, you can still see that this product has (2 in stock). But this is wrong.

**To Reproduce**
1. Add a product and set stock (2).
2. Go to frontend and buy these two products.
3. Set this order to be in "pending payment" status.
4. See the list of products and you will see that this product has still (2 in stock).
5.  Go to frontend and try to add 2 more in your cart. (You can see that the system let you add them in your cart).
6. Go to cart page and see the bug message.
7. Try to add an order manually with this product. You will see that the system informs you that there are (2 in stock).

**Screenshots**
Here you can see the exactly steps to reproduce the issue.
https://www.useloom.com/share/ec01d05290614b8ea5161763a9f27370

**Expected behavior**
1. If there is a pending payment with a product that have stock enabled, then the shop owner must see that the product is out of stock or its quantity is reduced.
2. After the order, if the stock is zero, the product must be hidden from the frontend.
3. When you try to add a manually order, the system must informs you for the real stock quantity of this product.

In my opinion, I believe that "pending payment" status must works like "on hold" or "proccessing" status as it concerns for stock, with the only different that the order will be canceled after X minutes.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

Home URL: http://localhost/woo
Site URL: http://localhost/woo
WC Version: 3.5.4
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: el
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.35 (Win64) PHP/7.2.10
PHP Version: 7.2.10
PHP Post Max Size: 8 MB
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.59.0
OpenSSL/1.1.0i

SUHOSIN Installed: –
MySQL Version: 5.7.23
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.4
WC Database Prefix: wp_
Συνολικό μέγεθος βάσης δεδομένων: 0.56MB
Μέγεθος βάσης δεδομένων: 0.44MB
Μέγεθος ευρετηρίου βάσης δεδομένων: 0.12MB
wp_woocommerce_sessions: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_api_keys: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rates: Δεδομένα: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Δεδομένα: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Δεδομένα: 0.00MB + Index: 0.00MB
wp_commentmeta: Δεδομένα: 0.00MB + Index: 0.00MB
wp_comments: Δεδομένα: 0.00MB + Index: 0.01MB
wp_links: Δεδομένα: 0.00MB + Index: 0.00MB
wp_options: Δεδομένα: 0.42MB + Index: 0.03MB
wp_postmeta: Δεδομένα: 0.01MB + Index: 0.02MB
wp_posts: Δεδομένα: 0.01MB + Index: 0.01MB
wp_termmeta: Δεδομένα: 0.00MB + Index: 0.01MB
wp_terms: Δεδομένα: 0.00MB + Index: 0.01MB
wp_term_relationships: Δεδομένα: 0.00MB + Index: 0.00MB
wp_term_taxonomy: Δεδομένα: 0.00MB + Index: 0.00MB
wp_usermeta: Δεδομένα: 0.00MB + Index: 0.01MB
wp_users: Δεδομένα: 0.00MB + Index: 0.01MB
wp_wc_download_log: Δεδομένα: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Δεδομένα: 0.00MB + Index: 0.00MB

### Post Type Counts ###

page: 6
post: 2
product: 2
shop_order: 6

### Security ###

Secure connection (HTTPS): ❌
					Το κατάστημά σας δε χρησιμοποιεί HTTPS. Μάθετε περισσότερα σχετικά με το HTTPS και τα πιστοποιητικά SSL.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: από τον/την Automattic – 3.5.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Βάση καταστήματος: #5 - /shop/
Καλάθι: #6 - /cart/
Ταμείο: #7 - /checkout/
Ο λογαριασμός μου: #8 - /my-account/
Όροι και Προϋποθέσεις: ❌ Η σελίδα δεν ορίστηκε

### Theme ###

Name: Twenty Sixteen
Version: 1.8
Author URL: https://wordpress.org/
Child Theme: ❌ – Αν κάνετε μετατροπή του WooCommerce πάνω σε ένα γονικό θέμα που δεν δημιουργήσατε εσείς προσωπικά
τότε σας προτείνουμε να χρησιμοποιήσετε ένα θέμα απόγονο. Δείτε: Πως να δημιουργήσετε ένα θέμα απόγονο

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
```
</details>

**Comment by rrennick** [comment]
> When we have a product with stock (2) and someone order all of them or some of them and the order has "pending payment" status, then in the backend we still see that this product has still "2 on stock".

I tested this in my install and after placing the order

<img width="815" alt="screen shot 2019-01-24 at 2 58 37 pm" src="https://user-images.githubusercontent.com/343847/51701814-a9040f00-1fe8-11e9-8607-07a2535f31e5.png">

The item is out of stock

<img width="677" alt="screen shot 2019-01-24 at 2 58 14 pm" src="https://user-images.githubusercontent.com/343847/51701894-cafd9180-1fe8-11e9-9a0b-4c7092a49c03.png">

My order status is `On Hold` not `Pending Payment`. Are you manually entering the orders in the dashboard?

**Comment by plxrisa** [comment]
I'm sorry for the confuse... I mean... (IF you change the status to "pending payment" for any reason OR add manually an order with "pending payment" status).
The main problem is that the system holds these products as it should, but...
1. Doesn't hide the product from the frontend.
2. A new client can still add them in the cart, until he will go to cart and see the error message.
3. The store owner see wrong informations in the backend about the stock.

You can see the issue #21772 and its comments for extra details and steps to reproduce the issue.

**Comment by rrennick** [comment]
> IF you change the status to "pending payment" for any reason

Switching to pending payment status puts the items on the order back in stock. That is done intentionally.

**Comment by plxrisa** [comment]
>Switching to pending payment status puts the items on the order back in stock.

1. So, why if you have an order in pending payment, the system shows this error message to a new client (Sorry, we don't have enough stock to fulfill your order) in cart page, when he tries to buy a new one?

**Comment by rrennick** [comment]
@plxrisa Thanks. I was able to reproduce the error message.

**Comment by rrennick** [comment]
@plxrisa I investigated this and it works this way by design. The only 2 places WC checks for stock on pending payment orders is the cart and checkout. Would you like to change this to a feature request?

**Comment by plxrisa** [comment]
@rrennick Sure, if you can you can change it to a feature request. In my opinion the "pending payment" status doesn't work well. It's a little bit confusing the way that works.

Think this scenario: I have two blouses only left in my shop. You (as a client) buy both of them and your order is "pending payment". That means that I don't have another blouse for another client. Then:
1. Why WC inform me (as shop owner in the backend) that I still have two blouses? And why lets me add these 2 in future manual order? If I sell them manually in a next order, then you will call me and complain that I sell your products and didn't hold them for you.
2. Why this blouse is still on frontend? It must respect my setting (hide products that are out of stock).

That's why I wrote above in my issue that I believe that "pending payment" status must works like "on hold" with the only different the autocancel.

Before I wrote this issue I was searching what's going wrong and I found that in facebook groups people ask the same question. For example here is one of the comments from fb that I found...

> Orders marked as "pending" doesnt remove the stock of the purchased products...so people could buy more products than the ones I have on stock. Anyone can advice me on this please? any clue why this is happening?

Also, as @mikejolley wrote, maybe this is the reason for the issue #22118.

I believe that if it works like "on hold" it will be better and shop owners will not have these problems. But as I said, this is only my opinion, because you guys know better the WC core and how must works.

**Comment by rrennick** [comment]
@plxrisa I understand your point. I was a bit surprised that no one has written an extension that removes the pending orders from stock. However, a customer cannot create on order with a pending payment status. Only shop managers can do that.

I'll edit the title of the issue to better reflect the feature request.

**Comment by Jan-from-Babydk** [comment]
Hey

I've had the same issue regarding the "Hold/release stock on pending orders" and customers get the message "Sorry, we do not have enough “item” in stock to fulfil your order... ( 0 available)" for some time...

I've just updatede to Woocommerce 3.6.4 and Woocommerce Quickpay 5.0.0, and is pretty frustrated about this situation. 

Wha's the best way to handle this issue?
- setting "on hold" timer to blank/"0"/10.080?
- putting orders on hold/pending/processing?

Is there any workaround available?

Looking forward to here more.

Thanks

//Best regard 
Jan
