### ISSUE TITLE
Star Ratings on screen readers seem to cause a hissing sound on product pages

### ISSUE THREAD

**Issue by stuartduff** [woocommerce/woocommerce#22552]
**Is your feature request related to a problem? Please describe.**

We got a report from a customer 1739859-zen who uses a screen reader that when viewing a product they were hearing a strange hissing sound. The screen readers which were being used were [JAWS 2019](https://www.freedomscientific.com/downloads/jaws/JAWSWhatsNew) and [NVDA 2018.4](https://www.nvaccess.org/post/nvda-2018-4-now-available/) which both running on Windows 10 Using Chrome but the same thing happens in Firefox too.

Upon inspection, we found that if the `font-family: star` is not loaded the star rating display as a series of `S` like this example below and it seems to be the `SSSSSS` which are causing the noise when browsing a site using a screen reader.

![screen shot 2019-01-23 at 17 36 54](https://user-images.githubusercontent.com/1190565/51691951-bffc2e80-1ff3-11e9-8d2d-c4760e73638d.png)

![annotation on 2019-0-3](https://user-images.githubusercontent.com/1190565/51691769-5419c600-1ff3-11e9-9cb4-92afef8772a3.png)

**Describe the solution you'd like**

For accessibility, it may be better with screenreaders to display the score of the rating like a 4.5 or similar so that is referenced and remove the icon fonts which don't seem to load on screen readers

**Comment by kloon** [comment]
See #22595 for a fix. Best solution without causing too many issues is to hide the star rating icons from screen readers using area-hidden.
