### ISSUE TITLE
"Products" widget and nofollow

### ISSUE THREAD

**Issue by Mitch13260** [woocommerce/woocommerce#22550]
Hi,
Link juice is important for the SEO of a shop. It would be very good to be able to activate the nofollow in the product widget of the sidebar...

**Comment by mikejolley** [comment]
See https://docs.woocommerce.com/document/template-structure/

`templates/content-widget-product.php` is the one you can target and customise the markup.

Thanks

**Comment by mikejolley** [comment]
The line:

```
<a href="<?php echo esc_url( $product->get_permalink() ); ?>">
```

Becomes:

```
<a rel="nofollow" href="<?php echo esc_url( $product->get_permalink() ); ?>">
```

**Comment by Mitch13260** [comment]
Ok, sorry, it works!
Thank you for your help.
Have a good day ;)
