### ISSUE TITLE
Paypal decimal quantity problem solution

### ISSUE THREAD

**Issue by piotr-wroblewski** [woocommerce/woocommerce#22568]
Hi there,
  I had problem with decimal quatities passed to PayPal using build-in plugin. This was caused by using Quantities and Units plugin, quite old but providing possibility to handle decimal quantities as I needed. When I activated PayPal payments everything was fine besides decimal values - they were rounded down so customers were making incorrect payments. I needed decativate payment method last year. I was looking for different plugins and search different support forums but the solution is already in Woocommerce code - in class-wc-gateway-paypal-request.php - line 
  protected function get_line_item_args( $order, $force_one_line_item = false) 
Changing default value to true solves all my problems, one item per order is sufficient. You can find a lot of topics with this issue since 2013 and so on. 
It would be nice to have possibility to configure how PayPal payment plugin behaves - in some cases passing all order line items is not neccessary and not needed. Please consider add new option to plugin.

Best Regards
Piotr

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22653
