### ISSUE TITLE
Able to exceed coupon limit restrictions with guest checkout

### ISSUE THREAD

**Issue by FreshPhil** [woocommerce/woocommerce#22564]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
1. Create a coupon
2. Set Usage Limits to, 1 usage per user
3. Perform a guest checkout, while using the coupon
4. Return to the site and perform another checkout while using the coupon. This time though, opt into creating an account using the same email address
5. Note that you are able to use the coupon again using the same email

**Expected behavior**
If you have previously used a coupon on a guest checkout, that should count towards any coupon restrictions once you make a customer account.

Currently with a usage limit of 1, you could not use the same coupon for two guest checkouts using the same email. Nor can you use it for two checkouts while logged into an account. The combination of a guest checkout and logged in checkout should function the same way.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

Home URL: http://demo.local
Site URL: http://demo.local
WC Version: 3.5.4
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.10.1
PHP Version: 7.0.3 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 1,000 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 3.08MB
Database Data Size: 1.93MB
Database Index Size: 1.15MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.02MB + Index: 0.05MB
wp_postmeta: Data: 0.33MB + Index: 0.30MB
wp_posts: Data: 0.08MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 39
customize_changeset: 4
page: 6
post: 2
product: 24
product_variation: 56
revision: 4
shop_coupon: 1
shop_order: 3

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Stripe Gateway: by WooCommerce – 4.1.14
WooCommerce: by Automattic – 3.5.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.4.2
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by mihaigrigori** [comment]
@FreshPhil were you able to actually place an order with the same coupon or just to add the coupon on the cart page?

**Comment by AngeloLazzari** [comment]
Hi @mihaigrigori, i am the one found the issue in one of my ecommerce, yes, the same client has placed an order with guest using the user discount limitation to 1, and after a few weeks the same user ( same email ) used the same discount code doing the registration process and placing successfully another order. thank you

**Comment by FreshPhil** [comment]
@mihaigrigori my apologies, you are correct. I was able to apply the coupon, but still received the proper error when trying to complete the order.

@AngeloLazzari I have tried a few different steps to replicate the issue you experienced, even including clearing customer sessions. However, I have not been able to replicate this. Once I click the "Place Order", I receive a message that the coupon usage limit has been reached.

When you look both orders on your site, are they using the same billing email? As that is what is used from your guest checkout.

If you find that you are able to replicate this still on your site, I'd recommend doing some theme and plugin conflict testing. We have a guide on how to test for conflicts here:
https://docs.woocommerce.com/document/woocommerce-self-service-guide/#section-4

If you are still able to replicate this when using either the Twenty Nineteen or Storefront theme, with all other plugins disabled - place make a new issue here on Github with the steps.

**Comment by FreshPhil** [comment]
@AngeloLazzari thank you for the extra details. Using that info I was able to reproduce this issue and confirmed the steps and cause. As it differs from the original issue that I reported, I've created a new issue with the proper steps to reproduce. You can find that here:  #22623

**Comment by AngeloLazzari** [comment]
@FreshPhil great news!!! I am happy to help!!! thank you very much!
