### ISSUE TITLE
HTML tags should be stripped from description in Structured Data of Product 

### ISSUE THREAD

**Issue by noelmcg** [woocommerce/woocommerce#22565]
As per the title, I believe html tags should be stripped from the description in the products structured data.

Propose using ```wp_filter_nohtml_kses``` as opposed to ```wpautop```

woocommerce/includes/class-wc-structured-data.php
Line 213:

```
$markup['description'] = wpautop( do_shortcode( $product->get_short_description() ? $product->get_short_description() : $product->get_description() ) );
```

**Comment by claudiulodro** [comment]
Agreed. The HTML isn't going to get displayed in the search result preview on Google, so it doesn't make sense to have it and may even cause issues.

**Comment by claudiulodro** [comment]
That would work great. Thanks!
