### ISSUE TITLE
Request to add new filter hook to filter customer list on admin report.

### ISSUE THREAD

**Issue by sayful1** [woocommerce/woocommerce#22579]
To create customer list, current user query exclude all admin users and manager users. But there is no way to filter to add more user to exclude list. In our case, we added new user role called "sales agent". We also want to exclude "sales agent" from customer list.

I made some modification at following file to achieve my desired functionality. 

File: [woocommerce/includes/admin/reports/class-wc-report-customer-list.php](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/reports/class-wc-report-customer-list.php)

Current code:
```
$query = new WP_User_Query(
    array(
        'exclude' => array_merge( $admin_users->get_results(), $manager_users->get_results() ),
        'number'  => $per_page,
        'offset'  => ( $current_page - 1 ) * $per_page,
    )
);
```

Modified code:
```
$query = new WP_User_Query(
    apply_filters('woocommerce_admin_report_customer_query_args',array(
        'exclude' => array_merge( $admin_users->get_results(), $manager_users->get_results() ),
        'number'  => $per_page,
        'offset'  => ( $current_page - 1 ) * $per_page,
    ))
);
```

**Comment by kloon** [comment]
See #22605
