### ISSUE TITLE
test install script (tests/bin/install.sh) fails with error "bad flag in substitute command" if password has a '/' character.

### ISSUE THREAD

**Issue by outis** [woocommerce/woocommerce#22577]
**Describe the bug**
If the password passed to tests/bin/install.sh contains a forward slash, then the script will fail while updating wp-tests-config.php with the error message:
> sed: 1: "s/yourpasswordhere/ ...": bad flag in substitute command: 'X'

where 'X' is the character following the '/'.

**To Reproduce**
1. Open a terminal
2. Go to the woocommerce directory.
3. Run the test install script using a password that contains a '/'. For example:
    <samp>tests/bin/install.sh wooc_test wooc '____/____'</sam>

**Expected behavior**
The install script should run without error with valid DB credentials, no matter what characters are in the DB password used.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

**Comment by outis** [comment]
The cause is clear: install.sh interpolates the password directly into a sed script without handling any special characters. If there's a '/', it ends the regex early, causing the following characters to be interpreted as regex flags.

**Comment by rrennick** [comment]
@outis Could you submit your recommended changes through a pull request?

**Comment by outis** [comment]
Will do. I've almost done so, but every time I think I've got a complete fix, I realize there's a case that isn't handled.

I started out trying to detect when the user had escaped the forward slash, and not add extra escapes. However, it might make sense to assume the user hasn't done this and escape all slashes (and '&'), so as to also preserve escaped backslashes. In the current version, backslashes get reduced (e.g. '_\\_' becomes '_\_'). What do you think?

**Comment by rrennick** [comment]
> it might make sense to assume the user hasn't done this

If you add/update documentation to the script that makes clear that it expects unescaped passwords that should do the trick.

**Comment by mikejolley** [comment]
Thanks.

See https://github.com/woocommerce/woocommerce/pull/22634
