### ISSUE TITLE
"display: block" for billling address labels

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce#22576]
Passing a question from our user here:

> In the latest versions of WooCommerce, why do you suddenly enforce a "display: block" via JS on some billing form fields? For example:
> 
> &lt;p class="form-row form-row-wide no-invoice validate-required" id="billing_address_1_field" data-priority="50" style="display: block;"&gt; 
> 
> This is ruining our design, as we can't use the CSS flexbox model anymore because the injected block display takes precedence. 

This is an example of the property:

![http://cld.wthms.co/DcEjOe](http://cld.wthms.co/DcEjOe+) 
Full Size: http://cld.wthms.co/DcEjOe

The question is also: why was this added for forcing display block on billing address fields?

**Comment by tbnv** [comment]
Hello,

Thanks for having opened this issue.

I didn't notice this in the screenshot you sent by email, but they are not relevant. As you can see in the code snipped you pasted (and that I gave you via email support ticket), `display: block` is injected on paragraph level (see `form-row`). The screenshot points to the `label` element however.

When I disable the JS scripts embedded by WooCommerce, these inline `display: block` style properties disappear.

**Comment by rrennick** [comment]
Can you provide more of the technical details like WC version where this worked & version where it doesn't? Your system status report might also be helpful.

**Comment by tbnv** [comment]
It was working properly with version 3.5.3, and it's causing issues since version 3.5.4.

When I replace the whole `woocommerce` plugin folder with version 3.5.3, the problem disappears. As soon as I place version 3.5.4 back, the issue is back as well.

Also, if I disable WC javascripts, the inline `display: block` style is not injected (but then I loose other features, so I can't remove `localize_printed_scripts`).

**Comment by tbnv** [comment]
I'm willing to disable this script since it's bringing even more trouble than this. However, it looks like this "address" script doesn't only apply to the address fields, but also control the payment method accordion? Weird.

**Comment by mikejolley** [comment]
address-18n.js and country-select.js scripts both hide and show fields. Both of these scripts use jquery `hide()` and `show()` functions to control address field visibility.

Looking now I don't think there is a problem with that specifcally, and adding a class isn't going to change that.

> I want the checkout process to be as easy as possible for our customers, and not ask useless information. For instance, only a few of our customers need a proper invoice. So I added a checkbox for requesting an invoice. When this checkbox is ticked, then I display the billing address fields.

Sounds in fact like you want to toggle visibility of all fields, but then these scripts put the fields back.

Perhaps the best solution for your case would be to try and wrap all fields in another element you can target.  You could target `woocommerce-billing-fields` or adjust the form-billing.php template file to add new wrappers.

Thats not something we can support here as it's custom development, but thats what you'll need to do if you're overriding the default hide/show logic with something custom.

Hope this puts you on the correct track.

Thanks
