### ISSUE TITLE
Please add gallery_thumbnail_image_width to Customizer

### ISSUE THREAD

**Issue by komarovartem** [woocommerce/woocommerce#22575]
Hello. The issue is gallery_thumbnail_image_width the only size which is not covered by customizer options. While single and thumbnail can be changed easily the gallery_thumbnail size has to be changed via a custom function what makes it really inconvenient. The default sizes for single and thumbnail are ok even without changes for 90% of e-commerce websites but 100x100 gallery_thumbnail is extremely small especially when no srcset is provided (issue with quality on the retina). Please consider adding the gallery_thumbnail size to the customizer. Thank you.

**Comment by mikejolley** [comment]
We don't allow widths to be set via customiser because there is no visible difference--all images are scaled with CSS.

We allow the aspect ratio to be changed only.

Actual image sizes are filterable.

```
woocommerce_get_image_size_gallery_thumbnail
```

Thanks

**Comment by komarovartem** [comment]
Hello, thank you for an answer.
> We don't allow widths to be set via customiser because there is no visible difference--all images are scaled with CSS.
That is exactly what you are doing, you allow change width of images via the customizer all your opinions called

- single_image_width
- gallery_thumbnail_image_width
- thumbnail_image_width

and they assign to `$size['width']` property. 

And as I described in the first comment, there is a HUGE visible difference for gallery_thumbnail_image since it has no srcset and for any displays with a high pixel density gallery thumbnails look blurry. 

Maybe I was misunderstood. I just think that it would be really good to add "woocommerce_gallery_thumbnail_image_width" option to customizer so wc-core-functions.php would look like this

`absint( wc_get_theme_support( 'gallery_thumbnail_image_width', get_option( 'woocommerce_gallery_thumbnail_image_width', 100 ) ) );`

Please consider reopening this request. Thank you

**Comment by mikejolley** [comment]
Those widths only display if the theme does not declare support for WC. I'll mark this for votes - as I said, there is a filter to do exactly what you want.
