### ISSUE TITLE
woocommerce_checkout_fields doesn't work properly after 3.5.4 update

### ISSUE THREAD

**Issue by alirezakafi** [woocommerce/woocommerce#22578]
**Describe the bug**
i used **woocommerce_checkout_fields** filter to customize my billing address in checkout but after update, **billing_address_1_field** and **billing_address_2_field** order turned to default order and it doesn't care about priority i defined in my functions.php hook , also their label and placeholder turned to default value

my code for reordering billing fields:
```
$billing_order = array(
        "billing_first_name", 
        "billing_last_name", 
        "billing_company", 
        "billing_phone",
        "billing_email", 
        "billing_country", 
        "billing_state", 
        "billing_city", 
        "billing_postcode", 
        "billing_address_1", 
        "unloading_place" , 
        "billing_address_2", 
    );

    $count = 0;
    $priority = 10;

    foreach($billing_order as $field_name){
        $count++;
        $fields['billing'][$field_name]['priority'] = $count * $priority;
    }
```

also my code for change address_1 and address_2 label and placeholder:
```
$fields['billing']['billing_address_1']['label'] = 'something...';
    $fields['billing']['billing_address_1']['placeholder'] = 'something...';

    $fields['billing']['billing_address_2']['label'] = 'something...';
    $fields['billing']['billing_address_2']['placeholder'] = 'something...';
    $fields['billing']['billing_address_2']['class'] = array('hidden');
```

**Screenshots**

![untitled-1](https://user-images.githubusercontent.com/27764895/51798791-523b4700-222d-11e9-91a0-669885ca2dfa.png)

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/issues/22542

Default locales are applied on checkout load - this was broken in older versions and only triggered after changing too/from a country.
