### ISSUE TITLE
Support no product data storage

### ISSUE THREAD

**Issue by iDevelopper** [woocommerce/woocommerce#22585]
Hey there,

I post this question here as I can't find any response with Google, SO, or forums.

What is the best way to store data that is not for sale?

I develop a site to sell art objects (paintings, sculptures, ...) and I have to store the artists somewhere and have access to the description of the artist from the works of the shop presented to users.

Do we need to create artists as virtual products, or is there another solution? (I mean, without changing any code).

Could you give me a starting point, please?

Regards,

**Comment by rrennick** [comment]
Github isn't for support. For your question I suggest asking in https://woocommerce.slack.com/.

**Comment by iDevelopper** [comment]
Thanks, could you send me an invitation please?

**Comment by iDevelopper** [comment]
Thanks
