### ISSUE TITLE
not possible to force reload_checkout

### ISSUE THREAD

**Issue by adam-deep-co-uk** [woocommerce/woocommerce#22583]
in class-wc-ajax.php line 355 we have first 
unset( WC()->session->refresh_totals, WC()->session->reload_checkout );
and directly after that
isset( WC()->session->reload_checkout ) ? true : false

how can reload_checkout be set if we just unset it, what sense does it make?

**Comment by rrennick** [comment]
The blame indicates that the `isset()` is at least 4 years old & the `unset()` was added 2 years ago so the `isset()` was left behind as an oversight.

**Comment by kloon** [comment]
See #22594
