### ISSUE TITLE
Customer IP address isn't anonymized

### ISSUE THREAD

**Issue by cubottaedro** [woocommerce/woocommerce#22588]
Customer IP address, which is shown at least in _Edit order_ page, isn't removed when performing _Remove personal data_ bulk action in _Orders_ page.

Customer IP address should be removed along with other personal data.
In fact,  in [class-wc-privacy-erasers.php](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-privacy-erasers.php) _customer_ip_address_ is among the prop names to be passed to _wp_privacy_anonymize_data()_.

---

WooCommerce version: 3.5.4
WordPress version: 5.0.3

**Comment by rrennick** [comment]
I have been able to reproduce this in my dev install.

**Comment by kloon** [comment]
In my tests it works as expected. Can you confirm the IP address is exactly the same? For IP addresses wp_privacy_anonymize_data calls wp_privacy_anonymize_ip which basically just changes the last octet of the IP address to a 0 in most cases to anonymize it.

It would be helpful if you can provide before and after screenshots of your order, also ensure the option is enabled under WooCommerce -> Settings -> Accounts/Privacy to allow deletion of order data.

**Comment by cubottaedro** [comment]
I'm sorry, my fault. The last octet is changed to 0.
Certainly not a bug, but since I'm here I've a question. It seems to be a common practice, but in this very context (where all the other data are completely removed), is changing the last octet of the IP address enough?

**Comment by rrennick** [comment]
> The last octet is changed to 0.

Sorry, I didn't notice that because my original address was 127.0.0.1.
