### ISSUE TITLE
Can't delete/update produts

### ISSUE THREAD

**Issue by santoslopes** [woocommerce/woocommerce#22582]
The RestApi allows to read/write. I can list all the products but can't update or delete products. Got the error:
`raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`
My code:
`
from woocommerce import API
wcapi = API(    
    url="https://pentaculo.programamos.pt",
    consumer_key="ck_",
    consumer_secret="cs_",        
    version="wc/v3",
    timeout=30    
)
print(wcapi.delete("products/109?force=true").json())

`

**Comment by rrennick** [comment]
I'm not able to reproduce this in my install. Without the `?force=true` the product was moved to the trash. With `?force=true` it was deleted from the DB. Can you provide the steps needed to reproduce this with a REST client?

**Comment by kloon** [comment]
Unable to replicate as well. What client library are you using to interact with the API? Can you do tests using cURL instead?

**Comment by santoslopes** [comment]
Hi
Here is my code with the correct keys. I can read products, but can't delete, update or insert products.
Any help?

`
from woocommerce import API
wcapi = API(    
    url="https://pentaculo.programamos.pt",
    consumer_key="ck_35b30a2113d0e9d33e8e73da3bf67c62f293e2e6",
    consumer_secret="cs_de6d08d57e0f16a16da2af24467e9e3bb389825a",        
    version="wc/v3",
    timeout=30    
)
print(wcapi.delete("products/109?force=true").json())
print(wcapi.get("products").json())
`

**Comment by santoslopes** [comment]
That's what I tought but the permission is read/write
Please look at the image [here](http://pentaculo.programamos.pt/chave.jpg)
I don't know what is the problem because I can read but not write, the key as Read/write permissions

**Comment by santoslopes** [comment]
That's what I tought, but the key as Read/Write permissions. Please check [here](http://pentaculo.programamos.pt/chave.jpg)
I can read and can't write even though the key as read/write permissions.
Maybe the problem is outside woocommerce but where? In the certificate? I use PLESK and Let's Encript.

**Comment by kloon** [comment]
Again, I am not sure the library you are using here. Can you try with just a cURL request from command line? Also be sure to pass the content type as application/json when making requests.

**Comment by santoslopes** [comment]
Sorry my friend but I don't know how to do that. Can you point me in the right direction?

**Comment by rrennick** [comment]
The cURL samples are on the right - https://woocommerce.github.io/woocommerce-rest-api-docs/v3.html#products

**Comment by mikejolley** [comment]
Using a REST API client might show the real response. https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API#making-a-basic-request

You're seeing the result of a JSON decode on broken JSON.

https://stackoverflow.com/questions/50044698/python-woocommerce-api-jsondecodeerror-expecting-value

Find the source of the error/notice and this issue should clear up. It's not a problem in the API itself.

Thanks
