### ISSUE TITLE
wc_get_rating_html should not be sanitize via wp_kses_post

### ISSUE THREAD

**Issue by komarovartem** [woocommerce/woocommerce#22592]
Hi, I'm using SVG icons for the star rating and it works except content-widget-product.php because it is sanitized with wp_kses_post. So it is not a content it should not be sanitized with this function since it removes all unsupported tags. Moreover, content-widget-product.php is the only template with this issue since all other templates with wc_get_rating_html do not have sanitization of the entire function. Regards.

**Comment by kloon** [comment]
See #22593
