### ISSUE TITLE
set_prop method of WC_Data should be public

### ISSUE THREAD

**Issue by dakshhmehta** [woocommerce/woocommerce#22607]
When trying to use the class to set the property on a product, outside of the wooCommerce scope.

For example, in another hook, the method set_prop of WC_Data class is protected, whereas set_props is public.

Both should be public, so we can do following:
```php
add_action('some_hook', function(){
    $product = new WC_Product_Simple(100);
    $product->set_prop('sku', $product->get_sku().'-POSTFIX');
    $product->save();
});
```

Use Case: This is very useful when a product property needs to be updated from another plugin meta value.

Real World Example:
To copy gallery images of parent product to all child variations automatically when parent is saved.

Implementation:
Change keyword protected to public at https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-data.php#L666

**Comment by mikejolley** [comment]
Hi,

This is protected by design. Please use `set_sku` or the specific setters. This is to avoid developers bypassing any logic in the setter, e.g. data validation.

cc @woocommerce/proton  

Thanks

**Comment by dakshhmehta** [comment]
Well, what If I want to modify the WC_Product_Simple class in that case to add my own custom property name related to our proprietary plugin?

**Comment by mikejolley** [comment]
You can extend the class into a new product price, or use the set_meta etc functions instead. There are ways to register extra data. But changing all props is not allowed. Props are private.

**Comment by dakshhmehta** [comment]
Can I get a demo link to know this? Sorry if Im dragging this issue but really require a solid solution.

**Comment by mikejolley** [comment]
I don't have a link to docs but this covers meta usage https://catapultthemes.com/add-custom-fields-woocommerce-product/

**Comment by plugin-republic** [comment]
Just confirming that the link above should be updated to [https://pluginrepublic.com/add-custom-fields-woocommerce-product/](https://pluginrepublic.com/add-custom-fields-woocommerce-product/).
Thanks.
