### ISSUE TITLE
Hidden Product Shows Up in Search

### ISSUE THREAD

**Issue by ercousin** [woocommerce/woocommerce#22622]
**Describe the bug**
I have added several products as Hidden, yet they still show up in search results.

**Screenshots**

**Product Hidden**

![image](https://user-images.githubusercontent.com/1551339/52064683-1660f400-2543-11e9-8539-e22302256e3b.png)

**Search Results Show Hidden Products**

![image](https://user-images.githubusercontent.com/1551339/52064592-f16c8100-2542-11e9-8272-fca122726b57.png)

**Expected behavior**
I expect these products not to show up in shop or search results.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
I don't have a dev site to do this on
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

`
### WordPress Environment ###

Home URL: https://www.gtabrews.ca
Site URL: https://www.gtabrews.ca
WC Version: 3.5.4
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.33 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.59.0
OpenSSL/1.0.2q

SUHOSIN Installed: –
MySQL Version: 5.6.40-84.0-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.4
WC Database Prefix: wp_rcqv_
MaxMind GeoIP Database: ✔
Total Database Size: 30.52MB
Database Data Size: 24.57MB
Database Index Size: 5.95MB
wp_rcqv_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB
wp_rcqv_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_rcqv_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_rcqv_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_rcqv_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB
wp_rcqv_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB
wp_rcqv_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_rcqv_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_rcqv_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_rcqv_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_rcqv_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_rcqv_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_rcqv_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_rcqv_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_rcqv_commentmeta: Data: 0.04MB + Index: 0.01MB
wp_rcqv_comments: Data: 0.15MB + Index: 0.06MB
wp_rcqv_ewwwio_images: Data: 0.01MB + Index: 0.01MB
wp_rcqv_links: Data: 0.00MB + Index: 0.00MB
wp_rcqv_mepr_events: Data: 0.38MB + Index: 0.66MB
wp_rcqv_mepr_jobs: Data: 0.02MB + Index: 0.14MB
wp_rcqv_mepr_members: Data: 0.08MB + Index: 0.27MB
wp_rcqv_mepr_rule_access_conditions: Data: 0.02MB + Index: 0.05MB
wp_rcqv_mepr_subscriptions: Data: 0.06MB + Index: 0.30MB
wp_rcqv_mepr_subscription_meta: Data: 0.02MB + Index: 0.03MB
wp_rcqv_mepr_tax_rates: Data: 0.02MB + Index: 0.14MB
wp_rcqv_mepr_tax_rate_locations: Data: 0.02MB + Index: 0.06MB
wp_rcqv_mepr_transactions: Data: 0.11MB + Index: 0.36MB
wp_rcqv_mepr_transaction_meta: Data: 0.02MB + Index: 0.03MB
wp_rcqv_options: Data: 1.35MB + Index: 0.58MB
wp_rcqv_postmeta: Data: 1.58MB + Index: 0.56MB
wp_rcqv_posts: Data: 13.40MB + Index: 0.27MB
wp_rcqv_redirection_404: Data: 0.02MB + Index: 0.06MB
wp_rcqv_redirection_groups: Data: 0.02MB + Index: 0.03MB
wp_rcqv_redirection_items: Data: 0.02MB + Index: 0.08MB
wp_rcqv_redirection_logs: Data: 0.06MB + Index: 0.08MB
wp_rcqv_termmeta: Data: 0.00MB + Index: 0.01MB
wp_rcqv_terms: Data: 0.01MB + Index: 0.01MB
wp_rcqv_term_relationships: Data: 0.01MB + Index: 0.03MB
wp_rcqv_term_taxonomy: Data: 0.01MB + Index: 0.01MB
wp_rcqv_usermeta: Data: 0.93MB + Index: 0.52MB
wp_rcqv_users: Data: 0.06MB + Index: 0.06MB
wp_rcqv_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_rcqv_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_rcqv_wfBadLeechers: Data: 0.00MB + Index: 0.00MB
wp_rcqv_wfBlockedCommentLog: Data: 0.02MB + Index: 0.00MB
wp_rcqv_wfBlockedIPLog: Data: 0.00MB + Index: 0.01MB
wp_rcqv_wfBlocks: Data: 0.00MB + Index: 0.00MB
wp_rcqv_wfBlocks7: Data: 0.02MB + Index: 0.05MB
wp_rcqv_wfBlocksAdv: Data: 0.00MB + Index: 0.00MB
wp_rcqv_wfConfig: Data: 1.11MB + Index: 0.01MB
wp_rcqv_wfCrawlers: Data: 0.01MB + Index: 0.00MB
wp_rcqv_wfFileChanges: Data: 0.02MB + Index: 0.00MB
wp_rcqv_wfFileMods: Data: 1.05MB + Index: 0.24MB
wp_rcqv_wfHits: Data: 1.12MB + Index: 0.37MB
wp_rcqv_wfHoover: Data: 0.00MB + Index: 0.00MB
wp_rcqv_wfIssues: Data: 0.05MB + Index: 0.01MB
wp_rcqv_wfKnownFileList: Data: 1.52MB + Index: 0.00MB
wp_rcqv_wfLeechers: Data: 0.09MB + Index: 0.08MB
wp_rcqv_wfLiveTrafficHuman: Data: 0.05MB + Index: 0.05MB
wp_rcqv_wfLockedOut: Data: 0.00MB + Index: 0.00MB
wp_rcqv_wfLocs: Data: 0.01MB + Index: 0.00MB
wp_rcqv_wfLogins: Data: 0.37MB + Index: 0.09MB
wp_rcqv_wfNet404s: Data: 0.00MB + Index: 0.00MB
wp_rcqv_wfNotifications: Data: 0.02MB + Index: 0.00MB
wp_rcqv_wfPendingIssues: Data: 0.02MB + Index: 0.06MB
wp_rcqv_wfReverseCache: Data: 0.00MB + Index: 0.00MB
wp_rcqv_wfScanners: Data: 0.02MB + Index: 0.02MB
wp_rcqv_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wp_rcqv_wfStatus: Data: 0.15MB + Index: 0.06MB
wp_rcqv_wfThrottleLog: Data: 0.00MB + Index: 0.00MB
wp_rcqv_wfTrafficRates: Data: 0.02MB + Index: 0.00MB
wp_rcqv_wfVulnScanners: Data: 0.00MB + Index: 0.00MB
wp_rcqv_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_rcqv_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 574
calendar: 1
customize_changeset: 2
custom_css: 1
memberpressproduct: 4
memberpressrule: 5
nav_menu_item: 44
page: 56
post: 104
product: 16
product_variation: 14
revision: 1658
safecss: 1
shop_order: 168
shop_order_refund: 2
tablepress_table: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

VaultPress: by Automattic – 1.9.7
BAW Login/Logout menu: by Juliobox – 1.3.3
BeerXML Shortcode: by Derek Springer – 0.7.1
Duplicate Post: by Enrico Battocchi – 3.2.2
Easy Table of Contents: by Steven A. Zahm – 1.7
Jetpack by WordPress.com: by Automattic – 6.9
MCE Table Buttons: by Jake Goldman
10up
Oomph – 3.3

MemberPress MailChimp 3.0: by Caseproof
LLC – 1.1.7

MemberPress WooCommerce: by Caseproof
LLC – 1.0.5 – Not tested with the active version of WooCommerce

MemberPress Business Edition: by Caseproof
LLC – 1.3.51

Public Post Preview: by Dominik Schilling – 2.8.0
SG Optimizer: by SiteGround – 5.0.13
Theme Authenticity Checker (TAC): by builtBackwards – 1.5.3
Use Google Libraries: by Jason Penney – 1.6.2.3
WooCommerce Blocks: by Automattic – 1.3.1 – Not tested with the active version of WooCommerce
Advanced Order Export For WooCommerce: by AlgolPlus – 2.0.1 – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.8 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.1.14 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.18.0 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.5.4
Wordfence Security: by Wordfence – 7.1.20

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #1457 - /shop/
Cart: #1458 - /cart/
Checkout: #1459 - /checkout/
My account: #1460 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Thirteen
Version: 2.7
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

**Comment by mikejolley** [comment]
Hi,

The catalog visibility option does not hide products from showing on all pages (i.e. products can be found directly and can surface in things like main search results). The setting hides products from shop loops that WooCommerce is responsible for. shop page, categories, anywhere where outputs the list of products.

If you add `&post_type=product` to the URL you'll see product search results. They will be hidden there. This is the URL the product search widget uses.

It's not possible to hide them on your main search page unless you modify your theme files. If you want to include that functionality, see what template file it uses for search results and start there.

Thanks!

**Comment by mikejolley** [comment]
Possibly with the blocks plugin yes - I'm not sure where blocks pulls that count.

**Comment by ercousin** [comment]
As an experiment I updated some of my products to Visibility="Shop&Search Results" and now they show up.

I think this should be considered a bug, since we shouldn't have to add products to our main shop to be able to add them to posts using blocks.

**Comment by mikejolley** [comment]
@ercousin Would you mind putting a report in for the count issue? https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues
