### ISSUE TITLE
Add support for Postgres database

### ISSUE THREAD

**Issue by javadev** [woocommerce/woocommerce#22627]
**Is your feature request related to a problem? Please describe.**
It will be nice to have a Postgres database support out of the box from woocommerce developers.

**Describe the solution you'd like**
It may be a driver pg4wp which retranslate mysql scripts to the postgres scripts.

**Describe alternatives you've considered**
I tested a modified driver it works. But I am not sure about all functionality.
https://github.com/php4dev/heroku-wordpress/commit/9c90b6a99bff4128564bd8ced8377b7ef624f88d

**Additional context**
Postgresql is a default database in heroku. It will be nice to have an official support and installation for it.

**Comment by mikejolley** [comment]
Hi 

This is something which would need to happen at the WordPress level.

Looks like there is a doc here on the subject https://codex.wordpress.org/Using_Alternative_Databases#Extend_to_support_PostgreSQL

Officially WP supports only MariaDB and MySQL. If this changes in the future we'll be sure to test for compatibility.

Thanks
