### ISSUE TITLE
Refunded order does not reduce tax amount on tax report.

### ISSUE THREAD

**Issue by sayful1** [woocommerce/woocommerce#22636]
When I refund an order partially, it does not have any reflect on tax report.

**Steps to reproduce the behavior:**
1. Go to store and add some products. Then complete checkout process.
2. Go to admin WooCommerce -> Order and open the order.
3. Set order status as processing and refund order with 50% of its total amount.
4. Notice though total amount is reduced but tax amount still same.
5. Not go to tax report. Here also tax report is showing with full tax amount.

**Screenshots**
![before-refund](https://user-images.githubusercontent.com/6873334/52161008-1995e480-26e9-11e9-9a2f-131ef7d8597d.png)
![after-refund](https://user-images.githubusercontent.com/6873334/52161006-18fd4e00-26e9-11e9-9505-349e234f111c.png)
![after-refund-tax](https://user-images.githubusercontent.com/6873334/52161007-18fd4e00-26e9-11e9-80f1-8b97f57e6a98.png)

**Expected behavior**
Tax also should reduce if order total amount is reduced.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WC Version: 3.5.4
WP Version: 5.0.3
Server Info: nginx/1.14.0
PHP Version: 7.0.33
Name: Storefront - 2.4.2
Active plugins:
WooCommerce Product Tables Feature Plugin: by Automattic – 1.0.0-dev – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.5.4

**Comment by kloon** [comment]
See #21843 It will be part of the 3.6.0 release.
