### ISSUE TITLE
WooCommerce Tax Calculation

### ISSUE THREAD

**Issue by vermadarsh** [woocommerce/woocommerce#22643]
**BUG**
Whenever an admin user creates an order from admin panel, in the store where the TAX calculations and use of coupons is active. There are certain standard tax rates being applicable, based on **customer shipping address**.
Now when the admin creates an order, adds an item and applies a coupon, the tax is being calculated based in store address, and not on customer's shipping address.
The complete bug is explained in the screencast attached.

**To Reproduce**
To reproduct the issue, kindly watch the screencast attached.

**Expected behavior**
I expect that when the tax calculations is set to be calculated based on customer's shipping address, then it should be calculated on customer's shipping address, irrelevant of the store address.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] I can reproduce this bug consistently watching the screencast attached above.

**WordPress Environment**
Version - 5.3

**WooCommerce Environment**
Version - 5.3.4
System status - [system-status.txt](https://github.com/woocommerce/woocommerce/files/2826899/system-status.txt)

Bug description - [woocommerce_tax_calculation_issue.zip](https://github.com/woocommerce/woocommerce/files/2826932/woocommerce_tax_calculation_issue.zip)

I hope you'll understand the issue. If I'm understanding WooCommerce in a wrong manner, please do let me know.

Thank you!

**Comment by rrennick** [comment]
> To reproduct the issue, kindly watch the screencast attached.

There is no screencast attached. Can you provide written instructions on reproducing the issue as the bug template requested?

**Comment by vermadarsh** [comment]
Hi @rrennick,
Here is the link to the screencast: https://www.dropbox.com/s/ms1wuokcnxk4qj3/woocommerce_tax_calculation_issue.mp4?dl=0

**Comment by mikejolley** [comment]
@rrennick Are you looking at this one? recalculate method in meta-boxes-order.js passes the unsaved address, whearas coupon application does not. Thats why it uses base address - the actual order address is not yet saved.

**Comment by vermadarsh** [comment]
Hi @mikejolley,
Thanks for this understanding. I got this by digging in the code, but as I mentioned in the expected result, that when I'm creating an order, apply coupons should also use the unsaved data anyhow.

As an end-user, non-technical site admin, I'd expect this result.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22802

**Comment by vermadarsh** [comment]
Thanks for the patch @mikejolley 
Hope to get this in the next release :smile:
