### ISSUE TITLE
WooCommerce VAT not visible in PayPal

### ISSUE THREAD

**Issue by JeffreyDamen** [woocommerce/woocommerce#22647]
Can someone tell me if WooCommerce sents tax data to PayPal?

Settings
- **Enable tax rates and calculations**
- **Yes, I will enter prices inclusive of tax**
- Set **Display prices in the shop** to **including tax**
- **Display prices during cart and checkout** to **including tax** 
- Imported all EU VAT rules using a CSV

WooCommerce does calculate the VAT for each order from an EU customer which is shown in each order and invoice. However, the VAT is not registered on my PayPal statements.

Is it possible to make the WooCommerce VAT match the PayPal payment statements too?

WooCommerce version: 3.5.2
WordPress version: 4.9.9

**Comment by JeffreyDamen** [comment]
Okay, I installed the "WooCommerce PayPal Checkout Payment Gateway" and the VAT appears on PayPal :)

**Comment by mikejolley** [comment]
VAT is transferred if items are sent individually, but not if the order is sent as a whole. Depends on your settings. Either way, VAT is stored WC side if you need to look it up for reporting.

Thanks
