### ISSUE TITLE
Reduce Stock at change from pending to processing or on-hold

### ISSUE THREAD

**Issue by McCharly** [woocommerce/woocommerce#22644]
We use WooCommerce Pre-Orders and WooCommerce

Before the last WooCommerce Update we had this scenario:
Our Customer make a pre-order, the product-stock reduce by 1.
If the pre-order is available we set them to complete and the order-status change to **pending** and the Customer gets an email with the payment-site to complete the order.
When they make the payment with paypal or amazon pay the order-status change to **processing**, when the customer wants to pay by Bank-Transfer the order-status changes to **on-hold**.
**In all cases there is no stock change, except the reduce at the pre-order!**

After the last Update, WooCommerce reduce the stock for a second time when the customer makes his decisson on the payment-site (at the monemt the order-status change to processing or on-hold).
So we've to increase the stock manualy every time a pre-order is paid.

Please let me know if we have to live with this or there is a chance to get the old scenario back?

**Comment by mikejolley** [comment]
Hi,

Stock reductions happen when certain order statuses are hit. 

https://github.com/woocommerce/woocommerce/blob/f13c62c5ea36083e9fe227209f43b71587b2832e/includes/wc-stock-functions.php#L100-L103

This is done once per order. 

https://github.com/woocommerce/woocommerce/blob/f13c62c5ea36083e9fe227209f43b71587b2832e/includes/wc-stock-functions.php#L87

Pre-order extensions may change this. Can you use the helpdesk if this is the "WooCommerce Pre-Orders" extension from woocommerce.com please?

Thanks
