### ISSUE TITLE
Importing Unpublished Variable Products Loses Price

### ISSUE THREAD

**Issue by jesse1981** [woocommerce/woocommerce#22657]
**Describe the bug**
Importing Product CSV containing variable products flagged as not published (`0`), the variable products do not display their price either in the admin or the shop pages.  If you simply edit a product and make no changes but hit "Update", it fixes that product.

**To Reproduce**
1. Export products from WooCommerce that contains at least one variable product
2. Delete all products
3. Import products using same CSV
4. Find one of the variable products - no price
5. Edit product and just click "Update"
6. The product now has the price displayed.

**Screenshots**
N/A

**Expected behavior**
Expect all products to have their price displayed, including variable.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] Untested: This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

Server info: |   | Apache
-- | -- | --
PHP version: |   | 7.2.14-1+ubuntu18.04.1+deb.sury.org+1
PHP post max size: |   | 100 MB
PHP time limit: |   | 3600
PHP max input vars: |   | 1000
cURL version: |   | 7.58.0, OpenSSL/1.1.1a
SUHOSIN installed: |   | –
MySQL version: |   | 5.6.34-log
Max upload size: |   | 50 MB
Default timezone is UTC: | [x]  |  
fsockopen/cURL: | [x] |  
SoapClient: | [x] |  
DOMDocument: | [x] |  
GZip: | [x] |  
Multibyte string: | [x] |  
Remote post: | [x] |  
Remote get: | [x] |  
</details>

**Comment by rrennick** [comment]
@jesse1981 Where are you seeing the price not displayed?

**Comment by rrennick** [comment]
I was able to confirm this. It also shows as out of stock on the front end.

**Comment by rrennick** [comment]
On further testing, the variable product price is not shown on imported products when `Published` is set to `0` on both the variable product and it's variants. 

A variant imported as unpublished is disabled. A variable product has no price or stock when none of its variants are enabled.

**Comment by rrennick** [comment]
@jesse1981 Sorry, I forgot to add if you import your variable products with one of the variants as published and still do not have a price shown please re-open with details on one of the variable products.

**Comment by jesse1981** [comment]
Hi @rrennick, thankyou, that's interesting!

Yes, that's true, all my variants were marked as unpublished. I'll do some further testing.

**Comment by jesse1981** [comment]
Hi again,

All good now, you were spot on.  I had some initial road-bumps in running a SQL to mass delete publish(ed) and mass update private to publish(ed), but that's all cleaned up now.
