### ISSUE TITLE
WooCommerce doesn't support attribute taxonomy creation on non startup.

### ISSUE THREAD

**Issue by chrono-meter** [woocommerce/woocommerce#22660]
**Describe the bug**
WooCommerce doesn't support attribute taxonomy creation on non startup.
My small patch is [here](https://gist.github.com/chrono-meter/5292f126c6399adb4e4d2a8cd3f33949).

**To Reproduce**
1. Create product attribute in REST hook.
2. That product attribute is not registered in same session.

**Screenshots**

**Expected behavior**
Call register_taxonomy on demand.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://www.paradishouse.jp
Site URL: https://www.paradishouse.jp
WC Version: 3.5.4
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: –
Language: ja
External object cache: –

### Server Environment ###

Server Info: nginx/1.4.6
PHP Version: 5.6.23-1+deprecated+dontuse+deb.sury.org~trusty+1 - より良いパフォーマンスとセキュリティを実現するには、PHP バージョン7.2以上の使用をおすすめします。 PHP のバージョンアップ方法
PHP Post Max Size: 1,000 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.60-0ubuntu0.14.04.1 - 推奨の最低限の MySQL バージョンは 5.6 です。参照:  WordPress 要件
Max Upload Size: 1,000 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.4
WC Database Prefix: paradis_wp_
MaxMind GeoIP Database: ✔
データベースの合計サイズ: 22.68MB
データベースのデータサイズ: 18.91MB
データベースのインデックスサイズ: 3.77MB
paradis_wp_woocommerce_sessions: データ: 0.02MB + インデックス: 0.02MB
paradis_wp_woocommerce_api_keys: データ: 0.02MB + インデックス: 0.03MB
paradis_wp_woocommerce_attribute_taxonomies: データ: 0.02MB + インデックス: 0.02MB
paradis_wp_woocommerce_downloadable_product_permissions: データ: 0.02MB + インデックス: 0.05MB
paradis_wp_woocommerce_order_items: データ: 0.02MB + インデックス: 0.02MB
paradis_wp_woocommerce_order_itemmeta: データ: 0.02MB + インデックス: 0.03MB
paradis_wp_woocommerce_tax_rates: データ: 0.02MB + インデックス: 0.06MB
paradis_wp_woocommerce_tax_rate_locations: データ: 0.02MB + インデックス: 0.03MB
paradis_wp_woocommerce_shipping_zones: データ: 0.02MB + インデックス: 0.00MB
paradis_wp_woocommerce_shipping_zone_locations: データ: 0.02MB + インデックス: 0.03MB
paradis_wp_woocommerce_shipping_zone_methods: データ: 0.02MB + インデックス: 0.00MB
paradis_wp_woocommerce_payment_tokens: データ: 0.02MB + インデックス: 0.02MB
paradis_wp_woocommerce_payment_tokenmeta: データ: 0.02MB + インデックス: 0.03MB
paradis_wp_woocommerce_log: データ: 0.02MB + インデックス: 0.02MB
paradis_wp_commentmeta: データ: 0.02MB + インデックス: 0.03MB
paradis_wp_comments: データ: 0.02MB + インデックス: 0.09MB
paradis_wp_links: データ: 0.02MB + インデックス: 0.02MB
paradis_wp_options: データ: 2.03MB + インデックス: 0.05MB
paradis_wp_postmeta: データ: 6.03MB + インデックス: 1.98MB
paradis_wp_posts: データ: 5.11MB + インデックス: 0.45MB
paradis_wp_termmeta: データ: 0.02MB + インデックス: 0.03MB
paradis_wp_terms: データ: 0.06MB + インデックス: 0.03MB
paradis_wp_term_relationships: データ: 0.25MB + インデックス: 0.14MB
paradis_wp_term_taxonomy: データ: 0.05MB + インデックス: 0.03MB
paradis_wp_usermeta: データ: 0.03MB + インデックス: 0.03MB
paradis_wp_users: データ: 0.02MB + インデックス: 0.05MB
paradis_wp_wc_download_log: データ: 0.02MB + インデックス: 0.03MB
paradis_wp_wc_webhooks: データ: 0.02MB + インデックス: 0.02MB
paradis_wp_wfblockediplog: データ: 0.02MB + インデックス: 0.00MB
paradis_wp_wfblocks7: データ: 0.02MB + インデックス: 0.05MB
paradis_wp_wfconfig: データ: 0.42MB + インデックス: 0.00MB
paradis_wp_wfcrawlers: データ: 0.02MB + インデックス: 0.00MB
paradis_wp_wffilechanges: データ: 0.02MB + インデックス: 0.00MB
paradis_wp_wffilemods: データ: 2.52MB + インデックス: 0.00MB
paradis_wp_wfhits: データ: 0.05MB + インデックス: 0.05MB
paradis_wp_wfhoover: データ: 0.02MB + インデックス: 0.02MB
paradis_wp_wfissues: データ: 0.02MB + インデックス: 0.06MB
paradis_wp_wfknownfilelist: データ: 1.52MB + インデックス: 0.00MB
paradis_wp_wflivetraffichuman: データ: 0.02MB + インデックス: 0.02MB
paradis_wp_wflocs: データ: 0.02MB + インデックス: 0.00MB
paradis_wp_wflogins: データ: 0.02MB + インデックス: 0.03MB
paradis_wp_wfnotifications: データ: 0.02MB + インデックス: 0.00MB
paradis_wp_wfpendingissues: データ: 0.02MB + インデックス: 0.06MB
paradis_wp_wfreversecache: データ: 0.02MB + インデックス: 0.00MB
paradis_wp_wfsnipcache: データ: 0.02MB + インデックス: 0.05MB
paradis_wp_wfstatus: データ: 0.14MB + インデックス: 0.09MB
paradis_wp_wftrafficrates: データ: 0.02MB + インデックス: 0.00MB

### Post Type Counts ###

attachment: 1366
customize_changeset: 18
flamingo_contact: 4
flamingo_inbound: 6
jetpack_migration: 2
jetpack-testimonial: 1
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
mw-wp-form: 1
nav_menu_item: 32
page: 28
post: 4
product: 227
revision: 218
test: 1
voice: 1
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌エラーメッセージは訪問者に表示されないようにする必要があります。

### Active Plugins (16) ###

Akismet Anti-Spam (アンチスパム): 更新者: Automattic – 4.1.1
Classic Editor: 更新者: WordPress コントリビューター – 1.4
Contact Form 7: 更新者: Takayuki Miyoshi – 5.1.1
Display Posts: 更新者: Bill Erickson – 3.0.1
DX Delete Attached Media: 更新者: nofearinc – 1.0
Flamingo: 更新者: Takayuki Miyoshi – 1.9
Google Apps Login: 更新者: Lever Technologies – 3.2
Jetpack by WordPress.com: 更新者: Automattic – 6.9
MW WP Form: 更新者: Takashi Kitajima – 4.0.6
Shibuya CMS: 更新者: Takuma Ando – 0.3.17
Simple Custom Post Order: 更新者: Colorlib – 2.4.1
UpdraftPlus - Backup/Restore: 更新者: UpdraftPlus.Com
DavidAnderson – 1.16.5

WooCommerce For Japan: 更新者: 職人工房 – 1.2.25
WooCommerce: 更新者: Automattic – 3.5.4
Wordfence Security: 更新者: Wordfence – 7.1.20
WP Multibyte Patch: 更新者: 倉石 政典 – 2.8.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: JPY (円)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

ショップベース: #335 - /product/
カート: #9 - /cart/
購入手続き: #10 - /checkout/
マイアカウント: #11 - /my-account/
利用規約: ❌ ページ設定されていません

### Theme ###

Name: Paradis House Official
Version: 1.0
Author URL: https://www.paradishouse.jp/
Child Theme: ❌ – WooCommerce に準拠しているテーマや親テーマを修正するのではなく、子テーマを作ることをおすすめします。子テーマの作り方はこちらをご覧ください。
WooCommerce Support: ✔

### Templates ###

Overrides: paradishouse/woocommerce/loop/price.php
paradishouse/woocommerce/single-product/add-to-cart/simple.php
paradishouse/woocommerce/single-product/product-attributes.php
paradishouse/woocommerce/single-product/title.php

`</details>

**Comment by mikejolley** [comment]
I took a look through the code and it seems when we're working with new attributes AND terms e.g. CSV importer, we do register a temporary taxonomy.

With the REST API however this isn't needed. Creating the taxonomy is a single request. When you make the next request, the taxonomy exists. I don't see any reason to register it right away in the same request. 

FYI this is how the CSV importer deals with it:

```
// Register as taxonomy while importing.
		$taxonomy_name = wc_attribute_taxonomy_name( $attribute_name );
		register_taxonomy(
			$taxonomy_name,
			apply_filters( 'woocommerce_taxonomy_objects_' . $taxonomy_name, array( 'product' ) ),
			apply_filters(
				'woocommerce_taxonomy_args_' . $taxonomy_name,
				array(
					'labels'       => array(
						'name' => $raw_name,
					),
					'hierarchical' => true,
					'show_ui'      => false,
					'query_var'    => true,
					'rewrite'      => false,
				)
			)
		);
```

if you can explain a use case that requires this we can reopen or mark as a feature request. Otherwise it's probably not worth the extra overhead if it's not used.

Thanks
