### ISSUE TITLE
Refund Status changes order to show it was 100% refunded even if it isn't.

### ISSUE THREAD

**Issue by calendarboy** [woocommerce/woocommerce#22685]
If a customer is to be refunded the cost of the product, but not the S&H charge, there are problems. 

First, doing the partial refund does not change the order status. 

Secondly, if I then change the status of the order to "Refunded", when I click Update, it will then show the order as having two refunds. It shows the actual refund for the product and it **also** shows a refund for the S&H with a note _"Order fully refunded"_.

However, neither PayPal or Stripe show the incorrect "second" refund.

![screen-shot-refund](https://user-images.githubusercontent.com/5973789/52449829-847e5b80-2aed-11e9-909d-e1c4c75dbd75.jpg)

Status Report
`
### WordPress Environment ###

Home URL: https://quicksilverproductions.com
Site URL: https://quicksilverproductions.com
WC Version: 3.5.4
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.32-1~dotdeb+8.1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 25 MB
PHP Time Limit: 0
PHP Max Input Vars: 2500
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.41-84.1
Max Upload Size: 25 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.2.6
WC Database Prefix: qp__
MaxMind GeoIP Database: ✔
Total Database Size: 385.15MB
Database Data Size: 267.87MB
Database Index Size: 117.28MB
qp__woocommerce_sessions: Data: 1.72MB + Index: 0.05MB
qp__woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
qp__woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
qp__woocommerce_downloadable_product_permissions: Data: 0.07MB + Index: 0.07MB
qp__woocommerce_order_items: Data: 3.40MB + Index: 1.69MB
qp__woocommerce_order_itemmeta: Data: 37.76MB + Index: 15.09MB
qp__woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
qp__woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
qp__woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
qp__woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
qp__woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
qp__woocommerce_payment_tokens: Data: 0.04MB + Index: 0.02MB
qp__woocommerce_payment_tokenmeta: Data: 0.09MB + Index: 0.08MB
qp__woocommerce_log: Data: 0.00MB + Index: 0.00MB
qp__aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB
qp__cart_notices: Data: 0.00MB + Index: 0.00MB
qp__commentmeta: Data: 2.60MB + Index: 1.83MB
qp__comments: Data: 26.88MB + Index: 10.90MB
qp__enmask_hits: Data: 0.10MB + Index: 0.20MB
qp__enmask_keywords: Data: 0.00MB + Index: 0.00MB
qp__followup_coupons: Data: 0.02MB + Index: 0.03MB
qp__followup_coupon_logs: Data: 0.02MB + Index: 0.03MB
qp__followup_customers: Data: 0.39MB + Index: 0.78MB
qp__followup_customer_carts: Data: 0.16MB + Index: 0.03MB
qp__followup_customer_notes: Data: 0.02MB + Index: 0.03MB
qp__followup_customer_orders: Data: 0.05MB + Index: 0.02MB
qp__followup_email_coupons: Data: 0.02MB + Index: 0.02MB
qp__followup_email_excludes: Data: 0.02MB + Index: 0.05MB
qp__followup_email_logs: Data: 0.11MB + Index: 0.05MB
qp__followup_email_orders: Data: 0.30MB + Index: 0.09MB
qp__followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB
qp__followup_email_tracking: Data: 0.05MB + Index: 0.08MB
qp__followup_followup_history: Data: 0.06MB + Index: 0.05MB
qp__followup_order_categories: Data: 1.52MB + Index: 0.58MB
qp__followup_order_items: Data: 0.47MB + Index: 0.69MB
qp__followup_subscribers: Data: 0.02MB + Index: 0.03MB
qp__followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB
qp__followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
qp__gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
qp__gf_entry: Data: 19.55MB + Index: 4.03MB
qp__gf_entry_meta: Data: 6.52MB + Index: 8.55MB
qp__gf_entry_notes: Data: 0.02MB + Index: 0.03MB
qp__gf_form: Data: 0.02MB + Index: 0.00MB
qp__gf_form_meta: Data: 0.09MB + Index: 0.00MB
qp__gf_form_revisions: Data: 0.02MB + Index: 0.03MB
qp__gf_form_view: Data: 3.52MB + Index: 3.03MB
qp__itsec_distributed_storage: Data: 6.02MB + Index: 0.02MB
qp__itsec_fingerprints: Data: 0.02MB + Index: 0.03MB
qp__itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB
qp__itsec_lockouts: Data: 0.00MB + Index: 0.01MB
qp__itsec_logs: Data: 15.02MB + Index: 0.83MB
qp__itsec_temp: Data: 0.04MB + Index: 0.04MB
qp__links: Data: 0.00MB + Index: 0.00MB
qp__options: Data: 2.16MB + Index: 0.20MB
qp__pdf_stamped_files_tbl: Data: 0.00MB + Index: 0.00MB
qp__postmeta: Data: 85.72MB + Index: 48.00MB
qp__posts: Data: 9.45MB + Index: 2.28MB
qp__rg_form: Data: 0.00MB + Index: 0.00MB
qp__rg_form_meta: Data: 0.04MB + Index: 0.00MB
qp__rg_form_view: Data: 3.06MB + Index: 1.65MB
qp__rg_incomplete_submissions: Data: 0.00MB + Index: 0.00MB
qp__rg_lead: Data: 15.68MB + Index: 1.59MB
qp__rg_lead_detail: Data: 3.60MB + Index: 4.31MB
qp__rg_lead_detail_long: Data: 0.32MB + Index: 0.01MB
qp__rg_lead_meta: Data: 0.50MB + Index: 0.29MB
qp__rg_lead_notes: Data: 0.00MB + Index: 0.00MB
qp__termmeta: Data: 0.00MB + Index: 0.01MB
qp__terms: Data: 0.00MB + Index: 0.01MB
qp__term_relationships: Data: 0.16MB + Index: 0.30MB
qp__term_taxonomy: Data: 0.00MB + Index: 0.01MB
qp__usermeta: Data: 8.62MB + Index: 4.67MB
qp__users: Data: 0.45MB + Index: 0.34MB
qp__wc_download_log: Data: 0.02MB + Index: 0.03MB
qp__wc_webhooks: Data: 0.02MB + Index: 0.02MB
qp__woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB
qp__woocommerce_shipping_table_rates: Data: 0.00MB + Index: 0.00MB
qp__woocommerce_shipping_zone_shipping_methods: Data: 0.00MB + Index: 0.00MB
qp__woo_sr_cart_items: Data: 1.57MB + Index: 1.31MB
qp__woo_sr_orders: Data: 3.36MB + Index: 1.22MB
qp__woo_sr_order_items: Data: 1.88MB + Index: 1.34MB
qp__wpbackitup_job_control: Data: 0.00MB + Index: 0.00MB
qp__wpbackitup_job_items: Data: 4.38MB + Index: 0.43MB
qp__wpbackitup_job_tasks: Data: 0.01MB + Index: 0.00MB

### Post Type Counts ###

amn_smtp: 1
attachment: 447
backup: 1
cleanup: 2
customize_changeset: 2
follow_up_email: 7
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 38
page: 44
post: 3
product: 155
revision: 1174
scheduled-action: 219
shop_order: 28533
shop_order_refund: 485
yith_popup: 1
yith-wccos-ostatus: 2
yith-wcet-etemplate: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (33) ###

Gravity Forms: by rocketgenius – 2.4.5.1
BackUpWordPress: by XIBO Ltd – 3.8
iThemes Security: by iThemes – 7.2.0
Breeze: by Cloudways – 1.0.10
Coming Soon Page & Maintenance Mode by SeedProd: by SeedProd – 5.0.23
WP Cart Mailcheck: by Lee Willis – 1.0.5 – Not tested with the active version of WooCommerce
WP Hide Plugin Updates and Warnings: by Midland Web Company – 1.0
No CAPTCHA reCAPTCHA for WooCommerce: by MailOptin Team – 1.2.6 – Not tested with the active version of WooCommerce
Smart Reporter for e-commerce: by StoreApps – 2.9.19
Social Media Widget: by Noah Kagan – 4.0.6
WooCommerce Address Validation: by SkyVerge – 2.3.4 – 2.4.0 is available
WooCommerce Admin Bar Addition: by David Decker - DECKERWEB – 2.7.0 – Not tested with the active version of WooCommerce
WooCommerce Cart Notices: by SkyVerge – 1.8.6 – 1.9.0 is available
WooCommerce Email Customizer: by cxThemes – 3.22 – Not tested with the active version of WooCommerce
Follow-Up Emails: by WooCommerce – 4.8.6
WooCommerce Stripe Gateway: by WooCommerce – 4.1.14
WooCommerce Gravity Forms Product Add-Ons: by Lucas Stark – 3.3.7
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.7.3

WooCommerce Sales MIS Report: by Infosoft Consultant – 3.8
Advanced Order Export For WooCommerce (Pro): by AlgolPlus – 2.0.1
WooCommerce PDF Watermark: by WooCommerce – 1.1.7
WooCommerce Print Invoice/Packing list: by WooThemes / SkyVerge – 2.7.0 – 3.6.2 is available – Not tested with the active version of WooCommerce
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.12.2
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.13
WooCommerce: by Automattic – 3.5.4
WP BackItUp Community Edition: by WPBackItUp – 1.31.0
WP-DBManager: by Lester 'GaMerZ' Chan – 2.79.2
Email Login: by Beau Lebens – 4.6.4
Wplogin Customizer: by Suresh Kumar – 1.0
WP Mail SMTP: by WPForms – 1.4.1
WP reCaptcha Integration: by Jörn Lund – 1.2.1
YITH WooCommerce Custom Order Status Premium: by YITH – 1.1.10
YITH WooCommerce Order Tracking Premium: by YITHEMES – 1.5.3

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-3 (rated-3-2)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #5 - /shop
Cart: #6 - /cart
Checkout: #7 - /cart/checkout
My account: ❌ Page does not contain the shortcode.
Terms and conditions: #305 - /ordering-information

### Theme ###

Name: Sommerce
Version: 3.3.0
Author URL: http://yithemes.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: sommerce/woocommerce/archive-product.php version 3.3.0 is out of date. The core version is 3.4.0
sommerce/woocommerce/cart/cart-shipping.php version 3.2.0 is out of date. The core version is 3.5.0
sommerce/woocommerce/cart/cart.php version 3.3.0 is out of date. The core version is 3.5.0
sommerce/woocommerce/cart/cross-sells.php
sommerce/woocommerce/content-product.php version 3.0.0 is out of date. The core version is 3.4.0
sommerce/woocommerce/content-product_cat.php
sommerce/woocommerce/content-single-product.php version 3.0.0 is out of date. The core version is 3.4.0
/home/117436.cloudwaysapps.com/zzuhpqfmpu/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/admin-cancelled-order.php
/home/117436.cloudwaysapps.com/zzuhpqfmpu/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/admin-failed-order.php
/home/117436.cloudwaysapps.com/zzuhpqfmpu/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/admin-new-order.php
/home/117436.cloudwaysapps.com/zzuhpqfmpu/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/customer-completed-order.php
/home/117436.cloudwaysapps.com/zzuhpqfmpu/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/customer-invoice.php
/home/117436.cloudwaysapps.com/zzuhpqfmpu/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/customer-new-account.php version 3.5.0 is out of date. The core version is 3.5.2
/home/117436.cloudwaysapps.com/zzuhpqfmpu/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/customer-note.php
/home/117436.cloudwaysapps.com/zzuhpqfmpu/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/customer-on-hold-order.php
/home/117436.cloudwaysapps.com/zzuhpqfmpu/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/customer-processing-order.php version 3.5.0 is out of date. The core version is 3.5.4
/home/117436.cloudwaysapps.com/zzuhpqfmpu/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/customer-refunded-order.php
/home/117436.cloudwaysapps.com/zzuhpqfmpu/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/customer-reset-password.php
/home/117436.cloudwaysapps.com/zzuhpqfmpu/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/email-addresses.php version 3.2.1 is out of date. The core version is 3.5.4
/home/117436.cloudwaysapps.com/zzuhpqfmpu/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/email-customer-details.php
/home/117436.cloudwaysapps.com/zzuhpqfmpu/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/email-downloads.php
/home/117436.cloudwaysapps.com/zzuhpqfmpu/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/email-footer.php
/home/117436.cloudwaysapps.com/zzuhpqfmpu/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/email-header.php
/home/117436.cloudwaysapps.com/zzuhpqfmpu/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/email-order-details.php
/home/117436.cloudwaysapps.com/zzuhpqfmpu/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/email-order-items.php
/home/117436.cloudwaysapps.com/zzuhpqfmpu/public_html/wp-content/plugins/woocommerce-email-control/templates/emails/supreme/email-styles.php
sommerce/woocommerce/global/breadcrumb.php
sommerce/woocommerce/global/sidebar.php
sommerce/woocommerce/global/wrapper-end.php
sommerce/woocommerce/global/wrapper-start.php
sommerce/woocommerce/loop/add-to-cart.php
sommerce/woocommerce/loop/no-products-found.php
sommerce/woocommerce/loop/pagination.php
sommerce/woocommerce/loop/price.php
sommerce/woocommerce/loop/sale-flash.php
sommerce/woocommerce/single-product/add-to-cart/external.php version 2.1.0 is out of date. The core version is 3.4.0
sommerce/woocommerce/single-product/add-to-cart/grouped.php version 3.3.0 is out of date. The core version is 3.4.0
sommerce/woocommerce/single-product/add-to-cart/simple.php version 3.0.0 is out of date. The core version is 3.4.0
sommerce/woocommerce/single-product/add-to-cart/variable.php version 3.0.0 is out of date. The core version is 3.4.1
sommerce/woocommerce/single-product/meta.php
sommerce/woocommerce/single-product/price.php
sommerce/woocommerce/single-product/related.php
sommerce/woocommerce/single-product/sale-flash.php
sommerce/woocommerce/single-product/share.php version 1.6.4 is out of date. The core version is 3.5.0
sommerce/woocommerce/single-product/tabs/description.php
sommerce/woocommerce/single-product/tabs/tabs.php
sommerce/woocommerce/single-product/up-sells.php
sommerce/woocommerce/single-product-reviews.php version 3.2.0 is out of date. The core version is 3.5.0
sommerce/woocommerce/single-product.php
sommerce/woocommerce/taxonomy-product_cat.php
sommerce/woocommerce/taxonomy-product_tag.php

Outdated Templates: ❌
					
						Learn how to update
### Address Validation ###

Active Provider: SmartyStreets
Configured: ✔
Include Plus-four code?: Yes
Debug Mode: Yes
Geocode Addresses: No
Classify Addresses: No
Force Customer to look-up address via Postcode: No
`

**Comment by mikejolley** [comment]
In this case, it's working how it should. Refunded status is for 100% refunded orders. Partially refunded orders keep their original status. Without this you'd lose track of processing vs completed orders, since there is no separation between payment and fulfilment status.

You should do the partial refund, but leave the status alone. The totals etc will be updated to reflect the refund, and the order notes will also specify this happened.

A separate payment status is something to consider for the future, but there are currently other priorities.

Thanks!

**Comment by calendarboy** [comment]
O.K.

Since it did not used to work this way, I considered it to just be incorrect. 

We often have partial refunds. And it confusing to have an order still showing that it has been COMPLETED when the product has been returned. Thank goodness, I have YITH Custom Status.

**Comment by calendarboy** [comment]
Mike, 

I just went to our Orders on WooCommerce. I clicked on REFUNDED status. 

I was quite surprised to see that ALL of them had been changed to show full refunds whether they were or not. It used to be that a partial refund would show REFUND status. And it would not show a second refund of the balance. 

Jim

**Comment by jtas01** [comment]
Having the same issue. How are the emails affected by this? A new status of partial-refunded would be useful.
