### ISSUE TITLE
How do I get a product count following some filters?

### ISSUE THREAD

**Issue by gigioSouza** [woocommerce/woocommerce#22689]
I'm using the API with some ajax calls and I need to get the product count for a search. But I can't find it in the documentation. I'd like to know the count of products which match with the category and search term.

**Comment by claudiulodro** [comment]
If you're using the API [the total number of results is available in the X-WP-Total response header](https://woocommerce.github.io/woocommerce-rest-api-docs/#pagination). It's a [standard header in the WP API.](https://developer.wordpress.org/rest-api/using-the-rest-api/pagination/)

**Comment by gigioSouza** [comment]
@claudiulodro Thank you!
