### ISSUE TITLE
Canadian address formats.

### ISSUE THREAD

**Issue by calendarboy** [woocommerce/woocommerce#22686]
This is minor, but it has been wrong as long as I've used WooCommerce.

Canadian addresses should have two spaces between the Province and the Postal Code.
For example:

Banyen Books
3608 4th Avenue W
Vancouver, BC  V6R 1P1  (can you see the two spaces between BC and V6R?)
Canada

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22692

**Comment by siliconforks** [comment]
I guess this change makes sense, but is this issue really unique to Canadian addresses?  For example, the United States Postal Service says ["Two spaces are preferred between the state abbreviation and ZIP+4 Code"](https://pe.usps.com/text/pub28/28c2_009.htm).

**Comment by calendarboy** [comment]
The guideline for Canadian addresses does not say “preferred”. It just says it is to have two spaces after the Province before the Postal Code. 

Mike, I know you don’t like making changes. I know you hate being told anything should be different. 

Additionally, I am retiring. My web site will continue, but I will not be producing any more calendars. Forty-six years was long-enough. 

I just thought I would throw out these three things that are wrong before I’m done. 

Jim

**Comment by mikejolley** [comment]
> I know you hate being told anything should be different.

@calendarboy ... you realise I made the change, right?

It's in https://github.com/woocommerce/woocommerce/pull/22692
