### ISSUE TITLE
Shipping_Phone not included in email template

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce#22698]
**Describe the bug**
The `shipping_phone` field not included in the email template, while other fields are.

![Screenshot](http://cld.wthms.co/xAN73A+)
Screenshot link: http://cld.wthms.co/xAN73A

**Comment by C-space-B** [comment]
I use the Checkout Fields Plugin. When I disabled "order comments," it gets a line through it and goes gray but stays visible on the Additional Fields tab in the administrator. It is removed from the Checkout page. 
<img width="1501" alt="screen shot 2019-02-09 at 11 40 41 am" src="https://user-images.githubusercontent.com/47484205/52525519-d0511200-2c5f-11e9-8284-565a13fc523f.png">

When I disabled "shipping_phone" it disappeared completely from the Shipping Fields tab (not greyed out with a line through it):
<img width="1490" alt="screen shot 2019-02-09 at 11 40 14 am" src="https://user-images.githubusercontent.com/47484205/52525522-d6df8980-2c5f-11e9-98ae-6a70c3391820.png">
AND it now shows again on the checkout page:
<img width="389" alt="screen shot 2019-02-09 at 11 41 39 am" src="https://user-images.githubusercontent.com/47484205/52525529-e9f25980-2c5f-11e9-9a97-f0c1fa16874d.png">

There is clearly something wrong with the implementation of this field.

**Comment by kloon** [comment]
@johndcoy There is no shipping phone field by default in WooCommerce core, was this perhaps added via an extension or custom code? If so the extension or custom code needs to be sure to hook in on the right hooks to display any custom fields it adds.

@C-space-B please contact support for assistance with extensions, this repository is only for issues relating to WooCommerce core and not functionality that was added by extensions.

**Comment by C-space-B** [comment]
For the record, (in case anyone finds this ticket), it is the WooCommerce Services plugin that automatically adds the "shipping_phone" field which the Checkout Fields Plugin then sees as "default" and fails to give the display options.
