### ISSUE TITLE
Custom Section in Payments Settings Page

### ISSUE THREAD

**Issue by sebastianpisula** [woocommerce/woocommerce#22696]
I tried to add a custom section in the Payments Settings Page but not works:

	add_filter( 'woocommerce_get_sections_checkout', function ( $types ) {
		$types['custom'] = 'Custom Page';

		return $types;
	} );

	add_filter( 'woocommerce_get_settings_checkout', function ( $settings, $current_section ) {
		if ( $current_section === 'custom' ) {
			$settings = [];

			$settings[] = [
				'name'  => 'API',
				'id'    => 'api_key',
				'type'  => 'text',
				'value' => get_option( 'api_key' ),
			];
		}

		return $settings;
	}, 10, 2 );

<img width="735" alt="image" src="https://user-images.githubusercontent.com/15688144/52510378-052b7d80-2bfc-11e9-901e-4faf09244970.png">

**Comment by kloon** [comment]
See #22704
