### ISSUE TITLE
Product variation attributes of type "any" no longer allowed?

### ISSUE THREAD

**Issue by mjdewitt** [woocommerce/woocommerce#22702]
**Describe the bug**
I'm not sure if this is a bug, but it seems that the 2.6 feature of being able to define a variable product "any" attribute (no values pre-set on the product) are no longer allowed in 3.0?  
**To Reproduce**
1. Go and 'add an attribute with no values to a variable product'
2. Click on 'save'
3. attribute is removed on save - no error.
See
class-wc-meta-box-product-data.php  line 264 
    if ( empty( $options ) ) {
     continue;
    }

commenting out these lines corrects the behavior.

With a product attribute "any" saved, a related issue arises which  is the inability to add-to-cart a product variation with attribute data for an "any" attribute, It fails with the notice of invalid data for the attribute.
 
see class-wc-form-handler.php line 893 
} elseif ( '' === $valid_value && in_array( $value, $attribute->get_slugs() ) ) {

changing it to

} elseif ( '' === $valid_value || in_array( $value, $attribute->get_slugs() ) ) {  

corrects the behavior.

**Comment by kloon** [comment]
Still there for me in the latest version
![](http://cld.wthms.co/nAkyOR+)

And selection and checkout works fine on the frontend
![](http://cld.wthms.co/P8ChHI+)

Not sure to which version you updated, but as per my screenshots you can definitely define a single any option and have it work in the lastest release.

Closing but will reopen if there are ways to replicate this on the latest version.

**Comment by mjdewitt** [comment]
Hi,
Yes, I can see your variation working. I am curious, did you setup the product and define the attributes to test this, or is this product something that was defined in the past? I ask because I noticed this behavior with newly defined attributes on products. Thank you for looking into this.

**Comment by mjdewitt** [comment]
I just installed latest WooCommerce (add new plugin) on a new multisite (5.0.3), added a new variable product
![image](https://user-images.githubusercontent.com/36002368/52612784-410f4e80-2e59-11e9-8ea8-befd7f4ce584.png)

Tried to add a new "any" attribute and clicked "save
![image](https://user-images.githubusercontent.com/36002368/52612882-964b6000-2e59-11e9-91d7-3ce8d946be8e.png)

attribute is wiped out on save.

Added attribute again, but this time with a value.
![image](https://user-images.githubusercontent.com/36002368/52613048-6a7caa00-2e5a-11e9-9775-ba41abfe88a0.png)

Click save and attribute is saved.
![image](https://user-images.githubusercontent.com/36002368/52613081-926c0d80-2e5a-11e9-9aeb-be77dfb24cdc.png)

This is on a different host with only WooCommerce activated.

**Comment by mjdewitt** [comment]
Oh - I see what's going on attribute value is now required in order to be able to save the attribute.

this wasn't the case in the past:
![image](https://user-images.githubusercontent.com/36002368/52613889-bda42c00-2e5d-11e9-92de-d8cd0c30598c.png)

Even though it does work as an "any" attribute in the end, you have to put something into the value in order to save it. To me, the way it used to be is less confusing. I believe the real problem will be for anyone who upgrades and edits their saved attributes with blank values The Ajax update on save will trigger their removal.

**Comment by mjdewitt** [comment]
Hi,

I updated the case to reflect more accurately what is going on: "Product
attributes with no value cannot be saved."

I was confused over the definition of an "any" attribute. I assumed it had
two parts - no value assigned, declared as an any.

The issue for me was with "legacy" 2.6 attributes converted to 3.0 as they
would never validate. Editing the attributes and they would disappear on
save.

#22702 <https://github.com/woocommerce/woocommerce/issues/22702>.

Mike
