### ISSUE TITLE
checkout tab not found

### ISSUE THREAD

**Issue by alfariesh** [woocommerce/woocommerce#22700]
**Describe the bug**
I want to add a payment gateway, but I did not find the ceckout tab in my woocommerce settings.
after I checked the status there was a problem at SoapClient and the woocommerce version of the theme that I haven't updated.
after my problem has been resolved, and I check in the status there is no problem I check again in the woocommerce settings, but still I don't find the checkout tab!
I don't think this is a cache problem because I have cleaned it

**Comment by kloon** [comment]
Not sure where you are working from as an example but the Checkout tab was renamed quite some time ago, it is now called Payments. WooCommerce -> Settings -> Payments.
