### ISSUE TITLE
Stop _order_count & _money_spent deletion after completed or refunded new status

### ISSUE THREAD

**Issue by GeekPress** [woocommerce/woocommerce#22707]
Hi there,

I noticed a strange bug: each time an order is completed or refunded, the _order_count user meta is deleted. Same thing for _money_spent user meta.

It's pretty annoying if we are using these data to send emails depending to the number of orders or money spent by customers.

**To Reproduce**
Complete an order or refund an order.

**Expected behavior**
Instead of reseting _order_count & _money_spent, please increment or decrement the values.

**Comment by mikejolley** [comment]
This meta data acts as a cache - it's deleted when invalidated.

Instead of using meta directly, go via the CRUD. 

```
$customer = new WC_Customer( 1 );
$customer->get_total_spent();
```

This reads from cache (meta) or regenerates the value if missing.
