### ISSUE TITLE
REST API Wrong Link Header when listing orders per status

### ISSUE THREAD

**Issue by pierrebuet** [woocommerce/woocommerce#22701]
When consuming the endpoint for orders in the REST API and setting an order status, the Header Links for pagination are wrong, omitting the the status parameter. This makes it impossible to consume the header to get the next page of orders by status.
Consuming /orders?status=processing returns in the header links as rel=next something like  /orders?page=2 instead of /orders?status=processing&page=2

To reproduce, just look in the header response of a call to /orders?status="processing"

The culprid is https://github.com/woocommerce/woocommerce/blob/0d901a2ecadc7ea52aa4a875d511d5097d50cbed/includes/api/class-wc-rest-orders-controller.php#L215
where the status parameter got unset from the request which then can't be used to produce a $base including this parameter in the controller.
https://github.com/woocommerce/woocommerce/blob/0d901a2ecadc7ea52aa4a875d511d5097d50cbed/includes/abstracts/abstract-wc-rest-crud-controller.php#L387

To me, it looks like the unsetting was done to not return an array to string conversion error when attributes got replaced in the base url (but I have no idea why this replacement) here:
https://github.com/woocommerce/woocommerce/blob/0d901a2ecadc7ea52aa4a875d511d5097d50cbed/includes/abstracts/abstract-wc-rest-crud-controller.php#L374

Instead of unsetting the parameter in the request and losing the information in the header, the parameter status should be kept in the request and the test for an array or not should be done in the abstract crud controller while replacing part of the url. Not unsetting the status parameter from the request leads to an header link with URLencoded links of type /orders?status[0]=processing&page=2. Listing orders without a status parameter leads to a rel=next URL of type /orders?status[0]=any&page=2 which both are absolutely fine.

**Comment by peterfabian** [comment]
Please see #22741 .
