### ISSUE TITLE
Order page displaying all orders from website, rather than customer related

### ISSUE THREAD

**Issue by Akrasnovskis** [woocommerce/woocommerce#22709]
Hello Team,

I have a serious issue with the order page. Order page displaying all orders from the entire website, rather than customer related ones, if you click to view order then it showing an error page that is not a valid order. This is an important issue and must be fixed asap, it similar to the data breach, that everyone can view all orders, I have disable the page for now

**Comment by mikejolley** [comment]
Hi,

This will be a conflict with another plugin (or theme) on your site. Plugins can change the query used to retrieve the orders, and if they remove the restriction on user ID, this will happen.

Rule out conflicts before posting here and please in future carry out all steps on the [new issue form](https://github.com/woocommerce/woocommerce/issues/new/choose).

Closing as this is likely a plugin conflict and no steps to replicate on a clean install were given (works for me).
