### ISSUE TITLE
If local pickup adds taxes for a state, changing the state to one without taxes or local pickup won't remove them.

### ISSUE THREAD

**Issue by billrobbins** [woocommerce/woocommerce#22708]
**Describe the bug**
Local pickup is enabled for a zone that covers a state.  When an address is entered and that state is selected, taxes are added and local pickup is selected.  If the state is changed after that, a different shipping method is selected, but taxes aren't removed.  

Say there is a store in Texas.  They offer local pickup and have in-state taxes.  Someone places an order from Tennessee but accidentally click on Texas in the state drop-down.  Taxes will be added to the order.  When they correct the state to Tennessee, taxes will still be on the order even though local shipping isn't an option to that state.  A second change to the address, like ZIP code or street address is required to correct the taxes.

**To Reproduce**
1. Create a store with a US location.
2. Set taxes to be for the home state.
3. Create a shipping zone for the home state that uses Local Pickup.
4. Create another shipping zone with Flat Rate for everywhere else.
5. Add an item to the cart and proceeded to checkout.
6. Enter an address in a different state from the store, but select the store's state for the state of the order.  Taxes will be added to the order.
7. Change the state to the correct one.  Local pickup will no longer be available, but taxes will still be present.
8. Make one more change to the address to correct the taxes.  Changing the state for example.

**Screenshots**
![Taxes present after state changed and local pickup removed](https://cdn-std.dprcdn.net/files/acc_705319/iBIVWi)
(Link to screenshot:  https://cld.wthms.co/iBIVWi)

![Tax Rates](https://cdn-std.dprcdn.net/files/acc_705319/HcPklK)
(Link to screenshot:  https://cld.wthms.co/HcPklK)

![Shipping Zones](https://cdn-std.dprcdn.net/files/acc_705319/mBYV6l)
(Link to screenshot:  https://cld.wthms.co/mBYV6l)

**Expected behavior**
I expect that changing the address to a zone that doesn't offer local pickup and isn't taxed would remove the tax.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

Home URL: https://billthea11n.mystagingwebsite.com
Site URL: https://billthea11n.mystagingwebsite.com
WC Version: 3.5.4
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.0.33 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.62.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.17-MariaDB
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.3
WC Database Prefix: wp_
Total Database Size: 17.81MB
Database Data Size: 10.63MB
Database Index Size: 7.18MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.13MB + Index: 0.13MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
vp_backup_wp_commentmeta: Data: 0.02MB + Index: 0.03MB
vp_backup_wp_comments: Data: 0.02MB + Index: 0.08MB
vp_backup_wp_links: Data: 0.02MB + Index: 0.02MB
vp_backup_wp_options: Data: 1.08MB + Index: 0.05MB
vp_backup_wp_postmeta: Data: 0.14MB + Index: 0.11MB
vp_backup_wp_posts: Data: 0.08MB + Index: 0.06MB
vp_backup_wp_termmeta: Data: 0.02MB + Index: 0.03MB
vp_backup_wp_terms: Data: 0.02MB + Index: 0.03MB
vp_backup_wp_term_relationships: Data: 0.02MB + Index: 0.02MB
vp_backup_wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
vp_backup_wp_usermeta: Data: 0.02MB + Index: 0.03MB
vp_backup_wp_users: Data: 0.02MB + Index: 0.05MB
vp_backup_wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
vp_backup_wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
vp_backup_wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
vp_backup_wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
vp_backup_wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
vp_backup_wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
vp_backup_wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
vp_backup_wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
vp_backup_wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
vp_backup_wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
vp_backup_wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
vp_backup_wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
vp_backup_wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
vp_backup_wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
vp_backup_wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
vp_backup_wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.09MB + Index: 0.09MB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB
wp_followup_email_orders: Data: 0.02MB + Index: 0.09MB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB
wp_followup_followup_history: Data: 0.08MB + Index: 0.05MB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB
wp_gf_form: Data: 0.02MB + Index: 0.00MB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.36MB + Index: 0.08MB
wp_postmeta: Data: 1.50MB + Index: 2.95MB
wp_posts: Data: 0.28MB + Index: 0.14MB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.05MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB
wp_wc_order_stats: Data: 0.02MB + Index: 0.02MB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.05MB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_admin_notes: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_admin_note_actions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_wpml_mails: Data: 2.52MB + Index: 0.00MB
wp_wps_hit: Data: 0.02MB + Index: 0.14MB
wp_wps_index: Data: 0.33MB + Index: 0.58MB
wp_wps_key: Data: 0.05MB + Index: 0.02MB
wp_wps_object_type: Data: 0.02MB + Index: 0.08MB
wp_wps_query: Data: 0.02MB + Index: 0.02MB
wp_wps_uri: Data: 0.02MB + Index: 0.02MB
wp_wps_user_agent: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 26
bookable_resource: 4
carts: 4
customize_changeset: 8
follow_up_email: 6
jetpack_migration: 2
jp_img_sitemap: 3
jp_sitemap: 3
jp_sitemap_master: 3
nav_menu_item: 7
page: 11
post: 1
product: 80
product_variation: 10
revision: 16
scheduled-action: 82
shop_coupon: 303
shop_order: 62
shop_order_refund: 1
shop_subscription: 10
slide: 2
wc_booking: 7
wc_membership_plan: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.5.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page not set
Cart: #125 - /cart/
Checkout: #127 - /checkout/
My account: #129 - /account/
Terms and conditions: #419 - /terms-and-conditions/

### Theme ###

Name: Storefront
Version: 2.4.2 – 2.4.3 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: storefront/woocommerce/emails/admin-new-order.php

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22826
