### ISSUE TITLE
Default to publish variations while importing

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce#22703]
**Describe the bug**
RE: 1790658-zen

While importing variable products, if the value of the column **Published** is set to something other than `1` for a variation row, the variation is created but not shown on the product, not even in the admin.

**To Reproduce**
1. Export a working variable product
2. Change the value of Published to -1 for all variations
3. Delete permanently the product
4. Import the edited CSV
5. See error.

**Expected behavior**
Variations should be always imported as Published regardless of what the user set. Draft or Private variations are useless as they cannot be edited. Better to have a wrong but visible variation than a ghost one that cannot be deleted.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by mikejolley** [comment]
Variations can be hidden (private status).

**Comment by SiR-DanieL** [comment]
@mikejolley enabled or not? What about draft? If I set them to draft they disappear.

**Comment by rrennick** [comment]
> If I set them to draft they disappear.

I tested importing draft variations with the latest version of WC in the last 2 weeks & they imported correctly. They were not visible on the front end but I could edit them in the product edit screen.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22736
