### ISSUE TITLE
Canada Post Not loading Shipping lables

### ISSUE THREAD

**Issue by danielle321** [woocommerce/woocommerce#22710]
The canada post Woo Commerce is not loading the shipping labels, the preview or downloads. Once downloaded the file gives an error. Please assist ASAP

**Comment by danielle321** [comment]
<img width="1391" alt="screenshot 2019-02-11 13 16 36" src="https://user-images.githubusercontent.com/47537001/52584448-19d86300-2e00-11e9-806e-ddb25ab5c2a9.png">

**Comment by danielle321** [comment]
<img width="1158" alt="screenshot 2019-02-11 13 23 25" src="https://user-images.githubusercontent.com/47537001/52584545-49876b00-2e00-11e9-9d9a-bd23ea44ffca.png">

**Comment by rrennick** [comment]
@danielle321 Please contact https://woocommerce.com/contact-us/ for support of the CP extension.
