### ISSUE TITLE
Order data retention - trash completed orders

### ISSUE THREAD

**Issue by fauxpark** [woocommerce/woocommerce#22713]
**Is your feature request related to a problem? Please describe.**
We use custom fields attached to our orders containing extra PII such as DOB and at least one form of ID. The "Retain completed orders" option does a great job anonymising the standard order details, but it doesn't touch these custom fields.

**Describe the solution you'd like**
The option to trash completed orders (like pending/failed/cancelled do) instead of simply anonymising them would be perfect. Failing that, perhaps a checkbox to allow custom fields to also be anonymised.

**Comment by mikejolley** [comment]
We don't feel orders should be trashed beause it breaks reporting. 

You can hook into our code to remove your custom fields. The `woocommerce_privacy_remove_order_personal_data_meta` filter is what you're after.

https://github.com/woocommerce/woocommerce/blob/d0491072e8a7d0a4535db0ec2bae4a6d43ff64fd/includes/class-wc-privacy-erasers.php#L288

Pass your meta key and data type, and when anonymsation runs it will clear your custom meta too.

Thanks

**Comment by fauxpark** [comment]
By the same token then, manually trashing orders would *also* break reporting. I'm not sure how it is any different. In any case we don't make use of this feature.

Thank you for the filter suggestion, though, I'll look into that.

**Comment by mikejolley** [comment]
It sure would. But that's at least expected as it's a manual action you'd take as admin. There is no good reason to trash a valid order.
