### ISSUE TITLE
Paypal Pending Status

### ISSUE THREAD

**Issue by Gowsalayadevi** [woocommerce/woocommerce#22714]
**Describe the bug**
I upgrade the woo-commerce version from 3.1.1 to 3.5.4 since then the paypal payment is going to pending status not receiving the ipn. I checked all the paypal setting and tried other ways too. nothing is working
**To Reproduce**
1. add the product to the cart
2. make the paypal payment
3. you will be redirected to the order received page
4. But, the status will be pending in the admin panel

**Expected behavior**
actually, the order should be in processing state

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
**WordPress Environment**

### WordPress Environment ###

Home URL: https://ceilingfanswarehouse.com.au/dev
Site URL: https://ceilingfanswarehouse.com.au/dev
WC Version: 3.5.4
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 900 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.13
PHP Post Max Size: 20 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2q

SUHOSIN Installed: –
MySQL Version: 5.7.23-percona-sure1-log
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.4
WC Database Prefix: wp_
Total Database Size: 255.72MB
Database Data Size: 159.29MB
Database Index Size: 96.43MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 4.52MB + Index: 1.52MB
wp_woocommerce_order_itemmeta: Data: 19.55MB + Index: 15.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.17MB + Index: 0.17MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 1.52MB + Index: 1.89MB
wp_comments: Data: 11.52MB + Index: 9.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 15.52MB + Index: 4.52MB
wp_postmeta: Data: 71.59MB + Index: 46.13MB
wp_posts: Data: 20.55MB + Index: 4.03MB
wp_redirects: Data: 0.00MB + Index: 0.00MB
wp_relevanssi: Data: 4.41MB + Index: 5.69MB
wp_relevanssi_log: Data: 0.00MB + Index: 0.00MB
wp_relevanssi_stopwords: Data: 0.01MB + Index: 0.01MB
wp_termmeta: Data: 0.10MB + Index: 0.09MB
wp_terms: Data: 0.11MB + Index: 0.13MB
wp_term_relationships: Data: 3.52MB + Index: 2.52MB
wp_term_taxonomy: Data: 0.20MB + Index: 0.13MB
wp_usermeta: Data: 5.52MB + Index: 5.03MB
wp_users: Data: 0.27MB + Index: 0.22MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_shipping_methods: Data: 0.02MB + Index: 0.00MB
wp_wpmm_subscribers: Data: 0.00MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.01MB
wp_yoast_seo_meta: Data: 0.01MB + Index: 0.02MB

### Post Type Counts ###

attachment: 5004
custom_css: 1
customize_changeset: 47
nav_menu_item: 74
page: 45
post: 46
product: 1233
product_variation: 993
revision: 2258
shop_coupon: 412
shop_order: 12678
shop_order_refund: 56
sidebar: 4
slide: 2
wccc: 5
wooframework: 259
wpcf7_contact_form: 11
ywtm_tab: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.5.4

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #12 - /my-account/
Terms and conditions: #750 - /terms-and-conditions/

### Theme ###

Name: Electro Child
Version: 2.2.6
Author URL: https://madrasthemes.com/
Child Theme: ✔
Parent Theme Name: Electro
Parent Theme Version: 2.2.6
Parent Theme Author URL: https://madrasthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: electro/woocommerce/archive-product.php
electro-child/woocommerce/emails/admin-cancelled-order.php
electro-child/woocommerce/emails/admin-new-order.php
electro-child/woocommerce/emails/customer-completed-order.php
electro-child/woocommerce/emails/customer-invoice.php
electro-child/woocommerce/emails/customer-new-account.php
electro-child/woocommerce/emails/customer-note.php
electro-child/woocommerce/emails/customer-processing-order.php
electro-child/woocommerce/emails/customer-refunded-order.php
electro/woocommerce/global/quantity-input.php

**Comment by kloon** [comment]
IPS requests work fine in my test using the latest version of WooCommerce. Please read through the debugging IPN issues document and be sure to check your PayPal IPN log to see where it is trying to deliver your IPN and make sure it is correct https://docs.woocommerce.com/document/paypal-standard/#section-21

Closing as I am not able to replicate will gladly reopen if there are steps to replicate this with just WooCommerce and a default theme.
