### ISSUE TITLE
Read more for the products description 

### ISSUE THREAD

**Issue by JoshuaLegacy** [woocommerce/woocommerce#22716]
The "Read More" should be included in the product pages  with read more after the product title. or with a little description to the product bearing the read more before add to cart. 
Most customers  did not know that they can read more about the product before adding to cart

![products](https://user-images.githubusercontent.com/42834190/52631492-35ef0980-2ebf-11e9-92d2-7ffb1cdf63fc.PNG)

**Comment by GlennMartin1** [comment]
I'd suggest that you:
(1) shorten the title, and
(2) remove the "Add to Cart" button

See products on this page: https://www.hometowntrailers.com/dump-trailers/ Short title. No "Add to Cart." And there is no question to the user that these are links.

**Comment by mikejolley** [comment]
These are customisations you can make yourself since the need for this would vary from store to store - https://github.com/woocommerce/woocommerce/wiki/Template-File-Guidelines-for-Devs-and-Theme-Authors

We don't support customisation work here so I'm closing this issue.

Thanks
