### ISSUE TITLE
wc_add_notice at order-received endpoint

### ISSUE THREAD

**Issue by seldimi** [woocommerce/woocommerce#22728]
**Describe the bug**
I am sorry I am double posting so soon, but the issue #22726 is closed to soon without letting me explain. As suggested by one of the members, on custom payment gateway, I have used wc_add_notice on action woocommerce_api_wc_xxx_gateway when there is a successful payment.
When a payment failed, it works as should, as the user is redirected back to cart.

Still, the notice is not displayed on order-received but if I navigate in any other pages where you call woocommerce_output_all_notices function.

There is a workaround to change woocommerce_thankyou_order_received_text, but it's a filter can't be used within response function. 
And I'm pretty sure that this one was working even since WC 2.x/3.x

**To Reproduce**
1. Pay with a gateway that adds a notice like above
2. Check order-recieved page
3. Navigate to any other page (product/cart)

**Expected behavior**
The wc_add_notice via the gateway should have been displayed at order-received.

**Isolating the problem (mark completed items with an [x]):**
- [X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by pmgarman** [comment]
@seldimi GitHub issues are not a support channel for your custom code, other gateways are working fine without any issues so it seems your custom code is the only one with the issue. Perhaps look at how other payment gateways and see how they work and model after them?

**Comment by mikejolley** [comment]
Do not open duplicates please.

https://github.com/woocommerce/woocommerce/issues/22726
