### ISSUE TITLE
WC stops propagation of events in checkout fields, interfering with other functionalities

### ISSUE THREAD

**Issue by eddr** [woocommerce/woocommerce#22720]
1. latest release WC plugin
2. Checkout page
3. using intl-tel-input js code for the phone# field
=> the intl-tel-input click code doesn't triggered after the dropdown list is showed

This is the WC code that prevents it:
"
$( '.woocommerce-input-wrapper' ).on( 'click', function( event ) {
	event.stopPropagation();
} );
"
located in "assets\js\frontend\woocommerce.js"

what can be done?

**Comment by kloon** [comment]
That stops propagation when you click on the wrapper. Perhaps give an example of what you want to do? If you want to run custom js then trigger the input and not the wrapper?

**Comment by mikejolley** [comment]
Added in https://github.com/woocommerce/woocommerce/commit/3bf567279b6bc6058505067d2d8eeece999e77af

When there is a field description, it opens up on click. Without this, the click event runs on the input, then propagates up the DOM causing it to fire another click event on the wrapper and so on which hides the description.

Solution; target your event on the :input not the wrapper.

Thanks

**Comment by eddr** [comment]
@kloon yes - as I wrote, I'm using the popular "intl-tel-input" project. I have no easy and future compatible option to handle its events
https://github.com/jackocnr/intl-tel-input

The click event is on the document itself

**Comment by pramodjodhani** [comment]
I was able to fix it with this code:


```
Ivar iti_open = false;
jQuery('.iti__flag-container').click(function() {
    iti_open = !iti_open;
    if ( !iti_open ) {
        intlTelInputGlobals.instances[ 0 ]._closeDropdown();
    }
});
```
