### ISSUE TITLE
Product shortcode not working after update 

### ISSUE THREAD

**Issue by CamelliaGh** [woocommerce/woocommerce#22727]
I've been using this line of code:
[products columns="5" orderby="date" category="539" limit="5" attribute="zone" terms="5"]
but after updating woocommerce It is not working anymore. If I remove attribute and terms, it is ok but filtering by attribute is not working.

**Comment by kloon** [comment]
I have tested it and it seems to work fine for me.

![](https://cld.wthms.co/fDHv5v+)
![](https://cld.wthms.co/Ayk5pZ+)
![](https://cld.wthms.co/3Xknua+)
![](https://cld.wthms.co/dGlvAc+)

Make sure you actually have products with the attribute and term you specified.

**Comment by CamelliaGh** [comment]
I found the problem. The problem appears when slug of attribute value(term) is a number!
[products columns="5" orderby="date" category="539" limit="5" attribute="zone" terms="5"]
If I edit zone value to five instead of 5, it works!
