### ISSUE TITLE
Notices from payment gateways to order received misplaced

### ISSUE THREAD

**Issue by seldimi** [woocommerce/woocommerce#22726]
**Describe the bug**
Since WooCoomerce 3.5.3, when a client was paying via a payment gateway and returned back to order-received endpoint, if the payment gateway added a notice, it was displayed at the top of order-received page. 
From 3.5.3 and later, there is no notices on order-received page, but if you navigate to any other woocommerce page (cart, another product page etc) the notice is displayed there!

The snippet of the custom gateway that adds the notice is something similar to:
`
$message = __('Thank you for choosing us for your online shopping.<br />Your transaction was successful, payment was received.<br />Your order is currently being processed.', 'textdomain');
$message_type = 'success';
$nbg_message = array(
      'message' => $message,
      'message_type' => $message_type
);
update_post_meta($orderid, '_nbg_message', $nbg_message);
`

**To Reproduce**
1. Pay with a gateway that adds a notice like above
2. Check order-recieved page
3. Navigate to any other page (product/cart)

**Screenshots**
Placing an order with a credit card gateway:
https://imgur.com/4DPIQ5A

After checkout:
https://imgur.com/a/Y2TdSfV

Navigating away (eg shop page, product page)
https://imgur.com/a/GB5uvG6

**Expected behavior**
The notice added via the gateway should have been displayed at order-received.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by kloon** [comment]
The error is not with WooCommerce but how the gateway adds the notice. You seem to do post_meta calls to store a custom meta.

If you want to display a notice you can use the WooCommerce notice API. wc_add_notice will enqueue a notice and display on the first-page load that happens next after you enqueued it.

**Comment by seldimi** [comment]
As I have built the gateway, I had replaced the above snippet like
`$message = __('Thank you for choosing us for your online shopping.<br />Your transaction was successful, payment was received.<br />Your order is currently being processed.', 'textdomain'); $message_type = 'success'; wc_add_notice($message,$message_type); `

Still the same thing.. It doesn't load on order-received but on any other page (such as product page, archive etc)

**Comment by mikejolley** [comment]
It really depends on where (at what point) the notice was added, and if there is still a session.

There are other hooks on the order received page where you can insert text + html directly without relying on the order notice functions. Surely those are more appropriate here?

**Comment by seldimi** [comment]
The notice is added just before a successful payment is processed at the step where gateway reduces stock and changes status to order. After that, it’s redirected to order received page.
It really was there for many versions of WC, I am trying to find on which hook it was in case I find the PR it was removed.

**Comment by mikejolley** [comment]
Can you share the code? Thinking notices may be output before you add the new one.

**Comment by seldimi** [comment]
Assuming this is a class of WC_NBG_Gateway extends WC_Payment_Gateway and this action:
add_action('woocommerce_api_wc_nbg_gateway', array($this, 'check_nbg_response'));

```
        function check_nbg_response()
        {
            global $woocommerce;
            global $wpdb;
            if (isset($_GET['nbg']) && ($_GET['nbg'] === 'success')) {
                /* Some validation code */
                $order = new WC_Order($orderid);

                if ($response->status == 1) {
                    if (strcmp($response->reason, 'ACCEPTED') == 0) {
                            if (version_compare(WOOCOMMERCE_VERSION, "2.6") <= 0) {
                                $order->reduce_order_stock();
                            }else {
                                wc_reduce_stock_levels($orderid);
                            }
                            WC()->cart->empty_cart();
                            $message = __('Thank you for choosing us for your online shopping.<br />Your transaction was successful, payment was received.<br />Your order is currently being processed.', 'textdomain');
                            $message_type = 'success';
                            wc_add_notice($message,$message_type);
                            $redirect_url = $this->get_return_url($order);
                            wp_redirect($checkout_url);
                            exit;
                   }else {
                        $message = __('Thank you for choosing us for your online shopping. <br />However, the transaction wasn\'t successful, payment wasn\'t received.', 'textdomain');
                        $message_type = 'error';
                        $nbg_message = array(
                            'message' => $message,
                            'message_type' => $message_type
                        );
                        wc_add_notice($message,$message_type);

                        //Update the order status
                        $order->update_status('failed', '');
                        $checkout_url = $order->get_cancel_order_url();
                        wp_redirect($checkout_url);
                        exit;
                   }
                }
            }
        }

```

**Comment by mikejolley** [comment]
Use wc_get_order() not the class constructor directly

As for the issue, the session will be removed so that data won't pass through to the page after the redirect. So you should probably use the thanks page hooks which were designed for this. You should be able to insert HTML to format it like a notice.

**Comment by seldimi** [comment]
Ok, that's enough info, thank. you :)
