### ISSUE TITLE
New variations not showing. JS errors in add-to-cart-variation.min.js

### ISSUE THREAD

**Issue by danescobar** [woocommerce/woocommerce#22724]
**Describe the bug**
I'm using the latest version of Woocommerce. When I create new variations in an existing product and add images to each of them it only appears a random couple of variations. Firefox console reports the following:
```
TypeError: wp.template is not a function[Learn More] add-to-cart-variation.min.js:1:12587 
m https://findgoodhealth.org/wp-content/plugins/woocommerce/assets/js/frontend/add-to-cart-variation.min.js:1
onFoundVariation https://find...th.org/wp-content/plugins/woocommerce/assets/js/frontend/add-to-cart-variation.min.js:1
dispatch 8 jQuery
onFindVariation https://find...th.org/wp-content/plugins/woocommerce/assets/js/frontend/add-to-cart-variation.min.js:1
dispatch 8 jQuery
onChange https://find...th.org/wp-content/plugins/woocommerce/assets/js/frontend/add-to-cart-variation.min.js:1
dispatch 2 jQuery
receiveMessage resource://gre/actors/SelectChild.jsm:242 
```

**To Reproduce**
1. Go to attributes, create several and click on "Visible on the product page" and "Used for variations".
2. Go to variations, create several variations and add attributes like images, etc.
![admin_variations](https://user-images.githubusercontent.com/47578103/52671988-c9a2f300-2f1c-11e9-818c-b7a582a97578.jpg)
2. Save changes
3. Go to product page, empty cache, etc. and click on the drop down menu to select variations. Only one or two random variations will show instead of the whole array created before.
4. Optionally read your browser console to see JS errors.
![frontend_variations](https://user-images.githubusercontent.com/47578103/52671990-c9a2f300-2f1c-11e9-8ac6-50fa72ff8605.jpg)
_It shows only Blue & Lime variations in this case._

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other caching plugins and confirmed this bug is not caused by any caching or JS minification-optimization issues.
- [ ] I have deactivated all the other plugins and confirmed this bug is caused only when Woocommerce is active. May do it with Plugin Organizer plugin if necessary but I'm a little afraid of breaking my site usability.
- [x] This bug happens with the Astra theme active.
- [x] I can reproduce this bug consistently using the steps above.

**Comment by kloon** [comment]
Please deactivate all plugins except WooCommerce and switch to a default theme like Twentyseventeen or Storefront. The issue does not happen for me so this is likely a plugin or theme conflict.

Will gladly re-open the issue if you can provide clear steps to replicate this with no plugins except WooCommerce and a default theme activated.
