### ISSUE TITLE
Add custom shipping cost for backend orders

### ISSUE THREAD

**Issue by Leoz83** [woocommerce/woocommerce#22725]
Hi, I need to add a custom shipping cost for some orders placed from backend.
`woocommerce_new_order` is not called for new orders starting from backend.
I've used `woocommerce_order_status_changed` and a custom status for backend orders.
Now, I've used this:
```php
$item = new WC_Order_Item_Shipping();
$item->set_props(
    array(
        'method_title' => "test",
        'method_id'    => "test",
        'cost'         => 10,
        'taxes'    => array(),
        'tax'    => array(),
        'calc_tax'  => 'per_order',
        'total'        => 10,
        'tax_class'    => NULL,
        'total_tax'    => 0,
        'tax_status'   => 'none',
        'meta_data' => array(),
        'package'   => false,
    )
);
$order->calculate_totals();
$order->add_item( $item );
$order->save();
```
but total price is calculated **without** shipping cost.
If i save again the order after first time, total is correct and including shipping cost without tax.

If I use `$order->calculate_totals();` **after** `$order->add_item( $item );`, shipping cost is calculated **with** tax.

Any way to have shipping cost without tax and correct order total?
Thanks in advance

**Comment by kloon** [comment]
You first need to add the item before calculating. Then pass a false parameter to calculate_totals, this will skip the tax calculation.

ie.
```
$item = new WC_Order_Item_Shipping();
$item->set_props(
    array(
        'method_title' => "test",
        'method_id'    => "test",
        'cost'         => 10,
        'taxes'    => array(),
        'tax'    => array(),
        'calc_tax'  => 'per_order',
        'total'        => 10,
        'tax_class'    => NULL,
        'total_tax'    => 0,
        'tax_status'   => 'none',
        'meta_data' => array(),
        'package'   => false,
    )
);
$order->add_item( $item );
$order->calculate_totals( false );
$order->save();
```
