### ISSUE TITLE
Update docs and product pages for FB in 3.6.0 OBW

### ISSUE THREAD

**Issue by v18** [woocommerce/woocommerce#22754]
Before we start recommending Facebook (#22218) we need to make sure to get these things done. The user-facing docs should not be updated before the release of WC 3.6 so that the docs match the UI available.

- [ ] update docs: https://www.facebook.com/business/help/900699293402826?helpref=search&sr=1&query=facebook%20for%20woocommerce
- [ ] update any WC.com docs as needed
- [ ] update https://woocommerce.com/products/facebook/ to work more like other .org hosted extensions like https://woocommerce.com/products/shipping/

Feel free to edit this issue as needed.

**Comment by v18** [comment]
Why is this posted here? p7bbVw-2Oa-p2#comment-6433

**Comment by timmyc** [comment]
@v18 since this issue can't really be "closed" by a PR against woo core here, do you think it would be better suited for a p2 post / checklist?

**Comment by timmyc** [comment]
Per my note yesterday, I'm going to close this out since it can not be "fixed" via code in this repository. Just trying to get to inbox zero on the milestone :)
