### ISSUE TITLE
Add filter to wc_get_product_stock_status_options() return value

### ISSUE THREAD

**Issue by theandystratton** [woocommerce/woocommerce#22757]
**Is your feature request related to a problem? Please describe.**
Client wanted to add "Special Order" to stock status options for variants of a product (variable product)

**Describe the solution you'd like**
I edited the array returned by `wc_get_product_stock_status_options()`

**Describe alternatives you've considered**
Simply add a filter to the return value:

```php
function wc_get_product_stock_status_options() {
	return apply_filters( 'wc_product_stock_status_options', array(
		'instock'     => __( 'In stock', 'woocommerce' ),
		'outofstock'  => __( 'Out of stock', 'woocommerce' ),
		'onbackorder' => __( 'On backorder', 'woocommerce' )
	) );
}
```

**Additional context**
This would help us avoid editing the plugin file to add a single item to the array:

```php
add_filter( 'wc_product_stock_status_options', function( $options ){
	$options['specialorder'] = __( 'Special Order', 'woocommerce' );
	return $options;
});
```

**Comment by nishitlangaliya** [comment]
@kloon as per suggestion I have added filter #22834. would you please review and let me know if any changes required.

Thanks

**Comment by theandystratton** [comment]
Thanks!! 
Looks good! When would this roll out?
