### ISSUE TITLE
Better handling of thumbnail resizing requirements

### ISSUE THREAD

**Issue by antermoia** [woocommerce/woocommerce#22759]
I first shared this in [https://wordpress.org/support/topic/thumbnails-124/ ](https://wordpress.org/support/topic/thumbnails-124/ ) and was advised to post this here on Github. Not sure if "Feature Requests" is the correct place. Someone please move it elsewhere if it isn't. Thanks.

**Is your feature request related to a problem? Please describe.**
I run a photography website with >5000 images online, and at present I have THREE WooCommerce product images in my Media Library. What I’m trying to illustrate with this is that my site is centered around photos, not the shop. WooCommerce is a great add-on, but on my site, it’s really an add-on.

After I noticed that WooCommerce registers additional thumbnail sizes (that I neither want nor need), I went and disabled the cropping in the Customizer – which then caused WooCommerce to begin regenerating thumbnails for ALL of my >5000 images!

Needless to say – this almost locked me out of my hosting (I found an older thread on how to kill this madness), and it is also ABSOLUTELY unnecessary to (re)generate thumbnails for thousands of images that have NOTHING to do with WooCommerce.

**Describe the solution you'd like**
1. a clear warning "ATTENTION! We're going to update ALL of your thumbnails now! Depending on the number of images in your Media Library, this may take a LONG time and may also consume A LOT of server-side resources. Is this REALLY what you want?" (YES/NO) - and if the user selects "No", tell them to manually regenerate thumbnails for the WC products (link to a thumbnail regen plugin etc.)

2. IDEALLY, when changes to WooCommerce's thumbnail settings are made, it should only affect the images that are ACTUALLY already in-use for WooCommerce "products." I am not a developer but my understanding is that since products are a custom post type, it should be relatively easy to determine which images are actually used - and then update only those.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by kloon** [comment]
Hi, thanks for the feedback.

> 1. a clear warning "ATTENTION! We're going to update ALL of your thumbnails now! Depending on the number of images in your Media Library, this may take a LONG time and may also consume A LOT of server-side resources. Is this REALLY what you want?" (YES/NO) - and if the user selects "No", tell them to manually regenerate thumbnails for the WC products (link to a thumbnail regen plugin etc.)

This is how it used to be before we introduced the auto regeneration functionality, with the exception that we did not have functionality built in that could regenerate, yet still people were sending in support requests about their images being blurry when changing settings. I have to add that the regeneration functionality is built in such a way that it regenerates the images in batches and not all at once.

> 2. IDEALLY, when changes to WooCommerce's thumbnail settings are made, it should only affect the images that are ACTUALLY already in-use for WooCommerce "products." I am not a developer but my understanding is that since products are a custom post type, it should be relatively easy to determine which images are actually used - and then update only those.

This is not something WooCommerce really controls. That is how the WordPress API handling images work. WP allows plugins and themes to declare image support when this is done no matter where you upload an image it will create additional images based on what the plugins and themes registered. Only generating images that are in use are problematic as you can select existing images from the media library on products, so now you generate only a certain set of images then the shop manager changes the image of a product to that of one that was not regenerated and that specific image will not look right.

We have introduced a filter which you probably already discovered which enables you to disable the functionality altogether should you wish to. If you would like to read up on image generation, how to disable it or offload it to an external service like Jetpack Photon then [please read the documentation around this](https://github.com/woocommerce/woocommerce/wiki/Thumbnail-Image-Regeneration-in-3.3).
