### ISSUE TITLE
Activating paid extension via WP CLI doesn't activate my subscription

### ISSUE THREAD

**Issue by gedex** [woocommerce/woocommerce#22762]
**Describe the bug**

The culprit of this is:

https://github.com/woocommerce/woocommerce/blob/59c97539b3891fb225025f1adf5fb1071a754182/includes/class-woocommerce.php#L398-L400

`class-wc-admin.php` loads helper files. The problem is helper files won't be loaded in CLI context because it only loads when request context is admin.

**To Reproduce**
1. Buy paid extension from WooCommerce.com
2. Download the extension and put it under plugins directory.
3. Activate the extension via WP CLI: `wp plugin activate <extension-slug>`
4. Go to **WooCommerce > Extensions** screen and see extension subscription is not active.

**Expected behavior**

It should activate my WooCommerce.com subscription. In other words, this:

https://github.com/woocommerce/woocommerce/blob/c7fc4a9521f56fd3dc272d96918a93544231d7b6/includes/admin/helper/class-wc-helper.php#L1145-L1215

should be fired in CLI context.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22972
