### ISSUE TITLE
How to activate prices including VAT

### ISSUE THREAD

**Issue by Slehm** [woocommerce/woocommerce#22770]
I cannot get the VAT to work. When I try to select the option, I cannot choose it. 

[vat](https://user-images.githubusercontent.com/47781120/53014895-19684980-344a-11e9-9687-e0e7f560b9ba.jpg)

**Comment by Luminus** [comment]
@Slehm you need to disable automated taxes.

Please take issues like this to the forum here - https://wordpress.org/support/plugin/woocommerce/ rather than the repo.
