### ISSUE TITLE
Fatal error: Uncaught Error: When Using shop_messages shortcode inconjunction with Yoast SEo

### ISSUE THREAD

**Issue by Creativenauts** [woocommerce/woocommerce#22772]
**Describe the bug**
When using [shop_messages] shortcode within product Fatal error: Uncaught Error: Call to undefined function wc_print_notices() occurs.

**To Reproduce**
1. Install Woocommerce & Yoast SEO
2. Create a new woocommerce product
3. Place [shop_messages] shortcode in editor
4. Click Publish or Update Product

**Expected behavior**
Should save the post without error

**Isolating the problem (mark completed items with an [x]):**
- [ ] This issue only occurs when yoast SEO and woocommerce is active.

**Error Posted In Yoast Repo**
https://github.com/Yoast/wordpress-seo/issues/8101

**Comment by mikejolley** [comment]
Something in Yoast must be rendering the content too early. We can protect against it to prevent teh error, but the actual cause will be in Yoast.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22855
