### ISSUE TITLE
Subscription Page does not load unless extra javascript is added

### ISSUE THREAD

**Issue by MHAdministrator** [woocommerce/woocommerce#22796]
**Describe the bug**
I have MyListing there installed with Woocommerce and WooSubscriptions. Then a client clicks on the option to view subscriptions the page does not load. The order s page loads but not the subscription information. MtListing (27collective.net) had a look for another client of theirs and suggested that the following javascript be loaded jQuery('.shop_table.subscription_details').append( '<span class="subscription-auto-renew-toggle"><i></i></span>' );

This sorts the issue out but should be fixed by woosubscriptions developers.

**To Reproduce**
Install MyListings theme with WooCommerce and WooSubscriptions
1. Create new listing using reoccurring package purchase
2. View all orders
3. Click on view under related subscriptions
4. Page does not load

https://helpdesk.27collective.net/questions/question/view-subscription-fails-to-load/

**Comment by rrennick** [comment]
You should an update available for WooCommerce Subscriptions sometime today. If you still see this issue after updating WCS then contact WCS support through https://woocommerce.com/contact-us/ .

Closing this as it's not an issue with WooCommerce core.
