### ISSUE TITLE
Use WC_Order_Refund->delete() consistently

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#22795]
The `WC_Order_Refund->delete()` method has a hook in it called `woocommerce_delete_order_refund` that could be useful to use whenever refunds are deleted (perhaps due to an API issue with payment gateways): https://github.com/woocommerce/woocommerce/blob/d0491072e8a7d0a4535db0ec2bae4a6d43ff64fd/includes/data-stores/class-wc-order-refund-data-store-cpt.php#L48-L58

But in `wc_create_refund()`, there is one call to `$refund->delete();` (line 593) but also a direct call to `wp_delete_post()`: https://github.com/woocommerce/woocommerce/blob/acd933a7dde2e6f95503b9db480484bfee8324da/includes/wc-order-functions.php#L624

Could this direct call be replaced with refund->delete() since it's already checking if `$refund` is of that class?

**Comment by kloon** [comment]
@WPprodigy the wp_delete_post in wc_create_refund is for deleting the refund that was created when something went wrong, whereas the delete method on WC_Order_Refund deletes the order being refunded.

The reason for the direct call to wp_delete_post when an exception happens is to ensure we do not have refunds in the database that is incomplete or contains erroneous data due to the exception that happened.

**Comment by WPprodigy** [comment]
Ah, that makes sense. Missed that, thanks.

I think there still might be a need for some sort of hook to ensure failed refunds trigger something, but I'll need to test a bit more first.

**Comment by WPprodigy** [comment]
> whereas the delete method on WC_Order_Refund deletes the order being refunded.

Hmm, why is the order being deleted when something went wrong with the refund, then?

https://github.com/woocommerce/woocommerce/blob/acd933a7dde2e6f95503b9db480484bfee8324da/includes/wc-order-functions.php#L592-L595

**Comment by mikejolley** [comment]
Not sure what @kloon meant there. Thats deleting the refund on failure, not an order. Note, refunds are a type of order and extend order classes.

**Comment by WPprodigy** [comment]
Gotcha. So then this could use `$refund->delete();` as well? : https://github.com/woocommerce/woocommerce/blob/acd933a7dde2e6f95503b9db480484bfee8324da/includes/wc-order-functions.php#L624 

Concern being that it would be nice to have the `woocommerce_delete_order_refund` hook run in both circumstances if they are both the refund being deleted due to errors during the process.

**Comment by mikejolley** [comment]
@WPprodigy hmm I'm not sure. It would make some sense, however, that is cleaning up a failed refund. Do we really need events for a refund which wasn't actually created fully/properly?

**Comment by WPprodigy** [comment]
The use case that brought me here was needing to track when refunds failed (timeouts, various gateway errors). If the `woocommerce_delete_order_refund` hook always fired when a refund was failed to be created, that would cover the use case pretty well.

**Comment by mikejolley** [comment]
A failed refund might deserve a dedicated hook so you can distingush from a manually deleted refund.
