### ISSUE TITLE
Checkout confirmation page takes long time to load

### ISSUE THREAD

**Issue by Darklaki** [woocommerce/woocommerce#22806]
**Describe the bug**
When placing an order confirmation page loads very slow (30-40 seconds). I've also noticed that order is visible in dashboard right after user clicks button, although confirmation page delay

**To Reproduce**
1. Add product to card
2. Try to finalize an order

**Expected behavior**
Loading confirmation page shouldn't take so long.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

`
### WordPress Environment ###

Home URL: https://yamatosushi.pl
Site URL: https://yamatosushi.pl
WC Version: 3.5.5
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: pl_PL
External object cache: –

### Server Environment ###

Server Info: Apache/2
PHP Version: 7.3.0
PHP Post Max Size: 64 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.47.0
GnuTLS/3.4.10

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.30-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Całkowity rozmiar bazy danych: 27.92MB
Rozmiar bazy danych: 18.37MB
Rozmiar indeksu bazy danych: 9.55MB
wp_woocommerce_sessions: Dane: 0.13MB + Indeks: 0.02MB
wp_woocommerce_api_keys: Dane: 0.02MB + Indeks: 0.03MB
wp_woocommerce_attribute_taxonomies: Dane: 0.02MB + Indeks: 0.02MB
wp_woocommerce_downloadable_product_permissions: Dane: 0.02MB + Indeks: 0.05MB
wp_woocommerce_order_items: Dane: 0.23MB + Indeks: 0.11MB
wp_woocommerce_order_itemmeta: Dane: 2.52MB + Indeks: 3.03MB
wp_woocommerce_tax_rates: Dane: 0.02MB + Indeks: 0.06MB
wp_woocommerce_tax_rate_locations: Dane: 0.02MB + Indeks: 0.03MB
wp_woocommerce_shipping_zones: Dane: 0.02MB + Indeks: 0.00MB
wp_woocommerce_shipping_zone_locations: Dane: 0.02MB + Indeks: 0.03MB
wp_woocommerce_shipping_zone_methods: Dane: 0.02MB + Indeks: 0.00MB
wp_woocommerce_payment_tokens: Dane: 0.02MB + Indeks: 0.02MB
wp_woocommerce_payment_tokenmeta: Dane: 0.02MB + Indeks: 0.03MB
wp_woocommerce_log: Dane: 0.02MB + Indeks: 0.02MB
wp_aryo_activity_log: Dane: 0.13MB + Indeks: 0.00MB
wp_commentmeta: Dane: 0.02MB + Indeks: 0.03MB
wp_comments: Dane: 0.27MB + Indeks: 0.31MB
wp_failed_jobs: Dane: 0.02MB + Indeks: 0.00MB
wp_hustle_modules: Dane: 0.02MB + Indeks: 0.03MB
wp_hustle_modules_meta: Dane: 0.02MB + Indeks: 0.03MB
wp_links: Dane: 0.02MB + Indeks: 0.02MB
wp_mailchimp_carts: Dane: 0.02MB + Indeks: 0.00MB
wp_options: Dane: 1.50MB + Indeks: 0.05MB
wp_postmeta: Dane: 4.52MB + Indeks: 4.03MB
wp_posts: Dane: 1.52MB + Indeks: 0.25MB
wp_queue: Dane: 0.02MB + Indeks: 0.00MB
wp_smush_dir_images: Dane: 0.02MB + Indeks: 0.03MB
wp_statistics_exclusions: Dane: 0.02MB + Indeks: 0.03MB
wp_statistics_historical: Dane: 0.02MB + Indeks: 0.05MB
wp_statistics_pages: Dane: 0.02MB + Indeks: 0.06MB
wp_statistics_search: Dane: 0.02MB + Indeks: 0.05MB
wp_statistics_useronline: Dane: 0.02MB + Indeks: 0.00MB
wp_statistics_visit: Dane: 0.02MB + Indeks: 0.02MB
wp_statistics_visitor: Dane: 0.02MB + Indeks: 0.08MB
wp_termmeta: Dane: 0.02MB + Indeks: 0.03MB
wp_terms: Dane: 0.02MB + Indeks: 0.03MB
wp_term_relationships: Dane: 0.05MB + Indeks: 0.02MB
wp_term_taxonomy: Dane: 0.02MB + Indeks: 0.03MB
wp_usermeta: Dane: 0.23MB + Indeks: 0.17MB
wp_users: Dane: 0.02MB + Indeks: 0.05MB
wp_wcpdf_invoice_number: Dane: 0.05MB + Indeks: 0.00MB
wp_wc_download_log: Dane: 0.02MB + Indeks: 0.03MB
wp_wc_webhooks: Dane: 0.02MB + Indeks: 0.02MB
wp_wfblockediplog: Dane: 0.09MB + Indeks: 0.00MB
wp_wfblocks7: Dane: 0.02MB + Indeks: 0.05MB
wp_wfconfig: Dane: 0.42MB + Indeks: 0.00MB
wp_wfcrawlers: Dane: 0.02MB + Indeks: 0.00MB
wp_wffilechanges: Dane: 0.02MB + Indeks: 0.00MB
wp_wffilemods: Dane: 3.52MB + Indeks: 0.00MB
wp_wfhits: Dane: 0.44MB + Indeks: 0.20MB
wp_wfhoover: Dane: 0.02MB + Indeks: 0.02MB
wp_wfissues: Dane: 0.02MB + Indeks: 0.06MB
wp_wfknownfilelist: Dane: 1.52MB + Indeks: 0.00MB
wp_wflivetraffichuman: Dane: 0.02MB + Indeks: 0.02MB
wp_wflocs: Dane: 0.02MB + Indeks: 0.00MB
wp_wflogins: Dane: 0.14MB + Indeks: 0.06MB
wp_wfnotifications: Dane: 0.02MB + Indeks: 0.00MB
wp_wfpendingissues: Dane: 0.02MB + Indeks: 0.06MB
wp_wfreversecache: Dane: 0.02MB + Indeks: 0.00MB
wp_wfsnipcache: Dane: 0.02MB + Indeks: 0.05MB
wp_wfstatus: Dane: 0.13MB + Indeks: 0.11MB
wp_wftrafficrates: Dane: 0.02MB + Indeks: 0.00MB
wp_wpmm_subscribers: Dane: 0.02MB + Indeks: 0.00MB
wp_yoast_seo_links: Dane: 0.02MB + Indeks: 0.02MB
wp_yoast_seo_meta: Dane: 0.02MB + Indeks: 0.00MB
ya_newsletter: Dane: 0.02MB + Indeks: 0.00MB

### Post Type Counts ###

acf: 3
acf-field: 2
acf-field-group: 2
attachment: 151
page: 10
post: 2
product: 164
revision: 64
shop_coupon: 8
shop_order: 737
wpcf7_contact_form: 1
yith-wccos-ostatus: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

Advanced Custom Fields: przez Elliot Condon – 5.7.10
Dziennik aktywności: przez Activity Log Team – 2.5.2
BackWPup: przez Inpsyde GmbH – 3.6.7
Check and Enable GZIP compression: przez Richard's Toolbox – 1.1.11
Klasyczny edytor: przez Kontrybutorzy WordPressa – 1.4
Contact Form 7: przez Takayuki Miyoshi – 5.1.1
Custom Order Status for WooCommerce: przez Tyche Softwares – 1.4.6
Custom Payment Gateways for WooCommerce Pro: przez Algoritmika Ltd – 1.1.1 – Nietestowane z używaną wersją WooCommerce
Facebook for WooCommerce: przez Facebook – 1.9.8 – Nietestowane z używaną wersją WooCommerce
Google Analytics Dashboard for WP (GADWP): przez ExactMetrics – 5.3.7
Loco Translate: przez Tim Whitlock – 2.2.0
Really Simple SSL: przez Rogier Lankhorst
Mark Wolters – 3.1.3

reSmush.it Image Optimizer: przez reSmush.it – 0.1.22
TinyMCE Advanced: przez Andrew Ozz – 5.0.1
Checkout Field Editor for WooCommerce: przez ThemeHiGH – 1.3.1
WooCommerce PDF Invoices & Packing Slips: przez Ewout Fernhout – 2.2.6
WooCommerce: przez Automattic – 3.5.5
Wordfence Security: przez Wordfence – 7.2.2
WordPress Importer: przez wordpressdotorg – 0.6.4
Hustle: przez WPMU DEV – 6.0.7
Yoast SEO: przez Zespół Yoast – 9.6
WP Admin UI Customize: przez gqevu6bsiz – 1.5.12
WP Tryb Konserwacji: przez Designmodo – 2.2.2
WP Desk Helper: przez WP Desk – 1.6.2

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: PLN (zł)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Strona sklepu: #5 - /sklep/
Koszyk: #6 - /koszyk/
Zamówienie: ❌ Strona nie zawiera shortcode.
Moje konto: ❌ Strona nie zawiera shortcode.
Regulamin: #234 - /regulamin/

### Theme ###

Name: yamato
Version: – 0 jest dostępne
Author URL: 
Child Theme: ❌ – Jeśli modyfikujesz WooCommerce lub motyw nadrzędny
którego nie jesteś autorem
polecamy używanie motywu potomnego. Zobacz: Jak tworzyć motywy potomne

WooCommerce Support: ❌ Nie zadeklarowane

### Templates ###

Overrides: yamato/woocommerce/archive-product.php
yamato/woocommerce/cart/cart.php wersja 3.4.0 jest nieaktualna. Bazowa wersja to 3.5.0
yamato/woocommerce/cart/mini-cart.php wersja 3.3.0 jest nieaktualna. Bazowa wersja to 3.5.0
yamato/woocommerce/checkout/form-coupon.php
yamato/woocommerce/emails/customer-processing-order.php wersja 2.5.0 jest nieaktualna. Bazowa wersja to 3.5.4
yamato/woocommerce/myaccount/dashboard.php
yamato/woocommerce/myaccount/downloads.php
yamato/woocommerce/myaccount/form-add-payment-method.php
yamato/woocommerce/myaccount/form-edit-account.php wersja 3.4.0 jest nieaktualna. Bazowa wersja to 3.5.0
yamato/woocommerce/myaccount/form-edit-address.php
yamato/woocommerce/myaccount/form-login.php wersja 3.4.0 jest nieaktualna. Bazowa wersja to 3.5.0
yamato/woocommerce/myaccount/form-lost-password.php wersja 3.4.0 jest nieaktualna. Bazowa wersja to 3.5.2
yamato/woocommerce/myaccount/form-reset-password.php wersja 3.4.0 jest nieaktualna. Bazowa wersja to 3.5.5
yamato/woocommerce/myaccount/lost-password-confirmation.php wersja 2.6.0 jest nieaktualna. Bazowa wersja to 3.5.2
yamato/woocommerce/myaccount/my-account.php wersja 2.6.0 jest nieaktualna. Bazowa wersja to 3.5.0
yamato/woocommerce/myaccount/my-address.php
yamato/woocommerce/myaccount/my-downloads.php
yamato/woocommerce/myaccount/my-orders.php
yamato/woocommerce/myaccount/navigation.php
yamato/woocommerce/myaccount/orders.php
yamato/woocommerce/myaccount/payment-methods.php
yamato/woocommerce/myaccount/view-order.php
yamato/woocommerce/order/form-tracking.php
yamato/woocommerce/order/order-again.php wersja 2.3.0 jest nieaktualna. Bazowa wersja to 3.5.0
yamato/woocommerce/order/order-details-customer.php
yamato/woocommerce/order/order-details-item.php
yamato/woocommerce/order/order-details.php wersja 3.3.0 jest nieaktualna. Bazowa wersja to 3.5.2
yamato/woocommerce/order/order-downloads.php
yamato/woocommerce/order/tracking.php

</details>

**Comment by mikejolley** [comment]
If the order is created then the delay can either be the gateway you're using or the email sending. This is not reproducable on my store and others.

> * I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.

Unless you disabled the gateway and tested a default gateway like BACS you didn't test this?

1. Enable BACS. Place an order with that gateway. if it's quicker, it's your custom gateway taking too long to make whatever request it's doing.
2. To speed up emails you could try deffering them

```
add_filter( 'woocommerce_defer_transactional_emails', '__return_true' );
```

My guess is it's the gateway not the emails.

Thanks
