### ISSUE TITLE
WSOD - no products on shop page

### ISSUE THREAD

**Issue by mkogit** [woocommerce/woocommerce#22801]
**Describe the bug**
Sometimes my "/shop" page shows no products but title "Shop" only, there are no error messages even with WP_DEBUG=true. Switching themes back and forth solved the problem temporary as well as changing permalink settings from custom to e.g. shop-based.

**To Reproduce**
1. Go to Settings -> Permalinks and set product permalinks to "custom" := "/products/" (not "/shop/")
2. Check https://yoursite/shop -> page is empty / no products
3. Go to Settings -> Permalinks and set product permalinks to "shop-based"
4. Check https://yoursite/shop -> product list is visible again

**Screenshots**

**Expected behavior**
https://yoursite/shop should always show your products.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

I guess in includes/wc-core-functions.php:956 rewrite rules are not returned correct, For '/shop/?$' function wc_fix_rewrite_rules maps to shop-page itself instead of product list, so maybe boolean 'use_verbose_page_rules' should be true for custom permalink setting?

**WordPress Environment**
`
### WordPress Environment ###

Home URL: https://...
Site URL: https://...
WC Version: 3.5.4
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.40-0+deb8u1 - Wir empfehlen
PHP Version 7.2 oder höher für mehr Leistung und Sicherheit zu verwenden. So aktualisierst du deine PHP-Version

PHP Post Max Size: 100 MB
PHP Time Limit: 240
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.62-0+deb8u1 - Wir empfehlen mindestens MySQL-Version 5.6. Siehe: WordPress-Anforderungen
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.4
WC Database Prefix: wp_2_
Datenbank-Gesamtgröße: 11.66MB
Datenbank-Datengröße: 9.38MB
Datenbank-Indexgröße: 2.28MB
wp_2_woocommerce_sessions: Daten: 0.02MB + Index: 0.02MB
wp_2_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB
wp_2_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB
wp_2_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.05MB
wp_2_woocommerce_order_items: Daten: 0.06MB + Index: 0.02MB
wp_2_woocommerce_order_itemmeta: Daten: 0.20MB + Index: 0.22MB
wp_2_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB
wp_2_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB
wp_2_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB
wp_2_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB
wp_2_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB
wp_2_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB
wp_2_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB
wp_2_woocommerce_log: Daten: 0.02MB + Index: 0.02MB
wp_2_commentmeta: Daten: 0.02MB + Index: 0.03MB
wp_2_comments: Daten: 0.06MB + Index: 0.09MB
wp_2_myproject_invoice: Daten: 0.02MB + Index: 0.02MB
wp_2_em_bookings: Daten: 0.02MB + Index: 0.05MB
wp_2_em_events: Daten: 0.05MB + Index: 0.14MB
wp_2_em_locations: Daten: 0.02MB + Index: 0.08MB
wp_2_em_meta: Daten: 0.02MB + Index: 0.03MB
wp_2_em_tickets: Daten: 0.02MB + Index: 0.02MB
wp_2_em_tickets_bookings: Daten: 0.02MB + Index: 0.03MB
wp_2_links: Daten: 0.02MB + Index: 0.02MB
wp_2_newsletter: Daten: 0.02MB + Index: 0.03MB
wp_2_newsletter_emails: Daten: 0.02MB + Index: 0.00MB
wp_2_newsletter_sent: Daten: 0.02MB + Index: 0.03MB
wp_2_newsletter_stats: Daten: 0.02MB + Index: 0.03MB
wp_2_newsletter_user_logs: Daten: 0.02MB + Index: 0.00MB
wp_2_options: Daten: 3.11MB + Index: 0.06MB
wp_2_postmeta: Daten: 1.52MB + Index: 0.45MB
wp_2_posts: Daten: 3.48MB + Index: 0.20MB
wp_2_termmeta: Daten: 0.02MB + Index: 0.03MB
wp_2_terms: Daten: 0.02MB + Index: 0.03MB
wp_2_term_relationships: Daten: 0.02MB + Index: 0.02MB
wp_2_term_taxonomy: Daten: 0.02MB + Index: 0.03MB
wp_2_wc_download_log: Daten: 0.02MB + Index: 0.03MB
wp_2_wc_webhooks: Daten: 0.02MB + Index: 0.02MB
wp_blogs: Daten: 0.02MB + Index: 0.03MB
wp_blog_versions: Daten: 0.02MB + Index: 0.02MB
wp_registration_log: Daten: 0.02MB + Index: 0.02MB
wp_signups: Daten: 0.02MB + Index: 0.06MB
wp_site: Daten: 0.02MB + Index: 0.02MB
wp_sitemeta: Daten: 0.11MB + Index: 0.03MB
wp_usermeta: Daten: 0.05MB + Index: 0.03MB
wp_users: Daten: 0.02MB + Index: 0.05MB

### Post Type Counts ###

attachment: 92
custom_css: 1
customize_changeset: 3
event: 15
location: 2
ml-slider: 1
nav_menu_item: 22
page: 24
pickup_location: 2
post: 5
product: 16
revision: 601
shop_coupon: 12
shop_order: 82
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Fehlermeldungen sollten Besuchern nicht angezeigt werden.

### Active Plugins (10) ###

All In One SEO Pack: von Michael Torbert – 2.11
CryptX: von Ralf Weber – 3.2.16
Events Manager: von Marcus Sykes – 5.9.5
Newsletter: von Stefano Lissa & The Newsletter Team – 5.8.8
TinyMCE Advanced: von Andrew Ozz – 5.0.1
WooCommerce PDF Invoices: von Bas Elbers – 2.9.16 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce: von Automattic – 3.5.4 – 3.5.5 ist verfügbar
WP Responsive Menu: von MagniGenie – 3.1.3
WordPress MU Domain Mapping: von Donncha O Caoimh – 0.5.5.1

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop-Basis: #4 - /shop/
Warenkorb: #5 - /cart/
Kasse: #6 - /checkout/
Mein Konto: #7 - /my-account/
Allgemeine Geschäftsbedingungen: #116 - /agb-online-shop/

### Theme ###

Name: mychildtheme
Version: 0.1
Author URL: https://....
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.4.3
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: mychildtheme/woocommerce/archive-product.php
mychildtheme/woocommerce/cart/cart-shipping.php
mychildtheme/woocommerce/cart/cart.php
mychildtheme/woocommerce/checkout/payment-method.php
mychildtheme/woocommerce/checkout/payment.php
mychildtheme/woocommerce/emails/customer-invoice.php
mychildtheme/woocommerce/emails/customer-on-hold-order.php
mychildtheme/woocommerce/emails/customer-processing-order.php
mychildtheme/woocommerce/emails/email-addresses.php
mychildtheme/woocommerce/emails/email-footer.php
mychildtheme/woocommerce/emails/email-header.php
mychildtheme/woocommerce/emails/email-order-details.php
mychildtheme/woocommerce/emails/email-order-items.php
mychildtheme/woocommerce/emails/email-styles.php
mychildtheme/woocommerce/single-product/price.php
mychildtheme/woocommerce/single-product/product-attributes.php
mychildtheme/woocommerce/single-product/tabs/additional-information.php
mychildtheme/woocommerce/single-product-reviews.php
mychildtheme/woocommerce/single-product.php

`

**Comment by janakkaneriya007** [comment]
@mkogit 

I have tried to reproduce the issue by the steps you have mentioned but it's working.

Can you please try by disabling all the plugins except the WooCommerce and switching to WordPress default themes?

**Comment by mkogit** [comment]
Dear Janak,
thanks a lot for your test, after a long debugging session I found that "Events Manager" plugin causes the issue, if no events page is defined. So I will report to events manager support.
