### ISSUE TITLE
Changing attributes on already created variation products

### ISSUE THREAD

**Issue by albertramsbottom** [woocommerce/woocommerce#22800]
Changing attributes on already created variation products and saving them to create newly names size variations does save. Just keeps on spinning and nothing happens

65 variations with format:
SKU-Colour-Name-Size
i.e. NNmtfotl34-hather-grey-small

If I delete the already used size attribute and change it for a new size attribute with S,M,L,XL,XXL instead of Small, Medium,Large, X-Large, XX-large

And then save it, to create the new variations it just hangs

I do have Woo Commerce SKU Generator by SkyVerge installed

Cheers

**Comment by mikejolley** [comment]
I've reported this here https://github.com/skyverge/woocommerce-product-sku-generator/issues/16
