### ISSUE TITLE
REST API: Tax code filtering by request param

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce#22812]
**Is your feature request related to a problem? Please describe.**
We need to be able to filter returned tax codes by searching for a tax code name in the rest api so we can add or amend this bit:

```php
		$query = "
			SELECT *
			FROM {$wpdb->prefix}woocommerce_tax_rates
			WHERE 1 = 1
		";
```

**Describe the solution you'd like**
A filter around the query should allow us to do this.

**Describe alternatives you've considered**
Alternatively we could pull all tax codes and filter client-side, but this seems hacky.

**Comment by claudiosanches** [comment]
See my comment in the PR: https://github.com/woocommerce/woocommerce/pull/22813#pullrequestreview-206961730
