### ISSUE TITLE
back to shop does not update when deleting a product

### ISSUE THREAD

**Issue by timholz** [woocommerce/woocommerce#22816]
With version 3.5.5 i notice that the «back to shop» button does not update correctly when i delete a product in the cart. The button text «back to shop» is outside the  a-tag.
I checked cart-empty.php and could not find any mistake. Only when the page is refreshed the behaviour is as expected.

1. Add product to cart
2. delete product in cart
3. the button text shows, but is outside the a-tag

**Screenshots**
![grafik](https://user-images.githubusercontent.com/11427894/53235975-6db23a00-3693-11e9-9784-0727d2bc23f8.png)

![grafik](https://user-images.githubusercontent.com/11427894/53236045-a6eaaa00-3693-11e9-9908-5751cdd97761.png)

Inspecting the dom: text is outside a-tag.

The button-text should be inside the a-tag.

My workaround is to add the text with css pseudo class:

`.woocommerce p .wc-backward:before{
 content:'Retour à la boutique';`

Latest wordpress.

regards
theo

**Comment by mikejolley** [comment]
You can see in the template itself it is within the a tag https://github.com/woocommerce/woocommerce/blob/d7090929e2aa9bb8a712483c6e311b4bf4843d64/templates/cart/cart-empty.php#L28

And if you VIEW SOURCE it will also be within. The inspector shows the markup after any changes from JavaScript for example.

This means in your case this is either:

- Your theme has modified the template I showed above
- JavaScript on your page is moving the text
- Whatever is making that custom font appear is not injecting itself into the correct DOM element.

This is specific to your store so you'll need to check these things out and rule out your plugins and theme.

Thanks

**Comment by timholz** [comment]
Hi – Thanks for your answer. Must be a plugin then...
