### ISSUE TITLE
Issue with "Other" payment method in translations (class-wc-meta-box-order-data.php)

### ISSUE THREAD

**Issue by rynaldos** [woocommerce/woocommerce#22817]
Howdy!

The "Other" payment method here https://github.com/woocommerce/woocommerce/blob/81360d682764658c9fa5e79c795b0cb4ccf93967/includes/admin/meta-boxes/class-wc-meta-box-order-data.php#L404 does not show the translation in the invoice 

It is output here: https://github.com/woocommerce/woocommerce/blob/81360d682764658c9fa5e79c795b0cb4ccf93967/includes/admin/meta-boxes/class-wc-meta-box-order-data.php#L193 and appears to fetch the value in the database, hence it is lowercase and not translated

Is there a way we can show the translation? 

Here's the backend: 

<img width="467" alt="screen shot 2019-02-22 at 12 49 25" src="https://user-images.githubusercontent.com/6198774/53237824-57f74180-36a0-11e9-97d6-aba2515da428.png">

Here's the result: 

<img width="273" alt="screen_shot_2019-02-22_at_12 30 38" src="https://user-images.githubusercontent.com/6198774/53237868-6e9d9880-36a0-11e9-8758-c9cd7382430d.png">

Cheers!

**Comment by mikejolley** [comment]
Probably best to not output anything when a real payment method is not set.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22889
