### ISSUE TITLE
Allow webhook calls to http with WP_DEBUG

### ISSUE THREAD

**Issue by kshishkin** [woocommerce/woocommerce#22827]
WC requires https for webhook calls.
When building handler the dev faces challanges. I call for making the http work under WP_DEBUG.

The problem fixed in this SO, the siimpliest way would be just to surround with WP_DEBUG condition.
https://stackoverflow.com/questions/31875442/woocommerce-webhook-invalid-url

**Comment by claudiosanches** [comment]
All URLs must be safe, if you need to test, you can use external services like https://webhook.site/
Also there's filters on WordPress to filter `wp_safe_remote_post()`, so you can allow HTTP.

**Comment by kshishkin** [comment]
All URL's should be safe in production - could not agree more.
For development - another story.  We need to have control on how the client is handling the received hookshots. We do it on localhosts. We should have a simple way to allow hookshots to http endpoint for that purpose.

Without that people start testing out of production env and the overall security gets worse.

**Comment by claudiosanches** [comment]
@kshishkin as I said, this need to be deactivated on WordPress.
