### ISSUE TITLE
Reports are wrong when orders are in multiple currencies

### ISSUE THREAD

**Issue by beckos** [woocommerce/woocommerce#22823]
When orders are in more currencies, reports do not take care of conversions, yet they grab the shop's currency sign and sums the totals, displaying absolute numbers which do not reflect reality. Totally wrong.

I am running WooCommerce Currency Switcher Version 2.2.7.1 | By realmag777 and although the conversion rate is recorded within the order details, the reports don't use this.

**Comment by mikejolley** [comment]
The reporting system does **not** support multiple currency. Conversion plugins should convert to the store base currency, or filter/adjust the reporting to match their structure.

The currency converter on woo.com for example DISPLAYS in other currencies, but does not store those converted values. This is a plugin issue.

**Comment by beckos** [comment]
Okay. I'll contact them. Thanks.
