### ISSUE TITLE
Make error handling consistent in payment processing

### ISSUE THREAD

**Issue by villesiltala** [woocommerce/woocommerce#22836]
I am creating a custom payment gateway for a Finnish online payment processor. Currently, there seem to be two situations in which the `process_payment()` method of a payment gateway is called:
1. The checkout process `class-wc-checkout.php:888`
2. The customer payment page process `class-wc-form-handler.php:405`

Error handling for these two situations diverge. The first one uses error catching and the latter one seems to just trust that the payment process always succeeds.

This inconsistency makes it hard to code a clean error handling for both situations since there is only one payment process method to be called in the implemented gateway class.

My preferred solution for this would be to add a try-catch block for the payment page payment process and make it fall back to the previous page if an error is thrown from the payment process. The error message could then be displayed similarly as the Storefront theme displays error messages on the checkout page from the thrown error. This change would allow anyone implementing a payment gateway to always throw an error in the `process_payment()` method if something goes wrong and trust that the theme can handle the error in a consistent way.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22916
