### ISSUE TITLE
Wrong label "Total" instead of "Subtotal" in the Cart page

### ISSUE THREAD

**Issue by elmarilion** [woocommerce/woocommerce#22839]
Hello, 

In the cart page, in the table "shop_table shop_table_responsive cart woocommerce-cart-form__contents"  the _th_ value "product-subtotal"  is labeled as **Total**.

In the same page, in the table "cart_totals" the _th_ value of the "order-total" class is also labeled as **Total**.

This has as a result that in the same page the label **Total** appears twice, while only in the "cart_totals" table is right. 

I would like to ask you to change the first label to **Subtotal**, which it really is.

In the cart folder --> cart.php file, I change the value **Total** into **Subtotal** in lines 33 and 118.

Similar problem in the Checkout page: in the checkout folder --> review-order.php, I change the value **Total** into **Price** on line 27.

I would like to ask you to consider these changes, too, which are - from the description - more correct than the actual ones.

Thank you in advance.

**Comment by mikejolley** [comment]
The template is correct, seen here: https://github.com/woocommerce/woocommerce/blob/master/templates/cart/cart.php#L118

For products, horizontally from left to right this should read: Product, Price, Quantity, Total. In this context, total being the total for the line (price X quantity).

Thanks

**Comment by elmarilion** [comment]
Hi, 

thanks for the answer. 

Of course, as you say, it is the **total of the line**, which makes it a **Subtotal** (as the name of the class is also, for a reason), but still named "Total" in the front. In addition, the summary of all **totals of the lines** is also named "Total" (which it really is). 

So, the **totals of the lines** are named "Total" and the **total of the totals of the lines** is also named "Total" in the same page!

Just find it not very accurate and for the buyer even a bit confusing!

Hope you can reconsider. KR.

**Comment by mikejolley** [comment]
If you compare to cart subtotal, yes it could be confusing, but they are in separate areas.

FWIW sites like amazon just show price and don't bother with line totals.
