### ISSUE TITLE
[REST API] Delete Product Response has status property as "published" not "trashed"

### ISSUE THREAD

**Issue by richardaubin** [woocommerce/woocommerce#22833]
**Describe the bug**
The v3 api documentation shows the delete product response having a status property of "published" when it should be "trashed".

I've confirmed this deleting a product using the api and reading the json response.

**Comment by claudiosanches** [comment]
The same happens when deleting posts, pages and any other object on WP REST API, we just follow the same.

But we going to update all responses to use the same updated format using:

```
{
  "deleted": true,
  "previous": {..."status": "publish",...}
}
```

**Comment by mikejolley** [comment]
Since this needs to go in a new version of the API, and we're working on v4 API as part of the wc-admin project, I've raised a PR for this here: https://github.com/woocommerce/woocommerce-admin/pull/1861
