### ISSUE TITLE
Shipping methods instances remain in the wp_options table when deleting the zone

### ISSUE THREAD

**Issue by acanza** [woocommerce/woocommerce#22838]
**Describe the bug**
When a zone with one or more shipping methods is deleted, the settings of these shipping methods instances remain in the wp_options table. Leaving a lot of garbage in the database.

**To Reproduce**
1. Go to ‘WooCommerce > Settings > Shipping'
2. Create a new zone
3. Add, for example, a Flat Rate shipping method and setup its settings
4. Go back to shipping zones page and delete the zone along with its methods
5. Finally access to your database, check wp_options table and you'll can see as the "woocommerce_flat_rate_[instance_ID]_settings" has not been deleted

**Screenshots**
<img width="1273" alt="captura de pantalla 2019-02-23 a las 16 15 49" src="https://user-images.githubusercontent.com/3978410/53288443-530dbd00-3788-11e9-97d3-e8f5090e128b.png">

**Expected behavior**
Deleting every data of the shipping method instance when the zone it belongs to is also delete.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22867
