### ISSUE TITLE
Warning: Missing argument 3 for wgpb_extra_shortcode_features()

### ISSUE THREAD

**Issue by 3adegh** [woocommerce/woocommerce#22835]
Full error is :

Warning: Missing argument 3 for wgpb_extra_shortcode_features() in /home/.../domains/.../public_html/wp-content/plugins/woo-gutenberg-products-block/woocommerce-gutenberg-products-block.php on line 476

after update woocomerce the error epear in top of the product block in page

**Comment by kloon** [comment]
Hi thanks for the report, the blocks are still a feature plugin operating independently from core. Could I ask you please log this on that repository https://github.com/woocommerce/woocommerce-gutenberg-products-block
