### ISSUE TITLE
Tracking is disabled if the first step of the OBW is revisited

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce#22861]
**Describe the bug**
If the setup wizard is revisited after tracking was opted in, the tracking is turned off on the next step.

**To Reproduce**
1. Make sure the option `woocommerce_allow_tracking` is set to `yes`.
2. Go to the OBW `wp-admin/admin.php?page=wc-setup`.
3. Click "Let's go!" to proceed to the next step.
4. Note that the `woocommerce_allow_tracking` is now set to no.

This is because the opt-in checkbox is not shown since the option is already set:
https://github.com/woocommerce/woocommerce/blob/5c414507f9f65037cc388c076a326d8b7ab34260/includes/admin/class-wc-admin-setup-wizard.php#L508-L523

But after saving, tracking is turned off if nothing is set:
https://github.com/woocommerce/woocommerce/blob/5c414507f9f65037cc388c076a326d8b7ab34260/includes/admin/class-wc-admin-setup-wizard.php#L579-L584

**Expected behavior**
Expected tracking to remain active or at least show the opt-in checkbox to allow opting back in.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by kloon** [comment]
See #22884
