### ISSUE TITLE
Gutenberg Support for Product Categories

### ISSUE THREAD

**Issue by nickw108** [woocommerce/woocommerce#22862]
Not sure if this has already come up previously or if this is the right place to request this feature? I could also post it in https://github.com/woocommerce/woocommerce-gutenberg-products-block/. 

Currently, the category description is using a simple text area field instead of Gutenberg:
![screenshot 2019-02-26 at 14 22 09](https://user-images.githubusercontent.com/58966/53415643-061d2700-39d2-11e9-8804-e5e80dacb5b1.png)

With the power of the Gutenberg Blocks plugin available for posts and pages, many shop owners will want to use that for regular category pages, too.

**Comment by mikejolley** [comment]
This would be a request for WordPress core - post categories don't have it either.

https://wordpress.stackexchange.com/questions/312145/activate-gutenberg-in-category-descriptions
https://github.com/WordPress/gutenberg/issues/12511

When WP adds support for it in that position, we should be able to also :)

Thanks

**Comment by nicobsas** [comment]
I am waiting for that release too

**Comment by LauGau** [comment]
Waiting for that too...

**Comment by angang** [comment]
Waiting for that too :)

**Comment by CreativeDive** [comment]
Waiting ...

**Comment by Flaschenzug** [comment]
I am also waiting for this function ... and wonder why it is not already implemented.
Categories are so important. Gutenberg is a way to structure posts much better.

**Comment by 7einhalb** [comment]
It´s been 2 years ago and I´m also looking for this release. Is there any workaround available to just copy and use the Gutenberg-Code into the description instead of implementing the whole editor in categories?

**Comment by 7einhalb** [comment]
It´s been 2 years ago and I´m also looking for this release.

**Comment by reyrahn** [comment]
+1 
Alñternatives and/or Plugins available are not quite friendly with SEO and affect the performance of other functions like filters, attribute, etc. as well.
Hope to see Gutenberg working asap! Rgds.
