### ISSUE TITLE
 error Images ALT always empty on products

### ISSUE THREAD

**Issue by hikmalfach** [woocommerce/woocommerce#22863]
Please fix, i dont know why this error only on woocommerce product [product image & product gallery]. my woocommerce category, post and page is normal [HAVE ALT on images].

you can inspect and check here for example: https://medigi.website/product/tema-wordpress-hestia-flower/

please fix, thank you.

**Comment by mikejolley** [comment]
The images have alt text 

view-source:https://medigi.website/product/tema-wordpress-hestia-flower/ 

What you're looking at is the gallery generated by Flexslider.

Found https://github.com/woocommerce/FlexSlider/issues/1389 - will see if that attribute works.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22865
