### ISSUE TITLE
Extensions: Add section for inactive plugins in system status report

### ISSUE THREAD

**Issue by mansi-shah-2248** [woocommerce/woocommerce#22878]
**Is your feature request related to a problem? Please describe.**
When customers submit their system status report, it only shows the list of active plugins. It sometimes happens that plugin (for which they have raised support is de-activated, due to any reason). In such cases, we have to explicitly ask them version of that de-activated plugin.

**Describe the solution you'd like**
Separate section for inactive plugins in system status report.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22951
