### ISSUE TITLE
Coupons manager completely missing

### ISSUE THREAD

**Issue by androos** [woocommerce/woocommerce#22880]
Some Shops I manage have no Coupon menu in Backend available. It is completely missing. There is no link in the admin menu. If I try to use the link from a healthy site I get this message:
example.com/wp-admin/edit.php?post_type=shop_coupon

Invalid content type

These are clearly older Installation but I don't know how old. What can I do to repair this?

**Comment by mikejolley** [comment]
WC > Settings > General > "Enable the use of coupon codes"
