### ISSUE TITLE
Extensions: Show in system status if WooCommerce account is connected

### ISSUE THREAD

**Issue by mansi-shah-2248** [woocommerce/woocommerce#22882]
**Describe the solution you'd like**
Show in system status if woocommerce.com account is connected.

**Additional context**
![wc-connected](https://user-images.githubusercontent.com/16662063/53484293-82366e00-3aa9-11e9-9e55-2bbf3299f3c0.png)

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22887
