### ISSUE TITLE
PayPal fee meta set after New Order email sent (using IPN)

### ISSUE THREAD

**Issue by galbaras** [woocommerce/woocommerce#22886]
**Describe the bug**
IPN is the method recommended by PayPal for best reliability of payment confirmation, but it introduces a lag into the confirmation process.

When using this method (I haven't tested with PDT), and capturing the "PayPal Transaction Fee" meta in a woocommerce_email_order_meta_fields filter for New Order emails, no fee appears.

However, at a later time, resending the New Order email shows the correct fee in the message.

**To Reproduce**
1. Buy something on the site using PayPal
2. Check the New Order email - no PayPal fee
3. After a few minutes, resend the New Order email for the order from step 1 & 2
4. Check the New Order email - PayPal fee is displayed

**Expected behavior**
New Order email should be generated and sent to the store admin only when the IPN loop has been closed and all the transaction details are available.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

Home URL: https://www.behappyinlife.com
Site URL: https://www.behappyinlife.com
WC Version: 3.5.5
Log Directory Writable: ✔
WP Version: 5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.1.26 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 10.2.22-MariaDB
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.5
WC Database Prefix: wpbhil_
Total Database Size: 95.05MB
Database Data Size: 73.78MB
Database Index Size: 21.27MB
wpbhil_woocommerce_sessions: Data: 0.03MB + Index: 0.00MB
wpbhil_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wpbhil_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wpbhil_woocommerce_downloadable_product_permissions: Data: 0.03MB + Index: 0.04MB
wpbhil_woocommerce_order_items: Data: 0.03MB + Index: 0.02MB
wpbhil_woocommerce_order_itemmeta: Data: 0.18MB + Index: 0.12MB
wpbhil_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wpbhil_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wpbhil_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wpbhil_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
wpbhil_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wpbhil_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wpbhil_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.01MB
wpbhil_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wpbhil_cf7dbplugin_st: Data: 0.06MB + Index: 0.00MB
wpbhil_cf7dbplugin_submits: Data: 1.52MB + Index: 1.08MB
wpbhil_commentmeta: Data: 0.01MB + Index: 0.02MB
wpbhil_comments: Data: 0.10MB + Index: 0.06MB
wpbhil_et_bloom_stats: Data: 0.00MB + Index: 0.00MB
wpbhil_ewwwio_images: Data: 0.96MB + Index: 0.45MB
wpbhil_ewwwio_queue: Data: 0.02MB + Index: 0.02MB
wpbhil_itsec_distributed_storage: Data: 13.96MB + Index: 0.00MB
wpbhil_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB
wpbhil_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB
wpbhil_itsec_lockouts: Data: 0.02MB + Index: 0.08MB
wpbhil_itsec_log: Data: 2.02MB + Index: 0.11MB
wpbhil_itsec_logs: Data: 9.82MB + Index: 0.26MB
wpbhil_itsec_temp: Data: 0.02MB + Index: 0.06MB
wpbhil_iwp_backup_status: Data: 0.09MB + Index: 0.00MB
wpbhil_iwp_file_list: Data: 0.00MB + Index: 0.00MB
wpbhil_links: Data: 0.00MB + Index: 0.00MB
wpbhil_mclean_refs: Data: 0.00MB + Index: 0.00MB
wpbhil_mclean_scan: Data: 0.14MB + Index: 0.03MB
wpbhil_options: Data: 9.14MB + Index: 0.26MB
wpbhil_postmeta: Data: 2.23MB + Index: 0.93MB
wpbhil_posts: Data: 3.76MB + Index: 0.25MB
wpbhil_redirection_404: Data: 25.55MB + Index: 16.09MB
wpbhil_redirection_groups: Data: 0.00MB + Index: 0.00MB
wpbhil_redirection_items: Data: 0.02MB + Index: 0.03MB
wpbhil_redirection_logs: Data: 2.72MB + Index: 0.94MB
wpbhil_termmeta: Data: 0.01MB + Index: 0.02MB
wpbhil_terms: Data: 0.00MB + Index: 0.01MB
wpbhil_term_relationships: Data: 0.01MB + Index: 0.03MB
wpbhil_term_taxonomy: Data: 0.01MB + Index: 0.01MB
wpbhil_usermeta: Data: 0.16MB + Index: 0.11MB
wpbhil_users: Data: 0.01MB + Index: 0.01MB
wpbhil_wc_download_log: Data: 0.00MB + Index: 0.01MB
wpbhil_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wpbhil_woocommerce_gpf_google_taxonomy: Data: 0.86MB + Index: 0.00MB
wpbhil_wpmlautoresponderemails: Data: 0.00MB + Index: 0.00MB
wpbhil_wpmlautoresponders: Data: 0.00MB + Index: 0.00MB
wpbhil_wpmlautoresponderslists: Data: 0.00MB + Index: 0.00MB
wpbhil_wpmlbounces: Data: 0.00MB + Index: 0.00MB
wpbhil_wpmlclicks: Data: 0.00MB + Index: 0.00MB
wpbhil_wpmlcontents: Data: 0.00MB + Index: 0.00MB
wpbhil_wpmlcountries: Data: 0.01MB + Index: 0.02MB
wpbhil_wpmlemails: Data: 0.00MB + Index: 0.01MB
wpbhil_wpmlfields: Data: 0.00MB + Index: 0.01MB
wpbhil_wpmlfieldsforms: Data: 0.00MB + Index: 0.00MB
wpbhil_wpmlfieldslists: Data: 0.00MB + Index: 0.00MB
wpbhil_wpmlforms: Data: 0.00MB + Index: 0.00MB
wpbhil_wpmlgroups: Data: 0.00MB + Index: 0.00MB
wpbhil_wpmlhistoriesattachments: Data: 0.00MB + Index: 0.00MB
wpbhil_wpmlhistorieslists: Data: 0.00MB + Index: 0.00MB
wpbhil_wpmlhistory: Data: 0.00MB + Index: 0.01MB
wpbhil_wpmllatestposts: Data: 0.00MB + Index: 0.00MB
wpbhil_wpmllatestpostssubscriptions: Data: 0.00MB + Index: 0.00MB
wpbhil_wpmllinks: Data: 0.00MB + Index: 0.00MB
wpbhil_wpmlmailinglists: Data: 0.00MB + Index: 0.00MB
wpbhil_wpmloptions: Data: 0.00MB + Index: 0.00MB
wpbhil_wpmlorders: Data: 0.00MB + Index: 0.00MB
wpbhil_wpmlposts: Data: 0.00MB + Index: 0.00MB
wpbhil_wpmlsubscribermetas: Data: 0.00MB + Index: 0.00MB
wpbhil_wpmlsubscribers: Data: 0.00MB + Index: 0.02MB
wpbhil_wpmlsubscriberslists: Data: 0.00MB + Index: 0.01MB
wpbhil_wpmlsubscribersoptions: Data: 0.00MB + Index: 0.00MB
wpbhil_wpmltemplates: Data: 0.00MB + Index: 0.00MB
wpbhil_wpmlthemes: Data: 0.09MB + Index: 0.00MB
wpbhil_wpmlunsubscribes: Data: 0.00MB + Index: 0.00MB
wpbhil_wysija_campaign: Data: 0.00MB + Index: 0.00MB
wpbhil_wysija_campaign_list: Data: 0.00MB + Index: 0.00MB
wpbhil_wysija_custom_field: Data: 0.00MB + Index: 0.00MB
wpbhil_wysija_email: Data: 0.11MB + Index: 0.00MB
wpbhil_wysija_email_user_stat: Data: 0.00MB + Index: 0.00MB
wpbhil_wysija_email_user_url: Data: 0.00MB + Index: 0.00MB
wpbhil_wysija_form: Data: 0.00MB + Index: 0.00MB
wpbhil_wysija_list: Data: 0.00MB + Index: 0.00MB
wpbhil_wysija_queue: Data: 0.00MB + Index: 0.00MB
wpbhil_wysija_subscriber_ips: Data: 0.00MB + Index: 0.00MB
wpbhil_wysija_url: Data: 0.00MB + Index: 0.00MB
wpbhil_wysija_url_mail: Data: 0.00MB + Index: 0.00MB
wpbhil_wysija_user: Data: 0.02MB + Index: 0.02MB
wpbhil_wysija_user_field: Data: 0.00MB + Index: 0.00MB
wpbhil_wysija_user_history: Data: 0.00MB + Index: 0.00MB
wpbhil_wysija_user_list: Data: 0.01MB + Index: 0.01MB
wpbhil_yoast_seo_links: Data: 0.01MB + Index: 0.01MB
wpbhil_yoast_seo_meta: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 324
home_page: 4
iwp_log: 1142
nav_menu_item: 95
newsletter: 1
page: 78
portfolio: 1
post: 38
product: 5
product_variation: 28
products: 1
revision: 135
shop_coupon: 8
shop_order: 253
shop_order_refund: 5
slider: 3
testimonial: 276
wpcf7_contact_form: 5
wpsc-product: 1
wysijap: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (34) ###

InfiniteWP - Client: by Revmakx – 1.8.6
Akismet Anti-Spam: by Automattic – 4.1.1
iThemes Security: by iThemes – 7.3.1
Classic Editor: by WordPress Contributors – 1.4
Contact Form 7 IE DatePicker and Number Spinner Fix: by Benjamin Klein – 2.6
Contact Form 7 - Dynamic Text Extension: by Chris Mavricos
SevenSpark – 2.0.2.1

Contact Form 7 Honeypot: by Nocean – 1.14
Contact Form DB: by Michael Simpson – 2.10.29
Contact Form 7: by Takayuki Miyoshi – 5.1.1
Currency Switcher for WooCommerce: by Algoritmika Ltd – 2.9.7 – Not tested with the active version of WooCommerce
Easy Testimonials: by Gold Plugins – 3.3.1
EWWW Image Optimizer: by Exactly WWW – 4.6.3
Fluid Video Embeds: by jamie3d – 1.2.9
MonsterInsights - eCommerce Addon: by MonsterInsights Team – 7.1.1
Custom Extensions and Styles: by Gal Baras – 2.9
Genesis Shortcode Generator: by Josh Mallard – 2.0.1
MonsterInsights Pro: by MonsterInsights – 7.4.2
Jetpack by WordPress.com: by Automattic – 7.0.1
Media Cleaner Pro: by Jordy Meow – 5.1.1
Media File Renamer Auto: by Jordy Meow – 4.5.2
Redirection: by John Godley – 3.7.3
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.0
Simple Tags: by Amaury BALMER – 2.4.7
SMTP Mailer: by naa986 – 1.0.5
Video Thumbnails: by Sutherland Boswell – 2.12.3
WooCommerce Stripe Gateway: by WooCommerce – 4.1.14
WooCommerce: by Automattic – 3.5.5
WooMailpoet: by Lucy Eind – 2.3.1 – Not tested with the active version of WooCommerce
Yoast SEO: by Team Yoast – 9.6
WP Fastest Cache Premium: by Emre Vona – 1.5.2
WP Fastest Cache: by Emre Vona – 0.8.9.1
WP Sitemap Page: by Tony Archambeau – 1.6.1
Yoast SEO: WooCommerce: by Team Yoast – 9.6.1
MailPoet 2: by MailPoet – 2.10.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #937 - /books-products/
Cart: #1129 - /cart/
Checkout: #1130 - /checkout/
My account: #1132 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Beautiful Pro Theme
Version: 1.1
Author URL: https://www.studiopress.com/
Child Theme: ✔
Parent Theme Name: Genesis
Parent Theme Version: 2.8.1
Parent Theme Author URL: https://www.studiopress.com/
WooCommerce Support: ✔

### Templates ###

Overrides: beautiful-pro/woocommerce/checkout/thankyou.php
beautiful-pro/woocommerce/emails/email-styles.php
</details>

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22892
