### ISSUE TITLE
"Thanks for reading." in emails

### ISSUE THREAD

**Issue by njeffers** [woocommerce/woocommerce#22895]
**Describe the bug**
The wording at the end of many of the emails seems to be a bit off. I'm not the only one, as clients bring it to my attention quite a bit. I know I can always replace this, but I feel like we can do a bit better still out of the box. I see that this is related to #21288, which actually made quite a bit of progress towards this already. I added a slightly modified version that's a bit cleaner (and left aligns the company name to match the rest of the email).

**To Reproduce**
1. Send an order email

**Screenshots**
![image](https://user-images.githubusercontent.com/10125982/53507481-dbcc7780-3a6c-11e9-878d-f72f2e15f5ef.png)

![image](https://user-images.githubusercontent.com/10125982/53508163-1256c200-3a6e-11e9-8198-62f37712ee93.png)

**Comment by willgorham** [comment]
I agree that 'Thanks for reading.' feels odd and unnecessary.

**Comment by mikejolley** [comment]
I've worked on this here as it affected quite a few emails and it's quite hard to make this generic enough to work for everyone: https://github.com/woocommerce/woocommerce/pull/22927

Thanks
