### ISSUE TITLE
Categories on main shop page aren't cached per language

### ISSUE THREAD

**Issue by freeaanzee** [woocommerce/woocommerce#22894]
**Describe the bug**
The list of categories on the main shop page is cached by woocommerce_get_product_subcategories() using wp_cache_set() with the 'product-category-hierarchy-0' key. The zero index is shared by all translations of the main shop page (created by e.g. WPML) and causes category names to 'bleed' across translations.

Within a category the caching key for the list of subcategories is suffixed by the actual parent category ID, which is different in each language. So the problem only occurs on the main shop page.

**To reproduce**
1. Purge all object caches
2. Visit main shop page in the first language
3. Visit main shop page in the second language
4. Admire category names still being displayed in the first language

**Screenshots**

First language:

![Dutch](https://www.fairtradecrafts.be/product-category-hierarchy-0-nl.png)

Second language immediately after the switch:

![French](https://www.fairtradecrafts.be/product-category-hierarchy-0.png)

**Expected behavior**
Category names are always displayed in the selected language.

**Isolating the problem**
I understand this appears to be more of a WPML than a WooCommerce issue, but looking at the code responsible (see below) I don't see a way for external plugins to circumvent the way WooCommerce caches the main categories.

https://github.com/woocommerce/woocommerce/blob/0469bbe8b0946bddbd86717dcf8d66305c937d48/includes/wc-template-functions.php#L2416-L2444

For compatibility the easiest solution would just be not executing wp_cache_set() if $parent_id is equal to 0. That's how I fixed it for now, but of course this means the main shop page is no longer cached!

At your service,

Frederik

**Comment by mikejolley** [comment]
I don't think we should skip the cache for this because it will reduce performance on stores running a single language. We can wrap the cache key with a filter to allow WPML to append the site language to the cache key.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22915

**Comment by freeaanzee** [comment]
Perfect, I wanted to suggest a similar filter. I'll drop the WPML team a note.
