### ISSUE TITLE
Placeholder image should have a nicer width/height ratio

### ISSUE THREAD

**Issue by R33D3M33R** [woocommerce/woocommerce#22907]
Dear developers,

currently the placeholder.png image has a width of 398px and height of 391px. This 7 pixel deficiency results in visual quirks (gaps, floats breaking) if used on a site with square images. Since placeholder.png used to have perfect 1:1 aspect ratio, the change might have broken some existing sites.

I'm aware that an arbitrary placeholder image can be set in the wc-settings product tab, however I would prefer that the ratio would stay 1:1 as it was before commit https://github.com/woocommerce/woocommerce/commit/6b68c15309c2ede96a158d171ed764a6b79bc5ee

Best regards,
Andrej Mernik

**Comment by mikejolley** [comment]
Updated in a43a873a1344703141f8e022d0624f640da13f12
