### ISSUE TITLE
after registration the default hooks like "wp_login" aren't triggered

### ISSUE THREAD

**Issue by SebastianTusk** [woocommerce/woocommerce#22905]
After registration the new user is immediately authenticated. This is done without triggering Wordpress hooks like "wp_login". This might break plugins using these hooks.

**Comment by mikejolley** [comment]
wp_login is triggered via wp_signon which expects user credentials.

https://codex.wordpress.org/Function_Reference/wp_signon

During registration we're not accepting logon credentials, so passing those around and validating login details does not occur. Triggering it manually could lead to undesirable outcomes. e.g. a captcha plugin using wp_login would break the automatic-logon after registration.

Therefore it's probably not a good idea to trigger this action nor call wp_signon etc in this case.

https://github.com/WordPress/WordPress/blob/655d44ffe813eb9a64e30a6339316338246e9efc/wp-includes/pluggable.php#L815

`wp_set_auth_cookie` triggers it's own hooks which could be intercepted if desired.

`set_auth_cookie`
`set_logged_in_cookie`

To avoid conflicts, I don't think we should be firing wp_login hooks.

If you need to disable auto-login in woocommerce, add:

```
add_filter( 'woocommerce_registration_auth_new_customer', '__return_false' );
```

Thanks

**Comment by cesarvspr** [comment]
helpful content: https://www.businessbloomer.com/woocommerce-deny-automatic-login-upon-registration-my-account/?ck_subscriber_id=426953987
