### ISSUE TITLE
Remove Rounding when Number of Decimals is set to `0`

### ISSUE THREAD

**Issue by ldr2273** [woocommerce/woocommerce#22918]
Howdy,

I'm listing this as a Question/Enhancement because I'm sure it could potentially fit into both categories.

Currently, in _WooCommerce > Settings > General_, when you set the `Number of Decimals` to `0`, it rounds product prices up to the nearest dollar. I understand the logic in this for obvious reasons, but would it be possible to only do this on prices that are currently set at the dollar mark?

For example, products listed as $24.00 will display as $24, but any products listed as $3.95 will remain at $3.95?

I was checking for some snippets that might achieve this but couldn't locate any that would work. Is this something we could add an option for in core in the future? Or is this kind of an edge case?

Thanks for your feedback, and if I need to ask somewhere else, please re-route me :)

**Comment by mikejolley** [comment]
Rather than touch rounding, could the price display functions not be filtered to remove .00? Can you give more details on the use case? It sounds wrong to change DP to only affect display - the DP setting impacts some calculations also.

**Comment by ldr2273** [comment]
Hi @mikejolley,

> Rather than touch rounding, could the price display functions not be filtered to remove .00?

That would work for this particular case. I think I found something that will work: https://www.wpstud.io/show-hide-trailing-zeros-prices-woocommerce/

After testing, it appears to do the trick.

> It sounds wrong to change DP to only affect display - the DP setting impacts some calculations also.

Absolutely agree here. I was figuring this might be the case but wanted to confirm. Thanks for clarifying! 

I'm going to close this out now since the snippet would work for this use-case. Thanks for the insight!
