### ISSUE TITLE
 if  address_2 field insn't used, placeholder are saved and considerate as part of destination

### ISSUE THREAD

**Issue by kampiamodikuesto** [woocommerce/woocommerce#22911]
**Describe the bug**
If a user doesn't use/write on second address field (billing or shipping field) woocommerce save the placeholder "Appartment, unit...) as a value. So on the cart page under shipping estimation it is showed the first address field plus the placeholder "appartment, unit, ....". 

For the checkout is quite simple to unset billing_address_2 or shipping_address_2 (by codo or by customizer) but for the cart isn't becouse address_1 and address_2 are showed as one value ( $formatted_destination). This depends to WC()->countries->get_formatted_address( $package['destination'] (cart-shipping.php tamplate file).

**Expected behavior**
I would like that if a user doesn't use/write on second address field, nothig have to be saved.

**Comment by mikejolley** [comment]
This happens on themes which use placeholder scripts which add content to the input fields. This is not something that happens with WC by default on the core WordPress themes. Confirm it's your theme and contact the theme author.

Thanks
