### ISSUE TITLE
Breadcrumb's structured data are missing link for last item on pagination page

### ISSUE THREAD

**Issue by alexraputa** [woocommerce/woocommerce#22923]
**Describe the bug**
The last item of the breadcrumb is missing the link in the structured data for pagination pages. It can be seen also on WooCommerce.com.

**To Reproduce**
1. Go to any pagination page on a site.
2. View Source.
3. Search for BreadcrumbList.
4. See the error in the last item, having the ID not set to a URL.

**Screenshots**
<img width="634" alt="2019-03-04 13 22 14" src="https://user-images.githubusercontent.com/10957915/53730444-9ea72180-3e80-11e9-87c4-13a1f513e2c4.png">

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WooCommerce: 3.5.5
WordPress: 5.1

**Comment by mikejolley** [comment]
Added to https://github.com/woocommerce/woocommerce/pull/22925
