### ISSUE TITLE
infinite loop with do_shortcode 

### ISSUE THREAD

**Issue by Victorlerner** [woocommerce/woocommerce#22924]
https://github.com/woocommerce/woocommerce/issues/22785 
This is a continuation of this thread.
developers do all theme, so give them the option to turn it off.
can just add there variable $disable_do_shortcode = false;
Then I can via functions.php and add_filter make this variable true

**Comment by mikejolley** [comment]
Please don't open duplicate issues. I just have not gotten around to replying yet.
