### ISSUE TITLE
Woocommerce rest api return woocommerce_rest_cannot_view always

### ISSUE THREAD

**Issue by MahdiPishguy** [woocommerce/woocommerce#22926]
I have generated a consumer key and consumer secret. The website has SSL installed. I have also installed plugins required for JSON and REST services. This is how the url looks like:

`https://<url>/wp-json/wc/v1/products`

**If you want to test**

```
Consumer Key: ck_8add1dc9101f8793a731d6b9aeaadd319fbedf37
Consumer secret: cs_18980264faa482536874e4544dfce9c090c7e927
```

When I am trying to get(GET) the product details using Basic Auth by using POSTMAN, a Chrome plugin, I get a JSON response like:

```
{
  "code": "woocommerce_rest_cannot_view",
  "message": "Sorry, you cannot list resources.",
  "data": {
    "status": 401
  }
}
```

I have both the READ and WRITE permissions corresponding to the Consumer key. I'm testing this RestApi on PostMan RestClient and i disabled SSL ceritificate verification on this app settings

**ScreenShot of PostMan:**
https://i.stack.imgur.com/LR6xb.png

**Comment by mikejolley** [comment]
@MahdiPishguy If this is a live site, delete those keys immedietely

**Comment by MahdiPishguy** [comment]
@mikejolley no problem, this site is only for test

**Comment by mikejolley** [comment]
Basic auth is only possible over SSL https://github.com/woocommerce/woocommerce/blob/15bcef85e931269336ed0458276e8fccdfec935b/includes/api/class-wc-rest-authentication.php#L77-L79

Your screenshot shows you're using `http://`
