### ISSUE TITLE
Edit order page totals don't match calculations

### ISSUE THREAD

**Issue by seanreloaded** [woocommerce/woocommerce#22929]
**Describe the bug**
On the edit order page, the product(s) price is not displayed correctly even though the calculations with a coupon ARE correct.

This behavior can be seen on orders with a single product or multiple products.

**To Reproduce**

1. Create a coupon for a fixed cart discount. Include a usage restriction of a min spend. Then add a required product for the discount to trigger.
2. Add simple test product to cart and proceed to cart/checkout.
3. Complete the order.
4. Edit the order in the backend.

**Screenshots**

For a single item, the order displays like this:
![alt](https://cdn-std.dprcdn.net/files/acc_403167/Xre96z)
Image link: Image link: https://cld.wthms.co/Xre96z

For an order with multiple single items (or variations, it doesn't matter), the order displays like this:
![alt](https://cdn-std.dprcdn.net/files/acc_403167/j4wv9k)
Image link: https://cld.wthms.co/j4wv9k

Despite using a fixed amount cart coupon, the order displays like a percentage was taken from each item in the cart. Although, the calculation itself is incorrect, this looks incorrect to the shop owner.

It should also be made clear that this behavior only affects the backend order pages. The email notifications display the proper amounts.

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

This can be reproduced using nothing else than the default WooCommerce 3.5.5 and no other active plugins.

**Comment by mikejolley** [comment]
It's not `40 -10`, the `40` is the discounted line price. Ill see if we can add some clearer text to show this.

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/22949 open for feedback
