### ISSUE TITLE
Failed order email notification links to wrong documentation

### ISSUE THREAD

**Issue by addedlovely** [woocommerce/woocommerce#22939]
**Describe the bug**
The admin 'failed' order email notification links to https://docs.woocommerce.com/document/managing-orders/#section-10 - but that section of documentation is now 'Removing Personal Data'.

See:
https://github.com/woocommerce/woocommerce/blob/2c2891c17a54c5daa7cc624c9e1246af1d0e8d6b/templates/emails/admin-failed-order.php#L52

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22943

**Comment by dphyled** [comment]
Hi there!! I see the PR for this was merged back in March. However, checking on my site with WooCommerce 3.7 (and 3.6.5), I am seeing that the link in the Failed Order email is still linking to the "Removing Personal Data" documentation:
https://docs.woocommerce.com/document/managing-orders/#section-10

**Comment by claudiosanches** [comment]
This got reintroduced by mistake.

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24535.
