### ISSUE TITLE
Allow sale price to 23:59:59 on last sale date

### ISSUE THREAD

**Issue by stormit** [woocommerce/woocommerce#22933]
Hello,

My issue still is not solved. But you closed my topic. So I have to create another topic. PLEASE DON'T CLOSE TOPIC UNTIL IT IS SOLVED. This is my issue [https://github.com/woocommerce/woocommerce/issues/22545](https://github.com/woocommerce/woocommerce/issues/22545)

Thank you!

**Comment by mikejolley** [comment]
Ping someone in the old issue, do not open duplicates.
