### ISSUE TITLE
WC 2.2 cart preservation

### ISSUE THREAD

**Issue by fesarlis** [woocommerce/woocommerce#22934]
Hello,
I have an old WC 2.2.11/WP 4.6.1 installation which at the moment cannot be upgraded due to many customized features. It works fine with no issues at all. I have just a simple question:

Is cart preserved in WC 2.2? I am referring only to logged-in users. For example I login in as customer and add products to the cart. If I logout and login again the cart is empty. Is this normal behaviour? If so, can the cart be preserved for users who have an account (not guest shoppers)?

All my other eshops which use latest versions of WP and WC do that. For this particular one we have to stick with 2.2.11.

Thank you

**Comment by mikejolley** [comment]
There was a persistent cart in 2.2 however, I cannot say if it had any issues. There has been a lot of work on that part since then. We cannot support that old a version here so you'd need to debug this yourself (most of the logic is in the cart class).

Thanks
