### ISSUE TITLE
WooCommerce status widget in dashboard could use more caching

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#22947]
The WooCommerce Status widget on the dashboard page runs several queries for getting sales data. In particular it runs a query which gets the sales amount for this month: https://github.com/woocommerce/woocommerce/blob/3.5.5/includes/admin/class-wc-admin-dashboard.php#L91-L101

Since this query includes the current time stamp as an end date. This means the query hash will be unique every second. Because of this we don't take full advantage of the caching which is built into `WC_Admin_Report` class.

One suggestion would be to round off this timestamp to at least the current minute (or possibly even 10 minutes).

Another query which is called by this status widget is to determine the top sold product: https://github.com/woocommerce/woocommerce/blob/3.5.5/includes/admin/class-wc-admin-dashboard.php#L64-L84

This doesn't include any caching so will be run every time the dashboard page is loaded. Would there be an advantage in caching this as well? To me it would make sense to cache this for a full day.

**Comment by mikejolley** [comment]
@mikkamp We have a separate PR for get_top_seller which uses cache + lookup table.

**Comment by mikejolley** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/22950 - we can match the reports section.

**Comment by dz0ny** [comment]
This is quite a problem for big stores, it takes up to second and for each admin visits as mentioned above. Even an hourly cache would be better than the current setup.
