### ISSUE TITLE
How can i change product stock information using REST API in Delphi?

### ISSUE THREAD

**Issue by whitehorse3513** [woocommerce/woocommerce#22942]
Hi, How are you?
Now I am developing a Delphi program that modifies product stock information using Woocommerce REST API.
I can get Product information using REST API like in the sample.
But I can't modify the product stock information like sale_price.
Who knows Please Help me.
[Projects.zip](https://github.com/woocommerce/woocommerce/files/2934510/Projects.zip)

**Comment by mikejolley** [comment]
You need to do a PUT request as documented here http://woocommerce.github.io/woocommerce-rest-api-docs/#update-a-product

Test it in a client first to ensure the requests work on your site https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API

We don't offer support here however so I cannot help with your specific problem, plus we're not delphi developers :D 

Best of luck!

**Comment by MicrodeltaSL** [comment]
hello whitehorse3513, how you solved it? I have the same problem.

Thanks.

**Comment by anglam62** [comment]
Hello, I have the same problem.
is there anyone who can help me?
