### ISSUE TITLE
HP Notice:  get_id was called incorrectly. Product properties should not be accessed directly.

### ISSUE THREAD

**Issue by 0dp** [woocommerce/woocommerce#22946]
**Describe the bug**
I normally see the error that id was called incorrectly, and to fix it use get_id().
Updating some code I received the following notice:
 `PHP Notice:  get_id was called incorrectly. Product properties should not be accessed directly.`

Using the following code.
```
global $wpdb;
global $product;
$results = $wpdb->get_results( "SELECT * FROM {$wpdb->prefix}postmeta WHERE post_id IN (SELECT ID FROM {$wpdb->prefix}posts WHERE post_parent = $product->get_id() AND post_type = 'product_variation') AND meta_key = '_price_" . $_SESSION['custom_currency'] . "'", OBJECT );
```
The `$product->get_id()` returns nothing, and that creates a syntax error in the SQL query.

**Comment by mikejolley** [comment]
Using get_id is correct however you're not adding it to the query correctly which is likely why it's empty.... Use $wpdb->prepare. Your code is not secure.

We also don't know what $product is in this context. Ensure it's a product object.

I'm closing this, it's not a WC issue.

**Comment by 0dp** [comment]
Thanks @mikejolley for pointing out the SQL was not prepared.

I disagree though with your statement that we don't know what $product is in this context. We do know that its a product object. hence `Product properties should not be accessed directly.`

**Comment by 0dp** [comment]
```
[06-Mar-2019 14:20:29 Europe/Copenhagen] WC_Product_Variable Object
(
    [children:protected] => 
    [visible_children:protected] => 
    [variation_attributes:protected] => 
    [object_type:protected] => product
    [post_type:protected] => product
    [cache_group:protected] => products
...
    [id:protected] => 16173
...
```

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-data.php#L177

All product classes extend this.

**Comment by 0dp** [comment]
What's your point?

**Comment by mikejolley** [comment]
The point is to recieve that warning you must have something (not WC core) calling ->id, because `get_id` for sure exists and no one else is reporting this issue.

**Comment by mikejolley** [comment]
I'm not sure what you mean. Can you paste the entire code you're using there?

Are you certain the notice is coming from this block and nothing else?

**Comment by 0dp** [comment]
Yes, let's consider these two blocks of code
```
global $wpdb;
global $product;
log_me( $product->get_id() ); // logging function to verify that we're actually getting product object and that we can retrieve the id
 $proid = $product->get_id();

// Code  that works where we are using the variable $proid that holds the product id
 $results = $wpdb->query( $wpdb->prepare( "SELECT * FROM {$wpdb->prefix}postmeta WHERE post_id IN (SELECT ID FROM {$wpdb->prefix}posts WHERE post_parent = %d AND post_type = 'product_variation') AND meta_key = %s", $proid, "_price_".$_SESSION['custom_currency'] ), OBJECT  );

// This will fail...using $product->get_id()
 $results = $wpdb->query( $wpdb->prepare( "SELECT * FROM {$wpdb->prefix}postmeta WHERE post_id IN (SELECT ID FROM {$wpdb->prefix}posts WHERE post_parent = %d AND post_type = 'product_variation') AND meta_key = %s", $product->get_id(), "_price_".$_SESSION['custom_currency'] ), OBJECT  );
```
The failing code will result in, 
`PHP Notice:  get_id was called incorrectly. Product properties should not be accessed directly.`
Because $product->get_id() failed, this will result in syntax error in the sql because it is empty or unaccessible for some reason.

The working code merely assigns $product->get_id() to a variable and we use that instead

**Comment by soft79** [comment]
I doubt that is the entire code. I think you have a logic error somewhere in your code. Can you paste the complete function?

**Comment by 0dp** [comment]
I doubt it would make a difference though. As I explain in the examples above.

1. I verified what $product was in this context.
1. I showed that $product->get_id() was empty (private)
1. Error messages was shown
1. Came up with a work around

The question still remains, how and why?

Googling `PHP Notice: get_id was called incorrectly. Product properties should not be accessed directly.`
Shows that the notice is rare, to say the least.

**Comment by soft79** [comment]
```php
$proid = $product->get_id();

// Code  that works where we are using the variable $proid that holds the product id
 $results = $wpdb->query( $wpdb->prepare( "SELECT * FROM {$wpdb->prefix}postmeta WHERE post_id IN (SELECT ID FROM {$wpdb->prefix}posts WHERE post_parent = %d AND post_type = 'product_variation') AND meta_key = %s", $proid, "_price_".$_SESSION['custom_currency'] ), OBJECT  );

// This will fail...using $product->get_id()
 $results = $wpdb->query( $wpdb->prepare( "SELECT * FROM {$wpdb->prefix}postmeta WHERE post_id IN (SELECT ID FROM {$wpdb->prefix}posts WHERE post_parent = %d AND post_type = 'product_variation') AND meta_key = %s", $product->get_id(), "_price_".$_SESSION['custom_currency'] ), OBJECT  );
```

There is no difference between the two methods you showed. It is not possible that one will throw the notice and the other won't.

I suspect that in the actual code you are missing parenthesis after `get_id`.

**Comment by 0dp** [comment]
One uses a variable called $prodid that holds the result of $product->get_id() the other one uses $product->get_id() directly

**Comment by soft79** [comment]
Which is practically the same. Are you sure you're not missing parenthesis in the actual code? Just post the entire actual code.

**Comment by soft79** [comment]
You did adjust the code from your first post, I presume? That one won't work since the get_id() is between the double quotes and would indeed raise the notice. Did you follow Mike's advise and are you actually using the prepared statement?

**Comment by 0dp** [comment]
Did you see my edited response above?

If $product is a product object. And get_id is inherited by this. Then what does:
PHP Notice: get_id was called incorrectly. Product properties should not be accessed directly. mean?

I did edit the code from the first post. It's been further edited to be in sprintf format.
```
$results = $wpdb->query( $wpdb->prepare( "SELECT * FROM {$wpdb->prefix}postmeta WHERE post_id IN (SELECT ID FROM {$wpdb->prefix}posts WHERE post_parent = %d AND post_type = 'product_variation') AND meta_key = %s", $proid, "_price_".$_SESSION['custom_currency'] ), OBJECT  );
```
If I change that to
```
$results = $wpdb->query( $wpdb->prepare( "SELECT * FROM {$wpdb->prefix}postmeta WHERE post_id IN (SELECT ID FROM {$wpdb->prefix}posts WHERE post_parent = %d AND post_type = 'product_variation') AND meta_key = %s", $product->get_id(), "_price_".$_SESSION['custom_currency'] ), OBJECT  );
```
I will get `PHP Notice: get_id was called incorrectly. Product properties should not be accessed directly.`

**Comment by soft79** [comment]
No you won't. Just paste the actual code that causes the notice. Maybe you're even looking at the wrong place. 

You could hack a debug_print_backtrace() in the WC_Abstract_Legacy_Product __get() function just to be sure.

**Comment by 0dp** [comment]
I don't know what to tell you

**Comment by soft79** [comment]
Well, frankly if what you posted is the actual code, then it can't be a WC bug, it must be a PHP bug, but I really doubt that's the case. Either:

- you are missing parenthesis after $product->get_id
- you "use $product->get_id() between double quotes".
- you are concentrating on the wrong part of code and the issue occurs somewhere else.

**Comment by 0dp** [comment]
This notice, PHP Notice: get_id was called incorrectly. Product properties should not be accessed directly.

I don't understand what that means given that $product is product object? Is that not the point of get_id()?

**Comment by soft79** [comment]
Do you see the difference between the following lines?
Tell me, which one will yield the right result.

```php
$id1 = $product->get_id();
$id2 = "$product->get_id()";
$id3 = $product->get_id;
```

**Comment by 0dp** [comment]
You don't have to be patronizing

**Comment by soft79** [comment]
Patronizing? Don't get me wrong. Trying to help you here. 2 out of the 3 lines in my last post will trigger the notice. You are using get_id wrong. But if you don't show us the exact code nobody can help you. 

Good luck.

**Comment by mikejolley** [comment]
> If $product is a product object. And get_id is inherited by this. Then what does:
PHP Notice: get_id was called incorrectly. Product properties should not be accessed directly. mean?

This is thrown if a getter is not used. i.e. `$product->id` or the examples soft79 provided. When you access a class variable directly. 

`->get_id();` is a method (https://github.com/woocommerce/woocommerce/issues/22946#issuecomment-470106528) and so cannot cause this notice.

**Comment by soft79** [comment]
Yes, one detail: If $product->id is used the message would be

    PHP Notice: id was called incorrectly. Product properties should not be accessed directly.
Not
    PHP Notice: get_id was called incorrectly. Product properties should not be accessed directly.
