### ISSUE TITLE
Incoherent messages in edit address

### ISSUE THREAD

**Issue by xac369** [woocommerce/woocommerce#22940]
**Describe the bug**
If you change a country without "State / County" field to another country with "State / County", an incoherent information is displayed in error message and field.

**To Reproduce**
1. Edit your address (billing or shipping). 
2. Change to country "France" submit correct form
3. Edit your address again, and choose country "Gabon"
3. A new field "State / County *" appears in form (required field)
4. Leave field "State / County *" empty
5. Submit form

An error message on top of form "State / County is a required field."
The field "State / County (optional)" (required become optional) 
=> incoherent informations between, and wrong "optional" label

**Screenshots**
![clipboard01](https://user-images.githubusercontent.com/131215/53839472-d5239000-3f97-11e9-9748-c00ed3407e0b.jpg)
![clipboard02](https://user-images.githubusercontent.com/131215/53839480-d6ed5380-3f97-11e9-9eca-cd1addd1afe4.jpg)

**Expected behavior**
When I submit address, "optional" must be "*"

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: http://information-dentaire.localhost
Site URL: http://information-dentaire.localhost
WC Version: 3.5.5
Log Directory Writable: ✔
WP Version: ❌ 4.9.9 - There is a newer version of WordPress available (5.1)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.26 (Win32) OpenSSL/1.0.2l PHP/5.6.31
PHP Version: 5.6.31 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 3000
cURL Version: 7.51.0
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.25-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 620.80MB
Database Data Size: 411.18MB
Database Index Size: 209.62MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.11MB + Index: 0.09MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_cf7_vdata: Data: 0.02MB + Index: 0.00MB
wp_cf7_vdata_entry: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.06MB + Index: 0.09MB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB
wp_gf_form: Data: 0.02MB + Index: 0.00MB
wp_gf_form_meta: Data: 0.06MB + Index: 0.00MB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.50MB + Index: 0.08MB
wp_postmeta: Data: 79.61MB + Index: 32.11MB
wp_posts: Data: 65.56MB + Index: 12.09MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.28MB + Index: 0.30MB
wp_term_relationships: Data: 2.52MB + Index: 1.52MB
wp_term_taxonomy: Data: 0.23MB + Index: 0.23MB
wp_usermeta: Data: 137.69MB + Index: 153.42MB
wp_users: Data: 7.52MB + Index: 6.55MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wpml_mails: Data: 3.52MB + Index: 0.00MB
wp_yoast_seo_links: Data: 2.52MB + Index: 0.52MB
wp_yoast_seo_meta: Data: 0.52MB + Index: 0.00MB
_agenda: Data: 0.61MB + Index: 0.02MB
_annonces: Data: 36.56MB + Index: 0.00MB
_annonces_details: Data: 0.29MB + Index: 0.00MB
_articles: Data: 8.04MB + Index: 0.05MB
_articles_extended: Data: 0.53MB + Index: 0.04MB
_cabinet: Data: 3.55MB + Index: 0.01MB
_cabinet_extended: Data: 0.10MB + Index: 0.01MB
_clients: Data: 12.52MB + Index: 1.52MB
_essais: Data: 0.71MB + Index: 0.01MB
_essais_extended: Data: 0.02MB + Index: 0.01MB
_flipbook: Data: 14.98MB + Index: 0.01MB
_formations: Data: 17.40MB + Index: 0.18MB
_formations_extended: Data: 6.48MB + Index: 0.12MB
_list_actu: Data: 0.02MB + Index: 0.00MB
_list_agenda: Data: 0.02MB + Index: 0.00MB
_list_cabinet: Data: 0.02MB + Index: 0.00MB
_list_essais: Data: 0.02MB + Index: 0.00MB
_list_formation: Data: 0.02MB + Index: 0.00MB
_products: Data: 3.52MB + Index: 0.00MB
_products_extended: Data: 1.01MB + Index: 0.02MB
_rubriques: Data: 0.02MB + Index: 0.00MB
_zipcodes: Data: 2.52MB + Index: 0.00MB

### Post Type Counts ###

article: 12502
attachment: 25312
classified: 3534
event: 1659
issue: 1732
nav_menu_item: 20
oembed_cache: 1
page: 19
post: 4567
product: 345
product_variation: 12
revision: 8
scheduled-action: 17
shop_coupon: 2
shop_order: 51
shop_subscription: 3
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (19) ###

Gravity Forms: by rocketgenius – 2.3.6
MahiBasics: by  –
Advanced Custom Fields PRO: by Elliot Condon – 5.7.12
Admin Columns: by AdminColumns.com – 3.4.1
Google Tag Manager for Wordpress: by Thomas Geiger – 1.9.2
Gravity Forms + Custom Post Types: by spivurno – 3.1.13
Gravity Forms Quiz Add-On: by Rocketgenius – 3.1
RSS feeds with images: by Thomas Barthelet – 1.0
ID: by  –
JWT Authentication for WP-API: by Enrique Chavez – 1.2.5
Members: by Justin Tadlock – 2.1.0
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.13
WooCommerce Stripe Gateway: by WooCommerce – 4.1.14
Abonnements WooCommerce: by Prospress Inc. – 2.5.1 – 2.5.2 is available
WooCommerce Table Rate Shipping: by Bolder Elements – 4.1.3 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.5.5
Yoast SEO: by Team Yoast – 9.7
WP Mail Logging: by Christian Zöller – 1.8.5

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #13 - /boutique/
Cart: #40 - /panier/
Checkout: #41 - /commande/
My account: #42 - /mon-compte/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Information Dentaire
Version: V1 – 0 is available
Author URL: https://mahi-mahi.fr
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: id/woocommerce/cart\cart.php
id/woocommerce/checkout\form-login.php
id/woocommerce/checkout\payment-method.php
id/woocommerce/content-single-product.php
id/woocommerce/emails\customer-new-account.php
id/woocommerce/emails\customer-reset-password.php
id/woocommerce/emails\plain\customer-new-account.php
id/woocommerce/emails\plain\customer-reset-password.php
id/woocommerce/single-product\product-image.php

### Mes abonnements à durée libre ###

WCS_DEBUG: ✔ Non
Subscriptions Mode: ❌ Développement (Staging)
Subscriptions Live URL: http://information-dentaire-data.web-staging.com
Subscription Statuses: wc-active: 3
WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Oui
Cache Update Failures: ✔ 0 erreur

### Configuration de la boutique ###

Country / State: France

### Abonnements par plateformes de paiement ###

Stripe: wc-active: 3

### Passerelles de Paiement ###

Check payments: products
Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
pre-orders

</details>

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22948
