### ISSUE TITLE
Stock problem.

### ISSUE THREAD

**Issue by matroidde** [woocommerce/woocommerce#22944]
Hello guys,

I have a big problem with the stock. Everytime I activate the stock for a product and someone buys it the stock is -1. For example: If I create a product and set the stock to 50 products available and buy only one then the product is out of stock and shows -1. I also tried to deactivate any other woocommerce based plugins without success. It would be really nice if someone could help me.

Thanks.

**Comment by kloon** [comment]
I tested this now and unable to replicate, could you please attach your system status report. You mention you tested with plugins disable but this sounds a lot like either some custom code or a plugin causing issues.

Screenshots or a video would also help tremendously showing how you enable stock, set the value and then do a checkout and show the stock issue. Please also test with all plugins disabled except WooCommerce, even ones you rely on, and then also switch your theme to a default one like Twenty Seventeen or Storefront.

**Comment by mikejolley** [comment]
@matroidde We've seen this in the past cause by plugin conflicts, and I recall one being called by a service which updated stock via the REST API. Please rule that out.

To see what you're running we'd need the system status report. Since this issue does not have that and we cannot reproduce I'm making this closed. However, feel free to comment back if you can provide more information and/or steps to reproduce. The new issue form lists things you should do before submitting an issue: https://github.com/woocommerce/woocommerce/issues/new/choose

If you have access to the support desk on woocommerce.com it may also be better to go via there. That way the support staff can log into your site and take a look around to help identify the issue.

Thanks!

**Comment by matroidde** [comment]
Where can I post the system status report? Does this contain critical informations or can I share this for public?

**Comment by mikejolley** [comment]
Here ideally. It shows versions/plugins you're running. Check it if you like before posting.

**Comment by matroidde** [comment]
I think you mean this?

`
### WordPress Environment ###

Home URL: https://www.ilmdarts-open.de
Site URL: https://www.ilmdarts-open.de
WC Version: 3.5.6
Log Directory Writable: ✔
WP Version: 5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.33-0ubuntu0.16.04.2 - Wir empfehlen
PHP Version 7.2 oder höher für mehr Leistung und Sicherheit zu verwenden. So aktualisierst du deine PHP-Version

PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.25-0ubuntu0.16.04.2
Max Upload Size: 5 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Dein Server verfügt nicht über eine lauffähige Version der SoapClient Klasse - einige Zahlungsschnittstellen
welche SOAP nutzen
funktionieren unter Umständen nicht korrekt.

DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.6
WC Database Prefix: 5JpVs_
MaxMind GeoIP Database: ✔
Datenbank-Gesamtgröße: 12.29MB
Datenbank-Datengröße: 10.78MB
Datenbank-Indexgröße: 1.51MB
5JpVs_woocommerce_sessions: Daten: 1.02MB + Index: 0.02MB
5JpVs_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB
5JpVs_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB
5JpVs_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.05MB
5JpVs_woocommerce_order_items: Daten: 0.02MB + Index: 0.02MB
5JpVs_woocommerce_order_itemmeta: Daten: 0.08MB + Index: 0.03MB
5JpVs_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB
5JpVs_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB
5JpVs_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB
5JpVs_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB
5JpVs_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB
5JpVs_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB
5JpVs_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB
5JpVs_woocommerce_log: Daten: 0.02MB + Index: 0.02MB
5JpVs_commentmeta: Daten: 0.02MB + Index: 0.03MB
5JpVs_comments: Daten: 0.08MB + Index: 0.09MB
5JpVs_links: Daten: 0.02MB + Index: 0.02MB
5JpVs_options: Daten: 2.02MB + Index: 0.06MB
5JpVs_postmeta: Daten: 1.50MB + Index: 0.48MB
5JpVs_posts: Daten: 5.41MB + Index: 0.23MB
5JpVs_revslider_css: Daten: 0.13MB + Index: 0.00MB
5JpVs_revslider_layer_animations: Daten: 0.02MB + Index: 0.00MB
5JpVs_revslider_navigations: Daten: 0.02MB + Index: 0.00MB
5JpVs_revslider_sliders: Daten: 0.02MB + Index: 0.00MB
5JpVs_revslider_slides: Daten: 0.02MB + Index: 0.00MB
5JpVs_revslider_static_slides: Daten: 0.02MB + Index: 0.00MB
5JpVs_termmeta: Daten: 0.02MB + Index: 0.03MB
5JpVs_terms: Daten: 0.02MB + Index: 0.03MB
5JpVs_term_relationships: Daten: 0.02MB + Index: 0.02MB
5JpVs_term_taxonomy: Daten: 0.02MB + Index: 0.03MB
5JpVs_usermeta: Daten: 0.02MB + Index: 0.03MB
5JpVs_users: Daten: 0.02MB + Index: 0.05MB
5JpVs_wc_download_log: Daten: 0.02MB + Index: 0.03MB
5JpVs_wc_webhooks: Daten: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 323
customize_changeset: 2
gallery: 9
jetpack_migration: 2
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
lgx_counter: 4
logosliderwp: 6
mc4wp-form: 1
nav_menu_item: 7
page: 69
post: 11
pricing: 11
product: 5
revision: 416
schedule: 4
shop_coupon: 2
shop_order: 68
shop_order_refund: 3
speaker: 15
vc_settings_preset: 2
vcxreview: 3
wpcf7_contact_form: 8

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

Redux Framework: von Team Redux – 3.6.15
Coming Soon Page & Maintenance Mode by SeedProd: von SeedProd – 5.0.24
Contact Form 7: von Takayuki Miyoshi – 5.1.1
Cookie Notice: von dFactory – 1.2.46
Jetpack von WordPress.com: von Automattic – 7.1.1
WPBakery Page Builder: von Michael M - WPBakery.com – 5.6
Logo Slider WP: von LogicHunt – 1.3.4
Mailchimp for WordPress: von ibericode – 4.4
Really Simple SSL: von Rogier Lankhorst
Mark Wolters – 3.1.5

Slider Revolution: von ThemePunch – 5.4.8
Emeet Theme Core: von LogicHunt – 1.4.0
Widget Importer & Exporter: von ChurchThemes.com – 1.5.5
WooCommerce PayPal Checkout Gateway: von WooCommerce – 1.6.10
WooCommerce Services: von Automattic – 1.19.0
WooCommerce TM Extra Product Options: von themeComplete – 4.7.1
WooCommerce: von Automattic – 3.5.6
WP Counter Up: von LogicHunt – 1.2.0
Contact Form 7 Redirection: von Query Solutions – 1.3.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop-Basis: #3753 - /shop/
Warenkorb: #3754 - /warenkorb/
Kasse: #3755 - /kasse/
Mein Konto: #3756 - /mein-konto/
Allgemeine Geschäftsbedingungen: ❌ Seite nicht festgelegt

### Theme ###

Name: Emeet
Version: 1.8.1
Author URL: http://themeforest.net/user/themearth
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: emeet/woocommerce/archive-product.php
/var/www/vhosts/ilmdarts-open.de/httpdocs/wp-content/plugins/woocommerce-tm-extra-product-options/templates/cart/cart-item-data.php
emeet/woocommerce/single-product.php

`

**Comment by LDC22** [comment]
HI, i have the same problem...

**Comment by mikejolley** [comment]
@LDC22 Compare what you have installed to the above system status report. Any simularities?

**Comment by LDC22** [comment]
`
### WordPress Environment ###

Home URL: 
Site URL: 
WC Version: 3.5.4
Log Directory Writable: ✔
WP Version: ❌ 4.9.9 - È disponibile una versione più recente di WordPress (5.1)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache/2
PHP Version: 7.2.15
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.36

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.13-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Dimensione totale database: 7.69MB
Dimensione dati database: 6.70MB
Dimensione indice database: 0.99MB
wp_woocommerce_sessions: Dati: 0.04MB + Indice: 0.00MB
wp_woocommerce_api_keys: Dati: 0.00MB + Indice: 0.00MB
wp_woocommerce_attribute_taxonomies: Dati: 0.00MB + Indice: 0.00MB
wp_woocommerce_downloadable_product_permissions: Dati: 0.00MB + Indice: 0.00MB
wp_woocommerce_order_items: Dati: 0.00MB + Indice: 0.00MB
wp_woocommerce_order_itemmeta: Dati: 0.02MB + Indice: 0.02MB
wp_woocommerce_tax_rates: Dati: 0.00MB + Indice: 0.01MB
wp_woocommerce_tax_rate_locations: Dati: 0.00MB + Indice: 0.00MB
wp_woocommerce_shipping_zones: Dati: 0.00MB + Indice: 0.00MB
wp_woocommerce_shipping_zone_locations: Dati: 0.00MB + Indice: 0.00MB
wp_woocommerce_shipping_zone_methods: Dati: 0.00MB + Indice: 0.00MB
wp_woocommerce_payment_tokens: Dati: 0.00MB + Indice: 0.00MB
wp_woocommerce_payment_tokenmeta: Dati: 0.00MB + Indice: 0.00MB
wp_woocommerce_log: Dati: 0.00MB + Indice: 0.00MB
wp_akeeba_common: Dati: 0.00MB + Indice: 0.01MB
wp_ak_params: Dati: 0.00MB + Indice: 0.01MB
wp_ak_profiles: Dati: 0.00MB + Indice: 0.00MB
wp_ak_stats: Dati: 0.00MB + Indice: 0.00MB
wp_ak_storage: Dati: 0.00MB + Indice: 0.01MB
wp_ak_users: Dati: 0.00MB + Indice: 0.00MB
wp_commentmeta: Dati: 0.00MB + Indice: 0.01MB
wp_comments: Dati: 0.02MB + Indice: 0.01MB
wp_layerslider: Dati: 0.08MB + Indice: 0.00MB
wp_layerslider_revisions: Dati: 0.00MB + Indice: 0.00MB
wp_links: Dati: 0.00MB + Indice: 0.00MB
wp_mailpoet_custom_fields: Dati: 0.00MB + Indice: 0.00MB
wp_mailpoet_forms: Dati: 0.00MB + Indice: 0.00MB
wp_mailpoet_log: Dati: 0.00MB + Indice: 0.00MB
wp_mailpoet_mapping_to_external_entities: Dati: 0.00MB + Indice: 0.00MB
wp_mailpoet_newsletters: Dati: 0.00MB + Indice: 0.00MB
wp_mailpoet_newsletter_links: Dati: 0.00MB + Indice: 0.00MB
wp_mailpoet_newsletter_option: Dati: 0.00MB + Indice: 0.00MB
wp_mailpoet_newsletter_option_fields: Dati: 0.00MB + Indice: 0.01MB
wp_mailpoet_newsletter_posts: Dati: 0.00MB + Indice: 0.00MB
wp_mailpoet_newsletter_segment: Dati: 0.00MB + Indice: 0.00MB
wp_mailpoet_newsletter_templates: Dati: 0.58MB + Indice: 0.00MB
wp_mailpoet_scheduled_tasks: Dati: 0.00MB + Indice: 0.01MB
wp_mailpoet_scheduled_task_subscribers: Dati: 0.00MB + Indice: 0.00MB
wp_mailpoet_segments: Dati: 0.00MB + Indice: 0.00MB
wp_mailpoet_sending_queues: Dati: 0.00MB + Indice: 0.00MB
wp_mailpoet_settings: Dati: 0.00MB + Indice: 0.00MB
wp_mailpoet_statistics_clicks: Dati: 0.00MB + Indice: 0.00MB
wp_mailpoet_statistics_forms: Dati: 0.00MB + Indice: 0.00MB
wp_mailpoet_statistics_newsletters: Dati: 0.00MB + Indice: 0.00MB
wp_mailpoet_statistics_opens: Dati: 0.00MB + Indice: 0.00MB
wp_mailpoet_statistics_unsubscribes: Dati: 0.00MB + Indice: 0.00MB
wp_mailpoet_stats_notifications: Dati: 0.00MB + Indice: 0.00MB
wp_mailpoet_subscribers: Dati: 0.00MB + Indice: 0.01MB
wp_mailpoet_subscriber_custom_field: Dati: 0.00MB + Indice: 0.00MB
wp_mailpoet_subscriber_ips: Dati: 0.00MB + Indice: 0.00MB
wp_mailpoet_subscriber_segment: Dati: 0.00MB + Indice: 0.00MB
wp_options: Dati: 1.73MB + Indice: 0.05MB
wp_postmeta: Dati: 1.17MB + Indice: 0.61MB
wp_posts: Dati: 2.63MB + Indice: 0.11MB
wp_revslider_css: Dati: 0.09MB + Indice: 0.00MB
wp_revslider_layer_animations: Dati: 0.00MB + Indice: 0.00MB
wp_revslider_navigations: Dati: 0.00MB + Indice: 0.00MB
wp_revslider_sliders: Dati: 0.03MB + Indice: 0.00MB
wp_revslider_slides: Dati: 0.16MB + Indice: 0.00MB
wp_revslider_static_slides: Dati: 0.00MB + Indice: 0.00MB
wp_rg_form: Dati: 0.00MB + Indice: 0.00MB
wp_rg_form_meta: Dati: 0.02MB + Indice: 0.00MB
wp_rg_form_view: Dati: 0.01MB + Indice: 0.00MB
wp_rg_incomplete_submissions: Dati: 0.00MB + Indice: 0.00MB
wp_rg_lead: Dati: 0.00MB + Indice: 0.00MB
wp_rg_lead_detail: Dati: 0.01MB + Indice: 0.01MB
wp_rg_lead_detail_long: Dati: 0.00MB + Indice: 0.00MB
wp_rg_lead_notes: Dati: 0.00MB + Indice: 0.00MB
wp_termmeta: Dati: 0.00MB + Indice: 0.01MB
wp_terms: Dati: 0.00MB + Indice: 0.01MB
wp_term_relationships: Dati: 0.00MB + Indice: 0.01MB
wp_term_taxonomy: Dati: 0.00MB + Indice: 0.01MB
wp_usermeta: Dati: 0.03MB + Indice: 0.02MB
wp_users: Dati: 0.00MB + Indice: 0.01MB
wp_wcpdf_invoice_number: Dati: 0.02MB + Indice: 0.00MB
wp_wc_download_log: Dati: 0.00MB + Indice: 0.00MB
wp_wc_webhooks: Dati: 0.00MB + Indice: 0.00MB
wp_yoast_seo_links: Dati: 0.05MB + Indice: 0.02MB
wp_yoast_seo_meta: Dati: 0.01MB + Indice: 0.01MB

### Post Type Counts ###

attachment: 108
cmsmasters_cform: 41
cmsmasters_like: 129
content_template: 21
customize_changeset: 7
event-schedule: 6
mailpoet_page: 1
nav_menu_item: 45
oembed_cache: 3
page: 25
post: 11
product: 12
profile: 21
project: 16
revision: 320
shop_order: 35
tribe_events: 1
tribe_organizer: 1
tribe_venue: 1
wpcf7_contact_form: 9

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (41) ###

WP Hide & Security Enhancer: by Nsp Code – 1.5.5
Gravity Forms: by rocketgenius – 1.9.6
Redux Framework: by Team Redux – 3.6.15
LayerSlider WP: by Kreatura Media – 6.7.6
Akeeba Backup for WordPress: by Akeeba Ltd – 3.3.3.1
Autocomplete WooCommerce Orders: by Liam McArthur – 1.1.0
CMSMasters Contact Form Builder: by cmsmasters – 1.4.0
CMSMasters Content Composer: by cmsmasters – 1.7.4
CMSMasters Events Schedule: by cmsmasters – 1.0.0
CMSMasters Importer: by cmsmasters – 1.0.3
CMSMasters Mega Menu: by cmsmasters – 1.2.7
Contact Form 7: by Takayuki Miyoshi – 5.1.1
Passster: by patrickposner – 3.1.9.1
Disable Gutenberg: by Jeff Starr – 1.5.2
Disable All WordPress Updates: by Oliver Schlöbe – 1.6.3
Duplicate Post: by Enrico Battocchi – 3.2.2
Email Text Customizer for WooCommerce: by EnigmaWeb – 1.0.3 – Non testato con la versione attiva di WooCommerce
Envato Market: by Envato – 2.0.1
Flexible Checkout Fields PRO: by WP Desk – 1.9.0
Flexible Checkout Fields: by WP Desk – 1.8.3
GA Google Analytics: by Jeff Starr – 20190220
Instagram Feed: by Smash Balloon – 1.10.2
Invisible reCaptcha: by Mihai Chelaru – 1.2.1
Limit Login Attempts Reloaded: by wpchefgadget – 2.7.1
Tradurre con Loco: by Tim Whitlock – 2.2.0
MailPoet 3 (nuovo): by MailPoet – 3.18.2
Manutenzione: by fruitfulcode – 3.6.1
Really Simple SSL: by Rogier Lankhorst
Mark Wolters – 3.1.3

Revolution Slider: by ThemePunch – 5.4.8.1
Snazzy Maps: by Atmist – 1.1.5
SVG Support: by Benbodhi – 2.3.15
The Events Calendar: by Modern Tribe
Inc. – 4.7.4

Countdown Wpdevart: by wpdevart – 2.0.2
Woocommerce Minimum and Maximum Quantity: by Ashok G – 2.0.3 – Non testato con la versione attiva di WooCommerce
WooCommerce One Page Checkout: by Prospress Inc. – 1.5.5 – 1.6.0 è disponibile – Non testato con la versione attiva di WooCommerce
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.2.7
WooCommerce: by Automattic – 3.5.4
WordPress GDPR: by DB-Dzine – 1.7.2
Yoast SEO: by Team Yoast – 9.5
WP Add Custom CSS: by Daniele De Santis – 1.1.4
WP Desk Helper: by WP Desk – 1.6.5

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Shop base: ❌ La pagina non è impostata
Carrello: ❌ La pagina non è impostata
Cassa: ❌ La pagina non è impostata
Il mio account: ❌ La pagina non è impostata
Termini e condizioni: ❌ La pagina non è impostata

### Theme ###

Name: In Conference Child
Version: 1.0.0
Author URL: http://cmsmasters.net/
Child Theme: ✔
Parent Theme Name: In Conference
Parent Theme Version: 1.1.4
Parent Theme Author URL: http://cmsmasters.net/
WooCommerce Support: ✔

### Templates ###

Overrides: in-conference/woocommerce/archive-product.php
in-conference/woocommerce/content-product.php
in-conference/woocommerce/content-single-product.php
in-conference/woocommerce/content-widget-product.php
in-conference-child/woocommerce/emails/admin-cancelled-order.php versione 2.5.0 è obsoleta. La versione attuale è 3.5.0
in-conference-child/woocommerce/emails/admin-failed-order.php versione 2.5.0 è obsoleta. La versione attuale è 3.5.0
in-conference-child/woocommerce/emails/admin-new-order.php versione 2.5.0 è obsoleta. La versione attuale è 3.5.0
in-conference-child/woocommerce/emails/customer-completed-order.php versione 2.5.0 è obsoleta. La versione attuale è 3.5.0
in-conference-child/woocommerce/emails/customer-invoice.php versione 2.5.0 è obsoleta. La versione attuale è 3.5.0
in-conference-child/woocommerce/emails/customer-new-account.php versione 1.6.4 è obsoleta. La versione attuale è 3.5.2
in-conference-child/woocommerce/emails/customer-note.php versione 2.5.0 è obsoleta. La versione attuale è 3.5.0
in-conference-child/woocommerce/emails/customer-on-hold-order.php versione 2.5.0 è obsoleta. La versione attuale è 3.5.0
in-conference-child/woocommerce/emails/customer-processing-order.php versione 2.5.0 è obsoleta. La versione attuale è 3.5.4
in-conference-child/woocommerce/emails/customer-refunded-order.php versione 2.5.0 è obsoleta. La versione attuale è 3.5.0
in-conference-child/woocommerce/emails/customer-reset-password.php versione 2.0.0 è obsoleta. La versione attuale è 3.5.0
in-conference-child/woocommerce/emails/email-addresses.php versione 2.4.0 è obsoleta. La versione attuale è 3.5.4
in-conference-child/woocommerce/emails/email-customer-details.php
in-conference-child/woocommerce/emails/email-footer.php
in-conference-child/woocommerce/emails/email-header.php
in-conference-child/woocommerce/emails/email-order-details.php versione 2.5.0 è obsoleta. La versione attuale è 3.3.1
in-conference-child/woocommerce/emails/email-order-items.php versione 2.1.2 è obsoleta. La versione attuale è 3.5.0
in-conference-child/woocommerce/emails/email-styles.php versione 2.3.0 è obsoleta. La versione attuale è 3.3.0
in-conference/woocommerce/global/sidebar.php
in-conference/woocommerce/global/wrapper-end.php
in-conference/woocommerce/global/wrapper-start.php
in-conference/woocommerce/loop/loop-start.php
in-conference/woocommerce/loop/pagination.php
in-conference/woocommerce/product-searchform.php
in-conference/woocommerce/single-product/meta.php
in-conference/woocommerce/single-product/product-image.php
in-conference/woocommerce/single-product/product-thumbnails.php
in-conference/woocommerce/single-product/review.php
in-conference/woocommerce/single-product/tabs/tabs.php
in-conference/woocommerce/single-product-reviews.php
in-conference/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Scopri come aggiornare
`

**Comment by mikejolley** [comment]
I see some simularities e.g. Redux Framework.

Can you do a test with only WC active and try to replicate the plugin? I'm pretty certain it will be a conflict with something you have active.
