### ISSUE TITLE
When Adding a Product there is a Submit for Review button instead of Publish

### ISSUE THREAD

**Issue by EliBec** [woocommerce/woocommerce#22956]
The Publish button used to be available, but it is not longer there
I am logged in as an "admin" user. No permissions have been changed

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Attempt to add a new product. Notice the page shows "Submit for Review" instead of "Publish" 

## Expected/actual behavior

When I follow those steps, I see"Submit for Review". Also, the categories used to show on the right-hand side (see attached) 

I was expecting to see "Publish" button, as well as the categories to choose from on the right-hand side (see attached) 

## Isolating the problem

- [x ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above
![screen shot with publish button - staging environment](https://user-images.githubusercontent.com/38743802/53929281-3b251b80-405b-11e9-9c00-322d3fd6b411.png)
![screen shot with sumit for review button - production environment](https://user-images.githubusercontent.com/38743802/53929282-3b251b80-405b-11e9-8317-0268448c9889.png)

Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
`
### WordPress Environment ###

Home URL: https://leadertechinc.com
Site URL: https://leadertechinc.com
WC Version: 3.5.5
Log Directory Writable: ✔
WP Version: 5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.2.29 (Unix) mod_ssl/2.2.29 OpenSSL/1.0.1e-fips mod_bwlimited/1.4
PHP Version: 5.4.33 - ❌ WooCommerce will run under this version of PHP
however
it has reached end of life. We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version

PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.38.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.61-cll - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ❌ Your server does not support the mbstring functions - this is required for better character encoding. Some fallbacks will be used instead for it.
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.7
WC Database Prefix: lt_
MaxMind GeoIP Database: ✔
Total Database Size: 41.43MB
Database Data Size: 31.35MB
Database Index Size: 10.08MB
lt_woocommerce_sessions: Data: 0.15MB + Index: 0.00MB
lt_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
lt_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
lt_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
lt_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
lt_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
lt_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
lt_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
lt_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
lt_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
lt_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
lt_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
lt_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
lt_woocommerce_log: Data: 0.00MB + Index: 0.00MB
lt_blog_commentmeta: Data: 0.00MB + Index: 0.01MB
lt_blog_comments: Data: 0.04MB + Index: 0.02MB
lt_blog_links: Data: 0.00MB + Index: 0.00MB
lt_blog_mts_wp_reviews: Data: 0.00MB + Index: 0.00MB
lt_blog_options: Data: 0.11MB + Index: 0.04MB
lt_blog_postmeta: Data: 1.28MB + Index: 0.45MB
lt_blog_posts: Data: 3.63MB + Index: 0.09MB
lt_blog_termmeta: Data: 0.00MB + Index: 0.01MB
lt_blog_terms: Data: 0.01MB + Index: 0.03MB
lt_blog_term_relationships: Data: 0.01MB + Index: 0.03MB
lt_blog_term_taxonomy: Data: 0.01MB + Index: 0.02MB
lt_blog_usermeta: Data: 0.01MB + Index: 0.01MB
lt_blog_users: Data: 0.00MB + Index: 0.01MB
lt_blog_wc_download_log: Data: 0.00MB + Index: 0.00MB
lt_blog_wc_webhooks: Data: 0.00MB + Index: 0.00MB
lt_blog_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
lt_blog_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
lt_blog_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
lt_blog_woocommerce_log: Data: 0.00MB + Index: 0.00MB
lt_blog_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
lt_blog_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
lt_blog_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
lt_blog_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
lt_blog_woocommerce_sessions: Data: 0.03MB + Index: 0.00MB
lt_blog_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
lt_blog_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
lt_blog_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
lt_blog_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
lt_blog_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
lt_blog_yith_wcwl: Data: 0.00MB + Index: 0.00MB
lt_blog_yith_wcwl_lists: Data: 0.00MB + Index: 0.01MB
lt_blog_yoast_seo_links: Data: 0.01MB + Index: 0.00MB
lt_blog_yoast_seo_meta: Data: 0.00MB + Index: 0.00MB
lt_commentmeta: Data: 0.00MB + Index: 0.00MB
lt_comments: Data: 0.00MB + Index: 0.00MB
lt_links: Data: 0.00MB + Index: 0.00MB
lt_metaseo_images: Data: 0.02MB + Index: 0.00MB
lt_options: Data: 1.30MB + Index: 0.05MB
lt_postmeta: Data: 14.14MB + Index: 5.90MB
lt_posts: Data: 2.18MB + Index: 0.87MB
lt_smush_dir_images: Data: 0.00MB + Index: 0.00MB
lt_swp_cf: Data: 0.00MB + Index: 0.00MB
lt_swp_index: Data: 1.02MB + Index: 0.72MB
lt_swp_log: Data: 0.06MB + Index: 0.06MB
lt_swp_tax: Data: 0.00MB + Index: 0.00MB
lt_swp_terms: Data: 0.17MB + Index: 0.20MB
lt_termmeta: Data: 0.84MB + Index: 0.51MB
lt_terms: Data: 0.33MB + Index: 0.29MB
lt_term_relationships: Data: 0.17MB + Index: 0.38MB
lt_term_taxonomy: Data: 0.32MB + Index: 0.31MB
lt_toolset_post_guid_id: Data: 0.00MB + Index: 0.01MB
lt_usermeta: Data: 0.02MB + Index: 0.02MB
lt_users: Data: 0.00MB + Index: 0.01MB
lt_wc_download_log: Data: 0.00MB + Index: 0.00MB
lt_wc_webhooks: Data: 0.00MB + Index: 0.00MB
lt_wfblockediplog: Data: 0.02MB + Index: 0.01MB
lt_wfblocks7: Data: 0.00MB + Index: 0.00MB
lt_wfconfig: Data: 0.75MB + Index: 0.00MB
lt_wfcrawlers: Data: 0.00MB + Index: 0.00MB
lt_wffilechanges: Data: 0.00MB + Index: 0.00MB
lt_wffilemods: Data: 1.46MB + Index: 0.00MB
lt_wfhits: Data: 2.29MB + Index: 0.00MB
lt_wfhoover: Data: 0.00MB + Index: 0.00MB
lt_wfissues: Data: 0.01MB + Index: 0.00MB
lt_wfknownfilelist: Data: 0.75MB + Index: 0.00MB
lt_wflivetraffichuman: Data: 0.00MB + Index: 0.00MB
lt_wflocs: Data: 0.01MB + Index: 0.00MB
lt_wflogins: Data: 0.09MB + Index: 0.00MB
lt_wfnotifications: Data: 0.00MB + Index: 0.00MB
lt_wfpendingissues: Data: 0.00MB + Index: 0.00MB
lt_wfreversecache: Data: 0.00MB + Index: 0.00MB
lt_wfsnipcache: Data: 0.00MB + Index: 0.00MB
lt_wfstatus: Data: 0.08MB + Index: 0.00MB
lt_wftrafficrates: Data: 0.00MB + Index: 0.00MB
lt_wpms_links: Data: 0.00MB + Index: 0.00MB
lt_wysija_campaign: Data: 0.00MB + Index: 0.00MB
lt_wysija_campaign_list: Data: 0.00MB + Index: 0.00MB
lt_wysija_custom_field: Data: 0.00MB + Index: 0.00MB
lt_wysija_email: Data: 0.03MB + Index: 0.00MB
lt_wysija_email_user_stat: Data: 0.00MB + Index: 0.00MB
lt_wysija_email_user_url: Data: 0.00MB + Index: 0.00MB
lt_wysija_form: Data: 0.00MB + Index: 0.00MB
lt_wysija_list: Data: 0.00MB + Index: 0.00MB
lt_wysija_queue: Data: 0.00MB + Index: 0.00MB
lt_wysija_subscriber_ips: Data: 0.00MB + Index: 0.00MB
lt_wysija_url: Data: 0.00MB + Index: 0.00MB
lt_wysija_url_mail: Data: 0.00MB + Index: 0.00MB
lt_wysija_user: Data: 0.00MB + Index: 0.00MB
lt_wysija_user_field: Data: 0.00MB + Index: 0.00MB
lt_wysija_user_history: Data: 0.00MB + Index: 0.00MB
lt_wysija_user_list: Data: 0.00MB + Index: 0.00MB
lt_yoast_seo_links: Data: 0.00MB + Index: 0.00MB
lt_yoast_seo_meta: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

acf: 4
acf-field: 12
acf-field-group: 4
amn_smtp: 1
attachment: 1874
catalog: 58
cbs-pn-builder: 1
distributors: 7
engineers-desk: 1
envira: 1
home-page-slider: 4
nav_menu_item: 20
news: 50
nl-subscriber: 8267
our-career: 3
our-sales-team: 75
page: 27
post: 1
postman_sent_mail: 2
product: 89
revision: 208
scroll-triggered-box: 2
spucpt: 3
team: 4
technical-document: 19
videos: 5
wp-types-group: 3
wpcf7_contact_form: 4
wysijap: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

Add HTML Extension to Specific Pages: by CherryAnt.com – 1.0
Advanced Custom Fields: by Elliot Condon – 5.7.12
Categories Images: by Muhammad Said El Zahlan – 2.5.4
Classic Editor: by WordPress Contributors – 1.4
Contact Form 7: by Takayuki Miyoshi – 5.0.5
CSV Importer Improved: by Jason judge
Denis Kobozev – 0.6.1

Envira Gallery Lite: by Envira Gallery Team – 1.6.4
Head, Footer and Post Injections: by Stefano Lissa – 3.1.2
Popups - WordPress Popup: by timersys – 1.9.3.4
Post Types Order: by Nsp Code – 1.9.3.9
Recent Tweets Widget: by Noah Kagan – 1.6.8
SearchWP Live Ajax Search: by Jonathan Christopher – 1.3.1
Secure Folder wp-content/uploads: by Daniel Satria a/n RuangLaba – 1.2
Toolset Types: by OnTheGoSystems – 2.3.5
Upload Images: by AB – 1.1
W3 Total Cache: by Frederick Townes – 0.9.7.2
WooCommerce: by Automattic – 3.5.5
Wordfence Security: by Wordfence – 7.2.3
Yoast SEO: by Team Yoast – 3.1.2
Interactive 2 Level World Map: by Fla-shop.com – 2.0.2
WP Mail SMTP: by WPForms – 1.4.1
WP-PageNavi: by Lester 'GaMerZ' Chan – 2.93
Smush: by WPMU DEV – 3.1.1
Contact Form 7 Redirection: by Query Solutions – 1.3.1
MailPoet 2: by MailPoet – 2.11

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: leadertech
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: leadertech/single-product.php version - is out of date. The core version is 1.6.4
Outdated Templates: ❌
					
					
						Learn how to update
`

**Comment by mikejolley** [comment]
I'm not experiencing this:

![add new product test wordpress 2019-03-08 11-47-54](https://user-images.githubusercontent.com/90977/54027068-0ec2e980-4198-11e9-8f51-62d5ce474d05.png)

I see you checked:

> This bug happens with only WooCommerce plugin active

However, it's clear from your screenshots many other plugins are active. Some of them appear like they could change permissions - submit for review is shown when users don't have publish permissions. 

Have you perhaps overwritten the WooCommerce product type with a custom type e.g. via https://en-gb.wordpress.org/plugins/types/? I see thats installed.

Please rule out a conflict with a custom post type, and rule out conflicts with other installed plugins before raising issues here.

As this is not something I can reproduce and has not been reported by anyone else, I'm closing it. But please comment back if you find it happens with ONLY woocommerce active or you can reproduce the issue on another install and share those steps.

Thanks
