### ISSUE TITLE
Admin cancelled order incorrect message: woocommerce/templates/emails/admin-cancelled-order.php

### ISSUE THREAD

**Issue by beags121** [woocommerce/woocommerce#22958]
**Describe the bug**
If admin cancels an order the email received by admin (woocommerce/templates/emails/admin-cancelled-order.php) states: "Alas. Just to let you know — [customer-name] has cancelled order [#order-number]:"

This is surely wrong - shouldn't be the customer that has cancelled. Also not sure about the 'Alas.' line?

**To Reproduce**
1. Go to an order (logged in as admin)
2. Click on dropdown and change to order cancelled > click update
3. Admin(s) receive email
4. See erroneous copy

**Expected behavior**
Should say similar: "The order [#order-number] from [customer-name] has been cancelled. The order was as follows:"

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22971
