### ISSUE TITLE
SMTP and Reply-to

### ISSUE THREAD

**Issue by dualaudi** [woocommerce/woocommerce#22952]
**Problem: using smtp plugins
The From: address will always be the smtp email. Many sites will use SMTP plugins to ensure emails are sent successfully.  Problem is there is no Reply-To: option in settings from woocommerce > settings > email > manage

**Solution **
Under manage for each notification email, there should be "reply-to:" email that gets passed to the headers of the email being sent. Gravity forms does this just fine regardless of SMTP plugins.

**Describe alternatives you've considered**
Can't seem to find a working function php script to force my own reply-to:
![reply-to-option](https://user-images.githubusercontent.com/17436208/53907098-4f3c2f00-4001-11e9-9719-a88b417c0642.jpg)
 email.

**Additional context**
I don't think the previous commits addressed this properly.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/22979
