### ISSUE TITLE
Cannot display Variation PURCHASE NOTE

### ISSUE THREAD

**Issue by AKSUTAH** [woocommerce/woocommerce#22964]
**The bug**
Whenever trying to display the variation "purchase_note" I get nothing, just a blank.
If the variations parent has a purchase note set, I will get that instead.

How can I display the individual variations purchase_note instead of the parents?

**To Reproduce**
'purchase_note':
 $html .= esc_html( $product_object->get_purchase_note() );
 break;

**Expected behavior**
I hope to display the variation purchase note on a custom packing slip.

**Problem Area**
It looks like this overrides the ability to show variation purchase notes and instead shows parents... How do I circumvent this?

  public function get_purchase_note( $context = 'view' ) {
    $value = $this->get_prop( 'purchase_note', $context );

    // Inherit value from parent.
    if ( 'view' === $context && empty( $value ) ) {
      $value = apply_filters( $this->get_hook_prefix() . 'purchase_note', $this->parent_data['purchase_note'], $this );
    }
    return $value;
  }

**Comment by kloon** [comment]
Purchase notes are not settable on a variation level, but only on the parent variable product.

![Parent Variable Product](https://cld.wthms.co/ckDN2x+)

![Variation Product - Note there is no purchase note field](https://cld.wthms.co/Dsc9rs+)

If you want purchase notes on a variation level you will have to do custom development as that is not standard WooCommerce functionality.

**Comment by maydaohio** [comment]
Any progress on this as a feature request?
