### ISSUE TITLE
Media Library - Bulk delete broken

### ISSUE THREAD

**Issue by 1tan1** [woocommerce/woocommerce#22960]
**Describe the bug**
With Wordpress 5.1, if you use WooCommerce it breaks Media Library. Try selecting bulk images to delete and press delete. It won't delete/update. You have to refresh and it disappears.

**Comment by mikejolley** [comment]
I'm unable to replicate this. I'm able to delete and there are no errors on the console.

This is perhaps a conflict with an extension you're running (some extensions do not load unless WooCommerce is active).

Check the JS console for errors in your browser. In chrome, View > Developer > Javascript console, then attempt a delete.

That will tell you which script is causing the issue and allow you to narrow it down to a specific extension. Feel free to comment back if you find anything. I'm closing this for now as I'm unable to replacate an issue.

Thanks
