### ISSUE TITLE
reduce stock by weight

### ISSUE THREAD

**Issue by mojtaban12** [woocommerce/woocommerce#22961]
hi guys
is it possible to reduce stock by weight ! instead of decreasing it by number.
i have an product with 100kg weight. and i want to sell it in 10kg packages. when customer bought an pakckage, stock updated to 90kg.
thanks a lot

**Comment by mikejolley** [comment]
This isn't something we currently support. 

Not sure if https://woocommerce.com/products/measurement-price-calculator/ can do it. Also found this on google but untested https://stepqueue.com/plugins/woocommerce-weight-based-inventory/

One of those should hopefully help as this is extension territory :)
