### ISSUE TITLE
Performance issue for Geolite DB access when using a remote database file

### ISSUE THREAD

**Issue by tristanbes** [woocommerce/woocommerce#22976]
**Describe the bug**
On each requests, WooCommerce loads multiple times the GeoliteDB, which might sound not a problem when the file is stored on a local storage but as soon as you use a remote (cloud) storage system such as Amazon S3, it becomes a HUGE bottleneck for performances.

Right now, it takes 322ms just by fetching this `GeoLite2-Country.mmdb` and it's called 2 times.

**Screenshots**
![wordpress_spalina_ok_profile_-_blackfire](https://user-images.githubusercontent.com/346010/54035019-a0daea00-41b8-11e9-85c9-913325d3f774.png)

**Expected behavior**
We would want a way to add a custom local path to load the database without relying to the upload folder path, which on our case is `s3://xxxx`

For example, the front controller is located in `web/index.php` (we use [Bedrock](https://roots.io/bedrock/) structure).
Then, we should be able to define the path `web/GeoLite2-Country.mmdb` so it loads this file from there.

**Isolating the problem:**
[Link to BlackFire trace to see the problem with real benchmarks ](https://blackfire.io/profiles/145e2db1-275c-429a-bf6d-b48046f5bf6b/graph?settings%5Bdimension%5D=wt&settings%5Bdisplay%5D=focused&settings%5BtabPane%5D=nodes&selected=WC_Geolocation%3A%3Ageolocate_ip&callname=WC_Geolocation%3A%3Ageolocate_ip)

**WordPress Environment**
<details>
Woocommerce 3.5.5
WordPress 3.5
PHP 7.3.x
</details>

Thanks

**Comment by mikejolley** [comment]
Since we cannot force your s3 plugin to use the local version, you can use a filter. Have you seen `woocommerce_geolocation_local_database_path`?

**Comment by tristanbes** [comment]
nope, do you have an example to give for its usage please ?

Also side note but, without a local path, i'm 95% sure that WooCommerce won't be able to upload updates for the `GeoLite2-Country.mmdb` files, am I correct ?

**Comment by mikejolley** [comment]
Thats probably true; we use `wp_upload_dir` and manipulate files in those directories. If the s3 plugin changes this it might break it.

Filter is here https://github.com/woocommerce/woocommerce/blob/0d901a2ecadc7ea52aa4a875d511d5097d50cbed/includes/class-wc-geolocation.php#L242

```
add_filter( 'woocommerce_geolocation_local_database_path', 'custom_woocommerce_geolocation_local_database_path' );

function custom_woocommerce_geolocation_local_database_path() {
  return '/new/path/here/GeoLite2-Country.mmdb';
}
```

**Comment by tristanbes** [comment]
Thanks for this example ! 

Also, just for people who are using a remote storage system which is more and more common, wouldn't it be better to use a compliant way to upload the file instead of manipulating `wp_upload_dir` ? I don't think most of them will think of the performance issues.

I'm asking this because all our uploads goes to s3 and we didn't add filters for this, just add https://github.com/humanmade/S3-Uploads. My point here is that this plugin hooks into the upload system to redirect uploads to S3, so why it's not working for WooCommerce ?

I'm sorry if that sounds stupid, i'm not a WP developper/user so maybe i'm not using the correct terms. :-)

**Comment by mikejolley** [comment]
The issue is we need to unzip that database. I'll check it with that plugin later. If you have an mmdb file maybe it is indeed working.

**Comment by tristanbes** [comment]
ok, and with a custom path with a filter like the example, will it solve the problem of auto-updating the db ? or it won't auto-update it since it's not in a standard path ?

**Comment by mikejolley** [comment]
That filter I provided is just a way for you to tell it to load from the local version vs s3.

**Comment by tristanbes** [comment]
ok, so just to be clear, we're responsible for updating it (which we won't do but I guess it's ok 🤷‍♂️)

So there's room for improvements to support:

-> updating the DB on a remote storage system in an automatic way
-> updating the DB on a local storage but with an overriden path using a filter

Thanks for your help

**Comment by mikejolley** [comment]
Made some tweaks in https://github.com/woocommerce/woocommerce/pull/22981 - if you could test that out and confirm it bypasses s3 extension that would be great. Please comment on the PR going forward.

Thanks
