### ISSUE TITLE
woocommerce_cancel_unpaid_orders cron job not displaying

### ISSUE THREAD

**Issue by Lippiun** [woocommerce/woocommerce#22975]
The pending payments on my Woocommerce website aren't being changed to cancelled and instead are staying at pending. Apparently, there should be a cron job called woocommerce_cancel_unpaid_orders which goes through and cancels any pending orders.

I've installed a cron manager plugin to see if this is running and can't see it anywhere. Other Woocommerce cron events are scheduled such as:

woocommerce_cleanup_personal_data

woocommerce_cleanup_logs

woocommerce_scheduled_sales

woocommerce_cleanup_logs

woocommerce_geoip_updater

I'm running the latest version of Woocommerce 3.5.6. Does anyone know why this isn't running?

I've checked other Woocommerce websites on the same hosting to see if it's a problem with the server and it i can see if working on these. Could it be that a plugin has deleted it? If so, how do I add this back?

**Comment by mikejolley** [comment]
Go to `WooCommerce > Settings > Products > Inventory` and set `Hold stock (minutes)` to an integer. The default is 60.

Without this, the cron job won't exist.

In case you've removed the cron job somehow, you can get it back by de-activating and re-activating WooCommerce, or changing the value of the above options so it's recreated.

Hope that helps.

**Comment by Lippiun** [comment]
Hi Mike, 

Changing the value in the Hold Stock field worked thank you!

**Comment by SirRahikkala** [comment]
I will chime in that the "woocommerce_cancel_unpaid_orders" disappears occasionally and I cannot find reason why since we notice it way too long after. Setting the inventory time does recover it.
