### ISSUE TITLE
Implementing Custom Product Tables for Woo 4.0

### ISSUE THREAD

**Issue by tonybahama** [woocommerce/woocommerce#22985]
Hi!

Do you consider implementing the Product Tables Feature plugin for WooCommerce 4.0 @mikejolley ?

I has long been in development. I noticed you guys are implementing many performance implementations but some are redundant if the feature plugin would get finished and shipped instead.

**Comment by edohartono** [comment]
Hi @tonybahama 
I think existing wordpress table plugins is good to implement with woocommerce

**Comment by tonybahama** [comment]
Technically, yes. From scalability standpoint: no, it is not. That is why this project started which is AWESOME: https://github.com/woocommerce/woocommerce-product-tables-feature-plugin

My question is when does it get merged to Core.

**Comment by kloon** [comment]
@tonybahama Custom Product tables is a large undertaking and as such we cannot say when it will form part of core, there are still a lot of testing that needs to be done as well as development itteration based on feedback. You have it right that it needs to go into a major release as it is a potentially breaking change, which the earliest is 4.0, but it could also be 5.0 or even 6.0.

We have opted to also explore other alternatives we can implement now and in other minor releases that will not cause issues for existing store owners or have compatibility issues with extension or themes, a lot of those will ship with 3.6 and we will continue to explore more improvements with other minor releases.

We still welcome feedback and testing on the custom product tables feature plugin as that will likely make it into core in the future, but as it stands now our main priority is fixing performance issues in WooCommerce core where we can by evaluating existing queries and improving them, implementing the correct indexes on WooCommerce core tables and making use of lookup tables for querying data.

The performance gains alone we have seen on these changes is quite significant so will benefit all stores in a minor release.

I also want to make it clear that we welcome feedback from stores that are experiencing some sort of performance issue, please get in touch with our support team and we can open up communication and look at what is causing these issues. Each store is unique and as such, it is difficult to always find bottlenecks so we would like to work with stores experiencing issues so we can further see where we can improve performance in an easy backward compatible way that can be rolled out sooner.
