### ISSUE TITLE
Unique slug/reference for the attribute; must be no more than 28 characters.

### ISSUE THREAD

**Issue by Ankor12** [woocommerce/woocommerce#22999]
Hello, i have product attribute generated by another plugin, and they are 29 character, so i cant reorder them, i have this error message
Unique slug/reference for the attribute; must be no more than 28 characters.
How can i reorder them, without renaming, or maybe directly on the database ?
Thanks for your help

**Comment by mikejolley** [comment]
This is a limit imposed by the WordPress database structure. The name can be longer than 28, but the slug part cannot. The plugin you're using or the data will need to be modified. > 28 is not supported.
