### ISSUE TITLE
Unable to set a global availability on appoint able products

### ISSUE THREAD

**Issue by logicrooms** [woocommerce/woocommerce#22996]
**Describe the bug**
I set up a global availability to products from 16 to 22 on weekdays and 10 to 22 on weekends in the back-end side.
On the front end it stays 24/7 anyway. 
Please see the screenshots.
I also tried to set the dates to the end. Didn't help. Setting product custom availability didn't help neither
![Global availability](https://user-images.githubusercontent.com/48478648/54198136-cb89b300-44d6-11e9-89dc-f9f7e302760b.png)
![product actual availability](https://user-images.githubusercontent.com/48478648/54198232-fd9b1500-44d6-11e9-8642-5668a07a7abf.png)

**To Reproduce**
1. logicrrooms.at/buchen

**Comment by kloon** [comment]
The screenshots you produced does not form part of WooCommerce core functionality. There is no global availability fields in WooCommerce core.

This is likely from a plugin/extensions, looks like a bookings one. I suggest you contact the developers or if this is a WooCommerce.com product you can contact support through WooCommerce.com
