### ISSUE TITLE
Add an additional argument to prevent 'woocommerce_order_status_changed' from being called

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce#23009]
Currently I set up Woocommerce as a Multi Vendor Marketplace. I want to prevent vendor to changing order status when the current status is "on-hold" & "completed".

There is no hook like 'woocommerce_order_status_before_change' so, currently the only way doing this is via "woocommerce_order_status_changed". The way it works is, revert back the changes that was made. Because "woocommerce_order_status_changed" happens after the order status changed.

Buttt, there's a catch. When we want to disable only 1 status that cant be changed. its easy. We can do something like this:

```
add_action( 'woocommerce_order_status_changed', 'prevent_order_status_change', 10, 4 );
function prevent_order_status_change( $order_id, $status_from, $status_to, $order ) {
	$current_user = wp_get_current_user();
	$current_user_roles = $current_user->roles[0];
	
    if( $current_user_roles != 'administrator' && $status_from == 'completed') {
        $order->update_status( $status_from, 'ERROR: cannot modify completed order!' );
    }

}
```

It works preventing the changes. But if we want to disallow multiple status being changed, This code will not work:

```
add_action( 'woocommerce_order_status_changed', 'prevent_order_status_change', 10, 4 );
function prevent_order_status_change( $order_id, $status_from, $status_to, $order ) {

	$current_user = wp_get_current_user();
	$current_user_roles = $current_user->roles[0];

    if( ($current_user_roles != 'administrator' && $status_from == 'completed') || ( $current_user_roles != 'administrator' && $status_from == 'on-hold') ) {
        $order->update_status( $status_from, "ERROR: $current_user_roles cannot modify locked order!" );
    }

}
```
It wont work if the status changed from "on hold" to "completed". Because after we successfully preventing the changes ("on hold" to "completed") and reverting back the value ("completed" to "on hold"). "woocommerce_order_status_changed" kicks in again and change status back once more ("on hold" to "completed"). So the final status is "completed" instead of reverting back to "on hold".

currently the only solution to this problem is, making the changes manually via sql query, so "woocommerce_order_status_changed" will not kick  in.

```
	if( ($current_user_roles != 'administrator' && $status_from == 'completed') || ( $current_user_roles != 'administrator' && $status_from == 'on-hold') ) {
		
		global $wpdb;
		$query = "UPDATE $wpdb->posts 
			SET post_status = 'wc-$status_from'
			WHERE ID = $order_id";
		$wpdb->query($query);

	}
```

But there's also a catch, in case future woocommerce want to modify the current table to improve speed like this plugin does 'https://github.com/liquidweb/woocommerce-custom-orders-table'. So this code may not work in the future. As all my programming principle is to make the code as future-proof as possible.

For the developer, Do you have any solution to this problem?

**Comment by kloon** [comment]
Have a look at the woocommerce_before_order_object_save filter, from there you can see all the order properties as well as lined up changes and make decisions based on that data in the order data store right before saving it, you should be able to change the status before it is saved with that filter.

**Comment by erikdemarco** [comment]
@kloon 
can you point me to where woocommerce_before_order_object_save is defined? I did a search through the github source code, couldn't find it. Couldn't find it on the documentaion nor Hook Reference page too.

Maybe can you give an example how to implement it in my code?

**Comment by kloon** [comment]
Sure, the reason you are not finding it is because we use a variable for the data type, the class is reused between all the data stores.

https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-data.php#L205

**Comment by erikdemarco** [comment]
@kloon 
When I want to echo the data it gives this error:
Warning: Illegal string offset 'from' in /home/hxxxx
Warning: Illegal string offset 'to' in /home/hxxxx

Here's my code:
```
add_filter( 'woocommerce_before_order_object_save', 'prevent_order_status_change', 1, 2 );
function prevent_order_status_change( $order, $data_store ) {
	echo $order->status_transition['from'];
	echo $order->status_transition['to'];
	exit();
}
```

I can read all data in $order except the 'status_transition'. What happens?

**Comment by kloon** [comment]
You need to use $order->get_data() and $order->get_changes() and compare the results there, get_changes will return all the fields that were changed and get_data all the original data as it was read from the db prior to it going to be updated.

So get_data should have the result of the original status, and get_changes should contain the results of the new status it is going to be updated to.

**Comment by erikdemarco** [comment]
@kloon 
Can you explain why all $order data can be accessed except only $order->status_transition can't be accessed?

And is my final code looks OK to you?

```
add_filter( 'woocommerce_before_order_object_save', 'prevent_order_status_change', 1, 2 );
function prevent_order_status_change( $order, $data_store ) {

	//do this only if there's a status changes
	if($order->status_transition) {
		$getdata = $order->get_data();
		$order_id = $getdata['id'];
		$from = $getdata['status'];
		$to = $order->get_changes()['status'];
		
		//write prevent code here
		...

		return $order;
	}

}
```

**Comment by kloon** [comment]
Looks good, I would just add a check in the get_changes part to first check that status is present before just calling it, will give a warning if the status is not part of the changes.

The reason why status_transition cannot be accessed is that it is a protected variable, it can only be accessed inside the order class and not from elsewhere, we do this to prohibit other plugins and code from manipulating the variable when it should not be manipulated. We prefer the use of hooks for manipulating data.

**Comment by erikdemarco** [comment]
This code always shows 'true', even when there's a data in '$order->status_transition':
```
print_r($order);
if($order->status_transition) {
 echo "true";
} else {
 echo "false";
}
```

Here's what print_r($order) return;
```
WC_Order Object
(
    [status_transition:protected] => Array
        (
            [from] => on-hold
            [to] => processing
            [note] => Order status changed by bulk edit:
            [manual] => 1
        )
,,,
```
Even gettype($order) return 'String'. So there must be data there, how come if($order->status_transition) return 'false'?

Then what is the way to check wheter 'status_transition' happens?

**Comment by erikdemarco** [comment]
@kloon 
This code always shows 'true', even when there's a data in '$order->status_transition':
```
print_r($order);
if($order->status_transition) {
 echo "true";
} else {
 echo "false";
}
```

Here's what print_r($order) return;
```
WC_Order Object
(
    [status_transition:protected] => Array
        (
            [from] => on-hold
            [to] => processing
            [note] => Order status changed by bulk edit:
            [manual] => 1
        )
,,,
```
Even gettype($order) return 'String'. So there must be data there, how come if($order->status_transition) return 'false'?

Then what is the way to check wheter 'status_transition' happens?

**Comment by kloon** [comment]
> This code always shows 'false', even when there's a data in '$order->status_transition':
Yes it will because the variable is protected.

Here is an example to do what you want, please note I cannot give more than this as this is not a support forum but an issue tracker.

```php
add_filter( 'woocommerce_before_order_object_save', 'prevent_order_status_change', 10, 2 );
function prevent_order_status_change( $order, $data_store ) {
	$changes = $order->get_changes();
	if ( isset( $changes['status'] ) ) {
		$data = $order->get_data();
		$from_status = $data['status'];
		$to_status = $changes['status'];

		// Do your logic here and update statuses with CRUD eg $order->set_status( 'completed' );
                // Be sure to return the order object

	}
	return $order;
}
```

**Comment by erikdemarco** [comment]
@kloon 
I'm really sorry maybe i'm misunderstood. If we update the data using "$order->set_status( 'completed' )"
Then What is the difference between my original solution and this one? It will not work. 

As my original code, this code will also call 'woocommerce_before_order_object_save' the second time and revert back the 'prevention'. 

What I want to know is. How to prevent 'woocommerce_order_status_changed' or 'woocommerce_before_order_object_save' to be called again the second time after we call $order->set_status. Please read my first post. If we do this the end result will be same. the second call will reverting 'the prevention we have done.

**Comment by felipe-pita** [comment]
Thank you @kloon ! this helped me alot

**Comment by eavitan** [comment]
Please Help on it for few hours already, cant find a solution

`add_action('woocommerce_before_order_object_save' , function ($order, $data_store ){

    $changes = $order->get_changes();
    echo '<br />';echo '<br />';echo '<br />';
    var_dump($changes);
    die();
}, 10, 2);`


$change returns always empty array, why?!

**Comment by lomars** [comment]
@eavitan 

Don't use `var_dump()` and `die()`… use instead use `error_log( print_r( $changes, true ) );`, enabling before error logs in Wordpress.

**Comment by egarriga** [comment]
Hello. I have a similar cuestion for anyone who can help me.

The think is that when the I do not want to change the date of the next_payment from the date that the transation is complete or active in the Subscription case. I want the calculation to be from the start of the subscription. I have done this.

`		add_filter( 'woocommerce_before_subscription_object_save', function ( $subscription, $data_store ) {
			$changes = $subscription->get_changes();

			if( ! empty($changes) && isset($changes['status']) ) {
				$post_data = $subscription->get_date('date_created');

				$calc_plus_date = "+". $subscription->get_billing_interval() ." ". $subscription->get_billing_period();
				$next_payment_time = strtotime( $calc_plus_date, strtotime($post_data) );
				$next_payment_time = date('Y-m-d H:i:s', $next_payment_time);

				echo "<pre>";
				var_dump(get_class($subscription));
				var_dump($subscription);
				echo "</pre>";
				die();


				$subscription->set_date_prop('start', $post_data);
				$subscription->set_date_prop('next_payment', $next_payment_time);
			}

			error_log( print_r( $changes, true ) );

		} , 10, 2 );`

Th eproblem is went I am trying to access this function from the out side "set_date_prop" because the funciton is protected and I can change the value.
