### ISSUE TITLE
Setup wizard hard to use on mobile

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#23018]
**Describe the bug**
Setup wizard layout on mobile isn't so great. 

**To Reproduce**
1. Run the setup wizard on a device, or with browser inspector

**Screenshots**
![](https://cld.wthms.co/pM504m+)
Image Link: https://cld.wthms.co/pM504m

![](https://cld.wthms.co/1Ts2uZ+)
Image Link: https://cld.wthms.co/1Ts2uZ

![](https://cld.wthms.co/uwe9E6+)
Image Link: https://cld.wthms.co/uwe9E6

**Expected behavior**
To be able to read/see everything. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
I don't know if it's worth looking at this now as I think there are plans to redo it. Not much of WC admin is mobile optimised. @jameskoster?
