### ISSUE TITLE
Classes on state dropdown not preserved when selecting country

### ISSUE THREAD

**Issue by justlevine** [woocommerce/woocommerce#23020]
**Describe the bug**
When choosing a country from the dropdown, any classes added to the state field (whether via `woocommerce_form_field_args` filter or by manually calling the state field via `woocommerce_form_field`) are overwritten.

This seems to be due to country-select.js hard-coding in class values.

**To Reproduce**
1. Add the following code to functions.php
```
add_filter( 'woocommerce_form_field_args', function($field){
    if('state' === $field['type'] ){
        $field['input_class'][] = 'custom-field';
    }
    return $field;
}
```

2. Go to Checkout, Account Details, or wherever your fields are outputted. 
3. Select a country. 
4. Note how the state field is missing your input class.

**Expected behavior**
country-select.js should save the input class list, and then use it for all replace functions.
E.g.
In country-select.js: 94, add 

> input_classes = $statebox.attr('class');

And then in all `replaceWith()` functions add input_classes to `class="..."` 

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###
WC Version: 3.5.6
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
```
</details>

**Comment by mikejolley** [comment]
Thanks we'll review and comment on the PR.
