### ISSUE TITLE
wc-add-to-cart function not displaying custom message in PHP 7.2

### ISSUE THREAD

**Issue by dperis** [woocommerce/woocommerce#23024]
The web host for our site is moving from PHP 5.x to 7.2 and the i18n_view_cart message is no longer displayed upon cart addition.  Did something here get deprecated in 7.2 and how to fix?  Thank you.

case 'wc-add-to-cart' :
$params = array(
'ajax_url'                => WC()->ajax_url(),
'wc_ajax_url'             => WC_AJAX::get_endpoint( "%%endpoint%%" ),
'i18n_view_cart'          => esc_attr__( 'This swatch has been added to your cart. Click here to view.', 'woocommerce' ),
'cart_url'                => apply_filters( 'woocommerce_add_to_cart_redirect', wc_get_cart_url() ),
'is_cart'                 => is_cart(),
'cart_redirect_after_add' => get_option( 'woocommerce_cart_redirect_after_add' ),);
break;

**Comment by mikejolley** [comment]
I've confirmed it's working on 7.2. That code works under 7.2, plus it's handled by JavaScript not PHP. Your problem must be elsewhere so check the PHP error logs. Possibly a warning/notice breaking the AJAX responses.
