### ISSUE TITLE
'Scheduled Actions' settings page has no explanation or clear function

### ISSUE THREAD

**Issue by melek** [woocommerce/woocommerce#23048]
**Is your feature request related to a problem? Please describe.**
'Scheduled Actions' is added by WooCommerce to Wordpress -> Tools, but has no explanatory text or clear function. I didn't even know it was related to WooCommerce before investigating.

**Describe the solution you'd like**
I would like the tool's settings page to have explanatory text and be labelled clearly as a part of WooCommerce.

I'd also like it be placed in an appropriate area of WooCommerce rather than the 'Tools' menu, if that wouldn't threaten backwards compatibility too much.

**Describe alternatives you've considered**
I don't even know what this page does. It's confusing.

**Additional context**
None, except that I've found a few threads of people confusing this for generic WordPress functionality (such as [here on the plugin support page](https://wordpress.org/support/topic/scheduled-actions/)).

**Comment by kloon** [comment]
See #23064
