### ISSUE TITLE
[WC Beta] Conflict with WooCommerce Blocks plugin

### ISSUE THREAD

**Issue by ashucg** [woocommerce/woocommerce#23049]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Install and activate [WooCommerce Blocks](https://wordpress.org/plugins/woo-gutenberg-products-block/) plugin
2. Install / update to beta - 3.6.0-beta.1

## Expected/actual behavior

After following the the above steps, website goes down:

`PHP Fatal error:  Cannot declare class WC_Block_Featured_Product, because the name is already in use in /wp-content/plugins/woo-gutenberg-products-block/includes/blocks/class-wc-block-featured-product.php on line 15`

What I expect is that WC checks whether **WooCommerce Blocks** is an activate plugin and display admin notice to deactivate it if so. 

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by Braintelligence** [comment]
I fixed this by moving the woo commerce block plugin out of the plugin folder.

**Comment by mikejolley** [comment]
cc @timmyc

**Comment by AiratHalitov** [comment]
Will `woo-gutenberg-products-block` plugin be included into `woocommerce` v3.6.0 plugin?
Can anyone give me an answer?

**Comment by timmyc** [comment]
@AiratHalitov yes the blocks functionality is shipping in 3.6d - release notes for the beta which list the features can be [seen here](https://woocommerce.wordpress.com/2019/03/15/woocommerce-3-6-beta/)

**Comment by kloon** [comment]
See #23080

**Comment by anudeepnrao** [comment]
![Screenshot (126)](https://user-images.githubusercontent.com/17963986/56563700-00a31e00-65ca-11e9-88c7-00a5ad1d8f60.png)
The above mentioned error can prevent you from logging into admin dashboard. The Issue was solved by deleting the plugin folder at 
/<public_html>/wp-content/plugin
<public_html>  ---> your web server html root (location varies on cPanel and IIS)
