### ISSUE TITLE
find_matching_product_variation() behaviour with "Any" variation attributes

### ISSUE THREAD

**Issue by leewillis77** [woocommerce/woocommerce#23042]
**Describe the bug**
`find_matching_product_variation()` expects to receive a variable product instance, and an array of attributes so that it can find which of the individual variations matches those `match_attributes`.

It currently returns no results (return value of `0`) if you do not pass it a `match_attribute` (even empty) for an attribute where the variation is set to match "any" of the attribute values. 

E.g. Consider a variable product that differentiates on size attribute, but also has "colour" as an attribute used for variations, e.g.

![Screenshot 2019-03-15 15 34 06](https://user-images.githubusercontent.com/1097338/54443067-caa38c00-4737-11e9-986d-51d749397bb6.png)

`find_matching_product_variation()` should be able to find the correct variation given *just* the size. However if fails if it is passed only a size.

```
// This returns 0
$data_store   = WC_Data_Store::load( 'product' );
$variation_id = $data_store->find_matching_product_variation(
    $variable_product,
    [
        'attribute_pa_size' => 'large',
    ]
);
```

```
// This returns the correctly variation ID (74 in our example)
$data_store   = WC_Data_Store::load( 'product' );
$variation_id = $data_store->find_matching_product_variation(
    $variable_product,
    [
        'attribute_pa_size' => 'large',
        'attribute_pa_colour' => '',
    ]
);
```

The problem appears to be this code here which returns 0 if an attribute is used for variations on a product and no attribute value is passed into the match_attributes array:
https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-data-store-cpt.php#L1068

I've come up with a potential fix [PR to follow] that seems to work for me, but I'm not 100% sure the logic is correct so it could definitely do with a review.

**Comment by leewillis77** [comment]
Related: `get_permalink()` on a variation instance returns a URL without empty attributes, e.g.

/product/variable-product-with-any-option/?attribute_pa_size=small
rather than:
/product/variable-product-with-any-option/?attribute_pa_size=small&attribute_pa_colour=

**Comment by leewillis77** [comment]
Sorry. Also meant to say. This code is fairly heavily changed in master vs. 3.5.6, but the same bug appears in both.

**Comment by mikejolley** [comment]
@leewillis77 I believe find_matching_product_variation is supposed to match once you've filled all fields on the variation form. For this use case, all attributes are set. A blank attribute value (no selection) is not valid.

What are you using this for?

**Comment by leewillis77** [comment]
It's schema.org related. Basically, we provide Google with a variation specific URL, as generated by:

```
$variation = wc_get_product( $variation_id );
$permalink = $variation->get_permalink();
```

When Google crawl that URL, we want to identify the specific variation based on the information in the URL and provide appropriate structured data (related to #17471). To do that we can do:

```
$data_store   = WC_Data_Store::load( 'product' );
$variation_id = $data_store->find_matching_product_variation( $product, wp_unslash( $_GET ) );
```

That works for variations where all attributes used for variations have values for variations, but not where an attribute is set to "any" (see my example at the original issue report). In this example find_matching_product_variation returns 0 and we can't identify the selected variation, despite the fact we do practically have enough information to find a matching variation.

This happens because `get_permalink()` on a variation does not include attributes set to "any" in the URL it generates, but `find_matching_product_variation` needs them. I could probably work around it, but it feels a bit hacky, and the different behaviour you get between not passing the attribute key at all, and passing it with an empty value, seems pretty inconsistent e.g.

```
$data_store->find_matching_product_variation(
    $variable_product,
    [
        'attribute_pa_size' => 'large',
        'attribute_pa_colour' => '',
    ]
);
```

vs

```
$data_store->find_matching_product_variation(
    $variable_product,
    [
        'attribute_pa_size' => 'large',
    ]
);
```

Does that explain?

**Comment by mikejolley** [comment]
Will respond in PR.
