### ISSUE TITLE
Make store notice dismissable without adding hash to URL

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/woocommerce#23055]
**Is your feature request related to a problem? Please describe.**
When dismissing the Store Notice, a hash (#) is added to the URL, which scrolls to the top of the page. This is unexpected, and easily results in losing your place on the page.

**Describe the solution you'd like**
I'd like the Store Notice to be dismissable without adding a hash (#) to the URL.

**Additional context**
See https://github.com/woocommerce/woocommerce/blob/master/includes/wc-template-functions.php#L985

Thanks for your consideration!

**Comment by kloon** [comment]
See #23066
