### ISSUE TITLE
looking for Shortcode to display all category except vacation rental category

### ISSUE THREAD

**Issue by askzipy** [woocommerce/woocommerce#23059]
https://askzipy.com/booking/

i want to display all categories except vacation rental category on homepage, can anyone help me with such shortcode?

I know i can mention all categories but that is not permanent solution, as and when i add new category i have to mention, so i am looking for to add all category except vacation rentals

**Comment by mikejolley** [comment]
This requires code if you don't want to provide ids for the shortcode. GitHub is not a support forum--you should direct these types of questions to the forums or facebook groups.

This is off the top of my head and untested but you'd use something like this (us at own risk):

```php
add_filter( 'woocommerce_product_categories', 'custom_woocommerce_product_categories' );

function custom_woocommerce_product_categories( $args ) {
$args['exclude'] = 10; // replace with cat ID
return $args;
}
```

https://developer.wordpress.org/reference/classes/wp_term_query/__construct/
