### ISSUE TITLE
Update WC plugin screenshot on WP repo

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/woocommerce#23056]
**Describe the bug**
The screenshot of the WooCommerce Settings panel on the WordPress Plugin page https://wordpress.org/plugins/woocommerce/ is very outdated.

Should be updated.

**Comment by kloon** [comment]
cc @dougaitken since you brought this up last week. Believe you will be working on getting things updated? If not let me know and we can look at updating the screenshots within the team.

**Comment by dougaitken** [comment]
I added a comment on @peterfabian's post here @kloon paqDfi-8P-p2
