### ISSUE TITLE
Checkout Page Cash On Delivery BUG

### ISSUE THREAD

**Issue by axcar95** [woocommerce/woocommerce#23062]
**Describe the bug**
when ı add a product to the cart and go to checkout page there is a problem. in cargo options whatever ı choose there no changing in the calculation. free shipping and cargo payment and cash on delivery options doesnt working. and when ı go to the next page cash on delivery payment options doesnt appear. ı cant choose it. ıt happened after the update.
**To Reproduce**
1. Go to 'checkout page'
2. Click on 'kapıda ödeme'
3. See error
![not doing calculation](https://user-images.githubusercontent.com/48660460/54500011-752ed100-4929-11e9-901d-7528ab928033.jpg)
![not doing calculation 2](https://user-images.githubusercontent.com/48660460/54500013-78c25800-4929-11e9-8d48-21268cc49800.jpg)
![explanation doesnt appaer](https://user-images.githubusercontent.com/48660460/54500017-7d870c00-4929-11e9-899e-c90fa95b1b6b.jpg)

ı expected to fix this problem and calculate the prices

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://flamindesign.com
Site URL: https://flamindesign.com
WC Version: 3.5.6
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: tr_TR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.8
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.60.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.39-cll-lve
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.6
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Toplam veritabanı boyutu: 57.74MB
Veritabanı veri boyutu: 54.58MB
Veritabanı indis boyutu: 3.16MB
wp_woocommerce_sessions: Veri: 41.58MB + İndis: 1.04MB
wp_woocommerce_api_keys: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_attribute_taxonomies: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_downloadable_product_permissions: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_order_items: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_order_itemmeta: Veri: 0.01MB + İndis: 0.01MB
wp_woocommerce_tax_rates: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_tax_rate_locations: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_shipping_zones: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_shipping_zone_locations: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_shipping_zone_methods: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_payment_tokens: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_payment_tokenmeta: Veri: 0.00MB + İndis: 0.00MB
wp_woocommerce_log: Veri: 0.00MB + İndis: 0.00MB
wp_commentmeta: Veri: 0.02MB + İndis: 0.02MB
wp_comments: Veri: 0.09MB + İndis: 0.03MB
wp_failed_jobs: Veri: 0.00MB + İndis: 0.00MB
wp_iyzico_card: Veri: 0.00MB + İndis: 0.00MB
wp_iyzico_order: Veri: 0.00MB + İndis: 0.00MB
wp_links: Veri: 0.00MB + İndis: 0.00MB
wp_mailchimp_carts: Veri: 0.00MB + İndis: 0.00MB
wp_options: Veri: 10.61MB + İndis: 0.95MB
wp_postmeta: Veri: 1.15MB + İndis: 0.84MB
wp_posts: Veri: 0.79MB + İndis: 0.10MB
wp_queue: Veri: 0.00MB + İndis: 0.00MB
wp_revslider_css: Veri: 0.09MB + İndis: 0.00MB
wp_revslider_layer_animations: Veri: 0.00MB + İndis: 0.00MB
wp_revslider_navigations: Veri: 0.00MB + İndis: 0.00MB
wp_revslider_sliders: Veri: 0.04MB + İndis: 0.00MB
wp_revslider_slides: Veri: 0.11MB + İndis: 0.00MB
wp_revslider_static_slides: Veri: 0.00MB + İndis: 0.00MB
wp_termmeta: Veri: 0.01MB + İndis: 0.02MB
wp_terms: Veri: 0.01MB + İndis: 0.02MB
wp_term_relationships: Veri: 0.04MB + İndis: 0.08MB
wp_term_taxonomy: Veri: 0.02MB + İndis: 0.01MB
wp_usermeta: Veri: 0.01MB + İndis: 0.02MB
wp_users: Veri: 0.00MB + İndis: 0.01MB
wp_wc_download_log: Veri: 0.00MB + İndis: 0.00MB
wp_wc_webhooks: Veri: 0.00MB + İndis: 0.00MB
wp_yith_wcwl: Veri: 0.00MB + İndis: 0.00MB
wp_yith_wcwl_lists: Veri: 0.00MB + İndis: 0.01MB

### Post Type Counts ###

attachment: 81
customize_changeset: 1
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
mc4wp-form: 2
nav_menu_item: 19
page: 41
portfolio: 9
post: 1
product: 38
product_variation: 3
revision: 75
service: 12
shop_coupon: 2
shop_order: 6
testimonial: 3
vc_settings_preset: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Contact Form 7: (Takayuki Miyoshi) – 5.1.1
iyzico WooCommerce: (iyzico) – 1.1.3
WordPress.com’dan Jetpack: (Automattic) – 6.9
WPBakery Page Builder: (Michael M - WPBakery.com) – 5.6
Mailchimp for WooCommerce: (Mailchimp) – 2.1.13 – WooCommerce’in etkin sürümüyle test edilmemiştir
MailChimp for WordPress: (ibericode) – 4.3.3
My WP Translate: (MyThemeShop) – 1.0.8
PL BigBazaar Extensions: (PressLayouts) – 2.0
Really Simple SSL: (Rogier Lankhorst
Mark Wolters) – 3.1.3

Slider Revolution: (ThemePunch) – 5.4.8.1
WooCommerce Blocks: (Automattic) – 1.3.1
WooCommerce PayPal Checkout Gateway: (WooCommerce) – 1.6.9 – 1.6.10 mevcut
WooCommerce: (Automattic) – 3.5.6
YITH WooCommerce Compare: (YITH) – 2.3.8
YITH WooCommerce Wishlist: (YITH) – 2.2.7

### Settings ###

API Enabled: –
Force SSL: –
Currency: TRY (₺)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Mağaza giriş sayfası: #139 - /magaza/
Sepet sayfası: #140 - /cart/
Ödeme sayfası: #141 - /checkout/
Hesabım sayfası: #142 - /my-account/
Şartlar ve koşullar: #1613 - /sozlesmeler/mesafeli-satis-sozlesmesi/

### Theme ###

Name: BigBazaar
Version: 2.1.4
Author URL: http://presslayouts.com/
Child Theme: ❌ – WooCommerce'i kendinizin oluşturmadığı ana bir temada düzenliyorsanız
yardımcı bir tema kullanmanızı öneririz. Bkz.: Nasıl yardımcı tema oluşturulur?

WooCommerce Support: ✔

### Templates ###

Overrides: bigbazaar/woocommerce/archive-product.php
bigbazaar/woocommerce/cart/cross-sells.php
bigbazaar/woocommerce/cart/mini-cart.php
bigbazaar/woocommerce/content-product.php
bigbazaar/woocommerce/content-product_cat.php
bigbazaar/woocommerce/content-single-product.php
bigbazaar/woocommerce/content-widget-product.php 3.5.2 sürümü güncel değil. Çekirdek sürüm: 3.5.5
bigbazaar/woocommerce/global/wrapper-end.php
bigbazaar/woocommerce/global/wrapper-start.php
bigbazaar/woocommerce/loop/loop-end.php
bigbazaar/woocommerce/loop/loop-start.php
bigbazaar/woocommerce/loop/orderby.php
bigbazaar/woocommerce/loop/pagination.php
bigbazaar/woocommerce/loop/rating.php
bigbazaar/woocommerce/loop/sale-flash.php
bigbazaar/woocommerce/single-product/add-to-cart/external.php
bigbazaar/woocommerce/single-product/price.php
bigbazaar/woocommerce/single-product/product-image.php
bigbazaar/woocommerce/single-product/product-thumbnails.php
bigbazaar/woocommerce/single-product/related.php
bigbazaar/woocommerce/single-product/sale-flash.php
bigbazaar/woocommerce/single-product/short-description.php
bigbazaar/woocommerce/single-product/up-sells.php
bigbazaar/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Nasıl güncelleştirileceğini öğrenin
`
</details>

**Comment by peterfabian** [comment]
Hi, 

I can't even switch shipping methods when I fill in address on your website. It seems to me that currently your website does not include correct WooCommerce javascript files (e.g. I can see no checkout.js), so please [try to rule out plugin/theme conflict](https://docs.woocommerce.com/document/how-to-test-for-conflicts/) first. It is very likely that some other code is interfering with WooCommerce.

**Comment by axcar95** [comment]
when switch the theme to twenty seven my checkout page forks fine there is no problem. so the problem is because of the theme. but when ı mailed the author of the theme they said it is not because of us. it external plugin conflict. what can ı do now. try the deactive plugins etc? or is it useless because changing the theme stopped the problem?

________________________________
Gönderen: Peter Fabian <notifications@github.com>
Gönderildi: 18 Mart 2019 Pazartesi 12:17
Kime: woocommerce/woocommerce
Bilgi: axcar95; Author
Konu: Re: [woocommerce/woocommerce] Checkout Page Cash On Delivery BUG (#23062)


Hi,

I can't even switch shipping methods when I fill in address on your website. It seems to me that currently your website does not include correct WooCommerce javascript files (e.g. I can see no checkout.js), so please try to rule out plugin/theme conflict<https://docs.woocommerce.com/document/how-to-test-for-conflicts/> first. It is very likely that some other code is interfering with WooCommerce.

**Comment by peterfabian** [comment]
Based on what you said it seems it could be the theme's conflict/bug, but difficult to say without further debugging. 
I would suggest you to try and leave your theme active, disable all plugins except for WooCommerce and see if the problem still appears. If not, then activate plugins one by one and after each activation check when the problem occurs. That way you should be able to find the conflicting plugin.
In case the problem appears with your theme and only WooCommerce active, then I would suggest to reach out to theme author again and report it as a bug.
