### ISSUE TITLE
Stock management error with variable product

### ISSUE THREAD

**Issue by paul-c-bristol** [woocommerce/woocommerce#23061]
**Describe the bug**
We have a product with multiple variants.
When we enable stock management at the product level but uncheck the stock management at variant level and mark out of stock at variant level - the item shows as IN-STOCK when saving

**To Reproduce**
1. Create a product with stock management checked and 2 variants and save
2. One one variant change the Stock Management to unchecked and set the product out of stock
3. When saving the screens reloads and your variant then re-shows as IN STOCK

**Screenshots**
[none]

**Expected behavior**
Item should be out of stock.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
`
### WordPress Environment ###

WC Version: 3.5.1
Log Directory Writable: ✔
WP Version: ❌ 4.9.8 - There is a newer version of WordPress available (5.1.1)
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.27 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 60
PHP Max Input Vars: 2000
cURL Version: 7.64.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.22-MariaDB
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.1
WC Database Prefix: wp_2_
MaxMind GeoIP Database: ✔
Total Database Size: 110.45MB
Database Data Size: 71.74MB
Database Index Size: 38.71MB
wp_2_woocommerce_sessions: ❌ Table does not exist
wp_2_woocommerce_api_keys: ❌ Table does not exist
wp_2_woocommerce_attribute_taxonomies: ❌ Table does not exist
wp_2_woocommerce_downloadable_product_permissions: ❌ Table does not exist
wp_2_woocommerce_order_items: ❌ Table does not exist
wp_2_woocommerce_order_itemmeta: Data: 2.02MB + Index: 2.33MB
wp_2_woocommerce_tax_rates: ❌ Table does not exist
wp_2_woocommerce_tax_rate_locations: ❌ Table does not exist
wp_2_woocommerce_shipping_zones: ❌ Table does not exist
wp_2_woocommerce_shipping_zone_locations: ❌ Table does not exist
wp_2_woocommerce_shipping_zone_methods: ❌ Table does not exist
wp_2_woocommerce_payment_tokens: ❌ Table does not exist
wp_2_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_2_woocommerce_log: ❌ Table does not exist
wp_2_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_2_comments: Data: 0.16MB + Index: 0.09MB
wp_2_links: Data: 0.02MB + Index: 0.02MB
wp_2_options: Data: 6.34MB + Index: 0.08MB
wp_2_postmeta: Data: 41.56MB + Index: 24.06MB
wp_2_posts: Data: 14.52MB + Index: 3.70MB
wp_2_termmeta: Data: 0.09MB + Index: 0.13MB
wp_2_terms: Data: 0.09MB + Index: 0.09MB
wp_2_term_relationships: Data: 1.52MB + Index: 1.52MB
wp_2_term_taxonomy: Data: 0.09MB + Index: 0.11MB
wp_blogs: Data: 0.02MB + Index: 0.03MB
wp_blog_versions: Data: 0.02MB + Index: 0.02MB
wp_registration_log: Data: 0.02MB + Index: 0.02MB
wp_signups: Data: 0.02MB + Index: 0.06MB
wp_site: Data: 0.02MB + Index: 0.02MB
wp_sitemeta: Data: 0.31MB + Index: 0.03MB
wp_usermeta: Data: 4.52MB + Index: 6.03MB
wp_users: Data: 0.36MB + Index: 0.31MB

### Post Type Counts ###

3d-flip-book: 1
attachment: 5237
carts: 255
custom_css: 1
nav_menu_item: 37
page: 51
post: 4
postman_sent_mail: 882
product: 6591
product_variation: 1110
revision: 107
shop_order: 49
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (33) ###

Adminimize: by Frank Bültge – 1.11.4
Category Posts in Custom Menu: by Diana Koenraadt – 1.2.3
Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.3.2

Admin Columns: by AdminColumns.com – 3.3.1
Contact Form 7: by Takayuki Miyoshi – 5.1.1
Duplicate Menu: by Jonathan Christopher – 0.2.1
Gravity Forms: by rocketgenius – 2.3.6.6
GTranslate: by Translate AI Multilingual Solutions – 2.8.43
Heartbeat Control by WP Rocket: by WP Rocket – 1.2.5
Insert Headers and Footers: by WPBeginner – 1.4.3
3D FlipBook - Light Edition: by iberezansky – 1.9.10
Mailchimp for WooCommerce: by Mailchimp – 2.1.11 – Not tested with the active version of WooCommerce
MailChimp for WordPress: by ibericode – 4.2.5
MASS Users Password Reset: by KrishaWeb PVT LTD – 1.0
Menu Icons: by ThemeIsle – 0.11.4
New User Approve: by Josh Harrison – 1.7.6
Post Duplicator: by Metaphor Creations – 2.20
Post SMTP: by Jason Hendriks
Yehuda Hassine – 1.9.6

RegistrationMagic Premium: by Registrationmagic – 4.3.2.3
Relevanssi: by Mikko Saari – 4.1.2
Required taxonomies: by VegaCorp – 1.1.2
Show Hide Author: by Marios Alexandrou – 2.3
Preloader: by Alobaidi – 1.0.9
User Role Editor: by Vladimir Garagulya – 4.49
WooCommerce Invoice Gateway: by Stuart Duff – 1.0.2 – Not tested with the active version of WooCommerce
Woo Checkout Field Editor Pro: by ThemeHiGH – 1.3.0
Woo-Loader: by WooKage – 1.5 – Not tested with the active version of WooCommerce
WooCommerce Auto Category Thumbnails: by Shellbot – 1.2.1 – Not tested with the active version of WooCommerce
WooCommerce Bulk Discount: by Rene Puchinger – 2.4.5 – Not tested with the active version of WooCommerce
WooCommerce Cart Reports: by WooCommerce – 1.2.0 – 1.2.2 is available – Not tested with the active version of WooCommerce
Woocommerce Products Per Page: by Jeroen Sormani – 1.2.6 – Not tested with the active version of WooCommerce
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.12 – 3.0.14 is available
WooCommerce: by Automattic – 3.5.1 – 3.5.6 is available

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Basket: #5 - /basket/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #14725 - /terms-conditions/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.7.0
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome-child/woocommerce/emails/admin-new-order.php version 2.5.0 is out of date. The core version is 3.5.0
flatsome-child/woocommerce/emails/customer-processing-order.php
flatsome-child/woocommerce/emails/plain/admin-new-order.php version 2.5.0 is out of date. The core version is 3.5.0
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php version 3.5.0 is out of date. The core version is 3.5.1
flatsome/woocommerce/single-product/product-thumbnails.php version 3.3.2 is out of date. The core version is 3.5.1
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update
`

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23069
