### ISSUE TITLE
Default wording for Completed e-mails needs improvement

### ISSUE THREAD

**Issue by AdrienM76** [woocommerce/woocommerce#23078]
**Describe the bug**
The wording choice for default text in the customer-completed-order.php template is very poor.

"Your order has been marked complete on our side."

While someone may have thought this was a 'hip' way to communicate, it is rather snarky, implying 'all done here, now its your problem.'

At the very least, this wording is not customer service focused at all.

It is ambiguous. Sure it says it was 'marked complete' but what does that mean to the customer? It doesn't say it WAS completed, just that it was marked as such.

It does not state anything about the product having been shipped. The customer is left wondering if this means the store thinks the order has been received already.

**Expected behavior**
Default e-mails should be clear, concise and customer service focused. If a store owner wants to be cutesy, they can edit the template.

Have someone with a customer service background write these templates. A simple "Your order has been completed and shipped." would suffice here.

**Isolating the problem (mark completed items with an [x]):**
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently. It is default in the template.

**Comment by mikejolley** [comment]
> It is ambiguous. Sure it says it was 'marked complete' but what does that mean to the customer?

How can this text be generalized enough to mean anything to all possible store customers?

> It does not state anything about the product having been shipped. 
> A simple "Your order has been completed and shipped." would suffice here.

Not all stores ship goods, which rules our your suggestion. 

>  If a store owner wants to be cutesy, they can edit the template.

This is also the case if you want to add more customer-focussed-store-specfiic text.

Open to suggestions.

**Comment by mikejolley** [comment]
cc @MarinaWoo

**Comment by MarinaWoo** [comment]
> "Your order has been marked complete on our side." 

How about it be reduced to:

> "Your order is complete."

This matches the subject line of the email.

**Comment by MarinaWoo** [comment]
The above change doesn't allow for scenarios where an order is 'on its way to being complete' – for example, en route with a courier – and will mean the Store Manager should only mark an order as 'complete' and trigger this email when they know an order has actually arrived with the customer.

The current wording allows for an order to be en route, so a Store Manager can trigger this email when the order is posted/collected.

**Comment by willgorham** [comment]
Maybe 'We have completed your order', or 'We have completed processing your order'?

**Comment by MarinaWoo** [comment]
'We have completed your order'

+1

**Comment by mikejolley** [comment]
`We have completed your order` doesn't make much realistic sense in my opinion, but I do like `We have finished processing your order`. That makes sense to me as it's the next logical step/email after processing status.

**Comment by mikejolley** [comment]
Added to https://github.com/woocommerce/woocommerce/pull/23128 - feedback can be added there please.

**Comment by bamboomcr** [comment]
I would expect the message to tell me my order is on it's way or it has been dispatched "Your order has now been dispatched"

**Comment by TomasHurtz** [comment]
I realise the standard Woocommerce text cannot work for everyone.  So how do we customise the message "We have finished processing your order" on customer email.  I can't see a way to do so in woocommerce settings?

When I look at the "Order Complete" text it says:

Hi there. Your recent order on [site] has been completed. Your order details are shown below for your reference:

I need it to say more:

"We have finished processing your order.  You should receive your order according to our delivery timescales here: [link]
