### ISSUE TITLE
[WC 3.6] Wrong SKU in duplicated product 

### ISSUE THREAD

**Issue by Chouby** [woocommerce/woocommerce#23071]
**Describe the bug**
When duplicating a product, the new product keeps the SKU of the original product. In previous versions, the duplication process appended a "-1" to the original SKU to get a unique SKU per product. 

**To Reproduce**
1. Create a new product
2. Assign a SKU such as "test-sku"
3. Save the product
4. In the products list table, click on "duplicate".
5. Look at the sku of the duplicated product.

**Expected behavior**
 I was ewpecting the new SKU to be "test-sku-1" instead of "test-sku".

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
![Products ‹ Test — WordPress 2019-03-20 20-10-52](https://user-images.githubusercontent.com/90977/54715836-4775a200-4b4c-11e9-96a2-4a1836ec3445.png)

This appears to be working. If you've been running versions of WC from GitHub for testing purposes, make sure to run the product lookup table generation in system status > tools, and re-activate WC to ensure the lookup table is generated. I suspect you're just missing data in that table so it's not seeing the duplicate SKU.

@timmyc I'm assuming you marked this for the milestone without testing the issue. If you were able to replicate this too, let me know :)

Thanks
