### ISSUE TITLE
HTML template settings no longer exist - documenation inaccurate

### ISSUE THREAD

**Issue by AdrienM76** [woocommerce/woocommerce#23079]
**Describe the bug**
The documentation for editing e-mail settings is not consistent with the screens and functions available. Particularly https://docs.woocommerce.com/document/configuring-woocommerce-settings/#section-18, Editing Individual E-mail Templates has a screenshot and describes a process to customize the template in question, yet that functionality is not present in the current version. In addition, the documentation directs the user to 'click the gear wheel' on the right side. Yet there is no wheel, instead there is a 'manage' button. (presumably the same page will result)

**To Reproduce**
1. Go to woocommerce > settings > e-mails
2. Click on an e-mail name or the 'manage' button for that line
4. Observe there is no section for 'HTML template' or buttons for 'Copy file to theme' or 'View template'

**Screenshots**
![Screen Shot 2019-03-18 at 3 05 21 PM](https://user-images.githubusercontent.com/19876193/54560047-5c6dfc00-49b9-11e9-8535-6fd6032425ab.png)

**Expected behavior**
![Screen Shot 2019-03-18 at 3 07 50 PM](https://user-images.githubusercontent.com/19876193/54560156-97702f80-49b9-11e9-812c-53b7c993dfd3.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
This exists only if the directory is writable. If it's not, like in your case, you must do it manually i.e. using an FTP client or your hosting provider control panel.

> To override and edit this email template, copy woocommerce/templates/emails/admin-new-order.php to your theme folder: yourchildtheme/woocommerce/emails/admin-new-order.php. 

Thanks
