### ISSUE TITLE
SASS Color Arithmetic is Deprecated

### ISSUE THREAD

**Issue by eric-michel** [woocommerce/woocommerce#23072]
The file woocommerce.scss uses SASS color arithmetic in 4 places (that I can immediately find) - lines 736, 748, 1423, and 1677.

Color arithmetic in SASS is being deprecated - see https://github.com/sass/libsass/issues/2414. The current version of dart-sass already returns a compile error.
```
cmd.exe /D /C call E:\dart-sass\sass.bat woocommerce.scss:woocommerce.css
Error: Undefined operation "#ebe9eb - #111".
    ╷
723 │             background-color: $secondary - #111;
    │                               ^^^^^^^^^^^^^^^^^
    ╵
  woocommerce.scss 723:22  root stylesheet

Process finished with exit code 65
```

**Comment by mikejolley** [comment]
Thanks, fixed it in https://github.com/woocommerce/woocommerce/commit/308d08f97ea587ba0707745e868d387c875872e7
