### ISSUE TITLE
Certain shipping regions in a Zone are displaying twice during auto-completion.

### ISSUE THREAD

**Issue by seanreloaded** [woocommerce/woocommerce#23074]
**Describe the bug**
When adding Regions into a Shipping Zone, certain US States are displaying twice during auto-completion when you start to type them in. I have only been able to replicate this behavior with Maryland and Montana,

**To Reproduce**
1. Edit an existing Shipping Zone or create a new one.
2. In the Zone region auto-complete box, enter in "Maryland" or "Montana".

The following screenshots demonstrate the behavior:

![alt](https://cdn-std.dprcdn.net/files/acc_403167/QiWsSX)
Image link: https://cdn-std.dprcdn.net/files/acc_403167/QiWsSX

![alt](https://cdn-std.dprcdn.net/files/acc_403167/AEj3tI)
Image link: https://cld.wthms.co/AEj3tI

**Expected behavior**
Similar to typing in any other US state, I expect them to be displayed only once.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

(This was tested using WooCommerce 3.5.6 and Storefront 2.4.5.

**Comment by willgorham** [comment]
What are your shipping settings under Settings > General? (Shipping locations / Ship to specific countries options)

**Comment by mikejolley** [comment]
These places exist in non-US countries too.

**Comment by mikejolley** [comment]
Looks like it was fixed in https://github.com/woocommerce/woocommerce/pull/22339 for 3.6
