### ISSUE TITLE
Will offerCount be included in structured data? 

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#23075]
This was brought up [in this PR](https://github.com/woocommerce/woocommerce/pull/22925), but I didn't see a clear answer. It appears that offerCount is the number of prices available for a product. For most products, this would be 1, for variable, it could be many... but I can see this getting out of control for products added by plugins like Bookings, Subscriptions, Product Add-Ons, etc. 

Just curious if this will be something that's added to core in the future or if it will be left out due to the extreme variable nature of the item.

**Comment by mikejolley** [comment]
Only if it's needed i.e. is more than a warning. This is being discussed in https://github.com/woocommerce/woocommerce/issues/22969

**Comment by jessepearson** [comment]
@mikejolley thanks for the reference. I had searched for `offerCount` and it didn't come up.

**Comment by mikejolley** [comment]
@jessepearson just refered to this issue number tl;dr google changed some requirements for variable products so things like IDs and so on may need to be handled differently to prevent warnings. There will be no changes in the short term.
