### ISSUE TITLE
wc_get_order - failed to load ressources

### ISSUE THREAD

**Issue by robinma12** [woocommerce/woocommerce#23085]
Hello,

I installed Woocommerce and the theme shopper. Now I tried to use the wc_get_order function to do additional processing with the order details.

But whenever I place an order nothing happened so I decided to test the code in an seperate PHP file and as it seems when I try the following I get an HTTP Error 500 -> failed to load ressources.

Here's the part of the code that gets called when an order is placed, which contains the wc_get_order function:

`$order = wc_get_order(23);`

Could anybody help me with that? Woocommerce Version is 3.5.7

Thanks in advance

**Comment by rodrigoprimo** [comment]
Hi there! GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce
