### ISSUE TITLE
Issue to fetch featured product list through API

### ISSUE THREAD

**Issue by Atranaz** [woocommerce/woocommerce#23081]
**Describe the bug**
I am using the woocommerce for my mobile application but I found some of function are not working. In product list api when I tried to fetch the featured products it give me normal result. same issue with on_sale, min & max price. 

`
$params = array(
                'status' => 'publish',
                'featured' => 1
            );
            $productsdata = Woocommerce::get('products', $params);
            $productlist = $this->listProductLayout($productsdata);
            $result = ['status_code'=>200,'message' => 'List of products','data' => $productsdata];
            return response()->json($result, 200);
`

**Screenshots**

**Expected behavior**
return me list of featured products only

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.

Home URL: |   | 
-- | -- | --
Site URL: |   | 
WooCommerce version: |   | 3.5.5
Log directory writable: |   | 
WordPress version: |   | 5.1.1
WordPress multisite: |   | –
WordPress memory limit: |   | 1,000 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_GB
External object cache: |   | –


```
</details>

**Comment by mikejolley** [comment]
This works for me:

```
https://local.wordpress.test/wp-json/wc/v3/products?featured=1
```

As does adding it to the request body as:

```
{
	"featured": 1
}
```

Try the request via a desktop client https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API

I suspect it's the library you're using, if so please report to the relevent repo/developer.

Thanks
