### ISSUE TITLE
Settings are updated after admin menu hook

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce#23087]
**Describe the bug**
Options from the setting page are updated after the `admin_menu` hook.  For the most part this is not an issue, but one very minor problem is that this will prevent checking options on the next page load.

It looks like the options are being updated in the `'load-' . $settings_page` hook.  We might consider putting these on an earlier hook like `init` or `wp_loaded` if possible.

**To Reproduce**
1. Check an option value in an earlier hook than `'load-' . $settings_page`.  E.g.,
```php
function add_menu_item() {
    	if ( 'yes' === get_option( 'woocommerce_manage_stock' ) ) {
            // This block won't fire until the next page load.
        }
}
add_action( 'admin_menu', 'add_menu_item' );
```
2. Change an option and save.  E.g., enable stock management at `/wp-admin/admin.php?page=wc-settings&tab=products&section=inventory`
3. Note the option remains as the old value on initial page load.

This behavior can be seen in [this branch of wc-admin](https://github.com/woocommerce/woocommerce-admin/pull/1841).

**Screenshots**
(missing "Stock" page included in wc-admin when stock management is enabled)
<img width="332" alt="Screen Shot 2019-03-20 at 2 34 28 PM" src="https://user-images.githubusercontent.com/10561050/54663750-4a0cd300-4b1d-11e9-946b-64f867e61afc.png">
<img width="482" alt="Screen Shot 2019-03-20 at 2 34 13 PM" src="https://user-images.githubusercontent.com/10561050/54663751-4aa56980-4b1d-11e9-94c9-70a0a853ba9a.png">

**Expected behavior**
Expected to be able to get the new option setting inside the `admin_menu` to conditionally load pages.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
@joshuatf I think the idea of running save where it does now is to ensure it only processes settings on the settings page. Using init would run on every page load, admin and frontend.

**Comment by joshuatf** [comment]
@mikejolley Right, I guess I should have clarified a bit further, but could this not be replaced with a hook on init and check in the settings class?

```php
if ( ! is_admin() || ! isset( $_GET['page'] ) || 'wc-settings' !== $_GET['page'] ) {
    return;
}
``` 

Or alternatively, we could check against the global `$pagenow` like WP does under the hook for the `'load-' . $settings_page` hook.

**Comment by mikejolley** [comment]
@joshuatf got it. See #23091. I've marked that for 3.7 since moving logic around can affect extension compatibility so needs some extra testing before deploy. If you wanted a workaround temporarily you could check for the POST var when registering menus.
