### ISSUE TITLE
[concurrency issue] Create customer endpoint allows multiple users with same email and username

### ISSUE THREAD

**Issue by ataskine** [woocommerce/woocommerce#23098]
**Describe the bug**
Calling create customer API endpoint frequently with same email (and username) causes creation of multiple users with same **logon_name** and **email** address. This happens for example when using [WC API Create customer endpoint](https://woocommerce.github.io/woocommerce-rest-api-docs/#create-a-customer) to synchronise orders from another service with a logic that creates a customer for an email if user not exists.

**To Reproduce**

Assuming that you have WC API enabled and you have key and secret with write permission.

1. Create following script:
```
#!/bin/bash
for i in {1..3}
do
  curl -X POST \
    'https://<STOREURL>/wp-json/wc/v1/customers?consumer_key=<KEY>&consumer_secret=<SECRET>' \
    -H 'Content-Type: application/json' \
    -H 'cache-control: no-cache' \
    -d '{"email": "new2@customer.io"}' &
done
```
2. Run script
3. Go on your Wordpress users page and see that API generated multiple users with same logon_name and email.

**Screenshots**
Here is a screenshot after running the script.
![image](https://user-images.githubusercontent.com/32832496/54737758-1469f780-4bba-11e9-858f-c9d83f49665d.png)

**Expected behavior**
Expected that at least all the API endpoints that updates Customer would have been atomic. So I would have get 400 error response with code `"registration-error-email-exists"` as I will have if run same script again. 

My suggestion is to fix users table to have unique email and logon_name fields. However because WordPress have not been implemented this way I suggest that You take care of this with in Your API endpoint. Currently this implementation may cause serious harmful issues affecting all users having multiple accounts with same details. Please try for your self :)

**Comment by mikejolley** [comment]
This is a concurrency issue. If you perform those requests independently it does validate. This issue also occurs with the core WP users endpoint. `https://<STOREURL>/wp-json/wp/v2/users`

```
{
	"username":"test",
	"email":"test@test.com",
	"password":"12345"
}
```

Other endpoints may be similary affected.

Whilst I'd love to be able to easily solve this one and other similar concurrency issues on the WC side, the fact remains that the WP REST API we build upon has the same limitations. If WP core were to address this in the main API, we can follow suit. Changing this at database level is not an option for us, unless/if we ever move away from the core tables for storage of customers. 

cc @claudiosanches just making sure you 👀 this. I'm marking it won't fix for now but we should revisit this and/or raise on WP trac to see if there is interest in fixing on the WP side.
