### ISSUE TITLE
add hook for 'action button' in order details

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce#23099]
Currently to add custom action button to 'order details' page is by using 'woocommerce_order_details_after_order_table' hook. So if there's a 'order again' button, this custom button will show below that 'order again' button. whcih looks weird in desktop view. Why not make a special hook for group of action buttons like in order list page ('woocommerce_my_account_my_orders_actions'). So it will looks cleaner. 

Here's my current code, and look the view on the order details page:
```
function sfc_add_request_refund_orderdetails( $order ) {
        echo '<p><a class="button" href="' . esc_url( url_of_request_refund( $order ) ) . '">Request Refund</a></p>';
}
add_action( 'woocommerce_order_details_after_order_table','sfc_add_request_refund_orderdetails', 10, 1 ); 
```

**Comment by mikejolley** [comment]
Hi,

I'm not sure thats neccessary. The existing hook lets you control position by using a priority. The order again button uses 10. If you use 9 or lower your button can come first.

As for position, the 'order-again' paragraph tag has a class so you can float those buttons or style them with CSS. No need to do this via PHP.

Introducing/refactoring this wouldn't add much benefit and would incur a breaking template change. For that reason I don't think we should add another hook there and leave those templates as-is until a larger overhaul is done.

Thanks
