### ISSUE TITLE
Mixed InnoDB/MyISAM engine could escalate to severe

### ISSUE THREAD

**Issue by AlviseNicoletti** [woocommerce/woocommerce#23090]
I want to share with you a problem that was very severe !
The problem was a mix of InnoDB/MyISAM tables.

Infact after decision of MySQL to set InnoDB as default engine (mid 2018),
mixed databases that have (for example) old Woocommerce tables in MyIsAM but new WPML tables in Innodb (example a plugin create new tables > 2018)
creates failures in joins that cause lock in tables that cause entries with ID = 0 to appear,
that cause A LOT of problems and also Wordpress failure.

In WOOCOMMERCE case, it happened with **PREFIX_wc_download_logs** that was new (InnoDB) and other tables was MyISAM.
That ruined our database while updating plugins (**alter table and join on new createt tables fails**).

We are now sending to Wordpress developement team a fix to the main problem, that was in wp-includes/post.php line 4538 (missing infinity loop check).

FIX FOR YOU:
All plugin developers should check if their tables are the same of current default-storage-engine inside MySQL, if their not, they should:
**alter table TABLENAME engine "default-storage-engine";**

Bye !

Please advertise this problem, because it will be more and more frequent in the upcoming months.

**Comment by mikejolley** [comment]
I agree this could be a problem however I don't think WC should be changing table types. If this is possible it should be done by WordPress itself IMO. 

Whilst this won't fix the problem automatically, I've added database engine type to the status report https://github.com/woocommerce/woocommerce/pull/23101 This should at least make the problem more obvious when debugging and give us more data about how widespread a problem this is, or is becoming.

Thanks
