### ISSUE TITLE
Duplicate users created at checkout leading to login to wrong account and checkout delay

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce#23107]
Similar, but not the same: https://github.com/woocommerce/woocommerce/issues/23098 . Seen on WooCommerce 3.5.6 on WordPress 5.1.1, on PHP 7.2.16 (the issue appears to be a simple race condition and not dependent upon precise versions).

Our store is set to create a user automatically when someone orders at the checkout. The customer enters only their email address. WooCommerce is creating the username automatically from it.

Today on our store, two user accounts with identical usernames were created. (i.e. Two separate entries in the WP `users` table - same `user_login`, but different IDs and email addresses). Both people were on the checkout page at the same time, and both entered email addresses beginning with `info@`.

This resulted in one of the customers being logged into the other customer's account, with all that that entailed. That has security implications (e.g. ability to place new orders using the other customer's stored payment credentials; ability to access their account details and operate the account as their own). I haven't reported it privately because there's no clear way to reproduce upon demand (unless you know the precise instant someone else with a given email address is going to order).

I suggest WooCommerce could either introduce a semaphore lock on the "generate a new username" operation so that only one process is doing it at a time, or alternatively, add some randomisation to the generation of usernames. It's only because the usernames are entirely deterministic, based upon what other usernames exist, that the race condition becomes important.

Also, the performance aspect: looking at `wc_create_new_customer()`, and the `Ensure username is unique` loop, in which it checks possibly usernames sequentially starting from the beginning (`$append = 1; ... ; $append++`), I also infer that there must be a lot of moderately-busy shops running thousands of `SELECT` queries at the checkout, and some bigger ones running tens of thousands - one for each existing user. This will happen every time someone uses an email address beginning of `info@`, independently of any race.
On this site, currently the usernames `info` up to `info4140` exist. Running an SQL file with all the SQL `SELECT`s that WP runs when running `username_exists()` going through this sequence takes 1.46 seconds on the well-specced server this is running on; but on shared hosting I'd expect people will see a lot worse. (This would have implications for if a semaphore lock was used - i.e. would delay other peoples' concurrent checkouts if the algorithm remained unchanged). If the database server was loaded, then that many unnecessary SQL queries would have the unfortunate side-effect of making any other race conditions in WC rather more likely (e.g. the IPN/PDT PayPal double-processing clash).

Looking at a few others (sales@, hello@, mail@, contact@), none are close in number to info@.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23145 - please add feedback there.
