### ISSUE TITLE
Checkout Shortcode Not Checking Stock Management Status

### ISSUE THREAD

**Issue by mysticalone** [woocommerce/woocommerce#23108]
**Describe the bug**
Attempting to checkout order created manually using a product without stock management causes the following message to appear: "Sorry, we do not have enough "%1$s" in stock to fulfill your order (%2$s available). We apologize for any inconvenience caused."

**To Reproduce**
1. Create a product in WooCommerce. 
2. Do not enable stock management for product.
3. Then manually create WooCommerce order, adding the new product to the order.
4. Save the order, then click on "Customer payment page"
5. On the payment page, the message "Sorry, we do not have enough "%1$s" in stock to fulfill your order (%2$s available). We apologize for any inconvenience caused."

**Screenshots**

**Expected behavior**
When an order contains a product without stock management enabled, one expects to see the customer checkout page when processing manual order.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
no
```
</details>

**Comment by rodrigoprimo** [comment]
Closing to focus the discussion on PR #23109.
