### ISSUE TITLE
Add future post status to WC CLI supported product statuses

### ISSUE THREAD

**Issue by rekkitatu** [woocommerce/woocommerce#23103]
There are situations where I would like to use CLI to get information about scheduled products (products with future publish date). Currently `wp wc product list --status=future` tells that the supported statuses are 'any, draft, pending, private, publish'.

I can circumvent this issue by either using Wordpress CLI commands to get scheduled posts with post_type=product or by using WC CLI with date filtering. However, having the support for the future status straight in the WC CLI would make things faster and easier.

**Comment by mikejolley** [comment]
@claudiosanches The API uses `get_post_statuses` but `future` is not returned.

Admin uses `get_post_stati( array( 'show_in_admin_status_list' => true ), 'objects' )`, or we can hardcode `future`. Preference?

**Comment by claudiosanches** [comment]
@mikejolley we don't allow users to schedule products, but there's no problem to include that for filter products.

**Comment by mikejolley** [comment]
@claudiosanches WP does - you set a future date on a product before saving.

**Comment by claudiosanches** [comment]
@mikejolley good to know that this works too.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23138
