### ISSUE TITLE
Ssingle product woo elements in WP-Bakery problems

### ISSUE THREAD

**Issue by abossola** [woocommerce/woocommerce#23115]
When using the single product woo elements in WP-Bakery the columns width defaults to 4 columns

EX: https://cl.ly/aea9f8f97590 and https://cl.ly/ec398e04770a will show you what I mean

If you use the Products element and select one column it works as expected. But the single product shows four.

**Comment by mikejolley** [comment]
Hi

We're unable to test against premium plugins/page-builders. If WP Bakery advertises WC compatibiltiy you'll need to raise this with their support.

Thanks
