### ISSUE TITLE
Simple product with attributes marked "used for variations" results in error

### ISSUE THREAD

**Issue by FPCSJames** [woocommerce/woocommerce#23118]
**Describe the bug**
If a product is set to Variable, has attributes set that are marked "used for variations", then is switched back to Simple and saved, an error will occur when attempting to switch back to variable and add variations without saving in between.

```Uncaught Error: Call to undefined method WC_Product_Simple::get_variation_attributes() in /home/[user]/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php:677  
Stack trace:
#0 /home/[user]/public_html/wp-includes/class-wp-hook.php(286): WC_AJAX::add_variation('')
#1 /home/[user]/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /home/[user]/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#3 /home/[user]/public_html/wp-admin/admin-ajax.php(167): do_action('wp_ajax_woocomm...')
#4 {main}  
  thrown in /home/[user]/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php on line 677  
```

**To Reproduce**
1. Create a new variable product.
2. Add an attribute, and select "Used for varations".
3. Switch the product back to Simple.
4. Save the product as a draft.
5. Edit the product; change it to Variable.
6. Click Variations tab, then Go next to dropdown set to "Add variation".
7. See AJAX request return as 500 in Firefox or Chrome dev tools.

**Expected behavior**
The error should not occur. If a product is set back to Simple and saved after an attribute marked as "used for variations" has been added, that option should be cleared. Alternatively, if it is allowed to be saved that way, it should be detected and the appropriate class used after switching back to Variable (before saving) in the UI.

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

### WordPress Environment ###

Home URL: https://[snip]
Site URL: https://[snip]
WC Version: 3.5.7
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.2.16
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.0.38-MariaDB-cll-lve
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.7
WC Database Prefix: fmhgigd_
MaxMind GeoIP Database: ✔
Total Database Size: 6.19MB
Database Data Size: 4.35MB
Database Index Size: 1.84MB
fmhgigd_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
fmhgigd_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
fmhgigd_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
fmhgigd_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
fmhgigd_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
fmhgigd_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB
fmhgigd_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
fmhgigd_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
fmhgigd_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
fmhgigd_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
fmhgigd_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
fmhgigd_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
fmhgigd_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
fmhgigd_woocommerce_log: Data: 0.02MB + Index: 0.02MB
fmhgigd_ac_abandoned_cart_history_lite: Data: 0.06MB + Index: 0.00MB
fmhgigd_ac_email_templates_lite: Data: 0.02MB + Index: 0.00MB
fmhgigd_ac_guest_abandoned_cart_history_lite: Data: 0.02MB + Index: 0.00MB
fmhgigd_ac_sent_history_lite: Data: 0.02MB + Index: 0.00MB
fmhgigd_commentmeta: Data: 0.06MB + Index: 0.03MB
fmhgigd_comments: Data: 0.06MB + Index: 0.09MB
fmhgigd_ewwwio_images: Data: 0.11MB + Index: 0.08MB
fmhgigd_ewwwio_queue: Data: 0.02MB + Index: 0.02MB
fmhgigd_irecommendthis_votes: Data: 0.02MB + Index: 0.00MB
fmhgigd_itsec_distributed_storage: Data: 0.02MB + Index: 0.02MB
fmhgigd_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB
fmhgigd_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB
fmhgigd_itsec_lockouts: Data: 0.02MB + Index: 0.08MB
fmhgigd_itsec_log: Data: 0.02MB + Index: 0.03MB
fmhgigd_itsec_logs: Data: 0.02MB + Index: 0.09MB
fmhgigd_itsec_temp: Data: 0.02MB + Index: 0.06MB
fmhgigd_links: Data: 0.02MB + Index: 0.02MB
fmhgigd_options: Data: 2.48MB + Index: 0.06MB
fmhgigd_postmeta: Data: 0.31MB + Index: 0.27MB
fmhgigd_posts: Data: 0.08MB + Index: 0.06MB
fmhgigd_termmeta: Data: 0.02MB + Index: 0.03MB
fmhgigd_terms: Data: 0.02MB + Index: 0.03MB
fmhgigd_term_relationships: Data: 0.02MB + Index: 0.02MB
fmhgigd_term_taxonomy: Data: 0.02MB + Index: 0.03MB
fmhgigd_usermeta: Data: 0.02MB + Index: 0.03MB
fmhgigd_users: Data: 0.02MB + Index: 0.05MB
fmhgigd_wc_download_log: Data: 0.02MB + Index: 0.03MB
fmhgigd_wc_webhooks: Data: 0.02MB + Index: 0.02MB
fmhgigd_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
fmhgigd_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
fmhgigd_wsal_metadata: Data: 0.22MB + Index: 0.13MB
fmhgigd_wsal_occurrences: Data: 0.02MB + Index: 0.02MB
fmhgigd_wsal_options: Data: 0.13MB + Index: 0.00MB
fmhgigd_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
fmhgigd_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 52
nav_menu_item: 6
page: 5
post: 4
product: 20
product_variation: 5
revision: 8
scheduled-action: 26
shop_order: 31
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.5.7

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.4.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
</details>

**Comment by FPCSJames** [comment]
I discovered this issue after a client saved a product in the manner described. Their install uses plenty of plugins, a third-party theme, and custom code we've supplied, but I was subsequently able to replicate the issue on a test install with all plugins deactivated and Storefront active. This test install is what's in the WordPress Environment details.

**Comment by mikejolley** [comment]
Thanks, reproduced it. See https://github.com/woocommerce/woocommerce/pull/23131
