### ISSUE TITLE
Database error when populating product lookup table

### ISSUE THREAD

**Issue by rodrigoprimo** [woocommerce/woocommerce#23117]
I got two MySQL errors when running the WP-CLI command to populate lookup tables (`wp wc tool run regenerate_product_lookup_tables --user=1`):

```
 $ wp wc tool run regenerate_product_lookup_tables --user=1
WordPress database error: [Incorrect usage of UPDATE and ORDER BY]
UPDATE wp_wc_product_meta_lookup lookup_table LEFT JOIN wp_postmeta meta1 ON lookup_table.product_id = meta1.post_id AND meta1.meta_key = '_price' SET lookup_table.min_price = meta1.meta_value WHERE meta1.meta_value <> '' ORDER BY meta1.meta_value+0 ASC

WordPress database error: [Incorrect usage of UPDATE and ORDER BY]
UPDATE wp_wc_product_meta_lookup lookup_table LEFT JOIN wp_postmeta meta1 ON lookup_table.product_id = meta1.post_id AND meta1.meta_key = '_price' SET lookup_table.max_price = meta1.meta_value WHERE meta1.meta_value <> '' ORDER BY meta1.meta_value+0 DESC
Success: Updated system_status_tool regenerate_product_lookup_tables.
```

On a quick look, it seems that this is happening because MySQL doesn't support ORDER BY in UPDATE queries with multiple tables. From the page about the UPDATE syntax in MySQL manual:

> For multiple-table syntax, ORDER BY and LIMIT cannot be used. 
(https://dev.mysql.com/doc/refman/5.7/en/update.html)

Below are the links to the parts of the code that are calling those two queries:

https://github.com/woocommerce/woocommerce/blob/e42d40d7027009a43f62413b601a25fbf4125df1/includes/wc-product-functions.php#L1392
https://github.com/woocommerce/woocommerce/blob/e42d40d7027009a43f62413b601a25fbf4125df1/includes/wc-product-functions.php#L1407

cc @mikejolley

**Comment by mikejolley** [comment]
See workaround in https://github.com/woocommerce/woocommerce/pull/23136
