### ISSUE TITLE
WooCommerce Version 3.5.7 Error Message: Sorry, it seems that there are no available payment methods for your state. Please contact us if you require assistance or wish to make alternate arrangements.

### ISSUE THREAD

**Issue by fire3fly** [woocommerce/woocommerce#23116]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by mikejolley** [comment]
This should only occur if no gateways have been setup/configured in WC > Settings > Payments. Go there and enable some payment methods.

Alternatively, check you don't have extensions active which filter or disable available gateways.

Closing this as it lacks details to reproduce a bug and has not been reported by other users. 3.5.7 changed only 1 file unrelated to payment gateways.
