### ISSUE TITLE
WC_Geolocation::geolocate_ip() isn't taking state data from WC_Geolite_Integration::get_country_iso when it is available

### ISSUE THREAD

**Issue by mrbianchi** [woocommerce/woocommerce#23124]
it returns ['state'] = ''

**Comment by mikejolley** [comment]
`get_country_iso` is designed to only return the country ISO code (as documented inline).

`WC_Geolocation::geolocate_ip` uses a variety of methods to get the location however, most of those methods only support country. The maxmind database is the fallback so I'm not sure it would be wise to only expand that one to include state information.

Additonally, I tested a few US IP addresses with MaxMind and could not reliably get a state back. Only the country iso code was returned (as well as continent).

If you'd like to add support for states yourself, you can shortcircuit the geolocation function via the filter `woocommerce_geolocate_ip` and return a country/state there.

Thanks
