### ISSUE TITLE
hide attribute after change slug of attribute 

### ISSUE THREAD

**Issue by dashti011** [woocommerce/woocommerce#23127]
**Describe the bug**
hi 
my wordpress(5.1.1.1) and Wocommerce(3.5.7) install for Farsi(Persian) languhes  and i have products with attribute 
some of my attribute slag is Farsi and this attribute used in my product, until this step every thing is ok and all attribute show in info tab
but i have 3 problem 
1: when i edit a slug of an attribute ( change slug from Farsi to English), the attribute don't show in product info tab any more until edit product and add again att
2: if my slag was in Persian, i cant query attribute to show product by URL
2.1: this URL work ok "https://digikey.ir/family/ic/"
2.2: but this doesn't work "https://digikey.ir/?taxonomy=pa_%DA%A9%DB%8C%D9%81%DB%8C%D8%AA&term=%D8%A7%D8%B1%D8%AC%DB%8C%D9%86%D8%A7%D9%84"
2.3: this also doesn't work and show error ERR_TOO_MANY_REDIRECTS

"https://digikey.ir/?pa_%D8%B3%D8%B1%DB%8C=cmos&pa_%DA%A9%DB%8C%D9%81%DB%8C%D8%AA=%25d8%25a7%25d8%25b1%25d8%25ac%25db%258c%25d9%2586%25d8%25a7%25d9%2584&pa_%D9%88%DB%8C%DA%98%DA%AF%DB%8C-%D8%AE%D8%A7%D8%B5=%25da%25af%25db%258c%25d8%25aanand&product-category=451"
3:but after changea slug lang form Farsi to englsh, the new URL link of attribute work good and show correct product that have this attribute ,but doesn't show att in product tab until edit product and add again that attribute i have edited

 this is my permalink
![image](https://user-images.githubusercontent.com/38144111/54889846-3c13d500-4ec4-11e9-98bf-2be78c65a8ce.png)

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23132

**Comment by dashti011** [comment]
@mikejolley  hi mike , thanks a lot for fixed bug 👍 , but after this bug solved , what happen to perversely att edited ? are they fixed auto to show in info tab product?
> See #23132

**Comment by mikejolley** [comment]
They won't be remapped but you can rename back and back again so fixed query runs.

**Comment by dashti011** [comment]
hi
i tested the problem solved but
the query of URL doesn't work,show main page
None of query work
