### ISSUE TITLE
[WC 3.6.0 beta 1] Fatal error (undefined function before PHP 5.3) in action scheduler on PHP 5.2

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce#23121]
I was doing some testing related to another plugin of my own on a PHP 5.2 test install with the WC 3.6.0 beta 1 release, and got the below whilst visiting another plugin's options page. `json_last_error()` is PHP 5.3+.

```
Notice: Use of undefined constant JSON_ERROR_NONE - assumed 'JSON_ERROR_NONE' in wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php on line 137

Fatal error: Call to undefined function json_last_error() in wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php on line 137
`

**Comment by mikejolley** [comment]
Reported in https://github.com/Prospress/action-scheduler/issues/266 We'll either wait for 2.2.2 or hotfix WC before release. @timmyc

**Comment by timmyc** [comment]
Thanks @mikejolley - I messaged @rrennick earlier today but sounds like you had already pinged him about the issue.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23156
