### ISSUE TITLE
Add a method to get order ID in the order-received and view-order page

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce#23134]
Currently there's no easy way to get just the order id from 'view-order' page  in 'myaccount'

Just to get the order id i need this long code:

```
add_action( 'wp', 'cf_get_order_id', 20 );
function cf_get_order_id() {
    $url = $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'];
    $template_name = strpos($url,'/order-received/') === false ? '/view-order/' : '/order-received/';
    if (strpos($url,$template_name) !== false) {
        $start = strpos($url,$template_name);
        $first_part = substr($url, $start+strlen($template_name));
        $order_id = substr($first_part, 0, strpos($first_part, '/'));
        echo $order_id;
    }
}
```

Please add a hook so its easier to get the order_id

**Comment by mikejolley** [comment]
Hooks let you do stuff, they do not let you 'get' stuff. 

Hooks on those pages, such as `woocommerce_view_order` action, pass the order ID to your hooked in function. Thats probably the way to go?

If not you can get it from WP as it's a query variable. Core uses this:

```
global $wp;
$order = wc_get_order( $wp->query_vars['view-order'] );
```

That would be better than a niche method only for these screens. Use `query_vars`.

Hope that helps

**Comment by UVLabs** [comment]
> Hooks let you do stuff, they do not let you 'get' stuff.
> 
> Hooks on those pages, such as `woocommerce_view_order` action, pass the order ID to your hooked in function. Thats probably the way to go?
> 
> If not you can get it from WP as it's a query variable. Core uses this:
> 
> ```
> global $wp;
> $order = wc_get_order( $wp->query_vars['view-order'] );
> ```
> 
> That would be better than a niche method only for these screens. Use `query_vars`.
> 
> Hope that helps

Thank you for this. Ended up going with the query var route
