### ISSUE TITLE
WooCommerce roles are not translatable

### ISSUE THREAD

**Issue by rodrigoprimo** [woocommerce/woocommerce#23135]
**Describe the bug**
WooCommerce adds the roles `Customer` and `Shop Manager` to WordPress. There are dummy gettext calls to let translators work on those two strings: [includes/class-wc-install.php#L958](https://github.com/woocommerce/woocommerce/blob/520c517410c3b40b2fd18d282de03224f6d25a7a/includes/class-wc-install.php#L958). But the translations for those two strings are never used by WordPress. At least not in the admin page that list users. The problem is that WP uses a function called `translate_user_role()` and this function currently only works with the built-in roles as it only translates strings defined in the `default` text domain.

WP core ticket that is somewhat related to this problem: https://core.trac.wordpress.org/ticket/38736

From [this](https://bbpress.trac.wordpress.org/ticket/2501) ticket, it seems that bbPress implemented a workaround to make their custom roles translatable and it might be possible to implement the same solution for WP. Unfortunatelly, the code changes are not linked to the ticket.

**To Reproduce**
1. Set WC language to pt_BR (or any other language that has translations for the custom roles)
2. Go to /wp-admin/users.php
3. See that in the dropbox "Change role to..." (in pt_BR: "Alterar função para...") the default WP roles are translated, but the WC roles are not.

**Expected behavior**
Translation for WC roles should work.

cc @claudiosanches

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23150
