### ISSUE TITLE
WC_API Callback not working on linux

### ISSUE THREAD

**Issue by bitpalanthon** [woocommerce/woocommerce#23142]
Hi there, We have a problem regarding the WC_API Callback in Linux.

Here's the issue. 
When we setup our plugin in Window (WAMP). The WC_API callback works fine we can access the call back through:

`http://yoursite.com/?wc-api=CALLBACK` and `http://yoursite.com/wc-api/CALLBACK/`

But when we setup the plugin on a Linux environment we can only access the call back through 

`http://yoursite.com/?wc-api=CALLBACK` but we **CANNOT** access it using **`http://yoursite.com/wc-api/CALLBACK/`**

We cannot use the `http://yoursite.com/?wc-api=CALLBACK` callback in our plugin cause we are going to put that callback url on an OAuth redirect url.

Maybe we're missing some configuration here. Can someone help up. Thank you.

**Comment by mikejolley** [comment]
This is down to rewrite rules in WordPress, see Settings > Permalinks

`/?wc-api=CALLBACK` works for all setups.
`/wc-api/CALLBACK/` only works if settings > permalinks is NOT set to 'plain'.

Additonally, redirects need to be functional so check you can access pages etc. 

https://codex.wordpress.org/Using_Permalinks#Using_.22Pretty.22_permalinks

Thanks

**Comment by bitpalanthon** [comment]
Thank you @mikejolley
