### ISSUE TITLE
Add filters to introduction texts in emails

### ISSUE THREAD

**Issue by ericmulder** [woocommerce/woocommerce#23143]
**Is your feature request related to a problem? Please describe.**
We would like to change the introduction texts in the emails. I would prefer to do this without copying the email files to my theme, since I want to keep on track with woocommerce as much as possible. 

**Describe the solution you'd like**
Everything in the email templates is actions and hooks, but would it be possible to add a filter to the introduction texts? So change:
```php 
<p><?php printf( esc_html__( 'Your %s order has been marked complete on our side.', 'woocommerce' ), esc_html( wp_specialchars_decode( get_option( 'blogname' ), ENT_QUOTES ) ) ); ?></p>
```

 to

```php 
<p><?php apply_filters('woocommerce_email_order_introduction_message', printf( esc_html__( 'Your %s order has been marked complete on our side.', 'woocommerce' ), esc_html( wp_specialchars_decode( get_option( 'blogname' ), ENT_QUOTES ) ) )); ?></p>
```
**Describe alternatives you've considered**
Currently we're using a translation override plugin, but this has some drawbacks in performance, and is kind of mis-using this functionality.

**Comment by mikejolley** [comment]
I think for now, stick to translation overrides. I've logged https://github.com/woocommerce/woocommerce/issues/23147 which a system I envision replacing the need to do that and to give store owner full control. Filters on all strings does not scale and is still a technical solution.

Closing in favour of https://github.com/woocommerce/woocommerce/issues/23147

Thanks 👍

**Comment by ericmulder** [comment]
Thanks! Sounds like a good solution.
