### ISSUE TITLE
Moving order to refunded shows refund amount but refund not processed at gateway

### ISSUE THREAD

**Issue by glagonikas** [woocommerce/woocommerce#23144]
**Describe the bug**
When an order is moved to the "Refunded" status, the refund details are automatically added.

At that point, everything looks as if the refund has been processed on the payment processor (Stripe) as well, but in reality it hasn't.

As explained at #10446 moving orders to "refunded" is considered a manual renewal to prevent user errors.

This is confusing for some admins who think the refund has been processed on the processor also.

**To Reproduce**
1. Open an order on admin
2. Change its status to "Refunded"
3. Check the refunded amount at the order totals

**Screenshots**
![order-details](https://user-images.githubusercontent.com/10516403/54989991-92ab0d00-4fb1-11e9-861f-1c8a3115da72.png)

**Expected behavior**
Rather than adding all the refund details, the system should show a warning in the lines of "order set to refunded, but no refund amount specified" and let admins decide if they want to record a refund amount.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WooCommerce v3.5.7 & v3.6.0-beta.1
WooCommerce Stripe Gateway v4.1.15
WordPress v4.9.10
PHP v7.1

**Comment by mikejolley** [comment]
We can improve the working in the note. See https://github.com/woocommerce/woocommerce/pull/23149

**Comment by glagonikas** [comment]
This PR certainly improves things. Thanks
