### ISSUE TITLE
Avoid using "PUT" or "DELETE" HTTP methods for REST endpoints

### ISSUE THREAD

**Issue by DanReyLop** [woocommerce/woocommerce#23155]
The WooCommerce REST API uses all the HTTP verbs (`GET`, `POST`, `PUT`, `DELETE`). Also, we've found (props @dechov for the find) that WooCommerce Admin is already relying on some `PUT` REST endpoints. [Here](https://github.com/woocommerce/woocommerce-admin/blob/4c6e02a927332515272c5585c6e506d551d2088c/client/wc-api/notes/operations.js#L84), for example.

In WooCommerce Services, we've had user reports in the past regarding endpoints like those. An `apache2` server, with `mod_security` configured with the most popular set of settings, will forbid any `PUT` or `DELETE` HTTP requests to hit the server at all.

Here's the issue, with more context: https://github.com/Automattic/woocommerce-services/issues/930

I know changing all endpoints to be `GET`/`POST` would mean sacrificing a bit of readability, but it would be in favour of having greater compatibility with a wider variety of hosts. Some may have `mod_security` enabled by default, or can be configured by clicking a checkbox that says something vague like `Enable security features` (who wouldn't click that?).

What do you folks think about this? If you think we should change the WooCommerce REST endpoints, should this issue be raised in WordPress core too, since they're also using `PUT/DELETE` on the built-in endpoints?

cc/ @woocommerce/isotope since WooCommerce Admin is using some `PUT` endpoints.

**Comment by mikejolley** [comment]
@DanReyLop Not sure if you're aware of this but if compatibility is a concern, there is an available override:

https://github.com/woocommerce/woocommerce/wiki/Getting-started-with-the-REST-API#server-does-not-support-postdeleteput

This is also in the WP REST API:

https://developer.wordpress.org/rest-api/using-the-rest-api/global-parameters/#_method-or-x-http-method-override-header

Personally I'd prefer those overrides that are available to be used, rather than sacrifice standards and readability. I'd also prefer WC core was consistent with WP in that the verbs are supported.

**Comment by mikejolley** [comment]
cc @claudiosanches

**Comment by DanReyLop** [comment]
> Not sure if you're aware of this but if compatibility is a concern, there is an available override:

I was just reading about it right now, looks like this issue is better suited for the `WooCommerce Admin` repo :)

> Personally I'd prefer those overrides that are available to be used, rather than sacrifice standards and readability. I'd also prefer WC core was consistent with WP in that the verbs are supported.

Agreed. The `_method` override seems to be the best solution. I found an issue saying that Gutenberg doesn't use it so it doesn't work out-of-the-box in Siteground: https://github.com/WordPress/gutenberg/issues/2704#issuecomment-329231370

It would be great if WooCommerce Admin doesn't make the same mistake. I haven't found any `PUT` or `DELETE` AJAX call in WooCommerce core, so this issue doesn't make sense in this repo (unless you want to double-check).

**Comment by timmyc** [comment]
Thanks for the info here @DanReyLop - would you mind opening up an issue on the woocommerce-admin repo?

**Comment by DanReyLop** [comment]
Done: https://github.com/woocommerce/woocommerce-admin/issues/1934

I'm closing this one since WooCommerce core isn't doing anything wrong.
