### ISSUE TITLE
Global Product Attribute Type field is not showing

### ISSUE THREAD

**Issue by Wpshouter** [woocommerce/woocommerce#23169]
Just installed Woo commerce in a new website. But I don;t ind the attribute type field. I have been using woocomerce for a long time on a lot of website. I don;t understand why this is happening to this site.

**Screenshots**
https://prnt.sc/n4p51t

As you cans ee the screenshot there is not such filed from where I can select attribute type. I deactivated all plugins. No success.

The plugin currently there are

Smart Slider 3
Sticky Genesis Topbar
Thrive Architect
WooCommerce
WooCommerce Product Add-ons
WP File Manager
Please let me know.
Regards,
Jaber

**Comment by GlennMartin1** [comment]
Attribute type has been removed for over a year (since 3.3.0). This is not a bug.

The rationale for removal is provided here: https://github.com/woocommerce/woocommerce/issues/18045.

**Comment by Wpshouter** [comment]
Then how can I add images with attributes ? And this screenshot is taken from a site there is attribute type and options to add image to attribute. How it is here is it is removed?

https://prnt.sc/n4sduu

**Comment by mikejolley** [comment]
If an extension adds a custom attribute type e.g. swatches/images, the item comes back. This is extension territory.

Thanks
