### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function get_name()

### ISSUE THREAD

**Issue by yeshansachithak** [woocommerce/woocommerce#23160]
I have developed a plugin which is not working after the latest upgrade. Getting below error. 

```log
Fatal error: Uncaught Error: Call to a member function get_name() on boolean in /www/wp-content/plugins/my-plugin/admin/class-my-plugin-admin.php:938 Stack trace: #0 /www/wp-content/plugins/my-plugin/admin/class-my-plugin-admin.php(1020): Wc_Local_Schedule_N_Delivery_Admin->get_order_report_data('', '', '', '') #1 /www/wp-includes/class-wp-hook.php(286): Wc_Local_Schedule_N_Delivery_Admin->render_wc_lsnd_admin_order_reports_page('') #2 /www/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #3 /www/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #4 /www/wp-admin/admin.php(253): do_action('woocommerce_pag...') #5 {main} thrown in /www/wp-content/plugins/my-plugin/admin/class-my-plugin-admin.php on line 938
```

line 938 

```php
$html .= '<table id="order_reports_result_tbl" class="form-table">';
        if (!empty($order_reports)) {
            foreach ($order_reports as $order_report) {
                $order_id = $order_report->order_id;
                // Get an instance of the the WC_Order Object
                $order = wc_get_order($order_id);
                $html .= '<tr class="border_bottom">';
                $html .= '<td class="tbl_row first_row">' . $order_id . '</td>';
                $html .= '<td class="tbl_row">';
                // Iterating through each "line" items in the order
                foreach ($order->get_items() as $item_id => $item_data) {
                    // Get an instance of corresponding the WC_Product object
                    $product = $item_data->get_product();
                    $product_name = $product->get_name(); // Get the product name
                    $item_quantity = $item_data->get_quantity(); // Get the item quantity
                    //$item_total = $product->get_total(); // Get the item line total
                    // Displaying this data (to check)
                    $html .= $product_name . '(' . $item_quantity . ')' . '<br/>';
                }
                $html .= '</td>';
                $html .= '<td class="tbl_row">' . $order->get_billing_first_name() . '<br/>' . $order->get_billing_last_name() . '<br/>' . $order->get_billing_address_1() . '<br/>' . $order->get_billing_state() . '<br/>' . $order->get_billing_country() . '<br/>' . $order->get_billing_phone() . '<br/>' . '</td>';
                //$html .= '<td class="tbl_row">' . $order->get_order_currency() . ' ' . $order->get_total() . '</td>';
                $html .= '<td class="tbl_row">' . $order->get_currency() . ' ' . $order->get_total() . '</td>';
                $html .= '<td class="tbl_row">' . $order->get_customer_note() . '</td>';
                $html .= '<td class="tbl_row">' . $order->get_meta('_custom_schedule_timings') . '</td>';
                $html .= '</tr>';
            }
        } else {
            $html .= '<tr class="border_bottom">';
            $html .= '<td class="tbl_row" colspan="6">No record found</td>';
            $html .= '</tr>';
        }
        $html .= '</table>';
```

**WordPress Environment**
<details>
### WordPress Environment ###

Home URL: https://www.mysite.com
Site URL: https://www.mysite.com
WC Version: 3.5.7
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.14 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: 5.6.41-84.1
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.7
WC Database Prefix: ghuae_
Total Database Size: 227.60MB
Database Data Size: 153.23MB
Database Index Size: 74.37MB
ghuae_woocommerce_sessions: Data: 38.06MB + Index: 1.52MB
ghuae_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
ghuae_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
ghuae_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
ghuae_woocommerce_order_items: Data: 2.52MB + Index: 1.52MB
ghuae_woocommerce_order_itemmeta: Data: 12.52MB + Index: 11.03MB
ghuae_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
ghuae_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
ghuae_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
ghuae_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
ghuae_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
ghuae_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
ghuae_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
ghuae_woocommerce_log: Data: 0.00MB + Index: 0.00MB
ghuae_commentmeta: Data: 0.02MB + Index: 0.03MB
ghuae_comments: Data: 11.52MB + Index: 10.09MB
ghuae_links: Data: 0.02MB + Index: 0.02MB
ghuae_mywebtonetperfstatsresults: Data: 0.00MB + Index: 0.00MB
ghuae_mywebtonetqtest: Data: 0.00MB + Index: 0.00MB
ghuae_options: Data: 6.22MB + Index: 0.13MB
ghuae_postmeta: Data: 45.52MB + Index: 23.89MB
ghuae_posts: Data: 10.06MB + Index: 1.31MB
ghuae_termmeta: Data: 0.05MB + Index: 0.03MB
ghuae_terms: Data: 0.02MB + Index: 0.03MB
ghuae_term_relationships: Data: 0.25MB + Index: 0.14MB
ghuae_term_taxonomy: Data: 0.02MB + Index: 0.03MB
ghuae_usermeta: Data: 22.55MB + Index: 23.09MB
ghuae_users: Data: 1.52MB + Index: 0.94MB
ghuae_wc_avatars_cache: Data: 0.00MB + Index: 0.02MB
ghuae_wc_comments_subscription: Data: 0.00MB + Index: 0.01MB
ghuae_wc_download_log: Data: 0.00MB + Index: 0.00MB
ghuae_wc_follow_users: Data: 0.00MB + Index: 0.00MB
ghuae_wc_lsnd_cities: Data: 0.02MB + Index: 0.00MB
ghuae_wc_lsnd_countries: Data: 0.02MB + Index: 0.00MB
ghuae_wc_lsnd_order_report: Data: 0.05MB + Index: 0.00MB
ghuae_wc_lsnd_schedules: Data: 0.02MB + Index: 0.00MB
ghuae_wc_phrases: Data: 0.01MB + Index: 0.02MB
ghuae_wc_users_voted: Data: 0.00MB + Index: 0.00MB
ghuae_wc_webhooks: Data: 0.00MB + Index: 0.00MB
ghuae_wpml_mails: Data: 1.61MB + Index: 0.00MB
ghuae_yoast_seo_links: Data: 0.31MB + Index: 0.08MB
ghuae_yoast_seo_meta: Data: 0.12MB + Index: 0.13MB

### Post Type Counts ###

amn_exact-metrics: 1
amn_mi-lite: 1
attachment: 1589
elementor_library: 7
mc4wp-form: 2
nav_menu_item: 73
page: 20
post: 45
product: 1066
recipes: 2
revision: 137
shop_order: 4733
spucpt: 1
wpdiscuz_form: 1
wpmm_theme: 1
wysijap: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Query Monitor: by John Blackbourn – 3.3.4
Elementor Pro: by Elementor.com – 2.4.8
Elementor: by Elementor.com – 2.5.10
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.4.2
Mailchimp for WordPress: by ibericode – 4.5.0
Max Mega Menu: by megamenu.com – 2.6
MIGS Payment Gateway WooCommerce: by OsPayment – 2.0 – Not tested with the active version of WooCommerce
Nav Menu Roles: by Kathy Darling – 1.9.3
Popups - WordPress Popup: by timersys – 1.9.3.5
WC Local Schedule & Delivery: by Yeshan Perera – 1.2.0
WooCommerce Xero Integration: by WooCommerce – 1.7.10 – 1.7.16 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.5.7
Yoast SEO: by Team Yoast – 10.0.1
WP Mail Logging: by Christian Zöller – 1.8.5
WP Migrate DB: by Delicious Brains – 1.0.10
WP Rocket: by WP Media – 3.2.6
wpDiscuz: by gVectors Team (A. Chakhoyan
G. Zakaryan
H. Martirosyan) – 5.3.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AED (AED )
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #4 - /shop/
Cart: ❌ Page does not contain the shortcode.
Checkout: ❌ Page does not contain the shortcode.
My account: ❌ Page does not contain the shortcode.
Terms and conditions: #371 - /term-conditions/

### Theme ###

Name: WP Bootstrap Starter Child
Version: 1.2.1
Author URL: https://afterimagedesigns.com/
Child Theme: ✔
Parent Theme Name: WP Bootstrap Starter
Parent Theme Version: 3.2.0
Parent Theme Author URL: https://afterimagedesigns.com/
WooCommerce Support: ✔

### Templates ###

Overrides: wp-bootstrap-starter-child/woocommerce/cart/cart.php
wp-bootstrap-starter-child/woocommerce/checkout/form-checkout.php
wp-bootstrap-starter-child/woocommerce/myaccount/form-login.php
wp-bootstrap-starter-child/woocommerce/myaccount/my-address.php
wp-bootstrap-starter-child/woocommerce/order/order-details-item.php
</details>

**Comment by mikejolley** [comment]
The code above lacks handling for `$product = $item_data->get_product();` which can return false if the line item is not associated with a valid product, or the product no longer exists. That needs correcting.
