### ISSUE TITLE
[3.6] wp_count_terms() returning invalid counts

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce#23171]
**Describe the bug**
While testing the new `Products by Attributes` block for 3.6, I stumbled upon a bug that appears to have been introduced in #22570

The attributes block uses one of the new internal-only REST endpoints to grab a list of product attributes, and their associated counts/usage to render a selector in the UI. This [particular line](https://github.com/woocommerce/woocommerce/blob/master/includes/api/wc-blocks/class-wc-rest-blocks-product-attributes-controller.php#L147) is where `wp_count_terms()` is being called. But I've verified that the bug is happening outside of the context of the REST API, and in my testing [this line](https://github.com/woocommerce/woocommerce/blob/16a0a3e27ec0af857e8dda95da6e70c0901bbe46/includes/wc-term-functions.php#L38) is what seems to be causing the issue. If I comment that out, the REST endpoint returns the proper term count as expected.

If I manually test `wp_count_terms()` for a product attribute in `3.5.7` - the associated term count is correctly returned. When performing the same test against `master` or `release/3.6` it fails / returns 0.

This bug results in the Products by Attribute block not being usable in 3.6 - but I'm not certain what other issues the regression in `wp_count_terms()` might cause elsewhere, but guessing it could be problematic.

/cc @mikejolley @ryelle 

**To Reproduce**
1. Setup a new product attribute - i used "color"
2. Add three terms to the attribute, or however many you please
3. Output `wc_count_terms( your_term_name )` somewhere, note 0 is returned
4. Comment out the line noted above `$defaults['meta_key']              = 'order'; // phpcs:ignore` in `wc-term-functions.php` and verify the correct number of terms is output.
4. Perform the same steps on 3.5.7 and verify the correct number is returned.

**Expected behavior**
I expected `wp_count_terms()` to still function as it did in 3.5.x

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
5.1.1

**Comment by mikejolley** [comment]
@timmyc ping me later when you're online - there was a similar issue reported by @ryelle a few weeks back when the update process was not ran to migrate meta data which may be effecting this.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23194
