### ISSUE TITLE
Realtime notification

### ISSUE THREAD

**Issue by psd24** [woocommerce/woocommerce#23170]
When I get a command I always have to be aware that the ticket is printed or send me an email. Many times I can not see it and that is a problem for me.

The solution that I see is to implement relatime notififaciones (whatsapp, telegram ...) so that I can receive it instantly and thus be able to see the order.

**Comment by mikejolley** [comment]
Hi,

For realtime notifications on mobile, there is a mobile app: https://woocommerce.com/mobile/

Thanks
