### ISSUE TITLE
woocommerce kicks students out of wpcourseware

### ISSUE THREAD

**Issue by KarinMaantijd** [woocommerce/woocommerce#23187]
Using woocommerce with avada, wpcourseware and paid memberships pro.

Every time (!) an already existing student  (who bought their course via woocommerce) buys any new product, the student is completely kicked out of the wpcourseware environment.

The new product can be anything, so ranging from a ''real'' book or goodie to a virtual paid email series or e-book.

 **Expected behavior**
I would like to have students being able to buy any number of any product without being thrown out of their previous wpcourseware purchase.

**Isolating the problem (mark completed items with an [x]):**
This can not be done, as it is the combination of plugins that is the problem; woocommerce on itself works like a gem!

**WordPress Environment**
`
### WordPress Environment ###

Home URL: https://maantijd.nl
Site URL: https://maantijd.nl
WC Version: 3.5.7
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.14
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 3000
cURL Version: 7.19.7
NSS/3.27.1

SUHOSIN Installed: –
MySQL Version: ❌ 5.1.73 - Wij adviseren een minimum MySQL-versie 5.6. Bekijk: WordPress vereisten
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.7
WC Database Prefix: wp_
Totale databasegrootte: 308.55MB
Database datagrootte: 270.30MB
Database index grootte: 38.25MB
wp_woocommerce_sessions: Data: 36.62MB + Index: 1.11MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.01MB + Index: 0.03MB
wp_woocommerce_order_items: Data: 0.17MB + Index: 0.12MB
wp_woocommerce_order_itemmeta: Data: 1.08MB + Index: 0.76MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_ahm_download_stats: Data: 0.00MB + Index: 0.00MB
wp_ahm_emails: Data: 0.00MB + Index: 0.00MB
wp_aiowps_events: Data: 22.02MB + Index: 1.94MB
wp_aiowps_failed_logins: Data: 0.12MB + Index: 0.03MB
wp_aiowps_global_meta: Data: 10.45MB + Index: 0.00MB
wp_aiowps_login_activity: Data: 0.42MB + Index: 0.09MB
wp_aiowps_login_lockdown: Data: 0.06MB + Index: 0.01MB
wp_aiowps_permanent_block: Data: 0.00MB + Index: 0.00MB
wp_amelia_appointments: Data: 0.02MB + Index: 0.03MB
wp_amelia_categories: Data: 0.02MB + Index: 0.00MB
wp_amelia_coupons: Data: 0.02MB + Index: 0.00MB
wp_amelia_coupons_to_services: Data: 0.02MB + Index: 0.03MB
wp_amelia_customer_bookings: Data: 0.02MB + Index: 0.05MB
wp_amelia_customer_bookings_to_extras: Data: 0.02MB + Index: 0.03MB
wp_amelia_custom_fields: Data: 0.02MB + Index: 0.00MB
wp_amelia_custom_fields_options: Data: 0.02MB + Index: 0.02MB
wp_amelia_custom_fields_services: Data: 0.02MB + Index: 0.03MB
wp_amelia_extras: Data: 0.02MB + Index: 0.02MB
wp_amelia_galleries: Data: 0.02MB + Index: 0.00MB
wp_amelia_locations: Data: 0.02MB + Index: 0.00MB
wp_amelia_locations_views: Data: 0.02MB + Index: 0.03MB
wp_amelia_notifications: Data: 0.02MB + Index: 0.00MB
wp_amelia_notifications_log: Data: 0.02MB + Index: 0.05MB
wp_amelia_notifications_sms_history: Data: 0.02MB + Index: 0.02MB
wp_amelia_payments: Data: 0.02MB + Index: 0.02MB
wp_amelia_providers_to_daysoff: Data: 0.02MB + Index: 0.03MB
wp_amelia_providers_to_google_calendar: Data: 0.00MB + Index: 0.00MB
wp_amelia_providers_to_locations: Data: 0.02MB + Index: 0.05MB
wp_amelia_providers_to_periods: Data: 0.02MB + Index: 0.03MB
wp_amelia_providers_to_periods_services: Data: 0.02MB + Index: 0.05MB
wp_amelia_providers_to_services: Data: 0.02MB + Index: 0.05MB
wp_amelia_providers_to_specialdays: Data: 0.02MB + Index: 0.03MB
wp_amelia_providers_to_specialdays_periods: Data: 0.02MB + Index: 0.03MB
wp_amelia_providers_to_specialdays_periods_services: Data: 0.02MB + Index: 0.05MB
wp_amelia_providers_to_timeouts: Data: 0.02MB + Index: 0.03MB
wp_amelia_providers_to_weekdays: Data: 0.02MB + Index: 0.03MB
wp_amelia_providers_views: Data: 0.02MB + Index: 0.03MB
wp_amelia_services: Data: 0.02MB + Index: 0.02MB
wp_amelia_services_views: Data: 0.02MB + Index: 0.03MB
wp_amelia_users: Data: 0.02MB + Index: 0.03MB
wp_commentmeta: Data: 0.01MB + Index: 0.01MB
wp_comments: Data: 0.88MB + Index: 0.51MB
wp_eme_answers: Data: 0.01MB + Index: 0.02MB
wp_eme_bookings: Data: 0.03MB + Index: 0.01MB
wp_eme_categories: Data: 0.00MB + Index: 0.00MB
wp_eme_countries: Data: 0.00MB + Index: 0.00MB
wp_eme_dgroups: Data: 0.00MB + Index: 0.00MB
wp_eme_discounts: Data: 0.00MB + Index: 0.00MB
wp_eme_events: Data: 0.73MB + Index: 0.00MB
wp_eme_events_cf: Data: 0.00MB + Index: 0.00MB
wp_eme_fieldtypes: Data: 0.00MB + Index: 0.00MB
wp_eme_formfields: Data: 0.00MB + Index: 0.00MB
wp_eme_groups: Data: 0.00MB + Index: 0.00MB
wp_eme_holidays: Data: 0.00MB + Index: 0.00MB
wp_eme_locations: Data: 0.00MB + Index: 0.00MB
wp_eme_locations_cf: Data: 0.00MB + Index: 0.00MB
wp_eme_mailings: Data: 0.00MB + Index: 0.00MB
wp_eme_members: Data: 0.00MB + Index: 0.00MB
wp_eme_memberships: Data: 0.00MB + Index: 0.00MB
wp_eme_memberships_cf: Data: 0.00MB + Index: 0.00MB
wp_eme_mqueue: Data: 0.00MB + Index: 0.00MB
wp_eme_payments: Data: 0.02MB + Index: 0.01MB
wp_eme_people: Data: 0.02MB + Index: 0.01MB
wp_eme_recurrence: Data: 0.00MB + Index: 0.00MB
wp_eme_states: Data: 0.00MB + Index: 0.00MB
wp_eme_templates: Data: 0.00MB + Index: 0.00MB
wp_eme_usergroups: Data: 0.00MB + Index: 0.00MB
wp_geodir_attachments: Data: 0.03MB + Index: 0.01MB
wp_geodir_claim: Data: 0.02MB + Index: 0.00MB
wp_geodir_countries: Data: 0.03MB + Index: 0.00MB
wp_geodir_custom_fields: Data: 0.01MB + Index: 0.00MB
wp_geodir_custom_sort_fields: Data: 0.00MB + Index: 0.00MB
wp_geodir_event_schedule: Data: 0.04MB + Index: 0.03MB
wp_geodir_gd_event_detail: Data: 0.18MB + Index: 0.03MB
wp_geodir_gd_place_detail: Data: 0.00MB + Index: 0.00MB
wp_geodir_location_seo: Data: 0.00MB + Index: 0.00MB
wp_geodir_post_icon: Data: 0.03MB + Index: 0.00MB
wp_geodir_post_locations: Data: 0.02MB + Index: 0.00MB
wp_geodir_post_neighbourhood: Data: 0.00MB + Index: 0.00MB
wp_geodir_post_review: Data: 0.00MB + Index: 0.00MB
wp_geodir_term_meta: Data: 0.03MB + Index: 0.00MB
wp_groups_capability: Data: 0.01MB + Index: 0.02MB
wp_groups_group: Data: 0.00MB + Index: 0.00MB
wp_groups_group_capability: Data: 0.00MB + Index: 0.00MB
wp_groups_user_capability: Data: 0.00MB + Index: 0.00MB
wp_groups_user_group: Data: 0.02MB + Index: 0.05MB
wp_layerslider: Data: 0.07MB + Index: 0.00MB
wp_layerslider_revisions: Data: 0.00MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_mailpoet_custom_fields: Data: 0.00MB + Index: 0.00MB
wp_mailpoet_dynamic_segment_filters: Data: 0.00MB + Index: 0.00MB
wp_mailpoet_forms: Data: 0.02MB + Index: 0.00MB
wp_mailpoet_log: Data: 0.00MB + Index: 0.00MB
wp_mailpoet_mapping_to_external_entities: Data: 0.07MB + Index: 0.08MB
wp_mailpoet_newsletters: Data: 2.32MB + Index: 0.00MB
wp_mailpoet_newsletter_links: Data: 1.49MB + Index: 0.68MB
wp_mailpoet_newsletter_option: Data: 0.01MB + Index: 0.01MB
wp_mailpoet_newsletter_option_fields: Data: 0.00MB + Index: 0.01MB
wp_mailpoet_newsletter_posts: Data: 0.00MB + Index: 0.00MB
wp_mailpoet_newsletter_segment: Data: 0.00MB + Index: 0.01MB
wp_mailpoet_newsletter_templates: Data: 22.69MB + Index: 0.00MB
wp_mailpoet_premium_newsletter_extra_data: Data: 0.00MB + Index: 0.01MB
wp_mailpoet_scheduled_tasks: Data: 0.14MB + Index: 0.06MB
wp_mailpoet_scheduled_task_subscribers: Data: 6.68MB + Index: 7.88MB
wp_mailpoet_segments: Data: 0.00MB + Index: 0.00MB
wp_mailpoet_sending_queues: Data: 95.88MB + Index: 0.08MB
wp_mailpoet_settings: Data: 0.01MB + Index: 0.00MB
wp_mailpoet_statistics_clicks: Data: 0.26MB + Index: 0.38MB
wp_mailpoet_statistics_forms: Data: 0.03MB + Index: 0.05MB
wp_mailpoet_statistics_newsletters: Data: 0.91MB + Index: 1.42MB
wp_mailpoet_statistics_opens: Data: 0.51MB + Index: 1.13MB
wp_mailpoet_statistics_unsubscribes: Data: 0.00MB + Index: 0.02MB
wp_mailpoet_stats_notifications: Data: 0.00MB + Index: 0.00MB
wp_mailpoet_subscribers: Data: 0.42MB + Index: 0.29MB
wp_mailpoet_subscriber_custom_field: Data: 0.00MB + Index: 0.00MB
wp_mailpoet_subscriber_ips: Data: 0.00MB + Index: 0.01MB
wp_mailpoet_subscriber_segment: Data: 0.24MB + Index: 0.27MB
wp_mailpoet_user_flags: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 9.02MB + Index: 1.31MB
wp_pmpro_discount_codes: Data: 0.00MB + Index: 0.00MB
wp_pmpro_discount_codes_levels: Data: 0.00MB + Index: 0.00MB
wp_pmpro_discount_codes_uses: Data: 0.00MB + Index: 0.00MB
wp_pmpro_memberships_categories: Data: 0.00MB + Index: 0.00MB
wp_pmpro_memberships_pages: Data: 0.00MB + Index: 0.01MB
wp_pmpro_memberships_users: Data: 0.05MB + Index: 0.08MB
wp_pmpro_membership_levelmeta: Data: 0.00MB + Index: 0.02MB
wp_pmpro_membership_levels: Data: 0.02MB + Index: 0.01MB
wp_pmpro_membership_orders: Data: 0.00MB + Index: 0.02MB
wp_postmeta: Data: 19.41MB + Index: 8.65MB
wp_posts: Data: 17.50MB + Index: 1.31MB
wp_revslider_css: Data: 0.09MB + Index: 0.01MB
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.00MB + Index: 0.00MB
wp_revslider_settings: Data: 0.00MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.01MB + Index: 0.00MB
wp_revslider_slides: Data: 0.06MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
wp_riddleuser: Data: 0.00MB + Index: 0.00MB
wp_sl_setting: Data: 0.02MB + Index: 0.00MB
wp_sl_tag: Data: 0.02MB + Index: 0.00MB
wp_store_locator: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.01MB
wp_terms: Data: 0.02MB + Index: 0.05MB
wp_term_relationships: Data: 0.02MB + Index: 0.04MB
wp_term_taxonomy: Data: 0.03MB + Index: 0.03MB
wp_usermeta: Data: 6.52MB + Index: 6.89MB
wp_users: Data: 0.11MB + Index: 0.10MB
wp_watu_answer: Data: 0.00MB + Index: 0.00MB
wp_watu_grading: Data: 0.00MB + Index: 0.00MB
wp_watu_master: Data: 0.00MB + Index: 0.00MB
wp_watu_question: Data: 0.00MB + Index: 0.00MB
wp_watu_takings: Data: 0.00MB + Index: 0.00MB
wp_wcpdf_invoice_number: Data: 0.01MB + Index: 0.01MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_wpcw_certificates: Data: 0.02MB + Index: 0.00MB
wp_wpcw_couponmeta: Data: 0.00MB + Index: 0.00MB
wp_wpcw_coupons: Data: 0.00MB + Index: 0.00MB
wp_wpcw_coursemeta: Data: 0.22MB + Index: 0.01MB
wp_wpcw_courses: Data: 0.09MB + Index: 0.02MB
wp_wpcw_logs: Data: 0.00MB + Index: 0.00MB
wp_wpcw_member_levels: Data: 0.02MB + Index: 0.00MB
wp_wpcw_modules: Data: 0.06MB + Index: 0.00MB
wp_wpcw_notes: Data: 0.00MB + Index: 0.00MB
wp_wpcw_ordermeta: Data: 0.00MB + Index: 0.00MB
wp_wpcw_orders: Data: 0.00MB + Index: 0.00MB
wp_wpcw_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wp_wpcw_order_items: Data: 0.00MB + Index: 0.00MB
wp_wpcw_question_random_lock: Data: 0.02MB + Index: 0.00MB
wp_wpcw_question_tags: Data: 0.02MB + Index: 0.00MB
wp_wpcw_question_tags_map: Data: 0.02MB + Index: 0.00MB
wp_wpcw_queue_dripfeed: Data: 0.02MB + Index: 0.00MB
wp_wpcw_quizzes: Data: 0.02MB + Index: 0.00MB
wp_wpcw_quizzes_feedback: Data: 0.02MB + Index: 0.00MB
wp_wpcw_quizzes_questions: Data: 0.02MB + Index: 0.00MB
wp_wpcw_quizzes_questions_map: Data: 0.02MB + Index: 0.02MB
wp_wpcw_sessions: Data: 0.00MB + Index: 0.00MB
wp_wpcw_subscriptions: Data: 0.00MB + Index: 0.00MB
wp_wpcw_units_meta: Data: 0.14MB + Index: 0.00MB
wp_wpcw_user_courses: Data: 0.02MB + Index: 0.00MB
wp_wpcw_user_progress: Data: 1.19MB + Index: 0.00MB
wp_wpcw_user_progress_quizzes: Data: 0.33MB + Index: 0.00MB
wp_wpfront_ure_content_shortcodes: Data: 0.00MB + Index: 0.00MB
wp_wpfront_ure_login_redirect: Data: 0.00MB + Index: 0.00MB
wp_wpfront_ure_menu_editor: Data: 0.03MB + Index: 0.01MB
wp_wpfront_ure_options: Data: 0.02MB + Index: 0.00MB
wp_wpfront_ure_post_type_permissions: Data: 0.01MB + Index: 0.00MB
wp_wysija_campaign: Data: 0.01MB + Index: 0.00MB
wp_wysija_campaign_list: Data: 0.00MB + Index: 0.01MB
wp_wysija_custom_field: Data: 0.00MB + Index: 0.00MB
wp_wysija_email: Data: 7.71MB + Index: 0.00MB
wp_wysija_email_user_stat: Data: 0.97MB + Index: 0.93MB
wp_wysija_email_user_url: Data: 0.15MB + Index: 0.16MB
wp_wysija_form: Data: 0.01MB + Index: 0.00MB
wp_wysija_list: Data: 0.00MB + Index: 0.00MB
wp_wysija_queue: Data: 0.04MB + Index: 0.08MB
wp_wysija_subscriber_ips: Data: 0.00MB + Index: 0.00MB
wp_wysija_url: Data: 0.01MB + Index: 0.00MB
wp_wysija_url_mail: Data: 0.01MB + Index: 0.01MB
wp_wysija_user: Data: 0.37MB + Index: 0.17MB
wp_wysija_user_field: Data: 0.00MB + Index: 0.00MB
wp_wysija_user_history: Data: 0.00MB + Index: 0.00MB
wp_wysija_user_list: Data: 0.07MB + Index: 0.14MB
wp_yoast_seo_links: Data: 0.22MB + Index: 0.08MB
wp_yoast_seo_meta: Data: 0.03MB + Index: 0.03MB

### Post Type Counts ###

amn_mi-lite: 3
attachment: 2241
avada_faq: 8
avada_portfolio: 6
course_unit: 1060
fusion_element: 1
gd_event: 149
mailpoet_page: 1
nav_menu_item: 42
oembed_cache: 5
page: 157
post: 78
post_type_questionna: 3
product: 42
pronamic_gateway: 1
pronamic_payment: 1169
revision: 774
shop_coupon: 17
shop_order: 1318
slide: 15
themefusion_elastic: 2
tribe_events: 2
tribe_organizer: 2
tribe_rsvp_attendees: 1
tribe_rsvp_tickets: 1
tribe_venue: 2
wpcw_course: 25
wpdmpro: 2
wysijap: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (49) ###

LayerSlider WP: door Kreatura Media – 6.8.2
Advanced TinyMCE Configuration: door Andrew Ozz – 1.4
Akismet Anti-Spam: door Automattic – 4.1.1
All In One WP Security: door Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.3.8.3

Amelia: door TMS – 1.0.3
Easy Coming Soon: door Ankit Agarwal
Priyanshu Mittal – 2.3

Email Gebruikers: door Mike Walsh & MarvinLabs – 4.8.8
Events Made Easy: door Franky Van Liedekerke – 2.1.13
Fusion Builder: door ThemeFusion – 1.9
Fusion Core: door ThemeFusion – 3.9
GeoDirectory Claim Manager: door GeoDirectory – 1.3.2
GeoDirectory Custom Post Types: door GeoDirectory – 1.3.4
GeoDirectory Events: door GeoDirectory – 1.4.5
GeoDirectory Location Manager: door GeoDirectory – 1.4.3
GeoDirectory: door GeoDirectory – 1.6.38
Google Analytics for WordPress by MonsterInsights: door MonsterInsights – 7.4.2
Groepen: door itthinx – 2.6.0
Image Widget: door Modern Tribe
Inc. – 4.4.7

MailPoet Paid Memberships Pro Add-on: door Sebs Studio – 1.0.0
MailPoet 3 Premium (New): door MailPoet – 3.0.46
MailPoet 3 (New): door MailPoet – 3.22.0
Options Framework: door Devin Price – 1.8.5
WP Courseware - Paid Memberships Pro Add On: door Fly Plugins – 1.2
Paid Memberships Pro: door Stranger Studios – 2.0.4
Paid Memberships Pro - Email Templates Add On: door Paid Memberships Pro – 0.7.2
Paid Memberships Pro - WooCommerce Add On: door Stranger Studios – 1.6.1 – Niet getest met de actieve versie van WooCommerce
Pronamic Pay: door Pronamic – 5.5.5
Really Simple SSL pro: door Rogier Lankhorst – 2.0.24
Really Simple SSL: door Rogier Lankhorst
Mark Wolters – 3.1.5

Slider Revolution: door ThemePunch – 5.4.8.3
Theme My Login: door Theme My Login – 7.0.13
TinyMCE Advanced: door Andrew Ozz – 5.1.0
Username Changer: door Daniel J Griffiths – 3.1.3
WaterWoo PDF: door Little Package – 2.3
WooCommerce External Product New Tab: door Stuart Duff – 1.0.2 – Niet getest met de actieve versie van WooCommerce
Woo Commmerce Addon for WP Courseware: door Fly Plugins – 1.3.6
WooCommerce PDF Invoices & Packing Slips: door Ewout Fernhout – 2.2.11
WooCommerce: door Automattic – 3.5.7
WooMailpoet: door Lucy Eind – 3.2 – Niet getest met de actieve versie van WooCommerce
Yoast SEO: door Team Yoast – 10.0.1
Wordpress WeFact plugin: door Tussendoor internet & marketing – 2.4.3
WP Bouncer: door strangerstudios
Andrew Norcross – 1.4

WP Content Copy Protection: door Tyche Softwares – 1.1.8.7
WP Courseware: door Fly Plugins – 4.5.2
WP Maximum Execution Time Exceeded: door Johnnie J. O'Dell Jr. – 1.0.2
WPDM - TinyMce Button: door Shaon – 2.5.0
WPFront User Role Editor: door Syam Mohan – 2.14.2
MailPoet 2 Premium: door MailPoet – 2.7.9
MailPoet 2: door MailPoet – 2.11

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Winkelbasis: #4097 - /shop/
Winkelmand: #4098 - /cart/
Afrekenen: #4099 - /checkout/
Mijn account: #4100 - /my-account/
Algemene voorwaarden: #12191 - /voorwaarden/

### Theme ###

Name: Avada
Version: 5.9
Author URL: http://themeforest.net/user/ThemeFusion
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een child thema aan. Zie: Hoe maak je een child thema

WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

Thank you!
Karin Persons

**Comment by mikejolley** [comment]
Hi @KarinMaantijd 

> This can not be done, as it is the combination of plugins that is the problem; woocommerce on itself works like a gem!

^ This is a problem unfortunetely. We can only resolve issues here with the core WooCommerce plugin. Since this issue seems to be a conflict between several paid/premium plugin and integrations this isn't really something I can advise not. Not because I don't want to, but because I'd need to replicate your setup, purchase premium plugins, and know more about the plugins themselves to effectively diagnose the issue.

If you cannot point the blame at any one plugin you may need to hire a developer to look into this in depth - it could be anything. e.g. if WP Courseware uses roles, one of the WooCommerce addons you're using could be changing role after a purchase. Thats just a total guess, but thats the kind of conflict I'd expect to find.

This seems to be the link between WP Courseware and WooCommerce - https://wordpress.org/plugins/woo-commerce-addon-for-wp-courseware/#description - and I see a similar issue in it's forum https://wordpress.org/support/topic/customers-lose-accees-to-courses-when-buying-a-new-product/ 

I'd try getting in contact with WP Courseware support and see if they have any ideas. If it turns out WooCommerce is partly responsible or they need some changes to support their use-case, they can log an issue here on your behalf.

Hope you're able to solve your problem!

Thanks
(closing this as it does not relate to WC core)
