### ISSUE TITLE
Missing Woocommerce Membership Tab

### ISSUE THREAD

**Issue by jeremiah-sandoval** [woocommerce/woocommerce#23180]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Login to Wordpress
2. Go to Woocommerce > Memberships
3. Membership tab missing

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see the Membership Tab (Members, Membership Plan, Import/Export)

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>

WordPress environment
--
Home URL: |   | https://magnetictrading.com
Site URL: |   | https://magnetictrading.com
WooCommerce version: |   | 3.5.7
Log directory writable: |   | /home/thedigit/domains/magnetictrading.com/public_html/wp-content/uploads/wc-logs/
WordPress version: |   | 5.1.1
WordPress multisite: |   | –
WordPress memory limit: |   | 256 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –

</details>

**Comment by mikejolley** [comment]
Hi,

There is no Memberships tab in WooCommerce core, this comes from an extension. Ensure it's active in WP Admin > Plugins.

Thanks

**Comment by jeremiah-sandoval** [comment]
Yes Woocommerce Membership plugin is active.

**Comment by jeremiah-sandoval** [comment]
See screenshot for reference - https://trello-attachments.s3.amazonaws.com/595e296ad00c3c18548a5209/5c9b550ed729e0799e07a852/50dc55df4c8de3ab872aeae6666ba35a/woo-membership-error.jpg

**Comment by mikejolley** [comment]
Please use the support area for Woocommerce Membership plugin.

**Comment by amroland** [comment]
This issue still occurs.
