### ISSUE TITLE
WC 3.6 removes the wc- prefix from non core order statuses

### ISSUE THREAD

**Issue by james-allan** [woocommerce/woocommerce#23199]
**Describe the bug**
The latest WC 3.6 RC removes the status prefix after updating a subscription's status. 

**To Reproduce**
Steps to reproduce the behaviour with WC Subscriptions:
1. Go to **WooCommerce > Subscriptions** from the admin dashboard.
2. Change a subscription to any status. Note the subscription ID.
3. Once the page reloads the subscription you just changed has disappeared.

Checking the database shows that the subscription status is being saved without the `wc-` prefix. 

**Screenshots**
<a href="http://pic.pros.pr/d847473c989b" target="_blank"><img src="https://d2ddoduugvun08.cloudfront.net/items/3g390v1Q0F3B0R1I181m/%5Bd627cc7cc034fdbb233419eadb46cdf3%5D_Image+2019-04-03+at+2.11.43+pm.png" style="display: block;height: auto;width: 100%;"/></a>
http://pic.pros.pr/d847473c989b

**Expected behavior**
The commit which changed this is: https://github.com/woocommerce/woocommerce/commit/ae17d6f3bdbe4f55b5d9f569dc9624bcca588618. Because subscription statuses aren't order statuses, they are saved unprefixed. This wasn't previously the case.

In my opinion to fix this we will need to revert that commit. It's a breaking change. The change was also applied to the `Abstract_WC_Order_Data_Store_CPT` update and create functions. Not all classes which extend that class are orders and share the same statuses. 

@mikejolley looking at the commit message, can we have a more targeted fix by just checking for the `auto-draft` status and ignoring it rather than excluding all statuses which isn't an order status? 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by mikejolley** [comment]
@james-allan Does subscriptions register the wc-active status or active status?

This code is to prevent non wc- prefix statuses getting a forced prefix. It can only account for order statuses (which are known to have prefix).

What could be added is a check to see if the wc- prefixed status exists before setting it without one, but I don't know if thats best.

Either way, if this change doesn't ship now we should find a way to register other statuses with prefixes to stop it incorrectly prefixing ALL statuses.

**Comment by james-allan** [comment]
> Does subscriptions register the wc-active status or active status?

Yep we register all the subscription statuses in [`wcs_get_subscription_statuses()` ](https://github.com/Prospress/woocommerce-subscriptions/blob/2.5.3/wcs-functions.php#L229-L241).

> Either way, if this change doesn't ship now we should find a way to register other statuses with prefixes to stop it incorrectly prefixing ALL statuses.

👍 If there was a filter we could use to register `wc-` prefixed statuses we can do that. My only concern is that versions of Subscription pre 2.5.4 (our next release) would incompatible with 3.6 with serious consequences if this was to release even with that filter. Given the two would be released relatively close together, it's likely stores will run into this bug.

**Comment by mikejolley** [comment]
@james-allan I'm looking at adding a method which does the more specific prefixing as you suggested, but it would be good for you to extend that class in subscriptions so the change can be reapplied in the future. Stay tuned.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23203
