### ISSUE TITLE
Price is rounded wrong on Subtotal in cart

### ISSUE THREAD

**Issue by Tennex1425** [woocommerce/woocommerce#23202]
I am facing the problem, that my subtotal price on the cart page is wrong rounded. I have all my products saved in net, so woocommerce adds the, in germany common 19%, taxes on every item. But it then takes the calculated price and rounds it on the basis of 4 decimal places, instead of 2. So if the calculated price is for example 17,5049€ and i the same product again the subtotal price becomes 35,01 €. 
Do you guys know any workaround for this? I have read multiple threads with people facing the sam issue but i couldn't find the right solution for me. 

**To Reproduce**
1. Shop page and add a product to the cart with a quantity of 2

**Expected behavior**
Disable the woocommerce rounding by more than 2 decimal places

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://bqxqvaei.myraidbox.de
Site URL: https://bqxqvaei.myraidbox.de
WC Version: 3.4.7
Log Directory Writable: ✔
WP Version: ❌ 4.9.10 - Es ist eine neuere Version von WordPress verfügbar (5.1.1)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: nginx/1.15.6
PHP Version: 7.0.33-1+ubuntu16.04.1+deb.sury.org+1 - Wir empfehlen
PHP Version 7.2 oder höher für mehr Leistung und Sicherheit zu verwenden. So aktualisierst du deine PHP-Version

PHP Post Max Size: 2 GB
PHP Time Limit: 0
PHP Max Input Vars: 10000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.22-MariaDB-10.2.22+maria~xenial-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.7
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 101.14MB
Datenbank-Datengröße: 74.48MB
Datenbank-Indexgröße: 26.66MB
wp_woocommerce_sessions: Daten: 1.62MB + Index: 0.09MB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Daten: 0.08MB + Index: 0.06MB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB
wp_aws_cache: Daten: 0.02MB + Index: 0.00MB
wp_aws_index: Daten: 4.52MB + Index: 0.00MB
wp_borlabs_cookie_blocked_content_types: Daten: 0.02MB + Index: 0.02MB
wp_borlabs_cookie_log: Daten: 0.08MB + Index: 0.14MB
wp_cimy_uef_data: Daten: 0.02MB + Index: 0.03MB
wp_cimy_uef_fields: Daten: 0.02MB + Index: 0.03MB
wp_cimy_uef_wp_fields: Daten: 0.02MB + Index: 0.03MB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB
wp_comments: Daten: 6.52MB + Index: 9.09MB
wp_ddownload_statistics: Daten: 0.02MB + Index: 0.00MB
wp_ebp_categories: Daten: 0.02MB + Index: 0.00MB
wp_ebp_categories_events: Daten: 0.02MB + Index: 0.00MB
wp_ebp_coupons: Daten: 0.02MB + Index: 0.00MB
wp_ebp_coupons_used: Daten: 0.02MB + Index: 0.00MB
wp_ebp_eventlogs: Daten: 0.02MB + Index: 0.00MB
wp_ebp_events: Daten: 0.05MB + Index: 0.00MB
wp_ebp_events_occurrence: Daten: 0.02MB + Index: 0.00MB
wp_ebp_events_tickets: Daten: 0.02MB + Index: 0.00MB
wp_ebp_event_coupons: Daten: 0.02MB + Index: 0.00MB
wp_ebp_forms: Daten: 0.02MB + Index: 0.00MB
wp_ebp_forms_inputs: Daten: 0.02MB + Index: 0.00MB
wp_ebp_gateways: Daten: 0.02MB + Index: 0.00MB
wp_ebp_payments: Daten: 0.02MB + Index: 0.00MB
wp_ebp_settings: Daten: 0.05MB + Index: 0.00MB
wp_ebp_texts: Daten: 0.02MB + Index: 0.00MB
wp_groups_capability: Daten: 0.02MB + Index: 0.03MB
wp_groups_group: Daten: 0.02MB + Index: 0.02MB
wp_groups_group_capability: Daten: 0.02MB + Index: 0.02MB
wp_groups_user_capability: Daten: 0.02MB + Index: 0.02MB
wp_groups_user_group: Daten: 0.02MB + Index: 0.02MB
wp_icl_content_status: Daten: 0.02MB + Index: 0.02MB
wp_icl_core_status: Daten: 0.02MB + Index: 0.02MB
wp_icl_flags: Daten: 0.02MB + Index: 0.02MB
wp_icl_languages: Daten: 0.02MB + Index: 0.03MB
wp_icl_languages_translations: Daten: 0.20MB + Index: 0.14MB
wp_icl_locale_map: Daten: 0.02MB + Index: 0.02MB
wp_icl_message_status: Daten: 0.02MB + Index: 0.03MB
wp_icl_mo_files_domains: Daten: 0.02MB + Index: 0.02MB
wp_icl_node: Daten: 0.02MB + Index: 0.00MB
wp_icl_reminders: Daten: 0.02MB + Index: 0.00MB
wp_icl_strings: Daten: 5.52MB + Index: 7.55MB
wp_icl_string_pages: Daten: 1.52MB + Index: 0.47MB
wp_icl_string_positions: Daten: 0.02MB + Index: 0.02MB
wp_icl_string_status: Daten: 0.02MB + Index: 0.02MB
wp_icl_string_translations: Daten: 2.52MB + Index: 1.52MB
wp_icl_string_urls: Daten: 0.02MB + Index: 0.02MB
wp_icl_translate: Daten: 0.02MB + Index: 0.02MB
wp_icl_translate_job: Daten: 0.02MB + Index: 0.02MB
wp_icl_translations: Daten: 0.09MB + Index: 0.25MB
wp_icl_translation_batches: Daten: 0.02MB + Index: 0.00MB
wp_icl_translation_status: Daten: 0.02MB + Index: 0.02MB
wp_itsec_distributed_storage: Daten: 0.02MB + Index: 0.02MB
wp_itsec_lockouts: Daten: 0.00MB + Index: 0.00MB
wp_itsec_log: Daten: 0.00MB + Index: 0.00MB
wp_itsec_logs: Daten: 0.02MB + Index: 0.09MB
wp_itsec_temp: Daten: 0.00MB + Index: 0.00MB
wp_links: Daten: 0.02MB + Index: 0.02MB
wp_mailpoet_custom_fields: Daten: 0.02MB + Index: 0.02MB
wp_mailpoet_forms: Daten: 0.02MB + Index: 0.00MB
wp_mailpoet_log: Daten: 0.02MB + Index: 0.00MB
wp_mailpoet_mapping_to_external_entities: Daten: 0.02MB + Index: 0.02MB
wp_mailpoet_newsletters: Daten: 0.03MB + Index: 0.00MB
wp_mailpoet_newsletter_links: Daten: 0.02MB + Index: 0.03MB
wp_mailpoet_newsletter_option: Daten: 0.02MB + Index: 0.02MB
wp_mailpoet_newsletter_option_fields: Daten: 0.02MB + Index: 0.02MB
wp_mailpoet_newsletter_posts: Daten: 0.02MB + Index: 0.02MB
wp_mailpoet_newsletter_segment: Daten: 0.02MB + Index: 0.02MB
wp_mailpoet_newsletter_templates: Daten: 1.52MB + Index: 0.00MB
wp_mailpoet_scheduled_tasks: Daten: 0.02MB + Index: 0.03MB
wp_mailpoet_scheduled_task_subscribers: Daten: 0.02MB + Index: 0.02MB
wp_mailpoet_segments: Daten: 0.02MB + Index: 0.02MB
wp_mailpoet_sending_queues: Daten: 0.02MB + Index: 0.03MB
wp_mailpoet_settings: Daten: 0.02MB + Index: 0.02MB
wp_mailpoet_statistics_clicks: Daten: 0.02MB + Index: 0.05MB
wp_mailpoet_statistics_forms: Daten: 0.02MB + Index: 0.02MB
wp_mailpoet_statistics_newsletters: Daten: 0.02MB + Index: 0.03MB
wp_mailpoet_statistics_opens: Daten: 0.02MB + Index: 0.05MB
wp_mailpoet_statistics_unsubscribes: Daten: 0.02MB + Index: 0.05MB
wp_mailpoet_subscribers: Daten: 0.02MB + Index: 0.05MB
wp_mailpoet_subscriber_custom_field: Daten: 0.02MB + Index: 0.02MB
wp_mailpoet_subscriber_ips: Daten: 0.02MB + Index: 0.02MB
wp_mailpoet_subscriber_segment: Daten: 0.02MB + Index: 0.03MB
wp_options: Daten: 4.39MB + Index: 0.16MB
wp_payone_api_log: Daten: 0.02MB + Index: 0.02MB
wp_payone_transaction_log: Daten: 0.02MB + Index: 0.03MB
wp_pmxe_exports: Daten: 0.33MB + Index: 0.00MB
wp_pmxe_google_cats: Daten: 0.39MB + Index: 0.00MB
wp_pmxe_posts: Daten: 0.06MB + Index: 0.00MB
wp_pmxe_templates: Daten: 0.02MB + Index: 0.00MB
wp_pmxi_files: Daten: 0.00MB + Index: 0.00MB
wp_pmxi_history: Daten: 0.00MB + Index: 0.00MB
wp_pmxi_imports: Daten: 1.12MB + Index: 0.00MB
wp_pmxi_posts: Daten: 0.01MB + Index: 0.01MB
wp_pmxi_templates: Daten: 0.04MB + Index: 0.00MB
wp_postmeta: Daten: 5.52MB + Index: 4.03MB
wp_posts: Daten: 35.52MB + Index: 0.77MB
wp_termmeta: Daten: 0.01MB + Index: 0.02MB
wp_terms: Daten: 0.02MB + Index: 0.03MB
wp_term_relationships: Daten: 0.16MB + Index: 0.13MB
wp_term_taxonomy: Daten: 0.02MB + Index: 0.03MB
wp_usermeta: Daten: 0.09MB + Index: 0.06MB
wp_users: Daten: 0.02MB + Index: 0.05MB
wp_vtprd_purchase_log: Daten: 0.02MB + Index: 0.02MB
wp_vtprd_purchase_log_product: Daten: 0.02MB + Index: 0.02MB
wp_vtprd_purchase_log_product_rule: Daten: 0.02MB + Index: 0.02MB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_payonecw_customer_contexts: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_payonecw_documents: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_payonecw_ecc: Daten: 0.02MB + Index: 0.00MB
wp_woocommerce_payonecw_schema_version: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_payonecw_storage: Daten: 0.02MB + Index: 0.00MB
wp_woocommerce_payonecw_transactions: Daten: 0.16MB + Index: 0.00MB
wp_wusp_group_product_price_mapping: Daten: 0.02MB + Index: 0.02MB
wp_wusp_role_pricing_mapping: Daten: 0.02MB + Index: 0.02MB
wp_wusp_rules: Daten: 0.02MB + Index: 0.03MB
wp_wusp_subrules: Daten: 0.02MB + Index: 0.08MB
wp_wusp_user_pricing_mapping: Daten: 0.02MB + Index: 0.03MB
wp_wysija_campaign: Daten: 0.02MB + Index: 0.00MB
wp_wysija_campaign_list: Daten: 0.02MB + Index: 0.00MB
wp_wysija_custom_field: Daten: 0.02MB + Index: 0.00MB
wp_wysija_email: Daten: 0.06MB + Index: 0.00MB
wp_wysija_email_user_stat: Daten: 0.02MB + Index: 0.00MB
wp_wysija_email_user_url: Daten: 0.02MB + Index: 0.00MB
wp_wysija_form: Daten: 0.02MB + Index: 0.00MB
wp_wysija_list: Daten: 0.02MB + Index: 0.00MB
wp_wysija_queue: Daten: 0.02MB + Index: 0.02MB
wp_wysija_subscriber_ips: Daten: 0.02MB + Index: 0.02MB
wp_wysija_url: Daten: 0.02MB + Index: 0.00MB
wp_wysija_url_mail: Daten: 0.02MB + Index: 0.00MB
wp_wysija_user: Daten: 0.02MB + Index: 0.02MB
wp_wysija_user_field: Daten: 0.02MB + Index: 0.00MB
wp_wysija_user_history: Daten: 0.02MB + Index: 0.00MB
wp_wysija_user_list: Daten: 0.02MB + Index: 0.00MB

### Post Type Counts ###

acf: 1
attachment: 653
dedo_download: 5
home_slider: 1
mailpoet_page: 1
nav_menu_item: 115
nectar_slider: 6
page: 67
portfolio: 1
post: 2
product: 428
quantity-rule: 5
revision: 2570
shipping_rules: 1
shop_coupon: 1
shop_order: 29
tribe_events: 1
tribe_venue: 1
vtprd-rule: 1
wpcf7_contact_form: 3
wysijap: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (42) ###

WPML Multilingual CMS: von OnTheGoSystems – 3.9.4
MCCOM WooCommerce Duplicate Billing Address: von Max Auer – 1.16 – Nicht getestest mit der aktiven WooCommerce-Version
Ultimate Addons for WPBakery Page Builder: von Brainstorm Force – 3.16.22
Advanced Custom Fields: von Elliot Condon – 5.7.6
Advanced Woo Search: von ILLID – 1.51
AGB-Connector der IT-Recht Kanzlei: von Inpsyde GmbH – 1.0.4
Borlabs Cookie - Cookie Opt-in: von Benjamin A. Bornschein
Borlabs – 1.9.5

Contact Form 7: von Takayuki Miyoshi – 5.0.4
Delightful Downloads: von Ashley Rich – 1.6.6
Woocommerce Product Page for Visual Composer: von SiteSao Team – 1.9.9 – Nicht getestest mit der aktiven WooCommerce-Version
Enable Media Replace: von ShortPixel – 3.2.7
iThemes Security Pro: von iThemes – 5.4.8
Salient WPBakery Page Builder: von Michael M - WPBakery.com | Modified by ThemeNectar – 5.4.7
Loco Translate: von Tim Whitlock – 2.1.5
MailPoet 3 (New): von MailPoet – 3.17.2
MCE Table Buttons: von Jake Goldman
10up
Oomph – 3.3

Members: von Justin Tadlock – 2.1.0
Merge + Minify + Refresh: von Launch Interactive – 1.8.11
Nav Menu Roles: von Kathy Darling – 1.9.2
WooCommerce Product Filter: von Mihajlovic Nenad – 6.5.6 – Nicht getestest mit der aktiven WooCommerce-Version
Really Simple CAPTCHA: von Takayuki Miyoshi – 2.0.1
Remove Google Fonts References: von Bruno Xu – 2.6
ShiftNav Pro - Responsive Mobile Menu: von Chris Mavricos
SevenSpark – 1.4.0.1

Shortcode in Menus: von Gagan Deep Singh – 3.4
TinyMCE Advanced: von Andrew Ozz – 4.8.0
UberMenu 3 - The Ultimate WordPress Mega Menu: von Chris Mavricos
SevenSpark – 3.4.0.1

WooCommerce Checkout Manager: von Visser Labs – 4.2.3
WooCommerce Conditional Shipping and Payments: von WooThemes – 1.2.2 – 1.5.1 ist verfügbar – Nicht getestest mit der aktiven WooCommerce-Version
Woocommerce Multiple Addresses: von Alexander Tinyaev – 1.0.7.1 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Product Categories Selection: von PluginForage.com – 2.0 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce: von Automattic – 3.4.7 – 3.5.7 ist verfügbar
WooCommerce PayoneCw: von customweb GmbH – 3.0.215 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Hide Products: von codewoogeek – 3.8 – Nicht getestest mit der aktiven WooCommerce-Version
WP All Export Pro: von Soflyy – 1.5.2
WP All Import Pro: von Soflyy – 4.5.1
WP Media folder: von Joomunited – 4.7.0
WP All Import - ACF Add-On: von Soflyy – 3.1.6
WP All Import - User Import Add-On: von Soflyy – 1.1.0
WP All Import - WooCommerce Add-On Pro: von Soflyy – 2.3.9 – Nicht getestest mit der aktiven WooCommerce-Version
WPML String Translation: von OnTheGoSystems – 2.7.3
WPML Widgets: von Jeroen Sormani – 1.0.6
MailPoet 2: von MailPoet – 2.10.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop-Basis: #1640 - /onlineshop/
Warenkorb: #1684 - /onlineshop/warenkorb/
Kasse: #1682 - /onlineshop/kassa/
Mein Konto: #1764 - /haendler-login/konto/
Allgemeine Geschäftsbedingungen: #1687 - /onlineshop/agb/

### Theme ###

Name: Salient Child Theme
Version: 0.1
Author URL: http:%20//mysite.com/
Child Theme: ✔
Parent Theme Name: Salient
Parent Theme Version: 8.5.5
Parent Theme Author URL: http://themenectar.com
WooCommerce Support: ✔

### Templates ###

Archive Template: Dein Theme hat eine woocommerce.php-Datei
was dazu führt
dass du das Template woocommerce/archive-product.php nicht überschreiben kannst
da woocommerce.php höher gewichtet wird als archive-product.php. Das ist beabsichtigt
um Darstellungsprobleme zu verhindern.

Overrides: salient/woocommerce/cart/cart-shipping.php
salient/woocommerce/cart/cart-totals.php
salient/woocommerce/cart/cart.php
salient/woocommerce/cart/shipping-calculator.php
salient/woocommerce/checkout/form-checkout.php
salient/woocommerce/checkout/form-shipping.php
salient/woocommerce/checkout/review-order.php
salient/woocommerce/checkout/terms.php
salient/woocommerce/content-product.php
salient/woocommerce/content-single-product.php
salient/woocommerce/loop/add-to-cart.php
salient/woocommerce/loop/loop-start.php
salient/woocommerce/myaccount/form-login.php
salient/woocommerce/single-product/product-image.php
salient/woocommerce/single-product/tabs/description.php
salient/woocommerce/single-product/tabs/tabs.php

`
</details>

**Comment by mikejolley** [comment]
@Tennex1425 Are you saying you added `17,5049` as the product price?

**Comment by mikejolley** [comment]
Ok, I worked it out `14.71`.

The tax is calculated for the line, so you'd have 14.71 * 2 = 29.42 then calc tax.

29.42 * 1.19 = 35.0098 which rounds up to 35.01. With that in mind, the result seems correct. What you're describing is rounding per item which is not supported by default.

This wiki outlines how tax calculations work in WC https://github.com/woocommerce/woocommerce/wiki/How-Taxes-Work-in-WooCommerce

If you want to avoid the rounding issue you'd need to use tax inclusive pricing. Defining product price as 17.50, which would use this calc for the tax amount.

17.50-(17.50/1.19) = 2.79

Or for 2 items:

35-(35/1.19) = 5.59 tax.

The subtotal/total in that case would be exactly 35.

Hope this makes sense.

**Comment by aovivo2000** [comment]
Hi there,

with the WC 4.6 release today I just wanted to remind that the rounding issues in WooCommerce still persists and needs to be addressed. 

I wish I could contribute in any way, but I lack the skills. 
So I am hoping that this might be solved soon. this issue has been out there for a long time... rounding and taxing might work with prices including taxes - but as stated in my previous comment there are too many products and changes in taxes right now - that I would appreciate this to be addressed and fixed as soon as possible...

my best regards - and looking forward for this to be fixed soon..
P.-
