### ISSUE TITLE
"Invalid value type for field 'availability'" error in Rich Results schema validator

### ISSUE THREAD

**Issue by matthew-horrocks** [woocommerce/woocommerce#23200]
As mentioned in a number of comments in #22896 and #22842, the Google Rich Results schema validation will throw a warning of "Invalid value type for field 'availability'" when run against a product page.

This is caused by the use of ``https://schema.org/`` instead of ``http://schema.org/`` at https://github.com/woocommerce/woocommerce/blob/d69f014807f29e6ba7514dc85ce22ac1e77ecb11/includes/class-wc-structured-data.php#L259

https://schema.org//InStock uses the ``http://schema.org/`` format.

WordPress 5.1.1 and WooCommerce version 3.5.7.

**Comment by mikejolley** [comment]
Hi @matthew-horrocks 

Whilst you're right about the 'rich results' tool showing a warning about the value, the value is not incorrect.

- This tool shows no warning: https://search.google.com/structured-data/testing-tool/u/0/
- Google documentation (https://developers.google.com/search/docs/data-types/product) uses https and the same value we do - click the single product page 'see markup' button there to see the value it sends. It uses `https://schema.org/InStock` which matches our implementation.
- http://schema.org/InStock redirects to https://schema.org/InStock, therefore the https version is correct.

This likely means the Rich Results validator is outdated as it goes against the actual URL (https://schema.org/InStock) and Google's documentation. For that reason, this is not going to be changed.

Thanks for raising.
