### ISSUE TITLE
Allow True/False values for Publish column 

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce#23205]
Currently, only a `1` or `0` is used to identify if a product is published or not. Since export from Shopify uses True or False values when exporting products. It's minimal but could be helpful if either 1's and 0's could be used along site true or false values. 1=true 0=false or visa vera, whichever is used. 

https://cld.wthms.co/lvpGsd

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23207
