### ISSUE TITLE
Determining Refund ID for refund email

### ISSUE THREAD

**Issue by Spreeuw** [woocommerce/woocommerce#23209]
**Is your feature request related to a problem? Please describe.**
When hooking into the refund emails (`customer_partially_refunded_order ` and `customer_refunded_order`), for example with the `woocommerce_email_attachments` filter, there is no way to determine which particular refund the email is for. Only the parent order object is passed to the filter and while the refund object is set in the email object ($email->refund), this is not accessible for third party plugins.

**Describe the solution you'd like**
Ideally the email object should be passed to the filters in its entirety so that the refund object can be read when it's available.
Alternatively the refund object should be passed as an additional parameter to the email filters (probably not the best solution though).

**Describe alternatives you've considered**
I looked into various action hooks that are triggered during the emailing process to be able to fire any of my own actions, but being a makeshift solution it's far from ideal (and still not possible with the current actions & filters in the email) and it's much better to have the information available directly via the filters.

**Comment by mikejolley** [comment]
Passing `$this` to email class hooks would work. Did you want to prep a PR?

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/23250#pullrequestreview-224992780
