### ISSUE TITLE
is-active class missing on woocommerce-MyAccount-navigation when viewing single order

### ISSUE THREAD

**Issue by waynep16** [woocommerce/woocommerce#23219]
The my-account admin menu has is-active class when on the respective pages, but when drilling down to the singular view order page, the active class vanishes from the "orders" menu item.

**To Reproduce**

1. Sign in as customer
2. Visit /my-account page
click on orders my-account/orders/ < - sidebar menu class on LI is set to is-active
view single order <- sidebar menu class on orders tab is removed.

**Expected behavior**
The view single order screen menu item should still retain the is-active menu item class

**WordPress Environment**
Latest wp and latest woo

**Comment by peterfabian** [comment]
Please see #23236.
