### ISSUE TITLE
Network orders widget: Not checking if WC is network-activated

### ISSUE THREAD

**Issue by WPprodigy** [woocommerce/woocommerce#23215]
### What's Happening

The Network Orders widget makes sure WooCommerce is activated on the site before querying for order info. This makes sense, however, it's not taking network-activated plugins into account: https://github.com/woocommerce/woocommerce/blob/df2cd4b232aa1bfb31d48915bf18f7b397e344b0/includes/api/v2/class-wc-rest-network-orders-v2-controller.php#L121-L127

This means the widget doesn't work at all if WooCommerce is network activated.

The `active_plugins` option will only include plugins that are activated via the UI. It does not include network-wide plugins. Those can be retrieved with `get_site_option('active_sitewide_plugins');`.

### Code locations

1) The dashboard widget enqueues a script with blog IDs to check orders on: https://github.com/woocommerce/woocommerce/blob/f9cdab66eb1f61f6f26001838199aa1a5b8ba01f/includes/admin/class-wc-admin-dashboard.php#L314-L333

2) The script then calls a rest endpoint for each blog ID that was passed in:
https://github.com/woocommerce/woocommerce/blob/d0491072e8a7d0a4535db0ec2bae4a6d43ff64fd/assets/js/admin/network-orders.js#L25-L34

3) The REST endpoint: https://github.com/woocommerce/woocommerce/blob/df2cd4b232aa1bfb31d48915bf18f7b397e344b0/includes/api/v2/class-wc-rest-network-orders-v2-controller.php#L118-L154

**Comment by mikejolley** [comment]
@WPprodigy Pretty sure WC doesn't work if network activated because it would lead to tables being shared? Can you confirm?

**Comment by rrennick** [comment]
> it would lead to tables being shared?

The only difference between network activation and per site activation is that network activation does not run the activation/deactivation hooks on the individual sites. Network active plugins are loaded in the same routine as site active plugins.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23270 (thanks @jenkoian)
