### ISSUE TITLE
After editing Attribute Term, top shows "Back to Tags"

### ISSUE THREAD

**Issue by senff** [woocommerce/woocommerce#23224]
**Describe the bug**
When editing one of an existing Attribute's terms, top of the screen says "Back to Tags" instead of "Back to Attributes".

**To Reproduce**
1. Go to Products → Attributes
2. Choose an Attribute that has terms
3. Select "Edit" under any of the terms
4. Optional: make changes 
5. In the "Edit Attribute" screen, select "Update"

**Expected behavior**
Top of the page should show "Back to Attributes"

**Actual behavior**
Top of the page shows "Back to Tags"

**Screenshot**

![tags-instead-of-attributes](https://user-images.githubusercontent.com/1710669/55684788-4d75cc00-591d-11e9-8ab4-03fd5def0bff.png)

**Comment by peterfabian** [comment]
Hi, 

Unless I don't understand your steps correctly, I think the link leads to a list of terms, not to a list of attributes, so the link should perhaps read `Back to Terms`? Please see #23238.

**Comment by senff** [comment]
Indeed, the link itself (where it leads to) is correct, but the text isn't.

**Comment by mikejolley** [comment]
Closing in favour of https://github.com/woocommerce/woocommerce/pull/23238
