### ISSUE TITLE
Product Editor: sorting icon missing from Attributes

### ISSUE THREAD

**Issue by senff** [woocommerce/woocommerce#23221]
**Describe the bug**
The "sorting" icon (3 lines on top of eachother) is missing from Product Data → Attributes.
The order of the attributes can still be sorted by dragging and dropping, it's just the icon that is missing.

**To Reproduce**
1. Create or edit a Variable product
2. Click on Product data → Attributes

**Expected behavior**
When hovering over any of the attributes, it should show the sorting icon, arrow down and "Remove" on the right.

**Actual behavior**
It shows the arrow down and "Remove", but not the sorting icon (like it does in the Variations section).

**Screenshots**
Icon is missing from Attributes:

![icon-missing](https://user-images.githubusercontent.com/1710669/55682988-8a839380-5908-11e9-81ea-8546311f452e.png)

To compare -- icon is present in Variations:

![icon-present](https://user-images.githubusercontent.com/1710669/55682989-8b1c2a00-5908-11e9-8fde-66b6f2dce3c4.png)

**Comment by mikejolley** [comment]
Thanks, will close in favour of https://github.com/woocommerce/woocommerce/issues/23221 and add feedback there.
