### ISSUE TITLE
Performance: don't save shipping postmeta items when all goods are virtual

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce#23235]
On one site I'm working on, 8.7% of all rows in the (large, table scans are slow) postmeta table have one of 10 keys, with a value of `(string)0`. (These numbers would be halved if not for a multi-currency plugin). The keys are:

```
_cart_discount
_cart_discount_base_currency
_cart_discount_tax
_cart_discount_tax_base_currency
_order_shipping
_order_shipping_base_currency
_order_shipping_tax
_order_shipping_tax_base_currency
_order_tax
_order_tax_base_currency
```

The `_order_shipping` and `_order_shipping_tax` items particularly stand out, since shipping has never been active on the store (it's digital goods only). Would there be any risks or problem with simply not saving those meta items on orders with entirely virtual goods?

**Comment by DavidAnderson684** [comment]
On a related note, a further 7.8% of rows are storing empty string values in the shipping address fields (`_shipping_%') on orders which were entirely virtual (which on this store is actually all of them). This presumably also hurts the performance when a table scan is done by whatever code (in WC or elsewhere).

**Comment by lkraav** [comment]
Great find. Would it also be possible to create a database cleanup routine for this?

**Comment by claudiosanches** [comment]
@lkraav why not? Should be nice to clean it.
