### ISSUE TITLE
Woo Commerce Not Exporting Item Weights to Royal Mail Interface

### ISSUE THREAD

**Issue by sjjhr** [woocommerce/woocommerce#23233]
We are using Royal Mail click and drop's API. WooCommerce is not exporting the weight of our package, so we are having to do it manually. 

To do this, we have to look at each order and check the weight. 

We have checked GitHub for pre-existing solutions. Other people have reported the same thing, and shared some code with a solution. Unfortunately this hasn't worked as per screenshot. 

This is basic functionality which should not be missing from Woo Commerce. 
<img width="1224" alt="Woo Commerce Weight But" src="https://user-images.githubusercontent.com/48725143/55723642-71aad900-5a01-11e9-81a4-379fcbbd4c40.png">

**Comment by mikejolley** [comment]
Royal Mail support is not built into WooCommerce core and so does not control this, so you'd need to raise this with the developer of the extension - find their support area.

If package weights need to be added, there are filters in WC core that weight could be added to and store in meta.

Thanks!

**Comment by sjjhr** [comment]
Does Woo core, or the plugin generate the data including weight which needs
to be passed to Royal Mail's API?

And if we need to export a CSV with the data, does Woo core or the plugin
generate the CSV?

My developer says that Woo core is responsible but I cannot judge.

regards

**Comment by mikejolley** [comment]
> Does Woo core, or the plugin generate the data including weight which needs
to be passed to Royal Mail's API?

Woo core controls the weight field for products.

> And if we need to export a CSV with the data, does Woo core or the plugin
generate the CSV?

Unknown; woo core does have a CSV export function, but this may differ from the export you have in place for Royal Mail, which is an extension.

> My developer says that Woo core is responsible but I cannot judge.

Perhaps tell them to comment here if they need clarification. Royal Mail is not part of core.
