### ISSUE TITLE
We're enforcing developers and users the visibility of the billing_address_2 label

### ISSUE THREAD

**Issue by pojke** [woocommerce/woocommerce#23232]
I'm here to question this change:
https://github.com/woocommerce/woocommerce/commit/87054ece9a4c05db72e139730ed1764c63fab635#diff-03a6101815a8b39c1ff4ee2815fedc1a

What was it driven by? At which point there was an assumption that **everyone** wants this label to disappear and why?

I'm trying to understand the reasoning because today I had a 2nd case (after WC update) that it was questioned by shop owner "Why did my suburb field label has disappeared" (we renamed the field via language file)?

@claudiulodro

**Comment by mikejolley** [comment]
@pojke Address 2 **had no label** prior to this change. Are you adding the label via plugin or code? If code, you can remove the class also.

**Comment by pojke** [comment]
I think it is a wrong assumption and developer experience. It assumes that you'll never need this label visible because it's the default usage. 
If you create a label via woocommerce_checkout_fields filter, it will be invisible and you need to manually remove that class. It might work here, be painful, but it's not future proof - imagine we're adding another class to default WC labels. From now on you have to iterate over classes, pick the one disabling visibility, attach the rest.
And my current code will also break with new future changes because right now I remove all classes from a label (it's the easiest way to remove accessibility class).
```    //this is needed as of WC 3.6, label class to 2nd Address field is always hidden - this below brings it back
    $checkout_fields['billing']['billing_address_2']['label_class'] = array();
```

And lastly it's not _Style the field visible with CSS (it is hidden with css only)_ - it's WordPress accessibility class, you can't just make it visible via CSS. You're giving a wrong impression to whoever will read it.

I know it was a quick and easy fix but personally, I think that accessibility should be hooked much later in the code, check whether the label is empty or not and then hook accessibility class.

**Comment by mikejolley** [comment]
@pojke How would it be possible to know later on if it should be hidden or not? There isn't really a way to know what your intention is for the field if the label is modified...plus if the label itself is added later, it prevents you removing the default label.

**Comment by pojke** [comment]
@mikejolley The intention of the code I quoted is purely to display a hidden label **because** there is none by default. The solution should display a hidden label **if** there is no label. 

It should be executed after the woocommerce_checkout_fields hook as it is used for modifying fields. 
Then there should be a simple check whether the label is set or not, if not - the current behaviour is expected. That's what I would expect. Otherwise, you will **always** have accessibility invisible class set, which is not what this class should be used for in my opinion.

**Comment by mikejolley** [comment]
Ok @pojke - do you want to send a PR with that suggestion?

**Comment by mikejolley** [comment]
Closing in favour of https://github.com/woocommerce/woocommerce/pull/23300 cc @timmyc
