### ISSUE TITLE
<br> tag stripped off of product title - COD only

### ISSUE THREAD

**Issue by AashikP** [woocommerce/woocommerce#23247]
**Describe the bug**

Came across this interesting bug that was reported in 1947014-zen. Basically, `<br>` tag from a product title is stripped off if payments are made via COD.

**To Reproduce**
1.  Custom permalink structure: /%postname%
2. Basic WooCommerce auto-setup with: 
    * I plan to sell digital products 
    * **COD payment gateway** enabled 
    * Storefront theme 
    * Skip Jetpack
3. Create a new virtual product: 
    * Name: `May 18-23, 2019<br>2 People 1 Room` 
    * Enable stock management 
    * Stock quantity = 1
4. Purchase the product in incognito/private window
5. Check the product title to confirm that its now `May 18-23, 20192 People 1 Room`

**Expected behavior**

We expect the product title to remain the same irrespective of the payment gateway used.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

Any. Tried on a fresh install of 3.5.7 with WooCommerce only. Could also replicate in [3.6.0-rc.1](https://github.com/woocommerce/woocommerce/releases/tag/3.6.0-rc.1)

**Comment by mikejolley** [comment]
I think it may be unrelated to gateway and due to the product update when stock is changed. post_modified is set, and when thats updated so it title etc. Some users don't have privileges to save HTML.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23249
