### ISSUE TITLE
WordPress database error: [Table 'local.wp_wc_product_meta_lookup' doesn't exist

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#23259]
**Describe the bug**
>WordPress database error: [Table 'local.wp_wc_product_meta_lookup' doesn't exist]
INSERT IGNORE INTO wp_wc_product_meta_lookup (`product_id`) SELECT posts.ID FROM wp_posts posts WHERE posts.post_type IN ('product', 'product_variation') 

**To Reproduce**
Go to Status > Tools
Click on "Regenerate" Product Lookup tables
The page refreshes and I see this error.

**Screenshots**
![WooCommerce tools page showing various tools and a database error](https://user-images.githubusercontent.com/507025/55851975-01818c00-5b96-11e9-8eba-227519c07f47.png)

**Expected behavior**
The tables to be regenerated without error text. I'm not currently certain if the table was successfully built or not. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

I don't know about _consistantly_ but it's on two sites (one local, one not)

**WordPress Environment**
<details>
```
### WordPress Environment ###

WordPress address (URL): http://sandbox.test
Site address (URL): http://sandbox.test
WC Version: 3.6.0
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.14.0
PHP Version: 7.2.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.7.23
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() failed. Contact your hosting provider.
Remote Get: ❌ wp_remote_get() failed. Contact your hosting provider.

### Database ###

WC Database Version: 3.6.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 8.52MB
Database Data Size: 4.42MB
Database Index Size: 4.10MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.13MB + Index: 0.13MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.08MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB
wp_nf3_action_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_chunks: Data: 0.02MB + Index: 0.00MB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB
wp_nf3_field_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB
wp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB
wp_nf3_upgrades: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 1.05MB + Index: 0.06MB
wp_postmeta: Data: 2.08MB + Index: 2.94MB
wp_posts: Data: 0.22MB + Index: 0.13MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.06MB + Index: 0.05MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.06MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
```
</details>

**Comment by mikejolley** [comment]
@helgatheviking Were these installs updated manually i.e. not through auto-update? The DB install routine runs on activation/upgrade. Perhaps thats why the table was not created?

**Comment by helgatheviking** [comment]
@mikejolley these are both gitified versions of WooCommerce. I pulled down the latest commits in the master. Is there no way to get the tables installed if using a git version? Shouldn't regenerate build the table if it doesn't exist?

**Comment by mikejolley** [comment]
@helgatheviking If you'd been on 3.5 from git and then pulled 3.6 from git, yes, it would have triggered upgrade. But if you've been on earlier 3.6 builds, it won't update because the DB version will already be 3.6.

**Comment by helgatheviking** [comment]
That does seem to be the case. Deactivating the plugin, changing the DB option to 3.5, and then re-enabling the plugin seems to do the trick.

**Comment by mikejolley** [comment]
de-activate/re-activate would have also created the table because dbdelta runs regardless of db_version on activation :)

Thanks, marking resolved.

**Comment by rrennick** [comment]
Additional note for those running dev/test installs from git clones: 

My install had the earliest version of the wc_product_meta_lookup table so queries would fail due to field name changes. Deactivate/re-activate ran the dbDelta & the table schema was updated.
