### ISSUE TITLE
CSV import inserts new empty objects when UPDATE ticket if only some rows have SKU

### ISSUE THREAD

**Issue by iSevenDays** [woocommerce/woocommerce#23257]
**Describe the bug**
I have a store with 10 products.
Every product has SKU field.

I have a CSV file with some internal information and information about 10 products.

```
NAME SKU       PRICE
0                   1
0                  to be discussed
Shoes SHOES          1000
```

SKU exists only for the latest(third row).

Other rows have no SKU, rows with internal information should be skipped.

**To Reproduce**
1. Go to Products
2. Click on Import
3. Select Import and select a csv file
4. Tick "update" checkbox
5. Click import
6. See SKU - matches SKU when importing, price - matches price
7. Click "import"
8. See a lot of new published products in the store with empty information

Alternative steps - using screenshots:
You can see empty object is inserted.
https://gyazo.com/58752e20cccdb7dbf9d58a95ce918289
https://gyazo.com/ba8e7179c6f9651707dd38ec305d6c17
https://gyazo.com/d49212e01caa659d11abf61ec79755fe
https://gyazo.com/64160a5798deeeb0d392af668dc48e66

**Screenshots**
https://gyazo.com/12d241c225020f84f90f4d519c884da2

**Expected behavior**
I expect the price updated only for the following row
`Shoes SHOES 1000`

Other rows must be skipped.

I DID NOT expect to see hundreds of new empty products published to my production store.

**WORKAROUND**
Fill SKU with some text:

```
NAME SKU       PRICE
0     none       1
0     none      to be discussed
Shoes SHOES       1000
```

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Wordpress 5.1.1
/**
 * WooCommerce Product CSV importer
 *
 * @package  WooCommerce/Import
 * @version  3.1.0

</details>

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23262
