### ISSUE TITLE
Woocommerce products not showing. Display a 503 Error or 500 Internal Server Error

### ISSUE THREAD

**Issue by srijanc** [woocommerce/woocommerce#23260]
We don't offer technical support on GitHub so we recommend using the following:

**Reading our documentation**
Usage docs can be found here: https://docs.woocommerce.com/

If you have a problem, you may want to start with the self help guide here: https://docs.woocommerce.com/document/woocommerce-self-service-guide/

**Technical support for premium extensions or if you're a WooCommerce.com customer**
 from a human being - submit a ticket via the helpdesk
https://woocommerce.com/contact-us/ 

**General usage and development questions**
- WooCommerce Slack Community: https://woocommerce.com/community-slack/
- WordPress.org Forums: https://wordpress.org/support/plugin/woocommerce
- The WooCommerce Help and Share Facebook group

**Comment by mikejolley** [comment]
You seem to have just posted the issue template rather than a bug report. You should follow the links it suggested - usually you can find the source of the problem by looking at your wordpress and/or server error log.

https://docs.woocommerce.com/document/woocommerce-self-service-guide/
