### ISSUE TITLE
Add a new product type: Gift cards

### ISSUE THREAD

**Issue by pretzelhands** [woocommerce/woocommerce#23278]
**Is your feature request related to a problem? Please describe.**

As part of the [new 3-D Secure standard](https://doc.wirecard.com/CreditCard.html#CreditCard_3DS2) that is coming into force in Europe, there are a number of new parameters that should be sent to credit card acquirers. 

There are a few parameters related to tracking gift card purchases, but as WooCommerce currently does not support gift cards by default I am unable to track these.

This is different from discount codes in that users would be able to purchase a kind of credit in advance from the shop.

**Describe the solution you'd like**

I'd love to have a new product type "Gift Card" that could be selected when creating a product. It could be a subset of virtual product or phyiscal product that generates a discount code on purchase. I think this would integrate well with the existing discount functionality.

**Describe alternatives you've considered**

There are numerous other plugins providing such functionality in one way or another, but it would be great to have this feature available in a canonical way.

**Comment by mikejolley** [comment]
Hi particular request seems to fall under extension territory. Gift cards are probably not common enough to justify a new core product type. The core product types are more abstract whereas gift card is a specific thing/use-case.

> There are numerous other plugins providing such functionality in one way or another, but it would be great to have this feature available in a canonical way.

It would probably be best to look at the most common solutions to this and see which types they register to detect these if needed whilst looping over order items, if this feature is needed at gateway level.

Thanks
