### ISSUE TITLE
global/quantity-input.php input closing tag contained within $labelledby IF statement

### ISSUE THREAD

**Issue by DanWyatt** [woocommerce/woocommerce#23280]
**Describe the bug**
Pull request #22333 adds an IF statement in the _global/quantity-input.php_ template to check if `$labelledby` is not empty before outputting the `aria-labelledby` attribute, however the closing tag for the `<input>` tag is contained within this IF block, therefore if `$labelledby` is empty, the `<input>` tag will be left open.

**Comment by mikejolley** [comment]
This will be fixed by https://github.com/woocommerce/woocommerce/pull/23186

cc @timmyc
