### ISSUE TITLE
Order count wrong

### ISSUE THREAD

**Issue by fesarlis** [woocommerce/woocommerce#23284]
I have found some threads on this issue but I would like to know if it can be fixed in a production site.
A shop manager tried to add manual orders but they were not completed. I now see wrong order number totals. While no orders are present, I see

All (6) | Mine (4)

And if I try to add a manual order, and just click 'Recalculate' the above number is increased.

Any guidance is welcome.

**Comment by fesarlis** [comment]
The solution was to delete wc_auto_drafts manually via SQL. I am guessing this should be fixed.

**Comment by mikejolley** [comment]
Hi,

Thanks for the note on deleting the drafts. The actual issue will be fixed in 3.6 which prevents the creation of those drafts. 

3.6 will be out in around a week.

Thanks
