### ISSUE TITLE
Making Woocommerce REST API Calls Internally

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce#23281]
Hello, is it possible to call woocommerce rest api internally without any AUTHENTICATION like this:

=>https://wpscholar.com/blog/internal-wp-rest-api-calls/

That document is for wordpress, I can't find anything specifically for woocommerce on the internet.

**Comment by erikdemarco** [comment]
```
add_filter( 'woocommerce_rest_check_permissions', '__return_true' );

//List all products
$request = new WP_REST_Request( 'GET', '/wc/v3/products' );
$response = rest_do_request( $request );
$server = rest_get_server();
$data = $server->response_to_data( $response, false );
$json = wp_json_encode( $data );
echo $json;
```

I tried this and get his error:

Fatal error: Uncaught Error: Call to a member function get_id() on boolean in /public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-rest-crud-controller.php:358

**Comment by erikdemarco** [comment]
```
add_filter( 'woocommerce_rest_check_permissions', '__return_true' );

//List all products
$request = new WP_REST_Request( 'GET', '/wc/v3/products' );
$response = rest_do_request( $request );
$server = rest_get_server();
$data = $server->response_to_data( $response, false );
$json = wp_json_encode( $data );
echo $json;
```

I tried this and get this error:

Fatal error: Uncaught Error: Call to a member function get_id() on boolean in /public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-rest-crud-controller.php:358

**Comment by mikejolley** [comment]
^ Good find, just be sure that filter is only set for this code and not globally as that would open up your API for abuse.

R/e the error, looks like its failing on the permission check:

```
if ( ! wc_rest_check_post_permissions( $this->post_type, 'read', $object->get_id() ) ) {
```

Perhaps your code is being ran too early in the page lifecycle, i.e. before custom post types have been defined yet.

Ensure you run after `init`.

Closing this as you found a solution. Thanks.

**Comment by SravanKumar35** [comment]
Hi, were you able to call the rest api?
