### ISSUE TITLE
Sales By Product Export

### ISSUE THREAD

**Issue by CHEWX** [woocommerce/woocommerce#23286]
Hi,

**Is your feature request related to a problem? Please describe.**
Yes, there is no context on the report. 

**Describe the solution you'd like**
Display product names on report.

**Describe alternatives you've considered**
Use a third party plugin.

**Additional context**
Exporting a sales by product report is pretty much redundant due to lack of context so although a third party plugin rectifies the issue, it should be in core.

Thanks,
Tom

**Comment by mikejolley** [comment]
Please see https://github.com/woocommerce/woocommerce-admin - reporting is being re-done as part of that. Existing reports will not be updated going forward.

Thanks
