### ISSUE TITLE
Slug automatically redirecting to respective product

### ISSUE THREAD

**Issue by sandeshjangam** [woocommerce/woocommerce#23287]
**Describe the bug**
I have a product and its slug is 'product-1'.
I have custom post type which slug is also 'product-1'

whenever I go to 'exmple.com/product-1' then it is redirecting to 'example.com/product/product-1'

Why? Is it know issue?

**Comment by mikejolley** [comment]
Hi

This system is controlled by WordPress. You'd need to declare your post type supports custom post type archives and setup the permalinks etc when it's registering. If the slug still redirects it may be that the redirect rules need tweaking to change the order, but this is not within the scope of WooCommerce.

Thanks!
