### ISSUE TITLE
More coupon restriction options

### ISSUE THREAD

**Issue by nutrabay1** [woocommerce/woocommerce#23289]
Add new options in coupon restriction. This will be very helpful.

1. First purchase use only: Check this box to limit this coupon to the first purchase of a customer only. (Verified by billing email address or user id) -  first purchase excludes canceled/failed orders
2. Payment Method restriction
3. Allowed Customers: select customer via his email (default woo has open-ended email restriction but not structured specifically to a logged in customer account)
4. Coupon Invalidity message for the user on the frontend
5. NEW coupon type: "Percentage discount upto X fixed cart amount" 
6. Option to auto apply a coupon (checkbox)
7. Display coupon at checkout checkmark that display's it on the front end to the user at checkout

**Comment by mikejolley** [comment]
Some of these are covered by extensions:

https://en-gb.wordpress.org/plugins/woocommerce-auto-added-coupons/
https://woocommerce.com/products/coupon-restrictions/

If there is a feature not covered by extensions and you want to suggest it, please log it as a single issue (not multiple requests in the same issue) and I'll mark it as a feature request for voting (votes-needed label).

Thanks!
