### ISSUE TITLE
Order Item Meta unwanted hidden

### ISSUE THREAD

**Issue by DarkAllMan** [woocommerce/woocommerce#23294]
There are plugins that add meta to order items. For instance PPOM.
When the value of this Meta is found in the Item name (product name), this meta is hidden from view in order admin.
The original code was to hide variation data, where it was already added in the title, however with other plugins, this is a wrong way to show the data.

**Screenshots**
(https://imgur.com/z40c1HS)

**Expected behavior**
I would like the Meta to be visible.

The responsible code:
get_formatted_meta_data in class-wc-order-item.php 

	`public function get_formatted_meta_data( $hideprefix = '_', $include_all = false ) {
		$formatted_meta    = array();
		$meta_data         = $this->get_meta_data();
		$hideprefix_length = ! empty( $hideprefix ) ? strlen( $hideprefix ) : 0;
		$product           = is_callable( array( $this, 'get_product' ) ) ? $this->get_product() : false;
		$order_item_name   = $this->get_name();

		foreach ( $meta_data as $meta ) {
			if ( empty( $meta->id ) || '' === $meta->value || ! is_scalar( $meta->value ) || ( $hideprefix_length && substr( $meta->key, 0, $hideprefix_length ) === $hideprefix ) ) {
				continue;
			}

			$meta->key     = rawurldecode( (string) $meta->key );
			$meta->value   = rawurldecode( (string) $meta->value );
			$attribute_key = str_replace( 'attribute_', '', $meta->key );
			$display_key   = wc_attribute_label( $attribute_key, $product );
			$display_value = wp_kses_post( $meta->value );

			if ( taxonomy_exists( $attribute_key ) ) {
				$term = get_term_by( 'slug', $meta->value, $attribute_key );
				if ( ! is_wp_error( $term ) && is_object( $term ) && $term->name ) {
					$display_value = $term->name;
				}
			}

			// Skip items with values already in the product details area of the product name.
			if ( ! $include_all && $product && $product->is_type( 'variation' ) && wc_is_attribute_in_product_name( $display_value, $order_item_name ) ) {
				continue;
			}

			$formatted_meta[ $meta->id ] = (object) array(
				'key'           => $meta->key,
				'value'         => $meta->value,
				'display_key'   => apply_filters( 'woocommerce_order_item_display_meta_key', $display_key, $meta, $this ),
				'display_value' => wpautop( make_clickable( apply_filters( 'woocommerce_order_item_display_meta_value', $display_value, $meta, $this ) ) ),
			);
		}

		return apply_filters( 'woocommerce_order_item_get_formatted_meta_data', $formatted_meta, $this );
	}`

Specifically:
```
// Skip items with values already in the product details area of the product name.
if ( ! $include_all && $product && $product->is_type( 'variation' ) && wc_is_attribute_in_product_name($display_value, $order_item_name ) ) {
	continue;
}
```

**Comment by mikejolley** [comment]
You could use:

```
add_filter( 'woocommerce_is_attribute_in_product_name', '__return_false' );
```

**Comment by DarkAllMan** [comment]
This would show ALL the meta?

**Comment by mikejolley** [comment]
Yes, it would skip the check to see if the meta is in the name.

**Comment by nmedia82** [comment]
Hi,

Thanks, @mikejolley we added this hook in out [PPOM](https://najeebmedia.com/ppom) version 17.2. Now all order meta will be shown in order.

We also working on some more advanced feature for developers like provide a filter (hook) to Order Item meta via programatically. In this way, developers can add meta to order against products.

Best regards,
