### ISSUE TITLE
Review Schema belongs inside product

### ISSUE THREAD

**Issue by melindahelt** [woocommerce/woocommerce#23299]
10193349-HC

User asked for this issue to be reported here as they do not use GitHub: Issue is that the reviews belong inside the product and are currently not.

This is an example, created with a third  party plugin that has all reviews inside the product, per google requirements. That link shows a good product schema, with all reviews nested inside:

https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fdev.japanese-knives.co.il%2Fproduct%2Fshbt_ktsu_gyuto_210_sg2%2F

Now this is the same product, on a different testing server, running normal "Vanilla" Woocommerce schma.

https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fstg.japanese-knives.co.il%2Fproduct%2Fshbt_ktsu_gyuto_210_sg2

all of the reviews need to be inside the product, there should not be any independent review schema.

that is what google want: https://developers.google.com/search/docs/data-types/product

They reported that the issue is different than the one being discussed at https://github.com/woocommerce/woocommerce/issues/22969

**Comment by or128** [comment]
All of the Product's reviews need to be inside the product, there should not be any independent reviews schema.

The only two Schema on a product page should be:
1. BreadcrumbList
2. Product

If there are too many reviews, so many that you don't want to create an endless Schema, you can decide on a limit and only nest 10 or 5 of them for example, and let the rest be reported with the aggregateRating.

Please read Google's guidelines: https://developers.google.com/search/docs/data-types/product

**Comment by claudiosanches** [comment]
@melindahelt those URLs are not available anymore.

![Screenshot from 2019-04-17 10-18-43](https://user-images.githubusercontent.com/1264099/56290787-46f40b00-60fa-11e9-9d04-c993e924cdbf.png)

**Comment by melindahelt** [comment]
@or128 are you able to provide an example from your structured data from your site (similar to the links provided in the initial report)

**Comment by or128** [comment]
They do work, just refresh it a few times.
This server activates itself by demand, so it's slow to respond for the first access.

**Comment by or128** [comment]
**Just hit the refresh a few times:**
![image](https://user-images.githubusercontent.com/49712955/56292406-d7007780-612f-11e9-9915-2596d8e6903a.png)

**Comment by or128** [comment]
Here is just the code for the Product Schema, as it should be.
Outputted with all the reviews **inside**:

`<script data-snippet_id="snip-global-product-woo" type="application/ld+json">{"sku":"shbt_Ktsu_gyuto_210_SG2","image":{"height":"933","width":"1400","url":"https:\/\/dev.japanese-knives.co.il\/wp-content\/uploads\/Shibata-Kotetsu-Gyuto-210-SG2-20160701-1-DSC00231.jpg","@context":"http:\/\/schema.org","@type":"ImageObject"},"name":"\u05e1\u05db\u05d9\u05df \u05e9\u05e3 (\u05d2\u05d9\u05d5\u05d8\u05d5) \u05e9\u05d9\u05d1\u05d0\u05d8\u05d4 210\u05de&quot;\u05de SG2","offers":[{"@context":"http:\/\/schema.org","@type":"Offer","availability":"https:\/\/schema.org\/InStock","priceCurrency":"ILS","price":"1295.00","url":"https:\/\/dev.japanese-knives.co.il\/product\/shbt_ktsu_gyuto_210_sg2\/","priceValidUntil":"2019-03-16T09:25:18+00:00","itemOffered":{"@context":"http:\/\/schema.org","@type":"IndividualProduct","url":"https:\/\/dev.japanese-knives.co.il\/product\/shbt_ktsu_gyuto_210_sg2\/","sku":"shbt_Ktsu_gyuto_210_SG2","width":{},"height":{},"weight":{"@context":"http:\/\/schema.org","@type":"QuantitativeValue","value":"","unitCode":"kg"},"name":"\u05e1\u05db\u05d9\u05df \u05e9\u05e3 (\u05d2\u05d9\u05d5\u05d8\u05d5) \u05e9\u05d9\u05d1\u05d0\u05d8\u05d4 210\u05de\"\u05de SG2","description":"<h3>\u05e1\u05e8\u05d8\u05d5\u05e0\u05d9 \u05d4\u05d3\u05d2\u05de\u05d4<\/h3>\r\n[embedyt] https:\/\/www.youtube.com\/watch?v=UWCIIoWoqjQ[\/embedyt]\r\n<div style=\"clear: both\"><\/div>\r\n[embedyt] https:\/\/www.youtube.com\/watch?v=2tBs8pZG2nM[\/embedyt]\r\n<div style=\"clear: both\"><\/div>\r\n\r\n\r\n<h3>\u05e1\u05e8\u05d8\u05d5\u05df \u05d4\u05e6\u05d2\u05d4<\/h3>\r\n[embedyt] https:\/\/www.youtube.com\/watch?v=whQG6TXwUP0[\/embedyt]\r\n<div style=\"clear: both\"><\/div>\r\n\r\n[contentblock id=product_fb_content_header]\r\n[fb_pe url=\"https:\/\/facebook.com\/photo.php?fbid=10209666667038400&amp;set=o.338888892980003&amp;type=3\"]\r\n\r\n[contentblock id=shibata_general_info]\r\n\r\n[contentblock id=gyuto_description]\r\n\r\n[contentblock id=sg2]","image":{"@context":"http:\/\/schema.org","@type":"ImageObject","url":"https:\/\/dev.japanese-knives.co.il\/wp-content\/uploads\/Shibata-Kotetsu-Gyuto-210-SG2-20160701-1-DSC00231.jpg","width":1400,"height":933}}}],"description":"[contentblock id=shibata_kotetsu_info]","brand":{"@context":"http:\/\/schema.org","@type":"Brand"},"itemCondition":"http:\/\/schema.org\/NewCondition","aggregateRating":{"reviewCount":"3","bestRating":"5","ratingValue":"5","worstRating":"1","@context":"http:\/\/schema.org","@type":"AggregateRating"},"review":[{"@context":"http:\/\/schema.org","@type":"Review","author":{"@context":"http:\/\/schema.org","@type":"Person","name":"\u05d1\u05e8 \u05d1\u05e8\u05d5\u05da"},"reviewRating":{"@context":"http:\/\/schema.org","@type":"Rating","bestRating":5,"worstRating":1,"ratingValue":5},"reviewBody":"\u05e1\u05db\u05d9\u05df \u05e7\u05dc\u05d9\u05dc\u05d4 \u05d1\u05d0\u05d5\u05e4\u05df \u05de\u05e4\u05ea\u05d9\u05e2, \u05e8\u05de\u05ea \u05d7\u05d3\u05d5\u05ea \u05e4\u05e0\u05d5\u05de\u05e0\u05dc\u05d9\u05ea \u05e2\u05dd \u05de\u05e9\u05d5\u05d1 \u05d5\u05ea\u05d7\u05d5\u05e9\u05d4 \u05de\u05d0\u05d5\u05d3 \u05d1\u05e8\u05d5\u05e8\u05d9\u05dd.\r\n\u05dc\u05d8\u05e2\u05de\u05d9 \u05de\u05e6\u05e8\u05d9\u05db\u05d4 \u05d9\u05d3 \u05de\u05d9\u05d5\u05de\u05e0\u05ea \u05e9\u05e9\u05d5\u05dc\u05d8\u05ea \u05d1\u05d8\u05db\u05e0\u05d9\u05e7\u05ea \u05e2\u05d1\u05d5\u05d3\u05d4 \u05e2\u05dd \u05e1\u05db\u05d9\u05df \u05de\u05e9\u05d5\u05d1\u05d7\u05ea \u05db\u05d6\u05d5, \u05d8\u05e2\u05d5\u05ea \u05d1\u05d8\u05db\u05e0\u05d9\u05e7\u05d4 \u05d5\u05d7\u05d9\u05ea\u05d5\u05da \u05dc\u05d0 \"\u05e0\u05e7\u05d9\" \u05de\u05e0\u05d9\u05d1\u05d9\u05dd \u05e7\u05e0\u05e1 \u05de\u05d9\u05d9\u05d3\u05d9 \u05d5\u05de\u05de\u05e9 \u05de\u05e8\u05d2\u05d9\u05e9\u05d9\u05dd \u05d1\u05d0\u05d7\u05d9\u05d6\u05d4 \u05e9\u05d4\u05dc\u05d4\u05d1 \u05dc\u05d0 \u05de\u05e2\u05e8\u05d9\u05da \u05d0\u05ea \u05e6\u05d5\u05e8\u05ea \u05d4\u05e2\u05d1\u05d5\u05d3\u05d4. \r\n\u05d4\u05d7\u05d3\u05d5\u05ea \u05d1\u05d0\u05de\u05ea \u05d9\u05d5\u05e6\u05d0\u05ea \u05d3\u05d5\u05e4\u05df, \u05e7\u05e9\u05d4 \u05dc\u05d4\u05e1\u05d1\u05d9\u05e8 \u05dc\u05de\u05d9 \u05e9\u05dc\u05d0 \u05d7\u05ea\u05da \u05e2\u05dd \u05dc\u05d4\u05d1 \u05db\u05d6\u05d4.\r\n\u05de\u05d5\u05de\u05dc\u05e5 \u05d1\u05d7\u05d5\u05dd \u05e8\u05d1, \u05dc\u05e7\u05d7\u05ea \u05d1\u05d7\u05e9\u05d1\u05d5\u05df \u05e9\u05d9\u05e9 \u05dc\u05d4\u05e7\u05e4\u05d9\u05d3 \u05e2\u05dc \u05e2\u05d1\u05d5\u05d3\u05ea \u05d7\u05d9\u05ea\u05d5\u05da \u05de\u05e7\u05e6\u05d5\u05e2\u05d9\u05ea \u05db\u05d3\u05d9 \u05dc\u05e9\u05de\u05d5\u05e8 \u05e2\u05dc \u05d4\u05e1\u05db\u05d9\u05df. \u05dc\u05d0 \u05de\u05d5\u05de\u05dc\u05e5 \u05dc\u05e2\u05d1\u05d5\u05d3\u05d4 \u05e2\u05dc \u05de\u05e9\u05d8\u05d7 \u05e4\u05dc\u05e1\u05d8\u05d9\u05e7 \u05e8\u05da \u05d0\u05dc\u05d0 \u05e2\u05dc \u05de\u05e9\u05d8\u05d7 \u05d7\u05d9\u05ea\u05d5\u05da \u05de\u05e7\u05e6\u05d5\u05e2\u05d9 (\u05e7\u05e9\u05d9\u05d7).","datePublished":"2016-11-01T16:31:30+00:00"},{"@context":"http:\/\/schema.org","@type":"Review","author":{"@context":"http:\/\/schema.org","@type":"Person","name":"Rima Olvera"},"reviewRating":{"@context":"http:\/\/schema.org","@type":"Rating","bestRating":5,"worstRating":1,"ratingValue":5},"reviewBody":"This Gyuto is an excellent every day service knife. Although the shape of it is aggressive and not particularly beautiful, it is one of the best I have used for jobs like delicate technical jobs like perfect chiffonading of herbs, brunoise, etc. \r\nI haven't tried sharpening it yet, so I don't know how easy or difficult it will be, but it's holding an extremely sharp edge for quite a while. I recommend this knife for cooks who don't have lots of spare time to deal with the high-maintenance metals like Shirogami and Aogami.","datePublished":"2016-09-01T14:39:58+00:00"},{"@context":"http:\/\/schema.org","@type":"Review","author":{"@context":"http:\/\/schema.org","@type":"Person","name":"cohenalon7@gmail.com"},"reviewRating":{"@context":"http:\/\/schema.org","@type":"Rating","bestRating":5,"worstRating":1,"ratingValue":5},"reviewBody":"\u05e1\u05db\u05d9\u05df \u05e4\u05e9\u05d5\u05d8 \u05de\u05d3\u05d4\u05d9\u05de\u05d4, \u05e8\u05db\u05e9\u05ea\u05d9 \u05d0\u05d5\u05ea\u05d4 \u05dc\u05e4\u05e0\u05d9 \u05db\u05d7\u05d5\u05d3\u05e9\u05d9\u05d9\u05dd \u05d4\u05d5\u05e7\u05e1\u05de\u05ea\u05d9 \u05de\u05d4\u05de\u05e8\u05d0\u05d4 \u05d4\u05de\u05d9\u05d5\u05d7\u05d3 \u05d5\u05de\u05d4\u05d7\u05d3\u05d5\u05ea \u05d4\u05de\u05d3\u05d4\u05d9\u05de\u05d4, \u05d5\u05db\u05d1\u05e8 \u05e8\u05db\u05e9\u05ea\u05d9 \u05e1\u05db\u05d9\u05e0\u05d9 \u05e9\u05e3 \u05d1\u05e2\u05d1\u05e8 \u05d7\u05d3\u05d5\u05ea, \u05d0\u05da \u05dc\u05d0 \u05db\u05de\u05d5 \u05d6\u05d5, \u05dc\u05d4\u05db\u05d9\u05df \u05e1\u05dc\u05d8 \u05d6\u05d5 \u05ea\u05e8\u05e4\u05d9\u05d4 \u05d1\u05e9\u05d1\u05d9\u05dc\u05d9 \u05d5\u05d0\u05e0\u05d9 \u05db\u05dc \u05d4\u05d6\u05de\u05df \u05d1\u05d5\u05d7\u05df \u05d0\u05ea \u05d4\u05e1\u05db\u05d9\u05df \u05dc\u05d0\u05d9\u05d6\u05d5 \u05e8\u05de\u05d4 \u05e9\u05dc \u05d7\u05d9\u05ea\u05d5\u05da \u05d4\u05d9\u05d0 \u05de\u05d2\u05d9\u05e2\u05d4 \u05d5\u05d4\u05d9\u05d0 \u05dc\u05d0 \u05d0\u05d9\u05db\u05d6\u05d1\u05d4, \u05e9\u05d5\u05d5\u05d4 \u05d1\u05d4\u05d7\u05dc\u05d8 \u05d0\u05ea \u05d4\u05de\u05d7\u05d9\u05e8","datePublished":"2016-08-22T19:11:06+00:00"}],"@context":"http:\/\/schema.org","@type":"Product"}</script>`

**Comment by claudiosanches** [comment]
@or128 @melindahelt  thanks.

**Comment by The3IC** [comment]
Observation: (this is from reviews handled by theme): If/when an admin responds to the review, they would typically not give it a star rating so responses with no rating should not be included as Reviews as this (rating = 0) seems to generate an error.

**Comment by or128** [comment]
> Observation: (this is from reviews handled by theme): If/when an admin responds to the review, they would typically not give it a star rating so responses with no rating should not be included as Reviews as this (rating = 0) seems to generate an error.

Not Sure I understand, but anyway, responses to reviews should not be outputted in the Schema in anyway AFAIK.

**Comment by or128** [comment]
I am overwriting my server, so soon https://dev.japanese-knives.co.il/product/shbt_ktsu_gyuto_210_sg2/
 will not serve as an example.

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at https://github.com/woocommerce/woocommerce/pull/24278.
