### ISSUE TITLE
Setup Wizard error

### ISSUE THREAD

**Issue by wayheming** [woocommerce/woocommerce#23327]
**Describe the bug**
Hello, after starting the installation I get this error.

Notice: A non well formed numeric value encountered in C:\Work\OSPanel\domains\test.loc\wp-content\plugins\woocommerce\includes\wc-formatting-functions.php on line 624

**Screenshots**
http://prntscr.com/nd1xr7
http://prntscr.com/nd1zk5
http://prntscr.com/nd21ly

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): http://test.loc
Site address (URL): http://test.loc
WC Version: 3.6.0
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.0
PHP Post Max Size: 64 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.56.0
OpenSSL/1.1.0g

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 3.01MB
Database Data Size: 2.06MB
Database Index Size: 0.95MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.50MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 1
page: 6
post: 2
scheduled-action: 4

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.6.0-rc.3

### Inactive Plugins (30) ###

Classic Editor: by WordPress Contributors – 1.4
CMB2: by CMB2 team – 2.6.0
Contact Form 7: by Takayuki Miyoshi – 5.1.1
Dokan: by weDevs
LLC – 2.9.10 – Not tested with the active version of WooCommerce

Envato Theme Check: by Scott Parry – 20180222
Gutenberg Block Unit Test: by Rich Tabor – 1.0.6
Jetpack by WordPress.com: by Automattic – 7.0.1
Loco Translate: by Tim Whitlock – 2.2.0
Mailchimp for WooCommerce: by Mailchimp – 2.1.13 – Not tested with the active version of WooCommerce
Mailchimp for WordPress: by ibericode – 4.5.1
Recent Posts Widget Extended: by Satrya – 0.9.9.7
Redux Framework: by Team Redux – 3.6.15
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.0
Safe SVG: by Daryll Doyle – 1.9.3
Simple Twitter Tweets: by Ashley Sheinwald – 4.4
Simple Twitter Tweets: by Ashley Sheinwald – 3.2
Slider Revolution: by ThemePunch – 5.4.8.1
Transients Manager: by Pippin Williamson – 1.7.5
WooCommerce Email Customizer: by cxThemes – 3.22 – Not tested with the active version of WooCommerce
WooCommerce Email Customizer: by WooCommerce – 1.1.8 – Not tested with the active version of WooCommerce
WooCommerce Email Test: by RaiserWeb – 1.10 – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.9 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.18.0 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.1.14 – Not tested with the active version of WooCommerce
WordPress Importer: by wordpressdotorg – 0.6.4
WPBakery Page Builder: by Michael M - WPBakery.com – 5.7
XTEMOS Post Types plugin: by  – 1.7
YITH WooCommerce Wishlist: by YITH – 2.2.8 – Not tested with the active version of WooCommerce
Yoast SEO: by Team Yoast – 9.6 – Not tested with the active version of WooCommerce
Yoast SEO: WooCommerce: by Team Yoast – 9.3 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #10 - /shop/
Cart: #11 - /cart/
Checkout: #12 - /checkout/
My account: #13 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Nineteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 2
Oldest: 2019-04-17 07:21:37 +0000
Newest: 2019-04-17 07:21:37 +0000

Pending: 2
Oldest: 2019-04-24 07:21:37 +0000
Newest: 2019-04-24 07:21:37 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by kloon** [comment]
@wayheming looks like you are running the RC version? Can you confirm what version you are running exactly? 3.6 RC3? I just tested with RC3 and were unable to replicate the error in the wizard, from the looks it might be related to `wc_let_to_num` function which converts WP_MEMORY_LIMIT and PHP INI memory to actual bytes value.

**Comment by wayheming** [comment]
@kloon yes i use 3.6 RC3

**Comment by wayheming** [comment]
i just made a completely clean install again
I think that the wc-formatting-functions.php error I get on the status page
and installation errors do not refer to status error

http://prntscr.com/nd2rre
https://gyazo.com/43c1ae1075f520eaa8f9cd302a95fddb
<details>
`
### WordPress Environment ###

WordPress address (URL): http://test.loc
Site address (URL): http://test.loc
WC Version: 3.6.0
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.0
PHP Post Max Size: 64 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.56.0
OpenSSL/1.1.0g

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 3.02MB
Database Data Size: 2.08MB
Database Index Size: 0.94MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.52MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 1
page: 6
post: 2
scheduled-action: 4

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.6.0-rc.3

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #10 - /shop/
Cart: #11 - /cart/
Checkout: #12 - /checkout/
My account: #13 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Fifteen
Version: 2.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 2
Oldest: 2019-04-17 08:17:39 +0000
Newest: 2019-04-17 08:17:40 +0000

Pending: 2
Oldest: 2019-04-24 08:17:39 +0000
Newest: 2019-04-24 08:17:40 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by kloon** [comment]
> installation errors do not refer to status error
It does, since you are enabling tracking it will try and get your environment details to send which is where it calls the wc_let_to_num function.

I am working on a patch, what I think is happening is that ini_get is returning a false causing the error in wc_let_to_num. Will submit patch shortly, would appreciate if you can test it then if possible.

**Comment by wayheming** [comment]
yes, I will wait and test

**Comment by kloon** [comment]
@wayheming can you please test the changes in #23329 and let me know if that solves the issue for you?

**Comment by wayheming** [comment]
@kloon the error on the status page was gone but the installation is still not working

Notice: tk_ai cookie cannot be set - headers already sent by C:\Work\OSPanel\domains\test.loc\wp-includes\class.wp-scripts.php on line 369 in C:\Work\OSPanel\domains\test.loc\wp-content\plugins\woocommerce\includes\wc-core-functions.php on line 887

http://prntscr.com/nd334s

**Comment by kloon** [comment]
OK, so looks like if fixes the ini_get error, apart from that it seems you might have something in your install that is triggering output before the page is being rendered.

The cookie in question belongs to jetpack so it is possible that the issue is there. Would it be possible to delete the Jetpack plugin completely and test again? I will also run some tests on my side to try and replicate this.

**Comment by wayheming** [comment]
I have only installed wc 3.6 RC3

<details>
`
### WordPress Environment ###

WordPress address (URL): http://test.loc
Site address (URL): http://test.loc
WC Version: 3.6.0
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.0
PHP Post Max Size: 64 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.56.0
OpenSSL/1.1.0g

SUHOSIN Installed: –
MySQL Version: 5.6.38
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 3.00MB
Database Data Size: 2.06MB
Database Index Size: 0.94MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.50MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 1
page: 6
post: 2
scheduled-action: 4

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.6.0-rc.3

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #10 - /shop/
Cart: #11 - /cart/
Checkout: #12 - /checkout/
My account: #13 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Fifteen
Version: 2.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 2
Oldest: 2019-04-17 08:17:39 +0000
Newest: 2019-04-17 08:17:40 +0000

Pending: 2
Oldest: 2019-04-24 08:17:39 +0000
Newest: 2019-04-24 08:17:40 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by kloon** [comment]
Yea, the issue is the cookie is already set via Jetpack in your browser from a previous test so keeps picking it up. Busy testing now.

**Comment by kloon** [comment]
OK, did some further testing and the issue seems to stem from WC_Tracks_Client::get_identity which tries to set a cookie, the problem is that this gets called by a method which can be run anywhere in the WP lifecycle. Obviously, you need to set a cookie before headers are sent, we will work on a fix and keep you updated.

**Comment by wayheming** [comment]
@kloon ok, I'll be waiting for your answer. Thank you

**Comment by kloon** [comment]
@wayheming thanks for your help, would it be possible to test this patch #23332 and let me know if that fixes things for you?
