### ISSUE TITLE
Enhanced Select Converting to HTML entities

### ISSUE THREAD

**Issue by kloon** [woocommerce/woocommerce#23328]
**Describe the bug**
When defining an enhanced select element and passing certain characters like a slash (/) to the display text gets converted to the HTML entity code when you select that option with the slash.

**To Reproduce**
1. Go to 'admin.php?page=wc-setup'
2. See the currency select box, when you expand the select the slashes show correct but as soon as you select an option the value that is displayed converts the slash to the HTML entity code.

**Screenshots**
![Enhanced Select In Wizard](https://cld.wthms.co/1mXuWb+)

**Expected behavior**
Special characters should display correctly and not an HTML entity code.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23336/files and https://github.com/woocommerce/woocommerce/pull/23334
