### ISSUE TITLE
Products list has bug in dashboard

### ISSUE THREAD

**Issue by ejamshidiasl** [woocommerce/woocommerce#23326]
products list in admin dashboard not shown properly. for example title is not showing and price goes under seo_keyword column and some other problems.

**Comment by kloon** [comment]
Please disable all plugins except WooCommerce to find the conflict. Definitely sounds like you have a plugin conflict with your SEO plugin. Try using the Screen Options menu and unselecting the SEO columns https://cld.wthms.co/kWedfg

**Comment by ejamshidiasl** [comment]
![image](https://user-images.githubusercontent.com/25905962/56272798-b543c800-6110-11e9-974c-3c03c91621ca.png)

i disabled all expext woocommerce but nothing changed
