### ISSUE TITLE
Order line items are saved after hook woocommerce_new_order

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#23335]
**Is your feature request related to a problem? Please describe.**
The hook which is triggered when a new order object is created is `woocommerce_new_order`. This can be useful to detect when a new order has been created, regardless of how it was created (checkout, dashboard, API). However the problem is that the line items are only saved to the database after this hook is called. Which we can see in the following code: https://github.com/woocommerce/woocommerce/blob/3.5.8/includes/abstracts/abstract-wc-order.php#L175-L178

The [create function](https://github.com/woocommerce/woocommerce/blob/3.5.8/includes/data-stores/class-wc-order-data-store-cpt.php#L86) is the one that triggers the hook `woocommerce_new_order`.

**Describe the solution you'd like**
What I'd like to do is be able to access the line item data. However when we use the hook `woocommerce_new_order` we are only passed the order ID. Since at that point the line item data isn't saved yet. If we load the order from the DB with the order ID, we get empty line item data.
One solution would be to pass the $order object in the hook, so even if it hasn't been saved to the DB, the line item data is still accessible by any function which uses this hook. For example like this:

```
do_action( 'woocommerce_new_order', $order->get_id(), $order );
```

**Describe alternatives you've considered**
As an alternative I tried looking for a hook which was called at a later time after the line item data was changed, but wasn't able to find one.
Currently the hook `woocommerce_checkout_order_processed` is being used, but this is specific to only the checkout and doesn't cover creating an order in the dashboard or through the API.

**Additional context**
I had a look through the changes in 3.6, but the behaviour remains the same.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23338
