### ISSUE TITLE
Schema for Product Reviews is outputted incorrectly (against Google's guidelines)

### ISSUE THREAD

**Issue by or128** [woocommerce/woocommerce#23330]
Currently Woocommerce is outputting one review inside the Product Schema, and the rest of the reviews are outputted on their own, outside. **That is Wrong.**

**There should not be a Review schema sitting "free" in a product page.
Reviews should only be nested inside the product Schema.**

Here is an example I've created wit a 3rd party plugin (it's a week testing server, give it a few reloads):
https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fdev.japanese-knives.co.il%2Fproduct%2Fshbt_ktsu_gyuto_210_sg2%2F

Now this is the same product, on a different testing server, outputting "normal" Woocommerce schema:
https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fstg.japanese-knives.co.il%2Fproduct%2Fshbt_ktsu_gyuto_210_sg2

**all of the reviews need to be inside the product, there should not be any independent reviews schema.**

The only two Schema on a product page should be:
1. BreadcrumbList
2. Product

If there are too many reviews, so many that you don't want to create an endless Schema, you can decide on a limit and only nest 10 or 5 of them for example, and let the rest be reported with the aggregateRating.

Please read Google's guidelines: https://developers.google.com/search/docs/data-types/product

**Comment by kloon** [comment]
Thanks, already logged at #23299

**Comment by or128** [comment]
> Thanks, already logged at #23299

How does this work? how will this be handled?

**Comment by kloon** [comment]
We will look into the report soon and then provide an update and a fix. Please keep an eye on #23299 where we will update with details when we get to this.
