### ISSUE TITLE
After the update, the product 2019-17-04

### ISSUE THREAD

**Issue by youRpost9** [woocommerce/woocommerce#23346]
`
### WordPress Environment ###

WordPress address (URL): https://ftrade.com.ua
Site address (URL): https://ftrade.com.ua
WC Version: 3.6.0
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: ru_RU
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.16-1+0~20190307202206.17+jessie~1.gbpa7be82
PHP Post Max Size: 256 MB
PHP Time Limit: 600
PHP Max Input Vars: 10000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.43-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.3
WC Database Prefix: bjkrp_
MaxMind GeoIP Database: ✔
Общий размер базы данных: 64.09MB
Размер данных в базе данных: 53.88MB
Размер индекса базы данных: 10.21MB
bjkrp_woocommerce_sessions: Данные: 0.05 Мб + Индекс: 0.00 Мб
bjkrp_woocommerce_api_keys: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_woocommerce_attribute_taxonomies: Данные: 0.00 Мб + Индекс: 0.01 Мб
bjkrp_woocommerce_downloadable_product_permissions: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_woocommerce_order_items: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_woocommerce_order_itemmeta: Данные: 0.00 Мб + Индекс: 0.01 Мб
bjkrp_woocommerce_tax_rates: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_woocommerce_tax_rate_locations: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_woocommerce_shipping_zones: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_woocommerce_shipping_zone_locations: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_woocommerce_shipping_zone_methods: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_woocommerce_payment_tokens: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_woocommerce_payment_tokenmeta: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_woocommerce_log: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_advps_optionset: Данные: 0.02 Мб + Индекс: 0.00 Мб
bjkrp_advps_thumbnail: Данные: 0.02 Мб + Индекс: 0.00 Мб
bjkrp_aiowps_events: Данные: 0.97 Мб + Индекс: 0.07 Мб
bjkrp_aiowps_failed_logins: Данные: 0.12 Мб + Индекс: 0.04 Мб
bjkrp_aiowps_global_meta: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_aiowps_login_activity: Данные: 0.02 Мб + Индекс: 0.01 Мб
bjkrp_aiowps_login_lockdown: Данные: 0.02 Мб + Индекс: 0.01 Мб
bjkrp_aiowps_permanent_block: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_anycomment_email_queue: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_anycomment_likes: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_anycomment_rating: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_anycomment_subscriptions: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_anycomment_uploaded_files: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_atum_order_itemmeta: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_atum_order_items: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_atum_product_data: Данные: 0.02 Мб + Индекс: 0.05 Мб
bjkrp_aws_cache: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_aws_index: Данные: 0.96 Мб + Индекс: 0.00 Мб
bjkrp_bp_activity: Данные: 0.00 Мб + Индекс: 0.01 Мб
bjkrp_bp_activity_meta: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_bp_notifications: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_bp_notifications_meta: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_bp_xprofile_data: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_bp_xprofile_fields: Данные: 0.00 Мб + Индекс: 0.01 Мб
bjkrp_bp_xprofile_groups: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_bp_xprofile_meta: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_cegg_autoblog: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_cegg_price_alert: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_cegg_price_history: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_cftemail_forms: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_cftemail_messages: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_cf_forms: Данные: 0.04 Мб + Индекс: 0.00 Мб
bjkrp_cf_form_entries: Данные: 0.00 Мб + Индекс: 0.01 Мб
bjkrp_cf_form_entry_meta: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_cf_form_entry_values: Данные: 0.00 Мб + Индекс: 0.01 Мб
bjkrp_cf_pro_messages: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_cf_tracking: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_cf_tracking_meta: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_commentmeta: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_comments: Данные: 0.00 Мб + Индекс: 0.01 Мб
bjkrp_ewwwio_images: Данные: 0.83 Мб + Индекс: 0.34 Мб
bjkrp_fortyfour_logs: Данные: 28.61 Мб + Индекс: 2.87 Мб
bjkrp_links: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_lrgawidget_global_settings: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_mainwp_group: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_mainwp_request_log: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_mainwp_tips: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_mainwp_users: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_mainwp_wp: Данные: 0.02 Мб + Индекс: 0.00 Мб
bjkrp_mainwp_wp_backup: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_mainwp_wp_backup_progress: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_mainwp_wp_group: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_mainwp_wp_options: Данные: 0.08 Мб + Индекс: 0.00 Мб
bjkrp_mainwp_wp_settings_backup: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_mainwp_wp_sync: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_newsletter: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_newsletter_emails: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_newsletter_sent: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_newsletter_stats: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_nextend2_image_storage: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_nextend2_section_storage: Данные: 0.00 Мб + Индекс: 0.01 Мб
bjkrp_nextend2_smartslider3_generators: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_nextend2_smartslider3_sliders: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_nextend2_smartslider3_sliders_xref: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_nextend2_smartslider3_slides: Данные: 0.01 Мб + Индекс: 0.00 Мб
bjkrp_options: Данные: 3.64 Мб + Индекс: 0.24 Мб
bjkrp_pmxe_exports: Данные: 0.06 Мб + Индекс: 0.00 Мб
bjkrp_pmxe_google_cats: Данные: 0.26 Мб + Индекс: 0.05 Мб
bjkrp_pmxe_posts: Данные: 0.08 Мб + Индекс: 0.04 Мб
bjkrp_pmxe_templates: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_pmxi_files: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_pmxi_history: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_pmxi_images: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_pmxi_imports: Данные: 0.04 Мб + Индекс: 0.00 Мб
bjkrp_pmxi_posts: Данные: 0.11 Мб + Индекс: 0.13 Мб
bjkrp_pmxi_templates: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_postmeta: Данные: 9.40 Мб + Индекс: 2.60 Мб
bjkrp_posts: Данные: 1.79 Мб + Индекс: 0.88 Мб
bjkrp_ps_exclude: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_ps_postmeta: Данные: 0.00 Мб + Индекс: 0.01 Мб
bjkrp_ps_posts: Данные: 0.01 Мб + Индекс: 0.00 Мб
bjkrp_ps_product_sku: Данные: 0.00 Мб + Индекс: 0.01 Мб
bjkrp_redirection_404: Данные: 4.76 Мб + Индекс: 0.93 Мб
bjkrp_redirection_groups: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_redirection_items: Данные: 0.04 Мб + Индекс: 0.05 Мб
bjkrp_redirection_logs: Данные: 0.07 Мб + Индекс: 0.03 Мб
bjkrp_relevanssi: Данные: 1.10 Мб + Индекс: 1.33 Мб
bjkrp_relevanssi_log: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_relevanssi_stopwords: Данные: 0.01 Мб + Индекс: 0.01 Мб
bjkrp_rio_process_queue: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_robo_maps: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_sb2_404: Данные: 0.04 Мб + Индекс: 0.01 Мб
bjkrp_sb2_bl: Данные: 0.00 Мб + Индекс: 0.01 Мб
bjkrp_sb2_crawl: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_sb2_kw: Данные: 0.00 Мб + Индекс: 0.01 Мб
bjkrp_sb2_kwdt: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_sb2_log: Данные: 0.08 Мб + Индекс: 0.01 Мб
bjkrp_sb2_urls: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_sb2_urls_meta: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_signups: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_social_users: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_termmeta: Данные: 0.03 Мб + Индекс: 0.03 Мб
bjkrp_terms: Данные: 0.02 Мб + Индекс: 0.04 Мб
bjkrp_term_relationships: Данные: 0.05 Мб + Индекс: 0.09 Мб
bjkrp_term_taxonomy: Данные: 0.03 Мб + Индекс: 0.03 Мб
bjkrp_tinvwl_items: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_tinvwl_lists: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_tm_taskmeta: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_tm_tasks: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_usermeta: Данные: 0.13 Мб + Индекс: 0.01 Мб
bjkrp_users: Данные: 0.00 Мб + Индекс: 0.01 Мб
bjkrp_vslider: Данные: 0.00 Мб + Индекс: 0.01 Мб
bjkrp_wc_comments_subscription: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_wc_download_log: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_wc_phrases: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_wc_product_meta_lookup: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_wc_users_voted: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_wc_webhooks: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_wdpslayer: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_wdpsslide: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_wdpsslider: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_woof_query_cache: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_wpgmza: Данные: 0.02 Мб + Индекс: 0.00 Мб
bjkrp_wpgmza_categories: Данные: 0.02 Мб + Индекс: 0.00 Мб
bjkrp_wpgmza_category_maps: Данные: 0.02 Мб + Индекс: 0.00 Мб
bjkrp_wpgmza_maps: Данные: 0.02 Мб + Индекс: 0.00 Мб
bjkrp_wpgmza_polygon: Данные: 0.02 Мб + Индекс: 0.00 Мб
bjkrp_wpgmza_polylines: Данные: 0.02 Мб + Индекс: 0.00 Мб
bjkrp_wps_woo_grid: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_wysija_campaign: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_wysija_campaign_list: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_wysija_custom_field: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_wysija_email: Данные: 0.06 Мб + Индекс: 0.00 Мб
bjkrp_wysija_email_user_stat: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_wysija_email_user_url: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_wysija_form: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_wysija_list: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_wysija_queue: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_wysija_url: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_wysija_url_mail: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_wysija_user: Данные: 0.00 Мб + Индекс: 0.01 Мб
bjkrp_wysija_user_field: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_wysija_user_history: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_wysija_user_list: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_yith_vendors_commissions: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_yith_vendors_commissions_notes: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_yith_vendors_payments: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_yith_vendors_payments_relathionship: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_yith_wapo_groups: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_yith_wapo_types: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_yoast_seo_links: Данные: 0.07 Мб + Индекс: 0.02 Мб
bjkrp_yoast_seo_meta: Данные: 0.07 Мб + Индекс: 0.07 Мб
bjkrp_ywrr_email_blocklist: Данные: 0.00 Мб + Индекс: 0.00 Мб
bjkrp_ywrr_email_schedule: Данные: 0.00 Мб + Индекс: 0.00 Мб
itrr_contacts: Данные: 0.00 Мб + Индекс: 0.00 Мб
itrr_stats: Данные: 0.00 Мб + Индекс: 0.00 Мб
lyxz_commentmeta: Данные: 0.00 Мб + Индекс: 0.00 Мб
lyxz_comments: Данные: 0.00 Мб + Индекс: 0.01 Мб
lyxz_links: Данные: 0.00 Мб + Индекс: 0.00 Мб
lyxz_options: Данные: 0.02 Мб + Индекс: 0.01 Мб
lyxz_postmeta: Данные: 0.00 Мб + Индекс: 0.01 Мб
lyxz_posts: Данные: 0.00 Мб + Индекс: 0.01 Мб
lyxz_termmeta: Данные: 0.00 Мб + Индекс: 0.00 Мб
lyxz_terms: Данные: 0.00 Мб + Индекс: 0.01 Мб
lyxz_term_relationships: Данные: 0.00 Мб + Индекс: 0.00 Мб
lyxz_term_taxonomy: Данные: 0.00 Мб + Индекс: 0.00 Мб
lyxz_usermeta: Данные: 0.00 Мб + Индекс: 0.01 Мб
lyxz_users: Данные: 0.00 Мб + Индекс: 0.01 Мб

### Post Type Counts ###

amn_wpforms-lite: 1
attachment: 970
bp-email: 16
bulkpost: 1
custom_css: 1
customize_changeset: 16
elementor_library: 19
elementor-hf: 1
jetpack_migration: 2
logo_slider: 1
ml-slider: 1
nav_menu_item: 63
ocean_modal_window: 1
oceanwp_library: 3
oembed_cache: 9
option-tree: 1
page: 27
pf_contact: 37
post: 77
product: 160
product_slider: 1
product_variation: 1075
pt_view: 1
revision: 5
scheduled-action: 1
schema: 2
shop_order: 1
team: 1
wpcuwpfp-news-widget: 1
wpdiscuz_form: 1
wpforms: 1
wphb_minify_group: 7
wpmm_theme: 3
wysijap: 1
yith_wcps_type: 1
ywrac_cart: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (56) ###

Query Monitor: от John Blackbourn – 3.3.4
ACF Content Analysis for Yoast SEO: от Thomas Kräftner
ViktorFroberg
marol87
pekz0r
angrycreative
Team Yoast – 2.2.0

Advanced Woo Search: от ILLID – 1.67 – Не тестировалось с активной версией WooCommerce
All In One WP Security: от Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.3.8.3

Autoptimize CriticalCSS.com Power-Up: от Deny Dias & Optimizing Matters – 1.14.0
Autoptimize: от Frank Goossens (futtta) – 2.4.4
Webcraftic Clearfy - плагин оптимизации для Wordpress: от Webcraftic  – 1.5.0
DL Robots.txt: от Dyadya Lesha (info@dd-l.name) – 1.2
Easy Watermark: от BracketSpace – 0.7.2
Elementor: от Elementor.com – 2.5.14
Glue for Yoast SEO & AMP: от Joost de Valk – 0.4.3
Central Color Palette: от Gáravo – 1.13.8
Google Analytics: от Amr M. Ibrahim – 2.0.4
Ocean Cookie Notice: от OceanWP – 1.0.4
Ocean Custom Sidebar: от OceanWP – 1.0.4
Ocean Extra: от OceanWP – 1.5.3
Ocean Footer Callout: от OceanWP – 1.0.13
Ocean Full Screen: от OceanWP – 1.0.3
Ocean Modal Window: от OceanWP – 1.0.13
Ocean Popup Login: от OceanWP – 1.0.5
Ocean Posts Slider: от OceanWP – 1.0.12
Ocean Product Sharing: от OceanWP – 1.0.7 – Не тестировалось с активной версией WooCommerce
Ocean Side Panel: от OceanWP – 1.0.11
Ocean Social Sharing: от OceanWP – 1.0.14
Ocean Stick Anything: от OceanWP – 1.0.2
Ocean Sticky Footer: от OceanWP – 1.0.9
Ocean Sticky Header: от OceanWP – 1.1.11
Ocean White Label: от OceanWP – 1.0.5
Ocean Woo Popup: от OceanWP – 1.0.6
Redirection: от John Godley – 4.2.3
Relevanssi: от Mikko Saari – 4.1.4
Remove Yoast SEO Comments: от Mitch – 3.1
Webcraftic Robin image optimizer: от Webcraftic  – 1.3.5
Schema: от Hesham – 1.7.5
Sitemap Index: от Twardes – 1.2.3
Sitemap Simple: от Abhay Yadav – 1.2
Smart Slider 3: от Nextend – 3.3.18
WhatsHelp Chat Button: от Whatshelp – 1.3.0
Widget Options: от Phpbits Creative Studio – 3.7.2
WooCommerce Blocks: от Automattic – 1.4.0 – Не тестировалось с активной версией WooCommerce
Premmerce SEO for WooCommerce: от premmerce – 2.1 – Не тестировалось с активной версией WooCommerce
WooCommerce Variation Swatches: от Emran Ahmed – 1.0.55 – Не тестировалось с активной версией WooCommerce
WooCommerce Customizer: от SkyVerge – 2.6.0 – Не тестировалось с активной версией WooCommerce
Woocoomerce Extra Price Fields: от Webholics – 1.5.3
WooCommerce Google Analytics Integration: от WooCommerce – 1.4.9
WooCommerce PDF Invoices: от Bas Elbers – 2.9.16 – Не тестировалось с активной версией WooCommerce
WooCommerce Price Based on Country (Basic): от Oscar Gare – 1.8.1
WooCommerce: от Automattic – 3.6.0
WordPress Importer: от wordpressdotorg – 0.6.4
Yoast SEO: от Команда Yoast – 11.0 – Не тестировалось с активной версией WooCommerce
WP Fastest Cache: от Эмре Вона – 0.8.9.2
WP First Letter Avatar: от Dev49.net – 2.2.8
WordPress SEO For Image: от naa986 – 1.1.4
WP-Optimize: от David Anderson
Ruhani Rabin
Team Updraft – 2.3.1

WT Yandex Metrika: от Роман Кусты
АИТ "Web-Techology" – 1.0.1

Yoast SEO: Search index purge: от Team Yoast – 1.1.0

### Inactive Plugins (3) ###

Ocean Instagram: от OceanWP – 1.0.3
WooCommerce Compare List: от Themeisle – 1.1.2 – Не тестировалось с активной версией WooCommerce
WooCommerce Wishlist Plugin: от TemplateInvaders – 1.10.1 – Не тестировалось с активной версией WooCommerce

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Ссылка магазина: #5598 - /
Корзина: #5 - /cart/
Оформление заказа: #6 - /checkout/
Мой аккаунт: #7 - /my-account/
Правила и условия: #13781 - /pravila-i-uslovija/

### Theme ###

Name: OceanWP
Version: 1.6.4
Author URL: https://oceanwp.org/about-me/
Child Theme: ❌ – Если вы хотите оформить WooCommerce родительской темой
которую создал кто-то другой
мы рекомендуем воспользоваться дочерней темой. См. "Как создать дочернюю тему"

WooCommerce Support: ✔

### Templates ###

Overrides: oceanwp/woocommerce/cart/mini-cart.php
Есть обновления для oceanwp/woocommerce/content-single-product.php версии 3.4.0. Версия ядра — 3.6.0
oceanwp/woocommerce/loop/loop-start.php
oceanwp/woocommerce/single-product/title.php

Outdated Templates: ❌
					
					
						Узнайте
как обновить

### Geolocation debug info ###

HTTP_CF_IPCOUNTRY: ❌
GEOIP_COUNTRY_CODE: UA
HTTP_X_COUNTRY_CODE: ❌
HTTP_X_REAL_IP: 80.78.45.178
HTTP_X_FORWARDED_FOR: 80.78.45.178
REMOTE_ADDR: 80.78.45.178
Real external IP: 80.78.45.178
WCPBC_USE_REMOTE_ADDR: –
Geolocation Test: ✔

### PBC Settings ###

Version: 1.8.0
Base location: UA
Base currency: EUR
Price Based On: billing
Shipping: ✔
Test mode: –
Test country: –
Load products price in background: ✔
Prices entered with tax: –
Calculate tax based on: shipping
Display prices in the shop: excl

### Zone Pricing Ukraine ###

zone_id: ukraine
name: Ukraine
countries: UA
currency: UAH
exchange_rate: 31
disable_tax_adjustment: no

### Action Scheduler ###

Complete: 0
Oldest: –
Newest: –

Pending: 1
Oldest: 2019-04-17 15:09:36 +0000
Newest: 2019-04-17 15:09:36 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by claudiosanches** [comment]
@youRpost9 seems like is missing a description of the issue, what happens after the latest update?

**Comment by youRpost9** [comment]
the product card has changed

![Снимок](https://user-images.githubusercontent.com/48258192/56305742-7b42e800-6149-11e9-9f3c-9e50f64335a4.PNG)

**Comment by claudiosanches** [comment]
@youRpost9 still missing steps to reproduce and more details from the template:

```
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
</details>
```

But for what you are saying, sounds like your theme requires an update, please report this to the author of the theme in question.
