### ISSUE TITLE
when I change the attribute slug, this attribute is removed from the all products

### ISSUE THREAD

**Issue by igorek-zxz** [woocommerce/woocommerce#23342]
Now I have the attribute slug registered in russian language, and this causes errors in the pagination of goods on the Elementor.

I want to change the slug to English language (материал -> material)

But when I change the attribute slug, this attribute is removed from all products.

**Comment by mikejolley** [comment]
This will be fixed with https://github.com/woocommerce/woocommerce/pull/23132

Thanks

**Comment by igorek-zxz** [comment]
I'm sorry but I do not understand. How do I rename the existing attribute slug?
Please write more details.

**Comment by igorek-zxz** [comment]
@mikejolley <https://github.com/mikejolley> , I'm sorry but I do not
understand. How do I rename the existing attribute slug? It is not work....
watch this video
https://drive.google.com/file/d/1vALWlhDP5WVHwqRrIH_sJ5SA3tVnhHR9/view?usp=sharing
Please write more details.

ср, 17 апр. 2019 г. в 17:21, Mike Jolley <notifications@github.com>:
