### ISSUE TITLE
iconv(): Detected an illegal character in input string

### ISSUE THREAD

**Issue by orestis-s** [woocommerce/woocommerce#23348]
**Describe the bug**
iconv() used in wc_ascii_uasort_comparison() in plugins\woocommerce\includes\wc-core-functions.php at line 1627 and line 1628 generates a notice when input string contains greek characters
Example string is: Αυστραλία (translation of Australia)

**To Reproduce**
1. Go to any woocommerce page
2. See the notice

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
WordPress address (URL): http://localhost/wc36
Site address (URL): http://localhost/wc36
WC Version: 3.6.0
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: el
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.23 (Win64) mod_fcgid/2.3.9 OpenSSL/1.0.2j PHP/7.2.2
PHP Version: 7.2.2
PHP Post Max Size: 1 GB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 7.57.0
OpenSSL/1.1.0g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.20-MariaDB
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 34.48MB
Database Data Size: 18.78MB
Database Index Size: 15.70MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.09MB + Index: 0.09MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.06MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 2.19MB + Index: 0.06MB
wp_postmeta: Data: 8.50MB + Index: 11.02MB
wp_posts: Data: 2.52MB + Index: 0.63MB
wp_termmeta: Data: 0.09MB + Index: 0.14MB
wp_terms: Data: 0.09MB + Index: 0.11MB
wp_term_relationships: Data: 0.20MB + Index: 0.13MB
wp_term_taxonomy: Data: 0.38MB + Index: 0.11MB
wp_usermeta: Data: 0.50MB + Index: 0.52MB
wp_users: Data: 0.05MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.17MB + Index: 0.34MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
```
</details>

**Comment by claudiosanches** [comment]
> Go to any woocommerce page
> See the notice

I'm unable to reproduce this issue with the steps reported.

>  iconv() used in wc_ascii_uasort_comparison() in plugins\woocommerce\includes\wc-core-functions.php at line 1627 and line 1628 generates a notice when input string contains greek characters

Also what is the full error message? It's a warning or a fatal error?

**Comment by claudiosanches** [comment]
Without the full message it's hard to debug, but you should try check with your server support about iconv, if all requirements are satisfied: https://www.php.net/manual/en/iconv.requirements.php

**Comment by orestis-s** [comment]
The full notice is shown below. It's just a notice, but still...
The notice goes away when changing the //TRANSLIT option to //IGNORE, but that breaks the sort function.

Notice: iconv(): Detected an illegal character in input string in C:\Server\wc36\wp-content\plugins\woocommerce\includes\wc-core-functions.php on line 1628

**Comment by claudiosanches** [comment]
Sounds related to your installation, have you access for a terminal?
Can you check the output of the `locale`?

This is how output for me:

![Screenshot from 2019-04-17 14-58-34](https://user-images.githubusercontent.com/1264099/56310075-4e7ada80-6121-11e9-806e-46961036a45e.png)

**Comment by orestis-s** [comment]
You were right! I can't reproduce it on the staging/production environment. The issue only appears on our dev machines (running windows).

Closing this for now.
Thanks for your time anyway :)

**Comment by claudiosanches** [comment]
@orestis-s thanks for let me know, good to know that this may happens on windows, maybe is just your dev environment.

**Comment by sungil** [comment]
Hello I don't know how to check output of the locale on terminal.
Can you explain in detail?

**Comment by claudiosanches** [comment]
@sungil this has been already fixed in WooCommerce 3.6.2.

**Comment by sungil** [comment]
No, I am using woocommerce 3.6.2. you said it just relates to my dev environment.
But I don't know how to change my dev environment.

**Comment by claudiosanches** [comment]
@sungil need to install the necessary PHP libraries to make it work.
Here you can find installation guide and requirements: https://www.php.net/manual/en/book.iconv.php

**Comment by sungil** [comment]
no it is installed and enabled on my local

**Comment by claudiosanches** [comment]
Maybe outdated?

This is from my environment:

![Screenshot from 2019-05-16 16-37-44](https://user-images.githubusercontent.com/1264099/57881965-f525ca00-77f8-11e9-99a8-d56aa39e61c4.png)
