### ISSUE TITLE
Retrieve orders by date modified in 3.6

### ISSUE THREAD

**Issue by MioPedersen** [woocommerce/woocommerce#23341]
In the wc-api-dev it is mentioned that filtering by date_modified in the REST API would be available in WooCommerce 3.6, but after reading the change log I could not seem to find it mentioned?

Will WooCommerce 3.6 support this feature? We have been waiting for it for a long time, and it is pretty critical for our integration.

I opened a new issue because commenting was limited to collaborators on the other thread and the new thread remained unanswered.

**Comment by mikejolley** [comment]
Do you have a link to the thread you're talking about?

**Comment by mikejolley** [comment]
Ok I found it, and the duplicate issue so closing this one.
