### ISSUE TITLE
Subtotal Wrong When Changing Tax Class

### ISSUE THREAD

**Issue by trogdoor9432** [woocommerce/woocommerce#23340]
**The bug**
When ‘Prices entered with tax’ is set to Yes in WooCommerce settings and using 'woocommerce_product_get_tax_class' hook to change the tax class, the subtotal is wrong (0.01 more than it should be)

**To Reproduce**:
1. Setup 2 tax rates, 1 default tax rate (Default 5% and an additional tax rate set to 20%)
2. Ensure ‘Prices entered with tax’ is set to Yes in WooCommerce settings
3. Ensure 'Display prices during basket and checkout' is set to 'Excluding tax' for easier viewing
4. Enter a product into WooCommerce with a price of 6 and assign as taxable and using the default tax rate (5%)
5. Add this product to your basket and go to the basket page, you'll see the subtotal is 5.71
6. Add the code below and refresh the basket, you'll see the subtotal is now 5.72

Example code;

```
function set_tax_rate( $tax_class, $product ) {
    $tax_class = '20% VAT'; // 20% Tax
    return $tax_class;
}
add_filter( 'woocommerce_product_get_tax_class', 'set_tax_rate', 1, 2 );
add_filter( 'woocommerce_product_variation_get_tax_class', 'set_tax_rate', 1, 2 );
```

**Screenshots**
![basket](https://user-images.githubusercontent.com/49720101/56288217-36518e00-6116-11e9-91b4-bb6568f430b7.png)
![tax_20](https://user-images.githubusercontent.com/49720101/56288218-36518e00-6116-11e9-8b5d-8d2ba9946ce5.png)
![tax-standard](https://user-images.githubusercontent.com/49720101/56288219-36518e00-6116-11e9-96a2-ce5aee5a0393.png)
![wc_tax_options](https://user-images.githubusercontent.com/49720101/56288220-36518e00-6116-11e9-81d5-d44dc315f8f2.png)

**Expected behavior**
Subtotal should be 5.71 after changing tax class with 'woocommerce_product_get_tax_class',

**Isolating the problem (mark completed items with an [x]):**
- I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- This bug happens with a default WordPress theme active (I'm using Twenty Nineteen)
- I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: http://rh.local
Site URL: http://rh.local
WC Version: 3.5.8
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: nginx/1.10.1
PHP Version: 7.2.0
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 1,000 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.8
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 3.63MB
Database Data Size: 2.40MB
Database Index Size: 1.23MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_newsletter: Data: 0.02MB + Index: 0.03MB
wp_newsletter_emails: Data: 0.02MB + Index: 0.00MB
wp_newsletter_sent: Data: 0.02MB + Index: 0.03MB
wp_newsletter_stats: Data: 0.02MB + Index: 0.03MB
wp_newsletter_user_logs: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 1.06MB + Index: 0.05MB
wp_postmeta: Data: 0.39MB + Index: 0.27MB
wp_posts: Data: 0.31MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

acf-field: 108
acf-field-group: 6
attachment: 33
clients: 2
customize_changeset: 1
modula-gallery: 1
nav_menu_item: 25
page: 12
post: 3
product: 1
revision: 35
sa_slider: 1
sp_wp_carousel: 4

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (7) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.7.12
Classic Editor: by WordPress Contributors – 1.4
Newsletter - WooCommerce: by The Newsletter Team – 1.3.5
Newsletter: by Stefano Lissa & The Newsletter Team – 5.9.2
WooCommerce: by Automattic – 3.5.8
Yoast SEO: by Team Yoast – 11.0
WordPress Carousel Pro: by ShapedPlugin – 3.0.4 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #238 - /shop/
Basket: #239 - /cart/
Checkout: #240 - /checkout/
My account: #241 - /my-account/
Terms and conditions: #260 - /terms-and-conditions/

### Theme ###

Name: Twenty Nineteen
Version: 1.3
Author URL: https://en-gb.wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –
`
</details>

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23344
