### ISSUE TITLE
Opinion on warning "OfferCount" in structured data ? 

### ISSUE THREAD

**Issue by Hugo44** [woocommerce/woocommerce#23347]
Hello,

I've seen different topics about resolving warnings in the Google Search Console.
Most of them have been solved by following the advice on this forum.

However, I do not find the solution to the problem of variable products and the warning: “Offercount" field is missing.

When we look at an example of this data on the site: https://schema.org/offerCount
This data is represented as follows :
 "offers": {
    "@type": "AggregateOffer",
  "lowPrice": "$35",
    **"offerCount": "1938"**
  },

So yes; it is an optional data but represents a warning anyway and does not allow the complete validity of the product by Google for variable products of Woocommerce.
I think that the aspect of a product fully validated by the search console should not be neglected for SEO.
Thanks for your feedback.

**Comment by claudiosanches** [comment]
See https://github.com/woocommerce/woocommerce/pull/23349

**Comment by Hugo44** [comment]
The warning message is gone with these new lines:

						'@type'      => 'AggregateOffer',
						'lowPrice'   => wc_format_decimal( $lowest, wc_get_price_decimals() ),
						'highPrice'  => wc_format_decimal( $highest, wc_get_price_decimals() ),
						**'offerCount' => count( $product->get_children() ),**


Thank you so much!
