### ISSUE TITLE
Singapore Town Field Validation

### ISSUE THREAD

**Issue by kauyiming** [woocommerce/woocommerce#23345]
When at checking out, after clicking Checkout, a form validation will require the billing town to be filled.  However for Singapore, this field does not need to be filled.  Furthermore, it remains hidden. 

As discussed #21016 and #21018

<img width="1017" alt="Screen Shot 2019-04-17 at 11 51 06 pm" src="https://user-images.githubusercontent.com/49726809/56302583-ad197600-616c-11e9-8b23-cd4b931a1159.png">

**Comment by mikejolley** [comment]
It's hidden and non-required. I just tested and there is no validation message for city on a clean install with singapore selected. 

Go through the isolation steps listed on the new issue form https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=

Closing as non-reproducable/imcomplete.
