### ISSUE TITLE
Some shipping methods incorrectly apply Tax for wrong country

### ISSUE THREAD

**Issue by njeffers** [woocommerce/woocommerce#23358]
This is a very odd bug, and I've done everything that I can think of to try and prevent it from happening. Fresh, bone stock install with WP 5.1.1, WC 3.6.1, Official WC Stripe 4.1.15, Twenty Nineteen.

**To Reproduce**
1. Add a Product
2. Set store to have an Australian (New South Wales in my case) address. 
3. Enable Tax Rates & Calculations
4. Save and Go to Tax tab.
5. Prices entered with tax -> No, I will enter prices exclusive of tax
5b. Calculate tax based on ->Customer Shipping Address
5c. Shipping tax class -> Standard
5d. The rest is definitely stock, but not sure if I changed the three above.
6. Tax -> Standard Rates (see below)
![image](https://user-images.githubusercontent.com/10125982/56331231-4f6f3480-6140-11e9-9176-81b6f114a4fd.png)
7. Shipping.
7b. I have Local Pickup for Australia.
7c. I have New Zealand with Local Pickup (tax status -> None, Cost -> 0), Flat Rate (tax status -> Taxable, Cost -> 0)
8. Go to the frontend and add a product. 
9. In Cart, do shipping calculations, and set your country to anywhere in New Zealand.
10. Play around with the radio buttons for the different shipping rates, and you'll have GST show up for your Tax, which should be specific to Australia.

I did notice that this happened on the live site, as well as the stock install when selecting the Local Pickup option. I'm not sure if that's always the case, as YMMV.

**Screenshots**
![image](https://user-images.githubusercontent.com/10125982/56331296-9c530b00-6140-11e9-9065-f5fd6d191471.png)

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://localhost/emtrontest
Site address (URL): http://localhost/emtrontest
WC Version: 3.6.1
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.37 (Win64) PHP/7.2.14
PHP Version: 7.2.14
PHP Post Max Size: 8 MB
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.61.1
OpenSSL/1.1.1a

SUHOSIN Installed: –
MySQL Version: 5.7.24
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 0.83MB
Database Data Size: 0.70MB
Database Index Size: 0.13MB
wp_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_comments: Data: 0.00MB + Index: 0.01MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 0.68MB + Index: 0.04MB
wp_postmeta: Data: 0.00MB + Index: 0.01MB
wp_posts: Data: 0.01MB + Index: 0.01MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.00MB + Index: 0.00MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_usermeta: Data: 0.00MB + Index: 0.01MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_table_rates: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 1
page: 6
post: 2
product: 1
scheduled-action: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Stripe Gateway: by WooCommerce – 4.1.15 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.6.1

### Inactive Plugins (6) ###

Akismet Anti-Spam: by Automattic – 4.1.1
Hello Dolly: by Matt Mullenweg – 1.7.1
Jetpack by WordPress.com: by Automattic – 7.2.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.11
WooCommerce Services: by Automattic – 1.19.0 – Not tested with the active version of WooCommerce
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.15

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #11 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Nineteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2019-04-18 01:02:05 +0000
Newest: 2019-04-18 01:02:05 +0000

Pending: 1
Oldest: 2019-04-25 01:02:05 +0000
Newest: 2019-04-25 01:02:05 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by mikejolley** [comment]
It's local pickup.

> By default, when using local pickup store base taxes will apply regardless of customer address.

There are some snippets available to change this behaviour:

https://docs.woocommerce.com/document/local-pickup/#section-6

Thanks

**Comment by njeffers** [comment]
Hi @mikejolley,

Thanks for the quick reply. This fixed it. 

I know the ticket's closed, but I feel like the settings for Local Pickup could use some adjusting to clarify, and hopefully prevent anyone else from doing the same.

I'm a little under the weather, so my brain might not be functioning properly, but with the filter being needed, I feel like the "Tax status" dropdown is a little confusing. When trying to get this tax behavior to stop, I set it to None, expecting it to stop taxing it. It seems I'm wrong in that thinking, so not sure if that should be changed or what. I now realize that it's applying to tax on top of the additional cost (if set) for this shipping option.

I feel like adding a simple "?" bubble (like the other two items) specifying this trick may help, although my case may be a weird, rare outlier case that's not worth making changes for.

Thanks again.

![image](https://user-images.githubusercontent.com/10125982/56392893-92d0ae00-61e7-11e9-9c5f-cd7e0a9e82fe.png)
