### ISSUE TITLE
get_gallery_image_ids return an empty array in content-single-product.php custom template file

### ISSUE THREAD

**Issue by julienfelixweb** [woocommerce/woocommerce#23357]
**Describe the bug**
Since I updated my WC template for the version 3.6.0, the function echo get_gallery_image_ids return an empty array. I use it directly in the content-single-product.php file.

**Screenshots**
<img width="241" alt="Capture d’écran 2019-04-18 à 01 47 15" src="https://user-images.githubusercontent.com/770119/56327756-32585700-617c-11e9-9720-e3c3389fd0e2.png">
<img width="298" alt="Capture d’écran 2019-04-18 à 01 47 32" src="https://user-images.githubusercontent.com/770119/56327758-32f0ed80-617c-11e9-97d3-d5a155b2debc.png">

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

`
### WordPress Environment ###

WordPress address (URL): https://fondationantoinedegalbert.org
Site address (URL): https://fondationantoinedegalbert.org
WC Version: 3.6.0
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.13
PHP Post Max Size: 128 MB
PHP Time Limit: 180
PHP Max Input Vars: 2500
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.7.23-23-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.0
WC Database Prefix: jfw_
MaxMind GeoIP Database: ✔
Taille totale de la base de données: 43.53MB
Taille de la base de données: 28.00MB
Taille de l’index: 15.53MB
jfw_woocommerce_sessions: Données : 0.02MB + Index: 0.02MB
jfw_woocommerce_api_keys: Données : 0.02MB + Index: 0.03MB
jfw_woocommerce_attribute_taxonomies: Données : 0.02MB + Index: 0.02MB
jfw_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index: 0.05MB
jfw_woocommerce_order_items: Données : 0.02MB + Index: 0.02MB
jfw_woocommerce_order_itemmeta: Données : 0.02MB + Index: 0.03MB
jfw_woocommerce_tax_rates: Données : 0.02MB + Index: 0.06MB
jfw_woocommerce_tax_rate_locations: Données : 0.02MB + Index: 0.03MB
jfw_woocommerce_shipping_zones: Données : 0.02MB + Index: 0.00MB
jfw_woocommerce_shipping_zone_locations: Données : 0.02MB + Index: 0.03MB
jfw_woocommerce_shipping_zone_methods: Données : 0.02MB + Index: 0.00MB
jfw_woocommerce_payment_tokens: Données : 0.02MB + Index: 0.02MB
jfw_woocommerce_payment_tokenmeta: Données : 0.02MB + Index: 0.03MB
jfw_woocommerce_log: Données : 0.02MB + Index: 0.02MB
jfw_commentmeta: Données : 0.02MB + Index: 0.03MB
jfw_comments: Données : 0.02MB + Index: 0.09MB
jfw_icl_content_status: Données : 0.02MB + Index: 0.02MB
jfw_icl_core_status: Données : 0.02MB + Index: 0.02MB
jfw_icl_flags: Données : 0.02MB + Index: 0.02MB
jfw_icl_languages: Données : 0.02MB + Index: 0.03MB
jfw_icl_languages_translations: Données : 0.19MB + Index: 0.11MB
jfw_icl_locale_map: Données : 0.02MB + Index: 0.00MB
jfw_icl_message_status: Données : 0.02MB + Index: 0.03MB
jfw_icl_mo_files_domains: Données : 0.02MB + Index: 0.02MB
jfw_icl_node: Données : 0.02MB + Index: 0.00MB
jfw_icl_reminders: Données : 0.02MB + Index: 0.00MB
jfw_icl_strings: Données : 4.52MB + Index: 4.89MB
jfw_icl_string_packages: Données : 0.02MB + Index: 0.00MB
jfw_icl_string_pages: Données : 8.52MB + Index: 6.52MB
jfw_icl_string_positions: Données : 0.02MB + Index: 0.02MB
jfw_icl_string_status: Données : 0.02MB + Index: 0.02MB
jfw_icl_string_translations: Données : 2.52MB + Index: 0.42MB
jfw_icl_string_urls: Données : 0.06MB + Index: 0.05MB
jfw_icl_translate: Données : 0.05MB + Index: 0.02MB
jfw_icl_translate_job: Données : 0.02MB + Index: 0.02MB
jfw_icl_translations: Données : 0.08MB + Index: 0.22MB
jfw_icl_translation_batches: Données : 0.02MB + Index: 0.00MB
jfw_icl_translation_status: Données : 0.13MB + Index: 0.02MB
jfw_links: Données : 0.02MB + Index: 0.02MB
jfw_options: Données : 5.05MB + Index: 0.08MB
jfw_postmeta: Données : 4.38MB + Index: 1.81MB
jfw_posts: Données : 1.52MB + Index: 0.30MB
jfw_termmeta: Données : 0.02MB + Index: 0.03MB
jfw_terms: Données : 0.02MB + Index: 0.03MB
jfw_term_relationships: Données : 0.02MB + Index: 0.02MB
jfw_term_taxonomy: Données : 0.02MB + Index: 0.03MB
jfw_usermeta: Données : 0.05MB + Index: 0.03MB
jfw_users: Données : 0.02MB + Index: 0.05MB
jfw_wc_download_log: Données : 0.02MB + Index: 0.03MB
jfw_wc_product_meta_lookup: Données : 0.02MB + Index: 0.09MB
jfw_wc_webhooks: Données : 0.02MB + Index: 0.02MB
jfw_woocommerce_bnpmercanetcw_customer_contexts: Données : 0.02MB + Index: 0.02MB
jfw_woocommerce_bnpmercanetcw_documents: Données : 0.02MB + Index: 0.02MB
jfw_woocommerce_bnpmercanetcw_ecc: Données : 0.02MB + Index: 0.00MB
jfw_woocommerce_bnpmercanetcw_schema_version: Données : 0.02MB + Index: 0.02MB
jfw_woocommerce_bnpmercanetcw_storage: Données : 0.02MB + Index: 0.00MB
jfw_woocommerce_bnpmercanetcw_transactions: Données : 0.05MB + Index: 0.00MB

### Post Type Counts ###

acf-field: 20
acf-field-group: 9
attachment: 738
nav_menu_item: 14
newsletter: 2
page: 32
post: 1
product: 70
revision: 299
scheduled-action: 16
shop_order: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (16) ###

WPML Multilingual CMS: par OnTheGoSystems – 4.2.5
Advanced Custom Fields PRO: par Elliot Condon – 5.7.13
Classic Editor: par Contributeurs et contributrices WordPress – 1.4
Font Awesome: par Font Awesome – 4.0.0-rc9
Jetpack par WordPress.com: par Automattic – 7.2.1
Mailjet for WordPress: par Mailjet SAS – 5.0.11
Rearrange Woocommerce Products: par Aslam Doctor – 1.1 – Non testé avec la version active de WooCommerce
Woo Preview Emails: par Digamber Pradhan – 1.5.0 – Non testé avec la version active de WooCommerce
WooCommerce Multilingual: par OnTheGoSystems – 4.6.0
WooCommerce: par Automattic – 3.6.0
WooCommerce BNPMercanetCw: par customweb GmbH – 2.0.219 – Non testé avec la version active de WooCommerce
WP Migrate DB Pro Media Files: par Delicious Brains – 1.4.13
WP Migrate DB Pro: par Delicious Brains – 1.9.5
WP-Matomo: par André Bräkling – 1.0.21
WPML String Translation: par OnTheGoSystems – 2.10.3
WPML Translation Management: par OnTheGoSystems – 2.8.4

### Must Use Plugins (1) ###

WP Migrate DB Pro Compatibility: par Delicious Brains – 1.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Base de la boutique: #5 - /librairie/
Panier: #6 - /panier/
Validation de la commande: #7 - /commande/
Mon compte: #8 - /mon-compte/
Conditions générales de vente et d’utilisation: #333 - /conditions-generales-de-vente/

### Theme ###

Name: Fondation Antoine de Galbert
Version: 1.0
Author URL: https://www.julienfelix.com/
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: jfw_fondationantoinedegalbert/woocommerce/archive-product.php
jfw_fondationantoinedegalbert/woocommerce/auth/footer.php
jfw_fondationantoinedegalbert/woocommerce/auth/form-grant-access.php
jfw_fondationantoinedegalbert/woocommerce/auth/form-login.php
jfw_fondationantoinedegalbert/woocommerce/auth/header.php
jfw_fondationantoinedegalbert/woocommerce/cart/cart-empty.php
jfw_fondationantoinedegalbert/woocommerce/cart/cart-item-data.php
jfw_fondationantoinedegalbert/woocommerce/cart/cart-shipping.php
jfw_fondationantoinedegalbert/woocommerce/cart/cart-totals.php
jfw_fondationantoinedegalbert/woocommerce/cart/cart.php
jfw_fondationantoinedegalbert/woocommerce/cart/cross-sells.php
jfw_fondationantoinedegalbert/woocommerce/cart/mini-cart.php
jfw_fondationantoinedegalbert/woocommerce/cart/proceed-to-checkout-button.php
jfw_fondationantoinedegalbert/woocommerce/cart/shipping-calculator.php
jfw_fondationantoinedegalbert/woocommerce/checkout/cart-errors.php
jfw_fondationantoinedegalbert/woocommerce/checkout/form-billing.php
jfw_fondationantoinedegalbert/woocommerce/checkout/form-checkout.php
jfw_fondationantoinedegalbert/woocommerce/checkout/form-coupon.php
jfw_fondationantoinedegalbert/woocommerce/checkout/form-login.php
jfw_fondationantoinedegalbert/woocommerce/checkout/form-pay.php
jfw_fondationantoinedegalbert/woocommerce/checkout/form-shipping.php
jfw_fondationantoinedegalbert/woocommerce/checkout/order-receipt.php
jfw_fondationantoinedegalbert/woocommerce/checkout/payment-method.php
jfw_fondationantoinedegalbert/woocommerce/checkout/payment.php
jfw_fondationantoinedegalbert/woocommerce/checkout/review-order.php
jfw_fondationantoinedegalbert/woocommerce/checkout/terms.php
jfw_fondationantoinedegalbert/woocommerce/checkout/thankyou.php
jfw_fondationantoinedegalbert/woocommerce/content-product.php
jfw_fondationantoinedegalbert/woocommerce/content-product_cat.php
jfw_fondationantoinedegalbert/woocommerce/content-single-product.php
jfw_fondationantoinedegalbert/woocommerce/content-widget-product.php
jfw_fondationantoinedegalbert/woocommerce/content-widget-reviews.php
jfw_fondationantoinedegalbert/woocommerce/emails/admin-cancelled-order.php
jfw_fondationantoinedegalbert/woocommerce/emails/admin-failed-order.php
jfw_fondationantoinedegalbert/woocommerce/emails/admin-new-order.php
jfw_fondationantoinedegalbert/woocommerce/emails/customer-completed-order.php
jfw_fondationantoinedegalbert/woocommerce/emails/customer-invoice.php
jfw_fondationantoinedegalbert/woocommerce/emails/customer-new-account.php
jfw_fondationantoinedegalbert/woocommerce/emails/customer-note.php
jfw_fondationantoinedegalbert/woocommerce/emails/customer-on-hold-order.php
jfw_fondationantoinedegalbert/woocommerce/emails/customer-processing-order.php
jfw_fondationantoinedegalbert/woocommerce/emails/customer-refunded-order.php
jfw_fondationantoinedegalbert/woocommerce/emails/customer-reset-password.php
jfw_fondationantoinedegalbert/woocommerce/emails/email-addresses.php
jfw_fondationantoinedegalbert/woocommerce/emails/email-customer-details.php
jfw_fondationantoinedegalbert/woocommerce/emails/email-downloads.php
jfw_fondationantoinedegalbert/woocommerce/emails/email-footer.php
jfw_fondationantoinedegalbert/woocommerce/emails/email-header.php
jfw_fondationantoinedegalbert/woocommerce/emails/email-order-details.php
jfw_fondationantoinedegalbert/woocommerce/emails/email-order-items.php
jfw_fondationantoinedegalbert/woocommerce/emails/email-styles.php
jfw_fondationantoinedegalbert/woocommerce/emails/plain/admin-cancelled-order.php
jfw_fondationantoinedegalbert/woocommerce/emails/plain/admin-failed-order.php
jfw_fondationantoinedegalbert/woocommerce/emails/plain/admin-new-order.php
jfw_fondationantoinedegalbert/woocommerce/emails/plain/customer-completed-order.php
jfw_fondationantoinedegalbert/woocommerce/emails/plain/customer-invoice.php
jfw_fondationantoinedegalbert/woocommerce/emails/plain/customer-new-account.php
jfw_fondationantoinedegalbert/woocommerce/emails/plain/customer-note.php
jfw_fondationantoinedegalbert/woocommerce/emails/plain/customer-on-hold-order.php
jfw_fondationantoinedegalbert/woocommerce/emails/plain/customer-processing-order.php
jfw_fondationantoinedegalbert/woocommerce/emails/plain/customer-refunded-order.php
jfw_fondationantoinedegalbert/woocommerce/emails/plain/customer-reset-password.php
jfw_fondationantoinedegalbert/woocommerce/emails/plain/email-addresses.php
jfw_fondationantoinedegalbert/woocommerce/emails/plain/email-customer-details.php
jfw_fondationantoinedegalbert/woocommerce/emails/plain/email-downloads.php
jfw_fondationantoinedegalbert/woocommerce/emails/plain/email-order-details.php
jfw_fondationantoinedegalbert/woocommerce/emails/plain/email-order-items.php
jfw_fondationantoinedegalbert/woocommerce/global/breadcrumb.php
jfw_fondationantoinedegalbert/woocommerce/global/form-login.php
jfw_fondationantoinedegalbert/woocommerce/global/quantity-input.php
jfw_fondationantoinedegalbert/woocommerce/global/sidebar.php
jfw_fondationantoinedegalbert/woocommerce/global/wrapper-end.php
jfw_fondationantoinedegalbert/woocommerce/global/wrapper-start.php
jfw_fondationantoinedegalbert/woocommerce/loop/add-to-cart.php
jfw_fondationantoinedegalbert/woocommerce/loop/loop-end.php
jfw_fondationantoinedegalbert/woocommerce/loop/loop-start.php
jfw_fondationantoinedegalbert/woocommerce/loop/no-products-found.php
jfw_fondationantoinedegalbert/woocommerce/loop/orderby.php
jfw_fondationantoinedegalbert/woocommerce/loop/pagination.php
jfw_fondationantoinedegalbert/woocommerce/loop/price.php
jfw_fondationantoinedegalbert/woocommerce/loop/rating.php
jfw_fondationantoinedegalbert/woocommerce/loop/result-count.php
jfw_fondationantoinedegalbert/woocommerce/loop/sale-flash.php
jfw_fondationantoinedegalbert/woocommerce/myaccount/dashboard.php
jfw_fondationantoinedegalbert/woocommerce/myaccount/downloads.php
jfw_fondationantoinedegalbert/woocommerce/myaccount/form-add-payment-method.php
jfw_fondationantoinedegalbert/woocommerce/myaccount/form-edit-account.php
jfw_fondationantoinedegalbert/woocommerce/myaccount/form-edit-address.php
jfw_fondationantoinedegalbert/woocommerce/myaccount/form-login.php
jfw_fondationantoinedegalbert/woocommerce/myaccount/form-lost-password.php
jfw_fondationantoinedegalbert/woocommerce/myaccount/form-reset-password.php
jfw_fondationantoinedegalbert/woocommerce/myaccount/lost-password-confirmation.php
jfw_fondationantoinedegalbert/woocommerce/myaccount/my-account.php
jfw_fondationantoinedegalbert/woocommerce/myaccount/my-address.php
jfw_fondationantoinedegalbert/woocommerce/myaccount/my-downloads.php
jfw_fondationantoinedegalbert/woocommerce/myaccount/my-orders.php
jfw_fondationantoinedegalbert/woocommerce/myaccount/navigation.php
jfw_fondationantoinedegalbert/woocommerce/myaccount/orders.php
jfw_fondationantoinedegalbert/woocommerce/myaccount/payment-methods.php
jfw_fondationantoinedegalbert/woocommerce/myaccount/view-order.php
jfw_fondationantoinedegalbert/woocommerce/notices/error.php
jfw_fondationantoinedegalbert/woocommerce/notices/notice.php
jfw_fondationantoinedegalbert/woocommerce/notices/success.php
jfw_fondationantoinedegalbert/woocommerce/order/form-tracking.php
jfw_fondationantoinedegalbert/woocommerce/order/order-again.php
jfw_fondationantoinedegalbert/woocommerce/order/order-details-customer.php
jfw_fondationantoinedegalbert/woocommerce/order/order-details-item.php
jfw_fondationantoinedegalbert/woocommerce/order/order-details.php
jfw_fondationantoinedegalbert/woocommerce/order/order-downloads.php
jfw_fondationantoinedegalbert/woocommerce/order/tracking.php
jfw_fondationantoinedegalbert/woocommerce/product-searchform.php
jfw_fondationantoinedegalbert/woocommerce/single-product/add-to-cart/external.php
jfw_fondationantoinedegalbert/woocommerce/single-product/add-to-cart/grouped.php
jfw_fondationantoinedegalbert/woocommerce/single-product/add-to-cart/simple.php
jfw_fondationantoinedegalbert/woocommerce/single-product/add-to-cart/variable.php
jfw_fondationantoinedegalbert/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
jfw_fondationantoinedegalbert/woocommerce/single-product/add-to-cart/variation.php
jfw_fondationantoinedegalbert/woocommerce/single-product/meta.php
jfw_fondationantoinedegalbert/woocommerce/single-product/photoswipe.php
jfw_fondationantoinedegalbert/woocommerce/single-product/price.php
jfw_fondationantoinedegalbert/woocommerce/single-product/product-attributes.php
jfw_fondationantoinedegalbert/woocommerce/single-product/product-image.php
jfw_fondationantoinedegalbert/woocommerce/single-product/product-thumbnails.php
jfw_fondationantoinedegalbert/woocommerce/single-product/rating.php
jfw_fondationantoinedegalbert/woocommerce/single-product/related.php
jfw_fondationantoinedegalbert/woocommerce/single-product/review-meta.php
jfw_fondationantoinedegalbert/woocommerce/single-product/review-rating.php
jfw_fondationantoinedegalbert/woocommerce/single-product/review.php
jfw_fondationantoinedegalbert/woocommerce/single-product/sale-flash.php
jfw_fondationantoinedegalbert/woocommerce/single-product/share.php
jfw_fondationantoinedegalbert/woocommerce/single-product/short-description.php
jfw_fondationantoinedegalbert/woocommerce/single-product/stock.php
jfw_fondationantoinedegalbert/woocommerce/single-product/tabs/additional-information.php
jfw_fondationantoinedegalbert/woocommerce/single-product/tabs/description.php
jfw_fondationantoinedegalbert/woocommerce/single-product/tabs/tabs.php
jfw_fondationantoinedegalbert/woocommerce/single-product/title.php
jfw_fondationantoinedegalbert/woocommerce/single-product/up-sells.php
jfw_fondationantoinedegalbert/woocommerce/single-product-reviews.php
jfw_fondationantoinedegalbert/woocommerce/single-product.php
jfw_fondationantoinedegalbert/woocommerce/taxonomy-product_cat.php
jfw_fondationantoinedegalbert/woocommerce/taxonomy-product_tag.php

### Action Scheduler ###

Complete: 15
Oldest: 2019-04-18 00:41:56 +0200
Newest: 2019-04-18 00:44:10 +0200

Pending: 1
Oldest: 2019-04-25 00:41:56 +0200
Newest: 2019-04-25 00:41:56 +0200

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by kloon** [comment]
@julienfelixweb I am not able to reproduce this with 3.6.1, see my example call below on a product with one image in the gallery

```
wp> wc_get_product( 74287 )->get_gallery_image_ids();
=> array(1) {
  [0]=>
  int(60)
}
```

I would double check that the product you are calling actually has gallery images and not just a single product image. Featured image does not get returned by get_gallery_image_ids only the gallery image does.

If you are looking for the main/featured product image then use the get_image_id method of the product.

Closing, will gladly reopen if I have clear steps to replicate this with example code you are using.

**Comment by herbert-lubbertsen** [comment]
I have same issue. 

wc_get_product( 1598 )->get_gallery_image_ids()
returns NULL

$product->get_gallery_image_ids();
returns array(0) { }

In product admin gallery is filled.

**Comment by julienfelixweb** [comment]
I Herbert,

I was able to find a work around. after deactivate all plugins and activate them one after the other. I was able to find an issue with the plugin "WPML Translation Management". It seems that the product galleries only appears in English using WPML after updating WC in 3.6.0.

I fixed it using this filter to retrieve the English ID of the post (my main language is French).

`$default_lang_id = apply_filters( 'wpml_object_id', $product->get_id(), 'page', TRUE, 'en' );`

And the galleries showed up as before the update.

Hope it will help you.

Best

**Comment by nikoioan** [comment]
The problem still exists in WC Version 3.6.1
I confirm that the problem is the "WPML Translation Management".
I have opened a ticket to tehm and waiting for their reply.
Is there anyother workaround?

**Comment by Djules** [comment]
Some workarounds [here](https://wpml.org/forums/topic/urgent-product-gallery-not-showing-when-wpml-is-activated/), while they're working on a fix.
