### ISSUE TITLE
[3.6] SelectWoo encoding "/"

### ISSUE THREAD

**Issue by claudiosanches** [woocommerce/woocommerce#23351]
**Describe the bug**

SelectWoo is converting `/` to `&#47;` when display values on the front-end.

Reported on https://wordpress.org/support/topic/strange-ascii-text-after-the-3-6-0-update-in-the-check-out-placeholder/

**To Reproduce**

1. Set site's language to default en_US
2. Add a product to the cart
3. Go the checkout
4. Select the country as `South Georgia/Sandwich Islands`
5. Check that `/` is converted to `&#47;` after selected.

**Screenshots**

![Screenshot from 2019-04-17 15-48-04](https://user-images.githubusercontent.com/1264099/56314219-d1546300-612a-11e9-929b-95197fbd4220.png)

**Expected behavior**

No more `&#47;`.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mikejolley** [comment]
Fixed by https://github.com/woocommerce/woocommerce/pull/23334

**Comment by claudiosanches** [comment]
@mikejolley :man_facepalming: I forget about that PR.
