### ISSUE TITLE
issue with wc_ascii_uasort_comparison

### ISSUE THREAD

**Issue by nbastreet** [woocommerce/woocommerce#23361]
Hi.
After updating to woocommerce 3.6.0 and 3.6.1 also, i get many Notice in my site like this:

Notice: iconv(): Detected an illegal character in input string in ...\wp-content\plugins\woocommerce\includes\wc-core-functions.php on line 1627

Notice: iconv(): Detected an illegal character in input string in ...\wp-content\plugins\woocommerce\includes\wc-core-functions.php on line 1628

I am trying to disable all other plugins and use wordpress default theme but notice still exist!

**Comment by kloon** [comment]
Thanks, busy investigating.

**Comment by kloon** [comment]
See fix in #23363 Would appreciate if you can perhaps give that a test and report if it fixes the issue for you?

**Comment by nbastreet** [comment]
No issue still exist and many notice are in all pages and alphabetical ordering is incorrect

**Comment by nbastreet** [comment]
below change fixed the notice issue but alphabetical ordering is incorrect

`function wc_ascii_uasort_comparison( $a, $b ) {
	if ( function_exists( 'iconv' ) && defined( 'ICONV_IMPL' ) && @strcasecmp( ICONV_IMPL, 'unknown' ) !== 0 ) {
		//$a = iconv( 'UTF-8', 'ASCII//IGNORE//TRANSLIT', $a );
		//$b = iconv( 'UTF-8', 'ASCII//IGNORE//TRANSLIT', $b );
		$a = @iconv( 'UTF-8', 'ASCII//TRANSLIT//IGNORE', $a );
		$b = @iconv( 'UTF-8', 'ASCII//TRANSLIT//IGNORE', $b );
	}
	return strcmp( $a, $b );
}`

**Comment by kloon** [comment]
@nbastreet yes, the since iconv is dependent on the server config we cannot control that, the fix bypasses the iconv usage and default to using uasort on the special chars when the server does not have the correct config for handling locales which will mean it will not sort alphabetically correct. See #23348 which has details on server config.

**Comment by nbastreet** [comment]
@kloon thanks, this problem is on local machine so can you disable this function on local machine?
