### ISSUE TITLE
Unable to hide WC_Cart_Widget title

### ISSUE THREAD

**Issue by drewskix86** [woocommerce/woocommerce#23368]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Use a blank title on the WC Cart Widget
2. Widget class lines 60-64 populate the title with 'Cart' again

## Expected/actual behavior

When I follow those steps, I see...
The widget title 'Cart'
I was expecting to see...
No title
## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```

WordPress environment
--
WordPress address (URL): |   | https://reefpurero.com.au
Site address (URL): |   | https://reefpurero.com.au
WooCommerce version: |   | 3.6.1
Log directory writable: |   | /home/reefpure/public_html/wp-content/uploads/wc-logs/
WordPress version: |   | 5.1.1
WordPress multisite: |   | –
WordPress memory limit: |   | 768 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_AU
External object cache: |   | –


```
</details>

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23370
