### ISSUE TITLE
Use the filter for blacklisted usernames

### ISSUE THREAD

**Issue by AndreiIgna** [woocommerce/woocommerce#23366]
Just noticed the new function `wc_create_new_customer_username` in latest update 👍🏼

One thing that can be improved is the username check. Instead of hardcoding a few disallowed usernames, they could be run through the `illegal_user_logins` filter used in WordPress and other plugins.
https://github.com/woocommerce/woocommerce/blob/0b113621a6786fdc8ec0a1b6eadbb004f8428a44/includes/wc-user-functions.php#L139

The filter in Wordpress
https://github.com/WordPress/WordPress/blob/d4d12678470e8000ffefbff8c0d097655d5ae88c/wp-includes/user.php#L2447

This way the list can be updated easier, security plugins already use this and maybe site owners wanna control this themselves.

Can create a PR if this sounds ok for WooCommerce.

**Comment by mikejolley** [comment]
Sounds good if it's in addition to the ones we hardcode 👍

**Comment by AndreiIgna** [comment]
By default the list is empty, so the ones added by WooCommerce should just go through the filter.

I see PRs are already open for this 👍🏼

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23395

**Comment by claudiosanches** [comment]
@mikejolley @AndreiIgna this feature is already implemented, since we use `wp_insert_user()`, I'll opened a new PR to improve the error messages returned by `wp_insert_user()`: https://github.com/woocommerce/woocommerce/pull/23468

**Comment by AndreiIgna** [comment]
By using it in `wc_create_new_customer_username` it can catch blacklisted usernames and potentially generating another username without generating an error.

When accounts are created from checkout page, it won't be so good to show an error related to usernames after a customers submits all the info on Checkout page.

**Comment by mikejolley** [comment]
@claudiosanches This would prevent our username generation function potentially returning names which cannot be used which later throw errors. Should we include it anyway?

**Comment by claudiosanches** [comment]
We can use that filter to exclude values from `wc_create_new_customer_username()`, I'll write a Pull Request for it too.

**Comment by claudiosanches** [comment]
@AndreiIgna @mikejolley see # #23672
