### ISSUE TITLE
Changelog: create links to issues

### ISSUE THREAD

**Issue by uok** [woocommerce/woocommerce#23376]
Thanks for the update and many improvements!

My suggestion for the [changelog on wordpress.org](https://wordpress.org/plugins/woocommerce/#developers) (which is also loaded inside wordpress plugin info during update): Please create clickable links to the issues - currently there is only text info, e.g. # 123
Thanks!

**Comment by mikejolley** [comment]
Thanks for the suggestion. Let's see about doing this for 3.7. Made a note in the PR tracking the changelog 👍

**Comment by claudiosanches** [comment]
@mikejolley easy to create a script to apply to all links that we already have.
