### ISSUE TITLE
Action Scheduler Uncaught Exception

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#23373]
Logged here https://wordpress.org/support/topic/woocommerce-database-update-running-since-6-hours/

```
Fatal error: Uncaught ActionScheduler_InvalidActionException: Action [2813] has invalid arguments. It cannot be JSON decoded to an array. in /home/www/wordpress/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_InvalidActionException.php:26 Stack trace: #0 /home/www/wordpress/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php(799): ActionScheduler_InvalidActionException::from_decoding_args(2813) #1 /home/www/wordpress/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php(135): ActionScheduler_wpPostStore->validate_args(NULL, 2813) #2 /home/www/wordpress/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php(118): ActionScheduler_wpPostStore->make_action_from_post(Object(WP_Post)) #3 /home/www/wordpress/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/functions.php(171): ActionScheduler_wpPostStore->fetch_a in /home/www/wordpress/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_InvalidActionException.php on line 26
```

*Edit to add* 

## Steps to reproduce
1. Get the post `ID` from a pending action by hovering over the run link
2. Update the `post_content` field of that post to `"valid_json_encoded_string"` or `{"data":"invalid_json"}}`.
3. reload the Tools -> Scheduled Actions screen
4. The exception will be logged to the debug log.

*End Edit*

THis is an AS issue but we'll need to hotfix core once resolved.

cc @rrennick @JPry @peterfabian

**Comment by rrennick** [comment]
@mikejolley I updated the issue description to include steps to reproduce. This should be fixed in AS master https://github.com/Prospress/action-scheduler. I'd prefer to have a second confirmation before doing another AS bugfix release.

**Comment by mikejolley** [comment]
@rrennick Should we create a PR for core then we can pass it on to an affected user?

**Comment by sonite** [comment]
Fatal error: Uncaught ActionScheduler_InvalidActionException: Action [2607] has invalid arguments. It cannot be JSON decoded to an array. in /customers/9/5/8/everydaystyle.se/httpd.www/webshop/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_InvalidActionException.php:26 Stack trace: #0 /customers/9/5/8/everydaystyle.se/httpd.www/webshop/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php(799): ActionScheduler_InvalidActionException::from_decoding_args(2607) #1 /customers/9/5/8/everydaystyle.se/httpd.www/webshop/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php(135): ActionScheduler_wpPostStore->validate_args(NULL, 2607) #2 /customers/9/5/8/everydaystyle.se/httpd.www/webshop/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php(118): ActionScheduler_wpPostStore->make_action_from_post(Object(WP_Post)) #3 /customers/9/5/ in /customers/9/5/8/everydaystyle.se/httpd.www/webshop/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_InvalidActionException.php on line 26 

ROW 2607 in Post says`:
0 | 2019-04-22 23:20:12 | 2019-04-22 21:20:12 | {"rows":[{"post_id":"171","meta_value":"a:3:{i:3;s... | wc_update_product_lookup_tables_rating_count |   | pending | open | closed |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Now deleted and the site works again.

**Comment by rrennick** [comment]
> Should we create a PR for core then we can pass it on to an affected user?

Yes, I'm looking at #23414 to see if we can get all the AS fixes in the one release.

**Comment by rrennick** [comment]
PR #23489
