### ISSUE TITLE
Update to 3.6.1 crashing site

### ISSUE THREAD

**Issue by cmacreative** [woocommerce/woocommerce#23375]
Hi There,

When I clicked to update WooCommerce it's killing my site and displaying the following message in wp-admin. When will this issue be fixed?

Fatal error: Uncaught ActionScheduler_InvalidActionException: Action [5943] has invalid arguments. It cannot be JSON decoded to an array. in /home/website/public_html/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_InvalidActionException.php:26 Stack trace: #0 /home/website/public_html/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php(799): ActionScheduler_InvalidActionException::from_decoding_args(5943) #1 /home/website/public_html/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php(135): ActionScheduler_wpPostStore->validate_args(NULL, 5943) #2 /home/website/public_html/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_wpPostStore.php(118): ActionScheduler_wpPostStore->make_action_from_post(Object(WP_Post)) #3 /home/website/public_html/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/functi in /home/website/public_html/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_InvalidActionException.php on line 26

**Comment by mikejolley** [comment]
This is being looked into in https://github.com/woocommerce/woocommerce/issues/23373

As a workaround, delete post ID 5943 from your database using a tool such as PHPMYAdmin. cc @timmyc

**Comment by sabbirk15** [comment]
This error is crushing all of my sites. Is there a patch for this? The deleting post did not work for me, it is showing more ids. So I will be continuously deleting post ids from db, so it can not a good fix for me.

**Comment by mikejolley** [comment]
@sabbirk15 https://github.com/woocommerce/woocommerce/issues/23373
