### ISSUE TITLE
get_catalog_ordering_args possible warning trigger

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#23387]
**Describe the bug**
`get_catalog_ordering_args` can be called (incorrectly) with an array as `$orderby`/`$order` parameter, then `strtolower` or `strtoupper` emits a warning that it does not accept an array. 
I could not find such an instance of code in WC core, but maybe I missed something. 

If filter `woocommerce_default_catalog_orderby` returns an array of arrays, esc_attr casts it to string, so that is 'fine'.

Related, `WC_Shortcode_Products::parse_query_args` can receive orderby as array (e.g. `http://local.wordpress.test/shortcode-test/?orderby[]=price&orderby[]=date`), then `expode` emits a warning as it does not expect an array. 

**Expected behavior**
No warnings.

via https://wordpress.org/support/topic/warning-strtolower-expects-parameter-1-to-be-string-4/

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23451
