### ISSUE TITLE
Turning off marketplace suggestions does not remove scheduled action

### ISSUE THREAD

**Issue by uok** [woocommerce/woocommerce#23386]
**Describe the bug**
Turning off the marketplace suggestions (see https://github.com/woocommerce/woocommerce/pull/23218) does not remove `woocommerce_update_marketplace_suggestions` from scheduled actions (or change it to non-repeating)

**Expected behavior**
Scheduled action is removed if suggestions are turned off.
Scheduled action is added if turned on.

**WordPress Environment**
WP 5.1.1 with Woo 3.6.1

**Comment by peterfabian** [comment]
Please see #23396.
