### ISSUE TITLE
BULK edit sets all products to Out of Stock using WC 3.6.1

### ISSUE THREAD

**Issue by woocommercecodes** [woocommerce/woocommerce#23388]
I did a fresh install of WP and WC (latest versions) today. When running a bulk edit to change product prices, all products are set to Out of Stock. Using PHP 7.3. Got the same error with a fresh install of WC 3.6.

![wc_oos_bug](https://user-images.githubusercontent.com/38051739/56415848-480a7100-628f-11e9-9403-6016c7d2c27f.png)

**Comment by peterfabian** [comment]
Hi, 

I wasn't able to reproduce using the following steps:
1. Spin up a new site using WP 5.1.1, PHP 7.3.2, nginx
2. Install WC 3.6.1 & Storefront with default dummy products
3. Enable stock managements on some products, leave some in stock, some out stock, some on backorder
4. Select all products, perform a bulk edit, setting price to $45.
5. I saw no change in stock status in admin or on the front end. 

before:
![Screenshot 2019-04-19 at 17 50 10](https://user-images.githubusercontent.com/2207451/56431950-f16f5800-62cb-11e9-8438-b97199cd7f77.png)

after:
![Screenshot 2019-04-19 at 17 50 40](https://user-images.githubusercontent.com/2207451/56431953-f6340c00-62cb-11e9-9f2a-a847b8b16338.png)


Also, I'm a bit confused as your screenshot shows one In stock product in the very first row, but you say all products have been changed to out of stock?

**Comment by mikejolley** [comment]
Looks to be due to missing lookup table data. Variable products do a sync between children data/parent data and `child_has_stock_status` uses the lookup table for this.

**Comment by mikejolley** [comment]
@peterfabian Replicated like this:

- Truncate all data from lookup table
- Quick edit a variable product price
- It becomes out of stock

Looking for a workaround.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23455 for workaround during inital generation of data.

**Comment by woocommercecodes** [comment]
This issue is still present with 3.6.2. Here's the video:

https://www.loom.com/share/30c18cdfcfef44ed95aac8f75cf730f1

**Comment by kloon** [comment]
I was able to replicate this, seems to be related to setting the stock status for out of stock products on my end https://cld.wthms.co/2AEaFZ

**Comment by peterfabian** [comment]
Seems to me like in `WC_Admin_Post_Types::bulk_edit_save` we set manage_stock to true, but then `wc_update_product_stock` reads product twice and the product is no longer set to manage_stock == yes, thus stock_qty is not updated, which leaves it as NULL and `WC_Product::validate_props` sets it to out of stock. 

My attempt to fix: #23510
Can you please check if it solves the issue?

**Comment by Stomp1234** [comment]
Hi, 
I wonder if anyone can help me. Im not very savvy when it comes to Wordpress and woo commerce I'm working for a small independent company on their website. We sell shoes and have been for a while on Wordpress using woo commerce.
All products have different sizes when one gets sold online or in store we need to amend the stock quantity but ever since last Thursdays update to Woocommerce 3.6.2 every time I even edit a product in all products or in bulk editing it automatically put it to out of stock. All other sizes have stock against them and Ive tried to quick edit and put them in stock but they revert back to out of stock. Can anyone help?
Many Thanks

**Comment by madeincosmos** [comment]
Also reported in 1989921-zen

**Comment by peterfabian** [comment]
Updated #23534 if someone wants to test this.

**Comment by peterfabian** [comment]
For further discussion and testing please follow the linked Pull request.

**Comment by dougaitken** [comment]
2001781-zen
2019433-zen / 12689202-hc
