### ISSUE TITLE
WC_Product->get_downloads() returns null

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce#23394]
as stated here:
=> https://docs.woocommerce.com/wc-apidocs/class-WC_Product.html#_get_downloads

it should return array, why if downloads is empty it returns NULL?
isnt it supposed to return empty array instead?

**Comment by peterfabian** [comment]
Hi, 

I wasn't able to reproduce this. Could you post your system status report or provide further information about your setup? 

To me, it seems `WC_Product` is initialized with empty array by default. When it's retrieved from the db, it checks for relevant post_meta and it either does not modify the default or it constructs an array from meta_values. 
Also, it does not seem possible to store NULL in downloads even if passed explicitly to `WC_Product::set_downloads`.

I've tried running `$prod->get_downloads()` on 
- variable product that is not virtual and not downloadable
- downloadable product that has linked downloads
- downloadable product with no linked downloads
- downloadable product that had linked downloads, but they had been removed

All those return an array, either empty one or a list of linked downloads. Do you perhaps have very old products in the database that could be in some inconsistent state? Any other possible steps to reproduce?

**Comment by erikdemarco** [comment]
I create a simple product using REST API, and without sanitizing the data first. is that causing this problem?

**Comment by erikdemarco** [comment]
@peterfabian  I create a simple product using Woocommerce REST API, and without sanitizing the data first. is that causing this problem? the data is sent via html form.

**Comment by erikdemarco** [comment]
I think i found the problem. its because the form submission. thank you so much. please close this issue.
