### ISSUE TITLE
Improve escaping inside templates

### ISSUE THREAD

**Issue by NenadObradovic** [woocommerce/woocommerce#23390]
Hi guys,

Could you please consider to improve escaping (labels and variables) inside templates? 

Because at this moment if we want to override some template inside theme (if there is no hooks for it), then we also need to fix escaping inside your files in order to meet the standard and requirements of WordPress and ThemeForest market for example. 

- Maybe this helps you, regex to find all labels where escaping is missing
`(?<![esc_attr|esc_html])(__\(|_e\()(.*?[\)])`
and find-replace part 
`esc_html$0 or esc_attr$0 `

- Inside templates/auth/header.php you can improve alt attribute with textdomain
`<h1 id="wc-logo"><img src="<?php echo WC()->plugin_url(); ?>/assets/images/woocommerce_logo.png" alt="WooCommerce" /></h1>`

Thanks for your time

Best regards,
Nenad

**Comment by peterfabian** [comment]
Hi Nenad, 

Do I understand you correctly that you want us to escape output of translated strings in template files, e.g. 
https://github.com/woocommerce/woocommerce/blob/3dc0fcb0c7bbd2e638d92531c949c4a7e668e0cf/templates/order/order-details.php#L44

where `_e( 'Product', 'woocommerce' )` should be wrapped in `esc_html`, or use function `esc_html_e `?

Tagging @tiagonoronha and @mikejolley in case this has some explanation I'm not aware of.

Ad second bullet point--I'm not sure, is WooCommerce translated in other languages to something else?

Thx.

**Comment by NenadObradovic** [comment]
Hi peter,

Yes, I mean to escape translated strings

Best regards,
Nenad

**Comment by claudiosanches** [comment]
For this second one it's not really necessary, since should always display our logo, but if you like to replace that logo, you need to replace the entire template anyway, so you can go and change that `alt` too.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23460

**Comment by NenadObradovic** [comment]
Hi claudiosanches and mikejolley,

Thanks

Best regards,
Nenad
