### ISSUE TITLE
Product item disappears after adding and saving

### ISSUE THREAD

**Issue by calgorix23** [woocommerce/woocommerce#23393]
Not sure anyone else have this issue; when u add an order manually from backend, and go on to add product and meta data, that order disappears when u press “save”. Then when u press “create”, then the order reappears.

i have created a video to show this: https://youtu.be/XkXwuhg4tF4

Regards, Calvin

**Comment by peterfabian** [comment]
Hi, 

I could not reproduce this running only WooCommerce plugin. Can you please provide your [system status report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) and try to perform [plugin/theme conflict resolution](https://docs.woocommerce.com/document/how-to-test-for-conflicts/) (preferably on a staging site).

Thx.

**Comment by mikejolley** [comment]
I was also unable to replicate this. It could be that the ajax save event for the items is returning something erroneous. That could be from a plugin conflict so those steps ^ are essential, as well as looking to see if anything is logged in the WP debug log. https://docs.woocommerce.com/document/how-to-test-for-conflicts/ is the best bet here.

Marking invalid for now as all seems to be working on a clean install with those instructions. Feel free to reply or reopen a more detail issue if you find out more.

Thanks
