### ISSUE TITLE
Can't search by SKU in admin

### ISSUE THREAD

**Issue by leonwagner** [woocommerce/woocommerce#23398]
Search products by SKU in admin doesn't work in 3.6.1. (We've seen this before. Looks like it's back.)

**Comment by peterfabian** [comment]
Hi @leonwagner 

Can you please check if the database update has finished for you? How many Pending tasks do you have under WooCommerce > Status > Scheduled Actions? If you have any upgrade tasks pending there, you can run them by clicking on the Run link that appears on mouse over in the list of Pending actions.

If the database upgrade didn't work, you can try to `Regenerate` Product lookup tables via WooCommerce > Status > Tools.

In 3.6, we've extracted SKU to extra lookup table to improve performance for searching, so if the lookup table is not populated correctly, you might experience problems searching for SKUs.

**Comment by mikejolley** [comment]
Added to the FAQ https://github.com/woocommerce/woocommerce/wiki/3.6.x-notes-FAQ#i-am-having-issues-sortingsearching-by-sku-after-the-update
