### ISSUE TITLE
&ndash; not translated for selected item in Customer dropdown

### ISSUE THREAD

**Issue by FPCSJames** [woocommerce/woocommerce#23404]
**Describe the bug**
When viewing a single order, or on the Orders screen, the currently-selected customer - in the filter on Orders or the Customer select on an order - shows `&ndash;` instead of an endash. When searching for a customer, it displays correctly.

**To Reproduce**
1. View an order.
2. Observe the Customer dropdown in the General column of the order details.

**Screenshots**
![ndash-screenshot](https://user-images.githubusercontent.com/16146373/56439556-1b188700-62ac-11e9-9f90-b9bb59c928f9.png)

**Expected behavior**
An endash should appear, not the HTML entity spelled out.

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

### WordPress Environment ###

WordPress address (URL): https://snip.snip
Site address (URL): https://snip.snip
WC Version: 3.6.1
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.2.17
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.0.38-MariaDB-cll-lve
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.7
WC Database Prefix: fmhgigd_
MaxMind GeoIP Database: ✔
Total Database Size: 5.30MB
Database Data Size: 3.37MB
Database Index Size: 1.93MB
fmhgigd_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
fmhgigd_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
fmhgigd_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
fmhgigd_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
fmhgigd_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
fmhgigd_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB
fmhgigd_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
fmhgigd_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
fmhgigd_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
fmhgigd_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
fmhgigd_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
fmhgigd_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
fmhgigd_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
fmhgigd_woocommerce_log: Data: 0.02MB + Index: 0.02MB
fmhgigd_ac_abandoned_cart_history_lite: Data: 0.06MB + Index: 0.00MB
fmhgigd_ac_email_templates_lite: Data: 0.02MB + Index: 0.00MB
fmhgigd_ac_guest_abandoned_cart_history_lite: Data: 0.02MB + Index: 0.00MB
fmhgigd_ac_sent_history_lite: Data: 0.02MB + Index: 0.00MB
fmhgigd_commentmeta: Data: 0.06MB + Index: 0.03MB
fmhgigd_comments: Data: 0.05MB + Index: 0.09MB
fmhgigd_ewwwio_images: Data: 0.11MB + Index: 0.08MB
fmhgigd_ewwwio_queue: Data: 0.02MB + Index: 0.02MB
fmhgigd_irecommendthis_votes: Data: 0.02MB + Index: 0.00MB
fmhgigd_itsec_distributed_storage: Data: 0.02MB + Index: 0.02MB
fmhgigd_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB
fmhgigd_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB
fmhgigd_itsec_lockouts: Data: 0.02MB + Index: 0.08MB
fmhgigd_itsec_log: Data: 0.02MB + Index: 0.03MB
fmhgigd_itsec_logs: Data: 0.02MB + Index: 0.09MB
fmhgigd_itsec_temp: Data: 0.02MB + Index: 0.06MB
fmhgigd_links: Data: 0.02MB + Index: 0.02MB
fmhgigd_options: Data: 1.48MB + Index: 0.05MB
fmhgigd_postmeta: Data: 0.31MB + Index: 0.27MB
fmhgigd_posts: Data: 0.08MB + Index: 0.06MB
fmhgigd_termmeta: Data: 0.02MB + Index: 0.03MB
fmhgigd_terms: Data: 0.02MB + Index: 0.03MB
fmhgigd_term_relationships: Data: 0.02MB + Index: 0.02MB
fmhgigd_term_taxonomy: Data: 0.02MB + Index: 0.03MB
fmhgigd_usermeta: Data: 0.02MB + Index: 0.03MB
fmhgigd_users: Data: 0.02MB + Index: 0.05MB
fmhgigd_wc_download_log: Data: 0.02MB + Index: 0.03MB
fmhgigd_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
fmhgigd_wc_webhooks: Data: 0.02MB + Index: 0.02MB
fmhgigd_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
fmhgigd_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
fmhgigd_wsal_metadata: Data: 0.23MB + Index: 0.14MB
fmhgigd_wsal_occurrences: Data: 0.02MB + Index: 0.02MB
fmhgigd_wsal_options: Data: 0.13MB + Index: 0.00MB
fmhgigd_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
fmhgigd_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 53
nav_menu_item: 6
page: 5
post: 4
product: 20
product_variation: 5
revision: 8
scheduled-action: 2
shop_order: 29
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.6.1

### Inactive Plugins (20) ###

Abandoned Cart Lite for WooCommerce: by Tyche Softwares – 5.3.4
Authy Two Factor Authentication: by Authy Inc – 3.0.2
Bootstrap 3 Shortcodes: by Michael W. Delaney, Filip Stefansson, and Simon Yeldon – 3.3.12
BS3 Grid Builder: by Mahdi Yazdani – 1.0.5
Disable Gutenberg: by Jeff Starr – 1.7
EWWW Image Optimizer: by Exactly WWW – 4.7.3
FPCS Notify Open Graph: by James M. Joyce, Flashpoint Computer Services, LLC – 1.0
Imsanity: by Exactly WWW – 2.4.2
I Recommend This: by Harish Chouhan, Themeist – 3.8.3
iThemes Security: by iThemes – 7.3.3
ManageWP - Worker: by GoDaddy – 4.7.7
Query Monitor: by John Blackbourn – 3.3.4
W3 Total Cache (Fixed): by W3TC (Fixed) Community – 0.9.4.6.4
WooCommerce Multi-Step Checkout: by SilkyPress – 1.18 – Not tested with the active version of WooCommerce
WooCommerce Product Bundles: by SomewhereWarm – 5.7.11 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.1.16
WordPress Importer: by wordpressdotorg – 0.6.4
WP Anti-Detritus: by James M. Joyce, Flashpoint Computer Services, LLC – 1.0
WP Security Audit Log: by WP White Security – 3.4.0.1
Yoast SEO: by Team Yoast – 11.0 – Not tested with the active version of WooCommerce

### Must Use Plugins (2) ###

Kill MWP Auto Login: by Flashpoint Computer Services, LLC –
WP Password bcrypt: by Roots – 1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.4.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2019-04-19 13:55:52 -0500
Newest: 2019-04-19 13:55:52 -0500

Pending: 1
Oldest: 2019-04-26 13:55:52 -0500
Newest: 2019-04-26 13:55:52 -0500

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –
</details>

**Comment by peterfabian** [comment]
Thanks for reporting, I believe this will be fixed by https://github.com/woocommerce/woocommerce/pull/23334

Can you please verify?

**Comment by FPCSJames** [comment]
Yes, that should do it. I haven't had a chance to test it, but I don't see any reason to believe it won't.
