### ISSUE TITLE
Update PayPal to support 3D Secure 2.0 checkout flows (SCA)

### ISSUE THREAD

**Issue by allendav** [woocommerce/woocommerce#23400]
At a minimum, we need to validate that PayPal checkout (bundled in this plugin) works properly when EEA buyers present cards which require 3D Secure 2.0 as part of getting ready for PSD2 / SCA (which takes effect on September 14, 2019.)

It is possible this plugin will require no remediation to be ready for SCA.

See also https://www.braintreepayments.com/blog/getting-up-to-speed-on-psd2-regulation-2/

**Comment by mikejolley** [comment]
@allendav the core implementation is hosted on the PayPal site entirely. This page confirms PayPal will take care of it https://www.paypal.com/uk/webapps/mpp/psd2

Direct gateways (not core) are the ones which will need an update.

**Comment by allendav** [comment]
@mikejolley - you're right. Closing this issue.
