### ISSUE TITLE
Category REST API endpoint retrieves wrong data for menu_order, image and display

### ISSUE THREAD

**Issue by strelkovk** [woocommerce/woocommerce#23407]
**Describe the bug**
on endpoint /wp-json/wc/v3/products/categories/ category wrong data response
```
  "display": [""],
   "image": {
            "id": 1,
            "date_created": "2019-03-21T19:45:45",
            "date_created_gmt": "2019-03-21T19:45:45",
            "date_modified": "2019-03-21T19:45:45",
            "date_modified_gmt": "2019-03-21T19:45:45",
            "src": false,
            "name": "Hello world!",
            "alt": false
 },
  "menu_order": 0,
```

**To Reproduce**
1. Open to '/wp-json/wc/v3/products/categories/.'
2. Check if data is correct '....'

**Expected behavior**

**WordPress Environment**
wordpres 5.1, woocommerce 3.6.1

**Comment by strelkovk** [comment]
`		// Get category display type.
		$display_type = get_term_meta( $item->term_id, 'display_type', **true**);

		// Get category order.
		$menu_order = get_term_meta( $item->term_id, 'order', **true**);

		$data = array(
			'id'          => (int) $item->term_id,
			'name'        => $item->name,
			'slug'        => $item->slug,
			'parent'      => (int) $item->parent,
			'description' => $item->description,
			'display'     => $display_type ? $display_type : 'default',
			'image'       => null,
			'menu_order'  => (int) $menu_order,
			'count'       => (int) $item->count,
		);

		// Get category image.
		$image_id = get_term_meta( $item->term_id, 'thumbnail_id',**true**);`

**Comment by daveai** [comment]
what is the status of this bug and pull request. I am having same problem with image src as false.

**Comment by peterfabian** [comment]
Someone from the team needs to confirm it's a bug and review the Pull Request. After PR is fixed (if needed) and approved, it will be merged to master and assigned to a milestone for release.

**Comment by strelkovk** [comment]
Guys could you help me with covering those changes with unittests?

**Comment by claudiosanches** [comment]
See #23408

**Comment by claudiosanches** [comment]
PR fixing all entries of `get_term_meta()`: https://github.com/woocommerce/woocommerce/pull/23457
