### ISSUE TITLE
Sorting by rating doesn't work after updating to 3.6.1

### ISSUE THREAD

**Issue by dmitriy-denisov** [woocommerce/woocommerce#23403]
**Describe the bug**

Sorting products by rating does not work after updating WooCommerce to version 3.6.1. It should be noted that the sorting of products by rating starts to work correctly again, but only for products that were rated after updating the plugin. I ran the test several times, but the result was always the same.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): http://localhost/test
Site address (URL): http://localhost/test
WC Version: 3.6.1
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: ru_RU
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6
PHP Version: 7.2.6
PHP Post Max Size: 800 MB
PHP Time Limit: 900
PHP Max Input Vars: 10000
cURL Version: 7.59.0
OpenSSL/1.1.0h

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.33-MariaDB
Max Upload Size: 800 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.1
WC Database Prefix: wp_
Общий размер базы данных: 50.05MB
Размер данных в базе данных: 36.18MB
Размер индекса базы данных: 13.87MB
wp_woocommerce_sessions: Данные: 0.02 Мб + Индекс: 0.02 Мб
wp_woocommerce_api_keys: Данные: 0.02 Мб + Индекс: 0.03 Мб
wp_woocommerce_attribute_taxonomies: Данные: 0.02 Мб + Индекс: 0.02 Мб
wp_woocommerce_downloadable_product_permissions: Данные: 0.02 Мб + Индекс: 0.05 Мб
wp_woocommerce_order_items: Данные: 0.02 Мб + Индекс: 0.02 Мб
wp_woocommerce_order_itemmeta: Данные: 0.02 Мб + Индекс: 0.03 Мб
wp_woocommerce_tax_rates: Данные: 0.02 Мб + Индекс: 0.06 Мб
wp_woocommerce_tax_rate_locations: Данные: 0.02 Мб + Индекс: 0.03 Мб
wp_woocommerce_shipping_zones: Данные: 0.02 Мб + Индекс: 0.00 Мб
wp_woocommerce_shipping_zone_locations: Данные: 0.02 Мб + Индекс: 0.03 Мб
wp_woocommerce_shipping_zone_methods: Данные: 0.02 Мб + Индекс: 0.00 Мб
wp_woocommerce_payment_tokens: Данные: 0.02 Мб + Индекс: 0.02 Мб
wp_woocommerce_payment_tokenmeta: Данные: 0.02 Мб + Индекс: 0.03 Мб
wp_woocommerce_log: Данные: 0.02 Мб + Индекс: 0.02 Мб
wp_commentmeta: Данные: 0.02 Мб + Индекс: 0.03 Мб
wp_comments: Данные: 0.06 Мб + Индекс: 0.09 Мб
wp_duplicator_packages: Данные: 0.02 Мб + Индекс: 0.02 Мб
wp_links: Данные: 0.02 Мб + Индекс: 0.02 Мб
wp_options: Данные: 1.33 Мб + Индекс: 0.06 Мб
wp_pmxi_files: Данные: 0.02 Мб + Индекс: 0.00 Мб
wp_pmxi_history: Данные: 0.02 Мб + Индекс: 0.00 Мб
wp_pmxi_images: Данные: 0.42 Мб + Индекс: 0.00 Мб
wp_pmxi_imports: Данные: 0.11 Мб + Индекс: 0.00 Мб
wp_pmxi_posts: Данные: 0.23 Мб + Индекс: 0.16 Мб
wp_pmxi_templates: Данные: 0.08 Мб + Индекс: 0.00 Мб
wp_postmeta: Данные: 26.56 Мб + Индекс: 9.03 Мб
wp_posts: Данные: 2.52 Мб + Индекс: 0.88 Мб
wp_termmeta: Данные: 1.52 Мб + Индекс: 0.09 Мб
wp_terms: Данные: 0.06 Мб + Индекс: 0.03 Мб
wp_term_relationships: Данные: 2.52 Мб + Индекс: 2.52 Мб
wp_term_taxonomy: Данные: 0.06 Мб + Индекс: 0.03 Мб
wp_usermeta: Данные: 0.02 Мб + Индекс: 0.03 Мб
wp_users: Данные: 0.02 Мб + Индекс: 0.05 Мб
wp_wc_download_log: Данные: 0.02 Мб + Индекс: 0.03 Мб
wp_wc_product_meta_lookup: Данные: 0.25 Мб + Индекс: 0.42 Мб
wp_wc_webhooks: Данные: 0.02 Мб + Индекс: 0.02 Мб

### Post Type Counts ###

attachment: 2896
nav_menu_item: 47
page: 11
post: 2
product: 1930
product_variation: 9
revision: 20
scheduled-action: 30

### Security ###

Secure connection (HTTPS): ❌
					В вашем магазине не используется HTTPS. Подробнее о HTTPS и SSL-сертификатах .
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: от Automattic – 3.6.1

### Inactive Plugins (7) ###

Breadcrumb NavXT: от John Havlik – 6.2.1
Classic Editor: от WordPress Contributors – 1.4
Duplicator: от Snap Creek – 1.3.10
Google XML Sitemaps: от Arne Brachhold – 4.1.0
W3 Total Cache: от Frederick Townes – 0.9.7.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: RUB (₽)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Ссылка магазина: #6 - /
Корзина: #7 - /cart/
Оформление заказа: #8 - /checkout/
Мой аккаунт: #9 - /my-account/
Правила и условия: ❌ Страница не задана

### Theme ###

Name: Storefront
Version: 2.4.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – Если вы хотите оформить WooCommerce родительской темой
которую создал кто-то другой
мы рекомендуем воспользоваться дочерней темой. См. "Как создать дочернюю тему"

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 29
Oldest: 2019-04-19 09:55:58 +0000
Newest: 2019-04-19 09:58:55 +0000

Pending: 1
Oldest: 2019-04-26 09:55:58 +0000
Newest: 2019-04-26 09:55:58 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by peterfabian** [comment]
Hi, 

this is most likely caused by the new lookup table (which speeds up working with meta data) not being generated correctly. 

Please check WooCommerce > Status > Action Scheduler for Pending jobs. All jobs can be executed manually if they are not picked up by CRON automatically (Run link appears on each line after mouse over). 

If you see any of the jobs in Failed category, please post the error here (unless it's been already reported).

If the Action Scheduler jobs finished but you still see this problem, please try to regenerate the loopkup table. Look for “Product lookup tables” in “WooCommerce” > “Status” > “Tools” and click in “Regenerate”, this should fix it.

**Comment by dmitriy-denisov** [comment]
Hi.

No errors were found. Unfortunately, the regeneration also did not bring any result - the sorting of products by rating still does not work correctly.

**Comment by peterfabian** [comment]
Do you have any pending jobs in WooCommerce > Status > Action Scheduler?
Can you please check if your db table `wp_wc_product_meta_lookup` contains information about all your products?
Have you checked PHP logs if there are any messages in those?

**Comment by dmitriy-denisov** [comment]
1. There is only one pending job: woocommerce_update_marketplace_suggestions
2. Yes, the table wp_wc_product_meta_lookup contains product information, but some columns have Null values. It should be noted that in the rating_count column there are numerical values, while in the average_rating column there are only Null values are present. After adding a new review to the product, the Null value is replaced with the correct numeric value. At the same time, after the data is regenerated, all values in the average_rating column are again reset to Null but the values of the average product rating in the wp_post_meta table remain correct. Thus, it can be assumed that the function of recalculating the average rating of products, which is triggered when data regeneration starts, does not work correctly.
3. I restarted data regeneration, but I did not find any messages in the PHP logs.

**Comment by shadimanna** [comment]
I also have a product sorting issue with SKU, i.e. it is not working with version 3.6, my guess is these issues are related.

**Comment by peterfabian** [comment]
Please see PR #23465.

@shadimanna : I think your problem is unrelated to this; please try to search for similar issues to find how to verify the lookup table was generated correctly for you.

**Comment by shadimanna** [comment]
@peterfabian the table seems to have been generated correctly in the DB - https://www.dropbox.com/s/tavksc8kdoa9kw9/Screenshot%202019-04-24%2011.47.05.png?dl=0.

The order simply is incorrect when sorting on the product page - https://www.dropbox.com/s/48vy38s300429ln/Screenshot%202019-04-24%2011.48.06.png?dl=0.

Could this be related to #23466 or should I open a new issue?

**Comment by peterfabian** [comment]
@shadimanna Sorry, still can't reproduce this on a clean WC install. Please open a new issue and fill in the template with steps to reproduce on a clean install if possible.
