### ISSUE TITLE
woocommerce_restock_refunded_items config was removed

### ISSUE THREAD

**Issue by itecedor** [woocommerce/woocommerce#23419]
**Is your feature request related to a problem? Please describe.**
Half of the changes in this merged PR appear to be gone from the repo: https://github.com/woocommerce/woocommerce/pull/21314

Specifically, the new config that it added, `woocommerce_restock_refunded_items`, is not in the current version of `class-wc-settings-products.php`, rendering the code in `html-order-items.php` useless. I went through the history of `class-wc-settings-products.php` and couldn't find the commit, so it looks like maybe it was force pushed out?

**Describe the solution you'd like**
The change that @claudiulodro made to `class-wc-settings-products.php` should be put back so this feature works.

**Describe alternatives you've considered**
None

**Additional context**
Original issue: https://github.com/woocommerce/woocommerce/issues/20822
Merged PR: https://github.com/woocommerce/woocommerce/pull/21314

**Comment by kloon** [comment]
Stock is automatically restored when you refund a product when you use the qty option when refunding an item. Your order notes should reflect that stock was increased when doing a refund like this https://cld.wthms.co/Mcv476

If do not wish to restock the item when refunding then do not use the qty option when refunding and simply use the amount field to issue a monetary refund.

**Comment by itecedor** [comment]
@kloon what was removed was the *config* to choose whether the checkbox in your screenshot should be pre-checked or not. If you look at the code in the merged PR I linked to, you'll see the newly-added config `woocommerce_restock_refunded_items`, and if you look at master, you'll see that this config is being used by that checkbox but there is no way to SET the value of the config because the relevant code that was added to `class-wc-settings-products.php` by PR 2314 is no longer in the settings file.
