### ISSUE TITLE
3.61 Database update doesnt complete after 5 + hours

### ISSUE THREAD

**Issue by yatgirl** [woocommerce/woocommerce#23414]
After updating to 3.61 the woocommerce database says it needs to update.  5 hours later, it is still not completed. 
This was reported in https://wordpress.org/support/topic/woocommerce-database-update-woocommerce-is-updating-the-database-in-the-backgr/page/2/

**Comment by uok** [comment]
For upgrade procedures to work, WP CRON must work, otherwise the scheduled tasks never get triggered.
You can execute the pending tasks from WooCommerce > Status > Scheduled Actions, click on Pending and there is a 'Run' link on each line (it appears on mouse over)

**Comment by mbinkhorst** [comment]
Seems to take a long time indeed, and I get a new "woocommerce_update_marketplace_suggestions" created every 5 seconds. Currently I have over 730 pending "woocommerce_update_marketplace_suggestions" actions..

**Comment by peterfabian** [comment]
`woocommerce_update_marketplace_suggestions` is created on admin load if there is no job in queue with this tag. Seems like some problem with finding next job? @rrennick do you think it might be  something to look into in AS?

As for the fix, we have a PR to clean up those jobs if you deactivate the marketplace suggestions that would hopefully fix part of the problem (when suggestions are not active): https://github.com/woocommerce/woocommerce/pull/23396

**Comment by rrennick** [comment]
@peterfabian have you been able to reproduce this? I don't have this in my install. My first guess at what might be causing this in some installs is that the same scheduled action is being used for both the single retry and recurring actions:

https://github.com/woocommerce/woocommerce/blob/master/includes/admin/marketplace-suggestions/class-wc-marketplace-updater.php#L32
https://github.com/woocommerce/woocommerce/blob/master/includes/admin/marketplace-suggestions/class-wc-marketplace-updater.php#L82

**Comment by peterfabian** [comment]
I wasn't able to reproduce consistently, but noticed I had 2 pending jobs on my machine when working on #23396 (that's why I added while loop to the cleanup).

**Comment by rrennick** [comment]
I'll see if I can reproduce this later today.

**Comment by rrennick** [comment]
To reproduce:

- Start with a WC 3.5.7 install
- Disable the SA queue runner by installing https://github.com/Prospress/action-scheduler-disable-default-runner
- Update WC to 3.6.1
- Go to WC -> Status -> Tools -> Scheduled Actions -> Pending
- Check that the `woocommerce_update_marketplace_suggestions` scheduled action is pending
- Click the `Run` Action link on the scheduled action
- Check most recent completed actions to see that `woocommerce_update_marketplace_suggestions` completed
- Rinse & repeat the last 2 steps

I

**Comment by rrennick** [comment]
See https://github.com/Prospress/action-scheduler/pull/294

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23489

**Comment by alexeiol** [comment]
> For upgrade procedures to work, WP CRON must work, otherwise the scheduled tasks never get triggered.
> You can execute the pending tasks from WooCommerce > Status > Scheduled Actions, click on Pending and there is a 'Run' link on each line (it appears on mouse over)

This link for manual updates has disappeared. If I try to update using the link ../wp-admin/admin.php?page=wc-settings&do_update_woocommerce=1, I get an "expired link" error message. I am running WooCommerce 3.9.1 on Wordpress 5.3.2.

**Comment by peterfabian** [comment]
There should be a "Run" link when you move your mouse over each line in the list of Pending actions:
![Screenshot 2020-01-30 at 10 08 36](https://user-images.githubusercontent.com/2207451/73435300-a6996b00-4348-11ea-926c-559066410fc7.png)

If you want to run the database update manually, there is also a button in WooCommerce > Status > Tools:
![Screenshot 2020-01-30 at 10 11 24](https://user-images.githubusercontent.com/2207451/73435454-f6783200-4348-11ea-91e2-614e19f7559f.png)

**Comment by alexeiol** [comment]
@peterfabian Thank you for your answer. The issue is: I know there "should" be a link when I mouse over the lines, but there is not, just check the attachment. The link for manual and individual update "used to be" there; I know because have faced this problem before. Now it has simply disappeared!

Also, when I click on the button in the "Woocommerce-Status-Tools" page, it does not complete the pending tasks. I've been trying to complete this update for 11 days now!

![wc-db-upd](https://user-images.githubusercontent.com/13624357/73448067-da6f9300-433e-11ea-871c-541ef27888cb.jpg)

**Comment by peterfabian** [comment]
Apologies for that, @alexeiol!

Seems like there is a strange glitch where in some languages, the Run link does not appear, as it was discovered in https://github.com/woocommerce/woocommerce/issues/25533. Switching your admin to English temporarily should allow you to run the pending tasks. 

cc @rrennick another case with different admin language not showing the Run link.

**Comment by alexeiol** [comment]
@peterfabian It worked! Thanks a lot!

**Comment by rrennick** [comment]
> Seems like there is a strange glitch where in some languages, the Run link does not appear

#25404 should address this. I should be updating that PR next week and will look at testing with a translation.
