### ISSUE TITLE
Sale tag gets hidden behind product image on Twenty Seventeen theme

### ISSUE THREAD

**Issue by arunsathiya** [woocommerce/woocommerce#23427]
#### Steps to reproduce 

- Install WooCommerce on a WordPress site
- List a product with a sale price
- Visit the product

#### What is expected 

The `Sale` tag is visible.

#### What happens instead 

The `Sale` tag gets hidden behind the product image. The tag can be briefly seen before the image appears.

<img width="632" alt="Screenshot 2019-04-22 at 18 23 18" src="https://user-images.githubusercontent.com/18581859/56501308-e74b9480-652b-11e9-96b9-b3d2efeb08cd.png">
<img width="700" alt="Screenshot 2019-04-22 at 18 23 25" src="https://user-images.githubusercontent.com/18581859/56501310-e7e42b00-652b-11e9-940a-69e04607b424.png">

#### Notes

I am not entirely sure if this should be a theme-specific bug report, or something handled by WooCommerce. The reason behind submitting this bug report on WooCommerce repository is because this sale tag feature is not used on the theme otherwise. 

Happy to move to Twenty Seventeen repository on core Trac as required.

**Comment by kloon** [comment]
See #23450
