### ISSUE TITLE
Problemas con la actualización 3.6.1

### ISSUE THREAD

**Issue by Franjavartnav** [woocommerce/woocommerce#23424]
Desde que se ha instalado la versión 3.6.1 las páginas de woocommerce me aparecen desconfiguradas y se ha perdido el formato.

**Comment by rodrigoprimo** [comment]
There is not enough information in the description to understand what is the problem. I'm assuming it is the same as the one that was reported in #23374, so I'm closing this issue. If that is not the case, please provide more information following the [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=) and I will reopen this issue.
