### ISSUE TITLE
After upgrading to 3.6.0 new products has the whole store as Related products 

### ISSUE THREAD

**Issue by immunity20** [woocommerce/woocommerce#23423]
Upgrade to 3.6.0 Woocommerce with 5.1 Wordpress

Create a new product. ( description, price, weight, stock, category, brand, photo)

redirect to new product's front-end page.

Related products is filled with the whole store's product (~ 5600 products) page takes ages to load.

function for filling the Related products

`function show_cross_sell_in_single_product(){

    $crosssells = get_post_meta( get_the_ID(), '_crosssell_ids',true);
	if (sizeof($crosssells) ==0 ){
		return;
	}
    $args = array( 
        'post_type' => 'product', 
        'posts_per_page' => -1, 
        'post__in' => $crosssells 
        );
    $products = new WP_Query( $args );
    if( $products->have_posts() ) {
        echo '<div class="cross-sells"><h2>Αξεσουάρ που ίσως χρειάζεστε</h2>';
        woocommerce_product_loop_start();
        while ( $products->have_posts() ) { $products->the_post();
            wc_get_template_part( 'content', 'product' );
        }
        woocommerce_product_loop_end();
        echo '</div>';
	} else {
		echo 'omg';
	}
    wp_reset_query();
}`

**Comment by rrennick** [comment]
Can you look in your database with PHPMyAdmin or another tool and see what's being saved in the `_crosssell_ids` meta row?

**Comment by immunity20** [comment]
There is no meta row for that _crosssell_ids
Products inserted before upgrade to 3.6.0 (with no related products)
    echo gettype($crosssells); // is Array (empty)
    echo "a".$crosssells."a"; // aArraya
    print_r($crosssells); // empty array
    sizeof($crosssells); // 0

Products inserted after upgrading to 3.6.0
    echo gettype($crosssells); // is string
    echo "a".$crosssells."a"; // aa
    print_r($crosssells); // 
    sizeof($crosssells); // 1

**Comment by rrennick** [comment]
That looks like it's probably a result of #22773. You could update your logic to use `empty()` instead of `sizeof()`.

**Comment by immunity20** [comment]
That worked
