### ISSUE TITLE
wc_change_pre_get_terms() interferes with meta_query

### ISSUE THREAD

**Issue by jesinwp** [woocommerce/woocommerce#23436]
I'm not sure if this is a bug in WordPress or Woocommerce.

I use the ACF plugin to add a custom field to the product categories and query them using the following code:

```php
$term_ids = new WP_Term_Query( array( 'taxonomy' => 'product_cat', 'meta_key' => 'Brand', 'meta_value' => $brand_id, 'fields' => 'ids' ) );
```

This was working fine till I updated Woocommerce to 3.6. The newly added function `wc_change_pre_get_terms` which hooks into `pre_get_terms` is adding a new `meta_key` named "order".

This is the SQL query that is generated for my `WP_Term_Query` code:

```sql
SELECT DISTINCT t.term_id, tt.parent, tt.count, tt.taxonomy FROM wp_terms AS t  LEFT JOIN wp_termmeta ON ( t.term_id = wp_termmeta.term_id AND wp_termmeta.meta_key='order')  INNER JOIN wp_termmeta AS mt1 ON ( t.term_id = mt1.term_id ) INNER JOIN wp_term_taxonomy AS tt ON t.term_id = tt.term_id WHERE tt.taxonomy IN ('product_cat') AND ( 
  wp_termmeta.meta_key = 'order' OR wp_termmeta.meta_key IS NULL 
  AND 
  ( 
    ( mt1.meta_key = 'Brand' AND mt1.meta_value = '10494' )
  )
) ORDER BY wp_termmeta.meta_value+0 ASC, t.name ASC 
```

Notice the second line of the query

```sql
  wp_termmeta.meta_key = 'order' OR wp_termmeta.meta_key IS NULL 
```

This line should be within brackets `()` or all rows matching `wp_termmeta.meta_key IS NULL` are returned.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23449

**Comment by strarsis** [comment]
Just ran into the same or at least very similar/related issue!
