### ISSUE TITLE
How to change status to published after updating product?

### ISSUE THREAD

**Issue by juno249** [woocommerce/woocommerce#23438]
Hello,

I used Woocommerce API to update product such as short description. But after updating, product status was changed to 'furture'. Please help me. What can i do to change status to publish immediately?

**Comment by WillBrubaker** [comment]
If you believe that this is a WooCommerce bug and you have searched the other issues for similar reports, please list the exact steps to reproduce under the following conditions:

1. An unmodified default WordPress theme such as Twenty Nineteen, or feel free to switch to [Storefront](https://wordpress.org/themes/storefront/)
2. All plugins except for WooCommerce deactivated.

If you do not feel it is a bug and would like assistance troubleshooting, please do post in the WooCommerce support forums here: https://wordpress.org/support/plugin/woocommerce/

**Comment by kloon** [comment]
@juno249 could you please include a copy of the payload you are sending through so we can debug this.

**Comment by claudiosanches** [comment]
@juno249 you need to send a future date, like:

```json
{
	"date_created": "2019-04-30T12:00:00"
}
```

Will set the status to future already for you.

**Comment by claudiosanches** [comment]
Also if you use a past date will publish for you, as well.
