### ISSUE TITLE
Woocommerce Extension Update Multisite Bug

### ISSUE THREAD

**Issue by dkappelman** [woocommerce/woocommerce#23432]
I believe I have stumbled upon a reproducible multi-site extension update bug.  Basically, I have a site where I have WooCommerce and paid extensions activated on only one sub-site.  They are not network activated.  These plugins show as needed updates in the WooCommerce extensions tab under WooCommerce.com Subscriptions.    When you click the update button from that tab, it takes you to a page where it says "The plugin is at the latest version".

To reproduce:

1. Install the latest version of wordpress multisite (5.1.1).
2. Create a second blog.
3. Activate the latest WooCommerce version (3.6.1) on the second blog only.
4. Put an out of date paid WooCommerce extension in your plugins directory.
5. Activate the plugin on the second blog only.
6. Go to the WooCommerce Extensions > WooCommerce.com Subscriptions page.
7. Activate  the plugin.
8. You will see that an update is required.
9. Hit the update button.  You will be taken to a page where it says "The plugin is at the latest version"

Thanks for any help or advice! :)

**Comment by rrennick** [comment]
> Activate the latest WooCommerce version (3.6.1) on the second blog only.

Consider how changes made in WooCommerce would address this when WooCommerce is not active on the main site where the plugin update functionality runs.

If you use extensions from the WooCommerce store then in a multisite install WC needs to be active on the main site for the extension updater to work.

**Comment by dkappelman** [comment]
I'm not really familiar with all the ins and outs of the wordpress update process, so I just kind of thought this was a bug, or something that could be fixed, since it appears like something is broken as is.

So, with the WC Helper, is that deprecated?  Or is it still in active development?  It would be nice to be able to not do have a full WooCommerce install on the main blog and still be able to update plugins.

It would also seem to make some sense that when you click to manually update a plugin within the WooCommerce extension it could potentially override what wordpress thinks is up to date.  Anyway, if none of this is feasible, that's fine, but at least I know what's going on now. 👍

**Comment by rrennick** [comment]
> So, with the WC Helper, is that deprecated?

Sorry, yes it's out of date. You can activate WC on the main site long enough to update the extensions then deactivate it again.

I'm going to close this issue as it's a limitation of how updates work in WordPress multisite.
