### ISSUE TITLE
woocommerce product sku and price can't be sorting, always sorting by date

### ISSUE THREAD

**Issue by ryanfeng801** [woocommerce/woocommerce#23441]
**Describe the bug**
When I using the WordPress dashboard, in product, I click the sku or price, but the showing products were sorting by date. And if I choose in stock in filter by stock level, it doesn't showing right, but the number of items is right. 

**To Reproduce**
1. Go to 'product'
2. Click on 'SKU' or 'Price'
3. See error

**Screenshots**
![1](https://user-images.githubusercontent.com/37634935/56544872-bd05d100-6543-11e9-9176-3781e315e63b.png)
![2](https://user-images.githubusercontent.com/37634935/56544878-c0995800-6543-11e9-9bd2-56ef26089adf.png)
![3](https://user-images.githubusercontent.com/37634935/56544880-c2631b80-6543-11e9-967b-04e3aa7ece72.png)
![4](https://user-images.githubusercontent.com/37634935/56544887-c3944880-6543-11e9-9518-b632a91a5d70.png)

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://g4cgunstore.com
Site address (URL): https://g4cgunstore.com
WC Version: 3.6.1
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.33 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.59.0
OpenSSL/1.0.2q

SUHOSIN Installed: –
MySQL Version: 5.6.40-84.0-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.1
WC Database Prefix: 581_
MaxMind GeoIP Database: ✔
Total Database Size: 89.42MB
Database Data Size: 62.79MB
Database Index Size: 26.63MB
581_woocommerce_sessions: Data: 26.07MB + Index: 0.83MB
581_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
581_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
581_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
581_woocommerce_order_items: Data: 0.04MB + Index: 0.03MB
581_woocommerce_order_itemmeta: Data: 0.26MB + Index: 0.19MB
581_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
581_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
581_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
581_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
581_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
581_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
581_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
581_woocommerce_log: Data: 0.00MB + Index: 0.00MB
581_commentmeta: Data: 0.00MB + Index: 0.01MB
581_comments: Data: 0.13MB + Index: 0.07MB
581_cwcfp_conditional_fields: Data: 0.02MB + Index: 0.00MB
581_iowd_images: Data: 0.00MB + Index: 0.00MB
581_links: Data: 0.00MB + Index: 0.00MB
581_nextend2_image_storage: Data: 0.02MB + Index: 0.01MB
581_nextend2_section_storage: Data: 0.14MB + Index: 0.01MB
581_nextend2_smartslider3_generators: Data: 0.00MB + Index: 0.00MB
581_nextend2_smartslider3_sliders: Data: 0.11MB + Index: 0.00MB
581_nextend2_smartslider3_sliders_xref: Data: 0.00MB + Index: 0.00MB
581_nextend2_smartslider3_slides: Data: 0.69MB + Index: 0.00MB
581_options: Data: 4.53MB + Index: 0.65MB
581_postmeta: Data: 7.69MB + Index: 3.50MB
581_posts: Data: 3.24MB + Index: 0.54MB
581_revslider_css: Data: 0.00MB + Index: 0.00MB
581_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
581_revslider_sliders: Data: 0.02MB + Index: 0.00MB
581_revslider_slides: Data: 0.22MB + Index: 0.00MB
581_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
581_statistics_exclusions: Data: 0.00MB + Index: 0.00MB
581_statistics_historical: Data: 0.00MB + Index: 0.00MB
581_statistics_pages: Data: 4.70MB + Index: 7.77MB
581_statistics_search: Data: 1.71MB + Index: 1.06MB
581_statistics_useronline: Data: 0.20MB + Index: 0.00MB
581_statistics_visit: Data: 0.01MB + Index: 0.01MB
581_statistics_visitor: Data: 11.29MB + Index: 9.44MB
581_termmeta: Data: 0.04MB + Index: 0.04MB
581_terms: Data: 0.32MB + Index: 0.60MB
581_term_relationships: Data: 0.35MB + Index: 0.74MB
581_term_taxonomy: Data: 0.27MB + Index: 0.46MB
581_usermeta: Data: 0.47MB + Index: 0.27MB
581_users: Data: 0.02MB + Index: 0.03MB
581_wc_download_log: Data: 0.00MB + Index: 0.00MB
581_wc_product_meta_lookup: Data: 0.14MB + Index: 0.28MB
581_wc_webhooks: Data: 0.00MB + Index: 0.00MB
581_wdslayer: Data: 0.00MB + Index: 0.00MB
581_wdsslide: Data: 0.00MB + Index: 0.00MB
581_wdsslider: Data: 0.00MB + Index: 0.00MB
581_yith_wcwl: Data: 0.00MB + Index: 0.00MB
581_yith_wcwl_lists: Data: 0.00MB + Index: 0.02MB
581_yoast_seo_links: Data: 0.04MB + Index: 0.01MB
581_yoast_seo_meta: Data: 0.05MB + Index: 0.05MB

### Post Type Counts ###

amn_mi-lite: 1
amn_om: 1
attachment: 1698
cms_block: 37
custom_css: 2
customize_changeset: 1
jetpack_migration: 2
mc4wp-form: 1
ml-slider: 1
nav_menu_item: 183
page: 24
portfolio: 9
post: 6
product: 1103
product_variation: 18
revision: 541
scheduled-action: 36
shop_coupon: 1
shop_order: 261
shop_order_refund: 11
stores: 1
ultimate_slider: 1
wds-slider: 1
woodmart_sidebar: 1
wpcf7_contact_form: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

Redux Framework: by Team Redux – 3.6.15
Canada Post WooCommerce Shipping with Print Label: by Xadapter – 2.0.17 – Not tested with the active version of WooCommerce
CMB2: by CMB2 team – 2.6.0
Conditional Woo Checkout Field Pro: by Scott DeLuzio – 4.1.2
Contact Form 7: by Takayuki Miyoshi – 5.1.1
Google Language Translator: by Rob Myrick – 5.0.48
Jetpack by WordPress.com: by Automattic – 7.2.1
WPBakery Page Builder: by Michael M - WPBakery.com – 5.7
Mailchimp for WordPress: by ibericode – 4.5.1
Smart Slider 3 Pro: by Nextend – 3.3.18
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.16.12.24

User Role Editor: by Vladimir Garagulya – 4.50.2
Canpar Rate Calculator: by Canpar Courier – 1.0.7
WooCommerce Moneris Gateway: by SkyVerge – 2.10.2 – Not tested with the active version of WooCommerce
WooCommerce POS Pro: by kilbot – 0.4.18 – Not tested with the active version of WooCommerce
WooCommerce POS: by kilbot – 0.4.23
WooCommerce Services: by Automattic – 1.19.0 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.6.1
Woodmart Core: by  – 1.0.16
Yoast SEO Premium: by Team Yoast – 11.0
WP Statistics: by VeronaLabs – 12.6.3
Yoast SEO: WooCommerce: by Team Yoast – 11.0 – Not tested with the active version of WooCommerce
YITH WooCommerce Compare: by YITH – 2.3.9
YITH WooCommerce Wishlist: by YITH – 2.2.9

### Inactive Plugins (12) ###

Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.5.1
Image Optimizer WD: by 10Web – 1.0.23
MOJO Marketplace: by Mike Hansen – 1.3.4
OptinMonster API: by OptinMonster Team – 1.6.4
Premmerce SEO for WooCommerce: by premmerce – 2.1 – Not tested with the active version of WooCommerce
Slider Revolution: by ThemePunch – 5.4.8.3
WooCommerce Blocks: by Automattic – 2.0.1
Woocommerce Products Slider: by pickplugins – 1.12.21 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.1.16
WP Content Copy Protection & No Right Click: by wp-buy – 1.6.2
YITH WooCommerce Watermark: by YITHEMES – 1.1.1 – Not tested with the active version of WooCommerce
Yoast SEO: by Team Yoast – 11.0 – Not tested with the active version of WooCommerce

### Must Use Plugins (4) ###

Endurance Browser Cache: by Mike Hansen – 0.4
Endurance Page Cache: by Mike Hansen – 1.5
Endurance PHP Edge: by Mike Hansen – 0.2
SSO: by Garth Mortensen
Mike Hansen – 0.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #11 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Woodmart Child
Version: 1.0.0
Author URL: http://xtemos.com
Child Theme: ✔
Parent Theme Name: Woodmart
Parent Theme Version: 3.6.1
Parent Theme Author URL: http://themeforest.net/user/xtemos
WooCommerce Support: ✔

### Templates ###

Overrides: woodmart/woocommerce/archive-product.php
woodmart/woocommerce/cart/cart-item-data.php
woodmart/woocommerce/cart/cart.php
woodmart/woocommerce/cart/cross-sells.php
woodmart/woocommerce/cart/mini-cart.php
woodmart/woocommerce/checkout/form-checkout.php
woodmart/woocommerce/content-product.php
woodmart/woocommerce/content-product_cat.php
woodmart/woocommerce/content-single-product.php
woodmart/woocommerce/content-widget-product.php
woodmart/woocommerce/global/breadcrumb.php
woodmart/woocommerce/global/form-login.php
woodmart/woocommerce/global/quantity-input.php
woodmart/woocommerce/loop/add-to-cart.php
woodmart/woocommerce/loop/loop-end.php
woodmart/woocommerce/loop/loop-start.php
woodmart/woocommerce/loop/no-products-found.php
woodmart/woocommerce/loop/orderby.php
woodmart/woocommerce/loop/pagination.php
woodmart/woocommerce/loop/sale-flash.php
woodmart/woocommerce/myaccount/form-login.php
woodmart/woocommerce/product-searchform.php
woodmart/woocommerce/single-product/add-to-cart/grouped.php
woodmart/woocommerce/single-product/add-to-cart/variable.php
woodmart/woocommerce/single-product/meta.php
woodmart/woocommerce/single-product/product-image.php
woodmart/woocommerce/single-product/product-thumbnails.php
woodmart/woocommerce/single-product/rating.php
woodmart/woocommerce/single-product/related.php
woodmart/woocommerce/single-product/sale-flash.php
woodmart/woocommerce/single-product/tabs/tabs.php
woodmart/woocommerce/single-product/title.php
woodmart/woocommerce/single-product/up-sells.php
woodmart/woocommerce/single-product.php

### Moneris ###

Environment: Production
Tokenization Enabled: –
Debug Mode: Off
Hosted Tokenization Enabled: –
Integration Country: ca
AVS Enabled: 
AVS Actions: Neither Match: accept
					Zip Match: accept
					Street Match: accept
					Not Verified: accept

CSC Enabled: 
CSC Required: –
CSC Actions: No Match - reject
					Not Verified - reject

### Action Scheduler ###

Complete: 35
Oldest: 2019-04-17 10:24:13 -0400
Newest: 2019-04-22 20:38:21 -0400

Pending: 1
Oldest: 2019-04-24 10:24:13 -0400
Newest: 2019-04-24 10:24:13 -0400

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by kloon** [comment]
I am unable to replicate this. Please check that your lookup table is populated as the search is performed on those tables. If you have a large product list then this population can take some time to complete.

You can regenerate your lookup table by going to WooCommerce -> Status -> Tools and then clicking Regenrate next to Product Lookup Tables.

Please try the above and if you still get the same results please feel free to reopen the issue so we can look into this further.

**Comment by ryanfeng801** [comment]
I updated the database, and regenerate many times, it still not work. I checked my lookup table, all the data is right. Only sorting by name and date are working, sorting by product data(like sku price stock level) still not working. But if I filter by stock level (in stock), the number of shows is right, but the items still sorting by date. 
![1](https://user-images.githubusercontent.com/37634935/56616553-b468d580-65eb-11e9-9c25-7800abc655b7.png)
![2](https://user-images.githubusercontent.com/37634935/56616560-b6329900-65eb-11e9-8c1a-597354d20e36.png)
![3](https://user-images.githubusercontent.com/37634935/56616562-b763c600-65eb-11e9-829b-95cdc6f3a2a1.png)
Thanks for helping me. Wait for your response.

**Comment by claudiosanches** [comment]
I just tried to reproduce with no success, seems like all is sorting properly, have you sure that the new lookup table have entries for all products? This can take a few minutes to be generated.

**Comment by nvomedia** [comment]
Same problem here. It is always sorted on date added. I want to sort on stock 'sold out' and get products with stock at top since they are added last.
Did an regenerate of the product lookup tables and also an manual database upgrade, but with no luck.
I also noticed that that the buttons 'low stock' and 'sold out' are disappeared from the WordPress dashboard.

**Comment by ryanfeng801** [comment]
When I press Regenerate,  it finished like within a few seconds. Then I export products to a csv file and download to have a check, the date in the table is right.

**Comment by nvomedia** [comment]
This fix/patch is solving my problem. I have implemented this by myself waiting on the official update. https://github.com/woocommerce/woocommerce/pull/23590
