### ISSUE TITLE
Invalid characters in WXR export file

### ISSUE THREAD

**Issue by i30** [woocommerce/woocommerce#23447]
**Describe the bug**
Unknown characters are inserted in WXR export file:
![Screenshot from 2019-04-23 16-37-33](https://user-images.githubusercontent.com/16183687/56570976-2a6a3e00-65e6-11e9-9e23-03063235c2da.png)

These characters prevent XML parser from parsing export file:
<img width="909" alt="Screen Shot 2019-04-21 at 16 46 51" src="https://user-images.githubusercontent.com/16183687/56568914-29cfa880-65e2-11e9-84af-05c8092e41fc.png">

**To Reproduce**
Upgrade to version 3.6.1

<details>

### WordPress Environment ###

WordPress address (URL): http://dev.wp.tld
Site address (URL): http://dev.wp.tld
WC Version: 3.6.1
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.29 (Ubuntu)
PHP Version: 7.2.15-0ubuntu0.18.04.2
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.0g

SUHOSIN Installed: –
MySQL Version: 5.7.25-0ubuntu0.18.04.2
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 7.28MB
Database Data Size: 5.94MB
Database Index Size: 1.34MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_clever_visitors_info: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.42MB + Index: 0.02MB
wp_postmeta: Data: 2.52MB + Index: 0.39MB
wp_posts: Data: 1.33MB + Index: 0.09MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 242
elementor_library: 14
mc4wp-form: 1
nav_menu_item: 105
page: 45
post: 9
product: 32
product_variation: 5
scheduled-action: 4
shop_order: 3
wp_block: 1
wpcf7_contact_form: 4

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (6) ###

Contact Form 7: by Takayuki Miyoshi – 5.1.1
Elementor: by Elementor.com – 2.5.14
Mailchimp for WordPress: by ibericode – 4.5.1
Meta Box: by MetaBox.io – 4.17.3
WooCommerce: by Automattic – 3.6.1
WP Reset: by WebFactory Ltd – 1.60

### Inactive Plugins (35) ###

Akismet Anti-Spam: by Automattic – 4.1.1
RTL Tester: by <a href="http://blog.yoavfarhi.com">Yoav Farhi</a>
<a href="http://automattic.com">Automattic</a> – 1.1

WooCommerce Blocks: by Automattic – 2.0.1
WordPress Database Reset: by Chris Berthe – 3.0.2
WordPress Importer: by wordpressdotorg – 0.6.4
WPBakery Page Builder: by Michael M - WPBakery.com – 5.6
YITH WooCommerce Social Login: by YITH – 1.3.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page not set
Terms and conditions: ❌ Page visibility should be public

### Theme ###

Name: Storefront
Version: 2.4.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 2
Oldest: 2019-04-23 08:46:58 +0000
Newest: 2019-04-23 08:46:58 +0000

Pending: 2
Oldest: 2019-04-30 08:46:58 +0000
Newest: 2019-04-30 08:46:58 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –
</details>

**Comment by rrennick** [comment]
I was not able to reproduce this in PHP 7.3. My export files in WP 5.1.1 and WC 3.5.7 & 3.6.1 do not have the character causing the problem:

*WC 3.5.7 Export*
```
		<wp:meta_key><![CDATA[_action_manager_schedule]]></wp:meta_key>
		<wp:meta_value><![CDATA[O:32:"ActionScheduler_IntervalSchedule":2:{s:49:"ActionScheduler_IntervalSchedulestart_timestamp";i:1556026008;s:53:"ActionScheduler_IntervalScheduleinterval_in_seconds";i:3600;}]]></wp:meta_value>
```

*WC 3.6.1 Export*
```
		<wp:meta_key><![CDATA[_action_manager_schedule]]></wp:meta_key>
		<wp:meta_value><![CDATA[O:32:"ActionScheduler_IntervalSchedule":2:{s:49:"ActionScheduler_IntervalSchedulestart_timestamp";i:1553271735;s:53:"ActionScheduler_IntervalScheduleinterval_in_seconds";i:604800;}]]></wp:meta_value>
```

The meta value string is created by WP with `utf8_encode()` of the serialized schedule object. There may be particular versions of PHP that adds the characters.

The reason this hasn't been seen in earlier versions of WC is that this only affects recurring scheduled actions.

**Comment by rrennick** [comment]
Custom tables are coming in a future version of AS https://github.com/Prospress/action-scheduler/pull/259 . Whenever that happens scheduled actions won't be exportable/importable through the WP tools. 

We can disable the export of the post store scheduled actions with a filter. Any plugins using scheduled actions should be ensuring that the correct actions are scheduled. There shouldn't often be a need to import/export these. If someone did need to, they could install & activate AS, deactivate WC, then create the scheduled action export.

I'll work on a PR.

**Comment by claudiosanches** [comment]
See #23456
