### ISSUE TITLE
WC 3.6 order webhooks being triggered for non-orders

### ISSUE THREAD

**Issue by james-allan** [woocommerce/woocommerce#23443]
**Describe the bug**

The issue reported on our side: https://github.com/Prospress/woocommerce-subscriptions/issues/3315

Since WC 3.6 order.updated webhooks are being triggered for subscriptions and possibly other registered order types.

In https://github.com/woocommerce/woocommerce/pull/22731, the `WC_Webhook::should_deliver()` was refactored and as far as I can tell [this logic](https://github.com/woocommerce/woocommerce/blob/3.5.8/includes/class-wc-webhook.php#L149) is no longer enforced. 

So for order types which declare that they don't support order-webhooks, like subscriptions does ([here](https://github.com/Prospress/woocommerce-subscriptions/blob/2.5.3/woocommerce-subscriptions.php#L289)), they are now sending order topic webhooks. 

**To Reproduce**
1. Go to **WooCommerce > Settings > Advanced > Webhooks**
2. Create an **order updated** webhook if you don't have one already.
3. Install the Subscriptions plugin if you don't have it.
3. Go to **WooCommerce > Subscriptions** and edit any subscription.
4. Change the status or the next payment date and hit **Update**. 
5. On the latest WC, notice that the webhook is sent. On 3.5.8, the webhook isn't sent.

**Screenshots**

**Expected behavior**

Return to the WC 3.5 behaviour where order webhooks weren't sent for order types which were registered as not requiring order webhooks. 

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/pull/23444
