### ISSUE TITLE
Dutch postcode validation error

### ISSUE THREAD

**Issue by ReneTuin** [woocommerce/woocommerce#23459]
**Describe the bug**
Dutch zipcode not valid

class-wc-form-handler.php has on line 125 following code:
`$value = strtoupper( str_replace( ' ', '', $value ) );`

Which removes any whitespaces

But the Dutch validation for zipcode requires a whitespace
See class-wc-validation.php on line 95:
`case 'NL':
	$valid = (bool) preg_match( '/^[1-9][0-9]{3}\s(?!SA|SD|SS)[A-Z]{2}$/', $postcode );
	break;`

**Comment by mikejolley** [comment]
I think the code is valid. The code above you reference is the normalization part which applies to all postcodes.

See `wc_format_postcode` where it adds the space back. This happens for NL postcodes as follows:

```
case 'NL':
			$postcode = substr_replace( $postcode, ' ', 4, 0 );
			break;
```

If there is a bug we can replicate, please submit it using the bug report template in a new issue. AFAIK postcodes are formatted before validation kicks in -- we have the same format here in the UK.

I also tested against `1000 AP` during checkout which worked.

Thanks!

**Comment by ReneTuin** [comment]
Problem is from version 3.6.0 did you tested it on there?

**Comment by mikejolley** [comment]
Yes, there is not problem :)
