### ISSUE TITLE
Has anyone *ever* seen anything other than "unknown" for the "Tested up to" value on an upgrade?

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce#23458]
I don't want to spend lots of time looking at this - and so apologies for the short report - but, is it normal that I've never, on a large range of sites, development + live, different servers, different environments, etc. in the years since it was introduced seen anything other than "unknown" in the "Tested up to WooCommerce version" column on the plugins page upgrade notice? Is it just me?

![image](https://user-images.githubusercontent.com/1962275/56596683-8336d800-65e0-11e9-9a52-760f051454eb.png)

**Comment by claudiosanches** [comment]
3rd party plugins requires to include our new plugin headers:

```
 * WC requires at least: 3.0.0
 * WC tested up to:      3.6.0
```

You can find more details in: https://woocommerce.wordpress.com/2017/08/28/new-version-check-in-woocommerce-3-2/

**Comment by DavidAnderson684** [comment]
@claudiosanches Very many of them do, and several of them have since that was introduced. I can be stupid, but not that stupid. :-)

**Comment by DavidAnderson684** [comment]
Including all 4 in the screenshot.

**Comment by claudiosanches** [comment]
@DavidAnderson684 in my tests seems to be working fine, but take that currency switcher plugin, you probably need to update first to see if supports, there's no way to fetch this information before you have all plugins updated before you update WooCommerce.
