### ISSUE TITLE
woocommerce endless loading/spinner on the checkout page

### ISSUE THREAD

**Issue by matty11127** [woocommerce/woocommerce#23461]
So when I go to my checkout page at the bottom where you'd enter credit card details, there's an endless loading spinner. Now the weird part is, if you checkout as a guest, it works perfectly fine. But if you're logged into my website as a registered user, you will see the endless spinner. I have no idea what is causing this as I have disabled all the plugins 1 by 1, and it still does this. I have changed themes, I even used a woocomerce theme from them, still did not help. 

If you want to login to my site to see what I mean, the login details are below.

username: testing123
password: esvrZpn1fEqXYh388mw3(L(7

System report
______________________________________________________________________
`
### WordPress Environment ###

WordPress address (URL): https://realmuzicent.com
Site address (URL): https://realmuzicent.com
WC Version: 3.6.1
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.28 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.59.0
OpenSSL/1.0.2q

SUHOSIN Installed: –
MySQL Version: 5.6.40-84.0-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.1
WC Database Prefix: wpeg_
MaxMind GeoIP Database: ✔
Total Database Size: 51.05MB
Database Data Size: 47.72MB
Database Index Size: 3.33MB
wpeg_woocommerce_sessions: Data: 0.35MB + Index: 0.02MB
wpeg_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wpeg_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wpeg_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wpeg_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wpeg_woocommerce_order_itemmeta: Data: 0.04MB + Index: 0.02MB
wpeg_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wpeg_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wpeg_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wpeg_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wpeg_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wpeg_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wpeg_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wpeg_woocommerce_log: Data: 0.00MB + Index: 0.00MB
crypto_files: Data: 0.02MB + Index: 0.33MB
crypto_membership: Data: 0.02MB + Index: 0.09MB
crypto_payments: Data: 0.02MB + Index: 0.31MB
crypto_products: Data: 0.02MB + Index: 0.25MB
wpeg_commentmeta: Data: 0.02MB + Index: 0.02MB
wpeg_comments: Data: 0.09MB + Index: 0.04MB
wpeg_links: Data: 0.00MB + Index: 0.00MB
wpeg_options: Data: 18.16MB + Index: 0.13MB
wpeg_postmeta: Data: 1.81MB + Index: 0.76MB
wpeg_posts: Data: 1.35MB + Index: 0.18MB
wpeg_revslider_css: Data: 0.09MB + Index: 0.00MB
wpeg_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
wpeg_revslider_navigations: Data: 0.00MB + Index: 0.00MB
wpeg_revslider_sliders: Data: 0.04MB + Index: 0.00MB
wpeg_revslider_slides: Data: 0.24MB + Index: 0.00MB
wpeg_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
wpeg_termmeta: Data: 0.00MB + Index: 0.01MB
wpeg_terms: Data: 0.00MB + Index: 0.01MB
wpeg_term_relationships: Data: 0.00MB + Index: 0.01MB
wpeg_term_taxonomy: Data: 0.00MB + Index: 0.01MB
wpeg_ucare_logs: Data: 0.02MB + Index: 0.00MB
wpeg_um_conversations: Data: 0.02MB + Index: 0.02MB
wpeg_um_followers: Data: 0.02MB + Index: 0.02MB
wpeg_um_messages: Data: 0.06MB + Index: 0.02MB
wpeg_um_notifications: Data: 0.14MB + Index: 0.00MB
wpeg_usermeta: Data: 16.97MB + Index: 0.36MB
wpeg_users: Data: 0.03MB + Index: 0.03MB
wpeg_wc_download_log: Data: 0.00MB + Index: 0.00MB
wpeg_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wpeg_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wpeg_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wpeg_wfBlockedCommentLog: Data: 0.02MB + Index: 0.00MB
wpeg_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wpeg_wfBlocks7: Data: 0.02MB + Index: 0.05MB
wpeg_wfConfig: Data: 0.47MB + Index: 0.00MB
wpeg_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wpeg_wfFileChanges: Data: 0.02MB + Index: 0.00MB
wpeg_wfFileMods: Data: 3.52MB + Index: 0.00MB
wpeg_wfHits: Data: 2.02MB + Index: 0.22MB
wpeg_wfHoover: Data: 0.02MB + Index: 0.02MB
wpeg_wfIssues: Data: 0.02MB + Index: 0.06MB
wpeg_wfKnownFileList: Data: 1.52MB + Index: 0.00MB
wpeg_wfLeechers: Data: 0.06MB + Index: 0.00MB
wpeg_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB
wpeg_wfLocs: Data: 0.02MB + Index: 0.00MB
wpeg_wfLogins: Data: 0.05MB + Index: 0.03MB
wpeg_wfNotifications: Data: 0.02MB + Index: 0.00MB
wpeg_wfPendingIssues: Data: 0.02MB + Index: 0.06MB
wpeg_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wpeg_wfScanners: Data: 0.02MB + Index: 0.00MB
wpeg_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wpeg_wfStatus: Data: 0.13MB + Index: 0.09MB
wpeg_wfTrafficRates: Data: 0.02MB + Index: 0.00MB
wpeg_wfu_dbxqueue: Data: 0.02MB + Index: 0.00MB
wpeg_wfu_log: Data: 0.02MB + Index: 0.00MB
wpeg_wfu_userdata: Data: 0.02MB + Index: 0.00MB
wpeg_wfVulnScanners: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

album: 5
artist: 16
attachment: 531
email_template: 1
forum: 10
gallery: 12
jetpack_migration: 2
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
nav_menu_item: 49
page: 50
patner: 6
post: 10
producer: 8
product: 9
product_variation: 4
reply: 70
revision: 292
scheduled-action: 16
service: 6
shop_coupon: 5
shop_order: 50
shop_order_refund: 4
team: 7
testimonial: 3
topic: 32
um_activity: 450
um_directory: 1
um_form: 3
um_notice: 5
vc_grid_item: 2
video: 17
wpcf7_contact_form: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

bbPress: by The bbPress Community – 2.5.14
Recording CPT: by BeauTheme – 1.1.3
Classic Editor: by WordPress Contributors – 1.4
Contact Form 7: by Takayuki Miyoshi – 5.1.1
Files.fm File Upload Form: by Files.fm – 1.3.4
Instagram Feed: by Smash Balloon – 1.12
Jetpack by WordPress.com: by Automattic – 7.2.1
Multiple Themes: by David Gewirtz – 7.1.1
WPBakery Page Builder: by Michael M - WPBakery.com – 5.4.5
WooCommerce Pushover Integration: by Shop Plugins – 1.0.15 – Not tested with the active version of WooCommerce
Slider Revolution: by ThemePunch – 5.4.6.4
SG Optimizer: by SiteGround – 5.1.2
Ultimate Member: by Ultimate Member – 2.0.43
Ultimate Member - bbPress: by Ultimate Member – 2.0.4
Ultimate Member - Followers: by Ultimate Member – 2.1.2
Ultimate Member - Private Messages: by Ultimate Member – 2.1.9
Ultimate Member - Notices: by Ultimate Member – 2.0.4
Ultimate Member - Real-time Notifications: by Ultimate Member – 2.1.0
Ultimate Member - Online Users: by Ultimate Member – 2.0
Ultimate Member - Google reCAPTCHA: by Ultimate Member – 2.0.2
Ultimate Member - Social Activity: by Ultimate Member – 2.1.6
Ultimate Member - Terms & Conditions: by Ultimate Member – 2.0
Ultimate Member - Verified Users: by Ultimate Member – 2.0.2
Ultimate Member - WooCommerce: by Ultimate Member – 2.1.5 – Not tested with the active version of WooCommerce
WC Variations Radio Buttons: by 8manos – 2.0.2 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.1.16
WooCommerce Services: by Automattic – 1.19.0 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.6.1
Wordfence Security: by Wordfence – 7.2.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #27 - /shop/
Cart: #28 - /cart/
Checkout: #29 - /checkout/
My account: #30 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Recording
Version: 1.1.1
Author URL: http://beautheme.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: recording/woocommerce/archive-product.php version 2.0.0 is out of date. The core version is 3.4.0
recording/woocommerce/cart/cart-empty.php version 2.0.0 is out of date. The core version is 3.5.0
recording/woocommerce/cart/cart-totals.php
recording/woocommerce/cart/cart.php version 3.0.3 is out of date. The core version is 3.5.0
recording/woocommerce/content-product.php version 3.0.0 is out of date. The core version is 3.6.0
recording/woocommerce/content-single-product.php version 3.0.0 is out of date. The core version is 3.6.0
recording/woocommerce/loop/loop-start.php version 2.0.0 is out of date. The core version is 3.3.0
recording/woocommerce/loop/price.php
recording/woocommerce/loop/sale-flash.php
recording/woocommerce/single-product/product-image.php version 3.0.2 is out of date. The core version is 3.5.1
recording/woocommerce/single-product/product-thumbnails.php version 3.0.2 is out of date. The core version is 3.5.1
recording/woocommerce/single-product/related.php
recording/woocommerce/single-product-reviews.php version 2.3.2 is out of date. The core version is 3.6.0
recording/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

### Action Scheduler ###

Complete: 15
Oldest: 2019-04-18 23:16:56 +0000
Newest: 2019-04-18 23:17:32 +0000

Pending: 1
Oldest: 2019-04-25 23:16:56 +0000
Newest: 2019-04-25 23:16:56 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by claudiosanches** [comment]
> I have disabled all the plugins 1 by 1, and it still does this. I have changed themes, I even used a woocomerce theme from them, still did not help.

Try it again and show me, will be easy to test using Storefront too.

**Comment by matty11127** [comment]
Just to be clear, you want me to change the theme to the woocomerce?

**Comment by claudiosanches** [comment]
@matty11127 this is a test site, right? I'm asking if you can disable other plugins and theme, to check if it's really an issue on WooCommerce and not something caused by a 3rd party integration.

**Comment by matty11127** [comment]
This isn’t a test site. I’ve been running my business from this site for 2 years, with everything running fine. I already disabled the plugins and changed the theme and it still had the issue. I checked with all the plugins disabled. Plus, I’m not sure why it would do this only when you’re logged in. As a guest it’s fine.

**Comment by claudiosanches** [comment]
@matty11127 probably better try solve other issues then, since I can't not even add products to the cart, when I click in `Buy Album`:

![Screenshot from 2019-04-23 17-45-04](https://user-images.githubusercontent.com/1264099/56614496-8ab1ad80-65ef-11e9-8cfa-5cbc1098ab34.png)

I need steps to be able to reproduce this issue in another environment, so I can confirm if it's an issue on WooCommerce.

**Comment by matty11127** [comment]
Yes, all the adding things to cart plus the checkout page all stated having that issue at the same time. Which was when I recently updated all my plugins, including woo. Adding to cart and checkout are related. So you need me to disable all the plugins except woo? Because if I disable my user interface plugin you won’t be able to login and like I said as a guest it works fine. Let me know. Thanks for the help btw

**Comment by claudiosanches** [comment]
> Which was when I recently updated all my plugins, including woo. 
This still sounds like that is coming from one of your plugins, or even your theme.
I'll close for now, since I'm not able to reproduce this in another environment, if you find how to reproduce it, please feel free to comment here and I can open again, but for now this don't sounds like an issue on WooCommerce, as I said, probably some plugin/theme causing conflict.
