### ISSUE TITLE
WP_Term_Query "orderby" argument doesn't work any more for product categories

### ISSUE THREAD

**Issue by lomars** [woocommerce/woocommerce#23466]
Since WooCommerce 3.6.x `WP_Term_Query` **`orderby`** argument doesn't work any more with Product category taxonomy 

When doing a simple Term query on product categories like:

```
$terms = get_terms( 'product_cat', array(
    'taxonomy' => 'product_cat',
    'orderby'  => 'name', // Default argument value
) );
```

Will give the same result than:

```
$terms = get_terms( 'product_cat', array(
    'taxonomy' => 'product_cat',
    'orderby'  => 'term_id', 
) );
```

or even than:

```
$terms = get_terms( 'product_cat', array(
    'taxonomy' => 'product_cat',
    'orderby'  => 'order', 
) );

```

The `orderby` argument doesn't have any effect on sorting the terms.

Before on WooCommerce version 3.5.8 it was giving a different sorting for each of them.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23477
