### ISSUE TITLE
Rest API: The product category image data is null after upgrade WooCommerce

### ISSUE THREAD

**Issue by themevan** [woocommerce/woocommerce#23463]
I have upgraded WooCommerce to 3.6.1, but I found the product category image array is returned to null in rest api data such like 

image: {id: 1, date_created: null, date_created_gmt: null, date_modified: null,......}

Even I have deactivated the other plugins, and changed the theme. I'm sure the product category images is uploaded when I checking them again in WP backend.

Need help! Thanks

**Screenshots**
https://www.dropbox.com/s/jue80z745hgq8i2/Screenshot%202019-04-24%2000.46.42.png?dl=0

**Comment by claudiosanches** [comment]
That screenshot isn't yet available... It's missing a lot of this report, there's no indication of what REST API version, or anything else to help us how to debug. If you please could provide more information and steps to reproduce this issue, I'll be happy to try.

Still probably already reported and fixed on https://github.com/woocommerce/woocommerce/issues/23407

**Comment by mikejolley** [comment]
https://github.com/woocommerce/woocommerce/issues/23407 is the one - images etc are meta data.

**Comment by themevan** [comment]
Sorry, the screenshot now is available to view.  Simply speaking, just set the featured image for each product category, then, when I want to get the image URL through the /wc/v3/products/categories/ rest api endpoint, all image fields shows null as same as the screenshot: https://www.dropbox.com/s/jue80z745hgq8i2/Screenshot%202019-04-24%2000.46.42.png?dl=0

**Comment by themevan** [comment]
oh, I have upgraded to woocomerce 3.6.2, the problem is fixed.
Please close this issue. Thanks
