### ISSUE TITLE
HTML email template on Child theme stripping all <style> tags

### ISSUE THREAD

**Issue by kv-bluemillion** [woocommerce/woocommerce#23470]
**Describe the bug**
Child Theme Email Templates (ie-Avada-Child-Theme/woocommerce/emails/customer-processing-order.php) are stripping all <style> tags. Began happening immediately after updating to 3.6.1. No other updates done at the same time.

**To Reproduce**
1. Go to 'WooCommerce>Settings>Emails'
2. Click on 'Manage' within Processing Order item 
3. Click on 'View Template'
4. Edit template to include custom styling
5. Order product
6. Email received will not have any styling from the template.

**Expected behavior**
I would expect styling to remain intact.

**Isolating the problem (mark completed items with an [x]):**
- [X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
--
WordPress address (URL): |   | https://completetb.kinsta.com
Site address (URL): |   | https://completetb.kinsta.com
WooCommerce version: |   | 3.6.1
Log directory writable: |   | /www/completetb_454/public/wp-content/uploads/wc-logs/
WordPress version: |   | 5.1.1
WordPress multisite: |   | –
WordPress memory limit: |   | 256 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –

`
### WordPress Environment ###

WordPress address (URL): https://completetb.kinsta.com
Site address (URL): https://completetb.kinsta.com
WC Version: 3.6.1
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.15.9
PHP Version: 7.2.15-1+ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.38-MariaDB-1~xenial
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 46.97MB
Database Data Size: 33.16MB
Database Index Size: 13.81MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.08MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 4.52MB + Index: 0.48MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB
wp_gf_form: Data: 0.02MB + Index: 0.00MB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 6.06MB + Index: 0.11MB
wp_postmeta: Data: 15.42MB + Index: 11.17MB
wp_posts: Data: 5.22MB + Index: 0.36MB
wp_redirection_404: Data: 0.02MB + Index: 0.06MB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB
wp_redirection_logs: Data: 0.02MB + Index: 0.08MB
wp_revslider_css: Data: 0.13MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.02MB + Index: 0.00MB
wp_revslider_slides: Data: 0.02MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.05MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.19MB + Index: 0.09MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.27MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.09MB + Index: 0.16MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_links: Data: 0.14MB + Index: 0.05MB
wp_yoast_seo_meta: Data: 0.05MB + Index: 0.00MB

### Post Type Counts ###

attachment: 343
nav_menu_item: 30
note: 3
page: 34
post: 2
product: 693
product_variation: 109
revision: 275
scheduled-action: 15
shop_order: 33
slide: 2
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Gravity Forms: by rocketgenius – 2.4.8
AddFunc Head & Footer Code: by AddFunc – 2.1
Contact Form 7: by Takayuki Miyoshi – 5.1.1
Fusion Builder: by ThemeFusion – 1.9
Fusion Core: by ThemeFusion – 3.9
Fusion White Label Branding: by ThemeFusion – 1.1.3
Gravity Forms No CAPTCHA reCAPTCHA: by John Parks - Folkhack Studios – 1.0.7
Heartbeat Control by WP Rocket: by WP Rocket – 1.2.5
Media Deduper: by Cornershop Creative – 1.5.2
Redirection: by John Godley – 4.2.3
Slider Revolution: by ThemePunch – 5.4.8.3
Checkout Field Editor for WooCommerce: by ThemeHiGH – 1.3.1 – Not tested with the active version of WooCommerce
WooCommerce Blocks: by Automattic – 2.0.1
WooCommerce Composite Products: by SomewhereWarm – 3.15.2 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.6.1
Yoast SEO: by Team Yoast – 11.0 – Not tested with the active version of WooCommerce
WP Dashboard Notes: by Jeroen Sormani – 1.0.9

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 4.1.1
Extra Product Options (Product Addons) for WooCommerce: by ThemeHiGH – 1.3.3 – Not tested with the active version of WooCommerce
Hide Price Until Login: by CedCommerce – 1.0.10

### Must Use Plugins (1) ###

Kinsta Must-use Plugins: by Kinsta Team – 2.3.1

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #126 - /shop/
Cart: #12 - /cart/
Checkout: #129 - /checkout/
My account: #131 - /account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Avada Child
Version: 1.0.0
Author URL: https://theme-fusion.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 5.9
Parent Theme Author URL: http://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada-Child-Theme/woocommerce/cart/cart.php
Avada-Child-Theme/woocommerce/checkout/form-pay.php
Avada-Child-Theme/woocommerce/checkout/review-order.php
Avada-Child-Theme/woocommerce/checkout/thankyou.php
Avada-Child-Theme/woocommerce/emails/admin-new-order.php
Avada-Child-Theme/woocommerce/emails/customer-completed-order.php
Avada-Child-Theme/woocommerce/emails/customer-processing-order.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

### Composite Products ###

Database Version: 3.15.2
Template Overrides: –

### Action Scheduler ###

Complete: 14
Oldest: 2019-04-17 20:20:10 +0000
Newest: 2019-04-22 17:38:08 +0000

Pending: 1
Oldest: 2019-04-24 20:20:10 +0000
Newest: 2019-04-24 20:20:10 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by claudiosanches** [comment]
Please, can you provide your copy of the changed template or some sample of this implementation?

**Comment by kv-bluemillion** [comment]
Here's the snippet I've added:

// set our flag to be false until we find a product in that category
	$cat_check = false;
	        
	// check each cart item for our category
	foreach ( WC()->cart->get_cart() as $cart_item_key => $cart_item ) {
	            
	    $product = $cart_item['data'];
	    
	    // replace 'membership' with your category's slug
	    if ( has_term( 'stock-parts', 'product_cat', $product->id ) ) {
	        $cat_check = true;
	        // break because we only need one "true" to matter here
	        break;
	    }
	}
	        
	// if a product in the cart is in our category, do something
	if ( $cat_check ) {
	    // we have the category, do what we want
	    // echo "STOCK PARTS INCLUDED";
	} else {
		// we do not have the category, do what we want
	    // echo "NO STOCK PARTS INCLUDED";
	    ?> <style type="text/css">
				table>thead>tr>th:nth-child(3), table>tbody>tr>td:nth-child(3), table>tfoot>tr {display: none;}
			</style> <?php
	}

**Comment by mikejolley** [comment]
Hi there,

Styles are removed and put inline by a library called Emogrifier (https://github.com/MyIntervals/emogrifier). This was updated in 3.6.x. That may be why you're seeing different behaviour.

The latest version of Emogrifier has several fixes and improvements so this is not something we plan on fixing or reverting, so you may have to revise your code.

The code itself you shared has several issues which I'm happy to point out so you can move to a better solution.

1. This code checks the global CART. When emails are sent there is no guarantee the items are still in the cart, or that the cart exists. Emails can go out at any point, even when the cart is empty or another user is logged in.

2. The inline selectors use some advanced CSS. This won't work consistently across mail clients. (I also think it's too complex for Emogrifier to parse which is why it's not working any longer).

**This code should be moved to `templates/emails/email-order-items.php`** and it should check the items being output rather than the CART to hide content. The content could be hidden by not rendering it instead of with CSS which is not reliable.

I hope this helps.

**Comment by kv-bluemillion** [comment]
Mike,

Thanks for taking the time to explain and offer other options. 

The code provided was only in the email for Processing Orders, so I figured checking the CART contents made sense. I'll look into your suggestions and can hopefully come up with a better solution.

Best,
-K

**Comment by mikejolley** [comment]
@kv-bluemillion Processing orders can come at any time, so I think it's important to look at it again. Some gateways clear the cart for example before marking a payment complete. Some gateways set orders on-hold.

**Comment by kv-bluemillion** [comment]
That makes sense. I had success with the COD payment method, but haven't tested yet with other options (in the middle of a build), so sounds like I may have run into issues anyway. I'm very new to woocommerce customizations, so I'm learning a lot as I go. Thanks!
