### ISSUE TITLE
Product Variation do not removed

### ISSUE THREAD

**Issue by RazyRx** [woocommerce/woocommerce#23476]
**Describe the bug**
Variation do not removed on product type changed

**To Reproduce**
1. Create product with product type "Variable product" 
2. Add some attribute for variation
3. Create variations with "Create variations from all attributes"
4. Save product
5. Change product type to "Simple product"
6. Save product
7. Change product type to "Variable product"
8. Create variations with "Create variations from all attributes"
9. Save product
10. Move product to trash
11. Restore product from trash
12. Now product has 2 variation for each attribute value

**Expected behavior**
Expected:
1. Variation must be removed after product type change
2. Variation must be restored when product type changed back to "Variable product"

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
WordPress address (URL): http://localhost/dev
Site address (URL): http://localhost/dev
WC Version: 3.6.1
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –
</details>

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23478
