### ISSUE TITLE
woocommerce_before_cart_form

### ISSUE THREAD

**Issue by Stas0238** [woocommerce/woocommerce#23474]
Hello, you have woocommerce_before_cart_table and woocommerce_after_cart_table hooks (cart/cart.php), can you add in one of next update also hooks before form and after it such as woocommerce_before_cart_form woocommerce_after_cart_form. Because the existing hook gives us posibility just to add some content inside form which is not as normal to add it inside form, much better separate of that form. Thanks

**Comment by mikejolley** [comment]
There is a `woocommerce_before_cart` before the form too...plus `woocommerce_after_cart`. More hooks do not seem needed here.

Thanks
