### ISSUE TITLE
Placeholder filter for order email recipients

### ISSUE THREAD

**Issue by d-skinner** [woocommerce/woocommerce#23472]
I'd like to be able to add a placeholder to include all "user role" emails as recipients of order emails. For example, I have a shop_manager user role, and I'd like for all users with this role to receive a "new order" notification.

I've created a new user role placeholder function (see code below) using the "woocommerce_email_format_string" but now realise that this is not called on the recipient field of the email (only on the subject and heading fields). So my solution at the moment is completely moot unless this gets added to core.

```php
add_filter( 'woocommerce_email_format_string' , 'filter_email_format_string', 20, 2 );
function filter_email_format_string( $string, $email ) {
	global $wp_roles;

	// Get available user roles
  $all_roles = $wp_roles->roles;
  $editable_roles = apply_filters('editable_roles', $all_roles);

	$additional_placeholders = array(); // Set additional placeholders to empty array

	// Loop through available user roles and add placeholder
	foreach ( $editable_roles as $role_name => $role_info ) {
		$role_arg = 'role=' . $role_name;
		$role_users = get_users( $role_arg ); // Get all users that have current role

		// Collect all user emails
		$role_emails = array(); // Set role emails to empty array

		foreach ( $role_users as $user ) {
			array_push( $role_emails, $user->user_email );
		}

		$role_emails = implode(",", $role_emails); // Implode emails into comma seperated list

		// Add role based emails to placeholders
		$role_placeholder = "{role:" . $role_name . "}";
		$additional_placeholders[$role_placeholder] = $role_emails;
	}

  // return the clean string with new replacements
  return str_replace( array_keys( $additional_placeholders ), array_values( $additional_placeholders ), $string );
}
```

I've tried finding a plugin that would let me set emails to go to user roles (rather than to the comma separated textbox value) but there doesn't appear to be any such plugin.

To be honest I'm a little perplexed this is not already part of core as it seems to be rather simple functionality that I would have through many people want.

**Comment by kloon** [comment]
To alter the recipients you can use the woocommerce_email_recipient_* filter, ie for the new order email that filter would be woocommerce_email_recipient_new_order

**Comment by d-skinner** [comment]
@kloon I realise it's possible use the `woocommerce_email_recipient_*` filter to add recipients on a "per email" basis but it makes a lot more sense to me to just add this user role placeholder. Otherwise my plugin would need to have an option for each email rather than just allowing user roles to be added to the existing UI.

**Comment by claudiosanches** [comment]
> Otherwise my plugin would need to have an option for each email rather than just allowing user roles to be added to the existing UI.

You can have just one option, but still apply into several filters.
