### ISSUE TITLE
Invalid Postal/Zip Code error thrown for valid Netherland Postal Code

### ISSUE THREAD

**Issue by MANOJMANI07** [woocommerce/woocommerce#23481]
**Describe the bug**
Validation for the postal code of Netherland is not proper on editing address in my account page.
The message displayed on submitting the address - "Please enter a valid postcode / ZIP".

**To Reproduce**
Type any valid postal code(1019 XH) for Netherland country on editing address in my account page, it will result in the wrong validation and won't accept the zip code.

**Solution**
On removing **\s**  or replacing **\s** with **(\s?)** in the regex that is used to validate postal code for Netherland - "^[1-9][0-9]{3}\s(?!SA|SD|SS)[A-Z]{2}$" will work fine as spaces are removed from the postal code before validation.

**Comment by mikejolley** [comment]
Affects account page only. Not checkout.

**Comment by mikejolley** [comment]
See https://github.com/woocommerce/woocommerce/pull/23483

**Comment by lucaslinssen** [comment]
is it possible that this issue hasn't been solved yet? I'm still experiencing this bug for dutch zipcodes...
