### ISSUE TITLE
Checkout get_value() returning blank 'billing_country'

### ISSUE THREAD

**Issue by f1alan** [woocommerce/woocommerce#23487]
I am using v3.6.1 of Woocommerce although I believe this issue was present in the prior version.

I am populating various billing address fields in a template using the following code:

```
<?php foreach ( $checkout->checkout_fields['billing'] as $key => $field ) {
    if( isset( $field["visible"] ) && $field["visible"] ) {
        woocommerce_form_field( $key, $field, $checkout->get_value( $key ) );
    }                     
} ?>
```

I was finding that $checkout->get_value( $key ) was returning an empty string for 'billing_country' although all other fields were returned properly. The database contains the correct value.

As a workaround, I am now getting these values directly from the user's meta data like this:

`woocommerce_form_field( $key, $field, get_user_meta( $user_id, $key, true ) );`

**Comment by mikejolley** [comment]
Looking at the `get_value` method in checkout class it loads data in this order:

- POST
-  woocommerce_checkout_get_value filter
- logged in customer OR customer session meta
- default_checkout_X filter

Either the field has been posted blank, the customer meta is empty, or the filters are in use. It could be any of those, but this method is highly specific to checkout. Being blank could also be valid if the customer has not provided data yet.

It's more likely you'll want to pull from customer data. Not by using meta directly, but by using the `WC_Customer` class.

If there is a core bug as a result of this please let me know so I can add some tests/reproduce but I think it's working as intended.

Hope that helps.

**Comment by f1alan** [comment]
Thanks for the comments. To be honest, I have taken this site over from someone and have been ironing out various issues before it goes live. I'm not a Woocommerce expert but I was confident enough to log a bug because all other fields (i.e. First Name, Last Name etc) are working using this function and the meta data does indeed exist. I'm happy with my workaround although I'll bear your suggestion in mind. I really just wanted to pass my feedback on to the people responsible for the plugin.
