### ISSUE TITLE
Wrong canton (state) must be set to get the price with tax.

### ISSUE THREAD

**Issue by dankray** [woocommerce/woocommerce#23485]
**Describe the bug**
When setting the real location of the business (Switzerland / Aargau), the price in the shop is shown without tax. To get the price with tax (as desired) a wrong location (Switzerland / Zurich) must be used.

**To Reproduce**
WooCommerce seetings:
TAX
Tax options > Prices entered with tax > Yes …
Calculate tax based on > Customer shipping address

GENERAL
Store Adress
Country / State
Setting 1: Schweiz / Aargau
Setting 2: Schweiz / Zürich

**Expected behavior**
Setting 1: price in shop without tax
Setting 2: price in shop with tax

**Comment by mikejolley** [comment]
@dankray Settings > Default customer location is the option you want. Probably geolocate if you want taxes to show relevant to the user instead of the store base address. If Aargau is missing taxes in settings > taxes it won't show anything.

**Comment by dankray** [comment]
Thanks. I have deleted location specific settings / just entered the country and tax rate - now it's fine.
