### ISSUE TITLE
ERROR: The password you entered for the email address * is incorrect.

### ISSUE THREAD

**Issue by Track77** [woocommerce/woocommerce#23497]
Applicable to versions  3.6.1 and 3.6.2

**To Reproduce**
Steps to reproduce
1. Logout
2. Try login using valid password
3. The message appears "ERROR: The password you entered for the email address * is incorrect."
4. Edit file "class-wc-form-handler.php" => remove the method **wp_unslash**( $_POST['password'] ). Keep only the $_POST['password'].
5. Repeat => now you can login.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://test.3d-kstudio.com
Site address (URL): https://test.3d-kstudio.com
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.28 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.59.0
OpenSSL/1.0.2q

SUHOSIN Installed: –
MySQL Version: 5.6.40-84.0-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 112.30MB
Database Data Size: 80.61MB
Database Index Size: 31.69MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_downloadable_product_permissions: Data: 0.83MB + Index: 0.64MB
wp_woocommerce_order_items: Data: 0.09MB + Index: 0.05MB
wp_woocommerce_order_itemmeta: Data: 0.71MB + Index: 0.56MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
b2s_posts: Data: 0.02MB + Index: 0.11MB
b2s_posts_network_details: Data: 0.02MB + Index: 0.00MB
b2s_posts_sched_details: Data: 0.02MB + Index: 0.00MB
b2s_post_sched_settings: Data: 0.02MB + Index: 0.03MB
b2s_user: Data: 0.02MB + Index: 0.05MB
b2s_user_contact: Data: 0.02MB + Index: 0.02MB
b2s_user_network_settings: Data: 0.02MB + Index: 0.03MB
kstudio_buyer: Data: 0.11MB + Index: 0.02MB
kstudio_buyer_description: Data: 0.02MB + Index: 0.00MB
kstudio_license_id_files: Data: 0.02MB + Index: 0.00MB
kstudio_license_keys: Data: 8.52MB + Index: 0.00MB
kstudio_open_by_now_link: Data: 1.52MB + Index: 0.00MB
kstudio_plugin: Data: 0.02MB + Index: 0.03MB
kstudio_reseller: Data: 0.02MB + Index: 0.00MB
kstudio_tracking_url: Data: 1.52MB + Index: 0.11MB
mantis_project_version_table: Data: 0.17MB + Index: 0.02MB
wp_ac_abandoned_cart_history_lite: Data: 0.02MB + Index: 0.00MB
wp_ac_email_templates_lite: Data: 0.03MB + Index: 0.00MB
wp_ac_guest_abandoned_cart_history_lite: Data: 0.02MB + Index: 0.00MB
wp_ac_sent_history_lite: Data: 0.02MB + Index: 0.00MB
wp_bbpas: Data: 2.52MB + Index: 7.06MB
wp_blc_filters: Data: 0.02MB + Index: 0.00MB
wp_blc_instances: Data: 0.16MB + Index: 0.08MB
wp_blc_links: Data: 0.17MB + Index: 0.14MB
wp_blc_synch: Data: 0.11MB + Index: 0.06MB
wp_commentmeta: Data: 0.05MB + Index: 0.04MB
wp_comments: Data: 0.19MB + Index: 0.09MB
wp_download_cats: Data: 0.02MB + Index: 0.00MB
wp_download_count: Data: 0.02MB + Index: 0.00MB
wp_download_info: Data: 0.02MB + Index: 0.02MB
wp_download_version: Data: 0.08MB + Index: 0.00MB
wp_duplicator_packages: Data: 0.02MB + Index: 0.02MB
wp_ewwwio_images: Data: 0.17MB + Index: 0.17MB
wp_gravatars: Data: 0.02MB + Index: 0.02MB
wp_linkcategorymeta: Data: 0.02MB + Index: 0.05MB
wp_links: Data: 0.01MB + Index: 0.00MB
wp_links_extrainfo: Data: 0.02MB + Index: 0.03MB
wp_lockdowns: Data: 0.06MB + Index: 0.00MB
wp_login_fails: Data: 1.52MB + Index: 0.00MB
wp_mail_bank_email_logs: Data: 0.02MB + Index: 0.00MB
wp_mail_templates: Data: 0.02MB + Index: 0.02MB
wp_microblogposter_accounts: Data: 0.02MB + Index: 0.02MB
wp_microblogposter_items_meta: Data: 0.02MB + Index: 0.00MB
wp_microblogposter_logs: Data: 0.02MB + Index: 0.00MB
wp_microblogposter_old_items: Data: 0.02MB + Index: 0.00MB
wp_microblogposter_user_accounts: Data: 0.02MB + Index: 0.00MB
wp_newsletter: Data: 0.02MB + Index: 0.03MB
wp_newsletter_automated: Data: 0.02MB + Index: 0.00MB
wp_newsletter_emails: Data: 1.52MB + Index: 0.00MB
wp_newsletter_sent: Data: 0.84MB + Index: 1.43MB
wp_newsletter_stats: Data: 3.52MB + Index: 3.03MB
wp_newsletter_user_logs: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 1.93MB + Index: 0.22MB
wp_postmeta: Data: 40.09MB + Index: 3.24MB
wp_posts: Data: 2.15MB + Index: 0.43MB
wp_redirection_404: Data: 0.02MB + Index: 0.06MB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB
wp_redirection_logs: Data: 0.02MB + Index: 0.08MB
wp_relevanssi: Data: 4.42MB + Index: 8.88MB
wp_relevanssi_log: Data: 1.52MB + Index: 1.52MB
wp_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB
wp_social_users: Data: 0.06MB + Index: 0.02MB
wp_super: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.08MB + Index: 0.17MB
wp_term_relationships: Data: 0.12MB + Index: 0.23MB
wp_term_taxonomy: Data: 0.08MB + Index: 0.08MB
wp_usermeta: Data: 3.31MB + Index: 1.66MB
wp_users: Data: 0.26MB + Index: 0.19MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wpbi_bar_charts: Data: 0.02MB + Index: 0.02MB
wp_wpbi_database_connections: Data: 0.02MB + Index: 0.02MB
wp_wpbi_datatables: Data: 0.02MB + Index: 0.02MB
wp_wpbi_phinx_log: Data: 0.02MB + Index: 0.00MB
wp_wpbi_pie_charts: Data: 0.02MB + Index: 0.02MB
wp_wpbi_queries3: Data: 0.02MB + Index: 0.03MB
wp_wysija_campaign: Data: 0.02MB + Index: 0.00MB
wp_wysija_campaign_list: Data: 0.02MB + Index: 0.00MB
wp_wysija_custom_field: Data: 0.02MB + Index: 0.00MB
wp_wysija_email: Data: 0.05MB + Index: 0.00MB
wp_wysija_email_user_stat: Data: 0.02MB + Index: 0.00MB
wp_wysija_email_user_url: Data: 0.02MB + Index: 0.00MB
wp_wysija_form: Data: 0.02MB + Index: 0.00MB
wp_wysija_list: Data: 0.02MB + Index: 0.00MB
wp_wysija_queue: Data: 0.02MB + Index: 0.02MB
wp_wysija_subscriber_ips: Data: 0.02MB + Index: 0.02MB
wp_wysija_url: Data: 0.02MB + Index: 0.00MB
wp_wysija_url_mail: Data: 0.02MB + Index: 0.00MB
wp_wysija_user: Data: 0.22MB + Index: 0.14MB
wp_wysija_user_field: Data: 0.02MB + Index: 0.00MB
wp_wysija_user_history: Data: 0.02MB + Index: 0.00MB
wp_wysija_user_list: Data: 0.11MB + Index: 0.00MB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.05MB
wp_yoast_seo_links: Data: 0.25MB + Index: 0.09MB
wp_yoast_seo_meta: Data: 0.08MB + Index: 0.00MB
wp_ywrr_email_blocklist: Data: 0.02MB + Index: 0.00MB
wp_ywrr_email_schedule: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

amn_exact-metrics: 1
attachment: 1278
blocks: 26
customize_changeset: 3
deprecated_log: 4
faq: 42
flamingo_contact: 45
flamingo_inbound: 2
form-entries: 167
forum: 20
gfw_event: 2
gfw_report: 23
gvn_schart: 6
link_library_links: 88
manual_htm: 69
ml-slider: 5
nav_menu_item: 144
oembed_cache: 87
organized-thing: 1
page: 46
post: 97
postman_sent_mail: 12
product: 58
product_variation: 9
reply: 538
revision: 28
scheduled-action: 17
shop_coupon: 24
shop_order: 1468
shop_order_refund: 9
testimonials-widget: 13
todo: 2
topic: 327
user_request: 3
wcps: 1
wpeo-task: 1
wplp_link: 11
wp_block: 1
wysijap: 1
ywrac_cart: 12

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (78) ###

Custom Admin-Bar Favorites: by Robert Wise – 0.1
Admin Menu Editor: by Janis Elsts – 1.8.8
BackUpWordPress To Google Drive: by Human Made Limited – 2.1.13
BackUpWordPress: by XIBO Ltd – 3.8
Basic User Avatars: by Jared Atchison – 1.0.3
bbP Live Preview: by r-a-y – 0.1
bbPress Toolkit: by Pascal Casier – 1.0.12
bbPress - Live Topic Suggestions: by Hudson Atwell,japh,salbahra – 1.1.0
bbPress Advanced Statistics: by Jake Hall – 1.5
bbPress Notify (No-Spam): by <a href="http://usestrict.net">Vinny Alves (UseStrict Consulting)</a> – 2.1.11
bbPress Permalinks Advanced: by  – 1.1.0
bbpress Simple View Counts: by jezza101 – 0.2
bbPress: by The bbPress Community – 2.5.14
Buddy-bbPress Support Topic: by G3ronim0 – 2.1.4
Classic Editor: by WordPress Contributors – 1.4
Cleverness To-Do List: by C.M. Kendrick – 3.4.2
Crop Thumbnails: by Volkmar Kantor – 1.2.4
Dashboard Post-it: by Mark Dingemanse – 1.1
Disable Emails: by WebAware – 1.4.0
Disable Embeds: by Pascal Birchler – 1.4.0
Display All Image Sizes: by Press Up – 1.1.6
Advanced Download Counter: by Andy Staines – 1.3
Duplicate Post: by Enrico Battocchi – 3.2.2
Envato Market: by Envato – 2.0.1
Flexible FAQ: by S. Bage – 0.2
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 5.3.8
Google Language Translator: by Rob Myrick – 5.0.48
Hierarchical HTML Sitemap: by Alexandra Vovk – 10.2
Image Upload for BBPress: by Potent Plugins – 1.1.15
Lazy Load for Videos: by Kevin Weber – 2.7.1
Log Deprecated Notices: by Andrew Nacin – 0.4.1
My Link Order: by Andrew Charlton – 4.3
Newsletter - Google Analytics: by The Newsletter Team – 1.0.9
Newsletter - Extended Composer Blocks: by The Newsletter Team – 1.0.2
Newsletter - Facebook: by The Newsletter Team – 4.0.4
Newsletter - Reports: by The Newsletter Team – 4.2.2
Newsletter - WP Users Integration: by The Newsletter Team – 1.1.5
Newsletter: by Stefano Lissa & The Newsletter Team – 5.9.3
Nextend Social Login: by Nextendweb – 3.0.20
Password Protected: by Ben Huson – 2.2.4
Plugin Groups: by David Cramer  – 1.2.1
Plugin Notes: by Mohammad Jangda – 1.6
Post Tags and Categories for Pages: by curtismchale – 1.4.1
WooCommerce Product Filter: by Mihajlovic Nenad – 6.6.5 – Not tested with the active version of WooCommerce
Quick Alt Editor: by Arsmoon – 1.0.1
Really Simple CAPTCHA: by Takayuki Miyoshi – 2.0.1
Redirection: by John Godley – 4.2.3
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.0
Relevanssi: by Mikko Saari – 40.0.8
Search Regex: by John Godley – 1.4.16
SG Optimizer: by SiteGround – 5.1.2
Shortcodes to show or hide content: by Dave Clements – 2.5
Title and Nofollow For Links: by WPKube – 1.07
To-Dos: by Johan Ström (Updated: Alex Kramer) – 1.2
Ultimate Tag Cloud Widget: by Rickard Andersson – 2.7.2
User Role Editor: by Vladimir Garagulya – 4.50.2
User Submitted Posts: by Jeff Starr – 20190312
User Switching: by John Blackbourn & contributors – 1.5.0
WCP Contact Form: by Webcodin – 3.1.0
Woo Preview Emails: by Digamber Pradhan – 1.5.0 – Not tested with the active version of WooCommerce
WooCommerce Admin Bar Addition: by David Decker - DECKERWEB – 2.7.0 – Not tested with the active version of WooCommerce
WooCommerce Bulk Discount: by Oleksandr Kramer – 2.5.5 – Not tested with the active version of WooCommerce
WooCommerce Cross-Sale Discount: by Oleksandr Kramer – 0.6 – Not tested with the active version of WooCommerce
WooCommerce Currency Converter Widget: by Alexander Kramer – 0.6.2 – Not tested with the active version of WooCommerce
WooCommerce Custom Product Tabs Lite: by SkyVerge – 2.2.7 – Not tested with the active version of WooCommerce
WooCommerce Prices: by sydcode – 1.0.2 – Not tested with the active version of WooCommerce
Woocommerce Products Per Page: by Jeroen Sormani – 1.2.6 – Not tested with the active version of WooCommerce
WooCommerce Sales by Country: by MH Mithu – 1.5 – Not tested with the active version of WooCommerce
WooCommerce Sales By Location Report: by ChuckMac Development – 1.3.2 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.6.2
WordPress Importer: by wordpressdotorg – 0.6.4
Yoast SEO Premium: by Team Yoast – 25
WP Business Intelligence: by Kenton Hirowatari – 3.1.2
WP Easy Uploader: by Chris Jean – 1.0.14
WP Links Page: by Allyson Rico
Robert Macchi – 4.5

YITH WooCommerce Review Reminder: by YITH – 1.5.0
YITH WooCommerce Subscription: by YITH – 1.3.2
YITH WooCommerce Wishlist: by YITH – 2.2.10

### Inactive Plugins (45) ###

Abandoned Cart Lite for WooCommerce: by Tyche Softwares – 5.3.4
AddQuicktag: by Frank Bültge – 2.5.3
bbPress Admin Bar Addition: by David Decker - DECKERWEB – 1.7.1
bbPress Enable TinyMCE Visual Tab: by Jared Atchison – 1.0.1
Better Search Replace: by Delicious Brains – 1.3.3
Blog2Social: Social Media Auto Post & Scheduler: by Blog2Social
Adenion – 5.3.0

Broken Link Checker: by ManageWP – 1.11.8
Compress JPEG & PNG images: by TinyPNG – 3.2.0
Cookie Notice: by dFactory – 1.2.46
Custom Field Bulk Editor: by SparkWeb Interactive
Inc. – 1.9.1

Disable All WordPress Updates: by Oliver Schlöbe – 1.6.3
Display SQL Stats: by Jürgen Schulze – 0.9.5.1
Duplicate Menu: by Jonathan Christopher – 0.2.1
Duplicator: by Snap Creek – 1.3.10
Enhanced Media Library: by wpUXsolutions – 2.7.2
FV Gravatar Cache: by Foliovision – 0.4.3
GD bbPress Attachments: by Milan Petrovic – 3.1
Google Video Sitemap Feed With Multisite Support: by Art Project Group – 1.8.1.1
Google XML Sitemap for Videos: by Amit Agarwal – 2.6.1
GTmetrix for WordPress: by GTmetrix – 0.4.3
Guaven SQL Charts: by Guaven Labs – 2.1.2
Intuitive Custom Post Order: by hijiri – 3.1.2
Mailgun: by Mailgun – 1.7.1
MailPoet 2: by MailPoet – 2.11
Media Library Categories: by Jeffrey-WP – 1.7
Newsletter - Addons Manager: by The Newsletter Team – 1.0.4
Newsletter - Bounce: by The Newsletter Team – 1.0.5
Newsletter - Feed by Mail: by The Newsletter Team – 4.1.0
Newsletter - Geo: by The Newsletter Team – 1.0.5
Newsletter - Mailgun: by The Newsletter Team – 4.0.7
Newsletter - Mailjet: by The Newsletter Team – 4.0.5
Newsletter - Subscribe on Comments: by The Newsletter Team – 1.0.4
Organized: by organized – 1.0.1
P3 (Plugin Performance Profiler): by GoDaddy.com – 1.5.3.9
pCloud Backup: by Josselyn Jayant – 1.0
Query Monitor: by John Blackbourn – 3.3.4
SendGrid: by SendGrid – 1.11.8
Theme Test Drive: by Vladimir Prelovac – 2.9.1
WooCommerce 2Checkout Payment Gateway Free: by Najeeb Ahmad – 3.0 – Not tested with the active version of WooCommerce
Woo Email Control: by Ian Young – 1.061 – Not tested with the active version of WooCommerce
Woo Framework Shortcodes: by Anand Shah – 1.0.0
WordPress File Monitor Plus: by Scott Cariss – 2.2
WP-Cleanup: by JortK – 1.1.0
WP-PostViews: by Lester 'GaMerZ' Chan – 1.76.1
WP Admin Todo List: by Shyam Makwana – 1.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #65 - /shop/
Cart: #66 - /cart/
Checkout: #67 - /checkout/
My account: #68 - /my-account/
Terms and conditions: #4863 - /support/license-terms/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.8.3
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome-child/woocommerce/cart/mini-cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome-child/woocommerce/content-product.php
flatsome-child/woocommerce/content-product_cat.php
flatsome-child/woocommerce/content-single-product.php
flatsome-child/woocommerce/content-widget-product.php
flatsome-child/woocommerce/emails/customer-new-account.php
flatsome-child/woocommerce/emails/email-footer.php
flatsome-child/woocommerce/emails/email-header.php
flatsome-child/woocommerce/emails/email-styles.php
flatsome-child/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome-child/woocommerce/myaccount/dashboard.php
flatsome-child/woocommerce/myaccount/form-edit-address.php
flatsome-child/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome-child/woocommerce/myaccount/view-order.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome-child/woocommerce/single-product/add-to-cart/external.php
flatsome-child/woocommerce/single-product/add-to-cart/grouped.php
flatsome-child/woocommerce/single-product/add-to-cart/simple.php
flatsome-child/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
flatsome-child/woocommerce/single-product/meta.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome-child/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome-child/woocommerce/single-product/rating.php
flatsome-child/woocommerce/single-product/related.php
flatsome-child/woocommerce/single-product/review-meta.php
flatsome-child/woocommerce/single-product/review-rating.php
flatsome-child/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome-child/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome-child/woocommerce/single-product/title.php
flatsome-child/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

### Action Scheduler ###

Complete: 15
Oldest: 2019-04-17 18:22:53 +0300
Newest: 2019-04-24 18:40:23 +0300

Pending: 1
Oldest: 2019-05-01 18:40:23 +0300
Newest: 2019-05-01 18:40:23 +0300

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 1
Oldest: 2019-04-17 18:25:06 +0300
Newest: 2019-04-17 18:25:06 +0300

`
</details>

**Comment by claudiosanches** [comment]
Thanks for report it.
See https://github.com/woocommerce/woocommerce/pull/23499

**Comment by Track77** [comment]
Still doesn't work in woo 3.6.3
PS. my pass doesn't contains backslashes
