### ISSUE TITLE
Store gone blank after 3.6.2 update

### ISSUE THREAD

**Issue by progzilla** [woocommerce/woocommerce#23496]
Immediately after updating 3.6.1 to 3.6.2, our online store became blank. 

https://www.charitiesway.co.uk

Please help. It's urgent.

Thank you.

**Comment by claudiosanches** [comment]
It's missing all information of this bug report, there's no steps to reproduce, information about your installation or anything else, sorry but we need all those information in order to debug.

If you like to fill it:

```
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.

</details>
```

Also nice to enable WP debug mode and check the error logs.

**Comment by progzilla** [comment]
Yes I could have done that but I can't access either the admin area or homepage to get any of the information required because the website is absolutely blank.

Or kindly advice how I can get any error log out for you.

Thank you.

**Comment by claudiosanches** [comment]
> Or kindly advice how I can get any error log out for you.

Yes, no problem, let's try the WP Debug mode, try adding the code below into your `wp-config.php` before  `/* That's all, stop editing! Happy blogging. */` (by FTP, SSH, or hosting panel).

```php
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
```

After that you should try load the page again, a `wp-content/debug.log` file should be generated, please attach that file here or at least the content, so we can investigate.

**Comment by progzilla** [comment]
Thank you so much. I manage to resolve the issue. It was  a piece of code meant to rename a tag and the new update hated it. So its all good now.

Thank you once again.

**Comment by claudiosanches** [comment]
Happy to be able to help, thanks for let know.
