### ISSUE TITLE
Showing the add-on for the products next to products in the cart.

### ISSUE THREAD

**Issue by umernaeem217** [woocommerce/woocommerce#23498]
I am always working on customizing different wordpress plugins but this is the first time that I am comingon this platform for asking help.
I need to ask that How would we implement the woocommerce cart to show the add-ons for the products next to them in the cart asking for quantity.

![caprue](https://user-images.githubusercontent.com/34766137/56697323-be7ff680-6707-11e9-8d7f-84b41c881eeb.PNG)

**Comment by claudiosanches** [comment]
Hi there. GitHub is primarily for reporting bugs and is not a support forum. We don’t support custom development here. You could ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce
Thanks!
