### ISSUE TITLE
multi product-category product breadcrumbs not following navigation path

### ISSUE THREAD

**Issue by nk1987** [woocommerce/woocommerce#23504]
**Describe the bug**
For some reason in Woocommerce the product level breadcrumbs, on products with multiple product categories, does not follow the path that the user is navigating.

**To Reproduce**
1. Create a fresh install of woocommerce
2. Add 3 product-categories: f.x Cat food, Dog food, Bird food
3. Add 1 product "All-around-food", and make sure it is checked off in all three categories ( Cat food, dog food, bird food )
4. Set the "Primary product category" as "Bird food" and publish
5. Navigate to a new page, and insert a module that shows all three product-categories. Publish it, and "view page"
6. Now click "Cat food" > "All-around-food" and watch the breadcrumbs. It should show: Frontpage>Bird food>All-around-food - even though you navigated through "cat food".
7. That is the error, that the breadcrumbs, does not follow the path the user navigates, when a product is in two or more product-categories.

**Screenshots**

**Expected behavior**
I expect it to show the product-category path that I navigated., so that I can go 1 level up at any time.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by mikejolley** [comment]
Breadcrumbs do not work like this, they do not track how a user navigates. Breadcrumbs show the 'true' path where the product resides. If a product is in multiple categories, it's the main category. There are WordPress plugins to control which is considered the 'main' category.
