### ISSUE TITLE
Incorrect data in Product

### ISSUE THREAD

**Issue by kamiliazainal** [woocommerce/woocommerce#23500]
Hi,

I’m having a problem here. Currently, we’re using a theme for our business. However, the theme didn’t support the payment gateway that we’re using. So, we decided to use this plugin. So, this plugin handle all the orders. Others, such as adding a product is handled by the theme. Now, we would like to add a coupon code for a few product but i noticed that the product stored in Woocommerce is different with the real product stored in theme. Some even have duplicated ID. Some product that exist in theme didn’t exist in woocommerce. This is a big problem. Anyone have faced this kind of problem before ? Please help.

Thanks

**Comment by faisal-alvi** [comment]
Hi @kamiliazainal 

Thank you for reaching out here. Can you please describe more?

1. Which theme is being used?
2. How did you imported products in WooCommerce from your theme?
3. Can you please provide a demo/staging link?
4. Please provide screenshots.

Without much information, people can not help you.

Thank you.

**Comment by kamiliazainal** [comment]
Hi @faisal-alvi 

Thank you for the quick response. 

1. I'm using Traveler theme by Shine Theme
2. I didn't import anything. Just install the woocommerce plugin. If there's any import process occur, that might be done by previous person who help to build the website. But, as far as i concern, there's no import process occur.
3. https://www.halaltrekker.com
4.  
![total_product_in_woocommerce](https://user-images.githubusercontent.com/47439061/56718375-333b4b00-6771-11e9-80bd-77e76360ebb2.PNG)

![total_product_in_theme](https://user-images.githubusercontent.com/47439061/56718390-3c2c1c80-6771-11e9-8fcf-135f6382f2b2.PNG)

**Comment by faisal-alvi** [comment]
Hi @kamiliazainal ,

Thank you for sharing details.

It seems that you are using WooCommerce 3.6.2 and as per Traveler Theme, highest supported WooCommerce version is WooCommerce 3.3.x ([link](https://themeforest.net/item/traveler-traveltourbooking-wordpress-theme/10822683)).

![ThemeForestSupportedWoo](https://user-images.githubusercontent.com/25176325/56724864-6bd72680-6769-11e9-80e1-7f61cf2a5a00.png)

I would suggest first trying, supported version of WooCommerce. You can try v.3.3.1 ([link](https://github.com/woocommerce/woocommerce/tree/3.3.1)).

Thanks & Regards.

**Comment by claudiosanches** [comment]
Hi there! GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal.

Your issue seems to be caused by Traveler Theme.

Please contact the author directly for support.
Thank you!
