### ISSUE TITLE
REST API - Create Customer - Invalid Parameter (s): billing, shipping for iOS Swift

### ISSUE THREAD

**Issue by Dnyanda** [woocommerce/woocommerce#23502]
while creating new customer in iOS app we are using oauth1.0 swift api to create new customer. but oauth api uses dictionary object (OAuthSwift.Parameters = [String: Any]) as parameter
I have created below object 

var postDict =  OAuthSwift.Parameters()
        postDict["first_name"] = (firstNameFld.text!.trimmingCharacters(in: .whitespaces))
        postDict["last_name"] = (lastNameFld.text!.trimmingCharacters(in: .whitespaces))
        postDict["email"] = (emailFld.text!.trimmingCharacters(in: .whitespaces))
        postDict["password"] = (passwordFld.text!.trimmingCharacters(in: .whitespaces))
        postDict["billing"] = ["Phone": "12548798"]

but it gives and error {"code":"rest_invalid_param","message":"Invalid parameter(s): billing","data":{"status":400,"params":{"billing":"billing is not of type object."}}}

**Comment by claudiosanches** [comment]
Hi there. GitHub is primarily for reporting bugs and is not a support forum. We don’t support custom development here. You could ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce

**Comment by claudiosanches** [comment]
> but it gives and error {"code":"rest_invalid_param","message":"Invalid parameter(s): billing","data":{"status":400,"params":{"billing":"billing is not of type object."}}}

Need to check the output, not familiar with Swift, but the output need to be:

```json
"billing" : {
  "phone": "12548798"
}
```
