### ISSUE TITLE
Checkout prevented when no selling location is set

### ISSUE THREAD

**Issue by rynaldos** [woocommerce/woocommerce#23509]
Howdy!

When no country is selected as a selling location, with the following setting found under wp-admin/admin.php?page=wc-settings, this one: 

<img width="658" alt="Screen Shot 2019-04-25 at 14 24 20" src="https://user-images.githubusercontent.com/6198774/56735962-2fa2c680-6767-11e9-8d55-09683c5f6552.png">

.. then the checkout displays the following: 

<img width="527" alt="Screen Shot 2019-04-25 at 14 30 44" src="https://user-images.githubusercontent.com/6198774/56735810-cfac2000-6766-11e9-98d5-38705a2b322b.png">

.. which prevents the customer from checking out

<img width="338" alt="Screen Shot 2019-04-25 at 14 37 38" src="https://user-images.githubusercontent.com/6198774/56736151-b8b9fd80-6767-11e9-9c3f-84110fe96286.png">

Is this intentional or is there a way we can make it a bit more clear that the user needs to add a country in there? It does have a "Select none" option which doesn't make much sense. Perhaps remove that button and add a notice if the user saves that settings page without adding a country? 

**To Reproduce**
1. Go to wp-admin/admin.php?page=wc-settings
2. Set "Sell to specific countries" as the selling location
3. Set no country 
4. Go through the checkout process

I've tested this in WP v5.1.1, WC v3.6.2, and Storefront v2.4.5

Thanks!

**Comment by claudiosanches** [comment]
> Is this intentional or is there a way we can make it a bit more clear that the user needs to add a country in there? It does have a "Select none" option which doesn't make much sense. Perhaps remove that button and add a notice if the user saves that settings page without adding a country?

I think that this is intentional, this allows use WooCommerce just as a catalog and not allow any customer of buying, that "Select none" probably could be updated to "Clean" or something else.

**Comment by peterfabian** [comment]
Please see #23597.
