### ISSUE TITLE
fix: dismiss button is not properly clickable in woocommerce-message box

### ISSUE THREAD

**Issue by kakshak** [woocommerce/woocommerce#23506]
**Describe the bug**
When any woocommerce message box is available then the dismiss text should not be properly clickable in the box. When you hover the text, it should be clickable for that area not in the above portion of the area.

**To Reproduce**
1. Go to 'Products > Import'
2. Click on 'Choose file and import CSV file for the first time'
3. Two woocommerce message boxs are added above or you can check with any woocommerce message box

**Video**
https://www.loom.com/share/a30d838fb196400db23e3bfa30ab411c

**Expected behavior**
A proper click of the button expected to happen while hovering the text.

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
WordPress address (URL): |   | http://smartshareold.test
-- | -- | --
Site address (URL): |   | http://smartshareold.test
WooCommerce version: |   | 3.6.1
Log directory writable: |   | /srv/www/smartshareold/public_html/wp-content/uploads/wc-logs/
WordPress version: |   | 4.9.6 - There is a newer version of WordPress available (5.1.1)
WordPress multisite: |   | –
WordPress memory limit: |   | 256 MB
WordPress debug mode: |   |  
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –
```
</details>

**Comment by rrennick** [comment]
@kakshak For this issue, it would help if you provided your OS and web browser info including versions.

**Comment by kakshak** [comment]
**OS info**
<details>
Ubuntu 18.04.2 LTS
Memory: 7.7 GiB
Processer: Intel® Core™ i5-7400 CPU @ 3.00GHz × 4 
Graphics: Intel® HD Graphics 630 (Kaby Lake GT2)
GNOME: 3.28.2
OS-Type: 64-bit
Disk: 235.2 GB
</details>

**Web browser info**
<details>
Google chrome
Version 73.0.3683.103 (Official Build) (64-bit)
</details>

**Comment by rodrigoprimo** [comment]
I was able to reproduce this problem on Firefox 66 running on Linux. As far as I can see it only happens with two notices: `legacy_shipping` and `no_shipping_methods`. I will create a PR with a fix.

**Comment by rodrigoprimo** [comment]
See #23517. Thanks for your contribution.
