### ISSUE TITLE
Wrong database information when using HyperDB

### ISSUE THREAD

**Issue by rodrigoprimo** [woocommerce/woocommerce#23508]
**Describe the bug**
WC system status page shows incorrect database information if HyperDB is enabled. This happens because WC relies on the constant `DB_NAME` to get information about the database and this constant is not defined when HyperDB is being used.

Those sites will display the following in the database section of the system status page (note the misleading message saying that all WC tables do not exist and the wrong database size):

![Screenshot from 2019-04-25 09-13-07](https://user-images.githubusercontent.com/77215/56735493-fdc83a80-673b-11e9-9d61-ee98010f17ab.png)

The site will also generate the following PHP warning:

```
Use of undefined constant DB_NAME - assumed 'DB_NAME' (this will throw an Error in a future version of PHP)
wp-content/plugins/woocommerce/includes/api/v2/class-wc-rest-system-status-v2-controller.php:708
```

https://github.com/woocommerce/woocommerce/blob/b85f362e4177a0cbb1e025d6815b9cc7f4c38339/includes/api/v2/class-wc-rest-system-status-v2-controller.php#L708

We should probably fix this sooner than later as in a future version of PHP the undefined constant warning will be converted to an error.

I'm not sure if there is a way to get the database name when HyperDB is enabled.

**To Reproduce**
1. Check the database section of the system status page on a WC site that is using HyperDB. WooCommerce.com or its staging environment are two good examples of such sites.

**Expected behavior**
WC should display the correct information about the database of sites using HyperDB or at least fail gracefully with a message saying that it was not possible to get database information for that site.

**Comment by rrennick** [comment]
> I'm not sure if there is a way to get the database name when HyperDB is enabled.

I think you could check for `$wpdb->dbname`. That would also work for https://github.com/rrennick/shardb.

**Comment by rrennick** [comment]
> I think you could check for $wpdb->dbname.

On second thought that isn't going to be super reliable either because the tables can be in different DBs. An alternative might be use `get_class( $wpdb )` and if it's not `wpdb` then output that it's a  custom class and the classname.

**Comment by rodrigoprimo** [comment]
See #24034

**Comment by kloon** [comment]
Just for reference, I did some digging in the HyperDB code and they actually make use of the DBNAME constant as a fallback. I think the issue comes in that DBNAME is user defined in wp-config.php but is optional when using other DB classes. So not specifically HyperDB related.
