### ISSUE TITLE
WooCommerce setup page in click any dropdown option see the Design

### ISSUE THREAD

**Issue by parmarhardip** [woocommerce/woocommerce#23505]
**Describe the bug**
Design issue on wp setup page

**To Reproduce**
1. Fresh Wordpress install
2. WoCoomerce install and active and setup.
3. open to any dropdown on wp-setup page.
4. See error UI

**Video**
[https://www.screencast.com/t/hWoTNI77Y](https://www.screencast.com/t/hWoTNI77Y)

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment]
@parmarhardip is possible to use some another video format that doesn't requires Flash to be installed? Thanks.

**Comment by parmarhardip** [comment]
Sure @claudiosanches!

![screencast-localhost](https://user-images.githubusercontent.com/23077242/56784569-bd85bc80-680e-11e9-8d7b-6c0b139b1834.gif)

**Comment by claudiosanches** [comment]
@parmarhardip thank you for reporting and sending a Pull Request.

**Comment by claudiosanches** [comment]
Closing since #23526 fixes it. Thanks again!
