### ISSUE TITLE
Fatal Error 

### ISSUE THREAD

**Issue by gabriellubowa** [woocommerce/woocommerce#23516]
**I keep getting this fatal error when my woocommerce plugin is activated on my site:**

Fatal error: Cannot redeclare wc_reviews_enabled() (previously declared in /home/eulqeniu/public_html/wp-content/themes/konte/inc/functions/shop.php:196) in /home/eulqeniu/public_html/wp-content/plugins/woocommerce/includes/wc-conditional-functions.php on line 430

**Comment by claudiosanches** [comment]
Your theme is redeclare a function from WooCommerce, so please contact the author directly for support, this theme need to be updated asap.
