### ISSUE TITLE
woocommerce_price_filter_widget_texts filter

### ISSUE THREAD

**Issue by Stas0238** [woocommerce/woocommerce#23523]
Hello, can you add new filter for woocommerce_price_filter_widget to filter its texts to make some changes for them without translation plugins, so that users will be able to add icon on button or any other feature what they will have in their imagination :) path is: woocommerce/includes/widgets/class-wc-widget-price-filter.php

$widget_texts = apply_filters('woocommerce_price_filter_widget_texts', array(
			'filter' => esc_html__('Filter', 'woocommerce'),
			'price' => esc_html__('Price', 'woocommerce')
		) );

<img width="1706" alt="Screen Shot 2019-04-26 at 11 08 31 AM" src="https://user-images.githubusercontent.com/25957803/56797173-5ff46e80-6814-11e9-810a-3637147cd593.png">

**Comment by mikejolley** [comment]
Icons can be added using CSS, and as you point out the text can be changed via localisation.

We don't feel all text needs to be wrapped in filters as this would quickly get out of hand if every string was wrapped in a filter (this also creates performance bottlenecks).

Someone has opened a PR to move this to a template FWIW here https://github.com/woocommerce/woocommerce/pull/23384

Thanks

cc @peterfabian

**Comment by Stas0238** [comment]
@mikejolley  i meant svg icon which cannot be added by simple css. How can i do this ?

**Comment by mikejolley** [comment]
You'll need the template change above ^ Or use icon fonts and simple css :)

**Comment by Stas0238** [comment]
@mikejolley 
<img width="1566" alt="Screen Shot 2019-04-26 at 3 37 24 PM" src="https://user-images.githubusercontent.com/25957803/56811552-4285cb80-6839-11e9-90c4-7d85484413aa.png">
Sorry, but it seems that there is not class_exists() condition to rewrite the class above, so this function is not rewritable as I see. Can you advice how can i do it now ?

**Comment by Stas0238** [comment]
@mikejolley By the way, http://prntscr.com/nh8drm I guess it looks much better to wrap that div.summary.entry-summary inside hook. What do you think about implementing this in next update of plugin ?

**Comment by mikejolley** [comment]
The PR with the new template file has not been merged yet.

**Comment by Stas0238** [comment]
@mikejolley ok. I will wait on it.  How about this https://github.com/woocommerce/woocommerce/issues/23523#issuecomment-487068180 ? Can it be added ?

**Comment by claudiosanches** [comment]
@Stas0238 the problem with https://github.com/woocommerce/woocommerce/issues/23523#issuecomment-487068180 is that will break existing themes for sure, duplicating that wrap.

**Comment by Stas0238** [comment]
@claudiosanches ok, i got you. But if you did it from start then it would be better to wrap it
