### ISSUE TITLE
To broad of selector in single-product.js

### ISSUE THREAD

**Issue by topdown** [woocommerce/woocommerce#23539]
Having the un-needed `ul.tabs li a` in there disables any anchors for other frameworks that may have tabs on the single product page that are not expected to act like woo tabs.

https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/single-product.js#L28
```js
		.on( 'click', '.wc-tabs li a, ul.tabs li a', function( e ) {
			e.preventDefault();
```

**To Reproduce**
Add any framework that uses ul.tabs li a and the default for the anchor on that page is disabled.

**Fix**
Remove `, ul.tabs li a` it's overkill and generic.

**Comment by kloon** [comment]
Unfortunately, it is not as easy as just removing the functionality, it is there for a reason. A lot of themes still do not use the wc-tabs class so we have to add this for backward compatibility.

What you can do to remedy this is to add some code to your framework to use the `off` jquery event handler to remove the click event from your specific anchors in list items.
