### ISSUE TITLE
thankyou hook

### ISSUE THREAD

**Issue by Stas0238** [woocommerce/woocommerce#23537]
Can you please add do_action( 'woocommerce_before_thankyou') and do_action( 'woocommerce_after_thankyou') in checkout/thankyou.php just like you guys have in other templates such as cart, empty_cart, checkout templates. Because for this moment there is not start/end action to add some content for this specific page only. Please, it is not so annoying for you :)

**Comment by peterfabian** [comment]
Please see #23538.
