### ISSUE TITLE
Front end and back end woocomm popup cart ajax error messages

### ISSUE THREAD

**Issue by scifi247365** [woocommerce/woocommerce#23542]
Hi,

I'm using Wordpress and I just started to get error messages after an update.  The error messages are showing up on my website and in the back end wordpress.  I followed the instructions on the Wordpress support page and it directed me here and said that I need to raise it here, so here I am.

The error messages are to do with a woocommerce plugin.  I upgraded it to the pro version and when I tried to activate it, it could not upgrade it as the previous error messages were still there.

The error messages are as follows:

Warning: Illegal string offset '_wcspc_auto_show_ajax' in /homepages/15/d733566051/htdocs/clickandbuilds/QSIslamicStore/wp-content/plugins/woocomm-popup-cart-ajax/inc/class-admin.php on line 161

Warning: Illegal string offset '_wcspc_auto_show_normal' in /homepages/15/d733566051/htdocs/clickandbuilds/QSIslamicStore/wp-content/plugins/woocomm-popup-cart-ajax/inc/class-admin.php on line 180

Warning: Illegal string offset '_wcspc_manual_show' in /homepages/15/d733566051/htdocs/clickandbuilds/QSIslamicStore/wp-content/plugins/woocomm-popup-cart-ajax/inc/class-admin.php on line 193

Warning: Illegal string offset '_wcspc_position' in /homepages/15/d733566051/htdocs/clickandbuilds/QSIslamicStore/wp-content/plugins/woocomm-popup-cart-ajax/inc/class-admin.php on line 215

Warning: Illegal string offset '_wcspc_primary_colors' in /homepages/15/d733566051/htdocs/clickandbuilds/QSIslamicStore/wp-content/plugins/woocomm-popup-cart-ajax/inc/class-admin.php on line 229

Warning: Illegal string offset '_wcspc_secondary_colors' in /homepages/15/d733566051/htdocs/clickandbuilds/QSIslamicStore/wp-content/plugins/woocomm-popup-cart-ajax/inc/class-admin.php on line 241

Warning: Illegal string offset '_wcspc_bg_colors' in /homepages/15/d733566051/htdocs/clickandbuilds/QSIslamicStore/wp-content/plugins/woocomm-popup-cart-ajax/inc/class-admin.php on line 253

Warning: Illegal string offset '_wcspc_bg_image' in /homepages/15/d733566051/htdocs/clickandbuilds/QSIslamicStore/wp-content/plugins/woocomm-popup-cart-ajax/inc/class-admin.php on line 265

Warning: Illegal string offset '_wcspc_attributes' in /homepages/15/d733566051/htdocs/clickandbuilds/QSIslamicStore/wp-content/plugins/woocomm-popup-cart-ajax/inc/class-admin.php on line 281

Warning: Illegal string offset '_wcspc_total' in /homepages/15/d733566051/htdocs/clickandbuilds/QSIslamicStore/wp-content/plugins/woocomm-popup-cart-ajax/inc/class-admin.php on line 298

Warning: Illegal string offset '_wcspc_buttons' in /homepages/15/d733566051/htdocs/clickandbuilds/QSIslamicStore/wp-content/plugins/woocomm-popup-cart-ajax/inc/class-admin.php on line 315

Warning: Illegal string offset '_wcspc_continue' in /homepages/15/d733566051/htdocs/clickandbuilds/QSIslamicStore/wp-content/plugins/woocomm-popup-cart-ajax/inc/class-admin.php on line 331

Warning: Illegal string offset '_wcspc_reload' in /homepages/15/d733566051/htdocs/clickandbuilds/QSIslamicStore/wp-content/plugins/woocomm-popup-cart-ajax/inc/class-admin.php on line 348

Warning: Illegal string offset '_wcspc_count' in /homepages/15/d733566051/htdocs/clickandbuilds/QSIslamicStore/wp-content/plugins/woocomm-popup-cart-ajax/inc/class-admin.php on line 365

Warning: Illegal string offset '_wcspc_count_position' in /homepages/15/d733566051/htdocs/clickandbuilds/QSIslamicStore/wp-content/plugins/woocomm-popup-cart-ajax/inc/class-admin.php on line 383

Warning: Illegal string offset '_wcspc_count_icon' in /homepages/15/d733566051/htdocs/clickandbuilds/QSIslamicStore/wp-content/plugins/woocomm-popup-cart-ajax/inc/class-admin.php on line 400

Warning: Illegal string offset '_wcspc_count_hide_empty' in /homepages/15/d733566051/htdocs/clickandbuilds/QSIslamicStore/wp-content/plugins/woocomm-popup-cart-ajax/inc/class-admin.php on line 417

Warning: Illegal string offset '_wcspc_count_hide_checkout' in /homepages/15/d733566051/htdocs/clickandbuilds/QSIslamicStore/wp-content/plugins/woocomm-popup-cart-ajax/inc/class-admin.php on line 434

Fatal error: Cannot redeclare ATA_WCFC() (previously declared in /homepages/15/d733566051/htdocs/clickandbuilds/QSIslamicStore/wp-content/plugins/woocomm-popup-cart-ajax/woocommerce-popup-cart+ajax.php:99) in /homepages/15/d733566051/htdocs/clickandbuilds/QSIslamicStore/wp-content/plugins/woocommerce-smart-popup-cart/woocommerce-smart-popup-cart.php on line 96

Can someone please help me, as the error messages are front end as well and are visible on every page.

Thank you.

**Comment by peterfabian** [comment]
Hi, 

this seems like a problem with "WooCommerce Popup Cart + ajax" plugin. Please contact their support https://wordpress.org/support/plugin/woocomm-popup-cart-ajax/ or plugin author.
