### ISSUE TITLE
System Status Report doesn't show plugin is out of date

### ISSUE THREAD

**Issue by EtiennePoolman** [woocommerce/woocommerce#23547]
Reported in https://wordpress.org/support/topic/woocommercestatus-active-plugins/

I'm not sure since which version was the last version that showed an update was available for plugins, but from a couple of sites I have checked, it seems to be around 3.5.5 it changed.

Before, the System Status Report would show when a plugin had an update available with this text;

`WooCommerce Bookings: by Automattic – 1.11.2 – 1.14.0 is available`

On my test site with 3.6.2, no indication is given that the plugin is out of date, only the text that it is not tested with the active version of WooCommerce;

![Screenshot](https://cld.wthms.co/J0gsL6+)
Screenshot direct link: https://cld.wthms.co/J0gsL6

All three plugins other than WooCommerce on that site is actually outdated.

**Comment by peterfabian** [comment]
Please see #23601.

**Comment by TomasHurtz** [comment]
Just a question... https://github.com/woocommerce/woocommerce/pull/23601#issuecomment-493723531

**Comment by peterfabian** [comment]
Hi, seems like there was an update in the bahviour--previously the code checked for updates on the fly via a cloudflare address (https://github.com/woocommerce/woocommerce/pull/22887/commits/236d9827ee7a614e25a38fd30a50b980a77d64bd), now it checks via woocommerce.com API and saves the data in a transient. 
However, for this to work properly for plugins not listed on the wordpress.org, your site needs to be connected to woocommerce.com.

**Comment by TomasHurtz** [comment]
thanks for update. You mean this ?  https://docs.woocommerce.com/document/log-into-woocommerce-com-with-wordpress-com/

**Comment by peterfabian** [comment]
I understand your concern. I'm not 100% sure about the reason there, but I think the idea was that those plugins are only available for purchase via woocommerce.com, therefore you need to have the account anyway, so why not connect and make use of the service. 
The improvement is that now the status report is quicker as the response is cached and makes use of the common `WC_Helper_Updater` class that provides interface to woocommerce.com API.

**Comment by TomasHurtz** [comment]
So there no more public change log for woocommerce addons? I find that to be super annoying - am I the only one?

**Comment by peterfabian** [comment]
As far as I know, the public changelog is still available, they're all linked from woocommerce.com:
<img width="1477" alt="Screenshot 2019-05-27 at 10 26 25" src="https://user-images.githubusercontent.com/2207451/58406501-04fba480-806a-11e9-9a82-d31f2fa3a0ad.png">

It's just the way how WooCommerce core checks for updates that has changed.
