### ISSUE TITLE
Shop page shows more search results on the first page 

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce#23541]
**Describe the bug**
When I choose to show categories and products in Shop page display, the first shop page does show categories and products but more items than it's set in Products per row/rows per page.

**To Reproduce**
1. Go to Customizer > WooCommerce > Product Catalog and set the following:

![https://cld.wthms.co/sdgG8v](https://cld.wthms.co/sdgG8v+) 
Full Size: https://cld.wthms.co/sdgG8v

2. You'd expect 9 items on the first page, but instead, it shows categories + 9 products so 11 in total while wording says 9 items:

![https://cld.wthms.co/PJ3GlB](https://cld.wthms.co/PJ3GlB+) 
Full Size: https://cld.wthms.co/PJ3GlB

**Expected behavior**
I agree with the user who reported it (1989763-zen) that it is confusing, and also having spaces at the end of the first search page make customers think that these are all search results.

I'd expect 9 items to be on the first shop page, and show a correct number of items on it.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by kloon** [comment]
You will also get blanks at the end of the page if you change the columns and rows values to values that are not divisible by the number of products or categories so no matter what you change the values to, as you add products or categories you will end up with blanks somewhere at the end of the page.

The count is also only applicable to products, and from the screenshot there are 9 products showing so not bug there.

Closing this as there is nothing we can do as I explained you will always end up with a blank or two depending on your settings, number of products and/or categories.
