### ISSUE TITLE
mini cart hooks

### ISSUE THREAD

**Issue by Stas0238** [woocommerce/woocommerce#23545]
Hello woocommerce devs, I checked the cart/mini-cart.php and cart/cart.php and noticed that some hooks could be added inside to make the content more customizable.
1) You have woocommerce_widget_shopping_cart_before_buttons hook but you don't have the same after it something like woocommerce_widget_shopping_cart_after_buttons for wrapping some (added) content in one specific block element. Can it be implemented as a new hook ?
2) Can you guys add an action for woocommerce-mini-cart__total content or maybe whole paragraph with it's content inside :). It is 'chained' with the prev. task. (I want to have one block with subtotal and buttons in it, for now there is two blocks).
3) Cart/cart.php has woocommerce_cart_collaterals hook. Before it there is a form with woocommerce_before_cart_table and woocommerce_after_cart_table hooks inside. The question is - can you please, add the woocommerce_before_cart_collaterals and woocommerce_after_cart_collaterals hooks. It will help users who have two columns layout  ( there is a lot of those who do this way ) to add some content just after form. For this time we can add some content before collaterals with 'woocommerce_after_cart_table' hook but it's wrapped in form, which is not as good. (Ex. loader on refreshing is positioned according to all this form ). Thanks for support 👍

**Comment by woocommercecodes** [comment]
The devs should add qty buttons/icons/ + and - to the minicart for each product. Other systems have it, but not WC. So many basic features missing.
