### ISSUE TITLE
Attribute Custom Sort order is not used when adding an attribute to a product

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#23549]
**Describe the bug**
When we have an attribute that is configured using a "Custom Sort" order. In Product > Attributes the custom order is respected. Also on the frontend view we can see attributes being ordered correctly. However when we add a new attribute to a product the order defaults back to "name".

**To Reproduce**
1. Go to Product > Attributes, and create a new attribute with "custom ordering"
2. Add several attributes in a random order such as "Four, Two, One Three, Five"
3. Sort the attributes so they are in the right order, like "One, Two, Three, Four, Five"
4. Add the attribute to a product and try to add some terms
5. Notice that they are sorted by name and not by the custom order

**Screenshots**
![image](https://user-images.githubusercontent.com/11388669/56905168-a60d3480-6a97-11e9-89fb-b50f19f85659.png)

**Expected behavior**
I'd expect it to use the custom sort order. When testing the same with version 3.5.8, the custom sort order is respected
![image](https://user-images.githubusercontent.com/11388669/56905046-6fcfb500-6a97-11e9-9375-d6a42684eb55.png)

When we have a look at the attribute arguments it's explicitly set to sort by name: https://github.com/woocommerce/woocommerce/blob/3.6.2/includes/admin/meta-boxes/views/html-product-attribute.php#L43

That code has been there for a while but it seems in 3.6 and 3.6.2 there were some changes in how the default sort order is handled: https://github.com/woocommerce/woocommerce/commit/d8fe7988254832469773c420411fd958cc70d405

As a workaround the following code snippet reverts it back to the default sort order:

```
add_filter( 'woocommerce_product_attribute_terms', 'woo_custom_woocommerce_product_attribute_terms' );
function woo_custom_woocommerce_product_attribute_terms( $args ) {
	unset( $args['orderby'] );
	return $args;
}
```

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

```
WordPress 5.1.1
WooCommerce 3.6.2
Storefront 2.4.6
```
</details>

**Comment by claudiosanches** [comment]
See #23625
