### ISSUE TITLE
ZIP codes are not used in some countries like Hong Kong or Macau, yet the onboarding wizard asks for it

### ISSUE THREAD

**Issue by grigorijurasov** [woocommerce/woocommerce#23544]
**Is your feature request related to a problem? Please describe.**
ZIP codes are not used in some countries like Hong Kong or Macau, yet the onboarding wizard asks for it

**Describe the solution you'd like**
The ZIP code field should become optional in the onboarding wizard if a country that doesn't use ZIP codes is chosen.

**Describe alternatives you've considered**
Alternatively,  ZIP code field should disappear from the onboarding wizard if a country that doesn't use ZIP codes is chosen.

**Additional context**
1992600 zen

A workaround is to enter a random string instead of the ZIP code to the currently mandatory field.

**Comment by vedanshujain** [comment]
Closing this to move conversation to https://github.com/woocommerce/woocommerce/pull/23915
