### ISSUE TITLE
Not possible to order related products returned by `wc_get_related_products()`

### ISSUE THREAD

**Issue by benhuson** [woocommerce/woocommerce#23558]
The `wc_get_related_products()` function contain plenty of filters to customise the related products that are retrieved for a product.

The last filter `woocommerce_related_products` gives you complete control to override and return whichever posts you like in whatever order you like.

However that is immediately followed by `shuffle( $related_posts )` which means it is impossible to control the order of the related products via the filter.

I have a scenario where I would like to prioritise some related products based on their tag or sale status etc. I can handle this all fine within the filters provided, however that `shuffle()` then messes up any custom ordering.

It would be good to deprecate that `shuffle()` in a way that is backward compatible. Perhaps a filter that defaults to returning `true` to shuffle, which can be overridden? Moving it to before the `woocommerce_related_products` filter would not be fully back-compatible as it would prevent the random ordering where users had override the posts using the filter.

**Comment by benhuson** [comment]
Sort of relates to making #8970 feasible.

**Comment by benhuson** [comment]
It looks like to control any of the ordering functionality I need to override the `woocommerce_related_products()` function which is responsible for loading the template. I just wanted filter the posts via a plugin to prepend some extra posts via hooks rather than having to override a function.

**Comment by kloon** [comment]
See #23562
