### ISSUE TITLE
cannot partial refund 

### ISSUE THREAD

**Issue by arborarms** [woocommerce/woocommerce#23550]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by arborarms** [comment]
I can no longer put in a partial amounts for refunds in woocomerce I used to be able to so this is a fairly recent bug. I cant even select the box to input the amout although it still looks thre same i.e. amount box and resaon box

**Comment by polevaultweb** [comment]
Same. I cannot set the partial refund amount for completed orders. The refund amount is greyed out, the input element is `readonly`:

![image](https://user-images.githubusercontent.com/1770201/56953071-b115a280-6b33-11e9-9275-be01cc2858b2.png)

**Comment by polevaultweb** [comment]
This has been explained here (and partial refunds are still possible, by editing the amount of the line item) https://github.com/woocommerce/woocommerce/wiki/3.6.x-notes-FAQ#the-refund-input-field-is-grayed-out-when-viewing-orders-and-trying-to-refund-items

**Comment by polevaultweb** [comment]
https://github.com/woocommerce/woocommerce/issues/23379#issuecomment-484610279

**Comment by kloon** [comment]
Please see the link @polevaultweb posted, this is intentional for tax purposes. Ways to refund are explained at the link.

**Comment by lutifyme** [comment]
@polevaultweb I know this is an old thread but could someone please explain how to make partial refund when there's only one item? Yes, if there are two order items and you need to refund one it's possible but how about one item which needs to be partially refunded. For example customer purchased 1 item for the amount of $100 but needs to be refunded $20. We're not removing an order item, just offering partial refund for that one item. I can't believe this is not possible or has been thought of. Also, it could make sense if this was behaviour for orders with taxes only, but if you have any sort of taxes enabled (for one country out of hundreds) in woo this is the default behaviour globally even for orders to which taxes do not apply.
