### ISSUE TITLE
Scheduled actions created by WooCommerce add NULL <0x00> characters to XML export (invalid character for XML)

### ISSUE THREAD

**Issue by dedalx** [woocommerce/woocommerce#23555]
**Describe the bug**
Scheduled actions created by WooCommerce add NULL <0x00> characters to XML export (invalid characted for XML). Null characters does not allowed in XML structure and give errors when this XML file parsed via PHP (for example via custom XML processing, for custom theme demo import).

**To Reproduce**
1. Go to Tools > Export and Export all content.
2. Search XML for any "scheduled-action".
3. See <0x00> NULL characters

**Screenshots**
https://i.magnium-themes.com/content.xml_2019-04-30_11-02-10.jpg

**Expected behavior**
XML file should not contain NULL characters.

**Isolating the problem (mark completed items with an [x]):**
- [ X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ X ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WordPress 5.1.1

**Comment by rrennick** [comment]
Scheduled actions have been removed from the export in #23456 .
