### ISSUE TITLE
When creating a order via Woocommerce Rest API order note showing two notes for order status and also Not sending a correct email

### ISSUE THREAD

**Issue by codetycon** [woocommerce/woocommerce#23552]
Facing an issue when creating a order via WooCommerce rest API. There are two issues:

Order Note When creating order via Desktop:- New Order of "BANK Transfer" as a payment creating two order note
Order status changed from pending payment to on hold
For order stock reduced
When creating order via Mobile:- New order with "Bank Transfer" as a payment method creating three order note:- 1. Order status changed from pending payment to processing 2. Order stock reduced 3. Order status changed from pending payment to on hold

Customer Receiving a email with status processing, while the order status is on-hold
I tried to pass order status=on-hold from API when creating a order and updating a order payment details. But issue is still persist.

Order create api

POST wc-api/v3/orders/

Body
{
  "order": {
    "customer_id": 6925,
    "billing_address": {
      "first_name": "Android",
      "last_name": "Testing",
      "address_1": "Address of Developer",
      "address_2": "Cengkareng",
      "city": "Jakarta Barat",
      "state": "6",
      "postcode": "12345",
      "country": "ID",
      "email": "ankurgecr@gmail.com",
      "phone": "1234567890"
    },
    "shipping_address": {
      "first_name": "Android",
      "last_name": "Testing",
      "address_1": "Address of Developer",
      "address_2": "Cengkareng",
      "city": "Jakarta Barat",
      "state": "6",
      "postcode": "12345",
      "country": "ID"
    },
    "line_items": [
      {
        "product_id": 32776,
        "quantity": 1,
        "subtotal": 10000,
        "total": 10000,
        "variations": {
          "Color": "Blue"
        }
      }
    ],
    "fee_lines": [
      {
        "title": "Rp",
        "total": 846
      }
    ],
    "shipping_lines": [
      {
        "method_id": "OKE",
        "method_title": "JNE OKE",
        "total": 29500
      }
    ],
    "is_vat_exempt": false
  }
}

Order update API

POST wc-api/orders/[orderID]

BODY  {
  "order": {
    "status": "on-hold",
    "payment_details": {
      "method_id": "bacs",
      "method_title": "Bank Transfer BCA / MANDIRI",
      "paid": true
    },
    "set_paid": true
  }
}

Custoemr should receive a email of order status= on-hold.

I'm attaching a image for actual result.

Note: Is is working fine if we are placing a orde from website checkout, only the issue is with rest API.

**Comment by codetycon** [comment]
@claudiosanches Is there any bug with the API or I'm sending a wrong request?

**Comment by codetycon** [comment]
Any solution?

**Comment by codetycon** [comment]
@claudiosanches 
Could you please let me know the status of this bug because I have a number of users on my mobile shopping app and they are getting wrong emails.

**Comment by claudiosanches** [comment]
@codetycon I'll update when I have it tested, no worry.

**Comment by claudiosanches** [comment]
> Custoemr should receive a email of order status= on-hold.

This is incorrect, order status should be updated to `processing`, since you set that the order is already paid.

```
POST wc-api/orders/[orderID]

BODY {
"order": {
"status": "on-hold",
"payment_details": {
"method_id": "bacs",
"method_title": "Bank Transfer BCA / MANDIRI",
"paid": true
},
"set_paid": true
}
}
```

If you want to keep in as `on-hold`, you can't say that is already paid. Not a bug, it's normal it, still I recommend you to update to our new REST API, you are using our legacy REST API that will be removed soon from WooCommerce.

**Comment by codetycon** [comment]
I also tried with paid=false and set-paid= false

But order showing in wp admin as a processing

**Comment by codetycon** [comment]
![screenshot-emorystyle com-2019 05 07-12-33-26](https://user-images.githubusercontent.com/32788804/57278550-5eecf800-70c4-11e9-9e75-afd4a4b2caee.png)
![screenshot-emorystyle com-2019 05 07-12-31-34](https://user-images.githubusercontent.com/32788804/57278551-5f858e80-70c4-11e9-8c91-36a9cfdc8a11.png)

Please check attached images
1. Order placed via Website showing info about inventory while an order placed via API not showing inventory

**Comment by claudiosanches** [comment]
You don't need to send that field, no reason unless you want to set as true.
