### ISSUE TITLE
Product variation not showing in dropdown when creating new order

### ISSUE THREAD

**Issue by E-VANCE** [woocommerce/woocommerce#23554]
**Describe the bug**
We are creating manual orders (via backend –> new order) in our shop since some customers buy products in store and we generate the invoices via WooCommerce.

The issue at hand is, that we are unable to select some product variations in the add new product modal – strangely enough some variations do show up but others don't, most probably due to the amount of results returned. I saw that the variations are almost always positioned last in the list or at least near the end and I assume that the results are being cut off (30 showing at most) and thus the desired variation would technically be found but isn't available for selection.

The product in question is called **Baum** (tree) and its variations are called

- Apfelbaum
- Birnbaum
- Ahorn _not found_
- Eiche _not found_
- Grundplatte

Since we are running a shop for wooden toys and "Ahorn" & "Eiche" refer not only to a specific product (variation) but also specify the type of wood used for numerous toys (as a product attribute) this seems to 'taint' the results and push the variations to the back where I cannot select them any more.

If I search for the product ID (1570 f.ex.) as a workaround then it shows fine but this isn't really feasible for the 'common' user...

**Expected behavior**
I'd expect the variations attributes / taxonomies to have a higher 'score' in the dropdowns' search results, pushing them closer to the top.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

    ### WordPress Environment ###

    WordPress address (URL): xxx
    Site address (URL): xxx
    WC Version: 3.6.2
    Log Directory Writable: ✔
    WP Version: 5.1.1
    WP Multisite: –
    WP Memory Limit: 512 MB
    WP Debug Mode: –
    WP Cron: ✔
    Language: de_DE
    External object cache: –

    ### Server Environment ###

    Server Info: nginx/1.11.10
    PHP Version: 7.0.33 - Wir empfehlen
    PHP Version 7.2 oder höher für mehr Leistung und Sicherheit zu verwenden. So aktualisierst du deine PHP-Version

    PHP Post Max Size: 16 MB
    PHP Time Limit: 120
    PHP Max Input Vars: 1000
    cURL Version: 7.22.0
    OpenSSL/1.0.1

    SUHOSIN Installed: –
    MySQL Version: ❌ 5.5.54-0ubuntu0.12.04.1-log - Wir empfehlen mindestens MySQL-Version 5.6. Siehe: WordPress-Anforderungen
    Max Upload Size: 10 MB
    Default Timezone is UTC: ✔
    fsockopen/cURL: ✔
    SoapClient: ✔
    DOMDocument: ✔
    GZip: ✔
    Multibyte String: ✔
    Remote Post: ✔
    Remote Get: ✔

    ### Database ###

    WC Database Version: 3.6.2
    WC Database Prefix: xxx_
    Datenbank-Gesamtgröße: 146.34MB
    Datenbank-Datengröße: 91.37MB
    Datenbank-Indexgröße: 54.97MB
    xxx_woocommerce_sessions: Daten: 0.05MB + Index: 0.02MB
    xxx_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB
    xxx_woocommerce_attribute_taxonomies: Daten: 0.00MB + Index: 0.01MB
    xxx_woocommerce_downloadable_product_permissions: Daten: 0.00MB + Index: 0.00MB
    xxx_woocommerce_order_items: Daten: 1.54MB + Index: 1.05MB
    xxx_woocommerce_order_itemmeta: Daten: 13.18MB + Index: 9.31MB
    xxx_woocommerce_tax_rates: Daten: 0.00MB + Index: 0.01MB
    xxx_woocommerce_tax_rate_locations: Daten: 0.00MB + Index: 0.00MB
    xxx_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB
    xxx_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.05MB
    xxx_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB
    xxx_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB
    xxx_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB
    xxx_woocommerce_log: Daten: 0.02MB + Index: 0.02MB
    xxx_apto: Daten: 0.02MB + Index: 0.02MB
    xxx_apto_sort_list: Daten: 0.05MB + Index: 0.02MB
    xxx_commentmeta: Daten: 0.42MB + Index: 0.30MB
    xxx_comments: Daten: 3.03MB + Index: 1.19MB
    xxx_ewwwio_images: Daten: 3.20MB + Index: 1.65MB
    xxx_ewwwio_queue: Daten: 0.02MB + Index: 0.02MB
    xxx_faq_termmeta: Daten: 0.02MB + Index: 0.00MB
    xxx_followup_coupons: Daten: 0.00MB + Index: 0.00MB
    xxx_followup_coupon_logs: Daten: 0.00MB + Index: 0.00MB
    xxx_followup_customers: Daten: 0.11MB + Index: 0.24MB
    xxx_followup_customer_carts: Daten: 3.28MB + Index: 0.16MB
    xxx_followup_customer_notes: Daten: 0.02MB + Index: 0.03MB
    xxx_followup_customer_orders: Daten: 0.08MB + Index: 0.12MB
    xxx_followup_emails: Daten: 0.00MB + Index: 0.00MB
    xxx_followup_email_coupons: Daten: 0.00MB + Index: 0.00MB
    xxx_followup_email_excludes: Daten: 0.00MB + Index: 0.00MB
    xxx_followup_email_logs: Daten: 0.00MB + Index: 0.00MB
    xxx_followup_email_orders: Daten: 0.00MB + Index: 0.01MB
    xxx_followup_email_order_coupons: Daten: 0.00MB + Index: 0.00MB
    xxx_followup_email_tracking: Daten: 0.00MB + Index: 0.00MB
    xxx_followup_followup_history: Daten: 0.02MB + Index: 0.05MB
    xxx_followup_order_categories: Daten: 0.24MB + Index: 0.47MB
    xxx_followup_order_items: Daten: 0.47MB + Index: 0.96MB
    xxx_followup_subscribers: Daten: 0.05MB + Index: 0.03MB
    xxx_followup_subscribers_to_lists: Daten: 0.02MB + Index: 0.03MB
    xxx_followup_subscriber_lists: Daten: 0.02MB + Index: 0.03MB
    xxx_itsec_dashboard_events: Daten: 0.05MB + Index: 0.02MB
    xxx_itsec_distributed_storage: Daten: 0.02MB + Index: 0.02MB
    xxx_itsec_fingerprints: Daten: 0.02MB + Index: 0.03MB
    xxx_itsec_geolocation_cache: Daten: 0.02MB + Index: 0.03MB
    xxx_itsec_lockouts: Daten: 0.16MB + Index: 0.31MB
    xxx_itsec_logs: Daten: 9.02MB + Index: 0.73MB
    xxx_itsec_temp: Daten: 0.06MB + Index: 0.06MB
    xxx_links: Daten: 0.00MB + Index: 0.00MB
    xxx_lockdowns: Daten: 0.00MB + Index: 0.00MB
    xxx_login_fails: Daten: 0.01MB + Index: 0.00MB
    xxx_options: Daten: 7.48MB + Index: 1.27MB
    xxx_postmeta: Daten: 22.82MB + Index: 13.86MB
    xxx_posts: Daten: 4.43MB + Index: 0.63MB
    xxx_ps_exclude: Daten: 0.02MB + Index: 0.02MB
    xxx_ps_keyword: Daten: 0.02MB + Index: 0.00MB
    xxx_ps_postmeta: Daten: 0.02MB + Index: 0.03MB
    xxx_ps_posts: Daten: 0.08MB + Index: 0.00MB
    xxx_ps_product_categories: Daten: 0.02MB + Index: 0.00MB
    xxx_ps_product_sku: Daten: 0.02MB + Index: 0.00MB
    xxx_ps_product_tags: Daten: 0.02MB + Index: 0.00MB
    xxx_ps_term_relationships: Daten: 0.05MB + Index: 0.02MB
    xxx_redirection_404: Daten: 0.00MB + Index: 0.00MB
    xxx_redirection_groups: Daten: 0.00MB + Index: 0.00MB
    xxx_redirection_items: Daten: 0.14MB + Index: 0.13MB
    xxx_redirection_logs: Daten: 0.09MB + Index: 0.03MB
    xxx_revslider_css: Daten: 0.00MB + Index: 0.00MB
    xxx_revslider_layer_animations: Daten: 0.00MB + Index: 0.00MB
    xxx_revslider_settings: Daten: 0.00MB + Index: 0.00MB
    xxx_revslider_sliders: Daten: 0.00MB + Index: 0.00MB
    xxx_revslider_slides: Daten: 0.02MB + Index: 0.00MB
    xxx_revslider_static_slides: Daten: 0.02MB + Index: 0.00MB
    xxx_swpext_metrics_clicks: Daten: 0.14MB + Index: 0.17MB
    xxx_swpext_metrics_ids: Daten: 2.52MB + Index: 3.03MB
    xxx_swpext_metrics_queries: Daten: 0.14MB + Index: 0.14MB
    xxx_swpext_metrics_searches: Daten: 1.52MB + Index: 3.27MB
    xxx_swp_cf: Daten: 0.02MB + Index: 0.05MB
    xxx_swp_index: Daten: 5.36MB + Index: 3.69MB
    xxx_swp_log: Daten: 3.52MB + Index: 5.55MB
    xxx_swp_tax: Daten: 0.08MB + Index: 0.11MB
    xxx_swp_terms: Daten: 1.52MB + Index: 1.06MB
    xxx_termmeta: Daten: 0.08MB + Index: 0.09MB
    xxx_terms: Daten: 0.06MB + Index: 0.12MB
    xxx_term_relationships: Daten: 0.07MB + Index: 0.16MB
    xxx_term_taxonomy: Daten: 0.04MB + Index: 0.05MB
    xxx_usermeta: Daten: 4.96MB + Index: 3.77MB
    xxx_users: Daten: 0.35MB + Index: 0.42MB
    xxx_wc_download_log: Daten: 0.02MB + Index: 0.03MB
    xxx_wc_product_meta_lookup: Daten: 0.08MB + Index: 0.09MB
    xxx_wc_webhooks: Daten: 0.02MB + Index: 0.02MB
    xxx_woocommerce_paydirektcw_customer_contexts: Daten: 0.02MB + Index: 0.02MB
    xxx_woocommerce_paydirektcw_documents: Daten: 0.02MB + Index: 0.02MB
    xxx_woocommerce_paydirektcw_ecc: Daten: 0.02MB + Index: 0.00MB
    xxx_woocommerce_paydirektcw_schema_version: Daten: 0.02MB + Index: 0.02MB
    xxx_woocommerce_paydirektcw_storage: Daten: 0.02MB + Index: 0.00MB
    xxx_woocommerce_paydirektcw_transactions: Daten: 0.06MB + Index: 0.00MB
    xxx_wpmm_subscribers: Daten: 0.02MB + Index: 0.00MB
    xxx_yith_wcwl: Daten: 0.00MB + Index: 0.00MB
    xxx_yoast_seo_links: Daten: 0.02MB + Index: 0.02MB
    xxx_yoast_seo_meta: Daten: 0.08MB + Index: 0.00MB

    ### Post Type Counts ###

    apto_sort: 58
    attachment: 1025
    contactform: 1
    faq: 6
    featurestab: 1
    foobar: 1
    nav_menu_item: 69
    page: 27
    portfolios: 9
    post: 43
    product: 266
    product_variation: 238
    revision: 564
    scheduled-action: 47
    shop_coupon: 4
    shop_order: 4459
    shop_order_refund: 9
    sliders: 1
    wc_order_status: 8

    ### Security ###

    Secure connection (HTTPS): ✔
    Hide errors from visitors: ✔

    ### Active Plugins (37) ###

    Advanced Post Types Order: von Nsp Code – 4.2.5.5
    Antispam Bee: von pluginkollektiv – 2.9.1
    BackupBuddy: von iThemes – 8.3.11.0
    Classic Editor: von WordPress-Mitwirkende – 1.4
    GDPR Cookie Consent: von WebToffee – 1.7.6
    Disable Emojis (GDPR friendly): von Ryan Hellyer – 1.7.2
    Disable New User Notifications: von Thomas Griffin – 1.0.3
    Email Encoder - Protect Email Address: von WebFactory Ltd – 1.51
    Enhanced Text Widget: von Boston Dell-Vandenberg – 1.4.6
    EWWW Image Optimizer: von Exactly WWW – 4.7.3
    iThemes Security Pro: von iThemes – 5.9.4
    Login Logo: von Mark Jaquith – 0.9.0
    Product Sales Report for WooCommerce: von Potent Plugins – 1.4.8 – Nicht getestest mit der aktiven WooCommerce-Version
    Redirection: von John Godley – 4.2.3
    Reveal IDs: von Oliver Schlöbe – 1.5.3
    SearchWP Live Ajax Search: von Jonathan Christopher – 1.3.1
    SearchWP Metrics: von SearchWP LLC – 1.0.8
    SearchWP German Stemmer: von SearchWP LLC – 1.0.2
    SearchWP WooCommerce Integration: von SearchWP LLC – 1.2.1 – Nicht getestest mit der aktiven WooCommerce-Version
    SearchWP: von SearchWP LLC – 3.0.5
    Widget CSS Classes: von C.M. Kendrick – 1.5.3
    Widget Logic: von wpchefgadget alanft – 5.9.0
    Woocommerce Category Permalink Extension: von Liam Bailey (Webby Scots Wordpress - WSWP) – 1.0.0 – Nicht getestest mit der aktiven WooCommerce-Version
    WooCommerce EU VAT Number: von WooCommerce – 2.3.13
    Follow-Up Emails: von WooCommerce – 4.8.10
    WooCommerce Google Analytics Integration: von WooCommerce – 1.4.9
    WooCommerce Order Status Manager: von SkyVerge – 1.9.4
    WooCommerce Print Invoices/Packing Lists: von SkyVerge – 3.6.3
    WooCommerce Sequential Order Numbers Pro: von SkyVerge – 1.13.1
    WooCommerce Shipment Tracking: von WooCommerce – 1.6.13
    WooCommerce: von Automattic – 3.6.2
    WooCommerce PayDirektCw: von customweb GmbH – 2.0.109 – Nicht getestest mit der aktiven WooCommerce-Version
    Yoast SEO: von Team Yoast – 11.0 – Nicht getestest mit der aktiven WooCommerce-Version
    WP Maintenance Mode: von Designmodo – 2.2.3
    WP Migrate DB Pro: von Delicious Brains – 1.9.6
    WP Remote: von maekit – 2.8.4.3
    YITH WooCommerce Zoom Magnifier: von YITH – 1.3.9

    ### Settings ###

    API Enabled: –
    Force SSL: –
    Currency: EUR (€)
    Currency Position: right_space
    Thousand Separator: .
    Decimal Separator: ,
    Number of Decimals: 2
    Taxonomies: Product Types: external (external)
    grouped (grouped)
    simple (simple)
    variable (variable)

    Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
    exclude-from-search (exclude-from-search)
    featured (featured)
    outofstock (outofstock)
    rated-1 (rated-1)
    rated-2 (rated-2)
    rated-3 (rated-3)
    rated-4 (rated-4)
    rated-5 (rated-5)

    Connected to WooCommerce.com: ✔

    ### WC Pages ###

    Shop-Basis: #977 - /shop
    Warenkorb: #7 - /warenkorb
    Kasse: #8 - /kasse
    Mein Konto: #10 - /kundenkonto
    Allgemeine Geschäftsbedingungen: #1282 - /agb

    ### Theme ###

    Name: XXX
    Version: 2.6.3
    Author URL: XXX
    Child Theme: ✔
    Parent Theme Name: XXX
    Parent Theme Version: 2.6.3
    Parent Theme Author URL: XXX
    WooCommerce Support: ✔

    ### Templates ###

    Overrides: xxx/woocommerce/archive-product.php Version 3.3.0 ist veraltet. Die Hauptversion ist 3.4.0
    xxx/woocommerce/cart/cart-empty.php Version 3.1.0 ist veraltet. Die Hauptversion ist 3.5.0
    xxx-parent/woocommerce/cart/cart-shipping.php Version 3.2.0 ist veraltet. Die Hauptversion ist 3.6.0
    xxx/woocommerce/cart/cart-totals.php
    xxx/woocommerce/cart/cart.php Version 2.3.8 ist veraltet. Die Hauptversion ist 3.5.0
    xxx-parent/woocommerce/cart/cross-sells.php
    xxx/woocommerce/cart/mini-cart.php Version 3.3.0 ist veraltet. Die Hauptversion ist 3.5.0
    xxx-parent/woocommerce/checkout/cart-errors.php Version 2.4.0 ist veraltet. Die Hauptversion ist 3.5.0
    xxx/woocommerce/checkout/form-billing.php Version 3.0.9 ist veraltet. Die Hauptversion ist 3.6.0
    xxx/woocommerce/checkout/form-checkout.php Version 2.3.0 ist veraltet. Die Hauptversion ist 3.5.0
    xxx/woocommerce/checkout/form-login.php Version 2.0.0 ist veraltet. Die Hauptversion ist 3.4.0
    xxx/woocommerce/checkout/form-shipping.php Version 3.0.9 ist veraltet. Die Hauptversion ist 3.6.0
    xxx/woocommerce/checkout/payment.php Version 2.5.0 ist veraltet. Die Hauptversion ist 3.5.3
    xxx/woocommerce/checkout/thankyou.php
    xxx-parent/woocommerce/content-product.php Version 3.0.0 ist veraltet. Die Hauptversion ist 3.6.0
    xxx/woocommerce/content-product_cat.php
    xxx/woocommerce/content-single-product.php Version 3.0.0 ist veraltet. Die Hauptversion ist 3.6.0
    xxx/woocommerce/emails/customer-on-hold-order.php Version 2.5.0 ist veraltet. Die Hauptversion ist 3.5.0
    xxx-parent/woocommerce/global/breadcrumb.php
    xxx/woocommerce/global/form-login.php Version 2.1.0 ist veraltet. Die Hauptversion ist 3.6.0
    xxx-parent/woocommerce/global/sidebar.php
    xxx-parent/woocommerce/global/wrapper-end.php
    xxx/woocommerce/global/wrapper-start.php
    xxx-parent/woocommerce/loop/add-to-cart.php
    xxx-parent/woocommerce/loop/pagination.php
    xxx-parent/woocommerce/loop/price.php
    xxx/woocommerce/loop/sale-flash.php
    xxx-parent/woocommerce/order/form-tracking.php Version 3.3.0 ist veraltet. Die Hauptversion ist 3.6.0
    xxx-parent/woocommerce/order/tracking.php
    xxx/woocommerce/product-searchform.php Version 2.5.0 ist veraltet. Die Hauptversion ist 3.3.0
    xxx-parent/woocommerce/single-product/add-to-cart/external.php Version 2.1.0 ist veraltet. Die Hauptversion ist 3.4.0
    xxx-parent/woocommerce/single-product/add-to-cart/grouped.php Version 3.3.0 ist veraltet. Die Hauptversion ist 3.4.0
    xxx-parent/woocommerce/single-product/add-to-cart/simple.php Version 3.0.0 ist veraltet. Die Hauptversion ist 3.4.0
    xxx/woocommerce/single-product/add-to-cart/variable.php Version 3.0.0 ist veraltet. Die Hauptversion ist 3.5.5
    xxx-parent/woocommerce/single-product/meta.php
    xxx/woocommerce/single-product/price.php
    xxx/woocommerce/single-product/related.php
    xxx/woocommerce/single-product/sale-flash.php
    xxx-parent/woocommerce/single-product/share.php Version 1.6.4 ist veraltet. Die Hauptversion ist 3.5.0
    xxx-parent/woocommerce/single-product/tabs/description.php
    xxx-parent/woocommerce/single-product/tabs/tabs.php
    xxx-parent/woocommerce/single-product/title.php
    xxx/woocommerce/single-product/up-sells.php Version 1.6.4 ist veraltet. Die Hauptversion ist 3.0.0
    xxx-parent/woocommerce/single-product-reviews.php Version 3.2.0 ist veraltet. Die Hauptversion ist 3.6.0
    xxx/woocommerce/single-product.php
    xxx-parent/woocommerce/taxonomy-product_cat.php
    xxx-parent/woocommerce/taxonomy-product_tag.php

    Outdated Templates: ❌
    Erfahre wie du aktualisieren kannst

    ### Action Scheduler ###

    Complete: 46
    Oldest: 2019-03-31 06:49:27 +0200
    Newest: 2019-04-30 08:56:33 +0200

    Pending: 1
    Oldest: 2019-05-01 07:51:10 +0200
    Newest: 2019-05-01 07:51:10 +0200

    Canceled: 0
    Oldest: –
    Newest: –

    In-progress: 0
    Oldest: –
    Newest: –

    Failed: 0
    Oldest: –
    Newest: –
</details>

**Comment by kloon** [comment]
What is the search term you would enter to find a matching product? Can help us troubleshoot if we have a sense of how you are using the search?

Also how are your variatons set up? Does the ones you are searching for contain the keywords somewhere in the attributes or the description?

**Comment by E-VANCE** [comment]
> What is the search term you would enter to find a matching product? Can help us troubleshoot if we have a sense of how you are using the search?

Essentially we're searching by variation title, so we're entering "Ahorn" or "Eiche" in that case.

> Also how are your variatons set up? Does the ones you are searching for contain the keywords somewhere in the attributes or the description?

All of our products contain an attribute regarding the type of wood used and thus there are numerous items with "Ahorn" (not used as variation). Even the product "Baum -> Ahorn" contains an additonal attribute "Ahorn" specifying the wood type.

<img width="800" alt="Bildschirmfoto 2019-05-01 um 12 03 16" src="https://user-images.githubusercontent.com/4123541/57013046-de348480-6c09-11e9-9839-bb43c8c529e2.png">

**Comment by kloon** [comment]
Have you tried combining the main product name with the attribute name? That should give you more accurate results.

I am going to close this issue as I am not sure there is much we can do here since that lookup utilizes the same product search used everywhere else on the site. All I can suggest is to use better terms when searching, try and include something from the main product title as well as the attribute name for the variation specific.
