### ISSUE TITLE
HTML Symbol Tags not displaying as symbols in storefront's single product image viewer/gallery

### ISSUE THREAD

**Issue by miketlp** [woocommerce/woocommerce#23566]
I am using the storefront theme, and I noticed that recently (I’m not exactly sure when this happen though) that the captions for my product images are not properly rendering the html symbol tags properly when viewing the product images gallery (after clicking the magnifying glass). For example, things like `"&trade;"` , `“&reg;”` , `"&amp;”` or `“&copy;”`, etc. just show the actual html symbol tag code instead of rendering the actual symbol. I’ve attached some screenshots to see what I’m talking about…

These used to work fine awhile ago regardless if you copied the symbol or the html symbol tag, but not it appears that the html symbol tag isn’t working properly.
<img width="1376" alt="Screen Shot 2019-04-25 at 5 08 39 PM" src="https://user-images.githubusercontent.com/50153710/56989615-7e31d580-6b58-11e9-98bb-45f22e7fe41f.png">
<img width="1374" alt="Screen Shot 2019-04-25 at 5 09 05 PM" src="https://user-images.githubusercontent.com/50153710/56989620-82f68980-6b58-11e9-80f7-46485bd3c185.png">

**Comment by rodrigoprimo** [comment]
I was not able to reproduce this issue. The symbols you mentioned were displayed correctly on my local install running the latest WooCommerce and Storefront versions. See screenshot below.

Could you please provide clear steps to reproduce the issue and a copy of your system status report as requested in the [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=)? Also, if you are sure this is a Storefront problem and not a WooCommerce problem, please open this issue on the Storefront repository (http://github.com/woocommerce/storefront). cc @tiagonoronha 

![Screenshot from 2019-05-01 14-50-27](https://user-images.githubusercontent.com/77215/57032691-5d818280-6c21-11e9-8b61-e655cad05710.png)

**Comment by miketlp** [comment]
Hi Rodrigo,

Thank you very much for responding to my bug report. I was hesitant to post my system status directly on github since my post appears to be public and I didn’t want any sensitive information on there. I’ve pasted my system status report in this email below my message. One thing that I noticed in my original bug report was the Github automatically converted the html codes as the symbols instead of the code itself. I’m not sure if this makes a difference, but my original message should read as this:

"I am using the storefront theme, and I noticed that recently (I’m not exactly sure when this happen though) that the captions for my product images are not properly rendering the html symbol tags properly when viewing the product images gallery (after clicking the magnifying glass). For example, things like "&trade;" , “&reg;” , "&amp;” or “&copy;” , etc. just show the actual html symbol tag code instead of rendering the actual symbol. I’ve attached some screenshots to see what I’m talking about…

These used to work fine awhile ago regardless if you copied the symbol or the html symbol tag, but not it appears that the html symbol tag isn’t working properly."

Lastly, I’m not sure if this is a WooCommerce or Storefront problem. If you think that it might be a Storefront problem (and not a WooCommerce problem) after viewing my system status report, then let me know so that I can post this to Storefront’s Github.


System Status Report:

`
### WordPress Environment ###

WordPress address (URL): https://store.texaslabelprinters.com
Site address (URL): https://store.texaslabelprinters.com
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.1.27 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 64 MB
PHP Time Limit: 6000
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 10.1.38-MariaDB-cll-lve
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: 8g05UKpcVZ_
MaxMind GeoIP Database: ✔
Total Database Size: 47.90MB
Database Data Size: 43.24MB
Database Index Size: 4.66MB
8g05UKpcVZ_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB
8g05UKpcVZ_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
8g05UKpcVZ_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
8g05UKpcVZ_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
8g05UKpcVZ_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB
8g05UKpcVZ_woocommerce_order_itemmeta: Data: 0.22MB + Index: 0.23MB
8g05UKpcVZ_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
8g05UKpcVZ_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
8g05UKpcVZ_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
8g05UKpcVZ_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
8g05UKpcVZ_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
8g05UKpcVZ_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
8g05UKpcVZ_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
8g05UKpcVZ_woocommerce_log: Data: 0.02MB + Index: 0.02MB
8g05UKpcVZ_commentmeta: Data: 0.02MB + Index: 0.03MB
8g05UKpcVZ_comments: Data: 0.13MB + Index: 0.09MB
8g05UKpcVZ_ewwwio_images: Data: 0.41MB + Index: 0.36MB
8g05UKpcVZ_ewwwio_queue: Data: 0.02MB + Index: 0.02MB
8g05UKpcVZ_failed_jobs: Data: 0.02MB + Index: 0.00MB
8g05UKpcVZ_grp_google_place: Data: 0.02MB + Index: 0.02MB
8g05UKpcVZ_grp_google_review: Data: 0.02MB + Index: 0.03MB
8g05UKpcVZ_links: Data: 0.02MB + Index: 0.02MB
8g05UKpcVZ_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
8g05UKpcVZ_mail_bank: Data: 0.00MB + Index: 0.00MB
8g05UKpcVZ_mail_bank_email_logs: Data: 0.02MB + Index: 0.00MB
8g05UKpcVZ_mail_bank_logs: Data: 12.84MB + Index: 0.01MB
8g05UKpcVZ_mail_bank_meta: Data: 0.00MB + Index: 0.00MB
8g05UKpcVZ_options: Data: 2.50MB + Index: 0.09MB
8g05UKpcVZ_pmxi_files: Data: 0.02MB + Index: 0.00MB
8g05UKpcVZ_pmxi_history: Data: 0.02MB + Index: 0.00MB
8g05UKpcVZ_pmxi_images: Data: 0.02MB + Index: 0.00MB
8g05UKpcVZ_pmxi_imports: Data: 0.02MB + Index: 0.00MB
8g05UKpcVZ_pmxi_posts: Data: 0.02MB + Index: 0.03MB
8g05UKpcVZ_pmxi_templates: Data: 0.02MB + Index: 0.00MB
8g05UKpcVZ_postmeta: Data: 2.52MB + Index: 1.97MB
8g05UKpcVZ_posts: Data: 17.05MB + Index: 0.15MB
8g05UKpcVZ_queue: Data: 0.02MB + Index: 0.00MB
8g05UKpcVZ_termmeta: Data: 0.06MB + Index: 0.03MB
8g05UKpcVZ_terms: Data: 0.14MB + Index: 0.19MB
8g05UKpcVZ_term_relationships: Data: 0.13MB + Index: 0.09MB
8g05UKpcVZ_term_taxonomy: Data: 0.14MB + Index: 0.17MB
8g05UKpcVZ_usermeta: Data: 0.17MB + Index: 0.16MB
8g05UKpcVZ_users: Data: 0.02MB + Index: 0.05MB
8g05UKpcVZ_wc_download_log: Data: 0.02MB + Index: 0.03MB
8g05UKpcVZ_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
8g05UKpcVZ_wc_webhooks: Data: 0.02MB + Index: 0.02MB
8g05UKpcVZ_wfblockediplog: Data: 0.02MB + Index: 0.00MB
8g05UKpcVZ_wfblocks7: Data: 0.02MB + Index: 0.05MB
8g05UKpcVZ_wfconfig: Data: 0.44MB + Index: 0.00MB
8g05UKpcVZ_wfcrawlers: Data: 0.02MB + Index: 0.00MB
8g05UKpcVZ_wffilechanges: Data: 0.02MB + Index: 0.00MB
8g05UKpcVZ_wffilemods: Data: 3.52MB + Index: 0.00MB
8g05UKpcVZ_wfhits: Data: 0.05MB + Index: 0.05MB
8g05UKpcVZ_wfhoover: Data: 0.02MB + Index: 0.02MB
8g05UKpcVZ_wfissues: Data: 0.02MB + Index: 0.06MB
8g05UKpcVZ_wfknownfilelist: Data: 1.52MB + Index: 0.00MB
8g05UKpcVZ_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB
8g05UKpcVZ_wflocs: Data: 0.02MB + Index: 0.00MB
8g05UKpcVZ_wflogins: Data: 0.08MB + Index: 0.03MB
8g05UKpcVZ_wfnotifications: Data: 0.02MB + Index: 0.00MB
8g05UKpcVZ_wfpendingissues: Data: 0.02MB + Index: 0.06MB
8g05UKpcVZ_wfreversecache: Data: 0.02MB + Index: 0.00MB
8g05UKpcVZ_wfsnipcache: Data: 0.02MB + Index: 0.05MB
8g05UKpcVZ_wfstatus: Data: 0.13MB + Index: 0.09MB
8g05UKpcVZ_wftrafficrates: Data: 0.02MB + Index: 0.00MB
8g05UKpcVZ_wpml_mails: Data: 0.02MB + Index: 0.00MB
8g05UKpcVZ_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB
8g05UKpcVZ_yoast_seo_links: Data: 0.08MB + Index: 0.02MB
8g05UKpcVZ_yoast_seo_meta: Data: 0.09MB + Index: 0.00MB

### Post Type Counts ###

attachment: 233
custom_css: 5
customize_changeset: 21
ign_supplier_notices: 1
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 80
page: 36
post: 3
product: 82
product_variation: 9
revision: 1008
scheduled-action: 17
shop_coupon: 1
shop_order: 114
shop_order_refund: 2
wafs: 4
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (43) ###

A2 Optimized WP: by A2 Hosting – 2.0.10.9.2
amr shortcode any widget: by anmari – 3.7
Autoptimize: by Frank Goossens (futtta) – 2.5.0
Child Theme Configurator: by Lilaea Media – 2.4.4
Classic Editor: by WordPress Contributors – 1.4
Contact Form 7 Honeypot: by Nocean – 1.14
Contact Form 7 MailChimp Extension: by Renzo Johnson – 0.4.51
Contact Form 7: by Takayuki Miyoshi – 5.1.1
EWWW Image Optimizer: by Exactly WWW – 4.7.3
Heartbeat Control: by Jeff Matson – 1.2.5
Homepage Control: by WooThemes – 2.0.3
IgniteWoo Updater: by IgniteWoo.com – 2.1.12
Jetpack by WordPress.com: by Automattic – 7.2.1
Kadence WooCommerce Email Designer: by Kadence Themes – 1.1.9
Rename wp-login.php: by Ella Iseulde Van Dorpe – 2.5.5
Safe SVG: by Daryll Doyle – 1.9.4
Shortcodes Ultimate: by Vladimir Anokhin – 5.3.0
Stop XML-RPC Attack: by alfreddatakillen – 1.0.3
Tidio Chat: by Tidio Ltd. – 3.4.0
WooCommerce Blocks: by Automattic – 2.0.1
WooCommerce Order Test: by WP Fix It – 1.5 – Not tested with the active version of WooCommerce
WooCommerce Advanced Free Shipping: by Jeroen Sormani – 1.1.4 – Not tested with the active version of WooCommerce
WooCommerce Advanced Ajax Layered Navigation: by WooCommerce – 1.4.16
WooCommerce Brands: by WooCommerce – 1.6.8
WooCommerce Dropshipping Suppliers Pro: by IgniteWoo.com – 2.2.3 – Not tested with the active version of WooCommerce
WooCommerce Amazon Pay Gateway: by WooCommerce – 1.9.1
WooCommerce Google Ads Conversion Tracking: by Wolf+Bär Agency – 1.5.2
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.9
WooCommerce Product Add-ons: by WooCommerce – 3.0.11
WooCommerce Products Compare: by WooCommerce – 1.0.13 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.19.0 – Not tested with the active version of WooCommerce
WooCommerce Shipment Tracking: by WooCommerce – 1.6.13
WooCommerce FedEx Shipping: by WooCommerce – 3.4.17
WooCommerce Square: by WooCommerce – 1.0.37
WooCommerce: by Automattic – 3.6.2
Wordfence Security: by Wordfence – 7.2.5
Yoast SEO Premium: by Team Yoast – 11.1
WP Extended Search: by 5um17 – 1.2
WP Fastest Cache: by Emre Vona – 0.8.9.2
WP Mail SMTP Plugin by Mail Bank: by Tech Banker – 4.0.6
WP Maintenance Mode: by Designmodo – 2.2.3
WP Original Media Path: by studio RVOLA – 2.4.0
Yoast SEO: WooCommerce: by Team Yoast – 11.1 – Not tested with the active version of WooCommerce

### Inactive Plugins (8) ###

A2 Fixed W3 Total Cache: by  – 0.9.4.6.4.4
Customer Reviews for WooCommerce: by ivole – 3.69
Google Ads for WooCommerce: by Kliken – 1.0.1 – Not tested with the active version of WooCommerce
Mailchimp for WooCommerce: by Mailchimp – 2.1.15 – Not tested with the active version of WooCommerce
Scripts n Styles: by unFocus Projects – 3.5.1
Webcraftic Clearfy – WordPress optimization plugin: by Webcraftic <wordpress.webraftic@gmail.com> – 1.5.3
WP Rollback: by Impress.org – 1.6
Yoast SEO: Search index purge: by Team Yoast – 1.1.0

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #150 - /products/
Cart: #151 - /cart/
Checkout: #152 - /checkout/
My account: #153 - /my-account/
Terms and conditions: #284 - /terms-of-service/

### Theme ###

Name: Storefront Child Slider
Version: – 0 is available
Author URL: https://woocommerce.com/
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.4.6
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Store Catalog PDF Download ###

Template Overrides: 

### Action Scheduler ###

Complete: 16
Oldest: 2019-04-18 12:55:53 -0500
Newest: 2019-04-25 12:56:54 -0500

Pending: 1
Oldest: 2019-05-02 12:56:54 -0500
Newest: 2019-05-02 12:56:54 -0500

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by rrennick** [comment]
@miketip you can wrap code that you want to remain in code in back ticks. I edited your description to add them appropriately. Your system status report won't reveal anything about your site if you redact your site URLs.

**Comment by rodrigoprimo** [comment]
I'm afraid I'm not able to respond privately. Only on GitHub. Please see
Ron's comment (
https://github.com/woocommerce/woocommerce/issues/23566#issuecomment-488476827)
for a suggestion on how to deal with your concern about sensitive
information on the system status report.

**Comment by tiagonoronha** [comment]
I tested this Storefront and it seems to work correctly:

<img width="927" alt="Screenshot 2019-05-02 at 15 14 35" src="https://user-images.githubusercontent.com/1177726/57081656-19f44a80-6ced-11e9-8649-1e76b05624e3.png">

I don't think we do any specific modifications to the products galleries, but perhaps test with a different theme to check if this issue applies only to Storefront or not.
