### ISSUE TITLE
Setup Wizard: Flow does not redirect back to Ready page after Jetpack connection

### ISSUE THREAD

**Issue by brbrr** [woocommerce/woocommerce#23560]
**To Reproduce**
1. Create a new site with Woo plugin installed
2. Start a Woo Setup Wizard
3. Go through the wizard and connect Jetpack 
4. Select a free plan
5. See redirect to Jetpack dashboard

**Screenshots**
Video: https://monosnap.com/file/53HxL3oB3d5TIYlO1bJJ9EGzEoqwwM

**Expected behavior**
User should be redirected back to Setup Wizard's Ready page. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by kloon** [comment]
The issue needs to be fixed inside Calypso https://github.com/Automattic/wp-calypso/issues/33257
