### ISSUE TITLE
Product Category Permalink Choice

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/woocommerce#23568]
**Describe the bug**
If you have your permalinks set to `/shop/%product_cat%/` how are you able to choose the category/child category you want WooCommerce to use for the product permalink?

By default it seems it chooses this in alphabetical order based on parent category names, that is until you add a child category. Then it seems to change the product permalink based on the category that comes first in reverse alphabetical order.

1997177-zen 

**To Reproduce**
1. Go to a product and add it into two or more parent categories, select update.
2. View the current product permalink set to the first category in alphabetical order.
3. Add said product to any other parent category and make sure the product permalink stays in alphabetical order
4. Create or add product to a child category in a parent category that isn't the first in alphabetical order, update the product.
5. Notice the new permalink is now based on the parent-category/child-category in reverse alphabetical order.

**Screenshots**
https://cld.wthms.co/on87Ra

**Expected behavior**
I'm not sure what would be the expected behavior besides it always going with the first parent and child category in alphabetical order. It would also be ideal to have a way to set the primary category you want the product to use.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://beta.local
Site address (URL): https://beta.local
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.2-RC1-45274
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.14.0
PHP Version: 7.2.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.7.23
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 2.65MB
Database Data Size: 1.68MB
Database Index Size: 0.97MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.03MB + Index: 0.05MB
wp_postmeta: Data: 0.08MB + Index: 0.03MB
wp_posts: Data: 0.05MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 17
nav_menu_item: 5
page: 8
post: 2
product: 12
revision: 2
scheduled-action: 10
shop_order: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.6.2

### Inactive Plugins (9) ###

Akismet Anti-Spam: by Automattic – 4.1.1
Jetpack by WordPress.com: by Automattic – 7.2.1
Query Monitor: by John Blackbourn – 3.3.4
WooCommerce Beta Tester: by WooCommerce – 2.0.1 – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.11
WooCommerce Services: by Automattic – 1.19.0 – Not tested with the active version of WooCommerce
WooCommerce Square: by WooCommerce – 1.0.37
WooCommerce Stripe Gateway: by WooCommerce – 4.1.16
WordPress Beta Tester: by Peter Westwood
Andy Fragen – 2.0.4


### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #10 - /shop/
Cart: #11 - /cart/
Checkout: #12 - /checkout/
My account: #13 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.4.6
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 8
Oldest: 2019-04-04 19:24:11 +0000
Newest: 2019-05-01 01:01:19 +0000

Pending: 2
Oldest: 2019-05-08 01:01:19 +0000
Newest: 2019-05-08 01:01:19 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by kloon** [comment]
There is no interface for defining a URL structure for products at present. In 3.6 we introduced functionality that will take the child category and parent and then work back and do a combined URL that will be /shop/parent-cat/child-cat/product-slug

If you have multiple child categories assigned to a product then how are we suppose to know what the preferred category would be to use in the slug? That is why we use the alphabetical route so the urls are at least consistent each time, it would be bad to have a url that changes constantly.

Another thing would be to evaluate how you assign products to categories and even your URL structure. It just does not make sense to have multiple categories assigned to a product and then also want the URL to match that for each selected category, this is bad for SEO, you will get duplicate content errors.

What it sounds like is we need something one can build a URL structure with, which I do not think would be something core should handle, an extension perhaps.
