### ISSUE TITLE
woocommerce_template_single_add_to_cart not working after 3.6.x

### ISSUE THREAD

**Issue by codetipi** [woocommerce/woocommerce#23561]
**Describe the bug**
The `woocommerce_template_single_add_to_cart()` method no longer works inside a standard loop, such as `new WP_Query( array( 'post_type' => 'product' ) );`

**Expected behavior**
The add to cart template to load.

**Versions affected:**
If I revert back to 3.5.8 it works fine again, upgrading to 3.6.x (tested until 3.6.2) makes it stop working again.

Thanks guys.

**Comment by claudiosanches** [comment]
@codetipi may you give a full example of how are you using it?

**Comment by claudiosanches** [comment]
I'm checking here, but there's no recent changes in that function:

![Screenshot from 2019-04-30 17-02-59](https://user-images.githubusercontent.com/1264099/56989869-dae9bc00-6b69-11e9-8fdd-16bb3009f57d.png)

Also no changes with the `single-product/add-to-cart/simple.php`: https://github.com/woocommerce/woocommerce/commits/master/templates/single-product/add-to-cart/simple.php
And it's the same for almost all the other types.

Are you setting the `$product` global?

**Comment by codetipi** [comment]
Hey Claudio,

Thanks for the response - the bug I'm experiencing is happening when called inside a very basic REST API call and the $product global is not touched.

I've added some very few lines of code to a blank TwentyNineteen theme to recreate the issue and I've attached the modified zip here.

To see the issue in action:

1. Please install and activate the modified theme and also have the latest WooCommerce active
2. Go on the site and open any post, you'll see a text link at the top saying: `CLICK TO TEST woocommerce_template_single_add_to_cart()`
3. Click that link and in the console you'll see a message saying "Response => "

Now remove your WooCommerce 3.6.x and install 3.5.8 version, and do the same thing again, this time you'll see this in the console:

`response =>  <form class="cart" action="http://woo.test/product/ball/" method="post" enctype='multipart/form-data'>
				<div class="quantity">
		......`

As you can see v3.6.x seems to have broken the `woocommerce_template_single_add_to_cart()` for some reason.

The code I added is very basic too, if you go to the bottom of the modified `twentynineteen/functions.php`, you'll see 3 methods: 1x enqueue script, 1x rest api routes 1x route callback

Then in `twentynineteen/js/wootest.js` you'll see a very basic event listener to call the REST API when you click the simple test link added in the `twentynineteen/template-part/content/content-single.php`.

Hope this helps.

Chris

[twentynineteen.zip](https://github.com/woocommerce/woocommerce/files/3134551/twentynineteen.zip)

**Comment by claudiosanches** [comment]
Un 3.5.8 and 3.6.2 I'm getting the follow error:

![Screenshot from 2019-05-06 17-11-19](https://user-images.githubusercontent.com/1264099/57252201-fd744d00-7021-11e9-80a7-134615d3cfc7.png)

Seems like there's more things to fix on it first.

**Comment by codetipi** [comment]
That error isn't relevant to what I'm reporting though, the empty response seen in your screenshot below the "response payload" title is what I'm talking about. 

Here is what you get in 3.5.8:

<img width="563" alt="Screenshot 2019-05-08 at 17 21 21" src="https://user-images.githubusercontent.com/22545313/57391147-cfc00d00-71b5-11e9-9d51-ae478c7cba1c.png">

As you can see `woocommerce_template_single_add_to_cart()` does show up in the response in that version.

**Comment by claudiosanches** [comment]
For me is empty on `3.5.8` as well.

**Comment by kloon** [comment]
Your code it wrong, and you are using the wrong function to getting the add to cart markup, the one you are using uses a hook which will not fire in the REST call, you should call the correct functions depending on your product type, also you need to catch the output in a buffer and then return it for a REST API endpoint, see example below for a simple product.

```
function wootest_cb( $request ) {
	$args = array(
		'posts_per_page' => 1,
		'post_type' => 'product',
	);

	$qry = new WP_Query( $args );
	ob_start();
	if ( $qry->have_posts() ) :
		while ( $qry->have_posts() ) :
			$qry->the_post();
			woocommerce_simple_add_to_cart();
		endwhile;
		wp_reset_postdata();
	endif;
	return ob_get_clean();
}
```
