### ISSUE TITLE
Wocommerce Accomodation Bookings Plugin ; last day of a booking not half booked

### ISSUE THREAD

**Issue by FelixAnstdt** [woocommerce/woocommerce#23570]
I have set that you book nights and not days and I also set a time of arrival and a time of departure. The goal should be that after a booking, the arrival and departure day should only be seen as half booked in the calendar (with a red triangle instead of completely filled out) and that these half booked days can still be booked. Thus, for example, a departure day can also be an arrival day and an arrival day can also be a departure day. As you can see on the attached screenshot, this already works for the first day of a booking. But not for the last day of a booking.
I hope you can help me with this. Thanks! 
Here you can find the regarding Website: https://villa-albatros.at/produkt/appartment1

**Comment by laurendavissmith** [comment]
@FelixAnstdt thanks for this report, would you please move this issue over to the accommodation bookings repo so we can triage it correctly, https://github.com/woocommerce/woocommerce-accommodation-bookings/issues thanks!
