### ISSUE TITLE
Nigeria Zip Code Error

### ISSUE THREAD

**Issue by JVNMG** [woocommerce/woocommerce#23573]
Receiving a Payment error: INVALID C_ZIP for an order that is in Nigeria. When they select Nigeria for the country, the zip code field goes away.

1. Go to checkout
2. Select Nigeria as the country, see that the zip code field disappears
3. Complete checkout process
4. INVALID C_ZIP error generates and can't checkout

**Comment by rodrigoprimo** [comment]
I'm not able to reproduce this error on a clean WooCommerce install. I tested both with payment gateways Stripe and Cash on Delivery. Which payment gateway are you using? Could you please provide your system status report as request in the [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=)?

**Comment by JVNMG** [comment]
Sage Payment Solutions

Status Report:

`
### WordPress Environment ###

WordPress address (URL): https://churchconsulting.org
Site address (URL): https://churchconsulting.org
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.17-1+ubuntu18.04.1+deb.sury.org+3
PHP Post Max Size: 100 MB
PHP Time Limit: 0
PHP Max Input Vars: 4000
cURL Version: 7.58.0
OpenSSL/1.1.1b

SUHOSIN Installed: –
MySQL Version: 5.6.43-84.3-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: wp_
Total Database Size: 53.53MB
Database Data Size: 35.43MB
Database Index Size: 18.10MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.08MB + Index: 0.08MB
wp_woocommerce_order_items: Data: 0.06MB + Index: 0.03MB
wp_woocommerce_order_itemmeta: Data: 0.32MB + Index: 0.22MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_cf7dbplugin_st: Data: 0.05MB + Index: 0.00MB
wp_cf7dbplugin_submits: Data: 2.52MB + Index: 0.66MB
wp_commentmeta: Data: 0.06MB + Index: 0.03MB
wp_comments: Data: 0.39MB + Index: 0.36MB
wp_easycontactforms_acl: Data: 0.01MB + Index: 0.00MB
wp_easycontactforms_applicationsettings: Data: 0.00MB + Index: 0.01MB
wp_easycontactforms_contacttypes: Data: 0.00MB + Index: 0.01MB
wp_easycontactforms_customformentryfiles: Data: 0.00MB + Index: 0.01MB
wp_easycontactforms_customformentrystatistics: Data: 0.00MB + Index: 0.00MB
wp_easycontactforms_customformfields: Data: 0.13MB + Index: 0.01MB
wp_easycontactforms_customformfieldtypes: Data: 0.02MB + Index: 0.01MB
wp_easycontactforms_customforms: Data: 0.06MB + Index: 0.01MB
wp_easycontactforms_customformsentries: Data: 0.18MB + Index: 0.01MB
wp_easycontactforms_customforms_mailinglists: Data: 0.00MB + Index: 0.00MB
wp_easycontactforms_files: Data: 0.00MB + Index: 0.01MB
wp_easycontactforms_options: Data: 0.02MB + Index: 0.03MB
wp_easycontactforms_roles: Data: 0.00MB + Index: 0.00MB
wp_easycontactforms_sessions: Data: 0.00MB + Index: 0.00MB
wp_easycontactforms_users: Data: 0.02MB + Index: 0.08MB
wp_imagify_files: Data: 0.02MB + Index: 0.08MB
wp_imagify_folders: Data: 0.02MB + Index: 0.03MB
wp_iwp_backup_status: Data: 0.02MB + Index: 0.00MB
wp_layerslider: Data: 0.00MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 25.14MB + Index: 11.03MB
wp_postmeta: Data: 3.52MB + Index: 4.03MB
wp_posts: Data: 1.52MB + Index: 0.31MB
wp_revslider_css: Data: 0.09MB + Index: 0.01MB
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wp_revslider_settings: Data: 0.00MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.01MB + Index: 0.00MB
wp_revslider_slides: Data: 0.15MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.05MB
wp_term_relationships: Data: 0.01MB + Index: 0.03MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.48MB + Index: 0.50MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wpbdp_fees: Data: 0.00MB + Index: 0.00MB
wp_wpbdp_form_fields: Data: 0.00MB + Index: 0.00MB
wp_wpbdp_listings: Data: 0.02MB + Index: 0.00MB
wp_wpbdp_listing_fees: Data: 0.00MB + Index: 0.00MB
wp_wpbdp_logs: Data: 0.02MB + Index: 0.00MB
wp_wpbdp_payments: Data: 0.00MB + Index: 0.01MB
wp_wpbdp_payments_items: Data: 0.00MB + Index: 0.00MB
wp_wpbdp_plans: Data: 0.02MB + Index: 0.00MB
wp_wpbdp_submit_state: Data: 0.08MB + Index: 0.01MB
wp_wpclone: Data: 0.00MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

acps: 1
attachment: 415
avada_faq: 1
avada_portfolio: 7
iwp_log: 129
nav_menu_item: 115
oembed_cache: 1
options: 37
page: 150
post: 3
product: 23
product_variation: 4
revision: 7
scheduled-action: 20
shop_coupon: 15
shop_order: 523
slide: 3
themefusion_elastic: 2
uwpqsf: 1
wp-help: 1
wpbdp_listing: 47
wpcf7_contact_form: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (19) ###

InfiniteWP - Client: by Revmakx – 1.8.3
Admin Menu Editor Pro: by Janis Elsts – 2.6.4
Akismet Anti-Spam: by Automattic – 4.0.8
Artbees Themes Captcha: by Jose Rodriguez  – 1.0
Business Directory Plugin: by D. Rodenbaugh – 5.3.1
Contact Form DB: by Michael Simpson – 2.10.26
Contact Form 7: by Takayuki Miyoshi – 5.0.3
Duplicate Post: by Enrico Battocchi – 3.2.2
Easy Theme and Plugin Upgrades: by Chris Jean – 2.0.0
Enable Media Replace: by ShortPixel – 3.2.6
Imagify: by WP Media – 1.8.1.1
WPBakery Page Builder (Modified Version): by Michael M - WPBakery.com – 5.4.5.1
PHP Compatibility Checker: by WP Engine – 1.4.6
Slider Revolution: by ThemePunch – 5.4.6.4
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.18
White Label CMS: by www.videousermanuals.com – 1.6.4
WooCommerce Sage Payments USA Gateway: by Add On Enterprises (Andrew Benbow) – 1.0.11 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.6.2
Yoast SEO Premium: by Team Yoast – 8.0

### Inactive Plugins (1) ###

Envato WordPress Toolkit (Deprecated): by Envato – 1.8.0

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (3) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.6.4
Stop long comments: by WPEngine – 0.0.4
WP Engine System: by WP Engine – 3.2.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #4097 - /shop/
Cart: #5693 - /cart-2/
Checkout: #4099 - /checkout/
My account: #4100 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Networld Press
Version: 4.4
Author URL: http://networldmediagroup.com
Child Theme: ✔
Parent Theme Name: Jupiter
Parent Theme Version: 6.0.2
Parent Theme Author URL: http://themeforest.net/user/artbees
WooCommerce Support: ✔

### Templates ###

Overrides: jupiter/woocommerce/archive-product.php version 2.0.0 is out of date. The core version is 3.4.0
jupiter/woocommerce/content-product.php version 3.0.0 is out of date. The core version is 3.6.0
jupiter/woocommerce/content-product_cat.php
jupiter/woocommerce/loop/add-to-cart.php version 3.0.0 is out of date. The core version is 3.3.0
jupiter/woocommerce/loop/loop-end.php
jupiter/woocommerce/loop/loop-start.php version 2.0.0 is out of date. The core version is 3.3.0

Outdated Templates: ❌
					
					
						Learn how to update

### Action Scheduler ###

Complete: 20
Oldest: 2019-04-26 18:11:21 +0000
Newest: 2019-04-26 18:15:44 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by franticpsyx** [comment]
@rodrigoprimo confirmed that when choosing Nigeria, the Post Code field doesn't appear: https://cl.ly/b839f0cdf272

This is probably intended behavior?

**Comment by willgorham** [comment]
The Nigeria postal code field was made non-required and hidden recently: https://github.com/woocommerce/woocommerce/issues/21055.

**Comment by rodrigoprimo** [comment]
Thanks for sharing the system status report, @JVNMG. As Will mentioned, Nigeria postal code field was made non-required and hidden since WooCommerce 3.5.0. This field is not required and hidden for other countries as well. The error you are getting seems like a problem in the payment gateway.

I would suggest you first try updating WooCommerce Sage Payments USA Gateway as you are running an older version to see if they fixed the issue already. If not, please contact the extension author to report the problem (cc @ChromeOrange). If you are a WooCommerce.com paying customer, you can request support for this extension via this link: http://woocommerce.com/contact-us/.

**Comment by ChromeOrange** [comment]
This has been fixed in the latest release of the Paya plugin, version 3.1.6

**Comment by wondarkid** [comment]
> Receiving a Payment error: INVALID C_ZIP for an order that is in Nigeria. When they select Nigeria for the country, the zip code field goes away.
> 
> Steps to reproduce the behavior:
> 
> 1. Go to checkout
> 2. Select Nigeria as the country, see that the zip code field disappears
> 3. Complete checkout process
> 4. INVALID C_ZIP error generates and can't checkout

I have resolved this issue. it took some days but i finally figured out why. i tried building a woocommerce using a free host as it was meant to be a testing site (<a href="https://www.tecteem.com/123movies-watch-movies-online/">MYASLOVE</a>) before i buy a domain. when i select the country Nigeria, the ZIP code area disappeared and i really wanted to make delivery by shipping zones. Like i said, it too me some days but i have resolved the issue. it has to do with a .php file of the woocommerce plugin. In Nigeria zip codes were not really into use and that is the reason it is like that. Please do contact me on my website using the link below for more information. i can help you further.
https://www.tecteem.com/123movies-watch-movies-online/
