### ISSUE TITLE
Basic Auth with SSL not working 

### ISSUE THREAD

**Issue by codetycon** [woocommerce/woocommerce#23575]
My site is running on SSL, the issue is BAsic auth not working with product list API.

When I using this
GET https://www.outreachchimp.com/wc-api/v3/products?consumer_key=mykey&consumer_secret=mysecret

is working fine

But WHen I am using this 
GET https://www.outreachchimp.com/wp-json/wc/v3/products?consumer_key=mykey&consumer_secret=mysecret

Only the difference is  **wc-api** to **wp-json**

Getting this response for second call
{"code":"woocommerce_rest_cannot_view","message":"Sorry, you cannot list resources.","data":{"status":401}}

**Comment by rodrigoprimo** [comment]
I'm sorry but this is not a support forum. We use GitHub issues exclusively for WooCommerce core bug reports. For support, you can try the [WordPress.org support forum](https://wordpress.org/support/plugin/woocommerce/). Alternatively, if you are a paying WooCommerce.com user, you can [contact their support](http://woocommerce.com/contact-us/).
