### ISSUE TITLE
Tax displayed on order details when disabled site-wide

### ISSUE THREAD

**Issue by n-dawson** [woocommerce/woocommerce#23578]
**Describe the bug**
A tax total row ($0) is shown under order details, even when taxes are disabled site-wide, if taxes had previously been enabled and the method of display set to single instead of itemized.

This only applies once an order has been placed and doesn't affect the cart / checkout pages.

Re-enabling taxes, changing the total type, and disabling again resolves the error.

**To Reproduce**
1. Go to WooCommerce -> Settings and check "Enable taxes".
2. Go to the newly visible Tax tab.
3. Change "Display tax totals" from "Itemized" to "As a single total".
4. Return to the General tab and uncheck "Enable taxes".
5. Place a test order and review the totals shown on the order received page.

**Expected behavior**
When taxes are disabled, the tax total row shouldn't be shown anywhere on new orders regardless of the settings that were used while taxes were enabled.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WordPress Core - 5.1.1
WooCommerce - 3.6.2
Theme - TwentyNineteen
Other plugins - all disabled

**Additional Notes**
The totals section for the cart and checkout page call `wc_tax_enabled()` to determine whether to show the row.

The order details on the other hand loop through rows provided by the `get_order_item_totals()` method of the order class. That in turn builds an array and one of the methods used is `add_order_item_totals_tax_rows()` (ln 1849 of abstract-wc-order.php)

```
/**
 * Add total row for taxes.
 *
 * @param array  $total_rows Reference to total rows array.
 * @param string $tax_display Excl or incl tax display mode.
 */
protected function add_order_item_totals_tax_rows( &$total_rows, $tax_display ) {
    // Tax for tax exclusive prices.
    if ( 'excl' === $tax_display ) {
        if ( 'itemized' === get_option( 'woocommerce_tax_total_display' ) ) {
            foreach ( $this->get_tax_totals() as $code => $tax ) {
                $total_rows[ sanitize_title( $code ) ] = array(
                    'label' => $tax->label . ':',
                    'value' => $tax->formatted_amount,
                );
            }
        } else {
            $total_rows['tax'] = array(
                'label' => WC()->countries->tax_or_vat() . ':',
                'value' => wc_price( $this->get_total_tax(), array( 'currency' => $this->get_currency() ) ),
            );
        }
    }
}
```

This method doesn't check whether taxes are enabled first. If they're disabled but the setting is still the default of itemized, nothing will be displayed because `$this->get_tax_totals()` will be empty. If the user has changed the total type however, the else statement is hit resulting in the row erroneously being shown.

**Comment by claudiosanches** [comment]
Thanks for your help!

**Comment by claudiosanches** [comment]
See #23579
