### ISSUE TITLE
Tax based on shop address gets automatically changed to customer address

### ISSUE THREAD

**Issue by DanceNomads** [woocommerce/woocommerce#23577]
We have some issues with setting up the tax on our shop. We want the tax to be based on our shop address. As soon as we change it to that and save the changes, it automatically changes back to based on customer address. 

Also, we want to always show prices included VAT (we ticked that box).  For some reason, some people now see the wrong prizes. For example:
1. A lady shirt is 27 euros in the shop 
2. The person clicks on the product and then it shows 21,51 euros
3. In the checkout it shows 21,51 euros + 5,49 VAT. But we don't want people to see the price excl vat. 

<img width="1406" alt="Screenshot 2019-05-01 at 21 42 12" src="https://user-images.githubusercontent.com/50182687/57038442-2ed3ce00-6c5a-11e9-8c82-1bcc768d0c4e.png">

![WhatsApp Image 2019-05-01 at 21 53 40 jpeg1](https://user-images.githubusercontent.com/50182687/57039053-e4535100-6c5b-11e9-850b-f4ee0278cc6c.jpeg)
![WhatsApp Image 2019-05-01 at 21 53 40](https://user-images.githubusercontent.com/50182687/57039056-e4ebe780-6c5b-11e9-815a-621d2368b413.jpeg)
![WhatsApp Image 2019-05-01 at 21 53 41](https://user-images.githubusercontent.com/50182687/57039058-e4ebe780-6c5b-11e9-8f54-2bfd9f0d5254.jpeg)

**Expected behavior**
We want the prices on the shop to always show including taxes and we want the tax to be based on our shipping address

**Isolating the problem (mark completed items with an [x]):**
- [X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
`
### WordPress Environment ###

WordPress address (URL): https://dancenomads.net
Site address (URL): https://dancenomads.net
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.13
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.12-MariaDB-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 36.67MB
Database Data Size: 31.63MB
Database Index Size: 5.04MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.01MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.24MB + Index: 0.03MB
wp_comments: Data: 0.85MB + Index: 0.70MB
wp_csshero3: Data: 0.01MB + Index: 0.00MB
wp_et_bloom_stats: Data: 0.85MB + Index: 0.14MB
wp_et_divi_ab_testing_clients: Data: 0.00MB + Index: 0.00MB
wp_et_divi_ab_testing_stats: Data: 0.00MB + Index: 0.00MB
wp_et_social_stats: Data: 0.00MB + Index: 0.00MB
wp_failed_jobs: Data: 0.00MB + Index: 0.00MB
wp_gglcptch_whitelist: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_loginizer_logs: Data: 0.04MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 1.71MB + Index: 0.24MB
wp_postmeta: Data: 4.80MB + Index: 1.56MB
wp_posts: Data: 21.13MB + Index: 0.57MB
wp_queue: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.01MB + Index: 0.02MB
wp_terms: Data: 0.01MB + Index: 0.02MB
wp_term_relationships: Data: 0.08MB + Index: 0.18MB
wp_term_taxonomy: Data: 0.01MB + Index: 0.01MB
wp_usermeta: Data: 1.21MB + Index: 1.02MB
wp_users: Data: 0.35MB + Index: 0.25MB
wp_wcpdf_invoice_number: Data: 0.00MB + Index: 0.00MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_product_meta_lookup: Data: 0.03MB + Index: 0.07MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_woof_query_cache: Data: 0.00MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.05MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.15MB + Index: 0.16MB

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 855
custom_css: 3
customize_changeset: 1
et_pb_layout: 11
et_pb_layout_stashed: 8
jetpack_migration: 2
layout: 3
nav_menu_item: 25
page: 16
post: 17
product: 105
product_variation: 715
project: 10
revision: 703
scheduled-action: 124
shop_coupon: 10
shop_order: 12

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

Bloom: by Elegant Themes – 1.3.10
Cookie Notice: by dFactory – 1.2.46
Divi Builder: by Elegant Themes – 2.22.6
Facebook for WooCommerce: by Facebook – 1.9.11 – Not tested with the active version of WooCommerce
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 5.3.8
Google Captcha (reCAPTCHA) by BestWebSoft: by BestWebSoft – 1.43
Loginizer: by Raj Kothari – 1.4.1
Mailchimp for WooCommerce: by Mailchimp – 2.1.15 – Not tested with the active version of WooCommerce
Printful Integration for WooCommerce: by Printful – 2.1.1
Safe SVG: by Daryll Doyle – 1.9.4
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.20
Themify - WooCommerce Product Filter: by Themify – 1.1.9
WooCommerce Blocks: by Automattic – 2.0.1
Product Variation Swatches for WooCommerce: by Emran Ahmed – 1.0.56
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.11
WooCommerce Stripe Gateway: by WooCommerce – 4.1.16
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.2.12
WooCommerce: by Automattic – 3.6.2
Yoast SEO: by Team Yoast – 11.1 – Not tested with the active version of WooCommerce
YITH WooCommerce Ajax Product Filter: by YITH – 3.6.3

### Inactive Plugins (3) ###

UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.14

W3 Total Cache: by Frederick Townes – 0.9.7.3
WP Staging: by WP-Staging – 2.5.5

### Must Use Plugins (1) ###

ET Support Center :: Must-Use Plugins Autoloader: by Elegant Themes –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #26608 - /shop/
Basket: #26609 - /basket/
Checkout: #26610 - /checkout/
My account: #26611 - /my-account/
Terms and conditions: #26779 - /terms-and-conditions/

### Theme ###

Name: Divi Child Theme Dance Nomads
Version: 1.0.0
Author URL: https://dancenomads.net
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.22.6
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 122
Oldest: 2019-04-01 11:43:34 +0000
Newest: 2019-04-27 09:13:23 +0000

Pending: 2
Oldest: 2019-05-03 11:54:48 +0000
Newest: 2019-05-03 11:54:48 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by rodrigoprimo** [comment]
I'm sorry but this is not a support forum. We use GitHub issues exclusively for WooCommerce core bug reports. For support, you can try the WordPress.org support forum. Alternatively, if you are a paying WooCommerce.com user, you can contact their support.
