### ISSUE TITLE
No hook for adjusting stock change behavior when adding item to order via backend

### ISSUE THREAD

**Issue by tldawson** [woocommerce/woocommerce#23582]
**Issue**

When adding an item to an order in the backend, there is no way to modify the new stock-changing behavior introduced by #22329.  
For example, if an order had a custom status like `quote` I might not want to change stock until the customer approves the quote (and we change the order's status to `pending`).  

**Proposal**

Create a hook that grabs the `$order` or `$order_id` before function calls to `wc_maybe_adjust_line_item_product_stock()` in `wc_save_order_items()`, in the file `woocommerce/includes/admin/wc-admin-functions.php`.  

**Alternate proposal**

Add `$order` or `$order_id` to the list of parameters in the `wc_maybe_adjust_line_item_product_stock()` function definition, and then create a hook at the top of the function.

**Comment by LeonWesten** [comment]
Who can help me how to solve these problem?

**Comment by LeonWesten** [comment]
Is there already a solution to solve these problems?

**Comment by flyingeyefr** [comment]
My Woocommerce store is also used to create quotations so this new behavior is a NOGO for us. 

Before fallback to 3.5.7 I also noticed the change of stock when you create a new order in the backoffice ("Add order") is not canceled if we don't save the new order so the inventory is completely desynchronized. 

The previous behavior was good I don't understand why changing it in 3.6 without any parameter to keep it unchanged!

**Comment by LeonWesten** [comment]
> My Woocommerce store is also used to create quotations so this new behavior is a NOGO for us.
> 
> Before fallback to 3.5.7 I also noticed the change of stock when you create a new order in the backoffice ("Add order") is not canceled if we don't save the new order so the inventory is completely desynchronized.
> 
> The previous behavior was good I don't understand why changing it in 3.6 without any parameter to keep it unchanged!

I'm in process with someone from https://codeable.io who can fix this with costum code added in the functions.php. Maybe today its finally solved.

**Comment by flyingeyefr** [comment]
> > My Woocommerce store is also used to create quotations so this new behavior is a NOGO for us.
> > Before fallback to 3.5.7 I also noticed the change of stock when you create a new order in the backoffice ("Add order") is not canceled if we don't save the new order so the inventory is completely desynchronized.
> > The previous behavior was good I don't understand why changing it in 3.6 without any parameter to keep it unchanged!
> 
> I'm in process with someone from https://codeable.io who can fix this with costum code added in the functions.php. Maybe today its finally solved.

Hi LeonWesten, any news about the custom code? thank you

**Comment by LeonWesten** [comment]
Yes Sure, can you send me the slug of your costum order status? 

> > > My Woocommerce store is also used to create quotations so this new behavior is a NOGO for us.
> > > Before fallback to 3.5.7 I also noticed the change of stock when you create a new order in the backoffice ("Add order") is not canceled if we don't save the new order so the inventory is completely desynchronized.
> > > The previous behavior was good I don't understand why changing it in 3.6 without any parameter to keep it unchanged!
> > 
> > 
> > I'm in process with someone from https://codeable.io who can fix this with costum code added in the functions.php. Maybe today its finally solved.
> 
> Hi LeonWesten, any news about the custom code? thank you

**Comment by flyingeyefr** [comment]
> Yes Sure, can you send me the slug of your costum order status?
> 
> > > > My Woocommerce store is also used to create quotations so this new behavior is a NOGO for us.
> > > > Before fallback to 3.5.7 I also noticed the change of stock when you create a new order in the backoffice ("Add order") is not canceled if we don't save the new order so the inventory is completely desynchronized.
> > > > The previous behavior was good I don't understand why changing it in 3.6 without any parameter to keep it unchanged!
> > > 
> > > 
> > > I'm in process with someone from https://codeable.io who can fix this with costum code added in the functions.php. Maybe today its finally solved.
> > 
> > 
> > Hi LeonWesten, any news about the custom code? thank you

slug: quotation-manual
Thanks!

**Comment by flyingeyefr** [comment]
> Yes Sure, can you send me the slug of your costum order status?
> 
> > > > My Woocommerce store is also used to create quotations so this new behavior is a NOGO for us.
> > > > Before fallback to 3.5.7 I also noticed the change of stock when you create a new order in the backoffice ("Add order") is not canceled if we don't save the new order so the inventory is completely desynchronized.
> > > > The previous behavior was good I don't understand why changing it in 3.6 without any parameter to keep it unchanged!
> > > 
> > > 
> > > I'm in process with someone from https://codeable.io who can fix this with costum code added in the functions.php. Maybe today its finally solved.
> > 
> > 
> > Hi LeonWesten, any news about the custom code? thank you

Hi do you have the custom code? Thanks!

**Comment by LeonWesten** [comment]
> > Yes Sure, can you send me the slug of your costum order status?
> > > > > My Woocommerce store is also used to create quotations so this new behavior is a NOGO for us.
> > > > > Before fallback to 3.5.7 I also noticed the change of stock when you create a new order in the backoffice ("Add order") is not canceled if we don't save the new order so the inventory is completely desynchronized.
> > > > > The previous behavior was good I don't understand why changing it in 3.6 without any parameter to keep it unchanged!
> > > > 
> > > > 
> > > > I'm in process with someone from https://codeable.io who can fix this with costum code added in the functions.php. Maybe today its finally solved.
> > > 
> > > 
> > > Hi LeonWesten, any news about the custom code? thank you
> 
> Hi do you have the custom code? Thanks!

Add this code to your functions.php

```
add_filter( 'woocommerce_product_get_manage_stock', 'wcs_do_not_reduce_orderproposal_stock', 10);
function wcs_do_not_reduce_orderproposal_stock( $value ){
    if( is_admin() && isset($_REQUEST['order_id'])  ) {
        $order = new WC_Order( intval( $_REQUEST['order_id'] ) ); 
        if ($order->has_status( 'quotation-manual' ) || $order->has_status( 'pending' ) || $order->get_status()=='auto-draft' ) return false;
    }
    return $value ;
}
```

Hope this works for you.

**Comment by tldawson** [comment]
@LeonWesten  That worked like a charm! +1

**Comment by flyingeyefr** [comment]
@LeonWesten Thank you, that's working perfectly!

**Comment by claudiosanches** [comment]
Thank you for suggesting this feature!

I'm closing the issue as it already has a PR, please continue the discussion over at #24279.

**Comment by flyingeyefr** [comment]
Hello, it seems the custom code is not working anymore. 
As soon as I add items in a new order with 'quotation' custom status, the stock is decreased each time I hit the Update button.
Please advise.

![2020-12-10_235828](https://user-images.githubusercontent.com/50369066/101839997-a1e63b80-3b43-11eb-8e50-f01f45de2746.jpg)
