### ISSUE TITLE
Undefined offset: 0 wc-term-functions.php filter  wc_change_get_terms_defaults

### ISSUE THREAD

**Issue by danyj** [woocommerce/woocommerce#23583]
This filter is trowing an error since 3.6.0 

https://github.com/woocommerce/woocommerce/blob/master/includes/wc-term-functions.php#L47

`Notice: Undefined offset: 0 in T:\wamp64\www\Development\Pro\wp-content\plugins\woocommerce\includes\wc-term-functions.php on line 26`

You might want to check for the index or if array is empty and not  `is_array`. 
Or even better use it on WC pages only because this is now in all WP pages/post types  edit . 

We are using Unyson multi-select option here 
https://github.com/Themezly/Creatus/blob/master/inc/thzframework/theme/options/posts/page_options.php#L29

http://prntscr.com/njasx9

**Comment by claudiosanches** [comment]
Thanks for reporting it.
See #23611
