### ISSUE TITLE
Price Widget excludes category when combined with a product attribute

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#23589]
**Describe the bug**
When using the Filter by Price widget it displays the price range for the current selection. When we use it on a category page it shows the price range of all the products in that category. When we filter for a specific attribute it show the price range of all the products with the selected attribute. However what it doesn't do is show the price range of both the category and a selected attribute.

**To Reproduce**
1. Create two categories, ex: "original, replica"
2. Create an attribute with at least two options, ex: colour = blue, red
3. Create some products with extreme price differences and assign them to different categories / attributes. Originals with a very high prices and replicas with a low price. Ex: original, blue = 1000 & replica, blue = 10
4. If we filter for just the category or just attribute the price range is shown correctly. However if we filter for both the category and the attribute the price range shows all products for the selected attribute and ignores the category

**Screenshots**

Filtering the product category:
![image](https://user-images.githubusercontent.com/11388669/57070975-f7543880-6cd0-11e9-8c69-fb61f78470f7.png)

Filtering the product attribute:
![image](https://user-images.githubusercontent.com/11388669/57071159-7e091580-6cd1-11e9-988a-c06a3c5d9f7a.png)

Filtering both the category and the product attribute:
![image](https://user-images.githubusercontent.com/11388669/57071295-e35d0680-6cd1-11e9-823d-e6a7a27685ca.png)

**Expected behavior**
When filtering both the category and the product attribute I'd expect the price range to reflect only those products which are part of the result. So in the example I'd expect the price range to be €10 - €20

I had a look at the code and it seems the following section would be adding the category: https://github.com/woocommerce/woocommerce/blob/3.6.2/includes/widgets/class-wc-widget-price-filter.php#L154-L160

I monitored the tax query and in the scenario where only the category is filtered `$args['taxonomy']` is set to the product category. But in the scenario where we filter both category and attribute `$args['taxonomy']` is set to the attribute. The attribute is already added in the tax query so it gets added twice. Should the category be retrieved from `$args['product_cat']` instead?
I tried changing the code to something like this and that seem to return the correct result:

```
$tax_query[] = array(
	'taxonomy' => 'product_cat',
	'terms'    => array( $args['product_cat'] ),
	'field'    => 'slug',
);
```

Is there any other scenario's where that might not return the correct results?

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

```
WordPress 5.1.1
WooCommerce 3.6.2
Storefront 2.4.6
```
</details>

**Comment by kloon** [comment]
See #23720 for fix
