### ISSUE TITLE
Shortcodes no longer work as expected when used in custom REST endpoints.

### ISSUE THREAD

**Issue by styledev** [woocommerce/woocommerce#23584]
**Describe the bug**
Since version 3.6 when returning shortcodes inside of a custom REST endpoint all hooks are ignored and only shell HTML is returned. Use Case: Loading a product via AJAX into a modal. This behavior is a result of the addition of `! $this->is_rest_api_request()` to `is_request( $type )` when calling "case 'frontend'".

**To Reproduce**
1. Create a new "register_rest_route"
2. In the callback return: `return rest_ensure_response(array('code' => do_shortcode("[product_page id=<insert product id>]")));`
3. Go to your custom endpoint URL
4. See empty shell returned.

**Screenshots**
**Example of Error:** 
![wc-3-6-wrong-output](https://user-images.githubusercontent.com/12783/57054055-fc6ca580-6c46-11e9-9f78-9095d2d092a5.png)

**Example of Expected Behavior:** 
![wc-3-6-expected-output](https://user-images.githubusercontent.com/12783/57054060-01c9f000-6c47-11e9-8f7d-d6a30ca84887.png)

**Expected behavior**
The expected behavior is that all hooks that are registered with WooCommerce are fired when running a shortcode regardless if it is being run inside of a REST endpoint.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

WordPress address (URL): http://brainyactzescaperooms.test/wp
Site address (URL): http://brainyactzescaperooms.test
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.37 (Unix) OpenSSL/1.0.2q PHP/7.2.13
PHP Version: 7.2.13
PHP Post Max Size: 64 MB
PHP Time Limit: 1800
PHP Max Input Vars: 1000
cURL Version: 7.63.0
OpenSSL/1.0.2q

SUHOSIN Installed: –
MySQL Version: 8.0.12
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 16.86MB
Database Data Size: 14.95MB
Database Index Size: 1.91MB
wp_woocommerce_sessions: Data: 0.39MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_codes: Data: 0.36MB + Index: 0.25MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB
wp_gf_form: Data: 0.02MB + Index: 0.00MB
wp_gf_form_meta: Data: 0.05MB + Index: 0.00MB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 12.41MB + Index: 0.05MB
wp_postmeta: Data: 0.30MB + Index: 0.22MB
wp_posts: Data: 0.52MB + Index: 0.06MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

acf-field: 132
acf-field-group: 9
activity: 5
attachment: 35
bookable_resource: 9
escape_room: 10
location: 6
nav_menu_item: 15
page: 19
post: 24
product: 5
revision: 58
scheduled-action: 45
shop_order: 6
wc_booking: 29

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.7.13
WooCommerce: by Automattic – 3.6.2

### Inactive Plugins (1) ###

WooCommerce Bookings: by WooCommerce – 1.14.0

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #506 - /shop/
Cart: #507 - /cart/
Checkout: #508 - /checkout/
My account: #509 - /my-account/
Terms and conditions: #510 - /terms-conditions/

### Theme ###

Name: Brainy Actz
Version: 1.0
Author URL: http://parapxl.com/
Child Theme: ✔
Parent Theme Name: PXL Framework
Parent Theme Version: 4.3.0
Parent Theme Author URL: http://parapxl.com/
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 44
Oldest: 2019-04-29 12:53:35 -0700
Newest: 2019-05-01 18:45:50 -0700

Pending: 1
Oldest: 2019-05-08 15:59:30 -0700
Newest: 2019-05-08 15:59:30 -0700

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –
```
</details>

**Comment by claudiosanches** [comment]
This change is intentional to avoid REST API loading inside frontend (see https://github.com/woocommerce/woocommerce/issues/20937), you can override it for you endpoint using `woocommerce_is_rest_api_request` filter.

Example:

```php
add_filter( 'woocommerce_is_rest_api_request', function( $is_rest_api_request ) {
    if ( empty( $_SERVER['REQUEST_URI'] ) ) {
        return false;
    }

    $rest_prefix = 'your/endpoint/namespace';
    return ( false !== strpos( $_SERVER['REQUEST_URI'], $rest_prefix ) );
} );
```

**Comment by styledev** [comment]
@claudiosanches Actually, you are right to point out that filter but is_request( 'frontend' ) is fired once before the theme is initialized (on line 432 of class-woocommerce.php inside of function includes() ) and the filter you recommend is only usable on the the second time it is fired on line 529 in the same file inside of function init(). Thus you can't bypass this via a theme.

**Comment by jonathan-dejong** [comment]
I finally found this too after some extensive debugging as to why our custom filter plugin didn't properly render the resulting products anymore. 

For anyone else looking for how to solve this here's basically how I did it. This properly only affects my own endpoint and tells WC it's not a REST request (thus loading all the templates and hooks I need).

```
add_filter( 'woocommerce_is_rest_api_request', [ $this, 'simulate_as_not_rest' ] );
	/**
	 * We have to tell WC that this should not be handled as a REST request.
	 * Otherwise we can't use the product loop template contents properly.
	 * Since WooCommerce 3.6
	 *
	 * @param bool $is_rest_api_request
	 * @return bool
	 */
	public function simulate_as_not_rest( $is_rest_api_request ) {
		if ( empty( $_SERVER['REQUEST_URI'] ) ) {
				return $is_rest_api_request;
		}

		// Bail early if this is not our request.
		if ( false === strpos( $_SERVER['REQUEST_URI'], $this->namespace ) ) {
			return $is_rest_api_request;
		}

		return false;
	}
```

This is in the context of a class with a property of my namespace for the REST calls.

**Comment by hybridwebdev** [comment]
Recently got hit by this issue myself. WC really needs to start taking more care when it comes to making breaking changes like this. Seems like with every update, they are doing this which, frankly, is absolute shit. The solution proposed here works somewhat, but needs to be modified slightly.

**Comment by claudiosanches** [comment]
Example from @jonathan-dejong is correct, and should fix this issue.

**Comment by lostpebble** [comment]
No matter what I do, I can't seem to get this filter to execute. Can you please provide a little more context on how we can use it?

EDIT:

For anyone who maybe has the same problem and lands here, I managed to get the filter to execute by putting it right at the top of my plugin's code, in the same file where you set the version etc (the entry file). For some reason it wasn't being executed inside the class that controls my plugin's main code stuff.

My deepest hope is that WooCommerce considers us Rest API developers in future changes.. this has caused massive headaches and it all feels very fickle. Accessing the WooCommerce Cart in a custom Rest API is needed for so many types of external plugin integrations, such as shipping calculation plugins (what I develop). Please consider this in the future.
