### ISSUE TITLE
I am unable to search my products on woocomerce admin dashboard

### ISSUE THREAD

**Issue by tigerify** [woocommerce/woocommerce#23588]
On my woocomerce dashboard of wordpress......In all products page,woocomerce is not displaying proper search results of products.........I am trying to search my products,but results are not shown

**Comment by tigerify** [comment]
Its not giving exact search results for all products

**Comment by kloon** [comment]
It would help if you provided your system status report and fill in the template that was presented when you opened up the issue, if we do not have these we are pretty much in the dark.

Also what is your products names and what is the search term you are entering? When I run tests and do searches I get relevant results

![](https://cld.wthms.co/jm2ArF+)
![](https://cld.wthms.co/OruV4M+)

I am closing this issue as I am unable to replicate and it is missing quite a lot of information and testing on your part to rule out plugin/theme conflicts. Will gladly reopen if you can provide details on how to replicate this on a clean install.

**Comment by tigerify** [comment]
Please wait, don't close it
