### ISSUE TITLE
504 Gateway Timeout Caused By Something Connected to WooCommerce

### ISSUE THREAD

**Issue by im4everhappi** [woocommerce/woocommerce#23595]
**Describe the bug**
Whenever a customer is signed in and adds to cart there is an issue.  It was timing out every time.

Here are the notices: 
Notice: length was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Form_Handler::add_to_cart_action, WC_Form_Handler::add_to_cart_handler_variable, WC_Cart->add_to_cart, do_action('woocommerce_add_to_cart'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Cart->calculate_totals, WC_Cart_Totals->__construct, WC_Cart_Totals->calculate, WC_Cart_Totals->calculate_shipping_totals, WC_Cart_Totals->get_shipping_from_cart, WC_Cart->calculate_shipping, WC_Shipping->calculate_shipping, WC_Shipping->calculate_shipping_for_package, WC_Shipping_Method->get_rates_for_package, USPS_Simple_Shipping_Method->calculate_shipping, USPS_Simple_Shipping_Method->getRequestsArr, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong Please see /var/www/html/wp-includes/functions.php on line 4667

Notice: width was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Form_Handler::add_to_cart_action, WC_Form_Handler::add_to_cart_handler_variable, WC_Cart->add_to_cart, do_action('woocommerce_add_to_cart'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Cart->calculate_totals, WC_Cart_Totals->__construct, WC_Cart_Totals->calculate, WC_Cart_Totals->calculate_shipping_totals, WC_Cart_Totals->get_shipping_from_cart, WC_Cart->calculate_shipping, WC_Shipping->calculate_shipping, WC_Shipping->calculate_shipping_for_package, WC_Shipping_Method->get_rates_for_package, USPS_Simple_Shipping_Method->calculate_shipping, USPS_Simple_Shipping_Method->getRequestsArr, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong Please see /var/www/html/wp-includes/functions.php on line 4667

Notice: length was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Form_Handler::add_to_cart_action, WC_Form_Handler::add_to_cart_handler_variable, WC_Cart->add_to_cart, do_action('woocommerce_add_to_cart'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Cart->calculate_totals, WC_Cart_Totals->__construct, WC_Cart_Totals->calculate, WC_Cart_Totals->calculate_shipping_totals, WC_Cart_Totals->get_shipping_from_cart, WC_Cart->calculate_shipping, WC_Shipping->calculate_shipping, WC_Shipping->calculate_shipping_for_package, WC_Shipping_Method->get_rates_for_package, USPS_Simple_Shipping_Method->calculate_shipping, USPS_Simple_Shipping_Method->getRequestsArr, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong Please see /var/www/html/wp-includes/functions.php on line 4667

Notice: width was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Form_Handler::add_to_cart_action, WC_Form_Handler::add_to_cart_handler_variable, WC_Cart->add_to_cart, do_action('woocommerce_add_to_cart'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Cart->calculate_totals, WC_Cart_Totals->__construct, WC_Cart_Totals->calculate, WC_Cart_Totals->calculate_shipping_totals, WC_Cart_Totals->get_shipping_from_cart, WC_Cart->calculate_shipping, WC_Shipping->calculate_shipping, WC_Shipping->calculate_shipping_for_package, WC_Shipping_Method->get_rates_for_package, USPS_Simple_Shipping_Method->calculate_shipping, USPS_Simple_Shipping_Method->getRequestsArr, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong Please see /var/www/html/wp-includes/functions.php on line 4667

Notice: length was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Form_Handler::add_to_cart_action, WC_Form_Handler::add_to_cart_handler_variable, WC_Cart->add_to_cart, do_action('woocommerce_add_to_cart'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Cart->calculate_totals, WC_Cart_Totals->__construct, WC_Cart_Totals->calculate, WC_Cart_Totals->calculate_shipping_totals, WC_Cart_Totals->get_shipping_from_cart, WC_Cart->calculate_shipping, WC_Shipping->calculate_shipping, WC_Shipping->calculate_shipping_for_package, WC_Shipping_Method->get_rates_for_package, USPS_Simple_Shipping_Method->calculate_shipping, USPS_Simple_Shipping_Method->getRequestsArr, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong Please see /var/www/html/wp-includes/functions.php on line 4667

Notice: width was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Form_Handler::add_to_cart_action, WC_Form_Handler::add_to_cart_handler_variable, WC_Cart->add_to_cart, do_action('woocommerce_add_to_cart'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Cart->calculate_totals, WC_Cart_Totals->__construct, WC_Cart_Totals->calculate, WC_Cart_Totals->calculate_shipping_totals, WC_Cart_Totals->get_shipping_from_cart, WC_Cart->calculate_shipping, WC_Shipping->calculate_shipping, WC_Shipping->calculate_shipping_for_package, WC_Shipping_Method->get_rates_for_package, USPS_Simple_Shipping_Method->calculate_shipping, USPS_Simple_Shipping_Method->getRequestsArr, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong Please see /var/www/html/wp-includes/functions.php on line 4667

Notice: length was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Form_Handler::add_to_cart_action, WC_Form_Handler::add_to_cart_handler_variable, WC_Cart->add_to_cart, do_action('woocommerce_add_to_cart'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Cart->calculate_totals, WC_Cart_Totals->__construct, WC_Cart_Totals->calculate, WC_Cart_Totals->calculate_shipping_totals, WC_Cart_Totals->get_shipping_from_cart, WC_Cart->calculate_shipping, WC_Shipping->calculate_shipping, WC_Shipping->calculate_shipping_for_package, WC_Shipping_Method->get_rates_for_package, USPS_Simple_Shipping_Method->calculate_shipping, USPS_Simple_Shipping_Method->getRequestsArr, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong Please see /var/www/html/wp-includes/functions.php on line 4667

Notice: width was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Form_Handler::add_to_cart_action, WC_Form_Handler::add_to_cart_handler_variable, WC_Cart->add_to_cart, do_action('woocommerce_add_to_cart'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Cart->calculate_totals, WC_Cart_Totals->__construct, WC_Cart_Totals->calculate, WC_Cart_Totals->calculate_shipping_totals, WC_Cart_Totals->get_shipping_from_cart, WC_Cart->calculate_shipping, WC_Shipping->calculate_shipping, WC_Shipping->calculate_shipping_for_package, WC_Shipping_Method->get_rates_for_package, USPS_Simple_Shipping_Method->calculate_shipping, USPS_Simple_Shipping_Method->getRequestsArr, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong Please see /var/www/html/wp-includes/functions.php on line 4667

Notice: woocommerce_recently_viewed cookie cannot be set - headers already sent by /var/www/html/wp-includes/functions.php on line 4667 in /var/www/html/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 887

**To Reproduce**
1. Go to ordercart.ohmpharma.com.
2. Click on login.
3. Enter Catalog.
4. Add to cart.
5. See Error.

**Screenshots**

**Expected behavior**
It should add the item to cart so that the customer can continue to shop.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
`
### WordPress Environment ###

WordPress address (URL): https://ordercart.ohmpharma.com
Site address (URL): https://ordercart.ohmpharma.com
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.27-1+ubuntu16.04.1+deb.sury.org+1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 600 MB
PHP Time Limit: 600
PHP Max Input Vars: 2000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.25-0ubuntu0.16.04.2
Max Upload Size: 500 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: k3ehg8bl8k
Total Database Size: 5553.96MB
Database Data Size: 4498.81MB
Database Index Size: 1055.15MB
k3ehg8bl8kwoocommerce_sessions: Data: 4.42MB + Index: 0.19MB
k3ehg8bl8kwoocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
k3ehg8bl8kwoocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
k3ehg8bl8kwoocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
k3ehg8bl8kwoocommerce_order_items: Data: 16.86MB + Index: 7.35MB
k3ehg8bl8kwoocommerce_order_itemmeta: Data: 1130.95MB + Index: 76.40MB
k3ehg8bl8kwoocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
k3ehg8bl8kwoocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
k3ehg8bl8kwoocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
k3ehg8bl8kwoocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
k3ehg8bl8kwoocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
k3ehg8bl8kwoocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
k3ehg8bl8kwoocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
k3ehg8bl8kwoocommerce_log: Data: 0.00MB + Index: 0.00MB
k3ehg8bl8kcommentmeta: Data: 0.30MB + Index: 0.30MB
k3ehg8bl8kcomments: Data: 18.55MB + Index: 17.09MB
k3ehg8bl8kduplicator_packages: Data: 0.02MB + Index: 0.02MB
k3ehg8bl8kgive_commentmeta: Data: 0.02MB + Index: 0.03MB
k3ehg8bl8kgive_comments: Data: 0.02MB + Index: 0.00MB
k3ehg8bl8kgive_donationmeta: Data: 0.02MB + Index: 0.03MB
k3ehg8bl8kgive_donormeta: Data: 0.02MB + Index: 0.03MB
k3ehg8bl8kgive_donors: Data: 0.02MB + Index: 0.03MB
k3ehg8bl8kgive_formmeta: Data: 0.02MB + Index: 0.03MB
k3ehg8bl8kgive_logmeta: Data: 0.02MB + Index: 0.03MB
k3ehg8bl8kgive_logs: Data: 0.02MB + Index: 0.00MB
k3ehg8bl8kgive_sequential_ordering: Data: 0.02MB + Index: 0.00MB
k3ehg8bl8kgive_sessions: Data: 0.02MB + Index: 0.02MB
k3ehg8bl8kgroups_capability: Data: 0.01MB + Index: 0.02MB
k3ehg8bl8kgroups_group: Data: 0.00MB + Index: 0.00MB
k3ehg8bl8kgroups_group_capability: Data: 0.00MB + Index: 0.00MB
k3ehg8bl8kgroups_user_capability: Data: 0.00MB + Index: 0.00MB
k3ehg8bl8kgroups_user_group: Data: 0.18MB + Index: 0.55MB
k3ehg8bl8klinks: Data: 0.02MB + Index: 0.02MB
k3ehg8bl8koptions: Data: 16.39MB + Index: 2.14MB
k3ehg8bl8kphone_orders_log: Data: 0.02MB + Index: 0.00MB
k3ehg8bl8kpostmeta: Data: 148.70MB + Index: 179.50MB
k3ehg8bl8kposts: Data: 21.55MB + Index: 15.09MB
k3ehg8bl8kredirection_404: Data: 0.02MB + Index: 0.06MB
k3ehg8bl8kredirection_groups: Data: 0.02MB + Index: 0.03MB
k3ehg8bl8kredirection_items: Data: 0.02MB + Index: 0.09MB
k3ehg8bl8kredirection_logs: Data: 0.02MB + Index: 0.08MB
k3ehg8bl8ktermmeta: Data: 0.01MB + Index: 0.02MB
k3ehg8bl8kterms: Data: 1.52MB + Index: 2.03MB
k3ehg8bl8kterm_relationships: Data: 1.52MB + Index: 1.52MB
k3ehg8bl8kterm_taxonomy: Data: 1.52MB + Index: 3.03MB
k3ehg8bl8kuam_accessgroups: Data: 0.02MB + Index: 0.00MB
k3ehg8bl8kuam_accessgroup_to_object: Data: 0.02MB + Index: 0.00MB
k3ehg8bl8kusermeta: Data: 21.53MB + Index: 17.03MB
k3ehg8bl8kusers: Data: 1.52MB + Index: 0.48MB
k3ehg8bl8kvtcrt_purchase_log: Data: 0.00MB + Index: 0.00MB
k3ehg8bl8kvtcrt_purchase_log_product: Data: 0.00MB + Index: 0.00MB
k3ehg8bl8kvtcrt_purchase_log_product_rule: Data: 0.00MB + Index: 0.00MB
k3ehg8bl8kvtprd_lifetime_limits_purchaser: Data: 0.00MB + Index: 0.00MB
k3ehg8bl8kvtprd_lifetime_limits_purchaser_logid_rule: Data: 0.00MB + Index: 0.00MB
k3ehg8bl8kvtprd_lifetime_limits_purchaser_rule: Data: 0.00MB + Index: 0.00MB
k3ehg8bl8kvtprd_purchase_log: Data: 191.53MB + Index: 0.01MB
k3ehg8bl8kvtprd_purchase_log_product: Data: 0.93MB + Index: 0.28MB
k3ehg8bl8kvtprd_purchase_log_product_rule: Data: 0.45MB + Index: 0.28MB
k3ehg8bl8kwcpdf_invoice_number: Data: 0.02MB + Index: 0.01MB
k3ehg8bl8kwc_download_log: Data: 0.00MB + Index: 0.00MB
k3ehg8bl8kwc_product_meta_lookup: Data: 5.42MB + Index: 11.61MB
k3ehg8bl8kwc_webhooks: Data: 0.00MB + Index: 0.00MB
k3ehg8bl8kyoast_seo_links: Data: 0.00MB + Index: 0.00MB
k3ehg8bl8kyoast_seo_meta: Data: 0.03MB + Index: 0.03MB
wpstg0_commentmeta: Data: 0.30MB + Index: 0.30MB
wpstg0_comments: Data: 27.56MB + Index: 23.09MB
wpstg0_duplicator_packages: Data: 0.02MB + Index: 0.02MB
wpstg0_give_commentmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_give_comments: Data: 0.02MB + Index: 0.00MB
wpstg0_give_donationmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_give_donormeta: Data: 0.02MB + Index: 0.03MB
wpstg0_give_donors: Data: 0.02MB + Index: 0.03MB
wpstg0_give_formmeta: Data: 0.09MB + Index: 0.06MB
wpstg0_give_logmeta: Data: 0.02MB + Index: 0.03MB
wpstg0_give_logs: Data: 0.02MB + Index: 0.00MB
wpstg0_give_sequential_ordering: Data: 0.02MB + Index: 0.00MB
wpstg0_give_sessions: Data: 0.02MB + Index: 0.02MB
wpstg0_groups_capability: Data: 0.01MB + Index: 0.02MB
wpstg0_groups_group: Data: 0.00MB + Index: 0.00MB
wpstg0_groups_group_capability: Data: 0.00MB + Index: 0.00MB
wpstg0_groups_user_capability: Data: 0.00MB + Index: 0.00MB
wpstg0_groups_user_group: Data: 0.16MB + Index: 0.45MB
wpstg0_links: Data: 0.02MB + Index: 0.02MB
wpstg0_options: Data: 8.45MB + Index: 2.50MB
wpstg0_postmeta: Data: 171.72MB + Index: 204.52MB
wpstg0_posts: Data: 27.56MB + Index: 18.09MB
wpstg0_termmeta: Data: 0.01MB + Index: 0.01MB
wpstg0_terms: Data: 1.52MB + Index: 3.03MB
wpstg0_term_relationships: Data: 1.52MB + Index: 1.52MB
wpstg0_term_taxonomy: Data: 1.52MB + Index: 2.03MB
wpstg0_uam_accessgroups: Data: 0.02MB + Index: 0.00MB
wpstg0_uam_accessgroup_to_object: Data: 0.02MB + Index: 0.00MB
wpstg0_usermeta: Data: 20.55MB + Index: 19.06MB
wpstg0_users: Data: 1.52MB + Index: 0.81MB
wpstg0_vtcrt_purchase_log: Data: 0.00MB + Index: 0.00MB
wpstg0_vtcrt_purchase_log_product: Data: 0.00MB + Index: 0.00MB
wpstg0_vtcrt_purchase_log_product_rule: Data: 0.00MB + Index: 0.00MB
wpstg0_vtprd_lifetime_limits_purchaser: Data: 0.00MB + Index: 0.00MB
wpstg0_vtprd_lifetime_limits_purchaser_logid_rule: Data: 0.00MB + Index: 0.00MB
wpstg0_vtprd_lifetime_limits_purchaser_rule: Data: 0.00MB + Index: 0.00MB
wpstg0_vtprd_purchase_log: Data: 181.43MB + Index: 0.01MB
wpstg0_vtprd_purchase_log_product: Data: 0.89MB + Index: 0.27MB
wpstg0_vtprd_purchase_log_product_rule: Data: 0.42MB + Index: 0.27MB
wpstg0_wcpdf_invoice_number: Data: 0.01MB + Index: 0.01MB
wpstg0_wc_download_log: Data: 0.00MB + Index: 0.00MB
wpstg0_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wpstg0_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wpstg0_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wpstg0_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wpstg0_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wpstg0_woocommerce_order_itemmeta: Data: 975.48MB + Index: 74.27MB
wpstg0_woocommerce_order_items: Data: 14.83MB + Index: 6.63MB
wpstg0_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wpstg0_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wpstg0_woocommerce_sessions: Data: 2.72MB + Index: 0.12MB
wpstg0_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wpstg0_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
wpstg0_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wpstg0_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wpstg0_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wpstg0_yoast_seo_links: Data: 0.00MB + Index: 0.00MB
wpstg0_yoast_seo_meta: Data: 0.03MB + Index: 0.03MB
wpstg1_commentmeta: Data: 0.30MB + Index: 0.30MB
wpstg1_comments: Data: 28.56MB + Index: 24.09MB
wpstg1_duplicator_packages: Data: 0.02MB + Index: 0.02MB
wpstg1_give_commentmeta: Data: 0.02MB + Index: 0.03MB
wpstg1_give_comments: Data: 0.02MB + Index: 0.00MB
wpstg1_give_donationmeta: Data: 0.02MB + Index: 0.03MB
wpstg1_give_donormeta: Data: 0.02MB + Index: 0.03MB
wpstg1_give_donors: Data: 0.02MB + Index: 0.03MB
wpstg1_give_formmeta: Data: 0.02MB + Index: 0.03MB
wpstg1_give_logmeta: Data: 0.02MB + Index: 0.03MB
wpstg1_give_logs: Data: 0.02MB + Index: 0.00MB
wpstg1_give_sequential_ordering: Data: 0.02MB + Index: 0.00MB
wpstg1_give_sessions: Data: 0.02MB + Index: 0.02MB
wpstg1_groups_capability: Data: 0.01MB + Index: 0.02MB
wpstg1_groups_group: Data: 0.00MB + Index: 0.00MB
wpstg1_groups_group_capability: Data: 0.00MB + Index: 0.00MB
wpstg1_groups_user_capability: Data: 0.00MB + Index: 0.00MB
wpstg1_groups_user_group: Data: 0.17MB + Index: 0.46MB
wpstg1_links: Data: 0.02MB + Index: 0.02MB
wpstg1_options: Data: 9.52MB + Index: 2.52MB
wpstg1_postmeta: Data: 174.73MB + Index: 209.53MB
wpstg1_posts: Data: 26.56MB + Index: 18.09MB
wpstg1_termmeta: Data: 0.01MB + Index: 0.01MB
wpstg1_terms: Data: 1.52MB + Index: 3.03MB
wpstg1_term_relationships: Data: 1.52MB + Index: 1.52MB
wpstg1_term_taxonomy: Data: 1.52MB + Index: 2.03MB
wpstg1_uam_accessgroups: Data: 0.02MB + Index: 0.00MB
wpstg1_uam_accessgroup_to_object: Data: 0.02MB + Index: 0.00MB
wpstg1_usermeta: Data: 18.55MB + Index: 17.06MB
wpstg1_users: Data: 0.02MB + Index: 0.05MB
wpstg1_vtcrt_purchase_log: Data: 0.00MB + Index: 0.00MB
wpstg1_vtcrt_purchase_log_product: Data: 0.00MB + Index: 0.00MB
wpstg1_vtcrt_purchase_log_product_rule: Data: 0.00MB + Index: 0.00MB
wpstg1_vtprd_lifetime_limits_purchaser: Data: 0.00MB + Index: 0.00MB
wpstg1_vtprd_lifetime_limits_purchaser_logid_rule: Data: 0.00MB + Index: 0.00MB
wpstg1_vtprd_lifetime_limits_purchaser_rule: Data: 0.00MB + Index: 0.00MB
wpstg1_vtprd_purchase_log: Data: 191.53MB + Index: 0.01MB
wpstg1_vtprd_purchase_log_product: Data: 0.93MB + Index: 0.28MB
wpstg1_vtprd_purchase_log_product_rule: Data: 0.45MB + Index: 0.28MB
wpstg1_wcpdf_invoice_number: Data: 0.01MB + Index: 0.01MB
wpstg1_wc_download_log: Data: 0.00MB + Index: 0.00MB
wpstg1_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wpstg1_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wpstg1_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wpstg1_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wpstg1_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wpstg1_woocommerce_order_itemmeta: Data: 1002.29MB + Index: 75.91MB
wpstg1_woocommerce_order_items: Data: 15.20MB + Index: 6.77MB
wpstg1_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wpstg1_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wpstg1_woocommerce_sessions: Data: 2.25MB + Index: 0.08MB
wpstg1_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wpstg1_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
wpstg1_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wpstg1_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wpstg1_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wpstg1_yoast_seo_links: Data: 0.00MB + Index: 0.00MB
wpstg1_yoast_seo_meta: Data: 0.03MB + Index: 0.03MB

### Post Type Counts ###

attachment: 121
customize_changeset: 1
custom_css: 1
nav_menu_item: 8
page: 14
post: 3
postman_sent_mail: 250
product: 3841
product_variation: 45483
revision: 72
scheduled-action: 18
shop_coupon: 152
shop_order: 31642
shop_order_refund: 23
vtprd-rule: 3
wafs: 1
wpcf7_contact_form: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (30) ###

Category Tag Pages: by Marzio Carro – 1.0
Contact Form 7 Honeypot: by Nocean – 1.14
Contact Form 7: by Takayuki Miyoshi – 5.1.1
Disable Comments: by Samir Shah – 1.9.0
Easy Options for WooCommerce: by Jeff Sherk – 1.5.0 – Not tested with the active version of WooCommerce
Excel-Like Product Manager for WooCommerce and WP E-commerce: by Holest Engineering – 2.1.9 – Not tested with the active version of WooCommerce
FooBox Image Lightbox: by FooPlugins – 2.6.4
Groups: by itthinx – 2.6.1
iFeature Slider Free: by CyberChimps inc. – 1.2
Maintenance Mode: by Lukas Juhas – 2.4.3
PayPal for WooCommerce: by Angell EYE – 1.5.7 – Not tested with the active version of WooCommerce
Phone Orders for WooCommerce: by AlgolPlus – 3.3.0 – Not tested with the active version of WooCommerce
Post SMTP: by Yehuda Hassine – 1.9.8
Print-O-Matic: by twinpictures – 1.7.11
Private content: by Aldo Latino – 5.0
Product Sales Report for WooCommerce: by Potent Plugins – 1.4.8 – Not tested with the active version of WooCommerce
Product Visibility by User Role for WooCommerce Pro: by Algoritmika Ltd – 1.2.5 – Not tested with the active version of WooCommerce
Quick Featured Images: by Martin Stehle – 13.3.3
Responsive Add Ons: by CyberChimps – 1.0.7
User Role Editor: by Vladimir Garagulya – 4.50.2
USPS Simple Shipping for Woocommerce: by SkyWorks85 – 1.2.6 – Not tested with the active version of WooCommerce
WooCommerce Advanced Free Shipping: by Jeroen Sormani – 1.1.4 – Not tested with the active version of WooCommerce
WooCommerce Extended Coupon Features FREE: by Soft79 – 3.0.5 – Not tested with the active version of WooCommerce
WooCommerce Email Test: by RaiserWeb – 1.10 – Not tested with the active version of WooCommerce
WooCommerce Alipay Cross-Border: by WooThemes – 2.4 – Not tested with the active version of WooCommerce
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.7.5

WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.2.12
WooCommerce: by Automattic – 3.6.2
WP Category Sort: by Lovin Nagi – 1.0
YITH WooCommerce Ajax Product Filter: by YITH – 3.6.3

### Inactive Plugins (25) ###

Angell EYE Updater: by Angell EYE – 1.0.6
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.5.5
Duplicator: by Snap Creek – 1.3.10
Elementor: by Elementor.com – 2.5.14
Gutenberg: by Gutenberg Team – 5.6.1
ManageWP - Worker: by GoDaddy – 4.7.7
Multi-Carrier Shipping Plugin for WooCommerce: by PluginHive – 1.4.9 – Not tested with the active version of WooCommerce
Product Visibility by User Role for WooCommerce: by WP Wham – 1.4.1 – Not tested with the active version of WooCommerce
ReadyShipper WooCommerce API: by TrueShip
LLC – 1.0.3 – Not tested with the active version of WooCommerce

Redirection: by John Godley – 4.2.3
User Access Manager: by Alexander Schneider – 2.1.12
VarkTech Pricing Deals for WooCommerce: by Vark – 2.0.0.8
VarkTech Pricing Deals PRO for WooCommerce: by VarkTech – 2.0.0.5 – Not tested with the active version of WooCommerce
Webcraftic Clearfy – WordPress optimization plugin: by Webcraftic <wordpress.webraftic@gmail.com> – 1.5.3
Webcraftic Robin image optimizer: by Webcraftic <wordpress.webraftic@gmail.com> – 1.3.6
Woo Add Empty Cart Button: by Jomar Lipon – 2.0.0 – Not tested with the active version of WooCommerce
WooCommerce - Hide categories where no products are visible to user: by Randall Kam – 0.1 – Not tested with the active version of WooCommerce
WooCommerce Checkout Manager: by Visser Labs – 4.3
WooCommerce Email Monitor: by Raiserweb – 0.4 – Not tested with the active version of WooCommerce
WooCommerce New Product Badge: by jameskoster – 0.3.0 – Not tested with the active version of WooCommerce
WooCommerce Webship Integrated Quoting: by Rock Solid Internet Systems – 1.5 – Not tested with the active version of WooCommerce
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.3.3

WP AutoTerms: by WP AutoTerms – 2.2.6
WP Staging: by WP-Staging – 2.5.5
Yoast SEO: by Team Yoast – 11.1 – Not tested with the active version of WooCommerce

### Must Use Plugins (4) ###

Limit Login Attempts: by Johan Eenfeldt – 1.7.1
Product Subdomain: by  –
Safe mode: by  –
WP Staging Optimizer: by René Hermenau – 1.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: simple (simple)
grouped (grouped)
variable (variable)
external (external)

Taxonomies: Product Visibility: exclude-from-search (exclude-from-search)
exclude-from-catalog (exclude-from-catalog)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #74 - /products/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #77 - /
Terms and conditions: #50380 - /terms-and-conditions/

### Theme ###

Name: responsive-child
Version: 0.1
Author URL: http://ordercart.ohmpharma.com/
Child Theme: ✔
Parent Theme Name: Responsive
Parent Theme Version: 3.14
Parent Theme Author URL: http://cyberchimps.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 17
Oldest: 2019-04-19 23:45:26 +0000
Newest: 2019-04-30 23:11:34 +0000

Pending: 1
Oldest: 2019-05-03 23:46:21 +0000
Newest: 2019-05-03 23:46:21 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by mansi-shah-2248** [comment]
Looks like USPS Simple Shipping For WooCommerce plugin is causing these notices. From your system status is shows that this plugin is not compatible with active WooCommerce version.
Maybe try de-activating that plugin and then check.

**Comment by kloon** [comment]
Hi, what @mansi-shah-2248 said. From the logs you provided the issue is due to the USPS Simple Shipping plugin. You will need to get a version of that plugin that is compatible with the current version of WooCommerce from the author of that plugin.
