### ISSUE TITLE
Loading customer address into a shop order on admin - country field updates AFTER state, state isn't populated

### ISSUE THREAD

**Issue by JonBoss5** [woocommerce/woocommerce#23596]
I came across this on a project when creating an order from the admin panel. It pertains to the 'woocommerce_get_customer_details' ajax call. When I add a customer to the blank order - their address details pre-populate. However if the customer added is in a DIFFERENT country that the store's default, the state will not pre-populate. 

The reason is that the country is being updated after the state. So the state option does not exist in the select before the value is changed, and select2 won't trigger change afterwards. The ajax call returns the data just fine. So this must have to do with looping through the returned address fields.

Specifically, see: assets/js/admin/meta-boxes-order.js line 176.

In this function - the returned billing fields are updated like:

```
if ( response && response.billing ) {
   $.each( response.billing, function( key, data ) {
      $( ':input#_billing_' + key ).val( data ).change();
   });
}

```

See screenshot - logging out each key in this loop. The order has the state before the country. After this has run once, if I then click 'Load billing address' - the state is populated correctly, as the country is already correct when this loop runs for the 'state' field.

![2019-05-02_15-00-35](https://user-images.githubusercontent.com/16190776/57099931-9554fc80-6ceb-11e9-8103-661078700eb3.png)

This problem can be remedied by doing: 

```
if ( response && response.billing ) {
   $.each( response.billing, function( key, data ) {
      $( ':input#_billing_' + key ).val( data ).change();
   });
   $( ':input#_billing_state' ).val( response.billing.state ).change();
}

```

Obviously not the correct solution - just helps to illustrate what the problem is here.

**To Reproduce**
1. Go to 'wp-admin/edit.php?post_type=shop_order'
2. Click on 'Add Order'
3. Add a customer with a full billing/shipping address NOT IN the default country
4. State will not populate

**WordPress Environment**
WP 5.1.1
WooCommerce 3.6.2

**Comment by claudiosanches** [comment]
See https://github.com/woocommerce/woocommerce/pull/23615
Thanks for let us know about this issue.
