### ISSUE TITLE
Sale Products Not Displaying

### ISSUE THREAD

**Issue by jeremiah-sandoval** [woocommerce/woocommerce#23599]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Use this shortcode [sale_products per_page="12" paginate="true"]
2. Go to the page https://www.loveyourhealth.com.au/shop/sale
3. Most of the products that has sale price, are not displaying (eg  https://www.loveyourhealth.com.au/product/waters-co-bmp-400-5-25l-bench-top-alkaline-water-filter/)
4. This happens after the update to v3.6.2

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by kloon** [comment]
Please attach your system status report, this sounds like after the upgrade your lookup table did not generate or was not done generating resulting in missing on sale products. Either check again to ensure that there is no database upgrade notice in wp-admin, if not then please go to WooCommerce -> Status -> Tools tab and click the button next to generate lookup tables and give it some time to complete before checking again.

If you still are not getting the correct results after that then please let me know and I will reopen the issue and take a futher look, but this is definitely related to the lookup table not being populated correctly after the update. See for more details https://github.com/woocommerce/woocommerce/wiki/3.6.x-notes-FAQ#i-am-having-issues-sortingsearching-by-sku-after-the-update
