### ISSUE TITLE
Woocomerce product search results issue in admin dashboard backend

### ISSUE THREAD

**Issue by tigerify** [woocommerce/woocommerce#23591]
Sir,when I am going to ALL PRODUCTS section of woocomerce  (admin dashboard)......When I am searching my product with entering a keyword,not exact results are shown on first page for some of my products.......I am entering correct search keywords only..........but for some products,I am getting correct results.......see my images,u will understand.......

please see the images in the link
https://postimg.cc/gallery/1bi6ehfzu/

**Comment by emoop** [comment]
Hi, I've also got the same problem after the last update. You can solve it by going to woocomerce->tools and press regenerate product lookup tables button.Hope that I helped. And I also hope they solve the problem as soon as the can, because it is really bothering.

**Comment by tigerify** [comment]
No, please tell me in detail.....where to go n what to click....I am not
getting proper search results in back end for my product

**Comment by emoop** [comment]
In admin go to woocommerce->status,when opened .../wp-admin/admin.php?page=wc-status press Tools tab and go to Product lookup tables and press Regenerate. It may take a while for it to fill the table. It works for me.

**Comment by kloon** [comment]
Please see https://github.com/woocommerce/woocommerce/wiki/3.6.x-notes-FAQ#i-am-having-issues-sortingsearching-by-sku-after-the-update

This has been discussed in closed issues already, as @emoop suggested you need to regenerate your lookup table. All the details are at the link I posted above.
