### ISSUE TITLE
Order IDs took a huge step in numbering

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce#23604]
Only a simple question as I saw after upgrading my site from wc 3.5.8 to 3.6.2 that ids for products and orders took a huge step. Latest order ID before upgrade was 26909 but after upgrade the next order ID is 109032 which is about more than 80thousand more. Do I have to look at anything about or is this a correct step?

**Comment by claudiosanches** [comment]
This is normal, since those IDs are from the `wp_posts` table, so any new post (page, post type, etc) will increase this number, even our new system to schedule actions.
