### ISSUE TITLE
Create a new order in backend and country and state in billing and shipping address

### ISSUE THREAD

**Issue by parmarhardip** [woocommerce/woocommerce#23602]
**Describe the bug**
When I create a new order in backend and add billing or shipping address on that order then Select the county by state and change the country then old state showing in state textbox.

**To Reproduce**
1. Go to 'Order tag'
2. Click on 'New order'
3. Then add the billing or shipping address.
4. Go to country and state dropdown.
5. Select that country which is state dropdown provides.
For Example, Select the country=India and select the state Gujarat.
Now change the country which is a country provides a state textbox.
6. See error previous selected state showing in state textbox,

**Screenshots**
![order-page-country-state](https://user-images.githubusercontent.com/23077242/57128148-2097c600-6db0-11e9-97c1-fefa043b48b0.gif)

**Expected behavior**
If the select the country India and state select is Gujarat then change the country state textbox should be blank.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment]
Thanks for reporting it.
See #23603
