### ISSUE TITLE
custom shipping method issue

### ISSUE THREAD

**Issue by chiraggmodi** [woocommerce/woocommerce#23607]
I have create a custom shipping method through extending `WC_Shipping_Method` this method fetch custom values from custom post type which I have created.
The issue is, I need to click on save **setting button** in shipping setting inside my shipping zone which I created to update shipping cost.
so is there a way to update this without click on save button every time I change value in my custom post type?

**Comment by claudiosanches** [comment]
Hi there. GitHub is primarily for reporting bugs and is not a support forum. We don’t support custom development here. You could ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce

>  so is there a way to update this without click on save button every time I change value in my custom post type?

Yes, update the option when you save the custom post type.
