### ISSUE TITLE
Incorrectly showing 'Connected to WooCommerce.com' when the site is not connected

### ISSUE THREAD

**Issue by mansi-shah-2248** [woocommerce/woocommerce#23606]
**Describe the bug**
On a fresh install of WC 3.6.2, Connected to WooCommerce.com shows as checked whereas site is not connected to WooCommerce.com

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

WordPress address (URL): http://localhost/wordpress-wc3.6
Site address (URL): http://localhost/wordpress-wc3.6
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 384 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.29 (Ubuntu)
PHP Version: 5.6.40-1+ubuntu18.04.1+deb.sury.org+1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 50 MB
PHP Time Limit: 900
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1a

SUHOSIN Installed: –
MySQL Version: 5.7.24-0ubuntu0.18.04.1
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: wp_36_
MaxMind GeoIP Database: ✔
Total Database Size: 3.28MB
Database Data Size: 2.22MB
Database Index Size: 1.06MB
wp_36_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_36_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_36_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_36_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_36_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_36_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_36_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_36_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_36_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_36_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_36_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_36_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_36_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_36_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_36_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_36_comments: Data: 0.02MB + Index: 0.09MB
wp_36_links: Data: 0.02MB + Index: 0.02MB
wp_36_options: Data: 1.48MB + Index: 0.05MB
wp_36_postmeta: Data: 0.16MB + Index: 0.11MB
wp_36_posts: Data: 0.06MB + Index: 0.06MB
wp_36_termmeta: Data: 0.02MB + Index: 0.03MB
wp_36_terms: Data: 0.02MB + Index: 0.03MB
wp_36_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_36_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_36_usermeta: Data: 0.02MB + Index: 0.03MB
wp_36_users: Data: 0.02MB + Index: 0.05MB
wp_36_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_36_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_36_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 24
customize_changeset: 11
page: 7
post: 2
product: 22
product_variation: 10
revision: 2
scheduled-action: 1
shop_order: 6

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.6.2

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 4.1.1
Hello Dolly: by Matt Mullenweg – 1.7.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page visibility should be public

### Theme ###

Name: Storefront
Version: 2.4.6
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2019-05-03 05:45:05 +0000
Newest: 2019-05-03 05:45:05 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –
</details>

**Comment by claudiosanches** [comment]
Have you tried to disconnect?
Not able to reproduce this bug with the steps you provided.

**Comment by mansi-shah-2248** [comment]
> Have you tried to disconnect?

I never had connected local setup to woocommerce.com. So didn't try disconnecting.

> Not able to reproduce this bug with the steps you provided.

Please let me know what additional information I can provide you.
I did a new install again just to confirm and same happens there also.

**Comment by kloon** [comment]
I was able to replicate this, disconnecting from WooCommerce.com under WooCommerce -> Extensions -> WooCommerce.com Subscription and loading the System Status report still show a checkmark next to connected to WooCommerce.com.

**Comment by kloon** [comment]
See #23617 for fix.
