### ISSUE TITLE
Incorrect calculation of refund amount

### ISSUE THREAD

**Issue by rahulpragma** [woocommerce/woocommerce#23605]
The refund amount field is read-only because of certain reason which can be acceptable: https://wordpress.org/support/topic/refund-amount-field-set-to-readonly-after-latest-update/#post-11444735

But now it is calculating the refund incorrectly and the refunded amount is less than the total amount I received from the customer.

Here is a live example to regenerate the issue:
https://share.supremeopti.com/woocommerce-incorrect-refund-calculation.mp4

Product price €3,470.00  + Tax on it €659.30 + Freight  & Handling total €58.00 + Tax on it €11.02 = **€4,198.32**

But the refund is showing **€4131.30**. I don't know where is the difference of **€67.02**‬ gone? 

Not sure how would I explain it to the customer why I couldn't refund him the full amount. Or I should refund manually until Woocommerce fixes this bug.

**Comment by DavidAnderson684** [comment]
> I don't know where is the difference of €67.02‬ gone?

Look at 0:27 of your video. You've entered €1 and €1 as the amounts to refund from the freight/handling total and tax, instead of €58 and €11.02.  The difference between those amounts is €67.02.

**Comment by claudiosanches** [comment]
@rahulpragma as David said, you are entering the incorrect mount for freight, those fields are for amounts and not for quantity like on products.
