### ISSUE TITLE
Cart APIs

### ISSUE THREAD

**Issue by ayoubkhan558** [woocommerce/woocommerce#23619]
Cart APIs are missing which are very important to fully utilize WooCommerce APIs.

**Comment by kloon** [comment]
This has been rejected in the past. The REST API is for data consumption, not handling logins and carts. We have no plans for a cart API.

Manage the cart in your app, then use it to create an order if you want checkout functionality via the API.

**Comment by seb86** [comment]
@ayoubkhan558 Checkout https://cocart.xyz

**Comment by ayoubkhan558** [comment]
> @ayoubkhan558 Checkout https://cocart.xyz

Yes i seen this already and used it in my project.
