### ISSUE TITLE
woocommerce_new_product action doesn’t fire when creating a product from admin panel

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce#23610]
Steps to reproduce:
1. Click 'add product'
2. Input title
3. Click Publish

**Comment by claudiosanches** [comment]
On admin screen products/posts are initialized by WordPress, so it's already created before CRUD, still you can use `woocommerce_update_product` hook, or use one of the WordPress ones.

**Comment by adamradocz** [comment]
Then what's the point of the `woocommerce_new_product` hook?

**Comment by martinjankov** [comment]
> Then what's the point of the `woocommerce_new_product` hook?

That's a pretty good question. I just tried to use it and it is not working. It is misleading if not anything else. Might want to rename it.

**Comment by becdetat** [comment]
Here's a bit of a workaround, using `transition_post_status` to hook into the product lifecycle:

```php
add_action( 'transition_post_status', 'add_edit_product', 10, 3 );

function add_edit_product( $new_status, $old_status, $post ) {
    if ( 'product' !== $post->post_type ) {
        return;
    }

    if ( 'publish' !== $new_status ) {
        return;
    }

    if ( 'publish' === $old_status ) {
        echo 'Editing an existing product';
    } else {
        echo 'Adding a new product';
    }
}
```

**Comment by emilnymann** [comment]
I just stumbled upon this hook and spent a couple hours trying to figure out why it wasn't working. It seems like it fires when you save a product as a draft, but when you publish it directly, it doesn't.

Why is this closed when it's still an issue over a year later?

**Comment by asfo** [comment]
I found like @claudiosanches said that WP executes the `new_to_publish` hook, so in theory, this hook could just execute it in the same way.

**Comment by mihaiicey** [comment]
2023 and still doesn't fire :)).

**Comment by bunnadev** [comment]
> 2023 and still doesn't fire :)).

Same for me :)

**Comment by Christophvh** [comment]
@becdetat 

This is pretty good, but this also fires when you set an existing product to draft and then to publish again.

**Comment by unetics** [comment]
I found a workaround using @becdetat's solution and published date
```
add_action('transition_post_status', 'custom_function_on_new_product', 10, 3);
function custom_function_on_new_product($new_status, $old_status, $post) {
    // Check if the post type is 'product' and the new status is 'publish'
    if ($post->post_type === 'product' && $new_status === 'publish') {
        // Get the post's published date
        $published_date = get_the_date('Y-m-d', $post);

        // Get the current date
        $current_date = current_time('Y-m-d');

        // If the post has not been previously published (published date is current date)
        if ($published_date == $current_date) {
          // Its new do what you need
        }
    }
}
```

**Comment by pacmanito** [comment]
Can someone clarify when this hook **IS** fired?
It is supposed to fire when the product is created programmatically, isn't it? Like this: 

```
$product = new WC_Product_Simple();
...
$product->save();
```
