### ISSUE TITLE
Cannot filter products by stock status in admin panel

### ISSUE THREAD

**Issue by nicktirdea** [woocommerce/woocommerce#23616]
Hello,

I recently noticed that I can't filer my products by stock status in admin panel. When I try to filter them, item counter shows the correct number, but on the page there are also wrong products.

I want to see "out of stock products" and select filer options accordingly. In this case, product counter shows the correct number of out of stock products, but on the page I also see in stock products.

For example:
I have 1 out of stock product, set pagination to 20 items per page (in screen options) and system shows me 1 out stock product and 19 in stock ones. Despite this fact, the item counter shows correct value (1 item) - see screenshot 1. 

If I set pagination to 50 items per page, there will be shown 1 out of stock and 49 in stock products.

What I need is to see only out of stock products when I filter by this option (without in stock ones). Check please this issue.

Thank you,
Nick

<img width="825" alt="screen 1" src="https://user-images.githubusercontent.com/50314023/57209774-866b9400-6fe2-11e9-86c5-097c0f7f43a4.png">

**Comment by kloon** [comment]
Hi, this has been addressed already and a fix will be out in 3.6.3.

See #23587

**Comment by nicktirdea** [comment]
Thank you very much for your response! Didn't realize that Yoast plugin may cause this issue. Will wait for WooCommerce 3.6.3 version.

**Comment by kloon** [comment]
No problem, that is why when opening an issue we ask that you test with all plugins disabled except WooCommerce.
