### ISSUE TITLE
Problem in class-emogrifier.ph after last update of WooCommerce

### ISSUE THREAD

**Issue by GiorgosMaragos** [woocommerce/woocommerce#23614]
I had overridden the style of mail in WooCommerce in one last version (3.5.8) After last update, the mail style doesn't work. when debugging I have an error

PHP Fatal error:  Uncaught Error: Call to a member function appendChild() on null in plugins/woocommerce/includes/libraries/class-emogrifier.php:1419
I want the mail work without deleting the $headElementappendChild($styleElement); line of code

I have commented out$headElement-> appendChild ($ styleElement) and everything looks good. So I believe the problem is in mail css. I have tried deleting the custom CSS in customer-completed-order.php but nothing changes. I delete the customer-completed-order.php and the email-styles.php and the debugger shows the same problem. After deletion of all file of the child, mail works with the default style.

```
May-2019 13:46:50 UTC] PHP Fatal error:  Uncaught Error: Call to a member function appendChild() on null in /home/256865.cloudwaysapps.com/wkratgvfzw/public_html/wp-content/plugins/woocommerce/includes/libraries/class-emogrifier.php:1419
Stack trace:

#0 /home/256865.cloudwaysapps.com/wkratgvfzw/public_html/wp-content/plugins/woocommerce/includes/libraries/class-emogrifier.php(1328): Pelago\Emogrifier->addStyleElementToDocument('@media only scr...')
#1 /home/256865.cloudwaysapps.com/wkratgvfzw/public_html/wp-content/plugins/woocommerce/includes/libraries/class-emogrifier.php(526): Pelago\Emogrifier->copyUninlineableCssToStyleNode(Object(DOMXPath), Array)
#2 /home/256865.cloudwaysapps.com/wkratgvfzw/public_html/wp-content/plugins/woocommerce/includes/libraries/class-emogrifier.php(377): Pelago\Emogrifier->process()
#3 /home/256865.cloudwaysapps.com/wkratgvfzw/public_html/wp-content/plugins/woocommerce/includes/emails/class-wc-email.php(535): Pelago\Emogrifier->emogrify()
#4 /home/256865.cloudwaysapps.com/wkratgvfzw/public_html/wp-content/plugins/wooco in /home/256865.cloudwaysapps.com/wkratgvfzw/public_html/wp-content/plugins/woocommerce/includes/libraries/class-emogrifier.php on line 1419
```

**Comment by kloon** [comment]
Perhaps post a copy of your email-styles.php file so we can take a closer look at what might be causing this. Have you tried comparing your modified template with the WooCommerce one to see what the difference is?

**Comment by kloon** [comment]
Also have a read at https://github.com/woocommerce/woocommerce/wiki/3.6.x-notes-FAQ#emogrifier-update Again not sure what you are doing in your custom template but if you are utilising Emogrifier in there that could be the issue.

**Comment by GiorgosMaragos** [comment]
`<?php
/**
 * Email Styles
 *
 * This template can be overridden by copying it to yourtheme/woocommerce/emails/email-styles.php.
 *
 * HOWEVER, on occasion WooCommerce will need to update template files and you
 * (the theme developer) will need to copy the new files to your theme to
 * maintain compatibility. We try to do this as little as possible, but it does
 * happen. When this occurs the version of the template file will be bumped and
 * the readme will list any important changes.
 *
 * @see     https://docs.woocommerce.com/document/template-structure/
 * @package WooCommerce/Templates/Emails
 * @version 3.3.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// Load colors.
$bg              = get_option( 'woocommerce_email_background_color' );
$body            = get_option( 'woocommerce_email_body_background_color' );
$base            = get_option( 'woocommerce_email_base_color' );
$base_text       = wc_light_or_dark( $base, '#202020', '#ffffff' );
$text            = get_option( 'woocommerce_email_text_color' );

// Pick a contrasting color for links.
$link = wc_hex_is_light( $base ) ? $base : $base_text;
if ( wc_hex_is_light( $body ) ) {
	$link = wc_hex_is_light( $base ) ? $base_text : $base;
}

$bg_darker_10    = wc_hex_darker( $bg, 10 );
$body_darker_10  = wc_hex_darker( $body, 10 );
$base_lighter_20 = wc_hex_lighter( $base, 20 );
$base_lighter_40 = wc_hex_lighter( $base, 40 );
$text_lighter_20 = wc_hex_lighter( $text, 20 );

// !important; is a gmail hack to prevent styles being stripped if it doesn't like something.
?>
#wrapper {
	background-color: <?php echo esc_attr( $bg ); ?>;
	margin: 0;
	padding: 70px 0 70px 0;
	-webkit-text-size-adjust: none !important;
	width: 100%;
}

#template_container {
	box-shadow: 0 1px 4px rgba(0,0,0,0.1) !important;
	background-color: <?php echo esc_attr( $body ); ?>;
	border: 1px solid <?php echo esc_attr( $bg_darker_10 ); ?>;
	border-radius: 3px !important;
}

#template_header {
	background-color: <?php echo esc_attr( $base ); ?>;
	border-radius: 3px 3px 0 0 !important;
	color: <?php echo esc_attr( $base_text ); ?>;
	border-bottom: 0;
	font-weight: bold;
	line-height: 100%;
	vertical-align: middle;
	font-family: "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif;
}

#template_header h1,
#template_header h1 a {
	color: <?php echo esc_attr( $base_text ); ?>;
}

#template_footer td {
	padding: 0;
	-webkit-border-radius: 6px;
}

#template_footer #credit {
	border:0;
	color: <?php echo esc_attr( $base_lighter_40 ); ?>;
	font-family: Arial;
	font-size:12px;
	line-height:125%;
	text-align:center;
	padding: 0 48px 48px 48px;
}

#body_content {
	background-color: <?php echo esc_attr( $body ); ?>;
}

#body_content table td {
	padding: 48px 48px 0;
}

#body_content table td td {
	padding: 12px;
}

#body_content table td th {
	padding: 12px;
}

#body_content td ul.wc-item-meta {
	font-size: small;
	margin: 1em 0 0;
	padding: 0;
	list-style: none;
}

#body_content td ul.wc-item-meta li {
	margin: 0.5em 0 0;
	padding: 0;
}

#body_content td ul.wc-item-meta li p {
	margin: 0;
}

#body_content p {
	margin: 0 0 16px;
}

#body_content_inner {
	color: <?php echo esc_attr( $text_lighter_20 ); ?>;
	font-family: "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif;
	font-size: 14px;
	line-height: 150%;
	text-align: <?php echo is_rtl() ? 'right' : 'left'; ?>;
}

.td {
	color: <?php echo esc_attr( $text_lighter_20 ); ?>;
	border: 1px solid <?php echo esc_attr( $body_darker_10 ); ?>;
	vertical-align: middle;
}

.address {
	padding:12px 12px 0;
	color: <?php echo esc_attr( $text_lighter_20 ); ?>;
	border: 1px solid <?php echo esc_attr( $body_darker_10 ); ?>;
}

.text {
	color: <?php echo esc_attr( $text ); ?>;
	font-family: "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif;
}

.link {
	color: <?php echo esc_attr( $base ); ?>;
}

#header_wrapper {
	padding: 36px 48px;
	display: block;
}

h1 {
	color: <?php echo esc_attr( $base ); ?>;
	font-family: "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif;
	font-size: 30px;
	font-weight: 300;
	line-height: 150%;
	margin: 0;
	text-align: <?php echo is_rtl() ? 'right' : 'left'; ?>;
	text-shadow: 0 1px 0 <?php echo esc_attr( $base_lighter_20 ); ?>;
}

h2 {
	color: <?php echo esc_attr( $base ); ?>;
	display: block;
	font-family: "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif;
	font-size: 18px;
	font-weight: bold;
	line-height: 130%;
	margin: 0 0 18px;
	text-align: <?php echo is_rtl() ? 'right' : 'left'; ?>;
}

h3 {
	color: <?php echo esc_attr( $base ); ?>;
	display: block;
	font-family: "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif;
	font-size: 16px;
	font-weight: bold;
	line-height: 130%;
	margin: 16px 0 8px;
	text-align: <?php echo is_rtl() ? 'right' : 'left'; ?>;
}

a {
	color: <?php echo esc_attr( $link ); ?>;
	font-weight: normal;
	text-decoration: underline;
}

img {
	border: none;
	display: inline-block;
	font-size: 14px;
	font-weight: bold;
	height: auto;
	outline: none;
	text-decoration: none;
	text-transform: capitalize;
	vertical-align: middle;
	margin-<?php echo is_rtl() ? 'left' : 'right'; ?>: 10px;
}
<?php
`

when i had delete email-style.php  the error didn't stop.

**Comment by GiorgosMaragos** [comment]
when i had delete email-style.php  the error didn't stop

**Comment by kloon** [comment]
@GiorgosMaragos then the issue is with your themes or a plugin, best is to disable all plugins except WooCommerce and switch your theme to a default one like Storefront or Twentyseventeen and then test, you can then enable plugins one by one testing each time and eventually switching your theme back to find the offending plugin or theme. Changes are good you have a plugin or theme using the included library but using it incorrectly causing the fatal.
