### ISSUE TITLE
PHP Fatal error: Allowed memory size

### ISSUE THREAD

**Issue by Track77** [woocommerce/woocommerce#23612]
Several times a day, error information is written to the log.
This happens after upgrading to the latest version.

`[05-May-2019 05:49:08 Europe/Kiev] PHP Fatal error: Allowed memory size of 805306368 bytes exhausted (tried to allocate 20480 bytes) in /home/c3dkstud/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 249`

`[05-May-2019 05:26:56 Europe/Kiev] PHP Fatal error: Allowed memory size of 805306368 bytes exhausted (tried to allocate 20480 bytes) in /home/c3dkstud/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 249`

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://3d-kstudio.com
Site address (URL): https://3d-kstudio.com
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 756 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.28 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.59.0
OpenSSL/1.0.2q

SUHOSIN Installed: –
MySQL Version: 5.6.40-84.0-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 164.15MB
Database Data Size: 114.80MB
Database Index Size: 49.35MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_downloadable_product_permissions: Data: 1.42MB + Index: 1.11MB
wp_woocommerce_order_items: Data: 0.13MB + Index: 0.07MB
wp_woocommerce_order_itemmeta: Data: 1.02MB + Index: 0.79MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
b2s_posts: Data: 0.02MB + Index: 0.11MB
b2s_posts_network_details: Data: 0.02MB + Index: 0.00MB
b2s_posts_sched_details: Data: 0.02MB + Index: 0.00MB
b2s_post_sched_settings: Data: 0.02MB + Index: 0.03MB
b2s_user: Data: 0.06MB + Index: 0.09MB
b2s_user_contact: Data: 0.02MB + Index: 0.02MB
b2s_user_network_settings: Data: 0.02MB + Index: 0.03MB
kstudio_buyer: Data: 0.14MB + Index: 0.05MB
kstudio_buyer_description: Data: 0.02MB + Index: 0.00MB
kstudio_license_id_files: Data: 0.05MB + Index: 0.00MB
kstudio_license_keys: Data: 7.52MB + Index: 0.00MB
kstudio_open_by_now_link: Data: 2.52MB + Index: 0.00MB
kstudio_plugin: Data: 0.02MB + Index: 0.03MB
kstudio_reseller: Data: 0.02MB + Index: 0.00MB
kstudio_tracking_url: Data: 1.52MB + Index: 0.13MB
mantis_project_version_table: Data: 0.18MB + Index: 0.02MB
wp_ac_abandoned_cart_history_lite: Data: 0.08MB + Index: 0.00MB
wp_ac_email_templates_lite: Data: 0.03MB + Index: 0.00MB
wp_ac_guest_abandoned_cart_history_lite: Data: 0.02MB + Index: 0.00MB
wp_ac_sent_history_lite: Data: 0.06MB + Index: 0.00MB
wp_bbpas: Data: 6.52MB + Index: 11.06MB
wp_blc_filters: Data: 0.02MB + Index: 0.00MB
wp_blc_instances: Data: 0.16MB + Index: 0.08MB
wp_blc_links: Data: 0.16MB + Index: 0.13MB
wp_blc_synch: Data: 0.11MB + Index: 0.06MB
wp_commentmeta: Data: 0.05MB + Index: 0.04MB
wp_comments: Data: 0.21MB + Index: 0.09MB
wp_download_cats: Data: 0.02MB + Index: 0.00MB
wp_download_count: Data: 0.02MB + Index: 0.00MB
wp_download_info: Data: 32.56MB + Index: 7.52MB
wp_download_version: Data: 0.09MB + Index: 0.00MB
wp_duplicator_packages: Data: 0.02MB + Index: 0.02MB
wp_gravatars: Data: 0.02MB + Index: 0.02MB
wp_linkcategorymeta: Data: 0.02MB + Index: 0.05MB
wp_links: Data: 0.01MB + Index: 0.00MB
wp_lockdowns: Data: 0.02MB + Index: 0.00MB
wp_login_fails: Data: 0.02MB + Index: 0.00MB
wp_mail_templates: Data: 0.02MB + Index: 0.02MB
wp_newsletter: Data: 1.52MB + Index: 0.34MB
wp_newsletter_automated: Data: 0.02MB + Index: 0.00MB
wp_newsletter_emails: Data: 2.52MB + Index: 0.00MB
wp_newsletter_sent: Data: 2.00MB + Index: 3.23MB
wp_newsletter_stats: Data: 4.52MB + Index: 3.03MB
wp_newsletter_user_logs: Data: 0.20MB + Index: 0.00MB
wp_options: Data: 16.74MB + Index: 0.17MB
wp_postmeta: Data: 12.47MB + Index: 4.28MB
wp_posts: Data: 2.95MB + Index: 0.58MB
wp_redirection_404: Data: 1.02MB + Index: 0.27MB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB
wp_redirection_logs: Data: 0.05MB + Index: 0.08MB
wp_relevanssi: Data: 5.31MB + Index: 10.84MB
wp_relevanssi_log: Data: 0.20MB + Index: 0.00MB
wp_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB
wp_social_users: Data: 0.08MB + Index: 0.05MB
wp_super: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.12MB + Index: 0.24MB
wp_term_relationships: Data: 0.14MB + Index: 0.28MB
wp_term_taxonomy: Data: 0.12MB + Index: 0.12MB
wp_usermeta: Data: 7.34MB + Index: 2.99MB
wp_users: Data: 0.39MB + Index: 0.44MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wpbi_bar_charts: Data: 0.02MB + Index: 0.02MB
wp_wpbi_database_connections: Data: 0.02MB + Index: 0.02MB
wp_wpbi_datatables: Data: 0.02MB + Index: 0.02MB
wp_wpbi_phinx_log: Data: 0.02MB + Index: 0.00MB
wp_wpbi_pie_charts: Data: 0.02MB + Index: 0.02MB
wp_wpbi_queries3: Data: 0.02MB + Index: 0.03MB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB
wp_yith_wcwl_lists: Data: 0.08MB + Index: 0.11MB
wp_yoast_seo_links: Data: 0.36MB + Index: 0.13MB
wp_yoast_seo_meta: Data: 0.13MB + Index: 0.00MB
wp_ywrr_email_blocklist: Data: 0.02MB + Index: 0.00MB
wp_ywrr_email_schedule: Data: 0.06MB + Index: 0.00MB

### Post Type Counts ###

amn_exact-metrics: 1
attachment: 1949
blocks: 33
customize_changeset: 2
faq: 45
form-entries: 278
forum: 20
gfw_event: 2
gfw_report: 92
gvn_schart: 5
manual_htm: 69
ml-slider: 5
nav_menu_item: 138
oembed_cache: 114
page: 45
post: 101
product: 63
product_variation: 9
reply: 725
revision: 179
scheduled-action: 18
shop_coupon: 32
shop_order: 1911
shop_order_refund: 12
testimonials-widget: 13
todo: 28
topic: 393
wcps: 1
wplp_link: 30

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (78) ###

AddQuicktag: by Frank Bültge – 2.5.3
Custom Admin-Bar Favorites: by Robert Wise – 0.1
Admin Menu Editor: by Janis Elsts – 1.8.8
BackUpWordPress To Google Drive: by Human Made Limited – 2.1.13
BackUpWordPress: by XIBO Ltd – 3.8
Basic User Avatars: by Jared Atchison – 1.0.3
bbP Live Preview: by r-a-y – 0.1
bbPress Toolkit: by Pascal Casier – 1.0.12
bbPress - Live Topic Suggestions: by Hudson Atwell,japh,salbahra – 1.1.0
bbPress Advanced Statistics: by Jake Hall – 1.5
bbPress Notify (No-Spam): by <a href="http://usestrict.net">Vinny Alves (UseStrict Consulting)</a> – 2.1.11
bbPress Permalinks Advanced: by  – 1.1.0
bbpress Simple View Counts: by jezza101 – 0.2
bbPress: by The bbPress Community – 2.5.14
Blog2Social: Social Media Auto Post & Scheduler: by Blog2Social
Adenion – 5.3.0

Buddy-bbPress Support Topic: by G3ronim0 – 2.1.4
Classic Editor: by WordPress Contributors – 1.4
Cleverness To-Do List: by C.M. Kendrick – 3.4.2
Cookie Notice: by dFactory – 1.2.46
Crop Thumbnails: by Volkmar Kantor – 1.2.4
Custom New User Email: by Oleksandr Kramer – 1.0.0 – Not tested with the active version of WooCommerce
Disable Embeds: by Pascal Birchler – 1.4.0
Display All Image Sizes: by Press Up – 1.1.6
Advanced Download Counter: by Andy Staines – 1.3
Duplicate Post: by Enrico Battocchi – 3.2.2
Envato Market: by Envato – 2.0.1
Flexible FAQ: by S. Bage – 0.2
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 5.3.8
Google Language Translator: by Rob Myrick – 5.0.48
Google Video Sitemap Feed With Multisite Support: by Art Project Group – 1.8.1.1
GTmetrix for WordPress: by GTmetrix – 0.4.3
Hierarchical HTML Sitemap: by Alexandra Vovk – 10.2
Image Upload for BBPress: by Potent Plugins – 1.1.15
Lazy Load for Videos: by Kevin Weber – 2.6.1
Log Deprecated Notices: by Andrew Nacin – 0.4.1
Login LockDown: by Michael VanDeMar – v1.7.1
Mailgun: by Mailgun – 1.7.1
My Link Order: by Andrew Charlton – 4.3
Newsletter - Google Analytics: by The Newsletter Team – 1.0.9
Newsletter - Automated Newsletters: by The Newsletter Team – 4.3.2
Newsletter - Addons Manager: by The Newsletter Team – 1.0.4
Newsletter - Reports: by The Newsletter Team – 4.2.2
Newsletter - WP Users Integration: by The Newsletter Team – 1.1.5
Newsletter: by Stefano Lissa & The Newsletter Team – 5.9.3
Nextend Social Login: by Nextendweb – 3.0.20
Plugin Groups: by David Cramer  – 1.2.1
Plugin Notes: by Mohammad Jangda – 1.6
Post Tags and Categories for Pages: by curtismchale – 1.4.1
WooCommerce Product Filter: by Mihajlovic Nenad – 6.6.5 – Not tested with the active version of WooCommerce
Quick Alt Editor: by Arsmoon – 1.0.1
Redirection: by John Godley – 4.2.3
Relevanssi: by Mikko Saari – 40.0.8
Search Regex: by John Godley – 1.4.16
SG Optimizer: by SiteGround – 5.1.2
Shortcodes to show or hide content: by Dave Clements – 2.5
Title and Nofollow For Links: by WPKube – 1.07
Ultimate Tag Cloud Widget: by Rickard Andersson – 2.7.2
User Role Editor: by Vladimir Garagulya – 4.50.2
User Submitted Posts: by Jeff Starr – 20190502
User Switching: by John Blackbourn & contributors – 1.5.0
WCP Contact Form: by Webcodin – 3.1.0
Abandoned Cart Lite for WooCommerce: by Tyche Softwares – 6.0.2 – Not tested with the active version of WooCommerce
WooCommerce Bulk Discount: by Oleksandr Kramer – 2.5.5 – Not tested with the active version of WooCommerce
WooCommerce Cross-Sale Discount: by Oleksandr Kramer – 0.6 – Not tested with the active version of WooCommerce
WooCommerce Currency Converter Widget: by Oleksandr Kramer – 0.6.2 – Not tested with the active version of WooCommerce
WooCommerce Custom Product Tabs Lite: by SkyVerge – 2.2.7 – Not tested with the active version of WooCommerce
WooCommerce Prices: by sydcode – 1.0.2 – Not tested with the active version of WooCommerce
Woocommerce Products Per Page: by Jeroen Sormani – 1.2.6 – Not tested with the active version of WooCommerce
WooCommerce Sales by Country: by MH Mithu – 1.5 – Not tested with the active version of WooCommerce
WooCommerce Sales By Location Report: by ChuckMac Development – 1.3.2 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.6.2
Yoast SEO Premium: by Team Yoast – 25
WP Business Intelligence: by Kenton Hirowatari – 3.1.2
WP Easy Uploader: by Chris Jean – 1.0.14
WP Links Page: by Allyson Rico
Robert Macchi – 4.5

WP Revisions Manager: by P. Roy – 1.0
YITH WooCommerce Review Reminder: by YITH – 1.4.9
YITH WooCommerce Wishlist: by YITH – 2.2.10

### Inactive Plugins (23) ###

bbPress Admin Bar Addition: by David Decker - DECKERWEB – 1.7.1
Better Search Replace: by Delicious Brains – 1.3.3
Broken Link Checker: by ManageWP – 1.11.8
Compress JPEG & PNG images: by TinyPNG – 3.2.0
Custom Field Bulk Editor: by SparkWeb Interactive
Inc. – 1.9.1

Disable All WordPress Updates: by Oliver Schlöbe – 1.6.3
Duplicate Menu: by Jonathan Christopher – 0.2.1
Duplicator: by Snap Creek – 1.3.12
Enhanced Media Library: by wpUXsolutions – 2.7.2
FV Gravatar Cache: by Foliovision – 0.4.3
Intuitive Custom Post Order: by hijiri – 3.1.2
Media Library Categories: by Jeffrey-WP – 1.7
Newsletter - Bounce: by The Newsletter Team – 1.0.5
Newsletter - Extended Composer Blocks: by The Newsletter Team – 1.0.2
Newsletter - Feed by Mail: by The Newsletter Team – 4.1.0
Newsletter - Geo: by The Newsletter Team – 1.0.5
P3 (Plugin Performance Profiler): by GoDaddy.com – 1.5.3.9
Query Monitor: by John Blackbourn – 3.3.4
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.0
Theme Test Drive: by Vladimir Prelovac – 2.9.1
WooCommerce Admin Bar Addition: by David Decker - DECKERWEB – 2.7.0 – Not tested with the active version of WooCommerce
WordPress File Monitor Plus: by Scott Cariss – 2.2
WP Downgrade | Specific Core Version: by Reisetiger – 1.2.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #65 - /shop/
Cart: #66 - /cart/
Checkout: #67 - /checkout/
My account: #68 - /my-account/
Terms and conditions: #4863 - /support/license-terms/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.8.3
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome-child/woocommerce/cart/mini-cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome-child/woocommerce/content-product.php
flatsome-child/woocommerce/content-product_cat.php
flatsome-child/woocommerce/content-single-product.php
flatsome-child/woocommerce/content-widget-product.php
flatsome-child/woocommerce/emails/customer-new-account.php
flatsome-child/woocommerce/emails/email-footer.php
flatsome-child/woocommerce/emails/email-header.php
flatsome-child/woocommerce/emails/email-styles.php
flatsome-child/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome-child/woocommerce/myaccount/dashboard.php
flatsome-child/woocommerce/myaccount/form-edit-address.php
flatsome-child/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome-child/woocommerce/myaccount/view-order.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome-child/woocommerce/single-product/add-to-cart/external.php
flatsome-child/woocommerce/single-product/add-to-cart/grouped.php
flatsome-child/woocommerce/single-product/add-to-cart/simple.php
flatsome-child/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
flatsome-child/woocommerce/single-product/meta.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome-child/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome-child/woocommerce/single-product/rating.php
flatsome-child/woocommerce/single-product/related.php
flatsome-child/woocommerce/single-product/review-meta.php
flatsome-child/woocommerce/single-product/review-rating.php
flatsome-child/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome-child/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome-child/woocommerce/single-product/title.php
flatsome-child/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

### Action Scheduler ###

Complete: 16
Oldest: 2019-04-20 18:46:02 +0300
Newest: 2019-05-04 18:46:23 +0300

Pending: 1
Oldest: 2019-05-11 18:46:23 +0300
Newest: 2019-05-11 18:46:23 +0300

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 1
Oldest: 2019-04-20 18:46:13 +0300
Newest: 2019-04-20 18:46:13 +0300

`
</details>

**Comment by Track77** [comment]
Sorry - this is a problem with other plugin.

**Comment by mbaric** [comment]
hi @Track77, I have similar problem here at my end how did you trace down it was other plugin. Can you share your steps please. Thanks.

**Comment by Track77** [comment]
I used this advices for solution
https://wordpress.org/support/topic/how-to-debug-issues-after-updates/

I used this:

> Disable all other plugins except for WooCommerce itself, retest, and re-activate plugins until the issue occurs. This will help you find the culprit.

**Comment by mbaric** [comment]
Thank you Oleksandr, will try to see what we can do from our side.

@Track77
