### ISSUE TITLE
Request Import Product by CSV File without downloading image files.

### ISSUE THREAD

**Issue by ntaapp** [woocommerce/woocommerce#23629]
Hello,
I know it's weird, but I have thousands of images hosted in remote server. 
I just don't want WooCommerce Download all images to uploads folder and slowdown my main website.

If possible please add a check box says: "Use images as remote images (do not download images to uploads folder)

Thanks

**Comment by kloon** [comment]
Hi, that is unfortunately not possible at present. Images are required to be on your site as it is linked to a product as an attachment, the same as with WordPress posts and pages when you assign featured images.

A product image is essentially the same as a featured for a post in the context of a product.

**Comment by ntaapp** [comment]
That why I think it will be good if you guys can add this function.
