### ISSUE TITLE
Upload external image url when create product api v2

### ISSUE THREAD

**Issue by deptraicogisai** [woocommerce/woocommerce#23628]
Hi !
I want to use my image url on my product and variant when I create product by API . But i dont know what should to do because wp always download and save on wp server

**Comment by kloon** [comment]
Hi, please see this section on how to define images when importing or assigning it via the API https://docs.woocommerce.com/document/product-csv-import-suite-faq-troubleshooting/#section-9

TLDR: Just pass the filename if it already on your server instead of the full url.
