### ISSUE TITLE
Potential issue sending all WC endpoints to 404 when not on the account page

### ISSUE THREAD

**Issue by thomasplevy** [woocommerce/woocommerce#23622]
**Describe the bug**

First off I'm not entirely sure this is a bug, but it's an issue of some kind -- potentially -- and has caused issues for users using my plugin ([LifterLMS](https://wordpress.org/plugins/lifterlms/)) alongside WooCommerce.

My concern is that Since WC 3.6, any WooCommerce endpoint is sent to a 404 if that endpoint is accessed outside of the My Account page (see [commit](https://github.com/woocommerce/woocommerce/commit/a0f47fb429266e1d55fbe5f77db928e478682973)).

I see the intention of this bit of code however I feel that it causes some potential issues like preventing access to any child page.

Aside from this, it also creates a new conflict with any plugin "sharing" endpoints with WooCommerce. I've dug into this issue not because of the actual issue below but because my plugin also has a dashboard with a "lost-password" endpoint sharing an `add_rewrite_rule()` with the WC rule. Before 3.5.8 both our lost password page as well as the WC page work fine. While I know that there's little reason to have two frontend password resets, in the case of some of our shared users they wish to have different experiences for users (one for the shop users one for their students via my plugin).

Currently I can patch this issue from my end by "hijacking" the return of the `is_account_page()` function via the filter `woocommerce_is_account_page` but this doesn't exactly seem the best way to do this. Perhaps adding a filter inside of the block determining that a 404 should be sent would allow plugin devs like myself to alleviate these conflicts in a more semantic way. EG: I could add a check to see if this endpoint can be used on my plugin's dashboard and, if it is, skip the 404 generated by WC. If this seems like an acceptable filter to add I'll happily write the update and submit a PR.

**To Reproduce**

1. Create a page (any slug) but don't set it as the WC account page in WC settings
2. Add a new page with a slug of "downloads" (or any slug used by a WC account page endpoint) and set this page's parent as the page created in step 1.
3. Access the child page.
4. You'll be presented with a 404 on 3.6 or later but not on 3.5.8

**Expected behavior**

In the above example I would expect to be able to access the child page but instead receive a 404.

As I said, I'm not sure this is actually a bug and perhaps this has already been addressed and considered by the core team but I wanted to raise this as a potential issue.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```

### WordPress Environment ###

WordPress address (URL): https://dark-waterfall.myliftersite.com
Site address (URL): https://dark-waterfall.myliftersite.com
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.39 (Unix) OpenSSL/1.1.0g
PHP Version: 7.3.4
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.58.0
OpenSSL/1.1.0g

SUHOSIN Installed: –
MySQL Version: 5.7.26-0ubuntu0.18.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: wp_2bd9c306d1_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from https://dev.maxmind.com/geoip/geoip2/geolite2/ to the path: . Scroll down to "Downloads" and download the "MaxMind DB binary
gzipped" file next to "GeoLite2 Country". Please remember to uncompress GeoLite2-Country_xxxxxxxx.tar.gz and upload the GeoLite2-Country.mmdb file only.

Total Database Size: 2.20MB
Database Data Size: 0.94MB
Database Index Size: 1.26MB
wp_2bd9c306d1_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_2bd9c306d1_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_2bd9c306d1_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_2bd9c306d1_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_2bd9c306d1_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_2bd9c306d1_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_2bd9c306d1_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_2bd9c306d1_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_2bd9c306d1_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_2bd9c306d1_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_2bd9c306d1_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_2bd9c306d1_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_2bd9c306d1_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_2bd9c306d1_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_2bd9c306d1_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_2bd9c306d1_comments: Data: 0.02MB + Index: 0.09MB
wp_2bd9c306d1_lifterlms_notifications: Data: 0.02MB + Index: 0.05MB
wp_2bd9c306d1_lifterlms_product_to_voucher: Data: 0.02MB + Index: 0.03MB
wp_2bd9c306d1_lifterlms_quiz_attempts: Data: 0.02MB + Index: 0.03MB
wp_2bd9c306d1_lifterlms_stripe_plans: Data: 0.02MB + Index: 0.00MB
wp_2bd9c306d1_lifterlms_user_postmeta: Data: 0.02MB + Index: 0.03MB
wp_2bd9c306d1_lifterlms_vouchers_codes: Data: 0.02MB + Index: 0.03MB
wp_2bd9c306d1_lifterlms_voucher_code_redemptions: Data: 0.02MB + Index: 0.03MB
wp_2bd9c306d1_links: Data: 0.02MB + Index: 0.02MB
wp_2bd9c306d1_options: Data: 0.09MB + Index: 0.05MB
wp_2bd9c306d1_postmeta: Data: 0.13MB + Index: 0.11MB
wp_2bd9c306d1_posts: Data: 0.06MB + Index: 0.06MB
wp_2bd9c306d1_termmeta: Data: 0.02MB + Index: 0.03MB
wp_2bd9c306d1_terms: Data: 0.02MB + Index: 0.03MB
wp_2bd9c306d1_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_2bd9c306d1_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_2bd9c306d1_usermeta: Data: 0.02MB + Index: 0.03MB
wp_2bd9c306d1_users: Data: 0.02MB + Index: 0.05MB
wp_2bd9c306d1_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_2bd9c306d1_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_2bd9c306d1_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 2
course: 2
lesson: 13
llms_access_plan: 2
llms_order: 4
llms_question: 1
llms_quiz: 1
llms_transaction: 8
page: 6
post: 2
scheduled-action: 12
section: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.6.2

### Inactive Plugins (2) ###

LifterLMS: by LifterLMS – 3.30.3
LifterLMS Stripe Payment Gateway: by LifterLMS – 4.4.1

### Must Use Plugins (1) ###

LifterLMS Trial MU: by LifterLMS – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Nineteen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 4
Oldest: 2019-05-06 19:25:54 +0000
Newest: 2019-05-06 19:25:57 +0000

Pending: 4
Oldest: 2019-05-07 07:25:54 +0000
Newest: 2019-05-10 19:29:04 +0000

Canceled: 4
Oldest: 2019-04-27 19:05:22 +0000
Newest: 2019-05-03 19:29:04 +0000

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

```
</details>

**Comment by claudiosanches** [comment]
> If this seems like an acceptable filter to add I'll happily write the update and submit a PR.

Please, we'll be happy with your help.
I agree that will be nice to have a filter for it.

**Comment by thomasplevy** [comment]
@claudiosanches,

On it! I'll have a PR submitted in a bit.

I am curious though if the behavior I've described above (with regards to a "child" page sharing a slug with a WC endpoint) would be considered a bug or if this would be expected behavior that's been considered by the team.

**Comment by claudiosanches** [comment]
I'm closing the issue as it already has a PR, please continue the discussion over at #23660.

**Comment by thomasplevy** [comment]
@claudiosanches 

Perhaps I should open a separate issue for "bug" I'm asking about here? 

#23660 only addresses a portion of the issue I'm reporting

**Comment by thomasplevy** [comment]
@claudiosanches 

I'm sorry I don't currently have the capacity to work on a PR for the first part of this issue but I would still like to know if WC is considering this a bug or expected behavior.

If it is a bug / issue I'd like this issue to be reopened or addressed. 

The filter from #23660 is great for working around the issues and adding compatibility for my plugin but the issue described in the reproduction steps will still remain as a potential issue for any stock WC install sharing an endpoint as described.

Thanks
