### ISSUE TITLE
PayPal gateway will not capture authorized transactions if you use a custom order status.

### ISSUE THREAD

**Issue by SpencerConstance** [woocommerce/woocommerce#23626]
**Is your feature request related to a problem? Please describe.**
When using custom order status' from plugins like "WooCommerce Order Status Manager" from the WooCommerce store or similar plugins while the PayPal gateway is set to authorize, transactions will not be captured when the status is changed.

**Describe the solution you'd like**
Instead of hooking the "capture_payment" method to "woocommerce_order_status_on-hold_to_completed" in "class-wc-gateway-paypal.php", hook it to "woocommerce_order_status_completed" so the transaction will always be captured eventually.

**Additional context**
If the PayPal gateway is set to authorize and you use a custom order status right after "On Hold", the PayPal gateway will never capture the order.

**Comment by kloon** [comment]
See #23634
