### ISSUE TITLE
Coupon Discounts Incorrectly Calculate when Adding a Number of Items Usage Limit

### ISSUE THREAD

**Issue by t4lm1d** [woocommerce/woocommerce#23624]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Add a product
2. Add a product variation with a larger price ($19.99)
3. Add a product variation with a smaller price ($12.99)
4. Add a coupon with a usage limit of say 6 items
5. Add product 1 to the cart with a quantity of 1
6. Add product 2 to the cart with a quantity of 2
7. Add coupon created on step 4
8. Calculate discount

## Expected/actual behavior

When I follow those steps, I see...

Discount is calculated on subtotal meaning that at larger volumes, customers are not receiving a discount on the higher priced items. It's receiving discount on the highest priced subtotals

I was expecting to see...

Customer receives discounts on the correct number of highest priced items and then the subsequent lower priced items

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

Home URL: https://staging.phuelyou.com
Site URL: https://staging.phuelyou.com
WC Version: 3.5.3
Log Directory Writable: ✔
WP Version: ❌ 4.9.10 - There is a newer version of WordPress available (5.1.1)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.17-1+ubuntu18.04.1+deb.sury.org+3
PHP Post Max Size: 100 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1b

SUHOSIN Installed: –
MySQL Version: 5.6.43-84.3-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.3
WC Database Prefix: wp_
Total Database Size: 36.50MB
Database Data Size: 17.11MB
Database Index Size: 19.39MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.23MB + Index: 0.09MB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 1.88MB
wp_woocommerce_tax_rates: Data: 0.06MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.06MB + Index: 0.08MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_cf7dbplugin_st: Data: 0.02MB + Index: 0.00MB
wp_cf7dbplugin_submits: Data: 0.02MB + Index: 0.05MB
wp_commentmeta: Data: 0.08MB + Index: 0.11MB
wp_comments: Data: 1.52MB + Index: 0.55MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 0.30MB + Index: 0.06MB
wp_postmeta: Data: 7.52MB + Index: 10.03MB
wp_posts: Data: 1.52MB + Index: 0.56MB
wp_redirection_404: Data: 0.02MB + Index: 0.06MB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB
wp_redirection_items: Data: 0.02MB + Index: 0.08MB
wp_redirection_logs: Data: 0.02MB + Index: 0.08MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 3.52MB + Index: 5.03MB
wp_users: Data: 0.19MB + Index: 0.20MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.05MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.06MB + Index: 0.00MB

### Post Type Counts ###

attachment: 202
client: 12
customize_changeset: 9
mega_menu: 3
nav_menu_item: 14
page: 25
post: 11
product: 6
product_variation: 4
revision: 1
shop_coupon: 924
shop_order: 1177
shop_order_refund: 17
testimonial: 7
wpcf7_contact_form: 9
wpsl_stores: 24

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (27) ###

Ebor Framework: by Tom Rhodes – 1.4.11
Contact Form DB: by Michael Simpson – 2.10.21
Contact Form 7: by Takayuki Miyoshi – 5.1.1
Duplicate Page: by mndpsingh287 – 3.2
Instagram Feed: by Smash Balloon – 1.10.2
WPBakery Page Builder: by Michael M - WPBakery.com – 5.6
WooCommerce: No PO Boxes: by Maje Media LLC – 2.0.2 – Not tested with the active version of WooCommerce
Redirection: by John Godley – 3.7.1
Search & Replace: by Inpsyde GmbH – 3.1.2
SendGrid: by SendGrid – 1.11.8
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 2.0.1 – Not tested with the active version of WooCommerce
Velvet Blues Update URLs: by VelvetBlues.com – 3.2.8
WooCommerce Customer/Order CSV Export: by SkyVerge – 4.4.6 – 4.6.3 is available – Not tested with the active version of WooCommerce
WooCommerce emfluence Addon: by Eric Trujillo – 1.0.1 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.1.14
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.7
WooCommerce Sequential Order Numbers: by SkyVerge – 1.8.3 – Not tested with the active version of WooCommerce
WooCommerce Smart Coupons: by StoreApps – 3.6.0 – 4.0.3 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.5.3 – 3.6.2 is available
WordPress Importer: by wordpressdotorg – 0.6.4
Yoast SEO: by Team Yoast – 9.4
emfluence Marketing Platform: by emfluence Digital Marketing – 2.7.1
WP LESS: by Oncle Tom – 1.8.0
WP Maintenance Mode: by Designmodo – 2.2.2
WP Store Locator - CSV Manager: by Tijmen Smit – 1.2.0
WP Store Locator: by Tijmen Smit – 2.2.20
WPFront Notification Bar: by Syam Mohan – 1.7.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #319 - /shop/
Cart: #320 - /cart/
Checkout: #321 - /checkout/
My account: ❌ Page does not contain the shortcode.
Terms and conditions: #17 - /terms-of-use/

### Theme ###

Name: PHUEL
Version: 2.0.0
Author URL: https://faithaccompli.com
Child Theme: ✔
Parent Theme Name: Foundry
Parent Theme Version: 2.1.4
Parent Theme Author URL: http://www.tommusrhodus.com
WooCommerce Support: ✔

### Templates ###

Overrides: foundry/woocommerce/archive-product.php
phuel-child/woocommerce/cart/cart.php version - is out of date. The core version is 3.5.0
phuel-child/woocommerce/content-product.php version - is out of date. The core version is 3.4.0
foundry/woocommerce/content-product_cat.php
foundry/woocommerce/content-single-product.php
foundry/woocommerce/loop/loop-end.php
foundry/woocommerce/loop/loop-start.php
phuel-child/woocommerce/loop/orderby.php version 2.2.0 is out of date. The core version is 3.3.0
foundry/woocommerce/loop/pagination.php
foundry/woocommerce/loop/price.php
phuel-child/woocommerce/loop/result-count.php version 2.0.0 is out of date. The core version is 3.3.0
foundry/woocommerce/loop/sale-flash.php
foundry/woocommerce/notices/error.php
foundry/woocommerce/notices/notice.php
foundry/woocommerce/notices/success.php
foundry/woocommerce/product-searchform.php
foundry/woocommerce/single-product/add-to-cart/variable.php
foundry/woocommerce/single-product/meta.php
phuel-child/woocommerce/single-product/product-image.php version 3.3.2 is out of date. The core version is 3.5.1
foundry/woocommerce/single-product/rating.php
foundry/woocommerce/single-product/related.php
foundry/woocommerce/single-product/review.php
foundry/woocommerce/single-product/tabs/tabs.php
phuel-child/woocommerce/single-product/title.php
phuel-child/woocommerce/single-product/up-sells.php version 1.6.4 is out of date. The core version is 3.0.0
foundry/woocommerce/single-product-reviews.php
phuel-child/woocommerce/single-product.php
foundry/woocommerce/taxonomy-product_cat.php
foundry/woocommerce/taxonomy-product_tag.php

Outdated Templates: ❌
					
					
						Learn how to update

### Customer/Order CSV Export ###

Order Export Format: default
Customer Export Format: default
Automatically Export Orders: disabled
Automatically Export Customers: disabled
`
</details>

**Comment by kloon** [comment]
Hi, discounts are calculated on a subtotal level, if you do a search on here you will see numerous threads regarding this topic such as https://github.com/woocommerce/woocommerce/issues/22034 We also altered descriptions in https://github.com/woocommerce/woocommerce/pull/22421 to make it clearer for admins how discounts are calculated.

If you are after more control on how discounts are calculated then perhaps look at https://wordpress.org/plugins/woo-discount-rules/ which might provide you with the functionality to apply it on a product level.

**Comment by t4lm1d** [comment]
I understand what you are saying and ordinarily I think calculation on the subtotal would make sense.  However when you "Limit a coupon to the first 6 items in the cart," this no longer makes sense to users and is misleading.  They would expect the highest top priced items to receive the discount. (or even the lowest 6 priced items). * In this instance (limiting coupon discounts to a specific quantity), ordering the cart by highest subtotal doesn't seem to fit when the highest subtotal could be a quantity of lesser priced items* .. I see you closed the issue so all I can ask is that this consideration be revisited again at some point in the future.  Thanks though for passing on the discount rules plugin. We will check it out.

**Comment by KCJP** [comment]
Hello there, I originally pointed this issue out to our developers.

The request was to create a coupon for 20% off that can only be used on maximum of 6 items to prevent overuse of the coupon.  WooCommerce does support this. 

However, there is an issue.  To recreate it: 
1. Create a coupon for 20% off with a limit of 6 items
2. Add qty 5 of an item of $12.99 to the cart
3. Add qty 3 of an item of $19.99 to the cart
4. Apply the coupon.

As a Customer, the expected coupon discount should be $19.79, which is 20% off all three of the more expensive items and 20% off three of the lower priced items.

The actual coupon amount is $16.99, which behaves as described above.  It's calculated based on highest sub-total first and item count second.  As a customer though, this does not give me the discount I'm expecting.  There does not appear to be an option to toggle the order discounts are applied in, so at this time this issue appears to be a bug. @kloon , Would you or someone on the team mind taking a second look at this one?
