### ISSUE TITLE
The all tab doesn't work. 

### ISSUE THREAD

**Issue by HoofBoss** [woocommerce/woocommerce#23620]
**Describe the bug**
There is a tab in the orders section that I used to be able to see every order that we've have had through woocommerce. Now it doesn't have anything under it when i click on it and i have to go back and forth between the other tabs to find what i need when i used to be able to see everything under 1 tab. 

![Screenshot (28)](https://user-images.githubusercontent.com/49528014/57234202-267aea80-6fee-11e9-82a5-d87e511ed163.png)

**Comment by rodrigoprimo** [comment]
I'm sorry but this is not a support forum. We use GitHub issues exclusively for WooCommerce core bug reports. For support, you can try the WordPress.org support forum (https://wordpress.org/support/plugin/woocommerce/). Alternatively, if you are a paying WooCommerce.com user, you can contact their support (http://woocommerce.com/contact-us/).

You might also want to check this page (https://docs.woocommerce.com/document/how-to-test-for-conflicts/) to rule out plugin/theme conflict.

If I missed something and there is indeed a WooCommerce core bug, please open another issue following the bug report template (https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=).

**Comment by rodrigoprimo** [comment]
You might also want to make sure you are running the latest version of WooCommerce. There was an issue in a past version of WooCommerce when running WP 5.0.2 or higher that would cause the problem you are describing. This was fixed in WooCommerce 3.5.3 released in December 2018. To learn more about the issue see #22271 and #22273.

**Comment by marcwieland95** [comment]
I don't know if this is a regression, but I have the same issue as described above.

I've got WooCommerce version 3.8.1 and WP-Core version 5.3.2. Can anyone also confirm that the all-Tab is showing no results? Already switched to a default theme and deactivated WooCommerce related plugins.

**Comment by marcwieland95** [comment]
Some days later it started working out of nowhere. Is it possible that this has something to do with the database migrations which are done in the background?
