### ISSUE TITLE
WC()->cart return null.

### ISSUE THREAD

**Issue by paolomp2** [woocommerce/woocommerce#23623]
**Describe the bug**
The property WC()->cart return null. After the last update (3.6.1) the variable return null. There is some one problem?

Before that the value retorned was a object with the item of the cart. Please let me know if its necessary on aditional step. Thanks you.

**Comment by claudiosanches** [comment]
Depends on where you are calling it, since should only work on the front end, we made a few changes to improve performance and to ensure it:
https://github.com/woocommerce/woocommerce/blob/c79e3ad8f1f58022d9574f02a762de4476c5cad7/includes/class-woocommerce.php#L528-L541

**Comment by paolomp2** [comment]
claudiosanches, thanks for you answer. I am ussing it on a Ajax Called.
How its can be used in this situation?
