### ISSUE TITLE
Free shipping with minimum order not working with Version 3.6.2

### ISSUE THREAD

**Issue by SubratBarik** [woocommerce/woocommerce#23635]
I have configuring woocommerce free shipping on minimum order $40 (in australia) but it is not working. Flat rate shipping in australia and international shipping calculation works fine.

Any suggestions? what wrong?

`
### WordPress Environment ###

WordPress address (URL): https://demoserversydney.com/soles/website
Site address (URL): https://demoserversydney.com/soles/website
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.0.33 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 3000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 10.1.39-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: soles_
MaxMind GeoIP Database: ✔
Total Database Size: 0.97MB
Database Data Size: 0.79MB
Database Index Size: 0.18MB
soles_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB
soles_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
soles_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
soles_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
soles_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
soles_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
soles_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
soles_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
soles_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
soles_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
soles_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
soles_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
soles_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
soles_woocommerce_log: Data: 0.00MB + Index: 0.00MB
soles_cfs_sessions: Data: 0.02MB + Index: 0.01MB
soles_cfs_values: Data: 0.00MB + Index: 0.01MB
soles_commentmeta: Data: 0.00MB + Index: 0.00MB
soles_comments: Data: 0.00MB + Index: 0.01MB
soles_gf_draft_submissions: Data: 0.00MB + Index: 0.00MB
soles_gf_entry: Data: 0.00MB + Index: 0.00MB
soles_gf_entry_meta: Data: 0.00MB + Index: 0.00MB
soles_gf_entry_notes: Data: 0.00MB + Index: 0.00MB
soles_gf_form: Data: 0.00MB + Index: 0.00MB
soles_gf_form_meta: Data: 0.00MB + Index: 0.00MB
soles_gf_form_revisions: Data: 0.00MB + Index: 0.00MB
soles_gf_form_view: Data: 0.00MB + Index: 0.00MB
soles_links: Data: 0.00MB + Index: 0.00MB
soles_options: Data: 0.59MB + Index: 0.04MB
soles_postmeta: Data: 0.09MB + Index: 0.04MB
soles_posts: Data: 0.07MB + Index: 0.02MB
soles_rg_form: Data: 0.00MB + Index: 0.00MB
soles_rg_form_meta: Data: 0.00MB + Index: 0.00MB
soles_rg_form_view: Data: 0.00MB + Index: 0.00MB
soles_rg_incomplete_submissions: Data: 0.00MB + Index: 0.00MB
soles_rg_lead: Data: 0.00MB + Index: 0.00MB
soles_rg_lead_detail: Data: 0.00MB + Index: 0.00MB
soles_rg_lead_detail_long: Data: 0.00MB + Index: 0.00MB
soles_rg_lead_meta: Data: 0.00MB + Index: 0.00MB
soles_rg_lead_notes: Data: 0.00MB + Index: 0.00MB
soles_termmeta: Data: 0.00MB + Index: 0.01MB
soles_terms: Data: 0.00MB + Index: 0.01MB
soles_term_relationships: Data: 0.00MB + Index: 0.00MB
soles_term_taxonomy: Data: 0.00MB + Index: 0.00MB
soles_usermeta: Data: 0.01MB + Index: 0.01MB
soles_users: Data: 0.00MB + Index: 0.01MB
soles_wc_download_log: Data: 0.00MB + Index: 0.00MB
soles_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB
soles_wc_webhooks: Data: 0.00MB + Index: 0.00MB
soles_yoast_seo_links: Data: 0.00MB + Index: 0.00MB
soles_yoast_seo_meta: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 32
cfs: 7
customize_changeset: 4
home-slider: 5
nav_menu_item: 14
page: 11
post: 6
product: 2
product_variation: 2
revision: 24
scheduled-action: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (7) ###

Gravity Forms: by rocketgenius – 2.4.8
Classic Editor: by WordPress Contributors – 1.4
Custom Field Suite: by Matt Gibbs – 2.5.14
WooCommerce Image Zoom: by wpbean – 1.02.9
WooCommerce: by Automattic – 3.6.2
Yoast SEO: by Team Yoast – 11.1 – Not tested with the active version of WooCommerce
WPFront Scroll Top: by Syam Mohan – 2.0.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.1
Hello Dolly: by Matt Mullenweg – 1.7.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #13 - /the-shop/
Cart: #14 - /cart/
Checkout: #15 - /checkout/
My account: #16 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Soles
Version: 1.8
Author URL: #
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: soles/woocommerce/archive-product.php
soles/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
soles/woocommerce/single-product/short-description.php
soles/woocommerce/single-product.php

### Action Scheduler ###

Complete: 1
Oldest: 2019-05-06 11:29:38 +0000
Newest: 2019-05-06 11:29:38 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by claudiosanches** [comment]
> I have configuring woocommerce free shipping on minimum order $40 (in australia) but it is not working. Flat rate shipping in australia and international shipping calculation works fine.

I can't reproduce this issue with the steps you provided.
There's any extra step?

**Comment by SubratBarik** [comment]
Sorry, I didn't understand. Can please explain a bit more.


Regards,

Subrat Kumar Barik,
8420247731,
subratmca85@gmail.com

**Comment by SubratBarik** [comment]
I followed the documentation to setup free shipping. Normally, it works but with updated woocommerce plugin it is not working. Don't know what happened  or what I did wrong.

**Comment by claudiosanches** [comment]
> I followed the documentation to setup free shipping. Normally, it works but with updated woocommerce plugin it is not working. Don't know what happened or what I did wrong.

Still I need steps to how reproduce it, how the shipping zones are configured? What shipping method you have in any shipping zone? And so on.
Screenshots should help too.

**Comment by SubratBarik** [comment]
Here are the screenshots of shipping settings:

https://ibb.co/JyzM9kg
https://ibb.co/wQBPQBy
https://ibb.co/3BvTHDR
https://ibb.co/y4wvmw2
https://ibb.co/8sMtwKL

Let me know if you need anything else from me.

**Comment by claudiosanches** [comment]
In the first screenshot you can already see the problem: 

![shipping-step-1](https://user-images.githubusercontent.com/1264099/57412074-df475200-71c5-11e9-87f5-aa1b759b36d9.png)

You have two shipping zones that matches with Australia, that's why only flat rate appears in the cart, since it's the first shipping zone to match. So to fix it you need to put both shipping methods inside the same shipping zone.

**Comment by SubratBarik** [comment]
Thank you very much. Let me try the suggested fix.

**Comment by SubratBarik** [comment]
You saved me. Thank you very much. 

It was a silly mistake from my end. :)
