### ISSUE TITLE
'Out of stock'-error doesn't show up on checkout page

### ISSUE THREAD

**Issue by Walkeezy** [woocommerce/woocommerce#23630]
**Describe the bug**
If you add a product to the cart, meanwhile set this product to be 'out of stock', you get a 'out of stock'-notice in the cart. If you then proceed to the checkout, there is no error showing up until you reload the page manually.

And if you then return to the cart, you get the same 'out of stock'-error twice.

I've got this problem on multiple different WooCommerce-installations.

**To Reproduce**
1. Add product to cart.
2. Set this product to be 'out of stock'.
3. Proceed to checkout. No error.
4. Reload checkout-page. Error shows up.
5. Return to chart. Same error appears twice.

**Expected behavior**
Checkout page should show 'out of stock'-error. Same error shouldn't appear twice.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

WordPress address (URL): https://tessanda.ch
Site address (URL): https://tessanda.ch
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_CH
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.1.28 - Wir empfehlen
PHP Version 7.2 oder höher für mehr Leistung und Sicherheit zu verwenden. So aktualisieren Sie Ihre PHP-Version

PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.7.23-log-cll-lve
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: wp_
Datenbank-Gesamtgrösse: 16.70MB
Datenbank-Datengrösse: 11.17MB
Datenbank-Indexgrösse: 5.53MB
wp_woocommerce_sessions: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Daten: 0.09MB + Index: 0.13MB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB
wp_comments: Daten: 0.08MB + Index: 0.09MB
wp_links: Daten: 0.02MB + Index: 0.02MB
wp_litespeed_img_optm: Daten: 0.02MB + Index: 0.09MB
wp_litespeed_optimizer: Daten: 0.02MB + Index: 0.03MB
wp_nf3_actions: Daten: 0.02MB + Index: 0.00MB
wp_nf3_action_meta: Daten: 0.02MB + Index: 0.00MB
wp_nf3_chunks: Daten: 0.02MB + Index: 0.00MB
wp_nf3_fields: Daten: 0.02MB + Index: 0.00MB
wp_nf3_field_meta: Daten: 0.06MB + Index: 0.00MB
wp_nf3_forms: Daten: 0.02MB + Index: 0.00MB
wp_nf3_form_meta: Daten: 0.02MB + Index: 0.00MB
wp_nf3_objects: Daten: 0.02MB + Index: 0.00MB
wp_nf3_object_meta: Daten: 0.02MB + Index: 0.00MB
wp_nf3_relationships: Daten: 0.02MB + Index: 0.00MB
wp_nf3_upgrades: Daten: 0.02MB + Index: 0.00MB
wp_options: Daten: 1.13MB + Index: 0.05MB
wp_postmeta: Daten: 7.52MB + Index: 4.02MB
wp_posts: Daten: 1.50MB + Index: 0.41MB
wp_termmeta: Daten: 0.02MB + Index: 0.03MB
wp_terms: Daten: 0.02MB + Index: 0.03MB
wp_term_relationships: Daten: 0.05MB + Index: 0.02MB
wp_term_taxonomy: Daten: 0.02MB + Index: 0.03MB
wp_usermeta: Daten: 0.03MB + Index: 0.03MB
wp_users: Daten: 0.02MB + Index: 0.05MB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Daten: 0.05MB + Index: 0.09MB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB

### Post Type Counts ###

acf-field: 27
acf-field-group: 5
attachment: 1034
event: 4
nav_menu_item: 5
nf_sub: 34
oembed_cache: 1
page: 11
post: 2
product: 257
product_variation: 10
revision: 634
scheduled-action: 14
shop_order: 71

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (16) ###

Advanced Custom Fields: Ninjaforms Add-on: von Danny van Holten – 1.1
Admin Menu Editor: von Janis Elsts – 1.8.8
Advanced Custom Fields PRO: von Elliot Condon – 5.7.13
BackWPup: von Inpsyde GmbH – 3.6.8
Clean Image Filenames: von Upperdog – 1.2.1
Disable Comments: von Samir Shah – 1.9.0
Disable Emojis (GDPR friendly): von Ryan Hellyer – 1.7.2
Email Address Encoder: von Till Krüss – 1.0.19
Ninja Forms: von Die WP-Ninjas – 3.4.10
Safe SVG: von Daryll Doyle – 1.9.4
Simple Page Ordering: von Jake Goldman
10up – 2.3.2

WooCommerce Email Test: von RaiserWeb – 1.10 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce: von Automattic – 3.6.2
WooSwipe: von Thrive Website Design – 1.1.6.8
WP Force SSL: von Kostas Vrouvas – 1.4
WP HTML Mail: von Hannes Etzelstorfer – 2.9

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CHF (CHF)
Currency Position: left_space
Thousand Separator: '
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop-Basis: #43 - /shop/
Warenkorb: #109 - /shop/warenkorb/
Kasse: #111 - /shop/kasse/
Mein Konto: ❌ Seite nicht festgelegt
Allgemeine Geschäftsbedingungen: ❌ Seite nicht festgelegt

### Theme ###

Name: Tessanda
Version: 1.0
Author URL: http://clus.ch
Child Theme: ❌ – Wenn Sie WooCommerce mit einem Theme
das Sie nicht selbst entwickelt haben
an eigene Bedürfnisse anpassen
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie Sie ein Child-Theme erstellen (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: tessanda/woocommerce/cart/cart.php
tessanda/woocommerce/cart/mini-cart.php
tessanda/woocommerce/checkout/thankyou.php
tessanda/woocommerce/emails/customer-on-hold-order.php
tessanda/woocommerce/emails/email-styles.php
tessanda/woocommerce/single-product/related.php
tessanda/woocommerce/single-product/up-sells.php
tessanda/woocommerce/single-product.php

### Action Scheduler ###

Complete: 14
Oldest: 2019-05-06 09:24:16 +0200
Newest: 2019-05-06 09:25:14 +0200

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –
</details>

**Comment by kloon** [comment]
Please test with a default theme like Storefront or Twentyseventeen. I am unable to replicate this with just WooCommerce and Twentyseventeen active using the steps you suggested.

![](https://cld.wthms.co/CtDWAl+)
![](https://cld.wthms.co/iDkGlC+)

I will gladly reopen this issue if you can provide steps to replicate this with just WooCommerce active and a default theme.

**Comment by Walkeezy** [comment]
I did test it with Twenty Seventeen and all plugins disabled.

I get the same message on the checkout page as you @kloon, but the actual error only appears after a page reload. And if I then click on "Return to basket", I'm getting the errors twice on the cart page.

Checkout before page reload:
![checkout1](https://user-images.githubusercontent.com/11270687/57297771-cad55d80-70d0-11e9-8a2c-d1293f2e431b.jpg)

Checkout after page reload:
![checkout2](https://user-images.githubusercontent.com/11270687/57297775-cf017b00-70d0-11e9-9f0c-b04b2dc55fa6.jpg)

Cart, after returning to out from checkout:
![cart](https://user-images.githubusercontent.com/11270687/57297780-d163d500-70d0-11e9-9614-fa7ecd4d1d62.jpg)

**Comment by Walkeezy** [comment]
Can you reproduce this, @kloon? Any chance to get this reopened?

**Comment by kloon** [comment]
We can take another look, but as per my previous screenshots, I was unable to replicate this.

**Comment by kloon** [comment]
OK, I can confirm the double notices. Will work on a fix for the next release.

**Comment by Walkeezy** [comment]
Thank you very much!

**Comment by kloon** [comment]
See #23791 for fix.
