### ISSUE TITLE
Invalid parameter error while adding shipping_lines to create order API as per document

### ISSUE THREAD

**Issue by devdodiya** [woocommerce/woocommerce#23636]
I am using wc/v3 version of API and PHP as platform, currently i can get data with get requests i just tried creating order using the api as per the doc 

https://woocommerce.github.io/woocommerce-rest-api-docs/#create-an-order

i am just testing for now so i just copied and paste the data as per doc but i got following error when i post the data

`[07-May-2019 06:39:45 UTC] PHP Fatal error:  Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: Error: Invalid parameter(s): shipping_lines [rest_invalid_param] in /home/gathhnaw/public_html/mapi/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:350
Stack trace:
#0 /home/gathhnaw/public_html/mapi/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(386): Automattic\WooCommerce\HttpClient\HttpClient->lookForErrors(Object(stdClass))
#1 /home/gathhnaw/public_html/mapi/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(422): Automattic\WooCommerce\HttpClient\HttpClient->processResponse()
#2 /home/gathhnaw/public_html/mapi/vendor/automattic/woocommerce/src/WooCommerce/Client.php(56): Automattic\WooCommerce\HttpClient\HttpClient->request('orders', 'POST', Array)
#3 /home/gathhnaw/public_html/mapi/create_order.php(46): Automattic\WooCommerce\Client->post('orders', Array)
#4 {main}
  thrown in /home/gathhnaw/public_html/mapi/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line 350`
 

This is the code i used 
`<?php
require __DIR__ . '/vendor/autoload.php';
use Automattic\WooCommerce\Client;
$wc = new Client(
    'store url', 
    'secret_key', 
    'secret',
	[
		'wp_api'  => true,
		'version' => 'wc/v3',
	]
);

$data = array();
$data = [
    'payment_method' => 'cod',
    'billing' => [
        'first_name' => 'test',
        'last_name' => 'test',
        'address_1' => 'test',
        'address_2' => 'test',
        'city' => 'test',
        'state' => 'test',
        'postcode' => '12345',
        'country' => 'IN',
        'email' => 'test@test.com',
        'phone' => '(555) 555-5555'
    ],
    'shipping' => [
        'first_name' => 'test',
        'last_name' => 'test',
        'address_1' => 'test',
        'address_2' => 'test',
        'city' => 'test',
        'state' => 'test',
        'postcode' => '12345',
        'country' => 'IN',
        'email' => 'test@test.com',
        'phone' => '(555) 555-5555'
    ],
    'line_items' => [
        [
            'product_id' => 9436,
            'quantity' => 2
        ],
        [
            'product_id' => 9437,
            'quantity' => 1
        ]
    ],
    'shipping_lines' => [
        [
            'method_id' => 'flat_rate',
            'method_title' => 'Flat Rate',
            'total' => 10
        ]
    ]
];
print_r($wc->post('orders', $data));
exit;
`**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

Home URL: https://minutebag.com
Site URL: https://minutebag.com
WC Version: 3.5.7
Log Directory Writable: ✔
WP Version: 5.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.17
PHP Post Max Size: 512 MB
PHP Time Limit: 3000
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.23-MariaDB-log-cll-lve
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.2
WC Database Prefix: wpw7_
MaxMind GeoIP Database: ✔
Total Database Size: 56.50MB
Database Data Size: 41.18MB
Database Index Size: 15.32MB
wpw7_woocommerce_sessions: Data: 1.71MB + Index: 0.05MB
wpw7_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wpw7_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wpw7_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wpw7_woocommerce_order_items: Data: 0.93MB + Index: 0.45MB
wpw7_woocommerce_order_itemmeta: Data: 6.28MB + Index: 4.64MB
wpw7_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wpw7_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wpw7_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wpw7_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wpw7_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wpw7_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wpw7_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wpw7_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wpw7_alm: Data: 0.00MB + Index: 0.00MB
wpw7_atum_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wpw7_atum_order_items: Data: 0.00MB + Index: 0.00MB
wpw7_commentmeta: Data: 0.00MB + Index: 0.01MB
wpw7_comments: Data: 1.42MB + Index: 0.49MB
wpw7_contactformmaker: Data: 0.13MB + Index: 0.00MB
wpw7_contactformmaker_blocked: Data: 0.02MB + Index: 0.00MB
wpw7_contactformmaker_submits: Data: 0.00MB + Index: 0.00MB
wpw7_contactformmaker_themes: Data: 0.55MB + Index: 0.00MB
wpw7_contactformmaker_views: Data: 0.00MB + Index: 0.00MB
wpw7_EWD_OTP_Customers: Data: 0.00MB + Index: 0.00MB
wpw7_EWD_OTP_Custom_Fields: Data: 0.00MB + Index: 0.00MB
wpw7_EWD_OTP_Fields_Meta: Data: 0.00MB + Index: 0.00MB
wpw7_EWD_OTP_Orders: Data: 0.00MB + Index: 0.00MB
wpw7_EWD_OTP_Order_Statuses: Data: 0.00MB + Index: 0.00MB
wpw7_EWD_OTP_Sales_Reps: Data: 0.00MB + Index: 0.00MB
wpw7_ewwwio_images: Data: 0.00MB + Index: 0.00MB
wpw7_ionic_ecommerce_app_lang_settings: Data: 0.00MB + Index: 0.00MB
wpw7_ionic_ecommerce_banner_settings: Data: 0.00MB + Index: 0.00MB
wpw7_ionic_ecommerce_data: Data: 2.03MB + Index: 0.02MB
wpw7_ionic_ecommerce_labels: Data: 0.01MB + Index: 0.00MB
wpw7_ionic_ecommerce_label_value: Data: 0.02MB + Index: 0.01MB
wpw7_links: Data: 0.00MB + Index: 0.00MB
wpw7_mstoreapp_wishlist: Data: 0.00MB + Index: 0.00MB
wpw7_options: Data: 2.23MB + Index: 0.30MB
wpw7_paytm_donation: Data: 0.02MB + Index: 0.02MB
wpw7_pmxi_files: Data: 0.00MB + Index: 0.00MB
wpw7_pmxi_history: Data: 0.00MB + Index: 0.00MB
wpw7_pmxi_images: Data: 0.03MB + Index: 0.01MB
wpw7_pmxi_imports: Data: 0.00MB + Index: 0.00MB
wpw7_pmxi_posts: Data: 0.00MB + Index: 0.00MB
wpw7_pmxi_templates: Data: 0.00MB + Index: 0.00MB
wpw7_postmeta: Data: 15.47MB + Index: 6.63MB
wpw7_posts: Data: 5.06MB + Index: 0.78MB
wpw7_shopmagic_log_data: Data: 0.00MB + Index: 0.00MB
wpw7_social_users: Data: 0.01MB + Index: 0.01MB
wpw7_termmeta: Data: 0.03MB + Index: 0.03MB
wpw7_terms: Data: 0.01MB + Index: 0.03MB
wpw7_term_relationships: Data: 0.08MB + Index: 0.18MB
wpw7_term_taxonomy: Data: 0.01MB + Index: 0.02MB
wpw7_tmsuserscontacts: Data: 0.00MB + Index: 0.00MB
wpw7_tmsusersprofiles: Data: 0.00MB + Index: 0.00MB
wpw7_usermeta: Data: 4.63MB + Index: 1.29MB
wpw7_users: Data: 0.23MB + Index: 0.23MB
wpw7_wcpdf_invoice_number: Data: 0.02MB + Index: 0.02MB
wpw7_wc_cancel_orders: Data: 0.02MB + Index: 0.00MB
wpw7_wc_download_log: Data: 0.00MB + Index: 0.00MB
wpw7_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wpw7_woo_wallet_transactions: Data: 0.08MB + Index: 0.03MB
wpw7_woo_wallet_transaction_meta: Data: 0.03MB + Index: 0.03MB
wpw7_wplc_chat_msgs: Data: 0.02MB + Index: 0.00MB
wpw7_wplc_chat_sessions: Data: 0.02MB + Index: 0.00MB
wpw7_wplc_offline_messages: Data: 0.02MB + Index: 0.00MB
wpw7_wplc_webhooks: Data: 0.02MB + Index: 0.00MB
wpw7_yith_wapo_groups: Data: 0.00MB + Index: 0.00MB
wpw7_yith_wapo_types: Data: 0.00MB + Index: 0.00MB
wpw7_yoast_seo_links: Data: 0.02MB + Index: 0.01MB
wpw7_yoast_seo_meta: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 3350
blocks: 1
feedback: 1
ig_message: 8
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 14
oembed_cache: 2
page: 14
post: 5
product: 1625
product_variation: 221
revision: 952
shop_order: 1710
wpcf7_contact_form: 2
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Akismet Anti-Spam: by Automattic – 4.1.1
Contact Form 7 - Phone mask field: by Ruslan Heorhiiev – 1.2
Click to Chat for WhatsApp: by HoliThemes – 1.6
Contact Form 7: by Takayuki Miyoshi – 5.1.1
Facebook for WooCommerce: by Facebook – 1.9.8 – Not tested with the active version of WooCommerce
Ionic Ecommerce: by vectorcoder – 2.4
JSON API: by Dan Phiffer – 1.1.1
Nextend Social Login: by Nextendweb – 3.0.17
Product Sales Report for WooCommerce: by Potent Plugins – 1.4.8 – Not tested with the active version of WooCommerce
W3 Total Cache: by Frederick Townes – 0.9.7.3
WC Cancel Order: by Vikram Singh – 2.8
Checkout Field Editor for WooCommerce: by ThemeHiGH – 1.3.1
WooCommerce Wallet: by Subrata Mal – 1.3.2
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.2.11
WooCommerce: by Automattic – 3.5.7 – 3.6.2 is available

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #28 - /shop/
Cart: #29 - /cart/
Checkout: #30 - /checkout/
My account: #31 - /my-account/
Terms and conditions: #166 - /privacy-policy/

### Theme ###

Name: Flatsome
Version: 3.6.0
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php version 3.1.0 is out of date. The core version is 3.5.0
flatsome/woocommerce/cart/cart.php version 3.4.0 is out of date. The core version is 3.5.0
flatsome/woocommerce/checkout/form-checkout.php version 3.0.0 is out of date. The core version is 3.5.0
flatsome/woocommerce/checkout/form-coupon.php version 3.4.0 is out of date. The core version is 3.4.4
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php version 3.4.0 is out of date. The core version is 3.5.0
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php version 3.3.0 is out of date. The core version is 3.5.0
flatsome/woocommerce/notices/notice.php version 1.6.4 is out of date. The core version is 3.5.0
flatsome/woocommerce/notices/success.php version 3.3.0 is out of date. The core version is 3.5.0
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php version 3.3.2 is out of date. The core version is 3.5.1
flatsome/woocommerce/single-product/product-thumbnails.php version 3.3.2 is out of date. The core version is 3.5.1
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php version 1.6.4 is out of date. The core version is 3.5.0
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php version 3.2.0 is out of date. The core version is 3.5.0
flatsome/woocommerce/single-product.php

Outdated Templates: ❌
</details>

**Comment by brennick** [comment]
@devdodiya were you able to resolve this? I am having the same problem.

**Comment by devdodiya** [comment]
No unfortunately i didn't but i found a workaround i.e. i created a seperete api in php and used wocommerce php sdk's create order api

**Comment by brennick** [comment]
I was actually able to find a fix, you need to do `.toString()` on your price of the shipping rate.

**Comment by inpresif** [comment]
> toString

@brennick Thanks buddy. Helped me with API v3 and adding strval() for PHP
