### ISSUE TITLE
orders?status=partially-paid

### ISSUE THREAD

**Issue by nhcolcombr** [woocommerce/woocommerce#23639]
The API call does exclude all orders which already had an advanced status like 'wc-completed' in order history but were switched back to partially-paid (which might be necessary operationally)

If not intended I would consider it a bug.

**Comment by claudiosanches** [comment]
We don't support by default any `partially-paid` statuses, sounds like custom code, so probably you'll need to update it on the REST API as well.

**Comment by nhcolcombr** [comment]
yes, can be closed. I forgot this default request limit of 10 orders. 
The api works fine with any kind of order status.
