### ISSUE TITLE
WC 3.6: problem stock is decreased in "Order / Add order" when adding a product

### ISSUE THREAD

**Issue by flyingeyefr** [woocommerce/woocommerce#23637]
Hello, 

after upgrading to Woocommerce 3.6, we can't use anymore "Order / Add order" without messing up with our inventory because as soon as we add a product for a quotation in a new order, the quantity of stock is decreased: Even when status of the order is still 'on-hold' or any other equivalent status not paid. Stock should only be decreased when the order is validated by a payment. 

It was working fine before the upgrade. We had to fallback to 3.5.7. 

Please correct the bug.

Thank you
Regards

**Comment by beaulebens** [comment]
This is an intentional change in how Orders and Stock are handled, but a request for the ability to customize that functionality has been made in #23582. Please follow any changes there.
