### ISSUE TITLE
Either offers review or aggregateRating should be specified #22896

### ISSUE THREAD

**Issue by dougm1966** [woocommerce/woocommerce#23647]
I'm surprised all the thread on this subject are closed and marked fixed...They aren't. I'm running the current version of everything installed and still getting the errors in my google console.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by rodrigoprimo** [comment]
From [this comment](https://github.com/woocommerce/woocommerce/issues/22896#issuecomment-477074896) on the original issue:

> Missing aggregateRating/ratings is a warning. If your product doesn't have reviews, of course this data is missing. WooCommerce cannot make up review content for you :)

I will close this issue as it doesn't seem to be a problem. If I'm missing something, please leave a comment with more details and all the information requested in the bug report template and I will take a second look.
