### ISSUE TITLE
Filter for adding custom column to export feature is not triggering

### ISSUE THREAD

**Issue by baselbers** [woocommerce/woocommerce#23644]
Function "add_export_data" is not getting triggered.

```
/**
 * Add the custom column to the exporter and the exporter column menu.
 *
 * @param array $columns
 * @return array $columns
 */
function add_export_column( $columns ) {

	// column slug => column name
	$columns['custom_column'] = 'Custom Column';

	return $columns;
}
add_filter( 'woocommerce_product_export_column_names', 'add_export_column' );
add_filter( 'woocommerce_product_export_product_default_columns', 'add_export_column' );

/**
 * Provide the data to be exported for one item in the column.
 *
 * @param mixed $value (default: '')
 * @param WC_Product $product
 * @return mixed $value - Should be in a format that can be output into a text file (string, numeric, etc).
 */
function add_export_data( $value, $product ) {
	$value = get_permalink( $product->get_id() );
	return $value;
}
// Filter you want to hook into will be: 'woocommerce_product_export_product_column_{$column_slug}'.
add_filter( 'woocommerce_product_export_product_column_custom_column', 'add_export_data', 10, 2 );
```

WC Version: 3.6.2
WP Version: 5.1.1

**Comment by claudiosanches** [comment]
I just tested your code and works just fine.
Note that doesn't exists any filter by default called `woocommerce_product_export_column_names`.

Also works exporting only this "Custom Column", and when importing all fields as well.
Not sure if the code you provided here is the final implementation, but may happen if hooking those functions too late on WooCommerce.

**Comment by Rafiqul-Islam-Rafiq** [comment]
Filter you want to hook into will be: `'woocommerce_product_export_product_column_{$column_slug}'`.

So if your custom column name is `product_brand`, then `add_filter` will be like:
     
    add_filter( 'woocommerce_product_export_product_column_product_brand', 'add_export_data', 10, 2 );
  
    function add_export_data( $value, $product ) {
       $value = $product->get_meta( 'product_brand', true, 'edit' );
       return $value;
    }

If your custom column name is `brands`, then `add_filter` will be like:

    add_filter( 'woocommerce_product_export_product_column_brands', 'add_export_data', 10, 2 );

    function add_export_data( $value, $product ) {
       $value = $product->get_meta( 'brands', true, 'edit' );
       return $value;
    }

**Comment by pinguluk** [comment]
> Filter you want to hook into will be: `'woocommerce_product_export_product_column_{$column_slug}'`.
> 
> So if your custom column name is `product_brand`, then `add_filter` will be like:
> 
> ```
> add_filter( 'woocommerce_product_export_product_column_product_brand', 'add_export_data', 10, 2 );
> 
> function add_export_data( $value, $product ) {
>    $value = $product->get_meta( 'product_brand', true, 'edit' );
>    return $value;
> }
> ```
> 
> If your custom column name is `brands`, then `add_filter` will be like:
> 
> ```
> add_filter( 'woocommerce_product_export_product_column_brands', 'add_export_data', 10, 2 );
> 
> function add_export_data( $value, $product ) {
>    $value = $product->get_meta( 'brands', true, 'edit' );
>    return $value;
> }
> ```

Missed that too, thanks.
