### ISSUE TITLE
Broken Links in Captions for Product Image and Product Gallery

### ISSUE THREAD

**Issue by bradleysa** [woocommerce/woocommerce#23641]
After updating WooCommerce, links in image captions are displaying HTML code for Product image and Product gallery. 

You can see the issue by visiting a product and clicking on the little magnifying glass in the upper right corner of the featured image.

For more information, please see:
https://wordpress.org/support/topic/broken-links-in-captions-for-product-image-and-product-gallery/

Scrennshot:
https://cld.wthms.co/h0dKcn

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by kloon** [comment]
Can confirm this is a bug, I assume we are escaping to avoid a security issue but I tested WP's image captions and it allows HTML markup like links and headings so we should probably also allow this.

**Comment by kloon** [comment]
After evaluating this and looking at the options the only way to enable this functionality again would be to open up a previously fixed XSS security issue which we do not want to do.

With that, we feel that supporting HTML in captions is also not a standard thing to do, and to avoid any potential security issue stemming from that we are going with the decision to only support text as it is now.

If there is really a big demand for this we might revisit this and look into adding limited HTML support

**Comment by bradleysa** [comment]
Previously, HTML worked in the captions for WooCommerce.

WordPress has supported HTML in image captions since WordPress 3.4. 

It is disappointing that, without warning, a WooCommerce update stopped supporting HTML in the image captions.

And now, as I understand the situation, I will need to manually edit each caption to remove the broken HTML links.

Although this outcome is disappointing, I can trust and respect the logic behind the decision.

Thank you for investigating this issue and all your support.

**Comment by claudiosanches** [comment]
> WordPress has supported HTML in image captions since WordPress 3.4.

But WordPress doesn't output those captions in JS like WooCommerce does using Photoswipe library, we changed it due a security concern.

**Comment by bradleysa** [comment]
Thanks again @kloon, @claudiosanches, and all.
