### ISSUE TITLE
Coupon code with ampersand is inconsistent between logged in user and guest

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#23655]
**Describe the bug**
When we create a coupon with a ampersand in the code (ex: `a&a`), it works for a logged in user, but not for a guest user. If we create a coupon with the html representation of a ampersand in the code (ex: `b&amp;b), it works for guest users but not for logged in users.

**To Reproduce**
1. Create a coupon with code `a&a`
2. Create a coupon with code `b&amp;b`
3. Add a product to the cart as a logged in user
4. Apply the coupon `a&a` in the cart, and see that the coupon is applied
5. Apply the coupon `b&b` in the cart, and we get a message that it doesn't exist
6. Add a product to the cart when not logged in (guest user)
7. Apply the coupon `a&a` in the cart, and we get a message that it doesn't exist
8. Apply the coupon `b&b` in the cart, and see that the coupon is applied

**Screenshots**
Logged in user: 
![image](https://user-images.githubusercontent.com/11388669/57383470-c8453780-71a6-11e9-8626-df4369e0e619.png)

Guest user:
![image](https://user-images.githubusercontent.com/11388669/57383483-cf6c4580-71a6-11e9-97d0-a13cf4acd008.png)

**Expected behavior**
In both scenario's I'd expect to receive consistent results. It seems when the coupon object loaded, the difference is that the ID is 0, which causes the following check to fail:
https://github.com/woocommerce/woocommerce/blob/3.6.2/includes/class-wc-discounts.php#L586

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

```
WordPress 5.2
WooCommerce 3.6.2
Storefront 2.4.6
```
</details>

**Comment by rodrigoprimo** [comment]
Thanks for the detailed report, @mikkamp.

Sharing here some more details about this problem as I did investigate it but run out of time to implement a solution:

- The inconsistency is not between logged in users and guest users. It is between users without permission to add HTML (guest users and all users in the customer role) and users with permission to add HTML (admins, for example).
- This inconsistency is caused by `wc_format_coupon_code()` which is called [here](https://github.com/woocommerce/woocommerce/blob/e12e4aaa257b3ac5e60c1845bab51d53b2ee6c52/includes/class-wc-ajax.php#L209):

```
$ wp shell --user=1 // admin user
>>> wc_format_coupon_code( 'b&b' )
=> "b&b"

$ wp shell --user=2 // customer
>>> wc_format_coupon_code( 'b&b' )
=> "b&amp;b"
```

**Comment by madeincosmos** [comment]
Also reported in 12931527-hc

**Comment by dougaitken** [comment]
Similar/same as 2048091-zen / 9968221-hc

**Comment by tammullen** [comment]
Re-opening as PR is still open.

**Comment by htdat** [comment]
2998851-zen

**Comment by jessLundie** [comment]
And 3069301-zen

**Comment by simplenotezy** [comment]
Would love to have this fixed. Huge issues for our website

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by simplenotezy** [comment]
@konamiman is it fixed?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Konamiman** [comment]
@simplenotezy yes, it's fixed: https://github.com/woocommerce/woocommerce/pull/27140 - it's planned for inclusion in WooCommerce 4.5.

**Comment by simplenotezy** [comment]
@Konamiman great! Actually, now I am in doubt. Is it related to https://github.com/woocommerce/woocommerce/issues/26899? Perhaps not?

**Comment by Konamiman** [comment]
That other one doesn't seem to be related, but we won't be sure until we triage it.
