### ISSUE TITLE
[API] Expose more user attributes by customers endpoints

### ISSUE THREAD

**Issue by lukas0184** [woocommerce/woocommerce#23652]
I would like to propose to expose some additional user attributes by the customers API. I'm thinking about website and biographic info. These are of course native Wordpress user attributes, but having them available also by Woo API would be useful. How do you see this?

**Comment by claudiosanches** [comment]
Those attributes are already available in the users endpoint in WP API, you can fetch all data from there.

**Comment by claudiosanches** [comment]
Closing since we don't intend to replace or be an option for any WP API endpoint.
