### ISSUE TITLE
Filter by attribute

### ISSUE THREAD

**Issue by andersonand** [woocommerce/woocommerce#23661]
When a variable product linked to a product zeroes the stock the product remains marked with the taxonomy of the variance attribute. So when doing a filter search the products out of stock appear in the search and when choosing the option the customer can not buy because there is no longer this variation, you have a way to remove the attribute of this variation automatically when zeroing the stock?

**Comment by kloon** [comment]
The only option would be to hide out of stock product from your store. You can enable this via WooCommerce -> Settings -> Product -> Inventory tab in WP-Admin
![](https://cld.wthms.co/HX2zYH+)

**Comment by andersonand** [comment]
this does not happen with variations. Each variation has its stock when the variation zero the variation attribute remains in the product, so when I use a filter the product keeps appearing, if I remove the attribute manually the product some of the filter, this could be automatic.

**Comment by andersonand** [comment]
this does not happen with variations. Each variation has its stock when the stock of variation is equal to zero the attribute of the variation remains in the product, so when I use a filter the product keeps appearing, if I remove the attribute manually the product some of the filter, this could be automatic.

**Comment by andersonand** [comment]
This does not work with variations. Each variation has its stock and when the stock of variation is equal to zero the variation attribute remains in the product, so when I use a filter the product keeps appearing, if I remove the attribute manually the product disappears from the search with filters, this could be automatic.
