### ISSUE TITLE
Question: How to use wc_transaction_query in WooCommerce REST API?

### ISSUE THREAD

**Issue by stefanos82** [woocommerce/woocommerce#23662]
I use `wc-api-php` as my Client API and have built an app that synchronizes a customer's POS system with WooCommerce.

I have noticed how heavy it is and decided to build a mechanism to split the thousands of products in groups and queued each group, process the necessary data, discard what's not useful, and post it on website.

The problem is the following: for each group of 10 products, it takes approximately 14 seconds to finish.

I have looked for an alternative methodology and have found [`wc_transaction_query`](https://wp-kama.com/filecode/woocommerce/includes/wc-core-functions.php#L1283-1303).

I honestly didn't know it existed and still have no idea how to use it as there's no actual example with a working demo.

How can I use it? Is there any hook that REST API calls before and after a `restapi->post()` is being executed? I would like to enclose post() inside `BEGIN TRANSACTION / COMMIT` for performance improvements.

I use `restapi->post('products/batch', $data);` and I would like to send or update bulks of data on daily basis.

I have worked with nearly 1300 products and didn't like what I got for performance results.

I don't want to imagine what will happen with the total amount of 68000 products I need to send on the website...

**Comment by kloon** [comment]
@stefanos82 wc_transaction_query is just a wrapper for starting, committing and rolling back a MySQL DB transaction. Using that will not speed things up, the use of that is to just ensure you avoid data integrity when performing certain DB operations, IE placing an order to ensure you do not have multiple orders being placed at once for a product that only has one item in stock.

The wrapper is not implemented for the API or products so unfortunately not usable via the API. Using  the products/batch endpoint is definitely the way to go for speed. However you omitted some details in your issue like what version of WooCommerce you are using and a sample of the data you are posting.

In 3.6 we sped up product creation considerably so if not already running 3.6 I would suggest you upgrade. Also when posting product data, if you post image URLs this will slow things down a lot as the image will then be downloaded remotely and added to the product, that remote request is what slows product creation and updates down a lot so look at that.

Hope you come right in speeding things up, would love to hear if any of those things worked for you.

**Comment by stefanos82** [comment]
I use the latest WordPress and WooCommerce versions available.

I don't upload any photos, only standard product data, such as price, stock, description, and such.

Unfortunately, "batch" does not work as I expected, because I measured the time a single product takes to get pushed on the website and it's more or less the same with batch if we consider dividing each group per 10 products; that is, for a single product it takes up to 1.5 seconds to get pushed onto the website and 14-ish seconds for 10 products with batch.

I guess I have no other option than to build my own custom endpoint and setup a custom mechanism to access my database directly and push my data all at once.

**Comment by kloon** [comment]
If possible try setting up some profiling on a test site and running these commands to see where the bottleneck is. It is possible that it could be related to a plugin or theme doing something.

In my tests creating a product averages around 600ms when not posting an image, I get the same when calling WP endpoints, this is on a test site with 25k products.

**Comment by stefanos82** [comment]
If I may ask, are you using an SSD as your hard drive? If yes, that should be it; I use a standard hard drive.

**Comment by kloon** [comment]
Yes, I have SSD drives in my machine, although this is from a Virtual Machine running on my machine, but guess that also contributes to the speed. What are the speeds you are getting when creating a regular WP post via the API?

**Comment by stefanos82** [comment]
I haven't tried to create a regular post to be honest with you, only WooCommerce products as I am using the WooCommerce Client API to do so.

I don't think I can do such test with it.

**Comment by stefanos82** [comment]
OK, I have tried to create a normal post from inside my dashboard and it takes 1.3s for creation and for a brand new product 1.7s...

**Comment by kloon** [comment]
OK, thanks for testing and confirming. This shows the issues might be related to your server setup, network or even a plugin or theme on your site. Unfortunately not much we can do about that inside our codebase.

**Comment by stefanos82** [comment]
OK @kloon thank you very much, I will see what other alternatives I can test.

One last thing: can we demonstrate somewhere the actual use of `wc_transaction_query` so I can rest my curiosity?

I really want to see how can anyone populate multiple data at once.

I'm asking because on my project I use SQLite as my middleware that filters the necessary data and I populate 68,000 products in 0.3s thanks to `BEGIN TRANSACTION / COMMIT`.

**Comment by kloon** [comment]
Unfortunately, there is no way to use wc_transaction_query on the API at present as it needs to be implemented in our data store classes. We have toyed with using it hence why it is there, but it turned out to cause too many issues and slowing down performance in some cases hence why we removed the use of it. It was only used on checkout to ensure we were not causing issues with overselling stock.

**Comment by stefanos82** [comment]
@kloon quick update: I have synchronized my syncing app with an actual demo website I have setup on a VPS and the results were really mind blowing: 1.8s to 2s for creating a batch of 10 products and around 0.4s to 0.6s to update a batch of 10 products.

Please bear in mind that I have tried this on a VM Windows 7 with 4GB RAM and 2-core CPU and performed this fast. I cannot imagine how much faster it will execute when I will test it on a real hardware setup with 8GB RAM, SSD drive, and high upload business line internet speed.

I guess we need to let people know that working on SATA disks is now considered a drawback and should be upgraded to SSD drives for higher performance and faster results produced.
