### ISSUE TITLE
Looking Extended API for brands Plugin with Woocommerce Rest API

### ISSUE THREAD

**Issue by manigopal** [woocommerce/woocommerce#23664]
Brands API works but i do look for filter kind of API, 

Say for eg. products?category=15 @ here this API displays / filters products which are mapped to particular category.

As mentioned above i do look for the same
eg. products?brand=62 which is an extended API, which is now(not working)

But /wc/v2/brands => this works fine by displaying the brands list.

**Comment by kloon** [comment]
Hi @manigopal you will have to contact support of the Brands plugin you are using and ask about integration for filtering. WooCommerce core does not control that, that is something that will have to be added to the plugin to order to have support for it.

If this is the plugin sold via WooCommerce.com then please contact WooCommerce support via https://woocommerce.com/contact-us/
