### ISSUE TITLE
WooCommerce Partial Refunds 

### ISSUE THREAD

**Issue by sebhanz** [woocommerce/woocommerce#23667]
Hi Woo, 

I am trying to export partially refunded order (product level) but the export from Woo using API does not return product info. Just refund amount. 

Is there any way I can include refunded item info without using reason field?

**Comment by kloon** [comment]
Please provide an example of your API call? Your payload and perhaps the full cURL command if possible. This can help us debug issues and troubleshoot, without info like that we are pretty much in the dark.

**Comment by sebhanz** [comment]
@kloon 

Request 
GET http://dev.zynk.com/wordpress/wp-json/wc/v2/orders?per_page=20&page=1&status=processing&oauth_consumer_key=ck_3fe636347a28d8fed7be7327c5ce253667c6230c&oauth_nonce=9b0ea3ce0e594efb935cc501ebed5815&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1557399090&oauth_signature=uXY9QOAn4hDE3zgkWpg6cmpEcyQ%3D HTTP/1.1
Accept: application/json, application/xml, text/json, text/x-json, text/javascript, text/xml, application/json, text/json, text/x-json, text/javascript


Responce: JSON

![image](https://user-images.githubusercontent.com/8062151/57448556-9210c200-7251-11e9-86a1-a1d18c0f1f05.png)

**Comment by sebhanz** [comment]
UI: 

![image](https://user-images.githubusercontent.com/8062151/57448617-b66c9e80-7251-11e9-982f-ac621da683cc.png)

**Comment by kloon** [comment]
OK, thanks. As per the documentation, you will see that orders will only return the refund ID https://woocommerce.github.io/woocommerce-rest-api-docs/?php#order-refunds-properties

You will then need to hit the refunds endpoint with that ID which will have the product details for that specific refund https://woocommerce.github.io/woocommerce-rest-api-docs/?php#retrieve-a-refund

**Comment by sebhanz** [comment]
But partial refunds stay Completed/Processing. 
Refunds endpoint refunds everything in the order

**Comment by kloon** [comment]
No, the refunds endpoint can also do partial refunds. Also you will not use the refunds endpoint to do a refund, you mentioned you want to retrieve the refund details right? So you will call the orders endpoint first which give you the results as per your screenshot and then you will use that ID under the refunds section which is 65 and then call the refunds endpoint using a GET method with that ID, ie wp-json/wc/v3/orders/<order_id>/refunds/<refund_id>

**Comment by sebhanz** [comment]
Hi Kloon, 

Can you tell me if WooCommerce is planning on adding a filter when it comes to downloading orders from Woo via Api. Currently, it downloads all orders but this is not the most efficient way as the website with 60k orders takes over 4 hours to download orders.
