### ISSUE TITLE
Product filter placeholders (select2) are not customisable

### ISSUE THREAD

**Issue by fprati** [woocommerce/woocommerce#23668]
Product filters by attributes are widgets provided by woocommerce to use them in sidebar areas.

The 'dropdown' version always includes the keyword '**any**' (and their equivalent in other languages), but they are not customisable, i.e., they cannot be removed or modified.

How to reproduce-
For instance, define a product attribute such as color and use it to filter products by color in the woocomemrce shop sidebar. If you choose the 'dropdown' setting you will see in your sidebar the filter 'Any color'. I would have no mean to change it to 'Color', for instance, or 'All Colors'.

Potential ugly fix-
One can try and do that with some jquery and modify the element afterwards, but, apart from the ugly patch, you would have to put a delay because the select2 code kicks in after the document is ready and the visitor would be able to see the original text superseeded by the new one.

**Comment by kloon** [comment]
There is already a filter in place to change the Any value on the products attribute filter widget, give the `woocommerce_layered_nav_any_label` filter a try.
