### ISSUE TITLE
‘Out of Stock’ figure on Dashboard is including binned products

### ISSUE THREAD

**Issue by ConsoleMAD** [woocommerce/woocommerce#23676]
**Describe the bug**
This is only a minor issue, but I thought I’d mentioned it in case it’s not supposed to be this way. The ‘Woocommerce Status’ dashboard widget has a count of the Out of Stock items and this has been working for me for months. However, in recent weeks, I’d noticed the count creeping up and up. I initially thought it was a caching issue, but I just couldn’t get the count accurate.

Every now and again I’ll clear out all the binned products from the site and it was only then did the count eventually correct itself. I’m pretty sure this count did not include binned items before?

**To Reproduce**
1. Note that two items are listed as out of stock on the widget
2. Move one product to the bin > the widget still lists two products
3. Delete the product from the bin > one product in stock

**Expected behavior**
Ideally, the widget should only count items that are published

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://www.consolemad.co.uk
Site address (URL): https://www.consolemad.co.uk
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.3.5
PHP Post Max Size: 64 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.36

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.39-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: 6h7FVX_
MaxMind GeoIP Database: ✔
Total Database Size: 145.34MB
Database Data Size: 92.61MB
Database Index Size: 52.73MB
6h7FVX_woocommerce_sessions: Data: 1.23MB + Index: 0.03MB
6h7FVX_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
6h7FVX_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
6h7FVX_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
6h7FVX_woocommerce_order_items: Data: 0.94MB + Index: 0.51MB
6h7FVX_woocommerce_order_itemmeta: Data: 8.09MB + Index: 4.91MB
6h7FVX_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
6h7FVX_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
6h7FVX_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
6h7FVX_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
6h7FVX_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
6h7FVX_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
6h7FVX_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
6h7FVX_woocommerce_log: Data: 0.00MB + Index: 0.00MB
6h7FVX_aiowps_events: Data: 0.00MB + Index: 0.00MB
6h7FVX_aiowps_failed_logins: Data: 0.21MB + Index: 0.07MB
6h7FVX_aiowps_global_meta: Data: 0.00MB + Index: 0.00MB
6h7FVX_aiowps_login_activity: Data: 0.02MB + Index: 0.01MB
6h7FVX_aiowps_login_lockdown: Data: 0.00MB + Index: 0.00MB
6h7FVX_aiowps_permanent_block: Data: 0.00MB + Index: 0.00MB
6h7FVX_commentmeta: Data: 0.02MB + Index: 0.03MB
6h7FVX_comments: Data: 4.52MB + Index: 3.92MB
6h7FVX_cp_feeds: Data: 0.00MB + Index: 0.00MB
6h7FVX_links: Data: 0.02MB + Index: 0.02MB
6h7FVX_mywebtonetperfstatsresults: Data: 0.00MB + Index: 0.00MB
6h7FVX_mywebtonetqtest: Data: 0.00MB + Index: 0.00MB
6h7FVX_nextend2_image_storage: Data: 0.00MB + Index: 0.00MB
6h7FVX_nextend2_section_storage: Data: 0.00MB + Index: 0.01MB
6h7FVX_nextend2_smartslider3_generators: Data: 0.00MB + Index: 0.00MB
6h7FVX_nextend2_smartslider3_sliders: Data: 0.01MB + Index: 0.00MB
6h7FVX_nextend2_smartslider3_sliders_xref: Data: 0.00MB + Index: 0.00MB
6h7FVX_nextend2_smartslider3_slides: Data: 0.02MB + Index: 0.00MB
6h7FVX_options: Data: 6.42MB + Index: 1.20MB
6h7FVX_postmeta: Data: 49.48MB + Index: 31.86MB
6h7FVX_posts: Data: 9.50MB + Index: 3.36MB
6h7FVX_termmeta: Data: 0.03MB + Index: 0.03MB
6h7FVX_terms: Data: 0.02MB + Index: 0.03MB
6h7FVX_term_relationships: Data: 0.41MB + Index: 0.22MB
6h7FVX_term_taxonomy: Data: 0.06MB + Index: 0.03MB
6h7FVX_usermeta: Data: 3.52MB + Index: 4.02MB
6h7FVX_users: Data: 0.14MB + Index: 0.14MB
6h7FVX_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB
6h7FVX_wc_download_log: Data: 0.00MB + Index: 0.00MB
6h7FVX_wc_product_meta_lookup: Data: 0.38MB + Index: 0.56MB
6h7FVX_wc_webhooks: Data: 0.00MB + Index: 0.00MB
6h7FVX_wfBadLeechers: Data: 0.00MB + Index: 0.00MB
6h7FVX_wfBlockedCommentLog: Data: 0.00MB + Index: 0.00MB
6h7FVX_wfBlockedIPLog: Data: 0.00MB + Index: 0.00MB
6h7FVX_wfBlocks: Data: 0.00MB + Index: 0.00MB
6h7FVX_wfBlocks7: Data: 0.00MB + Index: 0.00MB
6h7FVX_wfBlocksAdv: Data: 0.00MB + Index: 0.00MB
6h7FVX_wfConfig: Data: 1.16MB + Index: 0.01MB
6h7FVX_wfCrawlers: Data: 0.00MB + Index: 0.00MB
6h7FVX_wfFileChanges: Data: 0.00MB + Index: 0.00MB
6h7FVX_wfFileMods: Data: 1.95MB + Index: 0.39MB
6h7FVX_wfHits: Data: 2.33MB + Index: 0.51MB
6h7FVX_wfHoover: Data: 0.00MB + Index: 0.00MB
6h7FVX_wfIssues: Data: 0.00MB + Index: 0.01MB
6h7FVX_wfKnownFileList: Data: 1.06MB + Index: 0.12MB
6h7FVX_wfLeechers: Data: 0.09MB + Index: 0.07MB
6h7FVX_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB
6h7FVX_wfLockedOut: Data: 0.00MB + Index: 0.00MB
6h7FVX_wfLocs: Data: 0.00MB + Index: 0.00MB
6h7FVX_wfLogins: Data: 0.11MB + Index: 0.03MB
6h7FVX_wfNet404s: Data: 0.00MB + Index: 0.00MB
6h7FVX_wfNotifications: Data: 0.05MB + Index: 0.01MB
6h7FVX_wfPendingIssues: Data: 0.00MB + Index: 0.00MB
6h7FVX_wfReverseCache: Data: 0.00MB + Index: 0.00MB
6h7FVX_wfScanners: Data: 0.01MB + Index: 0.01MB
6h7FVX_wfSNIPCache: Data: 0.00MB + Index: 0.00MB
6h7FVX_wfStatus: Data: 0.11MB + Index: 0.05MB
6h7FVX_wfThrottleLog: Data: 0.00MB + Index: 0.00MB
6h7FVX_wfTrafficRates: Data: 0.02MB + Index: 0.00MB
6h7FVX_wfVulnScanners: Data: 0.00MB + Index: 0.00MB
6h7FVX_wpmcleaner: Data: 0.00MB + Index: 0.00MB
6h7FVX_yoast_seo_links: Data: 0.21MB + Index: 0.09MB
6h7FVX_yoast_seo_meta: Data: 0.43MB + Index: 0.44MB

### Post Type Counts ###

accordion_menu: 1
attachment: 4495
cs_footer: 1
cs_user_templates: 1
ct_afc: 1
nav_menu_item: 204
oembed_cache: 1
page: 31
post: 173
product: 3058
revision: 219
scheduled-action: 18
shop_coupon: 4
shop_order: 3715
shop_order_refund: 46
tablepress_table: 1
was: 1
wpcf7_contact_form: 2
wpforms: 2
x-email-forms: 1
x-portfolio: 17

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

All-in-One WP Migration: by ServMask – 6.93
Classic Editor: by WordPress Contributors – 1.5
Contact Form 7: by Takayuki Miyoshi – 5.1.1
Google Tag Manager for Wordpress: by Thomas Geiger – 1.9.2 – Not tested with the active version of WooCommerce
Enable Media Replace: by ShortPixel – 3.2.9
Flexible Shipping: by WP Desk – 3.3.12
Head & Footer Code: by Aleksandar Urosevic – 1.0.9.1
WPBakery Page Builder: by Michael M - WPBakery.com – 5.7
Nextend Accordion Menu: by Nextend – 9.3.11
Nextend: by Nextend – 1.3.11
Post Types Order: by Nsp Code – 1.9.3.9
Quick Alt Editor: by Arsmoon – 1.0.1
Responsive Lightbox & Gallery: by dFactory – 2.1.0
Shortcoder: by Aakash Chakravarthy – 4.4
TablePress: by Tobias Bäthge – 1.9.2
Featured Image Thumbnail Grid: by A. R. Jones – 6.6.1
GDPR Cookie Consent Banner: by termly – 2.3.14
Ultimate Posts Widget: by Boston Dell-Vandenberg – 2.0.7
Widget Logic: by wpchefgadget
alanft – 5.9.0

WooCommerce Currency Converter: by WooCommerce – 1.6.13
WooCommerce Stripe Gateway: by WooCommerce – 4.1.16
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.2.12
WooCommerce Royal Mail: by WooCommerce – 2.5.15
WooCommerce: by Automattic – 3.6.2
Wordfence Security: by Wordfence – 7.2.5
Yoast SEO: by Team Yoast – 11.1.1 – Not tested with the active version of WooCommerce
WP Crontrol: by John Blackbourn & contributors – 1.7.1
WP Rocket: by WP Media – 3.3.2
X – Custom 404: by Themeco – 1.1.3
X – Email Forms (MailChimp): by Themeco – 1.1.2

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php

### Must Use Plugins (1) ###

1&1 Product Subdomain: by 1&1 – 1.0.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6280 - /shop/
Basket: #10 - /basket/
Checkout: #11 - /checkout/
My account: #12 - /my-account/
Terms and conditions: #33972 - /terms-and-conditions/

### Theme ###

Name: Pro – Child Theme - ConsoleMAD
Version: 1.0.0
Author URL: http://theme.co/
Child Theme: ✔
Parent Theme Name: Pro
Parent Theme Version: 2.5.5
Parent Theme Author URL: http://theme.co/
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file. You will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.
Overrides: pro/woocommerce/cart/cross-sells.php
pro/woocommerce/loop/loop-end.php
pro/woocommerce/loop/loop-start.php
pro/woocommerce/loop/pagination.php
pro/woocommerce/notices/error.php
pro/woocommerce/notices/notice.php
pro/woocommerce/notices/success.php
consolemad/woocommerce/single-product/meta.php
pro/woocommerce/single-product/related.php
pro/woocommerce/single-product/tabs/tabs.php
pro/woocommerce/single-product/up-sells.php
pro/woocommerce/single-product-reviews.php version 3.5.0 is out of date. The core version is 3.6.0

Outdated Templates: ❌
					
					
						Learn how to update

### Action Scheduler ###

Complete: 17
Oldest: 2019-04-17 21:30:02 +0100
Newest: 2019-05-08 21:30:02 +0100

Pending: 1
Oldest: 2019-05-15 21:30:02 +0100
Newest: 2019-05-15 21:30:02 +0100

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by hannahswain** [comment]
Cross-link to original forum post:
https://wordpress.org/support/topic/out-of-stock-figure-on-dashboard-is-including-binned-products/

I was able to reproduce using WooCommerce `3.6.2` and Storefront.

**Comment by kloon** [comment]
Have you tested this logged out also?

**Comment by ConsoleMAD** [comment]
I didn't think it was possible to access dashboard widgets without being logged in?

**Comment by kloon** [comment]
Sorry about that, misread the part that this was in WP-Admin. Will take a look.

**Comment by kloon** [comment]
See #23676 for fix.
