### ISSUE TITLE
Inventory Management Rules Conflict

### ISSUE THREAD

**Issue by PaulKaan** [woocommerce/woocommerce#23679]
Inventory Management Rules do not follow logical sequence if an order is created in Admin and then a customer logins in to pay for the order. The error message insufficient stock for order shows at checkout.

**To Reproduce**
Create a product
Add Stock eg 6 units
Product is set to manage stock and not allow back orders
Product is set to be in Catalogue and Search
Create an order in admin 
Add the product x 4 units
Stock is depleted automatically x 4 units
Stock is still positive with 2 units left but at value less than the number of units ordered
Order status is Pending Payment
Customer logins and attempts to pay for order
Checkout returns error that the is not enough stock
If change stock management to allow back orders the payment will go through
The stock is not reduced and remains at the correct level

**Expected behavior**
The customer should be able to pay for the order and the error message regarding insufficient stock should not show as the stock has already been depleted and accounted for.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://winedecoded.com.au
Site address (URL): https://winedecoded.com.au
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.5
PHP Post Max Size: 16 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.0.38-MariaDB
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
Zapier Integration - Active Feeds: ✔ 4 active Zapier Feeds.
Zapier Integration - Cron Tasks: ✔ 0 pending Zapier cron tasks.
Zapier Feed #1 Name: ✔ Create a new google contact and add to Wine Decoded Customers Group
Zapier Feed #1 Webhook URL: ✔ https://hooks.zapier.com/hooks/catch/3217075/ffoylv/
Zapier Feed #1 Trigger: ✔ New Customer
Zapier Feed #1 Test Result: ✔ Successfully sent sample data to https://hooks.zapier.com/hooks/catch/3217075/ffoylv/.
Zapier Feed #2 Name: ✔ Payment is received send SMS
Zapier Feed #2 Webhook URL: ✔ https://hooks.zapier.com/hooks/catch/3217075/ffoe7j/
Zapier Feed #2 Trigger: ✔ New Order Status Change
Zapier Feed #2 Test Result: ✔ Successfully sent sample data to https://hooks.zapier.com/hooks/catch/3217075/ffoe7j/.
Zapier Feed #3 Name: ✔ New Order add to list
Zapier Feed #3 Webhook URL: ✔ https://hooks.zapier.com/hooks/catch/3217075/ffovu4/
Zapier Feed #3 Trigger: ✔ New Order
Zapier Feed #3 Test Result: ✔ Successfully sent sample data to https://hooks.zapier.com/hooks/catch/3217075/ffovu4/.
Zapier Feed #4 Name: ✔ Add Customers to Group
Zapier Feed #4 Webhook URL: ✔ https://hooks.zapier.com/hooks/catch/3217075/aywc1u/
Zapier Feed #4 Trigger: ✔ New Customer
Zapier Feed #4 Test Result: ✔ Successfully sent sample data to https://hooks.zapier.com/hooks/catch/3217075/aywc1u/.

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: wp_
Total Database Size: 129.54MB
Database Data Size: 80.09MB
Database Index Size: 49.45MB
wp_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.56MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 1.34MB + Index: 1.95MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_automatewoo_abandoned_carts: Data: 0.01MB + Index: 0.01MB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.06MB
wp_automatewoo_events: Data: 0.00MB + Index: 0.01MB
wp_automatewoo_guests: Data: 0.00MB + Index: 0.01MB
wp_automatewoo_guest_meta: Data: 0.00MB + Index: 0.00MB
wp_automatewoo_logs: Data: 0.00MB + Index: 0.00MB
wp_automatewoo_log_meta: Data: 0.00MB + Index: 0.01MB
wp_automatewoo_queue: Data: 0.00MB + Index: 0.00MB
wp_automatewoo_queue_meta: Data: 0.00MB + Index: 0.00MB
wp_automatewoo_referrals: Data: 0.00MB + Index: 0.00MB
wp_automatewoo_referral_advocate_keys: Data: 0.00MB + Index: 0.00MB
wp_automatewoo_referral_invites: Data: 0.00MB + Index: 0.01MB
wp_automatewoo_unsubscribes: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 3.52MB + Index: 2.59MB
wp_ewwwio_images: Data: 4.52MB + Index: 4.72MB
wp_ewwwio_queue: Data: 0.00MB + Index: 0.00MB
wp_failed_jobs: Data: 0.00MB + Index: 0.00MB
wp_gf_addon_feed: Data: 0.00MB + Index: 0.00MB
wp_gf_draft_submissions: Data: 0.00MB + Index: 0.00MB
wp_gf_entry: Data: 0.08MB + Index: 0.01MB
wp_gf_entry_meta: Data: 0.47MB + Index: 0.35MB
wp_gf_entry_notes: Data: 0.00MB + Index: 0.00MB
wp_gf_form: Data: 0.01MB + Index: 0.00MB
wp_gf_form_meta: Data: 1.99MB + Index: 0.00MB
wp_gf_form_revisions: Data: 0.00MB + Index: 0.00MB
wp_gf_form_view: Data: 1.70MB + Index: 0.82MB
wp_glossary_related: Data: 0.00MB + Index: 0.01MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.01MB + Index: 0.00MB
wp_options: Data: 8.34MB + Index: 1.02MB
wp_postmeta: Data: 21.55MB + Index: 12.91MB
wp_posts: Data: 12.42MB + Index: 3.08MB
wp_queue: Data: 0.00MB + Index: 0.00MB
wp_rcp_discounts: Data: 0.00MB + Index: 0.00MB
wp_rcp_payments: Data: 0.00MB + Index: 0.00MB
wp_rcp_payment_meta: Data: 0.00MB + Index: 0.00MB
wp_rcp_subscription_level_meta: Data: 0.00MB + Index: 0.00MB
wp_redirection_404: Data: 1.95MB + Index: 0.52MB
wp_redirection_groups: Data: 0.00MB + Index: 0.00MB
wp_redirection_items: Data: 0.00MB + Index: 0.02MB
wp_redirection_logs: Data: 0.00MB + Index: 0.01MB
wp_relevanssi: Data: 12.50MB + Index: 16.67MB
wp_relevanssi_log: Data: 0.07MB + Index: 0.06MB
wp_relevanssi_stopwords: Data: 0.00MB + Index: 0.00MB
wp_restrict_content_pro: Data: 0.00MB + Index: 0.00MB
wp_rg_form: Data: 0.00MB + Index: 0.00MB
wp_rg_form_meta: Data: 1.00MB + Index: 0.00MB
wp_rg_form_view: Data: 0.48MB + Index: 0.23MB
wp_rg_incomplete_submissions: Data: 0.00MB + Index: 0.00MB
wp_rg_lead: Data: 0.03MB + Index: 0.01MB
wp_rg_lead_detail: Data: 0.08MB + Index: 0.14MB
wp_rg_lead_detail_long: Data: 0.00MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.07MB + Index: 0.02MB
wp_rg_lead_notes: Data: 0.00MB + Index: 0.00MB
wp_say_what_available_strings: Data: 0.84MB + Index: 0.00MB
wp_say_what_strings: Data: 0.01MB + Index: 0.00MB
wp_say_what_wildcards: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.17MB + Index: 0.23MB
wp_terms: Data: 0.11MB + Index: 0.16MB
wp_term_relationships: Data: 1.42MB + Index: 0.39MB
wp_term_taxonomy: Data: 0.25MB + Index: 0.14MB
wp_usermeta: Data: 1.47MB + Index: 1.89MB
wp_users: Data: 0.08MB + Index: 0.05MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_gpf_render_cache: Data: 0.00MB + Index: 0.00MB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.10MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_bundled_itemmeta: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_bundled_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_gpf_google_taxonomy: Data: 0.86MB + Index: 0.00MB
wp_woocommerce_shipping_table_rates: Data: 0.01MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.57MB + Index: 0.11MB
wp_yoast_seo_meta: Data: 0.21MB + Index: 0.21MB

### Post Type Counts ###

acf-field: 147
acf-field-group: 25
attachment: 3227
aw_workflow: 1
course: 1
dmc_slider: 1
dmc-offer: 122
dmc-slider: 1
glossary: 49
jetpack-testimonial: 7
lesson: 6
nav_menu_item: 48
oembed_cache: 192
page: 39
post: 116
product: 907
product_variation: 267
quiz: 6
revision: 1
scheduled-action: 904
shop_coupon: 28
shop_order: 645
shop_order_refund: 10
wc_membership_plan: 3
wc_user_membership: 379
wc_zapier_feed: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (49) ###

ManageWP - Worker: by GoDaddy – 4.7.7
VaultPress: by Automattic – 1.9.10
Gravity Forms: by rocketgenius – 2.4.9
CM Tooltip Glossary Ecommerce: by CreativeMindsSolutions – 3.8.14
Admin Columns Pro - Advanced Custom Fields (ACF): by Admin Columns – 2.5.2
Admin Columns Pro - WooCommerce: by Admin Columns – 3.3.3
Advanced Custom Fields: Gravityforms Add-on: by Danny van Holten – 1.2.1
Advanced Custom Fields: Smart Button: by Gilles Goetsch – 1.0.0
Admin Columns Pro: by AdminColumns.com – 4.5.8
Advanced Custom Fields PRO: by Elliot Condon – 5.8.0
Akismet Anti-Spam: by Automattic – 4.1.1
AutomateWoo - Referrals Add-on: by Prospress – 2.3.2 – Not tested with the active version of WooCommerce
AutomateWoo: by Prospress – 4.5.1
Classic Editor: by WordPress Contributors – 1.5
Dynamic SVG Icons: by Phil Kurth – 1.0
EWWW Image Optimizer: by Exactly WWW – 4.7.4
Force Strong Passwords: by Jason Cosper – 1.8.0
Google Universal Analytics: by Audrius Dobilinskas – 2.4.3
Gravity Forms MailChimp Add-On: by rocketgenius – 4.6
Jetpack by WordPress.com: by Automattic – 7.3.0
Mailchimp for WooCommerce: by Mailchimp – 2.1.15 – Not tested with the active version of WooCommerce
Post Duplicator: by Metaphor Creations – 2.20
Redirection: by John Godley – 4.2.3
Relevanssi Premium: by Mikko Saari – 2.2.5
Say What? Pro: by Lee Willis – 2.3.0
WooCommerce Shippit: by Shippit Pty Ltd – 1.4.7 – Not tested with the active version of WooCommerce
Simple Custom Post Order: by Colorlib – 2.4.3
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.18
WooCommerce Cost of Goods: by SkyVerge – 2.8.3
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.13 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.1.16
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.9
WooCommerce Gravity Forms Product Add-Ons: by Lucas Stark – 3.3.8 – Not tested with the active version of WooCommerce
WooCommerce Memberships: by SkyVerge – 1.13.0
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.6
WooCommerce Mix and Match: by Kathy Darling – 1.5.0
WooCommerce Print Invoices/Packing Lists: by SkyVerge – 3.6.4
WooCommerce Product Add-ons: by WooCommerce – 3.0.11
WooCommerce Smart Coupons: by StoreApps – 4.0.3 – Not tested with the active version of WooCommerce
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.15
WooCommerce Variation Swatches and Photos: by Lucas Stark – 3.0.12
WooCommerce Zapier Integration: by OM4 – 1.8.3
WooCommerce: by Automattic – 3.6.2
Yoast SEO: by Team Yoast – 11.1.1 – Not tested with the active version of WooCommerce
WP Migrate DB Pro Theme & Plugin Files: by Delicious Brains – 1.0.5
WP Migrate DB Pro: by Delicious Brains – 1.9.7
WP Rocket: by WP Media – 3.3.2
WP Thumb: by Human Made Limited – 0.10
Wined Mix and Match: by Oscar Gare – 1.2.0

### Inactive Plugins (4) ###

Reduce stock of manual orders for WooCommerce: by Claudio Sanches – 2.0.0 – Not tested with the active version of WooCommerce
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.1
Wine Decoded | HoneyBadger Integration: by Phil Kurth –
WooCommerce Google Product Feed: by Ademti Software Ltd. – 7.8.7

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (3) ###

load.php: by  –
ManageWP - Worker Loader: by ManageWP –
WP Migrate DB Pro Compatibility: by Delicious Brains – 1.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
variable (variable)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: #25 - /terms-conditions/

### Theme ###

Name: Grunterie
Version: 5.0.0
Author URL: http://georgespake.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: wined/woocommerce/content-product.php
wined/woocommerce/content-single-product.php
wined/woocommerce/loop/loop-start.php
wined/woocommerce/single-product/add-to-cart/simple.php
wined/woocommerce/single-product/price.php

### Memberships ###

Restriction mode:: Hide content only
Public content:: –
Excluded from discounts:: –
Membership plans:: 3
The MEGA List for those who applied for the 2013 Produttori Cru Offer:: Members: 21Access method: Manual assignment onlyAccess length: Unlimited
Wine Decoded Wine Bites Subscription:: Members: 2Access method: Manual assignment onlyAccess length: Unlimited
Free for all our Wine Decoded Members:: Members: 356Access method: User account registrationAccess length: Unlimited

### Mix and Match Products ###

Template Overrides: –

### Action Scheduler ###

Complete: 902
Oldest: 2019-04-10 16:40:01 +1000
Newest: 2019-05-11 16:18:00 +1000

Pending: 2
Oldest: 2019-05-17 11:28:28 +1000
Newest: 2019-05-17 11:28:29 +1000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by kloon** [comment]
Hi, I am trying to replicate this but unable to. I see you have quite a lot of plugins active which might have some custom code that is adjusting the stock when you try and pay? Also whay payment gateway are you using when making the payment?

My tests with Stripe and and offline gateway like BACS does not produce the same results, stock is only adjusted when the items are added to the order via admin.

Could you please try and rule out a plugin conflict by disabling all plugins except WooCommerce and also switching your theme to a default one and test again?

**Comment by PaulKaan** [comment]
Thanks @kloon Will spin up staging and do more testing give me a couple of days to come back to you.

**Comment by kloon** [comment]
Closing the issue for now, will reopen when you have steps to replicate this after your testing on a staging server.
