### ISSUE TITLE
Regular and Sale Price field allows for the "-" non-numeric character

### ISSUE THREAD

**Issue by EtiennePoolman** [woocommerce/woocommerce#23696]
When entering a Sale or Regular Price on a product, non-numeric characters are not allowed and you get a notification of that;

![Screenshot](https://cld.wthms.co/aGOMub+)
Screenshot direct link: https://cld.wthms.co/aGOMub

However, when entering a `-`  character, it is allowed and you are able to save the product;

![Screenshot](https://cld.wthms.co/jSrWtH+)
Screenshot direct link: https://cld.wthms.co/jSrWtH

**To Reproduce**
Create or edit a product and add `-` in either the sale or regular price fields and save the product.

The product will then show on the frontend with a `0` price and when added to the cart, if `WP_DEBUG_DISPLAY` is set to true, it will show a warning next to the product's price;

![Screenshot](https://cld.wthms.co/jXpZvS+)
Screenshot direct link: https://cld.wthms.co/jXpZvS

**Expected behavior**
I expected not to be able to enter `-` in the price fields like other non-numeric characters

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment]
#23705 should trim any `-` inside product prices, this also should fix on front end some PHP warnings:

```
[14-May-2019 16:01:08 UTC] PHP Warning:  A non-numeric value encountered in wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php on line 235
[14-May-2019 16:01:08 UTC] PHP Warning:  A non-numeric value encountered in wp-content/plugins/woocommerce/includes/class-wc-discounts.php on line 85
[14-May-2019 16:01:09 UTC] PHP Warning:  A non-numeric value encountered in wp-content/plugins/woocommerce/includes/wc-product-functions.php on line 1017
```

**Comment by kloon** [comment]
See #23705
