### ISSUE TITLE
'post_date' is automatically updated on product->save()

### ISSUE THREAD

**Issue by eddr** [woocommerce/woocommerce#23691]
**Describe the bug**
1. 'post_date' field in 'wp_posts' is updated when a product is saved (->save()). 'post_date_gmt' is not updated.
2. Seems to take the 'post_date_gmt' and add the WP UTC configuration (like +2 hours)
3. In my case, I use 'post_date' for different timezones within the same WP installation, so this behavior is unwanted (and unexpected, why would it be automatic)
4. I guess, at least there should be an option for developers to turn it off easily and certainly it should appear in docs.

**To Reproduce**
1. Create a product
2. Set post_date in DB without timezone
3. in PHP, use wc_get_product to get the product object, change something like name
4. ->save()

**Expected behavior**
No automatic change for 'post_date'

**WordPress Environment**
WP 5.2, WC 3.6.2, NGINX, Ubuntu
</details>

**Comment by kloon** [comment]
post_date is always stored in the current timezone as your site is set, whereas post_date_gmt is stored in GMT format. This is not unique to WooCommerce but how WordPress does it as well with posts and pages.

If you want to handle timezones you should always use the post_date_gmt value and then add your timezone data on top. Even better is not to use the DB directly but use the CRUD functionality provided which has all the getters and setters.

$product->get_date_created( 'edit' )->getTimestamp() will return the GMT timestamp and then you can apply your timezone settings ontop of that.

The post_data and post_date_gmt fields are linked to the date_created, so if you change those fields directly in the db without changing the date_created value it will update the values again based on date_created.

I am not considering this as a bug. You should be able to achieve what you want with the fields and methods available, it is just understanding how they tie together. Have a look at the update method in the product datastore to see the logic https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-data-store-cpt.php#L195

**Comment by eddr** [comment]
Thanks Kloon. I do use the GMT, but there is also a value for the non-GMT (local notification mails). Anyway, there is also a sense in having different timezones for different posts

Thanks!
