### ISSUE TITLE
Coupons losing expiration date when updating to 3.6.2 from 3.5.2

### ISSUE THREAD

**Issue by SimonJThompson** [woocommerce/woocommerce#23692]
**Describe the bug**
We're in the process of running an overdue update from WooCommerce 3.5.2 to 3.6.2. In the process of testing, we noticed that all of the Coupon expiration dates had disappeared - both in the admin grid and the post edit screen.

From investigation, this seems to be due to our system storing the expiration metadata with the key "expiry_date", whereas it's now "date_expires". This historically wouldn't have been an issue as there was a fallback to the legacy key, however a change seems to have been introduced in [this commit](https://github.com/woocommerce/woocommerce/commit/111246771c7f1a2f2a8ce0cc514dc0c71d867475) which removed the fallback. As such, the meta keys cannot be found. We can fix this by running a manual SQL update statement to swap out the meta keys and all then seems to work as it used it.

Whilst the meta key change itself took place quite a while ago, raising it here as there doesn't seem to be any migration in wc-update-functions.php to swap the old key for the new.

**To Reproduce**
Steps to reproduce the behaviour:
1. Run a legacy version of WooCommerce which has coupons with expiry dates.
2. Update WooCommerce to 3.6.2+
3. View the Coupon list in the admin panel, and note the absence of expiration dates.

**Expected behavior**
When WooCommerce is updated, old "expiry_date" coupon meta keys should be updated to "date_expires".

**Comment by kloon** [comment]
The commit that actually breaks this is https://github.com/woocommerce/woocommerce/commit/5749369ba5#diff-e7d781803cc50186db925e225e7f0ceaL118

Will restore the backward compatibility check.

**Comment by kloon** [comment]
See #23714 for fix.
