### ISSUE TITLE
Dashboard edit address: Missing "Address_2" fields

### ISSUE THREAD

**Issue by Nicola1008** [woocommerce/woocommerce#23693]
**Describe the bug**
In the frontend the user can't edit "address_2" field because this field is missing

**To Reproduce**
1. Go to the webiste frontend
2. Log in as a customer
3. Go to the dashboard
4. Click on "Address"
5. If you have already compiled the "address_2" in the billing field you can see it but if you click on "Edit address" you can't edit it because the field is missing

**Screenshots**
![address-bug-1](https://user-images.githubusercontent.com/50591692/57639795-f9f83d00-75b0-11e9-8d27-b5c5ae5c3719.png)
![address-bug-2](https://user-images.githubusercontent.com/50591692/57639798-f9f83d00-75b0-11e9-8087-0d603c4625b1.png)

**Expected behavior**
The filed "address_2" under the field "addres_1" that can be edited.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://www.misternets.com
Site address (URL): https://www.misternets.com
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.2
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: Apache/2
PHP Version: 7.2.7
PHP Post Max Size: 48 MB
PHP Time Limit: 30
PHP Max Input Vars: 4000
cURL Version: 7.60.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.23-MariaDB
Max Upload Size: 48 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: wp_
Dimensione totale database: 51.67MB
Dimensione dati database: 33.32MB
Dimensione indice database: 18.35MB
wp_woocommerce_sessions: Dati: 1.02MB + Indice: 0.02MB
wp_woocommerce_api_keys: Dati: 0.02MB + Indice: 0.03MB
wp_woocommerce_attribute_taxonomies: Dati: 0.02MB + Indice: 0.02MB
wp_woocommerce_downloadable_product_permissions: Dati: 0.02MB + Indice: 0.06MB
wp_woocommerce_order_items: Dati: 0.02MB + Indice: 0.02MB
wp_woocommerce_order_itemmeta: Dati: 0.06MB + Indice: 0.03MB
wp_woocommerce_tax_rates: Dati: 0.02MB + Indice: 0.06MB
wp_woocommerce_tax_rate_locations: Dati: 0.02MB + Indice: 0.03MB
wp_woocommerce_shipping_zones: Dati: 0.02MB + Indice: 0.00MB
wp_woocommerce_shipping_zone_locations: Dati: 0.02MB + Indice: 0.03MB
wp_woocommerce_shipping_zone_methods: Dati: 0.02MB + Indice: 0.00MB
wp_woocommerce_payment_tokens: Dati: 0.02MB + Indice: 0.02MB
wp_woocommerce_payment_tokenmeta: Dati: 0.02MB + Indice: 0.03MB
wp_woocommerce_log: Dati: 0.02MB + Indice: 0.02MB
wp_akeeba_common: Dati: 0.02MB + Indice: 0.00MB
wp_ak_params: Dati: 0.02MB + Indice: 0.00MB
wp_ak_profiles: Dati: 0.02MB + Indice: 0.00MB
wp_ak_stats: Dati: 0.02MB + Indice: 0.03MB
wp_ak_storage: Dati: 0.05MB + Indice: 0.00MB
wp_ak_users: Dati: 0.02MB + Indice: 0.00MB
wp_commentmeta: Dati: 0.02MB + Indice: 0.03MB
wp_comments: Dati: 0.11MB + Indice: 0.09MB
wp_icl_content_status: Dati: 0.02MB + Indice: 0.02MB
wp_icl_core_status: Dati: 0.02MB + Indice: 0.02MB
wp_icl_flags: Dati: 0.02MB + Indice: 0.02MB
wp_icl_languages: Dati: 0.02MB + Indice: 0.03MB
wp_icl_languages_translations: Dati: 0.19MB + Indice: 0.09MB
wp_icl_locale_map: Dati: 0.02MB + Indice: 0.00MB
wp_icl_message_status: Dati: 0.02MB + Indice: 0.03MB
wp_icl_mo_files_domains: Dati: 0.02MB + Indice: 0.02MB
wp_icl_node: Dati: 0.02MB + Indice: 0.00MB
wp_icl_reminders: Dati: 0.02MB + Indice: 0.00MB
wp_icl_strings: Dati: 6.52MB + Indice: 5.05MB
wp_icl_string_packages: Dati: 0.08MB + Indice: 0.00MB
wp_icl_string_pages: Dati: 10.52MB + Indice: 6.52MB
wp_icl_string_positions: Dati: 0.02MB + Indice: 0.02MB
wp_icl_string_status: Dati: 0.02MB + Indice: 0.02MB
wp_icl_string_translations: Dati: 2.52MB + Indice: 1.52MB
wp_icl_string_urls: Dati: 0.05MB + Indice: 0.02MB
wp_icl_translate: Dati: 0.02MB + Indice: 0.02MB
wp_icl_translate_job: Dati: 0.02MB + Indice: 0.02MB
wp_icl_translations: Dati: 0.19MB + Indice: 0.41MB
wp_icl_translation_batches: Dati: 0.02MB + Indice: 0.00MB
wp_icl_translation_status: Dati: 0.02MB + Indice: 0.02MB
wp_links: Dati: 0.02MB + Indice: 0.02MB
wp_options: Dati: 3.25MB + Indice: 0.13MB
wp_pmxe_exports: Dati: 0.03MB + Indice: 0.00MB
wp_pmxe_google_cats: Dati: 0.39MB + Indice: 0.00MB
wp_pmxe_posts: Dati: 0.06MB + Indice: 0.00MB
wp_pmxe_templates: Dati: 0.02MB + Indice: 0.00MB
wp_postmeta: Dati: 4.52MB + Indice: 3.03MB
wp_posts: Dati: 1.52MB + Indice: 0.30MB
wp_revslider_css: Dati: 0.13MB + Indice: 0.00MB
wp_revslider_layer_animations: Dati: 0.02MB + Indice: 0.00MB
wp_revslider_navigations: Dati: 0.02MB + Indice: 0.00MB
wp_revslider_sliders: Dati: 0.03MB + Indice: 0.00MB
wp_revslider_slides: Dati: 0.11MB + Indice: 0.00MB
wp_revslider_static_slides: Dati: 0.02MB + Indice: 0.00MB
wp_smush_dir_images: Dati: 0.02MB + Indice: 0.03MB
wp_termmeta: Dati: 0.06MB + Indice: 0.03MB
wp_terms: Dati: 0.06MB + Indice: 0.03MB
wp_term_relationships: Dati: 0.14MB + Indice: 0.09MB
wp_term_taxonomy: Dati: 0.06MB + Indice: 0.03MB
wp_tm_taskmeta: Dati: 0.02MB + Indice: 0.03MB
wp_tm_tasks: Dati: 0.02MB + Indice: 0.02MB
wp_usermeta: Dati: 0.08MB + Indice: 0.03MB
wp_users: Dati: 0.02MB + Indice: 0.05MB
wp_wcpdf_invoice_number: Dati: 0.02MB + Indice: 0.00MB
wp_wc_download_log: Dati: 0.02MB + Indice: 0.03MB
wp_wc_product_meta_lookup: Dati: 0.08MB + Indice: 0.09MB
wp_wc_webhooks: Dati: 0.02MB + Indice: 0.02MB
wp_woopricesim_fields: Dati: 0.08MB + Indice: 0.00MB
wp_woopricesim_regex: Dati: 0.02MB + Indice: 0.00MB
wp_woopricesim_settings: Dati: 0.02MB + Indice: 0.00MB
wp_woopricesim_simulations: Dati: 0.17MB + Indice: 0.00MB
wp_woopricesim_simulators: Dati: 0.06MB + Indice: 0.00MB
wp_wpml_mails: Dati: 0.08MB + Indice: 0.00MB
wp_yoast_seo_links: Dati: 0.08MB + Indice: 0.02MB
wp_yoast_seo_meta: Dati: 0.08MB + Indice: 0.00MB

### Post Type Counts ###

attachment: 480
custom_css: 1
customize_changeset: 7
jetpack_migration: 2
mc4wp-form: 1
nav_menu_item: 54
page: 18
portfolio: 15
post: 2
product: 309
product_variation: 313
revision: 3
scheduled-action: 196
shop_order: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

WPML Multilingual CMS: by OnTheGoSystems – 4.2.6
Booster Plus for WooCommerce: by Algoritmika Ltd – 4.3.1 – Non testato con la versione attiva di WooCommerce
Contact Form 7: by Takayuki Miyoshi – 5.1.1
Google Tag Manager for Wordpress: by Thomas Geiger – 1.9.2
GDPR Cookie Compliance: by Moove Agency – 2.0.8
Improved Product Options for WooCommerce: by 7VX LLC
USA CA – 4.6.3 – Non testato con la versione attiva di WooCommerce

WPBakery Page Builder: by Michael M - WPBakery.com – 5.7
Kirki Toolkit: by Ari Stathopoulos (@aristath) – 3.0.39
Meta Box: by MetaBox.io – 4.18.0
Really Simple SSL: by Rogier Lankhorst
Mark Wolters – 3.1.5

Revolution Slider: by ThemePunch – 5.4.8.3
Safe SVG: by Daryll Doyle – 1.9.4
Sober Addons: by UIX Themes – 1.4.1
User Switching: by John Blackbourn e collaboratori – 1.5.0
WooCommerce P.IVA e Codice Fiscale per Italia PRO: by dot4all – 2.0.24 – Non testato con la versione attiva di WooCommerce
AWS Price Calculator: by Altos Web Solutions Italia – 2.4.4 – Non testato con la versione attiva di WooCommerce
WooCommerce Advanced Shipping By Rules: by Open Tools
Reinhold Kainhofer – 2.0.6 – Non testato con la versione attiva di WooCommerce

WooCommerce Stripe Gateway: by WooCommerce – 4.1.16 – Non testato con la versione attiva di WooCommerce
WooCommerce Multilingual: by OnTheGoSystems – 4.6.2.1 – Non testato con la versione attiva di WooCommerce
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.2.12 – Non testato con la versione attiva di WooCommerce
WooCommerce: by Automattic – 3.6.2
Yoast SEO: by Team Yoast – 11.1.1
WP Mail Logging: by Christian Zöller – 1.9.1
WP-MailUp: by MailUp and N. I. Biz Soft Solutions – 1.4.11
Smush: by WPMU DEV – 3.2.0.1
WP Super Cache: by Automattic – 1.6.5
WPML String Translation: by OnTheGoSystems – 2.10.4
WPML Translation Management: by OnTheGoSystems – 2.8.5
YITH WooCommerce Order Tracking: by YITH – 1.2.7 – Non testato con la versione attiva di WooCommerce

### Inactive Plugins (4) ###

a3 Lazy Load: by a3rev Software – 1.9.2
Akeeba Backup for WordPress: by Akeeba Ltd – 3.4.2.2
Soo Product Filter: by UIX Themes – 1.0.8 – Non testato con la versione attiva di WooCommerce
WPML Media: by OnTheGoSystems – 2.5.2

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

akeeba-backup-coreupdate.php: by  –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #2483 - /shop/
Carrello: #5 - /cart/
Cassa: #2452 - /checkout/
Il mio account: #2453 - /my-account/
Termini e condizioni: #2573 - /termini-e-condizioni/

### Theme ###

Name: Sober Child Theme
Version: 1.0.0
Author URL: http://uix.store
Child Theme: ✔
Parent Theme Name: Sober
Parent Theme Version: 2.1.4
Parent Theme Author URL: http://uix.store
WooCommerce Support: ✔

### Templates ###

Overrides: sober-child/woocommerce/cart/cart-shipping.php
sober/woocommerce/cart/cart.php
sober/woocommerce/cart/mini-cart.php
sober/woocommerce/checkout/form-checkout.php
sober/woocommerce/checkout/form-coupon.php
sober/woocommerce/checkout/form-login.php
sober/woocommerce/checkout/review-order.php
sober-child/woocommerce/emails/admin-new-order.php
sober-child/woocommerce/emails/email-header.php
sober-child/woocommerce/emails/email-order-details.php
sober-child/woocommerce/emails/email-styles.php
sober/woocommerce/global/form-login.php
sober/woocommerce/global/quantity-input.php
sober/woocommerce/global/wrapper-end.php
sober/woocommerce/global/wrapper-start.php
sober/woocommerce/loop/add-to-cart.php
sober/woocommerce/loop/price.php
sober/woocommerce/loop/result-count.php
sober/woocommerce/myaccount/dashboard.php
sober/woocommerce/myaccount/form-edit-account.php
sober/woocommerce/myaccount/form-login.php
sober/woocommerce/myaccount/my-address.php
sober/woocommerce/notices/error.php
sober/woocommerce/notices/success.php
sober/woocommerce/order/form-tracking.php
sober/woocommerce/single-product/add-to-cart/external.php
sober/woocommerce/single-product/add-to-cart/grouped.php
sober/woocommerce/single-product/add-to-cart/simple.php
sober/woocommerce/single-product/add-to-cart/variable.php
sober/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
sober/woocommerce/single-product/product-image.php
sober/woocommerce/single-product/product-thumbnails.php
sober/woocommerce/single-product/related.php
sober/woocommerce/single-product/review-meta.php
sober/woocommerce/single-product/tabs/additional-information.php
sober/woocommerce/single-product/tabs/tabs.php
sober/woocommerce/single-product/up-sells.php
sober/woocommerce/single-product-reviews.php

### Action Scheduler ###

Complete: 196
Oldest: 2019-04-13 19:23:02 +0200
Newest: 2019-05-11 11:35:17 +0200

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by claudiosanches** [comment]
This is not a bug... Probably you deactivate this field in the Customizer, see:

![Screenshot from 2019-05-14 13-29-57](https://user-images.githubusercontent.com/1264099/57715171-755afc80-764c-11e9-8395-0e0336add01e.png)

Just change to "Optional" or "Required" that this field should display again.

**Comment by Nicola1008** [comment]
I have the option set to "optional" so yes... I think that it is a bug

**Comment by claudiosanches** [comment]
So this don't sounds true:
![Screenshot from 2019-05-14 13-41-16](https://user-images.githubusercontent.com/1264099/57715808-f6ff5a00-764d-11e9-9721-c1652e0ad4b4.png)

I just tested in a clean install and I can't reproduce this issue, so sounds like that your theme or some plugin is hiding this field.
