### ISSUE TITLE
A non numeric value encountered type: warning

### ISSUE THREAD

**Issue by damianwebelevate** [woocommerce/woocommerce#23709]
**Describe the bug**
I am writing a plugin that creates a product type->works, on product creation user selects this new product type and adds a price and a value to increment.  Works also. On the front end interacting with number field to increment the amount value, by 0.01.  Need this as product has to be accurate to 2 decimal places.  Normal woocommerce add to cart button simply doesn't work.  I used two things here to help debug this problem as no php output was displayed (yes I set the errors to display in the wp_config, and also ini_set both on localhost and production server) 
Using Query Monitor for all calls to and from wordpress/server and Ajaz add to cart for woocommerce plugin(s) as the normal add to cart button is simply unresponsive to submit events.
Ajax add to cart throws three errors (see below)
See output from console log:
Object
component: "Plugin: carbon-calculator-vita"
file: "wp-content/plugins/carbon-calculator-vita/carbon-calculator-vita.php"
line: 306
message: "Undefined index: carbon_amount"
stack: (7) ["car_calc_add_cart_item()", "apply_filters('woocommerce_add_cart_item')", "WC_Cart->add_to_cart()", "WC_AJAX::add_to_cart()", "do_action('wc_ajax_add_to_cart')", "WC_AJAX::do_wc_ajax()", "do_action('template_redirect')"]
type: "notice"
__proto__: Object
query-monitor.js?ver=1557819859:324 
Object
component: "Plugin: woocommerce"
file: "wp-content/plugins/woocommerce/includes/class-wc-cart-totals.php"
line: 235
message: "A non-numeric value encountered"
stack: (11) ["WC_Cart_Totals->get_items_from_cart()", "WC_Cart_Totals->calculate_item_totals()", "WC_Cart_Totals->calculate()", "WC_Cart_Totals->__construct()", "WC_Cart->calculate_totals()", "do_action('woocommerce_add_to_cart')", "WC_Cart->add_to_cart()", "WC_AJAX::add_to_cart()", "do_action('wc_ajax_add_to_cart')", "WC_AJAX::do_wc_ajax()", "do_action('template_redirect')"]
type: "warning"
__proto__: Object
query-monitor.js?ver=1557819859:324 
Object
component: "Plugin: woocommerce"
file: "wp-content/plugins/woocommerce/includes/class-wc-discounts.php"
line: 85
message: "A non-numeric value encountered"
stack: (13) ["WC_Discounts->set_items_from_cart()", "WC_Discounts->__construct()", "WC_Cart_Totals->calculate_discounts()", "WC_Cart_Totals->calculate_item_totals()", "WC_Cart_Totals->calculate()", "WC_Cart_Totals->__construct()", "WC_Cart->calculate_totals()", "do_action('woocommerce_add_to_cart')", "WC_Cart->add_to_cart()", "WC_AJAX::add_to_cart()", "do_action('wc_ajax_add_to_cart')", "WC_AJAX::do_wc_ajax()", "do_action('template_redirect')"]
type: "warning"
__proto__: Object

I have tried already casting the call number_format(floatval($product->get_type()), 2,'.',''
But no avail and similarly to the step value that the user assigns.

**To Reproduce**
Go to:
http://damianorourke.com/vita/product/carbon-calculator/

Interact with number field and increment value

View console log for errors

Logged in the errors are as follows and the amount field was incremented by 6.00 in this case.

![logged_in](https://user-images.githubusercontent.com/6705250/57737250-d9a8ab00-76a2-11e9-886c-58f86ff20a3a.PNG)

As the display price is set to zero, and when user adds to cart the cart is empty ie 0.00 to pay.

![basket_logged_in](https://user-images.githubusercontent.com/6705250/57737637-46707500-76a4-11e9-939b-a836fe7d5c7e.PNG)

PHP 7.2.10 (localhost 7.2.27 live) Wordpress 5.2–en_GB, this version of woocommerce

[carbon-calculator-vita.zip](https://github.com/woocommerce/woocommerce/files/3180197/carbon-calculator-vita.zip)

Please install for more details.

**Expected behavior**
User increments number field and adds to cart

I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.

This bug happens with a default WordPress theme active, (used all of default themes and still error

I can reproduce this bug consistently using the steps above.

`
### WordPress Environment ###

WordPress address (URL): http://damianorourke.com/vita
Site address (URL): http://damianorourke.com/vita
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.27 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.43-cll-lve
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 0.84MB
Database Data Size: 0.72MB
Database Index Size: 0.12MB
wp_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_comments: Data: 0.00MB + Index: 0.01MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 0.70MB + Index: 0.04MB
wp_postmeta: Data: 0.00MB + Index: 0.01MB
wp_posts: Data: 0.01MB + Index: 0.01MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.00MB + Index: 0.00MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_usermeta: Data: 0.00MB + Index: 0.01MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 1
page: 6
post: 2
product: 1
scheduled-action: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (5) ###

Query Monitor: by John Blackbourn – 3.3.5
Carbon Calculator Vita: by Damian O'Rourke – 1.1.1
Ajax add to cart for WooCommerce: by QuadLayers – 1.1.0 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.20.0
WooCommerce: by Automattic – 3.6.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: carbon (carbon)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6 - /shop/
Basket: #7 - /basket/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Seventeen
Version: 2.2
Author URL: https://en-gb.wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 2
Oldest: 2019-04-30 23:31:44 +0100
Newest: 2019-05-11 22:58:07 +0100

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by kloon** [comment]
Add to cart abs int all quantity values by default. Have a look at the `woocommerce_stock_amount` filter, you will likely need to either unhook our absint call on that or add your own function to allow for decimal quantities.
