### ISSUE TITLE
Filter "woocommerce_valid_order_statuses_for_cancel" resulting in "Uncaught ArgumentCountError: Too few arguments to function"

### ISSUE THREAD

**Issue by EdithAllison** [woocommerce/woocommerce#23703]
**Describe the bug**
The filter "woocommerce_valid_order_statuses_for_cancel" is used twice in WooCommerce, once with 1 argument, once with 2 arguments. When used in a custom theme results in error : "Uncaught ArgumentCountError: Too few arguments to function ... "

**Current Woo Code**
File: /includes/wc-account-functions.php 
Line 289
`	if ( ! in_array( $order->get_status(), apply_filters( 'woocommerce_valid_order_statuses_for_cancel', array( 'pending', 'failed' ), $order ), true ) ) {`

File: /includes/class-wc-form-handler.php
Line 669
`			$order_can_cancel = $order->has_status( apply_filters( 'woocommerce_valid_order_statuses_for_cancel', array( 'pending', 'failed' ) ) );`

**Suggested fix**
Add missing 2nd argument
File: /includes/class-wc-form-handler.php
Line 669
`			$order_can_cancel = $order->has_status( apply_filters( 'woocommerce_valid_order_statuses_for_cancel', array( 'pending', 'failed' ), $order ) );`

**WordPress Environment**
WooCommerce 3.6.2
Fix tested in Multisite WP install with Woo 3.6.2

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #23704.
