### ISSUE TITLE
Username autogeneration

### ISSUE THREAD

**Issue by mark4986** [woocommerce/woocommerce#23700]
New function wc_create_new_customer_username, introduced in 3.6.0, has changed the way a username is autogenerated.  Instead of creating the username from the local part of the email, the username is now (by default) an amalgam of the user's first and last names.

I assume this update reflects the increasing internationalisation of characters used in email addresses? However:

1. auto generating the username from the user's names currently allows usernames to be created that conflict with Moodle (and presumably other similar duplicate registrations). E.g. it does not remove all spaces, where those spaces are within a name (e.g. when the user puts in 2 first names, rather than one).

2. auto generating the username from the user's names probably breaches GDPR rules, since the person now becomes fully recognisable from their username. 

3. The checkbox in 3.6.2 Woocommerce/settings/accounts and privacy still states: "When creating an account, automatically generate a username from the customer's email address": This is not what happens, unless generating a username from the user's names fails. 

Please can I request: 

1. an option is added to restrict auto-generated usernames to alphanumeric lower case characters, (whether based on email or user names), + supplementary digits to generate a unique username?

2. that when creating usernames from user's names, at least part of each of the user's names (e.g. first character?) are disregarded in creating a username?

3. a setting giving the option to generate usernames from either email OR user names is added and/or the current description for the checkbox is amended.

Thanks for a great WooCommerce plugin.

**Comment by claudiosanches** [comment]
You can just deactivate auto generation and let users choice they own usernames.
Also check https://github.com/woocommerce/woocommerce/pull/23672 that should allow you filter and modify the entire username generation.

**Comment by mark4986** [comment]
Thanks Claudio, for me the solution was even easier - which was to allow Moodle to enable use of custom usernames in Moodle.  Navigate to Site Administration > Security > Site Policies > Here enable 'Allow extended characters in usernames'. 

When combined with your suggestion I think that solves all the problems - although it adds n extra field to the customer journey.
