### ISSUE TITLE
Excluding product properties when using the product_duplicate() function

### ISSUE THREAD

**Issue by mrleemon** [woocommerce/woocommerce#23718]
Is there a way to use the `product_duplicate()` function in `WC_Admin_Duplicate_Product` to clone a product but not all of its properties? For example, I'd like to keep all the product properties when duplicating a product, except for its price. Is there a WC filter to exclude properties from being copied?

Thanks in advance

**Comment by kloon** [comment]
Filter to use is `woocommerce_duplicate_product_exclude_meta`

Fields to exclude for price would be _price, _regular_price  and _sale_price

**Comment by mrleemon** [comment]
Thanks!
