### ISSUE TITLE
Wordpress Importing variable products, not all variations are checked as 'use as variation'.

### ISSUE THREAD

**Issue by NielsBeres** [woocommerce/woocommerce#23715]
**Describe the bug**
I am not a native English speaker, so I am sorry for mistakes in my grammer.

If I upload a csv file the system recognizes the variations I added, but only uses the first variation it encounters to tick the box 'use for variation', the other two variations are not shown.

Attribute 1 name | Attribute 1 value(s) | Attribute 1 visible | Attribute 1 global

Maat (LxBxH)| 200cm x 110cm x 78cm, 220cm x 110cm x 78cm | 1 | 1

Maat (LxBxH) | 200cm x 110cm x 78cm | | 1

Maat (LxBxH) | 220cm x 110cm x 78cm | | 1

On the first line there are ofcourse the headers, then there is the first product line (variable) and then there are two (variation) lines for the child products.

In the same product there is this information:

Attribute 3 name | Attribute 3 value(s) | Attribute 3 visible | Attribute 3 global

Blad dikte | 2cm, 3cm, 4cm | 1 | 1

| | | 1

| | | 1

Because attribute 3 also has everything Global and in the first line all options are added (2, 3 and 4cm) the information is added to the product and the only thing I have to do is login to Wordpress and check the box 'use for variation'. But I dont have to do this for attribute 1 and ofcourse don't want to do this for attribute 3 for every product I have.

How do I fix this problem?

**To Reproduce**
Import this csv: http://oldambt-meubelen.skyberatedev.nl/git/Productlijst%20-%20Eiken%20Tafels.csv

**Screenshots**
oldambt-meubelen.skyberatedev.nl/git/UnusedforVariation.png
oldambt-meubelen.skyberatedev.nl/git/UsedforVariation.png
oldambt-meubelen.skyberatedev.nl/git/CSV.png

**Expected behavior**
I expect that just as attribute 1, Maat (LxBxH), also attribute 3, Blad dikte is used as variation on the product page.

**Isolating the problem (mark completed items with an [x]):**
- [ x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

`
### WordPress Environment ###

WordPress address (URL): http://www.oldambt-meubelen.skyberatedev.nl
Site address (URL): http://www.oldambt-meubelen.skyberatedev.nl
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.1.29 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 900
PHP Max Input Vars: 10000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 10.2.24-MariaDB
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 3.92MB
Database Data Size: 2.61MB
Database Index Size: 1.31MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_comments: Data: 0.00MB + Index: 0.01MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 0.84MB + Index: 0.05MB
wp_postmeta: Data: 0.99MB + Index: 0.49MB
wp_posts: Data: 0.22MB + Index: 0.09MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.01MB + Index: 0.01MB
wp_term_relationships: Data: 0.03MB + Index: 0.06MB
wp_term_taxonomy: Data: 0.01MB + Index: 0.01MB
wp_usermeta: Data: 0.07MB + Index: 0.02MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 193
customize_changeset: 15
nav_menu_item: 6
page: 7
post: 6
product: 67
product_variation: 400
revision: 6
scheduled-action: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (4) ###

Advanced Woocommerce Product Gallery Slider: by UnikInfotech – 1.0.0 – Not tested with the active version of WooCommerce
Kint Debugger: by Brian Fegter
Chris Dillon – 1.2

WooCommerce: by Automattic – 3.6.2
Yoast SEO: by Team Yoast – 11.1.1 – Not tested with the active version of WooCommerce

### Inactive Plugins (1) ###

WooCommerce Multilingual: by OnTheGoSystems – 4.6.2.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /shop/
Basket: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Guru Theme
Version: 1.0.0
Author URL: http://stuartduff.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.5.0
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2019-05-15 08:59:52 +0000
Newest: 2019-05-15 08:59:52 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

</details>

**Comment by kloon** [comment]
Your format seems incorrect [as per the documentation](https://docs.woocommerce.com/document/product-csv-import-suite-column-header-reference/#section-3) global attribute headings needs to start with `attribute: pa_` and then have the attribute name.

An easy way to get the right format would be to first create a single product with the attributes and variations and then do an export. You can then use this file to replicate the import.
