### ISSUE TITLE
Hook for Product Gallery

### ISSUE THREAD

**Issue by Sisanu** [woocommerce/woocommerce#23717]
I love the `Product gallery` feature and how easy it is to set up and order the images in the back-end for the products. As a developer, I would like to have more options for customizing/editing the images selected, directly from the product edit view. 

It could be useful a hook, a filter or an action in the actions markup for the thumbnail (the one that currently presents the delete option when hovering the image), if possible. It can be something generic like 
`do_action( 'woocommerce_product_gallery_item_edit', $thepostid, $attachment_id )`, to allow for adding other edit links/buttons for the image, or extra info if necessary.

Thank you,
Iulia

**Comment by kloon** [comment]
Hi, thanks for the suggestion. I have marked this as an enhancement. Feel free to open a PR with the suggested changes, otherwise, we will take a look closer to our next release date.

**Comment by claudiosanches** [comment]
See #23743
