### ISSUE TITLE
Woocommerce after product import csv hook

### ISSUE THREAD

**Issue by igorartzona** [woocommerce/woocommerce#23716]
Sorry, may be add "csv_product_import_end" hook in file:  
 [https://github.com/woocommerce/woocommerce/blob/master/includes/admin/importers/views/html-csv-import-done.php](url)

**Comment by kloon** [comment]
Hi, thanks for the suggestion. I have marked this as an enhancement. Feel free to open a PR with the suggested changes, otherwise, we will take a look closer to our next release date.
