### ISSUE TITLE
Shipping tax only calculated exclusive of tax

### ISSUE THREAD

**Issue by ThornedRose** [woocommerce/woocommerce#23710]
**Describe the bug**
Woocommerce shipping tax is hardcoded (wc-class-tax.php, line 89 `		$taxes = self::calc_exclusive_tax( $price, $rates );`) to be exclusive of tax. This means that when you need tax to be included in the shipping, you must enter shipping calculations exclusive of tax. This then leads to rounding errors in certain scenarios.

**To Reproduce**
As an example. In my country, the GST rate is 15%. This is charged on products as well as the shipping. So this tax needs to be calculated on shipping for legal tax purposes. If I use flat rate shipping at a calculation of $1 per item, I need to enter 0.87 ($1/1.15) into the flat rate settings.
![image](https://user-images.githubusercontent.com/239386/57745094-e28b9200-771f-11e9-9081-4e04aa7430e5.png)
However, this causes rounding issues. For example. If someone purchases 100 products at a shipping rate of $1 per item, the total shipping comes to $100.05 due to rounding.
![image](https://user-images.githubusercontent.com/239386/57745192-46ae5600-7720-11e9-90f7-92cfba47392c.png)
Now I can get around this by setting the flat rate shipping equation to `(1/1.15)*[qty]` but this does not completely solve the issue in all scenarios as you will see below. Unticking the shipping tax is also NOT an option, as again, for legal tax purposes, tax must be calculated on shipping and the amount of tax charged must be displayed (see above screenshot "includes $13.05 GST").

Here's a scenario in which the incorrect tax calculation causes issues (despite the `(1/1.5)*[qty]` accurately rounding in simple shipping transactions:
Using a code snippet to set a maximum shipping rate (feature request: add this functionality to the flat rate equations), the rounding causes the maximum shipping rate to behave erroneously - if I set a maximum cost of $3.50 shipping, 3 products calculates at $3 shipping correctly but 4 products incorrectly calculates at $4 shipping and is not set at the maximum of $3.50. Selecting 5 or more products then correctly sets the shipping to $3.50. Clearly a rounding issue.
More info here about this specific scenario: https://stackoverflow.com/questions/56108152/maximum-shipping-cost-woocommerce/

**Screenshots**
See above

**Expected behavior**
Woocommerce should have the option of displaying the shipping with tax exclusive OR inclusive of tax. i.e. you should be able to select that you want tax on shipping and then select whether you want that shipping calculated inclusive or exclusive of tax. That way, when shipping rates are entered, you can enter the rates exclusive or inclusive of tax. Or at the very least, shipping tax calculations should respect this option:
![image](https://user-images.githubusercontent.com/239386/57745521-9e998c80-7721-11e9-8236-50f1302223d9.png)
If I select "Yes, I will enter prices inclusive of tax" then shipping tax should also be calculated inclusive of tax so I don't have to enter 0.87 as the shipping rate instead of $1 and get annoying rounding issues because of it.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Wordpress 5.2, Woocommerce 3.6.2 (although this has been a long standing problem)
Full stats from  Site Health Info
https://pastebin.com/cgjtPWS6
```
`
### WordPress Environment ###

WordPress address (URL): https://▓▓▓▓▓▓▓▓▓ (irrelevant but not a live website anyway)
Site address (URL): https://▓▓▓▓▓▓▓▓▓▓
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_NZ
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.2.18
PHP Post Max Size: 250 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.38-MariaDB-cll-lve
Max Upload Size: 250 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: ▓▓▓▓▓▓
Total Database Size: 4.58MB
Database Data Size: 4.26MB
Database Index Size: 0.32MB
▓▓▓▓▓_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB
▓▓▓▓▓_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
▓▓▓▓▓_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_woocommerce_log: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_commentmeta: Data: 0.00MB + Index: 0.01MB
▓▓▓▓▓_comments: Data: 0.00MB + Index: 0.01MB
▓▓▓▓▓_failed_jobs: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_links: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_mailchimp_carts: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_ms_snippets: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_options: Data: 0.43MB + Index: 0.05MB
▓▓▓▓▓_postmeta: Data: 0.28MB + Index: 0.09MB
▓▓▓▓▓_posts: Data: 3.46MB + Index: 0.07MB
▓▓▓▓▓_queue: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_snippets: Data: 0.02MB + Index: 0.00MB
▓▓▓▓▓_termmeta: Data: 0.00MB + Index: 0.01MB
▓▓▓▓▓_terms: Data: 0.00MB + Index: 0.01MB
▓▓▓▓▓_term_relationships: Data: 0.00MB + Index: 0.01MB
▓▓▓▓▓_term_taxonomy: Data: 0.01MB + Index: 0.01MB
▓▓▓▓▓_usermeta: Data: 0.01MB + Index: 0.01MB
▓▓▓▓▓_users: Data: 0.00MB + Index: 0.01MB
▓▓▓▓▓_wc_download_log: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB
▓▓▓▓▓_wc_webhooks: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_wfblockediplog: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_wfblocks7: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_wfconfig: Data: 0.03MB + Index: 0.01MB
▓▓▓▓▓_wfcrawlers: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_wffilechanges: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_wffilemods: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_wfhits: Data: 0.01MB + Index: 0.00MB
▓▓▓▓▓_wfhoover: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_wfissues: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_wfknownfilelist: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_wflivetraffichuman: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_wflocs: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_wflogins: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_wfnotifications: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_wfpendingissues: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_wfreversecache: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_wfsnipcache: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_wfstatus: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_wftrafficrates: Data: 0.00MB + Index: 0.00MB
▓▓▓▓▓_woocommerce_min_max_rules: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

astra_adv_header: 2
attachment: 32
birthstory: 5
customize_changeset: 119
custom_css: 3
hottopics: 1
nav_menu_item: 22
newsletter: 1
page: 13
post: 19
product: 9
product_variation: 23
revision: 257
scheduled-action: 1
wpforms: 1
wppb-ul-cpt: 1
wp_block: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

Admin Menu Editor: by Janis Elsts – 1.9
Astra Pro: by Brainstorm Force – 1.8.1
Astra Widgets: by Brainstorm Force – 1.1.0
Code Snippets: by Shea Bunge – 2.13.3
Content Cards: by Arūnas Liuiza – 0.9.7
Duplicate Post: by Enrico Battocchi – 3.2.2
footnotes: by ManFisher Medien ManuFaktur – 1.6.5
Health Check & Troubleshooting: by The WordPress.org community – 1.3.2
Insert Pages: by Paul Ryan – 3.4.5
Mailchimp for WooCommerce: by Mailchimp – 2.1.15 – Not tested with the active version of WooCommerce
Profile Builder - MailChimp Add-On: by Cozmoslabs
Mihai Iova – 1.1.8

Profile Builder - Multi-Step Forms Add-On: by Cozmoslabs
Cristophor Hurduban – 1.0.7

Profile Builder - Placeholder Labels Add-On: by Cozmoslabs
Cristophor Hurduban – 2.4.0

Profile Builder - WooCommerce Sync Add-on: by Cozmoslabs
Adrian Spiac – 1.5.6 – Not tested with the active version of WooCommerce

Permalink Manager Pro: by Maciej Bis – 2.2.2 – Not tested with the active version of WooCommerce
Post Type Switcher: by John James Jacoby – 3.1.0
Profile Builder Pro: by Cozmoslabs – 2.9.8
Ultimate Addons for Gutenberg: by Brainstorm Force – 1.13.3
UpdraftPlus - Backup/Restore: by UpdraftPlus.com
DavidAnderson – 2.16.14.24

WooCommerce Nested Category Layout: by SkyVerge – 1.12.0
WooCommerce PDF Watermark: by WooCommerce – 1.1.7 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.6.2
WooCommerce Show/Hide Products or Categories by User Roles: by CodeWooGeek – 6.1 – Not tested with the active version of WooCommerce
Wordfence Security: by Wordfence – 7.2.5
WPForms Lite: by WPForms – 1.5.2.3

### Inactive Plugins (7) ###

Akismet Anti-Spam: by Automattic – 4.1.1
Astra Hooks: by Brainstorm Force – 1.0.1
Facebook for WooCommerce: by Facebook – 1.9.12 – Not tested with the active version of WooCommerce
Guest Author: by Belal Sejouk – 1.9.1
Min and max woocommerce Rule: by Ajay Radadiya – 2.1 – Not tested with the active version of WooCommerce
WooCommerce PDF Invoices: by Andrew Benbow – 4.4.2 – Not tested with the active version of WooCommerce
WooCommerce Prices By User Role: by Festi-Team – 4.3 – Not tested with the active version of WooCommerce

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.6.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: NZD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #1072 - /order
Cart: #1073 - /cart
Checkout: #1074 - /checkout
My account: #1075 - /my-account
Terms and conditions: ❌ Page not set

### Theme ###

Name: Astra
Version: 1.8.3
Author URL: https://wpastra.com/about/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /home/msccorg/public_html/wp-content/plugins/pb-add-on-woocommerce/templates/myaccount-edit-profile.php

### Action Scheduler ###

Complete: 1
Oldest: 2019-05-14 09:41:31 +1200
Newest: 2019-05-14 09:41:31 +1200

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```

**Comment by kloon** [comment]
Shipping has always been exclusive because you have the option to apply tax on top of it, see the ? next to the shipping price field, it mentions you need to provide it excl of tax, there is also a dropdown you can use to set if the calculation should be taxed or not, so it makes sense to always ask for the excl tax amount.

Anyway, the to reason your tax is not working out right for your shipping is that you are using a rounded value in your shipping. $1/1.15 = 0.8695652174 and not 0.87 as you have it. That rounding you apply is what is throwing your tax calculations off.

If you enter the value 0.8695652174 and go to checkout with 100 items in the cart you will see it works out to the correct amount.

![](https://cld.wthms.co/8TM45y+)
![](https://cld.wthms.co/oh3Vhx+)

**Comment by ThornedRose** [comment]
@kloon Please read what I wrote originally carefully. I already know all of what you said. The problem is I (and many other people) do not want to enter shipping in exclusive of tax - we should be able to enter it in inclusive of tax because shipping tax should respect the "Yes, I will enter prices inclusive of tax" setting. Having to enter them exclusive of tax causes issues in certain situations. See here: https://stackoverflow.com/questions/56108152/maximum-shipping-cost-woocommerce/
This is an ongoing issue that people have been requesting be fixed for literally years.
I see that Woocommerce's Table Rate shipping plugin has the ability to select whether you want shipping rates entered to be inclusive or exclusive of tax. So you cannot say that it is impossible. Or is it just that Woocommerce is trying to force people to buy expensive products just to get something as simple as tax inclusive shipping rates?
