### ISSUE TITLE
woocommerce_rest_cannot_batch

### ISSUE THREAD

**Issue by jmawebtech** [woocommerce/woocommerce#23726]
Error: Rest cannot batch
Steps to reproduce:

1. Log into WooCommerce as admin.
2. Generate new API keys with read/write access.
3. Create this request:

https://www.littlewomentoo.com/wp-json/wc/v2/products/121246/variations/batch?consumer_key=HIDE&consumer_secret=HIDE

{"create":[{"attributes":[{"id":2,"name":"Size","slug":"size","visible":true,"variation":true,"option":"5"},{"id":1,"name":"Color","slug":"color","visible":true,"variation":true,"option":"grey"}],"sku":"194004","regular_price":"67.99","stock_quantity":0.0,"taxable":true,"manage_stock":true}]}

Response

{
"code": "woocommerce_rest_cannot_batch",
"message": "Sorry, you are not allowed to batch manipulate this resource.",
"data":{
"status": 401
}
}

**Comment by claudiosanches** [comment]
Not able to reproduce with the steps you provided:

![Screenshot from 2019-05-16 13-06-02](https://user-images.githubusercontent.com/1264099/57869438-6d7d9280-77db-11e9-88d1-15a844afa1a5.png)

It's creating the variable product without any issue.

Sounds like your user doesn't have `edit_others_posts` permission, this is required to use batch endpoints related with posts.
See:

https://github.com/woocommerce/woocommerce/blob/81360d682764658c9fa5e79c795b0cb4ccf93967/includes/wc-rest-functions.php#L214-L241

**Comment by jmawebtech** [comment]
The parent product was in the trash. The customer had to restore the product, before I could add variants.

**Comment by claudiosanches** [comment]
@jmawebtech makes sense, since you is not allowed to edit posts in trash.
