### ISSUE TITLE
Signature mismatch of get_formatted_order_total

### ISSUE THREAD

**Issue by Mr-AjayM** [woocommerce/woocommerce#23722]
**Describe the bug**
Method call uses the 1 parameter,  but the method signature uses 0 parameters for the method get_formatted_order_total. 

**To Reproduce**
1. Go to 'plugins\woocommerce\includes\abstracts\abstract-wc-order.php'
2. Find the method call get_formatted_order_total and method signature.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/32254909/57778305-65711480-7741-11e9-926a-9957ede25362.png)
![Screenshot_2](https://user-images.githubusercontent.com/32254909/57778318-6b66f580-7741-11e9-94d7-c9446391db97.png)

**Expected behavior**
A parameter should not pass to the function Or signature have the parameter.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #23723.
