### ISSUE TITLE
Maintain the Roadmap

### ISSUE THREAD

**Issue by nicomollet** [woocommerce/woocommerce#23724]
Hello

The https://woocommerce.wordpress.com/ has a nav menu "Roadmap" linking to this Trello:
https://trello.com/b/YgRbpuze/woocommerce-platform-roadmap

The Trello board is not maintained since May 2018, can it be refreshed or something?

Thank you

**Comment by claudiosanches** [comment]
I just removed that link, please follow our development blog to keep updated about what is coming in WooCommerce. Thanks!
