### ISSUE TITLE
woocommerce_checkout_fields filter - unable to override billing address placeholders

### ISSUE THREAD

**Issue by jpknz** [woocommerce/woocommerce#23736]
**Describe the bug**

1. When setting a custom placeholder for billing_address_1 and billing_address_2 it will set it briefly and then change to the default placeholder (custom placeholder flashes briefly on screen then displays default placeholder).

**To Reproduce**
  ```
  add_filter('woocommerce_checkout_fields', 'custom_override_checkout_fields');
    function custom_override_checkout_fields( $fields ) {

     $fields['billing']['billing_address_1']['placeholder'] = 'custom placeholder text here';
     $fields['billing']['billing_address_2']['placeholder'] = 'custom placeholder text here';

     return $fields;

    }
```

**Screenshots**

**Expected behavior**
billing_address_1 and 2 placeholder is set and used rather than briefly flashing with custom placeholder then reverting to the default text.

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment]
This filter is too late to change placeholders, try `woocommerce_default_address_fields` that will solve it:

```php
add_filter( 'woocommerce_default_address_fields', 'custom_wc_default_address_fields' );

function custom_wc_default_address_fields( $fields ) {
    $fields['address_1']['placeholder'] = 'custom placeholder text here';
    $fields['address_2']['placeholder'] = 'custom placeholder text here';

    return $fields;
}
```

**Comment by jpknz** [comment]
Hi @claudiosanches 

Thanks for the response.  Using the default fields filter does work as expected.

However using the woocommerce_checkout_fields the fields placeholder is changed and you can see in the final html source that the custom placeholder text is there - its just being overridden by the default (presumably client side which is why it briefly flashes on the screen).
