### ISSUE TITLE
Email field is blank in checkout page

### ISSUE THREAD

**Issue by nalinvaidya** [woocommerce/woocommerce#23733]
**Describe the bug**
If already existing user tries to purchase the product then billing email field is blank on checkout page

**To Reproduce**
1. Create a user from wordpress admin.
2. Login to created user account.
3. Go to shop page and add product to cart.
4. Proceed to checkout.
5. Look email field is blank.

**Expected behavior**
Email field should contain the logged in user email.

### WordPress Environment ###

`
### WordPress Environment ###

WordPress address (URL): http://wordpress.to
Site address (URL): http://wordpress.to
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: ❌ 5.0.4 - There is a newer version of WordPress available (5.2)
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.15.7
PHP Version: 7.1.25 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.63.0
OpenSSL/1.0.2q

SUHOSIN Installed: –
MySQL Version: 5.7.24-26
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 4.00MB
Database Data Size: 2.90MB
Database Index Size: 1.10MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 2.02MB + Index: 0.05MB
wp_postmeta: Data: 0.22MB + Index: 0.16MB
wp_posts: Data: 0.08MB + Index: 0.06MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 52
page: 8
post: 2
product: 24
product_variation: 4
revision: 7
shop_coupon: 1
shop_order: 6

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (6) ###

Elementor: by Elementor.com – 2.4.7
HumCommerce: by HumCommerce – 2.1.4
WooCommerce Stripe Gateway: by WooCommerce – 4.1.15 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.6.2
WP 1 Slider: by AccessPress Themes – 1.2.2
WPForms Lite: by WPForms – 1.5.0.4

### Inactive Plugins (5) ###

Akismet Anti-Spam: by Automattic – 4.1
Hello Dolly: by Matt Mullenweg – 1.7.1
Mailchimp for WooCommerce: by Mailchimp – 2.1.11 – Not tested with the active version of WooCommerce
WooCommerce Blocks: by Automattic – 1.2.0 – Not tested with the active version of WooCommerce
WordPress Importer: by wordpressdotorg – 0.6.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /?page_id=5
Cart: #6 - /?page_id=6
Checkout: #7 - /?page_id=7
My account: #8 - /?page_id=8
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.4.5 – 2.5.0 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 0
Oldest: –
Newest: –

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by claudiosanches** [comment]
This has been fixed on WooCommerce 3.6.3.

**Comment by uok** [comment]
https://github.com/woocommerce/woocommerce/issues/23521
