### ISSUE TITLE
"Postcode/ZIP" should read "Postal code" for Canada

### ISSUE THREAD

**Issue by grigorijurasov** [woocommerce/woocommerce#23735]
**Describe the bug**
On the checkout page, when Canada is selected "Postcode/ZIP" should read "Postal code". User reported to us that there's no such thing as Canada postcode.

**To Reproduce**
1. Add a product to cart
2. Head to checkout page
3. Choose Canada under "Country"

**Screenshots**
![Screenshot](https://cld.wthms.co/dHGInc+)
Screenshot direct link: https://cld.wthms.co/dHGInc

**Expected behavior**
When Canada is selected "Postcode/ZIP" should read "Postal code"

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!
I'm closing the issue as it already has a PR, please continue the discussion over at #23740.
