### ISSUE TITLE
17.9 MB of JS for blocks

### ISSUE THREAD

**Issue by PhilWaldmann** [woocommerce/woocommerce#23730]
Hi everyone,

I've noticed that a fresh installation of WP (5.2) with WooCommerce (3.6.2) will load almost 18MB of javascript files from `/wp-content/plugins/woocommerce/assets/js/blocks/` in the backend (e.g. Sites/Edit).
All 8 files have roughly the same size of 2.2MB and I think that we have a lot of duplicated code in there. 
It seems that __every__ WooCommerce block file contains `gutenberg`, `momentjs`, `react`, the source of the wc block and some smaller libraries.

Thanks,
Philipp

**Comment by claudiosanches** [comment]
Thanks for reporting it! 
I'm closing the issue since we have a repository for our blocks, please continue the discussion over at https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/571.
