### ISSUE TITLE
Order Refunded - Serious Email content Bug

### ISSUE THREAD

**Issue by arestice** [woocommerce/woocommerce#23737]
The Order Refunded email message that is being sent to the customer who paid for the order by Cash on Delivery method contains very frustrating text. Basically, it says that the customer needs to issue a refund himself.

The message reads I quote "To return funds to the customer you will need to issue a refund through your payment gateway." This type of message should never be visible to the customer, however, this is exactly what Order Refunded email message sent to the buyer states.

I don't use any plugins that alter the order messaging system in any way. 
Please, you have to address it as soon as possible, it is very unprofessional for the site owner to know that the customer gets this message.

![Capture](https://user-images.githubusercontent.com/50709651/57864719-414d1c00-77b1-11e9-837c-8f0ef3ad18f1.PNG)

**Comment by claudiosanches** [comment]
Missing steps to reproduce this issue.
Need to just change the order status to refunded in order to get that email.
Problem introduced in https://github.com/woocommerce/woocommerce/pull/23149

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!
I'm closing the issue as it already has a PR, please continue the discussion over at #23739.
