### ISSUE TITLE
Woocommerce order network

### ISSUE THREAD

**Issue by franc3sc0s92** [woocommerce/woocommerce#23747]
Hi, i want to show the table that is actually in home dashboard in a page of my site. How? thanks

**Comment by claudiosanches** [comment]
Hi there. GitHub is primarily for reporting bugs and is not a support forum. We don’t support custom development here. You could ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce

But in that dashboard widget we use the `wp-json/wc/v3/network` REST API endpoint, so if you want to built something like that widget, you can use the same REST API.
