### ISSUE TITLE
Product variation options lose focus when changed

### ISSUE THREAD

**Issue by slightlyfaulty** [woocommerce/woocommerce#23759]
**Is your feature request related to a problem? Please describe.**
It's not clear to me why this line exists:
https://github.com/woocommerce/woocommerce/blob/90aa716098cdfaa5f411b23bd294f13f6a9b4b57/assets/js/frontend/add-to-cart-variation.js#L278

All it does is remove focus from variation select fields when the user selects different options, i.e. on every change event. It's frustrating to work around this as it's not normal or expected behaviour for select fields. I don't see any advantage or reason for this deliberate removal of element focus. It doesn't even happen when ajax is used to load variations; it's only when variation data is preloaded and ajax loading is not used. This in itself is pretty inconsistent behaviour to have.

**Describe the solution you'd like**
Since there don't seem to be any event handlers that I can find listening or depending on this `blur`, could it not simply just be removed? I've tested this on my side and it doesn't seem to break anything as far as I can tell.

**Comment by kloon** [comment]
I think this has something to do with the fact that variation dropdown values can change when you select certain combinations. I do not think this has much impact on core but might cause issues with extensions that extend variation functionality.

I would rather be safe and certain than just removing, we need to keep backward compatibility in place so just removing would not be an option here.

@woocommerce/proton anyone know the reason why this is used?

**Comment by mikejolley** [comment]
@kloon Could it be that browsers need to blur (lose focus) before the `change` event fires?

**Comment by saulfautley** [comment]
@mikejolley If that were the case for some older browsers, I would imagine the `blur` would also be necessary when using ajax to load variations. Yet `blur` is only being triggered when `!form.useAjax`.

**Comment by rrennick** [comment]
This was addressed in the above commit.
