### ISSUE TITLE
Top Rated Products Shortcode does not work

### ISSUE THREAD

**Issue by ibndawood** [woocommerce/woocommerce#23756]
**Describe the bug**
Top Rated Products Shortcode using `[products top_rated="1" limit="5"]` or `[top_rated_products limit="5"]` does not work as expected. It returns products that are not ordered by ratings.

**To Reproduce**
1. Import Demo products and assign different ratings for different products.
2. Create a new page and add the shortcode `[products top_rated="1"]`
3. Add the widget **Products by Rating** to the Shop Sidebar in StoreFront WooCommerce Theme.
4. Compare the results from the widget and the shortcode. Shortcode returns wrong results

**Screenshots**
![image](https://user-images.githubusercontent.com/179533/57971706-116b6780-79af-11e9-93df-981a5d1556d6.png)
![image](https://user-images.githubusercontent.com/179533/57971712-221bdd80-79af-11e9-941b-f6416380c5a4.png)

**Expected behavior**
The output from the Products By Rating and the shortcode should match. Also the products should be arranged by rating. Here in the above screenshot, lower rated product ( T-Shirt ) is placed before higher rated product ( Beanie ).

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>```
### WordPress Environment ###

WordPress address (URL): http://localhost/~ibndawood/wptests
Site address (URL): http://localhost/~ibndawood/wptests
WC Version: 3.6.3
Log Directory Writable: ✔
WP Version: 5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.34 (Unix) PHP/7.1.23
PHP Version: 7.1.23 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 20 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 8.0.11
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 11.75MB
Database Data Size: 10.72MB
Database Index Size: 1.03MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.05MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 8.45MB + Index: 0.02MB
wp_postmeta: Data: 0.27MB + Index: 0.11MB
wp_posts: Data: 1.42MB + Index: 0.06MB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 56
customize_changeset: 1
nav_menu_item: 69
page: 23
post: 53
product: 12
revision: 5
scheduled-action: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.6.3

### Inactive Plugins (62) ###

Akismet Anti-Spam: by Automattic – 4.1.2
Atomic Blocks - Gutenberg Blocks Collection: by atomicblocks – 1.7.1
Bethlehem Demo: by MadrasThemes – 1.0.0
Bethlehem Extensions: by MadrasThemes – 1.4.3
CoBlocks: by GoDaddy – 1.9.6
Debug Bar: by wordpressdotorg – 1.0
Debug Bar Console: by koopersmith – 0.3
Debug Bar Cron: by Zack Tollman
Helen Hou-Sandi – 0.1.2

Debug Bar Extender: by Thorsten Ott
Automattic – 0.5

Developer: by Automattic – 1.2.6
Electro Demo: by MadrasThemes – 2.3.2 – Not tested with the active version of WooCommerce
Electro Extensions: by MadrasThemes – 2.3.2
Envato Market: by Envato – 2.0.0
Envato Theme Check: by Scott Parry – 20180222
Front Demo: by MadrasThemes – 0.0.223 – Not tested with the active version of WooCommerce
Front Extensions: by MadrasThemes – 0.0.223
Gutenberg: by Gutenberg Team – 5.7.0
Gutenberg Block Unit Test: by Rich Tabor – 1.0.6
Hello Dolly: by Matt Mullenweg – 1.7
Jetpack by WordPress.com: by Automattic – 7.3.1
Jobhunt Demo: by MadrasThemes – 1.0.1
Jobhunt Extensions: by MadrasThemes – 1.0.1 – Not tested with the active version of WooCommerce
Kidos Demo: by MadrasThemes – 1.0.0 – Not tested with the active version of WooCommerce
Kidos Extensions: by MadrasThemes – 1.0.0 – Not tested with the active version of WooCommerce
Kirki Toolkit: by Ari Stathopoulos (@aristath) – 3.0.39
Log Deprecated Notices: by Andrew Nacin – 0.4.1
Log Viewer: by Markus Fischbacher – 14.05.04
Media Center Demo: by MadrasThemes – 1.0.0
Media Center Extensions: by Transvelo – 2.7.10
Monster Widget: by Automattic – 0.3
Pig Latin: by Nikolay Bachiyski – 0.2
Pizzaro Demo: by MadrasThemes – 1.2.13
Pizzaro Extensions: by MadrasThemes – 1.2.13 – Not tested with the active version of WooCommerce
Redux Framework: by Team Redux – 3.6.15
Reen Demo: by MadrasThemes – 0.0.134 – Not tested with the active version of WooCommerce
Reen Extensions: by MadrasThemes – 0.0.134
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.1
Rewrite Rules Inspector: by Daniel Bachhuber
Automattic – 1.2.1

RTL Tester: by <a href="http://blog.yoavfarhi.com">Yoav Farhi</a>
<a href="http://automattic.com">Automattic</a> – 1.1

Simply Show IDs: by Matt Martz – 1.3.3
Stackable - Gutenberg Blocks: by Gambit Technologies
Inc – 1.15.2

Techmarket Demo: by MadrasThemes – 1.3.0
Techmarket Extensions: by MadrasThemes – 1.3.0
Theloke Demo: by MadrasThemes – 1.0.0 – Not tested with the active version of WooCommerce
Theloke Extensions: by MadrasThemes – 1.0.0 – Not tested with the active version of WooCommerce
Theme Check: by Otto42
pross – 20190208.1

Theme Test Drive: by Vladimir Prelovac – 2.9.1
Tokoo Demo: by MadrasThemes – 1.1.1 – Not tested with the active version of WooCommerce
Tokoo Extensions: by MadrasThemes – 1.1.1
Ultimate Addons for Gutenberg: by Brainstorm Force – 1.13.3
Uneno Demo: by MadrasThemes – 1.0.5 – Not tested with the active version of WooCommerce
Uneno Extensions: by MadrasThemes – 1.0.0 – Not tested with the active version of WooCommerce
Uneno Extensions: by MadrasThemes – 1.0.0 – Not tested with the active version of WooCommerce
Uneno Extensions: by MadrasThemes – 1.0.5 – Not tested with the active version of WooCommerce
User Switching: by John Blackbourn & contributors – 1.5.0
Vodi Demo: by MadrasThemes – 1.0.2
Vodi Extensions: by MadrasThemes – 1.0.2
WooCommerce Blocks: by Automattic – 2.1.0
WordPress Beta Tester: by Peter Westwood
Andy Fragen – 2.0.4

WordPress Importer: by wordpressdotorg – 0.6.4
WP Reset: by WebFactory Ltd – 1.60
YITH WooCommerce Wishlist: by YITH – 2.2.10

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2019-05-18 15:01:06 +0000
Newest: 2019-05-18 15:01:06 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –
```</details>

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #23771.
