### ISSUE TITLE
Address 2 field requests apartment number on en-gb localisation

### ISSUE THREAD

**Issue by Wegerich** [woocommerce/woocommerce#23755]
**Describe the bug**
In the UK the correct address format runs from smallest "thing" to largest, with the postal code at the end. https://www.postoffice.co.uk/mail/how-to-address-mail

So

Name
Company
Room/Department, Floor, House Name (Address 1)
Building Number, Street (Address 2)
City
County
Postal Code

Currently when checking out the placeholder text for Address 1 is "Street number and name" and then Address 2 is "Flat or apartment number (optional)".

[Screenshot example](https://imgur.com/uTHVVLt.png)

I would like to propose that this is reversed in the en-gb localisation. Alternatively, the placeholder text could be changed to simply "Address Line 1" and "Address Line 2".

**To Reproduce**
1. Install Woocommerce
2. Install Storefront Theme
3. go to wp-admin/options-general.php
3. Set site language to "English (UK)"
4. Create a product
5. Add product to cart
6. Go to Checkout
4. See placeholder text in address fields

**Screenshots**

**Expected behavior**
Placeholder text should be non-instructive or adjusted to GB address style

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://www.****.uk/wp
Site address (URL): https://www.****.uk
WC Version: 3.6.2
Log Directory Writable: ✔
WP Version: 5.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.5
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 10.1.38-MariaDB-cll-lve
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.2
WC Database Prefix: a8m9rq466w
Total Database Size: 249.61MB
Database Data Size: 141.96MB
Database Index Size: 107.65MB
[...]

### Post Type Counts ###

askme: 48
attachment: 154
custom_css: 2
customize_changeset: 5
gmpf: 1
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
nav_menu_item: 13
page: 14
post: 40
product: 28
product_variation: 2
revision: 715
safecss: 1
scheduled-action: 18
shop_coupon: 111
shop_order: 17975
shop_order_refund: 202
user_request: 2
wc_order_email: 3
wc_order_status: 8

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

WooCommerce: by Automattic – 3.6.2

### Inactive Plugins (1) ###

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #7 - /shop/
Basket: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: #19708 - /terms-conditions/

### Theme ###

Name: Storefront
Version: 2.5.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 18
Oldest: 2019-04-25 17:44:19 +0100
Newest: 2019-05-16 18:52:34 +0100

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –
```
</details>

**Comment by claudiosanches** [comment]
This sounds more like customization, also you can change it as you like using the `woocommerce_default_address_fields` filter, see an example:

```php
add_filter( 'woocommerce_default_address_fields', function( $fields ) {
    $fields['address_1']['placeholder'] = 'Address Line 1';

    if ( isset( $fields['address_2'] ) ) {
        $fields['address_2']['placeholder'] = 'Address Line 2';
    }

    return $fields;
} );
```

**Comment by Wegerich** [comment]
I tried using the filters but it did not work. The adjusted placeholders did show up for a split second during loading, but then they were over-written by something else. 

The fact remains that in en-GB, the apartment number should never appear after the street address.

**Comment by claudiosanches** [comment]
Using the filter I'm talking about will not be replaced like you are saying.

**Comment by Wegerich** [comment]
I previously tried this method in functions.php and it didn't work as I described. I tried a lot to understand why that happened but I unfortunately don't have enough knowledge to debug it. 

```
add_filter( 'woocommerce_checkout_fields' , 'override_billing_checkout_fields', 10, 1 );

function override_billing_checkout_fields( $fields ) {
		$fields['billing']['billing_address_1']['placeholder'] = 'Address line 1';
		$fields['billing']['billing_address_2']['placeholder'] = 'Address line 2';

		$fields['Shipping']['shipping_address_1']['placeholder'] = 'Address line 1';
		$fields['Shipping']['shipping_address_2']['placeholder'] = 'Address line 2';
    return $fields;
}
```

In the end I installed a plugin to do it but I still wanted to suggest this modification because it is technically incorrect according to GB address standards.

If you are able to figure out why this problem happened though, I would still be grateful.

**Comment by claudiosanches** [comment]
@Wegerich you are using the `woocommerce_checkout_fields` filter, if you try `woocommerce_default_address_fields` will work as I described.

**Comment by Wegerich** [comment]
I also tried this:


```
add_filter( 'woocommerce_default_address_fields', 'uwc_new_address_one_placeholder', 1 );

function uwc_new_address_one_placeholder( $fields ) {
	$address_fields['address_1']['placeholder'] = 'Address line 1';
	$address_fields['address_2']['placeholder'] = 'Address line 2';
	return $address_fields;
}	
```

but it did nothing at all. the correct text didn't even show up for a second when the page loaded. 

I tried pasting your code into the functions.php editor but it refused to save the file.

**Comment by claudiosanches** [comment]
@Wegerich still I advice you to try use my code in https://github.com/woocommerce/woocommerce/issues/23755#issuecomment-493991215
Because `address_2` may not exist depending on the display setting in the Customize menu, so it's best to check if `address_2` exists first.
But glad to help!
