### ISSUE TITLE
Better way to cache template path in wc_get_template_part and wc_get_template  function that will work in a load balanced environment

### ISSUE THREAD

**Issue by carl-alberto** [woocommerce/woocommerce#23751]
### DETAILS OF THE ISSUE
We have a setup of multiple application servers behind a load balancer where there are different root path for each app server e.g.
Server 1 path - /svr/bindings/serverpathxxxxxxxxx1/
Server 2 path - /svr/bindings/serverpathxxxxxxxxx2/
And we have a single persistent Redis cache that serves those application containers

Based from the [`wc_get_template_part`](https://github.com/woocommerce/woocommerce/blob/master/includes/wc-core-functions.php#L159-L197) function, it stores the full path in the cache in the $template variable eg. /svr/bindings/serverpathxxxxxxxxx1/wp-content/plugins/woocommerce

Similar code happens in `wc_get_template` function in same file.

What happens in a load balanced environment with a single persistent cache server serving multiple server, where full paths on each server are different, is when the event happens that the **2nd server** is called and the cache for the $template is called for **1st server** resulting a `failed to open stream: No such file or directory in /svr/bindings/serverpathxxxxxxxxx1/wp-content/plugins/woocommerce` warning and not rendering all relevant WooCommerce templates.

### Possible resolutions
We are looking to discuss possible solutions and would love to try to submit a PR for the possible fix but would like to hear what would be feasible that would benefit similar users that are having the same setup and issues :
1) Caching relative path instead of the full path
2) Store 2 or more cache key entries for $template variable depending which server is calling 
3) Adding another checking mechanism for the $template path if it exists, then get the correct 

### Temporary workaround
At the moment for the people that are being blocked by this issue, we have seen workarounds like:
1) Skip the whole WooCommerce caching by adding this line of code `wp_cache_add_non_persistent_groups( array( 'woocommerce' ) );` in their theme's function.php or their custom plugin
2) Doing a core hack by commenting out these lines https://github.com/woocommerce/woocommerce/blob/90aa716098cdfaa5f411b23bd294f13f6a9b4b57/includes/wc-core-functions.php#L161 
https://github.com/woocommerce/woocommerce/blob/90aa716098cdfaa5f411b23bd294f13f6a9b4b57/includes/wc-core-functions.php#L209
and replacing it with `$template = '';` so the values will not be loaded from cache
3) Add this filter can be added in custom mu-plugin, theme's functions.php or a custom plugin.
https://gist.github.com/carl-alberto/fc0496962e3ae3f514e4c7374db08c9e

**Comment by kfoubert** [comment]
Thanks Carl!

**Comment by claudiosanches** [comment]
> We are looking to discuss possible solutions and would love to try to submit a PR for the possible fix but would like to hear what would be feasible that would benefit similar users that are having the same setup and issues :

Please feel free to submit a Pull Request, I think that if works with relative paths we should give a try, also we can include filters, so people can disable or change this behavior without have to disable all caching for WooCommerce.

**Comment by carl-alberto** [comment]
Thanks for the input @claudiosanches, PR on its way but has led me to possible solution 2 instead of the 1 as you have suggested as there are no other elegant way to do this via native functions like `WC()->template_path()` and `WC()->plugin_path()` because it will always still use the full server path. Or you might have a better suggestion on what to use?

The proposed solution 2 which will create a cache key for each server and using the server variable `$_SERVER['SERVER_NAME']` as another layer of unique identifier for the $cachekey might be better in the longer performance wise. Will the `$_SERVER['SERVER_NAME']` also be a good choice to identify a server & cachekey relationship?

In testing this, I can provide you a test server access via WooCommerce Slack if you want? 

Thanks!

**Comment by claudiosanches** [comment]
> In testing this, I can provide you a test server access via WooCommerce Slack if you want?
Yes, please call me on Slack.

I have made a initial review in the Pull Request, I made a few suggestions, but already ready for us to test. Thanks!

**Comment by carl-alberto** [comment]
Thanks @claudiosanches ! will correspond via slack for an environment for you to test! :)

**Comment by kloon** [comment]
See #23783

**Comment by carl-alberto** [comment]
Hi @kloon, do I have any action items like resolving the Travis build errors? Thanks! :)

**Comment by claudiosanches** [comment]
@carl-alberto no worry about that errors, we are aware of, it's not just in that PR.

**Comment by carl-alberto** [comment]
Thanks @claudiosanches , please let us know if there are any actions items that we need to accomplish or you need any help! 😄

**Comment by claudiosanches** [comment]
@carl-alberto sorry for the delay, we are right now on a team meetup for this week, but I'll check this as soon as possible.

**Comment by JulienMelissas** [comment]
Hate to comment on a closed thread, but I have another suggested temporary fix for those who might be having issues, similar to @carl-alberto's Option #3 solution above: https://gist.github.com/JulienMelissas/d3601af950221432a109c8c4b1617b87
