### ISSUE TITLE
Facebook for Woocommerce can't synced with facebook shop

### ISSUE THREAD

**Issue by givari** [woocommerce/woocommerce#23761]
Recently i accidentally delete facebook catalog created from integrating woocommerce with facebook shop through Facebook for woocommerce plugin. then i try to re-instal the plugin, and try to recreate the catalog but didn't work out.

the facebook for woocommerce plugin "manage settings" also didn't work.

please anyone can help me, how to re-connect with my facebook shop ?

**Comment by rodrigoprimo** [comment]
I'm sorry but this is not a support forum. We use GitHub issues exclusively for WooCommerce core bug reports. For support, you can try the WordPress.org support forum (https://wordpress.org/support/plugin/woocommerce/). Alternatively, if you are a paying WooCommerce.com user, you can contact their support (http://woocommerce.com/contact-us/).
