### ISSUE TITLE
Add to cart is not showing when backorder items are sold out

### ISSUE THREAD

**Issue by vincenzoraco** [woocommerce/woocommerce#23765]
As per title, when a product reaches **stock quantity 0** and **allow backorders** option is set to **allow, but notify customer**, the **Add to cart** button is not showing. But, if you open the product page and click **Update**, without changing anything, the **Add to cart** button is showing.

**To Reproduce**
1. Add a product with 1 or more in stock
2. Tick **Manage stock?**
3. Set **Stock quantity** to 1 or more
4. Set **Allow backorders?** to **Allow, but notify customer**
5. Buy the product
6. Open the product page again, and it will show **out of stock** instead of showing **Available on backorder** and the **Add to card** button.
7. If you search the product from the backend, you will see the status changing from **Out of stock** to **On backorder**

**Screenshots**
![Screenshot 1](http://i68.tinypic.com/16ktmgx.png)

![Screenshot 2](http://i67.tinypic.com/3091nw2.png)

**Expected behavior**
When the last unit has been purchased, the item should not go on a **out of stock** label but should automatically go on the **on backorder** status, without manually update the product.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

Home URL: https://www.beyondtools.com
Site URL: https://www.beyondtools.com/wptools
WC Version: 3.5.7
Log Directory Writable: ✔
WP Version: ❌ 5.1.1 - There is a newer version of WordPress available (5.2)
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: –
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: Apache/2.2.32 (Unix) mod_ssl/2.2.32 OpenSSL/1.0.1e-fips mod_bwlimited/1.4
PHP Version: 7.1.26 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 3600
PHP Max Input Vars: 15300
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 10.0.37-MariaDB
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.5
WC Database Prefix: y0hxzkxp_
MaxMind GeoIP Database: ✔
Total Database Size: 2104.61MB
Database Data Size: 1948.00MB
Database Index Size: 156.61MB
y0hxzkxp_woocommerce_sessions: Data: 1274.64MB + Index: 41.02MB
y0hxzkxp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
y0hxzkxp_woocommerce_attribute_taxonomies: Data: 0.01MB + Index: 0.02MB
y0hxzkxp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_woocommerce_order_items: Data: 2.99MB + Index: 1.25MB
y0hxzkxp_woocommerce_order_itemmeta: Data: 14.83MB + Index: 10.23MB
y0hxzkxp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
y0hxzkxp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
y0hxzkxp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_alm: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_aws_cache: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_aws_index: Data: 16.80MB + Index: 0.00MB
y0hxzkxp_commentmeta: Data: 0.13MB + Index: 0.10MB
y0hxzkxp_comments: Data: 8.94MB + Index: 3.40MB
y0hxzkxp_duplicator_pro_entities: Data: 0.01MB + Index: 0.00MB
y0hxzkxp_duplicator_pro_packages: Data: 0.02MB + Index: 0.00MB
y0hxzkxp_failed_jobs: Data: 0.17MB + Index: 0.01MB
y0hxzkxp_frontend_builder_options: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_frontend_builder_pages: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_itsec_distributed_storage: Data: 7.60MB + Index: 0.00MB
y0hxzkxp_itsec_fingerprints: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_itsec_geolocation_cache: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_itsec_lockouts: Data: 0.00MB + Index: 0.01MB
y0hxzkxp_itsec_logs: Data: 386.18MB + Index: 9.10MB
y0hxzkxp_itsec_temp: Data: 0.42MB + Index: 0.37MB
y0hxzkxp_links: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_lockdowns: Data: 0.10MB + Index: 0.03MB
y0hxzkxp_login_fails: Data: 0.77MB + Index: 0.26MB
y0hxzkxp_mailchimp_carts: Data: 0.15MB + Index: 0.00MB
y0hxzkxp_nf_objects: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_nf_relationships: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_ninja_forms: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_offline_giftcard: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_options: Data: 42.17MB + Index: 3.57MB
y0hxzkxp_pmxe_templates: Data: 0.01MB + Index: 0.00MB
y0hxzkxp_pmxi_files: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_pmxi_history: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_pmxi_imports: Data: 0.25MB + Index: 0.00MB
y0hxzkxp_pmxi_posts: Data: 0.33MB + Index: 0.12MB
y0hxzkxp_pmxi_templates: Data: 0.09MB + Index: 0.00MB
y0hxzkxp_postmeta: Data: 112.62MB + Index: 42.73MB
y0hxzkxp_posts: Data: 16.95MB + Index: 3.88MB
y0hxzkxp_ps_exclude: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_ps_posts: Data: 0.24MB + Index: 0.06MB
y0hxzkxp_ps_product_sku: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_queue: Data: 0.10MB + Index: 0.00MB
y0hxzkxp_statistics_exclusions: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_statistics_historical: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_statistics_pages: Data: 24.09MB + Index: 18.19MB
y0hxzkxp_statistics_useronline: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_statistics_visit: Data: 0.03MB + Index: 0.02MB
y0hxzkxp_statistics_visitor: Data: 8.97MB + Index: 4.79MB
y0hxzkxp_termmeta: Data: 0.50MB + Index: 0.36MB
y0hxzkxp_terms: Data: 0.36MB + Index: 0.60MB
y0hxzkxp_term_relationships: Data: 1.64MB + Index: 3.13MB
y0hxzkxp_term_taxonomy: Data: 0.46MB + Index: 0.46MB
y0hxzkxp_usermeta: Data: 22.97MB + Index: 11.44MB
y0hxzkxp_users: Data: 0.95MB + Index: 1.12MB
y0hxzkxp_wc_download_log: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_wc_gpf_render_cache: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_wfConfig: Data: 0.02MB + Index: 0.01MB
y0hxzkxp_wfconfig: Data: 0.00MB + Index: 0.01MB
y0hxzkxp_wfCrawlers: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_wfcrawlers: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_wfHits: Data: 0.08MB + Index: 0.02MB
y0hxzkxp_wfhits: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_wfHoover: Data: 0.08MB + Index: 0.02MB
y0hxzkxp_wfhoover: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_wfIssues: Data: 0.01MB + Index: 0.00MB
y0hxzkxp_wfissues: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_woocommerce_gpf_google_taxonomy: Data: 0.86MB + Index: 0.00MB
y0hxzkxp_yoast_seo_links: Data: 0.26MB + Index: 0.05MB
y0hxzkxp_yoast_seo_meta: Data: 0.20MB + Index: 0.20MB

### Post Type Counts ###

acf: 2
acf-field: 2
acf-field-group: 2
attachment: 10170
custom_css: 2
customize_changeset: 6
et_pb_layout: 32
feedback: 107
giftcard: 4
nav_menu_item: 1169
nf_sub: 6
oembed_cache: 16
page: 102
post: 143
price_match_request: 3
product: 6200
product_variation: 167
revision: 2
rp_shop_giftcard: 98
shop_coupon: 19
shop_order: 15340
shop_order_refund: 285
shop_quote: 325
slide: 15
slides: 4
soliloquy: 1
sp_responsiveslider: 2
testimonial: 3
testimonials: 3
tribe_events: 123
tribe_organizer: 11
tribe_venue: 23
tribe-ea-record: 40
wishlist: 10704
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (32) ###

Advanced Custom Fields: by Elliot Condon – 5.7.12
Advanced Database Cleaner: by Younes JFR. – 2.0.0
WooCommerce Afterpay Gateway: by AfterPay – 1.3.1 – Not tested with the active version of WooCommerce
Akismet Anti-Spam: by Automattic – 4.1.1
iThemes Security: by iThemes – 7.3.3
Beyond Tools: by Vincenzo Raco – 1.0.0
Contact Form 7: by Takayuki Miyoshi – 5.1.1
Easy FancyBox: by RavanH – 1.8.15
Facebook for WooCommerce: by Facebook – 1.9.7 – Not tested with the active version of WooCommerce
WooCommerce - Gift Cards: by WP Ronin – 2.6.5 – Not tested with the active version of WooCommerce
Google XML Sitemaps: by Arne Brachhold – 4.1.0
Instagram Feed: by Smash Balloon – 1.12
Mailchimp for WooCommerce: by Mailchimp – 2.1.15 – Not tested with the active version of WooCommerce
Max Mega Menu: by megamenu.com – 2.6
My Custom Functions: by Space X-Chimp – 4.38
Product/Review CSV Import Export: by WebToffee – 3.7.2 – Not tested with the active version of WooCommerce
Search By SKU - for Woocommerce: by Matthew Lawson – 0.6.1 – Not tested with the active version of WooCommerce
SnapEngage plugin: by SnapEngage – 1.0
WooCommerce Extra Product Sorting Options: by SkyVerge – 2.7.3
WooCommerce PDF & Print: by gVectors Team – 1.5.0 – Not tested with the active version of WooCommerce
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.16 – 1.10.22 is available – Not tested with the active version of WooCommerce
WooCommerce Google Product Feed: by Ademti Software Ltd. – 7.8.4 – 7.8.8 is available
WooCommerce Products Compare: by WooCommerce – 1.0.7 – 1.0.13 is available – Not tested with the active version of WooCommerce
Woocommerce Products Per Page: by Jeroen Sormani – 1.2.6 – Not tested with the active version of WooCommerce
WooCommerce Sales Report Email: by WooThemes – 1.1.2 – 1.1.7 is available – Not tested with the active version of WooCommerce
WooCommerce Smart Refunder: by StoreApps – 1.1.1 – 1.4.1 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.5.7 – 3.6.3 is available
WP Disable: by optimisation.io - jody nesbitt – 1.5.21
WP Migrate DB: by Delicious Brains – 1.0.11
WP Rocket: by WP Media – 3.3.2
WooCommerce - Gift Cards Pro: by WP Ronin – 1.6.2 – Not tested with the active version of WooCommerce
Zip - WooCommerce: by Zip – 2.1.4

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-catalog (exclude-from-catalog-2)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Shop base: #481 - /shop/
Cart: #483 - /cart/
Checkout: #485 - /checkout/
My account: #487 - /my-account/
Terms and conditions: #11552 - /big-on-service/terms/

### Theme ###

Name: Beyond Tools
Version: 1.0
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: beyond-tools/woocommerce/archive-product.php version 2.0.0 is out of date. The core version is 3.4.0
beyond-tools/woocommerce/content-product.php
beyond-tools/woocommerce/content-product_cat.php
beyond-tools/woocommerce/content-single-product.php
beyond-tools/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

### WooCommerce Google Product Feed fields ###

Product description: Main product description only (full preferred.)
Availability: Defaults to "in stock".
Condition: Defaults to "new".
Brand: Pre-populates from pa_brand taxonomy.
Product Type: Pre-populates from pa_tool-equipment-type taxonomy.
Google Product Category: 

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send item_group_id: No

### Store Catalog PDF Download ###

Template Overrides: 
`
</details>

**Comment by kloon** [comment]
Hi, I am noticing you are running on an outdated version of WooCommerce. The current version is 3.6.3 and you seem to be running 3.5.4 and your DB version is even older meaning you could have data descripencies.

I have tried to replicate this with the current version of WooCommerce but am unable to, please see my screen recording below

![](https://cld.wthms.co/v7pAPD+)

I suggest you make backups of your site then proceed to test by disabling plugins and switch to a default theme to test if the error persists. If it does then I suggest you check that your WooCommerce database is updated, you should have a notices asking to perform this in your admin area.

Alternatively, you will have to update your whole site to WooCommerce 3.6.3 and then perform the DB update routine. Please make sufficient backups before proceeding so that should something go wrong you have the means to roll back.

Closing this issue as I am unable to replicate and you have outdated software, this could have well been a bug in a previous version which was fixed already.
