### ISSUE TITLE
An Ajax call reloads all page assets after every Ajax Add to Cart call

### ISSUE THREAD

**Issue by asafmjul** [woocommerce/woocommerce#23768]
**Describe the bug**
After 'ajax add to cart' from an archive page, another ajax call is made, loading all page assets again.

**To Reproduce**
1. While DevTools is open on "Network" (XHR)
2.  Add to cart from archive page using ajax
3. See redundant ajax call

**Screenshots**
https://snag.gy/YHj7Mc.jpg

**Expected behavior**
No redundant ajax call

**Isolating the problem (mark completed items with an [x]):**
- [V] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [V ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [V] I can reproduce this bug consistently using the steps above.

**Also, a WooCommerce chat support agent was able to replicate it in a clean installation.**

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://staging.jul.co.il
Site address (URL): https://staging.jul.co.il
WC Version: 3.6.3
Log Directory Writable: ✔
WP Version: 5.2
WP Multisite: –
WP Memory Limit: 300 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: he_IL
External object cache: –

### Server Environment ###

Server Info: nginx/1.15.12
PHP Version: 7.3.5-1+ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.38-MariaDB-1~xenial
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 205.62MB
Database Data Size: 105.62MB
Database Index Size: 100.00MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.17MB + Index: 0.06MB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.77MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_bluesnap_supported_currencies: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 4.16MB + Index: 8.20MB
wp_facetwp_index: Data: 5.02MB + Index: 6.31MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB
wp_icl_languages_translations: Data: 0.19MB + Index: 0.11MB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB
wp_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB
wp_icl_node: Data: 0.02MB + Index: 0.00MB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB
wp_icl_strings: Data: 4.52MB + Index: 6.95MB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB
wp_icl_string_pages: Data: 0.02MB + Index: 0.02MB
wp_icl_string_positions: Data: 0.02MB + Index: 0.02MB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB
wp_icl_string_translations: Data: 2.52MB + Index: 1.52MB
wp_icl_string_urls: Data: 0.02MB + Index: 0.02MB
wp_icl_translate: Data: 0.05MB + Index: 0.02MB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB
wp_icl_translations: Data: 5.52MB + Index: 12.06MB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB
wp_icl_translation_status: Data: 2.52MB + Index: 1.52MB
wp_imagify_files: Data: 2.52MB + Index: 1.14MB
wp_imagify_folders: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 5.27MB + Index: 1.08MB
wp_pmxe_exports: Data: 0.02MB + Index: 0.00MB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB
wp_pmxe_posts: Data: 0.02MB + Index: 0.00MB
wp_pmxe_templates: Data: 0.02MB + Index: 0.00MB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB
wp_pmxi_images: Data: 1.52MB + Index: 0.00MB
wp_pmxi_imports: Data: 0.08MB + Index: 0.00MB
wp_pmxi_posts: Data: 0.50MB + Index: 0.00MB
wp_pmxi_templates: Data: 0.14MB + Index: 0.00MB
wp_postmeta: Data: 31.13MB + Index: 27.13MB
wp_posts: Data: 10.06MB + Index: 7.20MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wp_swpext_metrics_clicks: Data: 0.05MB + Index: 0.03MB
wp_swpext_metrics_ids: Data: 0.36MB + Index: 0.48MB
wp_swpext_metrics_queries: Data: 0.14MB + Index: 0.08MB
wp_swpext_metrics_searches: Data: 0.33MB + Index: 0.75MB
wp_swp_cf: Data: 1.52MB + Index: 1.20MB
wp_swp_index: Data: 15.55MB + Index: 16.03MB
wp_swp_log: Data: 0.34MB + Index: 0.48MB
wp_swp_tax: Data: 0.02MB + Index: 0.05MB
wp_swp_terms: Data: 1.52MB + Index: 2.36MB
wp_termmeta: Data: 0.06MB + Index: 0.06MB
wp_terms: Data: 0.06MB + Index: 0.03MB
wp_term_relationships: Data: 5.02MB + Index: 2.13MB
wp_term_taxonomy: Data: 0.06MB + Index: 0.03MB
wp_usermeta: Data: 0.38MB + Index: 0.33MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 1.48MB + Index: 1.13MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wppusher_packages: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

acf-field: 130
acf-field-group: 4
attachment: 6360
customize_changeset: 4
jetpack_migration: 2
option: 2
page: 17
post: 3
product: 6591
revision: 88
scheduled-action: 8282
shop_coupon: 5
shop_order: 439
store: 5
wc_zapier_feed: 1
wp_block: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (3) ###

ManageWP - Worker: by GoDaddy – 4.8.0
Imagify: by WP Media – 1.9.2
WooCommerce: by Automattic – 3.6.3

### Inactive Plugins (33) ###

Advanced Custom Fields Multilingual: by OnTheGoSystems – 1.1
Advanced Custom Fields PRO: by Elliot Condon – 5.8.0
CardCom Payment Gateway: by CardCom LTD – 3.3.1.3 – Not tested with the active version of WooCommerce
Cloudinary: by Cloudinary Ltd.
XWP – 2.0.0.alpha-16

FacetWP: by FacetWP
LLC – 3.3.7

FacetWP - Load More: by FacetWP
LLC – 0.4.3

FacetWP - WPML: by FacetWP
LLC – 1.3.0

Loco Translate: by Tim Whitlock – 2.2.2
Mailchimp for WooCommerce: by Mailchimp – 2.1.16 – Not tested with the active version of WooCommerce
Mailgun: by Mailgun – 1.7.1
Metorik Helper: by Metorik – 1.2.0
SearchWP: by SearchWP
LLC – 3.0.6

SearchWP Custom Results Order: by SearchWP
LLC – 1.1.2

SearchWP Live Ajax Search: by Jonathan Christopher – 1.3.1
SearchWP Metrics: by SearchWP
LLC – 1.0.9.2

SearchWP WooCommerce Integration: by SearchWP
LLC – 1.2.1 – Not tested with the active version of WooCommerce

SearchWP WPML Integration: by Jonathan Christopher – 1.4.0
Smush: by WPMU DEV – 3.2.0.1
WooCommerce Customer/Order/Coupon CSV Import Suite: by SkyVerge – 3.6.0
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.9
WooCommerce Mixpanel: by SkyVerge – 1.13.1
WooCommerce Multilingual: by OnTheGoSystems – 4.6.2.1
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.21 – 1.10.22 is available – Not tested with the active version of WooCommerce
WooCommerce Smart Coupons: by StoreApps – 4.0.4
WooCommerce Zapier Integration: by OM4 – 1.9.3
WP All Export Pro: by Soflyy – 1.5.5
WP All Import - WooCommerce Add-On Pro: by Soflyy – 3.0.7
WP All Import Pro: by Soflyy – 4.5.6
WPML All Import: by OnTheGoSystems – 2.1
WPML Multilingual CMS: by OnTheGoSystems – 4.2.4.1
WPML String Translation: by OnTheGoSystems – 2.10.2
WPML Translation Management: by OnTheGoSystems – 2.8.3
WP Pusher: by WP Pusher – 2.4.10

### Must Use Plugins (2) ###

Kinsta Must-use Plugins: by Kinsta Team – 2.3.1
ManageWP - Worker Loader: by GoDaddy –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: ILS (₪)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #44 - /cart/
Checkout: #45 - /checkout/
My account: #46 - /my-account/
Terms and conditions: #401 - /terms-of-use/

### Theme ###

Name: Storefront
Version: 2.5.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 8,278
Oldest: 2019-04-21 13:55:20 +0300
Newest: 2019-05-20 13:14:01 +0300

Pending: 1
Oldest: 2019-05-21 10:47:02 +0300
Newest: 2019-05-21 10:47:02 +0300

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 3
Oldest: 2019-02-28 17:48:02 +0200
Newest: 2019-02-28 17:48:02 +0200

`
</details>

**Comment by asafmjul** [comment]
Hi, any ETA for a fix?

**Comment by claudiosanches** [comment]
@asafmjul there's already an Pull Request proposing a fix, you can try #23780, this will helps us to patch it more quickly.

**Comment by luciodiri** [comment]
Good catch @asafmjul  
Would also love an update on this

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #23780.
