### ISSUE TITLE
Products with Backorders set to 'Allow' are not marked as backorderd in order details.

### ISSUE THREAD

**Issue by bhouszka** [woocommerce/woocommerce#23782]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. For variable product set to manage stock for specific variations
2. For a specific variation set the stock level to 0 and Backorders to 'Allow'
3. Buy the product

## Expected/actual behavior

When I follow those steps, I see there is no information in Admin Panel -> order details that product is on backorder. Also, no other plugins listing products on backorders show them as back ordered like:

 - https://wordpress.org/plugins/atum-stock-manager-for-woocommerce/
 - https://wordpress.org/plugins/list-backorders-for-woocommerce/

As I have not chosen the option "Allow, but notify the customer" I was expecting there will be no information on the order confirmation, emails, etc, but the product will be marked as back ordered on the backend.

## Isolating the problem

- [X ] This bug happens with only WooCommerce plugin active
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X ] I can reproduce this bug consistently using the steps above

**Comment by vedanshujain** [comment]
WooCommerce as of now does not show back order explicitly marked on the order details. 

Unfortunately, we cannot with the plugins that you mentioned in the issue. I'd recommend that you go to the support forums of those plugins and see if that works out. 

I am closing the issue, but feel free to comment if you think there is a reproducible bug in WooCommerce itself.
