### ISSUE TITLE
Problem with nth-child pseudo selector in class-emogrifier.php

### ISSUE THREAD

**Issue by borisco** [woocommerce/woocommerce#23799]
The nth-child css pseudo selector is not working anymore
In the class-emogrifier.php file, strings in the translateNthChild function should include '/self' instead of '/static', line 1787, 1794 and 1801
I think it's the same as on https://www.somethingdigital.com/blog/emogrifier-find-replace-evil/

**Comment by kloon** [comment]
Can confirm this is a bug in the library, they have released an update with the fix and I will file a PR with the updated library for WooCommerce.

**Comment by kloon** [comment]
See #23824 23824
