### ISSUE TITLE
WC()->cart is null in rest api since 3.6

### ISSUE THREAD

**Issue by Tofandel** [woocommerce/woocommerce#23792]
A regression has happened in 3.6 because of the [optimisation](https://github.com/woocommerce/woocommerce/issues/23623) to load the cart only on the frontend

I have a wp rest api which handles some special add_to_cart functionality which doesn't work anymore in wc 3.6 because cart is null, the cart functions are also not loaded so I can't just do $cart = new WC_Cart().

And no cart lazy loading function was provided.

A function like wc_load_cart() which would load the functions for cases like this should have been made.
Or a check on the wc instance when trying to access the unexisting cart property to lazy load it (with the __get magic method)

Because a lot, and I really mean a lot of plugins use WC()->cart in rest api calls.. 
I'm amazed there is not tons of complaints already

**Comment by kloon** [comment]
See #23794 for fix. We will see if this makes it into the next fix release or the 3.7 release. Keep an eye on the PR for details.

**Comment by seb86** [comment]
@Tofandel I already fixed this issue in [CoCart](https://wordpress.org/plugins/cart-rest-api-for-woocommerce/). You might want to check it out.

**Comment by SimonMayerhofer** [comment]
For anyone interested in this functionality, i had a deeper look on how it is solved by @seb86 in CoCart.
The important part is the following function. I enhanced it a bit so it's only loaded on requests to the REST API with a specific prefix.

```

add_action( 'wp_loaded', 'maybe_load_cart', 5 );
/**
 * Loads the cart, session and notices should it be required.
 *
 * Note: Only needed should the site be running WooCommerce 3.6
 * or higher as they are not included during a REST request.
 *
 * @see https://plugins.trac.wordpress.org/browser/cart-rest-api-for-woocommerce/trunk/includes/class-cocart-init.php#L145
 * @since   2.0.0
 * @version 2.0.3
 */
function maybe_load_cart() {
	if ( version_compare( WC_VERSION, '3.6.0', '>=' ) && WC()->is_rest_api_request() ) {
		if ( empty( $_SERVER['REQUEST_URI'] ) ) {
			return;
		}

		$rest_prefix = 'your/endpoint/prefix';
		$req_uri     = esc_url_raw( wp_unslash( $_SERVER['REQUEST_URI'] ) );

		$is_my_endpoint = ( false !== strpos( $req_uri, $rest_prefix ) );

		if ( ! $is_my_endpoint ) {
			return;
		}

		require_once WC_ABSPATH . 'includes/wc-cart-functions.php';
		require_once WC_ABSPATH . 'includes/wc-notice-functions.php';

		if ( null === WC()->session ) {
			$session_class = apply_filters( 'woocommerce_session_handler', 'WC_Session_Handler' ); // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedHooknameFound

			// Prefix session class with global namespace if not already namespaced
			if ( false === strpos( $session_class, '\\' ) ) {
				$session_class = '\\' . $session_class;
			}

			WC()->session = new $session_class();
			WC()->session->init();
		}

		/**
		 * For logged in customers, pull data from their account rather than the
		 * session which may contain incomplete data.
		 */
		if ( is_null( WC()->customer ) ) {
			if ( is_user_logged_in() ) {
				WC()->customer = new WC_Customer( get_current_user_id() );
			} else {
				WC()->customer = new WC_Customer( get_current_user_id(), true );
			}

			// Customer should be saved during shutdown.
			add_action( 'shutdown', array( WC()->customer, 'save' ), 10 );
		}

		// Load Cart.
		if ( null === WC()->cart ) {
			WC()->cart = new WC_Cart();
		}
	}
} // END maybe_load_cart()
```
