### ISSUE TITLE
Schema.org error due to https

### ISSUE THREAD

**Issue by melindahelt** [woocommerce/woocommerce#23798]
User stoped into live chat to report the following:

class-wc-structured-data.php line 260

'availability' => 'https://schema.org/' . ( $product->is_in_stock() ? 'InStock' : 'OutOfStock' ),

/// This needs to be changed to http://schema.org

-> Causes warning in Google Search Console if left with https

They reported making the change in their plugin and the console error went away and would like this included in the next release

**Comment by rodrigoprimo** [comment]
@melindahelt, did they provide more details? Things like the warning message displayed in the Google Search Console and the system status report would help understand this problem. I think it is unlikely that the solution will be replacing `https://schema.org` with `http://schema.org`.

**Comment by melindahelt** [comment]
`
### WordPress Environment ###

WordPress address (URL): 
Site address (URL): 
WC Version: 3.6.3
Log Directory Writable: ✔
WP Version: 5.2.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.3
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.43-cll-lve
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.3
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 9.67MB
Datenbank-Datengröße: 7.87MB
Datenbank-Indexgröße: 1.80MB
wp_woocommerce_sessions: Daten: 0.02MB + Index: 0.00MB
wp_woocommerce_api_keys: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_attribute_taxonomies: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Daten: 0.03MB + Index: 0.01MB
wp_woocommerce_tax_rates: Daten: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Daten: 0.00MB + Index: 0.00MB
wp_commentmeta: Daten: 0.00MB + Index: 0.00MB
wp_comments: Daten: 0.01MB + Index: 0.02MB
wp_failed_jobs: Daten: 0.00MB + Index: 0.00MB
wp_links: Daten: 0.00MB + Index: 0.00MB
wp_mailchimp_carts: Daten: 0.01MB + Index: 0.00MB
wp_mc4wp_log: Daten: 0.00MB + Index: 0.00MB
wp_options: Daten: 1.06MB + Index: 0.07MB
wp_postmeta: Daten: 3.47MB + Index: 1.05MB
wp_posts: Daten: 0.87MB + Index: 0.12MB
wp_queue: Daten: 0.00MB + Index: 0.00MB
wp_revslider_css: Daten: 0.09MB + Index: 0.00MB
wp_revslider_layer_animations: Daten: 0.00MB + Index: 0.00MB
wp_revslider_navigations: Daten: 0.00MB + Index: 0.00MB
wp_revslider_sliders: Daten: 0.02MB + Index: 0.00MB
wp_revslider_slides: Daten: 1.02MB + Index: 0.00MB
wp_revslider_static_slides: Daten: 0.00MB + Index: 0.00MB
wp_statistics_exclusions: Daten: 0.00MB + Index: 0.00MB
wp_statistics_historical: Daten: 0.00MB + Index: 0.00MB
wp_statistics_pages: Daten: 0.00MB + Index: 0.00MB
wp_statistics_search: Daten: 0.00MB + Index: 0.00MB
wp_statistics_useronline: Daten: 0.00MB + Index: 0.00MB
wp_statistics_visit: Daten: 0.00MB + Index: 0.00MB
wp_statistics_visitor: Daten: 0.00MB + Index: 0.02MB
wp_termmeta: Daten: 0.01MB + Index: 0.02MB
wp_terms: Daten: 0.06MB + Index: 0.12MB
wp_term_relationships: Daten: 0.03MB + Index: 0.05MB
wp_term_taxonomy: Daten: 0.05MB + Index: 0.05MB
wp_usermeta: Daten: 0.04MB + Index: 0.04MB
wp_users: Daten: 0.00MB + Index: 0.01MB
wp_wc_download_log: Daten: 0.00MB + Index: 0.00MB
wp_wc_gpf_render_cache: Daten: 0.00MB + Index: 0.00MB
wp_wc_product_meta_lookup: Daten: 0.05MB + Index: 0.08MB
wp_wc_webhooks: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_gpf_google_taxonomy: Daten: 0.90MB + Index: 0.00MB
wp_wpforms_entries: Daten: 0.00MB + Index: 0.00MB
wp_wpforms_entry_fields: Daten: 0.00MB + Index: 0.00MB
wp_wpforms_entry_meta: Daten: 0.00MB + Index: 0.00MB
wp_yoast_seo_links: Daten: 0.01MB + Index: 0.01MB
wp_yoast_seo_meta: Daten: 0.12MB + Index: 0.12MB

### Post Type Counts ###

attachment: 543
boxzilla-box: 3
flycart_wmc_coupon: 8
mc4wp-form: 1
nav_menu_item: 14
page: 22
post: 1
product: 25
product_variation: 763
scheduled-action: 25
shop_coupon: 6
shop_order: 9
the_grid: 3
vc_settings_preset: 2
wc_product_tab: 3
woo_mb_template: 11
wpcf7_contact_form: 1
wpforms: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (46) ###

Query Monitor: von John Blackbourn – 3.3.6
Boxzilla - Exit Intent: von ibericode – 1.0.1
Boxzilla - Google Analytics: von ibericode – 1.1.5
Boxzilla - MailChimp integration: von ibericode – 1.1.2
Boxzilla - Pageviews: von ibericode – 1.0.1
Boxzilla - Theme Pack: von ibericode – 1.1.4
Boxzilla - Time On Site: von ibericode – 1.0.1
Boxzilla - WooCommerce: von ibericode – 1.0.1 – Nicht getestest mit der aktiven WooCommerce-Version
Boxzilla: von ibericode – 3.2.11
Payment Gateway Based Fees and Discounts for WooCommerce Pro: von Tyche Softwares – 2.5.5 – Nicht getestest mit der aktiven WooCommerce-Version
Contact Form 7: von Takayuki Miyoshi – 5.1.3
Envato Market: von Envato – 2.0.1
Head, Footer and Post Injections: von Stefano Lissa – 3.1.3
IgniteWoo Updater: von IgniteWoo.com – 2.1.12
WPBakery Page Builder: von Michael M - WPBakery.com – 6.0.2
Loco Translate: von Tim Whitlock – 2.2.2
Mailchimp for WordPress: von ibericode – 4.5.2
MailChimp for WordPress - Top Bar: von ibericode – 1.3.2
MailChimp for WordPress - Premium: von ibericode – 4.5.7
ModuloBox: von Themeone – 1.5.0
Savoy Theme - Instagram Gallery: von NordicMade – 1.0
Savoy Theme - Portfolio: von NordicMade – 1.0.8
Savoy Theme - Team Members: von NordicMade – 1.0.7
Savoy Theme - Wishlist: von NordicMade – 2.0.2
Official Facebook-Pixel: von Facebook – 1.7.25
Slider Revolution: von ThemePunch – 5.4.8.3
ShortPixel Image Optimizer: von ShortPixel – 4.13.1
WooCommerce Blöcke: von Automattic – 2.1.0
PayPal PLUS für WooCommerce: von Inpsyde GmbH – 2.0.2
WooCommerce Checkout Field Editor: von WooCommerce – 1.5.18
WooCommerce Google Analytics Pro: von SkyVerge – 1.7.1
WooCommerce Manager Pro: von IgniteWoo – 4.0.9 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce PDF Invoices: von Andrew Benbow – 4.4.2 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Google Product Feed: von Ademti Software Ltd. – 7.8.8
WooCommerce Slack: von WooCommerce – 1.1.12
WooCommerce Tab Manager: von SkyVerge – 1.10.1
WooCommerce: von Automattic – 3.6.3
WooCommerce Email Customizer with Drag and Drop Email Builder: von Flycart Technologies LLP – 1.5.10
Yoast SEO Premium: von Team Yoast – 11.2.1
WP Mail SMTP: von WPForms – 1.4.2
WP Rocket: von WP Media – 3.3.3.1
WP Rollback: von Impress.org – 1.6
WP Staging Pro: von WP-Staging
René Hermenau – 2.8.4

WPForms MailChimp: von WPForms – 1.3.0
WPForms: von WPForms – 1.5.2.3
Yoast SEO: WooCommerce: von Team Yoast – 11.2 – Nicht getestest mit der aktiven WooCommerce-Version

### Inactive Plugins (1) ###

Mailchimp for WooCommerce: von Mailchimp – 2.1.16 – Nicht getestest mit der aktiven WooCommerce-Version

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class
object-cache.php: Memcached Redux

### Must Use Plugins (1) ###

WP Staging Optimizer: von René Hermenau – 1.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
hidden (hidden)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
visible (visible)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop-Basis: #8 - /shop/
Warenkorb: #9 - /warenkorb/
Kasse: #10 - /kasse/
Mein Konto: #11 - /mein-konto/
Allgemeine Geschäftsbedingungen: #20 - /agb/

### Theme ###

Name: Savoy Child
Version: 1.0.1
Author URL: http://www.nordicmade.com
Child Theme: ✔
Parent Theme Name: Savoy
Parent Theme Version: 2.1.5
Parent Theme Author URL: http://www.nordicmade.com
WooCommerce Support: ✔

### Templates ###

Overrides: savoy/woocommerce/archive-product.php
savoy/woocommerce/cart/cart-empty.php
savoy/woocommerce/cart/cart-item-data.php
savoy/woocommerce/cart/cart-shipping.php
savoy/woocommerce/cart/cart-totals.php
savoy/woocommerce/cart/cart.php
savoy/woocommerce/cart/cross-sells.php
savoy/woocommerce/cart/mini-cart.php
savoy/woocommerce/cart/proceed-to-checkout-button.php
savoy/woocommerce/cart/shipping-calculator.php
savoy/woocommerce/checkout/cart-errors.php
savoy/woocommerce/checkout/form-billing.php
savoy/woocommerce/checkout/form-checkout.php
savoy/woocommerce/checkout/form-coupon.php
savoy/woocommerce/checkout/form-login.php
savoy/woocommerce/checkout/form-pay.php
savoy/woocommerce/checkout/form-shipping.php
savoy/woocommerce/checkout/payment-method.php
savoy/woocommerce/checkout/payment.php
savoy/woocommerce/checkout/review-order.php
savoy/woocommerce/checkout/terms.php
savoy/woocommerce/checkout/thankyou.php
savoy/woocommerce/content-product.php
savoy/woocommerce/content-product_cat.php
savoy/woocommerce/content-single-product.php
savoy/woocommerce/content-widget-product.php
savoy/woocommerce/content-widget-reviews.php
savoy/woocommerce/global/breadcrumb.php
savoy/woocommerce/global/form-login.php
savoy/woocommerce/global/quantity-input.php
savoy/woocommerce/global/sidebar.php
savoy/woocommerce/global/wrapper-end.php
savoy/woocommerce/global/wrapper-start.php
savoy/woocommerce/loop/add-to-cart.php
savoy/woocommerce/loop/loop-end.php
savoy/woocommerce/loop/loop-start.php
savoy/woocommerce/loop/no-products-found.php
savoy/woocommerce/loop/pagination.php
savoy/woocommerce/loop/price.php
savoy/woocommerce/loop/rating.php
savoy/woocommerce/loop/sale-flash.php
savoy-child/woocommerce/myaccount/dashboard.php
savoy/woocommerce/myaccount/downloads.php
savoy/woocommerce/myaccount/form-add-payment-method.php
savoy/woocommerce/myaccount/form-edit-account.php
savoy/woocommerce/myaccount/form-edit-address.php
savoy/woocommerce/myaccount/form-login.php
savoy/woocommerce/myaccount/form-lost-password.php
savoy/woocommerce/myaccount/form-reset-password.php
savoy/woocommerce/myaccount/lost-password-confirmation.php
savoy/woocommerce/myaccount/my-account.php
savoy/woocommerce/myaccount/my-address.php
savoy/woocommerce/myaccount/navigation.php
savoy/woocommerce/myaccount/orders.php
savoy/woocommerce/myaccount/payment-methods.php
savoy/woocommerce/myaccount/view-order.php
savoy/woocommerce/notices/error.php
savoy/woocommerce/notices/notice.php
savoy/woocommerce/notices/success.php
savoy/woocommerce/order/form-tracking.php
savoy/woocommerce/order/order-again.php
savoy/woocommerce/order/order-details-customer.php
savoy/woocommerce/order/order-details-item.php
savoy/woocommerce/order/order-details.php
savoy/woocommerce/order/tracking.php
savoy/woocommerce/product-searchform.php
savoy/woocommerce/single-product/add-to-cart/external.php
savoy/woocommerce/single-product/add-to-cart/grouped.php
savoy/woocommerce/single-product/add-to-cart/simple.php
savoy/woocommerce/single-product/add-to-cart/variable.php
savoy/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
savoy/woocommerce/single-product/add-to-cart/variation.php
savoy/woocommerce/single-product/meta.php
savoy/woocommerce/single-product/photoswipe.php
savoy/woocommerce/single-product/price.php
savoy/woocommerce/single-product/product-attributes.php
savoy/woocommerce/single-product/product-image.php
savoy/woocommerce/single-product/product-thumbnails.php
savoy/woocommerce/single-product/rating.php
savoy/woocommerce/single-product/related.php
savoy/woocommerce/single-product/review-meta.php
savoy/woocommerce/single-product/review-rating.php
savoy/woocommerce/single-product/review.php
savoy/woocommerce/single-product/sale-flash.php
savoy/woocommerce/single-product/share.php
savoy/woocommerce/single-product/short-description.php
savoy/woocommerce/single-product/stock.php
savoy/woocommerce/single-product/tabs/additional-information.php
savoy/woocommerce/single-product/tabs/description.php
savoy/woocommerce/single-product/tabs/tabs.php
savoy/woocommerce/single-product/title.php
savoy/woocommerce/single-product/up-sells.php
savoy/woocommerce/single-product-reviews.php
savoy/woocommerce/single-product.php
savoy/woocommerce/taxonomy-product_cat.php
savoy/woocommerce/taxonomy-product_tag.php

### WooCommerce Google Product Feed fields ###

Product description: Main product description only (short preferred.)
Availability: Defaults to "in stock".
Bundle indicator (is_bundle):
Condition: Defaults to "new".
Brand: Defaults to "Herr Lars moebelmanufaktur".
Manufacturer Part Number (MPN): Pre-populates from product sku.
Product Type: Pre-populates from product_cat taxonomy.
Google Product Category: Defaults to "Moebel".
Material: Pre-populates from pa_holz taxonomy.
Delivery label: Pre-populates from product_shipping_class taxonomy.

### WooCommerce Google Product Feed options ###

Include variations in feed: No
Send item_group_id: Enabled

### Action Scheduler ###

Complete: 23
Oldest: 2019-04-23 17:02:57 +0200
Newest: 2019-05-20 20:29:16 +0200

Pending: 2
Oldest: 2019-05-23 15:47:02 +0200
Newest: 2019-05-23 15:47:02 +0200

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
They also said:
• see schema.org reference for availability: https://schema.org/InStock
• woocommerce outputs the structured data with every product as json-ld
• its all fine with my shop, i've changed the line in the woocommerce file and now Google Search Console is happy

They made the change, then WC updated and change was lost so they made it again and let us know.

That's all I know for this issue.

**Comment by rodrigoprimo** [comment]
@melindahelt could you please ask them what was the warning?

**Comment by claudiosanches** [comment]
See https://github.com/woocommerce/woocommerce/pull/23774
