### ISSUE TITLE
stock was called incorrectly. Product properties should not be accessed directly.

### ISSUE THREAD

**Issue by mcsalesllc** [woocommerce/woocommerce#23795]
Receiving these errors in my error log when customers place an order.
The stock changes as it should when an order is placed

May 21, 17:59:01
stock was called incorrectly. Product properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Braintree\Plugin_Framework\SV_WC_Payment_Gateway_Direct->process_payment, WC_Order->payment_complete, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_processing'), WP_Hook->do_action, WP_Hook->apply_filters, wc_maybe_reduce_stock_levels, wc_reduce_stock_levels, do_action('woocommerce_reduce_order_stock'), WP_Hook->do_action, WP_Hook->apply_filters, OrderWrapper::handle_reduce_order_stock, WC_Abstract_Legacy_Product->__get, wc_doing_it_wrong. This message was added in version 3.0.
 
May 21, 17:59:00
Warning: preg_replace(): Compilation failed: invalid range in character class at offset 4 in /home/dh_dvap5v/mc-salesllc.com/wp-content/plugins/woocommerce-gateway-paypal-powered-by-braintree/includes/api/requests/class-wc-braintree-api-transaction-request.php on line 209

**Comment by kloon** [comment]
Your payment gateway is calling product properties directly and not using the getters provided for accessing properties. I suggest you contact the developers of the gateway for support. This platform is only for WooCommerce core issues and not for reporting issues within plugins/themes.
