### ISSUE TITLE
Shipping Calculator cannot hide rates for unwanted states

### ISSUE THREAD

**Issue by chirag255** [woocommerce/woocommerce#23805]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Go to Woocommerce > Settings > Shipping > Shipping Zones
2. Removed state from Region (In my case Canada, Quebec)
3. Go to Cart page. Use correct postal code for Quebec (G0A 4V0), but change state to any other allowed states (use Ontario)

## Screen shot
https://ibb.co/stFXVNd

## Expected/actual behavior

I was expecting to see shipping rates should not be displayed if I am using postal codes from disallowed states

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

</details>

**Comment by kloon** [comment]
If you want to limit shipping by postal codes instead of states then you will need to specify the postal codes instead of just relying on the states. WooCommerce does not have built in state to postal code verification.

Under your shipping zone regions, there's a link to enter postal codes https://cld.wthms.co/Qj81on
