### ISSUE TITLE
Attributes get mixed up on a full product CSV export

### ISSUE THREAD

**Issue by johangarzon** [woocommerce/woocommerce#23801]
**Bug description**
This may be an intended behavior, but I would like to make sure it is not a bug.
The attribute order gets mixed up when running a full products CSV export.
For example, I load many articles with:

SKU;Attribute name 1;Attribute value 1;Attribute name 2;Attribute value 2
1;brand;omega;color;silver
2;brand;longines;color;green

When I run a full products export, the resuting CSV is as follows:
SKU;Attribute name 1;Attribute value 1;Attribute name 2;Attribute value 2
1;color;silver;brand;omega
2;brand;longines;color;green

**To Reproduce**
Load products using the CSV import.
Export products using the CSV export and export all columns.

**Screenshots**

**Expected behavior**
I would expect all attributes keep their attribute number, so if "Brand" was oaded as Attribute 1, it should be sexported as attribute 1, so that the exports don't have the column "Attribute 1 name" many different attributes.

### WordPress Environment ###

WordPress address (URL): http://developmentmto.wpengine.com/de-de
Site address (URL): http://developmentmto.wpengine.com/de-de
WC Version: 3.6.3
Log Directory Writable: ✔
WP Version: 5.2.1
WP Multisite: ✔
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.4-1+ubuntu18.04.1+deb.sury.org+3
PHP Post Max Size: 200 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1b

SUHOSIN Installed: –
MySQL Version: 5.7.25-28-log
Max Upload Size: 195 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.3
WC Database Prefix: wp_4_
Total Database Size: 334.14MB
Database Data Size: 258.98MB
Database Index Size: 75.16MB
wp_4_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_4_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_4_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_4_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_4_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_4_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_4_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_4_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_4_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_4_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_4_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_4_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_4_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_4_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_4_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_4_comments: Data: 0.02MB + Index: 0.09MB
wp_4_links: Data: 0.02MB + Index: 0.02MB
wp_4_options: Data: 15.52MB + Index: 2.92MB
wp_4_pmxi_files: Data: 0.02MB + Index: 0.00MB
wp_4_pmxi_history: Data: 0.02MB + Index: 0.00MB
wp_4_pmxi_images: Data: 0.02MB + Index: 0.00MB
wp_4_pmxi_imports: Data: 0.02MB + Index: 0.00MB
wp_4_pmxi_posts: Data: 0.02MB + Index: 0.03MB
wp_4_pmxi_templates: Data: 0.02MB + Index: 0.00MB
wp_4_postmeta: Data: 189.75MB + Index: 36.11MB
wp_4_posts: Data: 30.56MB + Index: 16.13MB
wp_4_termmeta: Data: 1.52MB + Index: 2.02MB
wp_4_terms: Data: 3.52MB + Index: 5.03MB
wp_4_term_relationships: Data: 8.52MB + Index: 7.52MB
wp_4_term_taxonomy: Data: 2.52MB + Index: 3.03MB
wp_4_wc_product_meta_lookup: Data: 1.52MB + Index: 1.45MB
wp_4_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_4_woof_query_cache: Data: 0.02MB + Index: 0.02MB
wp_4_yoast_seo_links: Data: 0.11MB + Index: 0.05MB
wp_4_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB
wp_blogmeta: Data: 0.02MB + Index: 0.03MB
wp_blogs: Data: 0.02MB + Index: 0.03MB
wp_blog_versions: Data: 0.02MB + Index: 0.02MB
wp_registration_log: Data: 0.02MB + Index: 0.02MB
wp_signups: Data: 0.02MB + Index: 0.06MB
wp_site: Data: 0.02MB + Index: 0.02MB
wp_sitemeta: Data: 3.05MB + Index: 0.03MB
wp_usermeta: Data: 0.23MB + Index: 0.06MB
wp_users: Data: 0.02MB + Index: 0.05MB

### Post Type Counts ###

attachment: 51883
branding_col_bot: 8
branding_col_top: 1
branding_collection: 2
customize_changeset: 2
nav_menu_item: 266
ocw_carousel: 1
oembed_cache: 72
page: 60
portfolio: 8
post: 169
product: 10588
product_variation: 14
revision: 56
sa_slider: 1
scheduled-action: 19
shop_coupon: 2
shop_order: 15
shop_order_refund: 1
team: 30
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (26) ###

Trustbadge Reviews for WooCommerce: by Vendidero – 3.0.2 – Not tested with the active version of WooCommerce
Contact Form 7: by Takayuki Miyoshi – 5.1.3
Disable Real MIME Check: by Sergey Biryukov – 1.0
Duplicate Post: by Enrico Battocchi – 3.2.2
Envato Market: by Envato – 2.0.1
NS Cloner - Site Copier: by Never Settle – 3.1.1
NS Cloner Pro: by Never Settle – 3.1.3
Search by Algolia – Instant & Relevant results: by Algolia – 2.11.3
SVG Support: by Benbodhi – 2.3.15
Ultimate Addons for WPBakery Page Builder: by Brainstorm Force – 3.18.0
User Role Editor: by Vladimir Garagulya – 4.51
Savoy Theme - Instagram Gallery: by NordicMade – 1.0
Savoy Theme - Portfolio: by NordicMade – 1.0.8
Savoy Theme - Team Members: by NordicMade – 1.0.7
Yoast SEO Premium: by Team Yoast – 11.2.1
Custom Post Widget Montredo: by Montredo – 1.0.0
WooCommerce Multi-currency: by WooCommerce – 1.14.0 – Not tested with the active version of WooCommerce
Wirecard WooCommerce Extension: by Wirecard AG – 1.6.5 – Not tested with the active version of WooCommerce
Multiple Category Image Montredo: by Montredo – 1.0.0
Savoy Theme - Wishlist: by NordicMade – 2.0.4
Trustbadge Reviews for WooCommerce: by Vendidero – 3.0.2 – Not tested with the active version of WooCommerce
WP Rocket: by WP Media – 3.3.3.1
Trustpilot-reviews: by Trustpilot – 2.5.695 – Not tested with the active version of WooCommerce
MyFontsWebfontsKit #3759853: by MyFonts Team – 0.1
WooCommerce: by Automattic – 3.6.3
WPBakery Page Builder: by Michael M - WPBakery.com – 6.0.2

### Inactive Plugins (6) ###

Google Tag Manager for Wordpress: by Thomas Geiger – 1.9.2 – Not tested with the active version of WooCommerce
Jetpack by WordPress.com: by Automattic – 7.3.1
Mailchimp for WooCommerce: by Mailchimp – 2.1.16 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.20.0
WOOF - WooCommerce Products Filter: by realmag777 – 1.2.2.1 – Not tested with the active version of WooCommerce
WP Offload Media: by Delicious Brains – 2.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (3) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.6.4
Stop long comments: by WPEngine – 0.0.4
WP Engine System: by WP Engine – 3.2.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #4 - /shop/
Basket: #824 - /cart-2/
Checkout: #761 - /checkout-2/
My account: #825 - /my-account-2/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Savoy Child
Version: – 0 is available
Author URL: 
Child Theme: ✔
Parent Theme Name: Savoy
Parent Theme Version: 2.1.7
Parent Theme Author URL: http://www.nordicmade.com
WooCommerce Support: ✔

### Templates ###

Overrides: savoy-child/woocommerce/archive-product.php
savoy-child/woocommerce/cart/cart-empty.php
savoy/woocommerce/cart/cart-item-data.php
savoy/woocommerce/cart/cart-shipping.php
savoy/woocommerce/cart/cart-totals.php
savoy-child/woocommerce/cart/cart.php
savoy/woocommerce/cart/cross-sells.php
savoy/woocommerce/cart/mini-cart.php
savoy/woocommerce/cart/proceed-to-checkout-button.php
savoy/woocommerce/cart/shipping-calculator.php
savoy/woocommerce/checkout/cart-errors.php
savoy/woocommerce/checkout/form-billing.php
savoy/woocommerce/checkout/form-checkout.php
savoy/woocommerce/checkout/form-coupon.php
savoy/woocommerce/checkout/form-login.php
savoy/woocommerce/checkout/form-pay.php
savoy/woocommerce/checkout/form-shipping.php
savoy/woocommerce/checkout/payment-method.php
savoy/woocommerce/checkout/payment.php
savoy/woocommerce/checkout/review-order.php
savoy/woocommerce/checkout/terms.php
savoy/woocommerce/checkout/thankyou.php
savoy-child/woocommerce/content-product.php
savoy/woocommerce/content-product_cat.php
savoy-child/woocommerce/content-single-product.php
savoy/woocommerce/content-widget-product.php
savoy/woocommerce/content-widget-reviews.php
savoy/woocommerce/global/breadcrumb.php
savoy/woocommerce/global/form-login.php
savoy/woocommerce/global/quantity-input.php
savoy/woocommerce/global/sidebar.php
savoy/woocommerce/global/wrapper-end.php
savoy/woocommerce/global/wrapper-start.php
savoy/woocommerce/loop/add-to-cart.php
savoy/woocommerce/loop/loop-end.php
savoy/woocommerce/loop/loop-start.php
savoy/woocommerce/loop/no-products-found.php
savoy/woocommerce/loop/pagination.php
savoy/woocommerce/loop/price.php
savoy/woocommerce/loop/rating.php
savoy/woocommerce/loop/sale-flash.php
savoy/woocommerce/myaccount/dashboard.php
savoy/woocommerce/myaccount/downloads.php
savoy/woocommerce/myaccount/form-add-payment-method.php
savoy/woocommerce/myaccount/form-edit-account.php
savoy/woocommerce/myaccount/form-edit-address.php
savoy/woocommerce/myaccount/form-login.php
savoy/woocommerce/myaccount/form-lost-password.php
savoy/woocommerce/myaccount/form-reset-password.php
savoy/woocommerce/myaccount/lost-password-confirmation.php
savoy/woocommerce/myaccount/my-account.php
savoy/woocommerce/myaccount/my-address.php
savoy/woocommerce/myaccount/navigation.php
savoy/woocommerce/myaccount/orders.php
savoy/woocommerce/myaccount/payment-methods.php
savoy/woocommerce/myaccount/view-order.php
savoy/woocommerce/notices/error.php
savoy/woocommerce/notices/notice.php
savoy/woocommerce/notices/success.php
savoy/woocommerce/order/form-tracking.php
savoy/woocommerce/order/order-again.php
savoy/woocommerce/order/order-details-customer.php
savoy/woocommerce/order/order-details-item.php
savoy/woocommerce/order/order-details.php
savoy/woocommerce/order/tracking.php
savoy/woocommerce/product-searchform.php
savoy/woocommerce/single-product/add-to-cart/external.php
savoy/woocommerce/single-product/add-to-cart/grouped.php
savoy-child/woocommerce/single-product/add-to-cart/simple.php
savoy-child/woocommerce/single-product/add-to-cart/variable.php
savoy-child/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
savoy/woocommerce/single-product/add-to-cart/variation.php
savoy/woocommerce/single-product/meta.php
savoy/woocommerce/single-product/photoswipe.php
savoy-child/woocommerce/single-product/price.php
savoy/woocommerce/single-product/product-attributes.php
savoy-child/woocommerce/single-product/product-image.php
savoy/woocommerce/single-product/product-thumbnails.php
savoy/woocommerce/single-product/rating.php
savoy-child/woocommerce/single-product/related.php
savoy/woocommerce/single-product/review-meta.php
savoy/woocommerce/single-product/review-rating.php
savoy/woocommerce/single-product/review.php
savoy/woocommerce/single-product/sale-flash.php
savoy-child/woocommerce/single-product/share.php
savoy/woocommerce/single-product/short-description.php
savoy/woocommerce/single-product/stock.php
savoy/woocommerce/single-product/tabs/additional-information.php
savoy/woocommerce/single-product/tabs/description.php
savoy/woocommerce/single-product/tabs/tabs.php
savoy-child/woocommerce/single-product/title.php
savoy/woocommerce/single-product/up-sells.php
savoy/woocommerce/single-product-reviews.php
savoy/woocommerce/single-product.php
savoy/woocommerce/taxonomy-product_cat.php
savoy/woocommerce/taxonomy-product_tag.php

### Multi-currency ###

currency_symbol_EUR: -
enabled_currencies: a:13:{i:0;s:3:"AED";i:1;s:3:"AUD";i:2;s:3:"CHF";i:3;s:3:"DKK";i:4;s:3:"EUR";i:5;s:3:"GBP";i:6;s:3:"MXN";i:7;s:3:"NOK";i:8;s:3:"NZD";i:9;s:3:"SEK";i:10;s:3:"SGD";i:11;s:3:"USD";i:12;s:3:"ZAR";}
fee_percent: 0
price_charm: 1
price_format_EUR: -
rates: array(171)
rates_provider_id: OpenExchangeRates
rates_timestamp: 1558573200
round_to: 10
version: 1.14.0

### Action Scheduler ###

Complete: 18
Oldest: 2019-04-24 10:16:25 +0200
Newest: 2019-05-22 17:59:00 +0200

Pending: 1
Oldest: 2019-05-29 17:59:00 +0200
Newest: 2019-05-29 17:59:00 +0200

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by erdalcicek** [comment]
Hello 

Did you solve this problem? I have the same problem and couldn't find a solution.
