### ISSUE TITLE
WC() cart is not accessible in REST API endpoint

### ISSUE THREAD

**Issue by uprise10** [woocommerce/woocommerce#23800]
**Describe the bug**
We've got a site with a custom REST API endpoint in order to retrieve the cart counts with the following code:

```php
add_action('rest_api_init', function() {
	register_rest_route( 'our_endpoint/v1', '/get_cart_count', array(
		'methods' => 'POST',
		'callback' => function() {
			global $woocommerce;
			$params = array( 'cart_count' => $woocommerce->cart->cart_contents_count );
			return $params;
		},
	) );
});
```

However, the `$woocommerce->cart` is empty within this endpoint request. Also tried it with `WC()` instead of the global variable, but that doesn't matter. The code is working in regular templates of the theme, and even with admin-ajax.php request, but just not within the REST API.

**To Reproduce**
See above code.

**Screenshots**
n/a

**Expected behavior**
Obviously we'd expect the cart count :-)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WP 5.2
WooCommerce 3.6.3

Possibly this is related to #23792, but not sure that fix also covers the REST API

**Comment by seb86** [comment]
@uprise10 WooCommerce is not going to support cart via the REST-API. This is why I created [CoCart](https://cocart.xyz/). You should check it out.

**Comment by uprise10** [comment]
Hmm, bummer.. CoCart looks nice btw, thanks!

**Comment by claudiosanches** [comment]
We don't load the cart in the REST API because performance issues, also we don't intent to have a cart endpoint, you can handle sessions and so on in our app too, and use our REST API to fetch products and create the orders.

**Comment by SimonMayerhofer** [comment]
I just posted the solution from CoCart in #23792, for anyone who's interested.
