### ISSUE TITLE
Show/Hide depending on product type options

### ISSUE THREAD

**Issue by Ignasimg** [woocommerce/woocommerce#23809]
**Is your feature request related to a problem? Please describe.**
I was trying to develop a plugin that would add an option (checkbox) to the product type, like the default downloadable and virtual ones.
Surprise came when I intended to use the css classes show_if_... and hide_if_... as those were not working.

**Describe the solution you'd like**
I'd like it to work : )
I checked the code and same as the product type (from the select) are grabbed dynamically I feel the product type options (from the checkboxes) should also be; Right now they are hardcoded.

**Describe alternatives you've considered**
Leting the plugin take care of this - I feel it's a pain, because it's simply repeating code.

---

If you guys approve, might I pull this change? I didn't update it on my side yet but I'm quite clear what it should be like.

Thank you.

**Comment by kloon** [comment]
You are welcome to do a PR with proposed changes and we can take it from there. Just keep in mind it needs to be done dynamically as extensions/plugins can define custom product types and the changes needs to work across all product types no matter if they are defined in WooCommerce core or via a plugin.
