### ISSUE TITLE
Status Icons

### ISSUE THREAD

**Issue by amjad** [woocommerce/woocommerce#23816]
**Is your feature request related to a problem? Please describe.**
The big block of color text boxes are horrible and difficult to quickly identify the order status. 

**Describe the solution you'd like**
Bring back rounded status icons. 

**Describe alternatives you've considered**
Unable to customize the CSS to bring back the icons.

Is it possible to somehow customize the order status icons and make them how they were before? Any code snippet?

**Comment by kloon** [comment]
Perhaps provide some details as to the CSS you tried?

Research we did showed that the current text with different background colors is more easily identifiable, it is also more accessible to users who utilize screen readers.

Curious why you say it is difficult to identify? Each status has a different background and text color which should make each status stand out from the rest.

Also if you wish to change the css you can target the icons with `.order-status status-processing tips` just replace the processing part with the status you want to target.

**Comment by amjad** [comment]
@kloon, the colors are not very vibrant and are dull. I agree it may be suitable for people uses guided text. I guess we were just used to knowing that blue meant completed, yellow meant pending, green meant processing, red meant cancelled, etc. The icon was enough to give the information. Now the colors of statuses look pretty similar to each other, hard to tell from one look. 

In any case, I would like to know if its possible to do some custom css and bring back the old status icons?
