### ISSUE TITLE
Custom Sorting of Product Attributes - Actual issue for #20071 which was prematurely closed

### ISSUE THREAD

**Issue by MachineITSvcs** [woocommerce/woocommerce#23815]
Product Attributes dropdown on Product pages cannot be sorted either by arranging the product variations order or trying to order the attributes, under Products > Attributes in the Dashboard. When the page is refreshed, the custom sorting is reset. Sorting the variations when editing the products has no apparent affect.

You can probably recreate this issue by making a product with the Size attributes of 4GB, 8GB, 16GB, and 32GB and trying to order them in the dropdown.

I would suspect the expected behavior should be that you can arrange variations/attributes in a logical manner.

**Comment by kloon** [comment]
Continuing discussion in #20071
