### ISSUE TITLE
updating

### ISSUE THREAD

**Issue by Boeket4u** [woocommerce/woocommerce#23810]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
when updating the products page, it is impossible to edit the page neither text nor visually. there is no movement. what is the problem?
**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by Boeket4u** [comment]
It does not matter which plugin or theme I use, it is impossible to edit a description in the product page. I contacted yoast and they advise me to contact woocommerce

**Comment by claudiosanches** [comment]
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. I tried edit product descriptions and it appeared to work correctly.

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

Thanks!

**Comment by Boeket4u** [comment]
Hi, 














Hi, there is really a problem as you see the reply of Yoast below.. I contacted them first, This was their advice. It would be nice if you can solve this and donot close it as non-reducable.


Thank you for your patience while we investigated this issue. We apologize for the trouble you are experiencing with your site. As previously mentioned from our technical support team, the content editor does not load when WooCommerce is the only active plugin on your site. This means that your products cannot be updated by the core WooCommerce plugin.

Please contact the WooCommerce support team for assistance troubleshooting why you cannot see the content editor.

**Comment by Boeket4u** [comment]
Claudio Sanches schreef op 2019-05-24 20:44:

> Closed #23810 [1]. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

 

Links:
------
[1] https://github.com/woocommerce/woocommerce/issues/23810
[2]
https://github.com/woocommerce/woocommerce/issues/23810?email_source=notifications&amp;email_token=AL6KYWQAVXLWBWQI5ZOVXCLPXAZSXA5CNFSM4HPRIZ52YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGORUGIS5I#event-2366409077
[3]

**Comment by rrennick** [comment]
@Boeket4u WooCommerce support is at https://woocommerce.com/contact-us/.

**Comment by Boeket4u** [comment]
Hi, I cannot believe this. I tried to have contact, sent you messages by
mail, by view it on GitHub, I donot know anymore. No support, no answer,
no service, no contact, nothing..... 

I have a problem and cannot find it on your support page, sent you the
result of yoast, no reaction. May be it is better to deactivat the plug
in and close contact. I will look for another plugin. This is really
unbelievable of your arrogance., because giving at least an advice if I
have to buy a program to solve this problem. 

Boeket4u 

Ron Rennick schreef op 2019-05-25 04:33:

> @Boeket4u [1] WooCommerce support is at https://woocommerce.com/contact-us/. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

 

Links:
------
[1] https://github.com/Boeket4u
[2]
https://github.com/woocommerce/woocommerce/issues/23810?email_source=notifications&amp;email_token=AL6KYWUGEF7UE3DPGNAYPKLPXCQO7A5CNFSM4HPRIZ52YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWG4D5A#issuecomment-495829492
[3]

**Comment by claudiosanches** [comment]
@Boeket4u Have you read me last comment?

> Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

I'm asking for more details, just that, you can show me screenshots, or record a video of this bug, something to help me reproduce and then fix if it's really a problem on WooCommerce.
So I'm waiting for you post back anything that can help us to debug it.

Thanks!
