### ISSUE TITLE
Problem order by price in woocommerce

### ISSUE THREAD

**Issue by thibal2525** [woocommerce/woocommerce#23822]
Hi, I have a site made on woocommerce. When I sort my products by newest it's work fine. But when I sort my products by price it's not working. It's a totaly random ordering. When I refresh it's change the order but always by a random way. I precise I'm a french developper and I already try to: 

- Disable all plugins
- Update woocommerce
- Change the theme
- Change .htaccess

I don't understand why the problem persists on this site. I have the same theme on another site and it's work fine. If someone have an idea, it will be the best! Thanks. Here the site on an exemple category : http://lepoulpecalin.com/categorie-produit/massage/huiles-de-massage/

**Comment by peterfabian** [comment]
Hi, 

please provide [System status report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) so that we can better understand your issue.
 
It's most likely related to the new lookup table in WC 3.6, which you can try to troubleshoot as [explained in the wiki](https://github.com/woocommerce/woocommerce/wiki/3.6.x-notes-FAQ#i-am-having-issues-sortingsearching-by-sku-price-after-the-update).

**Comment by thibal2525** [comment]
`
### WordPress Environment ###

WordPress address (URL): https://lepoulpecalin.com
Site address (URL): https://lepoulpecalin.com
WC Version: 3.6.3
Log Directory Writable: ✔
WP Version: 5.2.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 5.6.40 - Nous recommandons d’utiliser PHP 7.2 ou supérieur pour optimiser les performances et la sécurité. Comment mettre à jour votre version de PHP ?
PHP Post Max Size: 512 MB
PHP Time Limit: 360
PHP Max Input Vars: 200000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 10.3.15-MariaDB
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.3.3
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Taille totale de la base de données: 128.12MB
Taille de la base de données: 82.92MB
Taille de l’index: 45.20MB
wp_woocommerce_sessions: Données : 4.02MB + Index: 0.08MB
wp_woocommerce_api_keys: Données : 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Données : 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Données : 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Données : 0.08MB + Index: 0.03MB
wp_woocommerce_tax_rates: Données : 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Données : 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Données : 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Données : 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Données : 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Données : 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Données : 0.02MB + Index: 0.03MB
wp_woocommerce_log: Données : 0.02MB + Index: 0.02MB
wp_aiowps_events: Données : 0.02MB + Index: 0.00MB
wp_aiowps_failed_logins: Données : 0.02MB + Index: 0.00MB
wp_aiowps_global_meta: Données : 0.02MB + Index: 0.00MB
wp_aiowps_login_activity: Données : 0.02MB + Index: 0.00MB
wp_aiowps_login_lockdown: Données : 0.02MB + Index: 0.00MB
wp_aiowps_permanent_block: Données : 0.02MB + Index: 0.00MB
wp_cf_forms: Données : 0.13MB + Index: 0.02MB
wp_cf_form_entries: Données : 0.02MB + Index: 0.06MB
wp_cf_form_entry_meta: Données : 0.02MB + Index: 0.03MB
wp_cf_form_entry_values: Données : 0.02MB + Index: 0.05MB
wp_cf_pro_messages: Données : 0.02MB + Index: 0.00MB
wp_cf_queue_failures: Données : 0.00MB + Index: 0.00MB
wp_cf_queue_jobs: Données : 0.00MB + Index: 0.00MB
wp_cf_tracking: Données : 0.02MB + Index: 0.00MB
wp_cf_tracking_meta: Données : 0.02MB + Index: 0.03MB
wp_commentmeta: Données : 0.02MB + Index: 0.03MB
wp_comments: Données : 0.02MB + Index: 0.09MB
wp_ewwwio_images: Données : 9.52MB + Index: 8.59MB
wp_ewwwio_queue: Données : 0.00MB + Index: 0.00MB
wp_hugeit_slider_slide: Données : 0.02MB + Index: 0.00MB
wp_hugeit_slider_slider: Données : 0.02MB + Index: 0.00MB
wp_links: Données : 0.02MB + Index: 0.02MB
wp_masterslider_options: Données : 0.05MB + Index: 0.02MB
wp_masterslider_sliders: Données : 0.02MB + Index: 0.02MB
wp_miwowidgets: Données : 0.02MB + Index: 0.03MB
wp_nf3_actions: Données : 0.02MB + Index: 0.00MB
wp_nf3_action_meta: Données : 0.02MB + Index: 0.00MB
wp_nf3_chunks: Données : 0.02MB + Index: 0.00MB
wp_nf3_fields: Données : 0.02MB + Index: 0.00MB
wp_nf3_field_meta: Données : 0.02MB + Index: 0.00MB
wp_nf3_forms: Données : 0.02MB + Index: 0.00MB
wp_nf3_form_meta: Données : 0.02MB + Index: 0.00MB
wp_nf3_objects: Données : 0.02MB + Index: 0.00MB
wp_nf3_object_meta: Données : 0.02MB + Index: 0.00MB
wp_nf3_relationships: Données : 0.02MB + Index: 0.00MB
wp_nf3_upgrades: Données : 0.02MB + Index: 0.00MB
wp_options: Données : 11.05MB + Index: 2.20MB
wp_postmeta: Données : 35.06MB + Index: 29.03MB
wp_posts: Données : 10.03MB + Index: 2.72MB
wp_rank_math_404_logs: Données : 0.00MB + Index: 0.00MB
wp_rank_math_internal_links: Données : 0.00MB + Index: 0.00MB
wp_rank_math_internal_meta: Données : 0.00MB + Index: 0.00MB
wp_rank_math_redirections: Données : 0.00MB + Index: 0.00MB
wp_rank_math_redirections_cache: Données : 0.00MB + Index: 0.00MB
wp_rank_math_sc_analytics: Données : 0.00MB + Index: 0.00MB
wp_revslider_css: Données : 0.13MB + Index: 0.00MB
wp_revslider_layer_animations: Données : 0.02MB + Index: 0.00MB
wp_revslider_navigations: Données : 0.02MB + Index: 0.00MB
wp_revslider_sliders: Données : 0.14MB + Index: 0.00MB
wp_revslider_slides: Données : 1.23MB + Index: 0.00MB
wp_revslider_static_slides: Données : 0.03MB + Index: 0.00MB
wp_sfa_abandoned_carts: Données : 0.13MB + Index: 0.00MB
wp_sgpb_subscribers: Données : 0.02MB + Index: 0.00MB
wp_sgpb_subscription_error_log: Données : 0.02MB + Index: 0.00MB
wp_termmeta: Données : 0.02MB + Index: 0.03MB
wp_terms: Données : 0.02MB + Index: 0.03MB
wp_term_relationships: Données : 1.02MB + Index: 0.06MB
wp_term_taxonomy: Données : 0.02MB + Index: 0.03MB
wp_usermeta: Données : 0.06MB + Index: 0.03MB
wp_users: Données : 0.02MB + Index: 0.05MB
wp_wcpdf_invoice_number: Données : 0.02MB + Index: 0.00MB
wp_wc_download_log: Données : 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Données : 0.00MB + Index: 0.01MB
wp_wc_webhooks: Données : 0.02MB + Index: 0.02MB
wp_wfBadLeechers: Données : 0.00MB + Index: 0.00MB
wp_wfBlockedCommentLog: Données : 0.00MB + Index: 0.00MB
wp_wfBlockedIPLog: Données : 0.04MB + Index: 0.03MB
wp_wfBlocks7: Données : 0.06MB + Index: 0.04MB
wp_wfConfig: Données : 1.54MB + Index: 0.02MB
wp_wfCrawlers: Données : 0.00MB + Index: 0.00MB
wp_wfFileChanges: Données : 0.00MB + Index: 0.00MB
wp_wfFileMods: Données : 2.07MB + Index: 0.44MB
wp_wfHits: Données : 2.55MB + Index: 0.69MB
wp_wfHoover: Données : 0.00MB + Index: 0.00MB
wp_wfIssues: Données : 0.05MB + Index: 0.01MB
wp_wfKnownFileList: Données : 1.07MB + Index: 0.13MB
wp_wfLeechers: Données : 0.06MB + Index: 0.05MB
wp_wfLiveTrafficHuman: Données : 0.00MB + Index: 0.01MB
wp_wfLocs: Données : 0.00MB + Index: 0.00MB
wp_wfLogins: Données : 0.11MB + Index: 0.03MB
wp_wfNet404s: Données : 0.00MB + Index: 0.00MB
wp_wfNotifications: Données : 0.00MB + Index: 0.00MB
wp_wfPendingIssues: Données : 0.00MB + Index: 0.01MB
wp_wfReverseCache: Données : 0.00MB + Index: 0.00MB
wp_wfScanners: Données : 0.00MB + Index: 0.00MB
wp_wfSNIPCache: Données : 0.00MB + Index: 0.00MB
wp_wfStatus: Données : 0.14MB + Index: 0.06MB
wp_wfTrafficRates: Données : 0.00MB + Index: 0.00MB
wp_wfVulnScanners: Données : 0.00MB + Index: 0.00MB
wp_wpmm_subscribers: Données : 0.02MB + Index: 0.00MB
wp_yith_wcwl: Données : 0.00MB + Index: 0.00MB
wp_yith_wcwl_lists: Données : 0.00MB + Index: 0.01MB
wp_yoast_seo_links: Données : 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Données : 1.45MB + Index: 0.00MB

### Post Type Counts ###

amn_wpforms-lite: 1
attachment: 6260
nav_menu_item: 63
page: 17
popupbuilder: 3
post: 2
product: 527
product_variation: 195
revision: 440
shop_coupon: 7
shop_order: 27
shop_order_refund: 1
testimonials: 2
wpcf7_contact_form: 5
ywrac_cart: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (53) ###

ManageWP - Worker: par ManageWP – 4.3.3
Advanced TinyMCE Configuration: par Andrew Ozz – 1.4
Black Studio TinyMCE Widget: par Black Studio – 2.6.2
Caldera Forms: par Caldera Labs – 1.8.4
CategoryTinymce: par Kevin Heath – 3.6.5
Caldera Forms Anti Spam: par Extensions Yoohoo – 0.1.2
Contact Form 7: par Takayuki Miyoshi – 5.1.1
Customize Admin: par Johan van der Wijk – 1.7.4
Disable Gutenberg: par Jeff Starr – 1.8.1
Disable WooCommerce Reviews: par pipdig – 1.1 – Non testé avec la version active de WooCommerce
Enhanced E-commerce for Woocommerce store: par Tatvic – 2.1.7
Envato Market: par Envato – 2.0.0
EWWW Image Optimizer: par Exactly WWW – 4.7.3
Hello Dolly: par Matt Mullenweg – 1.6
WPBakery Visual Composer: par Michael M - WPBakery.com – 5.0.1
kk Star Ratings: par Kamal Khan – 2.6.1
Master Slider WP: par averta – 2.7.2
Ninja Forms: par The WP Ninjas – 3.3.17
PHP Code Widget: par Otto – 2.3
Popup Builder: par Sygnoos – 3.2
Product CSV Import Export (BASIC): par WebToffee – 1.4.8 – Non testé avec la version active de WooCommerce
Quick Page/Post Redirect Plugin: par anadnet – 5.1.8
Really Simple SSL: par Rogier Lankhorst
Mark Wolters – 3.1.5

Slider Revolution: par ThemePunch – 5.4.7.2
Select Core: par Select Themes – 1.0.2
Select Instagram Feed: par Select Themes – 1.0
Select Twitter Feed: par Select Themes – 1.0
SF Taxonomy Thumbnail: par Grégory Viguier – 1.3
Simple Contact Info: par LehaMotovilov – 1.1.9
Simple Custom Post Order: par Colorlib – 2.4.2
Huge IT Slider: par Huge-IT – 4.0.6
String Locator: par Clorith – 2.3.1
TinyMCE Advanced: par Andrew Ozz – 4.8.0
Typekit Fonts for WordPress: par OM4 – 1.9.0
Abandoned Cart Reports For WooCommerce: par Small Fish Analytics – 2.5.1 – Non testé avec la version active de WooCommerce
Widget Importer & Exporter: par ChurchThemes.com – 1.5.5
Widget Logic: par wpchefgadget
alanft – 5.9.0

Widget Title Links: par Illimar Tambek – 1.4.1
WooCommerce Stripe Gateway: par WooCommerce – 4.1.16
WooCommerce Google Analytics Integration: par WooCommerce – 1.4.9
WooCommerce PDF Invoices & Packing Slips: par Ewout Fernhout – 2.2.12
WooCommerce Product SKU Generator: par SkyVerge – 2.3.4 – Non testé avec la version active de WooCommerce
WooCommerce: par Automattic – 3.6.3
Wordfence Security: par Wordfence – 7.2.5
Yoast SEO: par L’équipe Yoast – 11.2.1 – Non testé avec la version active de WooCommerce
WP Gallery Custom Links: par johnogg – 1.12
WP Lightbox 2: par Syed Balkhi – 3.0.6.2
WP Maintenance Mode: par Designmodo – 2.2.3
WP Rocket: par WP Media – 2.11.6
WPForms Lite: par WPForms – 1.4.9
YITH WooCommerce Quick View: par YITH – 1.3.9
YITH WooCommerce Recover Abandoned Cart: par YITH – 1.2.8 – Non testé avec la version active de WooCommerce
YITH WooCommerce Wishlist: par YITH – 2.2.10

### Inactive Plugins (0) ###


### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

ManageWP - Worker Loader: par ManageWP –

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la boutique: #4 - /boutique/
Panier: #5 - /panier/
Validation de la commande: #6 - /commande/
Mon compte: ❌ La page ne contient pas le code court.
Conditions générales de vente et d’utilisation: #17182 - /conditions-generales-de-vente/

### Theme ###

Name: Bazaar Child
Version: 1.0.0
Author URL: http://themeforest.net/user/select-themes
Child Theme: ✔
Parent Theme Name: Bazaar
Parent Theme Version: 1.2
Parent Theme Author URL: http://themeforest.net/user/select-themes
WooCommerce Support: ✔

### Templates ###

Archive Template: Votre thème a un fichier woocommerce.php
vous ne serez pas en mesure de substituer le modèle personnalisé woocommerce/archive-product.php étant donné que woocommerce.php a la priorité sur archive-product.php. Ceci vise à prévenir les problèmes d’affichage.

Overrides: bazaar/woocommerce/content-product.php version 3.0.0 est obsolète. La version du noyau est 3.6.0
bazaar/woocommerce/global/quantity-input.php version 3.3.0 est obsolète. La version du noyau est 3.6.0
bazaar/woocommerce/product-searchform.php

Outdated Templates: ❌
					
					
						Apprenez comment mettre à jour

### Action Scheduler ###

Complete: 0
Oldest: –
Newest: –

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by peterfabian** [comment]
Thanks, have you tried the troubleshooting tips linked from the wiki?

**Comment by thibal2525** [comment]
I updadte woocommerce database in Status > Scheduled Actions. And it's work fine now. Thanks for your help!
