### ISSUE TITLE
Tax Rounding Issue on items

### ISSUE THREAD

**Issue by mrdigitalau** [woocommerce/woocommerce#23827]
**Describe the bug**
- I created a video here explaining the issue http://somup.com/cqhueOnE1w
- TAX STANDARD RATES 10% - GST Australia
- Prices are entered in INCLUSIVE of tax
- Prices displayed in shop are INCLUDE tax
- Prices displayed at cart and checkout INCLUDE tax
- Rounding is done at a SUBTOTAL level

Scenario One
If I add a product ($5) with a quantity of 2, the tax calculated is correct, $0.91.

Scenario Two
If I add two different products, both $5 each, the tax calculated is $0.90.

Both carts are total $10, but scenario 1 shows $0.91 and scenario 2 shows $0.90.

*Expected behavior*
Seeing that both products have the same total why would they be different taxes?

**Isolating the problem (mark completed items with an [x]):**
- Deactivated all plugins except WooCommerce and issue remains.
- Caching is not switched on

Any assistance would be much appreciated!

Cheers

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): http://staging.mylollies.com.au
Site address (URL): http://staging.mylollies.com.au
WC Version: 3.6.4
Log Directory Writable: ✔
WP Version: 5.2.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.0.33 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 12 MB
PHP Time Limit: 300
PHP Max Input Vars: 2500
cURL Version: 7.64.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.7.26
Max Upload Size: 12 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 310.48MB
Database Data Size: 160.43MB
Database Index Size: 150.05MB
wp_woocommerce_sessions: Data: 0.09MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_order_items: Data: 6.52MB + Index: 2.52MB
wp_woocommerce_order_itemmeta: Data: 43.58MB + Index: 39.14MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.48MB + Index: 0.64MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 7.52MB + Index: 9.09MB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB
wp_gf_form: Data: 0.02MB + Index: 0.00MB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_litespeed_img_optm: Data: 0.00MB + Index: 0.00MB
wp_litespeed_optimizer: Data: 0.14MB + Index: 0.02MB
wp_options: Data: 6.36MB + Index: 0.25MB
wp_postmeta: Data: 54.59MB + Index: 49.17MB
wp_posts: Data: 6.52MB + Index: 3.92MB
wp_termmeta: Data: 0.09MB + Index: 0.09MB
wp_terms: Data: 0.06MB + Index: 0.03MB
wp_term_relationships: Data: 0.36MB + Index: 0.20MB
wp_term_taxonomy: Data: 0.08MB + Index: 0.06MB
wp_usermeta: Data: 26.56MB + Index: 35.09MB
wp_users: Data: 2.52MB + Index: 4.55MB
wp_wcpdf_invoice_number: Data: 0.00MB + Index: 0.00MB
wp_wc_cvo_cache: Data: 0.02MB + Index: 0.00MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB
wp_wc_order_rules: Data: 0.00MB + Index: 0.00MB
wp_wc_order_rules_conditions: Data: 0.00MB + Index: 0.00MB
wp_wc_product_meta_lookup: Data: 0.16MB + Index: 0.33MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB
wp_wpfront_ure_options: Data: 0.02MB + Index: 0.00MB
wp_wps_hit: Data: 0.00MB + Index: 0.01MB
wp_wps_index: Data: 2.60MB + Index: 4.14MB
wp_wps_key: Data: 0.09MB + Index: 0.14MB
wp_wps_object_type: Data: 0.00MB + Index: 0.01MB
wp_wps_query: Data: 0.00MB + Index: 0.00MB
wp_wps_uri: Data: 0.01MB + Index: 0.01MB
wp_wps_user_agent: Data: 0.00MB + Index: 0.00MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

acf-field: 36
acf-field-group: 4
attachment: 572
customize_changeset: 3
nav_menu_item: 94
page: 32
product: 593
product_variation: 984
revision: 219
scheduled-action: 13
shop_coupon: 4
shop_order: 17373

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (34) ###

Gravity Forms: by rocketgenius – 2.4.8.14
ACF QuickEdit Fields: by Jörn Lund – 2.4.17
Advanced Custom Fields PRO: by Elliot Condon – 5.8.0
Classic Editor: by WordPress Contributors – 1.5
Force Regenerate Thumbnails: by Pedro Elsner – 2.0.6
Gravity Forms Zero Spam: by GoWP – 1.0.3
Kadence WooCommerce Email Designer: by Kadence Themes – 1.2.0
WooCommerce Onsale Page: by wpgenie – 1.0.10
Woocommerce Account Payment Gateway: by SkyVerge – 1.0.2 – Not tested with the active version of WooCommerce
User Role Editor Pro: by Vladimir Garagulia – 4.49.1
WooCommerce Extended Coupon Features FREE: by Soft79 – 3.1.0
WooCommerce Bulk Stock Management: by WooCommerce – 2.2.16
WooCommerce Cart Add-Ons: by WooCommerce – 1.5.20
WooCommerce Catalog Visibility Options: by Lucas Stark – 3.2.4
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.18
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.2.4 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Pro: by SkyVerge – 1.7.1
WooCommerce MailChimp Integration: by WooCommerce – 1.0.4 – Not tested with the active version of WooCommerce
Advanced Order Export For WooCommerce (Pro): by AlgolPlus – 2.1.1 – Not tested with the active version of WooCommerce
WooCommerce Order Rules & Filters: by Actuality Extensions – 1.5.3 – Not tested with the active version of WooCommerce
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.2.12
WooCommerce Product Enquiry Form: by WooCommerce – 1.2.8
WooCommerce Google Product Feed: by Ademti Software Ltd. – 7.8.6
WooCommerce Product Search: by itthinx – 2.13.1
WooCommerce Role Based Methods: by WPBackOffice – 2.4.0 – Not tested with the active version of WooCommerce
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.13.1
WooCommerce Shipment Tracking: by WooCommerce – 1.6.14
WooCommerce Australia Post Shipping: by WooCommerce – 2.4.11
WooCommerce Smart Coupons: by StoreApps – 4.0.3 – Not tested with the active version of WooCommerce
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.15
WooCommerce: by Automattic – 3.6.4
Yoast SEO: by Team Yoast – 11.2.1 – Not tested with the active version of WooCommerce
Yoast SEO: WooCommerce: by Team Yoast – 10.0 – Not tested with the active version of WooCommerce
YITH WooCommerce Ajax Search Premium: by YITH – 1.6.7

### Inactive Plugins (1) ###

WooCommerce PDF Invoices, Packing Slips, Delivery Notes & Shipping Labels: by WebToffee – 3.6.6 – Not tested with the active version of WooCommerce

### Must Use Plugins (1) ###

Custom Setup Functions: by Mr Digital –

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Mr Digital
Version: – 0 is available
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: mylollies/woocommerce/archive-product.php
mylollies/woocommerce/checkout/form-checkout.php
mylollies/woocommerce/content-product.php
mylollies/woocommerce/global/quantity-input.php
mylollies/woocommerce/loop/loop-end.php
mylollies/woocommerce/loop/loop-start.php
mylollies/woocommerce/myaccount/dashboard.php
mylollies/woocommerce/myaccount/downloads.php
mylollies/woocommerce/myaccount/form-add-payment-method.php
mylollies/woocommerce/myaccount/form-edit-account.php
mylollies/woocommerce/myaccount/form-edit-address.php
mylollies/woocommerce/myaccount/form-login.php
mylollies/woocommerce/myaccount/form-lost-password.php
mylollies/woocommerce/myaccount/form-reset-password.php
mylollies/woocommerce/myaccount/lost-password-confirmation.php
mylollies/woocommerce/myaccount/my-account.php
mylollies/woocommerce/myaccount/my-address.php
mylollies/woocommerce/myaccount/my-downloads.php
mylollies/woocommerce/myaccount/my-orders.php
mylollies/woocommerce/myaccount/navigation.php
mylollies/woocommerce/myaccount/orders.php
mylollies/woocommerce/myaccount/payment-methods.php
mylollies/woocommerce/myaccount/view-order.php
mylollies/woocommerce/order/order-details-customer.php
mylollies/woocommerce/single-product/add-to-cart/simple.php
mylollies/woocommerce/single-product/add-to-cart/variable.php
mylollies/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
mylollies/woocommerce/single-product.php

### WooCommerce Google Product Feed fields ###

Availability: Defaults to "in stock".
Brand: 
Manufacturer Part Number (MPN): 
Product Type: 
Google Product Category: 
Size system: 

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send item_group_id: No

### Braintree (Credit Card) ###

Environment: Sandbox
Tokenization Enabled: 
Debug Mode: Off

### Braintree (PayPal) ###

Environment: Sandbox
Tokenization Enabled: –
Debug Mode: Off

### Action Scheduler ###

Complete: 13
Oldest: 2019-05-10 14:56:03 +1000
Newest: 2019-05-27 14:56:59 +1000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by paulshultz** [comment]
Can confirm this..

If you look at https://imgur.com/a/pfY6xCe this shows 5 products all at $1,395 each, then each product discounted to $399 using the Dynamic Pricing addon.
The total is $1,995.00 including $181.35 tax which is incorrect

If you look at https://imgur.com/a/SYzyURT this shows 5 products all at $1,395 each, then the cart total is discounted to $1995 using the Dynamic Pricing addon.
The total also is $1,995.00 including $181.35 tax which is incorrect

If you look at https://imgur.com/a/OLXBuX5 it shows 5 products fixed at $399 each
The total is $1,995.00 including $181.36 tax which is correct

This can be verified via tax calculator at https://www.moneysmart.gov.au/tools-and-resources/calculators-and-apps/gst-calculator

**Comment by vedanshujain** [comment]
Possibly #24024, if accepted, will fix this as well, because of late rounding of taxes.

**Comment by vedanshujain** [comment]
This should be fixed in latest beta which was released today.
