### ISSUE TITLE
Parent product changes to out of stock if one or more variations is out of stock

### ISSUE THREAD

**Issue by fistukidz** [woocommerce/woocommerce#23821]
**Describe the bug**
Since few weeks. when a variation of a variable product is bought and then set to stock 0 for that variation. it will also set the parent product to out of stock. 

the correct product was bought in the past where it did not create this error
https://www.fistukidz.com/wp-content/uploads/2019/05/woocommerce-error.png

if i will set a stock to the variable which was bought, then the parent will be IN STOCK. 

i have woocommerce version 3.6.3

**Comment by kloon** [comment]
Would you mind sharing how you have the product inventory set up? I tried to replicate this now on a variable product but I was unable to replicate with the same results?

On the main product do you have stock management enabled there? From what you are saying you are managing stock on a variation level and that is how I also tested it.

Main product does not manage stock
![](https://cld.wthms.co/llTnbH+)

Each variation has manage stock checked and stock values
![](https://cld.wthms.co/6rdx2L+)
![](https://cld.wthms.co/3AnLxM+)

After purchasing the 1 item left in stock on the XL variation in my test the stock adjusted to 0, but the product stayed in stock on the main product page, just that option is out of stock
![](https://cld.wthms.co/Bmg2by+)
![](https://cld.wthms.co/vDTkdG+)
![](https://cld.wthms.co/Vka18B+)

If you manage stock on a variable product level and not the parent then you should not have the option enabled to manage stock on the parent product. It may be that you are mixing the two options and one of the variations not managing stock on a variation level actually went out of stock causing the whole product to be in stock.

I will gladly reopen the issue if you can provide step by step instructions to replicate this with example of how you have the product set up as well as all the variations.

**Comment by fistukidz** [comment]
Hi. 
thank you for the reply. 
i manege stock on variation level, all variation are enabled. 
in order to reproduce the error i just need to change one variation stock to 0. 

however, when i change the product to 'simple product' in inventory its default to out of stock. 
so if i change the product to simple product and change the inventory to in stock, then i save it. 
then i change again to variable product, and i create all variables set prices, manage stock at variable level, and set all stocks to 1. But just one variable set to 0 (so basically to try to reproduce the error) then the parent product is showing correctly in stock. 

i cant understand why. i will be happy to give access to my shop so a programmer could check it.

**Comment by fistukidz** [comment]
Hi. 
so i got a reply which sold the issue. 
[https://wordpress.org/support/topic/woocommerce-variable-product-show-as-out-of-stock/#post-11572186](url)

thanks any way.
