### ISSUE TITLE
Tax not displayed anywhere

### ISSUE THREAD

**Issue by madmath03** [woocommerce/woocommerce#23823]
**Describe the bug**
Even though the Tax have been properly setup and applied to products (compared with another WC site with same settings and working properly), the tax do not show up on any step of the order.

**To Reproduce**
Hard to say how to reproduce since 2 different sites with same settings and version have a different behavior... here is a little summary of our configuration : 
* We are using products variation and each variation uses the parent product tax class
* Each product is using the Standard Tax class 8.5%
* Prices are entered with all taxes included
* Taxes should be displayed in the total of the order

**Screenshots**

![image](https://user-images.githubusercontent.com/6967675/58381757-61ef5000-7fc1-11e9-94b8-5f2242fb9fae.png)

**Expected behavior**
Taxes should be displayed in cart details.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/): **confirmed with Twenty Seventeen and Storefront**
- [ ] I can reproduce this bug consistently using the steps above: **Cannot reproduce it on another instance with same settings / versions :confused:**

**WordPress Environment**
<details>
```
### WordPress Environment ###

WordPress address (URL): https://www.s2senergie.com
Site address (URL): https://www.s2senergie.com
WC Version: 3.6.3
Log Directory Writable: ✔
WP Version: 5.2.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.25 (Debian)
PHP Version: 7.2.18
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.15-MariaDB-1:10.3.15+maria~bionic
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.3
WC Database Prefix: bmc_
MaxMind GeoIP Database: ✔
Taille totale de la base de données: 3.94MB
Taille de la base de données: 2.73MB
Taille de l’index: 1.21MB
bmc_woocommerce_sessions: Données : 0.02MB + Index: 0.02MB
bmc_woocommerce_api_keys: Données : 0.02MB + Index: 0.03MB
bmc_woocommerce_attribute_taxonomies: Données : 0.02MB + Index: 0.02MB
bmc_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index: 0.06MB
bmc_woocommerce_order_items: Données : 0.02MB + Index: 0.02MB
bmc_woocommerce_order_itemmeta: Données : 0.02MB + Index: 0.03MB
bmc_woocommerce_tax_rates: Données : 0.02MB + Index: 0.06MB
bmc_woocommerce_tax_rate_locations: Données : 0.02MB + Index: 0.03MB
bmc_woocommerce_shipping_zones: Données : 0.02MB + Index: 0.00MB
bmc_woocommerce_shipping_zone_locations: Données : 0.02MB + Index: 0.03MB
bmc_woocommerce_shipping_zone_methods: Données : 0.02MB + Index: 0.00MB
bmc_woocommerce_payment_tokens: Données : 0.02MB + Index: 0.02MB
bmc_woocommerce_payment_tokenmeta: Données : 0.02MB + Index: 0.03MB
bmc_woocommerce_log: Données : 0.02MB + Index: 0.02MB
bmc_aiowps_events: Données : 0.02MB + Index: 0.00MB
bmc_aiowps_failed_logins: Données : 0.05MB + Index: 0.00MB
bmc_aiowps_global_meta: Données : 0.02MB + Index: 0.00MB
bmc_aiowps_login_activity: Données : 0.02MB + Index: 0.00MB
bmc_aiowps_login_lockdown: Données : 0.02MB + Index: 0.00MB
bmc_aiowps_permanent_block: Données : 0.02MB + Index: 0.00MB
bmc_commentmeta: Données : 0.02MB + Index: 0.03MB
bmc_comments: Données : 0.02MB + Index: 0.09MB
bmc_links: Données : 0.02MB + Index: 0.02MB
bmc_oauth_access_tokens: Données : 0.02MB + Index: 0.02MB
bmc_oauth_authorization_codes: Données : 0.02MB + Index: 0.02MB
bmc_oauth_jwt: Données : 0.02MB + Index: 0.02MB
bmc_oauth_public_keys: Données : 0.02MB + Index: 0.02MB
bmc_oauth_refresh_tokens: Données : 0.02MB + Index: 0.02MB
bmc_oauth_scopes: Données : 0.02MB + Index: 0.00MB
bmc_options: Données : 1.44MB + Index: 0.05MB
bmc_postmeta: Données : 0.33MB + Index: 0.11MB
bmc_posts: Données : 0.13MB + Index: 0.06MB
bmc_termmeta: Données : 0.02MB + Index: 0.03MB
bmc_terms: Données : 0.02MB + Index: 0.03MB
bmc_term_relationships: Données : 0.02MB + Index: 0.02MB
bmc_term_taxonomy: Données : 0.02MB + Index: 0.03MB
bmc_tm_taskmeta: Données : 0.02MB + Index: 0.03MB
bmc_tm_tasks: Données : 0.02MB + Index: 0.02MB
bmc_usermeta: Données : 0.02MB + Index: 0.03MB
bmc_users: Données : 0.02MB + Index: 0.05MB
bmc_wc_download_log: Données : 0.02MB + Index: 0.03MB
bmc_wc_product_meta_lookup: Données : 0.02MB + Index: 0.09MB
bmc_wc_webhooks: Données : 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 94
custom_css: 2
customize_changeset: 1
elementor-hf: 1
nav_menu_item: 6
page: 10
post: 1
product: 5
product_variation: 20
scheduled-action: 30
wpcf7_contact_form: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

All In One WP Security: par Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.3.9.4

Astra Starter Sites: par Brainstorm Force – 1.3.12
Elementor: par Elementor.com – 2.5.15
Essential Addons for Elementor: par WPDeveloper – 3.0.0
Header, Footer & Blocks for Elementor: par Brainstorm Force
Nikhil Chavan – 1.1.2

WP OAuth Server: par WP OAuth Server – 3.7.6
Simple LDAP Login: par Clif Griffin Development Inc. – 1.6.0
Two Factor Authentication: par David Nutbourne + David Anderson
extension originale de Oskar Hane – 1.5.1 – Non testé avec la version active de WooCommerce

WooCommerce: par Automattic – 3.6.3
WP-FFPC: par Peter Molnar  – 1.11.2
WP Mail SMTP: par WPForms – 1.4.2
WP-Optimize: par David Anderson
Ruhani Rabin
équipe Updraft – 2.3.3

WPForms Lite: par WPForms – 1.5.2.3

### Inactive Plugins (5) ###

Akismet Anti-Spam: par Automattic – 4.1.2
Contact Form 7: par Takayuki Miyoshi – 5.1.3
Really Simple CAPTCHA: par Takayuki Miyoshi – 2.0.1
Super Progressive Web Apps: par SuperPWA – 2.0.2
WP-Discourse: par Discourse – 1.9.0

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la boutique: #983 - /boutique/
Panier: #978 - /cart/
Validation de la commande: #979 - /checkout/
Mon compte: #980 - /my-account/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Astra
Version: 1.8.4
Author URL: https://wpastra.com/about/
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 30
Oldest: 2019-05-26 07:26:20 -0400
Newest: 2019-05-26 07:29:01 -0400

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

```
</details>

**Comment by kloon** [comment]
It is not always possible to display taxes in the cart page because taxes are based on location and for new shoppers there are no address details specified on the cart page, the first time location is specified is on the checkout page so then it allows for showing the taxes. After the first purchase, their location will be stored and used by default while browsing your store.

To overcome this you can specify a default location for first-time visitors under WooCommerce -> Settings -> General. You have the option to use your own store address as the default or enable geolocation which will use an API to figure out the customer location based on their IP.

**Comment by madmath03** [comment]
@kloon I get your point and I agree with what you said, **but** geolocation is activated and yet the taxes are not displayed.
Plus, the taxes do not appear at the checkout phase either even after entering the address...

I think you've been a little hasty in closing this 😅

**Comment by kloon** [comment]
Sorry, only closing as this is not a bug and I cannot confirm it with the steps provided.

Perhaps provide some screenshots on how your taxes are set up? Would help a lot if I can get a sense of how your tax rates are set up.

Perhaps add a general tax rule that covers all locations as a fallback if you do not have one already?

Also, I am noticing you have caching enabled on your site. I assume your geolocation is selected with the option to support caching?

**Comment by madmath03** [comment]
Well, geolocation was activated but without handling the cache. Thanks for pointing that out.
Unfortunately, no changes in the behavior observed here.

Here are a few screenshots of how taxes are setup:
![image](https://user-images.githubusercontent.com/6967675/58408410-075ffd80-806e-11e9-9005-335d69e79132.png)
![image](https://user-images.githubusercontent.com/6967675/58408426-10e96580-806e-11e9-9723-9b4f1028c745.png)

As you can see, we do not have a fallback tax rule. Going to try this and let you know results.

**Comment by madmath03** [comment]
Well, that's kind of odd : setting the fallback tax rule did trigger the display of the tax, but for the sake of the test I used a different rate. The shipping address is ignored as I see the fallback rate (20%) being applied even though the shipping address is valid and should trigger the regular rate (8.5%).

![image](https://user-images.githubusercontent.com/6967675/58409016-7427c780-806f-11e9-9ffc-fe44301666e8.png)
![image](https://user-images.githubusercontent.com/6967675/58409073-915c9600-806f-11e9-8c0e-16def98e2610.png)

**Comment by kloon** [comment]
I think your issue is you gave GP set as the state code in your tax rule. As far as I can see there is no states for Guadeloupe. That is why it displays the fallback rate, since the country matches but on the state it cannot match and thus it goes to the next rule in your tax table which is a fallback rule that matches on any country or state.

Try removing GP from the state field in your tax table and only keep it in the country code part.

**Comment by madmath03** [comment]
That's it! Removing the state fixed the issue.

So it really was a configuration issue. My bad.
Thanks a lot 😃

**Comment by kloon** [comment]
No problem, glad I could help.
