### ISSUE TITLE
Post status filter in product search method

### ISSUE THREAD

**Issue by bitadvisor** [woocommerce/woocommerce#23829]
**Is your feature request related to a problem? Please describe.**
Currently `WC_Product_Data_Store_CPT::search_products` retrieves either published products or products with any status - it does not allow more granular status control.

**Describe the solution you'd like**
The aforementioned method should allow adding more statuses to the list when $all_statuses is set to false, like this:

    $post_statuses = current_user_can( 'edit_private_products' ) ? array( 'private', 'publish' ) : array( 'publish' );
    $post_statuses = apply_filters( 'woocommerce_search_products_post_statuses', $post_statuses );

It's not perfect (requires callback hooking/unhooking each time) but way more efficient than having to get status of each of the returned products in order to filter out the ones that are of no interest in a given situation (e.g. trashed products).

**Comment by claudiosanches** [comment]
Thank you for suggesting this feature!

I'm closing the issue as it already has a PR, please continue the discussion over at #23838.
