### ISSUE TITLE
wrong total price OR wrong tax calculation

### ISSUE THREAD

**Issue by heyimjones** [woocommerce/woocommerce#23831]
**Describe the bug**
Hey,
when adding several products to my woocommerce cart I either have a wrong total amount OR the wrong tax amount.

**I tried this:**
I checked "round the taxes at subtotal level". 
e.g. 3 different products a 40€ should be 120€ in total but it gives me a total of 119,99€. (but shows the right tax amount of 120€) 
Same is happening with 2 Items: 79,99€ instead of 80,00€. again the right tax amount (of 80€) 12,77€. 
<img width="772" alt="Bildschirmfoto 2019-05-28 um 13 57 41" src="https://user-images.githubusercontent.com/51117777/58473190-46fb1800-8148-11e9-9bbf-29548218a25b.png">

With only one Item in the cart, the calculation is done right. eg. 40€; 6,39€ Taxes - 80€; 12,77€ Taxes - etc. all okay!
<img width="880" alt="Bildschirmfoto 2019-05-28 um 13 59 55" src="https://user-images.githubusercontent.com/51117777/58473319-95a8b200-8148-11e9-9753-5e1278dd4907.png">

Strangely the issue also doesn’t occur when I have one item once and another item two times in the cart. 
total: 120€ + Tax 19,16€ - everything right. 
<img width="771" alt="Bildschirmfoto 2019-05-28 um 14 02 05" src="https://user-images.githubusercontent.com/51117777/58473419-d4d70300-8148-11e9-86a3-8bbfeefe3548.png">

**round per line - not in subtotal**
When I round them per line I got the right amount in total but the wrong amount in taxes! e.g. 120€ in total should have 19,16€ tax, but it shows 19,17€.

I tried this by entering prices inclusive of tax AND exclusive of tax . Always the same issue. 
It's either showing me the wrong total amount or the wrong calculated taxes.

All I want is that the total price to be calculated by adding all item prices with the taxes (40+40+40 = 120) and the taxes to be showed correctly (for 120€: 19,16 and not 19,17)

PS. I just tried to update woocommerce, but the issue still occurs.

I would be so grateful for your help.

Best regards

**Comment by heyimjones** [comment]
**SOLVED:**
**tax settings:**
checked "enter prices exclusive of tax"
checked "round tax at subtotal level, instead of rounding per line"

added this two filters to my function file

`add_filter( 'raw_woocommerce_price', function ( $price ) {
	$decimals = round( $price - floor( $price ), 2 );
	return ( $decimals == 0.01 || $decimals == 0.99 ) ? round( $price ) : $price;
} );`

`add_filter( 'woocommerce_calculated_total', 'custom_calculated_total' );
function custom_calculated_total( $total ) {
  $total = round( $total, 1 );
  return $total;
}`

this combined with setting 33,6134 € as the price (4 decimals) will show you the right taxes.
Why 33,6134€? 
I want a final price of 40€, taxes 19%
40 / 1,19 = 33,6134 without tax
**(I suppose) this will only work for products with prices X.00**

------------------------------------------------

If this doesn't help, you can try this:
Set the number of decimals in general settings to 4. 
in tax settings:
check "enter prices exclusive of tax"
check "round tax at subtotal level, instead of rounding per line"
Add this filter in your function file: 

`add_filter('wc_price_args', 'custom_decimals_price_args', 10, 1);
function custom_decimals_price_args($args) {
    $args['decimals'] = 2;
    return $args;
}`
set price like this: 33,6134 € (4 decimals)

Hope this will help someone.

**Comment by vedanshujain** [comment]
Closing this issue because of related improvement in #24024 . Also it looks like you have resolved the issue for yourself :) .
