### ISSUE TITLE
Even when loading rest_api_includes() manually, a notice is thrown

### ISSUE THREAD

**Issue by unfulvio** [woocommerce/woocommerce#23839]
#### PR in #23840 

Since v3.6.0 the `wc_rest_` handler classes are not always loaded and they are made available only at `rest_api_init`. If a plugin attempts to access to these classes too early (for example, at `before_woocommerce_init`) a [notice is thrown here](https://github.com/woothemes/woocommerce/blob/3ff2c2f0534df3f5c4f45843ed430da6303a5a08/includes/class-wc-autoloader.php#L95), and the classes are manually included to avoid PHP fatal errors.

However, the notice also recommends to load the rest API classes manually with `WC()->api->rest_api_includes()`. Despite this, even if you do so, this error will still persist, because the condition above does not check if `class_exist()` (has been loaded manually)

**To Reproduce**

Initialize rest handlers early, but also do `WC()->api->rest_api_includes();` as recommended by the notice: an error is still shown.

Compare with adding a `! class_exist( $class )` among the conditions where the 
conditions to produce this notice are determined: the error will be gone (unless you do not manually include the classes).

**Expected behavior**

If I include manually the WC rest API handlers, I should not see this notice which otherwise contradicts its own recommendation.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #23840.
