### ISSUE TITLE
Exporting products missing meta data fields

### ISSUE THREAD

**Issue by drosendo** [woocommerce/woocommerce#23844]
**Describe the bug**
Running the export of the products .csv meta data that is stored as array (serialized in the DB), doesn't get exported in the .csv only if it's string. Im guessing you are excluding it.

**To Reproduce**
1. Go to 'Products
2. turn on export custom meta
3. Click on Export

**Expected behavior**
Expect to have the data present serialized like the WordPress export

Another question: The images present on the export do not retain their ID on import, this may cause loss of information due to ID mismatch if there exist any relations?

Cheers,
David

**Comment by drosendo** [comment]
Hi,

Found solution, thanks:

`
 add_filter('woocommerce_product_export_meta_value',  'woo_handle_export', 10, 4); 
    public function woo_handle_export($value, $meta, $product, $row)
    {
        if ($meta->key == 'XPTO') {
            return json_encode($value);
        }
    }
`

**Comment by drosendo** [comment]
Still need help with:
Another question: The images present on the export do not retain their ID on import, this may cause loss of information due to ID mismatch if there exist any relations?

**Comment by claudiosanches** [comment]
> The images present on the export do not retain their ID on import, this may cause loss of information due to ID mismatch if there exist any relations?

No, since will search for the image and save an ID to relate it later in future imports as well.

**Comment by Tahoooe** [comment]
@drosendo Hi! I'm having a similar problem with the WooCommerce exporter not wanting to export a serialised field called `_role_based_price` in the database. I'm just starting with PHP, I tried to put your code in a few places (functions.php and wc-product-exporter.php, while replacing `XPTO` with `_role_based_price`), but it doesn't seem to do anything. Could you tell me what am I doing wrong? Thanks a lot :)

**Comment by drosendo** [comment]
> @drosendo Hi! I'm having a similar problem with the WooCommerce exporter not wanting to export a serialised field called `_role_based_price` in the database. I'm just starting with PHP, I tried to put your code in a few places (functions.php and wc-product-exporter.php, while replacing `XPTO` with `_role_based_price`), but it doesn't seem to do anything. Could you tell me what am I doing wrong? Thanks a lot :)

You are probably calling the filter too soon and WooCommerce may not yet be loaded, try something like:

`
add_action( 'plugins_loaded', 'my_plugin_override',20); //20 just to run later
 
function my_plugin_override() {
     add_filter('woocommerce_product_export_meta_value',  'woo_handle_export', 10, 4); 
}

function woo_handle_export($value, $meta, $product, $row)
    {
        if ($meta->key == 'XPTO') {
            return serialize($value);
        }
    }
`

Cheers,
David
