### ISSUE TITLE
Variations infinite loading

### ISSUE THREAD

**Issue by tripatwhat** [woocommerce/woocommerce#23842]
Hello,

i have an issue with variations infinite loading in every product. The error i see in console is: TypeError: a(…).selectWoo is not a function. Here are the things i tried, in order to solve this:

    moving website to different server
    disabling all plugins besides Woocommerce
    switching to storefront
    increasing memory limit to 512 mb
    solution from this link: https://wordpress.org/support/topic/endless-spinning-wheel-2/
    installing classic editor plugin to disable Gutenberg

Can somebody help me out with this? I've lost quite a bit of time solving this, it's quite annoying.

Thanks

**Comment by rodrigoprimo** [comment]
Hi there!

GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/

**Comment by tripatwhat** [comment]
Hello @rodrigoprimo ,

variations inside WooCommerce product are not working. This is the issue inside WooCommerce plugin, isn't it?

I didn't see any problem for your colleagues to reply to the same problem here:
https://github.com/woocommerce/woocommerce/issues/14972#issuecomment-300402820
https://github.com/woocommerce/woocommerce/issues/14512

It seems that you have a selective way of applying this rule of yours. Besides that, i was writing here because you need forever to reply on support forums. Seems like other people had the same problem, otherwise they wouldn't write here, wouldn't they?

Anyway, i solved the problem myself, but it's not cool to write me this, when at the same time your colleagues helped other people with exactly the same issue.


Best regards

**Comment by claudiosanches** [comment]
> variations inside WooCommerce product are not working. This is the issue inside WooCommerce plugin, isn't it?

Not able to reproduce this issue.

> I didn't see any problem for your colleagues to reply to the same problem here:

No reason to be rude, you'll not win anything with it... We are all here to help everyone!

> i have an issue with variations infinite loading in every product. The error i see in console is: TypeError: a(…).selectWoo is not a function. Here are the things i tried, in order to solve this:

For what you are reporting, seems like or there's no more `SelectWoo.min.js` or any other SelectWoo files after you moved from server, or even a plugin a 3rd party plugin is trying to use this library without calling it properly.

**Comment by tripatwhat** [comment]
Hello @claudiosanches,

i don't see my reply as rude, i am just asking why my question is not appropriate, while a lot of other users are asking the same thing and getting replies and help with the same issue. I guess that anybody would feel cut off and wanted to know why.

Regarding the issue, i didn't move the website anywhere. Everything was working properly and all of the sudden about 10 days ago variations started to have infinite loading. But, like i said in my previous reply, i already solved the problem. The issue was with leftovers of some old caching plugin. This plugin did not delete all cache files and folders it created. For some reason this wasn't a problem before, but now these files were causing WC to go into infinite loading of variations. After i removed all those files and folders everything worked again properly.

**Comment by claudiosanches** [comment]
@tripatwhat please fill a bug report if you think that this is a bug on WooCommerce: https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=
