### ISSUE TITLE
download-links that after user purchase add to product file, does not show in user profile

### ISSUE THREAD

**Issue by omidhajivali** [woocommerce/woocommerce#23841]
I use latest woocommerce  version 3.6.4 and have a problem with variation product that variations are downloadable,
I update a product and add some new files-download to product but new files does not show in user profile Although user Has bought this product but before update it

```
$downloads=WC()->customer->get_downloadable_products();
var_dump($downloads);
```
I used this code to check all files that user Allowed to download and I realized files that add in next updates do not allowed for user

Is there a way to manually access all files, or is there an option to show all product-download-files for users who bought this product?

**Comment by kloon** [comment]
@omidhajivali as [per the documentation](https://docs.woocommerce.com/document/digital-downloadable-product-handling/#section-10) adding new download links to a product will not update the existing orders, existing orders are only updated when you change the file paths or names of an existing file on a download.

If you want to regenerate download permissions for past orders you can use the plugin linked to in the documentation.
