### ISSUE TITLE
Coupon usage limit has been reached

### ISSUE THREAD

**Issue by Wayne-Ehr-Surprenant** [woocommerce/woocommerce#23843]
Same issue as mentionned here #23836   , but I have more information about this.

In fact, the bug is happening only when trying to apply a coupon to orders assigned to guest user.

I've tried the same coupon with the same order but this time with an existing user as the customer and the coupon applied just fine. 

& Sorry for creating a new issue, I have no idea how to re-open the previous issue.

**Comment by saltsurfsea** [comment]
I have the same problem, I just created a new issue #23846. Hope it can get resolved.

**Comment by claudiosanches** [comment]
Please do not duplicate issues, as I said, we could just open again.
Closing as duplicated of #23836
