### ISSUE TITLE
Imprecise "cost" stored in woocommerce_order_itemmeta table

### ISSUE THREAD

**Issue by andrew-dixon** [woocommerce/woocommerce#23854]
**Describe the bug**
The "cost" value stored in the woocommerce_order_itemmeta table for a product is always rounded to 2 decimal places, which then, in some cases, causes the total cost of the order to change when you "update" the order, e.g. move it from "pending" to "processing". 

For example, we have our shipping set to a cost of £4.125 + VAT, and at the UK rate of 20% this makes a total shipping cost of £4.95. However, in the woocommerce_order_itemmeta table, the cost of the shipping gets stored as £4.13, which plus 20% VAT is £4.96. When we initially view the order, it appears correctly, however, as soon as we "update" the order, it recalculates everything and increases the total order cost by 1p and then the order doesn't match the received payment, etc...

**To Reproduce**
1. Add a taxable shipping cost of £4.125 and a TAX rate of 20%
2. Order an item.
3. Go to the database and look in the woocommerce_order_itemmeta table and find the shipping item and see the "cost" key has a value of 4.13 instead of 4.125.
4. Go to the WP Admin and look at the order and see that it all adds up.
5. Change the status of the order and click update and notice that the VAT for the shipping and total price of the order increases by 1p, however, sometimes you need to click the "recalculate" button to get it to occur and sometimes it does the recalculation automatically, not really sure why that is.

**Expected behavior**
For it to store the "cost" value in the DB as the cost the item is set to.

**WordPress Environment**
<details>
### WordPress Environment ###

WordPress address (URL): http://localhost:8080
Site address (URL): http://localhost:8080
WC Version: 3.6.4
Log Directory Writable: ✔
WP Version: 5.2.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.25 (Debian)
PHP Version: 7.3.5
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.6.43
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.4
WC Database Prefix: tw_
MaxMind GeoIP Database: ❌ The MaxMind GeoIP Database does not exist - Geolocation will not function. You can download and install it manually from https://dev.maxmind.com/geoip/geoip2/geolite2/ to the path: . Scroll down to "Downloads" and download the "MaxMind DB binary
gzipped" file next to "GeoLite2 Country". Please remember to uncompress GeoLite2-Country_xxxxxxxx.tar.gz and upload the GeoLite2-Country.mmdb file only.

Total Database Size: 3.03MB
Database Data Size: 2.08MB
Database Index Size: 0.95MB
tw_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
tw_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
tw_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
tw_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
tw_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
tw_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
tw_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
tw_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
tw_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
tw_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
tw_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
tw_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
tw_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
tw_woocommerce_log: Data: 0.02MB + Index: 0.02MB
tw_commentmeta: Data: 0.02MB + Index: 0.03MB
tw_comments: Data: 0.02MB + Index: 0.09MB
tw_links: Data: 0.02MB + Index: 0.02MB
tw_options: Data: 1.52MB + Index: 0.02MB
tw_postmeta: Data: 0.02MB + Index: 0.03MB
tw_posts: Data: 0.02MB + Index: 0.06MB
tw_termmeta: Data: 0.02MB + Index: 0.03MB
tw_terms: Data: 0.02MB + Index: 0.03MB
tw_term_relationships: Data: 0.02MB + Index: 0.02MB
tw_term_taxonomy: Data: 0.02MB + Index: 0.03MB
tw_usermeta: Data: 0.02MB + Index: 0.03MB
tw_users: Data: 0.02MB + Index: 0.05MB
tw_wc_download_log: Data: 0.02MB + Index: 0.03MB
tw_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
tw_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 1
page: 6
post: 2
product: 2
scheduled-action: 1
shop_order: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (5) ###

Jetpack by WordPress.com: by Automattic – 7.3.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.14
WooCommerce Services: by Automattic – 1.20.0
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.28
WooCommerce: by Automattic – 3.6.4

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.2
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /?page_id=6
Basket: #7 - /?page_id=7
Checkout: #8 - /?page_id=8
My account: #9 - /?page_id=9
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 0
Oldest: –
Newest: –

Pending: 1
Oldest: 2019-05-31 16:52:42 +0100
Newest: 2019-05-31 16:52:42 +0100

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –
</details>

**Comment by andrew-dixon** [comment]
@vedanshujain Any chance you can have a look at this or assign it someone who can? Thanks.

**Comment by andrew-dixon** [comment]
@vedanshujain Any thoughts on this issue?

**Comment by vedanshujain** [comment]
Hmm, I spent some time with this, I would say that it actually makes sense in its current form, because when the number of decimals in settings are set to 2, WooCommerce should round all 3 digit decimals to 2 in the source. 

That said, I do not see any harm in not rounding off the shipping cost. Because all the line items are eventually going to be rounded off, either at line item level, or in subtotal, depending upon the setting. So may be we can remove the round off statement in https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-shipping-method.php#L299 unless I am overlooking something.

cc @mikejolley  (I am cc'ing you because you wrote the original code. Sorry for pinging again this week :D )

**Comment by mikejolley** [comment]
@vedanshujain 3dp prices are not supported. From this example, to end up with `4.95` with a tax rate of 20% you're forced to use 3dp but this is problematic. Products get around this by supporting prices defined inclusive of tax, but shipping does not yet support this.

Either shipping would need to support prices incl. tax (I think there is a feature request logged for that somewhere), or user would have to accept that certain prices are not possible and charge a different total after taxes.

**Comment by andrew-dixon** [comment]
@mikejolley @vedanshujain Surely the resolution to this is to store the "correct" price in the woocommerce_order_itemmeta table in the first place. If I replace the stored price in the table with the correct price, e.g. replace 4.13 with 4.125, for an order then that order doesn't have a problem when the price is recalculated. The table supports 3dp already, it is just that it is being rounded before it is inserted that is the issue. As these values are used during a recalculation, really they need to be stored as the same value as the original value, otherwise, you are always going to get calculation errors like this.

Conversely, if you do not want to support 3dp (for whatever reason) then the interface shouldn't allow for the price to be entered with 3dp, but then that doesn't help anyone trying to achieve a particular price point.

**Comment by andrew-dixon** [comment]
@mikejolley @vedanshujain Any further thoughts on this? Thanks.

**Comment by vedanshujain** [comment]
@andrew-dixon from Mike's comment, I can understand why 3dp could be problematic when setting only allows 2dp. In our case, 4.125 will be converted to 4.13 anyway at the time of checkout because 2dp setting will force shipping total to be rounded off.

Further, if we remove rounding from checkout page as well, then this will cause issues when shipping is also taxable, because users will now see an un-rounded total where as they would be expecting a shipping cost rounded off to 2dp. So I don't think we should stop rounding off decimals in the database.

Adding support for shipping costs inclusive of taxes should be a better approach instead. And I guess we should not support 3dp prices for shipping while only having 2dp for everything else. I am closing this issue, but please to add your comment if you think otherwise.

**Comment by andrew-dixon** [comment]
@vedanshujain You cannot calculate from one value and then re-calculate from another, this will always result in a pricing error. You need to store the price that is given and used in the calculation, not the price that is displayed. 

It is perfectly acceptable for the displayed price and the calculation price to be a different number of DP. I was never suggesting the displayed price should be changed, only that the price stored in the `woocommerce_order_itemmeta` table is stored as the same value as the value that is used in the initial calculation. Without doing this, whenever the basket is recalculated, it will always result in this issue.

This issue is not "invalid" as you have tagged it, it is perfectly valid, it is just that the preferred solution needs to be decided upon. 

The options, as far as I see it are:

1. Store the same value in the DB that is used in the initial calculation so that recalculation doesn't result in a different price.
1. Change the shipping costs to only allow up to 2 DP to be entered.
1. Allow shipping prices to be entered inclusive of tax, as you do with products.

In my opinion:

Option 1 would be the simplest to implement and test. The DB already supports more decimal places in the `woocommerce_order_itemmeta` table, so it is just a matter of changing the value passed to the DB to be the none rounded value.

Option 2 would be restrictive and not allow store owners to set the shipping price they would like to, for example, you could never have a shipping price of 4.95 (inc. tax) with a tax rate of 20%, as the value needs to be set to 4.125 to achieve this.

Option 3 would be a much bigger, harder to implement and test change than option 1 and wouldn't really gain you anything over option 1 over than it being slightly easier for store owners to enter their shipping prices.

Can we get someone else on the WooCommerce team to review this please?

**Comment by vedanshujain** [comment]
Right, sorry, I marked the issue as invalid because having shipping inclusive of taxes is already requested in https://github.com/woocommerce/woocommerce/issues/9320, but forgot to link the issue in my previous comment.

Combination of option 2 and option 3 as you suggest is probably what we should consider. cc @woocommerce/proton for second opinion.

**Comment by mklusak** [comment]
I really can't understand how `woocommerce_order_itemmeta` price item can be rounded at all ...  I set number of decimals to zero, yes, but event the question mark hint says it's intended for **displayed prices**. Then I have shipping cost set to 65 CZK (with 21% VAT). After processing order the following prices are saved to `woocommerce_order_itemmeta` table:

total_tax: 11.2812
cost: 54
instance_id: 6
method_id: flat_rate

WC saves 21% VAT as 11.2812, but then it rounds correct "without VAT" 53.72 cost to 54 CZK! And another accounting / invoicing plugin takes this numbers, sums them up, and now I have invoice with incorrect line "Shipping: 65.28 CZK". 

The andrew-dixon latest reply hit the nail on the head. Option number 1 is the only valid solution. No rounding before storing value to database.
