### ISSUE TITLE
WC_Product_Data_Store_CPT::find_matching_product_variation defaults to "Any" variation

### ISSUE THREAD

**Issue by drussell393** [woocommerce/woocommerce#23855]
When using the WC_Product_Data_Store_CPT::find_matching_product_variation() function in a plugin, WooCommerce gives back the "Any" variation depending on order in the WP backend.

So for instance, if you have 2 variations:

**Variation 1**
Size: Any

and

 **Variation 2**  
Size: 15ml

And the order is as follows in the dashboard:

![image](https://user-images.githubusercontent.com/7795204/58741197-986b0780-83d3-11e9-9a41-ad6b8c5ab48c.png)

The function will bring back 25590 (variation 1) even though the array is passed a size of `15ml`, simply because of the order in the backend.

If you move the order down, so "Any Size" is below all of the variations with defined sizes, though, it works as expected and returns 8781 when `15ml` is passed to the function.

This may be expected behavior, but my question would be how it would behave then if you have "Any Size" and then a second variation attribute (we'll call it "Color") that is defined. That may be related to #23042.

**Comment by claudiosanches** [comment]
> This may be expected behavior, but my question would be how it would behave then if you have "Any Size" and then a second variation attribute (we'll call it "Color") that is defined.

In this case should match with all variations at the same time, unless defined another ones.

Closing, since there's a Pull Request to improve this behavior: https://github.com/woocommerce/woocommerce/pull/23067
