### ISSUE TITLE
Pass the request object to the rest_check_permissions filter

### ISSUE THREAD

**Issue by superdav42** [woocommerce/woocommerce#23860]
**Is your feature request related to a problem? Please describe.**
Modifying the permissions of the rest API is difficult

**Describe the solution you'd like**
Changing the permission logic of the WC REST API is difficult with the filter `woocommerce_rest_check_permissions`. The same filter is used in several different object contexts and it can be hard to distinguish between them. It would be helpful if the request object was passed to this filter.

**Describe alternatives you've considered**
Alternatively different filters could be used for each object type but this would need BC code or breaks. 

**Additional context**
This was related to the new REST API added to Bookings. We ended up needing to register and unregister the filter in each endpoint.

**Comment by claudiosanches** [comment]
It's just one filter, but it's easy to distinguish between them.
See the fourth parameter (I have copied all instances of the `woocommerce_rest_check_permissions` filter):

```php
apply_filters( 'woocommerce_rest_check_permissions', $permission, $context, $object_id, $post_type ); // $post_type = 'product', 'shop_order, 'shop_coupon' and so on.
apply_filters( 'woocommerce_rest_check_permissions', $permission, $context, $object_id, 'user' );
apply_filters( 'woocommerce_rest_check_permissions', $permission, $context, $object_id, $taxonomy ); // $taxonomy - 'product_cat, 'product_tag', and more attributes.
apply_filters( 'woocommerce_rest_check_permissions', $permission, $context, 0, $object ); // $object = 'reports', 'settings', 'system_status', 'attributes', 'shipping_methods', 'payment_gateways', and 'webhooks'.
apply_filters( 'woocommerce_rest_check_permissions', $permission, $context, $object_id, 'product_review' );
```

So yes, it's just one, but easy to define what kind of "object" you are dealing of.
