### ISSUE TITLE
Product count and product not in stock not showing

### ISSUE THREAD

**Issue by jbrandek** [woocommerce/woocommerce#23861]
**Describe the bug**
on my site judaicapanama.com i set up to show 20 product per page and hide products that are not in stock. but when i check the categories the product count says taht is showing 1-20 of 275, when its really showing 17 in that page and in that category there is only 172 products in stock, so its counting more products that what there is really there.

**To Reproduce**
1. Go to https://judaicapanama.com/productos/infantiles/
2. Check product count, and compare to what there is really showing 17 in stead of 20
3. Also if you go to page 2 it says 20-40 and its only showing 11 products

**Expected behavior**
to show 20 products per page

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

WordPress environment
--
WordPress address (URL): |   | http://judaicapanama.com
Site address (URL): |   | http://judaicapanama.com
WooCommerce version: |   | 3.6.4
Log directory writable: |   | /home/judaicap/public_html/wp-content/uploads/wc-logs/
WordPress version: |   | 5.2.1
WordPress multisite: |   | –
WordPress memory limit: |   | 384 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | es_ES
External object cache: |   | –

```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
`
### WordPress Environment ###

WordPress address (URL): http://judaicapanama.com
Site address (URL): http://judaicapanama.com
WC Version: 3.6.4
Log Directory Writable: ✔
WP Version: 5.2.1
WP Multisite: –
WP Memory Limit: 384 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.33 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 600
PHP Max Input Vars: 25000
cURL Version: 7.65.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.6.43
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 91.71MB
Database Data Size: 69.95MB
Database Index Size: 21.76MB
wp_woocommerce_sessions: Data: 3.02MB + Index: 0.05MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.11MB + Index: 0.11MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.09MB + Index: 0.09MB
wp_ewwwio_images: Data: 6.52MB + Index: 5.03MB
wp_ewwwio_queue: Data: 0.02MB + Index: 0.02MB
wp_gdbc_attempts: Data: 0.02MB + Index: 0.02MB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB
wp_gf_form: Data: 0.02MB + Index: 0.00MB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB
wp_hermes_user_like_ip: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_nm_personalized: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 4.45MB + Index: 0.30MB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB
wp_pmxi_images: Data: 0.06MB + Index: 0.00MB
wp_pmxi_imports: Data: 0.20MB + Index: 0.00MB
wp_pmxi_posts: Data: 0.02MB + Index: 0.03MB
wp_pmxi_templates: Data: 0.05MB + Index: 0.00MB
wp_postmeta: Data: 35.56MB + Index: 11.89MB
wp_posts: Data: 3.52MB + Index: 0.73MB
wp_revslider_css: Data: 0.20MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.17MB + Index: 0.00MB
wp_revslider_slides: Data: 1.52MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_siq_sync: Data: 0.08MB + Index: 0.00MB
wp_snippets: Data: 0.02MB + Index: 0.00MB
wp_swift_performance_image_optimizer: Data: 8.52MB + Index: 1.52MB
wp_termmeta: Data: 0.06MB + Index: 0.03MB
wp_terms: Data: 0.09MB + Index: 0.13MB
wp_term_relationships: Data: 0.31MB + Index: 0.17MB
wp_term_taxonomy: Data: 0.09MB + Index: 0.13MB
wp_tm_taskmeta: Data: 0.00MB + Index: 0.00MB
wp_tm_tasks: Data: 0.00MB + Index: 0.00MB
wp_usermeta: Data: 0.23MB + Index: 0.19MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wcz_cart_save: Data: 0.02MB + Index: 0.00MB
wp_wcz_cart_share: Data: 0.02MB + Index: 0.00MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.11MB + Index: 0.14MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wfBadLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedCommentLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB
wp_wfBlocks: Data: 0.02MB + Index: 0.02MB
wp_wfBlocksAdv: Data: 0.02MB + Index: 0.00MB
wp_wfConfig: Data: 0.27MB + Index: 0.00MB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_wfFileMods: Data: 1.52MB + Index: 0.00MB
wp_wfHits: Data: 0.06MB + Index: 0.05MB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB
wp_wfIssues: Data: 0.02MB + Index: 0.00MB
wp_wfKnownFileList: Data: 1.52MB + Index: 0.00MB
wp_wfLeechers: Data: 0.02MB + Index: 0.00MB
wp_wfLockedOut: Data: 0.02MB + Index: 0.00MB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_wfLogins: Data: 0.02MB + Index: 0.03MB
wp_wfNet404s: Data: 0.02MB + Index: 0.02MB
wp_wfNotifications: Data: 0.02MB + Index: 0.00MB
wp_wfPendingIssues: Data: 0.02MB + Index: 0.00MB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_wfScanners: Data: 0.02MB + Index: 0.00MB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wp_wfStatus: Data: 0.06MB + Index: 0.03MB
wp_wfThrottleLog: Data: 0.02MB + Index: 0.02MB
wp_wfVulnScanners: Data: 0.02MB + Index: 0.00MB
wp_wpfb_post_templates: Data: 0.02MB + Index: 0.00MB
wp_wpfb_reviews: Data: 0.02MB + Index: 0.00MB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.05MB
wp_yoast_seo_links: Data: 0.05MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.11MB + Index: 0.00MB

### Post Type Counts ###

attachment: 3600
custom_css: 1
global_product_addon: 1
jetpack_migration: 2
jp_img_sitemap: 2
jp_img_sitemap_index: 1
jp_sitemap: 1
jp_sitemap_master: 1
mailpoet_page: 1
nav_menu_item: 201
page: 17
post: 12
product: 1844
product_variation: 127
project: 13
scheduled-action: 81
shop_coupon: 4
shop_order: 40
shop_order_refund: 3
testimonial: 4
vc_grid_item: 1
wpcf7_contact_form: 2
wysijap: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (26) ###

Redux Framework: by Team Redux – 3.6.15
Custom Order Status for WooCommerce: by Tyche Softwares – 1.4.7 – Not tested with the active version of WooCommerce
Contact Form 7: by Takayuki Miyoshi – 5.1.3
WooCommerce Login/Signup Popup: by XootiX – 1.3 – Not tested with the active version of WooCommerce
Email Address Encoder: by Till Krüss – 1.0.19
EWWW Image Optimizer: by Exactly WWW – 4.7.4
Improved Product Options for WooCommerce: by 7VX LLC
USA CA – 4.6.6

WPBakery Page Builder: by Michael M - WPBakery.com – 6.0.3
LionThemes Helper: by LionThemes – 1.0.0
Loco Translate: by Tim Whitlock – 2.3.0
Mega Main Menu: by MegaMain.com – 2.1.2
Slider Revolution: by ThemePunch – 5.4.5.2
Sassy Social Share: by Team Heateor – 3.2.24
SearchIQ: by searchiq – 3.2
WPC Product Bundles for WooCommerce (Premium): by WPclever.net – 3.6.1
WooCommerce Network Merchants (NMI) Gateway (Enterprise): by Pledged Plugins – 2.1.3
WooCommerce Product Add-ons: by WooCommerce – 2.9.1 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.6.4
Yoast SEO Premium: by Team Yoast – 11.3
WP Google Review Slider: by LJ Apps – 5.5
WP Mail SMTP: by WPForms – 1.4.2
WP Rocket | Exclude Inline JS From Combine: by WP Rocket Support Team –
WP Rocket: by WP Media – 3.3.3.1
WP-ServerInfo: by Lester 'GaMerZ' Chan – 1.65
YITH WooCommerce Category Accordion Premium: by YITH – 1.0.27
YITH WooCommerce Wishlist: by YITH – 2.2.10

### Inactive Plugins (34) ###

Ad Inserter: by Igor Funa – 2.4.18
Akismet Anti-Spam: by Automattic – 4.1.2
Better Font Awesome: by Mickey Kay – 1.7.1
Code Snippets: by Shea Bunge – 2.13.3
Custom Sidebars: by WPMU DEV – 3.2.3
Facebook for WooCommerce: by Facebook – 1.9.12 – Not tested with the active version of WooCommerce
Mailchimp for WordPress: by ibericode – 4.5.2
MailChimp User Sync: by ibericode – 1.7.7
Order Delivery Date for WooCommerce (Lite version): by Tyche Softwares – 3.8.1
Polylang: by Frédéric Demarle – 2.5.4
Product/Review CSV Import Export: by WebToffee – 3.7.3 – Not tested with the active version of WooCommerce
PW WooCommerce Bulk Edit Pro: by Pimwick
LLC – 2.192

Really Simple SSL: by Rogier Lankhorst
Mark Wolters – 3.1.5

Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.1
Testimonials: by WooThemes – 1.5.4
TinyMCE Advanced: by Andrew Ozz – 5.2.1
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.14

WeCreativez Woo Cart Share & Save: by WeCreatiez – 1.1.1 – Not tested with the active version of WooCommerce
Woo Add Custom States: by Trusted Technology Solutions (TrusTech) – 1.3 – Not tested with the active version of WooCommerce
WooCommerce Advanced Product Labels: by BeRocket – 1.1.14 – Not tested with the active version of WooCommerce
Woocommerce Gift Wrapper: by Little Package – 3.0.4 – Not tested with the active version of WooCommerce
WooCommerce Show Single Variations by Iconic: by Iconic – 1.1.13 – Not tested with the active version of WooCommerce
WooCommerce Stock Manager: by Vladislav Musílek – 1.2.8 – Not tested with the active version of WooCommerce
Woo Title Limit: by Dima W. – 1.4.4 – Not tested with the active version of WooCommerce
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.3.3

wp-shabbat: by DrMosko – 2.3
WP All Import - WooCommerce Add-On Pro: by Soflyy – 3.0.6 – Not tested with the active version of WooCommerce
WP All Import Pro: by Soflyy – 4.5.5
WPBruiser: by Mihai Chelaru – 3.1.29
WP Disable: by optimisation.io - jody nesbitt – 1.5.21
WP Fastest Cache: by Emre Vona – 0.8.9.4
WP Fastest Cache Premium: by Emre Vona – 1.5.1
YITH WooCommerce Compare: by YITH – 2.3.10
YITH WooCommerce Zoom Magnifier: by YITH – 1.3.9

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
woosb (woosb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-filtered (exclude-from-filtered)
exclude-from-search (exclude-from-search)
featured (featured)
instock (instock)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
visible (visible)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #11 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Hermes Child
Version: 1.2
Author URL: http://lion-themes.com/
Child Theme: ✔
Parent Theme Name: Hermes
Parent Theme Version: 1.6.1
Parent Theme Author URL: http://lion-themes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: hermes-child/woocommerce/archive-product.php
hermes-child/woocommerce/cart/cart.php version 3.4.0 is out of date. The core version is 3.5.0
hermes-child/woocommerce/cart/cross-sells.php
hermes-child/woocommerce/checkout/form-checkout.php version 3.4.0 is out of date. The core version is 3.5.0
hermes-child/woocommerce/checkout/form-login.php
hermes-child/woocommerce/checkout/review-order.php
hermes-child/woocommerce/checkout/thankyou.php
hermes-child/woocommerce/content-product.php version 3.4.0 is out of date. The core version is 3.6.0
hermes-child/woocommerce/content-product_cat.php
hermes-child/woocommerce/content-single-product.php version 3.4.0 is out of date. The core version is 3.6.0
hermes-child/woocommerce/content-widget-product.php version 3.4.0 is out of date. The core version is 3.5.5
hermes-child/woocommerce/emails/customer-new-account.php version 1.6.4 is out of date. The core version is 3.5.2
hermes-child/woocommerce/global/breadcrumb.php
hermes-child/woocommerce/loop/loop-end.php
hermes-child/woocommerce/loop/loop-start.php
hermes-child/woocommerce/loop/orderby.php version 3.4.0 is out of date. The core version is 3.6.0
hermes-child/woocommerce/loop/result-count.php
hermes-child/woocommerce/myaccount/my-account.php version 3.4.0 is out of date. The core version is 3.5.0
hermes-child/woocommerce/myaccount/navigation.php
hermes-child/woocommerce/product-searchform.php
hermes-child/woocommerce/single-product/add-to-cart/grouped.php
hermes-child/woocommerce/single-product/add-to-cart/simple.php
hermes-child/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
hermes-child/woocommerce/single-product/price.php
hermes-child/woocommerce/single-product/rating.php version 3.4.0 is out of date. The core version is 3.6.0
hermes-child/woocommerce/single-product/related.php
hermes-child/woocommerce/single-product/review.php
hermes-child/woocommerce/single-product/sale-flash.php
hermes-child/woocommerce/single-product/short-description.php
hermes-child/woocommerce/single-product/up-sells.php
hermes-child/woocommerce/single-product-reviews.php version 3.4.0 is out of date. The core version is 3.6.0
hermes-child/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

### Action Scheduler ###

Complete: 80
Oldest: 2019-05-09 02:55:27 +0000
Newest: 2019-06-02 07:19:03 +0000

Pending: 1
Oldest: 2019-06-06 18:47:31 +0000
Newest: 2019-06-06 18:47:31 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by vedanshujain** [comment]
From system reports it looks you have a bunch of plugins active and the theme is "Hermes Child".

Can you verify if this issue happens after deactivating all plugins except WooCommerce, and using a default theme like "StoreFront". Please also paste a system report after doing doing the above? FWIW I hiding product when out of stock setting is working fine on my local install.

**Comment by rodrigoprimo** [comment]
Closing due to lack of feedback. Please leave a comment after testing what was suggested above and we will take a look. Thanks.
