### ISSUE TITLE
Singapore Missing City Field on Checkout Page

### ISSUE THREAD

**Issue by keninbassart** [woocommerce/woocommerce#23865]
**Describe the bug**
When Choosing Singapore as a country in WooCommerce, the City/Town filed is hidden. However that is a recommended field used in addresses for Singapore: https://en.wikipedia.org/wiki/Address#Singapore

**To Reproduce**
1. Go to checkout with Storefront and WooCommerce only
2. Change Country to Singapore
3. See error as city field disappears

**Screenshots**

USA: 

![USAddress](https://cld.wthms.co/mRWiyf+)
Image Link: https://cld.wthms.co/mRWiyf

Singapore: 

![singapore](https://cld.wthms.co/FpbBfj+)
Image Link: https://cld.wthms.co/FpbBfj

**Expected behavior**

City/Town should be a field for Singapore

**Isolating the problem (mark completed items with an [x]):**
- [X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X ] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment]
Probably better check with @Luminus first, since he introduced this change because a customer asked by live chat: https://github.com/woocommerce/woocommerce/pull/21018

**Comment by mouligreenlaw** [comment]
Back on this ticket 2079772-zen.
I tested this on my local site running WC 3.6.4.
It behaves exactly as expected by this PR [#21018](https://github.com/woocommerce/woocommerce/pull/21018) in that the field is hidden when the Country is selected as Singapore.

I can them proceed to checkout successfully as shown below, both being the order details after a successful checkout:

Tested on my dev site (WC 3.6.4) using Billing address in the US and Shipping address in Singapore and worked fine:

![https://cld.wthms.co/YyKZf3](https://cld.wthms.co/YyKZf3+) 
Full Size: https://cld.wthms.co/YyKZf3

Tested again using only Billing address and again it worked:

![https://cld.wthms.co/HyuRmP](https://cld.wthms.co/HyuRmP+) 
Full Size: https://cld.wthms.co/HyuRmP

So I am currently thinking possible conflict so will ask the user to test and I'll check that they are using the latest and greatest versions.

**Comment by Luminus** [comment]
Thanks for the ping @claudiosanches.

I've tested again using Stripe as the payment method as I see that @mouligreenlaw tested using Check payments and I wanted to rule out any issues.

It still works as expected for me

![Singapore Stripe](https://user-images.githubusercontent.com/248077/58931823-11ae8580-8759-11e9-91de-ce17f4bfe4c8.jpg)

**Comment by keninbassart** [comment]
I see why we made the change, yet the "official" address format ( https://en.wikipedia.org/wiki/Address#Singapore ) includes the city/town. Would it make sense to include the field but just make it optional to satisfy both customer requirements?

**Comment by claudiosanches** [comment]
@keninbassart I prefer this solution.

**Comment by claudiosanches** [comment]
See #23878
