### ISSUE TITLE
Impossible to remove attributes

### ISSUE THREAD

**Issue by fab33390** [woocommerce/woocommerce#23869]
**Describe the bug**
Hi, i need to remove the attributes, but after confirm to remove them, they remains.

**Comment by claudiosanches** [comment]
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. I tried to remove attributes and it appeared to work correctly.

Also it's missing several important information from the bug template that has been deleted here.

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

Thanks!
