### ISSUE TITLE
Removing a tax column should cause the order total to be updated to show the value without the removed tax

### ISSUE THREAD

**Issue by wvega** [woocommerce/woocommerce#23875]
**Is your feature request related to a problem? Please describe.**

I'm trying to remove taxes from an order by going to the Edit Order admin page and removing the tax column, using the X icon that appears next to the tax name:

<img width="947" alt="Screen Shot 2019-06-06 at 10 52 41 AM" src="https://user-images.githubusercontent.com/45068/59052181-1ad04d00-8854-11e9-8113-6271f4fbc25e.png">

However, the order total is not updated after I remove the tax column. The total continues to take into account the tax amount I removed:

<img width="940" alt="Screen Shot 2019-06-06 at 10 55 41 AM" src="https://user-images.githubusercontent.com/45068/59052211-2de31d00-8854-11e9-8905-833ad923c35f.png">

Is this the expected behavior?

The order total remains the same (including the removed tax amount) when I reload the page and shows up in the Sales report (I tested on a brand new installation with a single order so it was easy to notice that the gross sale value included the tax amount too).

**Describe the solution you'd like**
I think removing a tax column should cause the order total to be updated to not include the tax that was removed.

That seems to be the correct behavior because that's what happens automatically when you click the Update button after removing the tax column.

**Describe alternatives you've considered**
While I was testing, I noticed that if you change the order status (for example from Processing to Hold), the order total is updated to show the (what I think is) correct amount: the price of the items plus shipping without taxes:

After a support conversation with @ryanr14, he also found out that clicking the Update button in the Edit Order page (without changing the order status like I did before), causes the order total to show the correct amount.

This may sound like you need to persist the tax column removal, but that's not what I think is happening here, because the tax column (and associated order item) are permanently removed as soon as you click the X icon and OK in the confirmation dialog. You can reload the page and the column is gone.

**Additional context**
The description of this issue is already too long so I'm going to attach the System Status information instead of posting it here directly, in case that helps reproducing the scenario I mentioned above.

[woocommerce-system-status.txt.zip](https://github.com/woocommerce/woocommerce/files/3262800/woocommerce-system-status.txt.zip)

---

Thank your for reading 😁

**Comment by claudiosanches** [comment]
When doing changes in the order items, no matter if it's just products or taxes, you need to click in the `Recalculate` button, have you tried?

**Comment by ryanr14** [comment]
Hey @claudiosanches, I think the screenshots here were a little confusing. 

When @wvega and I were chatting, we were both able to remove the tax column when an order is Processing. With that order status there is no Recalculate button available, rather it says "This order is no longer editable" where that button would be. 

The one thing that does recalculate the order, but isn't clear to do, is selecting Update.

https://cld.wthms.co/VZyjW6

**Comment by claudiosanches** [comment]
@ryanr14 ohh, so we just need to remove that button when is in some status that doesn't allow to Recalculate anymore.

**Comment by claudiosanches** [comment]
#23884 will prevent taxes from being removed when an order is no longer editable, preventing the error you are seen to happens again. For this particular order that you had already this error, please move back to "on-hold", click in the "Recalculate" button, and then move again to "processing" or "complete" status.
Thanks for reporting it.

**Comment by wvega** [comment]
@claudiosanches and @ryanr14 thank you for checking this issue.

Unfortunately, I think moving back to On Hold and clicking the Recalculate button doesn't produce the expected result either. Once I press Recalculate, the column tax is added again:

https://d.pr/v/0Iffzv

If you remove the tax column, clicking Update is still the action that seems to get the total right.

If I change `is_vat_exempt` to `yes` and click Recalculate, then the totals are correct too and it actually removes the Tax column if it is still present. That makes sense in my case, because by removing the tax column what I really want is to prevent taxes from being calculated for that order, but maybe it only works if the order has a single tax rate (I haven't worked or tested with multiple tax rates).

However, it is still unclear why clicking Update gets the totals right, even when `is_vat_exempt` is still set to `no`.

And I think the behavior of the **Remove Tax Column** button still could be improved, because is not clear that you need to click Update after using it and that Recalculate adds the tax column again unless you change `is_vat_exempt`.

**Comment by claudiosanches** [comment]
> Unfortunately, I think moving back to On Hold and clicking the Recalculate button doesn't produce the expected result either. Once I press Recalculate, the column tax is added again:

Makes sense, it should calculate taxes again, since the setting is to have taxes included into all orders with no exceptions.

> However, it is still unclear why clicking Update gets the totals right, even when is_vat_exempt is still set to no.

I'll investigate this behavior, but sounds correct to just let you update in this case, without calculating everything again.
