### ISSUE TITLE
$order->set_parent_id() doesnt change post_parent

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce#23876]
When I do this:
$order->set_parent_id(10)

$order->get_parent_id( ) shows 10. so its correct

but when i manually check the 'wp_post' for this id(10)
the post_parent value will still be '0'

Isnt set_parent_id() will also change the post_parent for that  post?

because in this 'https://github.com/woocommerce/woocommerce/blob/b4352c8b32ca7d40d96694e02153e4427fc6fbd0/includes/data-stores/abstract-wc-order-data-store-cpt.php' line 73, its stated:
'post_parent'   => $order->get_parent_id( 'edit' ),

So $order->get_parent_id(  ) must be same with 'post_parent' right?

**Comment by claudiosanches** [comment]
I tested and works just fine.
My guess is that you are forgetting to save after you made those changes. While setting things, will change only in the object, then you need to use `$order->save()` to properly save in the database.
