### ISSUE TITLE
Variations menu order is ignored when the variation is fetched via ajax on select change

### ISSUE THREAD

**Issue by ionutcalara** [woocommerce/woocommerce#23872]
For a product that has 2 variations and both match (one attribute is set to any) you will always get the variation with the smallest post id. This is in spite of the fact you can order variations in the admin. 

The reason of this is that in the `find_matching_product_variation` method (`WC_Product_Data_Store_CPT`) there is a subquery used and that has an order. According to this the order in a subquery is ignored: https://mariadb.com/kb/en/library/why-is-order-by-in-a-from-subquery-ignored/

The solution I see here is either a join, or a new query just for the same posts to retrieve the menu order and sort them properly.

**Comment by claudiosanches** [comment]
Menu orders are always ignored on the front-end, that order is just for the back-end.
It's all ordering based on attributes, see that the dropdowns menus in the front-end shows attributes and not variations, that's why is not ordered like in the admin.

Duplicated of #18974

**Comment by ionutcalara** [comment]
@claudiosanches this is not about the order in the selects. This is a problem when you change the attributes and you get a different image, because the ajax returns a different variation than it should. 

Also for example: say you have t-shirts with size and color. If you would want to set all variations out of stock for xxl you could create a variation that has -- any color and the size xxl. Since this would be at the top with menu_order 0, it would be fetched when changing the select and you could overwrite all of the variations. 

However as mentioned, the subquery has an order clause which is ignored. I don't think this is intended, otherwise why have it there in the first place.

**Comment by claudiosanches** [comment]
Maybe are you referring about https://github.com/woocommerce/woocommerce/issues/23855 ?

**Comment by ionutcalara** [comment]
The issue he mentions is entirely different, but its related to the same function. However strange enough he says that changing the order works for him. 

I wouldn't really approve the idea in the patch there, i think ordering based on the menu order is the best way to choose how woocommerce chooses the variations when multiple match. I think that's the whole point of the menu order. Its just not working for the images. 

Here's a video of the issue. https://cl.ly/cd789bb36980

**Comment by claudiosanches** [comment]
See that `1508` uses `Small`, `Black Melange`, and `Any Logo`, then `2425` uses `Small`, `Black Melange`, and `Komlageret, Aarhus`. So this generate a conflict, you have two variations that can match at the same time, since `1508` uses `Any Logo`, in order to try fix it, you can try move in the admin the order from those variations, or even try remove the "duplicated match".

**Comment by ionutcalara** [comment]
I tried changing the order in both ways, as you can see 1508 is on the 6th page, while 2425 is on the first page. Based on its order 2425 should be the first.  I tried the other way around and its the same. The order is by post id, small to big (ASC)

As mentioned above I found the culprit. The reason of this is that in the find_matching_product_variation method (WC_Product_Data_Store_CPT) there is a subquery used and that has an order. According to this the order in a subquery is ignored: https://mariadb.com/kb/en/library/why-is-order-by-in-a-from-subquery-ignored/

The solution I see here is either a join, or a new query just for the same posts to retrieve the menu order and sort them properly.

**Comment by claudiosanches** [comment]
@ionutcalara have you tested https://github.com/woocommerce/woocommerce/pull/23067 ?

**Comment by ionutcalara** [comment]
I have checked it now, just in case i missed anything, but its not going to fix this, its a different issue that is being handled. In that PR "any" is allowed meaning a variation with just one attribute set to any will match. 
I am not having a problem with that since i have multiple attributes. 

What I need is for the subquery order to work. It seems that some mysql versions do take the subquery in account. However mariaDb for sure does not.

I can create a pull request, but I am not sure which option you guys would prefer. The simplest option would be to set a limit in the subquery. This causes mariadb to order the query. 
This option is mentioned here: https://mariadb.com/kb/en/library/why-is-order-by-in-a-from-subquery-ignored/

Another option would be a join in the outer query, or a new query to fill in the menu order and sort by it.

**Comment by claudiosanches** [comment]
@ionutcalara can you please test issue for me?

**Comment by ionutcalara** [comment]
@claudiosanches Yes i have tested it, sorry, should have been more specific in my response. 
PS. It turns out LIMIT for subqueries is also not supported in all mysql versions. So i think a join is required.

**Comment by claudiosanches** [comment]
Thanks, please feel free to submit a Pull Request, for sure will be better to debug it.

**Comment by ionutcalara** [comment]
@claudiosanches I added the pull request.

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

Please continue the discussion over at #23881.
