### ISSUE TITLE
Product Import issue

### ISSUE THREAD

**Issue by westsidekc** [woocommerce/woocommerce#23886]
Hi, don't know if this has been reported yet or not; I can't find it anywhere recent other than 3 months ago.  The import issue seems to be back with wordpress 5.2.1 and the newest woocommerce.  I disabled all plugins and switched to twentyseventeen theme and tried to import and import still didn't work.  Installing Disable Real MIME plugin was the only thing that worked.

![import issue](https://user-images.githubusercontent.com/51489763/59120882-31da7200-891c-11e9-8a87-b8fc4c889065.PNG)

**Comment by peterfabian** [comment]
Hi @westsidekc 

I remember seeing it briefly, but when I try with the sample file included with WC in `sample-data` now, it seems to work fine. Could you please provide a sample file where you see this problem to make it easier for us to reproduce? Thanks!

**Comment by rodrigoprimo** [comment]
Closing due to lack of feedback. If you are still experiencing this issue, please leave a comment with the information asked above, and we will take a look. Thanks.
