### ISSUE TITLE
WooCommerce databse error whenactivating programatically

### ISSUE THREAD

**Issue by sandeshjangam** [woocommerce/woocommerce#23882]
```
[07-Jun-2019 12:07:27 UTC] WordPress database error Table 'wp_cf.wp_wc_webhooks' doesn't exist for query SELECT webhook_id
				FROM wp_wc_webhooks
				WHERE 1=1
				AND `status` = 'active'
				ORDER BY webhook_id DESC made by require('wp-admin/index.php'), require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WooCommerce->init, WooCommerce->load_webhooks, wc_load_webhooks, WC_Data_Store->__call, WC_Webhook_Data_Store->get_webhooks_ids, WC_Webhook_Data_Store->search_webhooks
[07-Jun-2019 12:07:28 UTC] WordPress database error Table 'wp_cf.wp_woocommerce_attribute_taxonomies' doesn't exist for query SELECT * FROM wp_woocommerce_attribute_taxonomies WHERE attribute_name != '' ORDER BY attribute_name ASC; made by require('wp-admin/index.php'), require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Post_Types::register_taxonomies, wc_get_attribute_taxonomies

```

## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Ajax call to activate the WooCommerce plugin.
2. Function used to activate plugin activate_plugin( 'woocommerce/woocommerce.php', '', false, true );
3. Once the ajax call completes. It will activate the plugin. Then check to debug log. You will see an error.

PS. Enable debug and debug log before testing.

## Expected/actual behavior

When I follow those steps, I see...

```
[07-Jun-2019 12:07:27 UTC] WordPress database error Table 'wp_cf.wp_wc_webhooks' doesn't exist for query SELECT webhook_id
				FROM wp_wc_webhooks
				WHERE 1=1
				AND `status` = 'active'
				ORDER BY webhook_id DESC made by require('wp-admin/index.php'), require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WooCommerce->init, WooCommerce->load_webhooks, wc_load_webhooks, WC_Data_Store->__call, WC_Webhook_Data_Store->get_webhooks_ids, WC_Webhook_Data_Store->search_webhooks
[07-Jun-2019 12:07:28 UTC] WordPress database error Table 'wp_cf.wp_woocommerce_attribute_taxonomies' doesn't exist for query SELECT * FROM wp_woocommerce_attribute_taxonomies WHERE attribute_name != '' ORDER BY attribute_name ASC; made by require('wp-admin/index.php'), require_once('wp-admin/admin.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Post_Types::register_taxonomies, wc_get_attribute_taxonomies
```

I was expecting to see...

Ideally, it should not throw an error.

## Isolating the problem

- [X] This bug happens with only WooCommerce plugin active
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by claudiosanches** [comment]
> Ajax call to activate the WooCommerce plugin.

Please give me a full example of it.

**Comment by kloon** [comment]
@sandeshjangam just checking if you saw @claudiosanches request for an example on how to replicate this?

Tables are the first thing that needs to be created for the plugin to function so even if you split WooCommerce to run programmatically you will need to ensure that all the tables are there before you start executing any functionality.

Closing this issue as this is likely an issue in the way you are calling your custom code. Will gladly reopen if you can provide details to prove otherwise.

**Comment by sandeshjangam** [comment]
Sample plugin zip -  https://cl.ly/82c6c7663728

Note -
1. Do this on a fresh installation
2. Enable debug log constants.


Steps to reproduce -
1. Install and Activate it.
2. Go to Settings->Woo Install Demo
3. Click on  Install Woo Ajax 
4. It will automatically show you alert once the plugin is activated.
5. Refresh the page after an alert. 
6. Now go to debug log you will see an error.

I hope this information enough to reproduce the issue.

**Comment by sandeshjangam** [comment]
@kloon @claudiosanches

**Comment by claudiosanches** [comment]
This is a custom code, also seems like not enabling properly, need to build a link with nonces like WordPress activate action.

**Comment by eriteric** [comment]
A very similar error happens with wp-cli `wp site create` on a multisite install with woocommerce network activated.
