### ISSUE TITLE
Account creation settings not honoring 'email address' username

### ISSUE THREAD

**Issue by jrick1229** [woocommerce/woocommerce#23887]
**Describe the bug**

When enabling "When creating an account, automatically generate a username from the customer’s email address" in settings (_WooCommerce > Settings > Accounts & Privacy > Account creation_), the username created is still based off the customer's first and last name.

**To Reproduce**

1. Enable - `When creating an account, automatically generate a username from the customer’s email address`
2. Go through the checkout process in Incognito.
3. Create an account during checkout with a unique email address.
4. Navigate to: `.../wp-admin/users.php`
5. You'll see that the username is **not** based on the email address, but instead is a concatenation of the first and last name of the user.

**Expected behavior**

I expect that the username would be equal to the email address.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

### WordPress Environment ###

WordPress address (URL): http://subs2.local
Site address (URL): http://subs2.local
WC Version: 3.6.4
Log Directory Writable: ✔
WP Version: 5.2.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.14.0
PHP Version: 7.2.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.7.23
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 4.00MB
Database Data Size: 2.49MB
Database Index Size: 1.51MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_ariadminer_connections: Data: 0.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.14MB + Index: 0.16MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.03MB + Index: 0.05MB
wp_postmeta: Data: 0.33MB + Index: 0.33MB
wp_posts: Data: 0.16MB + Index: 0.13MB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wpml_mails: Data: 0.14MB + Index: 0.00MB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 13
product_variation: 5
revision: 8
scheduled-action: 285
shop_coupon: 4
shop_order: 32
shop_subscription: 14

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce Stripe Gateway: by WooCommerce – 4.2.0
WooCommerce: by Automattic – 3.6.4

### Inactive Plugins (4) ###

ARI Adminer: by ARI Soft – 1.2.3
WooCommerce Subscriptions: by Prospress Inc. – 2.5.4
WooCommerce Subscriptions: by Prospress Inc. – 2.5.6
WP Mail Logging: by Christian Zöller – 1.9.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.4.5 – 2.5.0 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 115
Oldest: 2019-05-18 19:27:44 +0000
Newest: 2019-06-07 17:15:30 +0000

Pending: 10
Oldest: 2019-07-04 21:08:27 +0000
Newest: 2020-06-07 16:45:12 +0000

Canceled: 160
Oldest: 2019-05-18 19:28:44 +0000
Newest: 2020-06-07 17:41:38 +0000

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

</details>

**Comment by malviyaritesh** [comment]
@jrick1229 The language in Accounts Settings section maybe little bit confusing, but essentially it creates username based off email on "My Account" page.
I've reviewed the code responsible for auto generating username. What I've learned from code review is that the username is created (if not provided) based on first and last name of the user ("Checkout" page), also if those (first and last name) are also not present (in case of "My Account" page), then it will fallback to email. Here are the supporting lines of code:
https://github.com/woocommerce/woocommerce/blob/9eca72849dba6c3c491e5822dee7a3b47c8bead4/includes/wc-user-functions.php#L134-L156

You can create new account on "My Account" page on frontend without providing username and then it'll use email for creating the username as first and last names are not provided.
This is not a bug and working as expected but language for setting is maybe little bit off.

**Comment by james-allan** [comment]
> This is not a bug and working as expected but language for setting is maybe little bit off.

I'm pretty sure this is a bug or I don't understand how this setting is intended to work. 

Pre WC 3.6, the username was always generated from the customer's email, not the first or last name. You can see how it was done here: https://github.com/woocommerce/woocommerce/blob/2.5.5/includes/wc-user-functions.php#L66-L78

**Comment by james-allan** [comment]
Oh ok. Looking at the relevant PR (https://github.com/woocommerce/woocommerce/pull/23145) and issue, I see how this change was actually intended.

If that's the case, I think the setting needs to be changed. The language is pretty confusing because it never actually meant that a username would be generated from the email specifically. It was really there to enable stores to create a username automatically, it just happened to be from the email.

**Comment by malviyaritesh** [comment]
@james-allan Yeah, better wording could be used but the behavior is intended. Its great that you verified my comment by referencing to the PR which clearly states that. :)

**Comment by kloon** [comment]
See #23911
