### ISSUE TITLE
Installation of WooCommerceNET onto .net project 3.5 Error

### ISSUE THREAD

**Issue by wgcdesigns** [woocommerce/woocommerce#23889]
Having issues installing package onto 3.5 project but i see dependency is 2.0.  Any trick to getting this to install right?

--

Install-Package WooCommerceX.NET -Version 0.7.5
Installing 'WooCommerceX.NET 0.7.5'.
Successfully installed 'WooCommerceX.NET 0.7.5'.
Adding 'WooCommerceX.NET 0.7.5' to ConnectionManager.
Uninstalling 'WooCommerceX.NET 0.7.5'.
Successfully uninstalled 'WooCommerceX.NET 0.7.5'.
Install failed. Rolling back...
Install-Package : Could not install package 'WooCommerceX.NET 0.7.5'. You are trying to install this package into a project that targe
ts '.NETFramework,Version=v3.5', but the package does not contain any assembly references or content files that are compatible with th
at framework. For more information, contact the package author.
At line:1 char:16
+ Install-Package <<<<  WooCommerceX.NET -Version 0.7.5
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : 

NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by kloon** [comment]
We do not maintain a WooCommerceX.net project, but a from someone else. I suggest you contact the developers of that package for support. This repository is only for issues/bugs related to WooCommerce core that is installed on WordPress.
