### ISSUE TITLE
Can't use newly added Attribute values in Variations

### ISSUE THREAD

**Issue by Argentus** [woocommerce/woocommerce#23880]
**Describe the bug**
While editing existing Variable Products, when I add a new Value to an Attribute, it is impossible to use this Value immediately to create Variations (without Updating the whole Product first). This is not the case when creating a new product.

**To Reproduce**
1. Create an Attribute "Color" with possible values "Black" and "White".
2. Create a Variable Product, which uses the Color attribute for variations, but only enable the "Black" value. Publish.
3. Edit this product.
4. Open Attributes. Add Color value "White" to the product. Save attributes.
5. Open Variations. Add new variation.
6. Open the combobox to choose Color for the new variation. Observe options.

**Expected behavior**
I expect to see options "Black" and "White", as I would if I was creating a new product, not editing an existing one.

**Real behavior**
I see only one option, "Black". Newly added "White" option is only offered after updating the product. 

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Tested on different setups, WooCommerce versions 3.4.5 and 3.6.4

**Comment by claudiosanches** [comment]
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. I tried all steps you described and it appeared to work correctly.

You can see my test in:
https://www.dropbox.com/s/70ghuf5212dn7ma/screencast-2019-06-07-issue-23880.mp4?dl=0

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

Thanks!
