### ISSUE TITLE
Attribute with zero value does not work with a large amount of variations

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#23895]
**Describe the bug**
When we use the attribute value "0" in a product with a large amount of variations (more then 30 to pass the threshold), it doesn't match the correct variation and always matches the variation with the "0" value.
In this specific case we are using an attribute called Numbers and Letters which has terms for 0 - 9 and A - Z. In total this will be 36 variations which is more then 30, in that case it uses the AJAX call `get_variation` to match the correct variation.

**To Reproduce**
1. Create a product attribute with terms 0 to 5
2. Create a variable product with a variation for each number
3. Use the filter `woocommerce_ajax_variation_threshold` to set the threshold to 5 (or alternatively create a variable product with all numbers and letters to surpass the 30 threshold)
4. Try to add a variation other then then number "0" to the cart
5. Get an error message something like this: `Invalid value posted for Numbers`
6. If we inspect the response of the AJAX call we can see it always matches the variation "0" regardless of which number we choose
7. If we change the filter `woocommerce_ajax_variation_threshold` to an amount that is larger then the amount of variations we can add the variations to the cart without any issues

**Expected behaviour**
I'd expect it to match the correct variation regardless of whether it's using an AJAX call or not.

**Additional information**
It fails to match the correct value because of the following line: https://github.com/woocommerce/woocommerce/blob/3.6.4/includes/data-stores/class-wc-product-data-store-cpt.php#L1118

If we are using an attribute with the term "0" this value is considered to be `empty`. Since that check fails the `$match` value remains true and we return the variation which matches "0". 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

```
WordPress 5.2.1
WooCommerce 3.6.4
Storefront: 2.5.0
```
</details>

**Comment by kloon** [comment]
See #23909
