### ISSUE TITLE
Remove / hide / disable the "Install WooCommerce Admin" message from dashboard for Shop Manager users

### ISSUE THREAD

**Issue by lucaspessoapereira** [woocommerce/woocommerce#23890]
Hello everyone!

I am trying to setup a sort of "whitelabel" dashboard for my clients. You know, removing generic items from the left admin menu (Posts, Pages, etc.), removing everything Wordpress related, etc. Everything was running well until this new "Install WooCommerce Admin" came up recently. Is there any way I can remove this only for Shop Managers? Here is how I removed generic Wordpress update messages on `functions.php` within my child theme:

```
//Remove update notifications
function remove_core_updates(){
    global $wp_version;return(object) array('last_checked'=> time(),'version_checked'=> $wp_version,);
    }

    if(current_user_can( 'shop_manager' )) {
        add_filter('pre_site_transient_update_core','remove_core_updates');
        add_filter('pre_site_transient_update_plugins','remove_core_updates');
        add_filter('pre_site_transient_update_themes','remove_core_updates');
    }
```

**Comment by malviyaritesh** [comment]
@lucaspessoapereira You can use `woocommerce_show_admin_notice` filter provided by WooCommerce in `class-wc-admin-notices.php:171`.
Put following code somewhere (e.g. functions.php of active child theme) from where WC can run it:
```
add_filter( 'woocommerce_show_admin_notice', function( $show, $notice ) {
	if( 'wc_admin' === $notice ) {
		$show = false;
	}
	return $show;
}, 10, 2 );
```
Its better to ask these type of questions on https://wordpress.stackexchange.com/

**Comment by lucaspessoapereira** [comment]
@malviyaritesh thanks, it worked
