### ISSUE TITLE
Woocommerce photoswipe CSS bug introduced in 3.6.0

### ISSUE THREAD

**Issue by fkoomek** [woocommerce/woocommerce#23900]
**Describe the bug**
Just found this bug. Happens with only Woocommerce active, default theme, no customizations, happens on all sites, all browsers.

**To Reproduce**
1. Go to the product page
2. Click on any image from the gallery to go full screen
3. Click zoom in
4. See error - image is shrunk
(the image has to be bigger than your monitor resolution of course)

**Screenshots**
![issue](https://user-images.githubusercontent.com/41650225/59225796-ee109280-8bd1-11e9-9cf2-64e840652d76.gif)

**Expected behavior**
The image resizes to its full size and it's possible to move with it.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### WordPress Environment ###

WordPress address (URL): https://www.test2.liberlapidum.com/test2
Site address (URL): https://www.test2.liberlapidum.com/test2
WC Version: 3.6.4
Log Directory Writable: ✔
WP Version: 5.2.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.6
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 5000
cURL Version: 7.52.1
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.15-MariaDB-1:10.3.15+maria~stretch-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.4
WC Database Prefix: jq6x_
MaxMind GeoIP Database: ✔
Total Database Size: 0.75MB
Database Data Size: 0.63MB
Database Index Size: 0.12MB
jq6x_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB
jq6x_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
jq6x_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
jq6x_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
jq6x_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
jq6x_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
jq6x_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
jq6x_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
jq6x_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
jq6x_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
jq6x_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
jq6x_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
jq6x_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
jq6x_woocommerce_log: Data: 0.00MB + Index: 0.00MB
jq6x_commentmeta: Data: 0.00MB + Index: 0.00MB
jq6x_comments: Data: 0.00MB + Index: 0.01MB
jq6x_links: Data: 0.00MB + Index: 0.00MB
jq6x_options: Data: 0.60MB + Index: 0.03MB
jq6x_postmeta: Data: 0.01MB + Index: 0.02MB
jq6x_posts: Data: 0.01MB + Index: 0.01MB
jq6x_termmeta: Data: 0.00MB + Index: 0.01MB
jq6x_terms: Data: 0.00MB + Index: 0.01MB
jq6x_term_relationships: Data: 0.00MB + Index: 0.00MB
jq6x_term_taxonomy: Data: 0.00MB + Index: 0.00MB
jq6x_usermeta: Data: 0.00MB + Index: 0.01MB
jq6x_users: Data: 0.00MB + Index: 0.01MB
jq6x_wc_download_log: Data: 0.00MB + Index: 0.00MB
jq6x_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB
jq6x_wc_webhooks: Data: 0.00MB + Index: 0.00MB
jq6x_yoast_seo_links: Data: 0.00MB + Index: 0.00MB
jq6x_yoast_seo_meta: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 2
nav_menu_item: 4
page: 9
polylang_mo: 2
post: 2
product: 7
product_variation: 4
revision: 9
scheduled-action: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.6.4

### Inactive Plugins (6) ###

Hyyan WooCommerce Polylang Integration: by Hyyan Abo Fakher – 1.4.0
Multi Currency for WooCommerce: by VillaTheme – 2.1.3.5
Polylang: by Frédéric Demarle – 2.5.4
W3 Total Cache: by Frederick Townes – 0.9.7.5
WOOCS - WooCommerce Currency Switcher: by realmag777 – 1.2.8.1
Yoast SEO: by Team Yoast – 11.3 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: –
Force SSL: –
Currency: CZK (Kč)
Currency Position: left
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #50 - /
Cart: #51 - /kosik/
Checkout: #52 - /pokladna/
My account: #53 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Nineteen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2019-06-08 19:50:23 +0200
Newest: 2019-06-08 19:50:23 +0200

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by fkoomek** [comment]
Bug was introduced in 3.6.0 release. It seems that it's something wrong in /woocommerce/assets/css/photoswipe/photoswipe.css

.woocommerce img.pswp__img,
.woocommerce-page img.pswp__img {
	max-width: none; /* 2 */
}
 
which was included in the previous Woocommerce version fix the issue.

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24296.
