### ISSUE TITLE
Netherlands (Amsterdam) postcode not recognised

### ISSUE THREAD

**Issue by jjbbrr** [woocommerce/woocommerce#23901]
When just the country Netherlands and the city Amsterdam are entered on /cart it is able to provide the correct shipping. But when the postcode is also entered it gives the error: "Please enter a valid postcode / ZIP." Customer says it gave the same error on /checkout but I could only reproduce it on /cart as it worked fine on /checkout for me.

It seems that the error message is displaying in error because it still lets you proceed. 

If I insert the Netherlands postcode 1234 AB then it works but if I do it without spaces 1234AB then it gives the error. 

Wordpress 5.2.1
Woocomerce 3.6.4

**Comment by kloon** [comment]
Certain countries expect certain formats for postal codes, WooCommerce enforces these formats that is why if you enter the postal code in the incorrect format it gives the error.

If you would like to not enforce the postal code formatting checks for NL you can use the following code snippet.

```php
add_filter( 'woocommerce_validate_postcode', 'custom_disable_nl_postcode_validation', 10, 3 );
function custom_disable_nl_postcode_validation( $valid, $postcode, $country ) {
    if ( 'NL' === $country ) {
        return true;
    }
    return $valid;
}
```

**Comment by jjbbrr** [comment]
The website of the post office in the Netherlands displays their postcodes on their website without spaces https://www.postnl.nl/en/location-finder?q=Amsterdam&f=8&c=0

So since the country's official post office are displaying postcodes without spaces, can Woocommerce also accept them without spaces please?

Ideally both 1073LP and 1073 LP would be accepted to allow for personal preferences, not just 1073 LP as it is at present.

**Comment by kloon** [comment]
See #23910

**Comment by jjbbrr** [comment]
Thanks for addressing this so promptly!

**Comment by claudiosanches** [comment]
Duplicated of https://github.com/woocommerce/woocommerce/issues/23834
