### ISSUE TITLE
"Add to cart" button not working

### ISSUE THREAD

**Issue by ashrafmisran** [woocommerce/woocommerce#23905]
My add to cart button at the single product page does not work.
I have use Request to Quote plugin and at first there is no issue. However, after many other configuration to other parts of the website, the button seems not working. I already tried to deactivate recently installed plugin but still not success.

**Comment by kloon** [comment]
@ashrafmisran in my tests it all works fine so not a WooCommerce core issue. Please go over the questions that you were presented with and asked to fill out when you opened the issue to troubleshoot as this is very likely a plugin or theme conflict.
