### ISSUE TITLE
'wp_woocommerce_downloadable_product_permissions'

### ISSUE THREAD

**Issue by Mustafa321md** [woocommerce/woocommerce#23907]
Failed to create tmp table _fwbk_wp_c9a0fkh0tm_wc_download_log. REFERENCES command denied to user  'lgc842649140119'@'160.153.154.27' for table 'wp_woocommerce_downloadable_product_permissions'

**Comment by kloon** [comment]
WooCommerce uses foreign key constraints and the DB user for your website does not seem to have regular permissions which would allow the creation of foreign keys.

You will have to alter your database user permissions for the specific user and enable the options to creates foreign keys.

**Comment by Mustafa321md** [comment]
But How??? Can you give me guide

**Comment by Mustafa321md** [comment]
but how to give premission?? there is any guide???
step by step??

**Comment by kloon** [comment]
You will have to contact your hosting provider as that is something server related and not WooCommerce related. They should be able to do it for you.
