### ISSUE TITLE
Difficulty reordering product variation attributes

### ISSUE THREAD

**Issue by f1alan** [woocommerce/woocommerce#23912]
**Describe the bug**
We have a product with variations but had big trouble reordering the variations. We ended up re-adding the attributes in a carefully choreographed way.

**To Reproduce**
Steps to reproduce the behaviour:

First we tried to drag and drop using the "three lines" icon in the Variations tab in the "Product data" widget on the product page. This did not change the order.

Secondly we went into the attributes section of the dashboard (/wp-admin/edit.php?post_type=product&page=product_attributes) and clicked on "Configure terms". Again, we used the "three lines" icon to rearrange but the new order was not saved. There is no explicit save button but some auto-save indication is given.

In the end we created new attributes in the order that we wanted, added them to the product and then replaced each of the existing variations with the attributes in the correct order. In addition, if we deleted the variations and re-added them then they would go away permanently and not be shown on the product page dropdown. Therefor it was essential to adapt the existing variations.

**WordPress Environment**
<details>

WordPress environment
--
WordPress address (URL): |   | http://***********
Site address (URL): |   | http://***********
WooCommerce version: |   | 3.6.4
Log directory writable: |   | /var/www/****/wp-content/uploads/wc-logs/
WordPress version: |   | 5.2.1
WordPress multisite: |   | –
WordPress memory limit: |   | 256 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_GB
External object cache: |   | –

</details>

**Comment by peterfabian** [comment]
Hi @f1alan 

I'm not completely sure if by reordering variations you mean ordering the attributes, but if yes, it should work if you set the attribute ordering to `Custom ordering` and order the terms via Configure terms, as you can see in the short video I recorded: https://youtu.be/j1QgTok8qFU

Have you tried if this works with other plugins disabled (preferably, on a staging site)?

**Comment by peterfabian** [comment]
Additionally, I forgot to mention that you can reorder attributes in the `Attributes` section of the Variable product:
https://youtu.be/Wn2AuUFbUYY

**Comment by f1alan** [comment]
Hi @peterfabian 

Thank you for the response. It looks like the problem was indeed related to another plugin (https://wordpress.org/plugins/taxonomy-terms-order/).

When I disabled it the problem stopped. They have actually released an updated today that fixes the bug.

I'm sorry for bothering you when it was not your problem.
