### ISSUE TITLE
wp_remove_object_terms() does not delete product query transients

### ISSUE THREAD

**Issue by stefanfisk** [woocommerce/woocommerce#23913]
**Describe the bug**
Removing terms via `wp_remove_object_terms()` does not result in `WC_Post_Data::delete_product_query_transients()` being called. This seems to be caused by `WC_Post_Data::delete_product_query_transients()` only being hooked to `set_object_terms`, which is only applicable for `wp_set_object_terms()` and its wrappers.

The `set_object_terms` hook is setup here: https://github.com/woocommerce/woocommerce/blob/9eca72849dba6c3c491e5822dee7a3b47c8bead4/includes/class-wc-post-data.php#L32.

I'm not at all familiar with the WooCommerce source code, but the simplest solution that I can see is to also hook into `deleted_term_relationships`.

**To Reproduce**
1. Remove a product category via `wp_remove_object_terms()`
2. View the category's archive
3. The loop will contain the product until the 'product_query' transient expires

**Screenshots**

**Expected behavior**
I'd expect the product query transients to be deleted.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by peterfabian** [comment]
Hi @stefanfisk 
Would you like to submit a PR for this one? Seems like you analysed it already.

**Comment by stefanfisk** [comment]
@peterfabian Sure!

I can see that `set_object_terms` is also hooked here, does that look like a place that might be suffering the same issue to you?

https://github.com/woocommerce/woocommerce/blob/29d630b0993702857e29bc7be14af17ae17ac471/includes/wc-term-functions.php#L600

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24297.
