### ISSUE TITLE
Show seconds on the Logs timestamp for better understanding of events

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#23914]
When looking at WooCommerce > Status > Logs the timestamp should show seconds because it will help better understanding what's happening and which events are occurring on the same PHP call, instead of several PHP calls on the same minute.
It's not failproof but it's better than having several events on the same minute and not knowing if they happened with 1 or 59 seconds interval.

I can submit a PR if you guys agree on this.

For performance debug it would event help to go behind seconds, but that would require to make bigger changes on the logger system.

**Comment by kloon** [comment]
@webdados thanks for the suggestion. Feel free to submit a PR.

**Comment by webdados** [comment]
This relies on the global date_format and time_format options, which I don't think makes a lot of sense because those settings are intended mostly for non-tech things.

Maybe this needs a bit more discussion before a PR is submitted.

I would just output it in ISO 8601: YYYY-MM-DD hh:mm:ss
But that's me :-)

**Comment by kloon** [comment]
@webdados I had a look now and the timestamps does have seconds as part of the timestamps. What is your logging method set as? Files or DB? Possible to show a screenshot of what you are seeing? See below an example of a file log entry for webhooks, note the date time on the first line has seconds.

```
2019-05-21T06:43:59+00:00 INFO Array
(
    [Webhook Delivery] => Array
        (
            [Delivery ID] => 40e91094da11b753d030ff19176a58e5
            [Date] => May 21, 2019 @ 6:43
            [URL] => https://xxx.xyz
            [Duration] => 0.97042
            [Request] => Array
                (
                    [Method] => POST
                    [Headers] => Array
                        (
                            [User-Agent] => WooCommerce/3.7.0 Hookshot (WordPress/5.2)
                            [Content-Type] => application/json
                            [X-WC-Webhook-Source] => https://wc.local/
                            [X-WC-Webhook-Topic] => action.woocommerce_order_status_processing
                            [X-WC-Webhook-Resource] => action
                            [X-WC-Webhook-Event] => woocommerce_order_status_processing
                            [X-WC-Webhook-Signature] => xxx
                            [X-WC-Webhook-ID] => 1
                            [X-WC-Webhook-Delivery-ID] => xxx
                        )

                )

            [Body] => {\"action\":\"woocommerce_order_status_processing\",\"arg\":75189}
            [Response] => Array
                (
                    [Code] => 200
                    [Message] => OK
                    [Headers] => Requests_Utility_CaseInsensitiveDictionary Object
                        (
                            [data:protected] => Array
                                (
                                    [server] => nginx/1.10.3
                                    [content-type] => text/plain; charset=UTF-8
                                    [vary] => Accept-Encoding
                                    [x-request-id] => xxx
                                    [x-token-id] => xxx
                                    [cache-control] => no-cache, private
                                    [date] => Tue, 21 May 2019 06:43:59 GMT
                                    [x-ratelimit-limit] => 30
                                    [x-ratelimit-remaining] => 29
                                    [content-encoding] => gzip
                                )

                        )

                    [Body] => 
                )

        )

)
```

Also looking at the code of each log handler is does specify the date time format to be `Y-m-d H:i:s`

https://github.com/woocommerce/woocommerce/blob/master/includes/log-handlers/class-wc-log-handler-file.php#L121
https://github.com/woocommerce/woocommerce/blob/master/includes/log-handlers/class-wc-log-handler-db.php#L64

**Comment by webdados** [comment]
Hi @kloon 

I know the logs have seconds on the database (I'm using DB), but my post is about the way it's shown on WooCommerce > Status > Logs:

![image](https://user-images.githubusercontent.com/6853605/59416203-d9442280-8dbc-11e9-8531-33d7b73bb0bf.png)

After I submitted this post I took a look at the code and found out that this is tied to the global WordPress date and time format options: https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-log-table-list.php#L129

Because this feature is to be used by technical users (mostly) I don't think this should be tied into the global WordPress date and time format, but rather be shown in a more standard way, like ISO8601 for example.
Sure the user can change its date and time format, but it will affect other areas of the website.

**Comment by kloon** [comment]
OK, makes sense to me. Even though it is controllable via the WordPress settings I have to agree that it could have an undesirable effect for the rest of your site. I am happy for you to submit a PR with a proposal of either sticking to a standard like we do when outputting it in files or using a combination of the WordPress date option with a custom time one. I am leaning more towards the first approach of sticking with using the format we use for files.

**Comment by webdados** [comment]
OK.

I'll do it with a standard (ISO 8601) as used on the database logger:
https://github.com/woocommerce/woocommerce/blob/master/includes/log-handlers/class-wc-log-handler-db.php#L64

**Comment by webdados** [comment]
Also, shouldn't we use date_i18n() instead of date() on https://github.com/woocommerce/woocommerce/blob/master/includes/log-handlers/class-wc-log-handler-db.php#L64 (like it's done on post_date on wp_posts, for example)?

Is there a technical reason to store GMT instead of local WordPress time?
Or maybe we should keep storing it in GMT and then display it in local WordPress adjusted time?

Honest question.

**Comment by kloon** [comment]
> Is there a technical reason to store GMT instead of local WordPress time?

Yes, system logs should always be stored in GMT. This is so when used with external systems tools, eg Grafana, it just works.

**Comment by webdados** [comment]
> Or maybe we should keep storing it in GMT and then display it in local WordPress adjusted time?

Nevermind. mysql2date already does that (supposedly) because the third argument, $translate, is set to true when omitted.

**Comment by claudiosanches** [comment]
Thank you for suggesting this feature!

I'm closing the issue as it already has a PR, please continue the discussion over at #23925.
