### ISSUE TITLE
shipping methods bug!

### ISSUE THREAD

**Issue by Bio4Pets2017** [woocommerce/woocommerce#23921]
I can no longer adjust my shipping methods, nor can I reset my shipping zones, shipping options, shipping classes to get back in ....!
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by kloon** [comment]
Please go through the steps as asked

```
I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
This bug happens with a default WordPress theme active, or Storefront.
I can reproduce this bug consistently using the steps above.
```

Closing as I am unable to replicate this on a test site, nor did you provide steps to reproduce this or indicated that you tested with all plugins except WooCommerce disabled and your theme switched to a default one.

I will gladly reopen if you can provide steps to replicate this on a store with just WooCommerce installed and a default theme.

**Comment by Bio4Pets2017** [comment]
De plugin Product Feed PRO for WooCommerce did the trick! That was causing the bug

I had it for al long time, but now I deactivated the plugin and everything works like a charm!

Thanx for your reply!

Have a nice day!

 

 

Mocht je lid willen worden van onze nieuwsbrief kun je je inschrijven als je dat wilt via  <http://www.bio4pets.nl/> www.bio4pets.nl (onderaan de pagina). Wij voegen namelijk niemand toe (Wij geven namelijk om jouw privacy)

 

 

mailto:info@bio4pets.nl

webshop:www.bio4pets.nl <http://www.bio4pets.nl/> 

Like ons op Facebook: https://www.facebook.com/Bio4Pets/

https://www.facebook.com/MashavdVelde

 

Tel:0641604318

 

Met vriendelijke groet,

 

Masha van der Velde

Namens Bio4Pets

Beschrijving: Beschrijving: C:\Users\Gebruiker\Documents\Bio4pets\logo nieuwst opgefrist.png

 

Van: Gerhard Potgieter [mailto:notifications@github.com] 
Verzonden: donderdag 13 juni 2019 09:32
Aan: woocommerce/woocommerce
CC: Bio4Pets2017; Author
Onderwerp: Re: [woocommerce/woocommerce] shipping methods bug! (#23921)

 

Please go through the steps as asked

I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
This bug happens with a default WordPress theme active, or Storefront.
I can reproduce this bug consistently using the steps above.

Closing as I am unable to replicate this on a test site, nor did you provide steps to reproduce this or indicated that you tested with all plugins except WooCommerce disabled and your theme switched to a default one.

I will gladly reopen if you can provide steps to replicate this on a store with just WooCommerce installed and a default theme.
