### ISSUE TITLE
Path issue

### ISSUE THREAD

**Issue by AmmadNazir** [woocommerce/woocommerce#23923]
WooCommerce Version: 3.6.4
**To Reproduce**
1. Go to 'Categories'
2. Click on 'Make Default any Category'
3. See side menu active link not visible

**Screenshots**

![woo-comm-error](https://user-images.githubusercontent.com/3511870/59419943-6ac78a80-8de5-11e9-8f89-4883a8444d37.png)

**Comment by vedanshujain** [comment]
Looks like this is happening because query param `&post_type=product` is missing in the `Make default` link.

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #23936.
