### ISSUE TITLE
Coupons on Manual Orders displaying "Coupon usage limit has been reached."

### ISSUE THREAD

**Issue by rwaynick** [woocommerce/woocommerce#23927]
**Describe the bug**
It's not possible to apply a coupon to a manual order.

When applying a coupon to a manual order the message, "Coupon usage limit has been reached." is displayed even though there are no usage restrictions. 

**To Reproduce**
1. Create a new coupon with a fixed or percentage discount and no usage restrictions.

<img width="1184" alt="Screen Shot 2019-06-13 at 9 39 34 AM" src="https://user-images.githubusercontent.com/10882502/59437517-bcf5b500-8dbf-11e9-8779-a00ea16ebf90.png">

2. Create a new manual order and add a product to the order.
3. Try and use the coupon.
4. See error, "Coupon usage limit has been reached."

![Screen_Shot_2019-06-13_at_9_40_30_AM](https://user-images.githubusercontent.com/10882502/59437530-c252ff80-8dbf-11e9-89e8-d3629286d755.jpg)

**Expected behavior**
I expect the coupon to be applied to the order.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active. 
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Reproduced on Atomic V2 with only Jetpack, Akismet, and WooCommerce active. Note, it's not possible to deactivate Jetpack and Akismet.
```
</details>

**Comment by rwaynick** [comment]
Also, I just reproduced on a clean jurassic.ninja site with only WC installed.

**Comment by malviyaritesh** [comment]
I guess, this issue has already been resolved. See PR #23851.

**Comment by claudiosanches** [comment]
Duplicated of #23850
