### ISSUE TITLE
wc_get_product_id_by_sku returns 0 (DB upgrade related)

### ISSUE THREAD

**Issue by rtnet-pl** [woocommerce/woocommerce#23929]
**Describe the bug**
Function wc_get_product_id_by_sku returns 0 for SKU of product that is present in database. It happens when you update WooCommerce plugin only, (no database)

**To Reproduce**
1. Upgrade WooCommerce (unfortunately I do not remember the old version number) to current version (3.6.4)
2. Ignore the database upgrade notification (do not upgrade database at this time).
3. Add some product with any SKU assigned (i.e. 'test123')
4. Proceed to upgrade the WC DB
5. Call function wc_get_product_id_by_sku('test123') - it will return 0 instead of actual product ID.
6. Delete the product and re-create it with same SKU - wc_get_product_id_by_sku will return a valid ID.
```
<?php
// test.php
include('wp-config.php');

$id = wc_get_product_id_by_sku('test123');
var_dump($id);

?>

```

**Expected behavior**
wc_get_product_id_by_sku('test123') should return actual product ID.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): http://poligon.rtnet.pl/borsuk
Site address (URL): http://poligon.rtnet.pl/borsuk
WC Version: 3.6.4
Log Directory Writable: ✔
WP Version: ❌ 5.1.1 - Jest dostępna nowsza wersja WordPressa (5.2.1)
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: pl_PL
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.25 (Debian)
PHP Version: 7.2.9-1+0~20180910100512.5+stretch~1.gbpdaac35
PHP Post Max Size: 80 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.26-MariaDB-0+deb9u1
Max Upload Size: 80 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Całkowity rozmiar bazy danych: 44.82MB
Rozmiar bazy danych: 23.34MB
Rozmiar indeksu bazy danych: 21.48MB
wp_woocommerce_sessions: Dane: 0.02MB + Indeks: 0.03MB
wp_woocommerce_api_keys: Dane: 0.02MB + Indeks: 0.03MB
wp_woocommerce_attribute_taxonomies: Dane: 0.02MB + Indeks: 0.02MB
wp_woocommerce_downloadable_product_permissions: Dane: 0.02MB + Indeks: 0.05MB
wp_woocommerce_order_items: Dane: 0.02MB + Indeks: 0.02MB
wp_woocommerce_order_itemmeta: Dane: 0.06MB + Indeks: 0.03MB
wp_woocommerce_tax_rates: Dane: 0.02MB + Indeks: 0.06MB
wp_woocommerce_tax_rate_locations: Dane: 0.02MB + Indeks: 0.05MB
wp_woocommerce_shipping_zones: Dane: 0.02MB + Indeks: 0.00MB
wp_woocommerce_shipping_zone_locations: Dane: 0.02MB + Indeks: 0.05MB
wp_woocommerce_shipping_zone_methods: Dane: 0.02MB + Indeks: 0.00MB
wp_woocommerce_payment_tokens: Dane: 0.02MB + Indeks: 0.02MB
wp_woocommerce_payment_tokenmeta: Dane: 0.02MB + Indeks: 0.03MB
wp_woocommerce_log: Dane: 0.02MB + Indeks: 0.02MB
wp_cennik: Dane: 0.02MB + Indeks: 0.00MB
wp_commentmeta: Dane: 0.02MB + Indeks: 0.03MB
wp_comments: Dane: 0.05MB + Indeks: 0.09MB
wp_links: Dane: 0.02MB + Indeks: 0.02MB
wp_options: Dane: 0.28MB + Indeks: 0.05MB
wp_postmeta: Dane: 17.19MB + Indeks: 16.19MB
wp_posts: Dane: 3.16MB + Indeks: 2.88MB
wp_termmeta: Dane: 0.02MB + Indeks: 0.03MB
wp_terms: Dane: 0.02MB + Indeks: 0.03MB
wp_term_relationships: Dane: 0.34MB + Indeks: 0.17MB
wp_term_taxonomy: Dane: 0.02MB + Indeks: 0.03MB
wp_usermeta: Dane: 0.20MB + Indeks: 0.19MB
wp_users: Dane: 0.02MB + Indeks: 0.05MB
wp_video: Dane: 0.02MB + Indeks: 0.00MB
wp_wc_download_log: Dane: 0.02MB + Indeks: 0.03MB
wp_wc_product_meta_lookup: Dane: 1.42MB + Indeks: 1.22MB
wp_wc_webhooks: Dane: 0.02MB + Indeks: 0.02MB
wp_wyszukiwarka: Dane: 0.02MB + Indeks: 0.00MB
wp_wyszukiwarka_params: Dane: 0.02MB + Indeks: 0.00MB
wp_yoast_seo_links: Dane: 0.02MB + Indeks: 0.02MB
wp_yoast_seo_meta: Dane: 0.02MB + Indeks: 0.00MB
zzz_rtExportedOrders: Dane: 0.02MB + Indeks: 0.02MB
zzz_RtnetExportedOrders: Dane: 0.02MB + Indeks: 0.00MB
zzz_RtnetProductAviability: Dane: 0.02MB + Indeks: 0.00MB
zzz_RtnetSubsyncSecret: Dane: 0.02MB + Indeks: 0.00MB
zzz_RtnetTasks: Dane: 0.02MB + Indeks: 0.00MB

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 368
flamingo_contact: 28
flamingo_inbound: 2
page: 14
post: 5
product: 6131
product_variation: 350
revision: 24
scheduled-action: 14
shop_coupon: 1
shop_order: 22
shop_order_refund: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌
					Twój sklep nie używa protokołu HTTPS. Dowiedz się więcej o HTTPS i certyfikatach SSL .
Hide errors from visitors: ✔

### Active Plugins (13) ###

RTNET SubSync: przez rtnet.pl – 1.2 – Nietestowane z używaną wersją WooCommerce
Advanced Custom Fields: przez Elliot Condon – 5.7.7
Cennik: przez rtnet.pl – 1.0
Contact Form 7: przez Takayuki Miyoshi – 5.0.4
Easy WP SMTP: przez wpecommerce
alexanderfoxc – 1.3.7

Flamingo: przez Takayuki Miyoshi – 1.9
Perfect WooCommerce Brands: przez Alberto de Vera Sevilla – 1.6.5 – Nietestowane z używaną wersją WooCommerce
WooCommerce Przelewy24 Payment Gateway: przez DialCom24 Sp. z o.o. – 1.0.0 – Nietestowane z używaną wersją WooCommerce
User Role Editor: przez Vladimir Garagulya – 4.44
RTNET Video: przez rtnet.pl – 1.0
WooCommerce UPC, EAN, and ISBN: przez Scott Bolinger – 0.4.0 – Nietestowane z używaną wersją WooCommerce
WooCommerce: przez Automattic – 3.6.4
RTNET Wyszukiwarka: przez rtnet.pl – 1.0

### Inactive Plugins (3) ###

Akismet: przez Automattic – 3.1.7
Hello Dolly: przez Matt Mullenweg – 1.6
Yoast SEO: przez Team Yoast – 7.4.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: PLN (zł)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Strona sklepu: #9606 - /sklep/
Koszyk: #9698 - /cart/
Zamówienie: #9700 - /checkout/
Moje konto: #9702 - /account/
Regulamin: #9704 - /tos/

### Theme ###

Name: Twenty Sixteen
Version: 1.1 – 2.0 jest dostępne
Author URL: https://pl.wordpress.org/
Child Theme: ❌ – Jeśli modyfikujesz WooCommerce lub motyw nadrzędny
którego nie jesteś autorem
polecamy używanie motywu potomnego. Zobacz: Jak tworzyć motywy potomne

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 14
Oldest: 2019-06-13 15:49:04 +0200
Newest: 2019-06-13 15:50:22 +0200

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by kloon** [comment]
I am unable to replicate this locally, once the table is populated and I run wc_get_product_id_by_sku it returns the correct value.

It might also be related to your DB caching results? Worth doing some more testing on your side, also remember that the DB update routine runs in the background and is delayed so it could be that you are getting skewed results because the DB upgrade has not completed yet?

Can you please do some more testing and let me know the results? Try and only run the function again after you are sure the DB has been upgraded completely, check in WooCommerce -> Tools -> Scheduled Actions and look for the upgrade routine, it should show as done and not pending or running. Please also try and query for a different sku after doing it the first time to see if you might be getting cached results?

**Comment by mw108** [comment]
Having the same issue. In fact, I found this report when searching Google for "wc_get_product_id_by_sku returns 0".

I updated WP, all plugins and DB yesterday and since then I'm having the issue.

The product exists in the database with the SKU. Before the update it worked fine. But after the update wc_get_product_id_by_sku() returns 0 for a given product.

So I just re-saved the product without changing anything else and suddenly it works again ... ?!

**Comment by jas8522** [comment]
I had this same problem and found a failing Scheduled Action in the list that was preventing the DB upgrade task from completing successfully. I removed the failing scheduled action, then re-triggered the DB upgrade and my SKU searches all work successfully.

**Comment by mw108** [comment]
Yes, it has something to do with wc_product_meta_lookup table not being populated correctly.

You can also fix it by going to WooCommerce > Tools > Regenerate Lookup tables.

https://wordpress.org/support/topic/woocommerce-3-6-1-breaks-wc_get_product_id_by_sku/

**Comment by rtnet-pl** [comment]
@kloon I'm certain that db upgrade process was done with no errors.
It's not that easy for me to reproduce this. We're selling some integration software (ERP + WC) and i've seen this issue more than 10 times, different customers.
Once we've reproduced it in our testing environment - the details above are from this.

For us it is hard to tell the customer to provide some more details, customer is usually not that experienced to do that. And we can't just get into customers server to do research because of gdpr (additional paperwork etc.)

**Comment by claudiosanches** [comment]
For the steps in here sounds like something wrong to do, since is editing products without updating the database, this is something that will cause problems for sure.
Please update the database as soon as possible, to avoid any problem like that.
Closing since is a problem generated by not updating the database.

**Comment by mw108** [comment]
The related question here is, why the database update does / did not get automatically triggered after a WC update.

**Comment by claudiosanches** [comment]
@mw108 there's not a single update for skus for any version of WooCommerce, so should not run any update routine on it, still plugins or themes may influence on it, there's many things that could cause it, still need to have the database updated before editing anything, it's something required to make WooCommerce work properly.
