### ISSUE TITLE
NEW WORDPRESS WEBSITE WITH WOOCOMMERCE CONTINOUS HIGH CPU USAGE

### ISSUE THREAD

**Issue by isaiapasca** [woocommerce/woocommerce#23938]
Using a standard stock WordPress and woocomerce plugin, Logged in and left the page open on
https://arkpc.com.au/wp-admin/edit.php?post_type=shop_order
No orders yet in the store!

i noticed a huge server load this morning and i had a look to find out the problem, and i found the following:

1000 errors in google chrome console:

Failed to load resource: the server responded with a status of 403 (Forbidden)
/wp-json/wc/v4/admin/notes?order=desc&orderby=date&page=1&per_page=1&type=info%2Cwarning&_locale=user:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
/wp-json/wp/v2/users/me?context=edit&_locale=user:1 Failed to load resource: the server responded with a status of 403 (Forbidden)

this obviously is a bug in woocomerce or WordPress, not sure, not 100% where i should post this so anyone with proper technical knowledge gets on to this bug and fixes it.
any help appreciated.

I have to say that this happened while using Chrome Browser and the page was not in focus,

Anyone's help appreciated.

**WordPress Environment**
`
### WordPress Environment ###

WordPress address (URL): https://arkpc.com.au
Site address (URL): https://arkpc.com.au
WC Version: 3.6.4
Log Directory Writable: ✔
WP Version: 5.2.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.6
PHP Post Max Size: 16 MB
PHP Time Limit: 90
PHP Max Input Vars: 2000
cURL Version: 7.65.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.7.26
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.4
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 3.27MB
Database Data Size: 2.71MB
Database Index Size: 0.56MB
wp_woocommerce_sessions: Data: 0.21MB + Index: 0.01MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_comments: Data: 0.10MB + Index: 0.08MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_nm_personalized: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 0.58MB + Index: 0.04MB
wp_postmeta: Data: 0.17MB + Index: 0.05MB
wp_posts: Data: 0.24MB + Index: 0.08MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.01MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.01MB
wp_usermeta: Data: 0.00MB + Index: 0.01MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_admin_notes: Data: 0.00MB + Index: 0.00MB
wp_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB
wp_wc_customer_lookup: Data: 0.00MB + Index: 0.00MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB
wp_wc_order_product_lookup: Data: 0.00MB + Index: 0.00MB
wp_wc_order_stats: Data: 0.00MB + Index: 0.00MB
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_wfblockediplog: Data: 0.00MB + Index: 0.00MB
wp_wfblocks7: Data: 0.00MB + Index: 0.00MB
wp_wfconfig: Data: 0.37MB + Index: 0.01MB
wp_wfcrawlers: Data: 0.00MB + Index: 0.00MB
wp_wffilechanges: Data: 0.00MB + Index: 0.00MB
wp_wffilemods: Data: 0.66MB + Index: 0.11MB
wp_wfhits: Data: 0.00MB + Index: 0.00MB
wp_wfhoover: Data: 0.00MB + Index: 0.00MB
wp_wfissues: Data: 0.00MB + Index: 0.00MB
wp_wfknownfilelist: Data: 0.32MB + Index: 0.05MB
wp_wflivetraffichuman: Data: 0.00MB + Index: 0.00MB
wp_wflocs: Data: 0.00MB + Index: 0.00MB
wp_wflogins: Data: 0.00MB + Index: 0.00MB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB
wp_wfnotifications: Data: 0.00MB + Index: 0.00MB
wp_wfpendingissues: Data: 0.00MB + Index: 0.00MB
wp_wfreversecache: Data: 0.00MB + Index: 0.00MB
wp_wfsnipcache: Data: 0.00MB + Index: 0.00MB
wp_wfstatus: Data: 0.01MB + Index: 0.01MB
wp_wftrafficrates: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

attachment: 28
custom_css: 1
customize_changeset: 14
fpf_fields: 3
nav_menu_item: 10
page: 9
post: 3
product: 9
product_variation: 9
revision: 36
scheduled-action: 373
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (9) ###

Contact Form 7: by Takayuki Miyoshi – 5.1.3
Facebook for WooCommerce: by Facebook – 1.9.12 – Not tested with the active version of WooCommerce
Flexible Product Fields Pro: by WP Desk – 1.2.1
Flexible Product Fields: by WP Desk – 1.1.20
WooCommerce Admin: by WooCommerce – 0.12.0
WooCommerce eWAY Payment Gateway: by WooCommerce – 3.1.20
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.14
WooCommerce Services: by Automattic – 1.20.0
WooCommerce: by Automattic – 3.6.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: #3 - /privacy-policy/

### Theme ###

Name: Storefront
Version: 2.5.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 370
Oldest: 2019-05-21 05:25:48 +0000
Newest: 2019-06-15 01:02:04 +0000

Pending: 1
Oldest: 2019-06-15 02:02:04 +0000
Newest: 2019-06-15 02:02:04 +0000

Canceled: 2
Oldest: 2019-06-06 09:37:43 +0000
Newest: 2019-06-06 09:53:59 +0000

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by mikkamp** [comment]
The endpoint `/wp-json/wc/v4/admin/notes` is used by the WooCommerce Admin plugin. 

Your status report mentions `WooCommerce Admin: by WooCommerce – 0.12.0`
As an initial step I'd suggest to try and recreate the issue with the latest version. If it's still causing problems then it would be better to report this directly for the WooCommerce Admin plugin in the following location: https://github.com/woocommerce/woocommerce-admin/issues

**Comment by rrennick** [comment]
This should have been fixed in the latest version (0.13.2) of WooCommerce Admin. The issue was originally reported in https://github.com/woocommerce/woocommerce-admin/issues/2365.

@isaiapasca If you still have the issue after updating to the latest version of WooCommerce Admin, please open an issue at https://github.com/woocommerce/woocommerce-admin/issues.
