### ISSUE TITLE
Failed retrieving orders

### ISSUE THREAD

**Issue by MamaGof4** [woocommerce/woocommerce#23937]
**Describe the bug**
It will not retrieve my orders from the website or app. It keeps saying there was an error.

**To Reproduce**
Try to view orders in any area on the app or on site.

**Screenshots**
It won't let me add it here but its a giant purple triangle that pops up.

**Expected behavior**
To see any new orders.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
`
### WordPress Environment ###

WordPress address (URL): https://www.mamagof4sgiftsandmore.com
Site address (URL): https://www.mamagof4sgiftsandmore.com
WC Version: 3.6.4
Log Directory Writable: ✔
WP Version: 5.2.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.6
PHP Post Max Size: 65 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.38-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.4
WC Database Prefix: wp_9zzmqf_
Total Database Size: 15.07MB
Database Data Size: 13.41MB
Database Index Size: 1.66MB
wp_9zzmqf_woocommerce_sessions: Data: 3.02MB + Index: 0.11MB
wp_9zzmqf_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_9zzmqf_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_9zzmqf_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_9zzmqf_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_9zzmqf_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_9zzmqf_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_9zzmqf_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_9zzmqf_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_9zzmqf_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_9zzmqf_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_9zzmqf_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_9zzmqf_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_9zzmqf_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_9zzmqf_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_9zzmqf_comments: Data: 0.02MB + Index: 0.09MB
wp_9zzmqf_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_9zzmqf_links: Data: 0.02MB + Index: 0.02MB
wp_9zzmqf_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_9zzmqf_options: Data: 5.02MB + Index: 0.08MB
wp_9zzmqf_postmeta: Data: 1.52MB + Index: 0.22MB
wp_9zzmqf_posts: Data: 3.11MB + Index: 0.16MB
wp_9zzmqf_queue: Data: 0.02MB + Index: 0.00MB
wp_9zzmqf_termmeta: Data: 0.02MB + Index: 0.03MB
wp_9zzmqf_terms: Data: 0.02MB + Index: 0.03MB
wp_9zzmqf_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_9zzmqf_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_9zzmqf_usermeta: Data: 0.02MB + Index: 0.03MB
wp_9zzmqf_users: Data: 0.02MB + Index: 0.05MB
wp_9zzmqf_wc_admin_notes: Data: 0.02MB + Index: 0.00MB
wp_9zzmqf_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB
wp_9zzmqf_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB
wp_9zzmqf_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_9zzmqf_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB
wp_9zzmqf_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB
wp_9zzmqf_wc_order_stats: Data: 0.02MB + Index: 0.05MB
wp_9zzmqf_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB
wp_9zzmqf_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_9zzmqf_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_9zzmqf_yith_wcwl: Data: 0.02MB + Index: 0.02MB
wp_9zzmqf_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB

### Post Type Counts ###

attachment: 218
customize_changeset: 20
jetpack_migration: 2
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
nav_menu_item: 12
oembed_cache: 1
page: 13
post: 7
product: 62
product_variation: 39
revision: 75
scheduled-action: 571
shop_coupon: 3
shop_order: 1
wp_block: 2
wpcf7_contact_form: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

Akismet Anti-Spam: by Automattic – 4.1.2
Contact Form 7: by Takayuki Miyoshi – 5.1.3
DreamHost Panel Login: by DreamHost
danielbachhuber – 1.0.0

Easy Google Fonts: by Titanium Themes – 1.4.4
Facebook for WooCommerce: by Facebook – 1.9.12 – Not tested with the active version of WooCommerce
Flexible Shipping UPS: by WP Desk – 1.5.0
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.6.0
Remixer Gutenberg Blocks: by DreamHost – 1.0.0
Gutenberg: by Gutenberg Team – 5.9.1
Jetpack by WordPress.com: by Automattic – 7.4
Mailchimp for WooCommerce: by Mailchimp – 2.1.16 – Not tested with the active version of WooCommerce
Official Facebook Pixel: by Facebook – 1.7.25
One Click Demo Import: by ProteusThemes – 2.5.1
WooCommerce PDF Invoices, Packing Slips, Delivery Notes & Shipping Labels(Basic): by WebToffee – 2.4.8
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.1
ThemeGrill Demo Importer: by ThemeGrill – 1.5.7
WooCommerce Weight Based Shipping: by weightbasedshipping.com – 5.2.6
WooCommerce Admin: by WooCommerce – 0.13.2
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.14
WooCommerce Stripe Gateway: by WooCommerce – 4.2.0
WooCommerce Services: by Automattic – 1.20.0
WooCommerce Square: by WooCommerce – 1.0.37
WooCommerce: by Automattic – 3.6.4
WordPress Importer: by wordpressdotorg – 0.6.4
WP-PageNavi: by Lester 'GaMerZ' Chan – 2.93
WP Super Cache: by Automattic – 1.6.7
WPForms Lite: by WPForms – 1.5.2.3
YITH WooCommerce Compare: by YITH – 2.3.12
YITH WooCommerce Quick View: by YITH – 1.3.11
YITH WooCommerce Wishlist: by YITH – 2.2.11

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #13 - /shop/
Cart: #14 - /cart/
Checkout: #15 - /checkout/
My account: #16 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: eStore
Version: 1.3.8
Author URL: https://www.themegrill.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: estore/woocommerce/archive-product.php
estore/woocommerce/cart/cart-totals.php
estore/woocommerce/cart/cross-sells.php
estore/woocommerce/checkout/form-billing.php
estore/woocommerce/checkout/form-checkout.php
estore/woocommerce/checkout/form-login.php
estore/woocommerce/content-product.php
estore/woocommerce/content-single-product.php
estore/woocommerce/global/wrapper-end.php
estore/woocommerce/global/wrapper-start.php
estore/woocommerce/loop/add-to-cart.php
estore/woocommerce/loop/price.php
estore/woocommerce/loop/rating.php
estore/woocommerce/single-product/price.php
estore/woocommerce/single-product/related.php
estore/woocommerce/single-product.php
estore/woocommerce/taxonomy-product_cat.php

### Action Scheduler ###

Complete: 568
Oldest: 2019-05-17 00:16:12 +0000
Newest: 2019-06-14 15:15:07 +0000

Pending: 2
Oldest: 2019-06-14 16:15:07 +0000
Newest: 2019-06-14 16:15:07 +0000

Canceled: 1
Oldest: 2019-06-01 15:46:17 +0000
Newest: 2019-06-01 15:46:17 +0000

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by kloon** [comment]
Hi @MamaGof4 this sounds like an issue with the App you are using and not WooCommerce. Have you tried contacting support for the app? This repository is only for issues relating to the WooCommerce core plugin and not the Apps or Extensions that integrate with it.

I am going to close this but will gladly reopen is this happens to be an issue with WooCommerce core, but please first try and contact the app support and test with all extensions disabled and your theme switched to Twenty Seventeen or Storefront before proceeding to rule out any conflicts.

**Comment by MamaGof4** [comment]
That's so funny because that's what the apps tech support said too, that it
wasnt them it was the Woocommerce site.

I'm really close to shutting it all down and going somewhere else.

Always with love,

MamaGof4

**Comment by claudiosanches** [comment]
@MamaGof4 please, let they know that they may start an issue here describing why they think that is an issue on WooCommerce, so everyone can help each other.
