### ISSUE TITLE
ToolTip on product sale start/end dates is incorrect.

### ISSUE THREAD

**Issue by dsmithweb** [woocommerce/woocommerce#23931]
**Describe the bug**

When you hover over the the question mark for a product's sale start-and-end dates, it says the sale will end when the end date arrives:

![image](https://user-images.githubusercontent.com/20285748/59452862-47e0aa80-8dd4-11e9-8051-4f2fd87b4ab9.png)

However,  that's not the case; the sale expires at 11:59pm on the specified end date, per https://docs.woocommerce.com/document/managing-products/#general-section   

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by kloon** [comment]
Please see #23935 for fix
