### ISSUE TITLE
Checkout enabled for postcodes outside shipping zones

### ISSUE THREAD

**Issue by Xronn** [woocommerce/woocommerce#23934]
Users are able to enter their billing/shipping details and change their country to an option with cheaper postage even though their postcode is not whitelisted within that region. Checkout is still permitted. 

**To Reproduce**
1. Create 2 shipping zones e.g England & Wales, & Scottish Isles
2. Set your shipping methods for both & insert white listed postcodes for both
3. Go to check out on the front-end enter the postcode for 1 of the shipping zones
4. Notice you can select either of the 2 countries even though the postcode is only enabled in 1.

Shipping zone 1# No PH33* postcode
![Image of zone 1](https://puu.sh/DFCn6/ca7ae366a2.png)

Shipping zone 2# includes PH33* postcode
![Image of zone 2](https://puu.sh/DFCnz/6b43161ada.png)

Checkout should only be whitelisted for 1 shipping zone. All shipping zones can be selected

**Expected behavior**
Once a user has entered their postcode they should be unable to checkout & complete a purchase or unable to select a country where the postcode is not whitelisted.

**Comment by peterfabian** [comment]
Hi @Xronn 

I've tried your steps to reproduce. Apologies, but I don't really understand the problem.

I've created the shipping zones as per your instructions:
![Screenshot 2019-06-19 at 15 12 03](https://user-images.githubusercontent.com/2207451/59768426-a4483c00-92a4-11e9-878d-dd62aa36aeb5.png)

![Screenshot 2019-06-19 at 15 23 38](https://user-images.githubusercontent.com/2207451/59769355-4288d180-92a6-11e9-8bf9-461a97c6ee7b.png)

Now going to the checkout, I enter postcode for England and Wales, that's not in the list and it gets matched with 'Locations not covered by your other zones':
![Screenshot 2019-06-19 at 15 16 42](https://user-images.githubusercontent.com/2207451/59768867-60a20200-92a5-11e9-911b-2e0bf24d0c0d.png)

If I enter postcode starting with NR, the shipping options get updated to those available via England & Wales. As soon as I enter the PH3 zipcode, the shipping options got updated as well. If I change the country, the shipping changes to 'Locations not covered by your other zones':
https://youtu.be/PMcdFbkx3w0

Can you please elaborate where you see the problem? 
Also, it would help us if you included your [system status report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) and your shipping settings.

**Comment by rodrigoprimo** [comment]
Closing due to lack of feedback. If you are still experiencing this issue, please leave a comment with the information asked above, and we will take a look. Thanks.
