### ISSUE TITLE
São Tomé and Príncipe dobra has old currency code

### ISSUE THREAD

**Issue by jpknz** [woocommerce/woocommerce#23944]
`get_woocommerce_currencies()` will return STD for the São Tomé and Príncipe dobra. This currency and code was retired in 2018. The new São Tomé and Príncipe dobra has a code of STN.

See the below for confirmation
https://en.wikipedia.org/wiki/S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe_dobra
![image](https://user-images.githubusercontent.com/36459775/59564596-8bd7e780-9040-11e9-98c9-844eed074b52.png)

Expected behavior
STN returned for São Tomé and Príncipe dobra when `get_woocommerce_currencies()` called.

See also https://github.com/woocommerce/woocommerce/issues/23943

**Comment by kloon** [comment]
See #23950
