### ISSUE TITLE
Why i get the variation id is 0 in some products

### ISSUE THREAD

**Issue by vioulo** [woocommerce/woocommerce#23945]
I get orders info by the rest API, in field `line_items`, some products's `variation_id` is 0,
who know why ?
sure,some products's id also is 0!

**Comment by peterfabian** [comment]
Hi @vioulo,

`variation_id` is 0 if the product is not a variable product (e.g. a simple product), then there is no variation and API returns 0. You can see this also in the example in the docs: https://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-an-order
First line item is simple product, second line item is variable product.
