### ISSUE TITLE
Unhelpful mention of "Shipping Section" on stores with shipping disabled

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce#23940]
**Is your feature request related to a problem? Please describe.**

Steps:

- Disable shipping on the store

- Put item(s) (which have no shipping, e.g. are virtual goods) in cart, go to checkout

- Press "Returning customer? Click here to login"

Results: You will now see the text "If you are a new customer, please proceed to the Billing & Shipping section." There is no such section. There is only a "Billing details" section.

**Describe the solution you'd like**
If there is no shipping section on the checkout (e.g. shipping is disabled, or all goods in the cart are virtual), then there should be no mention of a non-existent "Shipping section".

**Comment by kloon** [comment]
Hi, thanks for the suggestion. I see there is already a PR opened with a fix for this so closing the issue and we will review the PR for inclusion in a future release.
