### ISSUE TITLE
Status Tool to update the database does not perform any action

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#23946]
**Describe the bug**
In WooCommerce > Status > Tools there is a tool to update the WooCommerce database.

This triggers the following action:
https://github.com/woocommerce/woocommerce/blob/3.6.4/includes/api/v2/class-wc-rest-system-status-tools-v2-controller.php#L532

Since version 3.6 we no longer use the background processor for updating the database, so this doesn't trigger any action.

In support we've come across quite a few sites where the DB version is lower then the WooCommerce version, but no update notification is shown. Sometimes these updates are hidden by plugin/theme code, but other times the notification is somehow missed.
It doesn't get triggered to show again unless there is a new WooCommerce update detected or the WooCommerce plugin is deactivated and reactivated again.

**Expected behavior**
In cases where the update button doesn't show, it's useful to have a tool available to force the update to run. At the very least it should run the same action that is run when clicking the update button.

We used to be able to trigger an update by visiting the URL: `https://domain.test/wp-admin/admin.php?page=wc-settings&do_update_woocommerce=true`
However this now requires a nonce. I would expect the tool to run a similar action like visiting this URL used to run.

**Comment by claudiosanches** [comment]
See #23966
