### ISSUE TITLE
get_attribute() only works on Simple Product, or if the attribute is being used as a variation

### ISSUE THREAD

**Issue by welbinator** [woocommerce/woocommerce#23942]
using get_attribute() to try and display attributes in the new order email, but it only works if:

1. The product is a Simple Product
OR
2. The product is a Variable product, AND "Use as Variable" is checked in the Attributes section

Is there something better than get_attribute() that will select the attribute even if it's not being used as a variation?

Or, is there a better way to include attribute information in the new order email that doesn't involve editing PHP files?

**Comment by kloon** [comment]
Perhaps post an example of the code you are using to display it? get_attribute accepts a parameter, so be sure to pass that when calling it.

Also there are no checks in place that would prevent attributes from being returned based on their product type. All the built-in product types have attribute support.

**Comment by rodrigoprimo** [comment]
Closing due to lack of feedback. If you are still experiencing this issue, please leave a comment with the information asked above, and we will take a look. Thanks.

**Comment by christiankungla** [comment]
I had the same problem.
It turns out I was checking the attribute on variation itself, but I should have checked the attribute on parent product.

```
$parent_id = $product->get_parent_id();

if( $parent_id > 0 && $parent_product = wc_get_product($parent_id) ) {
    if( $attr_color = $parent_product->get_attribute('pa_color) ) {
        echo 'Color: ' . $attr_color;
    }
}
```
