### ISSUE TITLE
Mauritanian ouguiya has old currency code

### ISSUE THREAD

**Issue by jpknz** [woocommerce/woocommerce#23943]
**Describe the bug**
`get_woocommerce_currencies()` will return MRO for the Mauritanian ouguiya. This currency and code was retired in 2017. The new Mauritanian ouguiya has a code of MRU.

See the below for confirmation
https://en.wikipedia.org/wiki/Mauritanian_ouguiya
![image](https://user-images.githubusercontent.com/36459775/59563554-a0fa4980-9033-11e9-8c8f-3742efe32858.png)

**Expected behavior**
MRU returned for Mauritanian ouguiya when `get_woocommerce_currencies()` called.

**Comment by kloon** [comment]
See #23950
