### ISSUE TITLE
In Email - Order notes field stripping out line breaks

### ISSUE THREAD

**Issue by adrien-robert** [woocommerce/woocommerce#23956]
Like on this bug reported in 2013: https://github.com/woocommerce/woocommerce/issues/3882, the issue is still there.

Is there a solution to keep line breaks from the textarea order notes (in the emails sent)?

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #23969.

**Comment by adrien-robert** [comment]
> Thank you for reporting this issue!
> 
> I'm closing the issue as it already has a PR, please continue the discussion over at #23969.

Thank you :)
