### ISSUE TITLE
Registration Form Validation: Show all error messages

### ISSUE THREAD

**Issue by EdithAllison** [woocommerce/woocommerce#23954]
**Is your feature request related to a problem? Please describe.**
The registration form on "My Account" currently only displays the 1st error message. If further fields are added to the form by a developer, this results in a frustrating error handling process. 

**Describe the solution you'd like**
Change the registration form error handling to match checkout and show all errors at once. 

**Describe alternatives you've considered**
Not really an alternative unless I want to build my own registration form. 

**Additional context**
Proposed solution:

File: woocommerce/includes/class-wc-form-handler.php 
Line 1070
```
if ( $validation_error->get_error_code() ) {
	throw new Exception( $validation_error->get_error_message() );
} 
```

Replace with

```
foreach ( $validation_error->get_error_messages() as $message ) {
	wc_add_notice( $message, 'error' );
}
```

Benefit would be that developers can then use the filter woocommerce_process_registration_errors to add errors to the error object & all errors are shown together at registration page.

**Comment by claudiosanches** [comment]
Thank you for suggesting this feature!

I'm closing the issue as it already has a PR, please continue the discussion over at #23968.
