### ISSUE TITLE
Apply coupon if specific product is in cart

### ISSUE THREAD

**Issue by RemonKoolen** [woocommerce/woocommerce#23976]
Hey everyone,

I have a question about coupons. I would like to add the function that if my customers have product A in the cart, an coupon will automatically apply to the rest of the products as well. It doesn't seem to work for some reason. 

So let's say i have product A, B & C, the discount would only apply when product A is in the cart. If I add B & C, the discount has to go on those item's as well. If I'd delete product A from the cart, the discount has to disappear as well.

Can anyone help me with this issue? Thanks in advance.

**Comment by kloon** [comment]
This is not something WooCommerce core support out of the box, perhaps search WordPress.org as I know there are extensions available there that allows you to achieve this https://wordpress.org/plugins/search/woocommerce+auto+coupon/
