### ISSUE TITLE
Grouped Products is not importing in Woocommerce with WP All Import 

### ISSUE THREAD

**Issue by pinchi4743** [woocommerce/woocommerce#23986]
I am trying to import Grouped products into woocommerce with child variation automatic but thats not work and there are not any options for doing this.

Its simple products sheet.
http://prntscr.com/o5jkwh

Its grouped products
http://prntscr.com/o5jl33

I also tried for combined the sheet but no solution so any one can help me in this.

**Comment by claudiosanches** [comment]
We don't support WP All Import, try our built in product importer, that will works just fine.
