### ISSUE TITLE
Criar nome de usuário pelo e-mail não funciona 

### ISSUE THREAD

**Issue by simead** [woocommerce/woocommerce#23995]
**Describe the bug**
Ação Quando uma conta for criada, gerar automaticamente um nome de usuário baseado no endereço de e-mail do cliente. Não está funcionando, ao ativar a opção o usuário e gerado sendo nome e sobre nome do cadastro também salvando o espaço.

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/52178934/60051099-9cbfd300-96a8-11e9-865b-28d05222dfc2.png)
![image](https://user-images.githubusercontent.com/52178934/60051150-bd882880-96a8-11e9-8b06-797e454282f0.png)

**Expected behavior**
Preciso que seja criado um usuário através do inicio do e-mail do cliente.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by rodrigoprimo** [comment]
I happen to understand Portuguese, but please from now on use only English when creating or commenting on issues as this is the only language that everyone on the WooCommerce core team speaks.

There is a problem in the string that describes what this feature does. This was fixed in #23911 and will be included in WC 3.7.0. You can see more information in the PR linked above, but basically the e-mail is used only if a name and last name are not provided.

**Comment by simead** [comment]
Right, But my problem that is creating space in the account user, I need to
add the name with over some without the space.

EX:
[image: image.png]


*Thalisson Henrique*

*S**IMEAD - Sistema Mercosul de Ensino a Distância*
*Fone: (41) 3029-2121 | e-mail: contato@simead.com.br
<contato@simead.com.br>*
Rua Carlos Razera, 286 - Vista Alegre, Curitiba, Paraná | CEP. 80810-310
www.simead.com.br / www.reciclacnh.com.br
 *Missão:* *Ser uma empresa de referência em cursos livres à distância,
trabalhando para oferecer a melhor formação e informação em cursos,
treinamentos e palestras.*



Em qua, 26 de jun de 2019 às 14:42, Rodrigo Primo <notifications@github.com>
escreveu:

**Comment by rodrigoprimo** [comment]
I'm sorry but I don't understand what you mean and the image provided as an example is not loading. Can you please elaborate and share the image again? Using the [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=) and providing the steps to reproduce the problem might help. Thanks.

**Comment by simead** [comment]
Would you have a code to put in fuction? I need the user name generated at
the checkout to be the beginning of the email from the user or cpf. Can you
help me ?


*Thalisson Henrique*

*S**IMEAD - Sistema Mercosul de Ensino a Distância*
*Fone: (41) 3029-2121 | e-mail: contato@simead.com.br
<contato@simead.com.br>*
Rua Carlos Razera, 286 - Vista Alegre, Curitiba, Paraná | CEP. 80810-310
www.simead.com.br / www.reciclacnh.com.br
 *Missão:* *Ser uma empresa de referência em cursos livres à distância,
trabalhando para oferecer a melhor formação e informação em cursos,
treinamentos e palestras.*



Em qua, 3 de jul de 2019 às 10:21, Rodrigo Primo <notifications@github.com>
escreveu:

**Comment by simead** [comment]
I'm using the latest version of woocommerce, I'm creating a user account on
the checkout page, using the function to create an automatic username. My
problem is that the name is counting space from the third name. when
created a registry with the name: *Thalisson Henrique Savi*o the user looks
like this: *thalissonhenrique savio*. This is too bad to introduce such a
user to our customers. Can you give me a personalization that I can put in
the function of my theme so that the user created by the checkout of
woorcommerce is the beginning of the email before the @?


*Thalisson Henrique*

*S**IMEAD - Sistema Mercosul de Ensino a Distância*
*Fone: (41) 3029-2121 | e-mail: contato@simead.com.br
<contato@simead.com.br>*
Rua Carlos Razera, 286 - Vista Alegre, Curitiba, Paraná | CEP. 80810-310
www.simead.com.br / www.reciclacnh.com.br
 *Missão:* *Ser uma empresa de referência em cursos livres à distância,
trabalhando para oferecer a melhor formação e informação em cursos,
treinamentos e palestras.*



Em seg, 15 de jul de 2019 às 10:36, contato simead <contato@simead.com.br>
escreveu:

**Comment by rodrigoprimo** [comment]
I'm sorry but I can't help as this is not a support portal. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/
