### ISSUE TITLE
Coupon tool tips need adjustment

### ISSUE THREAD

**Issue by LaurenaRehbein** [woocommerce/woocommerce#23994]
**Describe the bug**

The tool tips on the coupon settings screen, under "usage restrictions" for Products and Categories, currently specific that they apply to fixed discounts. They actually apply to fixed and percentage, and need to be updated. 

**To Reproduce**

1. Go to **WooCommerce > Add new coupon > Usage Restriction**
2. Hover over the `?` tool tips by each and see the misleading message. 

![https://cld.wthms.co/vGRkTK](https://cld.wthms.co/vGRkTK+)
Full Image: https://cld.wthms.co/vGRkTK+ 

**Expected behavior**

The check applies to fixed and percentage based discounts, not just fixed.

**Comment by rodrigoprimo** [comment]
I think you misunderstood the message, but please let me know if that is not the case or if you have suggestions on how we can make it more clear. The message in question is:

`Products that the coupon will be applied to, or that need to be in the cart in order for the "Fixed cart discount" to be applied.`

Both products and product categories restrictions apply to all types of discounts (percentage discount, fixed cart discount, and fixed product discount), but there is a difference in how they are applied depending on the discount type. If the discount type is percentage discount or fixed product discount, the "Products" field control the list of products that the coupon will be applied to. But if the discount type is fixed cart discount, the products listed in the field need to be present for the discount to be applied to the cart subtotal. I hope this clear things up.

Closing this issue for now, but leave a comment if I missed something and I will reopen it.
