### ISSUE TITLE
Product meta table not created. COLLATION 'utf8_general_ci' is not valid for CHARACTER SET 'utf8mb4'

### ISSUE THREAD

**Issue by agaleski** [woocommerce/woocommerce#24012]
**Describe the bug**
When running the db update via cli after updating WC from 3.5.x to 3.6.4 I get for each multisite blog a DB error like this:

```
WordPress errore sul database COLLATION 'utf8_general_ci' is not valid for CHARACTER SET 'utf8mb4' per la query 
CREATE TABLE wp_5YGEptrH_4_wc_product_meta_lookup (
  `product_id` bigint(20) NOT NULL,
  `sku` varchar(100) NULL default '',
  `virtual` tinyint(1) NULL default 0,
  `downloadable` tinyint(1) NULL default 0,
  `min_price` decimal(10,2) NULL default NULL,
  `max_price` decimal(10,2) NULL default NULL,
  `onsale` tinyint(1) NULL default 0,
  `stock_quantity` double NULL default NULL,
  `stock_status` varchar(100) NULL default 'instock',
  `rating_count` bigint(20) NULL default 0,
  `average_rating` decimal(3,2) NULL default 0.00,
  `total_sales` bigint(20) NULL default 0,
  PRIMARY KEY  (`product_id`),
  KEY `virtual` (`virtual`),
  KEY `downloadable` (`downloadable`),
  KEY `stock_status` (`stock_status`),
  KEY `stock_quantity` (`stock_quantity`),
  KEY `onsale` (`onsale`),
  KEY min_max_price (`min_price`, `max_price`)
  ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8_general_ci fatta da dbDelta
```

**To Reproduce**
1. Use AWS Aurora MySQL as Database
2. Install WP & WC 3.5.3
3. Update to WC 3.6.4
4. Run cli command "wp wc update"

**Screenshots**
![Screenshot 2019-06-26 at 16 21 15](https://user-images.githubusercontent.com/5888843/60187812-8774b100-982e-11e9-83a0-545eef2446ee.png)

**Expected behavior**
Creating the product meta lookup table correctly OR not claiming to have successfully updated the DB and raising the DB version without successful update.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by agaleski** [comment]
I fixed the problem myself for the moment like this:
```
CREATE TABLE wp_5YGEptrH_wc_product_meta_lookup (   `product_id` bigint(20) NOT NULL,   `sku` varchar(100) NULL default '',   `virtual` tinyint(1) NULL default 0,   `downloadable` tinyint(1) NULL default 0,   `min_price` decimal(10,2) NULL default NULL,   `max_price` decimal(10,2) NULL default NULL,   `onsale` tinyint(1) NULL default 0,   `stock_quantity` double NULL default NULL,   `stock_status` varchar(100) NULL default 'instock',   `rating_count` bigint(20) NULL default 0,   `average_rating` decimal(3,2) NULL default 0.00,   `total_sales` bigint(20) NULL default 0,   PRIMARY KEY  (`product_id`),   KEY `virtual` (`virtual`),   KEY `downloadable` (`downloadable`),   KEY `stock_status` (`stock_status`),   KEY `stock_quantity` (`stock_quantity`),   KEY `onsale` (`onsale`),   KEY min_max_price (`min_price`, `max_price`)   ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;
```

**Comment by claudiosanches** [comment]
We don't pick any COLLATION, this comes from `$wpdb->get_charset_collate()`, that grabs your COLLATION settings for your whole WordPress installation. See:

https://github.com/woocommerce/woocommerce/blob/c04f7b79f972ee854e5f5d726eb78ac04a726b32/includes/class-wc-install.php#L687-L696

So sounds like an issue with CLI and WP.

I'll close, since doesn't like an issue on WooCommerce, and this seems to come from WP.
