### ISSUE TITLE
On creating order from Back-end, its is placing order with more quantity then product's available stock with back orders disabled

### ISSUE THREAD

**Issue by garimapathak1** [woocommerce/woocommerce#24017]
**Describe the bug**
Suppose the product's stock is 10 and backorders are not allowed. When we create order from back-end we are able to create order with more that 10 stock and it is making stock negative.
**To Reproduce**
1. Go to 'WooCommerce => Orders =>Add new"
2. Click on add item => Add product and add any product with quantity more than available.
3. Order will get placed and stock will goes to negative.

**Screenshots**
1. product stock :- ![product](https://user-images.githubusercontent.com/36501066/60256191-b2bed500-98ee-11e9-9db9-f12a5a62a392.png)

2. create order ;- 
![order](https://user-images.githubusercontent.com/36501066/60256255-cff3a380-98ee-11e9-8bf6-2cec9e1b6d77.png)

3. Check quantity of product :- 
![stock](https://user-images.githubusercontent.com/36501066/60256285-deda5600-98ee-11e9-91bd-9213cc97d939.png)

**Expected behavior**
Order must not get placed from back-end

**WordPress Environment**
![status](https://user-images.githubusercontent.com/36501066/60256315-eb5eae80-98ee-11e9-8776-0443d3140597.png)

**Comment by claudiosanches** [comment]
This does not look like a bug, it actually allows the sale, since it is being done by a store manager, who must have control in the stock already.
Also this allows ordering products before have stock, I have seen some stores using it as a feature.

**Comment by yash-webkul** [comment]
Yes I agree that store manager have full control on the store so he can increase the stock manually but i have a doubt in this, If admin wants to change the stock then he can also do this manually then why the stock is decreasing anyway on creating order from backend?
