### ISSUE TITLE
Document Moved When Creating Product REST API

### ISSUE THREAD

**Issue by jmawebtech** [woocommerce/woocommerce#24013]
**Describe the bug**
I use .NET 4.61. When I create a product using the REST API, I receive this content:

<head><title>Document Moved</title></head>
<body><h1>Object Moved</h1>This document may be found <a HREF="https://1106-7916.el-alt.com/wp-json/wc/v2/products/410">here</a></body>

The JSON soon follows.

**To Reproduce**

Here is the request and response:

POST https://1106-7916.el-alt.com/wp-json/wc/v2/products?consumer_key=X&consumer_secret=X HTTP/1.1
Accept: application/json
Content-Type: application/json
User-Agent: JMA Web Technologies
Authorization: Basic 
Host: 1106-7916.el-alt.com
Content-Length: 294
Expect: 100-continue
Connection: Keep-Alive

{"attributes":[{"name":"Color","visible":true,"variation":true,"options":["Red","Blue","Green","Orange"]},{"name":"Size","visible":true,"variation":true,"options":["S","M","L"]}],"title":"FooFoo","sku":"TestCreateProductWoo1026","description":"Test","categories":[],"tags":[],"type":"variable"}

HTTP/1.1 201 Created
Cache-Control: no-cache, must-revalidate, max-age=0
Allow: GET, POST
Content-Length: 2352
Content-Type: text/html; charset=UTF-8
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Location: https://1106-7916.el-alt.com/wp-json/wc/v2/products/410
Server: Microsoft-IIS/8.5
X-Robots-Tag: noindex
Link: <https://1106-7916.el-alt.com/wp-json/>; rel="https://api.w.org/"
X-Content-Type-Options: nosniff
Access-Control-Expose-Headers: X-WP-Total, X-WP-TotalPages
Access-Control-Allow-Headers: Authorization, Content-Type
X-Powered-By: ASP.NET
Set-Cookie: ARRAffinity=e1df2ec63e1e05c731da1ac5e62c4aac114186fa59266ed8082c4127c693acae;Path=/;Domain=1106-7916.el-alt.com
Set-Cookie: WAWebSiteSID=98f57a86c6474e31af0b7c1e6ac3d781; Path=/; HttpOnly
Date: Wed, 26 Jun 2019 14:38:48 GMT

<head><title>Document Moved</title></head>
<body><h1>Object Moved</h1>This document may be found <a HREF="https://1106-7916.el-alt.com/wp-json/wc/v2/products/410">here</a></body>{"id":410,"name":"Product","slug":"product","permalink":"https:\/\/1106-7916.el-alt.com\/product\/product\/","date_created":"2019-06-26T10:38:48","date_created_gmt":"2019-06-26T14:38:48","date_modified":"2019-06-26T10:38:48","date_modified_gmt":"2019-06-26T14:38:48","type":"variable","status":"publish","featured":false,"catalog_visibility":"visible","description":"Test","short_description":"","sku":"TestCreateProductWoo1026","price":"","regular_price":"","sale_price":"","date_on_sale_from":null,"date_on_sale_from_gmt":null,"date_on_sale_to":null,"date_on_sale_to_gmt":null,"price_html":"","on_sale":false,"purchasable":false,"total_sales":0,"virtual":false,"downloadable":false,"downloads":[],"download_limit":-1,"download_expiry":-1,"external_url":"","button_text":"","tax_status":"taxable","tax_class":"","manage_stock":false,"stock_quantity":null,"in_stock":false,"backorders":"no","backorders_allowed":false,"backordered":false,"sold_individually":false,"weight":"","dimensions":{"length":"","width":"","height":""},"shipping_required":true,"shipping_taxable":true,"shipping_class":"","shipping_class_id":0,"reviews_allowed":true,"average_rating":"0","rating_count":0,"related_ids":[113],"upsell_ids":[],"cross_sell_ids":[],"parent_id":0,"purchase_note":"","categories":[{"id":36,"name":"Uncategorized","slug":"uncategorized"}],"tags":[],"images":[{"id":0,"date_created":"2019-06-26T06:38:49","date_created_gmt":"2019-06-26T14:38:49","date_modified":"2019-06-26T06:38:49","date_modified_gmt":"2019-06-26T14:38:49","src":"https:\/\/1106-7916.el-alt.com\/wp-content\/plugins\/woocommerce\/assets\/images\/placeholder.png","name":"Placeholder","alt":"Placeholder","position":0}],"attributes":[{"id":0,"name":"Color","position":0,"visible":true,"variation":true,"options":["Red","Blue","Green","Orange"]},{"id":0,"name":"Size","position":0,"visible":true,"variation":true,"options":["S","M","L"]}],"default_attributes":[],"variations":[],"grouped_products":[],"menu_order":0,"meta_data":[],"_links":{"self":[{"href":"https:\/\/1106-7916.el-alt.com\/wp-json\/wc\/v2\/products\/410"}],"collection":[{"href":"https:\/\/1106-7916.el-alt.com\/wp-json\/wc\/v2\/products"}]}}

**Screenshots**

**Expected behavior**
I expect to only see the JSON of the created product. I cannot parse the JSON, if I have HTML content.

**Isolating the problem (mark completed items with an [x]):**
- [ X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

https://1106-7916.el-alt.com/wc-api/v3

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by claudiosanches** [comment]
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. I tried reproduce using the steps you provided and it appeared to work correctly.

We based our REST API on WP REST API, and we don't try change locations or do any redirect like that, maybe it's some 3rd party plugin, or even the REST API library that you are using, maybe sending some header or something that doesn't work well for WP, and also sometimes issues like that are related to the environment (like using Windows servers), but doesn't sound like an issue on WooCommerce.

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

Thanks!
