### ISSUE TITLE
Add PHP minimum version checks

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#24014]
WooCommerce should set the `Requires PHP` header in the main plugin file.

```php
 * Requires PHP: 5.6
```

By doing so, WordPress will prevent users upgrading if their version is unsupported:

![plugins_____local wordpress test_____wordpress_2019-06-26_11-39-15](https://user-images.githubusercontent.com/90977/60197428-403eee00-9837-11e9-8ff7-eb4f1ab52f2a.png)

If you try to activate a plugin with this header on an older version, WP will error out with a message:

> Error: Current PHP version does not meet minimum requirements for WooCommerce

In case of manual updates, we should also add a check in woocommerce.php - this check can either add a notice and return (do not load WC) or deactivate WooCommerce. By doing this, individual modules/packages won't have to do these checks or add notices themselves.

- [x] Add `Requires PHP` header
- [ ] Add version detection code in main plugin file which outputs a notice and prevents WooCommerce from loading

This follows on from https://github.com/woocommerce/woocommerce/pull/23975 and is needed for https://github.com/woocommerce/woocommerce/pull/23957 (https://github.com/woocommerce/woocommerce/pull/23957) has it's own checks but these could be generalised and moved to core code). Logging this here so it's not forgotten. cc @peterfabian @timmyc @woocommerce/proton

**Comment by rodrigoprimo** [comment]
There is already a PR that sets the `Requires PHP` header: #23924. But it doesn't address the issue of manual updates (cc @kloon).

**Comment by claudiosanches** [comment]
For what I can remember for our last team meeting, we should still allow people to install and use, if they can, just preventing certainly functionality of to work, until we don't bump our requirements to WP 5.2.

@kloon @peterfabian are we fully adopting 5.6? If so I can write this PR and start writing bug fixes already updating legacy code.

**Comment by kloon** [comment]
As Rodrigo pointed out, #23924 already adds the header. The thinking around "backward compatibility" is that if you manually install the plugin on a site that does not have 5.6 as the minimum PHP version it should not "break" but certain features not supported should just be disabled. IE blocks should not load and the new API package should also not load. In #23975 we added notices and those will be displayed prompting to update your PHP and/or WP versions.

**Comment by claudiosanches** [comment]
@kloon with the current changes in the REST API will require at least support for namespaces.

**Comment by mensmaximus** [comment]
Is it really worth the time to develop extra code for disabling features in WooCommerce if the minimum requirements for WordPress (PHP 5.6.20) is not met?

**Comment by claudiosanches** [comment]
Current versions of WordPress will handle it, so I'm closing it for now.
