### ISSUE TITLE
Slow REST, Simple Request to GET products

### ISSUE THREAD

**Issue by isuke01** [woocommerce/woocommerce#24022]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to get products. There is problem related to WooCommerce speed overall. +- **1500ms** to just /products? (production), **800ms** to just reach endpoint with return - `woocommerce_rest_cannot_view` (localhost) with fresh installed Wordpress + imported dummy data from WooCommerce plugins : ACF (only activated no fields) Theme : Storefront.

**Describe the solution you'd like**
I had same issue with Standard WP RESt, so I just make simple solution for just GET data using Custom file where i Load core WP with SHORTINIT,  etc base security stuff and my own queries - now i can Get data in less than 50ms, 30 on avg.

I tried similar thing with Woo but I understand there are things that may changed in DB so i Tried to load also only WooCommerce plugin (../woocommerce.php) + other things that caused errors. Then I tried to use `WC_Product_Query` to return products. But it does return empty object. I couldn't solve it. 

Would be great if there were a file that can be included and it load  give access to WooCommerce function to load products but fast not slow. For slow operation that can be "fake" like cart, user data etc I can use RES. But to just fast GET and display products, filters it cant be that slow. As it is 2019 users expect fast webs/apps that can be loaded super fast not super slow.
Or would be great to just get some tips how i can make it. I really dont want any 3rd part plugin on page to be loaded. I also understand problem with overload with plugins, but I dont want any of them.

**Describe alternatives you've considered**
I considered using some external services like Algolia or Elastic etc and sync products after any changes using hook product_updated or something ...  Like I did on https://lysimport.no/lyspaerer/ As you can see this is how things should work, not like click and wait 2 seconds. 

**Additional context**

This is thing I tried in this case, I know I over required some functions but yeh ... I  was doing tests, but no luck.
Also would be nice to have some nice solution for multilanugage support ;)

```
define('SHORTINIT', true);
define('DOING_AJAX', true);

$parse_uri = explode( 'wp-content', $_SERVER['SCRIPT_FILENAME'] ); // WPCS: XSS ok, sanitization ok.
require_once $parse_uri[0] . 'wp-load.php';

header('Content-Type: application/json');
header('Cache-Control: no-cache');
header('Pragma: no-cache');
header('Access-Control-Allow-Methods: GET');
//header('Access-Control-Allow-Origin: '.get_option('home'));
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Credentials: true' );

send_nosniff_header();


/*
|--------------------------------------------------------------------------
|  Error reporting
|--------------------------------------------------------------------------
*/
ini_set("display_errors", 1);
error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING);


/*
|--------------------------------------------------------------------------
|  Load necessary WP utils
|--------------------------------------------------------------------------
*/
load_security_utils();

require_once( ABSPATH . WPINC . '/l10n.php' );
//require_once( ABSPATH . 'wp-admin/includes/admin.php' );
require_once( ABSPATH . WPINC . '/formatting.php' );
require_once( ABSPATH . WPINC . '/theme.php');
require_once( ABSPATH . WPINC . '/post.php' );
require_once( ABSPATH . WPINC . '/general-template.php' );
require_once( ABSPATH . WPINC . '/category-template.php' );
require_once( ABSPATH . WPINC . '/link-template.php' );
 require_once( ABSPATH . WPINC . '/class-wp-widget.php' );
require_once( ABSPATH . WPINC . '/class-wp-query.php' );
require_once( ABSPATH . WPINC . '/taxonomy.php' );
require_once( ABSPATH . WPINC . '/rest-api.php' );
 require_once( ABSPATH . WPINC . '/class-wp-tax-query.php' );
 require_once( ABSPATH . WPINC . '/class-wp-session-tokens.php' );
 require_once( ABSPATH . WPINC . '/class-wp-user-meta-session-tokens.php' );
 require_once( ABSPATH . WPINC . '/class-wp-post.php' );
require_once( ABSPATH . WPINC . '/shortcodes.php' );
wp_functionality_constants();


require_once( ABSPATH . 'wp-content/plugins/woocommerce/woocommerce.php' );
wc()->frontend_includes();

/*
|--------------------------------------------------------------------------
|  Security utils - to get user cookies if logged etc
|--------------------------------------------------------------------------
*/
function load_security_utils() {
    require_once( ABSPATH . WPINC . '/pluggable.php' );
    require_once( ABSPATH . WPINC . '/capabilities.php' );
    require_once( ABSPATH . WPINC . '/user.php' ); 
    require_once( ABSPATH . WPINC . '/meta.php' );
    require_once( ABSPATH . WPINC . '/post.php');

    require_once( ABSPATH . WPINC . '/class-wp-user.php' );
    require_once( ABSPATH . WPINC . '/class-wp-roles.php' );
    require_once( ABSPATH . WPINC . '/class-wp-role.php' );
    wp_cookie_constants();
}

$product_id = 51;
$args = [
    'limit' => 10,
];
$factory = new WC_Product_Factory();
$wcquery = new WC_Product_Query($args);

$response = [
    'fa' => new WC_Product_Factory(),
    'woo' => $wcquery,
    'woo2' => $factory->get_product(51),
 
];


echo json_encode($response);
```

Or maybe I should use some different thing like Magento, Persta etc ? Im really under the wall, Im fighting with this issue like slow Woo on pages for ages, it works good in synthetic bench  but after some time it just dying. :/

**Comment by claudiosanches** [comment]
Hi there. GitHub is primarily for reporting bugs and is not a support forum. We don’t support custom development here. You could ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce

> I had same issue with Standard WP RESt, so I just make simple solution for just GET data using Custom file where i Load core WP with SHORTINIT, etc base security stuff and my own queries - now i can Get data in less than 50ms, 30 on avg.

WooCommerce REST API is created using WP REST API as base, it's almost the same code, just extending.

> I tried similar thing with Woo but I understand there are things that may changed in DB so i Tried to load also only WooCommerce plugin (../woocommerce.php) + other things that caused errors. Then I tried to use WC_Product_Query to return products. But it does return empty object. I couldn't solve it.

For your code sample, seems like you are doing everything custom, we don't have any function to load all things like you want, because `WC_Product_Query` expects to have everything available already.

> Would be great if there were a file that can be included and it load give access to WooCommerce function to load products but fast not slow. For slow operation that can be "fake" like cart, user data etc I can use RES. But to just fast GET and display products, filters it cant be that slow. As it is 2019 users expect fast webs/apps that can be loaded super fast not super slow.

Yes, I agree, still for what you are describing, sounds like that you should use cache on your side, like getting products once, then save on cache to make your app faster.

Also you can improve those changing the authentication methods for your own, trying to save on cache, or something to speed it up.

But about your custom code, sorry, this is out of our scope.

**Comment by isuke01** [comment]
Hey, Thanks for replay

> WooCommerce REST API is created using WP REST API as base, it's almost the same code, just extending.

Yes the problem with Woo I think is, it uses standard WP REST API which is super slow ;/

> Yes, I agree, still for what you are describing, sounds like that you should use cache on your side, like getting products once, then save on cache to make your app faster.

Probably I end up make own Product DB table which contains all Product's data or some services like  I mention before.  Just small question, hook for update my cache. `woocommerce_update_product ` should do the job? Or should I use some other ?

Thanks.

**Comment by claudiosanches** [comment]
The hooks inside CRUD should works just fine for those, we do almost the same.
