### ISSUE TITLE
Store categories not working

### ISSUE THREAD

**Issue by lincolnboxdotcom** [woocommerce/woocommerce#24038]
Store categories on wordpress woo commerce app not working. Display error, all the items are in the correct categories, when visiting the website all items show in every category. Categories are set to "display products" setting, made extra pages for the categories and made them a child page under parent page shop.

**Comment by kloon** [comment]
Please attach the system status report and go through the debugging steps as outlined when you [opened the issue](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=). Without that info we cannot really assist you.

I will leave this issue open for a day or two to do some testing and provide the details required for us to asses if this is a bug or not.

In my tests now all products are displaying fine in their selected categories so this is likely a plugin/theme conflict.

**Comment by rodrigoprimo** [comment]
Closing due to lack of feedback. If you are still experiencing this issue, please leave a comment with the information asked above, and we will take a look. Thanks.

**Comment by lincolnboxdotcom** [comment]
Greetings,

I opened a new request 11 days ago with the requested in this previous
request. Here is the link
https://github.com/woocommerce/woocommerce/issues/24209

thanks
