### ISSUE TITLE
Woocommerce 3.6.4 - how to hide unavailable variations

### ISSUE THREAD

**Issue by ZanekShaw** [woocommerce/woocommerce#24039]
I'm using Woocommerce version 3.6.4.

I have set up my product attributes like this:
First - 1|2
Second - 1.1|1.2|1.3|2.1|2.2|2.3

I want it to display like this:
1 - 1.1|1.2|1.3
2 - 2.1|2.2|2.3
and have set up the product variations properly in the admin section.

The website is displaying them like this:
1 - 1.1|1.2|1.3|2.1|2.2|2.3
2 - 1.1|1.2|1.3|2.1|2.2|2.3

I have tried adding this to my themes function.php file with no luck.
```

function custom_wc_ajax_variation_threshold( $qty, $product ) {
    return 100;
}

add_filter( 'woocommerce_ajax_variation_threshold', 'custom_wc_ajax_variation_threshold', 10, 2 );

```
Can someone please help me

**Comment by claudiosanches** [comment]
Hi there. GitHub is primarily for reporting bugs and is not a support forum. We don’t support custom development here. You could ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce
