### ISSUE TITLE
PRODUCT SHOWING AS OUT OF STOCK WHEN THEY ARE IN STOCK

### ISSUE THREAD

**Issue by lisadonaldcreative** [woocommerce/woocommerce#24037]
TEMPORARY SOLUTION TO PRODUCTS THAT ARE IN STOCK BUT WHICH ARE SHOWING
 'OUT OF STOCK' ON WOOCOMMERCE

I have been having this problem for a while now. Solution i have found to work. 
Go into dashboard 
Products
Filter By Out of Stock
This will bring up a list of all products showing as out of stock in your store
Click on Quick Edit
Change all to the following:-
**Part 1**
Put a tick in manage stock and change quantity to 1000
click update
**Part 2**
click on quick edit again and remove the tick from the manage stock box
make sure that the 'in stock? box stated In Stock
Click update again

This still need to be remedied by woocommerce but this is definitely an easier solution than any others that i have found. The fact you can just do a quick filter once a week or even each morning means you can keep on top of it so your products don't show out of stock for too long hence it stops the loss of sales. Hope this helps people for now but please Woocommerce can you look into this issue. 
![WOOCOMMERCE SOLUTION TO OUT OF STOCK](https://user-images.githubusercontent.com/52375825/60396853-797ca400-9b3e-11e9-8f26-d07433d87e0b.JPG)
Regards Lisa

**Comment by kloon** [comment]
This has been addressed in other issues and we have made a wiki entry about this. It is due to the upgrade routine not running or completing, please see https://github.com/woocommerce/woocommerce/wiki/3.6.x-notes-FAQ#i-am-having-issues-sortingsearching-by-sku-price-after-the-update
