### ISSUE TITLE
Order product quantities do not sync to Shipstation when using a Refund

### ISSUE THREAD

**Issue by keeneyemedia** [woocommerce/woocommerce#24033]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create an order as "processing". Refresh Shipstation store connection to pull that order in.
<img width="1492" alt="Step 1" src="https://user-images.githubusercontent.com/882600/60357255-2c170000-99a1-11e9-8026-80f15e35672b.png">
<img width="1300" alt="Step 1 in SS" src="https://user-images.githubusercontent.com/882600/60357256-2c170000-99a1-11e9-9e38-6e1c9cfade6b.png">

2. Set the order to "pending", change the product line item quantity to something else, set back to "processing".
3. Refresh Shipstation and reload the Orders screen. The quantity will update with the new changed quantity.
<img width="1295" alt="Step 2 refresh ss qty 5" src="https://user-images.githubusercontent.com/882600/60357281-3cc77600-99a1-11e9-8826-3b16834ad4f6.png">
<img width="1493" alt="Step 2 set pending, change 5, set processing" src="https://user-images.githubusercontent.com/882600/60357282-3cc77600-99a1-11e9-9009-ff08b907cce9.png">

4. Create another order as "processing". Refresh Shipstation store connection to pull that order in.
<img width="1493" alt="Step 3 qty 7" src="https://user-images.githubusercontent.com/882600/60357360-726c5f00-99a1-11e9-8763-67f091385789.png">
<img width="1288" alt="Step 3 ss qty 7" src="https://user-images.githubusercontent.com/882600/60357361-726c5f00-99a1-11e9-9e43-55afb5b8ebf3.png">

5. Click "Refund", use the "quantity" field to change the product line item quantity and automatically calculate the refund. Click "Refund $XX".
6. Refresh Shipstation and reload the Orders screen. It still shows the old quantity, not the reduced quantity from the refund.
<img width="1496" alt="Step 4 refunded qty 1" src="https://user-images.githubusercontent.com/882600/60357435-a2b3fd80-99a1-11e9-8e99-f5383005805f.png">
<img width="1290" alt="Step 4 ss wrong qty" src="https://user-images.githubusercontent.com/882600/60357437-a2b3fd80-99a1-11e9-9672-e33c87d49d8e.png">

## Expected/actual behavior

Manually editing an orders line item quantity DOES update correctly in Shipstation.

Making any quantity changes using a "Refund" does NOT update correctly in Shipstation.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```

### WordPress Environment ###

WordPress address (URL): http://blank-woocommerce.local
Site address (URL): http://blank-woocommerce.local
WC Version: 3.7.0
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.14.0
PHP Version: 7.2.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.7.23
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 2.99MB
Database Data Size: 2.04MB
Database Index Size: 0.95MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.48MB + Index: 0.02MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 2
post: 2
product: 1
scheduled-action: 1
shop_order: 4
shop_order_refund: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce - ShipStation Integration: by WooCommerce – 4.1.28 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.7.0-dev

### Inactive Plugins (0) ###


### Must Use Plugins (1) ###

Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Nineteen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2019-06-28 15:53:01 +0000
Newest: 2019-06-28 15:53:01 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

```
</details>

**Comment by claudiosanches** [comment]
Hi there! GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal.

If you need technical support for Shipstation, please use the helpdesk instead: https://woocommerce.com/contact-us/
