### ISSUE TITLE
Separate order_downloads email template placement

### ISSUE THREAD

**Issue by aalkz** [woocommerce/woocommerce#24036]
**Is your feature request related to a problem? Please describe.**
I have to place the **Downloads** section *after* the **Order details** section in the "Order completed" email template for virtual products. I tried editing the `email-order-details.php` file, but I couldn't find a way to dissect the Downloads table apart from the Order details section. So I tried looking inside other templates, and found that nothing really could be done because this part is inside `/includes/class-wc-emails.php` 
https://github.com/woocommerce/woocommerce/blob/6b1d8fbb57d74a4afd4326db68a53862e4ce8c1a/includes/class-wc-emails.php#L187-L194

So the only way I got around this was literally swapping these lines around, and see if it changed the order of those sections... and it did!
```
add_action( 'woocommerce_email_order_details', array( $this, 'order_details' ), 10, 4 );
add_action( 'woocommerce_email_order_details', array( $this, 'order_downloads' ), 10, 4 );
```

But this is a core file inside `includes` so my workaround will be inevitably lost on the next update.

**Describe the solution you'd like**
A template for this part that makes this non dependent of the ordering of those `add_action` calls.

**Describe alternatives you've considered**
Maybe there's a hook I don't know how to use or something that doesn't require me to meddle with core files. If there is, I'd be very pleased if someone teaches me how :)

**Additional context**
Pedido = Order
Descargas = Downloads

![image](https://user-images.githubusercontent.com/6750582/60380147-38817400-9a06-11e9-9f56-692ee34c2183.png)

This is how it looks after tweaking  `class-wc-emails.php` as mentioned above:

![image](https://user-images.githubusercontent.com/6750582/60380186-e1c86a00-9a06-11e9-8ddb-1d8a51f559a3.png)

Thank you so much!

**Comment by malviyaritesh** [comment]
For this, one possible solution without modifying the core plugin files is to first remove the default hooked action and then add again with priority order you need.
Put following code (untested but should work) in your active child theme or somewhere accessible to WooCommerce:
```
// Remove default hook
remove_action( 'woocommerce_email_order_details', array( WC()->mailer(), 'order_downloads' ), 10, 4 );
// Add again with modified priority
add_action( 'woocommerce_email_order_details', array( WC()->mailer(), 'order_downloads' ), 10, 5 );
```

**Comment by kloon** [comment]
What @malviyaritesh suggests, this is doable within a theme/plugin using remove_action and add_action again with a different priority, that negates the need to make changes to the core plugin.

We have plans to redo the email system in the future which will make things more modular and easier to customize.
