### ISSUE TITLE
WooCommerce Dashboard widget display not showing correctly after addition of Subscription information

### ISSUE THREAD

**Issue by AmeliaBriscoe** [woocommerce/woocommerce#24045]
**Describe the bug**
https://woothemes.zendesk.com/agent/tickets/2142349

When viewing the Dashboard in larger screen sizes, where the dashboard shows with three or four columns, the WooCommerce widget is not displaying correctly.

**To Reproduce**
* Go to **Dashboard** in your WordPress admin
* Three Columns: Adjust the browser area to show three columns in the Dashboard area, and adjust the browser between 1500px and 1680px
* Four Columns: Adjust the browser area to show four columns in the Dashboard area, and adjust the browser between 1936px and 2191px

**Screenshots**
![Three Columns](https://user-images.githubusercontent.com/2174223/60463455-62999700-9c8f-11e9-89f2-3e2365168dec.png)

![Four Columns](https://user-images.githubusercontent.com/2174223/60463460-69280e80-9c8f-11e9-90cf-41de1669299c.png)

**Expected behavior**
The WooCommerce Dashboard widget should be showing aligned rows.

![three columns correct](https://user-images.githubusercontent.com/2174223/60463592-c4f29780-9c8f-11e9-9e58-3628e2a14c86.png)

![Four Columns Correct](https://user-images.githubusercontent.com/2174223/60463602-cb810f00-9c8f-11e9-8535-b4d0ce0d95be.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Browsers/OS**
Chrome: Version 75.0.3770.100 (Official Build) (64-bit)
Firefox: Version 67.0.4 (64-bit)
Safari: Version 12.1.1 (14607.2.6.1.1)
OS: macOS Mojave Version 10.14.5

**WordPress Environment**

WordPress address (URL): http://mywoowebsite.test/wp
Site address (URL): http://mywoowebsite.test
WC Version: 3.6.4
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.3.1 mod_ssl/2.2.34 OpenSSL/1.0.2o DAV/2 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.9 Perl/v5.24.0
PHP Version: 7.3.1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.60.0
OpenSSL/1.0.2o

SUHOSIN Installed: –
MySQL Version: 5.7.25
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.4
WC Database Prefix: wp_FRXp3EdyBatneQCq_
MaxMind GeoIP Database: ✔
Total Database Size: 6.53MB
Database Data Size: 4.08MB
Database Index Size: 2.45MB
wp_FRXp3EdyBatneQCq_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_FRXp3EdyBatneQCq_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_FRXp3EdyBatneQCq_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_FRXp3EdyBatneQCq_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_FRXp3EdyBatneQCq_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_FRXp3EdyBatneQCq_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB
wp_FRXp3EdyBatneQCq_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_FRXp3EdyBatneQCq_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_FRXp3EdyBatneQCq_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_FRXp3EdyBatneQCq_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_FRXp3EdyBatneQCq_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_FRXp3EdyBatneQCq_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_FRXp3EdyBatneQCq_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_FRXp3EdyBatneQCq_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_FRXp3EdyBatneQCq_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB
wp_FRXp3EdyBatneQCq_automatewoo_customers: Data: 0.02MB + Index: 0.09MB
wp_FRXp3EdyBatneQCq_automatewoo_events: Data: 0.02MB + Index: 0.05MB
wp_FRXp3EdyBatneQCq_automatewoo_guests: Data: 0.02MB + Index: 0.06MB
wp_FRXp3EdyBatneQCq_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB
wp_FRXp3EdyBatneQCq_automatewoo_logs: Data: 0.02MB + Index: 0.05MB
wp_FRXp3EdyBatneQCq_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB
wp_FRXp3EdyBatneQCq_automatewoo_queue: Data: 0.02MB + Index: 0.05MB
wp_FRXp3EdyBatneQCq_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB
wp_FRXp3EdyBatneQCq_automatewoo_unsubscribes: Data: 0.02MB + Index: 0.05MB
wp_FRXp3EdyBatneQCq_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_FRXp3EdyBatneQCq_comments: Data: 0.22MB + Index: 0.38MB
wp_FRXp3EdyBatneQCq_links: Data: 0.02MB + Index: 0.02MB
wp_FRXp3EdyBatneQCq_options: Data: 1.03MB + Index: 0.05MB
wp_FRXp3EdyBatneQCq_pimwick_gift_card: Data: 0.02MB + Index: 0.02MB
wp_FRXp3EdyBatneQCq_pimwick_gift_card_activity: Data: 0.02MB + Index: 0.02MB
wp_FRXp3EdyBatneQCq_postmeta: Data: 1.52MB + Index: 0.30MB
wp_FRXp3EdyBatneQCq_posts: Data: 0.33MB + Index: 0.14MB
wp_FRXp3EdyBatneQCq_smush_dir_images: Data: 0.02MB + Index: 0.03MB
wp_FRXp3EdyBatneQCq_termmeta: Data: 0.02MB + Index: 0.03MB
wp_FRXp3EdyBatneQCq_terms: Data: 0.02MB + Index: 0.03MB
wp_FRXp3EdyBatneQCq_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_FRXp3EdyBatneQCq_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_FRXp3EdyBatneQCq_usermeta: Data: 0.05MB + Index: 0.03MB
wp_FRXp3EdyBatneQCq_users: Data: 0.02MB + Index: 0.05MB
wp_FRXp3EdyBatneQCq_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB
wp_FRXp3EdyBatneQCq_wc_admin_notes: Data: 0.02MB + Index: 0.00MB
wp_FRXp3EdyBatneQCq_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB
wp_FRXp3EdyBatneQCq_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB
wp_FRXp3EdyBatneQCq_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_FRXp3EdyBatneQCq_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB
wp_FRXp3EdyBatneQCq_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB
wp_FRXp3EdyBatneQCq_wc_order_stats: Data: 0.02MB + Index: 0.05MB
wp_FRXp3EdyBatneQCq_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB
wp_FRXp3EdyBatneQCq_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_FRXp3EdyBatneQCq_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 39
aw_workflow: 3
customize_changeset: 2
nav_menu_item: 6
page: 15
post: 2
product: 9
product_variation: 24
revision: 9
scheduled-action: 454
shop_coupon: 1
shop_order: 17
shop_subscription: 8
wc_membership_plan: 1
wc_user_membership: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (25) ###

Atomic Blocks - Gutenberg Blocks Collection: by atomicblocks – 2.0
AutomateWoo - Subscriptions Add-on: by Prospress Inc. – 1.0.1 – Not tested with the active version of WooCommerce
AutomateWoo: by Prospress – 4.5.5
Block Gallery: by GoDaddy – 1.1.6
Classic Editor: by WordPress Contributors – 1.5
CoBlocks: by GoDaddy – 1.11.0
Genesis Connect for WooCommerce: by StudioPress – 1.0 – Not tested with the active version of WooCommerce
Genesis eNews Extended: by Brandon Kraft – 2.1.1
Jetpack by WordPress.com: by Automattic – 7.4.1
Simple Social Icons: by StudioPress – 3.0.1
User Switching: by John Blackbourn & contributors – 1.5.1
WooCommerce Admin: by WooCommerce – 0.14.0
WooCommerce All Products For Subscriptions: by SomewhereWarm – 2.2.5
WooCommerce Stripe Gateway: by WooCommerce – 4.2.2
WooCommerce Memberships: by SkyVerge – 1.13.1
WooCommerce One Page Checkout: by Prospress Inc. – 1.6.0 – Not tested with the active version of WooCommerce
WooCommerce Product Add-ons: by WooCommerce – 3.0.11
WooCommerce Services: by Automattic – 1.21.0
WooCommerce Subscriptions - Preserve Billing Schedule: by Prospress Inc. – 1.0.0 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions Restrict Product: by Prospress Inc. – 1.0.2 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by Prospress Inc. – 2.5.6
WooCommerce: by Automattic – 3.6.4
WP Crontrol: by John Blackbourn & crontributors – 1.7.1
Smush: by WPMU DEV – 3.2.1
WPForms Lite: by WPForms – 1.5.3.1

### Inactive Plugins (16) ###

AutomateWoo - Birthdays Add-on: by Prospress – 1.0.0 – Not tested with the active version of WooCommerce
Better WordPress Minify: by Khang Minh – 1.3.3
Facebook for WooCommerce: by Facebook – 1.9.15 – Not tested with the active version of WooCommerce
Health Check & Troubleshooting: by The WordPress.org community – 1.3.2
Really Simple SSL: by Rogier Lankhorst
Mark Wolters – 3.2.2

Say What?: by Lee Willis – 1.9.1
Sensei LMS: by Automattic – 2.1.2
Spam Destroyer: by Ryan Hellyer – 2.1.3
WCS Allow Synchronized Products to Renew Early: by Prospress Inc. – 1.0.0 – Not tested with the active version of WooCommerce
WooCommerce Customer History: by Brian Richards – 1.2.1 – Not tested with the active version of WooCommerce
WooCommerce Name Your Price: by Kathy Darling – 2.9.5
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.2.5
WooCommerce Subscriptions - Custom Price String: by Prospress Inc. – 1.0.1 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions - Delete Cancel Subscription Confirmation: by Prospress Inc. – 1.0 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions - Skip Pending Cancel: by Prospress Inc. – 1.0.0 – Not tested with the active version of WooCommerce
WP Mail Logging: by Christian Zöller – 1.9.1

### Must Use Plugins (2) ###

Disable plugins when doing local dev: by Mark Jaquith – 0.1
register-theme-directory.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
pw gift card (pw-gift-card)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #21 - /shop/
Cart: #22 - /cart/
Checkout: #23 - /checkout/
My account: #24 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Genesis Sample
Version: 2.10.0
Author URL: https://www.studiopress.com/
Child Theme: ✔
Parent Theme Name: Genesis
Parent Theme Version: 3.0.1
Parent Theme Author URL: https://www.studiopress.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Memberships ###

Restriction mode:: Redirect to page
Public content:: –
Excluded from discounts:: –
Membership plans:: 1
Plant Guides:: Members: 1Access method: Product(s) purchaseAccess length: Unlimited Subscription: OptionalInstallment plan: No

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: http://mywoowebsite.test/wp
Subscription Statuses: trash: 2
auto-draft: 1
wc-active: 3
wc-on-hold: 1
wc-cancelled: 1

WooCommerce Account Connected: ❌ No
Custom Retry Rules: ✔ No
Custom Retry Rule Class: ✔ No
Custom Raw Retry Rule: ✔ No
Custom Retry Rule: ✔ No
Retries Migration Status: ✔ Completed
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: Australia — Victoria

### Subscriptions by Payment Gateway ###

Stripe: wc-active: 3
wc-cancelled: 1

### Payment Gateway Support ###

Stripe: products
refunds
tokenization
add_payment_method
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
pre-orders

Cash on delivery: products

### Action Scheduler ###

Complete: 310
Oldest: 2019-06-12 14:39:39 +1000
Newest: 2019-07-02 05:46:23 +1000

Pending: 6
Oldest: 2019-07-02 06:45:14 +1000
Newest: 2019-10-01 03:00:00 +1000

Canceled: 131
Oldest: 2019-06-12 15:25:43 +1000
Newest: 2019-09-25 06:36:03 +1000

In-progress: 0
Oldest: –
Newest: –

Failed: 7
Oldest: 2019-06-13 11:55:25 +1000
Newest: 2019-06-19 09:03:05 +1000

**Comment by rodrigoprimo** [comment]
@AmeliaBriscoe I'm not able to reproduce this when only WooCommerce core is active. My first guess is that this is a problem with the way WooCommerce Subscription is adding information to the WooCommerce Status widget. Could you please open an issue on their repository? If I miss something and you believe this is a WooCommerce core problem, please leave a comment and I will reopen this issue.
