### ISSUE TITLE
translation error

### ISSUE THREAD

**Issue by matheusmelo1** [woocommerce/woocommerce#24047]
in the wordpress panel and in my shop it is written "cupão" instead of "cupom" in portuguese brazil

**Comment by claudiosanches** [comment]
I can't find any `cupão` in https://translate.wordpress.org/projects/wp-plugins/woocommerce/dev/pt-br/default/?filters%5Bterm%5D=cup%C3%A3o&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

Also translations are not manitenind here in GitHub, so you should suggest new translations on translate.wordpress.org
