### ISSUE TITLE
A lot of pictures aren't visable anymore in my webshop. The main pictures of products are blank but also my logo in the head etc. Very weird and annoying. This is not good for doing bussiness as customers are leaving right away all the time now. Please do check as this must be fixes a.s.a.p. Thank you in advance for your support. Kind regards, René van Gestel. www.VIParts.nl

### ISSUE THREAD

**Issue by VIParts** [woocommerce/woocommerce#24049]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by claudiosanches** [comment]
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. When in fact there's no details of how to reproduce it, all the template is ignored, none of the data that we need to test and check if is a bug is not here.

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

Thanks!
