### ISSUE TITLE
Suggested fix displaying product quantities

### ISSUE THREAD

**Issue by RossMitchellOZ** [woocommerce/woocommerce#24053]
In the Checkout page (and other places), the items in the cart are listed in the form: “Description x quantity”, such as “Thingie x 3”. In borderline situations with long descriptions, line breaks can give misleading displays like:

> Thingie x
> 3

This is untidy at the least, and possibly confusing.  In some contexts the “x” would be a control to delete that item, but not here.

My fix is to make the space between the “x” and the number a non breaking space.
A filter like this does it:

`add_filter('woocommerce_order_item_quantity_html', 'abc_qty_fixup');`
`add_filter('woocommerce_checkout_cart_item_quantity', 'abc_qty_fixup');`
`function  abc_qty_fixup($str) {`
`   return str_replace("&times; ","&times;&nbsp;",$str);`
`}`

However I feel that the correct fix is to change the strings in the woocommerce core plugin files, which include:

`woocommerce/templates/order/order-details-item.php:`
`woocommerce/templates/checkout/form-pay.php: `
`woocommerce/templates/checkout/review-order.php:`

I notice that “esc_html(” is only used on the quantity field in one of these three places, presumably there is a reason for this.

**Comment by vedanshujain** [comment]
Using `&nbsp;` instead of space does makes sense to me, so that `x 3` does not break by word wrap. 

Would you be able to create a PR so that other people can chime in as well? I will add `help wanted` tag anyway so see of anyone else wanna help.

**Comment by claudiosanches** [comment]
Thank you for suggesting this feature!

I'm closing the issue as it already has a PR, please continue the discussion over at #24311.
