### ISSUE TITLE
WC_Data::get_meta filter should out of IF statement

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#24062]
When using WC_Data::get_meta, if the searched meta doesn't exist yet it's not possible to filter the output because the `apply_filter` call is inside `if ( ! empty( $array_keys ) ) {`

https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-data.php#L326

Wouldn't it better to have this:

`if ( 'view' === $context ) {
	$value = apply_filters( $this->get_hook_prefix() . $key, $value, $this );
}`

outside/after the IF statement, so that it's possible to filter the output even for meta that was still not set on the database?

**Comment by vedanshujain** [comment]
This issue has a pull request. Lets move over the discussion there to https://github.com/woocommerce/woocommerce/pull/24066 .
