### ISSUE TITLE
Documentation wrong for setting up webhooks

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce#24063]
https://docs.woocommerce.com/document/stripe/#section-3 tells you how to set up webhooks in your Stripe console.

However, following these instructions gives an error. Stripe does not (presumably this changed since the documentation was written) allow you to not specify *which* webhooks you want. WooCommerce does not document which ones it supports. This means the user is likely to guess, or add them all (which will hurt performance).

**Comment by DavidAnderson684** [comment]
As someone who's coded Stripe webhooks, I'm also puzzled as to why WooCommerce doesn't ask for the shared key to be entered into the settings. But it was a while ago and perhaps I've forgotten something.

**Comment by claudiosanches** [comment]
Hi there! GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal.

If you need technical support for WooCommerce Stripe documentation, please use the helpdesk instead: https://woocommerce.com/contact-us/

I'll also CC the team responsible for that extension, so they can check this docs as well.
cc @woocommerce/extendables

**Comment by DavidAnderson684** [comment]
@claudiosanches This was not a request for support (I found my own solution), but a defect report for the documentation linked from the WooCommerce settings.
