### ISSUE TITLE
Variable products showing out of stock 

### ISSUE THREAD

**Issue by jzmwebdevelopment** [woocommerce/woocommerce#24072]
I am having an issue where my product is showing out of stock however all variations are enabled and have Manage stock selected.  Stock levels range between 1 to 5 

`
### WordPress Environment ###

WordPress address (URL): https://tinyturtles.co.nz
Site address (URL): https://tinyturtles.co.nz
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.13.6
PHP Version: 7.1.14-1+ubuntu16.04.1+deb.sury.org+1 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.31-MariaDB-1~xenial
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.4.5
WC Database Prefix: wpno_
Total Database Size: 1733.59MB
Database Data Size: 1563.42MB
Database Index Size: 170.17MB
wpno_woocommerce_sessions: Data: 338.44MB + Index: 8.71MB
wpno_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wpno_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wpno_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wpno_woocommerce_order_items: Data: 1.09MB + Index: 0.52MB
wpno_woocommerce_order_itemmeta: Data: 7.77MB + Index: 4.82MB
wpno_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wpno_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wpno_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wpno_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
wpno_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wpno_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wpno_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wpno_woocommerce_log: Data: 0.00MB + Index: 0.00MB
sib_model_contact: Data: 0.02MB + Index: 0.00MB
wpno_commentmeta: Data: 0.47MB + Index: 0.26MB
wpno_comments: Data: 3.79MB + Index: 1.48MB
wpno_duplicator_packages: Data: 0.02MB + Index: 0.02MB
wpno_links: Data: 0.00MB + Index: 0.00MB
wpno_mgmlp_folders: Data: 0.02MB + Index: 0.01MB
wpno_nf_objectmeta: Data: 0.01MB + Index: 0.00MB
wpno_nf_objects: Data: 0.00MB + Index: 0.00MB
wpno_nf_relationships: Data: 0.00MB + Index: 0.00MB
wpno_ninja_forms_fav_fields: Data: 0.02MB + Index: 0.00MB
wpno_ninja_forms_fields: Data: 0.01MB + Index: 0.00MB
wpno_options: Data: 7.58MB + Index: 0.43MB
wpno_postmeta: Data: 37.32MB + Index: 16.69MB
wpno_posts: Data: 5.75MB + Index: 1.64MB
wpno_revslider_css: Data: 0.13MB + Index: 0.00MB
wpno_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wpno_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wpno_revslider_sliders: Data: 0.14MB + Index: 0.00MB
wpno_revslider_slides: Data: 1.52MB + Index: 0.00MB
wpno_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wpno_sib_model_forms: Data: 0.02MB + Index: 0.00MB
wpno_sib_model_users: Data: 0.02MB + Index: 0.00MB
wpno_taxonomymeta: Data: 0.00MB + Index: 0.00MB
wpno_termmeta: Data: 0.57MB + Index: 0.37MB
wpno_terms: Data: 0.03MB + Index: 0.08MB
wpno_term_relationships: Data: 0.70MB + Index: 1.45MB
wpno_term_taxonomy: Data: 0.04MB + Index: 0.04MB
wpno_tm_taskmeta: Data: 0.02MB + Index: 0.03MB
wpno_tm_tasks: Data: 0.02MB + Index: 0.02MB
wpno_usermeta: Data: 4.70MB + Index: 1.83MB
wpno_users: Data: 0.17MB + Index: 0.20MB
wpno_vtprd_purchase_log: Data: 0.02MB + Index: 0.02MB
wpno_vtprd_purchase_log_product: Data: 0.02MB + Index: 0.02MB
wpno_vtprd_purchase_log_product_rule: Data: 0.02MB + Index: 0.02MB
wpno_wcpdf_invoice_number: Data: 0.08MB + Index: 0.00MB
wpno_wc_download_log: Data: 0.02MB + Index: 0.03MB
wpno_wc_points_rewards_user_points: Data: 0.14MB + Index: 0.19MB
wpno_wc_points_rewards_user_points_log: Data: 0.27MB + Index: 0.18MB
wpno_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wpno_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wpno_wsal_metadata: Data: 1.52MB + Index: 0.38MB
wpno_wsal_occurrences: Data: 0.11MB + Index: 0.11MB
wpno_wsal_options: Data: 0.02MB + Index: 0.00MB
wpno_yith_wcwl: Data: 0.01MB + Index: 0.01MB
wpno_yith_wcwl_lists: Data: 0.02MB + Index: 0.05MB
wpno_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wpno_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB
wpstg0_commentmeta: Data: 0.47MB + Index: 0.29MB
wpstg0_comments: Data: 3.70MB + Index: 1.63MB
wpstg0_duplicator_packages: Data: 0.02MB + Index: 0.02MB
wpstg0_links: Data: 0.00MB + Index: 0.00MB
wpstg0_mgmlp_folders: Data: 0.02MB + Index: 0.02MB
wpstg0_nf_objectmeta: Data: 0.01MB + Index: 0.00MB
wpstg0_nf_objects: Data: 0.00MB + Index: 0.00MB
wpstg0_nf_relationships: Data: 0.00MB + Index: 0.00MB
wpstg0_ninja_forms_fav_fields: Data: 0.02MB + Index: 0.00MB
wpstg0_ninja_forms_fields: Data: 0.01MB + Index: 0.00MB
wpstg0_options: Data: 5.71MB + Index: 0.37MB
wpstg0_postmeta: Data: 34.96MB + Index: 18.14MB
wpstg0_posts: Data: 5.37MB + Index: 1.53MB
wpstg0_revslider_css: Data: 0.02MB + Index: 0.00MB
wpstg0_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wpstg0_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wpstg0_revslider_sliders: Data: 0.02MB + Index: 0.00MB
wpstg0_revslider_slides: Data: 0.02MB + Index: 0.00MB
wpstg0_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wpstg0_sib_model_forms: Data: 0.02MB + Index: 0.00MB
wpstg0_sib_model_users: Data: 0.02MB + Index: 0.00MB
wpstg0_taxonomymeta: Data: 0.00MB + Index: 0.00MB
wpstg0_termmeta: Data: 0.57MB + Index: 0.42MB
wpstg0_terms: Data: 0.03MB + Index: 0.06MB
wpstg0_term_relationships: Data: 0.65MB + Index: 1.40MB
wpstg0_term_taxonomy: Data: 0.04MB + Index: 0.06MB
wpstg0_usermeta: Data: 3.25MB + Index: 2.02MB
wpstg0_users: Data: 0.17MB + Index: 0.14MB
wpstg0_vtprd_purchase_log: Data: 0.02MB + Index: 0.02MB
wpstg0_vtprd_purchase_log_product: Data: 0.02MB + Index: 0.02MB
wpstg0_vtprd_purchase_log_product_rule: Data: 0.02MB + Index: 0.02MB
wpstg0_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB
wpstg0_wc_download_log: Data: 0.02MB + Index: 0.03MB
wpstg0_wc_points_rewards_user_points: Data: 0.14MB + Index: 0.18MB
wpstg0_wc_points_rewards_user_points_log: Data: 0.26MB + Index: 0.16MB
wpstg0_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wpstg0_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wpstg0_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wpstg0_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wpstg0_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wpstg0_woocommerce_order_itemmeta: Data: 7.55MB + Index: 5.74MB
wpstg0_woocommerce_order_items: Data: 1.06MB + Index: 0.55MB
wpstg0_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wpstg0_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wpstg0_woocommerce_sessions: Data: 318.29MB + Index: 10.46MB
wpstg0_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wpstg0_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
wpstg0_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wpstg0_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wpstg0_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wpstg0_wsal_metadata: Data: 0.02MB + Index: 0.02MB
wpstg0_wsal_occurrences: Data: 0.02MB + Index: 0.02MB
wpstg0_wsal_options: Data: 0.02MB + Index: 0.00MB
wpstg0_yith_wcwl: Data: 0.01MB + Index: 0.01MB
wpstg0_yith_wcwl_lists: Data: 0.02MB + Index: 0.05MB
wpstg0_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wpstg0_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB
wpstg1_commentmeta: Data: 0.47MB + Index: 0.29MB
wpstg1_comments: Data: 3.70MB + Index: 1.63MB
wpstg1_duplicator_packages: Data: 0.02MB + Index: 0.02MB
wpstg1_links: Data: 0.00MB + Index: 0.00MB
wpstg1_mgmlp_folders: Data: 0.02MB + Index: 0.02MB
wpstg1_nf_objectmeta: Data: 0.01MB + Index: 0.00MB
wpstg1_nf_objects: Data: 0.00MB + Index: 0.00MB
wpstg1_nf_relationships: Data: 0.00MB + Index: 0.00MB
wpstg1_ninja_forms_fav_fields: Data: 0.02MB + Index: 0.00MB
wpstg1_ninja_forms_fields: Data: 0.01MB + Index: 0.00MB
wpstg1_options: Data: 5.71MB + Index: 0.36MB
wpstg1_postmeta: Data: 34.96MB + Index: 18.13MB
wpstg1_posts: Data: 5.37MB + Index: 1.53MB
wpstg1_revslider_css: Data: 0.02MB + Index: 0.00MB
wpstg1_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wpstg1_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wpstg1_revslider_sliders: Data: 0.02MB + Index: 0.00MB
wpstg1_revslider_slides: Data: 0.02MB + Index: 0.00MB
wpstg1_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wpstg1_sib_model_forms: Data: 0.02MB + Index: 0.00MB
wpstg1_sib_model_users: Data: 0.02MB + Index: 0.00MB
wpstg1_taxonomymeta: Data: 0.00MB + Index: 0.00MB
wpstg1_termmeta: Data: 0.57MB + Index: 0.42MB
wpstg1_terms: Data: 0.03MB + Index: 0.06MB
wpstg1_term_relationships: Data: 0.65MB + Index: 1.40MB
wpstg1_term_taxonomy: Data: 0.04MB + Index: 0.06MB
wpstg1_usermeta: Data: 3.26MB + Index: 2.02MB
wpstg1_users: Data: 0.17MB + Index: 0.14MB
wpstg1_vtprd_purchase_log: Data: 0.02MB + Index: 0.02MB
wpstg1_vtprd_purchase_log_product: Data: 0.02MB + Index: 0.02MB
wpstg1_vtprd_purchase_log_product_rule: Data: 0.02MB + Index: 0.02MB
wpstg1_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB
wpstg1_wc_download_log: Data: 0.02MB + Index: 0.03MB
wpstg1_wc_points_rewards_user_points: Data: 0.14MB + Index: 0.18MB
wpstg1_wc_points_rewards_user_points_log: Data: 0.26MB + Index: 0.16MB
wpstg1_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wpstg1_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wpstg1_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wpstg1_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wpstg1_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wpstg1_woocommerce_order_itemmeta: Data: 7.55MB + Index: 5.74MB
wpstg1_woocommerce_order_items: Data: 1.06MB + Index: 0.55MB
wpstg1_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wpstg1_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wpstg1_woocommerce_sessions: Data: 318.30MB + Index: 10.46MB
wpstg1_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wpstg1_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
wpstg1_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wpstg1_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wpstg1_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wpstg1_wsal_metadata: Data: 0.02MB + Index: 0.02MB
wpstg1_wsal_occurrences: Data: 0.02MB + Index: 0.02MB
wpstg1_wsal_options: Data: 0.02MB + Index: 0.00MB
wpstg1_yith_wcwl: Data: 0.01MB + Index: 0.01MB
wpstg1_yith_wcwl_lists: Data: 0.02MB + Index: 0.05MB
wpstg1_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wpstg1_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB
wpstg2_commentmeta: Data: 0.47MB + Index: 0.29MB
wpstg2_comments: Data: 3.70MB + Index: 1.64MB
wpstg2_duplicator_packages: Data: 0.02MB + Index: 0.02MB
wpstg2_links: Data: 0.00MB + Index: 0.00MB
wpstg2_mgmlp_folders: Data: 0.02MB + Index: 0.02MB
wpstg2_nf_objectmeta: Data: 0.01MB + Index: 0.00MB
wpstg2_nf_objects: Data: 0.00MB + Index: 0.00MB
wpstg2_nf_relationships: Data: 0.00MB + Index: 0.00MB
wpstg2_ninja_forms_fav_fields: Data: 0.02MB + Index: 0.00MB
wpstg2_ninja_forms_fields: Data: 0.01MB + Index: 0.00MB
wpstg2_options: Data: 5.96MB + Index: 0.36MB
wpstg2_postmeta: Data: 34.97MB + Index: 18.16MB
wpstg2_posts: Data: 5.37MB + Index: 1.53MB
wpstg2_revslider_css: Data: 0.02MB + Index: 0.00MB
wpstg2_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wpstg2_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wpstg2_revslider_sliders: Data: 0.02MB + Index: 0.00MB
wpstg2_revslider_slides: Data: 0.02MB + Index: 0.00MB
wpstg2_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wpstg2_sib_model_forms: Data: 0.02MB + Index: 0.00MB
wpstg2_sib_model_users: Data: 0.02MB + Index: 0.00MB
wpstg2_taxonomymeta: Data: 0.00MB + Index: 0.00MB
wpstg2_termmeta: Data: 0.57MB + Index: 0.42MB
wpstg2_terms: Data: 0.03MB + Index: 0.06MB
wpstg2_term_relationships: Data: 0.65MB + Index: 1.41MB
wpstg2_term_taxonomy: Data: 0.04MB + Index: 0.06MB
wpstg2_usermeta: Data: 3.27MB + Index: 2.02MB
wpstg2_users: Data: 0.17MB + Index: 0.14MB
wpstg2_vtprd_purchase_log: Data: 0.02MB + Index: 0.02MB
wpstg2_vtprd_purchase_log_product: Data: 0.02MB + Index: 0.02MB
wpstg2_vtprd_purchase_log_product_rule: Data: 0.02MB + Index: 0.02MB
wpstg2_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB
wpstg2_wc_download_log: Data: 0.02MB + Index: 0.03MB
wpstg2_wc_points_rewards_user_points: Data: 0.14MB + Index: 0.18MB
wpstg2_wc_points_rewards_user_points_log: Data: 0.26MB + Index: 0.16MB
wpstg2_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wpstg2_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wpstg2_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wpstg2_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wpstg2_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wpstg2_woocommerce_order_itemmeta: Data: 7.56MB + Index: 5.75MB
wpstg2_woocommerce_order_items: Data: 1.06MB + Index: 0.55MB
wpstg2_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wpstg2_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wpstg2_woocommerce_sessions: Data: 318.99MB + Index: 10.49MB
wpstg2_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wpstg2_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
wpstg2_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wpstg2_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wpstg2_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wpstg2_wsal_metadata: Data: 0.02MB + Index: 0.02MB
wpstg2_wsal_occurrences: Data: 0.02MB + Index: 0.02MB
wpstg2_wsal_options: Data: 0.02MB + Index: 0.00MB
wpstg2_yith_wcwl: Data: 0.01MB + Index: 0.01MB
wpstg2_yith_wcwl_lists: Data: 0.02MB + Index: 0.05MB
wpstg2_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wpstg2_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 4163
custom_css: 1
custom-css-js: 3
customize_changeset: 3
footer: 6
ftc_brand: 10
ftc_footer: 7
ftc_testimonial: 4
mc4wp-form: 1
mgmlp_media_folder: 49
nav_menu_item: 108
nf_sub: 120
page: 34
portfolio: 4
post: 8
product: 854
product_variation: 4060
revision: 481
scheduled-action: 1
shop_coupon: 888
shop_order: 4194
shop_order_refund: 13
woo_discount: 6
wpcf7_contact_form: 1
yith-wccos-ostatus: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (34) ###

Cache-Control: by Geeky Software – 2.2.3
CDN Enabler: by KeyCDN – 1.0.9
Contact Form 7: by Takayuki Miyoshi – 5.1.3
Duplicator: by Snap Creek – 1.3.14
Facebook for WooCommerce: by Facebook – 1.9.15 – Not tested with the active version of WooCommerce
Flexible Shipping: by WP Desk – 3.4.0
WPBakery Page Builder: by Michael M - WPBakery.com – 5.4.7
Maintenance Mode: by Lukas Juhas – 2.4.3
Mailchimp for WordPress: by ibericode – 4.5.2
SendinBlue Subscribe Form And WP SMTP: by SendinBlue – 2.9.5
Mailjet for WordPress: by Mailjet SAS – 5.1.1
Mega Main Menu: by MegaMain.com – 2.1.5
Order / Coupon / Subscription Export Import Plugin for WooCommerce: by Xadapter – 2.3.6 – Not tested with the active version of WooCommerce
Redux Framework: by Team Redux – 3.6.15
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.5.7
ThemeFTC: by ThemeFTC Team – 1.0.0
WC Hide Shipping Methods: by Rynaldo Stoltz – 1.3
Woo Discount Rules: by Flycart Technologies LLP – 1.7.16
Woocommerce Laybuy: by Carl Bowden
Larry Watene – 3.4.0 – Not tested with the active version of WooCommerce

WooCommerce Payment Express Gateway: by OPMC – 2.2 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.9
WooCommerce Hear About Us: by SiteOptimo – 1.5.2 – Not tested with the active version of WooCommerce
WooCommerce Custom Payment Gateway: by WPRuby – 1.2.0
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.2.14
WooCommerce Points and Rewards: by WooThemes – 1.5.13 – Not tested with the active version of WooCommerce
WooCommerce Smart Coupons: by WooThemes – 3.1.7 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.6.5
Yoast SEO: by Team Yoast – 11.5 – Not tested with the active version of WooCommerce
Envato Market: by Derek Herman – 1.0.0-RC2
WP-Optimize: by David Anderson
Ruhani Rabin
Team Updraft – 2.3.4

WP Staging Pro: by WP-Staging
René Hermenau – 2.8.4

WP-Sweep: by Lester 'GaMerZ' Chan – 1.1.0
YITH WooCommerce Compare: by YITH – 2.3.12
YITH WooCommerce Wishlist: by YITH – 2.2.11

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: NZD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: grouped (grouped)
external (external)
variable (variable)
simple (simple)

Taxonomies: Product Visibility: exclude-from-search (exclude-from-search)
exclude-from-catalog (exclude-from-catalog)
featured (featured)
featured (featured-2)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)
outofstock (outofstock)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #7458 - /shop/
Cart: #7454 - /shopping-cart/
Checkout: #7452 - /checkout/
My account: #7442 - /my-account/
Terms and conditions: #11986 - /terms-conditions/

### Theme ###

Name: Rango Child
Version: 1.2.1523585632
Author URL: https://wordpress.org/
Child Theme: ✔
Parent Theme Name: Rango
Parent Theme Version: 1.2.3
Parent Theme Author URL: https://wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: rango/woocommerce/archive-product.php
rango/woocommerce/cart/mini-cart.php version 3.3.0 is out of date. The core version is 3.5.0
rango/woocommerce/checkout/form-checkout.php
rango/woocommerce/content-product.php
rango/woocommerce/content-product_cat.php
rango/woocommerce/content-widget-product.php
rango-child/woocommerce/emails/email-footer.php
rango-child/woocommerce/emails/email-header.php
rango/woocommerce/global/quantity-input.php
rango/woocommerce/loop/add-to-cart.php
rango/woocommerce/loop/loop-end.php
rango/woocommerce/loop/loop-start.php
rango/woocommerce/loop/orderby.php
rango/woocommerce/loop/pagination.php
rango/woocommerce/myaccount/my-address.php
rango/woocommerce/single-product/add-to-cart/variable.php
rango/woocommerce/single-product/product-image.php
rango/woocommerce/single-product/product-thumbnails.php
rango/woocommerce/single-product/rating.php
rango/woocommerce/single-product/related.php
rango/woocommerce/single-product/tabs/tabs.php
rango/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

### Action Scheduler ###

Complete: 0
Oldest: –
Newest: –

Pending: 1
Oldest: 2019-07-01 06:42:18 +0000
Newest: 2019-07-01 06:42:18 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by rodrigoprimo** [comment]
Hi there!

GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/

If you believe you found a WooCommerce bug, please open another issue following the [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=) and provide clear steps to reproduce the problem on a clean WooCommerce install. Thanks.
