### ISSUE TITLE
Product import using csv gets stuck with no errors.

### ISSUE THREAD

**Issue by adititipnis** [woocommerce/woocommerce#24074]
**Describe the bug**
I am trying to import a few products to my site using a comma delimited csv. It's only 13 products but every time it uploads a few products and then stops working. The utility is still running but the if i check all products in another window, nothing is being added. The last product added was  minutes ago. Also, there are no errors in the logs.
**To Reproduce**
1. Upload this csv to product import. 
https://docs.google.com/spreadsheets/d/1Py7NRRwOCreMixxlsmuSMc6UaNMeCLcycQwPEcLMO90/edit?usp=sharing
2. map images column to images field
3. start upload

**Screenshots**

**Expected behavior**
All the products in the sheet need to be updated. Also, the progress should be shown precisely on the uploading page.

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```

WordPress address (URL): |   | http://pattasutra.com
-- | -- | --
Site address (URL): |   | http://pattasutra.com
WooCommerce version: |   | 3.6.4
Log directory writable: |   | /home/digit708/public_html/pattasutra.com/wp-content/uploads/wc-logs/
WordPress version: |   | 5.2.2
WordPress multisite: |   | –
WordPress memory limit: |   | 768 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –


```
</details>

**Comment by claudiosanches** [comment]
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. I tried your CSV and it appeared to work correctly.

It could be that your images are heavy in high resolution, so is demanding too much for your server to process it, probably in your PHP error log is showing errors like "PHP Fatal error:  Allowed memory size of xxxxxxxx bytes exhausted (tried to allocate xxxxxxx bytes)". You could try reduce the size of those images, see that those images are for web, probably open in mobile devices as well, so better reduce before importing.

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

Thanks!
