### ISSUE TITLE
Suggestion - Improving consistency in WC_AJAX::add_order_item()

### ISSUE THREAD

**Issue by daigo75** [woocommerce/woocommerce#24089]
Method `WC_AJAX::add_order_item()` provides a filter to allow 3rd parties to manipulate the order item just added to an order. An actor could use `woocommerce_ajax_order_item` to replace the order item just added, and that could cause discrepancies. For example, the new item could have a different ID, or a different product.

Here's the relevant section, illustrating the possible issue:
~~~
// Item ID could be 123
$item_id= $order->add_product( $product, $qty );
// The $item returned here could be a different one, with a different ID (e.g. 456)
$item = apply_filters( 'woocommerce_ajax_order_item', $order->get_item( $item_id ), $item_id );
// This would have $item_id = 123, while $item->get_id() would return 456
$added_items[ $item_id ] = $item;
// $product->get_formatted_name() would return the name of the
// product added to the original item. $item->get_product()->get_formatted_name()
// could return a different value
$order_notes[ $item_id ] = $product->get_formatted_name();
~~~

In addition to the above, plugins like Bundles intercept event `woocommerce_ajax_add_order_item_meta` to replaced the added item with a set of items, generated from the bundle. However, that action receives the original `$item_id`, which might not be the ID of the `$item` returned by `woocommerce_ajax_order_item`. Due to that, the Bundles plugin could end up trying to remove the wrong item.

Possible improvement
--
A solution to the above could be to fetch the item ID and other attributes from the item returned by the filter. That is:
~~~
$item_id= $order->add_product( $product, $qty );
$item = apply_filters( 'woocommerce_ajax_order_item', $order->get_item( $item_id ), $item_id );
// Take the ID from the item returned by the filter
$item_id = $item->get_id();
// At this stage, $item_id is the value of the $item returned by the filter
$added_items[ $item_id ] = $item;
// $item->get_product()->get_formatted_name() will return the 
// name of the product of the item returned by the filter
$order_notes[ $item_id ] = $item->get_product()->get_formatted_name();
~~~

The above would ensure a consistent behaviour, always returning the ID, the product and the instance of the item added to the order.

**Comment by claudiosanches** [comment]
> An actor could use woocommerce_ajax_order_item to replace the order item just added, and that could cause discrepancies. For example, the new item could have a different ID, or a different product.

If you like feel free to submit a Pull Request, but in many filters is possible to cause problems and side effects, if using wrong like that returning a different product, for this reason I'm going to close it for now.
