### ISSUE TITLE
how can ı dissappear out of stock products

### ISSUE THREAD

**Issue by axcar95** [woocommerce/woocommerce#24092]
ın my website homepage ı use woocommerce recent products to show my products. but some of them is out of stock now and ı want them to dissapear from my homepage. they cause extra unneseccary space.

to edit my home page ı use wpbakery page builder

**Comment by homescript1** [comment]
I'm facing the same issues, i'm trying to display a messages when a product is out of stock. Just what i get it is product page without the product image , here is the screenshots : 

- when i have added the code : 

![image](https://user-images.githubusercontent.com/39379514/61189456-c8b9ed00-a685-11e9-87ab-cde63fb17fb3.png)

- without the code :
![image](https://user-images.githubusercontent.com/39379514/61189480-fbfc7c00-a685-11e9-807f-0f2d978667b0.png)

Here is my code : 
![image](https://user-images.githubusercontent.com/39379514/61189516-5c8bb900-a686-11e9-9274-8e7e2c7dd03f.png)

**Comment by rodrigoprimo** [comment]
Hi there!

GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/

If I misunderstood your issue and you believe you found a WooCommerce core bug, please open another issue following the bug report template (https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=) and provide clear steps on how to reproduce the problem.

Thanks
