### ISSUE TITLE
URL query in the external/affiliate link doesn't process encoded blank space "%20" properly any more

### ISSUE THREAD

**Issue by LorindaH** [woocommerce/woocommerce#24096]
I'm using a URL query in the external/affiliate link to bring the product name over to my form field, for example: https://domainname.co.uk/book-now/?title=Product%20Name

This used to work, but now the "%20" shows in my form instead of a blank space. I'm not sure if this is because the URL is now using double-encoding, or because the button link has been replaced with a form.

Currently the WooCommerce button is:

```
<form class="cart" action="https://domainname.co.uk/book-now/?title=Product%20Name" method="get">
<button type="submit" class="single_add_to_cart_button button alt">Book Now</button>
<input type="hidden" name="title" value="Product%20Name">
</form>
```

I want the button to have:

```
<input type="hidden" name="title" value="Product Name">
```

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24295.
