### ISSUE TITLE
If cart/checkout subtotal 0 - proceed order

### ISSUE THREAD

**Issue by alfredobauer** [woocommerce/woocommerce#24093]
Hello,

I have a big Problem.

I use a custom plugin thats set discounts based on "giftcard" values.

So if the subtotal is 1000$ and the credit on the giftcard is 200$ - subtotal is 0 - zero.

The Problem is - if subtotal 0 then no payment options showing up.
If i proceed the order it dropps an error message"no payment gateway selected".

Anyone a Tipp?

**Comment by claudiosanches** [comment]
Hi there. GitHub is primarily for reporting bugs and is not a support forum. We don’t support custom development here. You could ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce
