### ISSUE TITLE
Flag WordPress core tables in System Status Report when missing.

### ISSUE THREAD

**Issue by madeincosmos** [woocommerce/woocommerce#24105]
**Is your feature request related to a problem? Please describe.**
On one of the sites I've been working with, the list of product categories was always empty even though there were a few categories already. This turned out to be due to the `wp_termmeta` table not being created correctly. 

If a WooCommerce-specific table doesn't exist, this is normally indicated in the System Status Report. However, because this is a WordPress core table rather than WooCommerce core, it took us hours of troubleshooting to find out the problem is with database.

**Describe the solution you'd like**
Ideally, System Status Report could also check for WordPress core tables, and flag the ones that are missing as it does right now for WooCommerce core ones:

https://codex.wordpress.org/Database_Description#Table_Overview

This would help both our customers and support teams alike to diagnose problems caused by database.

**Describe alternatives you've considered**
Other than enabling WP debug and tracing db errors this way, I can't think of any other way to identify a problem caused by missing db table. Having it highlighted in the System Status Report would help us identify such problems much faster than this.

**Comment by claudiosanches** [comment]
I think that Site Health should take care of it, probably better solution to move it into a ticket in Core Trac instead of just including it on WooCommerce, since it should help everyone and core already have they own system for diagnostic.

I'll close this issue, since I already logged it on Core Trac: https://core.trac.wordpress.org/ticket/47714
