### ISSUE TITLE
Add arguments to filter `woocommerce_ajax_order_item`

### ISSUE THREAD

**Issue by daigo75** [woocommerce/woocommerce#24107]
**Is your feature request related to a problem? Please describe.**
Filter `woocommerce_ajax_order_item` passes an order item and an item ID, but it doesn't provide other important context information such as order and product.

**Describe the solution you'd like**
Simple fix: add `$order` and `$product` to the arguments passed to the filter. These two elements are available when the filter is called.

**Describe alternatives you've considered**
At the moment, filter `woocommerce_ajax_add_order_item_meta` passes the `$order` instance. However, that filter runs later and might not always be the best one.

**Comment by rodrigoprimo** [comment]
See #24108
