### ISSUE TITLE
WC_Product_Query not preserving order of ids provided in 'include' parameter

### ISSUE THREAD

**Issue by maciej-laskowski** [woocommerce/woocommerce#24106]
Hi,
I am migrating my custom product queries from WP_Query to WC_Product_Query as I believe that is the best practice. I am providing an array of product ids in `$featured_products_ids` variable and would like to preserve the order. Unfortunately WC_Product_Query does not seem to provide such option.

Please have a lot at the following example:

```
var_dump($featured_products_ids)
array(7) { [0]=> int(88260) [1]=> int(51749) [2]=> int(88122) [3]=> int(87886) [4]=> int(88069) [5]=> int(72253) [6]=> int(52403) } 
```

Old code:
```
$args = [
	'post_type' => 'product',
	'post_status' => 'published',
	'post__in' => $featured_products_ids,
	'orderby' => 'post__in',
	'posts_per_page' => 20,
];

$posts = (new WP_Query( $args ))->posts;
// returns posts in correct order => 88260 51749 88122 87886 88069 72253 52403
```

New code:
```
$args = [
	'status' => 'published',
	'include' => $featured_products_ids,
	'orderby' => 'none',
	'limit' => 20,
];
			
$products = (new WC_Product_Query( $args ))->get_products();
// returns products ordered by id => 51749 52403 72253 87886 88069 88122 88260 
```

Since according to the docs https://github.com/woocommerce/woocommerce/wiki/wc_get_products-and-WC_Product_Query WC_Product_Query  should be used instead of WP_Query it should also provide a similar set of options. I can of course easily reorder products in php but would rather avoid extra complexity.

**Comment by AndreaBarghigiani** [comment]
Same problem here, I would like to give a specific order via `include` but even if I set the `orderby` to `none` it still order by `date`.

**Comment by maciej-laskowski** [comment]
Recently I also stumbled across another problem with wc_get_products() and WC_Product_Query. Ordering by menu_order does not seem to be possible. A quick look at the WP_Query and WC_Product_Query accepted arguments hints that there are possibly a lot of incompatibilities between those two. 

I wanted to refactor all my product queries to use wc_get_products() primarly to be ready for product custom tables introduction in the (hopefully) near future. I believe it will be impossible to query products using WP_Query then, right?

**Comment by claudiosanches** [comment]
In fact `'orderby' => 'post__in',` works just fine. But I'll include an alias for it, using `'orderby' => 'include',`.

**Comment by claudiosanches** [comment]
I wrote a PR for this new alias.

I'm closing the issue as it already has a PR, please continue the discussion over at #24294.

**Comment by AndreaBarghigiani** [comment]
Thank you @claudiosanches for your contribution, sad to see that is planned for the 3.8 but at least we have some code to work on.
