### ISSUE TITLE
503 error for Customer Downloads report when previously downloaded files are removed from product

### ISSUE THREAD

**Issue by jessLundie** [woocommerce/woocommerce#24115]
**Describe the bug**
When files that have been downloaded are removed from a product, user will see a 503 error when trying to access the full logs via **WooCommerce > Reports > Customer Downloads.**

Download log entries still exist in `wc_download_log`. Fatal error logs show:

```2019-07-09T20:01:38+00:00 CRITICAL Uncaught Error: Call to a member function get_name() on boolean in /maintest/wp-content/plugins/woocommerce/includes/admin/reports/class-wc-report-downloads.php:167
Stack trace:
#0 /wordpress/core/5.2.2/wp-admin/includes/class-wp-list-table.php(1332): WC_Report_Downloads->column_default(Object(stdClass), 'file')
#1 /wordpress/core/5.2.2/wp-admin/includes/class-wp-list-table.php(1272): WP_List_Table->single_row_columns(Object(stdClass))
#2 /wordpress/core/5.2.2/wp-admin/includes/class-wp-list-table.php(1259): WP_List_Table->single_row(Object(stdClass))
#3 /wordpress/core/5.2.2/wp-admin/includes/class-wp-list-table.php(1244): WP_List_Table->display_rows()
#4 /wordpress/core/5.2.2/wp-admin/includes/class-wp-list-table.php(1175): WP_List_Table->display_rows_or_placeholder()
#5 /maintest/wp-content/plugins/woocommerce/includes/admin/reports/class-wc-report-downloads.php(128): WP_List_Table->display()
#6 /maintest/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-reports.php(177): WC_Report_Downloads->output_report()
#7 /maintest/wp-content/plugins/woocommerce/includes/admin/views/html-admin-page-reports.php(69): WC_Admin_Reports::get_report('downloads')
#8 /maintest/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-reports.php(36): include_once('/maintest/wp-co...')
#9 /maintest/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-menus.php(246): WC_Admin_Reports::output()
#10 /wordpress/core/5.2.2/wp-includes/class-wp-hook.php(286): WC_Admin_Menus->reports_page('')
#11 /wordpress/core/5.2.2/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#12 /wordpress/core/5.2.2/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#13 /wordpress/core/5.2.2/wp-admin/admin.php(253): do_action('woocommerce_pag...')
#14 {main}
  thrown in /maintest/wp-content/plugins/woocommerce/includes/admin/reports/class-wc-report-downloads.php on line 167
```

**To Reproduce**
1. Create a product with a downloadable file
2. Purchase the product
3. Download the file
4. Check WooCommerce > Reports > Customer Downloads to see that download is recorded
5. Check `wc_download_log` table - download record exists
6. Remove the downloadable file from the product
7. Save the product

Repeat steps 4 & 5 - the records in the database still exist, but accessing the Customer Downloads report gives a 503 error. 

**Screenshots**

**Expected behavior**
The Customer Downloads report remains accessible and visible even if files are removed and replaced on the individual products. 

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://maintest.mystagingwebsite.com
Site address (URL): https://maintest.mystagingwebsite.com
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.2.19
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 6144
cURL Version: 7.65.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.31-MariaDB
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 5.01MB
Database Data Size: 3.03MB
Database Index Size: 1.98MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB
wp_ariadminer_connections: Data: 0.02MB + Index: 0.00MB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB
wp_automatewoo_log_meta: Data: 0.02MB + Index: 0.03MB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB
wp_automatewoo_unsubscribes: Data: 0.02MB + Index: 0.05MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.06MB + Index: 0.09MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 1.22MB + Index: 0.05MB
wp_postmeta: Data: 0.23MB + Index: 0.22MB
wp_posts: Data: 0.08MB + Index: 0.06MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_bundled_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_subscription_downloads: Data: 0.02MB + Index: 0.00MB
wp_wpml_mails: Data: 0.44MB + Index: 0.00MB

### Post Type Counts ###

attachment: 3
aw_workflow: 6
customize_changeset: 2
page: 12
post: 1
product: 12
product_variation: 19
revision: 6
scheduled-action: 75
shop_coupon: 2
shop_order: 16
shop_subscription: 5
wc_membership_plan: 1
wc_user_membership: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Meks Quick Plugin Disabler: by Meks – 1.0
WooCommerce Stripe Gateway: by WooCommerce – 4.2.2
WooCommerce: by Automattic – 3.6.5

### Inactive Plugins (25) ###

Akismet Anti-Spam: by Automattic – 4.1.2
ARI Adminer: by ARI Soft – 1.2.3
AutomateWoo: by Prospress – 4.5.5
AutomateWoo - Referrals Add-on: by Prospress – 2.3.2 – Not tested with the active version of WooCommerce
Classic Editor: by WordPress Contributors – 1.5
Jetpack by WordPress.com: by Automattic – 7.5.2
Mailchimp for WooCommerce: by Mailchimp – 2.1.17
Storefront Parallax Hero: by WooCommerce – 1.5.7
User Switching: by John Blackbourn & contributors – 1.5.1
WooCommerce Advanced Notifications: by WooCommerce – 1.2.16
WooCommerce All Products For Subscriptions: by SomewhereWarm – 2.3.0
WooCommerce Bookings: by WooCommerce – 1.14.5
WooCommerce Box Office: by WooCommerce – 1.1.12
WooCommerce Chained Products: by StoreApps – 2.9.2
WooCommerce Memberships: by SkyVerge – 1.13.1
WooCommerce Mix and Match: by Kathy Darling – 1.5.1
WooCommerce Name Your Price: by Kathy Darling – 2.9.6
WooCommerce Product Bundles: by SomewhereWarm – 5.10.2 – 5.11.0 is available
WooCommerce Services: by Automattic – 1.20.0 – 1.21.0 is available
WooCommerce Shipment Tracking: by WooCommerce – 1.6.14
WooCommerce Subscription Downloads: by WooCommerce – 1.1.18
WooCommerce Subscriptions: by Automattic – 2.5.7
WooCommerce Subscriptions Gifting: by Automattic – 2.0.4
WordPress Importer: by wordpressdotorg – 0.6.4
WP Mail Logging: by Christian Zöller – 1.9.1

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
bundle (bundle)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.0 – 2.5.1 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 46
Oldest: 2019-06-14 09:32:29 -0700
Newest: 2019-07-09 15:46:29 -0700

Pending: 4
Oldest: 2019-08-08 12:13:53 -0700
Newest: 2019-08-09 10:17:57 -0700

Canceled: 25
Oldest: 2019-06-14 09:34:35 -0700
Newest: 2019-07-27 11:43:59 -0700

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –
`
</details>

**Comment by aslamshekh** [comment]
I have tested this one and found as a bug, Which I resolved by this PR #24118. Kindly review and let me know if there are any changes required.

Downloads report not getting 503 any more, If previously downloaded files are removed from the product then I have added a simple message like File not exists instead of the file name.
