### ISSUE TITLE
Woocommerce CSV Import Suit - Out of Stock instead of On Backorder

### ISSUE THREAD

**Issue by vincenzoraco** [woocommerce/woocommerce#24119]
**Describe the bug**
When importing products data to update the stock levels and prices, the import sets the metakey '_stock_status' to 'outofstock' instead of 'onbackorder' if the product quantity is 0.

**To Reproduce**
1. Go to 'Product CSV Import Suite'
2. Click on 'Import Products'
3. Select File
4. Wait for the import to be completed
5. The product item page says 'out of stock' instead of 'Add to cart, on backorder'.
6. If you go to the product backend page
7. Click Inventory in Product Data
8. Allow Backorders? is showing 'Allow, but Notify Customer'.

**Expected behavior**
When importing, and the product stock level is 0 and we specify in the import that we want to allow the backorder on this item, it should set the value to 'onbackorder' in the metakey '_stock_status'.

**Isolating the problem (mark completed items with an [x]):**
- [X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

WordPress address (URL): https://www.beyondtools.com/wptools
Site address (URL): https://www.beyondtools.com
WC Version: 3.6.5
Log Directory Writable: ?
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: –
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.39 (cPanel) OpenSSL/1.0.2r mod_bwlimited/1.4
PHP Version: 7.1.30 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 3600
PHP Max Input Vars: 15300
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 10.0.38-MariaDB
Max Upload Size: 128 MB
Default Timezone is UTC: ?
fsockopen/cURL: ?
SoapClient: ?
DOMDocument: ?
GZip: ?
Multibyte String: ?
Remote Post: ?
Remote Get: ?

### Database ###

WC Database Version: 3.4.5
WC Database Prefix: y0hxzkxp_
MaxMind GeoIP Database: ?
Total Database Size: 949.83MB
Database Data Size: 828.52MB
Database Index Size: 121.31MB
y0hxzkxp_woocommerce_sessions: Data: 202.24MB + Index: 6.51MB
y0hxzkxp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
y0hxzkxp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
y0hxzkxp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_woocommerce_order_items: Data: 3.12MB + Index: 1.30MB
y0hxzkxp_woocommerce_order_itemmeta: Data: 15.52MB + Index: 10.75MB
y0hxzkxp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
y0hxzkxp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB
y0hxzkxp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_alm: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_aws_cache: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_aws_index: Data: 16.80MB + Index: 0.00MB
y0hxzkxp_commentmeta: Data: 0.13MB + Index: 0.10MB
y0hxzkxp_comments: Data: 9.30MB + Index: 3.56MB
y0hxzkxp_duplicator_pro_entities: Data: 0.01MB + Index: 0.00MB
y0hxzkxp_duplicator_pro_packages: Data: 0.02MB + Index: 0.00MB
y0hxzkxp_failed_jobs: Data: 0.17MB + Index: 0.01MB
y0hxzkxp_frontend_builder_options: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_frontend_builder_pages: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_itsec_distributed_storage: Data: 5.05MB + Index: 0.00MB
y0hxzkxp_itsec_fingerprints: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_itsec_geolocation_cache: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_itsec_lockouts: Data: 0.00MB + Index: 0.01MB
y0hxzkxp_itsec_logs: Data: 343.83MB + Index: 8.21MB
y0hxzkxp_itsec_temp: Data: 0.24MB + Index: 0.20MB
y0hxzkxp_links: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_lockdowns: Data: 0.10MB + Index: 0.03MB
y0hxzkxp_login_fails: Data: 0.77MB + Index: 0.26MB
y0hxzkxp_mailchimp_carts: Data: 0.17MB + Index: 0.02MB
y0hxzkxp_nf_objects: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_nf_relationships: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_ninja_forms: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_offline_giftcard: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_options: Data: 37.25MB + Index: 2.03MB
y0hxzkxp_pmxe_templates: Data: 0.01MB + Index: 0.00MB
y0hxzkxp_pmxi_files: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_pmxi_history: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_pmxi_imports: Data: 0.25MB + Index: 0.00MB
y0hxzkxp_pmxi_posts: Data: 0.33MB + Index: 0.12MB
y0hxzkxp_pmxi_templates: Data: 0.09MB + Index: 0.00MB
y0hxzkxp_postmeta: Data: 115.77MB + Index: 43.59MB
y0hxzkxp_posts: Data: 17.62MB + Index: 3.72MB
y0hxzkxp_ps_exclude: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_ps_posts: Data: 0.24MB + Index: 0.06MB
y0hxzkxp_ps_product_sku: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_queue: Data: 0.01MB + Index: 0.00MB
y0hxzkxp_statistics_exclusions: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_statistics_historical: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_statistics_pages: Data: 24.09MB + Index: 18.19MB
y0hxzkxp_statistics_useronline: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_statistics_visit: Data: 0.03MB + Index: 0.02MB
y0hxzkxp_statistics_visitor: Data: 8.97MB + Index: 4.79MB
y0hxzkxp_termmeta: Data: 0.55MB + Index: 0.38MB
y0hxzkxp_terms: Data: 0.39MB + Index: 0.63MB
y0hxzkxp_term_relationships: Data: 1.78MB + Index: 3.20MB
y0hxzkxp_term_taxonomy: Data: 0.49MB + Index: 0.48MB
y0hxzkxp_usermeta: Data: 20.61MB + Index: 11.53MB
y0hxzkxp_users: Data: 0.99MB + Index: 1.16MB
y0hxzkxp_wc_download_log: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_wc_gpf_render_cache: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB
y0hxzkxp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_wfConfig: Data: 0.02MB + Index: 0.01MB
y0hxzkxp_wfconfig: Data: 0.00MB + Index: 0.01MB
y0hxzkxp_wfCrawlers: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_wfcrawlers: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_wfHits: Data: 0.08MB + Index: 0.02MB
y0hxzkxp_wfhits: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_wfHoover: Data: 0.08MB + Index: 0.02MB
y0hxzkxp_wfhoover: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_wfissues: Data: 0.00MB + Index: 0.00MB
y0hxzkxp_wfIssues: Data: 0.01MB + Index: 0.00MB
y0hxzkxp_woocommerce_gpf_google_taxonomy: Data: 0.86MB + Index: 0.00MB
y0hxzkxp_yoast_seo_links: Data: 0.26MB + Index: 0.05MB
y0hxzkxp_yoast_seo_meta: Data: 0.20MB + Index: 0.20MB

### Post Type Counts ###

acf: 2
acf-field: 2
acf-field-group: 2
attachment: 10712
custom_css: 2
customize_changeset: 6
et_pb_layout: 32
feedback: 107
giftcard: 4
nav_menu_item: 1276
nf_sub: 6
oembed_cache: 16
page: 102
post: 143
price_match_request: 3
product: 6471
product_variation: 160
revision: 1
rp_shop_giftcard: 130
scheduled-action: 2
shop_coupon: 19
shop_order: 15960
shop_order_refund: 289
shop_quote: 342
slide: 15
slides: 6
soliloquy: 1
sp_responsiveslider: 2
testimonial: 3
testimonials: 3
tribe_events: 123
tribe_organizer: 11
tribe_venue: 23
tribe-ea-record: 40
wishlist: 10704
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ?
Hide errors from visitors: ?

### Active Plugins (32) ###

Advanced Custom Fields: by Elliot Condon – 5.8.1
Advanced Database Cleaner: by Younes JFR. – 2.0.0
WooCommerce Afterpay Gateway: by AfterPay – 1.3.1 – Not tested with the active version of WooCommerce
Akismet Anti-Spam: by Automattic – 4.1.2
iThemes Security: by iThemes – 7.4.0
Beyond Tools: by Vincenzo Raco – 1.0.0
Contact Form 7: by Takayuki Miyoshi – 5.1.3
Easy FancyBox: by RavanH – 1.8.17
Facebook for WooCommerce: by Facebook – 1.9.15 – Not tested with the active version of WooCommerce
WooCommerce - Gift Cards: by WP Ronin – 2.6.5 – Not tested with the active version of WooCommerce
Google XML Sitemaps: by Arne Brachhold – 4.1.0
Custom Feeds for Instagram: by Smash Balloon – 1.12.1
Mailchimp for WooCommerce: by Mailchimp – 2.1.17
Max Mega Menu: by megamenu.com – 2.7.1.4
My Custom Functions: by Space X-Chimp – 4.38
Product/Review CSV Import Export: by WebToffee – 3.7.6
Search By SKU - for Woocommerce: by Matthew Lawson – 0.6.1 – Not tested with the active version of WooCommerce
SnapEngage plugin: by SnapEngage – 1.0
WooCommerce Extra Product Sorting Options: by SkyVerge – 2.7.4
WooCommerce PDF & Print: by gVectors Team – 1.5.0 – Not tested with the active version of WooCommerce
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.16 – Not tested with the active version of WooCommerce
WooCommerce Google Product Feed: by Ademti Software Ltd. – 7.8.4 – Not tested with the active version of WooCommerce
WooCommerce Products Compare: by WooCommerce – 1.0.7 – Not tested with the active version of WooCommerce
Woocommerce Products Per Page: by Jeroen Sormani – 1.2.6 – Not tested with the active version of WooCommerce
WooCommerce Sales Report Email: by WooThemes – 1.1.2 – Not tested with the active version of WooCommerce
WooCommerce Smart Refunder: by StoreApps – 1.1.1 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.6.5
WP Disable: by optimisation.io - jody nesbitt – 1.5.21
WP Migrate DB: by Delicious Brains – 1.0.11
WP Rocket: by WP Media – 3.3.5.2
WooCommerce - Gift Cards Pro: by WP Ronin – 1.6.2 – Not tested with the active version of WooCommerce
Zip - WooCommerce: by Zip – 2.1.4

### Inactive Plugins (4) ###

WooCommerce - Store Exporter: by Visser Labs – 2.0.2 – Not tested with the active version of WooCommerce
WooCommerce Customer/Order CSV Export: by SkyVerge – 4.3.7 – Not tested with the active version of WooCommerce
WP Memcached Manager: by Warwick Poole – 0.1
WP Rocket | Custom Sitemap Preload Intervals: by WP Rocket Support Team –

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

WP Migrate DB Compatibility: by Delicious Brains – 1.2

### Settings ###

API Enabled: ?
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-catalog (exclude-from-catalog-2)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #481 - /shop/
Cart: #483 - /cart/
Checkout: #485 - /checkout/
My account: #487 - /my-account/
Terms and conditions: #11552 - /big-on-service/terms/

### Theme ###

Name: Beyond Tools
Version: 1.0
Author URL: 
Child Theme: ? – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ?

### Templates ###

Overrides: beyond-tools/woocommerce/archive-product.php version 2.0.0 is out of date. The core version is 3.4.0
beyond-tools/woocommerce/content-product.php version 3.4.0 is out of date. The core version is 3.6.0
beyond-tools/woocommerce/content-product_cat.php
beyond-tools/woocommerce/content-single-product.php version 3.4.0 is out of date. The core version is 3.6.0
beyond-tools/woocommerce/single-product.php

Outdated Templates: ?
					
					
						Learn how to update

### WooCommerce Google Product Feed fields ###

Product description: Main product description only (full preferred.)
Availability: Defaults to "in stock".
Condition: Defaults to "new".
Brand: Pre-populates from pa_brand taxonomy.
Product Type: Pre-populates from pa_tool-equipment-type taxonomy.
Google Product Category: 

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send item_group_id: No

### Store Catalog PDF Download ###

Template Overrides: 

### Action Scheduler ###

Complete: 1
Oldest: 2019-06-11 20:42:40 +0000
Newest: 2019-06-11 20:42:40 +0000

Pending: 1
Oldest: 2019-06-19 00:42:33 +0000
Newest: 2019-06-19 00:42:33 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –
</details>

**Comment by rodrigoprimo** [comment]
@woocommerce/extendables could you please take a look and see if you are able to reproduce this issue as, from the description, it seems to be related to Product CSV Import Suite and not WooCommerce core?

**Comment by roykho** [comment]
Issue moved to [woocommerce/woocommerce-product-csv-import-suite #157](https://github.com/woocommerce/woocommerce-product-csv-import-suite/issues/157) via [**ZenHub**](https://www.zenhub.com/)

**Comment by roykho** [comment]
@vincenzoraco - Thanks for reporting. We've moved this to the proper repo.

**Comment by vincenzoraco** [comment]
Hi @roykho, I get a 404 page when I try to access the link. Can I have access to the repo or is for internal use only?

**Comment by roykho** [comment]
@vincenzoraco its internal. You would have to open a support ticket to keep track of this issue. Please go to https://woocommerce.com/ and click on support.
