### ISSUE TITLE
Shipping problem

### ISSUE THREAD

**Issue by bluebirdgrain** [woocommerce/woocommerce#24113]
Our store is suddenly offering priority mail flat rate shipping to customers with large orders that should only be quoted UPS shipping. It seems to only occur when they have both large items and small items. Just started happening Monday. 

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by claudiosanches** [comment]
Hi there! GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal.

If you need technical support for [UPS Shipping Method](https://woocommerce.com/products/ups-shipping-method/), please use the helpdesk instead: https://woocommerce.com/contact-us/
