### ISSUE TITLE
how to allow user to upload their product for sale?

### ISSUE THREAD

**Issue by mayankpandav** [woocommerce/woocommerce#24122]
how to allow user to upload their product for sale?

**Comment by rodrigoprimo** [comment]
Hi there!

GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/
