### ISSUE TITLE
Filter to disable non required meta items

### ISSUE THREAD

**Issue by rochow** [woocommerce/woocommerce#24144]
**Is your feature request related to a problem? Please describe.**
wp_posts and wp_postmeta are obviously super flexible at the cost of being a real dog in performance

**Describe the solution you'd like**
There are constantly meta fields which never used on stores. For example:
Height
Width
Length
= These are rarely used in my experience. Normally if it is used, it's for shipping purposes.

Backorders
= Rare

Downloadable
Virtual
= Nearly always this is on or off, not many mixed stores

You get the gist. The point is having the ability to enable/disable **what** fields will mean - especially with stores with variations given it duplicates everything - a mountain of postmeta rows are saved.

For one example, a pretty small store really, there are 2500 products. Even the 7 mentioned field would save 17,500 rows of data.

In their case it can easily push further: _sold_individually, _tax_status, _tax_class, _sale_price_dates_from, _sale_price_dates_to (not useful unless a product is actually on sale!) etc.

It could be done either via an admin UI, or filters which can return false on various meta. This would:
- Hide them from the admin, given they won't work anyway
- Turn false rather than having functions erroring when expected meta is missing

**Comment by tahsin352** [comment]
@rochow nice idea, i totally agree with it. 

I propose to have both. admin UI & filters.

**Comment by RobertMPop** [comment]
@rochow, this should have been implemented years ago.

In my case, (at least) the stuff below is totally useless:

`'_tax_status'
'_tax_class'
'_sale_price_dates_from'
'_sale_price_dates_to'
'_weight'
'_length'
'_width'
'_height'
'_backorders'
'_upsell_ids'
'_crosssell_ids'
'_purchase_note'
'_virtual'
'_downloadable'
'_download_expiry'
'_wc_rating_count'
'_wc_average_rating'
'_wc_review_count'`

@rochow, you've mentioned 7 fields per product that could save some serious row data. Now, how about my **18 unnecessary rows** per product? :)

The same should also be achieved for Orders. For instance:

-  ALL shipping details which are basically duplicates of the billing details should be updated in postmeta **_only_** if the customer checks the "Ship to a different address?" checkbox and fills-in the fields.
- `_cart_discount`, `_cart_discount_tax` and all other coupon-related should be updated **_only_** if Coupons are enabled.
- `_order_tax`,  `_order_shipping_tax` and all other tax-related should be updated **_only_** if Taxes are enabled.

If WC wants to start having large e-commerce stores as clients, this matter should be a priority (besides releasing custom tables for products and orders).

**Comment by tahsin352** [comment]
@RobertMPop good point about separate table for product & orders. But my question is current it is a custom post_type 'product'. If we make it separate table, then I guess, we will not get those benefits of post_type.

**Comment by kloon** [comment]
In 3.6 #22773 addressed this, there are unfortunately a couple of fields we cannot delete. Read the comments on the PR for details on those fields.
