### ISSUE TITLE
Follow Ups API get emails return only 24 results

### ISSUE THREAD

**Issue by MatPain** [woocommerce/woocommerce#24149]
Hello,

i don't understand why the call api get emails return only 24 results,

documentation : 

http://woocommerce.github.io/woocommerce-follow-up-emails/#list-emails

my code :

                       `// Initialize the class
			$fue_api = new FUE_API_Client( $consumer_key, $consumer_secret, $wp_url );

			$json = $fue_api->get_emails();

		       $options[''] = __( 'Select a email (Follow-Up)', 'woocommerce'); // default value

			foreach ($json as $key => $object) {
			    $options[$object->email->id] = $object->email->name;
			}

			//echo print_r( $options ); //debug

			woocommerce_wp_select(
				array(
					'id' => 'email_start_event',
					'label'       => __( 'Select the email for the start event', 'woocommerce' ),
					'selected' => true,
					'wrapper_class' => 'form-row form-row-first',
					'value' => get_post_meta( $variation->ID, 'email_start_event', true ),
					'options' => $options
				)
			);`

thanks for your help

**Comment by claudiosanches** [comment]
Hi there! GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal.

If you need technical support for Follow Ups, please use the helpdesk instead: https://woocommerce.com/contact-us/
