### ISSUE TITLE
Orders REST API meta_data field incorrect

### ISSUE THREAD

**Issue by unidesigner** [woocommerce/woocommerce#24148]
**Describe the bug**
When requesting an order via REST API v3, I expect the meta_data field to contain the order's metadata. With the WPML plugin and multi-currency support enabled for WooCommerce, this does not work for orders that are made not in the main currency.

**To Reproduce**
1. Make an HTTP GET request to the order API and retrieve the json object
2. The meta_data fields contains e.g. `'meta_data': [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}],` for orders made not in the main currency. For orders in the main currency, the meta_data fields shows the dictionaries with key, value, id properly.

**Expected behavior**
Properly return the meta_data field for all orders.

**Isolating the problem (mark completed items with an [x]):**
- [ ] The problem seems to be occuring in `wp-content/plugins/woocommerce/includes/api/v2/class-wc-rest-orders-v2-controller.php`, either when formatting the HTTP GET response, or when appyling further filtering.

**WordPress Environment**
<details>
```Can be added if necessary.
```
</details>

**Comment by claudiosanches** [comment]
Sounds like that need to be patched in WPML, since they change and duplicate meta data.
Closing since it not happens in a clean install, only with WPML.

**Comment by unidesigner** [comment]
Ok, thanks. I'll ask WPML Support.
