### ISSUE TITLE
Problems with the country

### ISSUE THREAD

**Issue by ConniePfeifer** [woocommerce/woocommerce#24155]
Hello!

My problem is that I keep changing the country from where am I (Chile) .. and woocommerce doesn't save it. they keep changing it to Afganistan. Please help with that issue.. I can't solve it and i swear I have been a lot of hours trying to.

Thank you so much

**Comment by claudiosanches** [comment]
Where are you trying to change? What version of WooCommerce?
It's missing several information in this bug report, maybe better close and start again filling all the template: https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=

**Comment by rodrigoprimo** [comment]
Closing this issue due to lack of feedback. Please provide the information requested above and we will take a look.
