### ISSUE TITLE
setup wizard country drop down no matches found

### ISSUE THREAD

**Issue by Thagana** [woocommerce/woocommerce#24150]
upon launching the wizard when i try to select a country it displays no matches found.
I am using Shopper Theme with the latest woocommerce plugin.This happens in the admin area.
I searched for the same issue but found that most is due to theme CSS clashing with the woocommerce CSS but my problem is at the setup wizard and woocommerce settings > General.

**Comment by kloon** [comment]
Can you please test this by disabling all plugins except WooCommerce and then switching your theme to a default one like Storefront or Twentyseventeen and testing again?

This is likely caused by a JS error in your theme or a plugin.

**Comment by claudiosanches** [comment]
Hi there! GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal.

Your issue seems to be caused by Shopper Theme.

Please contact the author directly for support.
