### ISSUE TITLE
Woocommerce plugin not displaying product pages

### ISSUE THREAD

**Issue by marada1** [woocommerce/woocommerce#24169]
**Describe the bug**
When you click a buy now button to call up a product, all that shows is a blank screen. When you open the product link in the dashboard the product is listed. You can do a quick edit but can not open the product with edit or view.

**To Reproduce**
1. Go to 'www.smarthobbyllc.com'
2. Click on 'Buy Now'

**Screenshots**

**Expected behavior**
When you click on buy now the product is displayed and waits for input directing client to choose quantity where it is then placed into the cart.

**Isolating the problem (mark completed items with an [x]):**
- [Yes ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [Yes ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [Yes ] I can reproduce this bug consistently using the steps above.

</details>
`
### WordPress Environment ###

WordPress address (URL): https://www.smarthobbyllc.com
Site address (URL): https://www.smarthobbyllc.com
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.15
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.32-78.0-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: asb_
MaxMind GeoIP Database: ✔
Total Database Size: 6.45MB
Database Data Size: 5.16MB
Database Index Size: 1.29MB
asb_woocommerce_sessions: Data: 2.02MB + Index: 0.05MB
asb_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
asb_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
asb_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
asb_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
asb_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
asb_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
asb_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
asb_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
asb_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
asb_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
asb_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
asb_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
asb_woocommerce_log: Data: 0.02MB + Index: 0.02MB
asb_aiowps_events: Data: 0.00MB + Index: 0.00MB
asb_aiowps_failed_logins: Data: 0.01MB + Index: 0.00MB
asb_aiowps_global_meta: Data: 0.00MB + Index: 0.00MB
asb_aiowps_login_activity: Data: 0.00MB + Index: 0.00MB
asb_aiowps_login_lockdown: Data: 0.00MB + Index: 0.00MB
asb_aiowps_permanent_block: Data: 0.00MB + Index: 0.00MB
asb_commentmeta: Data: 0.00MB + Index: 0.01MB
asb_comments: Data: 0.31MB + Index: 0.22MB
asb_failed_jobs: Data: 0.02MB + Index: 0.00MB
asb_links: Data: 0.00MB + Index: 0.00MB
asb_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
asb_options: Data: 0.72MB + Index: 0.05MB
asb_postmeta: Data: 0.51MB + Index: 0.08MB
asb_posts: Data: 1.04MB + Index: 0.23MB
asb_queue: Data: 0.02MB + Index: 0.00MB
asb_smush_dir_images: Data: 0.00MB + Index: 0.00MB
asb_termmeta: Data: 0.00MB + Index: 0.01MB
asb_terms: Data: 0.00MB + Index: 0.01MB
asb_term_relationships: Data: 0.01MB + Index: 0.03MB
asb_term_taxonomy: Data: 0.00MB + Index: 0.00MB
asb_usermeta: Data: 0.01MB + Index: 0.01MB
asb_users: Data: 0.00MB + Index: 0.01MB
asb_wc_admin_notes: Data: 0.00MB + Index: 0.00MB
asb_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB
asb_wc_customer_lookup: Data: 0.00MB + Index: 0.00MB
asb_wc_download_log: Data: 0.02MB + Index: 0.03MB
asb_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB
asb_wc_order_product_lookup: Data: 0.00MB + Index: 0.00MB
asb_wc_order_stats: Data: 0.00MB + Index: 0.00MB
asb_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB
asb_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
asb_wc_webhooks: Data: 0.02MB + Index: 0.02MB
asb_wpfm_backup: Data: 0.02MB + Index: 0.00MB
wp_mrd7fxman4_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_mrd7fxman4_comments: Data: 0.00MB + Index: 0.01MB
wp_mrd7fxman4_gf_draft_submissions: Data: 0.00MB + Index: 0.00MB
wp_mrd7fxman4_gf_entry: Data: 0.00MB + Index: 0.00MB
wp_mrd7fxman4_gf_entry_meta: Data: 0.00MB + Index: 0.00MB
wp_mrd7fxman4_gf_entry_notes: Data: 0.00MB + Index: 0.00MB
wp_mrd7fxman4_gf_form: Data: 0.00MB + Index: 0.00MB
wp_mrd7fxman4_gf_form_meta: Data: 0.00MB + Index: 0.00MB
wp_mrd7fxman4_gf_form_revisions: Data: 0.00MB + Index: 0.00MB
wp_mrd7fxman4_gf_form_view: Data: 0.00MB + Index: 0.00MB
wp_mrd7fxman4_links: Data: 0.00MB + Index: 0.00MB
wp_mrd7fxman4_options: Data: 0.08MB + Index: 0.02MB
wp_mrd7fxman4_postmeta: Data: 0.02MB + Index: 0.02MB
wp_mrd7fxman4_posts: Data: 0.03MB + Index: 0.01MB
wp_mrd7fxman4_termmeta: Data: 0.00MB + Index: 0.00MB
wp_mrd7fxman4_terms: Data: 0.00MB + Index: 0.01MB
wp_mrd7fxman4_term_relationships: Data: 0.00MB + Index: 0.00MB
wp_mrd7fxman4_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_mrd7fxman4_usermeta: Data: 0.00MB + Index: 0.01MB
wp_mrd7fxman4_users: Data: 0.00MB + Index: 0.01MB

### Post Type Counts ###

attachment: 32
customize_changeset: 18
custom_css: 1
nav_menu_item: 21
page: 18
post: 3
product: 12
revision: 140
scheduled-action: 1127
shop_coupon: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

Autoptimize: by Frank Goossens (futtta) – 2.5.1
WooCommerce Continue Shopping: by HappyKite – 1.3.1 – Not tested with the active version of WooCommerce
Facebook for WooCommerce: by Facebook – 1.9.15 – Not tested with the active version of WooCommerce
Image Size Selection for Divi: by Aaron Bolton – 1.0.3
Mailchimp for WooCommerce: by Mailchimp – 2.1.17
PHP Compatibility Checker: by WP Engine – 1.4.7
Compress JPEG & PNG images: by TinyPNG – 3.2.0
PayPal PLUS for WooCommerce: by Inpsyde GmbH – 2.0.4
WooCommerce Admin: by WooCommerce – 0.15.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.15
WooCommerce Services: by Automattic – 1.21.0
WooCommerce: by Automattic – 3.6.5
WP File Manager: by mndpsingh287 – 5.2

### Dropin Plugins (1) ###

object-cache.php: APCu Object Cache

### Must Use Plugins (1) ###

System Plugin: by  – 3.9.5

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #272 - /new-hobby-shop/
Cart: #106 - /cart/
Checkout: #123 - /checkout/
My account: #110 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Divi
Version: 3.26.1
Author URL: http://www.elegantthemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1,124
Oldest: 2019-06-15 16:44:35 +0000
Newest: 2019-07-15 20:42:20 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 3
Oldest: 2019-07-15 13:01:47 +0000
Newest: 2019-07-15 21:42:20 +0000

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by marada1** [comment]
The steps I have taken to resolve include using woocommerce tool to regenerate missing pages, re publishing permalinks, updating and republishing product, deleting product and adding new, flushing cache, enlisting wordpress developers to troubleshoot. No success

**Comment by rodrigoprimo** [comment]
Hi there!

GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/

Checking your PHP error log might reveal what is the error that is causing the blank screen after you click on the "Buy now" button.

**Comment by marada1** [comment]
Hi Rodrigo, I was reporting this as a bug because all tests and procedures failed to find anything wrong. In addition, a Wordpress developer used wp-debug to look for PHP errors and found nothing. All the assistance from the various support groups failed at an solution. Everything appears to be correct on the install and configuration. As you can see in the woo report, there are no errors. The woo report also shows autoptimize installed and it is not anymore. That was tried to see if there was css or java code that needed to be cleaned up. Because all else failed that made me think there might be a bug. I have contacted my hosting provider and they are looking into it as well. Again, the only reason I posted was the possibilty there might be a bug.
Jack

**Comment by rodrigoprimo** [comment]
Hi Jack,

Thanks for the extra context. Unfortunately, the information provided is not enough to tell whether it is a WooCommerce bug or not.

**Comment by marada1** [comment]
Ok, I will wait to see what the hosing company says then go from there. If all else fails I’ll revert back to 3.6.4. Is the database for 3.6.5 the same as 3.6.4 or will I have to go to the backup for the database as well.

**Comment by marada1** [comment]
Been on line with GoDaddy for an hour and a half. Here is the finnal message from them.   The compatibility issue is with plugin and the content and the Hp versions of it and once review with plugin holder and check on it, as we have limited access on the plugin in WordPress. I've tried in all other ways but without restoration the site cannot be live with that page. please check with them for ecomommere plugin. Sounds like they are saying that Ver 3.6.5 is not compatible with them. So is that a bug or just them being not nice

**Comment by marada1** [comment]
Sorry to keep bothering you but this is FYI. I reverted back to version 3.6.4 and the product pages are back. It was less of a hassle then I figured. I downloaded the zip file of 3.6.4 then deactivated and deleted 3.6.5. Installed 3.6.4 and it saw the prior product pages. No changes needed. Installed a plugin manager and turned off auto update for woocommerce. So, GoDaddy is not compatible with the new version. I do not know if that is a concern or not.
Jack

**Comment by rodrigoprimo** [comment]
Thanks for the update, Jack. It is unlikely that GoDaddy is not compatible with the new WooCommerce version as there are several Woo sites running on that host and we haven't received other reports of problems.

If you are a paying WooCommerce.com customer, I suggest you contact their support as they have staff to help you troubleshoot this issue and determine what is causing it: http://woocommerce.com/contact-us/

**Comment by marada1** [comment]
I did contact them and they tried for over 2 hours yesterday to resolve it before telling me flat out the the plug in was not compatible. As I mentioned, I have reverted back to 3.6.4 and all is well.  I was just trying to give you an FYI of what GoDaddy had said.
