### ISSUE TITLE
[REST API] /products/attributes/<attribute_id>/terms endpoints stopped working

### ISSUE THREAD

**Issue by tszilassi** [woocommerce/woocommerce#24160]
**Describe the bug**
The Product Attribute Terms endpoints stopped working somewhere around the 3.6.0 update.

Returning an error code: woocommerce_api_invalid_product_attribute_id (A product attribute with the provided ID could not be found).

The cause of this issue is that these API endpoints rely on the wc_attribute_taxonomy_name_by_id() function to obtain the attribute taxonomy names.

This function uses array_search() with STRICT switch to look up the taxonomy names by attribute ID.

The <$attribute_id> URL path fragment value is a string type. The strict array_search() needs an integer typed needle ($attribute_id) because the attribute ids are integers in the haystack  (array obtained through wc_get_attribute_taxonomy_ids() function).

This is why the function fails to return the Attribute Taxonomy Name and failing the whole API call consecutively.

In my humble opinion the issue can be fixed wether by: 
- making sure that the $attribute_id parameter in the: wc_attribute_taxonomy_name_by_id($attribute_id) function is an Integer (and not a String as it's currently)
OR 
- adjusting the $attribute_name = (string) array_search( $attribute_id, $taxonomy_ids, true ) call to make the last parameter (strict) FALSE

**To Reproduce**
Steps to reproduce the behaviour:

1. Create new Product Attribute (or use an ID of an already created Product Attribute)
2. Add Terms to the newly created Attributes (or use an Attribute with Terms already present)
3. Enable the REST API (make sure to have Customer Key & Secret access credentials created)
4. Navigate to the API endpoint for querying Product Attribute Terms http://domain/wc-api/v3/products/attributes/<attribute_id>/terms?consumer_key=<consumer_key>&consumer_secret=<consumer_secret>
5. See Error "A product attribute with the provided ID could not be found" even if the Attribute with the given ID is present

**Expected behavior**
The REST API should return the array of Terms associated to the specific Product Attribute ID

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

WordPress address (URL): https://wordpress-242610-923058.cloudwaysapps.com
Site address (URL): https://wordpress-242610-923058.cloudwaysapps.com
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.2.19-1+0~20190531112732.22+jessie~1.gbp75765b
PHP Post Max Size: 256 MB
PHP Time Limit: 1000
PHP Max Input Vars: 2500
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.44-86.0
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 3.09MB
Database Data Size: 2.14MB
Database Index Size: 0.95MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 1.50MB + Index: 0.02MB
wp_postmeta: Data: 0.06MB + Index: 0.03MB
wp_posts: Data: 0.06MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 17
customize_changeset: 1
page: 8
post: 3
product: 12
revision: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Breeze: by Cloudways – 1.0.10
WooCommerce: by Automattic – 3.6.5

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.2
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #11 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 0
Oldest: –
Newest: –

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –


```
</details>

**Comment by malviyaritesh** [comment]
I noticed that you are using WooCommerce legacy API v3 and this issue only occurs in legacy API endpoint. It is strongly advised not to use deprecated legacy API which will get removed anytime in future as mentioned [here](https://github.com/woocommerce/woocommerce/wiki/Contributing-to-the-WooCommerce-REST-API#deprecation-of-older-versions).

Instead, you should use latest [endpoint](https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-attribute-terms), which works fine.

```cURL
curl https://example.com/wp-json/wc/v3/products/attributes/2/terms \
    -u consumer_key:consumer_secret
```

WooCommerce REST API is now being developed in a separate [woocommerce/woocommerce-rest-api](https://github.com/woocommerce/woocommerce-rest-api) repo, so REST API related issues should be reported there.

I'm submitting a PR here (as [woocommerce-rest-api](https://github.com/woocommerce/woocommerce-rest-api) repo doesn't support legacy API), which should fix this issue on legacy endpoint but I'm unsure if it'll be merged in `master` eventually.

**Comment by rodrigoprimo** [comment]
See https://github.com/woocommerce/woocommerce/pull/24203
