### ISSUE TITLE
[REST API] list products with specific list of categories

### ISSUE THREAD

**Issue by vaawebdev** [woocommerce/woocommerce#24167]
I use wc rest api to make my shop page and I have a filter that includes a list of categories. When I filter products by categories I build my query like this
wp-json/wc/v3/products?category=17&category=19&category=26
and the problem is that there ARE products in this query, but when I try to access one specific category like:
wp-json/wc/v3/products?category=17
I get no products in this variant.
I would like to get an specific logic not OR (as far as i consider this logic is OR) but AND
Ive searched through internet and didnt find any solution!

**Comment by claudiosanches** [comment]
>  wp-json/wc/v3/products?category=17&category=19&category=26

This is not a valid query string, all values are replaced by the last one...
Please read the REST API documentation: https://woocommerce.github.io/woocommerce-rest-api-docs/

This parameter uses a list of IDs, so you can use `wp-json/wc/v3/products?category=17,19,26` or ` wp-json/wc/v3/products?category[]=17&category[]=19&category[]=26`.

> I would like to get an specific logic not OR (as far as i consider this logic is OR) but AND
> Ive searched through internet and didnt find any solution!

As I said, you are not even using a valid query string for your queries, better read the REST API docs first.

**Comment by vaawebdev** [comment]
The problem is that a category property while listing products is defined as a string, and i get error while trying to query  ?category[]=17&category[]=19 {"code":"rest_invalid_param","message":"Invalid parameter(s): category","data":{"status":400,"params":{"category":"category is not of type string."}}}
