### ISSUE TITLE
woocommerce_after_edit_attribute_fields outputs before attribute fields

### ISSUE THREAD

**Issue by nilsolofsson** [woocommerce/woocommerce#24162]
**Describe the bug**
When using action `woocommerce_after_edit_attribute_fields` add markup to the edit attribute view, the markup is added before all the edit fields, even if the action is suggesting it would be done after.

**To Reproduce**
1. Create an action like:
```php
add_action('woocommerce_after_edit_attribute_fields', function() {
    echo "<h1>Hello World</h1>";
});
```
2. Edit an attribute
3. See "Hello World" printed on the top of page before the rest of the fields

**Expected behavior**
Markup should be added after the attribute fields. Behaviour should be equivalent too `woocommerce_after_add_attribute_fields`.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

WordPress address (URL): http://localhost:8080
Site address (URL): http://localhost:8080
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: sv_SE
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.25 (Debian)
PHP Version: 7.2.12
PHP Post Max Size: 8 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.7.24
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Din server har inte SoapClient klassen aktiverad - betalmoduler som använder SOAP kanske inte kommer fungera som de skall.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ❌ MaxMind GeoIP-databasen saknas – Geolokalisering kommer inte att fungera. Du kan ladda ner och installera den manuellt från https://dev.maxmind.com/geoip/geoip2/geolite2/ till sökvägen: . Bläddra ned till ”Nedladdningar” och ladda ner filen ”MaxMind DB binary
gzipped” intill ”GeoLite2 Country”. Kom ihåg att packa upp filen GeoLite2-Country_xxxxxxxx.tar.gz och sedan endast ladda upp filen GeoLite2-Country.mmdb.

Total databasstorlek: 1.64MB
Datastorlek för databas: 0.70MB
Indexstorlek för databas: 0.94MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.08MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 0.14MB + Index: 0.02MB
wp_postmeta: Data: 0.02MB + Index: 0.03MB
wp_posts: Data: 0.02MB + Index: 0.06MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.02MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 1
page: 2
post: 2

### Security ###

Secure connection (HTTPS): ❌
					Din butik använder inte HTTPS. Lär dig mer om HTTPS och SSL-certifikat.
Hide errors from visitors: ✔

### Active Plugins (2) ###

Target product configurator: av En Appstudio – 0.0.1
WooCommerce: av Automattic – 3.6.5

### Inactive Plugins (2) ###

Akismet Anti-Spam: av Automattic – 4.0.8
Hello Dolly: av Matt Mullenweg – 1.7

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Butikbas: ❌ Sida har inte valts
Varukorg: ❌ Sida har inte valts
Kassan: ❌ Sida har inte valts
Mitt konto: ❌ Sida har inte valts
Allmänna villkor: ❌ Sida har inte valts

### Theme ###

Name: Twenty Seventeen
Version: 1.7 – 2.2 finns tillgänglig
Author URL: https://wordpress.org/
Child Theme: ❌ – Om du modifierar WooCommerce på ett modertema som du själv inte byggt
så rekommenderar vi att du använder ett barntema istället. Läs: Hur du skapar ett barntema

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 0
Oldest: –
Newest: –

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –
</details>

**Comment by malviyaritesh** [comment]
As you can see the `woocommerce_after_edit_attribute_fields` action is triggered just before the end tag of `tbody`.
https://github.com/woocommerce/woocommerce/blob/d03413178144097e4f7903592da41a35ce2ef419/includes/admin/class-wc-admin-attributes.php#L269-L270
So the output produced by hooked function should be appropriate to be placed inside `tbody` otherwise browser will render the content unexpectedly.

However, your hooked function produces `h1` (invalid inside `tbody`) which gets rendered before the `table`. The following should render at expected place, try by yourself:
```
add_action( 'woocommerce_after_edit_attribute_fields', function() {
	echo
		'<tr>' .
			'<th>Some Label:</th>' .
			'<td>Some Value</td>' .
		'</tr>';
} );
```

**Comment by nilsolofsson** [comment]
Ah, right. That explains it! Thanks @malviyaritesh!
