### ISSUE TITLE
REST API List products by multiple product categories

### ISSUE THREAD

**Issue by vaawebdev** [woocommerce/woocommerce#24179]
The problem is that I want to list products with multiple categories and the category parameter is defined as a string:
https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products
Is it possible somehow to list all products with two ore more specific categories

My query example:
?category[]=41&category[]=19
I get error:
{"code":"rest_invalid_param","message":"Invalid parameter(s): category","data":{"status":400,"params":{"category":"category is not of type string."}}}

If I query 
?category=41,19 
It fails to get correct data, just ignoring it as incorrect argument

**Comment by claudiosanches** [comment]
You need to use `?category=41,19`, but note that this is allow since REST API v2.
I have tested it and works just fine.

**Comment by dieptang** [comment]
Hello, Sorry for reopen, 
Seems it's OR condition, How Can I do with AND ?

**Comment by ScarefaceZ** [comment]
try with & instead of ,

**Comment by ScarefaceZ** [comment]
try ?category=41&category=19

**Comment by thebeard** [comment]
@dieptang Did you ever get the AND logic working?

**Comment by srflorea1** [comment]
I am also looking for the AND logic. Did anybody find a solution?

**Comment by josemiguelpestana** [comment]
Hello, i am also needing to filter the products by categories with AND logic. how can i achieve it?

**Comment by MatthewPageUK** [comment]
And another person looking for what appears to be simple request. AND condition on categories... 🤷‍♂️

**Comment by sinapirani** [comment]
i also need this 🤦‍♂️

**Comment by eightshone** [comment]
So, still no one has figured this one out?

**Comment by vaawebdev** [comment]
In my case, I just ended up creating my own custom rest endpoint with all required filters

**Comment by sendloveboxafrica** [comment]
> In my case, I just ended up creating my own custom rest endpoint with all required filters

Can you share how you did this?

**Comment by daguitosama** [comment]
Still is missing the AND option for the filtering logic. 
Anyone has figure it out and can point to a solution ?

**Comment by amirhosein-sa** [comment]
6years have passed, yet no solution has been provided.

**Comment by eightshone** [comment]
@amirhosein-sa I have worked a couple of years ago on a project using woocommerce and I had to program most of the apis
