### ISSUE TITLE
Out of stock product get new url?

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce#24174]
Maybe it’s first time I recognized this behavior but I like to ask about if it is correct:

I have setup a product with stock handling of 1 item. After it is sold it should stay in shop but can not be back ordered.

I have such a product and I was wondering why it changed it url from product name to …/__trashed/

Is this a normal behavior and does it count against trashed for other products which are sold out?

And I was wondering too why WC Wishlists still let me put that product into wishlist?

I am with WC 3.6.5 abd the product can be found here: https://dekuenst.de/produkt/__trashed/

**Comment by rodrigoprimo** [comment]
> I have such a product and I was wondering why it changed it url from product name to …/__trashed/

The URL of the product should not change. I'm not sure why this happens and at a first look I don't think this is a WooCommerce core bug. If you are able to reproduce this problem on a clean WooCommerce core install, please open another issue following the bug report template with the steps to recreate the problem and we will take a look.

> And I was wondering too why WC Wishlists still let me put that product into wishlist?

This GitHub repository is used exclusively for WooCommerce core. If you are a paying WooCommerce.com customer, you could contact their support to ask your question about WooCommerce Wishlists: http://woocommerce.com/contact-us/
