### ISSUE TITLE
Import images  on product import.

### ISSUE THREAD

**Issue by ModenDev** [woocommerce/woocommerce#24189]
It would be good if the product import/export tool would export/import images directly. There are plenty of third party plugins that do this, but they are very expensive and this seems like an obvious feature for a product import/export tool. Please consider adding this to the woocommerce import tool

**Comment by kloon** [comment]
> export/import images directly

Can you elaborate a bit more on what you mean with directly? Currently, if you specify a URL/s in the images field and it is hosted on an external site the images will be copied over to your site where you are importing from.

**Comment by ModenDev** [comment]
Do I have to specify that manually via the csv or is it an option on the admin screen when exporting?

Its just that Woocommerce support said that this feature doesn’t exist

**Comment by kloon** [comment]
You will simply include the full url to the image as it is hosted on an external site.

So say store 1 at http://store1.example.com/ have the images and you are importing the file on store 2 at https://store2.example.com/ then the import file will just need to have the full urls of the image as they are hosted on store 1, eg https://store1.example.com/wp-content/uploads/2019/07/image.jpg and then when you import the file that image will be copied from that URL to the site you are busy importing on.

[Please read this document for more details on importing images](https://docs.woocommerce.com/document/product-csv-import-suite-faq-troubleshooting/#section-9)

**Comment by ModenDev** [comment]
Yeah that works.

I cant tell you why I was told it doesn’t.

Thanks
