### ISSUE TITLE
Shipping Zones: Duplicate zip codes result in error

### ISSUE THREAD

**Issue by ronlum** [woocommerce/woocommerce#24180]
**Describe the bug**
I recently updated to the latest Woocommerce version, 3.65. I was coming from v2, so the shipping zones feature was new to me. I had compiled a ton of zip codes, zones, and names in a spreadsheet, then input them into the Shipping Zones. I did not realize I had duplicate zip codes at the time (some for the same zone, some for different zones). Regardless, both situations resulted in certain valid zip codes when entered at the cart page, to not show it recognized as a zone and instead had a message "No shipping options were found for". This did not affect all zip codes, only a minority (the correlation is unclear). 

**To Reproduce**
1. Go to WOOCOMMERCE > SETTINGS> SHIPPING > SHIPPING ZONES
2. Create multiple zones, with multiple zip codes in each zone, but ensure there are duplicates and some same zip codes within different zones.
3. Notice there will be no error. Now go add something to your cart, during the cart shipping calculation, play with some of those zip codes. Some valid ones should give an error. 

**Isolating the problem (mark completed items with an [x]):**
- [] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Wordpress v4.9.7
Woocommerce v3.65

**Comment by claudiosanches** [comment]
> Create multiple zones, with multiple zip codes in each zone, but ensure there are duplicates and some same zip codes within different zones.

Doing it will select the first match for the zip code entered in the cart. That's why is not showing any error message, will pick the first match, so better you fix all duplicated zip codes.

**Comment by ronlum** [comment]
It actually did not select a zone, but rather, it would tell me there was no options for the selected zip code. This sort of error is why I was concerned about it. Thanks Claudio.
