### ISSUE TITLE
After refunding an existing order, new order number is messed up 

### ISSUE THREAD

**Issue by avish-bisbeehurry-cko** [woocommerce/woocommerce#24182]
After performing a refund on an existing order (payment done using COD), the next new order number is incremented by 2-3 numbers. 

1. Complete a transaction using any payment method (I used COD). Order number = 201
2. Go to the order (201) on the backend and click on "Refund button" (order got updated succesfully)
3. Try to complete payment using COD again. Order completed successfully. However, instead of getting new order number as 202, I received 203

**Expected behavior**
New order status should not incremented after a refund

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

WordPress address (URL): |   | http://localhost/wordpress-5.0.2/wordpress
-- | -- | --
Site address (URL): |   | http://localhost/wordpress-5.0.2/wordpress
WooCommerce version: |   | 3.6.5
Log directory writable: |   | C:\wamp64\www\wordpress-5.0.2\wordpress/wp-content/uploads/wc-logs/
WordPress version: |   | 5.2.2
WordPress multisite: |   | –
WordPress memory limit: |   | 256 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –

**Comment by rodrigoprimo** [comment]
Orders IDs are not sequential in WooCommerce. The plugin uses the WordPress table wp_posts to store orders and this means that the IDs are shared with all other post types. Order refunds are also stored in wp_posts. If you would like to have sequential order IDs, you will need an extension like [Sequential Order Numbers Pro](https://woocommerce.com/products/sequential-order-numbers-pro/).
