### ISSUE TITLE
Products not displaying on store or by category.

### ISSUE THREAD

**Issue by WendyTheRed** [woocommerce/woocommerce#24186]
With Woocommerce 3.6.5 none of our older products are showing. New products still show as those are in a slider. Likewise, we have a bundle plugin and those show. Sorting by categories doesn't do anything either. I've cleared caches and regenerated permalinks to no avail. I've included my status report below:

`
### WordPress Environment ###

WordPress address (URL): http://amazingtransformationcomics.com
Site address (URL): http://amazingtransformationcomics.com
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.7
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.65.1
OpenSSL/1.0.2s

SUHOSIN Installed: –
MySQL Version: 5.5.64-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: dz82l3lls_
Total Database Size: 5105.92MB
Database Data Size: 4932.68MB
Database Index Size: 173.24MB
dz82l3lls_woocommerce_sessions: Data: 4676.92MB + Index: 75.73MB
dz82l3lls_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
dz82l3lls_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
dz82l3lls_woocommerce_downloadable_product_permissions: Data: 4.20MB + Index: 4.27MB
dz82l3lls_woocommerce_order_items: Data: 2.05MB + Index: 1.19MB
dz82l3lls_woocommerce_order_itemmeta: Data: 20.40MB + Index: 14.95MB
dz82l3lls_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
dz82l3lls_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
dz82l3lls_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
dz82l3lls_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
dz82l3lls_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
dz82l3lls_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
dz82l3lls_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
dz82l3lls_woocommerce_log: Data: 0.02MB + Index: 0.02MB
dz82l3lls_clickfraudmonitor: Data: 0.00MB + Index: 0.00MB
dz82l3lls_commentmeta: Data: 0.86MB + Index: 0.61MB
dz82l3lls_comments: Data: 8.05MB + Index: 3.76MB
dz82l3lls_links: Data: 0.00MB + Index: 0.00MB
dz82l3lls_newsletter: Data: 0.01MB + Index: 0.01MB
dz82l3lls_newsletter_emails: Data: 0.00MB + Index: 0.00MB
dz82l3lls_newsletter_stats: Data: 0.00MB + Index: 0.00MB
dz82l3lls_options: Data: 82.88MB + Index: 11.09MB
dz82l3lls_postmeta: Data: 44.10MB + Index: 26.95MB
dz82l3lls_posts: Data: 8.02MB + Index: 2.24MB
dz82l3lls_revslider_css: Data: 0.11MB + Index: 0.00MB
dz82l3lls_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
dz82l3lls_revslider_navigations: Data: 0.02MB + Index: 0.00MB
dz82l3lls_revslider_sliders: Data: 0.02MB + Index: 0.00MB
dz82l3lls_revslider_slides: Data: 0.02MB + Index: 0.00MB
dz82l3lls_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
dz82l3lls_termmeta: Data: 0.02MB + Index: 0.03MB
dz82l3lls_terms: Data: 0.00MB + Index: 0.01MB
dz82l3lls_term_relationships: Data: 0.14MB + Index: 0.27MB
dz82l3lls_term_taxonomy: Data: 0.01MB + Index: 0.01MB
dz82l3lls_usermeta: Data: 5.65MB + Index: 3.41MB
dz82l3lls_users: Data: 0.36MB + Index: 0.39MB
dz82l3lls_wcpv_commissions: Data: 6.52MB + Index: 0.00MB
dz82l3lls_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB
dz82l3lls_wc_download_log: Data: 0.08MB + Index: 0.03MB
dz82l3lls_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
dz82l3lls_wc_webhooks: Data: 0.02MB + Index: 0.02MB
dz82l3lls_wfBlockedIPLog: Data: 1.03MB + Index: 0.00MB
dz82l3lls_wfBlocks7: Data: 0.02MB + Index: 0.05MB
dz82l3lls_wfConfig: Data: 1.39MB + Index: 0.00MB
dz82l3lls_wfCrawlers: Data: 0.02MB + Index: 0.00MB
dz82l3lls_wfFileChanges: Data: 0.02MB + Index: 0.00MB
dz82l3lls_wfFileMods: Data: 3.52MB + Index: 0.00MB
dz82l3lls_wfHits: Data: 1.02MB + Index: 1.17MB
dz82l3lls_wfHoover: Data: 1.52MB + Index: 0.16MB
dz82l3lls_wfIssues: Data: 0.02MB + Index: 0.06MB
dz82l3lls_wfKnownFileList: Data: 1.52MB + Index: 0.00MB
dz82l3lls_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB
dz82l3lls_wfLocs: Data: 0.02MB + Index: 0.00MB
dz82l3lls_wfLogins: Data: 1.02MB + Index: 0.03MB
dz82l3lls_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB
dz82l3lls_wfls_settings: Data: 0.02MB + Index: 0.00MB
dz82l3lls_wfNotifications: Data: 0.02MB + Index: 0.00MB
dz82l3lls_wfPendingIssues: Data: 0.02MB + Index: 0.06MB
dz82l3lls_wfReverseCache: Data: 0.02MB + Index: 0.00MB
dz82l3lls_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
dz82l3lls_wfStatus: Data: 0.16MB + Index: 0.13MB
dz82l3lls_wfTrafficRates: Data: 0.02MB + Index: 0.00MB
dz82l3lls_woocommerce_bundled_itemmeta: Data: 0.09MB + Index: 0.11MB
dz82l3lls_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB
dz82l3lls_yith_wcwl: Data: 0.00MB + Index: 0.00MB
dz82l3lls_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB
dz82l3lls_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
dz82l3lls_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB
vp_backup_dz82l3lls_clickfraudmonitor: Data: 0.00MB + Index: 0.00MB
vp_backup_dz82l3lls_commentmeta: Data: 0.83MB + Index: 0.65MB
vp_backup_dz82l3lls_comments: Data: 3.25MB + Index: 1.34MB
vp_backup_dz82l3lls_itsec_lockouts: Data: 0.02MB + Index: 0.08MB
vp_backup_dz82l3lls_itsec_log: Data: 9.52MB + Index: 0.41MB
vp_backup_dz82l3lls_itsec_temp: Data: 0.05MB + Index: 0.06MB
vp_backup_dz82l3lls_links: Data: 0.00MB + Index: 0.00MB
vp_backup_dz82l3lls_newsletter: Data: 0.01MB + Index: 0.01MB
vp_backup_dz82l3lls_newsletter_emails: Data: 0.00MB + Index: 0.00MB
vp_backup_dz82l3lls_newsletter_stats: Data: 0.00MB + Index: 0.00MB
vp_backup_dz82l3lls_options: Data: 5.23MB + Index: 0.42MB
vp_backup_dz82l3lls_postmeta: Data: 21.64MB + Index: 12.83MB
vp_backup_dz82l3lls_posts: Data: 7.69MB + Index: 1.84MB
vp_backup_dz82l3lls_terms: Data: 0.00MB + Index: 0.01MB
vp_backup_dz82l3lls_term_relationships: Data: 0.11MB + Index: 0.25MB
vp_backup_dz82l3lls_term_taxonomy: Data: 0.01MB + Index: 0.01MB
vp_backup_dz82l3lls_usermeta: Data: 2.62MB + Index: 1.61MB
vp_backup_dz82l3lls_users: Data: 0.22MB + Index: 0.11MB
vp_backup_dz82l3lls_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
vp_backup_dz82l3lls_woocommerce_downloadable_product_permissions: Data: 1.89MB + Index: 1.42MB
vp_backup_dz82l3lls_woocommerce_order_itemmeta: Data: 6.37MB + Index: 4.56MB
vp_backup_dz82l3lls_woocommerce_order_items: Data: 0.92MB + Index: 0.45MB
vp_backup_dz82l3lls_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
vp_backup_dz82l3lls_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
vp_backup_dz82l3lls_woocommerce_termmeta: Data: 0.01MB + Index: 0.01MB
vp_backup_dz82l3lls_yith_wcwl: Data: 0.00MB + Index: 0.00MB

### Post Type Counts ###

amn_mi-lite: 3
attachment: 1265
custom_css: 2
jetpack_migration: 2
nav_menu_item: 13
page: 27
post: 1
product: 170
revision: 455
safecss: 1
scheduled-action: 159
shop_commission: 2788
shop_coupon: 138
shop_order: 20359
shop_order_refund: 30

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (24) ###

WooCommerce OrbitalPay payment gateway: by bcrawford – .5 – Not tested with the active version of WooCommerce
AdSense Click-Fraud Monitoring Plugin: by Rene Hermenau – 1.8.4
Akismet Anti-Spam: by Automattic – 4.1.2
BackupBuddy: by iThemes – 4.2.16.4
Enhanced Media Library: by wpUXsolutions – 2.7.2
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.7.1
Heartbeat Control by WP Rocket: by WP Rocket – 1.2.5
Jetpack by WordPress.com: by Automattic – 7.5.3
Limit Login Attempts: by Johan Eenfeldt – 1.7.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.1
Widget Importer & Exporter: by ChurchThemes.com – 1.5.5
WooCommerce Admin Bar Addition: by David Decker - DECKERWEB – 2.7.0 – Not tested with the active version of WooCommerce
WooCommerce Colors: by WooThemes – 1.0.7 – Not tested with the active version of WooCommerce
WooCommerce Grid / List toggle: by jameskoster – 1.2.1 – Not tested with the active version of WooCommerce
WooCommerce Product Bundles: by SomewhereWarm – 5.4.0 – Not tested with the active version of WooCommerce
WooCommerce Product Vendors: by WooCommerce – 2.0.30 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.6.5
Wordfence Security: by Wordfence – 7.3.5
WordPress Importer: by wordpressdotorg – 0.6.4
Yoast SEO: by Team Yoast – 11.6 – Not tested with the active version of WooCommerce
WP Crontrol: by John Blackbourn & crontributors – 1.7.1
WP Rollback: by Impress.org – 1.6
WP Super Cache: by Automattic – 1.6.8
YITH WooCommerce Best Sellers Premium: by YITHEMES – 1.1.0 – Not tested with the active version of WooCommerce

### Inactive Plugins (5) ###

Slider Revolution: by ThemePunch – 5.2.5.3
VaultPress: by Automattic – 2.0.1
WooCommerce Helper: by WooCommerce – 1.7.2 – Not tested with the active version of WooCommerce – Network enabled
YITH WooCommerce Ajax Search: by YITH – 1.6.8
YITH WooCommerce Zoom Magnifier: by YITH – 1.3.10

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #62 - /store/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #300 - /legal-notices/

### Theme ###

Name: My PrimaShop (WC)
Version: 1.1
Author URL: http://www.yoururl.com
Child Theme: ✔
Parent Theme Name: PrimaShop (WC)
Parent Theme Version: 1.8.3
Parent Theme Author URL: http://www.primathemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 158
Oldest: 2019-06-19 21:31:14 -0500
Newest: 2019-07-17 12:30:04 -0500

Pending: 1
Oldest: 2019-07-17 12:30:05 -0500
Newest: 2019-07-17 12:30:05 -0500

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by rodrigoprimo** [comment]
Hi there!

GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/

If you believe your problem is caused by a WooCommerce core bug, please open a new issue following the [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=) and include the steps for us to reproduce the issue on a clean WooCommerce install. Thanks.
