### ISSUE TITLE
PHPUnit 6 is out of support

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#24192]
We should update our unit test framework to make it compatible with PHPUnit 7+. Currently, PHPUnit is pinned to version 6.5 and that version is already out of support.

**Comment by claudiosanches** [comment]
Should be fine doing it, since we drop support for legacy versions of PHP.

**Comment by rrennick** [comment]
I think the hold up on this is that the WordPress unit test lib isn't compatible with PHPUnit 7+.

**Comment by rodrigoprimo** [comment]
@rrennick I didn't test, but I believe that the WordPress unit test library is now compatible with PHPUnit 7+. At least the WP core ticket that I was following about that was closed a few weeks ago: https://core.trac.wordpress.org/ticket/43218

**Comment by claudiosanches** [comment]
See https://github.com/woocommerce/woocommerce/pull/24197
