### ISSUE TITLE
wc_load_cart gives fatal error, when called before "init" fx. on "woocommerce_loaded"

### ISSUE THREAD

**Issue by jespervnielsen** [woocommerce/woocommerce#24190]
**Is your feature request related to a problem? Please describe.**
When calling wc_load_cart on "woocommerce_loaded" it gives fatal error, because countries isnt't setup at that point, and therefor ´null´

> Fatal error: Uncaught Error: Call to a member function get_allowed_countries() on null in /host/www/pcschematic/frontend/wp-content/plugins/woocommerce/includes/wc-core-functions.php:1136
> Stack trace:
> #0 /host/www/pcschematic/frontend/wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php(128): wc_get_customer_default_location()
> #1 /host/www/pcschematic/frontend/wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php(117): WC_Customer_Data_Store_Session->set_defaults(Object(WC_Customer))
> #2 /host/www/pcschematic/frontend/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): WC_Customer_Data_Store_Session->read(Object(WC_Customer))
> #3 /host/www/pcschematic/frontend/wp-content/plugins/woocommerce/includes/class-wc-customer.php(116): WC_Data_Store->read(Object(WC_Customer))
> #4 /host/www/pcschematic/frontend/wp-content/plugins/woocommerce/includes/class-woocommerce.php(739): WC_Customer->__construct(0, true)
> #5 /host/www/pcschematic/fro in /host/www/pcschematic/frontend/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 1136

**Describe the solution you'd like**
either it should work, or at least check if "init" or similar is run, and create an error, that the function was called to early.

**Additional context**
![image](https://user-images.githubusercontent.com/31649178/61455014-b7f9c780-a962-11e9-90da-07cfe93a63e7.png)

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24198.
