### ISSUE TITLE
Store categories not working

### ISSUE THREAD

**Issue by lincolnboxdotcom** [woocommerce/woocommerce#24209]
**Describe the bug**
Links to view the products by category do not work. When clicked, they display the default all categories at once.

I am not good with internet technology and it is difficult for me just to figure out how to fill this form out

**To Reproduce**
1. Go to '...' www.lincolnbox.com
2. Click on '....' Coin Box Single Purchases or any other store category link
3. Scroll down to '....' store categories may be at the end of the page
4. See error when clicked they dont display the products by category

**Screenshots**

**Expected behavior**
For the products to be displayed by store category when click on links for store categories

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
`
### WordPress Environment ###

WordPress address (URL): https://lincolnbox.com
Site address (URL): https://lincolnbox.com
WC Version: 3.6.4
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: ❌ 40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.15
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.45.0
OpenSSL/1.0.1e

SUHOSIN Installed: –
MySQL Version: 5.6.32-78.0-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.4
WC Database Prefix: wp_bd3m4vbwxg_
MaxMind GeoIP Database: ✔
Total Database Size: 5.53MB
Database Data Size: 4.81MB
Database Index Size: 0.72MB
wp_bd3m4vbwxg_woocommerce_sessions: Data: 1.52MB + Index: 0.02MB
wp_bd3m4vbwxg_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_bd3m4vbwxg_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB
wp_bd3m4vbwxg_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_bd3m4vbwxg_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_bd3m4vbwxg_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.01MB
wp_bd3m4vbwxg_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_bd3m4vbwxg_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_bd3m4vbwxg_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_bd3m4vbwxg_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_bd3m4vbwxg_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_bd3m4vbwxg_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_bd3m4vbwxg_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_bd3m4vbwxg_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_bd3m4vbwxg_commentmeta: Data: 0.04MB + Index: 0.03MB
wp_bd3m4vbwxg_comments: Data: 0.12MB + Index: 0.09MB
wp_bd3m4vbwxg_gf_draft_submissions: Data: 0.00MB + Index: 0.00MB
wp_bd3m4vbwxg_gf_entry: Data: 0.00MB + Index: 0.00MB
wp_bd3m4vbwxg_gf_entry_meta: Data: 0.00MB + Index: 0.00MB
wp_bd3m4vbwxg_gf_entry_notes: Data: 0.00MB + Index: 0.00MB
wp_bd3m4vbwxg_gf_form: Data: 0.00MB + Index: 0.00MB
wp_bd3m4vbwxg_gf_form_meta: Data: 0.00MB + Index: 0.00MB
wp_bd3m4vbwxg_gf_form_revisions: Data: 0.00MB + Index: 0.00MB
wp_bd3m4vbwxg_gf_form_view: Data: 0.00MB + Index: 0.00MB
wp_bd3m4vbwxg_links: Data: 0.00MB + Index: 0.00MB
wp_bd3m4vbwxg_nf3_actions: Data: 0.02MB + Index: 0.00MB
wp_bd3m4vbwxg_nf3_action_meta: Data: 0.02MB + Index: 0.00MB
wp_bd3m4vbwxg_nf3_chunks: Data: 0.02MB + Index: 0.00MB
wp_bd3m4vbwxg_nf3_fields: Data: 0.02MB + Index: 0.00MB
wp_bd3m4vbwxg_nf3_field_meta: Data: 0.02MB + Index: 0.00MB
wp_bd3m4vbwxg_nf3_forms: Data: 0.02MB + Index: 0.00MB
wp_bd3m4vbwxg_nf3_form_meta: Data: 0.02MB + Index: 0.00MB
wp_bd3m4vbwxg_nf3_objects: Data: 0.02MB + Index: 0.00MB
wp_bd3m4vbwxg_nf3_object_meta: Data: 0.02MB + Index: 0.00MB
wp_bd3m4vbwxg_nf3_relationships: Data: 0.02MB + Index: 0.00MB
wp_bd3m4vbwxg_nf3_upgrades: Data: 0.02MB + Index: 0.00MB
wp_bd3m4vbwxg_options: Data: 2.06MB + Index: 0.05MB
wp_bd3m4vbwxg_postmeta: Data: 0.40MB + Index: 0.11MB
wp_bd3m4vbwxg_posts: Data: 0.26MB + Index: 0.10MB
wp_bd3m4vbwxg_termmeta: Data: 0.00MB + Index: 0.01MB
wp_bd3m4vbwxg_terms: Data: 0.00MB + Index: 0.01MB
wp_bd3m4vbwxg_term_relationships: Data: 0.01MB + Index: 0.03MB
wp_bd3m4vbwxg_term_taxonomy: Data: 0.00MB + Index: 0.01MB
wp_bd3m4vbwxg_usermeta: Data: 0.02MB + Index: 0.01MB
wp_bd3m4vbwxg_users: Data: 0.00MB + Index: 0.01MB
wp_bd3m4vbwxg_wc_admin_notes: Data: 0.00MB + Index: 0.00MB
wp_bd3m4vbwxg_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB
wp_bd3m4vbwxg_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB
wp_bd3m4vbwxg_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_bd3m4vbwxg_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB
wp_bd3m4vbwxg_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB
wp_bd3m4vbwxg_wc_order_stats: Data: 0.00MB + Index: 0.01MB
wp_bd3m4vbwxg_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB
wp_bd3m4vbwxg_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB
wp_bd3m4vbwxg_wc_webhooks: Data: 0.02MB + Index: 0.02MB

### Post Type Counts ###

attachment: 75
customize_changeset: 10
nav_menu_item: 5
nf_sub: 4
page: 8
post: 2
product: 50
product_variation: 4
revision: 43
scheduled-action: 326
shop_order: 3
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

Gravity Forms: by rocketgenius – 2.4.10
All In One SEO Pack: by Michael Torbert – 3.1.1
Contact Widgets: by GoDaddy – 1.6.1
Google XML Sitemaps: by Arne Brachhold – 4.1.0
Ninja Forms: by The WP Ninjas – 3.4.4
Storefront Product Pagination: by WooThemes – 1.2.4 – Not tested with the active version of WooCommerce
Storefront Product Sharing: by WooCommerce – 1.0.6
Storefront Sticky Add to Cart: by WooThemes – 1.1.9
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.21
WooCommerce Blocks: by Automattic – 2.2.0
WooCommerce Admin: by WooCommerce – 0.14.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.15 – 1.6.16 is available
WooCommerce: by Automattic – 3.6.4 – 3.6.5 is available
WP101 Video Tutorials: by WP101Plugin.com – 0.3

### Dropin Plugins (1) ###

object-cache.php: APCu Object Cache

### Must Use Plugins (1) ###

System Plugin: by  – 3.9.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: #263 - /privacy-policy/

### Theme ###

Name: Storefront
Version: 2.4.3 – 2.5.1 is available
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 325
Oldest: 2019-06-30 18:02:38 -0400
Newest: 2019-07-19 13:03:00 -0400

Pending: 1
Oldest: 2019-07-19 14:03:00 -0400
Newest: 2019-07-19 14:03:00 -0400

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

</details>

**Comment by rodrigoprimo** [comment]
Hi there!

GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal so, unfortunately, we cannot help you debug the problem you are having on your site. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/

**Comment by lincolnboxdotcom** [comment]
Greetings

My website crashed last week with wordpress saying woocommerce app caused a
"fatal error". Is this something you can give recommendations on how to
avoid happening again? here is a copy of the text below. I am using the
storefront theme which says is developed by woocommerce.


Since WordPress 5.2 there is a built-in feature that detects when a plugin
or theme causes a fatal error on your site, and notifies you with this
automated email.

In this case, WordPress caught an error with one of your plugins,
WooCommerce.

First, visit your website (https://lincolnbox.com/) and check for any
visible issues. Next, visit the page where the error was caught (
https://lincolnbox.com/wp-login.php) and check for any visible issues.

Please contact your host for assistance with investigating this issue
further.

If your site appears broken and you can't access your dashboard normally,
WordPress now has a special "recovery mode". This lets you safely login to
your dashboard and investigate further.

https://lincolnbox.com/wp-login.php?action=enter_recovery_mode&rm_token=pLkrCsTk0qsVVAdb2VSYii&rm_key=lu2ZJ3jADfl4Qa3SBMd8Fr

To keep your site safe, this link will expire in 1 day. Don't worry about
that, though: a new link will be emailed to you if the error occurs again
after it expires.



Error Details
=============
An error of type E_ERROR was caused in line 34 of the file
/home/content/p3pnexwpnas14_data01/80/42678380/html/wp-content/plugins/woocommerce/woocommerce.php.
Error message: Uncaught Error: Class 'WooCommerce' not found in
/home/content/p3pnexwpnas14_data01/80/42678380/html/wp-content/plugins/woocommerce/woocommerce.php:34
Stack trace:
#0
/home/content/p3pnexwpnas14_data01/80/42678380/html/wp-content/plugins/woocommerce/woocommerce.php(38):
WC()
#1
/home/content/p3pnexwpnas14_data01/80/42678380/html/wp-settings.php(362):
include_once('/home/content/p...')
#2 /home/content/p3pnexwpnas14_data01/80/42678380/html/wp-config.php(98):
require_once('/home/content/p...')
#3 /home/content/p3pnexwpnas14_data01/80/42678380/html/wp-load.php(37):
require_once('/home/content/p...')
#4 /home/content/p3pnexwpnas14_data01/80/42678380/html/wp-login.php(12):
require('/home/content/p...')
#5 {main}
  thrown

**Comment by rodrigoprimo** [comment]
Thanks for the additional information, @lincolnboxdotcom. Judging by the PHP error you shared, this still doesn't look like a WooCommerce bug.
