### ISSUE TITLE
Product-tags with no associated products cause Server 'Bad Gateway - 502' Error

### ISSUE THREAD

**Issue by visualpropaganda** [woocommerce/woocommerce#24210]
**Describe the bug**
PHP 7.3.1 was constantly crashing and restarting on our Server. The Error-Log is:

`[error] 32730#32730: *877 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 91.14.163.247, server: edelmix.de, request: "GET /produkt-schlagwort/camcross/ HTTP/2.0", upstream: "fastcgi://unix:/var/lib/php5-fpm/web3.sock:", host: "edelmix.de", referrer: "https://edelmix.de/wp-admin/edit-tags.php?taxonomy=product_tag&post_type=product&orderby=count&order=asc"
`
We were able to solve this by deleting all product-tags with the count of 0.
This problem started with the latest version of woocommerce 3.6.5.
The product-tags didn't cause any problems before the update.

**To Reproduce**
1. Go to 'Product Tags'
2. Create New Product Tag
3. Try to view/preview the new created 'Product Tag'. which is not associated with any product.
4. Server/browser returns 502 - Bad Gateway
5. PHP crashes and restarts

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
`
### WordPress Environment ###

WordPress address (URL): https://edelmix.de
Site address (URL): https://edelmix.de
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: nginx/1.14.0
PHP Version: 7.3.1
PHP Post Max Size: 100 MB
PHP Time Limit: 180
PHP Max Input Vars: 4200
cURL Version: 7.52.1
OpenSSL/1.0.2s

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.37-MariaDB-1~stretch
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 206.59MB
Datenbank-Datengröße: 160.55MB
Datenbank-Indexgröße: 46.04MB
wp_woocommerce_sessions: Daten: 14.02MB + Index: 1.28MB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Daten: 0.00MB + Index: 0.01MB
wp_woocommerce_downloadable_product_permissions: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Daten: 0.20MB + Index: 0.12MB
wp_woocommerce_order_itemmeta: Daten: 2.98MB + Index: 1.15MB
wp_woocommerce_tax_rates: Daten: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Daten: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB
wp_adtribes_my_conversions: Daten: 0.02MB + Index: 0.02MB
wp_all_around: Daten: 0.00MB + Index: 0.00MB
wp_all_around_thmb: Daten: 0.00MB + Index: 0.00MB
wp_aws_index: Daten: 13.52MB + Index: 0.00MB
wp_chanimator: Daten: 0.02MB + Index: 0.00MB
wp_cmeb_free_domains: Daten: 0.13MB + Index: 0.00MB
wp_cmeb_userlist: Daten: 0.02MB + Index: 0.00MB
wp_commentmeta: Daten: 0.01MB + Index: 0.01MB
wp_comments: Daten: 1.09MB + Index: 0.43MB
wp_csshero: Daten: 0.02MB + Index: 0.00MB
wp_eum_logs: Daten: 0.08MB + Index: 0.00MB
wp_faq_termmeta: Daten: 0.01MB + Index: 0.00MB
wp_icl_content_status: Daten: 0.00MB + Index: 0.00MB
wp_icl_core_status: Daten: 0.00MB + Index: 0.00MB
wp_icl_flags: Daten: 0.00MB + Index: 0.00MB
wp_icl_languages: Daten: 0.00MB + Index: 0.01MB
wp_icl_languages_translations: Daten: 0.10MB + Index: 0.11MB
wp_icl_locale_map: Daten: 0.00MB + Index: 0.00MB
wp_icl_message_status: Daten: 0.00MB + Index: 0.00MB
wp_icl_node: Daten: 0.00MB + Index: 0.00MB
wp_icl_reminders: Daten: 0.00MB + Index: 0.00MB
wp_icl_strings: Daten: 0.00MB + Index: 0.00MB
wp_icl_string_positions: Daten: 0.00MB + Index: 0.00MB
wp_icl_string_status: Daten: 0.00MB + Index: 0.00MB
wp_icl_string_translations: Daten: 0.00MB + Index: 0.00MB
wp_icl_translate: Daten: 0.29MB + Index: 0.01MB
wp_icl_translate_job: Daten: 0.00MB + Index: 0.01MB
wp_icl_translations: Daten: 0.03MB + Index: 0.07MB
wp_icl_translation_batches: Daten: 0.02MB + Index: 0.00MB
wp_icl_translation_status: Daten: 0.00MB + Index: 0.00MB
wp_itsec_distributed_storage: Daten: 4.52MB + Index: 0.02MB
wp_itsec_fingerprints: Daten: 0.02MB + Index: 0.03MB
wp_itsec_geolocation_cache: Daten: 0.02MB + Index: 0.03MB
wp_itsec_lockouts: Daten: 0.02MB + Index: 0.08MB
wp_itsec_log: Daten: 6.52MB + Index: 0.03MB
wp_itsec_logs: Daten: 2.02MB + Index: 0.13MB
wp_itsec_temp: Daten: 0.02MB + Index: 0.06MB
wp_links: Daten: 0.00MB + Index: 0.00MB
wp_masterslider_options: Daten: 0.06MB + Index: 0.02MB
wp_masterslider_sliders: Daten: 0.19MB + Index: 0.03MB
wp_nxs_log: Daten: 0.09MB + Index: 0.00MB
wp_options: Daten: 9.19MB + Index: 0.45MB
wp_pmxe_exports: Daten: 0.20MB + Index: 0.00MB
wp_pmxe_google_cats: Daten: 0.39MB + Index: 0.00MB
wp_pmxe_posts: Daten: 0.28MB + Index: 0.00MB
wp_pmxe_templates: Daten: 0.09MB + Index: 0.00MB
wp_postmeta: Daten: 61.67MB + Index: 12.94MB
wp_posts: Daten: 6.28MB + Index: 1.49MB
wp_PO_plugins: Daten: 0.02MB + Index: 0.03MB
wp_prli_clicks: Daten: 0.02MB + Index: 0.19MB
wp_prli_groups: Daten: 0.02MB + Index: 0.02MB
wp_prli_links: Daten: 0.02MB + Index: 0.16MB
wp_prli_link_metas: Daten: 0.02MB + Index: 0.03MB
wp_psu_redirects: Daten: 0.48MB + Index: 0.33MB
wp_psu_terms: Daten: 0.02MB + Index: 0.02MB
wp_relevanssi: Daten: 10.55MB + Index: 16.06MB
wp_relevanssi_log: Daten: 0.02MB + Index: 0.00MB
wp_relevanssi_stopwords: Daten: 0.06MB + Index: 0.00MB
wp_revslider_css: Daten: 0.05MB + Index: 0.00MB
wp_revslider_layer_animations: Daten: 0.02MB + Index: 0.00MB
wp_revslider_settings: Daten: 0.02MB + Index: 0.00MB
wp_revslider_sliders: Daten: 0.02MB + Index: 0.00MB
wp_revslider_slides: Daten: 0.14MB + Index: 0.00MB
wp_revslider_static_slides: Daten: 0.02MB + Index: 0.00MB
wp_rg_form: Daten: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Daten: 0.02MB + Index: 0.00MB
wp_rg_form_view: Daten: 0.06MB + Index: 0.03MB
wp_rg_incomplete_submissions: Daten: 0.02MB + Index: 0.02MB
wp_rg_lead: Daten: 0.02MB + Index: 0.03MB
wp_rg_lead_detail: Daten: 0.02MB + Index: 0.06MB
wp_rg_lead_detail_long: Daten: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Daten: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Daten: 0.02MB + Index: 0.03MB
wp_social_users: Daten: 0.00MB + Index: 0.00MB
wp_tcb_api_error_log: Daten: 0.02MB + Index: 0.00MB
wp_td_fields: Daten: 0.02MB + Index: 0.00MB
wp_td_groups: Daten: 0.02MB + Index: 0.00MB
wp_termmeta: Daten: 3.44MB + Index: 0.58MB
wp_terms: Daten: 0.21MB + Index: 0.28MB
wp_term_relationships: Daten: 0.74MB + Index: 1.32MB
wp_term_taxonomy: Daten: 0.23MB + Index: 0.23MB
wp_tm_taskmeta: Daten: 0.02MB + Index: 0.03MB
wp_tm_tasks: Daten: 0.02MB + Index: 0.02MB
wp_toolset_associations: Daten: 0.02MB + Index: 0.05MB
wp_toolset_post_guid_id: Daten: 0.28MB + Index: 0.23MB
wp_toolset_relationships: Daten: 0.02MB + Index: 0.08MB
wp_toolset_type_sets: Daten: 0.02MB + Index: 0.03MB
wp_tve_leads_contacts: Daten: 0.05MB + Index: 0.00MB
wp_tve_leads_contact_download: Daten: 0.02MB + Index: 0.00MB
wp_tve_leads_event_log: Daten: 9.52MB + Index: 6.03MB
wp_tve_leads_form_variations: Daten: 1.52MB + Index: 0.06MB
wp_tve_leads_group_options: Daten: 0.02MB + Index: 0.00MB
wp_tve_leads_saved_group_options: Daten: 0.02MB + Index: 0.00MB
wp_tve_leads_split_test: Daten: 0.02MB + Index: 0.00MB
wp_tve_leads_split_test_items: Daten: 0.02MB + Index: 0.00MB
wp_ulp_campaigns: Daten: 0.02MB + Index: 0.00MB
wp_ulp_campaign_items: Daten: 0.02MB + Index: 0.00MB
wp_ulp_layers: Daten: 0.34MB + Index: 0.00MB
wp_ulp_popups: Daten: 0.13MB + Index: 0.00MB
wp_ulp_subscribers: Daten: 0.02MB + Index: 0.00MB
wp_ulp_webfonts: Daten: 0.08MB + Index: 0.00MB
wp_usermeta: Daten: 1.73MB + Index: 0.43MB
wp_users: Daten: 0.03MB + Index: 0.03MB
wp_wcpdf_invoice_number: Daten: 0.02MB + Index: 0.00MB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Daten: 0.22MB + Index: 0.42MB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_payonecw_customer_contexts: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_payonecw_documents: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_payonecw_ecc: Daten: 0.02MB + Index: 0.00MB
wp_woocommerce_payonecw_schema_version: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_payonecw_storage: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_payonecw_transactions: Daten: 4.52MB + Index: 0.00MB
wp_woocommerce_termmeta: Daten: 0.21MB + Index: 0.15MB
wp_wpmelon_advbedit_temp: Daten: 0.02MB + Index: 0.00MB
wp_wpnb_pages: Daten: 0.02MB + Index: 0.00MB
wp_wpnb_subscribers: Daten: 0.02MB + Index: 0.00MB
wp_yith_wcwl: Daten: 0.02MB + Index: 0.02MB
wp_yith_wcwl_lists: Daten: 0.02MB + Index: 0.05MB
wp_yoast_seo_links: Daten: 0.30MB + Index: 0.11MB
wp_yoast_seo_meta: Daten: 0.42MB + Index: 0.00MB

### Post Type Counts ###

acf-field: 1
acf-field-group: 1
attachment: 8642
avada_faq: 7
contactform: 1
dd_layouts: 10
faq: 1
fusion_element: 15
invoice: 2165
mdf_shortcodes: 1
meta_data_filter: 3
nav_menu_item: 182
page: 38
points_image: 3
post: 3
product: 1403
product_variation: 682
scheduled-action: 14
shop_coupon: 19
shop_order: 1243
shop_order_refund: 175
sliders: 1
tve_form_type: 3
tve_lead_group: 2
tve_lead_shortcode: 1
um_directory: 1
um_form: 3
um_role: 2
view: 3
view-template: 2
wc_zapier_feed: 1
wp-types-group: 1
wp-types-term-group: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (54) ###

Query Monitor: von John Blackbourn – 3.3.7
Autocomplete For Relevanssi: von Jojaba – 0.1
Better Search Replace: von Delicious Brains – 1.3.3
iThemes Security: von iThemes – 7.4.0
Classic Editor: von WordPress-Mitwirkende – 1.5
Coming Soon Page & Maintenance Mode by SeedProd: von SeedProd – 5.0.25
Contact Form 7 Honeypot: von Nocean – 1.14
Contact Form 7: von Takayuki Miyoshi – 5.1.3
Duplicate Menu: von Jonathan Christopher – 0.2.1
Duplicate Post: von Enrico Battocchi – 3.2.3
Google Tag Manager for Wordpress: von Thomas Geiger – 1.9.2 – Nicht getestest mit der aktiven WooCommerce-Version
Edelmix Newsletter Implementation: von Mirko Echghi-Ghamsari – 1.0
Edelmix USP Bar: von Mirko Echghi-Ghamsari – 1.0
Email Address Encoder: von Till Krüss – 1.0.19
Enable Media Replace: von ShortPixel – 3.3.3
Enhanced Media Library: von wpUXsolutions – 2.7.2
Fusion Builder: von ThemeFusion – 1.9.1
Fusion Core: von ThemeFusion – 3.9.1
PageSpeed Module: von KAGG Design – 1.1.4
Loco Translate: von Tim Whitlock – 2.3.0
WooCommerce Product Filter: von Mihajlovic Nenad – 6.6.3 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Pushover Integration: von Shop Plugins – 1.0.15 – Nicht getestest mit der aktiven WooCommerce-Version
Regenerate Thumbnails: von Alex Mills (Viper007Bond) – 3.1.1
Relevanssi: von Mikko Saari – 4.2.0
Schema App Structured Data: von Hunch Manifest – 1.13.0
Simple Page Ordering: von Jake Goldman
10up – 2.3.2

Easy Updates Manager: von Easy Updates Manager Team – 8.0.5
SVG Support: von Benbodhi – 2.3.15
Thrive Leads: von <a href="https://thrivethemes.com">Thrive Themes</a> – 2.2.0
Toolset Types: von OnTheGoSystems – 3.3.2
GDPR Cookie Consent Banner: von termly – 2.3.14
Vendidero Helper: von Vendidero – 1.2.1
wolkenkraft.com Barcodes for WooCommerce: von wolkenkraft.com – 1.3.0.2 – Nicht getestest mit der aktiven WooCommerce-Version
Woocommerce Advanced Bulk Edit: von George Iron – 4.2.2 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Extended Coupon Features PRO: von Soft79 – 3.1.0
WooCommerce Brands: von WooCommerce – 1.6.9
WooCommerce Coupon Shortcodes: von itthinx – 1.11.0
WooCommerce Deutsch (de_DE): von David Decker - DECKERWEB.de – 3.2.0 – Nicht getestest mit der aktiven WooCommerce-Version
Woocommerce Edelmix Customization: von Mirko Echghi-Ghamsari – 1.0 – Nicht getestest mit der aktiven WooCommerce-Version
Germanized für WooCommerce Pro: von Vendidero – 1.11.1
Germanized für WooCommerce: von Vendidero – 2.3.2
WooCommerce Perfect SEO Url: von Perfect SEO Url – 2.8.4 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Pretty Emails: von MB Création – 1.8.6 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Retourenschein PDF: von Elb Byte Studio GmbH – 1.0.8 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Smart Coupons: von StoreApps – 4.0.8
WooCommerce: von Automattic – 3.6.5
WooCommerce PayoneCw: von customweb GmbH – 3.0.248 – Nicht getestest mit der aktiven WooCommerce-Version
Yoast SEO: von Team Yoast – 11.6 – Nicht getestest mit der aktiven WooCommerce-Version
WP All Export Pro: von Soflyy – 1.5.7
WP Extra File Types: von Davide Airaghi – 0.4.3
WP-Optimize - Clean, Compress, Cache: von David Anderson
Ruhani Rabin
Team Updraft – 3.0.2

WP Rocket | External Script Handler: von WP Rocket Support Team –
WP Rocket: von WP Media – 3.3.5.2
YITH WooCommerce Wunschliste: von YITH – 2.2.12

### Inactive Plugins (9) ###

Advanced Access Manager: von Vasyl Martyniuk <vasyl@vasyltech.com> – 5.9.8
EffectIO Dashboard: von EffectIO – 1.4
Email Templates: von Damian Logghe – 1.3
PixelYourSite PRO: von PixelYourSite – 6.5.1 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Blocks: von Automattic – 2.2.1
WooCommerce PDF Invoices & Packing Slips: von Ewout Fernhout – 2.2.14
WooCommerce PDF Invoices & Packing Slips Professional: von Ewout Fernhout – 1.4.4 – Nicht getestest mit der aktiven WooCommerce-Version
WP Migrate DB Pro: von Delicious Brains – 1.8.1
WP Overnight Sidekick: von Jeremiah Prummer
Ewout Fernhout
Michael Kluver – 2.0.4

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class

### Must Use Plugins (2) ###

cache-woo-get-refreshed-fragment-request.php: von  –
WP Rocket | Clean Product Cache after WooCommerce Order: von WP Rocket Support Team –

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop-Basis: ❌ Seite nicht festgelegt
Warenkorb: #13 - /warenkorb-2/
Kasse: #14 - /kasse/
Mein Konto: #15 - /mein-konto/
Allgemeine Geschäftsbedingungen: #2437 - /agb/

### Theme ###

Name: Avada Child
Version: 1.0.0
Author URL: https://theme-fusion.com
Child Theme: ✔
Parent Theme Name: Avada
Parent Theme Version: 5.9.1
Parent Theme Author URL: http://themeforest.net/user/ThemeFusion
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
/var/www/clients/client2/web3/web/wp-content/plugins/woocommerce-pretty-emails/emails/admin-cancelled-order.php Version 2.3.0 ist veraltet. Die Hauptversion ist 3.6.0
/var/www/clients/client2/web3/web/wp-content/plugins/woocommerce-pretty-emails/emails/admin-failed-order.php Version 2.5.0 ist veraltet. Die Hauptversion ist 3.5.0
/var/www/clients/client2/web3/web/wp-content/plugins/woocommerce-pretty-emails/emails/admin-new-order.php Version 2.0.0 ist veraltet. Die Hauptversion ist 3.5.0
/var/www/clients/client2/web3/web/wp-content/plugins/woocommerce-pretty-emails/emails/customer-completed-order.php Version 1.6.4 ist veraltet. Die Hauptversion ist 3.5.0
/var/www/clients/client2/web3/web/wp-content/plugins/woocommerce-pretty-emails/emails/customer-invoice.php Version 2.2.0 ist veraltet. Die Hauptversion ist 3.5.0
/var/www/clients/client2/web3/web/wp-content/plugins/woocommerce-pretty-emails/emails/customer-new-account.php Version 1.6.4 ist veraltet. Die Hauptversion ist 3.5.2
/var/www/clients/client2/web3/web/wp-content/plugins/woocommerce-pretty-emails/emails/customer-note.php Version 1.6.4 ist veraltet. Die Hauptversion ist 3.6.0
/var/www/clients/client2/web3/web/wp-content/plugins/woocommerce-pretty-emails/emails/customer-on-hold-order.php Version - ist veraltet. Die Hauptversion ist 3.5.0
/var/www/clients/client2/web3/web/wp-content/plugins/woocommerce-pretty-emails/emails/customer-processing-order.php Version 1.6.4 ist veraltet. Die Hauptversion ist 3.5.4
/var/www/clients/client2/web3/web/wp-content/plugins/woocommerce-pretty-emails/emails/customer-refunded-order.php Version 2.4.0 ist veraltet. Die Hauptversion ist 3.5.0
/var/www/clients/client2/web3/web/wp-content/plugins/woocommerce-pretty-emails/emails/customer-reset-password.php Version 2.0.0 ist veraltet. Die Hauptversion ist 3.5.0
/var/www/clients/client2/web3/web/wp-content/plugins/woocommerce-pretty-emails/emails/email-addresses.php Version 2.2.0 ist veraltet. Die Hauptversion ist 3.5.4
/var/www/clients/client2/web3/web/wp-content/plugins/woocommerce-pretty-emails/emails/email-customer-details.php
/var/www/clients/client2/web3/web/wp-content/plugins/woocommerce-pretty-emails/emails/email-footer.php Version 2.0.0 ist veraltet. Die Hauptversion ist 2.3.0
/var/www/clients/client2/web3/web/wp-content/plugins/woocommerce-pretty-emails/emails/email-header.php Version 1.0 ist veraltet. Die Hauptversion ist 2.4.0
/var/www/clients/client2/web3/web/wp-content/plugins/woocommerce-pretty-emails/emails/email-order-items.php Version 2.1.2 ist veraltet. Die Hauptversion ist 3.5.0
Avada/woocommerce/loop/loop-start.php
Avada-Child-Theme/woocommerce/loop/pagination.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

Outdated Templates: ❌
					
					
						Erfahre
wie du aktualisieren kannst

### Action Scheduler ###

Complete: 14
Oldest: 2019-06-25 09:24:11 +0000
Newest: 2019-06-25 09:25:04 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

</details>

**Comment by visualpropaganda** [comment]
Okay, we now have the same issue (Bad Gateway 502) with product tags, which are associated with products.

**Comment by malviyaritesh** [comment]
I followed your instructions but was not able to reproduce it. Please test again by deactivating all plugins except WooCommerce and activating recommended theme [Storefront](https://woocommerce.com/storefront/). Let us know if the issue is still present.

**Comment by visualpropaganda** [comment]
Found the Problem. Was a bad Plugin. Still have the Problem that product tags don't show associated products. But that's another Problem. The '502 Bad Gateway' is solved.

**Comment by malviyaritesh** [comment]
I'm glad that you found the problem. Feel free to open new issue if there's a problem in WooCommerce.
