### ISSUE TITLE
Grupo dos produtos não aparece

### ISSUE THREAD

**Issue by gomeshenio** [woocommerce/woocommerce#24216]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by rodrigoprimo** [comment]
Closing as there is not enough information here to understand the issue. Please open another issue following the bug report template (https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=) and provide clear steps on how to reproduce the problem.

Please, keep in mind that GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/
