### ISSUE TITLE
e2e tests are failing but getting a green checkmark

### ISSUE THREAD

**Issue by szepeviktor** [woocommerce/woocommerce#24214]
How could it be that e2e tests are failing
https://travis-ci.org/woocommerce/woocommerce/jobs/562079175#L1028
but the exit status is 0?

> The command "travis_retry bash tests/bin/run-e2e-CI.sh" exited with 0.

Please advise.

**Comment by peterfabian** [comment]
Hi, we've added a possibility to retry running the tests 3 times and if any of the runs fully succeeds, then we consider it a pass.
This was introduced in https://github.com/woocommerce/woocommerce/pull/21174

We'll probably be looking into migrating tests to Puppeteer and make them more stable in the coming months.

**Comment by szepeviktor** [comment]
@peterfabian Thank you for the explanation.
