### ISSUE TITLE
Bug woocommerce 3.6.5 - format postcode - locale NL

### ISSUE THREAD

**Issue by jmau111** [woocommerce/woocommerce#24225]
**Describe the bug**
We get this error on checkout : a wrong format for the field "postcode" when Nederland is selected as country. But we made the field "postcode" not mandatory by using a custom woocommerce filter so it's not supposed to trigger any error if it's not set by our customers.

**To Reproduce**
1. Make the field "postcode" not mandatory
2. Process the checkout with selecting Nederland as country but without specifying any postcode
3. See error

**Quick fix**

The bug is located here https://github.com/woocommerce/woocommerce/blob/master/includes/wc-formatting-functions.php#L949

So we made this quick fix : 

```PHP
add_filter( 'woocommerce_format_postcode', 'woo_fix_format_postcode' );
function woo_fix_format_postcode($postCode)
{
    return trim($postCode);
}
```

it solved our problem but we think it should be done by default.

**Screenshots**

French :

![Capture d’écran 2019-07-24 à 15 01 18](https://user-images.githubusercontent.com/6878027/61824576-a7fc4f00-ae5e-11e9-94b5-383c81644469.png)

**Expected behavior**
We should not get any error when customers select Nederland as country but do not fulfill the postcode field if this field is not mandatory.

**WordPress Environment**
<details>
`Woocommerce 3.6.5`
</details>

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24284.

**Comment by jmau111** [comment]
@claudiosanches thanks
