### ISSUE TITLE
Country issue

### ISSUE THREAD

**Issue by honchen2000** [woocommerce/woocommerce#24237]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by honchen2000** [comment]
I saw that in country list You put Taiwan in to province of China. But Taiwan is not province of China. Please fix it

**Comment by rodrigoprimo** [comment]
I'm not sure if I follow the problem that you are reporting. I just checked and Taiwan is in the [list of countries](https://github.com/woocommerce/woocommerce/blob/master/i18n/countries.php#L229) and not in the [list of provinces of China](https://github.com/woocommerce/woocommerce/blob/master/i18n/countries.php#L229). Closing this issue for now. Please let me know if I missed something or if I misunderstood what you said and I will check again.

**Comment by nobodxbodon** [comment]
According to [ISO-3166](https://www.iso.org/obp/ui/#iso:code:3166:TW), Taiwan is province of China.
