### ISSUE TITLE
Stock value written as Floating-Point instead of INT

### ISSUE THREAD

**Issue by Skinessence** [woocommerce/woocommerce#24233]
**Describe the bug**
When I receive a new order the stock value is updated. In the database record show: f.e. meta_value 9.000000 instead of 9 (meta_key = _stock).
Other programs fail as stock is expected as INT and not string value.
 
- [X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
`
### wp-core ###

version: 5.2.2
site_language: nl_NL
user_language: nl_NL
permalink: /%postname%/
https_status: true
user_registration: 0
default_comment_status: open
multisite: false
user_count: 1207
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/u32460p27743/domains/skinessence.nl/public_html
wordpress_size: 16,16 GB (17353538302 bytes)
uploads_path: /home/u32460p27743/domains/skinessence.nl/public_html/wp-content/uploads
uploads_size: 1,84 GB (1975773094 bytes)
themes_path: /home/u32460p27743/domains/skinessence.nl/public_html/wp-content/themes
themes_size: 8,84 MB (9264662 bytes)
plugins_path: /home/u32460p27743/domains/skinessence.nl/public_html/wp-content/plugins
plugins_size: 264,25 MB (277090366 bytes)
database_size: 239,55 MB (251183104 bytes)
total_size: 18,50 GB (19866849528 bytes)

### wp-dropins (1) ###

advanced-cache.php: true

### wp-active-theme ###

name: HandyStore
version: 5.0.14 (see readme.txt for detailed changelog) (latest version: 5.0.14 (see readme.txt for detailed changelog))
author: Themes Zone
author_website: http://themes.zone
parent_theme: none
theme_features: wc-product-gallery-lightbox, wc-product-gallery-slider, post-thumbnails, automatic-feed-links, title-tag, custom-logo, menus, html5, post-formats, woocommerce, plumtree-layouts, widgets, editor-style
theme_path: /home/u32460p27743/domains/skinessence.nl/public_html/wp-content/themes/handystore

### wp-themes (3) ###

Twenty Nineteen: version: 1.4, author: het WordPress team
Twenty Seventeen: version: 2.2, author: het WordPress team
Twenty Sixteen: version: 2.0, author: het WordPress team

### wp-plugins-active (59) ###

Autoptimize: version: 2.5.1, author: Frank Goossens (futtta)
bol.com for WooCommerce: version: 1.0.6, author: Woosa
Classic Editor: version: 1.5, author: WordPress Contributors
Contact Form 7: version: 5.1.3, author: Takayuki Miyoshi
Envato Market: version: 2.0.1, author: Envato
Google Analytics for WordPress by MonsterInsights: version: 7.7.1, author: MonsterInsights
Handy Feature Pack: version: 1.0.5, author: Themes Zone
iQ Block Country: version: 1.2.5, author: Pascal
iThemes Security: version: 7.4.0, author: iThemes
Kirki Customizer Framework: version: 3.0.44, author: Ari Stathopoulos (@aristath)
Kiyoh Customerreview: version: 1.0.19, author: kiyoh
Loco Translate: version: 2.3.0, author: Tim Whitlock
Mailchimp for WordPress: version: 4.5.3, author: ibericode
Max Mega Menu: version: 2.7.1.4, author: megamenu.com
Mollie Payments for WooCommerce: version: 5.2.1, author: Mollie
Ninja Pages: version: 1.4.2, author: The WP Ninjas
Products Purchase Price for Woocommerce: version: 1.0.4, author: Softedge
Really Simple SSL: version: 3.2.3, author: Rogier Lankhorst, Mark Wolters
reSmush.it Image Optimizer: version: 0.1.22, author: reSmush.it
SB Welcome Email Editor: version: 4.9.1, author: Sean Barton
Sidebar Manager Light: version: 1.15, author: OTWthemes
Slider Revolution: version: 5.4.8, author: ThemePunch
SUMO Reward Points: version: 22.5, author: Fantastic Plugins
TablePress: version: 1.9.2, author: Tobias Bäthge
TinyMCE Advanced: version: 5.2.1, author: Andrew Ozz
UpdraftPlus - Backup/Restore: version: 2.16.16.1, author: UpdraftPlus.Com, DavidAnderson
Widget Shortcode: version: 0.3.4, author: Hassan Derakhshandeh
WooCommerce: version: 3.6.5, author: Automattic
WooCommerce - Product Importer: version: 1.3.1, author: Visser Labs
WooCommerce - Store Exporter Deluxe: version: 3.4, author: Visser Labs
Woocommerce Advanced Bulk Edit: version: 4.2.5, author: George Iron
WooCommerce Custom Product Tabs Lite: version: 1.6.4, author: SkyVerge
WooCommerce EU VAT Assistant: version: 1.9.14.190618, author: Aelia
WooCommerce Extended Coupon Features FREE: version: 3.1.0, author: Soft79
WooCommerce Google Product Feed: version: 7.9.1, author: Ademti Software Ltd.
WooCommerce New Product Badge: version: 0.3.0, author: jameskoster
WooCommerce PDF Invoices & Packing Slips: version: 2.2.14, author: Ewout Fernhout
WooCommerce PDF Invoices & Packing Slips Premium Templates: version: 2.2.0, author: Ewout Fernhout
WooCommerce PDF Invoices & Packing Slips Professional: version: 1.4.6, author: Ewout Fernhout
WooCommerce Sequential Order Numbers: version: 1.8.3, author: SkyVerge
WooCommerce Table Rate Shipping: version: 4.0.3, author: Bolder Elements
WordPress Editorial Calendar: version: 3.7.2, author: Colin Vernon, Justin Evans, Joachim Kudish, Mary Vogt, and Zack Grossbart
WP-Cron Control: version: 0.7.1, author: Thorsten Ott, Erick Hitter, Automattic
WP-Optimize - Clean, Compress, Cache: version: 3.0.5, author: David Anderson, Ruhani Rabin, Team Updraft
WP Affiliate Manager: version: 2.6.6, author: wp.insider, wpaffiliatemgr
WP All Import Pro: version: 4.5.7, author: Soflyy
WPBakery Page Builder: version: 6.0.5, author: Michael M - WPBakery.com
WP Crontrol: version: 1.7.1, author: John Blackbourn & crontributors
WP Custom Widget area: version: 1.2.5, author: Kishor Khambu
WP Security Audit Log: version: 3.4.2, author: WP White Security
WP Simple Mail Sender: version: 1.0.2, author: Enrique Chavez
WP Super Cache: version: 1.6.8, author: Automattic (latest version: 1.6.9)
YITH WooCommerce Ajax Product Filter: version: 3.6.6, author: YITH
YITH WooCommerce Badge Management: version: 1.3.18, author: YITH
YITH WooCommerce Compare: version: 2.3.12, author: YITH
YITH WooCommerce Wishlist: version: 2.2.12, author: YITH
Yoast SEO: WooCommerce: version: 6.3, author: Team Yoast
Yoast SEO Premium: version: 6.3.1, author: Team Yoast
Zedna WP Image Lazy Load: version: 1.6.2.2, author: Radek Mezulanik

### wp-plugins-inactive (3) ###

BackWPup: version: 3.6.10, author: Inpsyde GmbH
WooCommerce Product Bundles: version: 5.10.2, author: SomewhereWarm (latest version: 5.11.1)
WP All Import - WooCommerce Add-On Pro: version: 3.0.6, author: Soflyy

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1684
imagemagick_version: ImageMagick 6.9.4-10 Q16 x86_64 2017-11-14 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 377 GB
	imagick::RESOURCETYPE_DISK: -1
	imagick::RESOURCETYPE_FILE: 24576
	imagick::RESOURCETYPE_MAP: 377 GB
	imagick::RESOURCETYPE_MEMORY: 189 GB
	imagick::RESOURCETYPE_THREAD: 1
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 8.70

### wp-server ###

server_architecture: Linux 2.6.32-954.3.5.lve1.4.64.el6.x86_64 x86_64
httpd_software: Apache/2
php_version: 7.2.18 64bit
php_sapi: litespeed
max_input_variables: 3000
time_limit: 3600
memory_limit: 2048M
max_input_time: 0
upload_max_size: 64M
php_post_max_size: 2048M
curl_version: 7.62.0 OpenSSL/1.0.2k
suhosin: false
imagick_availability: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.2.23-MariaDB-cll-lve
client_version: 10.2.23-MariaDB

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/u32460p27743/domains/skinessence.nl/public_html/wp-content
WP_PLUGIN_DIR: /home/u32460p27743/domains/skinessence.nl/public_html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 2048M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

`</details>

**Comment by claudiosanches** [comment]
This is not an issue and you should convert to the except value for your program.
