### ISSUE TITLE
New, duplicate subscriptions not updating old subscription

### ISSUE THREAD

**Issue by Mars920** [woocommerce/woocommerce#24235]
**Describe the bug**
If a customer has an existing subscription on hold, and places a new order for the same subscription, the order is processed, but neither the new subscription is created or the exisiting subscription is updated to be active.

**Expected behavior**
To my understanding of how WooCommerce manages multiple subscriptions, the existing subscription should be updated to active in place of the new subscription.

**WordPress Environment**
<details>

### WordPress Environment ###

WordPress address (URL): https://bayfarms.net.nz
Site address (URL): https://bayfarms.net.nz
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_NZ
External object cache: –

### Server Environment ###

Server Info: Apache/2
PHP Version: 5.6.40 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.65.3
OpenSSL/1.0.2k-fips

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.23-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: wp_
Total Database Size: 388.17MB
Database Data Size: 249.03MB
Database Index Size: 139.14MB
wp_woocommerce_sessions: Data: 4.02MB + Index: 0.13MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_order_items: Data: 2.52MB + Index: 1.45MB
wp_woocommerce_order_itemmeta: Data: 17.55MB + Index: 15.98MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.13MB + Index: 0.05MB
wp_woocommerce_payment_tokenmeta: Data: 0.27MB + Index: 0.28MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_aryo_activity_log: Data: 3.02MB + Index: 0.00MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 19.55MB + Index: 15.98MB
wp_et_divi_ab_testing_clients: Data: 0.02MB + Index: 0.00MB
wp_et_divi_ab_testing_stats: Data: 0.02MB + Index: 0.00MB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB
wp_formmaker: Data: 0.08MB + Index: 0.00MB
wp_formmaker_backup: Data: 0.02MB + Index: 0.00MB
wp_formmaker_blocked: Data: 0.02MB + Index: 0.00MB
wp_formmaker_query: Data: 0.02MB + Index: 0.00MB
wp_formmaker_sessions: Data: 0.02MB + Index: 0.00MB
wp_formmaker_submits: Data: 0.02MB + Index: 0.00MB
wp_formmaker_themes: Data: 1.52MB + Index: 0.00MB
wp_formmaker_views: Data: 0.02MB + Index: 0.00MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB
wp_options: Data: 2.16MB + Index: 0.23MB
wp_osefirewall_acl: Data: 0.02MB + Index: 0.03MB
wp_osefirewall_adminemails: Data: 0.02MB + Index: 0.02MB
wp_osefirewall_advancepatterns: Data: 0.02MB + Index: 0.02MB
wp_osefirewall_aiscan: Data: 0.02MB + Index: 0.02MB
wp_osefirewall_attacktype: Data: 0.02MB + Index: 0.00MB
wp_osefirewall_backup: Data: 0.02MB + Index: 0.00MB
wp_osefirewall_backupath: Data: 0.02MB + Index: 0.02MB
wp_osefirewall_basicrules: Data: 0.02MB + Index: 0.00MB
wp_osefirewall_bkfiles: Data: 0.02MB + Index: 0.00MB
wp_osefirewall_country: Data: 0.02MB + Index: 0.02MB
wp_osefirewall_detattacktype: Data: 0.02MB + Index: 0.02MB
wp_osefirewall_detcontdetail: Data: 0.05MB + Index: 0.03MB
wp_osefirewall_detcontent: Data: 0.08MB + Index: 0.00MB
wp_osefirewall_detected: Data: 0.02MB + Index: 0.03MB
wp_osefirewall_domains: Data: 0.02MB + Index: 0.02MB
wp_osefirewall_files: Data: 0.02MB + Index: 0.00MB
wp_osefirewall_fileuploadext: Data: 0.02MB + Index: 0.02MB
wp_osefirewall_fileuploadlog: Data: 0.02MB + Index: 0.05MB
wp_osefirewall_gitlog: Data: 0.02MB + Index: 0.00MB
wp_osefirewall_iptable: Data: 0.02MB + Index: 0.02MB
wp_osefirewall_iptable_tmp: Data: 1.52MB + Index: 0.00MB
wp_osefirewall_logs: Data: 0.02MB + Index: 0.00MB
wp_osefirewall_malware: Data: 0.02MB + Index: 0.03MB
wp_osefirewall_pages: Data: 0.02MB + Index: 0.00MB
wp_osefirewall_referers: Data: 0.02MB + Index: 0.00MB
wp_osefirewall_scanhist: Data: 0.02MB + Index: 0.00MB
wp_osefirewall_sfschecked: Data: 1.52MB + Index: 0.00MB
wp_osefirewall_updateLog: Data: 0.02MB + Index: 0.00MB
wp_osefirewall_vars: Data: 0.02MB + Index: 0.00MB
wp_osefirewall_versions: Data: 0.02MB + Index: 0.00MB
wp_osefirewall_virusVersion: Data: 0.02MB + Index: 0.00MB
wp_osefirewall_vlscanner: Data: 0.02MB + Index: 0.00MB
wp_osefirewall_vshash: Data: 0.02MB + Index: 0.02MB
wp_osefirewall_vspatterns: Data: 0.05MB + Index: 0.02MB
wp_osefirewall_vstypes: Data: 0.02MB + Index: 0.00MB
wp_ose_app_admin: Data: 0.02MB + Index: 0.00MB
wp_ose_app_adminrecemail: Data: 0.02MB + Index: 0.03MB
wp_ose_app_email: Data: 0.02MB + Index: 0.00MB
wp_ose_app_geoip: Data: 8.52MB + Index: 7.03MB
wp_ose_secConfig: Data: 0.02MB + Index: 0.00MB
wp_postmeta: Data: 81.61MB + Index: 76.98MB
wp_posts: Data: 33.53MB + Index: 5.75MB
wp_qss: Data: 0.20MB + Index: 0.05MB
wp_queue: Data: 0.02MB + Index: 0.00MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.09MB + Index: 0.08MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 11.52MB + Index: 10.02MB
wp_users: Data: 0.45MB + Index: 0.42MB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB
wp_wc_customer_lookup: Data: 0.08MB + Index: 0.03MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB
wp_wc_order_product_lookup: Data: 0.08MB + Index: 0.06MB
wp_wc_order_stats: Data: 0.08MB + Index: 0.05MB
wp_wc_order_tax_lookup: Data: 0.06MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_wfBlockedIPLog: Data: 0.22MB + Index: 0.00MB
wp_wfBlocks7: Data: 0.02MB + Index: 0.05MB
wp_wfConfig: Data: 1.36MB + Index: 0.00MB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB
wp_wfFileChanges: Data: 0.02MB + Index: 0.00MB
wp_wfFileMods: Data: 2.52MB + Index: 0.00MB
wp_wfHits: Data: 1.02MB + Index: 0.23MB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB
wp_wfIssues: Data: 0.02MB + Index: 0.06MB
wp_wfKnownFileList: Data: 1.52MB + Index: 0.00MB
wp_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB
wp_wfLogins: Data: 0.13MB + Index: 0.03MB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB
wp_wfNotifications: Data: 0.02MB + Index: 0.00MB
wp_wfPendingIssues: Data: 0.02MB + Index: 0.06MB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.05MB
wp_wfStatus: Data: 1.02MB + Index: 0.09MB
wp_wfTrafficRates: Data: 0.02MB + Index: 0.00MB
wp_wpml_mails: Data: 45.52MB + Index: 0.00MB
wp_wsal_metadata: Data: 3.52MB + Index: 2.52MB
wp_wsal_occurrences: Data: 0.30MB + Index: 0.36MB
wp_wsal_options: Data: 0.02MB + Index: 0.00MB
wsw_404_log: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 185
custom_css: 2
et_pb_layout: 13
fmemailverification: 1
nav_menu_item: 22
page: 15
payment_retry: 394
post: 3
product: 88
project: 24
revision: 2033
scheduled-action: 1855
shop_coupon: 12
shop_order: 14256
shop_order_refund: 170
shop_subscription: 1072
xlwcty_thankyou: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

Activity Log: by Activity Log Team – 2.5.2
BackWPup: by Inpsyde GmbH – 3.6.10
Classic Editor: by WordPress Contributors – 1.5
Mailchimp for WordPress: by ibericode – 4.5.3
Menu Icons: by ThemeIsle – 0.11.5
Toolbox for WooCommerce Subscriptions: by Gabor Javorszky  – 1.4.14 – Not tested with the active version of WooCommerce
Divi Forms Google reCaptcha: by Trumani – 1.1
VisionLab Custom Functions: by Jacek Pakulski – 0.2.0
VisionLab Fluid Subscriptions: by Jacek Pakulski – 0.7.1
WC Password Strength Settings: by Daniel Santoro – 2.1.0
WooCommerce Address Book: by Hall Internet Marketing – 1.5.5
WooCommerce Better Usability: by Moises Heberle – 1.0.28
Checkout Field Editor for WooCommerce: by ThemeHiGH – 1.3.3
Woo Discount Rules: by Flycart Technologies LLP – 1.7.17
Advanced Order Export For WooCommerce: by AlgolPlus – 3.0.1
Woo - Send Email on Cancelled or Failed Order: by Tickera.com – 1.0.0
NextMove Lite - Thank You Page for WooCommerce: by XLPlugins – 2.9.6
WooCommerce Admin: by WooCommerce – 0.15.0
WooCommerce Stripe Gateway: by WooCommerce – 4.2.3
WooCommerce Max Quantity: by Isabel Castillo – 1.5.1 – Not tested with the active version of WooCommerce
WooCommerce PDF Invoices: by Bas Elbers – 3.0.7
WooCommerce Subscriptions: by Prospress Inc. – 2.2.10 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.6.5
Wordfence Security: by Wordfence – 7.3.5

### Must Use Plugins (1) ###

ET Support Center :: Must-Use Plugins Autoloader: by Elegant Themes –

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: NZD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #8291 - /testshop/
Cart: #794 - /cart/
Checkout: #795 - /checkout/
My account: #796 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Divi Child Theme
Version: 1.0.0
Author URL: https://www.elegantthemes.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.26.3
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: Divi child/woocommerce/cart/cart-empty.php
Divi child/woocommerce/cart/cart-shipping.php
Divi child/woocommerce/cart/cart-totals.php
Divi child/woocommerce/cart/cart.php
Divi child/woocommerce/cart/proceed-to-checkout-button.php
Divi child/woocommerce/checkout/form-billing.php
Divi child/woocommerce/checkout/form-checkout.php
Divi child/woocommerce/checkout/form-login.php
Divi child/woocommerce/checkout/review-order.php
Divi child/woocommerce/checkout/thankyou.php
Divi child/woocommerce/emails/customer-completed-order.php
Divi child/woocommerce/emails/customer-invoice.php
Divi child/woocommerce/emails/customer-on-hold-order.php
Divi child/woocommerce/emails/customer-processing-order.php
Divi child/woocommerce/myaccount/dashboard.php

### subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live

### Action Scheduler ###

Complete: 1,574
Oldest: 2019-06-25 09:44:31 +1200
Newest: 2019-07-26 09:10:10 +1200

Pending: 188
Oldest: 2019-07-26 10:10:10 +1200
Newest: 2019-08-26 07:14:18 +1200

Canceled: 79
Oldest: 2019-07-01 06:21:22 +1200
Newest: 2019-08-27 09:45:07 +1200

In-progress: 0
Oldest: –
Newest: –

Failed: 14
Oldest: 2018-01-13 16:29:51 +1300
Newest: 2018-04-11 07:05:05 +1200

</details>

**Comment by rodrigoprimo** [comment]
Hi there!

This GitHub repository is for reporting bugs and issues specific to the WooCommerce plugin. It seems to me that you are reporting an issue in WooCommerce Subscriptions which is a separate product. If that is the case, please contact WooCommerce.com support via http://woocommerce.com/contact-us/ and if there is indeed a bug in the software they will pass the information to the developers of WooCommerce Subscriptions.

Thanks
