### ISSUE TITLE
Small tweak in mobile row actions

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/woocommerce#24231]
![“ID” slightly higher than other row actions](https://cld.wthms.co/YUBaGR+)
Link to image here: https://cld.wthms.co/YUBaGR.

The ID section is slightly higher on mobile than the other actions. Because the ID is not wrapped in an <a>, on mobile, the padding is slightly off.

(This is also the case for the "Quick edit" because it's a button instead of an anchor, but that's a problem in WP core, not WC.)

Adding the following below this section will solve this: https://github.com/woocommerce/woocommerce/blob/master/assets/css/admin.scss#L2756-L2758

```
	.row-actions span.id {
		padding-top: 8px;
	}
```

**Comment by rodrigoprimo** [comment]
See #24277. Thanks for creating this issue and including a fix to the problem, @jobthomas.

**Comment by jobthomas** [comment]
Just for the sake of documentation, I logged the issue of "Quick Edit" not being at the same height here: https://core.trac.wordpress.org/ticket/47815 (with a proposed solution)
