### ISSUE TITLE
When I add items to the cart @wordpress/apiFectch recieves invalid nonce

### ISSUE THREAD

**Issue by dwayneparton** [woocommerce/woocommerce#24241]
**Description**
This may be more of a wordpress bug or a gutenberg bug, but the problem only seems to occur with woocommerce.

I am heavily using @wordpress/apiFectch It works perfect until i add an item to the cart, then I receive a rest_cookie_invalid_nonce.  When an item is added to the cart the nonce fails because the user id is incorrect in the wp_verify_nonce( $nonce, 'wp_rest' ) in wp-includes/rest-api.php. It is getting the nonce from $_SERVER['HTTP_X_WP_NONCE'] and doesn't make much sense to me because that filter should be setting the uID on nonce creation and verification(wp-includes/pluggable.php.). But it's likes like that filter is not being executed when the nonce is initially created.

I have custom endpoints outside of woocommerce with basic GET functionality. They stop working when the nonce is invalid.

I was able to remedy this issue by updating class-wc-session-handler.php(Line 286) to return the default $uid if nonce is 'wp_rest':

```
public function nonce_user_logged_out( $uid , $action = -1 ) {
	if($action === 'wp_rest'){
		return $uid;
	}
	return $this->has_session() && $this->_customer_id ? $this->_customer_id : $uid;
}
```
But the actual solution I am using is in my theme functions:
```
if ( ! is_user_logged_in() ) {
	add_filter( 'nonce_user_logged_out', function ( $uid , $action = -1 ) {
		if($action === 'wp_rest'){
			return get_current_user_id();
		}
		return $uid;
	}, 99, 2 );
}
```

**To Reproduce**
Use @wordpress/apiFetch on the front-end of a site. It should work as expected. Add an item to the cart. When an item is added to the cart the nonce fails.

**Expected behavior**
@wordpress/apiFetch should be able to authenticate all api endpoints correctly

**WordPress Environment**
This persists on both live and local environments
<details>

### WordPress Environment ###

WordPress address (URL): http://rockinrudys.gecko
Site address (URL): http://rockinrudys.gecko
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: ❌ 40 MB - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.27 (Unix) OpenSSL/1.0.1p PHP/5.6.31
PHP Version: 5.6.31 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.43.0
OpenSSL/1.0.1p

SUHOSIN Installed: –
MySQL Version: 5.7.21-0ubuntu0.16.04.1
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 5.08MB
Database Data Size: 3.37MB
Database Index Size: 1.71MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_comments: Data: 0.02MB + Index: 0.09MB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB
wp_gf_form: Data: 0.02MB + Index: 0.00MB
wp_gf_form_meta: Data: 0.05MB + Index: 0.00MB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB
wp_links: Data: 0.02MB + Index: 0.02MB
wp_options: Data: 0.42MB + Index: 0.05MB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB
wp_pmxi_images: Data: 0.02MB + Index: 0.00MB
wp_pmxi_imports: Data: 0.02MB + Index: 0.00MB
wp_pmxi_posts: Data: 0.02MB + Index: 0.00MB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB
wp_postmeta: Data: 1.52MB + Index: 0.30MB
wp_posts: Data: 0.28MB + Index: 0.09MB
wp_rg_form: Data: 0.02MB + Index: 0.00MB
wp_rg_form_meta: Data: 0.05MB + Index: 0.00MB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB
wp_rg_lead: Data: 0.02MB + Index: 0.03MB
wp_rg_lead_detail: Data: 0.02MB + Index: 0.06MB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB
wp_termmeta: Data: 0.02MB + Index: 0.03MB
wp_terms: Data: 0.02MB + Index: 0.03MB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_usermeta: Data: 0.05MB + Index: 0.03MB
wp_users: Data: 0.02MB + Index: 0.05MB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB

### Post Type Counts ###

acf-field: 18
acf-field-group: 5
asset: 115
attachment: 232
nav_menu_item: 5
page: 10
person: 8
post: 3
product: 20
product_variation: 2
revision: 25
scheduled-action: 2
tablepress_table: 1
theme-part: 5
ticket: 51

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (11) ###

Gravity Forms: by rocketgenius – 2.4.11
Akismet Anti-Spam: by Automattic – 4.1.2
Gecko Command: by Gecko Designs – 1.4.3
Gecko Framework: by Gecko Designs – 0.0.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.1
RockinRudys by Gecko Designs: by Gecko Designs – 1.0.1
WooCommerce Blocks: by Automattic – 2.2.1
WooCommerce Stripe Gateway: by WooCommerce – 4.2.3
WooCommerce: by Automattic – 3.6.5
WP All Import Pro: by Soflyy – 4.5.6
WP Migrate DB: by Delicious Brains – 1.0.11

### Inactive Plugins (3) ###

Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.7.1
Redirection: by John Godley – 4.3.1
Yoast SEO: by Team Yoast – 11.7 – Not tested with the active version of WooCommerce

### Must Use Plugins (1) ###

WP Migrate DB Compatibility: by Delicious Brains – 1.2

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: ❌ Page not set
Cart: #97 - /cart/
Checkout: #98 - /checkout/
My account: #99 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: 
Version: – 0 is available
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 2
Oldest: 2019-07-01 09:39:18 -0600
Newest: 2019-07-23 11:33:22 -0600

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –
</details>

**Comment by tammullen** [comment]
Adding `needs developer feedback` label to get a priority assigned to this bug.

**Comment by claudiosanches** [comment]
Duplicated of #23682
