### ISSUE TITLE
The Display tab under products on WooCommerce settings in Wordpress is gone. please fix.

### ISSUE THREAD

**Issue by footballernow** [woocommerce/woocommerce#24245]
The Display tab under Products on WooCommerce Settings in Wordpress is gone. Please fix. I need this issue fixed so I can add categories to my shop page.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by peterfabian** [comment]
Hi, I believe this has been removed with WC 3.3. The relevant options should now live in the Customizer under WooCommerce > Product Catalog.

**Comment by footballernow** [comment]
I have gone to the customizer section under product catalog to select categories to show on the shop page but no categories show up. There are just my products and only 1 page of products. If I expand the number of rows to 10 I can get all of my products if it’s on 4 rows only 4 rows of products will show up with no additional pages. Please fix.
