### ISSUE TITLE
Ability to filter logout redirect URL

### ISSUE THREAD

**Issue by toddlevy** [woocommerce/woocommerce#24243]
**Is your feature request related to a problem? Please describe.**
I am hoping to redirect the user to the referring page when they click the logout link at /account/logout

Currently, there is a message...
> Are you sure you want to log out? Confirm and log out

The code that renders this message calls wc_logout_url does not pass in a referrer.

Then, the wc_logout_url essentially "forces" the referrer to be the main account page.

`$redirect = $redirect ? $redirect : wc_get_page_permalink( 'myaccount' );`

**Describe the solution you'd like**
The proposed solution is to have a filter for the $redirect inside of the wc_logout_url function.

`$redirect = apply_filters('woocommerce_logout_redirect', $redirect);`

**Describe alternatives you've considered**
Variety of things like hooking into wp_logout, wp_logout_url filter, etc.

**Comment by claudiosanches** [comment]
Thank you for suggesting this feature!

I'm closing the issue as it already has a PR, please continue the discussion over at #24282.

**Comment by hjoelr** [comment]
I attempted to use the woocommerce_logout_default_redirect_url filter on my store after upgrading to WC 3.8.0 and I'm pretty confident that something is not correct with it. What it's actually filtering is not the redirect but instead the path to the logout endpoint. I haven't had time to fully investigate this, but I'm thinking the filter should actually be located here: https://github.com/woocommerce/woocommerce/blob/master/includes/wc-template-functions.php#L33-L37 .

Also (and related), I think the `wc_logout_url()` and `wp_logout_url()` functions are accomplishing two different things. The `wc_logout_url()` is taking a parameter called `$redirect` like the Wordpress-equivalent function, but it's not really the redirect in `wc_logout_url()` if a logout endpoint is defined.
