### ISSUE TITLE
Filter 'woocommerce_product_get_image' has duplicate param $image

### ISSUE THREAD

**Issue by manchumahara** [woocommerce/woocommerce#24246]
**Is your feature request related to a problem? Please describe.**
This issue is not related to a problem but this is suggestion to improve filter 'woocommerce_product_get_image'  as it uses duplicate param $image as 6th param.

**Describe the solution you'd like**
Filter 'woocommerce_product_get_imag'  has 6  params inside method 'get_image' in file wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-product.php 

the return is like 
`return apply_filters( 'woocommerce_product_get_image', $image, $this, $size, $attr, $placeholder, $image );
`
Here the 6th param $image is used duplicate and has no use if I am not wrong

Here is the code for the method 

```
/**
	 * Returns the main product image.
	 *
	 * @param  string $size (default: 'woocommerce_thumbnail').
	 * @param  array  $attr Image attributes.
	 * @param  bool   $placeholder True to return $placeholder if no image is found, or false to return an empty string.
	 * @return string
	 */
	public function get_image( $size = 'woocommerce_thumbnail', $attr = array(), $placeholder = true ) {
		$image = '';
		if ( $this->get_image_id() ) {
			$image = wp_get_attachment_image( $this->get_image_id(), $size, false, $attr );
		} elseif ( $this->get_parent_id() ) {
			$parent_product = wc_get_product( $this->get_parent_id() );
			if ( $parent_product ) {
				$image = $parent_product->get_image( $size, $attr, $placeholder );
			}
		}
		

		if ( ! $image && $placeholder ) {
			$image = wc_placeholder_img( $size );
		}

		return apply_filters( 'woocommerce_product_get_image', $image, $this, $size, $attr, $placeholder, $image );
	}
```

**Describe alternatives you've considered**
We can remove the param $image  or deprecate it in next release  or we can replace this $image param with a new one. I noticed from the filter   'woocommerce_product_get_image' we have chance to replace the image finally with something we want  or modify as need but we can not understand that if placeholder used or not. We can replace the 6th param $image with a new param called $placeholder_used (true/false).

My suggestion is like below as a modified code for method "get_image"

```
/**
	 * Returns the main product image.
	 *
	 * @param  string $size (default: 'woocommerce_thumbnail').
	 * @param  array  $attr Image attributes.
	 * @param  bool   $placeholder True to return $placeholder if no image is found, or false to return an empty string.
	 * @return string
	 */
	public function get_image( $size = 'woocommerce_thumbnail', $attr = array(), $placeholder = true ) {
		$image = '';
		if ( $this->get_image_id() ) {
			$image = wp_get_attachment_image( $this->get_image_id(), $size, false, $attr );
		} elseif ( $this->get_parent_id() ) {
			$parent_product = wc_get_product( $this->get_parent_id() );
			if ( $parent_product ) {
				$image = $parent_product->get_image( $size, $attr, $placeholder );
			}
		}
		
                $placeholder_used = false;

		if ( ! $image && $placeholder ) {
			$image = wc_placeholder_img( $size );
                        $placeholder_used = true;
		}

		return apply_filters( 'woocommerce_product_get_image', $image, $this, $size, $attr, $placeholder, placeholder_used );
	}
```

In this way the 6th param $image can be replaced with new param $placeholder_used  and it can be meaningful. 

**Additional context**
I already described it enough.

**Comment by malviyaritesh** [comment]
The commit message for 8a8f085dc suggest that last `$image` param was added back for back-compatibility. Earlier first `$image` param was passed as `wc_get_relative_url( $image )` while second was `$image` as it is.
We can deprecate the second `$image` param in future releases.

**Comment by peterfabian** [comment]
Thanks, @malviyaritesh, you're correct.

**Comment by manchumahara** [comment]
> The commit message for [8a8f085](https://github.com/woocommerce/woocommerce/commit/8a8f085dcf802a866c4f8de2f3656ceb47478854) suggest that last `$image` param was added back for back-compatibility. Earlier first `$image` param was passed as `wc_get_relative_url( $image )` while second was `$image` as it is.
> We can deprecate the second `$image` param in future releases.

Thank you for clarification.
