### ISSUE TITLE
Sales prices dissapear after purchase by client

### ISSUE THREAD

**Issue by parttir** [woocommerce/woocommerce#24247]
Hi all,

I have this issue with woocommerce.

1. When i have a product in sale, after purchasing by client, the price returns back to regular price in stead of sales price.

What i have done to try to fix this. 

- I reinstalled the theme

- Reinstalled Woocommerce

- Wordpress re-install.

This doesnt made sense.

It seems like it's a cron job issue. On the first screenshot which i named "picture 1" you can see that i have a regular price(€24,95) and a sales price (€17,47).  I have set this up in my product editing page (see screenshot "picture 2")

They are being displayed well for 1 single time in stead of staying until we change it back to regular price. After purchase by customer the sales price automatically removes. Even when i shedule the period.

**Comment by peterfabian** [comment]
Hi, 

Would you mind sharing your system status report please? 
Have you tried if this happens with only WooCommerce plugin active? 
Are you able to check your scheduled/cron jobs using one of the plugins, e.g. https://wordpress.org/plugins/wp-crontrol/?

**Comment by parttir** [comment]
Hi @peterfabian 

1. I will do this. 


Have you tried if this happens with only WooCommerce plugin active?

- No i haven't, because the website cant be offline.

Are you able to check your scheduled/cron jobs using one of the plugins, e.g. 

See screenshot

![cronjobs](https://user-images.githubusercontent.com/47103107/62131026-a4dbe580-b2da-11e9-8e36-3e4c6237678c.PNG)
[status system report.txt](https://github.com/woocommerce/woocommerce/files/3446848/status.system.report.txt)


Hope you can help me!!

**Comment by claudiosanches** [comment]
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. I tried the steps you described and it appeared to work correctly.

It could be some 3rd party plugin or code in your theme that is causing it. You could try disable all your plugins one by one and testing your site, if you can't go offline, you can create a offline copy of your site.

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

Thanks!
