### ISSUE TITLE
Woocommerce doesn't respect Wordpress permalink settings for endpoints

### ISSUE THREAD

**Issue by trompx** [woocommerce/woocommerce#24240]
**Describe the bug**

I am not sure this is a bug or intentional but woocommerce does not respect the wordpress permalink settings for urls not handled by the Product permalinks settings.

I have my wordpress permalink set to : `/%postname%` without trailing slash.
All my-account tabs urls end with trailing slash, thus each request redirects from /my-account/tab_name/ to /my-account/tab_name
Same for view order urls and probably many more : `/my-account/view-order/15/`

**To Reproduce**

1. Set wordpress permalink to: /%postname%
2. Go to my-account dashboard and click on downloads tab
3. Check network tab in chrome devtools or other browser and see the redirect

**Expected behavior**

Woocommerce urls for which we cannot set the permalink should respect the Wordpress one in order to avoid redirection.

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24283.
