### ISSUE TITLE
Update Product Variation API should use PUT not POST, or update documentation

### ISSUE THREAD

**Issue by phpfui** [woocommerce/woocommerce#24256]
The documentation https://woocommerce.github.io/woocommerce-rest-api-docs/?shell#update-a-product says to use PUT to update a Product Variation.  This makes sense from a REST point of view.  But PUT returns a 405 error.

I updated my code to use POST, and that worked.  POST does not make sense in this case, because you are doing an update, and POST should only be used to add a new record.

Since you probably have existing code using POST, I would suggest you add support for PUT and depreciate POST for Update Product Variation.  Then the documentation will be correct.  Or you could change the documentation to POST, even though it violates common REST practice, at least it would correctly document existing behavior.

In any case, I am just bringing this to your attention.  Since I started using POST, everything works and no immediate fix is needed. I would  attach sample code, but I am working in PowerShell and I am sure it would not be much use to you.

And thanks for a generally great product.  Seems to work well.

**Comment by claudiosanches** [comment]
> But PUT returns a 405 error.

405 means "Method Not Allowed"... This sounds like that your server doesn't allow `PUT` requests, probably not `DELETE` either.
This is an issue with your server configuration.
