### ISSUE TITLE
Rating footer overlays update button

### ISSUE THREAD

**Issue by kloon** [woocommerce/woocommerce#24255]
**Describe the bug**
Issue reported via wp.org https://wordpress.org/support/topic/i-could-give-for-but-somethings-bugging-me/#post-11777928

The rating footer seems to overlay the update button in some instances prohibiting it from being clicked.

**Comment by claudiosanches** [comment]
Wjat rating footer? In what screen? Not sure what are you talking about.

**Comment by rodrigoprimo** [comment]
cc @kloon in case you missed @claudiosanches' comment above

**Comment by kloon** [comment]
@claudiosanches I was referring to the footer link we have on all WooCommerce pages in wp-admin

![](https://cld.wthms.co/yy8c0P+)

That said I tried to replicate this now again but was unable, I was able to when I logged it, from the sounds it might only happen on some screens with long content.

**Comment by kloon** [comment]
Checking the location of that text now I believe this might have been a bug in WP core that was fixed? I am running 5.3 beta and not able to replicate this anymore on there. I'll close for now but we can reopen should this pop up again.
