### ISSUE TITLE
PayPal Transaction ID missing from some Orders

### ISSUE THREAD

**Issue by Hamsterkacke** [woocommerce/woocommerce#24250]
**Describe the bug**
I tried to export orders via external plugins, but some orders where missing.

Turns out, those Orders don't have the PayPal Transaction ID in the database and therefore also don't have the meta_values for paid_date and completed_date. I guess, if the transaction id step fails, the paid and completed_fields aren't set.

In the backend though everything is okay. Order is completed, IPN Call was correct etc.

So i am a bit lost, why those only happens to certain paypal orders. I can't find a pattern for this. The pp-logs (generated from woocommerce) for a specific order also looks correct to me. 

As far as i can recall, it stopped working somewhere around the 1.6.2019. So i am not quite sure, if it is related to one of the last woocommerce updates, that those orders won't get updated correctly.

And hints for me? Any things i can debug to find the culprit? I tried to search the closed and open issues, but didn't find a similar problem.

**Comment by claudiosanches** [comment]
Sounds like those orders are not properly updated, like manually updated. Also I tested current versions of WooCommerce (3.6.5 and 3.7 RC) and is saving the transaction ID.

**Comment by naveedcs** [comment]
I am having the exact same problem and I can not reproduce what's wrong 99 percent of the orders are fine but randomly there is an order without any transaction id.

**Comment by nikita-kiryanov** [comment]
I am also experiencing this issue. We recently had 3 of those in a row. Such orders also have an empty date_paid, date_paid_gmt, date_completed, and date_completed_gmt.

**Comment by ErdincKocak** [comment]
is there any solution for that? I have the same problem. Some orders don't have a transaction ID.
