### ISSUE TITLE
WooCommerce CSV importer: show filename when finished

### ISSUE THREAD

**Issue by paulcee** [woocommerce/woocommerce#24266]
This is an enhancement request for the WooCommerce CSV importer.

When the import finishes, you get a screen with a check-mark icon indicating that the import is complete (and listing any errors). But it doesn't tell you which file was imported.

Could this screen show the filename too? e.g. "importing FILE2.CSV is complete".

When importing many files in a row, this will help you to remember which one you just did -- which otherwise isn't visible even in the URL -- and thus avoids accidental duplicate imports of the same file. (It might be in the history, but can be hard to find: for example, Chrome ridiculously does not show the URLs in its history, only the page titles.)

**Comment by shamalisulakhe** [comment]
@paulcee , you can refer to the above pull request for the solution. I have added the patch for the same.

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24856.
