### ISSUE TITLE
Add to Cart not working within Woocommerce 3.6.5

### ISSUE THREAD

**Issue by dreamesper** [woocommerce/woocommerce#24272]
Bug:  www.dreamesper.com

Adding items to CART will send the customer to an empty shopping cart for some, odd reason. I have tried switching themes, loading 3.7.0rc1 and adding/disabling some other plugins as well.
Nothing has fixed the issue...

**Isolating the problem (mark completed items with an [x]):**
- [X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

WORDPRESS ENVIRONMENT COPY:

WordPress environment
WordPress address (URL): 		https://dreamesper.com
Site address (URL): 		https://dreamesper.com
WooCommerce version: 		3.6.5
Log directory writable: 		/home/content/p3pnexwpnas12_data02/46/3796746/html/wp-content/uploads/wc-logs/
WordPress version: 		5.2.2	
WordPress multisite: 		–
WordPress memory limit: 		256 MB	
WordPress debug mode: 		
WordPress cron: 		
Language: 		en_US
External object cache: 		–
Server environment
Server info: 		Apache
PHP version: 		7.2.15	
PHP post max size: 		100 MB
PHP time limit: 		0
PHP max input vars: 		1000
cURL version: 		7.45.0, OpenSSL/1.0.1e
SUHOSIN installed: 		–
MySQL version: 		5.6.32-78.0-log	
Max upload size: 		100 MB
Default timezone is UTC: 		
fsockopen/cURL: 		
SoapClient: 		
DOMDocument: 		
GZip: 		
Multibyte string: 		
Remote post: 		
Remote get: 		
Database
WooCommerce database version: 		3.6.5
Database prefix 	  	wp_akyx8yatq1_	
MaxMind GeoIP database: 		/home/content/p3pnexwpnas12_data02/46/3796746/html/wp-content/uploads/GeoLite2-Country.mmdb
Total Database Size 	  	67.40MB
Database Data Size 	  	63.17MB
Database Index Size 	  	4.23MB
wp_akyx8yatq1_woocommerce_sessions 	  	Data: 0.09MB + Index: 0.03MB
wp_akyx8yatq1_woocommerce_api_keys 	  	Data: 0.00MB + Index: 0.01MB
wp_akyx8yatq1_woocommerce_attribute_taxonomies 	  	Data: 0.00MB + Index: 0.01MB
wp_akyx8yatq1_woocommerce_downloadable_product_permissions 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_woocommerce_order_items 	  	Data: 0.05MB + Index: 0.04MB
wp_akyx8yatq1_woocommerce_order_itemmeta 	  	Data: 0.34MB + Index: 0.27MB
wp_akyx8yatq1_woocommerce_tax_rates 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_woocommerce_tax_rate_locations 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_woocommerce_shipping_zones 	  	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_woocommerce_shipping_zone_locations 	  	Data: 0.02MB + Index: 0.05MB
wp_akyx8yatq1_woocommerce_shipping_zone_methods 	  	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_woocommerce_payment_tokens 	  	Data: 0.02MB + Index: 0.02MB
wp_akyx8yatq1_woocommerce_payment_tokenmeta 	  	Data: 0.02MB + Index: 0.03MB
wp_akyx8yatq1_woocommerce_log 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_adrotate 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_adrotate_groups 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_adrotate_linkmeta 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_adrotate_schedule 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_adrotate_stats 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_adrotate_stats_archive 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_adrotate_tracker 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_adrotate_transactions 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_apct_testimonial_detail 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_bluesnap_supported_currencies 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_bp_activity 	  	Data: 0.00MB + Index: 0.01MB
wp_akyx8yatq1_bp_activity_meta 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_bp_notifications 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_bp_notifications_meta 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_bp_xprofile_data 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_bp_xprofile_fields 	  	Data: 0.00MB + Index: 0.01MB
wp_akyx8yatq1_bp_xprofile_groups 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_bp_xprofile_meta 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_commentmeta 	  	Data: 0.02MB + Index: 0.01MB
wp_akyx8yatq1_comments 	  	Data: 0.52MB + Index: 0.35MB
wp_akyx8yatq1_defender_lockout 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_defender_lockout_log 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_EWD_OTP_Customers 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_EWD_OTP_Custom_Fields 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_EWD_OTP_Fields_Meta 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_EWD_OTP_Orders 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_EWD_OTP_Order_Statuses 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_EWD_OTP_Sales_Reps 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_links 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_litespeed_img_optm 	  	Data: 0.00MB + Index: 0.02MB
wp_akyx8yatq1_litespeed_optimizer 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_lws_wr_historic 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_mollie_pending_payment 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_msdb_coupon 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_msdb_post_collection 	  	Data: 0.01MB + Index: 0.04MB
wp_akyx8yatq1_msdb_post_data 	  	Data: 0.20MB + Index: 0.02MB
wp_akyx8yatq1_msdb_product_discount 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_msdb_purchase 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_msdb_shopping_cart 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_msdb_store_discount 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_nf3_actions 	  	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_nf3_action_meta 	  	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_nf3_fields 	  	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_nf3_field_meta 	  	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_nf3_forms 	  	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_nf3_form_meta 	  	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_nf3_objects 	  	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_nf3_object_meta 	  	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_nf3_relationships 	  	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_options 	  	Data: 4.30MB + Index: 0.13MB
wp_akyx8yatq1_postmeta 	  	Data: 54.78MB + Index: 1.65MB
wp_akyx8yatq1_posts 	  	Data: 1.78MB + Index: 0.66MB
wp_akyx8yatq1_rank_math_404_logs 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rank_math_internal_links 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rank_math_internal_meta 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rank_math_redirections 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rank_math_redirections_cache 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rank_math_sc_analytics 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_responsive_thumbnail_slider 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_photo_slider_instal 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_photo_slider_instal_video 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_photo_slider_manager 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect1 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect10 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect10_loader 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect1_loader 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect2 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect2_loader 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect3 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect3_loader 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect4 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect4_loader 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect5 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect5_loader 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect6 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect6_loader 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect7 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect7_loader 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect8 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect8_loader 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect9 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effect9_loader 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_effects_data 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_font_family 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_rich_web_slider_id 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_ship200bulk 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_shipment_batch_process 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_signups 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_smush_dir_images 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_termmeta 	  	Data: 0.01MB + Index: 0.01MB
wp_akyx8yatq1_terms 	  	Data: 0.01MB + Index: 0.02MB
wp_akyx8yatq1_term_relationships 	  	Data: 0.11MB + Index: 0.23MB
wp_akyx8yatq1_term_taxonomy 	  	Data: 0.01MB + Index: 0.01MB
wp_akyx8yatq1_usermeta 	  	Data: 0.29MB + Index: 0.19MB
wp_akyx8yatq1_users 	  	Data: 0.04MB + Index: 0.04MB
wp_akyx8yatq1_user_registration_sessions 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_vw_lsrooms 	  	Data: 0.00MB + Index: 0.01MB
wp_akyx8yatq1_vw_lwsessions 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_vw_sessions 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_wc_admin_notes 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_wc_admin_note_actions 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_wc_customer_lookup 	  	Data: 0.01MB + Index: 0.01MB
wp_akyx8yatq1_wc_download_log 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_wc_order_coupon_lookup 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_wc_order_product_lookup 	  	Data: 0.01MB + Index: 0.01MB
wp_akyx8yatq1_wc_order_stats 	  	Data: 0.01MB + Index: 0.01MB
wp_akyx8yatq1_wc_order_tax_lookup 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_wc_product_meta_lookup 	  	Data: 0.01MB + Index: 0.02MB
wp_akyx8yatq1_wc_webhooks 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_woocommerce_wallee_attribute_options 	  	Data: 0.02MB + Index: 0.02MB
wp_akyx8yatq1_woocommerce_wallee_completion_job 	  	Data: 0.02MB + Index: 0.03MB
wp_akyx8yatq1_woocommerce_wallee_method_configuration 	  	Data: 0.02MB + Index: 0.05MB
wp_akyx8yatq1_woocommerce_wallee_refund_job 	  	Data: 0.02MB + Index: 0.03MB
wp_akyx8yatq1_woocommerce_wallee_token_info 	  	Data: 0.02MB + Index: 0.06MB
wp_akyx8yatq1_woocommerce_wallee_transaction_info 	  	Data: 0.02MB + Index: 0.03MB
wp_akyx8yatq1_woocommerce_wallee_void_job 	  	Data: 0.02MB + Index: 0.03MB
wp_akyx8yatq1_woo_shipment_status_email 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_woo_shippment_provider 	  	Data: 0.01MB + Index: 0.00MB
wp_akyx8yatq1_woo_wallet_transactions 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_woo_wallet_transaction_meta 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_wplc_chat_msgs 	  	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_wplc_chat_sessions 	  	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_wplc_offline_messages 	  	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_wplc_webhooks 	  	Data: 0.02MB + Index: 0.00MB
wp_akyx8yatq1_yith_wcwl 	  	Data: 0.00MB + Index: 0.00MB
wp_akyx8yatq1_yith_wcwl_lists 	  	Data: 0.00MB + Index: 0.01MB
wp_akyx8yatq1_yoast_seo_links 	  	Data: 0.03MB + Index: 0.01MB
wp_akyx8yatq1_yoast_seo_meta 	  	Data: 0.03MB + Index: 0.04MB
Post Type Counts
al_product 	  	26
amn_exact-metrics 	  	1
attachment 	  	1996
audioplayer 	  	1
bp-email 	  	16
carousels 	  	1
channel 	  	1
custom_css 	  	1
customize_changeset 	  	47
jetpack_migration 	  	2
lws-wre-event 	  	3
lws-wre-pool 	  	1
lws-wre-unlockable 	  	1
mp_album 	  	1
mp_artist 	  	1
mp_band 	  	1
mp_genre 	  	1
ms_collection 	  	16
ms_song 	  	1585
nav_menu_item 	  	61
oembed_cache 	  	29
owl-carousel 	  	1
page 	  	30
post 	  	1
product 	  	126
product_variation 	  	4
revision 	  	193
sa_slider 	  	1
scheduled-action 	  	766
ship200bulk 	  	1
shop_coupon 	  	6
shop_order 	  	461
shop_order_refund 	  	140
slick_slider 	  	1
sp_wp_carousel 	  	1
tf_shop_slider 	  	1
um_directory 	  	1
um_form 	  	3
user_registration 	  	1
wafs 	  	2
wcpcsu-custom-post 	  	1
wcps 	  	1
woocarousel 	  	1
wpape_gallery_theme 	  	2
wpcd_coupons 	  	1
wpsc_cart_orders 	  	1
yith_wcps_type 	  	1
Security
Secure connection (HTTPS): 		
Hide errors from visitors 		
Active plugins (22)
WooCommerce Authorize.Net Gateway 	  	by Pledged Plugins – 5.1.2 – Not tested with the active version of WooCommerce	
AJAX Search for WooCommerce 	  	by Damian Góra – 1.4.0 – Not tested with the active version of WooCommerce	
Akismet Anti-Spam 	  	by Automattic – 4.1.2
Autoptimize 	  	by Frank Goossens (futtta) – 2.5.1
Comet Cache 	  	by WebSharks, Inc. – 170220
Customer Reviews for WooCommerce 	  	by ivole – 3.77 – Not tested with the active version of WooCommerce	
Fast Velocity Minify 	  	by Raul Peixoto – 2.7.3
Google Analytics Dashboard for WP (GADWP) 	  	by ExactMetrics – 5.3.8
GTranslate 	  	by Translate AI Multilingual Solutions – 2.8.48
Kirki Customizer Framework 	  	by Ari Stathopoulos (@aristath) – 3.0.44
WooCommerce Product Carousel Slider 	  	by AazzTech – 3.3.2 – Not tested with the active version of WooCommerce	
Refer A Friend for WooCommerce by WPGens 	  	by Goran Jakovljevic – 1.1.7 – Not tested with the active version of WooCommerce	
Ultimate Member 	  	by Ultimate Member – 2.0.54
Advanced Shipment Tracking for WooCommerce 	  	by zorem – 2.3 – Not tested with the active version of WooCommerce	
WPC Fly Cart for WooCommerce 	  	by WPclever.net – 1.6.7 – Not tested with the active version of WooCommerce	
WooCommerce Blocks 	  	by Automattic – 2.2.1 – Not tested with the active version of WooCommerce	
WooCommerce 	  	by Automattic – 3.6.5
WooRewards 	  	by Long Watch Studio – 3.5.1 – Not tested with the active version of WooCommerce	
Yoast SEO 	  	by Team Yoast – 11.7
WP Force SSL 	  	by Kostas Vrouvas – 1.4
Smush 	  	by WPMU DEV – 3.2.2.1
WP-Spreadplugin 	  	by Thimo Grauerholz – 4.4.4
Inactive plugins (4)
Hummingbird Pro 	  	by WPMU DEV – 1.9.4.1
WooCommerce Admin 	  	by WooCommerce – 0.16.0 – Not tested with the active version of WooCommerce	
WPMU DEV Dashboard 	  	by WPMU DEV – 4.7
YITH WooCommerce Quick View 	  	by YITH – 1.3.11 – Not tested with the active version of WooCommerce	
Dropin Plugins (1)
advanced-cache.php 	  	advanced-cache.php
Must Use Plugins (1)
System Plugin 	  	by – 3.9.7
Settings
API enabled: 		
Force SSL: 		
Currency 		USD ($)
Currency position 		left
Thousand separator 		,
Decimal separator 		.
Number of decimals 		2
Taxonomies: Product types 		external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomies: Product visibility 		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
Connected to WooCommerce.com: 		–
WooCommerce pages
Shop base:		#6231 - /shop/
Cart:		#6 - /cart/
Checkout:		#7 - /checkout/
My account:		#8 - /my-account/
Terms and conditions:		#717 - /return-policy/
Theme
Name: 		Online Shop
Version: 		2.0.0
Author URL: 		https://www.acmethemes.com/
Child theme: 		– If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme	
WooCommerce support: 		
Templates
Overrides: 	  	–
Action Scheduler
Action Status 	  	Count 	Oldest Scheduled Date 	Newest Scheduled Date
Complete	 	763	2019-06-29 22:04:55 -0400	2019-07-30 20:59:40 -0400
Pending	 	2	2019-07-30 21:59:40 -0400	2019-07-31 11:05:13 -0400
Canceled	 	0	–	–
In-progress	 	0	–	–
Failed	 	1	–	–

**Comment by peterfabian** [comment]
Hi, 

I wasn't able to reproduce the problem, added 5 different products to cart, removed some, each time it worked fine. 
![Screenshot 2019-07-31 at 09 45 02](https://user-images.githubusercontent.com/2207451/62193382-ee2e4280-b377-11e9-915f529680054b75.png)

Does it only happen sometimes or only for specific products? 
Were you able to reproduce this running with only WooCommerce plugin on a testing copy of your website?

**Comment by dreamesper** [comment]
Hmm... interesting. I was having trouble with ADD TO CART for desktop only... NOT mobile. I cleared history of my browser & re-opened Chrome... now, ADD TO CART works fine.

Thanks! I believe that now you can close this thread.

**Comment by peterfabian** [comment]
Thanks for coming back with a reply. I will close the ticket, then.
