### ISSUE TITLE
Order object cache doesn´t invalidate on refunds

### ISSUE THREAD

**Issue by aloco** [woocommerce/woocommerce#24274]
**Describe the bug**
We are using Redis Object Cache along WooCommerce.(https://de.wordpress.org/plugins/redis-cache/) 

It seem like the cache keys are not invalidated correctly when making a refund of an order. This causes problems on the backend order details UI and issues for other plugins like invoice / credit note generators.

As a workaround, I am using a global 5 minutes TTL via Redis Object Cache for all objects which are set with no TTL.  

**To Reproduce**
1. Setup Redis Cache and WooCommerce
2. Make an order
3. Go to order details 
4. Fully refund all items of the order
5. After saving, the order is marked as refunded, but the refunded items are not showing up (e.g. no total refund amount)
6. Flush redis cache -> everything shows up correct
7. Delete a refunded item, so its not refunded anymore
8. Amount of this refunded item turns to "0", but its still listed as refunded
9. Flush redis cache -> everything shows up correct

**Screenshots**
"Completed" Order:
<img width="1382" alt="1" src="https://user-images.githubusercontent.com/11661125/62208553-90115780-b397-11e9-9392-a65f1688c5c6.png">

"Refunded" Order, it should display the total of refunded items below the item table
<img width="1369" alt="2" src="https://user-images.githubusercontent.com/11661125/62208582-9e5f7380-b397-11e9-83d7-44c383f65d15.png">

"Refunded" Order, after flushing the redis cache, everything shows up correct
<img width="1378" alt="3" src="https://user-images.githubusercontent.com/11661125/62208612-addebc80-b397-11e9-84d6-719603e5dcd6.png">

"Refunded" Order, after removing the refunded item, the total is wrong
<img width="1364" alt="4" src="https://user-images.githubusercontent.com/11661125/62208627-ba631500-b397-11e9-9ea0-594177a08f1c.png">

**Expected behavior**
Order state is consistent replicated into the object cache.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): -
Site address (URL): -
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: ✔

### Server Environment ###

Server Info: Apache/2.4.25 (Debian)
PHP Version: 7.2.15
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2q

SUHOSIN Installed: –
MySQL Version: 5.6.44
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Datenbank-Gesamtgröße: 1.85MB
Datenbank-Datengröße: 0.87MB
Datenbank-Indexgröße: 0.98MB
wp_woocommerce_sessions: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB
wp_woocommerce_order_items: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_order_itemmeta: Daten: 0.02MB + Index: 0.03MB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB
wp_comments: Daten: 0.02MB + Index: 0.09MB
wp_links: Daten: 0.02MB + Index: 0.02MB
wp_options: Daten: 0.19MB + Index: 0.02MB
wp_postmeta: Daten: 0.09MB + Index: 0.06MB
wp_posts: Daten: 0.05MB + Index: 0.06MB
wp_termmeta: Daten: 0.02MB + Index: 0.03MB
wp_terms: Daten: 0.02MB + Index: 0.03MB
wp_term_relationships: Daten: 0.02MB + Index: 0.02MB
wp_term_taxonomy: Daten: 0.02MB + Index: 0.03MB
wp_usermeta: Daten: 0.02MB + Index: 0.03MB
wp_users: Daten: 0.02MB + Index: 0.05MB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB
wp_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB
wp_wpstatichtmloutput_meta: Daten: 0.02MB + Index: 0.00MB

### Post Type Counts ###

attachment: 17
page: 8
post: 2
product: 12
revision: 2
scheduled-action: 16
shop_order: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Redis Object Cache: von Till Krüss – 1.4.3
WooCommerce: von Automattic – 3.6.5

### Inactive Plugins (0) ###


### Dropin Plugins (1) ###

object-cache.php: Redis Object Cache Drop-In

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: #5 - /shop/
Warenkorb: #6 - /warenkorb/
Kasse: #7 - /kasse/
Mein Konto: #8 - /mein-konto/
Allgemeine Geschäftsbedingungen: ❌ Seite nicht festgelegt

### Theme ###

Name: Storefront
Version: 2.5.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 16
Oldest: 2019-07-31 13:11:23 +0200
Newest: 2019-07-31 13:12:24 +0200

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by aloco** [comment]
Hi, 

do you have any updates on this? We heavily rely on object cache due to performance reasons and have a significant number of support requests due to "incorrect" refunds. just wondering why the milestone was removed.

**Comment by lkraav** [comment]
I am also running Redis, and we have some refunds - but have never noticed any erroneous behavior thus far. I'll keep one eye more open now though.

**Comment by JulienMelissas** [comment]
I would echo what Ikraav said, we use Redis with WooCommerce on a multisite running almost 60 shops now... I don't think I've had a repot of this ever coming up. What Redis plugin are you using?

**Comment by peterfabian** [comment]
Apologies for late response. Since we haven't seen more reports of this behavior, I'm inclined to close this one. Please let us know if you still experience these problems.
