### ISSUE TITLE
Add a hook to sort fees

### ISSUE THREAD

**Issue by sebastianpopp** [woocommerce/woocommerce#24273]
**Is your feature request related to a problem? Please describe.**
I'm working on a shop where I programmatically have to add a few different fees. The second fee is calculated based on the first fee, but since the second fee is higher and woocommerce displays fees sorted by amount, the second fee always shows up before the first fee, wich is confusing for the customer.

**Describe the solution you'd like**
I'd like to have a filter in the WC_Cart_Fees::get_fees() function to be able to change the order of the fees.

**Describe alternatives you've considered**
Right now I've updated the `cart-totals.php` and `review-order.php` templates in my theme to be able to sort the fees, but I think having a hook would be a much cleaner solution and would also affect the order in the admin view.

**Additional context**
I would be happy to make those changes myself and create a pull request, but I wanted to get some feedback first. Do you think this enhancement makes sense? Would a filter make sense here? Should the existing ordering be then moved into a filter too?

**Comment by claudiosanches** [comment]
Thank you for suggesting this feature!

I'm closing the issue as it already has a PR, please continue the discussion over at #24280.
