### ISSUE TITLE
Created Variable does not contain listed Attributes

### ISSUE THREAD

**Issue by iNadav** [woocommerce/woocommerce#24290]
**Describe the bug**
I am trying to create a Product Variable using WooCommerce Rest API (https://woocommerce.github.io/woocommerce-rest-api-docs/?shell#product-properties). Sadly, whenever I create one, it creates the product variable with the correct price and image, but the attribute which is being passed doesn't get selected. even though it exists in the product attributes tab and selected as a "Variable attribute"
**cURL Code**
```
curl -X POST https://example.com/wp-json/wc/v3/products \
    -u cc:cc \
    -H "Content-Type: application/json" \
    -d '{  
   "regular_price":"549.99",
   "image":{  
      "src":"https://www.cookingclassy.com/wp-content/uploads/2014/03/hummus-31.jpg"
   },
   "attributes":[  
      {  
         "id":9,
         "options": "olive"
      }
   ]
}'
```
**Actions tried**
I  tried passing the attribute options as an array, a string, and what not. the id of the attribute was always correct as well as the id of the product. keys are definitely right since the variable is created but doesn't contain the attribute.

**Expected behavior**
The product variable should be listed with it's attribute/s. as well as the image and price that are currently listed correctly.

**WordPress Environment**
<WordPress 5.2 | OceanWP Theme>
```
Apache,
WooCommerce version 3.6.5,
PHP 7.1.30,
512mb max upload,
Memory limit 256mb
```
</details>

**Comment by claudiosanches** [comment]
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. I tried to create a variable product with variations and attributes, and it appeared to work correctly.

> even though it exists in the product attributes tab and selected as a "Variable attribute"

This sounds like the product already exists, are you trying to create a variation for your variable product?

>  I tried passing the attribute options as an array, a string, and what not. the id of the attribute was always correct as well as the id of the product. keys are definitely right since the variable is created but doesn't contain the attribute.

There's a full example of creating variable products with variations in the [REST API docs](https://woocommerce.github.io/woocommerce-rest-api-docs/?shell#create-a-product), you can see here:

```bash
curl -X POST https://example.com/wp-json/wc/v3/products \
    -u consumer_key:consumer_secret \
    -H "Content-Type: application/json" \
    -d '{
  "name": "Ship Your Idea",
  "type": "variable",
  "description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.",
  "short_description": "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
  "categories": [
    {
      "id": 9
    },
    {
      "id": 14
    }
  ],
  "images": [
    {
      "src": "http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_4_front.jpg"
    },
    {
      "src": "http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_4_back.jpg"
    },
    {
      "src": "http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_3_front.jpg"
    },
    {
      "src": "http://demo.woothemes.com/woocommerce/wp-content/uploads/sites/56/2013/06/T_3_back.jpg"
    }
  ],
  "attributes": [
    {
      "id": 6,
      "position": 0,
      "visible": false,
      "variation": true,
      "options": [
        "Black",
        "Green"
      ]
    },
    {
      "name": "Size",
      "position": 0,
      "visible": true,
      "variation": true,
      "options": [
        "S",
        "M"
      ]
    }
  ],
  "default_attributes": [
    {
      "id": 6,
      "option": "Black"
    },
    {
      "name": "Size",
      "option": "S"
    }
  ]
}'
```

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

Thanks!

**Comment by iNadav** [comment]
Hey,
My bad for some reason I got it all messed up.
I just fixed the thread, please read it again.

**Comment by claudiosanches** [comment]
@iNadav have you tried what I said?
It'sselecting attributes without any issue.

**Comment by claudiosanches** [comment]
Also make sure that exists that ID, and the value in the way you are entering it.
