### ISSUE TITLE
[REST API] Payment gateways dont update new value

### ISSUE THREAD

**Issue by deptraicogisai** [woocommerce/woocommerce#24299]
I want to update new secret_key and publishable_key in settings paymentgateway , but it cant apply new data

**Comment by rodrigoprimo** [comment]
Closing as there is not enough information to understand what is the problem and to try to reproduce it. Keep in mind that GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/

If you believe you found a WooCommerce core bug, please open another issue following the bug report template (https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=) and provide clear steps on how to reproduce the problem.
