### ISSUE TITLE
Add order manually > add fee tax rounding issue

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce#24306]
I added in wc 3.6.5 a order manually and added two lines of fees to it. After recalculating tax and order total there was a rounding issue:

item 1 is 225.00 incl. 19% tax which is net = 189.07563025210084
I see rounded values for item = 189.08 and for tax = 35.92

item 2 is 80.00 incl. 19% tax which is net = 67.226890756302521
There the rounded values are for item = 67.23 and for tax 12.77

If I put all together, there should be a order total of 305.00 but it is only 304.99

**Comment by vedanshujain** [comment]
This is a known issue and is fixed in #24024 which will be included in next release (3.7). You can also apply the patch from the PR, or [upgrade to 3.7 RC2](https://woocommerce.wordpress.com/2019/08/02/woocommerce-3-7-rc2/) if you'd like to apply fix early.
