### ISSUE TITLE
3.7 rc2: `npm run build` causes worktree changes in `assets/js/flexslider/jquery.flexslider.min.js`

### ISSUE THREAD

**Issue by lkraav** [woocommerce/woocommerce#24305]
**Describe the bug**
Git worktree should not become dirty after running `npm run build`

**To Reproduce**
0. Run `git checkout -f release/3.7`
1. Run `npm run build`
2. Run `git status`

**Screenshots**

```
leho@crdy woocommerce@3.x.git $ [git:release/3.7+?] git status
On branch release/3.7
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   assets/js/flexslider/jquery.flexslider.min.js
```

**Expected behavior**
No worktree changes after running build toolchain.

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24309.
