### ISSUE TITLE
Product Variation doesn't contain attribute WooCommerce Rest API

### ISSUE THREAD

**Issue by iNadav** [woocommerce/woocommerce#24300]
**Describe the bug**
I am trying to create a Variation for a variable type product using WooCommerce Rest API (https://woocommerce.github.io/woocommerce-rest-api-docs/?shell#create-a-product-variation). Sadly, whenever I create one, it creates the product variation with the correct price and image, but the attribute which is being passed doesn't get selected. even though it exists in the product attributes tab and selected as a "Variations attribute"
**cURL Code**
```
curl -X POST https://example.com/wp-json/wc/v3/products/IDHERE/variations \
    -u cc:cc \
    -H "Content-Type: application/json" \
    -d '{  
   "regular_price":"549.99",
   "image":{  
      "src":"https://www.cookingclassy.com/wp-content/uploads/2014/03/hummus-31.jpg"
   },
   "attributes":[  
      {  
         "id":9,
         "options": "olive"
      }
   ]
}'
```
**Actions tried**
I  tried passing the attribute options as an array, a string, and what not. the id of the attribute was always correct as well as the id of the product. keys are definitely right since the variation is created but it doesn't contain the attribute.

**Expected behavior**
The product variation should be listed with it's attribute/s. as well as the image and price that are currently listed correctly.

**WordPress Environment**
<WordPress 5.2 | OceanWP Theme>
```
Apache,
WooCommerce version 3.6.5,
PHP 7.1.30,
512mb max upload,
Memory limit 256mb
```
</details>

**Comment by rodrigoprimo** [comment]
Hi there!

GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/

I just tested and was able to successfully create a product variation with a given attribute defined. Please note that according to the documentation you should use `option` and your example says `options`, this might be what is causing the problem.

**Comment by iNadav** [comment]
> Hi there!
> 
> GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/
> 
> I just tested and was able to successfully create a product variation with a given attribute defined. Please note that according to the documentation you should use `option` and your example says `options`, this might be what is causing the problem.

I used 'option' as well, it was just a typo on this thread. I even created a new website with WooCommerce and it didn't work =/ Are you using the same environment versions I am using? I didn't start this thread for free premium support ..

**Comment by rodrigoprimo** [comment]
> I used 'option' as well, it was just a typo on this thread.

Thanks for the clarification.

> Are you using the same environment versions I am using?

I tested using the latest revision from the master branch and the latest WordPress release.

To create the attribute via the REST API, I used Insomnia and performed a POST request to the URL `https://wc.test/wp-json/wc/v3/products/339/variations` (where 339 is the ID of one of the variable products in my local install) with the following data:

```
{
  "regular_price": "9.00",
  "attributes": [
    {
      "id": 5,
      "option": "Green"
    }
  ]
}
```
