### ISSUE TITLE
New Account Email Missing Additional Content

### ISSUE THREAD

**Issue by kadencethemes** [woocommerce/woocommerce#24316]
**Describe the bug**
The customer-new-account.php template is missing:

```
/**
 * Show user-defined additonal content - this is set in each email's settings.
 */
if ( $additional_content ) {
	echo wp_kses_post( wpautop( wptexturize( $additional_content ) ) );
}
```
https://github.com/woocommerce/woocommerce/blob/master/templates/emails/customer-new-account.php

Instead, it's hardcoded:

`<p><?php esc_html_e( 'We look forward to seeing you soon.', 'woocommerce' ); ?></p>`

**To Reproduce**
1. Go to settings > emails > custom new account.
2. Edit Additional Content section.
3. Create a new account on the site so that email is sent
4. That email is be missing the edited additional content instead containing the hardcoded "We look forward to seeing you soon"

**Expected behavior**
New customer account email should pull in additional content like the rest of the emails.

Thanks!

**Comment by janakkaneriya007** [comment]
@kadencethemes 
I didn't find any section name "**Additional Content section**" in fresh WooCommerce plugin.
Note, I didn't have any extension enabled while testing your case.
Check with disabling any other WooCoomerce extension, plugins and changing the theme to the default one.
check below screenshot
![acc](https://user-images.githubusercontent.com/34676570/62447846-edd0e580-b783-11e9-9f5d-503b40cd1f59.png)

**Comment by kloon** [comment]
@kadencethemes what version of WooCommerce are you testing with? The feature is only part of WooCommerce 3.7 which is yet to be released.

**Comment by kloon** [comment]
OK, did some testing on 3.7 RC and found the output is missing there as well. Thanks for reporting, will get this fixed before the release.

**Comment by kloon** [comment]
Please see #24323 for the fix.

**Comment by kadencethemes** [comment]
Thanks, sorry should have clarified this had to do with WC 3.7

Ben
