### ISSUE TITLE
Bug: Social logins not working : Uncaught ReferenceError: Cookies is not defined

### ISSUE THREAD

**Issue by yoganebula** [woocommerce/woocommerce#24317]
**Describe the bug**
After I have added products into the cart & reach the checkout page, none of the social login feature work.

https://yoganebula.com/hatha/checkout/

**To Reproduce**
1. Goto : https://yoganebula.com/hatha/classes/surya-kriya/
2. Add the product to cart
3. Goto Checkout
4. https://yoganebula.com/hatha/checkout/
5. Try clicking on "Have an Amazon account" , or Returning customers, click here or have a coupon. - none of the links work.

Attaching the screenshot of (5)
<img width="703" alt="Screen Shot 2019-08-04 at 10 23 21 AM" src="https://user-images.githubusercontent.com/53703659/62424805-07016580-b6a2-11e9-88e1-9c0b80c29d40.png">

**Expected behavior**
This just to work just fine earlier.
I have tried deactivating all the plugins but issue persists.
I have deleted cache many times as well.

Please assist as this is an active site where students purchase classes.
I just renewed the woocommerce package last week.

**WordPress Environment**
<details>
```

WordPress environment
--
WordPress address (URL): |   | https://yoganebula.com/hatha
Site address (URL): |   | https://yoganebula.com/hatha
WooCommerce version: |   | 3.6.5
Log directory writable: |   | /home3/samirlal/yoganebula/hatha/wp-content/uploads/wc-logs/
WordPress version: |   | 4.9.10 - There is a newer version of WordPress available (5.2.2)
WordPress multisite: |   | –
WordPress memory limit: |   | 256 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –


```
</details>

**Comment by yoganebula** [comment]
<img width="1434" alt="Screen Shot 2019-08-04 at 3 41 03 PM" src="https://user-images.githubusercontent.com/53703659/62428321-64131080-b6ce-11e9-8efe-f422bf9ee16e.png">

Attaching the error that I see on console

**Comment by rodrigoprimo** [comment]
Hi there!

GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. Since you mentioned you are a paying WooCommerce.com customer, you could contact their support and they should be able to help you with your problem: http://woocommerce.com/contact-us/

Another option is to try the community support forums: https://wordpress.org/support/plugin/woocommerce.
