### ISSUE TITLE
Hook doesn't display the content on the right place

### ISSUE THREAD

**Issue by Bookyourroom** [woocommerce/woocommerce#24314]
Hey guys,

I want to style the products on the shop page and therefore I used a hook to display a certain attribute of each product. Unfaortunately, the hook doesn't place the content the right way. The hook I used was should put the output after the shop loop item, however, the attribute get's displayed before everything else.

![help](https://user-images.githubusercontent.com/44427310/62411082-d9a7af80-b5ee-11e9-9446-f4aeacda634f.JPG)

For refernece, this is the code I used: 

> add_action('woocommerce_after_shop_loop_item','displaying_product_attributes', 10);
> function displaying_product_attributes() {
>     global $product;
> 
>     $bezirk_val = $product->get_attribute('pa_bezirk');
> 
>     echo '<div class="custom-bezirk-container"><p class="custom-bezirk">'.$bezirk_val.'</p></div>';
> }

I appreciate any sort of help I can get
Thanks :)

**Comment by rodrigoprimo** [comment]
I just tested and, when using Storefront (or one of the default WordPress themes), `woocommerce_after_shop_loop_item` is called after the product information is displayed. It is likely that you are using a theme that overrides `templates/content-product.php` and that is why you are getting a different result. So this doesn't seem to be a bug in WooCommerce core and I will close this issue. Please let me know if I missed something.
