### ISSUE TITLE
tbody on Shipping Zones table displays wrong

### ISSUE THREAD

**Issue by yratof** [woocommerce/woocommerce#24326]
**Describe the bug**
Shipping zones table inherits the 'table' display, causing the thead and tbody to not be in sync.

**To Reproduce**
1) Go to Woocommerce settings
2) Go to Shipping
3) Go to Shipping Zones
4) Add several shipping zones

**Screenshots**

![image](https://user-images.githubusercontent.com/1001935/62453973-c2de9580-b773-11e9-955f-347d490cb262.png)

**Expected behavior**
Tbody should not be a table, but a table-row-group

**Comment by rodrigoprimo** [comment]
Thanks for your contribution. I will close this issue and we will continue the conversation on the PR that you opened.
