### ISSUE TITLE
HELP NEED FOR CREATE ORDER API

### ISSUE THREAD

**Issue by wifirevaithi** [woocommerce/woocommerce#24328]
Hi,

  my api create order perfectly but cannot get any response.can anyone help mew i'm i beginner to wordpress.

**Comment by claudiosanches** [comment]
Hi there. GitHub is primarily for reporting bugs and is not a support forum. We don’t support custom development here. You could ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce
