### ISSUE TITLE
request: not deprecate filter: woocommerce_geolocation_local_database_path

### ISSUE THREAD

**Issue by diablodale** [woocommerce/woocommerce#24320]
I request that the filter `woocommerce_geolocation_local_database_path` not be deprecated/removed.

## Reason

The `geo.mmdb` file is in the codebase hardcoded to download at `WP_CONTENT_DIR . '/uploads/GeoLite2-Country.mmdb'`. If this filter is removed, then it is not possible for dev/admin to manage the `geo.mmdb` location.

In my specific scenario, I do not want anyone to be able to download `geo.mmdb`. And I want to isolate as many possible Woo files into a single upload directory to reduce file proliferation. But since the `geo.mmdb` was hardcoded to `/uploads/GeoLite2-Country.mmdb`, it doesn't benefit from the forbidden downloads within `/uploads/woocommerce_uploads` nor its organization.

## Workaround

Without the filter, an admin will need to write and manage a micro-authorization-rule to deny access to that single `/uploads/GeoLite2-Country.mmdb` file.

## Related

* https://github.com/woocommerce/woocommerce/pull/22981
* https://github.com/woocommerce/woocommerce/issues/22976

**Comment by claudiosanches** [comment]
This filter is not deprecated, only a parameter that used to set a version for the deprecated GeoLite API, since we moved to this new one we don't need that parameter anymore.

**Comment by diablodale** [comment]
OK. To check for clarity....

* filter `woocommerce_geolocation_local_database_path` is not deprecated
* 1st parameter on `woocommerce_geolocation_local_database_path` ***is*** deprecated.

Did I understand that correctly? 🤔
