### ISSUE TITLE
Verificação/Validação de cpf

### ISSUE THREAD

**Issue by brazzil** [woocommerce/woocommerce#24332]
Uso o WooCommerce Extra Checkout Fields for Brazil para validar o checkout, porém, o formulário de checkout está usando plugin WooCommerce MultiStep Checkout para separar (organizar) as etapas da compra (login, dados de compra, pagamento).

O problema é que o campo cpf não é validado na etapa correta e só ativa a validação após clicar em pagar o pedido (que fica na etapa posterior). 

Como posso colocar as instruções de validação do cpf na etapa correta?

Espero ter sido claro!

Obrigado

**Comment by claudiosanches** [comment]
Hi there. GitHub is primarily for reporting bugs and is not a support forum. We don’t support custom development here. You could ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce
