### ISSUE TITLE
Notice: Trying to get property 'order_item_type' of non-object

### ISSUE THREAD

**Issue by vendidero** [woocommerce/woocommerce#24334]
The `get_order_item` method  in `WC_Order_Factory` calls `get_order_item_type` of `WC_Order_Item_Data_Store`. `get_order_item_type` loads the order item type from the DB without checking if the item exists or not. This may lead to a PHP notice if the order item does not exist and tries to be initiated through the factory.

**To Reproduce**
1. enable WP_DEBUG
2. Call `WC_Order_Factory::get_order_item( 232432 );`
3. See error

A little further checking within `get_order_item_type` should do the trick:

```php
public function get_order_item_type( $item_id ) {
	global $wpdb;
	$item_data = $wpdb->get_row( $wpdb->prepare( "SELECT order_item_type FROM {$wpdb->prefix}woocommerce_order_items WHERE order_item_id = %d LIMIT 1;", $item_id ) );
	if ( $item_data ) {
		return $item_data->order_item_type;
	}
	return false;
}
```

Cheers

**Comment by rodrigoprimo** [comment]
Thanks for your contribution. See #24353.
