### ISSUE TITLE
Bug Conflict between Gutenberg Editor and WooCommerce 3.6.5

### ISSUE THREAD

**Issue by CJ42** [woocommerce/woocommerce#24330]
**Updating a Post or Page fails with the Gutenberge editor**
I have upgraded to version 3.6.5 and since then, the Gutenberg editor doesn't work. I always obtain the red banner `Updating failed`.

To ensure that the error comes from the Gutenberg editor, I have:

- uninstalled WooCommerce and kept Gutenberg
- Disabled Gutenberg (using external Plugin, to keep classic editor) and kept WooCommerce.

The error message in the browser console is shown below:

```
/wp-json/wp/v2/posts/<post-id>?_locale=user:1 
POST Failed to load resource: the server responded with a status of 500 (Internal Server Error)
```

**To Reproduce**

1. Install Wordpress v5.5.2
2. Create a new Post or Page, click on save draft (expected: **success**)
3. Install the latest stable version of WooCommerce (3.6.5)
4. Create a new Post or Page, click on save draft (expected: **Updating failed**)
5. Open the browser console. The error message mentioned above should appear.
6. Install the plugin [Disable Gutenberg](https://wordpress.org/plugins/disable-gutenberg/), and activate it.
7. Create a new Post or Page, add some content and click on Save Draft (expected: **Update Successful**)

**Expected behavior**
Post or Page should always save / update, no matter the editor.

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
version 5.2.2

</details>

**Comment by rodrigoprimo** [comment]
Hi there, I was not able to reproduce this issue. I tested both with WooCommerce 3.6.5 and with the latest version from the master branch, and I was able to both save a post as a draft and to publish it.

Would you be able to check the PHP error log to see if there is anything there? In the PHP error log, you should see more information about the problem that caused the server to return a 500 error code and this might help us understand what is causing the problem.

Thanks

**Comment by rodrigoprimo** [comment]
Closing due to lack of feedback.
