### ISSUE TITLE
Enhancement: Add To Cart Text

### ISSUE THREAD

**Issue by NenadObradovic** [woocommerce/woocommerce#24348]
Hi guys,

Could you please consider to improve escaping for add to cart labels so we can be able to wrap it with some html tags or to add additional html tags in order to improve button style? 

At this moment inside these files
**wp-content/plugins/woocommerce/templates/loop/add-to-cart.php
wp-content/plugins/woocommerce/templates/single-product/add-to-cart/simple.php (and other single button templates)**

you escaped button text with esc_html function

```
esc_html( $product->add_to_cart_text() )
esc_html( $product->single_add_to_cart_text() )
```

and my suggestion for enhancement can be

```
wp_kses( $product->add_to_cart_text(), array( 'span' => array( 'class' => true ) ) )
wp_kses( $product->single_add_to_cart_text(), array( 'span' => array( 'class' => true ) ) )
```

Thanks for your time.

Best regards,
Nenad

**Comment by claudiosanches** [comment]
All templates can be replaced in your theme, by default we prefer escape all HTML and avoid any trouble.
