### ISSUE TITLE
Refund email could use better description about refund reason

### ISSUE THREAD

**Issue by kloon** [woocommerce/woocommerce#24346]
The refund email currently just outputs the refund reason next to the amount in the table, see image below `Testing notes`, this makes it a bit difficult to read and understand.

![](http://d.wedj.at/WABwAk+)

A suggestion is to add `Refund:` before the note in the table to make it clear that is the refund amount.

**Comment by SiR-DanieL** [comment]
Just a clarification, this is a screenshot of the Order page in My Account, where I first noticed it. It would need to be changed there as well.
