### ISSUE TITLE
"The card was declined/Invalid Card number" Message edit

### ISSUE THREAD

**Issue by ramgerges** [woocommerce/woocommerce#24342]
I am pretty new at website building, and don't have too much experience in CSS codes and php...

Here is what I'm trying to solve, and wasn't able to do so far:
What I would like to do is edit the "card decline" or "invalid card number" (and all of the related error messages) that woocommerce gives out on the checkout page...

I'm trying to add some humorous messages instead... something like "oops! looks like you're out of money..." instead of the generic messages.

I've been trying to find the location of those "credit card error" messages and wasn't able to find it.

Can somebody point me to the right direction and how I could edit those messages? Perhaps there is a CSS code for that? or maybe a .php file in the woocommerce plugin itself where I can simply edit the message to the one that I would be needing?

Thank you for your help!

![1](https://user-images.githubusercontent.com/53842263/62585933-3faf6380-b889-11e9-9bad-968f51052665.jpg)
![2](https://user-images.githubusercontent.com/53842263/62585934-4047fa00-b889-11e9-930a-cdc10c04de91.jpg)

**Comment by rodrigoprimo** [comment]
Hi there!

GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/
