### ISSUE TITLE
Sale Price Dates

### ISSUE THREAD

**Issue by stormit** [woocommerce/woocommerce#24345]
Hello,

I'm a developer. I'm having a problem with **Sale price dates**. I set From Date to a future date. On that date, WooCommerce's cron clears that field [https://prnt.sc/opfdjk](https://prnt.sc/opfdjk). But it is necessary for our feature. Can that field be kept?

Thank you very much!

**Comment by vedanshujain** [comment]
Thanks for reporting the issue. I am not sure if this will be a helpful change for the community in general so I am closing this issue.
That said, if you'd want to keep track of sale date you can perhaps hook into `woocommerce_update_product` and save the data somewhere else?
