### ISSUE TITLE
Datatype issues

### ISSUE THREAD

**Issue by mch0lic** [woocommerce/woocommerce#24356]
**Describe the bug**
Take a look at is_existing_sku( $product_id, $sku ) PHPDoc declaration:
https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-product-data-store-cpt.php#L948

Declared return type is *bool*, return type is *string*, technically it's always going to be an *int* since query returns post ID. 

Question is, is this intended behaviour that 3rd party developers can rely on (result being string/int) or this an actual bug?

If this is intended behaviour, then perhaps it's worth looking at filter *wc_product_has_unique_sku* and change $sku_found variable name to something more meaningful and less confusing since *sku_found* implies true/false value or at the least sku itself, yet we get product_id?

https://github.com/woocommerce/woocommerce/blob/master/includes/wc-product-functions.php#L560

I know this is a bit nitpicking but it's not clear if this is intended behaviour or this is an actual bug and 3rd party developer should not rely on that ID coming through when hooking into the filter.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment]
It should return boolean, you should not rely in the ID, not that the interfaces describes as boolean as well.

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24385.
