### ISSUE TITLE
On update product category page, after changes made, can't update

### ISSUE THREAD

**Issue by warrenjfisher** [woocommerce/woocommerce#24363]
**Describe the bug**
 - UPDATE button overlaid with WooCommerce message and does not highlight on cursor over to allow update

**To Reproduce**
1. Go to product categories in woocommerce
2. Edit a product category - any field
3. Go to update at bottom - button does not work

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by JuanchoPestana** [comment]
Hey @warrenjfisher ,
I've tried to reproduce this bug but haven't been able to! Could you please provide a bit more information? Versions, any particular settings activated, theme used, etc?
Thanks a lot and hope we can fix this!

**Comment by warrenjfisher** [comment]
Thanks for getting back to me.

 

Here are the details:

WooCommerce Version:  3.6.5
Theme:  Highend Version:  3.5.2.1

Site:  https://catnipbill.com

 

Page is:



 

Here is the issue:



 

The update button is overwritten with the message 'Thank you for selling
with WooCommerce' and I cant find any way for the cursor to get the update
to react.  The image shows that I also have Yoast Premium installed -
current version 3.8.

 

BTW - I do have another site - https://www.winebuyoftheday.com - same theme,
same yoast, same version WooCommerce - and it works properly. See below.
And there are a number of differences in the other plugins; but the
woocommerce plugins are the same as below.



 

Here are the WooCommerce related plugins

I have admin enabled on the site that does not work right
https://catnipbill.com 

Not enabled on the site that does work.  (I have not tried testing it this a
fix yet).

 



 

Let me know what else you need.

 

Thanks,

 

Warren

 

________________________

Warren J. Fisher

ZevMir, LLC

 <http://www.zevmir.com/> www.zevmir.com

+1 917-362-1111 cell

This email and any files transmitted with it are confidential and may be
privileged information and are intended solely for the use of the individual
or entity to who they are addressed.  If you are not the intended recipient
(or have received this email in error please note that any disclosure,
distribution, or copying of this email is strictly prohibited.   If received
in error, please delete this email and attachments and confirm this to the
sender.

**Comment by warrenjfisher** [comment]
The bug is when WooCommerce Admin is enabled

 

Warren

 

From: warren.jack.fisher@gmail.com <warren.jack.fisher@gmail.com> 
Sent: Friday, August 9, 2019 1:29 PM
To: 'woocommerce/woocommerce'
<reply@reply.github.com>;
'woocommerce/woocommerce' <woocommerce@noreply.github.com>
Cc: 'Mention' <mention@noreply.github.com>
Subject: RE: [woocommerce/woocommerce] On update product category page,
after changes made, can't update (#24363)

 

Thanks for getting back to me.

 

Here are the details:

WooCommerce Version:  3.6.5
Theme:  Highend Version:  3.5.2.1

Site:  https://catnipbill.com

 

Page is:



 

Here is the issue:



 

The update button is overwritten with the message 'Thank you for selling
with WooCommerce' and I cant find any way for the cursor to get the update
to react.  The image shows that I also have Yoast Premium installed -
current version 3.8.

 

BTW - I do have another site - https://www.winebuyoftheday.com - same theme,
same yoast, same version WooCommerce - and it works properly. See below.
And there are a number of differences in the other plugins; but the
woocommerce plugins are the same as below.



 

Here are the WooCommerce related plugins

I have admin enabled on the site that does not work right
https://catnipbill.com 

Not enabled on the site that does work.  (I have not tried testing it this a
fix yet).

 



 

Let me know what else you need.

 

Thanks,

 

Warren

 

________________________

Warren J. Fisher

ZevMir, LLC

 <http://www.zevmir.com/> www.zevmir.com

+1 917-362-1111 cell

This email and any files transmitted with it are confidential and may be
privileged information and are intended solely for the use of the individual
or entity to who they are addressed.  If you are not the intended recipient
(or have received this email in error please note that any disclosure,
distribution, or copying of this email is strictly prohibited.   If received
in error, please delete this email and attachments and confirm this to the
sender.

**Comment by JuanchoPestana** [comment]
Hey Warren, 
I installed the "Highend" theme and checked that my versions match yours but still couldn't manage to reproduce the error...

Have you tried doing the basic steps like checking if there are any plugins/themes out of date?
Checking for any particular setting you have different from the other site that works?

I'm sorry if I'm not being of much help, but without being able to reproduce the bug it's a bit complicated to find out what's causing it!

**Comment by warrenjfisher** [comment]
The bug is when WooCommerce Admin is Activated.   I turned it off and it
worked fine.

 

Warren

**Comment by JuanchoPestana** [comment]
Awesome, glad you found it!

**Comment by rrennick** [comment]
This was reported in https://github.com/woocommerce/woocommerce-admin/issues/2682 and will be fixed in the next release of WooCommerce Admin.
