### ISSUE TITLE
digital doa

### ISSUE THREAD

**Issue by jgfrm** [woocommerce/woocommerce#24368]
## Steps to reproduce the issue
1. Create a downloadable product
2. Order that product
3. Receive the email with the hyperlink to the product
4. Download the product by clicking the link

## Expected/actual behavior

When I follow those steps, I see...
error "Call to a member function get_billing_email() on boolean"

I was expecting to see...
Download of the digitial product

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

WordPress address (URL): https://dev.intra.thevalueengineers.nl
Site address (URL): https://dev.intra.thevalueengineers.nl
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 8 GB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.13-1+0~20181207100540.13+stretch~1.gbpf57305
PHP Post Max Size: 500 MB
PHP Time Limit: 1600
PHP Max Input Vars: 2000
cURL Version: 7.52.1
OpenSSL/1.0.2s

SUHOSIN Installed: –
MySQL Version: 5.7.21
Max Upload Size: 500 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: wp_tve_
MaxMind GeoIP Database: ✔
Total Database Size: 100.27MB
Database Data Size: 76.59MB
Database Index Size: 23.68MB
wp_tve_woocommerce_sessions: Data: 1.52MB + Index: 0.05MB
wp_tve_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_tve_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_tve_woocommerce_downloadable_product_permissions: Data: 0.05MB + Index: 0.06MB
wp_tve_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB
wp_tve_woocommerce_order_itemmeta: Data: 0.14MB + Index: 0.14MB
wp_tve_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_tve_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_tve_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_tve_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_tve_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_tve_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_tve_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_tve_woocommerce_log: Data: 0.02MB + Index: 0.02MB
cerber_acl: Data: 0.02MB + Index: 0.00MB
cerber_blocks: Data: 0.02MB + Index: 0.00MB
cerber_countries: Data: 0.02MB + Index: 0.00MB
cerber_lab: Data: 0.02MB + Index: 0.00MB
cerber_lab_ip: Data: 0.02MB + Index: 0.00MB
cerber_lab_net: Data: 0.02MB + Index: 0.02MB
cerber_log: Data: 0.02MB + Index: 0.05MB
cerber_qmem: Data: 0.02MB + Index: 0.02MB
cerber_traffic: Data: 0.05MB + Index: 0.02MB
oepl_crm_map_fields: Data: 0.02MB + Index: 0.00MB
wp_e3value_aiowps_events: Data: 0.02MB + Index: 0.00MB
wp_e3value_aiowps_failed_logins: Data: 0.02MB + Index: 0.00MB
wp_e3value_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB
wp_e3value_aiowps_login_activity: Data: 0.06MB + Index: 0.00MB
wp_e3value_aiowps_login_lockdown: Data: 0.02MB + Index: 0.00MB
wp_e3value_aiowps_permanent_block: Data: 0.02MB + Index: 0.00MB
wp_e3value_cerber_files: Data: 0.02MB + Index: 0.00MB
wp_e3value_cerber_sets: Data: 0.02MB + Index: 0.00MB
wp_e3value_cerber_uss: Data: 0.02MB + Index: 0.02MB
wp_e3value_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_e3value_comments: Data: 0.13MB + Index: 0.09MB
wp_e3value_cptch_images: Data: 0.02MB + Index: 0.00MB
wp_e3value_cptch_packages: Data: 0.02MB + Index: 0.00MB
wp_e3value_cptch_whitelist: Data: 0.02MB + Index: 0.02MB
wp_e3value_discourse_nonce: Data: 0.02MB + Index: 0.00MB
wp_e3value_links: Data: 0.02MB + Index: 0.02MB
wp_e3value_lockdowns: Data: 0.02MB + Index: 0.00MB
wp_e3value_login_fails: Data: 0.06MB + Index: 0.00MB
wp_e3value_ngg_album: Data: 0.02MB + Index: 0.02MB
wp_e3value_ngg_gallery: Data: 0.02MB + Index: 0.02MB
wp_e3value_ngg_pictures: Data: 0.02MB + Index: 0.02MB
wp_e3value_options: Data: 2.50MB + Index: 0.06MB
wp_e3value_postmeta: Data: 6.52MB + Index: 3.03MB
wp_e3value_posts: Data: 3.52MB + Index: 0.22MB
wp_e3value_redirection_404: Data: 0.08MB + Index: 0.06MB
wp_e3value_redirection_groups: Data: 0.02MB + Index: 0.03MB
wp_e3value_redirection_items: Data: 0.02MB + Index: 0.08MB
wp_e3value_redirection_logs: Data: 0.08MB + Index: 0.08MB
wp_e3value_slim_events: Data: 0.38MB + Index: 0.23MB
wp_e3value_slim_events_archive: Data: 0.02MB + Index: 0.02MB
wp_e3value_slim_stats: Data: 3.52MB + Index: 0.17MB
wp_e3value_slim_stats_archive: Data: 0.02MB + Index: 0.02MB
wp_e3value_sm_sessions: Data: 10.55MB + Index: 0.00MB
wp_e3value_snippets: Data: 0.06MB + Index: 0.00MB
wp_e3value_termmeta: Data: 0.02MB + Index: 0.03MB
wp_e3value_terms: Data: 0.02MB + Index: 0.03MB
wp_e3value_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_e3value_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_e3value_usermeta: Data: 1.52MB + Index: 3.03MB
wp_e3value_users: Data: 0.09MB + Index: 0.05MB
wp_e3value_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_e3value_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_e3value_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_e3value_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB
wp_e3value_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB
wp_e3value_woocommerce_downloadable_product_permissions: Data: 0.09MB + Index: 0.14MB
wp_e3value_woocommerce_log: Data: 0.02MB + Index: 0.02MB
wp_e3value_woocommerce_order_itemmeta: Data: 0.27MB + Index: 0.27MB
wp_e3value_woocommerce_order_items: Data: 0.06MB + Index: 0.02MB
wp_e3value_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB
wp_e3value_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB
wp_e3value_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB
wp_e3value_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB
wp_e3value_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB
wp_e3value_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB
wp_e3value_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB
wp_e3value_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB
wp_e3value_yoast_seo_links: Data: 0.06MB + Index: 0.02MB
wp_e3value_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB
wp_smackformrelation: Data: 0.02MB + Index: 0.00MB
wp_smackleadbulider_field_manager: Data: 0.02MB + Index: 0.00MB
wp_smackleadbulider_form_field_manager: Data: 0.02MB + Index: 0.00MB
wp_smackleadbulider_shortcode_manager: Data: 0.02MB + Index: 0.00MB
wp_smackthirdpartyformfieldrelation: Data: 0.02MB + Index: 0.00MB
wp_smack_ecom_info: Data: 0.02MB + Index: 0.00MB
wp_tve_aiowps_events: Data: 0.02MB + Index: 0.00MB
wp_tve_aiowps_failed_logins: Data: 0.23MB + Index: 0.00MB
wp_tve_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB
wp_tve_aiowps_login_activity: Data: 0.06MB + Index: 0.00MB
wp_tve_aiowps_login_lockdown: Data: 0.02MB + Index: 0.00MB
wp_tve_aiowps_permanent_block: Data: 0.02MB + Index: 0.00MB
wp_tve_commentmeta: Data: 0.02MB + Index: 0.03MB
wp_tve_comments: Data: 0.08MB + Index: 0.09MB
wp_tve_duplicator_packages: Data: 0.02MB + Index: 0.02MB
wp_tve_groups_capability: Data: 0.02MB + Index: 0.03MB
wp_tve_groups_file: Data: 0.02MB + Index: 0.05MB
wp_tve_groups_file_access: Data: 0.02MB + Index: 0.00MB
wp_tve_groups_file_group: Data: 0.02MB + Index: 0.00MB
wp_tve_groups_group: Data: 0.02MB + Index: 0.02MB
wp_tve_groups_group_capability: Data: 0.02MB + Index: 0.02MB
wp_tve_groups_user_capability: Data: 0.02MB + Index: 0.02MB
wp_tve_groups_user_group: Data: 0.05MB + Index: 0.02MB
wp_tve_inbound_events: Data: 0.02MB + Index: 0.00MB
wp_tve_inbound_page_views: Data: 0.02MB + Index: 0.00MB
wp_tve_inbound_tracked_links: Data: 0.02MB + Index: 0.00MB
wp_tve_layerslider: Data: 0.02MB + Index: 0.00MB
wp_tve_layerslider_revisions: Data: 0.02MB + Index: 0.00MB
wp_tve_links: Data: 0.02MB + Index: 0.02MB
wp_tve_lockdowns: Data: 0.02MB + Index: 0.00MB
wp_tve_login_fails: Data: 0.17MB + Index: 0.00MB
wp_tve_masterslider_options: Data: 0.02MB + Index: 0.02MB
wp_tve_masterslider_sliders: Data: 0.02MB + Index: 0.02MB
wp_tve_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB
wp_tve_ms_snippets: Data: 0.02MB + Index: 0.00MB
wp_tve_ngg_album: Data: 0.02MB + Index: 0.02MB
wp_tve_ngg_gallery: Data: 0.02MB + Index: 0.02MB
wp_tve_ngg_pictures: Data: 0.02MB + Index: 0.02MB
wp_tve_options: Data: 3.44MB + Index: 0.08MB
wp_tve_postmeta: Data: 2.52MB + Index: 1.92MB
wp_tve_posts: Data: 6.50MB + Index: 0.36MB
wp_tve_qsot_event_zone_to_order: Data: 0.02MB + Index: 0.06MB
wp_tve_qsot_ticket_codes: Data: 0.02MB + Index: 0.02MB
wp_tve_redirection_404: Data: 4.52MB + Index: 5.83MB
wp_tve_redirection_groups: Data: 0.02MB + Index: 0.03MB
wp_tve_redirection_items: Data: 0.02MB + Index: 0.09MB
wp_tve_redirection_logs: Data: 3.52MB + Index: 2.72MB
wp_tve_revslider_css: Data: 0.13MB + Index: 0.00MB
wp_tve_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB
wp_tve_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB
wp_tve_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB
wp_tve_revslider_navigations: Data: 0.02MB + Index: 0.00MB
wp_tve_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB
wp_tve_revslider_sliders: Data: 0.02MB + Index: 0.00MB
wp_tve_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB
wp_tve_revslider_slides: Data: 0.02MB + Index: 0.00MB
wp_tve_revslider_slides_bkp: Data: 0.02MB + Index: 0.00MB
wp_tve_revslider_static_slides: Data: 0.02MB + Index: 0.00MB
wp_tve_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB
wp_tve_slim_events: Data: 0.17MB + Index: 0.13MB
wp_tve_slim_events_archive: Data: 0.02MB + Index: 0.02MB
wp_tve_slim_stats: Data: 8.52MB + Index: 2.59MB
wp_tve_slim_stats_archive: Data: 0.02MB + Index: 0.02MB
wp_tve_sm_sessions: Data: 12.56MB + Index: 0.00MB
wp_tve_snippets: Data: 0.08MB + Index: 0.00MB
wp_tve_termmeta: Data: 0.02MB + Index: 0.03MB
wp_tve_terms: Data: 0.02MB + Index: 0.03MB
wp_tve_term_relationships: Data: 0.02MB + Index: 0.02MB
wp_tve_term_taxonomy: Data: 0.02MB + Index: 0.03MB
wp_tve_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB
wp_tve_wc_admin_notes: Data: 0.02MB + Index: 0.00MB
wp_tve_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB
wp_tve_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB
wp_tve_wc_download_log: Data: 0.02MB + Index: 0.03MB
wp_tve_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB
wp_tve_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB
wp_tve_wc_order_stats: Data: 0.02MB + Index: 0.05MB
wp_tve_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB
wp_tve_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB
wp_tve_wc_webhooks: Data: 0.02MB + Index: 0.02MB
wp_tve_woocommerce_multisafepay: Data: 0.02MB + Index: 0.00MB
wp_tve_wp_topbar_data: Data: 0.02MB + Index: 0.00MB
wp_tve_yoast_seo_links: Data: 0.08MB + Index: 0.02MB
wp_tve_yoast_seo_meta: Data: 0.06MB + Index: 0.00MB

### Post Type Counts ###

amn_wpforms-lite: 3
attachment: 232
awl_filter_gallery: 1
custom_css: 1
customize_changeset: 242
display_type: 7
ditty_news_ticker: 2
encyclopedia: 12
flipboxes: 2
mts_notification_bar: 2
nav_menu_item: 51
nelioab_alt_page: 2
nelioab_local_exp: 7
ngg_gallery: 4
ngg_pictures: 4
oembed_cache: 4
page: 49
portfolio: 5
post: 37
post_grid: 1
product: 19
product_variation: 39
qsot-event: 3
qsot-event-area: 1
qsot-venue: 1
revision: 756
scheduled-action: 49
shop_coupon: 7
shop_order: 156
woo_multii_layout: 2
wpforms: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (85) ###

LayerSlider WP: by Kreatura Media – 6.8.4
User Switching in Admin Bar: by Mark Wilkinson – 1.1.1
Advanced Menu Widget: by Ján Bočínec – 0.4.1
Akismet Anti-Spam: by Automattic – 4.1.2
All In One WP Security: by Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.3.9.4

Amazon Link Engine: by GeoRiot Networks
Inc. – 1.3.6

Automatic Copyright Year: by WPSOS – 1.1
BAW Login/Logout menu: by Juliobox – 1.3.3
Child Theme Configurator: by Lilaea Media – 2.5.0
Classic Editor: by WordPress Contributors – 1.5
Code Snippets: by Shea Bunge – 2.13.3
Component Shortcodes: by Theme4Press – 1.0.1
Cookie Notice: by dFactory – 1.2.46
Disable Feeds: by Samir Shah
BBpress support by Matthew Sigley – 1.4.4

Display Posts: by Bill Erickson – 3.0.2
Ditty News Ticker: by Metaphor Creations – 2.2.4
Slack Notifications: by dorzki – 2.0.5
Duplicator: by Snap Creek – 1.3.18
Email Address Encoder: by Till Krüss – 1.0.19
Email Return-Path Header Fix: by Abdussamad Abdurrazzaq – 0.1
Encyclopedia Lite: by Dennis Hoppe – 1.7.28
Enhanced Media Library: by wpUXsolutions – 2.7.2
Export Users to CSV: by Matt Cromwell – 1.1.1
Flip Boxes: by Cool Plugins – 1.5
footnotes: by ManFisher Medien ManuFaktur – 1.6.5
Groups File Access: by itthinx – 1.6.3
Groups: by itthinx – 2.8.0
Hide Admin Bar From Non-admins: by Stranger Studios – 1.0
Hide Title: by Dojo Digital – 1.0.8
Easy HTTPS (SSL) Redirection: by Tips and Tricks HQ – 1.9
Collapse-O-Matic: by twinpictures
baden03 – 1.7.11

Login LockDown: by Michael VanDeMar – v1.7.1
Max Mega Menu: by megamenu.com – 2.7.1.4
Menu Icons: by ThemeIsle – 0.11.5
Menu Items Visibility Control: by Hassan Derakhshandeh – 0.3.7
Modify Product Page Layout for WooCommerce: by Robin Metcalfe  –  – Not tested with the active version of WooCommerce
Mollie Payments for WooCommerce: by Mollie – 5.2.1
NextGEN Gallery: by Imagely – 3.2.10
NS Remove Related Products for WooCommerce: by NsThemes – 2.3.0 – Not tested with the active version of WooCommerce
Parallax One Plus: by Themeisle – 1.4.2
PDF Embedder: by Lever Technology LLC – 4.4
Post Grid by PickPlugins: by PickPlugins – 2.0.38
Read More Without Refresh: by George Gkouvousis – 3.1
Recent Posts Widget Extended: by Satrya – 0.9.9.7
Redirection: by John Godley – 4.3.3
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.1
Remove Dashboard Access: by Drew Jaynes (DrewAPicture) – 1.1.3
Responsive Image Maps: by Philip Newcomer – 1.4
Slider Revolution: by ThemePunch – 6.0.1
Shortcode in Menus: by Gagan Deep Singh – 3.5
SlideShare: by Team Yoast – 1.9.2
Easy Updates Manager: by Easy Updates Manager Team – 8.0.5
SVG Support: by Benbodhi – 2.3.15
Sync SugarCRM Users - extended: by dan – 2.6
Theme Check: by Otto42
pross – 20190801.1

Under Construction: by WebFactory Ltd – 3.50
User Role Editor: by Vladimir Garagulya – 4.51.2
User Switching: by John Blackbourn & contributors – 1.5.1
WaterWoo PDF: by Little Package – 2.4.3
WC Disable Zoom / Lightbox features: by Rynaldo Stoltz – 1.0 – Not tested with the active version of WooCommerce
Widget Box: by Theme4Press – 1.1.0
Woo Coupon URL: by PersonalDiscount – 1.0.0
Woo Product Multi Layout lite: by eDataStyle – 1.7
WooCommerce Admin: by WooCommerce – 0.16.0
WooCommerce Checkout Manager: by Visser Labs – 4.3
WooCommerce Email Validation: by Hugh Lashbrooke – 2.1.1 – Not tested with the active version of WooCommerce
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.7.5

WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.3.1
WooCommerce: by Automattic – 3.6.5
WordPress Importer: by wordpressdotorg – 0.6.4
Yoast SEO: by Team Yoast – 11.8 – Not tested with the active version of WooCommerce
WP-Cron Control: by Thorsten Ott
Erick Hitter
Automattic – 0.7.1

WP Mail SMTP: by WPForms – 1.5.2
WP-Markdown: by Stephen Harris – 1.6.1
WP-Members: by Chad Butler – 3.2.9.3
WP Migrate DB: by Delicious Brains – 1.0.11
WP Notification Bars: by MyThemeShop – 1.0.5
WP-Orphanage Extended: by MELONIQ.NET – 1.1
WP reCaptcha Integration: by Jörn Lund – 1.2.1
WP Session Manager: by Eric Mann – 4.2.0
WP Simple Mail Sender: by Enrique Chavez – 1.0.2
Slimstat Analytics: by Jason Crouse – 4.8.5
WP User Avatar: by flippercode – 2.2.4
WPForms Lite: by WPForms – 1.5.4.2
Custom Product Tabs for WooCommerce: by YIKES
Inc. – 1.6.10

### Inactive Plugins (8) ###

Equivalent Mobile Redirect: by uniquelylost – 4.2
jQuery Updater: by Ramoonus – 3.4.1
Nelio A/B Testing: by Nelio Software – 4.7.6
Page Builder by SiteOrigin: by SiteOrigin – 2.10.6
Shortcodes Anywhere or Everywhere: by David Gewirtz – 1.4.2
Shortcodes Everywhere: by HappyPlugins – 1.0.1
SiteOrigin Widgets Bundle: by SiteOrigin – 1.15.7
User Session Synchronizer: by Rafasashi – 1.3.82

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
registrations (registrations)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #349 - /shop/
Cart: #350 - /cart/
Checkout: #351 - /checkout/
My account: #352 - /my-account/
Terms and conditions: #338 - /terms-and-conditions/

### Theme ###

Name: evolve Plus Child
Version: 1.0.0
Author URL: http://theme4press.com
Child Theme: ✔
Parent Theme Name: evolve Plus
Parent Theme Version: 2.9.8.1
Parent Theme Author URL: https://theme4press.com
WooCommerce Support: ✔

### Templates ###

Overrides: evolve-plus/woocommerce/cart/cart-shipping.php
evolve-plus/woocommerce/cart/cart-totals.php
evolve-plus/woocommerce/cart/cart.php
evolve-plus/woocommerce/cart/shipping-calculator.php
evolve-plus/woocommerce/checkout/form-billing.php
evolve-plus/woocommerce/checkout/form-checkout.php
evolve-plus/woocommerce/checkout/form-shipping.php
evolve-plus/woocommerce/checkout/payment-method.php
evolve-plus/woocommerce/checkout/review-order.php
evolve-plus/woocommerce/checkout/thankyou.php
evolve-plus/woocommerce/content-product.php
evolve-plus/woocommerce/content-product_cat.php
evolve-plus/woocommerce/content-single-product.php
evolve-plus/woocommerce/global/breadcrumb.php
evolve-plus/woocommerce/global/quantity-input.php
evolve-plus/woocommerce/loop/add-to-cart.php
evolve-plus/woocommerce/loop/loop-end.php
evolve-plus/woocommerce/loop/loop-start.php
evolve-plus/woocommerce/loop/no-products-found.php
evolve-plus/woocommerce/loop/pagination.php
evolve-plus/woocommerce/myaccount/dashboard.php
evolve-plus/woocommerce/myaccount/form-login.php
evolve-plus/woocommerce/myaccount/form-lost-password.php
evolve-plus/woocommerce/myaccount/my-account.php
evolve-plus/woocommerce/notices/error.php
evolve-plus/woocommerce/notices/notice.php
evolve-plus/woocommerce/notices/success.php
evolve-plus/woocommerce/single-product/add-to-cart/external.php
evolve-plus/woocommerce/single-product/add-to-cart/grouped.php
evolve-plus/woocommerce/single-product/add-to-cart/simple.php
evolve-plus/woocommerce/single-product/add-to-cart/variable.php
evolve-plus/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
evolve-plus/woocommerce/single-product/meta.php
evolve-plus/woocommerce/single-product/price.php
evolve-plus/woocommerce/single-product/product-image.php
evolve-plus/woocommerce/single-product/product-thumbnails.php
evolve-plus/woocommerce/single-product/short-description.php
evolve-plus/woocommerce/single-product/tabs/additional-information.php
evolve-plus/woocommerce/single-product/tabs/description.php
evolve-plus/woocommerce/single-product/tabs/tabs.php
evolve-plus/woocommerce/single-product/title.php
evolve-plus/woocommerce/single-product-reviews.php

### Action Scheduler ###

Complete: 14
Oldest: 2019-06-27 14:20:06 +0000
Newest: 2019-06-27 15:00:19 +0000

Pending: 35
Oldest: 2019-04-20 19:43:30 +0000
Newest: 2019-08-08 09:48:43 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

Fix:
woocommerce/includes/class-wc-order-item-product.php
public function get_item_downloads() {
                $files      = array();
                $product    = $this->get_product();
                $order      = $this->get_order();
                $product_id = $this->get_variation_id() ? $this->get_variation_id() : $this->get_product_id();
                if ( $order ) {
                        $email_hash = function_exists( 'hash' ) ? hash( 'sha256', $order->get_billing_email() ) : sha1( $order->get_billing_email() );
                }

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24384.
