### ISSUE TITLE
WooCommerce/Stripe Order Processing Customer Email and Page Redirect Problems

### ISSUE THREAD

**Issue by bens0811** [woocommerce/woocommerce#24377]
**Describe the bug**
When I click the Place Order button on the WooCommerce Checkout page of my website, the customer does not receive an order confirmation email (even though it is enabled in the email tab) and the Checkout page is not redirected to the Order Confirmation page. The order processes and I receive an email notification for the order but the customer does not. When pressing the Place Order button, the page just looks like it's reloading, even though an actual order is processed. The problem seemed to begin after I installed a shipment tracking information plugin. However, after uninstalling it and deleting it the problems persist. It has never processed an order properly since the first time it stopped working. I have tried uninstalling and reinstalling the Stripe gateway plugin but to no avail. I found a thread where someone else was having the exact same issue and Wordpress couldn't solve it and told him to contact WooCommerce. I happen to also be using Flatsome as he was. https://wordpress.org/support/topic/customers-not-receiving-an-order-confirmation/page/2/

STATUS REPORT

WordPress address (URL): https://cococaye.com
Site address (URL): https://cococaye.com
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.33 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 260 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.65.3
OpenSSL/1.0.2s

SUHOSIN Installed: –
MySQL Version: 5.6.41-84.1
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 13.16MB
Database Data Size: 12.58MB
Database Index Size: 0.58MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.00MB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_order_itemmeta: Data: 0.03MB + Index: 0.02MB
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB
wp_aioo_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_aioo_comments: Data: 0.00MB + Index: 0.00MB
wp_aioo_layerslider: Data: 0.00MB + Index: 0.00MB
wp_aioo_links: Data: 0.00MB + Index: 0.00MB
wp_aioo_options: Data: 0.53MB + Index: 0.04MB
wp_aioo_postmeta: Data: 0.04MB + Index: 0.02MB
wp_aioo_posts: Data: 0.38MB + Index: 0.02MB
wp_aioo_revslider_css: Data: 0.01MB + Index: 0.00MB
wp_aioo_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
wp_aioo_revslider_settings: Data: 0.00MB + Index: 0.00MB
wp_aioo_revslider_sliders: Data: 0.00MB + Index: 0.00MB
wp_aioo_revslider_slides: Data: 0.00MB + Index: 0.00MB
wp_aioo_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
wp_aioo_termmeta: Data: 0.00MB + Index: 0.00MB
wp_aioo_terms: Data: 0.00MB + Index: 0.01MB
wp_aioo_term_relationships: Data: 0.00MB + Index: 0.00MB
wp_aioo_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_aioo_usermeta: Data: 0.00MB + Index: 0.01MB
wp_aioo_users: Data: 0.00MB + Index: 0.01MB
wp_aioo_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB
wp_aioo_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB
wp_aioo_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB
wp_aioo_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB
wp_aioo_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB
wp_aioo_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB
wp_aioo_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB
wp_aioo_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB
wp_aioo_woocommerce_termmeta: Data: 0.00MB + Index: 0.00MB
wp_aioo_wpsl_stores: Data: 0.00MB + Index: 0.00MB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_comments: Data: 0.01MB + Index: 0.01MB
wp_contactic_notices: Data: 0.00MB + Index: 0.00MB
wp_contactic_st: Data: 0.00MB + Index: 0.00MB
wp_contactic_submits: Data: 0.00MB + Index: 0.01MB
wp_failed_jobs: Data: 0.00MB + Index: 0.00MB
wp_links: Data: 0.00MB + Index: 0.00MB
wp_mailchimp_carts: Data: 0.00MB + Index: 0.00MB
wp_nyyp_commentmeta: Data: 0.00MB + Index: 0.00MB
wp_nyyp_comments: Data: 0.00MB + Index: 0.01MB
wp_nyyp_links: Data: 0.00MB + Index: 0.00MB
wp_nyyp_options: Data: 0.03MB + Index: 0.01MB
wp_nyyp_postmeta: Data: 0.00MB + Index: 0.01MB
wp_nyyp_posts: Data: 0.00MB + Index: 0.01MB
wp_nyyp_terms: Data: 0.00MB + Index: 0.01MB
wp_nyyp_term_relationships: Data: 0.00MB + Index: 0.00MB
wp_nyyp_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_nyyp_usermeta: Data: 0.00MB + Index: 0.01MB
wp_nyyp_users: Data: 0.00MB + Index: 0.00MB
wp_options: Data: 1.85MB + Index: 0.06MB
wp_postmeta: Data: 0.16MB + Index: 0.08MB
wp_posts: Data: 9.37MB + Index: 0.14MB
wp_queue: Data: 0.00MB + Index: 0.00MB
wp_revslider_css: Data: 0.09MB + Index: 0.00MB
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB
wp_revslider_navigations: Data: 0.00MB + Index: 0.00MB
wp_revslider_sliders: Data: 0.01MB + Index: 0.00MB
wp_revslider_slides: Data: 0.02MB + Index: 0.00MB
wp_revslider_static_slides: Data: 0.00MB + Index: 0.00MB
wp_social_users: Data: 0.00MB + Index: 0.00MB
wp_termmeta: Data: 0.00MB + Index: 0.01MB
wp_terms: Data: 0.00MB + Index: 0.01MB
wp_term_relationships: Data: 0.00MB + Index: 0.00MB
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB
wp_usermeta: Data: 0.02MB + Index: 0.02MB
wp_users: Data: 0.00MB + Index: 0.01MB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB
wp_wpfm_backup: Data: 0.00MB + Index: 0.00MB
wp_yith_wcwl: Data: 0.00MB + Index: 0.00MB
wp_yith_wcwl_lists: Data: 0.00MB + Index: 0.01MB

### Post Type Counts ###

attachment: 24
blocks: 2
customize_changeset: 115
nav_menu_item: 9
page: 22
post: 5
product: 2
revision: 1313
scheduled-action: 4
shop_coupon: 1
shop_order: 26
store_locator: 1
woo_discount: 1
wpcf7_contact_form: 2
yith-wcet-etemplate: 1
ywdpd_discount: 8

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

All-in-One WP Migration File Extension: by ServMask
Inc. – 1.5

All-in-One WP Migration: by ServMask – 7.4
Classic Editor: by WordPress Contributors – 1.5
Contact Form 7: by Takayuki Miyoshi – 5.1.4
Contactic: by Contactic – 1.4.0
WooCommerce Continue Shopping: by HappyKite – 1.3.1 – Not tested with the active version of WooCommerce
Duplicate Page: by mndpsingh287 – 3.9
Mailchimp for WooCommerce: by Mailchimp – 2.1.17
Nextend Social Login: by Nextendweb – 3.0.20
Slider Revolution: by ThemePunch – 5.4.8.1
Uber Login Logo: by UberWeb – 1.5.1
Use Any Font: by Dinesh Karki – 5.3
WC Password Strength Settings: by Daniel Santoro – 2.1.0
Checkout Field Editor for WooCommerce: by ThemeHiGH – 1.3.4
WooCommerce Stripe Gateway: by WooCommerce – 4.2.3
WooCommerce: by Automattic – 3.6.5
WooSidebars: by WooCommerce – 1.4.5
WP File Manager: by mndpsingh287 – 5.2
WP Mail SMTP: by WPForms – 1.5.2
WP Multi Store Locator Pro: by WpExpertsio – 2.9
WP Social Icons: by Magnigenie – 1.1
YITH WooCommerce Wishlist: by YITH – 2.2.12

### Inactive Plugins (9) ###

Akismet Anti-Spam: by Automattic – 4.1.2
Hello Dolly: by Matt Mullenweg – 1.7.2
Really Simple SSL: by Rogier Lankhorst
Mark Wolters – 3.2.3

Sticky Menu (or Anything!) on Scroll: by Mark Senff – 2.1.1
WooCommerce Email Customizer: by WooCommerce – 1.1.10
WooCommerce Smart Coupons: by StoreApps – 4.0.8
YITH WooCommerce Dynamic Pricing and Discounts Premium: by YITH – 1.5.3
YITH WooCommerce Email Templates Premium: by YITH – 1.3.17 – Not tested with the active version of WooCommerce
YITH WooCommerce Share For Discounts Premium: by YITH – 1.5.3

### Must Use Plugins (4) ###

Endurance Browser Cache: by Mike Hansen – 0.4
Endurance Page Cache: by Mike Hansen – 1.6
Endurance PHP Edge: by Mike Hansen – 0.2
SSO: by Garth Mortensen
Mike Hansen – 0.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #280 - /shop/
Cart: #281 - /shopping-cart/
Checkout: #282 - /checkout/
My account: #283 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: coco-caye
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.8.3
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
coco-caye/woocommerce/emails/customer-completed-order.php
coco-caye/woocommerce/emails/customer-new-account.php
coco-caye/woocommerce/emails/customer-processing-order.php
coco-caye/woocommerce/emails/customer-refunded-order.php
coco-caye/woocommerce/emails/customer-reset-password.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

### Action Scheduler ###

Complete: 4
Oldest: 2019-07-15 04:11:06 +0000
Newest: 2019-08-09 03:58:14 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

**Comment by rodrigoprimo** [comment]
Hi there!

GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/
