### ISSUE TITLE
Missing 'applied_coupon' trigger in checkout.js

### ISSUE THREAD

**Issue by kolyasapphire** [woocommerce/woocommerce#24370]
**Is your feature request related to a problem? Please describe.**

There is a useful JS trigger 'applied_coupon' on the cart page (line 456), however there is none for the checkout page where coupons can also be entered.

https://github.com/woocommerce/woocommerce/blob/6c263c97b6fc9d6ba675d68e36ddb77349866569/assets/js/frontend/cart.js#L448-L463

**Describe the solution you'd like**
Add the trigger on success of coupon submission in checkout.js:
https://github.com/woocommerce/woocommerce/blob/6c263c97b6fc9d6ba675d68e36ddb77349866569/assets/js/frontend/checkout.js#L574-L590

**Additional context**

This trigger is valuable to run some JS on coupon submission, for example for coupon analytics - count how many times a particular code was applied, but not checked out with. This improvement would allow developers to use the same code on both checkout and cart pages.

Please add any suggestions / better solutions you may have, thanks in advance!

**Comment by kolyasapphire** [comment]
If I'm not missing anything I can create a pull request. We can just add this line on 585 of checkout.js:

`$( document.body ).trigger( 'applied_coupon', [ code ] );`

**Comment by kloon** [comment]
@kolyasapphire feel free to open the Pull Request with the changes. Thanks!

**Comment by claudiosanches** [comment]
Thank you for suggesting this feature!

I'm closing the issue as it already has a PR, please continue the discussion over at #24406.
