### ISSUE TITLE
Print Default

### ISSUE THREAD

**Issue by paanda88** [woocommerce/woocommerce#24381]
After printing and processing my orders, I mark each order in turn as " Order Complete " the print option then opens up, and wants to print all the orders I have already printed. I am sure this is not supposed to happen.

**Comment by claudiosanches** [comment]
By default WooCommerce doesn't include any "print option" like you are describing. Sounds like that feature comes for some integration/plugin.

**Comment by claudiosanches** [comment]
Closing since this repository is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. Please contact the author directly for support.
