### ISSUE TITLE
Product gallery image pushes gallery thumbnails downward

### ISSUE THREAD

**Issue by paaljoachim** [woocommerce/woocommerce#24407]
**Describe the bug**
I have noticed when using various height gallery product images that the highest image in the gallery will push all the thumbnails down even though it is not active.

Add a high image among the various other square gallery images. Notice the last gallery image is higher then the other images.
![Screen Shot 2019-08-14 at 20 03 03](https://user-images.githubusercontent.com/5323259/63044507-a3abda80-bece-11e9-8dee-5539fd319a4e.png)

Viewing the product on the frontend. Here on can see that the thumbnails are pushed very far down. Even though the high image is not seen in the viewport it still has an effect.

![Screen Shot 2019-08-14 at 20 03 16](https://user-images.githubusercontent.com/5323259/63044543-b9b99b00-bece-11e9-8e16-9eb6959726fc.png)

Removing the high image brings it almost back to normal distance. There is still an image that is a little higher then the other images.

![Screen Shot 2019-08-14 at 20 06 17](https://user-images.githubusercontent.com/5323259/63044705-12893380-becf-11e9-8b2a-ed712a56f176.png)

Images not seen in the view port should not have an effect on the page. As can be seen in the first screenshot.

**Comment by claudiosanches** [comment]
The space generated to display the images will consider all images on your product, like that last image that doesn't use an square, will require more height to be displayed.
This sounds related to your image settings, since not forcing hard crop, will probably get images in different size like that, that may generate different height in the gallery.

**Comment by paaljoachim** [comment]
Ok. Thanks for the feedback!
