### ISSUE TITLE
Add to cart templates loaded differently based on is_purchasable() 

### ISSUE THREAD

**Issue by digitalchild** [woocommerce/woocommerce#24400]
**Describe the bug**
When setting a products` is_purchasable()` to false  the add to cart templates are loaded differently for simple products and variable products. The` is_purchasable()` short circuits the loading of the add-to-cart.php template for simple products. This means that any actions in this template are not loaded if the product is not purchasable. This results in any plugin that hooks into the actions in this template not firing. This is not the case for variable products. Even when the product `is_purchasable()` is false the template still loads. This means that the actions load for variable products but not for simple products with the same state. 

**To Reproduce**
1. Set a simple product is_purchasable() as false. 
2. Load the single product page and the add to cart template is not loaded, including all the relevant actions wrapped in that template. The button is missing. 
3. Set a variable product is_purchasable() as false. 
4. Load the single product page and the add to cart template is still loaded, however the add to cart button is disabled. The relevant actions wrapped in that template still load. 

**Expected behavior**
The actions should be loaded for both simple and variable products so that plugins that hook into these actions (such as a Wishlist plugin) can still function. 

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
WordPress 5.2.2, WooCommerce 3.7.0 
</details>

**Comment by claudiosanches** [comment]
>  The actions should be loaded for both simple and variable products so that plugins that hook into these actions (such as a Wishlist plugin) can still function.

Plugins like that have another actions to hook into.
Variations work differently from single product, and as I said, there's better actions to use.

**Comment by digitalchild** [comment]
If they behave differently then why is the same action declared in the two different add-to-cart templates? If they have the same action name it should be assumed that they should function the same.
