### ISSUE TITLE
Shortcode shows no preview in backend Gutenberg

### ISSUE THREAD

**Issue by paaljoachim** [woocommerce/woocommerce#24402]
**Describe the bug**
WooCommerce version 3.7.0

**Backend**

Adding product shortcode such as [product_page id="255"] into a default paragraph block shows it like so.

![Screen Shot 2019-08-14 at 13 53 52](https://user-images.githubusercontent.com/5323259/63019207-f9668f80-be9a-11e9-96d2-7514863064c2.png)

The same goes for adding the shortcode block. The product is not rendered in the backend.

**Frontend**

Previewing the page. Shows the product on the frontend.

![Screen Shot 2019-08-14 at 13 55 35](https://user-images.githubusercontent.com/5323259/63019339-4c404700-be9b-11e9-9458-28f73f760fda.png)

**Expected behavior**
I expect to see the shortcode rendered on the backend.

I have tested on a live dev site and a local site using Chrome. Both web sites do not show a rendered preview on the backend.

**Comment by paaljoachim** [comment]
Part 2.

There are additional errors showing the shortcode as I tried to do so above.

I added 3 different shortcodes for 3 different products but the frontend showed 3 duplicates of the same product.



I then added the tinymce/classic block and added a short code:
![Screen Shot 2019-08-14 at 20 39 49](https://user-images.githubusercontent.com/5323259/63047028-dad0ba80-bed3-11e9-89fb-071ad35803ae.png)

Short code 1. Shows one product
Short code 2 and 3 should show the same product.

![Screen Shot 2019-08-14 at 20 42 03](https://user-images.githubusercontent.com/5323259/63047087-fdfb6a00-bed3-11e9-8b78-efc0ef636a27.png)

**Comment by paaljoachim** [comment]
I kept playing around with the shortcode and the classic blocks. They are not showing what they should. 

There are no console errors on the page.

Bottom line: I just want to show a product based on what it looks like in the product page. I have hidden with css and removed various fields I do not need to show.

**Comment by claudiosanches** [comment]
> I have tested on a live dev site and a local site using Chrome. Both web sites do not show a rendered preview on the backend.

WooCommerce don't intent to show any preview in the backend for shortcodes like that, mostly we don't include any code to render because we are already moving those into new blocks.

Also I tried to use multiple `product_page` shortcode in the same page and seems to be working just fine, maybe some global not setting properly in your theme. Still `product_page` doesn't sound the correct shortcode to render inside columns, I know that is only for testing, but there's better shortcodes on WooCommerce for it.

**Comment by paaljoachim** [comment]
I have begun to experiment with the product block instead of using the shortcodes and I am noticing that they are working fairly well. 

NB! A product block is showing what it would look like on a shop page and not in the single product page though.
