### ISSUE TITLE
woocommerce_update_product_stock_query

### ISSUE THREAD

**Issue by gremlindeg** [woocommerce/woocommerce#24410]
In version 3.6.1 it was $sql = apply_filters( 'woocommerce_update_product_stock_query', $sql, $product_id_with_stock, $stock_quantity, $operation );

but after that it is 
$sql = apply_filters( 'woocommerce_update_product_stock_query', $sql, $product_id_with_stock, $stock_quantity, 'set' );

may be it is better to return information about operation in the filter?

**Comment by kloon** [comment]
@gremlindeg the operation is still passed but just hardcoded to set. What value are you expecting there to be sent through?

**Comment by gremlindeg** [comment]
@kloon  On updating product's count i want to know previous count value and new count value

**Comment by claudiosanches** [comment]
>  On updating product's count i want to know previous count value and new count value

Not sure how this is related if the change, you that pointed out, as @kloon said, the only changing in the last argument that is only the `$operation` that is now hard coded, but it's the same operation yet.
