### ISSUE TITLE
Order items are not refunding anymore after creating orders programmatically 

### ISSUE THREAD

**Issue by Johnny99211** [woocommerce/woocommerce#24413]
I've maybe found a bug because the order items are not refunded anymore (just the whole price of the order). Every step described uses a normal WooCommerce function provided for these kind of customization (no manual database changes are made).

Everything starts with a form I have where a user can fill out some order details. When he clicks a submit button, the order get's created with the status `pending` via an AJAX request:

```
$order = wc_create_order();
try {
	$order->set_created_via( 'create-order-form' );
	$order->set_customer_id( get_current_user_id() );
	$order->set_customer_ip_address( WC_Geolocation::get_ip_address() );
	$order->set_customer_user_agent( wc_get_user_agent() );
	$order->calculate_totals();
} catch ( WC_Data_Exception $e ) {
	wp_send_json_error( $response, 500 );
	wp_die();
}
```
This works very good. No logging errors in the `debug.log` or any issues happens. From this step on the customer can see his order in his account. 

At the `view-order` page he has now a button which he can click to add a product to the cart (which get's defined by me):

```
try {
	WC()->cart->empty_cart();
	WC()->cart->add_to_cart( $my_defined_product_id );
	$response = array(
		'url' => get_permalink( get_option( 'woocommerce_checkout_page_id' ) )
	);
	wp_send_json_success( $response, 200 );
} catch ( Exception $e ) {
	wp_send_json_error( null, 500 );
	wp_die();
}
```
When everything was added, the user get's redirected to the checkout where he can see the product and everything. Now he can click a custom checkout button. Instead of creating a new order, I'm using the `woocommerce_create_order` hook to return my previous created order id which is saved in the user meta. I'm also doing some stuff which I've copied from the method normally used to create a new order during the checkout: 

```
add_action( 'woocommerce_create_order', 'checkout_use_existing_order', 10, 2 );
function checkout_use_existing_order( $tmp_id, $checkout ) {

	foreach ( WC()->cart->get_cart() as $cart_item ) {
		$product_id = $cart_item['product_id'];
	}

	if ( ! empty( $product_id ) ) {
		$order_id = get_post_meta( get_current_user_id(), 'order_id', true );

		if ( ! empty( $order_id ) ) {
			$order = wc_get_order( $order_id );

			$cart_hash          = WC()->cart->get_cart_hash();
			$available_gateways = WC()->payment_gateways->get_available_payment_gateways();
			$order_vat_exempt   = WC()->cart->get_customer()->get_is_vat_exempt() ? 'yes' : 'no';
			$data               = $checkout->get_posted_data();

			try {
				$fields_prefix = array(
					'shipping' => true,
					'billing'  => true,
				);

				$shipping_fields = array(
					'shipping_method' => true,
					'shipping_total'  => true,
					'shipping_tax'    => true,
				);

				foreach ( $data as $key => $value ) {
					if ( is_callable( array( $order, "set_{$key}" ) ) ) {
						$order->{"set_{$key}"}( $value );
					} elseif ( isset( $fields_prefix[ current( explode( '_', $key ) ) ] ) ) {
						if ( ! isset( $shipping_fields[ $key ] ) ) {
							$order->update_meta_data( '_' . $key, $value );
						}
					}
				}

				//We need to do this to prevent duplicate items added afterwards
				do_action( 'woocommerce_resume_order', $order_id );
				$order->remove_order_items();

				$order->set_cart_hash( $cart_hash );
				$order->update_meta_data( 'is_vat_exempt', $order_vat_exempt );
				$order->set_currency( get_woocommerce_currency() );
				$order->set_prices_include_tax( 'yes' === get_option( 'woocommerce_prices_include_tax' ) );
				$order->set_customer_note( $data['order_comments'] ?? '' );
				$order->set_payment_method( $available_gateways[ $data['payment_method'] ] ?? $data['payment_method'] );
				$order->set_shipping_total( WC()->cart->get_shipping_total() );
				$order->set_discount_total( WC()->cart->get_discount_total() );
				$order->set_discount_tax( WC()->cart->get_discount_tax() );
				$order->set_cart_tax( WC()->cart->get_cart_contents_tax() + WC()->cart->get_fee_tax() );
				$order->set_shipping_tax( WC()->cart->get_shipping_tax() );
				$order->set_total( WC()->cart->get_total( 'edit' ) );
				WC()->checkout()->create_order_line_items( $order, WC()->cart );
				WC()->checkout()->create_order_fee_lines( $order, WC()->cart );
				WC()->checkout()->create_order_shipping_lines( $order, WC()->session->get( 'chosen_shipping_methods' ), WC()->shipping()->get_packages() );
				WC()->checkout()->create_order_tax_lines( $order, WC()->cart );
				WC()->checkout()->create_order_coupon_lines( $order, WC()->cart );

				$order->save();

				do_action( 'woocommerce_checkout_update_order_meta', $order_id, $data );

				return $order_id;
			} catch ( Exception $e ) {
				return new WP_Error( 'checkout-error', $e->getMessage() );
			}
		} else {
			return new WP_Error( 'checkout-error', 'Error' );
		}
	} else {
		return new WP_Error( 'checkout-error', 'Error' );
	}
}
```

The order get's now paid but is still in the pending status until the customer clicked another button. But before this, he can use a cancel button to cancel the order:

```
// Prepare line items which we are refunding
$line_items = array();
if ( $items = $order->get_items() ) {
    foreach ( $items as $item_id => $item ) {
        $line_total = wc_get_order_item_meta( $item_id, '_line_total' );
        $qty        = wc_get_order_item_meta( $item_id, '_qty' );
        $refund_tax = $item['total_tax'];
        $line_items[ $item_id ] = array(
            'qty'          => $qty,
            'refund_total' => wc_format_decimal( $line_total ),
            'refund_tax'   => $refund_tax,
        );
    }
}

refund( $order->get_total(), $refund_reason, $order_id, $line_items, true );

function refund( $refund_amount, $refund_reason, $order_id, $line_items, $refund_payment ) {

    try {
        $refund = wc_create_refund( array(
            'amount'         => $refund_amount,
            'reason'         => $refund_reason,
            'order_id'       => $order_id,
            'line_items'     => $line_items,
            'refund_payment' => $refund_payment
        ) );
    } catch ( Exception $e ) {
        wp_send_json_error( null, 500 );

        return 'An error occurred during the refund: ' . $e;
    }

    return $refund;
}
```

This is the output of the` $items` array:

```
[15-Aug-2019 16:05:03 UTC] Array
(
    [amount] => 512.30
    [reason] => Strange problems
    [order_id] => 5518
    [line_items] => Array
        (
            [436] => Array
                (
                    [qty] => 1
                    [refund_total] => 400
                    [refund_tax] => 76
                )

        )

    [refund_payment] => 1
)
```

And now the strange thing happens: The order get's fully cancelled but not the line items. There is no red arrow showing at the line item which should be fully refounded. When I try to get the refunds for an order via `$order->get_refounds()`, the result is also empty but it shouldn't:

![image](https://user-images.githubusercontent.com/43766368/63133548-0e8c0d00-bfc6-11e9-9bab-a7c45904fbad.png)

Normally the refounded order should looks like this:

![image](https://user-images.githubusercontent.com/43766368/63133503-ca990800-bfc5-11e9-8847-76b89878489c.png)

I'm so confused. I've debugged everything but I can't find the problem. Maybe this is a bug I found, I'm not sure. Maybe someone of the programmers can check this? This would be very helpful. Thanks a lot!

**Comment by Johnny99211** [comment]
I think I've found the problem. I'm unsetting the order status `wc-completed` via the `wc_order_statuses` hook. When I move it back in and reload the refunded order at the dashboard, everything seems to look normal. The` get_refunds()` method also works and returns the correct refund. 

So now it would be nice to know why this happens? Because I don't need the `wc-completed` status anymore. Are there any bindings or so?

**Comment by Johnny99211** [comment]
The refunds are having the status `[status] => completed` so I can't remove it. Otherwise it won't work. But this should be maybe changed I think so that the refund get's his own status.

**Comment by claudiosanches** [comment]
You should let WooCommerce change the status if needed after the refunds, also if you are just cancelling before any payment, there's no reason to record any refund.
Closing since this issue is for a custom development, we doesn't sounds like an issue on WooCommerce, but we can open again if it's really an issue on WooCommerce.
