### ISSUE TITLE
Branding Question: Naming an add-on plugin

### ISSUE THREAD

**Issue by justintadlock** [woocommerce/woocommerce#24411]
Sorry for posting this on GitHub. However, I haven't received a reply via email and am planning on publishing a new plugin tomorrow that integrates one of my plugins with WooCommerce.

I'm creating an add-on for my [Members plugin](https://wordpress.org/plugins/members) that will better integrate WooCommerce's roles and capabilities into the UI.  I'm wanting to make sure that I respect any trademark/branding with the plugin name.

I have two ideas for naming the plugin:

- Members - WooCommerce Integration
- Members - WC Integration 

Are either of these acceptable?

I've done several of these integrations with other plugins, and the naming scheme has been acceptable for them.  I just want to double check before publishing with you.

The Members add-on will not utilize any other WC branding outside of the description and just describing what the plugin does in general.

**Comment by kloon** [comment]
Hi @justintadlock, thanks for reaching out first.

Both those names are acceptable, as long as your plugin does not start with the name WooCommerce or denotes that it is an official WooCommerce plugin/extension anywhere it should be fine.

You are also not allowed to use the official logos and branding as your plugin images without obtaining permission first.

**Comment by justintadlock** [comment]
@kloon - Awesome! Thanks.
