### ISSUE TITLE
Grouped Products made of Variations

### ISSUE THREAD

**Issue by gbruzzo** [woocommerce/woocommerce#24418]
Hello there

we have a store whose products are exclusively variations. The 'products' are 'music releases' whose variations are the products actually being sold (CD / Vinyl / downloadable file of music release xyz). Tried to create a grouped product involving these variations, but the admin search form does not return variations. Adding the main product to a group makes no sense. Bundled and composite products are way too complicated for our goals. 

As a matter of fact, on line 15 of file /woocommerce/includes/admin/meta-boxes/views/html-product-data-linked-products.php  we find

`data-action="woocommerce_json_search_products"`

 this could be changed to 

`data-action="woocommerce_json_search_products_and_variations"`

making it possible to search for selectwoo to return all variations and thus allow creation of a grouped product of variations. 

Should we submit a pull request? 

Cheers

Giacomo Bruzzo

**Comment by claudiosanches** [comment]
Grouped products doesn't support variations, it's not designed to support variations, only changing that line doesn't provide proper support for it.
You should use composite products or any other of the alternatives instead.
