### ISSUE TITLE
Order Received page remove few sections

### ISSUE THREAD

**Issue by vbzl** [woocommerce/woocommerce#24424]
Woocommerce version 3.6.4

Hi, I am looking into removing few sections from the order received confirmation page. I do not wish to make changes in the main php file, instead I would like to add a snippet code in to the plugin.

I'd like to remove Woocommerce order details and customer details from the order-received page only.

"woocommerce-order-overview woocommerce-thankyou-order-details order_details"
"woocommerce-order-details" including the table "woocommerce-table woocommerce-table--order-details shop_table order_details"
"woocommerce-customer-details"

Please advise the snippet code I could use to achieve this. Thanks.

<img width="1169" alt="woocommerce" src="https://user-images.githubusercontent.com/54083066/63223007-551a7b00-c203-11e9-9dcf-c1b72b12fc20.png">

**Comment by claudiosanches** [comment]
Hi there. GitHub is primarily for reporting bugs and is not a support forum. We don’t support custom development here. You could ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce
