### ISSUE TITLE
Order emails printing double content

### ISSUE THREAD

**Issue by Yammaski** [woocommerce/woocommerce#24420]
When printing an order email that contains more than 2 pages, the "email-order-details.php" tfoot ... /tfoot & thead ... /thead is printed on every page.
This issue is in ThunderBird and the webmail from my host. In Windows Live Mail the print looks ok.

WordPress 5.2.2 - WooCommerce 3.6.5 - PHP 7.2.20

How can I solve this issue ?

In attach an example print with TB and WLM.
[order_71213_Print-TB.pdf](https://github.com/woocommerce/woocommerce/files/3511808/order_71213_Print-TB.pdf)
[order_71213_Print-WLM.pdf](https://github.com/woocommerce/woocommerce/files/3511809/order_71213_Print-WLM.pdf)

Best Regards,
Yam.

**Comment by grigorijurasov** [comment]
14508399-hc - I've tested this with both Thunderbird and Gmail and I see "Subtotal", "Shipping", "Payment method" and "Total" fields repeated on multiple pages:

https://d.pr/free/i/5VPKQ5

**Comment by claudiosanches** [comment]
> When printing an order email that contains more than 2 pages, the "email-order-details.php" tfoot ... /tfoot & thead ... /thead is printed on every page.

Emails are converted into HTML before sent, also by default browsers, and softwares or services like Thunderbird or Gmail may repeat any content from `thead` inside new pages, this is an expected behavior.
