### ISSUE TITLE
Need to change `wc_product_meta_lookup` table structure datatype size for min_price and max_price

### ISSUE THREAD

**Issue by itzmekhokan** [woocommerce/woocommerce#24428]
**Describe the bug**
If you set your product price greater than equal 100,000,000, you will face the issues that backend product list table price filter ( desc ) not working as well as woocommerce `widget_price_filter` also not working. After debugging I found that if you set any product price above or greater than above, woocommerce set value of `min_price/max_price` field with 99999999.99 ( maximum size and decimal point ) of table `wc_product_meta_lookup`.

**To Reproduce**
1. Go to backend Products and add / edit any product
2. Set its price to 100,000,000 to greater and save it.
3. Now filter products list table by price DESC.
4. Or add "Filter Products by Price" widget in shop sidebar and see the widget price range.

**Screenshots**
![Table columns value](https://user-images.githubusercontent.com/13062380/63251603-ac642e00-c28b-11e9-902e-2730e8967919.png)
![Product List Table filter](https://user-images.githubusercontent.com/13062380/63251683-d584be80-c28b-11e9-9f13-ee5cbefb9084.png)
![Price filter widget](https://user-images.githubusercontent.com/13062380/63251724-ea615200-c28b-11e9-9684-b4584ce750c2.png)

**Expected behavior**
For widget "Filter Products by Price" the price range should be set with the maximum or minimum value of products.
For backend products list table product should be shown as price DESC value properly.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

WordPress environment
--
WordPress address (URL): |   | http://localhost/wp
Site address (URL): |   | http://localhost/wp
WooCommerce version: |   | 3.7.0
WooCommerce REST API package: |   | 1.0.2 /data/html/wp/wp-content/plugins/woocommerce/packages/woocommerce-rest-api
Log directory writable: |   | /data/html/wp/wp-content/uploads/wc-logs/
WordPress version: |   | 5.2.2
WordPress multisite: |   | –
WordPress memory limit: |   | 256 MB
WordPress debug mode: |   |  
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –

</details>

**Comment by claudiosanches** [comment]
cc @mikejolley

**Comment by vedanshujain** [comment]
We currently cast values to `decimal(10, 2)` in a few places which would need to be updated as well.

**Comment by camilolunacom** [comment]
Any updates on the ETA for this fix?
