### ISSUE TITLE
Filter by price widget does not work for large denomination currencies

### ISSUE THREAD

**Issue by iamgabrielma** [woocommerce/woocommerce#24427]
The widget `Filter by price ` seems to have an upper limit of 9 digits, which does not work for currencies like the Vietnamese dongs where normal prices are in the millions.

For example 100.000.000 dong ( which is the upper limit of this widget can filter) would be around 4.900€

Reported on 2284995-zen

**To Reproduce**
1. Go to WooCommerce > Settings, set your store currency to Vietnamese dong.
2. Go to Appearance > Widgets > enable `Filter by price`
3. Set a product or more with a price higher than 100.000.000d (100 million)
4. See that is not possible to filter them.

<img width="1288" alt="Screen Shot 2019-08-19 at 14 52 47" src="https://user-images.githubusercontent.com/3812076/63248224-0f0bf880-c291-11e9-91ac-40af0bc44521.png">

**Comment by claudiosanches** [comment]
This is not an enhancement, it's a bug, closing since it's better described by #24428
