### ISSUE TITLE
Changing wording/cart and checkout tables

### ISSUE THREAD

**Issue by drenina** [woocommerce/woocommerce#24421]
On the cart contents tablehead and in the order review tablhead, there is a table cell called "Total". This is not the correct wording since it is NOT the total - additional taxes, fees etc might come into place. The actual Total should only be used for the cart totals table at the very bottom as well as the last row in the order review table. currently the only way to change is by overriding the files or editing the original files - if you change it with Poedit for example, the word Total would be changed EVERYWHERE.

**Comment by claudiosanches** [comment]
Thank you for suggesting this feature!

I'm closing the issue as it already has a PR, please continue the discussion over at #24440.
