### ISSUE TITLE
View Order: Fatal error if order does not exist

### ISSUE THREAD

**Issue by strayobject** [woocommerce/woocommerce#24434]
**Describe the bug**
Fatal error when attempting to view order that does not exist in my account.

`Fatal error: Uncaught Error: Call to a member function get_status() on boolean in /vagrant/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-my-account.php:144`

**To Reproduce**
 - Go to my account -> orders -> view order
 - Enter random order id in the url (make sure it does not exist in WC)
 - Server responds with 500 and the error above.

**Screenshots**
n/a

**Expected behavior**
An error indicating invalid order.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24435.
