### ISSUE TITLE
Namibian dollar as `N$`, not `$`

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce#24431]
**Is your feature request related to a problem? Please describe.**
It is confusing for customers to have `$` for Namibian dollars as their currency symbol is `N$`

**Describe the solution you'd like**
I went through WooCommerce currencies and noticed that New Taiwan dollar has `NT$` symbol. Is there any reason why it has its special dollar symbol while others do not?

![https://cld.wthms.co/AxkaD2](https://cld.wthms.co/AxkaD2+) 
Full Size: https://cld.wthms.co/AxkaD2

**Describe alternatives you've considered**
I have provided the customer with the code snippet from https://docs.woocommerce.com/document/change-a-currency-symbol/

**Comment by claudiosanches** [comment]
This is a bug in fact, if the currency symbol is incorrect.

**Comment by claudiosanches** [comment]
>  I went through WooCommerce currencies and noticed that New Taiwan dollar has NT$ symbol. Is there any reason why it has its special dollar symbol while others do not?

Some currencies uses by default `$`, but if you find any in that list that requires new symbols, we can update.

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24438.
