### ISSUE TITLE
Cancelled Order not emailing me

### ISSUE THREAD

**Issue by pexlechris** [woocommerce/woocommerce#24448]
Hi. When a user in my site procced to payment and then cancel his payment. The order is marked as Cancelled in my Woo Backoffice, but the email for this cancelled order is not sendind to myself, so I can offer to this user an offer, discount etc...
Is there a solution?

**Comment by SiR-DanieL** [comment]
The Cancelled order email is only sent if the order status was Processing or On Hold. In your case, it seems like it was Pending Payment, in which case the email is not triggered.
