### ISSUE TITLE
3.7: Backordered Products Missing Backordered Label on Front End

### ISSUE THREAD

**Issue by DynAggelos** [woocommerce/woocommerce#24458]
**Describe the bug**
When products are set to backordered, they no longer show up as backordered to the customer on either the product page or anywhere else. This means customers will think backordered products are in stock.

**To Reproduce**
1. Set any product to backordered.
2. Go to the product page, and look for a notice that the product is backordered.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**Comment by kloon** [comment]
Hi @DynAggelos, that is correct the label does say `Allow back-orders?` which implies that you are allowing it on the product but not setting the status. All stock statuses are controlled by the inventory level.

I would not call this a bug, if you want to set a product as backordered you will have to make it "sold out" by setting the stock level to 0, and then ensure the `Allow back-orders?` option is checked.

**Comment by DynAggelos** [comment]
I wish you had spent a little more time trying to understand what my issue was about. In my original post I said, "When products are set to backordered, they no longer show up as backordered to the customer." That does _not_ mean the product was set to "Allow Backorders?," that means the product was set to "On Backorder" with the "Manage Stock?" option unticked. This most certainly is a bug, and this behavior was recently introduced in 3.7.

![image](https://user-images.githubusercontent.com/35944457/63979782-53f91180-ca7f-11e9-92ec-ac4a76263a7f.png)
Product is set to backordered.

![Uploading image.png…]()
Customer doesn't see "Backordered", and thinks it is in stock.

**Comment by kloon** [comment]
Thanks for the additional information and screenshots, makes it much more understandable where the issue lies. We will take a look.

**Comment by DynAggelos** [comment]
Thanks, I appreciate it.

**Comment by kloon** [comment]
Closed in #24559
