### ISSUE TITLE
WooCommerce 3.7 REST API (v2 & v3) Random "woocommerce_product_invalid_image_id" error when update a product

### ISSUE THREAD

**Issue by SirTronco** [woocommerce/woocommerce#24470]
Hi! 
First of all, sorry for my english!

This issue happens after upgrading to WooCommerce 3.7

I'm sending this update request (interchangeably with batch or directly):
`{"update":[{"id": 171860, "images": [{"src": "https://www.dore-denia.com/wp-content/uploads/imatges/ET-0002-0.jpg",  "position": 0 }]  }]}
`
And it usually works!

But sometimes the web responses:
```
{
  "update": [
    {
      "id": 171860,
      "error": {
        "code": "woocommerce_product_invalid_image_id",
        "message": "#172281 es un ID de imagen no válido.",
        "data": {
          "status": 400
        }
      }
    }
  ]
}
```

I've tried to send the same request several times (unmodified), trying to find a behavior..and it appears to randomly works:  **sometimes succesfully, sometimes fail**

I have noted that the ID in the error message, is increasing. I think maybe there is a problem creating new image IDs.

**I have tried the following:**
- If the product already has an image, results in a random success/fail
- If the product has **not** an image, results in a random success/fail
- Putting the exact ID of an existing image, results in **successfully every time**, like this:
`{"update":[{"id": 171860, "images": [{ "id":172279, "src": "https://www.dore-denia.com/wp-content/uploads/imatges/ET-0002-0.jpg",  "position": 0 }]  }]}
`

Thanks!

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment and System Status**
`
### WordPress Environment ###

WordPress address (URL): https://www.dore-denia.com
Site address (URL): https://www.dore-denia.com
WC Version: 3.7.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.8
PHP Post Max Size: 64 MB
PHP Time Limit: 600
PHP Max Input Vars: 5000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.7.27-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Tamaño total de la base de datos: 518.75MB
Tamaño de los datos de la base de datos: 435.70MB
Tamaño del índice de la base de datos: 83.05MB
wp_woocommerce_sessions: Datos: 60.09MB + Índice: 3.02MB + Motor InnoDB
wp_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_order_itemmeta: Datos: 0.08MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_berocket_termmeta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_comments: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
wp_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_ms_snippets: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_options: Datos: 8.23MB + Índice: 1.03MB + Motor InnoDB
wp_postmeta: Datos: 322.94MB + Índice: 54.16MB + Motor InnoDB
wp_posts: Datos: 37.56MB + Índice: 20.06MB + Motor InnoDB
wp_revslider_css: Datos: 0.13MB + Índice: 0.00MB + Motor InnoDB
wp_revslider_layer_animations: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_revslider_navigations: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_revslider_sliders: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_revslider_slides: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_revslider_static_slides: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_smush_dir_images: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_snippets: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_termmeta: Datos: 0.09MB + Índice: 0.09MB + Motor InnoDB
wp_terms: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
wp_term_relationships: Datos: 2.52MB + Índice: 1.52MB + Motor InnoDB
wp_term_taxonomy: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
wp_usermeta: Datos: 0.30MB + Índice: 0.25MB + Motor InnoDB
wp_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp_wc_product_meta_lookup: Datos: 2.52MB + Índice: 2.09MB + Motor InnoDB
wp_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_wpmm_subscribers: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp_yith_wcwl: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_yith_wcwl_lists: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp_yoast_seo_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp_yoast_seo_meta: Datos: 0.48MB + Índice: 0.00MB + Motor InnoDB
wp_zp_locations: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

Asesor de Cookies: por Carlos Doral Pérez – 0.28
Code Snippets: por Shea Bunge – 2.13.3
Contact Form 7: por Takayuki Miyoshi – 5.1.4
Instant Articles for WP: por Automattic
Dekode
Facebook – 4.2.0

Google Analytics para WordPress por MonsterInsights: por MonsterInsights – 7.7.1
WPBakery Page Builder: por Michael M - WPBakery.com – 5.4.5
Members: por Justin Tadlock – 2.2.0
Print Google Cloud Print GCP WooCommerce: por BizSwoop a CPF Concepts
LLC Brand – 3.0.5 – No probado con la versión activa de WooCommerce

Really Simple SSL: por Rogier Lankhorst
Mark Wolters – 3.2.5

Redirect 404 Error Page to Homepage: por ProThoughts.com – 1.0
Shopkeeper Typekit Fonts: por GetBowtied – 1.3
User Role Editor: por Vladimir Garagulya – 4.51.2
W3 Total Cache: por Frederick Townes – 0.9.7.5
Advanced AJAX Product Filters for WooCommerce: por BeRocket – 1.3.3.2 – No probado con la versión activa de WooCommerce
WooCommerce PayPal Checkout Gateway: por WooCommerce – 1.6.17
WooCommerce Role Based Price: por Varun Sridharan – 3.3.5 – No probado con la versión activa de WooCommerce
WooCommerce Services: por Automattic – 1.21.1
WooCommerce: por Automattic – 3.7.0
Yoast SEO: por Equipo Yoast – 11.9
WP Maintenance Mode: por Designmodo – 2.2.4
Smush: por WPMU DEV – 3.2.4
YITH WooCommerce Cart Messages: por YITH – 1.4.3
YITH WooCommerce Wishlist: por YITH – 2.2.13

### Inactive Plugins (1) ###

Smartsupp Live Chat: por Smartsupp – 3.3 – No probado con la versión activa de WooCommerce

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: db.php
object-cache.php: object-cache.php

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la tienda: #24699 - /tienda/
Carrito: #24700 - /carrito/
Finalizar compra: #7 - /pago/
Mi cuenta: #24702 - /mi-cuenta/
Términos y condiciones: #140841 - /terminos-y-condiciones-de-uso/

### Theme ###

Name: CPU dore-denia
Version: 1.0
Author URL: http:%20//www.getbowtied.com/
Child Theme: ✔
Parent Theme Name: Shopkeeper
Parent Theme Version: 2.6.10
Parent Theme Author URL: https://www.getbowtied.com/
WooCommerce Support: ✔

### Templates ###

Overrides: shopkeeper/woocommerce/archive-product.php
shopkeeper/woocommerce/cart/cart-empty.php
La  version 3.5.0 de shopkeeper/woocommerce/cart/mini-cart.php está obsoleta. La versión del núcleo es la 3.7.0
shopkeeper/woocommerce/checkout/form-coupon.php
shopkeeper/woocommerce/checkout/form-login.php
La  version 3.4.0 de shopkeeper/woocommerce/content-product.php está obsoleta. La versión del núcleo es la 3.6.0
shopkeeper/woocommerce/content-product_cat.php
La  version 3.4.0 de shopkeeper/woocommerce/content-single-product.php está obsoleta. La versión del núcleo es la 3.6.0
La  version 2.5.0 de shopkeeper-child/woocommerce/emails/admin-cancelled-order.php está obsoleta. La versión del núcleo es la 3.7.0
La  version 2.5.0 de shopkeeper-child/woocommerce/emails/admin-failed-order.php está obsoleta. La versión del núcleo es la 3.7.0
La  version 2.5.0 de shopkeeper-child/woocommerce/emails/admin-new-order.php está obsoleta. La versión del núcleo es la 3.7.0
La  version 2.5.0 de shopkeeper-child/woocommerce/emails/customer-completed-order.php está obsoleta. La versión del núcleo es la 3.7.0
La  version 2.5.0 de shopkeeper-child/woocommerce/emails/customer-invoice.php está obsoleta. La versión del núcleo es la 3.7.0
La  version 1.6.4 de shopkeeper-child/woocommerce/emails/customer-new-account.php está obsoleta. La versión del núcleo es la 3.7.0
La  version 2.5.0 de shopkeeper-child/woocommerce/emails/customer-note.php está obsoleta. La versión del núcleo es la 3.7.0
La  version 2.5.0 de shopkeeper-child/woocommerce/emails/customer-on-hold-order.php está obsoleta. La versión del núcleo es la 3.7.0
La  version 2.5.0 de shopkeeper-child/woocommerce/emails/customer-processing-order.php está obsoleta. La versión del núcleo es la 3.7.0
La  version 2.5.0 de shopkeeper-child/woocommerce/emails/customer-refunded-order.php está obsoleta. La versión del núcleo es la 3.7.0
La  version 2.0.0 de shopkeeper-child/woocommerce/emails/customer-reset-password.php está obsoleta. La versión del núcleo es la 3.7.0
La  version 3.4.0 de shopkeeper/woocommerce/global/quantity-input.php está obsoleta. La versión del núcleo es la 3.6.0
shopkeeper/woocommerce/global/sidebar.php
shopkeeper/woocommerce/global/wrapper-end.php
shopkeeper/woocommerce/global/wrapper-start.php
shopkeeper/woocommerce/loop/loop-end.php
shopkeeper/woocommerce/loop/loop-start.php
shopkeeper/woocommerce/loop/no-products-found.php
La  version 3.5.0 de shopkeeper/woocommerce/myaccount/form-login.php está obsoleta. La versión del núcleo es la 3.6.0
La  version 3.4.0 de shopkeeper/woocommerce/order/form-tracking.php está obsoleta. La versión del núcleo es la 3.6.0
shopkeeper/woocommerce/single-product/add-to-cart/simple.php
La  version 3.5.0 de shopkeeper/woocommerce/single-product/product-image.php está obsoleta. La versión del núcleo es la 3.5.1
La  version 3.3.2 de shopkeeper/woocommerce/single-product/product-thumbnails.php está obsoleta. La versión del núcleo es la 3.5.1
shopkeeper/woocommerce/single-product/tabs/tabs.php
shopkeeper/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Aprende cómo actualizar

### Action Scheduler ###

Complete: 6
Oldest: 2019-08-21 08:07:32 +0000
Newest: 2019-08-21 08:07:32 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by SirTronco** [comment]
Hi!

I'm answer myself!

For now, we have deactivated the "**W3 Total Cache"** plugin, and now works correctly every time.
Now we will try with the options, and i'll feedback here.

**Comment by SirTronco** [comment]
Ok, we find it.

In the settings of the plugin, we need to deactivate the **"Database cache"** option, this matches the idea that there were problems when generating image IDs.

Thanks and apologies the inconvenience!

**Comment by guilherme-oliveria** [comment]
@SirTronco 
I have the same problem, but I think it's because of the "?" because I pass parameters to search the images in my host, but I want to test its method, which path of the "Database cache" in the plugin woocomerc.

**Comment by edumats** [comment]
Thank you, I disabled `Database cache` in W3 Total Cache and the issue was solved as well. As the error was intermittent, it was very hard to diagnose the source of the problem.
