### ISSUE TITLE
Partial refund products which has been bought with restricted coupon

### ISSUE THREAD

**Issue by faridmovsumov** [woocommerce/woocommerce#24483]
Let say I have two products A => $100 and B => $200

Customer used percentage discount (10%) which is valid only for product A

In this case, a customer pays $90 for A and $200 for B

But then when I check order from the Admin, I see coupon discount which is in total $10 split to both products. 

And if a customer wants to partially refund one of these products then you should fix calculations manually which means a lot of operations.

Is that a bug? Is there a way I can solve that issue?

**Comment by faridmovsumov** [comment]
Basically _line_total meta saved wrong in wp_woocommerce_order_itemmeta table

**Comment by faridmovsumov** [comment]
Sorry, I found the reason for this behavior. There is no bug, there is some custom logic which is the reason for that.

**Comment by jozeflambrecht** [comment]
@faridmovsumov Would you mind sharing the logic behind this?
