### ISSUE TITLE
Attributes Archives Menu Visibility

### ISSUE THREAD

**Issue by michacassola** [woocommerce/woocommerce#24498]
Please make it possible to easily and without having to use the custom link field insert a product attribute archive in the apprearance/menu screen.
(`https://domain.tld/product-attribute/color/`)

**Comment by kloon** [comment]
You can use the following filter to enable that by default `woocommerce_attribute_show_in_nav_menus`

```php
apply_filters( 'woocommerce_attribute_show_in_nav_menus', '__return_true' );
```

**Comment by michacassola** [comment]
Thanks, will try.
