### ISSUE TITLE
category text and images not showing

### ISSUE THREAD

**Issue by missmadison** [woocommerce/woocommerce#24490]
**Describe the bug**
on each of my categories, I have a brief description of the category along with 2 images.  My "Chiffon Gowns" category will not show the category text or images.  

**To Reproduce**
1. Go to 'Products...'
2. Click on '.Categories...'
3. Scroll down to 'Chiffon Gowns.', click View
![2019-08-24 (2)](https://user-images.githubusercontent.com/54486569/63644165-63e7ae80-c697-11e9-97d1-9112baa54db2.png)
![2019-08-24 (1)](https://user-images.githubusercontent.com/54486569/63644166-63e7ae80-c697-11e9-9c10-bea44c7e53c3.png)
![2019-08-24](https://user-images.githubusercontent.com/54486569/63644167-64804500-c697-11e9-99dc-110193cf2961.png)

**Expected behavior**
see screen shots of other categories
![2019-08-24 (4)](https://user-images.githubusercontent.com/54486569/63644184-cc369000-c697-11e9-9ce7-d59a1012cd1d.png)
![2019-08-24 (3)](https://user-images.githubusercontent.com/54486569/63644185-cccf2680-c697-11e9-82e2-136df7b80a11.png)

**Comment by kloon** [comment]
Can you please attach your system status report and verify that you tested this with just WooCommerce active and your theme switched to a default one like Storefront or Twentynineteen.

In my tests the description and images are showing, this is all dependant on your theme though as some themes will modify the display to suite the design of the theme.

Closing this issue as I am unable to replicate this with a default theme and just WooCommerce active, but I will gladly reopen if you can provide steps to reproduce this on a default setup, but as mentioned this is all dependant on your theme and you will like have to contact the theme developers to assist with this.
