### ISSUE TITLE
Slug /shop/ showing directory on the server

### ISSUE THREAD

**Issue by MezMerrit** [woocommerce/woocommerce#24500]
Hey peeps :) I give up! I've never use WC before so it's over my head. I suspect this is a .htaccess issue (also over my head).

**Describe the bug**
Shop page URL goes to a directory on the server. And I have no categories page, the URL produces a 404. 
(see To Reproduce below for links)

**Pages Installed by WC:** https://auskwads.com/wp-content/uploads/2019/08/pages.jpg
**WooCommerce > Settings > Products > Shop page** = "Shop"

Permalink settings are...
**Common Settings (Custom):** /%category%/%postname%/
**Optional Settings:** https://auskwads.com/wp-content/uploads/2019/08/optional.jpg
**Product permalink:** /shop/

**To Reproduce**
**Shop Page:** https://auskwads.com/shop/
**Categories Page:** https://auskwads.com/product-category/

**Expected behavior**
**Demo product:** https://auskwads.com/product-category/tshirts/

**Isolating the problem:**
- [ x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x ] This bug happens with a default WordPress theme active, and [Storefront].
- [ x ] I can reproduce this bug consistently using the steps above.
Also...
- [ x ] Double checked no other taxonomies are named similarly to permalinks/slugs.
- [ x ] Overwrote the theme files with WC files in the process of troubleshooting.
- [ x ] Removed WC and reinstalled a different zip package.
- [ x ] Stripped WP back to barebones & started over twice.
- [ x ] Happens with and without active Jetpack connection.

**WordPress Environment**
Fresh install of WP v5.2.2
`
### WordPress Environment ###

WordPress address (URL): https://auskwads.com
Site address (URL): https://auskwads.com
WC Version: 3.7.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.8
PHP Post Max Size: 260 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.65.3
OpenSSL/1.0.2s

SUHOSIN Installed: –
MySQL Version: 5.6.41-84.1
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.0
WC Database Prefix: e0a_
MaxMind GeoIP Database: ✔
Total Database Size: 3.29MB
Database Data Size: 2.99MB
Database Index Size: 0.30MB
e0a_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
e0a_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
e0a_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
e0a_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_comments: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
e0a_ezihosting_freight_tick_boxes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
e0a_failed_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_mailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_options: Data: 2.72MB + Index: 0.11MB + Engine MyISAM
e0a_postmeta: Data: 0.10MB + Index: 0.03MB + Engine MyISAM
e0a_posts: Data: 0.11MB + Index: 0.04MB + Engine MyISAM
e0a_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_tcb_api_error_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_td_fields: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_td_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
e0a_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
e0a_term_relationships: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
e0a_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_usermeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
e0a_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
e0a_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_wc_customer_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_wc_order_product_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_wc_order_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
e0a_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
e0a_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_wpfb_gettwitter_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_wpfb_post_templates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e0a_wpfb_reviews: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (8) ###

Category Tag Pages: by Marzio Carro – 1.0
Custom Facebook Feed Pro Business: by Smash Balloon – 3.9
Folders Pro: by Premio – 2.2.2
Jetpack by WordPress.com: by Automattic – 7.6
MOJO Marketplace: by Mike Hansen – 1.5
WooCommerce
WooCommerce Admin: by WooCommerce – 0.17.0
WooCommerce Services: by Automattic – 1.21.1
WooCommerce: by Automattic – 3.7.0

### Inactive Plugins (2) ###

Content Aware Sidebars: by Joachim Jensen - DEV Institute – 3.9
Multiple Themes: by David Gewirtz – 7.1.1

### Dropin Plugins (2) ###

db-error.php: db-error.php
maintenance.php: maintenance.php

### Must Use Plugins (3) ###

Endurance Browser Cache: by Mike Hansen – 0.4
Endurance Page Cache: by Mike Hansen – 1.6
SSO: by Garth Mortensen
Mike Hansen – 0.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #113 - /shop/
Cart: #27 - /cart/
Checkout: #28 - /checkout/
My account: #29 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Lodestar
Version: 1.0.8
Author URL: https://www.wordpress.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: lodestar/woocommerce/emails/admin-cancelled-order.php
lodestar/woocommerce/emails/admin-failed-order.php
lodestar/woocommerce/emails/admin-new-order.php
lodestar/woocommerce/emails/customer-completed-order.php
lodestar/woocommerce/emails/customer-invoice.php
lodestar/woocommerce/emails/customer-new-account.php
lodestar/woocommerce/emails/customer-note.php
lodestar/woocommerce/emails/customer-on-hold-order.php
lodestar/woocommerce/emails/customer-processing-order.php
lodestar/woocommerce/emails/customer-refunded-order.php
lodestar/woocommerce/emails/customer-reset-password.php

### Action Scheduler ###

Complete: 66
Oldest: 2019-08-24 10:06:45 +0000
Newest: 2019-08-25 22:57:49 +0000

Pending: 2
Oldest: 2019-08-25 23:57:49 +0000
Newest: 2019-08-25 23:57:50 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by MezMerrit** [comment]
Got it sorted. Woo Commerce mistakenly creates an empty "shop" folder on the server that causes a conflict with the permalink rules. People have been complaining about this issue for a few years, might be time to call it a bug and get it fixed hey!

**Comment by MezMerrit** [comment]
Yessum... it means WooCommerce doesn't necessarily work straight out of the box. And since WP and WC are both written and maintained by Automaticc, I find it difficult to split hairs over who should fix it. But thanks for leaving the post here to help others with the same issue :)

**Comment by claudiosanches** [comment]
@MezMerrit Automattic doesn't write or maintain WordPress. Still what you are reporting is not on WooCommerce scope, it's a WordPress scope, since WordPress deals with rewrite rules.
