### ISSUE TITLE
Woocommerce API creates duplicate images

### ISSUE THREAD

**Issue by TimonAndries** [woocommerce/woocommerce#24527]
Hello,
I’m using wordpress 5.2.2 with Woocommerce 3.7.0

We’re using the standard Woocommerce API to fill up our webshop with products from our ERP software. But we are having some issues with the images.

When sending products to the shop we upload the images to a folder on the server /public_html/images then the API takes them and put them into /public_html/wp-content/uploads/2019/08

The image name is the articlenumber, for example we send product ABCD to the webshop. It will be placed in the images folder as ABCD.jpg and then in the wordpress folder where the API will create the necessary formats, so in the wordpress folder we’ll have:

ABCD.jpg
ABCD.jpg-100×100.jpg
ABCD.jpg-150×150.jpg
ABCD.jpg-300×300.jpg
ABCD.jpg-214×300.jpg
ABCD.jpg-450×630.jpg

The problem is the next time we send that product to the shop (if something was changed with the product) the API will put the images in the wordpress folder again instead of recognizing it’s already there. So it will add:

ABCD-1.jpg
ABCD.jpg-1-100×100.jpg
ABCD.jpg-1-150×150.jpg
ABCD.jpg-1-300×300.jpg
ABCD.jpg-1-214×300.jpg
ABCD.jpg-1-450×630.jpg

So now for 1 article I already have 14 images. Next time the product get’s exported again it will add it with ABCD-2.jpg etc…

This is causing a big problem in regards of diskspace. Even a shop with only a couple of products gets to have hundreds of images in no time. Taking in account that we have webshops with thousands of articles it's not manageable
.

**Comment by kloon** [comment]
You should ommit the image from the second request if nothing has changed. When making a POST request to update a product you should ideally only be posting the data that has changed.

TBH there is really no way for us to know if an image is identical without doing a lot of expensive comparisons, for example, an image may be cropped and uploaded with the same name, having to read image data and compare it with each request will be very expensive and resource-intensive causing API requests to be slow.

Closing this as won't fix for now as there is a workaround by not posting data that has not changed to the API.
