### ISSUE TITLE
Theme "upsell" in extensions listing showing HTML

### ISSUE THREAD

**Issue by mbabker** [woocommerce/woocommerce#24534]
**Describe the bug**
On the WooCommerce > Extensions page, if you go to any section but the featured section, the "upsell" for the Storefront theme is showing its text with the HTML tags included, instead of rendering the HTML.

**To Reproduce**
1. Go to `/wp-admin/admin.php?page=wc-addons&section=shipping-methods`
2. Scroll down to the bottom
3. Look at the box for the theme, see HTML inline with the text.

**Screenshots**
![Screen Shot 2019-08-29 at 2 48 40 PM](https://user-images.githubusercontent.com/368545/63971777-f360d900-ca6c-11e9-9231-c51d75a6fcef.png)

**Expected behavior**
HTML behaves as HTML and styles the text appropriately

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24546.
