### ISSUE TITLE
Add support to WC_Payment_Tokens to support namespaces

### ISSUE THREAD

**Issue by tpaonetower** [woocommerce/woocommerce#24541]
**Is your feature request related to a problem? Please describe.**
Within WC_Payment_Tokens, classes that implement namespaces cannot be used due to how the logic is composed in [WC_Payment_Tokens](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-payment-tokens.php#L153):
`$token_class = 'WC_Payment_Token_' . $token_result->type;`

The subsequent line then performs a `class_exists($token_class)`. If a class extending WC_Payment_Token is namespaced, this evaluation will always return false. This logic is also imposed on `WC_Payment_Tokens::delete()`.

The current work-around for this, is to extend the namespaced class and have that class in the global namespace.

**Describe the solution you'd like**
One solution would be to emulate a filter similar to `woocommerce_data_stores`.  The array passed to this filter would have keys reflecting the value of `$type` of the class extending `WC_Payment_Token` and the values would be the full name of the class, with the namespace. Here's an example integration:

```
add_filter('woocommerce_payment_token_types', function($classes) {
    // "example" is the value of WC_Payment_Token_Example::get_type()
    $classes['example'] = \My\Namespace\WC_Payment_Token_Example::class;
    return $classes;
});
```

This would require modifying the logic of `WC_Payment_Tokens::delete()` and `WC_Payment_Tokens::get()` to then leverage this new filter.

An alternative would be simply to change `$token_class = 'WC_Payment_Token_' . $token_result->type;` to just have a simple filter that would not require significant changes to current functionality:
```
$token_class = apply_filters('woocommerce_payment_token_get_class'  ,'WC_Payment_Token_' . $token_result->type, $token_result->type); 
```
This solution would not affect current functionality. Having the second argument to the filter be `$token_result->type` would allow filters that leverage this to identity the type of token being processed and adjust the class name accordingly.

**Additional context**
This limitation is not outlined in the current documentation. Making note of it would be very beneficial.

**Comment by claudiosanches** [comment]
Thank you for suggesting this feature!

I'm closing the issue as it already has a PR, please continue the discussion over at #24542.
