### ISSUE TITLE
Individually sold items cause confusion when adding more than one through add-to-cart GET command

### ISSUE THREAD

**Issue by njeffers** [woocommerce/woocommerce#24550]
**Describe the bug**
Adding another product to the cart via the old "add-to-cart" GET command will just redirect you back to the same page with no warnings if the item is limited to only allow one quantity in cart, and the user tries adding a second. I believe this boils down to the logic in the add_to_cart_action() function, but I could be wrong.

**To Reproduce**
1) Create a product that is sold individually
2) Add item to cart
3) Add a button or link to the homepage with something like mydomain.com/?add-to-cart=52
4) Try to add it to the cart again
5) Get redirected back to the same page you were on

This works a little better if you're on a product page, as you'll get the warning about not being allowed to add more than one item, but this is very confusing if you're a customer outside of those pages, such as the homepage.

Also of note, if you keep trying to add that product out of confusion ("why isn't it doing anything?") and manually go to the cart, you get a bunch of repeated messages about having more than one product (one per time, naturally).

**Expected behavior**
If item is sold individually, and already in cart, just redirect to the cart. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by kloon** [comment]
Hi, have you tried experimenting with the redirect after adding to cart option? If that option is enabled then it will redirect to the cart page. The reason it stays on the current page is that you have that option disabled and the page you have your buttons on is not a standard WooCommerce page so notices and errors are not outputted there.

![](https://cld.wthms.co/5vnT8c+)

Give that a try. I am closing this issue for now but might likely revisit this in the future as an enhancement to auto redirect to the cart page when a single purchase product is added to the cart.

**Comment by njeffers** [comment]
Hi @kloon,

I actually have the redirect to cart option enabled. It never fires off due to the add_to_cart_action(). In this function, if the item wasn't added to the cart (wasn't, because you can't have two), it just returns nothing, which drops you back to the current page.

Correct that the notices won't show on non-woo pages - I believe I mentioned this in my initial post. Thing is, why allow adding to the cart through the URL, if not for manipulating the cart outside of woocommerce?

I've had this issue happen on quite a few sites throughout the years. This happens mostly on subscription-based sites where you need to limit to 1 subscription. From a UX perspective, many clients want to add a "sign up" CTA on the homepage without making the customer click through a ton of pages to checkout. Homepage -> checkout seems so much better, and this partially breaks this.
