### ISSUE TITLE
Missing "attribute box" in product edit

### ISSUE THREAD

**Issue by Gadz01** [woocommerce/woocommerce#24551]
Hi there. I am using a woocommerce for a dropshipping store. The attribute box when editing the product is missing. When product in viewed in front end, the attributes are visible in the "additional info" tab.  I am trying to figure out the error by disabling the plug ins, then turning in on back. But sill, I can not resolve the issue. It was there before. 
![image](https://user-images.githubusercontent.com/54742546/64064028-2357da00-cc2f-11e9-8793-ba43c7aaa06d.png)

**Comment by kloon** [comment]
This is probably hidden by your screen options. On the product edit page, click screen options top right corner and make sure the Product Data option is checked.

![Screen Options Menu](https://cld.wthms.co/tMKvlC+)
