### ISSUE TITLE
Sidebar navigation does not consistently respect primary product category

### ISSUE THREAD

**Issue by vardumper** [woocommerce/woocommerce#24562]
**Describe the bug**
Many products of our shop are assigned to multiple categories (eg: Men's -> Subcategory, Women's -> Another Subcategory). That said, we also define a primary category, in order to have the customer know which category he is browsing. While the main navigation (vertical top menu) highlights all chosen categories similarly, the breadcrumb navigation displays the correct path to the primary category.
But the woocommerce sidebar (created with WC_Product_Cat_List_Walker) sometimes highlights opens the correct tree, showing the active subcategory - sometimes it doesn't.

**To Reproduce**
1. Create products and assign them to multiple categories
2. Assign a primary category
3. Verify the sidebar navigations status

**Screenshots**
![correct](https://user-images.githubusercontent.com/21208397/64155484-2ae7d080-ce33-11e9-8d0b-b26ae3778881.jpg)
![erroneous](https://user-images.githubusercontent.com/21208397/64155486-2ae7d080-ce33-11e9-9e2d-4e000c213797.jpg)

**Expected behavior**
The sidebar should consistently reflect a products primary category, and not show a "random" category.

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://orgawell.com
Site address (URL): https://orgawell.com
WC Version: 3.7.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.2
WP Multisite: –
WP Memory Limit: N GB
WP Debug Mode: ✔
WP Cron: –
Language: de_DE_formal
External object cache: –

### Server Environment ###

Server Info: nginx/1.17
PHP Version: 7.2
cURL Version: 7.5*
OpenSSL

SUHOSIN Installed: –
MySQL Version: 8.0.17
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ❌ wp_remote_post() ist fehlgeschlagen. Kontaktieren Sie Ihren Webhosting-Anbieter.
Remote Get: ❌ wp_remote_get() ist fehlgeschlagen. Kontaktieren Sie Ihren Webhosting-Anbieter.

### Database ###

WC Database Version: 3.7.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Datenbank-Gesamtgröße: 246.68MB
Datenbank-Datengröße: 162.59MB
Datenbank-Indexgröße: 84.09MB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins ###

BS PAYONE WooCommerce 3: von pooliestudios – 1.4.0
Custom Permalinks: von Sami Ahmed Siddiqui – 1.5.1
Language Fallback: von Bernhard Kau – 1.0.3
Loco Translate: von Tim Whitlock – 2.3.0
Manage Notification E-mails: von Virgial Berveling – 1.4.2
MCE Table Buttons: von Jake Goldman
WooCommerce Blocks: von Automattic – 2.3.0
Germanized für WooCommerce Pro: von Vendidero – 1.11.2
Germanized für WooCommerce: von Vendidero – 2.3.3
WooCommerce Shipment Tracking Pro: von PluginHive – 2.2.13 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce - Store Exporteur Deluxe: von Visser Labs – 3.4 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce: von Automattic – 3.7.0
WooSidebars: von WooCommerce – 1.4.5
WordPress Importer: von wordpressdotorg – 0.6.4
Yoast SEO: von Team Yoast – 11.8 – Nicht getestest mit der aktiven WooCommerce-Version
WP Crontrol: von John Blackbourn & crontributors – 1.7.1
WP Fastest Cache: von Emre Vona – 0.8.9.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: #277 - /shop/
Warenkorb: #278 - /warenkorb/
Kasse: #7 - /kasse/
Mein Konto: #8 - /mein-konto/
Allgemeine Geschäftsbedingungen: #11 - /agb/

### Theme ###

Name: Flatsome Orgawell Theme
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.8.0
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

### Action Scheduler ###

### Templates ###

Extended logging mode for Store Exporter Deluxe: ✔Inactive Turn on Logging mode
Debugging mode for Store Exporter Deluxe: ✔Inactive Turn on Debugging mode
Scheduled Export to FTP: ✔
Scheduled Export to SFTP: ❌ The required SFTP functions are not available; ssh2_connect()
ssh2_auth_password()
ssh2_sftp(). Contact your hosting provider.

`
```
</details>

**Comment by claudiosanches** [comment]
>  But the woocommerce sidebar (created with WC_Product_Cat_List_Walker) sometimes highlights opens the correct tree, showing the active subcategory - sometimes it doesn't.

Not able to reproduce it, also doesn't give any real steps to reproduce this issue.
There's anything else that we can try to replicate this behavior?

**Comment by vardumper** [comment]
I'll try to clarify the steps needed to reproduce this error.

1. Create a category structure like: 
```
A  
     * AA
     * AB
B
     * BA
     * BB   
```
2. Create product 1 and 2
3. Assign product 1 to category AA and BA, choose category AA to be the products primary category
4. Assign product 2 to category AA and BA, choose category BA to be the products primary category
5. when looking at product 1, the category menu in the sidebar shows the correct active states and opens the correct subtree of main category A
6. when looking at product 2, the category menu in the sidebar has incorrect active states and opens the WRONG subtree of main category A, whilst it should open tree B since the main category is BA

I hope this clarifies the problem. And thanks for looking into my issue

**Comment by vardumper** [comment]
I am going to close this issue. It seems that functionality to choose one category as primary category over another comes from Yoast SEO plugin, thus I will report this issue there. I thought Wordpress did this out of the box. My bad.
