### ISSUE TITLE
Custom Order Status Email Not Displaying in the Admin emails section.

### ISSUE THREAD

**Issue by db123v** [woocommerce/woocommerce#24561]
Once you have created a custom order status and then add an order status email and click on customize email, upon clicking on customize email, you are taken to the emails tab but a blank page is displayed.

Steps to Reproduce:
1. Login as an Admin.
2. Go to the Woocommerce menu.
3. Click on the Setting Submenu under Woocommerce.
4. Click on the order statuses tab.
5. Edit the desire custom status.
6. Click on the "Emails" option.
7. Hover over on to the custom status and click on "Customize Email"
8. System takes you to the Emails tab but nothing is being displayed. Only the "Save Changes" button is displayed.

Your help with fixing this would be highly appreciated.

**Comment by kloon** [comment]
Hi @db123v, custom order statuses and emails are not part of WooCommerce core. I suggest you get in touch with the developers to assist with this. This platform is only for reporting issues within WooCommerce core and not extensions/themes.
