### ISSUE TITLE
How to accept billing from all countries/states, but only ship to one country, state and city with Woocommerce?

### ISSUE THREAD

**Issue by oliveandgrain** [woocommerce/woocommerce#24573]
As we do our own delivery, we need to make sure that we are not accepting deliveries from anywhere outside of Sydney, NSW, Australia. But we need to be able to accept payments from NZ and other international customers within the billing field. 

From what I've tried, it seems like I am only able to change both fields leaving to restricting the billing as a cost of restricting the shipping. 

I'm also having issues changing the order/priority of each field in both the billing fields. 

Is this possible through a PHP snippet or am I looking at a larger customisation job? 

Cheers,

Aron

**Comment by rodrigoprimo** [comment]
Hi there!

GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/
