### ISSUE TITLE
Custom delimiter for CSV products export

### ISSUE THREAD

**Issue by rbsmidt** [woocommerce/woocommerce#24579]
I've been really pleased with the import/export of products added to Woo. Over the time almost every WooCommerce client i've had, needs an export of some sort or importing batches of products. The native import/export is easy to extend in terms of custom columns and eliminates almost any need for expensive, overcomplicated import/export plugins.

However i really miss one small feature in the exporter. The custom csv delimiter. It's there in the importer. I've had a bunch of clients (all mac users really) who have semi-colon as there standard CSV delimiter (both Excel and Numbers). Changing this is really not an option with Numbers. For excel it doesn't render the file correct by import through the data tab and choosing the comma as delimter (attributes of variable products mess up the rows). 
While a simple "search and replace all" routine is easy for most it isn't a solution for all (non techy) clients, and it's also a unnecessary manuel step imho.

I'd really like to see either a custom delimiter option in the export screen (as the importer has under advanced options, or a hook to change the delimiter (similar to adding custom columns).

Dugging through the WooCommerce code for exporting it doesn't seem to be possible today to change the delimiter without changing the plugin code (`fputcsv`call in `abstract-wc-csv-exporter.php` line 484 to be exact).

`fputcsv( $buffer, $export_row, ",", '"', "\0" ); // @codingStandardsIgnoreLine`

If the option is left out for some premeditated reason that i can't think of, i'd like to hear as well :-)

**Comment by vedanshujain** [comment]
I think a filter for changing the delimiter would work well here.

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24759.
