### ISSUE TITLE
Add a filter for setting the default colors

### ISSUE THREAD

**Issue by yoxalld** [woocommerce/woocommerce#24571]
Now that Woocommerce supports (essentially) any theme by tying the display into the_content for themes that don't declare Woocommerce support. It would be great to have a filter to be able to change the default colors that Woocommerce uses.

I found a [snippet](https://dtbaker.net/blog/set-default-woocommerce-colors/) that apparently used to work but is now deprecated. If I have simply overlooked something already available please let me know as I have spent a couple hours trying to find solutions but have not come across anything that works.

This would provide a quick solution to making the default Woocommerce interface feel like it matches the rest of a theme.

Something along the lines of this is what I was picturing:
```
add_filter('some_woo_hook', 'set_my_default_colors');

function set_my_default_colors($default_colors){
    $default_colors = array(
        'primary' => '372772',
        'primary-text' => '0B070E',
        'secondary' => '94C595',
        'secondary-text' => '747C92',
        'highlight' => 'A1E8AF',
        'highlight-text' => 'FFFFFF',
        'contentbg' => 'F2F3F5',
        'subtext' => '999FAF'
    ) 
    return $default_colors;
}
```

**Comment by claudiosanches** [comment]
That filters are used when we compiled colors on the fly, something not recommended and obsolete right now, still if you want to change the default colors in themes it's better and also a cleaner solution to just write some CSS, or extend the WooCommerce styles in your theme.
