### ISSUE TITLE
calculate_shipping() for a custom method when custom checkout field is changed

### ISSUE THREAD

**Issue by atif089** [woocommerce/woocommerce#24585]
1. Added a custom checkout field using woocommerce_checkout_fields filter.
2. Added the class to `woocommerce_shipping_methods` for a custom shipping method.
3. When the custom field on the form is updated I call `jQuery( document.body ).trigger( 'update_checkout' );` which updates the cart.

But if any other shipping method is selected (apart from my custom one) then the `calculate_shipping()` method of my class is not run. So the user doesn't see the updated shipping price.

Is there a way I can run calculate_shipping() for all the possible shipping methods when this field is changed.

Similar issue -> Duplicate of https://github.com/woocommerce/woocommerce/issues/7565

**Comment by atif089** [comment]
Figured!

To prevent recalculation, WooCommerce caches the rates of the cart using a hash created based on user and address fields. Since this hash is not aware of the custom field that is created, the hash doesn't change.

We need to hook into `woocommerce_cart_shipping_packages` and add another key pair so that a different hash can be generated based on the custom field.

Sample code

```php
function handle_shipping_address_type($packages) {
    $add_is_home= 0;
    parse_str($_POST['post_data'], $post_data);
    if ($post_data["add_is_home"]) {
        $add_is_home= 1;
    }
    $packages[0]["destination"]["addr_is_home"] = $add_is_home;
    return $packages;
}
add_filter('woocommerce_cart_shipping_packages', 'handle_shipping_address_type');
````

**Comment by teledirigido** [comment]
This saved me hours of work, Thank you very much!

**Comment by lekhang2512** [comment]
> Figured!
> 
> To prevent recalculation, WooCommerce caches the rates of the cart using a hash created based on user and address fields. Since this hash is not aware of the custom field that is created, the hash doesn't change.
> 
> We need to hook into `woocommerce_cart_shipping_packages` and add another key pair so that a different hash can be generated based on the custom field.
> 
> Sample code
> 
> ```
> function handle_shipping_address_type($packages) {
>     $add_is_home= 0;
>     parse_str($_POST['post_data'], $post_data);
>     if ($post_data["add_is_home"]) {
>         $add_is_home= 1;
>     }
>     $packages[0]["destination"]["addr_is_home"] = $add_is_home;
>     return $packages;
> }
> add_filter('woocommerce_cart_shipping_packages', 'handle_shipping_address_type');
> ```

I use the above code and it works. But when I choose the shipping method, click checkout comes up with an error message:
