### ISSUE TITLE
When Woocommerce 3.7.0 is installed Blog Posts Index doesn't use archive.php when params orderby=date&order=ASC are added

### ISSUE THREAD

**Issue by partnuz** [woocommerce/woocommerce#24582]
**Describe the bug**
Blog Posts Index page doesn't use archive.php when using params /blog_page/?orderby=date&order=ASC Problem occurs only when Woocommerce is installed ( without plugins). After some debugging it seems that WP_Query has is_posts_page set to 0 when normally it has this param set to 1

**To Reproduce**
1. Create a page named "BlogPageIndex"
2. Go to "Settings > Reading" and under "Your display homepage" set "Posts Page" to above mentioned
3. Go to url generated by page from point 1 and add "?orderby=date&order=ASC" so you have for example /blog_posts/?orderby=date&order=ASC
4. Page is not using archive.php like it should. Instead it uses only page.php

**Expected behavior**
This page should display list of posts ( defined in archive.php)

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): http://wootest.locdev
Site address (URL): http://wootest.locdev
WC Version: 3.7.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.37 (Win64) PHP/7.0.33
PHP Version: 7.0.33 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.59.0
OpenSSL/1.0.2q

SUHOSIN Installed: –
MySQL Version: 5.7.24
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 0.62MB
Database Data Size: 0.52MB
Database Index Size: 0.10MB
wp_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 0.51MB + Index: 0.03MB + Engine MyISAM
wp_postmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_posts: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (3) ###

Jetpack by WordPress.com: by Automattic – 7.7
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.29
WooCommerce: by Automattic – 3.8.0-dev

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 4.1.2
Hello Dolly: by Matt Mullenweg – 1.7.2
WooCommerce: by Automattic – 3.7.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Sixteen
Version: 2.0
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 0
Oldest: –
Newest: –

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by rodrigoprimo** [comment]
There is a problem in PR #23159 that causes the issue reported here. cc @mikejolley in case the change is still fresh in your mind and you can see an easy way to fix this.

**Comment by partnuz** [comment]
@rodrigoprimo @mikejolley My temporary solution simply removes wc changes done on blog index page, so it doesn't include the situation when shop shortcode is used on this page ( though blog and shop should be separate pages so it cover 99% situations )

class Main {
    function __construct() {
        add_action( 'pre_get_posts' , [ $this , 'revertQuery' ] , 9 , 1 );
    }
    
    public function revertQuery( $wp_query ){
        $wc = WC();
        if( is_object( $wc ) && $wp_query -> queried_object_id == ( $postPage = get_option( 'page_for_posts' ) ) ){
            remove_action( 'pre_get_posts', [ $wc -> query , 'pre_get_posts' ], 10 );
        }
    }
}

This is feature is fully optional, perhaps I can create a plugin and post it on wordpress.org ?

**Comment by danfisher85** [comment]
I have exactly the same bug. I'm using posts filter on the Blog page which filters by 'get' params. However, after reverting changes were made in PR #23159, it starts working correctly.

**Comment by n-dawson** [comment]
I think part of the issue could be the `is_showing_page_on_front()` method of the `WC_Query` class.

```
private function is_showing_page_on_front( $q ) {
	return $q->is_home() && 'page' === get_option( 'show_on_front' );
}
```

The docblock states that this is to check if we're currently on the front page. The problem is when you are on the front page, it returns false. The conditional for that would be `is_front_page()` rather than `is_home()`. It's only when you pass in parameters such as `orderby` that WP recognises it as a blog query and `is_home()` becomes true instead. There's then no distinction between the front page and the actual blog.

There's a check on line 291 for the presence of the `orderby` param:

`} elseif ( ! empty( $_GET['orderby'] ) ) {`

This conditional is going to fire, regardless of whether we're on a static homepage or a blog index and override the query if orderby is set.

The solution would seemingly be a more robust check for determining whether we're on the homepage.
