### ISSUE TITLE
Filter Products by Multiple Attributes

### ISSUE THREAD

**Issue by Nichollas96** [woocommerce/woocommerce#24583]
I've been searching for an answer on this for the past couple of days but with no real success. Is there a way to filter products with REST API with a URL that looks something like this: 

/wp-json/wc/v3/products?category=164&attribute=pa_rezolutie&attribute_term=77&attribute=pa_producator&attribute_term=93 ?

I'm really trying to get products with both attributes pa_rezolutie=77 and pa_producator=93 but it doesn't seem to work. Is there another way to do this?

**Comment by claudiosanches** [comment]
Currently it's not supported, also the query string you wrote will not work.

```
?category=164&attribute=pa_rezolutie&attribute_term=77&attribute=pa_producator&attribute_term=93
```

It will render as:

```
?category=164&attribute=pa_producator&attribute_term=93
```

This happens because duplicated values will be ignored by default.
You can try it with this simple code:

```html
<pre><?php print_r($_REQUEST); ?></pre>
```

Save a file with the above code and try use the same query strings, the result should be:

```
Array
(
    [category] => 164
    [attribute] => pa_producator
    [attribute_term] => 93
)
```
