### ISSUE TITLE
Error when placing cart and checkout shortcode on the same page.

### ISSUE THREAD

**Issue by paaljoachim** [woocommerce/woocommerce#24595]
**Describe the bug**
Placing the shortcodes [woocommerce_cart] and [woocommerce_checkout] on the same page ends up creating an error on the order received page.

Backend Gutenberg where both shortcodes have been added.
![Screen Shot 2019-09-09 at 12 25 56](https://user-images.githubusercontent.com/5323259/64523625-02614a00-d2fd-11e9-8fbb-f82ffe233be6.png)

Order received page:
![Screen Shot 2019-09-09 at 12 27 12](https://user-images.githubusercontent.com/5323259/64523701-363c6f80-d2fd-11e9-85aa-af062bfb693b.png)

I am following this tutorial:
https://businessbloomer.com/woocommerce-cart-checkout-same-page/

Similar issues:
"Bug when Cart and Checkout shortcodes used on samepage"
https://github.com/woocommerce/woocommerce/issues/11579
and
"Cart and checkout on same page"
https://github.com/woocommerce/woocommerce/issues/24508

**Comment by claudiosanches** [comment]
You can hide it from your order received page, also in the order pay page (you can find it going to checkout after an order is pending, by email or from "My account" > "Orders" page).

Here the code that you'll use to override the `is_cart()` function.

```php
function is_cart() {
	$page_id = wc_get_page_id( 'cart' );
	$is_cart   = ( $page_id && is_page( $page_id ) ) || defined( 'WOOCOMMERCE_CART' ) || wc_post_content_has_shortcode( 'woocommerce_cart' );

	return $is_cart && ! ( is_checkout_pay_page() || is_order_received_page() );
}
```

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24738.
