### ISSUE TITLE
woocommerce_checkout doesn't appear

### ISSUE THREAD

**Issue by str-lml** [woocommerce/woocommerce#24596]
Hi, I try to add the element [woocommerce_checkout] in  a page but this elemen't never appear in the website.

![image](https://user-images.githubusercontent.com/16543728/64524090-1e192000-d2fe-11e9-87c8-ee8d17b1e0d7.png)

And get a blank page
![image](https://user-images.githubusercontent.com/16543728/64524239-689a9c80-d2fe-11e9-8957-83841c5b8257.png)

Any idea about this?

**Comment by CasperBraske** [comment]
This might be related to the block content plug-in you are using. Try to refer to the "issues template" and check all the steps to reproduce the error.

**Comment by rodrigoprimo** [comment]
Hi there!

GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/

If you believe you found a WooCommerce bug, please open another issue following the bug template as suggested by @CasperBraske.

Off the top of my head, I believe that the checkout shortcode only works on the checkout page (/wp-admin/admin.php?page=wc-settings&tab=advanced). If the page where you are adding the checkout shortcode is not set to be the checkout page, this might be why you are getting a blank page.
