### ISSUE TITLE
Woocommerce Checkout - "State" field is not showing for certain countries - causing payment errors.

### ISSUE THREAD

**Issue by mahermansour7** [woocommerce/woocommerce#24592]
Hello,

I'm using Woocommerce and when the customer enters the checkout page, while filling out the billing address: 

1- if he chooses countries like United Arab Emirates, USA, Canada, etc..., a state field appears and the customer can fill it normally and the payment goes through with no problems.

![united arab](https://user-images.githubusercontent.com/55040067/64482661-7ebd3580-d1f6-11e9-9e9a-eecdf29d789c.png)

2- if Germany, or Afghanistan or some different countries are chosen, the "state/county" field disappears, and when the customer clicks "place order" and error appears: "shipping_state post variable not found". 

![germnay](https://user-images.githubusercontent.com/55040067/64482663-867cda00-d1f6-11e9-9284-2984a79fd8ba.png)

this is the error that appears 

![Anmerkung 2019-09-08 045257](https://user-images.githubusercontent.com/55040067/64482665-8d0b5180-d1f6-11e9-8c1c-f7188b8f2e64.png)

i'm using PayTabs as a payment gateway.

what should i do in this case? many customers from germany can't place orders because of this.

**Comment by rodrigoprimo** [comment]
This is likely an issue with your payment gateway as shipping_state is indeed not always set and it depends on the country. I would suggest you contact the developers of the payment gateway that you are using to let them know about this problem.

Alternatively, you can use the `woocommerce_get_country_locale` filter to set state as a visible and required field for the countries where you are seeing the error.
