### ISSUE TITLE
Fully implement lookup table in products shortcode

### ISSUE THREAD

**Issue by php-n00b** [woocommerce/woocommerce#24604]
**Describe the bug**

Sorting products by average rating using a shortcode and the orderby="rating" attribute is not working properly and not taking in consideration the number of opinions. So sometimes a product with 1 opinion and an average rating of 5 is placed higher than a product that has 4 opinions and an average rating of 5. Sometimes products that have no opinions at all are placed higher than products that have at least 1 opinion of any kind. It looks random as it's shown in the screenshots.

**To Reproduce**

1. Create 10 products and assign them to 1 category
2. Rate randomly 4 of them, each one multiple times. For example like this:
Product # 1: 4 opinions, all of them have 5 stars - Average rating is 5.
Product # 2: 1 opinion that have 4 stars - Average rating is 4.
Product # 3: 2 opinions, all of them have 5 stars - Average rating is 5.
Product # 4: 3 opinions, 2 of them have 5 stars, 1 of them have 3 stars - Average rating is 4,3.
Products # 5 to # 10: No opinions at all
3. Create a shortcode:
[products columns="5" limit="5" orderby="rating" category="name of category"]
And make it appear on some random page.

**Screenshots**

Shortcode used to generate products that are shown in the screenshots:
[products columns="5" limit="5" orderby="rating" category="name of category"]

Red numbers shows how many opinions a particular product have.

1st example:
![obraz](https://user-images.githubusercontent.com/55139773/64610717-280b5380-d3d0-11e9-8695-2212d1d6aa41.png)
2nd example:
![obraz](https://user-images.githubusercontent.com/55139773/64610727-2b064400-d3d0-11e9-905d-fe2ae6e32596.png)
3rd example:
![obraz](https://user-images.githubusercontent.com/55139773/64610731-2f326180-d3d0-11e9-8a33-d79c014dd5a5.png)

**Expected behavior**

When using the shortcode including the orderby="rating" attribute:

[products columns="5" limit="5" orderby="rating" category="name of category"]

And products have ratings like this:

Product # 1: 4 opinions, all of them have 5 stars - Average rating is 5.
Product # 2: No opinion at all - Average rating is 0.
Product # 3: 2 opinions, all of them have 5 stars - Average rating is 5.
Product # 4: 3 opinions, 2 of them have 5 stars, 1 of them have 3 stars - Average rating is 4,3.
Product # 5: 1 opinion that have 4 stars - Average rating is 4.

It should be sorted automatically in this way - by the actual average rating taking in consideration the number of opinions a particular product have:

1st: Product # 1
2nd: Product # 3
3rd: Product # 4
4th: Product # 5
5th: Product # 2

I believe that this is the proper way that average rating should work.

**Isolating the problem (mark completed items with an [x]):**

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WC Version: 3.7.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: pl_PL
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.6 () mod_fcgid/2.3.9 Phusion_Passenger/5.3.7
PHP Version: 7.3.8
PHP Post Max Size: 200 MB
PHP Time Limit: 200
PHP Max Input Vars: 100000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.41-MariaDB-cll-lve
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.0
WC Database Prefix: wp_
Całkowity rozmiar bazy danych: 19.64MB
Rozmiar bazy danych: 16.59MB
Rozmiar indeksu bazy danych: 3.05MB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Settings ###

API Enabled: –
Force SSL: –
Currency: PLN (zł)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### Theme ###

Name: OceanWP
Version: 1.7.1
Author URL: https://oceanwp.org/about-me/
Child Theme: ❌ – Jeśli modyfikujesz WooCommerce lub motyw nadrzędny
którego nie jesteś autorem
polecamy używanie motywu potomnego. Zobacz: Jak tworzyć motywy potomne

WooCommerce Support: ✔

### Templates ###

Overrides: oceanwp/woocommerce/cart/mini-cart.php
oceanwp/woocommerce/content-single-product.php
oceanwp/woocommerce/loop/loop-start.php
oceanwp/woocommerce/single-product/title.php

### Action Scheduler ###

Complete: 7
Oldest: 2019-08-15 21:43:50 +0200
Newest: 2019-09-05 22:49:29 +0200

Pending: 1
Oldest: 2019-09-12 22:49:29 +0200
Newest: 2019-09-12 22:49:29 +0200

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by claudiosanches** [comment]
I changed a bit the title, since this can be solved by including our new lookup table to those shortcodes.

**Comment by php-n00b** [comment]
Can you please tell me when this will be approximately implemented or if there is any workaround for now to make this work?

**Comment by claudiosanches** [comment]
@php-n00b probably in the next release circle, since we are going already to release 3.8 soon. But no dates yet.

**Comment by php-n00b** [comment]
Ok. Thanks for the answer.
