### ISSUE TITLE
Account creation: failed payments should avoid triggering new accounts

### ISSUE THREAD

**Issue by lkraav** [woocommerce/woocommerce#24603]
**Is your feature request related to a problem? Please describe.**

As correctly identified in https://github.com/woocommerce/woocommerce/issues/3155 automatic account and password creation boosts checkout conversion rates.

Downside: malicious actors arrive at checkout and try to purchase items with a variety of stolen e-mails and credit cards.

Stripe Radar often correctly blocks such credit card charges as too risky.

But each new e-mail address / CC attempt generates a new user, order and in our case, a new subscription + triggers external integrations (e-mail marketing platforms, etc), which for all intents and purposes are instantly garbage data, and should be prevented from occurring at the source.

**Describe the solution you'd like**

Account creation should be triggered only after a successful payment. (BACS scenario needs  :thinking:)

I haven't dug through source yet. If orders are immediately looking for user accounts to save to, it seems like keeping things in Guest mode during payment method success evaluation might be useful.

**Describe alternatives you've considered**

Malicious actors can generate spam accounts at a high rate, which can intermittently spike various manual cleanup work.

It feels like prevention, not cleanup, is the correct solution.

**Additional context**

Previous discussed in detail at https://github.com/woocommerce/woocommerce-gateway-stripe/issues/479

Your thoughts?

(I searched issues for multiple related keywords on this, but did not see this topic discussed anywhere before.)

**Comment by claudiosanches** [comment]
WooCommerce creates the customer, and save the order before the payment gateway response, this way it's possible to save anything relevant for the customer in question, but may also allow 3rd party plugins to include discounts and so on.

So changing it may cause problems, WooCommerce doesn't store in plain text the username and password (in case is enabled in the checkout), so if trying to create an account after processing a successful payment is not possible anymore to access the choice username and password.
This will have to complete change the checkout process, maybe forcing the customer to create an account only after a successful order is placed, something that I don't think that is good.

Also note that if a regular customer is trying to place an order and if fails, they can log in and try again in "My account" > "Orders" page, blocking it will make hard for those users as well.

One option to stop those spam accounts is to include recaptcha or some similar solution.

**Comment by lkraav** [comment]
We just got attacked by a botnet and here we are again with the same problem. 10,000 (ten thousand) spam accounts, orders and subscriptions got made before we enabled Cloudflare super bot fight mode and it managed to have an effect. But for how long?

I wonder what the cost of this unprotected design is across the WooCommerce ecosystem?

If this is shipped in WC core, better protection mechanisms need to be created in core, too. Talking about "go find antispam and antifraud" plugins is not the answer.

EDIT For example, could orders stay in Guest mode until payment succeeds?

**Comment by otakupahp** [comment]
Maybe, a "sandbox" account could be created to cache all data and only save after the payment is made.

But I believe than stronger pre-purchase methods are better.

**Comment by lkraav** [comment]
> But I believe than stronger pre-purchase methods are better.

Can you list the available options? I'm hearing experiences that people have all known security methods deployed, and they still can't stop this.

**Comment by otakupahp** [comment]
Let's see what others do... Shopify offers a "bot protection", but not sure what it means.

Maybe including some kind of reCAPTCHA or similar could work
