### ISSUE TITLE
How to exclude categories with wc_get_products()

### ISSUE THREAD

**Issue by AndreaBarghigiani** [woocommerce/woocommerce#24606]
I've read [your documentation](https://github.com/woocommerce/woocommerce/wiki/wc_get_products-and-WC_Product_Query) about `wc_get_products()` but I do not understand if this is possible *otb* or if I have/can hook into the [Custom Parameter](https://github.com/woocommerce/woocommerce/wiki/wc_get_products-and-WC_Product_Query#adding-custom-parameter-support) to create my kind of `exclude_category` parameter.

I am looking to find a way to exclude one or more categories from the custom loop I can create with `wc_get_products()`, there are any?

Can someone help pointing me to some tutorials or to confirm that if the filter `woocommerce_product_data_store_cpt_get_products_query` is the right way to go?

**Comment by AndreaBarghigiani** [comment]
Happy to close my own issue. I'll add the code that I used in order to make the 'exclude_category' parameter working.

*Custom wc_get_products() query:*
```php
$products = wc_get_products(
	[
		'status' => 'publish',
		'limit' => 8,
		'return' => 'ids',
		'visibility' => 'catalog',
		'exclude_category' => 'custom_product_taxonomy', // my new parameter
	]
);
```

*Create the filter to remove the value of `exclude_category`:*
```php
add_filter('woocommerce_product_data_store_cpt_get_products_query', 'sam_exclude_cat_query', 10, 2);

function sam_exclude_cat_query($query, $query_vars) {
    if (!empty($query_vars['exclude_category'])) {
        $query['tax_query'][] = array(
            'taxonomy' => 'product_cat',
            'field'    => 'slug',
            'terms'    => $query_vars['exclude_category'], // Use the value of previous block of code
            'operator' => 'NOT IN',
        );
    }
    return $query;
}
```

Here you go, now you can use it to exclude a single category, I think you need to customize the code if you pass an array of category slugs.

**Comment by BusinessBloomer** [comment]
Just popping in to thank you, that's exactly what I was looking for :)
