### ISSUE TITLE
Adding a sold out badge to shop/archive pages

### ISSUE THREAD

**Issue by drenina** [woocommerce/woocommerce#24605]
if a product is not in stock, currently only on the single product page a notice is shown that this product is not available (but not on the shop and archive pages). This is not very customer friendly since on all shop and archive pages the customers believes all the products are in stock only to find out that the product isn't when he goes to the single product page. I would suggest adding a SOLD OUT badge to the shop and archive pages so that the cutomer can see at first sight which products are available and which not.

**Comment by kloon** [comment]
Hi @drenina, we feel this is theme/extension territory as a lot of users actually use WooCommerce as a catalog without selling anything or keeping stock which will result in all those products having out of stock labels applied.

Doing a google search will reveal quite a few tutorials which will guide you through adding a badge like this to out of stock products. One example is https://www.cloudways.com/blog/add-woocommerce-sold-out-badge/
