### ISSUE TITLE
Styling date in plain/email-order-items.php

### ISSUE THREAD

**Issue by MarcFFF** [woocommerce/woocommerce#24607]
There seems to be a small formatting issue in the email-order-details.php for the plain emails: When the date is set to be displayed in the following format 01. January 2019, it has too many spaces between the date and the first punctuation mark. There should only be one empty space between the dot and the month.

**Comment by rodrigoprimo** [comment]
Could you please open another issue following the [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=) and include all the steps to reproduce this issue? I tested this quickly and I was not able to reproduce the problem that you mentioned, but I'm not sure if I'm using the same date format that you are.
