### ISSUE TITLE
sorting attributes by its labels in admin product edit

### ISSUE THREAD

**Issue by jaleghk** [woocommerce/woocommerce#24617]
Admin > Product Edit > Tab: Attributes > Userdefined Attribute - Select Box

Is it possible to sort the attributes by its label? we use a huge of attributes, and sorting by taxonomy key is not very helpful - really its not funny to pick the right option - what im searching for - some our taxonomy-keys are different from there labels.

i found out that i can not change this over hooks or actions - only in the plugin code - but this is not the right way and also not update-save. this is the reason why i posting this issue here.

code can found here, line 20-24
includes/admin/meta-boxes/views/html-product-data-attributes.php

idea:
- add an array
- push tax as key and label as value for every attribute
- after adding all atts - asort this array
- ouput data via second loop with echo
- unset temporarily vars
 and thats it!

thanks for your time

**Comment by claudiosanches** [comment]
You can sort it using the `woocommerce_attribute_taxonomies` filter, so will sort it in `wc_get_attribute_taxonomies()`, but note that `wc_get_attribute_taxonomies()` save values in transients, so you should clean the transients after applied the filter.
