### ISSUE TITLE
Cumulated rounding error on net payment

### ISSUE THREAD

**Issue by udotelaar** [woocommerce/woocommerce#24619]
All prices in our shop are entered in gross value. When selling into non EU countries only the net price is charged. WooCommerce starts to calculate the net price by dividing the gross price by the VAT-factor. 

Lets say we have a product for 9,95 Euro in the Shop (gross value.) WC divides by 1,19 (19% VAT) and the result is 8.36134453... and rounds it to 8.36 (net value). The problem now is, when the customer orders 5 of this. 5 x 8.36 Euro results in 41.80 Euro but in the basket and invoice WC states that it is 41.81 Euro. That is because in this case WC calculates the complete gross value first 5 x 9,95 Euro (49.75) and divides this value by 1,19. The result is 41,806722... which will correctly by rounded to 41,81 Euro. You see the problem. Single product price 8.36 Euro. Buying 5 of it should be 41.80 Euro not 41.81 Euro which is not correct.

**Screenshots**
![Bestellung_bearbeiten_‹_Marisco_Naturkosmetik_—_WordPress](https://user-images.githubusercontent.com/657194/64701795-bd2e4b00-d4a9-11e9-9e49-0a5d1cf19866.jpg)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://www.marisco-naturkosmetik.de
Site address (URL): https://www.marisco-naturkosmetik.de
WC Version: 3.6.5
Log Directory Writable: ✔
WP Version: 5.2.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE_formal
External object cache: –

### Server Environment ###

Server Info: nginx/1.17.1
PHP Version: 7.2.21-1+ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 2 GB
PHP Time Limit: 30
PHP Max Input Vars: 10000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.26-MariaDB-10.2.26+maria~xenial-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.6.5
WC Database Prefix: wp_oihqaskqjd_
MaxMind GeoIP Database: ✔
Datenbank-Gesamtgröße: 570.95MB
Datenbank-Datengröße: 325.86MB
Datenbank-Indexgröße: 245.09MB
wp_oihqaskqjd_woocommerce_sessions: Daten: 22.06MB + Index: 0.33MB
wp_oihqaskqjd_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB
wp_oihqaskqjd_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB
wp_oihqaskqjd_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB
wp_oihqaskqjd_woocommerce_order_items: Daten: 0.23MB + Index: 0.08MB
wp_oihqaskqjd_woocommerce_order_itemmeta: Daten: 3.52MB + Index: 3.03MB
wp_oihqaskqjd_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB
wp_oihqaskqjd_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB
wp_oihqaskqjd_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB
wp_oihqaskqjd_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB
wp_oihqaskqjd_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB
wp_oihqaskqjd_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB
wp_oihqaskqjd_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB
wp_oihqaskqjd_woocommerce_log: Daten: 0.02MB + Index: 0.02MB
wp_oihqaskqjd_commentmeta: Daten: 0.08MB + Index: 0.09MB
wp_oihqaskqjd_comments: Daten: 1.52MB + Index: 0.55MB
wp_oihqaskqjd_feedmanager_channel: Daten: 0.02MB + Index: 0.03MB
wp_oihqaskqjd_feedmanager_country: Daten: 0.02MB + Index: 0.03MB
wp_oihqaskqjd_feedmanager_errors: Daten: 0.02MB + Index: 0.00MB
wp_oihqaskqjd_feedmanager_feed_status: Daten: 0.02MB + Index: 0.08MB
wp_oihqaskqjd_feedmanager_field_categories: Daten: 0.02MB + Index: 0.00MB
wp_oihqaskqjd_feedmanager_product_feed: Daten: 0.02MB + Index: 0.02MB
wp_oihqaskqjd_feedmanager_product_feedmeta: Daten: 0.02MB + Index: 0.03MB
wp_oihqaskqjd_feedmanager_source: Daten: 0.02MB + Index: 0.08MB
wp_oihqaskqjd_icl_content_status: Daten: 0.02MB + Index: 0.02MB
wp_oihqaskqjd_icl_core_status: Daten: 0.02MB + Index: 0.02MB
wp_oihqaskqjd_icl_flags: Daten: 0.02MB + Index: 0.02MB
wp_oihqaskqjd_icl_languages: Daten: 0.02MB + Index: 0.03MB
wp_oihqaskqjd_icl_languages_translations: Daten: 0.19MB + Index: 0.08MB
wp_oihqaskqjd_icl_locale_map: Daten: 0.02MB + Index: 0.00MB
wp_oihqaskqjd_icl_message_status: Daten: 0.02MB + Index: 0.03MB
wp_oihqaskqjd_icl_mo_files_domains: Daten: 0.05MB + Index: 0.02MB
wp_oihqaskqjd_icl_node: Daten: 0.02MB + Index: 0.00MB
wp_oihqaskqjd_icl_reminders: Daten: 0.02MB + Index: 0.00MB
wp_oihqaskqjd_icl_strings: Daten: 5.52MB + Index: 4.97MB
wp_oihqaskqjd_icl_string_packages: Daten: 0.02MB + Index: 0.00MB
wp_oihqaskqjd_icl_string_pages: Daten: 221.75MB + Index: 211.34MB
wp_oihqaskqjd_icl_string_positions: Daten: 0.48MB + Index: 0.13MB
wp_oihqaskqjd_icl_string_status: Daten: 0.02MB + Index: 0.02MB
wp_oihqaskqjd_icl_string_translations: Daten: 3.52MB + Index: 1.52MB
wp_oihqaskqjd_icl_string_urls: Daten: 0.45MB + Index: 0.38MB
wp_oihqaskqjd_icl_translate: Daten: 8.52MB + Index: 1.52MB
wp_oihqaskqjd_icl_translate_job: Daten: 0.16MB + Index: 0.06MB
wp_oihqaskqjd_icl_translations: Daten: 0.48MB + Index: 0.94MB
wp_oihqaskqjd_icl_translation_batches: Daten: 0.02MB + Index: 0.00MB
wp_oihqaskqjd_icl_translation_status: Daten: 13.52MB + Index: 0.09MB
wp_oihqaskqjd_links: Daten: 0.02MB + Index: 0.02MB
wp_oihqaskqjd_options: Daten: 2.52MB + Index: 0.31MB
wp_oihqaskqjd_postmeta: Daten: 26.55MB + Index: 11.03MB
wp_oihqaskqjd_posts: Daten: 5.52MB + Index: 1.06MB
wp_oihqaskqjd_redirection_404: Daten: 0.02MB + Index: 0.06MB
wp_oihqaskqjd_redirection_groups: Daten: 0.02MB + Index: 0.03MB
wp_oihqaskqjd_redirection_items: Daten: 5.52MB + Index: 4.98MB
wp_oihqaskqjd_redirection_logs: Daten: 1.52MB + Index: 0.66MB
wp_oihqaskqjd_smush_dir_images: Daten: 0.02MB + Index: 0.03MB
wp_oihqaskqjd_termmeta: Daten: 0.06MB + Index: 0.06MB
wp_oihqaskqjd_terms: Daten: 0.06MB + Index: 0.03MB
wp_oihqaskqjd_term_relationships: Daten: 0.48MB + Index: 0.27MB
wp_oihqaskqjd_term_taxonomy: Daten: 0.05MB + Index: 0.03MB
wp_oihqaskqjd_usermeta: Daten: 0.31MB + Index: 0.25MB
wp_oihqaskqjd_users: Daten: 0.02MB + Index: 0.05MB
wp_oihqaskqjd_wc_download_log: Daten: 0.02MB + Index: 0.03MB
wp_oihqaskqjd_wc_product_meta_lookup: Daten: 0.16MB + Index: 0.31MB
wp_oihqaskqjd_wc_webhooks: Daten: 0.02MB + Index: 0.02MB
wp_oihqaskqjd_yoast_seo_links: Daten: 0.02MB + Index: 0.02MB
wp_oihqaskqjd_yoast_seo_meta: Daten: 0.30MB + Index: 0.00MB

### Post Type Counts ###

attachment: 4364
invoice: 1198
nav_menu_item: 109
oembed_cache: 1
page: 30
post: 2
product: 1726
product_variation: 2
revision: 228
shop_order: 630
shop_order_refund: 68
wpps-shortcodes: 8

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

ManageWP - Worker: von GoDaddy – 4.9.1
WPML Multilingual CMS: von OnTheGoSystems – 4.2.7.1
All-in-One WP Migration: von ServMask – 7.1
Angell EYE Updater: von Angell EYE – 2.0.6
Antispam Bee: von pluginkollektiv – 2.9.1
BackUpWordPress: von XIBO Ltd – 3.10
Classic Editor: von WordPress-Mitwirkende – 1.5
GDPR Cookie Consent: von WebToffee – 1.7.7
Duplicate Post: von Enrico Battocchi – 3.2.2
Google Tag Manager for Wordpress: von Thomas Geiger – 1.9.2 – Nicht getestest mit der aktiven WooCommerce-Version
WPBakery Page Builder: von Michael M - WPBakery.com – 6.0.3
Umleitungen: von John Godley – 4.3.1
woo-inquire-us-and-disable-add-to-cart-button: von themelocation – 1.3
Vendidero Helper: von Vendidero – 1.2.1
WooCommerce Blöcke: von Automattic – 2.2.0
PayPal PLUS für WooCommerce: von Inpsyde GmbH – 2.0.4
Germanized für WooCommerce Pro: von Vendidero – 1.11.1
Germanized für WooCommerce: von Vendidero – 2.3.2
WooCommerce Multilingual: von OnTheGoSystems – 4.6.5
Sofort Banking for WooCommerce: von Sven Wagener – 1.4.3
WooCommerce: von Automattic – 3.6.5 – 3.7.0 ist verfügbar
Yoast SEO: von Team Yoast – 11.6 – Nicht getestest mit der aktiven WooCommerce-Version
WP Product Feed Manager: von Michel Jongbloed – 1.14.0
Protected Shops: von conpark GmbH – 2.0
Protected Shops für WooCommerce: von conpark GmbH – 2.0 – Nicht getestest mit der aktiven WooCommerce-Version
Smush: von WPMU DEV – 3.2.1
WPML Media: von OnTheGoSystems – 2.5.2
WPML String Translation: von OnTheGoSystems – 2.10.5.1
WPML Translation Management: von OnTheGoSystems – 2.8.6.2

### Must Use Plugins (1) ###

ManageWP - Worker Loader: von ManageWP –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: #25 - /
Warenkorb: #6 - /warenkorb/
Kasse: #7 - /kasse/
Mein Konto: #8 - /mein-konto/
Allgemeine Geschäftsbedingungen: #44 - /agb/

### Theme ###

Name: MNV1
Version: 1 License: GNU General Public
Author URL: https://www.udo-telaar.de
Child Theme: ✔
Parent Theme Name: VendiPro
Parent Theme Version: 1.7.7
Parent Theme Author URL: http://wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: mnv1/woocommerce/archive-product.php
vendipro/woocommerce/cart/mini-cart.php
vendipro/woocommerce/checkout/form-checkout.php
vendipro/woocommerce/content-widget-product.php
vendipro/woocommerce/content-widget-reviews.php
mnv1/woocommerce/emails/customer-note.php
mnv1/woocommerce/emails/customer-processing-order.php
mnv1/woocommerce/emails/plain/customer-processing-order.php
vendipro/woocommerce/global/wrapper-end.php
vendipro/woocommerce/global/wrapper-start.php
vendipro/product-searchform.php
vendipro/woocommerce/single-product/review.php

### Action Scheduler ###

Complete: 0
Oldest: –
Newest: –

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

</details>

**Comment by pinolec** [comment]
I did not submit the above-mentioned https://github.com/pinolec/woocommerce/commit/0d17bd0421300c9d615d4886d9dec406924d5437Fix as it may break tax calculations for some. I have only tested this roughly with setup mentioned by @udotelaar
This fix need more testing.

**Comment by udotelaar** [comment]
Hi Tarek,

that's no reasonable option. A shop system should be able to multiplicate 5 x single price to the overall price in the correct way. What checkout system operates with three decimals!? That's out of touch with reality and not customer-friendly. It also is a problem with tax law and customs when the sum of single prices differs from total price.

**Comment by juliaamosova** [comment]
@udotelaar we are closing this issue in favor of https://github.com/woocommerce/woocommerce/issues/24975 - please continue to discuss and comment there.

**Comment by vedanshujain** [comment]
Reopening because this is different from to issue reported in #24975. I agree with the suggestion that, we should remove taxes before multiplying by quantity to reduce rounding errors.

**Comment by anant1811** [comment]
Also reported in 3245283-zen

**Comment by vedanshujain** [comment]
This is the same problem as in #27026, unfortunately, the fix here is to enter prices as they would be displayed. I have listed some workarounds in https://github.com/woocommerce/woocommerce/issues/27026#issuecomment-738913704. Eventually, looks like if we want to be accurate for most cases, which is that prices will be displayed to the customer how they are entered, for example, when gross will be displayed and gross will be entered, then there will be some inaccuracies when that is not the case, for example, when net will be displayed but gross was entered (the case here in this issue).

I tried this in many competing eCommerce software as well to get inspiration but was able to repro rounding issues depending on what set of configuration I chose.

We are planning to add more help text and settings to guide people for better setting selection In #29976. I am closing this as won't fix it for now, but also curious in case I have missed something and implement this fix is possible..

**Comment by udotelaar** [comment]
Hi Vendanshujain,

we use the settings that you recommend since the launch of our shop. The result is the bug shown above. 1,5 years later 5 x 8.36 Euro still results in 41.81. 

![Warenkorb](https://user-images.githubusercontent.com/657194/119619880-baea5c80-be04-11eb-8ad1-b625fbbbcbfc.jpg)

**Comment by boutzamat** [comment]
Why are you closing this?! You literally added "won't fix" status to it. 
Did you give up on fixing something as important the taxes in an e-commerce system? 

I must admit i am considering not using WooCommerce for my clients anymore. Which is sad because i just built a big Vue storefront for a headless WooCommerce, just to find out that you don't care about TAXES that are like the most important thing in a shopping system. Come on guys?
