### ISSUE TITLE
Free shipping method showing along with Flat rate. 

### ISSUE THREAD

**Issue by nayemDevs** [woocommerce/woocommerce#24628]
**Is your feature request related to a problem? Please describe.**
When I am adding Flat Rate and Free Shipping (Minimum order value 50) method for a specific zone that time If the customer from the zone try to purchase a product which amount is 50+ then below scenario happen -

Kindly check my backend settings: https://prnt.sc/p5m2ex

1. The customer is now eligible to get free shipping 
2. Also, the Flat rate shipping method showing while the customer is eligible to get free shipping. 

Cart page: https://prntscr.com/p5m3g9

**Describe the solution you'd like**
As the customer is purchasing amount of more than 50 and getting eligible for the Free shipping offer than other shipping methods for that zone should be hidden/disabled. 

**Additional context**
I want my customer to show only free shipping if they purchased more than $50 and don't want to see other available methods which are paid but if they do not meet the amount to get free shipping that time other available methods can be showed.

**Comment by uok** [comment]
This is not built in, you need to script it yourself
https://docs.woocommerce.com/document/hide-other-shipping-methods-when-free-shipping-is-available/

**Comment by nayemDevs** [comment]
@uok I am aware of the doc just checking if any possibility to add a simple checkbox while adding free shipping :)

**Comment by rynaldos** [comment]
@nayemDevs 

We don't disable methods or add a setting to do so automatically because some users will expect methods all to be offered. You'll need to use the code in that document (or the plugin) to do that.

**Comment by nayemDevs** [comment]
@rynaldos I agree that some user will expect methods but I am requesting for a checkbox so that those who do not need can enable the checkbox and who need can uncheck. You will agree with me that adding code on child-theme is not a general user task. However, I have applied the solution mentioned over the doc.

**Comment by claudiosanches** [comment]
Better follow the guide https://docs.woocommerce.com/document/hide-other-shipping-methods-when-free-shipping-is-available/ or try https://wordpress.org/plugins/wc-hide-shipping-methods/
