### ISSUE TITLE
Not importing pictures from AliExpress

### ISSUE THREAD

**Issue by Justinhed** [woocommerce/woocommerce#24647]
**Describe the bug**
When importing a product though AliExpress it now no longer imports the pictures to show in the product image and product gallery on the product

**To Reproduce**
1. Open Alidropship woo
2. Click on Import
3. Click on Direct Import from Ali Express
4. Find your product you want and click on Import
5. Go back to Wordpress to product and click on the product so the screen opens with your product
6. You will see your product but no image. When you open the product scroll down on the right side you will see product image and product gallery and nothing is there. It used to be there

**Expected behavior**
Images should be imported

**Comment by kloon** [comment]
Hi @Justinhed, the issue you describe seems to be related to the Alidropship plugin you are using. This issue tracker is only for reporting issues with WooCommerce core functionality and not plugins or themes.

I suggest you contact the developer of the plugin for assistance with this.
