### ISSUE TITLE
WooCommerce support for Twenty Twenty theme

### ISSUE THREAD

**Issue by yannickiki** [woocommerce/woocommerce#24648]
WordPress 5.3 will include a new core theme that will be released on November 12. Will WooCommerce support this theme?

**Comment by kloon** [comment]
Hi @yannickiki, while changes we made in past releases should cover any theme to be compatible, we will definitely be testing and adding in any compatibility issue fixes. We have always supported the default WordPress themes out of the box.

**Comment by peterfabian** [comment]
Some support could be improved, from a quick overview and comparison with 2019. Mostly layout and colors are off/inconsistent:

1.) Shop layout is too narrow, buttons are grey:
![Screenshot 2019-11-18 at 18 50 19](https://user-images.githubusercontent.com/2207451/69077589-3744f800-0a36-11ea-815e-b0fb8f07f681.png)

2. Homepage layout is also narrow, buttons are pink:
![Screenshot 2019-11-18 at 18 52 28](https://user-images.githubusercontent.com/2207451/69077623-4cba2200-0a36-11ea-9548-16006a52efa0.png)

3. Cart button colors are inconsistent, layout is too narrow:
![Screenshot 2019-11-18 at 18 53 41](https://user-images.githubusercontent.com/2207451/69077788-b3d7d680-0a36-11ea-89fb-9cd242f9b3fd.png)

4. Checkout: Layout is again too narrow, checkout button size and color is wrong, background for payment gateways looks suboptimal, form inputs are misaligned.
![FireShot Capture 002 - Checkout – Fixed Longhorn - fixed-longhorn jurassic ninja](https://user-images.githubusercontent.com/2207451/69077947-21840280-0a37-11ea-93f8-a5ab95b203ed.png)

5. Thank you page layout needs improvement:
![FireShot Capture 007 - Checkout – Fixed Longhorn - fixed-longhorn jurassic ninja](https://user-images.githubusercontent.com/2207451/69078161-935c4c00-0a37-11ea-97b3-35dfc38ff043.png)

6. Orders list without and with orders needs a better layout:
![Screenshot 2019-11-18 at 19 12 54](https://user-images.githubusercontent.com/2207451/69078129-82133f80-0a37-11ea-909d-cd11a44d94e2.png)

![Screenshot 2019-11-18 at 19 13 06](https://user-images.githubusercontent.com/2207451/69078236-b8e95580-0a37-11ea-8098-417cd57f6dd3.png)

For some pages (cart, checkout), the template can be changed in the Pages menu, in Document settings to Full width and those pages then look better, but this is not possible with Shop page or Single product page afaik.
![Screenshot 2019-11-18 at 19 19 20](https://user-images.githubusercontent.com/2207451/69078701-b4716c80-0a38-11ea-9678-70971b92a1d7.png)

**Comment by peterfabian** [comment]
Also, selectWoo looks broken:
![Screenshot 2019-11-18 at 19 23 36](https://user-images.githubusercontent.com/2207451/69078803-f7cbdb00-0a38-11ea-8346-13f0aaa27b94.png)

**Comment by peterfabian** [comment]
Reviews are shown as comments.
![Screenshot 2019-11-19 at 12 41 21](https://user-images.githubusercontent.com/2207451/69143709-e848a280-0ac9-11ea-835b-310336aadb8b.png)
