### ISSUE TITLE
Add category name/ID into CSS class in products list loop

### ISSUE THREAD

**Issue by jarretc** [woocommerce/woocommerce#24646]
Currently the loop HTML looks something like this

```
<div class="columns-#">
	<ul class="products columns-#">
		::before
		<li class="product-category product">
			More HTML/etc
		</li>
		<li class="product-category product">
			More HTML/etc
		</li>
                ::after
	</ul>
</div>
```

Because of this, you aren't able to target a specific category in the list to style due to there not being any name/ID set in the CSS class. Ideally it should look something like the following

```
<div class="columns-#">
	<ul class="products columns-#">
		::before
		<li class="product-category product category-id-1">
			More HTML/etc
		</li>
		<li class="product-category product category-id-3">
			More HTML/etc
		</li>
                ::after
	</ul>
</div>
```

Or use the category name in place of the ID though the ID would be simpler. The reasoning behind this is the post in the forums here:

https://wordpress.org/support/topic/remove-category-product-name-from-main-page/#post-11939226

You can see that due to there being no way to target the specific category, while the CSS works if a category is added/removed the styling needs to be updated for the :nth-of-type() value.

**Comment by claudiosanches** [comment]
There's already categories in that list, those are listed as `product_cat-<name>` format.
You also can customize it using `woocommerce_post_class` filter.

**Comment by jarretc** [comment]
Hi @claudiosanches, thanks for the response. I checked into this further and looks like I should have specified further. If you use the [product_categories] shortcode then then loop HTML that is output doesn't contain the category name in the CSS class.

**Comment by claudiosanches** [comment]
You can use `product_cat_class` filter to customize it.
