### ISSUE TITLE
New order created by code not displayed in list but shows count.

### ISSUE THREAD

**Issue by 33manish** [woocommerce/woocommerce#24656]
**Description**
I am using woocommerce Version 3.7.0. I am trying to add an order by code. My code is as follows 
		```
$order_data = array('customer_id' => $user);
		$order = wc_create_order($order_data);
		$product = new WC_Product(373);
		$order->add_product($product, 1);
		$order->set_address($address, 'billing');
		$order->set_address($address, 'shipping');
		$order->calculate_totals();
		$order->update_status('processing', TRUE);
```
Order placed and displayed in order count on order listing page. But this does not displayed on listing table. Please check attached image.

![Orders ‹ Heady Mix — WordPress](https://user-images.githubusercontent.com/55548883/65258856-47695580-db21-11e9-8d5a-9e5e292f7fc3.png)

As you can see in image there is
Order count = 8
But in the list there  are only 7 orders.

I can open order details by changing order id from address bar. It shows me all details correctly

Please check attached image

![Edit order ‹ Heady Mix — WordPress](https://user-images.githubusercontent.com/55548883/65259176-e0986c00-db21-11e9-8d2b-1b75ff96ed01.png)

Please help me to fix this issue.

**Comment by kloon** [comment]
From the sample code it seems you are not calling the save method on the order object? Can you perhaps add a `$order->save();` at the end and then test if this makes a difference?

**Comment by claudiosanches** [comment]
As @kloon said, you need to save again, the order is created and saved once by `wc_create_order()`, but after you updated including the new product, you suppose to save using `$order->save()`.
