### ISSUE TITLE
Make `WC_Abstract_Order::recalculate_coupons` method `public`

### ISSUE THREAD

**Issue by pulber** [woocommerce/woocommerce#24654]
I came across this problem and it seems to be an easy fix. Whenever a coupon is applied to a subscription order and you change order `line_items`, discount amount doesn't recalculate or apply. It might be true for regular orders as well.

It would be great to be able to use `recalculate_coupons` method at any time.

For now, I changed it from `protected` to `public`.

https://docs.woocommerce.com/wc-apidocs/source-class-WC_Abstract_Order.html#1010

**Comment by kloon** [comment]
Thanks for the suggestion @pulber, for now I would suggest the easiest would be to first remove the coupon and apply it again to the order after making changes to the line items, that should fix the issue without needing changes to the WooCommerce code base.

We will look into making that method public.

**Comment by pulber** [comment]
@kloon That was my first workaround, but it didn't help much in the following case: Subscriptions with recurring discount (X amount discount for X renewal orders) + expiration date + edit subscription line items.

**Comment by claudiosanches** [comment]
Thank you for suggesting this feature!

I'm closing the issue as it already has a PR, please continue the discussion over at #24740.
