### ISSUE TITLE
Browser cache active when using back/forward buttons on non-cached pages

### ISSUE THREAD

**Issue by uok** [woocommerce/woocommerce#24653]
While trying to find the reason for duplicate conversion tracking I noticed that the "Order received" page is sometimes cached in the browser, which should never be the case.

### Steps to reproduce
1. checkout and proceed to "order received" page (result: loaded from server)
2. navigate to another page, e.g. a product category (result: loaded from server)
3. use back button in browser to return to "order received" page 
4. Bug: page is loaded from browser cache

### Info
Apparently using `no-cache` is not enough to prevent browser from caching while using buttons

Helpful sources
https://stackoverflow.com/questions/31735428/prevent-browser-back-button-cache
https://stackoverflow.com/questions/49547/how-do-we-control-web-page-caching-across-all-browsers

WP 5.2.3
Woo 3.6.5

**Comment by kloon** [comment]
Closing issue as there is an open PR, can discuss further in #24652
