### ISSUE TITLE
Malformed order email in French

### ISSUE THREAD

**Issue by strategio** [woocommerce/woocommerce#24660]
**Describe the bug**

**To Reproduce**
- Setup WordPress in French
- Install and activate WooCommerce
- Complete the setup
- Create a simple product
- Order this product on the frontend

=> The received email is messed up as shown in the screenshot: The closing `h2` tag is missing the `>`.

Extract of the HTML:
```
<h2 style='color: #96588a; display: block; font-family: "Helvetica Neue", Helvetica, Roboto, Arial, sans-serif; font-size: 18px; font-weight: bold; line-height: 130%; margin: 0 0 18px; text-align: left;'>
[Commande n°37] (septembre 20, 2019)</h2<div style="margin-bottom: 40px;">
```

**Screenshots**
![order-in-french](https://user-images.githubusercontent.com/1941656/65350368-f3f81580-dbbb-11e9-84e6-d34c9a7f857a.png)

As a consequence, the whole markup below this tag is messed up (including the table).

**Debug:**
I tried to track this bug but I don't have too much time. The email content passed to PHPMailer seems correct and valid. It's possibly an issue with encoding somewhere in PHPMailer.

**Comment by uok** [comment]
Please post which Woo/WP version you are using.
Have you tried disabling all the other plugins? 
Does it only occur in French emails?

**Comment by kloon** [comment]
I checked WooCommerce 3.7 and the opening and closing h2 tag are present there. The code is part of templates/emails/email-order-details.php if you want to check for yourself.

I suggest you look at your theme for a WooCommerce folder and look in that folder if you perhaps not have the template file overridden as the issue likely lies there.

I am closing this issue as I am not able to replicate. Please test with all plugins disabled except WooCommerce and your theme switched to a default one like Storefront or Twentynineteen.

I will gladly reopen the issue if you can provide steps to replicate this with just the latest version of WooCommerce installed and no template files overridden.

**Comment by strategio** [comment]
HI,

Just to confirm, we initially thought of an bug in our plugin (WPML/WCML) but finally it was replicable with a fresh install and only WC (see my steps in the description).

I used all latest stable versions (WP 5.2.3 and WC 3.7.0), theme Twenty Nineteen and no other plugin.

At least 3 people managed to replicate this issue in our team.

As I said, I could not go further in debugging (lack of time).

Also, I cannot say if it happens in other languages (different than French).

I personnally don't use WooCommerce, I was just reporting an issue that I came accross. I'll let you consider it... or not.

**Comment by kloon** [comment]
OK, thanks @strategio. We will debug this a bit more.

**Comment by swatipawarGS** [comment]
Hi @strategio ,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end for French language  using WooCommerce 5.9.0 version , WordPress 5.8.2 version . 


Please find below screenshot for reference :

![#24660](https://user-images.githubusercontent.com/94531721/144374062-d03cb5f0-0d45-4133-96e0-f1d0ee666b29.jpg)


Please provide us more detailed and any additional steps required to repro this issue which may help us to evaluate it further.

**Comment by strategio** [comment]
Hi @swatipawarGS, this might have been fixed elsewhere.
Unfortunately, I have no time to re-test right now and it's not really a problem for me (I just reported something unexpected).
Let's close this issue then.
