### ISSUE TITLE
Woo and Elementor Conflict

### ISSUE THREAD

**Issue by rdrg520** [woocommerce/woocommerce#24679]
WooCommerece is not letting me use Elementor, my page builder.  

I uninstalled all plugins and reinstalled, one by one, until it revealed Woo was the issue, see attached.

![Screen Shot 2019-09-24 at 11 01 58 AM](https://user-images.githubusercontent.com/55758522/65538092-9d008200-ded4-11e9-9f04-fc092521d06a.png)

When I re-active Woo my page builder just sits there and spins, see left side of my screen where widgets are.

My store is not active until this is resolved.

Thanks for sooner news!!

**Comment by claudiosanches** [comment]
Do you have more details? What is the response for this Ajax request?
What errors are on your error log?
Also you completed removed the issue template, so missing several steps to understand this issue.

**Comment by peterfabian** [comment]
Hi @rdrg520 

I was unable to replicate your issue on a new site. 

Please provide more information about your configuration, e.g. the [system status report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/).

**Comment by claudiosanches** [comment]
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. I tried to reproduce this issue and it appeared to work correctly.

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

Thanks!
