### ISSUE TITLE
REST - undefined cart functions

### ISSUE THREAD

**Issue by vasikgreif** [woocommerce/woocommerce#24673]
I know the WC functions are not loaded in REST API as of 3.6. The fix used to be telling WC not to handle the request as a REST request:

```
add_filter( 'woocommerce_is_rest_api_request', [ $this, 'simulate_as_not_rest' ] );
	/**
	 * We have to tell WC that this should not be handled as a REST request.
	 * Since WooCommerce 3.6
	 *
	 * @param bool $is_rest_api_request
	 * @return bool
	 */
	public function simulate_as_not_rest( $is_rest_api_request ) {
		if ( empty( $_SERVER['REQUEST_URI'] ) ) {
			return $is_rest_api_request;
		}

		// Bail early if this is not our request.
		if ( false === strpos( $_SERVER['REQUEST_URI'], VINO_REST_NAMESPACE .'/added-to-cart' ) ) {
			return $is_rest_api_request;
		}

		return false;
	}
```

This does not seem to work anymore, I got a bunch of `undefined` functions, the first being `Undefined function wc_get_cart_item_data_hash() in /wp-content/plugins/woocommerce/includes/class-wc-cart-session.php`. I tried to fix that one, but got another one right after that.

I also tried to call the `wc_load_cart()` function, that did not help either. Is there another way to have the WC functions available in the REST API calls?

**Comment by vasikgreif** [comment]
@seb86 Thanks, that's a cool plugin! However, for what I need, this is overkill. I just need to be able to access the WC cart functions inside my custom REST endpoint. Maybe you could point me to a filter or something that gets me access to the core WC Cart / Session function inside of REST enpoint?

**Comment by seb86** [comment]
https://github.com/co-cart/co-cart/blob/master/includes/class-cocart-init.php#L145

**Comment by rodrigoprimo** [comment]
Closing as @seb86 suggestion in the last comment seems to solve your question (I didn't test it).

**Comment by vasikgreif** [comment]
Hmmm, not really. The real question is why the `woocommerce_is_rest_api_request` no longer works. The solution proposed by @seb86 is more a hack...

**Comment by rodrigoprimo** [comment]
I'm sorry if I'm missing something but could you please elaborate on what you mean by `woocommerce_is_rest_api_request` no longer works?

The filter still exists:

https://github.com/woocommerce/woocommerce/blob/1c47315b8952523bae50b96305499d8a82aee5d8/includes/class-woocommerce.php#L285

> I know the WC functions are not loaded in REST API as of 3.6.

cc @peterfabian as I believe you were involved in this change to stop loading frontend/theme code during REST requests (https://github.com/woocommerce/woocommerce/pull/21090) and might see something that I'm not seeing.

**Comment by vasikgreif** [comment]
@rodrigoprimo As said in the issue description, even when I return `false` using the filter, I still don't have the cart functions included for some reason. It might be some specific theme issue, I'll try this on a clean install...

**Comment by claudiosanches** [comment]
@vasikgreif are you doing it on a theme? Maybe is hooking too late.

**Comment by CJMcGregor** [comment]
I'm experiencing the same thing, and I am adding the filter in my theme's functions.php. If not there, where should it be added @claudiosanches  ?
