### ISSUE TITLE
Unexpected token error in JSON at payment checkout

### ISSUE THREAD

**Issue by christianloos** [woocommerce/woocommerce#24693]
We got some issues at our website regarding the ticketing system, we think it's possible that it's a WooComerce problem and we are not able to proceed with payments due to these two errors:

At the Chekout: Unexpected token < in JSON at position 0
https://mikejolley.com/2015/11/12/debugging-unexpected-token-in-woocommerce-2-4/

and after this -> 
?wc-ajax=checkout : Response : <h1>Error thrown</h1><p>Class 'ET_Builder_Element' not found</p>
This one is probably due to the Divi Builder but it could be related.

Here's the full report of our website status

Woocomerce status:
### WordPress Environment ###

WordPress address (URL): https://www.erasmuslifebudapest.com
Site address (URL): https://www.erasmuslifebudapest.com
WC Version: 3.7.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.13.6
PHP Version: 7.2.22
PHP Post Max Size: 64 MB
PHP Time Limit: 180
PHP Max Input Vars: 10000
cURL Version: 7.65.3
OpenSSL/1.0.2s

SUHOSIN Installed: –
MySQL Version: 5.6.45-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
Zapier Integration - Active Feeds: ✔ 1 active Zapier Feed.
Zapier Integration - Cron Tasks: ✔ 0 pending Zapier cron tasks.
Zapier Feed #1 Name: ✔ Orders to a google shheet
Zapier Feed #1 Webhook URL: ✔ https://hooks.zapier.com/hooks/catch/3725211/q19v7u/
Zapier Feed #1 Trigger: ✔ New Order
Zapier Feed #1 Test Result: ✔ Successfully sent sample data to https://hooks.zapier.com/hooks/catch/3725211/q19v7u/.

### Database ###

WC Database Version: 3.7.0
WC Database Prefix: wpELB_
MaxMind GeoIP Database: ✔
Total Database Size: 107.08MB
Database Data Size: 79.45MB
Database Index Size: 27.63MB
wpELB_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
wpELB_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpELB_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpELB_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpELB_woocommerce_order_items: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wpELB_woocommerce_order_itemmeta: Data: 0.28MB + Index: 0.27MB + Engine InnoDB
wpELB_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpELB_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpELB_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpELB_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpELB_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpELB_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpELB_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpELB_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_acl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_blocks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_countries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_lab: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_lab_ip: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cerber_lab_net: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cerber_log: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
cerber_qmem: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
cerber_traffic: Data: 7.52MB + Index: 0.27MB + Engine InnoDB
wpELB_blc_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpELB_blc_instances: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpELB_blc_links: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wpELB_blc_synch: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wpELB_cerber_files: Data: 6.48MB + Index: 1.00MB + Engine MyISAM
wpELB_cerber_sets: Data: 0.18MB + Index: 0.00MB + Engine MyISAM
wpELB_cerber_uss: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wpELB_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpELB_comments: Data: 3.52MB + Index: 1.83MB + Engine InnoDB
wpELB_EWD_OTP_Customers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpELB_EWD_OTP_Custom_Fields: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpELB_EWD_OTP_Fields_Meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpELB_EWD_OTP_Orders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpELB_EWD_OTP_Order_Statuses: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpELB_EWD_OTP_Sales_Reps: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpELB_jig_ext_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpELB_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpELB_loginizer_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpELB_ngg_album: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpELB_ngg_gallery: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpELB_ngg_pictures: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpELB_options: Data: 5.16MB + Index: 0.06MB + Engine InnoDB
wpELB_permalinks_customizer_redirects: Data: 0.31MB + Index: 0.04MB + Engine MyISAM
wpELB_postmeta: Data: 22.28MB + Index: 16.77MB + Engine InnoDB
wpELB_posts: Data: 13.44MB + Index: 2.63MB + Engine InnoDB
wpELB_realmedialibrary: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpELB_realmedialibrary_debug: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpELB_realmedialibrary_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpELB_realmedialibrary_posts: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wpELB_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wpELB_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpELB_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpELB_revslider_sliders: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wpELB_revslider_slides: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
wpELB_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpELB_swift_performance_image_optimizer: Data: 1.52MB + Index: 0.36MB + Engine InnoDB
wpELB_swift_performance_warmup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpELB_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpELB_terms: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wpELB_term_relationships: Data: 0.27MB + Index: 0.16MB + Engine InnoDB
wpELB_term_taxonomy: Data: 0.11MB + Index: 0.14MB + Engine InnoDB
wpELB_usermeta: Data: 1.48MB + Index: 0.80MB + Engine InnoDB
wpELB_users: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wpELB_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpELB_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpELB_wc_customer_lookup: Data: 0.15MB + Index: 0.15MB + Engine MyISAM
wpELB_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpELB_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpELB_wc_order_product_lookup: Data: 0.27MB + Index: 0.18MB + Engine MyISAM
wpELB_wc_order_stats: Data: 0.16MB + Index: 0.11MB + Engine MyISAM
wpELB_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpELB_wc_product_meta_lookup: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wpELB_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpELB_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpELB_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpELB_wfBlocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpELB_wfConfig: Data: 2.27MB + Index: 0.00MB + Engine InnoDB
wpELB_wfCrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpELB_wfFileChanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpELB_wfFileMods: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wpELB_wfHits: Data: 2.02MB + Index: 1.14MB + Engine InnoDB
wpELB_wfHoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpELB_wfIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpELB_wfKnownFileList: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wpELB_wfLiveTrafficHuman: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wpELB_wfLocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpELB_wfLogins: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wpELB_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpELB_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpELB_wfNotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpELB_wfPendingIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpELB_wfReverseCache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpELB_wfSNIPCache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpELB_wfStatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wpELB_wfTrafficRates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpELB_woocher: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wpELB_woocher_v2: Data: 0.20MB + Index: 0.00MB + Engine InnoDB
wpELB_woocommerce_extra_cost: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpELB_yarpp_related_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpELB_yoast_seo_links: Data: 0.34MB + Index: 0.09MB + Engine InnoDB
wpELB_yoast_seo_meta: Data: 0.08MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (37) ###

PW Advanced Woo Reporting: by Proword – 4.5 – Not tested with the active version of WooCommerce
Akismet Anti-Spam: by Automattic – 4.1.2
Integration for Billingo & WooCommerce - Extended: by Vizmeg Viktor & Bokor Bence & Viszt Péter – 1.6.6 – Not tested with the active version of WooCommerce
Broken Link Checker: by ManageWP – 1.11.8
Cookie Notice: by dFactory – 1.2.46
Email Encoder - Protect Email Address: by Ironikus – 1.53
EventON: by AshanJay – 2.7.3
EventON - Event Lists: by Ashan Jay – 0.9
EventON Slider Addon: by Federico Schiocchet - Pixor – 2.9.0
EventON - Event Tickets: by Ashan Jay – 1.7.7 – Not tested with the active version of WooCommerce
EventON - Weekly View: by Ashan Jay – 1.0.11
Justified Image Grid: by Belcovio – 3.9.2
Lightweight and Responsive Youtube Embed: by WPSzaki – 1.0.0
Loginizer: by Raj Kothari – 1.4.2
OneSignal Push Notifications: by OneSignal – 1.17.8
Barion Payment Gateway for WooCommerce: by Peter Szel  – 3.0.3 – Not tested with the active version of WooCommerce
Permalinks Customizer: by YAS Global Team – 2.7.0
Post Types Order: by Nsp Code – 1.9.4.1
WP Real Media Library: by Matthias Günter – 4.2.0
Slider Revolution: by ThemePunch – 5.4.1
WebP Express: by Bjørn Rosell – 0.16.0
Advanced Order Export For WooCommerce: by AlgolPlus – 3.0.3
WPC Product Bundles for WooCommerce: by WPclever.net – 3.7.2
Woocher: by dajer – 1.0.0
WooCommerce Admin: by WooCommerce – 0.19.0
WooCommerce Product Fees: by Caleb Burks – 1.3.0 – Not tested with the active version of WooCommerce
WooCommerce Zapier Integration: by OM4 – 1.6.0 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.7.0
Wordfence Security: by Wordfence – 7.4.0
WordPress Importer: by wordpressdotorg – 0.6.4
Yoast SEO Premium: by Team Yoast – 9.5
WP Cerber Security, Antispam & Malware Scan: by Cerber Tech Inc. – 8.4
WP Show Posts: by Tom Usborne – 1.1.3 – Not tested with the active version of WooCommerce
Yoast SEO: Local: by Team Yoast and Arjan Snaterse – 9.2
Yoast SEO: WooCommerce: by Team Yoast – 9.2 – Not tested with the active version of WooCommerce
Yet Another Related Posts Plugin: by YARPP – 5.1.1
NextGEN Gallery: by Imagely – 3.2.18

### Inactive Plugins (45) ###

Classic Editor: by WordPress Contributors – 1.5
Conditional Product Fees For WooCommerce Checkout: by Thedotstore – 3.0.1 – Not tested with the active version of WooCommerce
Easy Social Post Feed: by Danish Ali Malik – 4.4.3
EventON - Action User: by Ashan Jay – 2.1.7
EventON - Countdown timer: by Ashan Jay – 0.4
EventON - CSV import: by Ashan Jay – 1.1.6
EventON - Daily View: by Ashan Jay – 1.0.8
EventON - Event Search: by Ashan Jay – 0.7
EventON - Full cal: by Ashan Jay – 1.1.6
EventON - QR Code: by Ashan Jay – 1.1
EventON - RSVP Events: by Ashan Jay – 2.5.15
EventON - Subscriber: by Ashan Jay – 1.2.5
EventON - Sync Events: by Ashan Jay – 1.2.1
Facebook for WooCommerce: by Facebook – 1.9.15 – Not tested with the active version of WooCommerce
Gutenberg: by Gutenberg Team – 6.5.0
Health Check & Troubleshooting: by The WordPress.org community – 1.4.0
Hello Dolly: by Matt Mullenweg – 1.7.2
Jetpack by WordPress.com: by Automattic – 7.7.2
Media Grid: by Luca Montanari – 6.12
P3 (Plugin Performance Profiler): by GoDaddy.com – 1.5.3.9
Query Monitor: by John Blackbourn – 3.3.7
Related Posts by AddThis: by The AddThis Team – 2.2.6
Slider Revolution 404 Page Add-On: by ThemePunch – 1.0.1
Slider Revolution Background FilmStrip Add-On: by ThemePunch – 1.0.0
Slider Revolution Background Slicey Add-On: by ThemePunch – 1.0.0
Slider Revolution Backup Add-on: by ThemePunch – 1.0.1
Slider Revolution Coming Soon & Maintenance Add-on: by ThemePunch – 1.0.4
Slider Revolution Featured Slider Add-on: by ThemePunch – 1.0.0
Slider Revolution Holiday Snow: by ThemePunch – 1.0.3
Slider Revolution Login Page Add-on: by ThemePunch – 1.0.0
Slider Revolution Particles Effect: by ThemePunch – 1.0.3
Slider Revolution Polyfold Scroll Effect: by ThemePunch – 1.0.1
Slider Revolution Previous and Next Posts Add-On: by ThemePunch – 1.0.0
Slider Revolution Related Posts Add-On: by ThemePunch – 1.0.0
Slider Revolution Sharing Add-on: by ThemePunch – 1.0.0
Slider Revolution Typewriter Effect: by ThemePunch – 1.0.0
Slider Revolution Whiteboard Add-on: by ThemePunch – 1.0.4
Slider Revolution WP Gallery Add-On: by ThemePunch – 1.0.1
Status and Order Tracking: by Etoile Web Design – 2.11.13 – Not tested with the active version of WooCommerce
Super Socializer: by Team Heateor – 7.12.35
Swift Performance: by SWTE – 1.6.8
Tawk.to Live Chat: by Tawkto – 0.4.1
User Menus: by Jungle Plugins – 1.1.3
WooCommerce Blocks: by Automattic – 2.4.2
WooCommerce Custom Fields: by RightPress – 2.2.4 – Not tested with the active version of WooCommerce

### Must Use Plugins (1) ###

ET Support Center :: Must-Use Plugins Autoloader: by Elegant Themes –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: HUF (Ft)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
woosb (woosb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /fiokom/
Terms and conditions: #124 - /terms-and-conditions

### Theme ###

Name: Divi Child
Version: 1.0.0
Author URL: https://www.elegantthemes.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.29.3
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 2,168
Oldest: 2019-08-26 12:14:06 +0000
Newest: 2019-09-26 10:46:12 +0000

Pending: 3
Oldest: 2019-09-26 11:42:07 +0000
Newest: 2019-10-01 13:58:50 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

**Comment by rodrigoprimo** [comment]
Hi there!

GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/
