### ISSUE TITLE
How to search for more than one attribute Use this API https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products

### ISSUE THREAD

**Issue by Coder108** [woocommerce/woocommerce#24691]
Excuse me

 I use this API of this URL
https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products

But only attributes and attribute_term are required for the API to request with attributes parameters. When I use them, I don't know how to get products based on multiple attributes. For example, I want to get a list of products, which is country = France, year = 1998 and 2010, grape variety = Merlot grape wines.

How can such requests use this API xxx/wp-json/wc/v3/products to get the data?

**Comment by rodrigoprimo** [comment]
Unfortunately, filtering products by multiple attributes is not currently supported by the WooCommerce REST API.
