### ISSUE TITLE
structured data brand and id missing according to google markup testing tool

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#24703]
i get these warnings

![afbeelding](https://user-images.githubusercontent.com/6078370/65775838-3764fd80-e141-11e9-825c-3229854fc4fa.png)

 i know i can fix them by a filter and trick woo, but i rather have woo fix these permanent.

Thank you !

`/*
 * Rich Snippet Data
 * Add missing data not handled by WooCommerce yet
 */
function custom_woocommerce_structured_data_product ($data) {
	global $product;
	
	$data['brand'] = $product->get_name() ?? null;
	if ($data['brand']=='') $data['brand']='no-brand';
	$data['mpn'] = $product->get_sku() ?? null;
	if ($data['mpn']=='') $data['mpn']=$product->get_id() ?? null;
	
	return $data;
}
add_filter( 'woocommerce_structured_data_product', 'custom_woocommerce_structured_data_product' );`

**Comment by peterfabian** [comment]
Thanks for reporting. 

Please see comment https://github.com/woocommerce/woocommerce/issues/22896#issuecomment-477074896.
