### ISSUE TITLE
WC CLI: Regenerate product thumbnails

### ISSUE THREAD

**Issue by traed** [woocommerce/woocommerce#24713]
Sometimes product thumbnails break. For example, I've found that when importing products using the (official) CSV import suite plugin no thumbnails get generated. Rather than using a third party plugin to regenerate all thumbnails (which can be several thousands for large shop) i can use WP_CLI and wp media regenerate to regenerate specific thumbnails. However, this gets rather tedious if there are multiple images in a product gallery and/or if the product is variable and the variations also have images since wp media regenerate only accepts attachments IDs. Hence, I propose a CLI command to regenerate all images for a specific product ID.

**Describe the solution you'd like**
wp wc product regenerate_thumbnals --id=123
Regenerates all thumbnails for the specified ID(s).

**Describe alternatives you've considered**
Alternative 1 - Using the Regenerate Thumbnails plugin to regenerate all thumbnails. Not viable for shops with a lot of products.
Alternative 2 - Using wp media regenerate. Tedious if a product has a lot of attachments since it only accepts attachment IDs.

**Comment by claudiosanches** [comment]
You can run for all images with:

```bash
wp media regenerate
```

Or combine results from `wp post meta get <id> _product_image_gallery` and `wp post meta get <id> _thumbnail_id` with `wp wc product regenerate_thumbnals --id=<ids>`.

**Comment by claudiosanches** [comment]
Here an example of script to speed up this process, lets call it `script.sh`:

```bash
#!/bin/sh

PRODUCT_ID=$1

if [ -z "${PRODUCT_ID}" ]; then
	echo "Requires a product ID"
	echo
	echo "run \"./script.sh <id>\""
fi

IMAGE_GALLERY=$(wp post meta get "${PRODUCT_ID}" _product_image_gallery)
THUMBNAIL_ID=$(wp post meta get "${PRODUCT_ID}" _thumbnail_id)
RAW_IDS="${IMAGE_GALLERY},${THUMBNAIL_ID}"
IDS=`echo "${RAW_IDS}" | tr ',' ' '`

wp media regenerate "${IDS}"
exit
```

With it now you can just run `./script.sh <product_id>`.

**Comment by jorgeatorres** [comment]
Given there's a workaround available (using WP-CLI itself) and there hasn't been a ton of interest in this, we're closing for now. Feel free to re-open if I've misinterpreted something and the WP-CLI alternative isn't a good fit for some reason. Thanks!
