### ISSUE TITLE
Pages not created on install

### ISSUE THREAD

**Issue by JakeQZ** [woocommerce/woocommerce#24710]
**Describe the bug**
Pages 'Shop', 'My Account', 'Cart', 'Checkout' are not created upon installing WooCommerce.

**To Reproduce**
1. Install WooCommerce
2. Do not run the Setup Wizard
3. Go to Pages in the admin dashboard
4. See that there are no WooCommerce pages created

**Expected behavior**
The WooCommerce pages 'Shop', 'My Account', 'Cart', 'Checkout' should be created.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Additional Information**

Discussion at https://wordpress.org/support/topic/pages-not-auto-created-in-3-7-0/.  It appears that page creation has been incorrectly moved to the Setup Wizard.  This is a retrograde change and should be reverted.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://&ast;&ast;&ast;&ast;.co.uk/wordpress
Site address (URL): https://&ast;&ast;&ast;&ast;.co.uk
WC Version: 3.7.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.30 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.44-cll-lve
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.0
WC Database Prefix: ppadsdev_
MaxMind GeoIP Database: ✔
Total Database Size: 0.69MB
Database Data Size: 0.55MB
Database Index Size: 0.14MB
ppadsdev_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ppadsdev_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ppadsdev_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ppadsdev_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ppadsdev_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ppadsdev_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ppadsdev_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ppadsdev_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ppadsdev_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ppadsdev_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ppadsdev_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ppadsdev_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ppadsdev_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ppadsdev_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ppadsdev_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ppadsdev_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ppadsdev_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ppadsdev_options: Data: 0.51MB + Index: 0.03MB + Engine MyISAM
ppadsdev_postmeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
ppadsdev_posts: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
ppadsdev_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ppadsdev_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ppadsdev_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ppadsdev_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ppadsdev_usermeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ppadsdev_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ppadsdev_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
ppadsdev_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ppadsdev_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
ppadsdev_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Akismet Anti-Spam: by Automattic – 4.1.2
Classic Editor: by WordPress Contributors – 1.5
Performance Pads: by QZ Design – 0.2.0
WooCommerce: by Automattic – 3.7.0
WP Mail SMTP: by WPForms – 1.6.2

### Inactive Plugins (1) ###

Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #8 - /shop
Basket: #10 - /basket
Checkout: #12 - /checkout
My account: #14 - /my-account
Terms and conditions: ❌ Page not set

### Theme ###

Name: Expert Movers
Version: 0.2
Author URL: https://www.luzuk.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: expert-movers/woocommerce/archive-product.php
expert-movers/woocommerce/checkout/form-checkout.php
expert-movers/woocommerce/global/wrapper-end.php
expert-movers/woocommerce/global/wrapper-start.php
expert-movers/woocommerce/single-product.php


### Action Scheduler ###

Complete: 2
Oldest: 2019-09-12 15:23:49 +0100
Newest: 2019-09-21 12:25:43 +0100

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by peterfabian** [comment]
Just checking the git, it seems like it was like this for ±2 years. I agree that it could be confusing to new users, so we might think about moving it to other phase of plugin activation/installation.

**Comment by JakeQZ** [comment]
You may be right that it was changed longer ago than I thought it was.

But you might want to consider this typical scenario:
- I'm a developer setting up a site for a client
- I don't have the full details of the clients' business, that's for them to fill in when they run the Setup Wizard, which might be some time after installation
- In the meantime, they'd like to see a demostration of how the site will work (including these pages)

**Comment by claudiosanches** [comment]
Creating on `register_activation_hook()` should not be good, since may create pages before WordPress download language packs and then creating pages in English for everyone.
This is one of the reasons why we only create after is installed, what we can do is maybe to include a message about it, so people can click and create.

**Comment by JakeQZ** [comment]
> Maybe we can include a warning/notice if pages are not created with a button to trigger it if the Setup Wizard is ignored.

That could be useful - something like a pre-Setup Wizard (for want of a better name).  Is there anything else similar that the Setup Wizard does that may nonetheless be required if it's not run?  (I'm not aware of anything, but that doesn't mean there isn't anything.)

**Comment by claudiosanches** [comment]
Just those pages are required to run properly, all other settings have default values already.

**Comment by barryhughes** [comment]
There hasn't been too much interest in this issue since it was created and, with the latest version of WooCommerce, if I:

- Install
- Activate
- Skip guided setup
- Navigate to the page list

I see the expected WooCommerce pages have been created:

<div align="center"><img width="519" alt="Screenshot 2024-03-06 at 19 54 53" src="https://github.com/woocommerce/woocommerce/assets/3594411/d830e05b-de83-4870-aa33-8104cd85f563"></div>

I don't think there's a need for more work here, so will go ahead and close this issue.
