### ISSUE TITLE
Thank You Page does not meet requirements for PayPal Auto Return

### ISSUE THREAD

**Issue by ldr2273** [woocommerce/woocommerce#24723]
As seen here: https://www.sandbox.paypal.com/businessmanage/preferences/website

> Auto return for website payments brings your buyers back to your website immediately after completing a payment. Auto return applies to PayPal website payments, including “buy now” payments, donations, subscriptions, and shopping cart payments.
> 
> Return URL requirements:
> Enter the URL that will be used to redirect your customers after a payment. This URL must meet the guidelines detailed below.

> - According to our User Agreement, you must explain to the buyer on the page displayed by the return URL that the payment has been made and the transaction completed.

> - You must explain on the page displayed by the return URL that payment transaction details will be emailed to the buyer.

> - Example: Thank you for your payment. Your transaction has been completed, and a receipt for your purchase has been emailed to you. Log into your PayPal account to view transaction details.

Auto Return is the default if using PDT, I believe.

The WooCommerce Thank You page only provides the following information: 

![Thank You](https://cloudup.com/caMw3Gjr3Jb+)
Full Size Link: https://cloudup.com/caMw3Gjr3Jb

Is this something we can get updated?

**Comment by claudiosanches** [comment]
We can include more information for PayPal.

**Comment by ldr2273** [comment]
2336836-zen

Adding affected ticket/user here so we can follow up once this is addressed.

Filed Report based off this convo: https://a8c.slack.com/archives/C0E1AV8T0/p1569807214117000

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24756.
