### ISSUE TITLE
Problem adding products in product category as there is no option of categories while adding product

### ISSUE THREAD

**Issue by Ishikarathore** [woocommerce/woocommerce#24721]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.
2.
3.

## Expected/actual behavior

When I follow those steps, I see...

I was expecting to see...

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin here.
```
</details>

**Comment by ashucg** [comment]
You've shared nothing useful, literally. Please, at least include **WordPress Environment** details so that someone can actually try to reproduce this issue.

**Comment by rodrigoprimo** [comment]
Closing as there is not enough information on this issue. If you found a WooCommerce bug, please open another issue and provide all the information requested in the bug report template.

Keep in mind that this channel is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/
