### ISSUE TITLE
Performance: lots of postmeta should not be recorded upon order creation

### ISSUE THREAD

**Issue by RobertMPop** [woocommerce/woocommerce#24726]
**Is your feature request related to a problem? Please describe.**

When an order is placed, Woocommerce alone stores at least 41 lines related to that order in the post_meta table. So please keep in mind that we're not even considering other custom lines.

This issue should be properly addressed, since lot of that stored data is not relevant/necessary in many cases.

**Describe the solution you'd like**

Let's break down some major cases:

**1) Taxes**

If taxes are not enabled (the respective checkbox in _Settings->General_ is empty), the following lines should not be recorded:

`_cart_discount_tax,
_order_shipping_tax,
_order_tax,
_prices_include_tax,
is_vat_exempt`

**2) Coupons**

If coupons are not used (the respective checkbox in _Settings->General_ is empty), the following lines should not be recorded:

`_cart_discount,
_recorded_coupon_usage_counts`

**3) Shipping destination**

If `'Force shipping to the customer billing address'` option is selected in _Settings->Shipping->Shipping options_, the following lines should not be recorded (and only billing details should be used for shipping purposes):

`_shipping_first_name,
_shipping_last_name,
_shipping_address_1,
_shipping_address_2,
_shipping_city,
_shipping_state,
_shipping_country,
_shipping_address_index`

  **3) a.** As a further performance improvement, I would also suggest that all billing details could be recorded as an **array**, instead of 7 separate post meta lines as they are currently recorded.

  **3) b.** Are `_billing_address_index` and `_shipping_address_index` used anywhere? -> maybe you should consider completely removing them.

**4) Selling only physical products**

If no downloadable items are involved, `_download_permissions_granted` should not be recorded.

**5) Other questionable post meta**

`_recorded_sales,
_order_stock_reduced`

Are these used somehow? I mean, when a product is sold, there is the `total_sales` product meta that gets updated and that should suffice.

**As you can see, in my case (as well as it surely is the case for many, many, many other Woocommerce stores), the order-related post_meta _could be reduced from ~42 to ~19_, which would be a hell of an improvement.**

**Comment by claudiosanches** [comment]
I agree with most of those items, we probably going to work on it, we are planning to reduce a few of those already logged in #23235.

Here some notes about the ones that we aren't going to remove:

> 3) a. As a further performance improvement, I would also suggest that all billing details could be recorded as an array, instead of 7 separate post meta lines as they are currently recorded.

This is something that we aren't going to do, it will cause unnecessary backwards compatibility. Currently we considering moving into flat/custom tables, so should be nice to avoid more backwards compatibility before we maybe try it.

> 3) b. Are _billing_address_index and _shipping_address_index used anywhere? -> maybe you should consider completely removing them.

Those are used by searching orders in the back-end. Without those indexes may become heavy to proper search for orders.

> 5) Other questionable post meta
>
>_recorded_sales, _order_stock_reduced
>
>Are these used somehow? I mean, when a product is sold, there is the total_sales product meta that gets updated and that should suffice.

Yes, those are used, for example `_order_stock_reduced` is important to avoid reducing stock twice.

**Comment by stevegrunwell** [comment]
@RobertMPop We're working on moving order data into a custom table right now as a feature plugin; this may be of interest to you: https://github.com/liquidweb/woocommerce-custom-orders-table

**Comment by RobertMPop** [comment]
@stevegrunwell yes, I've been aware for quite some time that you guys are working on that, be sure that we very much salute your initiative and please keep up the good work in going forward with it.

WooCommerce needs to be released from its scalability chains and, once it does, it will skyrocket. There are also the product custom tables that the WC guys hopefully are still working on.

As concerns my opened issue, I simply wanted to convey that minor changes could be easily made to the code and thus save a lot of postmeta rows, while we're waiting for the custom tables to land. For instance, I've customized the code and reduced the number of product-related postmeta to ~10 / product, but it will still not beat custom tables in the long run, since I run a marketplace where lots of products are being added by vendors every single day.

**Comment by mfs-mindsize** [comment]
@claudiosanches  said:

```
_a. As a further performance improvement, I would also suggest that all billing details could be recorded as an array, instead of 7 separate post meta lines as they are currently recorded._
This is something that we aren't going to do, it will cause unnecessary backwards compatibility. Currently we considering moving into flat/custom tables, so should be nice to avoid more backwards compatibility before we maybe try it.
```
Is that 100% accurate tho'? Isn't the point of having classes (e.g., WC_Customer) to access the DB is to mitage any risk of backwards compatibility? For example, 

```
	public function set_shipping_first_name( $value ) {
		$this->set_address_prop( 'first_name', 'shipping', $value );
	}
```
How that value is returned doesn't matter. And there could be a conditional (for WC version?) that determines if it's a from a single meta row or out of an array? 

Note: I understand there's an underlying effort (per @stevegrunwell) to rework the DB. So yeah, maybe some of these don't make sense to address in the middle of that progress. Mine is more of a curiosity question for clarity. Thanks :)

**Comment by rrennick** [comment]
> When an order is placed, Woocommerce alone stores at least 41 lines related to that order in the post_meta table.

The high performance order storage data store (HPOS) eliminates these post meta rows so I'll mark this as addressed.
