### ISSUE TITLE
WP 5.3 admin CSS compat

### ISSUE THREAD

**Issue by sybrew** [woocommerce/woocommerce#24731]
**Describe the bug**
WordPress 5.3 overhauled the admin interface.

With that, the descenders of the text in the select-elements are overflowing and hidden:

![image](https://user-images.githubusercontent.com/7662236/65955383-481ab980-e448-11e9-90a5-728bfff1cd3a.png)

**The cause**
Using WC 3.7, in `in wp-content/plugins/woocommerce/assets/css/admin.css`, the line-height property is causing this:
```css
.post-type-product .tablenav select {
   line-height: 1;
}
```

Source:
https://github.com/woocommerce/woocommerce/blob/4593f523fd3750e86970b17eeaaba29b5e86f02a/assets/css/admin.scss#L6531-L6540

**Comment by dougaitken** [comment]
@sybrew Can you confirm what browser and device you are using, please? 

I'm not able to replicate on WooCommerce `3.7.0` and latest WordPress `5.3` beta.

Firefox (latest) on macOS 10.14.6:

<img width="1262" alt="wc_37_wp53" src="https://user-images.githubusercontent.com/52214/65964566-270c9580-e455-11e9-8c81-ea57ba5e66ef.png">

<details>
`
### WordPress Environment ###

WordPress address (URL): [URL]
Site address (URL): [URL]
WC Version: 3.7.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3-beta2-46366
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Unix) OpenSSL/1.0.2g
PHP Version: 7.2.22
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.27-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.0
WC Database Prefix: wp_e8a3ea50f0_
MaxMind GeoIP Database: ✔
Total Database Size: 2.15MB
Database Data Size: 1.17MB
Database Index Size: 0.98MB
wp_e8a3ea50f0_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e8a3ea50f0_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_e8a3ea50f0_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e8a3ea50f0_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_e8a3ea50f0_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e8a3ea50f0_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_e8a3ea50f0_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_e8a3ea50f0_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_e8a3ea50f0_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e8a3ea50f0_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_e8a3ea50f0_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_e8a3ea50f0_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e8a3ea50f0_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_e8a3ea50f0_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e8a3ea50f0_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_e8a3ea50f0_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_e8a3ea50f0_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e8a3ea50f0_options: Data: 0.52MB + Index: 0.03MB + Engine InnoDB
wp_e8a3ea50f0_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_e8a3ea50f0_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_e8a3ea50f0_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_e8a3ea50f0_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_e8a3ea50f0_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e8a3ea50f0_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_e8a3ea50f0_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_e8a3ea50f0_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_e8a3ea50f0_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_e8a3ea50f0_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_e8a3ea50f0_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_e8a3ea50f0_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (3) ###

Companion Plugin: by Osk – 1.11
WooCommerce: by Automattic – 3.7.0
WordPress Beta Tester: by Peter Westwood
Andy Fragen – 2.1.0


### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.2
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2019-10-01 13:07:31 +0000
Newest: 2019-10-01 13:07:31 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by sybrew** [comment]
Hi @dougaitken 

I missed critical details, my apologies.
- WP 5.3-beta2-46366
- WC 3.7.0
- Chrome 77.0.3865.90 (here lies the problem)
- Windows 10 Pro 1809 @ 17763.678 (I think this is also an issue on OSX and Linux, however)

**Comment by dougaitken** [comment]
Thanks @sybrew for confirming!

> Chrome 77.0.3865.90 (here lies the problem)

Yup.
I can confirm Chrome `77.0.3865.90` on macOS  along with Safari is the same as well - (Safari `Version 13.0.1 (14608.2.11.1.11)`)

**Comment by peterfabian** [comment]
Not sure if it's just my installation, but I can see some problems also in variations:
![Screenshot 2019-10-02 at 13 09 32](https://user-images.githubusercontent.com/2207451/66039732-f7719200-e515-11e9-9c0c-5814a21fcc1e.png)

**Comment by dougaitken** [comment]
Can confirm same as @peterfabian - the fields aren't as "squashed" but they're still cut off:

FYI this screenshot is on 3.8 beta 1

<img width="1036" alt="variable_product_data_squashed" src="https://user-images.githubusercontent.com/52214/66123577-4f71cc80-e5da-11e9-8103-5a1f62bd171c.png">

latest Firefox on latest macOS, screen size doesn't change the ratio of squashed or not.

**Comment by peterfabian** [comment]
As we want to prepare for WP 5.3, I've bumped this to 3.8 milestone and created the PR to fix the problems.

**Comment by Spreeuw** [comment]
@peterfabian It looks like there's stil a misalignment with WC3.8-RC1 and WP5.3-RC1 in the action buttons area that was not addressed with #24832 :
![wp53wc38-actions](https://user-images.githubusercontent.com/3217773/67407942-87a47380-f5b8-11e9-8fb6-985cf17b91aa.png)

**Comment by peterfabian** [comment]
Reopening to fix the action buttons.

**Comment by peterfabian** [comment]
Please see #25119.
