### ISSUE TITLE
Coupon Brings Total Below Free Shipping Threshold

### ISSUE THREAD

**Issue by tedmonk** [woocommerce/woocommerce#24754]
I apologize in advance if this isn't the correct section for this issue. Here's the problem I came across:

When a $X off coupon is applied, there are instances where, because of the item cost and the coupon amount, the order total goes below the free shipping threshold which then charges the user shipping, when it shouldn't.

To reproduce create a Free Shipping option for X amount and a Coupon for $X off. Purchase an Item with a price that is eligible for free shipping but will drop below the free shipping threshold when the coupon is applied.

I believe the coupon should be applied after the total amount is calculated, therefore making the coupon always valid.

Thanks for allowing me to bring this to your attention.

**Comment by claudiosanches** [comment]
Changing it may cause backwards compatibility for our current users, since by default discounts should be considered before allowing free shipping.
But we could include an option for free shipping if should ignore discounts or not.

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24776.
