### ISSUE TITLE
Add Lao Province Request

### ISSUE THREAD

**Issue by Dezueka** [woocommerce/woocommerce#24762]
Please add Lao State or province in your standard woocommerce format. I have my own custom LA Provinces, but wheneever Woocommerce has updated, it also delete my LA state or province. 

So I write this topic to request you adding it for us. I have updated the 2 files with states.php and adding LA.php file in the states folder of woocommerce. 

It work, and I have just wanted you to make it woocommerce standard available, through all update version. I will give you the files if you want to add it on the future update version.
Best Regard,
Laotian.Co

**Comment by rodrigoprimo** [comment]
If you have some time, please review #24765. Thanks for your contribution.
