### ISSUE TITLE
Set image CSS on emails to be max-width: 100%

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#24763]
When using the WooCommerce email templates to send ant content that has images on it, if the image is larger than the email template width, it will break it:

![image](https://user-images.githubusercontent.com/6853605/66115159-2cd6b800-e5c8-11e9-9974-2c6c5a571d6e.png)

In this example, it's an AutomateWoo email, but it could anything that has an image on it.

I suggest that this is added to the email css for images:
`max-width: 100%;
height: auto;`

**Comment by claudiosanches** [comment]
Thank you for suggesting this change!

I'm closing the issue as it already has a PR, please continue the discussion over at #24764.
