### ISSUE TITLE
Scheduled Actions are displayed in Comments if WooCommerce is deactivated

### ISSUE THREAD

**Issue by kalonya** [woocommerce/woocommerce#24775]
**Describe the bug**
When there are scheduled tasks and Woocommerce is deactivated, those tasks are shown in the Comments section of Wordpress and also displayed as the recent comments on Blog pages on the frontend.

**To Reproduce**
1. Check if there are any Scheduled Tasks in Woocommerce>Status>Scheduled Actions. Click on the "Update Database" button in Woocommerce>Status>Tools if there is nothing.
2. Navigate to Plugins and deactivate WooCommerce.
3. Click on Comments at the left sidebar of the admin panel.
4. See error.

**Screenshots**
<img width="1440" alt="Screen Shot 2019-10-05 at 22 17 30" src="https://user-images.githubusercontent.com/16854238/66260525-15fab600-e7c0-11e9-8fe9-8a753fa18d03.png">
<img width="570" alt="Screen Shot 2019-10-05 at 22 17 38" src="https://user-images.githubusercontent.com/16854238/66260526-15fab600-e7c0-11e9-80e9-c104a00e0f44.png">

With Storefront:
<img width="1271" alt="Screen Shot 2019-10-05 at 22 39 15" src="https://user-images.githubusercontent.com/16854238/66260609-04fe7480-e7c1-11e9-9bc6-cf0c70679a74.png">

With XDebug:
<img width="1282" alt="Screen Shot 2019-10-05 at 22 20 49" src="https://user-images.githubusercontent.com/16854238/66260527-16934c80-e7c0-11e9-9d2a-b5240985cb8e.png">

**Expected behavior**
Those tasks shouldn't be displayed among the Comments even the Woocommerce is deactivated.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only the WooCommerce plugin is active (and deactivated).
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://flatsome-main.kalonya
Site address (URL): http://flatsome-main.kalonya
WC Version: 3.7.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.3.2
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.34
Max Upload Size: 1,000 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 4.83MB
Database Data Size: 3.57MB
Database Index Size: 1.26MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.08MB + Index: 0.05MB + Engine InnoDB
wp_postmeta: Data: 0.31MB + Index: 0.23MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_social_users: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (10) ###

Contact Form 7: by Takayuki Miyoshi – 5.1.4
Jetpack by WordPress.com: by Automattic – 7.8
Klarna Checkout for WooCommerce: by Krokedil – 1.11.3
Mailchimp for WooCommerce: by Mailchimp – 2.2.4
Nextend Social Login: by Nextendweb – 3.0.20
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.17
WooCommerce Stripe Gateway: by WooCommerce – 4.2.5
WooCommerce: by Automattic – 3.7.0
WooSidebars: by WooCommerce – 1.4.5
YITH WooCommerce Wishlist: by YITH – 2.2.13

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: NOK (kr)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #59 - /shop/
Cart: #58 - /cart/
Checkout: #57 - /checkout/
My account: #56 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.9.0
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php


### Klarna Checkout ###

Orders created via API callback: 0% (0 of 0) of all orders paid via Klarna Checkout were created via API callback during the last month. This is a fallback order creation feature. You should aim for 0%.

### Action Scheduler ###

Complete: 18
Oldest: 2019-10-05 20:28:04 +0000
Newest: 2019-10-05 20:31:41 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by kloon** [comment]
@kalonya can you perhaps tests this with a default theme like Storefront or Twentynineteen? The reason I ask is that premium themes like Flatsome tend to have numerous custom made templates and widgets to enhance existing ones.

Action Scheduler uses the comment system to store some details as does regular WooCommerce ratings so those will likely also show up, but there are types set on those comment data which should make it not show unless the widget or template overrides this functionality.

If I test this with Twentynineteen or Storefront using the regular comments widgets from WordPress these do not show up so I am inclined to think the error lies within the theme.

**Comment by claudiosanches** [comment]
Currently Action Scheduler uses Post types and comments, so once you disable WooCommerce you probably will get some of those comments showing up, since there's code that will hide those comments on WooCommerce while you register a private post type, but since you deactivate WooCommerce, WordPress is not aware of what to do with those content that no code is registering anymore.

Note we'll update the Action Scheduler soon to custom tables (maybe in 3.9), so no more comments like that will get generated.

For now you can delete all comments of `action_log` type, so you avoid showing those comments in the front-end.
Note that it isn't a bug on WooCommerce, but how WordPress deals with orphan data.

I'll include a PR to help delete those data when you complete exclude WooCommerce from your site.

**Comment by claudiosanches** [comment]
With #24778 now it's possible to clean all Action Scheduler data when you uninstall WooCommerce, but note that this happens when you complete uninstall.

**Comment by kalonya** [comment]
@kloon There is a screenshot taken with Storefront in my comment. Also tested with Twenty-nineteen.

@claudiosanches Isn't that better to clean all those Action Scheduler data after deactivating Woocommerce? Or it may be optional. On some websites, I prefer to keep Woocommerce deactivated temporarily instead of uninstalling because I don't want to lose all settings. I'm sure many users do the same.

**Comment by claudiosanches** [comment]
@kalonya better only when deactivated, also note that another plugins may include Action Scheduler as well, so we can't just clean all after deactivated.

**Comment by sybrew** [comment]
Why was the WordPress comments-table used in the first place, only to be actively cleaned up from visibility because there's no native control?

This is completely untenable:
https://github.com/Prospress/action-scheduler/blob/347d4d9183e7916c8c12305698c713ad9951bdfc/classes/data-stores/ActionScheduler_wpCommentLogger.php#L224-L230

"Battle-Tested Background Processing"... right. I thought the folk at Automattic knew how to work with WordPress. You've lost credibility here.

**Comment by claudiosanches** [comment]
@sybrew A lot of anger coming from you, I advise you to get help, I've had this kind of problem in the past and it's something that consumed me, I recommend you get help as soon as possible.

So about the comments table, this is not really a problem for most of the cases, using the WordPress post type system there's advantages as well, not to forget that this is a 3rd party library when we included on WooCommerce, just now ProsPress is part of Automattic, and there are work to improve it as I said here already.

So please, less anger, you are talking with another human beings, with felling and all the other things that make them human.
