### ISSUE TITLE
Woocommerce -> Settings -> Emails -> New Order - Changing the email for new orders does not work even though after clicking save it confirms that your changes have been saved

### ISSUE THREAD

**Issue by mikeguy** [woocommerce/woocommerce#24774]
**Describe the bug**
Woocommerce -> Settings -> Emails -> New Order
If you try to change the email for the New Orders it does not save.
All the others do (for example I changed Failed Orders -OK and also Cancelled Orders - OK)

**To Reproduce**
1. Woocommerce
2. Settings
3. Emails
4. Change email in New Order from existing one
5. Click Save
-at this point it fails updating the email

**Screenshots**

**Expected behavior**
It should update your email accordingly when you click on Save.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
`
### WordPress Environment ###

WordPress address (URL): https://4playsports.ca/wordpress
Site address (URL): https://4playsports.ca
WC Version: 3.7.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.23
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.66.0
OpenSSL/1.0.2t

SUHOSIN Installed: –
MySQL Version: 5.7.27
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 71.54MB
Database Data Size: 67.38MB
Database Index Size: 4.16MB
wp_woocommerce_sessions: Data: 64.73MB + Index: 3.35MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta: Data: 0.04MB + Index: 0.02MB + Engine MyISAM
wp_comments: Data: 0.20MB + Index: 0.16MB + Engine MyISAM
wp_failed_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 0.82MB + Index: 0.05MB + Engine MyISAM
wp_postmeta: Data: 0.95MB + Index: 0.22MB + Engine MyISAM
wp_posts: Data: 0.57MB + Index: 0.20MB + Engine MyISAM
wp_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.02MB + Index: 0.04MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_usermeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yith_wcwl: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yith_wcwl_lists: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_yoast_seo_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_seo_meta: Data: 0.04MB + Index: 0.04MB + Engine MyISAM

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Contact Form 7: by Takayuki Miyoshi – 5.1.4
DRF Portfolio Management: by Drfuri – 1.0.1
Envato Market: by Envato – 2.0.2
Facebook for WooCommerce: by Facebook – 1.9.15 – Not tested with the active version of WooCommerce
Jetpack by WordPress.com: by Automattic – 7.8
WPBakery Page Builder: by Michael M - WPBakery.com – 6.0.2
Kirki Customizer Framework: by Ari Stathopoulos (@aristath) – 3.0.45
Mailchimp for WooCommerce: by Mailchimp – 2.2.4 – Not tested with the active version of WooCommerce
MC4WP: Mailchimp for WordPress: by ibericode – 4.5.5
Meta Box: by MetaBox.io – 5.2.1
Soo Demo Importer: by SooThemes – 1.0.1
Unero WPBakery Page Builder Addons: by DrFuri – 1.1.5
WooCommerce Variation Swatches: by ThemeAlien – 1.0.4 – Not tested with the active version of WooCommerce
Braintree For WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.0.7 – Not tested with the active version of WooCommerce

WooCommerce Admin: by WooCommerce – 0.19.0 – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.17 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.21.1 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.7.0
Yoast SEO Premium: by Team Yoast – 12.2
Yoast SEO: WooCommerce: by Team Yoast – 12.1 – Not tested with the active version of WooCommerce
YITH WooCommerce Wishlist: by YITH – 2.2.13 – Not tested with the active version of WooCommerce

### Inactive Plugins (4) ###

Akismet Anti-Spam: by Automattic – 4.1.2
Hello Dolly: by Matt Mullenweg – 1.7.2
WooCommerce Square: by WooCommerce – 2.0.4 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.2.5 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: –
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: #2470 - /term-conditions/

### Theme ###

Name: Unero
Version: 1.8.1
Author URL: http://drfuri.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: unero/woocommerce/cart/cart-shipping.php
unero/woocommerce/cart/cart-totals.php
unero/woocommerce/cart/cart.php
unero/woocommerce/cart/mini-cart.php
unero/woocommerce/checkout/form-checkout.php
unero/woocommerce/checkout/form-coupon.php
unero/woocommerce/checkout/form-login.php
unero/woocommerce/content-product.php
unero/woocommerce/content-single-product.php
unero/woocommerce/global/form-login.php
unero/woocommerce/global/quantity-input.php
unero/woocommerce/global/wrapper-end.php
unero/woocommerce/global/wrapper-start.php
unero/woocommerce/loop/add-to-cart.php
unero/woocommerce/loop/orderby.php
unero/woocommerce/loop/pagination.php
unero/woocommerce/myaccount/dashboard.php
unero/woocommerce/myaccount/form-edit-account.php
unero/woocommerce/myaccount/form-login.php
unero/woocommerce/myaccount/my-address.php
unero/woocommerce/order/form-tracking.php
unero/woocommerce/single-product/add-to-cart/grouped.php
unero/woocommerce/single-product/add-to-cart/variable.php
unero/woocommerce/single-product/meta.php
unero/woocommerce/single-product/product-image.php
unero/woocommerce/single-product/product-thumbnails.php
unero/woocommerce/single-product/rating.php
unero/woocommerce/single-product/short-description.php

### Action Scheduler ###

Complete: 687
Oldest: 2019-09-04 15:39:45 +0000
Newest: 2019-10-05 14:22:23 +0000

Pending: 1
Oldest: 2019-10-05 15:22:23 +0000
Newest: 2019-10-05 15:22:23 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by kloon** [comment]
This is a known bug on certain database setups, you can fix it by removing the emoji in the additional content section and the settings should save correctly.

A fix will be available in the next release, WooCommerce 3.8, but as mentioned above you can work around it by just removing the emoji and saving.
