### ISSUE TITLE
Make sass variables default to make them overridable!

### ISSUE THREAD

**Issue by bobmulder** [woocommerce/woocommerce#24771]
**Is your feature request related to a problem? Please describe.**

**I'm extremely frustrated when** I want to customize WooCommerce's default css.

In fact I want to override the beautiful sass variables located in `assets/css/_variables.scss` by doing this in my own `woocommerce.scss`:

```scss
@import "./modules/woocommerce-variables"; // local file
@import "../../../../plugins/woocommerce/assets/css/woocommerce.scss";
```

However, because the variables in `assets/css/_variables.scss` are not set as default it is not possible to override them!

**Describe the solution you'd like**
In `assets/css/_variables.scss`:

```scss
$woocommerce:   	#a46497;
$green:         	#7ad03a;
$red:           	#a00;
$orange:        	#ffba00;
$blue:          	#2ea2cc;

// should be replaced with

$woocommerce:   	#a46497 !default;
$green:         	#7ad03a !default;
$red:           	#a00 !default;
$orange:        	#ffba00 !default;
$blue:          	#2ea2cc !default;
```

**Additional context**
Is there anything I haven't seen why this isn't done by default by WooCommerce?

**Comment by bobmulder** [comment]
@claudiosanches what do you think about this request? Maybe I'm able to make a PR to this...

**Comment by kloon** [comment]
@bobmulder please go ahead and open a pull request and we can evaluate it there.

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24822.
