### ISSUE TITLE
Make phone numbers in emails clickable

### ISSUE THREAD

**Issue by Sophivorus** [woocommerce/woocommerce#24779]
Being able to click on the clients' phone number in the new order email would allow store admins to contact clients on the spot to fulfill a request.

WooCommerce already has a `wc_make_phone_clickable` function, but it isn't being used much. I tried to implement this feature myself using the `woocommerce_email_customer_details_fields` hook, but haven't had much luck yet, and in any case I think this enhancement would be useful for all store admins, not just me.

**Comment by Crease29** [comment]
I'd like to implement that today 🙂

**Comment by kloon** [comment]
Closing as there are open PR's for this issue. Discission can continue in the pull requests.
