### ISSUE TITLE
Weight Metadata intermittent

### ISSUE THREAD

**Issue by gsingh0317** [woocommerce/woocommerce#24788]
I'm having trouble figuring out why the weight field is intermittently showing up for some line_items on orders and not others. Is there a setting anywhere that controls this?

**Comment by kloon** [comment]
Hi @gsingh0317, we will need a bit more info on this. Could you please attach your system status report, give details on the products that are showing the weight and the ones not? Ie are they simple, variable, external products? Can you confirm you have the weight filled in for all these products?

Some screenshots will help us a lot trying to debug this.

**Comment by claudiosanches** [comment]
By default WooCommerce doesn't show up weight metadata in line_items, this sounds like that comes from another plugin.

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

Thanks!
