### ISSUE TITLE
Identity cookie is still set when making AJAX calls

### ISSUE THREAD

**Issue by mikkamp** [woocommerce/woocommerce#24792]
**Describe the bug**
According to the documentation the identity cookie tk_ai is only set for requests to the Store Dashboard, see: https://docs.woocommerce.com/document/woocommerce-cookies/#store-dashboard-wp-admin

There was a recent change which addressed this here: https://github.com/woocommerce/woocommerce/pull/23787

However the new hook `admin_init` isn't only used for dashboard requests. According to the documentation it will also be used for frontend AJAX requests, see:

- https://codex.wordpress.org/Plugin_API/Action_Reference/admin_init
- https://codex.wordpress.org/AJAX_in_Plugins#Ajax_on_the_Viewer-Facing_Side

WooCommerce itself doesn't use any of these AJAX requests on the frontend, since it has it's own endpoint for handling AJAX requests in the frontend.
However if there is any theme or plugin on the site which does an AJAX request to the URL `wp-admin/admin-ajax.php`, then the `tk_ai` cookie will still be set.

Sites are required to notify their customers about all cookies which are used on their site, so a scenario like this makes it hard to stick to the rules. This has been brought up in the following threads:

- https://wordpress.org/support/topic/woocommerce-is-not-gdpr-compliant/
- https://wordpress.org/support/topic/tk_ai-cookie-and-gdpr/

We already have code in place to not set the cookie when an API request takes place, see: https://github.com/woocommerce/woocommerce/blob/3.7.0/includes/tracks/class-wc-tracks-client.php#L66-L69
Can a condition also be included here to make sure it's not set for AJAX calls?

**To Reproduce**
1. Install a plugin/theme which does an AJAX request to the URL `wp-admin/admin-ajax.php`
2. Visit the site in an incognito browser window
3. Inspect the requests in developer tools and observe that the cookie `tk_ai` is set

**Comment by web-formation** [comment]
This has been discussed in length on the 2 forums above. By serving an undescribed tracking on EU users this action does contravene EU law and that I am sure you are aware is a risky thing to be doing.
We as users are also put in that position so I encourage you to give this priority.

Heres a couple of useful points from the discussion forums:
https://developer.wordpress.org/reference/hooks/admin_init/

kero

(@kingkero)

2 weeks, 1 day ago

Really sad that this has not yet been fixed. As a current workaround (WooCommerce 3.7.0) we use the following snippet

add_action('wp_loaded', function () {
    remove_action('admin_init', [\WC_Tracks_Client::class, 'maybe_set_identity_cookie']);
}, 999);

**Comment by web-formation** [comment]
Can you confirm the snippet above is ok to use?  and describe where to place it please?  I am not a programmer, just a user, thankyou for your attention.

**Comment by web-formation** [comment]
Heres the details from my site via google console when POST is triggered. using cloudflare and rocket as can be seen.


cache-control	
no-transform, no-cache, must-revalidate, max-age=0
cf-cache-status	
DYNAMIC
cf-ray	
5234ffa97af5a31e-HKG
content-encoding	
gzip
content-length	
21
content-type	
text/html; charset=UTF-8
date	
Thu, 10 Oct 2019 02:00:07 GMT
expect-ct	
max-age=604800, report-uri="ht….com/cdn-cgi/beacon/expect-ct"
expires	
Wed, 11 Jan 1984 05:00:00 GMT
referrer-policy	
strict-origin-when-cross-origin
server	
cloudflare
set-cookie	
**tk_ai=woo%3AhReeFi83mDMLzaIzS0LXam8x; path=/**
vary	
Accept-Encoding,Accept-Encoding
x-cf-powered-by	
WP Rocket 3.3.5.2
x-content-type-options	
nosniff
X-Firefox-Spdy	
h2
x-frame-options	
SAMEORIGIN
x-powered-by	
PHP/7.0.33
x-robots-tag	
noindex
x-turbo-charged-by	
LiteSpeed

**Comment by kloon** [comment]
Closing this issue. Can continue the discussion in the PR.
