### ISSUE TITLE
WC_Admin_Settings::get_option produce warning when fetching a multidimensional array

### ISSUE THREAD

**Issue by xristos3490** [woocommerce/woocommerce#24791]
**Describe the bug**
Under `WC_Admin_Settings::get_option` a `stripslashes` filter is applied for the returned setting value. See https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-settings.php#L190

When a **setting value is a multidimensional array** (array of arrays), the use of `array_map` with the `stripslashes` will produce a warning: 
```
PHP Warning:  stripslashes() expects parameter 1 to be string, array given in /srv/www/sites/apfs/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-settings.php on line 190
```

This came to the foreground after the WC 3.7.0 update that pre-fetches the setting value. See https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-settings.php#L238

**To Reproduce**
N/A

**Expected behavior**
The `array_map` call should use the `stripslashes_deep` instead of the simple `stripslashes`

**Comment by kloon** [comment]
Hi @xristos3490 thanks for reporting. I am going to close this issue since there is a PR open, discussion can continue in there should it need to.
