### ISSUE TITLE
gallery_thumbnail size question

### ISSUE THREAD

**Issue by seriusokhatsky** [woocommerce/woocommerce#24796]
Hello,

Could you please explain why do you use ` wc_get_image_size( 'gallery_thumbnail' )` in the file `includes/wc-template-functions.php` 

and then create a size like
 
`$thumbnail_size = apply_filters( 'woocommerce_gallery_thumbnail_size', array( $gallery_thumbnail['width'], $gallery_thumbnail['height'] ) );`

Why not simply

`$thumbnail_size = apply_filters( 'woocommerce_gallery_thumbnail_size', 'woocommerce_gallery_thumbnail' );` ?

The code is here https://github.com/woocommerce/woocommerce/blob/master/includes/wc-template-functions.php#L1458

Thank you

**Comment by kloon** [comment]
gallery_thumbnail is a WordPress specific image size that is controlled by WordPress core. We create a new one based on that which is used for displaying thumbnails underneath main product images on the single product pages, but we also wrap it around a filter so theme authors that customise the pages can define custom sizes without it affected WordPress default thumbnail sizes.

I hope that makes sense to you.

**Comment by seriusokhatsky** [comment]
@kloon thank you very much for the reply. I know that. But the question is different. I mean why you take the width and height and don't use just the size name? I can't override the "crop" parameter because of this. You don't use it and take height and width only.

**Comment by seriusokhatsky** [comment]
Hey, @kloon it seems to be a bug there, please, check.

**Comment by kloon** [comment]
Not a bug, since WC 3.3 we allow store owners to set the crop ratio via the customizer. Crop settings can, however, till be overridden via the filters https://github.com/woocommerce/woocommerce/wiki/Customizing-image-sizes-in-3.3 Just pass in the crop argument to the array.

**Comment by seriusokhatsky** [comment]
OK, thank you, but what is the purpose to use `wc_get_image_size` function here? https://github.com/woocommerce/woocommerce/blob/master/includes/wc-template-functions.php#L1458

Why not simply 

`$thumbnail_size = apply_filters( 'woocommerce_gallery_thumbnail_size', 'woocommerce_gallery_thumbnail' );`
