### ISSUE TITLE
Product sorting by post__in breaks after updating to WC 3.6.0

### ISSUE THREAD

**Issue by Uteev** [woocommerce/woocommerce#24806]
**The bug description**

When showing category products we need to list parent category products after listing current subcategory products. To achieve this task we use the filter hook woocommerce_product_query.

our function:

```php
add_filter( 'woocommerce_product_query', array($this, 'Show_Parent_Category_Products' ), 10 );

/**
	 * Lists parent category products after listing current subcategory products.
	 *
	 * This function changes the way WC retrieves subcategory products by modifying \WP_Query.
	 *
	 * @var \WP_Query $query.
	 */
	public function Show_Parent_Category_Products( $query ) {
		if( is_product_category() ) {
			$cat = get_queried_object();
			if( 0 < $cat->parent  ) {

				$parent_cat_products_ids = $this->Get_Category_Product_IDs( $cat->parent );
				$current_cat_products_ids = $this->Get_Category_Product_IDs( $cat->term_id );

				// Add the array of posts to the front of our $all_posts_ids array
				$product_ids_merged = array_merge( $current_cat_products_ids, $parent_cat_products_ids );
				// Make sure that we remove the ID's from their original positions
				$all_products_ids   = array_unique( $product_ids_merged );

				$query->set( 'post__in', $all_products_ids );
				$query->set( 'product_cat', '' );
				$query->set( 'orderby', 'post__in' );
				$query->set( 'order', 'ASC' );
			}
		}
	}
```
At 3.5.8 it works fine and shows on front first subcategory products then parent category. After updating to 3.6.0 it doesn't work anymore and there is no such sorting. 

So basicaly it used to sort according to post__in and after update it does not sort as intended.

**To Reproduce**
1. Use the code above 
2. Update from WC 3.5.8 to 3.6.0 or higher
3. Go to product category page on front
4. See there is no intended sorting

**Expected behavior**
Product sorting by post__in sorts products according to ids in post__in.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment]
There's no change in the past releases that should change the behavior of this object, you can also try `pre_get_posts` with a high priority, so you make sure that you are replacing correct after WooCommerce.
Also in my tests seems to be working just fine.
