### ISSUE TITLE
Touch devices problem: Cannot delete images in admin product gallery

### ISSUE THREAD

**Issue by mary151** [woocommerce/woocommerce#24801]
**Describe the bug**
This happens on mobile phone or touch devices in any browser. When I want to delete image from product gallery in  Woocommerce admin on the phone, there is no "x" showing, so I can't delete images. I changed admin.css to show "x" button, but it doesn’t function. 

**To Reproduce**

1.  **On phone** with Android open a browser.
2.  Go to wordpress administration page --> Products--> View All --> Edit Product
2.  View "Product Gallery". There is no "x" icon to delete images.
3.  When show "x" icon via admin.css , it doesn't function.
I added this css:
 #woocommerce-product-images .inside #product_images_container ul ul.actions {
		display:block;
}

**Comment by juliaamosova** [comment]
Thanks for reporting @mary151! 

I confirm that I can reproduce the bug on my Android device. 

I am getting an option to delete an image when hovering over it on the desktop:

![delete_image_desktop_cropped](https://user-images.githubusercontent.com/19143190/66565180-c3bbeb00-eb59-11e9-8933-56f3816f3ac5.jpg)

But the option doesn't come up on Android device:

![delete_image_mobile](https://user-images.githubusercontent.com/19143190/66564938-1cd74f00-eb59-11e9-9ddc-be14e071725f.jpg)

Option to delete an image ( `x` ) should appear either by default or when clicked on the image IMO.

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24840.
