### ISSUE TITLE
Comma in Product Attribute Term causes Variation attribute unset on csv Import

### ISSUE THREAD

**Issue by damiannep** [woocommerce/woocommerce#24800]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
1. Export a Variable product with a Product Attribute term which contains a comma
2. Import the same variable product from the exported file

**Screenshots**
Exported product on test site 1 - https://cld.wthms.co/sx9aIS
Imported product on test site 2 - https://cld.wthms.co/PLn3PA

**Expected behavior**
Expected: successful import

Actual: variation linked to product ok, but attribute terms with commas are unset on variation.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

Confirmed issue with @kloon in p1570699178052800-slack-proton.

**Comment by juliaamosova** [comment]
Thanks for reporting the issue @damiannep! I am able to reproduce it. 

Before Export / Import:

![before](https://user-images.githubusercontent.com/19143190/66652568-ef100a00-ec2d-11e9-9a76-1fdc627522b6.jpg)

After Export / Import:

![after](https://user-images.githubusercontent.com/19143190/66652579-f59e8180-ec2d-11e9-86a9-cec7edb158dc.jpg)

**Comment by juliaamosova** [comment]
It is difficult to know how many users are affected by this bug. However, I am giving it a `high` priority as if the variation has 2 colors, it is logical to use a comma between the colors to describe it and this can be a common case to use. 

I selected the next minor release milestone 3.9 as I don't think this issue has a high impact in order to include it in the fix release (such as 3.8.1).

**Comment by altnet** [comment]
Hi, I'm getting this issue as well via the standard importer. I'm surprised that it's not more widely reported. I would have thought there'd be a quite few people whose shops have broken?

**Comment by altnet** [comment]
> Hi, I'm getting this issue as well via the standard importer. I'm surprised that it's not more widely reported. I would have thought there'd be a quite few people whose shops have broken?

I take that back. To my embarrassment, have to admit my problem, at least, was actually user error (my user error!!)
