### ISSUE TITLE
Wanna add new variation via REST

### ISSUE THREAD

**Issue by Crr0pster** [woocommerce/woocommerce#24815]
I'm aware that before creating a new variation (say, "brown") for an existing product (say, 22998), "brown" must exist in the product's attributes within the relevant attribute (say, "color"). To achieve this, I PUT https://<URL>/wp-json/wc/v3/products/22998
with the body
{
  "attributes": [
		{
          "id": "62",
          "visible": true,
          "variation": true,
          "options": ["brown"]
		}
  ]
}
After this, "brown" is added, but all color attributes which had existed before are gone (and therefore, all existing variations). Only "brown" remains. I don't seem to be able to just *add* "brown" to the list of available colors. I would need a parameter for "options" like mode: "add" or something like this. 

Thanks.

Regards, Michael

**Comment by kloon** [comment]
@Crr0pster when you are updating a product's attributes you need to specify all the attributes in the update request as it overwrites the existing ones with the new ones. The API does not just add to the existing attributes when you do an update request, believe all API's work this way.
