### ISSUE TITLE
I had approx 1600 + products but on category page per products are not showing fully.

### ISSUE THREAD

**Issue by khmubashar** [woocommerce/woocommerce#24827]
I am using latest version of wordpress and woocommerce using openlightspeed server. I have more than 1600 products but on home page or in category pages i setup 5 columns and per page 15 products show on every category 1st pagination page. But when i open category page it show only one product on 1st page, and 2nd product on 2nd page. 
I troubleshoot theme by changing theme, i disable all plugins. i restart my server and cache. but still its issue persist. for your reference i am sharing category pages. 
http://165.227.182.100/product-category/1004gourmet/special-deals/on-sale/
As well as check home page where i setup 3 product columns in 2 rows. and one slide list product category but its not showing.

**Comment by rodrigoprimo** [comment]
Hi there!

GitHub is for reporting bugs and issues specific to the WooCommerce plugin. This is not a support portal. For support, you could try the support forums https://wordpress.org/support/plugin/woocommerce. If you are a paying WooCommerce.com customer, you could contact their support as well: http://woocommerce.com/contact-us/
