### ISSUE TITLE
wc_kses_notice Filter

### ISSUE THREAD

**Issue by allanemerson** [woocommerce/woocommerce#24839]
**Is your feature request related to a problem? Please describe.**
If you wanted to include an inline svg in a given notice, you have no way to whitelist it in wc_kses_notice(). This is problematic because wc_kses_notice() is called both in the notice template on $message, but then also called again in wc_print_notices on the ob_get_clean() output. So, even if you overwrite the template to remove the kses on $message, print_notices will still strip svgs. 

**Describe the solution you'd like**
Add a filter for 'wc_kses_notice_allowed_tags', or something similar, so we can update the array passed into wp_kses() on line 220 of wc-notice-functions.php

**Describe alternatives you've considered**
The current workaround will be to inject the svgs into the notice elements with javascript, but this isn't ideal in scenarios with ajax could be in play, since we'd need to watch for events/DOM changes, etc. Ideally, we can just have the elements we choose outputted to the page server side.

**Additional context**
Putting a filter on this array, https://ep.d.pr/RnmnaY, would allow developers to whitelist markup as needed.

**Comment by claudiosanches** [comment]
Thank you for suggesting this feature!

I'm closing the issue as it already has a PR, please continue the discussion over at #24849.
