### ISSUE TITLE
wc-country-select unnecessarily requires selectWoo

### ISSUE THREAD

**Issue by clifgriffin** [woocommerce/woocommerce#24838]
**Describe the bug**
In 3.8 beta 1, this commit was added:
https://github.com/woocommerce/woocommerce/commit/d1236021bb873066c4526a9295db5175221c23ba

This doesn't seem to be necessary as wc-country-select still has protective conditionals to detect whether selectWoo is available. 

Workaround:
```php
global $wp_scripts;
$wp_scripts->registered['wc-country-select']->deps = array( 'jquery' );
```

**To Reproduce**
1. Disable selectWoo:
```php
wp_dequeue_script( 'selectWoo');
wp_deregister_script('selectWoo');
```
2. Go to checkout. 
3. wc-country-select and wc-address-i18n are not loaded.

**Expected behavior**
WooCommerce scripts should not require selectWoo as a dependency.

**Comment by claudiosanches** [comment]
You are right, should be optional to load SelectWoo if you want to remnove from the frontend.

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24848.
