### ISSUE TITLE
Remove call to func_get_args() in WC_Order_Factory

### ISSUE THREAD

**Issue by JacobMC** [woocommerce/woocommerce#24841]
**Is your feature request related to a problem? Please describe.**
There is a call to `func_get_args()` in `WC_Order_Factory::get_order()` that is causing a PHP 7.0 error notification in phpcs.

The feedback from phpcs is as follows:
```
FILE: woocommerce/includes/class-wc-order-factory.php
-----------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------
LINE 49: ERROR Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter "$order_id" was changed on line 25. (PHPCompatibility.FunctionUse.ArgumentFunctionsReportCurrentValue.Changed)
```

**Describe the solution you'd like**
I would like for the call to `func_get_args()` to be removed. I can and am willing to submit a PR to fix this issue.

**Describe alternatives you've considered**
The only alternative I've been able to come up with is manually updating that file each time there is a WooCommerce update, either with a fix or an ignore comment for phpcs. Which is what I've done for a few of our clients.

**Comment by claudiosanches** [comment]
Please, a PR should be appreciated, thanks!

**Comment by JacobMC** [comment]
@claudiosanches Awesome! I'll get that in today.

**Comment by claudiosanches** [comment]
But note that the function is called just for developer use throwing an warning about.

**Comment by JacobMC** [comment]
Right, the only reason it has been an issue for my team is that the error stops our CI/CD flow. In all honesty that's also the only reason that I found it in the first place.

**Comment by rodrigoprimo** [comment]
Closing as there is already a PR to address this issue.
