### ISSUE TITLE
I can't use coupons on checkout

### ISSUE THREAD

**Issue by zJar84** [woocommerce/woocommerce#24858]
I'm using Storefront theme, without child themes and I've deactivated all plugins except WooCommerce and tried to use the coupon and it didn't work.

I didn't configured yet the payment methods, but I enable PayPal in SandBox mode and it still not working.

I've used this code on `functions.php` file:
`remove_action( 'woocommerce_before_checkout_form', 'woocommerce_checkout_coupon_form', 10 );
add_action( 'woocommerce_review_order_before_payment', 'woocommerce_checkout_coupon_form' );`

Regards.

**Comment by claudiosanches** [comment]
Hi there. GitHub is primarily for reporting bugs and is not a support forum. We don’t support custom development here. You could ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce
Also where you are trying to include this form will trigger the "place order" button, so need to fix the effect before using.
