### ISSUE TITLE
php 7.4 warning.

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#24854]
/var/docs/wptheme.tst/public/wp-content/plugins/woocommerce/includes/class-woocommerce.php on line 202, PHP Notice:  Trying to access array offset on value of type null in 

not checking for isset of $type !  I think code should be like this

`if` ( isset ($error['type']) && in_array( $error['type'], array( E_ERROR, E_PARSE, E_COMPILE_ERROR, E_USER_ERROR, E_RECOVERABLE_ERROR ), true ) ) `{`

**Comment by BackuPs** [comment]
![afbeelding](https://user-images.githubusercontent.com/6078370/67006367-4528f580-f0e5-11e9-8de7-86d8213a4286.png)

**Comment by claudiosanches** [comment]
Already fixed for WooCommerce 3.8 by #24442
