### ISSUE TITLE
Hold-Stock enhancement to support business days

### ISSUE THREAD

**Issue by vinigarcia87** [woocommerce/woocommerce#24850]
In Brazil, we have a very common payment method, called [Boleto Bancario](https://www.pagbrasil.com/payment-methods/boleto-bancario/).
Generally, boletos are confirmed with a delay of two to three business days.
When a customer try to buy some product using this method, we need to hold the product stock for some time, to make sure he will pay the boleto. The problem here is that we should hold for two to three _business days_.
So, the way woocommerce_hold_stock_minutes not really works well in this case. We sometimes have holidays that make the waiting longer than three days...
Having a really high number of minutes don`t work either because we may be holding a important item in stock for too long (thinking on products with low stock amount, this means to lose a significant amount of sales).

What would be nice to have, is better options for hold-stock, like, in my example, hold-stock for `x` business days. Also, will be very nice if we could hook this functionality to program any rule we want.

I have been looking for this for quite some time, never found many information about this functionality.

Also, since this is a problem I facing right now, someone can help me on having a solution for such a problem? Any hook I may use maybe? Any help you could give me would be nice.

**Comment by claudiosanches** [comment]
It's possible to customize the behavior and avoid canceling orders using `woocommerce_cancel_unpaid_order` filter, so this way you can cancel orders based on your payment gateway settings.

**Comment by vinigarcia87** [comment]
> It's possible to customize the behavior and avoid canceling orders using `woocommerce_cancel_unpaid_order` filter, so this way you can cancel orders based on your payment gateway settings.

Thanks for the tip! Gonna try it
