### ISSUE TITLE
Schema error: Either “offers”, “review”, or “aggregateRating” should be specified error

### ISSUE THREAD

**Issue by morganhvidt** [woocommerce/woocommerce#24862]
**Describe the bug**
Looks like the Schema bug is back in WC 3.7.1.
`"Either “offers”, “review”, or “aggregateRating” should be specified error"`

Multiple people are reporting the errors today:
https://wordpress.org/support/topic/either-offers-review-or-aggregaterating-should-be-specified-error-5/

**Comment by dademaru** [comment]
The issue is on `WC_Structured_Data::generate_review_data()` [$markup['itemReviewed']](https://github.com/woocommerce/woocommerce/blob/bccb7c3283babca29153964181194d970250f529/includes/class-wc-structured-data.php#L340)

'itemReviewed' has been added in [WC 3.0.3](https://github.com/woocommerce/woocommerce/blob/304b07d8558d3769418670837e6094dbd0097360/CHANGELOG.txt#L1615), but now seems that Google requires **either “offers”, “review”, or “aggregateRating”.**

While Product structured data is **missing field 'review'** (optional).

I think that Review structured data could be a subset for Product structured data (see Schema.org Review [Example 2 JSON-LD](https://schema.org/Review#eg-10)) and 'itemReviewed' could be omitted (same example).

**Comment by claudiosanches** [comment]
>  "Either “offers”, “review”, or “aggregateRating” should be specified error"

This one is easy to fix, you just need to receive a review, so `review` and `aggregateRating` will got generated.

**Comment by dademaru** [comment]
@claudiosanches 
as reported by **Sn00z389** (@webmakers2011) in [linked topic](https://wordpress.org/support/topic/either-offers-review-or-aggregaterating-should-be-specified-error-5/),
this error is due to the new **Google update of Rich Snippets**:

> October 16, 2019 onward
> Product
> Search Console improved its error detection pipeline for Product structured data. Product items are now validated wherever they occur in a structured data tree rather than just at the top level. This may cause errors or warnings to appear on pages that were previously shown as valid.

But in `WC_Structured_Data::generate_review_data() -> $markup['itemReviewed']` the `'@type' => 'Product'` miss one of the (now) required props: “offers”, “review”, or “aggregateRating”.

As far as I'm concerned embedding Review structured data in Product structured data could be the solution.

**Comment by claudiosanches** [comment]
@dademaru still it's possible to render `offers` or `aggregateRating`, if your product have an offer or some review, and then this error will got solved.
Also there's already a Pull Request to include `review`: https://github.com/woocommerce/woocommerce/pull/24278

But again, note that if you product doesn't have any offer or review, those errors will keep showing.

**Comment by galapogos01** [comment]
@claudiosanches why was this closed?  The schema errors are happening for products with valid offers.

**Comment by bongoz1981** [comment]
Yes i still have the problem. I fixed error with @dademaru fix. But the problem was not solved entirely: i still have review not inside product with many warnings

**Comment by bongoz1981** [comment]
> @claudiosanches
> as reported by **Sn00z389** (@webmakers2011) in [linked topic](https://wordpress.org/support/topic/either-offers-review-or-aggregaterating-should-be-specified-error-5/),
> this error is due to the new **Google update of Rich Snippets**:
> 
> > October 16, 2019 onward
> > Product
> > Search Console improved its error detection pipeline for Product structured data. Product items are now validated wherever they occur in a structured data tree rather than just at the top level. This may cause errors or warnings to appear on pages that were previously shown as valid.
> 
> But in `WC_Structured_Data::generate_review_data() -> $markup['itemReviewed']` the `'@type' => 'Product'` miss one of the (now) required props: “offers”, “review”, or “aggregateRating”.
> 
> As far as I'm concerned embedding Review structured data in Product structured data could be the solution.

Hai trovato una soluzione?

**Comment by dademaru** [comment]
@claudiosanches 
> @dademaru still it's possible to render `offers` or `aggregateRating`, if your product have an offer or some review, and then this error will got solved.
This in not true… I've tried to explain why, also reporting Sn00z389 (@webmakers2011) comment.
The current issue is related to `'itemReviewed'`.
Until 'Review' is included in Product structured data, the issue will not be fully resolved.
Only by including it Google will stop requesting 'offers' (or other props) for the Product within 'itemReviewed'.
> Also there's already a Pull Request to include `review`: #24278
I missed it, this would fix the issue.
> But again, note that if you product doesn't have any offer or review, those errors will keep showing.
Of course

**Comment by galapogos01** [comment]
> > Also there's already a Pull Request to include `review`: #24278
> 
> I missed it, this would fix the issue.

This pull request does not fix the issue. It was created before the latest change in Google validation rules.

**Comment by Sn00z389** [comment]
Hi all, yes this is not a good fix for that... For many years Woocommerce fails to make good rich snippets and I think it should be a top priority, since we do not have our reviews in Google anymore.

Also, we have never got the price and the stock status in Google either, so this is a must for next version of WC.

All of the rich snippets must pass validation on GSC and this must be a top priority these days.

**Comment by madeincosmos** [comment]
I can still reproduce the problem with WooCommerce version 3.8.0-rc1 and a product with valid reviews. Reopening so that we can double check this.

**Comment by galapogos01** [comment]
> I can still reproduce the problem with WooCommerce version 3.8.0-rc1 and a product with valid reviews. Reopening so that we can double check this.

Whether there are reviews or not the item should have no Errors.

Items with no reviews should show a Warning in the structured data tool only.

**Comment by rwaynick** [comment]
Also reported in 16058308-hc for a product that has two valid reviews. I could reproduce on 3.7.1.

**Comment by claudiosanches** [comment]
@galapogos01 
> Items with no reviews should show a Warning in the structured data tool only.

The Google message is `"Either “offers”, “review”, or “aggregateRating” should be specified error"`, if you have a solution, please submit a Pull Request.

**Comment by claudiosanches** [comment]
Solved this in #24278 (PR updated excluding itemReviewed since is already nested to Product schema).

**Comment by claudiosanches** [comment]
@galapogos01 

> edit: testing against your pull request, it moves the error from Review to Product, which is worse!

In fact is best nesting with Product schema, but we don't need `itemReviewed` anymore, each as causing the errors!

**Comment by drnick2** [comment]
So what is the solution to this problem? Each day I am receiving more errors on Google Search Console.

**Comment by TimTank** [comment]
So what is the solution to this problem? Each day more errors and dropping in google

**Comment by drnick2** [comment]
I hope we do not have to go to that extreme as this issue should be able to corrected, it was not a problem until one of the last updates.

**Comment by claudiosanches** [comment]
@drnick2 @TimTank the solution is the code in #24278
Probably will get into the next release of WooCommerce, after 3.8 is released.

**Comment by or128** [comment]
Why is this cosed? this issue was not solved.

**Comment by drnick2** [comment]
I hope it is not closed as I have over 40 errors (Either "offers", "review", or "aggregateRating" should be specified) and it has affected my serp ranking, so a fix is in order.

**Comment by dademaru** [comment]
@drnick2 
since 'Review' is embed in 'Product' structured data as of WC 3.8.0, try this quick fix waiting #24278 - to completely remove separate 'Review' structured data and prevent Google warnings / errors.
```add_filter( 'woocommerce_structured_data_review', '__return_false'  );```
Hope it helps ;-)

**Comment by drnick2** [comment]
@dademaru  Thanks for the the info, will give it a try.

**Comment by drnick2** [comment]
Does anyone know if this fix is in Woocommerce 3.8? I just received an email that it is live.

**Comment by claudiosanches** [comment]
Not yet on 3.8, will be on the next release.

**Comment by mrkapable007** [comment]
Anyone have a solution for this yet?

**Comment by drnick2** [comment]
@mrkapable007  I heard the fix is in the next Woocommerce release, just do not know when that will be.

**Comment by mrkapable007** [comment]
> 
> 
> @mrkapable007 I heard the fix is in the next Woocommerce release, just do not know when that will be.

well, hoping this gets fixed pretty fast. Thanks for the reply.

**Comment by morganhvidt** [comment]
I've just updated to the released WooCommerce 3.8.1. 
I can confirm the update fixed the schema error 😄

**Comment by PymatFlow** [comment]
Hi I am using WooCommerce 3.8.1, but I have the same issue

**Comment by fliix-de** [comment]
Same issue here on our site. WooCommerce 3.8.1

Fix "add_filter( 'woocommerce_structured_data_review', '__return_false' );" doesn't work for us.

https://search.google.com/structured-data/testing-tool/ still shows Review Errors. One per comment.

**Comment by Mic2005** [comment]
I still have 85 products with this "Either “offers”, “review”, or “aggregateRating” should be specified error" warning. Does anyone know how to fix this?
