### ISSUE TITLE
Can't set shipping at £9.99 including 20% VAT

### ISSUE THREAD

**Issue by raymondgillespie** [woocommerce/woocommerce#24873]
**Describe the bug**
I would like to set a shipping value of £9.99. VAT is enabled on all products and shipping at 20%. WooCommerce is set to have all prices entered inclusive of VAT, but this only applies to products, so shipping options with VAT need to be entered exclusive of VAT. If I enter the ex. VAT price of £8.325 or £8.33, the shipping cost is calculated to be £10. If I enter £8.32 the shipping cost is calculated as £9.98.

**To Reproduce**
1) Set tax to 20% across all products and shipping.
2) Create a flat-rate shipping option.
3) Enter price of £8.32, £8.325 or £8.33. 
4) There is no way to get this to calculate the shipping at £9.99

**Screenshots**
![2](https://user-images.githubusercontent.com/25502129/67159527-b236c800-f33d-11e9-94e0-2e61d004fd26.png)
![1](https://user-images.githubusercontent.com/25502129/67159528-b236c800-f33d-11e9-948f-599e0e42bf4c.jpg)

**Expected behavior**
There should be a way to create a shipping item for £9.99.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by uok** [comment]
you can try to enter `9.99 / 1.2`

**Comment by raymondgillespie** [comment]
It's a bit of a workaround, but I will give it a go - thanks!

**Comment by juliaamosova** [comment]
Thank you for reporting the issue @raymondgillespie. There is a broader issue in place related to how rounding is done in WooCommerce. See more details in https://github.com/woocommerce/woocommerce/issues/24975. As mentioned in that issue, we will start working on addressing it soon.

**Comment by juliaamosova** [comment]
@raymondgillespie we are closing issue in favor of https://github.com/woocommerce/woocommerce/issues/24975 - please continue to discuss and comment there.
