### ISSUE TITLE
#23093 - Enhancement – Move tax classes from WordPress Options to a new wc_tax_rate_class

### ISSUE THREAD

**Issue by joergschwirz** [woocommerce/woocommerce#24882]
Hi,

with the following update we have lost the tax classes assignment to the products:

3.7.0 – 2019-08-12
Enhancement – Move tax classes from WordPress Options to a new wc_tax_rate_classes table. #23093

What was happen:

Woocommerce has created a new database table where the tax classes now be placed. The tax classes received different slug names then before.

We have only evalutated the german version.
Before the update the slugname of the reduced rate was: “ermaessigter-steuersatz” the display text “Ermässigter Steuersatz” – the wording was also correct.

After the update the reduced rate was named: “reduzierter-preis” the display text “Reduzierter Preis” – this german wording is NONSENSE.

the translation to english is “Redudced price" – in real the meaning is “reduced tax rate” – who has defined this bad translation 😉 the same is nonsense has happen with the zero rate - translated to "0-Preis" -> translated to english: zero-Price ;-)

The really bad point is: at all our products the tax class was set to the slugname “ermaessigter-steuersatz” and the new tax class definition was set to “reduzierter-preis” – in that case all products lost there tax assignment.

We have updates the orducts with the new slugname and everything is fine now.

Why slup names are not language independent?

I hope the information could help others.

Joerg

**Comment by claudiosanches** [comment]
> the translation to english is “Redudced price" – in real the meaning is “reduced tax rate” – who has defined this bad translation wink the same is nonsense has happen with the zero rate - translated to "0-Preis" -> translated to english: zero-Price ;-)

This sounds like you have to proper translate it on https://translate.wordpress.org/locale/de/default/wp-plugins/woocommerce/

Probably better talk with the German community of translators, so they can proper fix it, since it's a translation issue.

> Why slup names are not language independent?

Because before we had no proper slug, only the text in that input, slugs is something new on this new table, that's the reason that the translation need to be fixed on your side.
