### ISSUE TITLE
[3.8] Cart Display Inconsistencies with Global Attributes 

### ISSUE THREAD

**Issue by ldr2273** [woocommerce/woocommerce#24880]
**Describe the bug**
When adding a variable product to cart with Global Attributes used of `Any X`, it displays differently in the cart than when the Global Attribute is defined in the product data box. Kinda confusing to explain, so I'll post screenshots of what I mean. Also, I don't know whether this is truly a bug or an enhancement request, so please update the labels on this as you see fit.

**To Reproduce**
1. Add a Global Attribute- let's say `Shape`, for example. 
2. Create a Variable Product and add a couple of variations using this Global Attribute `Shape`:

**Define one of the shapes while leaving the other as `Any Shape`.**

![Variables](https://cloudup.com/cCJLS02RUV4+)
Full Size Link: https://cloudup.com/cCJLS02RUV4

3. Publish variable product. 
4. Navigate to front end of the site, and add both variables to cart, one with the defined shape, and one that's set to `Any Shape`. 
5. When viewing the cart, the variations display differently and is inconsistent and confusing:

![Cart](https://cloudup.com/cYFi2pZWMcM+)
Full Size Link: https://cloudup.com/cYFi2pZWMcM

On a customer's site I was testing with a third-party theme, it displayed as such:

![Astra theme](https://cloudup.com/crao1YFvbwW+)
Full Size Link: https://cloudup.com/crao1YFvbwW

This is confusing, and while it doesn't necessarily break anything, it's inconsistent and might raise questions. 

In WC 3.7.1, this behavior is consistent. Here's the view in Storefront theme, no matter how you select the variation:

![Storefront](https://cloudup.com/ciU80Yqv4Tv+)
Full Size Link: https://cloudup.com/ciU80Yqv4Tv

Consistent in Twenty Nineteen as well.

I'm not sure if this was intended or not, so I've also marked this issue as a question.

**Comment by vedanshujain** [comment]
@ldr2273 I can see this in 3.7.1 as well. This was added to modify the product link in the cart so that you click on it also auto-selects the variation from the drop-down boxes on the product page when all variations are defined. 

From the code I don't see any option to disable this behavior though.

**Comment by vedanshujain** [comment]
Can you comment what are variable product settings in 3.7 in the last screenshot when you were not able to see the links?

**Comment by claudiosanches** [comment]
This isn't a bug on 3.8, also we made it by default to just include in the attribute name in case of global attributes, we included this change since WooCommerce 3.0.
Also themes may change it as they like.

**Comment by claudiosanches** [comment]
This is how works, if have more than 3 attributes, will list then all:

https://github.com/woocommerce/woocommerce/blob/01f5a09d2746a1f559f544a1c9ed0bccc21a6b65/includes/data-stores/class-wc-product-variation-data-store-cpt.php#L285-L308

Also possible to change it by the filters.

**Comment by pacmanito** [comment]
5 years have passed. To me it still seems like a bug leading to inconsistent product title styling. I spent a lot of time digging the issue until I found this topic. Better implementation is possible. Or at least there should be some documentation.
