### ISSUE TITLE
wc_get_customer_default_location unexpected return value

### ISSUE THREAD

**Issue by srjwebster** [woocommerce/woocommerce#24881]
**Describe the bug**
When accessing a site as a non-logged in user from a country that is NOT in the get_allowed_countries() array, the session country, billing_country, and shipping_country as all set as the value of the first allowed country, rather than the key. 

Issue occurs on line 1138 of wc-core-functions.php @version 3.3.0 when using current( $allowed_country_codes ) rather than something like array_key_first( $allowed_country_codes )

**To Reproduce**
1. Visit a site from a country that is not in the allowed countries list.
2. Attempt to use the WC()->Customer->get_billing_country() method
3. Find that instead of the usually reliable 2 letter ISO code you have been returned the actual name
4. Have to work around and access the i18n table and do a costly array traversal to find the key of the value. 

**Expected behavior**
WC()->Customer->get_billing_country always returns a 2 digit code across all other uses, I don't know if this change would have unintended consequences down the line, but it feels better to fix those and have a method with a reliable return value.

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24884.
