### ISSUE TITLE
Edit E-Mail Template

### ISSUE THREAD

**Issue by ks-maja** [woocommerce/woocommerce#24889]
After the new update 3.7.1 im missing the button for changing E-Mail templates.

![image](https://user-images.githubusercontent.com/56954783/67465123-e0b9e900-f644-11e9-8fc8-9a3a43593d07.png)

**Comment by claudiosanches** [comment]
Hi there, thanks for posting. I wasn’t able to replicate this issue with the details you submitted. I tried follow the steps you provided and it appeared to work correctly.

It could be that you don't have permissions to edit any template, or the templates are missing, or even you had some kind of connection error and it's missing the templates. Also note that we haven't did any change to email templates on 3.7.1, so no reason for this version break those templates.

Please post back if you can provide more details on how to reproduce this issue. For now, I’m am closing this as non-reproducable.

Thanks!

**Comment by claudiosanches** [comment]
Also note that this issue is missing several information from the bug template, you complete removed all the content, so no way to further debug it.
