### ISSUE TITLE
PayPal Instant Payment Notifications (IPN) - Issues with payments

### ISSUE THREAD

**Issue by smombiegate** [woocommerce/woocommerce#24890]
Hi

We are emailed this:

"Please check your server that handles PayPal Instant Payment Notifications (IPN). Instant Payment Notifications sent to the following URL(s) are failing:

https://www.saveusnow.org.uk/wc-api/WC_Gateway_Paypal/

If you do not recognize this URL, you may be using a service provider that is using IPN on your behalf. Please contact your service provider with the above information. If this problem continues, IPNs may be disabled for your account."

My server company says this is logged:

"The server should support this however the plug-in looks to be producing errors, I found bellow in the logs.

[23-Oct-2019 12:20:05 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function hforce_create_renewal_order() in /home/saveusmark/public_html/wp-content/plugins/xa-woocommerce-subscriptions/includes/hf-includes/class-hf-paypal-standard-ipn-handler.php:222
Stack trace:
#0 /home/saveusmark/public_html/wp-content/plugins/xa-woocommerce-subscriptions/includes/hf-includes/class-hf-paypal-standard-ipn-handler.php(35): HF_Subscription_PayPal_Standard_IPN_Handler->process_ipn_request(Array)
#1 /home/saveusmark/public_html/wp-content/plugins/xa-woocommerce-subscriptions/includes/class-subscription-paypal.php(242): HF_Subscription_PayPal_Standard_IPN_Handler->valid_response(Array)
#2 /home/saveusmark/public_html/wp-includes/class-wp-hook.php(286): HF_Subscription_Paypal::process_ipn_request(Array)
#3 /home/saveusmark/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#4 /home/saveusmark/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#5 /home/saveusmark/public_html/wp-content/plugins/woocommerce/includes/g in /home/saveusmark/public_html/wp-content/plugins/xa-woocommerce-subscriptions/includes/hf-includes/class-hf-paypal-standard-ipn-handler.php on line 222"

Can you help please?

**Comment by dougaitken** [comment]
Hi @smombiegate 

Looking at that PHP Fatal Error log, I see it referring to `xa-woocommerce-subscriptions` - we don't offer support for third-party plugins so I'd recommend reaching out to the developers of that  plugin.

Thanks,
