### ISSUE TITLE
get_variation_attributes gets all attributes, also the deleted ones..

### ISSUE THREAD

**Issue by striderxfossility** [woocommerce/woocommerce#24896]
Simple function:

global $product;
$attributes = $product->get_variation_attributes();

It returns all the attributes ever maded. also the ones you deleted. Is there an other way? cant find it anywhere.

After this function I have:
$attArray = array();

foreach ($attributes['pa_afmeting'] as $value) {
array_push($attArray, (array) get_term_by('slug', $value, 'pa_afmeting' ));
}

**Comment by claudiosanches** [comment]
Hi there. GitHub is primarily for reporting bugs and is not a support forum. We don’t support custom development here. You could ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce
