### ISSUE TITLE
get_variation_attributes gets all variations, also the deleted ones..

### ISSUE THREAD

**Issue by striderxfossility** [woocommerce/woocommerce#24891]
Simple function:

global $product;
$attributes = $product->get_variation_attributes();

It returns all the variations ever maded. also the ones you deleted. Is there an other way? cant find it anywhere.

After this function I have:
$attArray = array();

foreach ($attributes['pa_afmeting'] as $value) {
        array_push($attArray, (array) get_term_by('slug',  $value, 'pa_afmeting' ));
}

**Comment by claudiosanches** [comment]
It's missing several information on this bug report, also `$product->get_variation_attributes()` returns attributes and not variations.
Sounds like you are using this method incorrectly.

Also note that GitHub is primarily for reporting bugs and is not a support forum. We don’t support custom development here. You could ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce

**Comment by striderxfossility** [comment]
Then i meant Attributes, it get all of them including the removed ones?? why are you closing this.
