### ISSUE TITLE
Product meta filters

### ISSUE THREAD

**Issue by Stas0238** [woocommerce/woocommerce#24904]
**Describe the solution you'd like**
I looked up and didn't find how to disable categories and tags on single product ( I dont want to do it with css, just don't want to show it from code ). You have filter in the same file for sku ( which is great for some reasons ), and can you please add same filters for categories and tags to make them disable via filter ?

single-product/meta.php

**Comment by claudiosanches** [comment]
Hi there. GitHub is primarily for reporting bugs and is not a support forum. We don’t support custom development here. You could ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce

**Comment by jobthomas** [comment]
@claudiosanches I don't think this is as much a support request as it is a feature request. I don't think these filters exist yet and this user is asking if we'd consider bringing them in.

**Comment by thomas-zg** [comment]
Why not customizing the template and copying it to yourtheme/woocommerce/single-product/meta.php?

**Comment by Stas0238** [comment]
@thomas-zg 
I don't want to update my project every time this file's version changes (I am trying to use only filters to make my theme/woocoomerce as clean as I can, you should understand that)

WooCommerce already has filter for show/hide sku which is made with function https://prnt.sc/pow62h
I asked you to add something like on next screenshot – https://prnt.sc/pow7c1 or https://prnt.sc/pow7m0

They won't be affected badly on speed or any other case but will give such good opotunity to disable those meta by coding

**Comment by jobthomas** [comment]
In all fairness @Stas0238 templated updates aren't that frequent on one hand, and they also aren't often very substantial (rather more than just tweaks).

**Comment by kmanijak** [comment]
This issue is pretty old and since then, the templates have been blockified. With the current WooCommerce you can edit the templates (including Single Product template) adjusting it to your needs.

In the meantime I'll go ahead and close this issue to keep the backlog clean, however, please note the closed issues can be still commented on! 🙌
