### ISSUE TITLE
delete external images- wordpress media 

### ISSUE THREAD

**Issue by loaishar** [woocommerce/woocommerce#24905]
I have deleted all my products via SQL code.
and all my products have deleted successfully, but the images of the products still show in the media in my WordPress.
ind this images are external images.
I have a huge number of external images and I can not delete it manually.
so anybody knows how to delete them once?
maybe via A SQL code or aby method else?

**Comment by claudiosanches** [comment]
Hi there. GitHub is primarily for reporting bugs and is not a support forum. We don’t support custom development here. You could ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce
