### ISSUE TITLE
WC Tracker not including processing orders

### ISSUE THREAD

**Issue by james-allan** [woocommerce/woocommerce#24916]
**Describe the bug**
When I was comparing the data returned by [`WC_Tracker::get_order_totals()`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-tracker.php#L512-L534) with what I can see on the front end I noticed the WC tracked data doesn't include processing orders. It only includes orders which are completed or refunded. 

See this line: https://github.com/woocommerce/woocommerce/blame/master/includes/class-wc-tracker.php#L522

Are orders which are processing excluded from the totals on purpose or is this a bug?

Before it was updated to a raw database query (in https://github.com/woocommerce/woocommerce/commit/db57a67fde1af317383efc0134869feb9c1ba746), it use to include statuses returned by `wc_get_is_paid_statuses()` which would have included processing orders.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by kloon** [comment]
Closing, we can continue the discussion in p6q8Tx-1gP-p2
