### ISSUE TITLE
Checkout Not Showing the right

### ISSUE THREAD

**Issue by JohanVer5054** [woocommerce/woocommerce#24917]
Hey so in the checkout the billing and shipping were setups end working and now it's showing all the text inputs as WoCommerce Checkout Manager and on the backend, it's showing its setup username and so on can you please let me know how I can fix this.

**Comment by kloon** [comment]
Hi @JohanVer5054, this sounds like a plugin or theme conflict. Can you please test with all plugins disabled except WooCommerce and your theme switched to a default one like Twentyseventeen.

You can contact your theme author or the plugin author for assistance in debugging but we use this issue tracker only for reporting issues with WooCommerce core and not plugins and themes.
