### ISSUE TITLE
Shop page in multisite allways shows products never categories

### ISSUE THREAD

**Issue by androos** [woocommerce/woocommerce#24938]
Have a multi site with multiple subdomains
on all subdomains there is no way to change the look of the default shop page, it always show products never categories. Customizer settings have no effect. 
Default Domain works as expected.

**Comment by androos** [comment]
Any suggestions?
I have tested this with all plugins deactivated and with standard theme. 
I cloud replicate it on a test site.

**Comment by juliaamosova** [comment]
Hi @androos,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report bugs only. 

The type of issue you submitted looks like `support request` which may or may not reveal a bug once proper troubleshooting is done.

Regarding your question:

WooCommerce is multisite compatible. This means, when you install and activate the WooCommerce plugin, it will be activated on all sites, and there will be an option to create a store, set up products for each site on the multisite but **individually**. Each store will be independent of the other.

So, say I have 3 sites in a multisite- Site One, Site Two and Site Three (with Site One being the main site). When I install and activate WooCommerce on Site One, it will be activated on Site Two and Site Three as well. However, when I add products on Site One, or update some settings the changes will not be reflected on Site Two or Site Three, by default. You'd need to add products and update settings on each site individually. 

Let me know if it helps or if I am missing something.

**Comment by androos** [comment]
Sry, I must be terrible at describing things in English. 
What I was trying to explain is a problem with the look the main shop page.
As you know you can customize the look of this page in wordpress customizer. 
Go to Appearance -> Customize. Then: WooCommerce -> Product Catalog.
You can choose there: 
"Shop page display
Choose what to display on the main shop page.
* Show Products
* Show Categories
* show Categories & Products"

It doesn't matter what it is set to, it always shows the page like I had set it to: 
"Show Products"
That happens on all subdomains!
But not on the default domain. On the main domain this works normal. 
"
I have no other explanation for this as that this must be a bug.

**Comment by androos** [comment]
So I could recreate this? Any conformation?

**Comment by androos** [comment]
Steps to reproduce:
Have an normal worpress installation
Convert the wordpress installation in to an multi site with subdomains
Activate Woocommerce network wide
Have products with categories in all subdomains

**Comment by androos** [comment]
The last status for this issue was "needs feedback". I gave some feedback. But no change since 2 months?
