### ISSUE TITLE
Payment Race Condition

### ISSUE THREAD

**Issue by cblach** [woocommerce/woocommerce#24936]
I'm the developer of a payment gateway module. As many other payment modules, I use callbacks (from the payment gateway) to register when the payment is completed and call $order->payment_complete($transactionid) when the callback is received.

The problem, however, is that woocommerce cannot handle when the callback comes at the same time as the customer is sent back to order_received_url. The order_received_url invokes the following function in woocommerce https://github.com/woocommerce/woocommerce/blob/master/includes/shortcodes/class-wc-shortcode-checkout.php#L222 .
In this function it modifies the order and saves it with an IP-address https://github.com/woocommerce/woocommerce/blob/master/includes/shortcodes/class-wc-shortcode-checkout.php#L242 .
If this code is run approximately at the same time as the payment_complete call is done, it can cause the order to revert to a non-paid state, as the save is performed with old order data. In my scenario this is not a rare occurence but happens in approximately half of the paid orders.

Example:
1. Customer places order and is sent to payment window
2. Customer enters card information and pays order.
3. order_received_url: Customer is sent back to the woocommerce order_received_url, the $order is loaded from the database.
4. callback: A callback is sent to woocommerce, the $order is loaded from the database and payment_complete is called.
5. callback: The callback's call to payment_complete results $order->save() being called, saving the order in the database.
6. order_received_url: The order_received_url invokes an $order->save() to save the paying customer's IP-address, restoring the $order to a faulty non-paid state.

This could potentially be solved by removing the $order->save() call from the order_received() function, and saving the IP-address as post meta data instead.

**Comment by rodrigoprimo** [comment]
cc @peterfabian as I believe this is related to the changes introduced in #21038.

**Comment by peterfabian** [comment]
Hi @cblach 

Please correct me if I'm wrong, what you're saying in your example is that the order is loaded from the database here: https://github.com/woocommerce/woocommerce/blob/master/includes/shortcodes/class-wc-shortcode-checkout.php#L230

Then a callback runs that marks the order as paid, but on the line 242 https://github.com/woocommerce/woocommerce/blob/master/includes/shortcodes/class-wc-shortcode-checkout.php#L242, it gets saved again as unpaid order?

Strictly speaking, it seems to me that this opportunity for a race condition is probably true of any WooCommerce code where objects are loaded and then saved later, with some actions/filters running in between. 

> This could potentially be solved by removing the $order->save() call from the order_received() function, and saving the IP-address as post meta data instead.

If you propose circumventing CRUD layer for orders and writing directly to `post_meta`, then I'm not a big fan of this approach. However, I think that postponing this `order->save()` for later time might be a way to work around this problem.

**Comment by cblach** [comment]
Hi @peterfabian 
I believe you you are quite right, about how the bug works.
However, I am unsure how postponing the order->save() in the checkout page would help. From my understanding, the problem is really at the order->load() in checkout where it loads the unpaid order (which might soon be outdated, aka paid). Postponing the save, should only postpone the inevitable. That said, I might miss some perspective, please do elaborate.

Also, you are right that race-conditions are unavoidable, however, this race condition is in my opinion particularly bad as it might affect a large portion of orders (due to the unfortunate timing of the order->load()/order->save right after the order is paid) and is not a one-in-a-million event as most other race conditions.

Something that might alleviate the majority of cases is making the save conditional.
The comment before the order is modified in the checkout php reads "In case order is created from admin, but paid by the actual customer, store the ip address of the payer.". Perhaps the save could be made only if said order is actually created in the admin, and not just in general case?

**Comment by peterfabian** [comment]
> Postponing the save, should only postpone the inevitable. That said, I might miss some perspective, please do elaborate.

I was thinking more in the terms of moving the whole load + save of IP address to a scheduled action and let it run at later time.

However, it seems like we do have the option to check whether the order was created via admin interface, so I've added the check in #25137. Please test if you get a chance.

**Comment by glagonikas** [comment]
@cblach Have you managed to reproduce this in a staging/test environment?

We've got a similar issue whereby orders are moved to processing, then back to pending-payment, but we've never managed to reproduce (and identify) the cause. In our case however, the order notes have a few (<5) seconds difference.
