### ISSUE TITLE
Price filter not working over 100 million

### ISSUE THREAD

**Issue by camilolunacom** [woocommerce/woocommerce#24945]
**Describe the bug**
The price filter is not working for prices over 100,000,000.

Filtering product with a max_price of any value above 100,000,000 will not work. The query will still show all product with a price above the min_price.

Example:
Simple store with 5 products with their prices at: 
Product A: 80 million
Product B: 110 million
Product C: 150 million
Product D: 160 million
Product E: 200 million

Placing the min_price filter at 90 million and max_price filter at 155 million should show only products B and C. But it is actually showing B, C, D and E.

**To Reproduce**
1. Create the 5 products above;
2. Go to the Store page;
3. Use the price filter widget (or append `?min_price=80000000&max_price=155000000` to the url);
4. You will see products B, C, D and E instead of only B and C.

**Screenshots**
According to the price filter (and URL parameters), this store should only show products with prices 105 million and 150 million. Instead it's showing all products with prices above 100 million.

![Example of filter results](https://st.alzr.co/Screen-Shot-2019-10-31-at-3.09.20-PM.png)

**Expected behavior**
Price filter should work for any value, including over 100 million which is not that much on currencies such as COP.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

WordPress address (URL): https://test.alzr.co
Site address (URL): https://test.alzr.co
WC Version: 3.7.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.4
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.9
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.59.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.6.40-84.0-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.1
WC Database Prefix: y7b_
MaxMind GeoIP Database: ✔
Total Database Size: 37.16MB
Database Data Size: 23.40MB
Database Index Size: 13.76MB
y7b_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
y7b_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
y7b_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
y7b_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
y7b_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
y7b_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
y7b_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
y7b_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
y7b_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
y7b_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
y7b_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
y7b_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
y7b_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
y7b_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
y7b_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
y7b_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
y7b_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
y7b_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
y7b_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
y7b_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
y7b_icl_languages_translations: Data: 0.20MB + Index: 0.13MB + Engine InnoDB
y7b_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
y7b_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
y7b_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
y7b_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
y7b_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
y7b_icl_strings: Data: 2.52MB + Index: 4.78MB + Engine InnoDB
y7b_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
y7b_icl_string_pages: Data: 1.52MB + Index: 1.97MB + Engine InnoDB
y7b_icl_string_positions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
y7b_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
y7b_icl_string_translations: Data: 1.52MB + Index: 0.31MB + Engine InnoDB
y7b_icl_string_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
y7b_icl_translate: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
y7b_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
y7b_icl_translations: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
y7b_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
y7b_icl_translation_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
y7b_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
y7b_options: Data: 6.03MB + Index: 0.05MB + Engine InnoDB
y7b_postmeta: Data: 7.52MB + Index: 4.03MB + Engine InnoDB
y7b_posts: Data: 1.52MB + Index: 0.50MB + Engine InnoDB
y7b_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
y7b_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
y7b_term_relationships: Data: 1.52MB + Index: 0.48MB + Engine InnoDB
y7b_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
y7b_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
y7b_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
y7b_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
y7b_wc_product_meta_lookup: Data: 0.19MB + Index: 0.44MB + Engine InnoDB
y7b_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
y7b_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

BackupBuddy: by iThemes – 8.4.19.0
Event Tickets: by Modern Tribe
Inc. – 4.10.10

Mini Storage Calculator: by New Destiny Media
LLC – 1.04

SG Optimizer: by SiteGround – 5.3.6
The Events Calendar: by Modern Tribe
Inc. – 4.9.10

WooCommerce: by Automattic – 3.7.1

### Inactive Plugins (6) ###

Akismet Anti-Spam: by Automattic – 4.1.2
Hello Dolly: by Matt Mullenweg – 1.7.2
WPML Media: by OnTheGoSystems – 2.5.3
WPML Multilingual CMS: by OnTheGoSystems – 4.2.8
WPML String Translation: by OnTheGoSystems – 2.10.6
WPML Translation Management: by OnTheGoSystems – 2.8.7

### Settings ###

API Enabled: –
Force SSL: –
Currency: COP ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #45 - /
Cart: #46 - /carrito/
Checkout: #47 - /finalizar-compra/
My account: #48 - /mi-cuenta/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront Child Theme
Version: 1.0.0
Author URL: http://stuartduff.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.5.3
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2019-10-24 02:59:39 -0500
Newest: 2019-10-24 02:59:39 -0500

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –
</details>

**Comment by juliaamosova** [comment]
Hi @camilolunacom thank you for reporting the issue. I am able to reproduce it. 

By default, `Filter by Price` widget doesn't offer an option to filter the price above 100,000,000 even if there are products exist with the price above 100,000,000:

![widget](https://user-images.githubusercontent.com/19143190/68217116-f41c6b00-ffd9-11e9-8042-47d59a80fc87.jpg)

Upon appending`?min_price=80000000&max_price=155000000` to the URL, the widget max / min amounts get updated but the results shown are still incorrect - all products are displayed on the page even those beyond set limits:

![all](https://user-images.githubusercontent.com/19143190/68217200-20d08280-ffda-11e9-83fc-42f264652fb2.jpg)

Adding a `High` priority and `3.9` milestone.

**Comment by itzmekhokan** [comment]
This issues is related with #24428

**Comment by juliaamosova** [comment]
Thanks for referencing the existing issue @itzmekhokan. I am closing this one in favor of 24428 - please continue the discussion there.
