### ISSUE TITLE
[WP 5.3] CSS issues with selectWoo and Product Data postbox inputs

### ISSUE THREAD

**Issue by franticpsyx** [woocommerce/woocommerce#24942]
**Describe the bug**

When updating to WP5.3:

- [ ] Checkboxes under the Product Data postbox look distorted.
- [ ] SelectWoo inputs appear very differently from the new admin styles (edited).

**To Reproduce**

1. Update to WP 5.3.
2. Go to **Product Data > Advanced**.
3. Tick/untick **Enable Reviews**.
4. Go to **Product Data > Linked Products**.
5. Borders are not consistent with WP 5.3. 

Other types of selectWoo inputs (e.g. multi-select) have line-height and padding issues that need fixing under WP 5.3. 

On a side note, I'd love to contribute to `selectWoo`, but the repository doesn't seem to be actively maintained and its built assets are merely pasted in the WC repo. Would be nice to have a node module for `selectWoo` and build WC with it. 

Note that `select2` is currently at 4.0.11, and there doesn't seem to be an easy way to cherry pick fixes from there into `selectWoo`. 

**Screenshots**
https://share.getcloudapp.com/z8uwLW2q
https://share.getcloudapp.com/YEuvrEqm

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

WP 5.3

**Comment by helgatheviking** [comment]
I would also add that SelectWoo inputs appear very differently from the new admin styles (maybe they always did, I can't recall)

SelectWoo inputs are squared versus rounded. And active inputs are highlighted in black versus highlighted in the admin's color.

![SelectWoo inputs with black, square borders](https://user-images.githubusercontent.com/507025/68151793-9f0c2680-feff-11e9-98b9-23763723bc84.png)

**Comment by franticpsyx** [comment]
> SelectWoo inputs are squared versus rounded. 

Yup, we've been struggling with this as well. @xristos3490 has worked on some local fixes in our extensions but selectWoo needs a PR, as the results list is appended to the `body` and can't be re-styled. One challenge here is that we'll need a conditional class on the `body` element for backwards compatibility.

We've noted some issues with buttons, too -- primary buttons are now "flat", but Woo-colored buttons (mainly used in empty states and onboarding screens) still have the WP 5.2 "3D" look.

Happy to contribute fixes if we get the green light.

**Comment by juliaamosova** [comment]
@franticpsyx thank you for reporting the issue. Thank you for your feedback as well @helgatheviking. We are going to discuss this further with the WooCommerce core team and get back here with an update. Contributions are, of course, welcome but we'll need to decide how to proceed in this particular case.

**Comment by peterfabian** [comment]
Please see https://github.com/woocommerce/woocommerce/pull/25118.
