### ISSUE TITLE
WC_Shortcode_My_Account::retrieve_password() Code Conflict

### ISSUE THREAD

**Issue by yaaashaaar** [woocommerce/woocommerce#24967]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

Try to add new errors to `WC_Shortcode_My_Account::retrieve_password()`, using the available hooks.

## Expected/actual behavior

If you try to add some errors, in the forget password process, you may want to use `WC_Shortcode_My_Account::retrieve_password()` method. On line 298, it checks if there are any errors in the `$errors`, which was defined in the line 294:
`$errors = new WP_Error();`
It seems that the `lostpassword_post` action which was defined in the line 296, should've been a filter hook instead of an action. Otherwise in this situation the error check on line 298, would never be triggered and it's worthless.

P.S. Line numbers refer to the [core class file](https://github.com/woocommerce/woocommerce/blob/master/includes/shortcodes/class-wc-shortcode-my-account.php), in the latest version (3.7.1)

```
$errors = new WP_Error();

do_action( 'lostpassword_post', $errors );

if ( $errors->get_error_code() ) {
    wc_add_notice( $errors->get_error_message(), 'error' );

    return false;
}
```
## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

**Comment by claudiosanches** [comment]
> It seems that the lostpassword_post action which was defined in the line 296, should've been a filter hook instead of an action. Otherwise in this situation the error check on line 298, would never be triggered and it's worthless.

This is not true, works just fine with an action, no need for an filter.

> Try to add new errors to WC_Shortcode_My_Account::retrieve_password(), using the available hooks.

I can add new errors without any issue, see my sample code:

```
add_action( 'lostpassword_post', function( $error ) {
    $error->add( 'my_error_code', 'My error message!' );
});
```

And here displaying my custom message:
![Screenshot from 2019-11-13 15-51-59](https://user-images.githubusercontent.com/1264099/68794319-91584e80-062d-11ea-93dc-ce01b7b8de1e.png)
