### ISSUE TITLE
WooCommerce 3.8.0 Product Attribut and Variations won't load 

### ISSUE THREAD

**Issue by LilZloty** [woocommerce/woocommerce#24979]
Hello ! 

Describe the bug : 
Since the update **3.7.1** i can't load the **product attribut system** and the **products variations** , so i decided to start a new website in local and it work's, but when i load it in my webhosting without any other plugin activated and the default theme also it doesn't work, it keep loading. 

So i tried to install an ancient version of woocommerce the "**3.7.0**" and it work perfectly but now im stuck because others plugins are updated lol 

To Reproduce

1. Go to WooCommerce > Products > Modify > Variations 
2. Click on Add a Variation
3. Loading loading 

Expected behavior
I would like to know where it can came from thank's for your reply. 

Isolating the problem (mark completed items with an [x]):

[x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
[x] This bug happens with a default WordPress theme active, or Storefront.
[x] I can reproduce this bug consistently using the steps above.

Wordpress environment 
<details>
`
### WordPress Environment ###

WordPress address (URL): https://sneakday.com
Site address (URL): https://sneakday.com
WC Version: 3.8.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.23
PHP Post Max Size: 20 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.66.0
OpenSSL/1.0.2t

SUHOSIN Installed: –
MySQL Version: 5.7.28
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.0
WC Database Prefix: sneakday_
MaxMind GeoIP Database: ✔
Taille totale de la base de données: 10.69MB
Taille de la base de données: 8.57MB
Taille de l’index: 2.12MB
sneakday_woocommerce_sessions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
sneakday_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
sneakday_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
sneakday_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
sneakday_woocommerce_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
sneakday_woocommerce_order_itemmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
sneakday_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
sneakday_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
sneakday_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
sneakday_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
sneakday_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
sneakday_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
sneakday_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
sneakday_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
sneakday_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
sneakday_comments: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
sneakday_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
sneakday_options: Données : 3.06MB + Index : 0.08MB + Moteur InnoDB
sneakday_postmeta: Données : 2.41MB + Index : 0.72MB + Moteur InnoDB
sneakday_posts: Données : 0.42MB + Index : 0.13MB + Moteur InnoDB
sneakday_revslider_css: Données : 0.13MB + Index : 0.00MB + Moteur InnoDB
sneakday_revslider_layer_animations: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
sneakday_revslider_navigations: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
sneakday_revslider_sliders: Données : 0.11MB + Index : 0.00MB + Moteur InnoDB
sneakday_revslider_slides: Données : 1.52MB + Index : 0.00MB + Moteur InnoDB
sneakday_revslider_static_slides: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
sneakday_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
sneakday_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
sneakday_term_relationships: Données : 0.14MB + Index : 0.08MB + Moteur InnoDB
sneakday_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
sneakday_usermeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
sneakday_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
sneakday_wc_admin_notes: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
sneakday_wc_admin_note_actions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
sneakday_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
sneakday_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
sneakday_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
sneakday_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
sneakday_wc_order_product_lookup: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
sneakday_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
sneakday_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
sneakday_wc_product_meta_lookup: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
sneakday_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
sneakday_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
sneakday_wsluserscontacts: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
sneakday_wslusersprofiles: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (31) ###

Akismet Anti-Spam: par Automattic – 4.1.3
Cherry Data Importer: par TemplateMonster – 1.1.2
Cherry Live Demo Mods Switcher: par Cherry Team – 1.1
Cherry Plugin Wizard: par Cherry Team – 1.0.0
Cherry PopUps: par Jetimpex – 1.1.8
Cherry Projects: par Cherry Team – 1.2.15
Cherry Search: par Zemez – 1.1.5
Cherry Services List: par Zemez – 1.4.7
Cherry Sidebars: par Zemez – 1.1.3
Cherry Socialize: par Jetimpex – 1.1.4
Cherry Team Members: par Zemez – 1.4.6
Cherry Testimonials: par Zemez – 1.1.3
Contact Form 7: par Takayuki Miyoshi – 5.1.4
Elementor: par Elementor.com – 2.7.5
JetElements For Elementor: par Zemez – 2.1.4
JetMenu: par Zemez – 1.5.14
HubSpot All-In-One Marketing - Forms, Popups, Live Chat: par HubSpot – 7.15.11
Slider Revolution: par ThemePunch – 5.4.1
Shoppable Social Media Galleries by SNPT: par Snapppt – 1.1.7
TM Photo Gallery: par JetImpex – 1.1.2
TM Style Switcher: par Jetimpex – 1.0.6
TM Timeline: par Jetimpex – 1.1.1
TM WooCommerce Ajax Filters: par TemplateMonster – 1.0.9 – Non testé avec la version active de WooCommerce
TM WooCommerce Compare & Wishlist: par JetImpex – 1.1.7 – Non testé avec la version active de WooCommerce
TM WooCommerce Package: par Zemez – 1.3.6 – Non testé avec la version active de WooCommerce
TM WooCommerce Quick View: par TemplateMonster – 1.0.1 – Non testé avec la version active de WooCommerce
WooCommerce Admin: par WooCommerce – 0.21.0 – Non testé avec la version active de WooCommerce
WOOCS - WooCommerce Currency Switcher: par realmag777 – 1.3.0 – Non testé avec la version active de WooCommerce
WooCommerce: par Automattic – 3.8.0
WordPress Importer: par wordpressdotorg – 0.6.4
WordPress Social Login: par Miled – 2.3.3

### Must Use Plugins (1) ###

Elementor Safe Mode: par Elementor.com – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
woosb (woosb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la boutique: #25 - /shop/
Panier: #26 - /cart/
Validation de la commande: #27 - /checkout/
Mon compte: ❌ Page non définie
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Cosmetro
Version: 3.2.0
Author URL: https://themeforest.net/user/jetimpex
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: cosmetro/woocommerce/archive-product.php
cosmetro/woocommerce/cart/cart-totals.php
cosmetro/woocommerce/cart/cart.php
cosmetro/woocommerce/cart/cross-sells.php
cosmetro/woocommerce/cart/proceed-to-checkout-button.php
cosmetro/woocommerce/checkout/review-order.php
cosmetro/woocommerce/content-product.php
cosmetro/woocommerce/content-product_cat.php
cosmetro/woocommerce/content-widget-product.php
cosmetro/woocommerce/global/breadcrumb.php
cosmetro/woocommerce/global/quantity-input.php
cosmetro/woocommerce/global/wrapper-end.php
cosmetro/woocommerce/global/wrapper-start.php
cosmetro/woocommerce/loop/loop-end.php
cosmetro/woocommerce/loop/loop-start.php
cosmetro/woocommerce/myaccount/my-account.php
cosmetro/woocommerce/product-searchform.php
cosmetro/woocommerce/single-product/meta.php
cosmetro/woocommerce/single-product/product-image.php
cosmetro/woocommerce/single-product/related.php
cosmetro/woocommerce/single-product/review.php
cosmetro/woocommerce/single-product/title.php
cosmetro/woocommerce/single-product/up-sells.php
cosmetro/woocommerce/single-product-reviews.php
cosmetro/woocommerce/single-product.php

### Action Scheduler ###

Complete: 23
Oldest: 2019-11-04 15:13:33 +0100
Newest: 2019-11-05 18:08:30 +0100

Pending: 1
Oldest: 2019-11-05 19:08:30 +0100
Newest: 2019-11-05 19:08:30 +0100

Canceled: 1
Oldest: 2019-11-05 17:38:56 +0100
Newest: 2019-11-05 17:38:56 +0100

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Pictures** | Products attributs
![image](https://user-images.githubusercontent.com/54123008/68229825-381e6880-fff8-11e9-9894-4e0b42914368.png)

**Comment by LilZloty** [comment]
The error in the console 
![image](https://user-images.githubusercontent.com/54123008/68231338-27bbbd00-fffb-11e9-9e9c-9c69e4dd02c2.png)

**Comment by juliaamosova** [comment]
Hi @LilZloty,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only. 

That said, I am not able to reproduce the issue with either version of WooCommerce (3.7, 3.7.1, 3.8). 

The type of issue you submitted looks like `support request` which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow the steps listed in **Isolating the problem** section of our [bug report template](https://github.com/woocommerce/woocommerce/issues/new?assignees=&labels=&template=Bug_report.md&title=). If you confirm the bug on your end, please provide us with clear steps to reproduce the issue. 

To help you troubleshoot the issue you are having, I recommend doing the following:

* Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case
* If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket here](https://woocommerce.com/contact-us/)
* Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

I am closing this issue as it seems to be a support request and not a bug. If I missed something, please leave a comment and I will take a second look.

**Comment by Pixelstart** [comment]
Having the same issue here. Also from 3.7.1.
