### ISSUE TITLE
South Africa not included as country that receives VAT instead of "Tax"

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#24995]
**Describe the bug**
South Africa collects VAT and not "tax", so it should have this swapped automatically in WooCommerce. This should just mean an extra line added here:
https://github.com/woocommerce/woocommerce/blob/3.8.0/includes/class-wc-countries.php#L361-L364

**To Reproduce**
1. Switch country to South Africa
1. Tax doesn't switch to VAT

**Affected tickets**
2436315-hc

**Comment by jobthomas** [comment]
VAT instead of TAX:
https://www.sars.gov.za/TaxTypes/VAT/Pages/default.aspx

@Luminus indicated he'd work on a PR

**Comment by jobthomas** [comment]
@Luminus If I can believe this wiki map then this might be a big PR @Luminus https://en.wikipedia.org/wiki/Value-added_tax#/media/File:Countries_with_VAT.svg

**Comment by Luminus** [comment]
@jobthomas I think I'll limit it to the countries on this list that actually use the VAT abbreviation for now - https://en.wikipedia.org/wiki/Value-added_tax#Non-European_Union_countries

**Comment by Luminus** [comment]
I'm accounting for the following countries based on that list:

- Bahamas
- Bahrain
- Barbados
- Egypt
- Ethiopia
- Fiji
- Gambia
- Ghana
- India
- Iran
- Kazakhstan
- Mauritius
- Mongolia
- Namibia
- Nepal
- Nigeria
- Palestine
- Rwanda
- Saint Kitts and Nevis
- Saudi Arabia
- South Africa
- South Korea
- Sri Lanka
- Thailand
