### ISSUE TITLE
Option _sold_individually not working. Quantity input still displaying

### ISSUE THREAD

**Issue by radykal** [woocommerce/woocommerce#24992]
**Describe the bug**
I noticed in the latest update the option "Enable this to only allow one of this item to be bought in a single order" with the meta key _sold_individually seems not be working correctly. In the past when this option was checked, the quantity input was not showing in the product page.

**To Reproduce**
Tested with Storefront theme and latest WooCommerce version 3.8.0

**Expected behavior**
Do not display quantity input in product page.

**Comment by billrobbins** [comment]
Hi @radykal,

I tried this on my development site just now and enabling the "Sold Individually" option did remove the quantity field from the front-end.  

![no quantity](https://cdn-std.droplr.net/files/acc_705319/2lTPJy)
(Link to screenshot:  https://cld.wthms.co/2lTPJy)

Can you confirm this happens with only WooCommerce 3.8 and Storefront active on the site?  If so please post the System Status Report too.

**Comment by radykal** [comment]
Sorry for the confusing. It was caused by another plugin. You can close this one!
