### ISSUE TITLE
Menu_order not updated when using products shortcode

### ISSUE THREAD

**Issue by PyIter** [woocommerce/woocommerce#25004]
**Describe the bug**
When reordering with the sorting function, the menu_order is not updated where a the shortcode [products] is used. This is because the order is stored in transients. 

**To Reproduce**
1. Go to 'Products';
2. Click on 'Sorting';
3. Drag a product so that the sorting changes;
4. Go to a page where the [products] shortcode is used, with the parameter orderby="menu_order"
5. Refresh the page. 
6. The products are not shown ordered by menu_order. 

**Workaround**
After reordering you can run the following query: 

DELETE FROM `wp_options` WHERE `option_name` LIKE ('%\_transient\_wc\_block\_%');

The transient cache stores the order of the products, and is not deleted when updating the menu_order in the backend. 

**Screenshots**
N/A

**Expected behavior**
The expected behavior is that at the page where shortcode is used the menu_order is updated at refreshing. 

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a new wordpress/woocommerce install
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Wordpress 5.2.4
Woocommerce 3.8.0

**Comment by juliaamosova** [comment]
Thank you for raising this issue @PyIter. 

I can reproduce it. Steps I took:

1) Created a page with the following shortcode: `[products columns="3" orderby="menu_order"]`:

![sorting](https://user-images.githubusercontent.com/19143190/68843300-2740b780-06c8-11ea-980f-e9c8989722de.jpg)

2) Navigated to `WooCommerce / Products`
3) Clicked on `Sorting` and rearranged products:

![resorted](https://user-images.githubusercontent.com/19143190/68843319-30318900-06c8-11ea-9c55-8fa790cd7ad8.jpg)

4) Navigated back to the page I created in step 1 - products order didn't change according to how I rearranged them in step 3. The order stayed the same as it was when I created the page (with the original order).
