### ISSUE TITLE
Ability to add content before and after a settings page

### ISSUE THREAD

**Issue by passatgt** [woocommerce/woocommerce#25019]
**Is your feature request related to a problem? Please describe.**
I'm trying to add a sidebar to my plugin's settings page, which is located under a tab in Settings / Integrations. Currently theres no way to add content outside of the main form, but inside the `.wrap` div. 

**Describe the solution you'd like**
I would suggest having two extra actions in `html-admin-settings.php` before and after the opening-closing `<form>` tag. Based on the current naming scheme, i would propose:

```
do_action( 'woocommerce_before_settings_' . $current_tab );
do_action( 'woocommerce_after_settings_' . $current_tab );
```

**Describe alternatives you've considered**
I considered using CSS to move my content to the sidebar(for example absolute position), but its a very hacky solution. Also, if i would add a second form to process data, it won't be valid, since its not advisable to nest two form inside each-other.

**Comment by claudiosanches** [comment]
Thank you for suggesting this feature!

I'm closing the issue as it already has a PR, please continue the discussion over at #25028.
