### ISSUE TITLE
Setup Wizard (OBW) still opt-in by default

### ISSUE THREAD

**Issue by californiakat** [woocommerce/woocommerce#25010]
**Describe the bug**

Setup Wizard (OBW) popup for Usage Tracking "Help Improve WooCommerce" shows opt-in by default. 

In the Beta release notes and 3.8 Changelog, it says that Setup Wizard (OBW) is opt-out by default, which adheres to WordPress.org plugin guidelines.

<img width="626" alt="Screen Shot 2019-11-10 at 12 47 54" src="https://user-images.githubusercontent.com/6988393/68543598-72ea1d00-03b9-11ea-802d-a5c2427212b8.png">
<img width="674" alt="Screen Shot 2019-11-10 at 12 53 02" src="https://user-images.githubusercontent.com/6988393/68543599-741b4a00-03b9-11ea-9bc1-67179304f31f.png">

**To Reproduce**
1. Go to Dashboard Help tab in upper right corner.
2. Click on Setup Wizard.
3. Enter Store Setup info in fields.
4. Select Let's Go
5. Popup shows opt-in.

**Screenshots**
<img width="611" alt="Screen Shot 2019-11-10 at 12 47 01" src="https://user-images.githubusercontent.com/6988393/68543628-e4c26680-03b9-11ea-8daa-0a47b5498934.png">

**Expected behavior**
The box is supposed to be unticked.

Also the text says: 
Learn more about how usage tracking works, and how you'll be helping "here."
Instead of "here," we should use the name of page for transparency purposes. 

So should read: Learn more about how usage tracking works, and how you'll be helping at WooCommerce Usage Tracking (URL: https://woocommerce.com/usage-tracking/).

If we need to cut some words to fit everything on the same line, I recommend:
Learn more about usage tracking, and how you'll be helping at WooCommerce Usage Tracking(URL: https://woocommerce.com/usage-tracking/).
or
Learn more about Usage Tracking (URL: https://woocommerce.com/usage-tracking/), and how you'll be helping. 

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Pressable site
WooCommerce 3.8
WP 5.2.4

**Comment by juliaamosova** [comment]
Thank you for reporting the issue @californiakat. However, I am not able to reproduce it. I have tried multiple scenarios of the new install - the box comes unchecked in all the cases. Could it be that you run the setup again on the site where it was previously done? In this case, the box will be checked (as it was checked before). 

>Also the text says:
Learn more about how usage tracking works, and how you'll be helping "here."
Instead of "here," we should use the name of page for transparency purposes.

Sounds good to me, we can change that in order to be more transparent.

**Comment by californiakat** [comment]
>Could it be that you run the setup again on the site where it was previously done? In this case, the box will be checked (as it was checked before).

It could be but it was unticked on the previous site also. In any case, I can see on a fresh install, it works as expected so closing.

>Sounds good to me, we can change that in order to be more transparent.

Awesome, thanks!

**Comment by juliaamosova** [comment]
>It could be but it was unticked before also. In any case, I can see on a fresh install, it works as expected so closing.

Thanks for testing again @californiakat. 

>Awesome, thanks!

I opened a new issue to document that and make sure we have it done: https://github.com/woocommerce/woocommerce/issues/25022
