### ISSUE TITLE
Caching issues with WC_Cache_Helper::incr_cache_prefix()

### ISSUE THREAD

**Issue by tillkruss** [woocommerce/woocommerce#25018]
The `WC_Cache_Helper::incr_cache_prefix()` is increasing counter that don't exist.

The `wp_cache_incr()` method is not increasing counters that haven't been added to the cache. Or at least I can't find any references where those counters are created in WC.

This will inevitably lead to **cache invalidation issues** with most object caches.

https://github.com/woocommerce/woocommerce/blob/a6819ad495be38a73fb558d5bb519a1d4e246182/includes/class-wc-cache-helper.php#L104-L111

The correct way of increasing counters with WP object cache is:

```php
wp_cache_add('counter', 0);
wp_cache_incr('counter', 1);
```

See `WP_Object_Cache::incr()`:

https://github.com/WordPress/WordPress/blob/ba249d8951ba05ca516284da1c3db6f026490803/wp-includes/cache.php#L559-L595

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #24961.
