### ISSUE TITLE
Review Schema Error: "Either “offers”, “review”, or “aggregateRating” should be specified error"

### ISSUE THREAD

**Issue by or128** [woocommerce/woocommerce#25014]
Review Schema has error in them:
**One of offers or review or aggregateRating should be provided.**

I believe Google has changed the guidelines and now requires the Review Schema to be served differently.

This error occurs once for every review outputted.

1. check any product with reviews with Structured Data Testing Tool: 
https://search.google.com/structured-data/testing-tool#

**Screenshot: **
https://ibb.co/d59vvmn

**Expected behavior**
No errors.

**WordPress Environment**
Latest WP and WC.

Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.

`
### WordPress Environment ###

WordPress address (URL): https://www.japanese-knives.co.il
Site address (URL): https://www.japanese-knives.co.il
WC Version: 3.8.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.2.4
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.17.4
PHP Version: 7.3.9
PHP Post Max Size: 2 GB
PHP Time Limit: 3600
PHP Max Input Vars: 9000
cURL Version: 7.66.0
OpenSSL/1.0.2k-fips

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.18-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
Zapier Integration - Active Feeds: ✔ 2 active Zapier Feeds.
Zapier Integration - Cron Tasks: ✔ 0 pending Zapier cron tasks.
Zapier Feed #1 Name: ✔ WooCommerce new order to Pipedrive
Zapier Feed #1 Webhook URL: ✔ https://hooks.zapier.com/hooks/catch/1820158/az4tnv/
Zapier Feed #1 Trigger: ✔ New Order
Zapier Feed #1 Test Result: ✔ Successfully sent sample data to https://hooks.zapier.com/hooks/catch/1820158/az4tnv/.
Zapier Feed #2 Name: ✔ WooCommerce new person to Pipedrive
Zapier Feed #2 Webhook URL: ✔ https://hooks.zapier.com/hooks/catch/1820158/w3lvd2/
Zapier Feed #2 Trigger: ✔ New Order
Zapier Feed #2 Test Result: ✔ Successfully sent sample data to https://hooks.zapier.com/hooks/catch/1820158/w3lvd2/.

### Database ###

WC Database Version: 3.8.0
WC Database Prefix: hks_
MaxMind GeoIP Database: ✔
Total Database Size: 168.52MB
Database Data Size: 127.52MB
Database Index Size: 41.00MB
hks_woocommerce_sessions: Data: 2.02MB + Index: 0.05MB + Engine InnoDB
hks_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
hks_woocommerce_order_items: Data: 1.52MB + Index: 0.28MB + Engine InnoDB
hks_woocommerce_order_itemmeta: Data: 8.52MB + Index: 6.03MB + Engine InnoDB
hks_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
hks_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
hks_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
hks_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_acl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_blocks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_countries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_lab: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_lab_ip: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
cerber_lab_net: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_log: Data: 4.52MB + Index: 2.34MB + Engine InnoDB
cerber_qmem: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
cerber_traffic: Data: 23.05MB + Index: 1.48MB + Engine InnoDB
hks_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_atum_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_atum_product_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_cerber_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_cerber_sets: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
hks_cerber_uss: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_commentmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
hks_comments: Data: 5.52MB + Index: 2.25MB + Engine InnoDB
hks_duplicator_pro_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_duplicator_pro_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_enquiry_detail_new: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
hks_enquiry_history: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_enquiry_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_enquiry_quotation: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_enquiry_thread: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_gcb: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_grp_google_place: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_grp_google_review: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_huge_itgallery_gallerys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
hks_huge_itgallery_images: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
hks_huge_itgallery_like_dislike: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
hks_huge_itgallery_params: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
hks_imagify_files: Data: 0.36MB + Index: 0.33MB + Engine InnoDB
hks_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_mclean_refs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_mclean_scan: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
hks_media_file_manager_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_nextend2_image_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_nextend2_section_storage: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_nextend2_smartslider3_sliders: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
hks_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_nextend2_smartslider3_slides: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
hks_options: Data: 25.38MB + Index: 0.38MB + Engine InnoDB
hks_postmeta: Data: 34.56MB + Index: 19.06MB + Engine InnoDB
hks_posts: Data: 5.52MB + Index: 2.44MB + Engine InnoDB
hks_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
hks_revslider_css_bkp: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
hks_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_sliders: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
hks_revslider_sliders_bkp: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
hks_revslider_slides: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
hks_revslider_slides_bkp: Data: 0.41MB + Index: 0.00MB + Engine InnoDB
hks_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tcb_api_error_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_termmeta: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
hks_terms: Data: 1.52MB + Index: 0.52MB + Engine InnoDB
hks_term_relationships: Data: 1.52MB + Index: 0.38MB + Engine InnoDB
hks_term_taxonomy: Data: 0.36MB + Index: 0.34MB + Engine InnoDB
hks_tge_answers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_tge_questions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_tqb_event_log: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
hks_tqb_results: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tqb_tests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tqb_tests_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tqb_users: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
hks_tqb_user_answers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_tqb_variations: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
hks_ukuu_favorites: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_usermeta: Data: 2.52MB + Index: 1.98MB + Engine InnoDB
hks_users: Data: 0.11MB + Index: 0.08MB + Engine InnoDB
hks_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wc_customer_lookup: Data: 0.25MB + Index: 0.16MB + Engine InnoDB
hks_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
hks_wc_order_product_lookup: Data: 1.52MB + Index: 0.42MB + Engine InnoDB
hks_wc_order_stats: Data: 0.28MB + Index: 0.22MB + Engine InnoDB
hks_wc_order_tax_lookup: Data: 0.17MB + Index: 0.16MB + Engine InnoDB
hks_wc_product_meta_lookup: Data: 0.09MB + Index: 0.16MB + Engine InnoDB
hks_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
hks_wd_fb_data: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
hks_wd_fb_info: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wd_fb_option: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wd_fb_shortcode: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
hks_wd_fb_theme: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
hks_woocommerce_bundled_itemmeta: Data: 0.47MB + Index: 0.63MB + Engine InnoDB
hks_woocommerce_bundled_items: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
hks_yoast_seo_links: Data: 0.33MB + Index: 0.09MB + Engine InnoDB
hks_yoast_seo_meta: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
sib_model_contact: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (76) ###

Query Monitor: by John Blackbourn – 3.4.0
10bit-woocommerce-zap-mirror: by 10bit – 1.3.14 – Not tested with the active version of WooCommerce
Add Index To Autoload: by RAIDBOXES – 1.0.0
Check Email: by Chris Taylor – 0.5.6
Classic Editor: by WordPress Contributors – 1.5
Contact Form 7: by Takayuki Miyoshi – 5.1.4
Content Blocks (Custom Post Widget): by Johan van der Wijk – 3.1
Delete Expired Transients: by WebAware – 2.0.7
Duplicate Menu: by Jonathan Christopher – 0.2.1
Enable Media Replace: by ShortPixel – 3.3.6
Envato Market: by Envato – 2.0.3
Facebook Post Embed: by Alobaidi – 1.0.0
Finale WooCommerce Deal Pages: by XLPlugins – 1.4.1 – Not tested with the active version of WooCommerce
Finale - WooCommerce Sales Countdown Timer & Discount Plugin: by XLPlugins – 2.16.0 – Not tested with the active version of WooCommerce
Force Regenerate Thumbnails: by Pedro Elsner – 2.0.6
Global Content Blocks: by Dave Liske – 2.1.5
Health Check & Troubleshooting: by The WordPress.org community – 1.4.2
WhatsApp Chat for WordPress / WooCommerce: by idnovate.com – 1.3.9 – Not tested with the active version of WooCommerce
Stop Generating Image Sizes: by Nazmul Ahsan – 2.0.2
Imagify: by WP Media – 1.9.7
Collapse-O-Matic: by twinpictures
baden03 – 1.7.11

Klaviyo: by Klaviyo
Inc. – 2.1.2 – Not tested with the active version of WooCommerce

Loco Translate: by Tim Whitlock – 2.3.1
Media Cleaner Pro: by Jordy Meow – 5.5.1
Perfmatters: by forgemedia – 1.4.4
PixelYourSite PRO: by PixelYourSite – 7.3.6 – Not tested with the active version of WooCommerce
plugin load filter: by enomoto@celtislab – 3.1.0
Product Filter for WooCommerce: by 7VX LLC
USA CA – 7.2.1

Product Catalog Feed Pro by PixelYourSite: by PixelYourSite – 4.0.6 – Not tested with the active version of WooCommerce
PushAlert - Web Push Notifications: by PushAlert – 2.3.5 – Not tested with the active version of WooCommerce
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.1
Slider Revolution: by ThemePunch – 6.1.4
snip - The Rich Snippets & Structured Data Plugin: by wpbuddy – 2.14.19
Search & Replace: by Inpsyde GmbH – 3.2.1
ShiftNav Pro - Responsive Mobile Menu: by Chris Mavricos
SevenSpark – 1.6.3

Shortcode Empty Paragraph Fix: by  – 0.2
SmartLook Visitor Recording: by Smartsupp – 2.1.1
Social Icons Widget by WPZOOM: by WPZOOM – 3.4.0
SOFT79 Cart Links for WooCommerce: by Soft79 – 1.1.4 – Not tested with the active version of WooCommerce
WooCommerce Thank You Page - NextMove: by XLPlugins – 1.12.3 – Not tested with the active version of WooCommerce
TWB Woocommerce Reviews: by Abu Bakar – 1.7.3 – Not tested with the active version of WooCommerce
UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.6.1

Widget CSS Classes: by C.M. Kendrick – 1.5.4
CardCom Payment Gateway: by CardCom LTD – 3.3.1.8 – Not tested with the active version of WooCommerce
WooCommerce Admin: by WooCommerce – 0.21.0 – Not tested with the active version of WooCommerce
WooCommerce Breadcrumbs: by Anthony Hortin – 1.0.5 – Not tested with the active version of WooCommerce
WooCommerce - Frontend Inventory: by Mirko Grewing – 0.7 – Not tested with the active version of WooCommerce
WooCommerce Google Ads Conversion Tracking: by Wolf+Bär Agency – 1.5.5 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Pro: by SkyVerge – 1.8.5
WooCommerce Notification Premium: by Andy Ha (villatheme.com) – 1.4.1 – Not tested with the active version of WooCommerce
WooCommerce Product Bundles: by SomewhereWarm – 5.13.3
WooCommerce Product Primary Category: by BeoCode.d.o.o. – 0.1.2 – Not tested with the active version of WooCommerce
WooCommerce Show Attributes: by Isabel Castillo – 1.6.4 – Not tested with the active version of WooCommerce
WooCommerce Zapier Integration: by OM4 – 1.9.5 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.8.0
WooSidebars: by WooCommerce – 1.4.5
Yoast SEO Premium: by Team Yoast – 12.4
WP Accessibility Helper: by Alex Volkov – 0.5.9.3
WP Cerber Security, Antispam & Malware Scan: by Cerber Tech Inc. – 8.5
Custom Body Class: by Andrei Lupu – 0.7.1
WP Mail SMTP: by WPForms – 1.7.0
WP Native Dashboard: by Heiko Rabe – 1.3.13
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.0.13

WP Rocket | Set Tablets As Mobile: by WP Rocket Support Team –
WP Rocket | YITH WooCommerce Recently Viewed Products Integration: by WP Rocket Support Team –  – Not tested with the active version of WooCommerce
WP Rocket | Custom cURL Timeout For Preload Requests: by WP Rocket Support Team –
WP Rocket | CPCSS Debug Helper: by WP Rocket Support Team – 1.0.0
WP Rocket | Exclude Files from Defer JS: by WP Rocket Support Team –
WP Rocket: by WP Media – 3.4.1.2
WP-RTL: by Fahad Alduraibi – 1.0
WP Server Stats: by Saumya Majumder – 1.6.8
WP User Avatars: by John James Jacoby – 1.4.0
WPX Cron Manager Light: by Giovambattista Fazioli – 2.3.4
Finale Email Countdown Timer: by XLPlugins – 1.2.0 – Not tested with the active version of WooCommerce
XL WooCommerce Sales Triggers: by XLPlugins – 2.9.3 – Not tested with the active version of WooCommerce
Embed Plus for YouTube Pro - Gallery, Channel, Playlist, Live Stream: by Embed Plus for YouTube Team – 13.1.2.1

### Inactive Plugins (16) ###

Contact Form 7 Captcha: by 247wd – 0.0.3
Custom Product Stickers for Woocommerce: by starblank.com – 1.9.0 – Not tested with the active version of WooCommerce
Duplicator Pro: by Snap Creek – 3.8.2.1
Klaviyo for WooCommerce V2: by Klaviyo
Inc. – 2.0.6 – Not tested with the active version of WooCommerce

Mini-cart fatal error logger: by Hiro – 0.1b
Redis Object Cache: by Till Krüss – 1.5.0
Smart Slider 3 Pro: by Nextend – 3.3.22
What The File: by Never5 – 1.5.4
Widget Options: by Phpbits Creative Studio – 3.7.3
Widget Shortcode: by Hassan Derakhshandeh – 0.3.4
WooCommerce Blocks: by Automattic – 2.4.4
WooCommerce Conversion Tracking: by Tareq Hasan – 2.0.4 – Not tested with the active version of WooCommerce
WooCommerce Direct Variation Link: by WP BackOffice – 1.0.3 – Not tested with the active version of WooCommerce
WooCommerce Facebook Like Share Button: by Terry Tsang – 2.2.4 – Not tested with the active version of WooCommerce
WooCommerce Product Slider Pro: by ShapedPlugin – 2.4.19 – Not tested with the active version of WooCommerce
WooCommerce Social Media Share Buttons: by Toastie Studio – 1.3.0 – Not tested with the active version of WooCommerce

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class

### Must Use Plugins (3) ###

aaa-wp-cerber.php: by Cerber Tech Inc. – 1.0
Health Check Troubleshooting Mode: by  – 1.5.1
plugin load filter [plf-filter]: by enomoto@celtislab – 3.1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: ILS (₪)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #1812 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /order/
My account: #7 - /my-account/
Terms and conditions: #605 - /legal/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.10.0
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

### Product Bundles ###

Database Version: 5.13.3
Template Overrides: –

### Action Scheduler ###

Complete: 1,591
Oldest: 2019-10-11 17:50:04 +0300
Newest: 2019-11-11 15:45:03 +0200

Pending: 3
Oldest: 2019-11-11 16:35:05 +0200
Newest: 2019-11-14 12:35:06 +0200

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 13
Oldest: 2019-04-24 15:45:14 +0300
Newest: 2019-06-25 16:47:19 +0300

`

</details>

**Comment by claudiosanches** [comment]
Please stop duplicating issues, this is already fixed by https://github.com/woocommerce/woocommerce/pull/24278 and will be released as soon as possible.
