### ISSUE TITLE
Fix for alignment issues on the settings screen introduced by WP 5.3

### ISSUE THREAD

**Issue by passatgt** [woocommerce/woocommerce#25029]
**Is your feature request related to a problem? Please describe.**
With WordPress 5.3, styling of the form fields have been changed. Different size and color mainly. Currently the fields are larger and not aligned with either the help icon or the label vertically. 

**Describe the solution you'd like**
Here is an example how the settings layout could be improved

![Screenshot 2019-11-13 at 17 46 49](https://user-images.githubusercontent.com/43415/68786379-fc128580-063f-11ea-9dc9-d7b080a8d934.png)

- Label, help icon and field is vertically aligned
- Field height matches the fields on the WordPress Settings screen
- Select box dropdown icon changed to match built-in select box style introduced in WP 3.5
- Rounded multi-select field with bottom padding reduced to be equal to top/left/right padding

Part of this is also reported in #24942

**Comment by passatgt** [comment]
Other issues i noticed on the same topic:

Color preview and field not aligned, also the color preview is not a square:

![Screenshot 2019-11-13 at 20 25 56](https://user-images.githubusercontent.com/43415/68796882-dc855800-0653-11ea-9514-7739b383c29c.png)

Field descriptions(not the help tooltip) should be below the field, like with descriptions with selecti fields:

![Screenshot 2019-11-13 at 20 27 30](https://user-images.githubusercontent.com/43415/68797066-2c641f00-0654-11ea-9efe-1e0552779339.png)

On the Advanced tab, the table layout spacing / header font size doesn't match the built-in layout of WordPress table:

![Screenshot 2019-11-13 at 20 32 49](https://user-images.githubusercontent.com/43415/68797427-dcd22300-0654-11ea-9a26-00fce46b9892.png)

**Comment by juliaamosova** [comment]
Thank you for reporting and for your contribution @passatgt.

**Comment by peterfabian** [comment]
3.8.1 is out, so closing this one.
