### ISSUE TITLE
Missing importnant information in wc_get_orders function documentation

### ISSUE THREAD

**Issue by hal295** [woocommerce/woocommerce#25020]
Please add information about default order count limit which is 10 items.
How can yny developer know about this? I thought it wasn't set. 

Moreover, this example in documentation is confusing:

// Get 10 most recent order ids in date descending order.
$query = new WC_Order_Query( array(
    'limit' => 10,     ... **why if it is default?**
    'orderby' => 'date',
    'order' => 'DESC',
    'return' => 'ids',
) );

Thanks

**Comment by claudiosanches** [comment]
>Please add information about default order count limit which is 10 items.
>How can yny developer know about this? I thought it wasn't set.

Note that `wc_get_orders` and `WC_Order_Query` works like `get_posts` and `WP_Query`, where the default value for `limit` (or `posts_per_page`) comes from your settings (with `get_option( 'posts_per_page' )`).

By default WordPress define as 10, but you can change it going to your WordPress Dashboard > Settings > Reading, and change the value of "Blog pages show at most".

**Comment by claudiosanches** [comment]
Sorry, I forget to mention that it's already documented in https://github.com/woocommerce/woocommerce/wiki/wc_get_orders-and-WC_Order_Query

See:

![Screenshot from 2019-11-13 13-07-44](https://user-images.githubusercontent.com/1264099/68781512-aaa1d080-0616-11ea-8f50-d22050da6ae4.png)
