### ISSUE TITLE
Help improve WooCommerce with usage tracking - message in a pop-up window

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#25022]
**Is your feature request related to a problem? Please describe.**

Setup Wizard / Help improve WooCommerce with usage tracking - message in a pop-up window can be improved:

<img width="611" alt="usage" src="https://user-images.githubusercontent.com/19143190/68667352-af468600-053d-11ea-82ba-9f32f10df8cb.png">

**Describe the solution you'd like**

Learn more about how usage tracking works, and how you'll be helping "here."
Instead of "here," we should use the name of page for transparency purposes.

So should read: Learn more about how usage tracking works, and how you'll be helping at WooCommerce Usage Tracking (URL: https://woocommerce.com/usage-tracking/).

**Describe alternatives you've considered**

If we need to cut some words to fit everything on the same line, I recommend:
Learn more about usage tracking, and how you'll be helping at WooCommerce Usage Tracking(URL: https://woocommerce.com/usage-tracking/).
or
Learn more about Usage Tracking (URL: https://woocommerce.com/usage-tracking/), and how you'll be helping.

**Additional context**

Thanks to @californiakat for raising this issue.

**Comment by rynaldos** [comment]
Nice! Thanks for raising this @juliaamosova. Here is exactly why "here" isn't good: http://stephanieleary.com/2015/05/why-click-here-is-a-terrible-link-and-what-to-write-instead/

**Comment by juliaamosova** [comment]
Thanks for your feedback and for linking the article @rynaldos! Thanks to @californiakat for raising the issue originally.
