### ISSUE TITLE
Allow filtering product held stock when paying for an order with a custom order status

### ISSUE THREAD

**Issue by unfulvio** [woocommerce/woocommerce#25021]
### PR in #25036 

Some customers reached us (SkyVerge) via Etienne in A8C Slack about an issue with WooCommerce Order Status Manager. 

The issue is that some custom order statuses set with Order Status Manager may be flagged to require payment. The order may be put by the merchant in one of these statuses after stock has already been decreased. When the stock is 1, at payment (from My Account > Orders > Pay), the customer may face a message like

>  [Sorry, "%s" is no longer in stock so this order cannot be paid for. We apologize for any inconvenience caused.](https://github.com/woocommerce/woocommerce/blob/3a49e7a53b21b43ab177c93def43fdbb5d4c0178/includes/shortcodes/class-wc-shortcode-checkout.php#L144)

Right above this there is a filter `woocommerce_pay_order_product_in_stock` though, which we could use to check if the order uses an Order Status Manager custom status and skip the check.

However, right a little below, there is another error message they customer would encounter, which is actually pretty similar:

> [Sorry, we do not have enough "%1$s" in stock to fulfill your order (%2$s available). We apologize for any inconvenience caused.](https://github.com/woocommerce/woocommerce/blob/3a49e7a53b21b43ab177c93def43fdbb5d4c0178/includes/shortcodes/class-wc-shortcode-checkout.php#L158)

The difference, I can see, is that the first check evaluates the product's absolute availability; while the latter also checks against any held stock for other pending orders. We have no way though to bypass this.

I was thinking, a filter right above, akin to `woocommerce_pay_order_product_in_stock` which should pass some of those variable, and of course the order and the product.

Alternatively, perhaps, `woocommerce_get_held_stock_quantity()` could be filtered too (but it would provide less context, so I would rather have a filter placed in the context of `WC_Shortcode_Checkout::order_pay()`.

I ran a quick test to see if placing a filter would allow me to get around the reported issue, here's the code I used after forcing a filter in WooCommerce (`$this` is in the context of a WooCommerce Order Status Manager class):

```php
add_filter( 'woocommerce_pay_order_product_in_stock', function( $in_stock, $product, $order ) {

    if ( ! $in_stock &&  $order->has_status( $this->order_needs_payment_statuses() ) ) {
        $in_stock = true;
    }

    return $in_stock;

}, 10, 3 );


// this filter does not exist (yet)
add_filter( 'woocommerce_get_held_stock_quantity', function( $quantity, $product, $exclude_order_id ) {

    if ( $exclude_order_id > 0 && $quantity <= 1 ) {

        $order = wc_get_order( $exclude_order_id );

        if ( $order && $order->has_status( $this->order_needs_payment_statuses() ) ) {

            foreach ( $order->get_items() as $item ) {

                if ( $product->get_id() === $item->get_product()->get_id() ) {

                    $quantity -= $item->get_quantity();
                    break;
                }
            }
        }
    }

    return $quantity;

}, 10, 3 );
```

I was about to submit a PR, but I am not sure what would be the best name of a filter to be placed in https://github.com/woocommerce/woocommerce/blob/3a49e7a53b21b43ab177c93def43fdbb5d4c0178/includes/shortcodes/class-wc-shortcode-checkout.php#L156 since that'd be a bit similar to https://github.com/woocommerce/woocommerce/blob/3a49e7a53b21b43ab177c93def43fdbb5d4c0178/includes/shortcodes/class-wc-shortcode-checkout.php#L142 - and of course hear your opinions.

Thanks!

**Comment by juliaamosova** [comment]
Thank you for opening this issue @unfulvio. We discussed this issue with the WooCommerce core team: 

It seems like there is already a filter in place to bypass the stock check, but there is another one to check the stock vs on hold quantity and this is not able to be bypassed via a filter. In this case, we would say it is OK to add another filter since we already have one to bypass the first stock check.

As far as the name, `'woocommerce_get_held_stock_quantity'` looks like a good name. Please submit a PR as you proposed. If there will be any changes requested, it can be then further discussed with a PR reviewer.

**Comment by unfulvio** [comment]
hey @juliaamosova thanks for the quick reply -- I've added a PR in https://github.com/woocommerce/woocommerce/pull/25036 - I chose to add a filter within the context of `WC_Shortcode_Checkout::order_pay()` only so I could pass the product and order object as well. 

I feel this is more consistent with the `woocommerce_pay_order_product_in_stock` filter right above, and also there's context with an order being paid, whereas `wc_get_held_stock_quantity()` would also be called elsewhere.

**Comment by juliaamosova** [comment]
Great! Thanks for your contribution @unfulvio.
