### ISSUE TITLE
WooCommerce Services requires that the currency is set to US Dollars

### ISSUE THREAD

**Issue by davecarrera** [woocommerce/woocommerce#25038]
Since updating today i have two red bordered errors stating
WooCommerce Services requires that the currency is set to US Dollars
WooCommerce Services requires that the base country/region is the United States.

I am UK based and use Stirling so a bit confused as to why this need to be changed ?

**Comment by claudiosanches** [comment]
Hello, [WooCommerce Services](https://docs.woocommerce.com/document/woocommerce-services/) for now only works in US, so in this case you should disable the WooCommerce Services plugin in the plugins screen on your WordPress dashboard.
