### ISSUE TITLE
New Google error: Either "offers", "review", or "aggregateRating" should be specified

### ISSUE THREAD

**Issue by speek75** [woocommerce/woocommerce#25047]
We have 3 websites (Wordpress) and they all received the same error on the same day Thursday 17th October (Error: Either “offers”, “review”, or “aggregateRating” should be specified)

Does anyone know whats going on and how to fix?

Its on the review product pages post.

**Comment by juliaamosova** [comment]
Thank you for reporting the issue @speek75. We have a PR open that fixes it: https://github.com/woocommerce/woocommerce/pull/24278. 

Closing this issue. Please continue to discuss this in the PR. 

cc @ben72
