### ISSUE TITLE
Persist country from shipping calculator in cart to checkout

### ISSUE THREAD

**Issue by adriandmitroca** [woocommerce/woocommerce#25043]
**Is your feature request related to a problem? Please describe.**
It might be confusing when you are selecting your shipping country on cart page, calculate or even select shipping options and then, it fallback to defaults when you proceed to the checkout.

**Describe the solution you'd like**
Country should be set automatically to the value saved in cart.

**Describe alternatives you've considered**
I am not sure how to deal with other data than country (from what I recall, by default there is also postcode field supported) as I've simplified in my project entire shipping calculator to just country selector.

**Additional context**
I am not sure how this could be added into the core properly, but basically the solution is pretty much straightforward:
```php
add_filter('default_checkout_billing_country', function ($country) {
    return WC()->customer->get_shipping_country() ?: $country;
});
```

**Comment by ObliviousHarmony** [comment]
Hello,

I'm sorry but I don't seem to be able to replicate this! When I enter shipping details on the Cart page, I see that same information on the Checkout page. I tested using the basic storefront theme.

I tried:

- Every option under `WooCommerce Settings > General > Default customer location`
- Every option under `WooCommerce Settings > Shipping > Shipping Options > Shipping destination`
- As registered user and unregistered user
- With and without a stored billing address
- With and without a stored shipping address
