### ISSUE TITLE
html button tag closes with a in class-wc-admin-setup-wizard.php

### ISSUE THREAD

**Issue by ecksite** [woocommerce/woocommerce#25056]
**Describe the bug**
This is rather a little html syntax error, than a bug, but maybe creates some problems.

In [line 602 of /includes/admin/class-wc-admin-setup-wizard.php](https://github.com/woocommerce/woocommerce/blob/05a89e849ebaf57747c1055ebc1b49fdb1229937/includes/admin/class-wc-admin-setup-wizard.php#L602) the html opens a `button` tag but closes with an `a` tag.

**To Reproduce**
1. open `/includes/admin/class-wc-admin-setup-wizard.php` in your IDE
2. jump to `line 602`

**Expected behavior**
a html button tag should start and close with `button`: like this:
```html
<button >...</button>
```

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

### WordPress Environment ###

WC Version: 3.8.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Unix)
PHP Version: 7.3.11
PHP Post Max Size: 512 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1500
cURL Version: 7.52.1
OpenSSL/1.0.2t

SUHOSIN Installed: –
MySQL Version: 5.7.28
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
</details>

**Comment by juliaamosova** [comment]
Thanks for reporting it @ecksite.
