### ISSUE TITLE
Track new order creation without pixel tracking customers

### ISSUE THREAD

**Issue by warrendholmes** [woocommerce/woocommerce#25069]
When a new order is placed via the checkout, we should track that event in tracks for users that have opted in. There should be no tracking of any data of the customer that placed the order.

For this event, we should track :

- Order ID
- Order total
- Order currency
- Order status
- Payment method

I _think_ we'll want to hook in to the **woocommerce_checkout_order_processed** action here https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-checkout.php#L1121

**Comment by kloon** [comment]
Just a note on this, if we use the woocommerce_checkout_order_processed hook we will not be able to get the order status as this hook fires before the order is processed for payment so all order at this point will have a pending status. I will do some investigation to see if there is another hook we can use instead.

**Comment by kloon** [comment]
Had a quick look and I think using the thankyou page hook instead would be better as then we can get the status, check if payment was made and with what payment gateway.

**Comment by claudiosanches** [comment]
Removing from 3.9.0 milestone, since we need to proper enable tracking on the front-end, currently all classes works only in `wp-admin` and it will require some refactor.

**Comment by allendav** [comment]
>  currently all classes works only in wp-admin and it will require some refactor

We just ran into this on the Stripe plugin: https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1264#issuecomment-670200343

We're going to move forward with just wp-admin events for now, but would like to add things like tracking events for orders that complete without admin intervention to a future release of the Stripe plugin:

https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1275

cc @bmccotter

**Comment by peterfabian** [comment]
Hi folks, apologies for the late update. Is this one still relevant/something we should be looking into?

**Comment by vedanshujain** [comment]
Removing the high priority because I am not sure if this is still relevant.

**Comment by pmcpinto** [comment]
I'll close this issue, as we already track some of these data points in the woocommerceanalytics package.
