### ISSUE TITLE
WordPress Admin appearance > menus breaks after upgrade to Woocommerce 3.8.0

### ISSUE THREAD

**Issue by thelar** [woocommerce/woocommerce#25079]
As per title, appearance > menu's is now broken after an upgrade to Woocommerce 3.8

Console is displaying:
```
ReferenceError: columns is not defined nav-menu.js:601:4
    initToggles https://4x4tyres.localhost/wp/wp-admin/js/nav-menu.js?ver=5.3:601
    init https://4x4tyres.localhost/wp/wp-admin/js/nav-menu.js?ver=5.3:66
    <anonymous> https://4x4tyres.localhost/wp/wp-admin/js/nav-menu.js?ver=5.3:1319
    jQuery 4
```

**To Reproduce**
1. Update woocommerce to 3.8
2. Go to Appearance > menus
3. Note that page does not load properly
4. Open console and see error above

**Expected behavior**
I expect to be able to get to my menu admin screen and edit menus

**Isolating the problem (mark completed items with an [x]):**
- I have deactivated Woocommerce and can confirm that the menus admin screen is fine when woocommerce is not active

**WordPress Environment**
WordPress 5.3
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
`
### WordPress Environment ###

WordPress address (URL): https://4x4tyres.localhost/wp
Site address (URL): https://4x4tyres.localhost
WC Version: 3.8.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.37 (Unix) OpenSSL/1.0.2s PHP/7.2.20
PHP Version: 7.2.20
PHP Post Max Size: 300 MB
PHP Time Limit: 9000
PHP Max Input Vars: 1000
cURL Version: 7.65.3
OpenSSL/1.0.2s

SUHOSIN Installed: –
MySQL Version: 5.7.19
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.0
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 62.15MB
Database Data Size: 43.89MB
Database Index Size: 18.26MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.34MB + Index: 0.42MB + Engine InnoDB
wp_fbf_importer_log: Data: 8.52MB + Index: 0.00MB + Engine InnoDB
wp_fbf_rsp_rules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_fbf_rsp_rule_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_fbf_vehicle_manufacturers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.47MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 22.56MB + Index: 8.03MB + Engine InnoDB
wp_posts: Data: 2.52MB + Index: 2.28MB + Engine InnoDB
wp_relevanssi: Data: 1.14MB + Index: 1.65MB + Engine MyISAM
wp_relevanssi_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_relevanssi_stopwords: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.22MB + Index: 0.31MB + Engine InnoDB
wp_terms: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_term_relationships: Data: 2.52MB + Index: 2.52MB + Engine InnoDB
wp_term_taxonomy: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
wp_usermeta: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 1.52MB + Index: 1.75MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.46MB + Index: 0.01MB + Engine MyISAM
wp_wpsdb_alter_statements: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Data: 1.52MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (24) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.8.7
BBC Subscribe: by Kevin Price-Ward – 1.0
Classic Editor: by WordPress Contributors – 1.5
CMS Tree Page View: by Pär Thernström – 1.6
Cron GUI: by Simon Wheatley – 1.03
Dekopay - Bootsgrid WooCommerce Payment Gateway: by  – 1.0 – Not tested with the active version of WooCommerce
4x4 Importer: by Kevin Price-Ward – 1.0.0
4x4 Order Wise: by Kevin Price-Ward – 1.0.0
4x4 RSP Generator: by Kevin Price-Ward – 1.0.0
4x4 Wheel Search: by Kevin Price-Ward – 1.0.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.2
Relevanssi: by Mikko Saari – 4.3.4
SearchWP Live Ajax Search: by Jonathan Christopher – 1.4.4
Simple 301 Redirects: by Scott Nellé – 1.07
User Switching: by John Blackbourn & contributors – 1.5.3
WooCommerce Admin: by WooCommerce – 0.22.0
WooCommerce SagePay Form and SagePay Direct Gateway: by Andrew Benbow – 4.1.2 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.3.1
WooCommerce Multi-currency: by TIV.NET INC – 1.20.0
WooCommerce: by Automattic – 3.8.0
WordPress Admin Style: by Frank Bültge – 1.5.4
Yoast SEO: by Team Yoast – 12.5
WP Sync DB Media Files: by Sean Lang – 1.1.4b1
WP Sync DB: by Sean Lang – 1.5

### Inactive Plugins (4) ###

Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.10.0
Multi Currency for WooCommerce: by VillaTheme – 2.1.4
Wordfence Security: by Wordfence – 7.4.1
WP Google Authenticator: by Julien Liabeuf – 1.1.0

### Must Use Plugins (3) ###

Bedrock Autoloader: by Roots – 1.0.0
Disallow Indexing: by Roots – 1.0.0
Register Theme Directory: by Roots – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #25 - /
Basket: #11 - /basket/
Checkout: #14 - /checkout/
My account: #16 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: 4x4tyres
Version: 9.0.9
Author URL: https://www.chapteragency.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: 4x4tyres/resources/views/woocommerce/archive-product.blade.php
4x4tyres/resources/views/woocommerce/checkout/form-billing.blade.php version - is out of date. The core version is 3.6.0
4x4tyres/resources/views/woocommerce/checkout/form-checkout.blade.php version - is out of date. The core version is 3.5.0
4x4tyres/resources/views/woocommerce/checkout/form-shipping.blade.php version - is out of date. The core version is 3.6.0
4x4tyres/resources/views/woocommerce/myaccount/my-account.blade.php
4x4tyres/resources/views/woocommerce/single-product.blade.php

Outdated Templates: ❌
					
					
						Learn how to update

### sagepay ###

MCrypt: ❌ No
OpenSSL: ✔ Yes
OpenSSL Methods: ✔ Yes
PHP Max_Input_Vars: ❌ Your php_max_inpt_vars value is 1000. If you experience any issues during checkout then increase this value to 5000.
SagePay Form Enabled?: ❌
SagePay Direct Enabled?: ✔

### Multi-currency ###

currency_symbol_CHF: -
currency_symbol_CZK: -
currency_symbol_EUR: -
currency_symbol_GBP: -
currency_symbol_ISK: -
currency_symbol_JPY: -
currency_symbol_SEK: -
currency_symbol_USD: -
enabled_currencies: a:8:{i:0;s:3:"CHF";i:1;s:3:"CZK";i:2;s:3:"EUR";i:3;s:3:"GBP";i:4;s:3:"ISK";i:5;s:3:"JPY";i:6;s:3:"SEK";i:7;s:3:"USD";}
fee_percent: 0
log_level: error
price_charm: 0
price_format_CHF: -
price_format_CZK: -
price_format_EUR: -
price_format_GBP: -
price_format_ISK: -
price_format_JPY: -
price_format_SEK: -
price_format_USD: -
rates: array(168)
rates_provider_id: Currencylayer
rates_retrieval_status: 1
rates_timestamp: 1574179747
round_to: 0.01
version: 1.20.0

### Action Scheduler ###

Complete: 476
Oldest: 2019-10-20 15:31:52 +0100
Newest: 2019-11-20 13:36:35 +0000

Pending: 5
Oldest: 2019-11-20 14:36:35 +0000
Newest: 2019-11-21 12:31:55 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by thelar** [comment]
Apologies, was a third party payment plugin that is causing this issue, not Woocommerce!

**Comment by OiNutter** [comment]
@thelar which plugin was causing the issue as I'm getting the same problem?
