### ISSUE TITLE
Wrong totals in orders with taxable and non-taxable products and percentage coupons

### ISSUE THREAD

**Issue by leanzafrancesco** [woocommerce/woocommerce#25091]
**Describe the bug**
When applying a percentage coupon to a new order created from the backend, the order totals are calculated wrong (if compared to the same items and the same coupon applied to the cart).

**To Reproduce**
To replicate this behavior you should enable and set taxes as follows:
1. Go to **WooCommerce > Settings**
2. Enable Taxes
3. Go to **Tax** tab
4. Set "*Prices entered with tax*" option to "*Yes, I will enter prices inclusive of tax*"
5. Set "*Display prices in the shop*" to "*Excluding Tax*"
6. Set "*Display prices during cart and checkout*" to "*Excluding Tax*"
7. Go to **Standard rates** options
8. Create 2 rates: 
    - Rate: 20% | Priority: 1 | Compound: no
    - Rate: 5% | Priority: 2 | Compound: yes

After setting the taxes you should do the following:
1. Create 3 products:
    - "Test 1": simple product with price = 3.17 and Tax status = Taxable
    - "Test 2": simple product with price = 6.13 and Tax status = Taxable
    - "Test 3": simple product with price = 9.53 and Tax status = None
2. Create a 10% coupon (code: `10percent`)

Steps to replicate the behavior:
1. Go to **WooCommerce > Orders**
2. Click on **Add Order**
3. Click on **Add Item(s)**
4. Click on **Add product(s)**
5. Choose the products previously created (Test 1, Test 2, Test 3) and add them to the order (with quantity = 1 for each of them)
6. Click on **Recalculate**
7. Click on **Apply Coupon**
8. Insert the coupon code previously created (`10percent`)
9. Now you'll see: 
    - the total of the order will be **17.16** (it should be 16.95)
    - the discount will be **1.49** (it should be 1.69)

_see the "Expected behavior" below for details_

**Screenshots and Video**
Order
![order](https://user-images.githubusercontent.com/16973833/69326879-de02e180-0c4c-11ea-9148-81ca2023811c.png)

Cart
![cart](https://user-images.githubusercontent.com/16973833/69326818-be6bb900-0c4c-11ea-8604-4c0fd902e68f.png)

The following video shows the exact replication of this behavior:
[![Watch the video](https://user-images.githubusercontent.com/16973833/69323615-61213900-0c47-11ea-9bdf-89d41e598d3a.png)](https://streamable.com/w7l6m)

**Expected behavior**
If you add the same products (Test 1, Test 2, Test 3) to the cart and apply the same coupon code `10percent` the totals will be:
- Cart Total = 16.95
- Coupon Discount = 1.69

_The cart result is the correct one, since the Subtotal amount is 16.92, so the 10% discount is 1.69._
So, also the order should have the same results:
- Total = **16.95**
- Discount = **1.69**

**Isolating the problem**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

```
### WordPress Environment ###

WordPress address (URL): http://yi-network.test/test
Site address (URL): http://yi-network.test/test
WC Version: 3.8.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.15.12
PHP Version: 7.2.12-1+ubuntu14.04.1+deb.sury.org+1
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.14-MariaDB-1:10.3.14+maria~trusty
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.0
WC Database Prefix: wp_14_
MaxMind GeoIP Database: ✔
Total Database Size: 4.43MB
Database Data Size: 2.79MB
Database Index Size: 1.64MB
wp_14_woocommerce_sessions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_14_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_14_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_14_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_14_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_14_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_14_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_14_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_14_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_14_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_14_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_14_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_14_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_14_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_14_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_14_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_14_faq_termmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_14_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_14_options: Data: 1.02MB + Index: 0.08MB + Engine InnoDB
wp_14_postmeta: Data: 0.47MB + Index: 0.06MB + Engine InnoDB
wp_14_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_14_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_14_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_14_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_14_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_14_tinvwl_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_14_tinvwl_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_14_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_14_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_14_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_14_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_14_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_14_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_14_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_14_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_14_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_14_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_14_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_14_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_blogmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_blogs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_registration_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_site: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sitemeta: Data: 0.16MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.19MB + Index: 0.14MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.8.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.3
Hello Dolly: by Matt Mullenweg – 1.7

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #3 - /
Cart: #4 - /cart/
Checkout: #5 - /checkout/
My account: #6 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Sixteen
Version: 2.0
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 4
Oldest: 2019-10-23 07:18:01 +0000
Newest: 2019-11-21 07:38:36 +0000

Pending: 1
Oldest: 2019-11-28 07:38:36 +0000
Newest: 2019-11-28 07:38:36 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –
```
</details>

**Comment by juliaamosova** [comment]
Thank you for reporting the issue and very detailed steps to reproduce it @leanzafrancesco. 

I can reproduce the behavior described in the report. 

WP-Admin manual order:
<hr>

![order_admin](https://user-images.githubusercontent.com/19143190/69343814-34304e80-0c66-11ea-8bac-fb8c44d7c1b1.jpg)

Site front-end order (cart):
<hr>

![order_cart](https://user-images.githubusercontent.com/19143190/69343833-3beff300-0c66-11ea-949d-90ea2ae13a65.jpg)
