### ISSUE TITLE
unexpected No shipping method has been selected error message

### ISSUE THREAD

**Issue by viva121** [woocommerce/woocommerce#25115]
After updating to 3.8.0 for each order I receive: No shipping method has been selected
I have digital products only, and that is specified  for each of them.
My theme is OceanWP child
In woocommerce settings I have switched off shipping and shipping calculations in WooCommerce/Settings/General.
I have tried switching off all plugins except woo and changing my theme.
Also restored database several days back.
Nothing helped.

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [ ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1.Check out
2.
3.

## Expected/actual behavior

When I follow those steps, I see...
No shipping method has been selected

I was expecting to see...
Redirection to payment gateway

## Isolating the problem

- [ ] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ ] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

WordPress address (URL): https://shop.vita-bio.com
Site address (URL): https://shop.vita-bio.com
WC Version: 3.8.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: ru_RU
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.12
PHP Post Max Size: 5 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2t

SUHOSIN Installed: –
MySQL Version: 5.7.28-1
Max Upload Size: 5 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.0
WC Database Prefix: wp_
Общий размер базы данных: 10.15MB
Размер данных в базе данных: 7.52MB
Размер индекса базы данных: 2.63MB
wp_woocommerce_sessions: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_woocommerce_api_keys: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_woocommerce_attribute_taxonomies: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_woocommerce_downloadable_product_permissions: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wp_woocommerce_order_items: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_woocommerce_order_itemmeta: Данные: 0.05MB + Индекс: 0.03MB + Движок InnoDB
wp_woocommerce_tax_rates: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wp_woocommerce_tax_rate_locations: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_woocommerce_shipping_zones: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_woocommerce_shipping_zone_locations: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_woocommerce_shipping_zone_methods: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_woocommerce_payment_tokens: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_woocommerce_payment_tokenmeta: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_woocommerce_log: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_commentmeta: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_comments: Данные: 0.44MB + Индекс: 0.63MB + Движок InnoDB
wp_failed_jobs: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_links: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_mailchimp_carts: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_mailchimp_jobs: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_options: Данные: 2.08MB + Индекс: 0.08MB + Движок InnoDB
wp_postmeta: Данные: 2.52MB + Индекс: 0.50MB + Движок InnoDB
wp_posts: Данные: 1.52MB + Индекс: 0.38MB + Движок InnoDB
wp_queue: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_termmeta: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_terms: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_term_relationships: Данные: 0.08MB + Индекс: 0.05MB + Движок InnoDB
wp_term_taxonomy: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_usermeta: Данные: 0.05MB + Индекс: 0.03MB + Движок InnoDB
wp_users: Данные: 0.02MB + Индекс: 0.05MB + Движок InnoDB
wp_wc_admin_notes: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wc_admin_note_actions: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_wc_category_lookup: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wc_customer_lookup: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_wc_download_log: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_wc_order_coupon_lookup: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_wc_order_product_lookup: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wp_wc_order_stats: Данные: 0.02MB + Индекс: 0.05MB + Движок InnoDB
wp_wc_order_tax_lookup: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_wc_product_meta_lookup: Данные: 0.02MB + Индекс: 0.09MB + Движок InnoDB
wp_wc_tax_rate_classes: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_wc_webhooks: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_yoast_seo_links: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_yoast_seo_meta: Данные: 0.06MB + Индекс: 0.00MB + Движок InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Ocean Extra: от OceanWP – 1.5.19
Livemesh Addons for Elementor: от Livemesh – 2.8
Ivory Search: от Ivory Search – 4.4.2
Anti-spam: от webvitaly – 5.5
Contact Form 7: от Takayuki Miyoshi – 5.1.5
Elementor: от Elementor.com – 2.7.5
Essential Addons for Elementor: от WPDeveloper – 3.6.0
PayPal Express Checkout Payment Gateway for WooCommerce ( Basic ): от WebToffee – 1.4.0
Google Analytics Dashboard for WP (GADWP): от ExactMetrics – 5.3.9
Post SMTP: от Yehuda Hassine – 2.0.6
Premium Addons for Elementor: от Leap13 – 3.9.0
Text Blocks: от Hal Gatewood – 1.5.3
Sticky Header OceanWP: от Oren Hahiashvili – 1.0.5
WooCommerce Admin: от WooCommerce – 0.22.0
WooCommerce: от Automattic – 3.8.0
Yoast SEO: от Команда Yoast – 12.6
WP Chatbot: от MobileMonkey – 4.3

### Inactive Plugins (5) ###

Mailchimp for WooCommerce: от Mailchimp – 2.3 – Не тестировалось с активной версией WooCommerce
WooCommerce Direct Checkout: от QuadLayers – 2.2.9 – Не тестировалось с активной версией WooCommerce
WooCommerce Direct Checkout PRO: от QuadLayers – 2.1.8 – Не тестировалось с активной версией WooCommerce
WOOCS - WooCommerce Currency Switcher: от realmag777 – 2.3.0 – Не тестировалось с активной версией WooCommerce
Политика конфиденциальности для сайта. Согласие под формами Contact-Form 7: от aleksinsky.ru – 1.28

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Ссылка магазина: #6 - /shop/
Корзина: #7 - /cart/
Оформление заказа: #8 - /checkout/
Мой аккаунт: #9 - /my-account/
Правила и условия: #141 - /terms-conditions/

### Theme ###

Name: OceanWP Child
Version: 1.0
Author URL: https://oceanwp.org/
Child Theme: ✔
Parent Theme Name: OceanWP
Parent Theme Version: 1.7.3
Parent Theme Author URL: https://oceanwp.org/about-me/
WooCommerce Support: ✔

### Templates ###

Overrides: oceanwp/woocommerce/cart/mini-cart.php
oceanwp/woocommerce/content-single-product.php
oceanwp/woocommerce/loop/loop-start.php
oceanwp/woocommerce/single-product/title.php

### Action Scheduler ###

Complete: 975
Oldest: 2019-10-26 12:56:16 +0000
Newest: 2019-11-26 11:26:55 +0000

Pending: 1
Oldest: 2019-11-26 12:26:55 +0000
Newest: 2019-11-26 12:26:55 +0000

Canceled: 2
Oldest: 2019-11-16 11:02:31 +0000
Newest: 2019-11-16 11:02:31 +0000

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

``

</details>

**Comment by juliaamosova** [comment]
Thanks for opening the issue @viva121. However, I can't reproduce it on my end. See screencast below showing that everything works as expected:

https://recordit.co/VM0tO5LJ2C

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only. 

The type of issue you submitted looks like `support request` which may or may not reveal a bug once proper troubleshooting is done. 

To help you troubleshoot the issue you are having, I recommend doing the following:

* Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case
* If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket here](https://woocommerce.com/contact-us/)
* Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

I am closing this issue as it seems to be a support request and not a bug. If I missed something, please leave a comment and I will take a second look.
