### ISSUE TITLE
Incorrect ld+json datalayers for Google rich product snippets

### ISSUE THREAD

**Issue by keesjand** [woocommerce/woocommerce#25111]
Woocommerce out of the box solution for json datalayer rich snippets on
https://themes.woocommerce.com/storefront/product/flying-ninja/ is incorrect.
are not correct:
https://search.google.com/structured-data/testing-tool?hl=nl#url=https%3A%2F%2Fthemes.woocommerce.com%2Fstorefront%2Fproduct%2Fflying-ninja%2F

The product ld+json datalayers should have the review data layer within it:
And the review itself lacks one of these:
offers /review / aggregateRating. Because the reviewRating and ratingvalue is already in, I think best would be to include 'aggregateRating'. 

This will help to get rich snippets in Google. Now it will not!

I assume storefront is on the latest woocommerce version. I know there are supplementary plugins but the all? work with this woo core ld+json so this should be working first.

**Comment by peterfabian** [comment]
Hi, thanks for reporting. 

We already have a fix ready for this (https://github.com/woocommerce/woocommerce/pull/24278) and it will be released soon in a fix release.
