### ISSUE TITLE
Report error : class-wc-cart.php on line 1892 [ 27/11/2019 ]

### ISSUE THREAD

**Issue by juanma386** [woocommerce/woocommerce#25129]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

In the cart sumary
Use Wordpres last version versión 5.3–es_AR
Yith Request Quote Versión 1.5.0
WooCommerce Versión 3.8.0
Php 7.1.33
Server linux CWP Centos 7
Error :

Warning: A non-numeric value encountered in /home/guiacar/public_html/wp-content/plugins/woocommerce/includes/class-wc-cart.php on line 1892

**Comment by juliaamosova** [comment]
@juanma386 thank you for raising the issue. However, it is not clear how to reproduce it? 

So far, I've tried to place an order but no errors were present in my error log. Please provide steps to reproduce the issue. 

>Use Wordpres last version versión 5.3–es_AR
Yith Request Quote Versión 1.5.0
WooCommerce Versión 3.8.0
Php 7.1.33
Server linux CWP Centos 7

Please note that error must be reproducible with just WooCommerce activated running the default [Storefront theme](https://en-gb.wordpress.org/themes/storefront/).

**Comment by juanma386** [comment]
This error not reproduce in the production, need enabled condition debug mode and enable errors report to reproducing fail.

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Julia Amosova<mailto:notifications@github.com>
Enviado: jueves, 28 de noviembre de 2019 07:16
Para: woocommerce/woocommerce<mailto:woocommerce@noreply.github.com>
CC: Juan manuel Pedro Villalba<mailto:xomie_01@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Asunto: Re: [woocommerce/woocommerce] Report error : class-wc-cart.php on line 1892 [ 27/11/2019 ] (#25129)


@juanma386<https://github.com/juanma386> thank you for raising the issue. However, it is not clear how to reproduce it?

So far, I've tried to place an order but no errors were present in my error log. Please provide steps to reproduce the issue.

Use Wordpres last version versión 5.3–es_AR
Yith Request Quote Versión 1.5.0
WooCommerce Versión 3.8.0
Php 7.1.33
Server linux CWP Centos 7

Please note that error must be reproducible with just WooCommerce activated running the default Storefront theme<https://en-gb.wordpress.org/themes/storefront/>.

**Comment by juliaamosova** [comment]
>This error not reproduce in the production, need enabled condition debug mode and enable errors report to reproducing fail.

@juanma386 yes, the debug is enabled on my end: 

```
define('WP_DEBUG', true);
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', true );
```

I have no errors in the debug log. What are the steps to reproduce the issue with just WooCommerce activated?

**Comment by juliaamosova** [comment]
@juanma386 I am closing this issue die to inactivity. If you'd like us to take another look, please leave a comment.
