### ISSUE TITLE
Display incorrect placeholder  for United Kingdom (UK)  in shipping calculator - cart page

### ISSUE THREAD

**Issue by niravcse006** [woocommerce/woocommerce#25152]
**Describe the bug**
The shipping calculator on the cart page first you set any United State country address saved. After that, you can try to change the address from the United State to United Kingdom(UK). So now when you click on the United Kingdom(UK) country you can display below textbox as:
1. Country
2. City
3. Postcode / ZIP

After that when we saved the United Kingdom(UK)  address in shipping calculator and after that when I once again change the United Kingdom(UK) address then it displays below textbox as:
1. State / County
2. City
3 .Postcode / ZIP

So please make sure when we change address from the United State or any other country to United Kingdom(UK) then please change placeholder name "**Country**" to "**State / County**" 

Note: This placeholder display when you change address from another country to the United Kingdom(UK) update.

**To Reproduce**
1. Install fresh Wordpress with latest version
2. Install fresh WooCommerce with latest version
3. Install Storefront default WooCommerce Theme
4. Go to front side visit store and anyone product to "Add To Cart"
5. Go to Cart Page
6. On cart page shipping calculator first set any United State Address and update it.
7. After that change country name United State to United Kingdom(UK)
8. When you click on United Kingdom(UK) then we display textbox with placeholder name "Country" below of the country dropdown.
9. Please this "Country" placeholder name replace to "State / County". 

**Screenshots**
1. https://ibb.co/vq4Hky4
2. https://drive.google.com/file/d/1KLSyH2CtlkAXfCz3mB0jdG50SP6G375p/view

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://regular-hamerkop.jurassic.ninja
Site address (URL): https://regular-hamerkop.jurassic.ninja
WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Unix) OpenSSL/1.0.2g
PHP Version: 7.3.12
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.28-0ubuntu0.16.04.2-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: wp_0f1dcfd096_
MaxMind GeoIP Database: ✔
Total Database Size: 3.54MB
Database Data Size: 2.30MB
Database Index Size: 1.24MB
wp_0f1dcfd096_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_0f1dcfd096_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0f1dcfd096_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_0f1dcfd096_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_0f1dcfd096_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_0f1dcfd096_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0f1dcfd096_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_0f1dcfd096_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0f1dcfd096_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_0f1dcfd096_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0f1dcfd096_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_0f1dcfd096_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_0f1dcfd096_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0f1dcfd096_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_0f1dcfd096_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0f1dcfd096_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_0f1dcfd096_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_0f1dcfd096_options: Data: 1.48MB + Index: 0.06MB + Engine InnoDB
wp_0f1dcfd096_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_0f1dcfd096_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_0f1dcfd096_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0f1dcfd096_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0f1dcfd096_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_0f1dcfd096_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0f1dcfd096_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0f1dcfd096_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_0f1dcfd096_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_0f1dcfd096_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_0f1dcfd096_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_0f1dcfd096_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0f1dcfd096_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0f1dcfd096_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0f1dcfd096_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_0f1dcfd096_wc_order_stats: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_0f1dcfd096_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_0f1dcfd096_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_0f1dcfd096_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_0f1dcfd096_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (7) ###

Companion Plugin: by Osk – 1.11
Jetpack by WordPress.com: by Automattic – 7.9.1
WooCommerce Admin: by WooCommerce – 0.22.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.17 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.3.1
WooCommerce Services: by Automattic – 1.22.1
WooCommerce: by Automattic – 3.8.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.3
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 3
Oldest: 2019-12-02 10:08:56 +0000
Newest: 2019-12-02 10:08:56 +0000

Pending: 1
Oldest: 2019-12-02 11:08:56 +0000
Newest: 2019-12-02 11:08:56 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by juliaamosova** [comment]
Thank you for reporting the issue @niravcse006. I can reproduce it on my end. 

One note on your screenshot - there is no `Country` placeholder - there is `County`:

![county](https://user-images.githubusercontent.com/19143190/70061805-da704280-15dc-11ea-938a-f635b9a5f13e.jpg)

I can see the same on my end after attempting to update the country from the US to the UK:

![county_before](https://user-images.githubusercontent.com/19143190/70062005-2e7b2700-15dd-11ea-89f8-bc4a8bbc0847.jpg)

However, if I click on `Update` button and go back to edit the address again, I see `State / County` placeholder instead:

![county_after](https://user-images.githubusercontent.com/19143190/70062313-b19c7d00-15dd-11ea-92cd-f8994ab4e264.jpg)

With that said, I am not sure what the correct placeholder should be there. If I am not mistaken, the UK doesn't have states. It has [countries](https://en.wikipedia.org/wiki/Countries_of_the_United_Kingdom) and [counties](https://en.wikipedia.org/wiki/List_of_counties_of_the_United_Kingdom) though. 

We will look into the correct placeholder to use when we'd get to work on fixing this issue.

**Comment by jeffstieler** [comment]
Considering the UK is split into Countries and Counties, I don't think adding "State" to the label makes much sense (other than to keep the label consistent in this scenario).

It looks like the root cause of this issue is that `templates/cart/shipping-calculator.php` [hard codes this value as 'State / County'](https://github.com/woocommerce/woocommerce/blob/3611d4643791bad87a0d3e6e73e031bb80447417/plugins/woocommerce/templates/cart/shipping-calculator.php#L50) in a few places.

I think the proper solution is to replace the hardcoded values with data from the country locale. Perhaps using `WC()->countries->get_address_fields()` - getting the value for `['shipping_state']['label']`?
