### ISSUE TITLE
Sale price not showing if set with a datetime

### ISSUE THREAD

**Issue by grosssmutttr** [woocommerce/woocommerce#25155]
**Describe the bug**
We import products and set the following:
    $product->set_regular_price($args['regular_price']);
    $product->set_sale_price(isset($args['sale_price']) ? $args['sale_price'] : '' );
    $product->set_price(isset($args['sale_price']) ? $args['sale_price'] : $args['regular_price'] );
if (isset($args['sale_price'])) {
        $product->set_date_on_sale_from(isset($args['set_date_on_sale_from']) ? $args['set_date_on_sale_from'] : '' );
        $product->set_date_on_sale_to(isset($args['set_date_on_sale_to']) ? $args['set_date_on_sale_to'] : '' );
    }

For example:
$args['regular_price'] = 99
$args['sale_price'] = 69

So if we do the following:
$wc_product = wc_get_product(19225);

var_dump($wc_product->get_price());
var_dump($wc_product->get_sale_price());
var_dump($wc_product->get_regular_price());

The result is:
99
69
99

The datetime is also correctly imported so the backend of the product shows all data (regular_price, sale_price and datetime-span correctly.

If the date has passed as described via the tooltip it should show the sale_price on 00:00 o'clock of the set date - unfortunately it doesn't show the sale price but it shows the sale badge and the price on the product detail page is strikethrough. The problem is that the sale price is the same as the regular price and not the sale price. In the template of the simple product $product->get_price_html() is called to print the regular_price to the left of the sale_price.

Timezone is UTC as it is checked in the system report it should work correctly.

If I simply save the product again in the backend nothing happens and the sale price is still not active and shown.
If I change the sale price date to a day before today (when the sale price should be active) it is shown in the frontend.
If I change it back to today the sale price is still shown and everything works as expected.

So I think there is a cronjob running whether the date is already reached and then it sets something - perhaps there is a datetimezone issue?

**Expected behavior**
The sale price should be displayed after the datetime is reached.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://test.de
Site address (URL): https://test.de
WC Version: 3.7.0
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: ❌ 5.2.4 - Es ist eine neuere Version von WordPress verfügbar (5.3)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.12
PHP Post Max Size: 16 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.38.0
GnuTLS/3.3.30

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.62-0+deb8u1 - Wir empfehlen mindestens MySQL-Version 5.6. Siehe: WordPress-Anforderungen
Max Upload Size: 16 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.7.0
WC Database Prefix: k9n_
MaxMind GeoIP Database: ✔
Datenbank-Gesamtgröße: 237.28MB
Datenbank-Datengröße: 158.11MB
Datenbank-Indexgröße: 79.17MB
k9n_woocommerce_sessions: Daten: 5.02MB + Index: 0.08MB + Engine InnoDB
k9n_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
k9n_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
k9n_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
k9n_woocommerce_order_items: Daten: 1.52MB + Index: 0.42MB + Engine InnoDB
k9n_woocommerce_order_itemmeta: Daten: 9.52MB + Index: 9.02MB + Engine InnoDB
k9n_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
k9n_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
k9n_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
k9n_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
k9n_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
k9n_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
k9n_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
k9n_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
k9n_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
k9n_comments: Daten: 9.52MB + Index: 10.06MB + Engine InnoDB
k9n_imagify_files: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
k9n_imagify_folders: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
k9n_jtl_connector_category_level: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
k9n_jtl_connector_link_category: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
k9n_jtl_connector_link_crossselling: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
k9n_jtl_connector_link_currency: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
k9n_jtl_connector_link_customer: Daten: 0.16MB + Index: 0.27MB + Engine InnoDB
k9n_jtl_connector_link_customer_group: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
k9n_jtl_connector_link_image: Daten: 0.38MB + Index: 0.38MB + Engine InnoDB
k9n_jtl_connector_link_language: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
k9n_jtl_connector_link_manufacturer: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
k9n_jtl_connector_link_measurement_unit: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
k9n_jtl_connector_link_order: Daten: 0.08MB + Index: 0.06MB + Engine InnoDB
k9n_jtl_connector_link_payment: Daten: 0.08MB + Index: 0.06MB + Engine InnoDB
k9n_jtl_connector_link_product: Daten: 0.11MB + Index: 0.08MB + Engine InnoDB
k9n_jtl_connector_link_shipping_class: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
k9n_jtl_connector_link_shipping_method: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
k9n_jtl_connector_link_specific: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
k9n_jtl_connector_link_specific_value: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
k9n_jtl_connector_product_checksum: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
k9n_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
k9n_novalnet_aff_account_detail: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
k9n_novalnet_aff_user_detail: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
k9n_novalnet_callback_history: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
k9n_novalnet_invoice_details: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
k9n_novalnet_subscription_details: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
k9n_novalnet_transaction_detail: Daten: 0.08MB + Index: 0.11MB + Engine InnoDB
k9n_options: Daten: 6.08MB + Index: 0.27MB + Engine InnoDB
k9n_postmeta: Daten: 56.59MB + Index: 39.13MB + Engine InnoDB
k9n_posts: Daten: 41.52MB + Index: 5.84MB + Engine InnoDB
k9n_revslider_css: Daten: 0.13MB + Index: 0.00MB + Engine InnoDB
k9n_revslider_css_bkp: Daten: 0.13MB + Index: 0.00MB + Engine InnoDB
k9n_revslider_layer_animations: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
k9n_revslider_layer_animations_bkp: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
k9n_revslider_navigations: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
k9n_revslider_navigations_bkp: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
k9n_revslider_sliders: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
k9n_revslider_sliders_bkp: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
k9n_revslider_slides: Daten: 4.05MB + Index: 0.00MB + Engine InnoDB
k9n_revslider_slides_bkp: Daten: 3.52MB + Index: 0.00MB + Engine InnoDB
k9n_revslider_static_slides: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
k9n_revslider_static_slides_bkp: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
k9n_termmeta: Daten: 0.03MB + Index: 0.03MB + Engine InnoDB
k9n_terms: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
k9n_term_relationships: Daten: 4.41MB + Index: 2.47MB + Engine InnoDB
k9n_term_taxonomy: Daten: 0.08MB + Index: 0.03MB + Engine InnoDB
k9n_usermeta: Daten: 7.52MB + Index: 8.98MB + Engine InnoDB
k9n_users: Daten: 0.38MB + Index: 0.36MB + Engine InnoDB
k9n_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
k9n_wc_product_meta_lookup: Daten: 0.23MB + Index: 0.45MB + Engine InnoDB
k9n_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
k9n_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
k9n_wplc_chat_msgs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
k9n_wplc_chat_sessions: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
k9n_wplc_offline_messages: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
k9n_wplc_webhooks: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
k9n_yoast_seo_links: Daten: 0.14MB + Index: 0.06MB + Engine InnoDB
k9n_yoast_seo_meta: Daten: 1.48MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (32) ###

CustomOrderFields: von arrangio-online – 1
Adcell Tracking und Remarketing: von Firstlead GmbH – 1.0.10 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce-Bestellexport für Lexware: von Oliver Wagner – 1.0.0 – Nicht getestest mit der aktiven WooCommerce-Version
Bootstrap for Contact Form 7: von Felix Arntz – 1.4.8
Contact Form 7: von Takayuki Miyoshi – 5.1.4
Cookie Notice: von dFactory – 1.2.46
Enhanced E-commerce for Woocommerce store: von Tatvic – 2.2.1
Imagify: von WP Media – 1.9.7
Instagram Feed Pro Personal: von Smash Balloon – 5.1.1
WPBakery Page Builder: von Michael M - WPBakery.com – 6.0.5
Netzspitze Orders with Coupon: von Fabian Keßler | Netzspitze UG – 1.0
Product Slider For WooCommerce: von AccessPress Themes – 3.0.1 – Nicht getestest mit der aktiven WooCommerce-Version
Slider Revolution: von ThemePunch – 6.1.2
User Role Editor: von Vladimir Garagulya – 4.51.3
WooCommerce Cash On Pickup: von Marian Kadanka – 1.5 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce JTL-Connector: von JTL-Software GmbH – 1.8.2.4 – Nicht getestest mit der aktiven WooCommerce-Version
PayPal PLUS für WooCommerce: von Inpsyde GmbH – 2.0.4 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Print Invoice & Delivery Note: von Tyche Softwares – 4.5.2
WooCommerce Sequential Order Numbers: von SkyVerge – 1.9.0
Trustbadge Reviews for WooCommerce: von Vendidero – 3.0.3 – Nicht getestest mit der aktiven WooCommerce-Version
WebInterpret for WooCommerce: von WebInterpret – 2.5.1 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Wholesale Prices Premium: von Rymera Web Co – 1.23.1
WooCommerce Wholesale Prices: von Rymera Web Co – 1.10
WooCommerce: von Automattic – 3.7.0 – 3.8.1 ist verfügbar
WordPress Importer: von wordpressdotorg – 0.6.4
Yoast SEO: von Team Yoast – 12.0
WP Rocket: von WP Media – 3.3.7

### Inactive Plugins (4) ###

Instagram Feed: von Smash Balloon – 1.12.2
Maintenance: von fruitfulcode – 3.7.1
Nelio A/B Testing: von Nelio Software – 4.7.6

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

WP Rocket | Disable Automatic Cache Deletion: von WP Rocket Support Team –

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: #6 - /online-shop/
Warenkorb: #7 - /warenkorb/
Kasse: #8 - /kasse/
Mein Konto: #9 - /mein-konto/
Allgemeine Geschäftsbedingungen: ❌ Seite nicht festgelegt

### Theme ###

Name: test-theme
Version: 1.0.0
Author URL: http://test.de
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Action Scheduler ###

Complete: 2.764
Oldest: 2019-11-02 19:50:07 +0100
Newest: 2019-12-03 09:10:07 +0100

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 29
Oldest: 2019-09-23 15:44:53 +0200
Newest: 2019-11-25 11:03:18 +0100

`
</details>

**EDIT**
Now it happened that if I simply save the product in the backend again everything is showing as expected - now it is 9:34 o'clock - but nothing had happened automatically - cache is not active.
Our timezone is Europe/Berlin

**Comment by claudiosanches** [comment]
It's missing several steps to debug it, I have tested and seems to be working, but maybe it's something on your code, you haven't send the whole code, but when you use `$product->save()`, will run the Product's data store, and both methods `create` and `update` should already clean all cache by default.

Maybe the problem is when you are setting `$product->set_date_on_sale_from( $data )`, see the documentation:

> UTC timestamp, or ISO 8601 DateTime. If the DateTime string has no timezone or offset, WordPress site timezone will be assumed. Null if their is no date.

You also said that the site is on UTC, but your timezone is Europe/Berlin, maybe something related to it.

I'll close since sounds like a problem in the date that was been passed, please post back if you can provide more details, and proper steps to reproduce this data (some sample data, and our settings should help) so I can open it again and help you debug it.

**Comment by Lemondragon** [comment]
I have the exact same issue but using the REST API, as I understand, our problem may have the same cause.

After lots of tests, this is what I found :

You must set the 'from' dates at 00:00:00 in the wordpress installation's timezone.
You must set the 'to' dates at 23:59:59 in the wordpress installation's timezone.

In my case, using the REST API, I must know in that timezone wordpress is configured to know what I should send to it. I was wrongly assuming that sending my date in the **date_on_sale_from_gmt** field was gmt-based and that **date_on_sale_from** was based on the timezone of the installation but both are in the timezone of the installation and there is no difference when setting them via REST.

If the time is not set exactly that way, this is where woocommerce behave unexpectedly. Resulting in what you describe :

> unfortunately it doesn't show the sale price but it shows the sale badge and the price on the product detail page is strikethrough

I am not knowledgeable in woocommerce enough to pinpoint where but it seems like  some part of the logic assumes that the time will be as above by ignoring the 'time' part of the timestamp and some other part use the time exactly as set. Meaning they give a different answer to the question "is it on sale?" trough the day when the time is set any other way. (Should I strike-trough? Yes! Should I use the sale price? No!)

The data you input in the UI is considered to be in the site's timezone. So, if your site's timezone is UTC+1, if you input January 10 in the 'from" date input. Woocommerce will set the time at 00:00:00 on that day, so, the input will actually be January 10 00:00:00 UTC+1. Which is the same as January 9 23:00:00 UTC.

When setting the metadata directly (Via REST API or code), we have to ensure the time is set according to these rules ourselves.

These would work as intended :
-  January 9 23:00:00 UTC
-  January 10 00:00:00 UTC+1
But this would cause the problematic situation during a few hours (But as I have observed, it can even span up to a day even if the time is just one hour off) :
- January 10 00:00:00 UTC+1
- January 10 00:00:00 UTC-5

I did not tested it but I would not be surprised you can also get this behavior if you change the timezone of your site after setting sale dates.

I find it unusual to use timestamps to represent a date if the 'time' part of it can cause unexpected behavior if it is not at one specific time in the site's timezone.
