### ISSUE TITLE
Changing Product author, adding additional emails for Reviews 

### ISSUE THREAD

**Issue by liviujs** [woocommerce/woocommerce#25176]
{Feature Request}
Dear all we have a situation where we need to change the author assigned to a WooCommerce product.

PROBLEM 1: The product author is receiving unwanted notifications when reviews for the product are left. Since we have more then 3K reviews and 3-4 different product authors we need a way to receive this notification into the company email address, and even add some additional emails for this notifications, in order to be able to respond quick in case of a problem or negative review.

I've deepen into this problem and found this solution:
1. https://wordpress.org/support/topic/change-product-author/ from this topic i followed the plugin link that they recommend and the author had exactly the same problem https://wordpress.org/plugins/woo-change-product-author/

PROBLEM 2: We need the option to add more then 1 email for this notifications. Exactly the same way it's possible to do for the out of stock notifications.

**Comment by juliaamosova** [comment]
Thank you for opening a feature request @liviujs. However, what you are looking for is already available by other means. 

>PROBLEM 1: The product author is receiving unwanted notifications when reviews for the product are left. Since we have more then 3K reviews and 3-4 different product authors we need a way to receive this notification into the company email address, and even add some additional emails for this notifications, in order to be able to respond quick in case of a problem or negative review.

You can use the following plugin to change product ownership: 

https://wordpress.org/plugins/change-woocommerce-product-author/

>PROBLEM 2: We need the option to add more then 1 email for this notifications. Exactly the same way it's possible to do for the out of stock notifications.

You can use the following snippet to override the recipient of the review notification:

```
function new_comment_moderation_recipients( $emails, $comment_id ) { 
    return array( 'example@example.com' );
}
add_filter( 'comment_moderation_recipients', 'new_comment_moderation_recipients', 24, 2 );
add_filter( 'comment_notification_recipients', 'new_comment_moderation_recipients', 24, 2 );
```

In this snippet, change `example@example.com` to the email you'd like to use for review notifications. 

Finally, you can manage reviews via WooCommerce / Comments section - every time a new review is posted, you'd get a notification there as well - you can then approve and reply further. You'd need to make sure your settings are configured for the reviews / comments to require approval as shown on the screenshot below:

![review](https://user-images.githubusercontent.com/19143190/70432694-c5316300-1a77-11ea-82ab-113275af7d82.jpg)

There is no action for us to take, therefore, I am closing this issue.
