### ISSUE TITLE
Ghost Order (Manual) - missing product stock

### ISSUE THREAD

**Issue by AashikP** [woocommerce/woocommerce#25212]
**Describe the bug**

While creating a manual order, if you accidentally close tab (after adding a product), you'll notice that the stock has reduced, but the order cannot be found

**To Reproduce**
1. Enable Stock management
2. Create a manual order and add your product - notice the order note that denotes the reduced stock
3. Close tab (Do not create the order itself)
4. When you get back to the Dashboard, you'll see that the order is missing, and the stock count has reduced

**Screenshots**

![https://d.pr/i/EiA1mU+](https://d.pr/i/EiA1mU+)

![https://d.pr/i/6Quxoy+](https://d.pr/i/6Quxoy+)

![https://d.pr/i/FVkXmQ+](https://d.pr/i/FVkXmQ+)

**Expected behavior**

Do not reduce stock before an order is created.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Any

**Comment by juliaamosova** [comment]
@AashikP thanks for reporting the issue. I can reproduce it on my end:

- Created manual order without saving it:

![order1](https://user-images.githubusercontent.com/19143190/70710268-b1d00300-1cd6-11ea-8d9a-99cd661c284f.jpg)

- Navigated back to see if the stock of the product got reduced - and yes, it was reduced without order being created:

![order2](https://user-images.githubusercontent.com/19143190/70710312-c7ddc380-1cd6-11ea-893f-7002f0734ea4.jpg)

**Comment by AashikP** [comment]
Another report in 2610527-zen.

**Comment by arunsathiya** [comment]
2822321-zen

**Comment by jacoswan** [comment]
23025979-hc

**Comment by vedanshujain** [comment]
This was fixed by #26642 which is included in 4.4 beta.
