### ISSUE TITLE
Missing paragraph closing HTML tag in Customer Reset Password email

### ISSUE THREAD

**Issue by starypop** [woocommerce/woocommerce#25226]
**Describe the bug**
There is a missing `</p>` closing tag in /templates/emails/customer-reset-password.php file on line 27.

`<p><?php printf( esc_html__( 'Hi %s,', 'woocommerce' ), esc_html( $user_login ) ); ?>`

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Thanks for reporting the issue @starypop. 

The place where it needs to be corrected is here:

https://github.com/woocommerce/woocommerce/blob/master/templates/emails/customer-reset-password.php#L27
