### ISSUE TITLE
http in schema

### ISSUE THREAD

**Issue by ditad** [woocommerce/woocommerce#25224]
In woocommerce/includes/class-wc-structured-data.php:

`'availability' => 'http://schema.org/' . ( $product->is_in_stock() ? 'InStock' : 'OutOfStock' ),`

http must be https

**Comment by juliaamosova** [comment]
Thanks for reporting the issue @ditad. 

The place where it needs to be corrected is here:

https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-structured-data.php#L262

**Comment by claudiosanches** [comment]
With HTTPS causes issues for validate, see more details on https://github.com/woocommerce/woocommerce/issues/23798

Closing since we can't use HTTPS on it schema.

cc @juliaamosova
