### ISSUE TITLE
Remove "alas" from cancelled email text

### ISSUE THREAD

**Issue by EdithAllison** [woocommerce/woocommerce#25244]
In the cancelled email, the text says:

`echo sprintf( esc_html__( 'Alas. Just to let you know &mdash; order #%1$s belonging to %2$s has been cancelled:', 'woocommerce' ), esc_html( $order->get_order_number() ), esc_html( $order->get_formatted_billing_full_name() ) ) . "\n\n";`

The word "alas" is confusing to non-English speakers. It's not commonly used and non-native speakers don't understand what it means. A real query from my client was "Who is 'Alas'? Why does he appear on every email?"

I recommend to rename to something easier to understand, maybe "What a pity", "What a shame" , "Sorry" or  simply to remove without replacement.

**Comment by juliaamosova** [comment]
Hi @EdithAllison,

Thank you for opening this enhancement request! Being a non-native English speaker myself, I share the same feeling about the word `Alas` in our cancellation emails. I agree with you that it can be simply removed or changed to `Sorry!`. 

@californiakat may I ask you to provide your feedback here on what you think will be best to replace it with?

**Comment by californiakat** [comment]
> Who is 'Alas'? Why does he appear on every email?"
 Haha! :) I totally see your client's point. And it's pretty uncommon in native English as well.

>I recommend to rename to something easier to understand
I agree. Why not remove 'Alas' and leave it plain.

A few choices:

Just to let you know order...
or 
Notification to let you know order...
or 
Notification that order ...

**Comment by michaelignacio** [comment]
I agree with the comments above and I'd like to take this on :) Will submit the changes in a bit
