### ISSUE TITLE
Product sort by price in admin returns random order instead of order by price. 

### ISSUE THREAD

**Issue by conschneider** [woocommerce/woocommerce#25245]
**Describe the bug**
Sorting products in admin via price gives random sort order. Products are not sorted by price. 

**To Reproduce**
Visit WP Admin > WooCommerce > Products
Click price column to order by price.

**Screencast**
http://recordit.co/tbbXjwZ8iV

**Expected behavior**
When I follow those steps, I see the products in a random order, not ordered by price.
I was expecting to see the list of products in descending or ascending price order.

This has been reported before: https://github.com/woocommerce/woocommerce/issues/16708 - had a chat today with someone. I was able to reproduce on two local installations. Ruled out conflict. 

Happy to do further testing, let me know. 

**Isolating the problem (mark completed items with an [x]):**
- [✅] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [✅] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [✅] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): http://wooprs.local
Site address (URL): http://wooprs.local
WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.14.0
PHP Version: 7.2.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.7.23
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 2.82MB
Database Data Size: 1.78MB
Database Index Size: 1.04MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_hook_list: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.06MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.8.1

### Inactive Plugins (15) ###

Classic Editor: by WordPress Contributors – 1.5
Debug Objects: by Frank Bültge – 2.5.0
Debug Toolkit: by hellofromTonya – 1.0.1
Easy Theme and Plugin Upgrades: by Chris Jean – 2.0.1
Really Simple SSL: by Rogier Lankhorst
Mark Wolters – 3.2.7

User Switching: by John Blackbourn & contributors – 1.5.3
WooCommerce GoCardless Gateway: by WooCommerce – 2.4.12 – Not tested with the active version of WooCommerce
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.10 – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.18
WooCommerce Pre-Orders: by WooCommerce – 1.5.17 – Not tested with the active version of WooCommerce
WooCommerce Product Generator: by itthinx – 1.1.1 – Not tested with the active version of WooCommerce
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.2 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.3.1
WooCommerce Subscriptions: by Automattic – 2.6.2 – Not tested with the active version of WooCommerce
Woo Marketplace List: by conschneider – 0.1 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 10
Oldest: 2019-11-28 11:50:38 +0000
Newest: 2019-12-17 12:27:54 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by juliaamosova** [comment]
Hi @conschneider,

Thanks for raising this issue! However, I can't reproduce it on my end. I've tried on 2 sites:

- Brand new Jurassic Ninja site
- My Pressable test site

It works as expected on both sites:

**My Pressable test site - screencast:** 

http://g.recordit.co/NOCLHf2qU6.gif

**Brand new Jurassic Ninja site:**

Low to High sorting:

![sorting_low_to_high](https://user-images.githubusercontent.com/19143190/71411188-4c6a0380-2640-11ea-9416-0f9c82a78614.jpg)

High to Low sorting:

![sorting_high_to_low](https://user-images.githubusercontent.com/19143190/71411191-525fe480-2640-11ea-9915-2572a0cf859e.jpg)

I wonder if it could be related to how the products were created? Maybe some of your products are created using extensions?

**Comment by madeincosmos** [comment]
Similar to @juliaamosova , I can't reproduce the same problem on any of my test sites. 

@conschneider product sorting order is determined based on the lookup tables, can you please go to **WooCommerce > Status > Tools**, regenerate the lookup tables and see if it helps? If it doesn't, there might be a problem with cron or Action Scheduler.

**Comment by orenhavshush** [comment]
I have the same issue, order by price (backend and Frontend) sort it in random order

**Comment by conschneider** [comment]
Thanks for taking a look @juliaamosova so quickly and testing. 
Thanks for the suggestion @madeincosmos . 

The products were indeed created via a plugin: https://github.com/itthinx/woocommerce-product-generator. 

Regenerating the lookup tables fixed it for me. 

I will keep this in mind for future incidents. With so many ways of adding products to the database there is likely to be more scenarios where this happens and can be fixed via: WooCommerce > Status > Tools > Product lookup tables. 
Closing.
