### ISSUE TITLE
Make woocommerce_email_headers filter usage consistent.

### ISSUE THREAD

**Issue by JacobMC** [woocommerce/woocommerce#25268]
**Is your feature request related to a problem? Please describe.**
It appears that the `apply_filters` gets called on `woocommerce_email_headers` four times in WooCommerce core:

- `woocommerce/includes/emails/class-wc-email.php:420`
- `woocommerce/includes/class-wc-emails.php:620`
- `woocommerce/includes/class-wc-emails.php:643`
- `woocommerce/includes/class-wc-emails.php:681`

Each time it is called, 3 parameters are passed. In 3 out of 4 of the calls, the third parameter is an object.

The last time it is called (`class-wc-emails.php:681`) (line 681) the third parameter passed is an array _instead_ of an object. This is inconsistent and unusual behavior for a filter.

**Describe the solution you'd like**
I would like for either all four calls to `apply_filters` on `woocommerce_email_headers` to use an object as the third parameter or for the last call (`class-wp-emails.php:681`) to use a different filter.

**Describe alternatives you've considered**
My current solution is run type-checks on the third parameter when filtering `woocommerce_email_headers`.

I'd be happy to work on this and submit a PR, but I don't know what implementation would be best at this point or if there are other alternatives. Also, maybe I'm the only person who cares about hook consistency and this is a non-issue.

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #25312.
