### ISSUE TITLE
customer-logout endpoint fails to redirect correctly

### ISSUE THREAD

**Issue by diablodale** [woocommerce/woocommerce#25288]
Woo's custom customer logout fails to redirect to the specified URL after logout.
Through code review I identified there is both

* an errant approach to specifying and processing post-logout redirects
* errant code which ignores the attempt to specify a redirect and instead always redirects to the page named 'myaccount'

This is related to https://github.com/woocommerce/woocommerce/issues/24243#issuecomment-559162421

## Setup

* Ubuntu 18.04.3
* Apache 2.4.38
* PHP 7.3.12
* Wordpress 5.3.2
* Woocommerce 3.8.1
* Setup Woo using the Wizard with basic -- no addons/plugins, no jetpack, etc.

## Repro

Errant behavior can be seen with similar to the following:

1. Add a filter for `woocommerce_logout_default_redirect_url` and make that filter function always `return home_url();`
2. Visit your website and log into an account
3. Visit the custom Woo "My Account" page
4. Hover over (don't click) Woo's link on the left for logout.

Notice that the URL is based on `/` and appends on it the endpoint for `customer-logout`. For example, without prettylinks, it will look like `https://myserver/?customer-logout&_wpnonce=1234567890`. **_This is the errant approach for redirect support._**

The `home_url()` redirect specified has instead been used as a base URL on which an endpoint was placed. I can think of many scenarios where this will fail to both logout and fail to redirect with URLs to other websites, query params, fragments, ports, etc. 

More repro steps...

1. Click on that logout link

## Result

The user is redirected to the "My Account" page, e.g. without pretty links it is `https://myserver/?page_id=9`

## Expected

Redirect to `home_url()` as was specified. 

## Notes

I don't have an immediate global fix because these errors are both in approach and in specific code. I believe the core team needs to consider how they want to approach redirects on endpoints like logout. With that choice, then specific code can be changed or written.

### Errant approach

The errant approach scatters itself within Woo's code. Here is one example of misusing base URL as a redirect.

https://github.com/woocommerce/woocommerce/blob/aa590c8acd7b2c61327af9abefe446d14125a6fe/includes/wc-template-functions.php#L3486

At that code, the intention is to logout and then redirect to an URL. However, the function used for that intention does not create an URL that later results in a redirect. Instead, the function called creates an URL on which an endpoint is placed on a base URL (worded as a permalink in the params).

https://github.com/woocommerce/woocommerce/blob/aa590c8acd7b2c61327af9abefe446d14125a6fe/includes/wc-page-functions.php#L87

Just a few redirects URLs that will cause failure to logout and/or redirect correctly

```
https://mysameserver:1234/
https://remoteserver/
https://username:password@remoteserver.com/path/something?foobar=67#fragment12
```

### Specific errant hardcoded redirect

There is also a specific code bug that causes Woo to always ignore the desired redirect on logout. Instead, Woo will always redirect the customer to the "My Account" page

https://github.com/woocommerce/woocommerce/blob/aa590c8acd7b2c61327af9abefe446d14125a6fe/includes/wc-template-functions.php#L35

Two problems here

1. The errant approach discussed above is also here.
2. The filter `woocommerce_logout_default_redirect_url` should be applied to the default on that line of code. One place this was correctly done and you can copy the filter is at https://github.com/woocommerce/woocommerce/blob/aa590c8acd7b2c61327af9abefe446d14125a6fe/includes/wc-template-functions.php#L3483

## Isolating the problem (mark completed items with an [x])

- [] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] I have deactivated other plugins **_not needed to reproduce this bug_** and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

```
### WordPress Environment ###

WordPress address (URL): https://**redacted**
Site address (URL): https://**redacted**
WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 150 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.38
PHP Version: 7.3.12
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.34-MariaDB-1~bionic
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 1.75MB
Database Data Size: 0.75MB
Database Index Size: 1.00MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.13MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Secure DB Connection: by Xiao Yu – 1.1.5
** redacted, this plugin adds the code/filter to expose Woo's errant behavior **
WooCommerce: by Automattic – 3.8.1

### Inactive Plugins (19) ###

** redacted **

### Dropin Plugins (1) ###

db.php: Secure DB Connection

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /?page_id=6
Cart: #7 - /?page_id=7
Checkout: #8 - /?page_id=8
My account: #9 - /?page_id=9
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Eleven
Version: 3.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2019-12-20 19:48:47 +0000
Newest: 2019-12-20 19:48:47 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –
```
</details>

**Comment by claudiosanches** [comment]
> At that code, the intention is to logout and then redirect to an URL. However, the function used for that intention does not create an URL that later results in a redirect. Instead, the function called creates an URL on which an endpoint is placed on a base URL (worded as a permalink in the params).

Thanks for debugging it, when I introduced that new filter I have only checked the variable names and didn't checked that it never worked as indented when using custom endpoints.
