### ISSUE TITLE
[E2E] Fix warnings that come up when building Docker container to run e2e tests

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#25299]
The following warnings come up after running `docker-compose up` to build the container:

```
wordpress-cli_1             | Warning: Unable to create directory wp-content/uploads/2019/12. Is its parent directory writable by the server?
wordpress-cli_1             | [23-Dec-2019 16:42:12 UTC] PHP Warning:  copy(/var/www/html/wp-content/uploads/woocommerce-placeholder.png): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-install.php on line 1220
wordpress-cli_1             | Warning: copy(/var/www/html/wp-content/uploads/woocommerce-placeholder.png): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-install.php on line 1220
```

![Screen Shot 2019-12-23 at 4 46 52 PM](https://user-images.githubusercontent.com/19143190/71369829-dadc7780-25a3-11ea-8f59-d3f55f798841.png)

It looks like a user of the container permission issues. We will likely run into issues when need to test uploading files to the site. 

**UPDATE (December 24, 2019):**

I see the error indeed when trying to upload a CSV file on the site built in the Docker container:

![Screen Shot 2019-12-24 at 11 16 32 AM](https://user-images.githubusercontent.com/19143190/71410892-fd6f9e80-263e-11ea-8c89-5a242d66cc6e.png)

**Comment by nerrad** [comment]
I thought I had a solution for this but it wasn't reliable so I had to abandon it. I thought I'd document my findings so far and potential solutions:

## The problem

- When mounting the woocommerce core volume, the owner:group in the WordPress container for `wp-content` is `root:root` (along with the WC folder in `wp-content`).
- There's two problems with the `wp-cli` container being linked: 1.  It runs as `www-data` user so it doesn't have write access to the `wp-content` folder; 2. There is a known issue where the UID/GID for `www-data` on the wp-cli container is different than that in the `wordpress` container (https://github.com/docker-library/wordpress/issues/256).

## Potential solutions.

- I made various attempts to try and change ownership (via `chown` in the docker configuration files) and while it appeared to work across multiple `docker-compose up` and `docker-compose down` with volumes _already mounted_, it wasn't stable enough to use as a solution.
- We could look at just setting up wp-cli in the `wordpress` container and configure and run an `entry-point` script that does the initial WordPress setup and configuration of plugins etc. For extensibility we could have the entry-script pull in custom scripts provided by other plugins using this process (woo and woo-admin would use that).

I hope to try and do some more work on this before the end of the week but just thought I'd document where I got so far in case I can't resume for now.

**Comment by nerrad** [comment]
**Update**:

This one was bugging me so I gave another go at it this weekend and I think I have a fix. I'm going to publish it in the Blocks repository first and make sure it works in travis builds etc. Once that's verified, I have some ideas about how the WooCommerce core package version of this could be flexible for both WooCore and Woo extensions (including the ability to include arbitrary plugins/themes in the e2e environment - as well as from specific branches).

**Comment by nerrad** [comment]
Here's a pull with a fix in the blocks repository: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/1716. Note the follow ups in the pull description, I think they'd apply to what we'd want to see in a published package (specific to woo testing environment). Since the `wc-admin` repository is already being used as a monorepo for publishing `@woocommerce` namespaced WC npm packages, I think we should consider publishing any Woo e2e utils and docker testing environment from that repository as well (p2 post will be coming on general package publishing soon).

**Comment by juliaamosova** [comment]
Closing this issue. Fixed by https://github.com/woocommerce/woocommerce/pull/26109.
