### ISSUE TITLE
WP Nonce checks fail on admin post for anonymous users with items in the cart.

### ISSUE THREAD

**Issue by JBossSimplistics** [woocommerce/woocommerce#25301]
I'm not 100% sure what the expected behaviour is here. I noticed the problem on my woocommerce site when a form submission action was failing to update important data. After some testing I realized its because the nonce check was failing in some cases. To be clear, the form uses:

`wp_nonce_field( NONCE_ACTION, NONCE_NAME );`

It submits to admin_post. So that I have a function that processes the POST request like:

```
add_action( 'admin_post_form_submission', function(){
    if( ! wp_verify_nonce( $_POST[ NONCE_NAME ], NONCE_ACTION ) ){
        exit;
    }
});
```

Now this form gets used by NON logged-in users. When a user has an empty cart, everything is fine. But for anonymous users who have added items to their cart, this nonce check fails. The reason is the function nonce_user_logged_out ( class-wc-session-handler.php:292 ). When the nonce is created for display on the form - that function fires on the filter 'nonce_user_logged_out' to ensure a unique nonce for each customer. The problem is that the filter is never added on admin_post. So when the nonce check is fired, the user ID being used to check the nonce is empty. 

The result is that the nonce calculated on the form and the nonce calculated in admin_post are different, and a nonce check never passes on admin post for an anonymous user with items in their cart. 

My current fix for this has been:

```
add_action( 'admin_post_form_submission', function(){
    wc_load_cart();
    if( ! wp_verify_nonce( $_POST[ NONCE_NAME ], NONCE_ACTION ) ){
        exit;
    }
});
```

That seems to add this filter back, in WC_Session_Handler->init(). I can imagine a lot of places this could be a problem. admin_post actions can be used to process forms for all users. Please let me know if I can provide any more info, or if I'm missing something here and this is intended behaviour.

Cheers.

**Comment by juliaamosova** [comment]
Hi @JBossSimplistics,

Thank you for reporting the issue. Can you please provide steps to reproduce the issue in order to see the error at the front end of the site? Please include:

- What actions do you take as a user at the front end?
- What happens when you take these actions?
- What do you expect to happen instead?

**Comment by JBossSimplistics** [comment]
Hi Julia,

Sorry - not sure what you're looking for beyond the description above? I think its pretty specific:

What actions do you take as a user at the front end?
- Submit any form that goes to an admin post action that uses a nonce check, while the following 2 things are true:
1. You're not logged in
2. You have items in your cart

What happens when you take these actions?
- The nonce check fails. It fails because the nonce calculated on the frontend is filtered by woocommerce, but in admin post, it is not.

What do you expect to happen instead?
- I would expect that the nonce check would work for admin posts, without putting that burden on the developer. I pasted the line of code that I used to solve this problem above: wc_load_cart(). That adds back the hook needed to check against the nonce correctly, but that shouldn't required by the developer using Woocommerce.

Hope that provides some extra details?

**Comment by ObliviousHarmony** [comment]
In my testing I wasn't actually able to trigger the `admin_post_{{action}}` action at all for a logged-out user (it is after all an "admin" post request!) WordPress provides an `admin_post_nopriv_{{action}}` action that is supposed to be used in this case. 

Ignoring that slightly confusing aspect of your issue report, it's possible you're encountering the bug described in #23682. If that is the case, we're currently looking at the possible solutions, and will keep that issue updated. If you agree this to be the same issue that you're experiencing, we can go ahead and close this as a duplicate.

**Comment by JBossSimplistics** [comment]
Hey Christopher,

Yes so to answer your first item above - you're correct my original post should have shown 'nopriv_' in that action, you're right.

That aside, I took a look at the post above, and yes - looks like its the same root issue causing this. The comment by tylerdigital sums it up very well I think: the problem is that adding items to your shopping cart triggers nonce_user_logged_out for cart session purposes. But that filter doesn't fire in admin_post_nopriv, and so a nonce check fails. I'll leave it to you - not sure if this post offers additional context.

It looks like the issue has existed for awhile, and is clearly related here, so if you'd like to close this one off no worries.

Thanks for the response.

**Comment by juliaamosova** [comment]
Thanks for the additional feedback @JBossSimplistics! We are closing your issue in favor of https://github.com/woocommerce/woocommerce/issues/23682 which was submitted previously. Please continue the discussion there if needed.
