### ISSUE TITLE
jquery-ui.min.css not found

### ISSUE THREAD

**Issue by witcher83** [woocommerce/woocommerce#25313]
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [X ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [X ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. On a fresh installation i did the clone of WooCommerce repository and i followed the steps described here https://github.com/woocommerce/woocommerce/wiki/How-to-set-up-WooCommerce-development-environment
2. In the browser console i have the follwing message:
GET http://gdprdev.com/wp-content/plugins/woocommerce/assets/css/jquery-ui/jquery-ui.min.css?ver=3.9.0 net::ERR_ABORTED 404 (Not Found)

## Expected/actual behavior

The installation has SCRIPT_DEBUG enabled so, all unminified files should be loaded but in the file 
wp-content/plugins/woocommerce/includes/admin/class-wc-admin-assets.php:40 i see that the plugin is set to load the minified file in any case.

Launching `grunt assets` again does not solves the issue

## Isolating the problem

- [X ] This bug happens with only WooCommerce plugin active
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [X ] I can reproduce this bug consistently using the steps above

**Comment by witcher83** [comment]
i forgot to specify the WooCommerce version: 3.9-RC1

**Comment by claudiosanches** [comment]
This got removed by mistake on https://github.com/woocommerce/woocommerce/pull/25074
Thanks for let us know about this issue.
