### ISSUE TITLE
Filter hook to modify product download URL based on order data

### ISSUE THREAD

**Issue by pstiefel** [woocommerce/woocommerce#25336]
**Background info**
We are selling software with WooCommerce. Our product download URLs redirect customers to our external licensing service to create a custom license file for each product/order. To identify the customer and his order we need to insert data from the order into the product download (redirect) URL.

We implemented this by adding a new filter hook into function download_product in class-wc-download-handler.php. We now use placeholders in the product download URL and replace them with data from the actual order when a customer clicks the download link.

**Preferred solution**
Please add a new filter hook to modify the $file_path (product download URL) based on customer/order data.
Suggestion: 
On line 83 of class-wc-download-handler.php (function download_product) add the new filter woocommerce_download_product_filepath.
```
$file_path        = $product->get_file_download_path( $download->get_download_id() ); 
$file_path = apply_filters('woocommerce_download_product_filepath', $file_path, $email_address, $order, $product, $download);
$parsed_file_path = self::parse_file_path( $file_path );
```
(Only the line in the middle is new, the surrounding lines are provided for context.)
**EDIT 20191230:** We don't need it yet, but for completeness $product and $download should also be arguments of the hook. /EDIT 

**Alternatives considered**
We researched and evaluated a lot of related existing hooks (all of them, I believe). There is none that is suitable to implement our requirement.

The nearest misses were:
Filter woocommerce_file_download_filename – This does not supply data on the customer/order which is required for our purpose.
Action woocommerce_download_product - This supplies data but does not allow to change the $file_path of the product download.

**Comment by trocotronic** [comment]
I have the same problem. I need to modify the file to download based on the order, but `woocommerce_download_product_filepath` only provides `download_key`, `file_path` and `product`. It would be cumbersome to have this information in the hook.

**Comment by claudiosanches** [comment]
Thank you for suggesting this feature!

I'm closing the issue as it already has a PR, please continue the discussion over at #25485.
