### ISSUE TITLE
Customizer options: default columns and rows value is not picked up from the theme support setup

### ISSUE THREAD

**Issue by webmandesign** [woocommerce/woocommerce#25332]
**Describe the bug**
When declaring a WooCommerce support in a theme with a code such as:
```php
<?php

add_theme_support( 'woocommerce', array(
	'single_image_width'    => 600,
	'thumbnail_image_width' => 300,
	'product_grid' => array(
		'default_columns' => 3,
		'min_columns'     => 2,
		'max_columns'     => 5,
		'default_rows' => 3,
		'min_rows'     => 2,
		'max_rows'     => 8,
	),
) );
```

And then visiting **Appearance &rarr; Customize &rarr; WooCommerce &rarr; Product Catalog**, the values "Products per row" and "Rows per page" are set to `4` instead of the default values set via theme with the code above (should be `3` in our example).

**Expected behavior**
Customization options should pick up default values set via `add_theme_support( 'woocommerce', $args );`.

**Comment by claudiosanches** [comment]
This is already done while you change themes, see: 

https://github.com/woocommerce/woocommerce/blob/7701d4b57cb20dc89e25bb7bf2ff872d85f4c535/includes/wc-template-functions.php#L391-L409

Trying to reproduce your steps, seems like you are including it into a theme when your theme is already enabled.

**Comment by webmandesign** [comment]
Well, this is all good. But how does it work when a theme is activated and only then a plugin is activated? Does it even pick up the theme's settings from code? It seems not, at least not for me.
