### ISSUE TITLE
Add a custom table for customers

### ISSUE THREAD

**Issue by jellyNoone** [woocommerce/woocommerce#25349]
I'm developing a site and will use WooCommerce as the backbone of a multivendor store front. 

To comply with the law I have to generate receipts to my vedors. To do this I made a custom table called Entities and store the data of the vendors in there. When going through the database I saw that orders are stored in the posts table and postsmeta table is used to store customer details for every order. I've seen threads about this issue but the one I read was from 2016. 

My proposal is this, and please tell me if my thinking is wrong. Create a similar table to store the customer data, save the id of the user if the user is loged in in the table. If it turns out that at checkout there were no changes to the data leave it as is and add save the ID of the lets call it Entity in the posts meta for the order. 

If however data changes a new row can be added for the new changes and this becomes the new "main_entity" of the logged in user.  WooCommerce I think also stores the customer information to the usermeta I think, this way only a single reference to the entity could be used. If at any point the user would start using a same address as before you could just point the "main_entity" to the old ID.

If the user is not logged in, a row can still be added to the table, just omit the user_id.

I don't know the legal implications of this since you'd be tracking the users addresses  during their entire usage of your website. But could maybe provide data for a potential fraud protection system(a bit far fetched).

I've only been a serious programmer for about a year and so I don't really know if there are any performance benifits to a system like this over the current one.

**Comment by claudiosanches** [comment]
>My proposal is this, and please tell me if my thinking is wrong. Create a similar table to store the customer data, save the id of the user if the user is loged in in the table. If it turns out that at checkout there were no changes to the data leave it as is and add save the ID of the lets call it Entity in the posts meta for the order.
> If however data changes a new row can be added for the new changes and this becomes the new "main_entity" of the logged in user. WooCommerce I think also stores the customer information to the usermeta I think, this way only a single reference to the entity could be used. If at any point the user would start using a same address as before you could just point the "main_entity" to the old ID.

In fact if it's a registered user should save the address on `usermeta`, and in orders it's saved the address for registered and non-registered customers, because a customer may change his/her address after an order is placed, so we can't use always only the address from `usermeta`, to comply with laws cross over the world we need to keep the address of the order details for a time in the database.

**Comment by jellyNoone** [comment]
Yes I understand that, but if a user doesnt change their address for lets say 5 orders you would be able to save what around 10 * 5(rows being saved now) - 1(one row in a new table) 49 rows if the user doesn't change their address, but if they do you just add a new row to the table and add the ID of that new address to the order. You don't change the existing address you add a new one. This way you could also at some point display these settings to a registered user if they use lets say two different addresses to choose which one to ship to when they make a new order. I think this would be a nicer way of tracking user information.

Also a bit unrelated.. At checkout a user can pass in a great deal of text for their name, lastname... etc. Since the date is saved as meta_value which is the datatype of longtext, a new table could allow us to change this to a smaller datatype.
