### ISSUE TITLE
Overriding data store 'product' breaks display of variations in wp-admin. 

### ISSUE THREAD

**Issue by FiniteSource** [woocommerce/woocommerce#25345]
**Describe the bug**
Implementing a product data store breaks variable products UI in admin even when it's just calling the parent methods.  Created variations will not display in admin.  You can add them but they disappear once saved.  They do work on frontend.

**To Reproduce**
1. Create a class that implements WC_Object_Data_Store_Interface and WC_Product_Data_Store_Interface
2. Override the data store 'product'

Alternatively install:
https://github.com/coderkevin/woocommerce-product-inventory-datastore

3. Create a variable product with attributes and variations then save

**Screenshots**
![Screen Shot 2019-12-31 at 1 42 55 PM](https://user-images.githubusercontent.com/3336230/71633798-c156b380-2bd3-11ea-8581-db00d4756022.png)

**Expected behavior**
Variations being displayed in admin

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

<details>

WordPress address (URL): |   | http://wordpress.test
Site address (URL): |   | http://wordpress.test
WooCommerce version: |   | 3.8.1
WooCommerce REST API package: |   | 1.0.2 /Users/xxx/Code/wordpress/wp-content/plugins/woocommerce/packages/woocommerce-rest-api
Log directory writable: |   | /Users/xxx/Code/wordpress/wp-content/uploads/wc-logs/
WordPress version: |   | 5.3.2
WordPress multisite: |   | –
WordPress memory limit: |   | 256 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –

</details>

**Comment by FiniteSource** [comment]
Extending `WC_Product_Data_Store_CPT` does the trick because of this line:

`$results = WC_Data_Store::load( 'product' )->query( $args );`

If this is going to be called on the product data store I think query should be added to the interface.

**Comment by claudiosanches** [comment]
Interfaces should not have effects like that, you should extend `WC_Product_Data_Store_CPT` if you want to make it function without having to code all functions for the interface.
Also note that in WooCommerce Date Stores for variable and grouped products, and also product variations extend `WC_Product_Data_Store_CPT` to make it works.
