### ISSUE TITLE
Import variation product without parent variable product produce misleading success message

### ISSUE THREAD

**Issue by OlegApanovich** [woocommerce/woocommerce#25357]
**Describe the bug**
When we try to import product variations with do not existing variable parent product in the end of the import process we receive success message that all products imported. But obviously there no any new products anywhere. 

**To Reproduce**
1. Remove all products, even from trash.
2. Then try to download and import file that you can find by follow link https://docs.google.com/spreadsheets/d/1xiToWgav2NX7GS3565SFzDn3yPHF0_vCba6whO_eWFk/edit?usp=sharing You also can create your own import file. The main conditions that it has variation product and do not existing variable product as a parent for variastions like on a screen below.
![Screenshot](https://user-images.githubusercontent.com/25242713/71765970-4d821700-2f03-11ea-82f8-d66471fadd66.png)
3. Then try to fire up import process with import file without update option like on my screen below
![Screenshot1](https://user-images.githubusercontent.com/25242713/71766015-e4e76a00-2f03-11ea-804e-92464834ddd0.png)
 4. In the end of import process you will receive success message 
![Screenshot3](https://user-images.githubusercontent.com/25242713/71766045-44de1080-2f04-11ea-9355-05808ca937b2.png)
But you can't find any new product in product list in database neither.

**Expected behavior**
We must show some error message in such case.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Latest wordpress intalation
```

```
</details>

**Comment by tammullen** [comment]
Hi @OlegApanovich 

Thank you for taking the time reporting this bug, we really appreciate your help. I can reproduce it on my end in v3.8.1 using the same steps as you provided.

Success notice saying products imported
<img width="783" alt="Screenshot 2020-01-15 at 11 54 27" src="https://user-images.githubusercontent.com/24649833/72432107-27276b80-378e-11ea-9b0a-9f8eea6b39a8.png">

No products showing in Product list
<img width="947" alt="Screenshot 2020-01-15 at 11 57 40" src="https://user-images.githubusercontent.com/24649833/72432152-40301c80-378e-11ea-9802-f65cf36ebb84.png">

However when I try this in the latest v3.9.0-rc.2 the importer does display an error as we would expect

<img width="654" alt="Screenshot 2020-01-15 at 11 59 04" src="https://user-images.githubusercontent.com/24649833/72432314-a6b53a80-378e-11ea-80bf-6d78ca618c17.png">

I'm going to close this as it working in the latest version. Please feel free to comment on it in case we missed something. We’d be happy to take another look.
