### ISSUE TITLE
Disabled shipping option still requires price during WooCommerce installation

### ISSUE THREAD

**Issue by richboos** [woocommerce/woocommerce#25358]
![woocommerce-setup](https://user-images.githubusercontent.com/773755/71769454-a647b480-2eef-11ea-9e8c-0ac26ef9cfc3.PNG)

(Edited: The first time I couldn't find where to attach a file, now I see it.)

When a user in the US reaches the Shipping step of WooCommerce installation, they are presented with two shipping zones to start with: United States, and Locations not covered by your other zones.
These zones can be disabled with a toggle.
I disable the Locations not covered by your other zones, then click continue. But instead of continuing, I get an alert box telling me I must fill out the cost field.

This might be a bug, as I'm being forced to enter data for a feature I won't use (it's disabled!). Perhaps it isn't a bug and this is required in case someone enables it later and there is no provision to force a cost then? But just in case, I wanted to report it here.

**Comment by juliaamosova** [comment]
Hi @richboos,

Thank you for taking the time reporting this bug, we really appreciate your help. I can reproduce it on my end. 

**Screencast:**

https://recordit.co/z91Lyk9R7g

**Screenshot:**

![wizard](https://user-images.githubusercontent.com/19143190/72386399-3fa96e80-3719-11ea-84dd-a6749152ab96.jpg)

I noticed that it happens only if one of the methods is disabled. If both methods are disabled, the issue doesn't occur. 

We’re going to work on this bug as soon as possible. Stay tuned for updates.

**Comment by peterfabian** [comment]
Please continue the discussion in the PR, closing.
