### ISSUE TITLE
WooCommerce Admin prompt on dashboard, despite just opting out of it during installation

### ISSUE THREAD

**Issue by richboos** [woocommerce/woocommerce#25359]
During WooCommerce installation/setup, one of the very last steps asks if you want some optional software. At the time of writing, I remember those software being MailChimp, Facebook, Jetpack, and WooCommerce Admin.

I made sure all the options were toggled to no. No I do not want any of these installed.

Installation is complete and I click on the button to view the dashboard. On the dashboard, WooCommerce is asking me if I want to install WooCommerce admin. No. I do not want that installed.

It would be nice if no meant no. Instead of 20 seconds after telling WooCommerce no, it asks us again to install WooCommerce Admin.

**Comment by peterfabian** [comment]
Fair enough, we could add some logic so that brand new shops wouldn't have this displayed. As setup wizard is only generally displayed once at the very beginning of the shop's existence, the admin banner is more aimed at existing customers.

Thanks for the suggestion.

**Comment by juliaamosova** [comment]
Since WooCommerce Admin is now a part of WooCommerce Core we no longer offer an option to install it during onboarding. Closing this issue as it is absolute at this point.
