### ISSUE TITLE
Significant Changes to Accessing and Using GeoLite2 Databases

### ISSUE THREAD

**Issue by stodorovic** [woocommerce/woocommerce#25361]
**Describe the bug**
MaxMind doesn't support publicly downloading GeoLite2 Databases since December 30, 2019. More details: https://dev.maxmind.com/geoip/geoip2/geolite2/

**To Reproduce**
```
[woocommerce]$ grep -r GEOLITE2_DB .
./includes/class-wc-geolocation.php:    const GEOLITE2_DB = 'http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz';
./includes/class-wc-geolocation.php:            $tmp_database_path    = download_url( self::GEOLITE2_DB );
[woocommerce]$ wget http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz
--2020-01-04 18:46:29--  http://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.tar.gz
Resolving geolite.maxmind.com (geolite.maxmind.com)... failed: Name or service not known.
wget: unable to resolve host address ‘geolite.maxmind.com’
[woocommerce]$
```

**Expected behavior**
I'm not sure that is _Bug report_ or _Feature request_. I could use [geoipupdate](https://dev.maxmind.com/geoip/geoipupdate/) and filter _woocommerce_geolocation_local_database_path_ to use external DB (eg. _/usr/share/GeoIP/GeoLite2Country.mmdb_) as a solution. I've removed cron task, but I'd like to know more details about GeoLite2 integration in the future. Do you planning to add "keys" for downloading?

**Comment by oscargare** [comment]
Hi, Do you have any guidelines for how to implement it? I want to contribute to solving this issue.

**Comment by peterfabian** [comment]
Hi @oscargare, thanks for your initiative. We're discussing this currently to see what options we have in terms of how to include the database and if we need to involve the legal department. @ObliviousHarmony will keep this updated.

**Comment by HowdyMcGee** [comment]
@peterfabian An additional issue I believe is how WooCommerce is including the Maxmind library. This is causing incompatibility issues with other plugins who also use the library. See #25370

**Comment by marke123** [comment]
Just an FYI, Matomo.org (formerly Piwiki Analytics) reports that they switched over from maxmind to db-ip.com due to the license requirement.
