### ISSUE TITLE
Broken design for the calendar - [3.9.0-rc.1]

### ISSUE THREAD

**Issue by MartaPawlonka** [woocommerce/woocommerce#25373]
**Describe the bug**
I noticed that the design for a calendar is broken for the new version WooCommerce 3.9. 

**To Reproduce**
1. Go to Edit order page.
2. Click on Date created field.
3. See error.

**Screenshots**
http://wpdesk.me/mp/lxmbf.png

**Expected behavior**
Should look in this way: http://wpdesk.me/mp/zcoae.png

**Comment by tammullen** [comment]
Hi @MartaPawlonka,
Thank you for taking the time reporting this bug, we really appreciate your help. I can reproduce it on my end with the same steps as you described when using 3.9.0-rc.1
<img width="297" alt="Screenshot_2020-01-12_at_21_06_48" src="https://user-images.githubusercontent.com/24649833/72225704-6bddb780-3580-11ea-88ec-c97e5d1c6f83.png">

However I'm going to close this as it is now working as expected in 3.9.0-rc.2
<img width="296" alt="Screenshot 2020-01-12 at 21 06 01" src="https://user-images.githubusercontent.com/24649833/72225730-bf500580-3580-11ea-9adb-6e204f767a8b.png">
