### ISSUE TITLE
Plugin Conflict - GeoIP Detection ( Maxmind library ) 

### ISSUE THREAD

**Issue by HowdyMcGee** [woocommerce/woocommerce#25370]
Taken from the [related support forum](https://wordpress.org/support/topic/incompatible-with-plugin-geoip-detection-3-0-fatal-error/)

> Woocommerce and [GeoIP Detection](https://wordpress.org/plugins/geoip-detect/) cannot be enabled at the same time because they use different versions of the Maxmind vendor library:
> 
> https://wordpress.org/support/topic/fatal-error-getwithprefixlen/
> 
> I am requiring geoip2/geoip2 via composer and using the current version v2.10. You seem to have copied some files out of it and require it manually.
> 
> Do you have an idea how to avoid this version interdependency?
> Would it be possible to move your classes into a different namespace, or also use the composer version?

**Comment by benjaminpick** [comment]
To reproduce the issue, install `GeoIP Detection` in version `3.0` - I have reverted to an older version of the maxmind library in `3.0.1` for now.

**Comment by ObliviousHarmony** [comment]
As part of a refactor to address #25361, I'll switch us to a composer dependency and update to the latest version.

**Comment by benjaminpick** [comment]
Ok, thanks - I'm not sure if composer is intelligent enough to allow the new and old version to be installed side by side, possibly we wil need to release a new plugin version at the same time.

**Comment by claudiosanches** [comment]
Solved by #25378
