### ISSUE TITLE
Question about Woocommerce admin

### ISSUE THREAD

**Issue by rodolphebertozzo** [woocommerce/woocommerce#25372]
Since mid 2019 is deployed Woocommerce Admin as a plugin for those who want to test it.
So I wanted to know if Wocommerce Admin will remain a plugin or if it is just a test and will be implemented in Woocommerce later?
I also wanted to know when the final version will be available?

**Comment by rrennick** [comment]
> So I wanted to know if Wocommerce Admin will remain a plugin

It will continue to be developed in its own repository similar to Gutenberg, WooCommerce Product Blocks, Action Scheduler, and WooCommerce REST API.

> will be implemented in Woocommerce later?

Yes, we are planning on merging WC Admin into WooCommerce in a future version.

> I also wanted to know when the final version will be available?

As with Gutenberg, et al. above, WooCommerce Admin will remain an active project where updates will be merged into WC core as they become available.
