### ISSUE TITLE
WC_Email woocommerce_email_* filters don't pass core WP filter chain arguments

### ISSUE THREAD

**Issue by diablodale** [woocommerce/woocommerce#25385]
filter `woocommerce_email_from_address` and the callback `WC_Email::get_from_address()` added on core WP filter `wp_mail_from` don't pass the core WP `$from_email` along the filter chain. This makes it impossible to use the core WP filter chain's arguments to make decisions in code.

A Woo fix is reasonably easy -- pass the core WP filter arguments in Woo's filter chain and coordinate the two usages of `get_from_address()` and its siblings; or create two separate functions.

**PLEASE NOTE** this issue of _not_ passing the core WP filter chain's parameter also exists in the other Woo callbacks `get_from_name()`, `get_content_type()` for the core WP `wp_mail_from_name` and `wp_mail_content_type`

## Reproduce

This was found during code review and debugging why my control of the "email from" was not working in all scenarios of plugin filter priorities, Woo installed/not, other plugin management of mail headers, etc. It can be reproduced to creating your own `add_filter` to control email headers using the core WP `wp_mail_from` filter chain.

https://github.com/woocommerce/woocommerce/blob/15ffaeee6b910da6988028bf8da895a12675e6be/includes/emails/class-wc-email.php#L630-L632

...adds on-the-fly filters for the core WP `wp_mail_from`. When the core WP `wp_mail()` runs, it applies these filters, e.g. `wp_mail_from`, _and passes argument `$from_email`_.

https://github.com/WordPress/WordPress/blob/918dead27e833df6832d2cb771b366da3d774a1a/wp-includes/pluggable.php#L345

Unfortunately Woo's `get_from_address()` does not accept that `$from_email` argument. And it doesn't pass any such argument further into Woo's filter `woocommerce_email_from_address`. Therefore, it is not possible for any callback for `woocommerce_email_from_address` filter to examine the `$from_email` in the `wp_mail_from` filter chain to make a choice to use the original `$from_email`, use Woo's option `woocommerce_email_from_address`, alter it, etc.

https://github.com/woocommerce/woocommerce/blob/15ffaeee6b910da6988028bf8da895a12675e6be/includes/emails/class-wc-email.php#L614-L617

All three of these Woo filter callbacks are being used for two purposes: internal class use + callback from core WP filters. Each use has slightly different needs. A fix needs to verify both needs are met -or- separate into separate functions.

Since the `add_filter('wp_mail_from', array($this, 'get_from_address' ))` and its siblings are done on-the-fly inside the `WC_Email::send()` function (not in the plugin load stage), it is more challenging to remove these Woo filter callbacks. I could remove these by hacking three `remove_filter()` in the other filter `woocommerce_mail_callback` applied a few lines down. While this is not a bug, it is an aberration of hiding/chasing filters due to the root issue with `get_from_address()` and its siblings.

## Fix

Here is a example approach to fix 1 of the 3 Woo filters. It is to receive the core WP filter's argument, and pass that argument into Woo's filter. A similar approach might also be used on the other 2 filter callbacks.

```php
public function get_from_address( $chain_from_address = '' ) {
	$from_address = apply_filters( 'woocommerce_email_from_address', get_option( 'woocommerce_email_from_address' ), $this, $chain_from_address );
	return sanitize_email( $from_address );
}
```

## Notes

Related to https://github.com/woocommerce/woocommerce/issues/9653

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

<details>

```
### WordPress Environment ###

WordPress address (URL): https://**redacted**
Site address (URL): https://**redacted**
WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache/2.4.38
PHP Version: 7.3.12
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.34-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 24.87MB
Database Data Size: 11.18MB
Database Index Size: 13.69MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.19MB + Index: 0.31MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.22MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.25MB + Index: 0.27MB + Engine InnoDB
wp_comments: Data: 1.52MB + Index: 0.89MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.27MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 3.52MB + Index: 5.03MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.31MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp_users: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_wc_download_log: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Akismet Anti-Spam: by Automattic – 4.1.3
All In One SEO Pack: by Michael Torbert – 3.3.4
Block Plugin Spam Redirects: by Dale Phurrough – 0.1.1
Change Wordpress robot email behavior: by Dale Phurrough – 1.0.5
Classic Editor: by WordPress Contributors – 1.5
GDPR Cookie Consent: by WebToffee – 1.8.2
Disable Emojis (GDPR friendly): by Ryan Hellyer – 1.7.2
Hard 404 on Wordpress searches: by Dale Phurrough – 1.0.1
Reset Opcache on Upgrade: by Dale Phurrough – 1.1.0
Restrict Dashboard News: by Dale Phurrough – 0.2.0
Remove optional Wordpress HTTP headers & links: by Dale Phurrough – 1.1.0
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.10.2
Secure DB Connection: by Xiao Yu – 1.1.5
Woocommerce Private Tweaks: by Dale Phurrough – 1.0.10
Woocommerce Paypal Gateway Extras: by Dale Phurrough – 1.2.1
WooCommerce Sales By Location Report: by ChuckMac Development – 1.3.2 – Not tested with the active version of WooCommerce
Woocommerce Digital Downloads, Registration, Authorization: by Dale Phurrough – 1.4.0
WooCommerce: by Automattic – 3.8.1
Wordfence Login Security: by Wordfence (mod Dale Phurrough) – 1.0.4
WP Maintenance Mode: by Designmodo – 2.2.4
WP Redis: by Pantheon, Josh Koenig, Matthew Boynes, Daniel Bachhuber, Alley Interactive – 0.8.0


### Inactive Plugins (0) ###


### Dropin Plugins (2) ###

db.php: Secure DB Connection
object-cache.php: object-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #753 - /shop/
Cart: #754 - /cart/
Checkout: #755 - /checkout/
My account: #756 - /my-account/
Terms and conditions: #750 - /terms/

### Theme ###

Name: Twenty Eleven Customized by Dale
Version: 1.1.0
Author URL: http://hidale.com
Child Theme: ✔
Parent Theme Name: Twenty Eleven
Parent Theme Version: 3.3
Parent Theme Author URL: https://wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: twentyeleven-dale/woocommerce/auth/form-login.php
twentyeleven-dale/woocommerce/checkout/form-login.php
twentyeleven-dale/woocommerce/global/form-login.php


### Action Scheduler ###

Complete: 1
Oldest: 2020-01-09 17:00:22 +0100
Newest: 2020-01-09 17:00:22 +0100

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –
```
</details>

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #25405.
