### ISSUE TITLE
WooCommerce Admin plugin notice shown if folder name does not mach

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce#25394]
**Describe the bug**
If wc-admin is installed in a directory not named `woocommerce-admin` the notice to install shown wc-admin will be shown.

Minor, but we can update this to check for the namespace and class in place of the folder name.

**To Reproduce**
1. Install wc-admin.
1. Rename to anything other than `woocommerce-admin`.
1. Trigger `woocommerce_installed` or switch themes to trigger the notice.
1. Note the notice.

**Screenshots**
<img width="1164" alt="Screen Shot 2020-01-13 at 5 38 59 PM" src="https://user-images.githubusercontent.com/10561050/72245463-989ad900-362b-11ea-9eac-c93989409aa8.png">

**Expected behavior**
Expected to not see this notice.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Thank you for submitting the issue @haszari and @joshuatf for submitting PR.
