### ISSUE TITLE
Coupon Error

### ISSUE THREAD

**Issue by Eco-LivingIdeas** [woocommerce/woocommerce#25409]
**Describe the bug**
I have generated a new coupon where I want my customers to get 15% off everything in the basket but they must have one specific item in there to qualify for the discount. However, when I add that specific product in the field that says "Products – Products that the coupon will be applied to, or that need to be in the cart in order for the fixed or percentage discount to be applied.", it only applies the 15% discount to that specific product and not everything else in the basket.

**To Reproduce**
1. Go to 'woocommerce'
2. Click on 'coupon, add new'
3. Scroll down to 'fill in coupon details'

**Screenshots**
If applicable, add screenshots to 
![coupon 2](https://user-images.githubusercontent.com/59936851/72469568-937a8d00-37d7-11ea-9d6c-b52c560f1202.JPG)
![coupon 3](https://user-images.githubusercontent.com/59936851/72469569-937a8d00-37d7-11ea-835c-30e7e4c94212.JPG)
![Coupon 1](https://user-images.githubusercontent.com/59936851/72469571-94132380-37d7-11ea-8508-2ab4b45eeedb.JPG)

help explain your problem.

**Expected behavior**
I thought the discount would be applied to everything in the basket so long as one of the swim nappies was in there.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```

N/A
</details>

**Comment by juliaamosova** [comment]
Hi @Eco-LivingIdeas,

Thank you for raising the issue. However, note that the description of the `Products` field says that `Products that the coupon will be applied to, or that need to be in the cart in order for the "Fixed cart discount" to be applied.` It doesn't say anything about the percentage discount to be applied to the cart as in your case:

![limited](https://user-images.githubusercontent.com/19143190/72550024-c1200e80-3889-11ea-8e33-3d3ee249ddde.jpg)

I tested it with the `Fixed cart discount` (not `Fixed percentage discount`) type of coupon and it worked as expected:

![limited2](https://user-images.githubusercontent.com/19143190/72550099-e745ae80-3889-11ea-8dc8-613272a472ea.jpg)

![limited3](https://user-images.githubusercontent.com/19143190/72550109-ead93580-3889-11ea-88fb-34522b9807f1.jpg)

I am closing this issue as there is no bug found. Please feel free to comment back in case you think I missed something and I will take a 2nd look.
