### ISSUE TITLE
From email not updating

### ISSUE THREAD

**Issue by ChrisHoman** [woocommerce/woocommerce#25408]
**Describe the bug**
When sending emails, the email address is always the admin address. Changing the email in "WC > settings > emails > from address has no effect. This is similar to the issue described in #24405 and #24450 but the provided solution (remove emoji) has no effect.

I understand it was supposed to be fixed in 3.8 but currently using 3.8.1

I tried the following to fix it:

- Clear all caches
- Search and replace all database records to replace old email address with new
- Changed the admin email address

All to no avail.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://photoluts.com
Site address (URL): https://photoluts.com
WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.13
PHP Post Max Size: 64 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.67.0
OpenSSL/1.0.2t

SUHOSIN Installed: –
MySQL Version: 5.6.45
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: wpwt_
MaxMind GeoIP Database: ✔
Total Database Size: 8.08MB
Database Data Size: 6.84MB
Database Index Size: 1.24MB
wpwt_woocommerce_sessions: Data: 0.69MB + Index: 0.04MB + Engine MyISAM
wpwt_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpwt_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpwt_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpwt_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_cartflows_ca_cart_abandonment: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_cartflows_ca_email_history: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_cartflows_ca_email_templates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_cartflows_ca_email_templates_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_cf_forms: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wpwt_cf_form_entries: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_cf_form_entry_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_cf_form_entry_values: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_cf_pro_messages: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_cf_queue_failures: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_cf_queue_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_cli_cookie_scan: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_cli_cookie_scan_categories: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpwt_cli_cookie_scan_cookies: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpwt_cli_cookie_scan_url: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_cli_scripts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_cli_visitor_details: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpwt_comments: Data: 0.43MB + Index: 0.30MB + Engine MyISAM
wpwt_edd_customermeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_edd_customers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_et_bloom_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_failed_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_gh_activity: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_gh_broadcasts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_gh_contactmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpwt_gh_contacts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_gh_emailmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_gh_emails: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_gh_events: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_gh_form_impressions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_gh_funnels: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_gh_sms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_gh_stepmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_gh_steps: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_gh_submissionmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_gh_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_gh_superlinks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_gh_tags: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_gh_tag_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_litespeed_img_optm: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_litespeed_optimizer: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_loginizer_logs: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpwt_mailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_mailchimp_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_mwb_dos_data: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_options: Data: 1.94MB + Index: 0.13MB + Engine MyISAM
wpwt_postmeta: Data: 2.14MB + Index: 0.24MB + Engine MyISAM
wpwt_posts: Data: 1.35MB + Index: 0.25MB + Engine MyISAM
wpwt_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_rank_math_404_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_rank_math_internal_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_rank_math_internal_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_rank_math_redirections: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_rank_math_redirections_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_rank_math_sc_analytics: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_rio_process_queue: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wpwt_smush_dir_images: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_sumo_tbl_user_earned_coupon: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpwt_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpwt_term_relationships: Data: 0.03MB + Index: 0.07MB + Engine MyISAM
wpwt_term_taxonomy: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpwt_tm_taskmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_tm_tasks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_usermeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wpwt_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpwt_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpwt_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpwt_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpwt_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpwt_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpwt_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpwt_wplc_chat_msgs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpwt_wplc_chat_ratings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpwt_wplc_chat_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpwt_wplc_chat_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpwt_wplc_custom_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpwt_wplc_departments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpwt_wplc_offline_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpwt_wplc_roi_conversions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpwt_wplc_roi_goals: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpwt_wplc_webhooks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

Akismet Anti-Spam: by Automattic – 4.1.3
Autoptimize: by Frank Goossens (futtta) – 2.6.1
Cloudflare Page Cache: by Patrick Meenan – 1.4
Contact Form 7: by Takayuki Miyoshi – 5.1.6
Divi Sensei Before After Slider: by Divi Sensei – 2.1.0
Enable Media Replace: by ShortPixel – 3.3.7
Flamingo: by Takayuki Miyoshi – 2.1.1
Judge.me Product Reviews for WooCommerce: by Judge.me – 1.3.1 – Not tested with the active version of WooCommerce
Loginizer: by Raj Kothari – 1.4.3
Mailchimp for WooCommerce: by Mailchimp – 2.3.1
MC4WP: Mailchimp for WordPress: by ibericode – 4.7.4
MWB WooCommerce Social Share Discount Coupon: by makewebbetter – 1.0.1 – Not tested with the active version of WooCommerce
Safe SVG: by Daryll Doyle – 1.9.7
Search & Replace: by Inpsyde GmbH – 3.2.1
Rank Math SEO: by Rank Math – 1.0.37.1
SEO for WooCommerce: by Rank Math – 1.0.0 – Not tested with the active version of WooCommerce
W3 Total Cache: by BoldGrid – 0.12.0
GDPR Cookie Consent: by WebToffee – 2.2.3
WooCommerce Admin: by WooCommerce – 0.24.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.18
WooCommerce Stripe Gateway: by WooCommerce – 4.3.1
WooCommerce Google Ads Conversion Tracking: by Wolf+Bär Agency – 1.6.2
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.7.6

WooCommerce Services: by Automattic – 1.22.2
WooCommerce Smart Sale Badge: by Hugh Lashbrooke – 1.1 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.8.1
WP Chatbot: by MobileMonkey – 4.3
WP Clone by WP Academy: by WP Academy – 2.2.9
WP Mail SMTP: by WPForms – 1.8.1
Smush: by WPMU DEV – 3.4.2

### Inactive Plugins (34) ###

Advanced Dynamic Pricing for WooCommerce: by AlgolPlus – 2.3.0
Beeketing For WooCommerce: by Beeketing – 3.8.16 – Not tested with the active version of WooCommerce
Bloom: by Elegant Themes – 1.3.10
Booster for WooCommerce: by Algoritmika Ltd – 4.7.0
Child Theme Configurator: by Lilaea Media – 2.5.2
Compress JPEG & PNG images: by TinyPNG – 3.2.1
Contact Form 7 Extension For Mailchimp: by Renzo Johnson – 0.5.10
Digital Goods Checkout on WooCommerce: by Claudio Sanches – 1.1.0 – Not tested with the active version of WooCommerce
Digital Goods for WooCommerce Checkout: by Thedotstore – 3.2 – Not tested with the active version of WooCommerce
Divi Contact Form MailChimp Extension: by ReCorp – 2.0.1
EU VAT Compliance for WooCommerce (Free): by David Anderson – 1.13.17
EWWW Image Optimizer: by Exactly WWW – 5.1.4
Facebook for WooCommerce: by Facebook – 1.9.15 – Not tested with the active version of WooCommerce
Gratisfaction- Loyalty Rewards Referral Birthday and Giveaway Program: by Appsmav – 3.7.3
Groundhogg: by Groundhogg Inc. – 2.1.11
Holler Box: by Scott Bolinger – 1.5.1
ImageMagick Engine: by Orangelab – 1.5.4
Jilt for WooCommerce: by Jilt – 1.7.1
Messenger Customer Chat: by Facebook – 1.3
OneSignal Push Notifications: by OneSignal – 2.0.0
Sales Pop: by Beeketing – 1.4.18 – Not tested with the active version of WooCommerce
Schema & Structured Data for WP & AMP: by Magazine3 – 1.9.21
SUMO Coupons: by Fantastic Plugins – 5.0 – Not tested with the active version of WooCommerce
Table of Contents Plus: by Michael Tran – 1601
Webcraftic Robin image optimizer: by Webcraftic <wordpress.webraftic@gmail.com> – 1.4.1
WooCommerce Cart Abandonment Recovery: by CartFlows Inc – 1.2.3 – Not tested with the active version of WooCommerce
WooCommerce Checkout Manager: by QuadLayers – 4.8.5 – Not tested with the active version of WooCommerce
WooCommerce Direct Checkout: by QuadLayers – 2.3.2 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.17
WooCommerce Price Based on Country (Basic): by Oscar Gare – 1.8.19
WooCommerce Social Share Discount PRO: by WooPro – 1.8.9 – Not tested with the active version of WooCommerce
WP-Live Chat by 3CX: by 3CX – 8.1.5
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.0.15

Yoast SEO: by Team Yoast – 12.8.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #672 - /store/
Cart: #576 - /cart/
Checkout: #577 - /checkout/
My account: #578 - /my-account/
Terms and conditions: #2283 - /terms-conditions/

### Theme ###

Name: Divi Child
Version: 3.29.3.1568987596
Author URL: http://www.elegantthemes.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 4.1
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1,523
Oldest: 2019-12-15 19:33:14 +0000
Newest: 2020-01-15 18:56:24 +0000

Pending: 2
Oldest: 2020-01-15 19:56:24 +0000
Newest: 2020-01-15 19:56:24 +0000

Canceled: 48
Oldest: 2020-01-10 14:07:32 +0000
Newest: 2020-01-14 08:40:36 +0000

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by thomas-zg** [comment]
Afaik, the only way is to use these filters:
`
// Function to change email address 
function wpb_sender_email( $original_email_address ) {    
return 'tim.smith@example.com';} 

// Function to change sender name
function wpb_sender_name( $original_email_from ) {    
return 'Tim Smith';} 

// Hooking up our functions to WordPress filters 
add_filter( 'wp_mail_from', 'wpb_sender_email' );
add_filter( 'wp_mail_from_name', 'wpb_sender_name' );
`

**Comment by ChrisHoman** [comment]
Hi Thomas, @thomas-zg 

That was very useful in that it actually didn't solve the problem but alerted me that the cause is elsewhere. Turns out some idiot, me, had configured an smtp mailer to be used which overrode the default settings...

So problem solved
