### ISSUE TITLE
Change wording for email restrictions on coupons

### ISSUE THREAD

**Issue by jobthomas** [woocommerce/woocommerce#25400]
**Is your feature request related to a problem? Please describe.**

Currently, the notice "Please enter an email address" does not occur when the field is empty, only when the content added there is *not* valid. 

**Describe the solution you'd like**
Change text from "Please enter an email address" to "Please enter a valid email address"

![](https://d.pr/i/2PJ3Fo+)
Link to image here: https://d.pr/i/2PJ3Fo.

**Comment by juliaamosova** [comment]
Hi @jobthomas,

Thanks for opening this enhancement issue. I agree that messaging can be improved. However, it looks like we are using a built-in browser form validation for that field as I am getting different messages in different browsers:

**Chrome:**

![chrome](https://user-images.githubusercontent.com/19143190/72355028-9b0a3b00-36de-11ea-9e9f-f2c7e9c99d9a.jpg)

**Safari:**

![safari](https://user-images.githubusercontent.com/19143190/72355059-a65d6680-36de-11ea-9436-146b7a9fc56c.jpg)

**Firefox:**

![firefox](https://user-images.githubusercontent.com/19143190/72355077-afe6ce80-36de-11ea-9992-edea93fc87e3.jpg)

There is a way to create a custom JavaScript validation though. 

I will keep this issue labeled as `enhancement` with `priority:low` as it fits the occasion.

**Comment by jobthomas** [comment]
That explains why I could've find the line in the code repo; it's browser validation. I'm not sure if we should keep this open then given that it's not something that Woo core provides.

**Comment by juliaamosova** [comment]
>I'm not sure if we should keep this open then given that it's not something that Woo core provides.

I agree. We can keep it as an `enhancement` but I don't think we'd get to work on this any time soon. We can reopen in case we'd receive more reports and requests for custom validation. Closing for now as it seems we are in agreement.
