### ISSUE TITLE
Can't change Woocommerce language EN->PL

### ISSUE THREAD

**Issue by piotrkorzan** [woocommerce/woocommerce#25410]
**Describe the bug**

I am trying to change language for woocommerce from english to polish. I have tried putting woocommerce-pl_PL.mo & .po files into wp-content/languages/plugins/ and woocommerce-pl_PL.mo & .po files to woocommerce/i18n/languages/ and still no success.

I've also tried to use Loco Translate and still nothing.

Could you help?

**To Reproduce
Steps to reproduce the behavior:**

Please check url:
https://uroda365.pl/

**Screenshots**

![Zrzut ekranu 2020-01-15 o 23 49 51](https://user-images.githubusercontent.com/59939785/72478422-4b1c9880-37f2-11ea-88ee-cb3c85a6d9d4.png)
![Zrzut ekranu 2020-01-15 o 23 50 00](https://user-images.githubusercontent.com/59939785/72478423-4b1c9880-37f2-11ea-813e-679a5712c703.png)
![Zrzut ekranu 2020-01-15 o 23 50 18](https://user-images.githubusercontent.com/59939785/72478424-4bb52f00-37f2-11ea-8d43-d611ce537a76.png)

**Expected behavior**

Woocommerce in PL language.

**Isolating the problem (mark completed items with an [x]):**

 I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
[ x] This bug happens with a default WordPress theme active, or Storefront.
[x ] I can reproduce this bug consistently using the steps above.
WordPress Environment

**Szczegóły**
``` Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin. ```
N/A

**Comment by juliaamosova** [comment]
Hi @piotrkorzan,

Thank you for rasing the issue. WooCommerce comes localization-ready out of the box for the Polish language. The easiest way to switch the language of WooCommerce and Site from English to Polish is by navigating to `Settings / General / Site Language` and selecting `Polski` in the drop-down:

![polski1](https://user-images.githubusercontent.com/19143190/72551370-a56a3780-388c-11ea-9fff-01033968f836.jpg)

The front-end of your site will be in Polish as well:

![polski2](https://user-images.githubusercontent.com/19143190/72551408-b450ea00-388c-11ea-81fd-c610b11bbc84.jpg)

Let me know if I missed something.

**Comment by piotrkorzan** [comment]
Hello @juliaamosova, thanks for your answer.
It's also done. Still it's in english.

**Comment by juliaamosova** [comment]
@piotrkorzan apologies for the delayed reply. I double-checked your site and see that it seems to be looking good and in Polish:

![screencapture-uroda365-pl-2020-01-29-12_53_30](https://user-images.githubusercontent.com/19143190/73358492-a04ab680-4296-11ea-9e66-c4d02d0dd7d4.png)

![screencapture-uroda365-pl-product-category-marki-loreal-2020-01-29-12_54_19 (1)](https://user-images.githubusercontent.com/19143190/73358549-c1aba280-4296-11ea-9acb-9fd50403bff5.png)

I don't think there is a bug related to translation so I am going to close this issue. However, please feel free to comment on it in case we missed something. We’d be happy to take another look.
