### ISSUE TITLE
[WC 3.9 rc-3] MaxMind Geolocation Improvements

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/woocommerce#25416]
**Is your feature request related to a problem? Please describe.**
The new MaxMind GeoLocation setup, at first glance, can be confusing.

**Describe the solution you'd like**
My first issue was handling the update for existing sites. My test store already used Geolocate and once updated to RC-3 I wasn't prompted in any way that I need to get a MaxMind license key to continue using my existing Geolocate setting.

Beyond that, I find it confusing that the settings for this were added in a separate settings tab under Integration. What if the two fields under the Integration tab were moved to under the Default customer location setting and made conditional? They wouldn't show up unless the settings for Geolocate were selected.

**Describe alternatives you've considered**
At the least, if I select Geolocate and haven't entered my MaxMind license I should be prompted to do so with links to the docs for this and the Integration tab.

**Additional context**

**Comment by claudiosanches** [comment]
> My test store already used Geolocate and once updated to RC-3 I wasn't prompted in any way that I need to get a MaxMind license key to continue using my existing Geolocate setting.

On your test store you have already update from 3.9, so no upgrade routine got triggered, try disable and enable WooCommerce again.
But we include this notice:

https://github.com/woocommerce/woocommerce/blob/42269f965c94b1cf51f09500ff44ddbfc90cfd68/includes/admin/views/html-notice-maxmind-license-key.php#L12-L31

> Beyond that, I find it confusing that the settings for this were added in a separate settings tab under Integration. What if the two fields under the Integration tab were moved to under the Default customer location setting and made conditional? They wouldn't show up unless the settings for Geolocate were selected.

This is an integration, and also it should got removed from WooCommerce in the future, we plan to move this integration to a feature plugin, also we need to ensure people are aware that they are using MaxMind Geolocation database, something that we failed to make clear in the past, in fact we should never integrate it inside WooCommerce without been on the integration tab, that's now we have more trouble to make this update.
