### ISSUE TITLE
Correct MaxMind error message shown in the case of invalid key to include option for the key not being activated yet

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#25429]
**Is your feature request related to a problem? Please describe.**

When a new license key is generated, MaxMind can take up to 5 minutes to activate it. They do display the notice that it may take up to 5 minutes to activate, but it could be easily missed.

So after generating the license, when a user instantly enters the license in WooCommerce, they get The MaxMind license key is invalid. error message:

![Screen Shot 2020-01-19 at 11 43 27](https://user-images.githubusercontent.com/19143190/72739666-01d69b00-3b9c-11ea-945c-b7d94f236dfb.png)

**Describe the solution you'd like**

The error message could be updated to `The MaxMind license key is invalid. If you have just generated the license key, then it may take a few minutes to activate.` or something similar.

This would cause less confusion when a user generates the license key and then adds to WooCommerce right away.

**Describe alternatives you've considered**

Add a note about waiting for the license key to be activated to our documentation. 

**Additional context**

Credit for this enhancement idea goes to @anant1811.

**Comment by PeteAH** [comment]
I have the same issue is there a fix?
