### ISSUE TITLE
Cash on Delivery Performance

### ISSUE THREAD

**Issue by rochow** [woocommerce/woocommerce#25438]
**Describe the bug**
class WC_Gateway_COD extends WC_Payment_Gateway {}

__construct() { $this->init_form_fields(); }

init_form_fields() {
Get zones
Get methods for every zone
Then for each zone inside a method, get methods for the zone
}

At no point does this check "is COD active and I need to run all this code?"

Refer to the screenshot section to see the New Relic & DB queries on a normal website with about 40 zones - some per state and some per country, nothing super excessive.

You can see this is **smashing** the site, about 400 related DB queries (a lot of get_option relate to this too) which is taking approx 3.5 seconds to run. This happens on _every single pageload._

**To Reproduce**
1) Setup a lot of zones and methods
2) Load site and look at queries

**Screenshots**
![slack-imgs com](https://user-images.githubusercontent.com/230566/72765182-f4222380-3c36-11ea-9225-3d9812f818b2.png)

![slack-imgs com-2](https://user-images.githubusercontent.com/230566/72765187-f71d1400-3c36-11ea-9f92-8ef1a4bff811.png)

**Expected behavior**
No extra load for a gateway that isn't in use.

- I'm unsure why you would need to init admin form fields on every pageload, rather than only when editing the gateway
- If you have to, it should at least check COD is active before running intensive code
- The same issue may exist with other payment gateways (at a glance they don't seem to)
- The performance probably needs fixing because if enabled, it's excessive

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Happens on a blank install with only WC & 2020 theme running

**Comment by ObliviousHarmony** [comment]
Thanks for catching this one!
