### ISSUE TITLE
Logout behaviour via My Account isn't consistent 

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce#25433]
**Describe the bug**

2647076-zen

Pressing logout via a menu item returns a message - `Are you sure you want to log out? Confirm and log out`.

Pressing the [submenu button `logout`](https://github.com/woocommerce/woocommerce/blob/2e61321e2a6b89d89de92b0270c6cd0e00a44ea9/includes/wc-account-functions.php#L95) or the [`not %1$s? <a href="%2$s">Log out</a>`](https://github.com/woocommerce/woocommerce/blob/2e61321e2a6b89d89de92b0270c6cd0e00a44ea9/templates/myaccount/dashboard.php#L29) immediate logs the customer out. 

Any menu link added via the Customizer has one nonce, and the My Account links have another nonce. 

When the `Are you sure you want to log out? Confirm and log out` is shown, `log out` is now linked to the same nonce as the other two. 

**To Reproduce**
1. Go to [site]/my-account
2. Click on a Logout menu item
3. See that the confirmation message is shown
4. Refresh page
5. Click on the Submenu item or the "not you" link
6. Notice that the customer is logged out

**Screenshots**

![woo_logout_nonce](https://user-images.githubusercontent.com/52214/72754341-6fe08980-3bbf-11ea-98ff-31857190770c.png)

Image link - https://d.pr/i/YNOgbi

**Expected behavior**

Pressing any logout button on the site presents the same behavior - one-click logout. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only the WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

Introduced in #15571

**WordPress Environment**
<details>
```
### WordPress Environment ###

WordPress address (URL): https://core.doug.press
Site address (URL): https://core.doug.press
WC Version: 3.8.1
REST API Version: ✔ 1.0.2
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.2.26
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.67.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.21-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 2.78MB
Database Data Size: 1.62MB
Database Index Size: 1.16MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.31MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.27MB + Index: 0.16MB + Engine InnoDB
wp_posts: Data: 0.31MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpml_mails: Data: 0.11MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Akismet Anti-Spam: by Automattic – 4.1.3
Homepage Control: by WooThemes – 2.0.3
Log Emails: by WebAware – 1.3.1
WooCommerce: by Automattic – 3.8.1

### Inactive Plugins (8) ###

Classic Editor: by WordPress Contributors – 1.5
Gutenberg: by Gutenberg Team – 7.2.0
Jetpack by WordPress.com: by Automattic – 8.1
Storefront Parallax Hero: by WooCommerce – 1.5.7
WooCommerce Blocks: by Automattic – 2.5.10
WooCommerce Royal Mail: by WooCommerce – 2.5.20
WooCommerce Stripe Gateway: by WooCommerce – 4.3.1
WP Mail Logging: by MailPoet – 1.9.5

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 3
Oldest: 2020-01-04 09:11:13 +0000
Newest: 2020-01-20 11:23:43 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

```
</details>

**Comment by juliaamosova** [comment]
Hi @dougaitken,

Thank you for taking the time reporting this issue, we really appreciate your help. I can reproduce it on my end. 

Added `Logout` WooCommerce endpoints custom link to the menu:

![menu1](https://user-images.githubusercontent.com/19143190/73383455-47444800-42c1-11ea-9fb5-77f74279d337.jpg)

At the front-end on the `My Account` page, clicked on the `Logout` WooCommerce endpoint custom link menu tab and was presented with the notice asking if I want to log out:

![menu2](https://user-images.githubusercontent.com/19143190/73383549-7064d880-42c1-11ea-9b17-2626a12b3638.jpg)

However, when I logged in again and clicked on one of the `Logout` options within `My Account` page, the notice asking me to confirm if I want to log out was not present:

![menu3](https://user-images.githubusercontent.com/19143190/73383662-a1450d80-42c1-11ea-9ff5-55dad5947e8c.jpg)

I was logged out right away:

![Screen Shot 2020-01-29 at 5 57 11 PM](https://user-images.githubusercontent.com/19143190/73383682-abffa280-42c1-11ea-9843-d2667c1a945c.png)

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by rodelgc** [comment]
We'll try to reproduce this on the current latest stable version of WooCommerce (version 5.9.0) to see if this issue is still happening. I'm adding the `status: needs reproduction` label for the meantime.

**Comment by swatipawarGS** [comment]
Hi @dougaitken ,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using WooCommerce 5.9.0 version. 

Please find below screencast for reference :

https://user-images.githubusercontent.com/94531721/146181282-c1e79cc3-8032-4ac5-8adf-3df8c4206f4d.mp4


Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.
