### ISSUE TITLE
Serbian Currency

### ISSUE THREAD

**Issue by WPAleks-PFS** [woocommerce/woocommerce#25441]
**Description**
Currency for Serbia is Dinar but in WooCommerce it’s  дин. and it should be рсд since that is the official currency symbol and by the law, we should display рсд in Serbian shops. Of course, it should stay as Cyrillic since that is our primary and official letter.
https://www.xe.com/currency/rsd-serbian-dinar

**Comment by StefanNieuwenhuis** [comment]
Isn't this already the case? See: https://github.com/woocommerce/woocommerce/blob/c92968582c436fe5ac19d6948c8fd51b23c25f7c/i18n/locale-info.php#L202

**Comment by WPAleks-PFS** [comment]
Noup, let me show you the problem.

![Screen Shot 2020-01-21 at 16 35 07](https://user-images.githubusercontent.com/53833972/72818748-4893c600-3c6c-11ea-9095-c9762386a51f.png)
![Screen Shot 2020-01-21 at 16 35 58](https://user-images.githubusercontent.com/53833972/72818749-4893c600-3c6c-11ea-89db-90e1a3ed7ed9.png)

You can see that in both places it's in Cyrillic дин.

**Comment by WPAleks-PFS** [comment]
It can't be changed in translation since I'm the translation editor and I looked for it but it's not possible since there is no translatable string.

**Comment by tammullen** [comment]
Hi @WPAleks-PFS,

Thank you for taking the time to share this idea, we really appreciate your help.
I agree we appear to be correctly using RSA as the currency code but converting it to дин (which is Cyrillic for the unofficial currency code of DIN). The correct Cyrillic for RSA is рсд.

I think this is where the Cyrillic conversion  is happening
https://github.com/woocommerce/woocommerce/blob/4434c4706e85f53a798e404a02a0deb05d6a7470/includes/wc-core-functions.php#L644

While this is clearly a great improvement/idea we won’t be able to tackle it in the upcoming weeks. We’re going to add it to our backlog where it will be considered for future releases.

Stay tuned for updates.

**Comment by WPAleks-PFS** [comment]
Thanks a lot for looking at it and I agree it's not urgent but it's by the Serbian law and developers need to override this issue which is not the greatest idea. However, at least we know that the fix is coming :)

**Comment by s28491** [comment]
> It can't be changed in translation since I'm the translation editor and I looked for it but it's not possible since there is no translatable string.

Try using snippet from woocommerce docs: https://docs.woocommerce.com/document/change-a-currency-symbol/, works for me. I needed a latin `din.` instead of cyrilic `дин.`.

**Comment by WPAleks-PFS** [comment]
> > It can't be changed in translation since I'm the translation editor and I looked for it but it's not possible since there is no translatable string.
> 
> Try using snippet from woocommerce docs: https://docs.woocommerce.com/document/change-a-currency-symbol/, works for me. I needed a latin `din.` instead of cyrilic `дин.`.

It’s not a permanent solution, you could use transliteration plugin to change cirylic to latin but explaining to a less tech savvy people to add snippet is not the best solution. However, it should be fixed for everyone who installs Woo
