### ISSUE TITLE
Missing filters for button texts in cart

### ISSUE THREAD

**Issue by rocketeer76** [woocommerce/woocommerce#25452]
**Describe the bug**
It's not possible to change the button texts on some buttons in cart using filters. I'm missing some filters similar to these:

woocommerce_order_button_text
woocommerce_product_single_add_to_cart_text

**Expected behavior**
I would like to have some filters such as these:

woocommerce_update_cart_button_text
woocommerce_continue_shopping_button_text
woocommerce_apply_coupon_button_text
woocommerce_proceed_to_checkout_button_text

So that you could do something like this:

/** Change text on continue shopping button at checkout **/
function woo_custom_continue_shopping_button_text( $button_text ) {
	return __('Any text goes here', 'woocommerce');
}
add_filter( 'woocommerce_continue_shopping_button_text', 'woo_custom_continue_shopping_button_text' );

**Comment by claudiosanches** [comment]
Please feel free to submit a Pull Request and we can evaluate the need of it, but those buttons are in templates, so you can already replace it by override templates.
Closing since there's already alternatives to achieve it.

**Comment by rocketeer76** [comment]
Templates are updated from time to time, filters not as often. I'm not a developer so I can't do a pull request.
