### ISSUE TITLE
Disable product variation to show up in WooCommerce product gallery below main image

### ISSUE THREAD

**Issue by justina-standaert** [woocommerce/woocommerce#25460]
If you go to one of my product pages https://canterburypottery.com/shop/product/dinner-plate-27-5cm/ you’ll see I have a product gallery below the featured image headed “Some examples”. Clicking on a thumb shows larger image which is what I want. But what I don’t want is if you click on a variation swatch it shows up as a first thumbnail in the gallery as well and actually replaces the first thumb of the gallery. It’s fine as a larger version above the gallery but I don’t want it to appear in the gallery as well and certainly not replacing the first thumbnail.

I Googled this problem and found that I'm not the only one that wants this sorted but I can't find the necessary coding to change it anywhere.  Please help!

Below are some screenshots:

![Image4](https://user-images.githubusercontent.com/60174447/72879776-e1beed00-3cfd-11ea-9aca-3601a66b0d46.jpg)
![Image3](https://user-images.githubusercontent.com/60174447/72879778-e1beed00-3cfd-11ea-9081-c8cf9d1a8910.jpg)
![Image2](https://user-images.githubusercontent.com/60174447/72879779-e1beed00-3cfd-11ea-8ae7-525f0e0458cd.jpg)
![Image1](https://user-images.githubusercontent.com/60174447/72879780-e2578380-3cfd-11ea-8bbc-3c776265331b.jpg)

**Comment by justina-standaert** [comment]
The screenshots I just uploaded are in reverse order and should be as follows:

![Image1](https://user-images.githubusercontent.com/60174447/72879869-1337b880-3cfe-11ea-9e62-3d244f993eaa.jpg)
![Image2](https://user-images.githubusercontent.com/60174447/72879874-16cb3f80-3cfe-11ea-9b79-00897f64004d.jpg)
![Image3](https://user-images.githubusercontent.com/60174447/72879889-1a5ec680-3cfe-11ea-9143-79bc39ac1b3a.jpg)
![Image4](https://user-images.githubusercontent.com/60174447/72879900-1e8ae400-3cfe-11ea-9997-692280499fb3.jpg)

**Comment by juliaamosova** [comment]
Hi @justina-standaert,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the 3rd party plugin that adds variations swatches.  

Please contact the author of the plugin directly for further help.
