### ISSUE TITLE
[3.9] trimming maxmind license key

### ISSUE THREAD

**Issue by Spreeuw** [woocommerce/woocommerce#25464]
**Describe the bug**
Using the 'copy' button on the maxwell license creating page after creating a license key ("the only time this key is displayed"), included whitespace before and after the key in my case (2 times in a row, using firefox). While this is an error on the Maxmind end, I believe this should be automatically trimmed by WooCommerce before validating, because as a user I can't see the license key on my clipboard and when I paste it in the license key field I can't see it includes whitespace because it's a password field.

**To Reproduce**
1. Go to Maxwell and generate a new license key
2. After the key is generated, click the copy to clipboard icon
3. Paste the license key in WooCommerce
4. License key does not validate

**Expected behavior**
Whitespace should be trimmed from the license key

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #25466.
