### ISSUE TITLE
[E2E] Create a package with Docker setup

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#25465]
**Is your feature request related to a problem? Please describe.**

Now that we have new e2e tests using Puppeteer running in Core, we need to create a package with Docker setup <strike>& WC helper functions</strike> for writing e2e tests so that it could be easily installed in other WC related projects. 

**Describe the solution you'd like**

There is a PR in progress to utilize a new shared Puppeteer's package that will contain general Puppeteer config files and helper functions for writing tests that are not specific to WooCommerce - see https://github.com/woocommerce/woocommerce/pull/25417. 

Once that PR is completed and merged, we need to work on the additional package that will contain:

- Docker setup for running e2e tests locally and on Travis
<strike>- WooCommerce related helper functions for writing e2e tests</strike>

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by juliaamosova** [comment]
Discussion: https://teamisotope.wordpress.com/2020/02/12/a-home-for-woocommerce-npm-packages/

**Comment by juliaamosova** [comment]
Current PR which will likely be moved to WooCore: https://github.com/woocommerce/woocommerce-admin/pull/3717

**Comment by juliaamosova** [comment]
According to `p90Yrv-1yE-p2/#comment-3654`, we decided that the package that will contain Docker setup for running e2e tests will live in the `wc-admin` repository.

**Comment by juliaamosova** [comment]
A final note that this package will "live" in WooCommerce Core as per: p7bje6-1UJ-p2. 

It is important to note that we should contribute to the @woocommerce/env package as much as possible so that it works for our needs as opposed to creating our own package:

https://github.com/WordPress/gutenberg/tree/master/packages/env

**Comment by nerrad** [comment]
Just noticed a typo in your comment @juliaamosova .  Did you mean "we should contribute to the `@wordpress/env` package"?

**Comment by juliaamosova** [comment]
@nerrad yes, a typo! Thanks for catching. Corrected.
