### ISSUE TITLE
Free Shipping not selected as default when eligible

### ISSUE THREAD

**Issue by gahsto** [woocommerce/woocommerce#25471]
When 'Free Shipping' is enabled as a shipping option conditional to $100+ purchase, Flat Rate is selected by default instead.

**Comment by claudiosanches** [comment]
Hi @gahsto,

In fact will select by default the first shipping option available, so you just need to rearrange your shipping methods putting free shipping at the top.

See an example:

![Screenshot_2020-01-23 Shipping ‹ Settings ‹ WooCommerce Dev — WooCommerce](https://user-images.githubusercontent.com/1264099/73020327-2a60ce00-3e04-11ea-93f5-728fac4322b8.png)

**Comment by gahsto** [comment]
Hi Claudio,
Yes I have them in the correct order. This seems to be an issue that has
been ongoing for years:
https://github.com/woocommerce/woocommerce/issues/11551
Please advise.
[image: Screen Shot 2020-01-23 at 4.04.36 PM.png]

**Comment by gahsto** [comment]
Hello, this item is not "closed" as your proposed solution does not work.
Please advise.

**Comment by claudiosanches** [comment]
@gahsto this is not an issue on WooCommerce, also what I said solves the problem.

**Comment by gahsto** [comment]
@claudiosanches it does not solve the problem as I have it configured according to your specs in the screen shot above. Free shipping is not selected by default even though the conditions have been met.
It defaults to Standard shipping.
Please advise.
![Screen Shot 2020-01-27 at 2 24 37 PM](https://user-images.githubusercontent.com/38016279/73206380-d0684d00-4110-11ea-94e9-46e6497c61b9.png)

**Comment by gahsto** [comment]
@claudiosanches it is an issue.
As you can see below I have it configured as suggested, yet the cart does not update with free shipping selected. It works if I meet the conditions when adding the first product, but if I 'Continue Shopping' without initially meeting the condition then add products afterward to meet it, it doesn't change.
![Screen Shot 2020-01-27 at 2 28 17 PM](https://user-images.githubusercontent.com/38016279/73206808-9b102f00-4111-11ea-80d8-b4b3af11ed5e.png)
![Screen Shot 2020-01-27 at 2 24 37 PM](https://user-images.githubusercontent.com/38016279/73206809-9b102f00-4111-11ea-9273-aa394e01ddbb.png)

**Comment by gahsto** [comment]
?
