### ISSUE TITLE
Inform that WC notices functions have changed in 3.9.0

### ISSUE THREAD

**Issue by yoancutillas** [woocommerce/woocommerce#25475]
The `includes/wc-notice-functions.php` file version and its functions are still flagged as `@version 2.1.0`, even though a lot of its functions have changed in 3.9.0.
Now we set and get $data in addition to the notice message, which breaks all plugins parsing the result of wc_get_notices for example.

Is it possible to simply add a `@version 3.9.0` in the description of the functions that have changed? :)

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #25477.
