### ISSUE TITLE
Force SSL for Checkout options missing

### ISSUE THREAD

**Issue by seb86** [woocommerce/woocommerce#25483]
I'm setting up a demo site with a fresh install of WooCommerce v3.9 and I find the options to force SSL for checkout are not showing in the advanced section of the settings. I checked the DOM and all that shows is an empty table between the page setup and checkout endpoints.

![Screenshot_2020-01-24 Advanced ‹ Settings ‹ CoCart Demo — WooCommerce](https://user-images.githubusercontent.com/497406/73078382-5b073d00-3ec2-11ea-80d3-00630c918b1a.png)

Any idea why? I have pasted my system report below.

------

`
### WordPress Environment ###

WordPress address (URL): https://wp-demo.cocart.xyz
Site address (URL): https://wp-demo.cocart.xyz
WC Version: 3.9.0
REST API Version: ✔ 1.0.6
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.33 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1d-fips

SUHOSIN Installed: –
MySQL Version: 5.7.25-28-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.0
WC Database Prefix: wp_
Total Database Size: 3.84MB
Database Data Size: 2.22MB
Database Index Size: 1.62MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.08MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.16MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_redirection_404: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 25
customize_changeset: 2
nav_menu_item: 4
page: 7
post: 2
product: 19
product_variation: 7
revision: 3
scheduled-action: 171
wp-rest-api-log: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

Akismet Anti-Spam: by Automattic – 4.1.3
CoCart: by Sébastien Dumont – 2.0.6 – Not tested with the active version of WooCommerce
CoCart Pro (Trial): by Sébastien Dumont – 1.0.0 – Not tested with the active version of WooCommerce
Disable Administration Email Verification Prompt: by ModularWP – 1.0.2
Disable Emails: by WebAware – 1.6.1
Disable Search: by Scott Reilly – 1.7.2
Jetpack by WordPress.com: by Automattic – 8.1.1
JWT Authentication for WP-API: by Enrique Chavez – 1.2.6
Login Designer: by Rich Tabor – 1.2.4
Redirection: by John Godley – 4.6.2
REST API Toolbox: by Pete Nelson – 1.4.2
SG Optimizer: by SiteGround – 5.4.3
Storefront Footer Copyright Text: by Storefront Footer Text – 1.0.0
WooCommerce Blocks: by Automattic – 2.5.11 – Not tested with the active version of WooCommerce
PayPal PLUS for WooCommerce: by Inpsyde GmbH – 2.1.0 – Not tested with the active version of WooCommerce
WooCommerce Admin: by WooCommerce – 0.24.0 – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.18 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.3.1 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.9.0
WP Clean Admin Menu: by P. Roy – 1.0.1
WP REST API Controller: by YIKES
Inc. – 2.0.3

REST API Log: by Pete Nelson – 1.6.7
WP-REST-API V2 Menus: by Claudio La Barbera – 0.7.5

### Inactive Plugins (3) ###

Application Passwords: by George Stephanis – 0.1.1
WordPress REST API Authentication: by miniOrange – 1.3.3
WP OAuth Server: by WP OAuth Server – 3.7.92

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #19 - /
Cart: #20 - /cart/
Checkout: #21 - /checkout/
My account: #22 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 168
Oldest: 2020-01-20 02:36:39 +0100
Newest: 2020-01-24 15:59:00 +0100

Pending: 2
Oldest: 2020-01-24 15:59:08 +0100
Newest: 2020-01-24 16:20:53 +0100

Canceled: 1
Oldest: 2020-01-22 18:23:24 +0100
Newest: 2020-01-22 18:23:24 +0100

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

**Comment by seb86** [comment]
Found a previous issue explaining the function used to determin if the site has SSL but if SSL is forced already should it not be ticked in the system status?

![Screenshot_2020-01-24 System status ‹ Status ‹ CoCart Demo — WooCommerce](https://user-images.githubusercontent.com/497406/73079160-05339480-3ec4-11ea-8160-72956501ae89.png)

**Comment by claudiosanches** [comment]
If you already use HTTPS for all pages the "Force SSL" option will be removed from the settings, since there's no use for you.
Also "forcing" SSL will cause some redirections on PHP, so it's nice to know about it on the System status, but if you have already configured to have HTTPS for all your website, we don't really need to care about the Force SSL.
