### ISSUE TITLE
Add user capabilities for admin user roles in default woocommerce

### ISSUE THREAD

**Issue by itsgauravjain22** [woocommerce/woocommerce#25486]
**Is your feature request related to a problem? Please describe.**
The problem is that I can't share full admin portal with some less privileged admin user like only view all products/view only his product, add products, edit all products/edit his published products. There's very limited definition of user roles in woocommerce and likely boolean definition of fine grained user capabilities.

**Describe the solution you'd like**
A super admin should have unrestricted access as it's now Admin has. Super Admin can define other less privileged user roles with separate user capabilities. Following capabilities should be there:
- View all products
- Add Products
- Edit all products
- Delete all products
- View his products
- Edit his Products
- Delete his products
- View all orders
- View only orders in which his products is included.
- Edit all orders

In simple term, a role can manage all products/order (like editor in wordpress), another role can manage his products/orders (like author in wordpress). And these roles can be super admin defined with proper user capabilities.

Then we could presumably make woocommerce better than it is by giving sepate user to manage it's portfolio. I know it's similar to what product vendor has to offer but vendor management is a lot more than just having fine grained user capability roles. The rest API should follow these user capabilities with defined user roles tied with generated user credentials. This would make easier to develop further application using woocommerce as backend.

**Describe alternatives you've considered**
No suitable alternative available. I have considered using product vendors extension but they don't have rest API support plus there're too much unnecessary functionalities like vendor commission and more. With other third party multivendor plugin, they have very different rest API along with other woocommerce plugins incompatible.
Tried third party user role capabilities plugin but again rest API don't respect those user capabilities. I think Admin capabilities should be inbuilt in woocommerce so that rest API could be exposed properly.

**Additional context**
Rest API/Graph QL opens doors for endless possibilities. But current user capabilities can just have boolean roles. Either you can view products or write (add/Edit) products. There's nothing we can control in context of user roles and capabilities. The gap should be filled.

**Comment by claudiosanches** [comment]
Hi {username},

Thank you for taking the time to share this idea, we really appreciate your help, but there's already alternatives for it.

> No suitable alternative available. I have considered using product vendors extension but they don't have rest API support plus there're too much unnecessary functionalities like vendor commission and more. With other third party multivendor plugin, they have very different rest API along with other woocommerce plugins incompatible.
> Tried third party user role capabilities plugin but again rest API don't respect those user capabilities. I think Admin capabilities should be inbuilt in woocommerce so that rest API could be exposed properly.

There's a lot of alternatives, you don't even need plugins, you can write your own if you like.
WordPress give you freedom to include new user roles, with any capability that you want, and also WooCommerce REST API includes several filters to manipulate how authentication is made based on user permissions/capabilities.
So if you are including new user roles or capabilities, you can just easily set it for the WooCommerce REST API using the `woocommerce_rest_check_permissions` filter.

See an example of how to use this filter:

```php
/**
 * Check permissions.
 *
 * @param bool $permission If have permissions.
 * @param string $context Permission context, possible values: 'read', 'create', 'edit', 'delete', and 'batch'.
 * @param int $object_id Object ID.
 * @param string $object_type Object type, e.g. product, order, customer, and so on.
 * @return bool
 */
function mycustom_woo_rest_check_permissions( $permission, $context, $object_id, $object_type ) {
    if ( ! in_array( $object_type, array( 'product', 'product_variation' ), true ) ) {
        return  $permission;
    }

    // Change the follow list with your store's new user capabilities.
	$contexts = array(
		'read'   => 'read_private_posts',
		'create' => 'publish_posts',
		'edit'   => 'edit_post',
		'delete' => 'delete_post',
		'batch'  => 'edit_others_posts',
	);

    // We don't allow access to revisions on the REST API, since we don't even enable revisions on WooCommerce.
	if ( 'revision' === $post_type ) {
		$permission = false;
	} else {
		$cap              = $contexts[ $context ];
		$post_type_object = get_post_type_object( $object_type );
		$permission       = current_user_can( $post_type_object->cap->$cap, $object_id );
	}

    return $permission;
}

add_filter( 'woocommerce_rest_check_permissions', 'mycustom_woo_rest_check_permissions', 10, 4 );
```

Also we are looking into WooCommerce's current user roles, but for now we shouldn't change anything related for it.

**Comment by itsgauravjain22** [comment]
Thanks @claudiosanches for the prompt reply. What I meant was to have those capabilities defined in graphical user interface of backend admin portal of woocommerce. I was interested in just consuming those rest API and wish it would be included in woocommerce backend.
Well I really appreciate for the function you provide. I lack knowledge of woocommerce programming. So I would first learn woocommerce/wordpress backend code then I will get back to you.
Thank again.

**Comment by itsgauravjain22** [comment]
Hi @claudiosanches , Could you please inform me which capability is needed for displaying private product. I want ```/wp-json/wc/v3/products?page=1&per_page=20``` to show only those products which are added by that user.

I tried ```read_private_products```, but it list all the products which are posted by another user as well. So what's the purpose of this capability.

I tried ```read_private_posts``` thinking it would list only those products that are created from that user. But its totally independent from woocommerce capabilities.
