### ISSUE TITLE
Shipping label hangs on Purchasing

### ISSUE THREAD

**Issue by Streeter1981** [woocommerce/woocommerce#25498]
**Describe the bug**
When purchasing a new shipping label via Woocommerce for an order, it just hangs on “Purchasing …”.

I’ve validated that it is indeed charging my bank account for the purchase and even receive email receipt from Woocommerce on the label purchase. . If I go back to the Order screen, it also just shows “Purchasing …” and doesn’t show the actual label.

This happens on any browser, all latest versions.

**To Reproduce**
1. Go to any order
2. Click Create Shipping label, complete the form
3. Click Buy shipping labels
4. "Purchasing ... " shows, never completes. 

**Screenshots**
![5B702C95-9D34-4B2F-BA95-2D1424754102](https://user-images.githubusercontent.com/8643441/73142156-d135ac00-4048-11ea-87a9-b683cfafbf0b.GIF)

![image](https://user-images.githubusercontent.com/8643441/73142164-de529b00-4048-11ea-9876-bf5a8fa71f6b.png)

**Expected behavior**
Purchasing should complete, with a button to Print label

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with [Storefront](https://woocommerce.com/storefront/) theme.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WordPress Version 5.3.2

```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
`
### WordPress Environment ###

WordPress address (URL): https://superherodiy.com
Site address (URL): https://superherodiy.com
WC Version: 3.9.0
REST API Version: ✔ 1.0.6
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.26
PHP Post Max Size: 260 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.67.0
OpenSSL/1.0.2t

SUHOSIN Installed: –
MySQL Version: 5.7.23-23
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.0
WC Database Prefix: e80_
Total Database Size: 17.08MB
Database Data Size: 14.91MB
Database Index Size: 2.17MB
e80_woocommerce_sessions: Data: 1.65MB + Index: 0.09MB + Engine MyISAM
e80_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
e80_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_woocommerce_order_items: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
e80_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.05MB + Engine MyISAM
e80_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_alm: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
e80_comments: Data: 0.06MB + Index: 0.04MB + Engine MyISAM
e80_failed_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_icwp_wpsf_audit_trail: Data: 0.18MB + Index: 0.01MB + Engine MyISAM
e80_icwp_wpsf_events: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
e80_icwp_wpsf_geoip: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_icwp_wpsf_ip_lists: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_icwp_wpsf_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_icwp_wpsf_scanner: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_icwp_wpsf_scanq: Data: 2.06MB + Index: 0.00MB + Engine MyISAM
e80_icwp_wpsf_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_icwp_wpsf_traffic: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_mailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_options: Data: 2.77MB + Index: 0.09MB + Engine MyISAM
e80_postmeta: Data: 3.13MB + Index: 0.70MB + Engine MyISAM
e80_posts: Data: 1.18MB + Index: 0.10MB + Engine MyISAM
e80_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_sbi_instagram_feeds_posts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_sbi_instagram_posts: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
e80_smush_dir_images: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_termmeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
e80_terms: Data: 0.01MB + Index: 0.04MB + Engine MyISAM
e80_term_relationships: Data: 0.04MB + Index: 0.08MB + Engine MyISAM
e80_term_taxonomy: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
e80_tm_taskmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_tm_tasks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_usermeta: Data: 0.18MB + Index: 0.11MB + Engine MyISAM
e80_users: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
e80_w3tc_cdn_pathmap: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_w3tc_cdn_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_wcpdf_invoice_number: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_wc_product_meta_lookup: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
e80_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
e80_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_wfblockediplog: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_wfblocks7: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_wfconfig: Data: 0.38MB + Index: 0.02MB + Engine MyISAM
e80_wfcrawlers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_wffilechanges: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_wffilemods: Data: 1.93MB + Index: 0.42MB + Engine MyISAM
e80_wfhits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_wfhoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_wfissues: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
e80_wfknownfilelist: Data: 0.99MB + Index: 0.13MB + Engine MyISAM
e80_wflivetraffichuman: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_wflocs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_wflogins: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
e80_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
e80_wfnotifications: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_wfpendingissues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_wfreversecache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_wfsnipcache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_wfstatus: Data: 0.07MB + Index: 0.04MB + Engine MyISAM
e80_wftrafficrates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_woobe_history: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_woobe_history_bulk: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
e80_yoast_seo_links: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
e80_yoast_seo_meta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
puu_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
puu_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
puu_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
puu_options: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
puu_postmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
puu_posts: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
puu_termmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
puu_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
puu_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
puu_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
puu_usermeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
puu_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM

### Post Type Counts ###

advgb_profiles: 1
attachment: 498
custom_css: 2
foogallery: 7
jetpack_migration: 2
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
jp_vid_sitemap: 2
nav_menu_item: 18
oembed_cache: 3
page: 10
post: 90
product: 252
product_variation: 27
pt_view: 1
scheduled-action: 15
shop_order: 88
shop_order_refund: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Shield Security: by Shield Security – 8.5.1
Cloudflare: by John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.4.1

Customer Reviews for WooCommerce: by ivole – 3.94 – Not tested with the active version of WooCommerce
Display PHP Version: by David Gwyer – 1.5
Smash Balloon Instagram Feed: by Smash Balloon – 2.1.5
Jetpack by WordPress.com: by Automattic – 8.1.1
MOJO Marketplace: by Mike Hansen – 1.5
PHP Compatibility Checker: by WP Engine – 1.5.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.18 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.22.3
WooCommerce: by Automattic – 3.9.0
Yoast SEO: by Team Yoast – 12.9.1
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.0.15

WP YouTube Lyte: by Frank Goossens (futtta) – 1.7.11
Embed Plus for YouTube - Gallery, Channel, Playlist, Live Stream: by Embed Plus for YouTube Team – 13.2.0.1

### Inactive Plugins (2) ###

Anti-Malware Security and Brute-Force Firewall: by Eli Scheetz – 4.19.50
Heartbeat Control by WP Rocket: by WP Rocket – 2.0

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (2) ###

Endurance Page Cache: by Mike Hansen – 1.6
SSO: by Garth Mortensen
Mike Hansen – 0.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #11 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 13
Oldest: 2019-12-28 13:33:04 -0700
Newest: 2020-01-26 14:00:57 -0700

Pending: 2
Oldest: 2020-02-01 13:40:21 -0700
Newest: 2020-02-01 13:40:22 -0700

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by dougaitken** [comment]
Hi @Streeter1981 

Did this happen just before you opened this issue? 

Shipping Labels are part of the WooCommerce Services extension and not part of WooCommerce Core so I'm closing this issue. 

Please do reach out via your WooCommerce.com account here - https://woocommerce.com/my-account/create-a-ticket/ - we will take a look into this.

Thanks!

**Comment by Anoroc** [comment]
Hi @Streeter1981 
Did you ever find a solution to this? I've been experiencing the same issue for some time now. I've failed to find a realistic solution to the problem, and support (via Woocommerce or my host) haven't been able to produce a solution, either. 

Thanks!
