### ISSUE TITLE
country dropdown border 1 pixel too wide

### ISSUE THREAD

**Issue by njwgh** [woocommerce/woocommerce#25495]
The border of the dropdown on the 'country' field on the checkout page is 1 pixel too wide on the right hand side

**To Reproduce**

1. go to https://themes.woocommerce.com/storefront/checkout/
2. add a product to cart and go to checkout page
3. Click in the 'country' field to select a country

It seems to be dependent on the width of your browser window
As you drag the browser narrower and wider you can see it sometimes being the correct width and sometimes being too wide. So I guess a 'rounding' error when calculating the width?

**Screenshots**

![woocommerce-country-dropdown](https://user-images.githubusercontent.com/6837919/73136579-3d44fe00-40a3-11ea-95f8-f84c1ad4095c.png)

**Expected behavior**
Width of dropdown should match the select box 

**Isolating the problem (mark completed items with an [x]):**
this occurs on the demo storefront site:
https://themes.woocommerce.com/storefront/checkout/
Using Chrome browser (Version 79.0.3945.130) , Microsoft edge browser , Opera browser on Windows 10 - depending on width of browser window

**Comment by franticpsyx** [comment]
Thanks for reporting this @njwgh  

This is an issue in the way `select2` calculates the dropdown width. For anyone who wants to patch this one in `selectWoo`, have a look at the `_resizeDropdown` function. We need to replace:

```
    var css = {
      width: this.$container.outerWidth(false) + 'px'
    };
```

with

```
    var css = {
      width: this.$container[ 0 ].getBoundingClientRect().width + 'px';
    };
```

While we are at it, it might be a good idea if someone built an `npm` package out of `selectWoo`, as currently there is no automated way to pull the library into WC during the build stage. In the past it has been unclear to us where to contribute fixes (here on in the `selectWoo` repo) for this reason. The styles are also scattered around different files -- some fixes/overrides are in admin css, and some in the `selectWoo` css.

**Comment by juliaamosova** [comment]
Hi @njwgh,

Thank you for taking the time reporting this bug, we really appreciate your help. I can reproduce it on my end. 

![pixel](https://user-images.githubusercontent.com/19143190/73353210-c79b8680-428a-11ea-8735-a792cfb47539.jpg)

@franticpsyx thanks for your feedback and comment as well. 

We are aware of this issue but it had not been a priority for us to work on just yet. We consider creating a package out of `selectWoo` as well. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by rodelgc** [comment]
We'll try to reproduce this on the current latest stable version of WooCommerce (version 5.9.0) to see if this issue is still happening. I'm adding the `status: needs reproduction` label for the meantime.

**Comment by swatipawarGS** [comment]
Hi @njwgh ,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using WooCommerce 5.9.0 version and WordPress 5.8.2 version.

Please find below screenshot for reference :

![#25495](https://user-images.githubusercontent.com/94531721/146152188-18d71733-0d1b-4576-9461-f3318cc31cc5.jpg)


Please provide us more detailed and any additional steps required to repro this issue which may help us to evaluate it further.

**Comment by njwgh** [comment]
I agree. I am no longer able to reproduce this.
