### ISSUE TITLE
Able to create manual order for variation with zero stock and backorder not allowed 

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#25518]
**Describe the bug**

Able to create manual order for variation with zero stock and backorder not allowed. 

Originally reported in the comment in https://github.com/woocommerce/woocommerce/issues/25415 but since the original issue was slightly different, I opened a new issue to document confirmed bug. 

**To Reproduce**

1. Set up a variable product, the stock is handled on level variation, do not allow backorders and set the stock to 0.
2. Add a manual order, choose the variation with stock 0. The product will be added and the stock will be reduced by the given amount.

**Screenshots**

A variation where stock is managed at the level of the variation with backorders not allowed:

![var1](https://user-images.githubusercontent.com/19143190/73288895-b81d2e80-41f3-11ea-9d1b-ec56464520c1.jpg)

Placing manual order - I can select variation with zero stock and backorders not allowed:

![var2](https://user-images.githubusercontent.com/19143190/73288944-c8cda480-41f3-11ea-8614-98e0c80d7f59.jpg)

Order is created - stock is being reduced:

![var3](https://user-images.githubusercontent.com/19143190/73288995-d71bc080-41f3-11ea-9561-990481fdc055.jpg)

Variation now has a negative stock even though backorders were not allowed:

![var4](https://user-images.githubusercontent.com/19143190/73289031-e569dc80-41f3-11ea-8484-dd4b83903311.jpg)

**Expected behavior**

I expected not to be able to place a manual order for the variation that has zero stock with backorders not allowed. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://jamosova2.mystagingwebsite.com
Site address (URL): https://jamosova2.mystagingwebsite.com
WC Version: 3.9.0
REST API Version: ✔ 1.0.6
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.2.27
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.68.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.21-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.0
WC Database Prefix: wp_
Total Database Size: 7.69MB
Database Data Size: 4.23MB
Database Index Size: 3.46MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.16MB + Index: 0.16MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.20MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 1.52MB + Index: 1.88MB + Engine InnoDB
wp_posts: Data: 0.41MB + Index: 0.22MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 202
customize_changeset: 1
jetpack_migration: 2
jp_img_sitemap: 3
jp_sitemap: 3
jp_sitemap_master: 3
page: 7
post: 1
product: 234
product_variation: 176
revision: 17
scheduled-action: 60
shop_coupon: 4
shop_order: 79
shop_order_refund: 15

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Query Monitor: by John Blackbourn – 3.5.2
Jetpack by WordPress.com: by Automattic – 8.1.1
WooCommerce Beta Tester: by WooCommerce – 2.0.1 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.3.1 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.9.0 – 3.9.1 is available

### Inactive Plugins (16) ###

Akismet Anti-Spam: by Automattic – 4.1.3
Gutenberg: by Gutenberg Team – 7.1.0
Storefront Powerpack: by WooCommerce – 1.5.0
SVG Support: by Benbodhi – 2.3.15
WooCommerce Admin: by WooCommerce – 0.24.0 – Not tested with the active version of WooCommerce
WooCommerce Blocks: by Automattic – 2.5.2 – Not tested with the active version of WooCommerce
WooCommerce Customer/Order CSV Export: by SkyVerge – 4.3.5 – Not tested with the active version of WooCommerce
WooCommerce Deposits: by Automattic – 1.3.3 – Not tested with the active version of WooCommerce
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.10 – Not tested with the active version of WooCommerce
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.0.3 – 2.3.6 is available – Not tested with the active version of WooCommerce
WooCommerce Print Invoices/Packing Lists: by SkyVerge – 3.6.1 – Not tested with the active version of WooCommerce
WooCommerce Product Add-ons: by WooCommerce – 2.9.7 – Not tested with the active version of WooCommerce
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.11.2 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.22.2 – 1.22.3 is available – Not tested with the active version of WooCommerce
WooCommerce Store Catalog PDF Download: by WooCommerce – 1.0.8 – Not tested with the active version of WooCommerce
WP Migrate DB: by Delicious Brains – 0.9.2

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: Query Monitor Database Class
object-cache.php: Memcached

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 58
Oldest: 2020-01-07 09:40:49 -0500
Newest: 2020-01-29 05:50:52 -0500

Pending: 0
Oldest: –
Newest: –

Canceled: 2
Oldest: 2020-01-14 18:00:40 -0500
Newest: 2020-01-20 12:48:52 -0500

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by juliaamosova** [comment]
Noting here that the issue happens not only with variable products/variations but with simple products as well.

**Comment by ObliviousHarmony** [comment]
Hey @juliaamosova,

I wonder if this is actually something we should change? My thinking is that a merchant may knowingly do this after making a sale via chat or email but not want users to be able to backorder the product under normal circumstances. What do you think?

**Comment by KoolPal** [comment]
@ObliviousHarmony As a store owner this is NOT a bug but a desired feature for the same as reason as explained by you.

Else think about the mess for the store owner. Increase stock by 1 and then rush to make a manual order and hope that nobody purchases by then!
Additional mess if store owner has some plugin which sends out some "back in stock" notification email.

Please do NOT change this! Thanks.

**Comment by juliaamosova** [comment]
Thanks for questioning the issue @ObliviousHarmony and thanks for providing your feedback @KoolPal. 

I am pinging @thomas-zg here for feedback who originally reported the issue: https://github.com/woocommerce/woocommerce/issues/25415#issuecomment-577407094. 

I am not a store owner myself so it's hard for me to tell what is best. I do think that it doesn't make sense to be able to place manual order for the item that is out of stock and for which backorders are not allowed. It negates the purpose of having stock management in the first place.

**Comment by KoolPal** [comment]
@juliaamosova Some quick notes:
1. The OP @ashraffarag reported this issue which could not be replicated.
2. @thomas-zg chimed in mentioning this could be replicated via Manual Order
3. Manual orders are Store owner / admin controlled. They **should know** what they are doing.
4. The scenario explained does not seem to be a normal situation in any day-to-day operations in any online store.
5. We should not make changes to the system which prevents Store owners from making some conscious decisions / actions.
6. If we prevent Manual order for OOS items the alternate process is painful as explained by me here: https://github.com/woocommerce/woocommerce/issues/25518#issuecomment-658507580 

In case you do propose to go ahead with preventing such manual orders for OOS, please be kind enough to provide for some option to allow this as well.

Thanks

**Comment by rrennick** [comment]
> I do think, however, that it doesn't make sense to be able to place manual order for the item that is out of stock and for which backorders are not allowed.

As a store owner I don't want our customers to be able to back order. But I want to be able to put stock on hold for a customer so that when a new shipment arrives the stock will be allocated for that customer.

**Comment by juliaamosova** [comment]
Thanks for your additional feedback @KoolPal. @rrennick thanks for your feedback as well. Both are very helpful. It sounds like we should leave this functionality the way it is. Let's close this issue, for now, as-is, and will evaluate further in case more feedback will be received asking for a change instead.

**Comment by michalmarek-sk** [comment]
Hi guys, I'm facing the same issue and let's say that it's fine when the backorders are allowed for admin/owner but for creating of order there is one attribute called 'customer_id' and there is a default value 0 meaning the guest is creating an order so why it is not restricted at least for them or users not being admin/owner or am I missing something?

**Comment by IDJGILL** [comment]
> Hi guys, I'm facing the same issue and let's say that it's fine when the backorders are allowed for admin/owner but for creating of order there is one attribute called 'customer_id' and there is a default value 0 meaning the guest is creating an order so why it is not restricted at least for them or users not being admin/owner or am I missing something?

I was about to ask the same question. Thanks
