### ISSUE TITLE
Site Crash with Advanced Product Labels Extension

### ISSUE THREAD

**Issue by gettek** [woocommerce/woocommerce#25513]
**Describe the bug**
Update to 3.9.1 causes WordPress crash when using [WooCommerce Advanced Product Labels Extension](https://woocommerce.com/products/woocommerce-advanced-product-labels/)

**To Reproduce**
1. Enable WooCommerce Advanced Product Labels Extension
2. Upgrade Woocommerce from 3.9.0 to 3.9.1
3. WordPress will fail to load
4. Enable debugging results in the below output to **debug.log**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Latest WordPress Installed
```
[28-Jan-2020 23:19:07 UTC] PHP Fatal error:  Uncaught Error: Class 'WAPL_Admin' not found in /var/www/sitename.co.uk/htdocs/wp-content/plugins/woocommerce-advanced-product-lab
els/woocommerce-advanced-product-labels.php:119
Stack trace:
#0 /var/www/sitename.co.uk/htdocs/wp-content/plugins/woocommerce-advanced-product-labels/woocommerce-advanced-product-labels.php(201): Woocommerce_Advanced_Product_Labels->ini
t()
#1 /var/www/sitename.co.uk/htdocs/wp-settings.php(360): include_once('/var/www/elegan...')
#2 /var/www/sitename.co.uk/wp-config.php(81): require_once('/var/www/elegan...')
#3 /var/www/sitename.co.uk/htdocs/wp-load.php(42): require_once('/var/www/elegan...')
#4 /var/www/sitename.co.uk/htdocs/wp-admin/admin.php(34): require_once('/var/www/elegan...')
#5 /var/www/sitename.co.uk/htdocs/wp-admin/index.php(10): require_once('/var/www/elegan...')
#6 {main}
  thrown in /var/www/sitename.co.uk/htdocs/wp-content/plugins/woocommerce-advanced-product-labels/woocommerce-advanced-product-labels.php on line 119
[28-Jan-2020 23:19:37 UTC] PHP Fatal error:  Uncaught Error: Class 'WAPL_Post_Type' not found in /var/www/sitename.co.uk/htdocs/wp-content/plugins/woocommerce-advanced-product
-labels/woocommerce-advanced-product-labels.php:128
Stack trace:
#0 /var/www/sitename.co.uk/htdocs/wp-content/plugins/woocommerce-advanced-product-labels/woocommerce-advanced-product-labels.php(201): Woocommerce_Advanced_Product_Labels->ini
t()
#1 /var/www/sitename.co.uk/htdocs/wp-settings.php(360): include_once('/var/www/elegan...')
#2 /var/www/sitename.co.uk/wp-config.php(81): require_once('/var/www/elegan...')
#3 /var/www/sitename.co.uk/htdocs/wp-load.php(42): require_once('/var/www/elegan...')
#4 /var/www/sitename.co.uk/htdocs/wp-blog-header.php(13): require_once('/var/www/elegan...')
#5 /var/www/sitename.co.uk/htdocs/index.php(17): require('/var/www/elegan...')
#6 {main}
  thrown in /var/www/sitename.co.uk/htdocs/wp-content/plugins/woocommerce-advanced-product-labels/woocommerce-advanced-product-labels.php on line 128
```
</details>

**Comment by juliaamosova** [comment]
Hi @gettek,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the [WooCommerce Advanced Product Labels](https://woocommerce.com/products/woocommerce-advanced-product-labels/) plugin which is one of the paid products on our marketplace. To get further technical support for it, please contact the WooCommerce helpdesk by [opening a ticket](https://woocommerce.com/contact-us/).

**Comment by gettek** [comment]
Just being a good samaritan here; paid or unpaid it's clear the upgrade to WooCommerce introduced an incompatibility within your product chains.
