### ISSUE TITLE
Database update issue after recent Woocommerce update

### ISSUE THREAD

**Issue by pgamaster** [woocommerce/woocommerce#25533]
**Describe the bug**
Database update stuck, no progress, pending status. 
woocommerce_run_update_callback is waiting:
'update_callback' => 'wc_update_390_move_maxmind_database'
'update_callback' => 'wc_update_390_change_geolocation_database_update_cron'
'update_callback' => 'wc_update_390_db_version'
The recent woocommerce update caused the issue.

Same issue:
https://wordpress.org/support/topic/database-updating-pending/
https://wordpress.org/support/topic/woocommerce-db-updates-remain-pending-when-woocommerce-ddbb-was-updated/

**To Reproduce**
Go to /wp-admin/admin.php?page=wc-status&tab=action-scheduler&s=woocommerce_run_update&status=pending

**Screenshots**
http://i.piccy.info/i9/d19bf4db6358e373efec307c7cca31a9/1580388396/117614/1357426/woobug1.jpg

**Expected behavior**
it must update the database

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://------.com
Site address (URL): http://-------.com
WC Version: 3.9.1
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: ru_RU
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.25 (Debian)
PHP Version: 7.2.13
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: 5.7.24
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ На вашем сервере не включён класс SoapClient - некоторые плагины шлюзов
использующие SOAP могут не работать как ожидалось.

DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: wp_
Общий размер базы данных: 144.93MB
Размер данных в базе данных: 95.11MB
Размер индекса базы данных: 49.82MB
wp_woocommerce_sessions: Данные: 2.52MB + Индекс: 0.05MB + Движок InnoDB
wp_woocommerce_api_keys: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_woocommerce_attribute_taxonomies: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_woocommerce_downloadable_product_permissions: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wp_woocommerce_order_items: Данные: 0.06MB + Индекс: 0.02MB + Движок InnoDB
wp_woocommerce_order_itemmeta: Данные: 0.20MB + Индекс: 0.22MB + Движок InnoDB
wp_woocommerce_tax_rates: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wp_woocommerce_tax_rate_locations: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_woocommerce_shipping_zones: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_woocommerce_shipping_zone_locations: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_woocommerce_shipping_zone_methods: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_woocommerce_payment_tokens: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_woocommerce_payment_tokenmeta: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_woocommerce_log: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_berocket_termmeta: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_braapf_product_stock_status_parent: Данные: 1.52MB + Индекс: 0.31MB + Движок InnoDB
wp_braapf_product_variation_attributes: Данные: 1.45MB + Индекс: 1.30MB + Движок InnoDB
wp_braapf_variation_attributes: Данные: 0.14MB + Индекс: 0.14MB + Движок InnoDB
wp_commentmeta: Данные: 0.06MB + Индекс: 0.03MB + Движок InnoDB
wp_comments: Данные: 0.22MB + Индекс: 0.09MB + Движок InnoDB
wp_failed_jobs: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_links: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_litespeed_img_optm: Данные: 0.02MB + Индекс: 0.09MB + Движок InnoDB
wp_litespeed_optimizer: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_mailchimp_carts: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_mailchimp_jobs: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_options: Данные: 9.14MB + Индекс: 2.39MB + Движок InnoDB
wp_pmxi_files: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_pmxi_history: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_pmxi_images: Данные: 0.06MB + Индекс: 0.00MB + Движок InnoDB
wp_pmxi_imports: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_pmxi_posts: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_pmxi_templates: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_postmeta: Данные: 44.58MB + Индекс: 29.11MB + Движок InnoDB
wp_posts: Данные: 15.52MB + Индекс: 7.91MB + Движок InnoDB
wp_queue: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_termmeta: Данные: 0.05MB + Индекс: 0.03MB + Движок InnoDB
wp_terms: Данные: 0.06MB + Индекс: 0.06MB + Движок InnoDB
wp_term_relationships: Данные: 2.45MB + Индекс: 1.45MB + Движок InnoDB
wp_term_taxonomy: Данные: 0.09MB + Индекс: 0.03MB + Движок InnoDB
wp_tm_taskmeta: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_tm_tasks: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_usermeta: Данные: 0.19MB + Индекс: 0.03MB + Движок InnoDB
wp_users: Данные: 0.02MB + Индекс: 0.05MB + Движок InnoDB
wp_wc_download_log: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_wc_product_meta_lookup: Данные: 2.52MB + Индекс: 4.27MB + Движок InnoDB
wp_wc_tax_rate_classes: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_wc_webhooks: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_wfblockediplog: Данные: 0.17MB + Индекс: 0.00MB + Движок InnoDB
wp_wfblocks7: Данные: 0.34MB + Индекс: 0.34MB + Движок InnoDB
wp_wfconfig: Данные: 0.44MB + Индекс: 0.00MB + Движок InnoDB
wp_wfcrawlers: Данные: 0.05MB + Индекс: 0.00MB + Движок InnoDB
wp_wffilechanges: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wffilemods: Данные: 2.52MB + Индекс: 0.00MB + Движок InnoDB
wp_wfhits: Данные: 1.52MB + Индекс: 0.16MB + Движок InnoDB
wp_wfhoover: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_wfissues: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wp_wfknownfilelist: Данные: 1.52MB + Индекс: 0.00MB + Движок InnoDB
wp_wflivetraffichuman: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_wflocs: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wflogins: Данные: 2.52MB + Индекс: 0.58MB + Движок InnoDB
wp_wfls_2fa_secrets: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_wfls_settings: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wfnotifications: Данные: 0.02MB + Индекс: 0.00MB + Движок InnoDB
wp_wfpendingissues: Данные: 0.02MB + Индекс: 0.06MB + Движок InnoDB
wp_wfreversecache: Данные: 0.05MB + Индекс: 0.00MB + Движок InnoDB
wp_wfsnipcache: Данные: 0.22MB + Индекс: 0.27MB + Движок InnoDB
wp_wfstatus: Данные: 0.11MB + Индекс: 0.09MB + Движок InnoDB
wp_wftrafficrates: Данные: 3.52MB + Индекс: 0.00MB + Движок InnoDB
wp_woobe_history: Данные: 0.02MB + Индекс: 0.05MB + Движок InnoDB
wp_woobe_history_bulk: Данные: 0.02MB + Индекс: 0.03MB + Движок InnoDB
wp_woof_query_cache: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_yoast_seo_links: Данные: 0.02MB + Индекс: 0.02MB + Движок InnoDB
wp_yoast_seo_meta: Данные: 0.44MB + Индекс: 0.00MB + Движок InnoDB

### Post Type Counts ###

amn_wpforms-lite: 1
attachment: 7788
br_filters_group: 1
br_product_filter: 8
custom_css: 1
customize_changeset: 13
nav_menu_item: 136
page: 19
post: 31
product: 2189
product_variation: 17287
revision: 185
scheduled-action: 6
shop_coupon: 1
shop_order: 142
wcps: 1
wpcf7_contact_form: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ❌
					В вашем магазине не используется HTTPS. Подробнее о HTTPS и SSL-сертификатах .
Hide errors from visitors: ✔

### Active Plugins (31) ###

Query Monitor: от John Blackbourn – 3.5.2
Ad Inserter: от Igor Funa – 2.6.2
AJAX Search for WooCommerce: от Damian Góra – 1.6.1
Autoptimize: от Frank Goossens (futtta) – 2.6.1
Classic Editor: от Участники разработки WordPress – 1.5
Cloudflare: от John Wineman
Furkan Yilmaz
Junade Ali (Cloudflare Team) – 3.4.1

Contact Form 7: от Takayuki Miyoshi – 5.1.6
Disable Real MIME Check: от Сергей Бирюков – 1.0
Duplicate Menu: от Jonathan Christopher – 0.2.2
WP OPcache: от nierdz – 3.0.2
Font Awesome: от Font Awesome – 4.0.0-rc13
Homepage Control: от WooThemes – 2.0.3
Mailchimp for WooCommerce: от Mailchimp – 2.3.1 – Не тестировалось с активной версией WooCommerce
Menu Icons: от ThemeIsle – 0.12.2
Perfect WooCommerce Brands: от Alberto de Vera Sevilla – 1.7.8
PW WooCommerce Bulk Edit: от Pimwick
LLC – 2.63

Simple Drop Cap: от Yudhistira Mauris – 1.2.8
UpdraftPlus - Backup/Restore: от UpdraftPlus.Com
DavidAnderson – 1.16.21

WooCommerce Bulk Editor: от realmag777 – 1.0.5.1 – Не тестировалось с активной версией WooCommerce
Checkout Field Editor for WooCommerce: от ThemeHigh – 1.4.0 – Не тестировалось с активной версией WooCommerce
Variation Swatches for WooCommerce: от Emran Ahmed – 1.0.73
Advanced AJAX Product Filters for WooCommerce: от BeRocket – 1.4.1.4 – Не тестировалось с активной версией WooCommerce
WOOF - WooCommerce Products Filter: от realmag777 – 1.2.3 – Не тестировалось с активной версией WooCommerce
PickPlugins Product Slider for WooCommerce: от PickPlugins – 1.12.23 – Не тестировалось с активной версией WooCommerce
WooCommerce: от Automattic – 3.9.1
Wordfence Security: от Wordfence – 7.4.5
Yoast SEO: от Команда Yoast – 12.9.1
WP Mail SMTP: от WPForms – 1.8.1
WP-Optimize - Clean, Compress, Cache: от David Anderson
Ruhani Rabin
Team Updraft – 3.0.15

WP Translitera: от Евгений Юрченко – p1.2.5
WPForms Lite: от WPForms – 1.5.8.2

### Inactive Plugins (13) ###

Akismet Anti-Spam: от Automattic – 4.1.3
Bazz CallBack Widget: от Viktor Ievlev – 3.18
Cache Enabler: от KeyCDN – 1.3.4
Easy WP SMTP: от wpecommerce
alexanderfoxc – 1.3.9.2

Facebook for WooCommerce: от Facebook – 1.9.15 – Не тестировалось с активной версией WooCommerce
Hello Dolly: от Matt Mullenweg – 1.7.2
LiteSpeed Cache: от LiteSpeed Technologies – 2.9.9.2
Product CSV Import Export (BASIC): от WebToffee – 1.7.2 – Не тестировалось с активной версией WooCommerce
SSL Insecure Content Fixer: от WebAware – 2.7.2
WooCommerce Direct Checkout: от QuadLayers – 2.3.2 – Не тестировалось с активной версией WooCommerce
WP All Import: от Soflyy – 3.5.2
WP All Import - WooCommerce Add-On: от Soflyy – 1.4.3 – Не тестировалось с активной версией WooCommerce
YITH WooCommerce Ajax Product Filter: от YITH – 3.8.4 – Не тестировалось с активной версией WooCommerce

### Settings ###

API Enabled: –
Force SSL: –
Currency: RUB (₽)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Ссылка магазина: #5 - /shop/
Корзина: #6 - /cart/
Оформление заказа: #7 - /checkout/
Мой аккаунт: #8 - /my-account/
Правила и условия: ❌ Страница не задана

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – Если вы хотите оформить WooCommerce родительской темой
которую создал кто-то другой
мы рекомендуем воспользоваться дочерней темой. См. "Как создать дочернюю тему"

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Выполнено: 3
Oldest: 2019-08-15 10:13:50 +0000
Newest: 2019-08-15 10:13:50 +0000

Ожидает: 3
Oldest: 2020-01-30 11:37:59 +0000
Newest: 2020-01-30 11:38:02 +0000

Отменено: 0
Oldest: –
Newest: –

В процессе: 0
Oldest: –
Newest: –

Неудачно: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by pgamaster** [comment]
![woobug1](https://user-images.githubusercontent.com/15028396/73451430-43bbca00-4370-11ea-95a7-8d03e8e0359e.jpg)

**Comment by juliaamosova** [comment]
Hi @pgamaster,

Thank you for submitting the issue. DB update is a part of the Action Scheduler functionality which relies on WP Cron which is how WordPress handles scheduling time-based tasks. So unless WP Cron runs, those tasks would be pending.

Similar to what had been suggested in the forum threads you linked to, you can run the pending jobs manually (on mouseover, a `Run` link appears on each line if you navigate to `WooCommerce / Status / Scheduled Actions`). 

Can you please try that and let us know how it goes.

**Comment by pgamaster** [comment]
there's no RUN link... unfortunately

**Comment by juliaamosova** [comment]
@pgamaster interesting. What about selecting a task `Run` and applying it to the selected jobs as shown below:

![DB_run](https://user-images.githubusercontent.com/19143190/73457695-f9384e80-436b-11ea-9c69-22737f27c114.jpg)

**Comment by pgamaster** [comment]
no run action...

![woobug3](https://user-images.githubusercontent.com/15028396/73461395-bdf54a00-4382-11ea-9697-52fbc1af32fa.jpg)

**Comment by peterfabian** [comment]
cc @rrennick maybe you saw when this would happen?

**Comment by rrennick** [comment]
The `Run` is an action link under the hook name. There isn't a bulk `Run`.

**Comment by pgamaster** [comment]
It's not there, please look into my screen shots.

**Comment by rrennick** [comment]
> It's not there, please look into my screen shots.

The screenshot doesn't show the HTML where the action link would be. Only `Pending` actions have action links

<img width="306" alt="Screen Shot 2020-01-30 at 1 24 08 PM" src="https://user-images.githubusercontent.com/343847/73473882-df930900-4363-11ea-981b-4fb77c37b363.png">

**Comment by pgamaster** [comment]
it shows actually, I updated my post https://jsfiddle.net/6oa4hemk/

**Comment by pgamaster** [comment]
Another screen shot

![woobug4](https://user-images.githubusercontent.com/15028396/73474336-03bc0d80-4397-11ea-8977-16aa2ba81ba2.jpg)

**Comment by pgamaster** [comment]
Firefox
![woobug5](https://user-images.githubusercontent.com/15028396/73474663-80e78280-4397-11ea-8446-2f2301234a64.jpg)

**Comment by pgamaster** [comment]
I switched to an English version, it works. The issue appears on Russian version.

![woobug6](https://user-images.githubusercontent.com/15028396/73474862-d7ed5780-4397-11ea-9a1c-eb676845f1c9.jpg)

**Comment by rrennick** [comment]
@pgamaster Glad to hear that. You'll be able to run the update that way :)

> I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.

We'll need confirmation that it happens with no other plugins active & a default theme before investigating further.

**Comment by pgamaster** [comment]
I can't turn off all plugins since the store is 24/7 online and dockerized :( 
As you can see the issue is related to Russian admin theme. You may look through the code...

**Comment by rrennick** [comment]
> You may look through the code...

Action Scheduler hasn't been updated in WooCommerce since 3.6.X but it's possible that it's an issue in the translation files. However, the translation files are maintained by the folks at https://translate.wordpress.org.

> Also we don't have any testing environment.

If you were able to set up a test install, I could provide instructions on creating pending actions.

**Comment by jirsbek** [comment]
I had the same issue as @pgamaster having WordPress admin in non-english translation. Switching to English works and I can see the _Run_ command now.

**Comment by juanmapd** [comment]
Same issue on Spanish

**Comment by dmeijide** [comment]
Same issue here, Spanish language. I had 5573 Scheduled Actions since I've installed WooCommerce last month. All the actions created not completed and no Run button. I found this post and now I've changed the language and I am clicking all the actions one by one .... This is insane.

**Comment by debora813** [comment]
Same issue. Could you help me? 


> Same issue here, Spanish language. I had 5573 Scheduled Actions since I've installed WooCommerce last month. All the actions created not completed and no Run button. I've changed the language to English and the Run button appeared. Can this be solved by disabling wp-cron and programing your own one?

**Comment by dmeijide** [comment]
> Same issue. Could you help me?
> 
> > Same issue here, Spanish language. I had 5573 Scheduled Actions since I've installed WooCommerce last month. All the actions created not completed and no Run button. I've changed the language to English and the Run button appeared. Can this be solved by disabling wp-cron and programing your own one?

Hi, @debora813 The issue I had was with wp-cron. You can check your cron status to see if it's working properly with this plugin:
https://es.wordpress.org/plugins/wp-cron-status-checker/

We solve this issue disabling wp-cron and creating an external one to update the database, this plugin can help with that:
https://es.wordpress.org/plugins/advanced-cron-manager/

Hope that helps.

**Comment by peterfabian** [comment]
Thanks for sharing your solutions, @dmeijide . 

As this topic is rather old and it started to report problems with update to WC 3.9, it seems like there are multiple problems being mixed in one issue thread. 

The issue caused by inability to run Action Scheduler actions manually when using non-English locales was a bug that is now solved. Those actions can be run via Tools > Scheduled Actions.

If you are facing other Action Scheduler problems, please try to update your WooCommerce installation to the latest version and please read through this document to get a better overviewo of how Action Scheduler works: https://docs.woocommerce.com/document/subscriptions/whats-new-in-subscriptions-3-0/

Also, as mentioned here, it's quite useful to install a plugin that lets you manage cron. 

If you encounter a new problem that you can reproduce, please open a new issue. Thanks!

**Comment by 08soniya** [comment]
I'm also facing the same issue scheduler is not working . there are many pending schedule action.
