### ISSUE TITLE
Tax class Zero Rate is not only for zero taxes

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce#25542]
I was wondering why there in WC settings under tax is a class called Zero Rate. I came to this because we tried to find a better translation for this class beside reduced and standard classes.

Well, we need all three of them and their logic seems to be OK as Standard is for us 19% EU-wide, reduced is 7% EU-wide.

But if I take a look at Zero Rate class, I am able to submit and save beside countries a value of tax other than 0%. If this class is only for zero rates, why am I able to save other than zero into it?

Wouldn't it be better to name this class to other than Zero Rate?

**Comment by claudiosanches** [comment]
WooCommerce default tax classes are just an example, you don't need to use any those classes.
Also the settings work the same for any tax class, that's why you are able to input any value.
