### ISSUE TITLE
Bootstrap .col-Integration Idea

### ISSUE THREAD

**Issue by sascharudolph** [woocommerce/woocommerce#25557]
Hey guys,

this is a feature, related to an old issue from 2017 https://github.com/woocommerce/woocommerce/issues/15793

We still suffering from the fact, that bootstrap is colliding with woocommerce' css.

To prevent old or further themes from being changed or simply destroyed by changing classes, what about an option (select-field) in the backend, where you can change the classes by yourself or choose from variation like "default: col-*" .... "woocommerce: wcol-*" etc.?

That should prevent every Theme from not working properly and give the user more opportunities to style their content / cart process.

Let me know what you are thinking about it :)

Cheers
Sascha

**Comment by ObliviousHarmony** [comment]
Hi Sascha,

Thank you for taking the time to share this idea, we really appreciate your help. 

Unfortunately, changing the classes used by elements is more a job for custom templates. You can [read more about overriding templates in our documentation](https://docs.woocommerce.com/document/template-structure/). 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project.
