### ISSUE TITLE
Remove Legacy API setting page and related code

### ISSUE THREAD

**Issue by dougaitken** [woocommerce/woocommerce#25559]
**Describe the bug**

The Legacy API was deprecated in WooCommerce 2.6, which was released over 3.5 years old. It should now be removed as it is no longer supported.

**Expected behavior**

Once support for a feature has been removed and is unsupported in WooCommerce, this feature should be completely removed in the `x+3` release - https://docs.woocommerce.com/document/frequently-asked-questions/#wcvers

**Comment by claudiosanches** [comment]
It's not longer supported, and also we shouldn't release any enhancement or bug fixes.
Still we don't plan to remove any code on core too soon, so we avoid backwards compatibility with 3rd party plugins, some plugins may include REST API classes directly.

Anyway, no one should use, it could be removed into any up come Major release when we feel comfortable of removing legacy code, but not something urgent or something that we plan to do soon.

**Comment by dougaitken** [comment]
> so we avoid backwards compatibility with 3rd party plugins, some plugins may include REST API classes directly.

But this is deprecated code. And it was one major release. Backwards compatibility it
