### ISSUE TITLE
WC_Product_Variable::sync() does not run when a variation is removed

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#25552]
**Describe the bug**
I have some code that runs on the `woocommerce_variable_product_sync_data`. It checks if any variations have a particular meta field (specifically if any of the variations are Name Your Price-enabled) and sets a meta flag on the parent. I just noticed that if you remove the Name Your Price variation, the meta flag on the parent does not go away. 

This appears to be because `sync()` and thus `woocommerce_variable_product_sync_data` are not fired when a variation is removed. 

Not sure if this is a bug or if I should be doing my `sync` process on some other hook... but from the naming this seems like the right place. 

**To Reproduce**
1. Add the following snippet:
```

function kia_test_woocommerce_variable_product_sync_data( $product ) {
	error_log('syncing');
}
add_action( 'woocommerce_variable_product_sync_data', 'kia_test_woocommerce_variable_product_sync_data' );
```

2. create a new variable product and add some variations. You should see the error log spit out `syncing`.

3. Delete a single variation by clicking on the "Remove" link. Nothing new should have been added to the error log.

**Expected behavior**
`sync` should fire when a variation is removed.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by ObliviousHarmony** [comment]
Hi helgatheviking,

Thank you for taking the time reporting this bug, we really appreciate your help. I can reproduce it on my end. 

- Added a hook to the sync action.
- Deleted a variation, it is not triggered.

We’re going to solve this bug as soon as possible. Stay tuned for updates.

**Comment by helgatheviking** [comment]
@ObliviousHarmony is there any chance this could get on the radar for 4.2? (or sooner since it's a bug fix and not a feature)

**Comment by MaciejKrawczyk** [comment]
Not sure if it's related, but when I remove a variation from the product, "woocommerce_update_product" action does not fire (it works for when a variation is added and updated).
