### ISSUE TITLE
Products still show in search results even with Catalog Visibility set to Hidden or Shop Only

### ISSUE THREAD

**Issue by jshrek** [woocommerce/woocommerce#25563]
**Describe the bug**
Product still shows up in search results even when catalog visibility is to to "shop only" or "hidden".

**To Reproduce**
Create a Simple Product that is Virual and is also Downloadable called My Dogs.
Set the catalog visibility to hidden.
Publish the product.
Search your site with example.com/?s=dogs
The product will still show up on search results page (but is successfully hidden from shop page).
NOTE: Setting catalog visibility to "search results only" will succesfully hide it from the Shop as well.

**Expected behavior**
When catalog visibility is set to "shop only" or "hidden" the product should NOT show up in any search results.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WordPress v5.3.2 and WooCommerce v3.9.1

**Comment by mstudioIL** [comment]
I have it also

**Comment by conschneider** [comment]
I can reproduce on a fresh local install with Twenty Twenty and Storefront: 

Screencast: http://somup.com/cYeOF81lUv

**Comment by jshrek** [comment]
I have also reported this issue on the WooCommerce support forum on wordpress.org ... feel free to post a comment there as well!
https://wordpress.org/support/topic/products-still-show-in-search-results-even-with-catalog-visibility-set-to-hidden/

**Comment by claudiosanches** [comment]
>  Search your site with example.com/?s=dogs

This is the default search on all WordPress, for your shop you suppose to include `&post_type=product`, like `example.com/?s=dogs&post_type=product` will exclude based on that setting.
