### ISSUE TITLE
Second order is created when coupon is added after starting a payment gateway

### ISSUE THREAD

**Issue by becdetat** [woocommerce/woocommerce#25578]
**Describe the bug**
A second order is created when you start paying via PayPal, then back out, then add a coupon, then start paying via PayPal again.

**To Reproduce**
1. Have a coupon code ready
2. Put an item in the cart
3. Checkout
4. Select pay with PayPal <-- _This creates an order that is pending payment for the full amount_
5. Without paying, back out to the checkout
6. Apply the coupon code
7. Select pay with PayPal <-- _This creates an order that is pending payment for the discounted amount_

**Expected behavior**
This appears to be expected behaviour, as the first order is waiting for the first PayPal payment to complete which it never does, however it is confusing for the site owners because an orphan order is created. The site owner is expecting the coupon to be added to the first order and go through to PayPal, without the second order being created.

Note that this only happens when the coupon code is added. If no coupon code is added the second order is not created.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

WordPress address (URL): https://relieved-quail.jurassic.ninja
Site address (URL): https://relieved-quail.jurassic.ninja
WC Version: 3.9.1
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Unix) OpenSSL/1.0.2g
PHP Version: 7.3.14
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.29-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.1
WC Database Prefix: wp_c49da98aa5_
Total Database Size: 7.38MB
Database Data Size: 4.81MB
Database Index Size: 2.57MB
wp_c49da98aa5_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_c49da98aa5_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_c49da98aa5_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_c49da98aa5_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_c49da98aa5_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_c49da98aa5_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_c49da98aa5_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_c49da98aa5_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_c49da98aa5_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_c49da98aa5_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_c49da98aa5_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_c49da98aa5_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_c49da98aa5_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_c49da98aa5_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpstg0_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_options: Data: 1.52MB + Index: 0.03MB + Engine InnoDB
wpstg0_postmeta: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wpstg0_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wpstg0_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg0_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpstg0_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpstg0_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg0_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpstg0_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpstg0_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpstg0_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpstg0_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_c49da98aa5_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_c49da98aa5_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_c49da98aa5_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_c49da98aa5_options: Data: 1.48MB + Index: 0.06MB + Engine InnoDB
wp_c49da98aa5_postmeta: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
wp_c49da98aa5_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_c49da98aa5_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_c49da98aa5_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_c49da98aa5_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_c49da98aa5_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_c49da98aa5_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_c49da98aa5_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_c49da98aa5_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_c49da98aa5_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_c49da98aa5_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_c49da98aa5_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_c49da98aa5_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_c49da98aa5_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_c49da98aa5_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_c49da98aa5_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_c49da98aa5_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_c49da98aa5_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_c49da98aa5_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_c49da98aa5_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
event_ticket: 1
page: 7
post: 2
product: 20
product_variation: 9
scheduled-action: 38
shop_coupon: 2
shop_order: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (9) ###

Companion Plugin: by Osk – 1.11
Jetpack by WordPress.com: by Automattic – 8.1.1
WooCommerce Admin: by WooCommerce – 0.24.0 – Not tested with the active version of WooCommerce
WooCommerce Box Office: by WooCommerce – 1.1.16
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.18 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.3.1 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.22.3
WooCommerce: by Automattic – 3.9.1
WP Staging: by WP-Staging – 2.6.8

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 4.1.3
Hello Dolly: by Matt Mullenweg – 1.7.2
Tiered Price Table for WooCommerce: by Kolya Lukin – 3.0.2 – Not tested with the active version of WooCommerce

### Must Use Plugins (1) ###

WP Staging Optimizer: by René Hermenau – 1.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 36
Oldest: 2020-02-04 00:37:54 +0000
Newest: 2020-02-04 22:53:17 +0000

Pending: 2
Oldest: 2020-02-04 23:53:17 +0000
Newest: 2020-02-04 23:53:17 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –
</details>

**Comment by SirRahikkala** [comment]
I don't know if its related but one of my stores is having similar issues with sessions and coupons. The orders which are not finalised, are stuck in woocommerce_sessions table and when the user comes back, they are not linked to that user, instead it say that coupon is used (in reality it's not because the old session is still open) also the cron job clearing the sessions does not clear them but the Woocommerce status/tools clearing function does work.

There seems to be something funky going on with session handling.

**Comment by claudiosanches** [comment]
This is the expected behavior, also to avoid any conflict with PayPal API, since when you go to PayPal will generate a hash and ID for the payment, including new items will require a new order number too.
Also since the order is "pending payment" it will get canceled according with the on-hold stock settings.
