### ISSUE TITLE
Improve Catalog page Pagination when showing Categories + Products

### ISSUE THREAD

**Issue by johndcoy** [woocommerce/woocommerce#25585]
**Is your feature request related to a problem? Please describe.**
**Rows per page** doesn't apply to both categories and products. It's broken:

![Screenshot](https://d.pr/i/xieFiT+)
Screenshot link: https://d.pr/i/xieFiT

**Describe the solution you'd like**
I’d assume that **Rows per page** would set the rows for both. If set to 2, show two rows of categories and two rows of products on each page. Then only show two rows in the final pages of whichever has remaining items.

**Describe alternatives you've considered**
As @ObliviousHarmony suggested:

> As it is, I'd be inclined to make a separate "Categories Per Page" option, rename the "Product Per Row" option for clarity, and do what you suggested. Perhaps it could even take up the extra space if the products don't fill the page.

**Additional context**

Slack - XXX

**Comment by garymurray** [comment]
@johndcoy I took a quick look at this, and it seems to actually be behaving as expected - i.e. in the last setting it looks like this:

<img width="293" alt="Screenshot 2020-02-06 at 11 05 57" src="https://user-images.githubusercontent.com/10805911/73931762-c1338d00-48d0-11ea-97b4-98e1b31c8c7d.png">

Were it is basically saying:

> Rows per page
> How many rows of products should be shown per page?

So based on the way the setting is described - it controls the the number of rows of **products** shown on the page, not categories **and** products. 

From your issue, if I understand correctly, you feel that that setting **should** control both the number of rows of categories and products shown on the page - is that correct? i.e. if it is set to `2` it should show 2 rows of categories and 2 rows of products?

I think a different way to handle this would be to introduce a second set of 'settings/controls' specific to how **categories** are shown if `Show categories and products` is selected in the initial dropdown.

This would then allow someone to create a page that had something more like this:

- 2 rows of categories with 3 categories per row and
- 4 rows of products with 4 products per row

Does that make sense? If so, I can mockup the possible changes there.

cc @ObliviousHarmony

**Comment by juliaamosova** [comment]
> 
> I think a different way to handle this would be to introduce a second set of 'settings/controls' specific to how categories are shown if Show categories and products is selected in the initial dropdown.
> 
> This would then allow someone to create a page that had something more like this:
> 
> - 2 rows of categories with 3 categories per row and
> - 4 rows of products with 4 products per row
> Does that make sense? If so, I can mockup the possible changes there.

I really like this solution as it seems like a very clear and straightforward way of addressing the issue. cc @peterfabian @claudiosanches for feedback as well.

**Comment by garymurray** [comment]
Here is a mockup of what I proposed:

Products only selected (default state I believe):

![products](https://user-images.githubusercontent.com/10805911/74738311-87f30980-524e-11ea-8408-ae58cc59fcdb.jpg)

Categories only selected:

![categories](https://user-images.githubusercontent.com/10805911/74738335-96412580-524e-11ea-9efd-2410812a4b74.jpg)

Categories and products selected:

![productsandcategories](https://user-images.githubusercontent.com/10805911/74738359-a22ce780-524e-11ea-9c12-382ad155af18.jpg)

Note - I have moved the **Default product sorting** setting above the **Category page display** setting as I feel it makes more sense to come straight after the initial setting.

I also introduced some horizontal rules to break each setting into each own thing to make the settings easier to scan and see what settings effect which main item.

**Comment by ObliviousHarmony** [comment]
Thanks for this @garymurray!

I really like the decision to hide the settings that aren't relevant to the current display option. I think we can make those boxes take up the full width as well. The horizontal rules look great too!

How do you think this should be rendered to the user on the shop page? Right now all of the categories are dumped into the listing as products. Should we just keep that as-is and change the categories that are displayed? Does that look weird?

**Comment by garymurray** [comment]
> How do you think this should be rendered to the user on the shop page? Right now all of the categories are dumped into the listing as products. Should we just keep that as-is and change the categories that are displayed? Does that look weird?

@ObliviousHarmony can you show me what you mean there - then I can give it some thought - thanks.

**Comment by ObliviousHarmony** [comment]
@garymurray Here is a picture of my shop page with categories and products both set to display:

<img width="696" alt="Screen Shot 2020-02-26 at 14 43 30" src="https://user-images.githubusercontent.com/6451942/75395107-86f15600-58a6-11ea-8d06-7dec8753d4be.png">

I feel like with these two settings, this method of displaying the categories and products together might be a really strange user experience.

**Comment by garymurray** [comment]
@LevinMedia can you pick this up please - it is not a high priority given we are moving to merchants using blocks to create these pages in the future.

**Comment by LevinMedia** [comment]
@ObliviousHarmony I'm with you on this one, in addition to the proposal from @garymurray I think we should split the categories and products into two distinct sections... because I agree, having them all lumped into the same bucket is not a good look. 

<img width="1976" alt="Screen Shot 2020-03-11 at 9 13 56 PM" src="https://user-images.githubusercontent.com/4500952/76486772-9e1f6000-63dd-11ea-993b-2dc2f7bcbe2c.png">

**Comment by LevinMedia** [comment]
On second thought, That's not going to work. Using the controls that @gary has proposed and splitting the categories and products into two sections would present new issues. 

Say the categories per row were set to four, and the rows of categories were set to two. That gives you eight categories to display on the page. This is fine if the store has eight categories or less... but what if that store has 100 categories? After we display the eight categories, we could link to a paginated page of all the remaining categories, but that doesn't exist. Even if it did exist, we'd have to create additional configurations to control how the categories are ordered. 

The issue at hand here isn't great, however, given the amount of effort required to implement viable fix, along the move towards blocks, I think it's best if we close this out and focus our attention elsewhere.
