### ISSUE TITLE
Show/Hide password in My account

### ISSUE THREAD

**Issue by snuffybg** [woocommerce/woocommerce#25580]
**Describe the bug**
Hello,
Today when i work on My account templates notice that in form-edit-account template show/hide password doesnt work. The show part works but if you try to hide it wont swap from text field to password field. When i look in to woocommerce.js notice that the script is looking for attr name='password' , but in form-edit-account the name attributes for each field (current , new , repeat new) are different password_current , password_1 , password_2 . Any fix on this ? 

**Note**
I am not allowed to share some information in details. I did test in clean install without any themes or plugins except woocommerce and the issue is there.

**To Reproduce**
1. Login in frontend of woocommerce
2. Go to Dashboard
3. Go to Edit Account
4. Type in any password field something and toggle show/hide.

**Expected behavior**
Showing and hiding password content.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WC Version: 3.9.1
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.13
PHP Post Max Size: 20 MB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.67.0
OpenSSL/1.0.2t

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.31-MariaDB-log
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.1

### Post Type Counts ###

page: 30
post: 5
product: 4
shop_coupon: 1
shop_order: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (12) ###

WooCommerce
WooCommerce: by Automattic – 3.9.1
WP Crontrol: by John Blackbourn & crontributors – 1.7.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #45208 - /subscription/
Cart: #45215 - /cart/
Checkout: #45216 - /checkout/
My account: #45217 - /my-account/
Terms and conditions: #53189 - /terms-of-use/

### Theme ###

WooCommerce Support: ✔

### Templates ###

Overrides: hidden/woocommerce/checkout/form-billing.php
hidden/woocommerce/checkout/form-checkout.php
hidden/woocommerce/checkout/payment.php
hidden/woocommerce/checkout/review-order.php
hidden/woocommerce/myaccount/dashboard.php
hidden/woocommerce/myaccount/form-edit-account.php
hidden/woocommerce/myaccount/form-login.php
hidden/woocommerce/myaccount/view-order.php
hidden/woocommerce/order/order-again.php
hidden/woocommerce/order/order-details-customer.php
hidden/woocommerce/order/order-details-item.php
hidden/woocommerce/order/order-details.php

### Action Scheduler ###

Complete: 14

</details>

**Comment by juliaamosova** [comment]
Hi @snuffybg,

Thank you for reporting the issue. This issue had been reported here as well https://github.com/woocommerce/woocommerce/issues/25624. 

I know that yours came first but since I already replied on https://github.com/woocommerce/woocommerce/issues/25624, I am closing your issue in favor of https://github.com/woocommerce/woocommerce/issues/25624. Please continue sharing your feedback there if needed.
