### ISSUE TITLE
Cart Fragments

### ISSUE THREAD

**Issue by stormit** [woocommerce/woocommerce#25599]
Hi all,

I recommend that there should be a js trigger which calls the **refresh_cart_fragment** js function. So we can refresh cart in the theme or other plugins.

`function refresh_cart_fragment() {
		$.ajax( $fragment_refresh );
	}`

Thanks!

**Comment by claudiosanches** [comment]
If you need to trigger it you can use `wc_fragment_refresh`.

This should trigger `refresh_cart_fragment()` function:
```js
jQuery( document.body ).trigger( 'wc_fragment_refresh' );
```

**Comment by stormit** [comment]
Hi @claudiosanches,

I know. But it only works if browser supports htm5. This trigger should work for all browsers. It will be better.

Thank you!
