### ISSUE TITLE
ship to different address

### ISSUE THREAD

**Issue by V35CH** [woocommerce/woocommerce#25604]
**Describe the bug**
there is a bug in the checkout.js in the method: init_ship_to_different_address
It should test if a compared shipping address field is not empty.

`return $( this ).val() !== $billing.find( '#' + id ).val();`

should be like this:
```
var shipping_field_val = $(this).val();
return '' != shipping_field_val && shipping_field_val !== $billing.find('#' + id).val();
```

Otherwise the method returns true if there is a billing address but no shipping address data.
This could happen if you have a logedin customer account with only a billing address but with no shipping address set.

I have disabled all Plugins and switched to the storefront theme to test this behavior.

**To Reproduce**
1. Create an user account with only a billing address
2. goto the checkout
3. the checkbox for the shipping address will be checked.

**Expected behavior**
The checkbox should only be checked if there is a shipping address

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**In my custom javascript file I use this fix:**
```
/**
 * Bug in WooCommerce Checkout
 */
jQuery( document ).ready(function ($) {
    // wc_checkout_params is required to continue, ensure the object exists
    if (typeof wc_checkout_params === 'undefined') {
        return false;
    }
    function init_ship_to_different_address() {
        
        var $checkbox = $('#ship-to-different-address input');
        
        if ($checkbox.prop('checked')) {
            var $billing = $('div.woocommerce-billing-fields');

            // Find shipping field values that diverge from billing.
            var $differentFields = $('div.shipping_address').find('input, select').filter(function () {
                $(this).attr('id').replace('shipping', 'billing');
                var id = $(this).attr('id').replace('shipping', 'billing');

                var shipping_field_val = $(this).val();
                return '' != shipping_field_val && shipping_field_val !== $billing.find('#' + id).val();
            });

            $checkbox.prop('checked', $differentFields.length > 0);
        }

        $('div.shipping_address').toggle($checkbox.prop('checked'));
    }
    init_ship_to_different_address();
});
```

**Comment by juliaamosova** [comment]
Hi @V35CH,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/25493. We also have a fix for it in https://github.com/woocommerce/woocommerce/pull/25521. The fix is currently planned to be released as part of WooCommerce 4.0. 

We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
