### ISSUE TITLE
Replace {site_address} by {site_url} ?

### ISSUE THREAD

**Issue by corsonr** [woocommerce/woocommerce#25603]
**Is your feature request related to a problem? Please describe.**

In many places, and mostly for emails, we provide the `{site_address}` placeholder, but wouldn't it be more relevant to name it `{site_url}`? To me, it would more relevant especially since in the settings we have two "address fields".

For instance:

https://github.com/woocommerce/woocommerce/blob/c1a7a08c01c23c1cb749ba2be17804128865114d/includes/emails/class-wc-email.php#L235

**Describe the solution you'd like**

My suggestion is to replace `{site_address}` by `{site_url}` wherever it's used so that it matches the WordPress core naming reference.

I'm happy to do a PR

**Comment by claudiosanches** [comment]
Makes sense call it `site_url`, I agree that could get confuse with "email address".
Please feel free to submit a Pull Request.
Thanks @corsonr
