### ISSUE TITLE
Totals calculation causes rounding problems due to wc_round_tax_total()

### ISSUE THREAD

**Issue by lamda** [woocommerce/woocommerce#25629]
In WC_Cart_Totals:: calculate_totals() the taxes are always rounded before adding them to the total with wc_round_tax_total():

```
$this->set_total( 'total', round( $this->get_total( 'items_total', true ) + $this->get_total( 'fees_total', true ) + $this->get_total( 'shipping_total', true ) + wc_round_tax_total( array_sum( $this->get_merged_taxes( true ) ), 0 ), 0 ) );
```

This causes a rounding problem of 1 Cent for me in a few cases when calculating the totals with a product, a custom fee and an applied percentage discount coupon when using tax-inclusive pricing. I can provide an example if needed.

I have activated "Round tax at subtotal level, instead of rounding per line". Is there a specific reason to round taxes before adding them to the total? If I remove the call to wc_round_tax_total at this position, the total comes up correctly.

I'm on WordPress 5.3.2 and WooCommerce 3.9.1

**Comment by juliaamosova** [comment]
Hi @lamda,

Thank you for submitting the issue. 

>This causes a rounding problem of 1 Cent for me in a few cases when calculating the totals with a product, a custom fee and an applied percentage discount coupon when using tax-inclusive pricing. I can provide an example if needed.

Would you please provide us with the exact details of your setup including the screenshot of your tax settings - it will help us analyze the issue further since there are so many tax settings combinations. Details of what you are getting as a result versus what you expect to get will be very helpful as well.

**Comment by lamda** [comment]
**Describe the bug**
A combination of a product, a discount and a custom fee leads to a rounding error of one cent in the total.

**To Reproduce**
Steps to reproduce the behavior:
1. set up a fresh WooCommerce and WordPress installation with Storefront
2. Add a product with a price of €71.50 including 10% VAT
3. Add a coupon with a 3% discount on the cart contents
4. Add a custom fee in functions php as follows - this fee should be €1.5 including 10% tax, so we have to divide it by 1.1
```
add_action('woocommerce_cart_calculate_fees', 'set_box_fee', 10);
function set_box_fee($cart) {
    $boxFee = 1.5/1.1; // 1.5€ fee, of which we only need the net part
    $cart->add_fee(__('Packaging', 'woocommerce'), $boxFee, true);
}
```
5. try to check out with the product and the coupon and notice a rounding difference

**Screenshots**
<img width="374" alt="Screenshot 2020-02-12 at 07 52 00" src="https://user-images.githubusercontent.com/1311431/74310081-99c73f00-4d6c-11ea-8673-c2d964793ea8.png">

**Expected behavior**
I would expect the total to be €70.86 based on the discount of €2.14.

**Possible cause
In WC_Cart_Totals:: calculate_totals() the taxes are always rounded before adding them to the total with wc_round_tax_total():

```
$this->set_total( 'total', round( $this->get_total( 'items_total', true ) + $this->get_total( 'fees_total', true ) + $this->get_total( 'shipping_total', true ) + wc_round_tax_total( array_sum( $this->get_merged_taxes( true ) ), 0 ), 0 ) );
```
Removing the call to `wc_round_tax_total()` in this line shows the correct total of €70.86.

Note that 3% of €71.5 comes up to exactly €2.145. Another solution could be to round this value up to €2.15€ and display that in checkout. Note however, that without the custom fee the totals show up correctly:
![image](https://user-images.githubusercontent.com/1311431/74310409-718c1000-4d6d-11ea-8752-eafee81d38b9.png)


**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://www.woocommerce.test
Site address (URL): https://www.woocommerce.test
WC Version: 3.9.1
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 4 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.39 (Unix) OpenSSL/1.0.2s PHP/7.2.19
PHP Version: 7.2.19
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.65.1
OpenSSL/1.0.2s

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.15-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.1
WC Database Prefix: wp_
Total Database Size: 3.06MB
Database Data Size: 2.08MB
Database Index Size: 0.98MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.50MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 6
post: 2
product: 2
scheduled-action: 1
shop_coupon: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.9.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.3
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /?page_id=6
Cart: #7 - /?page_id=7
Checkout: #8 - /?page_id=8
My account: #9 - /?page_id=9
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.3
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 0
Oldest: –
Newest: –

Pending: 1
Oldest: 2020-02-12 06:40:51 +0000
Newest: 2020-02-12 06:40:51 +0000

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by lamda** [comment]
Here's a screenshot of my tax settings:

<img width="712" alt="Screenshot 2020-02-12 at 08 03 53" src="https://user-images.githubusercontent.com/1311431/74310777-3b02c500-4d6e-11ea-9a35-05d19b0982b9.png">

**Comment by lamda** [comment]
Any news on this?
I could submit a pull request, but I am still a bit unclear as to why the taxes are rounded before being added to the total. Is there a specific reason for this? Am I perhaps adding the fee incorrectly?

**Comment by vedanshujain** [comment]
sorry for the delay, I am planning to take a look at this week @lamda .
