### ISSUE TITLE
Issue with woocommerce_single_product_image_thumbnail_html filter

### ISSUE THREAD

**Issue by sajjadalis** [woocommerce/woocommerce#25626]
**Describe the bug**
The filter `woocommerce_single_product_image_thumbnail_html` is not working. I'm trying to set alt tag for Woocommerce gallery images via  `woocommerce_single_product_image_thumbnail_html` filter. Here is my code inside TwentyTwenty functions.php file. 

```
function replaceAlt($content) {
    $dom = new DOMDocument();
	@$dom->loadHTML($content);
	$x = new DOMXPath($dom);

	foreach($x->query("//img") as $node)
	{   
		$node->setAttribute("alt","Alt Text");
	}

	$content = $dom->saveHtml();

	return $content;
}
add_filter('the_content', 'replaceAlt');
add_filter('woocommerce_gallery_image_html_attachment_image_params filter', 'replaceAlt');
```

`the_content` filter replace alt tag inside Woocommerce description. `woocommerce_single_product_image_thumbnail_html` filter was working fine sometime ago with similar code. Not sure when this issue started.

**To Reproduce**
1. Please add the code inside Default WordPress theme or any other theme functions.php file.
2. Check a product with featured image and images inside gallery
3. Add an image inside Product description for `the_content` filter.
4. Inspect images on front-end to see results.

**Expected behavior**
It should set missing alt tag and replace any existing alt tag with defined text.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
WooCommerce version: 3.9.1
WooCommerce REST API package:  1.0.7 D:\laragon\www\wordpressy\wp-content\plugins\woocommerce\packages\woocommerce-rest-api
Log directory writable: D:\laragon\www\wordpress/wp-content/uploads/wc-logs/
WordPress version: 5.3.2
WordPress multisite:  –
WordPress memory limit: 1 GB
WordPress debug mode:  –
WordPress cron: 
Language: en_US
External object cache: –
```
</details>

**Comment by claudiosanches** [comment]
I can't reproduce it, works just fine, but seems like your code is incorrect, see:

```php
add_filter('woocommerce_gallery_image_html_attachment_image_params filter', 'replaceAlt');
```

Seems like it suppose to be:

```php
add_filter('woocommerce_single_product_image_thumbnail_html', 'replaceAlt');
```
