### ISSUE TITLE
need urlencode() of $license_key in new maxmind geo integration

### ISSUE THREAD

**Issue by diablodale** [woocommerce/woocommerce#25637]
The new maxmind geo integration released in 3.9.0 does not urlencode the license_key argument on the download URL. This opens a vulnerability into possible abuse/hack/security issue.

### Setup

Woocommerce 3.9.0+

### Repro

Code review of new Maxmind integration code

https://github.com/woocommerce/woocommerce/blob/0436d8637f59726202bc4539ec4c4078e1a0e514/includes/integrations/maxmind-geolocation/class-wc-integration-maxmind-database-service.php#L87-L101

Notice line 91. It wp_clean() the option value, but it does not urlencode it.
As per Wordpress docs https://developer.wordpress.org/reference/functions/add_query_arg/

> Values are expected to be encoded appropriately with urlencode() or rawurlencode()... Important: The return value of add_query_arg() is not escaped by default. Output should be late-escaped with esc_url() or similar to help prevent vulnerability to cross-site scripting (XSS) attacks.

### Expected

At a minimum, the following. Perhaps more with `esc_url_raw()`

```php
'license_key' => urlencode(wc_clean( $license_key )),
```

### Isolating the problem
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #25682.
