### ISSUE TITLE
maxmind migration function doesn't generate the new db path as integration does itself

### ISSUE THREAD

**Issue by diablodale** [woocommerce/woocommerce#25638]
The migration code `wc_update_390_move_maxmind_database()` for the new MaxMind integration released in 3.9.0 doesn't fully generate the new path in the same way that the integration will. This could lead to an unintentional failure, unneeded download, duplicated db file, etc.

### Setup

Woocommerce 3.9.0+

### Repo

Code review of new Maxmind integration code

https://github.com/woocommerce/woocommerce/blob/0bd2730963258cd753bb680d8749b361c91cfbe8/includes/wc-update-functions.php#L2065-L2067

In the above code, a final step is missing. It is not applying the new filter `woocommerce_maxmind_geolocation_database_path` as is done in the actual integration code below

https://github.com/woocommerce/woocommerce/blob/0436d8637f59726202bc4539ec4c4078e1a0e514/includes/integrations/maxmind-geolocation/class-wc-integration-maxmind-database-service.php#L65-L78

If someone has add_filter() `woocommerce_maxmind_geolocation_database_path` then the new path used in the integration will not be correct. The goal is as written in Woo's code "Generate the new path in the same way that the integration will." and therefore I recommend it fully do that.

### Expected

Easy fix. Apply the filter, e.g. add this code as line 2066

```php
$new_path = apply_filters( 'woocommerce_maxmind_geolocation_database_path', $new_path );
```

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment]
Thank you for reporting this issue!

I'm closing the issue as it already has a PR, please continue the discussion over at #25681.
