### ISSUE TITLE
[4.0 beta1] Backorder settings ignored for manual orders

### ISSUE THREAD

**Issue by corsonr** [woocommerce/woocommerce#25635]
**Describe the bug**

**To Reproduce**
1. Create a new product from scratch
2. Enable stock at product level
3. Do **not** allow backorder
4. Create a manual order from the dashboard
5. Add the product and increase Qty
6. Recalculate and place order

**Screenshots**

![](https://d.pr/i/UZpTXO+)

![](https://d.pr/i/B4Qywx+)

![](https://d.pr/i/4FKrSw+)

![](https://d.pr/i/1g8MoN+)

**Expected behavior**

I think there should be a way to add more products to an order than the actual stock value if backorders aren't enabled, even from the dashboard.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by juliaamosova** [comment]
Hi @corsonr 

Thank you for reporting the issue. Note that this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/25518. I am closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed. Thanks a lot for testing 4.0 beta!
