### ISSUE TITLE
[4.0 beta1] Refund: incorrect rounding

### ISSUE THREAD

**Issue by corsonr** [woocommerce/woocommerce#25634]
**Describe the bug**

When refunding an order with tax, I get the numbers that should, IMO, have a better rounding:

**To Reproduce**
1. Add any tax rate
2. Place an order with multiple products in cart
3. Try to refund 1 product or so
4. You should see what I mean

**Screenshots**

![](https://d.pr/i/mcFP9L+)

**Expected behavior**

I guess it's should be only digits by default and use regular rounding settings

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by vedanshujain** [comment]
@corsonr this change was intentionally added to allow defining precision and respected `Rounding at subtotal setting` as part of https://github.com/woocommerce/woocommerce/pull/24208. I know that its not as pretty as before, but the alternative is you would see totals of those values not matching up with final amount when rounding at subtotal setting is enabled.

I am closing the issue now, but let me know if you have any comments and we can reopen.
