### ISSUE TITLE
Tax rounding issue when the option `Round tax at subtotal level, instead of rounding per line` is enabled

### ISSUE THREAD

**Issue by dumega** [woocommerce/woocommerce#25641]
**Describe the bug**
In some context, when the option `Round tax at subtotal level, instead of rounding per line` is enabled, there may be 1 cent price difference between cart tax total and order tax total.

**To Reproduce**
1. Go to `Tax options`, enable `Round tax at subtotal level, instead of rounding per line`
2. Go to `"Standard" tax rates`, add two rate line item:

![image](https://user-images.githubusercontent.com/3198527/74299800-be311480-4d88-11ea-9eb0-2b18424ca3cf.png)

3. Go to products list, use the product `Polo` as example, edit its price to `$22.99`, Tax status to `Taxable`, Tax class to `Standard`

![image](https://user-images.githubusercontent.com/3198527/74299929-24b63280-4d89-11ea-89aa-ffcf22e4f269.png)

4. Go to shop page and add this product Polo to the cart, and checkout with the address :

1518 Fair Drive
Knoxville, TN 37918, USA

5. In the checkout page, we can see that the cart tax total is $3.05 ( WC()->cart->get_total_tax() )

![image](https://user-images.githubusercontent.com/3198527/74300451-b7a39c80-4d8a-11ea-9419-d61117108a40.png)

6. After complete the payment, in the order details page, the order tax total become $3.06 ( $order->get_total_tax() )

![image](https://user-images.githubusercontent.com/3198527/74300714-9f804d00-4d8b-11ea-8a32-a9a99ef2b6eb.png)

**Expected behavior**
The cart tax total should equal to the order tax total

**WordPress Environment**
<details>
```

WooCommerce version: 3.9.1
WordPress version: 5.3.2


```
</details>

**Comment by vedanshujain** [comment]
Fixed via #25800

**Comment by idreesi** [comment]
We are facing this issue again with:
WooCommerce Version 10.9.1
WordPress Version 6.9.4
