### ISSUE TITLE
[4.0 beta1]: Issue when trying to delete a refund

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce#25648]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
1. Make an order.
2. Click on refund and do a partial refund.
3. Try and delete the refund.
4. You will see a confusing line item and the deleted refund is still there.

**Screenshots**
![](https://d.pr/i/Engp9u+)

**Expected behavior**
I expect to see the refund line item removed as if refund was never there. I also expect to see the total amount to be what it was before the refund and that no refund line item shown.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by tammullen** [comment]
Hi @roykho,

Thank you for testing and submitting the issue!
I tried reproducing the issue on some orders and wasn't able to
![Screenshot_2020-02-17_at_13_47_15](https://user-images.githubusercontent.com/24649833/74659521-69c4d500-518c-11ea-8765-e53acebd731f.png)
![Screenshot_2020-02-17_at_13_47_27](https://user-images.githubusercontent.com/24649833/74659528-6d585c00-518c-11ea-8e65-9e902af476af.png)
When I try deleting refunds or partial refunds they do get removed and the total is updated correctly. 

I will continue to try to reproduce it but if you know of any other details that could help to re-produce it and help us to evaluate it further that would be great.

**Comment by roykho** [comment]
So I am able to repeat this issue consistently on my Pressable site. However if I tested this locally on my dev site, it works fine. I hope that helps a bit in narrowing down the issue.

**Comment by tammullen** [comment]
Thanks @roykho 

Thank you for the extra information. I can now reproduce it on my end on Pressable & Atomic.

We’re going to solve this bug as soon as possible. Stay tuned for updates

**Comment by tammullen** [comment]
Closing this issue in favor of the other similar submitted issue https://github.com/woocommerce/woocommerce/issues/25650. Please continue sharing your feedback there if needed.
