### ISSUE TITLE
Image Change with Drop-down selection-PLEASE ASSIST-No One is on Any Other Forum

### ISSUE THREAD

**Issue by StephMB777** [woocommerce/woocommerce#25640]
I’ve attached a photo. This will be the best way to describe what I need to do, but I’ll try explaining with words. I’m not proficient in code language, coding, WP, GF, etc, so please excuse me if I’m confusing and speak to me like I'm 2. No offense will be taken.

I am building an e-commerce website for my company using WordPress. I am a dealer for an LED company. I have permission to use every image, video, info from their site. I don’t want to copy their site, but I do like how their images change once you select an option in their dropdown list. Can you please tell me how to do this with GF without having to buy additional plugins besides product add-ons? I’ve watched a video showing this option using only the product add-ons, but he doesn’t explain how the images change; https://www.youtube.com/watch?v=cbcFjaIaGyQ&t=184s

Hopefully that wasn’t too confusing. Thank you in advance for your help!!!
![Image Selection Change1](https://user-images.githubusercontent.com/60944997/74280148-cda95280-4ce1-11ea-8482-d3043910921a.jpeg)

**Comment by peterfabian** [comment]
Hi @StephMB777 

This request is better asked in our [support channels](https://woocommerce.com/contact-us/), but as you're already here, let's try to find out what we can do. 

The standard WooCommerce using variable products switches images based on chosen variation, but images in dropdowns are not a well-supported feature among browsers, so you might experience some problems there and would need to either build a custom Javascript dropdown or find some other workaround.

If you have a more complex product and need to use the Gravity Forms to configure it, you would probably need to do some custom coding to achieve the desired effect. I found a tutorial that does partially what you need: https://jetsloth.com/gravity-forms/how-to-build-a-product-configurator-with-gravity-forms-and-image-choices/
But even that does not get you exactly what you need as it doesn't work with WooCommerce, based on the comments below the tutorial. 

[Looking at the docs](https://docs.woocommerce.com/document/woocommerce-gravity-forms-product-addons/#section-40), it seems like changing product pictures is not supported by default just with GF and WooCommerce Gravity Forms Product Add-Ons.

**Comment by StephMB777** [comment]
Thank you @peterfabian. I will move on seeing I don't have the experience to tackle something like this. I appreciate your time and knowledge.
