### ISSUE TITLE
Removing line item in order details not updating automatically

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce#25650]
**Describe the bug**
Deleting shipping does not appear to delete until next reload.

**To Reproduce**
1. Make an order with shipping
2. Go to order and make sure it is in pending status
3. Click on the `x` ( delete ) icon for the shipping
4. See that after the AJAX response, the shipping line item still exists and totals are not recalculated. Until reload.

**Screenshots**
![](https://d.pr/i/X3cwMQ+)

**Expected behavior**
I expect the shipping order line item to disappear and that the total line items are calculated correctly.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment]
Hi @roykho,

Thank you for testing and submitting the issue! 
I tried reproducing the issue with pending orders.
I used both an order made from the store and a manually created order and in both instances the shipping item was removed and the order totals updated correctly.
![Screenshot_2020-02-17_at_10_29_41](https://user-images.githubusercontent.com/24649833/74647179-201bc080-5173-11ea-8124-553423764c06.png)
![Screenshot_2020-02-17_at_10_29_51](https://user-images.githubusercontent.com/24649833/74647185-2316b100-5173-11ea-9728-276be42cbb98.png)

I will continue to try to reproduce it but if you know of any other details that could help to re-produce it and help us to evaluate it further that would be great.

**Comment by roykho** [comment]
So I am able to repeat this issue consistently on my Pressable site. However if I tested this locally on my dev site, it works fine. I hope that helps a bit in narrowing down the issue.

**Comment by tammullen** [comment]
Thanks @roykho 

Thank you for the extra information. I can now reproduce it on my end on Pressable & Atomic.

We’re going to solve this bug as soon as possible. Stay tuned for updates

**Comment by tammullen** [comment]
Updating the title to remove 4.0 beta as this also seems to be happening in 3.92 and also to reflect this seems to be happening for all line items including refunds (as raised here https://github.com/woocommerce/woocommerce/issues/25648) and product line items in the order.

<img width="1628" alt="Screenshot_2020-02-20_at_16_57_45" src="https://user-images.githubusercontent.com/24649833/74966095-5628a100-540e-11ea-91dc-ec1a3e2adf4f.png">
<img width="1629" alt="Screenshot_2020-02-20_at_16_58_05" src="https://user-images.githubusercontent.com/24649833/74966105-5b85eb80-540e-11ea-881c-d1b80c86103d.png">
<img width="1630" alt="Screenshot_2020-02-20_at_16_58_21" src="https://user-images.githubusercontent.com/24649833/74966114-5f197280-540e-11ea-836a-3100f59971ac.png">

Removing a product line item creates the correct order note but doesn't update the order details until clicking recalculate or update order.
