### ISSUE TITLE
 [4.0 beta1] Issue installing WC Services via WC Admin dashboard

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce#25675]
Jetpack is installed but not WC Services. When going to WooCommerce  > Dashboard, I see the following error: 

```
Notice: Automattic\Jetpack\Constants was called incorrectly. Not all plugins have loaded yet but we requested the class Automattic\Jetpack\Constants Please see Debugging in WordPress for more information. (This message was added in version 1.1.3.0.) in /var/www/wp-includes/functions.php on line 4986
```

![](https://d.pr/i/OZxKTK+)
Link to screenshot: https://d.pr/i/OZxKTK

![](https://d.pr/i/8IgO1h+)
Link to screenshot: https://d.pr/i/8IgO1h

(Testing with GoDaddy test site)
 

Noting that WC Admin was at .23.3 and Jetpack was at 8.1.1 when I switched to the WC beta version. Issues occurred before and after updates.

**Comment by tammullen** [comment]
Hi @yukikatayama 

Thank you for taking the time to test and report this bug, we really appreciate your help. I can reproduce it on my end using JN with no existing Jetpack install.

![Screenshot_2020-02-18_at_17_52_58](https://user-images.githubusercontent.com/24649833/74763480-ce109300-5277-11ea-82ca-202f35130a80.png)
Error displayed after clicking Activate and Continue

You can continue by going using the browser's back button but that isn't ideal.
