### ISSUE TITLE
WooCommerce Cupon Code (Bug) - Update V.3.9.2

### ISSUE THREAD

**Issue by ThriftMembers** [woocommerce/woocommerce#25677]
**PROBLEM SOLVED - SEE COMMENTS**
https://github.com/woocommerce/woocommerce/issues/25677#issuecomment-586593685

**Describe the bug**
I noticed that after the last update of WooCommerce (V.3.9.2) the Cupon Code is generating HTML that is not supposed to be there. The Cupon Code is set to give customers free shipping after a certain amount is reached. This worked fine before the update - no problems what so ever.

After the update, once I use a Cupon Code, but the min amount isn't reached, this is shown: 

` <span class=”woocommerce-Price-amount-Price-amount”><span class=”woocommerce-Price-currencySymbol”>DKK</span> 400,00</span>
`

The text of the DKK and 400,00 shown, is like it should (depending on what Cupon Code I use).
It manages to add the HTML string to this as well no matter what Cupon Code I try.

I used the **Health Check & Troubleshooting** plugin to troubleshoot this issue.

1. Tried another theme to make sure this wasn't the issue. (used Twenty Twenty).
2. Tried to deactivate all plugins besides WooCommerce - didn't work.
3. Tried both combined. - Still didn't work.

**To Reproduce**
1. Go to basket or checkout and use a cupon code, that provides free shipping (or whatever), but that requires a certain min amount to be activated.

2. Once the Cupon Code is activated this error shows up.

**IMPORTANT:**
Make sure the minimum amount is **NOT** reached, you need the error message or this will **NOT** show up.

**Screenshots**
![billede](https://user-images.githubusercontent.com/61068289/74574236-4e3aae00-4f83-11ea-8b73-f146a1eb4036.png)

**Isolating the problem (mark completed items with an [x]):**
- [ X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ X ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

### WordPress Environment ###

WordPress address (URL): https://www.thriftmembers.com
Site address (URL): https://www.thriftmembers.com
WC Version: 3.9.2
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 102 MB
WP Debug Mode: –
WP Cron: ✔
Language: da_DK
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.14
PHP Post Max Size: 96 MB
PHP Time Limit: 50
PHP Max Input Vars: 5000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.21-MariaDB-1:10.3.21+maria~bionic
Max Upload Size: 96 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.2
WC Database Prefix: www0_
Total databasestørrelse: 61.87MB
Database datastørrelse: 56.92MB
Database indexstørrelse: 4.95MB
www0_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
www0_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
www0_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
www0_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_aws_cache: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
www0_aws_index: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
www0_ays_sccp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_ays_sccp_block_content: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
www0_layerslider: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_layerslider_revisions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_options: Data: 5.42MB + Index: 0.19MB + Engine InnoDB
www0_postmeta: Data: 2.25MB + Index: 0.33MB + Engine InnoDB
www0_posts: Data: 0.23MB + Index: 0.08MB + Engine InnoDB
www0_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
www0_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_revslider_sliders: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
www0_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_revslider_slides: Data: 0.47MB + Index: 0.00MB + Engine InnoDB
www0_revslider_slides_bkp: Data: 0.33MB + Index: 0.00MB + Engine InnoDB
www0_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_shipment_batch_process: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_swpm_membership_meta_tbl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_swpm_membership_tbl: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_swpm_members_tbl: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_swpm_payments_tbl: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_termmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
www0_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
www0_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
www0_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
www0_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
www0_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
www0_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
www0_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_wfblockediplog: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
www0_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
www0_wfconfig: Data: 0.45MB + Index: 0.00MB + Engine InnoDB
www0_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_wffilemods: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
www0_wfhits: Data: 1.52MB + Index: 0.22MB + Engine InnoDB
www0_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
www0_wfknownfilelist: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
www0_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_wflocs: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
www0_wflogins: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
www0_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
www0_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
www0_wfstatus: Data: 0.17MB + Index: 0.09MB + Engine InnoDB
www0_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_woo_shippment_provider: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
www0_wpuf_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_wpuf_transaction: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
www0_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_yith_ywpar_points_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
www_eg_grids: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www_eg_item_elements: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www_eg_item_skins: Data: 0.20MB + Index: 0.03MB + Engine InnoDB
www_eg_navigation_skins: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
www_layerslider: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www_layerslider_revisions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www_options: Data: 2.50MB + Index: 0.08MB + Engine InnoDB
www_postmeta: Data: 3.52MB + Index: 0.64MB + Engine InnoDB
www_posts: Data: 2.52MB + Index: 0.25MB + Engine InnoDB
www_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
www_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www_revslider_sliders: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
www_revslider_sliders_bkp: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
www_revslider_slides: Data: 7.52MB + Index: 0.00MB + Engine InnoDB
www_revslider_slides_bkp: Data: 7.52MB + Index: 0.00MB + Engine InnoDB
www_revslider_static_slides: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
www_revslider_static_slides_bkp: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
www_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www_term_relationships: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
www_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
www_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
www_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
www_wfconfig: Data: 0.44MB + Index: 0.00MB + Engine InnoDB
www_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www_wffilemods: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
www_wfhits: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
www_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
www_wfknownfilelist: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
www_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
www_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
www_wfstatus: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
www_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
www_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
www_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 284
cookielawinfo: 1
mc4wp-form: 1
mpc_badge: 1
mpcth_of: 22
nav_menu_item: 44
page: 21
post: 1
product: 12
revision: 1
scheduled-action: 18
shop_coupon: 6
shop_order: 4
shop_order_refund: 2
swpm_payment_button: 4
tribe_events: 1
tribe_organizer: 1
tribe_venue: 1
user_request: 2
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (2) ###

Health Check & Troubleshooting: af The WordPress.org community – 1.4.2
WooCommerce: af Automattic – 3.9.2

### Inactive Plugins (29) ###

Advanced Custom Fields: af Elliot Condon – 5.8.7
Advanced Custom Fields: Gallery Field: af Elliot Condon – 2.1.0
Advanced Custom Fields: Repeater Field: af Elliot Condon – 2.1.0
Advanced Woo Search: af ILLID – 1.93
Booster Plus for WooCommerce: af Algoritmika Ltd – 4.7.1
Coming Soon Page, Under Construction & Maintenance Mode by SeedProd: af SeedProd – 5.1.0
Contact Form 7: af Takayuki Miyoshi – 5.1.6
Customerly Live Chat: af Customerly.io – 1.7.3
GDPR Cookie Consent: af WebToffee – 1.8.3
Loco Translate: af Tim Whitlock – 2.3.1
MC4WP: Mailchimp for WordPress: af ibericode – 4.7.5
MPC Extensions: af MassivePixelCreation – 3.9.9.1
MPC Importer: af MassivePixelCreation – 3.9.9.4
MPC Mega Menu: af Lee Chestnutt | Modified by MPC Team – 3.9.7
MPC Shortcodes: af MassivePixelCreation – 3.8.2
MPC Widgets: af MassivePixelCreation – 3.9.5
Secure Copy Content Protection: af Copy Content Protection Team – 1.8.1
Shipmondo for WooCommerce: af Shipmondo – 3.1.1
Simple WordPress Membership: af smp7
wp.insider – 3.9.6

Slider Revolution: af ThemePunch – 6.1.8
SWPM Show Member Info: af smp7
wp.insider – 1.8

Trustpilot-reviews: af Trustpilot – 2.5.800 – Ikke testet med den aktive version af WooCommerce
WooCommerce Admin: af WooCommerce – 0.25.1
WooCommerce PayPal Checkout Gateway: af WooCommerce – 1.6.19
WooCommerce Quickview: af Iconic – 3.9.7.2 – Ikke testet med den aktive version af WooCommerce
WooCommerce Services: af Automattic – 1.22.3
Wordfence Security: af Wordfence – 7.4.6
WPBakery Page Builder: af Michael M - WPBakery.com – 6.0.5
YITH WooCommerce Points and Rewards: af YITH – 1.4.2

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: af  – 1.7.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: DKK (DKK)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop basisside: #6 - /shop/
Kurv: #3374 - /kurv/
Checkout: #3375 - /kasse/
Min konto: ❌ Siden indeholder ikke en kortkode (shortcode).
Handelsbetingelser: #3935 - /handelsbetingelser/

### Theme ###

Name: Blaszok
Version: 3.9.9.4
Author URL: http://mpcreation.net
Child Theme: ❌ – Hvis du redigerer WooCommerce i et hovedtema
som du ikke selv har udviklet
anbefaler vi
at du anvender et undertema (child theme). Se: Hvordan du opretter et undertema

WooCommerce Support: ✔

### Templates ###

Overrides: blaszok/woocommerce/archive-product.php
blaszok/woocommerce/cart/cart-totals.php
blaszok/woocommerce/cart/cart.php
blaszok/woocommerce/cart/cross-sells.php
blaszok/woocommerce/cart/shipping-calculator.php
blaszok/woocommerce/checkout/form-billing.php
blaszok/woocommerce/checkout/form-checkout.php
blaszok/woocommerce/checkout/form-shipping.php
blaszok/woocommerce/content-product.php
blaszok/woocommerce/content-product_cat.php
blaszok/woocommerce/content-single-product.php
blaszok/woocommerce/loop/add-to-cart.php
blaszok/woocommerce/loop/loop-end.php
blaszok/woocommerce/loop/loop-start.php
blaszok/woocommerce/loop/no-products-found.php
blaszok/woocommerce/loop/pagination.php
blaszok/woocommerce/loop/result-count.php
blaszok/woocommerce/loop/sale-flash.php
blaszok/woocommerce/myaccount/form-edit-address.php
blaszok/woocommerce/myaccount/form-login.php
blaszok/woocommerce/myaccount/my-address.php
blaszok/woocommerce/myaccount/my-orders.php
blaszok/woocommerce/notices/error.php version 3.5.0 er udgået. Kerneversionen er 3.9.0
blaszok/woocommerce/notices/notice.php version 3.5.0 er udgået. Kerneversionen er 3.9.0
blaszok/woocommerce/notices/success.php version 3.5.0 er udgået. Kerneversionen er 3.9.0
blaszok/woocommerce/order/tracking.php
blaszok/product-searchform.php
blaszok/woocommerce/single-product/meta.php
blaszok/woocommerce/single-product/product-image.php
blaszok/woocommerce/single-product/product-thumbnails.php
blaszok/woocommerce/single-product/related.php version 3.0.0 er udgået. Kerneversionen er 3.9.0
blaszok/woocommerce/single-product/review.php
blaszok/woocommerce/single-product/sale-flash.php
blaszok/woocommerce/single-product/tabs/additional-information.php
blaszok/woocommerce/single-product/tabs/description.php
blaszok/woocommerce/single-product/tabs/tabs.php
blaszok/woocommerce/single-product/up-sells.php

Outdated Templates: ❌
					
					
						Lær hvordan man opdaterer

### Action Scheduler ###

Gennemført: 17
Oldest: 2020-02-13 21:21:16 +0100
Newest: 2020-02-14 22:47:30 +0100

Afventer: 1
Oldest: 2020-02-14 23:47:30 +0100
Newest: 2020-02-14 23:47:30 +0100

Annulleret: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Mislykket: 0
Oldest: –
Newest: –

`

</details>

**Comment by CKENT0369** [comment]
I am having this issue as well.

**Comment by ThriftMembers** [comment]
> 
> 
> I am having this issue as well.

@CKENT0369 

After some research on forums I found the problem.

For some reason it would not accept the `<span class=""></span>` string so I went to the **wc-formatting-functions.php** located at **woocommerce/includes/wc-formatting-functions.php** and deleted the strings from within the php file.

This is normally not something I would do, but I made it work and it dosen’t seem to have affected my website in any ways.

Never found out whats causing the problem to begin with, but seems to be working once you delete the `<span class=""></span>` in the php file.

Maybe this would be a help for you and/or others, that has this problem too 🙂

Have a great weekend! 🙂

**Comment by CKENT0369** [comment]
What line in that file because I dont see that exact text.

**Comment by ThriftMembers** [comment]
> 
> 
> What line in that file because I dont see that exact text.

@CKENT0369 it depends on how much custom coding you have in your code.
You should be able to see the strings as text in the PHP file. Some is between line 1-44 mine was all the way down aroundline 550 (i have a big webshop with a lot of customizations).

You could try send me the code, and I'll tell you what line excatly you need to delete. :)

**Comment by ThriftMembers** [comment]
@CKENT0369 

Make sure you locate the right file.
/wp-content/plugins/woocommerce/includes/**wc-formatting-functions.php**

You should see both class-wc-_filename_ and just wc-_filename_.
Make sure to get the wc-filename file called **wc-formatting-functions.php**.

**Comment by CKENT0369** [comment]
I got it  See the parts I commented out. 

`$formatted_price = ( $negative ? '-' : '' ) . sprintf( $args['price_format'], /**'<span class="woocommerce-Price-currencySymbol">' . **/get_woocommerce_currency_symbol( $args['currency'] ) /**. '</span>'**/, $price );
	$return          = /***'<span class="woocommerce-Price-amount amount">' .***/ $formatted_price /**. '</span>'**/;`

**Comment by ThriftMembers** [comment]
Excatly. You just remove the following:

```
$formatted_price = ( $negative ? '-' : '' ) . sprintf( $args['price_format'], '' . get_woocommerce_currency_symbol( $args['currency'] ) . '', $price );
	$return          = '' . $formatted_price . '';

	if ( $args['ex_tax_label'] && wc_tax_enabled() ) {
		$return .= ' <small class="woocommerce-Price-taxLabel tax_label">' . WC()->countries->ex_tax_or_vat() . '</small>';
```

Make sure to leave the txt string beginning and end **''** these should not be removed.

**Comment by ThriftMembers** [comment]
@CKENT0369 let me know if it works for you :)
