### ISSUE TITLE
product attribute archives automatically reenabled

### ISSUE THREAD

**Issue by Mesmer7** [woocommerce/woocommerce#25674]
**Describe the bug**
The software randomly reenables product attribute archives after I have disabled them. 

I have defined 6 product attributes. I enabled archives for 3 of the attributes and disabled archives for the other three. But something in the software has re-enabled ALL archives five times over the past two years.  

**To Reproduce**
I do not know how to reproduce/trigger this bug. 

At least two of these occurrences have occurred after a woocommerce database update. I didn't catch the other occurrences quick enough to be certain when they happened. 

The most recent occurrence was this week.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://www.hypnoticdreams.com
Site address (URL): https://www.hypnoticdreams.com
WC Version: 3.9.2
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.13
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.46-cll-lve
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.2
WC Database Prefix: wp_
Total Database Size: 11.00MB
Database Data Size: 8.58MB
Database Index Size: 2.42MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.06MB + Index: 0.07MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.22MB + Index: 0.17MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_blc_filters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_blc_instances: Data: 0.07MB + Index: 0.02MB + Engine MyISAM
wp_blc_links: Data: 0.38MB + Index: 0.05MB + Engine MyISAM
wp_blc_synch: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wp_commentmeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_comments: Data: 0.20MB + Index: 0.09MB + Engine MyISAM
wp_ewwwio_images: Data: 0.95MB + Index: 0.06MB + Engine MyISAM
wp_ewwwio_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mbdb_books: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 1.19MB + Index: 0.35MB + Engine MyISAM
wp_postmeta: Data: 1.31MB + Index: 0.66MB + Engine MyISAM
wp_posts: Data: 0.60MB + Index: 0.08MB + Engine MyISAM
wp_responsive_menu: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_termmeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_terms: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wp_term_relationships: Data: 0.02MB + Index: 0.04MB + Engine MyISAM
wp_term_taxonomy: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_usermeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_download_log: Data: 0.03MB + Index: 0.04MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfBlockedIPLog: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfBlocks7: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfConfig: Data: 0.40MB + Index: 0.01MB + Engine MyISAM
wp_wfCrawlers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfFileChanges: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfFileMods: Data: 1.68MB + Index: 0.34MB + Engine MyISAM
wp_wfHits: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wfHoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfIssues: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wfKnownFileList: Data: 0.88MB + Index: 0.11MB + Engine MyISAM
wp_wfLiveTrafficHuman: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfLocs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfLogins: Data: 0.05MB + Index: 0.02MB + Engine MyISAM
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfNotifications: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_wfPendingIssues: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wfReverseCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfSNIPCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfStatus: Data: 0.08MB + Index: 0.03MB + Engine MyISAM
wp_wfTrafficRates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woof_query_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_seo_links: Data: 0.16MB + Index: 0.04MB + Engine MyISAM
wp_yoast_seo_meta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM

### Post Type Counts ###

anr-post: 1
attachment: 122
carousels: 13
custom_css: 1
elementor_library: 1
faq: 20
mbdb_book: 2
mc4wp-form: 2
nav_menu_item: 31
oembed_cache: 9
page: 12
post: 115
product: 28
rttpg: 3
scheduled-action: 6
shop_coupon: 3
shop_order: 359
shop_order_refund: 3
sidebar: 1
tt_font_control: 2
woocarousel: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Advanced Database Cleaner: by Younes JFR. – 3.0.0
Advanced noCaptcha & invisible Captcha: by Shamim Hasan – 5.6 – Not tested with the active version of WooCommerce
Arconix FAQ: by Tyche Softwares – 1.9.1
The SEO Framework: by The SEO Framework Team – 4.0.4
Carousel Slider: by Sayful Islam – 1.9.3 – Not tested with the active version of WooCommerce
Classic Editor: by WordPress Contributors – 1.5
Contact Form 7: by Takayuki Miyoshi – 5.1.6
EWWW Image Optimizer: by Exactly WWW – 5.2.1
Hypnotic Dreams  - AutoComplete Orders: by Hypnotic Dreams – 2.0
MC4WP: Mailchimp for WordPress: by ibericode – 4.7.5
Mooberry Book Manager: by Mooberry Dreams – 4.1.22
Hypnotic Dreams Latest News posts: by Hypnotic Dreams –
Responsive Menu: by ExpressTech – 3.1.25
W3 Total Cache: by BoldGrid – 0.13.1
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.4.0 – Not tested with the active version of WooCommerce
WooCommerce Grid / List toggle: by jameskoster but edited by Hypnotic Dreams – 1.2.1 – Not tested with the active version of WooCommerce
WOOF - WooCommerce Products Filter: by realmag777 – 1.2.3 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.9.2
WooSidebars: by WooCommerce – 1.4.5
Wordfence Security: by Wordfence – 7.4.6
Asset CleanUp: Page Speed Booster: by Gabriel Livan – 1.3.5.5

### Inactive Plugins (5) ###

Broken Link Checker: by ManageWP – 1.11.11
Query Monitor: by John Blackbourn – 3.5.2
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.3
Woocommerce upcoming Products: by Mohaiminul Islam – 1.5.9.2 – Not tested with the active version of WooCommerce
Yoast SEO: by Team Yoast – 13.0

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #24 - /mp3s/
Cart: #25 - /cart/
Checkout: #26 - /checkout/
My account: #27 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: HypnoticDreams2019
Version: 1.2
Author URL: https://www.hypnoticdreams.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.5.3
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: hypnoticdreams2019/woocommerce/emails/customer-completed-order.php
hypnoticdreams2019/woocommerce/emails/customer-processing-order.php


### Action Scheduler ###

Complete: 6
Oldest: 2020-01-21 13:00:06 -0500
Newest: 2020-02-10 13:05:42 -0500

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by juliaamosova** [comment]
Hi @Mesmer7,

Thank you for raising the issue. 

It is the hardest for us to confirm and fix the issue (if confirmed) when we don't know how to reproduce it. 

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again by leaving it as is for some time in order to see if the issue appears. It is best to do it on the stating or test site. 

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by Mesmer7** [comment]
I have been using Storefront as a parent theme. I built my own child them, and it doesn't change anything in the database. So it can't be that. 

I'm aware of how difficult it is to fix a problem when you can't find what's triggering it. But unfortunately, I can't leave all my plugins disabled for 6 months while I wait for it to happen again.

**Comment by juliaamosova** [comment]
Thanks for getting back on this issue @Mesmer7. 

>But unfortunately, I can't leave all my plugins disabled for 6 months while I wait for it to happen again.

As I mentioned in my comment, it is best to test something like this on a staging or test site (not live). Since it can't be reproduced, the cause is not known and we haven't received any other similar requests, I am going to close this issue. 

Please feel free to comment on it again in case you'd have an idea what could be causing it on your end and we will take another look.

**Comment by lionheart-web-design** [comment]
I've had the exact same issue on 2 different sites both with very different plugins and I'm NOT using the Storefront theme.  It is definitely something that happens when the site is updated. That's all I can figure out.

**Comment by Mesmer7** [comment]
> I've had the exact same issue on 2 different sites both with very different plugins and I'm NOT using the Storefront theme. It is definitely something that happens when the site is updated. That's all I can figure out.

Thanks, lionheart. Since I've never seen anyone else mention this, I had concluded it was just my site. I still haven't figured it out, but I had a thought. Any chance you're using Yoast or Rank Math to rewrite the shop category and tag URLs?

**Comment by lionheart-web-design** [comment]
Thanks for the feedback. Yes I'm using Yoast. That might make sense that there is a conflict there. I use the Avada Fusion Builder theme.  I only noticed this starting this January with one of my sites. I went live and submitted the sitemap and then realized the sitemap wasn't what it looked like pre-launch.  This specific client had dozens of product attributes which we did not want archive urls for.  So it was very obvious. I had to quickly redo the work. But then several times over the past 3 months it kept happening. Today another of my clients I was looking at their product attributes and noticed the same thing.  I might reach out to Yoast and see if they can think of anything.  Thanks again.

**Comment by lionheart-web-design** [comment]
Ok- I figured it out!  It is an issue with Yoast.  So here's what's happening.  Typically before I go live I check the sitemap and turn things off in Yoast that aren't needed.  Later the client asks for a new product attribute and I simply uncheck 'Enable archives' thinking that will keep it from creating urls and showing up in the site index.  And it does temporarily, BUT I hadn't gone into Yoast Settings to ALSO turn it off there.  BUT the main problem is that Yoast does NOT show ALL of your attributes - especially if you have a lot.  So it seems like Yoast's default is to have everything ON, and YOU have to tell it to turn it OFF.  Since Yoast is not giving you access to ALL of the attributes in Yoast's settings, they are ON by default- and it overrides the unchecked 'Enable archives'.  I tested this on two different sites.  It has to be turned OFF IN BOTH PLACES for it to not show in the sitemap now and in the future. Basically Yoast needs to 1) either respect the 'Enable archives' checkbox or 2) show ALL your attributes, but it can't or should NOT do both.  I have a client with a paid Yoast plugin who is going to ask them about this.  What also sucks is that Yoast adds 'new' things, like FAQ Categories (which previously it did not have) and they turn them ON automatically, which affects your sitemap - not cool Yoast!

**Comment by Mesmer7** [comment]
@lionheart-web-design 

I had a hunch. Thanks for confirming it. However, I quit using Yoast years ago. I'm currently using Rank.
