### ISSUE TITLE
Add custom state 

### ISSUE THREAD

**Issue by mustafa2731** [woocommerce/woocommerce#25684]
Hello There, 

By using your code I have added custom states at my woocommerce. But I am looking for your help to create a mandatory filed during checkout for the below option. By default, it is showing optional at the filed by because of this people are eliminating this field to avoid the delivery charges. 

I am looking for your help to solve this issue .

/*
 Add this to your theme's functions.php file. Replace XX with the country code
*/

add_filter( 'woocommerce_states', 'custom_woocommerce_states' );
 
function custom_woocommerce_states( $states ) {
 
    $states['XX'] = array(
            'XX1' => __('State 1', 'woocommerce') ,
            'XX2' => __('State 2', 'woocommerce') ,
            'XX3' => __('State 3', 'woocommerce') ,
    );

    return $states;
}

appreciate your support

**Comment by juliaamosova** [comment]
Hi @mustafa2731,

I believe you need to modify the checkout fields to make the custom state field you created required. Take a look at this issue where I provide several examples: https://github.com/woocommerce/woocommerce/issues/25142.
