### ISSUE TITLE
[4.0 beta] Notices Dismiss Button Alignment

### ISSUE THREAD

**Issue by jffng** [woocommerce/woocommerce#25692]
**Describe the bug**
The dismiss button on notices are not aligned, depending on the type of notice. 

**To Reproduce**
- Open WC admin on [this site](https://bluehost-and-a8c.com/wp-admin) and view any of the notices. 
- If using WC 4.0+, expand Notices from the top menu

**Screenshots**
<img width="1337" alt="Screen Shot 2020-02-17 at 3 34 30 PM" src="https://user-images.githubusercontent.com/5375500/74685184-c085db00-519b-11ea-8416-3dc8dc7206c5.png">

**Expected behavior**
I expect the placement and style of the Notices, including their dismiss button, to be consistent. 

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

### WordPress Environment ###

WordPress address (URL): https://bluehost-and-a8c.com
Site address (URL): https://bluehost-and-a8c.com
WC Version: 3.9.2
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.4-beta1-47294
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.26
PHP Post Max Size: 260 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.67.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.23-23
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.2
WC Database Prefix: _DYD_
Total Database Size: 6.82MB
Database Data Size: 5.89MB
Database Index Size: 0.93MB
_DYD_woocommerce_sessions: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
_DYD_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_DYD_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
_DYD_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_DYD_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_actionscheduler_actions: Data: 0.20MB + Index: 0.07MB + Engine MyISAM
_DYD_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_DYD_actionscheduler_logs: Data: 0.15MB + Index: 0.09MB + Engine MyISAM
_DYD_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_DYD_comments: Data: 0.16MB + Index: 0.13MB + Engine MyISAM
_DYD_email_log: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
_DYD_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_mailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_mailchimp_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_options: Data: 4.63MB + Index: 0.15MB + Engine MyISAM
_DYD_postmeta: Data: 0.43MB + Index: 0.18MB + Engine MyISAM
_DYD_posts: Data: 0.22MB + Index: 0.13MB + Engine MyISAM
_DYD_termmeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
_DYD_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_DYD_term_relationships: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
_DYD_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_usermeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
_DYD_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_DYD_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_DYD_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_DYD_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_DYD_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_DYD_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_DYD_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 39
nav_menu_item: 20
page: 9
post: 3
product: 33
product_variation: 5
revision: 24
shop_coupon: 3
shop_order: 12
shop_order_refund: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

Enable WooCommerce Onboarding Split Test: by Automattic – 1.0.0 – Not tested with the active version of WooCommerce
Debug Bar - Enable WP_DEBUG from admin dashboard: by Puvox.software – 1.82
Facebook for WooCommerce: by Facebook – 1.9.15 – Not tested with the active version of WooCommerce
Fusion Builder: by ThemeFusion – 2.1.2
Fusion Core: by ThemeFusion – 4.1.2
Jetpack by WordPress.com: by Automattic – 8.1.1
Mailchimp for WooCommerce: by Mailchimp – 2.3.1 – Not tested with the active version of WooCommerce
Password Protected: by Ben Huson – 2.2.5
WooCommerce Beta Tester: by WooCommerce – 2.0.1 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.3.1 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.22.3
WooCommerce: by Automattic – 3.9.2
WordPress Beta Tester: by Peter Westwood
Andy Fragen – 2.1.0

### Inactive Plugins (10) ###

Akismet Anti-Spam: by Automattic – 4.1.3
Email Log: by Sudar – 2.3.1
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.10.4
Hello Dolly: by Matt Mullenweg – 1.7.2
MOJO Marketplace: by Mike Hansen – 1.4.6
OptinMonster API: by OptinMonster Team – 1.9.6 – Not tested with the active version of WooCommerce
Query Monitor: by John Blackbourn – 3.5.2
VaultPress: by Automattic – 2.1.1
WPForms Lite: by WPForms – 1.5.8.2
WP phpMyAdmin: by Puvox.software – 3.01

### Dropin Plugins (2) ###

db-error.php: db-error.php
maintenance.php: maintenance.php

### Must Use Plugins (3) ###

Endurance Browser Cache: by Mike Hansen – 0.4
Endurance Page Cache: by Mike Hansen – 1.6
SSO: by Garth Mortensen
Mike Hansen – 0.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #21 - /
Cart: #22 - /cart/
Checkout: #23 - /checkout/
My account: #24 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Avada
Version: 6.1.2
Author URL: http://themeforest.net/user/ThemeFusion
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

### Action Scheduler ###

Complete: 0
Oldest: –
Newest: –

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –</details>

**Comment by swatipawarGS** [comment]
Hi @jffng ,

Thank you for taking the time to report this bug, we really appreciate your help. We are able to reproduce the issue on our end using WooCommerce 5.9.0 version. 

Please find below screenshot for reference :

![#25692](https://user-images.githubusercontent.com/94531721/145801591-08eb52d1-28e7-4493-8cc0-6f0646d401cf.jpg)


Priority of this issue will be assigned shortly after we’d go through a round of prioritization. Please note it may take a couple of days.

**Comment by rrennick** [comment]
We don't have control over this as other plugins/extensions can style their own dismiss buttons/icons.
