### ISSUE TITLE
Coupon Error Message Appear as HTML Code

### ISSUE THREAD

**Issue by synora** [woocommerce/woocommerce#25699]
**Describe the bug**
When a coupon code with a minimum or max spend amount is entered at checkout, an error is thrown and is displayed in HTML. 

The error occurs when the cart subtotal is less than the coupon's minimum spend amount or greater than the coupon's max spend amount. 

```
The minimum spend for this coupon is <span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">$</span>159.00</span>.
``` 

**To Reproduce**
1. Go to WooCommerce > Coupons and create a coupon of any amount.
2. Within the coupon, click on 'Usage restriction' and enter a 'minimum spend' or 'maximum spend' amount. 
3. Publish the coupon.
4. Test coupon by adding items to cart and entering coupon code. If the coupon has a minimum spend amount, add items to the cart that create a subtotal less than the coupon spend amount and vise versa for coupons with max spend amounts. 

**Screenshots**
This is a screenshot of a coupon with a minimum spend amount being applied to a cart that has a subtotal less than the coupon's minimum spend amount: 

![Screen Shot on 2020-02-18 at 14-11-24](https://user-images.githubusercontent.com/10015451/74769583-ad851080-5258-11ea-98fa-4c87d7016a56.png)

**Expected behavior**
A string of words is expected as an error message rather than HTML.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ X] I can reproduce this bug consistently using the steps above.

There are two other reports of this at https://wordpress.org/support/topic/coupon-18/

**Comment by Eproksw** [comment]
I have the same problem.

**Comment by noremlas** [comment]
I also have that problem

**Comment by MarijaPP** [comment]
same problem here

**Comment by Josimarcsilva** [comment]
I also have the same problem.

**Comment by peterfabian** [comment]
Thanks all for reporting. We're preparing a fix for this and it will be released soon.

**Comment by Lobzik525** [comment]
I also have the same problem too

**Comment by josevarghese** [comment]
Eagerly waiting for the bug fix release :)

**Comment by peterfabian** [comment]
This should be fixed with 3.9.3. Please create a new issue if you're still experiencing problems.

**Comment by josevarghese** [comment]
Thanks! v3.9.3 fixed it :)

**Comment by noremlas** [comment]
Right.  3.9.3 fix this problem.  Thank you

**Comment by Chavesjr** [comment]
somehow is it possible to be fixed in this on release 3.9.2 Pls

**Comment by peterfabian** [comment]
@Chavesjr 

You can download WC 3.9.3 from wordpress.org, take these 4 files, then replace the existing ones you have in WC 3.9.2 with the new ones and it should work (**please back up before doing this just in case**):
- includes/abstracts/abstract-wc-order.php 
- includes/class-wc-cart.php 
- includes/class-wc-coupon.php 
- includes/class-wc-discounts.php

**Comment by krotkolapka** [comment]
I have WC 4.0.1, but I still have the same problem.
![Screenshot 2020-04-23 at 09 44 57](https://user-images.githubusercontent.com/46359826/80072956-3d8c5280-8547-11ea-8692-95bf9b4da529.jpg)

**Comment by peterfabian** [comment]
@krotkolapka 
can you please open a new issue? We've fixed this as far as I know and the escaping function should allow `<span>` tags. Only way I could see this still happening was if somehow your `includes/class-wc-cart.php` was from an older version of WooCommerce?

**Comment by castilloedwin** [comment]
Thanks, 3.9.3 fix this problem
