### ISSUE TITLE
[4.0 beta1 / 3.9.2 ] Action Scheduler Webhook ArgumentCountError

### ISSUE THREAD

**Issue by jffng** [woocommerce/woocommerce#25691]
**Describe the bug**
Following the steps to create a webhook on WC 3.9.2 on [this Bluehost test site](https://bluehost-and-a8c.com/), I encountered the following error. From the WC logs after creating a webhook and attempting to trigger it:

```
2020-02-17T19:40:04+00:00 CRITICAL Uncaught ArgumentCountError: Too few arguments to function wc_deliver_webhook_async(), 0 passed in /home4/bluehql6/public_html/wp-includes/class-wp-hook.php on line 287 and exactly 2 expected in /home4/bluehql6/public_html/wp-content/plugins/woocommerce/includes/wc-webhook-functions.php:51
Stack trace:
#0 /home4/bluehql6/public_html/wp-includes/class-wp-hook.php(287): wc_deliver_webhook_async()
#1 /home4/bluehql6/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#2 /home4/bluehql6/public_html/wp-includes/plugin.php(544): WP_Hook->do_action(Array)
#3 /home4/bluehql6/public_html/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_Action.php(22): do_action_ref_array('woocommerce_del...', Array)
#4 /home4/bluehql6/public_html/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/classes/ActionScheduler_Abstract_QueueRunner.php(59): ActionScheduler_Action->execute()
#5 /home4/bluehql6/public_html/wp-content/plugins/woocommerce/incl in /home4/bluehql6/public_html/wp-content/plugins/woocommerce/includes/wc-webhook-functions.php on line 51
```

**To Reproduce**
I encountered this error after the following steps:

1. Switch to WC 3.9.2 using the Beta Tester plugin.
2. Following the _Basic_ instructions outlined here https://github.com/woocommerce/woocommerce/wiki/Release-Testing-Instructions#40

Looking at the timestamps, it looks like the error occurred after the webhook was created and right before the webhook was first triggered. 

https://webhook.site/#!/f0a73ee8-206f-405d-9cb0-792fd6fdc5a1/f4dc59e9-1dd1-44aa-908f-b7617747717d/1
 
I cannot reproduce reproduce the error. 

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

### WordPress Environment ###

WordPress address (URL): https://bluehost-and-a8c.com
Site address (URL): https://bluehost-and-a8c.com
WC Version: 3.9.2
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.4-beta1-47294
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.26
PHP Post Max Size: 260 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.67.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.23-23
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.2
WC Database Prefix: _DYD_
Total Database Size: 6.10MB
Database Data Size: 5.44MB
Database Index Size: 0.66MB
_DYD_woocommerce_sessions: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
_DYD_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_DYD_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
_DYD_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_DYD_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_DYD_comments: Data: 0.16MB + Index: 0.13MB + Engine MyISAM
_DYD_email_log: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
_DYD_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_mailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_mailchimp_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_options: Data: 4.53MB + Index: 0.08MB + Engine MyISAM
_DYD_postmeta: Data: 0.43MB + Index: 0.18MB + Engine MyISAM
_DYD_posts: Data: 0.22MB + Index: 0.13MB + Engine MyISAM
_DYD_termmeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
_DYD_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_DYD_term_relationships: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
_DYD_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_usermeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
_DYD_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_DYD_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_wc_customer_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_wc_order_product_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_wc_order_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
_DYD_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_DYD_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
_DYD_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 39
nav_menu_item: 20
page: 9
post: 3
product: 32
product_variation: 5
revision: 24
scheduled-action: 544
shop_coupon: 3
shop_order: 12
shop_order_refund: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (13) ###

Enable WooCommerce Onboarding Split Test: by Automattic – 1.0.0 – Not tested with the active version of WooCommerce
Debug Bar - Enable WP_DEBUG from admin dashboard: by Puvox.software – 1.82
Facebook for WooCommerce: by Facebook – 1.9.15 – Not tested with the active version of WooCommerce
Fusion Builder: by ThemeFusion – 2.1.2
Fusion Core: by ThemeFusion – 4.1.2
Jetpack by WordPress.com: by Automattic – 8.1.1
Mailchimp for WooCommerce: by Mailchimp – 2.3.1 – Not tested with the active version of WooCommerce
Password Protected: by Ben Huson – 2.2.5
WooCommerce Beta Tester: by WooCommerce – 2.0.1 – Not tested with the active version of WooCommerce
WooCommerce Stripe Gateway: by WooCommerce – 4.3.1 – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.22.3
WooCommerce: by Automattic – 3.9.2 – 4.0.0-beta.1 is available
WordPress Beta Tester: by Peter Westwood
Andy Fragen – 2.1.0

### Inactive Plugins (10) ###

Akismet Anti-Spam: by Automattic – 4.1.3
Email Log: by Sudar – 2.3.1
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.10.4
Hello Dolly: by Matt Mullenweg – 1.7.2
MOJO Marketplace: by Mike Hansen – 1.4.6
OptinMonster API: by OptinMonster Team – 1.9.6 – Not tested with the active version of WooCommerce
Query Monitor: by John Blackbourn – 3.5.2
VaultPress: by Automattic – 2.1.1
WPForms Lite: by WPForms – 1.5.8.2
WP phpMyAdmin: by Puvox.software – 3.01

### Dropin Plugins (2) ###

db-error.php: db-error.php
maintenance.php: maintenance.php

### Must Use Plugins (3) ###

Endurance Browser Cache: by Mike Hansen – 0.4
Endurance Page Cache: by Mike Hansen – 1.6
SSO: by Garth Mortensen
Mike Hansen – 0.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #21 - /
Cart: #22 - /cart/
Checkout: #23 - /checkout/
My account: #24 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Avada
Version: 6.1.2
Author URL: http://themeforest.net/user/ThemeFusion
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

### Action Scheduler ###

Complete: 541
Oldest: 2020-01-17 20:15:52 +0000
Newest: 2020-02-17 19:48:53 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 2
Oldest: 2020-01-21 10:17:28 +0000
Newest: 2020-02-17 20:11:42 +0000

In-progress: 0
Oldest: –
Newest: –

Failed: 1
Oldest: 2020-02-17 19:40:02 +0000
Newest: 2020-02-17 19:40:02 +0000
</details>

**Comment by rodrigoprimo** [comment]
There seems to be a pattern where for some reason Action Scheduler is calling a function with the wrong number of arguments. There are a few issues reporting the same problem but when different functions are called: #24593, #25494, #25081, https://github.com/woocommerce/woocommerce-admin/issues/3169 and https://github.com/mailchimp/mc-woocommerce/issues/509.

I'm not sure if this problem is caused by Action Scheduler itself or by the code that uses it. Anyway, I wonder if we should wrap the `do_action_ref_array()` (https://github.com/woocommerce/action-scheduler/blob/master/classes/actions/ActionScheduler_Action.php#L22) call in a try/catch block to just log the problem and prevent the fatal error? Or maybe it is possible to use PHP reflection to check if the correct number of arguments is passed when the code tries to schedule an action for future execution and fail if the number doesn't match what the function expects? cc @rrennick.

**Comment by rrennick** [comment]
Here's an issue where someone was producing the same error when hooking into the `save_post` action: https://github.com/woocommerce/action-scheduler/issues/391

> I wonder if we should wrap the do_action_ref_array() (https://github.com/woocommerce/action-scheduler/blob/master/classes/actions/ActionScheduler_Action.php#L22) call in a try/catch block to just log the problem and prevent the fatal error?

That sounds like a good approach.

**Comment by rodrigoprimo** [comment]
@rrennick should I create an issue describing this problem and the proposed solution on the Action Scheduler repository?

**Comment by rrennick** [comment]
@rodrigoprimo I'll create the issue & PR in the AS repo today. I'll be adding a hook to fire when this error occurs. Do you think we should add a handler in WC core to log the info if the site has WC logging enabled?

**Comment by rrennick** [comment]
> I wonder if we should wrap the do_action_ref_array() (https://github.com/woocommerce/action-scheduler/blob/master/classes/actions/ActionScheduler_Action.php#L22) call in a try/catch block to just log the problem and prevent the fatal error?

On researching this I realized this is being reported against AS 2.2.5 vs 3.X. WooCommerce does not call `ActionScheduler_Action::execute()` directly. Action Scheduler 3.1.1 only calls it inside a try/catch block. I'm suggesting we not make changes for this unless we have reliable steps to reproduce in 3.1.1.

**Comment by rodrigoprimo** [comment]
@rrennick thanks for pointing that AS 3.1.1 calls `execute()` inside a try/catch block (https://github.com/woocommerce/action-scheduler/blob/be0a27922b6ca34f5f5e924cb7265b78062a2918/classes/abstracts/ActionScheduler_Abstract_QueueRunner.php#L65). That being said, I don't think this is enough to protect against this fatal error as the code is catching `Exception` and `TypeError` does not extend this class. `TypeError` extends `Error` that extends `Throwable` which is also extended by `Exception`. I'm not sure if the best solution is to catch `Throwable` or to call `catch` a second time to catch `TypeError` or `Error`. What do you think?

```
$ wp shell

Psy Shell v0.9.9 (PHP 7.2.27-1+ubuntu18.04.1+deb.sury.org+1 — cli) by Justin Hileman

>>> function do_something( $a ) {}
>>> try {
...     do_something();
... } catch ( Exception $e ) {}
TypeError: Too few arguments to function do_something(), 0 passed in /home/vagrant/.wp-cli/packages/vendor/wp-cli/shell-commandeval()'d code on line 2 and exactly 1 expected
>>> try {
    do_something();
} catch ( TypeError $e ) {}
>>> 
```

**Comment by rrennick** [comment]
> I'm not sure if the best solution is to catch Throwable or to call catch a second time to catch TypeError or Error. What do you think?

`TypeError` & `Error` are only available in PHP >=7.0 so it will require a bit more complex solution.

**Comment by will-in-wi** [comment]
We encountered this issue too, and hacked around it by base64 encoding the payload. It _seems_ to be related to JSON escape sequences, but we've stopped being able to reproduce the issue.

**Comment by sangemaru** [comment]
We also ran into this issue in v3.9.3. Only one such error out of tens of attempts. Have not been able to reproduce after.

**Comment by rrennick** [comment]
I believe this has been addressed in Action Scheduler.
