### ISSUE TITLE
[4.0 beta1] Text on "Update WooCommerce Database" notice button is red

### ISSUE THREAD

**Issue by LCmry** [woocommerce/woocommerce#25690]
**Describe the bug**
The text on the notice to "Update WooCommerce Database" is red and clashes with the purple button.

**To Reproduce**
1. Update to 4.0 beta 1
2. Go to "Notices" in upper right of WC Admin menu bar
3. See that the notice to update the database text is red

**Screenshots**
<img width="1602" alt="Update_db_text" src="https://user-images.githubusercontent.com/7651258/74678755-c914ec00-5170-11ea-9ca8-0e56259060b7.png">

**Expected behavior**
Text isn't red, probably white is expected.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by peterfabian** [comment]
I'm not sure we'll be fixing this as a new notice will be created, but I'll keep it open until the new notice is in place.

**Comment by peterfabian** [comment]
These notices are no longer showing on WC-admin screens, so closing, see https://github.com/woocommerce/woocommerce/pull/25828 and https://github.com/woocommerce/woocommerce/pull/25736 for further reference.
