### ISSUE TITLE
[4.0 beta1] #24818 prevents dynamic addition of data attributes to send to ajax add to cart

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#25694]
**Describe the bug**
8f6cb9d058702b4b83749f971d910e385a975212 introduces an incompatibility with Name Your Price. NYP has offered some ajax add to cart support, but only if the user is using the classes/attributes needed to trigger the WooCommerce scripts in `AddToCartHandler.prototype.onAddToCart` (achieved by using loop classes in the `add-to-cart/simple.php` template. 

I've been able to include the NYP input data dynamically by setting the price as a data attribute on the add to cart button. By looping through the `data()` Woo successfully passed my data into what got sent to the ajax add to cart function.

```
$.each( $thisbutton.data(), function( key, value ) {
	data[ key ] = value;
	data[ key ] = value;
});
```

Unless I am missing a way to insert the data directly into the `dataset`, then it's no longer possible to dynamic add data to the add to cart button for passing to the ajax add to cart function.

**To Reproduce**
1. Override the add to cart simple template with https://gist.github.com/helgatheviking/e9e8c9aebccaf62a259061cd4b0256b7
2. create a simple product with Name Your Price enabled
3. View product, click "add to cart". Should see "please enter valid, positive number" error, which is the error you get when the NYP input field is not present in the `$_POST`

**Expected behavior**
Data attributes can be set dynamically... effectively allowing NYP to pass extra data

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by vedanshujain** [comment]
I can verify that [this change](https://github.com/woocommerce/woocommerce/commit/8f6cb9d058702b4b83749f971d910e385a975212) causes backward incompatibility. A fix would be incoming soon.

**Comment by vedanshujain** [comment]
Closing this issue since this now have pull request, lets continue the discussion over there #25726
