### ISSUE TITLE
Updating product data tabs

### ISSUE THREAD

**Issue by Tim567** [woocommerce/woocommerce#25715]
I am working on a custom plugin using elementor and need to reload the product data tabs of woocommerce. I am creating a new tab with the `add_filter( 'woocommerce_product_tabs',function)` hook. 

I have made it so that it works when you reload the page and the product data tabs are reloaded. But i want to make it so i can reload the product data tabs manualy.

Is there a function I can call to do this?

**Comment by juliaamosova** [comment]
Hi @Tim567,

It sounds as you are trying to refresh the contents of one of the tabs on a product page without reloading the browser page. I don't think that's possible without using AJAX and handling all of that in JS. 

Please note that GitHub should be treated as a place to report bugs - it is not a support portal - as much as we'd like to help, we simply don't have resources for that. Therefore, I am closing this issue. Thanks for understanding!
