### ISSUE TITLE
WooCommerce App (Jetpack): Wrong user

### ISSUE THREAD

**Issue by strarsis** [woocommerce/woocommerce#25738]
**Describe the bug**
All actions by the WooCommerce App are performed as the superadmin user.

**To Reproduce**
1. Connect the WooCommerce App with the shop site (using Jetpack plugin + account).
2. Perform an action, e.g. change the order status from "Processing" to "Completed".
3. Notice (e.g. in Audit Log / Stream) that this action was performed by the superadmin user.

**Expected behavior**
The action should be performed by the particular user, though there is no option for setting the user for the app.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @strarsis,

Thank you for submitting the issue. Can you please confirm that it is related to our [WooCommerce Mobile App](https://woocommerce.com/mobile/)? 

>Notice (e.g. in Audit Log / Stream) that this action was performed by the superadmin user.

Would you please confirm this step? I am looking via `Help & support / Application log` section. There is an entry related to the status change but we don't record the user:

![app](https://user-images.githubusercontent.com/19143190/75179630-7d31ec00-5708-11ea-8918-c850955999ce.jpg)

**Comment by strarsis** [comment]
@juliaamosova: Good point! When the action is correctly mapped to the user, the audit plugins don't interpret them correctly and it is an issue with these instead.
Can I view these logs also on the WordPress Dashboard or JetPack login page?

**Comment by juliaamosova** [comment]
>Good point! When the action is correctly mapped to the user, the audit plugins don't interpret them correctly and it is an issue with these instead.

@strarsis what is the issue exactly? Can you please be more specific? Do I understand correctly that you would like to be able to identify which user performed certain actions on the site? 

>Can I view these logs also on the WordPress Dashboard or JetPack login page?

You can't. But you can use a plugin such as [WP Security Audit Log](https://wordpress.org/plugins/wp-security-audit-log/) that logs all the activity by all users on the site (according to how you would set it up).

**Comment by strarsis** [comment]
@juliaamosova: WP Security Audit Log plugin and the Stream plugin both log the Superuser as the one performing the actions that actually another user does via the WooCommerce app.
To reproduce: Install and enable WP Security Audit Log and also the Stream plugin.
Connect the WooCommerce app as some WordPress user, not as the Superuser.
Perform some action with the WooCommerce App (e.g. change the order status).
View the WP Security Audit Log and Stream activity logs and notice that the originating user is the Superuser.

**Comment by juliaamosova** [comment]
@strarsis I see, thanks for the additional explanation. To confirm we are on the same page with your feature request - you would like to be able to identify which user made a change in the app using any activity log plugin, correct?

**Comment by strarsis** [comment]
@juliaamosova: Correct! This is very helpful for debugging and finding out accidental changes.

**Comment by astralbodies** [comment]
@strarsis Hiya! Just wanted to let you know that the app should be performing the actions on your site as the `wp-admin` user associated with the Jetpack connection (not the site's connection). Can you reach out to the support staff in the app under My Site -> Settings -> Help & Support?

You'll want to give them the two WordPress.com account e-mail addresses or usernames associated with the site that are being used.

**Comment by strarsis** [comment]
@astralbodies: Thank you for your answer.
So this means that currently there is no option in JetPack/WordPress.com to set the user that should perform the WooCommerce API actions on the site and that the JetPack support has to set one on demand? Is it planned to add such an user option to JetPack?

**Comment by astralbodies** [comment]
@strarsis Jetpack requires an administrator to make the first connection to WordPress.com. That account is like the site owner for the connection. If you have additional wp-admin users that wish to use the app, they can log into wp-admin and connect Jetpack to their own WordPress.com account. When they log into the Woo app with their WordPress.com credentials, then the actions performed through the app will be associated with their wp-admin account. 

Hope that helps!!

**Comment by strarsis** [comment]
@astralbodies: When I remove and re-add a JetPack account to another WordPress user, 
does the app owner have to re-authenticate with JetPack? I would like to avoid this.

**Comment by astralbodies** [comment]
I'm not entirely sure what the experience will be on the app side if you switch which wp-admin user is associated with a Jetpack/WordPress.com account. I believe the app shouldn't care much as long as there is a valid connection.

More about the Jetpack Primary User: https://jetpack.com/support/primary-user/

**Comment by juliaamosova** [comment]
@strarsis I am closing this issue as it looks like nothing for us to do on the WooCommerce Core side of things. Please feel free to comment in case I missed something and we will take another look.
