### ISSUE TITLE
Error coupon code

### ISSUE THREAD

**Issue by diesseweb** [woocommerce/woocommerce#25737]
Hi, i've a problem. I've created a coupon code (only for €99 cart). If the subtotal is less than 99€, the cart show this message: 

`**Per` utilizzare questo codice promozionale, la spesa minima è <span class="woocommerce-Price-amount amount"><span `class="woocommerce-Price-currencySymbol">€</span>99,00</span>.**`

How can i fix it? 
<img width="982" alt="Schermata 2020-02-23 alle 22 28 43" src="https://user-images.githubusercontent.com/61393617/75121752-5091bc00-5697-11ea-83ad-3e7c5d734cbc.png">

**Comment by tammullen** [comment]
Hi @diesseweb 

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/25699 
We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
