### ISSUE TITLE
Checkout process does not display error using wp_send_json_error("ERROR MESSAGE")

### ISSUE THREAD

**Issue by jobst** [woocommerce/woocommerce#25739]
**Describe the bug**
I am using a hook to add a function (plugin based) at the end of the order process:

`add_action('woocommerce_order_status_completed', array($this, 'process_orders_completed'), 1000,1);`

In that function I check all parameters and "do some stuff".
When there is a processing error I am using following code to return an error to the ajax call:

  `
   wp_send_json_error("ERROR MESSAGE");
   exit;
  `

While it stops the flow correctly the ERROR MESSAGE never arrives.
This is due to the fact that woocommerce/assets/js/frontend/checkout.js makes an incorrect assumption (line 510 of that file):

`if (result.messages) {
  wc_checkout_form.submit_error( result.messages ); 
 } else {
  wc_checkout_form.submit_error( '<div class="woocommerce-error">' + wc_checkout_params.i18n_checkout_error + '</div>' );
 }
`
If you use ANY of the WP based json function "result.messages" is NEVER set and it ALLWAYS display the default error message.

**To Reproduce**
1)write a plugin, any plugin
2)hook the plugins by means of hooks into the woocommerce checkout events
3)return an error using wp_send_json_error("ERROR MESSAGE");
4) it will ONLY display the default message

**Screenshots**
Not applicable

**Expected behavior**
When using a hooked function in the checkout phase I expect the error message to appear in the checkout pages, e.g. using 

`wp_send_json_error("ERROR MESSAGE");`

I expect the error message to appear.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by ObliviousHarmony** [comment]
Hello @jobst,

While it's true that the `woocommerce_order_status_{$status}` filter is fired by the checkout when marked as completed, it also fires any time an order's status is changed to `completed`. Given that, it isn't really ideal to try and submit an AJAX error response. If you instead throw an exception with your error message, it will be handled according to the needs of the calling location. In the admin backend for instance, this should give you an error notice; while in the frontend checkout, it should display the error message.

As an aside, the error you've encountered is the result of the malformed response. The client has a schema that it is expecting, which the server will respond with when not modified by any plugin such as this. If you'd like to keep your current implementation as-is, you'd need to change your error to follow [that response schema](https://github.com/woocommerce/woocommerce/blob/97456e7d7860d33d8362077e026de1d7866c41b4/includes/class-wc-checkout.php#L1053).

Hope that helps!
