### ISSUE TITLE
Strings to translate

### ISSUE THREAD

**Issue by melvinvita** [woocommerce/woocommerce#25740]
Hi, I can't translate the strings "Billing address, Shipping address" from emails or from checkout thank you page. I'm using the latest woocommerce version and loco translator.

I've tried editing the email-addresses.php template but still happens.

This doesn't happen in previous versions

**Comment by juliaamosova** [comment]
Hi @melvinvita,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. 

I am using WooCommerce 3.9.2 + Twenty Twenty theme + Loco Translate. 

I can find both `Billing address` and `Shipping address` strings and translate them:

![billing](https://user-images.githubusercontent.com/19143190/75183747-25e44980-5711-11ea-9d9a-244b5b9e428d.jpg)

![shipping](https://user-images.githubusercontent.com/19143190/75183759-2bda2a80-5711-11ea-8678-bc085c7bfe1d.jpg)

![thank](https://user-images.githubusercontent.com/19143190/75183775-33013880-5711-11ea-99b5-3181a6357e00.jpg)

![email](https://user-images.githubusercontent.com/19143190/75183790-38f71980-5711-11ea-85e7-7e5888eb243f.jpg)

Are you taking the same steps as I outlined? Are you searching for correct strings?

**Comment by melvinvita** [comment]
Hi @juliaamosova , 

Thank you so much for your reply.

I realiced that was "WooCommerce Checkout Field Editor" plugin that was messing with this lines. I had to translate the same strings on this plugin.
