### ISSUE TITLE
Notice: map_meta_cap was called incorrectly (WooCommerce de-activated)

### ISSUE THREAD

**Issue by bjornenio** [woocommerce/woocommerce#25744]
Clean install of the latest WooCommerce and WordPress. Activate WooCommerce. Turn wp_debug on in wp-config. De-Activate WooCommerce and the following message is shown in admin under Comments.

Notice: map_meta_cap was called incorrectly. The post type shop_order is not registered, so it may not be reliable to check the capability "edit_post" against a post of that type. Please see Debugging in WordPress for more information. (This message was added in version 4.4.0.) in /wp-includes/functions.php on line 4986

**Comment by juliaamosova** [comment]
Hi @bjornenio,

Thanks for taking the time to report the issue. While I can reproduce it, there is nothing we can do on our end on the WooCommerce side of things. There is an issue in WordPress core for which there is a ticket open:

https://core.trac.wordpress.org/ticket/49437
https://core.trac.wordpress.org/ticket/36208

I am closing this issue.

**Comment by mareqj** [comment]
I just found these errors on a site where I am looking for a possible cause of failed shop orders. Is there any chance that this could cause such thing?
