### ISSUE TITLE
wc_get_shipping_method_count() doesn't check if shipping methods are enabled

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce#25752]
Relevant source code:

https://github.com/woocommerce/woocommerce/blob/master/includes/wc-core-functions.php#L1475-L1515

Documentation for `wc_get_shipping_method_count()` says it counts `shipping methods currently enabled`, but when it runs the SQL query, it doesn't check whether the shipping methods are enabled:

```SQL
SELECT COUNT(*) FROM {$wpdb->prefix}woocommerce_shipping_zone_methods
```

I could see this issue while working on the _Checkout_ block because I have this shipping method in my database:
![imatge](https://user-images.githubusercontent.com/3616980/75254033-fc462380-57df-11ea-8522-0b4dc2764a29.png)

which is counted by `wc_get_shipping_method_count()` even though it's disabled.

**Comment by juliaamosova** [comment]
Thanks for reporting the issue and submitting a fix for it @Aljullu!
