### ISSUE TITLE
Webhooks - Add useful data

### ISSUE THREAD

**Issue by bhubbard** [woocommerce/woocommerce#25763]
I think for all the webhooks, should have some extra data in the payload, such as the action name.

**Comment by juliaamosova** [comment]
Hi @bhubbard,

Thanks for your suggestion. However, it is possible that adding more data to the payload could be considered a breaking change, given that it alters the response. 

To achieve what you are looking for, you can add query parameters to the delivery URL. That way you could manually add an identifier for the calling event. 

I am closing this issue for now. Please feel free to comment on it in case we missed something. We’d be happy to take another look.
