### ISSUE TITLE
Billing address 2 label: double “optional” string.

### ISSUE THREAD

**Issue by Adrian-S** [woocommerce/woocommerce#25768]
Had the same problem as this: https://wordpress.org/support/topic/billing-address-2-label-double-optional-string/

The function `get_default_address_fields()` in `includes/class-wc-countries.php` has some useless code. It starts with an IF and that can be removed and only ELSE case used.

Further more `esc_attr( $address_2_placeholder )` from here:
```
'address_2'  => array(
	'placeholder'  => esc_attr( $address_2_placeholder ),
	'class'        => array( 'form-row-wide', 'address-field' ),
	'autocomplete' => 'address-line2',
	'priority'     => 60,
	'required'     => 'required' === get_option( 'woocommerce_checkout_address_2_field', 'optional' ),
)
```
can be repalced with `__( 'Apartment, suite, unit etc.', 'woocommerce' )` like this:
```
'address_2'  => array(
	'placeholder'  => __( 'Apartment, suite, unit etc.', 'woocommerce' ),
	'class'        => array( 'form-row-wide', 'address-field' ),
	'autocomplete' => 'address-line2',
	'priority'     => 60,
	'required'     => 'required' === get_option( 'woocommerce_checkout_address_2_field', 'optional' ),
)
```

My installed version is 3.9.2, but I see that the file was last updated in version 3.3.0 and found similar issues with approved changes, that never made it the production:
https://github.com/woocommerce/woocommerce/pull/21186
https://github.com/woocommerce/woocommerce/pull/20622

Also 'woocommerce_checkout_address_2_field' option seems to be depreciated or something and not in the settings UI.

My fix for now, if anyone needs it:
```
add_filter( 'woocommerce_default_address_fields', 'fix_address_2_placeholder' );
function fix_address_2_placeholder($fields) {

	if(!empty($fields['address_2'])) {
		$fields['address_2']['placeholder'] = __( 'Apartment, suite, unit etc.', 'woocommerce' );
	}

	return $fields;
}
```

Thanks.

**Comment by juliaamosova** [comment]
Hi @Adrian-S,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/25510. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
