### ISSUE TITLE
Usage Limit per User Doesn't Prevent Logged Out User from Using Coupon Again

### ISSUE THREAD

**Issue by DynAggelos** [woocommerce/woocommerce#25769]
**Describe the bug**
The "Usage limit per user" coupon restriction can be by-passed by using the coupon while logged in, and then later using the coupon again while logged out. This is because, as the field hint says when setting the limitation, it considers the user's user ID when they are logged in (ignoring their billing email address), but their billing email address when logged out.

**To Reproduce**

1. Create an order for yourself, add a product, apply a coupon with the "Usage limit per user" limitation set to 1, and set the order to "Processing".
2. Go to the storefront while logged in, add the same product to your cart, and try to use the same coupon. You will see you can't, because your account has already used it once.
3. Open up a private browser (or log out of your account), add the same product to your cart, enter your account's billing information into the checkout page, and then try to use the same coupon. It will work. (Note: it will also work if you apply the coupon, and then enter your account's billing information, which is also a problem.)

**Screenshots**
![Capture1](https://user-images.githubusercontent.com/35944457/75376257-5e149500-5895-11ea-9582-4058235c47f0.JPG)
First coupon use: logged in.

![Capture2](https://user-images.githubusercontent.com/35944457/75376264-610f8580-5895-11ea-89d1-eee0d5dd7541.JPG)
Second coupon use: logged out, but using the same billing address, including email.

**Expected behavior**
When a user is logged out it should verify that their billing email address has not already used the coupon up to the limit. When a user is logged in it should check both the billing email address and their user ID to make sure the combined use of these two (making sure not to count orders twice where the billing email address and the user ID were both used for the same order) does not reach the coupon usage limit.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @DynAggelos,

Thank you for submitting the issue. 

I can place 1st order while logged in with my usage restriction coupon `test-user` - works as expected:

![c1](https://user-images.githubusercontent.com/19143190/75380093-6de7a580-58a4-11ea-9ab7-f3da6ab67468.jpg)

If I try to use the coupon again while being logged in as the same user - I am getting an error message letting me know that I can't use the coupon again - works as expected:

![c2](https://user-images.githubusercontent.com/19143190/75380173-8ce63780-58a4-11ea-9fde-4ff4e0397acf.jpg)

In incognito mode or logged out, I can first apply the coupon again. After entering my billing email address (which is the same as when I placed the 1st order), the coupon remains there. But if I actually click on placing the order, I am getting the error message letting me know that I can't use the coupon - works as expected:

![c3](https://user-images.githubusercontent.com/19143190/75380290-c028c680-58a4-11ea-8f33-fcfa11ffb336.jpg)

It looks like in your test, you actually didn't place an order to see the error message. We do the verification on the placing order step. Can you please confirm it works for you that way?

**Comment by DynAggelos** [comment]
I see! That's right. Sorry for reporting a false bug.
