### ISSUE TITLE
Grouped products don't show from - to price

### ISSUE THREAD

**Issue by Jeroenleender** [woocommerce/woocommerce#25774]
**Describe the bug**
New site completely updated, imported products using wp all import. Grouped products have related products added to them which are visible in the back-end. all related products have prices. From - To prices are not shown in either front-end or back-end. When u rearrange the related product order inside the grouped product and then save the grouped product. The prices show up on front-end and back-end

**To Reproduce**
1. 'Import related products and attach them to their parent using wp all import'

**Screenshots**
i made a video that shows the exact issue.
[video](https://test013.smoldersbv.nl/related_product_price_issue.mkv)

**Expected behavior**
That woocommerce would show From - To price on front-end and back-end since all values that are visible in the backend are correct.

**Isolating the problem (mark completed items with an [x]):**
- [ X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ X ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ X ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
latest as of 27-2-2020
```

```
</details>

**Comment by juliaamosova** [comment]
Hi @Jeroenleender,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/25706. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
