### ISSUE TITLE
How to check coupon code valid or not?

### ISSUE THREAD

**Issue by Lalitchaudhary2** [woocommerce/woocommerce#25773]
I developed one e-commerce app using woocommerce rest-API. now I need to add coupons codes feature in-app. I know how to pass coupon code in creating order, but how to check this code is valid or not before creating an order?

**Comment by juliaamosova** [comment]
Hi @Lalitchaudhary2,

You should be able to use [`is_valid()` function](https://docs.woocommerce.com/wc-apidocs/source-class-WC_Coupon.html#830). 

Please note that GitHub should be treated as a place to report bugs - it is not a support portal. As much as we'd like to help, we don't have resources to do so. I am closing this issue. Thank you for understanding!
