### ISSUE TITLE
Existing Setup Wizard footer references guided tour Videos

### ISSUE THREAD

**Issue by tammullen** [woocommerce/woocommerce#25781]
**Describe the bug**
On the final step of the setup wizard there is a link in the footer to the currently offline guided tour videos (the link re-directs to documentation).

**To Reproduce**
1. Go to the final step of the existing setup wizard 
(if you are getting the new onboarding wizard you can disable it from the help menu in WooCommerce / Settings / Help)
![Screenshot_2020-02-28_at_00_49_04](https://user-images.githubusercontent.com/24649833/75500257-54d61600-59c4-11ea-94d9-7d912b0127ca.png)
2. Scroll down to the footer of the page.
4. See link to guided tour videos.
![screencapture-conscious-crested-jurassic-ninja-wp-admin-admin-php-2020-02-16-18_31_54](https://user-images.githubusercontent.com/24649833/75500291-6cad9a00-59c4-11ea-8537-907166af97a3.png)

**Expected behavior**
No link to the videos until such time they are back online.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

The code is here 
https://github.com/woocommerce/woocommerce/blob/4271eb94d721a0816dc1991fdcd213a2d1ed840b/includes/admin/class-wc-admin-setup-wizard.php#L2469

**Comment by michaelignacio** [comment]
I'd like to take this on - do I just push on the master branch or do I have to create a new branch for this fix? Somehow I can't find the answer for this on the contributing guidelines.
