### ISSUE TITLE
[4.0 RC1] Paid by customer should reflect the amount paid by customer

### ISSUE THREAD

**Issue by AashikP** [woocommerce/woocommerce#25788]
**Is your feature request related to a problem? Please describe.**

WooCommerce 4.0 has a new section in the order details page for the amount `Paid by customer`. As of now, it reflects the order total, even after partially refunding the order:

![https://d.pr/i/NMS6Md+](https://d.pr/i/NMS6Md+)
*If the image does not load, please click this link: https://d.pr/i/NMS6Md*

While the net total does display the actual amount collected in the order, `Paid by customer` does not change. 

**Describe the solution you'd like**

`Paid by customer` should reflect the actual amount paid by the customer.

**Describe alternatives you've considered**

Perhaps clarify that it is the original amount paid by the customer, and net total describes the actual amount collected in the order?

**Additional context**

N/A

**Comment by peterfabian** [comment]
cc @LevinMedia

**Comment by LevinMedia** [comment]
Heya @AashikP ! Thanks for the feedback!

>Perhaps clarify that it is the original amount paid by the customer, and net total describes the actual amount collected in the order?

We've been running usability tests the last few weeks that include these details and UX specifically - thus far it hasn't caught anyone off guard or created un-due confusion. Additionally, this UX is also included in the mobile app, and to my knowledge they haven't had an reports on it either cc @astralbodies 

One small difference in the mobile app UX, which I think we should add here, is including the date paid and the payment method, directly under "Paid by Customer". 

**Mobile example:**

![IMG_986F37C24CD1-1](https://user-images.githubusercontent.com/4500952/75909926-d9c89180-5e01-11ea-9cac-cb3f34f79218.jpeg)

Given the positive results of the usability testing, I think we could defer that till after the 4.0 release , unless @peterfabian thinks it's minor enough to address now.

**Comment by AashikP** [comment]
@LevinMedia 

Thank you for the additional details.

> One small difference in the mobile app UX, which I think we should add here, is including the date paid and the payment method, directly under "Paid by Customer".

That would indeed make things a lot more clear. 

> Given the positive results of the usability testing, I think we could defer that till after the 4.0 release 

Sounds like a plan!

**Comment by peterfabian** [comment]
Yup, we can refine it later if needed. A bit late for 4.0 now.

**Comment by galbaras** [comment]
Besides the UX point, to which I agree, showing correct amounts seems to be a rather basic requirement for a shopping cart system, so perhaps the numbers can be fixed quickly, and the UX changed later?
