### ISSUE TITLE
Checkout notice actions issue

### ISSUE THREAD

**Issue by Erehr** [woocommerce/woocommerce#25782]
I wanted to move my error notices (and get rid .woocommerce-NoticeGroup wrapper) on checkout pages. 

For checkout fields (name, email etc.) there's no issue, I can make script to trigger on 'updated_checkout'  and delete old notice and append new in different place. But I noticed that it's not applied to error for terms checkbox with is triggered later ('checkout_error') and doesn't pass any arguments (notice content) with it.

checkout.js
`418 $( document.body ).trigger( 'updated_checkout', [ data ] );`
`565 $( document.body ).trigger( 'checkout_error' );`

So for a fix I would like the second trigger to pass notice content with it like the data.message with first one. 

`$( document.body ).trigger( 'checkout_error', [ error_message ] );`

**Comment by vedanshujain** [comment]
I think it makes sense to add error message to `checkout_error` as you suggest. Would you be open to sending a PR to patch it, because looks like you already know what and where to apply the fix?

**Comment by dominic-ks** [comment]
@vedanshujain I'll look at putting in a PR for this unless @Erehr has already done this work?

**Comment by vedanshujain** [comment]
@dominic-ks please free to send in a PR.

**Comment by dominic-ks** [comment]
@vedanshujain cool, just submitted this - https://github.com/woocommerce/woocommerce/pull/28101
