### ISSUE TITLE
Stock reduction with Stripe Radar puts the order in review

### ISSUE THREAD

**Issue by anant1811** [woocommerce/woocommerce#25806]
We had a user reach out with the following request:

>Hello I have noticed an issue with the Stripe plugin. If an order is put in review by stripes “Radar” payment protection it goes to hold status in WC. However, when we move the order to “processing” it amends the stock a second time! Is this a bug?

This makes sense since the stock is reduced for both the On-Hold status and the Processing status: https://docs.woocommerce.com/document/managing-orders/
I guess I’m not sure if this should happen when Stripe initiates this since the user has to place this in Processing mode after review, and it removes the stock twice. 

Any thoughts on how to trigger a fraud rating? And Test Mode should pass anything, so I’m not sure how to go about replicating this to see if the stock levels are reduced twice, as the user describes. Any feedback would be appreciated!

**Comment by anant1811** [comment]
This was reported in 2751709-zen. 

The user came back with additional info:

>some additional info on this issue, I had 3 orders put on hold by Stripe's Radar this morning and I notice only one of them has the stock issue. I can see from the notes that the one that had the issue first went to processing then to hold, whereas the two that did not have the issue went straight to hold.

>So, it is clearly when the payment goes from pending >> processing >> hold all at once that causes the issue. I am afraid I cannot see anything that might indicate why this would happen on some orders and not others. Maybe it is something happening on Stripe that is different?

I think this is something we should be checking with Stripe as well, I reached out to the user for more details including screenshots.

**Comment by stuartduff** [comment]
I've carried out some comparison testing with Stripe and updated 2751709-zen

**Comment by tammullen** [comment]
Closing as a part of this repository’s maintenance as looks like there isn't a bug here.
