### ISSUE TITLE
[4.0-rc] Database upgrade does not complete

### ISSUE THREAD

**Issue by gbruzzo** [woocommerce/woocommerce#25809]
**Describe the bug**
Problems updating to 4.0-rc.1 : Database update hangs / does not complete

**To Reproduce**

update from 3.9.2 with Woocommerce Admin plugin 
after 4.0-rc1 is installed, message asks for database update
update goes on forever (days)

I have since reinstalled the staging environment and have restarted the database update

**Screenshots**
<img width="1116" alt="Screenshot 2020-03-03 at 15 41 39" src="https://user-images.githubusercontent.com/16798202/75792311-ad5f3780-5d65-11ea-90a0-91e8210a1632.png">

**Expected behavior**

database should have updated after a couple of days 

**Isolating the problem (mark completed items with an [x]):**

**WordPress Environment**
`
### WordPress Environment ###

WordPress address (URL): https://www.staging.rarenoiserecords.com
Site address (URL): https://www.staging.rarenoiserecords.com
WC Version: 4.0.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.13
Action Scheduler Version: ✔ 3.1.1
WC Admin Version: ✔ 0.26.1
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.29 (Unix) mod_hive/6.27 OpenSSL/1.0.1e-fips mod_fastcgi/2.4.6
PHP Version: 7.3.15
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.59.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.6.36-82.1-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.2
WC Database Prefix: wprn_
Total Database Size: 155.18MB
Database Data Size: 89.08MB
Database Index Size: 66.10MB
wprn_woocommerce_sessions: Data: 0.17MB + Index: 0.02MB + Engine InnoDB
wprn_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wprn_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wprn_woocommerce_downloadable_product_permissions: Data: 2.52MB + Index: 3.78MB + Engine InnoDB
wprn_woocommerce_order_items: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wprn_woocommerce_order_itemmeta: Data: 11.52MB + Index: 10.03MB + Engine InnoDB
wprn_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wprn_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wprn_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wprn_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wprn_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wprn_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wprn_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wprn_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wprn_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wprn_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wprn_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wprn_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wprn_apto_sort_list: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wprn_aryo_activity_log: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wprn_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wprn_comments: Data: 6.52MB + Index: 9.09MB + Engine InnoDB
wprn_dae_links: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wprn_dae_subscribermeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wprn_dae_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wprn_ed_downloadform: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wprn_ed_emaillist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wprn_ed_filter: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wprn_ed_pluginconfig: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wprn_eo_wbc_cat_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wprn_eo_wbc_order_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wprn_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wprn_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wprn_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wprn_map_media: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wprn_map_players: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wprn_map_playlists: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wprn_map_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wprn_map_statistics: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wprn_options: Data: 11.27MB + Index: 0.23MB + Engine InnoDB
wprn_postmeta: Data: 28.56MB + Index: 21.08MB + Engine InnoDB
wprn_posts: Data: 5.52MB + Index: 2.55MB + Engine InnoDB
wprn_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wprn_rank_math_404_logs: Data: 0.09MB + Index: 0.02MB + Engine InnoDB
wprn_rank_math_internal_links: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
wprn_rank_math_internal_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wprn_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wprn_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wprn_rank_math_sc_analytics: Data: 6.52MB + Index: 3.52MB + Engine InnoDB
wprn_realmedialibrary: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wprn_realmedialibrary_debug: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wprn_realmedialibrary_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wprn_realmedialibrary_order: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wprn_realmedialibrary_posts: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wprn_relevanssi: Data: 2.52MB + Index: 6.06MB + Engine InnoDB
wprn_relevanssi_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wprn_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wprn_say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wprn_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wprn_terms: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wprn_term_relationships: Data: 0.42MB + Index: 0.23MB + Engine InnoDB
wprn_term_taxonomy: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wprn_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wprn_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wprn_usermeta: Data: 5.52MB + Index: 6.03MB + Engine InnoDB
wprn_users: Data: 0.47MB + Index: 0.36MB + Engine InnoDB
wprn_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wprn_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wprn_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wprn_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wprn_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wprn_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wprn_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wprn_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wprn_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wprn_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wprn_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wprn_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wprn_widgetkit: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
wprn_woocommerce_bolt_checkout_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wprn_woocommerce_exported_csv_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wprn_wpml_mails: Data: 1.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 44
acf-field-group: 11
ai_playlist: 1
anr-post: 1
artists: 65
attachment: 764
custom_css: 3
dae_download: 1
nav_menu_item: 100
oembed_cache: 9
page: 15
post: 181
product: 105
product_variation: 456
revision: 2
scheduled-action: 3908
shop_coupon: 3
shop_order: 5841
wp_events: 4
wpbf_hooks: 14
wpea_import_history: 25
xt_scheduled_imports: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (41) ###

XT WooCommerce Floating Cart Pro: by XplodedThemes – 1.5.2.2 – Not tested with the active version of WooCommerce
Admin Menu Editor: by Janis Elsts – 1.9.3
Advanced Custom Fields PRO: by Elliot Condon – 5.8.7
Advanced noCaptcha & invisible Captcha: by Shamim Hasan – 5.6 – Not tested with the active version of WooCommerce
Angell EYE Updater: by Angell EYE – 2.0.8
Modern Audio Player: by Tean – 3.1
Activity Log: by Activity Log Team – 2.5.2
Change Quantity on Checkout for WooCommerce: by Bhavik Kiri – 1.0 – Not tested with the active version of WooCommerce
Cookie Notice: by dFactory – 1.2.50
Custom Post Type UI: by WebDevStudios – 1.7.3
DHWC Ajax: by Sitesao team – 1.1.19 – Not tested with the active version of WooCommerce
Disable Comments: by Samir Shah – 1.10.2
Email download link: by Gopi Ramasamy – 2.7
Envato Market: by Envato – 2.0.3
Flexible Shipping: by WP Desk – 3.9.9 – Not tested with the active version of WooCommerce
PayPal for WooCommerce: by Angell EYE – 2.1.14 – Not tested with the active version of WooCommerce
Post Types Order: by Nsp Code – 1.9.4.2
Youtube Playlist Video Player: by Rik de Vos – 1.11.0
WP Real Media Library: by devowl.io GmbH – 4.7.2
Lazy Load - Optimize Images: by WP Rocket – 2.3.2
Say What?: by Lee Willis – 1.9.3
Rank Math SEO: by Rank Math – 1.0.39.1
Server IP & Memory Usage Display: by Apasionados
Apasionados del Marketing – 2.1.0

WooCommerce Show Single Variations by Iconic: by Iconic – 1.1.17-dev – Not tested with the active version of WooCommerce
Unlist Posts & Pages: by Nikhil Chavan – 1.0.4
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.16.22.1

Widgetkit: by YOOtheme – 2.9.23
WooCommerce Admin: by WooCommerce – 0.26.1 – Not tested with the active version of WooCommerce
WooCommerce Beta Tester: by WooCommerce – 2.0.1 – Not tested with the active version of WooCommerce
WooCommerce Chained Products: by StoreApps – 2.9.5 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.17 – Not tested with the active version of WooCommerce
WooCommerce Sequential Order Numbers: by SkyVerge – 1.9.3 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 4.0.0-rc.1
WP Event Aggregator Pro: by Xylus Themes – 1.5.6
WP Event Aggregator: by Xylus Themes – 1.5.11
WP Fastest Cache Premium: by Emre Vona – 1.5.7
WP Fastest Cache: by Emre Vona – 0.9.0.3
WP Mail SMTP: by WPForms – 1.8.1
Page Builder Framework Premium Addon: by David Vongries – 2.1.6
XT WooCommerce Quick View Pro: by XplodedThemes – 1.4.3.4 – Not tested with the active version of WooCommerce
YITH Amazon S3 Storage for WooCommerce Premium: by YITH – 1.1.10

### Inactive Plugins (3) ###

Customizer Reset - Export & Import: by David Vongries – 1.1.1
Duplicate Post: by Enrico Battocchi – 3.2.4
Meks Quick Plugin Disabler: by Meks – 1.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix-and-match (mix-and-match)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-filtered (exclude-from-filtered)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #8 - /releases/
Cart: #9 - /checkout-1/
Checkout: #10 - /checkout-2/
My account: #11 - /my-account/
Terms and conditions: #6633 - /terms-and-conditions/

### Theme ###

Name: RareNoise Theme
Version: 1.0.0
Author URL: https://www.rarenoiserecords.com
Child Theme: ✔
Parent Theme Name: Page Builder Framework
Parent Theme Version: 2.1.4.4 – 2.2 is available
Parent Theme Author URL: https://mapsteps.com
WooCommerce Support: ✔

### Templates ###

Overrides: rarenoise/woocommerce/single-product/meta.php
rarenoise/woocommerce/single-product/title.php

### Action Scheduler ###

Complete: 3,950
Oldest: 2020-02-01 17:05:33 +0000
Newest: 2020-03-02 10:28:41 +0000

Pending: 7
Oldest: 2020-03-03 15:19:38 +0000
Newest: 2020-03-07 17:08:26 +0000

Canceled: 1
Oldest: 2020-03-02 11:28:41 +0000
Newest: 2020-03-02 11:28:41 +0000

</details>

**Comment by peterfabian** [comment]
Hi @gbruzzo, 

Thanks for reporting! 
Have you tried to run the actions manually? When you place your mouse cursor over the pending action, a `Run` link should appear on each of the rows.

I see you have quite a few completed scheduled actions, can you please check if those are not stuck in some infinite loop (i.e. if these aren't the same actions getting scheduled over and over again)?

**Comment by gbruzzo** [comment]
Hi there

I did try running them manually, it seems though to no effect. 

The completed actions are all seem to be actually completed.

hundreds of 

wc-admin_delete_batch_customers, 
wc-admin_delete_batch_orders, 
wc-admin_import_batch_orders, 
wc-admin_import_batch_customers, all though with different arguments.
wc_admin_unsnooze_admin_notes
(and more)

They do not seem to be stuck in a loop (what are tell-tale signs of this? What should I be looking for?) 

Giacomo

**Comment by gbruzzo** [comment]
Hello there 

after 22 hours the database upgrade is still not complete. 

I will revert our staging to 3.9.2 and wait until all our plugins are 4.0 compatible. 

Meanwhile please let me know if anything comes to mind.

**Comment by peterfabian** [comment]
I can see the latest completed action from the system status shows timestamp `2020-03-02 10:28:41 +0000`. Do you know if that's before you started the upgrade? 

I'm trying to find out if any actions have actually completed with the new WC4 and new Action Scheduler, or if all those completed ones have been completed while running with WC 3.9.x.

**Comment by peterfabian** [comment]
> They do not seem to be stuck in a loop (what are tell-tale signs of this? What should I be looking for?)

I think if they have different arguments, as you correctly noticed, then those are regular WC Admin actions and nothing is stuck in a loop.

**Comment by peterfabian** [comment]
Can you please try to disable other plugins just to make sure there isn't a plugin conflict causing this problem? 

Would you be able to check the error logs (PHP error log and WC logs) if there is anything preventing the actions from running?

**Comment by gbruzzo** [comment]
Hi there, the last completed actions are pre-update.

will try rolling back to 3.9.3, disabling all plugins then restarting the update 

Giacomo

**Comment by gbruzzo** [comment]
Hello there 

Tried disabling all plugins, keeping only Woocommerce and Woocommerce Beta Tester
4.0RC1 - **managed to get the database to update in 3 out of 5 attempts** (I reinstalled the staging site every time). Hanging = hanging for at least half a day. Manual attempts to start scheduled processes were unsuccessful. In one case one plugin generated an error 

```
WordPress database error: [Table 'DBName.DBPrefix_wc_admin_notes' doesn't exist]
SELECT note_id FROM DBPrefix_wc_admin_notes WHERE name = 'wc-update-db-reminder' ORDER BY note_id ASC
```
I tried to reproduce the error (delete staging/reinstall staging, upgrade again), but unsuccessfully.

4.0RC2 - **managed to get the database to update in 4 out of 5 attempts.** (I reinstalled the staging site every time). Hanging = hanging for at least half a day. Manual attempts to start scheduled processes were unsuccessful.

4.0 stable - disabled Beta Tester and installed with full complement of plugins, but database update was hanging. Next test was to disable all plugins but for Woocommerce and attempt upgrade to 4.0 : database update was again hanging for at least half a day.

Finally I reinstalled the staging environment for the third time, disabled all plugins but for Woocommerce and reinstalled Beta Tester. Attempted update to 4.0 stable via Beta Tester, **and this time the database managed to complete** (very quicky, as a matter of fact). 

Checked all the php logs, cannot find errors associated with the upgrade. 

As you may imagine I am wholly confused, and would appreciate suggestions. Not sure I would risk upgrading our main site 

Giacomo Bruzzo

**Comment by peterfabian** [comment]
Thanks for reporting back and apologies for the trouble. 

One thing that might help: there was a bug with ActionScheduler screen in WooCommerce > Status, so the actions _should_ run if you trigger them instead from WP menu Tools > Scheduled Actions. That way you should be able to finish the db upgrade (or any other action that seems stuck). We're [working on a fix for this already](https://github.com/woocommerce/action-scheduler/issues/485).

As for why the jobs are not processed automatically, it's something that @rrennick can maybe provide a better explanation for, but in general, there are 2 job runners included with ActionScheduler 3 (AS) now:
- one is triggered by WP cron, 
- the other by async requests when browsing WP admin. 

Some hosts (such as Pressable) temporarily disabled running the jobs automatically as they wanted to closely inspect how the new AS would behave, so it could be sometimes difficult to tell why the jobs are not getting processed, but generally speaking, if you can check that cron is running and you haven't disabled the async processing, the jobs _should_ run. 

Can you maybe share which hosting provider do you use so we can try to test using a similar environment?

**Comment by gbruzzo** [comment]
Hi @peterfabian 

we use Siteground VPS (2CPU/4GB) so quite solid. 

Staging site is setup via Softaculous 

Let me delete the staging site reinstall and try your suggestions.

Will revert as soon as done.

**Comment by gbruzzo** [comment]
Hi @peterfabian 

New staging site, new upgrade to WC 4.0 via regular plugin upgrade (plugins page). 

Update successful, did not require any nudge (I was observing the actions being triggered from Tools -> Scheduled Actions)

Glad, but confused.

**Comment by peterfabian** [comment]
I'll close this issue now. Please feel free to comment here or create a new issue if you find steps to reproduce any problem. Thanks.
