### ISSUE TITLE
Woocommerce dashboard not working

### ISSUE THREAD

**Issue by Whiteheadcarpentry** [woocommerce/woocommerce#25805]
**Describe the bug**
The dashboard display is blank, the grpahs display for a second then everything dissappears

**To Reproduce**
1. Go to 'woocommerce'
2. Click on 'dashboard'
3. See error

**Screenshots**

![Screen Shot 2020-03-03 at 08 44 55](https://user-images.githubusercontent.com/61731098/75758418-001bfd80-5d2c-11ea-8a26-51d2afdc4a58.png)

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
From my hosting " Thank you for your patience, Thomas.

I have carefully reviewed your case, but unfortunately, I was unable to resolve it.

As there are no errors presented on the server, I had to manually check what is causing the issue. I have tested your website with different themes, to check if the theme is conflicting with your plugin however it seems that the issue appears on all themes. After that, I have turned off all of your plugins except for woocommerce and woocommerce-admin, however, the Dashboard still does not work and the following errors appear in the browser's Developers console:

react-dom.min.js?ver=16.9.0:103 TypeError: Cannot read property &#039;setProperty&#039; of undefined
    at Element.&lt;anonymous&gt; (index.js?ver=0.26.1:34)
    at Ja.each (index.js?ver=0.26.1:34)
    at Ja.style (index.js?ver=0.26.1:34)
    at Mc (index.js?ver=0.26.1:34)
    at t.value (index.js?ver=0.26.1:34)
    at t.value (index.js?ver=0.26.1:34)
    at t.value (index.js?ver=0.26.1:34)
    at Ti (react-dom.min.js?ver=16.9.0:148)
    at unstable_runWithPriority (react.min.js?ver=16.9.0:26)
    at Ma (react-dom.min.js?ver=16.9.0:52)
ve @ react-dom.min.js?ver=16.9.0:103

index.js?ver=0.26.1:34 Uncaught (in promise) TypeError: Cannot read property &#039;setProperty&#039; of undefined
    at Element.&lt;anonymous&gt; (index.js?ver=0.26.1:34)
    at Ja.each (index.js?ver=0.26.1:34)
    at Ja.style (index.js?ver=0.26.1:34)
    at Mc (index.js?ver=0.26.1:34)
    at t.value (index.js?ver=0.26.1:34)
    at t.value (index.js?ver=0.26.1:34)
    at t.value (index.js?ver=0.26.1:34)
    at Ti (react-dom.min.js?ver=16.9.0:148)
    at unstable_runWithPriority (react.min.js?ver=16.9.0:26)
    at Ma (react-dom.min.js?ver=16.9.0:52)

* All of the mentioned changes are reverted

I will advise you to contact the plugin's developers so they can further investigate and provide you with more information."

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://whiteheadcarpentry.com
Site address (URL): https://whiteheadcarpentry.com
WC Version: 3.9.2
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.1.33 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1d-fips

SUHOSIN Installed: –
MySQL Version: 5.7.25-28-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.2
WC Database Prefix: wp_
Total Database Size: 11.18MB
Database Data Size: 9.86MB
Database Index Size: 1.32MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 5.02MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 3.45MB + Index: 0.06MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sbi_instagram_posts: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 11
fusion_template: 1
nav_menu_item: 4
page: 9
post: 1
product: 1
revision: 93
scheduled-action: 100
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (15) ###

Contact Form 7: by Takayuki Miyoshi – 5.1.6
Fusion Builder: by ThemeFusion – 2.2.1
Fusion Core: by ThemeFusion – 4.2.1
Insert Headers and Footers: by WPBeginner – 1.4.5
Smash Balloon Instagram Feed: by Smash Balloon – 2.2
Jetpack by WordPress.com: by Automattic – 8.2.1
Slider Revolution: by ThemePunch – 6.1.8
SG Optimizer: by SiteGround – 5.4.4
WooCommerce Admin: by WooCommerce – 0.26.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.20
WooCommerce Stripe Gateway: by WooCommerce – 4.3.2
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.32
WooCommerce: by Automattic – 3.9.2
Yoast SEO: by Team Yoast – 13.2
WordPress Starter: by SiteGround – 1.0.8

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #27 - /shop/
Cart: #90 - /cart/
Checkout: #91 - /checkout/
My account: #92 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Avada
Version: 6.2.1
Author URL: http://themeforest.net/user/ThemeFusion
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php
Avada/woocommerce/checkout/thankyou.php
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

### Action Scheduler ###

Complete: 99
Oldest: 2020-02-20 14:37:04 +0000
Newest: 2020-03-02 21:13:32 +0000

Pending: 0
Oldest: –
Newest: –

Canceled: 1
Oldest: 2020-03-02 22:13:32 +0000
Newest: 2020-03-02 22:13:32 +0000

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`
</details>

**Comment by johndcoy** [comment]
This is likely a problem with the site in question and not core. I cannot replicate with only WooCommerce and Twenty Twenty theme active.

Post your question on the forums if you still have troubles after conflict testing the theme and all other plugins.

https://docs.woocommerce.com/document/woocommerce-self-service-guide/#section-4

If this fixes the issue, then re-enable each plugin one at a time, then the theme, until you find the one that's causing the conflict.

**Comment by kathy330** [comment]
I got the same issue. When I update Woocommerce to 5.1.0 the dashboard and analytics are blank.
Console Error
Unchecked runtime.lastError: The message port closed before a response was received.
2react-dom.min.js:125 TypeError: Cannot read property 'call' of undefined
    at a (index.js:1)
Me @ react-dom.min.js:125
react.min.js:24 Uncaught TypeError: Cannot read property 'call' of undefined
    at a (index.js:1)


Also for the 5.0 version, when I click on "Set product image" under the product setting.
it redirects me to the following page.
![Screen Shot 2021-03-10 at 12 18 57 pm](https://user-images.githubusercontent.com/39319724/110560885-d8f7d780-819a-11eb-8478-4d0cc53161d3.png)

and the short description is not working in the product setting as well.
![Screen Shot 2021-03-10 at 12 21 54 pm](https://user-images.githubusercontent.com/39319724/110561122-40158c00-819b-11eb-8c6b-70da9004bda7.png)

I am so frustrated with the 5.0 version. The 5.0 version is not compatible well with WordPress 5.6 update.

**Comment by offminded** [comment]
I had the same issue. Woocommerce dashboard was blank and console had the same react error. The following fixed the issue for me:
- Update wordpress to latest version (5.7)
- Disable and re-enable the woocommerce plugin
