### ISSUE TITLE
Persistent Cart does not use unique meta data key.

### ISSUE THREAD

**Issue by JohnChandlerEdmonton** [woocommerce/woocommerce#25821]
The persistent cart is stored as a record in the user_meta table with key
         _woocommerce_persistent_cart_" .  get_current_blog_id()

But this is not a unique identifier when a shared user table is being employed.

This is a request to change it to use this instead:
"_woocommerce_persistent_cart_" . $table_prefix
or whatever you think would be appropriate.

----------------------------------------------------------
To illustrate. Suppose there are two websites, each with its own woocommerce store.

www.dogs.com/main
www.dogs.com/specialevent

The table prefix for the first site is "main". 
The table prefix for the second one is "specialevent"

The second site does not use its own user tables. Instead it is set to share the first one's with the following in its wp config.

define( 'CUSTOM_USER_TABLE', 'main_users' ); 
define( 'CUSTOM_USER_META_TABLE', 'main_usermeta' );

However, the command
get_current_blog_id()
always returns "1" no matter what site you visit.

It is not a unique identifier.

Consequently when a user goes to one site and creates a persistent cart it will overwrite whatever persistent cart existed in the other site by overwriting the user meta data with key 
         _woocommerce_persistent_cart_1

Using the $table_prefix instead of "get_current_blog_id()" would be a possible way to go. This is the way wordpress does the "capabilities" user_meta data for example.    For each user, each site has its own user meta record as follows:
- main_capabilities 
- specialevent_capabilities

P.S. Where this can be a problem is if you are trying to keep track of stock by causing the items ordered to be reserved in some way when added to cart and unreserved when removed from the cart. When the cart gets over-written, such reservations will not be removed correctly.

More info about shared user table: 
https://kinsta.com/blog/share-logins-wordpress/

**Comment by vedanshujain** [comment]
`get_current_blog_id` function should actually return different values based on the blog you are in. I tested by creating a multisite network with just WooCommerce install, and cart sessions for different sites were persisted even while using the same user table.

Are you able to reproduce this issue only when WooCommerce is activated as well? I would also suggest making sure that there is no weird thing going on which might interfere with the output of  `get_current_blog_id`. 

I am closing this issue, but feel free to comment back and we will re-open if this needs further discussion (or open another issue with steps to reproduce).

**Comment by JohnChandlerEdmonton** [comment]
Thanks for getting back to me. 

 

I am looking into multi-site.   I never used it before not knowing exactly what it was.  It seems like it may be a good fit for what I am doing (having multiple different wordpress installs for different aspects of the same business, but for which a user registration should be a common, shared  id for each of the sites.  

 

If I am able to migrate the production websites to it then the problem would be resolved.  

 

I have heard some plugins are not designed properly to work with it so I’ll have to install them and see.  It looks promising though.  If you wish, just  leave this problem closed for the time being.  I’ll get back to you only if I need to.

 

If I need to, the reason would be the multisite didn’t work for me and so I still need to just have several regular wordpress installs (with no use of the multisite tool).  In that case get_current_blog_id()returns 1 on each of them as described in my problem description.

 

All the best, 

    John
