### ISSUE TITLE
Suspicious code flagged up

### ISSUE THREAD

**Issue by Robs9786hg** [woocommerce/woocommerce#25848]
The WPMU defender plugin has flagged up suspicious code in the following file...
wp-content/plugins/woocommerce/includes/admin/reports/class-wc-report-sales-by-product.php

It says this could be a false positive but that I should contact the developer incase

The error message is shown below. It mentions red and green highlights but you won’t be able to see that. I can email a screenshot for you so you can see the highlights if you let mw know where to email it.

Many thanks 

Rob

Issue Details
We've uncovered suspicious code in wp-content/plugins/woocommerce/includes/admin/reports/class-wc-report-sales-by-product.php. The red highlighted code is the flagged code and the green is the cleaned up code. Note that these warnings can be false positives, so consult your developer before taking action.

Error
	public function __construct() {
		// @codingStandardsIgnoreStart
		if ( isset( $_GET['product_ids'] ) && is_array( $_GET['product_ids'] ) ) {
			$this->product_ids = array_filter( array_map( 'absint', $_GET['product_ids'] ) );
		} elseif ( isset( $_GET['product_ids'] ) ) {
			$this->product_ids = array_filter( array( absint( $_GET['product_ids'] ) ) );
		}

**Comment by claudiosanches** [comment]
Hello @Robs9786hg 

On this code all user input is sanitized with `absint()`, so it's a false positive.
But please, next time consider reporting it on https://hackerone.com/automattic/. Also, if the issue is valid, a bug bounty will be paid out to you. 

Thanks.

**Comment by quinnj102** [comment]
I am using the defender plugin as well and have received this suspicious code notification as well. Good to know that this is a false positive and I can ignore.

**Comment by warudin** [comment]
Received the notification on multiple sites as well. Will ignore it for now but maybe Defender is right in notifying that this code isn't optimal?
