### ISSUE TITLE
Implement additional Tracks

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce#25849]
In the 4.1 release we’ll need to introduce some tracks that are missing:

**Update product**
After a preliminary analysis, it seems that the `wcadmin_product_edit` is being triggered by some extensions’ automations and orders updates. So we need to create a new event that’s only triggered when a user effectively clicks on Update.

Event name: `wcadmin_product_update`
Event props:
product_type: the type of product
manage_stock: if the product has stock management enabled (Y/N)
stock_quantity_update: if the product update included a stock quantity update

**View order**
We don’t have a way to identify when a user sees a single order, only when he sees the orders screen or edits an order status.

Event name: `wcadmin_single_order_view`
Event props:
The same as `wcadmin_orders_edit_status_change` but instead of having the `next_status` and `previous_status` props, we should have the `current_status` prop.

**Add coupon**
We don’t have a way to identify when a user is adding a coupon.

Event name: `wcadmin_coupon_add`
Event props:
The discount type, free shipping, individual use, exclude sale items, and if any usage limits were applied (we don't need to know the limits, just if they were used)

**Global filter**
We need to implement a global filter across all the events, as a way to identify which behavior is done in the eCommerce plan. More info here: https://wp.me/p6q8Tx-1qv

cc @timmyc

**Comment by juliaamosova** [comment]
Thanks @pmcpinto! I am ccing @vedanshujain who is going to be a Release Lead for 4.1 and @ObliviousHarmony as a Release Lead backup. Also adding 4.1 milestone so we don't miss it.

**Comment by timmyc** [comment]
Global filter work in progress here:

https://github.com/woocommerce/woocommerce/pull/25851

Will be getting a p2 up today with some more details around that. We will need a similar solution for js/client-born tracks... and that will require some consolidation of logic across woo core and wc-admin.

**Comment by pmcpinto** [comment]
Hey there, why were these events not implemented in 4.1?

cc @vedanshujain

**Comment by timmyc** [comment]
@pmcpinto looking at the `release/4.1` branch inside the `includes/tracks` folder, I'm seeing the following from the above 2 PRS:

`single_order_view`
> events/class-wc-order-tracking.php
> 34:		WC_Tracks::record_event( 'single_order_view', $properties );

`product_update`
> events/class-wc-products-tracking.php
> 20:		add_action( 'edit_post', array( $this, 'track_product_updated' ), 10, 2 );
> 23:		add_action( 'add_meta_boxes_product', array( $this, 'track_product_updated_client_side' ), 10 );
> 32:	public function track_product_updated( $product_id, $post ) {
> 46:	 * This is needed because `track_product_updated` (using the `edit_post`
> 51:	public function track_product_updated_client_side( $post ) {
> 72:					window.wcTracks.recordEvent( 'product_update', properties );

`coupon_updated`
looks like the naming of this track might have gotten changed up a bit ( cc @becdetat ), but IIRC from my testing it does record on coupon creation too, but need to test to verify again:

> events/class-wc-coupon-tracking.php
> 17:		add_action( 'woocommerce_coupon_object_updated_props', array( $this, 'track_coupon_updated' ), 10, 2 );
> 26:	public function track_coupon_updated( $coupon, $updated_props ) {
> 37:		WC_Tracks::record_event( 'coupon_updated', $properties );

**Comment by vedanshujain** [comment]
Sorry, looks like I incorrectly modified the milestones. This change is live in 4.1.
