### ISSUE TITLE
Coupon validation error on checkout when using usage limit

### ISSUE THREAD

**Issue by vijayhardaha** [woocommerce/woocommerce#25845]
**Description**
When using usage limit validation in a coupon and usage_count meta key is not available in database the getting error while place ordering using the coupon.

**Steps to Follow**
1. Create a coupon with custom code with a usage limit.
2. Don't add the 'usage_count' meta key in the database.
3. Now apply coupon. it will be applied with no error.
4. Place order. the error will be shown (Coupon %s was used in another transaction during this checkout, and coupon usage limit is reached. Please remove the coupon and try again.)

**Expected behavior**
The error should not be there. as this is a valid coupon.

I've also checked the help insert query. here is the query.
```
INSERT INTO wp_postmeta ( post_id, meta_key, meta_value )
SELECT 4363, '_coupon_held_1584293018_4DJre4', '' FROM DUAL
WHERE ( 
SELECT meta_value from wp_postmeta
WHERE wp_postmeta.meta_key = 'usage_count'
AND wp_postmeta.post_id = 4363
LIMIT 1
FOR UPDATE
 ) + ( 
SELECT COUNT(meta_id) FROM wp_postmeta
WHERE wp_postmeta.meta_key like '_coupon_held_{51659de4518eae2539be882a3e142326151d52838f06542c173e8f6179f6c081}'
AND wp_postmeta.meta_key > '_coupon_held_1583688218'
AND wp_postmeta.post_id = 4363
FOR UPDATE
 ) < 1
```
One thing is disturbing me that why meta_key is like ```'_coupon_held_{51659de4518eae2539be882a3e142326151d52838f06542c173e8f6179f6c081}'```
shouldn't it be ```'_coupon_held_%'``` (Maybe I am not understanding something here but please check about this meta key this from your end)

Thanks

**Comment by vijayhardaha** [comment]
### Addtional Information on that query code

filename: class-wc-coupon-data-store-cpt.php
function name: check_and_hold_coupon
variable name: $insert_statement

**Comment by vedanshujain** [comment]
Thanks for reporting the issue, long meta key that you see while debugging is expected and is handled correctly by WordPress later on.

I can reproduce the bug, marking this low priority because we insert `usage_count` when coupon is created, so this is niche case.

**Comment by vijayhardaha** [comment]
Ok, Thanks.
