### ISSUE TITLE
Text type in global product attributes

### ISSUE THREAD

**Issue by itsgauravjain22** [woocommerce/woocommerce#25844]
**Is your feature request related to a problem? Please describe.**
Current woocommerce global product attributes is of type multi select with configurable options terms. There're no product attributes types field to mention whether this is multiselect or a plain text.

**Describe the solution you'd like**
A global product attribute which accept plain text value should be priority for woocommerce. This would help saving local attribute each when product is added.
For eg. If a woocommerce store is configured to sell books, then it would be possible to add isbn13, isbn10, bookauthor, publisher, published-date, pages and language as global product attributes of type plain text (or strings, number)

**Describe alternatives you've considered**
Currently no general alternative selected. It should be default feature of woocommerce. I think most of the ecommerce platform have support for this including Magento, spree etc. The reason to include it in woocommerce without custom code is to make the attributes available in woocommerce products rest API.

**Comment by itsgauravjain22** [comment]
What I need a solution to enforce product attribute name and its slug for text product attributes. I think it's not possible in local product attributes after woocommerce removed text type option. Without enforcing the attribute name, woocommerce store would be prone to highly inconsistent data because on non standardized attributes name and slug.

**Comment by claudiosanches** [comment]
Hello, we don't plan to support it, also for most of the things you listed you can just taxonomies, I see the problem related to isbn13 and isbn10 where each one requires a different value, but for this one we plan to include new fields on WooCommerce: https://github.com/woocommerce/woocommerce/issues/22969

**Comment by itsgauravjain22** [comment]
@claudiosanches Take the example of books pages. Does it hurt performance wise too much, If register as global attribute & add unique numbers it. A book can contain any number of pages. Clearly this product attribute fall in category of text attribute just like isbn13.

If it does hurt, what are recommended solution for creating such identifier like product attributes.

**Comment by claudiosanches** [comment]
@itsgauravjain22 Yes, if using only for single values it doesn’t even make sense to use global attributes.

> If it does hurt, what are recommended solution for creating such identifier like product attributes.

For values that have unique values you shouldn't use any kind of attribute, it should be custom fields on your product, or even better create a "Book" type of product with custom fields just for it.

**Comment by itsgauravjain22** [comment]
@claudiosanches Thanks for the information.

> create a "Book" type of product with custom fields just for it.

If I create a custom "Book" Type of product, Would it be supported by woocommerce csv schema mentioned [here](https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema) and Woocommerce Rest API v3 documented [here](https://woocommerce.github.io/woocommerce-rest-api-docs/)

If it's not supported, Is there way to make such fields without custom fields in a native woocommerce supported environment.

**Comment by claudiosanches** [comment]
@itsgauravjain22 if you are creating a new type of product, what requires some knowledge about coding, you can also integrate with REST API and CSV importer.

> Point is I try to minimize customization as much as possible, to be closer to official channels.

WooCommerce is made to allow customization, in cases like yours it's better to make something custom instead of abusing of something that will potentially cause performance issues.

**Comment by itsgauravjain22** [comment]
Thanks for the advise and suggestion. Then I would go for custom solution.
