### ISSUE TITLE
[4.0] Custom variation multiple select field not working

### ISSUE THREAD

**Issue by jethrolanda** [woocommerce/woocommerce#25852]
**Describe the bug**
We have a custom multiple select added in variation fields but when we try to save the changes it will only accept 1 value.

**To Reproduce**
1. Create a variable product with variations
2. Edit a variation and select multiple values in the custom multiple select
3. Save variation changes by clicking "Save changes button" ( not the Publish )

Issue: it will only accept 1 value

**Screenshots**
![image](https://user-images.githubusercontent.com/7158648/76289344-e195a380-62e3-11ea-87c7-57c3372ccea8.png)

**Expected behavior**
It should save all values.

**WordPress Environment**
WooCommerce Version 4.0.0-rc.2
WordPress Version 5.3.2
WooCommerce Wholesale Prices Version 1.11.1
WooCommerce Wholesale Prices Premium Version 1.23.9

Note: Tested and working in WC Version 3.9.3

**Comment by jethrolanda** [comment]
I noticed that in woocommerce\assets\js\admin\meta-boxes-product-variation.js
This is the code from WC 3.9.3 which is working:
```
get_variations_fields: function( fields ) {
	var data = $( ':input', fields ).serializeJSON();

	$( '.variations-defaults select' ).each( function( index, element ) {
		var select = $( element );
		data[ select.attr( 'name' ) ] = select.val();
	});

	return data;
}
```
while this is the code from WC 4 rc 2 it only allows 1 post value for ajax request:
```
get_variations_fields: function( fields ) {

    var data = {};

    $( ':input', fields ).each( function( index, elem ) {

        var $input = $( elem );

        // Bypass inputs without name att
        if ( ! elem.name ) {
            return;
        }

        // Bypass non-checked checkboxes and radio buttons.
        if ( ( $input.is( ':radio' ) || $input.is( ':checkbox' ) ) && ! $input.is( ':checked' ) ) {
            return;
        }

        // Bypass disabled fields.
        if ( true === $input.prop( 'disabled' ) ) {
            return;
        }

        data[ elem.name ] = elem.value;

    });

    $( '.variations-defaults select' ).each( function( index, element ) {
        var select = $( element );
        data[ select.attr( 'name' ) ] = select.val();
    });

    return data;
}
```

**Comment by juliaamosova** [comment]
Hi @jethrolanda,

Thank you for submitting the issue. Noring here the testing I've done so far with a free version of the Wholesale prices plugin. I understand that the feature you are using is provided by the paid version. 

I used only the free version of [WooCommerce Wholesale Prices](https://wordpress.org/plugins/woocommerce-wholesale-prices/) plugin - version 1.11.1. 

Tested with newly released WooCommerce 4.0. 

My variations prices setup (I have 3 variations):

![var1](https://user-images.githubusercontent.com/19143190/76349819-181def00-62e1-11ea-878f-8f3af7a07b95.jpg)

Before saving variations:

![var2](https://user-images.githubusercontent.com/19143190/76349920-456a9d00-62e1-11ea-88de-523dd2fb4060.jpg)

After saving variations but before publishing a product:

![var3](https://user-images.githubusercontent.com/19143190/76350098-8367c100-62e1-11ea-9f1f-a8281b496c58.jpg)

After publishing the product, I can view it:

- As a regular customer:

<img width="1346" alt="Screen Shot 2020-03-10 at 3 00 58 PM" src="https://user-images.githubusercontent.com/19143190/76350155-9da19f00-62e1-11ea-9a30-22cd47818be8.png">

- As the customer of a wholesale price: 

<img width="1364" alt="Screen Shot 2020-03-10 at 3 00 49 PM" src="https://user-images.githubusercontent.com/19143190/76350178-a6927080-62e1-11ea-924d-aebaf0169afb.png">

Please note that I can also successfully save variations without wholesale price plugin you are using. 

I will see if I can test further with a paid plugin and use the feature that is giving troubles.

**Comment by jkohlbach** [comment]
Hi @juliaamosova we are happy to provide a copy of the premium add on for testing. The free version doesn’t have any fields that are arrays so this issue won’t show for that. Feel free to email Jethro directly at jethro@rymera.com.au to coordinate an archive. He can provide that ASAP.

**Comment by gaupoit** [comment]
This PR https://github.com/woocommerce/woocommerce/pull/25382 also causes an issue that we cannot choose multiple files with Downloadble products. 

**To Reproduce**
Steps to reproduce the behavior:

1. Create a variable product with variations
2. Choose Downloadable option
3. Select multiple files in Downloadable Files section
Save variation changes by clicking "Save changes button" ( not the Publish )

Issue: it will only accept 1 file

**Screenshots**
If applicable, add screenshots to help explain your problem.

<img width="717" alt="Screen Shot 2020-03-11 at 14 10 14" src="https://user-images.githubusercontent.com/4486806/76392066-6d223980-63a3-11ea-9b7b-c8663c1cc627.png">

After saving...

<img width="740" alt="Screen Shot 2020-03-11 at 14 21 00" src="https://user-images.githubusercontent.com/4486806/76392180-9a6ee780-63a3-11ea-9d3c-4041d130468b.png">

**Expected behavior**
It should save all selected files.

**WordPress Environment**
WooCommerce Version 4.0.0

**Comment by juliaamosova** [comment]
Thanks @jkohlbach, @ObliviousHarmony managed to reproduce it on our end and I see that there is a PR submitted already. Thanks for the additional details @gaupoit.

**Comment by jkohlbach** [comment]
Could we bump the priority on this? It's causing support issues.

**Comment by juliaamosova** [comment]
@jkohlbach there is already PR open to fix this issue: https://github.com/woocommerce/woocommerce/pull/25874 - pending author's feedback. At this point, the priority doesn't matter anymore. The issue will be fixed as soon as the author of the PR will address comments. Once done, we will then include the fix in the next available release.

**Comment by peterfabian** [comment]
@jkohlbach We're going to release 4.0.1 that includes the #25950 within a day.

**Comment by jkohlbach** [comment]
@peterfabian @juliaamosova you're both legends thank you!
