### ISSUE TITLE
Admin.css issues with Select2

### ISSUE THREAD

**Issue by wpnetninjas** [woocommerce/woocommerce#25853]
**Describe the bug**
When using Advanced Custom Fields Pro select2 fields on WooCommerce products via admin interface. User is unable to clear the selection of the Select 2 menu by clicking on the 'x'. This is due to CSS in WooCommerce admin.css which sets the width of the selection__arrow to 28px. This ends up overlapping the select2-selection__clear span.

.branch-5-3 .select2-container .select2-selection--single .select2-selection__arrow {
    right: 1px;
    height: 28px;
    width: 28px;
    background: url("data:image/svg+xml;charset=US-ASCII,%3Csvg%20width%3D%2220%22%20height%3D%2220%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20d%3D%22M5%206l5%205%205-5%202%201-7%207-7-7%202-1z%22%20fill%3D%22%23555%22%2F%3E%3C%2Fsvg%3E") no-repeat right 5px top 55%;
        background-size: auto;
    background-size: 16px 16px;
}

To resolve the issue, the above css in admin.css needs to be removed completely.

**Screenshots**
http://somup.com/cYeQQthzjp

**Expected behavior**
The close span should be clickable and allow the user to clear Select 2 box selected option

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @wpnetninjas,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/25427. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
