### ISSUE TITLE
Product weight does not accept "4,5" values although product price does

### ISSUE THREAD

**Issue by maltehuebner** [woocommerce/woocommerce#25864]
**Describe the bug**
We use WooCommerce 3.9.2 and and WooCommerce Admin 0.26.1 in a german WordPress installation. When adding products, we are able to setup a product price like "49,99", but not a weight like "4,5".

**To Reproduce**
1. Get a german WooCommerce 3.9.2 installation with WooCommerce Admin 0.26.1.
2. Add a product.
3. While in the adding process, try to setup the product weight in a german format like "4,5".
4. The value "4,5" is rejected, but values like "4.5" are accpeted.

**Screenshots**
<img width="791" alt="Bildschirmfoto 2020-03-10 um 06 57 39" src="https://user-images.githubusercontent.com/633959/76354324-87600700-6312-11ea-8b0c-9987e10c0cdc.png">
<img width="791" alt="Bildschirmfoto 2020-03-10 um 07 01 30" src="https://user-images.githubusercontent.com/633959/76354331-88913400-6312-11ea-9e7f-2201cd6174c0.png">

**Expected behavior**
I expect to be able to setup freight weight in a german format like "4,5" kg.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://wordpress.wp
Site address (URL): http://wordpress.wp
WC Version: 3.9.2
REST API Version: ✔ 1.0.7
Log Directory Writable: ❌ Um Logging zu aktivieren
mache /var/www/wordpress/wp-content/uploads/wc-logs/ beschreibbar oder definiere ein benutzerdefiniertes WC_LOG_DIR.

WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.29 (Ubuntu)
PHP Version: 7.2.28-3+ubuntu18.04.1+deb.sury.org+1
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1a

SUHOSIN Installed: –
MySQL Version: 5.7.29-0ubuntu0.18.04.1
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Dein Server verfügt nicht über eine lauffähige Version der SoapClient Klasse - einige Zahlungsschnittstellen
welche SOAP nutzen
funktionieren unter Umständen nicht korrekt.

DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.0
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 21.92MB
Datenbank-Datengröße: 11.36MB
Datenbank-Indexgröße: 10.56MB
wp_woocommerce_sessions: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Daten: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_aws_cache: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aws_index: Daten: 1.52MB + Index: 0.44MB + Engine InnoDB
wp_berocket_termmeta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_braapf_product_stock_status_parent: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_braapf_product_variation_attributes: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_braapf_term_taxonomy_hierarchical: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_braapf_variation_attributes: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_cp_calculated_fields_form_discount_codes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cp_calculated_fields_form_posts: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cp_calculated_fields_form_revision: Daten: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_cp_calculated_fields_form_settings: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Daten: 2.45MB + Index: 0.19MB + Engine InnoDB
wp_postmeta: Daten: 2.52MB + Index: 4.03MB + Engine InnoDB
wp_posts: Daten: 1.52MB + Index: 0.27MB + Engine InnoDB
wp_relevanssi: Daten: 1.52MB + Index: 3.83MB + Engine InnoDB
wp_relevanssi_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_relevanssi_stopwords: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Daten: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Daten: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_dhl_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipmentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipments: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_gzd_shipment_items: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpf_filters: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpf_modules: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpf_modules_type: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpf_usage_stat: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 137
br_filters_group: 10
br_product_filter: 18
cookielawinfo: 1
custom_css: 1
customize_changeset: 171
invoice: 13
nav_menu_item: 44
page: 27
post: 6
product: 225
product_variation: 244
revision: 75
scheduled-action: 29
shop_coupon: 2
shop_order: 24
wafs: 1
woo_discount: 3
woo_discount_cart: 1

### Security ###

Secure connection (HTTPS): ❌
					Dein Shop benutzt kein HTTPS. Erfahre mehr über HTTPS und SSL-Zertifikate.
Hide errors from visitors: ✔

### Active Plugins (36) ###

Advanced Woo Search: von ILLID – 1.95
AGB-Connector der IT-Recht Kanzlei: von Inpsyde GmbH – 2.0.2
Formularfelder berechneten: von CodePeople – 1.0.362
CategoryTinymce: von Kevin Heath – 3.8.1
Code Snippets: von Code Snippets Pro – 2.14.0
GDPR Cookie Consent: von WebToffee – 1.8.5
Facebook for WooCommerce: von Facebook – 1.9.15 – Nicht getestest mit der aktiven WooCommerce-Version
Jetpack von WordPress.com: von Automattic – 8.2.3
Live CSS JS Code Editor: von Ozan Canakli – 1.0.4
Loco Translate: von Tim Whitlock – 2.3.1
Pflanzburg: von Malte Hübner – 0.1
Relevanssi: von Mikko Saari – 4.6.0
Search & Replace: von Inpsyde GmbH – 3.2.1
Shortcodes Ultimate: von Vladimir Anokhin – 5.7.0
SiteOrigin CSS: von SiteOrigin – 1.2.5
TinyMCE Advanced: von Andrew Ozz – 5.3.0
Universal Star Rating: von Chasil – 2.0.6
User Role Editor: von Vladimir Garagulya – 4.53
Vendidero Helper: von Vendidero – 1.3.0
WooCommerce Weight Based Shipping: von weightbasedshipping.com – 5.3.3.1
Woo Discount Rules: von Flycart Technologies LLP – 1.9.5
WPC Product Bundles for WooCommerce: von WPClever.net – 3.8.9
WooCommerce Admin: von WooCommerce – 0.26.1
WooCommerce AJAX Products Filter: von BeRocket – 2.4.1.8
WC - APG Weight Shipping: von Art Project Group – 2.3.1.4 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce Expand Tabs: von Diana Burduja – 1.13 – Nicht getestest mit der aktiven WooCommerce-Version
WooCommerce PayPal Checkout Gateway: von WooCommerce – 1.6.20
WooCommerce Stripe-Gateway: von WooCommerce – 4.3.2
Germanized für WooCommerce Pro: von Vendidero – 2.0.13
Germanized für WooCommerce: von Vendidero – 3.1.3
WooCommerce Services: von Automattic – 1.22.3 – 1.22.4 ist verfügbar
WooCommerce: von Automattic – 3.9.2 – 4.0.0 ist verfügbar
WP phpMyAdmin: von Puvox.software – 3.01
WPB Product Categories Slider for WooCommerce: von wpbean – 1.1.7 – Nicht getestest mit der aktiven WooCommerce-Version
WPC Composite Products for WooCommerce (Premium): von WPClever.net – 1.4.3
Custom Product Tabs for WooCommerce: von YIKES
Inc. – 1.6.13


### Inactive Plugins (10) ###

AJAX Search for WooCommerce: von Damian Góra – 1.6.2
Flexible Shipping: von WP Desk – 3.9.9
Klarna Payments for WooCommerce: von krokedil
klarna
automattic – 2.0.6

Mailchimp for WooCommerce: von Mailchimp – 2.3.3
Mobile Menu: von Rui Guerreiro – 2.8
Woo Product Filter: von woobewoo – 1.2.6
Woo Variations Table: von Alaa Rihan – 2.1.3
WPC Composite Products for WooCommerce: von WPClever.net – 1.4.3
WPC Smart Quick View for WooCommerce: von WPClever.net – 1.3.4
WPC Variations Radio Buttons for WooCommerce: von WPClever.net – 1.1.5

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
woosb (woosb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: #7 - /?page_id=7
Warenkorb: #8 - /?page_id=8
Kasse: #9 - /?page_id=9
Mein Konto: #10 - /?page_id=10
Allgemeine Geschäftsbedingungen: #49 - /?page_id=49

### Theme ###

Name: Arcade
Version: 2.1.8
Author URL: https://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.5.5
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Abgeschlossen: 6
Oldest: 2020-02-01 20:39:36 +0100
Newest: 2020-02-01 20:39:38 +0100

Ausstehend: 23
Oldest: 2020-02-20 19:46:07 +0100
Newest: 2020-03-08 16:51:42 +0100

Abgebrochen: 0
Oldest: –
Newest: –

In Bearbeitung: 0
Oldest: –
Newest: –

Fehlgeschlagen: 0
Oldest: –
Newest: –

`
```
</details>

**Comment by juliaamosova** [comment]
Hi @maltehuebner,

Thank you for submitting the issue. However, I can’t reproduce the same as you are seeing. 

I've switched the language to German via `Settings / General` and installed a free version of [Germanized for WooCommerce by Vendidero](https://vendidero.de/woocommerce-germanized). 

In both price and weight cases, I still can't use a comma as a decimal separator:

- Price:

<img width="965" alt="Screen Shot 2020-03-10 at 4 24 53 PM" src="https://user-images.githubusercontent.com/19143190/76357273-c596ff80-62ed-11ea-87f0-0dbbef69d306.png">

- Weight:

<img width="960" alt="Screen Shot 2020-03-10 at 4 25 11 PM" src="https://user-images.githubusercontent.com/19143190/76357295-ce87d100-62ed-11ea-8d16-28fd3c46fa1b.png">

Do I need to do anything else in order to make the website "Germanized"?

**Comment by juliaamosova** [comment]
@maltehuebner never mind my request:

>Do I need to do anything else in order to make the website "Germanized"?

I see that after changing the decimal separator to be `comma` via `WooCommerce/Settings?General`:

![ecimal](https://user-images.githubusercontent.com/19143190/76360080-b36b9000-62f2-11ea-968a-4607e3a95bac.jpg)

I can actually use comma in the price without needing to "Germanize" the site:

<img width="961" alt="Screen Shot 2020-03-10 at 5 11 39 PM" src="https://user-images.githubusercontent.com/19143190/76360110-c5e5c980-62f2-11ea-9bfe-4e1000e98b02.png">

But still can't use comma in the shipping weight:

<img width="964" alt="Screen Shot 2020-03-10 at 5 11 32 PM" src="https://user-images.githubusercontent.com/19143190/76360146-d5651280-62f2-11ea-953a-63370dea0266.png">

Looks like the issue is on our end indeed.

**Comment by ObliviousHarmony** [comment]
This is because in many places, we marry the PHP locale with the decimal settings, as well as a default of `.` before removing the locale from the number entirely for validation. This is only validated using the PHP locale. We need to make this more resilient for these differences here.

**Comment by claudiosanches** [comment]
This is becoming a common mistake for many people, maybe we can make things more clear in our settings, but we don't have any options to set the decimal operator for weight or dimensions, in fact those values come from PHP locale functions, so it will use what you have set for the PHP on your server.

About the options in Settings > General > Currency options, if you check the tooltip for the "Decimal separator" option you'll see "This sets the decimal separator of displayed prices.".

So this is not a bug, but maybe we could remove the tooltip and set it just as a description, like:

![Screenshot from 2020-03-10 19-18-10](https://user-images.githubusercontent.com/1264099/76364443-ef5b2100-6303-11ea-8aa5-c0011b5eca0e.png)

**Comment by Marcoevich** [comment]
As I posted a similar issue (as mentioned by Julia) I hope that I can leave my vote here. Many of us use shared hosting servers that we have limited control over. I would very much prefer that you leave those settings in place and make them do what I thought they would do: set the thousand and decimal separator for prices as well as the weight and dimensions. I wouldn't know how to change these options otherwise. For me it would make sense to have one option that controls this behaviour for all parts of our shop.

**Comment by claudiosanches** [comment]
@Marcoevich even on shared hosting you can set things like that. Also if you are hosting on your country suppose to already have all set for you. Too many options makes things only more difficult for people to understand and set, so more options aren't something we want to include often.

**Comment by Marcoevich** [comment]
I see, can't disagree with that. I've now solved the issue by adding `setlocale(LC_NUMERIC, 'nl_NL');` to `functions.php`. Now my issue is resolved.

**Comment by Marcoevich** [comment]
Unfortunately, this little change had many unwanted consequences. All kinds of scripts displayed wrong amounts and width calculations in css didn't work anymore, etc. So this is no solution.

I've contacted Siteground support about this but they don't know of a simple server side setting without any unwanted consequences.

Do you have a better idea on how to make this change for woocommerce, without it having unwanted side effects to other parts of the site @claudiosanches ?

**Comment by maltehuebner** [comment]
Although I thought I could call myself an experienced PHP developer, I was not able to adjust the settings in a way to make the weight input field work and break nothing else :(

**Comment by opicron** [comment]
I use commas for pricing decimals and dots for attributes decimals for a while now. 

This works best with all other plugins and scripts. I assume that fixing this issue will break many other extensions. 

And how will we actually seperate multiple decimal attributes if we actually use the comma for decimals? 

1.2, 1.3 works now, I assume that 1,2 1,3 with an space, or 1,2/1,3 with an slash will be much less clear and error prone.

Even if the current situation is odd for new users I think it far outweighs the fixed situation. As long as it is documented well we should be good.

**Comment by rizatufan** [comment]
I am having this problem too. How did you solve the problem?

**Comment by vitsupport** [comment]
Hi. Why can't the option for decimals be changed to apply for both price and shipping? Changing the locale generates, as @Marcoevich said, unwanted changes for i.e. CSS. Most users who install a ready made theme, are just users and not developers, and expect to use the same decimal separater through out their site... Or am I totally wrong? :)

**Comment by Sataptech** [comment]
It really shouldn't be that hard.

If you use a comma for decimals in one place you use it everywhere. So this should be a localization option in Woocommerce and NOT something that needs to be set on server side.
