### ISSUE TITLE
WooCommerce 4.0 update errors wp-db.php on line 659

### ISSUE THREAD

**Issue by phemels** [woocommerce/woocommerce#25865]
I have update woocommerce to 4.0 om my testwebsite, but now get these errors in the backend:

wpdb::$actionscheduler_actions in /home/pahedomotica/test.pahedomotica.nl/wp-includes/wp-db.php on line 659

Notice: Undefined property: wpdb::$actionscheduler_actions in /home/pahedomotica/test.pahedomotica.nl/wp-includes/wp-db.php on line 659

Warning: Cannot modify header information - headers already sent by (output started at /home/pahedomotica/test.pahedomotica.nl/wp-includes/wp-db.php:659) in /home/pahedomotica/test.pahedomotica.nl/wp-includes/functions.php on line 6029

Warning: Cannot modify header information - headers already sent by (output started at /home/pahedomotica/test.pahedomotica.nl/wp-includes/wp-db.php:659) in /home/pahedomotica/test.pahedomotica.nl/wp-admin/includes/misc.php on line 1252

Warning: Cannot modify header information - headers already sent by (output started at /home/pahedomotica/test.pahedomotica.nl/wp-includes/wp-db.php:659) in /home/pahedomotica/test.pahedomotica.nl/wp-admin/admin-header.php on line 9

Is there a fix for this?

**Comment by rrennick** [comment]
@phemels Thanks for the report. You didn't fill out the bug template. Can you confirm you have this issue with the following:

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

If so, could you please submit your system status report?

**Comment by phemels** [comment]
Hi Ron,

*Isolating the problem (mark completed items with an [x]):*

   -  I have deactivated other plugins and confirmed this bug occurs when
   only WooCommerce plugin is active.
   - X This bug happens with a default WordPress theme active, or Storefront
   <https://woocommerce.com/storefront/>.
   -  I can reproduce this bug consistently using the steps above.

If so, could you please submit your system status report?
`
### WordPress Environment ###

WordPress address (URL): https://test.pahedomotica.nl
Site address (URL): https://test.pahedomotica.nl
WC Version: 4.0.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.2
WC Admin Version: ✔ 1.0.0
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.15
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 100000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.27-MariaDB
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.0
WC Database Prefix: wp_
Total Database Size: 53.39MB
Database Data Size: 40.01MB
Database Index Size: 13.38MB
wp_woocommerce_sessions: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB + Engine
MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index:
0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.28MB + Index: 0.14MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine
MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB +
Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine
MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine
MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_admin_columns: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_aelia_dismissed_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aelia_exchange_rates_history: Data: 0.02MB + Index: 0.00MB + Engine
InnoDB
wp_ajaxsearchpro: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_ajaxsearchpro_priorities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ajaxsearchpro_statistics: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_asp_index: Data: 5.52MB + Index: 5.03MB + Engine InnoDB
wp_asp_synonyms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_atum_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_atum_product_data: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_aws_cache: Data: 1.50MB + Index: 0.00MB + Engine InnoDB
wp_aws_index: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_comments: Data: 0.12MB + Index: 0.07MB + Engine MyISAM
wp_dgwt_wcas_index: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
wp_dgwt_wcas_invindex_doclist: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_dgwt_wcas_invindex_info: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dgwt_wcas_invindex_wordlist: Data: 0.25MB + Index: 0.17MB + Engine InnoDB
wp_dgwt_wcas_tax_index: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_dgwt_wcas_var_index: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_feedmanager_channel: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_feedmanager_country: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_feedmanager_errors: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_feedmanager_feed_status: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_feedmanager_field_categories: Data: 0.02MB + Index: 0.00MB + Engine
InnoDB
wp_feedmanager_product_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_feedmanager_product_feedmeta: Data: 0.02MB + Index: 0.03MB + Engine
InnoDB
wp_feedmanager_source: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_custom_fields: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine
InnoDB
wp_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailpoet_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailpoet_mapping_to_external_entities: Data: 0.04MB + Index: 0.04MB +
Engine MyISAM
wp_mailpoet_newsletters: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_newsletter_links: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_mailpoet_newsletter_option: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_newsletter_option_fields: Data: 0.00MB + Index: 0.01MB + Engine
MyISAM
wp_mailpoet_newsletter_posts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_newsletter_segment: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_newsletter_templates: Data: 1.72MB + Index: 0.00MB + Engine
MyISAM
wp_mailpoet_scheduled_tasks: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_mailpoet_scheduled_task_subscribers: Data: 0.00MB + Index: 0.00MB +
Engine MyISAM
wp_mailpoet_segments: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_sending_queues: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_settings: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_statistics_clicks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_statistics_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_statistics_newsletters: Data: 0.00MB + Index: 0.00MB + Engine
MyISAM
wp_mailpoet_statistics_opens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_statistics_unsubscribes: Data: 0.00MB + Index: 0.00MB + Engine
MyISAM
wp_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB
+ Engine InnoDB
wp_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine
InnoDB
wp_mailpoet_subscribers: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_mailpoet_subscriber_custom_field: Data: 0.00MB + Index: 0.00MB + Engine
MyISAM
wp_mailpoet_subscriber_ips: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailpoet_subscriber_segment: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.50MB + Index: 0.24MB + Engine MyISAM
wp_postmeta: Data: 5.42MB + Index: 1.79MB + Engine MyISAM
wp_posts: Data: 1.30MB + Index: 0.23MB + Engine MyISAM
wp_redirection_404: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_redirection_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_redirection_items: Data: 0.21MB + Index: 0.17MB + Engine MyISAM
wp_redirection_logs: Data: 2.44MB + Index: 0.62MB + Engine MyISAM
wp_rrequest: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_stock_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_terms: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wp_term_relationships: Data: 0.07MB + Index: 0.12MB + Engine MyISAM
wp_term_taxonomy: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wcpdf_credit_note_number: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wcpdf_invoice_number: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wcpdf_packing_slip_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_proforma_number: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdslayer: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wdsslide: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wdsslider: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_webwinkelkeur_invite_error: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfBlockedIPLog: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfBlocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfConfig: Data: 3.49MB + Index: 0.01MB + Engine MyISAM
wp_wfCrawlers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfFileChanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfFileMods: Data: 4.74MB + Index: 0.98MB + Engine MyISAM
wp_wfHits: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wfHoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfIssues: Data: 0.38MB + Index: 0.10MB + Engine MyISAM
wp_wfKnownFileList: Data: 2.48MB + Index: 0.30MB + Engine MyISAM
wp_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfLocs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfLogins: Data: 0.16MB + Index: 0.04MB + Engine MyISAM
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfNotifications: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_wfPendingIssues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfReverseCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfSNIPCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfStatus: Data: 0.26MB + Index: 0.10MB + Engine MyISAM
wp_wfTrafficRates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wrm_comment: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wysija_campaign: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_campaign_list: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_custom_field: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_email: Data: 0.14MB + Index: 0.00MB + Engine MyISAM
wp_wysija_email_user_stat: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_email_user_url: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_list: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_subscriber_ips: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_url: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_url_mail: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_user: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wysija_user_field: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_user_history: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wysija_user_list: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yith_wapo_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wapo_types: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_yoast_seo_meta: Data: 0.03MB + Index: 0.04MB + Engine MyISAM

### Post Type Counts ###

amn_exact-metrics: 1
attachment: 1110
custom_css: 1
c_p_tab: 1
mailpoet_page: 1
nav_menu_item: 51
oembed_cache: 5
page: 25
popup: 7
popup_theme: 6
post: 25
product: 395
product_variation: 72
revision: 11
shop_coupon: 49
shop_order: 120
sp_wps_shortcodes: 1
tm_global_cp: 6
user_request: 2
wafs: 1
wcps: 1
wds-slider: 1
wpcf7_contact_form: 1
wysijap: 1
yith_popup: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (50) ###

Admin Menu Editor: by Janis Elsts – 1.9.3
AJAX Search for WooCommerce (Premium): by Damian Góra – 1.6.1 – Not tested
with the active version of WooCommerce
Akismet Anti-Spam: by Automattic – 4.1.3
ATUM Inventory Management for WooCommerce: by Stock Management Labs™ –
1.6.9 – Not tested with the active version of WooCommerce
Better Search Replace: by Delicious Brains – 1.3.3
Booster Plus for WooCommerce: by Algoritmika Ltd – 4.7.1 – Not tested with
the active version of WooCommerce
Classic Editor: by WordPress Contributors – 1.5
Code Snippets: by Code Snippets Pro – 2.14.0
Admin Columns: by AdminColumns.com – 4.0.1
Contact Form 7: by Takayuki Miyoshi – 5.1.7
Customer Reviews for WooCommerce: by ivole – 3.98 – Not tested with the
active version of WooCommerce
Easy FancyBox: by RavanH – 1.8.18
Easy Table of Contents: by Steven A. Zahm – 2.0.1
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 6.0.2
MailPoet 3 (New): by MailPoet – 3.46.2
MCE Table Buttons: by Jake Goldman
10up
Oomph – 3.3

Max Mega Menu - Pro Addon: by megamenu.com – 2.0.1
Max Mega Menu: by megamenu.com – 2.7.4
Mollie Payments for WooCommerce: by Mollie – 5.4.2 – Not tested with the
active version of WooCommerce
PHP Compatibility Checker: by WP Engine – 1.5.0
Popup Maker: by Popup Maker – 1.9.1
Redirection: by John Godley – 4.7
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.3
Sales Pop: by Beeketing – 1.4.18 – Not tested with the active version of
WooCommerce
Slider by 10Web: by 10Web – 2.2.29
SMTP Mailer: by naa986 – 1.0.8
Sticky Menu (or Anything!) on Scroll: by WebFactory Ltd – 2.2
Stock Exporter for WooCommerce: by Webdados – 0.7.1 – Not tested with the
active version of WooCommerce
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.22

WooCommerce Dynamic Pricing & Discounts: by RightPress – 2.3.5 – Not tested
with the active version of WooCommerce
WooCommerce NL Postcode Checker: by Ewout Fernhout – 2.3.0 – Not tested
with the active version of WooCommerce
WebwinkelKeur: by Albert Peschar – 1.8 – Not tested with the active version
of WooCommerce
WooCommerce Cost of Goods: by SkyVerge – 2.9.5
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.19
WooCommerce MyParcel: by Adem Demir – 3.2.0 – Not tested with the active
version of WooCommerce
WooCommerce Offerte: by Voleatech GmbH – 1.7.7 – Not tested with the active
version of WooCommerce
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.4.7
WooCommerce PDF Invoices & Packing Slips Professional: by Ewout Fernhout –
2.4.1 – Not tested with the active version of WooCommerce
WooCommerce PDF Invoices & Packing Slips Premium Templates: by Ewout
Fernhout – 2.8.0 – Not tested with the active version of WooCommerce
PickPlugins Product Slider for WooCommerce: by PickPlugins – 1.13.2 – Not
tested with the active version of WooCommerce
WooCommerce TM Extra Product Options: by themeComplete – 4.9.12.1 – Not
tested with the active version of WooCommerce
WooCommerce: by Automattic – 4.0.0
Wordfence Security: by Wordfence – 7.4.6
Yoast SEO: by Team Yoast – 13.2 – Not tested with the active version of
WooCommerce
WP Menu Cart Pro: by Jeremiah Prummer
Ewout Fernhout – 3.2.0 – Not tested with the active version of WooCommerce

WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.0.16

WP Product Feed Manager: by Michel Jongbloed – 1.19.1 – Not tested with the
active version of WooCommerce
WP Rollback: by Impress.org – 1.7.0
WP Overnight Sidekick: by Jeremiah Prummer
Ewout Fernhout
Michael Kluver – 2.2.0

Zendesk Chat Widget: by Zendesk – 1.4.15

### Inactive Plugins (4) ###

Disable Emails: by WebAware – 1.6.2
e-Boekhouden.nl: by e-Boekhouden.nl – 3.0.2
W3 Total Cache: by BoldGrid – 0.13.1
WooBought - WooCommerce Live Sales Notifications: by Maarten Belmans –
1.3.2 – Not tested with the active version of WooCommerce

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
yith-composite (yith-composite)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-2 (rated-2-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #4 - /
Cart: #5 - /winkelmand/
Checkout: #6 - /afrekenen/
My account: #7 - /mijn-account/
Terms and conditions: #172 - /pahedomotica-algemene-voorwaarden/

### Theme ###

Name: Twenty Nineteen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that
you did not build personally we recommend using a child theme. See: How to
create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: /home/pahedomotica/
test.pahedomotica.nl/wp-content/plugins/woocommerce-tm-extra-product-options/templates/cart/cart-item-data.php

### Ajax Search for WooCommerce ###

Ajax Search for WooCommerce - mbstring: ✔
Ajax Search for WooCommerce - pdo_mysql: ✔
Ajax Search for WooCommerce - Finding wp-load.php: ✔
Ajax Search for WooCommerce - Multisite: disabled
Ajax Search for WooCommerce - Conflicts with plugins: no

### Action Scheduler ###

Complete: 132
Oldest: 2020-02-09 21:35:02 +0100
Newest: 2020-03-10 21:40:39 +0100

Pending: 5
Oldest: 2020-03-11 21:37:08 +0100
Newest: 2020-03-11 21:40:39 +0100

`

Met vriendelijke groet / Kind regards,

Paul,


Website: www.pahedomotica.nl

Email: info@pahedomotica.nl

Tel nr.: 06-54650989


Op di 10 mrt. 2020 om 21:59 schreef Ron Rennick <notifications@github.com>:

**Comment by phemels** [comment]
Hi Ron,

Found it, when disabling this plugin the lines are gone:

[image: image.png]

I will contact the plugin makers

Met vriendelijke groet / Kind regards,

Paul,


Website: www.pahedomotica.nl

Email: info@pahedomotica.nl

Tel nr.: 06-54650989


Op di 10 mrt. 2020 om 22:05 schreef Paul PaHeDomotica <info@pahedomotica.nl

**Comment by rrennick** [comment]
@phemels Thanks for the follow up :)
