### ISSUE TITLE
[4.0.0] Upgrade error...

### ISSUE THREAD

**Issue by GlennMartin1** [woocommerce/woocommerce#25862]
**Describe the bug**
Upon attempting to upgrade, I receive this error:

> Warning: require_once(classes/ActionScheduler_Versions.php): failed to open stream: No such file or directory in /nas/content/live/hometownstruct/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/action-scheduler.php on line 31
> 
> Fatal error: require_once(): Failed opening required 'classes/ActionScheduler_Versions.php' (include_path='.:/usr/share/pear/php:/usr/share/php') in /nas/content/live/hometownstruct/wp-content/plugins/woocommerce/includes/libraries/action-scheduler/action-scheduler.php on line 31
> T

WordPress automatically detected an error and deactivated WooCommerce.

I reactivated WooCommerce and (as of now, still testing) everything appears to be ok.

**To Reproduce**
1. Upgrade from WC 3.9.3 to WC 4.0
2. See error.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://www.hometownstructures.com
Site address (URL): https://www.hometownstructures.com
WC Version: 4.0.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.2
WC Admin Version: ✔ 1.0.0
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.15-3+ubuntu18.04.1+deb.sury.org+1
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.58.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.28-31-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.0
WC Database Prefix: wp_cjzpj17bjz_
Total Database Size: 57.01MB
Database Data Size: 44.95MB
Database Index Size: 12.06MB
wp_cjzpj17bjz_woocommerce_sessions: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
wp_cjzpj17bjz_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cjzpj17bjz_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cjzpj17bjz_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_cjzpj17bjz_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cjzpj17bjz_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cjzpj17bjz_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_cjzpj17bjz_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_cjzpj17bjz_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_cjzpj17bjz_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cjzpj17bjz_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cjzpj17bjz_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cjzpj17bjz_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_cjzpj17bjz_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cjzpj17bjz_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cjzpj17bjz_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cjzpj17bjz_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cjzpj17bjz_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_cjzpj17bjz_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cjzpj17bjz_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cjzpj17bjz_gf_entry: Data: 0.39MB + Index: 0.11MB + Engine InnoDB
wp_cjzpj17bjz_gf_entry_meta: Data: 1.52MB + Index: 2.16MB + Engine InnoDB
wp_cjzpj17bjz_gf_entry_notes: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_cjzpj17bjz_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_gf_form_meta: Data: 0.31MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cjzpj17bjz_gf_form_view: Data: 1.52MB + Index: 0.59MB + Engine InnoDB
wp_cjzpj17bjz_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cjzpj17bjz_options: Data: 1.45MB + Index: 0.17MB + Engine InnoDB
wp_cjzpj17bjz_postmeta: Data: 22.55MB + Index: 2.92MB + Engine InnoDB
wp_cjzpj17bjz_posts: Data: 4.31MB + Index: 0.67MB + Engine InnoDB
wp_cjzpj17bjz_redirection_404: Data: 1.02MB + Index: 0.11MB + Engine InnoDB
wp_cjzpj17bjz_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cjzpj17bjz_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_cjzpj17bjz_redirection_logs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_cjzpj17bjz_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_rg_form_meta: Data: 0.36MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_rg_form_view: Data: 1.52MB + Index: 0.52MB + Engine InnoDB
wp_cjzpj17bjz_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cjzpj17bjz_rg_lead: Data: 0.30MB + Index: 0.06MB + Engine InnoDB
wp_cjzpj17bjz_rg_lead_detail: Data: 1.52MB + Index: 1.05MB + Engine InnoDB
wp_cjzpj17bjz_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_rg_lead_meta: Data: 0.20MB + Index: 0.28MB + Engine InnoDB
wp_cjzpj17bjz_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cjzpj17bjz_sl_setting: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_sl_tag: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cjzpj17bjz_store_locator: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cjzpj17bjz_terms: Data: 0.42MB + Index: 0.44MB + Engine InnoDB
wp_cjzpj17bjz_term_relationships: Data: 0.33MB + Index: 0.16MB + Engine InnoDB
wp_cjzpj17bjz_term_taxonomy: Data: 0.47MB + Index: 0.47MB + Engine InnoDB
wp_cjzpj17bjz_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_cjzpj17bjz_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_cjzpj17bjz_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cjzpj17bjz_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cjzpj17bjz_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cjzpj17bjz_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cjzpj17bjz_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_cjzpj17bjz_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_cjzpj17bjz_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cjzpj17bjz_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_cjzpj17bjz_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cjzpj17bjz_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cjzpj17bjz_wfBadLeechers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_wfBlockedIPLog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_wfBlocks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cjzpj17bjz_wfBlocksAdv: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_wfConfig: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_wfCrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_wfFileMods: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_wfHits: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cjzpj17bjz_wfHoover: Data: 0.31MB + Index: 0.06MB + Engine InnoDB
wp_cjzpj17bjz_wfIssues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_wfLeechers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_wfLockedOut: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_wfLocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_wfLogins: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cjzpj17bjz_wfNet404s: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cjzpj17bjz_wfReverseCache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_wfScanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_wfStatus: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_cjzpj17bjz_wfThrottleLog: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cjzpj17bjz_wfVulnScanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cjzpj17bjz_yoast_seo_links: Data: 1.03MB + Index: 0.16MB + Engine InnoDB
wp_cjzpj17bjz_yoast_seo_meta: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

amn_exact-metrics: 1
attachment: 3171
custom_css: 1
customize_changeset: 9
easy-pricing-table: 6
mc4wp-form: 1
ml-slide: 184
ml-slider: 121
nav_menu_item: 28
oembed_cache: 8
page: 169
post: 17
product: 73
revision: 54
shop_order: 11
wp_block: 15

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Gravity Forms: by rocketgenius – 2.4.17
Akismet Anti-Spam: by Automattic – 4.1.3
Gmail SMTP: by naa986 – 1.1.9
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 6.0.2
Gravity Forms MailChimp Add-On: by rocketgenius – 4.6
Gutenberg: by Gutenberg Team – 7.6.0
MC4WP: Mailchimp for WordPress: by ibericode – 4.7.5
MetaSlider: by Team Updraft – 3.15.3
Print, PDF & Email by PrintFriendly: by Print
PDF
& Email by PrintFriendly – 3.14.7

Redirection: by John Godley – 4.7
Shortcodes Ultimate: by Vladimir Anokhin – 5.7.0
Storefront Footer Bar: by WooThemes – 1.0.4
Storefront Powerpack: by WooCommerce – 1.5.0
WooCommerce Stripe Gateway: by WooCommerce – 4.3.2 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 4.0.0
Yoast SEO: by Team Yoast – 13.2 – Not tested with the active version of WooCommerce
Smush: by WPMU DEV – 3.4.2

### Inactive Plugins (1) ###

Woo Stickers by Webline: by Weblineindia – 1.1.2

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (4) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.6.4
WP Engine Seamless Login Plugin: by WP Engine – 1.5.3
WP Engine Security Auditor: by wpengine – 1.0.8
WP Engine System: by WP Engine – 4.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: ❌ Page not set
Cart: #5 - /my-account/cart/
Checkout: #6 - /my-account/checkout/
My account: #7 - /my-account/
Terms and conditions: #3079 - /my-account/terms-and-conditions/

### Theme ###

Name: Homestore
Version: 2.0.32
Author URL: https://woocommerce.com
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 2.5.5
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: homestore/woocommerce/single-product/title.php

### Action Scheduler ###

Complete: 28
Oldest: 2020-02-12 14:24:57 -0500
Newest: 2020-03-10 15:34:25 -0400

Pending: 2
Oldest: 2020-03-11 15:27:49 -0400
Newest: 2020-03-11 15:27:49 -0400

</details>

**Comment by jeffstieler** [comment]
Thanks for the report @GlennMartin1.

Action Scheduler was moved to a different directory in https://github.com/woocommerce/woocommerce/pull/25404, but WC 4.0.0 should be looking in the new directory.

Does the error reoccur if you reactivate WooCommerce? If so, can you provide the full stack trace from the error?

**Comment by GlennMartin1** [comment]
I've reactivated WooCommerce, and everything appears 100% fine. 

> If so, can you provide the full stack trace from the error?

Sorry - not a developer, and I don't even know what you mean. I'll try, if you wish to explain.

**Comment by jeffstieler** [comment]
> I've reactivated WooCommerce, and everything appears 100% fine.

Great! It's likely that the new WooCommerce files weren't in play yet due to caching.

> Sorry - not a developer, and I don't even know what you mean. I'll try, if you wish to explain.

I was referring to copy-pasting more of the error log (you'd see the words "stack trace" in there). No need since your store is trouble free now.

**Comment by GlennMartin1** [comment]
@jeffstieler  I just updated five other sites to WooCommerce 4.0.0 with no issues. Not sure what was up with the first one.

Thanks!
