### ISSUE TITLE
[feature] Theming WooCommerce SASS (variables)

### ISSUE THREAD

**Issue by luukskeur** [woocommerce/woocommerce#25873]
**Description**
Reading the [docs](https://docs.woocommerce.com/document/css-structure/#section-2) WooCommerce tends to recommend to 1. override the CSS you need and load WC styling or 2. dequeue WC styling and create your own based on the defaults. 
However, in [another issue](https://github.com/woocommerce/woocommerce/pull/24822) I see the SASS makes use of variables with a purpose (even though it wasn't on the table a [few years earlier](https://github.com/woocommerce/woocommerce/pull/17653)).

Since I (for example) do want the WC styling but just want some colors or sizes adjusted I'd like that it can be overwritten by variables. Also to purge unused WC styling and just load the styles I need since the WC styling is 65kb+. For example: I removed the review comments feature but the CSS is still loaded.
So, I was wondering if it could be possible to make more use of variables and make the SASS a bit more dynamic, not just for theming but also for performance.

**Possible solution**
1. Namespacing all variables to prevent conflicts (with eq [Bootstrap](https://github.com/twbs/bootstrap/blob/master/scss/_variables.scss))
2. Create more variables for not just colors but also sizing, borders and shadows.
3. Convert parts of the SASS as optional features, enabled/disabled [by variables](https://github.com/twbs/bootstrap/blob/master/scss/_variables.scss#L202-L217).

**Describe alternatives you've considered**
1. Disabling all WC styling and re-create my own based on the defaults. Issue: New CSS for features and updates will need to be re-created on each update.
2. Overwriting WC styles with custom CSS. Issue: Duplicated CSS, all WC CSS is still loaded (performance) and the CSS structure could change in updates.

----
Looking forward to the ideas and discussion! I could create a basic PR to show the concept.

**Comment by juliaamosova** [comment]
Hi @luukskeur,

Thank you for taking the time to share this idea, we really appreciate your help. 

While this is clearly a great improvement, we won’t be able to tackle it in the upcoming weeks. We’re going to add it to our backlog where it will be considered for future releases.

**Comment by luukskeur** [comment]
Hi @juliaamosova, thanks for your reply!

I understand this is a big thing (if it's even considered) and it isn't easy to create in short term. Should I publish it at https://ideas.woocommerce.com/ also? How and should and can, I contribute to this specific task?

Thanks!

**Comment by barryhughes** [comment]
Closing in favor of #29574 (see also the recent discussion in #29575). I think this will ultimately address the main concern here, but let me know if I'm mistaken and we can re-evaluate.
