### ISSUE TITLE
Call to undefined method ActionScheduler_DBLogger::unhook_stored_action()

### ISSUE THREAD

**Issue by snelweg** [woocommerce/woocommerce#25877]
after upgrading to WC 4.0

`2020-03-11T12:17:20+00:00 CRITICAL Uncaught Error: Call to undefined method ActionScheduler_DBLogger::unhook_stored_action() in /home/xx/domains/xx.xxx/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/Runner.php:99
Stack trace:
#0 /home/xx/domains/xx.xxx/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(215): Action_Scheduler\Migration\Runner->migrate_actions(Array)
#1 /home/xx/domains/xx.xxx/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/data-stores/ActionScheduler_HybridStore.php(150): ActionScheduler_HybridStore->migrate(Array)
#2 /home/xx/domains/xx.xxx/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionScheduler_QueueCleaner.php(46): ActionScheduler_HybridStore->query_actions(Array)
#3 /home/xx/domains/xx.xxx/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/ActionSchedu in /home/xx/domains/xx.xxx/public_html/wp-content/plugins/woocommerce/packages/action-scheduler/classes/migration/Runner.php op de lijn 99`

`Versie van WooCommerce:		4.0.0
WooCommerce REST API-pakket:		 1.0.7 /home/xx/domains/xx.xxx/public_html/wp-content/plugins/woocommerce/packages/woocommerce-rest-api
WooCommerce Blocks-pakket:		 2.5.14 /home/xx/domains/xx.xxx/public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/
Action Scheduler-pakket:		 3.1.2 /home/xx/domains/xx.xxx/public_html/wp-content/plugins/woocommerce/packages/action-scheduler
WooCommerce Admin-pakket:		 1.0.0 /home/xx/domains/xx.xxx/public_html/wp-content/plugins/woocommerce-admin
Logmap beschrijfbaar:		 /home/xx/domains/xx.xxx/public_html/wp-content/uploads/wc-logs/
Versie van WordPress:		5.3.2
WordPress multisite:		–
WordPress geheugenlimiet:		2 GB
WordPress debug-modus:		–
WordPress cron:		
Taal:		nl_NL
Externe object-cache:		–
Serveromgeving
Serverinformatie:		Apache/2
PHP-versie:		7.3.12
PHP post max size:		2 GB
PHP time limit:		120
PHP max input vars:		1000
cURL Versie:		7.62.0, OpenSSL/1.0.2k
SUHOSIN geïnstalleerd:		–
MySQL-versie:		10.2.27-MariaDB-cll-lve
Max upload size:		2 GB
Standaard tijdzone is UTC:		
fsockopen/cURL:		
SoapClient:		
DOMDocument:		
GZip:		
Multibyte string:		
Remote post:		
Remote get:		
Database
Versie WooCommerce-database:		3.9.3
Prefix database	 	wp_
Totale databasegrootte	 	197.81MB
Database datagrootte	 	145.05MB
Database index grootte	 	52.76MB
wp_woocommerce_sessions	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies	 	Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_order_items	 	Data: 0.60MB + Index: 0.30MB + Engine MyISAM
wp_woocommerce_order_itemmeta	 	Data: 2.97MB + Index: 2.24MB + Engine MyISAM
wp_woocommerce_tax_rates	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
sib_model_contact	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions	 	Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_aws_cache	 	Data: 1.48MB + Index: 0.00MB + Engine MyISAM
wp_aws_index	 	Data: 4.52MB + Index: 0.00MB + Engine InnoDB
wp_berocket_termmeta	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_blc_filters	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_blc_instances	 	Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_blc_links	 	Data: 0.20MB + Index: 0.03MB + Engine MyISAM
wp_blc_synch	 	Data: 0.08MB + Index: 0.06MB + Engine MyISAM
wp_cart_notices	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta	 	Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_comments	 	Data: 14.22MB + Index: 12.18MB + Engine MyISAM
wp_dlm_order	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dlm_order_customer	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_dlm_order_item	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_dlm_order_transaction	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_dlm_session	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_download_log	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_eum_logs	 	Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_expm_maker	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_expm_maker_pages	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_failed_jobs	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_followup_coupons	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs	 	Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers	 	Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts	 	Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders	 	Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes	 	Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs	 	Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders	 	Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking	 	Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history	 	Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories	 	Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_followup_order_items	 	Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gdpr_consent	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_groups_capability	 	Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_groups_group	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_groups_group_capability	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_groups_user_capability	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_groups_user_group	 	Data: 0.01MB + Index: 0.04MB + Engine MyISAM
wp_g_aths_plugin	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ip_geo_block_cache	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ip_geo_block_logs	 	Data: 0.09MB + Index: 0.02MB + Engine MyISAM
wp_ip_geo_block_stat	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_itro_plugin_field	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_itro_plugin_option	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_lockdowns	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_login_fails	 	Data: 0.16MB + Index: 0.06MB + Engine MyISAM
wp_mailchimp_carts	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mobileassistant_accounts	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mobileassistant_devices	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mobileassistant_failed_login	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mobileassistant_push_settings	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mobileassistant_session_keys	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mobileassistant_users	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mollie_pending_payment	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nb_data	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nb_nottypes	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_news_announcement	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options	 	Data: 3.71MB + Index: 0.32MB + Engine MyISAM
wp_popup_manager	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_popup_manager_templates	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_postmeta	 	Data: 21.78MB + Index: 8.84MB + Engine MyISAM
wp_posts	 	Data: 17.96MB + Index: 14.86MB + Engine MyISAM
wp_pps_countries	 	Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_pps_popup	 	Data: 0.55MB + Index: 0.00MB + Engine MyISAM
wp_pps_popup_show_categories	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ps_exclude	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ps_postmeta	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_ps_posts	 	Data: 0.20MB + Index: 0.06MB + Engine MyISAM
wp_ps_product_sku	 	Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_queue	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_redirection_404	 	Data: 1.05MB + Index: 0.26MB + Engine MyISAM
wp_redirection_groups	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_redirection_items	 	Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_redirection_logs	 	Data: 0.13MB + Index: 0.04MB + Engine MyISAM
wp_sfa_abandoned_carts	 	Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_sgpb_subscribers	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sgpb_subscription_error_log	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sp_email_logs	 	Data: 7.52MB + Index: 0.02MB + Engine InnoDB
wp_stream	 	Data: 0.76MB + Index: 0.58MB + Engine MyISAM
wp_stream_meta	 	Data: 2.68MB + Index: 1.47MB + Engine MyISAM
wp_termmeta	 	Data: 0.08MB + Index: 0.05MB + Engine MyISAM
wp_terms	 	Data: 0.04MB + Index: 0.09MB + Engine MyISAM
wp_term_relationships	 	Data: 1.14MB + Index: 2.11MB + Engine MyISAM
wp_term_taxonomy	 	Data: 0.07MB + Index: 0.06MB + Engine MyISAM
wp_usermeta	 	Data: 0.29MB + Index: 0.18MB + Engine MyISAM
wp_users	 	Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_vtwpr_purchase_log	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_vtwpr_purchase_log_product	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_vtwpr_purchase_log_product_rule	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_notes	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup	 	Data: 0.33MB + Index: 0.17MB + Engine InnoDB
wp_wc_download_log	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup	 	Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup	 	Data: 0.36MB + Index: 0.25MB + Engine InnoDB
wp_wc_order_stats	 	Data: 0.13MB + Index: 0.14MB + Engine InnoDB
wp_wc_order_tax_lookup	 	Data: 0.17MB + Index: 0.11MB + Engine InnoDB
wp_wc_product_meta_lookup	 	Data: 0.20MB + Index: 0.34MB + Engine InnoDB
wp_wc_tax_rate_classes	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_webhooks	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfBlockedIPLog	 	Data: 0.18MB + Index: 0.14MB + Engine MyISAM
wp_wfBlocks7	 	Data: 0.33MB + Index: 0.30MB + Engine InnoDB
wp_wfConfig	 	Data: 2.20MB + Index: 0.02MB + Engine MyISAM
wp_wfCrawlers	 	Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wfFileChanges	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfFileMods	 	Data: 2.49MB + Index: 0.49MB + Engine MyISAM
wp_wfHits	 	Data: 6.19MB + Index: 1.15MB + Engine MyISAM
wp_wfHoover	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfIssues	 	Data: 0.08MB + Index: 0.02MB + Engine MyISAM
wp_wfKnownFileList	 	Data: 1.34MB + Index: 0.15MB + Engine MyISAM
wp_wfLiveTrafficHuman	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfLocs	 	Data: 0.04MB + Index: 0.01MB + Engine MyISAM
wp_wfLogins	 	Data: 0.11MB + Index: 0.04MB + Engine MyISAM
wp_wfls_2fa_secrets	 	Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfNotifications	 	Data: 0.04MB + Index: 0.01MB + Engine MyISAM
wp_wfPendingIssues	 	Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wfReverseCache	 	Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_wfSNIPCache	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfStatus	 	Data: 11.54MB + Index: 2.22MB + Engine MyISAM
wp_wfTrafficRates	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_recommendations	 	Data: 0.13MB + Index: 0.03MB + Engine MyISAM
wp_woocommerce_session_activity	 	Data: 0.08MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_shipping_flat_rate_boxes	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfront_ure_login_redirect	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpfront_ure_options	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wplc_chat_msgs	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_chat_sessions	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_offline_messages	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplc_webhooks	 	Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wplnst_scans	 	Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wplnst_scans_objects	 	Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wplnst_urls	 	Data: 0.02MB + Index: 0.05MB + Engine MyISAM
wp_wplnst_urls_locations	 	Data: 0.04MB + Index: 0.03MB + Engine MyISAM
wp_wplnst_urls_locations_att	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wplnst_urls_status	 	Data: 0.10MB + Index: 0.04MB + Engine MyISAM
wp_wpml_mails	 	Data: 32.16MB + Index: 0.04MB + Engine MyISAM
wp_wrd_discounts	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wrd_sent_coupons	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yith_wcwl	 	Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_yith_wcwl_lists	 	Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_yoast_seo_links	 	Data: 0.04MB + Index: 0.02MB + Engine MyISAM
wp_yoast_seo_meta	 	Data: 1.41MB + Index: 1.70MB + Engine MyISAM
wp_ywrr_email_blocklist	 	Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ywrr_email_schedule	 	Data: 0.02MB + Index: 0.01MB + Engine MyISAM
Post type aantal
announcement	 	5
attachment	 	2316
carts	 	21
custom_css	 	4
encyclopedia	 	13
feature	 	1
flamingo_contact	 	232
flamingo_inbound	 	51
follow_up_email	 	6
glossary	 	14
i-agree-popup	 	1
jetpack-portfolio	 	1
jetpack_migration	 	2
jp_img_sitemap	 	2
jp_img_sitemap_index	 	1
jp_sitemap	 	1
jp_sitemap_master	 	1
jp_vid_sitemap	 	1
nav_menu_item	 	101
oembed_cache	 	27
otw-portfolio	 	1
page	 	54
pf_contact	 	4
popup	 	1
popupbuilder	 	1
popup_theme	 	6
post	 	36
product	 	632
product_variation	 	998
project	 	4
projects	 	1
revision	 	578
scheduled-action	 	844
shop_coupon	 	477
shop_order	 	1313
shop_order_refund	 	57
slide	 	3
ultimate_slider	 	1
user_request	 	5
vgwc	 	1
warranty_request	 	2
wc_product_tab	 	18
woocarousel	 	1
wp-booklet2	 	1
wpb_wtm_tab	 	4
wpcf7_contact_form	 	3
wpforms	 	1
yith-wcet-etemplate	 	1
yith_popup	 	1
yith_price_rule	 	2
ywar_reviews	 	8
ywcm_message	 	3
ywrac_cart	 	6
Beveiliging
Beveiligde verbinding (HTTPS):		
Verberg fouten voor bezoekers		
Actieve plugins (61)
Advanced Cron Manager	 	door BracketSpace – 2.3.10
Advanced Woo Search	 	door ILLID – 1.96 – Niet getest met de actieve versie van WooCommerce
Akismet Anti-Spam	 	door Automattic – 4.1.3
Klassieke editor	 	door WordPress-bijdragers – 1.5
Code Prettify	 	door Kaspars Dambis – 1.4.2
Coming Soon Product for WooCommerce	 	door Terry Tsang – 1.0.0 – Niet getest met de actieve versie van WooCommerce
Contact Form 7	 	door Takayuki Miyoshi – 5.1.7
Customer Reviews for WooCommerce	 	door ivole – 3.98 – Niet getest met de actieve versie van WooCommerce
Download Monitor	 	door Never5 – 4.4.2
Encyclopedia Lite	 	door Dennis Hoppe – 1.7.33
EU Cookie Law	 	door Alex Moss, Marco Milesi – 3.1.1
Flamingo	 	door Takayuki Miyoshi – 2.1.1
Font Awesome 4 Menus	 	door New Nine Media – 4.7.0
Glossary	 	door Codeat – 1.8.9
Media Deduper	 	door Cornershop Creative – 1.5.3
Menu Icons	 	door ThemeIsle – 0.12.2
Mobile Assistant Connector	 	door eMagicOne – 2.0.1
Mollie Payments for WooCommerce	 	door Mollie – 5.4.2 – Niet getest met de actieve versie van WooCommerce
Perfect WooCommerce Brands	 	door Alberto de Vera Sevilla – 1.7.9
WooCommerce Pushover Integration	 	door Shop Plugins – 1.0.16
Redirection	 	door John Godley – 4.7
Regenerate Thumbnails	 	door Alex Mills (Viper007Bond) – 3.1.3
Tawk.to Live Chat	 	door Tawkto – 0.4.1
VG WooCarousel	 	door VinaWebSolutions – 1.3 – Niet getest met de actieve versie van WooCommerce
Abandoned Cart Reports For WooCommerce	 	door Small Fish Analytics – 2.6.0 – Niet getest met de actieve versie van WooCommerce
WooCommerce - List Products by Tags	 	door Remi Corson – 1.0 – Niet getest met de actieve versie van WooCommerce
WooCommerce Weight Based Shipping	 	door weightbasedshipping.com – 5.3.3.1 – Niet getest met de actieve versie van WooCommerce
WooCommerce Order Pending To Cancelled Email	 	door Fresh-Media – 1.0.0 – Niet getest met de actieve versie van WooCommerce
Shipping Method Display Style for WooCommerce	 	door Thedotstore – 3.5 – Niet getest met de actieve versie van WooCommerce
Shipping Method Display Style for WooCommerce	 	door Thedotstore – 3.5 – Niet getest met de actieve versie van WooCommerce
WooCommerce Admin	 	door WooCommerce – 1.0.0 – Niet getest met de actieve versie van WooCommerce
WooCommerce Auto Restore Stock	 	door Gerhard Potgieter – 1.0.1 – Niet getest met de actieve versie van WooCommerce
WooCommerce Bulk Stock Management	 	door WooCommerce – 2.2.8 – Niet getest met de actieve versie van WooCommerce
WooCommerce Cart Notices	 	door SkyVerge – 1.7.1 – Niet getest met de actieve versie van WooCommerce
WooCommerce Cart Reports	 	door WooCommerce – 1.1.18 – Niet getest met de actieve versie van WooCommerce
WooCommerce Composite Products	 	door SomewhereWarm – 3.11.1 – Niet getest met de actieve versie van WooCommerce
WooCommerce Cost of Goods	 	door SkyVerge – 2.4.1 – Niet getest met de actieve versie van WooCommerce
WooCommerce Display Products by Tags	 	door Sebs Studio – 1.0.0 – Niet getest met de actieve versie van WooCommerce
Follow-Up Emails	 	door WooCommerce – 4.8.4 – Niet getest met de actieve versie van WooCommerce
WooCommerce Logistic	 	door agenciamagma, Carlos Cardoso Dias – 0.0.1 – Niet getest met de actieve versie van WooCommerce
WooCommerce Min/Max Quantities	 	door WooCommerce – 2.4.10 – Niet getest met de actieve versie van WooCommerce
WooCommerce MyParcel	 	door Adem Demir – 3.2.0 – Niet getest met de actieve versie van WooCommerce
WooCommerce Out of Stock Message	 	door Kharis Sulistiyono – 1.0 – Niet getest met de actieve versie van WooCommerce
WooCommerce Product Categories Selection	 	door PluginForage.com – 2.0 – Niet getest met de actieve versie van WooCommerce
Role Based Price For WooCommerce	 	door Varun Sridharan – 3.3.6 – Niet getest met de actieve versie van WooCommerce
WooCommerce Sequential Order Numbers Pro	 	door SkyVerge – 1.11.2 – Niet getest met de actieve versie van WooCommerce
WooCommerce Flat Rate Box Shipping	 	door WooCommerce – 2.0.3 – Niet getest met de actieve versie van WooCommerce
WooCommerce Shortcodes	 	door WooThemes, Claudio Sanches – 1.0.0 – Niet getest met de actieve versie van WooCommerce
WooCommerce Tab Manager	 	door SkyVerge – 1.8.2 – Niet getest met de actieve versie van WooCommerce
WooCommerce Waitlist	 	door Neil Pie – 1.5.6 – Niet getest met de actieve versie van WooCommerce
WooCommerce Warranty Requests	 	door WooCommerce – 1.8.7 – Niet getest met de actieve versie van WooCommerce
WooCommerce	 	door Automattic – 4.0.0
Wordfence Security	 	door Wordfence – 7.4.6
Yoast SEO	 	door Team Yoast – 13.2 – Niet getest met de actieve versie van WooCommerce
WP Image Zoom	 	door SilkyPress – 1.40
WP Broken Link Status Checker	 	door Pau Iglesias, SeedPlugins – 1.0.6
WP Mail Logging	 	door MailPoet – 1.9.5
WP Mail SMTP	 	door WPForms – 1.8.1
WP-Matomo	 	door André Bräkling – 1.0.22
Yandex Metrica	 	door Mustafa Uysal – 1.8.1
YITH WooCommerce Wishlist	 	door YITH – 3.0.9
Inactieve plugins (24)
Advanced AJAX Product Filters for WooCommerce	 	door BeRocket – 1.4.1.8 – Niet getest met de actieve versie van WooCommerce
All Meta Stats Yoast SEO Addon	 	door NetAttingo Technologies – 1.0.0
Broken Link Checker	 	door ManageWP – 1.11.11
Coming Soon Page & Maintenance Mode by SeedProd	 	door SeedProd – 5.1.0
Custom Product Tabs for WooCommerce	 	door YIKES, Inc. – 1.7.0
Debug Bar	 	door wordpressdotorg – 1.0
Disable REST API	 	door Dave McHale – 1.5
Easy Updates Manager	 	door Easy Updates Manager Team – 9.0.1
Error Log Monitor	 	door Janis Elsts – 1.6.9
Hide My WP Ghost Lite	 	door WPPlugins - WordPress Security Plugins – 3.5.02
Mailjet for WordPress	 	door Mailjet SAS – 5.2.1
Min and Max Quantity for WooCommerce	 	door BeRocket – 1.2.12.3 – Niet getest met de actieve versie van WooCommerce
Popup Builder	 	door Sygnoos – 3.63
Post SMTP	 	door Yehuda Hassine – 2.0.11
SparkPost	 	door SparkPost – 3.2.0
Trustpilot-reviews	 	door Trustpilot – 2.5.800 – Niet getest met de actieve versie van WooCommerce
WC - APG Weight Shipping	 	door Art Project Group – 2.3.1.4 – Niet getest met de actieve versie van WooCommerce
WooCommerce Advanced Product Quantities	 	door WP BackOffice – 2.1.9 – Niet getest met de actieve versie van WooCommerce
Woocommerce Blocker	 	door Thedotstore – 1.8.4 – Niet getest met de actieve versie van WooCommerce
WooCommerce PickingPal	 	door PickingPal – 1.3.0 – Niet getest met de actieve versie van WooCommerce
WooCommerce Product SKU Generator	 	door SkyVerge – 2.4.4
WP fail2ban	 	door Charles Lecklider – 4.2.7.1
WP Log Viewer	 	door Maxwell Berkel – 1.2.1
YITH WooCommerce Zoom Magnifier	 	door YITH – 1.3.15 – Niet getest met de actieve versie van WooCommerce
Moet plugins gebruiken (2)
installatron_hide_status_test.php	 	door –
p3-profiler.php	 	door –
Instellingen
API geactiveerd:		
Forceer SSL:		
Valuta		EUR (€)
Positie van valutasymbool		left_space
Duizendtalscheiding		,
Decimaalscheiding		.
Aantal decimalen		2
Taxonomieën: Producttypen		composite (composite), external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomieën: productzichtbaarheid		exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
Gekoppeld aan WooCommerce.com:		–
WooCommerce-pagina's
Winkelbasis:		#1 - /
Winkelmand:		#2 - /dewinkel/winkelmand
Afrekenen:		#3 - /dewinkel/afrekenen
Mijn account:		#4 - /mijn-account
Algemene voorwaarden:		#10395 - /algemene-voorwaarden
Thema
Naam:		Storefront child
Versie:		2.2.8
URL van de maker:		https://woocommerce.com/
Subthema:		
Hoofdthema naam:		Storefront
Hoofdthema versie:		2.5.5
URL van de maker van het hoofdthema:		https://woocommerce.com/
WooCommerce Support:		
Templates
Overschrijvingen:	 	–
Er heeft zich een kritische fout voorgedaan op je website. Controleer je postvak-in van je beheer-e-mailadres voor instructies.

Lees meer over probleemoplossing in WordPress.`

**Comment by rrennick** [comment]
> Follow-Up Emails door WooCommerce – 4.8.4

@snelweg You need to either deactivate FUE or update to a recent version.

**Comment by snelweg** [comment]
wow, thank you! That did the trick.
