### ISSUE TITLE
Problem about WC Admin

### ISSUE THREAD

**Issue by rodolphebertozzo** [woocommerce/woocommerce#25871]
After update 4.0, when I open WC Admin (implemented in the last update), the different dashboards take a very long time to load. Is this normal? Do you plan to work on the code afterwards to optimize the loading?
Another question, when will the translations of WC Admin be available?

**Comment by peterfabian** [comment]
Hi @rodolphebertozzo , thanks for your feedback!

Yes, we do plan to optimize the dashboard after the initial release. 
As for translations, please follow the community contributions at https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/. You can even add your translations if you would like to help the community.
