### ISSUE TITLE
Minor bug in the API response from the woocommerce.com

### ISSUE THREAD

**Issue by rohanvakharia** [woocommerce/woocommerce#25872]
**Describe the bug**
In the response to the suggestions request woocommerce.com responding icon images URL with double slash.

**To Reproduce**
1. Go to 'https://woocommerce.com/wp-json/wccom/marketplace-suggestions/1.0/suggestions.json'
2. See any product icon URL

**Screenshots**
![image](https://user-images.githubusercontent.com/6183560/76399903-73b1b080-63a5-11ea-8b15-7feb290338a8.png)

**Expected behavior**
There should be only one slash.

**WordPress Environment**
5.3.2

**Comment by peterfabian** [comment]
Thanks for reporting, I notified the team that produces the JSON file.

**Comment by Dan-Q** [comment]
This has now been fixed at the source.
