### ISSUE TITLE
Deprecated image size not removed in 4.0.0

### ISSUE THREAD

**Issue by wayheming** [woocommerce/woocommerce#25879]
Hello, Woocommerce team, thank you for the new 4.0 update.
I have a question about the sizes of pictures that should have been deleted in 4.0 but are still in the code.

`woocommerce/includes/class-woocommerce.php`

```php
/**
  * Legacy image sizes.
 *
 * @deprecated These sizes will be removed in 4.0.
 */
add_image_size( 'shop_catalog', $thumbnail['width'], $thumbnail['height'], $thumbnail['crop'] );
add_image_size( 'shop_single', $single['width'], $single['height'], $single['crop'] );
add_image_size( 'shop_thumbnail', $gallery_thumbnail['width'], $gallery_thumbnail['height'], $gallery_thumbnail['crop'] );
```

**Comment by peterfabian** [comment]
Hi @wayheming 

We've decided to _not_ remove deprecated code at this point to have fewer breaking changes and thus hoped for fewer problems during 4.0. 
We plan to remove it in the following major release which would clean up more methods, functions and deprecated APIs.

**Comment by wayheming** [comment]
@peterfabian ok thank you

**Comment by danielcharrua** [comment]
Hello! v5.0 was released but the legacy image sizes are still there, any reason for why they are not removed yet?
Thank you.
