### ISSUE TITLE
[4.0] Scheduled DB updates are stuck on pending 

### ISSUE THREAD

**Issue by unster** [woocommerce/woocommerce#25870]
## Prerequisites
WordPress 5.3.2 installed (Polish language selected)
WooCommerce 3.9.3 installed

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Update WooCommerce 3.9.3 to WooCommerce 4.0
2. Open Scheduled Actions under WooCommerce > Status 
3. Notice pending jobs & lack of "run" action
4. Change site language to English, re-open Status page
5. "run" action is now available & but doesn't execute any pending job

## Expected/actual behavior

When I follow those steps, I see...
> 9 pending jobs i.e.:
cwg_sync_instock_data ('pid' => array ( 0 => '11298', 1 => '11600', 2 => '12452', )), 
woocommerce_run_update_callback (0 => 'wc_admin_update_0201_order_status_index')
> after using workaround to change language to English I see "Run" option after each line
> when clicking "Run" - nothing happens

I was expecting to see...
> empty list of pending jobs, OR systematically decreasing list of pending jobs

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
`
### WordPress Environment ###

WC Version: 4.0.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.2
WC Admin Version: ✔ 1.0.0
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.1
PHP Version: 7.3.11-1+ubuntu18.04.1+deb.sury.org+1
PHP Post Max Size: 100 MB
PHP Time Limit: 600
PHP Max Input Vars: 20000
cURL Version: 7.58.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.20-MariaDB-1:10.3.20+maria~bionic-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.2
WC Database Prefix: wpNB_
Total Database Size: 92.61MB
Database Data Size: 72.27MB
Database Index Size: 20.34MB
wpNB_woocommerce_sessions: Data: 0.25MB + Index: 0.02MB + Engine InnoDB
wpNB_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpNB_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpNB_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpNB_woocommerce_order_items: Data: 0.38MB + Index: 0.13MB + Engine InnoDB
wpNB_woocommerce_order_itemmeta: Data: 3.52MB + Index: 3.03MB + Engine InnoDB
wpNB_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpNB_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpNB_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpNB_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpNB_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpNB_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpNB_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpNB_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpNB_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wpNB_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpNB_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpNB_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpNB_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpNB_aepc_custom_audiences: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpNB_aepc_logs: Data: 10.52MB + Index: 0.00MB + Engine InnoDB
wpNB_commentmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wpNB_comments: Data: 2.52MB + Index: 1.44MB + Engine InnoDB
wpNB_download_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpNB_es_deliverreport: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpNB_es_emaillist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpNB_es_notification: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpNB_es_sentdetails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpNB_ewwwio_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpNB_ewwwio_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpNB_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpNB_litespeed_img_optm: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpNB_litespeed_optimizer: Data: 0.20MB + Index: 0.03MB + Engine InnoDB
wpNB_logger_ginger: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpNB_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpNB_nxs_log: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wpNB_nxs_query: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpNB_options: Data: 3.52MB + Index: 0.30MB + Engine InnoDB
wpNB_postmeta: Data: 37.56MB + Index: 12.03MB + Engine InnoDB
wpNB_posts: Data: 7.52MB + Index: 1.20MB + Engine InnoDB
wpNB_sdm_downloads: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wpNB_SH_CD_SHORTCODES: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpNB_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpNB_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpNB_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpNB_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wpNB_terms_hit: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpNB_term_relationships: Data: 0.28MB + Index: 0.16MB + Engine InnoDB
wpNB_term_taxonomy: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wpNB_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpNB_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpNB_usermeta: Data: 1.52MB + Index: 0.52MB + Engine InnoDB
wpNB_users: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wpNB_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpNB_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpNB_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpNB_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpNB_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpNB_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpNB_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpNB_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpNB_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpNB_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpNB_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wpNB_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpNB_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpNB_woocommerce_tpay: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpNB_woocommerce_tpay_clients: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpNB_wrd_discounts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpNB_wrd_sent_coupons: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpNB_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpNB_yoast_seo_meta: Data: 0.50MB + Index: 0.00MB + Engine InnoDB
wpNB_ywrr_email_blocklist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpNB_ywrr_email_schedule: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 2
acf-field-group: 2
allegro_auction: 12
attachment: 176
carts: 6077
customize_changeset: 38
custom_css: 1
cwginstocknotifier: 27
dlm_download: 2
dlm_download_version: 2
es_template: 1
ff-customcode-item: 1
ff-options: 4
header_builder: 1
jetpack_migration: 2
landing-page: 1
mc4wp-form: 1
ml-slide: 8
ml-slider: 2
nav_menu_item: 6
oembed_cache: 9
page: 15
post: 7
postman_sent_mail: 250
product: 14
product-feed: 1
product_variation: 8
raccartlist: 478
racemailtemplate: 2
racmaillog: 552
racrecoveredorder: 46
revision: 16
sdm_downloads: 6
sendpress_list: 1
shipment: 428
shop_coupon: 17
shop_order: 1925
sptemplates: 3
sp_settings: 1
sp_template: 3
wbcr-snippets: 3
wc_zapier_feed: 1
wpcdt_countdown: 1
wpcf7_contact_form: 1
wpwautoposterlogs: 40

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

Advanced Custom Fields: by Elliot Condon – 5.8.8
Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro: by codewoogeek – 1.9.6 – Not tested with the active version of WooCommerce
Checkout Countdown for WooCommerce: by Puri.io – 3.0.4 – Not tested with the active version of WooCommerce
Contact Form 7: by Takayuki Miyoshi – 5.1.7
Custom Order Numbers for WooCommerce: by Tyche Softwares – 1.2.9 – Not tested with the active version of WooCommerce
Flexible Shipping: by WP Desk – 3.9.11 – Not tested with the active version of WooCommerce
Google Analytics Dashboard for WP (GADWP): by ExactMetrics – 5.3.10
HookMeUp – Additional Content for WooCommerce: by GetBowtied – 1.2.7 – Not tested with the active version of WooCommerce
Loco Translate: by Tim Whitlock – 2.3.1
MetaSlider: by Team Updraft – 3.15.3
Post SMTP: by Yehuda Hassine – 2.0.11
Product Catalog Feed by PixelYourSite: by PixelYourSite – 1.0.5 – Not tested with the active version of WooCommerce
Recover Abandoned Cart: by Fantastic Plugins – 21.9 – Not tested with the active version of WooCommerce
Shortcodes Ultimate: by Vladimir Anokhin – 5.7.0
WooCommerce Ultimate Box Product: by Progos – 1.2.0 – Not tested with the active version of WooCommerce
WooCommerce Checkout Optimization by Cartimize: by Cartimize – 1.0.4 – Not tested with the active version of WooCommerce
WooCommerce Blocks: by Automattic – 2.5.14
Advanced Order Export For WooCommerce: by AlgolPlus – 3.1.1 – Not tested with the active version of WooCommerce
WooCommerce Admin: by WooCommerce – 1.0.0 – Not tested with the active version of WooCommerce
WooCommerce Boost Sales Premium: by Andy Ha (villatheme.com) – 1.4.1 – Not tested with the active version of WooCommerce
WooCommerce Cart Reports: by WooCommerce – 1.2.2 – Not tested with the active version of WooCommerce
WooCommerce InPost: by WP Desk – 3.9.12
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.4.7
WooCommerce Product Reviews Pro: by SkyVerge – 1.15.2 – Not tested with the active version of WooCommerce
WooCommerce Review for Discount: by WooCommerce – 1.6.12 – Not tested with the active version of WooCommerce
Tpay WooCommerce payment module: by Tpay – 2.8.6 – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 4.0.0
WP Add Custom CSS: by Daniele De Santis – 1.1.5
YITH WooCommerce Review Reminder: by YITH – 1.6.4

### Inactive Plugins (15) ###

Maintenance: by WP Maintenance – 3.85
Nginx Helper: by rtCamp – 2.2.1
Perfmatters: by forgemedia – 1.4.8
PixelYourSite PRO: by PixelYourSite – 7.3.11 – Not tested with the active version of WooCommerce
Redis Object Cache: by Till Krüss – 1.5.6
WooCommerce Allegro: by WP Desk – 3.9.12 – Not tested with the active version of WooCommerce
WooCommerce Google Analytics Pro: by SkyVerge – 1.8.8 – Not tested with the active version of WooCommerce
WP Rocket: by WP Media – 3.4.4
WP Rocket | Cache Search Results: by WP Rocket Support Team –
WP Rocket | Disable SSL Certificate Validation: by WP Rocket Support Team –
WP Rocket | Enable Native Lazyload: by WP Rocket Support Team –
WPvivid Backup Plugin: by WPvivid Team – 0.9.35
YITH WooCommerce Review Reminder Premium: by YITH – 1.5.7 – Not tested with the active version of WooCommerce
Yoast SEO: WooCommerce: by Team Yoast – 12.5.1 – Not tested with the active version of WooCommerce
Yoast SEO Premium: by Team Yoast – 13.2

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: PLN (zł)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: box_product (box_product)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #4 - /
Cart: #5 - /?page_id=5
Checkout: #6 - /?page_id=6
My account: #7 - /?page_id=7
Terms and conditions: #171 - /?page_id=171

### Theme ###

Name: Shopkeeper Child 2915
Version: 2.9.15
Author URL: http:%20//www.getbowtied.com/
Child Theme: ✔
Parent Theme Name: Shopkeeper
Parent Theme Version: 2.9.10
Parent Theme Author URL: https://www.getbowtied.com/
WooCommerce Support: ✔

### Templates ###

Overrides: shopkeeper-child-2915/woocommerce/archive-product.php
shopkeeper-child-2915/woocommerce/cart/cross-sells.php
shopkeeper/woocommerce/cart/mini-cart.php
shopkeeper-child-2915/woocommerce/checkout/form-checkout.php
shopkeeper/woocommerce/checkout/form-coupon.php
shopkeeper/woocommerce/checkout/form-login.php
shopkeeper/woocommerce/content-product.php
shopkeeper/woocommerce/content-product_cat.php
shopkeeper/woocommerce/content-single-product.php
shopkeeper/woocommerce/global/quantity-input.php version 3.6.0 is out of date. The core version is 4.0.0
shopkeeper/woocommerce/global/sidebar.php
shopkeeper/woocommerce/global/wrapper-end.php
shopkeeper/woocommerce/global/wrapper-start.php
shopkeeper/woocommerce/loop/loop-end.php
shopkeeper/woocommerce/loop/loop-start.php
shopkeeper/woocommerce/loop/no-products-found.php
shopkeeper/woocommerce/myaccount/form-login.php
shopkeeper/woocommerce/order/form-tracking.php
shopkeeper/woocommerce/single-product/add-to-cart/simple.php
shopkeeper/woocommerce/single-product/product-image.php
shopkeeper/woocommerce/single-product/product-thumbnails.php
shopkeeper/woocommerce/single-product/tabs/tabs.php
shopkeeper/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

### Action Scheduler ###

Complete: 10
Oldest: 2020-01-06 10:15:04 +0100
Newest: 2020-02-06 21:35:20 +0100

Pending: 9
Oldest: 2020-02-06 22:51:30 +0100
Newest: 2020-03-11 08:15:26 +0100

Canceled: 1
Oldest: 2020-01-31 22:01:19 +0100
Newest: 2020-01-31 22:01:19 +0100
</details>

**Comment by antyhelion** [comment]
I had the same problem. I solved it like this:

1) I disabled all plug-ins except WooCommerce,
2) I changed the panel language to "English (United States)",
3) I refreshed the task list and clicked at each "Run".

**Comment by unster** [comment]
> I had the same problem. I solved it like this:
> 3. I refreshed the task list and clicked at each "Run".

Tried that, not working for me. I've updated reproduction steps.

**Comment by peterfabian** [comment]
Thanks for reporting, @unster . Are the jobs still pending for you? `Run` should run those jobs right away, unless there is some problem. Do you see anything in the logs? Can you please share the list of pending jobs?

Otherwise, there might be some recurrent jobs that are kept in pending status.

cc @rrennick

**Comment by rrennick** [comment]
> "run" action is now available & but doesn't execute any pending job

@unster How many of the `Run` action links did you try?

**Comment by unster** [comment]
@peterfabian @rrennick 
yes, the jobs are still pending
each click on "run" just reload the page
list of current jobs (same since creating the ticket): https://imgur.com/qUeuQEb

where can I get the logs to share?

**Comment by rrennick** [comment]
> where can I get the logs to share?

Could you enable `WP_DEBUG` and `WP_DEBUG_LOG` (if not enabled), click one of the run links then disable if debug logging wasn't enabled? The debug log is usually `wp-content/debug.log`.

**Comment by rrennick** [comment]
I downloaded and installed the Polish version of WooCommerce from WordPress.org. With that version active I'm able to run actions using the `Run` action link with the language set to either `Polski` or `English`.

**Comment by matthisamoto** [comment]
Having the same issues, `Run` does not print anything to the log for me.

**Comment by rrennick** [comment]
@matthisamoto You can reproduce the issue with only WooCommerce and one of the default themes active?

**Comment by matthisamoto** [comment]
@rrennick Yes.

**Comment by unster** [comment]
I've turned debug ON, but no debug.log file is being created. When created manually with 777 CHMOD, no data is being saved inside when clicking "run".

**Comment by rrennick** [comment]
Are you running `Non-Repeating` or `Recurring` actions?

**Comment by unster** [comment]
> Non-Repeating

Few post above I've provided screenshot of those pending actions: https://imgur.com/qUeuQEb

**Comment by matthisamoto** [comment]
<img width="1498" alt="Screen Shot 2020-03-11 at 2 03 37 PM" src="https://user-images.githubusercontent.com/547172/76453635-33e8ca00-63a1-11ea-8f12-efb3b0aaa1d4.png">

**Comment by rrennick** [comment]
Could one of you go to https://woocommerce.com/contact-us/ provide a reference to this ticket and submit login credentials so we can have a look?

**Comment by matthisamoto** [comment]
Mine is a local site currently in development.

**Comment by rrennick** [comment]
> Mine is a local site currently in development.

If you have WP CLI you can use `wp action-scheduler run` to run those.

**Comment by rrennick** [comment]
Are you trying to run these actions from WooCommerce -> Status -> Scheduled Actions or Tools -> Scheduled Actions ?

**Comment by matthisamoto** [comment]
WC Status

**Comment by rrennick** [comment]
@matthisamoto Try running one from Tools -> Scheduled Actions -> Pending.

**Comment by matthisamoto** [comment]
@rrennick Okay, that worked from Tools. What's the difference?

**Comment by rrennick** [comment]
@unster @matthisamoto Thanks so much for the quick turn around on feedback. I've created https://github.com/woocommerce/action-scheduler/issues/485 to address the issue and will close this one.

**Comment by matthisamoto** [comment]
Additional actions related to updating Product Data (that I imagine were dependent on the other actions completing) were also stalled and I was able to run them from the Scheduled Actions page under Tools.

**Comment by unster** [comment]
> @matthisamoto Try running one from Tools -> Scheduled Actions -> Pending.

Yep, that one worked for me as well :-) thanks!

**Comment by tsetend** [comment]
A user reported this problem here 2803898-zen.

It is a staging site and I disabled all the other plugins except WooCommerce. I switched to Twenty Twenty theme. Initiated the database update from **WooCommerce > Status > Tools**. The update is still in progress after a few hours:

![Screenshot](https://d.pr/i/xNZSNG+)
Screenshot: https://d.pr/i/xNZSNG

Pending scheduled action:

![Screenshot](https://d.pr/i/2JN0XP+)
Screenshot: https://d.pr/i/2JN0XP

**Comment by pgamaster** [comment]
Scheduled Actions don't run automatically, I run my shop on docker.

**Comment by Igcorreia** [comment]
Same here. I think everything is fine on my side but I have 902 pending.
