### ISSUE TITLE
Switch Payment from PayPal to COD doesn't apply extra fee

### ISSUE THREAD

**Issue by bortonecesario** [woocommerce/woocommerce#25888]
If i do an order and i select Paypal as payment method after i've clicked on place order button i'm redirected on Paypal for the authentication. If i close this page on woocommerce there is the order in Wait For Payment status.
If i send the link for pay the order to the customer like this:
http://bxxxxxxxxx.org/checkout/order-pay/580/?pay_for_order=true&key=wc_order_o1P4hpRbYiYlP

and the customer click on this link for pay the order. If the customer switch the payment method from PayPal to COD and the COD has the Extra Fee setted (as me 7.5€) this extra fee is not applied to the order. 

[Screenshoot.pdf](https://github.com/woocommerce/woocommerce/files/4320680/Screenshoot.pdf)

**Screenshots**
attached

**Expected behavior**
When the customer change the payment method from PayPal to COD if there are extra fee these must be added to the total costs

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WC Version: 4.0.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.2
WC Admin Version: ✔ 1.0.0
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: it_IT
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.0.33 - Consigliamo di usare PHP versione 7.2 o superiore per prestazioni e sicurezza maggiori. Come aggiornare la versione di PHP
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 100000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.44-MariaDB-cll-lve
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###
WC Database Version: 4.0.0

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.10.4
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

**Comment by juliaamosova** [comment]
Hi @bortonecesario,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/25777. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
