### ISSUE TITLE
Connect your store JITM can't be dismissed

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce#25889]
### Describe the bug
The JITM for connecting with WooCommerce.com is currently not dismissable and that could cause frustration for merchants who don't want to or need to connect. Not quite a bug but a usability issue. 

### To Reproduce
1. Go to a WooCommerce wp-admin dashboard for a store that's not yet connected to WooCommerce.com
2. See the JITM "Connect your store to WooCommerce.com to reveice extensions updates and support.
3. See issue that it can't be dismissed

### Expected behavior
We should use a class of JITM that can be dismissed, such as `notice is-dismissible notice-info` or add the X to dismiss to this class `updated woocommerce-message`.

### Scope / Impact
I think this will go a long way towards helping merchants maintain trust in our product. Not being able to dismiss a notice feels like you're being forced into something you may not necessarily want to do.

### Screenshots
<img width="1596" alt="Screen Shot 2020-03-11 at 11 25 59 AM" src="https://user-images.githubusercontent.com/5121465/76440026-435d1880-638b-11ea-922b-56bbf61d7dd5.png">

#### Desktop (please complete the following information):
- Mac OS 10.15.3
- Firefox 73.0.1

**Comment by juliaamosova** [comment]
Hi @elizaan36,

Thank you for taking the time to report this bug. I can reproduce it on my end. However, I think this notice shouldn't be there in the first place since it is now a part of WC Admin bar via `Inbox`. 

I see that we now have 2 identical notices:

![inbox](https://user-images.githubusercontent.com/19143190/76468572-a918c700-63c2-11ea-9109-5afb774091c6.jpg)

cc @timmyc @peterfabian for which one should be kept. AFAIK, the one provided by the WC Admin should remain.

**Comment by timmyc** [comment]
I concur that we should keep the wc-admin inbox notif and remove the legacy one. @pmcpinto any opinions here?

**Comment by pmcpinto** [comment]
> I concur that we should keep the wc-admin inbox notif and remove the legacy one. @pmcpinto any opinions here?

+1. Just for reference, that inbox notification it's the one with the best performance in terms of conv. rate.

**Comment by juliaamosova** [comment]
Thanks for the feedback @timmyc @pmcpinto! Looks like we should include it in 4.1. I am changing the priority to `high` and copying @vedanshujain as he is a Release Lead for 4.1.
