### ISSUE TITLE
WooCommerce 3.x support period?

### ISSUE THREAD

**Issue by marconett** [woocommerce/woocommerce#25897]
what does the future support for WooCommerce 3.x look like?
bugfix releases, only security releases, no new updates at all?

**Comment by uok** [comment]
why don't you update to Woo 4.x?

**Comment by juliaamosova** [comment]
Hi @marconett,

>what does the future support for WooCommerce 3.x look like?
bugfix releases, only security releases, no new updates at all?

These are good questions to ask. Currently, we have only one stream of development, so no fixes, even security ones will be released for any 3.X versions. Even if we released 3.9.4, most people would never see it in their plugin page, as 4.0 is newer. 

We will be releasing any bug fixes and security updates in 4.X versions. 

I am going to close this issue but please feel free to reply back if needed.
