### ISSUE TITLE
We would like to disable Woocommerce Admin in v 4.0

### ISSUE THREAD

**Issue by gbruzzo** [woocommerce/woocommerce#25911]
Hello all

in https://wordpress.org/support/topic/this-plugin-uninstalled-and-delete-but-still-showing-analytics-and-functionality/

it is suggested that 

`add_filter( 'woocommerce_admin_disabled', '__return_true' );`

is the filter to be added to functions.php  It does not seem to currently work though. 

We are certainly interested in the plugin's development, but are currently using external / Rest API based solutions and would like to avoid unnecessary duplication for now.

Cheers

**Comment by peterfabian** [comment]
Hi @gbruzzo , 

Others seem to have used the filter successfully, so maybe there was some problem with the code line not being executed in the file where you put it? Also, please check you don't have the plugin installed/active in parallel with WC 4.0.

**Comment by gbruzzo** [comment]
Hi @peterfabian 

Uh - will try switching off plugins and changing themes. 

Very odd though, have tried running this early in functions.php as well, with not changes (Analytics still appears in admin). 

Let me try and report back.

**Comment by gbruzzo** [comment]
Hi @peterfabian 

- just reinstalled the staging site, upgraded to 4.0 
- installed Storefront
- deactivated all plugins but WC

added 

`add_filter( 'woocommerce_admin_disabled', '__return_true' );`

to functions.php 

and nothing happens - e.g. the Analytics tab and functionality are still visible in Admin. 

Can you test on your side? 

Cheers

**Comment by gbruzzo** [comment]
Hi @peterfabian 

update - managed to make it work as plugin as per 
[Plugin](https://gist.github.com/joshuatf/006111b6f43c3ab3d2cad39e3443822b
)

Now we know we can disable the admin (though not the extra tables). 

Will keep monitoring development

**Comment by rrennick** [comment]
> to functions.php

The filter is called before the theme is loaded so it has to be added via a plugin.

**Comment by rodrigoprimo** [comment]
Thanks for sharing that you were able to disable WooCommerce Admin using the filter. Closing this issue since the problems was resolved.
