### ISSUE TITLE
Shipping to Switzerland doesn't show up when optional field is not filled in

### ISSUE THREAD

**Issue by webcrashpilot** [woocommerce/woocommerce#25912]
**Describe the bug**
After update to woocommerce 4.0 the field "billing_state" is mandatory for customers in Switzerland (checkout page where customers have to fill in the address). Only for customers in Switzerland but not for customers in Germany, Austria etc. If the field is not selected the customer gets the message "shipping method not selected".

Second problem, even if the required field for "billing_state" is selected, it is displayed as optionally.

Maybe it has something to do with the following update in woocomerce 4.0: 
"Tweak – Update ‚Country‘ to ‚Country / Region‘ label. #25530"

**To Reproduce**
1. Update woocommerce 4.0
2. Order a product go to the shopping cart / checkout page and enter an address, select country Switzerland
3. See problem

**Comment by juliaamosova** [comment]
Hi @webcrashpilot,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

My shipping setup for Switzerland:

<img width="1434" alt="Screen Shot 2020-03-13 at 11 36 52 AM" src="https://user-images.githubusercontent.com/19143190/76636340-425cf000-651f-11ea-8e7c-3509b2eff773.png">

Checkout page - no state is selected for Switzerland (marked as optional) - no shipping methods offered:

![sw1](https://user-images.githubusercontent.com/19143190/76636542-a384c380-651f-11ea-921e-cf1e5ca9c1c7.jpg)

Checkout page - the state is selected - shipping options are offered:

![sw2](https://user-images.githubusercontent.com/19143190/76636620-c1522880-651f-11ea-9a18-e3f9568b1bc1.jpg)

We’re going to prioritize working on this bug.

**Comment by webcrashpilot** [comment]
Hi, thank you very much.

 

Kind regards,

 

Alexander

 

Von: Julia Amosova [mailto:notifications@github.com] 
Gesendet: Freitag, 13. März 2020 16:44
An: woocommerce/woocommerce <woocommerce@noreply.github.com>
Cc: webcrashpilot <info@pfefferspray-store.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [woocommerce/woocommerce] Problem after update to woocommerce 4.0 (#25912)

 

Hi @webcrashpilot <https://github.com/webcrashpilot> ,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end.

My shipping setup for Switzerland:

 <https://user-images.githubusercontent.com/19143190/76636340-425cf000-651f-11ea-8e7c-3509b2eff773.png> 

Checkout page - no state is selected for Switzerland (marked as optional) - no shipping methods offered:

 <https://user-images.githubusercontent.com/19143190/76636542-a384c380-651f-11ea-921e-cf1e5ca9c1c7.jpg> 

Checkout page - the state is selected - shipping options are offered:

 <https://user-images.githubusercontent.com/19143190/76636620-c1522880-651f-11ea-9a18-e3f9568b1bc1.jpg> 

We’re going to prioritize working on this bug.

**Comment by peterfabian** [comment]
This should be solved by https://github.com/woocommerce/woocommerce/pull/25916 and will be released in the next couple of days.

**Comment by peterfabian** [comment]
This should be fixed now.
