### ISSUE TITLE
meta-boxes-product-variation.js file get_variations_fields function issue

### ISSUE THREAD

**Issue by EmranAhmed** [woocommerce/woocommerce#25929]
File location: `/woocommerce/assets/js/admin/meta-boxes-product-variation.js`

In previous woocommerce version `get_variations_fields` data was returned with jQuery `serializeJSON()` method but in this version (4.0) it generate input name and assign with associate value which actually doesn't work nested input name and value.

Seems there is a input name like 
`<input name="_wc_variation_file_names[variation_id][]" value="value">`

It generate `data[ _wc_variation_file_names[variation_id][] ] = value` on `get_variations_fields` function file `meta-boxes-product-variation.js` file.

And thats why multiple downloadable files to a variation doesn't save.

**Comment by phillipcornwell** [comment]
Also found in 14445181-hc and 2797463-zen

I was able to replicate this issue in my test site as well, with only WooCommerce and Storefront active. When adding a second file to a product you found the first one was removed and not available for download by the customer.

**Comment by juliaamosova** [comment]
Hi @EmranAhmed,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/25852 and here https://github.com/woocommerce/woocommerce/issues/25921. 

There is a fix for it in WooCommerce 4.0.1 via https://github.com/woocommerce/woocommerce/pull/25950. Please update WooCommerce to 4.0.1. Thanks!
