### ISSUE TITLE
WC 4.0 admin dashboard and images fail to load

### ISSUE THREAD

**Issue by lifeforceinst** [woocommerce/woocommerce#25924]
### After loading WooCommerce 4.0 on a local test platform - **_what a non-functional mess._**

Running WordPress 5.3.2., I immediately loaded the default theme of Twenty20 and disabled all the plugins except WooCommerce.  I set a default .htaccess and and clearing all browser caches - but still there were issues.

> The Main WooCommerce dashboard pages have items which are filled with placeholders and no data (I have not hidden the data in the grey boxes, this is all that was displayed).

This occurs for the dashboard, customers and analytics, as you can see in some of the modified screengrabs.
![WC40-Issues#1](https://user-images.githubusercontent.com/27138365/76683064-e797c700-65f8-11ea-9d88-5434415ed52f.jpg)
![WC40-Issues#2](https://user-images.githubusercontent.com/27138365/76683067-f0889880-65f8-11ea-9a77-45b46d886810.jpg)

Then for product images WooCommerce seems to looks for all images in the default folder /wp-content/uploads/. Again - something else which all worked fine with the previous versions of WC.
![WC40-Issues#3](https://user-images.githubusercontent.com/27138365/76683367-7ad1fc00-65fb-11ea-9ace-7a157665223f.jpg)

Generally all status reports fine, as you can see from the following extract from the system report
WC Version: 4.0.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.2
WC Admin Version: ✔ 1.0.0
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 384 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###
Server Info: Apache
PHP Version: 7.2.24
PHP Post Max Size: 
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1
SUHOSIN Installed: –
MySQL Version: 5.7.29
Max Upload Size: 
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

It always seems the same when there is a significant update, one has to question what testing did not occur that such broken code gets released.

**Comment by clongatojr** [comment]
I´m having the same problem. Nothing shows and after a few page loads Sucuri kicks me out of my own website.
This doesn´t happen with older versions of Woocommerce.

**Comment by peterfabian** [comment]
Hi @lifeforceinst , thanks for reporting the issue and apologies for the problems you've encountered. What version have you tried to update from or what exactly do you mean by 'loading WooCommerce 4.0 on a local test platform'? We can only fix the problem if we manage to reproduce the problem ourselves, so the more details you provide us with, the better chance of fixing the issues we have. Thanks!

**Comment by lifeforceinst** [comment]
A local test platform, means rather than applying the change on a production system, as advised, I have tested the new WC 4.0 on a test platform.  You can see detail of the environment above.

The system was running WC 3.9.3 and WP 5.3.2 happily.  I then upgraded WC to 4.0 and ad detailed above things are broken.  If you see the images - they show examples of the pages which are broken.

**Comment by peterfabian** [comment]
Thanks. Can you please elaborate on how you created a copy of your production server to your local platform? I have a feeling that it might be related to the fact that images are not found where WC expects them to be.

Could you check the Network tab in the Chrome dev tools if the requests to your server are being sent to the correct address and if they get a response?

**Comment by lifeforceinst** [comment]
Peter,
These duplicate R&D test sites have worked 100% fine for years using
the same replication methods.  The local replication site worked
100% find with WC 3.9.x and all previous versions.
These R&D sites are an exact  site replica using WP Migrate DB
Pro, or BackupBuddy.  The images themselves can be found in
WordPress Media gallery.

At 14:08 17/03/2020, Peter Fabian wrote:
Thanks. Can you please elaborate
on how you created a copy of your production server to your local
platform? I have a feeling that it might be related to the fact that
images are not found where WC expects them to be.
Could you check the Network tab in the Chrome dev tools if the requests
to your server are being sent to the correct address and if they get a
response?
­
You are receiving this because you were mentioned.
Reply to this email directly,

view it on GitHub, or

unsubscribe.

The Life Force
Institute
illuminating your
life
London United Kingdom |
Barcelona Spain | Brisbane Australia 
Web:
thelifeforceinstitute.com
and www.tlfi.com.au
eMail:

thelifeforceinstitute@gmail.com
On receiving and access this
material, you accept our terms and conditions, which are available at

thelifeforceinstitute.com/home/terms.

**Comment by peterfabian** [comment]
Hi, 

thanks for the further information. I've tried to create a site with a sample set of products and orders running WC 3.9.3, then used WP Migrate DB Pro (with Plugin and Media add-ons) to "Pull" the site to another server, where I performed the upgrade to WC 4.0. I could not, however, reproduce the errors you reported. 

I will try running the same procedure for some of the older testing sites to see if I can reproduce the issues, maybe there is something I missed. Please let us know if you have any further details or steps to reproduce the problem reliably.

**Comment by lifeforceinst** [comment]
An interesting fact is that if I run the site using Firefox and not
chrome, then things work a little bit better, as in some information is
displayed, but when I looked closer the only data in the dashboard which
was actually real data, was the downloads, all other items regarding
products, sales were all zero.
I have seen Java issues like this over many years caused by java issues
with different browsers in the many years of having tested
products.  
Also looking through error logs, I found WooCommerce generated a Critical
PHP error
2020-03-20T09:12:13+00:00 CRITICAL Uncaught Error: Call to a member
function get_file_download_path() on boolean in
/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/Downloads/Controller.php:112
Stack trace:
#0
/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/Downloads/Controller.php(59):
Automattic\WooCommerce\Admin\API\Reports\Downloads\Controller->prepare_item_for_response(Array,
Object(WP_REST_Request))
#1 /wp-includes/rest-api/class-wp-rest-server.php(946):
Automattic\WooCommerce\Admin\API\Reports\Downloads\Controller->get_items(Object(WP_REST_Request))
#2 /wp-includes/rest-api/class-wp-rest-server.php(329):
WP_REST_Server->dispatch(Object(WP_REST_Request))
#3 /wp-includes/rest-api.php(305):
WP_REST_Server->serve_request('/wc-analytics/r...')
#4 /wp-includes/class-wp-hook.php(288): rest_api_loaded(Object(WP))
#5 /wp-includes/class-wp-hook.php(312): WP_Hook-> in
/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/API/Reports/Downloads/Controller.php
on line 112


We really need a way to turn off this horrid interface and use the
old interface, similar to how you can continue to use classic editor with
WordPress.

At 14:28 18/03/2020, Peter Fabian wrote:
Hi,
thanks for the further information. I've tried to create a site with a
sample set of products and orders running WC 3.9.3, then used WP Migrate
DB Pro (with Plugin and Media add-ons) to "Pull" the site to
another server, where I performed the upgrade to WC 4.0. I could not,
however, reproduce the errors you reported.
I will try running the same procedure for some of the older testing sites
to see if I can reproduce the issues, maybe there is something I missed.
Please let us know if you have any further details or steps to reproduce
the problem reliably.
­
You are receiving this because you were mentioned.
Reply to this email directly,

view it on GitHub, or

unsubscribe.

The Life Force
Institute
illuminating your
life
London United Kingdom |
Barcelona Spain | Brisbane Australia 
Web:
thelifeforceinstitute.com
and www.tlfi.com.au
eMail:

thelifeforceinstitute@gmail.com
On receiving and access this
material, you accept our terms and conditions, which are available at

thelifeforceinstitute.com/home/terms.

**Comment by peterfabian** [comment]
Hi, you can turn off this horrid interface by adding a code snippet/filter somewhere which runs before the plugins are getting loaded (i.e. not your theme functions.php file, that only runs later):

```
add_filter( 'woocommerce_admin_disabled', '__return_true' );
```

Also, thanks for providing the error, we'll try to understand why it's happening and fix it as soon as possible.

**Comment by georgetasioulis** [comment]
We experienced the exact same issue on a website and were able to resolve it by increasing the CloudLinux PMEM limit of the cPanel account hosting that domain.
Probably similar to https://github.com/woocommerce/woocommerce/issues/25999#issuecomment-603348343

**Comment by lifeforceinst** [comment]
Since upgrading to WC 4.01 things have improved a little bit, though when you look at analytics or orders status or customer status then the calls via REST API which populate these tables result in no data, except for the download table.

**Comment by lifeforceinst** [comment]
After adding the filter to my theme, this did not disable the new admin interface components.

`  add_filter ('woocommerce_admin_disabled','__return_true');`

**Comment by rrennick** [comment]
> After adding the filter to my theme

@lifeforceinst The filter has to be implemented in a plugin. WC Admin is already loaded by the time WP loads the theme.

**Comment by zhollenbeak** [comment]
Chat [20285808](https://mc.a8c.com/support-stats/happychat/transcript.php?id=20285808) reported this problem.

**Comment by juliaamosova** [comment]
Hi @lifeforceinst,

This issue had been open for a while now with the last report submitted a year ago. It seems that the issue is less likely to happen these days. 

I will go ahead and close it due to inactivity. However, please feel free to comment on it in case you'd like us to continue looking into it.

**Comment by lifeforceinst** [comment]
The problem isn't solved - there is a workaround to disable this stupid interface, but a workaround is not a fix.
