### ISSUE TITLE
Attributes not updating for existing products by csv

### ISSUE THREAD

**Issue by ntindicator** [woocommerce/woocommerce#25934]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [ ] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x ] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Import variable products via csv with 1 attribute that will be used for variations.
2. Import another csv with variations that results in a working variable product.
2. After importing, re-import the variable products csv with a different attribute visibility setting. 1 if visible or 0 if not visible. Set all columns except 'SKU' and 'Attribute 1 visibility' to 'do not import'.
3. Import the variable products ticking the box to update existing products.

## Expected/actual behavior

When I follow those steps, I see...
The visibility of the attribute on the single product page or product edit page hasn't changed.

I was expecting to see...
The visibility setting of the attribute change, and would no longer be visible on the product page. 
## Isolating the problem
By deleting the products completely I was able to change the visibility setting by importing the CSV again, but couldn't update the setting after it was already imported. The same is true for  attribute values. They don't change if updated.

- [ x] This bug happens with only WooCommerce plugin active
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [ x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://wordpress.local
Site address (URL): https://wordpress.local
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: 5.4
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.18 (Ubuntu)
PHP Version: 7.3.14-1+ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.29-0ubuntu0.16.04.1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: wp_
Total Database Size: 28.50MB
Database Data Size: 19.18MB
Database Index Size: 9.32MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_alm: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_as3cf_items: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_aws_cache: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_aws_index: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_gglcptch_whitelist: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.41MB + Index: 0.14MB + Engine InnoDB
wp_pmxe_exports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 10.52MB + Index: 6.03MB + Engine InnoDB
wp_posts: Data: 2.52MB + Index: 0.84MB + Engine InnoDB
wp_signups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_swpm_membership_meta_tbl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_swpm_membership_tbl: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_swpm_members_tbl: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_swpm_payments_tbl: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
wp_terms: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_term_relationships: Data: 0.27MB + Index: 0.22MB + Engine InnoDB
wp_term_taxonomy: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.19MB + Index: 0.45MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfu_dbxqueue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfu_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfu_userdata: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.08MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf: 1
attachment: 2916
customize_changeset: 1
ebayitem: 3
mc4wp-form: 2
ml-slider: 1
nav_menu_item: 18
page: 29
post: 10
product: 824
product_variation: 702
revision: 378
shop_coupon: 1
shop_order: 17
shop_order_refund: 4
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.0.1

### Inactive Plugins (0) ###


### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #482 - /art-gallery/
Cart: #483 - /cart/
Checkout: #484 - /checkout/
My account: #485 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 6
Oldest: 2020-02-20 18:36:13 +0000
Newest: 2020-03-16 03:38:16 +0000

Pending: 3
Oldest: 2020-03-16 22:02:02 +0000
Newest: 2020-03-30 00:41:20 +0000

Canceled: 17
Oldest: -0001-11-30 00:00:00 +0000
Newest: -0001-11-30 00:00:00 +0000

`
```
</details>

**Comment by yukikatayama** [comment]
Similar issue reported in 20487603-hc and confirmed in testing.

In this case, user is switching their simple product to a variable product and mapping the `variations` using the parent's SKU.

On import, `used for variations` is not enabled.

Note, when a new product is imported, creating variations is fine.

To test:

1. create a simple product that has a SKU.
2. Export it and add the necessary columns and fields to turn it into a variable product. Making sure "Attribute 1 visible" is set to `1` and Parent is set to the parent's SKU.
3. merge import

**Comment by stephhjacq** [comment]
In 2900095-zen I see the same issue for a new variable product - `used for variations` is not enabled. 

This product was created by using an existing product as a template to confirm correct values were entered.

**Comment by ShadyBonsai** [comment]
Also having the Same issue where by I have 3 different attributes and when I import the CSV it does not create a variation with a cost? anyone have the same issue?

**Comment by juliaamosova** [comment]
Hi @ntindicator, @yukikatayama, @stephhjacq and @ShadyBonsai,

Apologies for getting back to this issue with delay. Thanks for raising it! 

It is not clear to me, however, how to properly reproduce this issue or what the issue is. 

Visuals will be helpful. Also, it seems that you all are referring to different issues. 

What I've done so far is the following (trying to reproduce the issue reported by @ntindicator):

1) Created a variable product with 1 attribute `Size` that has the following options: `S`, `M`, `L`;
2) Marked the attribute to be `Visible on the product page` and `Used for variations`:

![csv1](https://user-images.githubusercontent.com/19143190/82598721-168e6400-9b79-11ea-92ba-0567f0409be6.jpg)

3) Created 3 variations (one for each size) out of this attribute and assigned a price to each variation:

![Screen Shot 2020-05-21 at 3 39 07 PM](https://user-images.githubusercontent.com/19143190/82598837-42114e80-9b79-11ea-94f2-79c00c20e647.png)

4) Exported products via CSV Export option on `All Products` page:

![csv2](https://user-images.githubusercontent.com/19143190/82598966-7b49be80-9b79-11ea-8029-04e1954e260c.jpg)

5) In the CSV file exported, I found a column `Attribute 1 visible` - it has value `1` next to the parent variable product which indicates `visible` - which is expected because I marked attribute to be `Visible on the product page` in step 2:

![csv3](https://user-images.githubusercontent.com/19143190/82599394-31150d00-9b7a-11ea-818e-9dbd1b09f865.jpg)

6) I changed `1` to `0` and saved the new CSV file:

![csv4](https://user-images.githubusercontent.com/19143190/82599606-9e28a280-9b7a-11ea-952d-f269210839e0.jpg)

7) Next, I imported the new CSV file to the site via the `Import` button on `All Products` page with `Update existing products` box selected:

![csv5](https://user-images.githubusercontent.com/19143190/82599951-23ac5280-9b7b-11ea-83a3-b0c742fe4c40.jpg)

8) Navigated back to the variable product and saw that `Visible on the product page` is not selected which is expected because I set for this field to have a value `0` in the CSV file in step 6:

![csv6](https://user-images.githubusercontent.com/19143190/82600037-3faff400-9b7b-11ea-9952-583ff908c674.jpg)

Am I missing any steps?

**Comment by juliaamosova** [comment]
@ShadyBonsai what are your steps to reproduce the issue? 

So far I can successfully update variations prices of the existing product bu exporting products, updating prices in CSV file, and importing it back to the site. 

I made a video to show my steps: https://recordit.co/nOWYnEubUd.

**Comment by juliaamosova** [comment]
>In 2900095-zen I see the same issue for a new variable product - used for variations is not enabled.

>This product was created by using an existing product as a template to confirm correct values were entered.

@stephhjacq I looked at 2900095-zen and tested the CSV file provided there by the customer. I noticed that it was missing the `id:1` value in the `Parent` column which creates the connection between the parent product and its variations. I added `id:1` to the `Parent` column and imported user's file to my test site - variations were successfully created:

![parent1](https://user-images.githubusercontent.com/19143190/82609940-83aaf500-9b8b-11ea-9c08-a4375f97367b.jpg)

![parent2](https://user-images.githubusercontent.com/19143190/82609947-886fa900-9b8b-11ea-85c0-ffb8edf24cb1.jpg)

I also tested further myself and created a variable product on the site. Next, I exported that product to the CSV file in order to have a template of the existing product. I then added 3 new rows to create a new variable product with 2 variations. Finally, I imported updated CSV file to my test site and the new variable product was indeed created. I made a video of what I did:

Part 1: https://cloudup.com/cy3OMh4JSIT
Part2: https://cloudup.com/c7M2UL7jrpE

Unless I am missing something, everything seems to work as expected.

**Comment by juliaamosova** [comment]
>In this case, user is switching their simple product to a variable product and mapping the variations using the parent's SKU.

>On import, used for variations is not enabled.

@yukikatayama this seems like a separate issue - different from what the author of this thread is reporting. I was able to replicate your scenario and created a separate issue for it: https://github.com/woocommerce/woocommerce/issues/26585.

**Comment by ntindicator** [comment]
Hi @juliaamosova, thanks for your reply. The steps I'm using are somewhat different, as both variable and variations are imported by separate csv files, and products aren't exported from Woocommerce to update. When importing to update the products, there are only 3 columns in the CSV, and there are no variations as these are generated and imported separately. This could be important, as you successfully updated the visibility with variations in the CSV. The CSV I'm using to update has the variable products only with no variations, as shown below. The first column is ignored, the 2nd column is the SKU, and the 3rd contains the visibility setting.

,SKU,Attribute 1 visible
401,03494,1
402,03487,1
403,03074,1
404,02914,1
405,03064,1
406,03065,1 

After importing the CSV, there is no change from "not visible" to "visible".
<img width="795" alt="Variable_sku" src="https://user-images.githubusercontent.com/30362690/83411837-5815ed80-a45c-11ea-9a00-48cafcffc5df.png">
<img width="788" alt="Variable_visibility" src="https://user-images.githubusercontent.com/30362690/83411849-5c420b00-a45c-11ea-8b9d-ab4fa01c293f.png">

If I change Attribute 1 name on the variable product only to "Size", the attribute will cease to exist on the admin screen. This is to be expected, as the variations have the attribute name "Item" not "Size". If I try to change it back to "Item", the product will still be unusable in the admin screen. In the front end the product is unchanged, from how it was before the Attribute 1 name was changed to Size. This proves that something has updated because it changed, although it's now broken, and it's probably best to delete it.

,SKU,Attribute 1 name
401,03494,Size
402,03487,Size
403,03074,Size
404,02914,Size
405,03064,Size
406,03065,Size

,SKU,Attribute 1 name
401,03494,Item
402,03487,Item
403,03074,Item
404,02914,Item
405,03064,Item
406,03065,Item

<img width="788" alt="No attributes" src="https://user-images.githubusercontent.com/30362690/83413054-872d5e80-a45e-11ea-8275-53bfd6cf3708.png">

**Comment by FreshPhil** [comment]
@juliaamosova I just came across this issue by finding that I couldn't update the `Used for variations` setting to _uncheck_ it on existing products by CSV import. That seems within the scope of the above general issue, but wanted to point this out as it isn't specifically listed above.

If you'd prefer this be added as a separate issue, please let me know :)

**Comment by kaleidografik** [comment]
Completely agree with @FreshPhil - Our issue is that existing products do not update the `Used for variations` checkbox upon import/update. However, it seems when doing so for a new product, it works as expected.

To me, it seems the `Used for variations` checkbox should have it's own column in the attributes CSV options, in the same way that `Visible` and `Global` do?

**Comment by ntindicator** [comment]
I have discovered that this issue occurred because all attribute fields weren't included in the CSV import I did. Updating the name field alone fails to update the product, but if the fields such as value(s) are included then the product will update.

**Comment by nisiwi** [comment]
I seem to be currently struggling with this exact issue, changing attribute settings, when updating existing products via upload.

In fact I see a similar problem with allowing products with no prices (I have the correct snippet added) to display their variation swatches.

If I make any modifications manually (change an attribute setting OR set a product price and then clear it) to a product it will upadte fine and perform as expected.  However if I try updating by upload the updates are not adopted.

It seems that some logic gets triggered when updating manually which isn't getting triggered when updating via upload.

Was anyone able to reliably update or change product attribute settings via upload and if so how, this may also be relevant to displaying swatches on the front end ?

**Comment by nisiwi** [comment]
A fix mentioned here might help others - I've not yet tested
https://github.com/woocommerce/woocommerce/issues/19645

Other threads discussing the same issue:
https://github.com/woocommerce/woocommerce/issues/25934
https://github.com/woocommerce/woocommerce/issues/26380

This is clearly a problematic area so some official guidance would be welcome.

**Comment by rrennick** [comment]
> Was anyone able to reliably update or change product attribute settings via upload

I did this on a live site this weekend with the latest version of WC. To determine what columns you need to import, export the products and select the fields `ID` and `attributes`.
