### ISSUE TITLE
Hard to remove customer from order

### ISSUE THREAD

**Issue by odedta** [woocommerce/woocommerce#25945]
**Describe the bug**
I'm trying to test some things and I need to remove a contact from an order but I have to click all around the x button until I manage to a spot that works.

I recorded a video
https://www.loom.com/share/3d9f1a0b5c514a8a83d2c58168abb48c

Thanks

**Comment by tammullen** [comment]
Hi @odedta 

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/25427. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
