### ISSUE TITLE
Save variation issue

### ISSUE THREAD

**Issue by mynewvk** [woocommerce/woocommerce#25954]
The new way to save variation ( 'get_variations_fields' function ) does not respect array values without the keys.

Example:

I have those fields - https://ibb.co/80xt9HK
HTML markup - https://ibb.co/GMcpnGz

"new tier" adds a new group of fields with [] (empty) index in the end.
 
The problem is that on save function does not retrieve that as an array, but only use the last element of the array -https://ibb.co/Z66PvwX

Please let me know whether this is a bug (This occurs only from WooCommerce 4) or I need to handle keys by myself.

Thanks!

**Comment by juliaamosova** [comment]
Hi @mynewvk, thanks for opening the issue. We are reverting the change related to how variations are being saved starting from 4.0 in 4.0.1: https://github.com/woocommerce/woocommerce/pull/25950. 

We are working on releasing 4.0.1 as we speak.

**Comment by mynewvk** [comment]
Hi @juliaamosova,

Thanks!
