### ISSUE TITLE
Product display option doesn't exist

### ISSUE THREAD

**Issue by Fabrikka** [woocommerce/woocommerce#25959]
**Describe the bug**
I need to make some customizations on my general shop page, like display some categories and not all the products. 

**To Reproduce**
The option is not displayed itself in "woocommerce > settings > products > "nothing like display".

**Screenshots**
As you can see, just options "general" "inventory" "downloadable products". But not "display".

**Expected behavior**
Having the option like it's named in the manual.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.

`
### WordPress Environment ###

WordPress address (URL): http://shop.fabrikka.fr
Site address (URL): https://shop.fabrikka.fr
WC Version: 4.0.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.2
WC Admin Version: ✔ 1.0.1
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.6
PHP Post Max Size: 128 MB
PHP Time Limit: 0
PHP Max Input Vars: 3000
cURL Version: 7.52.1
OpenSSL/1.0.2l

SUHOSIN Installed: –
MySQL Version: ❌ 5.5.61-38.13-log - Nous recommandons MySQL version 5.6 minimum. Voir : Exigences de WordPress
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.0
WC Database Prefix: byg_
Taille totale de la base de données: 71.42MB
Taille de la base de données: 42.13MB
Taille de l’index: 29.29MB
byg_woocommerce_sessions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
byg_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
byg_woocommerce_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_woocommerce_order_itemmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
byg_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
byg_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
byg_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
byg_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
byg_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_actionscheduler_actions: Données : 0.34MB + Index : 0.34MB + Moteur InnoDB
byg_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_actionscheduler_logs: Données : 0.20MB + Index : 0.17MB + Moteur InnoDB
byg_adtribes_my_conversions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_atum_order_itemmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
byg_atum_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_atum_product_data: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
byg_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
byg_comments: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
byg_failed_jobs: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_icl_content_status: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_icl_core_status: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_icl_flags: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_icl_languages: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
byg_icl_languages_translations: Données : 0.19MB + Index : 0.11MB + Moteur InnoDB
byg_icl_locale_map: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_icl_message_status: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
byg_icl_mo_files_domains: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_icl_node: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_icl_reminders: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_icl_strings: Données : 7.52MB + Index : 12.06MB + Moteur InnoDB
byg_icl_string_packages: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_icl_string_pages: Données : 7.52MB + Index : 11.03MB + Moteur InnoDB
byg_icl_string_positions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_icl_string_status: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_icl_string_translations: Données : 3.52MB + Index : 1.97MB + Moteur InnoDB
byg_icl_string_urls: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_icl_translate: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_icl_translate_job: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_icl_translations: Données : 0.05MB + Index : 0.06MB + Moteur InnoDB
byg_icl_translation_batches: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_icl_translation_downloads: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_icl_translation_status: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_mailchimp_carts: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_mailchimp_jobs: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_mainwp_backupwordpress: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_maxbuttonsv3: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_maxbuttons_collections: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_maxbuttons_collections_trans: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_moos_oauth_access_tokens: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_moos_oauth_authorization_codes: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_moos_oauth_authorized_apps: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_moos_oauth_clients: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_moos_oauth_public_keys: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_moos_oauth_refresh_tokens: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_moos_oauth_scopes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_moos_oauth_users: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_options: Données : 5.03MB + Index : 0.17MB + Moteur InnoDB
byg_postmeta: Données : 2.22MB + Index : 1.28MB + Moteur InnoDB
byg_posts: Données : 3.09MB + Index : 0.06MB + Moteur InnoDB
byg_queue: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_share_logins_log: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_termmeta: Données : 0.05MB + Index : 0.03MB + Moteur InnoDB
byg_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
byg_term_relationships: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
byg_tutor_earnings: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_tutor_quiz_attempts: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_tutor_quiz_attempt_answers: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_tutor_quiz_questions: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_tutor_quiz_question_answers: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_tutor_withdraws: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_UPCP_Catalogues: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_UPCP_Catalogue_Items: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_UPCP_Categories: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_UPCP_Custom_Fields: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_UPCP_Fields_Meta: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_UPCP_Items: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_UPCP_Item_Images: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_UPCP_SubCategories: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_UPCP_Tagged_Items: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_UPCP_Tags: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_UPCP_Tag_Groups: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_UPCP_Videos: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_usermeta: Données : 0.03MB + Index : 0.03MB + Moteur InnoDB
byg_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
byg_wc_admin_notes: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_wc_admin_note_actions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
byg_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
byg_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
byg_wc_order_product_lookup: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
byg_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
byg_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
byg_wc_product_meta_lookup: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
byg_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_wfblockediplog: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_wfblocks7: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
byg_wfconfig: Données : 1.23MB + Index : 0.00MB + Moteur InnoDB
byg_wfcrawlers: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_wffilechanges: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_wffilemods: Données : 4.52MB + Index : 0.00MB + Moteur InnoDB
byg_wfhits: Données : 0.11MB + Index : 0.05MB + Moteur InnoDB
byg_wfhoover: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_wfissues: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
byg_wfknownfilelist: Données : 2.52MB + Index : 0.00MB + Moteur InnoDB
byg_wflivetraffichuman: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_wflocs: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_wflogins: Données : 0.22MB + Index : 0.08MB + Moteur InnoDB
byg_wfls_2fa_secrets: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_wfls_settings: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_wfnotifications: Données : 0.05MB + Index : 0.00MB + Moteur InnoDB
byg_wfpendingissues: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
byg_wfreversecache: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_wfsnipcache: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
byg_wfstatus: Données : 0.13MB + Index : 0.09MB + Moteur InnoDB
byg_wftrafficrates: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
byg_yoast_seo_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
byg_yoast_seo_meta: Données : 1.45MB + Index : 0.00MB + Moteur InnoDB

### Post Type Counts ###

attachment: 118
bbfb_content: 1
courses: 1
custom_css: 1
customize_changeset: 4
jetpack_migration: 2
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
lesson: 5
nav_menu_item: 52
page: 28
post: 1
private-page: 2
product: 9
product_variation: 2
revision: 37
shop_order: 6
topics: 1
tutor_enrolled: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (38) ###

WPML Multilingual CMS: par OnTheGoSystems – 4.3.10
Yoast SEO Multilingual: par OnTheGoSystems – 1.0.3
ACF Content Analysis for Yoast SEO: par Thomas Kräftner
ViktorFroberg
marol87
pekz0r
angrycreative
équipe Yoast – 2.3.0

Add Admin JavaScript: par Scott Reilly – 1.8.1
Advanced Custom Fields: par Elliot Condon – 5.8.8
Antispam Bee: par pluginkollektiv – 2.9.1
BackUpWordPress: par XIBO Ltd – 3.10
Ultimate Footer Builder: par BestBug – 1.8.6
Blackhole for Bad Bots: par Jeff Starr – 2.7
Block Bad Queries (BBQ): par Jeff Starr – 20191109
CMP - Coming Soon & Maintenance Plugin: par NiteoThemes – 3.7.1
Contact Form 7 Multilingual: par OnTheGoSystems – 1.0.2
Envato Market: par Envato – 2.0.3
GA Google Analytics: par Jeff Starr – 20191109
Éditeur de page: par Michael M - WPBakery.com – 6.1
Mailchimp for WooCommerce: par Mailchimp – 2.3.5
MainWP Child: par MainWP – 4.0.7
NeuronThemes Share: par Neuronthemes – 1.0.0
Safe SVG: par Daryll Doyle – 1.9.8
Share Logins: par codexpert – 2.1.4
Tutor LMS: par Themeum – 1.5.6
WooCommerce Blocks: par Automattic – 2.5.14
Product Feed PRO for WooCommerce: par AdTribes.io – 7.7.4
WooCommerce Admin: par WooCommerce – 1.0.1
Custom Price Labels for WooCommerce: par WP Wham – 2.5.4 – Non testé avec la version active de WooCommerce
WooCommerce Email Customizer: par cxThemes – 3.33 – Non testé avec la version active de WooCommerce
WooCommerce Stripe Gateway: par WooCommerce – 4.3.2 – Non testé avec la version active de WooCommerce
More Sorting Options for WooCommerce (Premium): par WP Wham – 3.2.1 – Non testé avec la version active de WooCommerce
WooCommerce Multilingual: par OnTheGoSystems – 4.7.9 – Non testé avec la version active de WooCommerce
WooCommerce Services: par Automattic – 1.22.4
WooCommerce: par Automattic – 4.0.0
Wordfence Security: par Wordfence – 7.4.6
WordPress Importer: par wordpressdotorg – 0.7
Yoast SEO: par L’équipe Yoast – 13.3
MailChimp for WordPress Multilingual: par OnTheGoSystems – 0.0.3
WPML Media: par OnTheGoSystems – 2.5.5
WPML String Translation: par OnTheGoSystems – 3.0.8
WPML Translation Management: par OnTheGoSystems – 2.9.5

### Inactive Plugins (1) ###

One Click Demo Import: par ProteusThemes – 2.5.2

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la boutique: #8 - /
Panier: #9 - /cart/
Validation de la commande: #10 - /checkout/
Mon compte: #11 - /my-account/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Soma Child
Version: 1.0.0
Author URL: http://neuronthemes.com
Child Theme: ✔
Parent Theme Name: Soma
Parent Theme Version: 1.1.0
Parent Theme Author URL: http://neuronthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: soma/woocommerce/archive-product.php
soma/woocommerce/cart/cart-empty.php
soma/woocommerce/cart/cart-totals.php
soma/woocommerce/cart/cart.php
soma/woocommerce/cart/cross-sells.php
soma/woocommerce/cart/mini-cart.php
soma/woocommerce/cart/shipping-calculator.php version 3.5.0 est obsolète. La version du noyau est 4.0.0
soma/woocommerce/checkout/form-billing.php
soma/woocommerce/checkout/form-checkout.php
soma/woocommerce/checkout/form-coupon.php
soma/woocommerce/checkout/form-shipping.php
soma/woocommerce/checkout/review-order.php
soma/woocommerce/checkout/thankyou.php
soma/woocommerce/content-product.php
soma/woocommerce/content-product_cat.php
soma/woocommerce/content-single-product.php
/srv/data/web/vhosts/shop.fabrikka.fr/htdocs/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/admin-cancelled-order.php
/srv/data/web/vhosts/shop.fabrikka.fr/htdocs/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/admin-failed-order.php
/srv/data/web/vhosts/shop.fabrikka.fr/htdocs/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/admin-new-order.php
/srv/data/web/vhosts/shop.fabrikka.fr/htdocs/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/customer-completed-order.php
/srv/data/web/vhosts/shop.fabrikka.fr/htdocs/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/customer-invoice.php
/srv/data/web/vhosts/shop.fabrikka.fr/htdocs/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/customer-new-account.php
/srv/data/web/vhosts/shop.fabrikka.fr/htdocs/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/customer-note.php
/srv/data/web/vhosts/shop.fabrikka.fr/htdocs/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/customer-on-hold-order.php
/srv/data/web/vhosts/shop.fabrikka.fr/htdocs/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/customer-processing-order.php
/srv/data/web/vhosts/shop.fabrikka.fr/htdocs/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/customer-refunded-order.php
/srv/data/web/vhosts/shop.fabrikka.fr/htdocs/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/customer-reset-password.php version 3.7.0 est obsolète. La version du noyau est 4.0.0
/srv/data/web/vhosts/shop.fabrikka.fr/htdocs/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/email-addresses.php version 3.5.4 est obsolète. La version du noyau est 3.9.0
/srv/data/web/vhosts/shop.fabrikka.fr/htdocs/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/email-customer-details.php
/srv/data/web/vhosts/shop.fabrikka.fr/htdocs/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/email-downloads.php
/srv/data/web/vhosts/shop.fabrikka.fr/htdocs/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/email-footer.php
/srv/data/web/vhosts/shop.fabrikka.fr/htdocs/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/email-header.php version 2.4.0 est obsolète. La version du noyau est 4.0.0
/srv/data/web/vhosts/shop.fabrikka.fr/htdocs/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/email-order-details.php
/srv/data/web/vhosts/shop.fabrikka.fr/htdocs/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/email-order-items.php
/srv/data/web/vhosts/shop.fabrikka.fr/htdocs/wp-content/plugins/woocommerce-email-control/templates/emails/vanilla/email-styles.php version 3.3.0 est obsolète. La version du noyau est 4.0.0
soma-child/woocommerce/emails/plain/customer-reset-password.php version 3.5.0 est obsolète. La version du noyau est 3.7.0
soma/woocommerce/global/form-login.php
soma/woocommerce/loop/add-to-cart.php
soma/woocommerce/loop/loop-end.php
soma/woocommerce/loop/loop-start.php
soma/woocommerce/loop/orderby.php
soma/woocommerce/loop/pagination.php
soma/woocommerce/loop/price.php
soma/woocommerce/loop/result-count.php
soma/woocommerce/myaccount/form-edit-account.php
soma/woocommerce/myaccount/form-edit-address.php
soma/woocommerce/myaccount/form-login.php
soma/woocommerce/myaccount/form-lost-password.php
soma/woocommerce/myaccount/form-reset-password.php
soma/woocommerce/myaccount/lost-password-confirmation.php
soma/woocommerce/myaccount/my-account.php
soma/woocommerce/myaccount/my-address.php
soma/woocommerce/myaccount/navigation.php
soma/woocommerce/notices/error.php
soma/woocommerce/notices/notice.php
soma/woocommerce/notices/success.php
soma/woocommerce/order/form-tracking.php
soma/woocommerce/order/order-again.php
soma/woocommerce/order/order-details-customer.php
soma/woocommerce/order/order-details.php
soma/woocommerce/product-searchform.php
soma/woocommerce/single-product/add-to-cart/external.php
soma/woocommerce/single-product/add-to-cart/grouped.php version 3.4.0 est obsolète. La version du noyau est 4.0.0
soma/woocommerce/single-product/add-to-cart/simple.php
soma/woocommerce/single-product/add-to-cart/variable.php
soma/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
soma/woocommerce/single-product/add-to-cart/variation.php
soma/woocommerce/single-product/meta.php
soma/woocommerce/single-product/price.php
soma/woocommerce/single-product/product-attributes.php
soma/woocommerce/single-product/product-image.php
soma/woocommerce/single-product/rating.php
soma/woocommerce/single-product/related.php
soma/woocommerce/single-product/review-meta.php
soma/woocommerce/single-product/review.php
soma/woocommerce/single-product/sale-flash.php
soma/woocommerce/single-product/short-description.php
soma/woocommerce/single-product/stock.php
soma/woocommerce/single-product/tabs/additional-information.php
soma/woocommerce/single-product/tabs/description.php
soma/woocommerce/single-product/tabs/tabs.php
soma/woocommerce/single-product/title.php
soma/woocommerce/single-product/up-sells.php
soma/woocommerce/single-product-reviews.php
soma/woocommerce/single-product.php
soma/woocommerce/taxonomy-product_cat.php
soma/woocommerce/taxonomy-product_tag.php

Outdated Templates: ❌
					
					
						Apprenez comment mettre à jour

### Action Scheduler ###

Terminer: 769
Oldest: 2020-02-15 21:46:56 +0100
Newest: 2020-03-17 20:17:47 +0100

En attente: 3
Oldest: 2020-03-17 21:17:47 +0100
Newest: 2020-03-21 18:51:53 +0100

<img width="973" alt="Capture d’écran 2020-03-17 à 21 05 08" src="https://user-images.githubusercontent.com/50143079/76896935-18932880-6893-11ea-8369-0b14b1631f7c.png">

**Comment by tammullen** [comment]
Hi @Fabrikka 

Have a look here for help with customizing your site https://docs.woocommerce.com/document/woocommerce-customizer/

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.
