### ISSUE TITLE
Allow us to create our own template for single products and archives

### ISSUE THREAD

**Issue by krachteneu** [woocommerce/woocommerce#25965]
**Is your feature request related to a problem? Please describe.**
I am currently trying to edit the way single products and product grids look, but it seems like WooCommerce is preventing me to do that. I am able to make a simple layout for blog posts and pages fairly quickly, but when I try to make a custom WooCommerce layout I have to wander through dozens of template parts and other code snippets and functions. Also I can't figure out the way the hierarchy of product layouts work. I seem to have to order every item in the product page. I don't have to do this with normal blog posts! 
 
**Describe the solution you'd like**
A simple **single-wooproduct.php** page and **product-archive.php** page with a custom WooCommerce Wordpress Loop that displays the items the way I want instead of the way WooCommerce wants in a free and open source way. What if want to blend WooCommerce with my own theme, it doesn't seem to be possible! 

**Describe alternatives you've considered**
I tried page builders but they only offer a premium solution to edit product page templates and grids. 

**Additional context**
I see there are similar issues opened but all of them ignored by the Woocommerce team.   @mikejolley

**Comment by claudiosanches** [comment]
Hello.

> A simple single-wooproduct.php page and product-archive.php page with a custom WooCommerce Wordpress Loop that displays the items the way I want instead of the way WooCommerce wants in a free and open source way

Sorry, but isn't not clear what you want. I understand that it's new for you and it's different from regular blog themes, but there's nothing wrong, it's all WordPress code.

All parts of the layouts works using WordPress hooks, also in each template is described what function hook into it and looking in the function you can change the template.

> What if want to blend WooCommerce with my own theme, it doesn't seem to be possible!

Also there's not stopping you from using `template_redirect` or any other WordPress filter to override WooCommerce's templates, also WordPress allows you to created just a `single-product.php` and a `archive-product.php` on your theme and override everything from WooCommerce, so you can write the template and loop products in the way you want.

Any way, using "A simple single-wooproduct.php page and product-archive.php" shouldn't be backwards compatibility, but we are studying ways to improve our templates, while I'm going to close this issue no worry, I remember it while the time comes to update templates.
Thanks.

**Comment by krachteneu** [comment]
Fine, I'll make my own plugin. I was eager to work with WooCommerce but our theme has conflicts with your plugin. I already knew you would close my feature request, as this has also happend with Gutenberg. You want to disable some features and add a paywall I know the reason..
