### ISSUE TITLE
Not able to change status in hook "woocommerce_new_order"

### ISSUE THREAD

**Issue by WebLenn** [woocommerce/woocommerce#25964]
**Describe the bug**
I'm trying to change the order statussen of some orders based on some simple conditions.
The hook I tried using for this was "woocommerce_new_order" since this hook will run on every new order.

I could succesfully change values of the order but for some reason both `$order->set_status('in-review');` and `$order->update_status('in-review');` didn't change the status, even when I call the save method after using the setter `$order->save();`.

**To Reproduce**

Add the following code to your functions.php:
```
add_action( 'woocommerce_new_order', function( $order_id ) {
  $order = new WC_Order( $order_id );
  $order->update_status('in-review');
}, 999, 1);
```
Create a new order and check if the custom status was successfully applied.

If i change the code to use the WP hook "save_post" I do get the expected behavior:
```
add_action( 'save_post', function( $order_id ) {
  if( get_post_type($order_id) != 'shop_order') return;
  $order = new WC_Order( $order_id );
  $order->update_status('in-review');
});
```

**Expected behavior**

I expect the order status to change on a new order when adding the above code to my functions.php

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by ObliviousHarmony** [comment]
Hello @WebLenn,

What is the status being changed to? It's very probably that the payment gateway is overriding the status that you're setting. The `woocommerce_new_order` hook is indeed called upon order creation, but shortly after creation, the order is sent off to the payment gateway for handling. Certain gateways immediately set the status as they require manual processing, for instance.

You've got a few options to work around this:
- The `woocommerce_update_order` hook is called after every save action
- The `woocommerce_payment_successful_result` hook is called after a successful payment
- The `woocommerce_payment_complete` action is called when a payment is complete with a valid status.

Hope that helps!
