### ISSUE TITLE
Variable products which include downloads

### ISSUE THREAD

**Issue by NicWhitham** [woocommerce/woocommerce#25973]
I have been selling cd’s in physical format (shipped) and downloadable MP3 format (multiple tracks/files) for many years but I just found out that all downloadable tracks except the most recently added download file are deleted from the product and when I edit the product. When I try to add it back only the most recently added download file is saved and the others are removed. The downloadable files are set to download and virtual. I am only able to add multiple downloadable files to simple products not variable. 

If anyone can help explain why this has changed recently I would be most appreciative as I now have to go back through orders and resend missing files, then find a way to add them back.  I am not the only person experiencing this issue:  https://wordpress.org/support/topic/variable-products-including-downloads-2/

**Comment by peterfabian** [comment]
Hi @NicWhitham 

Apologies for the problem. It seems like what you're experiencing has already been reported in https://github.com/woocommerce/woocommerce/issues/25921 and should be solved in the next release soon.
