### ISSUE TITLE
Impossible to add custom visibility

### ISSUE THREAD

**Issue by vasikgreif** [woocommerce/woocommerce#25991]
I wanted to add a new custom visibility to the default ones. 

There's a filter `woocommerce_product_visibility_options`, that can be used to add new visibility to the dropdown. 

To save a new taxonomy, I used `woocommerce_product_set_visibility` action, which is by itself a little hacky solution, as the hook is triggerd after the default visibility is saved:

```php
if ( ! is_wp_error( wp_set_post_terms( $product->get_id(), $terms, 'product_visibility', false ) ) ) {
	do_action( 'woocommerce_product_set_visibility', $product->get_id(), $product->get_catalog_visibility() );
}

```

But I don't see any way to retrieve the custom visibility, as there's no hook available in the `read_visibility()` method to set the custom visibility back to the `$product` object.

Am I missing something?

**Comment by ObliviousHarmony** [comment]
Hello @vasikgreif,

You should be able to use the `woocommerce_product_read` filter in this case. That filter allows you to make changes to the product after it gets read but before any code makes use of it.

**Comment by ObliviousHarmony** [comment]
Hey @vasikgreif and @webgmclassics,

Sorry for the not-useful advice last year! It doesn't look like there's an easy way to implement a custom catalog visibility. One possibility would be to hook the property setter with  A filter for reading the visibility would be entirely appropriate given the clear support for filtering the setting of the visibility.

**Comment by webgmclassics** [comment]
@ObliviousHarmony Thanks for the reply. Helps me know I'm not crazy! To be clear, a filter for reading product visibility does not currently exist, correct?

**Comment by ObliviousHarmony** [comment]
That is correct @webgmclassics.

**Comment by bakkbone** [comment]
Can I clarify then... the `woocommerce_product_visibility_options` filter has no native way to actually use any options you add to the list? So, its only real use at the moment would be changing the labels or removing an option, not adding it...?

**Comment by eddr** [comment]
Are there any updates on this?

Thanks
