### ISSUE TITLE
Wrong hooked function in woocommerce_before_single_product

### ISSUE THREAD

**Issue by stian-overasen** [woocommerce/woocommerce#25996]
In `content-single-product.php` is says that the `wc_print_notices` function is hooked on `woocommerce_before_single_product` at priority 10. This is not correct.
https://github.com/woocommerce/woocommerce/blob/1926a5042622980ce9b520e63b8cc30d917d4a07/templates/content-single-product.php#L25

At line 306 in `wc-template-hooks.php` we can see that it is in fact the `woocommerce_output_all_notices` function that is hooked.
https://github.com/woocommerce/woocommerce/blob/1926a5042622980ce9b520e63b8cc30d917d4a07/includes/wc-template-hooks.php#L306

**Comment by ObliviousHarmony** [comment]
Hi @stian-overasen,

Thank you for taking the time reporting this bug, we really appreciate your help. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.
