### ISSUE TITLE
Single use coupons able to be reused by guests if Hold Stock is blank

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#26002]
**Describe the bug**
If the _Hold Stock_ setting is blank in a store, and the store has coupons that can only be used once per user, and guest checkout is enabled, then guests can use those coupons multiple times with a single email address. 

The check to see if the coupon has already been used by the guest is done here:
https://github.com/woocommerce/woocommerce/blob/4.0.1/includes/abstracts/abstract-wc-order.php#L1049-L1059

`check_and_hold_coupon_for_user` is called, which is found here:
https://github.com/woocommerce/woocommerce/blob/4.0.1/includes/data-stores/class-wc-coupon-data-store-cpt.php#L587-L595

`get_tentative_held_time` is called in that method, which is just a few lines above it starting on 479. It pulls the `woocommerce_hold_stock_minutes`, which results in 0 if the field is blank. `$held_time` then becomes 0 in `check_and_hold_coupon_for_user`, returning `null` back to `hold_coupon_for_users`, which allows the coupon to be used. 

**To Reproduce**
1. Set _Hold Stock_ to blank.
2. Create a new coupon that has a _Usage limit per user_ of `1`. 
3. Add product to cart as guest, apply coupon, and check out. 
4. Repeat step 3 using the same email, which will allow you to check out again, but shouldn't. 

**Expected behavior**
I would expect the coupon to be rejected due to it was already used by the email address. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by bmcculley** [comment]
I'm not sure if I've missed a use case of the Hold Stock time, but removing that check from from the coupon limit per user check seems to fix this issue. 

I've submitted pul request #26058 with my proposed change.
