### ISSUE TITLE
auto merge feature for users using the same email, logged in or logged out

### ISSUE THREAD

**Issue by kevin718** [woocommerce/woocommerce#26028]
Users are unable to see orders they placed, prior to creating an account. Moreover, they can't see orders they place when they're not logged in (but with the same email).

There should be some type of auto merge feature for user who use Apple Pay or Google Pay that use the same email. This data is available for the admins/store dashboard but the users cannot see orders not placed while logged in.

Most cart systems have this auto-merge feature. I have not seen an alternative plugin on woocommerce for this feature. Thanks!

**Comment by juliaamosova** [comment]
Hi @kevin718,

Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the `votes needed` label and evaluate over time if this issue collects more feedback. 

Don’t be alarmed if you don’t see any activity on this issue for a while.
