### ISSUE TITLE
Tax options

### ISSUE THREAD

**Issue by akinocakk** [woocommerce/woocommerce#26035]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

1. Go to wc-settings page
2. Click on tax tab
3. Add "Additional tax classes" input -> "%18 TAX" (text)
4. Save and update page
5. Click %18 TAX section (page=wc-settings&tab=tax&section=%18-tax)
6. The page is not displayed correctly (https://prnt.sc/rpwv4t)

**Expected behavior**
Must be: https://prnt.sc/rpwvfu

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://www.dogalindangelsin.com
Site address (URL): https://www.dogalindangelsin.com
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: tr_TR
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.3.16
PHP Post Max Size: 50 MB
PHP Time Limit: 300
PHP Max Input Vars: 6000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 10.3.22-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: dg_
Toplam veritabanı boyutu: 0.68MB
Veritabanı veri boyutu: 0.55MB
Veritabanı indis boyutu: 0.13MB
dg_woocommerce_sessions: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_woocommerce_api_keys: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_woocommerce_attribute_taxonomies: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_woocommerce_downloadable_product_permissions: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_woocommerce_order_items: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_woocommerce_order_itemmeta: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_woocommerce_tax_rates: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_woocommerce_tax_rate_locations: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_woocommerce_shipping_zones: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_woocommerce_shipping_zone_locations: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_woocommerce_shipping_zone_methods: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_woocommerce_payment_tokens: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_woocommerce_payment_tokenmeta: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_woocommerce_log: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_actionscheduler_actions: Veriler: 0.00 MB + Dizin: 0.02 MB + Motor MyISAM
dg_actionscheduler_claims: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_actionscheduler_groups: Veriler: 0.00 MB + Dizin: 0.01 MB + Motor MyISAM
dg_actionscheduler_logs: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_commentmeta: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_comments: Veriler: 0.00 MB + Dizin: 0.01 MB + Motor MyISAM
dg_links: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_options: Veriler: 0.54 MB + Dizin: 0.03 MB + Motor MyISAM
dg_postmeta: Veriler: 0.00 MB + Dizin: 0.01 MB + Motor MyISAM
dg_posts: Veriler: 0.01 MB + Dizin: 0.01 MB + Motor MyISAM
dg_termmeta: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_terms: Veriler: 0.00 MB + Dizin: 0.01 MB + Motor MyISAM
dg_term_relationships: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_term_taxonomy: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_usermeta: Veriler: 0.00 MB + Dizin: 0.01 MB + Motor MyISAM
dg_users: Veriler: 0.00 MB + Dizin: 0.01 MB + Motor MyISAM
dg_wc_admin_notes: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_wc_admin_note_actions: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_wc_category_lookup: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_wc_customer_lookup: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_wc_download_log: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_wc_order_coupon_lookup: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_wc_order_product_lookup: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_wc_order_stats: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_wc_order_tax_lookup: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_wc_product_meta_lookup: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM
dg_wc_tax_rate_classes: Veriler: 0.00 MB + Dizin: 0.01 MB + Motor MyISAM
dg_wc_webhooks: Veriler: 0.00 MB + Dizin: 0.00 MB + Motor MyISAM

### Post Type Counts ###

attachment: 1
page: 6
post: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Hata mesajları ziyaretçilere gösterilmemelidir.

### Active Plugins (1) ###

WooCommerce: (Automattic) – 4.0.1

### Inactive Plugins (1) ###

WooCommerce Admin: (WooCommerce) – 1.0.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: TRY (₺)
Currency Position: left_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Mağaza giriş sayfası: #6 - /index.php/magaza/
Sepet sayfası: #7 - /index.php/sepet/
Ödeme sayfası: #8 - /index.php/odeme/
Hesabım sayfası: #9 - /index.php/hesabim/
Şartlar ve koşullar: ❌ Sayfa ayarlanmamış

### Theme ###

Name: Twenty Twenty
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – WooCommerce'i kendinizin oluşturmadığı ana bir temada düzenliyorsanız
yardımcı bir tema kullanmanızı öneririz. Bkz.: Nasıl yardımcı tema oluşturulur?

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Tamamla: 1
Oldest: 2020-03-31 05:48:15 +0000
Newest: 2020-03-31 05:48:15 +0000

`
</details>

**Comment by tammullen** [comment]
Hi @akinocakk 

Thank you for taking the time reporting this bug, we really appreciate your help. I can reproduce it on my end. 
​
![Screenshot_2020-03-31_at_20_10_09](https://user-images.githubusercontent.com/24649833/78066018-1ac5ae80-738c-11ea-8e49-1041a48c50f8.png)

​
We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by swatipawarGS** [comment]
Hi @akinocakk ,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using WooCommerce 5.9.0 version  . 

Please find below screencast for reference :

https://user-images.githubusercontent.com/94531721/145173241-47e83c88-b889-4999-a0c6-d1b0f0c7ab3b.mp4


Please provide us more detailed and any additional steps required to repro this issue which may help us to evaluate it further.
