### ISSUE TITLE
Missing translations in i18n.data.woocommerce

### ISSUE THREAD

**Issue by tivnet** [woocommerce/woocommerce#26059]
In `languages/plugins/woocommerce-ru_RU.mo`

```
#: includes/admin/views/html-admin-page-status-report.php:827
#: includes/admin/settings/class-wc-settings-general.php:229
msgid "Currency"
msgstr "Валюта"
```

But when it comes to `dcnpgettext()`, I do not see "Currency" in `i18n.data[domain]`.
There are some strings, but not all from POMO.

**Comment by tivnet** [comment]
@rrennick The string I've mentioned does exist in the core. But in the admin package, it does not.

**Comment by rrennick** [comment]
@tivnet Yes, that's the reason I transferred the issue.

**Comment by juliaamosova** [comment]
Hi @tivnet,

Apologies for the delayed response here! We fixed the issue in WooCommerce 4.1 via https://github.com/woocommerce/woocommerce/pull/26339. Can you please confirm if translations are now working for you and let us know?

**Comment by tivnet** [comment]
Hi @juliaamosova, thanks for the update. Because I have changed my code to pass the translated string from PHP to JS, I won't be able to test it now. But, I saw the messages from others regarding that patch, and I surely trust them.

**Comment by juliaamosova** [comment]
Thanks for your follow-up @tivnet. Noted.
