### ISSUE TITLE
Package unit tests not running in Travis

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#26053]
Unit tests from REST API, WC Admin and Blocks are not running in Travis, which is not good. We need to update the Travis builds to include those tests and run them along with our tests to make sure the changes we're making are not breaking e.g. REST API (or some other included package).

**Comment by juliaamosova** [comment]
Thanks for documenting this task @peterfabian.

**Comment by rrennick** [comment]
I'll close this as we are no longer using Travis.
