### ISSUE TITLE
Sale price not updated when importing CSV

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce#26073]
**Describe the bug**

I imported a CSV like this:

![](https://d.pr/i/e617dm+)
**Image Link**: https://d.pr/i/e617dm+

Once imported, the product did not have the sale price showing until I click on Update on the product page. All values were set correctly, just not applying.

**To Reproduce**
1. Import a CSV like the one above updating existing products
2. Check the product admin
3. See the error on product page
4. Update the product
5. See how it's fixed.

**Expected behavior**

Merging the products' CSV should automatically also update the products.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment]
Hi @SiR-DanieL 

Thank you for submitting the issue. 

The default column names for sale dates are  `Date sale price starts` and `Date sale price ends`
https://github.com/woocommerce/woocommerce/blob/87acfa731da6cb75c5ff20e0dafdb038408d69b3/includes/admin/importers/mappings/default.php#L51

Can you confirm if these are also in the csv used and if they are populated.

Have `Sale start` and `Sale end` been setup as custom columns? https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Importer-&-Exporter#adding-custom-import-columns-developers

**Comment by SiR-DanieL** [comment]
They are custom but I manually mapped them to `Date sale price starts` and `Date sale price ends` before starting the import.

**Comment by batesy87** [comment]
I am also seeing this issue, if the sale start date has already passed the prices are not updated, the import does not seem to set the price to the sale price or trigger a check. 
Manually running woocommerce_scheduled_sales / wc_scheduled_sales() correctly updates the price.

**Comment by AashikP** [comment]
Hi there!

While I could originally replicate the issue, I realized that I did not check the `Update existing products checkbox`. When I did, the update was successful: https://d.pr/i/KsJBSW

Here's the CSV I used: https://d.pr/f/0Q80Pu

Note that as per [Product CSV Import Schema](https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema), this is the right format:

![https://d.pr/i/ybvyCd+](https://d.pr/i/ybvyCd+)

I did not have to use [Product CSV Import Suite](https://woocommerce.com/products/product-csv-import-suite/?aff=10486&cid=1131038) to update the product.

I'm not closing this topic yet - just in case I missed anything. Please do comment on the missing steps in that case.
