### ISSUE TITLE
Undocumented return types in wc_get_price_excluding_tax() wc_get_price_including_tax()

### ISSUE THREAD

**Issue by danielbitzer** [woocommerce/woocommerce#26092]
The doc blocks for the functions `wc_get_price_excluding_tax()` and `wc_get_price_including_tax()` state that they will return floats but they can also return strings.

https://github.com/woocommerce/woocommerce/blob/172ceb51e8e63f23142a71f23a2415bf1c5b938a/includes/wc-product-functions.php#L1035

This can lead to "non-numeric value encountered" notices and warnings. The return type should ideally be updated to `float|string` so developers are aware.

**Comment by juliaamosova** [comment]
Hi @danielbitzer,

Apologies for the delayed response and thanks for reporting it! It makes sense to update the return type indeed. Please feel free to submit a PR. Otherwise, we'd get to it at some point.
