### ISSUE TITLE
Dashboard not reporting previous periods on sales data

### ISSUE THREAD

**Issue by rldesign62** [woocommerce/woocommerce#26106]
The WooCommerce dashboard overview will not allow us to compare current sales data to data from previous time periods. It always shows previous prior sales as $0.00.

Here's the system status info:

`
### WordPress Environment ###

WordPress address (URL): https://kentuckysoapsandsuch.com
Site address (URL): https://kentuckysoapsandsuch.com
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: 5.4
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.16-1+ubuntu18.04.1+deb.sury.org+1
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.58.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.6.41-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: wp_
Total Database Size: 68.56MB
Database Data Size: 45.98MB
Database Index Size: 22.58MB
wp_woocommerce_sessions: Data: 4.71MB + Index: 0.15MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.19MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 5.52MB + Index: 4.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 1.50MB + Index: 0.56MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.52MB + Index: 0.50MB + Engine InnoDB
wp_ac_abandoned_cart_history_lite: Data: 0.23MB + Index: 0.00MB + Engine MyISAM
wp_ac_email_templates_lite: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ac_guest_abandoned_cart_history_lite: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ac_sent_history_lite: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_chat_lines: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_chat_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_chat_online: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_chat_visitors: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_comments: Data: 2.52MB + Index: 0.94MB + Engine InnoDB
wp_cptch_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cptch_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cptch_whitelist: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 5.31MB + Index: 0.13MB + Engine InnoDB
wp_phppc_functions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 12.52MB + Index: 9.98MB + Engine InnoDB
wp_posts: Data: 4.52MB + Index: 0.81MB + Engine InnoDB
wp_revslider_css: Data: 0.09MB + Index: 0.00MB + Engine MyISAM
wp_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_revslider_sliders: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_revslider_slides: Data: 0.08MB + Index: 0.00MB + Engine MyISAM
wp_revslider_static_slides: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_taxonomymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 4.50MB + Index: 3.97MB + Engine InnoDB
wp_users: Data: 0.30MB + Index: 0.30MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.04MB + Index: 0.04MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.13MB + Index: 0.12MB + Engine MyISAM
wp_wc_order_stats: Data: 0.04MB + Index: 0.03MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.03MB + Index: 0.04MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpgmza: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_category_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_polygon: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_polylines: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.08MB + Index: 0.06MB + Engine InnoDB

### Post Type Counts ###

acf: 2
acf-field: 2
acf-field-group: 2
amn_mi-lite: 3
attachment: 749
jetpack_migration: 2
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
nav_menu_item: 44
option-tree: 1
page: 24
post: 2
product: 142
product_variation: 257
revision: 217
shop_coupon: 20
shop_order: 2125
shop_order_refund: 16
staticblocks: 1
testimonial: 33
testimonial_rotator: 2
wp_log: 60
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (28) ###

Advanced Custom Fields: by Elliot Condon – 5.8.9
Akismet Anti-Spam: by Automattic – 4.1.4
Authorize.Net CIM for WooCommerce: by Cardpay Solutions
Inc. – 2.0.13

Better Search Replace: by Delicious Brains – 1.3.3
Captcha: by simplywordpress – 4.4.5
Classic Editor: by WordPress Contributors – 1.5
CMB2: by CMB2 team – 2.7.0
Coming soon and Maintenance mode WpDevArt: by wpdevart – 3.1.7
Constant Contact Plugin for WordPress: by Katz Web Services
Inc. – 4.1.1

Contact Form 7: by Takayuki Miyoshi – 5.1.7
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.10.4
Jetpack by WordPress.com: by Automattic – 8.3
WPBakery Page Builder: by Michael M - WPBakery.com – 6.1
Legenda Core: by 8theme – 1.0.0
Redux Framework: by Team Redux – 3.6.18
Slider Revolution: by ThemePunch – 5.4.7.3
Screets Live Chat: by Screets – 2.8.7
SSL Insecure Content Fixer: by WebAware – 2.7.2
Testimonial Rotator: by Hal Gatewood – 3.0.2
WooCommerce Address Validation: by SkyVerge – 2.6.3
WooCommerce Admin: by WooCommerce – 1.0.3
WooCommerce Services: by Automattic – 1.22.5
WooCommerce USPS Shipping: by WooCommerce – 4.4.40
WooCommerce TM Extra Product Options: by themeComplete – 5.0.8
WooCommerce: by Automattic – 4.0.1
WooCommerce Multi-Step Checkout: by SilkyPress – 2.9
WP Rocket: by WP Media – 3.5.2
YITH WooCommerce Wishlist: by YITH – 3.0.9

### Inactive Plugins (6) ###

Abandoned Cart Lite for WooCommerce: by Tyche Softwares – 5.7.2
Check Email: by Chris Taylor – 0.5.7
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.24
Velvet Blues Update URLs: by VelvetBlues.com – 3.2.9
WooCommerce Autoresponder: by wpstriker – 1.7 – Not tested with the active version of WooCommerce
WooCommerce Blocks: by Automattic – 2.5.15

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached Redux

### Must Use Plugins (4) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.6.4
WP Engine Seamless Login Plugin: by WP Engine – 1.5.3
WP Engine Security Auditor: by wpengine – 1.0.8
WP Engine System: by WP Engine – 4.0.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #13 - /products/
Cart: #34 - /cart/
Checkout: #35 - /checkout/
My account: #36 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Legenda Child
Version: 0.0.1
Author URL: http://8theme.com
Child Theme: ✔
Parent Theme Name: Legenda
Parent Theme Version: 4.2.1
Parent Theme Author URL: http://themeforest.net/user/8theme
WooCommerce Support: ✔

### Templates ###

Overrides: legenda-child/woocommerce/archive-product.php
legenda/woocommerce/cart/cart-empty.php
/nas/content/live/kysoaps/wp-content/plugins/woocommerce-tm-extra-product-options/templates/cart/cart-item-data.php
legenda/woocommerce/cart/cart-shipping.php
legenda/woocommerce/cart/cart.php
legenda/woocommerce/cart/cross-sells.php
legenda/woocommerce/cart/mini-cart.php
legenda-child/woocommerce/checkout/form-billing.php version 3.0.9 is out of date. The core version is 3.6.0
legenda-child/woocommerce/checkout/form-checkout.php version 2.3.0 is out of date. The core version is 3.5.0
legenda-child/woocommerce/checkout/form-coupon.php version 3.3.0 is out of date. The core version is 3.4.4
legenda-child/woocommerce/checkout/form-login.php version 2.0.0 is out of date. The core version is 3.8.0
legenda-child/woocommerce/checkout/form-shipping.php version 3.0.9 is out of date. The core version is 3.6.0
legenda-child/woocommerce/checkout/review-order.php version 3.3.0 is out of date. The core version is 3.8.0
legenda/woocommerce/content-product.php
legenda/woocommerce/content-product_cat.php
legenda-child/woocommerce/content-single-product.php version 3.4.0 is out of date. The core version is 3.6.0
legenda/woocommerce/global/form-login.php
legenda/woocommerce/global/quantity-input.php version 3.6.0 is out of date. The core version is 4.0.0
legenda/woocommerce/loop/add-to-cart.php
legenda/woocommerce/loop/loop-end.php
legenda/woocommerce/loop/loop-start.php
legenda/woocommerce/loop/no-products-found.php
legenda/woocommerce/loop/pagination.php
legenda/woocommerce/loop/rating.php
legenda/woocommerce/myaccount/form-login.php
legenda/woocommerce/myaccount/navigation.php
legenda/woocommerce/single-product/add-to-cart/external.php
legenda/woocommerce/single-product/add-to-cart/simple.php
legenda/woocommerce/single-product/meta.php
legenda/woocommerce/single-product/product-image.php
legenda/woocommerce/single-product/product-thumbnails.php
legenda/woocommerce/single-product/related.php
legenda/woocommerce/single-product/short-description.php
legenda/woocommerce/single-product/tabs/tabs.php
legenda/woocommerce/single-product/title.php
legenda/woocommerce/single-product/up-sells.php
legenda/woocommerce/single-product-reviews.php
legenda/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

### Address Validation ###

Active Provider: SmartyStreets
Configured: ✔
Include Plus-four code?: Yes
Debug Mode: No
Geocode Addresses: No
Classify Addresses: No
Force Customer to look-up address via Postcode: No

### Action Scheduler ###

Complete: 1,852
Oldest: 2020-03-07 18:11:24 +0000
Newest: 2020-04-07 17:18:06 +0000

Failed: 1
Oldest: –
Newest: –

Pending: 5
Oldest: 2020-04-07 18:18:06 +0000
Newest: 2020-04-10 16:31:12 +0000

`

**Comment by Blokbout** [comment]
Hi, I'm having the same issue. 
Only the sales data since the beginning of march is visible in the dashboard. I noticed that the order numbers are also sequential since then, unlike before.
Any help would be greatly appreciated.

**Comment by Blokbout** [comment]
> Hi, I'm having the same issue.
> Only the sales data since the beginning of march is visible in the dashboard. I've noticed that the order numbers are also sequential since then, unlike before.
> Any help would be greatly appreciated.

It appears that historical data from before the last Woocommerce update is not showing by default.
This worked for me:
Analytics > Settings > Import historical data

Hope this helps.

**Comment by rldesign62** [comment]
Problem solved. Thanks for the info!
