### ISSUE TITLE
[GlobalStep - 4.1 beta 1]Incorrect file format TXT is displayed in error message upon importing invalid file.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#26123]
**Step to Reproduce:**
1. Create a test site using JN. 
2. Complete initial screens and go to dashboard.
3. Click on "Add Products".
4. Click on "Import" button.
5. Click on "Choose file".
6. Upload JPG or PNG file.
7. Observe that incorrect file format TXT is displayed in error message upon importing invalid file.

**Actual Result:**
Incorrect file format TXT is displayed in error message upon importing invalid file.

Expected Result:
User should be able to import CSV and XML.

![5  IncorrectMsg](https://user-images.githubusercontent.com/41110392/78811624-c18ef800-79e7-11ea-8a5f-826ee6cce969.png)

**Comment by juliaamosova** [comment]
Hi @gglobalstep,

Thanks for opening the issue! TXT file, however, is an acceptable file format for the CSV import:

https://github.com/woocommerce/woocommerce/blob/a7d57a248ed03dac7bad119e71f83dd961f43cb3/includes/admin/importers/class-wc-product-csv-importer-controller.php#L108-L121

I wonder if we need to make it more clear in the upload section that TXT file format is acceptable. Something along the following:

![txt](https://user-images.githubusercontent.com/19143190/79262258-0808aa80-7e5f-11ea-97a4-5ed58f5a9a53.jpg)

I am marking this issue as an `enhancement` for now.
