### ISSUE TITLE
[GlobalStep - 4.1 beta 1]On Windows 7: Chrome, while adding a Product instead of “Rs” symbol box is displayed

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#26122]
**Steps to Reproduce:**
1. Create a test site using JN. 
2. Complete initial screens and go to dashboard.
3. Click on "Add your first product".
4. Click on "Add manually".
5. Enter all the details.
6. Go to Product Data section.
7. Observe that "Rs" symbol next to Regular Price and Sale price displayed as a box.

**Note:**
Similar issue is observed on "Setup Shipping" page

**Actual Result:**
While adding a Product instead of “Rs” symbol box is displayed

**Expected Result:**
“Rs” symbol should be displayed.

![4  Instead of Rs symbol box is displayed_A](https://user-images.githubusercontent.com/41110392/78811437-7ffe4d00-79e7-11ea-8186-f4469a62d77c.png)
![4  Instead of Rs symbol box is displayed_B](https://user-images.githubusercontent.com/41110392/78811447-8391d400-79e7-11ea-86c3-5011d2c2b969.png)

**Comment by juliaamosova** [comment]
Hi @gglobalstep,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported. Everything is working as expected on my end. I must note that I tested using [Browserstack](https://www.browserstack.com/) as I don't have access to the Windows machine but I don't think it makes any difference as Browserstack does the job in this case. 

Windows 7 - Chrome 81 - using USD as a currency:

![usd](https://user-images.githubusercontent.com/19143190/79258708-8e21f280-7e59-11ea-809c-131a29d57f3f.jpg)

Windows 7 - Chrome 81 - using Indian Rupee as a currency:

![ind_rupee](https://user-images.githubusercontent.com/19143190/79258892-d3462480-7e59-11ea-9d5f-a629f8fc5b92.jpg)

Could it be that you tested with older version of Chrome?

**Comment by gglobalstep** [comment]
Hi @juliaamosova 
We are able to reproduce this issue ease find more information as below:
Screen Resolution: 1366 x 768
Chrome v81.0.4044.92(64 bit)

![#26122_UpdatedAttachment_1](https://user-images.githubusercontent.com/41110392/79482865-0d1c5400-802f-11ea-86a8-f1588c43ff28.png)
![#26122_UpdatedAttachment_2](https://user-images.githubusercontent.com/41110392/79482872-10afdb00-802f-11ea-83de-4e35cba32569.png)

**Comment by tammullen** [comment]
Hi @gglobalstep 

I have tried this with Chrome on Windows 10 and can't recreate it.

Advice from related issue: https://github.com/woocommerce/woocommerce/issues/23933

You can check in general if currency symbols can be displayed correctly on your test machine by visiting this page https://en.wikipedia.org/wiki/Currency_symbol

Also there is a known issue with Windows 7 and the rupee symbol that requires a patch
https://support.microsoft.com/en-us/topic/an-update-to-support-the-new-currency-symbol-for-the-indian-rupee-in-windows-vista-in-windows-server-2008-in-windows-7-and-in-windows-server-2008-r2-cb129c3b-8de4-03ed-e911-0a71a5e583ec

Closing as it doesn't look like this is a WooCommerce issue
