### ISSUE TITLE
[GlobalStep - 4.1 beta 1]Upon searching for a product on "All Products" page gets refresh and user redirects to the top of the page.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#26126]
**Step to Reproduce:**
1. Create a test site using JN. 
2. Complete initial screens and go to dashboard.
3. Click on "All Products".
4. Enter some text on "Search" box and click on "Search Products" button.
5. Observe that user redirects to the top of the page.

**Actual Result:**
Upon searching for a product on "All Products" page gets refresh and user redirects to the top of the page.

**Expected Result:**
Se
[8. Serach Issue.zip](https://github.com/woocommerce/woocommerce/files/4451800/8.Serach.Issue.zip)
arch results should be displayed and user should not redirect to the top.

**Comment by juliaamosova** [comment]
Hi @gglobalstep,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. 

I made a gif to show that I am able to search for a product without bein redirected to the top of the page:

![](http://g.recordit.co/gPC8jIU4YR.gif)

Please provide us with more details about the issue which may help us to evaluate it further. Am I missing any steps to reproduce the behavior?

**Comment by gglobalstep** [comment]
Hi @juliaamosova
We are able to reproduce this issue with same steps as mentioned above.
Also we observed that in GIF provided by you we can't see notification messages of Jurassic Ninja and other plugins.
Can that be the cause?


Environment tested on is as below:
Screen Resolution: 1366 x 768
Chrome v81.0.4044.92(64 bit)

[#26126_Updated.zip](https://github.com/woocommerce/woocommerce/files/4488648/26126_Updated.zip)

**Comment by juliaamosova** [comment]
Thanks for the additional details! I can see the issue now - it is more visible when notices are present:

![](http://g.recordit.co/uelWJeN4IY.gif)

I think this is currently working as expected but I will confirm.

**Comment by rrennick** [comment]
This is the way the list table search works in WordPress because the search loads a new page. You can see the same behaviour on the Orders or Posts list.
