### ISSUE TITLE
Warning in Import CSV in tax settings

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#26137]
**Step to Reproduce:**
1. Create a test site using JN. 
2. Complete initial screens and go to dashboard.
3. Click on "Setup Tax".
4. Click on "Configure" button.
5. Click on "Tax".
6. Click on "Standard Rates".
7. Click on "Import CSV".
8. Upload a CSV file.
9. Observe Query Monitor on the top PHP error is displayed in yellow.

**Actual Result:**
A PHP error is thrown in query monitor upon clicking Import CSV option during configuration of Tax Setup.

**Expected Result:**
Plugin should be error free.

![13](https://user-images.githubusercontent.com/41110392/78918120-8a831a00-7aad-11ea-832f-db5c469fca6b.jpg)

**Comment by juliaamosova** [comment]
Hi @gglobalstep,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. 

I can successfully sample import tax rates CSV file (downloaded from [here](https://github.com/woocommerce/woocommerce/blob/master/sample-data/sample_tax_rates.csv)):

![tax_rates](https://user-images.githubusercontent.com/19143190/79269896-283e6680-7e6b-11ea-9a99-36989d54bf28.jpg)

I've tried on 2 different sites:

- Jurassic Nina
- Pressable

I will leave this open for a bit in case others will report the same issue.

**Comment by gglobalstep** [comment]
@juliaamosova Sorry for the confusion. Upload CSV step is not needed this error triggers as soon as you click on Import CSV option. Could you please confirm if this information helps?

**Comment by rrennick** [comment]
The debug warning is

```
[16-Jun-2023 18:37:26 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /Users/ronrennick/Sites/wc/wp-content/woocommerce/plugins/woocommerce/src/Internal/Admin/Orders/PageController.php on line 146
```

**Comment by rrennick** [comment]
I believe this one has been fixed.
