### ISSUE TITLE
Slow get last order query

### ISSUE THREAD

**Issue by peixotorms** [woocommerce/woocommerce#26135]
This issue, is a bit similar to #12080 but not exactly.

On our shop, with 85 products but around 120k orders (5 to 10k per month or so), we have integrated Klaviyo which makes a request to the v1 api, in this format:

`yoursite.com/wc-api/v1/orders?filter[updated_at_min]=2020-04-01T20:47:49Z&page=3&filter[limit]=50&consumer_key=abcdef&consumer_secret=12345`

This query takes somewhere from 43 seconds to 120 seconds, depending on the server used.

I profiled it with php xdebug, and it comes down to the same situation as #12080 where it chokes on the last order query.

WC_Data_Store->get_last_order @ 307 called from WC_API_Customers->get_customer @ 132, under 
`wp-content/plugins/woocommerce/includes/legacy/api/v1/class-wc-api-customers.php#line132`

```
https://i.imgur.com/wu8CUoD.png
https://i.imgur.com/wnSFsbr.png
```
In this case, each query takes around 2 to 3 seconds, but it's done per user, 38 times.

Example from the slow query logs:

```
SELECT posts.ID
			FROM wp_posts AS posts
			LEFT JOIN wp_postmeta AS meta on posts.ID = meta.post_id
			WHERE meta.meta_key = '_customer_user'
			AND   meta.meta_value = '59227'
			AND   posts.post_type = 'shop_order'
			AND   posts.post_status IN ( 'wc-pending','wc-processing','wc-on-hold','wc-completed','wc-cancelled','wc-refunded','wc-failed' )
			ORDER BY posts.ID DESC;
# Time: 2020-04-09T11:20:55.776004Z
# User@Host: sample[sample] @ localhost []  Id:     2
# Schema: sample  Last_errno: 0  Killed: 0
# Query_time: 3.319790  Lock_time: 0.000227  Rows_sent: 7  Rows_examined: 120113  Rows_affected: 0
# Bytes_sent: 171
```

I read that woocommerce was moving from postmeta to their own tables, but when will it happen?

With a custom table, we could add an index to the meta_key column.

For example, `SELECT MAX(LENGTH(meta_value)) FROM wp_postmeta WHERE meta_key = '_customer_user';` return 5, however the longest row with different meta_key is 25k chars.

We can improve this query with indexes, but ideally, you would have this in separate tables specific for these situations:
```
ALTER TABLE `wp_posts` ADD INDEX(`post_status`);
ALTER TABLE `wp_posts` ADD INDEX(`post_type`);
ALTER TABLE `wp_postmeta` ADD INDEX(meta_value(191));
```

Any way to speed up that query on the api request, on WC4?

**Comment by peterfabian** [comment]
Hi @peixotorms 

The [legacy API v1 you're using is due for removal after September 2016](https://github.com/woocommerce/woocommerce-rest-api/blob/master/.github/CONTRIBUTING.md#deprecation-of-older-versions). We're keeping it around only for backwards compatibility reasons. We suggest moving to the new REST API, which gets further updates going forward. I'm sorry, but we won't be fixing bugs in this API version anymore. If you need to add indexes to make these queries faster on your installation, please feel free to do so. 

We're always exploring ways to improve performance in backward compatible ways, so custom db tables are not at the top of our agenda for now, but we have plans related to them in our long term vision. In the meantime, you can try to use a plugin from LiquidWeb: https://github.com/liquidweb/woocommerce-custom-orders-table--of course first on your staging site to see if it's compatible with your setup. 

Thanks for understanding.

**Comment by peixotorms** [comment]
Thanks. It turned out Klaviyo had provided the client with a legacy plugin and that's why they were using v1 api and not receiving updates, which already make use of v3. I forgot to close this, sorry. Thanks anyway.

**Comment by peterfabian** [comment]
Thanks for reporting back!
