### ISSUE TITLE
[GlobalStep - 4.1 beta 1] On window 7(Firefox 64-bit/32-bit), dashboard assets fails to load(takes approx. 10-20 mins).

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#26144]
**Step to Reproduce:**
1. Create a test site using JN. 
2. Complete initial screens and go to dashboard.
3. Observe that dashboard asset fails to load.

**Note:** 
Dashboard assets load after approx. 10-20 mins.

**Actual Result:**
On window 7(Firefox 64-bit/32-bit), dashboard assets fails to load(takes approx. 10-20 mins).

**Expected Result:**
Assets should load properly.

![20](https://user-images.githubusercontent.com/41110392/78920942-c6b87980-7ab1-11ea-9e4a-be219ebb9cbf.png)

**Comment by juliaamosova** [comment]
Hi @gglobalstep,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported. Everything is working as expected on my end. I tested using Browserstack - [they claim their Windows 7 Firefox browser is 64-bit](https://www.browserstack.com/question/621):

![assets_loading](https://user-images.githubusercontent.com/19143190/79375882-58e3d600-7f27-11ea-9615-90b8e3881330.jpg)

Not sure what we can do about this issue. There could be all kinds of reasons why the assets are not loading. It is also often difficult to reproduce. 

I am going to close this issue for now but will keep it in mind in case we'd get more reports.
