### ISSUE TITLE
When will all product variations also have a low stock threshold? 

### ISSUE THREAD

**Issue by eyeconimaging** [woocommerce/woocommerce#26164]
When will all product variations also have a low stock threshold? 
The other thread has been closed with no action taken and people still want this?!?

**Comment by tammullen** [comment]
Thanks @eyeconimaging for raising this.
We are closing your issue in favor of the previously submitted issue https://github.com/woocommerce/woocommerce/issues/22706. 

Thanks for sharing your feedback and voting there and we will provide an update there soon as we evaluate the feedback on it.

**Comment by Fiorinol** [comment]
The linked issue is closed and seems to be getting no traction.
