### ISSUE TITLE
Problem with Action Scheduler since migration to 4.0.1

### ISSUE THREAD

**Issue by juliomachado** [woocommerce/woocommerce#26170]
I noticed that since I updated to version 4.0.1, I can't get rid of the "WooCommerce is updating the database in background" message. Taking a look in my wp_actionscheduler_actions table, I noticed it has more than a million records, all with [“wc_admin_update_0251_db_version”] or [“wc_admin_update_0251_remove_unsnooze_action”] value in column args and always pending.

I truncated the table but, in less than an hour, another 3000 records were generated...

**Comment by tammullen** [comment]
Hi @juliomachado 

Thank you for reporting the issue. There is a similar issue that has been reported previously here https://github.com/woocommerce/action-scheduler/issues/517. 
Please have a look at it and continue sharing your feedback there. We are closing your issue in favor of that issue. 
 
If I missed something, please leave a comment and we will take a second look.

**Comment by rrennick** [comment]
This was an issue in one of the WC Admin update routines: https://github.com/woocommerce/woocommerce-admin/issues/3982
