### ISSUE TITLE
Remove the onboarding split test screen

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce#26173]
I think that we should remove the onboarding split test screen, considering that we're going to move the new obw to 100% of users and that we decided to stop installing wc-admin:  https://d.pr/i/yCgswA

cc @timmyc @vedanshujain

**Comment by juliaamosova** [comment]
I plus one to this - I think the split test screen should be removed at this point. We can also add `Not right now` option to the Store Details section which will be the first section that users see when they start OBW.

**Comment by timmyc** [comment]
Somewhat related: https://github.com/woocommerce/woocommerce-admin/issues/4123

Though I haven't been able to reproduce this myself - wondering if the splash screen still might serve a purpose to allow users to exit out of the OBW completely.

**Comment by pmcpinto** [comment]
> wondering if the splash screen still might serve a purpose to allow users to exit out of the OBW completely.

Afaik the splash screen is only displayed once, so the user can't go back to it. As I see it, at this point the splash screen is mainly creating friction. But it doesn't hurt to wait and remove it on the upcoming release instead of doing it in 4.1

**Comment by pmcpinto** [comment]
Is it possible to remove this screen in 4.3? cc @juliaamosova (I'm not sure who's going to be the release lead on this one 😄 )

**Comment by peterfabian** [comment]
We can also remove the old OBW code, I assume (except public methods/functions/classes, I guess).

**Comment by juliaamosova** [comment]
@pmcpinto I see @peterfabian (who is the release lead of 4.3 along with @Konamiman) already replied. 

On my end, noting that I've been waiting for this task to be completed so that we could also remove the old OBW e2e test: https://github.com/woocommerce/woocommerce/blob/master/tests/e2e/utils/components.js#L207-L344.

**Comment by pmcpinto** [comment]
Hey @rrennick I think this was supposed to be removed in 4.4 but it seems that it wasn't merged. Is it possible to still include it in 4.4 or do we need to wait until 4.5? Tks

cc @Konamiman

**Comment by rrennick** [comment]
@pmcpinto We needed to do a companion PR in WC Admin to replace some of the screen registration (eg. help tab). Was that done? cc @joshuatf

**Comment by pmcpinto** [comment]
@rrennick just a heads that Joshua already merged the [PR](https://github.com/woocommerce/woocommerce-admin/pull/4999) in the WC Admin side. So this screen will be removed in 4.6, correct?

**Comment by rrennick** [comment]
@pmcpinto Now just waiting for review.
