### ISSUE TITLE
The wc_product_meta_lookup table

### ISSUE THREAD

**Issue by stormit** [woocommerce/woocommerce#26184]
Hello,

I'm facing a problem with importer. I use the **One Click Demo Import** plugin to import content from another site. The problem is the **wc_product_meta_lookup** table is blank after importing. So, some functions do not work correctly. For example, the **wc_get_product_ids_on_sale** function returns an empty array (I delete the **wc_products_onsale** transient after importing) because the wc_product_meta_lookup table is empty. Is there any way which updates the wc_product_meta_lookup table after importing?

Thank you!

**Comment by bampisSyk** [comment]
You can force regenerate the lookup table either by clicking the Regenerate button from Woocommece Tools in the admin panel or by using a snippet like the on bellow
`define( 'WP_CLI', true );

    if ( ! wc_update_product_lookup_tables_is_running() ) {
        wc_update_product_lookup_tables();
    }`

Code is self explanatory, beware the define on top of it
I hope this solves your issue

**Comment by stormit** [comment]
Thank you very much! It worked :)
