### ISSUE TITLE
woocommerce_cleanup_sessions is not in the cron events and my sessions table is over 5GB

### ISSUE THREAD

**Issue by jpSimkins** [woocommerce/woocommerce#26181]
**Describe the bug**
My sessions table is over 5GB. I searched and found that `woocommerce_cleanup_sessions` is a cron that is supposed to purge expired sessions. I have a plugin (Cron Events) that shows all registered cron event, `woocommerce_cleanup_sessions` is not on the list. I also checked Scheduled Actions as I wasn't sure if it may appear under that. Seems it doesn't exist for either.

**To Reproduce**
I do not know how to reproduce. I just found this out on our PROD system.

**Expected behavior**
I expected to see the cron event or the scheduled action.

I am not sure what to do to enable this cron event. I cannot disable and re-enable the plugin as this would affect PROD. I would have to disable other systems and that is a problem. Ideally, a script to add the event would be ideal.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://www.freetv.com/wordpress
Site address (URL): https://www.freetv.com
WC Version: 3.9.2
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: ❌ 5.3.2 - There is a newer version of WordPress available (5.4)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 () OpenSSL/1.0.2k-fips mod_fcgid/2.3.9
PHP Version: 7.2.28
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.0.2k

SUHOSIN Installed: –
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.2
WC Database Prefix: oly_
Total Database Size: 6302.71MB
Database Data Size: 5721.89MB
Database Index Size: 580.82MB
oly_woocommerce_sessions: Data: 5289.50MB + Index: 276.75MB + Engine InnoDB
oly_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
oly_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
oly_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
oly_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
oly_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
oly_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
oly_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
oly_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
oly_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
oly_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
oly_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
oly_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
oly_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
oly_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
oly_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
oly_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
oly_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
oly_api_device_regcodes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
oly_api_device_tokens: Data: 6.52MB + Index: 16.16MB + Engine InnoDB
oly_avod_admeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
oly_avod_ads: Data: 2.52MB + Index: 4.55MB + Engine InnoDB
oly_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
oly_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
oly_icl_cms_nav_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
oly_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
oly_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
oly_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
oly_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
oly_icl_languages_translations: Data: 0.20MB + Index: 0.13MB + Engine InnoDB
oly_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
oly_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
oly_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
oly_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
oly_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
oly_icl_strings: Data: 4.52MB + Index: 6.70MB + Engine InnoDB
oly_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
oly_icl_string_pages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
oly_icl_string_positions: Data: 2.31MB + Index: 0.17MB + Engine InnoDB
oly_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
oly_icl_string_translations: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
oly_icl_string_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
oly_icl_translate: Data: 1.41MB + Index: 0.02MB + Engine InnoDB
oly_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
oly_icl_translations: Data: 2.52MB + Index: 7.06MB + Engine InnoDB
oly_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
oly_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
oly_icl_translation_status: Data: 0.47MB + Index: 0.08MB + Engine InnoDB
oly_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
oly_olymp_schedules: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
oly_olymp_schedules_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
oly_options: Data: 211.09MB + Index: 126.14MB + Engine InnoDB
oly_postmeta: Data: 70.52MB + Index: 13.91MB + Engine InnoDB
oly_posts: Data: 15.44MB + Index: 8.95MB + Engine InnoDB
oly_query_override_terms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
oly_query_wrangler: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
oly_sdi_olyott_wc_iap: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
oly_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
oly_terms: Data: 0.14MB + Index: 0.16MB + Engine InnoDB
oly_term_relationships: Data: 5.17MB + Index: 3.25MB + Engine InnoDB
oly_term_taxonomy: Data: 0.13MB + Index: 0.16MB + Engine InnoDB
oly_usermeta: Data: 70.50MB + Index: 70.03MB + Engine InnoDB
oly_users: Data: 9.52MB + Index: 10.55MB + Engine InnoDB
oly_user_content_log: Data: 6.52MB + Index: 14.06MB + Engine InnoDB
oly_user_content_meta: Data: 8.50MB + Index: 19.05MB + Engine InnoDB
oly_user_parental_control: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
oly_user_watchlist: Data: 1.45MB + Index: 1.00MB + Engine InnoDB
oly_w3tc_cdn_pathmap: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
oly_w3tc_cdn_queue: Data: 11.52MB + Index: 0.44MB + Engine InnoDB
oly_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
oly_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
oly_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
oly_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
oly_wpfront_ure_login_redirect: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
oly_wpfront_ure_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
oly_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
oly_yoast_seo_meta: Data: 0.16MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

api-app: 12
api-screens: 10
attachment: 4496
custom_css: 1
elementor_library: 15
nav_menu_item: 85
networks: 2
page: 52
post: 1
product: 42
revision: 211
series: 1053
user-dashboard: 4
video: 677
wc_membership_plan: 2
wc_user_membership: 54623

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (36) ###

WPML Multilingual CMS: by OnTheGoSystems – 4.3.6
OpenID Connect Generic: by daggerhart – 3.5.0
Disable All WordPress Updates: by Oliver Schlöbe – 1.6.6
Elementor Pro: by Elementor.com – 2.8.4
Elementor: by Elementor.com – 2.9.2
Enhanced Media Library: by wpUXsolutions – 2.7.2
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.10.4
Oly If Menu - Visibility control for menu items: by Olympusat – 0.12.2
Oly OTT API: by Olympusat – 1.3.1
Oly OTT AVOD: by Olympusat – 2.0.0
Olympusat Schedule: by Olympusat  – 4.1.0
OlyOTT Ingestion: by Olympusat – 1.0.0
Query Wrangler: by Jonathan Daggerhart – 1.5.44
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.3
Safe SVG: by Daryll Doyle – 1.9.8
SDI OlyOTT WooCommerce - IAP (In App Purchases): by SDI & Olympusat – 1.0.0 – Not tested with the active version of WooCommerce
YIKES Simple Taxonomy Ordering: by YIKES
Inc. – 2.1.0

SMTP Mailer: by naa986 – 1.0.8
Super Socializer: by Team Heateor – 7.12.38
Taxomony Metabox: by David Cramer – 1.0.0
User Switching: by John Blackbourn & contributors – 1.5.4
W3 Total Cache: by BoldGrid – 0.13.1
WooCommerce Authorize.Net Gateway: by SkyVerge – 3.2.1
WooCommerce Stripe Gateway: by WooCommerce – 4.3.2
WooCommerce Gateways Country Limiter: by OnTheGoSystems – 1.4 – Not tested with the active version of WooCommerce
WooCommerce Memberships: by SkyVerge – 1.17.0
WooCommerce Multilingual: by OnTheGoSystems – 4.7.7 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by WooCommerce – 3.0.1
WooCommerce: by Automattic – 3.9.2
Yoast SEO: by Team Yoast – 13.1
WP Crontrol: by John Blackbourn & crontributors – 1.7.1
WP Force SSL: by WebFactory Ltd – 1.55
WPML CMS Nav: by OnTheGoSystems – 1.5.2
WPML Media: by OnTheGoSystems – 2.5.5
WPML String Translation: by OnTheGoSystems – 3.0.6
WPML Translation Management: by OnTheGoSystems – 2.9.4

### Inactive Plugins (9) ###

Cookie Notice: by dFactory – 1.2.50
Gravity Forms: by rocketgenius – 2.3.3
Oly Social: by Olympusat – 1.0
Preview E-mails for WooCommerce: by Digamber Pradhan – 1.6.3
Stop Emails: by Sal Ferrarello – 1.2.0
WooCommerce Blocks: by Automattic – 2.5.13
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.20
WordPress Importer: by wordpressdotorg – 0.6.4
Yoast SEO Multilingual: by OnTheGoSystems – 1.0.3

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db-error.php: db-error.php
db.php: HyperDB

### Must Use Plugins (1) ###

Oly OTT Core: by  – 1.0.0

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: ❌ Page visibility should be public
Cart: #11652 - /cart-2/
Checkout: #11654 - /checkout-2/
My account: #11656 - /my-account/
Terms and conditions: #3641 - /term-of-use/?lang=en

### Theme ###

Name: OlyOTT
Version: 1.0.0
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: oly-ott/woocommerce/archive-product.php
oly-ott/woocommerce/checkout/form-checkout.php
oly-ott/woocommerce/checkout/form-coupon.php
oly-ott/woocommerce/checkout/payment-method.php
oly-ott/woocommerce/checkout/terms.php
oly-ott/woocommerce/checkout/thankyou.php
oly-ott/woocommerce/content-product.php
oly-ott/woocommerce/emails/customer-processing-order.php
oly-ott/woocommerce/emails/email-footer.php
oly-ott/woocommerce/emails/email-header.php
oly-ott/woocommerce/emails/email-styles.php
oly-ott/woocommerce/global/breadcrumb.php
oly-ott/woocommerce/global/sidebar.php
oly-ott/woocommerce/global/wrapper-end.php
oly-ott/woocommerce/global/wrapper-start.php
oly-ott/woocommerce/myaccount/dashboard.php
oly-ott/woocommerce/myaccount/form-edit-account.php
oly-ott/woocommerce/myaccount/form-login.php
oly-ott/woocommerce/myaccount/form-lost-password.php
oly-ott/woocommerce/myaccount/form-reset-password.php
oly-ott/woocommerce/myaccount/lost-password-confirmation.php
oly-ott/woocommerce/myaccount/my-address.php
oly-ott/woocommerce/myaccount/navigation.php
oly-ott/woocommerce/myaccount/orders.php
oly-ott/woocommerce/myaccount/payment-methods.php
oly-ott/woocommerce/order/order-details-customer.php
oly-ott/woocommerce/single-product.php

### Memberships ###

Restriction mode:: Hide content only
Public content:: –
Excluded from discounts:: –
Membership plans:: 2
Plus:: Members: 0Access method: Product(s) purchaseAccess length: Specific length (1 months)Subscription: OptionalInstallment plan: No
Free:: Members: 54623Access method: Product(s) purchaseAccess length: Unlimited Subscription: No

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://www.freetv.com/wordpress
Subscriptions Template Theme Overrides: oly-ott/woocommerce/myaccount/subscriptions.php
Subscription Statuses: –
WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — Florida

### Action Scheduler ###

Complete: 3
Oldest: 2020-03-19 11:23:06 -0400
Newest: 2020-04-13 09:03:33 -0400

`
</details>

**Comment by jpSimkins** [comment]
I was able to manually purged the data by using my own query directly on the DB. I would like to know how to enable the cron event. I am not even sure how the event was removed. We did update from WC version 2 but I don't believe that is the cause as this would have been a bigger issue much earlier I assume.

**Comment by jpSimkins** [comment]
I toggled the plugin to repair the issue. Not sure how these disappeared but it's resolved for now.

**Comment by bobmulder** [comment]
I'm not sure, but I might be facing the same sort issue on the actionscheduler tables. It's not purging for a multisite of mine. Can you explain where you toggled the plugin to repair the issue, @jpSimkins?

**Comment by jpSimkins** [comment]
@bobmulder I just deactivated and re-activated the plugin.

**Comment by bobmulder** [comment]
Oh haha right, I was thinking of a tool within WooCommerce to repair this, but it's so easy :)
