### ISSUE TITLE
invisible password reset link in e-mail using dark theme

### ISSUE THREAD

**Issue by mcantsin** [woocommerce/woocommerce#26209]
the class "link" in the e-mail link tag, when getting the password reset e-mail, is invisible in e-mail clients using dark theme, as the tag "color: #ffffff;" is added.

https://github.com/woocommerce/woocommerce/blob/968f7ddc5b2737ca40b4503701c89e9bc038adb4/templates/emails/customer-reset-password.php#L34

this line:
https://github.com/woocommerce/woocommerce/blob/968f7ddc5b2737ca40b4503701c89e9bc038adb4/templates/emails/email-styles.php#L26

**Comment by juliaamosova** [comment]
Hi @mcantsin,

Thank you for taking the time to report this bug, we really appreciate your help. Please feel free to submit a PR to fix it. Otherwise, we'd get to it at some point.
