### ISSUE TITLE
[4.1 beta2]: Title of the issue

### ISSUE THREAD

**Issue by Ravilio** [woocommerce/woocommerce#26215]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by nielslange** [comment]
@Ravilio Please provide the required information when creating a ticket.

**Comment by juliaamosova** [comment]
@Ravilio I am closing this issue as it has no information about the bug at all. If you encountered an issue, please provide all the details that we require so that we could take a look further.
