### ISSUE TITLE
Textdomain issue after 4.0 merge: new onboarding always in english, despitre translations are ready

### ISSUE THREAD

**Issue by maximebj** [woocommerce/woocommerce#26214]
Hi, 

When you install WooCommerce in a non english site, the new onboardings (with or without JetPack) are still in english, even if the strings are translated on wp.org. 

It seems that most of the strings from WooCommerce Admin package kept the `woocommerce-admin` textdomain after the merge in 4.0.

For example the string _Start setting up your WooCommerce store_ which can be found in packages/woocommerce-amdin/dist/app/index.js.

After a quick search, none of the `wp_set_script_translations` in WooCommerce has 'woocommerce-admin' in second parameter.

I don't know what is the best at this point: 

- change all textdomains to _woocommerce_
- or fix one of the wp_set_script_translations() function with second parameter 'woocommerce-admin'

I still begin with JS translations in WordPress so I may be wrong somewhere.

## Steps to reproduce

- Install a new WordPress Website
- Set language to french 
- Install WooCommerce
- Launch Onboarding setup

PS: my 2 cents: Jetpack is being more and more intrusive, like the guy you didn't invited at your birthday party but still showing up anyway.

**Comment by maximebj** [comment]
Clarification: I can see WooCommerce JSON files in `languages/plugins/`

**Comment by rrennick** [comment]
@maximebj Thanks for reporting the issue. It was already reported in https://github.com/woocommerce/woocommerce/issues/25920. Closing this as a duplicate.

**Comment by maximebj** [comment]
Thanks ! Sorry for the duplicate. The search and related issues gave me nothing.
