### ISSUE TITLE
Thousand & Decimal separator setting not honored in product shipping attributes

### ISSUE THREAD

**Issue by Marcoevich** [woocommerce/woocommerce#26224]
**Describe the bug**
In Woocommerce =>Settings => General I've set the decimal separator to (,) and the thousand separator to (.). This setting is not honored in the product shipping attributes.

**To Reproduce**

1. In Woocommerce =>Settings => General, set the decimal separator to comma (,) and the thousand separator to dot (.).
2. Edit a product. Add weight or dimensions which include a decimal separator.
3. See the error:

![image](https://user-images.githubusercontent.com/1243033/79437663-d1ec3780-7fd2-11ea-9cdd-52b0ba824099.png)

**Expected behavior**
I would expect that the product shipping attributes would honor the thousand separator and decimal separator as setup in Settings -> General. Those settings are as follows:

![image](https://user-images.githubusercontent.com/1243033/79437791-f47e5080-7fd2-11ea-80d7-3bef7ed4f2d4.png)

**Desktop**

* OS: Windows 7 64-bit
* Browser: Chrome
* Version: 80.0.3987.149

**Comment by juliaamosova** [comment]
Hi @Marcoevich,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/25864. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
