### ISSUE TITLE
Reports > Sales by Category has incorrect reporting when refunding products

### ISSUE THREAD

**Issue by yukikatayama** [woocommerce/woocommerce#26221]
18971020-hc

**Describe the bug**

When refunding a product, then viewing the **Reports > Sales by Category**, reporting is incorrect.

**To Reproduce**

1. Purchase a product in the same category in two separate orders.
2. Under **Reports > Sales by Category**, filter to view today's purchases of the category in step 1. Reporting should show correctly
3. Refund one of the orders
4. Refresh reporting page and notice it will be $0 (or, as if two orders were refunded)
5. If you purchase the product a third time, category report will calculate as if only one item was purchased today

Reporting in **Sales by Products** and when checking under **Analytics > Products** and **Analytics > Categories** do show correct reporting.

**Screenshots**

After two separate purchases of same category:

![](https://d.pr/i/TVT86C+)
Link to screenshot: https://d.pr/i/TVT86C

After only refunding 1 order:

![](https://d.pr/i/sp2ccD+)
Link to screenshot: https://d.pr/i/sp2ccD

With WC 4.0.1

**Comment by juliaamosova** [comment]
Hi @yukikatayama,

Thanks for opening the issue. It was, however, reported already a few times and something that we won't be fixing at this time:

https://github.com/woocommerce/woocommerce/issues/24293
https://github.com/woocommerce/woocommerce/issues/25311

With WooCommerce Admin now a part of WooCommerce Core, it replaces the legacy Report section that we are no longer working on. 

As you mentioned yourself, the amounts are shown correctly in the Analytics section (provided by WooCommerce Admin) which should be the source of truth at this point. The legacy Reports section will likely be deprecated with time. 

Closing this issue with a `won't fix` label.
