### ISSUE TITLE
Shipping Zone Wildcards: AANN* format not matching correctly

### ISSUE THREAD

**Issue by ldr2273** [woocommerce/woocommerce#26238]
**Describe the bug**

Using wildcards in Shipping Zones with AANN* format are not matching the correct zones.

**To Reproduce**

1. Go to **WooCommerce > Settings > Shipping** and add a Shipping Zone with the following wildcards: 

KA26*
KA29*
KA30*

2. Add a Flat Rate of let's say $25 to the zone.
3. Add a second Shipping zone with the following wildcard:

KA27*

4. Add a Flat Rate of let's say $50 to the zone. 
5. Add a product to cart with zip KA27 8SQ. 
6. The zip will be matched to the first zone, even though it's listed in the second zone.

**Expected behavior**
I would expect KA27 8SQ to match the zone with the KA27* wildcard.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by yukikatayama** [comment]
original report in 2902318-zen

**Comment by juliaamosova** [comment]
Hi @ldr2273,

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. I tested with WC 4.1. 

Here are my shipping zones as per your instructions:

![Screen Shot 2020-05-06 at 3 03 26 PM](https://user-images.githubusercontent.com/19143190/81217658-f6707980-8faa-11ea-87cc-3e2fca5d2c5b.png)

And here is the result in the cart - I've got `KA27 8SQ` postcode matched to the 2nd shipping zone as expected (with Flat rate of $50):

![sc](https://user-images.githubusercontent.com/19143190/81217768-291a7200-8fab-11ea-92ed-6122910b44a4.jpg)

Could you please retest to see if this is still an issue? Maybe I am missing some settings. I also have shipping debug mode enabled:

![sc2](https://user-images.githubusercontent.com/19143190/81217883-51a26c00-8fab-11ea-9a08-1558a8710e53.jpg)

**Comment by ldr2273** [comment]
Hi @juliaamosova - thanks for taking the time out to test this!

I have retested the issue, and now I'm getting the correct results :/ Closing now and will report back in the ticket for further debugging.
