### ISSUE TITLE
Change WooCommerce untested extension checks to use major versions

### ISSUE THREAD

**Issue by bekarice** [woocommerce/woocommerce#26248]
Our team @woocommerce/skyverge has proposed that core adjust the way the "Untested extensions" handling is done, given the evolution of how core releases are done.

- When the [untested extension check was added](https://woocommerce.wordpress.com/2017/08/28/new-version-check-in-woocommerce-3-2/), WC had [very recently "adopted semver"](https://woocommerce.wordpress.com/2017/03/13/important-update-regarding-the-upcoming-woocommerce-release-2-7-will-be-3-0-0/). At this point in time, all minor releases weren't _really_ minor releases -- they were often substantial releases with large refactors and feature changes. Because of the scope of changes between versions like 2.5 => 2.6 or 3.1 => 3.2, having the untested extensions check for every minor version made sense at that time.
- Releases are no longer nearly as large and as infrequent. We've gone from ~3 minor releases per year with substantial backwards compatibility concerns to [the core team setting a goal](https://woocommerce.wordpress.com/2019/12/11/woocommerce-3-9-beta-1/) of smaller, more stable, and more frequent releases.
- Release schedule is now more like a minor release every 2 months (doubling the historic minor release rate) with much smaller scope.

Because of these changes, we want to propose that the untested extensions check also adjust to account for this.

**Describe the solution you'd like**
We'd like this check to now adjust to adding notices for **major** version upgrades only, e.g. 3.x => 4.0. In fact, the entire reason this was added in the first place was _because of a major version upgrade_, see https://github.com/woocommerce/woocommerce/issues/15478 for context.

Woo core releases have become much more frequent and stable. This is a big win! 🎉 Because of this, though, these notifications are way less useful for minor versions. We've noticed two things with the last few rounds of releases:
- One of the original goals of the change was to reduce support around WC version updates:
   > They will have clear warnings about the dangers of upgrading when the plugin is incompatible. This should reduce your support load when new versions of WooCommerce are released.

   The current system is now having the _opposite_ effect. Often, we don't require any plugin changes for minor releases (again, this is great!). However, if we don't release the plugin with the updated headers, we find that we get a lot of support questions with concerns regarding compatibility. So, we end up releasing "empty" plugin updates with a header + changelog bump, and nothing else. This isn't a practice we think makes sense just to avoid support when no compatibility changes are needed -- plugin deploys should be for real updates.
- People who have used WooCommerce longer, though, are starting to ignore the notices for minor versions. They reach out when they see new minor versions, hear "nope everything is compatible!", and then upgrade. Because version 4.0 _was_ a backwards-incompatible release, we definitely _wanted_ the notification of users to happen here, as it's a good thing for them to be aware of the 4.0 change and plugin compatibility being required, but we don't want to condition folks to ignore these notices over time, either.

So this shows us the untested extension warnings are _good_ and doing exactly what we want them to do, from the user perspective: folks are aware of extension compatibility for updates. We are making them far less useful, though, when
- they are surfaced too often based on the changes to the core dev schedule and approach. Since WC is committed to semver and backwards compatibility in minor versions, they are not needed for minor versions.
- they cause a different kind of support they weren't intended to create.

**Describe alternatives you've considered**
Plugin developers could filter out their own plugins for minor releases, but that's not what these are intended for -- they should serve the needs of devs and users, and we think refinement ensures they stay most relevant and useful. 🙂 

**Additional context**
If y'all are in favor of this idea, we are happy to submit a PR with the changes to move this notice to a major version check instead!

Tagging @claudiosanches @claudiulodro @rodrigoprimo @peterfabian since I'm not sure who's the best person to chat with these days. 🙌

**Comment by juliaamosova** [comment]
Hi @bekarice 👋 

Thank you for submitting the suggestion and provide an extensive explanation of the reasons for the change. We will chat with the WooCommerce Core team a bit further and share our initial feedback/suggestions/comments here.

**Comment by bekarice** [comment]
👋 Heya @juliaamosova, I wanted to check in here to see if there had been any discussion? Given the [announcement to move to monthly releases](https://woocommerce.wordpress.com/2020/05/12/woocommerce-4-2-beta-1/), this conversation feels relevant, as merchants may end up seeing these alerts all the time, contributing to the blindness issue I mentioned. Thanks for any details you can share!

**Comment by peterfabian** [comment]
Hi @bekarice, 

Thanks for raising those points and for a great post here!

Yup, we're still having the discussion about the best ways to handle this, as it is a tricky one.

We definitely agree with a lot of your points and don't want to put extra strain on extension developers or cause the cobra effect with the warnings. 

On the other hand, we are aware that end users frequently encounter problems resulting from plugin conflicts. Removing the declaration of compatibility from the extensions for minor releases can make this problem even worse. 
While the number of changes in WC core itself is perhaps somewhat reduced, there are now multiple teams contributing with their code to WC bundle (WC Admin, Blocks), so the total number of changes usually isn't that small. 

From my point of view, in an ideal world, extensions would get tested with the pre-release version of WooCommerce and if all the tests pass, an automated release script would publish an update declaring compatibility. 

What's quite annoying at the moment, as you said, is that declaration of compatibility lives in the code where extensions need to release a new version for every WC update. While I'm not saying that the solution used on wp.org is ideal, it allows plugins to just push an update to the readme file that declares the compatibility with WP core versions. Do you think a similar solution (i.e. the possibility to bump version compatibility info independently from plugin update) would work for you folks?

**Comment by peterfabian** [comment]
One more thought from the discussion we've had was to offer declaring compatibility with wildcards (so 4.*) or some system similar to composer, e.g. "^4.0" meaning at least 4.0.

**Comment by bekarice** [comment]
@peterfabian, definitely hear you on wanting to avoid compatibility issues even with minor updates. We've not seen nearly as many compat problems with minor releases as we have with major releases, but I'm sure y'all are also seeing different / more conversations than our team!

I agree that a method of declaring compatibility outside the plugin code (readme, or perhaps a WooCommerce.com setting for plugins distributed there) would be really helpful to avoid these empty releases long-term.

I think the wildcard method is probably a great starting point, though, as that helps _all_ developers, not just those who host plugins in one of those two channels. I'd be in favor of making that change sooner since individual developers can make the determination of when to use it (e.g., being specific about supported version for plugins that are mission-critical, like payment gateways, while using a wildcard for non-essential plugins), and it helps to balance between _always_ showing these notices for every update, but keeping users informed. 👍

**Comment by om4james** [comment]
I also like @bekarice's idea of an extension opting in with wildcards. That way for mission-critical extensions (eg payment gateways), devs can use specific version compatibility strings (such as `4.1`, but for simpler extensions a `4.*` wildcard could suffice.

> Do you think a similar solution (i.e. the possibility to bump version compatibility info independently from plugin update) would work for you folks?

It's definitely best for end users (and extension devs) if we don't have to release a new version that is a simple version bump. It avoids update fatigue for end users, and helps save developer resources too.

The WP.org method of just pushing a readme change to the stable tag is great. However on WooCommerce.com this would be more difficult.

@peterfabian are you thinking of a possible "tested up to" field in the vendor dashboard for each plugin instead?

**Comment by peterfabian** [comment]
Hi all, thanks for sharing your thoughts and perspectives. After further consideration and discussion, we think _it's best to keep these checks in place only for major releases_. Most extensions would probably start using 4.* anyway, so it has more or less the same effect. As you mention, with monthly releases, the number of changes is smaller anyway, so let's not keep everyone busy by releasing dummy updates and focus on how we can make more impact on the ecosystem as a whole through less intense manual work. 
Ultimately, we'd like to move towards automated extension tests and not rely on manually reported compatibility, but that is a longer-term outlook on the platform that is broader than our team's focus at this point. We'll be announcing these changes on the dev blog and 3dpdevs p2.
