### ISSUE TITLE
DocBlock in template/emails/plain/customer-details.php contains an error

### ISSUE THREAD

**Issue by slavicd** [woocommerce/woocommerce#26244]
Line 7 of template/emails/plain/customer-details.php should say 
> This template can be overridden by copying it to yourtheme/woocommerce/emails/plain/customer-details.php.

instead of 

> This template can be overridden by copying it to yourtheme/woocommerce/emails/plain/email-addresses.php.

**Comment by juliaamosova** [comment]
Hi @slavicd,

Thank you for taking the time to report this bug, we really appreciate your help. Thanks for submitting PR as well.
