### ISSUE TITLE
Option to delete part / element of a variation

### ISSUE THREAD

**Issue by kneops** [woocommerce/woocommerce#26255]
When I add the variations to a product, for instance made up of 3 kinds of attributes, thus resulting in several rows of variations with 3 columns, I cannot delete one variation from a row. I encountered this when one variation (row) was not valid like in this screenshot:
https://pix.toile-libre.org/upload/original/1587394757.png

To explain the screenshot: only the vacuum versions of the product have holes, the non-vacuum have no holes. So I wanted to delete the 'Geen holes' (= no holes in Dutch) option from selected rows. I cannot. That would instantly have solved the problem. Instead at this moment it seems only possible with using a Gravity forms addon, which seems to be overkill.

I hope my explanation makes sense :)

**Comment by claudiosanches** [comment]
Hello @kneops, all the issue template got removed, please next time keep the template, it help us a lot to triage and debug issues, there's no steps to reproduce this issue.

> To explain the screenshot: only the vacuum versions of the product have holes, the non-vacuum have no holes. So I wanted to delete the 'Geen holes' (= no holes in Dutch) option from selected rows. 

On your screenshot there's no examples of it, there's only one attribute, so it will not generate "3 columns" as you said...

Can you please give me more details and detailed steps to reproduce it?
I'm not sure if it's a bug or you are suggesting a new feature.

**Comment by kneops** [comment]
Hi Claudio,

We dismissed these variations for this product and created seperate 
products, but the idea is this and can be reproduced with any variations:

Let's say you sell t-shirts, and have 3 attributes, each with several 
values (in this example I will leave out size).
Then you create variations using all 3 attributes, this can be done by 
Woocommerce automatically, so the result is 3 columns with variations.
For instance:

- fabric (cotton, silk, polyester, etc.)
- color (red, blue etc.
- sleeves (long, short)

ALL variations can be made and they all have different prices, except 
red silk t-shirts never have sleeves. So in the row red silk t-shirts 
that has 3 columns fabric + color + sleeves, I want to remove the option 
sleeves, so that if a customer chooses silk, then color red, the third 
option is not available.

I wonder if this can be done, it would mean less seperate products,

Jack


<https://www.jacktummers.com>
Op 05-05-2020 om 16:51 schreef Claudio Sanches:
