### ISSUE TITLE
[GlobalStep - 4.1 RC]: Confirmation message stating category already exists fails to be displayed.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#26268]
Steps to Reproduce:
1. Create a test site using JN. 
2. Complete initial screens.
3. Add new product.
4. Add new category.
5. Note that confirmation message fails to display.
6. Now try to add same category with same name multiple times.
7. Observe that confirmation message stating category already exists fails to displayed.

Actual Result:
Confirmation message stating category already exists fails to be displayed.

Expected Result:
Confirmation message should be displayed stating category already exists.

**Comment by claudiosanches** [comment]
Hello.

>  Confirmation message stating category already exists fails to be displayed.

This is the default WordPress behavior, it doesn't introduces duplicated categories, also doesn't display any message about it.
I'll close since it's the expected behavior, and we should improve it in the future with a new administrative interface.
