### ISSUE TITLE
No "reveal password" eye icon button when create account at checkout

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce#26271]
**Describe the bug**
The new "reveal password" eye icon button should be available in all password fields in WooCommerce, except for when creating an account at checkout. Especially important in checkout as there's one password field (no "confirm password" field).

I've reproduced this in Storefront and Twenty Twenty, so suspect it's a core issue.

**To Reproduce**
1. Go to `WooCommerce > Settings > Accounts & Privacy` tab.
2. Enable `Allow customers to create an account during checkout` option.
3. Open incognito window / different browser, add something to cart, proceed to checkout.
4. Select `Create an account` checkbox to reveal password form.
5. No reveal password eye icon in password field.

**Screenshots**
<img width="1257" alt="Screen Shot 2020-04-24 at 11 48 13 AM" src="https://user-images.githubusercontent.com/4167300/80160490-df806d80-8621-11ea-8b85-7c35d430260c.png">

**Expected behavior**
The reveal password button should be available consistently in all password fields.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @haszari, thanks for bringing this up! I agree that we should provide an eye icon for consistency. 

I am having trouble to get the password field revealed in the first place so far. Testing in incognito mode in Chrome on brand new JN site. Tried both Storefront and Twenty Twenty themes - same result. Tested with 4.0.1 and 4.1 RC:

![](http://g.recordit.co/vXbHQKgiri.gif)

Going to try in Safari. 

In any case, marking this with 4.1 milestone to see if we can include it. cc @vedanshujain.

**Comment by haszari** [comment]
> I am having trouble to get the password field revealed in the first place so far.

Woops sorry @juliaamosova - I think my reproduce instructions are missing a step (or 2) 🤦. There's also various Woo account settings for allowing user to choose a password (vs getting emailed a generated password). You might need to tweak some more account settings to get the password field to display.
