### ISSUE TITLE
Hide the Postcode/Zip field on the billing/shipping form when Ghana is selected

### ISSUE THREAD

**Issue by tolu-paystack** [woocommerce/woocommerce#26270]
### Explain the issue
Ghana has no post codes, but entering a post code is currently required when Ghana is selected at checkout

### Steps to reproduce the issue

1. When checking out, select Ghana as billing/shipping address
2. Attempt to pay without entering a post code

You'll get an error message saying "Postcode/Zip is not a valid Postcode/Zip"

### Expected behavior
When Ghana is selected, the Postcode/Zip field should be hidden

### Isolating the problem (mark completed items with an [x]):

* [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
* [x] This bug happens with a default WordPress theme active, or Storefront.
* [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @tolu-paystack,

Thank you for taking the time to report this bug, we really appreciate your help. 

I added a comment on the PR to see if we need to discuss the implementation further:

https://github.com/woocommerce/woocommerce/pull/26272#issuecomment-619112992
