### ISSUE TITLE
[GlobalStep - 4.1 RC]: Error message stating “Sorry, this file type is not permitted for security reasons." is displayed while uploading product CSV

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#26280]
Steps to Reproduce:
1. Tested on JN multisite.
2. Complete initial screens.
3. Click on add new product.
4. Click on Import.
5. Try to upload CSV file.
6. Observe that  Error message stating “Sorry, this file type is not permitted for security reasons." is displayed while uploading product CSV.

Actual Result:
Error message stating “Sorry, this file type is not permitted for security reasons." is displayed while uploading product CSV

Expected Result:
User should be able to upload CSV file.

<img width="960" alt="#8" src="https://user-images.githubusercontent.com/41110392/80236731-2d749000-8679-11ea-8751-1a42dc948d17.png">

**Comment by juliaamosova** [comment]
Hi @gglobalstep,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/26076. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
