### ISSUE TITLE
[GlobalStep - 4.1 RC]: Database error is displayed while activating Code Snippet.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#26284]
Steps to Reproduce:
1. Tested on JN Multisite.
2. Complete initial screens.
3. Click on Add new plugins.
4. Install Code Snippet.
5. Click on Activate button.
6. Observe that database error is displayed.

Actual Result:
Database error is displayed while activating Code Snippet.

Expected Result:
Error shouldn't be encounter while activating code snippet plugin.

[#12.zip](https://github.com/woocommerce/woocommerce/files/4530298/12.zip)

**Comment by juliaamosova** [comment]
Hi @gglobalstep,

Thank you for reporting the issue. However, this issue had been reported previously (by you) here: https://github.com/woocommerce/woocommerce/issues/26142. We are closing this issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
