### ISSUE TITLE
Coupon current user validation

### ISSUE THREAD

**Issue by evaXyn** [woocommerce/woocommerce#26305]
Hello, 
we created a new coupon with customer email, and expected that this coupon will be valid only for this user. 
But this was valid for every user, even for guest users. 
We backtraced it to coupon function is_coupon_valid and found out that the validation is missing the user restriction.
So we added the validation manually, with the hook you provide underneath, in order to set the coupon valid for the specific user.

Your function code
![image](https://user-images.githubusercontent.com/33082837/80357994-6fbded00-8884-11ea-9134-9c3d2050dc38.png)

Our Hook
![image](https://user-images.githubusercontent.com/33082837/80358095-91b76f80-8884-11ea-8a98-6fc57aff59e9.png)

**Comment by tammullen** [comment]
Hi @evaXyn 

Thank you for reporting the issue. 

However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end and I am unable to use a coupon with an allowed email restriction for customers with a different email

![Screenshot 2020-04-27 at 21 47 46](https://user-images.githubusercontent.com/24649833/80419284-c2bd9180-88d0-11ea-8938-e38518ef39fc.png)

To help us further evaluate this issue can you fill out the additional details of the bug report template that we ask for such as Steps to reproduce the behavior including the coupon settings and the system status report from **WooCommerce > System Status** in WordPress admin. 

Please provide us with the information requested so we could take a look further.

In addition a similar issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/26002. Can you also take a look at it and see if it matches your issue.

**Comment by seldimi** [comment]
I think Eva says that coupon should not be allowed to be applied by any user before hitting "complete order"

How to reproduce:
- login as any other user or guest and apply coupon restricted to Eva named 'Eva'
- Hit apply coupon on checkout and it will be applied to checkout form. When you click complete order it says 'thia coupon doesn't belong to you etc...'

Wouldn't be more correct not to allow user apply a coupon if he is logged in (as restriction applies) or if he is guest and has already filled billing email address?

Applying a coupon to any user on checkout (before completing order) seems like a glitch.

**Comment by tammullen** [comment]
Hi @seldimi 

Thanks for your feedback, we do the coupon verification on the placing order step as the billing details can be modified up until this point and the billing details will be part of coupon validation.

**Comment by seldimi** [comment]
I have understood that but that's not correct IMO.
As long as there is ajax validation, why that can't be there? It's not correct to the user.

**Comment by homeworker** [comment]
The validation should be triggered on coupon add, not on order complete action.
Think for a moment you are a guest client or old client, you place the order convinced that you get the discount and then when you place the order you have no discount applied (happen with paypal payment for example).

![cassa](https://user-images.githubusercontent.com/4161571/93074309-71961a80-f684-11ea-9c33-a6b99c1a5193.png)

![PayPal](https://user-images.githubusercontent.com/4161571/93074293-6cd16680-f684-11ea-9f71-30f94d269c53.png)

**Maybe you can ask the email at the same time with the coupon code when the email verification is active.**

**Comment by apmwebdev** [comment]
Another ticket running into this issue: 25224820-hc

**Comment by tammullen** [comment]
Hi @evaXyn 

Thank you for reporting the issue. However, a similar issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/26289. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
