### ISSUE TITLE
Coupon used multiple time (with restriction of 1 per user) because of Browser change

### ISSUE THREAD

**Issue by gabrielecettolin** [woocommerce/woocommerce#26300]
Hello, I have an issue with the coupon management. I've created a coupon that will give a 10% discount for the first purchase.

It has been set with a restriction of 1 use per user or guests. This will work considering the email of the customer.

Today one of my returning customers has used for the second time the coupon even she wasn't allowed to do so. She has used the same email address and same shipping address.

I then discovered that if i change the browser and use the coupon with the same email address you are allowed to use it twice. 

Why is this happening? And how can i fix this issue?

**Comment by tammullen** [comment]
Hi @gabrielecettolin 

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/26002. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
