### ISSUE TITLE
The Show password button

### ISSUE THREAD

**Issue by stormit** [woocommerce/woocommerce#26304]
Hello,

The Show password button does not work correctly on the **Password Change** form (**My Account > Account Details** tab). It only allows to show password, does not allow to hide password.

**Comment by juliaamosova** [comment]
Hi @stormit,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/25624. We are closing your issue in favor of the previously submitted.

The fix will be included in the upcoming WooCommerce 4.1 version via https://github.com/woocommerce/woocommerce/pull/25627.
