### ISSUE TITLE
My products change status from published to draft by themselves and don't show on the front end of my site

### ISSUE THREAD

**Issue by johnall** [woocommerce/woocommerce#26313]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

My products change to draft status and don’t show on my front end.
I have tried all of the solutions that I could find on the internet, but no luck.

**My Emailis> EWorldBlue@gmail.com**
I tried disabling all my plugin
reinstalled WooCommere plugin
Increased my memory to 64
Change status to public from quick edit
Changed Themes from Sydnet To Twenty Seventeen And several others
Running Wordpress 5.4
Does anyone have an idea of what I can do?

**To Reproduce**
1. Go to  https://eworldblue.com/
2. Click on  Real Estate - Training or Personal Assistant Agreement - Letters & Articles-Agent Tools

3. Scroll down to 'Click on any of those products PS all of my affiliate products are working and were installed using the Commission Machine Plugin
4. See error See Attached Photo

**Screenshots**

**Expected behavior**
A clear and concise description of what you expected to happen
I should see my products

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

[WordPress environment.docx](https://github.com/woocommerce/woocommerce/files/4541637/WordPress.environment.docx)
![Products problem](https://user-images.githubusercontent.com/17264438/80411785-c20a0880-889a-11ea-9f46-e6b577bae473.JPG)

```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by claudiosanches** [comment]
Hello @johnall 

This report isn't valid, you are sending your URL to test, there's no steps to test it with a clean installation, also there's no code on WooCommerce to change the status of products like you are reporting, it sounds like custom code.

I'm going to close since there's no way to test it in a clean install, please feel free to post back with steps to reproduce in a clean install and I then we can open it again.

**Comment by johnall** [comment]
Is this what you need?

I answered the questions above
All I do is enter my products and select publish  then update
My products stay published fo a few minutes then go into draft status
I never save them in draft
Can you be more specific as to what you need because I do not wire code
Thank You For Your Response

[WordPress environment.docx](https://github.com/woocommerce/woocommerce/files/4547560/WordPress.environment.docx)
Is this what you need?

**Comment by claudiosanches** [comment]
@johnall I can't reproduce it in a clean install, at least not with the steps you provided.

**Comment by johnall** [comment]
Sorry, I don't know what you mean by a clean install. Are you trying it on a new Wordpress installation?
I have used Wordpress for years and never had this problem. I think something went wrong with my site, but I just don't  know where to look for it. I am sure that if you are trying to get it to happen on  a new Wordpress site it won't happen.
