### ISSUE TITLE
Wrong translation for bs_BA

### ISSUE THREAD

**Issue by hadisn** [woocommerce/woocommerce#26318]
Hi, you have mistake in new order email subject, translated to bosnian currently is: "Neuspjela narudžba", on english this mean "Failed Order" but it should be "Nova narudžba" which means "New order". Screenshot attached of where problem is.
![Capture](https://user-images.githubusercontent.com/2553775/80498349-e681e580-896b-11ea-9065-1928b3a611f9.JPG)

I corrected it but i receive same subject again...

**Comment by claudiosanches** [comment]
Hello, translations are created and handled by local communities, you are free to update and send suggestion on https://translate.wordpress.org/projects/wp-plugins/woocommerce/
