### ISSUE TITLE
Coupons with ampersand (&) in name aren't recognized on mobile

### ISSUE THREAD

**Issue by ldr2273** [woocommerce/woocommerce#26321]
**Describe the bug**
When using a coupon code with the ampersand (&) symbol in the name, it is not recognized on mobile only. 

**To Reproduce**
1. Create a coupon code with "&" in the name:

![Coupon Code](https://d.pr/i/pgn0Xj+)
Link: https://d.pr/i/pgn0Xj

2. Use this coupon in the cart on desktop, and it is applied successfully: 

![Desktop](https://d.pr/i/6pCrMf+)
Link: https://d.pr/i/6pCrMf

3. View the store on your mobile device, add a product to cart, and then attempt to apply the same coupon code there. Once doing so, you get a `Coupon "woo&test" does not exist!` error:

![Mobile](https://d.pr/i/zWzjPy+)
Link: https://d.pr/i/zWzjPy

**Expected behavior**
I would expect the coupon code with the ampersand to be recognized on desktop and mobile. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

I was testing on mobile and have not attempted to test iOS. Tested with WC 4.0.1 and latest Twenty Twenty theme.

**Comment by tammullen** [comment]
Hi @ldr2273 

Thank you for reporting the issue. However, this issue had been reported previously here #23655. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
