### ISSUE TITLE
Silent "Error while saving" before saving product

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#26322]
**Describe the bug**

Filing this on behalf of @andrewjkerr: pb22l9-8V-p2#comment-397.

Quoting:

>When adding a product, there’s this “error while saving” message before I actually do anything

>I just typed some words and didn’t hit any save buttons (I think) but this error message was already showing up. 😅

![save2](https://user-images.githubusercontent.com/19143190/80528924-b08d3300-8964-11ea-9842-99febcb358e8.jpg)

Observed on JN site while testing WC 4.1 beta2. I couldn't reproduce but wanted to document it in case we'd see more reports of this issue.

**Comment by claudiosanches** [comment]
I can't reproduce it too, maybe some connect problem or something on his installation, maybe even on his server.
