### ISSUE TITLE
Twenty Twenty style issue if no description present

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#26334]
**Describe the bug**
The up-sells/cross-sells do not clear appropriately when there is no description and the tabs don't display

**To Reproduce**
1. Create a simple product
2. Do NOT define a long description
3. define cross-sells and upsells

**Screenshots**
![image](https://user-images.githubusercontent.com/507025/80613322-5dfe5600-89fa-11ea-8b9c-d68d337b6946.png)

**Expected behavior**
Up-sells and cross-sells display below the short-description

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment]
I can reproduce it on my end. But it's missing one step, you need to also disable reviews on `wp-admin/admin.php?page=wc-settings&tab=products`.

We’re going to solve this bug as soon as possible. Stay tuned for updates.
