### ISSUE TITLE
No Tracking for First Class Shipment

### ISSUE THREAD

**Issue by AllegiantGaming** [woocommerce/woocommerce#26363]
When using woocommerce services to create shipping labels, on wordpress, it states that tracking information is included for USPS - First Class Mail. However, once the label is purchased and made, there is no tracking number. 

**To Reproduce**
1. Go to"WooCommerce" > Orders > Select Order for Shipment 
2. Click on 'Create Shipping Label'
3. Continue to 'Shipping Rates' and Select 'USPS - First Class Mail (includes USPS tracking)
4. Purchase Label
5. See Issue - No Tracking Number is on the label, or available in the Woocommerce 'Shipment Tracking' on Right Hand Side of Order Page. 

![image](https://user-images.githubusercontent.com/62673401/80873611-8945a700-8c7f-11ea-9a17-e499954a87f7.png)

**Expected behavior**
I expect for their to be a tracking number provided on the label and in the Shipment Tracking section.

**Comment by peterfabian** [comment]
Hi @AllegiantGaming 

Thanks for reporting, this is related to the shipping plugin, so I've migrated it to the respective repository: https://github.com/Automattic/woocommerce-services/issues/2021. Please follow the updates on the migrated issue.
