### ISSUE TITLE
New customer email and forgot password email not sending

### ISSUE THREAD

**Issue by mi1996** [woocommerce/woocommerce#26364]
We don't offer technical support on GitHub so we recommend using the following:

**Reading our documentation**
Usage docs can be found here: https://docs.woocommerce.com/

If you have a problem, you may want to start with the self help guide here: https://docs.woocommerce.com/document/woocommerce-self-service-guide/

**Technical support for premium extensions or if you're a WooCommerce.com customer**
 from a human being - submit a ticket via the helpdesk
https://woocommerce.com/contact-us/ 

**General usage and development questions**
- WooCommerce Slack Community: https://woocommerce.com/community-slack/
- WordPress.org Forums: https://wordpress.org/support/plugin/woocommerce
- The WooCommerce Help and Share Facebook group

**Comment by peterfabian** [comment]
Hi @mi1996 , 

I understand that you have problems with sending out the 'new customer' and 'forgot password' emails from your site? Generally, all emails are using the same infrastructure from WordPress, so if e.g. notification about a new order is sent correctly, the other emails should work as well. 

Please provide us with your [system status report](https://docs.woocommerce.com/document/how-to-review-your-woocommerce-system-status/) and try to check for plugin conflicts (further instructions: https://docs.woocommerce.com/document/how-to-test-for-conflicts/) 

Thanks!
