### ISSUE TITLE
Upgrade to Woocommerce 4.01 checkout page problem

### ISSUE THREAD

**Issue by hotcookieweb** [woocommerce/woocommerce#26369]
**Describe the bug**
Upgraded to Woocommerce 4.01.   Checkout page on any change tries to process the checkout.  Gives the "Please read and accept the terms and conditions to proceed with your order."  I can successfully checkout when I do accept terms and conditions and click checkout.   But I no longer can go from the cart to the checkout page and make changes on the checkout page.

**To Reproduce**
1. Go to checkout page from cart
2. Change billing first name, hit return
3. See error "Please read and accept the terms and conditions to proceed with your order."

**Screenshots**
**Expected behavior**
Checkout form is updated and shipping is updated appropriate based on any address change.

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
`
### WordPress Environment ###

WordPress address (URL): https://hotcookielocal.com
Site address (URL): https://hotcookielocal.com
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.9
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.65.1
OpenSSL/1.0.2o

SUHOSIN Installed: –
MySQL Version: 5.7.26
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: wp_
Total Database Size: 55.40MB
Database Data Size: 39.16MB
Database Index Size: 16.24MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 1.84MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.16MB + Index: 0.14MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
wp_cleantalk_sessions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cleantalk_sfw: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_cleantalk_sfw_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cleantalk_spamscan_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.42MB + Index: 0.41MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.14MB + Index: 0.17MB + Engine InnoDB
wp_followup_order_items: Data: 0.08MB + Index: 0.14MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.17MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 1.52MB + Index: 0.47MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.34MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 12.52MB + Index: 6.03MB + Engine InnoDB
wp_posts: Data: 5.52MB + Index: 0.38MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 1.52MB + Index: 3.03MB + Engine InnoDB
wp_users: Data: 0.09MB + Index: 0.08MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfpklist_template_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 10.55MB + Index: 0.00MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfront_ure_login_redirect: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfront_ure_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 67
acf-field-group: 10
attachment: 185
br_notice: 1
custom_css: 1
customize_changeset: 1
follow_up_email: 2
nav_menu_item: 31
page: 31
post: 3
postman_sent_mail: 250
product: 70
product_variation: 25
revision: 381
shop_coupon: 12
shop_order: 462
shop_order_refund: 50
wcccf: 3
wccpf: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Post SMTP: by Yehuda Hassine – 2.0.11
WooCommerce: by Automattic – 4.0.1
WP Migrate DB Pro Media Files: by Delicious Brains – 1.4.15
WP Migrate DB Pro Multisite Tools: by Delicious Brains – 1.2.6
WP Migrate DB Pro Theme & Plugin Files: by Delicious Brains – 1.0.5
WPMU DEV Dashboard: by WPMU DEV – 4.8.1

### Inactive Plugins (24) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.8.7
Advanced Order Export For WooCommerce: by AlgolPlus – 3.1.4
Branda Pro: by WPMU DEV – 3.3.0
Classic Editor: by WordPress Contributors – 1.5
Clear OPcache Plugin: by Binary Cocoa – 0.5
Clientside: by Berend de Jong – 1.12.1
Follow-Up Emails: by WooCommerce – 4.9.0 – 4.9.1 is available
Gravity Forms: by rocketgenius – 2.4.17
Hotcookie Shipping: by Anton Roug – 1.2
Import and export users and customers: by codection – 1.15.5.11
Jetpack by WordPress.com: by Automattic – 8.4.2
Order / Coupon / Subscription Export Import Plugin for WooCommerce (BASIC): by WebToffee – 1.6.4
Site Kit by Google: by Google – 1.7.1
Store Toolkit for WooCommerce: by Visser Labs – 2.2 – Not tested with the active version of WooCommerce
User Role Editor: by Vladimir Garagulya – 4.53.1
User Switching: by John Blackbourn & contributors – 1.5.4
WooCommerce Address Book: by Hall Internet Marketing – 1.7.5
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.16
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.4.6 – Not tested with the active version of WooCommerce
WooCommerce Product Add-ons: by WooCommerce – 3.0.14 – 3.0.32 is available – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.22.3 – 1.23.0 is available – Not tested with the active version of WooCommerce
WooCommerce Square: by WooCommerce – 2.1.1 – 2.1.3 is available
WooCommerce Subscriptions: by Automattic – 2.5.7 – 3.0.4 is available – Not tested with the active version of WooCommerce
WP Migrate DB Pro: by Delicious Brains – 1.9.10

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /shop/cart/
Checkout: #8 - /shop/checkout/
My account: #9 - /shop/account/
Terms and conditions: #109 - /terms-conditions/

### Theme ###

Name: Storefront
Version: 2.5.5
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Canceled: 91
Oldest: 2020-04-03 15:39:32 -0700
Newest: 2020-05-01 16:46:45 -0700

Complete: 323
Oldest: 2020-04-02 21:51:57 -0700
Newest: 2020-05-03 18:34:11 -0700

Pending: 3
Oldest: 2020-05-04 06:00:00 -0700
Newest: 2020-05-08 15:21:22 -0700

`

**Comment by peterfabian** [comment]
Hi @hotcookieweb , 

When you press enter on the checkout page, the default action for that page is executed, and the default action is to place the order, so I don't think this is new or unexpected? If you want, you can modify this behaviour, but I don't think we'll be changing this, sorry. 

In case I have misunderstood your request, please feel free to comment here and we might reopen the issue. Thanks!

**Comment by hotcookieweb** [comment]
That’s a new behavior I haven’t encountered.  Is that the new default for 4.01.   How is that disabled?

Tony Roug
Hot Cookie
630.240.7643
www.hotcookie.com

**Comment by peterfabian** [comment]
Hi Tony, when tried to reproduce it, I saw the same behaviour with WC 3.9 on Storefront 2.5.1, so I don't actually think this is a recent change. Please let us know which version you see this not happening in and we can check further.

**Comment by hotcookieweb** [comment]
Below is the status report my live site <http://www.hotcookie.com/> is running.   The problem does not happen on my live site.

As for enter=submit being a default behavior.    As I was thinking more about that position, technically it’s not possible for this to be a default behavior.   With this problem, I can’t change the shipping address zip code to change the shipping options.   Its stuck on forcing a checkout.   There is no way this could be default behavior.

`
### WordPress Environment ###

WordPress address (URL): https://hotcookie.com
Site address (URL): https://hotcookie.com
WC Version: 3.9.2
REST API Version: ✔ 1.0.7
Log Directory Writable: ✔
WP Version: ❌ 5.3.3 - There is a newer version of WordPress available (5.4.1)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.17.3
PHP Version: 7.3.11-1+ubuntu18.04.1+deb.sury.org+1
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 8.0.18
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.1
WC Database Prefix: wp_
Total Database Size: 95.32MB
Database Data Size: 76.23MB
Database Index Size: 19.09MB
wp_woocommerce_sessions: Data: 21.11MB + Index: 4.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.16MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 1.84MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.02MB + Index: 0.59MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.23MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_followup_customers: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.16MB + Index: 0.19MB + Engine InnoDB
wp_followup_order_items: Data: 0.08MB + Index: 0.14MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.17MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 1.52MB + Index: 0.47MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 10.09MB + Index: 1.19MB + Engine InnoDB
wp_postmeta: Data: 14.45MB + Index: 5.59MB + Engine InnoDB
wp_posts: Data: 6.27MB + Index: 0.44MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 2.48MB + Index: 3.02MB + Engine InnoDB
wp_users: Data: 0.09MB + Index: 0.08MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wfpklist_template_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 15.55MB + Index: 0.00MB + Engine InnoDB
wp_wpfront_ure_login_redirect: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpfront_ure_options: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 67
acf-field-group: 10
attachment: 186
custom_css: 1
follow_up_email: 4
nav_menu_item: 31
page: 31
post: 4
postman_sent_mail: 250
product: 70
product_variation: 25
revision: 371
scheduled-action: 476
shop_coupon: 13
shop_order: 512
shop_order_refund: 50
wcccf: 3
wccpf: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (26) ###

Gravity Forms: by rocketgenius – 2.4.17
Advanced Custom Fields PRO: by Elliot Condon – 5.8.7
Classic Editor: by WordPress Contributors – 1.5
Clear OPcache Plugin: by Binary Cocoa – 0.5
Site Kit by Google: by Google – 1.4.0
Hotcookie Shipping: by Anton Roug – 1.2
Import and export users and customers: by codection – 1.15.4.1
Post SMTP: by Yehuda Hassine – 2.0.11
Branda Pro: by WPMU DEV – 3.3.0
User Role Editor: by Vladimir Garagulya – 4.53
User Switching: by John Blackbourn & contributors – 1.5.4
Advanced Order Export For WooCommerce: by AlgolPlus – 3.1.1 – Not tested with the active version of WooCommerce
Follow-Up Emails: by WooCommerce – 4.8.31 – 4.9.1 is available
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.10 – 2.4.16 is available – Not tested with the active version of WooCommerce
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.4.6
WooCommerce Product Add-ons: by WooCommerce – 3.0.14 – 3.0.32 is available – Not tested with the active version of WooCommerce
WooCommerce Services: by Automattic – 1.22.3 – 1.23.0 is available
WooCommerce Square: by WooCommerce – 2.1.0 – 2.1.4 is available
Store Toolkit for WooCommerce: by Visser Labs – 2.1.1 – Not tested with the active version of WooCommerce
WooCommerce Subscriptions: by Automattic – 2.5.7 – 3.0.4 is available – Not tested with the active version of WooCommerce
WooCommerce: by Automattic – 3.9.2 – 4.0.1 is available
WP Migrate DB Pro Media Files: by Delicious Brains – 1.4.15
WP Migrate DB Pro Multisite Tools: by Delicious Brains – 1.2.6
WP Migrate DB Pro Theme & Plugin Files: by Delicious Brains – 1.0.5
WP Migrate DB Pro: by Delicious Brains – 1.9.10
WPMU DEV Dashboard: by WPMU DEV – 4.8.1

### Inactive Plugins (4) ###

Clientside: by Berend de Jong – 1.12.1
Jetpack by WordPress.com: by Automattic – 8.3
Order / Coupon / Subscription Export Import Plugin for WooCommerce (BASIC): by WebToffee – 1.6.0
Smush Pro: by WPMU DEV – 3.6.0

### Must Use Plugins (1) ###

WP Migrate DB Pro Compatibility: by Delicious Brains – 1.2

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /shop/cart/
Checkout: #8 - /shop/checkout/
My account: #9 - /shop/account/
Terms and conditions: #109 - /terms-conditions/

### Theme ###

Name: Hot Cookie Bakery
Version: 1.4
Author URL: https://remondevries.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: hotcookiebakery/woocommerce/emails/email-addresses.php version 3.5.4 is out of date. The core version is 3.9.0
hotcookiebakery/woocommerce/emails/plain/email-addresses.php
hotcookiebakery/woocommerce/order/order-details-customer.php

Outdated Templates: ❌
					
					
						Learn how to update

### Templates ###

thumbnail: 
medium: 
medium_large: 
large: 
1536x1536: 
2048x2048: 
woocommerce_thumbnail: 
woocommerce_single: 
woocommerce_gallery_thumbnail: 
shop_catalog: 
shop_single: 
shop_thumbnail: 

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://hotcookie.com
Subscription Statuses: –
WooCommerce Account Connected: ✔ Yes
Active Product Key: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United States (US) — California

### Payment Gateway Support ###

Square: products
card_types
customer_decline_messages
payment_form
authorization
charge
charge-virtual
capture_charge
refunds
voids
customer_id
tokenization
add_payment_method
token_editor
subscriptions
subscription_suspension
subscription_cancellation
subscription_reactivation
subscription_amount_changes
subscription_date_changes
multiple_subscriptions
subscription_payment_method_change_customer
subscription_payment_method_change_admin


### Square ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Save to Log

### Action Scheduler ###

Complete: 354
Oldest: 2020-04-05 02:58:11 -0700
Newest: 2020-05-05 06:01:10 -0700

Pending: 3
Oldest: 2020-05-05 10:55:52 -0700
Newest: 2020-05-08 15:18:54 -0700

Canceled: 119
Oldest: 2020-04-06 09:45:53 -0700
Newest: 2020-05-04 14:24:49 -0700

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –

`

Tony Roug
Hot Cookie
630.240.7643
www.hotcookie.com

**Comment by hotcookieweb** [comment]
I check my site <http://www.hotcookie.com/>.  Enter=submit is the default behavior.   What seems to have changed when I upgraded was how it handled changes to the shipping address.   I got into a case where I couldn’t change the shipping address without a submit.   I can’t recreate that error now that I have re-enabled on my test site. I go through a detailed check of how shipping works when I upgrade because all the shipping plugins are custom.   

The one effect that does still persist is that if I hit enter after I change the zip code that changes shipping, it submits the order without ever allow me to see the new shipping information.   The shipping is correct based on the zip code but I never had a chance to confirm that I agreed to the new shipping.  

So, I’m still not convinced that enter=submit is a good default behavior.  This may be a side effect of how woocommerce handles updates of shipping versus a site like amazon.   On amazon, changing the shipping address is not possible without explicitly hitting a button to change.  I’m thinking that’s where I want to go.   

Also, enter has no effect when I’m on amazon.   The only way to submit and order is the click “place you order”.

This brings me back to the question, is there a standard way to change remove enter=submit as the default woocommerce behavior?


Tony Roug
Hot Cookie
630.240.7643
www.hotcookie.com

**Comment by peterfabian** [comment]
Hi @hotcookieweb 

Yes, I've tried it on your live site and saw it happening as well. I believe this is [default HTML behaviour](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission), so we probably won't be changing this. 

You can prevent this from happening with JavaScript/jQuery if you add it to the checkout:

```

$("#place_order").keyup(function (event) {
    if ( event.target.type != 'textarea' && ( event.which === 13 || event.keyCode === 13 ) ) {
        event.preventDefault();
        return false;
    }
    else return true;
});

```

**Comment by hotcookieweb** [comment]
Adding that event doesn’t seem to stop the form from doing submit on checkout.
With the code, I still have the same effects.


Tony Roug
Hot Cookie
630.240.7643
www.hotcookie.com

**Comment by peterfabian** [comment]
You might need to adapt it to your particular website, but the gist is that you can either employ some tricks in HTML (false buttons, etc) or add JS to prevent this from happening.

**Comment by hotcookieweb** [comment]
This works…   

			$(document).on("keypress", 'form', function (e) {
			    var code = e.keyCode || e.which;
			    if (code == 13) {
			        e.preventDefault();
			        return false;
			    }
			});

Tony Roug
Hot Cookie
630.240.7643
www.hotcookie.com
