### ISSUE TITLE
woocommerce_cart_item_quantity filter improvement

### ISSUE THREAD

**Issue by luizbills** [woocommerce/woocommerce#26373]
**Is your feature request related to a problem? Please describe.**
The filter `woocommerce_cart_item_quantity` don't have the same arguments order of other similar filters (`woocommerce_cart_item_subtotal` and `woocommerce_cart_item_price`).
https://github.com/woocommerce/woocommerce/blob/master/templates/cart/cart.php#L121

**Describe the solution you'd like**
Make the `woocommerce_cart_item_quantity` filter pass its arguments in following order: $quatity, $cart_item and $cart_item_key.

**Additional context**
This is a break change.

**Comment by peterfabian** [comment]
Hi @luizbills, 

Thanks for the enhancement idea. As you noted, this would be a breaking change, so not an easy one to make. We could add another filter with consistent arg order and deprecate this one, but unfortunately, this is not a priority at the moment. Hope you understand and this does not represent a large annoyance to you.

**Comment by luizbills** [comment]
No problem. But it was not necessary to close the issue, you could leave it open to be reminded in future updates. Maybe putting a "priority: low" label.

**Comment by peterfabian** [comment]
Thanks, I understand and agree to some degree. However, we're trying to keep the number of issues down, so if we leave similar ones open, we would end up in a worse place than we're in at the moment, so this being a breaking change makes it a difficult sell.
