### ISSUE TITLE
Owner of store is incorrect

### ISSUE THREAD

**Issue by jfksdca** [woocommerce/woocommerce#26377]
Hi, I set-up the site originally as myself, the developer (jfksdca) so when it came time to install woocommerce it uses jfksdca as the site owner but it really should be the owner of the site who has the paypal account.  her email is historyofpickleball?@gmail.com.

I uninstalled woocommerce and told wordpress to run the woocommerce setup wizard.  That let me add the correct email but it still says only jfksdca can add a credit card for the shipping labels.'

I even deleted jfksdca to see what that would do.

![add-credit-card](https://user-images.githubusercontent.com/4826890/81031688-ef7a2780-8e41-11ea-8635-78d6f18934b7.png)

**Comment by superdav42** [comment]
@peterfabian is right you just need to transfer ownership of the blog to historyofpickleball?@gmail.com and then they can manage the payment options to purchase shipping labels. Please follow the instructions here: 
https://wordpress.com/support/transferring-a-site-to-another-wordpress-com-account/

I'm closing this issue as it's related to the [WooCommerce Services](https://github.com/Automattic/woocommerce-services/) extension. If you need further help please open an issue in that repository.
