### ISSUE TITLE
Add Tracks on search features

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce#26381]
It seems that we don't have Tracks on some of the search features available on Core:

**Must have**
**Search orders:** wp-admin/edit.php?post_type=shop_order
New event tracking name: `wcadmin_orders_view_search`
Triggered when the user clicks "Search orders"

**Search products:**  /wp-admin/edit.php?post_type=product
New event tracking name: `wcadmin_products_search`
Triggered when the user clicks "Search products"

**View products:***  /wp-admin/edit.php?post_type=product
New event tracking name: `wcadmin_products_view`
Triggered when the user visits the "All products" page

*- I just noticed that this event doesn't exist and it's also super useful

**Nice to have**
**Search categories:**  /wp-admin/edit-tags.php?taxonomy=product_cat&post_type=product
New event tracking name: `wcadmin_categories_search`
Triggered when the user clicks "Search categories"

**Search tags:**   /wp-admin/edit-tags.php?taxonomy=product_tag&post_type=product
New event tracking name: `wcadmin_tags_search`
Triggered when the user clicks "Search tags"

**Comment by pmcpinto** [comment]
@timmyc @ObliviousHarmony is it possible to have this for 4.2? Thanks

**Comment by mattsherman** [comment]
Fixed by #26409, #26417, and #26429.
