### ISSUE TITLE
Theme specific CSS files should be loaded in block editor

### ISSUE THREAD

**Issue by Aljullu** [woocommerce/woocommerce#26394]
**To Reproduce**
1. With the TwentyTwenty theme, create a post or page with the _Handpicked products_ block.
2. Compare how the block looks in the frontend and the editor.

In the frontend, the products span always the same height:
![imatge](https://user-images.githubusercontent.com/3616980/81162406-6e2fab80-8f8d-11ea-96dc-c28d06d78657.png)

In the editor, the products have a different height depending on the image size or the block name length:
![imatge](https://user-images.githubusercontent.com/3616980/81162455-80a9e500-8f8d-11ea-82e4-88235b172606.png)

Looking at the CSS, it looks like in the frontend some styles from `woocommerce/assets/css/twenty-twenty.css` are loaded, while in the editor they are not. Causing discrepancies.

**Expected behavior**
Theme specific CSS files should be loaded in the block editor as well, so the experience between the editor and the frontend is more similar.

**Comment by Aljullu** [comment]
We might end up moving some of the styles that affect blocks to WC Blocks repo, so in that case it might not be necessary. See https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/2418.

**Comment by juliaamosova** [comment]
Thanks for rasing the issue here @Aljullu! Will keep it open for now as the work progresses. Also, cc @claudiosanches here for awareness.

**Comment by Aljullu** [comment]
I will proceed closing this issue from core. As decided in woocommerce/woocommerce-gutenberg-products-block#2418 we will move those styles to WC Blocks so we can take care of making them load in the editor.
