### ISSUE TITLE
Marketplace suggestions: In app purchase back link doesn't work

### ISSUE THREAD

**Issue by danielbitzer** [woocommerce/woocommerce#26393]
**Describe the bug**
The back doesn't work when going through the in app purchase flow when originating from the **Get more options** product suggestions tab.

**Screenshots**
Screen recording: https://d.pr/v/6Quf3K

**To Reproduce**
1. Ensure your site is opted-in to marketplace suggestions
1. Edit any product
2. Click on 'Get more options'
3. Click on 'Learn more' for any product
4. Click on the back/arrow button in header, top left (not browser back button)
1. The page will reload rather than going back

**Expected behavior**
Back to previous page.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by haszari** [comment]
FYI @mattyza

**Comment by juliaamosova** [comment]
Noting here that I can reproduce the same:

![](http://g.recordit.co/JjNNhDrJMK.gif)

**Comment by claudiosanches** [comment]
I can confirm this bug, currently it's opening in a new tab, but even if you change it that return button doesn't work.

**Comment by rrennick** [comment]
@juliaamosova This is a WooCommerce.com issue as the marketplace suggestions page runs on WooCommerce.com

<img width="596" alt="Screen Shot 2020-06-17 at 4 59 20 PM" src="https://user-images.githubusercontent.com/343847/84944361-04421000-b0bc-11ea-97da-2f04feb197e8.png">

**Comment by haszari** [comment]
> This is a WooCommerce.com issue as the marketplace suggestions page runs on WooCommerce.com

It's possible that the params passed through to WCCOM from the woo site are incorrect - so the issue could be in either code base (or both, might be an interaction). But agree, alpha team are the experts here :)

**Comment by rrennick** [comment]
> so the issue could be in either code base

@haszari You can't reliably go back from a page opened in a new tab. Closing a tab goes back to the last active tab which may or may not have been the opener. This should go back to redesign to decide how the flow is going to work.

**Comment by haszari** [comment]
@rrennick I think the flow is fine (could be wrong) - though I'm keen to hear other ideas for how to improve this.

To clarify how this works .. 

The back button in this issue is not a browser back button, it's a link rendered in the WCCOM page, to take you "back to your store". The url for that link is [constructed from params (`wccom-site`, `wccom-back`)](https://github.com/Automattic/woocommerce.com/blob/master/plugins/wccom-plugins/in-app-purchase/includes/class-utility.php#L129) (private repo link) passed in from the [woo core end](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-addons.php#L487).

**Comment by rrennick** [comment]
> wccom-site, wccom-back

@haszari My params are `?wccom-site=https%3A%2F%2Fron.localhost&wccom-back=%252Fwp-admin%252Fpost.php%253Fpost%253D11399`. The link associated with the back arrow has no URL.

**Comment by haszari** [comment]
> My params are `?wccom-site=https%3A%2F%2Fron.localhost&wccom-back=%252Fwp-admin%252Fpost.php%253Fpost%253D11399`. The link associated with the back arrow has no URL.

Aha! Maybe an issue on the WCCOM end, rendering the link? cc @mattyza

**Comment by mattyza** [comment]
We have a pull request open for this on WooCommerce.com, so feel free to close this issue as desired. cc @peterfabian
