### ISSUE TITLE
Puerto Rico shipping with PayPal via USPS from WC

### ISSUE THREAD

**Issue by xboxhacker** [woocommerce/woocommerce#26412]
Down the rabbit hole we go again.....

WC is listing Puerto Rico as a "Country". But in fact is a territory of the USA. So when someone orders from my site, from PR, they select Puerto Rico as the country. 
When the order gets to PayPal, I CANNOT ship it because Puerto Rico is NOT a country It is a state. Please see screen shot.

As you can see it says "PR, Puerto Rico", when in fact if should say "PR, United States"

**Screenshots**
Non-working order shipment
https://badgeglow.com/wp-content/uploads/2020/05/Screenshot-2020-05-07-16.22.49.png

Here is the working shipping address, that works with PayPal.
https://badgeglow.com/wp-content/uploads/2020/05/Screenshot-2020-05-07-16.40.41.png

**### Notice "PR, United States"**

**Expected behavior**
PR should be listed as a state of the USA. This would fix my problem, and hundreds of others users too!

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://badgeglow.com
Site address (URL): https://badgeglow.com
WC Version: 4.1.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.15
Action Scheduler Version: ✔ 3.1.5
WC Admin Version: ✔ 1.1.1
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.30
PHP Post Max Size: 8 MB
PHP Time Limit: 180
PHP Max Input Vars: 5000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.7.30
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.1.0
WC Database Prefix: wpvb_
Total Database Size: 28.13MB
Database Data Size: 16.85MB
Database Index Size: 11.28MB
wpvb_woocommerce_sessions: Data: 2.00MB + Index: 0.11MB + Engine MyISAM
wpvb_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpvb_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_woocommerce_order_items: Data: 0.20MB + Index: 0.09MB + Engine MyISAM
wpvb_woocommerce_order_itemmeta: Data: 1.14MB + Index: 0.84MB + Engine MyISAM
wpvb_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpvb_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
crypto_files: Data: 0.02MB + Index: 0.33MB + Engine InnoDB
crypto_membership: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
crypto_payments: Data: 0.02MB + Index: 0.31MB + Engine InnoDB
crypto_products: Data: 0.02MB + Index: 0.25MB + Engine InnoDB
wpvb_actionscheduler_actions: Data: 0.18MB + Index: 0.09MB + Engine MyISAM
wpvb_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpvb_actionscheduler_logs: Data: 0.12MB + Index: 0.10MB + Engine MyISAM
wpvb_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpvb_comments: Data: 1.52MB + Index: 1.03MB + Engine InnoDB
wpvb_gf_draft_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_gf_entry: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_gf_entry_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_gf_entry_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_gf_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_gf_form_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_gf_form_revisions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_gf_form_view: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_layerslider: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpvb_nf3_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_nf3_action_meta: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wpvb_nf3_chunks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_nf3_fields: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_nf3_field_meta: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wpvb_nf3_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_nf3_form_meta: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wpvb_nf3_objects: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_nf3_object_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_nf3_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_nf3_upgrades: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wpvb_options: Data: 3.06MB + Index: 0.27MB + Engine InnoDB
wpvb_p3d_coatings: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_p3d_discount: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_p3d_infills: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_p3d_materials: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_p3d_price_requests: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_p3d_printers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_postmeta: Data: 6.30MB + Index: 6.81MB + Engine InnoDB
wpvb_posts: Data: 1.52MB + Index: 0.31MB + Engine InnoDB
wpvb_revslider_css: Data: 0.09MB + Index: 0.00MB + Engine MyISAM
wpvb_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_revslider_sliders: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wpvb_revslider_slides: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wpvb_revslider_static_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_rg_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_rg_form_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_rg_form_view: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_rg_incomplete_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_rg_lead: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_rg_lead_detail: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_rg_lead_detail_long: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_rg_lead_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_sbi_instagram_feeds_posts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_sbi_instagram_posts: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wpvb_stock_log: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpvb_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpvb_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpvb_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpvb_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpvb_usermeta: Data: 0.22MB + Index: 0.20MB + Engine InnoDB
wpvb_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpvb_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_wc_customer_lookup: Data: 0.05MB + Index: 0.05MB + Engine MyISAM
wpvb_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_wc_order_product_lookup: Data: 0.07MB + Index: 0.07MB + Engine MyISAM
wpvb_wc_order_stats: Data: 0.05MB + Index: 0.04MB + Engine MyISAM
wpvb_wc_order_tax_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpvb_wc_product_meta_lookup: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wpvb_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpvb_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpvb_woocommerce_termmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 85
nav_menu_item: 6
page: 10
portfolio: 2
post: 3
product: 19
product_variation: 57
revision: 117
shop_coupon: 8
shop_order: 1334
shop_order_refund: 6
slide: 1
tm_global_cp: 1
woo_discount_cart: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (29) ###

Gravity Forms: by rocketgenius – 2.4.8.3
3DPrint: by Sergey Burkov – 2.8.7.6 – Installed version not tested with active version of WooCommerce 4.1.0
LayerSlider WP: by Kreatura Media – 5.6.2
Akismet Anti-Spam: by Automattic – 4.0.7
All In One SEO Pack: by All in One SEO Team – 3.4.3
Contact Form 7: by Takayuki Miyoshi – 5.1.7
Duplicate Post: by Enrico Battocchi – 3.2.2
Force Regenerate Thumbnails: by Pedro Elsner – 2.0.6
Smash Balloon Instagram Feed: by Smash Balloon – 2.4.1
Lockdown WP Admin: by Sean Fisher – 2.3.2
My Wordpress Login Logo: by Afsal Rahim – 2.3.3
NinjaFirewall (WP Edition): by The Ninja Technologies Network – 4.1.1
NinjaScanner: by The Ninja Technologies Network – 2.0.6
PayPal for WooCommerce: by Angell EYE – 1.5.7 – Installed version not tested with active version of WooCommerce 4.1.0
Product Sales Report for WooCommerce: by Potent Plugins – 1.4.9 – Installed version not tested with active version of WooCommerce 4.1.0
Really Simple SSL: by Rogier Lankhorst
Mark Wolters – 3.3.1

Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.0.2
Slider Revolution: by ThemePunch – 5.4.6.3.1
Easy Updates Manager: by Easy Updates Manager Team – 9.0.3
User Role Editor: by Vladimir Garagulya – 4.54
Woo Discount Rules: by Flycart Technologies LLP – 1.9.3 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce Free Shipping Per Product: by WPRuby – 1.1.0 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce Blocks: by Automattic – 2.5.15 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.21 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce Stock Manager: by StoreApps – 2.1.1 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce TM Extra Product Options: by themeComplete – 4.6.6.1 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce: by Automattic – 4.1.0
WP Rollback: by Impress.org – 1.7.0
ReCaptcha v2 for Contact Form 7: by IQComputing – 1.2.6

### Inactive Plugins (5) ###

BeTheme Header Builder: by Muffin group – 1.0.5
Under Construction Site: by wpshopmart – 1.4.6
WooCommerce - Gravity Forms Product Add-Ons: by WooThemes – 2.9.5 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce Helper: by WooCommerce – 1.7.2 – Installed version not tested with active version of WooCommerce 4.1.0 – Network enabled
WPBakery Page Builder: by Michael M - WPBakery.com – 5.4.5

### Must Use Plugins (1) ###

0-ninjafirewall.php: by The Ninja Technologies Network – 1.0

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #49 - /shop/
Cart: #50 - /cart/
Checkout: #51 - /checkout/
My account: #52 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Betheme
Version: 21.5.2
Author URL: https://muffingroup.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: betheme/woocommerce/archive-product.php
/home/badgeglo/public_html/wp-content/plugins/woocommerce-tm-extra-product-options/templates/cart/cart-item-data.php
betheme/woocommerce/cart/cart.php
betheme/woocommerce/cart/mini-cart.php
betheme/woocommerce/content-product.php
betheme/woocommerce/content-single-product.php
betheme/woocommerce/loop/loop-end.php
betheme/woocommerce/loop/loop-start.php
betheme/woocommerce/loop/no-products-found.php
betheme/woocommerce/loop/pagination.php
betheme/woocommerce/notices/error.php version 3.5.0 is out of date. The core version is 3.9.0
betheme/woocommerce/notices/notice.php version 3.5.0 is out of date. The core version is 3.9.0
betheme/woocommerce/notices/success.php version 3.5.0 is out of date. The core version is 3.9.0
/home/badgeglo/public_html/wp-content/plugins/3dprint/woocommerce/order/order-again.php version 2.3.0 is out of date. The core version is 3.5.0
betheme/woocommerce/single-product/add-to-cart/external.php
/home/badgeglo/public_html/wp-content/plugins/3dprint/woocommerce/single-product/add-to-cart/variable.php version 2.3.0 is out of date. The core version is 3.5.5
/home/badgeglo/public_html/wp-content/plugins/3dprint/woocommerce/single-product/price.php version 2.4.9 is out of date. The core version is 3.0.0
/home/badgeglo/public_html/wp-content/plugins/3dprint/woocommerce/single-product/product-image.php version - is out of date. The core version is 3.5.1
betheme/woocommerce/single-product/product-thumbnails.php
betheme/woocommerce/single-product/sale-flash.php
betheme/woocommerce/single-product/tabs/additional-information.php
betheme/woocommerce/single-product/tabs/description.php
betheme/woocommerce/single-product/tabs/tabs.php
betheme/woocommerce/single-product/title.php

					
					
						Learn how to update

### Action Scheduler ###

Complete: 133
Oldest: 2020-04-07 22:41:53 +0000
Newest: 2020-05-07 15:04:07 +0000

Pending: 2
Oldest: 2020-05-13 23:10:40 +0000
Newest: 2020-05-13 23:10:41 +0000

`
</details>

**Comment by juliaamosova** [comment]
Hi @xboxhacker,

Thanks for raising the issue here. Last time we discussed this in https://github.com/woocommerce/woocommerce/issues/22687 and our view on how Puerto Rico is being presented in Woo hasn't changed since. We intend to keep listing Puerto Rico as a country for now. 

With that said, however, our state list is customizable and you can add Puerto Rico as a state by using a code snippet provided in [Add/Modify States doc](https://docs.woocommerce.com/document/addmodify-states/). This should solve the immediate issue for you.
