### ISSUE TITLE
Add hooks to "Add payment method form" to show additional fields and validate input

### ISSUE THREAD

**Issue by tsteur** [woocommerce/woocommerce#26414]
**Is your feature request related to a problem? Please describe.**
Yes. A while back we had a credit card verification attack using Braintree. Basically someone validated say 100K credit cards using the checkout or add payment method and this resulted in say 50K USD cost plus Braintree would temporarily terminate the account until Captchas are put in place everywhere payment methods are being added or changed (eg checkout, add payment method, change payment method.)

Not being able to show captchas means shop owners cannot protect themselves from credit card verification attacks and are therefore at high risk of running into a similar situation where they suddenly
* face massive cost due to the credit card verifications 
* get their payment account blocked until they figure out how to patch Woocommerce. In our case the whole process took several days since Braintree for example gets their people to validate the captcha was implemented correctly before allowing payments again
* aren't able to sell anything for days unless they have multiple payment providers

**Describe the solution you'd like**
To accomplish showing a checkout when adding a payment method, and to be able to validate the captcha, I have to patch Woocommerce after every update see https://gist.github.com/tsteur/f1a4bcf4a55ab9c53f22d2a2765a0a5c

I would create a pull request but not sure regarding naming conventions and best practices.

**Describe alternatives you've considered**
Due to missing hooks I couldn't figure out an alternative.

**Additional context**
Here's a screenshot of what I'm trying to achieve:

![image](https://user-images.githubusercontent.com/273120/81345752-29328300-910d-11ea-8b53-8c5a463ce0ff.png)

**Comment by juliaamosova** [comment]
Hi @tsteur,

Thanks for raising the issue. We have a [plugin on our marketplace that adds re-captcha to many WooCommerce pages](https://woocommerce.com/products/recaptcha-for-woocommerce/). It doesn't add re-captcha to `My Account / Add payment method` page though. Perhaps could be a good feature request for the developers of that plugin. 

Alternatively, if you are interested in submitting a PR that adds a hook so it is easier for you to patch, we will certainly consider it. 

>I would create a pull request but not sure regarding naming conventions and best practices.

Our contributions guidelines can be found in [Wiki](https://github.com/woocommerce/woocommerce/wiki). And here is a section related to [naming conventions](https://github.com/woocommerce/woocommerce/wiki/Naming-conventions) in particular. You are welcome to submit a PR. PR will reviewer will ask for any changes if will be necessary and advice on best practices further.

**Comment by tsteur** [comment]
@juliaamosova thanks for that. I sent a message regarding the plugin you mentioned to consider adding this feature. Also created a PR so this feature can be added in the first place see https://github.com/woocommerce/woocommerce/pull/26445

**Comment by juliaamosova** [comment]
Thanks @tsteur! I labeled your PR as `needs review`. We should be getting to reviewing it soon.
