### ISSUE TITLE
Missing .pot file after updating to v4.1.0

### ISSUE THREAD

**Issue by jrick1229** [woocommerce/woocommerce#26424]
**Describe the bug**
After updating to v4.1.0 of WooCommerce, there's no longer a .pot file in: `woocommerce/i18n/languages/`

This was brought to our attention by the Tim, the author of LocoTranslate: https://wordpress.org/support/topic/pot-file-absent-in-4-1-0/

**Steps to Replicate**

1. Install v4.1.0 on your site
2. Check in: `/wp-content/plugins/woocommerce/i18n/languages/..`
3. See that folder is empty

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

```
WP Version: 5.4.1
WC Database Version: 4.1.0
WooCommerce: by Automattic – 4.1.0
```
</details>

**Comment by anant1811** [comment]
Can replicate this as well.

**Comment by claudiosanches** [comment]
I just fixed now release on WordPress.org, now it will include the `woocommerce.pot`, also you can download it from https://plugins.svn.wordpress.org/woocommerce/tags/4.1.0/i18n/languages/woocommerce.pot

I'm closing since seems like we had some problem while releasing it.
