### ISSUE TITLE
Fixed some errors in the WC_Queue examples

### ISSUE THREAD

**Issue by melehin** [woocommerce/woocommerce#26428]
Hello!

I fixed some errors (On "Adding jobs to the queue" section) in the examples at https://github.com/woocommerce/woocommerce/wiki/WC_Queue---WooCommerce-Worker-Queue
My fixes is here: https://github.com/melehin/woocommerce/wiki/WC_Queue---WooCommerce-Worker-Queue

Please, pull fixes from this repo https://github.com/melehin/woocommerce.wiki

**Comment by Konamiman** [comment]
Hi @melehin,

We really appreciate your desire to contribute to WooCommerce with bug fixes, however the GitHub issues system should be used only to notify bugs. If instead you want to contribute with code that fixes bugs or enhances the WooCommerce platform in any other way, you should submit a pull request instead. Please take a look at [the WooCommerce contribution guide](https://github.com/woocommerce/woocommerce/blob/master/.github/CONTRIBUTING.md) for all the details.

And by the way, your repo link is giving me a "Not found" error, perhaps you have marked it as private?

I'm closing this issue for now. Please go ahead and submit a proper pull request for your bug fixes, we'll be really happy to review it.

**Comment by melehin** [comment]
hi, @Konamiman,

> And by the way, your repo link is giving me a "Not found" error, perhaps you have marked it as private?

The wiki repository above is available as https://github.com/melehin/woocommerce/wiki for viewing and https://github.com/melehin/woocommerce.wiki for cloning

I can't do PR to the wiki repo, no rights. The wiki is separated from main repo and has own URI [man repo].wiki
Based on answers from [SO](https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github) and [GitHub Help](https://help.github.com/en/github/building-a-strong-community/about-wikis)

As I understand, to update wiki a contributor need pull/merge https://github.com/melehin/woocommerce.wiki repo from inside woocommerce.wiki folder early cloned from https://github.com/woocommerce/woocommerce.wiki

And pull to the main wiki repo

**Comment by Konamiman** [comment]
Hi @melehin,

Sorry about that, I didn't realize that you were talking about the wiki, I misinterpreted that you had fixed some README file in the main repository.

I see only these changes in the file, could you please confirm that this is all you have changed?

![image](https://user-images.githubusercontent.com/937723/81692475-bbfd5580-945e-11ea-8fae-045d944d2682.png)

**Comment by melehin** [comment]
@Konamiman, yes at the moment. 

I also found some CSV fields -> internal fields mapping mismatch on [this page](https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema). I will fix it later, when I will have free time

**Comment by melehin** [comment]
Hi, @Konamiman!

I edited some wiki pages. Could you merge this from my repo?
