### ISSUE TITLE
Woocommerce - Variables products

### ISSUE THREAD

**Issue by rezzedine** [woocommerce/woocommerce#26446]
I would like to know how I can display Out Of Stock on the main product page (list of all products) when all possible attributes (Color/Size) are out of stock.

Current behavior: Product is displayed with the name and out of stock (price disappeared)

Expected behavior: Product is displayed with the name and price. Instead of having Add to Cart I would like to see Out of Stock.

If I click on the product and access the detailed page I see "Out of Stock"

Thank you!

**Comment by peterfabian** [comment]
Hi @rezzedine , 

Based on what I know, our support folks are following up with you via email. 
Support ref: 2963378-zen

Therefore, I'm going to close this ticket now. Thanks for understanding.
