### ISSUE TITLE
Message "Database update …" can not be closed

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce#26443]
Hi, I have installed WC 4 on a site were WC was til 2016 active – few years ago. Installing was done in few minutes without any bug. Products from past were still in there. But no orders, because I deleted them after deactivating WC in past. This was the situation.

After installing WC 4 on that site, a window with message came up after database was upgraded to latest version. But this message is now over a week on every WC page displayed and no chance to close that. Even if I click on button "Thanks" or in my language "Vielen Dank!" I get a blank page which tells me that action failed.

![Bildschirmfoto 2020-05-10 um 10 16 44](https://user-images.githubusercontent.com/3390880/81494209-5d41ab80-92a7-11ea-93d5-a2fabc81dc74.png)

Message stays on screen even after update to WC 4.1.

We had this behavior in the past and they told me it was fixed. But it is not. On other site I did not see that message again after upgrading WC from 4 to 4.1.

**Comment by paulcobb** [comment]
Same issue here

**Comment by peterfabian** [comment]
Hi, 

Apologies for the bug. 

Related to #26031 and https://github.com/woocommerce/woocommerce-admin/issues/3973

Before we get a fix in place, you can run the following query to get rid of it:
`UPDATE wp_wc_admin_notes SET status='actioned' WHERE name='wc-update-db-reminder';`

**Comment by ajgw** [comment]
Hi @peterfabian were do I run this update? In database?

**Comment by ajgw** [comment]
Yeah, I found table in database and set row to actioned and now it is gone.

Thanks Peter.

**Comment by paulcobb** [comment]
The query does not fix it for me unfortunately.
Running on a multisite if that makes any difference?

**Comment by peterfabian** [comment]
Hi @paulcobb , 

It should not make a difference, I think. The only difference is that your table prefix `wp_` will be different, so just double checking if you replaced it in the query above?

**Comment by paulcobb** [comment]
Thanks @peterfabian for the clarification
When I ran the modified query I get matched rows = 0 as I had already previously manually altered the database to 'actioned'.
Still not sure though why this has had no effect on dismissing the 'WooCommerce database update done' notice?

**Comment by peterfabian** [comment]
Interesting @paulcobb! I just tested it on a brand new multisite and it seemed to work fine. 

So just that I understand... when you run `SELECT status FROM wp_wc_admin_notes WHERE name='wc-update-db-reminder'`, you get one row with value `actioned`?

And the db update notice is still displayed in your admin, correct?

This is the query the API endpoint runs when asking for notices, I wonder, if you try to run it, do you get anything back? If not, maybe some caching issue on the JS side is the culprit?

```
SELECT 
  note_id, title, content 
FROM 
  WP_DB_PREFIX_wc_admin_notes 
WHERE 
  1=1 
  AND type IN ('error','update') 
  AND status IN ('unactioned') 
ORDER BY date_created desc 
LIMIT 0, 25
```

**Comment by paulcobb** [comment]
@peterfabian
I was getting confused with the multisite database format!
Once I linked the blog id with the relevant table id, I can see that 'actioned' does indeed dismiss the 'datebase update' notice.
Sorry for taking some time to get to the point!
Many thanks for your patience!
Regards,
Paul

**Comment by peterfabian** [comment]
No worries, happy it helped :)
