### ISSUE TITLE
Products with hidden visibility contribute towards product category count

### ISSUE THREAD

**Issue by danishmuneer** [woocommerce/woocommerce#26459]
**Describe the bug**
We set the visibility of a few products as "hidden" so they don't show up on shop and search results page. We added these products to a new product category "hidden category" to organize better. We have added product category widget from woocommerce to our primary sidebar and selected the option of "hide categories with zero products". Ideally, this should stop "hidden category" to not show in the sidebar but it does.  

**To Reproduce**
1. create a product with hidden visibility
2. add hidden product to a category, make sure that category doesn't have any visible products
3. add product category widget to sidebar, make sure "hide categories with zero products" is selected
4. the category still shows up on the sidebar front-end

**Screenshots**
https://www.dropbox.com/s/cjhzxdrxpdubrot/Capture.PNG?dl=0

**Expected behavior**
Products with hidden visibility should not contribute towards product category count at least for the product category widget.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://www.curtain-and-divider.com
Site address (URL): https://www.curtain-and-divider.com
WC Version: 4.0.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.14
Action Scheduler Version: ✔ 3.1.4
WC Admin Version: ✔ 1.0.3
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache/2.4.39 (Unix) mod_hive/6.27 OpenSSL/1.0.1e-fips mod_fastcgi/2.4.6
PHP Version: 7.1.33 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.59.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.6.36-82.1-log
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.0.1
WC Database Prefix: wp_
Total Database Size: 916.42MB
Database Data Size: 814.48MB
Database Index Size: 101.94MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.31MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 12.52MB + Index: 6.92MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_cf7dbplugin_submits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_comments: Data: 2.52MB + Index: 0.80MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 1.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 6.02MB + Index: 28.08MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 16.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 8.14MB + Index: 6.25MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 11.50MB + Index: 0.42MB + Engine InnoDB
wp_postmeta: Data: 685.56MB + Index: 30.97MB + Engine InnoDB
wp_posts: Data: 51.25MB + Index: 4.59MB + Engine InnoDB
wp_PO_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_PO_plugins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_PO_post_plugins: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_PO_url_plugins: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_relevanssi: Data: 13.27MB + Index: 20.13MB + Engine InnoDB
wp_relevanssi_log: Data: 0.25MB + Index: 0.17MB + Engine InnoDB
wp_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.09MB + Index: 0.13MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.05MB + Engine MyISAM
wp_term_relationships: Data: 0.05MB + Index: 0.11MB + Engine MyISAM
wp_term_taxonomy: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_thesis_terms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 0.42MB + Index: 0.50MB + Engine InnoDB
wp_users: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.14MB + Index: 0.13MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.19MB + Index: 0.23MB + Engine InnoDB
wp_wc_order_stats: Data: 0.16MB + Index: 0.17MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 1.52MB + Index: 0.91MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfaqfields: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpfaqgroups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpfaqgroupsposts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfaqquestions: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_wpfaqquestionsgroups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpfaqquestionsposts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfaqquestionsquestions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_seo_links: Data: 0.34MB + Index: 0.14MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.13MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 4512
epkb_post_type_1: 60
fl-builder-template: 128
fl-theme-layout: 3
nav_menu_item: 188
page: 231
post: 121
product: 108
product_variation: 5720
revision: 2652
shop_coupon: 2
shop_order: 2260
shop_order_refund: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

Gravity Perks: by Gravity Wiz – 2.1.9
Gravity Forms: by Gravity Forms – 2.4.18
Attachment Pages Redirect: by Samuel Aguilera – 1.1.1
Beaver Builder Plugin (Standard Version): by The Beaver Builder Team – 2.3.2.5
Beaver Themer: by The Beaver Builder Team – 1.3.0.2
Knowledge Base for Documents and FAQs: by Echo Plugins – 6.4.2
Genesis Connect for WooCommerce: by StudioPress – 1.1.0 – Not tested with the active version of WooCommerce
Google XML Sitemaps: by Arne Brachhold – 4.1.0
GP Conditional Pricing: by Gravity Wiz – 1.2.40
Mailgun: by Mailgun – 1.7.1
Menu Image: by Rui Guerreiro – 2.9.6
Relevanssi: by Mikko Saari – 4.7.2.1
SG Optimizer: by SiteGround – 5.5.4
WooCommerce Cart-Based Shipping: by Erica Dion – 2.5.1 – Not tested with the active version of WooCommerce
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.21
WooCommerce PayTrace Payment Gateway: by VanboDevelops – 2.5.5
WooCommerce Purchase Order Payment Gateway: by WooCommerce – 1.2.9
WooCommerce Google Ads Conversion Tracking: by Wolf+Bär Agency – 1.6.4
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.21
WooCommerce Gravity Forms Product Add-Ons: by Lucas Stark – 3.3.11 – 3.3.12 is available
WooCommerce: by Automattic – 4.0.1 – 4.1.0 is available
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.0.19

### Inactive Plugins (3) ###

Classic Editor: by WordPress Contributors – 1.5
WordPress Importer: by wordpressdotorg – 0.7
WP Crontrol: by John Blackbourn & crontributors – 1.8.3

### Dropin Plugins (1) ###

object-cache.php: Memcached

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6600 - /shop/
Cart: #6601 - /cart/
Checkout: #7506 - /checkout/
My account: #6603 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Genesis Sample
Version: 3.0.1
Author URL: https://www.studiopress.com/
Child Theme: ✔
Parent Theme Name: Genesis
Parent Theme Version: 3.3.2
Parent Theme Author URL: https://www.studiopress.com/
WooCommerce Support: ✔

### Templates ###

Overrides: genesis-sample/woocommerce/cart/cart-item-data.php version 2.1.0 is out of date. The core version is 2.4.0
genesis-sample/woocommerce/cart/cart-shipping.php version 3.2.0 is out of date. The core version is 3.6.0
genesis-sample/woocommerce/cart/cart.php version 2.3.8 is out of date. The core version is 3.8.0
genesis-sample/woocommerce/checkout/review-order.php version 2.3.0 is out of date. The core version is 3.8.0
genesis-sample/woocommerce/emails/email-order-details.php version 3.2.0 is out of date. The core version is 3.7.0
genesis-sample/woocommerce/emails/email-order-items.php version 2.1.2 is out of date. The core version is 3.7.0
genesis-sample/woocommerce/order/order-details-item.php version 3.0.0 is out of date. The core version is 3.7.0
genesis-sample/woocommerce/order/order-details.php version 3.0.0 is out of date. The core version is 3.7.0
genesis-sample/woocommerce/single-product/add-to-cart/simple.php version 2.1.0 is out of date. The core version is 3.4.0
genesis-sample/woocommerce/single-product/short-description.php version 1.6.4 is out of date. The core version is 3.3.0
genesis-sample/woocommerce/single-product.php version 0.9.8 is out of date. The core version is 1.6.4

Outdated Templates: ❌
					
					
						Learn how to update

### Action Scheduler ###

Complete: 185
Oldest: 2020-04-14 15:05:40 -0400
Newest: 2020-05-11 15:35:41 -0400

Failed: 1
Oldest: 2020-04-22 16:00:11 -0400
Newest: 2020-04-22 16:00:11 -0400

Pending: 2
Oldest: 2020-05-12 15:47:35 -0400
Newest: 2020-05-12 15:47:35 -0400

### Paytrace Gateway ###

Integration type: post
Separated Forms: No
Accept Checks: No
Allow Vault Payments: No
Require CSC: No
Testmode: No
`
</details>

**Comment by tammullen** [comment]
Hi @danishmuneer 

Thank you for reporting the issue. I was able to reproduce it.

However, this issue has been reported previously here https://github.com/woocommerce/woocommerce/issues/25375. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
