### ISSUE TITLE
Hideous performance of the WooCommerce 4.0 admin migration code

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce#26452]
I upgraded a not small (but not particularly large as things go) site, with a six-figure number of existing customers/orders, to WooCommerce 4.0 five days ago.

During those 5 days, the total number of items in a "processing" state in action scheduler (thousands) has gone *up*, not down. The unprocessed items (in the "pending" state) goes back the full 5 days still. There are several things going on, but the main thing is a specific SQL query that's being run in sequence for every single customer, and it involves a row-scan of hundreds of thousands of rows every time. The query is getting all known orders for the customer, like so:

```
SELECT posts.ID
FROM wp_posts AS posts
LEFT JOIN wp_postmeta AS postmeta on posts.ID = postmeta.post_id
WHERE postmeta.meta_key = '_customer_user'
AND   postmeta.meta_value = '92339'
AND   posts.post_type = 'shop_order'
AND   posts.post_status IN ( 'wc-pending','wc-processing','wc-on-hold','wc-completed','wc-cancelled','wc-refunded','wc-failed' )
ORDER BY posts.ID DESC
```

As a method for finding a customer's orders, this is horribly inefficient. Even once we've (as we have) allowed MySQL to index the `postmeta` table by reducing the size of the `meta_key` column down to 191 (from its WP default of 255), this still forces MySQL to do a value scan across all the (hundreds of thousands of) rows that have the matching `meta_key` (of `_customer_user`) in order to then match the value. Hundreds of thousands is better than millions.... but still not enough to make the number of tasks to process go down, instead of up.

Of relevance: https://github.com/woocommerce/woocommerce/issues/17241

**Comment by rrennick** [comment]
The query in the description is from the customer data store: https://github.com/woocommerce/woocommerce/blob/master/includes/data-stores/class-wc-customer-data-store.php#L326

**Comment by claudiosanches** [comment]
Here the code that causes this problem:

https://github.com/woocommerce/woocommerce/blob/85a077b939b44500fc01b68d34e711117545f586/includes/data-stores/class-wc-customer-data-store.php#L319-L347

For sure it's an expensive query, and probably we could introduce a lookup table for customers.

**Comment by joshuatf** [comment]
In wc-admin that query is used to determine the most current info and update a customer in the customer lookup table.  It should only be run on `edit_user_profile_update` or `updated_user_meta` so I'd venture that the bigger issue here may be a failed AS job that causes this to be run permanently.

>For sure it's an expensive query, and probably we could introduce a lookup table for customers.

As far as the query itself goes, this is a good idea and since wc-admin makes use of a customer lookup table, we could cache the last order ID there to make this a bit more efficient.

**Comment by DavidAnderson684** [comment]
> I'd venture that the bigger issue here may be a failed AS job that causes this to be run permanently.

It appeared to run once for each customer in the tasks that were importing customer data into wc-admin that ran upon updating to WooCommerce 4.0.

**Comment by DavidAnderson684** [comment]
As per the mention in #27746, it appears that even though temporarily upgrading the CPU power on the MySQL server twenty-fold allowed me to run enough Action Scheduler tasks to clear the import backlog, at the end of it WooCommerce is saying that 0 orders/customers have been imported. The tables themselves have a very considerable number of rows, but not enough to match the actual number.

**Comment by rrennick** [comment]
> now (when I visit Analytics -> Settings, which I hadn't done before) WooCommerce is saying that 0 orders/customers have been imported.

The progress bars show the status of in-progress imports. It shows the zeros when no import is running. You can determine from the Analytics reports how many customers, orders, etc. have been imported.

**Comment by DavidAnderson684** [comment]
@rrennick OK, I understand - the "0" means "on this run" rather than "over the lifetime of the site".
In my case, though, it appears that I need to add 20x CPU power before considering starting that migration again. As such, I think I'll wait until either the migration code is improved, or until that table is powering something more than just analytics.
