### ISSUE TITLE
woocomecre plugin

### ISSUE THREAD

**Issue by shailight1** [woocommerce/woocommerce#26470]
**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

after that last update 
i lost the ability of seen the product discription.

as i scroll down and i try to press one of  fusion page option
it throws me to error 404

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only 

  | WooCommerce Measurement Price Calculator is
 active.
-

![Screen Shot 2020-05-12 at 7 04 29 PM](https://user-images.githubusercontent.com/65242764/81720677-67220500-9487-11ea-871f-b0ff287233f6.png)

`
### WordPress Environment ###

WordPress address (URL): https://light1.co.il
Site address (URL): https://light1.co.il
WC Version: 4.1.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.5
WC Admin Version: ✔ 1.1.1
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: he_IL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.33 - אנחנו ממליצים להשתמש ב-PHP גרסה 7.2 ומעלה מטעמי אבטחה וביצועים. כיצד לעדכן את גירסת ה-PHP שברשותך
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 1500
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.7.30
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.1.0
WC Database Prefix: wp_
הגודל הכולל של בסיס הנתונים: 30.70MB
גודל הנתונים של בסיס הנתונים: 25.59MB
גודל האינדקס של בסיס הנתונים: 5.11MB
wp_woocommerce_sessions: נתונים: 3.78MB + אינדקס: 0.07MB + מנוע MyISAM
wp_woocommerce_api_keys: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woocommerce_attribute_taxonomies: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woocommerce_downloadable_product_permissions: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woocommerce_order_items: נתונים: 0.02MB + אינדקס: 0.01MB + מנוע MyISAM
wp_woocommerce_order_itemmeta: נתונים: 0.15MB + אינדקס: 0.10MB + מנוע MyISAM
wp_woocommerce_tax_rates: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woocommerce_tax_rate_locations: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woocommerce_shipping_zones: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woocommerce_shipping_zone_locations: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woocommerce_shipping_zone_methods: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woocommerce_payment_tokens: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woocommerce_payment_tokenmeta: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woocommerce_log: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_actionscheduler_actions: נתונים: 1.08MB + אינדקס: 0.26MB + מנוע MyISAM
wp_actionscheduler_claims: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_actionscheduler_groups: נתונים: 0.00MB + אינדקס: 0.01MB + מנוע MyISAM
wp_actionscheduler_logs: נתונים: 0.59MB + אינדקס: 0.36MB + מנוע MyISAM
wp_ac_abandoned_cart_history_lite: נתונים: 0.91MB + אינדקס: 0.02MB + מנוע MyISAM
wp_ac_email_templates_lite: נתונים: 0.01MB + אינדקס: 0.00MB + מנוע MyISAM
wp_ac_guest_abandoned_cart_history_lite: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_ac_sent_history_lite: נתונים: 0.01MB + אינדקס: 0.00MB + מנוע MyISAM
wp_adtribes_my_conversions: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_aiowps_events: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_aiowps_failed_logins: נתונים: 0.22MB + אינדקס: 0.07MB + מנוע MyISAM
wp_aiowps_global_meta: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_aiowps_login_activity: נתונים: 0.02MB + אינדקס: 0.01MB + מנוע MyISAM
wp_aiowps_login_lockdown: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_aiowps_permanent_block: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_bp_activity: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_bp_activity_meta: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_bp_notifications: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_bp_notifications_meta: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_bp_xprofile_data: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_bp_xprofile_fields: נתונים: 0.00MB + אינדקס: 0.01MB + מנוע MyISAM
wp_bp_xprofile_groups: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_bp_xprofile_meta: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_commentmeta: נתונים: 0.00MB + אינדקס: 0.01MB + מנוע MyISAM
wp_comments: נתונים: 0.11MB + אינדקס: 0.05MB + מנוע MyISAM
wp_csp3_subscribers: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_eopa_global_rule_table: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_eopa_poptions_table: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_eopa_rowoption_table: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_eopa_temp_table: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_followup_coupons: נתונים: 0.00MB + אינדקס: 0.01MB + מנוע MyISAM
wp_followup_coupon_logs: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_followup_customers: נתונים: 0.01MB + אינדקס: 0.02MB + מנוע MyISAM
wp_followup_customer_carts: נתונים: 0.04MB + אינדקס: 0.01MB + מנוע MyISAM
wp_followup_customer_notes: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_followup_customer_orders: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_followup_email_excludes: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_followup_email_logs: נתונים: 0.02MB + אינדקס: 0.01MB + מנוע MyISAM
wp_followup_email_orders: נתונים: 0.31MB + אינדקס: 0.06MB + מנוע MyISAM
wp_followup_email_tracking: נתונים: 0.01MB + אינדקס: 0.02MB + מנוע MyISAM
wp_followup_followup_history: נתונים: 0.38MB + אינדקס: 0.02MB + מנוע MyISAM
wp_followup_order_categories: נתונים: 0.01MB + אינדקס: 0.02MB + מנוע MyISAM
wp_followup_order_items: נתונים: 0.01MB + אינדקס: 0.02MB + מנוע MyISAM
wp_followup_subscribers: נתונים: 0.00MB + אינדקס: 0.01MB + מנוע MyISAM
wp_followup_subscribers_to_lists: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_followup_subscriber_lists: נתונים: 0.00MB + אינדקס: 0.01MB + מנוע MyISAM
wp_grp_google_place: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_grp_google_review: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_layerslider: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע MyISAM
wp_layerslider_revisions: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_links: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_options: נתונים: 8.04MB + אינדקס: 0.81MB + מנוע MyISAM
wp_postmeta: נתונים: 6.34MB + אינדקס: 2.09MB + מנוע MyISAM
wp_posts: נתונים: 0.62MB + אינדקס: 0.18MB + מנוע MyISAM
wp_shipment_batch_process: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_signups: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_termmeta: נתונים: 0.05MB + אינדקס: 0.03MB + מנוע MyISAM
wp_terms: נתונים: 0.03MB + אינדקס: 0.06MB + מנוע MyISAM
wp_term_relationships: נתונים: 0.12MB + אינדקס: 0.21MB + מנוע MyISAM
wp_term_taxonomy: נתונים: 0.02MB + אינדקס: 0.03MB + מנוע MyISAM
wp_usermeta: נתונים: 0.16MB + אינדקס: 0.04MB + מנוע MyISAM
wp_users: נתונים: 0.00MB + אינדקס: 0.01MB + מנוע MyISAM
wp_vi_wad_ali_orders_info: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_vi_wad_error_product_images: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_vtprd_purchase_log: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_vtprd_purchase_log_product: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_vtprd_purchase_log_product_rule: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wcpdf_invoice_number: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wc_admin_notes: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wc_admin_note_actions: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wc_category_lookup: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wc_customer_lookup: נתונים: 0.01MB + אינדקס: 0.02MB + מנוע MyISAM
wp_wc_download_log: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wc_order_coupon_lookup: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wc_order_product_lookup: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע MyISAM
wp_wc_order_stats: נתונים: 0.01MB + אינדקס: 0.02MB + מנוע MyISAM
wp_wc_order_tax_lookup: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wc_product_meta_lookup: נתונים: 0.06MB + אינדקס: 0.07MB + מנוע MyISAM
wp_wc_tax_rate_classes: נתונים: 0.00MB + אינדקס: 0.01MB + מנוע MyISAM
wp_wc_webhooks: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wfblockediplog: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wfblocks7: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wfconfig: נתונים: 0.38MB + אינדקס: 0.01MB + מנוע MyISAM
wp_wfcrawlers: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wffilechanges: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wffilemods: נתונים: 1.15MB + אינדקס: 0.17MB + מנוע MyISAM
wp_wfhits: נתונים: 0.03MB + אינדקס: 0.01MB + מנוע MyISAM
wp_wfhoover: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wfissues: נתונים: 0.00MB + אינדקס: 0.01MB + מנוע MyISAM
wp_wfknownfilelist: נתונים: 0.59MB + אינדקס: 0.08MB + מנוע MyISAM
wp_wflivetraffichuman: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wflocs: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wflogins: נתונים: 0.02MB + אינדקס: 0.01MB + מנוע MyISAM
wp_wfls_2fa_secrets: נתונים: 0.02MB + אינדקס: 0.02MB + מנוע InnoDB
wp_wfls_settings: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_wfnotifications: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wfpendingissues: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wfreversecache: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wfsnipcache: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wfstatus: נתונים: 0.02MB + אינדקס: 0.01MB + מנוע MyISAM
wp_wftrafficrates: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woo_shipment_status_email: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_woo_shippment_provider: נתונים: 0.01MB + אינדקס: 0.00MB + מנוע MyISAM
wp_wpgmza: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_wpgmza_categories: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_wpgmza_category_maps: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_wpgmza_circles: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_wpgmza_maps: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_wpgmza_polygon: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_wpgmza_polylines: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_wpgmza_rectangles: נתונים: 0.02MB + אינדקס: 0.00MB + מנוע InnoDB
wp_yoast_seo_links: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM
wp_yoast_seo_meta: נתונים: 0.00MB + אינדקס: 0.00MB + מנוע MyISAM

### Post Type Counts ###

attachment: 716
bp-email: 16
cartflows_flow: 1
cartflows_step: 3
custom_css: 1
follow_up_email: 4
fusion_element: 2
jetpack_migration: 2
mc4wp-form: 1
nav_menu_item: 24
oembed_cache: 2
page: 14
post: 16
product: 315
product_variation: 511
pw_bogo: 2
shop_coupon: 7
shop_order: 165
shop_order_refund: 12
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

LayerSlider WP: מאת Kreatura Media – 6.7.6
All In One WP Security: מאת Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.4.3

טפסי צרו קשר 7: מאת טקאיוקי מיושי – 5.1.7
Facebook for WooCommerce: מאת Facebook – 1.11.2
Fusion Builder: מאת ThemeFusion – 1.8.2
Fusion Core: מאת ThemeFusion – 3.8.2
Reviews and Rating - Google Business: מאת Noah Hearle
Design Extreme – 3.3

סקריפטים בהדר ובפוטר: מאת WPBeginner – 1.4.5
Loco Translate: מאת Tim Whitlock – 2.3.3
PW WooCommerce BOGO Pro: מאת Pimwick
LLC – 2.129

Server IP & Memory Usage Display: מאת Apasionados
Apasionados del Marketing – 2.1.0

WC Hide Shipping Methods: מאת Rynaldo Stoltz – 1.3
WooCommerce Cart Add-Ons: מאת WooCommerce – 1.5.22 (העדכון לגרסה 1.5.28 זמין) – הגרסה המתוקנת לא נבדקה עם הגרסה הפעילה של WooCommerce 4.1.0
Follow-Up Emails: מאת WooCommerce – 4.9.1
Woocommerce iCredit: מאת rivhit.co.il – 3.1 – הגרסה המתוקנת לא נבדקה עם הגרסה הפעילה של WooCommerce 4.1.0
WooCommerce Variation Swatches and Photos: מאת Lucas Stark – 2.1.4 (העדכון לגרסה 3.1.1 זמין) – הגרסה המתוקנת לא נבדקה עם הגרסה הפעילה של WooCommerce 4.1.0
ווקומרס: מאת חברת אוטומטיק – 4.1.0
WP Rocket: מאת WP Media – 2.11.6

### Inactive Plugins (4) ###

Abandoned Cart Lite for WooCommerce: מאת Tyche Softwares – 5.7.2 – הגרסה המתוקנת לא נבדקה עם הגרסה הפעילה של WooCommerce 4.1.0
All In One SEO Pack Pro: מאת All in One SEO Team – 3.4.3
DreamHost Automated Migration: מאת DreamHost – 3.9
WooCommerce Measurement Price Calculator: מאת SkyVerge – 3.13.3 (העדכון לגרסה 3.17.4 זמין) – הגרסה המתוקנת לא נבדקה עם הגרסה הפעילה של WooCommerce 4.1.0

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: ILS (₪)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

בסיס חנות: #24 - /shop/
סל קניות: #25 - /cart/
תשלום: #26 - /checkout/
החשבון שלי: ❌ העמוד לא מכיל את פקודת המקרו.
תנאי שימוש: #1477 - /%d7%aa%d7%a7%d7%a0%d7%95%d7%9f-%d7%94%d7%90%d7%aa%d7%a8/

### Theme ###

Name: Avada
Version: 5.8.2
Author URL: http://themeforest.net/user/ThemeFusion
Child Theme: ❌ – אם משנים את ווקומרס בערכת נושא אב שלא נבנתה באופן אישי
מומלץ להשתמש בערכת עיצוב בת. אפשר לראות: כיצד ליצור ערכת עיצוב בת

WooCommerce Support: ✔

### Templates ###

Overrides: Avada/woocommerce/cart/cart.php גרסה 3.5.0 אינה עדכנית. גרסת הליבה היא 3.8.0
Avada/woocommerce/checkout/form-pay.php
Avada/woocommerce/checkout/review-order.php גרסה 3.3.0 אינה עדכנית. גרסת הליבה היא 3.8.0
Avada/woocommerce/checkout/thankyou.php גרסה 3.2.0 אינה עדכנית. גרסת הליבה היא 3.7.0
Avada/woocommerce/loop/loop-start.php
Avada/woocommerce/single-product/add-to-cart/variable.php
Avada/woocommerce/single-product/short-description.php
Avada/woocommerce/single-product/tabs/additional-information.php
Avada/woocommerce/single-product/tabs/description.php

Outdated Templates: ❌
					
					
						למד כיצד לעדכן

### Action Scheduler ###

הושלם: 3,027
Oldest: 2020-05-03 14:43:38 +0300
Newest: 2020-05-12 19:30:08 +0300

נכשל: 3
Oldest: –
Newest: –

ממתין לאישור: 9
Oldest: 2020-05-12 19:33:43 +0300
Newest: 2020-05-19 18:31:11 +0300

`
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by juliaamosova** [comment]
Hi @shailight1,

Thank you for raising the issue. 

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by shailight1** [comment]
Hello, thanks for the fast reply.
I did try  to close all plugins and I found the woocommerce measurement
price calculator

בתאריך יום ג׳, 12 במאי 2020, 20:09, מאת Julia Amosova ‏<
notifications@github.com>:

**Comment by juliaamosova** [comment]
Hi @shailight1,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

As you confirmed in your testing, the issue you are having is caused by the [Measurement Price Calculator](https://woocommerce.com/products/measurement-price-calculator/) plugin which is one of the paid products on our marketplace. To get further technical support for it, please contact the WooCommerce helpdesk by [opening a ticket](https://woocommerce.com/contact-us/). 

On the side note, I see in your System Status report that you are using outdated version of the Measurement Price Calculator plugin:

>WooCommerce Measurement Price Calculator: מאת SkyVerge – 3.13.3 (העדכון לגרסה 3.17.4 זמין) – הגרסה המתוקנת לא נבדקה עם הגרסה הפעילה של WooCommerce 4.1.0

It is highly likely that the issue will be resolved as soon as you update the Measurement Price Calculator plugin. 

I am closing this issue since it is not directly caused by WooCommerce Core.
