### ISSUE TITLE
Chrome crashes when previewing drafted posts while WC is active.

### ISSUE THREAD

**Issue by CGlingener** [woocommerce/woocommerce#26474]
**Describe the bug**
Using the "Preview" button of a **drafted** post, **which has a metabox**, while WooCommerce is active, results in a never resolving requests. Once more than 5 never resolving requests are present the preview will no longer being loaded and chrome just shows "Waiting for available sockets".

**To Reproduce**
When having

* chrome
* the block editor
* WooCommerce active
* a drafted post edit page
* which has a metabox applied (no matter which content)
* and the user clicks "Preview"
* this http request is triggered /wp-admin/post.php?post=146&action=edit&message=4
* which gets never resolved:
<img width="1265" alt="pending" src="https://user-images.githubusercontent.com/1089098/81739405-980c3500-949b-11ea-80d2-79255e953662.png">
* and even worse, it stacks with every further click on "Preview" <img width="1266" alt="pending-5x" src="https://user-images.githubusercontent.com/1089098/81739466-b83bf400-949b-11ea-8a73-109a4bcaf279.png">
* once 5 pending requests are in the pipeline, the preview no longer gets loaded (on the 6th click)

These pending requests can be on a single tab or split over multiple - that doesn't matter. When a tab with a pending request is closed the socket is available again and can be used for the preview.

This happening because WooCommerce changes the Cache-Control headers and applies `no-store` there. And that, for same reason, does not work on Chrome on that specific requests and ends in a never ending request. => https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cache-helper.php#L44

Removing the `no-store` and it’s working fine again.

**I know, it’s probably a Chrome bug** and I will also report it there, but to be honest I don’t expect that they will handle it with a very high priority.

And having multiple tabs open while editing a site is not very uncommon, so this bug can become very annoying. (Plus the unnecessary load on the server.)

We (toolset.com) will add a function which will remove the no-store property for that specific page call (action=edit&message=4) – just wanted to let you know, as your clients may also ran into this issue and maybe you do not require the `no-store` parameter at all (which I guess from the comment in the source code).

**Expected behavior**
No never ending http requests.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active. **And any metabox is active.**
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

WordPress address (URL): http://performance.vb
Site address (URL): http://performance.vb
WC Version: 4.1.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.5
WC Admin Version: ✔ 1.1.1
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.29 (Ubuntu)
PHP Version: 7.2.27-1+ubuntu18.04.1+deb.sury.org+1
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.30-0ubuntu0.18.04.1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.1.0
WC Database Prefix: wp_
Total Database Size: 3.58MB
Database Data Size: 2.01MB
Database Index Size: 1.57MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.05MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_toolset_associations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_toolset_post_guid_id: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_toolset_relationships: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_toolset_type_sets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
children: 32
page: 13
parents: 42
post: 33
revision: 38
wp-types-group: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

Toolset Types: by OnTheGoSystems – 3.3.10
WooCommerce: by Automattic – 4.1.0

### Inactive Plugins (4) ###

Custom Meta Box Boilerplate: by christophherr – 1.0.0
Register 300 Rest Routes: by Christian – 1.0
Remove 'no-store' Cache-Control for post preview.: by Christian – 1.0 – Installed version not tested with active version of WooCommerce 4.1.0
Toolset Types with fix for Chrome: by OnTheGoSystems – 3.3.10

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #60 - /?page_id=60
Cart: #61 - /?page_id=61
Checkout: #62 - /?page_id=62
My account: #63 - /?page_id=63
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Pending: 2
Oldest: 2020-05-07 19:57:35 +0000
Newest: 2020-05-07 20:52:18 +0000
```
</details>

**Comment by talldan** [comment]
The same issue was also described in WordPress/gutenberg#22688.

**Comment by palbera** [comment]
Hi @CGlingener 

I am facing with same issue with chrome and is very annoying

You wrote that you developed a function to disable `no-store` http response header, could you please share it in order to copy and paste in the functions.php file?

I will appreciate it

Thanks

**Comment by CGlingener** [comment]
@palbera 

we're using this temporary fix:

```php
/*
 * Hotfix for Chrome crashing when clicking on "Preview" of a drafted post.
 * Problem: WooCommerce is adding "no-store" to Cache-Control to nearly any request
 * and Chrome can't handle it in the preview process.
 *
 * Can be removed once this WooCommerce Ticket is resolved:
 * https://github.com/woocommerce/woocommerce/issues/26474
 */
if( ! function_exists( 'wc_chrome_no_cache_fix' ) ) {
	function wc_chrome_no_cache_fix( $headers ) {
		if( isset( $headers['Cache-Control'] ) ) {
			$cache_control = strtolower( $headers['Cache-Control'] );
			if( strpos( $cache_control, 'no-store') !== false ) {
				$headers['Cache-Control'] = str_replace(
					[ ', no-store', ',no-store', 'no-store, ', 'no-store,', 'no-store' ],
					'',
					$cache_control
				);
			}
		}

		return $headers;
	}

	// Only add filter to remove 'no-store' on ./wp-admin/post.php?post=146&action=edit&message=4 calls.
	// (That http request is only triggered when the "Preview" button is clicked.)
	if(
		isset( $_REQUEST['action'] ) &&
		isset( $_REQUEST['message'] ) &&
		$_REQUEST['action'] === 'edit' &&
		$_REQUEST['message'] === '4'
	) {
		// Remove 'no-store' from HTTP header Cache-Controls. WordPress does not use it at all, but WooCommerce adds it.
		add_filter( 'nocache_headers', 'wc_chrome_no_cache_fix', PHP_INT_MAX );
	}
}

```

**Comment by palbera** [comment]
Thanks a lot @CGlingener, your workaround works like a charm

I hope this solution would be implemented soon by the woocommerce dev team

Cheers

**Comment by zfeezy** [comment]
Thanks all @here, and fyi to anyone working on this -- the no-store issue from above was my culprit too, but it isn't only WooCommerce causing the issue. In my case it was the WP Migrate DB plugin. So... check your plugins!

**Comment by patrick-leb** [comment]
thanks @CGlingener, your fix worked perfectly.

Is there any drawbacks to remove the `no-store` here?

**Comment by CGlingener** [comment]
@patrick-leb I can't think of any drawback as the fix just targets the preview page. For all other pages the no-store will still be active.

My guess is that woocommerce is adding the `no-store` to make sure the frontend products data is always up do date and nothing cached or maybe some reason related to the shopping cart. As they did not expect any harm by adding the no-store they simply applied it to every request.

**Comment by patrick-leb** [comment]
It's really not Woo's fault here, clearly Chrome isn't handling it right. Who knows when Chrome is going to fix that though...

**Comment by rrennick** [comment]
WordPress now does previews in a new tab which loaded fine for me. I'll close this issue as it both seems resolved by the latest WP and is not directly related to WooCommerce.
