### ISSUE TITLE
Add warning on changing downloadable products

### ISSUE THREAD

**Issue by FreshPhil** [woocommerce/woocommerce#26475]
**Is your feature request related to a problem? Please describe.**
Currently, if you change a simple downloadable product and to a variable downloadable product, there is no indication that existing customers will lose their downloads.

2968918-zen

**Describe the solution you'd like**
Some prompt or notice that informs you that this change would result in previous customers losing access. 

**Describe alternatives you've considered**
Another option would be to lock in the customer permissions based on their original order, not the current product. That has a much broader impact that would need to be considered though.

**Comment by juliaamosova** [comment]
Hi @FreshPhil,

Thanks for raising this! Marking it as an enhancement for now. We will see if we can work on it sooner than later.

**Comment by SiobhyB** [comment]
I wanted to note that this caused quite a lot of trouble for a business in 3450550-zen. They weren't aware that previous customers would lose access as a result of the change, leading to 1000+ customers, spanning back years, losing access.

**Comment by roykho** [comment]
Did a bit of initial digging into this and I believe the current behavior might not be the best approach. Currently we are assuming the purchased downloaded product does not change in terms of the product type or even if the downloadable file gets removed.

I agree with Phil.

IMHO A customer order should not be dependent on a product once it has been purchased. All the data that is stored with the order should be sufficient to retrieve the downloaded file regardless if there are any new changes to the product itself.

It is no different from say a subscription product. After a subscription order is made, if you change the product's price, it does not affect the on-going subscriptions price but just for new customers. Same idea should be implement for downloadable products.

With that said, this may be a heavier lift than just simply displaying a warning.
