### ISSUE TITLE
Lack of core business features

### ISSUE THREAD

**Issue by psealock** [woocommerce/woocommerce#26482]
@peterpenguw commented on [Wed May 13 2020](https://github.com/woocommerce/woocommerce-admin/issues/4354)

At $30/month, it is very hard to pick WooCommerce over Shopify when I consult with clients.  The only businesses WooCommerce can attract at this state are **taboo industries**, strange business models or very budget level testing projects (bulk of users are not making $, so WooCommerce is not making $).

The problem is the lack of core business features.  The last 4.0 update of Woo seems to be mostly cosmetics (reports) and fringe features (schedulers).  However, operating a real WooCommerce business (>10 employees, >2mil rev) where the owner is always wishing they were back with Shopify, here are the plugins we need just to get a bare bones business working:

Active plugins (61)
--
Redux Framework |   | by Team Redux – 3.6.15
Admin CSS MU |   | by Arun Basil Lal – 2.5
Admin Menu Editor |   | by Janis Elsts – 1.9.5
Advanced Custom Fields |   | by Elliot Condon – 5.8.10
Akismet Anti-Spam |   | by Automattic – 4.1.5
Activity Log |   | by Activity Log Team – 2.5.2
Classic Editor |   | by WordPress Contributors – 1.5
Conditional Shipping for WooCommerce |   | by Lauri Karisola / WooElements.com – 2.0.2 – Installed version not tested with active version of WooCommerce 4.1.0
Contact Form 7 |   | by Takayuki Miyoshi – 5.1.7
Disable/Remove Google Fonts |   | by Fonts Plugin – 1.1.3
Google Tag Manager for Wordpress |   | by Thomas Geiger – 1.11.4 – Installed version not tested with active version of WooCommerce 4.1.0
Electro Extensions |   | by MadrasThemes – 2.5.5 – Installed version not tested with active version of WooCommerce 4.1.0
Envato Market |   | by Envato – 2.0.3
Filter WooCommerce Orders by Create Method |   | by iMediaDesigns – 1.0.0 – Installed version not tested with active version of WooCommerce 4.1.0
Flexible Checkout Fields PRO |   | by WP Desk – 1.7 – Installed version not tested with active version of WooCommerce 4.1.0
Flexible Checkout Fields |   | by WP Desk – 2.4.10
FraudLabs Pro for WooCommerce |   | by FraudLabs Pro – 2.13.8 – Installed version not tested with active version of WooCommerce 4.1.0
Header Footer Code Manager |   | by 99robots – 1.1.7
WPBakery Page Builder |   | by Michael M - WPBakery.com – 6.0.5
Kadence WooCommerce Email Designer |   | by Kadence WP – 1.4.1 – Installed version not tested with active version of WooCommerce 4.1.0
MC4WP: Mailchimp for WordPress |   | by ibericode – 4.7.7
Media Cleaner |   | by Jordy Meow – 5.6.3
Mega Main Menu |   | by MegaMain.com – 2.1.7
One Click Demo Import |   | by ProteusThemes – 2.5.2
Post Views Counter |   | by Digital Factory – 1.3.1
Postmen Woocommerce Shipping |   | by <a href="https://www.postmen.com/">Postmen</a> – 1.1.9 – Installed version not tested with active version of WooCommerce 4.1.0
PW WooCommerce Bulk Edit |   | by Pimwick, LLC – 2.74
Really Simple SSL |   | by Rogier Lankhorst, Mark Wolters – 3.2.6
Slider Revolution |   | by ThemePunch – 5.4.8
RoadThemes Helper |   | by RoadThemes – 1.0.0
Shortcodes Ultimate |   | by Vladimir Anokhin – 5.8.1
Templatera |   | by WPBakery – 1.1.11
WooCommerce Conditional Shipping Pro |   | by Lauri Karisola / WooElements.com – 2.2.6 – Installed version not tested with active version of WooCommerce 4.1.0
Woo Default Attributes |   | by Kuuak – 1.0.4 – Installed version not tested with active version of WooCommerce 4.1.0
Advanced Order Export For WooCommerce |   | by AlgolPlus – 3.1.4 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce Order Navigation |   | by FullStack – 1.0.0 – Installed version not tested with active version of WooCommerce 4.1.0
Canpar Rate Calculator |   | by Canpar Courier – 1.0.7
WooCommerce Cost of Goods |   | by SkyVerge – 2.8.1 (update to version 2.9.6 is available) – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce Duplicate Billing Address |   | by Andrew Schultz – 1.16 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce DYMO Print Product Add-on |   | by WP Fortune – 5.0.10 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce DYMO Print |   | by WP Fortune – 5.0.9 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce PayPal Checkout Gateway |   | by WooCommerce – 1.6.5 (update to version 1.6.21 is available) – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce PDF Invoices & Packing Slips |   | by Ewout Fernhout – 2.4.10
WooCommerce POS Pro |   | by kilbot – 0.4.19 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce POS |   | by kilbot – 0.4.24 – Installed version not tested with active version of WooCommerce 4.1.0
Woocommerce Products Per Page |   | by Jeroen Sormani – 1.2.6 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce Canada Post Shipping |   | by WooCommerce – 2.5.7 (update to version 2.5.16 is available) – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce - ShipStation Integration |   | by WooCommerce – 4.1.36
WooCommerce |   | by Automattic – 4.1.0
XL NMI Gateway for WooCommerce |   | by XLPlugins – 1.8.4 – Installed version not tested with active version of WooCommerce 4.1.0
Wordfence Security |   | by Wordfence – 7.4.7
Yoast SEO Premium |   | by Team Yoast – 9.3
WP File Manager |   | by mndpsingh287 – 5.9
WP Mail Logging |   | by MailPoet – 1.9.6
WP Sitemap Page |   | by Tony Archambeau – 1.6.2
Smush Pro |   | by WPMU DEV – 3.2.0.2
Smush Pro |   | by WPMU DEV – 3.2.0.2
WP Fortune |   | by WP Fortune – 1.0.8
WPMU DEV Dashboard |   | by WPMU DEV – 4.8.1
WPS Cleaner |   | by WPServeur, NicolasKulka – 1.4.7
YITH WooCommerce Ajax Product Filter Premium |   | by YITH – 3.9.0 – Installed version not tested with active version of WooCommerce 4.1.0

The problem is testing, maintaining, and making sure all 60+ plugins WORK.  And make sure you have a fast website.  **This is basically incurring cost of running a WooCommerce business to be much more than Shopify's!** 

**Describe the solution you'd like**
Here are some core features that should NOT be another plugin to install & test:
- Duplicate (clone) any type of element in Admin, whether it's pages, menus, products
- Imsanity
Admin CSS MU |   | by Arun Basil Lal – 2.5
Admin Menu Editor |   | by Janis Elsts – 1.9.5
Advanced Custom Fields |   | by Elliot Condon – 5.8.10
Akismet Anti-Spam |   | by Automattic – 4.1.5
Activity Log |   | by Activity Log Team – 2.5.2
WPS Cleaner |   | by WPServeur, NicolasKulka – 1.4.7
WP File Manager |   | by mndpsingh287 – 5.9
WP Mail Logging |   | by MailPoet – 1.9.6
WP Sitemap Page |   | by Tony Archambeau – 1.6.2
WooCommerce Conditional Shipping Pro |   | by Lauri Karisola / WooElements.com – 2.2.6
Woo Default Attributes |   | by Kuuak – 1.0.4 
Advanced Order Export For WooCommerce |   

**Describe alternatives you've considered**
Shopify

**Should this be prioritized? Why?**
Because at this rate WooCommerce will forever be slowing its growth once people realize Shopify is better.

**Comment by tammullen** [comment]
Closing in favor of original issue
