### ISSUE TITLE
Bring Custom Emails editing up to par with Shopify

### ISSUE THREAD

**Issue by peterpenguw** [woocommerce/woocommerce#26489]
Problem: 
Say you want a customized note or foot at the bottom of all "order complete" emails you send to customers. The default WooCommerce email editing system requires knowledge of PHP to edit.  Compared to Shopify's simple email customization experience, Woo is very behind.

Solution: 
Simply look at a plugin like "Kadance Email Designer" and either collaborate or build a similar solution.  We have roughly 20 orders per day and this plugin should be core! (https://www.kadencewp.com/product/woocommerce-email-designer/)

This is a priority because A) every other platform is ahead B) clean emails = good customer service!

**Comment by juliaamosova** [comment]
Hi @peterpenguw,

Thanks for opening this feature request. We have plans to reimagine the email editing experience for merchants in WooCommerce but nothing concrete that we can share at the moment. 

I am going to close this issue as it is already on our radar. Thanks again!
