### ISSUE TITLE
On Sale filter Widget

### ISSUE THREAD

**Issue by ibndawood** [woocommerce/woocommerce#26498]
**Is your feature request related to a problem? Please describe.**
Currently, there are no filters to view the products that are on sale in shop or product archive page. This is especially helpful for users who are looking for deals in the shop.

**Describe the solution you'd like**
We should have a filter with a check box that filters only products that are on sale in the products archive page.

**Describe alternatives you've considered**
Currently WooCommerce provides a shortcode and WooCommerce blocks to display on sale products but it does not have a pagination option and cannot be used to filter with other filters.

**Additional context**
I am interested in building this feature if you go ahead. I have earlier contributed to Star rating filter feature.

**Comment by juliaamosova** [comment]
Hi @ibndawood,

Thanks for opening this feature request and for offering contributing to it. 

We have a [WooCommerce Product Search](https://woocommerce.com/products/woocommerce-product-search/) plugin on our marketplace that offers the [Product Filter – Sale widget](https://docs.woocommerce.com/document/woocommerce-product-search/widgets/product-filter-sale/) already. Therefore, we don't see a strong need in offering this widget in core.  

In any case, I will add an `enhancement` label to your issue with the `votes needed` tag to see if we can collect more interest on it over time.

**Comment by ibndawood** [comment]
Thank you @juliaamosova for your response.
