### ISSUE TITLE
'Update woocommerce database needed' keeps showing up, while update is complete

### ISSUE THREAD

**Issue by hotpt** [woocommerce/woocommerce#26506]
Hi,

I have an issue with the update of the woocommerce database message. 
I did the update but still this message keeps appearing in admin that I need to update my woocommerce database.
The image I enclosed in this post is in Dutch, so I don't know the exact text of the message in English.
When I click on this Update Wocommerce database button, the next image appears, saying: the link you followed is expired. Please try again.

Hope someons knows about the issue because I cannot find it in other support threads.

![woo_database](https://user-images.githubusercontent.com/36693432/81900532-478cf880-95bd-11ea-9edb-176f8624830b.png)
![woo_database1](https://user-images.githubusercontent.com/36693432/81900817-de59b500-95bd-11ea-8f74-01c04c6f13ab.png)

**Comment by tammullen** [comment]
Hi @hotpt 

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce-admin/issues/4114. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
