### ISSUE TITLE
[4.2] Importer mapping form not automatically prefilled

### ISSUE THREAD

**Issue by Chouby** [woocommerce/woocommerce#26507]
**Describe the bug**
The version 4.2 introduces a regression as the mapping form of the products importer is no more  automatically prefilled (intially detected thanks to phpunit integration test).

**To Reproduce**
1. On a fresh install, go to the Products list
2. Click on "Start Import".
3. Select a CSV file and click on "Continue".

**CSV for tests**
```csv
SKU,Name,Price,Stock
Sku-1,Product-1,99,3000
Sku-2,Product-2,99,3000
```

**Screenshots**
Result in WooCommerce 4.1: 
![WC-4 1](https://user-images.githubusercontent.com/3238583/81933024-f8f75280-95ec-11ea-8017-d1eb2fc7aa31.png)
Result in WooCommerce 4.2: 
![WC-4 2](https://user-images.githubusercontent.com/3238583/81933033-fbf24300-95ec-11ea-9e02-4984fadc6d89.png)

**Expected behavior**
I expect the mapping from to be correctly prefilled. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment]
Hi @Chouby 

Thank you for taking the time reporting this bug, we really appreciate your help. I can reproduce it on my end. 
​
![Screenshot 2020-05-14 at 17 55 04](https://user-images.githubusercontent.com/24649833/81963010-7088aa00-960c-11ea-9fd3-ecc39070b334.png)
![Screenshot 2020-05-14 at 17 55 24](https://user-images.githubusercontent.com/24649833/81963025-754d5e00-960c-11ea-819f-1cce57918d18.png)

​
We’re going to solve this bug as soon as possible. Stay tuned for updates.
