### ISSUE TITLE
[GlobalStep - 4.2 Beta] Database error is displayed upon clicking "Connect" button during payment setup of CBD Vertical On boarding Flow.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#26512]
**Environment:**
Windows 10- Google Chrome (Version 81.0.4044.138)
Mac Mojave-10.14.6-Safari(v13.0.5 )

**Steps to Reproduce:** 
1. Create a site using Ninja tool.
2. Install all the plugins.
3. Tap on "Run the Setup wizard" and then tap on "Yes Please" button.
4. Complete all the introductory tabs i.e., Store details, Industry-Select CBD only, Product types, Business details and Theme. 
5. Now on Dashboard> "Setup Checklist", select "Setup Payments" at the bottom of the list
6. Square payments is shown, and click on "Set Up" button.
7. After plugin installed, Click on the "Connect" button.
7. Observe that in CBD Vertical On boarding Flow, database error is displayed upon clicking "Connect"  button for Square option.

**Actual Result:**
Database error is displayed upon clicking "Connect" button during payment setup of CBD Vertical On boarding Flow.

**Expected Result:**
In CBD Vertical On boarding Flow no database error should be displayed by clicking on "Connect " button for Square option.

![#26512](https://user-images.githubusercontent.com/41110392/81951087-5d80d480-9622-11ea-92b1-c2ec0a746a41.jpg)

**Comment by juliaamosova** [comment]
Hi @gglobalstep,

Thanks for reporting this issue! 

We had it open in our Square repository: https://github.com/woocommerce/woocommerce-square/issues/419 - it is a private repository that only the developers of Square plugin have access (posting here for the reference anyways). 

Copying the response of @james-allan from that team:

I've been able to replicate this issue on my local install just by activating the plugin for the first time, going through the Woo OBW wasn't necessary.

There are a couple of strange things about this error. 

1. It only appears in Query Monitor (QM).
2. No errors are logged in the error log. 
2. No error is returned from `$wpdb->last_error` after running the query.
3. Running the query manually via the database directly doesn't throw any errors. 
3. Looking at other plugin's _create table queries_ (WC Core and WC Subscriptions) I noticed that they don't include the `IF NOT EXISTS` that is in Square's query (see [here](https://github.com/woocommerce/woocommerce-square/blob/2.1.4/includes/Gateway/Customer_Helper.php#L178 )). 
      - `dbdelta()` is designed to only create tables if they don't exist so removing it should be fine. 
      - After removing the `IF NOT EXISTS` I now get [this error in QM](https://user-images.githubusercontent.com/8490476/81641042-71caa300-9463-11ea-8208-a96b4b747aa1.png).
      - Similar to the original issue. This only appears in QM. No other errors are logged anywhere.
      - Given the query now changed to `DESCRIBE {table name}` I started to think this was just QM hooking into the query and running some queries of its own. 
     -  Going back to the original issue, I suspect somewhere in this QM function it's attempting to pluck the table name out of the query and getting the `IF` from the original query. That causes an error because `IF` is a SQL keyword. It gets the correct table in the updated query, but then errors because the table doesn't exist.
     - To confirm this, I replicated the issue with a WC core dbdelta query. See below. 

<img width="1047" alt="Screen Shot 2020-05-12 at 3 23 11 pm" src="https://user-images.githubusercontent.com/8490476/81641525-85c2d480-9464-11ea-8419-7f717445a0dc.png">

Doing some Googling I found others reporting this issue with QM as well. For example https://wordpress.org/support/topic/database-error-with-query-monitor-describe-if/

With that in mind, I'm going to close this one.

**Comment by gglobalstep** [comment]
This issue is observed to be **Open** on WooCommerce 4.2 RC 1
**Environment:**
Windows
OS: 10
Browser: Chrome(Version 81.0.4044.138 (64-bit))

MAC
OS: Mojave v10.14.6
Browser: Safari(v13.0.5)

**Comment by gglobalstep** [comment]
This issue is observed to be **"Open"** on WooCommerce 4.3 Beta.

**Environment:**
**Windows 10**
Browser: Chrome(Version 83.0.4103.61)(64-bit)
Browser: Firefox(Version 77.0.1)(64-bit)
**MacBook Pro Version 10.15.5 (19F101)**
Browser: Safari(Version 13.1.1)(15609.2.9.1.2)
