### ISSUE TITLE
Admin Order detail page : Is_virtual loaded from product, not from the order

### ISSUE THREAD

**Issue by TheGranadilla** [woocommerce/woocommerce#26523]
I'm dynamically setting a product "virtual" in cart, by using : $cart_item['data']->set_virtual( 1 );

Order get saved correctly, and there is no shipping triggered, as expected, since it's now a virtual product.

BUT, if admin review the order, there is a shipping line displayed (but ignored in total amount), like if the "virtual" value registered in the order is ignored, but retrieved from product->is_virtual, during order review.

So if the admin update the order (ex. to "complete"), the shipping line is added and recorded to the order, and the client receive an e.mail with a total amount not matching what he paid (shipping added). This doesn't happend if the admin set the order to complete from the orders listings pages. (quick action)

**To Reproduce**
- Dynamically set a product to virtual, in the cart ($cart_item['data']->set_virtual( 1 ))
- place the order
- Check the order in orders listing : Total amount is correct (only item price counted, no shipping)
- Review the order : A shipping line appear, but not counted in the total.
- Review the order : Change order statue to "complete".
- Review the order : After order edit, The shipping line get saved, and added to the total.

**Expected behavior**
Order details page : Since product been set virtual during the order, it should stay virtual, and no shipping should be lately added to the order. So virtual attribute shouldn't be loaded from the original product, but from order > product.

Thanks!

**Comment by ObliviousHarmony** [comment]
Hello,

Are you saving the product after changing the virtual flag? To be clear as well, this will update the _actual_ product and affect all future orders made for that product.

**Comment by TheGranadilla** [comment]
Hi, thanks for your answer !
No, i'm not saving the product. I'm just changing it's virtual flag in the cart :

```
add_action( 'woocommerce_before_calculate_totals', 'set_custom_price_and_flag', 20, 1 );
function set_custom_price_and_flag( $cart ) {
    if ( is_admin() && ! defined( 'DOING_AJAX' ) )
        return;

    if ( did_action( 'woocommerce_before_calculate_totals' ) >= 2 )
        return;


    foreach ( $cart->get_cart() as $cart_item_key => $cart_item ){
        if( isset($cart_item['version'])) {
        $cart_item['data']->set_price( '2.90' );
        $cart_item['data']->set_sold_individually( 1 );
	$cart_item['data']->set_virtual( 1 );
	 }
}
```

It's working fine... Except if the order is updated from the admin order review page.
Changing order status from orders lists (quick action buttons) works fine and don't add the shipping.

**Comment by ObliviousHarmony** [comment]
I am so sorry for the delay @TheGranadilla,

The reason for this is that the `$cart_item['data']` that you're accessing is just the underlying `WC_Product` for the `WC_Order_item_Product` class. When you make a change to this you're making a change to the global product. You could make this work by using `$cart_item['data']->save()` but it would apply globally as well.

I might alternatively suggest using `woocommerce_checkout_create_order_shipping_item` action to zero out the shipping fee. You would still have the line item but you could set it to 0. You could also use the `woocommerce_checkout_create_order` action to alter the order object before it gets saved and remove the line item altogether.

**Comment by adrienthiery** [comment]
Hi @ObliviousHarmony ,
I just saw you recommended to use the `woocommerce_checkout_create_order` hook to alter the order object.
I have been trying for a while to do this, but I don't manage to do it.
I update the order in my hooked function, but it never updates the order 🤔 

Any hints to help me out?
Thanks a whole lot in advance

**Comment by abhishek-pokhriyal** [comment]
> but it never updates the order

are you doing `$order->save()` at the end?

**Comment by adrienthiery** [comment]
I did, yes, with no avail.
