### ISSUE TITLE
Let customize woocommerce-input-wrapper

### ISSUE THREAD

**Issue by caarek** [woocommerce/woocommerce#26521]
**Is your feature request related to a problem? Please describe.**
I create new wordpress theme which support woocommerce with customized templates. The problem occurred when I tried to customize checkout fields (form-billing.php). I use "woocommerce_form_field" function which add additional span with woocommerce-input-wrapper class between label and input. I need to move label next to input or remove completely this span, because it's breaking my form.
I saw a lot of similar questions/problems on stackoverflow and unfortunately I didn't find a good answer. It looks like this problem have to be resolved in woocommerce.

**Describe the solution you'd like**
I think there are two possible solutions for this.
1. Create additional option in "woocommerce_checkout_fields" filter for example "input_wrapper" which let you remove/hide completely this span wrapper for each fields.
2. If span input-wrapper is necessary I think label could be move next to input ( under span ) or add additional option as above ex. "label_in_wrapper".

**Describe alternatives you've considered**
I considered to remove this span with javascript, or just create form without "woocommerce_form_field" function.

**Additional context**
What actually fields looks like
![image](https://user-images.githubusercontent.com/22256709/82024680-6f00c580-9690-11ea-9714-4cc0f08e4328.png)

First solution
![image](https://user-images.githubusercontent.com/22256709/82024863-bd15c900-9690-11ea-9175-48dda285b828.png)

Second solution
![image](https://user-images.githubusercontent.com/22256709/82024821-a8d1cc00-9690-11ea-8b4d-bb8a9c6b3777.png)

**Comment by catchmareck** [comment]
@tammullen could you please take a look at this?

I also encounter this issue and couldn't find a good solution. I have to create dirty hacks as @caarek described: modify the form using JS - which is causing the form to "shake" (JS is firing with a delay so at first, the form looks bad for me, and after JS is loaded it gets fixed).

Is there any better solution?

**Comment by vedanshujain** [comment]
We already have a filter to support these kinds of modifications: `woocommerce_form_field` (this filter has the same name as the function). 

Assuming that you are familiar with [WordPress filters](https://developer.wordpress.org/plugins/hooks/filters/), this will allow you to modify any and all content of the field container (`p` tag with class `form-row`).

See the definition of this filter here: https://github.com/woocommerce/woocommerce/blob/master/includes/wc-template-functions.php#L2837

I am closing this issue, but feel free to write back if this does not solve your use case and we can discuss further.
