### ISSUE TITLE
if statement never meet in get_order_total()

### ISSUE THREAD

**Issue by adamradocz** [woocommerce/woocommerce#26534]
https://github.com/woocommerce/woocommerce/blob/8b0d4ef050fad20a96b0438b2050525fd9e38365/includes/abstracts/abstract-wc-payment-gateway.php#L263

$order_id gets an absint value, so the first part of the if statement never meet.

**Comment by lkraav** [comment]
I wonder if something like `phpstan` would catch these.

**Comment by adamradocz** [comment]
Sorry, I misread the statement... :)
