### ISSUE TITLE
Shipping Calculator Country select input doesn't display "Select a country..." as default option.

### ISSUE THREAD

**Issue by jeffreyscottfrench** [woocommerce/woocommerce#26540]
**Describe the bug**
templates/shipping-calculator.php - Shipping Calculator Country select input doesn't display "Select a country..." as default option

**To Reproduce**
1. Go to 'any woocommerce install'
2. Click on 'calculate shipping on the cart page'
3. Scroll down to 'country field select box'

**Screenshots**

**Expected behavior**
Expected to see prompt option displayed to select a country from the select box input, did not see it, though the option is hardcoded into the shipping-calculator.php file.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WP 5.4.1
```

WordPress address (URL): |   | //localhost:8001
-- | -- | --
Site address (URL): |   | //localhost:8001
WooCommerce version: |   | 4.1.0
WooCommerce REST API package: |   | 1.0.7 /var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-rest-api
WooCommerce Blocks package: |   | 2.5.16 /var/www/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/
Action Scheduler package: |   | 3.1.5 /var/www/html/wp-content/plugins/woocommerce/packages/action-scheduler
WooCommerce Admin package: |   | 1.1.1 /var/www/html/wp-content/plugins/woocommerce-admin
Log directory writable: |   | /var/www/html/wp-content/uploads/wc-logs/
WordPress version: |   | 5.4.1
WordPress multisite: |   | –
WordPress memory limit: |   | 256 MB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_US
External object cache: |   | –


```
</details>

**Comment by tammullen** [comment]
Hi @jeffreyscottfrench 

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/26435. 
We are closing your issue in favor of the previously submitted. 
Please continue sharing your feedback there if needed.

**Comment by jeffreyscottfrench** [comment]
Ok - I have commented there regarding the shipping-calculator.php template as well, though I think this is a separate issue as there are two files that need to be corrected for both to be resolved:

templates/cart/shipping-calculator.php   --  line 31
includes/wc-template-functions.php   --  line 2706

Setting the option element's value attribute to "default" in both instances is necessary.
