### ISSUE TITLE
If manage_woocommerce is removed from a Shop Manager role the WooCommerce menu item appears with Customers/Dashboard sub menu items

### ISSUE THREAD

**Issue by ninetyninew** [woocommerce/woocommerce#26547]
**Describe the bug**
If you remove the manage_woocommerce capability from a shop manager (as you want shop managers not to alter WooCommerce settings) then sub menu items such as Coupons, Orders, etc are split out into parent menu items - great. However we've just noticed that recently doing this leaves the WooCommerce parent menu item visible with only Customers and Dashboard as sub menu items. Dashboard is the same link to the dashboard you get via the parent Analytics menu so is probably not needed here and IMO in this scenario the new Customers sub menu should become a parent menu item.

**To Reproduce**
1. remove_cap manage_woocommerce from a shop manager
2. Login to the dashboard as a shop manager
3. You'll see the WooCommerce menu and 2 sub menu items that IMO should not be there

**Screenshots**
![Screenshot from 2020-05-19 14-20-08](https://user-images.githubusercontent.com/56840277/82331330-e198da80-99db-11ea-9004-7b3970a275c3.png)

**Expected behavior**
In this scenario make Customers sub menu item a parent menu item, remove the dashboard submenu (as already in Analytics)

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment]
Hi @ninetyninew ,

Thank you for taking the time reporting this bug, we really appreciate your help. I can reproduce it on my end.

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by ninetyninew** [comment]
Thanks - I did notice later that the Dashboard under the WooCommerce menu item is actually different to the Analytics home as I assumed earlier, therefore it maybe that needs to be it's own parent menu item too like Customers. But then WordPress already has a top level 'Dashboard' menu item so maybe a WooCommerce sub menu of that... not sure?
