### ISSUE TITLE
Shipping rate is hidden when cost=$0 causing confusing UI 

### ISSUE THREAD

**Issue by j111q** [woocommerce/woocommerce#26544]
**Describe the bug**
When the shipping cost = $0, the shipping rate is hidden.

This is basically fine and very avoidable if you are only using the core WooCommerce product without shipping plugins, because you could just rename the shipping method label as 'Free shipping' or '10-day delivery (Free)' or whatever you want.
But with certain shipping plugins where you are unable to easily rename the shipping method label, you can get some unexpected and confusing UI.

For example, when using the Distance Rate plugin, this is what the customer in the cart will see:

![image (1)](https://user-images.githubusercontent.com/65582817/82307235-a48c1280-99f2-11ea-807f-5bdbf6a43067.png)

**Expected behavior**
I would expect this instead:

![Screenshot 2020-05-19 at 5 24 05 PM](https://user-images.githubusercontent.com/65582817/82309318-912e7680-99f5-11ea-836f-aa0a2668c5a6.png)

**To Reproduce**
1. Go to Settings > Shipping > Shipping zones
2. Click on 'Add shipping method' > 'Flat rate'
3. Edit the Flat rate to have $0
4. Go to your cart and see that the $0 does not appear.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.

- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).

- [x] I can reproduce this bug consistently using the steps above.

**Additional notes:**
I brought this up as a potential area of improvement for the Distance Rate plugin, rather than for WooCommerce core. But @mikkamp kindly chimed in to point out that this would be a better fix directly in core WooCommerce, rather than having every shipping extension override it, which I would agree makes sense. Slack thread is here: p1589862151375500-slack-extendables-support

**Comment by rrennick** [comment]
Note: the shipping amount is displayed in the checkout block

<img width="421" alt="Screenshot 2023-07-11 at 2 33 17 PM" src="https://github.com/woocommerce/woocommerce/assets/343847/66551a14-8fd3-4f6e-9c2f-4d7522358f1a">

**Comment by pmcpinto** [comment]
Hey Jill, 

Thank you for taking the time to share this idea. We appreciate your help. Our team is currently focused on the Cart and Checkout blocks, and the shipping amount is displayed in the experience. 

We'll close the issue, as it doesn't fit our current priorities. We'll revisit the list of suggestions like this one once our priorities are updated.
