### ISSUE TITLE
Tooltips flash when hovering over the bottom of the help icon

### ISSUE THREAD

**Issue by superdav42** [woocommerce/woocommerce#26555]
**Describe the bug**
When hovering over any help icon which shows a tooltip the tooltip can start flashing if the cursor is at the bottom of the help icon. Happens most frequently with Firefox but can happen in chrome too.
This is happening because the tooltip box is partially covering the help icon so when the tooltip appears the cursor is no longer hovering over the icon so the tooltip is closed but then the cursor is again hovering over the icon so the tool tip is show and then it all begins again.

**To Reproduce**
1. Go to WooCommerce Settings page with a help icon
2. Hover over the bottom part of the icon
3. See flashing tooltip.

**Screenshots**
![ezgif com-optimize](https://user-images.githubusercontent.com/1534605/82371609-b6ac8780-99d7-11ea-8f16-b2eafa23daeb.gif)

**Expected behavior**
Tooltip to remain visible until the cursor moves out of the icon or the tooltip.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Doesn't really matter I've been consistently experiencing this bug since I started using WC at 3.4

**Comment by juliaamosova** [comment]
Hi @superdav42, 

Thanks for submitting the issue and a fix 🙌 . Marking your PR as `needs review`.
