### ISSUE TITLE
The country states for the Philippines needs to be updated

### ISSUE THREAD

**Issue by benedictte** [woocommerce/woocommerce#26564]
I noticed that a few of the current Philippine country/state definitions do not follow the ISO standards.

This is the mapping in WooCommerce:
'DAC' => __( 'Davao Occidental', 'woocommerce' ),
'SIQ' => __( 'Siquijor', 'woocommerce' ),

Based on ISO it should be:

PH-DVO* | Davao Occidental
PH-SIG* | Siquijor

You may refer to this:
https://www.iso.org/obp/ui/#iso:code:3166:PH

**Comment by tammullen** [comment]
Hi @benedictte 

Thank you for raising this issue.

We no longer use ISO, we instead use CLDR (details here https://github.com/woocommerce/woocommerce/pull/24564).

These are the CLDR details for Philippines
https://github.com/unicode-org/cldr/blob/release-37/common/subdivisions/en.xml#L3991

I'm going to close this issue as I don't believe any further action is required. Please feel free to comment on it in case we missed something.

**Comment by benedictte** [comment]
Thank you for the clarification.
