### ISSUE TITLE
[GlobalStep - 4.2 RC1]: Error in PHP tab of Query monitor is seen upon manually uploading tax rate CSV file

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#26574]
**Environment:**
Windows 10- Google Chrome (Version 81.0.4044.138)
Mac Mojave -10.14.6 -Safari(v13.0.5 )

**Steps to Reproduce:**
1. Create a site using Ninja tool.
2. Install all the plugins.
3. Click on "Run the Setup wizard".
4. Complete the setup wizard and go to WooCommerce Dashboard.
5. Click on "Setup Tax".
6. Import tax manually.
7. Click on import button.
8. Upload a CSV file.
9. Observe that in query monitor PHP Notice is displayed.

**Actual Result:**
Error in PHP tab of Query monitor is seen upon manually uploading tax rate CSV file

**Expected Result:**
No error message should be displayed and user should be able to upload CSV file.

![#26574](https://user-images.githubusercontent.com/41110392/82571480-a4317a00-9ba0-11ea-9449-7ee00e03c2b9.jpeg)

**Comment by tammullen** [comment]
Thanks for opening this issue @gglobalstep! I created an issue on your behalf for this in the Mailchimp for WooCommerce repository  https://github.com/mailchimp/mc-woocommerce/issues/655

Closing this issue for now.
