### ISSUE TITLE
Wrong product price calculation

### ISSUE THREAD

**Issue by Holu8** [woocommerce/woocommerce#26571]
**Describe the bug**
According to [https://docs.woocommerce.com/document/setting-up-taxes-in-woocommerce/](url):
> “Yes, I will enter prices inclusive of tax” means that all catalog prices are input using your store’s base tax rate.
> For example, in the UK you would input prices inclusive of the 20% tax rate e.g. You enter a product price of £9.99 that includes £1.67 tax. A customer in the UK would pay £9.99 as defined, and a customer in the US would only pay £8.32.

This behavior is wrong. If you enter price of £9.99, it correctly includes £1.67 tax. However if you have for other countries set tax to be 0, it should have same final price (in our case £9.99). That's how you expect "price inclusive of tax" to work (same price including tax for all countries - the country you ship/bill (according to your settings) to tax), so in our example customer should still pay the same amount no matter where he ships/bills the product (and only substract from the price the right tax).

Another example (not really common but can happen with this wrong calculation used in Woo):
You have shop based in UK (where is 20%) and sell to US with tax 30%. For UK, you will sell for £100 (inclusive tax), but for US the final price will be £108,3 (it calculates the price of the product - tax in the shops homecountry + the tax (30%)). 
In our example it is £100/1,2*1,3 = £108,3 (in order details it displays that the "total" for the product  is £83,3 and the tax (which is labeled incorrectly 20%!) to be £25,00. That's just wrong.

**Expected behavior:**
Expected behavior is that the product price is fixed and doesn't change no matter what tax is used (for inclusive).

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

I consider this to be critical bug. 

Thank you for response.

**Comment by tammullen** [comment]
Hi @Holu8 

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. 

> If you enter price of £9.99, it correctly includes £1.67 tax. However if you have for other countries set tax to be 0, it should have same final price (in our case £9.99). 

![Screenshot_2020-05-21_at_14_29_51](https://user-images.githubusercontent.com/24649833/82564653-096d7700-9b71-11ea-9c54-c1bb3769f80d.png)
I have set my store to be based in the UK

![Screenshot 2020-05-21 at 14 30 08](https://user-images.githubusercontent.com/24649833/82564669-0ecac180-9b71-11ea-91f9-632c1c0b6aba.png)
I have chosen to enter prices inclusive of tax 

![Screenshot 2020-05-21 at 14 33 42](https://user-images.githubusercontent.com/24649833/82564684-15593900-9b71-11ea-8d9d-0be4cd369af7.png)
I have created a tax rate of 20% for the UK

From our documentation https://docs.woocommerce.com/document/setting-up-taxes-in-woocommerce/#section-3
> “Yes, I will enter prices inclusive of tax” means that all catalog prices are input using your store’s base tax rate.

Therefore in this instance as I have a UK based store and a UK tax rate of 20% I will enter my prices inclusive of the UK 20% tax rate
![Screenshot 2020-05-21 at 14 32 58](https://user-images.githubusercontent.com/24649833/82564906-7aad2a00-9b71-11ea-8b30-cca6a34794c9.png)
In this example I have set a product price of £10 inc UK Vat.

![Screenshot_2020-05-21_at_14_32_50](https://user-images.githubusercontent.com/24649833/82564970-91538100-9b71-11ea-80b7-4c77817e3a65.png)
This is displayed correctly in the checkout for a UK address

![Screenshot_2020-05-21_at_14_34_08](https://user-images.githubusercontent.com/24649833/82565241-fa3af900-9b71-11ea-9eb1-6683b40132ed.png)
If we try a United States address it would use my other tax rate of 0%.

If you don't want this behaviour have a look at https://github.com/woocommerce/woocommerce/wiki/How-Taxes-Work-in-WooCommerce#prices-including-tax---experimental-behavior
Where we have filter you can use  to charge the same amount everywhere and absorb the differences in taxes.

>You have shop based in UK (where is 20%) and sell to US with tax 30%. For UK, you will sell for £100 (inclusive tax), but for US the final price will be £108,3 (it calculates the price of the product - tax in the shops homecountry + the tax (30%)).
In our example it is £100/1,2*1,3 = £108,3 (in order details it displays that the "total" for the product is £83,3 and the tax (which is labeled incorrectly 20%!) to be £25,00. That's just wrong.

![Screenshot 2020-05-21 at 14 35 23](https://user-images.githubusercontent.com/24649833/82565435-556ceb80-9b72-11ea-8151-975b4eb964de.png)
To try this out I added a 30% rate for the United States.

![Screenshot_2020-05-21_at_14_35_56](https://user-images.githubusercontent.com/24649833/82565471-64539e00-9b72-11ea-865e-c0b04fc610e4.png)
When I set my billing location to United States I am seeing the correct rate applied.

> the tax (which is labeled incorrectly 20%!) 

Can you provide more details of which label you are referring to.

If I am missing anything here please let us know.

If you confirm a bug, please provide us with clear steps to reproduce it as well as all the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue.

**Comment by Holu8** [comment]
I am sorry about not following template. I thought linking to your docs was enough to explain. The provided snippet works great and is exactly, what should be considered as "inclusive tax". Thank you for that.

> Can you provide more details of which label you are referring to.
Actually this was misunderstanding from my side. Everything works as intended.

Thank you very much once again, you can close this issue.
