### ISSUE TITLE
Add Order Item validation is add HTML to alert and check code insted of message.

### ISSUE THREAD

**Issue by mariovalney** [woocommerce/woocommerce#26588]
**Describe the bug**

The **woocommerce_ajax_add_order_item_validation** filter  was changed on [b9bb4a7c6](https://github.com/woocommerce/woocommerce/commit/b9bb4a7c6a55c04e6c177799b652aee996d969f8).

This added one problem: there is HTML on error message what is a problem as it's just "alerted".
And a not-intuitive requiremente to "code" on WP_Error even only printind the "message".

_About the second item, I'm not sure is a WooCommerce requirement to have code on WP_Errors like commit message is "This matches the pattern used elsewhere in WooCommerce..."_

```
add_action( 'woocommerce_ajax_add_order_item_validation', 'just_a_snipet_woocommerce_ajax_add_order_item_validation', 99, 4 );

function just_a_snipet_woocommerce_ajax_add_order_item_validation( $error, $product, $order, $qty ) {
    $error->add( '', 'There is HTML on alert.' ) );
    return $error;
}
```

**To Reproduce**
1. Add the snippet above.
2. Try to add a product on Order edit page.
3. See the alert.

**Screenshots**
https://i.imgur.com/gcVV4Vt.png

**Expected behavior**
Not print HTML.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment]
Closed by #26589
