### ISSUE TITLE
Adding an item to a newly created order in the Admin panel without saving the order results in stock being reduced that is unrecoverable.

### ISSUE THREAD

**Issue by jhartsoch** [woocommerce/woocommerce#26607]
**Describe the bug**
Adding an item to a newly created order in the Admin panel without saving the order results in stock being reduced that is unrecoverable.  Additionally, add_order_item() in class-wc-ajax DOES NOT respect the new **woocommerce_prevent_adjust_line_item_product_stock** filter. and is DIRECTLY reducing stock in all cases creating both problems.

**Steps to reproduce**
1. Orders-Add Order
2. Add an item
3. DON'T save the order
4. Notice the order is not listed, but stock on the item HAS been reduced and is never recovered.. See error

**Expected behavior**
Adding items to a newly created order still in 'auto-draft' status should NOT reduce stock until that order is actually saved/created.  The Ajax handler for adding items is currently reducing stock directly in this case.  The handler also needs to respect the new **woocommerce_prevent_adjust_line_item_product_stock**

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

WordPress address (URL): https://www.fairhavenhealth.com
Site address (URL): https://www.fairhavenhealth.com
WC Version: 4.1.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.5
WC Admin Version: ✔ 1.1.1
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 4 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.2.30-1+0~20200419.40+debian8~1.gbpb1b799
PHP Post Max Size: 1 GB
PHP Time Limit: 0
PHP Max Input Vars: 10000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.6.47-87.0-log
Max Upload Size: 1 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.1.0
WC Database Prefix: wp_
Total Database Size: 4576.58MB
Database Data Size: 2779.08MB
Database Index Size: 1797.50MB
wp_woocommerce_sessions: Data: 4.02MB + Index: 1.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_items: Data: 32.58MB + Index: 11.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 288.75MB + Index: 129.27MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 27.56MB + Index: 20.16MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 19.55MB + Index: 14.27MB + Engine InnoDB
wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_alm: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 10.52MB + Index: 10.02MB + Engine InnoDB
wp_comments: Data: 352.86MB + Index: 273.03MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 4.52MB + Index: 10.73MB + Engine InnoDB
wp_followup_customer_carts: Data: 33.52MB + Index: 5.81MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 4.52MB + Index: 3.45MB + Engine InnoDB
wp_followup_email_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 22.09MB + Index: 12.55MB + Engine InnoDB
wp_followup_email_orders: Data: 136.30MB + Index: 31.75MB + Engine InnoDB
wp_followup_email_order_coupons: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_tracking: Data: 7.52MB + Index: 9.58MB + Engine InnoDB
wp_followup_followup_history: Data: 236.64MB + Index: 4.55MB + Engine InnoDB
wp_followup_order_categories: Data: 9.52MB + Index: 10.98MB + Engine InnoDB
wp_followup_order_items: Data: 5.52MB + Index: 9.31MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 13.14MB + Index: 6.11MB + Engine InnoDB
wp_postmeta: Data: 1049.97MB + Index: 880.52MB + Engine InnoDB
wp_posts: Data: 141.52MB + Index: 58.31MB + Engine InnoDB
wp_pum_subscribers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_redirection_404: Data: 2.02MB + Index: 8.06MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 3.02MB + Index: 7.08MB + Engine InnoDB
wp_responsive_menu: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sbi_instagram_feeds_posts: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_sbi_instagram_posts: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_shareasale_wc_tracker_datafeeds: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_shareasale_wc_tracker_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_social_users: Data: 0.25MB + Index: 0.09MB + Engine InnoDB
wp_taxjar_record_queue: Data: 5.50MB + Index: 2.52MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 2.08MB + Index: 1.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 201.70MB + Index: 194.41MB + Engine InnoDB
wp_users: Data: 10.52MB + Index: 14.53MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 12.52MB + Index: 10.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 35.56MB + Index: 29.06MB + Engine InnoDB
wp_wc_order_stats: Data: 20.55MB + Index: 15.55MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.28MB + Index: 0.27MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfBlockedIPLog: Data: 1.02MB + Index: 0.00MB + Engine InnoDB
wp_wfBlocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfConfig: Data: 2.25MB + Index: 0.00MB + Engine InnoDB
wp_wfCrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfFileChanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfFileMods: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
wp_wfHits: Data: 10.02MB + Index: 2.72MB + Engine InnoDB
wp_wfHoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfKnownFileList: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wfLiveTrafficHuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfLocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfLogins: Data: 3.52MB + Index: 1.75MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfNotifications: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wfPendingIssues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfReverseCache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfSNIPCache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfStatus: Data: 0.17MB + Index: 0.13MB + Engine InnoDB
wp_wfTrafficRates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 7.52MB + Index: 2.25MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.09MB + Index: 0.16MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 1.14MB + Index: 0.16MB + Engine InnoDB
wp_yoast_seo_meta: Data: 45.58MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

advanced_ads: 5
attachment: 5810
blocks: 3
captainform_post: 1
custom_css: 2
customize_changeset: 2
follow_up_email: 17
mc4wp-form: 2
nav_menu_item: 164
nelioab_local_exp: 1
oembed_cache: 140
page: 58
popup: 2
popup_theme: 6
post: 327
product: 153
product_variation: 6
revision: 954
saswp: 1
shop_coupon: 306
shop_order: 202883
shop_order_refund: 2124
ufaq: 2
wc_order_status: 11
wccpf: 1
wpcf7_contact_form: 4
ywar_reviews: 8

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (68) ###

ManageWP - Worker: by GoDaddy – 4.9.6
Advanced Ads: by Thomas Maier
Advanced Ads GmbH – 1.17.11

Advanced noCaptcha & invisible Captcha: by Shamim Hasan – 5.6 – Installed version not tested with active version of WooCommerce 4.1.0
Akismet Anti-Spam: by Automattic – 4.1.5
Application Passwords: by George Stephanis – 0.1.1
Better Font Awesome: by Mickey Kay – 1.7.1
Classic Editor: by WordPress Contributors – 1.5
Contact Form 7: by Takayuki Miyoshi – 5.1.7
WooCommerce Continue Shopping: by HappyKite – 1.4.2 – Installed version not tested with active version of WooCommerce 4.1.0
GDPR Cookie Consent: by WebToffee – 1.8.7
Custom Permalinks: by Sami Ahmed Siddiqui – 1.5.1
Display Posts: by Bill Erickson – 3.0.2
Google Tag Manager for Wordpress: by Thomas Geiger – 1.11.4 – Installed version not tested with active version of WooCommerce 4.1.0
Facebook for WooCommerce: by Facebook – 1.11.2
FH StoneEdge Cart Integrator: by Jacob Hartsoch – 3.33 – Installed version not tested with active version of WooCommerce 4.1.0
IgniteWoo Updater: by IgniteWoo.com – 2.1.11
Imagify: by WP Media – 1.9.9
Instagram Feed Pro Personal: by Smash Balloon – 5.6
Collapse-O-Matic: by twinpictures
baden03 – 1.7.12

Lock User Account: by babaTechs – 1.0.2
Mailgun: by Mailgun – 1.7.1
WooCommerce Table Rate Shipping Plus: by mangohour – 1.9.2 – Installed version not tested with active version of WooCommerce 4.1.0
Minimum Order Amount for Woocommerce: by Dario Curasì – 1.5.0 – Installed version not tested with active version of WooCommerce 4.1.0
Multifile Upload Field for Contact Form 7: by Spyros Vlachopoulos – 1.0.1
Nextend Social Login: by Nextendweb – 3.0.24
Nextend Social Login Pro Addon: by Nextendweb – 3.0.23
Popup Maker: by Popup Maker – 1.10.1
Redirection: by John Godley – 4.7.1
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.3
Lazy Load by WP Rocket: by WP Rocket – 2.3.2
ShareASale WooCommerce Tracker: by ShareASale.com
Inc. – 1.4.5 – Installed version not tested with active version of WooCommerce 4.1.0

Simple Tooltips: by Justin Saad – 2.1.3
Smart SEO Data CSV Import/Export: by Freddie Lore – 6.0.3
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 3.1.0 – Installed version not tested with active version of WooCommerce 4.1.0
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.5.7.2
TWB Woocommerce Reviews: by Abu Bakar – 1.7.3 – Installed version not tested with active version of WooCommerce 4.1.0
UberMenu 3 - The Ultimate WordPress Mega Menu: by Chris Mavricos
SevenSpark – 3.6.1

WordPress Users & WooCommerce Customers Import Export(BASIC): by WebToffee – 1.4.1 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce Waitlist: by XootiX – 1.4 – Installed version not tested with active version of WooCommerce 4.1.0
WC Duplicate Order: by Jamie Gill – 1.7 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce Order Search Admin powered by Algolia: by Raymond Rutjes – 1.13.0 – Installed version not tested with active version of WooCommerce 4.1.0
White Label CMS: by www.videousermanuals.com – 2.2
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.4.2 – Installed version not tested with active version of WooCommerce 4.1.0
Advanced Order Export For WooCommerce: by AlgolPlus – 3.1.4 – Installed version not tested with active version of WooCommerce 4.1.0
Product Feed PRO for WooCommerce: by AdTribes.io – 8.1.6 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce Extended Coupon Features FREE: by Soft79 – 3.1.4 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.8.0
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.19 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce Amazon Pay: by WooCommerce – 1.12.2
WooCommerce First Data Payeezy Gateway: by SkyVerge – 4.7.2
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.21 (update to version 2.0.1 is available) – Installed version not tested with active version of WooCommerce 4.1.0
Klaviyo for WooCommerce V2: by Klaviyo
Inc. – 2.0.8 – Installed version not tested with active version of WooCommerce 4.1.0

WooCommerce Min/Max Quantities: by WooCommerce – 2.4.16 (update to version 2.4.17 is available)
WooCommerce Order Status Manager: by SkyVerge – 1.11.7 (update to version 1.11.8 is available)
WooCommerce Google Product Feed: by Ademti Software Ltd. – 8.1.1
WooCommerce Product Reviews Pro: by SkyVerge – 1.15.4
WooCommerce Shipment Tracking: by WooCommerce – 1.6.22
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.36
WooCommerce Shop as Customer: by cxThemes – 2.16 – Installed version not tested with active version of WooCommerce 4.1.0
WooCommerce: by Automattic – 4.1.0 (update to version 4.1.1 is available)
Wordfence Security: by Wordfence – 7.4.7
Yoast SEO: by Team Yoast – 14.0.4
WP Change Default From Email: by Subodh Ghulaxe – 1.1.2
WP Crontrol: by John Blackbourn & crontributors – 1.8.3
WP Meta and Date Remover: by Prasad Kirpekar – 1.7.9
WP Rocket | No CORS for Fonts: by WP Rocket Support Team –
WP Rocket: by WP Media – 3.5.4
Custom Product Tabs for WooCommerce: by YIKES
Inc. – 1.7.1 – Installed version not tested with active version of WooCommerce 4.1.0

### Inactive Plugins (1) ###

Post Meta Inspector: by Daniel Bachhuber
Automattic – 1.1.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

ManageWP - Worker Loader: by GoDaddy –

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: simple (simple)
grouped (grouped)
variable (variable)
external (external)

Taxonomies: Product Visibility: exclude-from-search (exclude-from-search)
exclude-from-catalog (exclude-from-catalog)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #90 - /shop/
Cart: #91 - /cart/
Checkout: #92 - /checkout/
My account: #93 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.11.3
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome-child/woocommerce/cart/cart.php version 3.5.0 is out of date. The core version is 3.8.0
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome-child/woocommerce/emails/customer-processing-order.php version 3.5.4 is out of date. The core version is 3.7.0
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

Outdated Templates: ❌
					
					
						Learn how to update

### WooCommerce Google Product Feed fields ###

Product description: Variation description only
fallback to main description (short preferred).

Availability: Defaults to "in stock".
Brand: Defaults to "Fairhaven Health". Pre-populates from pa_brand taxonomy.
Google Product Category: Defaults to "525".
Global Trade Item Number (GTIN): 

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send item_group_id: Enabled

### Payeezy Gateway Credit Card ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off

### Action Scheduler ###

Complete: 79,825
Oldest: 2020-04-25 09:26:37 -0700
Newest: 2020-05-26 09:23:56 -0700

Failed: 5,673
Oldest: 2018-03-01 10:43:44 -0800
Newest: 2020-01-21 09:47:36 -0800

Pending: 7
Oldest: 2020-05-26 09:29:21 -0700
Newest: 2028-12-15 15:47:16 -0800

`

**Comment by juliaamosova** [comment]
Hi @jhartsoch 

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

- I created a simple product with a stock of 100:

![pr1](https://user-images.githubusercontent.com/19143190/82935808-ac503780-9f5b-11ea-917a-26f03d8d2d40.jpg)

- Created a manual order without saving it and saw that the stock was reduced in the order notes:

![pr2](https://user-images.githubusercontent.com/19143190/82935824-b2461880-9f5b-11ea-99e3-1a428a77eae9.jpg)

- Navigated away (without saving the order) and made sure it was not created in the `All Orders` view:

![pe3](https://user-images.githubusercontent.com/19143190/82935885-c25df800-9f5b-11ea-8d46-a072e76fafb1.jpg)

- Navigated to the product and saw that the stock was indeed reduced without an order being created:

![pr4](https://user-images.githubusercontent.com/19143190/82935865-b96d2680-9f5b-11ea-8c19-8b2a5fd8d300.jpg)

Tested in WC 4.1.1 and WC 4.2 RC1. 

We’re going to solve this bug as soon as possible. Stay tuned for updates.

**Comment by jhartsoch** [comment]
> Hi @jhartsoch
> 
> Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end.
> 
> * I created a simple product with a stock of 100:
> 
> ![pr1](https://user-images.githubusercontent.com/19143190/82935808-ac503780-9f5b-11ea-917a-26f03d8d2d40.jpg)
> 
> * Created a manual order without saving it and saw that the stock was reduced in the order notes:
> 
> ![pr2](https://user-images.githubusercontent.com/19143190/82935824-b2461880-9f5b-11ea-99e3-1a428a77eae9.jpg)
> 
> * Navigated away (without saving the order) and made sure it was not created in the `All Orders` view:
> 
> ![pe3](https://user-images.githubusercontent.com/19143190/82935885-c25df800-9f5b-11ea-8d46-a072e76fafb1.jpg)
> 
> * Navigated to the product and saw that the stock was indeed reduced without an order being created:
> 
> ![pr4](https://user-images.githubusercontent.com/19143190/82935865-b96d2680-9f5b-11ea-8c19-8b2a5fd8d300.jpg)
> 
> Tested in WC 4.1.1 and WC 4.2 RC1.
> 
> We’re going to solve this bug as soon as possible. Stay tuned for updates.

Wow, that was quick!  *Note the related bug I mention regarding the ajax handler not calling the 'woocommerce_prevent_adjust_line_item_product_stock filter.   I temporarily solved both issues for my own purposes in class-wc-ajax.php around line 919:

				/* adding support for woocommerce_prevent_adjust_line_item_product_stock AND not adjusting stock for 'auto-draft' orders */
				if (  ($post_status != 'auto-draft') && $product->managing_stock() && !apply_filters( 'woocommerce_prevent_adjust_line_item_product_stock', false, $item, $qty ) ) {
					$new_stock               = wc_update_product_stock( $product, $qty, 'decrease' );
					$order_notes[ $item_id ] = $product->get_formatted_name() . ' &ndash; ' . ( $new_stock + $qty ) . '&rarr;' . $new_stock;
					$item->add_meta_data( '_reduced_stock', $qty, true );
					$item->save();
				}

**Comment by negapo** [comment]
Let me just add something that doesnt make sense

Do the following test:

- Create an order on the admin panel, leave the order status as "wc-pending", add an item (stock is reduced), save the order then cancel the order (stock is not returned).
- Create an order on the admin panel, change the order status to "wc-on-hold", add an item (stock is reduced), save the order then cancel the order (stock is returned).

WC-Pending was in earlier versions a status that didnt commit changes to stock so it wasn't marked as with the  '_reduced_stock', it still isn't, so the wc_maybe_reduce_stock_levels and the wc_maybe_increase_stock_levels dont work. This leaves the order for incorrect stock management when an order is created, items are added and reflected on stock levels, then the ordre is cancelled and the stock doesnt return to the system as expected. If the WC-Pending is to be a stock changing status then is should behave like one where all changes (additions, removals and a cancellation) reflect on the stock levels. 

The correct logic is really simple, if the items on an order changed stock then all changes in that order should commit to stock (additions, removals and a cancellation), and the contrary is also true.

**Comment by jhartsoch** [comment]
nice add @negapo.  I think the problem is the logic in the ajax add_order_item handler that reduces stock *doesn't* set the order's global stock_reduced flag.  I think all these issues stem from that function trying to manually reduce stock on a line item add instead of going through wc_maybe_reduce_stock_levels where that order level flag gets set. Just a thought

**Comment by negapo** [comment]
@jhartsoch i think you are right on the money, that's where the logic breaks, using that ajax call that doesn't properly flag the order.

(Just a side note, im seeing that your are using the same setup as the store that i own (WC with Flatsome and some plug-ins). We tried to build everything on top of WC but have faced a few challenge that you must have dealt also, stock management, order picking, etc. Would love to change ideas). Regards
