### ISSUE TITLE
Variation settings screen - some field values are partially blocked

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce#26606]
**Describe the bug**
Some of the setting values shown in the select dropdowns are partially blocked. 

**To Reproduce**
1. Go to a variable products page.
2. Click on `Variations`.
3. Expand a specific variation.
4. See the partially blocked values on the dropdowns.

**Screenshots**
![](https://d.pr/i/edIvJm+)

**Expected behavior**
I expect to see the selected value not blocked.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

Tested on 4.1 branch.

**Comment by juliaamosova** [comment]
Hi @roykho,

Thanks for raising this. However, I can't reproduce it in 4.1:

![var](https://user-images.githubusercontent.com/19143190/82925157-5d020b00-9f4b-11ea-853e-db8578099d34.jpg)

If working locally, could it be that you didn't build assets? That would be running the following commands before activating WooCommerce:

- `npm install`
- `composer install`
- `npm run build`

I am sure you know of these but I always like to double-check before diving further.

**Comment by roykho** [comment]
I didn't run it because I was under the impression Husky -> post merge process builds the files for you. So I am guessing it doesn't from your comment. Then this is a non issue.
