### ISSUE TITLE
missing translation for Arabic

### ISSUE THREAD

**Issue by ibraheemhsn** [woocommerce/woocommerce#26603]
**Is your feature request related to a problem? Please describe.**
Please have a look at the attached image, explaining that checkout page is not totally translated.
I see that woocommerce-ar.po is totally translated , including the sections in the attached image.
but the translation does not appear in the front end.

I used default woo theme (storefront) for test.

![Capture](https://user-images.githubusercontent.com/9101663/82892427-1830a100-9f58-11ea-9177-6447cd7b58c4.PNG)

**Comment by juliaamosova** [comment]
Hi @ibraheemhsn,

Thanks for raising the issue. However, I think the translations are working as expected in your case. Did you first have your site language in the default English language (or any other language initially) and later changed the language to Arabic? 

If this is the case, you'd need to manually translate the strings that were not translated by navigating to corresponding parts of WooCommerce. We wrote docs related to this case as well - please check [Why some strings on the Checkout page are not being translated?](https://docs.woocommerce.com/document/woocommerce-localization/#section-12) for more details. 

Let us know if you are still experiencing issues.

**Comment by ibraheemhsn** [comment]
OK, many thanks, this has fixed issue, some translation strings are managed by theme customizer.
