### ISSUE TITLE
Bug in the Order Update WebHook

### ISSUE THREAD

**Issue by negapo** [woocommerce/woocommerce#26612]
**Describe the bug**
If you have an active "Order updated" WebHook and you edit an order in the order admin panel the webhook is being fired without any of the changes reflected (the order data that is sent is the old data, before the update).

**To Reproduce**
Create an "Order updated" WebHook.
Open an existing order on the order admin panel, change any field like the billing "First Name", click "Update", analyze the webhook sent, it will not reflect the new changes.

**Screenshots**

**Expected behavior**
The update WebHooks should be a push notification of the update with the newly added modifications and not the data before the update.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): http://bean.pt/dev
Site address (URL): http://bean.pt/dev
WC Version: 4.1.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.1.3
Log Directory Writable: ✔
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: pt_PT
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.29 (Unix) mod_hive/6.27 OpenSSL/1.0.1e-fips mod_fastcgi/2.4.6
PHP Version: 7.1.33 - Recomendamos que utilize PHP 7.2 ou superior para melhor performance e segurança. Como actualizar a sua versão PHP
PHP Post Max Size: 32 MB
PHP Time Limit: 45
PHP Max Input Vars: 1000
cURL Version: 7.59.0
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.6.36-82.1-log
Max Upload Size: 24 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.1.1
WC Database Prefix: wp_
Tamanho total da base de dados: 3.47MB
Tamanho dos dados da base de dados: 2.06MB
Tamanho do índice da base de dados: 1.41MB
wp_woocommerce_sessions: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Dados: 0.02MB + Índice: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Dados: 0.02MB + Índice: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_woocommerce_log: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Dados: 0.02MB + Índice: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_commentmeta: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_comments: Dados: 0.02MB + Índice: 0.09MB + Engine InnoDB
wp_links: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_omgf_fonts: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_omgf_fonts_subsets: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_options: Dados: 1.16MB + Índice: 0.06MB + Engine InnoDB
wp_postmeta: Dados: 0.06MB + Índice: 0.03MB + Engine InnoDB
wp_posts: Dados: 0.02MB + Índice: 0.06MB + Engine InnoDB
wp_termmeta: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_terms: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_term_relationships: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_term_taxonomy: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_usermeta: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_users: Dados: 0.02MB + Índice: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Dados: 0.02MB + Índice: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_wc_download_log: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Dados: 0.02MB + Índice: 0.06MB + Engine InnoDB
wp_wc_order_stats: Dados: 0.02MB + Índice: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Dados: 0.02MB + Índice: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Dados: 0.02MB + Índice: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB
wp_wc_webhooks: Dados: 0.02MB + Índice: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 3
nav_menu_item: 1
page: 6
post: 1
product: 1
shop_order: 11

### Security ###

Secure connection (HTTPS): ❌
					A sua loja não está a usar HTTPS. Saiba mais sobre HTTPS e certificados SSL.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: por Automattic – 4.1.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Página da Loja: #7 - /loja/
Carrinho: #8 - /carrinho/
Finalizar compras: #9 - /finalizar-compra/
Minha conta: #10 - /minha-conta/
Termos e condições: ❌ Página não definida

### Theme ###

Name: Storefront
Version: 2.5.6
Author URL: https://woocommerce.com/
Child Theme: ❌ – Se estiver a modificar o tema do WooCommerce ou um tema principal que não construiu pessoalmente
recomendamos o uso de um tema dependente. Veja: Como criar um tema dependente

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Concluída: 32
Oldest: 2020-05-26 19:21:39 +0000
Newest: 2020-05-26 19:59:57 +0000

</details>

**Comment by negapo** [comment]
Hi, this may not be seen as important, but if you want Woocommerce to continue to grow you need an option to connect it to other things, and the webhooks are the only efficient way of doing it. The rest API is very complete but very inadequate for certain things because of its exhausting request/response logic. The webhook is the only thing that pushes info but its not well developed, at least it needs to be bug free.

**Comment by negapo** [comment]
Anyone? Please

**Comment by vedanshujain** [comment]
Hi, I tried reproducing the error but was not able to. On my install of WooCommerce 4.1.1, I added an `Order updated` webhook, opened an existing order and edited billing detail (first name) to trigger the webhook. I was able to see updated details in the webhook. Note that I was using WP REST API Integration V3 in the API version. 
Is this easily reproducible for you? Do you have any more detail that may help in debugging the issue?

**Comment by negapo** [comment]
@vedanshujain thanks for noticing the ticket. I initially thought it was easily reproducible but it isn't, i'm on a test installation, everything up to date, one product, one web hook. I start to create an order and then go to the admin panel and change some fields, update, check for the web hook data, and do it again. Whats happens is the following, in a non deterministic way, randomly:

Create the Order - WebHook fires with the proper data
Update a Billing Field - WebHook fires with the proper data
Update Another Field - WebHook DOESN'T FIRE
Update Another Field - WebHook fires with stale data, the data from the previous unsent webhook
Update Another Field - WebHook DOESN'T FIRE
Update Another Field - WebHook fires with the proper data, ignoring one update webhook
Update Another Field - WebHook DOESN'T FIRE
Update Another Field - WebHook fires twice, one with the first update and another, 5/6 seconds later, with the last update
Update Another Field - WebHook delays and fires 2/3 minutes after the update

And this continues, in a random way, very difficult to track whats happening, it could be something in my environment but that's improbable. Could you please try a series of updates @vedanshujain in the same order and see if the webhooks fire as expected? ty

**Comment by negapo** [comment]
Can anyone just test this and verify that there is no problem? I have extensively tested this and cannot get the expected behavior of the webhook being fired timely and with the proper data on every update. thanks

**Comment by Frisoni** [comment]
I may have the same problem.
In my flow, orders are created in On-Hold Status, then my payment gateway send a response confirming payment and order status is changed to Processing.
The difference between this two actions is less than 3 seconds.
I usually get only the second webhook fired (processing), but in some cases only on-hold is fired.
In this case, I have only one completed schedule action.

I'm thinking about a CRON issue, if previous schedule is pending, the next one overwrite it to run most updated one, which is ok not.

But if schedule is RUNNING, a new one can't be created and the updated info is missed.
Above is an example of time for a real order:
-> 15:00:45 -> Order created (changed to on-hold)
-> 15:00:45 -> Webhook Async Schedule (created)
-> 15:00:47 -> Webhook Async Schedule (started)
-> 15:00:48 -> Payment return (changed to processing)
-> 15:00:49 -> Webhook Async Schedule (completed)

Does this make any sense?

**Comment by negapo** [comment]
What im missing is a pattern, cannot find one, its all over the place in my case,
I can see cases where that happens, an update is ignored and i received the fresh data on the second one, i can see other cases when an update is ignored and i receive stale data, i can see cases with huge delays like 2/3 minutes.

Note, i'm using WP REST API Integration V3

**Comment by Frisoni** [comment]
You'll need to check further.
I checked some other orders with the same problem and found a pattern with Webhook and Action Scheduler.

Digging Woo code, I think the problem may be in this particular file:
woocommerce/includes/wc-webhook-functions.php

In function wc_webhook_process_delivery there is this code:
`		$next_scheduled_date = WC()->queue()->get_next( 'woocommerce_deliver_webhook_async', $queue_args, 'woocommerce-webhooks' );
		// Make webhooks unique - only schedule one webhook every 10 minutes to maintain backward compatibility with WP Cron behaviour seen in WC < 3.5.0.
		if ( is_null( $next_scheduled_date ) || $next_scheduled_date->getTimestamp() >= ( 600 + gmdate( 'U' ) ) ) {
			WC()->queue()->add( 'woocommerce_deliver_webhook_async', $queue_args, 'woocommerce-webhooks' );
		}`

I can't test debugging, but when queue()->get_next() is called, the arg_id is already running (but not completed) and return the schedule_data, avoidind to create a new queue with updated info from order.

There should be a way to check next schedule date of only created schedule, or if found one, delete it and create a new one, to avoid this problem.

**Comment by mouligreenlaw** [comment]
Also on 3084383-zen

**Comment by rickdroio** [comment]
Dears, do you have any feedback regarding this issue?

It's happening similar issue with me:
1 - order created as pending status >> hook fired
2- payment gateway response (less than 1 second)
3- order updated to processing status >> **hook not fired**

It is not happening 100% of cases, my guess it is when payment gateway responses is too fast.

Thanks

**Comment by ObliviousHarmony** [comment]
One of the fixes in the 4.4.0 release is #27067, which should resolve all of these sorts of race conditions by delaying the execution of the webhooks until after the request has completed.
