### ISSUE TITLE
Product: Changes to existing options with set_attribute() are not stored when calling save()

### ISSUE THREAD

**Issue by hannesdorn** [woocommerce/woocommerce#26627]
There is a product with an existing attribute 'external_url'.
I wanted to set a new value (option) for this attribute.

This does not work:
```
$oProduct = new WC_Product_Simple($iId);
$aAttributes = $oProduct->get_attributes('edit');
if (isset($aAttributes['external_url'])) {
    $oAttribute = $aAttributes['external_url'];
} else {
    $oAttribute = new WC_Product_Attribute();
}
$oAttribute->set_options(array('new value'));
$oProduct->set_attributes($aAttributes);
$oProduct->save();
```

The changes to the attribute are not stored if the attribute exists.

The problem is in wp-content\plugins\woocommerce\includes\abstracts\abstract-wc-data.php in protected function set_prop( $prop, $value ), which is called by public function set_attributes( $raw_attributes ) in wp-content\plugins\woocommerce\includes\abstracts\abstract-wc-product.php.

```
protected function set_prop( $prop, $value ) {
    if ( array_key_exists( $prop, $this->data ) ) {
        if ( true === $this->object_read ) {
            if ( $value !== $this->data[ $prop ] || array_key_exists( $prop, $this->changes ) ) {
                $this->changes[ $prop ] = $value;
            }
        } else {
            $this->data[ $prop ] = $value;
        }
    }
}
```

$value !== $this->data[ $prop ] results in false, because the reference both the same array with the same object references.

$oProduct->get_attributes('edit') returns an array with references to instances of WC_Product_Attribute.
If you change a value of the instance of WC_Product_Attribute, it changes the original value in $oProduct.

get_attributes should return clones of WC_Product_Attribute instead of references.

This works:

```
$oProduct = new WC_Product_Simple($iId);
$aAttributes = $oProduct->get_attributes('edit');
$oAttribute = new WC_Product_Attribute();
if (isset($aAttributes['external_url'])) {
    $oAttributeOld = $aAttributes['external_url'];
    $oAttribute->set_id($oAttributeOld->get_id());
    $oAttribute->set_name($oAttributeOld->get_name());
    $oAttribute->set_position($oAttributeOld->get_position());
    $oAttribute->set_visible($oAttributeOld->get_visible());
    $oAttribute->set_variation($oAttributeOld->get_variation());
} else {
    $oAttribute->set_id(0);
    $oAttribute->set_name('External URL');
    $oAttribute->set_position(0);
    $oAttribute->set_visible(true);
    $oAttribute->set_variation(false);
}
$oAttribute->set_options(array('new value'));
$aAttributes['external_url'] = $oAttribute;
$oProduct->set_attributes($aAttributes);
$oProduct->save();
```

**Comment by vedanshujain** [comment]
You are seeing this because Simple Product does not have `external_url` attribute URL by default, its set by external product class `WC_Product_External`. You can use it like so:

```php
	$product = new WC_Product_External( $iId );
	$product->set_product_url( 'https://woocommerce.com' );
	$product->save();


	$product->get_product_url();
```

If you wish to save a custom attribute on simple product instead, you would have to use metadata. See methods `add_meta` and `read_meta` in Datastore class. An example (but I won't recommend this approach, because the above approach is way simpler and 'correct'):
```php
	$data_store = WC_Data_Store::load( 'product' );
	$product = new WC_Product_Simple( $iId );
	$product->get_attributes();
	$meta = new stdClass();
	$meta->key = 'external_url';
	$meta->value = 'https://woocommerce.com';
	$data_store->add_meta( $product, $meta );


	$data_store->read_meta( $product );
```

I hope this answers your query, I am closing the issue, but feel free to comment back if you would to discuss more.

**Comment by hannesdorn** [comment]
Supi! Thanks!
