### ISSUE TITLE
Taxonomies Update Messages Not Consistent

### ISSUE THREAD

**Issue by corsonr** [woocommerce/woocommerce#26633]
**Is your feature request related to a problem? Please describe.**

When editing a `product_cat`, a `product_tag` or a product attribute, the messages are always the same:

![](https://d.pr/i/wNrCwd+)

![](https://d.pr/i/nhMlQV+)

**Describe the solution you'd like**

Using a message that matches the actual taxonomy label would make more sense:

![](https://d.pr/i/0HmkJl+)

![](https://d.pr/i/vliaPJ+)

**Describe alternatives you've considered**

I'm submitting a PR for that 😉

**Comment by juliaamosova** [comment]
Hi @corsonr 

Thanks for raising the issue - it makes sense to me to specify what item had been updated indeed. Thanks for your contribution as well. I marked your PR as `needs review`.
