### ISSUE TITLE
Size image are missed up

### ISSUE THREAD

**Issue by Stas0238** [woocommerce/woocommerce#26661]
Hello,

I had to make this new report as I didn't get any answer on my old one -> https://github.com/woocommerce/woocommerce/issues/26548.

Regards, Stas.

**Comment by tammullen** [comment]
Hi @Stas0238 ,
​
Thank you for reporting the issue and sorry for the delay in responding to the previous issue. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
