### ISSUE TITLE
Theme with uppercase folder name fails to activate during Setup Wizard

### ISSUE THREAD

**Issue by mpandzo** [woocommerce/woocommerce#26679]
**Describe the bug**
There is a problem in the "Choose a theme" step of the Setup Wizard.
If a theme has an uppercase letter in the folder name (e.g. Avada instead of avada), the Choose action fails with the message

```
"The requested theme `avada` could not be installed. Theme API call failed." 
```

**To Reproduce**
1. Activate WooCommerce on a clean install
2. Use the WooCommerce Setup Wizard 
3. Proceed to the Choose a theme step
4. Click Choose on a theme with an uppercase folder name, e.g. Avada
5. See error

**Screenshots**
![avada-error](https://user-images.githubusercontent.com/7498710/83618424-b6d98500-a58a-11ea-96be-0246dd052a79.png)

**Expected behavior**
A theme should be activated regardless of whether it's folder uses uppercase or lowercase letters since WordPress itself allows the use of both uppercase and lowercase letters in folder names.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Additional info**
I believe the problem lies within woocommerce\packages\woocommerce-admin\src\API\OnboardingThemes.php lines 89 to 95 where the theme slug is sanitized, and the theme parameter is transformed:

```
		$theme          = sanitize_title_with_dashes( $request['theme'] );
```

and

```
		$slug             = sanitize_key( $theme );
```

**WordPress Environment**
<details>
```
N/A
```
</details>

**Comment by tammullen** [comment]
Hi @mpandzo,

Thank you for reporting the issue. The on-boarding wizard is part of WooCommerce Admin which is being developed in another repository: https://github.com/woocommerce/woocommerce-admin/. 

This issue has been reported previously there https://github.com/woocommerce/woocommerce-admin/issues/4393. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.

**Comment by mpandzo** [comment]
Thank you @tammullen, sorry, googled and couldn't find an issue so created one. Will dig deeper next time.
