### ISSUE TITLE
4.2 Breaks working WooCommerce caused by redeclaring a variable

### ISSUE THREAD

**Issue by FirstWarden** [woocommerce/woocommerce#26688]
After upgrading to 4.2, a variable gets redeclared, causing a fatal error.

Haven't got the name of the variable written down, but in my case it happened in combination with the Mollie for Woocommerce plugin.

Downloaded 4.1.1, removed 4.2, installed 4.1.1 and deactivated my plugins, reactivated one by one, but still the fatal error remains.

Had to do a restore via my DirectAdmin.

Sorry for the lack of details, maybe others can confirm

**Comment by tammullen** [comment]
Hi @FirstWarden 

Thank you for submitting the issue. Unfortunately without more details we can’t fully evaluate this issue.

Any extra details you can provide can be of help. Was the error displayed on screen (and if so which screens?) or was it in your logs?

Please also have a look at the bug report template and provide us with any of the information you can including the system status report from **WooCommerce > System Status** in WordPress admin.

**Comment by FirstWarden** [comment]
Have staged my site to a sandbox with the original versions of plugins used, updated WC, but could not get the error triggered.

Can't reproduce. Closing.
