### ISSUE TITLE
Remove "invoice" from the customer invoice email

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#26692]
The "customer invoice email" doesn't really send an invoice.

An invoice is a fiscal/legal document that you issue either before payment (if you sell on credit) or after payment (if you sell on pre-payment) and this email is not such a document.

In some countries, an invoice must be issued (by law) by a certified software (local or on the cloud), and calling this email "customer invoice email" can be misleading and, can be even become a legal issue (calling invoice to something is not).

I know that in some countries anything with a value on it could be considered an invoice, but I don't think this email qualifies as such a document. At most, it's a "payment request email" or an "order details email".

My proposal:
- Change the email name from "Customer invoice / Order details" to "Order details"
- Remove all mentions to "invoice" on this email (and WooCoommerce altogether)

**Comment by juliaamosova** [comment]
Hi @webdados,

Thanks for raising the issue! I can see by the number of thumbs up you received that this is indeed a pressing one for folks out there. I am marking it as an `enhancement` and `question` for now which means something for us to chat more about with the WooCommerce Core team. We'll try to review it soon and provide feedback here. Thanks for your patience!

**Comment by webdados** [comment]
Thanks @juliaamosova,

If this gets a consensus I'm more than happy to submit a PR.

Let me just add some additional details: it could make sense to not do a one time change and make the "invoice" term disappear so that people get used to this over two releases or so. Maybe step one could be to remove it from the email name and title and on a second phase remove it from other places. I'm just guessing here.

**Comment by juliaamosova** [comment]
Hi @webdados,

Thanks for your additional feedback and offer to submit a PR. We chatted about this further with the team and not sure yet that we should do any changes. Mainly because it seems that countries, in general, have a different definition of the `invoice` and so it is not easy to make it work for everyone with one particular solution. We realize that the existing one doesn't cater to everyone either. 

With that said, however, have you looked at editing the email template and/or translating the title, etc . where the word `invoice` appears to something that is more common in your region? If you did, can you please share why it doesn't work?

**Comment by juliaamosova** [comment]
Also placing here a few screenshots showing the template in question:

![inv1](https://user-images.githubusercontent.com/19143190/84069366-68682400-a998-11ea-8c0a-6a02f3d53968.jpg)

![Screen Shot 2020-06-08 at 2 51 54 PM](https://user-images.githubusercontent.com/19143190/84069397-70c05f00-a998-11ea-89f4-758d171f7c05.png)

![inv2](https://user-images.githubusercontent.com/19143190/84069402-73bb4f80-a998-11ea-8ebb-b3a957496900.jpg)

![inv3](https://user-images.githubusercontent.com/19143190/84069414-774ed680-a998-11ea-8e51-1d076e65ba69.jpg)

**Comment by webdados** [comment]
Hi @juliaamosova and thanks for your reply and the screenshot.
I know WooCommerce well and I'm a developer to 30+ WC plugins :-)

This brings us to a bigger problem in WooCommerce: hardcoded texts in emails. (yes, we can change them by moving the template to the child theme, but that's not a solution for most)

The term "invoice" is hardcoded in at least three files related to this email, and these cannot be customized on the WooCommerce admin:

![image](https://user-images.githubusercontent.com/6853605/84078321-a4b77680-a9d0-11ea-8e11-e7c927cbef33.png)

![image](https://user-images.githubusercontent.com/6853605/84078386-c0228180-a9d0-11ea-895a-f04a858a0dab.png)

![image](https://user-images.githubusercontent.com/6853605/84078548-05df4a00-a9d1-11ea-81a5-1a95be1bea86.png)

**Comment by cdcastro** [comment]
@webdados Thanks a lot for this issue. In fact this is a real problem we have for example in Portugal. Invoices here are a lot more than a simple PDF or email. 

@juliaamosova, for sure this update would be very appreciated and useful.

**Comment by lkraav** [comment]
> What the customer receives:
> 
> ![inv3](https://user-images.githubusercontent.com/19143190/84069414-774ed680-a998-11ea-8e51-1d076e65ba69.jpg)

Indeed, this screenshot itself is the perfect demonstration of the current core logic fail state:

1. "Invoice" and "order details" are not the same thing, as already stated in issue opening comment, so should most certainly not be written as "customer invoice / order details".

2. Screenshot clear as day does not have any invoice-specific data, it's simply repeating "order details", with Order ID and all. This has been a problem when store owner wants to re-send "new order" email to a customer, and somewhat unexpectedely something claiming to be an invoice (that really isn't, in a lot of legislations) gets sent.

Therefore, removing "invoice" language from admin actions and e-mail templates should be fine.

3. As-is, this core "Invoice" doesn't even ever get sent out, unless manually triggered. But in a lot of legislations, a valid invoice should be sent out automatically to accompany every completed transaction.

"Order" is a confirmation of "doing business request", "Invoice" is confirmation of "this transaction happened".

Core invoice implementation currently feels a bit like the famous "red-headed step-child" status. It's understandable, though, subject is complicated to address correctly across legislations. Still, as-is, I feel it could easily be made to be.. less wrong? Just remove core "invoice" language, and rebuild pieces from there.

Good job @webdados opening this issue :clap:

**Comment by webdados** [comment]
> unexpectedly something claiming to be an invoice (that really isn't, in a lot of legislations) gets sent.

This is exactly my concern

**Comment by webdados** [comment]
> But in a lot of legislations, a valid invoice should be sent out automatically to accompany every completed transaction

This is also what triggered the issue. For example, in Portugal (and I'm sure in other legislations), an invoice must be issued by a certified software. There are a couple of plugins that integrate with such systems and allow the issuing and sending of a proper (real, legal) invoice.

![image](https://user-images.githubusercontent.com/6853605/84257362-22809c80-ab0d-11ea-8f31-d1bb9652bfef.png)

As you can see, this is very misleading. And the problem is not on the invoicing plugin. It's on WooCommerce calling an "invoice" to something that simply isn't one.

**Comment by lkraav** [comment]
Yep, @baselbers https://github.com/baselbers/woocommerce-pdf-invoices/ and @Spreeuw https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/ might be interested in this discussion, if they're not following already.

Any additional insight from you guys?

**Comment by Spreeuw** [comment]
@lkraav yes I brought this up at the time the change was introduced back in 2017. I'm all for removing 'invoice' from the email name too

**Comment by negapo** [comment]
My two cents:
@webdados is right on the money, im also from Portugal where there is a specific legal meaning of the term "invoice", but this is a broader issue, although the term "invoice" might have different meaning in some countries that specific email is just an "Order Summary" email, just that, one that its very helpful like when there was a problem with sending the order confirmation email and we have to resend it to a client. Why not reformulate that email to be just that? If the term "invoice" is not consensual than we shouldn't be using it or we should localize the term.

**Comment by negapo** [comment]
Just to make an argument:

**Order Summary Email**
Has a lot of use cases:
- Costumer inputs the wrong email address at checkout and we need to send another email.
- Something went wrong with the order confirmation email (SMTP server, client email classified message as SPAM) and we want to try again.
- Costumer has deleted order confirmation email and wants a summary of the order for exchanges / returns, etc.
There is no confusing about what it is, it's a summary of the order.
It's essential for a real life store, i can testify.

**Customer invoice / Order details"**
Use cases:
- Someone who doesn't have an invoice system and sends their invoices manually on every order.
- Someone trying to achieve what an "Order Summary" email would be.
The name is confusing, at least in some countries where an "invoice" has a strong legal meaning (where rules have to be enforced).
Non essential unless its used as a "Order Summary" email.

**Comment by nicomollet** [comment]
+1 same in France

**Comment by webdados** [comment]
@nicomollet Let's hope a big country like yours will have a stronger effect on the WooCommerce team's opinion on changing this. 😂

**Comment by webdados** [comment]
Any decision on this, and why was the label "has feedback" been removed?

I'm not going to repeat all the arguments already stated on this thread, but I will focus on this one: **this is a concern to each and every country where the word "invoice" has an actual legal meaning**.

**Comment by vvaz** [comment]
Just read the whole thread and I'm adding my voice to the concerns here. Would really love to see this implemented. If my clients receive an "Invoice" from a non-certified invoicing software vendor - from a list that my government manages and where WooCommerce is not listed / approved - my business can get into serious trouble.

**Comment by mklasen** [comment]
Heya, 

In The Netherlands we don't consider an order summary an invoice. Invoice requirements *for businesses* here are quite specific. You'll find a summary below with a source in the bottom.

With 2.5 billion spend on foreign webshops by Dutch consumers in 2020 (an increase of 30% compared to 2019) we can state that business between European member states is thriving. Countries follow their own rules and have different expectations from the word invoice. This is both confusing for the the webshop owner, as for the customer. 

Quoted from the Dutch Tax Administration website (source below):

Every invoice you receive must include the following data:

- the name and address of the supplier
- the VAT identification number of the supplier
- your name and address
- the invoice number
- the invoice date
- the date on which the goods or services were supplied
- the quantity and type of goods supplied
- the nature and type of services supplied


Invoices must also include the following data for every VAT tariff or exemption:

- the price per piece or unit, excluding VAT
- any reductions that are not included in the price
- the VAT tariff that has been applied
- the cost (the price excluding VAT)
- in case of advance payment: the date of payment, if this is different from the invoice date
the amount of VAT

Sources:
- https://www.belastingdienst.nl/wps/wcm/connect/bldcontenten/belastingdienst/business/vat/vat_in_the_netherlands/vat_administration/invoice_requirements

**Comment by webdados** [comment]
@mklasen In short, and to clarify, you do agree that the word "invoice" should not be used in the WooCommerce core/emails?

The rules are quite similar here in Portugal and all invoicing software must be certified by the tax authority.

We even have (for quite some years now) a mechanism similar to blockchain, in which every invoicing document issued has a hash key that is calculated with details from that document and the same hash key from the document issued immediately before that one, which makes theoretically impossible for a business owner to "change" anything on a previous invoice, like deleting it or change its value to pay fewer taxes, without breaking the whole chain from thereon.

These kinds of rules are becoming standard in all the European Union and more countries will follow them.

**Comment by mklasen** [comment]
Definitely, we don't consider an email order confirmation / order summary an invoice in The Netherlands. 

I think it could be considered as one when it contains all the required information but since this is country-specific, the quick fix would be to just eliminate the word invoice. The site owner can then integrate an invoice solution themselves.

**Comment by passatgt** [comment]
Same situation for Hungary, invoicing can be done only with certified softwares, so this e-mail is just and order confirmation or reminder. Which is useful, but its certainly not an invoice(at least not in Hungary). I develop two separate invoicing extension(with around 5000+ active installs) and this issue does come up frequently in support tickets.

**Comment by webdados** [comment]
@passatgt That's exactly why I raised the issue. The screenshot in [this comment](https://github.com/woocommerce/woocommerce/issues/26692#issuecomment-641910088) shows options to issue a real invoice that can be confused by the "fake invoice" email from WooCommerce.

**Comment by nicomollet** [comment]
Can we expect an answer from Devs on this?
This is currently the issue with most +1 reactions.
https://github.com/woocommerce/woocommerce/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by mklasen** [comment]
Translating the string "invoice" to "order details" doesn't solve the issue completely as customers and site admins might still use a different language, especially in multisite environments.

Examples:
- A dutch customer uses the English version of a WooCommerce site and receives an order summary that's called an invoice, but doesn't qualify for invoice requirements. Using the word "Order details" would prevent this as you don't expect it to be an invoice.
- Shop managers do not always use the local translations. For example, almost all WordPress websites that I manage have the language set to English.

**Comment by negapo** [comment]
This is really hard to understand and i think its a symptom of where WooCommerce is heading, Automattic argument is, lets not change it because: "countries, in general, have a different definition of the invoice ..."

**Isn't this the main reason to change it?**
There is no argument to name this "invoice" and not "order summary / details" and although this kind of things can be solved by plugins or localization its seems that we are reluctant to solve issues at the source and just duct taping them.

**Comment by webdados** [comment]
> Isn't this the main reason to change it?

YES! A round of applause to @negapo, please.

**Comment by webdados** [comment]
Anyone here? :-D

**Comment by webdados** [comment]
> Can we expect an answer from Devs on this? This is currently the issue with most +1 reactions. https://github.com/woocommerce/woocommerce/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

Almost 2 years have passed and it still is: https://github.com/woocommerce/woocommerce/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by barryhughes** [comment]
Feel free to add notes, observations and questions to https://github.com/woocommerce/woocommerce/pull/45395. This PR is currently an early draft and has not been finalized, so it's a great time to indicate if there are problems with the proposed wording, etc.

**Comment by nicomollet** [comment]
Great, finally! I wish this kind of change didn't take that long.
