### ISSUE TITLE
Slow query in the Woocommerce new version

### ISSUE THREAD

**Issue by diegpl** [woocommerce/woocommerce#26696]
**Is your feature request related to a problem? Please describe.**
There is a DB query loading many rows if the user is a superadmin. The pic illustrates that https://pasteboard.co/JbpBbBN.jpg – it result in a slow query. Are you guys aware of that in the last version?

Just saw another slow query too: https://pasteboard.co/JbpEj1j.jpg - I do not know if the get_adjacent_post() is really needed. But maybe it is showing there just as a collateral effect of many rows called before.

Query monitor plugin do not show the exact time. It shows more the number of rows and/or what caused the slowness…

The problem about many rows is might related just to the superadmin.

**Describe the solution you'd like**
To filter the rows called related to the user by what I saw in the logs.

**Describe alternatives you've considered**
To filter the rows called related to the user by what I saw in the logs.

**Additional context**
I`ve been seeing some update_meta() being called while logged in the front as well. I think the new version solved some of that and the duplicated calls. But probably some more can be cut off as well.

Thank you! ;-)

**Comment by diegpl** [comment]
That is where they requested me to post the issue here: https://wordpress.org/support/topic/slow-query-in-the-woocommerce-new-version/
Thank you! ;-)

**Comment by claudiosanches** [comment]
Hello @diegpl.

> Just saw another slow query too: https://pasteboard.co/JbpEj1j.jpg - I do not know if the get_adjacent_post() is really needed. But maybe it is showing there just as a collateral effect of many rows called before.

Seems like there's many things impacting on the performance, but note that `get_adjacent_post()` isn't used on WooCommerce, also for none of the others functions that WP says that uses `get_adjacent_post()` function: https://developer.wordpress.org/reference/functions/get_adjacent_post/#used-by

This seems like a feature from your theme, also we didn't changed anything that could impact performance just for a super admin, so this really sounds like something related to your theme.

I'm closing this issue for now. If I missed something, please leave a comment and we will take a second look.
