### ISSUE TITLE
[GlobalStep] On MAC, created attributes fails to update on Products ->Add New Attribute page.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#26710]
**Environment:**
MAC Book Air: Safari(v13.0.5 (15608.5.11))

**Steps to Reproduce:** 
1. Login to the wp-admin dashboard using valid credentials.
2. Click on Products.
3. Click on Attributes.
4. Add valid attribute details i.e., Name, Slug, Default Sort Order.
5. Click on Add Attribute button.
6. Observe that newly created attributes fails to update in the table present on Attributes page.

**Actual Result:**
On MAC, created attributes fails to update on Products ->Add New Attribute page.

**Expected Result:**
User should be able to add attributes for product.

[#2642.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/4731076/2642.zip)

**Comment by juliaamosova** [comment]
Hi @gglobalstep,

Thanks for raising the issue! I took a look at the video you shared and noted that while you are trying to create an attribute with a different attribute name from the one that already exists, you assign the new attribute the same slug `None` which already exists. There is also a message letting you know the same.

The slug value is not case-sensitive and so when `None` gets sanitized before being saved in the database, it becomes `none` which is the same as an already existing slug of the previously created attribute:

![slug](https://user-images.githubusercontent.com/19143190/83914729-cfd76700-a73f-11ea-90af-abdfcc97b799.jpg)

I am closing this as a non-issue.
