### ISSUE TITLE
Checkboxes not working in Woocommerce backend.

### ISSUE THREAD

**Issue by laurence2283** [woocommerce/woocommerce#26713]
**Describe the bug**

When trying to use checkboxes to select multiple orders/products in the woo commerce backend the checkboxes are not functioning and not being marked as selected. 

**To Reproduce**
1. Go to 'Product Page'
2. Click on 'Product Checkbox' - Nothing Happens
**Expected behavior**

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>

WooCommerce version: |   | 4.2.0
-- | -- | --
WooCommerce REST API package: |   | 1.0.8 wp-content/plugins/woocommerce/packages/woocommerce-rest-api
WooCommerce Blocks package: |   | 2.5.16 wp-content/plugins/woocommerce/packages/woocommerce-blocks/
Action Scheduler package: |   | 3.1.6 wp-content/plugins/woocommerce/packages/action-scheduler
WooCommerce Admin package: |   | 1.2.3 wp-content/plugins/woocommerce/packages/woocommerce-admin
Log directory writable: |   | wp-content/uploads/wc-logs/
WordPress version: |   | 5.4.1
WordPress multisite: |   | –
WordPress memory limit: |   | 1 GB
WordPress debug mode: |   | –
WordPress cron: |   |  
Language: |   | en_GB
External object cache: |   | –

</details>

**Comment by laurence2283** [comment]
The issue has now resolved itself.

**Comment by juliaamosova** [comment]
Hi @laurence2283,

Thanks for raising the issue. Glad to hear its been resolved. 

I am going to close the issue but feel free to comment back in case it comes back so that we could take another look.
