### ISSUE TITLE
Intermittent error 500 while running the tests

### ISSUE THREAD

**Issue by renatho** [woocommerce/woocommerce#26724]
**Describe the bug**
I'm trying to set up the `@woocommerce/e2e-environment`, but sometimes when I run the tests a weird error 500 happens (the folder that appears in the trace in the screenshot is not a folder of my computer and I believe it's not of the docker images too). It looks like to be associated with the `initialize.sh`, because it happens sometimes when I add it to the `tests/e2e/docker/initialize.sh` (even with only an `echo`). And it runs the tests after the error.

**To Reproduce**
1. Set up the env following the [documentation](https://github.com/woocommerce/woocommerce/tree/master/tests/e2e/env)
2. Run `npm explore @woocommerce/e2e-environment -- npm run docker:up`
3. Run `npm explore @woocommerce/e2e-environment -- npm run test:e2e`

**Screenshots**
<img width="908" alt="Screen Shot 2020-06-08 at 11 24 35" src="https://user-images.githubusercontent.com/876340/84042342-52983600-a97b-11ea-97c0-28dda4a400c1.png">

**Expected behavior**

Run the tests without the error 500.

**Isolating the problem:**
- I tried it in a project and in the hello-dolly plugin and the same happened.

**Comment by renatho** [comment]
Additional information: I could see the error without the `initialize.sh` too.

**Comment by juliaamosova** [comment]
Hi @renatho,

Apologies for the delayed response here. Would you please let us know if you are still experiencing the issue?

**Comment by renatho** [comment]
> Hi @renatho,
> 
> Apologies for the delayed response here. Would you please let us know if you are still experiencing the issue?

Hi @juliaamosova ! No worries! 😊

I didn't find a solution. I tested now and it didn't happen, but I don't know if it was fixed with another change because it happens eventually.

But any server error, still points to that folder. Even in Travis, like this in some warnings: https://travis-ci.org/github/Automattic/sensei/jobs/713735399.

Any other information you need about this, feel free to ask me. 😉

**Comment by rrennick** [comment]
This should be fixed in version 0.15.
