### ISSUE TITLE
Shipping regions in Kenya

### ISSUE THREAD

**Issue by NDULZ** [woocommerce/woocommerce#26722]
Kenya is a very large country and so is the capital city Nairobi. Putting the entire country in one shipping zone makes it impossible to have different prices for different regions. Using the postal code feature is also impossible due to the poor addressing the country and the few that have addresses use P.O Boxes and rarely update their addresses to the nearest post office.

Kenya should be split into different distinct shipping Zones like Nigeria and Angola and Nairobi into even further smaller pieces.

Shipping by distance is the only alternative that comes close to resolving the issue however it is not perfect and comes with additional costs.

**Comment by peterfabian** [comment]
How are you folks going to handle this in blocks? I have a feeling it might be worth it to revisit how this is handled? @mikejolley / @nerrad

**Comment by nerrad** [comment]
@peterbutler The new blocks gather shipping information [via a custom REST API endpoint](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/master/src/StoreApi/Schemas/CartShippingRateSchema.php) which in turn just pulls what is available from WC core. So this sounds like if this is addressed in WC Core, then the blocks should "just work".

**Comment by juliaamosova** [comment]
Thanks for the details @nerrad, noted. 

Adding some notes here as we discussed this further with the team today. 

More generally speaking, we can’t add all of the states for every country as they’re all sent to the client on request. When we looked at adding the UK regions, for example, we saw that it would add significant response content. 

In the long term, we should find a better way to handle states and regions addition to countries that don't have them yet in WooCommerce. One of the ways could be async fetch for the states of a given country.

With that said, we are going to add Kenya regions for now but look into better ways to handle it in the future. 

Hi @NDULZ,

Thanks for raising the issue! Given the discussion we had with the team, we are going to add Kenya states to WooCommerce. We are utilizing the [Unicode CLDR](http://cldr.unicode.org/) which provides key building blocks for software to support the world's languages, with the largest and most extensive standard repository of locale data available. 

With that said, we are planning to add Kenya regions as shown below:

https://github.com/unicode-org/cldr/blob/release-37/common/subdivisions/en.xml#L2549-L2596

Stay tuned for updates.

**Comment by NDULZ** [comment]
Hi @juliaamosova 
Thank you for the prompt feedback.
I see you decided to subdivide the regions to counties.
Just a suggestion to assigning each county an id, each county has a predefined number by the Government of Kenya e.g. Mombasa is 001 and Nairobi is 047 as opposed to having them in alphabetical order. You can find the full list here: https://en.wikipedia.org/wiki/Counties_of_Kenya.
Additionally is there any way to further subdivide Nairobi county?

**Comment by NDULZ** [comment]
And do you have an ETA on the implementation?

**Comment by NDULZ** [comment]
@juliaamosova ^

**Comment by juliaamosova** [comment]
Hi @NDULZ,

>I see you decided to subdivide the regions to counties.

As I mentioned, we follow the [Unicode CLDR](http://cldr.unicode.org/) which had the list of counties for Kenya available as I added them. We use the same format for all other countries in WooCommerce. 

>Just a suggestion to assigning each county an id, each county has a predefined number by the Government of Kenya e.g. Mombasa is 001 and Nairobi is 047 as opposed to having them in alphabetical order.

There are a few reasons why we wouldn't do it:

- Similar to what I already mentioned above - we follow the Unicode CLDR standard which lists counties in the alphabetical order;
- The rest of the regions of other countries in WooCommerce are also listed in alphabetical order which is the way for us to keep things in order in WooCommerce. 

If you like, you can modify counties by using this snippet:

https://docs.woocommerce.com/document/addmodify-states/

There are also plugins that allow to do that. For example, [Woo Add Custom States](https://wordpress.org/plugins/woo-add-custom-states/). 

>Additionally is there any way to further subdivide Nairobi county?

You can use the snippet above to do that as we won't be dividing the county further. 

>And do you have an ETA on the implementation?

The fix will be included in WooCommerce 4.3 which is scheduled to be released on July 7, 2020.
