### ISSUE TITLE
Rounding Error - Cant Refund

### ISSUE THREAD

**Issue by negapo** [woocommerce/woocommerce#26734]
**Describe the bug**
Trying to refund all items for an order. Due to a rounding error the total amount to refund is one cent higher than the total order amount, when clicking refund an error message appears "cant refund this amount".

**To Reproduce**
Hard to reproduce unless you use the same values as in the snapshot order. Use those value to create a new order, then try to refund the whole order.

**Screenshots**
[https://ibb.co/6ZqvqJr](url)

**Expected behavior**
Total amount to refund should be equal to the order amount.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @negapo,

Thanks for raising the issue. Can you please specify the tax percentage on your site? Also, it will be great to see the screenshot of your tax settings that can be found by navigating to `WooCommerce / Settings / Tax`.

**Comment by negapo** [comment]
Sure, all products on that order are at the normal tax rate which is 23%.
On the tax options menu i have the option "include prices with taxes" selected, so all my store prices are inputed with taxes and the tax free price is deducted by Woo (Price / ( 1 + Tax Rate)). I haven't had the time to check where the rounding is taking place but it's for sure a rounding problem.

**Comment by webdados** [comment]
I'm pretty sure this is related to #26582

**Comment by negapo** [comment]
just read #26582 , i think it's the same thing, we also had problems with rounding on the same conditions (tax 23%, prices inclusive of tax, rounding at subtotal).

**Comment by vedanshujain** [comment]
Closing this issue since the original issue was fixed and released 4.3. @negapo if this is still happening please comment back and we will re-open to take a look.

**Comment by negapo** [comment]
this is indeed solved, thanks @vedanshujain
