### ISSUE TITLE
Cannot generate standalone invoices

### ISSUE THREAD

**Issue by BonnieBeeman** [woocommerce/woocommerce#26747]
Before the last WooCommerce upgrade we were able to generate standalone invoices and print them when we mailed a shipment.  We include invoices in each shipment.   Why was invoice generation as a standalone along with the parts list disabled?  These documents are critical to our business.  We do NOT want to use the default WooCommerce order action " Email Invoice / order details to customer" as all of our shipments need manual USPS order numbers added and we have to wait 24 hours for USPS pickup.   This is a huge problem that the standalone invoice generation and parts has been disabled. 

![Cannot generate standalone invoices](https://user-images.githubusercontent.com/13384976/84343321-b29a0280-ab5c-11ea-9039-7955455b2984.png)

**Comment by juliaamosova** [comment]
Hi @BonnieBeeman,

Thanks for raising the issue. We haven't done any changes around the `Actions` column in a while. In WooCommerce Core, that column allows you to change the order status and for example mark order as `Completed`:

![complete](https://user-images.githubusercontent.com/19143190/84413465-a5255c80-abde-11ea-8613-797a15ecd03a.jpg)

It sounds like the functionality you are looking for is being added by one of the plugins on the site.

**Comment by BonnieBeeman** [comment]
You are right.  

My Wordpress theme is Bazar, which includes Yith plugins.  The ability to print invoices as a standalone is attributed to Yith.  I am sorry for bothering you.  Thank you for explaining this so clearly.

**Comment by juliaamosova** [comment]
Hi @BonnieBeeman, no worries at all, and thanks for your follow-up! I am closing this thread as a non-WooCommerce issue.
