### ISSUE TITLE
Bulk edit sale price of variable products (variations) not updating the sale price

### ISSUE THREAD

**Issue by kennydeckers** [woocommerce/woocommerce#26763]
**Describe the bug**
When you want to "bulk edit" the sale price of (a) variable product(s) it does not seem to do actually update anything.

**To Reproduce**
1. Go to the "All products" overview
2. Filter by product type "Variable product"
3. Select a variable product
4. Bulk Actions -> Edit -> Apply
5. Under the "Product data" section, next to the "Sale price" label, select "Set to regular price decreased by (fixed amount or %):"
6. Enter 50% as value
7. Click Update

**Screenshots**
![image](https://user-images.githubusercontent.com/2227271/84587197-7943ea00-ae1d-11ea-9200-1eae206131c9.png)

**Expected behavior**
I expect the sale price to be 50% the value of the regular price.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): __REDACTED__
Site address (URL): __REDACTED__
WC Version: 4.2.0
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.3
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.18
PHP Post Max Size: 512 MB
PHP Time Limit: 600
PHP Max Input Vars: 10000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.7.30-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.0
WC Database Prefix: wptl_
Total Database Size: 49.24MB
Database Data Size: 44.59MB
Database Index Size: 4.65MB
wptl_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_actionscheduler_actions: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wptl_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wptl_actionscheduler_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wptl_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_options: Data: 41.81MB + Index: 3.12MB + Engine MyISAM
wptl_postmeta: Data: 2.26MB + Index: 1.02MB + Engine MyISAM
wptl_posts: Data: 0.37MB + Index: 0.16MB + Engine MyISAM
wptl_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wptl_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wptl_term_relationships: Data: 0.06MB + Index: 0.15MB + Engine MyISAM
wptl_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wptl_usermeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wptl_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wptl_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_wc_customer_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_wc_order_product_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_wc_order_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wptl_wc_product_meta_lookup: Data: 0.09MB + Index: 0.10MB + Engine MyISAM
wptl_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wptl_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 436
page: 6
post: 2
product: 241
product_variation: 1033

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (3) ###

Jetpack by WordPress.com: by Automattic – 8.6.1
WooCommerce Services: by Automattic – 1.23.2
WooCommerce: by Automattic – 4.2.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.6
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 2
Oldest: 2020-06-14 06:26:09 +0000
Newest: 2020-06-14 06:33:11 +0000

`
```
</details>

**Comment by tammullen** [comment]
Hi @kennydeckers 

Thank you for taking the time reporting this issue and the associated PR, we really appreciate your help. 

I can reproduce this behaviour on my end that editing both sale price and regular price has no effect on the variations and the product updated notification doesn't make this clear.

I am adding the Question label for now as I think in some scenarios this is intended behaviour as for attributes like prices, each variation has its own prices that should not be affected however the UI is confusing in this regard.

We will discuss this on the team.

**Comment by kennydeckers** [comment]
> Hi @kennydeckers
> 
> Thank you for taking the time reporting this issue and the associated PR, we really appreciate your help.
> 
> I can reproduce this behaviour on my end that editing both sale price and regular price has no effect on the variations and the product updated notification doesn't make this clear.
> 
> I am adding the Question label for now as I think in some scenarios this is intended behaviour as for attributes like prices, each variation has its own prices that should not be affected however the UI is confusing in this regard.
> 
> We will discuss this on the team.

You're welcome! I saw the the ability to update the stock for variable products through bulk-edit was already possible so I really think that this feature would be a nice addition (or fix, depending on how you see it 😄).

**Comment by KoolPal** [comment]
@tammullen What happens to this fix #26767 Will this get released? If yes, in which version of Woocommerce?

**Comment by rrennick** [comment]
As explained in https://github.com/woocommerce/woocommerce/pull/26767#issuecomment-663645291 this feature isn't viable.

**Comment by pacmanito** [comment]
The feature is viable as currently there's no way to bulk edit variation prices. Maybe users can make a decision if their server can handle this themselves?

**Comment by kdckrs** [comment]
I agree, for me it's a viable feature. If someone decided to load 20809808 products on the table he will probably already know that this has a performance impact and there is a possibility that bulk actions will use a lot of memory and potentially cause a timeout.

PS: It's 2021 right?

**Comment by pacmanito** [comment]
@rrennick  So maybe instead of just rejecting the feature it's better to implement it in some way preventing timeout issues. You have an Action Scheduler, why not use it for such task?

**Comment by rrennick** [comment]
> You have an Action Scheduler, why not use it for such task?

@pacmanito It could definitely be done this way. Another alternative would be writing a WP CLI tool to do it as CLI does not timeout processes. 

The issue with WC core implementing bulk edits with Action Scheduler is that it's inconsistent with the rest of the WP dashboard bulk edit experience where changes are applied (more or less) instantly. Alternatively, a **Bulk Edit Variation Prices** extension seems viable and should not take up too much maintenance time.

Edit to add: If merchants install a small extension for a task, they are going to be aware that the implementation might not be consistent with the rest of the WP dashboard experience.

**Comment by pacmanito** [comment]
@rrennick I would be happy to have it in any form, although I doubt the adoption rate will be high as an extension because people simply won't know about its existence.
Currently, for this sole purpose (bulk editing sale prices for variations) I have to keep installed a whole bulk edit plugin which is rather bulky and is absolute overkill for this simple task.
As for experience inconsistency, I suppose that a simple popup saying something like "bulk edit is being handled in the background, please be ready to wait for some time until it is finished" would be sufficient. And it would be the best solution because anything more complicated has 99% chance of never being done. 
In the ideal world, we can have a dedicated screen showing variations and their quantities where the quantity can be edited individually or in bulk. This has been asked for already because editing variations quantity is very time-consuming in WooCommerce compared to other eCommerce platforms (you have to open the product then open the variations tab which is rather slow and then open a particular variation). But I am afraid this won't be ever done just like many other features besides Blocks and JS-Admin, that's why I am asking to simply merge this pull request or at least release this as an extension if you suppose it should be done this way.

P.S. Current implementation is misleading for sure because you can select variable products, start bulk edit and get a success message while no changes have been made.
