### ISSUE TITLE
custom product_type_options not working

### ISSUE THREAD

**Issue by redactuk** [woocommerce/woocommerce#26769]
**Describe the bug**
If I add a new product_type_options checkbox the checkbox is always checked regardless of postmeta value.

**To Reproduce**
Add this code to functions:
```
add_filter('product_type_options', function ($product_type_options) {

	$product_type_options['purchasable'] = array(
		'id' => '_purchasable',
		'wrapper_class' => 'show_if_simple show_if_grouped show_if_variable',
		'label' => __('Purchasable', 'rscustom'),
		'description' => __('Purchasable products that can be bought online.', 'rscustom'),
		'default' => 'no'
	);

	return $product_type_options;

}, 10, 1);

add_action('woocommerce_process_product_meta', function ($post_id) {

	$is_purchasable = isset($_POST['_purchasable']) ? 'yes' : 'no';
	update_post_meta($post_id, '_purchasable', $is_purchasable);

});
```

The new 'purchasable' product_type_options value is correctly saved, but checkbox always displayed as checked.

The line that seems to be causing the issue in WooCommerce is in html-product-data-panel.php - line 29

```
$selected_value = is_callable( array( $product_object, "is_$key" ) ) ? $product_object->{"is_$key"}() : 'yes' === get_post_meta( $post->ID, '_' . $key, true );
```

The condition is always evaluating to true but `$product_object->{"is_$key"}()` is also evaluating to true for my custom option even if meta value is 'no'.
I'm afraid I don't understand why this is happening.

If I replace Line 29 simply with

```
$selected_value = 'yes' === get_post_meta( $post->ID, '_' . $key, true );
```
then it appears to work correctly.

**WordPress Environment**
WordPress: 5.4.2
WooCommerce: 4.2.0

**Comment by rrennick** [comment]
@redactuk Thanks for contacting us. The `is_purchasable()` function exists in the product data store. You need to use a meta key that doesn't conflict with the product data store `is_*` functions.
