### ISSUE TITLE
Checkout not working: Asks me to insert mail even if mail is not empty

### ISSUE THREAD

**Issue by clex0r** [woocommerce/woocommerce#26773]
Status Report:
`
### WordPress Environment ###

WordPress address (URL): https://amsport-shop.ch
Site address (URL): https://amsport-shop.ch
WC Version: 4.2.0
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.4
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_CH
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.0.33 - Wir empfehlen
PHP Version 7.2 oder höher für mehr Leistung und Sicherheit zu verwenden. So aktualisierst du deine PHP-Version

PHP Post Max Size: 200 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.70.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.45-MariaDB
Max Upload Size: 200 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.0
WC Database Prefix: wp_
Datenbank-Gesamtgröße: 20.39MB
Datenbank-Datengröße: 17.35MB
Datenbank-Indexgröße: 3.04MB
wp_woocommerce_sessions: Daten: 0.06MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Daten: 0.03MB + Index: 0.02MB + Engine MyISAM
wp_woocommerce_tax_rates: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Daten: 0.56MB + Index: 0.16MB + Engine MyISAM
wp_actionscheduler_claims: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Daten: 0.28MB + Index: 0.18MB + Engine MyISAM
wp_commentmeta: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Daten: 0.23MB + Index: 0.18MB + Engine MyISAM
wp_email_log: Daten: 0.25MB + Index: 0.00MB + Engine MyISAM
wp_icl_content_status: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_core_status: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_flags: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_languages: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_icl_languages_translations: Daten: 0.10MB + Index: 0.11MB + Engine MyISAM
wp_icl_locale_map: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_message_status: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_node: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_reminders: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_strings: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_string_positions: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_string_status: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_string_translations: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_translate: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_translate_job: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_translations: Daten: 0.16MB + Index: 0.28MB + Engine MyISAM
wp_icl_translation_batches: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_icl_translation_status: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_imagify_files: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_imagify_folders: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_carts: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_jobs: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_newsletter: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_newsletter_emails: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_newsletter_sent: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_newsletter_stats: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_newsletter_user_logs: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Daten: 4.19MB + Index: 0.28MB + Engine MyISAM
wp_postmeta: Daten: 1.08MB + Index: 0.20MB + Engine MyISAM
wp_posts: Daten: 2.11MB + Index: 0.22MB + Engine MyISAM
wp_pum_subscribers: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rednao_wc_invoice: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rednao_wc_invoices_created: Daten: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_rednao_wc_invoices_custom_field: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_smush_dir_images: Daten: 0.14MB + Index: 0.07MB + Engine MyISAM
wp_social_users: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Daten: 0.02MB + Index: 0.04MB + Engine MyISAM
wp_term_taxonomy: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Daten: 0.09MB + Index: 0.04MB + Engine MyISAM
wp_users: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_user_registration_sessions: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wcpdf_invoice_number: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_notes: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_download_log: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_stats: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_tax_lookup: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_meta_lookup: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_tax_rate_classes: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfblockediplog: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfblocks7: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfconfig: Daten: 2.33MB + Index: 0.02MB + Engine MyISAM
wp_wfcrawlers: Daten: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_wffilechanges: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wffilemods: Daten: 3.28MB + Index: 0.65MB + Engine MyISAM
wp_wfhits: Daten: 0.22MB + Index: 0.07MB + Engine MyISAM
wp_wfhoover: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfissues: Daten: 0.04MB + Index: 0.01MB + Engine MyISAM
wp_wfknownfilelist: Daten: 1.77MB + Index: 0.20MB + Engine MyISAM
wp_wflivetraffichuman: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wflocs: Daten: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wflogins: Daten: 0.12MB + Index: 0.03MB + Engine MyISAM
wp_wfls_2fa_secrets: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfpendingissues: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfreversecache: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfsnipcache: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfstatus: Daten: 0.13MB + Index: 0.06MB + Engine MyISAM
wp_wftrafficrates: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_indexable: Daten: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_yoast_indexable_hierarchy: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_migrations: Daten: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_yoast_primary_term: Daten: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_seo_links: Daten: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_yoast_seo_meta: Daten: 0.03MB + Index: 0.04MB + Engine MyISAM

### Post Type Counts ###

attachment: 226
custom_css: 1
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
jp_vid_sitemap: 2
nav_menu_item: 23
page: 42
popup: 1
popup_theme: 6
post: 5
product: 22
product_variation: 21
revision: 249
shop_coupon: 2
shop_order: 27
user_registration: 1
wpcf7_contact_form: 3
wphb_minify_group: 25

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (31) ###

All-in-One WP Migration: von ServMask – 7.23
Contact Form 7: von Takayuki Miyoshi – 5.1.9
E-Mail Log: von Sudar – 2.3.2
Facebook for WooCommerce: von Facebook – 1.11.4
Flexible Shipping: von WP Desk – 3.9.20
GA Google Analytics: von Jeff Starr – 20200325
Site Kit by Google: von Google – 1.9.0
Imagify: von WP Media – 1.9.10
Jetpack von WordPress.com: von Automattic – 8.6.1
Kadence WooCommerce Email Designer: von Kadence WP – 1.4.1 – Die installierte Version wurde nicht mit der aktiven WooCommerce-Version 4.2.0 getestet
Limit Login Attempts Reloaded: von WPChef – 2.13.0
Mailchimp for WooCommerce: von Mailchimp – 2.4.0 – Die installierte Version wurde nicht mit der aktiven WooCommerce-Version 4.2.0 getestet
Newsletter: von Stefano Lissa &
Das Newsletter Team – 6.7.1
Nextend Social Login: von Nextendweb – 3.0.24
UpdraftPlus – Sichern/Wiederherstellen: von UpdraftPlus.Com
DavidAnderson – 1.16.25

WC Password Strength Settings: von Daniel Santoro – 2.1.0 – Die installierte Version wurde nicht mit der aktiven WooCommerce-Version 4.2.0 getestet
WooCommerce Payrexx Gateway: von Payrexx – 1.6.20 – Die installierte Version wurde nicht mit der aktiven WooCommerce-Version 4.2.0 getestet
WooCommerce PDF Invoice Builder: von RedNao – 1.2.12 – Die installierte Version wurde nicht mit der aktiven WooCommerce-Version 4.2.0 getestet
WPC Product Bundles for WooCommerce: von WPClever.net – 5.2.2
Product Slider and Carousel with Category for WooCommerce: von WP OnlineSupport – 2.2 – Die installierte Version wurde nicht mit der aktiven WooCommerce-Version 4.2.0 getestet
WooCommerce Admin: von WooCommerce – 1.2.4 – Die installierte Version wurde nicht mit der aktiven WooCommerce-Version 4.2.0 getestet
WooCommerce PayPal Checkout Gateway: von WooCommerce – 2.0.2 – Die installierte Version wurde nicht mit der aktiven WooCommerce-Version 4.2.0 getestet
WooCommerce Stripe-Gateway: von WooCommerce – 4.4.0 – Die installierte Version wurde nicht mit der aktiven WooCommerce-Version 4.2.0 getestet
WooCommerce Google Analytics Integration: von WooCommerce – 1.4.22
WooCommerce PDF Invoices & Packing Slips: von Ewout Fernhout – 2.5.1
WooCommerce Services: von Automattic – 1.23.2
WooCommerce: von Automattic – 4.2.0
Wordfence Security: von Wordfence – 7.4.7
Yoast SEO: von Team Yoast – 14.3
WP Rocket: von WP Media – 3.5.5.1
Custom Product Tabs for WooCommerce: von YIKES
Inc. – 1.7.1 – Die installierte Version wurde nicht mit der aktiven WooCommerce-Version 4.2.0 getestet

### Inactive Plugins (5) ###

Advanced Custom Fields Multilingual: von OnTheGoSystems – 1.6.0
Shortcodes Ultimate: von Vladimir Anokhin – 5.8.0
WooCommerce Multilingual: von OnTheGoSystems – 4.9.0 – Die installierte Version wurde nicht mit der aktiven WooCommerce-Version 4.2.0 getestet
WPML Media: von OnTheGoSystems – 2.5.5
WPML Multilingual CMS: von OnTheGoSystems – 4.3.6

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: CHF (CHF)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: #75 - /shop/
Warenkorb: #77 - /cart/
Kasse: #79 - /checkout/
Mein Konto: #81 - /my-account/
Allgemeine Geschäftsbedingungen: #343 - /agb/

### Theme ###

Name: Flatsome
Version: 3.11.3
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – Wenn du WooCommerce mit einem Theme
das du nicht selbst entwickelt hast
an eigene Bedürfnisse anpasst
dann empfehlen wir die Verwendung eines Child-Themes. Siehe Wie du ein Child-Theme erstellst (engl.)

WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

### Action Scheduler ###

Abgeschlossen: 1.008
Oldest: 2020-05-15 13:38:38 +0000
Newest: 2020-06-15 13:30:46 +0000

Ausstehend: 2
Oldest: 2020-06-15 13:45:46 +0000
Newest: 2020-06-15 14:08:07 +0000

`

As the title describes, i can not checkout because of missing email, even if the mail is provided.
To check: https://amsport-shop.ch/shop/

Add anything to cart and try to checkout.

**Comment by tammullen** [comment]
Hi @clex0r 

I wasn't able to reproduce your issue.

![Screenshot 2020-06-15 at 15 14 15](https://user-images.githubusercontent.com/24649833/84669684-0c177e00-af1d-11ea-8116-115093cd762d.png)
![Screenshot 2020-06-15 at 15 29 01](https://user-images.githubusercontent.com/24649833/84669694-0e79d800-af1d-11ea-9fe0-a01c73305b1b.png)

I entered an email and was able to go to checkout ok.

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:
​
- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)
​
If you confirm the bug, please provide us with clear steps to reproduce it.
​
I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.
