### ISSUE TITLE
HTML entities in product name not showing correctly in cart page

### ISSUE THREAD

**Issue by Konamiman** [woocommerce/woocommerce#26780]
**Describe the bug**

This is related to https://github.com/woocommerce/woocommerce/issues/25544. If a product has HTML entities such as `<` or `>` in its name it will not show correctly in the cart page.

**To Reproduce**

1. Create a product named _Product with < and >_, a simple product with any price will be enough.
2. Go to the store and put it in the cart.
3. Go to the cart page and see how it's displayed as _Product with_:

![image](https://user-images.githubusercontent.com/937723/84775345-6416b900-afdf-11ea-9358-97f878e26904.png)

Additionally, if you remove the product from the cart the message says _“Product with ” removed_:

![image](https://user-images.githubusercontent.com/937723/84775480-945e5780-afdf-11ea-9b0b-c11b587f8712.png)

**Expected behavior**

The product names should show correctly in the cart page even if they contain HTML entities.

**Isolating the problem (mark completed items with an [x]):**

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment]
Closed by #26885
