### ISSUE TITLE
Disabling Async Webhook send old information in order.update

### ISSUE THREAD

**Issue by Frisoni** [woocommerce/woocommerce#26787]
**Describe the bug**
If you disable async mode from webhook, when changing order status in woo order, at save webhook order.update fire with old status information.

**To Reproduce**

First, you need to disable async using filters.
add_filter('woocommerce_webhook_deliver_async','do_not_async_webhook');
function do_not_async_webhook(){
        return False;
}

1. Go to any order already created, lets say current status is on-hold
2. Change order status to Processing
3. Click update order button.
4. Checking webhook log (WP_DEBUG must bu true), in body content of webhook order status is on-hold, instead of send new order status processing.

Removing filter and processing webhook Async works fine.

**Expected behavior**
Even if webhook is not Async I expect to sent most updated order information.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://woocommerce-176158-1320703.cloudwaysapps.com
Site address (URL): https://woocommerce-176158-1320703.cloudwaysapps.com
WC Version: 4.2.0
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.3
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: –
Language: pt_BR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.3.19-1+0~20200612.60+debian8~1.gbp6c8fe1
PHP Post Max Size: 25 MB
PHP Time Limit: 180
PHP Max Input Vars: 2500
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.7.30
Max Upload Size: 25 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.0
WC Database Prefix: csc_
Tamanho total do banco de dados: 137.96MB
Tamanho dos dados do banco de dados: 95.63MB
Tamanho do índice do banco de dado: 42.33MB
csc_woocommerce_sessions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_woocommerce_api_keys: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
csc_woocommerce_attribute_taxonomies: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_woocommerce_downloadable_product_permissions: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
csc_woocommerce_order_items: Dados: 0.28MB + Índex: 0.11MB + mecanismo InnoDB
csc_woocommerce_order_itemmeta: Dados: 2.52MB + Índex: 3.03MB + mecanismo InnoDB
csc_woocommerce_tax_rates: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
csc_woocommerce_tax_rate_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
csc_woocommerce_shipping_zones: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_woocommerce_shipping_zone_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
csc_woocommerce_shipping_zone_methods: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_woocommerce_payment_tokens: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_woocommerce_payment_tokenmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
csc_woocommerce_log: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_actionscheduler_actions: Dados: 3.02MB + Índex: 0.89MB + mecanismo InnoDB
csc_actionscheduler_claims: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_actionscheduler_groups: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_actionscheduler_logs: Dados: 1.02MB + Índex: 1.47MB + mecanismo InnoDB
csc_adtribes_my_conversions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_aepc_custom_audiences: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_aepc_logs: Dados: 16.52MB + Índex: 0.00MB + mecanismo InnoDB
csc_aiowps_events: Dados: 2.52MB + Índex: 0.00MB + mecanismo InnoDB
csc_aiowps_failed_logins: Dados: 0.36MB + Índex: 0.00MB + mecanismo InnoDB
csc_aiowps_global_meta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_aiowps_login_activity: Dados: 0.17MB + Índex: 0.00MB + mecanismo InnoDB
csc_aiowps_login_lockdown: Dados: 0.05MB + Índex: 0.00MB + mecanismo InnoDB
csc_aiowps_permanent_block: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_cart_notices: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_commentmeta: Dados: 0.08MB + Índex: 0.11MB + mecanismo InnoDB
csc_comments: Dados: 1.52MB + Índex: 1.02MB + mecanismo InnoDB
csc_correios_postcodes: Dados: 0.23MB + Índex: 0.08MB + mecanismo InnoDB
csc_failed_jobs: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_links: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_mailchimp_carts: Dados: 0.05MB + Índex: 0.00MB + mecanismo InnoDB
csc_mailchimp_jobs: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_ms_snippets: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_options: Dados: 7.45MB + Índex: 0.28MB + mecanismo InnoDB
csc_postmeta: Dados: 12.52MB + Índex: 14.06MB + mecanismo InnoDB
csc_posts: Dados: 5.52MB + Índex: 1.25MB + mecanismo InnoDB
csc_queue: Dados: 0.52MB + Índex: 0.00MB + mecanismo InnoDB
csc_rank_math_404_logs: Dados: 0.13MB + Índex: 0.05MB + mecanismo InnoDB
csc_rank_math_internal_links: Dados: 0.05MB + Índex: 0.02MB + mecanismo InnoDB
csc_rank_math_internal_meta: Dados: 0.08MB + Índex: 0.00MB + mecanismo InnoDB
csc_rank_math_redirections: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_rank_math_redirections_cache: Dados: 0.08MB + Índex: 0.02MB + mecanismo InnoDB
csc_rank_math_sc_analytics: Dados: 18.55MB + Índex: 10.16MB + mecanismo InnoDB
csc_snippets: Dados: 0.05MB + Índex: 0.00MB + mecanismo InnoDB
csc_social_users: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_swift_performance_image_optimizer: Dados: 2.52MB + Índex: 0.52MB + mecanismo InnoDB
csc_swift_performance_warmup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
csc_termmeta: Dados: 0.11MB + Índex: 0.11MB + mecanismo InnoDB
csc_terms: Dados: 0.06MB + Índex: 0.03MB + mecanismo InnoDB
csc_term_relationships: Dados: 0.16MB + Índex: 0.13MB + mecanismo InnoDB
csc_term_taxonomy: Dados: 0.06MB + Índex: 0.06MB + mecanismo InnoDB
csc_tm_taskmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
csc_tm_tasks: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_uap_affiliates: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_affiliate_referral_users_relations: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_banners: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_campaigns: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_coupons_code_affiliates: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_cpm: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_dashboard_notifications: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_landing_commissions: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_mlm_relations: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_notifications: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_offers: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_offers_affiliates_reference: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_payments: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_ranks: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_ranks_history: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_referrals: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_ref_links: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_reports: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_visits: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_usermeta: Dados: 3.52MB + Índex: 6.03MB + mecanismo InnoDB
csc_users: Dados: 0.17MB + Índex: 0.14MB + mecanismo InnoDB
csc_wc_admin_notes: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_wc_admin_note_actions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_wc_category_lookup: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_wc_customer_lookup: Dados: 0.14MB + Índex: 0.09MB + mecanismo InnoDB
csc_wc_download_log: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
csc_wc_gpf_render_cache: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_wc_order_coupon_lookup: Dados: 0.05MB + Índex: 0.03MB + mecanismo InnoDB
csc_wc_order_product_lookup: Dados: 0.27MB + Índex: 0.30MB + mecanismo InnoDB
csc_wc_order_stats: Dados: 0.13MB + Índex: 0.14MB + mecanismo InnoDB
csc_wc_order_tax_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
csc_wc_product_meta_lookup: Dados: 0.27MB + Índex: 0.56MB + mecanismo InnoDB
csc_wc_tax_rate_classes: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_wc_webhooks: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_wfBlockedIPLog: Dados: 0.13MB + Índex: 0.00MB + mecanismo InnoDB
csc_wfBlocks7: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
csc_wfConfig: Dados: 0.52MB + Índex: 0.00MB + mecanismo InnoDB
csc_wfCrawlers: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_wfFileChanges: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_wfFileMods: Dados: 5.52MB + Índex: 0.00MB + mecanismo InnoDB
csc_wfHits: Dados: 1.52MB + Índex: 0.23MB + mecanismo InnoDB
csc_wfHoover: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_wfIssues: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
csc_wfKnownFileList: Dados: 3.52MB + Índex: 0.00MB + mecanismo InnoDB
csc_wfLiveTrafficHuman: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_wfLocs: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_wfLogins: Dados: 0.39MB + Índex: 0.14MB + mecanismo InnoDB
csc_wfls_2fa_secrets: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_wfls_settings: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_wfNotifications: Dados: 0.08MB + Índex: 0.00MB + mecanismo InnoDB
csc_wfPendingIssues: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
csc_wfReverseCache: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_wfSNIPCache: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
csc_wfStatus: Dados: 0.13MB + Índex: 0.09MB + mecanismo InnoDB
csc_wfTrafficRates: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_woocommerce_bundled_itemmeta: Dados: 0.13MB + Índex: 0.14MB + mecanismo InnoDB
csc_woocommerce_bundled_items: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
csc_woocommerce_gpf_google_taxonomy: Dados: 1.52MB + Índex: 0.00MB + mecanismo InnoDB
csc_yith_wcwl: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_yith_wcwl_lists: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB

### Post Type Counts ###

attachment: 1193
blocks: 116
boleto_reminder: 233
customize_changeset: 15
mc4wp-form: 1
nav_menu_item: 26
o-discount: 1
oembed_cache: 5
page: 14
popup: 11
popup_theme: 9
post: 1
product: 402
product_variation: 2482
revision: 713
shop_coupon: 46
shop_order: 876
shop_order_refund: 11
wafs: 2
wc_product_tab: 21
wpcf7_contact_form: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Mensagens de erro não devem ser mostradas para visitantes.

### Active Plugins (38) ###

Astro WooCommerce Free Gift: por AstroTemplates – 1.0.1 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.0
Editor clássico: por Colaboradores do WordPress – 1.5
Code Snippets: por Code Snippets Pro – 2.14.0
Debug Bar: por wordpressdotorg – 1.0.1
Disable Emails: por WebAware – 1.6.3
Duplicate Page: por mndpsingh287 – 4.2
Easy Theme and Plugin Upgrades: por Chris Jean – 2.0.1
Hide YouTube Related Videos: por SparkWeb Interactive
Inc. – 1.4.2

Indeed Ultimate Affiliate Pro: por indeed – 5.2
Kint Debugger: por Brian Fegter
Chris Dillon – 1.2

Loco Translate: por Tim Whitlock – 2.4.0
Regenerate Thumbnails: por Alex Mills (Viper007Bond) – 3.1.3
Rank Math SEO: por Rank Math – 1.0.44
WC Dias adicionais por produto: por Fernando Acosta – 1.4.8
WC Any Shipping Notify: por Fernando Acosta – 1.5.7
WC Lembrete de Boleto: por Fernando Acosta – 1.2.9
Calculadora de Frete otimizada no carrinho: por Fernando Acosta – 1.5.2 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.0
WC Simulador de Frete: por Fernando Acosta – 1.7.1
WC Simulador de parcelas e descontos: por Fernando Acosta – 1.6.9
WC Redução e restauração de estoque: por Fernando Acosta – 1.2.6
WC Tabela de Frete Offline: por Fernando Acosta – 1.4.3
Widgets in Menu for WordPress: por saurabhshukla
yapapaya – 1.0.0

Advanced Order Export For WooCommerce: por AlgolPlus – 3.1.4 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.0
Additional Variation Images Gallery for WooCommerce: por Emran Ahmed – 1.1.41 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.0
Variation Swatches for WooCommerce: por Emran Ahmed – 1.0.82 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.0
WooCommerce Advanced Free Shipping: por Jeroen Sormani – 1.1.4 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.0
WooCommerce Cart Notices: por SkyVerge – 1.11.4 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.0
WooCommerce Composite Products: por SomewhereWarm – 7.0.2
Claudio Sanches - Correios for WooCommerce: por Claudio Sanches – 3.8.0 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.0
WooCommerce Dynamic Pricing: por Lucas Stark – 3.1.19 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.0
Brazilian Market on WooCommerce: por Claudio Sanches – 3.7.2 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.0
WooCommerce Mix and Match Products: por Kathy Darling – 1.9.5 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.0
WooCommerce Product Bundles: por SomewhereWarm – 6.2.4
WooCommerce Google Product Feed: por Ademti Software Ltd. – 8.1.1 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.0
WooCommerce Tab Manager: por SkyVerge – 1.12.1 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.0
WooCommerce: por Automattic – 4.2.0
WP-Optimize - Clean, Compress, Cache: por David Anderson
Ruhani Rabin
Team Updraft – 3.1.2

REST API Log: por Pete Nelson – 1.6.7

### Inactive Plugins (18) ###

All In One WP Security: por Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.4.3

Contact Form 7: por Takayuki Miyoshi – 5.1.9
Contact Form 7 Extension For Mailchimp: por Renzo Johnson – 0.5.20
Facebook for WooCommerce: por Facebook – 1.11.4
Free Gift for WooCommerce: por Maxim – 0.0.2 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.0
Google Customer Reviews for WooCommerce: por eCreations – 2.6.12 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.0
Mailchimp for WooCommerce: por Mailchimp – 2.4.0 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.0
Pagar.me for WooCommerce: por Pagar.me
Claudio Sanches – 2.0.18 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.0

Popup Maker: por Popup Maker – 1.10.2
Rank Math Google Indexing API: por Rank Math – 1.2
Site Kit by Google: por Google – 1.9.0
Swift Performance: por SWTE – 2.1.8
WooCommerce Google Ads Conversion Tracking: por Wolf+Bär Agency – 1.6.5
WooCommerce Google Analytics Pro: por SkyVerge – 1.8.9 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.0
WooCommerce Product Stock Alert: por WC Marketplace – 1.6.1 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.0
WooCommerce Social Login: por SkyVerge – 2.8.6 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.0
Wootomation - Machine Learning AI: por Dragos Micu – 1.2.0 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.0
Wordfence Security: por Wordfence – 7.4.7

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: BRL (R$)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base da loja: #6 - /loja/
Carrinho: #7 - /carrinho/
Finalizar compra: #8 - /finalizar-compra/
Minha conta: #9 - /minha-conta/
Termos e condições: ❌ Página não definida

### Theme ###

Name: CSCLK - Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.11.3
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
csclk-flatsome-child/woocommerce/emails/customer-completed-order.php
csclk-flatsome-child/woocommerce/emails/customer-on-hold-order.php
csclk-flatsome-child/woocommerce/emails/customer-processing-order.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
csclk-flatsome-child/woocommerce/single-product/add-to-cart/variable.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
/home/176158.cloudwaysapps.com/zamnamjeum/public_html/wp-content/plugins/woo-variation-gallery/templates/product-images.php
/home/176158.cloudwaysapps.com/zamnamjeum/public_html/wp-content/plugins/woo-variation-gallery/templates/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

### WooCommerce Google Product Feed fields ###

Product description: Variation description only
fallback to main description (full preferred).

Availability: Defaults to "in stock".
Brand: Defaults to "Cuscoloko".
Manufacturer Part Number (MPN): Pre-populates from product sku.
Product Type: Pre-populates from product_cat taxonomy.
Google Product Category: 
Global Trade Item Number (GTIN): 
Size system: Defaults to "BR".

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send item_group_id: Enabled

### Composite Products ###

Database Version: 7.0.2
Template Overrides: –

### Product Bundles ###

Database Version: 6.2.4
Template Overrides: –

### Mix and Match Products ###

Template Overrides: –

### Action Scheduler ###

Cancelado: 10
Oldest: 2020-05-21 13:06:41 -0300
Newest: 2020-06-03 06:52:49 -0300

Concluído: 3.899
Oldest: 2020-05-16 14:13:40 -0300
Newest: 2020-06-16 14:06:02 -0300

Malsucedido: 1
Oldest: –
Newest: –

Pendente: 3
Oldest: 2020-06-16 14:13:53 -0300
Newest: 2020-06-22 17:30:09 -0300

`
</details>

**Comment by rrennick** [comment]
Hi @Frisoni ,  

Thank you for taking the time reporting this bug, we really appreciate your help. I can reproduce it on my end. 

I changed an order from on-hold to pending payment. The webhook delivered https://webhook.site/#!/6fda5bc5-58e8-47be-b9d5-56c35f352999/510918b0-a353-4289-a387-a6efeaff5ece/1

We’re going to solve this bug as soon as possible. Stay tuned for updates.
