### ISSUE TITLE
Local Pickup cost do not allow comma as decimal separator

### ISSUE THREAD

**Issue by ghost** [woocommerce/woocommerce#26785]
A customer noticed me the following error:

Notice: A non well formed numeric value encountered in /share/CACHEDEV1_DATA/Web/WordPress/wp-content/plugins/woocommerce/includes/class-wc-tax.php on line 173

After debuging a bit i noticed that a comma separated value was causing the error and found the place were was located.

To reproduce:

Create a taxable[ Local Pickup ](https://docs.woocommerce.com/document/local-pickup/) shipping method with a cost using a comma separated value like 3,31, save the changes and then add a product to the cart. It produces the mentioned error and the shipping amount displayed is incorrect.

**Screenshots**
Box values: Local Pickup, Taxable, 3,31

![local_pickup](https://user-images.githubusercontent.com/67015189/84800489-31c88400-affe-11ea-8705-1fb0c168c25b.jpg)

**Expected behavior**
Since the selected decimal separator in WooCommerce configuration is a comma "," this cost has to be stored correctly.

**EDITED:** 

After watching the code i see that WC do nothing to the cost variable in calculate_shipping function located at class-wc-shipping-local-pickup file, but it does in the flate rate class.

At least you could mention that users must use dot as a separator. If users dosen't see the error then passing a comma separated values calculates a wrong tax and adds a wrong shipping costs,and that is wrong alltheway.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment]
Closing as I was wasn't able to reproduce and author's account has been deleted on GitHub

**Comment by therealninot** [comment]
¿How can you close this? ¿Cannot reproduce? ¿Are you a newebie or something?¿Is Woocommerce a serious plugin or we have to migatre all our customers sites most of them using wc and WMPL? that one have some yeraly costs.

Please take this seriously, because you didn't even try to put a decimal comma separated value and didn't even read my report..

Like at the highschool, do you see the difference? Do you see? So there is the error.

Function in local pickup:
`	public function calculate_shipping( $package = array() ) {
		$this->add_rate(
			array(
				'label'   => $this->title,
				'package' => $package,
				'cost'    => $this->cost,
			)
		);
	}`
Function in flat rate, oooooo is calling a function named evaluate_cost, to convert correctly:
`	/**
	 * Calculate shipping.
	 *
	 * @param array $package (default: array()).
	 */
	public function calculate_shipping( $package = array() ) {
		$rate = array(
			'id'      => $this->id,
			'label'   => $this->title,
			'cost'    => 0,
			'package' => $package,
		);

		// Calculate the costs.
		$has_costs = false; // True when a cost is set. False if all costs are blank strings.
		$cost      = $this->get_option( 'cost' );

		if ( '' !== $cost ) {
			$has_costs    = true;
			$rate['cost'] = $this->evaluate_cost(
				$cost,
				array(
					'qty'  => $this->get_package_item_qty( $package ),
					'cost' => $package['contents_cost'],
				)
			);
		}

		// Add shipping class costs.
		$found_shipping_classes = $this->find_shipping_classes( $package );
		$highest_class_cost     = 0;

		foreach ( $found_shipping_classes as $shipping_class => $products ) {
			// Also handles BW compatibility when slugs were used instead of ids.
			$shipping_class_term = get_term_by( 'slug', $shipping_class, 'product_shipping_class' );
			$class_cost_string   = $shipping_class_term && $shipping_class_term->term_id ? $this->get_option( 'class_cost_' . $shipping_class_term->term_id, $this->get_option( 'class_cost_' . $shipping_class, '' ) ) : $this->get_option( 'no_class_cost', '' );

			if ( '' === $class_cost_string ) {
				continue;
			}

			$has_costs  = true;
			$class_cost = $this->evaluate_cost(
				$class_cost_string,
				array(
					'qty'  => array_sum( wp_list_pluck( $products, 'quantity' ) ),
					'cost' => array_sum( wp_list_pluck( $products, 'line_total' ) ),
				)
			);

			if ( 'class' === $this->type ) {
				$rate['cost'] += $class_cost;
			} else {
				$highest_class_cost = $class_cost > $highest_class_cost ? $class_cost : $highest_class_cost;
			}
		}

		if ( 'order' === $this->type && $highest_class_cost ) {
			$rate['cost'] += $highest_class_cost;
		}

		$rate['package'] = $package;

		// Add the rate.
		if ( $has_costs ) {
			$this->add_rate( $rate );
		}

		/**
		 * Developers can add additional flat rates based on this one via this action since @version 2.4.
		 *
		 * Previously there were (overly complex) options to add additional rates however this was not user.
		 * friendly and goes against what Flat Rate Shipping was originally intended for.
		 *
		 * This example shows how you can add an extra rate based on this flat rate via custom function:
		 *
		 *      add_action( 'woocommerce_flat_rate_shipping_add_rate', 'add_another_custom_flat_rate', 10, 2 );
		 *
		 *      function add_another_custom_flat_rate( $method, $rate ) {
		 *          $new_rate          = $rate;
		 *          $new_rate['id']    .= ':' . 'custom_rate_name'; // Append a custom ID.
		 *          $new_rate['label'] = 'Rushed Shipping'; // Rename to 'Rushed Shipping'.
		 *          $new_rate['cost']  += 2; // Add $2 to the cost.
		 *
		 *          // Add it to WC.
		 *          $method->add_rate( $new_rate );
		 *      }.
		 */
		do_action( 'woocommerce_flat_rate_shipping_add_rate', $this, $rate );
	}`



Please, some real programmer take this project that is full of bugs, more than 20 i found yesterday and i'll not publish them since i see you d'ont even care.

It's incredible tthat you need to apply 4 functions to get a wellformatted decimal, just store de fucking numbers as numbers.

`		// Remove whitespace from string.
		$sum = preg_replace( '/\s+/', '', $sum );

		// Remove locale from string.
		$sum = str_replace( $decimals, '.', $sum );

		// Trim invalid start/end characters.
		$sum = rtrim( ltrim( $sum, "\t\n\r\0\x0B+*/" ), "\t\n\r\0\x0B+-*/" );`

So there is the BUUUUUUGGGGGGG you, now you see it?

**Comment by P4KM4N** [comment]
I have this bug too. I try to set the cost to 3.50, but it refuse to accept decimal

<img width="1100" height="849" alt="Image" src="https://github.com/user-attachments/assets/d018788e-e9fa-4058-9880-1af32759bf07" />
