### ISSUE TITLE
Wrong method ID stored when adding multiple shipping rates

### ISSUE THREAD

**Issue by mikesies** [woocommerce/woocommerce#26795]
I can't figure out if this is expected behaviour or a bug, but it seems a bug to me. Apologies if this is expected behaviour.

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate
- [x] The issue still exists against the latest `master` branch of WooCommerce on Github (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Create a custom shipping class
2. Add multiple rates in calculate_shipping() through $this->add_rate()
3. Place an order. 

## Expected/actual behavior

I expect the order to be placed with the details from add_rate() like:

`            $rate = array(
                'id' => $my_custom_id,
                'label' => $my_custom_label,
                'cost' =>$my_custom_price,
            );`

The order is actually placed like:

`            $rate = array(
                'label' => $my_custom_label,
                'cost' =>$my_custom_price,
            );`

and the ID is used from the shipping class constructor.

The ID in add_rate() seems to be ignored.

## Isolating the problem

- [x] This bug happens with only WooCommerce plugin active
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/)
- [x] I can reproduce this bug consistently using the steps above

## WordPress Environment

<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://localhost:8080
Site address (URL): http://localhost:8080
WC Version: 4.2.0
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.3
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.38 (Debian)
PHP Version: 7.3.9
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1c

SUHOSIN Installed: –
MySQL Version: 5.7.27
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.0
WC Database Prefix: wp_
Total Database Size: 3.55MB
Database Data Size: 2.11MB
Database Index Size: 1.44MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 5
nav_menu_item: 5
page: 7
post: 2
product: 12
product_variation: 1
revision: 3
shop_order: 10

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (5) ###

Invition Print & Ship Zakeke: by Invition – 1.3
Invition Print & Ship: by Invition – 1.10 – Installed version not tested with active version of WooCommerce 4.2.0
Invition Wordpress Tools: by Invition – 1.0
Product Input Fields for WooCommerce: by Tyche Softwares – 1.2.6 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce: by Automattic – 4.2.0

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
instock (instock)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: ❌ Page not set
Cart: #25 - /?page_id=25
Checkout: #28 - /?page_id=28
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Nineteen
Version: 1.6
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Pending: 15
Oldest: 2020-04-06 11:26:06 +0000
Newest: 2020-06-17 13:16:57 +0000

`
```
</details>

**Comment by rrennick** [comment]
@mikesies Thanks for contacting us.

> I can't figure out if this is expected behaviour or a bug, but it seems a bug to me. Apologies if this is expected behaviour.

What's stored in the order meta is the shipping method ID vs the shipping class ID. If you create an order through the admin interface, choose your custom shipping class in the Shipping Method dropdown, it is the same as manually entering the shipping description and leaving the method dropdown on `N/A`:

<img width="708" alt="Screen Shot 2020-06-18 at 4 47 20 PM" src="https://user-images.githubusercontent.com/343847/85065406-7b8ea700-b183-11ea-88f1-fa1e49409384.png">

**Comment by mikesies** [comment]
Hi rrennick,

Thanks for your answer! I think I've used the wrong words to explain what I mean. I've made a custom shipping method like this:

https://docs.woocommerce.com/document/shipping-method-api/

Then in the calculate_shipping() function i've added multiple rates with their own ID through add_rate()

when one of the rates is ordered, it is stored with the ID from the __construct() function instead of the ID used in add_rate().

The ID used in add_rate() is not used and not stored as far as I can see. The code always uses the ID from the __construct() class.

I can share my full code if that makes it more clear

**Comment by rrennick** [comment]
> I can share my full code if that makes it more clear

@mikesies That would  make it easier to diagnose.

**Comment by mikesies** [comment]
This is my shipping class. As you can see the class can result in one or multiple rates being added. No matter which rate is being ordered, the shipment is always stored with the ID print_and_ship_auto while we want it to be stored with the ID from the add_rate class (e.g. print_and_ship_normal or print_and_ship_tracked.

This because our plugin fetches this result later and automatically handles the order.

`<?php
/**
 * WC_Shipping_PrintAndShip_Auto class.
 *
 * @category Class
 * @package  Shipping-for-WooCommerce/Classes
 * @author   Mike Sies <mike@studiogewaagd.nl>
 */

namespace PrintAndShip;

class WC_Shipping_PrintAndShip_Auto extends \WC_Shipping_Method
{

    /**
     * Constructor. The instance ID is passed to this.
     */
    public function __construct( $instance_id = 0 ) 
    {
        $this->id                 = 'print_and_ship_auto';
        $this->instance_id        = absint($instance_id);
        $this->method_title       = __('Invition - Automatic shipping calculator');
        $this->method_description = __(
            'This shipment will check the contents of the cart 
            and the shipment destination and calculate shipping through 
            the Partner API based on the latest Invition rates.'
        );
        $this->supports = array(
            'shipping-zones',
            'instance-settings',
        );
        $this->instance_form_fields = array(
            'enabled' => array(
                'title'   => __('Enable'),
                'type'    => 'checkbox',
                'label'   => __('Enable this shipping method'),
                'default' => 'yes',
            ),
        );
        $this->enabled = $this->get_option('enabled');
        $this->title   = 'Automatic Shipping Calculator';

        add_action('woocommerce_update_options_shipping_' . $this->id, array( $this, 'process_admin_options'));
    }
    
    /**
     * Add the shipping rate chosen by the user
     *
     * @param mixed $package Not sure what this does
     * 
     * @return void
     */
    public function calculate_shipping($package = array()) // WIP
    {
        $orderLines = array();
        
        // Map the order lines
        foreach ($package['contents'] as $product) {
            $print_and_ship_sku = "";
            $print_and_ship_sku = get_post_meta($product['product_id'], 'print_and_ship_sku', true);

            // It's not an Invition product
            if ($print_and_ship_sku == "") {
                continue;
            }

            // We have a match, add to array
            $orderLines[] = array(
                'quantity' => $product['quantity'],
                'item_sku' => $print_and_ship_sku,
            );
        }

        // No Invition products found
        if (count($orderLines) == 0) {
            debuglog('no invition products found');
            return;
        }

        // Map the address
        $address = array(
            'streetname'      => $package['destination']['address'],
            'city'            => $package['destination']['city'],
            'zipcode'         => $package['destination']['postcode'],
            'country_code'    => $package['destination']['country'],
        );
        
        // Merge it all in one array
        $data = array(
            'address'       => $address,
            'lines'         => $orderLines,
            'shipping_kind' => 'dropship',
        );

        // Request the actual quote
        $ipp = new \PrintAndShip\IPP();
        $quote = $ipp->requestQuote($data);

        // No shipping options received.
        if (!$quote) {
            debuglog('No options received');
            return false;
        }

        // Set the default names
        $methodNames = array(
            'normal'  => __('Regular mail (no tracking)'),
            'tracked' => __('Tracked mail'),
            'premium' => __('Premium shipment (with track and trace)'),
        );

        $minimumShippingLevel = get_option('print_and_ship_shipping_minimal_level');

        // Make a shipping rate for each result
        foreach ($quote->shipping_options as $option) {

            // A minimum level was set in the settings, is the option higher then the minimum level?
            if ($minimumShippingLevel != '') {
                
                switch ($minimumShippingLevel) {
                case 'tracked':
                    if ($option->level == 'normal') {
                        continue 2;
                    }
                    break;
                case 'premium':
                    if ($option->level == 'normal' || $option->level == 'tracked') {
                        continue 2;
                    }
                    break;
                }
            }

            $rate = array(
                'id' => 'print_and_ship_' . $option->level,
                'label' => $methodNames[$option->level],
                'cost' => $option->price,
            );
    
            // Register the rate
            $this->add_rate($rate);
        }
    }
}
`

**Comment by rrennick** [comment]
> I've made a custom shipping method like this:
> https://docs.woocommerce.com/document/shipping-method-api/

@mikesies I tested the example method and it does save the method ID

```
mysql> select * from wp_woocommerce_order_itemmeta where order_item_id = 5031;
+---------+---------------+-------------+----------------------------------------+
| meta_id | order_item_id | meta_key    | meta_value                             |
+---------+---------------+-------------+----------------------------------------+
|   48257 |          5031 | method_id   | your_shipping_method                   |
|   48258 |          5031 | instance_id | 0                                      |
|   48259 |          5031 | cost        | 01                                     |
|   48260 |          5031 | total_tax   | 10                                     |
|   48261 |          5031 | taxes       | a:1:{s:5:"total";a:1:{i:18;s:2:"10";}} |
+---------+---------------+-------------+----------------------------------------+
```

There may be something else in your install that is preventing it from being saved.

**Comment by mikesies** [comment]
Yes I know, but that is the ID set in the __construct() function. 

If you set a different ID in the add_rate() function, it is ignored.

**Comment by rrennick** [comment]
> If you set a different ID in the add_rate() function, it is ignored.

Can you clarify if you are having no `method_id` row stored?

**Comment by rrennick** [comment]
@mikesies It looks like the sample in the documentation is misleading. The method ID isn't taken from the array passed to `add_rate()` - https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-shipping-method.php#L265:L282

**Comment by mikesies** [comment]
Hi @rrennick 

Thanks. That is exactly what I meant. 

Is that something that could / should be changed in an update? Or does that have any other implications that I'm not aware of?

**Comment by rrennick** [comment]
> Is that something that could / should be changed in an update?

We wouldn't change something like this unless there was a significant demand for it.

**Comment by mikesies** [comment]
Well that's too bad, but I understand. Thanks for helping investigate this.

Would you by any chance have a workaround to store an identifier for later in this function?

**Comment by rrennick** [comment]
> Would you by any chance have a workaround to store an identifier for later in this function?

You can add it to the `meta_data`.

**Comment by mikesies** [comment]
Amazing, that's even better. Rebuilt the feature and works like a charm. Thanks for the support. 

Maybe the documentation can be a bit improved on this. I discovered that the ID added to add_rate is required if you add multiple rates, if the ID from the construct is used only the last added rate is shown. If a unique ID is entered, all rates are shown but the ID is never stored. That was what confused me and might be confusing to others.
