### ISSUE TITLE
Form Shrinks on Checkout Page

### ISSUE THREAD

**Issue by shubhamshashank** [woocommerce/woocommerce#26803]
![Capture](https://user-images.githubusercontent.com/64638247/84937049-cdd6b600-b0f8-11ea-8966-034165570346.PNG)
![1](https://user-images.githubusercontent.com/64638247/84937225-0d9d9d80-b0f9-11ea-96fa-feea61d2dbf2.PNG)

**Comment by tammullen** [comment]
Hi @shubhamshashank ,
We are closing your issue in favor of the previously submitted https://github.com/woocommerce/woocommerce/issues/26789. Please continue sharing your feedback there if needed.
