### ISSUE TITLE
Can no longer modify v2 legacy API output with the 'woocommerce_rest_prepare_shop_order_object' hook

### ISSUE THREAD

**Issue by pixelwatt** [woocommerce/woocommerce#26800]
**Describe the bug**
I can no longer modify output from the v2 legacy API using the 'woocommerce_rest_prepare_shop_order_object' hook. Modifications to the $response object are no longer reflected in the actual API response.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://www.boulderblooms.com
Site address (URL): https://www.boulderblooms.com
WC Version: 4.1.1
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.1.3
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.18-1+ubuntu18.04.1+deb.sury.org+1
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.58.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.7.29-32-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.1.1
WC Database Prefix: wp_
Total Database Size: 29.36MB
Database Data Size: 18.67MB
Database Index Size: 10.69MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.14MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 1.52MB + Index: 0.78MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.28MB + Index: 0.31MB + Engine InnoDB
wp_itsec_distributed_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_lockouts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_itsec_logs: Data: 2.52MB + Index: 0.23MB + Engine InnoDB
wp_itsec_mutexes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_opaque_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_temp: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_itsec_user_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_iwp_backup_status: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_iwp_file_list: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_iwp_processed_iterator: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nf3_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_action_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_nf3_chunks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_field_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_nf3_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_object_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf3_upgrades: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 6.48MB + Index: 6.88MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.38MB + Engine InnoDB
wp_redirection_404: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_indexable: Data: 0.48MB + Index: 0.13MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 508
customize_changeset: 1
global_product_addon: 1
growers: 4
iwp_log: 1
locations: 2
nav_menu_item: 23
nf_sub: 184
page: 9
post: 3
product: 111
product_variation: 68
revision: 37
shop_coupon: 5
shop_order: 1295
shop_order_refund: 31

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

ManageWP - Worker: by GoDaddy – 4.9.6
BackupBuddy: by iThemes – 8.5.7.0
Classic Editor: by WordPress Contributors – 1.5
CMB2 Roadway Segments: by Rob Clark – 0.9.81
CMB2: by CMB2 team – 2.7.0
iThemes Security Pro: by iThemes – 6.6.0
Jetpack by WordPress.com: by Automattic – 8.5
Ninja Forms - Mail Chimp: by The WP Ninjas – 3.1.11
Ninja Forms - Layout & Styles: by The WP Ninjas – 3.0.28
Ninja Forms: by Saturday Drive – 3.4.24.3
Front Page Alert: by Rob Clark – 0.9.0
Redirection: by John Godley – 4.8
Simple Custom Post Order: by Colorlib – 2.5.0
WooCommerce Authorize.Net Gateway: by SkyVerge – 3.2.6 (update to version 3.2.7 is available)
WooCommerce Product Add-ons: by WooCommerce – 3.0.33 (update to version 3.0.34 is available)
WooCommerce Services: by Automattic – 1.23.0 (update to version 1.23.2 is available) – Installed version not tested with active version of WooCommerce 4.1.1
WooCommerce: by Automattic – 4.1.1 (update to version 4.2.0 is available)
Yoast SEO: by Team Yoast – 14.2

### Inactive Plugins (1) ###

Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.3

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached Redux

### Must Use Plugins (5) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.6.4
ManageWP - Worker Loader: by GoDaddy –
WP Engine Seamless Login Plugin: by WP Engine – 1.5.5
WP Engine Security Auditor: by wpengine – 1.0.9
WP Engine System: by WP Engine – 4.0.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #86 - /shop/
Cart: #87 - /cart/
Checkout: #88 - /checkout/
My account: #89 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Boulder Blooms
Version: 1.0.8
Author URL: https://pixelwatt.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: –

### Authorize.Net Credit Card ###

Environment: Production
Tokenization Enabled: –
Debug Mode: Off
Webhooks Enabled: ❌
						Not generated

### Action Scheduler ###

Complete: 183
Oldest: 2020-05-21 15:31:19 -0600
Newest: 2020-06-17 10:16:01 -0600

`
</details>

**Comment by tammullen** [comment]
Hi @pixelwatt 

The legacy API v2 you're referring to is is deprecated and will be removed at some point. We're keeping it around only for backwards compatibility reasons. We suggest moving to the new REST API, which gets further updates going forward. I'm sorry, but we won't be fixing bugs in this API version anymore.

I am closing this issue for now as a result. If I missed something, please leave a comment and we will take a second look.

**Comment by pixelwatt** [comment]
@tammullen At the very least, can you change the "product_meta" key back to "order_meta"? Given that random change and the fact that it can no longer be undone through hooks, the integration we rely on is broken along with what I imagine are many others. I get the fact that legacy features need to be phased out, but changing something like that and allowing the methods to revert it to no longer function is not ideal, and kind of defeats the point of even keeping the APIs active for backwards compatibility. Our integration is in the process of adding support for the new API, but I need something functional until then, and doubt I'm alone.

**Comment by pixelwatt** [comment]
Any update on whether or not "product_meta" can be changed back to "order_meta"?

**Comment by pixelwatt** [comment]
@tammullen Any updates at all? A client's integration is broken and can no longer be fixed via code, a situation I imagine many other devs are experiencing.
