### ISSUE TITLE
Zone Regions: United Kingdom (UK) missing on new installs.

### ISSUE THREAD

**Issue by gilesholder** [woocommerce/woocommerce#26810]
**Describe the bug**
I have just set up a new site with a fresh install of WordPress/WooCommerce. Upon trying to setup Shipping Zones I have discovered that the United Kingdom is now missing from the "Zone Regions" field. I have checked against an existing working site and its there. Seems to only affect new installs.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use a fresh install/setup of WC
2. In Shipping Zones under Shipping try to set "United Kingdom" as the zone.
3. No results found.

**Screenshots**
New Install Missing UK: **https://ibb.co/f4QKqhq**
Old Install With UK: **https://ibb.co/j9YxBWG**

**Expected behaviour**
For UK to be a selectable shipping zone/region.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
PHP 7.3
Latest WooCommerce
Latest WordPress
Elementor Free & Pro (should not interfere)
Blank Install/Setup
```

**Comment by tammullen** [comment]
Hi @gilesholder 

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end and I can see the UK listed in version 4.2 and 4.3 Beta
​
![Screenshot 2020-06-18 at 17 34 03](https://user-images.githubusercontent.com/24649833/85048132-c829b080-b18a-11ea-8552-5d4ea73cccdd.png)
![Screenshot 2020-06-18 at 17 34 56](https://user-images.githubusercontent.com/24649833/85048134-c9f37400-b18a-11ea-97c0-8292582e8d9b.png)

Can you ​provide The System Status Report which is found in your WordPress admin under **WooCommerce > Status**. Please select “Get system report”, then “Copy for support"

This will allow us to evaluate this issue further.

**Comment by gilesholder** [comment]
Hi there, I just reset the database to a clean install and it now works perfectly. Guessing this was an install glitch which has resolved itself on a rebuild. I will close this case.
