### ISSUE TITLE
Product shortcode does not work within template file 

### ISSUE THREAD

**Issue by rufus100** [woocommerce/woocommerce#26836]
The shortcode for displaying a single product does not work fully when placed within the template file using `<?php echo do_shortcode('[product_page id="65"]');?>`

When using this method, the image gallery does not work since the Photoswipe css and js files are not in the `<head>` of the page.

When the shortcode is placed in the Wordpress content field, it works fine. However, placing it in a custom field also breaks the gallery.

Here you can see how the gallery behaves when the shortcode is echoed using php in a storefront theme with no plugins activated apart from WooCommerce: https://nutrivy.staging.wpengine.com/faqs/

### WordPress Environment ###

WordPress address (URL): https://nutrivy.staging.wpengine.com
Site address (URL): https://nutrivy.staging.wpengine.com
WC Version: 4.2.0
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.3
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.18-1+ubuntu18.04.1+deb.sury.org+1
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
cURL Version: 7.58.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.7.29-32-log
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.0
WC Database Prefix: wp_
Total Database Size: 6.60MB
Database Data Size: 4.43MB
Database Index Size: 2.17MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_lightbox_photoswipe_img: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nextend2_image_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nextend2_section_storage: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nextend2_smartslider3_sliders: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
wp_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nextend2_smartslider3_slides: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_options: Data: 2.45MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.45MB + Index: 0.22MB + Engine InnoDB
wp_posts: Data: 0.23MB + Index: 0.06MB + Engine InnoDB
wp_redirection_404: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

acf-field: 18
acf-field-group: 3
ambassador: 5
attachment: 73
customize_changeset: 96
nav_menu_item: 6
page: 13
popup: 1
popup_theme: 6
post: 8
product: 1
revision: 11
shop_coupon: 39
shop_order: 13
sp_pcp_shortcodes: 1
wcb: 7
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.2.0

### Inactive Plugins (35) ###

Advanced Custom Fields: by Elliot Condon – 5.8.12
Advanced Custom Fields PRO: by Elliot Condon – 5.8.11
Analytify - Google Analytics Dashboard: by Analytify – 3.0.0
Bootstrap 3 Shortcodes: by Michael W. Delaney
Filip Stefansson
and Simon Yeldon – 3.3.12

Ci WooCommerce Product Gallery Slider: by codeixer – 2.0.3 – Installed version not tested with active version of WooCommerce 4.2.0
Classic Editor: by WordPress Contributors – 1.5
Contact Form 7: by Takayuki Miyoshi – 5.1.9
Coupon Box for WooCommerce: by VillaTheme – 2.0.1.5 – Installed version not tested with active version of WooCommerce 4.2.0
Custom Product Tabs for WooCommerce: by YIKES
Inc. – 1.7.1 – Installed version not tested with active version of WooCommerce 4.2.0

Email Templates: by Damian Logghe – 1.3.1.2
Facebook for WooCommerce: by Facebook – 1.11.4
Google Ads for WooCommerce: by Kliken – 1.0.4 – Installed version not tested with active version of WooCommerce 4.2.0
Google XML Sitemaps: by Arne Brachhold – 4.1.0
HubSpot All-In-One Marketing - Forms, Popups, Live Chat: by HubSpot – 7.34.4
Insert Headers and Footers: by WPBeginner – 1.4.5
Integration with HubSpot for WooCommerce: by MakeWebBetter – 4.0.1 – Installed version not tested with active version of WooCommerce 4.2.0
Jetpack by WordPress.com: by Automattic – 8.6.1
Kadence WooCommerce Email Designer: by Kadence WP – 1.4.1 – Installed version not tested with active version of WooCommerce 4.2.0
Lightbox with PhotoSwipe: by Arno Welzel – 3.0.3
Mailchimp for WooCommerce: by Mailchimp – 2.4.1 – Installed version not tested with active version of WooCommerce 4.2.0
Maintenance: by WP Maintenance – 3.90
Min and Max Quantity for WooCommerce: by BeRocket – 1.2.13.1 – Installed version not tested with active version of WooCommerce 4.2.0
myStickymenu: by Premio – 2.4.2
Popup Maker: by Popup Maker – 1.10.2
Post Carousel Pro: by ShapedPlugin – 1.2.14
Reading Time WP: by Jason Yingling – 2.0.9
Redirection: by John Godley – 4.8
Simple Lightbox: by Archetyped – 2.8.1
Smart Slider 3: by Nextend – 3.4.1.8
Trustpilot-reviews: by Trustpilot – 2.5.807 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Coupon Generator: by Jeroen Sormani – 1.1.0 – Installed version not tested with active version of WooCommerce 4.2.0
WooCommerce Direct Checkout: by QuadLayers – 2.3.8
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.9.2

WooCommerce Services: by Automattic – 1.23.2
WooCommerce Stripe Gateway: by WooCommerce – 4.4.0 – Installed version not tested with active version of WooCommerce 4.2.0

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (5) ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.6.4
post-type.php: by  –
WP Engine Seamless Login Plugin: by WP Engine – 1.5.5
WP Engine Security Auditor: by wpengine – 1.0.9
WP Engine System: by WP Engine – 4.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #60 - /shop/
Cart: #61 - /cart/
Checkout: #62 - /checkout/
My account: #63 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.5 (update to version 2.5.7 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 191
Oldest: 2020-05-28 15:05:58 +0000
Newest: 2020-06-22 12:40:05 +0000

Pending: 1
Oldest: 2020-06-22 12:41:05 +0000
Newest: 2020-06-22 12:41:05 +0000

Canceled: 1
Oldest: 2020-05-27 13:28:59 +0000
Newest: 2020-05-27 13:28:59 +0000

`

**Comment by rrennick** [comment]
This looks like it's the same issue as #26962. I've started the discussion on that issue so will close this one. Please follow along on #26962.
