### ISSUE TITLE
Add filter for wc_help_tip strings

### ISSUE THREAD

**Issue by ninetyninew** [woocommerce/woocommerce#26830]
**Describe the solution you'd like**
Add a filter to wc_help_tip to allow developers to amend help tip strings:
https://docs.woocommerce.com/wc-apidocs/source-function-wc_help_tip.html#1397-1414

e.g. If you have a custom wc_order_is_editable filter which makes the order non-editable for a specific condition the help tip reads "To edit this order change the status back to "Pending", that may not apply when taking into account the new condition so a new wc_help_tip filter would mean this could be updated to instruct the user better.

**Comment by claudiosanches** [comment]
Hello @ninetyninew,

Thank you for taking the time to share this idea, we really appreciate your help.

> e.g. If you have a custom wc_order_is_editable filter which makes the order non-editable for a specific condition the help tip reads "To edit this order change the status back to "Pending", that may not apply when taking into account the new condition so a new wc_help_tip filter would mean this could be updated to instruct the user better.

In fact there's other ways to solve it like by changing with JavaScript, also it's possible to filter any strings on WordPress with the `gettext` filter.

A new filter to change the value of help tips isn't something that we should consider including any time soon, note that also we plan to update our admin interfaces, and probably we'll remove those help tips.

So while we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look.
