### ISSUE TITLE
Make cart error notice behavior consistent with checkout error notices

### ISSUE THREAD

**Issue by ObliviousHarmony** [woocommerce/woocommerce#26856]
**Is your feature request related to a problem? Please describe.**

If a notice is generated during the cart's shipping calculator update, it isn't always obvious to the user that something went wrong. Using WCS with automated taxes, try entering an address in Washington with the zip code 94110. An error generated by the automated taxes will be placed at the top of the screen after updating, but if you haven't scrolled high enough, you won't see it. If you proceed to checkout it will lead to the `cart-errors.php` template file instead of highlighting the error to the user immediately.

**Describe the solution you'd like**

Currently the checkout page scrolls to the top in the above error case. I would propose that the cart page be consistent and scroll to the top when a cart error is encountered in this case. In addition if there is an error, attempting to proceed to checkout should just scroll to the top as well.

**Describe alternatives you've considered**

Since this is caused by an AJAX action technically we might put an error in the box itself, but since there's just a notice being generated, it would be difficult to filter out where what error belongs. It is a bit simpler to just have this consistent behavior for all notices during cart usage.

**Comment by pmcpinto** [comment]
Hey Christopher, 

Thank you for taking the time to share this idea. We appreciate your help, and we're sorry for the late reply. While this is very helpful, it doesn’t fit our current priorities, as our team is currently focused on the [Cart and Checkout experience powered by blocks](https://github.com/woocommerce/woocommerce-blocks/tree/trunk/docs/third-party-developers/extensibility). We'll revisit the list of suggestions like this one once our priorities are updated. In the meantime, we'll review this behavior in the blocks experience.
