### ISSUE TITLE
Help Site is not loading

### ISSUE THREAD

**Issue by davidain** [woocommerce/woocommerce#26852]
Ok so here is the link to my site, it is not working because of woocommerce issues. I need help now! My site is supposed to go live tomorrow! I turned on the debugging  code to specifically identify what the problem is.

site: www.ashtonandashleyshome.com   ( Click on Log In as site owner)

Warning: include_once(/var/www/wp-content/plugins/woocommerce/packages/action-scheduler/action-scheduler.php): failed to open stream: No such file or directory in /var/www/wp-content/plugins/woocommerce/includes/class-woocommerce.php on line 451

Warning: include_once(): Failed opening '/var/www/wp-content/plugins/woocommerce/packages/action-scheduler/action-scheduler.php' for inclusion (include_path='.:/opt/remi/php73/root/usr/share/pear:/opt/remi/php73/root/usr/share/php:/usr/share/pear:/usr/share/php') in /var/www/wp-content/plugins/woocommerce/includes/class-woocommerce.php on line 451

Warning: require_once(/var/www/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Package.php): failed to open stream: No such file or directory in /var/www/wp-content/plugins/jetpack/vendor/autoload_packages.php on line 168

Fatal error: require_once(): Failed opening required '/var/www/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Package.php' (include_path='.:/opt/remi/php73/root/usr/share/pear:/opt/remi/php73/root/usr/share/php:/usr/share/pear:/usr/share/php') in /var/www/wp-content/plugins/jetpack/vendor/autoload_packages.php on line 168
There has been a critical error on your website. Please check your site admin email inbox for instructions.

**Comment by juliaamosova** [comment]
Hi @davidain,

Thanks for raising the issue. A bit more details will be helpful. What version of WooCommerce are you using? What causes these errors? In other words, what actions/steps do you take on the site before you see these errors?

**Comment by davidain** [comment]
Yes I am using Wordpress version 5.4.2 and Woocommerce version 4.2.2, Right now everything is working and in order to fix it I had to uninstall the plugin and reinstall it, which also means the problem could happen again.

**Comment by davidain** [comment]
> Hi @davidain,
> 
> Thanks for raising the issue. A bit more details will be helpful. What version of WooCommerce are you using? What causes these errors? In other words, what actions/steps do you take on the site before you see these errors?
