### ISSUE TITLE
Webhook not firing when there is an Action Schedule running for the same Order Id

### ISSUE THREAD

**Issue by Frisoni** [woocommerce/woocommerce#26851]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Every order update should fire a webhook for order.update.
If this is done scheduling an action, when an action is already set for this order id a new one is NOT created, and thats ok if the schedule is waiting to run as it will read last order info on run.
But, if order update schedule is already running, the new update schedule should be created to send the new information, this is not happening.

**Expected behavior**
Order update cannot miss firing new info.

**Actual behavior**
When there are too close order updates, last info is no firing webhook.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
All my cases in production are because of very fast integration with my payment gateway.
To reproduce manually we need a slow webhook to respond.
1. Created a webhook in webhook.site seting Time before respond to 10 seconds (maximum allowed)
2. Create a webhook in woo for order update poiting to this webhook.site link.
3. Enter on any order in Woo and changed status from pending to on-hold and Save order.
4. On Action Schedule there is not a schedule action woocommerce_deliver_webhook_async waiting to run
5. Refresh page until woocommerce_deliver_webhook_async action start to run.
6. When started, before webhook respond (you have 10 seconds) go to order and change status to processing
7. In this point, webhook already sent on-hold info to webhook.site, but a NEW webhook for processing will not be created because already exists an action with the same arg, even if this action is already running.
8. in this scenario, the last info received by webhook.site will be on-hold.

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

Obs.:
I've already comment about this bug in this another open issue, but I started this new one to make it clear how to reproduce the bug.
https://github.com/woocommerce/woocommerce/issues/26612#issuecomment-644706332

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): https://www.cuscoloko.com.br
Site address (URL): https://www.cuscoloko.com.br
WC Version: 4.2.1
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.4
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: pt_BR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.25 (Debian)
PHP Version: 7.4.7
PHP Post Max Size: 25 MB
PHP Time Limit: 180
PHP Max Input Vars: 2500
cURL Version: 7.52.1
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 5.7.30
Max Upload Size: 25 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.1
WC Database Prefix: csc_
Tamanho total do banco de dados: 149.98MB
Tamanho dos dados do banco de dados: 110.33MB
Tamanho do índice do banco de dado: 39.65MB
csc_woocommerce_sessions: Dados: 2.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_woocommerce_api_keys: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
csc_woocommerce_attribute_taxonomies: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_woocommerce_downloadable_product_permissions: Dados: 0.02MB + Índex: 0.09MB + mecanismo InnoDB
csc_woocommerce_order_items: Dados: 0.23MB + Índex: 0.09MB + mecanismo InnoDB
csc_woocommerce_order_itemmeta: Dados: 2.52MB + Índex: 2.95MB + mecanismo InnoDB
csc_woocommerce_tax_rates: Dados: 0.02MB + Índex: 0.11MB + mecanismo InnoDB
csc_woocommerce_tax_rate_locations: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
csc_woocommerce_shipping_zones: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_woocommerce_shipping_zone_locations: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
csc_woocommerce_shipping_zone_methods: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_woocommerce_payment_tokens: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_woocommerce_payment_tokenmeta: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
csc_woocommerce_log: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_actionscheduler_actions: Dados: 4.02MB + Índex: 1.41MB + mecanismo InnoDB
csc_actionscheduler_claims: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_actionscheduler_groups: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_actionscheduler_logs: Dados: 2.02MB + Índex: 1.36MB + mecanismo InnoDB
csc_adtribes_my_conversions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_aepc_custom_audiences: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_aepc_logs: Dados: 15.52MB + Índex: 0.00MB + mecanismo InnoDB
csc_aiowps_events: Dados: 2.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_aiowps_failed_logins: Dados: 0.34MB + Índex: 0.00MB + mecanismo InnoDB
csc_aiowps_global_meta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_aiowps_login_activity: Dados: 0.13MB + Índex: 0.00MB + mecanismo InnoDB
csc_aiowps_login_lockdown: Dados: 0.06MB + Índex: 0.00MB + mecanismo InnoDB
csc_aiowps_permanent_block: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_cart_notices: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_commentmeta: Dados: 0.06MB + Índex: 0.06MB + mecanismo InnoDB
csc_comments: Dados: 2.44MB + Índex: 1.05MB + mecanismo InnoDB
csc_correios_postcodes: Dados: 0.25MB + Índex: 0.09MB + mecanismo InnoDB
csc_failed_jobs: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_links: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_mailchimp_carts: Dados: 0.11MB + Índex: 0.00MB + mecanismo InnoDB
csc_mailchimp_jobs: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_ms_snippets: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_options: Dados: 15.22MB + Índex: 0.44MB + mecanismo InnoDB
csc_postmeta: Dados: 15.45MB + Índex: 12.47MB + mecanismo InnoDB
csc_posts: Dados: 10.31MB + Índex: 1.17MB + mecanismo InnoDB
csc_queue: Dados: 0.42MB + Índex: 0.00MB + mecanismo InnoDB
csc_rank_math_404_logs: Dados: 0.06MB + Índex: 0.02MB + mecanismo InnoDB
csc_rank_math_internal_links: Dados: 0.06MB + Índex: 0.02MB + mecanismo InnoDB
csc_rank_math_internal_meta: Dados: 0.09MB + Índex: 0.00MB + mecanismo InnoDB
csc_rank_math_redirections: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_rank_math_redirections_cache: Dados: 0.08MB + Índex: 0.02MB + mecanismo InnoDB
csc_rank_math_sc_analytics: Dados: 7.52MB + Índex: 7.55MB + mecanismo InnoDB
csc_snippets: Dados: 0.05MB + Índex: 0.00MB + mecanismo InnoDB
csc_social_users: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_swift_performance_image_optimizer: Dados: 2.50MB + Índex: 1.52MB + mecanismo InnoDB
csc_swift_performance_warmup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
csc_termmeta: Dados: 0.11MB + Índex: 0.11MB + mecanismo InnoDB
csc_terms: Dados: 0.05MB + Índex: 0.03MB + mecanismo InnoDB
csc_term_relationships: Dados: 1.16MB + Índex: 0.11MB + mecanismo InnoDB
csc_term_taxonomy: Dados: 0.06MB + Índex: 0.03MB + mecanismo InnoDB
csc_tm_taskmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
csc_tm_tasks: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_uap_affiliates: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_uap_affiliate_referral_users_relations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
csc_uap_banners: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_campaigns: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_coupons_code_affiliates: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_cpm: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_dashboard_notifications: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_landing_commissions: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_mlm_relations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
csc_uap_notifications: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_offers: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_offers_affiliates_reference: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_payments: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_uap_ranks: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_ranks_history: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_uap_referrals: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_uap_ref_links: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_uap_reports: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_uap_visits: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_usermeta: Dados: 4.42MB + Índex: 5.86MB + mecanismo InnoDB
csc_users: Dados: 0.16MB + Índex: 0.14MB + mecanismo InnoDB
csc_wc_admin_notes: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_wc_admin_note_actions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_wc_category_lookup: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_wc_customer_lookup: Dados: 0.16MB + Índex: 0.13MB + mecanismo InnoDB
csc_wc_download_log: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
csc_wc_gpf_render_cache: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
csc_wc_order_coupon_lookup: Dados: 0.05MB + Índex: 0.03MB + mecanismo InnoDB
csc_wc_order_product_lookup: Dados: 0.27MB + Índex: 0.30MB + mecanismo InnoDB
csc_wc_order_stats: Dados: 0.13MB + Índex: 0.14MB + mecanismo InnoDB
csc_wc_order_tax_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
csc_wc_product_meta_lookup: Dados: 0.28MB + Índex: 0.59MB + mecanismo InnoDB
csc_wc_tax_rate_classes: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_wc_webhooks: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_wfBlockedIPLog: Dados: 0.17MB + Índex: 0.00MB + mecanismo InnoDB
csc_wfBlocks7: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
csc_wfConfig: Dados: 2.23MB + Índex: 0.00MB + mecanismo InnoDB
csc_wfCrawlers: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_wfFileChanges: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_wfFileMods: Dados: 8.52MB + Índex: 0.00MB + mecanismo InnoDB
csc_wfHits: Dados: 1.02MB + Índex: 0.22MB + mecanismo InnoDB
csc_wfHoover: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_wfIssues: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
csc_wfKnownFileList: Dados: 3.52MB + Índex: 0.00MB + mecanismo InnoDB
csc_wfLiveTrafficHuman: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_wfLocs: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_wfLogins: Dados: 0.39MB + Índex: 0.14MB + mecanismo InnoDB
csc_wfls_2fa_secrets: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_wfls_settings: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_wfNotifications: Dados: 0.06MB + Índex: 0.00MB + mecanismo InnoDB
csc_wfPendingIssues: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
csc_wfReverseCache: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_wfSNIPCache: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
csc_wfStatus: Dados: 1.02MB + Índex: 0.09MB + mecanismo InnoDB
csc_wfTrafficRates: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
csc_woocommerce_bundled_itemmeta: Dados: 0.13MB + Índex: 0.14MB + mecanismo InnoDB
csc_woocommerce_bundled_items: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
csc_woocommerce_gpf_google_taxonomy: Dados: 1.52MB + Índex: 0.00MB + mecanismo InnoDB
csc_yith_wcwl: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
csc_yith_wcwl_lists: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB

### Post Type Counts ###

attachment: 1240
blocks: 117
boleto_reminder: 257
customize_changeset: 17
mc4wp-form: 1
nav_menu_item: 29
o-discount: 1
oembed_cache: 6
page: 17
popup: 11
popup_theme: 9
post: 3
product: 401
product_variation: 2507
revision: 788
shop_coupon: 50
shop_order: 957
shop_order_refund: 13
wafs: 2
wc_product_tab: 21
wp-rest-api-log: 1
wpcf7_contact_form: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (49) ###

All In One WP Security: por Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.4.4

Astro WooCommerce Free Gift: por AstroTemplates – 1.0.1 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.1
Editor clássico: por Colaboradores do WordPress – 1.5
Code Snippets: por Code Snippets Pro – 2.14.0
Contact Form 7 Extension For Mailchimp: por Renzo Johnson – 0.5.20
Contact Form 7: por Takayuki Miyoshi – 5.1.9
Duplicate Page: por mndpsingh287 – 4.2
Easy Theme and Plugin Upgrades: por Chris Jean – 2.0.1
Google Customer Reviews for WooCommerce: por eCreations – 2.6.12 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.1
Facebook for WooCommerce: por Facebook – 1.11.4
Rank Math Google Indexing API: por Rank Math – 1.2
Site Kit by Google: por Google – 1.10.0
Hide YouTube Related Videos: por SparkWeb Interactive
Inc. – 1.4.2

Indeed Ultimate Affiliate Pro: por WPIndeed Development – 6.3
Loco Translate: por Tim Whitlock – 2.4.0
Mailchimp para Woocommerce: por Mailchimp – 2.4.1 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.1
Popup Maker: por Popup Maker – 1.10.2
Regenerate Thumbnails: por Alex Mills (Viper007Bond) – 3.1.3
Rank Math SEO: por Rank Math – 1.0.44.1
Swift Performance: por SWTE – 2.1.9
WC Dias adicionais por produto: por Fernando Acosta – 1.4.8
WC Any Shipping Notify: por Fernando Acosta – 1.5.7
WC Lembrete de Boleto: por Fernando Acosta – 1.2.9
Calculadora de Frete otimizada no carrinho: por Fernando Acosta – 1.5.2 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.1
WC Simulador de Frete: por Fernando Acosta – 1.7.1
WC Simulador de parcelas e descontos: por Fernando Acosta – 1.6.9
WC Redução e restauração de estoque: por Fernando Acosta – 1.2.6
WC Tabela de Frete Offline: por Fernando Acosta – 1.4.3
Widgets in Menu for WordPress: por saurabhshukla
yapapaya – 1.0.0

Advanced Order Export For WooCommerce: por AlgolPlus – 3.1.4 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.1
Additional Variation Images Gallery for WooCommerce: por Emran Ahmed – 1.1.41 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.1
Variation Swatches for WooCommerce: por Emran Ahmed – 1.0.84
WooCommerce Advanced Free Shipping: por Jeroen Sormani – 1.1.4 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.1
WooCommerce Cart Notices: por SkyVerge – 1.11.4 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.1
Claudio Sanches - Correios for WooCommerce: por Claudio Sanches – 3.8.0 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.1
WooCommerce Dynamic Pricing: por Lucas Stark – 3.1.19 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.1
Brazilian Market on WooCommerce: por Claudio Sanches – 3.7.2 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.1
WooCommerce Google Ads Conversion Tracking: por Wolf+Bär Agency – 1.6.5
WooCommerce Google Analytics Pro: por SkyVerge – 1.8.13
Pagar.me para WooCommerce: por Pagar.me
Claudio Sanches – 2.0.18 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.1

WooCommerce Product Bundles: por SomewhereWarm – 6.2.5
WooCommerce Google Product Feed: por Ademti Software Ltd. – 8.1.2
WooCommerce Social Login: por SkyVerge – 2.8.7 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.1
WooCommerce Tab Manager: por SkyVerge – 1.12.1 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.1
WooCommerce Waitlist: por Neil Pie – 2.1.21
WooCommerce: por Automattic – 4.2.1
Wordfence Security: por Wordfence – 7.4.8
WP-Optimize - Clean, Compress, Cache: por David Anderson
Ruhani Rabin
Team Updraft – 3.1.2

REST API Log: por Pete Nelson – 1.6.7

### Inactive Plugins (3) ###

Disable Emails: por WebAware – 1.6.3
WooCommerce WishLists: por Lucas Stark – 2.2.0 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.1
Wootomation - Machine Learning AI: por Dragos Micu – 1.2.0 – Versão instalada não testada com a versão ativa do WooCommerce 4.2.1

### Must Use Plugins (1) ###

Swift Performance early loader: por  –

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: BRL (R$)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base da loja: #6 - /loja/
Carrinho: #7 - /carrinho/
Finalizar compra: #8 - /finalizar-compra/
Minha conta: #9 - /minha-conta/
Termos e condições: ❌ Página não definida

### Theme ###

Name: CSCLK - Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.11.3
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
csclk-flatsome-child/woocommerce/emails/customer-completed-order.php
csclk-flatsome-child/woocommerce/emails/customer-on-hold-order.php
csclk-flatsome-child/woocommerce/emails/customer-processing-order.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
csclk-flatsome-child/woocommerce/single-product/add-to-cart/variable.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
/home/176158.cloudwaysapps.com/wzcbdnsnsw/public_html/wp-content/plugins/woo-variation-gallery/templates/product-images.php
/home/176158.cloudwaysapps.com/wzcbdnsnsw/public_html/wp-content/plugins/woo-variation-gallery/templates/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php

### WooCommerce Google Product Feed fields ###

Product description: Variation description only
fallback to main description (full preferred).

Availability: Defaults to "in stock".
Brand: Defaults to "Cuscoloko".
Manufacturer Part Number (MPN): Pre-populates from product sku.
Product Type: Pre-populates from product_cat taxonomy.
Google Product Category: 
Global Trade Item Number (GTIN): 
Size system: Defaults to "BR".

### WooCommerce Google Product Feed options ###

Include variations in feed: Enabled
Send item_group_id: Enabled
debug_key: 908be233-3e7e-4d9e-8339-9b549d9c6397

### Product Bundles ###

Database Version: 6.2.5
Template Overrides: –

### Social Login ###

Facebook: ✔ Available
Twitter: Disabled
Google: ✔ Available
Amazon: Disabled
Linkedin: Disabled
Paypal: Disabled
Disqus: Disabled
Yahoo: Disabled
Vkontakte: Disabled

### Action Scheduler ###

Cancelado: 9
Oldest: 2020-05-29 00:02:02 -0300
Newest: 2020-06-22 22:05:04 -0300

Concluído: 5.746
Oldest: 2020-05-23 14:09:12 -0300
Newest: 2020-06-23 13:56:09 -0300

Malsucedido: 2
Oldest: –
Newest: –

Pendente: 4
Oldest: 2020-06-23 14:11:09 -0300
Newest: 2020-06-28 19:48:03 -0300

`
</details>

**Comment by mouligreenlaw** [comment]
Also on 3084383-zen

**Comment by Frisoni** [comment]
Hey!
Even after corection from https://github.com/woocommerce/woocommerce/issues/27066 I'm still having this webhook issue.
Wher an action is running and I try to create a new update action it did not fire and I don't get the newest information to be sent.

Anyone that can test and confirm this bug?

**Comment by becomebusiness** [comment]
I'm having this issue too.

When an order goes from "pending" -> "processing" and it happens very close to each other (less than 1 second apart), I get an order.update trigger with the status as "pending" when in fact it should be "processing".

Order.create sets it to pending
Order.update still shows as pending
When I check the order in the backend it's set to processing.

Definitely still a bug.

**Comment by matt-h** [comment]
I created two potential fixes here: https://github.com/woocommerce/woocommerce/pull/27850 and https://github.com/woocommerce/woocommerce/pull/27851

The first I think fixes the core problem here but changes some of the functionality of the action scheduler. The second adds an option (open to enabled or disabled by default) which just allows sending all webhooks even if they are queued. Which might be a good feature to have if you want every change even if one is queued.

One or both of these should solve the issue here in different ways.

**Comment by peterfabian** [comment]
Hi all. Is this still a problem or did https://github.com/woocommerce/woocommerce/pull/27850 solve it?

**Comment by matt-h** [comment]
https://github.com/woocommerce/woocommerce/pull/27850 solved it for me.
