### ISSUE TITLE
[Accessibility] Manual Order Shipping is not accessibility via screen reader

### ISSUE THREAD

**Issue by melindahelt** [woocommerce/woocommerce#26875]
Submitted via WooCommerce Support:

Steps to reproduce:
Go to Add Order Manually
Add Item
Add Shipping

What you get then is a shipping rate of 0.00 and what is described to me by my sighted assistant as a “Pencil” to the right of it. You have to click the pencil to edit the shipping details, such as amount and shipping type.

There is no way to click that pencil via the keyboard. Pressing enter on 0.00 yields nothing and I can’t edit it without assistance.

**Comment by lsinger** [comment]
Noting that we should strive for _all_ items to be reachable via keyboard and accessible via screen reader.

**Comment by jeffpaul** [comment]
Note that @Manussakis has a PR up for this that's going through review.
