### ISSUE TITLE
Phone numbers shouldn't be validated if they are not required

### ISSUE THREAD

**Issue by clifgriffin** [woocommerce/woocommerce#26895]
**Prerequisites (mark completed items with an [x]):**
- [X ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When setting billing_phone to unrequired, an invalid phone number triggers 'Billing Phone is not a valid phone number' error message.

I found this because a customer paying with Amazon Pay was unable to checkout and the issue was that the phone number stored in their Amazon account was not a valid phone number.

**Expected behavior**
Unrequired fields should not be further validated.

**Actual behavior**
Unrequired fields are validated for correct formatting

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Add this code to functions.php
```php
add_filter( 'woocommerce_billing_fields', 'foo_override_billing_fields' );

function foo_override_billing_fields( $fields ) {
    $fields['billing_phone']['required'] = false;
    return $fields;
}
```
2. Go to checkout and enter an invalid phone number: foobar
3. Try to submit checkout.
4. See error 'Billing Phone is not a valid phone number'
**Isolating the problem (mark completed items with an [x]):**
- [X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X ] I can reproduce this bug consistently using the steps above.

**Comment by passatgt** [comment]
I don't think this is a good idea. If someone wants to enter a phone number even if it's optional, it should be validated. A filter for the is_phone() function in the WC_Validation class would be a good idea though and with that you can either improve the built-in validation or disable it.

**Comment by clifgriffin** [comment]
@passatgt From a UX perspective, I think it's confusing to validate an optional field. 

But it's something I could easily argue from both sides. 

However, if we ask only what the normal way of handling optional fields is, I think it's pretty rare to validate optional fields unless they are mission critical. (Such as, "if you want to be notified enter your email address here")

I agree that having an additional filter would be more ideal than overriding the billing field settings directly.

**Comment by claudiosanches** [comment]
Hello @clifgriffin 

While I understand your frustration, we need to keep this validation, it can't allow incorrect numbers, if you don't require any number, you can just remove this field from the form too.
In fact sounds like it need to be improved when the number comes from the Amazon Pay and fill the checkout form to avoid problems like that for everyone.

Also note that `WC_Validation::is_phone( $value )` allows several different formats, on your case seems like they entered something really out of common to trigger this message.

I'm closing for now, but if you like to submit a PR adding a filter we can discuss investigate it.

**Comment by webdados** [comment]
Please re-open and re-evaluate this issue.

This applies not only to phone numbers but also to postcodes and probably other fields.

It makes no sense to validate a non-required field if it was not filled by the user.

The expected behavior is, IMHO:
- Field is required: validation is performed
- Field is optional and filled by the user: validation is performed
- Field is optional and NOT filled by the user: validation is NOT performed (it's empty... validation will always fail making the field required by the current logic, even if was set and non-required by the website owner via filters or a plugin)

I can submit a PR if you agree this should be the behavior.

**Comment by BrunoPoncePerez** [comment]
Good afternoon, I have a similar problem. Currently I have the phone field disabled and the mandatory option also, but even so, when the user places their data and sends the form I see the following problem: 

-Please enter a valid phone number. Only numbers. 

I have seen that there are similar problems with emails, but this is not the case. Can someone help me with the solution, please.

**Comment by tj0xin** [comment]
The issue persists. Any Solution?
