### ISSUE TITLE
Make it possible to show deprecated hook notices if the deprecated hook has no direct replacement

### ISSUE THREAD

**Issue by jbeales** [woocommerce/woocommerce#26903]
**Is your feature request related to a problem? Please describe.**
I keep getting support requests for a Woo extension that I made because other 3rd-party, (and even 1st-party!), devs haven't stopped using a filter that was removed in 2017, (see #26901). I've been looking at adding the filter to the `WC_Deprecated_Filter_Hooks` class, but `WC_Deprecated_Filter_Hooks` and `WC_Deprecated_Action_Hooks` only work if there is a replacement available.

**Describe the solution you'd like**
I would like a way to show a "You're using a deprecated hook" notice to WooCommerce even if there is no replacement hook available

**Describe alternatives you've considered**
Option 1: DIY: I have considered calling the `wc_deprecated_hook()` function in my own plugin. This would solve my immediate problem, but doesn't give the WC community a way to push developers to adopt the current WC architecture.

Option 2: Add a fake "new" hook to `WC_Deprecated_Filter_Hooks`: This doesn't actually work. `WC_Deprecated_Filter_Hooks` works by checking for anything hooked to old hook names when the new hook is called, and since a fake hook name is never called `WC_Deprecated_Filter_Hooks` is never triggered.

**Additional context**
I think we could do this by permitting extra elements in the `$deprecated_version` array, then for any hooks that are in the `$deprecated_version` array but are not in `$deprecated_hooks` add a handler for when they are called.

Unfortunately we can't add deprecated hooks with no replacement to the `$deprecated_hooks` array because it's an associative array that uses the new hook name for keys.

I also noticed that #22598 is looking at removing the whole `WC_Deprecated_Hooks` / `WC_Deprecated_Filter_Hooks` / `WC_Deprecated_Action_Hooks` system completely. If that's done it would be great to see a way to add messages for hooks that have been removed, not replaced.

Links to the classes in question: 
`WC_Deprecated_Hooks`: https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-deprecated-hooks.php
`WC_Deprecated_Action_Hooks`: https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-deprecated-action-hooks.php
`WC_Deprecated_Filter_Hooks`: https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-deprecated-filter-hooks.php

**Comment by vedanshujain** [comment]
This is a good suggestion, but I am not sure if this is possible:

>  I think we could do this by permitting extra elements in the $deprecated_version array, then for any hooks that are in the $deprecated_version array but are not in $deprecated_hooks add a handler for when they are called.

If the hook is removed, then it will never be called. So if there is a handler for a removed hook we will never know and therefore cannot show a deprecated notice. Checking for all deprecated handlers is also not foolproof because the handler could be added after we perform the check.

>  If that's done it would be great to see a way to add messages for hooks that have been removed, not replaced.

Those methods still do not handle removed hook unless I am missing something.

I am closing this as non-viable (reasoning at https://github.com/woocommerce/woocommerce/issues/26901#issuecomment-654392340), but would love to be corrected if there is actually a good solution for this.

**Comment by jbeales** [comment]
> If the hook is removed, then it will never be called.
In an ideal world, yes. But for some hooks, (like the one in #26901), at least some themes & plugins do an `apply_filters('some_ancient_and_dead_wc_filter')`, in which case it would be good to show a deprecated notice, even if it's just in a log file. Since the `woocommerce_single_product_image_html` filter is in a template file, which may be copied to a theme, it, and anything else in a template, is probably more long-lived than they should be.

I went hunting to see if WP's `add_filter()` runs its input through a filter or something that we could use, but it doesn't that I can see, so we're out of luck trying to put up a notice when people add things to deprecated filters.
