### ISSUE TITLE
Removed filter woocommerce_single_product_image_html is missing from WC_Deprecated_Filter_Hooks class

### ISSUE THREAD

**Issue by jbeales** [woocommerce/woocommerce#26901]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
The filter `woocommerce_single_product_image_html` was [removed in 2017](https://github.com/woocommerce/woocommerce/issues/14152) in 3823b783186245291a12f6452b1c56edacd2e576. Some themes and plugins still try to use this filter, and it leads to confusion from users and a support burden for people, (like me), that publish extensions related to galleries. The removal doesn't appear to have been publicized beyond adding `woocommerce_single_product_image_html` to the list of [deprecated filters in the migration notes](https://github.com/woocommerce/woocommerce/wiki/2.6.x-to-3.0.0-Developer-Migration-Notes#deprecated-filters) - after WooCommerce 3.0 was released. 

It seems like `woocommerce_single_product_image_html` should have been added to the `WC_Deprecated_Filter_Hooks` class, but wasn't.

**Expected behavior**
If a plugin or theme tries to execute the `woocommerce_single_product_image_html` filter I expect an error or warning to appear, either in the WP admin or in a debug log, (preferably the wp-admin).

**Actual behavior**
Nothing happens when calling  `apply_filters( 'woocommerce_single_product_image_html', $html, $post_id )`.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Install the attached demo plugin: 
[jb-single-product-image-html-hook-demo.zip](https://github.com/woocommerce/woocommerce/files/4853041/jb-single-product-image-html-hook-demo.zip)
2. Visit any Product page
3. Verify the text "Some test text being filtered" appears above the product image
4. See that there are no error messages and nothing has been added to debug.log

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://wptest.loc
Site address (URL): http://wptest.loc
WC Version: 4.2.2
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.4
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Unix) OpenSSL/1.1.1d
PHP Version: 7.3.10
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.66.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.27
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.2
WC Database Prefix: wp_
Total Database Size: 4.62MB
Database Data Size: 3.09MB
Database Index Size: 1.53MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.13MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wpsc_also_bought: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpsc_cart_contents: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpsc_cart_item_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpsc_checkout_forms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wpsc_claimed_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpsc_coupon_codes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpsc_currency_list: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_wpsc_download_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpsc_meta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wpsc_product_rating: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpsc_purchase_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpsc_purchase_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpsc_region_tax: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpsc_submited_form_data: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpsc_visitors: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wpsc_visitor_meta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM

### Post Type Counts ###

attachment: 6
flamingo_contact: 2
page: 12
post: 4
product: 8
product_variation: 2
revision: 7
shop_coupon: 2
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌
                    Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

JB woocommerce_single_product_image_html Demo: by John Beales – 1.0 – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce: by Automattic – 4.2.2

### Inactive Plugins (15) ###

Better Sold Out for WPEC: by John Beales – 0.1
Bookings Helper: by WooCommerce – 1.0.2 – Installed version not tested with active version of WooCommerce 4.2.2
Contact Form 7: by Takayuki Miyoshi – 5.1.9
Elementor: by Elementor.com – 2.9.13
Flamingo: by Takayuki Miyoshi – 2.1.1
Gallery Captions for WooCommerce: by John Beales – 1.0.2 – Installed version not tested with active version of WooCommerce 4.2.2
JB Widget Problems Demo: by John Beales – 1.0
Porto Theme - Functionality: by P-Themes – 1.7.1
Variation Swatches for WooCommerce: by Emran Ahmed – 1.0.84
Variation Swatches for WooCommerce - Pro: by Emran Ahmed – 1.0.54
WooCommerce Additional Variation Images: by WooCommerce – 1.7.22 (update to version 1.7.23 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Bookings: by Automattic – 1.13.3 (update to version 1.15.21 is available) – Installed version not tested with active version of WooCommerce 4.2.2
WooCommerce Services: by Automattic – 1.23.2
WooCommerce Stripe Gateway: by WooCommerce – 4.5.0
Woo Description on Radio Buttons demo: by John Beales – 1.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #17 - /shop/
Cart: #18 - /cart/
Checkout: #19 - /checkout/
My account: #20 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.7
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 7
Oldest: 2020-06-08 15:59:41 +0000
Newest: 2020-06-30 15:43:29 +0000

`
```
</details>

**Comment by vedanshujain** [comment]
For filters/hooks that are deprecated without replacement, it's not possible without an expensive hack to actually check and display a notice. When a filter/hook is replaced, we add a check in the new filter/hook name to see if there are any handlers for the old name as well and if there is we show the deprecation notice. But in absence of a replacement, there is no correct place to check if a handler for a removed hook is present or not.

Also, I think it's reasonable to remove the hook in a major version. The good news is, since the last few releases. we run a semi-automated test as part of our release process to see what all extensions are using a hook/filter deprecated in the current release so we can reach out to them and bring it to their attention.

I am closing the issue as we have a good enough workaround in our release process documented above, and I don't see a reasonable path to fix the issue although I do understand the frustration. I am also curious if my initial assessment is wrong and there is actually a good way to show notice when a removed hook is used.

**Comment by jbeales** [comment]
> we run a semi-automated test as part of our release process to see what all extensions are using a hook/filter deprecated in the current release so we can reach out to them and bring it to their attention.

It would be great if this could be expanded & become somehow universal. One of the extensions I ran into that did this is a Woo-developed one available for sale on WooCommerce.com, so it _should_ be easy to fix, but the other place I've seen it is a 3rd-party theme sold through Themeforest. If there was a way for Woo/Automattic to reach out to Themeforest/Envato-hosted authors that would be great.

> I am also curious if my initial assessment is wrong and there is actually a good way to show notice when a removed hook is used.
For hooks that actually get called, like `apply_filters('woocommerce_single_product_image_html')`, there could be a file somewhere that more or less hooks `wc_deprecated_hook()` into them all. As I mentioned in #26903 I don't see a way to catch people trying to hook into deprecated hooks.

**Comment by vedanshujain** [comment]
> It would be great if this could be expanded & become somehow universal.

This is a recent enhancement to our processes, and we now run it on every release since the last few releases. This is particular filter was deprecated before we started doing this, and this is why it was missed.

> If there was a way for Woo/Automattic to reach out to Themeforest/Envato-hosted authors that would be great.

cc @woocommerce/proton  if we can do anything to reach out to Themeforest etc about deprecated filters/hooks in their themes.
