### ISSUE TITLE
Province taxes not being calculated at checkout

### ISSUE THREAD

**Issue by maverickstruth** [woocommerce/woocommerce#26902]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When using manual taxes, changing the province (region / country set to Canada) does not update the taxes at checkout.

**EXPECTED BEHAVIOUR:** When going to the checkout, selecting “Country: Canada” and “Province: British Columbia” should result in the “your order” box being updated and a tax of 5% being added.
**ACTUAL BEHAVIOUR:** There is no refresh and no tax is added

**EXPECTED BEHAVIOUR:** When going to the checkout, selecting “Country: Canada” and “Province: Ontario” should result in the “your order” box being updated and a tax of 13% being added.
**ACTUAL BEHAVIOUR:** There is no refresh and no tax is added

This issue is occurring in:

- a brand new WordPress installation
- only WooCommerce enabled
- using the Storefront theme
- on Chrome 83, including incognito mode
- on Safari 13, including incognito mode

**Steps to reproduce the bug**
Set up the shop as per the shop settings shown below.

Then, proceed with product check out and change the country/province as shown in this video: https://www.loom.com/share/acdedf6d060541d18aeac82d7a842a1e

**Screenshots**
The relevant shop & product settings are as follows:

<img width="760" alt="woocommerce_general_settings" src="https://user-images.githubusercontent.com/693393/86152929-c24e9c00-bab5-11ea-8177-5cdaee148fc2.png">

<img width="699" alt="Screenshot 2020-06-30 09 39 37" src="https://user-images.githubusercontent.com/693393/86152972-d0042180-bab5-11ea-8c28-21762c586d05.png">

<img width="1016" alt="Screenshot 2020-06-30 09 39 49" src="https://user-images.githubusercontent.com/693393/86152982-d4303f00-bab5-11ea-87b8-227db4ad5905.png">

<img width="725" alt="Screenshot 2020-06-30 09 40 06" src="https://user-images.githubusercontent.com/693393/86152993-d7c3c600-bab5-11ea-8c8b-0abcfccf9288.png">

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

WordPress address (URL): https://woocommerce-402734-1359639.cloudwaysapps.com
Site address (URL): https://woocommerce-402734-1359639.cloudwaysapps.com
WC Version: 4.2.2
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.4
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.25 (Debian)
PHP Version: 7.3.19-1+0~20200612.60+debian9~1.gbp6c8fe1
PHP Post Max Size: 10 MB
PHP Time Limit: 60
PHP Max Input Vars: 2500
cURL Version: 7.52.1
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.45-MariaDB-1~stretch
Max Upload Size: 10 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.2.2
WC Database Prefix: wp_
Total Database Size: 3.76MB
Database Data Size: 2.33MB
Database Index Size: 1.43MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.48MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
customize_changeset: 1
page: 8
post: 3
product: 1
revision: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.2.2

### Inactive Plugins (4) ###

Breeze: by Cloudways – 1.1.7
Jetpack by WordPress.com: by Automattic – 8.6.1
WooCommerce Services: by Automattic – 1.23.2
WooCommerce Stripe Gateway: by WooCommerce – 4.5.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #8 - /shop
Cart: #9 - /cart
Checkout: #10 - /checkout
My account: #11 - /my-account
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.7
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 42
Oldest: 2020-06-29 00:42:04 +0000
Newest: 2020-06-29 00:48:48 +0000
</details>

**Comment by tammullen** [comment]
Hi @maverickstruth 

Thank you for submitting the issue. The reason this is happening is because the tax is calculated once all the required address field are filled in. If the other required fields are filled out the tax should calculate correctly.
​
![Screenshot_2020-07-02_at_19_19_16](https://user-images.githubusercontent.com/24649833/86400380-6a27bd80-bca0-11ea-9b03-009e7e6bc584.png)
![Screenshot_2020-07-02_at_19_21_03](https://user-images.githubusercontent.com/24649833/86400382-6bf18100-bca0-11ea-8c7c-10a5f6cc08b2.png)

**Comment by maverickstruth** [comment]
Confirmed, that is the case on my system as well. I'll make sure to note this on my conversation with the support folks on the forums so that they know.

That being said, the UX of this is awkward, so I might suggest that this be considered as a future change that the updates happen regardless of whether all fields are updated.

Thanks again.
