### ISSUE TITLE
woocommerce_rest_cannot_view error instead of product.create webhook

### ISSUE THREAD

**Issue by alibek-gao** [woocommerce/woocommerce#26926]
When new product created on server specified in "Delivery URL" instead of new product info I receive following message: 

{"code":"woocommerce_rest_cannot_view","message":"...","data":{"status":403}}

on server side I only write Raw Post Data to log

**Comment by Xonman** [comment]
@alibek-gao did you close this issue because you solved it? I am having a similar problem and would love a permanent fix.

**Comment by alibek-gao** [comment]
@Xonman as i remember, after deleting and creating new hook problem was solved

**Comment by Xonman** [comment]
@alibek-gao ok, thanks for the response!
