### ISSUE TITLE
Improve performance of WC_Customer_Data_Store's functions -- `get_last_order`, `get_total_spent` and `get_order_count` functions

### ISSUE THREAD

**Issue by vedanshujain** [woocommerce/woocommerce#26925]
**Is your feature request related to a problem? Please describe.**
Currently, functions `get_last_order` and `get_order_count` use very expensive queries to compute not so important results. The function names are very unsuspecting and can easily lead to a severe reduction in performance.

These queries are slow because they use a join with posts and post meta table with comparison in columns in both the table. So MySQL creates a temporary table, dumps all the somewhat filtered data from both the table, and then query to figure out the result. As you can expect, this is incredibly slow.

**Describe the solution you'd like**
I would suggest improving the function by:
1. Adding a cache layer based on customer ID (<- This should be a low hanging fruit)
2. Improve the query performance itself somehow (consider memoizing this result in a meta value).

**Describe alternatives you've considered**
N/A

**Additional context**
This is the `EXPLAIN` output for final get_last_order query (for egs):

| ID | Select Type  | Table | type  | possible keys | keys | key_len | ref | rows | filtered | extra |
| --- | --- | --- |  --- |  --- |  --- |  --- |  --- |  --- |  --- |  --- | 
| 1 | SIMPLE | wc_postmeta	 | ref | post_id,meta_key | meta_key | 767 | const | 8770 | 10 | Using where; Using temporary; Using filesort |
| 1 |	SIMPLE |	wc_posts | eq_ref | PRIMARY,post_name,type_status_date,post_parent,post_author | PRIMARY | 8	| woo_dev.wc_postmeta.post_id | 1 | 15.39 | Using where |

**Comment by mbruschi** [comment]
We can confirm that this query is very expensive and slows down the performance a lot. If it helps here is a stacktrace that shows it takes ~9s. Postmeta has ~6M entries, Post ~120k.

![image](https://user-images.githubusercontent.com/6988573/90096284-2611e900-dd33-11ea-8335-0364ce5656f6.png)

**Comment by juliquiron** [comment]
Hi @vedanshujain I think this PR may introduce some of your suggestions: https://github.com/woocommerce/woocommerce/pull/27352  Would you might to check and provide feedback on it? Thanks!
