### ISSUE TITLE
Category redirect missing from latest WooCommerce release

### ISSUE THREAD

**Issue by harloffkelly** [woocommerce/woocommerce#26939]
In version 4.0.1 of WooCommerce, there is a "301 Redirect URL" area on each category detail where you can redirect a category directly to a page. This video (https://vimeo.com/387103486) also shows a "Redirect URL" area in the category detail, and explains why this feature is ideal. In version 4.2.2 of WooCommerce, this feature is missing. 

Can anyone advise whether this feature was removed from WooCommerce core on purpose or if this was an omission that can be reinstated in a future release? I was unable to locate a removal in the WooCommerce changelogs, and was unable to locate a similar question in forums.

**Comment by tammullen** [comment]
Hi @harloffkelly 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 
​
The functionality you are referring to is part of the the 3rd party plugin Storefront Blocks

I am closing this issue for now as it seems to not be a bug. If I missed something, please leave a comment and we will take a second look.
