### ISSUE TITLE
Add a filter/way of omitting order items from having stock changed via wc_increase_stock_levels & wc_reduce_stock_levels

### ISSUE THREAD

**Issue by ninetyninew** [woocommerce/woocommerce#26943]
[wc_increase_stock_levels](https://docs.woocommerce.com/wc-apidocs/source-function-wc_increase_stock_levels.html#237) and [wc_reduce_stock_levels](https://docs.woocommerce.com/wc-apidocs/source-function-wc_increase_stock_levels.html#139) use `$order->get_items()` to loop through the items within an order and then increase/reduce stock based on a few conditions inside.

In some custom development scenarios you may need to remove specific items from the stock level changes for specific order items so they do not have their stock increased/reduced at all based on some conditions.

The only way we can see to manipulate this is by using [wp_debug_backtrace_summary](https://developer.wordpress.org/reference/functions/wp_debug_backtrace_summary/) to find out if wc_increase_stock_levels or wc_reduce_stock_levels is being called and manipulate the order items using a [woocommerce_get_cart_contents](https://docs.woocommerce.com/wc-apidocs/source-class-WC_Cart.html#146) filter.

**Comment by lsinger** [comment]
As discussed in #27200 this is probably too specific to include in Core WooCommerce. I'll therefore close this issue for now. Please feel free to start a new discussion in the future.
