### ISSUE TITLE
Pagination is shown at both top and bottom of product listing.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#26946]
## Bug Description:
Two sorting drop-down are displayed on preview and publish screen while selecting any category from the "Product category list" block.

## Environment:
**Windows 10**
Browser: Chrome(Version 83.0.4103.61 (64-bit))
Browser: Firefox(Version 77.0.1)(64-bit)

## Steps to Reproduce:
1. Launch any of the 5 test sites.
1. Sign In with valid credentials.
1. Go to Pages->Add New.
1. Add the "Product category list" block.
1. Click on Preview.
1. Select any one category from the "Product category list" block.
1. Observe that two sorting drop-downs are displayed.

## Actual Result:
Two sorting dropdown's are displayed on preview and publish screen.

## Expected Result:
Only one sorting dropdown should be displayed on preview and publish screen.

## Artifacts:
[#2807.zip](https://github.com/woocommerce/woocommerce-gutenberg-products-block/files/4864544/2807.zip)

**Comment by juliaamosova** [comment]
Hi @gglobalstep,

Thanks for reporting the issue and thanks for your comment @nerrad. 

The 2 dropdowns to filter products are also shown on the regular `Shop` page:

![filtering](https://user-images.githubusercontent.com/19143190/86822648-e4b65b80-c059-11ea-85f4-077b4ad63511.jpg)

We also show pagination twice. In the way, this is working as expected and we had these elements shown at the top and bottom of the pages for a long time. 

One benefit I see of keeping it is that if the merchant set up to display 100 products on the page, they don't have to always scroll up to filter products or move to the next page when they are at the bottom and vise versa. 

I'll mark this issue as `question` for now which means something for us to discuss further as a team but it is likely we won't be doing anything about it for now.

**Comment by rrennick** [comment]
Closing as pagination being shown at top and bottom is theme dependent:

<img width="824" alt="Screenshot 2023-06-16 at 4 25 42 PM" src="https://github.com/woocommerce/woocommerce/assets/343847/ad30ef7a-0d11-4c98-a8fb-d70aaf2f14da">
