### ISSUE TITLE
Use a woocommerce default wordpress update_meta_cache alternative to fetch object meta on queries with multiple items

### ISSUE THREAD

**Issue by ghost** [woocommerce/woocommerce#26958]
Hi, I'm trying to understand why do objects require to know the meta_id? I was tracking my queries and noticed that for every product makes a separate request to the database to get the [meta data for that item with the id.](https://github.com/woocommerce/woocommerce/blob/85580cfb4f0ffec83a736f7391f7775bab9f50b9/includes/data-stores/class-wc-data-store-wp.php#L83). 

Now, I can't understand why is the meta_id so important, that it requires a new query to fetch, but perhaps other users are using it so this cannot be changed.

I think it would be great to have a similar function to the default wordpress update_meta_cache, except it would be used to fetch the meta data for multiple objects at the same time with the meta_id.

Now, at least when querying multiple objects their ids can be used to fetch their metadata before actually instantiating them.

**Comment by Konamiman** [comment]
The metadata id is generally required to make changes to the meta table, since multiple rows can exist with the same meta name and meta value.

Anyway, I'm closing this for now as the user who asked no longer exists.
