### ISSUE TITLE
Remove/hide the Features setting

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce#26972]
We aim to make the Home screen as the default experience for every user in the release that will happen in August ([GH issue](https://github.com/woocommerce/woocommerce-admin/issues/4761)). In order to avoid maintaining two different experiences, the Features setting should be removed alongside the 4761 change. We'll probably replicate the same strategy for upcoming new features, so perhaps that Settings section could be hidden instead of being completely removed.

**Comment by pmcpinto** [comment]
cc @timmyc

**Comment by juliaamosova** [comment]
Adding 4.4 milestone to this issue.

**Comment by pmcpinto** [comment]
@juliaamosova just a heads up that we decided to postpone this change until 4.5. Thanks

**Comment by juliaamosova** [comment]
Thanks @pmcpinto! Updating the milestone.
