### ISSUE TITLE
get_customer_location fires on every page

### ISSUE THREAD

**Issue by glagonikas** [woocommerce/woocommerce#26973]
**Prerequisites (mark completed items with an [x]):**
- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When the "Default customer location" is set to "Geolocate (with page caching support)", the Ajax request `/?wc-ajax=get_customer_location` is called on each page load.

This is not delaying the page load, because it's done via Ajax, but it's yet another request that hits the server. On busy websites handling a large amount of visitors, it's an extra request which increases the server load.

From what i can see, this is not a shortinit function, so on a busy server, it might not always be very fast and therefore contribute to increased server load.

**Expected behavior**
The "Geolocate (with page caching support)" option is adding the v= parameter on every URL to differentiate between customers of different countries. It is understandable that this ajax would be required once, but it should set a cookie and remember the country on the next page load. Then on the next page load, if the cookie is already set, the request should not fire.

As this is done via Javascript, i'm not sure if there would be any implications on sites with HttpOnly cookies?

**Actual behavior**
This ajax fires on every page load.

**Steps to reproduce the bug**
1. Set "Default customer location" to "Geolocate (with page caching support)"
2. Visit the front-end and check the console. The Ajax request is called
3. Visit another page (for example /shop). The Ajax request is called again

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

WordPress address (URL): https://xxxx
Site address (URL): https://xxxx
WC Version: 4.2.0
REST API Version: ✔ 1.0.8
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.2.3
Log Directory Writable: ❌

WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.1
PHP Version: 7.4.7
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.1.1c

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.17-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.2.0 (update to version 4.2.2 is available)

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5007 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #93 - /terms-conditions/

### Theme ###

Name: Twenty Twenty
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
</details>

**Comment by John-belt** [comment]
HI,
I am facing the same thing. Why is the ajax being fired on every page , the hash code returned by the first ajax should be appended directly for all other requests. This will prevent unnecessary requests, unless there is some thought process behind this. This is also creating the issue with multiple redirects along with using it with cloudflare.

**Comment by Konamiman** [comment]
Hi @glagonikas, thanks for your contribution.

I think that your suggestion makes sense. The `v` parameter that is generated from the ajax request and appended to the url of the request could be appended to a short lived cookie, at least long enough to last for the typical user session. I'll mark this issue as an enhancement suggestion.
