### ISSUE TITLE
Display Paypal fees in Orders, like Stripe does.

### ISSUE THREAD

**Issue by laurentdebricon** [woocommerce/woocommerce#26991]
You can see **Stripe Fee** :
![Screenshot from 2020-07-09 11-58-32](https://user-images.githubusercontent.com/736104/87026112-903ae980-c1db-11ea-85e9-159a67aa7942.png)

https://github.com/woocommerce/woocommerce-gateway-stripe/blob/f597353e4a0caf7fd426e53a7f41262ad5ab3cb5/includes/class-wc-gateway-stripe.php#L705

it would be great if we have the same for Paypal : 
I can see the fee is stored in "PayPal Transaction Fee" custom field.

**Comment by mensmaximus** [comment]
https://de.wordpress.org/plugins/woocommerce-gateway-paypal-express-checkout/ already does.

**Comment by rodrigoprimo** [comment]
Closing per the comment above.

**Comment by laurentdebricon** [comment]
i am sad this issue is closed, it's so handy to have the stripe fees. i would love to know also the paypal fees for budget planning in the reporting :( :( i don't want to install a new extension, let's make this feature into woocommerce core !

![Captura de tela de 2020-12-07 10-56-12](https://user-images.githubusercontent.com/736104/101336584-f014e980-387a-11eb-9714-d35f2e7887b7.png)

**Comment by rodrigoprimo** [comment]
Thanks for the additional details. I'm reopening this issue so that we get an opinion from someone else from our team. I'm unsure if we should support this or not and I feel like I should have done deeper research on the subject before closing this issue.

**Comment by jeffstieler** [comment]
Considering the core PayPal gateway is storing this metadata but not displaying it, it's reasonable to include this feature in core. Anyone picking this up can probably use https://github.com/woocommerce/woocommerce/pull/28389 as a starting point.

**Comment by peterfabian** [comment]
The core PayPal gateway has been deprecated in favor of [PayPal Payments plugin](https://woocommerce.com/products/woocommerce-paypal-payments/). 

Please see the announcement: https://developer.woocommerce.com/2021/07/12/developer-advisory-paypal-standard-will-be-hidden-on-new-installs/
