### ISSUE TITLE
WooCommerce Upgrade issue fatal error

### ISSUE THREAD

**Issue by nextsmarter** [woocommerce/woocommerce#26996]
After upgrade to newest woocommerce version, our site broken with below error:
-----------------------------------------------------
Fatal error: Uncaught Exception: Invalid data store for admin note. in /home/offshor1/ithotelpro.com/wp-content/plugins/woocommerce-admin/src/Notes/DataStore.php:127 Stack trace: #0 /home/offshor1/ithotelpro.com/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): Automattic\WooCommerce\Admin\Notes\DataStore->read(Object(Automattic\WooCommerce\Admin\Notes\WC_Admin_Note)) #1 /home/offshor1/ithotelpro.com/wp-content/plugins/woocommerce-admin/src/Notes/WC_Admin_Note.php(87): WC_Data_Store->read(Object(Automattic\WooCommerce\Admin\Notes\WC_Admin_Note)) #2 /home/offshor1/ithotelpro.com/wp-content/plugins/woocommerce-admin/src/Notes/WC_Admin_Notes.php(109): Automattic\WooCommerce\Admin\Notes\WC_Admin_Note->__construct('10') #3 /home/offshor1/ithotelpro.com/wp-content/plugins/woocommerce-admin/src/Notes/WC_Admin_Notes_Deactivate_Plugin.php(60): Automattic\WooCommerce\Admin\Notes\WC_Admin_Notes::delete_notes_with_name(Array) #4 /home/offshor1/ithotelpro.com/wp-content/plugins/woocommerce/packages/woocommerce-admi in /home/offshor1/ithotelpro.com/wp-content/plugins/woocommerce-admin/src/Notes/DataStore.php on line 127
There has been a critical error on your website.
-----------------------------------------------------

For more detail, please refer below captured image:
https://a.cl.ly/eDu1eNJL

2 months recently, I very scare when upgrade woocommerce, we have many sites got trouble with this plugin.
Feel the plugin very unstable recently.

**Comment by juliaamosova** [comment]
Hi @nextsmarter,

Thank you for reporting the issue. We are aware of it and looking at it as we speak. 

This issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/26985. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.

Thanks for your patience as we figure out the fix!
