### ISSUE TITLE
Pass $product_data WC_Product object to woocommerce_add_cart_item_data filter

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#27002]
**Is your feature request related to a problem? Please describe.**
When filtering the the `woocommerce_add_cart_item_data` if you want access to the product object you need to re-instantiate a product from the `$product_id` parameter. However in the cart class, the product is already instantiated via [`$product_data = wc_get_product( $variation_id ? $variation_id : $product_id );`](https://github.com/woocommerce/woocommerce/blob/7fa34c6770c4f55d2071e48f69f386ed15504553/includes/class-wc-cart.php#L1011)

**Describe the solution you'd like**
I'd like to see the `$product_data` object passed as an additional parameter to the [`woocommerce_add_cart_item_data`](
https://github.com/woocommerce/woocommerce/blob/7fa34c6770c4f55d2071e48f69f386ed15504553/includes/class-wc-cart.php#L1019) filter.

**Comment by rrennick** [comment]
@helgatheviking Thanks for the suggestion. We won't implement this for the same reason I outlined [here](https://github.com/woocommerce/woocommerce/pull/27069#issuecomment-671369813).
