### ISSUE TITLE
Product status changes to Out Of Stock after updated or selecting Featured

### ISSUE THREAD

**Issue by TomzLv** [woocommerce/woocommerce#27005]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I have a problem: If I edit imported product with variations and save it, then product status changes to “Out of Stock”. Even when select product “Featured”, it becomes “Out of stock”.

**Expected behavior**
Product status "In stock"
**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 
Product with variations becomes out of stock after selecting "Featured"
**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Import products with variation
2. Select product "Featured"
3. Product with variations becomes Out of stock

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by ivatautomattic** [comment]
Hello @TomzLv ,

Thank you for submitting the issue. Could you provide more details of the bug? Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Detailed steps to reproduce, the system status report and screenshots would help a lot in this case.**

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error

**Screenshots**
If applicable, add screenshots to help explain your problem.


**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by rrennick** [comment]
Closing for lack of feedback.
