### ISSUE TITLE
Customer deletion

### ISSUE THREAD

**Issue by oweichpold** [woocommerce/woocommerce#27007]
Hello!

How can I delete a customer including orders if a deletion is requested according to DSGVO or if a customer record is incorrect? 

On the admin page I can only delete the user but not the woocommerce customer.

Thanks a lot in advance!

Best regards!

**Comment by everaldomatias** [comment]
Hello!
Look at this topic: https://wordpress.org/support/topic/delete-customers/page/2/#post-13080492

**Comment by peterfabian** [comment]
Thanks for commenting, @everaldomatias , and for providing more context. 
@oweichpold , please follow the updates on this ticket: https://github.com/woocommerce/woocommerce-admin/issues/3810.

I'm closing this one as a duplicate. Thanks for understnading.
