### ISSUE TITLE
Setup Wizard not translated

### ISSUE THREAD

**Issue by marcochiesi** [woocommerce/woocommerce#27031]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When WordPress is set with a language other than English, the WooCommerce Setup Wizard is displayed (mostly) in English, even if all the strings are translated and included in the current translation (i.e. Italian, which is 100% translated).
It seems that all the untranslated strings come from JS files, while the ones that are translated come from PHP files.
I suppose the issue could be similar to https://github.com/woocommerce/woocommerce/issues/25920 as also the WooCommerce Admin interface is rendered with JavaScript.

**Expected behavior**
The Setup Wizard should use the same locale of the WordPress website.

**Actual behavior**
 The Setup Wizard is displayed (mostly) in English.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Configure WordPress in a locale other than English in Settings -> General
2. Install and activate WooCommerce
3. Run the setup Wizard

Or, alternatively, if WooCommerce is already installed,
1. Configure WordPress in a locale other than English in Settings -> General
2. Restart the Setup Wizard from WooCommerce -> Orders -> Help >- Setup Wizard -> Profile Setup Wizard -> Enable

**Screenshots**
![image](https://user-images.githubusercontent.com/2298248/87333129-f8236400-c53c-11ea-8a3c-4bed716d50a9.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @marcochiesi,

Thanks for reporting the issue. It seems similar to https://github.com/woocommerce/woocommerce/issues/26994. We are still investigating the translation issue and will be updating this thread with our findings soon. Thanks for your patience!

**Comment by fernandotellado** [comment]
Same Issue for Spanish (Spain) translations :(

**Comment by peterfabian** [comment]
Related to https://github.com/woocommerce/woocommerce/issues/26994 maybe?

**Comment by futurevisionweb** [comment]
Still have this issue for french.

**Comment by chihsuan** [comment]
![Screenshot 2023-04-18 at 15 34 03](https://user-images.githubusercontent.com/4344253/232705015-92b68dfb-6386-46e2-903e-634748daaa3e.png)

Closing this since OBW has been translated.
