### ISSUE TITLE
CSV Product Export overwrites data in XLS

### ISSUE THREAD

**Issue by sterenas** [woocommerce/woocommerce#27042]
CSV Export products with default options and metadata checkbox checked. 
Open the CSV file in Excel.
I'd expect all data to be on column A only since this is a CSV file.
In Excel, Menu Data / Text to Columns and choose coma as the delimiter
You get a mess and data is overwritten

Site language = Spanish
Thousands separator = . (dot)
Decimal separator = , (coma)
Site has simple and variable products

Could this be due to an internationalization issue?

WooCommerce/WP and all plugins -> latest version

**Comment by peterfabian** [comment]
Hi @sterenas , 

Apologies, but I don't believe we use Excel, so can't really test this out. Every sheet processing software (Excel, OpenOffice Calc, Google Sheets) imports CSVs slightly differently and as long as we export a CSV file in the correct format (which, I believe, we do), there is not much else we can do. 
Please let us know if you think the CSV file has any problem or there is any improvement we can do.
