### ISSUE TITLE
Remove State Field for Country Liechtenstein

### ISSUE THREAD

**Issue by masteradhoc** [woocommerce/woocommerce#27056]
Hi there

Liechtenstein is a very small country.
Because of the small popuplation of around 37'000 people we dont have states.

If country is liechtenstein please automatically remove the municipality/state field on checkout.
![Anmerkung 2020-07-17 083259](https://user-images.githubusercontent.com/6242098/87755911-330cec80-c808-11ea-96fc-881874c5e3c4.png)

Thanks
Brian

**Comment by michi-dev** [comment]
The same problem for me ... i totally agree

**Comment by claudiosanches** [comment]
Closed by https://github.com/woocommerce/woocommerce/pull/27057
