### ISSUE TITLE
Slow queries warning on large database

### ISSUE THREAD

**Issue by woorise** [woocommerce/woocommerce#27064]
On WooCommerce version 4.3 I get a warning for slow queries from Query Monitor plugin. It's a multisite installation with more than 50.000 database tables. WooCommerce is only enabled on main site.

Please check the attached screenshot:

![Screenshot_2020-07-17](https://user-images.githubusercontent.com/22965450/87813349-6718f980-c86a-11ea-9b70-abe0c0b396c8.png)

**Comment by rrennick** [comment]
@woorise `SHOW TABLES` is going to be slow in a database with 50K tables. The WordPress core `dbDelta()` function uses this query to determine whether tables need to be created. It is used by most plugins that create custom tables.

Do you have a significant number of these queries being run against your database?

**Comment by chris-vas** [comment]
Ιt needs to happen in every page load on admin?

I have one more plugin that creates custom tables but I don't get any warnings for slow queries.

Also for the same reason (because of the amount of tables I suppose) I can't access the Status page of WooCommerce.

**Comment by woorise** [comment]
Ιt needs to happen in every page load on admin?

I have one more plugin that creates custom tables but I don't get any warnings for slow queries.

Also for the same reason (because of the amount of tables I suppose) I can't access the Status page of WooCommerce.

**Comment by rrennick** [comment]
> Ιt needs to happen in every page load on admin?

In that case there is a DB update that is failing for some reason. Could you look through your debug logs (or query analyzer may have it) to see what it is?

**Comment by woorise** [comment]
I tool a look and I noticed that after some WooCommerce updates the issue is gone. So maybe it was a DB update that was falling.

The issue https://github.com/woocommerce/woocommerce/issues/27014 still remains though.

**Comment by tammullen** [comment]
Hi @woorise 

As a part of this repository’s maintenance, I am closing this issue as it appears to be resolved. Please feel free to comment on it in case we missed something. We’d be happy to take another look.
