### ISSUE TITLE
The word "includes" from (includes %s) isn't translating properly on many sites

### ISSUE THREAD

**Issue by apmwebdev** [woocommerce/woocommerce#27087]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I've been seeing a lot of requests from customers recently that the word "includes" is not translating properly for them. The specific context is the `(includes %s)` string that shows up in checkout to show the taxes. I can't replicate this at all, but I've been seeing this specific issue from too many different customers to think it is just a coincidence. One forum thread about it is [here](https://wordpress.org/support/topic/problem-with-includes-xx-not-translating-to-danish/).

A couple of people said they ran into the issue with fresh installs of WordPress using Twenty Twenty or Storefront as the theme and only WooCommerce and Loco Translate as plugins. Another user reported the same problem using Polylang instead of Loco Translate.

I'm creating this bug per @rrennick's instructions. He said:

> I’m seeing it with the translation file. I added some debug code where the string is being translated and don’t see anything logged. Create an issue so we can investigate.

**Expected behavior**
The `include` string should translate properly here.

**Actual behavior**
It shows up in English instead.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create a staging site and install WooCommerce. 
1. Change the site language to something different. The languages I've specifically seen reported with this issue are Danish, Dutch, Croatian, Finnish, and Estonian, although I doubt that the exact language matters.
1. Add another language for the WooCommerce plugin from translate.wordpress.org. 
1. Make sure the `(includes %s)` string is translated properly.
1. Make sure taxes are turned on. Screenshots of the exact tax settings for a couple of the sites experiencing the issue can be found on the [second page of the above forum thread](https://wordpress.org/support/topic/problem-with-includes-xx-not-translating-to-danish/page/2/).
1. Create a product that will be taxed.
1. Go to the front end of the site and add that product to the cart.
1. Go to checkout and add an address that should be taxed according to your tax settings.
1. Note that the word `includes` is not translated.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
This SSR is from one of the users in the aforementioned forum thread.

```
### WordPress Environment ###

WordPress address (URL): https://woocommerce.hairandskincare.dk
Site address (URL): https://woocommerce.hairandskincare.dk
WC Version: 4.3.0
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.0
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: da_DK
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.2.31
PHP Post Max Size: 32 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 7.70.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.32-MariaDB-cll-lve
Max Upload Size: 24 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.0
WC Database Prefix: wpqu_
Total databasestørrelse: 0.86MB
Database datastørrelse: 0.68MB
Database indexstørrelse: 0.18MB
wpqu_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpqu_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_actionscheduler_actions: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wpqu_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpqu_actionscheduler_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpqu_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_options: Data: 0.63MB + Index: 0.04MB + Engine MyISAM
wpqu_postmeta: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wpqu_posts: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wpqu_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpqu_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpqu_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_usermeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpqu_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpqu_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_wc_customer_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_wc_order_product_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_wc_order_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpqu_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpqu_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpqu_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 17
customize_changeset: 1
page: 8
post: 2
product: 12
revision: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: af Automattic – 4.3.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: af Automattic – 4.1.6
Hello Dolly: af Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: DKK (DKK)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop basisside: #6 - /shop/
Kurv: #7 - /kurv/
Checkout: #8 - /kasse/
Min konto: #9 - /min-konto/
Handelsbetingelser: ❌ Siden er ikke indstillet

### Theme ###

Name: Twenty Twenty
Version: 1.4
Author URL: https://da.wordpress.org/
Child Theme: ❌ – Hvis du redigerer WooCommerce i et hovedtema
som du ikke selv har udviklet
anbefaler vi
at du anvender et undertema (child theme). Se: Hvordan du opretter et undertema

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Gennemført: 2
Oldest: 2020-07-10 06:45:49 +0000
Newest: 2020-07-10 06:45:49 +0000

Igangværende: 1
Oldest: 2020-07-11 06:45:49 +0000
Newest: 2020-07-11 06:45:49 +0000
```
</details>

**Comment by jer23jk** [comment]
Add this in functions.php until bug resolved:

add_filter( 'gettext', function( $translation, $text, $domain ) {
	if ( $domain == 'woocommerce' ) {
		if ( $text == 'includes' ) { $translation = 'yourtranslation'; }
	}
	return $translation;
}, 10, 3 );

**Comment by rodrigoprimo** [comment]
I believe that what happened here is that in a recent WooCommerce release the way that this string is defined changed (https://github.com/woocommerce/woocommerce/commit/14a26aca2cde9c81ade02bdc6dd0a34e184a4202#diff-258e00eaddfa27b18ebd350e55997e8f8a52d245f26c4648fe4e7289cb4b7e22L321), so when users updated their store, the string was not translated in several languages. I tested now with Brazilian Portuguese, and the translation works as expected.

That being said, the change mentioned above made it harder to translate this string as it relied heavily on string concatenation. I created #28064 to address this.

Closing this issue for now, but please leave a comment if I'm missing something.
