### ISSUE TITLE
Product Count Incorrect - Cannot Reset

### ISSUE THREAD

**Issue by JackJDW** [woocommerce/woocommerce#27089]
I imported over 500 products from Shopify over to Woocommerce. 

After the import complete it showed the product count but never showed any products.

I no longer want to import these products. 

I have used the tools available within woocommerce to try and fix this issue, include clear transients, regenerate product tables etc... 

Any one have any idea what I can do to remove the "ghost" products?

**Comment by JackJDW** [comment]
![Screenshot 2020-07-21 at 17 54 11](https://user-images.githubusercontent.com/68608030/88083659-3fcc7000-cb7b-11ea-9048-d97aa0b2354c.png)

The published products are the correct amount.

**Comment by thomas-zg** [comment]
Have you tried to recount the terms?

**Comment by JackJDW** [comment]
Hi Thomas,

Yes ive tried that too!

I exported the products to see if they would show and they seem to!

Jack

**Comment by glagonikas** [comment]
@JackJDW can you check your database and confirm the `post_status` of those products in the `wp_posts` table? I suspect you might have set it to something other than `publish`, `draft`, `private`, `trash` during import.

If that's the case, you can either remove them using an sql query, or set them to a status like `trash` and then delete via admin

**Comment by JackJDW** [comment]
@glagonikas You are a life saver! 

It has created multiple posts, my question is can i delete them straight from the table. The post_status is set to -1 and I dont need them, it seems to only work when I change it to published and then delete them through the admin. 

Photo Attached..

![Screenshot 2020-07-22 at 12 46 25](https://user-images.githubusercontent.com/68608030/88172739-5d501700-cc19-11ea-8e43-43b358b91f73.png)

**Comment by JackJDW** [comment]
@glagonikas I would like to thank you!!

I have done around 500 searches on how to fix this!

I have now done it!

**Comment by glagonikas** [comment]
glad you sorted it!

Keep in mind that deleting posts viat the sql won't delete the postmeta, so you need to run a query to search for orphan postmeta if you delete them already.

Alternatively, if you haven't deleted them, you can update them to status `trash`, then delete them via admin, which will remove all related postmeta
