### ISSUE TITLE
Ampersand in Product Category via API

### ISSUE THREAD

**Issue by intelligentdb** [woocommerce/woocommerce#27086]
Noob, yes.

I have some experience with APIs, and just started working with WooCommerce (cURL from FileMaker). My first test, querying the store's list of Product Categories worked fine. However, I'm finding that the JSON result contains \&amp; encoding instead of decoding the escaped ampersand character.

**Prerequisites (mark completed items with an [x]):**
- [ ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

API query returns encoded ampersand character.

**Expected behavior**

Text string containing the ampersand character, unencoded.

**Actual behavior**

If the text of a Product Category contains an ampersand (&) character, the API query returns \&amp;

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**

[GET] https://sample.com/wp-json/wc/v3/products/categories?per_page=100&page=2

**Screenshots**

![image](https://user-images.githubusercontent.com/68602966/88073580-57d4cd00-cb44-11ea-8494-414e328802ff.png)

![image](https://user-images.githubusercontent.com/68602966/88073184-e7c64700-cb43-11ea-862b-04014f393d4c.png)

![image](https://user-images.githubusercontent.com/68602966/88073274-00366180-cb44-11ea-9c97-a1c96d43ae7c.png)

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>

`
### WordPress Environment ###

WordPress address (URL): https://sample.com
Site address (URL): https://sample.com
WC Version: 4.3.0
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.0
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 200 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Flywheel/4.1.0
PHP Version: 7.2.29-1+ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 300 MB
PHP Time Limit: 30
PHP Max Input Vars: 4000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.6.32-1+deb.sury.org~precise+0.1
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.0
WC Database Prefix: wp_
Total Database Size: 55.96MB
Database Data Size: 46.42MB
Database Index Size: 9.54MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.04MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ai1ec_cfg_aliases: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_bookly_appointments: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bookly_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bookly_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bookly_customer_appointments: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_bookly_holidays: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_bookly_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bookly_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bookly_payments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bookly_schedule_item_breaks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bookly_sent_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bookly_series: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bookly_services: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bookly_shop: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_bookly_staff: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bookly_staff_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bookly_staff_preference_orders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bookly_staff_schedule_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_bookly_staff_services: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_bookly_stats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bookly_sub_services: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.04MB + Index: 0.02MB + Engine MyISAM
wp_comments: Data: 0.49MB + Index: 0.39MB + Engine MyISAM
wp_et_bloom_stats: Data: 11.16MB + Index: 1.98MB + Engine MyISAM
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_addon_payment_callback: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_addon_payment_transaction: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.23MB + Index: 0.28MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.19MB + Index: 0.17MB + Engine InnoDB
wp_gg_folders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gg_galleries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gg_galleries_excluded: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gg_galleries_resources: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gg_photos: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gg_photos_pos: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gg_photos_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gg_settings_presets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gg_settings_sets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gg_stats: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gg_tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nf_objectmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nf_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ninja_forms_fav_fields: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_ninja_forms_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 6.85MB + Index: 1.38MB + Engine MyISAM
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_podsrel: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 10.73MB + Index: 1.31MB + Engine MyISAM
wp_posts: Data: 10.80MB + Index: 0.72MB + Engine MyISAM
wp_redirects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_view: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rg_lead: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_rg_lead_detail: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rhc_cache: Data: 0.04MB + Index: 0.01MB + Engine MyISAM
wp_rhc_events: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_social_users: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_taxonomymeta_bak: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_termmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.08MB + Index: 0.16MB + Engine MyISAM
wp_term_relationships: Data: 0.11MB + Index: 0.25MB + Engine MyISAM
wp_term_taxonomy: Data: 0.09MB + Index: 0.09MB + Engine MyISAM
wp_UPCP_Catalogues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_UPCP_Catalogue_Items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_UPCP_Categories: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_UPCP_Custom_Fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_UPCP_Fields_Meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_UPCP_Items: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_UPCP_Item_Images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_UPCP_SubCategories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_UPCP_Tagged_Items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_UPCP_Tags: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_UPCP_Tag_Groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_UPCP_Videos: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_uport: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_uport_categories: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_uport_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_usermeta: Data: 0.19MB + Index: 0.09MB + Engine MyISAM
wp_users: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfront_ure_options: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yith_wcwl: Data: 0.13MB + Index: 0.05MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.17MB + Index: 0.28MB + Engine InnoDB
wp_yoast_indexable: Data: 1.52MB + Index: 0.42MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.14MB + Index: 0.05MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.48MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

_pods_pod: 2
attachment: 2210
custom_css: 2
customize_changeset: 5
dvgalleries: 31
et_pb_layout: 3
events: 121
featured_item: 1
membership_plan: 19
nav_menu_item: 40
oembed_cache: 20
page: 112
pile_gallery: 1
popup: 7
popup_theme: 7
popuppress: 1
portfolio: 1
post: 123
product: 372
revision: 1012
shop_coupon: 1
shop_order: 60
shop_order_refund: 2
slgf_slider: 1
stone: 4
testimonial: 49
thrive_optin: 1
tribe_events: 18
tribe_organizer: 1
tribe_venue: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (33) ###

Gravity Forms: by Gravity Forms – 2.4.18
Titan Anti-spam & Security: by CreativeMotion – 7.1.4
Better Search Replace: by Delicious Brains – 1.3.3
Bloom: by Elegant Themes – 1.3.10
Bookly Pro (Add-on): by Bookly – 2.3
Bookly: by Bookly – 18.4
Classic Editor: by WordPress Contributors – 1.5
Custom Facebook Feed Pro Personal: by Smash Balloon – 3.13.1
DV Gallery: by Egemenerd – 1.5
Easy Testimonials: by Gold Plugins – 3.6.1
Social LikeBox & Feed: by Weblizar – 2.9.3
Gallery Custom Links: by Jordy Meow – 1.2.7
Site Kit by Google: by Google – 1.11.1
Gravity Forms AWeber Add-On: by Gravity Forms – 2.10
Gravity Forms PayPal Standard Add-On: by Gravity Forms – 3.3
Header and Footer Scripts: by Digital Liberation – 2.2.1
List Pages Shortcode: by Ben Huson
Aaron Harp – 1.7.4

Popup Maker: by Popup Maker – 1.11.0
Remove Orphan Shortcodes: by Meks – 1.1
s2Member Framework: by WP Sharks – 200301
The Events Calendar: by Modern Tribe
Inc. – 5.1.4

Ultra Portfolio - WordPress: by themepassion – 4.1
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.26

WooCommerce Admin: by WooCommerce – 1.3.0 – Installed version not tested with active version of WooCommerce 4.3.0
WooCommerce Stripe Gateway: by WooCommerce – 4.5.0 – Installed version not tested with active version of WooCommerce 4.3.0
WooCommerce Membership: by RightPress – 2.0.3 – Installed version not tested with active version of WooCommerce 4.3.0
WooCommerce: by Automattic – 4.3.0
WooSidebars: by WooCommerce – 1.4.5
Yoast SEO: by Team Yoast – 14.5 – Installed version not tested with active version of WooCommerce 4.3.0
WP All Import Pro: by Soflyy – 4.6.2
YITH WooCommerce Ajax Search: by YITH – 1.7.9 – Installed version not tested with active version of WooCommerce 4.3.0
YITH WooCommerce Wishlist: by YITH – 3.0.11 – Installed version not tested with active version of WooCommerce 4.3.0
Embed Plus for YouTube Pro - Gallery, Channel, Playlist, Live Stream: by Embed Plus for YouTube Team – 13.4

### Dropin Plugins (1) ###

db-error.php: db-error.php

### Must Use Plugins (1) ###

ET Support Center :: Must-Use Plugins Autoloader: by Elegant Themes –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #268 - /shop/
Cart: #1540 - /cart/
Checkout: #1541 - /checkout/
My account: #1542 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Divi
Version: 4.5.1
Author URL: http://www.elegantthemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 18
Oldest: 2020-06-22 19:51:05 -0400
Newest: 2020-07-21 08:58:52 -0400

Pending: 1
Oldest: 2020-07-22 08:58:52 -0400
Newest: 2020-07-22 08:58:52 -0400

`

</details>

**Comment by claudiosanches** [comment]
Hello @intelligentdb, thanks for opening this report.

> If the text of a Product Category contains an ampersand (&) character, the API query returns &amp;

I understand that you are expecting to use `&`, but this is the default behavior on WordPress, that's how all taxonomy terms get saved into `wp_terms` table.

See my test, I created two categories with the same name, one for products and another for posts:

![Screenshot from 2020-10-22 20-26-32](https://user-images.githubusercontent.com/1264099/96940016-f86cbd00-14a4-11eb-93f1-14e212e7dd7e.png)

So this is the expected behavior, and it should render correctly on HTML pages, also it's possible to decode as well, and keeping safe.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.
