### ISSUE TITLE
UPC/EAN Field for products

### ISSUE THREAD

**Issue by skullo27** [woocommerce/woocommerce#27106]
Woocommerce is one of the only major eCommerce systems that I know of that does not natively support UPC/EAN codes for products and does not provide a field for it. 

This is drastically needed as in today's landscape this piece of data is pretty much essential if you are selling physical goods. It is required by Google to run ads in google shopping which should alone be sufficient to warrant considering adding this. However, there are also other considerations, for example as businesses grow they maybe need to integrate with warehouse management systems such as Linnworks or Tradeghecko, or marketing suites such as ChannelAdvisor. Currently, this integration is problematic as Woocommerce does not support this data. This use case also highlights why using a custom solution or plugin to handle this is not ideal as any other platform developed for a Woocommerce integration would not support it without itself needing to be customised.

Bigcommerce, Magento and Shopify all support UPC/EAN product data out of the box and with no need for customisation which makes Woocommerce currently a poor choice for medium-sized merchants.

**Comment by sylvainddesjardins** [comment]
I'm totally agree with this

**Comment by erricgunawan** [comment]
+1 from 7633945-zen 

> We use SKU for ordering products from our various suppliers etc. but here in EU EAN is also required/used on all products with a barcode. SKU’s almost never have barcodes (so nothing to scan with the app).
>
> We could just change the SKU fields to the EAN codes but on the invoices the SKU is displayed for customers since SKU is frequently used by vendor for warranty claims. We also use SKU to place orders with the overseas vendors.
>
> Can we activate/find a separate EAN field that we can use for scanning items in the Woocommerce app?

### UPDATE

>There is already a field used for barcodes under productdata (productgegevens in Dutch), namely GTIN “Global Trade Item Number”.

![image001](https://github.com/woocommerce/woocommerce/assets/35628116/8f14dd41-7d2b-447e-a6b1-a9508a50b3bc)

>Maybe to make it easier for the developers to implement, link with the app in a possible future update.

**Comment by mattsherman** [comment]
Implemented by #49312
