### ISSUE TITLE
Japan Zip Code Format Issue

### ISSUE THREAD

**Issue by mribble** [woocommerce/woocommerce#27108]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
The shipping address verification system requires a hyphen in the correct spot for both shipping estimates and during the address verification checkout.  For example when requesting a shipping estimate if I set Country=Japan, Providence=Tokyo, City=Tokyo, and zipcode=1340088 I get "Please enter a valide postcode/ZIP.".  If I just change the zipcode to 134-0088 then it gives me a shipping rate.

**Expected behavior**
I would expect 1340088 and 134-0088 to work as a Japan zip code.

**Actual behavior**
If I use 1340088 as a zip code for Japan then woocommerce treats that as an invalid zipcode.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to https://www.dreamingrobots.com/
2. Click EEW Nano Store at top
3. Click on EEW Nano Bobbins (3 Pack)
4. Click "Add to cart" button
5. Click "View cart" button
6. Click calculate shipping link
7. Change Country to Japan, change prefecture to Tokyo, change city to Tokyo, Change Postcode/ZIP to 1340088 

This will cause an error saying "Please enter a valid postcode / ZIP."

If you change the postcode/ZIP to 134-0088 it will give you a postage rate.

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
`
### WordPress Environment ###

WordPress address (URL): https://www.dreamingrobots.com
Site address (URL): https://www.dreamingrobots.com
WC Version: 4.3.1
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.2
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.1
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.43 () OpenSSL/1.0.2k-fips
PHP Version: 7.2.31
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.10-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.1
WC Database Prefix: wp_
Total Database Size: 586.73MB
Database Data Size: 515.85MB
Database Index Size: 70.88MB
wp_woocommerce_sessions: Data: 1.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_items: Data: 1.52MB + Index: 0.25MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 15.52MB + Index: 8.97MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.25MB + Index: 0.86MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.20MB + Index: 0.19MB + Engine InnoDB
wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 21.05MB + Index: 1.38MB + Engine InnoDB
wp_comments: Data: 43.55MB + Index: 10.03MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mclean_refs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mclean_scan: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 11.09MB + Index: 4.03MB + Engine InnoDB
wp_oses_attachments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_oses_clicks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oses_emails: Data: 356.06MB + Index: 2.50MB + Engine InnoDB
wp_oses_email_attachments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_oses_failures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_oses_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 40.56MB + Index: 27.06MB + Engine InnoDB
wp_posts: Data: 14.31MB + Index: 4.41MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 7.52MB + Index: 8.97MB + Engine InnoDB
wp_users: Data: 1.52MB + Index: 0.55MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.20MB + Index: 0.16MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.28MB + Index: 0.30MB + Engine InnoDB
wp_wc_order_stats: Data: 0.22MB + Index: 0.33MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_woo_sales_country_region: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 302
custom_css: 1
feedback: 2915
jetpack_migration: 2
jp_img_sitemap: 3
jp_sitemap: 3
jp_sitemap_master: 3
nav_menu_item: 11
page: 26
post: 7
product: 11
product_variation: 6
revision: 184
shop_coupon: 4
shop_order: 7029
shop_order_refund: 131

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Akismet Anti-Spam: by Automattic – 4.1.6
Jetpack by WordPress.com: by Automattic – 8.7.1
Sendy Widget: by Webholics – 1.2
Storefront Powerpack: by WooCommerce – 1.5.0
WordPress Users & WooCommerce Customers Import Export(BASIC): by WebToffee – 1.4.2 – Installed version not tested with active version of WooCommerce 4.3.1
Product Feed PRO for WooCommerce: by AdTribes.io – 8.4.7
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.0.3
WooCommerce Google Ads Conversion Tracking: by Wolf+Bär Agency – 1.6.8 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.22 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Pre-Orders: by WooCommerce – 1.5.27 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Services: by Automattic – 1.23.2 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Square: by WooCommerce – 2.1.6
WooCommerce Waitlist: by Neil Pie – 2.1.24
WooCommerce: by Automattic – 4.3.1
WP Rocket: by WP Media – 3.6.2.1
WP Offload SES Lite: by Delicious Brains – 1.4.2
Smush: by WPMU DEV – 3.6.3

### Inactive Plugins (1) ###

WP Mail SMTP: by WPForms – 2.2.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Square ###

Environment: Production
Tokenization Enabled: ✔
Debug Mode: Off

### Action Scheduler ###

Complete: 832
Oldest: 2020-06-22 11:33:04 +0000
Newest: 2020-07-23 02:58:42 +0000

Pending: 2
Oldest: 2020-07-23 20:52:28 +0000
Newest: 2020-07-29 19:43:25 +0000

`
</details>

**Comment by tammullen** [comment]
Hi @mribble 

Thank you for taking the time reporting this bug, we really appreciate your help. 

We use Unicode CLDR for our information. Postal code validation data has been deprecated in CLDR. They note to use other services that are kept up to date such http://i18napis.appspot.com/address/data/JP

In that service they suggest the `-` should be optional. Our current regex requires it since https://github.com/woocommerce/woocommerce/pull/10886

https://github.com/woocommerce/woocommerce/blob/d23a5fd0a9b16091c0881172e8145702e9146e60/includes/class-wc-validation.php#L80
​
We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by mribble** [comment]
Thank you for finding the root cause and adding it to your future release schedule.
