### ISSUE TITLE
For some products, default variation is not selected, if a variation is selected, "Add to cart" button stay disabled

### ISSUE THREAD

**Issue by DamienMLBW** [woocommerce/woocommerce#27111]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
For some variable products (not all), default variation is not selected, if selected "Add to cart" stay disabled. The variations are correct and in stock so the Add to cart button should be clickable.

There is no javascript error in the console.

If I update the product the problem disappear only for this product. I can't find a way to update all the products at one time even in WooCommerce > Status > Tools. I have more than 1500 products.

**Expected behavior**
When the page is load, the default variation should be selected.

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to https://www.muralunique.com/product/downtown-toronto-at-night/
2. Click on any variation
3. Scroll down to "Add to cart"

**Screenshots**
![add-to-cart-disabled](https://user-images.githubusercontent.com/66086641/88291048-a8bfff00-ccc5-11ea-9ac5-8df72d704eb3.PNG)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
`
### WordPress Environment ###

WordPress address (URL): https://www.muralunique.com
Site address (URL): https://www.muralunique.com
WC Version: 4.3.1
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.2
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.1
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.3.20
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 8000
cURL Version: 7.71.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.23-MariaDB
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.1
WC Database Prefix: wp_
Total Database Size: 420.95MB
Database Data Size: 283.99MB
Database Index Size: 136.96MB
wp_woocommerce_sessions: Data: 22.05MB + Index: 1.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 9.52MB + Index: 9.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.30MB + Index: 0.13MB + Engine InnoDB
wp_commentmeta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_comments: Data: 11.52MB + Index: 9.09MB + Engine InnoDB
wp_duplicator_packages: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.28MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 1.52MB + Index: 0.30MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.05MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.34MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.28MB + Index: 0.22MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.20MB + Index: 0.13MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_strings: Data: 1.52MB + Index: 1.14MB + Engine InnoDB
wp_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_pages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_string_positions: Data: 0.25MB + Index: 0.06MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 0.19MB + Index: 0.03MB + Engine InnoDB
wp_icl_string_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate: Data: 8.52MB + Index: 1.52MB + Engine InnoDB
wp_icl_translate_job: Data: 0.16MB + Index: 0.09MB + Engine InnoDB
wp_icl_translations: Data: 1.52MB + Index: 6.06MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 9.39MB + Index: 0.13MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_img_optm: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_litespeed_img_optming: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_litespeed_optimizer: Data: 3.52MB + Index: 0.23MB + Engine InnoDB
wp_options: Data: 44.09MB + Index: 1.83MB + Engine InnoDB
wp_postmeta: Data: 82.61MB + Index: 48.16MB + Engine InnoDB
wp_posts: Data: 17.33MB + Index: 7.88MB + Engine InnoDB
wp_relevanssi: Data: 4.67MB + Index: 8.33MB + Engine MyISAM
wp_relevanssi_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_relevanssi_stopwords: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.22MB + Index: 0.31MB + Engine InnoDB
wp_terms: Data: 0.19MB + Index: 0.22MB + Engine InnoDB
wp_term_relationships: Data: 2.52MB + Index: 2.52MB + Engine InnoDB
wp_term_taxonomy: Data: 0.23MB + Index: 0.23MB + Engine InnoDB
wp_tinvwl_analytics: Data: 1.52MB + Index: 0.33MB + Engine InnoDB
wp_tinvwl_items: Data: 0.23MB + Index: 0.00MB + Engine InnoDB
wp_tinvwl_lists: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 24.56MB + Index: 23.06MB + Engine InnoDB
wp_users: Data: 2.52MB + Index: 1.33MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 1.47MB + Index: 0.92MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 0.45MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 1.02MB + Index: 0.22MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.38MB + Index: 0.19MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.13MB + Index: 0.11MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 12.52MB + Index: 5.06MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.08MB + Index: 0.16MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.17MB + Index: 0.06MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.50MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 7
acf-field-group: 5
attachment: 11114
csp_rules: 1
elementor_library: 32
follow_up_email: 2
installateur: 11
jet_options_preset: 1
jet-menu: 4
nav_menu_item: 97
oembed_cache: 1
page: 34
post: 84
product: 1530
product_variation: 3064
revision: 1707
shop_coupon: 3
shop_order: 11159
shop_order_refund: 13
uni_cpo_option: 15
wc_order_email: 1
wc_order_status: 8
wcpf_item: 12
wcpf_project: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (35) ###

Gravity Forms: by Gravity Forms – 2.4.19
WPML Multilingual CMS: by OnTheGoSystems – 4.3.16
Advanced Custom Fields PRO: by Elliot Condon – 5.8.11
Akismet Anti-Spam: by Automattic – 4.1.6
Customizer Export/Import: by The Beaver Builder Team – 0.9.1
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 3.2.5
Elementor Pro: by Elementor.com – 2.10.3
Elementor: by Elementor.com – 2.9.13
JetMenu: by Crocoblock – 2.0.4
JetTabs For Elementor: by Crocoblock – 2.1.6
Jupiter X Core: by Artbees – 1.16.1
MLBW Elementor Custom Elements: by My Little Big Web – 1.0.0
Relevanssi: by Mikko Saari – 4.7.2.1
TI WooCommerce Wishlist: by TemplateInvaders – 1.20.5 – Installed version not tested with active version of WooCommerce 4.3.1
Product Options and Price Calculation Formulas for WooCommerce – Uni CPO (Premium): by MooMoo Agency – 4.8.1 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Additional Variation Images: by WooCommerce – 1.7.21 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Extended Coupon Features FREE: by Soft79 – 3.1.4 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.5.7 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Elavon Converge Gateway: by SkyVerge – 2.4.2 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.0.3
WooCommerce Google Analytics Pro: by SkyVerge – 1.8.8 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Multilingual: by OnTheGoSystems – 4.9.1 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Order Status Manager: by SkyVerge – 1.11.2 – Installed version not tested with active version of WooCommerce 4.3.1
Product Filters for WooCommerce: by Nexter – 1.1.16 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Sequential Order Numbers Pro: by SkyVerge – 1.15.1 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Shipment Tracking: by WooCommerce – 1.6.18 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Smart Coupons: by StoreApps – 4.3.0 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce: by Automattic – 4.3.1
Yoast SEO: by Team Yoast – 14.6.1
Asset CleanUp: Page Speed Booster: by Gabriel Livan – 1.3.6.5
WP Rocket | Cache Dynamic Cookie: by WP Rocket Support Team –
WP Rocket: by WP Media – 3.6.2.1
WPC Variations Radio Buttons for WooCommerce: by WPClever.net – 2.1.3
WPML String Translation: by OnTheGoSystems – 3.0.12
WPML Translation Management: by OnTheGoSystems – 2.9.9

### Inactive Plugins (3) ###

Follow-Up Emails: by WooCommerce – 4.8.16 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce Additional Variation Images: by WooCommerce – 1.7.17 – Installed version not tested with active version of WooCommerce 4.3.1
Wordfence Security: by Wordfence – 7.4.9

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #404 - /murals/
Cart: #405 - /cart/
Checkout: #406 - /complete-the-order/
My account: #407 - /my-account/
Terms and conditions: #31324 - /terms-and-conditions/

### Theme ###

Name: JupiterX Child
Version: 1.0.0
Author URL: https://jupiterx.com
Child Theme: ✔
Parent Theme Name: JupiterX
Parent Theme Version: 1.19.0
Parent Theme Author URL: https://artbees.net/
WooCommerce Support: ✔

### Templates ###

Overrides: jupiterx/lib/templates/woocommerce/cart/cart.php
jupiterx/lib/templates/woocommerce/checkout/thankyou.php
jupiterx/lib/templates/woocommerce/content-product.php
jupiterx-child/lib/templates/woocommerce/loop/add-to-cart.php
jupiterx-child/lib/templates/woocommerce/loop/price.php
jupiterx/lib/templates/woocommerce/loop/rating.php
jupiterx-child/lib/templates/woocommerce/order/order-details-item.php
jupiterx/lib/templates/woocommerce/single-product/add-to-cart/grouped.php
jupiterx/lib/templates/woocommerce/single-product/add-to-cart/simple.php
jupiterx/lib/templates/woocommerce/single-product/add-to-cart/variable.php
jupiterx/lib/templates/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
jupiterx/lib/templates/woocommerce/single-product/meta.php
jupiterx-child/single-product/product-image.php
jupiterx-child/lib/templates/woocommerce/single-product/related.php

### Elavon Converge Credit Card ###

Environment: Production
Tokenization Enabled: –
Debug Mode: Save to Log

### TI WooCommerce Wishlist Templates ###

Overrides: –

### Action Scheduler ###

Complete: 350
Oldest: 2020-07-22 17:29:38 -0400
Newest: 2020-07-22 17:34:06 -0400

Pending: 1
Oldest: 2020-07-23 17:29:38 -0400
Newest: 2020-07-23 17:29:38 -0400

`

**Comment by DamienMLBW** [comment]
I inspected the code to select in the html a variation and enable the Add To Cart button but when the page relaod it says "Choose an option ...".

Unofrtunately I can't wait so I used this plugin to bulk resave all my products : PW WooCommerce Bulk Edit

I will reopen this if the problem happens again.

**Comment by DamienMLBW** [comment]
Unfortunatelly, the problem happens again : https://www.muralunique.com/product/toy-building-blocks/
Can a woocommerce wp-cron cause this ?

**Comment by Joshykins** [comment]
Looks to be same as these issues https://github.com/woocommerce/woocommerce/issues/27076, https://github.com/woocommerce/woocommerce/issues/27076.

**Comment by DamienMLBW** [comment]
Thank you I will answer in the other thread.
