### ISSUE TITLE
Reopening #26923 - WooCommerce Status says "My Account" not set up although it works fine...

### ISSUE THREAD

**Issue by gevcen** [woocommerce/woocommerce#27124]
Dear,

I'd like to re-open the issue #26923 with the following screencast as evidence for the issue : https://sgevcen.tinytake.com/tt/NDQ4NDcwN18xNDE5OTc1OA

Thanks

**Comment by tammullen** [comment]
Hi @gevcen 

I will re-open previously reported issue https://github.com/woocommerce/woocommerce/issues/26923 . 
We are closing this issue in favor of the previously submitted. 

Can you post your screencast on that issue and continue sharing your feedback there if needed.
