### ISSUE TITLE
Hide Shipping Address and Shipping Calculator when 'Local Pickup' is selected on cart page

### ISSUE THREAD

**Issue by pickmeok** [woocommerce/woocommerce#27127]
Hello,

On **cart page** it is quite confusing for customers to see the 'Ship to address' and 'Shipping Calculator' below the provided 'Shipping Options' when he selects (radio buton) 'Pickup from store'.

How could these two be hidden, upon ' Pickup from store' is selected on **Cart Page**.

Thank you

**Comment by tammullen** [comment]
Hi @pickmeok 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.
​
We don't offer technical support on GitHub so we recommend using the following:

**Reading our documentation**
Usage docs can be found here: https://docs.woocommerce.com/

If you have a problem, you may want to start with the self help guide here: https://docs.woocommerce.com/document/woocommerce-self-service-guide/

**Technical support for premium extensions or if you're a WooCommerce.com customer**
Contact WooCommerce support by opening a ticket.
https://woocommerce.com/contact-us/ 

**For help with custom code**
WooCommerce Slack Community: https://woocommerce.com/community-slack/ in the `#developers` channel. 

**General usage and development questions**
- WooCommerce Slack Community: https://woocommerce.com/community-slack/
- WordPress.org Forums: https://wordpress.org/support/plugin/woocommerce
- The Official WooCommerce Facebook Group https://www.facebook.com/groups/advanced.woocommerce/

If you confirm a bug, please open a new issue and provide us with clear steps to reproduce it.
​
I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.
