### ISSUE TITLE
Cannot select options in Woocommerce setting

### ISSUE THREAD

**Issue by JBabe101** [woocommerce/woocommerce#27134]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
My site was working well, and all of a sudden I am not able to select any options in the Woocommerce settings page.  Below is a status report copied from my site:

`
### WordPress Environment ###

WordPress address (URL): https://www.uniqo.co.za
Site address (URL): https://www.uniqo.co.za
WC Version: 4.3.1
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 3.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.1
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.8
PHP Post Max Size: 8 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 10.2.32-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.1
WC Database Prefix: wpucl_
Total Database Size: 10.81MB
Database Data Size: 9.28MB
Database Index Size: 1.53MB
wpucl_woocommerce_sessions: Data: 1.25MB + Index: 0.04MB + Engine MyISAM
wpucl_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpucl_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_woocommerce_order_items: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpucl_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.05MB + Engine MyISAM
wpucl_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_actionscheduler_actions: Data: 0.06MB + Index: 0.04MB + Engine MyISAM
wpucl_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpucl_actionscheduler_logs: Data: 0.04MB + Index: 0.03MB + Engine MyISAM
wpucl_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_comments: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wpucl_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_mailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_mailchimp_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_nm_personalized: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_options: Data: 3.43MB + Index: 0.27MB + Engine MyISAM
wpucl_postmeta: Data: 2.09MB + Index: 0.57MB + Engine MyISAM
wpucl_posts: Data: 2.08MB + Index: 0.18MB + Engine MyISAM
wpucl_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpucl_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpucl_term_relationships: Data: 0.02MB + Index: 0.04MB + Engine MyISAM
wpucl_term_taxonomy: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpucl_usermeta: Data: 0.11MB + Index: 0.08MB + Engine MyISAM
wpucl_users: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpucl_w3tc_cdn_pathmap: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_w3tc_cdn_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_wcpdf_invoice_number: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpucl_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_wc_order_product_lookup: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wpucl_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpucl_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_wc_product_meta_lookup: Data: 0.03MB + Index: 0.05MB + Engine MyISAM
wpucl_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wpucl_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wpucl_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wpucl_yith_wcwl_lists: Data: 0.03MB + Index: 0.03MB + Engine MyISAM

### Post Type Counts ###

attachment: 766
feedback: 12
fpf_fields: 1
jetpack_migration: 2
jp_img_sitemap: 3
jp_sitemap: 3
jp_sitemap_master: 3
jp_vid_sitemap: 3
nav_menu_item: 30
o-discount: 1
o-list: 1
page: 11
post: 1
product: 256
product_variation: 169
revision: 70
shop_order: 44
uni_cpo_option: 1
wcpa_pt_forms: 1
woo_discount: 2
woo_discount_cart: 1
ywdpd_discount: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (16) ###

Coming Soon Page, Under Construction & Maintenance Mode by SeedProd: by SeedProd – 5.1.3
Facebook for WooCommerce: by Facebook – 1.11.4 – Installed version not tested with active version of WooCommerce 4.3.1
Site Kit by Google: by Google – 1.12.0
Jetpack by WordPress.com: by Automattic – 8.7.1
Mailchimp for WooCommerce: by Mailchimp – 2.4.1 – Installed version not tested with active version of WooCommerce 4.3.1
Max Mega Menu: by megamenu.com – 2.8
Change Storefront Footer Copyright Text: by QuadLayers – 1.0.1 – Installed version not tested with active version of WooCommerce 4.3.1
W3 Total Cache: by BoldGrid – 0.14.3
WooCommerce Blocks: by Automattic – 3.0.0 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce PayFast Gateway: by WooCommerce – 1.4.15 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.5.3
WooCommerce Services: by Automattic – 1.23.2 – Installed version not tested with active version of WooCommerce 4.3.1
WooCommerce: by Automattic – 4.3.1
wpCentral: by Softaculous Ltd. – 1.5.3
YellowPencil: by WaspThemes – 7.3.1
YITH WooCommerce Wishlist: by YITH – 3.0.11 – Installed version not tested with active version of WooCommerce 4.3.1

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: db.php
object-cache.php: object-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: ZAR (R)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #35 - /products/
Cart: #36 - /cart/
Checkout: #37 - /checkout/
My account: #38 - /my-account/
Terms and conditions: #2 - /sample-page/

### Theme ###

Name: Storefront
Version: 2.5.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 64
Oldest: 2020-06-27 00:06:53 +0000
Newest: 2020-07-27 09:34:27 +0000

Pending: 1
Oldest: 2020-07-28 04:20:13 +0000
Newest: 2020-07-28 04:20:13 +0000

**Comment by juliaamosova** [comment]
Hi @JBabe101,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.
