### ISSUE TITLE
[4.4] Pagination of custom product queries broken

### ISSUE THREAD

**Issue by franticpsyx** [woocommerce/woocommerce#27163]
**Prerequisites (mark completed items with an [x]):**

- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

Since https://github.com/woocommerce/woocommerce/pull/26260 was merged, the pagination of all custom product queries run by third-party code appears broken. This came up in Composite Products e2e tests running against the latest beta.

We've tracked down the cause to the `adjust_posts_count` filter introduced [here](https://github.com/woocommerce/woocommerce/pull/26260/files#diff-fd1cd974e8c35c334c7b3b83e29aa0b6R48). 

This filter seems to affect every product query running on a WooCommerce site, not just the main WooCommerce product query. 

Another problem with this filter is that it will cause severe performance issues with queries that return hundreds or thousands of product IDs, as it will unnecessarily create instances for all of them.  

**Possible solution**

Limit this filter to the main product query. The callback could check if `$query->get( 'wc_query' )` is empty and return the unmodified count.

**Expected behavior**

Custom product queries should not be affected by this.

**Actual behavior**

The `found_posts` count of custom product queries is affected by this filter.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**

Create a custom, paginated product query. The count of `found_posts` will be filtered based on the main query, and the pagination of the custom query will be broken.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @franticpsyx,

Thanks for reporting the issue. I am marking this with 4.4 milestone so that we could take a look at it asap.

**Comment by franticpsyx** [comment]
Thanks @juliaamosova — we opened https://github.com/woocommerce/woocommerce/pull/27166 to make things a bit easier for you. The PR seems to make all of our e2e tests pass with WC 4.4.
