### ISSUE TITLE
Variable Products broken in WC 4.3.1 and WP 5.5RC1(also with WC 4.4 Beta and WP 5.5RC1)

### ISSUE THREAD

**Issue by Danielspain22** [woocommerce/woocommerce#27167]
**Prerequisites (mark completed items with an [x]):**
- [x ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
After upgrading to wp 5.5 RC1 on a staging site can't add a variable product. 

**Expected behavior**
Product data dropdown (where variable, single, etc is choosen) should appear after add new product.

**Actual behavior**
The product data dropdown doesn't appear anymore when you create a new product. Also, in front end variation attributes are sometimes not shown in some themes.(can't add variable products in backend with ANY theme, like twenty-twenty)

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Go to: WooCommerce > Products. Select the Add Product button. The Product Data selector doesn´t appear anymore(for choosing product types). 

**Isolating the problem (mark completed items with an [x]):**
- [ X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ X] I can reproduce this bug consistently using the steps above.

No plugin or theme related. Hope this get fixed before wp 5.5 final release...(as the calendar shows, wc 4.4 will be released AFTER wp 5.5 comes out...)
thanks

**Comment by Danielspain22** [comment]
The same happens if you try WP5.5 RC1 with Woocommerce 4.4 beta

**Comment by juliaamosova** [comment]
Hi @Danielspain22,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

Using WooCommerce 4.4 beta1 and WordPress 5.5-RC1-48681:

![product](https://user-images.githubusercontent.com/19143190/88849942-9dcf0800-d1b8-11ea-90f0-d93f7ff1dd75.jpg)

We’re going to work on this bug as soon as possible.

**Comment by DavidWalters123** [comment]
Im having this issue all of a sudden... is there a solution for this?

**Comment by DominatorCode** [comment]
After updating to a last plugin and WP versions problem was solved
