### ISSUE TITLE
wc 4.4 beta don't show previous orders as a logged customer(in the backend are ok)

### ISSUE THREAD

**Issue by Danielspain22** [woocommerce/woocommerce#27162]
**Prerequisites (mark completed items with an [x]):**
- [ x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Upgraded on a staging site to wc 4.4 beta from 4.3.1. Everything is fine but, if i log as a customer with previous orders and visit
My Account, Orders a message appears:
**No order has been made yet.**
(and the user has a lot of orders), "in wc 4.3.1 the list of orders, when the customer is logged are ok, only happens in the 4.4 beta "

**Expected behavior**
The usual list of orders of the logged user must be shown.

**Actual behavior**
No previous orders are shown(to the customer as a logged user, in the backend the orders are fine for all customers)

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
Upgrade to wc 4.4 beta from 4.3.1 , log as a customer with previous orders, or make new ones, and go to my orders.

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

This happens with all plugins deactivated and with a default theme too(tested with twenty-twenty). No plugin or theme-related.

**Comment by juliaamosova** [comment]
Hi @Danielspain22,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

Logged in as a customer in WC 4.3.1:

<img width="845" alt="Screen Shot 2020-07-29 at 10 41 17 AM" src="https://user-images.githubusercontent.com/19143190/88814503-30a37e80-d188-11ea-9cc1-39543fdcd48f.png">

Logged in as the same customer after upgrading to WC 4.4 beta1:

<img width="832" alt="Screen Shot 2020-07-29 at 10 39 54 AM" src="https://user-images.githubusercontent.com/19143190/88814564-41ec8b00-d188-11ea-9ce7-13a422a453e5.png">

We’re going to work on this bug as soon as possible.
