### ISSUE TITLE
Virtual or downloadable option not showing in product data after Updating 4.4.0 beta

### ISSUE THREAD

**Issue by izavishek** [woocommerce/woocommerce#27189]
I update Woocommerce plugin to beta version after updating downloadable & virtual option is missing I already tried to revert to old version but still missing

Theme woodmart

**Comment by tammullen** [comment]
Hi @izavishek,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/27167. 
We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
