### ISSUE TITLE
Cart session destroy with every browser reload on checkout/cart page

### ISSUE THREAD

**Issue by eshimischi** [woocommerce/woocommerce#27203]
Hello!

Here is my report:
`
### WordPress Environment ###

WordPress address (URL): https://xn--43-6kc4be0fbz.xn--p1ai/cms
Site address (URL): https://xn--43-6kc4be0fbz.xn--p1ai
WC Version: 4.3.1
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.2
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.1
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: ru_RU
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.7
PHP Version: 7.2.31
PHP Post Max Size: 5 GB
PHP Time Limit: 14400
PHP Max Input Vars: 10000
cURL Version: 7.35.0
OpenSSL/1.0.1f

SUHOSIN Installed: –
MySQL Version: 5.6.39-83.1
Max Upload Size: 5 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.1
WC Database Prefix: 91669c_
Общий размер базы данных: 12.73MB
Размер данных в базе данных: 11.45MB
Размер индекса базы данных: 1.28MB
91669c_woocommerce_sessions: Данные: 0.01MB + Индекс: 0.00MB + Движок MyISAM
91669c_woocommerce_api_keys: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_woocommerce_attribute_taxonomies: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_woocommerce_downloadable_product_permissions: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_woocommerce_order_items: Данные: 0.07MB + Индекс: 0.03MB + Движок MyISAM
91669c_woocommerce_order_itemmeta: Данные: 0.42MB + Индекс: 0.30MB + Движок MyISAM
91669c_woocommerce_tax_rates: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_woocommerce_tax_rate_locations: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_woocommerce_shipping_zones: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_woocommerce_shipping_zone_locations: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_woocommerce_shipping_zone_methods: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_woocommerce_payment_tokens: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_woocommerce_payment_tokenmeta: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_woocommerce_log: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_actionscheduler_actions: Данные: 0.02MB + Индекс: 0.02MB + Движок MyISAM
91669c_actionscheduler_claims: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_actionscheduler_groups: Данные: 0.00MB + Индекс: 0.01MB + Движок MyISAM
91669c_actionscheduler_logs: Данные: 0.02MB + Индекс: 0.02MB + Движок MyISAM
91669c_aiowps_events: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_aiowps_failed_logins: Данные: 0.11MB + Индекс: 0.04MB + Движок MyISAM
91669c_aiowps_global_meta: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_aiowps_login_activity: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_aiowps_login_lockdown: Данные: 0.15MB + Индекс: 0.04MB + Движок MyISAM
91669c_aiowps_permanent_block: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_commentmeta: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_comments: Данные: 0.06MB + Индекс: 0.03MB + Движок MyISAM
91669c_links: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_nextend2_image_storage: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_nextend2_section_storage: Данные: 0.00MB + Индекс: 0.01MB + Движок MyISAM
91669c_nextend2_smartslider3_generators: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_nextend2_smartslider3_sliders: Данные: 0.01MB + Индекс: 0.00MB + Движок MyISAM
91669c_nextend2_smartslider3_sliders_xref: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_nextend2_smartslider3_slides: Данные: 0.00MB + Индекс: 0.01MB + Движок MyISAM
91669c_odb_logs: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_options: Данные: 1.35MB + Индекс: 0.05MB + Движок MyISAM
91669c_pmxi_files: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_pmxi_history: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_pmxi_images: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_pmxi_imports: Данные: 0.01MB + Индекс: 0.00MB + Движок MyISAM
91669c_pmxi_posts: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_pmxi_templates: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_postmeta: Данные: 6.43MB + Индекс: 0.42MB + Движок MyISAM
91669c_posts: Данные: 2.62MB + Индекс: 0.10MB + Движок MyISAM
91669c_regenerate_dir_images: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_termmeta: Данные: 0.00MB + Индекс: 0.01MB + Движок MyISAM
91669c_terms: Данные: 0.00MB + Индекс: 0.01MB + Движок MyISAM
91669c_term_relationships: Данные: 0.01MB + Индекс: 0.02MB + Движок MyISAM
91669c_term_taxonomy: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_usermeta: Данные: 0.01MB + Индекс: 0.01MB + Движок MyISAM
91669c_users: Данные: 0.00MB + Индекс: 0.01MB + Движок MyISAM
91669c_wc_admin_notes: Данные: 0.01MB + Индекс: 0.00MB + Движок MyISAM
91669c_wc_admin_note_actions: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_wc_category_lookup: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_wc_customer_lookup: Данные: 0.01MB + Индекс: 0.01MB + Движок MyISAM
91669c_wc_download_log: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_wc_order_coupon_lookup: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_wc_order_product_lookup: Данные: 0.10MB + Индекс: 0.08MB + Движок MyISAM
91669c_wc_order_stats: Данные: 0.02MB + Индекс: 0.02MB + Движок MyISAM
91669c_wc_order_tax_lookup: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_wc_product_meta_lookup: Данные: 0.01MB + Индекс: 0.02MB + Движок MyISAM
91669c_wc_reserved_stock: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM
91669c_wc_tax_rate_classes: Данные: 0.00MB + Индекс: 0.01MB + Движок MyISAM
91669c_wc_webhooks: Данные: 0.00MB + Индекс: 0.00MB + Движок MyISAM

### Post Type Counts ###

attachment: 334
nav_menu_item: 4
page: 13
post: 1
postman_sent_mail: 250
product: 156
shop_order: 253
wpcf7_contact_form: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

All In One WP Security: от Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.4.4

Autoclear Autoptimize Cache: от Theme Surgeons – 2.0.0
Autoptimize: от Frank Goossens (futtta) – 2.7.6
Classic Editor Addon: от <a href="https://so-wp.com">Pieter Bos</a>
<a href="https://gschoppe.com">Greg Schoppe</a> – 2.6.2

Classic Editor: от Участники разработки WordPress – 1.5
Controls for Contact Form 7: от Kaspars Dambis – 0.8.0
Honeypot for Contact Form 7: от Nocean – 1.14.1
Contact Form 7: от Takayuki Miyoshi – 5.2
Cyrillic Permalinks: от Petko Bossakov – 2.0.1
Make Paths Relative: от YAS Global Team – 1.1.2
Post SMTP: от Yehuda Hassine – 2.0.12
Product CSV Import Export (BASIC): от WebToffee – 1.8.2
Regenerate Thumbnails: от Alex Mills (Viper007Bond) – 3.1.3
Оптимизация базы данных: от CAGE Web Design | Рольф Ван Гелдер
Эйндховен
Нидерланды – 4.9.1

Безопасный SVG: от Daryll Doyle – 1.9.9
Smart Slider 3: от Nextend – 3.4.1.8
Soil: от Roots – 3.9.0
WooCommerce: от Automattic – 4.3.1

### Inactive Plugins (2) ###

Mobile Detect: от Pothi Kalimuthu – 1.2.0
The SEO Framework: от The SEO Framework Team – 4.0.7

### Must Use Plugins (2) ###

Bedrock Autoloader: от Roots – 1.0.3
Register Theme Directory: от Roots – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: RUB (руб.)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Ссылка магазина: ❌ Страница не задана
Корзина: ❌ Страница не содержит шорткода.
Оформление заказа: #25 - /checkout/
Мой аккаунт: ❌ Страница не задана
Правила и условия: ❌ Страница не задана

### Theme ###

Name: Kebab
Version: 1.0.0
Author URL: https://brandmaker.ru
Child Theme: ❌ – Если вы хотите оформить WooCommerce родительской темой
которую создал кто-то другой
мы рекомендуем воспользоваться дочерней темой. См. "Как создать дочернюю тему"

WooCommerce Support: ✔

### Templates ###

Overrides: Есть обновления для kebab-theme/woocommerce/archive-product.php версии -. Версия ядра — 3.4.0
Есть обновления для kebab-theme/woocommerce/cart/cart-empty.php версии -. Версия ядра — 3.5.0
Есть обновления для kebab-theme/woocommerce/cart/cart.php версии -. Версия ядра — 3.8.0
Есть обновления для kebab-theme/woocommerce/checkout/form-checkout.php версии -. Версия ядра — 3.5.0
Есть обновления для kebab-theme/woocommerce/checkout/thankyou.php версии -. Версия ядра — 3.7.0
Есть обновления для kebab-theme/woocommerce/content-product.php версии -. Версия ядра — 3.6.0
Есть обновления для kebab-theme/woocommerce/content-product_cat.php версии -. Версия ядра — 2.6.1
kebab-theme/woocommerce/emails/email-styles.php
Есть обновления для kebab-theme/woocommerce/global/quantity-input.php версии -. Версия ядра — 4.0.0

Outdated Templates: ❌

### Action Scheduler ###

Выполнено: 87
Oldest: 2020-07-02 17:56:01 +0000
Newest: 2020-08-02 14:01:02 +0000

`

1) After update to latest version of Woocommerce i do not see jquery.BlockUi.js, wc-checkout.js and woocommerce.js loading in my scripts anymore and it broke my custom WC script and shop functionality
2) Adding products to cart is working, but every time i go to my cart/checkout page with every reload of the page my
wc_cart_hash_xxxxxxxxxxxxxxxxxxxxxx lose it value and cart became clear. It only works after i visit /checkout/ page, neither products pages nor any other page.
3) I manually added WC scripts ( jquery.BlockUi.js, wc-checkout.js and woocommerce.js) and my cart/checkout page show that my session is expired with every page reload.

Do not understand where to look. Please help?

**Comment by juliaamosova** [comment]
Hi @eshimischi,

Thank you for raising the issue.

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by eshimischi** [comment]
> Hi @eshimischi,
> 
> Thank you for raising the issue.
> 
> I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
> 
> If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Спасибо, Юлия! Thanks, i'll check it and return back with a results.

**Comment by eshimischi** [comment]
After tests with plugins and my custom WP theme, i've found what caused my issue. It has nothing to do with Woocommerce but with JS library [Quicklink](https://github.com/GoogleChromeLabs/quicklink) i use in my theme, i forgot to add [noprefetch] attribute to delete icon in my cart and it caused deletion of cart content with every page reload. I'll be wiser since now. Thanks!

**Comment by juliaamosova** [comment]
Glad to hear you found the cause of the issue and thanks for letting us know @eshimischi!
