### ISSUE TITLE
Woocommerce Documentation missing

### ISSUE THREAD

**Issue by teledirigido** [woocommerce/woocommerce#27223]
Something had happened now and the Woocommerce documentation is no longer available:

Eg:
https://docs.woocommerce.com/wc-apidocs/class-WC_Order.html
https://docs.woocommerce.com/wc-apidocs/class-WC_Product.html
https://docs.woocommerce.com/wc-apidocs/class-WC_Product_Variation.html
https://docs.woocommerce.com/wc-apidocs/class-WC_Abstract_Legacy_Product.html
https://docs.woocommerce.com/wc-apidocs/class-WC_Product_Simple.html

Where can we find this now?

**Comment by juliaamosova** [comment]
Hi @teledirigido,

Thanks for the ping - we are currently investigating the issue. 

In the meantime, the docs can be found here: https://docs.woocommerce.com/wc-apidocs/index.html

For example, https://docs.woocommerce.com/wc-apidocs/class-WC_Order.html can now be accessed at https://docs.woocommerce.com/wc-apidocs/classes/WC-Order.html.

**Comment by claudiosanches** [comment]
I'm working on include some rewrite rules to fix it.
Closing since it isn't a bug on WooCommerce, and the links still exists there.

**Comment by ktmn** [comment]
Still commonly getting 404s for first Google results
