### ISSUE TITLE
Ensure WC is ready for jQuery-migrate drop in WP 5.5

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#27243]
[WP 5.5 is dropping jQuery migrate](https://core.trac.wordpress.org/ticket/37110#comment:139), so we need to check our code to make sure we're ready.

**Comment by DavidAnderson684** [comment]
It's WP 5.6 that's updating jQuery to v3; in 5.5 what's happening is the removal of jQuery migrate - https://make.wordpress.org/core/2020/06/29/updating-jquery-version-shipped-with-wordpress/

**Comment by peterfabian** [comment]
Thanks for the correction, @DavidAnderson684 ! I've updated the issue.

**Comment by peterfabian** [comment]
No problems with jQuery migrate reported afaik, so closing this issue.
