### ISSUE TITLE
[WC Beta Tester] Bug report for version "4.4.0-beta.1"

### ISSUE THREAD

**Issue by ben72** [woocommerce/woocommerce#27264]
**Describe the bug**
Widgets "Filter Products by Attribute" and "Acitve Products Filters" not visible on front-end after switching to the beta version.
Price filter is visible though. No html is output for those filters at all.

**To Reproduce**
1. Add an attribute filter to a widget area
2. View fron-end
3. Switch to beta version
4. Widget is not visible on front-end

**Expected behavior**
The widgets should be visible as before.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://dev3.mydomain.se
Site address (URL): https://dev3.mydomain.se
WC Version: 4.4.0
REST API Version: ✔ 1.0.11
WC Blocks Version: ✔ 3.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.4.0-beta.2
Log Directory Writable: ✔
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: sv_SE
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.8
PHP Post Max Size: 64 MB
PHP Time Limit: 180
PHP Max Input Vars: 5000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.49-cll-lve
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.4.0
WC Database Prefix: c67imyiip_
Total Database Size: 205.64MB
Database Data Size: 128.12MB
Database Index Size: 77.52MB
c67imyiip_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
c67imyiip_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
c67imyiip_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
c67imyiip_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
c67imyiip_woocommerce_order_items: Data: 3.52MB + Index: 1.52MB + Engine InnoDB
c67imyiip_woocommerce_order_itemmeta: Data: 25.56MB + Index: 28.09MB + Engine InnoDB
c67imyiip_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
c67imyiip_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
c67imyiip_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
c67imyiip_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
c67imyiip_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
c67imyiip_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
c67imyiip_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
c67imyiip_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_actionscheduler_actions: Data: 0.43MB + Index: 0.19MB + Engine MyISAM
c67imyiip_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
c67imyiip_actionscheduler_logs: Data: 0.36MB + Index: 0.27MB + Engine MyISAM
c67imyiip_adtribes_my_conversions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_affiliate_wp_affiliatemeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_affiliate_wp_affiliates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_affiliate_wp_campaigns: Data: 0.00MB + Index: 0.00MB + Engine
c67imyiip_affiliate_wp_creatives: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_affiliate_wp_customermeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_affiliate_wp_customers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_affiliate_wp_payouts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_affiliate_wp_referrals: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_affiliate_wp_rest_consumers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_affiliate_wp_visits: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_cart_notices: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_commentmeta: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
c67imyiip_comments: Data: 7.33MB + Index: 3.13MB + Engine MyISAM
c67imyiip_failed_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
c67imyiip_gf_draft_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_gf_entry: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
c67imyiip_gf_entry_meta: Data: 0.11MB + Index: 0.08MB + Engine MyISAM
c67imyiip_gf_entry_notes: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
c67imyiip_gf_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_gf_form_meta: Data: 0.06MB + Index: 0.00MB + Engine MyISAM
c67imyiip_gf_form_revisions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_gf_form_view: Data: 2.82MB + Index: 1.32MB + Engine MyISAM
c67imyiip_gf_rest_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_iconic_was_fees: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
c67imyiip_itsec_dashboard_events: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
c67imyiip_itsec_distributed_storage: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_itsec_fingerprints: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_itsec_geolocation_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_itsec_lockouts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
c67imyiip_itsec_logs: Data: 1.64MB + Index: 0.49MB + Engine MyISAM
c67imyiip_itsec_mutexes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_itsec_opaque_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_itsec_temp: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
c67imyiip_itsec_user_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_kbp_form_entry: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_kbp_form_entrymeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_litespeed_cssjs: Data: 7.06MB + Index: 0.59MB + Engine MyISAM
c67imyiip_litespeed_img_optm: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_mailchimp_carts: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
c67imyiip_mailchimp_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_mclean_refs: Data: 0.18MB + Index: 0.07MB + Engine MyISAM
c67imyiip_mclean_scan: Data: 0.15MB + Index: 0.04MB + Engine MyISAM
c67imyiip_monsterinsights_pageinsights_cache: Data: 0.86MB + Index: 0.07MB + Engine MyISAM
c67imyiip_ms_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_options: Data: 10.04MB + Index: 0.59MB + Engine MyISAM
c67imyiip_pmxe_exports: Data: 0.12MB + Index: 0.00MB + Engine MyISAM
c67imyiip_pmxe_google_cats: Data: 0.26MB + Index: 0.05MB + Engine MyISAM
c67imyiip_pmxe_posts: Data: 0.83MB + Index: 0.43MB + Engine MyISAM
c67imyiip_pmxe_templates: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
c67imyiip_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
c67imyiip_pmxi_hash: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
c67imyiip_pmxi_images: Data: 0.06MB + Index: 0.02MB + Engine MyISAM
c67imyiip_pmxi_imports: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
c67imyiip_pmxi_posts: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
c67imyiip_pmxi_templates: Data: 0.30MB + Index: 0.00MB + Engine InnoDB
c67imyiip_postmeta: Data: 45.43MB + Index: 27.89MB + Engine MyISAM
c67imyiip_posts: Data: 4.93MB + Index: 2.13MB + Engine MyISAM
c67imyiip_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_rafflepress_contestants: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_rafflepress_entries: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_rafflepress_giveaways: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_rafflepress_polls: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_spu_hits_logs: Data: 1.00MB + Index: 1.45MB + Engine MyISAM
c67imyiip_termmeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
c67imyiip_terms: Data: 0.08MB + Index: 0.18MB + Engine MyISAM
c67imyiip_term_relationships: Data: 0.40MB + Index: 0.87MB + Engine MyISAM
c67imyiip_term_taxonomy: Data: 0.11MB + Index: 0.14MB + Engine MyISAM
c67imyiip_tm_taskmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_tm_tasks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_usermeta: Data: 1.51MB + Index: 0.91MB + Engine MyISAM
c67imyiip_users: Data: 0.07MB + Index: 0.07MB + Engine MyISAM
c67imyiip_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_wc_customer_lookup: Data: 0.42MB + Index: 0.35MB + Engine MyISAM
c67imyiip_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_wc_order_coupon_lookup: Data: 0.03MB + Index: 0.05MB + Engine MyISAM
c67imyiip_wc_order_product_lookup: Data: 1.93MB + Index: 1.60MB + Engine MyISAM
c67imyiip_wc_order_stats: Data: 0.61MB + Index: 0.41MB + Engine MyISAM
c67imyiip_wc_order_tax_lookup: Data: 0.37MB + Index: 0.45MB + Engine MyISAM
c67imyiip_wc_product_meta_lookup: Data: 0.32MB + Index: 0.45MB + Engine MyISAM
c67imyiip_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
c67imyiip_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_wpmelon_advbedit_temp: Data: 0.11MB + Index: 0.08MB + Engine MyISAM
c67imyiip_wppopups_hits: Data: 1.08MB + Index: 1.56MB + Engine MyISAM
c67imyiip_ylc_chat_rows: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
c67imyiip_ylc_chat_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_ylc_chat_visitors: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_ylc_offline_messages: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
c67imyiip_yoast_indexable: Data: 2.70MB + Index: 0.56MB + Engine MyISAM
c67imyiip_yoast_indexable_hierarchy: Data: 0.05MB + Index: 0.12MB + Engine MyISAM
c67imyiip_yoast_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
c67imyiip_yoast_primary_term: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
c67imyiip_yoast_seo_links: Data: 0.05MB + Index: 0.02MB + Engine MyISAM
c67imyiip_yoast_seo_meta: Data: 0.61MB + Index: 0.62MB + Engine MyISAM

### Post Type Counts ###

acf: 4
acf-field: 11
acf-field-group: 4
amn_mi-lite: 2
attachment: 2241
carts: 2643
custom_css: 3
customize_changeset: 24
gift_card: 52
google_maps: 1
it_boom_bar: 12
nav_menu_item: 540
oembed_cache: 7
page: 50
post: 76
product: 634
product_variation: 3846
revision: 120
shop_coupon: 131
shop_order: 7886
shop_order_refund: 680
sidebar: 2
spucpt: 5
tve_form_type: 1
tve_lead_group: 1
widget_content: 6
woocarousel: 1
woocarouselpro: 6
wp_block: 8
wp-bio-links: 1
wppopups: 7
ylc-macro: 2
ywdpd_discount: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.4.0-beta.1 (update to version 4.4.0-rc.1 is available)

### Inactive Plugins (69) ###

Advanced Custom Fields: by Elliot Condon – 5.8.12
BackupBuddy: by iThemes – 8.6.0.0
Billmate Payment Gateway for WooCommerce: by Billmate – 3.8.1 (update to version 3.10.17 is available) – Installed version not tested with active version of WooCommerce 4.4.0
Cart Reports for WooCommerce: by WooCommerce – 1.2.9 – Installed version not tested with active version of WooCommerce 4.4.0
Clean Image Filenames: by Upperdog – 1.2.1
Cookie Notice: by dFactory – 1.3.2
CSS Hero: by The CSS Hero Team – 4.11
Disable Site: by Jimmy K. <jimmy@nintencode.com> – 1.3.1
Display All Image Sizes: by Press Up – 1.1.6
Enable Media Replace: by ShortPixel – 3.4.1
Envato Market: by Envato – 2.0.3
Flexible Shipping: by WP Desk – 3.11.0
Gravity Forms: by Gravity Forms – 2.4.19
Gravity Forms Mailchimp Add-On: by Gravity Forms – 4.7
Gutenberg: by Gutenberg Team – 8.6.1
Gutenberg Blocks by Kadence Blocks – Page Builder Features: by Kadence WP – 1.8.10
Gutenberg Blocks by Kadence Blocks – PRO Extension: by Kadence WP – 1.4.12
Hotjar: by Hotjar – 1.0.7
Imsanity: by Exactly WWW – 2.6.0
iThemes Boom Bar: by iThemes – 1.2.14
iThemes Security Pro: by iThemes – 6.6.1
iThemes Sync: by iThemes – 2.1.6
LiteSpeed Cache: by LiteSpeed Technologies – 3.2.4
Loco Translate: by Tim Whitlock – 2.4.0
Mailchimp for WooCommerce: by Mailchimp – 2.4.3 – Installed version not tested with active version of WooCommerce 4.4.0
Max Mega Menu: by megamenu.com – 2.8
Media Cleaner Pro: by Jordy Meow – 5.6.2
MonsterInsights - eCommerce Addon: by MonsterInsights Team – 7.3.6
MonsterInsights - Forms Tracking Addon: by MonsterInsights Team – 1.5.1
MonsterInsights - Page Insights Addon: by MonsterInsights Team – 1.3.1
MonsterInsights Pro: by MonsterInsights – 7.11.0
Phoenix Media Rename: by crossi72 – 2.0.3
Product Feed PRO for WooCommerce: by AdTribes.io – 8.5.3 – Installed version not tested with active version of WooCommerce 4.4.0
RafflePress Pro: by RafflePress – 1.3.1
SVG Support: by Benbodhi – 2.3.18
Theme Customisations: by WooThemes – 1.0.0
Trustpilot-reviews: by Trustpilot – 2.5.808 – Installed version not tested with active version of WooCommerce 4.4.0
WC Hide Shipping Methods: by Rynaldo Stoltz – 1.4
Woo Attributes Coupon: by Gaurav Nagpal – 2.2.0 – Installed version not tested with active version of WooCommerce 4.4.0
WooCommerce Advanced Bulk Edit: by George Iron – 4.5 – Installed version not tested with active version of WooCommerce 4.4.0
WooCommerce Attribute Swatches by Iconic: by Iconic <support@iconicwp.com> – 1.2.7 – Installed version not tested with active version of WooCommerce 4.4.0
WooCommerce Beta Tester: by WooCommerce – 2.0.1 – Installed version not tested with active version of WooCommerce 4.4.0
WooCommerce Brands: by WooCommerce – 1.6.18 – Installed version not tested with active version of WooCommerce 4.4.0
WooCommerce Cart Notices: by SkyVerge – 1.11.4 – Installed version not tested with active version of WooCommerce 4.4.0
WooCommerce Cost of Goods: by SkyVerge – 2.9.8 – Installed version not tested with active version of WooCommerce 4.4.0
WooCommerce Gateways Country Limiter: by OnTheGoSystems – 1.4 – Installed version not tested with active version of WooCommerce 4.4.0
WooCommerce Print Invoices/Packing Lists: by SkyVerge – 3.8.6 (update to version 3.8.7 is available) – Installed version not tested with active version of WooCommerce 4.4.0
WooCommerce Product Image Flipper: by jameskoster – 0.4.2 – Installed version not tested with active version of WooCommerce 4.4.0
WooCommerce Sequential Order Numbers: by SkyVerge – 1.9.5 – Installed version not tested with active version of WooCommerce 4.4.0
Woocommerce Stock Popup: by IndiaSan – 1.0.0 – Installed version not tested with active version of WooCommerce 4.4.0
WooCommerce Stripe Gateway: by WooCommerce – 4.5.0 – Installed version not tested with active version of WooCommerce 4.4.0
Woocommerce Variation Quantity: by IndiaSan – 1.0.0 – Installed version not tested with active version of WooCommerce 4.4.0
WooThumbs for WooCommerce by Iconic: by Iconic – 4.8.1 – Installed version not tested with active version of WooCommerce 4.4.0
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.1.2

WP All Export Pro: by Soflyy – 1.5.10
WP All Import - ACF Add-On: by Soflyy – 3.2.7
WP All Import - WooCommerce Add-On Pro: by Soflyy – 3.2.3 – Installed version not tested with active version of WooCommerce 4.4.0
WP All Import - Yoast WordPress SEO Add-On: by Soflyy – 1.1.8
WP All Import Pro: by Soflyy – 4.6.2
WP Bio Links: by Guglielmo Pepe – 1.0.0
WP Extended Search: by 5um17 – 1.3.1
WP Link Preview: by Kishan Gajera – 1.4.1
WP Popups: by timersys – 2.0.3.3
YITH Live Chat Premium: by YITH – 1.4.2
YITH WooCommerce Dynamic Pricing and Discounts Premium: by YITH – 1.6.2 – Installed version not tested with active version of WooCommerce 4.4.0
YITH WooCommerce Gift Cards Premium: by YITH – 3.1.6 – Installed version not tested with active version of WooCommerce 4.4.0
Yoast SEO: Local: by Team Yoast and Arjan Snaterse – 13.4 – Installed version not tested with active version of WooCommerce 4.4.0
Yoast SEO: WooCommerce: by Team Yoast – 13.4 – Installed version not tested with active version of WooCommerce 4.4.0
Yoast SEO Premium: by Team Yoast – 14.6.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: SEK (kr)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #7005 - /shop/
Cart: #7006 - /shop/cart/
Checkout: #7007 - /shop/checkout/
My account: #7008 - /shop/account/
Terms and conditions: #495 - /kopvillkor/

### Theme ###

Name: Storefront
Version: 2.5.8
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1,261
Oldest: 2020-07-07 21:29:35 +0200
Newest: 2020-08-07 20:28:23 +0200

Failed: 307
Oldest: 2019-02-28 16:02:47 +0100
Newest: 2020-05-02 12:09:37 +0200

`</details>

**Comment by juliaamosova** [comment]
Hi @ben72,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

I made a screencast to show that it works in both WooCommerce 4.3.1 and WooCommerce 4.4. rc1:

https://recordit.co/2gpFQrK5x8

The important thing to keep in mind is that filter widgets appear only on the shop, tag, category, etc. types of pages - basically only on the pages where the products can be filtered. We have the same mentioned in our docs:

https://docs.woocommerce.com/document/woocommerce-widgets/#section-5

Can you please clarify if you are having issues with the widget not appearing on the Shop page? And if so, can you please confirm that you performed a theme and plugins conflict? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by ben72** [comment]
Thank you for testing @juliaamosova!
The only thing that could be causing this then is the data on my site. I might not be the only one with similar data though..
As you can see in the environment dump no other plugins were active and the Storefront theme was used.
I checked the shop page and the pricing filter was active. It should be them same with that only showing on shop related pages?
I've since removed the dev site I tested on but I can make another test later.

**Comment by juliaamosova** [comment]
Hi @ben72,

Thanks for the follow-up and apologies for the delayed response. 

>The only thing that could be causing this then is the data on my site. I might not be the only one with similar data though..

What kind of data do you have on your site? It is still not clear how to reproduce the issue. 

>I checked the shop page and the pricing filter was active. It should be them same with that only showing on shop related pages?

Sorry, I am not sure there is enough information here either. Can you please clarify what pages do you expect to see the filter widgets and where do they not appear?

**Comment by ben72** [comment]
Hi @juliaamosova OK I'm not sure how you tested this? But I made a vanilla install of WP 5.5 and latest WC. I added two products with global attributes size and color and a couple of filter widgets: attribute color, attribute size and price.

They were all present in the sidebar but when I updated to WC 4.4.0-rc.1 they were gone upon refresh except the price filter.
Are you not able to reproduce this? If so, I can email you the site url and login.
Please see screenshots before and after WC update from the Shop page.

I get some php warnings as well when going to the plugins page, these appear 4 times on the screen:
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'auto_update_woocommerce' not found or invalid function name in /wp-includes/class-wp-hook.php on line 287

Thanks!
![1](https://user-images.githubusercontent.com/1370224/90314474-519ff980-df14-11ea-8e66-424af999c6ac.png)
![2](https://user-images.githubusercontent.com/1370224/90314473-51076300-df14-11ea-9531-19cd471ae9dd.png)

**Comment by juliaamosova** [comment]
Hi @ben72,

Thanks for the additional feedback!

>Hi @juliaamosova OK I'm not sure how you tested this? But I made a vanilla install of WP 5.5 and latest WC. I added two products with global attributes size and color and a couple of filter widgets: attribute color, attribute size and price.

They were all present in the sidebar but when I updated to WC 4.4.0-rc.1 they were gone upon refresh except the price filter.
Are you not able to reproduce this? If so, I can email you the site url and login.
Please see screenshots before and after WC update from the Shop page.

We managed to identify the cases where the issue with `Filter by Attribute` widget happens - please see below:

https://github.com/woocommerce/woocommerce/issues/27419#issuecomment-679238547

Can you please confirm if you are not assigning the value to variations and leave them with `Any` value?

**Comment by juliaamosova** [comment]
>I get some php warnings as well when going to the plugins page, these appear 4 times on the screen:
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'auto_update_woocommerce' not found or invalid function name in /wp-includes/class-wp-hook.php on line 287

There should be coming from WooCommerce Beta Tester plugin:

https://github.com/woocommerce/woocommerce-beta-tester/issues/68

Are you using WooCommerce Beta Tester plugin to switch between WooCommerce dev versions for testing?

**Comment by ben72** [comment]
Thanks! I'm no longer able to reproduce the issue it seems.
