### ISSUE TITLE
Remove relative include paths - they may break opcache

### ISSUE THREAD

**Issue by artpi** [woocommerce/woocommerce#27269]
Relative include paths in PHP can break, when server is running `opcache`. See [here about vulnerability details](https://stackoverflow.com/a/30913177).

WordPress.com deploy system refuses to include WooCommerce, because of that issue - for more context, see here - [internal a8c discussion](p3topS-MV-p2)

The Earn team is happy to tackle this, but will we would appreciate any feedback on what issues we may run into.

# All the files with relative include paths

I used a script, that I attach at the end to generate these.

### includes/admin/class-wc-admin-post-types.php

- [x] [`include_once 'class-wc-admin-duplicate-product.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-post-types.php#L34)
- [x] [`include_once 'list-tables/class-wc-admin-list-table-orders.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-post-types.php#L95)
- [x] [`include_once 'list-tables/class-wc-admin-list-table-coupons.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-post-types.php#L99)
- [x] [`include_once 'list-tables/class-wc-admin-list-table-products.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-post-types.php#L103)

### includes/admin/class-wc-admin-status.php

- [x] [`include_once 'views/html-admin-page-status-logs.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-status.php#L127)
- [x] [`include_once 'views/html-admin-page-status-logs-db.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-status.php#L145)

### includes/admin/class-wc-admin-webhooks.php

- [x] [`include 'settings/views/html-webhooks-edit.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-webhooks.php#L211)

### includes/admin/class-wc-admin.php

- [x] [`include 'class-wc-admin-dashboard.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin.php#L107)
- [x] [`include 'class-wc-admin-permalink-settings.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin.php#L110)
- [x] [`include 'plugin-updates/class-wc-plugins-screen-updates.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin.php#L113)
- [x] [`include 'plugin-updates/class-wc-updates-screen-updates.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin.php#L116)
- [x] [`include 'class-wc-admin-profile.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin.php#L122)
- [x] [`include 'views/html-email-template-preview.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin.php#L226)

### includes/admin/list-tables/class-wc-admin-list-table-coupons.php

- [x] [`include_once 'abstract-class-wc-admin-list-table.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/list-tables/class-wc-admin-list-table-coupons.php#L18)

### includes/admin/list-tables/class-wc-admin-list-table-orders.php

- [x] [`include_once 'abstract-class-wc-admin-list-table.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/list-tables/class-wc-admin-list-table-orders.php#L18)

### includes/admin/list-tables/class-wc-admin-list-table-products.php

- [x] [`include_once 'abstract-class-wc-admin-list-table.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/list-tables/class-wc-admin-list-table-products.php#L18)

### includes/admin/meta-boxes/class-wc-meta-box-order-downloads.php

- [x] [`include 'views/html-order-download-permission.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-order-downloads.php#L59)

### includes/admin/meta-boxes/class-wc-meta-box-order-items.php

- [x] [`include 'views/html-order-items.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-order-items.php#L41)

### includes/admin/meta-boxes/class-wc-meta-box-order-notes.php

- [x] [`include 'views/html-order-notes.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-order-notes.php#L31)

### includes/admin/meta-boxes/class-wc-meta-box-product-data.php

- [x] [`include 'views/html-product-data-panel.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L33)
- [x] [`include 'views/html-product-data-general.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L42)
- [x] [`include 'views/html-product-data-inventory.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L43)
- [x] [`include 'views/html-product-data-shipping.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L44)
- [x] [`include 'views/html-product-data-linked-products.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L45)
- [x] [`include 'views/html-product-data-attributes.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L46)
- [x] [`include 'views/html-product-data-advanced.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L47)
- [x] [`include 'views/html-product-data-variations.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-product-data.php#L180)

### includes/admin/meta-boxes/views/html-order-items.php

- [x] [`include 'html-order-item.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/views/html-order-items.php#L62)
- [x] [`include 'html-order-fee.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/views/html-order-items.php#L72)
- [x] [`include 'html-order-shipping.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/views/html-order-items.php#L81)
- [x] [`include 'html-order-refund.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/views/html-order-items.php#L92)

### includes/admin/meta-boxes/views/html-product-data-attributes.php

- [x] [`include 'html-product-attribute.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/views/html-product-data-attributes.php#L45)

### includes/admin/meta-boxes/views/html-product-data-general.php

- [x] [`include 'html-product-download.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/views/html-product-data-general.php#L92)
- [x] [`require 'html-product-download.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/views/html-product-data-general.php#L108)

### includes/admin/meta-boxes/views/html-variation-admin.php

- [x] [`include 'html-product-variation-download.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/views/html-variation-admin.php#L381)
- [x] [`require 'html-product-variation-download.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/views/html-variation-admin.php#L397)

### includes/admin/plugin-updates/class-wc-plugin-updates.php

- [x] [`include 'views/html-notice-untested-extensions-inline.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/plugin-updates/class-wc-plugin-updates.php#L118)
- [x] [`include 'views/html-notice-untested-extensions-modal.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/plugin-updates/class-wc-plugin-updates.php#L133)

### includes/admin/settings/class-wc-settings-tax.php

- [x] [`include 'views/html-settings-tax.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/settings/class-wc-settings-tax.php#L240)

### includes/class-wc-ajax.php

- [x] [`include_once 'admin/list-tables/class-wc-admin-list-table-orders.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L551)
- [x] [`include 'admin/meta-boxes/views/html-product-attribute.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L584)
- [x] [`include 'admin/meta-boxes/views/html-product-attribute.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L584)
- [x] [`include 'admin/meta-boxes/views/html-variation-admin.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L719)
- [x] [`include 'admin/meta-boxes/views/html-order-download-permission.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L819)
- [x] [`include 'admin/meta-boxes/views/html-order-items.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L937)
- [x] [`include 'admin/meta-boxes/views/html-order-notes.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L942)
- [x] [`include 'admin/meta-boxes/views/html-order-items.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L937)
- [x] [`include 'admin/meta-boxes/views/html-order-shipping.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L1053)
- [x] [`include 'admin/meta-boxes/views/html-order-items.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L937)
- [x] [`include 'admin/meta-boxes/views/html-order-items.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L937)
- [x] [`include 'admin/meta-boxes/views/html-order-items.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L937)
- [x] [`include 'admin/meta-boxes/views/html-order-items.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L937)
- [x] [`include 'admin/meta-boxes/views/html-order-notes.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L942)
- [x] [`include 'admin/meta-boxes/views/html-order-items.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L937)
- [x] [`include 'admin/meta-boxes/views/html-order-items.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L937)
- [x] [`include 'admin/meta-boxes/views/html-order-items.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L937)
- [x] [`include 'admin/meta-boxes/views/html-order-notes.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L942)
- [x] [`include 'admin/meta-boxes/views/html-order-items.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L937)
- [x] [`include 'admin/meta-boxes/views/html-variation-admin.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-ajax.php#L719)

### includes/class-wc-privacy.php

- [x] [`include_once 'class-wc-privacy-erasers.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-privacy.php#L38)
- [x] [`include_once 'class-wc-privacy-exporters.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-privacy.php#L39)

### includes/class-wc-shipping-zone.php

- [x] [`require_once 'legacy/class-wc-legacy-shipping-zone.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-shipping-zone.php#L12)

### includes/class-wc-webhook.php

- [x] [`require_once 'legacy/class-wc-legacy-webhook.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-webhook.php#L18)

### includes/integrations/maxmind-geolocation/class-wc-integration-maxmind-geolocation.php

- [x] [`require_once 'class-wc-integration-maxmind-database-service.php';`](https://github.com/woocommerce/woocommerce/blob/master/includes/integrations/maxmind-geolocation/class-wc-integration-maxmind-geolocation.php#L11)

### packages/action-scheduler/action-scheduler.php

- [x] [`require_once( 'classes/ActionScheduler_Versions.php' );`](https://github.com/woocommerce/woocommerce/blob/master/packages/action-scheduler/action-scheduler.php#L31)
- [x] [`require_once( 'classes/abstracts/ActionScheduler.php' );`](https://github.com/woocommerce/woocommerce/blob/master/packages/action-scheduler/action-scheduler.php#L43)

### packages/action-scheduler/classes/abstracts/ActionScheduler.php

- [x] [`include( "{$dir}{$class}.php" );`](https://github.com/woocommerce/woocommerce/blob/master/packages/action-scheduler/classes/abstracts/ActionScheduler.php#L122)

# Script that generates these files

```
<?php

function getDirContents( $dir ){
    $dir = realpath( $dir );
    $results = array();
    $files = scandir( $dir );


    foreach( $files as $value ){
        $path = $dir. DIRECTORY_SEPARATOR .$value;
        if ( $value === '.' || $value === '..' ) {    
        } else if ( is_dir( $path ) ) {
            $results[] = $value;
            getDirContents( $path );
        } else if( substr( $value, -4, 4 ) === '.php' ){
			$data = file_get_contents( $path );
			$matches = [];
			$offenders = preg_match_all( '/^\s*(?:include|require)(?:_once)?\s*\(?\s*(?:\'|")(.+)(?:\'|")\s*\)?\s*;/m', $data, $matches, PREG_SET_ORDER ); //'/^\s+(include|require)(_once)?\s(?:\'|")(.+)(?:\'|")*;/m'
			if( $offenders ) {
                $fil = str_replace('/Users/artpi/Downloads/woocommerce/', '', $path );
				echo "\n### " . $fil . "\n\n";
				foreach( $matches as $match ) {
                    $match = trim($match[0]);
                    $line = file_line_number( $data, $match );
					echo "- [ ] [`{$match}`](https://github.com/woocommerce/woocommerce/blob/master/{$fil}#L{$line})\n";
				}
			}
        }
    }
}

getDirContents('./' );

function file_line_number( $file, $str ) {
    $lines = explode( "\n", $file );
    $line = 1;
    foreach ($lines as $lin ) {
        if ( stristr( $lin, trim( $str ) ) ) {
            return $line;
        }
        $line++;
    }
    return 0;
}
```

**Comment by rrennick** [comment]
> The Earn team is happy to tackle this, but will we would appreciate any feedback on what issues we may run into.

@artpi It should be fine to update the relative paths to absolute.

**Comment by peterfabian** [comment]
I've added as an item for discussion to tomorrow's meeting. I also think it should be fine to update, but if there's anyone who knows about a potential problem, I'll add a comment here.

**Comment by peterfabian** [comment]
Sorry for the late response. 

> The Earn team is happy to tackle this, but will we would appreciate any feedback on what issues we may run into.

We are not aware of any issues with replacing the relative paths, so from our perspective, please go ahead and let us know if you need any help with problems you (potentially might) run into.
