### ISSUE TITLE
[Request] Pinterest buyable pins integration

### ISSUE THREAD

**Issue by taewookim** [woocommerce/woocommerce#27267]
Side question: Did these paid SaaS ecommerce platforms "lobby" WC to be excluded? Wondering why they wouldn't support a platform that powers 25% of ecommerce sites

**Comment by peterfabian** [comment]
Hi @taewookim , 

Thanks for the request, it's a great point you have. Last year we started our partnership with Pinterest and hopefully, it would lead to adding more features, including Buyable Pins, to the [official extension](https://woocommerce.com/products/pinterest-for-woocommerce/). Please follow the news about the extensions to find out when the support will be added.

**Comment by taewookim** [comment]
Thanks for the update. 

Does this plugin currently support buyable pins? If not, when is the ETA?

**Comment by peterfabian** [comment]
I don't think it does and I'm not aware of any ETA, sorry.
