### ISSUE TITLE
Decimals in the quantity field

### ISSUE THREAD

**Issue by jonykg** [woocommerce/woocommerce#27274]
Hello!

I am setting up the website for a grocery store and when installing the POS, I find the limitation that we cannot enter decimals in the quantity field when adding a product to cart. And we need that feature because we sell many fruits and veggies by weight, so we cannot force our clients to buy 1, 2, 3, 4... kg of that products...

Thanks for taking into account this request.

Best regards

**Comment by peterfabian** [comment]
Hi @jonykg ,

Thanks for your inquiry! We currently don't plan to add this feature to WooCommerce core, but there are several plugins that should enable this for you, if you want to give them a try, e.g.:
- https://wordpress.org/plugins/product-quantity-for-woocommerce/
- https://wordpress.org/plugins/wpc-product-quantity/

Hope it helps.
