### ISSUE TITLE
Add pages to WC store upon activation.

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#27286]
**Is your feature request related to a problem? Please describe.**
Currently, the pages are added during onboarding and people who skip onboarding have a broken store.

**Describe the solution you'd like**
Having a working store and a robust solution for starting up with WC without onboarding.

**Describe alternatives you've considered**
Currently, this is being done in WC Admin during onboarding and it probably belongs to core.

**Additional context**
https://github.com/woocommerce/woocommerce-admin/issues/4575

**Comment by peterfabian** [comment]
This might need some synchronization with folks from Isotope (and could be done together with deprecating the old onboarding code?)

**Comment by rrennick** [comment]
Old setup is removed in https://github.com/woocommerce/woocommerce/pull/26853
