### ISSUE TITLE
Add flag for new customer to response to customer info endpoint

### ISSUE THREAD

**Issue by kloon** [woocommerce/woocommerce#27284]
On woo-mobile, we have a need to show a visual indicator when a customer is a new customer. It'd be really helpful if we could have either:

a. A boolean flag called new_customer included in the response, or
b. a orders_count element added to the response (if the user has multiple orders, then not new)

Please let me know if I can provide any additional information.

Originally logged at https://github.com/woocommerce/woocommerce/issues/24187 by @AmandaRiu

**Comment by rrennick** [comment]
Closing as `orders_count` was added to the response at some point:

```
GET wp-json/wc-analytics/customers?_fields=id,orders_count

[
  {
    "id": 1091,
    "orders_count": 0
  },
  {
    "id": 1092,
    "orders_count": 0
  },
  {
    "id": 1089,
    "orders_count": 1
  },
....
```
