### ISSUE TITLE
E2E: Update CustomerFlow and StoreOwnerFlow to ShopperFlow and MerchantFlow

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#27287]
Update `CustomerFlow` and `StoreOwnerFlow` to `ShopperFlow` and `MerchantFlow` in `@woocommerce/e2e-utils` package and throughout the tests where needed in order to use the new language adopted throughout WooCommerce. We should update the `default.json` entries to `merchant` and `shopper` as well.

**Comment by rrennick** [comment]
The `customer` should probably be left as a customer. In normal use case, a used account is created at the same time a shopper becomes a customer. But, we could break out the flows that don't require an account into `Shopper`.
