### ISSUE TITLE
WooCommerce Dropshipping Broken After 4.3.2 Core Update

### ISSUE THREAD

**Issue by Boondoggy** [woocommerce/woocommerce#27304]
## Prerequisites (mark completed items with an [x]):

[x] I have have carried out troubleshooting steps and I believe I have found a bug.
[x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

## Describe the bug
WooCommerce Dropshipping plugin breaks my admin site following an update for WooCommerce core 4.3.2. For example, drop down menu buttons do not work throughout the admin site, including post/page/product editors.

###Expected behavior
Click on 'Screen Options' -- expect drop down menu to slide down. I expected the plugin update to not cause a conflict. Rolling back the plugin to 4.3.1 does not resolve the issue.

###Actual behavior
Drop down menus no longer work, nothing happens expansion buttons are clicked.

##Steps to reproduce the bug
1. Install WooCommerce Core Plugin. 
2. Verify drop down menu buttons work.
3. Install WooCommerce Dropshipping Plugin.
4. Verify drop down menu buttons work.
5. Inspect element, check if error matches:

```
Uncaught TypeError: $(...).live is not a function
    at HTMLDocument.<anonymous> (wc_dropship_manager.js?ver=5.5:27)
    at i (jquery.js?ver=1.12.4-wp:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4-wp:2)
    at Function.ready (jquery.js?ver=1.12.4-wp:2)
    at HTMLDocument.J (jquery.js?ver=1.12.4-wp:2)

```
Note: I'm a WooCommerce Dropshipping subscriber. Not sure if this will affect testing. 

Isolating the problem (mark completed items with an [x]):
[x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce Dropshipping plugin is active.
[  ] This bug happens with a default WordPress theme active, or Storefront.
[x] I can reproduce this bug consistently using the steps above.

##WordPress Environment
### WordPress Environment ###
WordPress address (URL): https://mrfinnigus.com
Site address (URL): https://mrfinnigus.com
WooCommerce version: 4.3.2

REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.1
Log Directory Writable: ✔
WP Version: 5.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔ 

###Server Environment
Server Info: nginx
PHP Version: 7.3.20
PHP Post Max Size: 2GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.71.1 OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.21-MariaDB-log
Max Upload Size: 2GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

###Database
WC Database Version: 4.3.2
Database prefix wp_
Total Database Size 23.69MB
Database Data Size 20.98MB
Database Index Size 2.71MB
wp_woocommerce_sessions Data: 1.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_items Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_failed_jobs Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options Data: 2.14MB + Index: 0.06MB + Engine InnoDB
wp_postmeta Data: 7.05MB + Index: 0.81MB + Engine InnoDB
wp_posts Data: 9.31MB + Index: 0.22MB + Engine InnoDB
wp_queue Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_indexable Data: 0.28MB + Index: 0.25MB + Engine InnoDB
wp_yoast_indexable_hierarchy Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta Data: 0.06MB + Index: 0.00MB + Engine InnoDB

###Post Type Counts
attachment 324
customize_changeset 28
custom_css 3
elementor_library 1
elementskit_template 1
feedback 6
jetpack_migration 2
jp_img_sitemap 4
jp_sitemap 4
jp_sitemap_master 4
nav_menu_item 15
page 18
post 12
product 16
product_variation 54
revision 292
shop_order 126

###Security
Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

###Active Plugins (22)
Akismet Anti-Spam by Automattic – 4.1.6
AMP by AMP Project Contributors – 1.5.5
CoBlocks by GoDaddy – 2.2.0
Elementor by Elementor.com – 2.9.14
Essential Addons for Elementor by WPDeveloper – 4.2.0 – Installed version not tested with active version of WooCommerce 4.3.2
WordPress.com Editing Toolkit by Automattic – 1.17
Gutenberg by Gutenberg Team – 8.7.1
Jetpack by WordPress.com by Automattic – 8.8.1
Kirki Customizer Framework by David Vongries – 3.1.5
Page Optimize by Automattic – 0.5.0
Page scroll to id by malihu – 1.6.8
Page Builder by SiteOrigin by SiteOrigin – 2.11.1
SiteOrigin Widgets Bundle by SiteOrigin – 1.17.4
WooCommerce Blocks by Automattic – 3.1.0 – Installed version not tested with active version of WooCommerce 4.3.2
WooCommerce Dropshipping by WooCommerce – 2.4 – Installed version not tested with active version of WooCommerce 4.3.2
WooCommerce PayPal Checkout Gateway by WooCommerce – 2.0.3 – Installed version not tested with active version of WooCommerce 4.3.2
WooCommerce Stripe Gateway by WooCommerce – 4.5.0 – Installed version not tested with active version of WooCommerce 4.3.2
WooCommerce Services by Automattic – 1.24.0 – Installed version not tested with active version of WooCommerce 4.3.2
WooCommerce by Automattic – 4.3.2
WordPress Importer by wordpressdotorg – 0.7
Yoast SEO by Team Yoast – 14.7
WP Rollback by Impress.org – 1.7.1

###Inactive Plugins (5)
Classic Editor by WordPress Contributors – 1.6
ElementsKit Lite by Wpmet – 1.5.10
Layout Grid by Automattic – 1.2.4
Mailchimp for WooCommerce by Mailchimp – 2.4.3 – Installed version not tested with active version of WooCommerce 4.3.2
Templately by Templately – 1.1.2

###Settings
API Enabled: -
Force SSL: ✔
Currency: GBP (USD)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external), grouped (grouped), simple (simple), variable (variable)
Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog), exclude-from-search (exclude-from-search), featured (featured), outofstock (outofstock), rated-1 (rated-1), rated-2 (rated-2), rated-3 (rated-3), rated-4 (rated-4), rated-5 (rated-5)
Connected to WooCommerce.com: ✔

### WC Pages
Shop base: #1835 - /shop-2/
Cart: #1836 - /cart-2/
Checkout: #1837 - /checkout-2/
My account: #1838 - /my-account-2/
Terms and conditions: ❌ Page not set

###Theme
Name: AThemes
Version: 1.0.13
Author URL: https://athemes.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

###Templates
Overrides: leto/woocommerce/checkout/form-coupon.php, leto/woocommerce/checkout/form-login.php

###Action Scheduler
Complete: 184
Oldest: 2020-07-12 14:14:37 +0000
Newest: 2020-08-12 03:28:28 +0000

Pending: 2
Oldest: 2020-08-13 02:44:16 +0000
Newest: 2020-08-18 06:38:37 +0000

**Comment by dougaitken** [comment]
Hi @Boondoggy 

Please close this issue and open a support ticket directly from your WooCommerce.com account. This GitHub repository is only for the core WooCommerce plugin and this error doesn't happen with the core plugin. It was fixed in WooCommerce 4.3.2 via #27170
