### ISSUE TITLE
Latest WooCommerce update conflicts with WP themes and changes/removes site formatting

### ISSUE THREAD

**Issue by GMB321** [woocommerce/woocommerce#27302]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

The bug causes a conflict with certain formatting elements from the installed WP themes.

**Expected behavior**

I expected the plugin update to not cause a conflict.

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

The latest Woocommerce update caused a conflict with the WP Theme and lost formatting elements on the site. The site is now unformatted with images and blocks missing etc. Once the plugin is deactivated the site works perfectly.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to  'Update WooCommerce plugin to 4.3.2'
2. Click on 'Visit site'
3. Scroll down to 'Home page'
4. See error 'visual changes to formatting on site is incorrect for the theme'

**Screenshots**
![Woo error ss1 plugin ativated](https://user-images.githubusercontent.com/69547527/89957446-583a2280-dc2f-11ea-9caa-b9786c7a586f.jpg)
![Woo error ss2 plugin deactivated](https://user-images.githubusercontent.com/69547527/89957449-58d2b900-dc2f-11ea-9481-226b2778bdc6.jpg)

**Isolating the problem (mark completed items with an [x]):**
- [X ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>
`
### WordPress Environment ###

WordPress address (URL): https://medicarehealthmasks.co.uk
Site address (URL): https://medicarehealthmasks.co.uk
WC Version: 4.3.2
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.1
Log Directory Writable: ✔
WP Version: 5.5
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.20
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1g-fips

SUHOSIN Installed: –
MySQL Version: 5.7.25-28-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.2
WC Database Prefix: ptk_
Total Database Size: 6.49MB
Database Data Size: 4.78MB
Database Index Size: 1.71MB
ptk_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ptk_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ptk_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ptk_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ptk_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ptk_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ptk_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ptk_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ptk_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ptk_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ptk_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ptk_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ptk_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ptk_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ptk_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
ptk_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ptk_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ptk_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ptk_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ptk_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
ptk_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ptk_options: Data: 2.09MB + Index: 0.06MB + Engine InnoDB
ptk_postmeta: Data: 1.41MB + Index: 0.13MB + Engine InnoDB
ptk_posts: Data: 0.30MB + Index: 0.06MB + Engine InnoDB
ptk_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ptk_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ptk_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ptk_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ptk_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ptk_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ptk_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ptk_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ptk_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ptk_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ptk_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ptk_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ptk_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
ptk_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ptk_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ptk_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
ptk_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ptk_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ptk_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ptk_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
ptk_yoast_indexable: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
ptk_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
ptk_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ptk_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
ptk_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
ptk_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 33
custom_css: 1
customize_changeset: 55
elementor_library: 2
nav_menu_item: 12
page: 13
post: 1
product: 5
revision: 46
wpforms: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (12) ###

Coming Soon Page, Under Construction & Maintenance Mode by SeedProd: by SeedProd – 5.1.3
Elementor: by Elementor.com – 2.9.14
Jetpack by WordPress.com: by Automattic – 8.8.1
Ocean Extra: by OceanWP – 1.6.5
SG Optimizer: by SiteGround – 5.6.2
WooCommerce Stripe Gateway: by WooCommerce – 4.5.0 – Installed version not tested with active version of WooCommerce 4.3.2
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.22 – Installed version not tested with active version of WooCommerce 4.3.2
WooCommerce: by Automattic – 4.3.2
WordPress Importer: by wordpressdotorg – 0.7
Yoast SEO: by Team Yoast – 14.7
WordPress Starter: by SiteGround – 1.1.1
WPForms Lite: by WPForms – 1.6.2.2

### Inactive Plugins (2) ###

Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.12.2
The Events Calendar: by Modern Tribe
Inc. – 5.1.5

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /
Cart: #258 - /cart/
Checkout: #30 - /checkout/
My account: ❌ Page not set
Terms and conditions: #250 - /terms-and-conditions/

### Theme ###

Name: OceanWP
Version: 1.8.6
Author URL: https://oceanwp.org/about-me/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: oceanwp/woocommerce/cart/mini-cart.php
oceanwp/woocommerce/content-single-product.php
oceanwp/woocommerce/loop/loop-start.php
oceanwp/woocommerce/single-product/title.php

### Action Scheduler ###

Complete: 12
Oldest: 2020-08-10 14:11:50 +0000
Newest: 2020-08-11 22:32:02 +0000

Pending: 1
Oldest: 2020-08-12 00:32:49 +0000
Newest: 2020-08-12 00:32:49 +0000

`

**Comment by juliaamosova** [comment]
Hi @GMB321,

Thanks for raising the issue. However, the theme issues need to be fixed on the theme side of things. Please report the behavior you are seeing to the developers of the OceanWP theme and ask them to take a look further. 

I am closing this thread as this doesn't seem to be WooCommerce issue but please feel free to comment in case you think we missed something.
