### ISSUE TITLE
HTML in Woocommerce Product Title for a line break

### ISSUE THREAD

**Issue by accari** [woocommerce/woocommerce#27305]
**Prerequisites (mark completed items with an [x]):**
- [x ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
After the latest update my Woocommerce **product title** doesn't work anymore as it should. The technical support from the theme support of my home page told that "It looks like Woocommerce has started to escape HTML in product titles. Hope they will revert it back in the next release.".

To make my long product names look nicer in the front-end, I have used a snippet that is making a back-end "|" symbol show as a line break in the front-end. Since the last WC update, this is only functiong at the archive page, but the product page is showing the text "<br/>" instead of a line break in the middle of the title. Here is the snippet I'm using:

---

add_filter( 'the_title', 'custom_the_title', 100, 2 );

function custom_the_title( $title, $post_id ){
$post_type = get_post_field( 'post_type', $post_id, true );
if( $post_type == 'product' || $post_type == 'product_variation' ){
$title = str_replace( ' | ', '<br/>', $title );
}
return $title;
}

add_filter( 'woocommerce_cart_item_name', 'iconic_cart_item_title', 100, 3 );

function iconic_cart_item_title( $title, $cart_item, $cart_item_key ) {
return custom_the_title( $title, $cart_item['product_id'] );
}

---
Of course, if there is another succesful way of creating line breaks in the product title, I would be happy to know!

**Comment by maddogprod** [comment]
I'm having the same issue (though I approach it differently). I use simple HTML code in the products titles for colors and line breaks. It's always worked fine. With the new update the HTML parses on the Category Pages (using shortcodes) but doesn't parse on the Product Page and displays the HTML. 

I had to roll back to the last version of WooCommerce. Parsing the HTML is important. Weirder is that it's inconsisent between shortcode/category pages and the Product Page.

The Product Titles I use are similar to this:

`<span class="color">Step 1:</span>Cleansing Milk`

**Comment by melindahelt** [comment]
Same issue.

Steps to replicate:

Use HTML in product title
![](https://d.pr/i/r99oaL+)Image Link: https://d.pr/i/r99oaL

It displays correctly in cart and checkout while using WooCommerce 4.3.3. and Storefront
![](https://d.pr/i/9RuctR+)Image Link: https://d.pr/i/9RuctR

Update to WooCommerce 4.4 and now breaks display

![](https://d.pr/i/ltIvtV+)Image Link: https://d.pr/i/ltIvtV

#3236914-zen

**Comment by chussman** [comment]
Hi there, i have same issue since Woocommerce 4.4

Any solution??

**Comment by maddogprod** [comment]
> Hi there, i have same issue since Woocommerce 4.4
> 
> Any solution??

I used WooCommerce's plugin (https://wordpress.org/plugins/woocommerce-beta-tester/ ) to roll back to the last good version until they get it fixed.

**Comment by arunsathiya** [comment]
3238451-zen (1854869-hc)

**Comment by peterfabian** [comment]
4.3.3 reportedly works fine. Screenshot: https://d.pr/i/MOp3Wc/E9RGA4K3AK

**Comment by zhollenbeak** [comment]
Issue Reported in WC 4.4.1 on 23479222-hc

**Comment by tijosh** [comment]
A report in 3243128-zen (23473412-hc)

**Comment by tijosh** [comment]
Another report 3243715-zen (27305-hc)

**Comment by ktyfuller604** [comment]
another report - 23587418-hc

**Comment by SolutionsDEV** [comment]
I thought to add my comment over here as my case is a similar one.

Since a few versions of woocommerce, the <br> tag is not rendered in the titles of products in the cart only, while it is rendered and working fine every where else.

I just have updated woocmmerce to the latest version which is now 7.8.0, this did not solve the issue.

I hope you could find a quick solution to this.

If there is a php snippet that solved this, if you provide it, I can use it.

Thanks,

**Comment by Konamiman** [comment]
Hi @SolutionsDEV, could you please open a new issue providing detailed reproduction steps? Thank you!
