### ISSUE TITLE
Ordered products not registered with order since WP 5.5

### ISSUE THREAD

**Issue by justinkruit** [woocommerce/woocommerce#27319]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
The products that are ordered aren't being sent to the database, and the order (according to the database column `num_items_sold`) thinks 0 items have been sold. This problem accorded when WordPress was updated to 5.5.

**Expected behavior**
Items that have been bought should be sent to the database.

**Actual behavior**
No items are being sent with the order information, and the order thinks no items have been ordered.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Update to WordPress 5.5
2. Use the latest WooCommerce (4.3.2)
3. Place an order with any items in the cart. The type of product has no difference.
4. See order details and the sent mail to the customer, both missing the ordered items.

**Screenshots**
![chrome_FxojjZl7Pr](https://user-images.githubusercontent.com/1642830/90117014-9d0ca900-dd56-11ea-9615-d664710ea186.png)
![chrome_NpKG1N8ICT](https://user-images.githubusercontent.com/1642830/90117026-a0a03000-dd56-11ea-8308-a464057384e5.png)
![chrome_Oo0N3nT1Et](https://user-images.githubusercontent.com/1642830/90117027-a138c680-dd56-11ea-8535-3d19d6265f32.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): https://tevreden-baby.indivontwikkelt.nl
Site address (URL): https://tevreden-baby.indivontwikkelt.nl
WC Version: 4.3.2
REST API Version: ✔ 1.0.10
WC Blocks Version: ✔ 2.7.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.3.1
Log Directory Writable: ✔
WP Version: 5.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache/2
PHP Version: 7.2.28
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.0.2k-fips

SUHOSIN Installed: –
MySQL Version: 5.7.27
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.3.2
WC Database Prefix: wp_
Totale databasegrootte: 69.20MB
Database datagrootte: 36.71MB
Database index grootte: 32.49MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_berocket_termmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 0.44MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 11.52MB + Index: 5.03MB + Engine InnoDB
wp_posts: Data: 5.52MB + Index: 2.13MB + Engine InnoDB
wp_termmeta: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.30MB + Index: 0.25MB + Engine InnoDB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.23MB + Index: 0.45MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wsal_metadata: Data: 12.52MB + Index: 20.13MB + Engine InnoDB
wp_wsal_occurrences: Data: 1.52MB + Index: 1.81MB + Engine InnoDB
wp_yoast_indexable: Data: 3.52MB + Index: 1.31MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.11MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 74
acf-field-group: 11
attachment: 3610
br_filters_group: 2
br_product_filter: 6
customize_changeset: 11
nav_menu_item: 9
oembed_cache: 2
page: 17
post: 4
product: 1902
product_variation: 8
revision: 162
shop_order: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

ACF Content Analysis voor Yoast SEO: door Thomas Kräftner
ViktorFroberg
marol87
pekz0r
angrycreative
Team Yoast – 2.6

Advanced Custom Fields PRO: door Elliot Condon – 5.8.14
Contact Form 7: door Takayuki Miyoshi – 5.2.1
Woocommerce one page checkout and layouts: door BluePlugins – 2.4
Facebook for WooCommerce: door Facebook – 1.11.4 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.3.2
Limit Login Attempts Reloaded: door WPChef – 2.15.1
Mollie-betalingen voor WooCommerce: door Mollie – 5.8.1 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.3.2
SendCloud | Smart Shipping Service: door SendCloud B.V. – 1.1.2
WooCommerce AJAX Products Filter: door BeRocket – 3.0.0.9
WooCommerce: door Automattic – 4.3.2
Yoast SEO: door Team Yoast – 14.7
Bootstrap Blocks: door Liip AG – 2.4.1
WP PHP Console: door Fulvio Notarstefano – 1.5.4
WP Activity Log: door WP White Security – 4.1.3.1

### Inactive Plugins (5) ###

Akismet Anti-Spam: door Automattic – 4.1.6
Flamingo: door Takayuki Miyoshi – 2.2
Hello Dolly: door Matt Mullenweg – 1.7.2
LiteSpeed Cache: door LiteSpeed Technologies – 3.3.1
WPS Hide Login: door WPServeur
NicolasKulka
tabrisrp – 1.5.6

### Must Use Plugins (1) ###

installatron_hide_status_test.php: door  –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Winkelbasis: #70 - /winkel/
Winkelmand: #71 - /winkelmand/
Afrekenen: #72 - /afrekenen/
Mijn account: #73 - /mijn-account/
Algemene voorwaarden: ❌ Pagina niet ingesteld

### Theme ###

Name: InDiv Solutions
Version: 2.0
Author URL: https://www.indivsolutions.nl/
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een child thema aan. Zie: Hoe maak je een child thema

WooCommerce Support: ✔

### Templates ###

Overrides: tevredenbaby/woocommerce/archive-product.php
tevredenbaby/woocommerce/cart/cart-empty.php
tevredenbaby/woocommerce/cart/cart.php
tevredenbaby/woocommerce/cart/mini-cart.php
tevredenbaby/woocommerce/cart/proceed-to-checkout-button.php
tevredenbaby/woocommerce/checkout/form-checkout.php
tevredenbaby/woocommerce/checkout/form-coupon.php
tevredenbaby/woocommerce/checkout/form-pay.php
tevredenbaby/woocommerce/checkout/payment.php
tevredenbaby/woocommerce/content-product.php
tevredenbaby/woocommerce/content-single-product.php
tevredenbaby/woocommerce/global/form-login.php
tevredenbaby/woocommerce/global/quantity-input.php
tevredenbaby/woocommerce/loop/add-to-cart.php
tevredenbaby/woocommerce/loop/loop-end.php
tevredenbaby/woocommerce/loop/loop-start.php
tevredenbaby/woocommerce/loop/orderby.php
tevredenbaby/woocommerce/loop/sale-flash.php
tevredenbaby/woocommerce/myaccount/downloads.php
tevredenbaby/woocommerce/myaccount/form-edit-account.php
tevredenbaby/woocommerce/myaccount/form-edit-address.php
tevredenbaby/woocommerce/myaccount/form-login.php
tevredenbaby/woocommerce/myaccount/form-lost-password.php
tevredenbaby/woocommerce/myaccount/form-reset-password.php
tevredenbaby/woocommerce/myaccount/my-address.php
tevredenbaby/woocommerce/myaccount/my-orders.php
tevredenbaby/woocommerce/myaccount/navigation.php
tevredenbaby/woocommerce/myaccount/orders.php
tevredenbaby/woocommerce/product-searchform.php
tevredenbaby/woocommerce/single-product/add-to-cart/simple.php
tevredenbaby/woocommerce/single-product/add-to-cart/variation-add-to-cart-button.php
tevredenbaby/woocommerce/single-product/meta.php
tevredenbaby/woocommerce/single-product/related.php
tevredenbaby/woocommerce/single-product/sale-flash.php
tevredenbaby/woocommerce/single-product/tabs/additional-information.php
tevredenbaby/woocommerce/single-product/tabs/description.php
tevredenbaby/woocommerce/single-product/tabs/tabs.php
tevredenbaby/woocommerce/single-product/up-sells.php
tevredenbaby/woocommerce/single-product.php

### Action Scheduler ###

Afgerond: 4
Oldest: 2020-07-23 02:30:37 +0000
Newest: 2020-08-13 09:18:14 +0000

`
</details>

**Comment by tammullen** [comment]
Hi @justinkruit 

Thank you for submitting the issue. However, I can’t reproduce the issue you reported using the steps you provided. Everything is working as expected on my end. 

![Screenshot 2020-08-13 at 11 56 54](https://user-images.githubusercontent.com/24649833/90126992-63d73780-dd5c-11ea-8cd2-cf40873eb97e.png)
![Screenshot 2020-08-13 at 11 58 17](https://user-images.githubusercontent.com/24649833/90127000-66d22800-dd5c-11ea-9984-95279d18f00d.png)
![Screenshot 2020-08-13 at 11 57 08](https://user-images.githubusercontent.com/24649833/90127006-689beb80-dd5c-11ea-9419-e58938d6ba9b.png)
![Screenshot 2020-08-13 at 11 57 59](https://user-images.githubusercontent.com/24649833/90127009-69cd1880-dd5c-11ea-8e4f-661a0e5e8a64.png)

​
I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
​
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

WP 5.5 removed jQuery-migrate, so you might need to use https://wordpress.org/plugins/enable-jquery-migrate-helper/ plugin until your plugins all fix their Javascript files

**Comment by justinkruit** [comment]
So I did those steps, and apparently the order was suddenly correct. Tested per plugin, and found out the bug is coming from WP Activity Log. [A bug report has already](https://wordpress.org/support/topic/update-4-1-31-broken-woocommerce-urgent/) been made and devs are looking into it. Sorry for confusing the Woocommerce plugin as the bug.
