### ISSUE TITLE
REST API Error When Creating Product: Invalid parameter(s): date_on_sale_from, date_on_sale_to

### ISSUE THREAD

**Issue by databuzz** [woocommerce/woocommerce#27315]
I'm attempting to create a new Product via the REST API v3 by doing a POST to the Products endpoint:

wp-json/wc/v3/products

with this payload:

`{
	"attributes" : [],
	"backorders" : "yes",
	"button_text" : "",
	"catalog_visibility" : "visible",
	"categories" : [],
	"cross_sell_ids" : [],
	"date_on_sale_from" : "",
	"date_on_sale_to" : "",
	"default_attributes" : [],
	"description" : "",
	"dimensions" : 
	{
		"height" : "",
		"length" : "",
		"width" : ""
	},
	"download_expiry" : 0,
	"download_limit" : 0,
	"downloadable" : false,
	"downloads" : [],
	"external_url" : "",
	"featured" : false,
	"grouped_products" : [],
	"images" : [],
	"in_stock" : false,
	"manage_stock" : false,
	"menu_order" : 0,
	"meta_data" : [],
	"name" : "Upload Tester 2",
	"parent_id" : 0,
	"purchase_note" : "",
	"regular_price" : "21.99",
	"reviews_allowed" : false,
	"sale_price" : "",
	"shipping_class" : "",
	"short_description" : "testing uploads 2",
	"sku" : "TST2",
	"slug" : "tester2",
	"sold_individually" : false,
	"status" : "draft",
	"stock_quantity" : 0,
	"tags" : [],
	"tax_class" : "standard",
	"tax_status" : "taxable",
	"type" : "simple",
	"upsell_ids" : [],
	"virtual" : false,
	"weight" : ""
}`

Since upgrading to Version 4.3.2 I'm suddenly getting a 400 request error with this response:

`Invalid parameter(s): date_on_sale_from, date_on_sale_to `

Previously this would upload successfully without error. Appears to be an issue since upgrading WooCommerce to Version 4.3.2.

**Comment by peterfabian** [comment]
Hi @databuzz ! Thanks for opening the issue. We've switched to using WP validation for dates in WC 4.3.2, which inadvertently broke passing empty strings to date fields. We're [working on a fix](https://github.com/woocommerce/woocommerce/pull/27318) for this to allow empty strings again in 4.3.3 which will be released soon.
