### ISSUE TITLE
Compatibility with WordPress 5.5 : "Unknown"

### ISSUE THREAD

**Issue by gevcen** [woocommerce/woocommerce#27333]
Dear,

I just saw you released a new update of WooCommerce but it displays that compatibility with WordPress 5.5 is "unknown"

Is it possible to update this flag to make sure everything is ok before upgrading to 5.5 ?
Thanks

![image](https://user-images.githubusercontent.com/51261962/90238131-b892b500-de25-11ea-9bf1-32c3e35d9330.png)

**Comment by peterfabian** [comment]
Thanks for the nudge, updated. 

<img width="1019" alt="Screenshot 2020-08-14 at 12 50 39" src="https://user-images.githubusercontent.com/2207451/90242158-c8fa5e00-de2c-11ea-90f8-8e5ec6baaa3d.png">
