### ISSUE TITLE
Adding "Standard" to the list of additional tax classes hides rates from Standard rates tab

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce#27339]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
If I add `Standard` to `Additional tax classes` in WooCommerce > Settings > Tax, it hides rates from the Standard rates tab.

**Expected behavior**
Maybe show a warning that it shouldn't be there? 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**

1. Go to WooCommerce > Settings > Tax and add `Standard` to `Additional tax classes`:

![https://d.pr/i/fOqCYN](https://d.pr/i/fOqCYN+) 
Full Size: https://d.pr/i/fOqCYN

2. Go to the Standard rates tab and add a tax rate there. Save the changes and refresh that page, the tax is gone:

![https://d.pr/i/WDxexq](https://d.pr/i/WDxexq+) 
Full Size: https://d.pr/i/WDxexq

3. Now let's check the database, the tax is there, but there is no `tax_rate_class` assigned which is normal for standard rates:

![https://d.pr/i/4bpR9z](https://d.pr/i/4bpR9z+) 
Full Size: https://d.pr/i/4bpR9z

4. Now let's check the Standard rates tab with Query Monitor:

![https://d.pr/i/vMUo8b](https://d.pr/i/vMUo8b+) 
Full Size: https://d.pr/i/vMUo8b

Since `Standard` was added as an additional tax class, the SQL request is built in the same way as for other additional classes:

```
SELECT *
FROM `wp_woocommerce_tax_rates`
WHERE `tax_rate_class` = 'standard';
```

I see that rate correctly and if Standard is not added as an additional tax class. This is how SQL request looks like on this page normally:

![https://d.pr/i/k5E5In](https://d.pr/i/k5E5In+) 
Full Size: https://d.pr/i/k5E5In

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
I tested it with WooCommerce 4.3.1 and 4.3.3.

**Comment by juliaamosova** [comment]
Hi @treibalen,

Thanks for the very detailed report and investigating what is happening behind the scenes. I can reproduce the behavior described. 

The priority of this issue to be fixed seems `low` to me compared to others reported, therefore, I am marking as such. However, please feel free to let us know that you think the priority should be bumped to `high`.
