### ISSUE TITLE
woocommerce plugin

### ISSUE THREAD

**Issue by smsalman75** [woocommerce/woocommerce#27336]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
Installation failed: Could not copy file. woocommerce/packages/woocommerce-blocks/build/checkout-frontend.asset.php

**Comment by juliaamosova** [comment]
Hi @smsalman75,

Thank you for reporting the issue. However, it looks like you also reported this issue here https://github.com/woocommerce/woocommerce/issues/27338. We are closing this issue in favor of another one you submitted. Please continue sharing your feedback there if needed.
