### ISSUE TITLE
Bug in Quick Edit with the use of jQuery UI 1.12.1

### ISSUE THREAD

**Issue by stefanos82** [woocommerce/woocommerce#27340]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
> A clear and concise description of what the bug is. 

Since the announcement of [updating jQuery](https://make.wordpress.org/core/2020/06/29/updating-jquery-version-shipped-with-wordpress/), I have decided to test my local system.

With `jQuery UI 1.12.1` Quick Edit breaks, but not with `1.11.4`.

**Expected behavior**
> A clear and concise description of what you expected to happen.

It should behave the same as before with the use of `1.11.4`.

**Actual behavior**
> A clear and concise description of what actually happens. Please be as descriptive as possible; 

It removes the product line fortunately without permanently delete it.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error

1. Click on `Quick Edit`; it removes the product line, but fortunately does not permanently delete it.
2. Open your `dev tools > console` and repeat the whole procedure; you get the following message:
![image](https://user-images.githubusercontent.com/1777466/90257502-edb3fd00-de4f-11ea-93f6-27c6a8be2493.png)

**Screenshots**
> If applicable, add screenshots to help explain your problem.

Please see step 2 from previous section.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by juliaamosova** [comment]
Hi @stefanos82,

Thank you for submitting the issue. However, I can’t reproduce it - there aren't enough steps to replicate the error.

>Click on Quick Edit; it removes the product line, but fortunately does not permanently delete it.

Are you referring to `Quick edit` option on the product?

![quick_edit](https://user-images.githubusercontent.com/19143190/90295571-594d9880-de57-11ea-9edc-080c414abd4e.jpg)

I did test it and there were no errors either when I clicked on `Quick edit` or edited and saved the product using `Quick edit`:

![](http://g.recordit.co/gUMX6fisaz.gif)

I've tested with WooCommerce 4.3.3. 

Can you please provide a bit more details?

**Comment by juliaamosova** [comment]
Noting here as well that we have an issue created to check our code is ready for jQuery v3 in WP 5.6: https://github.com/woocommerce/woocommerce/issues/27243.

**Comment by stefanos82** [comment]
Hey @juliaamosova, thank you for testing my issue.

Yes, what I have done was to follow the suggestions of @azaozz from https://make.wordpress.org/core/2020/06/29/updating-jquery-version-shipped-with-wordpress/ and choose all three available options and the error happened when I switched from 1.11.4 to 1.12.1.

The error is shown here in dev tools console:
![image](https://user-images.githubusercontent.com/1777466/90297664-f03a4500-de97-11ea-832c-0a452d84b3ce.png)

That's all I did, really.

**Comment by stefanos82** [comment]
I will investigate my whole system and if I detect any silly thing from my side, I will come back and report the actual cause behind this behavior.

**Comment by stefanos82** [comment]
OK, I have tried the plugin on a vanilla WooCommerce and the problem triggers when both jQuery 3.5.1 and jQuery 1.12.1 are used:
![image](https://user-images.githubusercontent.com/1777466/90298074-6b502b00-de99-11ea-9d8c-946f35e33e64.png)

* I have tried the default jQuery with the latest UI version; works fine.
* I have tried the default jQuery UI with jQuery 3.5.1; works fine.
* As soon as I choose both of their newer versions, the error takes place.

In all cases, enabling the jQuery Migrate changes nothing in its behavior.

**Comment by stefanos82** [comment]
Chrome is much more descriptive about the actual issue.

Here's the error:
![image](https://user-images.githubusercontent.com/1777466/90299129-9dfc2280-de9d-11ea-9297-651fc635e8a9.png)

Here's the code formatted:
![image](https://user-images.githubusercontent.com/1777466/90299153-b9672d80-de9d-11ea-899a-1a69046e2efd.png)

**Comment by stefanos82** [comment]
By the way, with this plugin enabled, I can reproduce the following issue from Gutenberg: https://github.com/WordPress/gutenberg/issues/3356

As soon as I deactivate the plugin, everything works as expected.

**Comment by peterfabian** [comment]
I can reproduce this as well.

**Comment by ObliviousHarmony** [comment]
Hello @stefanos82,

I've found a [Trac ticket for this bug](https://core.trac.wordpress.org/ticket/51872) indicating that it is a problem with WordPress 5.6 and not WooCommerce.

**Comment by stefanos82** [comment]
I use WordPress 5.5.3 and this bug triggers only in WooCommerce quick edit; no custom taxonomy or whatsoever if it helps.

**Comment by ObliviousHarmony** [comment]
Thanks @stefanos82! 

The custom taxonomies triggering this error are those being registered by WooCommerce. While you may be experiencing this bug in WordPress 5.5.3, it's worth noting it's still a problem in WordPress Core caused by upgrading jQuery UI. This code doesn't live in WooCommerce and so it isn't something we can address.

We will wait for there to be a resolution in that Trac ticket and then see if this still happens in whatever version the fix is shipped in!

**Comment by stefanos82** [comment]
OK, thank you for letting me know.
