### ISSUE TITLE
Remove classes deprecated version 3.0 or earlier

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce#27343]
This is a parent issue for removing classes that were deprecated in WooCommerce version 3.0 or earlier. This is in milestone 5.0 as removing these will be breaking changes.

### Classes

- [ ] Legacy Api
- [ ] Legacy Shipping Methods
- [ ] Legacy Abstract Order
- [ ] Legacy Abstract Payment Token
- [ ] Legacy Abstract Product
- [ ] Legacy Coupon
- [ ] Legacy Customer

**Comment by peterfabian** [comment]
After further discussions, we've decided to stay in line with the usual approach in the WordPress ecosystem, and instead of removing those classes, we'll most likely just add a filter to optionally not load them if the user chooses to.

**Comment by peterfabian** [comment]
Closing in favor of https://github.com/woocommerce/woocommerce/issues/28139.
