### ISSUE TITLE
Remove class method deprecated version 3.0 or earlier

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce#27356]
This is a parent issue for removing class methods (in non-deprecated classes) that were deprecated in WooCommerce version 3.0 or earlier. This is in milestone 5.0 as removing these will be breaking changes.

### Class Methods

- [ ] WC_Admin_Duplicate_Product
  - get_product_to_duplicate
- [ ] WC_Emails
  - order_schema_markup
- [ ] WC_Order_Refund
  - get_refund
  - get_refund_amount
  - get_refund_reason
- [ ] WC_Query
  - rating_filter_meta_query
  - visibility_meta_query
  - stock_status_meta_query
  - layered_nav_init
  - get_products_in_view
  - layered_nav_query
- [ ] WC_Rest_Orders_V1_Controller
  - create_base_order
- [ ] WC_Rest_Products_V1_Controller
  - get_product_menu_order
  - save_product_images
  - save_product_meta
- [ ] WC_Rest_Products_V2_Controller
  - get_attribute_taxonomy_label
- [ ] Woocommerce
  - add_thumbnail_support
- [ ] WC_Tax
  - get_shop_base_rate
- [ ] WC_Admin_Attributes
- [ ] WC_Admin_Settings
- [ ] WC_Admin_Assets
- [ ] WC_Legacy_Cart
  - get_cart_url
  - get_checkout_url
  - ship_to_billing_address_only
  - coupons_enabled
  - get_discounts_before_tax
  - get_order_discount_total
  - apply_cart_discounts_after_tax
  - apply_product_discounts_after_tax
  - get_discounts_after_tax
- [ ] WC_Shortcode_My_Account
  - edit_account
- [ ] WC_Shipping
  - sort_shipping_methods

**Comment by peterfabian** [comment]
After further discussions, we've decided to stay in line with the usual approach in the WordPress ecosystem and not remove the methods. For specific methods within classes, I think we can't do much besides marking these as deprecated, so closing the issue for now.
