### ISSUE TITLE
Add ability to update product review status

### ISSUE THREAD

**Issue by justinshreve** [woocommerce/woocommerce#27362]
The update endpoints for product reviews in v2 and v1 never supported status updating. v3 currently doesn't either (though the response returns a readonly value).

We can't just pass the status into `wp_update_comment` via `prepare_item_for_database` like we can for other fields, because `wp_update_comment` fails for some reason if you try to pass a status that is already being used. 

It looks like the comments endpoint does a workaround for this: https://github.com/WP-API/WP-API/blob/57e027e59cef9706d42d6aa13b9db7928eb6765f/lib/endpoints/class-wp-rest-comments-controller.php#L549

**Comment by barryhughes** [comment]
Closing, as this now seems possible via [REST API v3](https://woocommerce.github.io/woocommerce-rest-api-docs/#product-reviews), for example:

```http
POST https://wp.local/wp-json/wc/v3/products/reviews/12345 HTTP/1.1
Content-Type: application/json
Authorization: Basic ABCDEF123456

{
  "status": "hold"
}
```

If I've misunderstood, of course let us know.
