### ISSUE TITLE
4.4.0: wc_get_loop_prop() called before it's loaded

### ISSUE THREAD

**Issue by dovy** [woocommerce/woocommerce#27394]
Hey all, I have a bunch of users of Redux reporting this error:

```
Fatal error: Uncaught Error: Call to undefined function wc_get_loop_prop() in /home/smokes9/public_html/wp-content/plugins/woocommerce/includes/class-wc-query.php:376 
    Stack trace: 
        #0 /home/smokes9/public_html/wp-content/plugins/woocommerce/includes/class-wc-query.php(363): WC_Query->adjust_total_pages() 
        #1 /home/smokes9/public_html/wp-includes/class-wp-hook.php(289): WC_Query->handle_get_posts(Array) 
        #2 /home/smokes9/public_html/wp-includes/plugin.php(249): WP_Hook->apply_filters(Array, Array) 
        #3 /home/smokes9/public_html/wp-includes/class-wp-query.php(3179): apply_filters_ref_array(‘the_posts’, Array) 
        #4 /home/smokes9/public_html/wp-includes/class-wp-query.php(3432): WP_Query->get_posts() 
        #5 /home/smokes9/public_html/wp-includes/class-wp-query.php(3541): WP_Query->query(Array) 
        #6 /home/smokes9/public_html/wp-content/themes/ekommart/inc/options/class-options.php(915): WP_Query->__construct(Array) 
        #7 /home/smokes9/public_html/wp-includes/class-wp-hook.php(287): Ekommart_Options->section_site_footer(Array) 
        #8 /home/smokes9/ in /home/smokes9/public_html/wp-content/plugins/woocommerce/includes/class-wc-query.php on line 376
```

The thing is, Redux doesn't do anything special with the WordPress data. What I think is it play here is our plugin is loading before yours, and you have a hook that tries to fire wc_get_loop_prop(), but it's not been included yet.

I'm willing to work with you and debug it. Our WordPress data query class is pretty basic, you can see it here: https://github.com/reduxframework/redux-framework-4/blob/master/redux-core/inc/classes/class-redux-wordpress-data.php

The only possibility I can see a conflict on how we search for all "pages/posts" https://github.com/reduxframework/redux-framework-4/blob/master/redux-core/inc/classes/class-redux-wordpress-data.php#L582

Maybe we're trying to call your custom post type before it's ready?

Anyways, I'd love to put a fix in tomorrow if any of you have ideas, or perhaps you could look on your end and do something similar. I could exclude the post type from that any clause I suppose.

Can you do some digging?

**Comment by dovy** [comment]
I ended up putting the following shim in. May want to check your autoloader for wherever that hook is firing from.

```
				// Shim to fix the late load of the WooCommerce autoloader.
				if ( defined( 'WC_PLUGIN_FILE' ) && ! function_exists( 'wc_get_loop_prop' ) ) {
					$woocommerce_file = dirname( WC_PLUGIN_FILE ) . '/includes/wc-template-functions.php';
					if ( file_exists( $woocommerce_file ) ) {
						require_once $woocommerce_file;						
					}
				}
```

**Comment by peterfabian** [comment]
Thanks for reporting, @dovy . We're working on a fix for this now as well and plan to release it ASAP, as we got reports about similar problems with some other themes (Newspaper, Gauge) and plugins (NotificationX).

We'll probably update our filter, testing it now.

**Comment by glamble007** [comment]
CRITICAL Uncaught Error: Call to undefined function wc_get_loop_prop() in /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-query.php:376 
Theme Flatsome.

**Comment by TinyGiantStudios** [comment]
Just tagging on:

https://wordpress.org/support/topic/php-fatal-error-login/
https://wordpress.org/support/topic/woocommerce-4-4-0-and-acf/

It seems that the [ACF](https://wordpress.org/plugins/advanced-custom-fields/) plugin is also affected here.

**Comment by peterfabian** [comment]
The PR above should fix the issue, so closing it. We're preparing a 4.4.1 release with this fix (and one more for https://github.com/woocommerce/woocommerce/issues/27384).

**Comment by dovy** [comment]
WTG WooCommerce team. Appreciate the extremely fast turnaround.
