### ISSUE TITLE
Jetpack Autoloader Issue

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#27390]
We are getting the reports of the following error which we are currently investigating:

>Fatal error: Cannot redeclare Automattic\Jetpack\Autoloader\enqueue_packages_59b2271d25a961ec5100b6f811b89e89() (previously declared in /srv/htdocs/wp-content/plugins/woocommerce/vendor/autoload_packages.php:183) in /srv/htdocs/wp-content/plugins/woocommerce/vendor/autoload_packages.php on line 205
xargs: sudo: exited with status 255; aborting

It seems to happen when using WooCommerce 4.3.3 and WooCommerce 4.4.

**Comment by juliaamosova** [comment]
Noting here that this issue will need to be addressed in Jetpack and then shipped in a new version of the autoloader.

**Comment by vedanshujain** [comment]
Closing this issue since it was fixed in a subsequent release.
