### ISSUE TITLE
Policy violation: contact with external server without consent

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce#27421]
This item has been reported in at https://github.com/woocommerce/woocommerce-admin/issues/4955, since which there have been two WooCommerce releases without any comment on the issue. So I am flagging it up here to bring it to your attention.

**Comment by rrennick** [comment]
@DavidAnderson684 Please don't create new issues that link to existing issues to "bring it to your attention". Version 4.4.0 was in RC when you created the original issue and 4.4.1 was an emergency bug fix to 4.4.0.

Closing as a duplicate.

**Comment by DavidAnderson684** [comment]
@rrennick Arguably, wordpress.org policy / end-user privacy violations should be being treated as the same priority as emergency fixes.
