### ISSUE TITLE
Deprecated: Non-static method WC_Post_Types::updated_term_messages() should not be called statically in /var/docs/server.tst/public/wp-includes/class-wp-hook.php on line 287

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#27436]
Latest woocommerce beta (Version 4.5.0-beta.1) throws this message in any post category overview in the admin backend !

Deprecated: Non-static method WC_Post_Types::updated_term_messages() should not be called statically in /var/docs/server.tst/public/wp-includes/class-wp-hook.php on line 287

![afbeelding](https://user-images.githubusercontent.com/6078370/90867659-07949900-e396-11ea-935a-ef1c848f8341.png)

Please fix.

**Comment by cesarmtz93-wit** [comment]
I have the same issue but with WC_Shipping_Method version 4.5.2

**Comment by cesarmtz93-wit** [comment]
WC_Shipping_Method version 4.5.2 

Deprecated: Non-static method WC_Shipping_Logistics::generate_shipping_guide() should not be called statically in /wp-includes/class-wp-hook.php on line 287
