### ISSUE TITLE
REST API `WC_REST_Terms_Controller` returns invalid response when used multiple times in one session

### ISSUE THREAD

**Issue by falahati** [woocommerce/woocommerce#27434]
**Prerequisites (mark completed items with an [x]):**
- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
`WC_REST_Terms_Controller` class caches the taxonomy name from the first `WP_REST_Request`. This creates a situation in which the name of a queried taxonomy leaks into the subsequent requests from the first one. This will not happen when there are multiple HTTP requests involved and only shows itself when a script calls the REST API by creating multiple `WP_REST_Request` instances and resolving them programmatically in one actual request.
Since the idea behind the existence of `WP_REST_Request` and `WP_REST_Responce` classes are to create an isolated running environment for each request, HTTP or not, this leakage of data between two `WP_REST_Request` is an unwanted bug.

**Expected behavior**
`WC_REST_Terms_Controller` should respond to each `WP_REST_Request` individually and do not cache variables in between multiple requests.

**Actual behavior**
When a `WP_REST_Request` request gets processed by the `WC_REST_Terms_Controller` class, it can then only respond to requests regarding the taxonomy of the first request. For any other taxonomy, it returns invalid responses.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Following is a simple and dirty example for this:

```PHP
$req = new WP_REST_Request('GET', '/wc/v3/products/attributes/1/terms');
$req->set_query_params(['per_page' => 100, 'offset' => 0, 'hide_empty' => false]);
$res = rest_do_request($req);
$server = rest_get_server();
$data1 = $server->response_to_data($res, false);

$req = new WP_REST_Request('GET', '/wc/v3/products/attributes/2/terms');
$req->set_query_params(['per_page' => 100, 'offset' => 0, 'hide_empty' => false]);
$res = rest_do_request($req);
$server = rest_get_server();
$data2 = $server->response_to_data($res, false);
```

`$data2` then contains a list of terms that are actually about the first taxonomy and is almost identical to the `$data1`.

You can see the actual lines responsible for this here:
https://github.com/woocommerce/woocommerce/blob/e8884c85db04446453d7046923244f705e0604a8/includes/rest-api/Controllers/Version3/class-wc-rest-terms-controller.php#L791
https://github.com/woocommerce/woocommerce/blob/e8884c85db04446453d7046923244f705e0604a8/includes/rest-api/Controllers/Version1/class-wc-rest-product-attributes-v1-controller.php#L527

Both these functions cache the taxonomy name or the attribute name of a request for performance reasons. This is fine, however, we should clear these variables after returning a response, or before processing a new request.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by Konamiman** [comment]
Hi @falahati, thanks for your report. Here's a pull request that fixes the issue, it's going to be merged as soon as it's reviewed and approved by my team: https://github.com/woocommerce/woocommerce/pull/29115
