### ISSUE TITLE
Notice after updating database WC 4.4 - Thank You button does anything

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce#27463]
We had this behavior long time. Anytime a database update is needed for WC, I get a notice. If update is successful, there is a another message notice incl. a "Thank You" button. This button does anything. Instead notice stays on screen on all WC pages even after 12 hours.

This is a longtime bug which should be fixed soon.

![Bildschirmfoto 2020-08-19 um 08 36 45](https://user-images.githubusercontent.com/3390880/90600581-227cd700-e1f7-11ea-98a9-5cd95ef44f04.png)

**Comment by juliaamosova** [comment]
Related issue: https://github.com/woocommerce/woocommerce/issues/27424.

There were a few attempts to fix the issue of the notices but it remains present:

- ://github.com/woocommerce/woocommerce/pull/26031
- https://github.com/woocommerce/woocommerce/pull/26500

Assigning this a 4.5 milestone to see if we can fix it sooner rather than later.

**Comment by mensmaximus** [comment]
I have to report the contrary. The admin message bug has been a constant companion for a few month. Different sites showed different effects which alll have been reported. With the update to 4.4 i noticed the messages finaly disapeared after a few clicks on the thank you button on all those sites. On the affected sites i also noticed the upgrade process took longer. However all sites look fine now.

**Comment by nixiack** [comment]
I have a chat that is having this issue as well: [hc-1273615](https://mc.a8c.com/support-stats/happychat/transcript.php?id=1273615)

**Comment by franticpsyx** [comment]
Confirming, this has been happening on all of our local dev sites + demo sites for a while now. Sometimes clicking “Thanks” multiple times will sort it out, but there’s no clear pattern.

**Comment by roykho** [comment]
Closing this in favor of https://github.com/woocommerce/woocommerce/issues/27424 since it has a PR attached.
