### ISSUE TITLE
Tax class doesn't save in product if class name is RTL language

### ISSUE THREAD

**Issue by senff** [woocommerce/woocommerce#27462]
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When selecting a tax class on a product editing page, the setting is not saved is the name of the tax class is written in an RTL language (e.g. Hebrew or Arabic) after saving the product. No issues if the characters are standard LTR.

**Expected behavior**
The selected tax class should still be the selected one, after the product is saved/updated.

**Actual behavior**
After saving/updating, the tax class goes back to "Standard".

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to **WooCommerce → Settings → Tax**
2. In the "**Additional Tax Classes**" field, add a class written in an RTL language, e.g. מִבְחָן ("test")
3. Save settings
4. Create a new product or editing an existing one
5. In the "General" tab, go to the "Tax class" field and select the class you created in step 2.
6. Save/Update the product.
7. When the page reloads, observe that the Tax class is back to "Standard".

**Screencast**
https://d.pr/i/pm3Gz3

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

WordPress address (URL): http://woo.local
Site address (URL): http://woo.local
WC Version: 4.4.1
REST API Version: ✔ 1.0.15
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.4.0
Log Directory Writable: ✔
WP Version: 5.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.3.5
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 5.7.28
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.4.1
WC Database Prefix: wp_
Total Database Size: 21.36MB
Database Data Size: 13.42MB
Database Index Size: 7.94MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.45MB + Index: 0.45MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.13MB + Index: 0.48MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.39MB + Index: 0.30MB + Engine InnoDB
wp_advanced_notifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_advanced_notification_triggers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_campaigns: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_hits: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_afwc_payouts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_afwc_payout_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_afwc_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_abandoned_carts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_customers: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_automatewoo_customer_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_events: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_guests: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_automatewoo_guest_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_log_meta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_queue: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_automatewoo_queue_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_automatewoo_referrals: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_automatewoo_referral_advocate_keys: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_automatewoo_referral_invites: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.48MB + Index: 0.47MB + Engine InnoDB
wp_email_log: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_followup_coupons: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_coupon_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_customers: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_followup_customer_carts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_customer_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_followup_email_excludes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_email_orders: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_followup_email_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_followup_followup_history: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_order_categories: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_followup_subscribers: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscribers_to_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_followup_subscriber_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.16MB + Index: 0.17MB + Engine InnoDB
wp_postmeta: Data: 2.52MB + Index: 2.88MB + Engine InnoDB
wp_posts: Data: 0.41MB + Index: 0.22MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wcato_notes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcpv_commissions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpv_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_cvo_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_deposits_payment_plans_schedule: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_bundled_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_bundled_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_per_product_shipping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_pickup_locations_geodata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

afreg_fields: 1
attachment: 80
aw_workflow: 5
bookable_person: 4
bookable_resource: 10
course: 1
custom_css: 2
customize_changeset: 15
def_reg_fields: 10
global_product_addon: 1
nav_menu_item: 19
page: 24
post: 6
product: 37
product_variation: 37
revision: 88
shop_bogof_rule: 1
shop_coupon: 13
shop_order: 420
shop_order_refund: 1
shop_subscription: 10
wc_booking: 17
wc_membership_plan: 5
wc_pickup_location: 1
wc_user_membership: 6
wcpf_item: 7
wcpf_project: 4

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.4.1

### Inactive Plugins (107) ###

Affiliate For WooCommerce: by StoreApps – 2.4.1
All-in-One WP Migration: by ServMask – 7.26
AutomateWoo: by WooCommerce – 5.0.1
AutomateWoo - Birthdays Add-on: by WooCommerce – 1.1.2 – Installed version not tested with active version of WooCommerce 4.4.1
AutomateWoo - Refer A Friend Add-on: by WooCommerce – 2.5.6 – Installed version not tested with active version of WooCommerce 4.4.1
AutomateWoo - Subscriptions Add-on: by WooCommerce – 1.1.0 – Installed version not tested with active version of WooCommerce 4.4.1
Bookings Helper: by WooCommerce – 1.0.3 – Installed version not tested with active version of WooCommerce 4.4.1
Cashier for WooCommerce: by StoreApps – 1.0.0 – Installed version not tested with active version of WooCommerce 4.4.1
Classic Editor: by WordPress Contributors – 1.6
Code Snippets: by Code Snippets Pro – 2.14.0
Contact Widgets: by GoDaddy – 1.7.0
Custom User Registration Fields for WooCommerce: by Addify – 1.6.2
Display PHP Version: by David Gwyer – 1.5
Display Posts: by Bill Erickson – 3.0.2
Email Log: by Sudar – 2.4.2
Filter WooCommerce Orders by Payment Method: by SkyVerge – 1.0.0 – Installed version not tested with active version of WooCommerce 4.4.1
Follow-Up Emails: by WooCommerce – 4.9.6 – Installed version not tested with active version of WooCommerce 4.4.1
Groups WooCommerce: by itthinx – 1.19.0
Health Check & Troubleshooting: by The WordPress.org community – 1.4.4
Jetpack by WordPress.com: by Automattic – 8.8.2
Loco Translate: by Tim Whitlock – 2.4.2
Meks Quick Plugin Disabler: by Meks – 1.0
Product Filters for WooCommerce: by WooCommerce – 1.2.2 – Installed version not tested with active version of WooCommerce 4.4.1
Query Monitor: by John Blackbourn – 3.6.4
Sensei LMS: by Automattic – 3.4.1
Simple Debug Info Panel: by Mark Senff – 1.0
Sticky Block: by Senff – 1.0
Storefront Powerpack: by WooCommerce – 1.5.0
Storefront Product Sharing: by WooCommerce – 1.0.6
String Locator: by Clorith – 2.4.1
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.16.27.1

User Role Editor: by Vladimir Garagulya – 4.56
Woo Align Buttons: by 320up – 3.6.5 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.38 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.19 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Additional Variation Images: by WooCommerce – 1.7.24 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Address Validation: by SkyVerge – 2.7.0 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Admin: by WooCommerce – 1.3.2 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Advanced Notifications: by WooCommerce – 1.2.27 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce After the Order: by OM4 – 1.0.6 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce All Products For Subscriptions: by SomewhereWarm – 3.1.17
WooCommerce Amazon Pay: by WooCommerce – 1.12.2 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Authorize.Net Gateway: by SkyVerge – 3.3.0
WooCommerce AvaTax: by SkyVerge – 1.10.2 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Blocks: by Automattic – 3.2
WooCommerce Bookings: by WooCommerce – 1.15.24 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Bookings Availability: by WooCommerce – 1.1.15 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Box Office: by WooCommerce – 1.1.28 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Brands: by WooCommerce – 1.6.19 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Buy One Get One Free: by Oscar Gare – 2.0.12 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Canada Post Shipping: by WooCommerce – 2.5.18 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Catalog Visibility Options: by Lucas Stark – 3.2.10 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.36 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Composite Products: by SomewhereWarm – 7.0.6
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.8.4
WooCommerce Currency Converter: by WooCommerce – 1.6.23 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.0.14 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Deposits: by WooCommerce – 1.5.3 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Distance Rate Shipping: by Automattic – 1.0.25 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Dropshipping: by WooCommerce – 2.6 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.21
WooCommerce EU VAT Number: by WooCommerce – 2.3.23 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce FedEx Shipping: by WooCommerce – 3.4.32 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Force Sells: by WooCommerce – 1.1.25 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.23 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Local Pickup Plus: by SkyVerge – 2.8.3 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Measurement Price Calculator: by SkyVerge – 3.17.5 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Memberships: by SkyVerge – 1.17.6
WooCommerce Min/Max Quantities: by WooCommerce – 2.4.19 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Mix and Match Products: by Kathy Darling – 1.10.0 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Name Your Price: by Kathy Darling – 3.1.4 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce One Page Checkout: by Automattic – 1.7.8 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Order Barcodes: by WooCommerce – 1.3.22 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce PayFast Gateway: by WooCommerce – 1.4.15 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Payments: by Automattic – 1.3.0 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.0.3 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce PayPal Payments Advanced Gateway: by WooCommerce – 1.24.11 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooCommerce – 4.5.0 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce PayPal Pro Hosted: by WooCommerce – 1.0.22 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce PDF Watermark: by WooCommerce – 1.2.1 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Points and Rewards: by WooCommerce – 1.6.36 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Pre-Orders: by WooCommerce – 1.5.28 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Product Add-ons: by WooCommerce – 3.0.38 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Product Bundles: by SomewhereWarm – 6.3.5
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.36 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Product Table: by Codup.io – 1.2.2.19 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Product Vendors: by WooCommerce – 2.1.42 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Purchase Order Payment Gateway: by WooCommerce – 1.2.11 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Royal Mail: by WooCommerce – 2.5.30
WooCommerce Sales Report Email: by WooCommerce – 1.1.15 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Services: by Automattic – 1.24.1 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Shipment Tracking: by WooCommerce – 1.6.24 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Shipping Per Product v2: by WooCommerce – 2.3.11 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Smart Coupons: by StoreApps – 4.8.0
WooCommerce Square: by WooCommerce – 2.1.6 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Store Credit: by Themesquad – 3.2.1 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Stripe Gateway: by WooCommerce – 4.5.2 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Subscriptions: by WooCommerce – 3.0.7
WooCommerce Subscriptions Gifting: by WooCommerce – 2.1.1 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.29 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce UPS Shipping: by WooCommerce – 3.2.28 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce USPS Shipping: by WooCommerce – 4.4.47 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Waitlist: by Neil Pie – 2.1.24 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Warranty Requests: by WooCommerce – 1.9.18 – Installed version not tested with active version of WooCommerce 4.4.1
WP Crontrol: by John Blackbourn & crontributors – 1.8.5
WP Mail Logging: by MailPoet – 1.9.6
WP Rollback: by Impress.org – 1.7.1

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.7.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
bundle (bundle)
composite (composite)
cpb_custom_product_boxes (cpb_custom_product_boxes)
external (external)
grouped (grouped)
mix and match (mix-and-match)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #7 - /
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.8 (update to version 2.6.0 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1,689
Oldest: 2020-07-24 12:46:55 -0400
Newest: 2020-08-24 12:39:19 -0400

Pending: 10
Oldest: 2020-08-24 12:43:19 -0400
Newest: 2020-08-31 06:53:33 -0400
</details>

**Comment by juliaamosova** [comment]
Hi @senff,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/26590. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
