### ISSUE TITLE
Rename built-in PayPal payment method to PayPal Standard

### ISSUE THREAD

**Issue by thenbrent** [woocommerce/woocommerce#27467]
The PayPal Standard payment method name in core is currently _PayPal_. This creates ambiguity about which PayPal integration is built into core. It also encourages adoption of PayPal Standard as the integration method, when newer methods are preferable.

Our partners at PayPal have requested the payment method name be updated to the more accurate _PayPal Standard_.

More details: pb0GrA-Qc-p2

**Comment by mensmaximus** [comment]
Imho paypal standard should be phased out because the interface does not get any support from paypal anymore. Any issus with paypal standard in the past 24 month could be solved by replaincg it with the new paypal checkout gateway.

**Comment by thenbrent** [comment]
@mensmaximus this change is in fact a small part in work toward phasing out PayPal Standard in favor of a newer version of PayPal. 🙂
