### ISSUE TITLE
Class "class-wc-widget-price-filter.php" version

### ISSUE THREAD

**Issue by chyvak1831** [woocommerce/woocommerce#27474]
Since version WooCommerce 2.3.0 this file
`woocommerce\includes\widgets\class-wc-widget-price-filter.php`
get a lot updates, but at top of file still present 
` * @version  2.3.0`
I'm not sure - is this ok or version of this file had to be changed with each update...?

**Comment by rrennick** [comment]
> is this ok or version of this file had to be changed with each update...?

That's the version where the class was introduced. New methods in classes have `@since` docs.
