### ISSUE TITLE
Some product attributes disappeared

### ISSUE THREAD

**Issue by atikullamerchant** [woocommerce/woocommerce#27502]
Hi Team,

**Issue:**
I can see all my attributes on the backend but these attributes are missing from my front end filter on the category page.

**Solutions Tried:**
1. I’ve tried adding a test attribute in hope that everything falls back in place but that didn’t solve my problem.
2. These brands were showing properly earlier, so I'm quite sure its not a product issue. I've also checked some random products, and all of them were having the brand in their attribute.

**Changes Done before the issue:**
1. Updated my woocommerce plugin
2. Added two new categories and a couple of attributes. (but this is a usual process, we keep adding new attributes and categories from time to time)

These are the Brand attributes present on my back-end:
[https://bikesterglobal.com/shop/wp-content/uploads/2020/08/Screenshot-2020-08-27-at-5.19.38-PM.png](url)

And these are the Brand Attributes showing on my front-end:
[https://bikesterglobal.com/shop/wp-content/uploads/2020/08/Screenshot-2020-08-27-at-5.20.04-PM-scaled.png](url)

**Comment by juliaamosova** [comment]
Hi @atikullamerchant,

Thanks for raising the issue and sorry to hear about the trouble. I think the issue you are having is largely connected to this one here: https://github.com/woocommerce/woocommerce/issues/27419.  

Can you please confirm if you have these issues with variable products or does it happen with simple products as well? Or is it hard to tell?

**Comment by robert281119** [comment]
Hello
When I upgrade WordPress 5.5. all Variable products 'jump' so Simple product and not possible return to Variable.  if become to sell the product have the status. out of stock'  As I understand you have some problem ?? 
Thank you Robert

**Comment by MC-Rider** [comment]
Also posted this in thread #27419. But that thread appears to have been closed so wanted to post here too as they are related issues...

---
Reverting to WooCommerce v4.3.3 appears to have fixed the problem for me. I tried removing code line 399 in v4.4.1 as mentioned above (in post #27419) and that did not solve my problem (that I described also in post #27419 ).

Question: Not sure if this is a related issue or not — I just noticed today that pagination on my main Shop page only is not working correctly. From the main Shop page, Page 2 and onward show no products but do show Categories as normal. Pagination from Category pages is working as normal, the issue exists only on the main Shop page.

Has anyone else noticed this? Or is this an issue of my own? Wondered if perhaps there was some sort of common error behind both the Shop page pagination missing products issue and the attribute filters missing products issue. Thx.

**Comment by juliaamosova** [comment]
Hi everyone! 

We released [WooCommerce 4.5.2](https://developer.woocommerce.com/2020/09/14/woocommerce-4-5-2-fix-release/) just now - it contains the fix for the issue with the `Filter by Attribute` widget. Essentially, we rolled back to the way it used to work in WooCommerce 4.3. 

Please update to WooCommerce 4.5.2 and let us know if you are still experiencing any issues. Thanks for testing and for your patience everyone!

**Comment by juliaamosova** [comment]
Users in https://github.com/woocommerce/woocommerce/issues/27419 reported that this issue had been fixed by WooCommerce 4.5.2 update so I am closing it. 

Please continue sharing feedback in case there are still some issues with `Filter products by attributes` widget.

**Comment by eyal531** [comment]
Hi everyone,
I also had this problem after woocommerce database update. website: [Our Name Jewelry]( https://ournamejewelry.co.il/)
The solution was to add new attribute - and then all the attributes returned as if nothing happened.
