### ISSUE TITLE
Importing product and retaining the CSV ID instead of new ID.

### ISSUE THREAD

**Issue by tnchuntic** [woocommerce/woocommerce#27505]
Just wanted to ask if its possible to force the Woocommerce product import to use the CSV ID instead of creating new ID.

Currently in the import page its allowing me to mapped-out the ID field to the ID in CSV but when processing starts its creating new ID.

Why I want to keep the CSV ID instead of creating new ID is because of I want to retain the same ID of the product to keep the orders mapped out.

Scenario:
- Accidentally deleted the Product ID 123 
- Order 20 have Product ID 123

Plan of fixing the issue:
- Restore live website before the deletion of product into a Staging website
- Export existing product get only the deleted product using woocommerce export
- Import the exported deleted product using woocommerce import.

So that way I can restore back the product and still make the order work.

Hope to hear from your end.

**Comment by rrennick** [comment]
> Just wanted to ask if its possible to force the Woocommerce product import to use the CSV ID instead of creating new ID.

@tnchuntic When you insert a new record into the `wp_posts` table the ID field is assigned by MySQL. WordPress doesn't support specifying an ID on `wp_posts` insert. 

In your case, the existing orders should have enough of the product data to continue to display the product info in the existing orders.
