### ISSUE TITLE
Add WordPress.com hosting to status report

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#27511]
**Is your feature request related to a problem? Please describe.**
Now that premium plugins are allowed to be installed at WordPress.COM sites, when I get a support ticket I have no way of knowing if the site requesting support is a .COM or a self-hosted site.

**Describe the solution you'd like**
Add .COM hosting status to the system status

**Describe alternatives you've considered**
The only real alternative is to visit the site and browse the source code and then make an informed guess.

**Comment by tammullen** [comment]
Hi @helgatheviking 

Thank you for taking the time to share this idea, we really appreciate your help

I'm going to close your issue in favor of the previously submitted https://github.com/woocommerce/woocommerce/issues/27000 as we had already labelled that issue as an ehancement. Please continue sharing your feedback there if needed.

One thing which might help with identifying WordPress.com sites is looking for plugins in the report like these
![Screenshot_2020-08-28_at_15_56_06](https://user-images.githubusercontent.com/24649833/91582013-258a6c80-e947-11ea-97fa-43ef78e4d232.png)

**Comment by helgatheviking** [comment]
oh my gosh... i duplicated MYSELF! well I am having a day I guess. Sorry about that... and thanks for the tip, esp the MU plugin might be enough info.
