### ISSUE TITLE
Invalid call to get_avatar() in Recent Reviews dashboard widget

### ISSUE THREAD

**Issue by mundschenk-at** [woocommerce/woocommerce#27529]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
`get_avatar()` is called with an invalid argument in `WC_Admin_Dashboard::recent_reviews()`. The [`$id_or_email` parameter is set to `$comment->comment_author`](https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-dashboard.php#L330) in the call to `get_avatar()`. The comment author name is not an expected value for this parameter. As [documented in the API](https://developer.wordpress.org/reference/functions/get_avatar/#parameters), allowed values are "a user_id, gravatar md5 hash, user email, WP_User object, WP_Post object, or WP_Comment object".

**Expected behavior**
The whole `$comment` object should be passed to `get_avatar()`.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
Not relevant.
```
</details>

**Comment by rodrigoprimo** [comment]
Thanks for reporting this issue. PR #28067 should fix it.
