### ISSUE TITLE
Add content-visibility in WooCommerce CSS

### ISSUE THREAD

**Issue by Camilo517** [woocommerce/woocommerce#27524]
There is a new CSS rule that improves loading time, it would be interesting to add it in WooCommerce

Here he explains it and there is a proof:
https://web.dev/content-visibility/

**Comment by Camilo517** [comment]
Some news? It is something very simple to implement and it will help a lot

**Comment by nerrad** [comment]
This is a great promising new CSS rule but [is still experimental](https://developer.mozilla.org/en-US/docs/Web/CSS/content-visibility) and as a result is not something that can be considered for WooCommerce yet.
