### ISSUE TITLE
[4.5 RC1] function auto_update_woocommerce not found or invalid function name

### ISSUE THREAD

**Issue by kkmuffme** [woocommerce/woocommerce#27530]
PHP Error: call_user_func_array() expects parameter 1 to be a valid callback, function auto_update_woocommerce not found or invalid function name
File: /wp-includes/class-wp-hook.php on line 287
Error URL: /wp-admin/plugins.php
Trace:

```
#0 \wp-includes\plugin.php (206): WP_Hook->apply_filters( $value = NULL, $args =
Array(
  [0] => 
  [1] => stdClass Object
)
)
#1 \wp-admin\includes\class-wp-plugins-list-table.php (236): apply_filters( $tag = auto_update_plugin, $value = NULL, stdClass Object )
#2 \wp-admin\plugins.php (533): WP_Plugins_List_Table->prepare_items()
```

since WP5.5 (incl. 5.6), tested on WC 4.4 & 4.5rc1 where both versions have this issue

**Comment by ktmn** [comment]
```Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'auto_update_woocommerce' not found or invalid function name in .../wp-includes/class-wp-hook.php on line 287```

WC 4.5.2

Only get them while Beta Tester is active, on `/wp-admin/plugins.php` page.

Same with WC 4.6.0-rc.1

Might just be beta tester plugin issue.

In WC Beta Tester the "Automatic Updates" option is not enabled and neither is the WP core auto update option for any plugins.

**Comment by rrennick** [comment]
Fixed in https://github.com/woocommerce/woocommerce-beta-tester/pull/74
