### ISSUE TITLE
[v2 & v3] System Status filter data changed type in v1.0.6/WC 3.9

### ISSUE THREAD

**Issue by ChaseWiseman** [woocommerce/woocommerce#27554]
The primary `$request` parameter that's passed to the `woocommerce_rest_prepare_system_status` filter has inconsistent data between v1.0.5 and 1.0.6.

Previously, many of the top-level property values like `environment` and `settings` that are present in `\WP_REST_Response::$data` were PHP objects, matching their type in the schema.

Due to the changes in https://github.com/woocommerce/woocommerce-rest-api/pull/93, those are now arrays which breaks compatibility with plugins filtering `woocommerce_rest_prepare_system_status` and manipulating that data, like adding custom properties to the `environment` object.

Note the final REST API response still has the correct property types, it's just the data moving through filters that's changed.

**Comment by peterfabian** [comment]
I'm guessing this is not really super important since it's been a long time since reporting, so closing. If you think we still should fix this, please let us know. Thanks.
