### ISSUE TITLE
Payments going through without payment method filled in.

### ISSUE THREAD

**Issue by Engage11** [woocommerce/woocommerce#27550]
I was going to send this as a bug report but I'm sure someone else would also have this problem.
People are sending transactions without inputting their card information, and the information is being sent to us as payed for with credit card information processed.
We did a test and intentionally left the card fields blank. It submitted completely and there is nothing to show otherwise that there was no card or payment.

`
### WordPress Environment ###

WordPress address (URL): https://www.heartlandforest.org
Site address (URL): https://www.heartlandforest.org
WC Version: 4.4.1
REST API Version: ✔ 1.0.15
WC Blocks Version: ✔ 3.2
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.4.0
Log Directory Writable: ✔
WP Version: 5.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.21
PHP Post Max Size: 32 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 7.72.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.6.47
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.4.1
WC Database Prefix: wp_
Total Database Size: 129.63MB
Database Data Size: 111.06MB
Database Index Size: 18.57MB
wp_woocommerce_sessions: Data: 3.82MB + Index: 0.14MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.12MB + Index: 0.07MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.86MB + Index: 0.64MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.64MB + Index: 0.19MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.48MB + Index: 0.30MB + Engine MyISAM
wp_bwg_album: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_bwg_album_gallery: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_bwg_gallery: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_bwg_image: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_bwg_image_comment: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_bwg_image_rate: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_bwg_image_tag: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_bwg_option: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_bwg_shortcode: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_bwg_theme: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_childthemewp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 1.45MB + Index: 0.53MB + Engine InnoDB
wp_ewwwio_images: Data: 0.26MB + Index: 0.11MB + Engine MyISAM
wp_gallery_galleries: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gallery_galleriesslides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gallery_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gmp_htmltype: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gmp_icons: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_gmp_maps: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gmp_markers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gmp_marker_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gmp_modules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gmp_modules_type: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gmp_options: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gmp_options_categories: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gmp_usage_stat: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_litespeed_img_optm: Data: 0.06MB + Index: 0.05MB + Engine MyISAM
wp_litespeed_optimizer: Data: 3.56MB + Index: 0.09MB + Engine MyISAM
wp_maxbuttonsv3: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_maxbuttons_collections: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_maxbuttons_collections_trans: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mclean_refs: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_mclean_scan: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp_mgmlp_folders: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_nextend2_image_storage: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_nextend2_section_storage: Data: 0.06MB + Index: 0.01MB + Engine MyISAM
wp_nextend2_smartslider3_generators: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nextend2_smartslider3_sliders: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_nextend2_smartslider3_sliders_xref: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nextend2_smartslider3_slides: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_nf3_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nf3_action_meta: Data: 0.20MB + Index: 0.03MB + Engine MyISAM
wp_nf3_chunks: Data: 1.05MB + Index: 0.00MB + Engine MyISAM
wp_nf3_fields: Data: 0.07MB + Index: 0.01MB + Engine MyISAM
wp_nf3_field_meta: Data: 7.28MB + Index: 1.49MB + Engine MyISAM
wp_nf3_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nf3_form_meta: Data: 0.33MB + Index: 0.02MB + Engine MyISAM
wp_nf3_objects: Data: 0.18MB + Index: 0.07MB + Engine MyISAM
wp_nf3_object_meta: Data: 15.93MB + Index: 0.13MB + Engine MyISAM
wp_nf3_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_nf3_upgrades: Data: 2.24MB + Index: 0.00MB + Engine MyISAM
wp_nf_objectmeta: Data: 0.17MB + Index: 0.03MB + Engine MyISAM
wp_nf_objects: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_nf_relationships: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_ngg_album: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ngg_gallery: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_ngg_pictures: Data: 0.14MB + Index: 0.01MB + Engine MyISAM
wp_ninja_forms_fav_fields: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_ninja_forms_fields: Data: 0.82MB + Index: 0.01MB + Engine MyISAM
wp_options: Data: 7.16MB + Index: 0.23MB + Engine InnoDB
wp_postmeta: Data: 30.20MB + Index: 10.80MB + Engine InnoDB
wp_posts: Data: 24.13MB + Index: 0.95MB + Engine InnoDB
wp_psninja_amdd: Data: 3.30MB + Index: 1.32MB + Engine MyISAM
wp_psninja_amdd_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_psninja_urls: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_rg_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rg_form_meta: Data: 0.05MB + Index: 0.00MB + Engine MyISAM
wp_rg_form_view: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rg_incomplete_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rg_lead: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rg_lead_detail: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_rg_lead_detail_long: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rg_lead_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rg_lead_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rg_stripe: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rg_stripe_transaction: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_smush_dir_images: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_tm_tasks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Data: 2.50MB + Index: 0.30MB + Engine InnoDB
wp_users: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_volunteer_emails: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_volunteer_rsvps: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wauc_auction_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wauc_winners: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.04MB + Index: 0.05MB + Engine MyISAM
wp_wc_order_stats: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.03MB + Index: 0.05MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wdm_bidders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfBadLeechers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfBlockedIPLog: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfBlocks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfBlocksAdv: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfConfig: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wfCrawlers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfFileMods: Data: 2.51MB + Index: 0.50MB + Engine MyISAM
wp_wfHits: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_wfHoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfIssues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfLeechers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfLockedOut: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfLocs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfLogins: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfNet404s: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfReverseCache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfScanners: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfStatus: Data: 0.07MB + Index: 0.03MB + Engine MyISAM
wp_wfThrottleLog: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfVulnScanners: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woo_ua_auction_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpgmza: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_category_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_maps: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_polygon: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpgmza_polylines: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpml_mails: Data: 0.65MB + Index: 0.00MB + Engine MyISAM
wp_wps_woo_grid: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wrt_tabs: Data: 0.06MB + Index: 0.00MB + Engine MyISAM
wp_wrt_tabs_settings: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_yoast_seo_links: Data: 0.04MB + Index: 0.01MB + Engine MyISAM
wp_yoast_seo_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 457
calendar: 1
custom_css: 4
display_type: 7
ec_store: 1
maxgallery: 1
mgmlp_media_folder: 95
mts_notification_bar: 1
nav_menu_item: 39
nf_sub: 2834
ngg_gallery: 1
ngg_pictures: 62
nimble_post_type: 4
page: 109
post: 1
product: 103
product_variation: 162
revision: 1040
safecss: 1
shop_coupon: 8
shop_order: 1319
shop_order_refund: 10
tribe_events: 18
tribe_organizer: 1
tribe_venue: 2
tt_font_control: 1
ultimate-auction: 1
volunteer_opp: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (28) ###

Black Studio TinyMCE Widget: by Black Studio – 2.6.9
Bulk remove posts from category: by MasterNs – 3.1.1
Classic Editor: by WordPress Contributors – 1.6
Flexible Checkout Fields: by WP Desk – 2.5.2
Helcim Commerce for WooCommerce: by Helcim Inc. – 1.1.8 – Installed version not tested with active version of WooCommerce 4.4.1
Jetpack by WordPress.com: by Automattic – 8.8.2
Media Cleaner: by Jordy Meow – 6.0.4
Max Mega Menu: by megamenu.com – 2.8
Ninja Forms - Addon Manager: by The WP Ninjas – 3.0.13
Ninja Forms - Conditional Logic: by The WP Ninjas – 3.0.28
Ninja Forms - Multi-Part Forms: by The WP Ninjas – 3.0.26
Ninja Forms - Layout & Styles: by The WP Ninjas – 3.0.28
Ninja Forms: by Saturday Drive – 3.4.26
Fonts Plugin | Google Fonts Typography: by Fonts Plugin – 2.1.9
PageSpeed Ninja: by PageSpeed Ninja – 0.9.43
WP Responsive Tabs horizontal vertical and accordion Tabs: by I Thirteen Web Solution – 1.1.11
Page Builder by SiteOrigin: by SiteOrigin – 2.11.2
Sitewide Notice WP: by Yoohoo Plugins – 2.2.1
Smart Slider 3: by Nextend – 3.4.1.9
SiteOrigin Widgets Bundle: by SiteOrigin – 1.17.6
WooCommerce Blocks: by Automattic – 3.2
Advanced Order Export For WooCommerce: by AlgolPlus – 3.1.5
WooCommerce Admin: by WooCommerce – 1.4.0 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.23 – Installed version not tested with active version of WooCommerce 4.4.1
WooCommerce: by Automattic – 4.4.1
WP Mail Logging: by MailPoet – 1.9.6
YITH WooCommerce Name Your Price: by YITH – 1.1.15
NextGEN Gallery: by Imagely – 3.3.17

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CAD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: auction (auction)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #12371 - /shop/
Cart: ❌ Page does not contain the shortcode.
Checkout: #4102 - /checkout/
My account: #4103 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Nineteen Child
Version: (update to version 0 is available)
Author URL: https://childthemewp.com/twenty-nineteen/
Child Theme: ✔
Parent Theme Name: Twenty Nineteen
Parent Theme Version: 1.7
Parent Theme Author URL: https://wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1,591
Oldest: 2020-08-01 11:12:14 -0400
Newest: 2020-09-01 09:42:08 -0400

Pending: 6
Oldest: 2020-09-01 10:38:11 -0400
Newest: 2020-09-07 09:49:03 -0400

`

**Comment by Engage11** [comment]
I think I may have figured it out. It was my coworker signed in and manually placing a payment for someone. It sent it through thinking it was a test transaction. As I have already said, there is no way to know if the transaction is bad because it sends an order email exactly the same way. So my question now would be, how do I turn off this feature?

**Comment by Engage11** [comment]
WooCommerce is not in test mode, which makes the whole allowing to skip the payment fields, look more like a legit bug. I hope someone notices and patches within the next update.

**Comment by negapo** [comment]
Hi @Engage11 
The problem must be with your credit card plug-in (Helcim Commerce) and not WooCommerce, the plug-in handles that validation.

**Comment by Engage11** [comment]
Thanks, I contacted them directly. I have a suspicion that it could be a Chrome thing as well.

**Comment by juliaamosova** [comment]
Hi @Engage11,

Thanks for raising the issue. However, if you are using one of the payment gateway plugins, it will be best to contact them for further help which you mentioned you already did. 

>I think I may have figured it out. It was my coworker signed in and manually placing a payment for someone. It sent it through thinking it was a test transaction. As I have already said, there is no way to know if the transaction is bad because it sends an order email exactly the same way. So my question now would be, how do I turn off this feature?

It is not clear what feature you are looking to turn off here? Is it the ability to place manual orders in WooCommerce? If this is the case, there is no option in settings to disable this functionality. 

If you want to limit others who have access to your site, you can give them a user role that will not allow them to create manual orders: https://docs.woocommerce.com/document/roles-capabilities/.

**Comment by Engage11** [comment]
I think you missed the other part of my messages. I thought there was a feature to allow transactions without card data filled out.
It put through 2 transactions and randomly grabbed a card used from 5-6 months ago. Normally it would warn when the payment fields are not filled out. The bug happened twice and I can't seem to find record of where the issue occurred.
I'm still waiting to hear back from the payment provider as to why their plugin did that.



________________________________

**Comment by juliaamosova** [comment]
>I think you missed the other part of my messages. I thought there was a feature to allow transactions without card data filled out.

We don't have such a feature in WooCommerce Core. If there is one in your site, it is likely provided by the payment gateway plugin. 

It doesn't look like there is a bug in WooCommerce Core which is why I am closing this issue. Please feel free to comment back in case I missed something and we'd take another look.
