### ISSUE TITLE
Shipping costs on refunds

### ISSUE THREAD

**Issue by tommiby** [woocommerce/woocommerce#27566]
Hello,

it seems that refunfded shipping costs are not showing on order refunds when refund is accessed through REST API. The refund shows only the refunded order rows but not the shipping cost details when the shipping costs had been refunded. Would it be possible to add the the refunded shipping cost data also to refunds similar way as it is the orders?

**Comment by mahmoudsaeed** [comment]
@vedanshujain I can work on a PR if nobody is already doing this.
