### ISSUE TITLE
WooCommerce Slack Extension Issue

### ISSUE THREAD

**Issue by imranbts** [woocommerce/woocommerce#27588]
There is an exception handling issue found in the WooCommerce Slack extension.

Please see the issue details below.

**Issue Description:**

An error of type E_ERROR was caused in line 186 of the file /wp-content/plugins/woocommerce-slack/includes/class-wcslack-client.php. Error message: Uncaught Error: Cannot use object of type WP_Error as array in /wp-content/plugins/woocommerce-slack/includes/class-wcslack-client.php:186

`private function post( $payload ) {
		$response = wp_remote_post( $payload['url'], array(
			'body' => $payload['post'],
		) );

		if ( empty( $response['body'] ) ) {
			throw new Exception( 'Got invalid response object, possibly a WP_Error.' );
		}

		return json_decode( $response['body'] );
}`

WP_Error is an object and passed in the response if failed wp_remote_post but in condition it's being checked as an Array.

Hope you resolve this issue in next release.

Thanks.

**Comment by mikkamp** [comment]
Moved over to the woocommerce-slack repo: https://github.com/woocommerce/woocommerce-slack/issues/71
