### ISSUE TITLE
When errors prevent loading the checkout, only generic text is shown

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce#27609]
Here in https://github.com/woocommerce/woocommerce/blob/6eb65cb40c79c2b657b190793ca9a25dccec06b1/includes/shortcodes/class-wc-shortcode-checkout.php#L280 , there's a check on whether any errors have been registered. If they have, then the template `checkout/cart-errors.php` is shown.

That template contains only a generic error message ("There are some issues with the items in your cart. Please go back to the cart page and resolve these issues before checking out."). The actual text of the errors that were registered is not shown; it is ultimately just discarded.

Is there any reason for this? Should the text that was passed as the first parameter to `wc_add_notice($text, 'error')` not be shown?

**Comment by jonathansadowski** [comment]
Thanks for taking the time to ask about this @DavidAnderson684. I was able to verify the behavior that you're describing by using this snippet:

```
add_action( 'woocommerce_before_checkout_form_cart_notices', function() {
	wc_add_notice( 'Test error message', 'error' );
} );
```

You're correct that the actual error message isn't displayed. Thank you for taking the time to share the idea to display errors on that page, we really appreciate your help. While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the `votes needed` label and evaluate over time if this issue collects more feedback.

Don’t be alarmed if you don’t see any activity on this issue for a while.
