### ISSUE TITLE
Tax is added to shipping classes when "I will enter prices including VAT" is selected

### ISSUE THREAD

**Issue by glagonikas** [woocommerce/woocommerce#27611]
**Prerequisites (mark completed items with an [x]):**
- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When tax is enabled and set to "I will enter prices including VAT", any taxable shipping classes do not get the memo and still have tax added to them.

**Expected behavior**
When "I will enter prices including tax" is selected, all prices (not just products) across the site should be entered including VAT OR there shouldn't be an option to make shipping classes taxable OR there should be a note next to the radio button stating shipping classes do not inherit this option.

**Actual behavior**
When tax is enabled and this option is selected, if any of the shipping classes are set to "Taxable" they automatically get the tax added to them on the front end. The label on the radio button states "Changing it will not update existing products." but there is no reference about shipping classes, and there is no way of updating shipping classes, as they show the correct price on the back end.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

1. Go to /wp-admin/admin.php?page=wc-settings&tab=general and enable taxes
2. On /wp-admin/admin.php?page=wc-settings&tab=tax make sure the “Yes, i will enter prices including tax” is selected
3. On /wp-admin/admin.php?page=wc-settings&tab=tax&section=standard add a new rate for “GB” with 20%
4. On /wp-admin/admin.php?page=wc-settings&tab=shipping&zone_id=1 make sure the “Flat Rate” options are set to "taxable"
5. Go to a product page and add it to the cart
6. Go to checkout, and check the shipping price

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

WordPress address (URL): 
Site address (URL): 
WC Version: 4.4.1
REST API Version: ✔ 1.0.15
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.4.0
Log Directory Writable: ✔

WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: –
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: nginx/1.18.0
PHP Version: 7.4.9
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.1.1c

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.17-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔


### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.4.1

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
featured (featured-de)
outofstock (outofstock)
outofstock (outofstock-de)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5007 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #93 - /terms-conditions/

### Theme ###

Name: Storefront
Version: 2.6.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by juliaamosova** [comment]
Hi @glagonikas,

Thanks for raising the issue. However, I don't see a bug here but rather misconfiguration of shipping settings. 

The way to control whether or not the tax will be applied to shipping is by selecting/deselecting the option `Shipping` in the tax rate itself by navigating to `WooCommerce/Settings/Tax/Standard (or any other) rates`. The `Shipping` option allows to choose whether the tax rate should be applied to shipping or not:

![tax](https://user-images.githubusercontent.com/19143190/92970636-fd256680-f44c-11ea-90a5-f8b0f9c9da63.jpg)

In my case, I have the following tax settings:

![Screen Shot 2020-09-11 at 4 28 52 PM](https://user-images.githubusercontent.com/19143190/92970693-15958100-f44d-11ea-9b83-3b44f87f30ac.png)

The following flat rate setting:

![Screen Shot 2020-09-11 at 4 32 03 PM](https://user-images.githubusercontent.com/19143190/92970738-2a721480-f44d-11ea-9f30-5bcdf3c7e7a2.png)

If I select the 20% tax rate to apply for my $20 shipping price (via `WooCommerce/Settings/Tax/Standard (or any other) rates`), I get a shipping price of $24 (tax included) in the cart:

![taxyes](https://user-images.githubusercontent.com/19143190/92971053-c26ffe00-f44d-11ea-8c4d-8cec8723d10f.jpg)

But I don't select the checkbox next to the `Shipping` option, I will get a shipping price of $20 while the tax is still applied to the product:

![taxno](https://user-images.githubusercontent.com/19143190/92971065-c69c1b80-f44d-11ea-88f1-7e83cb03f13c.jpg)

I am closing this issue as I don't see a big here. However, please feel free to reply with a follow-up in case I missed something and we'd take another look.

**Comment by glagonikas** [comment]
Hi @juliaamosova, thanks for looking into this.

Apologies, but I might not have explained the issue well enough here.

Based on your screenshots, you have specified that you will be entering the prices on the site, including tax. Then on your flat rate settings, you have entered a price of $20. This is your price **including** VAT.

On the front end, I'd expect to see the shipping price as "Flat rate (Florida): $20.00" because you've entered the price **including** VAT, no?

The checkbox on the Standard tax rates, states "Choose whether or not this tax rate also gets applied to shipping.". We want VAT to be applied on shipping, so we have this enabled. I don't see why you'd add an additional 20% on the shipping cost, as the price we've entered **includes** VAT.

Hope this makes sense?

**Comment by juliaamosova** [comment]
Thanks for your follow-up @glagonikas! I am reopening this issue so it doesn't get lost but I am running out of time to take a look at it today. I will do that on Monday.

**Comment by glagonikas** [comment]
Hi @juliaamosova Let me know if you need anything further for me

**Comment by glagonikas** [comment]
Hi @juliaamosova was wondering if you had time to review this bug and confirm? We need to know if it's a bug or "feature" before we proceed with a new integration we've planned.

**Comment by tammullen** [comment]
Hi @glagonikas 

Apologies for the delay in replying.

https://github.com/woocommerce/woocommerce/wiki/How-Taxes-Work-in-WooCommerce#defining-prices

> Note: shipping prices are always defined excluding tax in the current system

I believe this confirms this is the expected behaviour

**Comment by glagonikas** [comment]
@tammullen Thanks for pointing to the docs. Is there a roadmap on changing this (as mentioned in the docs)?

On stores that add prices including tax, it's quite confusing having to enter just the shipping costs excluding tax.

**Comment by juliaamosova** [comment]
>@tammullen Thanks for pointing to the docs. Is there a roadmap on changing this (as mentioned in the docs)?

Hi @glagonikas thank you for your follow-up! We don't have it on our roadmap to change the way the setup on stores that add prices including tax currently works. You are welcome to file an enhancement type of issue. However, the situation will likely remain as-is for some time. 

I'll go ahead and close this issue as a non-bug though.

**Comment by glagonikas** [comment]
@juliaamosova I appreciate you're trying to clean up the number of open tickets, but your response will simply create more.

You say this is not a bug and you are happy with the docs, BUT the docs state

> Note: shipping prices are always defined excluding tax in the current system, **_although a change is being considered._**

If you're closing this issue and asking me to create an enhancement, you should at least remove the "although..." part from your docs so the docs are accurate and people don't wait in vain for this feature. If it's not on your roadmap, you're clearly not considering this change and therefore, as a minimum, there's a bug in your docs.

It took us 7 months to get to this point due to slow responses and nobody knows when/if this will ever be implemented, so a least make sure the docs are accurate.

**Comment by peterfabian** [comment]
I'm marking this as an enhancement with votes needed, so please vote on the initial comment in this thread if you'd like to see this implemented.
