### ISSUE TITLE
i18n: automatically import W.org translations from woocommerce-admin

### ISSUE THREAD

**Issue by jeherve** [woocommerce/woocommerce#27622]
I see that you're already updating the textdomain strings for packages like WooCommerce Admin thanks to this script:
https://github.com/woocommerce/woocommerce/blob/d9990b752e2744406870380380e3fd0f085bd33e/bin/package-update.sh

This allows all strings originally created for the WooCommerce Admin plugin to be made available for translation on translate.wordpress.org.

I was curious, however, if existing WooCommerce Admin translations (available [here](https://translate.wordpress.org/projects/wp-plugins/woocommerce-admin/)) could be migrated to the WooCommerce plugin [here](https://translate.wordpress.org/projects/wp-plugins/woocommerce/) on each WooCommerce release? This way WooCommerce site owners would benefit from the work translation contributors put into translating the WooCommerce Admin plugin, and would avoid duplicating work.

All that said, this may already be happening :) Let me know if that's the case!

Thank you!

cc @budzanowski; I see you've done some translation work in #26750 a few months back; maybe you'll know if this is already done today.

**Comment by budzanowski** [comment]
That would be a question to Team Global @akirk .

**Comment by akirk** [comment]
Are we planning to remove the `woocommerce-admin` plugin from WordPress.org? Just to understand if this would be a one-time effort or something continuous.

**Comment by rrennick** [comment]
> Are we planning to remove the woocommerce-admin plugin from WordPress.org?

I don't believe so.

**Comment by nicomollet** [comment]
@jeherve What is the status on this?
In fr_FR release, I still see many untranslated strings in the admin part.
For example "Items Sold" string is translated in fr_FR but does not appear in the Statistics screen.

![image](https://user-images.githubusercontent.com/108828/101905566-f0352200-3bb7-11eb-8a02-86d6b2db2c0f.png)

WooCommerce version 4.8.0, and "wooCommerce" fr_FR is 100% translated. "woocommerce-admin" fr_FR is incomplete though.
Thank you

**Comment by jeherve** [comment]
> What is the status on this?

I don't really have any more information.

Your issue seems a bit different (albeit related) from what I was mentioning above though. I had created this issue to suggest porting WooCommerce Admin translations to WooCommerce when a new version of WooCommerce Admin was brought to WooCommerce itself.

In your screenshot, it would appear that part of the Woo dashboard does not display translations, even though [those strings are translated in translate.wordpress.org](https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/fr/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=9167391&filters%5Btranslation_id%5D=70707140). Maybe #26994 should be reopened? @jeffstieler I see you worked on that original translation issue; do you think you could take a look?

Thank you!

**Comment by rrennick** [comment]
> I was curious, however, if existing WooCommerce Admin translations (available here) could be migrated to the WooCommerce plugin here on each WooCommerce release?

@jeherve I don't know of any plugins where translations available via https://translate.wordpress.org are submitted through the plugin repository SVN. The [WooCommerce versions](https://plugins.trac.wordpress.org/browser/woocommerce/#tags/5.8.0) do not have any language files included. The language files are automatically generated by the WordPress.org infrastructure. Can you provide a reference project/plugin where translations submitted via SVN are delivered via https://translate.wordpress.org?

**Comment by jeherve** [comment]
> Can you provide a reference project/plugin where translations submitted via SVN are delivered via translate.wordpress.org?

I don't think that's possible. By migrating translations, I was referring to a manual process (that maybe could be automated, I'm not too familiar with the tool) via the Import options available at the bottom of a language page on translate.wordpress.org.

![image](https://user-images.githubusercontent.com/426388/137871733-d47a18f5-7c23-4d28-bad6-f28cf9bb2fc8.png)

**Comment by rrennick** [comment]
> By migrating translations, I was referring to a manual process (that maybe could be automated, I'm not too familiar with the tool) via the Import options available at the bottom of a language page on translate.wordpress.org.

For another use case this might be useful to investigate in advance. However, since WC Admin has been included in WooCommerce for 18 months, there would be little benefit in implementing that now. GlotPress has a feature to match existing translations to strings in an updated version. I don't recall whether that is automatic or not but on any given release of WC, 99% of the existing translations will apply to the new version. Because of the proximity of the two releases it's unlikely that the number of translated strings added would be significant.

I'll leave this open for a bit for follow up discussion but this probably isn't a project we would undertake.
