### ISSUE TITLE
Shipping cost not correct

### ISSUE THREAD

**Issue by nampen123** [woocommerce/woocommerce#27624]
Updated to 4.5.0 and now the orders didn't calculate the shipping costs.. 
So customers didn't pay for shipment. 

New setting that shipping cost only get calculated after filling in the adress is the cause of this issue.
Changed it to the old setting and now shipping cost is calculated.

Where can I get my money back?....

**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

**Comment by dougaitken** [comment]
Found this issue via 20283751-hc, I've replicated on my own site

* Ensure the option is checked **before** the update
 * **WP Admin > WooCommerce > Settings > Shipping > Shipping Options > Calculations > Check - Hide shipping costs until an address is entered**
* Update site to WooCommerce 4.5
* Go through order flow with a physical product that has shipping costs and would otherwise trigger a shipping method and fee
* Note you can process an order without choosing or being charged for shipping
* Uncheck `Hide shipping costs...` and resaved
* Note now that shipping will be calculated

Handy gif 

![https://d.pr/i/sLf2Um](https://d.pr/i/sLf2Um+)
Image link: https://d.pr/i/sLf2Um



And another - 8366354-hc

**Comment by tammullen** [comment]
Hi @nampen123 

Thank you for taking the time reporting this bug, we really appreciate your help. I can reproduce it on my end. 
Thanks @dougaitken for the extra info.

![Screenshot 2020-09-09 at 12 31 49](https://user-images.githubusercontent.com/24649833/92593097-7891e700-f298-11ea-8183-84ade9f9998c.png)
![Screenshot_2020-09-09_at_12_14_53](https://user-images.githubusercontent.com/24649833/92593114-7d569b00-f298-11ea-8633-fe2bf4076200.png)
![Screenshot_2020-09-09_at_12_29_17](https://user-images.githubusercontent.com/24649833/92593110-7af44100-f298-11ea-849c-4eb7b94fc0b6.png)

We’re going to solve this bug as soon as possible. Stay tuned for updates.

**Comment by peterfabian** [comment]
FYI:
Customer will be able to checkout without paying for shipping if both of the below are true:
- Customer’s country does not require state
- setting `Hide shipping costs until an address is entered` is checked

The workaround, for the time being, is to set `Hide shipping costs until an address is entered` to false.

We are working on a hotfix.

**Comment by PaulMHodgson** [comment]
Our E-Commerce site just lost money because of this issue.  We pay for Woocommerce services.... not happy.

**Comment by Archvist** [comment]
> Our E-Commerce site just lost money because of this issue. We pay for Woocommerce services.... not happy.

What WooCommerce services do you pay for?

**Comment by Daniel-HBK** [comment]
This issue drove me crazy for two hours!. if didn't notice updates counter I would be never stop debugging it!...Anyway thank you for the hotfix and concern.

**Comment by ejide28** [comment]
please help, am having the same issues

**Comment by ejide28** [comment]
where can I get shipping options?

**Comment by peterfabian** [comment]
Hi @stefanos82 , 

I guess it's possible that custom solutions need to be adjusted, so please check the code in this PR and let us know if you think what we did doesn't make sense from the perspective of extensibility. Thanks.

**Comment by stefanos82** [comment]
@peterfabian looks good to me.

Was is part of the newly released 4.5.2?

**Comment by peterfabian** [comment]
Those changes were shipped in 4.5.1.

(4.5.2 updated code related to filtering of variations)
