### ISSUE TITLE
variable product + variable/attribute in URL+ caching + UTM/gclid in URL = issue

### ISSUE THREAD

**Issue by StSaens** [woocommerce/woocommerce#27638]
- [ x ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Using variable products with caching woo fails to load the proper variation if attribute is passed in URL AND the URL contains gclid/UTM/fbclid etc.

Only when caching is enabled (WP Fastest Cache and W3 seem both to show same behaviour)
Tested on a clean WP with Woo and Caching

**Expected behavior**
I'd expect Woo to load (for instance) red if the URL contains ?pa_attribute_color=red and gclid/UTM/etc are present in the URL.

**Actual behavior**
Woo seems to default to the product/color it should show when cache is generated. So if the first call is to load color yellow it always defaults to yellow. If the first call is red, then it always shows red.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
I’ve noticed that something causes the wrong product to load when caching is enabled and the URL contains more parameters than product attribute.

This is when Google Ads add their clickID (gclid=xyz) to a URL, or when other attributes are added, such as UTM (&utm_source=facebook, etc) or facebook clicksID (fbclid)

Example (tested on a clean installed WP with Woo and caching:

/productA/ (shows default color yellow = good)
/productA/?attribute_pa_color=red (shows red color = good)
/productA/?attribute_pa_color=red&gclid=123abc (shows default color. Should show red)
/productA/?attribute_pa_color=red&utm_source=facebook&gclid=123abc (shows default color. Should show red)

I've worked around this issue by running some ugly JS to do a click on the specified attribute a bit after onload. But it's not how it should be I think.

**Isolating the problem (mark completed items with an [x]):**
- [ x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://xx.com
Site address (URL): http://xx.com
WC Version: 4.5.1
REST API Version: ✔ 4.5.1
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.5.0
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.43 (Unix)
PHP Version: 7.3.21
PHP Post Max Size: 76 MB
PHP Time Limit: 240
PHP Max Input Vars: 4000
cURL Version: 7.54.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.6.42-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.4.1
WC Database Prefix: fx9m_
Totale databasegrootte: 2.38MB
Database datagrootte: 1.01MB
Database index grootte: 1.37MB
fx9m_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fx9m_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fx9m_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fx9m_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
fx9m_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fx9m_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fx9m_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
fx9m_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fx9m_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fx9m_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fx9m_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fx9m_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fx9m_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fx9m_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fx9m_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
fx9m_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fx9m_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fx9m_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fx9m_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fx9m_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
fx9m_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fx9m_options: Data: 0.17MB + Index: 0.03MB + Engine InnoDB
fx9m_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fx9m_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
fx9m_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fx9m_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fx9m_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fx9m_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fx9m_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fx9m_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fx9m_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fx9m_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fx9m_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fx9m_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fx9m_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fx9m_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fx9m_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
fx9m_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fx9m_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fx9m_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
fx9m_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fx9m_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fx9m_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 3
page: 2
post: 2
product: 3
product_variation: 4

### Security ###

Secure connection (HTTPS): ❌
					Jouw winkel gebruikt geen HTTPS. Leer meer over HTTPS en SSL-certificaten.
Hide errors from visitors: ✔

### Active Plugins (3) ###

Limit Login Attempts Reloaded: door WPChef – 2.15.2
WooCommerce: door Automattic – 4.5.1
WP Fastest Cache: door Emre Vona – 0.9.1.0

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Winkelbasis: ❌ Pagina niet ingesteld
Winkelmand: ❌ Pagina niet ingesteld
Afrekenen: ❌ Pagina niet ingesteld
Mijn account: ❌ Pagina niet ingesteld
Algemene voorwaarden: ❌ Pagina niet ingesteld

### Theme ###

Name: Twenty Twenty
Version: 1.5
Author URL: https://nl.wordpress.org/
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een child thema aan. Zie: Hoe maak je een child thema

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Geannuleerd: 1
Oldest: 2020-09-04 14:10:32 +0000
Newest: 2020-09-04 14:10:32 +0000

Afgerond: 3
Oldest: 2020-09-04 14:10:32 +0000
Newest: 2020-09-10 09:51:08 +0000

`
```
</details>

**Comment by rrennick** [comment]
Hi @StSaens ,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

I set up W3 Total Cache with the following settings:
- page cache enabled (Disk)
- object cache enabled

Used a variable product with product attribute of `Size` with values `Small, Medium, Large`. Set `Medium` as the default size. Tested the following URLs
- `/product/test-25133/` - `Medium` preselected
- `/product/test-25133/?attribute_size=small` - `Small` preselected
- `/product/test-25133/?attribute_size=small&gclid=123abc` - `Small` preselected

In WordPress page caching is usually handled outside of any of other plugin functionality. This is necessary for page caching plugins like W3TC to work effectively across a large range of installs that have a large number of different plugins installed among them.

With the information you have provided my guess would be that you have something in your configuration that is filtering out query strings when certain patterns are matched.

I'm going to close this issue.. However, if you can demonstrate/detail how this issue can be created in an install we will be happy to re-open.
