### ISSUE TITLE
Updated to WooCommerce 4.5.0: Now Rest API results 404 (rest_no_route)

### ISSUE THREAD

**Issue by mkchetan25** [woocommerce/woocommerce#27631]
**Versions:**
Wordpress: 5.5.1
WooCommerce: 4.5.0

**Issue Description:**
Recently, I updated woocommerce to the latest version and now I'm facing this error while accessing the REST API
URL: https://v2farmfresh.com/wp-json/wc/v3/products

`
"code": "rest_no_route",
    "message": "No route was found matching the URL and request method",
    "data": {
        "status": 404
}
`

Your help is much appreciated.

**Comment by vedanshujain** [comment]
@mkchetan25 from your [routes endpoint](https://v2farmfresh.com/wp-json/) I don't see WC API endpoints listed. Can you please go to the status page (should be https://v2farmfresh.com/wp-admin/admin.php?page=wc-status) on your site and share the screenshot of `WordPress environment` section, I am mostly interested in the value of `WooCommerce REST API package:` row.

As a workaround, can you install [rest api plugin](https://github.com/woocommerce/woocommerce-rest-api/releases/tag/1.0.15) separately and see if it temporarily fixes your issue.

**Comment by mkchetan25** [comment]
@vedanshujain, glad to hear from you.

As mentioned, I attached the screenshot here:

![image](https://user-images.githubusercontent.com/31512936/92625052-d7318200-f2e5-11ea-8bb0-6e607f515300.png)

I can check by installing "rest api plugin" in my localhost and update you.

**Comment by mkchetan25** [comment]
Unfortunately, I'm unable to find woocommerce-rest-api plugin in the wordpress plugins. Any other help?

**Comment by vedanshujain** [comment]
@mkchetan25 its not listed on wordpress, follow this link to download and upload manually to install https://github.com/woocommerce/woocommerce-rest-api/releases/tag/1.0.15.

Also, your environment status page looks correct, and all the APIs are listed, just the WC core APIs are not for some reason. I am unable to reproduce this issue on my local setup. Can you paste your full status report from the status page by clicking on `Get System Report`? Maybe another extension is causing a conflict?

**Comment by mkchetan25** [comment]
Thank you, I'm checking with WooCommerce-Rest-API. In the meanwhile, please take a look on the status report:

`
`
### WordPress Environment ###

WordPress address (URL): 
Site address (URL): 
WC Version: 
REST API Version: ✔ 4.5.0
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.5.0
Log Directory Writable: ❌ To allow logging
make  writable or define a custom WC_LOG_DIR.

WP Version: ❌  - There is a newer version of WordPress available (5.5.1)
WP Multisite: –
WP Memory Limit: ❌  - We recommend setting memory to at least 64MB. See: Increasing memory allocated to PHP
WP Debug Mode: –
WP Cron: –
Language: 
External object cache: –

### Server Environment ###

Server Info: 
PHP Version: - ❌ WooCommerce will run under this version of PHP
however
some features such as geolocation are not compatible. Support for this version will be dropped in the next major release. We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version

PHP Post Max Size: 
PHP Time Limit: 
PHP Max Input Vars: 
cURL Version: 
SUHOSIN Installed: –
Max Upload Size: 
Default Timezone is UTC: ❌ Default timezone is  - it should be UTC
fsockopen/cURL: ❌ Your server does not have fsockopen or cURL enabled - PayPal IPN and other scripts which communicate with other servers will not work. Contact your hosting provider.
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ❌ Your server does not have the DOMDocument class enabled - HTML/Multipart emails
and also some extensions
will not work without DOMDocument.

GZip: ❌ Your server does not support the gzopen function - this is required to use the GeoIP database from MaxMind.
Multibyte String: ❌ Your server does not support the mbstring functions - this is required for better character encoding. Some fallbacks will be used instead for it.
Remote Post: ❌ wp_remote_post() failed. Contact your hosting provider.
Remote Get: ❌ wp_remote_get() failed. Contact your hosting provider.

### Database ###

WC Database Version: 
WC Database Prefix: 
Database information:: Unable to retrieve database information. Usually
this is not a problem
and it only means that your install is using a class that replaces the WordPress database class (e.g.
HyperDB) and WooCommerce is unable to get database information.


### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (0) ###


### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: ()
Currency Position: 
Thousand Separator: 
Decimal Separator: 
Number of Decimals: 
Taxonomies: Product Types: 
Taxonomies: Product Visibility: 
Connected to WooCommerce.com: –

### WC Pages ###


### Theme ###

Name: 
Version: 
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 259
Oldest: 2020-08-18 07:42:25 +0000
Newest: 2020-09-09 14:39:49 +0000

Pending: 1
Oldest: 2020-09-10 07:44:37 +0000
Newest: 2020-09-10 07:44:37 +0000
`
`

**Comment by mkchetan25** [comment]
I don't know how to explain, but the backup extracted from the production to my localhost does work well with the Rest API. I did not install "woocommer-rest-api" plugin, but still it works well. Problem persists only in the production environment.

Any suggestion on what to check with, would be appreciable.

**Comment by mkchetan25** [comment]
Well, I did restoring the backup from the production and then installing and activating the plugin woocommerce-rest-api. I found nothing interesting, but instead got stuck up with this:
* our installation of the WooCommerce REST API feature plugin is incomplete. Please run composer install within the C:\MAMP\htdocs\xxxx\wp-content\plugins\woocommerce-rest-api-1.0.15 directory.
* http://172.20.10.5/new-v2farmfresh/wp-json/wc/v3/products results with
`
"code": "rest_no_route",
    "message": "No route was found matching the URL and request method",
    "data": {
        "status": 404
}
`

Any help?

**Comment by abhishek-pokhriyal** [comment]
I can also confirm the issue with the incomplete WooCommerce REST API plugin.

I installed the plugin on a local WP installed (and activated) using WP-CLI `wp plugin install https://github.com/woocommerce/woocommerce-rest-api/archive/1.0.15.zip --activate` and I got the following notice on the WP Dashboard.

![image](https://user-images.githubusercontent.com/11808845/92731821-326d7e00-f393-11ea-8bcc-2a48b1d7d57a.png)

@vedanshujain Looks like the [release 1.0.15](https://github.com/woocommerce/woocommerce-rest-api/releases/tag/1.0.15) does not contain the composer dependencies.

PS: Running `composer install` fixes the issue.

**Comment by ChristiaanScheermeijer** [comment]
I seem to have the same problem after updating to WooCommerce 4.5.1 and 4.5.2. Only the `wc/v1` and `wc/store` API routes are exposed in the `/wp-json` response.

I have tried debugging the issue and I'm seeing that after this commit 16473d5, the `add_action('load_rest_api', ...)` function is being called after the `load_rest_api` action is being triggered.

What could cause the order to change on different installations?

**Comment by ChristiaanScheermeijer** [comment]
I think I have solved it for our installation. I had a custom plugin which also registered some rest routes in the `init` hook. This seems to cause a delay in the `init` sequence causing the WooCommerce `init` handler to fall behind. 

Using the same setup as the latest change (registering the routes in the `rest_api_init` hook) has solved the problem.

**Comment by rrennick** [comment]
> Recently, I updated woocommerce to the latest version and now I'm facing this error while accessing the REST API

@mkchetan25 Can you retest this with the latest version of WooCommerce to see whether the issue still occurs?

**Comment by vdwijngaert** [comment]
> > Recently, I updated woocommerce to the latest version and now I'm facing this error while accessing the REST API
> 
> @mkchetan25 Can you retest this with the latest version of WooCommerce to see whether the issue still occurs?

I just had a client experiencing a similar issue after updating to 5.8.0. A plugin's endpoint on the `wc-api` namespace suddenly resulted in a 404, flushing permalinks fixed the issue.

**Comment by peterfabian** [comment]
Until someone can reproduce this, we will have a hard time fixing it. Also, REST API is now included with WC, so it shouldn't depend on a plugin, so the original report is probably stale by now.
Closing until then. If you manage to reproduce, please feel free to comment here and we'll reopen (or create a new issue).

**Comment by nmarrot** [comment]
I'm actually facing the same problem.

**When i call :** 
https://par-toutatis.fr/wp-json/wc/v3/orders
**I receive :** 
[code] => rest_no_route [message] => No route was found matching the URL and request method. [data] => stdClass Object ( [status] => 404 )

But it works perfectly if i call : https://par-toutatis.fr/wp-json/wc/v3/orders/myId

Versions:
Wordpress: 6.0.1
WooCommerce: 6.3.1

![Capture d’écran 2022-08-17 à 17 13 57](https://user-images.githubusercontent.com/111446678/185178009-1cb51469-f469-48bf-9708-7aae8163c596.png)

**Edit : if i call the full url https://par-toutatis.fr/wp-json/wc/v3/orders?consumer_key=ck_XX&consumer_secret=cs_XX
it works.**

I would appreciate your help

**Comment by Alejo-504** [comment]
Me paso lo mismo en mi caso un plugin personalizado estaba registrando rutas en la api de wordpress en el hook "init" lo que generaba el problema al cambiarlo a "rest_api_init" se soluciono.

Cabe mencionar que en las ultimas versiones de woocommerce este mismo problema también causa que no carguen los métodos de pago en las configuraciones.  Woocommerce - settings - Payments.
