### ISSUE TITLE
Introduce GitHub workflow to run e2e tests on multiple hosts 

### ISSUE THREAD

**Issue by claudiosanches** [woocommerce/woocommerce#27646]
This is blocked by some changes required to allows us to run e2e tests on external hosts. One of the blockers: https://github.com/woocommerce/woocommerce/pull/27432

Tasks:

- [ ] A new branch to build e2e tests using https://github.com/woocommerce/action-build
- [ ] Workflow file

**Comment by rrennick** [comment]
@claudiosanches I pinged you on #27432 so you can review while working on this one.

**Comment by rrennick** [comment]
Closing this one as we are running tests on external sites.
