### ISSUE TITLE
No pagination for payment methods in the my-account > payment methods endpoint

### ISSUE THREAD

**Issue by rynaldos** [woocommerce/woocommerce#27663]
Hi!

We have received the following from a user and was able to replicate the same behaviour. 

> The issue started on the my account page where I noticed I was only seeing 1 payment method list in the payment methods endpoint. If you look at the account profile you'd see all of the payment methods from CIM.

> After looking through the code I realized that the list is controlled by the Wordpress main post entries for blog and whatnot.

<img width="649" alt="Screenshot 2020-09-13 at 18 23 38" src="https://user-images.githubusercontent.com/6198774/93023308-51b41780-f5ee-11ea-8f12-f935a756439d.png">

> The issue is that there is no pagination for the payment methods so if you have more than 1 you won't get a previous and next on the my account pages like you do with the orders section.

<img width="1129" alt="Screenshot 2020-09-13 at 18 23 46" src="https://user-images.githubusercontent.com/6198774/93023319-65f81480-f5ee-11ea-82f7-c88eb1859c7c.png">

**Expected behavior**

If there are multiple payment methods, but only a single one visible, then it might be confusing to the customer. I don't think customers realize that it can be controlled with the post number value in the Reading settings. It isn't obvious. It would be easier if there was some pagination involved here instead of displaying a single method only. 

**Actual behavior**

Only a single payment method is shown, even though the user has multiple save payment methods. No pagination. 

Steps to reproduce the bug:

1. Install Aauthorize.net extension
2. Set your WP > Settings > Reading to 1
3. Go to my-account page > payment methods endpoint
4. Add multiple payment methods. 
5. See error

**Screenshots**

See above.

I am not sure if this is the intended behaviour or not. 

Thanks!

**Comment by juliaamosova** [comment]
Hi @rynaldos,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/25025. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
