### ISSUE TITLE
get_review_count not updating properly

### ISSUE THREAD

**Issue by Oremaker** [woocommerce/woocommerce#27668]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ x ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
get_review_count not updating properly comments count

**Expected behavior**
When there are new comments i expect the review_count to reflect the number so i can use it in my templates

**Actual behavior**
Database query is giving the good number but get_review_count is giving a different number
Also not matching with get_rating_count

Database query is giving the real number so it is probably not called anytime.
 SELECT COUNT(*) FROM table_comments
			WHERE comment_parent = 0
			AND comment_post_ID = "ProductID"
			AND comment_approved = '1

This leads to many problems for the products, e.g:  
 - Wrong information for user
 - Product errors in Google Search Console as in some cases there is one review but reviewCount is still 0

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

1. Go to https://www.ceroresiduo.com/producto/bolsa-silicona-platino-pequena/
1. Also check https://www.ceroresiduo.com/producto/estuche-cepillo-de-dientes/
2. Check rating count and comment count

Basic code in template: $rating_count = $product->get_rating_count();

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
### WordPress Environment ###

WordPress address (URL): https://www.ceroresiduo.com
Site address (URL): https://www.ceroresiduo.com
WC Version: 4.5.1
REST API Version: ✔ 4.5.1
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.5.0
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 400 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Debian)
PHP Version: 7.3.14
PHP Post Max Size: 35 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.52.1
OpenSSL/1.0.2r

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.26-MariaDB-0+deb9u1
Max Upload Size: 35 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

**Comment by juliaamosova** [comment]
Hi @Oremaker,

Thanks for reporting the issue. However, it is still not clear what the issue exactly is and how to reproduce it. 

Can you please provide the exact clear step by step to replicate the issue locally?

**Comment by Oremaker** [comment]
Solved.
In case someone needs this information:

If you are updated to Wordpress v5.5 and afterwards update your woocommerce (in my case Woocommerce 3.7 to 4.5.1) many reviews in my database stayed as comment_type -> "comment" . When clearing transients for the product this comments are not counted as reviews so the rating count and the review count do not match because of the database comment_type difference.

Solved through updating the database comments related to a product to comment_type -> review, afterwards clearing transients match perfectly.

Query to check if you have any review with comment_type -> comment

SELECT wp_comments.* FROM wp_comments INNER JOIN wp_posts as p ON p.ID=comment_post_ID WHERE comment_parent = 0 AND p.post_type='product' AND comment_approved = '1' AND comment_post_ID is not null AND comment_type = 'comment'

**Comment by juliaamosova** [comment]
Thanks for your follow-up and for providing the solution @Oremaker.
