### ISSUE TITLE
Still not clear if this is possibile?

### ISSUE THREAD

**Issue by Nicotu** [woocommerce/woocommerce#27672]
It's part of v3 api (unreleased).

_Originally posted by @mikejolley in https://github.com/woocommerce/woocommerce/issues/11676#issuecomment-348953110_

**Comment by Nicotu** [comment]
I'm trying to use this feature with multiple parameters, but I still get an error from the api on V3. Is there any chance to confirm if this is possibile or not or if there's any workaround? What was actually the reasoning behind dropping this feature in the first place? Thank you!

**Comment by rrennick** [comment]
@Nicotu If you are looking for help using the REST API, I suggest joining the [WooCommerce Community Slack](https://woocommerce.com/community-slack/) and posting your question there. When you ask, you should provide the details of the request you are trying to get working.
