### ISSUE TITLE
ERROR 502 Bad Gateway - API request

### ISSUE THREAD

**Issue by mirco261** [woocommerce/woocommerce#27670]
Hi,
sometimes when I try to make api call, like download products:
GET `/wp-json/wc/v3/products?per_page=100&page=28`

I get error 502 bad gateway

sometimes GET 1-30 pages return all fine, but sometimes (2-3rd run) I've got 502 bad gateway error

Response Headers
```
HTTP/1.1 502 Bad Gateway
Server: nginx
Date: Mon, 14 Sep 2020 20:11:54 GMT
Content-Type: text/html
Content-Length: 89474
Connection: keep-alive
ETag: "5e786dfc-15d82"
Host-Header: 6b7412fb82ca5edfd0917e3957f05d89
X-Proxy-Cache: MISS
X-Proxy-Cache-Info: W NC:000000 UP:0
```
Woocommerce 4.5.2
Wordpress 5.5.1
PHP on server 7.4.8 (7.3.20 tested too and same result)

I've tried disable all plugins and templates and same result

**HERE IS TESTING TOOL** - just click to **TEST**
`https://apitester.com/`

check every step and look to **Response Headers** - sometimes you will find 502 bad gateway in 1st row and HTML code in **Response Body**

Do you have any idea?

**Comment by peterfabian** [comment]
Hi @mirco261 

I would suggest removing the API secrets from API tester tool, as it would allow anyone to get/edit orders, products, users etc from your store. I've edited your post to remove the sensitive detail, but please, also remove it from apitester.com.

**Comment by mirco261** [comment]
thank you... api was only for reading... but you have right...

**Comment by peterfabian** [comment]
I tried to replicate this locally, but couldn't. 

I ran Apache Benchmark, e.g. I ran 50 requests with 4 parallel requests at the same time:

`ab -c 4 -n 50 -v 3 "https://apitest.local/wp-json/wc/v3/products/?per_page=100&consumer_key=ck_cee92...&consumer_secret=cs_01c4a6..."`

But I only got HTTP 200 responses.

Also tried a simpler approach with curl that would simulate the API tester, but only got back HTTP 200 codes:
```
for i in {1..12}
do
    URL="https://apitest.local/wp-json/wc/v3/products/?consumer_key=ck_cee92...&consumer_secret=cs_01c4a67...&per_page=100&page=$i"
    echo "Hitting $URL"
    curl -isk $URL | cut -d '}' -f 1
    echo ""
done
```

However, I could see the bad gateway responses from your shop. Is there anything in the HTTP server or PHP logs that might be useful to debug this further?

**Comment by mirco261** [comment]
HI Peter,

thank you for your time, that you spend on this problem.

I've contact help center in my hosting. I use siteground hosting, and they said to me, that they dont see anything in PHP error log.

I don't think that 502 error is timeout problem, because duration of request takes same time, as request with HTTP 200 code.

But I have new clue. When I use Standard PHP settings, everything goes well, but on Ultrafast PHP I see errors.
`https://www.siteground.com/kb/ultrafast-php-vs-standard-php`

I asked there, what is difference between PHP options, and writed me:
`As per the Ultrafast PHP the difference is that the Standard PHP uses CGI and the Ultrafast PHP uses mod_php.`

Can this clue help solve my problem?
thank you

**Comment by peterfabian** [comment]
That's quite odd, because your response header suggests the HTTP server is nginx, while mod_php runs on Apache HTTP server as far as I know. 

I would suggest to get in touch with some technical folks from SiteGround and let them troubleshoot, as they have the best idea about what all the configuration differences are and can access all the logs they need to get to the bottom of it. Since it works fine with Standard PHP, I wouldn't say the WC code is at fault here.

Please keep us posted if you find out more. I might try to set up a testing site with Apache and mod_php to see if I can reproduce.

**Comment by negapo** [comment]
Hi, we have the same exact problem using the API and Siteground, we have plenty of resources (CPU running at 15% max and RAM at 25% max), we have tried everything to pint point the problem but we cant. Any insight on this would be wonderful, we are aware that this can be a siteground problem but any lights on the right direction would be great. thanks.

**Comment by mirco261** [comment]
I have ticket in SG with this problem and collaborate with them as much I can. 
They found some problem in their Memcached, but problem is still.

I will actual this thread if I I will know anything new.

**Comment by mirco261** [comment]
They tried some optimization and changes but nothing help at all...

Last message from them:

```
We have checked the case with our sysadmins who confirmed that the issue is caused by the shared server limits, either for Apache timeout or Nginx packet size. These limits directly affect the server performance and stability which is why they cannot be changed on the shared plans.

We can see that the limits are slightly exceeded, so if you do not want to upgrade, please consider reducing the number of requests.

The other option would be to upgrade to a cloud server where we can increase the limits per your custom needs.

If there is anything else we can help you with, please let us know.
```

so, I think is in SG and it is no chance to use REST API without ERROR 502 on shared plan... 

And if we can not simulate this problem on other platform... we are deadlocked...

**Comment by negapo** [comment]
We have a cloud plan with plenty of spare resources, CPU running at 15% max and RAM at 25% max at peak, and we still have problems, we thought at first the queries were very long and timing out, like fetching a lot of products or orders, but thats not the case, cant understand why the constant errors when using the API.

**Comment by mirco261** [comment]
so... It si problem not in WC plugin, but in hosting... 
I fetch about 15000products with 15000variants in about 60-65minutes... Standard PHP...

**Comment by crashbit666** [comment]
Hi!

I using Siteground cloud account and I test with Ultra Fast PHP, memcached and versions of PHP

With Ultra Fast PHP + memcached + php 7.4.8 ---> A lot of 502 errors
Ultra Fast PHP - memcached disabled + 7.4.8 ---> Some errors
Standard PHP + memcached + 7.4.8 ---> Some errors
Standard PHP - memcached dissabled + 7.4.8 ----> Some errors
Ultra Fast PHP + memcached + 7.3 PHP 7.3.20 ---> NO ERRORS

I don't know what is the problem, but at the moment I'm using latests config.

I don't see errors on apache error_log , but I can see strange logs on access_log. If I can find this logs I attach here

**Comment by crashbit666** [comment]
This is the log that the siteground access_log shows me:

192.88.135.17 www.mamabepo.com - [20/Sep/2020:12:57:11 +0000] "GET / HTTP/1.1" 200 14185 "https://www.mamabepo.com" "Mozilla/5.0+(compatible; UptimeRobot/2.0; http://www.uptimerobot.com/)" | TLSv1.2 | - - 0.000 HIT 0 NC:000000 UP:0

The 502 error comes out when it shows the 0 NC: 00000 UP: 0, which I have no idea what it is

**Comment by mirco261** [comment]
crashbit666 - you have absolutely right. Thank you for your post.

Option Ultra Fast PHP + memcached + 7.3 PHP 7.3.20 ---> WORKS WELL

hm... I dont know what to write to SG, to solve this problem on other variations (php + memcached)... 
But it is fine that is option to have ultrafast PHP + memcached enabled...

**Comment by rrennick** [comment]
> so... It si problem not in WC plugin, but in hosting...
> I fetch about 15000products with 15000variants in about 60-65minutes... Standard PHP...

@mirco261 Can you let us know whether this has been resolved with SiteGround?

**Comment by mirco261** [comment]
@rrennick Hi. I am still on this settings in siteground:
Ultra Fast PHP + memcached + PHP 7.4.24

I had conversation with support in Siteground about this problem, but this is last message from SG was:
We have checked the case with our sysadmins who confirmed that the issue is caused by the shared server limits, either for Apache timeout or Nginx packet size. These limits directly affect the server performance and stability which is why they cannot be changed on the shared plans.

**Comment by rrennick** [comment]
@mirco261 Thanks for the quick follow up. Essentially SG support is telling you that you will need to upgrade your hosting to increase your server limits to resolve the issue. The alternative that you could implement is add a small delay between api calls.

I'll leave this issue open for a bit for you if you have any additional questions.

**Comment by AaronZhenhaoZhong** [comment]
Same issue here in 2023
