### ISSUE TITLE
npm install fails on Catalina at `lerna bootstrap` 

### ISSUE THREAD

**Issue by andfinally** [woocommerce/woocommerce#27678]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I'm unable to build the Node packages on a fresh checkout of the plugin. I've tried with a different Node version, 10.16.3, and also using `npm ci`, and I've tried restarting my machine, but the build fails consistently.

**Expected behavior**
On running `npm install`, the npm installation process completes.

**Actual behavior**
The build spends 30-40 minutes on a `lerna` task, and eventually fails with 

```
lerna ERR! npm install stderr:
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Bootstrapping 3 packages
lerna info Installing external dependencies
lerna ERR! npm install exited 1 in '@woocommerce/e2e-environment'
```
[CLI output](https://github.com/woocommerce/woocommerce/files/5226257/npm.install.error.txt)
[npm debug log](https://github.com/woocommerce/woocommerce/files/5226265/2020-09-15T15_17_22_026Z-debug.log)

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. On a macOS Catalina 10.15.6 machine with Node 14.1.0 and npm 6.14.8, check out the master of this repo.
2. `cd` into the plugin directory and run `npm install`.
3. See error.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WooCommerce isn't built yet, so I can't get a status report.

**Comment by juliaamosova** [comment]
Hi @andfinally,

Thanks for reporting! We are aware of this issue and fixing it via https://github.com/woocommerce/woocommerce/pull/27667 - please see PR for more details of the issue.

**Comment by andfinally** [comment]
Ah brilliant, thanks for the ⚡️ response @juliaamosova!

**Comment by andfinally** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/27667, thank you! ❤️
