### ISSUE TITLE
Update templates to fix coding standards

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#27681]
We have 3 template files that don't conform to [coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#naming-conventions):
- wp-content/plugins/woocommerce/templates/content-product_cat.php
- wp-content/plugins/woocommerce/templates/taxonomy-product_cat.php
- wp-content/plugins/woocommerce/templates/taxonomy-product_tag.php

We should update them to fix the problem. 

It seems that for `taxonomy-*.php` templates, [our template loading](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-template-loader.php#L106) is modeled based on [WP core loading of template overrides](https://github.com/WordPress/WordPress/blob/master/wp-includes/template.php#L320)—it searches for file name based on taxonomy name and the taxonomy for the product category in WC is `product_cat`. This loading probably can be changed rather easily to start using the dash in the name and fall back to underscore (±plugins using filters to filter templates).

The situation is a bit different for `content-product_cat.php`, where we load it ourselves explicitly, but there are some filters and pluggable functions that plugins/themes can use to change its location, so I’m assuming it’s easier to break this inadvertently.

More context in pMz3w-bWp-p2.

**Comment by claudiosanches** [comment]
@peterfabian not sure about this one, since this change will be against: https://developer.wordpress.org/themes/template-files-section/taxonomy-templates/#custom-taxonomy

Currently we use `taxonomy-{taxonomy}.php`, for taxonomies like `product_cat` and `product_tag`. 
By default you need to match the taxonomy slug.

**Comment by peterfabian** [comment]
That's a good point, thanks @claudiosanches . Myabe term/slug should be considered a word, and then our files do conform to the coding standard saying hyphens connect words.... 🤔

**Comment by rrennick** [comment]
> not sure about this one, since this change will go against

In the linked PR, template naming support is

- `themename/content-product_cat.php`
- `themename/woocommerce/content-product-cat.php`
- `themename/woocommerce/content-product_cat.php`

The 3 templates are renamed to `-` in the `/templates/` folder and the instructions in the doc block are to copy the template to `themename/woocommerce/`. Template files in the `/woocommerce/` folder are in addition to the standard template hierarchy so the PR maintains the WP standards support. Any existing template files will continue to work with the existing names.
