### ISSUE TITLE
Create api title issue

### ISSUE THREAD

**Issue by pradeepgadiya** [woocommerce/woocommerce#27692]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
i want to create a product through API and using in title  & sign like shoes & sandals .
title proper showing all product listing but once i open this product i was showing title in decode form like this shoes &amp; sandals.
I want my title like this shoes & sandals.

can you please suggest me how can i use & symbol in api?
Thanks

**Comment by claudiosanches** [comment]
Hello @pradeepgadiya.

For security reasons WooCommerce escape HTML, but note that WordPress also does it by default in case an user without `unfiltered_html` capability tries to create the same product using on the WP administrative interface.
Also those characters get rendered correctly on the front-end or in any HTML view.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.
