### ISSUE TITLE
City field cannot be hidden for Puerto Rico. Credit Cards will not validate. 

### ISSUE THREAD

**Issue by soussartdirection** [woocommerce/woocommerce#27711]
AS in issue #26643 https://github.com/woocommerce/woocommerce/issues/26643

In this thread they say that they hid the "City" field and replaced with "municipality". This has broken credit card verification for Puertp Rico clients. You should just leave as is and eliminate municipality field and just leave city field. Puerto Rico uses US Postal Service so "Municipalities" are considered cities. 

If you hide city field and put new "municipality" field there is no way Credit Cards can validate .

My Puerto Rico clients cannot validate their credit cards because of this. and get this error  "Transaction Failed. 300-The city field is required "

Please make "municipality" field just a regular "city" field again. 

Thanks

**Comment by phillipcornwell** [comment]
Have another user with a similar issue: 3349828-zen

**Comment by tammullen** [comment]
Thanks @soussartdirection for reporting this and sorry for the delay in responding.

As you have noted this was changed in https://github.com/woocommerce/woocommerce/pull/26698

I am marking this as bug for now as your report does sound like it is a bug.

We’re going to solve this bug as soon as possible. Stay tuned for updates.

**Comment by luboslives** [comment]
+1 this issue leads to a PayPal error - "The field Shipping Address **City** is required".

I've tried manually adding a City to the client's account in the WP admin, but that does not help and the value gets erased again when the client attempts a purchase. If Municipality and City are interchangeable, maybe you can force a copy of the value before sending it off to PayPal etc.
