### ISSUE TITLE
Woocommerce hooks & variables for external products?

### ISSUE THREAD

**Issue by dirkthewebphoenix** [woocommerce/woocommerce#27717]
What hooks & variables does Woocommerce have for external products? (the search field here doesn't work on my end, btw)

To vary the procedures via building an add_filter plugin or so, the hooks & variables must be known. What are they for external products?

(or where can one find such detailed specific info?)

Thanks for any helpful tips.

**Comment by juliaamosova** [comment]
Hi @dirkthewebphoenix,

We have WooCommerce Code Reference available below:

https://woocommerce.github.io/code-reference/index.html

I believe this is what you are looking for:

https://woocommerce.github.io/code-reference/classes/WC-Product-External.html

I am closing this issue but please feel free to comment back in case I missed something and we'd take another look.
