### ISSUE TITLE
Grouped product not hidden

### ISSUE THREAD

**Issue by PriitGit** [woocommerce/woocommerce#27710]
Hi!
Grouped product not hidden in product catalog page. In settings > invetory > Out of stock visibility is checked, but still shows grouped product in catalog. All sub products or related products in this grouped product is “out of stock”, but still shows that product in archive page? Are that bug or I missing something?

All Best,
Defix

**Comment by grigorijurasov** [comment]
Also reported here: https://wordpress.org/support/topic/grouped-product-not-hidden-in-product-catalog/

I'm able to replicate on my test site with two latest WooCommerce versions.

Steps to replicate:


1. Create one simple and one variable product (same happens with just two simple products too). Set the product and the variations to out of stock.
2. Create a grouped product, assign it to a product category.
3. Link the two products to the grouped product.
4. Navigate to the category page. The grouped product is still there, even though all components are out of stock.

**Comment by PriitGit** [comment]
Hi!

Is there any information or a temporary solution to this problem?

All Best,
Defix

**Comment by juliaamosova** [comment]
Hi @PriitGit,

Apologies for the delayed response. 

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end using WooCommerce 4.6.1:

http://g.recordit.co/HOC5wxjW2O.gif

We’re going to work on solving this bug as soon as possible.

**Comment by roykho** [comment]
Hi @PriitGit - what do you think about (for now) just hiding the "add to cart" button on the grouped product's page so at least people won't click the button just to get a message they can't add it to the cart?

After looking into this, it appears it may require quite a bit of effort to tackle this so will the interim solution work for you?

**Comment by PriitGit** [comment]
Thanks @roykho !
As a temporary solution, you can try it, but how to do it?

**Comment by roykho** [comment]
@PriitGit - so we'll get this patched up and get it out in a later version release.

**Comment by PriitGit** [comment]
@roykho - Thank you for the information and please keep us up to date.

**Comment by roykho** [comment]
Ok I've just put in a PR to hide the `add to cart` button when all linked products are out of stock per discussion. I will be closing this for now until we get more votes on this to fix the original issue of hiding the grouped product itself when all linked products are out of stock.

Thanks again for reporting @PriitGit
