### ISSUE TITLE
External/Affiliate Links adding extra character “?” to the URL

### ISSUE THREAD

**Issue by pssyss** [woocommerce/woocommerce#27727]
**Prerequisites (mark completed items with an [x]):**
- [x ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Hello,

The affiliate link is
https://domain.com/#a_aid=sid
However the button link leads to
https://domain.com/?#a_aid=sid

Tried to trouble shoot for 5 hours yesterday. It doesn’t seem to be an issue with our theme (Divi) or any of the plugins, tried disabling those.
Found similar issues of illegal chracters in external/affiliate links but no resolution found yet.

Anyone?

Thank you!

https://wordpress.org/support/topic/external-affiliate-links-adding-extra-character-to-the-url/#post-13431737

**Expected behavior**
The affiliate link is
https://domain.com/#a_aid=sid

**Actual behavior**
However the button link leads to
https://domain.com/?#a_aid=sid

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WooCommerce version: 4.3.2
WordPress version: 5.5
PHP version: 7.3.16
MySQL version: 5.6.40-84.0-log

**Comment by rynaldos** [comment]
Hey team! 

I am able to replicate the same behavior using WooCommerce core v4.5.0, however, not on an earlier version such as v4.2.0. 

Using https://woocommerce.com/products/ as the affiliate product link (example), it outputs the following URL in the most recent core release:

https://woocommerce.com/products/?

When in an earlier version, it outputs as https://woocommerce.com/products/

The strange thing is, however, after a couple of tried with v.4.2.0, the same started happening and it also appended the ? character. 

Cheers!

**Comment by pssyss** [comment]
Hello friends, 

Hope someone can help me fix this issue.

Thank you!

**Comment by jonathansadowski** [comment]
Hi @pssyss,

Thanks for reporting this issue. The change in how external links are handled is related to a recent change in the way that browsers handle form submissions. One of the browsers that I sometimes used for testing was on a past version that didn't have this issue, and once I updated it to the latest, I was able to recreate the issue.

Unfortunately, we're not able to change the behavior of form submissions within the browser, and it's the browser that is adding the `?` character.

**Comment by pssyss** [comment]
The logic to close this issue does not make sense to me.

**Comment by jorgepa77** [comment]
> Hi @pssyss,
> 
> Thanks for reporting this issue. The change in how external links are handled is related to a recent change in the way that browsers handle form submissions. One of the browsers that I sometimes used for testing was on a past version that didn't have this issue, and once I updated it to the latest, I was able to recreate the issue.
> 
> Unfortunately, we're not able to change the behavior of form submissions within the browser, and it's the browser that is adding the `?` character.

Then I think the solution should be to use a link tag instead of a form to address External/Affiliate links.
