### ISSUE TITLE
WC_REST_Authentication class methods not fired on requests

### ISSUE THREAD

**Issue by bynicolas** [woocommerce/woocommerce#27726]
Ok, I'll try to keep it short and simple since it might only be me missing a setting somewhere.

But I cannot authenticate using the generated `consumer key/secret` from the `WC > advanced > REST API` tab

- It's not a server issue or a missing header. That has been checked.
- If I try using my WordPress user/password (using https://github.com/WP-API/Basic-Auth plugin), I can authenticated against the REST API, but that is not what I expect. I wish to use the generated REST API credentials.
- So I went on and try to log some debug output directly from the `authenticate()` method in the **WC_REST_Authentication** class. Nothing was logging in the `debug.log` file. Witch I found weird.
- So I went and created my own `authenticate()` and `perform_basic_authentication()` functions in a custom plugin to see if I could authenticate with the `consumer` credentials. Copy/Pasting the methods from the class (with only required tweaks to make it work outside of class). I tried that assuming the `determine_current_user` filter was not being called.
**That worked!**

So either this is a bug and the `determine_current_user` filter is not being called (witch I can't find anyone complaining about, so I doubt it's the case) or I am missing a setting somewhere or I am using the feature wrong.

If it's not a bug, what am I doing wrong?

**Comment by om4james** [comment]
Hi @bynicolas, would it be possible for you you to see if the changes proposed in #27587 fix your issue?

**Comment by rrennick** [comment]
Changing the label to `needs feedback` due to inactivity.
