### ISSUE TITLE
4.5.2: unexpected WC REST API v1 usage: `WC_Abstract_Legacy_Order::get_product_from_item is deprecated since version 4.4.0! Use $item->get_product() instead.`

### ISSUE THREAD

**Issue by lkraav** [woocommerce/woocommerce#27729]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
### Describe the bug
For some reason, WooCommerce Subscriptions webhook payload goes to `woocommerce/includes/rest-api/Controllers/Version1/class-wc-rest-orders-v1-controller.php`

I actually can't figure out who's to blame, maybe y'all can help figure it out.

See this stacktrace https://sentry.io/share/issue/6795315567c1421a95c62166475054f3/

Why would we jump from WC REST API v3 -> v1 near the top?

```
User Deprecated: WC_Abstract_Legacy_Order::get_product_from_item is <strong>deprecated</strong> since version 4.4.0! Use $item->get_product() instead.
    /wp-content/plugins/woocommerce/includes/wc-deprecated-functions.php in wc_deprecated_function at line 54
/wp-content/plugins/woocommerce/includes/legacy/abstract-wc-legacy-order.php in WC_Abstract_Legacy_Order::get_product_from_item at line 320
… lugins/woocommerce/includes/rest-api/Controllers/Version1/class-wc-rest-orders-v1-controller.php in WC_REST_Orders_V1_Controller::prepare_item_for_response at line 176
… nt/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-posts-controller.php in WC_REST_Posts_Controller::get_item at line 156
/wp-content/plugins/woocommerce-subscriptions/includes/class-wcs-webhooks.php in WCS_Webhooks::create_payload at line 147
...
```

**Expected behavior**
Should V3 API be used all the way, or?

**WordPress Environment**
WP 5.5.1 and a ton of plugins.

But I think stack trace shows clearly there is no other code involved between the weird jump from WC REST API v3 -> v1.

Something `$this` suddenly goes to WC REST API v1 :thinking:

**Comment by lkraav** [comment]
@chickenn00dle has graciously pointed out, `WC_REST_Subscriptions_Controller` extends `WC_REST_Orders_V1_Controller`. Somehow I didn't know to look for that vector.

Regardless, core shouldn't be shipping deprecated method calls in any of its internal implementations, even if legacy APIs, correct?

So https://github.com/woocommerce/woocommerce/blob/f5e130c190c73050070ee43e653ff07707e88ef3/includes/rest-api/Controllers/Version1/class-wc-rest-orders-v1-controller.php#L176 should still be refactored?

**Comment by rrennick** [comment]
> Regardless, core shouldn't be shipping deprecated method calls in any of its internal implementations, even if legacy APIs, correct?

@lkraav Thanks for the research. Yes this should be fixed. The problem line is https://github.com/woocommerce/woocommerce/blob/master/includes/rest-api/Controllers/Version1/class-wc-rest-orders-v1-controller.php#L176

**Comment by lkraav** [comment]
I find it curious how this slipped a grep scan when deprecating the method in question. Is there perhaps a process deficiency to look into?

**Comment by rrennick** [comment]
> I find it curious how this slipped a grep scan when deprecating the method in question.

Fair point. At the time it was done, the REST API was still being maintained in a separate repository and being added to WC in the `/packages/` folder. A scan of the `/includes/` folder didn't scan the REST API.  In this codebase it's in `/includes/rest-api/`.

**Comment by lkraav** [comment]
Is there a way to get this into 4.6.0 RC-s? Seems like a trivial update?

Same for https://github.com/woocommerce/woocommerce/issues/27828 which I'm also seeing.
