### ISSUE TITLE
Pass data to checkout_place_order_success to allow for some logic when order is created

### ISSUE THREAD

**Issue by vaclavgreif** [woocommerce/woocommerce#27722]
I need to do some conditional logic when the order is created, before the redirect to gateway happens. For that I'd need to have the data available.

Pull request here: https://github.com/woocommerce/woocommerce/pull/27721

**Comment by rrennick** [comment]
Closing as addressed per https://github.com/woocommerce/woocommerce/pull/27721#issuecomment-1155107515
