### ISSUE TITLE
Math class add div+mod

### ISSUE THREAD

**Issue by cpiber** [woocommerce/woocommerce#27730]
Please add div and mod capabilities to the math class. I can also do a PR.

Example situation: Want to have staggered shipping costs with a base price plus some additional fee per ex. 20 items. For this I would need `div`/`\` to integer divide. `mod`/`%` could be used similarly.

**Comment by rrennick** [comment]
@cpiber Can you provide more detail on what you are referring to?

**Comment by cpiber** [comment]
Can you please elaborate? I don't know what more detail to add

**Comment by rrennick** [comment]
> I don't know what more detail to add

Example:

> Please add div and mod capabilities to the math class.

Which math class?

Your description looks like you are asking us to add PHP language, jQuery, or libraries.

**Comment by cpiber** [comment]
@rrennick ?

**Comment by rrennick** [comment]
> I can also do a PR.

@cpiber That's likely your best option. This wouldn't be a high priority for us to do the development.
