### ISSUE TITLE
Support to add headers on webhooks

### ISSUE THREAD

**Issue by rafa-acioly** [woocommerce/woocommerce#27742]
**Is your feature request related to a problem? Please describe.**
Currently there's no way to add extra headers on the webhook, which demand to write fome sort of function (filter) to add this extra headers to the webhooks, it would be nice if the webhooks have the inputs by default.

**Describe the solution you'd like**
When adding/editing a `webhook`  we could have extra inputs to add a new header key/value using the webhook form page.

here's a example from magento2:

![68747470733a2f2f692e696d6775722e636f6d2f537552703965412e706e67](https://user-images.githubusercontent.com/11068059/93835060-6b8bd500-fc54-11ea-92ae-3b6557eb1435.png)

**Describe alternatives you've considered**
There's a filter called `woocommerce_webhook_http_args` to add the custom headers.

**Additional context**
When we create a webhook most of the time is to comunicate with a REST API that used token based authentication, the majority of it uses `Authorization` header key but currently there's no easy way to add them to the webhook request.

**Comment by rrennick** [comment]
@rafa-acioly We appreciate the suggestion but this is the type of feature that we leave for the developer community. This isn't something we would look at adding to core.

The webhook edit screen/save contains hooks to allow adding fields & saving the entered values:

- https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-webhooks.php#L128
- https://github.com/woocommerce/woocommerce/blob/master/includes/admin/class-wc-admin-webhooks.php#L128

The headers are filterable through https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-webhook.php#L334
