### ISSUE TITLE
Broken REST API after upgrading to 4.5.2.  

### ISSUE THREAD

**Issue by omanuela** [woocommerce/woocommerce#27752]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Rest calls work fine in WooCommerce 4.4.1.  They stopped working on 4.5.2.  (however, from other REST issues posted here, it looks like it may have stopped working on 4.5.0, but I just did not notice until now)

**Expected behavior**
I'm expected to get actual WooCommerce data (in this case product info) instead of "rest_no_route" error code.

**Actual behavior**
Calling the following "/wp-json/wc/v3/products/1234" returns "{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}" 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
1. In WooCommerce 4.4.1, run the following CURL request from the command line:  `curl -k https://{website}/wp-json/wc/v3/products/{postId} -u {ck....}:{cs....}`.    
The response is the product info, as it should be, e.g. `{"id":1234,"name":"abcd", etc.}`
2. Make backup of WooCommerce plugin directory.
3. Upgrade only WooCommerce to latest version (4.5.2).  Run the exact same command as above from the command line: `curl -k https://{website}/wp-json/wc/v3/products/{postId} -u {ck....}:{cs....}`.    
The response is  `{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}`
3. Restore the backup made in step 2 to downgrade to WooCommerce 4.4.1.  The same CURL request as in step 1 and 3 returns the expected result, just like in step 1.

So, the only difference between having it work and not having it work is the version number of WooCommerce.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Additional info**
WordPress version used:  5.5.1
Disabling all plugins and leaving only WooCommerce active still returns the same "rest_no_route" error message.
Switching to a default theme (Twenty Twenty) still returns the same error message.

I looked at the issue described on https://github.com/woocommerce/woocommerce/issues/27631, which seems to be somewhat similar and tried installing https://github.com/woocommerce/woocommerce-rest-api/releases/tag/1.0.15 (temporary workaround), but then the exact curl command above returns a different error:   `{"code":"woocommerce_rest_cannot_view","message":"Sorry, you cannot view this resource.","data":{"status":401}}`

So, this does not work in my case either.  For now the only thing that works is to remain on version 4,4,1.

**Comment by aresrioja10** [comment]
Same bug here. Have you found some solution?

**Comment by omanuela** [comment]
> 
> 
> Same bug here. Have you found some solution?

Hi, yes, I found the solution that worked for me.  

There was a custom plugin that was registering custom REST endpoints the old way (using the "init" action).  Changing this so that these are registered using the "rest_api_init" action instead solved the issue.

**Comment by aresrioja10** [comment]
> > Same bug here. Have you found some solution?
> 
> Hi, yes, I found the solution that worked for me.
> 
> There was a custom plugin that was registering custom REST endpoints the old way (using the "init" action). Changing this so that these are registered using the "rest_api_init" action instead solved the issue.

It works! Thank you so much!

**Comment by jonathansadowski** [comment]
Hi @omanuela and @aresrioja10. I just wanted to confirm that both of you are no longer having issues after dealing with the other plugin that was registering the endpoints outside of the `rest_api_init` hook, is that correct?

I'm going to close this issue for now, because it sounds like that resolved things for you, but please feel free to add a comment if you're still having issues. Also, if there's a plugin in the directory that was causing this issue, please let us know so that we can reach out to its author.
