### ISSUE TITLE
REST API: taxes endpoint does not return multiple postcodes/cities

### ISSUE THREAD

**Issue by mahmoudsaeed** [woocommerce/woocommerce#27750]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
The `wc/v3/taxes` endpoint only returns the last postcode/city for a tax rate, ignoring multiple postcodes and/or cities.

**Expected behavior**
If a rate has multiple postcodes and/or cities (semi-colon separated values), the endpoint response should include an array of postcodes/cities.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Add a tax rate with multiple postcodes (e.g. `32789; 33255`) and/or cities (e.g. `MIAMI; ORLANDO`)
2. Make a GET request to `wc/v3/taxes`
3. The response would be something like the following:
```
{
        "id": 5,
        "country": "US",
        "state": "FL",
        "postcode": "33255",
        "city": "ORLANDO",
        "rate": "6.0000",
        "name": "US FL",
        "priority": 10,
        "compound": true,
        "shipping": true,
        "order": 4,
        "class": "standard"
}
```

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mahmoudsaeed** [comment]
@rodrigoprimo @peterfabian Any update on this? I have already created a [PR](https://github.com/woocommerce/woocommerce/pull/27751) that resolves the issue.

**Comment by peterfabian** [comment]
Thanks for your contribution @mahmoudsaeed  and apologies for the delay in the review. I've requested a review for the PR from @Konamiman .
