### ISSUE TITLE
WC 4.6 Beta 1: Not being redirected to the onboarding after activating the plugin

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce#27755]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
After installing the plugin in a new site I'm not being redirected to the WooCommerce onboarding after activating the plugin.

**Expected behavior**
Being redirected to the onboarding after activating the plugin

**Actual behavior**
I stay in the Installed plugins page instead of going to the onboarding

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create a new WP site
2. Install the WooCommerce 4.6 beta.1 version and click activate
3. Confirm that you're not redirected to the onboarding

**Screenshots**
https://www.loom.com/share/fe56edeb8daa4522a167caed47bd7656

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by pmcpinto** [comment]
cc @rodrigoprimo @juliaamosova

**Comment by juliaamosova** [comment]
Thanks for reporting @pmcpinto!

**Comment by rrennick** [comment]
This will probably be addressed in WC Admin. @joshuatf could you confirm?

**Comment by rodrigoprimo** [comment]
Related WooCommerce Admin issue https://github.com/woocommerce/woocommerce-admin/issues/5193
