### ISSUE TITLE
API Authentication Fails over http

### ISSUE THREAD

**Issue by Piepongwong** [woocommerce/woocommerce#27768]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
I'm using docker swarm locally for development with Docker Desktop for Windows. 

Wordpres image: wordpress:5-php7.2
Mysql image:  mysql:5.7

I tried to authenticate via http://fainey.com/wp-json/wc/v3/products with parameters and basic auth flow, but I got.

```
{
    "code": "woocommerce_rest_cannot_view",
    "message": "Sorry, you cannot list resources.",
    "data": {
        "status": 401
    }
}
```

First I tried switchin version, like is suggested here https://github.com/woocommerce/woocommerce/issues/27752 .

That didn't work. **What did work** was adding ssl via traefik. However it's not specified in the documentation that ssl is required. Is this by design and is the documentation incomplete or is it a bug?

**Comment by SWengineer-A** [comment]
Same issues here.

**Comment by itallogravina** [comment]
I am also having the same problem, I installed the wp in the docker and when making a local OAuth 1 request I can't get this error

**Comment by aresrioja10** [comment]
Same problem here. Have you found any solution? I can't upgrade Woocommerce :(

**Comment by itallogravina** [comment]
I made a connection with the postman, just to generate the specific token. So just use the token for everything, I used this as a reference https://code.tutsplus.com/tutorials/wp-rest-api-setting-up-and-using-oauth-10a-authentication--cms-24797

**Comment by jonathansadowski** [comment]
Hi @Piepongwong, @SWengineer-A, and @aresrioja10,

This is working as intended. Basic auth is only supported over HTTPS. Basic auth isn't supported over HTTP because it would potentially enable an attacker to intercept your credentials. You can use the API over HTTP by authenticating your request using OAuth authentication, as documented [here](https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-http).
