### ISSUE TITLE
Add more details to E2E README on what happens when user runs `nvm use` command

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#27764]
Add more details to E2E README on what happens when user runs `nvm use` command. See https://github.com/woocommerce/woocommerce/pull/27714#discussion_r491653904 for more context.

**Comment by lanej0** [comment]
Looking at the related comment, it appears that this task relates to the old (Puppeteer-based) e2e tests, which have been replaced by Playwright.  Closing this.
