### ISSUE TITLE
Ensure compatibility with Twenty Twentyone

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#27766]
A new theme, 2021 is coming to WordPress in December. 

WIP Repo: https://github.com/WordPress/twentytwentyone
Blog post: https://make.wordpress.org/core/2020/09/23/introducing-twenty-twenty-one/

Similarly to [PHP8 support](https://github.com/woocommerce/woocommerce/issues/27674), we need to be ready by December 8th (planned date for WP 5.6)

cc @rodrigoprimo

**Comment by jeffikus** [comment]
I've been contributing to Twenty Twenty One dev and I've added the base structure for the theme support in my fork. Will talk to the core team about what they want to do about adding styles and submit a PR.

**Comment by jonathansadowski** [comment]
Draft PR based on @jeffikus' work: https://github.com/woocommerce/woocommerce/pull/28134

**Comment by peterfabian** [comment]
Night mode support coming to 2021: https://make.wordpress.org/core/2020/10/22/twenty-twenty-one-dark-mode-discussion/

Not sure if we need to do anything about it?

**Comment by tammullen** [comment]
Noting here this observation from @AashikP of the message `"This theme does not support WooCommerce" `in the OBW
Is there anything we can do within WC or does it need an update in the theme itself?

![wc-support](https://user-images.githubusercontent.com/24649833/100634993-ded25700-3327-11eb-8c38-93ecd5757be3.png)

**Comment by jonathansadowski** [comment]
> Noting here this observation from @AashikP of the message `"This theme does not support WooCommerce" `in the OBW
> Is there anything we can do within WC or does it need an update in the theme itself?

Thanks for passing along @tammullen, and for the original report @AashikP. I wasn't able to reproduce this. Is it possible that the testing was done before we merged #28134? This would also happen if the theme were installed directly via the instructions in the Github repo, as the name of the theme would be `twentytwentyone-trunk` in that case, and the [method we use to check the theme](https://github.com/woocommerce/woocommerce/blob/686872a2372a71ed35b90a8ff790b046d0b40118/includes/wc-core-functions.php#L2331-L2352) doesn't account for that. If the theme directory is renamed from `twentytwentyone-trunk` to `twentytwentyone` before going through the OBW, this issue shouldn't show up.

![image](https://user-images.githubusercontent.com/363749/100797878-6ed7d580-33e8-11eb-8a98-4fc19efa50fb.png)

**Comment by AashikP** [comment]
Thank you, @jonathansadowski 

I'll test this again and update here. The theme is installed as `twentytwentyone`.

I used this command `wp theme install https://github.com/WordPress/twentytwentyone/archive/trunk.zip --force`

![https://d.pr/i/g5gs5d+](https://d.pr/i/g5gs5d+)

**Comment by ObliviousHarmony** [comment]
Some remaining defects: 

- **Checkout**: Stripe saved payment method selection checkboxes are squished.
- **Product & Catalog Pages**: The `sale` badge should likely have a color based off the CSS vars.
- **Everywhere**: There are many notices that are white boxes with a green bar at the top and green buttons, regardless of theme colors. Examples include empty order & download list `my-account` pages, as well as empty carts.

**Comment by peterfabian** [comment]
Closing, as the majority of items are fixed/done. Remaining enhancements logged separately as https://github.com/woocommerce/woocommerce/issues/28789. Thank you all!
