### ISSUE TITLE
woocommerce_meta_nonce is used twice on the product edit screen

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce#27775]
I Found this when working with E2E tests.

`woocommerce_meta_nonce` is the nonce used on the edit screens. It's also added to the product images metabox
 https://github.com/woocommerce/woocommerce/blob/master/includes/admin/meta-boxes/class-wc-meta-box-product-images.php#L32. This creates a duplicate ID. The product images nonce should be changed to a unique name or removed.

**Comment by kampiamodikuesto** [comment]
same problem in woocommerce/includes/admin/meta-boxes/views/html-product-data-variations.php for element with id "current-page-selector-1". This is present in two html element.

**Comment by gateway** [comment]
Has this been fixed, I also just ran into this with the latest build, wanted to make sure it wasn't something new I was seeing.

**Comment by rrennick** [comment]
@gateway Issues are closed when the pull request that addresses them have been merged. An open issue is the indicator that the issue has not been fixed.

**Comment by rrennick** [comment]
Closing this as the nonce no longer present in the product edit page.
