### ISSUE TITLE
[GlobalStep - WooCommerce 4.6 Beta1] On Checkout page, "State" dropdown fails to list "Armed Forces" in alphabetical order.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#27774]
## Bug Description:
On Checkout page, "State" dropdown fails to list "Armed Forces" in alphabetical order.
 
## Environment:
 Windows 10, Mac Mojave:10.14.6 (18G103)
 Browser: Chrome(Version 85.0.4183.83 (64-bit))
  Firefox(Version 80.0.1)(64-bit)
  Safari(Version 13.1.1)
 
## Steps To Reproduce:
 1. Create a Jurassic Ninja test site
 1. Install and Activate WooCommerce, Query Monitor and WooCommerce Beta Tester Plugin.
 1. Create a product from Products page by clicking on "Add New" button
 1. Go to WooCommerce->Status->tools and click on "Create Pages" button for "Create default WooCommerce Pages" option
 1. Click on "Visit Site" option that appears after hovering mouse on home icon at top left corner
 1. On Front-end, Add the created product to the cart by clicking on "Add to Cart" button.
 1. On Front-end, Click on "View Cart" button.
 1. Click on "Proceed to Checkout" button
 1. Observe that on "Checkout" page, "Armed Forces" states fails to be arranged in alphabetic order under "State" dropdown
  
## Actual Result:
On Checkout page, "State" dropdown fails to list "Armed Forces" in alphabetical order.
 
## Expected Result:
 On Checkout page, "State" dropdown should list "Armed Forces" in alphabetical order.
 
 ## Artifacts:
[#27774.zip](https://github.com/woocommerce/woocommerce/files/5277463/27774.zip)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment]
Hi @gglobalstep 

Thanks for raising this

CLDR doesn't consider them as states (https://github.com/unicode-org/cldr/blob/6adc82b6b6116bb67e046ec129adb66f4aa6aac4/common/subdivisions/en.xml#L5324) however we have listed them with the states as some services consider them as such for processing payments etc (https://github.com/woocommerce/woocommerce/issues/1605). 

I'm marking this as `won't fix` because I think having them listed after the CLDR list of states makes sense.
