### ISSUE TITLE
Add notice to Reports page to use Analytics instead

### ISSUE THREAD

**Issue by GeoJunkie** [woocommerce/woocommerce#27789]
**Is your feature request related to a problem? Please describe.**
Since [WooCommerce Reports are becoming obsolete](https://docs.woocommerce.com/document/reports/), site owners should be using the new [WooCommerce Analytics instead](https://docs.woocommerce.com/document/woocommerce-analytics/). Many site owners are unaware of the new Analytics section, or don't realize that it is the more accurate source of truth for reports.

**Describe the solution you'd like**
Add a notice to **WooCommerce > Reports** informing shop owners to check out Analytics and encouraging using them instead.

**Describe alternatives you've considered**
The [WooCommerce Reports documentation](https://docs.woocommerce.com/document/reports/) has a notice about this.

![](https://d.pr/i/zLwL8t+)
Image Link: https://d.pr/i/zLwL8t

However, this may not be noticed by site owners who have used these reports for a while. A site notice would raise visibility of the new, enhanced Analytics.

**Additional context**

This has come up in a few forum posts and support requests. A couple examples: 
https://wordpress.org/support/topic/reports-are-wrong/
https://wordpress.org/support/topic/discrepancies-between-wc-admin-and-woo-reports/

24118658-hc

**Comment by juliaamosova** [comment]
Hi @GeoJunkie,

Apologies for the delayed response here. 

Thanks for raising this issue - I think this is a great idea. I am going to assign 4.8 milestone here for now but also pinging to see what @pmcpinto and @timmyc think about this?

**Comment by timmyc** [comment]
I think this is a great idea. On implementation, we might want to sniff out and see if the site has WooCommerce Admin disabled via the `woocommerce_admin_disabled` [filter](https://github.com/woocommerce/woocommerce-admin/blob/main/src/FeaturePlugin.php#L67). If they do have it disabled, then I think we shouldn't show this notification - or perhaps show a different notification and ask them why they have it disabled :)

**Comment by pmcpinto** [comment]
Great idea. I'm just wondering if we should add a notice to the Reports section and/or add an inbox notification. cc @elizaan36 for feedback on this

**Comment by elizaan36** [comment]
I'd lean towards a notice in the Reports section since it should be more in the category of a warning message.

**Comment by pmcpinto** [comment]
> I'd lean towards a notice in the Reports section since it should be more in the category of a warning message.

Sounds good 👍 @elizaan36 do you have any suggestions for the notice content?

**Comment by elizaan36** [comment]
something like,
> Please note: This legacy **Reports** area will be deprecated and removed on [Date]. You can start using the new and better **[Analytics](url)** section, available now. [Learn more](url)

With a link to the new Analytics documentation.

**Comment by peterfabian** [comment]
The idea is great! However, we don't really explicitly plan to remove the reports at any specific time (especially since some of the extensions are using them), so I think the notice might need some re-wording. I'll try to get some work done to be able to get a more specific message.
