### ISSUE TITLE
Remove old setup wizard component from e2e utils

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#27786]
Remove [old setup wizard component](https://github.com/woocommerce/woocommerce/blob/master/tests/e2e/utils/src/components.js#L219-L356) from e2e utils since the old set up wizard had been fully removed from WooCommerce.

**Comment by dennisgon** [comment]
hi can i try to work in this issue?

**Comment by juliaamosova** [comment]
@dennisgon sure!

**Comment by dennisgon** [comment]
hi @juliaamosova I already make PR according to the issue, you can check it on #27852 
is this correct?
