### ISSUE TITLE
API keys automatically generated from PUT request from Zapier Webhooks

### ISSUE THREAD

**Issue by Xpressprint** [woocommerce/woocommerce#27783]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

### Using Zapier Webooks to edit the line item meta data of an existing order is causing multiple duplicate API keys being generated automatically.

**The PUT request goes through fine, and the order is updated correctly, but every time it fires is a new key generated (and used). Then the old keys are being revoked by the system because of limit per user.**

Contacted Zapier support, reporting no issues on their end. Contacted WC support, sent me here.

Screenshots explaining the issue:
<img width="1364" alt="WC-ZAP_1" src="https://user-images.githubusercontent.com/26872809/94263344-32de4b00-ff35-11ea-94d6-174087e44165.png">
<img width="1364" alt="WC-ZAP_2" src="https://user-images.githubusercontent.com/26872809/94263358-3671d200-ff35-11ea-993e-404f563bda06.png">
<img width="1366" alt="WC-ZAP_3" src="https://user-images.githubusercontent.com/26872809/94263362-38d42c00-ff35-11ea-942b-e604c2306923.png">
<img width="1363" alt="WC-ZAP_4" src="https://user-images.githubusercontent.com/26872809/94263368-3a9def80-ff35-11ea-98ef-69bd6313dd75.png">

Hook code from Zapier step:
<img width="822" alt="Screenshot of PUT request in Zapier" src="https://user-images.githubusercontent.com/26872809/94263904-17277480-ff36-11ea-9e8e-267ea36cbd79.png">

Why are new keys generated instead of using key added to Zapier Webhooks auth field?

**Comment by Xpressprint** [comment]
**Correction:** The keys are not automatically created _each time_ the Zapier action fires. It can happen several times a day, or not happen for 3-4 days. I have not found a pattern looking at the orders or actions in Zapier.

Where is the functionality of automatically creating API keys coming from, and what purpose is it supposed to serve?

**Comment by Xpressprint** [comment]
How long does it usually take to get a response on something like this? It is still a problem for us, I have to manually check and delete new API-keys ever day.

**Comment by om4james** [comment]
Hi @Xpressprint ,

We (OM4 Software) are the developers of the [WooCommerce Zapier extension](https://woocommerce.com/products/woocommerce-zapier/).

Looking at your screenshots, it looks like you may also be using WooCommerce Zapier on your site, as step 1 in your Zap appears to be showing the purple WooCommerce logo?

WooCommerce Zapier's authentication mechanism periodically creates new REST API keys in your WooCommerce store, as they are used by the WooCommerce Zapier integration when your WooCommerce Zaps run on zapier.com.

WooCommerce Zapier also then periodically cleans up (revokes) Zapier REST API keys if they aren't used for several days also.

I hope this helps solve the mystery for you.

If you need further assistance, please [reach out to us directly by submitting a support ticket](https://om4.io/woocommerce-zapier-documentation/support/).

James
OM4 Software

**Comment by Xpressprint** [comment]
Hi James, and thanks for that information.

 I just had one set of keys for "Zapier" used for your plugin and the native webhook step, so then splitting the two should solve my issue.


Thanks!
— Andreas


PS: Please consider adding support in your plugin to edit line item meta data of an order, so I don't have to add these webhook steps ;-)

**Comment by om4james** [comment]
> PS: Please consider adding support in your plugin to edit line item meta data of an order, so I don't have to add these webhook steps ;-)

Unfortunately, the Zapier platform/UI doesn't currently let us create the separate meta data input fields inside the line items list/array, because it is nested too deeply in terms of structure.

However, we add new features to the extension based on customer demand. If you were to add your idea to the WooCommerce Extension Ideas Forum, others can vote on your idea (and you might also vote on other ideas). We review popular suggestions as part of our development process.

http://ideas.woocommerce.com/forums/133476-woocommerce?category_id=178441

**Comment by SchwannK** [comment]
Hey James @om4james , I hope you're well!

I came across this thread yesterday, and saw your mention that "WooCommerce Zapier also then periodically cleans up (revokes) Zapier REST API keys if they aren't used for several days also."

I realised that my custom Webhook Zaps have been requiring re-authentication every week or so, needing me to manually recreate API keys on WooCommerce, and suspect that this might be the reason.

Would you be able to provide more information on how WooCommerce Zapier actually does the API key cleaning? Does it search for API keys with the name "Zapier" in them? I've always labeled mine with a name containing "Zapier" hence this might be the case, so will create a set omitting this keyword to try.

Thanks!
Schwann

**Comment by om4james** [comment]
Hi @SchwannK , please [reach out to us directly here](https://om4.io/woocommerce-zapier-documentation/support/) so we can assist you in detail. Thanks!

**Comment by ChrisColotti** [comment]
I just came across this old thread but I am not seeing the old keys get cleaned up after several days...in some cases there are over 100 of them from the WC Zapier integration as much as a month old..

**Comment by the-csaba** [comment]
Hi @ChrisColotti 

One hundred keys is undoubtedly high. Our plugin deletes keys when not used for more than 30 days. It checks it every day. Multiple connections or many Zap edits may cause that high number.

Please [reach out to us directly here](https://om4.io/woocommerce-zapier-documentation/support/) so we can assist you in detail. Thanks!

**Comment by the-csaba** [comment]
Hi @claudiosanches  or @tammullen , can you limit the conversation on this issue? Thanks

**Comment by ChrisColotti** [comment]
@om4csaba sent :)
