### ISSUE TITLE
Add filter for single-product-reviews form

### ISSUE THREAD

**Issue by hedqvist** [woocommerce/woocommerce#27782]
**Is your feature request related to a problem? Please describe.**
We are collecting product reviews and would like to remove the form from product pages to only display the current reviews

**Describe the solution you'd like**
A filter to hide the review submission form

**Describe alternatives you've considered**
Allowing developers to filter this seems like a good idea

**Additional context**
Has Pull Request #27781

**Comment by pmcpinto** [comment]
Thank you for taking the time to share this idea. We appreciate your help.

I'll close this issue, as it looks like the PR (#27781) doesn't show any activity since last August. Please feel free to re-open it, if you don't mind.
