### ISSUE TITLE
Integrate `@automattic/puppeteer-utils` fully so that its page utilities could be used

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#27787]
Integrate `@automattic/puppeteer-utils` fully so that its page utilities such as `await waitAndClick( this.page, titleSelector );` could be used in WooCommerce Core e2e tests:

https://github.com/Automattic/puppeteer-utils#page-utilities

**Comment by rrennick** [comment]
@juliaamosova I created #27790 which adds the following to `e2e-environment`

```
	clickAndWaitForNewPage,
	getAccountCredentials,
	isEventuallyPresent,
	isEventuallyVisible,
	logDebugLog,
	logHTML,
	waitAndClick,
	waitAndType,
	waitForSelector,
	scrollIntoView,
	Page
```

When you switch to that branch run `npm install` before attempting to use the additions.
