### ISSUE TITLE
WooCommerce interferes in get_the_post_thumbnail_url()

### ISSUE THREAD

**Issue by artneo7** [woocommerce/woocommerce#27797]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
It seems WooCommerce is interfering in `get_the_post_thumbnail_url( $id, $size )`. When targeting ids from products the size is always full. Could only solve this by setting 'Appearance > Customize > WooCommerce > Product Images > Uncropped' and resizing image thumbnails.

**Expected behavior**
The function `get_the_post_thumbnail_url( $id, $size )` should return the correct image size URL.

**Actual behavior**
The function `get_the_post_thumbnail_url( $id, $size )` returns the original image size.

**Steps to reproduce the bug**
1. `add_image_size( 'test', 520, 520, ['center', 'center'] )` and upload a bigger image;
2. Use the function `get_the_post_thumbnail_url( $id, 'test' )` to display it in the custom theme;
3. Interact (add to cart or change variations selection) with the single page product (seems to trigger the image size URL reset to 'full');
4. Go to 'Appearance > Customize > WooCommerce > Product Images > change 1:1 to Uncropped';
5. Use a plugin to resize image thumbnails, and test again. Should fix the issue.

This took me a while to solve and it seem legit. As I didn't find any related issue I thought I could have found a bug and it could save someone else time.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
> 2. Use the function get_the_post_thumbnail_url( $id, 'test' ) to display it in the custom theme;
> 3. Interact (add to cart or change variations selection) with the single page product (seems to trigger the image size URL reset to 'full');

@artneo7 I wasn't able to reproduce this with WooCommerce 5.8.0 and Storefront. I created a new post and set an image as the featured image. I saw the expected result both before and after Step 3

```
<img width="520" height="520" src="https://ron.localhost/wp-content/uploads/2021/10/IMG_20190712_092912-520x520.jpg" class="attachment-test size-test wp-post-image" alt="" loading="lazy" srcset="https://ron.localhost/wp-content/uploads/2021/10/IMG_20190712_092912-520x520.jpg 520w, https://ron.localhost/wp-content/uploads/2021/10/IMG_20190712_092912-scaled-324x324.jpg 324w, https://ron.localhost/wp-content/uploads/2021/10/IMG_20190712_092912-scaled-100x100.jpg 100w, https://ron.localhost/wp-content/uploads/2021/10/IMG_20190712_092912-150x150.jpg 150w" sizes="(max-width: 520px) 100vw, 520px" />
```

[ ]  This bug happens with a default WordPress theme active, or Storefront.

This may have been caused by the theme you had active. Could you re-test this with WooCommerce 5.8.0 and a default theme or Storefront. If you still see the issue, could you provide more details on the steps to reproduce the issue?
