### ISSUE TITLE
Stock not change “on-hold” orders in WooCommerce 4.5.2

### ISSUE THREAD

**Issue by asanka-sanmark** [woocommerce/woocommerce#27799]
When on-hold and add new items to existing order, new items stock not reduce in WooCommerce new version 4.5.2… Old versions work it perfectly.

**I tested this problem with below few steps [x]):**
- [ ] switch my theme to Storefront and checked
- [ ] Disable all plugins without WooCommerce and checked

But problem is same not resolved. old woocommerce versions has no problem.
Is there a bug of woocommerce?

Please help.

Thanks.

### My Woocommerce status report ###

WordPress address (URL): https://grade1.lk
Site address (URL): https://grade1.lk
WC Version: 4.5.2
REST API Version: ✔ 4.5.2
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.5.0
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.18.0
PHP Version: 7.4.3
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 
SUHOSIN Installed: –
MySQL Version: 5.7.31-0ubuntu0.18.04.1
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.5.2
WC Database Prefix: wp8z_
Total Database Size: 301.91MB
Database Data Size: 254.40MB
Database Index Size: 47.51MB
wp8z_woocommerce_sessions: Data: 120.66MB + Index: 0.97MB + Engine MyISAM
wp8z_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp8z_woocommerce_order_items: Data: 2.51MB + Index: 1.19MB + Engine MyISAM
wp8z_woocommerce_order_itemmeta: Data: 33.73MB + Index: 12.63MB + Engine MyISAM
wp8z_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_actionscheduler_actions: Data: 3.95MB + Index: 1.05MB + Engine MyISAM
wp8z_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp8z_actionscheduler_logs: Data: 2.14MB + Index: 1.60MB + Engine MyISAM
wp8z_atum_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_atum_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_atum_product_data: Data: 0.04MB + Index: 0.05MB + Engine MyISAM
wp8z_aws_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_aws_index: Data: 10.24MB + Index: 0.00MB + Engine MyISAM
wp8z_commentmeta: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
wp8z_comments: Data: 8.41MB + Index: 3.17MB + Engine MyISAM
wp8z_ewwwio_images: Data: 4.26MB + Index: 2.10MB + Engine MyISAM
wp8z_ewwwio_queue: Data: 0.17MB + Index: 0.12MB + Engine MyISAM
wp8z_failed_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_hustle_entries: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_hustle_entries_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_hustle_modules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_hustle_modules_meta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp8z_hustle_tracking: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_mailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_mailchimp_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_mailpoet_custom_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp8z_mailpoet_dynamic_segment_filters: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp8z_mailpoet_feature_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp8z_mailpoet_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp8z_mailpoet_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp8z_mailpoet_mapping_to_external_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp8z_mailpoet_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp8z_mailpoet_newsletter_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp8z_mailpoet_newsletter_option: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp8z_mailpoet_newsletter_option_fields: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp8z_mailpoet_newsletter_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp8z_mailpoet_newsletter_segment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp8z_mailpoet_newsletter_templates: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp8z_mailpoet_scheduled_tasks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp8z_mailpoet_scheduled_task_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp8z_mailpoet_segments: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp8z_mailpoet_sending_queues: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp8z_mailpoet_settings: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp8z_mailpoet_statistics_clicks: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp8z_mailpoet_statistics_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp8z_mailpoet_statistics_newsletters: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp8z_mailpoet_statistics_opens: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp8z_mailpoet_statistics_unsubscribes: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp8z_mailpoet_statistics_woocommerce_purchases: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp8z_mailpoet_stats_notifications: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp8z_mailpoet_subscribers: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp8z_mailpoet_subscriber_custom_field: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp8z_mailpoet_subscriber_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp8z_mailpoet_subscriber_segment: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp8z_mailpoet_user_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp8z_ms_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_options: Data: 4.15MB + Index: 0.42MB + Engine MyISAM
wp8z_phone_orders_log: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp8z_postmeta: Data: 42.98MB + Index: 16.70MB + Engine MyISAM
wp8z_posts: Data: 7.25MB + Index: 1.17MB + Engine MyISAM
wp8z_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_revslider_css: Data: 0.09MB + Index: 0.00MB + Engine MyISAM
wp8z_revslider_css_bkp: Data: 0.09MB + Index: 0.00MB + Engine MyISAM
wp8z_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_revslider_layer_animations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_revslider_navigations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_revslider_sliders: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp8z_revslider_sliders_bkp: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp8z_revslider_slides: Data: 0.21MB + Index: 0.00MB + Engine MyISAM
wp8z_revslider_slides_bkp: Data: 0.19MB + Index: 0.00MB + Engine MyISAM
wp8z_revslider_static_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_revslider_static_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_sched_columns: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_sched_events: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_sched_filters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_sched_meta_fields: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_sched_schedules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_smush_dir_images: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_stock_log: Data: 0.13MB + Index: 0.07MB + Engine MyISAM
wp8z_termmeta: Data: 0.06MB + Index: 0.07MB + Engine MyISAM
wp8z_terms: Data: 0.05MB + Index: 0.06MB + Engine MyISAM
wp8z_term_relationships: Data: 0.42MB + Index: 0.89MB + Engine MyISAM
wp8z_term_taxonomy: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wp8z_tm_taskmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_tm_tasks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_usermeta: Data: 1.16MB + Index: 0.63MB + Engine MyISAM
wp8z_users: Data: 0.05MB + Index: 0.05MB + Engine MyISAM
wp8z_wcpdf_invoice_number: Data: 0.10MB + Index: 0.06MB + Engine MyISAM
wp8z_wc_admin_notes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_wc_category_lookup: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
wp8z_wc_customer_lookup: Data: 0.20MB + Index: 0.14MB + Engine MyISAM
wp8z_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
wp8z_wc_order_product_lookup: Data: 1.83MB + Index: 1.48MB + Engine MyISAM
wp8z_wc_order_stats: Data: 0.25MB + Index: 0.17MB + Engine MyISAM
wp8z_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_wc_product_meta_lookup: Data: 0.11MB + Index: 0.14MB + Engine MyISAM
wp8z_wc_reserved_stock: Data: 0.08MB + Index: 0.07MB + Engine MyISAM
wp8z_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp8z_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp8z_yoast_indexable: Data: 5.07MB + Index: 1.10MB + Engine MyISAM
wp8z_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.08MB + Engine MyISAM
wp8z_yoast_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp8z_yoast_primary_term: Data: 0.06MB + Index: 0.07MB + Engine MyISAM
wp8z_yoast_seo_links: Data: 0.27MB + Index: 0.12MB + Engine MyISAM
wp8z_yoast_seo_meta: Data: 0.10MB + Index: 0.11MB + Engine MyISAM

### Post Type Counts ###

attachment: 3471
customize_changeset: 1
custom_css: 1
mailpoet_page: 1
nav_menu_item: 47
oembed_cache: 27
page: 35
post: 231
product: 1440
product_variation: 82
revision: 983
shop_coupon: 6
shop_order: 5489
shop_order_refund: 3
wc_order_status: 19
woo_discount: 2
woo_discount_cart: 1
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

Advanced Woo Search: by ILLID – 2.11 – Installed version not tested with active version of WooCommerce 4.5.2
Akismet Anti-Spam: by Automattic – 4.1.6
Classic Editor: by WordPress Contributors – 1.6
EWWW Image Optimizer: by Exactly WWW – 5.7.1
Flexible Shipping: by WP Desk – 3.14.0 – Installed version not tested with active version of WooCommerce 4.5.2
GA Google Analytics: by Jeff Starr – 20200815
Insert Headers and Footers: by WPBeginner – 1.4.6
WPBakery Page Builder: by Michael M - WPBakery.com – 6.2.0
Meta Box: by MetaBox.io – 5.3.4
WooCommerce PayHere Payment Gateway: by PayHere (Private) Limited – 1.0.9 – Installed version not tested with active version of WooCommerce 4.5.2
Phone Orders for WooCommerce (Pro): by AlgolPlus – 3.5.0 – Installed version not tested with active version of WooCommerce 4.5.2
Pre School Shortcodes: by SoftWebMedia – 2.32
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.5.7.3
W3 Total Cache: by BoldGrid – 0.15.0
Woo Add Custom States: by Trusted Technology Solutions (TrusTech) – 1.8.3
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.4.3 – Installed version not tested with active version of WooCommerce 4.5.2
ShareIt! Social Buttons: by DefThemes – 1.8.7
WooCommerce Order Status Manager: by SkyVerge – 1.12.0 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.6.1 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce - List Products by Tag: by Asanka Jagoda – 2.2.5 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce: by Automattic – 4.5.2
Yoast SEO: by Team Yoast – 15.0

### Inactive Plugins (11) ###

Contact Form 7: by Takayuki Miyoshi – 5.2.2
Facebook for WooCommerce: by Facebook – 2.0.2 – Installed version not tested with active version of WooCommerce 4.5.2
Hotjar: by Hotjar – 1.0.8
Hustle: by WPMU DEV – 7.3.1
Mailchimp for WooCommerce: by Mailchimp – 2.4.7 – Installed version not tested with active version of WooCommerce 4.5.2
Recent Tweets Widget: by Noah Kagan – 1.6.8
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.3
Responsive Timetable For Wordpress: by Rik de Vos – 1.16.0
Slider Revolution: by ThemePunch – 6.1.0
WooCommerce Side Cart: by XootiX – 2.1 – Installed version not tested with active version of WooCommerce 4.5.2
WP Rollback: by Impress.org – 1.7.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: LKR (Rs )
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: simple (simple)
grouped (grouped)
variable (variable)
external (external)
woosb (woosb)

Taxonomies: Product Visibility: exclude-from-search (exclude-from-search)
exclude-from-catalog (exclude-from-catalog)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #1522 - /shop/
Cart: #1523 - /cart/
Checkout: #1524 - /checkout/
My account: #1525 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: KidsWorld Child Theme
Version: 2.50
Author URL: http://themeforest.net/user/Softwebmedia
Child Theme: ✔
Parent Theme Name: Kids World
Parent Theme Version: 2.6.2
Parent Theme Author URL: http://themeforest.net/user/Softwebmedia
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: kids-world/woocommerce/content-product.php
kids-world/woocommerce/content-widget-product.php
kids-world/woocommerce/loop/loop-start.php
kids-world/woocommerce/single-product/product-image.php
kids-world/woocommerce/single-product/product-thumbnails.php

### Action Scheduler ###

Complete: 4,046
Oldest: 2020-08-18 04:33:58 +0000
Newest: 2020-09-18 04:16:25 +0000

Pending: 321
Oldest: 2020-09-18 04:59:44 +0000
Newest: 2020-09-29 09:30:01 +0000

Failed: 4
Oldest: –
Newest: –

`

**Comment by Hbitvof** [comment]
Same problem here. Can this be fixed as soon as possible? This gives alot of stock problems.

**Comment by tammullen** [comment]
Hi @asanka-sanmark  and @Hbitvof 

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/27445. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
