### ISSUE TITLE
Failed login attempts return 200 instead of 403

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/woocommerce#27802]
I am not sure if this is something we would be able to do easily or not, but I was talking to a WP Engine support tech and they passed this on to me: 

> The WooCommerce plugin seems to be overriding the default WordPress login functionality, specifically in the file wp-content/plugins/woocommerce/includes/class-wc-form-handler.php. This override allows direct submission of login credentials to the site rather than through the default wp-login.php form. Based on the log entries, there doesn't appear to be a way for us to block or limit these requests as WordPress returns a 200 HTTP response code regardless of success or failure. A possible solution would be to add a hidden captcha to these login/password reset forms or configure them to return a 403 HTTP response code on repeated failed submission attempts so that our security system is able to block them.

Would it be possible in the [`process_login()` method](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-form-handler.php#L899-L955) to modify the response code to 403 instead of 200 if the login has failed?

**Comment by rrennick** [comment]
> Would it be possible in the process_login() method to modify the response code to 403 instead of 200 if the login has failed?

@jessepearson 403s are handled by the web server not WP. So, if we returned a 403 on a failed login the user would get the server 403 page vs a WP login form with a failed login message (which is why WP returns 200 on a failed login). There are filters/hooks available to implement 403s on a site if the site owner chooses to. 

Here's a sample of the access log from one of my sites where hackers are running password guessing scripts:

```
 "POST /wp-login.php HTTP/1.1" 200 2185 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
 "POST /wp-login.php HTTP/1.1" 200 2158 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
 "POST /wp-login.php HTTP/1.1" 200 2157 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
 "POST /wp-login.php HTTP/1.1" 200 2185 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
"POST /wp-login.php HTTP/1.1" 200 2158 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
"POST /wp-login.php HTTP/1.1" 200 2157 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
 "POST /wp-login.php HTTP/1.1" 200 2185 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
 "POST /wp-login.php HTTP/1.1" 200 2158 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
 "POST /wp-login.php HTTP/1.1" 200 2157 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
 "POST /wp-login.php HTTP/1.1" 200 2185 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0"
```

Note the `200` status code.

**Comment by jessepearson** [comment]
Okay, thanks for the follow up, I will pass this along.
