### ISSUE TITLE
MISSING CITY FIELD FOR PUERTO RICO / URGENT-Losing all sales to Puerto RIco

### ISSUE THREAD

**Issue by soussartdirection** [woocommerce/woocommerce#27843]
The bug is simple. At some point the City field was substituted by Municiplaity field when Puerto RIco is chosen as a country at checkout. 

This has hidden the City field. Now all credit card transactions to Puerto Rico clients are broken because of missing city field. 

I get the following error. 

"Transaction Failed. 300-The city field is required"

**I am sure this is happening to all WOOCOMMERCE clients that sell to Puerto RIco.**

**Please bring back city field.** 

Thanks

PLEASE FIX THIS!!

**Comment by tammullen** [comment]
Hi @soussartdirection 

Thank you for reporting the issue. We are closing your issue in favor of the previously submitted https://github.com/woocommerce/woocommerce/issues/27711. Apologies for not responding sooner to it. 

 Please continue sharing your feedback there if needed.
