### ISSUE TITLE
Add a time delay buffer on last_updated docker image tag

### ISSUE THREAD

**Issue by rodrigoprimo** [woocommerce/woocommerce#27846]
**Describe the bug**

@claudiosanches and I got the following error yesterday when running `npm run docker:up` to prepare the environment for the e2e tests:

```
7.4.11: Pulling from library/php
ERROR: no matching manifest for linux/amd64 in the manifest list entries
```

We manage to work around this problem by replacing the variable `${DC_PHP_VERSION}` with `7.4.9` in `tests/e2e/env/docker-compose.yaml`. It is not clear to us why docker was trying to use `7.4.11` instead of `7.4.9` as defined [here](https://github.com/woocommerce/woocommerce/blob/2e7f1056e076ae4ebfd30817b41b5497100c3f95/tests/e2e/env/bin/docker-compose.sh#L22). 

We believe that we got the error above because we were running `npm run docker:up` the same day that `7.4.11` was released so there was not an image for it in Docker Hub yet.

Maybe we need to make sure we are always using a version that exists in Docker Hub to avoid this error?

cc @rrennick @ObliviousHarmony

**Comment by ObliviousHarmony** [comment]
It is currently using [this script](https://github.com/woocommerce/woocommerce/blob/2e7f1056e076ae4ebfd30817b41b5497100c3f95/tests/e2e/env/bin/get-latest-docker-tag.js) to pull the latest version from Docker Hub. It's possible you tried in a strange moment where the images weren't fully ready. Since this API response we're using already returns all of the architectures we could consider it invalid if the `amd64` is not available? [You can see the API response with this URL.](https://hub.docker.com/v2/repositories/library/php/tags)

**Comment by rrennick** [comment]
> We manage to work around this problem

@rodrigoprimo @claudiosanches You can use [environment variables](https://github.com/woocommerce/woocommerce/tree/master/tests/e2e#how-to-run-tests-using-custom-wordpress-php-and-mariadb-versions) to use specific library versions.

> 7.4.11: Pulling from library/php

We probably should just add this to the documentation as I don't think there is any way we can completely avoid it happening on people's desktop.

**Comment by rodrigoprimo** [comment]
> It's possible you tried in a strange moment where the images weren't fully ready.

I believe that is what happened.

> We probably should just add this to the documentation as I don't think there is any way we can completely avoid it happening on people's desktop.

:+1:

**Comment by rrennick** [comment]
I updated the issue title to reflect that we should be able to add some logic to skip tags that are less that X hours old. I will use WP 5.6 to determine how many hours we might need.

**Comment by rrennick** [comment]
At ~5 hours the WP 5.6 image was not available. It was available at ~10 hours. 12 should be a good number to start with.
