### ISSUE TITLE
4.5.2 changing WooCommerce / WordPress api prefix results in http 401 "woocommerce_rest_cannot_view"

### ISSUE THREAD

**Issue by Thomas-1985** [woocommerce/woocommerce#27854]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
WordPres: 5.5.1
WooCommerce: 4.5.2 (can also confirm in 4.2.2)
Theme: Storefront 2.7.0 (can also confirm in 2.5.7)

When i change the WordPress api prefix to some custom value, i cannot use the wc api anymore.
-I use the following code to change the prefix functions.php):

function change_rest_url_prefix( ) {
  return 'backend-api';
}

-After that, i login to the wp backend and regenerate the permalinks (settings -> permalinks).
-Every time i try to query the wc api (using Postman) i get
{
    "code": "woocommerce_rest_cannot_view",
    "message": "Entschuldigung, es können keine Ressourcen aufgelistet werden.",
    "data": {
        "status": 401
    }
}

-If i remove the custom prefix and regenerate the thumbnails, api access works again

**Expected behavior**
API access should work with the custom api prefix.

**Actual behavior**
It misbehaves like described in the bug report above.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
See above, this can be reproduced.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by rrennick** [comment]
Hi @Thomas-1985 ,  

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. I tested with the following steps

- Added this snippet to a plugin
```
add_filter( 'rest_url_prefix', function( $url ) {
	return 'wc-json';
});
```
- Visited Settings -> Permalinks
- Made a request to `https://ron.localhost/wc-json/wc/v3/products/18705/variations/18706`

<img width="1196" alt="Screen Shot 2021-10-19 at 10 32 44 AM" src="https://user-images.githubusercontent.com/343847/137920308-b4ad95c5-7a3e-4bec-b62e-eefabec3e2df.png">

Please provide us with more details about the issue which may help us to evaluate it further.
