### ISSUE TITLE
woocommerce delivered order status

### ISSUE THREAD

**Issue by G1enn1** [woocommerce/woocommerce#27865]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
There is a new option as an order status Delivered
When you chois this option the order disapears 
**Expected behavior**
no cleu?
**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to '...' a random order
2. Click on '....' change status -> delivered -> search for the order

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by ivatautomattic** [comment]
Hello @G1enn1 ,

Thank you for submitting the issue. To further investigate the issue we would need to evaluate the system report. Also, if you could add screenshots this would help a lot. Please provide us with the information requested so we could take a look further.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

**Comment by G1enn1** [comment]
![image](https://user-images.githubusercontent.com/72390901/95167369-d3dbca00-07af-11eb-83a6-367f84bacd30.png)
![image](https://user-images.githubusercontent.com/72390901/95167456-fd94f100-07af-11eb-929d-c5d851e13b9c.png)

When an order gets the status delivered there is no way to find it back. It is still exesisting you can find it in db

**Comment by G1enn1** [comment]
`
### WordPress Environment ###

WordPress address (URL): https://www.stralendgroen.nl
Site address (URL): https://www.stralendgroen.nl
WC Version: 4.5.2
REST API Version: ✔ 4.5.2
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.5.0
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache/2
PHP Version: 7.2.31
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1c

SUHOSIN Installed: –
MySQL Version: 10.4.14-MariaDB
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.5.2
WC Database Prefix: 1I6j3_
Totale databasegrootte: 702.02MB
Database datagrootte: 571.51MB
Database index grootte: 130.51MB
1I6j3_woocommerce_sessions: Data: 18.02MB + Index: 0.02MB + Engine InnoDB
1I6j3_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1I6j3_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1I6j3_woocommerce_downloadable_product_permissions: Data: 1.52MB + Index: 6.78MB + Engine InnoDB
1I6j3_woocommerce_order_items: Data: 4.52MB + Index: 3.03MB + Engine InnoDB
1I6j3_woocommerce_order_itemmeta: Data: 409.66MB + Index: 59.66MB + Engine InnoDB
1I6j3_woocommerce_tax_rates: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
1I6j3_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
1I6j3_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1I6j3_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1I6j3_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
1I6j3_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1I6j3_actionscheduler_actions: Data: 1.02MB + Index: 0.48MB + Engine InnoDB
1I6j3_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1I6j3_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1I6j3_actionscheduler_logs: Data: 0.52MB + Index: 0.44MB + Engine InnoDB
1I6j3_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1I6j3_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1I6j3_atum_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1I6j3_atum_product_data: Data: 0.17MB + Index: 0.08MB + Engine InnoDB
1I6j3_commentmeta: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
1I6j3_comments: Data: 7.85MB + Index: 2.84MB + Engine MyISAM
1I6j3_cp_calculated_fields_form_discount_codes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_cp_calculated_fields_form_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_cp_calculated_fields_form_revision: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
1I6j3_cp_calculated_fields_form_settings: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
1I6j3_feedmanager_channel: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1I6j3_feedmanager_country: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1I6j3_feedmanager_feed_status: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
1I6j3_feedmanager_field_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_feedmanager_product_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1I6j3_feedmanager_product_feedmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1I6j3_feedmanager_source: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
1I6j3_fmepco_poptions_table: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_fmepco_rowoption_table: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_fmepco_temp_table: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_imagify_files: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
1I6j3_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1I6j3_kiyoh: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
1I6j3_mollie_pending_payment: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_nextend2_image_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1I6j3_nextend2_section_storage: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1I6j3_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_nextend2_smartslider3_sliders: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
1I6j3_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_nextend2_smartslider3_slides: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
1I6j3_nm_personalized: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_options: Data: 6.41MB + Index: 0.31MB + Engine InnoDB
1I6j3_postmeta: Data: 69.59MB + Index: 37.13MB + Engine InnoDB
1I6j3_posts: Data: 7.94MB + Index: 0.89MB + Engine MyISAM
1I6j3_silvasoft_woo_log: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
1I6j3_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1I6j3_social_users: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1I6j3_stock_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_swift_performance_image_optimizer: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1I6j3_termmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
1I6j3_terms: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
1I6j3_term_relationships: Data: 0.07MB + Index: 0.16MB + Engine MyISAM
1I6j3_term_taxonomy: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
1I6j3_usermeta: Data: 12.70MB + Index: 2.35MB + Engine MyISAM
1I6j3_users: Data: 0.20MB + Index: 0.24MB + Engine MyISAM
1I6j3_user_registration_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1I6j3_wcpdf_credit_note_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_wcpdf_invoice_number: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
1I6j3_wcpdf_packing_slip_number: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
1I6j3_wcpdf_proforma_number: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
1I6j3_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1I6j3_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_wc_customer_lookup: Data: 0.28MB + Index: 0.23MB + Engine InnoDB
1I6j3_wc_download_log: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
1I6j3_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1I6j3_wc_order_product_lookup: Data: 3.52MB + Index: 9.56MB + Engine InnoDB
1I6j3_wc_order_stats: Data: 0.36MB + Index: 1.23MB + Engine InnoDB
1I6j3_wc_order_tax_lookup: Data: 0.25MB + Index: 0.20MB + Engine InnoDB
1I6j3_wc_product_meta_lookup: Data: 0.14MB + Index: 0.20MB + Engine InnoDB
1I6j3_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1I6j3_wc_webhooks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1I6j3_wdp_orders: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
1I6j3_wdp_order_items: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
1I6j3_wdp_rules: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1I6j3_wfblockediplog: Data: 0.16MB + Index: 0.00MB + Engine InnoDB
1I6j3_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
1I6j3_wfconfig: Data: 2.27MB + Index: 0.00MB + Engine InnoDB
1I6j3_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_wffilemods: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
1I6j3_wfhits: Data: 2.02MB + Index: 0.20MB + Engine InnoDB
1I6j3_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1I6j3_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
1I6j3_wfknownfilelist: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
1I6j3_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1I6j3_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_wflogins: Data: 0.34MB + Index: 0.13MB + Engine InnoDB
1I6j3_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1I6j3_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
1I6j3_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
1I6j3_wfstatus: Data: 1.02MB + Index: 0.11MB + Engine InnoDB
1I6j3_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_woocommerce_bundled_itemmeta: Data: 1.52MB + Index: 0.92MB + Engine InnoDB
1I6j3_woocommerce_bundled_items: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
1I6j3_wpgdprc_consents: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
1I6j3_yoast_indexable: Data: 2.52MB + Index: 1.23MB + Engine InnoDB
1I6j3_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
1I6j3_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
1I6j3_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
1I6j3_yoast_seo_links: Data: 0.45MB + Index: 0.23MB + Engine InnoDB
1I6j3_yoast_seo_meta: Data: 4.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

amn_mi-lite: 2
attachment: 1282
atum_purchase_order: 5
atum_supplier: 6
blocks: 19
customize_changeset: 22
custom_css: 1
featured_item: 8
jetpack_migration: 2
ml-slider: 1
nav_menu_item: 30
oembed_cache: 70
page: 40
polylang_mo: 3
post: 4
product: 599
product_variation: 375
revision: 40
shop_coupon: 11
shop_order: 5340
shop_order_refund: 332
slidedeck2: 1
user_registration: 1
vpc-config: 1
warmcache: 49
wc_order_email: 7
wc_order_status: 15
wc_rma: 1
woo_discount: 1
wpcf7_contact_form: 4
yith-wccos-ostatus: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (36) ###

ATUM Inventory Management for WooCommerce: door Stock Management Labs™ – 1.7.7
Calculated Fields Form: door CodePeople – 1.0.415
Contact Form 7: door Takayuki Miyoshi – 5.2.2
Site Kit by Google: door Google – 1.17.0
Imagify: door WP Media – 1.9.11
Kadence WooCommerce Email Designer: door Kadence WP – 1.4.3 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.5.2
Kiyoh Customerreview: door kiyoh – 1.0.29 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.5.2
Loco Translate: door Tim Whitlock – 2.4.3
Mollie-betalingen voor WooCommerce: door Mollie – 5.9.0
Really Simple SSL: door Really Simple Plugins – 3.3.5
Silvasoft boekhouden: door silvasoft – 2.3 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.5.2
Tawk.to Live Chat: door Tawkto – 0.4.3
Banner voor GDPR-toestemming voor cookies: door termly  – 2.3.15
Advanced Order Export For WooCommerce: door AlgolPlus – 3.1.6
WooCommerce Composite Products: door SomewhereWarm – 7.1.0
WooCommerce Conditional Shipping and Payments: door SomewhereWarm – 1.8.5
WooCommerce Cost of Goods: door SkyVerge – 2.9.8 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.5.2
WooCommerce Google Analytics Integration: door WooCommerce – 1.4.23 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.5.2
WooCommerce MyParcel: door Richard Perdaan – 4.0.5 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.5.2
WooCommerce Offerte: door Voleatech GmbH – 1.7.10 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.5.2
WooCommerce Order Status Manager: door SkyVerge – 1.12.2
WooCommerce PDF Invoices & Packing Slips: door Ewout Fernhout – 2.6.1
WooCommerce PDF Invoices & Packing Slips Professional: door Ewout Fernhout – 2.6.4 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.5.2
WooCommerce PDF Invoices & Packing Slips Premium Templates: door Ewout Fernhout – 2.9.6 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.5.2
WooCommerce POS: door kilbot – 0.4.24 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.5.2
WooCommerce Product Bundles: door SomewhereWarm – 6.4.0
WooCommerce: door Automattic – 4.5.2
Wordfence Security: door Wordfence – 7.4.11
Yoast SEO: door Team Yoast – 15.0
WP GDPR Compliance: door Van Ons – 1.5.4
WP-Mail-SMTP: door WPForms – 2.4.0
WooCommerce product feed Manager: door Michel Jongbloed – 2.14.0 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.5.2
WP Rocket: door WP Media – 3.7.2
WP YouTube Lyte: door Frank Goossens (futtta) – 1.7.14
Yoast SEO: WooCommerce: door Team Yoast – 13.6
YellowPencil: door WaspThemes – 7.3.1

### Inactive Plugins (6) ###

Autoptimize: door Frank Goossens (futtta) – 2.7.7
Cloudflare: door Cloudflare
Inc. – 3.8.2

Composite Products - Conditional Images: door SomewhereWarm – 1.2.2 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.5.2
GA Google Analytics: door Jeff Starr – 20200815
WooCommerce Admin: door WooCommerce – 1.5.0 – Geïnstalleerde versie niet getest met actieve versie van WooCommerce 4.5.2
WP Super Cache: door Automattic – 1.7.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
composite (composite)
external (external)
grouped (grouped)
simple (simple)
variable (variable)
woosb (woosb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Winkelbasis: #141 - /shop/
Winkelmand: #140 - /cart/
Afrekenen: #139 - /checkout/
Mijn account: #138 - /my-account/
Algemene voorwaarden: #100 - /av/

### Theme ###

Name: Flatsome
Version: 3.12.2
Author URL: http://www.uxthemes.com/
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een child thema aan. Zie: Hoe maak je een child thema

WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-product_cat.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php


### Composite Products ###

Database Version: 7.1.0
Loopback Test: ✔
Template Overrides: –

### Product Bundles ###

Database Version: 6.4.0
Loopback Test: ✔
Template Overrides: –

### Action Scheduler ###

Afgerond: 1.550
Oldest: 2020-09-05 17:05:41 +0000
Newest: 2020-10-06 04:32:30 +0000

Mislukt: 27
Oldest: 2019-05-28 15:22:24 +0000
Newest: 2020-10-06 00:01:22 +0000

In afwachting: 5
Oldest: 2020-10-06 10:56:09 +0000
Newest: 2020-10-11 07:31:26 +0000

`

**Comment by G1enn1** [comment]
Hello,

Here are some screenshots.
On the first you can see that i manually put the order on status 'delivered'
And then when i search for it it's gone on the second screenshot.
How can we fix this?
Especially because the orders are going on 'delivered' when we don't want
them to.
They just disappeared.
Do you need anything else?

[image: image.png]
[image: image.png]

Met stralende groet,

Glenn van der Kroef

Stralendgroen
050 211 0420
Info@stralendgroen.nl
www.stralendgroen.nl


Op di 6 okt. 2020 om 08:19 schreef ivatautomattic <notifications@github.com

**Comment by rrennick** [comment]
@G1enn1 I apologize for the really long delay in follow up here. WooCommerce core does not have a `Delivered` status. You must have an extension that's adding it. I'll close this due to its age and seems to be an issue with an extension.
