### ISSUE TITLE
change receiver email of default PayPal Gateway using filter

### ISSUE THREAD

**Issue by pexlechris** [woocommerce/woocommerce#27867]
**Is your feature request related to a problem? Please describe.**
I cannot change the paypal receiver email in gateway settings with a wp filter.
I can change it in the checkout, but when an IPN come it cannot authorize the IPN request because the IPN email address is different from the Gateway email address.

**Describe the solution you'd like**
I would like to exists a wp filter that filter the PayPal Gateway settings

**Describe alternatives you've considered**
Also, my problem could be resolved, if there was a filter to ignore the WC_Gateway_Paypal_IPN_Handler::validate_receiver_email
or if I could change the get_option using a wp filter

**Comment by BusinessBloomer** [comment]
Until that's fixed, I managed to find a workaround and override the class: https://www.businessbloomer.com/woocommerce-multiple-paypal-accounts/

Tested and it works, but please be careful if you wish to use this on a live site

**Comment by barryhughes** [comment]
Checking before we add a new hook: would filtering on `option_woocommerce_paypal_settings` and modifying the `receiver_email` value work for you, or is that problematic?

**Comment by pexlechris** [comment]
To help you...
The problem is when need it to validate the IPN paypal email with the email in the settings.
In this file `/woocommerce/includes/gateways/paypal/includes/class-wc-gateway-paypal-ipn-handler.php`
if I could to bypass the validation of method `validate_receiver_email`,
the problem would have been solved.

So if with this hook `option_woocommerce_paypal_settings `, I could bypass this validation (changing on the fly the `$this->receiver_email`: email of the settings), yes this could be a solution

**Comment by barryhughes** [comment]
You could certainly use that hook to set the receiver email to some non-default value for the duration of a single request (ie, when an IPN message is received—and you could further restrict the change to a specific subset of those requests if you need to) ... generally, we would prefer to reuse existing hooks where possible, so long as they are suitable, vs adding new ones.

**Comment by barryhughes** [comment]
I'll close for the time being; but if you believe using the hook I shared is not a valid approach then please do update us and perhaps include a few details as to why it doesn't work. Thanks!

**Comment by pexlechris** [comment]
I searched in the code of woocommerce plugin and this filter `option_woocommerce_paypal_settings `, there is nowhere.

I use the old default PayPal Gateway. Not the extra plugin

**Comment by barryhughes** [comment]
Hi @pexlechris,

It is provided by the [Options API](https://developer.wordpress.org/plugins/settings/options-api/) rather than by WooCommerce, *and is formed dynamically at runtime* (which is why you will not find it via a string search), along with a few other filter hooks:

- `pre_option_<OPTION_NAME>`
- `default_option_<OPTION_NAME>`
- `option_<OPTION_NAME>`

In our case, of course, the option name in question is `woocommerce_paypal_settings`, resulting in a filter called `option_woocommerce_paypal_settings`.
