### ISSUE TITLE
Create `wc-scripts` package

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#27868]
Create a package similar to [`@wordpress/scripts`](https://www.npmjs.com/package/@wordpress/scripts). The new package will be a collection of reusable scripts tailored for WooCommerce development.

**Comment by rrennick** [comment]
When I started looking at this I realized all the scripts are in the `@woocommerce/e2e-environment` package so we don't need a separate package for scripts. The `@wordpress/scripts` package runs scripts from multiple Gutenberg related packages.
