### ISSUE TITLE
Add Other than Simple Product Types to `@woocommerce/api` package

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#27872]
Add Other than Simple Product Types to `@woocommerce/api` package. 

Add Other Product Types:
- [x] [Variable product](https://github.com/woocommerce/woocommerce/issues/28883)
- [x] [Grouped product](https://github.com/woocommerce/woocommerce/issues/28885)
- [x] [External product](https://github.com/woocommerce/woocommerce/issues/28884)

**Comment by helgatheviking** [comment]
Can it be extensible to add other product types too?

**Comment by ObliviousHarmony** [comment]
It already is @helgatheviking! Once I iron out a few bugs and finish #27871 I'll be writing documentation about how to do it. I didn't want to actively encourage it until we reached a more stable point with the API of the package, but I think we're just about there.

**Comment by ObliviousHarmony** [comment]
I never did get the opportunity to write that documentation, sorry!

As far as progress on this issue goes, I did manage to finish the `SimpleProduct` type as well as all of the shared data types that our various products provide. It shouldn't be _too_ much work to extend this to other product types now though!

**Comment by rrennick** [comment]
Closing this as complete.

@helgatheviking The issues listed in the description are linked to PRs for that product type. Either the grouped PR or external product PR would be a good one to look at for a reference for adding another product type.
