### ISSUE TITLE
Write new e2e test: Merchant / Order Emails Received (new order, payment etc)

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#27879]
Write a new e2e test that covers Merchant / Order Emails Received flow. 

The test should cover the following functionality:
- new order 
- TBD

**Comment by zhongruige** [comment]
For this task, I'll start with a test for emails send through the Order Actions postbox (highlighted in orange below):

<img width="337" alt="Screen Shot 2021-03-02 at 9 17 37 PM" src="https://user-images.githubusercontent.com/71906536/109752034-e7dbfa00-7b9c-11eb-8c75-9530e06ac799.png">

This will also include adding in support for installing the WP Mail Logging plugin as part of the e2e container initialization. From there, I'll see what other flows would be good to add without increasing the scope of the task too much, then break them down into separate tasks/PRs if needed.
