### ISSUE TITLE
Finish SimpleProduct Type in `@woocommerce/api` package

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#27871]
Finish SimpleProduct Type in `@woocommerce/api` package. 

Finish SimpleProduct Type:
- Finish base type
- Add specific-features

**Comment by ObliviousHarmony** [comment]
- Fill out the rest of the `Product` base class with properties shared among all product types
- Add (if any) the rest of the `SimpleProduct`-specific properties
- Add the new properties to the product repository
  - Given all of the shared code among product repositories, perhaps a single "product repository" with a given type is best
- Add "list", "read", "update", and "delete" operations for `SimpleProduct`
- Add the new properties to the simple product factory in `@woocommerce/e2e-utils`
