### ISSUE TITLE
Publish `@woocommerce/e2e-tests` package on npm for the first time

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#27876]
Publish `@woocommerce/e2e-tests` package on npm for the first time.

**Comment by rrennick** [comment]
Related: 
- #27805 
- #27836 
- The `e2e-utils` package will need to be updated and released after #27836 is merged.
- We need to add a readme for the package

Once those 4 are complete, this can be released.

**Comment by rrennick** [comment]
Addressed in #27916.
