### ISSUE TITLE
Test the flow of `Merchant / Plugins` (can update WooCommerce)

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#27881]
Write a new test that covers Merchant / Plugins flow. 

The test should cover the following functionality:
- merchant can update WooCommerce

**Comment by zhongruige** [comment]
We'll work on this separately as part of the automating smoke testing project.

**Comment by rrennick** [comment]
Addressed in https://github.com/woocommerce/woocommerce/issues/25957
