### ISSUE TITLE
Spike: Introduce e2e tests reporting tool

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#27885]
Introduce the e2e tests reporting tool. For example, https://github.com/allure-framework/allure2.

**Comment by zhongruige** [comment]
Some helpful resources:

* https://github.community/t/how-to-generate-allure-reports-in-the-github-actions/167735/2
* https://javascript.plainenglish.io/using-allure-and-jest-to-improve-test-reporting-d43a8e01ab0f

**Comment by tammullen** [comment]
> Some helpful resources

Thanks!
