### ISSUE TITLE
Make is_request() public

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#27888]
the WooCommerce class method [`is_request()`](https://github.com/woocommerce/woocommerce/blob/3391d8c0b082b94abaccb401a8b4c3a1812091be/includes/class-woocommerce.php#L315) is a handy utility for testing what kind of environment you're currently in. But it's `private` so extensions can't access it and instead have to duplicate it.

**Describe the solution you'd like**
Convert the method from `private` to `public`

**Describe alternatives you've considered**
Duplicating the entire function in every other plugin that needs it

**Comment by abhishek-pokhriyal** [comment]
> Duplicating the entire function in every other plugin that needs it

Yup, I've duplicated the function in almost half a plugins by now. I always wonder why is it declared as private in the first case.

**Comment by lkraav** [comment]
> > Duplicating the entire function in every other plugin that needs it
> 
> Yup, I've duplicated the function in almost half a dozen plugins by now. I always wonder why is it declared as private in the first place.

Probably because owners know it's too fragile and subject to change in public use.

It really seems like something WP core should ship.

**Comment by helgatheviking** [comment]
>Probably because owners know it's too fragile and subject to change in public use.

Not sure I understand what you mean here? The function is unreliable? If so, that better at least 1 core function to check on than the same function in multiple plugins I think. 

You might be right that it belongs in WP core, but my experience with WP core is it can take 8-10 years to get a single line of code added. Getting into Woo seems a heck of a lot more promising. :)

**Comment by abhishek-pokhriyal** [comment]
@lkraav There is another public method in WooCommerce Class called [`is_rest_api_request`](https://github.com/woocommerce/woocommerce/blob/2380e9d37680b19dcb698e7724bea893f8702d67/includes/class-woocommerce.php#L282-L300) which should be in WP Core and might be fragile too.

**Comment by lkraav** [comment]
> > Probably because owners know it's too fragile and subject to change in public use.
> 
> Not sure I understand what you mean here? The function is unreliable? If so, that better at least 1 core function to check on than the same function in multiple plugins I think.

I don't know how reliable this method is or isn't.

For example, I recently discovered https://developer.wordpress.org/reference/functions/wp_is_json_request/ exists.

Identifying request types looks like quite a confusing landscape, starting with the age old `is_admin()` which also tests positive for any `admin-ajax.php` request, frontend too.

All I'm saying is - not surprised this method is not public.

**Comment by claudiosanches** [comment]
@helgatheviking thank you for your suggestions, but note that `is_request()` is for internal use only, that's why is private, we don't plan to support it or give support for all kinds of customizations that may affect this method.
Also is impossible for us to deprecate or remove the method once is public, in case we want to replace to something WP core may implement.

**Comment by helgatheviking** [comment]
Had to try @claudiosanches ! :) About to copy the exact same function into one of my plugins.
