### ISSUE TITLE
Write new e2e test: Merchant / Product (view, search and edit products)

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#27880]
Write 1 new e2e test that covers Merchant / Product flow. 

The test should cover the following functionality:

- view all products
- search products
- edit product details

**Comment by zhongruige** [comment]
Looking into how we can best organize the tests for the view all products, search products, and edit product details flow, I am thinking that we can split this up into two tests:

* `describe('View products')` which would have two tests under it, something like `it('can view all products') {}` and `it('can search for a product') {}`. Mostly my thinking is the list and search are two 'views' so they would fit well into one test.
* `describe('Edit product details')`, which would have a test to edit the details on a product and verify the changes are saved.

**Comment by juliaamosova** [comment]
Thanks for starting to work on it @zhongruige! I agree with your proposal and think we should indeed split those tests as you suggested.

I guess what's left here to figure out is what search parameters should we use (by product name, partial product name). And what exact details do we want to edit at a minimum in the test.

**Comment by zhongruige** [comment]
> Thanks for starting to work on it @zhongruige! I agree with your proposal and think we should indeed split those tests as you suggested.
> 
> 
> 
> I guess what's left here to figure out is what search parameters should we use (by product name, partial product name, anything else). And what exact details do we want to edit at a minimum in the test? 

That's a good question! I was debating the same myself. I was thinking we could start with a partial product name to start then iterate on that from there (thinking that often times a user will start with a partial search then go from there once a match is found). Potentially in the future we could add an independent and more focused robust search test that covers things like zero searches, full matches etc.

Curious on your thoughts!

**Comment by juliaamosova** [comment]
>That's a good question! I was debating the same myself. I was thinking we could start with a partial product name to start then iterate on that from there (thinking that often times a user will start with a partial search then go from there once a match is found). Potentially in the future we could add an independent and more focused robust search test that covers things like zero searches, full matches etc.

I agree that we should start with something very basic to at least cover the search functionality itself, to make sure it works. This had been our approach in other tests as well so let's stick to that. As you mentioned, we can add more test cases in the next iteration of writing/updating tests. 

>For the edit piece, I am thinking we can test changes to:
>- title
>- description
>- price

I agree with these as well - these 3 are the basics that we should start with to cover the minimum functionality that we can in this round. Let's start with it.

**Comment by zhongruige** [comment]
> > That's a good question! I was debating the same myself. I was thinking we could start with a partial product name to start then iterate on that from there (thinking that often times a user will start with a partial search then go from there once a match is found). Potentially in the future we could add an independent and more focused robust search test that covers things like zero searches, full matches etc.
> 
> @zhongruige I agree that we should start with something very basic to at least cover the search functionality itself, to make sure it works. This had been our approach in other tests as well so let's stick to that. As you mentioned, we can add more test cases in the next iteration of writing/updating tests.
> 
> > For the edit piece, I am thinking we can test changes to:
> > 
> > * title
> > * description
> > * price
> 
> I agree with these as well - these 3 are the basics that we should start with to cover the minimum functionality that we can in this round. Let's start with it.

Sounds good! Thanks for the feedback!
