### ISSUE TITLE
Attribute "arrow" in dropdown collapses product date table

### ISSUE THREAD

**Issue by jrick1229** [woocommerce/woocommerce#27894]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

When clicking the "arrow" in the attributes tab, the entire product data table is collapsed: https://d.pr/i/25dAeK

Clicking on the attribute name or row outside of the "arrow" does not result in this issue.

Doing a console debug when clicking the "arrow" results in the following:

```
SyntaxError: Element.querySelectorAll: '#side-sortables .ui-sortable-handle:visible' is not a valid selector
```

**Expected behavior**

Clicking the "arrow" should expand the attribute without collapsing the product data table.

**Actual behavior**

Clicking the "arrow" will expand the attribute, but also collapses the entire product data table.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**

Steps to reproduce the bug:
1. Go to a variable product
2. Click on the 'Attributes' tab
3. Click on the "arrow" to expand an attribute: https://d.pr/i/Pm49qY
4. See issue: https://d.pr/i/25dAeK

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

<details>

```
### WordPress Environment ###

WordPress address (URL): http://localhost:10005
Site address (URL): http://localhost:10005
WC Version: 4.6.0
REST API Version: ✔ 4.6.0
WC Blocks Version: ✔ 3.4.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.0-rc.3
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.3.5
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.6.0

### Active Plugins (4) ###

WooCommerce Stripe Gateway: by WooCommerce – 4.5.2
WooCommerce Subscriptions: by WooCommerce – 3.0.7
WooCommerce: by Automattic – 4.6.0-rc.1
WP Mail Logging: by MailPoet – 1.9.7

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.7.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –
```
</details>

**Comment by juliaamosova** [comment]
Hi @jrick1229,

Thank you for reporting the issue. It had also been reported here https://github.com/woocommerce/woocommerce/issues/27923. We are closing your issue in favor of https://github.com/woocommerce/woocommerce/issues/27923. Please continue sharing your feedback there if needed.

I know that your issue was submitted prior to https://github.com/woocommerce/woocommerce/issues/27923 but I happened to reply to https://github.com/woocommerce/woocommerce/issues/27923 already. Sorry about that!
