### ISSUE TITLE
Improve documentation on running e2e tests on the external (non-local) URL

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#27902]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

Running e2e tests on the external URL doesn't seem to work. 

I tried to run e2e tests on my Pressable test site. I followed the instructions we have here: [Test Variables](https://github.com/woocommerce/woocommerce/tree/master/tests/e2e#test-variables). 

In particular, I did as suggested in our docs:

>If you need to modify the port for your local test environment (eg. port is already in use), copy `tests/e2e/env/config/default.json` to `tests/e2e/config/default.json` and edit that copy. Only edit this file while your test container is down.

As a result, the URL itself gets picked up but the process but it is still waiting for the Docker container to be built:

```
juliaamosova@julia-mbp woocommerce % npm run test:e2e-dev

> woocommerce@4.7.0 test:e2e-dev /Users/juliaamosova/src/woocommerce
> npm explore @woocommerce/e2e-environment -- npm run test:e2e-dev


> @woocommerce/e2e-environment@0.1.5 test:e2e-dev /Users/juliaamosova/src/woocommerce/tests/e2e/env
> bash ./bin/wait-for-build.sh && ./bin/e2e-test-integration.js --dev

Testing URL: https://jamosova2.mystagingwebsite.com

Wed Oct  7 15:23:50 EDT 2020 - Docker container is still being built
Wed Oct  7 15:24:01 EDT 2020 - Docker container is still being built
Wed Oct  7 15:24:11 EDT 2020 - Docker container is still being built
Wed Oct  7 15:24:22 EDT 2020 - Docker container is still being built
Wed Oct  7 15:24:32 EDT 2020 - Docker container is still being built
Wed Oct  7 15:24:42 EDT 2020 - Docker container is still being built
Wed Oct  7 15:24:53 EDT 2020 - Docker container is still being built
Wed Oct  7 15:25:03 EDT 2020 - Docker container is still being built
Wed Oct  7 15:25:13 EDT 2020 - Docker container is still being built
Wed Oct  7 15:25:24 EDT 2020 - Docker container is still being built
Wed Oct  7 15:25:34 EDT 2020 - Docker container is still being built
Wed Oct  7 15:25:45 EDT 2020 - Docker container is still being built
Wed Oct  7 15:25:55 EDT 2020 - Docker container is still being built
Wed Oct  7 15:26:05 EDT 2020 - Docker container is still being built
Wed Oct  7 15:26:16 EDT 2020 - Docker container is still being built
Wed Oct  7 15:26:26 EDT 2020 - Docker container is still being built
^C
juliaamosova@julia-mbp woocommerce %
```

I tried to build the Docker container and run tests again but I am getting the same result as above. 

Also noting here that we shouldn't require a Docker container if tests are to be run on the external URL. 

**Expected behavior**

I expected that there will be no need to build the Docker container. We should be able to copy `tests/e2e/env/config/default.json` to `tests/e2e/config/default.json`, edit that copy with custom URL and other details if needed, run all the necessary commands before running e2e tests as described in [Prep work for running tests](https://github.com/woocommerce/woocommerce/tree/master/tests/e2e#prep-work-for-running-tests) (except for `npm run docker:up`) and then be able to run e2e tests on the external URL. 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Copy `tests/e2e/env/config/default.json` to `tests/e2e/config/default.json`, edit that copy with a custom URL where you want to run e2e tests and other details if needed.
2. Run all the necessary commands before running e2e tests as described in [Prep work for running tests](https://github.com/woocommerce/woocommerce/tree/master/tests/e2e#prep-work-for-running-tests) (except for `npm run docker:up`)
3. Run tests by using `npm run test:e2e-dev`
4. See that your custom URL is listed as where the tests will run on. But the tests don't start running. Instead, there is a loop of messages letting you know that the Docker container is still being built. 

**Screenshots**

N/A

**Isolating the problem (mark completed items with an [x]):**

N/A

**WordPress Environment**

N/A

**Comment by ObliviousHarmony** [comment]
Howdy @juliaamosova,

This is caused by the test site lacking the "Ready" post indicating WordPress has been installed and configured for testing. In https://github.com/woocommerce/woocommerce/pull/27432 this is noted as being a requirement. I think it might be a good idea to display a more descriptive version of this message in cases where we aren't referencing a local host. I don't think we should remove this requirement however as it feels like a good way to explicitly say "I'd like to run tests on this site" and allow the suite to execute. That said, I think it might also run anyway once the script reaches its maximum failures, so that's probably worth keeping in mind too.

**Comment by rrennick** [comment]
> I think it might be a good idea to display a more descriptive version of this message in cases where we aren't referencing a local host. 

We don't have any way of determining if it's a local host. My dev installs that I use outside of E2E are `project.localhost` but I could name them `project.com`.

> I think it might also run anyway once the script reaches its maximum failures, so that's probably worth keeping in mind too.

It stops waiting after 5 minutes.

**Comment by rrennick** [comment]
> Also noting here that we shouldn't require a Docker container if tests are to be run on the external URL.

@juliaamosova We don't. Do we need to expand the [instructions for external testing](https://github.com/woocommerce/woocommerce/blob/master/tests/e2e/env/external.md) ?
