### ISSUE TITLE
[WooCommerce 4.6 RC 1] Website fails to create shop, cart, checkout and my account pages once WooCommerce plugin is activated.

### ISSUE THREAD

**Issue by nixiack** [woocommerce/woocommerce#27910]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] there is a similar bug that was found for Beta [**here**](https://github.com/woocommerce/woocommerce/issues/27770) which was closed.

**Describe the bug**
Website fails to create shop, cart, checkout and my account pages once WooCommerce plugin is activated.

**Expected behavior**
After WooCommerce is installed from scratch and a product setup, the `Cart`, `Checkout`, `Shop` and `My Account` pages are not created. 

**Actual behavior**
After installing WC 4.6 RC-1 and going through the steps to create products, establish shipping, and installing the other plugins (Jetpack/WC Services/MailChimp), you can go to the product page but adding a product to the Cart, going to the Cart in navigation or trying to get to a `Cart` or `My Account` page rotates back to the Home Page.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Install WC 4.6 RC-1 from scratch
2. Go through setup wizard and set up a product/shipping/etc.
3. Go to the product under **WooCommerce > Products** and physically add the product to the Cart
4. Click `Go to Cart` or click the `Cart` option on the navigation, it takes you to a blank page or the Home page

**Screenshots**
Pages prior to install: 

![Screenshot](https://d.pr/i/bbBUuY+)
Screenshot: https://d.pr/i/bbBUuY

Installing WC 4.6 RC-1, made sure setup went through and installed the requisite additional plugins successfully: 

![Screenshot](https://d.pr/i/rZP3fc+)
Screenshot: https://d.pr/i/rZP3fc

Created product, same pages (no WC pages): 

![Screenshot](https://d.pr/i/18jfUo+)
Screenshot: https://d.pr/i/18jfUo

Testing product, I am unable to get to the Cart page as it does not exist: http://g.recordit.co/VsiGHAksPs.gif
(From the Gif, I added the product 3 times total - I cannot get to the Cart from the Go to Cart option shortcut nor the top nav area).

Created WC default pages under **WooCommerce > Status > Tools** successfully. 

![Screenshot](https://d.pr/i/Ic3SlD+)
Screenshot: https://d.pr/i/Ic3SlD

Cart works: http://g.recordit.co/E25nmWJnOl.gif

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://testmike.local
Site address (URL): http://testmike.local
WC Version: 4.6.0
REST API Version: ✔ 4.6.0
WC Blocks Version: ✔ 3.4.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.0-rc.3
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.10.1
PHP Version: 7.0.3 - We recommend using PHP version 7.2 or above for greater performance and security. How to update your PHP version
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
cURL Version: 7.38.0
OpenSSL/1.0.1t

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.21-MariaDB-log - We recommend a minimum MySQL version of 5.6. See: WordPress requirements
Max Upload Size: 1,000 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.6.0
WC Database Prefix: wp_
Total Database Size: 18.66MB
Database Data Size: 13.95MB
Database Index Size: 4.71MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.03MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 2.48MB + Index: 3.00MB + Engine InnoDB
wp_posts: Data: 0.48MB + Index: 0.25MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.09MB + Index: 0.08MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 9.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.11MB + Index: 0.17MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 183
page: 6
post: 2
product: 492
product_variation: 296

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.6.0-rc.1

### Inactive Plugins (5) ###

Google Ads & Marketing by Kliken: by Kliken – 1.0.4 – Installed version not tested with active version of WooCommerce 4.6.0
Jetpack by WordPress.com: by Automattic – 9.0.1
Mailchimp for WooCommerce: by Mailchimp – 2.4.7 – Installed version not tested with active version of WooCommerce 4.6.0
WooCommerce Payments: by Automattic – 1.5.0 – Installed version not tested with active version of WooCommerce 4.6.0
WooCommerce Services: by Automattic – 1.24.3 – Installed version not tested with active version of WooCommerce 4.6.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #995 - /shop/
Cart: #996 - /cart/
Checkout: #997 - /checkout/
My account: #998 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.7.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 8
Oldest: 2020-09-22 13:38:42 +0000
Newest: 2020-10-08 19:06:30 +0000

`
```
</details>

**Comment by rodrigoprimo** [comment]
@nixiack I'm not able to reproduce this issue. Here is a GIF of the steps that I took. Are you doing something different? The pages should be created once WooCommerce is activated.

![Peek 2020-10-08 19-04](https://user-images.githubusercontent.com/77215/95519424-6b514080-099b-11eb-9a71-36dd3ffe3ee8.gif)

**Comment by tammullen** [comment]
Thanks @nixiack, I also can't seem to reproduce it, I did the same steps as Rodrigo. I also continued on through the setup wizard and added a product just to confirm the pages remained after being created.

Is the test site you used brand new? Is there a chance it could have had a now deleted previous WC install?

**Comment by rodrigoprimo** [comment]
The only explanation that I have so far for this is that for some reason (maybe an old WooCommerce install that was partially removed) the option `woocommerce_db_version` exists in the database before WooCommerce is activated. This would explain why the pages were not created. @nixiack could you please check if that is the case?

**Comment by rodrigoprimo** [comment]
Closing due to lack of feedback and as WC 4.6.0 was released. I imagine this problem happened because the database already contained the `woocommerce_db_version` option.
