### ISSUE TITLE
REST-API Orders line_item price inconsistency when quantity > 1

### ISSUE THREAD

**Issue by mccoyg** [woocommerce/woocommerce#27911]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
On line 172 in /woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php
`$data['price'] = $item->get_quantity() ? $item->get_total() / $item->get_quantity() : 0;`
the mathematical division in certain cases creates an inconsistent result. This code is inherited in V3. I am using V3

price in database = $14.31
qty ordered = 10
line_item subtotal (no tax) = 143.10

Rest Api response
'price':  '14.309999999999999',

**Expected behavior**
'price': '14.31'

**Actual behavior**
Rest Api response
'price':  '14.309999999999999',

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

I am patching this code in production for now which fixes it temporarily. 
`$data['price'] = $item->get_quantity() ? wc_format_decimal( $item->get_total() / $item->get_quantity() ): 0;`
I am unsure if they WooCommerce team had a specific reason for allowing the precision of this float to go beyond two decimal places.

**Screenshots**
<img width="832" alt="Screen Shot 2020-10-08 at 6 23 18 PM" src="https://user-images.githubusercontent.com/14010752/95530823-b49d9200-0993-11eb-8732-ec639e8921a5.png">

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by rrennick** [comment]
@mccoyg Thanks for reporting the issue.

> I am unsure if they WooCommerce team had a specific reason for allowing the precision of this float to go beyond two decimal places.

Adding the developer feedback label as there could have been a reason the value was left unrounded.

**Comment by NomadAndInLove** [comment]
I'm experiencing the same issue on my show. Issue only happens when more than 1 of the same item is ordered.

**Comment by mccoyg** [comment]
@NomadAndInLove I think the file/path is: wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php. I hand-typed that path so please verify.

**Comment by NomadAndInLove** [comment]
@mccoyg Apologies. I'm obviously blind. I have already tested your patch by replace the code on line 172 and it works 100%. Is there a way to create a snippet via the functions.php file on my Child Theme so that I don't have to replace this line every time WooCommerce updates?

**Comment by mccoyg** [comment]
@NomadAndInLov Sorry. I thought it would have been updated by now. I don't know if there is a filter to tie into. You might need to create a sub-class of WC_REST_Orders_V2_Controller?

**Comment by NomadAndInLove** [comment]
@mccoyg I'm running Version 5.0.0 of WooCommerce. I haven't updated it to 5.1.0. Are you saying the issue has been resolved by WooCommerce?

Anyway, I'll see if I can create a snippet for it and post it on Stackoverflow in case someone else needs a fix for it.

**Comment by mccoyg** [comment]
@NomadAndInLove sounds good. Please link the stackoverflow link here. I am unsure they (woocommerce) will ever update this and  I might need to refer back to it at some point.

**Comment by NomadAndInLove** [comment]
@mccoyg Will do. I'll post it here as soon as it's up on Stackoverflow.

**Comment by NomadAndInLove** [comment]
@mccoyg I'll also like back here from my post on Stackoverflow so it's easy to follow this issue.

**Comment by robin-scott** [comment]
@rrennick - came here from a core Slack discussion. In my opinion, this line should be rounded.

**Comment by mccoyg** [comment]
@rrennick the wc_format_decimal() method is taken straight from the earlier in that class (line 162). seems like an easy merge by core.

**Comment by robin-scott** [comment]
`wc_format_decimal ` rounds the number to `woocommerce_price_num_decimals` if this is left blank (as it is in this case). FYI - https://woocommerce.wp-a2z.org/oik_api/wc_format_decimal/ - it's super useful in many places.

https://github.com/woocommerce/woocommerce/blob/a7bceeb50f7686c6a1ae4a226bfce64a26bdb076/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php#L172

There are likely some tax use cases where rounding will create an penny going to the wrong place, so probably a filter here may be most beneficial.

**Comment by mccoyg** [comment]
@robin-scott could you give an example of which filter should be used to hook into that controller?

**Comment by schmitzoide** [comment]
Maybe something like this (not tested!)?

```
$decimals = apply_filters( 'wc_get_price_decimals_for_rest_api', get_option( 'woocommerce_price_num_decimals', 2 ) ); 
$price = $item->get_quantity() ? $item->get_total() / $item->get_quantity() : 0;
$price = wc_format_decimal( $price, $decimals );
$data['price'] = $price; 
```

**Comment by mccoyg** [comment]
@schmitzoide. Hmm, not seeing  any reference to this filter in woocommerce: 'wc_get_price_decimals_for_rest_api'. Can you point out where the definition of this filter is?

**Comment by robin-scott** [comment]
@mccoyg right now, the filter doesn't exist (yet) to allow this. It should be optional, as some users may need this to be not rounded if they have taxes applied.

The order meta stored for the line is subtotal, total and qty - which we divide to get a unit price. We're talking about a core change here - adding a filter - not a filter which (currently) exists.

**Comment by robin-scott** [comment]
For the time being, your suggested workaround will achieve this, but shouldn't be applied in all cases - hence the discussion is to add a filter to allow you to override the default, which doesn't work for your case.

**Comment by schmitzoide** [comment]
@mccoyg The `wc_get_price_decimals_for_rest_api` filter would be a suggestion to create a new one for the particular case of the REST API output.

**Comment by mccoyg** [comment]
@robin-scott. copy that. Just trying to get as much information in this thread as possible to help others who happen upon this.

**Comment by robin-scott** [comment]
@mccoyg No problem at all - you've basically flagged the exact place to put the filter and given the correct hook :)

**Comment by NomadAndInLove** [comment]
@mccoyg I've updated my question on Stackoverflow. I've also linked my question to this post.
