### ISSUE TITLE
MariaDB Syntax error

### ISSUE THREAD

**Issue by bash-stack** [woocommerce/woocommerce#27917]
Mariadb throws error: 

```
 *23201 FastCGI sent in stderr: "PHP message: WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '('1519', 'fb_visibility', 'no')('1525', 'fb_visibility', 'no')('813', 'fb_vis...' at line 2 for query 
                        INSERT INTO wp_postmeta (post_id, meta_key, meta_value )
                                VALUES ('1510', 'fb_visibility', 'no')('1519', 'fb_visibility', 'no')('1525', 'fb_visibility', 'no')('813', 'fb_visibility', 'no')('826', 'fb_visibility', 'no')('832', 'fb_visibility', 'no')('989', 'fb_visibility', 'no')('1080', 'fb_visibility', 'no')('1086', 'fb_visibility', 'no')('1103', 'fb_visibility', 'no')('1114', 'fb_visibility', 'no')('1136', 'fb_visibility', 'no')('1240', 'fb_visibility', 'no')('1912', 'fb_visibility', 'no')('1923', 'fb_visibility', 'no')('1938', 'fb_visibility', 'no')('1000', 'fb_visibility', 'no')('1007', 'fb_visibility', 'no')('1072', 'fb_visibility', 'no')('1094', 'fb_visibility', 'no')('1109', 'fb_visibility', 'no')('1161', 'fb_visibility', 'no')('1163', 'fb_visibility', 'no')('1948', 'fb_visibility', 'no')
                 made by do_action('wp_ajax_nopriv_wc_facebook_background_handle_virtual_products_variations'), WP_Hook->do_action, WP_Hook->apply_filters, SkyVerge\WooCommerce\PluginFramework\v5_5_4\SV_WP_Background_Job_Handler->maybe_handle, SkyVerge\WooCommerce\PluginFramework\v5_5_4\SV_WP_Background_Job_Handler->handle, SkyVerge\WooCommerce\Facebook\Utilities\Background_Handle_Virtual_Products_Variations->process_job, SkyVerge\WooCommerce\Facebook\Utilities\Background_Handle_Virtual_Products_Variations->sync_and_hide, SkyVerge\WooCommerce\Facebook\Utilities\Background_Handle_Virtual_Products_Variations->set_product_visibility_metaPHP message: WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '('1519', 'fb_visibility', 'no')('1525', 'fb_visibility', 'no')('813', 'fb_vis...' at li
2020/10/08 22:01:54 [error] 22#22: *23201 FastCGI sent in stderr: "handle, SkyVerge\WooCommerce\PluginFramework\v5_5_4\SV_WP_Background_Job_Handler->handle, SkyVerge\WooCommerce\Facebook\Utilities\Background_Handle_Virtual_Products_Variations->process_job, SkyVerge\WooCommerce\Facebook\Utilities\Background_Handle_Virtual_Products_Variations->sync_and_hide, SkyVerge\WooCommerce\Facebook\Utilities\Background_Handle_Virtual_Products_Variations->set_product_visibility_metaPHP message: WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '('1519', 'fb_visibility', 'no')('1525', 'fb_visibility', 'no')('813', 'fb_vis...' at line 2 for query 
                        INSERT INTO wp_postmeta (post_id, meta_key, meta_value )
                                VALUES ('1510', 'fb_visibility', 'no')('1519', 'fb_visibility', 'no')('1525', 'fb_visibility', 'no')('813', 'fb_visibility', 'no')('826', 'fb_visibility', 'no')('832', 'fb_visibility', 'no')('989', 'fb_visibility', 'no')('1080', 'fb_visibility', 'no')('1086', 'fb_visibility', 'no')('1103', 'fb_visibility', 'no')('1114', 'fb_visibility', 'no')('1136', 'fb_visibility', 'no')('1240', 'fb_visibility', 'no')('1912', 'fb_visibility', 'no')('1923', 'fb_visibility', 'no')('1938', 'fb_visibility', 'no')('1000', 'fb_visibility', 'no')('1007', 'fb_visibility', 'no')('1072', 'fb_visibility', 'no')('1094', 'fb_visibility', 'no')('1109', 'fb_visibility', 'no')('1161', 'fb_visibility', 'no')('1163', 'fb_visibility', 'no')('1948', 'fb_visibility', 'no')
                 made by do_action('wp_ajax_nopriv_wc_facebook_background_handle_virtual_products_variations'), WP_Hook->do_action, WP_Hook->apply_filters, SkyVerge\WooCommerce\PluginFramework\v5_5_4\SV_WP_Background_Job_Handler->maybe_handle, SkyVerge\WooCommerce\PluginFramework\v5_5_4\SV_WP_Background_Job_Handler->handle, SkyVerge\WooCommerce\Facebook\Utilities\Background_Handle_Virtual_Products_Variations->process_job, SkyVerge\WooCommerce\Facebook\Utilities\Background_Handle_Virtual_Produc
2020/10/08 22:01:54 [error] 22#22: *23201 FastCGI sent in stderr: "oducts_Variations->set_product_visibility_metaPHP message: WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '('1519', 'fb_visibility', 'no')('1525', 'fb_visibility', 'no')('813', 'fb_vis...' at line 2 for query 
                        INSERT INTO wp_postmeta (post_id, meta_key, meta_value )
                                VALUES ('1510', 'fb_visibility', 'no')('1519', 'fb_visibility', 'no')('1525', 'fb_visibility', 'no')('813', 'fb_visibility', 'no')('826', 'fb_visibility', 'no')('832', 'fb_visibility', 'no')('989', 'fb_visibility', 'no')('1080', 'fb_visibility', 'no')('1086', 'fb_visibility', 'no')('1103', 'fb_visibility', 'no')('1114', 'fb_visibility', 'no')('1136', 'fb_visibility', 'no')('1240', 'fb_visibility', 'no')('1912', 'fb_visibility', 'no')('1923', 'fb_visibility', 'no')('1938', 'fb_visibility', 'no')('1000', 'fb_visibility', 'no')('1007', 'fb_visibility', 'no')('1" while reading response header from upstream, client: 192.168.224.5, server: , request: "GET /wp-admin/admin-ajax.php?action=wc_facebook_background_handle_virtual_products_variations&nonce=927bbd329d HTTP/1.1", upstream: "fastcgi://192.168.224.4:9000", host: "####", referrer: "http://######/wp-admin/admin-ajax.php?action=wc_facebook_background_handle_virtual_products_variations&nonce=927bbd329d"
2020/10/08 22:01:54 [error] 22#22: *23201 FastCGI sent in stderr: "072', 'fb_visibility', 'no')('1094', 'fb_visibility', 'no')('1109', 'fb_visibility', 'no')('1161', 'fb_visibility', 'no')('1163', 'fb_visibility', 'no')('1948', 'fb_visibility', 'no')
                 made by do_action('wp_ajax_nopriv_wc_facebook_background_handle_virtual_products_variations'), WP_Hook->do_action, WP_Hook->apply_filters, SkyVerge\WooCommerce\PluginFramework\v5_5_4\SV_WP_Background_Job_Handler->maybe_handle, SkyVerge\WooCommerce\PluginFramework\v5_5_4\SV_WP_Background_Job_Handler->handle, SkyVerge\WooCommerce\Facebook\Utilities\Background_Handle_Virtual_Products_Variations->process_job, SkyVerge\WooCommerce\Facebook\Utilities\Background_Handle_Virtual_Products_Variations->sync_and_hide, SkyVerge\WooCommerce\Facebook\Utilities\Background_Handle_Virtual_Products_Variations->set_product_visibility_metaPHP message: WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '('1519', 'fb_visibility', 'no')('1525', 'fb_visibility', 'no')('813', 'fb_vis...' at line 2 for query 
                        INSERT INTO wp_postmeta (post_id, meta_key, meta_value )
                                VALUES ('1510', 'fb_visibility', 'no')('1519', 'fb_visibility', 'no')('1525', 'fb_visibility', 'no')('813', 'fb_visibility', 'no')('826', 'fb_visibility', 'no')('832', 'fb_visibility', 'no')('989', 'fb_visibility', 'no')('1080', 'fb_visibility', 'no')('1086', 'fb_visibility', 'no')('1103', 'fb_visibility', 'no')('1114', 'fb_visibility', 'no')('1136', 'fb_visibility', 'no')('1240', 'fb_visibility', 'no')('1912', 'fb_visibility', 'no')('1923'
, 'fb_visibility', 'no')('1938', 'fb_visibility', 'no')('1000', 'fb_visibility', 'no')('1007', 'fb_visibility', 'no')('1072', 'fb_visibility', 'no')('1094', 'fb_visibility', 'no')('1109', 'fb_visibility', 'no')('1161', 'fb_visibility', 'no')('1163', 'fb_visibility', 'no')('1948', 'fb_visibility', 'no')
                 made by do_action('wp_ajax_nopriv_wc_facebook_background_handle_virtual_pro
2020/10/08 22:01:54 [error] 22#22: *23201 FastCGI sent in stderr: "rk\v5_5_4\SV_WP_Background_Job_Handler->maybe_handle, SkyVerge\WooCommerce\PluginFramework\v5_5_4\SV_WP_Background_Job_Handler->handle, SkyVerge\WooCommerce\Facebook\Utilities\Background_Handle_Virtual_Products_Variations->process_job, SkyVerge\WooCommerce\Facebook\Utilities\Background_Handle_Virtual_Products_Variations->sync_and_hide, SkyVerge\WooCommerce\Facebook\Utilities\Background_Handle_Virtual_Products_Variations->set_product_visibility_metaPHP message: WordPress database error You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '('1519', 'fb_visibility', 'no')('1525', 'fb_visibility', 'no')('813', 'fb_vis...' at line 2 for query 
                        INSERT INTO wp_postmeta (post_id, meta_key, meta_value )

```

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to your webserver/database log

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): https://####
Site address (URL): https://###
WC Version: 4.5.2
REST API Version: ✔ 4.5.2
WC Blocks Version: ✔ 3.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.5.0
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.19.2
PHP Version: 7.4.9
PHP Post Max Size: 256 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.69.1
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.5-MariaDB-1:10.5.5+maria~focal
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.5.2
WC Database Prefix: wp_
Total Database Size: 27.35MB
Database Data Size: 25.47MB
Database Index Size: 1.88MB
wp_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_aiowps_events: Data: 0.41MB + Index: 0.09MB + Engine MyISAM
wp_aiowps_failed_logins: Data: 0.25MB + Index: 0.09MB + Engine MyISAM
wp_aiowps_global_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_aiowps_login_activity: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_aiowps_login_lockdown: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_aiowps_permanent_block: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_comments: Data: 0.15MB + Index: 0.05MB + Engine MyISAM
wp_failed_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_frm_fields: Data: 0.08MB + Index: 0.01MB + Engine MyISAM
wp_frm_forms: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_frm_items: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_frm_item_metas: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_carts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mailchimp_jobs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_masterslider_options: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_masterslider_sliders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 2.14MB + Index: 0.13MB + Engine MyISAM
wp_postmeta: Data: 13.86MB + Index: 0.54MB + Engine MyISAM
wp_posts: Data: 7.74MB + Index: 0.13MB + Engine MyISAM
wp_queue: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_indexable: Data: 0.39MB + Index: 0.19MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.05MB + Index: 0.02MB + Engine MyISAM
wp_yoast_seo_meta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM

### Post Type Counts ###

attachment: 436
booked_appointments: 1
custom_css: 1
elementor_library: 25
frm_form_actions: 15
frm_styles: 1
global_product_addon: 1
nav_menu_item: 15
oembed_cache: 1
option-tree: 1
page: 26
post: 12
product: 24
revision: 838
shop_coupon: 2
shop_order: 68
shop_order_refund: 14
themo_tour: 3
wc_booking: 144

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

Better Search Replace: by Delicious Brains – 1.3.3
Elementor Pro: by Elementor.com – 2.10.3
Elementor: by Elementor.com – 3.0.11
Envato Market: by Envato – 2.0.4
Facebook for WooCommerce: by Facebook – 2.0.4 – Installed version not tested with active version of WooCommerce 4.5.2
Formidable Forms: by Strategy11 – 4.07.01
Insert Headers and Footers: by WPBeginner – 1.4.6
Kirki Customizer Framework: by David Vongries – 3.1.5
Mailchimp for WooCommerce: by Mailchimp – 2.4.7 – Installed version not tested with active version of WooCommerce 4.5.2
Master Slider Pro: by averta – 3.2.2
Post Types Order: by Nsp Code – 1.9.5.2
Simple Page Ordering: by Jake Goldman
10up – 2.3.4

Page Builder Widget Pack: by Themovation – 1.5.13
Widget Logic: by WPChef – 5.10.4
WooCommerce Accommodation Bookings: by WooCommerce – 1.1.21 – Installed version not tested with active version of WooCommerce 4.5.2
Woocommerce Booking Exporter: by wpexperts.io – 1.5 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Bookings: by Automattic – 1.12.2 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.0 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce Product Add-ons: by WooCommerce – 3.0.5 – Installed version not tested with active version of WooCommerce 4.5.2
WooCommerce: by Automattic – 4.5.2
Yoast SEO: by Team Yoast – 15.0
WP-FFPC: by Peter Molnar  – 1.11.2

### Inactive Plugins (5) ###

Akismet Anti-Spam: by Automattic – 4.1.6
All In One WP Security: by Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.4.4

Coming Soon Page, Under Construction & Maintenance Mode by SeedProd: by SeedProd – 5.1.3
Hello Dolly: by Matt Mullenweg – 1.7.2
NinjaFirewall (WP Edition): by The Ninja Technologies Network – 4.2.6

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

Elementor Safe Mode: by Elementor.com – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: THB (฿)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: accommodation-booking (accommodation-booking)
booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #49 - /shop-3/
Cart: #50 - /cart/
Checkout: #51 - /checkout/
My account: #48 - /my-account/
Terms and conditions: #46 - /contact/

### Theme ###

Name: Embark - Child Theme
Version: 1.0
Author URL: http://themovation.com
Child Theme: ✔
Parent Theme Name: Embark
Parent Theme Version: 1.0.5
Parent Theme Author URL: http://themovation.com
WooCommerce Support: ✔

### Templates ###

Overrides: embark/woocommerce/archive-product.php version - is out of date. The core version is 3.4.0
embark/woocommerce/cart/cart.php version - is out of date. The core version is 3.8.0
embark-child/woocommerce/emails/email-styles.php version 3.3.0 is out of date. The core version is 4.0.0
embark/woocommerce/single-product.php version - is out of date. The core version is 1.6.4

Outdated Templates: ❌
					
					
						Learn how to update

### Action Scheduler ###

Complete: 15
Oldest: 2020-10-09 15:30:39 +0000
Newest: 2020-10-09 15:39:02 +0000

`
</details>

**Comment by juliaamosova** [comment]
Hi @bash-stack,

Thanks for raising the issue. It seems that errors are coming from the [Facebook for WooCommerce extension](https://woocommerce.com/products/facebook/).

The support for this extension is handled by the 3rd party developer SkyVerge. Please visit [Facebook for WooCommerce extension](https://woocommerce.com/products/facebook/) page and click on `Get Support` button on the sidebar on the right-hand side. 

Because this is not a WooCommerce Core issue, I am closing it. However, please feel free to comment back in case we missed something and we'd take another look.
