### ISSUE TITLE
Filter Products by Attributes is not showing any Attribute

### ISSUE THREAD

**Issue by agl99** [woocommerce/woocommerce#27924]
I'm using WordPress 5.5.1 and WooCommerce 4.5.2. Existing thread ([27519](https://github.com/woocommerce/woocommerce/issues/27519)) says it's resolved in 4.5.2 but I couldn't make it work.

![Widgets](https://user-images.githubusercontent.com/72689233/95675593-41d22800-0bda-11eb-8604-a35af1fa9a8a.png)

![Attributes](https://user-images.githubusercontent.com/72689233/95675595-48609f80-0bda-11eb-8daf-f5bd5d4614ad.png)

![Variations](https://user-images.githubusercontent.com/72689233/95675598-4dbdea00-0bda-11eb-9d6b-c03329c19177.png)

What am I missing here?

**Comment by TheGranadilla** [comment]
I think you must create the attribute in "Products > attributes" and then use it in your products.
It can work if you create your attribute in the product. It must be a "global" attribute. Hope I'm clear ^^

**Comment by agl99** [comment]
@TheGranadilla - Thanks a lot!
