### ISSUE TITLE
Translations loaded 2 times and too soon

### ISSUE THREAD

**Issue by Chouby** [woocommerce/woocommerce#27949]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
The WooCommerce translations are loaded 2 times. The first translation file is loaded too soon (before all plugins are loaded), 
and possibly in a wrong language.This results in performance issue (file loaded 2 times) and can create compatibility issues (the translations are loaded before all plugins are loaded and thus making inoperant a possible locale switch by a 3rd party plugin).  

**Expected behavior**
The translations must be loaded only once after all plugins are loaded.

**Actual behavior**
1. WooCommerce loads a first translation file before all plugins are loaded. This file may be in a wrong language.
2. Then it loads a second translation file.This one is always in the expected language.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
You need 2 non en-US languages to correctly reproduce, here I selected Spanish and German.
Steps to reproduce the bug:
1. Go to Settings > General, install  "German" and "Spanish" language. 
2. Select "French" as site's language
3. Go to User > Profile and select "German" as language
4. Make sure to update WooCommerce translations in both languages
5. Activate Query Monitor and on any backend screen, select "Languages" in the Query Monitor menu.

Here is some quick analysis I have made:
* The class `WC_Privacy` is instantiated as soon as WooCommerce is loaded and its constructor calls `__()` in https://github.com/woocommerce/woocommerce/blob/4.5.2/includes/class-wc-privacy.php#L31
* This fires a call to `_load_textdomain_just_in_time()` which loads the translations in the current locale. At this stage, the current locale may not be the right one if a user has set a different language in its profile or if a 3rd party plugin wants to switch it, generally in an a function hooked to `plugins_loaded`.
NB: As many files are loaded as soon as WooCommerce is loaded, it's likely that `WC_Privacy` is not the only class calling `__()` too soon ( before the action `plugins_loaded` is fired and before the call to `load_plugin_textdomain()` ), but I did not check that.

**Screenshots**
Here is a screenshot of the Query Monitor results after steps described above:
![screenshot-query-monitor](https://user-images.githubusercontent.com/3238583/95890089-98c73100-0d83-11eb-8741-69c1c8f0ef6a.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active (with the exception of Query Monitor).
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

WordPress 5.5.1
WooCommerce 4.5.2
Twenty Twenty
Query Monitor

**Comment by peterfabian** [comment]
Thanks for the bugreport, @Chouby ! 

I can confirm this problem.
