### ISSUE TITLE
Remove use of jQuery ready() in WC core code

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#27945]
As per [the jQuery docs](https://api.jquery.com/ready/):

> All of the following syntaxes are equivalent:
> ```
> $( handler )
> $( document ).ready( handler )
> $( "document" ).ready( handler )
> $( "img" ).ready( handler )
> $().ready( handler )
> ```
> 
> As of jQuery 3.0, only the first syntax is recommended; the other syntaxes still work but are deprecated. 

Therefore, we should fix the deprecated usages of `ready()` method, as we still use it in some places:

- wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php
- wp-content/plugins/woocommerce/includes/customizer/class-wc-shop-customizer.php

(and maybe more).

**Comment by anant1811** [comment]
Just adding that this also affects 3400290-zen

**Comment by DavidAnderson684** [comment]
N.B. The link doesn't say that `ready()` has been deprecated; it says that there is one preferred syntax for using it, and all others are deprecated.
