### ISSUE TITLE
Negative stock still happening when placing two orders at the same time

### ISSUE THREAD

**Issue by RezaRamezanpour** [woocommerce/woocommerce#27953]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I've read almost all issues related like #24782 #24009 #22118 but still we have negative stock and many customers complain about that. The problem is exact like #24782. 

**Expected behavior**
If the total stock is 1, when the second customer completes the payment and returns to the store, he should see an error that this product is not available or something like that.

**Actual behavior**
The message "Order Received" is displayed.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

1. Disable backorders/negative stock
2. Give the product a stock of 1
3. Place an order from two separate devices or browsers at the same time
4. See that the stock value is reduced to -1

I have reproduced this many times in localhost with fresh installation and storefront theme and only Woocommerce is active.

**Screenshots**
![image](https://user-images.githubusercontent.com/12220097/95907963-354ffa00-0da9-11eb-9680-146443e9da73.png)

![image](https://user-images.githubusercontent.com/12220097/95908768-5b29ce80-0daa-11eb-8bc2-054e96c571c8.png)

![image](https://user-images.githubusercontent.com/12220097/95908156-8233d080-0da9-11eb-83c4-5f83194d13ea.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only the WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): http://localhost/wordpress
Site address (URL): http://localhost/wordpress
WC Version: 4.1.0
REST API Version: ✔ 1.0.7
WC Blocks Version: ✔ 2.5.16
Action Scheduler Version: ✔ 3.1.5
WC Admin Version: ✔ 1.1.1
Log Directory Writable: ✔
WP Version: 5.5.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Ubuntu)
PHP Version: 7.4.11
PHP Post Max Size: 120 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 8.0.21-0ubuntu0.20.04.4
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.1.0
WC Database Prefix: wp_
Total Database Size: 11.07MB
Database Data Size: 8.19MB
Database Index Size: 2.88MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_OSA_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_OSA_cart: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_OSA_cartmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_OSA_error_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_OSA_view_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentLikes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_dokan_announcement: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_follow_store_followers: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_dokan_orders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_dokan_product_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_refund: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_report_abuse_reports: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_dokan_rma_conversations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_rma_request: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_rma_request_product: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_shipping_zone_locations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_vendor_balance: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_withdraw: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.05MB + Index: 0.05MB + Engine InnoDB
wp_postmeta: Data: 1.52MB + Index: 0.52MB + Engine InnoDB
wp_posts: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_shopmagic_automation_outcome: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_shopmagic_automation_outcome_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_shopmagic_guest: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_shopmagic_guest_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_shopmagic_optin_email: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 1.52MB + Index: 0.56MB + Engine InnoDB
wp_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpuf_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpuf_transaction: Data: 0.02MB + Index: 0.06MB + Engine InnoDB

### Post Type Counts ###

attachment: 20
nav_menu_item: 7
page: 23
post: 2
product: 17
product_variation: 10
revision: 9
shop_order: 11

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce: by Automattic – 4.1.0 (update to version 4.5.2 is available)
افزونه پرداخت امن زرین‌پال برای ووکامرس: by Masoud Amini – 4.6.1 (this is a sandbox payment plugin)

### Inactive Plugins (13) ###

Dokan: by weDevs – 3.0.9
Dokan Pro - business: by weDevs
WooCommerce Admin: by WooCommerce – 1.1.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: IRT (تومان)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #10 - /shop/
Cart: #11 - /cart/
Checkout: #12 - /checkout/
My account: #13 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.5.6 (update to version 2.8.0 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Canceled: 3
Oldest: 2020-09-24 09:41:32 +0330
Newest: 2020-10-04 09:06:35 +0330

Complete: 30
Oldest: 2020-09-24 09:41:32 +0330
Newest: 2020-10-13 22:29:25 +0330

`
</details>

**Comment by ChiefWigs1982** [comment]
I'm having the exact same issue.

I noticed from your details you're using a "sandbox payment plugin" - I'm not using a plugin for that - I've simple set the paypal settings (WooCommerce "PayPaly Standard" settings) to use the PayPal API.

If I mane the product I'm testing with have a price of $0, then there's obviously no purchase involved, and that works correctly - the first browser I click purchase in will complete the sale and the second one will fail as expected.

However, as soon as there's a payment required, it falls over. There must need to be some more checking in place. If I set the price to $1, then both browsers will send me to PayPal (sandbox) from the checkout page, and both will let me complete the purchase without failing.

**Comment by peterfabian** [comment]
Hi folks, 

this should be considerably improved with WooCommerce 4.3, where we introduced `wc_reserved_stock` table to reserve stock while customers are paying for the order on PayPal (or another website). I can see from the system status report that you're using WC 4.1. Please try the up to date version and let us know if you still see the same problem.

**Comment by ChiefWigs1982** [comment]
I'm using WP Version 5.5.1 with WooCommerce Version 4.6.1.

I've seen the wc_reserved_stock table, but it's empty - I checked it while testing the purchases and it never had any content in it at all, so maybe something's not working with that?

**Comment by ChiefWigs1982** [comment]
Ok, so I hadn't set the "Hold Stock" variable in WC Settings > Products > Inventory, so I guess that's why the reserved_stock table wasn't populating. I've now set that to 2 minutes and I can see items going in and out of that table, but I'm still getting products overselling and ending up on backorder eventhough it's disabled.

**Comment by TheRealLauch** [comment]
Hey, still have the same issue!

Cant reproduce on staging site, but i still get product variants with -1 to -6QTY even tho backorder is deactivated. 

Using Divi Theme with Woocommerce and Paypal Checkout Plugin on newest state.

**Comment by CaroSo73** [comment]
Hi! I do have the same issue, stock going in negative eventho back order is desactivated.
Using Storefront theme 3.4.0 and woocommerce 4.8.0 and Wordpress 5.6.1

**Comment by lp-ben** [comment]
Has there been any sort of fix for this yet? I've got this issue happening on multiple sites.

**Comment by jonwigham** [comment]
> Has there been any sort of fix for this yet? I've got this issue happening on multiple sites.

Which payment method(s) are you using? I used to use the "PayPal Express" method but I switched over to "PayPal Standard" and have almost no double sales now. The user experience with the Standard one isn't quite as nice as with Express, but it seems to play nicer with the stock management settings...

**Comment by CaroSo73** [comment]
> > Has there been any sort of fix for this yet? I've got this issue happening on multiple sites.
> 
> Which payment method(s) are you using? I used to use the "PayPal Express" method but I switched over to "PayPal Standard" and have almost no double sales now. The user experience with the Standard one isn't quite as nice as with Express, but it seems to play nicer with the stock management settings...

I use Pay Pal Standard and Stripe and I still got the issue :(

**Comment by lp-ben** [comment]
> > Has there been any sort of fix for this yet? I've got this issue happening on multiple sites.
> 
> Which payment method(s) are you using? I used to use the "PayPal Express" method but I switched over to "PayPal Standard" and have almost no double sales now. The user experience with the Standard one isn't quite as nice as with Express, but it seems to play nicer with the stock management settings...

I'm using Authorize.net and other processors, no PayPal of any sort.

**Comment by TheRealLauch** [comment]
Anyone tested With newest WooCommerce and WordPress Versions?

**Comment by CaroSo73** [comment]
> Anyone tested With newest WooCommerce and WordPress Versions?

I'm going to update to woocommerce 5.0 (I already use the latest WordPress version 5.6.2) on next Monday. After few days of running the updated system, I'll be back with an answer ! :)

**Comment by ldr2273** [comment]
Hi @peterfabian!

We're still seeing some reports of this come through, and I wanted to check and see if this was anything we could further look into? I personally have not been able to replicate, but I'm getting reports from customers who have updated to 5.0. TIA!

**Comment by peterfabian** [comment]
Thanks for reporting the issue, folks. It would be helpful to us if you could include the system status report with your reports as we might be able to see if there is any plugin that is appearing repeatedly for this problem and what storage engine you folks are using in your database tables. 

The problem is somewhat tricky as we can't really be sure the configurations people are using support transactions at the database level (different table engines, etc), which makes it tricky to implement a solution for everyone. As mentioned above, we've tried to tackle this problem in 4.3 by introducing db level atomicity via MySQL tricks (INSERT INTO SELECT with subqueries using SELECT ... FOR UPDATE), but it seems we might need to revisit it to see if it's working as we intended. cc @vedanshujain

**Comment by CaroSo73** [comment]
> Thanks for reporting the issue, folks. It would be helpful to us if you could include the system status report with your reports as we might be able to see if there is any plugin that is appearing repeatedly for this problem and what storage engine you folks are using in your database tables.
> 
> The problem is somewhat tricky as we can't really be sure the configurations people are using support transactions at the database level (different table engines, etc), which makes it tricky to implement a solution for everyone. As mentioned above, we've tried to tackle this problem in 4.3 by introducing db level atomicity via MySQL tricks (INSERT INTO SELECT with subqueries using SELECT ... FOR UPDATE), but it seems we might need to revisit it to see if it's working as we intended. cc @vedanshujain

[statut_systeme_sdd.txt](https://github.com/woocommerce/woocommerce/files/6077294/statut_systeme_sdd.txt)
Hi! Here is the system status report, I hope it helps for analyse and fix the issue.

**Comment by hughcawley** [comment]
Has this been resolved yet? Seems like the same issue has been causing issues and been in cases for years now? Have had 2 run ins with the error over the past week. No paypal used, just Stripe, backorders not allowed.

**Comment by barryhughes** [comment]
I'm sorry to hear that some of you are still experiencing problems. Unfortunately, so far, I am unable to replicate.

@CaroSo73 thanks for sharing your sysinfo...@hughcawley would you be able to share yours? It may help us to identify patterns for those cases where this issue still occurs.

**Comment by Mayb3Nots** [comment]
Hi i am having issue with this too. This is a problem even if the stock doesnt goes negative beacuse when two customer orders the same thing at the same time it will both minus the stock at the same time that means the stock is now more than what i currently have.

I am using WooCommerce 5.5.2, NativeFarm theme, Payment method used : Stripe, BillPlz and iPay88

**Comment by cb5466** [comment]
Same issue in 2024 Wordpress 6.5.5 and woocommerce 9.0.2.
I guess it will never be solved
