### ISSUE TITLE
Script sh ./bin/prefix-vendor-namespaces.sh handling the post-install-cmd event returned with error code 127

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#27984]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ ] I have have carried out troubleshooting steps and I believe I have found a bug.
related to the dev repo and not the running of Woo
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
composer install scripts will not finished... so autoloader is not generated and so the plugin will not run due to fatal errors from missing classes... ie

>Fatal error: Uncaught Error: Class 'Automattic\WooCommerce\Vendor\League\Container\Container' not found in C:\Users\helga\Local Sites\sandbox\app\public\wp-content\plugins\woocommerce\src\Internal\DependencyManagement\ExtendedContainer.php on line 16

**Expected behavior**
`composer install` will complete the `post-install-cmd` scripts

**Actual behavior**
`post-install-cmd` fails and Autoloader not generated:

```
>sh ./bin/prefix-vendor-namespaces.sh
: not foundx-vendor-namespaces.sh: 2: ./bin/prefix-vendor-namespaces.sh:

: not foundx-vendor-namespaces.sh: 16: ./bin/prefix-vendor-namespaces.sh: }
: not foundx-vendor-namespaces.sh: 17: ./bin/prefix-vendor-namespaces.sh:
: not foundx-vendor-namespaces.sh: 14: ./bin/prefix-vendor-namespaces.sh: {
: not foundx-vendor-namespaces.sh: 19: ./bin/prefix-vendor-namespaces.sh:
: not foundx-vendor-namespaces.sh: 22: ./bin/prefix-vendor-namespaces.sh:
find: missing argument to `-exec'
'ind: unknown predicate `-delete
: not foundx-vendor-namespaces.sh: 25: ./bin/prefix-vendor-namespaces.sh:
sed: can't read .bak: No such file or directory
: No such file or directoryue/container/composer.json
: not foundx-vendor-namespaces.sh: 29: ./bin/prefix-vendor-namespaces.sh:
Script sh ./bin/prefix-vendor-namespaces.sh handling the post-install-cmd event returned with error code 127
```

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. `git pull origin master`
2. run `composer install`

**Screenshots**
![image](https://user-images.githubusercontent.com/507025/96200748-e83e6600-0f17-11eb-8739-9b4667d0212c.png)

I'm using the Ubuntu subsystem in Windows Terminal. Generally running the command lines in "faux" Ubuntu has helped get around issues I've experienced with the build scripts and Windows, but I can't seem to get around this one. (I know this screenshot says don't run as root, but I tried it without `sudo` as well and got the same)

**Comment by Konamiman** [comment]
Hi @helgatheviking, could you please try the following and tell us if it works for you:

1. Open the `bin/prefix-vendor-namespaces.sh` file

2. Replace this line:

```
find . /vendor/league/container -name "*.php.bak" -type f -delete
```

with:

```
find ./vendor/league/container -name "*.php.bak" -type f -exec rm {} \;
```

3. Run `composer install` again

**Comment by helgatheviking** [comment]
Thanks @Konamiman sadly I am getting the exact same error.

**Comment by Konamiman** [comment]
Hey @helgatheviking,

I've tried the script in my Windows machine using WSL and it worked as expected, only that I got some _sed: can't read .bak: No such file or directory_ errors that can be safely ignored. I'm using WSL 2, though; are you on WSL 1 by chance?

Anyway, I would like to point out that this script is a temporary solution to add a unique prefix to the `league/container` package in order to prevent conflicts with other extensions using different versions of the same package; we plan to replace this with a more proper solution and then this script will go away.

**Comment by claudiosanches** [comment]
Hello @helgatheviking, thanks for reporting this issue, Rodrigo already solved it in https://github.com/woocommerce/woocommerce/pull/28038
I'm closing for now, but please let me know if the issue persist on your end even after this fix. Thanks!

**Comment by helgatheviking** [comment]
awesome... Thanks Claudio!

**Comment by helgatheviking** [comment]
@claudiosanches  Hi Claudio... I'm stuck again here. I've got the latest from `master` (so including #28038) and have updated my Linux subsystem to WSL2, but still getting the same error and unable to generate the autoloader.

```
Generating autoload files
> sh ./bin/prefix-vendor-namespaces.sh
: not foundx-vendor-namespaces.sh: 2:

: not foundx-vendor-namespaces.sh: 16: }
: not foundx-vendor-namespaces.sh: 17:
: not foundx-vendor-namespaces.sh: 14: {
: not foundx-vendor-namespaces.sh: 19:
: not foundx-vendor-namespaces.sh: 22:
find: missing argument to `-exec'
'ind: unknown predicate `-delete
: not foundx-vendor-namespaces.sh: 25:
: No such file or directoryue/container/composer.json
: not foundx-vendor-namespaces.sh: 29:
Script sh ./bin/prefix-vendor-namespaces.sh handling the post-install-cmd event returned with error code 127
```

**Comment by helgatheviking** [comment]
FWIW, I'm still failing with this. This _may_ be due to attempting to run php 8 for some testing. 

```
cabox@new:~/workspace/wp-content/plugins/woocommerce$ composer install
Deprecation Notice: Required parameter $path follows optional parameter $schema in phar:///usr/local/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/UndefinedConstraint.php:62
Deprecation Notice: Required parameter $path follows optional parameter $schema in phar:///usr/local/bin/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/UndefinedConstraint.php:108
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in phar:///usr/local/bin/composer/src/Composer/Repository/RepositoryManager.php:130
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in phar:///usr/local/bin/composer/src/Composer/Repository/RepositoryManager.php:130
A script named bin would override a Composer command and has been skipped
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
PHP Fatal error:  Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/DefaultPolicy.php:84
Stack trace:
#0 [internal function]: array_merge()
#1 phar:///usr/local/bin/composer/src/Composer/DependencyResolver/DefaultPolicy.php(84): call_user_func_array()
#2 phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php(384): Composer\DependencyResolver\DefaultPolicy->selectPreferredPackages()
#3 phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php(736): Composer\DependencyResolver\Solver->selectAndInstall()
#4 phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php(228): Composer\DependencyResolver\Solver->runSat()
#5 phar:///usr/local/bin/composer/src/Composer/Installer.php(474): Composer\DependencyResolver\Solver->solve()
#6 phar:///usr/local/bin/composer/src/Composer/Installer.php(228): Composer\Installer->doInstall()
#7 phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php(121): Composer\Installer->run()
#8 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(241): Composer\Command\InstallCommand->execute()
#9 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(843): Symfony\Component\Console\Command\Command->run()
#10 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(193): Symfony\Component\Console\Application->doRunCommand()
#11 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(254): Symfony\Component\Console\Application->doRun()
#12 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#13 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(103): Symfony\Component\Console\Application->run()
#14 phar:///usr/local/bin/composer/bin/composer(56): Composer\Console\Application->run()
#15 /usr/local/bin/composer(24): require('...')
#16 {main}
  thrown in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/DefaultPolicy.php on line 84

Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/DefaultPolicy.php:84
Stack trace:
#0 [internal function]: array_merge()
#1 phar:///usr/local/bin/composer/src/Composer/DependencyResolver/DefaultPolicy.php(84): call_user_func_array()
#2 phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php(384): Composer\DependencyResolver\DefaultPolicy->selectPreferredPackages()
#3 phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php(736): Composer\DependencyResolver\Solver->selectAndInstall()
#4 phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php(228): Composer\DependencyResolver\Solver->runSat()
#5 phar:///usr/local/bin/composer/src/Composer/Installer.php(474): Composer\DependencyResolver\Solver->solve()
#6 phar:///usr/local/bin/composer/src/Composer/Installer.php(228): Composer\Installer->doInstall()
#7 phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php(121): Composer\Installer->run()
#8 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(241): Composer\Command\InstallCommand->execute()
#9 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(843): Symfony\Component\Console\Command\Command->run()
#10 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(193): Symfony\Component\Console\Application->doRunCommand()
#11 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(254): Symfony\Component\Console\Application->doRun()
#12 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#13 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(103): Symfony\Component\Console\Application->run()
#14 phar:///usr/local/bin/composer/bin/composer(56): Composer\Console\Application->run()
#15 /usr/local/bin/composer(24): require('...')
#16 {main}
  thrown in phar:///usr/local/bin/composer/src/Composer/DependencyResolver/DefaultPolicy.php on line 84
cabox@new:~/workspace/wp-content/plugins/woocommerce$
```

**Comment by helgatheviking** [comment]
@claudiosan Still experiencing https://github.com/woocommerce/woocommerce/issues/27984#issuecomment-718058407 with PHP 7.4 (on Windows Linux subsystem WSL 1.. though most of the time it runs all Linux commands just fine).

**Comment by Konamiman** [comment]
Hi @helgatheviking,

This script has been removed in https://github.com/woocommerce/woocommerce/pull/28147. That pull request will be included in WooCommerce 4.9, which will be released in January. Is using WSL2 meanwhile an option for you?

**Comment by helgatheviking** [comment]
Awesome! I can pull that down right now. I'm usually working locally on your `master` branch. I tried WSL2 but there was no way to `watch` files that were stored in my windows folders (which is currently where all my plugins are stored). Changes in the windows files don't fire change events in Ubuntu? That seemed a fairly common complaint, and the workarounds looked pretty complex so I rolled back to WSL1. Thanks for fixing this!

**Comment by Konamiman** [comment]
As a personal suggestion and based on my own experience: WSL2 works great when you take the reverse approach, that is, keeping all the files inside Linux. That way everything is self-contained where all the tooling is running, and you can still access your files easily from Windows: if you use VS Code, there's a built-in remote extension; and if you use anything else, you can access files via ` \\wsl$\<distro name>`. That's how I am currently working in WooCommerce (with PHPStorm) and it works wonderfully.

**Comment by helgatheviking** [comment]
Thanks Néstor! I'd read similar things when researching the problem but couldn't figure it out at the time and had to get stuff moving! But when I have some more time I will have to check out it.

**Comment by Konamiman** [comment]
Great. I'll close this for now then.
