### ISSUE TITLE
Experienced senior woo-commerce APIs developer NEEDED

### ISSUE THREAD

**Issue by mohammad0omar** [woocommerce/woocommerce#27996]
Hello,

 For a very interesting remote freelance project, we are Looking for an Experienced senior woo-commerce APIs developer, experienced in writing plugins to add/manage APIs and core functionalities.

Communication skills and a portfolio are a must, please reach to me through my email 
mohammad0omar**[at]**outlook**[dot]**com (change **at** and **dot** with their real values, using this to minimize any risk in web crawlers)

**Comment by tammullen** [comment]
Closing as GitHub should be treated as a place to report confirmed bugs only.
