### ISSUE TITLE
Add tracks for manual Woo extension installation

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#27992]
Check if it is possible to add new Tracks events to fire when

- a Woo extension is manually installed via the WPAdmin Plugins menu
- a Woo extension is manually activated via the WPAdmins Plugins menu

Maybe based on plugin author? If not, start with WC Pay and WC Ship.

**Comment by roykho** [comment]
Hmm is this needed in WC core? I believe each Woo extension themselves should announce its own installation. What do you think?

**Comment by peterfabian** [comment]
I see your point, yeah, that perhaps makes a bit more sense. cc @oneillo 
Should we close this one, then and open issues for the extensions we're taking care of?

**Comment by oneillo** [comment]
@peterfabian makes sense. If we can get our owned extensions announcing when they are installed, starting with our top priorities, that would be helpful. Objective here was to provide visibility into one of the main paths for adding and activating extensions into Woo stores for future marketing automations / analyses.

**Comment by rrennick** [comment]
> Should we close this one, then, and open issues for the extensions we're taking care of?

Closing as this will be handled elsewhere.
