### ISSUE TITLE
If "hide out of stock" is enabled, then product category count is wrong if there is a product out of stock

### ISSUE THREAD

**Issue by gevcen** [woocommerce/woocommerce#28002]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Assumptions**
Assume that you define the WooCommerce settings to hide products that are out of stock.
Assume also that you have a category with 2 products : one in stock, and one out of stock.

**Expected behavior**
If a product if out of stock, it should not be counted in the number of products on Shop page (sub-categories only)

**Actual behavior**
Go to the Shop page with sub-categories defined only, and you'll see "2 products" written below the name of the category. And then if you open the category, the user finds only 1 product (as expected).

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug: see above

**Screenshots**
Video : https://sgevcen.tinytake.com/tt/NDczODM3Nl8xNDk5Mjg5Mg

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by tammullen** [comment]
Hi @gevcen 

Thank you for reporting the issue. However, an issue has been reported previously here which I believe is the same problem https://github.com/woocommerce/woocommerce/issues/25375. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
