### ISSUE TITLE
wc_get_order vs wc_get_orders -- wrong data

### ISSUE THREAD

**Issue by WebMedic-X** [woocommerce/woocommerce#28029]
Hi,

Order in question has the following total: 23.00

When using wc_get_order, example:

$order = wc_get_order(ORDER_ID);
echo $order->get_total();

We get 17.50

However when querying using:

$orders = wc_get_orders($args);

foreach($orders as $order) {
    echo $order->get_total();
}

We get the correct amount of 23.00

What could be causing this? any idea?

Thank you

**Comment by Konamiman** [comment]
Hi @WebMedic-X,

Thank you for your bug report. Unfortunately I haven't been able to reproduce it on my side. 

To start with, could you please try the steps in [our self-service guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/), especially the part about disabling other extensions?

If that didn't help, please provide us with more details about your environment, including more details about the order and the products it contains. Thank you!

**Comment by WebMedic-X** [comment]
Hi @Konamiman 

Thanks for getting back to me

We found out its actually a conflict with Booster plugin for WooCommece 

In touch with their support to get it resolved

Thank you
