### ISSUE TITLE
meta-boxes-product-variation.js file get_variations_fields function issue

### ISSUE THREAD

**Issue by SevenAcreFarm** [woocommerce/woocommerce#28020]
**REOPENING ISSUE** (#27442)

This issue is still not resolved, and has persisted for over two months at this point. Reading @marke123 's comments above it seems clear what needs to be tested. The plugin is "[WooCommerce Min Max Totals and Quantities](https://ignitewoo.com/woocommerce-extensions-plugins-themes/woocommerce-minimum-maximum-totals-quantities/)" Version 2.1.12 | By IgniteWoo. 

From my understanding the issue resides on the WooCommerce side and is not something that can be resolved from the plugin vendor side.

When adjusting the min/max/increment quantities (an array) on a per product level within the variations of a product, WooCommerce freezes up and fails to save or reload as expected, and I receive the following NGINX errors (below).

@juliaamosova What can we do to get this moving in a direction toward resolution? As a customer of WooCommerce I have gone from version 4.4.1 to 4.6.0, and am now up to WordPress 5.5.1. As a customer of IgniteWoo I have updated to the latest available 2.1.12.

The vendor states "Apparently this bug was reported back in March and fixed in WC 4.0.1, however the same bug is now back again and it has been reported to the WC devs already - again. Hopefully they can get that fixed in v4.4.2."

I could not find the git issue for that, but have to assume the comment is correct. I can only surmise that this issue (#27442) is in response to the problem and is not currently being addressed.

As a customer of WordPress, WooCommerce, and IgniteWoo -- I need a resolution to this issue. 

Please advise.

**Errors:**
> 2020/10/20 17:44:50 [error] 24254#0: *15972 FastCGI sent in stderr: "PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.p
> 2020/10/20 17:44:50 [error] 24254#0: *15972 FastCGI sent in stderr: "ordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852" while reading response header from upstream, client: X.X.X.X, server: sevenacre.farm, request: "POST /wp-admin/admin-ajax.php?_fs_blog_admin=true HTTP/1.1", upstream: "fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: "sevenacre.farm", referrer: "https://sevenacre.farm/wp-admin/post.php?post=871&action=edit"
> 2020/10/20 17:52:53 [error] 24254#0: *16106 FastCGI sent in stderr: "PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.p
> 2020/10/20 17:52:53 [error] 24254#0: *16106 FastCGI sent in stderr: "ordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852PHP message: PHP Warning:  in_array() expects parameter 2 to be array, null given in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-minimum-order-total-quantity/classes/class-wc-minimum-cart-total-qty-product-admin.php on line 852" while reading response header from upstream, client: X.X.X.X, server: sevenacre.farm, request: "POST /wp-admin/admin-ajax.php?_fs_blog_admin=true HTTP/1.1", upstream: "fastcgi://unix:/opt/bitnami/php/var/run/www.sock:", host: "sevenacre.farm", referrer: "https://sevenacre.farm/wp-admin/post.php?post=871&action=edit"

_Originally posted by @SevenAcreFarm in https://github.com/woocommerce/woocommerce/issues/27442#issuecomment-713041286_

**Comment by tammullen** [comment]
Hi @SevenAcreFarm 

Thank you for reporting the issue. However, as you noted this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/27442. We are closing your issue in favor of the previously submitted. 

Can you Please continue sharing your feedback there if needed.
