### ISSUE TITLE
Woocommerce 4.70 changes  made to the templates and i have a "bug" and a question

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#28032]
Hi

There are changes made to the template in 4.70 B1 and i must say i am partly happy with these

1) The content-product_cat.php is renamed to content-product-cat.php   Since we have been overriding this template part for years now I  wonder how long is woocommerce gonna call the old content-product_cat.php file after 4.70? 

in order to be compatible with earlier versions of woocommerce I now have to maintain the old file content-product_cat.php as any version of woocommerce below 4.70 is not calling the new file content-product-cat.php

2) If a user does not set a thumbnail but only gallery images the thumbnail is replaced by the first image in the gallery. A nice feature but now that same feature does not apply to the shop listing images. I suggest to use the same way when shop images are presented.

related https://github.com/woocommerce/woocommerce/pull/27289

The question i have is why did this feature even got into the build? Simply having users set the thumbnail image for the post would have been the better way to go and stay. This is how we have been doing it for ages now. Why suddenly this change? It does not add anything. If one can set gallery images one can also set a thumbnail. I am realy missing the point for this code change.

The problem i have with this change is as follow: if you do this for the single image it should also work on the shop, related, upsell or any other product listings showing the product image.

Now we get the default image to show when no thumbnail has been set in the shop page, upsel, related. So this is only half of the solution.  I know how to fix this myselves by overriding the woocommerce_template_loop_product_thumbnail action  but i believe this change should also gotten into the default core code.

Thank you and please change that aswell.

**Comment by BackuPs** [comment]
Another thing to add to this..... if users override the product-image.php template they also have to maintain compatible with users wo do not yet have updated to the latest woocommerce build otherwise they get the error that the variable $post_thumbnail_id does not exist. So themes can't remove that line of code

$post_thumbnail_id = $product->get_image_id();

 which is in the template until 4.70 as they do not know when the users update the theme and or woocommerce and in which order.

This is a bit struggling with the changes.  It would have been better if this code had gotten into the product-image.php file in 4.70
`	if ( ! $post_thumbnail_id ) {
	$gallery_image_ids = $product->get_gallery_image_ids();
	if ( ! empty( $gallery_image_ids ) ) {
		$post_thumbnail_id = array_shift( $gallery_image_ids );
	}
	}
`

and this into the thumbnail php file

`	$post_thumbnail_id = $product->get_image_id();
	$attachment_ids = '';
	$attachment_ids = $product->get_gallery_image_ids();

	if ( $attachment_ids && ! $product->get_image_id() ) {
		array_shift( $attachment_ids );
	}
`

Instead of parsing the args for the images the way it is done now !

**Comment by TheThemeBuilders** [comment]
May I say we are encountering the same issues as outlined by "Backups".  The logic behind these changes to the woo templates, which appear to us to be not well thought through and very arbitrary, is not evident.    We cannot really add to what he has said and his code suggestions appear to be elegant solutions to a problem you created.  

While outside of the purview of this pull given the recent onslaught of changes in Woo and its parent WordPress we developers would really like a bit more breathing time between fundamental updates.   Stop the madness!   While we can keep up even with these shenanigans it is dreadful to website owners who we know from all our support requests are floundering.  Many woo store owners are really struggling with the flurry of recent changes, view many of these changes as impediments to their business and more and more are asking us for easier and simpler to use alternatives.  

We have hundreds of emails from customers (we have a very large customer base across our theme and hosting platforms) complaining about woo updates and requesting alternatives.  Your on your way to updating yourself out of a customer base if you keep this up.

Thank you Backups, and Claudio we will follow carefully your replies.

**Comment by rrennick** [comment]
> I wonder how long is woocommerce gonna call the old content-product_cat.php file after 4.70?

The file `/theme-name/content-product_cat.php` is the standard WordPress template naming convention so that will continue to be supported indefinitely. There is no timeline for removing support for that file name in the `woocommerce` folder.

> I now have to maintain the old file content-product_cat.php as any version of woocommerce below 4.70 is not calling the new file content-product-cat.php

You can update `woocommerce/content-product_cat.php` to be `include './content-product-cat.php';` effectively eliminating the need to maintain two versions.

>  A nice feature but now that same feature does not apply to the shop listing images. I suggest to use the same way when shop images are presented.

That's a good suggestion. Could you create a new issue for that specifically as it's a separate issue from the template file names.

**Comment by BackuPs** [comment]
> You can update woocommerce/content-product_cat.php to be include './content-product-cat.php'; effectively eliminating the need to maintain two versions.

I am not 100% sure what you mean by this... But whatever i try this will not work as the variable $category is not transfered calling the /content-product-cat.php from /content-product_cat.php and thus producing a error that the variable does not exist !

Not even if i try to call it like this

wc_get_template( 'content-product-cat.php', $category ); from within conten-product_cat.php


Notice: Undefined variable: category in /public/wp-content/themes/twentytwentyone/woocommerce/content-product-cat.php 

So i have to maintain two templates in order to stay compatible.

**Comment by BackuPs** [comment]
> That's a good suggestion. Could you create a new issue for that specifically as it's a separate issue from the template file names.

As per your request I did here.

https://github.com/woocommerce/woocommerce/issues/28053

**Comment by rrennick** [comment]
> But whatever i try this will not work as the variable $category is not transfered calling the /content-product-cat.php from /content-product_cat.php and thus producing a error that the variable does not exist !

If you use `include` it does. `include` is the equivalent of insert the contents of this file here. Try this

```
$ cat a.php
<?php

include './b.php';

echo $b . PHP_EOL;
$ cat b.php
<?php 

$b = 'hello world';
$ php -f a.php
hello world
```

**Comment by BackuPs** [comment]
You are right.  Thanks for that solution !

**Comment by claudiosanches** [comment]
Hello @BackuPs. Seems like Ron already addressed most of the issues here, I'll follow up in #28053 so we make a fix before this release, I'm going to close this now issue number one is solved. Thank you for submitting this report and for starting this conversation.

@TheThemeBuilders please no reason for this tone, we are all here open for conversion and to improve, if you find some issue or bug, please feel free to open an issue here on GitHub, we'll be happy to work on it or clarify anything question.
