### ISSUE TITLE
Revenue in Sales Report from API Response not same as Revenue in Sales Report on WooCommerce

### ISSUE THREAD

**Issue by ishmalsw** [woocommerce/woocommerce#28034]
So, I have a backend system made on laravel that is synced with WooCommerce API for the store itself. Laravel Application accesses the sales reports from the endpoint "reports/sales" on the REST API. The revenue there in the response is not accurate, I should say not even close to the revenue that is shown on WooCommerce Dashboard.

The plugin that is used on WooCommerce is PriceBasedCountry plugin that converts all currencies to the default currency. 

I have been told by the Price Based country success team that the WooCommerce API is using their same plugin to convert currencies and then send back the response.

**Comment by rrennick** [comment]
@ishmalsw The api that corresponds to the dashboard analytics is `/wp-json/wc-analytics/`. The reports in `wp-json/wc/` are the old reports under WooCommerce -> Reports.

I'll close this issue. If you do find inconsistencies between the dashboard reports and the analytics endpoint, please let us know and we can re-open the issue.

**Comment by ishmalsw** [comment]
Hello Ron. I appreciate the quick response. That clears a lot of things up.
Could you be kind enough to refer me a link to Wordpress Analytics
documentation? I can't seem to find an analytics endpoint description on
https://developer.wordpress.org/rest-api/

Thanks

**Comment by rrennick** [comment]
@ishmalsw The 'wc-analytics` route is maintained in https://github.com/woocommerce/woocommerce-admin.
