### ISSUE TITLE
Sorting link on Product Admin List Table requires edit_others_pages capability

### ISSUE THREAD

**Issue by pjv** [woocommerce/woocommerce#28049]
A product manager on a site I manage was unable to see the `sorting` link on the All Products admin list table. I had to search the source to figure out what permission was required for a user to see that link and when I found it:

https://github.com/woocommerce/woocommerce/blob/3f61afe5337c4fbb94a6b14b919cda3795ea4e05/includes/admin/list-tables/class-wc-admin-list-table-products.php#L419-L420

I was surprised.

Before I file a PR to change that capability to `current_user_can('edit_products')` can anyone tell me if I am missing something and the `edit_others_pages` capability actually does make sense here?

**Comment by tammullen** [comment]
Hi @pjv 

The number of details you provided is not enough for us to work with and identify what could be going on.

Please provide us with steps to reproduce the issue on our end. Can you clarify where in WooCommerce you are referring to ideally with screenshots - step by step instructions for us to recreate your use case.

Are you referring to the using the `Shop Manager` user role (https://docs.woocommerce.com/document/roles-capabilities/#section-2) to sort the list of products in WP Admin / WooCommerce / Products / All Products?

Finally, it will be great if you could share your current System Status Report. You can get it by navigating to the WooCommerce / Status section of your site. Once there, click on the Get system report button and then copy it by clicking on the Copy for support button. Then paste it here in a comment.

**Comment by pjv** [comment]
Hi @tammullen,

I'm not reporting a problem on a site or asking for support.

I am just reporting what looks to me like a strange permission / capability in the Woo source in order to show the link that allows a user to sort products in the "All Products" admin list table page.

Users whose role does not grant the `edit_others_pages` capability cannot see the "sorting" link and that seems like a strange capability to require in order to show that link. I think it would make more sense for any user who has `edit_products` to be able to see that link and before I create a PR to change that permission, I'm simply asking whether I am missing some logic to having that sort function behind the `edit_others_pages` capability.

**Comment by tammullen** [comment]
Thanks @pjv for the extra information.

I've marked this to get feedback from one of the WooCommerce Core developers.

**Comment by rrennick** [comment]
@pjv The correct capability would be `edit_others_products`.

**Comment by pjv** [comment]
@rrennick that makes sense. I'm going to create a PR and will reference this issue.

**Comment by seant100** [comment]
This issue still persists. The "Sorting" link is showing now, but you still need the capaility "edit Others Pages" to do the actual drag and drop sorting

**Comment by oginomizuho** [comment]
Still present in the current codebase. The capability check is inconsistent across three locations:

- `class-wc-admin-list-table-products.php`: `edit_others_products`
- `class-wc-admin-assets.php`: `edit_others_pages`
- `class-wc-ajax.php`: `edit_products`

Currently, extra code has been added to the theme solely to enable sorting while maintaining proper permissions. This should be fixed as soon as possible.
