### ISSUE TITLE
Woocomerce 4.6.1 change .htaccess cause fall down site

### ISSUE THREAD

**Issue by samgomezro88** [woocommerce/woocommerce#28060]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
This morning in my site the woocommerce plugin made an automatic update to 4.6.1. change the .htaccess file and delete this line from the file (AddHandler application/x-httpd-ea-php74 .php .php7 .phtml), this makes the website falls down.

**Expected behavior**
Don't change the .htaccess file deleting lines dont related to Woocommerce behavior

**Actual behavior**
To fix the issue we just change the .htaccess file

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**

Just the update of the new plugin. Woocommerce was the only plugin that get an update today.

**Screenshots**
![CpanelError](https://user-images.githubusercontent.com/68862275/96893879-cc275100-1450-11eb-8bd5-6e19d2aa10bf.png)
![ErrorMaki](https://user-images.githubusercontent.com/68862275/96893884-ccbfe780-1450-11eb-90da-0a77681c01c8.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
> change the .htaccess file and delete this line from the file (AddHandler application/x-httpd-ea-php74 .php .php7 .phtml), this makes the website falls down.

@samgomezro88 This wouldn't have been added by WooCommerce. See https://github.com/woocommerce/woocommerce/search?q=AddHandler&type=code
