### ISSUE TITLE
"Children" misspelled as "Childre"

### ISSUE THREAD

**Issue by Red-Capes-IT** [woocommerce/woocommerce#28066]
https://github.com/woocommerce/woocommerce/blob/3f61afe5337c4fbb94a6b14b919cda3795ea4e05/includes/class-wc-product-variable.php#L416

**Comment by juliaamosova** [comment]
Hi @Red-Capes-IT,

Thank you for taking the time to report this bug, we really appreciate your help. Please feel free to submit a PR to fix it.

**Comment by ibonkonesa** [comment]
Hi, I can do this! Should I PR to master directly from my fork?

**Comment by rrennick** [comment]
> Should I PR to master directly from my fork?

@ibonkonesa Yes. Then visit your fork on Github and you should see a notice with a button to create the PR.

**Comment by NicholasMacedo** [comment]
Thank you for noticing my PR. When accepting the PR, could you please add the hacktoberfest-accepted label. Thanks. :)

**Comment by roykho** [comment]
> Thank you for noticing my PR. When accepting the PR, could you please add the hacktoberfest-accepted label. Thanks. :)

I don't believe this is needed. Hacktoberfest applies to all open source repos IIRC.
