### ISSUE TITLE
Payment Gateway can't automatic update the Order Status

### ISSUE THREAD

**Issue by ktchan1811** [woocommerce/woocommerce#28075]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
At the moment, I am using an local payment gateway (M'sia) and not using Paypal or Stripe. I am facing the issue of Woocommerce couldn't receive the IPN from the local payment gateway causing the Order Status showing "Pending Payment" although the payment has being approved. At moment, I am manually click to "Complete" upon receiving a notification email from the Local Payment Gateway vendor. Not sure what cause this?

**Comment by peterfabian** [comment]
Hi, 

Sorry, we don't provide support for 3rd party code. Please contact the developer of the payment gateway. If there are any logs they produce, it might help in determining where the problem lies. Thanks!

**Comment by ktchan1811** [comment]
Nored with thanks

**Comment by ktchan1811** [comment]
Hi 

Noted with thanks
