### ISSUE TITLE
'Payment methods' link missing from left hand menu when on example.com/my-account/payment-methods/

### ISSUE THREAD

**Issue by jjbbrr** [woocommerce/woocommerce#28086]
**Describe the bug**
This is a minor issue, but when you're on this page, the 'Payment methods' disappears from the left hand menu. It is there when you're on all other pages in 'My Account' but disappears when you're on this one. All the other menu items remain in position as you click through all these pages.

**Expected behavior**
'Payment methods' link should remain there all the time, regardless of whether you're on this page or not example.com/my-account/payment-methods/

**Actual behavior**
'Payment methods' link disappears when on this page example.com/my-account/payment-methods/

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to example.com/my-account/
2. Click on 'Payment methods' link in left hand navigation of My Account section
3. See in left hand menu that the 'Payment methods' link has disappeared

**WordPress Environment**
Wordpress 5.5.1
Woocommerce 4.6.0

**Comment by juliaamosova** [comment]
Hi @jjbbrr,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. Please see gif below:

![](http://g.recordit.co/ykvMEEetbq.gif)

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by swatipawarGS** [comment]
Hi @jjbbrr ,

Thank you for taking the time to report this bug, we really appreciate your help. We are unable to reproduce the issue on our end using WooCommerce 5.9.0 version and WordPress 5.8.2 version.

Please find below screencast for reference : 

https://user-images.githubusercontent.com/94531721/145769899-b9e0186d-7623-4a0e-b8a9-a9a11cdd470f.mp4


Please provide us more detailed and any additional steps required to repro this issue which may help us to evaluate it further.
