### ISSUE TITLE
New sale item to perfomance analytics

### ISSUE THREAD

**Issue by mariakhala** [woocommerce/woocommerce#28090]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
Hi i want all shipping cost of all statuses and my custom  order status as new attributes as mysale in performance analytics just like net sale but specific order status and shipping charges only. Any hook for this.
Thanks

**Comment by juliaamosova** [comment]
Hi @mariakhala,

Thank you for submitting your request. However, it had been reported previously here https://github.com/woocommerce/woocommerce-admin/issues/5498. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
