### ISSUE TITLE
My Account Addresses label not displayed when using Italian language

### ISSUE THREAD

**Issue by npdesigner** [woocommerce/woocommerce#28099]
The "Addresses" tab label in "My Account" page is not displayed when I use the Italian language while it should be already translated.

It`s placeholder "the empty space" works and navigates to the correct page as expected.

Best regards.

**Comment by juliaamosova** [comment]
Hi @npdesigner,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/27655. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
