### ISSUE TITLE
Allow filtering of cookie flags, which enables setting of samesite

### ISSUE THREAD

**Issue by DavidAnderson684** [woocommerce/woocommerce#28106]
Currently, it's not possible to set the "samesite" attribute on a cookie (or indeed, to do any filtering of what is set).

For us, this is breaking an embedded checkout which we use in all Chromium-based browsers, now that Chromium defaults to SameSite=Lax (https://www.chromestatus.com/feature/5088147346030592). However, it'd be useful generally to have a filter in wc_setcookie() to allow arbitrary changing of the cookie options.

By changing the parameter style for setcookie(), it becomes possible on PHP >= 7.3 to allow samesite to be set, whilst retaining compatibility with the existing, limited woocommerce_cookie_httponly filter. On PHP < 7.3, it is not possible for setcookie() to set "SameSite" in any circumstances, and thus the code detects the PHP version, so that this facility is still possible for users on non-EOL-ed versions (PHP 7.2 reaches EOL in 2 months).

Pull request: https://github.com/woocommerce/woocommerce/pull/28105

**Comment by jonshipman** [comment]
What about implementing it as an action as opposed to a filter? See
https://github.com/woocommerce/woocommerce/compare/master...jonshipman:master

My idea is that by just swapping out the function for an action we allow it to be changed by developers in the future. WordPress Core has yet to implement their change (see https://core.trac.wordpress.org/ticket/37000) and I'd suggest waiting until Core releases their solution. In the interim, an action that replicates the existing function would allow for SameSite to extend to those who want to add it in.
