### ISSUE TITLE
Question : Why are cross-sells hidden for grouped and external product types ?

### ISSUE THREAD

**Issue by MihaiCraciun** [woocommerce/woocommerce#28112]
https://github.com/woocommerce/woocommerce/blob/e7ac75fdfdb7aab2cbf22e1cf3629030b1b01ebe/includes/admin/meta-boxes/views/html-product-data-linked-products.php#L47

**Comment by rrennick** [comment]
> Why are cross-sells hidden for grouped and external product types

@MihaiCraciun There are separate answers for each type

External - External products are not purchased on-site so it isn't possible to cross sell a local product into the same purchase.

Grouped - I wasn't involved in the original decision for this. However, as a grouped product is already offering multiple products that can be purchased individually, effectively it is cross selling those products. 

If you have any further questions please let us know.
