### ISSUE TITLE
Cyprus listed in wrong continent

### ISSUE THREAD

**Issue by theo-gk** [woocommerce/woocommerce#28118]
**Prerequisites (mark completed items with an [x]):**
- [X] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [X] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
Hello, I noticed an error on the WooCommerce country list (on the shipping zone regions). Cyprus is listed as a country located on Asia, while it clearly belongs to Europe.

![Screenshot_1](https://user-images.githubusercontent.com/73558381/97358721-5550e480-18a4-11eb-8ae0-2d1cefc88c3a.png)

**Comment by rodrigoprimo** [comment]
Thanks for opening this issue, @theo-gk. We follow CLDR and I believe it puts Cyprus in Western Asia (https://github.com/unicode-org/cldr/blob/2dd06669d833823e26872f249aa304bc9d9d2a90/tools/java/org/unicode/cldr/util/data/UnMacroRegions.txt#L229). That is why recently we removed it from Europe (there was an entry in Europe and another one in Asia): https://github.com/woocommerce/woocommerce/pull/27636.

Please let me know if I'm missing something. I'm no expert on this subject.

**Comment by alexbogias** [comment]
You can check [wikipedia](https://en.wikipedia.org/wiki/European_Union). Cyprus belongs to also European Union

**Comment by theo-gk** [comment]
Cyprus belongs to Europe administratively and it's part of the European Union. [https://europa.eu/european-union/about-eu/countries_en](url) It's also a very delicate political matter putting Cyprus to Asia, but you should already know that... If we want to respect CLDR, then we can list the country on both continents. But I think that is more correct and way more practical to list it in Europe, where 99.99% of people will expect it to be

--

**Comment by rodrigoprimo** [comment]
Thanks for your input, @alexbogias and @theo-gk. 

> You can check wikipedia. Cyprus belongs to also European Union

Wikipedia also lists Cyprus as part of Western Asia: https://en.wikipedia.org/wiki/Western_Asia

> It's also a very delicate political matter putting Cyprus to Asia, but you should already know that

Generally speaking I know that this can be a delicate subject, but I don't know anything specifically about Cyprus. It is impossible for us, the maintainers of WooCommerce, to know what is the best option for each country. That is why we decided to adopt CLDR a while ago. Maybe you could open a ticket suggesting that CLDR change https://github.com/unicode-org/cldr/blob/2dd06669d833823e26872f249aa304bc9d9d2a90/tools/java/org/unicode/cldr/util/data/UnMacroRegions.txt#L229? See http://cldr.unicode.org/index/bug-reports

**Comment by rodrigoprimo** [comment]
Closing this issue for now due to lack of feedback and also considering that, as mentioned above, I don't think we can do anything on the WooCommerce side. Please let me know if I'm missing something and I will take a second look.
