### ISSUE TITLE
Travis CI delayed

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#28124]
We have a large backlog on travis.org CI. 
Maybe they have reduced the number of workers for us? 
Investigate if that is the case. 

How easy it is to migrate to travis.com? 
Or should we migrate to GH actions?

Please research and update our config so that our tests on CI run again.

**Comment by claudiosanches** [comment]
I just migrated to travis-ci.com, I'll close this issue for now, since the issue got fixed after migrating.
