### ISSUE TITLE
Composer v2 Support

### ISSUE THREAD

**Issue by XedinUnknown** [woocommerce/woocommerce#28122]
Hi!

In my project, I use Composer to require `woocommerce/woocommerce:^3.0 || ^4.0`. Although my constraint allows for WC 4+, it does not get installed by Composer. This is because [`composer/installers:1.9`][] is the first version that supports Composer v2, while WC 4 [requires][1] the _exact_ version of `1.7`. The same thing prevents me from installing WC `3.6`: it requires the _exact_ version of `1.6`.

Why is that? Why does it need the exact version `1.6` or `1.7` instead of `^1.6` or `^1.7`? Would it be possible for you to change that, in order to prevent this very narrow constraint from blocking newer WooCommerce versions with Composer v2?

[1]: https://github.com/woocommerce/woocommerce/blob/master/composer.json#L13
[`composer/installers:1.9`]: https://github.com/composer/installers/releases/tag/v1.9.0

**Comment by peterfabian** [comment]
Hi, 

thanks for opening the issue. Yup, we plan to update it soon, so that after the release of WC 4.7 we will support Composer 2. At the moment, we're waiting a bit until packages we include (Admin and Blocks) update their dependencies, then we can update ours as well.

**Comment by XedinUnknown** [comment]
Thanks for the reply!

Do I understand correctly that you will make the version constraint more flexible, e.g. `^1.7`?

**Comment by peterfabian** [comment]
Yup. I'm not 100% sure if it will be `^1.7` or `^1.9` or something else, as I haven't checked the package in detail yet, but I assume there is no reason to keep the dependency pinned to that specific version.

**Comment by peterfabian** [comment]
Side note: Blocks and Admin needs to be updated (or we need to load them via a commit hash) before we can do this, as they have some packages pinned to versions not compatible with Composer 2.

**Comment by budzanowski** [comment]
@peterfabian Blocks are ready: https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3335

**Comment by XedinUnknown** [comment]
It may also be a good idea to back-port the more flexible constraint into `3.x`.
