### ISSUE TITLE
WC_Order->skip_status_transition_events() (as in WooCommerce Bookings WC_Booking)

### ISSUE THREAD

**Issue by strarsis** [woocommerce/woocommerce#28135]
**Is your feature request related to a problem? Please describe.**
When programmatically creating WooCommerce Orders (`WC_Order`), e.g. when importing or synchronizing, 
the status transitions actions are triggered during save on order creation.
The most noticeable unintended side-effect by this is the sending of automated email, like an order creation email, e.g. for old orders that have been imported.

**Describe the solution you'd like**
The officially supported [WooCommerce Bookings](https://woocommerce.com/products/woocommerce-bookings/) premium plugin has the `WC_Booking` class that also got different stati and other fields similar to `WC_Order`. However, it also offers the `skip_status_transition_events` method that prevents triggering actions due to status changes when saving that booking for the first time on its creation.

**Describe alternatives you've considered**
The `woocommerce_email_enabled_<e-mail ID]` filters and a custom field/flag for the imported order instances have to be used to prevent the sending of unintended emails.

**Additional context**
As unintended emails due to order import/sync can be considered as quite undesirable outcome, an extra level of protection against uninteded actions, as the sending of automated emails would be helpful.

**Comment by Konamiman** [comment]
Hi @strarsis. It's possible to selectively disable email notifications whenever needed, as instructed here: https://woocommerce.com/document/email-faq/#section-3. This is the cleanest approach, adding additional mechanisms could cause issues with payment gateways or other plugins.

**Comment by rrennick** [comment]
Closing as won't fix.
