### ISSUE TITLE
sample_products.csv does not include all variations for "V-Neck T-Shirt"

### ISSUE THREAD

**Issue by robertocyrino** [woocommerce/woocommerce#28149]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When importing `sample_products.csv`, only 3 variations are created for `V-Neck T-Shirt`, when there should be 9 of them.

**Expected behavior**
Variations should be present for all of the attributes, but are currently only present for the color.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Download and extract WooCommerce
2. Go to Products > All Products > Import
3. Import `sample_products.csv` from the `Sample Data` folder.
4. Edit the `V-Neck T-Shirt` product
5. Go to Variations > verify there are 3 of them, only for the colors — not size
6. Delete the variations
7. Still in Variations, click Add variation > Create variations from all attributes
8. Verify there are 9 of them, now including the size as well.

**Screenshots**

Right after importing, and before creating new variations manually
![https://d.pr/i/Bcqdbh](https://d.pr/i/Bcqdbh+) 
Full Size: https://d.pr/i/Bcqdbh

After creating variations from all attributes
![https://d.pr/i/wz8h1l](https://d.pr/i/wz8h1l+) 
Full Size: https://d.pr/i/wz8h1l

**Comment by rrennick** [comment]
@robertocyrino Thanks for submitting the issue. The [sample import file](https://github.com/woocommerce/woocommerce/blob/master/sample-data/sample_products.csv) only contains 3 variations of the V Neck Tee Shirt (IDs 76-78).
