### ISSUE TITLE
Ability to get aggregated data per customer using WooCommerce REST API

### ISSUE THREAD

**Issue by apollonin** [woocommerce/woocommerce#28153]
**Is your feature request related to a problem? Please describe.**
I would like to have the ability to easily get the total number of orders and spent amount per customer using woo commerce REST API.

**Describe the solution you'd like**
Ideally, that should be included in the response to `/wp-json/wc/v3/customers` for each customer. 
Another option - extend reports and be able to get it via `/wp-json/wc/v3/reports/orders/totals?customer=${customerId}`

**Describe alternatives you've considered**
Right now I have to loop over all customers' orders in order to get totals.

**Comment by suhaasprasad** [comment]
+1

**Comment by rrennick** [comment]
> I would like to have the ability to easily get the total number of orders and spent amount per customer

@apollonin The REST API for the new Analytics data is under `wp-json/wc-analytics`. The endpoint for the above is `wp-json/wc-analytics/customers`. The `wc-analytics` route is maintained in [WooCommerce Admin](https://github.com/woocommerce/woocommerce-admin).

**Comment by apollonin** [comment]
Thank you, @rrennick . Would be good to reflex it somehow here in docs: https://woocommerce.github.io/woocommerce-rest-api-docs as I don't see route docs and params in WooCommerce Admin rpo
