### ISSUE TITLE
Woocommerce settings export - import function

### ISSUE THREAD

**Issue by Nerko69** [woocommerce/woocommerce#28168]
Would be really useful to have export-import of all woo settings as they are really cumbersome to reenter over and over...

**Comment by tammullen** [comment]
Hi @Nerko69 

Thank you for this suggestion. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/13089. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
