### ISSUE TITLE
REST API PUT Returns 200, but doesn't update

### ISSUE THREAD

**Issue by Mick-V8** [woocommerce/woocommerce#28178]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
Are there any conditions where a PUT for a Product update should return 200 OK, but not update the product?  The image attached shows a Postman example that works perfectly on one site (hosted by Kualo) and not on another (hosted by Flywheel).  My concern is that in our app we test for errors as a means of determining if it's worked, but on this site updating the product quantity doesn't work.  I can't see anything obvious in the return headers, but regardless I would have expect to see some kind of error.
![image](https://user-images.githubusercontent.com/70689457/97971154-822c5c80-1dba-11eb-8c4c-e29620522cc0.png)
![image](https://user-images.githubusercontent.com/70689457/97971448-fcf57780-1dba-11eb-8b0e-e3e2c47bb781.png)

**Comment by rrennick** [comment]
> Are there any conditions where a PUT for a Product update should return 200 OK, but not update the product?

@Mick-V8 Yes, The PUT in your screenshot does not include the product `id`. When you use a PUT with the WC REST API, the `id` of the object needs to be included in the data: 

```
{"id": 18722,"stock_quantity":240}
```

<img width="1131" alt="Screen Shot 2021-10-19 at 4 35 50 PM" src="https://user-images.githubusercontent.com/343847/137978526-01c0c0fb-a30a-447d-a9b9-94be708d630d.png">

I'll leave the issue open in case you have any follow up questions.
