### ISSUE TITLE
Memory depleted when requesting list of products via ajax

### ISSUE THREAD

**Issue by davefx** [woocommerce/woocommerce#28176]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

When calling json_search_products and json_search_products_and_variations we are getting out of memory problems, in our setup with thousands of existing products.

**Expected behavior**
A list of products in JSON should be returned, without depleting the memory.

**Actual behavior**
The execution gets aborted after depleting the available 1GB of RAM per PHP execution.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. In a setup with more than 2000 products, with mem_max_size=1GB, call /wp-admin/wp-ajax.php?action=woocommerce_json_search_products
5. The execution gets aborted due to memory depletion

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by roykho** [comment]
Hi there @davefx - thanks for reporting. I just want to get a little bit more context on this issue. Are you only running out of memory when you try to return all products in your catalog ( 2000 )? And when you actually try to search for a specific term, this issue does not happen. Is that accurate?

**Comment by davefx** [comment]
Exactly: when used in an actual search action things usually go
correctly... Although I suppose that, in the long term, if the products
database keeps growing, a really generic search term could end up causing
the same problem.

Basically, in our setup, this ajax function is being called without any
search parameter by a third-party plugin in order to obtain the list of
products via AJAX.
Maybe not the correct method, but I think we should always avoid situations
that potentially could cause memory depletion like this.

IMHO, we should always minimize the situations in which we have a
potentially long array of product objects in memory, especially if we are
not going to return the product objects. Keep in mind that product objects
can get really big with extensions like Bundles or Component products!
--
David Marín Carreño <davefx@gmail.com>
