### ISSUE TITLE
Cart shortcode does not work with switch_to_blog

### ISSUE THREAD

**Issue by carlomanf** [woocommerce/woocommerce#28174]
**Describe the bug**
I have two sites on the same network, both with woocommerce activated. I am trying to embed the cart for site A, inside site B.

I am using `switch_to_blog` to switch from site B to site A and then calling the cart shortcode.

Simplified version of the code I'm using:

```
switch_to_blog( $site_A->__get( 'id' ) );
echo do_shortcode( '[woocommerce_cart]' );
restore_current_blog(); // restores B
```

Both sites are using usermeta-based carts rather than cookie-based.

**Expected behavior**
I expected the shortcode to output the cart for site A.

**Actual behavior**
It actually outputs the cart for site B, but with a few elements broken (product permalinks etc)

I don't know if this is an oversight or if it is deliberately not implemented for some reason.

**Comment by rrennick** [comment]
> I don't know if this is an oversight or if it is deliberately not implemented for some reason.

@carlomanf Thanks for creating the issue. The WooCommerce cart is maintained in the web browser [session](https://www.php.net/manual/en/book.session.php). In WordPress multisite, `switch_to_blog()` updates the WordPress backend to reference the switched site but it does not update the web browser URL. As a result, the web browser session is still referencing the original site.

In the future it may be possible for you to achieve the functionality you are looking for with [product blocks and the store api](https://github.com/woocommerce/woocommerce-gutenberg-products-block). Let us know if you have any further questions.
