### ISSUE TITLE
Variable Product add_to_cart Link Can Add Parent to Cart With No Variation Selected

### ISSUE THREAD

**Issue by robin-scott** [woocommerce/woocommerce#28179]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Most recent - since version 3.6.0 - WooCommerce allows a user to add a "parent" variable product ID to cart using add_to_cart without a selected variation.

**Expected behavior**
Should not be possible to do this (imagine selling shoes, and you sell "1 shoe" without size information!).

**Actual behavior**
Add to cart link adds parent product with cheapest (first) variation price applied, and allows customer to checkout.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**

1. Install WooCommerce & Storefront
2. Setup a variable product
3. Make a link with parent product ID like yourdomain.com/?add-to-cart=[ID]
4. Checkout - you'll be able to place an order for this parent variable product ID.
5. Note - older versions of WooCommerce don't do this - they correctly will reject the parent from being added to cart.

**Screenshots**

![image](https://user-images.githubusercontent.com/17259256/97992892-42c23800-1ddb-11eb-9a3a-e3c826145dd8.png)

Video here: https://youtu.be/ZvwcXzylyUA

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by robin-scott** [comment]
BTW I had a good search for this issue in here - but there's a lot of needles in here which mention "variable" and "add to cart" apologies if this is a repost :)

Also note, we'll likely be patching this if it is not already, so a PR may be forthcoming on this ticket... let me know if this is already in motion.

**Comment by robin-scott** [comment]
Just adding comment that 4.7.0-rc.1 still has this issue - mostly for my own reference here.

**Comment by Studiokwebdesign** [comment]
https://github.com/woocommerce/woocommerce/pull/28103

**Comment by robin-scott** [comment]
Thanks @Studiokwebdesign - I was sure this would be somewhere... but that title is not illustrative

**Comment by robin-scott** [comment]
Closing this as it's got a PR on it already - will get some testing onto that. Thanks.
