### ISSUE TITLE
Documentation on how to use e2e packages in other repositories

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#28171]
The central place where folks can learn about our e2e testing infrastructure is this README:

https://github.com/woocommerce/woocommerce/tree/master/tests/e2e

Currently, it doesn't have any details on how to use our e2e packages in other projects. 

It will be great to add a section to the README above called `Setting up and Running e2e tests in other repositories` or something similar and link to the 4 packages we have with a brief description of what each of them does.

**Comment by rrennick** [comment]
We should be able to add a reference in the readme to https://github.com/woocommerce/woocommerce-e2e-boilerplate and that would cover this issue.

**Comment by rrennick** [comment]
Closing this as the E2E packages have been deprecated.
