### ISSUE TITLE
In Advanced Coupons for WordPress Premium, the coupon expiry date does not show up. Also have plugin Advanced Coupons for WordPress Free. Both are activated. Running a Buy One, Get One 1/2 Off coupon. When coupon is set to display under Customer Accounts and at checkout, "never expires" shows up. When I deactivate each plugin separately, the coupon expiry date appears but the coupon does not work.  Both plugins need to be activated to run deal. Please help.  Where does coupon expiry date go?

### ISSUE THREAD

**Issue by bloxkim** [woocommerce/woocommerce#28188]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by tammullen** [comment]
Hi @bloxkim 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 
​
The issue you are having seems to be caused by the 3rd party plugin Advanced Coupons for WooCommerce Coupons. 
​
Please contact the author of the plugin directly for further help.

**Comment by bloxkim** [comment]
Okay, will do. Thank you.
