### ISSUE TITLE
Run failed e2e test 3 times 

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#28185]
Implement running failed e2e test 3 times if it failed the first time it runs. This is to make sure that tests that fail do that not due to flakiness.

**Comment by rrennick** [comment]
This can be accomplished using [jest-circus](https://www.npmjs.com/package/jest-circus) and the environment variable `E2E_RETRY_TIMES=2`.

**Comment by MrJnrman** [comment]
Picking up this issue. Thanks for the suggestion @rrennick
