### ISSUE TITLE
Don't automatically delete "customer" if it has other content than "orders"

### ISSUE THREAD

**Issue by scrobbleme** [woocommerce/woocommerce#28180]
**Is your feature request related to a problem? Please describe.**

- We had a user within a customers site, who was the original maintainer and developer.
- Unfortunately the shop manager degraded the user to the user role "customer" after terminating the contract

→ **Problem**: The automatic user deletion removed this user and with this all the content the user created... 
Pages etc. where just moved to trash, but media was lost.  

Took us some time to find out what the problem was. 

**Describe the solution you'd like**

- Users of type "customer" should only be removed, if they don't have any other content as orders
  - if they have other content, maybe anonymize the user and change it's role to "none"
- There should be some log/mail of automatic user removal

**Describe alternatives you've considered**

We currently disable the automatic user removal, as it is not really safe to use.

**Comment by barryhughes** [comment]
- I think this problem was addressed by https://github.com/woocommerce/woocommerce/pull/38837.
- If we're wrong, please just let us know and we can re-open.
