### ISSUE TITLE
Regression: hard-coded database table in WC_Session_Handler

### ISSUE THREAD

**Issue by carlomanf** [woocommerce/woocommerce#28193]
#21455 caused a regression by replacing `$this->_table` with `{$wpdb->prefix}woocommerce_sessions`.

This forces sub-classes of `WC_Session_Handler` to overwrite `save_data` if they use a different database table.

This can be fixed by reinstating `{$this->_table}` in the new code.

**Comment by rrennick** [comment]
@carlomanf Thanks for reporting the issue. I apologize for the time it's taken for follow up. I've marked this as a regression for follow up by the dev team.
