### ISSUE TITLE
+1 for Cart API

### ISSUE THREAD

**Issue by inpresif** [woocommerce/woocommerce#28201]
I see this has been requested more than once since years ago, so I am just adding our +1.

Extra functionality for the Cart API so we can build a cart in our App and use the native Cart contents checkout if the users chooses to, so the Cart checkout is possible on the native Woocom setup.

**Comment by tammullen** [comment]
Hi @inpresif 

Thank you for reporting the issue. However, this issue had been discussed previously here https://github.com/woocommerce/woocommerce/issues/27724. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.

**Comment by lkraav** [comment]
@inpresif use emojis on opening comments to express support, not separate issues.
