### ISSUE TITLE
@woocommerce/e2e-utils npm package doesn't work: "Cannot find module 'config' from 'flows.js'"

### ISSUE THREAD

**Issue by ecgan** [woocommerce/woocommerce#28200]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

When I'm trying to use [@woocommerce/e2e-utils](https://www.npmjs.com/package/@woocommerce/e2e-utils) (current version is 0.1.1) and run e2e tests in a WooCommerce plugin project, the test cannot run and throws "Cannot find module 'config' from 'flows.js'" error.

**Expected behavior**

E2E tests should be able to run.

**Actual behavior**

I'm seeing an error like below: 

```text
  ● Test suite failed to run

    Cannot find module 'config' from 'flows.js'

    Require stack:
      node_modules/@woocommerce/e2e-utils/build/flows.js
      node_modules/@woocommerce/e2e-utils/build/index.js
      tests/e2e/specs/login123.test.js

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:299:11)
      at Object.<anonymous> (../../../../ronrennick/Sites/docker-e2e/woocommerce/tests/e2e/utils/src/flows.js:15:16)
```

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**

Steps to reproduce the bug:

1. In a new plugin project folder, run `npm install @woocommerce/e2e-utils --save`.
2. Create an e2e test using the example from the npm package page: https://www.npmjs.com/package/@woocommerce/e2e-utils
3. Run the e2e test.
4. Observe that the above error is thrown.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
> Run the e2e test.

@ecgan Can you explain this step in more detail or perhaps provide additional information on your setup? I've written a PR to address the issue but I'm not able to reproduce the error message. We'd like to verify it addresses the problem you encountered.

**Comment by ecgan** [comment]
@rrennick , so what I did was I have an e2e test like `dummy.test.js` with the following from [@woocommerce/e2e-utils npm page](https://www.npmjs.com/package/@woocommerce/e2e-utils):

```js
import {
    CustomerFlow,
    StoreOwnerFlow,
    createSimpleProduct,
    uiUnblocked
} from '@woocommerce/e2e-utils';
 
describe( 'Cart page', () => {
    beforeAll( async () => {
        await StoreOwnerFlow.login();
        await createSimpleProduct();
        await StoreOwnerFlow.logout();
    } );
 
    it( 'should display no item in the cart', async () => {
        await CustomerFlow.goToCart();
        await expect( page ).toMatchElement( '.cart-empty', { text: 'Your cart is currently empty.' } );
    } );
} );
```

Then I run e2e test by calling `npm run test-e2e` which uses [@wordpress/scripts](https://github.com/WordPress/gutenberg/tree/master/packages/scripts).

```
// npm script.
"test-e2e": "wp-scripts test-e2e"
```

**Comment by rrennick** [comment]
> Then I run e2e test by calling npm run test-e2e which uses @wordpress/scripts.

We use `@woocommerce/e2e-environment` to run tests. Are there any other packages you added to your project related to running tests?

**Comment by ecgan** [comment]
@rrennick , when I was working on it, it was a brand new plugin project with very minimal configuration and packages, there weren't any other packages related to running tests.
