### ISSUE TITLE
Place order button etc is not greyed out once clicked whilst using the twentytwenty theme

### ISSUE THREAD

**Issue by leeneilson** [woocommerce/woocommerce#28207]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
If you click on the place order button, whilst this is processing the button etc is not greyed out. This is leading to multiple clicks.

**Expected behavior**
The blockUI element should be on top of the elements, greying them out.

**Actual behavior**
They are not greyed out and can be clicked again.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Setup WooCommerce with products etc.
2. Install and activate the twentytwenty theme.
3. Place and order and watch the place order button etc, after clicking it.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**My hack to fix this**
I have been playing around and it seems as if this could be down to there not being a clearfix on the 'woocommerce-checkout' form. By adding the below CSS, the elements are now greyed out.

```
form.woocommerce-checkout {
	*zoom: 1;
}

form.woocommerce-checkout::before, form.woocommerce-checkout::after {
	content: ' ';
	display: table;
}

form.woocommerce-checkout::after {
	clear: both;
}
```

**Comment by roykho** [comment]
Thanks for reporting. There is already an open issue on this. So closing this in favor of https://github.com/woocommerce/woocommerce/issues/27656
