### ISSUE TITLE
CSV Import skipping silently some products

### ISSUE THREAD

**Issue by FeIix** [woocommerce/woocommerce#28223]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I'm importing a CSV of about 6000 products in a brand new WP / WC setup.
The import always says it finished successfully, but sometimes (maybe 1 third of my tries), the last 5/10 products are not imported.
No trace of them in the log.
When it happens, if I reimport the exact same file, existing products will be skipped as expected, but the missings ones are still ignored.

However, when deleting all imported products and keeping only the missings, it works, they are imported without problem.

The exact same file 2 in 3 times will import all products without missing a single one.

**Expected behavior**
The importer should import all products.

**Actual behavior**
Last products in the CSV are skipped without reason, while being valid.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
- Import a long CSV of at least 4000 products (simple, variable, variations)
- Compare imported number with CSV number
- If it's the same number : 
    - Delete all the tables
    - Reinstall WP
    - repeat until there are less imported products than in the CSV.

**Isolating the problem (mark completed items with an [x]):**
- [? ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [? ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

### WordPress Environment ###

WC Version: 4.6.2
REST API Version: ✔ 4.6.2
WC Blocks Version: ✔ 3.4.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.2
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 512 Mo
WP Debug Mode: ✔
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.11
PHP Post Max Size: 128 Mo
PHP Time Limit: 2400
PHP Max Input Vars: 5000
cURL Version: 7.64.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 8.0.22
Max Upload Size: 128 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Votre serveur n’a pas la classe SoapClient activée - certaines extensions de passerelle utilisant SOAP peuvent ne pas fonctionner correctement.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.6.2
WC Database Prefix: g45gq_
Taille totale de la base de données: 4.41MB
Taille de la base de données: 2.57MB
Taille de l’index: 1.84MB
g45gq_woocommerce_sessions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
g45gq_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
g45gq_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
g45gq_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
g45gq_woocommerce_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
g45gq_woocommerce_order_itemmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
g45gq_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
g45gq_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
g45gq_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
g45gq_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
g45gq_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
g45gq_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
g45gq_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
g45gq_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
g45gq_actionscheduler_actions: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
g45gq_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
g45gq_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
g45gq_actionscheduler_logs: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
g45gq_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
g45gq_comments: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
g45gq_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
g45gq_options: Données : 1.45MB + Index : 0.06MB + Moteur InnoDB
g45gq_postmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
g45gq_posts: Données : 0.08MB + Index : 0.06MB + Moteur InnoDB
g45gq_redirection_404: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
g45gq_redirection_groups: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
g45gq_redirection_items: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
g45gq_redirection_logs: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
g45gq_term_relationships: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
g45gq_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
g45gq_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
g45gq_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
g45gq_usermeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
g45gq_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
g45gq_wc_admin_note_actions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
g45gq_wc_admin_notes: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
g45gq_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
g45gq_wc_customer_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
g45gq_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
g45gq_wc_etransactions_payment: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
g45gq_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
g45gq_wc_order_product_lookup: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
g45gq_wc_order_stats: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
g45gq_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
g45gq_wc_product_meta_lookup: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
g45gq_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
g45gq_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
g45gq_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
g45gq_wpmailsmtp_tasks_meta: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
g45gq_yoast_indexable: Données : 0.02MB + Index : 0.08MB + Moteur InnoDB
g45gq_yoast_indexable_hierarchy: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
g45gq_yoast_migrations: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
g45gq_yoast_primary_term: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
g45gq_yoast_seo_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB

### Post Type Counts ###

acf-field: 34
acf-field-group: 6
attachment: 6524
oembed_cache: 5
page: 6
post: 2
product: 5801
product_variation: 31
wc_afrsm: 9

### Security ###

Secure connection (HTTPS): ❌
					Votre boutique n’utilise pas HTTPS. En savoir plus sur HTTPS et les certificats SSL.
Hide errors from visitors: ❌Les messages d’erreur ne doivent pas s’afficher aux visiteurs.

### Active Plugins (13) ###

WooCommerce: par Automattic – 4.6.2
AddToAny Share Buttons: par AddToAny – 1.7.42
Woocommerce Drawer: par SAS – 0.12 – La version installée n’a pas été testée avec la version en cours de WooCommerce 4.6.2
Advanced Custom Fields PRO: par Elliot Condon – 5.9.1
Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro: par codewoogeek – 1.9.9 – La version installée n’a pas été testée avec la version en cours de WooCommerce 4.6.2
E-Transactions: par E-Transactions – 0.9.9.9.1 – La version installée n’a pas été testée avec la version en cours de WooCommerce 4.6.2
MainWP Child: par MainWP – 4.1.2
Redirection: par John Godley – 4.9.2
Yoast SEO: par L’équipe Yoast – 15.2.1
DPD France: par DPD France S.A.S. – 5.2.9 – La version installée n’a pas été testée avec la version en cours de WooCommerce 4.6.2
Advanced Flat Rate Shipping For WooCommerce: par theDotstore – 3.7.2 – La version installée n’a pas été testée avec la version en cours de WooCommerce 4.6.2
WooCommerce PDF Invoices & Packing Slips: par Ewout Fernhout – 2.7.0
WP Mail SMTP: par WPForms – 2.5.1

### Inactive Plugins (7) ###

Akismet Anti-Spam: par Automattic – 4.1.7
Export Import Menus: par Akshay Menariya – 1.6.0
iThemes Security: par iThemes – 7.9.0
Mailjet for WordPress: par Mailjet SAS – 5.2.4
Max Mega Menu: par megamenu.com – 2.9.1
Simply Show Hooks: par Stuart O'Brien
cxThemes – 1.2.1

UpdraftPlus - Backup/Restore: par UpdraftPlus.Com
DavidAnderson – 1.16.34

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la boutique: #6 - /boutique/
Panier: #7 - /panier/
Commander: #8 - /commander/
Mon compte: #9 - /mon-compte/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Divi Child
Version: 1.0.0
Author URL: http://example.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 4.6.6
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: Divi-child/woocommerce/archive-product.php
Divi-child/woocommerce/emails/customer-completed-order.php
Divi-child/woocommerce/emails/customer-new-account.php
Divi-child/woocommerce/emails/customer-processing-order.php
Divi-child/woocommerce/emails/email-order-details.php
Divi-child/woocommerce/emails/email-order-items.php
Divi-child/woocommerce/single-product/add-to-cart/simple.php

### Action Scheduler ###

Terminé: 3
Oldest: 2020-11-10 09:12:54 +0100
Newest: 2020-11-10 09:12:51 +0100

I will try ASAP without plugins and on native theme, but i'm pretty sure this is a bug in woocommerce import.
Nothing in my plugins or theme should interfere, they look unrelated.

**Comment by rrennick** [comment]
@FeIix This is likely a resource issue in your web server. However, if you would like to provide an import file that will reproduce this issue in a development install, we will investigate further.

**Comment by FeIix** [comment]
Hello and thanks for your answer,

I can't send an example file because it's not my property, but I might have more informations about this :
I found out that the last X images that are often skipped are all variations, duplicated from a related product.

The thing is that their image url is just the filename, only their previously imported related product has a full URL.
It seems that putting just the filename only works if images have been imported in a previous import.
When trying to reuse an image in the same import (http://.../uploads/img1.png then just img1.png), it's not working and the entire product is silently skipped.

If I do my import in 2 parts (first base products, then duplicated variations, in 2 different CSVs), it works fine, everything is imported.

I'm not sure it's a server issue because even when there are skipped products, I got the "import success" end message, without error.
Could it be that images are imported in media library at the end of import, in some hook, so when I try to reuse an image it's not already available ?

**Comment by lanej0** [comment]
Hi @FeIix,

Really sorry that this issue slipped through the cracks! I'm just following up on this -- are you still seeing this behaviour or does it seem to be resolved in recent versions of WooCommerce?

Just to confirm the replication steps: it sounds like we can test this behaviour potentially by setting up a CSV file that imports a product image by path (where it's hosted on the site) then for a product further down in the file, we reference the image by name only, e.g. `product.png`, then that product is skipped on the import?

**Comment by FeIix** [comment]
No problem, thanks.

I did not have the opportunity to use WC import since that project (WC 4.6.2 at the time), so maybe it was fixed, but it should be easy to test

You are right on the replication steps, in my case :

- The main products (full url) where all of type Variable, and the skipped products their variations (reusing image using image name only)

- The variations where always placed after their variable product in the CSV file (never a single filename imported before a full url)

- I had more than 6000 products (most of them being Simple, only a few being Variable/Variation), but it should be replicable with only 2 I guess

- Importing variations, with filename only, in a separate CSV, after the one with full urls, fixed the bug

**Comment by lanej0** [comment]
Thanks again for taking the time to report this!

I've done a bunch of testing here, and haven't been able to replicate an issue.  Here's what I tried:

1. Doing an import with a bunch of images that don't exist (just setting the image to something random like `1234.jpg`).  In this case, it skips importing those, and tells me in the log `Unable to use image 1234.jpg`
2. I can re-use images, as you described above. So if I either upload `1234.jpg`, or point to a URL for `1234.jpg` and then import a bunch of products just referencing `1234.jpg`, everything works as expected.

So it seems like things are working as they should now.  I'm going to close out this issue, but if you run into this again, please feel free to re-open it.
