### ISSUE TITLE
Update master branch to trunk

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#28238]
In alignment with other parts of the world and Automattic, we should update our `master` branch to `trunk`.

**Comment by claudiosanches** [comment]
Just noting here that GitHub reported that renaming the default branch can cause a set of challenges:

- Open pull requests need to be retargeted to the new branch
- Draft releases need to be retargeted to the new branch
- Branch protection policies need to be transferred to the new branch

Also there's a promise from GitHub that by the end of this year changing the default branch will already retarget all PRs and migrate branch protection policies.

See more details: https://github.com/github/renaming#later-this-year-seamless-move-for-existing-repositories-

**Comment by peterfabian** [comment]
Thanks, great point Claudio. Let's wait until EOY and if nothing happens, let's migrate ourselves.

**Comment by peterfabian** [comment]
As per: https://github.com/github/renaming#creating-a-seamless-move-for-existing-repositories-

> Beginning in January 2021, we'll begin rolling out functionality to make it easier to rename the default branch of an existing repository

So we can either wait a bit more until GH rolls this out, or do it ourselves.

**Comment by beaulebens** [comment]
If they're now putting a timeline of this month on it, then I'm fine waiting for them.

**Comment by rrennick** [comment]
@peterfabian Thanks for the reference.

**Comment by claudiosanches** [comment]
Default branch renamed and GitHub updated all our PRs:

![Screenshot from 2021-02-25 19-16-56](https://user-images.githubusercontent.com/1264099/109226857-2ab56080-779e-11eb-979d-506884c14559.png)

For those that needs to update local environments:

```bash
git branch -m master trunk
git fetch origin
git branch -u origin/trunk trunk
```

**Comment by claudiosanches** [comment]
Reopening since we need to update some files.
