### ISSUE TITLE
Description tab not showing if only content is an elementor 'template' widget

### ISSUE THREAD

**Issue by johnrisby** [woocommerce/woocommerce#28247]
- [* ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [* ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

If you use Elementor for product pages, and the only thing in your Elementor page is a template widget, the Description tab doesn't show up. If you add any text on the page, it works as expected.

**Expected behavior**

The description tab should show up on the product page, and the Elementor template should be rendered.

**Actual behavior**

The description tab is not shown.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create a new product
2. Make sure Elementor is installed and it is turned on for Product pages
3. Edit the product page with Elementor
4. Put some text in
5. Check the product on the front end, it will display the Description tab and the text.
6. Go back and remove the text.
7. Add a Template widget and tell it to load another Elementor template into the page. It will show on the preview.
8. Go back to the front end, the description tab will not be shown
9. Edit the page again, and add a text block with some content.
10. Go back to the front end, the description tab will show, and so will the expected template

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [*] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [*] I can reproduce this bug consistently using the steps above.

I have found the problem.

It's in the file includes/wc-template-functions.php

Line 1784 of Version 4.6.2 - function woocommerce_default_product_tabs( $tabs = array() ) {

`if($post->post_content)`

is used to see if there is any content, and if so, it renders the Description tab.

If it is empty, it doesn't display it.

But $post->post_content is stripped of tags, so if the only thing in it is a shortcode etc, it is always empty.

If that line is changed to 

`if(apply_filters('the_content', $post->post_content))`

then it works as expected. It doesn't show the Description tab if there is no content, but it does show and render correctly if it's only a template etc.

**Comment by rrennick** [comment]
@johnrisby Thanks for submitting the issue. I'm not able to reproduce this issue using a shortcode. I used the following steps

- I created a test shortcode
```
// Issue https://github.com/woocommerce/woocommerce/issues/27896
add_shortcode( 'i28247', function() {
	return 'Issue 28247 shortcode content';
});
```

- Added the shortcode to the product description
<img width="1096" alt="Screen Shot 2021-10-20 at 2 33 39 PM" src="https://user-images.githubusercontent.com/343847/138142825-aa7e1ea6-f77b-4d90-87d8-c26d9d88dcfd.png">

- Viewed the single product page
<img width="837" alt="Screen Shot 2021-10-20 at 2 35 12 PM" src="https://user-images.githubusercontent.com/343847/138143011-8b21ed56-6c75-4f9f-bf12-958da61b0c84.png">

Please provide us with more details about the issue which may help us to evaluate it further. We need to be able to reproduce the issue with only WooCommerce active and a default theme or Storefront active.

**Comment by mail2chethankarur** [comment]
Hi

I am facing this issue now. Can I reopen this conversation?

**Comment by rrennick** [comment]
Hi @mail2chethankarur If you have discussed this issue with Elementor support and they have provided information on how it's an issue in WC core then please open a new issue with that info. Otherwise we suggest that you contact Elementor support.
