### ISSUE TITLE
4.7.0 release not tagged

### ISSUE THREAD

**Issue by leewillis77** [woocommerce/woocommerce#28244]
Version 4.7.0 has been released to https://wordpress.org/plugins/woocommerce, but is not tagged here, leading GitHub to show the latest release as 4.6.2 and making it difficult for people running WooCommerce for development from GitHub to checkout this specific release.

**Comment by claudiosanches** [comment]
Solved: https://github.com/woocommerce/woocommerce/releases/tag/4.7.0
