### ISSUE TITLE
wc_get_products function include param problem

### ISSUE THREAD

**Issue by hqin2013** [woocommerce/woocommerce#28252]
[https://github.com/woocommerce/woocommerce/wiki/wc_get_products-and-WC_Product_Query](https://github.com/woocommerce/woocommerce/wiki/wc_get_products-and-WC_Product_Query)

Hi, i followed this document to check products with include 100+ products, and found there are only 10 producs t in the result ?! doesn't it return 100+ products?!

how to solve it?!

$post_ids = array(); // ==> 100+ products ids 
$args = array('include'=>$post_ids);

Regards
Qin

**Comment by anastis** [comment]
```
$post_ids = array(); // ==> 100+ products ids
$args = array( 'include'=>$post_ids, 'limit' => count( $post_ids ) );
```

**Comment by hqin2013** [comment]
> count( $post_ids )

it works, thank you!
