### ISSUE TITLE
Research spike on notifications reappearing

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#28257]
There has been several problems reported related to Notices not going away when clicked, e.g. #27424 or #27463.
There might be several problems why this is happening, but let's try to ignore 'Action Scheduler not running' right now and focus on nonce problem and architecture of Notes. 

Thus we need a research spike on possible solutions, discuss this with other teams who use the code and come to a conclusion on how to solve it.

**Comment by roykho** [comment]
Closing in favor of https://github.com/woocommerce/woocommerce/issues/27424 as a solution has already been suggested and in review.
