### ISSUE TITLE
Hidden products still in WP sitemaps

### ISSUE THREAD

**Issue by ajgw** [woocommerce/woocommerce#28253]
Hi everybody, I have few items in store set to hidden in frontend and search but wonder as google bots indexed them. It seems that hidden products are still in WP sitemap listed for search engines. This shouldn't be because hiding them in store has often reasons.

Is there anywhere a setting for this I have overseen?

**Comment by juliaamosova** [comment]
Hi @ajgw,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/27954. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
