### ISSUE TITLE
[WC 4.7 + WP 5.6 + PHP8 + 2021] Create an account option from checkout with Twenty Twenty-One can be easily missed and looks odd

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#28275]
Opening this issue on behalf of @ldr2273. Reference: pb22l9-an-p2. 

**Testing Env:**
- Atomic ephemeral
- WP: 5.6-beta4-49590
- WC: 4.7.0
- PHP: 8.0.0RC3
- macOS
- Chrome
- 2021 theme

**Issue:**

Create an account option from checkout with Twenty Twenty-One can be easily missed and looks odd.

Unchecked:

![5](https://user-images.githubusercontent.com/19143190/99090554-c975d280-259c-11eb-8cb7-f575666d62fc.png)

Checked:

![6](https://user-images.githubusercontent.com/19143190/99090581-d266a400-259c-11eb-9da4-9085d4bb5189.png)

**Comment by AashikP** [comment]
Same with saving payment methods. Reporting here as it looks like fixing original report would fix this one as well:

![https://d.pr/i/pRP0ou+](https://d.pr/i/pRP0ou+)

**Comment by roykho** [comment]
I just tested this and I think it is no longer an issue with the latest round of changes with Twenty Twenty One theme. ![](https://d.pr/i/jDiA9T+)
