### ISSUE TITLE
Check JS libraries included in WooCommerce core to ensure they are compatible with jQuery 3

### ISSUE THREAD

**Issue by rodrigoprimo** [woocommerce/woocommerce#28284]
We need to make sure that all external JS libraries that are included in WooCommerce and that rely on jQuery are compatible with jQuery 3 before WP removes jQuery Migrate 3. We should also take this opportunity to explore where we can remove jQuery usage entirely, and switch to either vanilla JS, or something provided via the more modern stack that comes with Gutenberg. Specially considering that some of the libraries that we are using are not maintained anymore.

WooCommerce core includes the following JS libraries that use jQuery (I generated this list manually by going through the JS files in our repository):

- assets/js/jquery-payment/
- assets/js/jquery-flot/
- assets/js/jquery-serializejson/
- assets/js/flexslider/
- assets/js/jquery-ui-touch-punch/
- assets/js/selectWoo/
- assets/js/zeroclipboard/
- assets/js/jquery-cookie/
- assets/js/stupidtable/
- assets/js/jquery-qrcode/
- assets/js/select2/
- assets/js/jquery-tiptip/
- assets/js/zoom/
- assets/js/prettyPhoto/
- assets/js/jquery-blockui/

**Comment by jonathansadowski** [comment]
I just wanted to note that there's a comment about current progress on p7bje6-2VM-p2

**Comment by pacmanito** [comment]
@rodrigoprimo, @jonathansadowski, @roykho I've just noticed that zeroclipboard library uses $.event.props which was not only deprecated but dropped long ago - https://jquery.com/upgrade-guide/3.0/#breaking-change-jquery-event-props-and-jquery-event-fixhooks-removed
