### ISSUE TITLE
Ensure WooCommerce is compatible with jQuery 3

### ISSUE THREAD

**Issue by rodrigoprimo** [woocommerce/woocommerce#28286]
[WP 5.6 will ship with jQuery 3](https://href.li/?https://make.wordpress.org/core/2020/11/05/updating-core-jquery-to-version-3-part-2/). It will also include jQuery Migrate 3, so this change should not impact WooCommerce JS code in any way. That being said, we need to start working to make sure our code is fully compatible with jQuery 3 as [WP plans to remove jQuery Migrate 3 in a future version](https://make.wordpress.org/core/2020/06/29/updating-jquery-version-shipped-with-wordpress/) (WP 5.7 or later).

I don't think there is a way to search all our codebase automatically and get a list of functions that we are using that were deprecated in jQuery 3 (similar to what we normally do with PHPCompability when checking for compatibility with a new version of PHP). So I guess we will either have to get the list of [jQuery 3 changes](https://jquery.com/upgrade-guide/3.0/) and search for deprecated code manually or monitor the dev tools console while browsing WooCommerce related pages and fix deprecated code as it is reported by jQuery Migrate. Please let me know if there is a better way to approach this.

I'm planning to split this epic into two issues. One to address WooCommerce JS code and another one to address external JS libraries that are shipped with WooCommerce.

**Comment by Pairfum-London** [comment]
Dear Rodrigo,

Regarding your comment above about 'search for deprecated code manually', below is a list of the notices we received after installing the Enable jQuery Migrate Helper plugin:

Time	Notice	Plugin or theme	File location	Triggered on page
11/12/2020 21:23	jQuery.isFunction() is deprecated	Plugin: WooCommerce	https://www.pairfum.com/wp-content/plugins/woocommerce/assets/js/jquery-blockui/jquery.blockUI.min.js	https://www.pairfum.com/
11/12/2020 21:24	jQuery.fn.submit() event shorthand is deprecated	Plugin: WooCommerce	https://www.pairfum.com/wp-content/plugins/woocommerce/assets/js/frontend/checkout.min.js	https://www.pairfum.com/checkout/
11/12/2020 21:49	jQuery.fn.click() event shorthand is deprecated	Plugin: WooCommerce	https://www.pairfum.com/wp-content/plugins/woocommerce/assets/js/frontend/woocommerce.min.js	https://www.pairfum.com/fragranced-couscous/
12/12/2020 10:21	jQuery.fn.bind() is deprecated	Plugin: WooCommerce	https://www.pairfum.com/wp-content/plugins/woocommerce/assets/js/frontend/checkout.min.js	https://www.pairfum.com/checkout/
12/12/2020 10:22	jQuery.isFunction() is deprecated	Plugin: WooCommerce	https://www.pairfum.com/wp-content/plugins/woocommerce/assets/js/frontend/single-product.min.js	https://www.pairfum.com/product/new-diffuser-refill-reeds-classic-long-diffuser-sticks/
12/12/2020 10:22	jQuery.fn.bind() is deprecated	Plugin: WooCommerce	https://www.pairfum.com/wp-content/plugins/woocommerce/assets/js/flexslider/jquery.flexslider.min.js	https://www.pairfum.com/product/new-diffuser-refill-reeds-classic-long-diffuser-sticks/
12/12/2020 10:22	jQuery.fn.focus() event shorthand is deprecated	Plugin: WooCommerce	https://www.pairfum.com/wp-content/plugins/woocommerce/assets/js/flexslider/jquery.flexslider.min.js	https://www.pairfum.com/product/reed-diffuser-refill/
12/12/2020 10:22	jQuery.fn.click() event shorthand is deprecated	Plugin: WooCommerce	https://www.pairfum.com/wp-content/plugins/woocommerce/assets/js/frontend/single-product.min.js	https://www.pairfum.com/product/reed-diffuser-refill/
12/12/2020 10:23	jQuery.isArray is deprecated; use Array.isArray	Plugin: WooCommerce	https://www.pairfum.com/wp-content/plugins/woocommerce/assets/js/selectWoo/selectWoo.full.min.js	https://www.pairfum.com/checkout/
12/12/2020 10:23	jQuery.fn.change() event shorthand is deprecated	Plugin: WooCommerce	https://www.pairfum.com/wp-content/plugins/woocommerce/assets/js/frontend/checkout.min.js	https://www.pairfum.com/checkout/
12/12/2020 13:22	jQuery.fn.bind() is deprecated	Plugin: WooCommerce	https://www.pairfum.com/wp-content/plugins/woocommerce/assets/js/frontend/address-i18n.min.js	https://www.pairfum.com/cart/
12/12/2020 13:28	jQuery.fn.bind() is deprecated	Plugin: WooCommerce	https://www.pairfum.com/wp-content/plugins/woocommerce/assets/js/frontend/country-select.min.js	https://www.pairfum.com/cart/
12/12/2020 13:41	jQuery.fn.blur() event shorthand is deprecated	Plugin: WooCommerce	https://www.pairfum.com/wp-content/plugins/woocommerce/assets/js/flexslider/jquery.flexslider.min.js	https://www.pairfum.com/product/reed-diffuser-tower-classic/
12/12/2020 13:41	jQuery.isFunction() is deprecated	Plugin: WooCommerce	https://www.pairfum.com/wp-content/plugins/woocommerce/assets/js/zoom/jquery.zoom.min.js	https://www.pairfum.com/product/reed-diffuser-tower-classic/
12/12/2020 13:41	jQuery.fn.delegate() is deprecated	Plugin: WooCommerce	https://www.pairfum.com/wp-content/plugins/woocommerce/assets/js/flexslider/jquery.flexslider.min.js	https://www.pairfum.com/product/reed-diffuser-refill/
12/12/2020 16:04	jQuery.fn.bind() is deprecated	Plugin: WooCommerce	https://www.pairfum.com/wp-content/plugins/woocommerce/assets/js/frontend/price-slider.min.js	https://www.pairfum.com/?customize_changeset_uuid=c4154cdc-105d-4c2c-993b-bf15a4734296&customize_theme=generatepress_child&customize_messenger_channel=preview-0
12/12/2020 15:58	jQuery.isFunction() is deprecated	WordPress core	https://www.pairfum.com/wp-admin/js/iris.min.js	https://www.pairfum.com/wp-admin/customize.php?return=%2Fwp-admin%2Fadmin.php%3Fpage%3Dlitespeed-toolbox
12/12/2020 15:58	jQuery.isArray is deprecated; use Array.isArray	WordPress core	https://www.pairfum.com/wp-admin/js/color-picker.min.js	https://www.pairfum.com/wp-admin/customize.php?return=%2Fwp-admin%2Fadmin.php%3Fpage%3Dlitespeed-toolbox
12/12/2020 15:58	jQuery.trim is deprecated; use String.prototype.trim	WordPress core	https://www.pairfum.com/wp-admin/js/customize-controls.min.js	https://www.pairfum.com/wp-admin/customize.php?return=%2Fwp-admin%2Fadmin.php%3Fpage%3Dlitespeed-toolbox
12/12/2020 15:58	jQuery.isFunction() is deprecated	WordPress core	https://www.pairfum.com/wp-admin/js/customize-controls.min.js	https://www.pairfum.com/wp-admin/customize.php?return=%2Fwp-admin%2Fadmin.php%3Fpage%3Dlitespeed-toolbox
12/12/2020 15:59	jQuery.isFunction() is deprecated	WordPress core	https://www.pairfum.com/wp-admin/js/customize-widgets.min.js	https://www.pairfum.com/wp-admin/customize.php?return=%2Fwp-admin%2Fadmin.php%3Fpage%3Dlitespeed-toolbox
12/12/2020 15:59	jQuery.fn.bind() is deprecated	WordPress core	https://www.pairfum.com/wp-admin/js/customize-controls.min.js	https://www.pairfum.com/wp-admin/customize.php?return=%2Fwp-admin%2Fadmin.php%3Fpage%3Dlitespeed-toolbox
12/12/2020 15:59	jQuery.isFunction() is deprecated	WordPress core	https://www.pairfum.com/wp-admin/js/color-picker.min.js	https://www.pairfum.com/wp-admin/customize.php?return=%2Fwp-admin%2Fadmin.php%3Fpage%3Dlitespeed-toolbox
12/12/2020 15:59	jQuery.isArray is deprecated; use Array.isArray	WordPress core	https://www.pairfum.com/wp-admin/js/iris.min.js	https://www.pairfum.com/wp-admin/customize.php?return=%2Fwp-admin%2Fadmin.php%3Fpage%3Dlitespeed-toolbox
12/12/2020 15:59	jQuery.type is deprecated	WordPress core	https://www.pairfum.com/wp-admin/js/iris.min.js	https://www.pairfum.com/wp-admin/customize.php?return=%2Fwp-admin%2Fadmin.php%3Fpage%3Dlitespeed-toolbox
12/12/2020 15:59	jQuery.fn.click() event shorthand is deprecated	WordPress core	https://www.pairfum.com/wp-admin/js/color-picker.min.js	https://www.pairfum.com/wp-admin/customize.php?return=%2Fwp-admin%2Fadmin.php%3Fpage%3Dlitespeed-toolbox
12/12/2020 15:59	jQuery.fn.change() event shorthand is deprecated	WordPress core	https://www.pairfum.com/wp-admin/js/color-picker.min.js	https://www.pairfum.com/wp-admin/customize.php?return=%2Fwp-admin%2Fadmin.php%3Fpage%3Dlitespeed-toolbox
12/12/2020 15:59	jQuery.fn.mousedown() event shorthand is deprecated	WordPress core	https://www.pairfum.com/wp-admin/js/iris.min.js	https://www.pairfum.com/wp-admin/customize.php?return=%2Fwp-admin%2Fadmin.php%3Fpage%3Dlitespeed-toolbox
12/12/2020 16:48	jQuery.fn.click() event shorthand is deprecated	WordPress core	https://www.pairfum.com/wp-admin/js/customize-nav-menus.min.js	https://www.pairfum.com/wp-admin/customize.php?return=%2Fwp-admin%2Fadmin.php%3Fpage%3Dlitespeed-toolbox
Contract

Hopefully, this list makes it a little easier for you.

Kind regards,

Pairfum London

**Comment by maloherry** [comment]
We can't edit variations in variable products without Enable jQuery Migrate Helper plugin and downgrading to the old version of jQuery.

**Comment by rodrigoprimo** [comment]
Thanks for the list, @Pairfum-London. I will check it once we resume working on this early next year.

@maloherry, I'm not able to reproduce this issue. Maybe the problem you are having is due to another plugin that you have installed? If not, and you experience this issue on a site with only WooCommerce installed, could you please open a separate issue with details on how to replicate this bug?

**Comment by mrleemon** [comment]
The Flexslider script shipped with WC makes plenty use of the `bind()` function and other obsolete features. Do you plan to update it to remove the jQuery deprecations?

**Comment by jonathansadowski** [comment]
I'm closing this, as it was supposed to be closed when #29044 was merged.
