### ISSUE TITLE
Warning in customizer

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce#28297]
**Describe the bug**
Support forum report: https://wordpress.org/support/topic/warning-sprintf-class-wc-shop-customizer-php/

https://github.com/woocommerce/woocommerce/blob/master/includes/customizer/class-wc-shop-customizer.php#L535

- The `sprintf()` placeholder should have the positional argument
- The plugin URL should be directly to `wordpress.org` instead of the locale subdomain

This issue may have surfaced for this customer due to an issue in a translation file. Changing the string would mean that it doesn't match any lookup strings.

**Comment by roykho** [comment]
So we have `%s` used all throughout the code base (valid uses). I am wondering what is special about the usage here that causes the issue? Or are you stating any translation where the lookup string has changed would cause this issue if we're not using positional placeholders? If so, it would seem we need to fix this all throughout the code base.

**Comment by Robertght** [comment]
Hey @roykho! There are some warnings that were shared in the thread as well:

```
– Warning: sprintf(): Too few arguments in /home/customer/www/mycitystore.it/public_html/wp-content/plugins/woocommerce/includes/customizer/class-wc-shop-customizer.php on line 535

– Warning: Cannot modify header information – headers already sent by (output started at /home/customer/www/mycitystore.it/public_html/wp-content/plugins/woocommerce/includes/customizer/class-wc-shop-customizer.php:535) in /home/customer/www/mycitystore.it/public_html/wp-includes/functions.php on line 6274
```

**Comment by claudiosanches** [comment]
This one is probably an issue with the translation, probably someone saved a string without any placeholder, that's why is causing this issue, and by just changing the string will return in English correctly like we entered on WooCommerce. I don't think we need to fix all strings.

**Comment by claudiosanches** [comment]
I just reverted #28401 because this isn't fix anything, it really need to be fixed on the translation.

**Comment by brambil** [comment]
The bug is back. 
```
Fatal error: Uncaught Error: 3 arguments are required, 2 given
in /home2/pcnsavid/public_html/wp-content/plugins/woocommerce/includes/customizer/class-wc-shop-customizer.php on line 535

Stack di chiamate:

sprintf()
wp-content/plugins/woocommerce/includes/customizer/class-wc-shop-customizer.php:535
WC_Shop_Customizer::add_product_images_section()
wp-content/plugins/woocommerce/includes/customizer/class-wc-shop-customizer.php:44
WC_Shop_Customizer::add_sections()
wp-includes/class-wp-hook.php:307
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:331
WP_Hook::do_action()
wp-includes/plugin.php:474
do_action()
wp-includes/class-wp-customize-manager.php:933
WP_Customize_Manager::wp_loaded()
wp-includes/class-wp-hook.php:307
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:331
WP_Hook::do_action()
wp-includes/plugin.php:474
do_action()
wp-settings.php:609
require_once()
wp-config.php:95
require_once()
wp-load.php:50
require_once()
wp-blog-header.php:13
require()
index.php:17
```
