### ISSUE TITLE
In stock format when changing low stock amount on product lvl

### ISSUE THREAD

**Issue by mathiasdb** [woocommerce/woocommerce#28294]
**Prerequisites**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I have the following settings in my WP Admin: WooCommerce > Products > Stock:
- [x] Manage stock
- [x] Hold stock for 30 minutes
- [x] Low stock notifications
- [x] No stock notifications
- [x] Low stock quantity: 5
- [x] No stock quantity: 0
- [x] Stock format: "low amount"

**Expected behavior**
When a product has a stock amount lower than 5, the "in stock" message on the single product page changes from "%s in stock" to "Only %s left in stock".

**Actual behavior**
When changing the "low stock amount" on product level, a.k.a. setting a "low stock amount" for a specific product. The message on the single product page does not change from "%s in stock" to "Only %s left in stock".

**Possible solution**
The function wc_format_stock_for_display() handles this. This function is located at woocommerce/includes/wc-formatting-functions.php at line 1187.

Changing the if-statement for "low_amount" from this:

`if ( $stock_amount <= get_option( 'woocommerce_notify_low_stock_amount' ) ) {`

to this, resolves the issue for me:

`if ( $stock_amount <= wc_get_low_stock_amount( $product ) ) {`

I'm sorry if this is not a bug. Could be expected behaviour but then I would change the "wording" / "labeling" on the fields.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://staging.kvk.be
Site address (URL): https://staging.kvk.be
WC Version: 4.7.0
REST API Version: ✔ 4.7.0
WC Blocks Version: ✔ 3.6.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.3
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: –
Language: nl_NL
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.12
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 20000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.31-34-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.7.0
WC Database Prefix: wp_
Totale databasegrootte: 23.87MB
Database datagrootte: 18.12MB
Database index grootte: 5.75MB
wp_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
kvk_abonnees: Data: 0.04MB + Index: 0.06MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_apto_sort_list: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_fbv: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fbv_attachment_folder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_entry: Data: 0.58MB + Index: 0.05MB + Engine MyISAM
wp_gf_entry_meta: Data: 0.65MB + Index: 0.62MB + Engine MyISAM
wp_gf_entry_notes: Data: 0.06MB + Index: 0.02MB + Engine MyISAM
wp_gf_form: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_gf_form_meta: Data: 0.21MB + Index: 0.00MB + Engine MyISAM
wp_gf_form_revisions: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_gf_form_view: Data: 0.08MB + Index: 0.04MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_litespeed_img_optm: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 0.92MB + Index: 0.07MB + Engine MyISAM
wp_pmxi_files: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_pmxi_history: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_pmxi_images: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_pmxi_imports: Data: 0.05MB + Index: 0.00MB + Engine MyISAM
wp_pmxi_posts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_pmxi_templates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_postmeta: Data: 6.57MB + Index: 1.46MB + Engine MyISAM
wp_posts: Data: 0.73MB + Index: 0.27MB + Engine MyISAM
wp_realmedialibrary: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_realmedialibrary_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_realmedialibrary_posts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_redirection_404: Data: 5.85MB + Index: 1.15MB + Engine MyISAM
wp_redirection_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_redirection_items: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wp_redirection_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.01MB + Index: 0.03MB + Engine MyISAM
wp_term_relationships: Data: 0.05MB + Index: 0.11MB + Engine MyISAM
wp_term_taxonomy: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_usermeta: Data: 1.37MB + Index: 0.76MB + Engine MyISAM
wp_users: Data: 0.09MB + Index: 0.07MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

acf-field: 116
acf-field-group: 13
album: 1
apto_sort: 2
attachment: 2073
fluo-block: 2
nav_menu_item: 47
news-item: 252
oembed_cache: 41
opta_match: 35
opta_player: 29
opta_team: 19
page: 59
partner: 9
post: 121
product: 81
product_variation: 308
revision: 74

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Foutmeldingen zouden niet getoond moeten worden aan bezoekers.

### Active Plugins (22) ###

Gravity Forms: door Gravity Forms – 2.4.21
Advanced Custom Fields PRO: door Elliot Condon – 5.9.3
Advanced Post Types Order: door Nsp Code – 4.3.8.3
Autoptimize: door Frank Goossens (futtta) – 2.7.8
Klassieke editor: door WordPress-bijdragers – 1.6
Disable Comments: door WPDeveloper – 1.11.0
Enable Media Replace: door ShortPixel – 3.5.0
Favicon door RealFaviconGenerator: door Philippe Bernard – 1.3.18
FileBird Lite: door Ninja Team – 4.1
Fluo Core: door Mathias De Beyser – 20.10.16-1500
Limit Login Attempts Reloaded: door WPChef – 2.15.2
Members: door MemberPress – 3.1.3
OptaSports: door Mathias De Beyser – 20.08.20-2315
Redirection: door John Godley – 4.9.2
Resize Image After Upload: door ShortPixel – 1.8.6
Sports Alliance SSO: door Mathias De Beyser – 20.10.22-1450
SVG Ondersteuning: door Benbodhi – 2.3.18
UsageDD: door Dion Designs – 1.4.7
Usersnap: door Usersnap – 4.9
WooCommerce: door Automattic – 4.7.0
WP Crontrol: door John Blackbourn & crontributors – 1.8.5
WP Rocket | No Cache for Admins: door WP Rocket Support Team –

### Inactive Plugins (4) ###

Redis Object Cache: door Till Krüss – 2.0.15
SendCloud | Smart Shipping Service: door SendCloud B.V. – 1.1.2
WooCommerce Multi-Step Checkout: door SilkyPress – 2.12
WP Rocket: door WP Media – 3.7.0.1

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Redis Object Cache Drop-In

### Must Use Plugins (1) ###

installatron_hide_status_test.php: door  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Winkelbasis: #2145 - /shop/
Winkelmand: #2146 - /winkelmand/
Afrekenen: #2147 - /afrekenen/
Mijn account: #2148 - /my-kvk/
Algemene voorwaarden: ❌ Pagina niet ingesteld

### Theme ###

Name: Fluo Child
Version: 19.09.29-1000
Author URL: https://www.spotdesign.be/
Child Theme: ❌ – Als je wijzigingen aanbrengt in WooCommerce of in een hoofdthema dat je niet zelf gebouwd hebt
raden we het gebruik van een child thema aan. Zie: Hoe maak je een child thema

WooCommerce Support: ✔

### Templates ###

Archive Template: Jouw thema heeft een woocommerce.php bestand. Je zal het woocommerce/archive-product.php template niet kunnen overschrijven omdat woocommerce.php prioriteit heeft over archive-product.php. Dit is bedoeld om weergave-problemen te voorkomen.
Overrides: fluo-child-theme/woocommerce/myaccount/dashboard.php
fluo-child-theme/woocommerce/myaccount/form-edit-account.php
fluo-child-theme/woocommerce/myaccount/form-login.php
fluo-child-theme/woocommerce/myaccount/my-account.php
fluo-child-theme/woocommerce/myaccount/navigation.php

### Action Scheduler ###

Afgerond: 6
Oldest: 2020-10-19 14:45:06 +0200
Newest: 2020-11-16 11:41:02 +0100

`
</details>

**Comment by mathiasdb** [comment]
@see https://github.com/woocommerce/woocommerce/compare/master...mathiasdb:patch-1

**Comment by rrennick** [comment]
@mathiasdb Thanks for reporting the issue and patch. I was able to reproduce the issue with the details you provided. Could you create a pull request from your patch?

**Comment by mathiasdb** [comment]
@rrennick I got an error when requesting => At least 1 approving review is required by reviewers with write access. Could you please review the patch?

**Comment by rrennick** [comment]
@mathiasdb Yes, all PRs require an approving review. Here are the instructions for creating a PR https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request
