### ISSUE TITLE
Twenty Twenty One home page

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#28308]
Please ensure the 2021 home page (similar to what storefront creates) looks good:

- [ ] wide screen layout
- [ ] middle screen layout (e.g. ipad)
- [ ] narrow screen layout (e.g. iphone)
- [ ] test with nonsquare product images (narrow and horizontally wider)
- [ ] Chrome
- [ ] Safari
- [ ] Firefox

Make sure the transitions between the layout widths look sensible (e.g. if the menu is still in narrow layout mode but the rest of the content in wide layout mode, it might be suboptimal, but please use your best judgment).

**Comment by jonathansadowski** [comment]
After picking up the work @rodrigoprimo started and digging into this issue a bit further, it appears that home page compatibility really breaks down into two parts:

1. Ensuring that our shortcodes are compatible with 2021.
2. Ensuring that blocks are compatible with 2021.

The latter seems to be tracked in https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3433, any thoughts on whether we should update this issue to "Twenty Twenty-One Short Codes"?

**Comment by peterfabian** [comment]
I think it makes sense, as blocks compatibility is handled in another repo.

**Comment by peterfabian** [comment]
Were you able to verify the homepage with the shortcodes @jonathansadowski ? Shall we close this one or does it need more work? Thx!
