### ISSUE TITLE
Twenty Twenty One checkout page

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#28305]
Please ensure the 2021 checkout page looks good:

- [ ] wide screen layout
- [ ] middle screen layout (e.g. ipad)
- [ ] narrow screen layout (e.g. iphone)
- [ ] test with nonsquare product image and missing image
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] select2 dropdown for countries looks good
- [ ] proportions of address vs product overview is nice
- [ ] can apply coupon code and it looks good
- [ ] notices look good (e.g. when coupon does not exist)
- [ ] an indication of a missing field looks good (i.e. maybe the field is highlighted, notice above looks good)
- [ ] test with different payment gateways, e.g. WC Pay, Stripe, PayPal

Make sure the transitions between the layout widths look sensible (e.g. if the menu is still in narrow layout mode but the rest of the content in wide layout mode, it might be suboptimal, but please use your best judgment).

**Comment by ObliviousHarmony** [comment]
Everything seems to be good here!
