### ISSUE TITLE
Twenty Twenty One product category page

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#28309]
Please ensure the 2021 product category page looks good:

- [ ] wide screen layout
- [ ] middle screen layout (e.g. ipad)
- [ ] narrow screen layout (e.g. iphone)
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] ~~dropdown for sorting looks good~~
- [ ] ~~adding to cart behaves nicely -- indication of button press, etc~~

Make sure the transitions between the layout widths look sensible (e.g. if the menu is still in narrow layout mode but the rest of the content in wide layout mode, it might be suboptimal, but please use your best judgment).

**Comment by roykho** [comment]
I started looking into this and I found this has been taken care of by this PR here https://github.com/woocommerce/woocommerce/pull/28340

So closing this one as it's not relevant anymore.
