### ISSUE TITLE
Twenty Twenty One cart page

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#28304]
Please ensure the 2021 cart page looks good:

- [ ] wide screen layout
- [ ] middle screen layout (e.g. ipad)
- [ ] narrow screen layout (e.g. iphone)
- [ ] test with nonsquare product images (narrow and horizontally wider) and missing image
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] empty cart
- [ ] cart with some products
- [ ] can apply coupon code and it looks good
- [ ] notices look good (e.g. when hold stock is enabled, can't add to cart, or when coupon does not exist/has already been used too many times)

Make sure the transitions between the layout widths look sensible (e.g. if the menu is still in narrow layout mode but the rest of the content in wide layout mode, it might be suboptimal, but please use your best judgment).

**Comment by ObliviousHarmony** [comment]
Everything is looking good here!
