### ISSUE TITLE
Twenty Twenty One single product page

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#28303]
Please ensure the 2021 single product page looks good:

- [ ] wide screen layout
- [ ] middle screen layout (e.g. ipad)
- [ ] narrow screen layout (e.g. iphone)
- [ ] test with nonsquare product image and missing image
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] tabs with description works fine
- [ ] reviews and star rating looks good
- [ ] variable product tested
- [ ] simple product tested
- [ ] a product without description tested
- [ ] a product with description tested
- [ ] a product without a gallery of images
- [ ] a product with a gallery of images
- [ ] add to cart works well and notice (that the product was added to cart) looks good

Make sure the transitions between the layout widths look sensible (e.g. if the menu is still in narrow layout mode but the rest of the content in wide layout mode, it might be suboptimal, but please use your best judgment).

**Comment by ObliviousHarmony** [comment]
Everything looks good here!
