### ISSUE TITLE
Coupon discount amount calculated differently when coupon is applied, then removed, and then reapplied

### ISSUE THREAD

**Issue by preston-dvorak** [woocommerce/woocommerce#28301]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When adding a coupon to a new order being created in the admin area, the discount amount changes if you apply the coupon, remove it, and then re-apply the same coupon. This only seems to happen when tax caluclations are enabled, a tax rate is set, and the item prices are inclusive of tax.

**Expected behavior**
It's expected that the calculated discount amount stays the same no matter how many times a coupon is added or removed.

**Actual behavior**
The first time the coupon is applied, the discount amount seems to be caluclated with the tax rate removed (e.g. if the tax rate is 10%, the calculated discount amount will be 10% lower).
After the coupon is removed and re-applied to the same order, the discount amount is caculated using the item's actual price.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Enable tax calculations under Woocommerce > Settings > General
2. Under Woocommerce > Settings > Tax, check "Yes, I will enter prices inclusive of tax." (Other settings didn't make a difference in my testing.)
3. Under Woocommerce > Settings > Tax > Standard Rates, be sure a row is set with a "Rate %" entered.
4. Create a product under Woocommerce > Products, be sure it has a Regular Price entered, is Taxable, and the Tax Class is Standard.
5. Create a coupon under Marketing > Coupons, be sure Discount Type is "Percentage discount" and a Coupon Amount is set.
6. Under Woocommerce > Orders, click "Add Order"
7. Click the "Add item(s)" button, add the product created in step 4.
8. Click the "Apply coupon" button, apply the coupon code created in step 5.
9. Note the "discount amount" under the Total column next to the product.
10. Remove the coupon by clicking the "x" next to the coupon code under the item list.
11. Click the "Apply coupon" button, apply the same coupon code created in step 5.
12. Note the "discount amount" under the Total column next to the product, which is different than it was after step 9.

 

**Screenshots**
![woo-bug-firstcouponapp](https://user-images.githubusercontent.com/34477288/99365557-113a7980-287d-11eb-8669-a1e59871bf81.jpg)
![woo-bug-secondcouponapp](https://user-images.githubusercontent.com/34477288/99365589-1e576880-287d-11eb-8b14-7724a5fadf38.jpg)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): http://NA/freshwp
Site address (URL): http://NA/freshwp
WC Version: 4.7.0
REST API Version: ✔ 4.7.0
WC Blocks Version: ✔ 3.6.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.3
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.2.31
PHP Post Max Size: 128 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.62.0
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 10.2.31-MariaDB-log-cll-lve
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.7.0
WC Database Prefix: fwp_
Total Database Size: 3.73MB
Database Data Size: 2.32MB
Database Index Size: 1.41MB
fwp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fwp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fwp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fwp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
fwp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fwp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fwp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
fwp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fwp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fwp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fwp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fwp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fwp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fwp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fwp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
fwp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fwp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fwp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fwp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fwp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
fwp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fwp_options: Data: 1.48MB + Index: 0.06MB + Engine InnoDB
fwp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fwp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
fwp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fwp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fwp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fwp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fwp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fwp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fwp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fwp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fwp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fwp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fwp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fwp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fwp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
fwp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
fwp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
fwp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
fwp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
fwp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
fwp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 7
post: 2
product: 1
revision: 1
shop_coupon: 1
shop_order: 9

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.7.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 24
Oldest: 2020-11-17 01:46:22 +0000
Newest: 2020-11-17 07:27:12 +0000

`
</details>

**Comment by rrennick** [comment]
@preston-dvorak Thanks for submitting the issue. I wasn't able to reproduce it in my install. Here are the details on my test settings

Tax Rate: 15%
Product:
<img width="527" alt="Screen Shot 2020-11-26 at 12 36 15 PM" src="https://user-images.githubusercontent.com/343847/100375334-0356c800-2fe4-11eb-8f4f-47edb6689e82.png">

Tax Settings:
<img width="456" alt="Screen Shot 2020-11-26 at 12 37 09 PM" src="https://user-images.githubusercontent.com/343847/100375410-1f5a6980-2fe4-11eb-9866-094672363a79.png">

Coupon:
<img width="692" alt="Screen Shot 2020-11-26 at 12 37 50 PM" src="https://user-images.githubusercontent.com/343847/100375466-38631a80-2fe4-11eb-8ba4-773a1f678abf.png">

Order (same every time I added the coupon):
<img width="928" alt="Screen Shot 2020-11-26 at 12 38 48 PM" src="https://user-images.githubusercontent.com/343847/100375587-69dbe600-2fe4-11eb-93c0-d0ca024d015f.png">

Could you compare those to yours and identify additional settings needed to reproduce the issue?
