### ISSUE TITLE
Twenty Twenty One log in page

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#28315]
Please ensure the 2021 Log In page looks good:

- [ ] wide screen layout
- [ ] middle screen layout (e.g. ipad)
- [ ] narrow screen layout (e.g. iphone)
- [ ] Chrome
- [ ] Safari
- [ ] Firefox
- [ ] possible notice looks good (e.g. when password is invalid)

Make sure the transitions between the layout widths look sensible (e.g. if the menu is still in narrow layout mode but the rest of the content in wide layout mode, it might be suboptimal, but please use your best judgment).

**Comment by ObliviousHarmony** [comment]
The only problem I see here is that the checkmark in the checkbox is oddly off-center.

**Comment by peterfabian** [comment]
Closing, 2021 compat has shipped.
