### ISSUE TITLE
Defensive defaults for wc_date_format and wc_time_format

### ISSUE THREAD

**Issue by aheckler** [woocommerce/woocommerce#28319]
**Is your feature request related to a problem? Please describe.**

WP core does not warn users when they select a custom date or time format, but leave the text box blank, like so:

![Markup 2020-08-26 at 15 33 03](https://user-images.githubusercontent.com/5512652/99399134-3f3ab080-28b3-11eb-959e-be545e7339ce.png)

This can cause issues with our plugins, e.g. Bookings example: 2930-gh-woocommerce/woocommerce-bookings and a Subscriptions backend display problem:

![Markup on 2020-11-17 at 09:02:00](https://user-images.githubusercontent.com/5512652/99399402-9f315700-28b3-11eb-82ab-41bdb6cf0405.png)

**Describe the solution you'd like**

We should code `wc_date_format` and `wc_time_format` a bit more defensively. They can probably fall back to the default date and time formats if we detect that `date_format` and `time_format` are empty.

**Describe alternatives you've considered**

None yet.

**Additional context**

None.

**Comment by roykho** [comment]
Hey @aheckler - So I think the reason WP core allows you to do this is because some people don't want to show date or time on their site. While this not as big of a deal for blog posts, I would imagine they would need date/time for an ecommerce site.

With that said, would adding in a default here override the intended behavior of allowing people to not show date/time if they really wanted? Perhaps let them have that choice if they really wanted? I think it would be better for them to just add something in custom field than to force an override. IMO anyways.

**Comment by aheckler** [comment]
> So I think the reason WP core allows you to do this is because some people don't want to show date or time on their site. While this not as big of a deal for blog posts, I would imagine they would need date/time for an ecommerce site.

Agreed.

> With that said, would adding in a default here override the intended behavior of allowing people to not show date/time if they really wanted? 

I mean... I guess this does change the current behavior for people who have blank date/time formats on purpose. But doing that _on an ecommerce site_ seems like an extreme edge case. You even agreed with me above. 😛 

> Perhaps let them have that choice if they really wanted?

If someone actually needs empty date/time formats, they can use the available filters like so:

```
add_filter( 'woocommerce_date_format', '__return_empty_string' ); 
add_filter( 'woocommerce_time_format', '__return_empty_string' ); 
```

> I think it would be better for them to just add something in custom field than to force an override.

Well, yes, but that would be a core WP fix right? This is something we can do on our side to be a bit more defensive about misconfigured options in WP core.

**Comment by roykho** [comment]
I am 50/50 on this however the argument here is that you're forcing a date/time for them when the intended design of having empty `Custom` field affords them the ability to hide it.

So it comes down to is it easier for them to just add in a date string format when they want to use a custom format or is it easier for them to add code using the filter to hide the date/time. I would say the former.

But as I stated before though, it is not likely for an ecommerce store to not have date/time on orders and such...Thus I am ok with this change as well.

**Comment by aheckler** [comment]
> I am 50/50 on this however the argument here is that you're forcing a date/time for them when the intended design of having empty `Custom` field affords them the ability to hide it.

That is true, but having empty formats with WC isn't just a cosmetic issue. It actually breaks things:

- Bookings: 2930-gh-woocommerce/woocommerce-bookings
- Subscriptions: 3489058-zen
- Probably lots more

This change makes WC resilient to that, while still allowing people to blank out the formats if they wish, via the filters.
