### ISSUE TITLE
Woocommerce SKU Variation 

### ISSUE THREAD

**Issue by paulbreco** [woocommerce/woocommerce#28334]
I have an issue in my Woocommerce in all my products, 

When I try to select a variation, and add to cart It shows "no stock", for that product. 
![image](https://user-images.githubusercontent.com/50209255/99581995-7bebd200-29af-11eb-84f0-cf7268960a3b.png)

The button of add to cart is using the parent SKU or product ID (i don't know) instead of the variation SKU, 
I have this configuration:
![image](https://user-images.githubusercontent.com/50209255/99582469-25cb5e80-29b0-11eb-9a12-ebe029923b06.png)
![image](https://user-images.githubusercontent.com/50209255/99582609-5ca17480-29b0-11eb-8737-13225de9f1b2.png)

how can I fix this problem?

**Comment by paulbreco** [comment]
I manage to solve the problem changing the theme it was old, it wasn't update since 1 year ago.

**Comment by tammullen** [comment]
Thanks for the update @paulbreco 
Looks like we can close this for now, if I missed something, please leave a comment and we will take a second look.
