### ISSUE TITLE
WooCommerce (Order) > Orders screen > Add New Order > Select product popup > VisibleHTML markup

### ISSUE THREAD

**Issue by khoipro** [woocommerce/woocommerce#28345]
**Prerequisites (mark completed items with an [x]):**

- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

On the Add new order screen, when selecting existing product to add to new order, it displays unfriendly HTML markup.

**Expected behavior**

The input field contains only product title.

**Actual behavior**

The input field displays the markup with `<span class="description"></span>`.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Login to wp-admin
2. Navigate to WooCommerce > Orders
3. Add new order
4. Click on Add item button
5. Click on Add product, and popup appears.
6. Enter any product name, such as "Shirt" (I'm using the sample data from woocommerce)

**Screenshots**

<img width="813" alt="Screenshot_3" src="https://user-images.githubusercontent.com/10395311/99752254-8d032300-2b16-11eb-97e8-25ec0ad11c89.png">

**WordPress Environment**

<details>
`
### WordPress Environment ###

WordPress address (URL): http://ecom2.test
Site address (URL): http://ecom2.test
WC Version: 4.7.0
REST API Version: ✔ 4.7.0
WC Blocks Version: ✔ 3.6.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.3
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.3.5
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.64.0
OpenSSL/1.1.1b

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.7.0
WC Database Prefix: wp_
Total Database Size: 3.91MB
Database Data Size: 2.48MB
Database Index Size: 1.43MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.50MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 25
customize_changeset: 6
nav_menu_item: 2
page: 6
post: 2
product: 18
product_variation: 7
shop_order: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (8) ###

Loco Translate: by Tim Whitlock – 2.4.5
WooCommerce Bulk Variations: by Lucas Stark – 1.6.6 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce Checkout Field Editor: by WooCommerce – 1.5.36 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce One Page Checkout: by Automattic – 1.7.9 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce Product Enquiry Form: by WooCommerce – 1.2.16 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce Tab Manager: by SkyVerge – 1.13.1 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce Variation Swatches and Photos: by Lucas Stark – 3.1.2 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce: by Automattic – 4.7.0

### Inactive Plugins (5) ###

WooCommerce Customer/Order/Coupon CSV Import Suite: by SkyVerge – 3.9.1 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce Email Customizer: by WooCommerce – 1.1.18 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce Quick View: by WooCommerce – 1.2.12 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce Sales Report Email: by WooCommerce – 1.1.17 – Installed version not tested with active version of WooCommerce 4.7.0
WooSlider: by WooThemes – 2.4.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: VND (₫)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 1
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Woostify
Version: 1.7.7
Author URL: https://woostify.com/about
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 6
Oldest: 2020-11-19 15:15:35 +0000
Newest: 2020-11-20 02:51:16 +0000

Pending: 1
Oldest: 2020-11-20 02:54:35 +0000
Newest: 2020-11-20 02:54:35 +0000

`
</details>

**Comment by tammullen** [comment]
Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/27154. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
