### ISSUE TITLE
Write new e2e test: Merchant / Orders / Apply Coupon

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#28359]
Write a new e2e test that covers `Merchant / Orders / Apply Coupon` flow.

**Comment by zhongruige** [comment]
I'll work on getting these tests added to the e2e test suite, applying the coupon and verifying the price changes when editing an order:

![Screen Shot 2020-11-23 at 9 33 29 PM](https://user-images.githubusercontent.com/71906536/100049032-9371f300-2dd3-11eb-9877-f71f3ad38304.png)

**Comment by zhongruige** [comment]
As I've been looking into this issue, my current thinking is I could potentially add the product as a Store Owner/Customer flow to an order or set up free shipping and apply the coupon that way.

I tested if fees could work in this flow, but it doesn't appear coupons can be applied to fees:

![Screen Shot 2020-11-26 at 2 07 12 PM](https://user-images.githubusercontent.com/71906536/100391617-3b183c80-2ff1-11eb-802f-56d4c963229b.png)

I'd like to keep the test a bit more self-contained without relying on setting up free shipping etc., so, I'm curious on what people think about either adding a product or going the free shipping route to test applying a coupon to an order, or if there's any other suggestions. Thanks!

**Comment by zhongruige** [comment]
Thanks for the follow up @tammullen! I'll go that direction for this test.
