### ISSUE TITLE
Write new e2e test: Merchant / Orders / Filter Orders by order status

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#28360]
Write a new e2e test that covers `Merchant / Orders / Filter Orders` flow.

**Comment by zhongruige** [comment]
I'll work on getting these tests added to the e2e test suite, running through the filters on the order list page for each status:

![Screen Shot 2020-11-23 at 9 31 07 PM](https://user-images.githubusercontent.com/71906536/100048921-4a21a380-2dd3-11eb-8896-4fb127258b75.png)
