### ISSUE TITLE
WooCommerce breaks other plugin's ability to send POST requests to REST API (rest_cookie_invalid_nonce)

### ISSUE THREAD

**Issue by cabrerahector** [woocommerce/woocommerce#28364]
**Prerequisites (mark completed items with an [x]):**

- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

One of my plugin users reported that [WordPress Popular Posts](https://wordpress.org/plugins/wordpress-popular-posts/) can no longer track post/page/product views after adding any product to the shopping cart (see [popular-posts returns error 403 and rest_cookie_invalid_nonce code in json](https://wordpress.org/support/topic/popular-posts-returns-error-403-and-rest_cookie_invalid_nonce-code-in-json/)). I was able to reproduce this behavior with a fresh WordPress install with only WooCommerce and WordPress Popular Posts enabled.

**Expected behavior**

Adding a product to the cart shouldn't break WPP's (and potentially other plugins') ability to send POST requests to the REST API.

**Actual behavior**

Adding a product to the cart breaks WPP's (and potentially other plugins') ability to send POST requests to the REST API.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**

Steps to reproduce the bug:

1. Installed a fresh copy of WordPress.
2. Installed the latest version of the WooCommerce plugin (4.7.0 at the time of writing) and completed its set up process (I installed the bare minimum options, no Jetpack nor the other service/product offerings.)
3. Installed the latest version of the WordPress Popular Posts plugin (that's 5.2.4 at the moment.)
4. Used stock settings, didn't change anything.
5. Visited a product page and WordPress Popular Posts was able to track the product view (the plugin sends a POST request to /wp-json/wordpress-popular-posts/v1/popular-posts), REST API's response was 201 (created) as expected.
6. Visited a post page and WordPress Popular Posts was able to track the visit normally again.
6. Went back to the product I visited earlier and then added it to the cart using Storefront's _Add to Cart_ button.
7. The REST API now responds with Error 403 rest_cookie_invalid_nonce whenever WordPress Popular Posts tries to track any post/page/product view afterwards.
8. This issue apparently only affects the current session. Open a new Incognito window, repeat the steps above and WordPress Popular Posts will track views normally again until you add any product to the cart.

I recorded this process if it makes things easier, please check below.

**Screenshots**

Video capture: https://cabrerahector.com/wc-wpp-rest-api-403-invalid-nonce.mp4

**Isolating the problem (mark completed items with an [x]):**

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with the [Storefront](https://woocommerce.com/storefront/) theme active.
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
### WordPress Environment ###

WordPress address (URL): http://wp.local
Site address (URL): http://wp.local
WC Version: 4.7.0
REST API Version: ✔ 4.7.0
WC Blocks Version: ✔ 3.6.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.3
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.38 (Raspbian)
PHP Version: 7.3.19-1~deb10u1
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 1800
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.25-MariaDB-0+deb10u1
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.7.0
WC Database Prefix: wp_
Total Database Size: 3.49MB
Database Data Size: 2.03MB
Database Index Size: 1.46MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.03MB + Index: 0.06MB + Engine InnoDB
wp_popularpostsdata: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_popularpostssummary: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_postmeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.08MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
customize_changeset: 1
page: 8
post: 6
product: 12
revision: 3

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce: by Automattic – 4.7.0
WordPress Popular Posts: by Hector Cabrera – 5.2.4

### Inactive Plugins (12) ###

Advanced Custom Fields: by Elliot Condon – 5.9.3
FakerPress: by Gustavo Bordoni – 0.5.0
Gutenberg: by Gutenberg Team – 9.4.1
Health Check & Troubleshooting: by The WordPress.org community – 1.4.5
Polylang: by WP SYNTEX – 2.8.4
WooCommerce Stripe Gateway: by WooCommerce – 4.5.5 – Installed version not tested with active version of WooCommerce 4.7.0
WordPress Reset: by Aristeides Stathopoulos
Matt Martz – 1.4.2

WPML CMS Nav: by OnTheGoSystems – 1.5.2
WPML Media: by OnTheGoSystems – 2.5.5
WPML Multilingual CMS: by OnTheGoSystems – 4.3.11
WPML String Translation: by OnTheGoSystems – 3.0.8
WPML Translation Management: by OnTheGoSystems – 2.9.5

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #18 - /shop/
Cart: #19 - /cart/
Checkout: #20 - /checkout/
My account: #21 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.9.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 6
Oldest: 2020-11-21 17:43:24 +0000
Newest: 2020-11-21 18:18:45 +0000

```
</details>

**Comment by rrennick** [comment]
Hi @cabrerahector,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end following the steps you provided. 

We’re going to solve this bug as soon as possible. Stay tuned for updates.

**Comment by cabrerahector** [comment]
Don't mention it, Ron. If there's anything at all I can do to help please don't hesitate to ask.

**Comment by FuegoConQueso** [comment]
I've been having the same error, though without adding any items to the cart, with Contact Forms 7 form submissions.

The quick fix I'm using is to modify class-wp-session-handler.php in woocommerce with the following function:
`	public function nonce_user_logged_out( $uid, $action ) {
	    if ($action != 'wp_rest') {
    		return $this->has_session() && $this->_customer_id ? $this->_customer_id : $uid;
	    }
	    return $uid;
	}`
You'll also need to update the related add_filter() in that file to accommodate the new argument.

Not sure if it will fix your error, but it might be worth a try.

**Comment by cabrerahector** [comment]
Not sure if that's the proper way to fix things @FuegoConQueso but it does work (or at least it seems that adding a product to the cart no longer invalidates the nonce WPP uses to communicate with the REST API) so thanks for sharing. Might serve as a temporary workaround while we wait for the WC team to come up with a proper patch.

**Comment by FuegoConQueso** [comment]
Yeah, @cabrerahector, it's definitely not the *right* way to fix it, but it's the only temporary work around I could find that works. Ultimately, to play nicely with other plugins, I *think* WC team would need to change their nonce_user_logged_out to either a) make all nonce actions "opt-in" (most secure, but most likely to make wc other plugins break/ insecure), b) allow nonce actions to be opted out by other plugins (obvious potential security problems), or c) just opt out wp_rest (I do not believe they use that nonce for anything secure). But regardless, I am eagerly awaiting an update that is better than my duct tape fix, lol

**Comment by gerakleist** [comment]
@FuegoConQueso , what would be the appropriate update to the add_filter function for this to work?

**Comment by FuegoConQueso** [comment]
Update the line
`add_filter( 'nonce_user_logged_out', array( $this, 'nonce_user_logged_out' ) );`
To
`add_filter( 'nonce_user_logged_out', array( $this, 'nonce_user_logged_out' ), 10, 2 );`
The additional arguments are just priority (10, aka the default), and then the number of accepted arguments (default 1, but we need 2).

Note that this fix will break and have to be readded with every WooCommerce update, so use at your own peril.

**Comment by nikkez** [comment]
Thank you @FuegoConQueso for your solution!

I hope the official fix comes as soon possible.

**Comment by 5c0rp10** [comment]
@FuegoConQueso Thank you brother for the solutions, you saved my day.
@woocommerce Please fix the issue asap, its been months

**Comment by jbeales** [comment]
This has been driving me mad all day, I'm glad I found out why it's happening.

For the root cause: WooCommerce modifies the UID used to create nonces if a cart exists for a user. However, in class-woocommerce.php's init function there's [these couple of lines](https://github.com/woocommerce/woocommerce/blob/a46e889e3732a89f576cdcb900ef3aabc31254e6/includes/class-woocommerce.php#L602-L605):
```
// Classes/actions loaded for the frontend and for ajax requests.
if ( $this->is_request( 'frontend' ) ) {
       wc_load_cart();
}
```
`wc_load_cart()` adds the filter that modifies the UID, but `$this->is_request('frontend')` returns false for REST API requests.

Either we need to load the cart for all REST API requests or we need to pull out the UID-filtering functionality and use it in API requests. The UID filter is pretty tied in to the cart, so loading the cart for API requests is a simpler solution.

This manifests, in my case, in a situation where someone who has added an item to their cart or made a purchase can no longer submit requests through the Contact Form 7 contact form.

**Comment by claudiosanches** [comment]
@cabrerahector Thank you very much for starting this issue and for giving detailed steps to reproduce.
I helped a lot for me to debug this issue, but note that this is duplicated of #23682 so I'm closing this one for now.
I'll start a PR in a few minutes with something that can solve both issues.
Thanks!

**Comment by phillipcornwell** [comment]
@claudiosanches This issue seems to be occurring in v5.2.1 now. Should this be reopened?

29016818-hc

**Comment by cabrerahector** [comment]
Well, according to their [Milestones](https://github.com/woocommerce/woocommerce/milestone/179?closed=1) the fix won't be available until May 11 when the WC team will release version 5.3.0. That's why the issue is still present with version 5.3.1 @philipdowner.

I guess this issue won't be reopened as it has been already fixed. It's the patch that won't be shipped to the official WP repository just yet.
