### ISSUE TITLE
Legacy image sizes have not been discontinued after version 4.6.0

### ISSUE THREAD

**Issue by kanlukasz** [woocommerce/woocommerce#28369]
**Prerequisites:**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug - NOT SURE IT'S BUG OR JUST A LITTLE MISTAKE**
Woocommerce was supposed to support older image sizes only up to version 4.6.0
Now we have 4.7.0 and you still support them.

```
/**
 * Legacy image sizes.
 *
 * @deprecated 3.3.0 These sizes will be removed in 4.6.0.
 */
add_image_size( 'shop_catalog', $thumbnail['width'], $thumbnail['height'], $thumbnail['crop'] );
add_image_size( 'shop_single', $single['width'], $single['height'], $single['crop'] );
add_image_size( 'shop_thumbnail', $gallery_thumbnail['width'], $gallery_thumbnail['height'], $gallery_thumbnail['crop'] );
```

**Steps to reproduce the bug**
1. Upload image
2. Check how many image sizes you have with `wp_get_registered_image_subsizes()`

**Additional info:**
- Does this cause us to generate more images with upload?
- Sorry for the broken issue template, but it did not fit the my problem description

**Comment by rrennick** [comment]
@kanlukasz Thanks for reporting the issue. The issue #28139 was created to address deprecation in general across the code base. I'm closing this issue in favour of it.
