### ISSUE TITLE
Variant data (price, sku, dimensions etc) does not save/update using the block editor for product post type.

### ISSUE THREAD

**Issue by mikkeltschentscher** [woocommerce/woocommerce#28383]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Using the block-editor for the product post type using WordPress 5.5.3 and WooCommerce 4.7.0 variant product data does not save when edited from within the metabox.

**Expected behavior**
Data should be saved when edited using Gutenberg Block Editor for products.

**Actual behavior**
When activating the block-editor for the product post type using WordPress 5.5.3 and WooCommerce 4.7.0 variant product data does not save when edited. Creating a new product, setting it as variable and adding multiple attributes and variants does save - but data (price, length, sku, etc) for each of the variants does not. Using the "variation_actions"-option, I however, can set and update prices for variants.

I also find this bug editing the excerpt of the product. It does not save after updating.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
1. Install WordPress 5.5.3
2. Install WooCommerce 4.7.0 and set Storefront as the default theme.
3. Create a variable product with 2 variants
4. Set the variant price to 100.
5. Activate the Gutenberg Block Editor for product post type.

```
function enable_block-editor_for_products($can_edit, $post_type){
	if($post_type == 'product'){$can_edit = true;}	
	return $can_edit;
}
add_filter('use_block_editor_for_post_type', 'enable_block-editor_for_products', 10, 2);
```

6. Try edit a variant price to 150. It wont save.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): http://localhost/danishskincare.dk
Site address (URL): http://localhost/danishskincare.dk
WC Version: 4.7.0
REST API Version: ✔ 4.7.0
WC Blocks Version: ✔ 3.6.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.3
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 500 MB
WP Debug Mode: –
WP Cron: ✔
Language: da_DK
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.0
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.60.0
OpenSSL/1.0.2o

SUHOSIN Installed: –
MySQL Version: 5.7.23
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.7.0
WC Database Prefix: wp_
Total databasestørrelse: 499.90MB
Database datastørrelse: 260.84MB
Database indexstørrelse: 239.06MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_items: Data: 7.52MB + Index: 3.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 54.59MB + Index: 43.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 33.56MB + Index: 28.09MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_entry_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 7.42MB + Index: 0.28MB + Engine InnoDB
wp_postmeta: Data: 120.67MB + Index: 136.42MB + Engine InnoDB
wp_posts: Data: 18.52MB + Index: 8.41MB + Engine InnoDB
wp_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_view: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rg_lead: Data: 0.19MB + Index: 0.03MB + Engine InnoDB
wp_rg_lead_detail: Data: 0.42MB + Index: 0.52MB + Engine InnoDB
wp_rg_lead_detail_long: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 1.52MB + Index: 0.47MB + Engine InnoDB
wp_term_taxonomy: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 13.52MB + Index: 16.03MB + Engine InnoDB
wp_users: Data: 1.52MB + Index: 0.80MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wppusher_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 342
acf-field-group: 36
attachment: 1479
before-and-after: 3
custom_css: 1
nav_menu_item: 15
oembed_cache: 18
page: 119
post: 603
product: 36
product_variation: 19
review: 95
revision: 262
shop_coupon: 184
shop_order: 7
shop_order_refund: 30
video: 4
woo_economic_log: 15061

### Security ###

Secure connection (HTTPS): ❌
					Din shop bruger ikke HTTPS. Få mere information om HTTPS og SSL Certifikater.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: af Automattic – 4.7.0

### Inactive Plugins (14) ###

Advanced Custom Fields PRO: af Elliot Condon – 5.9.3
Bambora Online Checkout: af Bambora – 4.4.3 – Den installerede version er ikke testet med den aktiverede version af WooCommerce 4.7.0
GLS Parcel Shops WooCommerce Integration: af Balboa & Bedford – 1.0.1 – Den installerede version er ikke testet med den aktiverede version af WooCommerce 4.7.0
Gravity Forms: af Gravity Forms – 2.4.21
Lazy Load - Optimize Images: af WP Rocket – 2.3.4
Partner-ads Danmark Woocommerce tracking og feed: af Partner-ads – 1.1.0 – Den installerede version er ikke testet med den aktiverede version af WooCommerce 4.7.0
WooCommerce Custom Checkout Options: af Francesco Carlucci – 0.1 – Den installerede version er ikke testet med den aktiverede version af WooCommerce 4.7.0
WooCommerce Klaviyo Integration: af Francesco Carlucci – 0.1 – Den installerede version er ikke testet med den aktiverede version af WooCommerce 4.7.0
WooCommerce Sequential Order Numbers Pro: af SkyVerge – 1.16.1 – Den installerede version er ikke testet med den aktiverede version af WooCommerce 4.7.0
WooCommerce Smart Coupons: af StoreApps – 4.12.2 – Den installerede version er ikke testet med den aktiverede version af WooCommerce 4.7.0
WooCommerce Table Rate Shipping: af WooCommerce – 3.0.30 – Den installerede version er ikke testet med den aktiverede version af WooCommerce 4.7.0
Yoast SEO: Video: af Team Yoast – 9.3
Yoast SEO: WooCommerce: af Team Yoast – 5.5 – Den installerede version er ikke testet med den aktiverede version af WooCommerce 4.7.0
Yoast SEO Premium: af Team Yoast – 9.3

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: DKK (DKK)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop basisside: #15051 - /produkter/
Kurv: #15020 - /cart/
Checkout: #15043 - /checkout/
Min konto: #15013 - /my-account/
Vilkår og betingelser: #15074 - /handelsbetingelser/

### Theme ###

Name: Storefront
Version: 2.9.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – Hvis du redigerer WooCommerce i et hovedtema
som du ikke selv har udviklet
anbefaler vi
at du anvender et undertema (child theme). Se: Hvordan du opretter et undertema

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Gennemført: 143
Oldest: 2020-10-26 15:29:00 +0100
Newest: 2020-11-24 08:14:13 +0100

`
</details>

**Comment by rrennick** [comment]
Hi @mikkeltschentscher ,

Thank you for reporting the issue. However, this issue had been reported previously here #23673. As explained on that issue, the product post doesn't currently support the block editor and will be addressed in a future release. We are closing your issue.

**Comment by mikkeltschentscher** [comment]
@rrennick 

OK. Thanks. We're looking forward to that :-)

**Comment by anteksiler** [comment]
Hi there,

When will this be activated?
