### ISSUE TITLE
Pagination for product attributes in admin panel

### ISSUE THREAD

**Issue by Bodrosh** [woocommerce/woocommerce#28382]
Hello, I ran into situations, a lot of attributes (more than 1000) are loaded into the system. In the admin panel on the edit.php?post_type=product&page=product_attributes they are displayed on the same page, wouldn’t it be better to do pagination, as for example in editing categories or products? With a large number of them on one page, problems with loading and performance may arise (I also noticed that when going to the pages of the admin panel and not only pages Woocommerce, register_taxonomies is called, if there are thousands of them, this causes a slowdown). Thanks.
![2020-11-20_09-32-46](https://user-images.githubusercontent.com/26584530/100058451-5856da80-2e3a-11eb-8398-432b16301e50.jpg)
![2020-11-24_09-50-16](https://user-images.githubusercontent.com/26584530/100058682-cdc2ab00-2e3a-11eb-9779-64b19b801359.jpg)

**Comment by rrennick** [comment]
Hi @Bodrosh,

Thank you for reporting the issue. However, this issue had been reported previously here #26539. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.

**Comment by Bodrosh** [comment]
Hello, @rrennick . Thank you, but code slows down a site with many taxonomies (with created global attributes), both backend and frontend (it loads on many pages, if not all):
\wp-content\plugins\woocommerce\includes\class-wc-post-types.php (205)
`$attribute_taxonomies  = wc_get_attribute_taxonomies();
		if ( $attribute_taxonomies ) {
			foreach ( $attribute_taxonomies as $tax ) {
                              ....
                              register_taxonomy(...);
                             ...
                      }
                }
`
Loading slows down for a few seconds, how can you overcome this problem? Thank's.
