### ISSUE TITLE
Returning false to woocommerce_shipping_calculator_enable_postcode breaks Shipping calculator

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#28393]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.

Related to #27491 

I normally return false to `woocommerce_shipping_calculator_enable_postcode` on stores where the shipping is only calculated based on the country + state, but since the last changes to the WC_Cart->show_shipping() function, when the postcode is a required field, we fail to get the shipping calculator to work as expected:
[08620cf](https://github.com/woocommerce/woocommerce/commit/08620cf8466054263d6975fb749c6b454d9dee34)
[7f2b322](https://github.com/woocommerce/woocommerce/commit/7f2b32208550a7b4f803cbe8748628c86dd126a3)

We should be able to have the postcode as a required field and, at the same time, be able to remove this field from the shipping calculator if not needed **because of the way we create shipping zones (not postcode based)**.

To be more clear: if the website is using only countries and states to set the shipping zones, it makes sense to remove the postcode from the calculator (even if later on on the checkout it is required) so the customer has a better and simpler UX on the cart.

I think adding a check to the `woocommerce_shipping_calculator_enable_postcode` filter at the `show_shipping` function would be enough to solve this issue. Not sure if this is a good idea to do on Country and State tho.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Solution:**
Changing class-wc-cart.php line 1540 to this will do it:
`if ( apply_filters( 'woocommerce_shipping_calculator_enable_postcode', true ) && isset( $country_fields['shipping_postcode'] ) && $country_fields['shipping_postcode']['required'] && ! $this->get_customer()->get_shipping_postcode() ) {`

Do you agree that this is a problem?
Should I open a PR?

**Comment by webdados** [comment]
Update: This only happens if "Hide shipping costs until an address is entered" is enabled.

If the shop owner passes `false` to `woocommerce_shipping_calculator_enable_postcode`, we can assume he's not using postcodes for shipping calculations (probably only countries and states), so I think we can safely show shipping if the shop customer only fills in the country and state even if "Hide shipping costs until an address is entered" is enabled, by adding `If( apply_filters( 'woocommerce_shipping_calculator_enable_postcode', true ) && ...` to line 1540 on class-wc-cart.php

**Comment by rrennick** [comment]
> Should I open a PR?

@webdados Would you write the PR and include steps to reproduce the issue?

**Comment by gbruzzo** [comment]
@webdados 

Hello there! 
We all our shipping rates are uniquely determined by country, with no reference to State, City or Postcode. 

We tested the following change in class-wc-cart.php (lines 1536 - 1542): 

```
			$country_fields = WC()->countries->get_address_fields( $country, 'shipping_' );
			if ( apply_filters( 'woocommerce_shipping_calculator_enable_state', true ) && isset( $country_fields['shipping_state'] ) && $country_fields['shipping_state']['required'] && ! $this->get_customer()->get_shipping_state() ) {
				return false;
			}
			if ( apply_filters( 'woocommerce_shipping_calculator_enable_postcode', true ) && isset( $country_fields['shipping_postcode'] ) && $country_fields['shipping_postcode']['required'] && ! $this->get_customer()->get_shipping_postcode() ) {

				return false;
			}
```

This works perfectly in our case - this reduces friction at the first point of checkout. 

This change would be very helpful for us

**Comment by vedanshujain** [comment]
Thanks for the report, we discussed this and agree with the suggestion. Marking it as a good first issue as a fix has already been suggested.

**Comment by webdados** [comment]
@vedanshujain Wil, someone from the team pick this up, or should I submit a PR?

**Comment by peterfabian** [comment]
@webdados If you can contribute with a PR, that would be great!

**Comment by kaushikasomaiya** [comment]
Observed in 5965114-zen. 

We were confused why shipping options matching `Locations not covered by your other zones` were showing up only for some countries like UAE and not for countries like Ukarine.

Figured out that the `Hide shipping costs until an address is entered` was enabled.

**Comment by barryhughes** [comment]
Thanks for submitting this, @webdados: we can expect to see the changes in our upcoming 8.4.0 release.
