### ISSUE TITLE
Disabling a variation doesn't actually disable it

### ISSUE THREAD

**Issue by ZioCain** [woocommerce/woocommerce#28408]
**Prerequisites (mark completed items with an [x]):**
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).

**Describe the bug**
Variable products with disabled variation still appear on shop page when filtered by specific attribute.
Specifically, when user navigates to a page where filters are active and a specific variation is selected, he can see the product that has that variation, even though it is disabled.
To not show the product on that filtered page, it is necessary to completely remove that variation from the product itself.

**Expected behavior**
Product list should not include disabled variations

**Actual behavior**
Product list includes disabled variations

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create product A and B
2. Add the same 3 variation to both products
3. On product A, have variation1 and variation2 enabled, but variation3 disabled
4. On product B, have all variation active
5. Have a sidebar with "filter product by attribute" widget active for that attribute/variation
6. Navigate to the front-end on the shop page
7. Apply filter by variation3
8. You'll see both product A and B

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I can reproduce this bug consistently using the steps above.

WordPress: 5.5.3
WooCommerce: 4.7.0

**Comment by rrennick** [comment]
Hi @ZioCain,

Thank you for reporting the issue. However, this issue had been reported previously here #28368. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
