### ISSUE TITLE
[GlobalStep - WooCommerce 4.8 RC 1] For Twenty Twenty theme, "Coupon has removed" error message appears vertically stretched on Checkout page.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#28422]
## Bug Description:
For Twenty Twenty theme, "Coupon has removed" error message appears vertically stretched on Checkout page.

## Environment:
Windows 10, macOS Mojave:10.14.6 (18G103)
Browser: Chrome(Version 86.0.4240.75 (64-bit))
                 Firefox(Version 82.0)(64-bit)
                 Safari(Version 13.1.1 (14609.2.9.1.3))

## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all required plugins.
1. Complete the Setup wizard.
1. Select the "Twenty Twenty theme".
1. Go to Coupons->Add a coupon.
1. Create a coupon and click on publish.
1. Go to frontend.
1. Add any product to the cart and go to Checkout page.
1. Apply a coupon on checkout page.
1. Remove the Coupon.
1. Now click on "Click here to enter your code" option.
1. Observe that "Coupon has removed" error message appears vertically stretched

## Actual Result:
For Twenty Twenty theme, "Coupon has removed" error message appears vertically stretched on Checkout page.

## Expected Result:
"Coupon has removed" error message should be properly display on checkout page.

## Artifacts:
[#28422.zip](https://github.com/woocommerce/woocommerce/files/5604137/28422.zip)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
Hi @gglobalstep,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end following the steps you provided. 

We’re going to solve this bug as soon as possible. Stay tuned for updates.

**Comment by tammullen** [comment]
Adding screenshot and noting I could see this in 4.7 and 4.4 so doesn't seem to be introduced by 4.8
![Screenshot 2020-11-27 at 22 24 37](https://user-images.githubusercontent.com/24649833/100487296-b8ca6e00-30ff-11eb-84ba-a8260f669678.png)

**Comment by zhongruige** [comment]
Also reported in https://github.com/woocommerce/woocommerce/issues/28948

**Comment by rrennick** [comment]
This was fixed at some point

<img width="614" alt="Screenshot 2023-06-19 at 2 42 38 PM" src="https://github.com/woocommerce/woocommerce/assets/343847/60171892-f8ef-4b4f-9a6c-59be94d9b9aa">
