### ISSUE TITLE
Action lostpassword_post misses second parameter

### ISSUE THREAD

**Issue by sybrew** [woocommerce/woocommerce#28428]
WordPress Core hook [lostpassword_post](https://developer.wordpress.org/reference/hooks/lostpassword_post/) has two parameters:
 * `$errors`
* `$user_data`

The hook copied from Core into WooCommerce at method `WC_Shortcode_My_Account::retrieve_password()` only supplies the first parameter, causing a discrepancy --- plausibly also PHP errors for those unbeknownst (such as was I).

You can easily mitigate this by adding the `$user_data` parameter to the hook. This parameter's variable is already correctly defined in the calling method.

**Comment by rrennick** [comment]
Hi @sybrew,

Thank you for taking the time to report this bug, we really appreciate your help. 

We’re going to solve this bug as soon as possible. Stay tuned for updates.
