### ISSUE TITLE
Reset password also reset user registered time

### ISSUE THREAD

**Issue by brunocantuaria** [woocommerce/woocommerce#28421]
I just found an issue on the pluggable function that WordPress provides and WooCommerce relies for saving password `wp_set_password()` . It doesn't explicit a user_registed time in the query, so the user registered time is updated to the current time.

This may cause issues like reports showing orders for users that registered days/weeks later. I fixed it, replacing the pluggable function in a custom plugin with the code:

```
if ( ! function_exists( 'wp_set_password' ) ) {
    function wp_set_password( $password, $user_id ) {
        global $wpdb;

        $userdata = get_userdata($user_id);

        $hash = wp_hash_password( $password );
        $wpdb->update(
            $wpdb->users,
            array(
                'user_pass'           => $hash,
                'user_activation_key' => '',
                'user_registered' => $userdata->user_registered,
            ),
            array( 'ID' => $user_id )
        );

        clean_user_cache( $user_id );
    }
}
```

I've opened a ticket at WordPress so they can either fix or document this, since the function is not used internally, they may not want to fix it.

https://core.trac.wordpress.org/ticket/51879#ticket

The `wp_set_password()` is used by WooCommerce in the reset password feature (when user clicks on the reset link sent through email). I found the function being called at class `WC_Shortcode_My_Account` ( includes/shortcodes/class-wc-shortcode-my-account.php:376)

**Comment by rrennick** [comment]
@brunocantuaria I just tried running the query directly in MySQL and the `user_registered` field is not updated. Can you provide steps to reproduce the issue you are seeing?

```
| 240 | keegan.bogan         | $P$BBLkzZFdt9amqluuN.FeeDd63c4Svg0 | keegan-bogan         | browe@example.net                |          | 2020-10-19 13:37:09 |                                               |           0 | Nolan        |    0 |       0 |
+-----+----------------------+------------------------------------+----------------------+----------------------------------+----------+---------------------+-----------------------------------------------+-------------+--------------+------+---------+
240 rows in set (0.00 sec)

mysql> UPDATE wp_users SET user_pass=MD5('REDACTED'),user_activation_key='' WHERE ID = 240;
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> select * from wp_users where ID=240;
+-----+--------------+----------------------------------+---------------+-------------------+----------+---------------------+---------------------+-------------+--------------+------+---------+
| ID  | user_login   | user_pass                        | user_nicename | user_email        | user_url | user_registered     | user_activation_key | user_status | display_name | spam | deleted |
+-----+--------------+----------------------------------+---------------+-------------------+----------+---------------------+---------------------+-------------+--------------+------+---------+
| 240 | keegan.bogan | 437b930db84b8079c2dd804a71936b5f | keegan-bogan  | browe@example.net |          | 2020-10-19 13:37:09 |                     |           0 | Nolan        |    0 |       0 |
+-----+--------------+----------------------------------+---------------+-------------------+----------+---------------------+---------------------+-------------+--------------+------+---------+
```

**Comment by juliaamosova** [comment]
Hi @brunocantuaria,

According to the WP ticket you opened, the issue doesn't seem to be with WordPress: https://core.trac.wordpress.org/ticket/51879#ticket. 

And so far, we were not able to see the issue in WooCommerce as per @rrennick's comment. 

Since the thread had been inactive for 7 days, I am going to go ahead and close it for now. However, please feel free to comment on it again in case we missed something and we'd take another look.
