### ISSUE TITLE
New State Missing for India in Tax State List

### ISSUE THREAD

**Issue by cwsindia** [woocommerce/woocommerce#28434]
Hello,

India has recently created a new Union Territory State named Ladakh. This state is not available in tax state list for India for tax configuration. I request you to please add this new state in List.

Thank You. 
Niraj

**Comment by rrennick** [comment]
Hi @cwsindia, Thanks for reporting the issue. 

The state is listed in CLDR 37 - https://github.com/unicode-org/cldr/blob/release-37/common/subdivisions/en.xml#L2257.

**Comment by cwsindia** [comment]
The state is listed in CLDR 37, but not available on live site. I tried all the possible spelling combinations but no luck. 
How to add this to the live site. I am using the latest version of Woocommerce.

**Comment by rrennick** [comment]
@cwsindia The second half of my comment was for the developer who writes the PR to add the state.
