### ISSUE TITLE
Integrate WP 5.6's wp_after_insert_post into product update flows

### ISSUE THREAD

**Issue by mdbitz** [woocommerce/woocommerce#28445]
WordPress 5.6 introduces the new wp_after_insert_post action and related function. I was recently running tests of the latest version of WordPress with WooCommerce and noticed that `added_post_meta` hooks were still firing after wp_insert_post.

Looking at the source code for updates I would like to suggest that WooCommerce be updated to use wp_after_insert_post so that plugins can utilize the `wp_after_insert_post` action to correctly identify when all product related data has been updated. (_sku, etc)

**Is your feature request related to a problem? Please describe.**
Not technically. Plugins traditionally update meta after updating a post so reliance on wp_insert_post can be spotty.

**Describe the solution you'd like**
`wp_after_insert_post` gives us the option to clearly state the Product and related meta is updated that add-ons can use to perform actions against the final state of the product(post).

I'd like to see the [update](https://github.com/woocommerce/woocommerce/blob/6e5cc0c2f2e2651b722f3806fa7c9e624f5b9204/includes/data-stores/class-wc-product-data-store-cpt.php#L200) function and other related save behavior make use of the wp_after_insert_post action/function. 

Details can be found at: https://make.wordpress.org/core/2020/11/20/new-action-wp_after_insert_post-in-wordpress-5-6/

At a quick review it should be updating line 242 to pass false for the third argument then calling wp_after_insert_post after all changes are complete. I haven't explored if additional changes are needed elsewhere.

**Comment by rrennick** [comment]
@mdbitz I'm closing this as the `wp_after_insert_post` hook is being called when adding/editing a product. If there is something that we've missed, let us know and we can re-open.
