### ISSUE TITLE
Product Categories List Block - Alignment Issues when used as a drop down on the Shop page

### ISSUE THREAD

**Issue by dcoleonline** [woocommerce/woocommerce#28442]
This comes from WordPress.com support interaction 3527328-zen.

**Prerequisites:**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug:**
When using the Product Categories List block on the Shop page as a dropdown, it seems that the arrow next to the drop down selector is either out of place or the wrong size. 

While this appearance varies by theme, I can confirm that this is happening on Storefront as well as Twenty Twenty. 

It only happens on the Shop page, but not on other pages that use the theme's default page template.

**Expected behavior:**
The alignment of the button to the right of the dropdown should match much more closely to the look of the block in the editor.

**Actual behavior:**
The button to the right of the dropdown is out of alignment on the shop page.

**Steps to reproduce the bug:**
1. Go to the block editor on the shop page.
2. Add a product categories list block and set it to use the drop down format
3. Publish the page and view it.
4. The button to the right of the drop down will be out of alignment.

**Storefront Shop Screenshot:**
![storefront-shop-comparison](https://user-images.githubusercontent.com/3505172/100549844-144d4680-323b-11eb-880f-244b29f9c15a.jpg)

---

**Storefront Test Page (non-shop) Screenshot:**
![storefront-nonshop-comparison](https://user-images.githubusercontent.com/3505172/100549853-2333f900-323b-11eb-93cb-6e0c8190079f.jpg)

---

**Twenty Twenty Shop Screenshot:**
![twenty-twenty-shop](https://user-images.githubusercontent.com/3505172/100549856-2d55f780-323b-11eb-82e6-cf48109797dd.jpg)

---

**Twenty Twenty Test Page (non-shop) Screenshot:**
![twenty-twenty-nonshop](https://user-images.githubusercontent.com/3505172/100549908-a81f1280-323b-11eb-85c6-1a470e89b093.jpg)

---

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment:**
<details>
### WordPress Environment ###

WordPress address (URL): https://lightningcookie.wpcomstaging.com
Site address (URL): https://lightningcookie.wpcomstaging.com
WC Version: 4.7.1
REST API Version: ✔ 4.7.1
WC Blocks Version: ✔ 3.6.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.3
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.3.24
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.73.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.23-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.7.1
WC Database Prefix: wp_
Total Database Size: 12.10MB
Database Data Size: 9.14MB
Database Index Size: 2.96MB
wp_woocommerce_sessions: Data: 0.19MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cartflows_ca_cart_abandonment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.19MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_taxjar_record_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
__wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
__wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_options: Data: 3.48MB + Index: 0.06MB + Engine InnoDB
__wp_postmeta: Data: 0.03MB + Index: 0.03MB + Engine InnoDB
__wp_posts: Data: 0.14MB + Index: 0.06MB + Engine InnoDB
__wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_taxjar_record_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
__wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
__wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
__wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 23
jp_img_sitemap: 1
jp_sitemap: 1
jp_sitemap_master: 1
page: 5
post: 1
product: 18
product_variation: 7
revision: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.7.1

### Inactive Plugins (36) ###

Akismet Anti-Spam: by Automattic – 4.1.7
AMP: by AMP Project Contributors – 2.0.7
Classic Editor: by WordPress Contributors – 1.6
CoBlocks: by GoDaddy – 2.5.3
Code Snippets: by Code Snippets Pro – 2.14.0
Coming Soon Page, Maintenance Mode & Landing Pages by SeedProd: by SeedProd – 6.0.9.0
Display Posts: by Bill Erickson – 3.0.2
Facebook for WooCommerce: by Facebook – 2.2.0
Gutenberg: by Gutenberg Team – 8.6.0
Health Check & Troubleshooting: by The WordPress.org community – 1.4.5
Jetpack by WordPress.com: by Automattic – 9.1
Klarna Checkout for WooCommerce: by Krokedil – 2.4.0
Klarna Payments for WooCommerce: by krokedil
klarna
automattic – 2.1.4

Layout Grid: by Automattic – 1.3
Mailchimp for WooCommerce: by Mailchimp – 2.4.7 – Installed version not tested with active version of WooCommerce 4.7.1
Page Optimize: by Automattic – 0.5.1
Starter Templates: by Brainstorm Force – 2.3.8
Storefront Powerpack: by WooCommerce – 2.0.0
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 3.2.3 – Installed version not tested with active version of WooCommerce 4.7.1
WooCommerce Australia Post Shipping: by WooCommerce – 2.4.28 – Installed version not tested with active version of WooCommerce 4.7.1
WooCommerce Canada Post Shipping: by WooCommerce – 2.5.19 – Installed version not tested with active version of WooCommerce 4.7.1
WooCommerce Cart Abandonment Recovery: by CartFlows Inc – 1.2.8 – Installed version not tested with active version of WooCommerce 4.7.1
WooCommerce Email Customizer: by WooCommerce – 1.1.18 – Installed version not tested with active version of WooCommerce 4.7.1
WooCommerce eWAY Payment Gateway: by WooCommerce – 3.1.25 – Installed version not tested with active version of WooCommerce 4.7.1
WooCommerce One Page Checkout: by Automattic – 1.7.10 – Installed version not tested with active version of WooCommerce 4.7.1
WooCommerce PayFast Gateway: by WooCommerce – 1.4.17
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.1
WooCommerce Product Add-ons: by WooCommerce – 3.2.0
WooCommerce Royal Mail: by WooCommerce – 2.5.32 – Installed version not tested with active version of WooCommerce 4.7.1
WooCommerce Shipping & Tax: by Automattic – 1.25.3 – Installed version not tested with active version of WooCommerce 4.7.1
WooCommerce Square: by WooCommerce – 2.2.5
WooCommerce Stripe Gateway: by WooCommerce – 4.5.5 – Installed version not tested with active version of WooCommerce 4.7.1
WooCommerce UPS Shipping: by WooCommerce – 3.2.29 – Installed version not tested with active version of WooCommerce 4.7.1
WooCommerce USPS Shipping: by WooCommerce – 4.4.49 – Installed version not tested with active version of WooCommerce 4.7.1
WordPress.com Editing Toolkit: by Automattic – 2.8.8
WPForms Lite: by WPForms – 1.6.3.1

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #1 - /shop/
Cart: #2 - /cart/
Checkout: #3 - /checkout/
My account: #4 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 21
Oldest: 2020-11-18 09:36:35 -0600
Newest: 2020-11-29 11:52:39 -0600
</details>

**Comment by rrennick** [comment]
Addressed in the linked PR.
