### ISSUE TITLE
Database update stops at 4.5.0

### ISSUE THREAD

**Issue by GeoJunkie** [woocommerce/woocommerce#28459]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When updating to WC 4.7.1 from versions prior to 4.5.0, the database version is only updated to 4.5.0. Deactivating and reactivating WooCommerce finishes the update to the current version.

Encountered this in 890335-hc and 26033016-hc and was able to reproduce on a test site from 4.2.0 and 4.4.0.

**Expected behavior**
The database update should set `woocommerce_db_version` to the current installed WC version. This should be displayed in the SSR.

**Actual behavior**
The SSR shows version 4.5.0, as well as the `woocommerce_db_version` option. When WooCommerce is deactivated and reactivated, the correct version appears.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Install a WooCommerce version prior to 4.5.0.
2. Update the plugin to the current WooCommerce version
3. Click on the database update prompt
4. Wait for the database update to complete (You may have to manually trigger the pending jobs in Action Scheduler)
5. Check **WooCommerce > Status > System Status** for the database version and/or check the `woocommerce_db_version` option in the database.

**Screenshots**
Before update:
![](https://d.pr/i/9WV1O6+)
Image Link: https://d.pr/i/9WV1O6
![](https://d.pr/i/3MA6Ro+)
Image Link: https://d.pr/i/3MA6Ro

After update:
![](https://d.pr/i/OtOzFq+)
Image Link: https://d.pr/i/OtOzFq
![](https://d.pr/i/FqDW2w+)
Image Link: https://d.pr/i/FqDW2w
![](https://d.pr/i/JAfV3b+)
Image Link: https://d.pr/i/JAfV3b

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
(Captured after updating and deactivating/reactivating WC)
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://440to471test.local
Site address (URL): http://440to471test.local
WC Version: 4.7.1
REST API Version: ✔ 4.7.1
WC Blocks Version: ✔ 3.6.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.3
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.16.0
PHP Version: 7.3.5
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
cURL Version: 7.54.0
LibreSSL/2.6.5

SUHOSIN Installed: –
MySQL Version: 8.0.16
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.7.1
WC Database Prefix: wp_
Total Database Size: 2.32MB
Database Data Size: 0.95MB
Database Index Size: 1.37MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.11MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 2
post: 2

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

WooCommerce: by Automattic – 4.7.1
WP CLI Login Command Server: by Evan Mattson – 1.2

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: ❌ Page not set
Cart: ❌ Page not set
Checkout: ❌ Page not set
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 7
Oldest: 2020-12-01 19:42:43 +0000
Newest: 2020-12-01 19:48:55 +0000

`
```
</details>

**Comment by DavidAnderson684** [comment]
Possibly related or the same: https://github.com/woocommerce/woocommerce-admin/issues/5058

**Comment by juliaamosova** [comment]
Hi @GeoJunkie,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

I first uploaded the WooCommerce 4.4.0 version on my site and followed your instructions:

![](http://g.recordit.co/ebBjkp9Xbl.gif)

We’re going to work on solving this issue as soon as possible.

**Comment by poolet08** [comment]
Hello, 

I encountered this same issue when upgrading to 4.7.0 and I am having issues with some subscriptions have the wrong src causing the renewal order to fail. 

I upgraded to 4.7.1 and it shows the correct database version in the status now (matches wc version). Can I assume the issue is fixed or should I take additional steps?

Thanks

**Comment by fylgjur** [comment]
Issue seen in 25695860-hc and followed up in 3556304-zen

**Comment by jessLundie** [comment]
Hi @poolet08, 

>  I encountered this same issue when upgrading to 4.7.0 and I am having issues with some subscriptions have the wrong src causing the renewal order to fail.

While it's possible that a WooCommerce DB issue would cause problems with your subscriptions data, I think it's unlikely that this would cause failed renewals due to an incorrect `src` token. 

If you are still seeing this issue, could you please log in to the WooCommerce.com account that holds your active license for Subscriptions and open a ticket with us on this here?  https://woocommerce.com/my-account/create-a-ticket/?form=ticket

**Comment by poolet08** [comment]
Hi @jessLundie,

Yep I did that and the theory is when I upgraded to 4.7.1 from 4.5.0 that the database update did not work. I still have an open ticket there. 

The issue definitely started occurring after I did that update. A lot of the payment source tokens say "card_xxx" instead of "src_xxx".

**Comment by rodrigoprimo** [comment]
AFAIK, having the value of `woocommerce_db_version` lower than the current WooCommerce version is expected and doesn't cause any issue to the store. We only update `woocommerce_db_version` when there is at least one update routine that needs to be executed while updating WooCommerce to a new version. The last time that this happened was when `4.5.0` was released (https://github.com/woocommerce/woocommerce/blob/master/includes/wc-update-functions.php#L2159).

When WooCommerce is installed, `woocommerce_db_version` is set to the current version,, and that value could be higher than the version where we had an update routine. It seems that the code that sets `woocommerce_db_version` to the current version, is also running when you deactivate and activate WC. Which I agree seems a bit confusing, but I don't expect it to cause any issues.

Considering this, unless I'm missing something (and please let me know if that is the case), I would suggest that we change this issue from `bug` to `enhancement`, lower its priority and remove it from the `4.9` milestone. What do you think, @juliaamosova?

**Comment by roykho** [comment]
I also wanted to leave a note here that I think the `woocommerce_db_version` should not be updated to the current version of WooCommerce core. It should have its own version. So for example if the last schema changes we did was `4.5.0`, then we should always update `woocommerce_db_version` to that version. Only bump the version if we indeed made any schema changes.

This way it is not confusing to us internally or to others when they expect that these two versions are different and that is ok.

**Comment by juliaamosova** [comment]
>Considering this, unless I'm missing something (and please let me know if that is the case), I would suggest that we change this issue from bug to enhancement, lower its priority and remove it from the 4.9 milestone. What do you think, @juliaamosova?

That sounds good to me @rodrigoprimo! Thanks for investigating the issue. Updating labels and removing the milestone.

**Comment by jessLundie** [comment]
@juliaamosova @rodrigoprimo - If I understand correctly, you are saying that in future, the WC DB version number would only be updated when there are actual schema changes to the DB, and not inline with every WC update?

I ask because this could prove very challenging for support. Right now, checking that the version matches is one of our first steps when verifying that the DB is updated to the latest schema.

If we are making this change, could we possibly add clear documentation somewhere so that our support team and customers can easily find which DB version numbers correlate correctly to which WC version numbers? Possibly a grid or similar so that we have an easy way to verify if a site's DB version is incorrect based on the version of WC they are running?

**Comment by rodrigoprimo** [comment]
> @juliaamosova @rodrigoprimo - If I understand correctly, you are saying that in future, the WC DB version number would only be updated when there are actual schema changes to the DB, and not inline with every WC update?

@jessLundie, that is actually the current behavior and it wasn't changed recently. My understanding from Roy's comment is that he is suggesting that we stop updating `woocommerce_db_version` to the latest version when WooCommerce is deactivated and then activated if there are no schema changes.

**Comment by peterfabian** [comment]
Hi, I'm slightly confused here. 
Looking at the options in the db, I can actually see 3:
- woocommerce_schema_version
- woocommerce_version
- woocommerce_db_version

It's true that we only update `woocommerce_db_version` explicitly when we perform changes in the database, but apparently, in newer versions, it gets updated to the current WC version. E.g. when I updated from 4.5.0 to 4.8, I could see it getting updated:
![Screenshot 2020-12-17 at 16 02 09](https://user-images.githubusercontent.com/2207451/102507272-56bcb300-4084-11eb-819a-9c5078404f06.png)

Is that not in contrast to what we're saying?
