### ISSUE TITLE
Twenty Twenty One bookable product page

### ISSUE THREAD

**Issue by Konamiman** [woocommerce/woocommerce#28452]
Please ensure the 2021 product page for a bookable product looks good:

- [ ] wide screen layout
- [ ] middle screen layout (e.g. ipad)
- [ ] narrow screen layout (e.g. iphone)
- [ ] Chrome
- [ ] Safari
- [ ] Firefox

Make sure the transitions between the layout widths look sensible (e.g. if the menu is still in narrow layout mode but the rest of the content in wide layout mode, it might be suboptimal, but please use your best judgment).

**Comment by peterfabian** [comment]
We've agreed, for the sake of consistency, that we won't add any specific style for 2021, as this was never done before and we prefer not to increase the support burden for extensions, thus no styling updates.
