### ISSUE TITLE
re: #27138

### ISSUE THREAD

**Issue by fullermetric** [woocommerce/woocommerce#28462]
Hello,

Currently running version WordPress 5.5.3 and WooCommerce 4.71

My manager discovered several endpoints that are not listed in the WOO REST API documentation.

eg. /wc/store/products.

And the problem is this endpoint exposes all of our products openly to the public.  

Is there a way to deregister this endpoint?  Shouldn't this endpoint be authenticating before giving away this information?

Thanks,
Kerry Ruddock
Fuller Metric Parts Ltd.

**Comment by rrennick** [comment]
> /wc/store/products

> this endpoint exposes all of our products openly to the public.

The `store` route is for the products block. It provides information that is already available by browsing the shop pages.
