### ISSUE TITLE
Updating account details redirects user to main Dashboard page

### ISSUE THREAD

**Issue by scottbuscemi** [woocommerce/woocommerce#28461]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
After saving changes to account details through the `/my-account/edit-account/` form, the user is redirected to the main Dashboard page with a success message rather than remaining on the same Account Details page.

**Expected behavior**
The user should remain on the same page, and the success message should appear at the top.

**Actual behavior**
The user is redirected to a different page after updating their details.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to My Account
2. Click on "Account Details"
3. Complete the account details fields (First name, last name, display name, email), then click "Save Changes"

**Screenshots**
<img width="1537" alt="Screen Shot 2020-12-01 at 2 31 49 PM" src="https://user-images.githubusercontent.com/4336848/100804566-f4a45280-33e1-11eb-9713-c079dfbd1b6d.png">

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @scottbuscemi,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end:

![](http://g.recordit.co/avIZdsUwFa.gif)

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by AlexT-for-MF** [comment]
Hello @scottbuscemi 

Try to use
`add_action( 'woocommerce_save_account_details', 'custom__woocommerce_save_account_details__redirect', 90, 1 );
function custom__woocommerce_save_account_details__redirect( $ID ) {

  wp_safe_redirect( wc_get_endpoint_url( 'edit-account' ) );

  exit();
}`

for me works fine. (WP code v. 5.7.2, Woo v. 5.4.1)

let me know if this causes any errors

**Comment by scottbuscemi** [comment]
@AlexT-for-MF Would this show a success message on the page though?

**Comment by AlexT-for-MF** [comment]
For my custom theme based on Storefront woo store theme yes

![13-07-2021 23-17-30](https://user-images.githubusercontent.com/39554247/125519209-742f4626-c777-4cba-ab89-a149d69d70af.jpg)

**Comment by ralucaStan** [comment]
No longer a valid issue
<img width="790" alt="Screenshot 2024-06-06 at 10 53 07" src="https://github.com/woocommerce/woocommerce/assets/1628454/a96f0fa4-cde9-4691-86a9-b4697d3a28bb">
