### ISSUE TITLE
List all Refunds in API failing

### ISSUE THREAD

**Issue by negapo** [woocommerce/woocommerce#28474]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When using the "/wp-json/wc/v3/orders/<id>/refunds" endpoint for retriving all refunds from an order some extra characters are being added to the json that is returned. An example below:

317
[Valid JSON Data]
0

This breaks the parser. I have tested with a fresh installation of WP, Woo, StoreFront, all at the latest version.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Fresh intallation of WC + Woo + StoreFront
2. Create a test product (Simple or Variable)
3. Complete an order on the front end
4. Go to the order on the admin panel and refund the bought item
5. Call "/wp-json/wc/v3/orders/<id>/refunds" on that order and see the returned JSON.

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): http://bean.pt/devtest
Site address (URL): http://bean.pt/devtest
WC Version: 4.7.1
REST API Version: ✔ 4.7.1
WC Blocks Version: ✔ 3.6.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.3
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.25
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1g-fips

SUHOSIN Installed: –
MySQL Version: 5.7.26-29-log
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.7.1
WC Database Prefix: flk_
Total Database Size: 3.74MB
Database Data Size: 2.33MB
Database Index Size: 1.41MB
flk_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
flk_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
flk_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
flk_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
flk_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
flk_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
flk_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
flk_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
flk_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
flk_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
flk_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
flk_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
flk_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
flk_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
flk_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
flk_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
flk_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
flk_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
flk_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
flk_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
flk_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
flk_options: Data: 1.48MB + Index: 0.06MB + Engine InnoDB
flk_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
flk_posts: Data: 0.03MB + Index: 0.06MB + Engine InnoDB
flk_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
flk_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
flk_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
flk_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
flk_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
flk_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
flk_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
flk_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
flk_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
flk_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
flk_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
flk_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
flk_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
flk_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
flk_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
flk_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
flk_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
flk_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
flk_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 2
customize_changeset: 1
page: 8
post: 2
product: 2
revision: 3
shop_order: 1
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

SG Optimizer: by SiteGround – 5.7.10
WooCommerce: by Automattic – 4.7.1

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.9.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 7
Oldest: 2020-12-02 18:24:10 +0000
Newest: 2020-12-02 18:33:26 +0000

`
</details>

**Comment by juliaamosova** [comment]
Hi @negapo,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end:

![api_refunds](https://user-images.githubusercontent.com/19143190/101197515-3296b600-3630-11eb-9ec2-538fbd6ffb36.jpg)

I don't see anything in the raw response either:

![api_raw](https://user-images.githubusercontent.com/19143190/101197523-362a3d00-3630-11eb-8cd0-ac8ca4a2616e.jpg)

I am not sure yet what could be going on since it sounds like you tested with all the plugins deactivated. 

Would it be possible for you to record how you make a request and the return you get and paste the recording here for us to evaluate?

**Comment by negapo** [comment]
Hi @juliaamosova , thanks for taking a look and im sorry to mislead you but you are right, the JSON being returned is clean and valid. I have further investigated and the problem is with my parser failing to parse the tax_class property. Has you can see from the docs at https://woocommerce.github.io/woocommerce-rest-api-docs/#order-refund-properties the field is supposed to be an integer (and it was until very recently) but its coming as an empty string, you can check your screenshot. Was this deliberately? If so the docs need to be updated. Thanks

**Comment by rrennick** [comment]
> Has you can see from the docs at https://woocommerce.github.io/woocommerce-rest-api-docs/#order-refund-properties the field is supposed to be an integer (and it was until very recently) but its coming as an empty string

@negapo Thanks for the follow up details. The [last change to the tax_calls property](https://github.com/woocommerce/woocommerce/blame/trunk/plugins/woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-order-refunds-v2-controller.php#L466) occurred 3 years ago. It has been typed as a string for at least that long and the documentation should be updated accordingly.
