### ISSUE TITLE
VAT and Brexit

### ISSUE THREAD

**Issue by natalkanna** [woocommerce/woocommerce#28484]
I'm in the UK. Part of my business plan is to offer dropshipping: customers in the UK place an order with me and then I send it directly to their customer. I charge 20% VAT on my invoices as I am a business-to-business wholesale retailer.
In rare instances, my customer is in the UK, but the person I am sending to is in Europe. (billing address UK, shipping address abroad).
With Brexit happening on 1st Jan, will Woocommerce be releasing an update to recognise the shipping country as being outside the UK, and charge the applicable VAT? Thank you.

**Comment by juliaamosova** [comment]
Hi @natalkanna,

Thanks for bringing this up! It is on our radar to make sure WooCommerce is ready for Brexit. I am assigning a milestone of the 4.9 release to this issue to make sure we take care of it.

**Comment by DavidAnderson684** [comment]
I don't see if any core changes are necessary to accomplish what is described in the issue. If you don't want to charge taxes to certain countries, then remove those countries' entries from your tax tables.

**Comment by natalkanna** [comment]
Thank you juliaamosova! :1st_place_medal:
