### ISSUE TITLE
Check E2E testing with PHP 8.0

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce#28486]
Currently, the E2E Environment package is pinned to use the latest version of PHP 7. Once WC 4.8 & WP 5.6 are released we need to check whether E2E runs okay on PHP 8.0 and decide whether to switch the tests to run on PHP 8.0.

**Comment by rodelgc** [comment]
Create a project thread for this.

**Comment by rrennick** [comment]
Closing as we are now using e2e-pw.
