### ISSUE TITLE
Write new e2e test: Merchant / Products / Import Products CSV

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#28489]
Write a new e2e test that covers `Merchant / Products / Import Products CSV` flow.

**Comment by milos2905** [comment]
Requirements for this test are:
1. Upload sample_products.csv file and confirm that all products have been successfully imported.
2. Create sample_products2.csv file by changing prices of products of the original sample_products.csv file. Upload sample_products2.csv file with Existing products that match by ID or SKU will be updated option selected. Confirm that all products have been successfully imported and the prices of the products updated.
