### ISSUE TITLE
Write new e2e test: Merchant / Orders / Search Orders

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#28488]
Write a new e2e test that covers `Merchant / Orders / Search Orders` flow.

**Comment by juliaamosova** [comment]
In this test, we are testing the functionality of the Search Orders bar in the top right corner of the `All Orders` view as shown below:

![seacrh_bar](https://user-images.githubusercontent.com/19143190/102807670-182d3e00-438d-11eb-8754-f57ac6711ba1.jpg)

In the test, we need to confirm that:

- Orders can be searched by a single-digit order number (Example, `1`, `2`, `3` etc)

- Orders can be searched by order item name such as `T-Shirt`

- Orders can be searched by the following billing fields:
  - billing first name
  - billing last name
  - billing company
  - billing email
  - billing phone
  - billing address 1
  - billing address 2
  - billing city
  - billing postcode
  - billing state

- Orders can be searched by the following shipping fields:
  - shipping first name
  - shipping last name
  - shipping address 1
  - shipping address 2
  - shipping city
  - shipping postcode
  - shipping state


<p>For the billing and shipping fields - we should use the default values we have set for both addresses in the <code>default.json</code> file. The test should confirm that the fields below can be searched by:</p>



<ul><li><a rel="noreferrer noopener" href="https://github.com/woocommerce/woocommerce/blob/master/tests/e2e/env/config/default.json#L37-L49" target="_blank">Customer billing address details</a></li><li><a rel="noreferrer noopener" href="https://github.com/woocommerce/woocommerce/blob/master/tests/e2e/env/config/default.json#L50-L60" target="_blank">Customer shipping address details</a></li></ul>

**Comment by milos2905** [comment]
After reviewing requirements decision is made that "Orders can be searched by a single-digit order number (Example, 1, 2, 3 etc)" should be replaced with "Orders can be searched by a specific order number". Reason is that most stores won’t have any order IDs that are single digits.
