### ISSUE TITLE
API Request: Enable searching for products by SKU

### ISSUE THREAD

**Issue by anitaa1990** [woocommerce/woocommerce#28508]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
Add an endpoint that the woo mobile app could use to fetch products based on whatever filters are passed through the API request. In this particular instance, we would like to search for products by a particular SKU value. This could be a partial SKU match. 

**How it works now**
We currently support the option to search for products by it’s name. We use the below endpoint to search for products by it’s name. So essentially, we use the search=[value] query parameter to fetch a list of products that includes the [value].
```
/wc/v3/products/&_method=get&per_page=25&orderby=title&order=asc&offset=0&search=woo
```

**Proposed Change**
We’d like to also support searching for a SKU in the future. So for instance, if a user enters “woo”, we should ideally fetch all products with name or SKU value that include the term “woo”.

Context:
`p7bje6-2GK#comment-5591`

**Comment by joshbetz** [comment]
@anitaa1990 Is it possible to know when someone is trying to search by SKU? If so, we could do something like:

```
/wc/v3/products/?sku=woo
```

One problem with having search always look up a SKU is that it makes every product search query slower (because of the extra post meta query). Changing the API to allow searching for SKUs with the `sku` param would isolate that slow query to SKU searches only. IMHO that would be pretty safe to do.

If we need to have all searches automatically look at the SKU, we'll likely need to do some research to see how often these searches happen and look at the impact of such a change.

**Comment by joshbetz** [comment]
It looks like we already have support for exact matches of skus.

https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-products-controller.php#L147-L163

A couple ideas here to facilitate searches:

1. We add a new query parameter (something like `sku_search`) which does a `LIKE` query.
2. We overload the existing `sku` parameter and do a `LIKE` query if there is only one sku in the list.

I would lean towards option 1. Number 2 would make sense in some contexts, but also breaks the existing API contract, which is not ideal.

@woocommerce/proton Any thoughts on these proposed options or any other ideas?

**Comment by anitaa1990** [comment]
Sorry for not responding @joshbetz! This got lost in my mail 🤦‍♀️ 

> @anitaa1990 Is it possible to know when someone is trying to search by SKU? If so, we could do something like: /wc/v3/products/?sku=woo

 That is what was suggested initially by Proton I think. At the moment, unfortunately, we don't have a way to identify if the user is searching for SKU or something else. The idea was to use our existing UI and query the SKU field in the server db. But from what I understood this would have a performance hit on the API.

We could work with Adam to explore UI to maybe include SKU as a separate option in the search filter. That way we would be able to identify if the merchant is searching for SKU.

**Comment by peterfabian** [comment]
Sorry for my late response here. 

Can we use the product meta lookup table to perform the search without joining the postmeta table? That probably shouldn't cause a large performance hit. 

Theoretically speaking, we can also probe if the db supports fulltext index and if it does, then add the fulltext index which should make even substring queries rather fast.
