### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function is_cart() 

### ISSUE THREAD

**Issue by shreya2621** [woocommerce/woocommerce#28510]
Fatal error: Uncaught Error: Call to undefined function is_cart() in D:\wamp\www\wordpress\wp-content\plugins\bus-ticket-booking-with-seat-reservation\includes\class-remove-bus-info-to-cart.php on line 14
--

1 | 0.0002 | 409712 | {main}(  ) | ...\index.php:0
2 | 0.0004 | 409984 | require( 'D:\wamp\www\wordpress\wp-blog-header.php' ) | ...\index.php:17
3 | 0.1560 | 3351032 | require_once( 'D:\wamp\www\wordpress\wp-includes\template-loader.php' ) | ...\wp-blog-header.php:19
4 | 0.1561 | 3351032 | do_action(  ) | ...\template-loader.php:13
5 | 0.1561 | 3351408 | WP_Hook->do_action(  ) | ...\plugin.php:478
6 | 0.1561 | 3351408 | WP_Hook->apply_filters(  ) | ...\class-wp-hook.php:311
7 | 0.1587 | 3405656 | wbtm_cart_item_have_two_way_route(  ) | ...\class-wp-hook.php:287

Good Afternoon

i am working on wordpress new version and making a website using bus-booking-and-seat-reservation plugin

i can add all the details regarding bus 

but whenever i go for the preview i get the above error 

used all possible solution from the google youtube 

i just have 4 days to complete my project 

can anyone help with the perfect solution

thankyou!!!

**Comment by sanzeeb3** [comment]
The error is from `bus-ticket-booking-with-seat-reservation` plugin which is possibly because you don't have WooCommerce activated so `is_cart()` is undefined.

**Comment by shreya2621** [comment]
> The error is from `bus-ticket-booking-with-seat-reservation` plugin which is possibly because you don't have WooCommerce activated so `is_cart()` is undefined.

i tried to install woocommerce but it says update failed 
its not getting install

**Comment by sanzeeb3** [comment]
What is the full update failed error message? You can download new WooCommerce https://wordpress.org/plugins/woocommerce/ and upload via FTP as well. Here's how: https://www.wpbeginner.com/beginners-guide/how-to-manually-update-wordpress-plugins-via-ftp/

**Comment by shreya2621** [comment]
I

> What is the full update failed error message? You can download new WooCommerce https://wordpress.org/plugins/woocommerce/ and upload via FTP as well. Here's how: https://www.wpbeginner.com/beginners-guide/how-to-manually-update-wordpress-plugins-via-ftp/

nstalling Plugin: WooCommerce 4.7.1
Downloading installation package from https://downloads.wordpress.org/plugin/woocommerce.4.7.1.zip…

Unpacking the package…


Fatal error: Maximum execution time of 120 seconds exceeded in D:\wamp\www\wordpress\wp-admin\includes\class-wp-filesystem-direct.php on line 82
There has been a critical error on your website. Please check your site admin email inbox for instructions.

Learn more about debugging in WordPress.

**Comment by sanzeeb3** [comment]
In that case, increase your memory timeout. Here's how: https://www.wpbeginner.com/wp-tutorials/how-to-fix-fatal-error-maximum-execution-time-exceeded-in-wordpress/

**Comment by shreya2621** [comment]
> In that case, increase your memory timeout. Here's how: https://www.wpbeginner.com/wp-tutorials/how-to-fix-fatal-error-maximum-execution-time-exceeded-in-wordpress/

tried 
but when i go with preview its taking a lot of time...its still generating preview

**Comment by shreya2621** [comment]
Thanks a lot man 
it worked!!!

Being a stranger and helping a stranger is really very appreciative 
Keep it up 
Thanks :)
