### ISSUE TITLE
Fatal error: Uncaught IntlException: Constructor

### ISSUE THREAD

**Issue by hiphopservers** [woocommerce/woocommerce#28516]
Per referral from WordPress WooCommerce support forum by @mikejolley; I am reporting this bug issue that has been duplicated is all version 4.6.x and above.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
This error is generated consistently with a fresh install both on multi-site and regular WordPress install. I have tried to load the plugin with no other plugin installed and still get the same error. The site returns the following error message in debug mode.  This error is also present in all versions of the app installed on the same server after upgrading to the latest version.

**Expected behavior**
The application should on a fresh install or after update allow normal functionally and be able to navigate all configuration tabs. 

**Actual behavior**
The store's primary settings tab and product tab do not work as expected. The frontend causes the entire site a blank screen when attempting to load until the plugin is disabled.  Even when no other plugin is running the following error is produced.

`
Fatal error: Uncaught IntlException: Constructor failed in /home/userID/domains/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php:1799 Stack trace: #0 /home/userID/domains/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1799): Collator->__construct('en_US') #1 /home/userID/domains/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(53): wc_asort_by_locale(Array) #2 /home/userID/domains/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-data-countries-controller.php(115): WC_Countries->get_countries() #3 /home/userID/domains/iamautumnco.com/public_html/wp-includes/rest-api/class-wp-rest-server.php(1050): WC_REST_Data_Countries_Controller->get_items(Object(WP_REST_Request)) #4 /home/userID/domains/iamautumnco.com/public_html/wp-includes/rest-api.php(464): WP_REST_Server->dispatch(Object(WP_REST_Request)) #5 /home/userID/domains/iamautumnc in /home/userID/domains/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 1799`

My site is running on PHP 7.3.24, CentOS. I also found the following errors in my error log file. 

```
[Sun Nov 15 06:35:04.990989 2020] [proxy_fcgi:error] [pid 8331:tid 139783563233024] [client 24.49.43.55:54182] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught IntlException: Constructor failed in /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php:1799\nStack trace:\n#0 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1799): Collator->__construct('en_US')\n#1 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(53): wc_asort_by_locale(Array)\n#2 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(38): WC_Countries->get_countries()\n#3 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(239): WC_Countries->__get('countries')\n#4 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1307): WC_Countries->get_allowed_countries()\n#5 /home/userID/truePath/iamautumnco.co...', referer: https://shop.iamautumnco.com/wp-admin/plugins.php?plugin_status=all&paged=1&s
[Sun Nov 15 06:35:08.640640 2020] [proxy_fcgi:error] [pid 8331:tid 139783563233024] [client 24.49.43.55:54182] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught IntlException: Constructor failed in /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php:1799\nStack trace:\n#0 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1799): Collator->__construct('en_US')\n#1 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(53): wc_asort_by_locale(Array)\n#2 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(38): WC_Countries->get_countries()\n#3 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(239): WC_Countries->__get('countries')\n#4 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1307): WC_Countries->get_allowed_countries()\n#5 /home/userID/truePath/iamautumnco.co...', referer: https://shop.iamautumnco.com/wp-admin/plugins.php?plugin_status=all&paged=1&s
[Sun Nov 15 06:35:23.652241 2020] [proxy_fcgi:error] [pid 8331:tid 139783563233024] [client 24.49.43.55:54200] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught IntlException: Constructor failed in /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php:1799\nStack trace:\n#0 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1799): Collator->__construct('en_US')\n#1 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(53): wc_asort_by_locale(Array)\n#2 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(38): WC_Countries->get_countries()\n#3 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(239): WC_Countries->__get('countries')\n#4 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1307): WC_Countries->get_allowed_countries()\n#5 /home/userID/truePath/iamautumnco.co...', referer: https://shop.iamautumnco.com/wp-admin/plugins.php?plugin_status=all&paged=1&s
[Sun Nov 15 06:35:25.747306 2020] [proxy_fcgi:error] [pid 8331:tid 139783563233024] [client 24.49.43.55:54200] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught IntlException: Constructor failed in /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php:1799\nStack trace:\n#0 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1799): Collator->__construct('en_US')\n#1 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(53): wc_asort_by_locale(Array)\n#2 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(38): WC_Countries->get_countries()\n#3 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(239): WC_Countries->__get('countries')\n#4 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1307): WC_Countries->get_allowed_countries()\n#5 /home/userID/truePath/iamautumnco.co...', referer: https://shop.iamautumnco.com/wp-admin/plugins.php?plugin_status=all&paged=1&s
[Sun Nov 15 06:35:28.540046 2020] [core:error] [pid 8526:tid 139782369593088] [client 24.49.43.55:54207] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
[Sun Nov 15 06:35:28.544321 2020] [core:error] [pid 8331:tid 139782134728448] [client 24.49.43.55:54206] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
[Sun Nov 15 06:36:05.947661 2020] [access_compat:error] [pid 8331:tid 139782168299264] [client 34.231.33.72:58136] AH01797: client denied by server configuration: /home/userID/truePath/iamautumnco.com/private_html/wp-content/uploads/woocommerce_uploads/, referer: https://iamautumnco.com/wp-content/uploads/woocommerce_uploads/
[Sun Nov 15 06:36:07.445910 2020] [proxy_fcgi:error] [pid 8331:tid 139782780770048] [client 24.49.43.55:54236] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught IntlException: Constructor failed in /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php:1799\nStack trace:\n#0 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1799): Collator->__construct('en_US')\n#1 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(53): wc_asort_by_locale(Array)\n#2 /home/userID/truePath/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-data-countries-controller.php(115): WC_Countries->get_countries()\n#3 /home/userID/truePath/iamautumnco.com/public_html/wp-includes/rest-api/class-wp-rest-server.php(1050): WC_REST_Data_Countries_Controller->get_items(Object(WP_REST_Request))\n#4 /home/userID/truePath/iamautumnco.com/public_html/wp-includes/rest-api.php(464): WP_REST_Server->dispatch(Object(WP_REST_Re...', referer: https://iamautumnco.com/wp-admin/plugins.php
```

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Install fresh copy of WordPress
2. Install WooCommerce plugin
3. If no error; Scroll down and make sure the error message is not in lower left corner of plugin iframe; attempt to configure the store.

`Fatal error: Uncaught IntlException: Constructor failed in /home/userID/domains/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php:1799 Stack trace: #0 /home/userID/domains/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1799): Collator->__construct('en_US') #1 /home/userID/domains/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(53): wc_asort_by_locale(Array) #2 /home/userID/domains/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/rest-api/Controllers/Version3/class-wc-rest-data-countries-controller.php(115): WC_Countries->get_countries() #3 /home/userID/domains/iamautumnco.com/public_html/wp-includes/rest-api/class-wp-rest-server.php(1050): WC_REST_Data_Countries_Controller->get_items(Object(WP_REST_Request)) #4 /home/userID/domains/iamautumnco.com/public_html/wp-includes/rest-api.php(464): WP_REST_Server->dispatch(Object(WP_REST_Request)) #5 /home/userID/domains/iamautumnc in /home/userID/domains/iamautumnco.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 1799
`

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
`
### WordPress Environment ###

WordPress address (URL): https://www.homemadedivashop.com
Site address (URL): https://www.homemadedivashop.com
WC Version: 4.7.1
REST API Version: ✔ 4.7.1
WC Blocks Version: ✔ 3.6.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.3
Log Directory Writable: ✔
WP Version: 5.5.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2
PHP Version: 7.4.13
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.73.0
OpenSSL/1.0.2k-fips

SUHOSIN Installed: –
MySQL Version: 5.7.31
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.4.1
WC Database Prefix: wp_
Total Database Size: 21.16MB
Database Data Size: 18.54MB
Database Index Size: 2.62MB
wp_woocommerce_sessions: Data: 2.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mcloud_mux_assets: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mcloud_mux_playback: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_mcloud_mux_renditions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_mcloud_task: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mcloud_task_data: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mcloud_task_schedule: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mcloud_task_token: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.02MB + Index: 0.16MB + Engine InnoDB
wp_postmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 2.36MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 1.02MB + Index: 0.22MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.38MB + Index: 0.14MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 4
custom_css: 1
nav_menu_item: 7
oembed_cache: 1
page: 7
post: 1
revision: 8
wpautoterms_page: 2
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (12) ###

WP AutoTerms: by WP AutoTerms – 2.4.3
Child Theme Configurator: by Lilaea Media – 2.5.6
Code Snippets: by Code Snippets Pro – 2.14.0
Contact Form 7: by Takayuki Miyoshi – 5.3.1
Media Cloud: by interfacelab – 4.1.14
Social Feed Gallery: by QuadLayers – 3.1.1
Meta Box: by MetaBox.io – 5.3.5
My Wordpress Login Logo: by Afsal Rahim – 2.3.3
User Role Editor: by Vladimir Garagulya – 4.57
WooCommerce: by Automattic – 4.7.1
Wordfence Security: by Wordfence – 7.4.14
Yoast SEO: by Team Yoast – 15.4

### Inactive Plugins (9) ###

Divi Builder: by Elegant Themes – 4.7.4
Product Feed PRO for WooCommerce: by AdTribes.io – 9.2.4 – Installed version not tested with active version of WooCommerce 4.7.1
ReCaptcha v2 for Contact Form 7: by IQComputing – 1.2.9
Site Kit by Google: by Google – 1.22.0
Strong Testimonials: by MachoThemes – 2.50.3
WooCommerce Google Analytics Integration: by WooCommerce – 1.4.25 – Installed version not tested with active version of WooCommerce 4.7.1
WooCommerce Stripe Gateway: by WooCommerce – 4.5.5 – Installed version not tested with active version of WooCommerce 4.7.1
Woo Invoice: by WebAppick – 3.1.4 – Installed version not tested with active version of WooCommerce 4.7.1
YITH Woocommerce Request A Quote: by YITH – 1.6.0 – Installed version not tested with active version of WooCommerce 4.7.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #13 - /shop/
Cart: #14 - /cart/
Checkout: #15 - /checkout/
My account: #16 - /my-account/
Terms and conditions: #23 - /wpautoterms/aup-tc/

### Theme ###

Name: Divi Child Homemade Diva
Version: 3.22.4.1598847898
Author URL: http://www.elegantthemes.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 4.7.4
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Pending: 3
Oldest: 2020-10-26 00:48:03 -0400
Newest: 2020-10-26 01:00:43 -0400

`
All sites installed on this host with this plugin active are broken and load a white page.

**Comment by hiphopservers** [comment]
I have removed the application from the initial site and installed a different solution.  The caption site is in development on my host and still has the last copy of WordPress and WooCommerce running on it causing the site to break.

**Comment by Rider7991** [comment]
Got similar problem with woocommerce after updating from 4.5.2.
My stack trace:
```
[03-Dec-2020 09:59:18 UTC] PHP Fatal error:  Uncaught IntlException: Constructor failed in /domains/randomsite.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php:1799
Stack trace:
#0 /domains/randomsite.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1799): Collator->__construct('pl_PL')
#1 /domains/randomsite.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(53): wc_asort_by_locale(Array)
#2 /domains/randomsite.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(38): WC_Countries->get_countries()
#3 /domains/randomsite.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-countries.php(262): WC_Countries->__get('countries')
#4 /domains/randomsite.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(1307): WC_Countries->get_allowed_countries()
#5 /domains/randomsite.com/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php(128): wc_get_customer_default_location()
#6 /domains/randomsite.com/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php(117): WC_Customer_Data_Store_Session->set_defaults(Object(WC_Customer))
#7 /domains/randomsite.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): WC_Customer_Data_Store_Session->read(Object(WC_Customer))
#8 /domains/randomsite.com/public_html/wp-content/plugins/woocommerce/includes/class-wc-customer.php(116): WC_Data_Store->read(Object(WC_Customer))
#9 /domains/randomsite.com/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(767): WC_Customer->__construct(1, true)
#10 /domains/randomsite.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php(2491): WooCommerce->initialize_cart()
#11 /domains/randomsite.com/public_html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(583): wc_load_cart()
#12 /domains/randomsite.com/public_html/wp-includes/class-wp-hook.php(287): WooCommerce->init('')
#13 /domains/randomsite.com/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#14 /domains/randomsite.com/public_html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#15 /domains/randomsite.com/public_html/wp-settings.php(546): do_action('init')
#16 /domains/randomsite.com/public_html/wp-config.php(80): require_once('/domains/random...')
#17 /domains/randomsite.com/public_html/wp-load.php(37): require_once('/domains/random...')
#18 /domains/randomsite.com/public_html/wp-blog-header.php(13): require_once('/domains/random...')
#19 /domains/randomsite.com/public_html/index.php(17): require('/domains/random...')
#20 {main}
  thrown in /domains/randomsite.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php on line 1799
[03-Dec-2020 09:59:19 UTC] PHP Fatal error:  Uncaught IntlException: Constructor failed in /domains/randomsite.com/public_html/wp-content/plugins/woocommerce/includes/wc-core-functions.php:1799
```

**Comment by mikejolley** [comment]
cc @peterfabian This was reported on the forums a few weeks ago and seems to be a compatibility issue from a recent change.

**Comment by peterfabian** [comment]
Thanks @mikejolley and thanks folks for reporting.

**Comment by claudiosanches** [comment]
Hello @hiphopservers, could you provide some more informations about this error?
Have you tried to enable PHP-Intl extension? What the status and information that gets displayed by `php_info()` about PHP-Intl?

This is how shows up for me:

![Screenshot from 2020-12-09 14-18-46](https://user-images.githubusercontent.com/1264099/101663456-7a02b500-3a29-11eb-9c2b-c501a6cf321a.png)

**Comment by hiphopservers** [comment]
@claudiosanches  here is the screen and I do not have the IUC TZData Version by default on my host in comparison to your screenshot and my host runs DirectAdmin host manager which handles building my install PHP versions.   I can add custom strings to add custom extensions to the PHP during building but I would have to look up the require syntax for the install then rebuild PHP. 

![Screen Shot 2020-12-10 at 4 50 23 AM](https://user-images.githubusercontent.com/15718381/101757435-2766de80-3aa5-11eb-9220-ce275dc25382.png)
shot you requested.

**Comment by hiphopservers** [comment]
@Rider7991  what are the settings on your host for PHP in this section?

**Comment by Rider7991** [comment]
@hiphopservers I just updated ICU from 53 to 60 and it's working right now. In the past I had what you can see on the screen below:
![icu](https://user-images.githubusercontent.com/35701147/101758206-59456880-3ad8-11eb-9568-52211133a82f.png)

**Comment by Rider7991** [comment]
@hiphopservers current, working setting:
![current_working_icu](https://user-images.githubusercontent.com/35701147/101758684-f1dbe880-3ad8-11eb-952d-7d4a18766e69.png)

**Comment by hiphopservers** [comment]
@Rider7991 

Clearly, I need to install that ICU TZData version.  This should have a workaround or warning that it needs to be installed instead of breaking the application.  Plus clear notes to have this data version installed if it is required.

**Comment by hiphopservers** [comment]
I was able to get the site to work by contacting my web admin software developer and learn how to properly update and install the specific version of ICU that included the ICU TZData version.  After installing the icu4c-66_1-src.tgz from the CLI and testing the plugins my errors stopped.  There needs to be some kind of exception or soft warning if the ICU data is not installed properly.  Also, instructions need to make this a pre-requisite for running WooCommerce since it is currently causing such a fatal error.

**Comment by claudiosanches** [comment]
Thank you all very much for helping debug it. I'll include a check to make sure that this function works, and maybe also a note in the System Status.

**Comment by hiphopservers** [comment]
@claudiosanches the real thanks for getting the bug reported goes to @mikejolley the real WooHero.  He was persistent about coming here and reporting the bug.  You are the rest of the development are able to resolve this issue because of his patience and commitment over on the WordPress support forum, thank you.
