### ISSUE TITLE
Secure Cookie Filter

### ISSUE THREAD

**Issue by tj-a** [woocommerce/woocommerce#28522]
**Is your feature request related to a problem? Please describe.**

There is currently no way to enforce the secure property on cookies generated by WC. The issue of insecure cookies is commonly reported by third-party pen testing companies and there is currently no official way to address this. The problem is observable where the `woocommerce_cart_hash` and `woocommerce_items_in_cart` cookies are created.

**Describe the solution you'd like**

A new filter applied within the core function `wc_setcookie()`which would allow the secure property to be enforced, in the same way that HttpOnly `woocommerce_cookie_httponly` filter is applied now. The hook could be called something like `woocommerce_cookie_secure`.

**Describe alternatives you've considered**

There doesn't appear to be any viable alternatives.

**Comment by roykho** [comment]
Hi there, thanks for reporting however there is already an issue opened for this. Closing this in favor of that one https://github.com/woocommerce/woocommerce/issues/26764
