### ISSUE TITLE
Twenty Twenty Theme Tinymce issue

### ISSUE THREAD

**Issue by Phukit** [woocommerce/woocommerce#28520]
**Prerequisites (mark completed items with an [x]):**
- [X ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ X] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
Hi,

I am using the twenty twenty deafult theme in wordpress and when I add woocommerce the tinymce editor shifts to a width of 580px for some reason.

I change to twenty nineteen or twenty eighteen and it goes back to 100% 

It is very weird and frustrating! can you please fix this quickly.  Custom CSS is not working either.  grrrr :(

Also I am using elementor pro and it also reformats the editor to 580px

Thanks.

**Comment by juliaamosova** [comment]
Hi @Phukit,

Thank you for submitting the issue. However, I don't fully understand how to reproduce it. Please either record a video or take some screenshots that explain the problem and provide more clear steps on how to reproduce the issue.

**Comment by Phukit** [comment]
thanks for the reply. 

I have switched themes by now. but install a fresh wordpress with twenty twenty theme than install woocommerce. 

than create a product and enter in any info you will see what i mean. 

I haven’t tried this in the new wordpress 5.6 it might have been fixed.

**Comment by juliaamosova** [comment]
Hi @Phukit,

Thanks for your follow-up. 

Here is what I am seeing in Twenty Twenty if I start writing a product description - the cursor moves to the right and the sentence doesn't start from the beginning of the editor. Is this the issue you are referring to?

![](http://g.recordit.co/iZQPYxHqcn.gif)

And here is what I am seeing in Twenty Twenty One (no issue):

![](http://g.recordit.co/I8OYZkAGDq.gif)

My environment:

- PHP 7.4.13
- WordPress 5.6 
- WooCommerce 4.8

**Comment by Phukit** [comment]
yes that was exactly the issue i was referring to. 

it was ONLY happening with twenty twenty theme. 

I have switched to the hello theme and everything works great.

**Comment by juliaamosova** [comment]
Thanks for confirming @Phukit. Even though the new default theme is Twenty Twenty One, we likely should fix it soonish as many people may still use Twenty Twenty on their sites and this bug is indeed annoying.

**Comment by roykho** [comment]
This is actually the issue with Twenty Twenty theme. And it looks like they will not try to fix this and states it is working correctly. Ref. https://core.trac.wordpress.org/ticket/48765

For this reason I am closing this as the fix needs to be from them.
