### ISSUE TITLE
WooCommerce Status Widget: Update Net Sales Logic

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce#28569]
The Start/Manage team is going to be looking at updating some of the WooCommerce wp-admin dashboard widgets, and this is the first of a few issues that Isotope will be looking into in the new year ( or possibly sooner! ).

<img width="474" alt="Dashboard ‹ bend outdoors — WordPress 2020-12-11 17-03-58" src="https://user-images.githubusercontent.com/22080/101968988-d6ef9e00-3bd6-11eb-97d3-0707347d9104.png">

As part of the updates to the Status Widget, we should change the source of the Net Sales data and link to the appropriate new analytic reports instead of directing users to legacy reports.

- [ ] Only use the new analytics logic on sites where wc-admin is not disabled via the `woocommerce_admin_disabled` filter
- [ ] [Net Sales](https://github.com/woocommerce/woocommerce/blob/c96a642e8a8153ffba37f2f2cf05170a373086ff/includes/admin/class-wc-admin-dashboard.php#L119) currently links to the "This Month" legacy report, we should instead direct it to the Revenue Report, Month to Date, with the Net Sales tab selected `wp-admin/admin.php?page=wc-admin&path=%2Fanalytics%2Frevenue&chart=net_revenue&orderby=net_revenue&period=month&compare=previous_period`
- [ ] Update the source of the month to date Net Sales logic to use the same logic used on the Net Sales in the Revenue Report

**Comment by timmyc** [comment]
Scoping this one at 2, we will probably need to write a test case for this, and possibly update some user documentation ( not sure about that though ).

**Comment by louwie17** [comment]
@timmyc @pmcpinto should the top seller product link also be updated as part of this PR?
Going to the analytics products page -> `wp-admin/admin.php?page=wc-admin&filter=single_product&products=PRODUCT_ID&path=%2Fanalytics%2Fproducts`
<img width="1063" alt="Screen Shot 2021-02-16 at 5 01 27 PM" src="https://user-images.githubusercontent.com/2240960/108121211-cf39f300-7078-11eb-8547-53fd6bf7d312.png">

**Comment by pmcpinto** [comment]
> @timmyc @pmcpinto should the top seller product link also be updated as part of this PR?

Yes, that would be great. Thanks!
