### ISSUE TITLE
Custom settings - Cannot use string '0' as default value for "select" setting type 

### ISSUE THREAD

**Issue by Sartoric** [woocommerce/woocommerce#28561]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Wordpress 5.5.1
Woocommerce 4.0.0

Cannot use string '0' as default value for "select" setting type 
I have a custom setting set like this: 

`			'title'       => __( 'Title'),
			'type'        => 'select',
			'default'     => '0',
			'options'     => array( '1' => __( 'Yes'), '0' => __( 'No',)`

**Expected behavior**
'No' is shown as default option in the select list

**Actual behavior**
'Yes' is selected and no "selected" attribute is set for the "select" tag
If I use "2" instead of "0" everything works as expected

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Add a settings like the one above
2. Check it on settings panel 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by Sartoric** [comment]
Any news on this ? 
I'm still facing the issue in 5.6

And it's the same even using numbers instead of string

`'title' => __( 'Title'), 'type' => 'select', 'default' => 0, 'options' => array( 1 => __( 'Yes'), 0 => __( 'No',)`

**Comment by rrennick** [comment]
@Sartoric Thanks for creating the issue.

WooCommerce settings are stored as WordPress options. The reason you cannot use either `0` or `'0'` for a default setting can be found in the [WordPress `get_option` function](https://developer.wordpress.org/reference/functions/get_option/#source). The first conditional check in that function is

```
if ( empty( $option ) ) {
```

Both `empty( 0 )` and `empty( '0' )` return `true`. As a result, you cannot use either as an option value (or WC setting value). I'll close this issue.

**Comment by Sartoric** [comment]
@rrennick 
I missed that the get_option is used.

Anyway I guess a note about this should be added in the documentation.
This is not straightforward, as we can use 0 as a value but it cannot be set as a default.

Of course one could debug it to find it out, but it would be easier to have such a note, isn't it ?

**Comment by rrennick** [comment]
> I guess a note about this should be added in the documentation.

Thanks for the suggestion. I'll re-open the issue for that purpose.

**Comment by coreymckrill** [comment]
@Sartoric I was just revisiting this, and I was able to get `0` to work as a default value for a select with this:

```php
array(
	'id' => 'test_setting_2',
	'title' => 'Select test',
	'type' => 'select',
	'default' => '0',
	'options' => array(
		'1' => 'Yes',
		'0' => 'No',
	),
),
```

When `test_setting_2` is not set in the database, the select correctly has the "No" option selected. Are you still able to replicate the problem you originally reported here?
