### ISSUE TITLE
Coupon code accepted without matching email.  

### ISSUE THREAD

**Issue by Gnaegi4** [woocommerce/woocommerce#28560]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I created a coupon code to which I assigned an email address. 

**Expected behavior**
 I expect that the coupon to be rejected if the buyer email address doesn't match the email assigned to the coupon
**Actual behavior**
At the cart page, there is a possibility to enter a coupon code, but at this point the customer has not entered an email address.  The coupon value is applied to the purchase amount anyway.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to 'marketing->coupons ->add coupon...' Give name and click generate coupon code. General tab: create a coupon with a % discount.  Enter discount amount and expiry date validity.  Usage restriction tab: enter an email address.  Usage limit tab: leave everything blank, which means usage is unlimited
2. Go to shop.  Add item to shopping cart.
3. Go to shopping cart.  Enter coupon code.
4. Error: At this point the user has not entered an email address, but the coupon is applied to the shopping cart anyway.
**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
`
### WordPress Environment ###

WordPress address (URL): https://beambiance.com
Site address (URL): https://beambiance.com
WC Version: 4.8.0
REST API Version: ✔ 4.8.0
WC Blocks Version: ✔ 3.8.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.7.3
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.13
PHP Post Max Size: 260 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.73.0
OpenSSL/1.1.1h

SUHOSIN Installed: –
MySQL Version: 5.6.41-84.1
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.8.0
WC Database Prefix: G4h_
Total Database Size: 12.33MB
Database Data Size: 10.11MB
Database Index Size: 2.22MB
G4h_woocommerce_sessions: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
G4h_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
G4h_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
G4h_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
G4h_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
G4h_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
G4h_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
G4h_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
G4h_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
G4h_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
G4h_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
G4h_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
G4h_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
G4h_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
G4h_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
G4h_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
G4h_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
G4h_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
G4h_cartflows_ca_cart_abandonment: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
G4h_cartflows_ca_email_history: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
G4h_cartflows_ca_email_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
G4h_cartflows_ca_email_templates_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
G4h_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
G4h_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
G4h_hustle_entries: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
G4h_hustle_entries_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
G4h_hustle_modules: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
G4h_hustle_modules_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
G4h_hustle_tracking: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
G4h_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
G4h_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
G4h_newsletter: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
G4h_newsletter_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
G4h_newsletter_sent: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
G4h_newsletter_stats: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
G4h_newsletter_user_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
G4h_options: Data: 6.08MB + Index: 0.16MB + Engine InnoDB
G4h_postmeta: Data: 1.14MB + Index: 0.14MB + Engine InnoDB
G4h_posts: Data: 1.34MB + Index: 0.06MB + Engine InnoDB
G4h_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
G4h_snippets: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
G4h_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
G4h_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
G4h_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
G4h_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
G4h_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
G4h_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
G4h_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
G4h_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
G4h_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
G4h_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
G4h_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
G4h_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
G4h_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
G4h_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
G4h_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
G4h_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
G4h_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
G4h_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
G4h_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
G4h_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
G4h_yoast_indexable: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
G4h_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
G4h_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
G4h_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
G4h_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 78
custom_css: 3
customize_changeset: 13
elementor_library: 1
elementor-hf: 2
helpie_faq: 27
nav_menu_item: 14
page: 12
post: 4
product: 14
revision: 92
shop_coupon: 3
shop_order: 1
wp_block: 2
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (24) ###

PublishPress Capabilities: by PublishPress – 1.10.1
Code Snippets: by Code Snippets Pro – 2.14.0
Contact Form 7: by Takayuki Miyoshi – 5.3.1
Elementor: by Elementor.com – 3.0.14
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.13.2
Gutenberg: by Gutenberg Team – 9.5.2
Elementor - Header, Footer & Blocks: by Brainstorm Force
Nikhil Chavan – 1.5.3

Helpie FAQ: by HelpieWP – 1.4.2
Jetpack by WordPress.com: by Automattic – 9.2.1
Members: by MemberPress – 3.1.3
Newsletter: by Stefano Lissa & The Newsletter Team – 7.0.0
OptinMonster: by OptinMonster Team – 2.0.2
Sidebar Manager: by Brainstorm Force – 1.1.6
Ultimate Addons for Gutenberg: by Brainstorm Force – 1.18.2
User Role Editor: by Vladimir Garagulya – 4.57.1
W3 Total Cache: by BoldGrid – 0.15.2
WooCommerce Cart Abandonment Recovery: by CartFlows Inc – 1.2.8
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.1
WooCommerce Stripe Gateway: by WooCommerce – 4.5.5
WooCommerce Shipping & Tax: by Automattic – 1.25.4
WooCommerce USPS Shipping: by WooCommerce – 4.4.49
WooCommerce: by Automattic – 4.8.0
Yoast SEO: by Team Yoast – 15.4
WPForms Lite: by WPForms – 1.6.3.1

### Inactive Plugins (4) ###

Creative Mail by Constant Contact: by Constant Contact – 1.2.2 – Installed version not tested with active version of WooCommerce 4.0
Custom Adobe Fonts (Typekit): by Brainstorm Force – 1.0.18
Custom Fonts: by Brainstorm Force – 1.2.5
Smush: by WPMU DEV – 3.8.2

### Dropin Plugins (3) ###

advanced-cache.php: advanced-cache.php
db.php: db.php
object-cache.php: object-cache.php

### Must Use Plugins (2) ###

Endurance Page Cache: by Mike Hansen – 2.0.5
SSO: by Garth Mortensen
Mike Hansen – 0.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #3604 - /shop/
Cart: #3605 - /cart/
Checkout: #3606 - /checkout/
My account: #3607 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Astra
Version: 2.6.1 (update to version 2.6.2 is available)
Author URL: https://wpastra.com/about/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Canceled: 1
Oldest: 2020-11-18 22:40:49 +0000
Newest: 2020-11-18 22:40:49 +0000

Complete: 69
Oldest: 2020-11-11 15:38:54 +0000
Newest: 2020-12-11 15:18:46 +0000

Pending: 1
Oldest: 2020-12-11 22:55:54 +0000
Newest: 2020-12-11 22:55:54 +0000

`
</details>

**Comment by negapo** [comment]
Hi @Gnaegi4 
If the user hasn't give the email address when he applied the coupon code then Woo doesn't know if the coupon can or cant be used. Did you expect some kind of warning message like "please fill in your email before applying this coupon"?

**Comment by juliaamosova** [comment]
Hi @Gnaegi4,

Thank you for submitting the issue. However, what you describe is the expected behavior of WooCommerce. 

To expand a bit further on what @negapo already mentioned, an email verification happens when the order is placed, not before. We state the same next to the field of `Allowed emails` when you create the coupon:

![email](https://user-images.githubusercontent.com/19143190/101991810-140e6b80-3c7d-11eb-90a7-8fc3c5e5fc17.jpg)

At the checkout, if the billing email doesn't match the one specified for the coupon usage allowance, the coupon will be removed, and the message letting the user know that they are using the coupon that had not been theirs will be shown - please see gif below that shows what it will look like:

![](http://g.recordit.co/42LRjqf5rZ.gif)

With the above in mind, I am closing this issue as a non-bug. However, please feel free to comment back in case I missed something and we'd take another look.

**Comment by BrianHenryIE** [comment]
For anyone who comes across this issue, I've written some code to check the email address sooner:

https://gist.github.com/BrianHenryIE/ba1b2b04f08e8dfba5bc6c8b76cfeee5
