### ISSUE TITLE
WooCommerce Status Widget: Add Tracking

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce#28566]
The Start/Manage team is going to be looking at updating some of the WooCommerce wp-admin dashboard widgets, and this is the first of a few issues that Isotope will be looking into in the new year ( or possibly sooner! ).

<img width="474" alt="image" src="https://user-images.githubusercontent.com/22080/101968238-f389d700-3bd2-11eb-8ee9-73dcf215b18d.png">

To get a sense of how often the wp-admin _WooCommerce Status Widget_ is used, we should add tracking events each time a link is clicked in the widget:

- Event Name: `wcadmin_status_widget_click` ( cc @pmcpinto  to verify that is an okay track name )
- Prop: `link` which will be one of: net-sales, orders-processing, orders-on-hold, low-stock, out-of-stock

**Comment by pmcpinto** [comment]
> Event Name: wcadmin_status_widget_click ( cc @pmcpinto to verify that is an okay track name )

👍 Thanks for creating this issue

**Comment by timmyc** [comment]
I estimate this work at 1.
