### ISSUE TITLE
Northern Ireland as a shipping zone post Brexit

### ISSUE THREAD

**Issue by dochara** [woocommerce/woocommerce#28562]
**Is your feature request related to a problem? Please describe.**
As anyone who has been following Brexit will know, Northern Ireland will shortly be in a different category for sales and shipping than other parts of the UK. Breifly, Northern Ireland will be part of the EU single market, the rest of the UK will not. This will mean that many sellers in the EU will be able to sell and ship to NI as though it was part of the EU, but not able to do so to the rest of the UK. Similarly, depending on what they sell, sellers in the UK may have to apply different regulations/charges for shipping to NI.

**Describe the solution you'd like**
I realise that adding NI as a separate shipping zone was discounted previously - Issue #15066. However I think it may be time to revisit that decision.

**Comment by juliaamosova** [comment]
Hi @dochara,

Thanks for raising the issue!

We currently have a PR open to address Brexit related changes: https://github.com/woocommerce/woocommerce/pull/28538. 

Pinging @peterfabian and @tammullen here to evaluate the issue described here in regards to Northern Island.

**Comment by tammullen** [comment]
Additional context in paqDfi-11G-p2#comment-3302

**Comment by tammullen** [comment]
Hi @dochara, 
We are currently looking into this but in the meantime in case it is helpful you can setup shipping zones that filter on the Northern Ireland postcode prefix of BT. This can be used to either have different postage options for NI or to exclude it. More details on setting up shipping zones here https://docs.woocommerce.com/document/setting-up-shipping-zones/

![Screenshot 2020-12-11 at 19 58 27](https://user-images.githubusercontent.com/24649833/101953414-35764580-3bf2-11eb-9dc8-64b230e2a37d.png)
Example of adding postcode filter for `BT*`

![Screenshot 2020-12-11 at 19 58 11](https://user-images.githubusercontent.com/24649833/101953461-4b840600-3bf2-11eb-8dba-8cd601021cb1.png)
Using it to have a different method for NI

![Screenshot 2020-12-11 at 20 45 19](https://user-images.githubusercontent.com/24649833/101953495-5b034f00-3bf2-11eb-9224-62f9974377e3.png)
Using it to exclude NI from the shipping zone.

**Comment by peterfabian** [comment]
Hi @dochara . I've been looking into this a bit this week and it seemed to me the situation is rather complex in terms of actual rules, byt at the ned of the day, it seems that all boils down to the fact that merchants need to be able to charge taxes and shipping costs correctly and easily for NI and the rest of the UK according to different rules.

I think it should be possible to separate NI by using zipcode wildcard `BT*` and set up shipping and taxes using that filter rather easily (if merchants don't use automated tax solution). Please let us know if you think this is not sufficient. 

I'd prefer us to not split NI as a separate territory, as politically it still belongs to UK and (according to my understanding) it will become part of UK VAT area, just following EU rules, and who knows what happens later down the line with tax rules.

Do you foresee any problems with that approach?
Thanks!

**Comment by dochara** [comment]
It isn't quite as simple as that unfortunately. The purpose of the NI backstop is to allow continued free movement of goods between the EU and NI and in such transactions EU vat rules will continue to apply. UK vat rules will apply for services. 

Thus UK sellers selling physical goods to NI may effectively be selling into the EU as a third country. I have no doubt there will be exceptions and special arrangements for particular categories of product - none of this is simple.

For sellers in the ROI, who ship to the ROI and NI but not mainland UK, but who accept orders from buyers in any country, the inability to separate NI easily has always been an issue. This is not an uncommon situation at all. There are workarounds of course, but it's not straightforward. It is likely that more sellers than previously, particularly small sellers, will now fall into this category. Others will continue to ship to the EU only, which will for goods include NI, but caese to ship to mainland UK.

I'm no expert on tax of any kind in any juristiction, but I don't think this is going to be simple no matter how it is approached.

**Comment by peterfabian** [comment]
> UK sellers selling physical goods to NI may effectively be selling into the EU as a third country

I think that should be fine as long as the taxes and shipping are set up correctly by the store admin, which can be done using the zipcode filter, or am I missing something? 

If we wanted to allow/disallow _selling_ to GB/NI, I'm a bit afraid that when we add NI as a separate country, then it will be other places where people might get confused (e.g. by taxes not being applied to NI when people set them up for the whole UK). 

We could add a subdivision of UK into GB and NI, but unless we start requiring people to fill it in, it won't be very useful. Additionally, I think the same _tax_ and _shipping_ setup is achievable using the ZIP code filter, which is already required today.

**Comment by Lindstromer** [comment]
Any news on this? Would be nice to be able to get XI from Woo when an order is placed. Mainly from a VAT perspective, rather than shipping availability etc.

**Comment by peterfabian** [comment]
Hi @Lindstromer , can you please elaborate on what you mean by XI?

**Comment by Lindstromer** [comment]
> Hi @Lindstromer , can you please elaborate on what you mean by XI?

The code for Northern Ireland seems to be XI, from the different sources I have read. 😄 

https://www.avalara.com/vatlive/en/vat-news/brexit-northern-ireland-vat-and-eoro--xi--number.html

**Comment by tammullen** [comment]
Hi @Lindstromer 
The new XI prefixed EORI number like all EORI numbers are not captured within WooCommerce Core. Usually these are handled by Plugins or custom code.

**Comment by peterfabian** [comment]
Thanks for the explanation, and apologies, I haven't seen the VAT number rule before. 
We currently don't plan to add a separate shipping zone for Northern Ireland and we have a guide posted for users in the docs which hopefully covers most use cases:
https://docs.woocommerce.com/document/ready-for-brexit-a-guide-for-woocommerce-store-owners/

In addition, there's a dev doc published on the blog: https://developer.woocommerce.com/2021/01/06/brexit-and-changes-to-woocommerce-core-code/

I'll close this for now. If we'll find out we need to change anything else wrt to Brexit, we can open a separate issue. Thanks all for providing the clarification and further information!

**Comment by webdados** [comment]
What about EU countries (Portugal, Spain, France...) selling goods to end customers Northern Ireland? As far as the NI protocol states https://www.nidirect.gov.uk/articles/eu-exit-and-northern-ireland-protocol it seems that VAT should still be charged for NI (but not anymore for the rest of UK). How can we define different tax rules? Is it enough to use "GB" as country code and then "BT*" as postcode?

![image](https://user-images.githubusercontent.com/6853605/104202945-7779ed80-5423-11eb-881e-29dfb599f868.png)

**Comment by tammullen** [comment]
Hi @webdados 

> How can we define different tax rules? Is it enough to use "GB" as country code and then "BT*" as postcode?

Yes you can use `BT*` as a postcode wildcard. More info on setting these up is here https://docs.woocommerce.com/document/setting-up-taxes-in-woocommerce/#section-12

You can also see an example earlier in this issue where I have used it for shipping zones.

In case you haven't seen it we also have a guide posted for users in the docs which hopefully covers most use cases:
https://docs.woocommerce.com/document/ready-for-brexit-a-guide-for-woocommerce-store-owners/

In addition, there's a dev doc published on the blog: https://developer.woocommerce.com/2021/01/06/brexit-and-changes-to-woocommerce-core-code/

**Comment by DeanForde** [comment]
Hi im just wondering if this will work for tax rules? I have a tax rule for all of GB but then I have a standalone rule for NI but I'm wondering will the "*" Wildcard in GB override the NI tax rule? as in will I need to include all GB postcode wildcards instead of just the "*" ?  

![image](https://user-images.githubusercontent.com/20243306/122542561-bd665d80-d022-11eb-831f-ae147f7cb47f.png)
