### ISSUE TITLE
WooCommerce Status Widget: Add Store Setup State

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce#28568]
The Start/Manage team is going to be looking at updating some of the WooCommerce wp-admin dashboard widgets, and this is the first of a few issues that Isotope will be looking into in the new year ( or possibly sooner! ).

<img width="474" alt="Dashboard ‹ bend outdoors — WordPress 2020-12-11 17-03-58" src="https://user-images.githubusercontent.com/22080/101968377-c25dd680-3bd3-11eb-83a3-98f3d2b1cb00.png">

One of the changes we would like to make to the Status Widget on the wp-admin dashboard, is to make it more useful for brand-new stores that are still in the process of getting things setup and configured.

On Woo pages, we display the "Store Setup" link in the Activity Panel area if a store has remaining setup items to perform, but this visual nudge is not shown on the wp-admin dashboard page. As such, the idea is to utilize the existing Status Widget to remind managers of the site that they have remaining setup tasks to do.

We implemented a similar solution in Calypso on wordpress.com in https://github.com/Automattic/wp-calypso/pull/44547

Acceptance Criteria:

- [ ] When a store is still in setup mode, as determined by the [logic that shows the Store Setup activity panel](https://github.com/woocommerce/woocommerce-admin/blob/main/client/header/activity-panel/index.js#L147-L151) the Status Widget should not show the standard stats/links, rather it should show the new design ( TBD ) informing users that their store has remaining setup tasks.
- [ ] Once the setup task list has been completed, or hidden, the Status Widget should render the standard state/content seen in the screenshot above.

cc @elizaan36 as this is an issue we will need some design assistance with.

**Comment by elizaan36** [comment]
hey @timmyc - put together a potential design for this store setup link using similar copy to the one you referenced in Calypso. Thoughts?

![store setup prompt](https://user-images.githubusercontent.com/5121465/103318323-bd7e8c80-49f3-11eb-8437-1ef90079a0e0.png)

**Comment by timmyc** [comment]
Looks really great to me @elizaan36 - fwiw we do have much easier access to the number of remaining tasks in the setup checklist, and we also have the "status indicator" component we show in the navigation bar panel area if we wanted to re-use that at all.

**Comment by timmyc** [comment]
@pmcpinto what do you think about this for the upcoming sprint?

**Comment by elizaan36** [comment]
> we do have much easier access to the number of remaining tasks in the setup checklist, and we also have the "status indicator" component we show in the navigation bar panel area if we wanted to re-use that at all.

Yes! I was thinking it would be interesting to target specific tasks similar to what we're doing with the first product email - maybe less daunting to break down the concept of completing setup that way. For example, something like "You're on step 1 of 5. Let's get started adding your first product."

**Comment by pmcpinto** [comment]
> @pmcpinto what do you think about this for the upcoming sprint?

Sounds good to me.

I'd keep it simple first and just have the generic store setup link instead of focus on specific tasks. Unless the effort required to highlight specific tasks and the current progress is minimal.

**Comment by timmyc** [comment]
_Not sure if this is feature creep_ - but while testing out a new store, I noticed that the Creative Mail extension is creating a wp-admin dashboard widget using an [alternative method via a meta-box](https://plugins.trac.wordpress.org/browser/creative-mail-by-constant-contact/trunk/src/managers/AdminManager.php#L434)... this results in the "widget" appearing at the top of the column, well above where the current Woo Status dash widget is shown:

![Screenshot_20210104-125429](https://user-images.githubusercontent.com/22080/103579357-066b9080-4e8d-11eb-8ba8-f417aa1ec61c.png)

So I'm wondering if we should consider exploring creating a new dashboard meta box akin to what is being done in the Creative Mail plugin that is only shown when setup checklist tasks are still pending completion. If we went that route, we could get a higher placement on page ( especially in narrow viewports ) - and I'm thinking we could just not show the other existing widgets until the setup checklist is no longer being shown.

**Comment by pmcpinto** [comment]
@timmyc placing the widget at the top of the dashboard would definitely help. I'm assuming that the effort required to follow this approach is fairly the same, right?

**Comment by elizaan36** [comment]
Good call @timmyc. Creating a new dashboard widget that could appear at the top would be ideal if possible. The current WC status widget appears at the very bottom by default and I'm not sure new users will know it's there, or at least it would be harder to find.

Here are alternatives to the basic store setup prompt shared above that show the number of steps remaining.

![WooCommerce setup - with steps](https://user-images.githubusercontent.com/5121465/103815652-4b2c2e80-5029-11eb-98da-a56a5e7347ab.png)

![WooCommerce setup - with steps and progress indication](https://user-images.githubusercontent.com/5121465/103816687-030e0b80-502b-11eb-8175-afe0d9d5a608.png)

**Comment by timmyc** [comment]
> I'm assuming that the effort required to follow this approach is fairly the same, right?

Well I think it could be a bit easier possibly. If we followed the Creative Mail implementation, it would be using a meta box on the dashboard, which is a bit different the the widgets. So it would be implementing an entirely new feature vs modifying the existing one. Roughly I think the work would involve:

- Implementing a new metabox using the designs above
- Adding logic to the existing Woo Dashboard widgets, and not showing them **until** store setup is complete
- Ensuring that legacy/established stores still see the existing dash widgets.

**Comment by pmcpinto** [comment]
> Well I think it could be a bit easier possibly.

@timmyc it seems that we have a winner then 😄 

@elizaan36 regarding the widget/meta box copy, I'm wondering if we should tweak the CTA copy to have it more focused on the end goal. Something like: "Start selling!" WDYT?

**Comment by elizaan36** [comment]
I like the idea of focusing on the outcome but prefer that CTA sans punctuation - first one here:
<img width="634" alt="image" src="https://user-images.githubusercontent.com/5121465/103938358-b8a29280-50ef-11eb-9647-114b10112b24.png">

**Comment by pmcpinto** [comment]
> I like the idea of focusing on the outcome but prefer that CTA sans punctuation - first one here:

👍 It looks better without the punctuation

**Comment by timmyc** [comment]
I'm thinking this is probably a 3 for this one given it steps outside of the standard dashboard widget zone, and will require writing some test cases for the Woo Release that this will land in.

**Comment by moon0326** [comment]
@pmcpinto @elizaan36 @timmyc It's not urgent, but I would like to have a text copy for each step (Store details, Add my products, Set up payments, set up tax, and personalize my store). I'm gonna use dummy copies for now.

@elizaan36 Could you send me the link to the main image?

Thank you!

**Comment by moon0326** [comment]
> * Implementing a new metabox using the designs above
> * Adding logic to the existing Woo Dashboard widgets, and not showing them **until** store setup is complete
> * Ensuring that legacy/established stores still see the existing dash widgets.

Do we consider the store setup is complete when the store owner completes all five tasks (store details, add my products, setup payments, set up tax, personalize my store)? Or do we want to keep it simple for this round and just display the setup up a link?  (Reading the thread, it sounds like the decision hasn't been made yet).

**Comment by moon0326** [comment]
@elizaan36 Hi ✋ I think "Step X of X" might not work as users might finish tasks randomly. For example, users can finish task 1 -> finish 3 instead of 2.

**Comment by elizaan36** [comment]
hey @moon0326 !

> @pmcpinto @elizaan36 @timmyc It's not urgent, but I would like to have a text copy for each step (Store details, Add my products, Set up payments, set up tax, and personalize my store). I'm gonna use dummy copies for now.

As far as I remember we're only going to have one version (not task specific) so the copy will be as shown.

> You’re almost there! Once you complete store setup you can start receiving orders.
[Start selling]

[Here's the link to the image](https://share.getcloudapp.com/4gu1nn6r)

If we need to keep it simple, we can start with this version that doesn't include the step number you're on.
![WooCommerce setup](https://user-images.githubusercontent.com/5121465/108133980-10cb9d80-707b-11eb-97fd-1bdada360386.png)

Once the store setup tasks are complete this wouldn't show, which I believe is same logic as the store setup link in the top bar.

**Comment by moon0326** [comment]
> As far as I remember we're only going to have one version (not task specific) so the copy will be as shown.

Thank you! That would make it much simpler. @timmyc Could you confirm this please?

> Here's the link to the image

Thank you 👍

**Comment by moon0326** [comment]
Hey @pmcpinto @elizaan36 

I just finished my 1st version of the widget and tested it. I noticed that there can be more than 5 tasks as shown as below.

How should we deal with this case? Are going with only 5 tasks (store details, add my products, set up tax, set up shipping, personalize my store)? I could be wrong, but it can be tricky to get the extra tasks (Set up WooCommerce Payments in this case) in the backend.

![Screen Shot 2021-02-17 at 4 44 32 PM](https://user-images.githubusercontent.com/4723145/108287330-8600a680-713f-11eb-9e43-690784c076c0.jpg)

**Comment by elizaan36** [comment]
> Are going with fixed 5 tasks (store details, add my products, set up tax, set up shipping, personalize my store)?

Can we also include "Choose payment methods" (what appears if you don't install WCPay) or the WCPay one shown here? 
I'm curious what's the logic on the store setup link that shows in the top bar as well until the setup tasks are complete? We should match that logic here if possible.

**Comment by moon0326** [comment]
> > Are going with fixed 5 tasks (store details, add my products, set up tax, set up shipping, personalize my store)?
> 
> Can we also include "Choose payment methods" (what appears if you don't install WCPay) or the WCPay one shown here?
> I'm curious what's the logic on the store setup link that shows in the top bar as well until the setup tasks are complete? We should match that logic here if possible.

I found logic :) I will include all of them.

**Comment by pmcpinto** [comment]
@moon0326 it seems that we're not tracking this new setup state. Do you want me to open a new issue about this?

**Comment by timmyc** [comment]
@pmcpinto looking back at the original issue here and I'm not seeing any specific tracks events declared in the acceptance around the store setup state widget. So to verify - do you want a track recorded every time this widget is shown? Or are we just interested in the clicks on the button? And of course, event names and any props we should be collecting would be good to note as well. Then I'm thinking we should just create a new issue for adding these tracks for cycle 12, but try and knock it out in the first week to get the PR in ahead of the 5.4 code freeze ( May 13 )

**Comment by pmcpinto** [comment]
I think it would be great to have both:

`wcadmin_setup_widget_view`
`wcadmin_setup_widget_click`

Nice to have on both: an event prop (`completed_tasks`) showing the number of completed tasks

And it would also be good to have one to track the views of the stats widget: `wcadmin_status_widget_view`

**Comment by timmyc** [comment]
Thanks Pedro! Follow-up issue created: https://github.com/woocommerce/woocommerce/issues/29731
