### ISSUE TITLE
Improve URL Structure

### ISSUE THREAD

**Issue by cbdkaufen** [woocommerce/woocommerce#28573]
I had started thiss topic on wordpress.org,
[https://wordpress.org/support/topic/not-so-perfect-url/](https://wordpress.org/support/topic/not-so-perfect-url/)

 but I have been told to open this issue here.

Here is the ongoing problem:

URLs are – together with the title tag – the most important Onpage SEO factors, as these deliver the first information to a potential viewer of a website.

Regarding the URL Structure of Woocommerce, they do differ from what is called best practice – as they ALWAYS deliver an extra level of complexity & depth to a website.

instead of

domain.tld/category/product
or
domaint.tld/product

you always get

domain.tld/product/abc

In my case it is like this:
[https://cbdkaufen.com/product/cbd-oel-2000mg/](https://cbdkaufen.com/product/cbd-oel-2000mg/)
should look like this

domain.tld/cbd-oel-2000mg/

to get the most out of it.

I always disliked the fact that you need to enter a category base/product base and
I know that woocommerce would mix the urls up with other taxonomies, pages or posts – but then again you would have to think of woocommerce as a not so good solution in terms of seo as it limits itself to the boundaries set by a blogging platform.
There are third party providers meanwhile which do a hack on the woocommerce core, but I would really appreciate this being implemented as a potential core feature which would enhance the SEO capabilities of woocommerce tremendously and finally put it on a level with prestashop, magento, shopify, shopware and all the other “real” Ecommerce-suits, which also had to learn the core principles of SEO in more than a decade (no disrespect, but currently wc is an awesome e-commerce module on top of a great blog environment and not really an ecommerce-platform with blogging capability).

In fact I think that once you install Woocommerce, it should take over the lead and prioritize URLS/taxonomies that are generate by itself in the worddpress environment, so that if there were other taxonomies fighting for the same prettyurl - the other ones should yield.

I think 2021 should be the year when woocommerce developers should integrate this feature natively (at least optional!) and then limit the taxonomies and names of pages/posts/etc to non product/product-category names.

Kind regards!

**Comment by mfs-mindsize** [comment]
@cbdkaufen - Interesting. Would you be able to share a link to two on how much this signal still impacts SEO in 2021+?  No doubt there was a time when The (Google) Algorithm focused heavily on the URL structure. But that's not what it used to be, is it? 

In fact, as I'm sure you already know, Google is experimenting with non-full URLs in Chrome. 

Google: We'll test hiding the full URL in Chrome 86 to combat phishing
[https://www.zdnet.com/article/google-well-test-hiding-the-full-url-in-chrome-86-to-combat-phishing/](https://www.zdnet.com/article/google-well-test-hiding-the-full-url-in-chrome-86-to-combat-phishing/)

If that's the case, then how much value can Google be placing on the URL structure as it relates to UX, and inturn from UX to SEO? "It's important, but we're not going to show it"? That would be odd, even by Google standards :)

If we embrace Google's #1 SEO mantra: "Design for the user, not the bot/algorithm." and most users don't seem to care about the full URL - at least if you ask Google - how much value is this going to add? As opposed to focusing on other far more important signals? 

I'm not dismissing your idea. I'm only wanting to get a better sense of how significant this is in 2021+.

**Comment by rrennick** [comment]
> Would you be able to share a link to two on how much this signal still impacts SEO in 2021+?

@cbdkaufen I'm labeling this issue with `needs feedback`. Could you provide us with references showing the issue you described with the current URL structure?
