### ISSUE TITLE
Can't authenticate to the REST API using oauth

### ISSUE THREAD

**Issue by GianBarGian** [woocommerce/woocommerce#28578]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Can't connect to the REST API using oauth 

**Expected behavior**
Both via frontend or using postman I should be able to connect to the api using oauth1.0. 
**Actual behavior**
While I can access the resources through basic authentication,this does not work when I try to authenticate using oauth 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
Create a new key for the rest api
Open postman and try to GET resources with basic auth (success) (e.g. https://www.example.subdomain.com/wp-json/wc/v3/products)
Try to switch to oauth1.0 authentication method 
Send the GET request to the same url
Get a 401 error "Invalid signature - provided signature does not match."

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): https://payments.yogicyantra.com
Site address (URL): https://payments.yogicyantra.com
WC Version: 4.8.0
REST API Version: ✔ 4.8.0
WC Blocks Version: ✔ 3.8.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.7.3
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.13
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1g-fips

SUHOSIN Installed: –
MySQL Version: 5.7.26-29-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.8.0
WC Database Prefix: wppg_
Total Database Size: 44.95MB
Database Data Size: 27.05MB
Database Index Size: 17.90MB
wppg_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppg_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppg_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppg_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wppg_woocommerce_order_items: Data: 0.28MB + Index: 0.14MB + Engine InnoDB
wppg_woocommerce_order_itemmeta: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wppg_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wppg_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppg_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppg_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppg_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppg_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppg_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppg_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppg_actionscheduler_actions: Data: 0.52MB + Index: 0.48MB + Engine InnoDB
wppg_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppg_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppg_actionscheduler_logs: Data: 0.44MB + Index: 0.30MB + Engine InnoDB
wppg_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppg_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppg_comments: Data: 1.52MB + Index: 1.23MB + Engine InnoDB
wppg_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppg_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppg_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppg_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppg_icl_languages_translations: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
wppg_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppg_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppg_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppg_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppg_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppg_icl_strings: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wppg_icl_string_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppg_icl_string_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppg_icl_string_pages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppg_icl_string_positions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppg_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppg_icl_string_translations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppg_icl_string_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppg_icl_translate: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppg_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppg_icl_translations: Data: 0.09MB + Index: 0.28MB + Engine InnoDB
wppg_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppg_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppg_icl_translation_status: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wppg_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wppg_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppg_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppg_litespeed_img_optm: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wppg_litespeed_optimizer: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppg_options: Data: 8.33MB + Index: 0.08MB + Engine InnoDB
wppg_podsrel: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wppg_postmeta: Data: 8.52MB + Index: 9.03MB + Engine InnoDB
wppg_posts: Data: 2.52MB + Index: 0.55MB + Engine InnoDB
wppg_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wppg_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppg_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wppg_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wppg_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppg_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppg_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppg_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppg_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppg_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wppg_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppg_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppg_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppg_wc_customer_lookup: Data: 0.17MB + Index: 0.14MB + Engine InnoDB
wppg_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppg_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppg_wc_order_product_lookup: Data: 0.28MB + Index: 0.36MB + Engine InnoDB
wppg_wc_order_stats: Data: 0.22MB + Index: 0.25MB + Engine InnoDB
wppg_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wppg_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wppg_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wppg_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppg_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wppg_wrc_caches: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wppg_wrc_relations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 761
category_content: 8
custom_css: 1
ec_woo_ddb_template: 18
general: 2
nav_menu_item: 6
page: 10
post: 2
product: 39
product_variation: 12
revision: 61
shop_coupon: 6
shop_order: 1752
shop_order_refund: 5
subcategory_content: 18
_pods_field: 102
_pods_pod: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 4.8.0

### Inactive Plugins (17) ###

Admin Menu Editor: by Janis Elsts – 1.9.7
All-in-One WP Migration: by ServMask – 7.31
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.4.4
Enhanced E-commerce for Woocommerce store: by Tatvic – 2.3.6.1
Imagify: by WP Media – 1.9.13
Order / Coupon / Subscription Export Import Plugin for WooCommerce (BASIC): by WebToffee – 1.7.1
Pods - Custom Content Types and Fields: by Pods Framework Team – 2.7.24
Product Feed PRO for WooCommerce: by AdTribes.io – 9.2.1
Redirection: by John Godley – 4.9.2
SG Optimizer: by SiteGround – 5.7.10
Stripe For WooCommerce: by Payment Plugins
support@paymentplugins.com – 3.2.8

WooCommerce Multilingual: by OnTheGoSystems – 4.10.3
WooMail - WooCommerce Email Customizer: by CidCode – 3.0.34 – Installed version not tested with active version of WooCommerce 4.0
WPML Multilingual CMS: by OnTheGoSystems – 4.4.6
WPML String Translation: by OnTheGoSystems – 3.1.5
WPML Translation Management: by OnTheGoSystems – 2.10.3
WP REST Cache: by Acato – 2020.3.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #1166 - /negozio/
Cart: #1167 - /carrello/
Checkout: #1168 - /pagamento/
My account: #1169 - /mio-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.0
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1,791
Oldest: 2020-11-12 15:21:22 +0000
Newest: 2020-12-13 10:22:43 +0000

Pending: 1
Oldest: 2020-12-13 12:17:22 +0000
Newest: 2020-12-13 12:17:22 +0000

`
</details>

**Comment by rrennick** [comment]
@GianBarGian Please see the documentation for using OAuth with the API: https://woocommerce.github.io/woocommerce-rest-api-docs/v1.html#authentication.
