### ISSUE TITLE
Cannot update order from 'woocommerce_checkout_create_order' hook

### ISSUE THREAD

**Issue by adrienthiery** [woocommerce/woocommerce#28580]
**Is your feature request related to a problem? Please describe.**
Hi there, 
I think there's a misconception (or I don't understand something) in the `woocommerce_checkout_create_order` hook.

It says in the docs and in the code : 
> Action hook to adjust order before save.

But I don't see how we can modify the `$order` from this hook, considering we pass the value and we don't get anything back from the hook.

**Describe the solution you'd like**
Would it be a good idea to pass a reference to the order [here](https://github.com/woocommerce/woocommerce/blob/492792476c0aad09b839b58153bb3d5755d5bd08/includes/class-wc-checkout.php#L386) , that way we can apply any changes we want to it before it is saved?

**Describe alternatives you've considered**
I don't see any, but would happily look into any alternatives or hints of alternatives

**Comment by tammullen** [comment]
Hi @adrienthiery 

Thank you for taking the time to share this idea, we really appreciate your help.

While this is clearly a great improvement/idea we won’t be able to tackle it in the upcoming weeks. We’re going to add it to our backlog where it will be considered for future releases.

**Comment by DavidAnderson684** [comment]
> But I don't see how we can modify the $order from this hook, considering we pass the value and we don't get anything back from the hook.

Call order methods, e.g. `$order->update_meta_data('my_key', 'my_value');`

**Comment by adrienthiery** [comment]
Hi there,
I had the time to look at that a bit more, and modifying the order does work, but there are some shenanigans going on with adding fees and taxes calculations in there... I'll close this for now but might re-open some bug related to this if I don't manage to beat it.

Thanks for the reactions though, very much appreciated! 🙂
