### ISSUE TITLE
Stock is decreased when you hit Update for already Cancelled order

### ISSUE THREAD

**Issue by treibalen** [woocommerce/woocommerce#28585]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When a paid order is cancelled and you click **Update** once again, stock is increased again.

**Expected behavior**
No further stock adjustment should happen.

**Actual behavior**
When a paid order is cancelled and you click **Update**, stock is increased again.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Place a test order. I used Stripe and my order was in Completed status. Stock is correctly descreased.
2. Change order status to Cancelled and click **Update**. Stock is correctly increased.
3. Click **Update** order without making any changes to it.
4. See how stock is decreased again:

![https://d.pr/i/zEz2wn](https://d.pr/i/zEz2wn+) 
Full Size: https://d.pr/i/zEz2wn

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

WooCommerce  4.8.0

**Comment by juliaamosova** [comment]
Seems related to https://github.com/woocommerce/woocommerce/issues/28505 but not the same.

**Comment by tammullen** [comment]
Thanks @treibalen for reporting this!

I can reproduce it on my end. 

![Screenshot 2020-12-20 at 16 12 35](https://user-images.githubusercontent.com/24649833/102718113-50c20e80-42de-11eb-8286-55776dcea316.png)

​
We’re going to solve this bug as soon as possible. Stay tuned for updates.

**Comment by vedanshujain** [comment]
This is fixed via #28620 and will be available with WC 4.9
