### ISSUE TITLE
Attribute visibility not update or ignored on woo rest api put request

### ISSUE THREAD

**Issue by yulumadavid** [woocommerce/woocommerce#28597]
We run over 70 woo shops and since 1,5 week we've run into this problem with only 2 shops so far. I would like to share to contribute. We did resolve this by hiding the attributes with css but I strongly believe this could be something others also could experience.

**How it worked:**
When we send attributes in the json array we can set 'visible' to 1 or to 0. This worked and still works for all our shops. Even for the two shops that are running into trouble right now **for new products**.

**What is happing right now**
Now for older products that already exist a longer time (i can't put my vinger on the difference between items that work and don't work) the call 'visible' is ignored. It doesn't matter if we set it to 0 or 1 the value stays as it is. For the newer products it does work and the difference of 0 and 1 is not ignored.

**Example**
We send https://prnt.sc/w3epgb but the result is still https://prnt.sc/w3est4

**Able to reproduce**
I CAN reproduce with these specific products but I CAN'T with new products. Also when I delete the product in my test environment and recreate the product the problem is solved.

I understand deeply that without reproduction you peeps can't do anything but do would like to share the problem. If more people experience this it might be a problem. We've seen a similar problem with variations _price not updated last year after Woo update. This problem was also not reproducable but was fixed after a while.

If we will find or experience a fix/change I will post it here.

**Comment by rrennick** [comment]
> When we send attributes in the json array we can set 'visible' to 1 or to 0.

@yulumadavid The `visible` property is a boolean and should be either `true` or `false`. I used the following steps to test the API in WooCommerce 5.8.0:

- I added an attribute through the dashboard

<img width="1088" alt="Screen Shot 2021-10-22 at 11 19 09 AM" src="https://user-images.githubusercontent.com/343847/138471834-f02e16ec-8f96-442d-863b-b569be8dd97e.png">

- I retrieved the product via the API

```
   "attributes": [
    {
      "id": 0,
      "name": "i18731",
      "position": 0,
      "visible": true,
      "variation": false,
      "options": [
        "Issue 18731"
      ]
    }
  ],
```

- I did a `PUT` that updated the attribute `visible` and `option` properties
- 
```
"attributes": [
    {
      "id": 0,
      "name": "i18731",
      "position": 0,
      "visible": false,
      "variation": false,
      "options": [
        "Issue 18731 updated"
      ]
  }]
```

- The return from the `PUT` had the updated data
- I verified that the product had been updated via the dashboard

<img width="1093" alt="Screen Shot 2021-10-22 at 11 25 07 AM" src="https://user-images.githubusercontent.com/343847/138472230-1712df0f-bccc-4875-9ef8-3d920c011e94.png">

If you are still seeing this issue using boolean values with just WooCommerce active, please let us know.
