### ISSUE TITLE
Error while installing @woocommerce/e2e-core-tests

### ISSUE THREAD

**Issue by NicestRudeGuy** [woocommerce/woocommerce#28602]
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

I want to use woocommerce's core test with my own setup ( non docker ). I have currently cloned the repo and extracted the e2e dir and it works fine but  i need to have this for several more sites , when i tried to use the npm package i got error for which i attached the screenshot below.I have every dependencies installed. 

Also update the link https://www.npmjs.com/package/@woocommerce/e2e-core-tests#setting-up-the-test-environment

Great work with the plugins and tests though 👍

link of the npm module 
https://www.npmjs.com/package/@woocommerce/e2e-core-tests

Screenshot
![image](https://user-images.githubusercontent.com/9863419/102354502-ab065b00-3fd0-11eb-878c-937a87f1fe69.png)

**Comment by rrennick** [comment]
@NicestRudeGuy Thanks for reporting the issue. The two issues with the package were fixed in #28463 and #28464. We will be releasing a new version of the package this week.
