### ISSUE TITLE
CSS3 validation issue - speak property

### ISSUE THREAD

**Issue by stodorovic** [woocommerce/woocommerce#28601]
**Is your feature request related to a problem? Please describe.**
Check _woocommerce.css_ on [https://jigsaw.w3.org/css-validator/](https://jigsaw.w3.org/css-validator/). There are few errors:
> Value Error : speak none is not a speak value : none

**Describe the solution you'd like**
Related to https://github.com/w3c/csswg-drafts/issues/510 speak property should be **"never"** instead of **"none"**.

**Describe alternatives you've considered**

**Additional context**
![woocommerce-css-errors](https://user-images.githubusercontent.com/15647032/102336694-cef67c00-3f91-11eb-9b1c-6ae8d393b2eb.png)

**Comment by roykho** [comment]
Closed via https://github.com/woocommerce/woocommerce/pull/28607
