### ISSUE TITLE
WooCommerce logout won't redirect properly, leads to white screen

### ISSUE THREAD

**Issue by simplicity17** [woocommerce/woocommerce#28619]
When logging in, everything works perfectly. When logging out, there are a number of outcomes, but after much testing, I believe the cause is the "Are you sure you want to logout" endpoint. If it does not appear, you get a white screen/broken redirect. If you go back from this broken screen, you have the WooCommerce notificaiton "Do you want to logout" with a logout button. From here, no matter which logout button you click, everything logs out and redirects correctly. The "Do you want to logout" prompt/screen/redirect is what is causing everything to break.

This is driving me crazy, I have no clue what is happening. This is my only website this is happening on. I am using the Woostify theme (my account page is built using their template system in conjunction with Elementor). I contacted Woostify, they can't seem to figure it out and believe it is WooCommerce's issue.

I have tried it with Wordpress 2020 theme and WooCommerce default barebones My Account widget/shortcode and the results are the same. No matter what I do, what I deactivate, etc. I get the same bug.

Thank you in advance for your help!!

View screen recording of what is happening here: https://youtu.be/mBuNQadeI4Q

**Comment by tammullen** [comment]
Hi @simplicity17,
Thank you for reporting the issue. However, you also reported previously here https://github.com/woocommerce/woocommerce/issues/28493. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
