### ISSUE TITLE
Database request error

### ISSUE THREAD

**Issue by shulakmaster** [woocommerce/woocommerce#28611]
I have found bug with "Filter Products by Attribute" widget.
In some cases it make wrong database request

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
See (1,2,3) screenshots
It coused by 
woocommerce/includes/widgets/class-wc-widget-layered-nav.php - file
get_filtered_term_product_counts() - function

**Solution**
I just was add the following <code>
if (strlen($term_ids_sql) < 3) {
			return array();
		}
</code> code here 
woocommerce/includes/widgets/class-wc-widget-layered-nav.php
See 4 screenshot
Please add this or some analog in one of the next plugin updates

**Screenshots**
1) https://prnt.sc/w4m2ng
2) https://prnt.sc/w4moyj
3) https://prnt.sc/w4mrlk
4) https://prnt.sc/w4n85k

**Files if screenshots won't be enabled**
1.
![1](https://user-images.githubusercontent.com/26648439/102482381-c5d9dd80-406b-11eb-8bfc-959bc7eb622c.png)
2.
![2](https://user-images.githubusercontent.com/26648439/102482386-c6727400-406b-11eb-98b4-6a3b4bf822c9.png)
3.
![3](https://user-images.githubusercontent.com/26648439/102482388-c70b0a80-406b-11eb-877c-0550756e90f7.png)
4.
![4](https://user-images.githubusercontent.com/26648439/102482897-98416400-406c-11eb-9e6f-4b3e4c286aa2.png)

**Comment by rrennick** [comment]
Hi @shulakmaster ,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. If you are still experiencing the issue please provide us with the information requested so we could take a look further.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
