### ISSUE TITLE
Replay webhook call

### ISSUE THREAD

**Issue by dcoturel** [woocommerce/woocommerce#28628]
Hi everyone,

I wanted to know if there is some way to re-send a web hook call that has failed. As far as I know, the only action available on a web hook call is to delete it.

Saludos,

**Comment by ObliviousHarmony** [comment]
Hello @dcoturel,

There is currently no support for retrying failed webhooks. In https://github.com/woocommerce/woocommerce/pull/27045 we were looking at adding that support but it will require some upstream work in https://github.com/woocommerce/action-scheduler first.

**Comment by dcoturel** [comment]
Hi!

Thanks for your answer.

Saludos,
