### ISSUE TITLE
Add self-hosted vs WordPress.COM status to system status

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#28626]
**Is your feature request related to a problem? Please describe.**
When support tickets come in from the marketplace I will frequently ask customers to create a staging site for me to work on while debugging their issue. This doesn't seem to work on .com hosted sites so it would be helpful to know in advance if they are self-hosted or not. 

**Describe the solution you'd like**
An additional line in the system status
>WordPress.com: yes|no

**Describe alternatives you've considered**
I've considered always recommending the Health Check plugin, just it isn't as good for me to actually get into the code and mess around where needed

**Comment by tammullen** [comment]
Thanks @helgatheviking 

Thank you for taking the time to share this idea, we really appreciate your help

I'm going to close your issue in favor of the previously submitted https://github.com/woocommerce/woocommerce/issues/27000 as we had already labelled that issue as an enhancement. Please continue sharing your feedback there if needed.

A reminder that something which might help with identifying WordPress.com sites is looking for plugins in the report like these
![Screenshot_2020-08-28_at_15_56_06](https://user-images.githubusercontent.com/24649833/91582013-258a6c80-e947-11ea-97fa-43ef78e4d232.png)

**Comment by helgatheviking** [comment]
brain. is. not. working. though I _did_ actually search for that! wow... fail. 

@tammullen is the site helper plugin always there? My end goal will be to pull this out automatically and maybe add a custom field or a tag in Helpscout so I can see it at a glance without digging through the SSR.
