### ISSUE TITLE
Recalculate taxes doesn't update "tax name" for orders

### ISSUE THREAD

**Issue by danielbitzer** [woocommerce/woocommerce#28649]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When recalculating taxes for an order from the edit order screen (or by calling `\WC_Abstract_Order::calculate_totals( true )` directly) the tax amount is recalculated by the tax name is remains the same.

**Expected behavior**
The tax name should be updated to reflect any changes made to the global tax rate.

**Actual behavior**
The tax name on the order stays the same.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to **WooCommerce > Settings > Tax > Standard rates**
2. Create a tax rate that applies to all regions with a tax name as follows: 
![](https://d.pr/i/bSV01w+)
3. Save changes
4. Go to **WooCommerce > Orders > Add order**
5. Add an item to the order
6. Save the order
7. Click the big blue "Recalculate" button
8. The tax "Test 1" should now be added.
![](https://d.pr/i/gPyV8U+)
9. Go back to **WooCommerce > Settings > Tax > Standard rates**
10. Change the **Rate %** and the **Tax Name**:
![](https://d.pr/i/beW9rP+)
11. Save changes
12. Open the previously created order
13. Click the big blue "Recalculate" button
14. Note that the **tax amount** is updated but the **tax name** is not updated 
![](https://d.pr/i/SpyUs0+)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by juliaamosova** [comment]
Hi @danielbitzer,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end - thanks for the very detailed instructions. 

I made a short gif to document the last 2 steps to confirm I can reproduce the issue - see below - I am updating the tax on the previously placed order - the tax amount changes but the tax name doesn't change:

![](http://g.recordit.co/Swthn9ja6a.gif)

We’re going to solve this bug as soon as possible.

**Comment by danielbitzer** [comment]
Thanks @juliaamosova, great to hear this is being prioritized!
