### ISSUE TITLE
Formas de Envio Não Funciona

### ISSUE THREAD

**Issue by bellapiaggi** [woocommerce/woocommerce#28653]
Quando tento realizar o teste de compra não aparece os modos de envio. 
Aparece o seguinte: There are no shipping methods available. Please ensure that your address has been entered correctly, or contact us if you need any help.

Já conferi várias vezes e o meu endereço está correto. Testei vários endereços de clientes diferentes, mas todos aparecem a mesma mensagem. 

Segue o status do Sistema: 
`
### WordPress Environment ###

WordPress address (URL): https://bellapiaggi.com.br
Site address (URL): https://bellapiaggi.com.br
WC Version: 4.8.0
REST API Version: ✔ 4.8.0
WC Blocks Version: ✔ 3.8.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.7.3
Log Directory Writable: ✔
WP Version: ❌ 5.5.3 - Há uma nova versão do WordPress disponível (5.6)
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: pt_BR
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.25
PHP Post Max Size: 260 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.73.0
OpenSSL/1.1.1h

SUHOSIN Installed: –
MySQL Version: 5.7.23-23
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.8.0
WC Database Prefix: wp_
Tamanho total do banco de dados: 10.43MB
Tamanho dos dados do banco de dados: 8.08MB
Tamanho do índice do banco de dado: 2.35MB
wp_woocommerce_sessions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_api_keys: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_attribute_taxonomies: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_downloadable_product_permissions: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_woocommerce_order_items: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_order_itemmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_tax_rates: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_woocommerce_tax_rate_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_shipping_zones: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_woocommerce_shipping_zone_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_shipping_zone_methods: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_woocommerce_payment_tokens: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_payment_tokenmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_log: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_actions: Dados: 0.02MB + Índex: 0.11MB + mecanismo InnoDB
wp_actionscheduler_claims: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_groups: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_logs: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_commentmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_comments: Dados: 0.02MB + Índex: 0.09MB + mecanismo InnoDB
wp_imagify_files: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wp_imagify_folders: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_links: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailchimp_carts: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mailchimp_jobs: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_options: Dados: 4.03MB + Índex: 0.09MB + mecanismo InnoDB
wp_postmeta: Dados: 2.45MB + Índex: 0.23MB + mecanismo InnoDB
wp_posts: Dados: 0.42MB + Índex: 0.06MB + mecanismo InnoDB
wp_prli_clicks: Dados: 0.02MB + Índex: 0.19MB + mecanismo InnoDB
wp_prli_links: Dados: 0.02MB + Índex: 0.17MB + mecanismo InnoDB
wp_prli_link_metas: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_termmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_terms: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_term_relationships: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_term_taxonomy: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_usermeta: Dados: 0.06MB + Índex: 0.03MB + mecanismo InnoDB
wp_users: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_wc_admin_notes: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_admin_note_actions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_category_lookup: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_customer_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_download_log: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_order_coupon_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_order_product_lookup: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_wc_order_stats: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_wc_order_tax_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_product_meta_lookup: Dados: 0.05MB + Índex: 0.09MB + mecanismo InnoDB
wp_wc_reserved_stock: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_tax_rate_classes: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_webhooks: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_yoast_indexable: Dados: 0.09MB + Índex: 0.08MB + mecanismo InnoDB
wp_yoast_indexable_hierarchy: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_yoast_migrations: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_yoast_primary_term: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_yoast_seo_links: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB

### Post Type Counts ###

attachment: 64
cartflows_flow: 1
cartflows_step: 2
customize_changeset: 2
elementor_font: 1
elementor_library: 9
nav_menu_item: 23
oembed_cache: 5
page: 13
post: 2
product: 8
product_variation: 7
revision: 269
shop_coupon: 1
shop_order: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (18) ###

CartFlows: por CartFlows Inc – 1.5.22
Dynamic Visibility for Elementor: por Dynamic.ooo – 3.0.1
Elementor Pro: por Elementor.com – 3.0.8
Elementor: por Elementor.com – 3.0.15
Facebook for WooCommerce: por Facebook – 2.2.0
HT Mega - Absolute Addons for Elementor Page Builder: por HasThemes – 1.5.0
Imagify: por WP Media – 1.9.13
Insert Headers and Footers: por WPBeginner – 1.5.0
Google Ads & Marketing by Kliken: por Kliken – 1.0.6
Mailchimp para Woocommerce: por Mailchimp – 2.5.0
Melhor Envio v2: por Melhor Envio – 2.9.5
Pretty Links: por Pretty Links – 3.2.1
Really Simple SSL: por Really Simple Plugins – 4.0.5
W3 Total Cache: por BoldGrid – 0.15.2
Brazilian Market on WooCommerce: por Claudio Sanches – 3.7.2
Mercado Pago payments for WooCommerce: por Mercado Pago – 4.6.0
WooCommerce: por Automattic – 4.8.0
Yoast SEO: por Equipe da Yoast – 15.5

### Inactive Plugins (2) ###

Claudio Sanches - Correios for WooCommerce: por Claudio Sanches – 3.8.0
Ecwid Ecommerce Shopping Cart: por Ecwid Ecommerce – 6.10.7

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: BRL (R$)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base da loja: #37 - /loja/
Carrinho: #38 - /carrinho/
Finalizar compra: #39 - /finalizar-compra/
Minha conta: #40 - /minha-conta/
Termos e condições: ❌ Página não definida

### Theme ###

Name: Hello Elementor
Version: 2.3.0
Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Child Theme: ❌ – Recomendamos você utilizar um tema filho no caso de você estiver personalizando o WooCommerce em um tema ascendente. Veja como criar um tema filho
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Concluído: 26
Oldest: 2020-12-05 19:41:11 +0000
Newest: 2020-12-22 15:33:00 +0000

`

**Comment by juliaamosova** [comment]
Hi @bellapiaggi,

Please note that we reply to bug reports in English language only. I used [Google Translate](https://translate.google.com/) to translate your message. You can use the same to translate my reply back. 

Translation of the title:

>Shipping Methods Does Not Work

Translation of the issue description:

>When I try to carry out the purchase test, the shipping modes do not appear.
The following appears: There are no shipping methods available. Please ensure that your address has been entered correctly, or contact us if you need any help.

>I've checked it several times and my address is correct. I tested several different customer addresses, but they all appear the same message.

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The type of issue you submitted looks like a support request which may or may not reveal a bug once proper troubleshooting is done. In order to confirm the bug, please follow one of the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.
