### ISSUE TITLE
Order status is draft when restoring it from trash in WP 5.6

### ISSUE THREAD

**Issue by renatho** [woocommerce/woocommerce#28652]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
The function `wp_untrash_post` was changed in WP 5.6, restoring the posts from trash as _draft_. So when we trash and order, and then restore, it's restoring as _draft_, instead of the original status.

**Expected behavior**
I imagine the expected behavior for the orders would be to restore them to the original status, when untrashing.

**Actual behavior**
When we restore an order from the trash, the status is always being restored as _draft_.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create a simple product.
2. Purchase the product.
3. Delete the order.
4. Go to the trashed orders, and restore the order. (Don't use the "Undo" link for the test because it has a different behavior, restoring to the original status)
5. See that the order was restored as _"draft"_.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): http://sensei-wp56.docker
Site address (URL): http://sensei-wp56.docker
WC Version: 4.9.0
REST API Version: ✔ 4.9.0
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.8.1
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.18.0
PHP Version: 7.4.13
PHP Post Max Size: 100 MB
PHP Time Limit: 600
PHP Max Input Vars: 3000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.34-MariaDB-1:10.2.34+maria~bionic-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.9.0
WC Database Prefix: wp_
Total Database Size: 4.61MB
Database Data Size: 3.17MB
Database Index Size: 1.44MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 2.05MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.23MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
course: 9
lesson: 14
nav_menu_item: 7
page: 8
post: 2
product: 3
question: 1
quiz: 14
revision: 16
shop_order: 3
shop_subscription: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (4) ###

Sensei WooCommerce Paid Courses: by Automattic – 2.2.0
Sensei LMS: by Automattic – 3.7.0-dev
WooCommerce Subscriptions: by WooCommerce – 3.0.11
WooCommerce: by Automattic – 4.9.0-dev

### Inactive Plugins (31) ###

Akismet Anti-Spam: by Automattic – 4.1.7
Classic Editor: by WordPress Contributors – 1.5
Code Snippets: by Code Snippets Pro – 2.14.0
Email Log: by Sudar – 2.3.1
Enable jQuery Migrate Helper: by The WordPress Team – 1.3.0
Gutenberg: by Gutenberg Team – 9.4.0-rc.1
Jetpack by WordPress.com: by Automattic – 8.4.1
Pixelgrade Care: by Pixelgrade – 1.7.1
Prevent Browser Caching: by Kostya Tereshchuk – 2.3.2
Query Monitor: by John Blackbourn – 3.5.2
Sensei Content Drip: by Automattic – 2.1.0
Sensei Course Participants: by Automattic – 2.0.2
Sensei LMS: by Automattic – 3.0.1 (update to version 3.6.0 is available)
Sensei LMS - Enrollment Comparison Tool: by Automattic – 1.0.0
Sensei LMS Certificates: by Automattic – 2.0.7
Sensei LMS Course Progress: by Automattic – 2.0.3
Sensei LMS Media Attachments: by Automattic – 2.0.3
Sensei Scenario Creator: by Automattic – 0.0.1
Sensei Share Your Grade: by Automattic – 2.0.1
Theme Check: by Theme Review Team – 20200922.1
User Switching: by John Blackbourn & contributors – 1.5.3
WooCommerce Admin: by WooCommerce – 1.3.0-beta.1
WooCommerce Memberships: by SkyVerge – 1.20.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 1.6.18 (update to version 2.1.1 is available) – Installed version not tested with active version of WooCommerce 4.0
WooCommerce Product Bundles: by SomewhereWarm – 5.13.1 – Installed version not tested with active version of WooCommerce 4.0
WooCommerce Services: by Automattic – 1.22.2 (update to version 1.25.4 is available) – Installed version not tested with active version of WooCommerce 4.0
WP Crontrol: by John Blackbourn & crontributors – 1.8.5
WP Log Viewer: by Maxwell Berkel – 1.2.1
WPML Multilingual CMS: by OnTheGoSystems – 4.3.6
WPML String Translation: by OnTheGoSystems – 3.0.6
WPML Translation Management: by OnTheGoSystems – 2.9.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #60 - /shop/
Cart: #62 - /cart/
Checkout: #64 - /checkout/
My account: #66 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.0
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: http://sensei-wp56.docker
Subscription Statuses: wc-pending: 1
WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: United Kingdom (UK)

### Action Scheduler ###

Complete: 69
Oldest: 2020-12-21 13:06:41 +0000
Newest: 2020-12-22 15:36:17 +0000

`
</details>

**Comment by juliaamosova** [comment]
Hi @renatho,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

See gif below showing the behavior:

![](http://g.recordit.co/PN9LNhmnSs.gif)

This is a basic functionality which in my view needs to work correctly which is why I am giving this issue a `high` priority.

**Comment by kevinruscoe** [comment]
My PR fixes this particular issue. However, due to the change in WP5.6, products are also effected (i.e trashing a "pending review" product, then restoring it, chucks it back into draft). 

If we need other WC post types to get put back into the correct status upon being restored, we can just amend the conditional at https://github.com/woocommerce/woocommerce/pull/28690/files#diff-3a21fb35ebe0a447670aa8b24c15b29d68d72ea3cc07dfc09b80657fa35f52e7R503
