### ISSUE TITLE
WC_Order::get_reason is not defined in 4.9.0.beta-1

### ISSUE THREAD

**Issue by senadir** [woocommerce/woocommerce#28668]
Our phpunit was running WC 4.9.0.beta-1 yesterday and tests broke, after further investigation, we found the reason to this error
```
Error: Call to undefined method WC_Order::get_reason()
```
We don't call this function directly but we do delete some orders in our unit test (to ensure draft orders are working well).

This is the full error 
https://gist.github.com/opr/c70ebe6f053c76564ad2ab4bb9bd0ae4

This is the file that is failing
https://github.com/woocommerce/woocommerce-gutenberg-products-block//blob/d1c0796361b4f6e94211336b59ac9fa44655bc1d/tests%2Fphp%2FDomain%2FServices%2FDeleteDraftOrders.php#L132

We couldn't reproduce this in 4.8.0

**Comment by juliaamosova** [comment]
Thanks for reporting @senadir! We will investigate further. Adding 4.9 milestone to it.

**Comment by vedanshujain** [comment]
Removing high priority and clearing milestone, since looks like this is caused by mocking behavior in blocks plugin. See https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3602

**Comment by juliaamosova** [comment]
Thanks @vedanshujain!
