### ISSUE TITLE
Able to apply email-restricted coupon to any order

### ISSUE THREAD

**Issue by DemonSkye** [woocommerce/woocommerce#28675]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ x ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When applying email-restricted coupons during cart / checkout, the coupon may be applied to the order even if the coupon does not match, only being removed during the payment step of checkout and throwing the "Sorry, it seems the coupon xxxx is not yours" error.  This is confusing to users because they saw the coupon as being applied successfully.   There needs to be changes made to the field which validates rather than only checking this during the "place order" workflow.

**Expected behavior**
If user attempts to add an email-bound coupon despite not being logged in with that email, they receive an error message that lets them understand they do not have that coupon available to them.

**Actual behavior**
Coupon is added to order and removed during place order workflow.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to 'wp-admin -> marketing'
2. Click on 'coupons'
3. Create an email-restricted coupon.
4. Login using an account with a different email
5. Add item to cart and apply coupon
6. Observe coupon is added in cart window.
7. Proceed to checkout
8.  Proceed through checkout
9.  Click place order
10. Notice coupon removal (should happen in either step 5 or 7 depending on which coupon treatment is used, cart or checkout respectively)

**Screenshots**
Added in cart:
![image](https://user-images.githubusercontent.com/10561297/103162283-9a1dcc80-47bc-11eb-9926-be552bbb88df.png)

On checkout screen
![image](https://user-images.githubusercontent.com/10561297/103162294-b91c5e80-47bc-11eb-8201-b57c81b93616.png)

After pressing place order:
![image](https://user-images.githubusercontent.com/10561297/103162304-d7825a00-47bc-11eb-90bb-54c598d41d25.png)

**Isolating the problem (mark completed items with an [x]):**
- [ x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x ] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @DemonSkye,

Thank you for reporting this issue. However, the behavior you are describing is expected. I agree that this is not ideal but there is no way for WooCommerce to know what is user's email on steps 5 or 7 (from the steps to reproduce the issue that you listed). WooCommerce does the email validation at the moment of the order being placed when the user's email is known. 

I am closing this as a non-bug. However, please feel free to comment back in case we missed something and we'd take another look.
