### ISSUE TITLE
use_block_editor_for_post_type breaks Product Short Description field

### ISSUE THREAD

**Issue by bowenac** [woocommerce/woocommerce#28686]
Have a site that is using this filter. After updating WP Core from 5.5.3 to 5.6 we can no longer edit the Product Short Description field unless it's on the text tab, when in visual it doesn't show any of the content, and you can't click into it. Removing this filter obviously removes gutenburg editor from products, and then the Product Short Description can be edited fine. Not sure if this is a WP Core bug, or if this can be fixed from WooCommerce. Not sure if WooCommerce has added support for Gutenburg, but it was working fine up to 5.5.3 so somewhere from 5.5.3 to 5.6 is when it caused this short description field to break.

```
function use_gutenburg_on_products( $use_block_editor, $post_type ) {
	if ( 'product' === $post_type ) {
		return true;
	}
	return $use_block_editor;
}
add_filter( 'use_block_editor_for_post_type', 'use_gutenburg_on_products', 10, 2 );
```

**Comment by rrennick** [comment]
@bowenac Thanks for reporting the issue. Could you let us know if you are still seeing the issue with WooCommerce 5.8.0? If so, could you provide screenshots from a WC version where this snippet was working and from the current version?
