### ISSUE TITLE
woocommerce/packages directory remains empty on 4.9.0-rc.1

### ISSUE THREAD

**Issue by szepeviktor** [woocommerce/woocommerce#28685]
4.9.0-rc.1 has been overwritten with packages added to `woocommerce/woocommerce`, so it contains 1+3 packages with is very bad.

v4.7.1 was properly empty:
https://github.com/woocommerce/woocommerce/tree/4.7.1/packages

Please read https://github.com/Automattic/jetpack/issues/18186
Thank you.

**Comment by juliaamosova** [comment]
Thanks for opening this issue @szepeviktor. I am tagging @vedanshujain who was involved in the conversation in https://github.com/Automattic/jetpack/issues/18186.

**Comment by vedanshujain** [comment]
Hi @szepeviktor We have release 4.9.0-rc.2 for WooCommerce, while package are still present in the tree, I believe this release should still fix your issue if it was working with 4.8.0 (I have used the same process as 4.8.0). Can you please check?

**Comment by szepeviktor** [comment]
Thank you.
https://github.com/woocommerce/woocommerce/tree/4.9.0-rc.2/packages

I leave the release process up to you.
Please consider a public release checklist, e.g. GitHub Wiki page.
All the best to you!
