### ISSUE TITLE
Taxes by Code does not factor in partial refunds

### ISSUE THREAD

**Issue by katinthehatsite** [woocommerce/woocommerce#28695]
**Prerequisites (mark completed items with an [x]):**
- [ x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When you look under WooCommerce > Reports > Taxes by Code and Taxes by date, you will see that these show the different result for the same day if there was a partial refund processed on the site. 

Example of Taxes by Code: 

<img width="1436" alt="Screen Shot 2020-12-30 at 3 06 04 PM" src="https://user-images.githubusercontent.com/25575134/103378531-820abd80-4ada-11eb-8813-108c3d4c543e.png">

Example of Taxes by Date:

<img width="1425" alt="Screen Shot 2020-12-30 at 3 07 38 PM" src="https://user-images.githubusercontent.com/25575134/103378590-b41c1f80-4ada-11eb-9dc0-0b90bbde62a6.png">

I have made a partial refund on the order made on December 30, 2020 but that refund does not seem to be reflected in "Taxes by Code":

<img width="1093" alt="Screen Shot 2020-12-30 at 3 09 01 PM" src="https://user-images.githubusercontent.com/25575134/103378649-eb8acc00-4ada-11eb-8c8f-92ca4d5d6d2c.png">
 
And the tax remains the same as the tax initially charged.

**Expected behavior**

I would expect the "Tax by code" to be adjusted once the partial refund was issued. 

**Actual behavior**

"Tax by code" report remained the same despite the partial refund.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create an order with tax, process it and partially refund
2. Check WooCommerce > Reports > Taxes by Code: the amount remains the same as was initially charged after partial refund

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @katinthehatsite,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/25311. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.

However, also please note that this is an issue that we won't be fixing. Please see [an explanation in the comment of 25311](https://github.com/woocommerce/woocommerce/issues/25311#issuecomment-568769054).
