### ISSUE TITLE
[GlobalStep - WooCommerce 4.9 RC1] Variable product misalignment on My Account + order subtotals misalignment during checkout 

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#28700]
## Bug Description:
 For "Twenty-Twenty" theme and "Twenty Twenty-One" theme, Variable product appears misaligned when viewed from My Account->Orders->View page.

## Environment:
Windows 10, macOS Mojave v10.14.6 (18G103)
Browser: Chrome(Version 87.0.4280.88 (64-bit))
                Firefox(Version 83.0)(64-bit)
                Safari: v13.1.1 (14609.2.9.1.3)
                
## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all required plugins.
1. Complete the Onboarding setup wizard 
1. Go to WooCommerce->Settings->Payments->Set to Cash on Delivery
1. Create or import Variable Products
1. Go to Front end and place an order for Variable Product
1. Click on "My Account" 
1. Click on "Orders"
1. Click on "View" for the order you have placed.
1. Observe that  Variable product appears misaligned when viewed from My Account->Orders->View page.

**Note**:
Observed for "Twenty-Twenty" theme, when order is viewed and when product is added to cart
and "Twenty Twenty-One" theme only when order is viewed.

## Actual Result:
 Variable product appears misaligned when viewed from My Account->Orders->View page.
 
## Expected Result:
  Variable product should appear properly when viewed from My Account->Orders->View page.

## Artifacts:
[#28700.zip](https://github.com/woocommerce/woocommerce/files/5757280/28700.zip)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Posting here the screenshot provided by @gglobalstep in the `Artifacts` section:

![#28700](https://user-images.githubusercontent.com/19143190/103703499-9f75d680-4f75-11eb-8b00-2b7af541aa4f.jpg)

**Comment by juliaamosova** [comment]
Thanks for reporting the issue @gglobalstep!

I can replicate it on my end in both 2020 and 2021 themes. Below is what I am seeing:

**2021 - v 1.0 (same as reported by @gglobalstep):**

![Screen Shot 2021-01-05 at 4 49 24 PM](https://user-images.githubusercontent.com/19143190/103704607-8d953300-4f77-11eb-92be-4bdf1b43f9dc.png)

**2021 - v 1.1 (latest) - note how the price is now misaligned as well + `subtotal`, `payment method` and `total` fields are now centered:**

![Screen Shot 2021-01-05 at 4 50 16 PM](https://user-images.githubusercontent.com/19143190/103704657-a30a5d00-4f77-11eb-828b-3402bedde6e2.png)

**2020:**

![Screen Shot 2021-01-05 at 4 50 52 PM](https://user-images.githubusercontent.com/19143190/103704693-b0274c00-4f77-11eb-8833-26d0206643fe.png)

**Storefront (everything looks good):**

![Screen Shot 2021-01-05 at 4 51 29 PM](https://user-images.githubusercontent.com/19143190/103704720-bb7a7780-4f77-11eb-9e12-09f2d539f90e.png)

**Comment by juliaamosova** [comment]
There is a misalignment on the checkout page as well in the 2021 theme - note how everything is centered down the products. This is in WC 4.9 RC2 pre-release:

<img width="1429" alt="Screen Shot 2021-01-06 at 7 27 08 PM" src="https://user-images.githubusercontent.com/19143190/103835869-63b23e00-5055-11eb-948a-08e75b253540.png">

**Comment by juliaamosova** [comment]
Also, on the order confirmation page:

<img width="943" alt="Screen Shot 2021-01-06 at 7 42 25 PM" src="https://user-images.githubusercontent.com/19143190/103836538-61e97a00-5057-11eb-81e8-a983b910b8f7.png">

**Comment by vedanshujain** [comment]
@juliaamosova @gglobalstep I am not able to reproduce this one, everything seems fine on my end, see:

<img width="1445" alt="Screenshot 2021-01-07 at 6 54 45 PM" src="https://user-images.githubusercontent.com/7571618/103897717-f61c1580-5119-11eb-8917-b33e4f170a74.png">


Do you see any error on console when this happens? Other screens also works fine for me, perhaps I am missing something?

**Comment by juliaamosova** [comment]
@vedanshujain are you using the latest version of the 2021 theme? The latest currently is 1.1.

**Comment by juliaamosova** [comment]
We decided to address this in WooCommerce 5.0. Changing the milestone.
