### ISSUE TITLE
Products are being discounted without active coupon or active sale

### ISSUE THREAD

**Issue by toya4354** [woocommerce/woocommerce#28714]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by toya4354** [comment]
WooCommerce is still showing a product that is discounted but there is no active coupon code or sale.

**Comment by juliaamosova** [comment]
Hi @toya4354,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Comment by toya4354** [comment]
Describe the bug
Coupon code is showing up but there is no active coupon code.

Expected behavior
Once the code expired from that particular product, it shouldn't allow it to be discounted any longer. Not to mention, there is no coupon code.

Actual behavior
The coupon code shows up when particular items are selected although the code is expired and there is no coupon code.

Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)
Steps to reproduce the bug:

There are no steps to reproduce it. If you had the coupon code, it allows for the discount. Since there is no active coupon code, then it shouldn't be discounting the products.
