### ISSUE TITLE
CSS: Please include page ID class in the classlist that appears within the body tag. 

### ISSUE THREAD

**Issue by nagpai** [woocommerce/woocommerce#28724]
## Is your feature request related to a problem? Please describe.
The page id that appears in the classlist of the body tag in any page or post html code, helps support team a long way in targetting CSS only to that specific page or post. 

The Shop page in Storefront, due to some reason has page ID missing in the list of class. It does not even have a specific class like maybe `woocommerce-shop-page`.

## Describe the solution you'd like

Have the page ID and a special class for the Shop page which will help us add CSS rules specific to that page. 

## Describe alternatives you've considered
Used a not rule which turned out  convoluted, and I am not sure if it works correctly

> body:not(.post-type-archive-product) #woocommerce_product_categories-7 {
    display: none;
}

**Comment by juliaamosova** [comment]
Just moved this issue from the Storefront repository to Core as per the comments above.

**Comment by nerrad** [comment]
Ahh thanks Julia, I guess I assumed it had already been done  (bad assumption!)

**Comment by juliaamosova** [comment]
No worries at all @nerrad! If anything, I should thank you for closing it as it generated a notice for me to take action on it and move it to Core repo as it wasn't done before.

**Comment by rrennick** [comment]
> The Shop page in Storefront, due to some reason has page ID missing in the list of class.

This comes from WP core functionality where a page is used as a permalink to other content. 
- Use a default WP theme
- Create a `News` page
- view the page and note the presence of the `page-id-999` class
- Go to Settings -> Reading
- Set the News page as your page for posts
- view the page and note the absence of the `page-id-999` class

The WP Query object removes its `is_page` status when it is updated to retrieve other post objects. While it would be possible to custom code adding the page id class in those situations, I don't feel this is something that WC core should be doing.

**Comment by nielslange** [comment]
> The WP Query object removes its is_page status when it is updated to retrieve other post objects. While it would be possible to custom code adding the page id class in those situations, I don't feel this is something that WC core should be doing.

Thanks for your explanation, @rrennick. You mentioned that the blog posts page has no page ID either, which is correct. However, the blog posts page adds the body class `blog` which can be used to target this particular page. In case of the WooCommerce shopping page, there's no unique body class available. This makes it impossible to target the shopping page without adding custom code to add the wanted body class. While adding the page ID might not be the best option for the shop page, wouldn't it be an option to add the body class `woocommerce-shop` similar the existing body classes `woocommerce-cart` and `woocommerce-checkout`?

**Comment by claudiosanches** [comment]
I agree that `woocommerce-shop` is a nice addition and will help style this page.
