### ISSUE TITLE
Cannot edit product variations from 4.5.2 to 4.8.0

### ISSUE THREAD

**Issue by dorlyjunior** [woocommerce/woocommerce#28739]
After the 4.8.0 update I can not edit the product variations. Actually, this error started after 4.5.2 and was reported here:

https://wordpress.org/support/topic/cannot-edit-product-variations-after-upgrade-to-4-5-2/

But no solution was presented there.

The following error happens on the Chrome console:

meta-boxes-product-variation.min.js?ver=4.8.0:1 Uncaught TypeError: d(…).serializeJSON is not a function
at Object.get_variations_fields (meta-boxes-product-variation.min.js?ver=4.8.0.:1)
at Object.save_changes (meta-boxes-product-variation.min.js?ver=4.8.0:1)
at HTMLButtonElement.save_variations (meta-boxes-product-variation.min.js?ver=4.8.0:1)

I had to go back to the 4.5.1 version to be able to edit the variations.

From my part, I didn't change a thing, no plugins added, no change on the environment, just the regular updates. Still, I can only edit the variations on 4.5.1. Any ideas?

**Comment by juliaamosova** [comment]
Hi @dorlyjunior,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

In addition to that, can you please test with WooCommerce 4.8 which is the latest version to see if the issue is still present in it for you?

**Comment by dorlyjunior** [comment]
Here we go:

**Prerequisites (mark completed items with an [x]):**
- [ x ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Can't edit a product variation.

**Expected behavior**
Be able to edit the variation data.

**Actual behavior**
This error happens:

meta-boxes-product-variation.min.js?ver=4.8.0:1 Uncaught TypeError: d(…).serializeJSON is not a function
at Object.get_variations_fields (meta-boxes-product-variation.min.js?ver=4.8.0.:1)
at Object.save_changes (meta-boxes-product-variation.min.js?ver=4.8.0:1)
at HTMLButtonElement.save_variations (meta-boxes-product-variation.min.js?ver=4.8.0:1)

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create a product.
2. Create a variation for the product.
3. Try to edit anything.
4. Error happens.

**Isolating the problem (mark completed items with an [x]):**
- [ x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x ] I can reproduce this bug consistently using the steps above.

Currently I'm using the 4.5.1 version to be able to edit the variations.

**Comment by zhongruige** [comment]
Hi @dorlyjunior,

Thank you for providing that information. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

1. I created a new product, set it to a Variable Product, and added a Color attribute:

<img width="1196" alt="Screen Shot 2021-01-28 at 4 01 47 PM" src="https://user-images.githubusercontent.com/71906536/106209948-2f78fb80-6183-11eb-89d4-80f1f502fcc7.png">

2. Next I created variations on the product:

<img width="1194" alt="Screen Shot 2021-01-28 at 4 02 53 PM" src="https://user-images.githubusercontent.com/71906536/106210093-6818d500-6183-11eb-9110-4d11c226b3ea.png">

3. I was able to expand the section below the variation and add in and save details, such as the price, SKU and weight:

<img width="1196" alt="Screen Shot 2021-01-28 at 4 04 09 PM" src="https://user-images.githubusercontent.com/71906536/106210147-7e269580-6183-11eb-82fb-ccbf4b2d6ad7.png">

4. After editing those, I was able to save the changes:

<img width="929" alt="Screen Shot 2021-01-28 at 4 13 47 PM" src="https://user-images.githubusercontent.com/71906536/106210638-6e5b8100-6184-11eb-905a-6089a881ef4c.png">

5. I also verified this was saved and was showing to the storefront:

<img width="874" alt="Screen Shot 2021-01-28 at 4 18 35 PM" src="https://user-images.githubusercontent.com/71906536/106210692-87fcc880-6184-11eb-9ffe-c7a5846d7ffc.png">

Please provide us with more details about the issue which may help us to evaluate it further. For example, if I missed any steps above when reproducing the issue.

I tested the above on the following:
* WordPress 5.6
* WooCommerce 4.92
* Storefront theme

It will be great if you could share your current System Status Report. You can get it by navigating to the `WooCommerce / Status` section of your site. Once there, click on the `Get system report` button and then copy it by clicking on the `Copy for support` button. Then paste it here in a comment. 

Thank you!

**Comment by dorlyjunior** [comment]
@zhongruige, awesome!

I updated to the latest version of woocommerce, checked my plugins and I was able to edit the variations again.

Thank you so much guys!

**Comment by zhongruige** [comment]
> @zhongruige, awesome!
> 
> I updated to the latest version of woocommerce, checked my plugins and I was able to edit the variations again.
> 
> Thank you so much guys!

That's great to hear! Glad to hear that's working now :)
