### ISSUE TITLE
API Orders _fields only returns listed fields

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce#28743]
I found this testing #28731 / smoke testing 4.9 RC2.

### Steps to reproduce

Use `/wp-json/wc/v3/orders/?_fields=date_created_gmt`

### Result set

```
[
  {
    "date_created_gmt": "2020-10-28T03:00:00"
  },
  {
    "date_created_gmt": "2020-10-28T03:00:00"
  },
  {
    "date_created_gmt": "2020-10-28T03:00:00"
  },
  {
    "date_created_gmt": "2020-10-28T03:00:00"
  },
  {
    "date_created_gmt": "2020-10-28T03:00:00"
  },
  {
    "date_created_gmt": "2020-10-28T02:00:00"
  },
  {
    "date_created_gmt": "2020-10-28T02:00:00"
  },
  {
    "date_created_gmt": "2020-10-28T02:00:00"
  },
  {
    "date_created_gmt": "2020-10-28T02:00:00"
  },
  {
    "date_created_gmt": "2020-10-28T02:00:00"
  }
]
```

### Expected

At a minimum, the order ID should be included in the results.

**Comment by vedanshujain** [comment]
This is not a new behavior but something that is there from the start. While I agree with the situation I am not sure if we should implement it as this could break backward compatibility. Anyone requiring ID field can anyways specify it in params like so `_fileds=id,date_created_gmt`.
