### ISSUE TITLE
Removing item from order doesn't restore stock

### ISSUE THREAD

**Issue by negapo** [woocommerce/woocommerce#28756]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
In the backend admin panel, if we remove an item from an order (where the stock for that item as already being reduced) it does not restore the stock.

**Expected behavior**
The stock for the item should be restore if it has previously been reduced.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to the front end, create an order, checkout.
2. Go to the admin panel and change the status to "processing". Stock for the items has now been reduced.
3. Remove an item from the order.
4. A log will appear that the item was removed but no stock is restored.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WP 5.6, Woo 4.8.0

</details>

**Comment by juliaamosova** [comment]
Hi @negapo,

Thank you for reporting the issue. Similar answer to what I provided in another report of yours: https://github.com/woocommerce/woocommerce/issues/28772. 

It had already been reported in several other issues. We have a fix for it in place https://github.com/woocommerce/woocommerce/pull/28620 - it will be included in WooCommerce 4.9 which is planned to be released on Tuesday, January 12th. 

If you'd like to test with us, you can get a pre-release version (WC 4.9 RC2) here: https://github.com/woocommerce/woocommerce/releases/tag/4.9.0-rc.2
