### ISSUE TITLE
Coupons don't get eliminated after emptying cart  WC 4.8 WP 5.6

### ISSUE THREAD

**Issue by Danielspain22** [woocommerce/woocommerce#28764]
**Prerequisites (mark completed items with an [x]):**
- [ x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Coupons don't get eliminated after emptying cart, coupons applied before remains active for a new cart(in the same session)

**Expected behavior**
Coupons should be eliminated from cart when you empty all the products there.

**Actual behavior**

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**

Create any coupon that applies, for example, a 50% discount applicable to any products. Log in as a customer, choose and add any product and apply the coupon created. Then the coupon gets applied and creates the correct discount. After that, click on the "X" to remove the added -and only- product. At this moment the cart gets emptied. But, if I add later ANOTHER product, the discount coupon is still active and makes a discount in the current cart. When emptying a previous shopping cart, the applied coupons should also be removed. If I remove all the sessions and carts from the admin, the coupon doesn't remains, but if is the user who empties their products and add another ones, the coupon is still there and active.

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WC 5.6 / Woocommerce 4.8 / PHP 7.3 it happens on all themes i've tested.
Thanks in advance!

**Comment by juliaamosova** [comment]
Hi @Danielspain22,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end using WooCommerce 4.8. Please see the gif below:

http://g.recordit.co/cBSPJABG7N.gif

I agree with you that the coupon should be removed from the cart upon removing the product from the cart. 

We’re going to solve this bug as soon as possible.

**Comment by gglobalstep** [comment]
This issue relates to https://github.com/woocommerce/woocommerce/issues/27060

**Comment by roykho** [comment]
Hi @Danielspain22 - Thanks for raising this issue. I've spoke with the core team about this and we've concluded it is working as designed. We see it as a convenience feature for customers so they don't have to re-apply coupons just because they emptied their cart.

From looking at your description, it seems what you're really wanting is a product specific coupon. This way if they add another product to the cart, the coupon will not apply as it is not stated in the coupon. Please try using that method to get around what it seems you're trying to do based on your description. Thanks!
