### ISSUE TITLE
Updating a Failed order reduces stock

### ISSUE THREAD

**Issue by negapo** [woocommerce/woocommerce#28772]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
If you click "update" on an order with the "failed" status it reduces the stock of the items in the order. If you then cancel the order it doesn't  restore the stock.

**Expected behavior**
Don't reduce stock on as "failed" order. If the expected behavior is to reduce stock on an update then we should restore the stock when the order is cancelled.

**Actual behavior**
Stock is reduced on "update" and then not restored on the status change to "cancelled".

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create a new order.
2. Set the order status to "failed" or just try to pay it with incorrect credit card data.
3. Open the failed order in the admin panel.
4. Click "update", stock will be reduced for the items.
5. Change the order status to "cancelled", stock will not be restored.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
WP 5.6
Woo 4.8.0
</details>

Stock management at the admin / API level is a mess for years now, every attempt to correct it brings new problems, this strategy of patching every little bug is going nowhere, and worse, the dev team is fixed on waiting for the next release to take on this little bugs and we can go for months with stores getting their stocks out of sync. I know its tricky to get this right but we need a macro view / strategy on how to manage stock on the admin side.

My two cents: Stock should be managed depending on the order status and should be committed on item addition/removing like in the old releases (with an option to override it) AND again checked on order updates. Example:

We should drop the '_order_stock_reduced' meta tag and look on an order item basis.

**Adding an item to an order**
- Check the order status 
     - If Pending payment, Failed, Cancelled or any other Non-Managing-Stock Status don't commit to stock.
     - If On-Hold, Processing or Completed  or any other Managing-Stock Status then commit to stock (we can have an option to override the stock behavior, but that should be flagged with a meta tag field).
- Flag the items that were reduced with the "_reduced_stock" meta tag.

**Removing an item from an order**
- Only check for the item meta tag "_reduced_stock", ignore the order status, restore the stock if the flag is set (we can have an option to override the stock commitment).

**Saving an Order**
Look at the status, if its a Managing-Stock Status then look at the individual items and look for the "_reduced_stock" meta tag, if its not there (and the override meta tag is also not present) then reduce the stock. If its a Non-Managing-Stock status then look for the "_reduced_stock" meta tag, if present  (and the override meta tag is also not present) then restore the stock for the items.

If an order is trashed do nothing, just trash the order.
I may have missed something important here, this is just an attempt at creating soem heuristics for stock management.

**Comment by juliaamosova** [comment]
Hi @negapo,

Thank you for reporting the issue. It had already been reported in several other issues, however. We have a fix for it in place https://github.com/woocommerce/woocommerce/pull/28620 - it will be included in WooCommerce 4.9 which is planned to be released on Tuesday, January 12th. 

If you'd like to test with us, you can get a pre-release version (WC 4.9 RC2) here: https://github.com/woocommerce/woocommerce/releases/tag/4.9.0-rc.2
