### ISSUE TITLE
Composer install error when using custom vendor-dir config in composer.json

### ISSUE THREAD

**Issue by lytesaber** [woocommerce/woocommerce#28775]
Description:
When configuring composer.json with custom vendor-dir configuration for example "content/vendor" composer install throws the following error when generating autoload files:

An error occurred while generating the autoloader files:
The project's composer.json or composer environment set a non-default vendor directory.
The default composer vendor directory must be used.

This looks like a issue due to https://github.com/Automattic/jetpack-autoloader Jetpack autoloader requiring the default vendor directory path. Is there any specific reason why this is the case?

Expected behavior:
Composer install generates autoload files without error.

Actual behavior:
Error is thrown when generating autoload files.

Steps to reproduce the bug:
1. Set "vendor-dir": "content/vendor" within config section of composer.json
2. Add "woocommerce/woocommerce": "4.8.0" as composer require
3. Run composer install via CLI

**Screenshots**
![image (2)](https://user-images.githubusercontent.com/16328255/104141407-45a45f00-5402-11eb-9e7a-d939900d9d25.png)
![image (3)](https://user-images.githubusercontent.com/16328255/104141417-61a80080-5402-11eb-8c06-1b3309bd5f1f.png)

**Comment by rkaiser0324** [comment]
@lytesaber if you're only using composer to deploy woocommerce and don't need to use the jetpack-autoloader directly, you can [exclude it from the classmap](https://getcomposer.org/doc/04-schema.md#exclude-files-from-classmaps) to get unblocked:

```
    "autoload": {
        "exclude-from-classmap": [
            "content/vendor/automattic/jetpack-autoloader"
        ]
    },
```

**Comment by itmatters4u** [comment]
Same issue here, this is breaking our managed development environments for WooCommerce WordPress sites.

**Comment by ObliviousHarmony** [comment]
This seems to be more of an issue with the `automattic/jetpack-autoloader` package. [I've submitted a feature request](https://github.com/Automattic/jetpack/issues/18478) and will look at implementing it. There unfortunately isn't really anything I can suggest as the only thing that would bypass it (`--no-plugins`) would also likely disable the `composer-installer` plugin that makes this orchestration even possible in the first place.

**Comment by rkaiser0324** [comment]
If you don't need to access the package directly (i.e., you're just using composer as a deployment tool), you can work around this by excluding the package in your `composer.json`:

```
    ...
    "replace": {
        "automattic/jetpack-autoloader": "*"
    },
    ...
```

**Comment by ObliviousHarmony** [comment]
I wanted to highlight that I've [fixed this bug in the Jetpack Autoloader](https://github.com/Automattic/jetpack/pull/18683). I can't promise that the updated package will make it into the next release but I did want to give an update.
