### ISSUE TITLE
2021 enhancements

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#28789]
Some remaining defects after the previous work on 2021 compat:

Product & Catalog Pages: The sale badge should likely have a color based off the CSS vars.
Everywhere: There are many notices that are white boxes with a green bar at the top and green buttons, regardless of theme colors. Examples include empty order & download list my-account pages, as well as empty carts.

Also, new v1.1 of 2021 has been released, so we might check the compatibility, too.

**Comment by kmanijak** [comment]
hey @peterfabian, do you think it's still something worth addressing or we can close this one?

**Comment by kmanijak** [comment]
I decided to close this one as it's been raised internally and not worked on for 3 years. Also, the description is pretty broad so in case there's a need we can always open the issue for a specific problem mentioned in this issue.

The closed issue can be still commented on 🙌
