### ISSUE TITLE
Keep minor and major version announcements consistent

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#28806]
On the [WooCommerce 4.9.0 release post](https://developer.woocommerce.com/2021/01/12/woocommerce-4-9-0-released/) we can read:

> This is a **minor release**, which means everything is backward compatible with the previous version.

But when updating from 4.8.0 to 4.9.0 we get this warning on WP Admin:

![image](https://user-images.githubusercontent.com/6853605/104451441-72d74580-5599-11eb-927c-36a3a255eea6.png)

I understand this is triggered probably by the fact the second part of the version number changes, and it's actually not a big deal, but It might get confusing for some users.

**Comment by tammullen** [comment]
Hi @webdados 

Thank you for submitting the issue. However, I can’t reproduce it. Everything is working as expected on my end. 

I don't see this warning when updating from 4.8.0 to 4.9.0 on Plugins > Installed Plugins. 
![Screen Recording 2021-01-13 at 12 31 46 2021-01-13 12_33_38](https://user-images.githubusercontent.com/24649833/104453706-b8e1d880-559c-11eb-9e83-0bc5d29ad04e.gif)


I also don't see this warning when updating from 4.8.0 to 4.9.0 on Dashboard > Updates.
 
![Screen Recording 2021-01-13 at 12 35 38 2021-01-13 12_39_07](https://user-images.githubusercontent.com/24649833/104453715-bb443280-559c-11eb-9e02-401a61c79aef.gif)
​
Please provide us with more details about where you are seeing this warning which may help us to evaluate it further. 
​

**Comment by webdados** [comment]
I think this happens if you also have installed and activated a 3rd party plugin that doesn't announce compatibility with the new version.

**Comment by Danielspain22** [comment]
I can confirm what webdados says. It happened to me too,and the culprit was a plugin(who works ok with 4.9, simply don't have this info confirmed).

**Comment by tammullen** [comment]
Thanks @webdados and @Danielspain22 for the extra information, I can now reproduce it.

![Screenshot 2021-01-14 at 22 31 36](https://user-images.githubusercontent.com/24649833/104657479-fb98d300-56b8-11eb-9f8c-456f07f4b3a5.png)
![Screenshot_2021-01-14_at_22_31_49](https://user-images.githubusercontent.com/24649833/104657483-fd629680-56b8-11eb-9591-3060c69c928d.png)

We’re going to solve this bug as soon as possible. Stay tuned for updates.
