### ISSUE TITLE
Refund Reason Length Should Be Limited

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce#28810]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
With some gateways, eg. Stripe, if the refund reason is over 500 characters it refunds an error but still, the order is marked as Refunded.

**Expected behavior**
The refund reason should be limited to 500 characters and prevent the refund if it's more.

**Actual behavior**
The order is marked as refunded, no error is returned, and the refund does not really go through.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Refund an order with a reason of 500+ characters on Stripe.
2. See error

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

p1610605796016700-slack-C07418EA0

**Comment by aheckler** [comment]
I reported this to the Stripe repo a few days ago:

https://github.com/woocommerce/woocommerce-gateway-stripe/issues/1446

And submitted a PR for a fix here:

https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1447

**Comment by tammullen** [comment]
Thanks @SiR-DanieL for reporting this, we really appreciate your help!

Sounds like from looking at the related issues in other repos the urgent need is specific to Stripe and it will be sufficient to take care of it in the WooCommerce Stripe Payment Gateway for now.

I'm going to mark it as an enhancement for considering doing it in core for all payment types.

**Comment by bgrgicak** [comment]
This issue was fixed in the [WooCommerce Stripe Payment Gateway](https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1447).

**Comment by rrennick** [comment]
> This issue was fixed in the https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1447.

Closing the issue.
