### ISSUE TITLE
Product field wont be saved if we input the field programatically using javascript

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce#28829]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
On product edit page (variable product):
https://xxx/wp-admin/post.php?post=xxx&action=edit

if we automatically update the value of field using jquery for example using:
jQuery('input#variable_sku0').val('SKU-EXAMPLE');

And click the submit button manually. the value wont be saved. eventhough the post parameter is correct.

**Expected behavior**
Sku value saved correctly

**Actual behavior**
It wont save value that updated programmatically using javascript

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

1. On product edit page (variable product):
https://xxx/wp-admin/post.php?post=xxx&action=edit

2. if we automatically update the value of variation product field using jquery:
jQuery('input#variable_sku0').val('SKU-EXAMPLE');

3. And click the submit button manually. the value wont be saved. eventhough the post parameter is correct.

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by kevinruscoe** [comment]
How about if you fire a `blur()` event on it after setting the value?
