### ISSUE TITLE
add_action always return -1

### ISSUE THREAD

**Issue by iyezhou** [woocommerce/woocommerce#28830]
```
add_action( 'woocommerce_api_wc_gateway_test', 'check_response');
function check_response() {
    echo 'test';
    return 'test';
}
```
when call `https://loaclhost/index.php/wc-api/WC_Gateway_Test`, always return httpCode: 200, response body: -1

**Comment by barryhughes** [comment]
Hi @iyezhou,

When using the `woocommerce_api_*` dynamic hook in this way, the status code and any data you wish to return is something you need to take care of yourself, for instance by adding something like `status_header( 400 );` within your callback.

We don't provide support here on GitHub, but if you still think there is a problem or bug then it would be great to have a little more insight into what you are trying to do, and what you expect (bear in mind, too, that this approach mostly exists for the benefit of payment gateways).
