### ISSUE TITLE
Display Issue: Columns on 'All product page' should become responsive at a higher breakpoint

### ISSUE THREAD

**Issue by anant1811** [woocommerce/woocommerce#28832]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

Columns on All product admin page becomes responsive at 782 px, so, on screen resolutions such as at 800 px where there's no enough horizontal space, the columns look like this:
![https://d.pr/i/QTN2ul](https://d.pr/i/QTN2ul+) 
Full Size: https://d.pr/i/QTN2ul

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to Products > All Products 
2. Set browser width to 800 px, check the display of columns. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by mfs-mindsize** [comment]
Hi @anant1811 - I'm curious, what plugin is adding the last column on the right? I'm looking a fresh new install of WC (on my local so there's no sales, etc.) and I don't see that column.

**Comment by tammullen** [comment]
Hi @anant1811 

Thanks for raising this.

![Screenshot 2021-02-12 at 14 33 49](https://user-images.githubusercontent.com/24649833/107781523-e3f84d00-6d3f-11eb-9f2d-18d451e107dc.png)

When I use 800px width I can see what you are referring to but it is less pronounced as I have fewer columns. I think your extra columns might be coming from other extensions?

Looking at this related issue https://github.com/woocommerce/woocommerce/issues/18133 and bearing in mind users can select the columns they want to view in screen options and in general these tables are controlled by WP core I think we can mark this as `won't fix` for now.
