### ISSUE TITLE
Twenty Twenty-One: Issue with the content wrapper

### ISSUE THREAD

**Issue by dianeco** [woocommerce/woocommerce#28868]
For the Twenty Twenty-One theme, the #primary and #main elements are duplicated on the WooCommerce pages:

![woocommerce-wrapper](https://user-images.githubusercontent.com/44895380/105209126-c58ca080-5b49-11eb-9730-d65c8f7ab2ee.PNG)

The following lines are not necessary: https://github.com/woocommerce/woocommerce/blob/eb62ed1c9fb354e87b476f592c8b68a63e58a861/includes/theme-support/class-wc-twenty-twenty-one.php#L56-L67

**Comment by rrennick** [comment]
Hi @dianeco,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

Screenshot of shop page markup:
<img width="394" alt="Screen Shot 2021-01-21 at 5 08 37 PM" src="https://user-images.githubusercontent.com/343847/105412668-6a22e700-5c0b-11eb-9f6c-88c53d0deabd.png">


We’re going to solve this bug as soon as possible. Stay tuned for updates.

**Comment by mfs-mindsize** [comment]
@rrennick is the issue unnecessary markup added by the *_wrapper() + _end(), or that the section id is not unique? The class duplication isn't wrong per se.

**Comment by hsingyuc** [comment]
I'll try this one 🙂
