### ISSUE TITLE
Weird characters in email subject (Redsys payment method)

### ISSUE THREAD

**Issue by wolframtheta** [woocommerce/woocommerce#28879]
Hi everyone,

I'm using this plugin [Redsys Gateway Light](https://wordpress.org/plugins/woo-redsys-gateway-light/) and searching for that plugin I didn't find anything about my problem. So on, I decided to ask you if somebody knows about it.
 
**Describe the bug**
with Resys payment method and all order emails that me or the client would have received they have a curious string as a subject.

The subject it's filled up with weird characters like:
>º z{{ ��Ú&z�«u��� _�� jg—j���§lvƝ�ƫ��¬jÇZvƬ
騲������۩y؝��Ϯ�ޞ

and so on..

The other parts of the email were correctly seen it so I thought that the problem wast with the character-set in the subject, but it is already set to UTF-8, so then I am lost and without any idea to solve this.
 
**To Reproduce (locally)**
1. Configure WooCommerce Redsys Gateway Light properly
2. Add a product with price
3. Buy this product with all the necessary steps with that plugin
4. See your email response from wordpress with the Processed Order.
 
**Screenshots**
 
**Expected behavior**
[https://imgur.com/a/S9Vr2DM](https://imgur.com/a/S9Vr2DM)
 
**Isolating the problem (mark completed items with an [x]):**
 
* [ ]  I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
* [ ]  This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
* [X]  I can reproduce this bug consistently using the steps above.
 
**WordPress Environment**

Dirección de WordPress (URL): |   | https://www.probens.org
-- | -- | --
Dirección del sitio (URL): |   | https://www.probens.org
Versión de WooCommerce: |   | 4.8.0
Paquete de la REST API de WooCommerce: |   | 4.8.0 /home/www/probens.org/html/wp-content/plugins/woocommerce/includes
Paquete WooCommerce Blocks: |   | 3.8.1 /home/www/probens.org/html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/
Paquete del programador de acciones: |   | 3.1.6 /home/www/probens.org/html/wp-content/plugins/woocommerce/packages/action-scheduler
Paquete de WooCommerce Admin: |   | 1.7.3 /home/www/probens.org/html/wp-content/plugins/woocommerce/packages/woocommerce-admin
Directorio de registros con permiso de escritura: |   | /home/www/probens.org/html/wp-content/uploads/wc-logs/
Versión de WordPress: |   | 5.6
WordPress multisitio: |   | –
Límite de memoria de WordPress: |   | 256 MB
Modo de depuración de WordPress: |   | –
Cron de WordPress: |   |  
Idioma: |   | es_ES
Caché externa de objetos: |   | –

Any help is welcome!

**Comment by wolframtheta** [comment]
Sorry for that, I was looking for some template but I didn't find it. @lsinger

**Comment by wolframtheta** [comment]
> Hi @wolframtheta,
> 
> Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further. 
> 
> Specifically it sounds like you're using a plugin for the Redsys payment gateway. Have you reached out the plugin developers yet, and if so, what was the result of the exchange? Please add any details that might help us evaluate this issue better. 
> 
> **Describe the bug**
> A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Isolating the problem (mark completed items with an [x]):**
> - [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
> - [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
> - [ ] I can reproduce this bug consistently using the steps above.
> 
> **WordPress Environment**
> <details>
> ```
> Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
> ```
> </details>
> 

Sorry for that, I was looking for a template but I did not see it. I've made this changes!

**Comment by lsinger** [comment]
Hi @wolframtheta,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

The issue you are having seems to be caused by the 3rd party plugin {name of the plugin}. 

Please contact the author of the plugin directly for further help.
