### ISSUE TITLE
No shipping options were found for AE 09603

### ISSUE THREAD

**Issue by kdimedia** [woocommerce/woocommerce#28889]
Video clip of the issue
https://www.loom.com/share/43e91350b90b457196ac5c210861c3ef
Appears to find shipping info as first class usps mail but when the price bumps it up to priority usps mail the error comes. 

	<Number>80040B18</Number>
	<Description>An error has occurred with the service.  Please contact the system administrator, or try again.</Description>
	<Source>USPSCom::DoAuth</Source>
</Error> (calculate_shipping)
01-19-2021 @ 21:11:04 - Error: Unexpected USPS Response: <?xml version="1.0" encoding="UTF-8"?>
<Error>
	<Number>80040B18</Number>
	<Description>An error has occurred with the service.  Please contact the system administrator, or try again.</Description>
	<Source>USPSCom::DoAuth</Source>
</Error> (calculate_shipping)

`
### WordPress Environment ###

WordPress address (URL): https://1320video.com
Site address (URL): https://1320video.com
WC Version: 4.9.1
REST API Version: ✔ 4.9.1
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.8.3
Log Directory Writable: ✔
WP Version: ❌ 5.5.2 - There is a newer version of WordPress available (5.6)
WP Multisite: –
WP Memory Limit: 300 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Flywheel/5.1.0
PHP Version: 7.4.13
PHP Post Max Size: 300 MB
PHP Time Limit: 180
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.7.25-google
Max Upload Size: 300 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.9.1
WC Database Prefix: wp_
Total Database Size: 1670.84MB
Database Data Size: 1131.17MB
Database Index Size: 539.67MB
wp_woocommerce_sessions: Data: 7.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.14MB + Index: 0.22MB + Engine InnoDB
wp_woocommerce_order_items: Data: 5.52MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 78.61MB + Index: 29.09MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 3.02MB + Index: 4.72MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 3.02MB + Index: 3.03MB + Engine InnoDB
wp_adsforwp_stats: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 1.52MB + Index: 0.88MB + Engine InnoDB
wp_comments: Data: 33.56MB + Index: 23.09MB + Engine InnoDB
wp_et_bloom_stats: Data: 73.59MB + Index: 0.00MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 0.27MB + Index: 0.06MB + Engine InnoDB
wp_gf_entry_meta: Data: 1.52MB + Index: 0.53MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.17MB + Index: 0.06MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_itsec_bans: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_dashboard_events: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_itsec_distributed_storage: Data: 21.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_fingerprints: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_geolocation_cache: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_itsec_lockouts: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_itsec_logs: Data: 3.02MB + Index: 0.44MB + Engine InnoDB
wp_itsec_mutexes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_opaque_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_itsec_temp: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_itsec_user_groups: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_nobuna_backups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nobuna_downloads: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_nobuna_products: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 220.30MB + Index: 100.81MB + Engine InnoDB
wp_postmeta: Data: 516.98MB + Index: 284.72MB + Engine InnoDB
wp_posts: Data: 77.56MB + Index: 18.80MB + Engine InnoDB
wp_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_rio_process_queue: Data: 1.02MB + Index: 0.66MB + Engine InnoDB
wp_taxjar_record_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.47MB + Index: 0.41MB + Engine InnoDB
wp_term_relationships: Data: 2.52MB + Index: 2.50MB + Engine InnoDB
wp_term_taxonomy: Data: 1.52MB + Index: 0.50MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 32.56MB + Index: 30.05MB + Engine InnoDB
wp_users: Data: 1.52MB + Index: 2.33MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 3.52MB + Index: 4.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.16MB + Index: 0.13MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.17MB + Index: 0.22MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 5.52MB + Index: 7.06MB + Engine InnoDB
wp_wc_order_stats: Data: 4.52MB + Index: 5.55MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.11MB + Index: 0.13MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.17MB + Index: 0.33MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfstatus: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 22.55MB + Index: 15.53MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.09MB + Index: 0.09MB + Engine InnoDB
wp_yoast_prominent_words: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 1.22MB + Index: 0.42MB + Engine InnoDB
wp_yoast_seo_meta: Data: 2.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

adsforwp: 2
ajde_events: 17
attachment: 3630
custom_css: 2
et_pb_layout: 39
jetpack_migration: 2
jp_img_sitemap: 2
jp_img_sitemap_index: 1
jp_sitemap: 1
jp_sitemap_master: 1
jp_vid_sitemap: 1
nav_menu_item: 23
oembed_cache: 61
page: 50
post: 2116
postman_sent_mail: 2500
product: 258
product_variation: 1057
revision: 273
rp4wp_link: 1077
shop_coupon: 162
shop_order: 81571
shop_order_refund: 414
sp_wps_shortcodes: 4
sp_wpsp_shortcodes: 3
wcps: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (37) ###

Gravity Forms: by Gravity Forms – 2.4.19.4
Divi Blog Extras: by Elicus – 2.5.4
Angell EYE Updater: by Angell EYE – 2.0.16
Anything Slider - Divi: by munirkamal – 1.5
Bloom: by Elegant Themes – 1.3.11
Divi Booster: by Dan Mossop – 3.3.6
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.0.2
Easy Login Styler: by Phpbits Creative Studio – 1.0.6
EventON: by AshanJay – 2.6.15
Facebook for WooCommerce: by Facebook – 2.2.0
Google Adsense Dashboard: by Alin Marcu – 2.3
iThemes Security Pro: by iThemes – 6.8.3
Jetpack by WordPress.com: by Automattic – 9.3.1
Nobuna Plugins: by Nobuna – 2.6
Facebook for WordPress: by Facebook – 3.0.0
PayPal for WooCommerce: by Angell EYE – 2.4.9
Post SMTP: by Yehuda Hassine – 2.0.19
Redirection: by John Godley – 5.0
Webcraftic Robin image optimizer: by Webcraftic  – 1.5.0
Robots.txt Editor: by Processby – 1.1.4
Snap Pixel: by Hassan Ali – 1.5.4
Update Theme and Plugins from Zip File: by Jeff Sherk – 2.0.0
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 2.16.20.24

Webgility: by Webgility – v380 – Installed version not tested with active version of WooCommerce 4.0
WooCommerce Product Slider Pro: by ShapedPlugin – 2.4.19 – Installed version not tested with active version of WooCommerce 4.0
WooCommerce Amazon S3 Storage: by WooCommerce – 2.1.22
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.9.6

WooCommerce Shipping & Tax: by Automattic – 1.25.5
WooCommerce - ShipStation Integration: by WooCommerce – 4.1.40
WooCommerce: by Automattic – 4.9.1
Yoast SEO Premium: by Team Yoast – 15.6.2
Analytify Pro: by WPBrigade – 2.2.1
Analytify - WooCommerce add-on: by Team Analytify – 3.0.2
Analytify - Google Analytics Dashboard: by Analytify – 3.1.5
WP Rocket: by WP Media – 3.4.2.2
WPS Hide Login: by WPServeur
NicolasKulka
wpformation – 1.6.1

Yoast SEO: WooCommerce: by Team Yoast – 13.8

### Inactive Plugins (7) ###

Ads for WP - Advanced Ads & Adsense Solution for WP & AMP: by Magazine3 – 1.9.16.1
Divi Post Extended: by Elicus Technologies – 1.0.2
Express Checkout via PayPal for WooCommerce: by wpgateways – 4.0.1
TaxJar - Sales Tax Automation for WooCommerce: by TaxJar – 3.2.4
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.1
WP All Import Pro: by Soflyy – 4.5.8
WP Post Navigation: by Anas Mir – 1.2.4

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
db-error.php: db-error.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #67686 - /shop/
Cart: #67687 - /cart/
Checkout: #67688 - /checkout/
My account: #67689 - /my-account/
Terms and conditions: #63 - /terms/

### Theme ###

Name: 1320-child
Version: (update to version 0 is available)
Author URL: 
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 4.8.1
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 9,427
Oldest: 2020-12-21 20:18:10 +0000
Newest: 2021-01-21 20:09:29 +0000

Failed: 1
Oldest: 2020-03-17 19:34:11 +0000
Newest: 2020-03-17 19:34:11 +0000

Pending: 5
Oldest: 2021-01-21 20:21:20 +0000
Newest: 2021-01-28 16:46:14 +0000

`

**Comment by juliaamosova** [comment]
Hi @kdimedia,

Thank you for submitting the issue. However, it sounds like your issue is related to a plugin that provides USPS shipping rates. In which case, this is not a part of WooCommerce Core functionality. 

I couldn't see the video - it doesn't fully load for me. In any case, please contact the developers of the plugin that provides USPS rates on your site so that they could help get it resolved. 

I am closing this thread as this is not a WooCommerce Core issue. If I missed something, please feel free to comment further here.
