### ISSUE TITLE
Show country even if it's the same as the shop's country

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce#28894]
**Is your feature request related to a problem? Please describe.**

Currently, the country in the orders and emails is not shown if it's the same as the shop's base address:

https://snipboard.io/qI6pkA.jpg

This should show Switzerland for the first order. The same happens on the order details and the emails.

**Describe the solution you'd like**

Show the country regardless of the shop's address. It would avoid any potential issue and confusion.

**Additional context**
27051841-hc

**Comment by juliaamosova** [comment]
Hi @SiR-DanieL,

Thank you for taking the time to share this idea, we really appreciate your help. 

While this is clearly a great improvement/idea we won’t be able to tackle it in the upcoming weeks. We’re going to add it to our backlog where it will be considered for future releases.

**Comment by 79mplus-admin** [comment]
@SiR-DanieL you can achieve this by using **woocommerce_formatted_address_force_country_display** filter. Just add the following code in your theme's functions.php file:
`add_filter( 'woocommerce_formatted_address_force_country_display', '__return_true' );`

**Comment by ralucaStan** [comment]
Closing as there is a working solution

**Comment by ralucaStan** [comment]
Closing as there was a valid workaround; the listing no longer shows addresses
