### ISSUE TITLE
Edit locations

### ISSUE THREAD

**Issue by Brabus6300** [woocommerce/woocommerce#28902]
Hello

I am working on a eCommerce Project and i can't choose my country from the settings.

My Online Shop offers products in the Republic of Kosovo, but i can't choose my country.

The suggested Countrys/Regions in the picture attached are outdated.

Further the following regions do not exist:
1. "Serbia - Kosovo"
2. "Serbia - Pec"
3. "Serbia - Prizren"
4. "Serbia - Kosovska Mitrovica"
5. "Serbia - Kosovo Pomoravlje"
6. "Serbia - Kosovo Metohija"

These Regions are nowadays regions of the Republic of Kosovo, which is a country by its own:
1. "Serbia - Kosovo" does not exist
2. Kosovo - Peja
3. Kosovo - Prizren
4. Kosovo - Mitrovicë
5. Kosovo - Gjilan
Other regions/municipalities:
Kosovo - Prishtina
Kosovo - Gjakova
Kosovo - Vushtrri
Kosovo - Ferizaj
Kosovo - Suhareka

Thank you for editing!

![Screenshot 2021-01-22 174614](https://user-images.githubusercontent.com/77850577/105519638-eedc3680-5cd9-11eb-8233-41dd0fb7d6bd.jpg)

**Comment by zhongruige** [comment]
Hi @Brabus6300,

Thank you for taking the time to report this! 

In this case, we adopted the UNICODE CLDR [http://cldr.unicode.org/translation/displaynames/country-names](http://cldr.unicode.org/translation/displaynames/country-names) standard for adding in countries and regions to WooCommerce. For example, the entries for Kosovo from CLDR is listed here: [https://github.com/unicode-org/cldr/blob/master/common/subdivisions/en.xml#L4277](https://github.com/unicode-org/cldr/blob/master/common/subdivisions/en.xml#L4277) and currently CLDR does not have any subdivisions marked for Kosovo, either: [https://github.com/unicode-org/cldr/blob/master/common/subdivisions/en.xml#L5544](https://github.com/unicode-org/cldr/blob/master/common/subdivisions/en.xml#L5544).

I'm closing this issue for now. If I missed something please leave a comment and we'll take a second look.

**Comment by BuLiG-coder** [comment]
where should i upload the file exactly please since i am kinda new in coding and here is an example of the edit i hope it shows now correctly as country and the state/city as cities https://prnt.sc/kCYMQOK9Z0X1

best regards
B.SH
