### ISSUE TITLE
REST API get/customers not returning unregistered customers. 

### ISSUE THREAD

**Issue by hallcrash** [woocommerce/woocommerce#28912]
I was attempting to transfer data to a local odoo installation via the Woocommerce REST API. When customers of all rolls are selected at 100 per page, the request returns only "registered users". I can see unregistered users on the [woocommerce-->customers] page, and some of those customers have multiple orders and they are associated with the correct customer, so I assume that they are organised by email address. I checked all the documentation and I searched if there was some other people with this problem, and I don't see anything around, Is this a bug? 
Query:
/wp-json/wc/v3/customers?per_page=100&role=all&consumer_key=<omitted>&consumer_secret=<omitted>

**Comment by rrennick** [comment]
> I can see unregistered users on the [woocommerce-->customers] page

@hallcrash The REST route/endpoint for the customers page is `/wp-json/wc-analytics/customers/`. Closing this issue.

**Comment by hallcrash** [comment]
I'm not sure how that's a support request. the solution you gave me
worked.. I wrote all this code, then it broke because it only returns 10
customers. there is no documentation wc-analytics json, and the OPTIONS
request method fails... so I don't know how to increase the amount of
results returned or page through the results. so as this is kinda a fix, it
still buggy.
