### ISSUE TITLE
Notification message not getting cleared on when doing add to cart on cart page

### ISSUE THREAD

**Issue by rajeshsingh520** [woocommerce/woocommerce#28914]
Hi,

Wehen you have related product shown on the Cart page, at that time if you do add to cart the top part notification message do not get cleared and they keep on staking on top of each other 

see the video for the issue https://youtu.be/Mq4fRhpTw9U

**Comment by zhongruige** [comment]
Hi @rajeshsingh520,

Thank you for taking the time to report this issue, as well as provide a link to a video showing the notification message not being cleared. We appreciate it!

I was able to replicate this issue with the debug shipping notification, which is enabled under `WooCommerce -> Settings -> Shipping -> Shipping Options`:

<img width="909" alt="Screen Shot 2021-01-27 at 11 12 45 AM" src="https://user-images.githubusercontent.com/71906536/106034800-99fd3f00-6090-11eb-87c6-c1f985cb83c8.png">

However, other notifications behaved as expected (such as when removing items from the cart), and would be cleared out or not duplicated and stacked on top of each other:

https://user-images.githubusercontent.com/71906536/106035469-666ee480-6091-11eb-916f-98273f482933.mov

Can you confirm if you are seeing this with all notifications, or if it just with the debug shipping notification above?

I performed the testing above on:
* WordPress 5.6
* WooCommerce 4.9.2
* Twenty Twenty, Twenty Twenty One, and Storefront themes 

Thank you!

**Comment by rajeshsingh520** [comment]
Hi,

Thanks for checking it out, the issue only happnes when you do (add to cart) on the cart page 

if you have any other notification also apart form the shipping zone noticiation, even that notification start to stack up on the cart page if you do add to cart on the cart page 

(like in our case we had a min purchase amount notification warning on the cart page and that also started staking up when we did add to cart)

this does not happens when you update cart or remove product form the cart

**Comment by zhongruige** [comment]
Hi @rajeshsingh520,

Thank you for the reply! I was able to reproduce it on my end setting the minimum amount notifications. Here's the steps I followed:

1. Added the [Code Snippets](https://wordpress.org/plugins/code-snippets/) plugin
2. Added the following code, sourced from the [Minimum Order Amount]() WooCommerce documentation:

```php
/**
 * Set a minimum order amount for checkout
 */
add_action( 'woocommerce_checkout_process', 'wc_minimum_order_amount' );
add_action( 'woocommerce_before_cart' , 'wc_minimum_order_amount' );
 
function wc_minimum_order_amount() {
    // Set this variable to specify a minimum order value
    $minimum = 50;

    if ( WC()->cart->total < $minimum ) {

        if( is_cart() ) {

            wc_print_notice( 
                sprintf( 'Your current order total is %s — you must have an order with a minimum of %s to place your order ' , 
                    wc_price( WC()->cart->total ), 
                    wc_price( $minimum )
                ), 'error' 
            );

        } else {

            wc_add_notice( 
                sprintf( 'Your current order total is %s — you must have an order with a minimum of %s to place your order' , 
                    wc_price( WC()->cart->total ), 
                    wc_price( $minimum )
                ), 'error' 
            );

        }
    }
}
```

3. Proceeded to the checkout screen, and verified the notification was showing:

<img width="1523" alt="Screen Shot 2021-01-28 at 2 53 39 PM" src="https://user-images.githubusercontent.com/71906536/106203955-6ba75e80-6179-11eb-8780-dc8a20054a52.png">

4. Proceeded to add and remove items from the shopping cart and saw the duplicated messages. From the price difference in the cart total, you can see how the old message is still being held in the session:

<img width="1492" alt="Screen Shot 2021-01-28 at 2 54 19 PM" src="https://user-images.githubusercontent.com/71906536/106204012-81b51f00-6179-11eb-920f-96c6eac92cc3.png">

I was able to reproduce this on the following:

* WordPress 5.6
* WooCommerce 4.9.2
* Twenty Twenty, Twenty Twenty One, and Storefront themes

Storefront:

<img width="846" alt="Screen Shot 2021-01-28 at 3 28 42 PM" src="https://user-images.githubusercontent.com/71906536/106207309-c7281b00-617e-11eb-88dd-19b7988f93a8.png">

Twenty Twenty One:

<img width="1334" alt="Screen Shot 2021-01-28 at 3 29 21 PM" src="https://user-images.githubusercontent.com/71906536/106207323-cee7bf80-617e-11eb-80c0-94baf311a95d.png">

We’re going to solve this bug as soon as possible. Stay tuned for updates.

**Comment by rajeshsingh520** [comment]
Hi,

thanks for checking this, right now we have added this temporary fix in your plugin see if this code sample is of any help to find fix for this

We are loading this JS on Cart page only to detect add to cart even on cart page and according to that remove notification

`$(document).ajaxComplete(function (event, jqxhr, settings) {
            if (settings.url.includes("wc-ajax=add_to_cart")) {
                jQuery(".woocommerce-error").remove();
            }
        });`

**Comment by zhongruige** [comment]
> Hi,
> 
> thanks for checking this, right now we have added this temporary fix in your plugin see if this code sample is of any help to find fix for this
> 
> We are loading this JS on Cart page only to detect add to cart even on cart page and according to that remove notification
> 
> `$(document).ajaxComplete(function (event, jqxhr, settings) { if (settings.url.includes("wc-ajax=add_to_cart")) { jQuery(".woocommerce-error").remove(); } });`

Thank you for sharing your solution @rajeshsingh520 ! This will make a great reference point for the development team when to go to pick up this issue.
