### ISSUE TITLE
Spike: Propose a benchmarking tool for measuring checkouts per second

### ISSUE THREAD

**Issue by jonathansadowski** [woocommerce/woocommerce#28926]
To align with our goals of having a full CRUD implementation with a 0% reduction in checkouts per second, we need to define how we'll measure CPS

Desired outcome: A proposal for a benchmarking tool for measuring CPS (checkouts per second). A post outlining the tools that were looked at, along with a recommendation for the tool to use.

**Comment by jonathansadowski** [comment]
MVP: P2 post with a suggested design for measuring API requests against a local environment

**Comment by jonathansadowski** [comment]
* Proposing benchmarking tool
2 day timebox

* Decision on approach on performing testing with given tool
2.5 day timebox

**Comment by ObliviousHarmony** [comment]
This has been completed!
