### ISSUE TITLE
Country Locale Data and States Consolodation

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/woocommerce#28944]
The locale data in the countries class is not quite in sync with the states file. An example would be Austria which has no states (the state field is not required and should be hidden). Checkout does show this correctly, but it needs to reference both sources of data to do this.

**Describe the bug**
Example locale for Austria: https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-countries.php#L794-L801

Austria has no States: https://github.com/woocommerce/woocommerce/blob/master/i18n/states.php#L64

**Expected behavior**
Ideally, this should have both `required => false` and `hidden => true` so the countries locale data can be trusted.

Related to https://github.com/woocommerce/woocommerce-gutenberg-products-block/pull/3662

**Comment by juliaamosova** [comment]
Hi @mikejolley,

Thank you for bringing this up. I'll mark this as a `high` priority so that we could take care of it soon for a consistent and reliable experience throughout.
