### ISSUE TITLE
Can't run E2E tests (different environment than 28958)

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce#28959]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
While trying to get around #28958 I switched to an Ubuntu environment and here, can't run the tests for a different reason.

**Expected behavior**
To be able to run the tests IAW with the documented steps

**Actual behavior**
`npm install` errors out

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. https://github.com/woocommerce/woocommerce/blob/master/tests/e2e/README.md#running-tests
2. on step `npm install` see an error for:
```
5868 error code ELIFECYCLE
5869 error errno 254
5870 error woocommerce@5.1.0 install: `lerna bootstrap --hoist`
5870 error Exit status 254
5871 error Failed at the woocommerce@5.1.0 install script.
5871 error This is probably not a problem with npm. There is likely additional logging output above.
5872 verbose exit [ 254, true ]
```

debug log: 
[2021-01-27T17_30_47_678Z-debug.log.zip](https://github.com/woocommerce/woocommerce/files/5882008/2021-01-27T17_30_47_678Z-debug.log.zip)

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [N/A ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [N/A ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by rrennick** [comment]
@WillBrubaker Was this the same config issue as #28960?

**Comment by WillBrubaker** [comment]
@rrennick No it is not.

**Comment by rrennick** [comment]
@WillBrubaker It might be a few days before we get to reviewing #29134. If you had a few minutes could you test to see if it resolves the issue you are having with Focal?

**Comment by rrennick** [comment]
As a follow up, I have Big Sur on my Mac and there appear to be issues with running linux distros in Virtualbox/Vagrant with this OS.

**Comment by rrennick** [comment]
Closing due to lack of followup.
