### ISSUE TITLE
Can't run e2e tests

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce#28958]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

Trying to run the E2E tests IAW this documentation: https://github.com/woocommerce/woocommerce/blob/master/tests/e2e/README.md#running-tests fails at the step `composer install --no-dev` with the error message:
```
command not founde.sh: line 2:
'/bin/package-update.sh: line 14: syntax error near unexpected token `{
'/bin/package-update.sh: line 14: `output() {
```

**Expected behavior**
That I can run the tests as documented

**Actual behavior**
Error message

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

 https://github.com/woocommerce/woocommerce/blob/master/tests/e2e/README.md#running-tests

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [N/A ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [N/A ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by rrennick** [comment]
This is being discussed in #28960 so closing as duplicate.
