### ISSUE TITLE
Logged in user can visit page to reset password (lost-password)

### ISSUE THREAD

**Issue by juanlopez4691** [woocommerce/woocommerce#28956]
This logic allows a logged user to visit page `/my-account/lost-password/`

https://github.com/woocommerce/woocommerce/blob/af3077bca9990260feae2850cd63762d06035f9c/includes/shortcodes/class-wc-shortcode-my-account.php#L42

A possible fix would be:
```diff
-- if ( ! is_user_logged_in() || isset( $wp->query_vars['lost-password'] ) ) {
++ if ( ! is_user_logged_in() && isset( $wp->query_vars['lost-password'] ) ) {
```

**Comment by juliaamosova** [comment]
Hi @juanlopez4691,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

![pw](https://user-images.githubusercontent.com/19143190/107126135-199ec100-687c-11eb-8e01-2fbba1c82577.jpg)

We’re going to solve this bug as soon as possible.

**Comment by juanlopez4691** [comment]
Great! Happy to be helpful :-)

Best regards,
Joan López

**Comment by sun** [comment]
Created PR https://github.com/woocommerce/woocommerce/pull/29164 together with @bogdanarizancu

**Comment by claudiosanches** [comment]
The suggested code in this issue causes a new bug: https://github.com/woocommerce/woocommerce/pull/29164
