### ISSUE TITLE
Can't run e2e tests

### ISSUE THREAD

**Issue by WillBrubaker** [woocommerce/woocommerce#28960]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

running E2E tests IAW https://github.com/woocommerce/woocommerce/blob/master/tests/e2e/README.md#running-tests fails on `npx wc-e2e docker:up` with:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/wc-e2e - Not found
npm ERR! 404
npm ERR! 404  'wc-e2e@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/will/.npm/_logs/2021-01-27T17_39_08_673Z-debug.log
Install for [ 'wc-e2e@latest' ] failed with code 1
```

**Expected behavior**
to be able to run the tests as documented

**Actual behavior**
error

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. https://github.com/woocommerce/woocommerce/blob/master/tests/e2e/README.md#running-tests
2. I had to remove the carriage returns from `bin/package-update.sh` and `node_modules/.bin/wc-e2e` to get around #28959  
3. final step `npx wc-e2e docker:up`

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [N/A ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [N/A ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by rrennick** [comment]
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/wc-e2e - Not found

@WillBrubaker Use the commands in step 3 of the testing instructions in https://github.com/woocommerce/woocommerce/pull/28841 in the latest master to correctly install the `wc-e2e` script.

**Comment by WillBrubaker** [comment]
Maybe I'm not understanding the instructions. Here's everything starting from zero:

```
8552  git clone git@github.com:woocommerce/woocommerce.git\n
 8553  cd woocommerce
 8554  git checkout master
 8555  nvm use
 8556  npm install
 8557  rm node_modules/@woocommerce/e2e-environment
 8558  rm -rf tests/e2e/env/node_modules
 8559  npm run build:packages
 8560  npm install
 8561  composer install --no-dev
 8562  cat bin/package-update.sh| tr -d "\r" > package-update.sh
 8563  mv package-update.sh bin/
 8564  composer install --no-dev
 8565  npm run build:assets
 8566  npm install jest --global
 8567  npx wc-e2e docker:up
 8568  cat node_modules/.bin/wc-e2e | tr -d "\r" > wc-e2e
 8569  mv wc-e2e node_modules/.bin/
 8570  npx wc-e2e docker:up
```

and I get the same result
[2021-01-27T21_25_47_747Z-debug.log.zip](https://github.com/woocommerce/woocommerce/files/5883218/2021-01-27T21_25_47_747Z-debug.log.zip)

**Comment by rrennick** [comment]
Starting with a new clone Travis does 8552-6, 8564-7 on every PR. What OS are you using?

**Comment by WillBrubaker** [comment]
Catalina 10.15.7

**Comment by rrennick** [comment]
> Catalina 10.15.7

On #28958 you tested with Ubuntu. Was that `Xenial`? Catalina is definitely okay for MacOS. What version(s) of `npm` do you have?

**Comment by WillBrubaker** [comment]
>Was that Xenial? 

Focal 

>What version(s) of npm

6.14.10 on the Ubuntu system
6.14.8 on mac

**Comment by rrennick** [comment]
> cat bin/package-update.sh| tr -d "\r" > package-update.sh

What error did you get that lead to doing this command? Did you get the error in both environments?

The software versions look fine.

**Comment by WillBrubaker** [comment]
>What error did you get that lead to doing this command?

https://github.com/woocommerce/woocommerce/issues/28958

>Did you get the error in both environments?

I didn't get that far on the Ubuntu environment https://github.com/woocommerce/woocommerce/issues/28959

**Comment by rrennick** [comment]
What shell are you running on the Mac?

**Comment by WillBrubaker** [comment]
zsh

**Comment by rrennick** [comment]
> zsh

@WillBrubaker I had an update in the last day or so & I think that's now my default shell so I should find out in the next day or so if that's causing a problem.

**Comment by rrennick** [comment]
I tried `zsh`. The only issue I had was `nvm use` gave me an error. In my case that's not a problem since I alreay have the correct version of `node` installed.

I thought I would check the script edit you used and found it did not make any changes to the file on my computer

```
$ cat bin/package-update.sh| tr -d "\r" > ../package-update.sh
$ diff ../package-update.sh bin/package-update.sh
$ 
```

Could you reset your file to the version from Github and post the differences it made on your computer?

**Comment by WillBrubaker** [comment]
diff doesn't show anything. The MS carriage returns get stripped out

**Comment by WillBrubaker** [comment]
Also, what difference does my shell make? Isn't the script supposed to use the interpreter designated?

**Comment by WillBrubaker** [comment]
What is the correct version of node?

**Comment by rrennick** [comment]
> What is the correct version of node?

Version 12. `nvm use` should have updated node to v12.

> Carriage returns get stripped out

When I ran the diff in `zsh` the files were identical.

> what difference does my shell make? Isn't the script supposed to use the interpreter designated?

Yes, the script runs using `sh`. What I was trying to work out is why you have a parse error on the script when no one else does. It looks like there is something on your computer that is adding `\r` to the lines but I don't know of anything that automatically does that.

**Comment by WillBrubaker** [comment]
What does `md5 -r bin/package-update.sh` result in on your system?

25801f01efe394066b085bd502b712cc bin/package-update.sh

After removing the carriage returns:

25234e109ceda842042812bc53004306 bin/package-update.sh

**Comment by WillBrubaker** [comment]
Nevermind. Found it https://git-scm.com/docs/gitattributes#_end_of_line_conversion ~/.gitconfig had 
```
autocrlf = true
```

I changed that and everything works. Thanks.

**Comment by rrennick** [comment]
@WillBrubaker Awesome. Glad you found it.
