### ISSUE TITLE
Add total discount from on sale items to orders

### ISSUE THREAD

**Issue by Dekadinious** [woocommerce/woocommerce#28972]
**Is your feature request related to a problem? Please describe.**
I want to display the discount the customer has been given on their order in various places. For example over the total order amount in the order emails. At present the discount given by coupons will be shown, but not discount given when a product was bought on sale.

I have been very frustrated working with the WC_Order class because the naming of the methods confuse me. I was expecting `$order->get_discount_total();` and similar methods to give me the total discount for the order. I was confused when it sometimes returned a positive value and sometimes returned 0.

After some testing I could see that the methods give a positive value when the discount is given through a coupon, but not when the discount is given through a product on sale.

It is very useful to be able to show how much discount is given on an order. I have been thinking that I could loop the order items and get the regular price of the item, and calculate the discount using the actual price the item was bought for. This will not work because it is not saved on the order. The regular price is therefore not the regular price at the time of purchase, but the regular price right now. If the price has changed, the discount is not correct.

**Describe the solution you'd like**
I would like the naming of the methods to be more clear, and the documentation to explain what type of discount is going to be fetched by the method. I would also probably like a few extra methods. I am no expert, but here are some thoughts:

`get_discount_total`
Gets the total discount given on an order. This is the sale discount and the coupon discount added together.

`get_coupon_discount_total`
Just like `get_discount_total` works today, but clearer documentation explaining that only discounts from coupons are fetched.

`get_sale_discount_total`
Gets the total discount given on an order based on regular price minus sale price. Does not account for coupon discounts.

**Describe alternatives you've considered**
I have considered saving this manually to order meta when orders are created, but it seems like something that could be valuable to put inside core.

**Comment by barryhughes** [comment]
Thank you for this suggestion.

I agree with the general concerns you raised, and we'll certainly try to factor them in via future changes. For now, though, I will close this issue:

- Some changes such as you suggested for existing method `WC_Abstract_Order::get_discount_total()` would pose backward compatibility concerns.
- Providing the ability to obtain only the sale discount (non-coupon discount) has a lot of merit, but from our perspective is one piece in a larger conversation about retention of different types of historic data. 

> I have considered saving this manually to order meta when orders are created, but it seems like something that could be valuable to put inside core.

Yes, though in the near-term, I think a solution such as you outlined would be the best way forward.
