### ISSUE TITLE
Extra ) in zipcode help text

### ISSUE THREAD

**Issue by zhongruige** [woocommerce/woocommerce#28992]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

In the zip code/postcode documentation description, there's an extra `)` in the zipcode help text.

**Expected behavior**

Remove the extra `)` in the text:

```diff
- Postcodes containing wildcards (e.g. CB23*) or fully numeric ranges (e.g. 90210...99000) are also supported. Please see the shipping zones documentation) for more information.
+ Postcodes containing wildcards (e.g. CB23*) or fully numeric ranges (e.g. 90210...99000) are also supported. Please see the shipping zones documentation for more information.
```

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to `WooCommerce > Settings > Shipping`
2. Click on `Add shipping zone`
3. In the `Zone regions` section, click on "Limit to specific ZIP/postcodes"
4. Under the "List 1 postcode per line" textbox that appears, note the postcode help text and note the extras `)` after the word "documentation".

**Screenshots**

<img width="1502" alt="Screen Shot 2021-02-01 at 1 35 31 PM" src="https://user-images.githubusercontent.com/71906536/106515420-e7afe800-6492-11eb-8dd9-aa561dfebb72.png">

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by EdithAllison** [comment]
I work a lot with Woo but I'm new to Github. Could I handle this as a first contrib?

**Comment by vedanshujain** [comment]
@EdithAllison please go ahead and submit a PR. thanks!
