### ISSUE TITLE
Write new e2e test: Merchant – Products – Add Simple Product

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#29004]
Write a new e2e test that covers the following flow: 

- Merchant / Products / Add Virtual Product

**Comment by rodel-calasagsag** [comment]
Hi @juliaamosova as discussed with @tammullen,
I noticed that we already have an e2e test for this. I'm referring to this test - https://github.com/woocommerce/woocommerce/blob/40506dfcc5beac5f93558bcabaf3262cac9ee3f7/tests/e2e/core-tests/specs/merchant/wp-admin-product-new.test.js#L64

But we can make this test a bit more comprehensive though, by adding steps to:
1. Hover on the "Virtual" checkbox and verify that it will display a tooltip.
2. Verify that the "Shipping" option disappears once "Virtual" is checked.

Let me know your thoughts. Thanks!

**Comment by tammullen** [comment]
Thanks @rodel-calasagsag, have you thoughts on what we need to do to continue to cover the flow `Merchant | Products | Add Simple Product`?

**Comment by rodel-calasagsag** [comment]
Hi @tammullen. I'm thinking I can do one of these two approaches:

1. I can improve the existing test by adding these steps into it:
> 
    1. Hover on the "Virtual" checkbox and verify that it will display a tooltip.
    2. Verify that the "Shipping" option disappears once "Virtual" is checked.
2. Or, I can create a new test for adding a non-virtual simple product because we don't seem to have an e2e test that covers it. I'm thinking it would have the following steps:
>
    1. Go to "Add new product" page.
    2. Enter a "Product name"
    3. Enter a long & short product description.
    4. Enter a "Regular price"
    5. Click on the "Shipping" tab.
    6. Enter a "Weight (kg)" value.
    7. Fill up the "Dimensions" fields.
    8. Click "Publish"
    9. Verify that a permalink is generated
    10. Go to "All Products" page
    11. Verify that the added simple (non-virtual) product is listed there with the correct product name and price
    12. Trash the item to clean the test up

Which of these would you like me to prioritize? I'm thinking we should do the 2nd one because it's a basic flow that we don't seem to cover yet, as far as I can see on the `trunk` branch.

**Comment by rrennick** [comment]
> 1. Hover on the "Virtual" checkbox and verify that it will display a tooltip.

This sounds like it might be something that would be flaky.

**Comment by tammullen** [comment]
> Hover on the "Virtual" checkbox and verify that it will display a tooltip.

> This sounds like it might be something that would be flaky.

Agreed

> Verify that the "Shipping" option disappears once "Virtual" is checked.

I think this sounds like a better option

> create a new test for adding a non-virtual simple product because we don't seem to have an e2e test that covers it.

Yes I think it would be good to have one for both, a quicker win would be just use the same flow as we have already but remove the step of setting the virtual checkbox. We could add more steps at a later date. We want to keep the tests as simple and short as possible for now.

**Comment by rodel-calasagsag** [comment]
Thank you @rrennick @tammullen 

As discussed in Slack, we'll leave the `can create simple virtual product titled "Simple Product" with regular price $9.99` test as it is, and then probably split or update it in the future when needed.

**Comment by loranallensmith** [comment]
We updated the title from virtual to simple here.

**Comment by veljkho** [comment]
I have added a new scenario covering non-virtual simple product flow and update the existing virtual simple product flow. Now we have covered them both.
