### ISSUE TITLE
Write new e2e test: Merchant – Settings – Add Shipping Classes

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#29005]
Write a new e2e test that covers the following flow: 

- Merchant / Settings / Add Shipping Classes

**Comment by rodel-calasagsag** [comment]
Hi @juliaamosova 
I have pushed a PR for this. Apologies for not clarifying the steps first. But here are the steps that I did:

1. Go to Shipping Classes page - `/wp-admin/admin.php?page=wc-settings&tab=shipping&section=classes`
2. Click 'Add shipping class' button
3. Type a "Shipping class name"
4. Type a slug
5. Type a description
6. Click on 'Save shipping classes' button
7. Verify that the 'Shipping classes' table now shows this added shipping class with the correct name, slug, and description

I used this documentation in learning the requirements, as well as in coming up the steps:
https://docs.woocommerce.com/document/product-shipping-classes/

Please let me know if I missed any step or assertion. Thanks!
