### ISSUE TITLE
Issue with the quantity reverting of certain items

### ISSUE THREAD

**Issue by gameplayerhd** [woocommerce/woocommerce#29012]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have carried out troubleshooting steps and I believe I have found a bug.
- [X ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
 The stock count reverts on certain products, which causes a wrong stock count and selling products we don’t have in stock. 

**Expected behavior**
Stock count to stay the same or deduct by orders.

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

Item 1:
1. I set the quantity to 50x
2. When somebody purchases it, it goes to -5 and is out of stock
3. I set it to 49x again
4. When somebody purchases it, it goes to -6 and is out of stock

Item 2:
1. Item is set at 8x
2. We sell 7x to 6 different customers
3. The stock count is after some time is suddenly 8x again
4. I set it to 0x, cause i'm scared of overselling.
5. After some time it changes to 8x again

Tested with storefront

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
`
### WordPress Environment ###

WordPress address (URL): https://myskin.dk
Site address (URL): https://myskin.dk
WC Version: 4.9.2
REST API Version: ✔ 4.9.2
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.9.0
Log Directory Writable: ✔
WP Version: 5.6
WP Multisite: –
WP Memory Limit: 10 GB
WP Debug Mode: –
WP Cron: ✔
Language: da_DK
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.3.23
PHP Post Max Size: 2 GB
PHP Time Limit: 1000
PHP Max Input Vars: 10000
cURL Version: 7.72.0
OpenSSL/1.1.1h

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.27-MariaDB
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.8.0
WC Database Prefix: rl9u_
Total databasestørrelse: 496.55MB
Database datastørrelse: 426.42MB
Database indexstørrelse: 70.13MB
rl9u_woocommerce_sessions: Data: 292.91MB + Index: 11.74MB + Engine MyISAM
rl9u_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
rl9u_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_woocommerce_order_items: Data: 1.74MB + Index: 0.87MB + Engine MyISAM
rl9u_woocommerce_order_itemmeta: Data: 16.02MB + Index: 8.66MB + Engine MyISAM
rl9u_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
rl9u_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_actionscheduler_actions: Data: 5.02MB + Index: 6.08MB + Engine InnoDB
rl9u_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rl9u_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rl9u_actionscheduler_logs: Data: 1.52MB + Index: 0.56MB + Engine InnoDB
rl9u_adtribes_my_conversions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_aepc_custom_audiences: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_aepc_logs: Data: 28.30MB + Index: 0.03MB + Engine MyISAM
rl9u_atum_logs: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
rl9u_atum_logs_cache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
rl9u_atum_logs_cache_var: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rl9u_atum_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_atum_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_atum_product_data: Data: 0.04MB + Index: 0.03MB + Engine MyISAM
rl9u_berocket_termmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_braapf_product_stock_status_parent: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
rl9u_braapf_product_variation_attributes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_braapf_term_taxonomy_hierarchical: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_braapf_variation_attributes: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_check_email_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rl9u_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_comments: Data: 3.97MB + Index: 1.48MB + Engine MyISAM
rl9u_crw_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rl9u_feedmanager_channel: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
rl9u_feedmanager_country: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
rl9u_feedmanager_feed_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_feedmanager_field_categories: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_feedmanager_product_feed: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_feedmanager_product_feedmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_feedmanager_source: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
rl9u_hfcm_scripts: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_imagify_files: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
rl9u_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
rl9u_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_litespeed_img_optm: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_litespeed_optimizer: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
rl9u_ms_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_nextend2_image_storage: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rl9u_nextend2_section_storage: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
rl9u_nextend2_smartslider3_generators: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rl9u_nextend2_smartslider3_sliders: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
rl9u_nextend2_smartslider3_sliders_xref: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rl9u_nextend2_smartslider3_slides: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
rl9u_options: Data: 10.99MB + Index: 0.46MB + Engine MyISAM
rl9u_pakkelabel_shipping_diffrentiated: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_pimwick_gift_card: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rl9u_pimwick_gift_card_activity: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
rl9u_postmeta: Data: 33.79MB + Index: 14.71MB + Engine MyISAM
rl9u_posts: Data: 6.26MB + Index: 0.96MB + Engine MyISAM
rl9u_rank_math_404_logs: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
rl9u_rank_math_analytics_gsc: Data: 5.52MB + Index: 9.69MB + Engine InnoDB
rl9u_rank_math_analytics_objects: Data: 0.13MB + Index: 0.05MB + Engine InnoDB
rl9u_rank_math_internal_links: Data: 0.28MB + Index: 0.07MB + Engine MyISAM
rl9u_rank_math_internal_meta: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
rl9u_rank_math_redirections: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_rank_math_redirections_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_rank_math_sc_analytics: Data: 4.46MB + Index: 1.24MB + Engine MyISAM
rl9u_relevanssi: Data: 1.10MB + Index: 1.78MB + Engine MyISAM
rl9u_relevanssi_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_relevanssi_stopwords: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_revslider_css: Data: 0.09MB + Index: 0.00MB + Engine MyISAM
rl9u_revslider_css_bkp: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
rl9u_revslider_layer_animations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_revslider_layer_animations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_revslider_navigations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_revslider_navigations_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_revslider_sliders: Data: 0.28MB + Index: 0.00MB + Engine MyISAM
rl9u_revslider_sliders_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_revslider_slides: Data: 3.42MB + Index: 0.00MB + Engine MyISAM
rl9u_revslider_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_revslider_static_slides: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_revslider_static_slides_bkp: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_smush_dir_images: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_termmeta: Data: 0.08MB + Index: 0.06MB + Engine MyISAM
rl9u_terms: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
rl9u_term_relationships: Data: 0.10MB + Index: 0.21MB + Engine MyISAM
rl9u_term_taxonomy: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
rl9u_usermeta: Data: 3.47MB + Index: 1.61MB + Engine MyISAM
rl9u_users: Data: 0.15MB + Index: 0.19MB + Engine MyISAM
rl9u_wccs_conditions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_wccs_condition_meta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
rl9u_wcpdf_invoice_number: Data: 0.09MB + Index: 0.05MB + Engine MyISAM
rl9u_wctofb: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_wc_admin_notes: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
rl9u_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_wc_customer_lookup: Data: 0.33MB + Index: 0.32MB + Engine MyISAM
rl9u_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.04MB + Engine MyISAM
rl9u_wc_order_product_lookup: Data: 1.59MB + Index: 1.35MB + Engine MyISAM
rl9u_wc_order_stats: Data: 0.46MB + Index: 0.26MB + Engine MyISAM
rl9u_wc_order_tax_lookup: Data: 0.26MB + Index: 0.29MB + Engine MyISAM
rl9u_wc_product_meta_lookup: Data: 0.05MB + Index: 0.06MB + Engine MyISAM
rl9u_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rl9u_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
rl9u_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_wdp_orders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_wdp_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_wdp_rules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rl9u_wdr_order_item_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rl9u_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
rl9u_woodmart_wishlists: Data: 0.02MB + Index: 0.01MB + Engine MyISAM
rl9u_woodmart_wishlist_products: Data: 0.07MB + Index: 0.11MB + Engine MyISAM
rl9u_woof_query_cache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
rl9u_wsal_metadata: Data: 2.52MB + Index: 6.03MB + Engine InnoDB
rl9u_wsal_occurrences: Data: 0.17MB + Index: 0.25MB + Engine InnoDB
rl9u_yoast_seo_links: Data: 0.49MB + Index: 0.09MB + Engine MyISAM
rl9u_yoast_seo_meta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM

### Post Type Counts ###

attachment: 1448
atum_inventory_log: 2
br_filters_group: 2
br_notice: 1
br_product_filter: 2
cms_block: 112
customize_changeset: 2
cwginstocknotifier: 718
nav_menu_item: 64
oembed_cache: 2
page: 81
portfolio: 9
post: 11
product: 652
product_variation: 14
revision: 855
shop_coupon: 25
shop_order: 5880
shop_order_refund: 67
woo_discount: 1
woo_discount_cart: 1
woodmart_sidebar: 2
woodmart_slide: 35
wpcf7_contact_form: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (45) ###

ATUM Action Logs: af Stock Management Labs™ – 1.1.3
ATUM Inventory Management for WooCommerce: af Stock Management Labs™ – 1.8.5
Back In Stock Notifier for WooCommerce | WooCommerce Waitlist Pro: af codewoogeek – 1.10.0
CategoryTinymce 5: af Kevin Heath – 5.5.3
Payment Gateway Based Fees and Discounts for WooCommerce: af Tyche Softwares – 2.6.2
Controlled Admin Access: af WPRuby – 1.3.9
Google Tag Manager for Wordpress: af Thomas Geiger – 1.11.6
Giftable for WooCommerce: af Decom – 1.0.5
Imagify: af WP Media – 1.9.13
WPBakery Page Builder: af Michael M - WPBakery.com – 6.0.5
Judge.me Product Reviews for WooCommerce: af Judge.me – 1.3.8
Kadence WooCommerce E-mail Designer: af Kadence WP – 1.4.4
Loco Translate: af Tim Whitlock – 2.5.0
OnSale Page for WooCommerce: af wpgenie – 1.0.11
Shipmondo til WooCommerce: af Shipmondo – 4.0.3
Pixel Caffeine: af AdEspresso – 2.1.4
PW WooCommerce Gift Cards Pro: af Pimwick
LLC – 1.293

Really Simple SSL: af Really Simple Plugins – 4.0.7
Relevanssi: af Mikko Saari – 4.11.0
Slider Revolution: af ThemePunch – 6.1.2
Sikker SVG: af Daryll Doyle – 1.9.9
Rank Math SEO: af Rank Math – 1.0.56.1
Smart Slider 3: af Nextend – 3.4.1.16
Swiipe Checkout: af Swiipe Aps – 3.4.0
Trustpilot-reviews: af Trustpilot – 2.5.808
UpdraftPlus - Backup/Restore: af UpdraftPlus.Com
DavidAnderson – 1.16.47

WebP Express: af Bjørn Rosell – 0.19.0
Checkout Field Editor for WooCommerce: af ThemeHigh – 1.4.5
WooCommerce PensoPay: af PensoPay – 5.7.9
Product Feed PRO for WooCommerce: af AdTribes.io – 9.5.1
WooCommerce Admin: af WooCommerce – 1.9.0
WooCommerce Google Ads Conversion Tracking: af Wolf+Bär Agency – 1.8.13
Klaviyo for WooCommerce V2: af Klaviyo
Inc. – 2.0.7

WooCommerce PDF Invoices & Packing Slips: af Ewout Fernhout – 2.7.4
WooCommerce Shipping & Tax: af Automattic – 1.25.6
Viabill PriceTags: af cm-telecom.dk – 1.3
WooCommerce: af Automattic – 4.9.2
Woodmart Core: af  – 1.0.19
Asset CleanUp: Page Speed Booster: af Gabe Livan – 1.3.7.3
WP Rocket: af WP Media – 3.8.3
WP Activity Log: af WP White Security – 4.1.5.2
Smart Coupons for WooCommerce: af WebToffee – 1.2.8
Tilpasset faneblade for WooCommerce: af YIKES
Inc. – 1.7.6

YITH Pre-Order for WooCommerce Premium: af YITH – 1.6.1
YITH WooCommerce Product Bundles: af YITH – 1.2.3

### Inactive Plugins (54) ###

Advanced AJAX Product Filters for WooCommerce: af BeRocket – 1.5.2.8
Advanced Dynamic Pricing for WooCommerce: af AlgolPlus – 3.1.5
Akismet Anti-Spam: af Automattic – 4.1.8
Amount Left for Free Shipping for WooCommerce: af WPFactory – 1.9.6
Analytify - Google Analytics Dashboard: af Analytify – 3.1.6
Antispam Bee: af pluginkollektiv – 2.9.3
Autoptimize: af Frank Goossens (futtta) – 2.8.1
BIALTY - Bulk Image Alt Text (Alt tag, Alt Attribute) with Yoast SEO + WooCommerce: af Pagup – 1.4.4
Cart Notices for WooCommerce: af BeRocket – 3.5.2
Category Restriction WooCommerce: af themelocation – 1.0
Check & Log Email: af WPChill – 1.0.1
Code Snippets: af Code Snippets Pro – 2.14.0
Coming Soon Page, Maintenance Mode & Landing Pages by SeedProd: af SeedProd – 6.0.11.1
Contact Form 7: af Takayuki Miyoshi – 5.3.2
Cookie Notice & Compliance for GDPR / CCPA: af Hu-manity.co – 2.0.0
Easy WooCommerce Discounts - WooCommerce Dynamic Pricing & Shipping: af Asana Plugins – 4.11.0
Facebook for WooCommerce: af Facebook – 2.2.0
Free shipping notification WooCommerce: af PI Websolution – 2.0.1
GDPR CCPA Compliance Support: af NinjaTeam – 2.4.1
Header Footer Code Manager: af 99robots – 1.1.8
Hello Dolly: af Matt Mullenweg – 1.7.2
Image optimization service by Optimole: af Optimole – 2.5.7
Jetpack by WordPress.com: af Automattic – 9.4
Limit Login Attempts Reloaded: af Limit Login Attempts Reloaded – 2.19.2
LiteSpeed Cache: af LiteSpeed Technologies – 3.6.2
Multi-Step Checkout for WooCommerce: af SilkyPress – 2.14
Partner-ads Woocommerce tracking and feed: af Partner-ads – 1.7.1
Preorders for WooCommerce: af Bright Plugins – 1.1.3
PW WooCommerce Gift Cards: af Pimwick
LLC – 1.170

Smush: af WPMU DEV – 3.8.2
Social Commerce for WooCommerce: af premiumthemes – 2.5.4
Veeqo for WooCommerce: af Veeqo – 1.2.7
WooCommerce Advanced Product Labels: af BeRocket – 1.2.0.3
WooCommerce Featured Video: af David Towoju – 2.0.0
WooCommerce Google Ads Dynamic Remarketing: af Wolf+Bär Agency – 1.7.18
Woocommerce one page checkout and layouts: af BluePlugins – 2.6
WooCommerce Single Page Checkout: af Brij Raj Singh – 1.2.5
WooCommerce UPC, EAN, and ISBN: af Scott Bolinger – 0.4.0
Woo Discount Rules: af Flycart – 2.3.4
Woo Discount Rules PRO 2.0: af Flycart Technologies LLP – 2.3.2
WOOF - WooCommerce Products Filter: af realmag777 – 1.2.4.2
Woo Product Category Discount: af WooExtend – 3.2
Wordfence Security: af Wordfence – 7.4.14
WP-Optimize - Clean, Compress, Cache: af David Anderson
Ruhani Rabin
Team Updraft – 3.1.6

WPC Composite Products for WooCommerce: af WPClever.net – 3.2.1
WPC Composite Products for WooCommerce (Premium): af WPClever.net – 1.4.3.2
WPC Frequently Bought Together for WooCommerce: af WPClever.net – 3.4.2
WP Fastest Cache: af Emre Vona – 0.9.1.4
WP Product Feed Manager: af Michel Jongbloed – 1.27.0
WP Sheet Editor - WooCommerce Products: af WP Sheet Editor – 1.6.0
WPS Hide Login: af WPServeur
NicolasKulka
wpformation – 1.6.1

WP Super Cache: af Automattic – 1.7.1
YITH WooCommerce Cart Messages: af YITH – 1.6.0
Yoast SEO: af Team Yoast – 15.7

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (1) ###

installatron_hide_status_test.php: af  –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: DKK (Kr.)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
pw gift card (pw-gift-card)
simple (simple)
variable (variable)
yith_bundle (yith_bundle)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop basisside: #6 - /shop/
Kurv: #7 - /kurv/
Checkout: #8 - /kasse/
Min konto: #9 - /min-konto/
Vilkår og betingelser: #1629 - /handelsbetingelser/

### Theme ###

Name: Woodmart
Version: 4.1.0
Author URL: http://themeforest.net/user/xtemos
Child Theme: ❌ – Hvis du redigerer WooCommerce i et hovedtema
som du ikke selv har udviklet
anbefaler vi
at du anvender et undertema (child theme). Se: Hvordan du opretter et undertema

WooCommerce Support: ✔

### Templates ###

Overrides: woodmart/woocommerce/archive-product.php
woodmart/woocommerce/cart/cart-item-data.php
woodmart/woocommerce/cart/cart.php version 3.7.0 er udgået. Kerneversionen er 3.8.0
woodmart/woocommerce/cart/cross-sells.php version 3.0.0 er udgået. Kerneversionen er 4.4.0
woodmart/woocommerce/cart/mini-cart.php
woodmart/woocommerce/checkout/form-checkout.php
woodmart/woocommerce/content-product.php
woodmart/woocommerce/content-single-product.php
woodmart/woocommerce/content-widget-product.php
woodmart/woocommerce/global/breadcrumb.php
woodmart/woocommerce/global/form-login.php
woodmart/woocommerce/global/quantity-input.php version 3.6.0 er udgået. Kerneversionen er 4.0.0
woodmart/woocommerce/loop/add-to-cart.php
woodmart/woocommerce/loop/loop-end.php
woodmart/woocommerce/loop/loop-start.php
woodmart/woocommerce/loop/no-products-found.php
woodmart/woocommerce/loop/orderby.php
woodmart/woocommerce/loop/pagination.php
woodmart/woocommerce/loop/sale-flash.php
woodmart/woocommerce/myaccount/form-login.php version 3.6.0 er udgået. Kerneversionen er 4.1.0
woodmart/woocommerce/product-searchform.php
woodmart/woocommerce/single-product/add-to-cart/grouped.php version 3.4.0 er udgået. Kerneversionen er 4.0.0
woodmart/woocommerce/single-product/add-to-cart/variable.php
woodmart/woocommerce/single-product/meta.php
woodmart/woocommerce/single-product/product-image.php
woodmart/woocommerce/single-product/product-thumbnails.php
woodmart/woocommerce/single-product/rating.php
woodmart/woocommerce/single-product/related.php version 3.0.0 er udgået. Kerneversionen er 3.9.0
woodmart/woocommerce/single-product/sale-flash.php
woodmart/woocommerce/single-product/tabs/tabs.php version 2.4.0 er udgået. Kerneversionen er 3.8.0
woodmart/woocommerce/single-product/title.php
woodmart/woocommerce/single-product/up-sells.php
woodmart/woocommerce/single-product.php
woodmart/woocommerce/content-product_cat.php version 2.6.1 er udgået. Kerneversionen er 4.7.0

### Action Scheduler ###

Complete: 14.951
Oldest: 2021-01-15 12:18:45 +0000
Newest: 2021-02-03 11:33:43 +0000

Pending: 4
Oldest: 2021-02-03 11:56:33 +0000
Newest: 2021-02-05 12:19:57 +0000

`
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by juliaamosova** [comment]
Hi @gameplayerhd,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

I have a product that I set to have a stock of 50:

![1](https://user-images.githubusercontent.com/19143190/106804724-c76b5f00-6633-11eb-9330-640d9e54a5de.jpg)

I placed an order for 1 item of that product:

![2](https://user-images.githubusercontent.com/19143190/106804748-cc301300-6633-11eb-962a-666cb0774a3d.jpg)

The stock decreased to 49 after the purchase as expected:

![3](https://user-images.githubusercontent.com/19143190/106804766-cfc39a00-6633-11eb-943a-3c660e135853.jpg)

You indicated that you tested with Storefront in your report and that you also deactivated all the plugins but the issue persists. However, can you please confirm that you in fact did this? 

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by volpagirl** [comment]
Hi - we have one client with the same issue on their website, started a few days ago. Seen a few posts that link this issue to ATUM's plugin but this client doesn't have ATUM's stock control plugin, they use Woocommerce stock control. They too have had random reversion of stock quantities from being out of stock to being in stock which has caused them some issues.

**Comment by zhongruige** [comment]
> Hi - we have one client with the same issue on their website, started a few days ago. Seen a few posts that link this issue to ATUM's plugin but this client doesn't have ATUM's stock control plugin, they use Woocommerce stock control. They too have had random reversion of stock quantities from being out of stock to being in stock which has caused them some issues.

Hi @volpagirl,

Thank you for mentioning this. To clarify real quick, is the "Woocommerce stock control" they're using the default one that ships with WooCommerce or a plugin? Has there been any consistency in reproducing the issue (e.g. set steps that would could follow, similar to what was initially reported here), or is it entirely random with reverting the quantities?
