### ISSUE TITLE
[GlobalStep - WooCommerce 5.0 RC 2 + WordPress 5.7 Beta 1][Mac] For Twenty Twenty One theme ”Apply coupon" and "Update cart" buttons are misaligned on Cart page.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#29015]
## Bug Description:
For Twenty Twenty One theme ”Apply coupon" and "Update cart" buttons are misaligned on Cart page.

## Environment:
macOS High Sierra v10.13.6
Browser: Safari: v13.1.2(13609.3.5.1.5)
                
## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all the required plugins
1. Complete the Onboarding setup wizard.
1. Select Twenty Twenty One Theme.
1. Add some products.
1. Go to frontend and click on of the Product.
1. Click on "Add to Cart" button.
1. Click on "View Cart" button.
1. Observe that for Twenty Twenty One theme ”Apply coupon" and "Update cart" buttons are misaligned for WordPress 5.7 on frontend.

## Actual Result:
For Twenty Twenty One theme ”Apply coupon" and "Update cart" buttons are misaligned on Cart page.

## Expected Result:
For Twenty Twenty One theme ”Apply coupon" and "Update cart" buttons should be properly aligned.

## Screenshot:

![#29015](https://user-images.githubusercontent.com/41110392/106771778-5b095380-6665-11eb-9a30-2b079ed0c233.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment]
Hello,

Thanks for reporting this issue. I'm able to reproduce this issue with Firefox in Linux.

**Comment by rrennick** [comment]
This has been fixed

<img width="1293" alt="Screenshot 2023-06-19 at 4 42 17 PM" src="https://github.com/woocommerce/woocommerce/assets/343847/e9942f82-4748-4b40-8ff4-07cda66c9429">
