### ISSUE TITLE
Multisite, same shop slug url impossible

### ISSUE THREAD

**Issue by laurentdebricon** [woocommerce/woocommerce#29017]
**Describe the bug**
- have a multisite (i also ave wpml on one site) 
- setup one site A shop url slug /shop
- setup another site B shop url slug /shop
- when you access B/shop , you get redirected to A/shop !

(htaccess looks clean)

**Comment by rrennick** [comment]
Hi @laurentdebricon ,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

I used an internal multisite install where all sites have WC active with a `/shop/` page. All the shop pages are accessible. You may have an issue with caching. Or, if you recently created the multisite setup you may need to update your `.htaccess` with the multisite rewrite rules.

Please provide us with steps to reproduce your issue in another install which may help us to evaluate it further.

**Comment by laurentdebricon** [comment]
hey thank you, 

i disabled https://fr.wordpress.org/plugins/redis-cache/
and everything worked

then re-enabled it again.

and everything works. 
weird feeling of happiness without understanding what happened ...
