### ISSUE TITLE
Microdata issue when sending to Facebook Products

### ISSUE THREAD

**Issue by mircobabini** [woocommerce/woocommerce#29026]
When you use the JSON-LD for Schema.org, WooCommerce adds the @id param using the permalink + #product.

https://github.com/woocommerce/woocommerce/blob/e5a3ac48aa14d674ce041e9580c01278f461dc33/includes/class-wc-structured-data.php#L200

Even if not reported in [Facebook microdata guidelines](https://developers.facebook.com/docs/marketing-api/catalog/guides/microdata-tags), an hard limit exists on the @id field length (which is 100 chars accordingly to the [Facebook microdata debugger](https://business.facebook.com/ads/microdata/debug).

So, we should instead use `$product->get_id() . '#product` or any other shorter version of the identificator.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Because of this bug, Facebook is not connecting to Pixel on site to parse the WooCommerce products.

**Temporary solution**
This is the workaround: https://gist.github.com/mircobabini/38374f8c2e2ee466f2a6ce0f2d34364d

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Everything at its latest.

**Comment by jono-alderson** [comment]
Can you clarify where the 100 character limit is documented?

**Comment by mircobabini** [comment]
Nowhere afaik. But the limit comes out as an error when using the Facebook Catalog Sync validor. Do you need a screenshot as an evidence?

**Comment by jono-alderson** [comment]
A screenshot would be really helpful; concerned that it's going to cause some headaches for us in Yoast SEO!

**Comment by mircobabini** [comment]
This is the debugging tool: https://business.facebook.com/ads/microdata/debug

URL with the bug: [https://www.tecnoa.../to/](https://www.tecnoacademy.it/catalogo/corso-tetti-a-falda-e-coperture-piane-caratteristiche-a-confronto/)
URL patched: [https://www.tecnoa.../to/?ignore-fix-29026](https://www.tecnoacademy.it/catalogo/corso-tetti-a-falda-e-coperture-piane-caratteristiche-a-confronto/?ignore-fix-29026)

<img width="649" alt="Screenshot 2021-02-17 at 15 12 29" src="https://user-images.githubusercontent.com/636911/108216274-93fbfa80-7132-11eb-8940-ba2a357eb040.png">

I don't like headaches 🤢

**Comment by jono-alderson** [comment]
Ack. Thanks!

**Comment by vedanshujain** [comment]
Yeah, this is going to cause us headaches as well :) . Thanks for reporting the issue, we will look into it soon. BTW, have you seen backward compatibility problems with the suggested workaround, seems like changing ID from URL to db_id should cause duplicate products to be populated?

**Comment by mircobabini** [comment]
Thanks @vedanshujain, great to have your attention here. Yeah, think so. We had to clear the whole Facebook's catalog and push it once again after changes. Not a big deal for us but can be huge for others. Must make considerations about how to make it backward compatible for sure.

**Comment by vedanshujain** [comment]
I am closing this issue for repo maintenance, as there haven't been other reports about this (but in case that's incorrect would be happy to re-open and discuss). That said, if we are to make this change then we should:
1. Only change this for new sites. 
2. Provide a tool that can be run manually to change this for existing sites, with a link to document explaining the implications and how to modify the catalog in other sites.

**Comment by mircobabini** [comment]
@vedanshujain It's sad that I lost your attention on this matter.

The fact there are no other reports does not mean a lot in this case. You can review the whole process we made above, people is just using tiny urls OR not reporting this because:
- they don't take care of their data
- they don't notice that
- they don't know how to report that

Btw, for savvy people reading this: use this filter and fix it by yourself. `woocommerce_structured_data_product`

**Comment by vedanshujain** [comment]
@mircobabini your comment is fair! It's just that this is coming out to be at relatively less priority because of both other high-priority issues we have open at this time in repo that we are intending to fix, and the potential disruption while making change here.

As I said, happy to re-open, this is definitely an issue at this point and is nowhere near "completed" like the GH status reports.
