### ISSUE TITLE
Error - Can't activate woocommerce 4.9.2

### ISSUE THREAD

**Issue by f4ku123** [woocommerce/woocommerce#29022]
**Hi, i can't install woocommerce plugin. I tried installing it from the wordpress plugin store and uploading it myself but it shows always the same error when i try to activate the plugin.** 

`Fatal error: Uncaught TypeError: Unsupported operand types: int / string in C:\xampp\htdocs\xx\wp-content\plugins\woocommerce\includes\wc-core-functions.php:987 Stack trace: #0 C:\xampp\htdocs\xx\wp-content\plugins\woocommerce\includes\class-woocommerce.php(652): wc_get_image_size('thumbnail') #1 C:\xampp\htdocs\xx\wp-includes\class-wp-hook.php(287): WooCommerce->add_image_sizes('') #2 C:\xampp\htdocs\xx\wp-includes\class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #3 C:\xampp\htdocs\xx\wp-includes\plugin.php(484): WP_Hook->do_action(Array) #4 C:\xampp\htdocs\xx\wp-settings.php(557): do_action('init') #5 C:\xampp\htdocs\xx\wp-config.php(90): require_once('C:\\xampp\\htdocs...') #6 C:\xampp\htdocs\xx\wp-load.php(37): require_once('C:\\xampp\\htdocs...') #7 C:\xampp\htdocs\xx\wp-admin\admin.php(34): require_once('C:\\xampp\\htdocs...') #8 C:\xampp\htdocs\xx\wp-admin\plugins.php(10): require_once('C:\\xampp\\htdocs...') #9 {main} thrown in C:\xampp\htdocs\xx\wp-content\plugins\woocommerce\includes\wc-core-functions.php on line 987`

**I'm using the last version of xampp with PHP 8.0.1. Can someone help me?**

**Comment by f4ku123** [comment]
Never mind, i downgraded my php version to 7.4.14 and it works.

**Comment by EricBusch** [comment]
I was also getting the same error when trying to run WooCommerce 5.5.2 on PHP 8. 

I was getting this error:

```
PHP Fatal error:  Uncaught TypeError: Unsupported operand types: int / string in ~/wp-content/plugins/woocommerce/includes/wc-core-functions.php:987
```

It seemed to be related to this record in the `options` table:

```
45773	woocommerce_thumbnail_cropping	predefined	yes
```

I'm not sure how the `woocommerce_thumbnail_cropping` ever got set to `predefined` but that was not a value WooCommerce was expecting.

After I deleted that record from the  `options` table my WordPress / WooCommerce site ran fine on PHP 8.
