### ISSUE TITLE
API package: measure current execution speed of e2e tests that will benefit from API package improvements

### ISSUE THREAD

**Issue by lsinger** [woocommerce/woocommerce#29030]
To help us understand the effect of future improvements to the API package on the execution speed of our e2e test, we need to document a procedure for taking such measurements. 

From the project thread: 

> We’d like to shorten the time and effort required to create and execute end-to-end tests. While we don’t have any reliable measurements for creating tests, we can take a look at how long the end-to-end tests currently run in Travis CI. I’ll collect some data before the first project thread update and add it here. Let’s aim for an average reduction of 10% in running time for tests needing to create any of the objects this iteration of the API client is working on (see introduction above).

I did not manage to take those measurements in time. To do so, we need to do these things: 

- make a list of e2e tests that need to create products, orders, and coupons not as part of their testing but as part of their setup
- figure out a way to time the execution of just those tests on Travis CI (possibly use the average of, say, five test runs on identical code bases)
- document that procedure, e.g., on the project thread
- take the initial measurement (that is, before rewriting any of those tests to use the API package)
- document the initial measurement on the project thread

**Comment by zhongruige** [comment]
Results have been documented.

pcr5Cj-jW-p2
