### ISSUE TITLE
Update Cart e2e tests to show they cover flow Add Simple Product to Cart (from shop page)

### ISSUE THREAD

**Issue by tammullen** [woocommerce/woocommerce#29042]
Followup Issue to https://github.com/woocommerce/woocommerce/issues/27882

We want to have e2e test that covers the following Critical Flow

-  Add Simple Product to Cart (from shop page)

We currently use `addToCartFromShopPage` in the Cart tests but it isn't obvious looking at the results that we do this flow so I think we should update the test naming to better reflect this.

Current test naming.
```
  Cart page
    ✓ should display no item in the cart
    ✓ should add the product to the cart when "Add to cart" is clicked
    ✓ should increase item qty when "Add to cart" of the same product is clicked
    ...
```

**Comment by veljkho** [comment]
Changed title since I discovered its the best place to update the test in Cart page test.
