### ISSUE TITLE
Error in customizer with WooCommerce active (Using fresh TwentyTwenty and zero other plugins)

### ISSUE THREAD

**Issue by justanotherco** [woocommerce/woocommerce#29046]
Hi there,

Using TwentyTwenty and zero plugins active apart from WooCommerce - I get this JS error in the console:

```
jquery.js?ver=3.5.1:4046 jQuery.Deferred exception: wp.customize.selectiveRefresh.on is not a function TypeError: wp.customize.selectiveRefresh.on is not a function
    at HTMLDocument.<anonymous> (http://mysite.test/wp-content/plugins/woocommerce/assets/js/frontend/price-slider.js?ver=4.9.2:79:33)
```

**Comment by roykho** [comment]
Thanks for reporting @justanotherco - this is resolved in https://github.com/woocommerce/woocommerce/commit/5c76d8df59335118964b897d17978df5486c43c1 and will be going out soon.
