### ISSUE TITLE
Add JavaScript linter to pre-commit hook

### ISSUE THREAD

**Issue by zhongruige** [woocommerce/woocommerce#29056]
We want to add a JavaScript linter to the pre-commit hook so that it automatically formats and lints committed JavaScript files.

We can look at potentially using [Husky](https://github.com/typicode/husky) for triggering the pre-commit hook, and running Prettier.

Helpful documentation for this flow: [https://prettier.io/docs/en/precommit.html](https://prettier.io/docs/en/precommit.html)

**Comment by ObliviousHarmony** [comment]
It seems our repository already has this now :smile:
