### ISSUE TITLE
Missing theme parts on default themes

### ISSUE THREAD

**Issue by apollolux** [woocommerce/woocommerce#29075]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I had originally reported this [on the WooCommerce WP Plugins Support page](https://wordpress.org/support/topic/missing-template-parts-on-default-themes/) and was directed to report it here.

WP default themes such as Twenty Twenty are missing theme parts (particularly the footer widgets section) on WC-controlled pages using templates such as `woocommerce/templates/single-product.php` . While Cart, Checkout, and My Account simply create regular pages that contain WC shortcodes for embedding the specific functionalities, Shop and single product pages instead use WC’s built-in templates rather than leverage the active theme’s parts or checking for theme-specific part existence and falling back to built-in if missing, and do not leverage its existing theme-checking functionality to more closely replicate what the default themes actually do for theme template parts and such.

Using a default theme like Twenty Twenty, the result is some content (all non-WC and some WC) with proper loading of Twenty Twenty’s theme parts and some content (only WC) only loading Twenty Twenty’s header (`get_header`) and footer (`get_footer`) without realizing that Twenty Twenty puts its footer widgets and menu loading (`get_template_part( 'template-parts/footer-menus-widgets' )`) in the page templates, index.php, and singular.php, rather than in footer.php . Twenty Twenty’s index.php in particular also tries to load multiple other template parts that WC’s shop page template doesn’t account for. The Shop page in particular also no longer has the Template dropdown option in the Page Attributes meta box even though Twenty Twenty is still the active theme, but this portion of the bug will be filed separately as I haven't yet figured out where in WC's system to suggest adding back in the Template support.

I found that WC has basic functionality in place to check if a default theme is active, but as far as I can tell none of it is used in WC-specific templates to conditionally include theme-specific parts that are outside `header.php` and `footer.php` . Admittedly, it looks like Twenty Twenty seems to be the first default theme that has these theme parts loaded directly in the page templates rather than rolled into header or footer, and I haven't yet checked if Twenty Twenty One does the same thing or not.

**Expected behavior**
With a default theme such as Twenty Twenty active, all pages (both WC-controlled and non-WC controlled) properly load all template parts of the theme without needing to create theme-specific copies of WC's templates,

**Actual behavior**
Because some theme parts are not rolled into Twenty Twenty's header or footer, theme parts such as the footer widgets section do not get loaded on pages like Shop or item details with WC-controlled templates.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Activate a default theme such as Twenty Twenty or a child theme of such that doesn't have copies of WC-specific templates.
2. Activate WooCommerce and either assign an existing page as the Shop page or create a new one for such. Optionally, publish shop items as well.
3. Populate any footer widgets sidebar with any valid widget.
4. Visit the site as normal and see that the Shop page as well as any item detail pages do not load the footer widgets theme part.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Proposed Solution**
Right now, as a workaround the active child theme has two WC template overrides, `single-product.php` and `archive-product.php` , with only one line added each before `get_footer` to load the missing footer widgets theme part. Ultimately, these additions (simply the addition of `get_template_part( 'template-parts/footer-menus-widgets' );` right before `get_footer('shop');` in each of the templates) should be in the vanilla WC templates inside a conditional to check if the active theme is a default theme such as Twenty Twenty or a child of such. The default theme Twenty Twenty One may or may not also load theme template parts in a similar fashion, but I haven't yet personally checked to confirm.

**WordPress Environment**
Note: the active child theme has two WC template overrides, `single-product.php` and `archive-product.php` , with only one line added each before `get_footer` to load the missing footer widgets theme part.

<details>
### WordPress Environment ###

WordPress address (URL): https://neowraps.shop
Site address (URL): https://neowraps.shop
WC Version: 4.9.2
REST API Version: ✔ 4.9.2
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.8.3
Log Directory Writable: ✔
WP Version: ❌ 5.5.3 - There is a newer version of WordPress available (5.6.1)
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.12
PHP Post Max Size: 32 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.6.49-cll-lve
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.9.2
WC Database Prefix: wp_3_
Total Database Size: 2.91MB
Database Data Size: 2.56MB
Database Index Size: 0.35MB
wp_3_woocommerce_sessions: Data: 0.90MB + Index: 0.04MB + Engine MyISAM
wp_3_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_actionscheduler_actions: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wp_3_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_3_actionscheduler_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_cf7_vdata: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_cf7_vdata_entry: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_3_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_3_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_options: Data: 1.24MB + Index: 0.04MB + Engine MyISAM
wp_3_podsrel: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_postmeta: Data: 0.10MB + Index: 0.06MB + Engine MyISAM
wp_3_posts: Data: 0.19MB + Index: 0.03MB + Engine MyISAM
wp_3_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_3_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_3_term_relationships: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_3_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_wc_admin_notes: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_3_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_3_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_3_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_3_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_3_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_3_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_3_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_blogmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_blogs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_registration_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_signups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_site: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_sitemeta: Data: 0.11MB + Index: 0.01MB + Engine MyISAM
wp_usermeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM

### Post Type Counts ###

_pods_field: 3
_pods_pod: 3
_pods_template: 1
attachment: 27
custom_css: 1
flamingo_contact: 2
nav_menu_item: 5
page: 9
post: 2
product: 7
promo: 6
revision: 83
shop_coupon: 1
shop_order: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (12) ###

Honeypot for Contact Form 7: by Nocean – 1.14.1
Contact Form 7: by Takayuki Miyoshi – 5.3.2
Flamingo: by Takayuki Miyoshi – 2.2.1
Pods - Custom Content Types and Fields: by Pods Framework Team – 2.7.26
Safe SVG: by Daryll Doyle – 1.9.9
Theme Check: by Theme Review Team – 20200922.1
WooCommerce: by Automattic – 4.9.2
Classic Editor: by WordPress Contributors – 1.6
Health Check & Troubleshooting: by The WordPress.org community – 1.4.5
WordPress Importer: by wordpressdotorg – 0.7
Akismet Anti-Spam: by Automattic – 4.1.8
Advanced Editor Tools (previously TinyMCE Advanced): by Automattic – 5.5.1

### Inactive Plugins (18) ###

Advanced CF7 DB: by Vsourz Digital – 1.8.1
Check & Log Email: by WPChill – 1.0.1
Contact Form 7 Conditional Fields: by Jules Colle – 1.9.14
Contact Form 7 Multi-Step Forms: by Webhead LLC. – 4.1
Controls for Contact Form 7: by Kaspars Dambis – 0.8.0
Elegant Themes Updater: by Elegant Themes – 1.2
Elementor: by Elementor.com – 3.1.1
Enable jQuery Migrate Helper: by The WordPress Team – 1.3.0
Go Daddy Quick Setup: by GoDaddy.com
LLC – 1.04

Hello Dolly: by Matt Mullenweg – 1.7.2
Query Monitor: by John Blackbourn – 3.6.7
Simple Contact form 7 Wizard Multisteps Form: by Junaid Bhatti – 1.0.3
The SEO Framework: by The SEO Framework Team – 4.1.3
Welcome to WordPress: by Starfield Technologies – 1.0
WP Crontrol: by John Blackbourn & crontributors – 1.9.0
WP Mail SMTP: by WPForms – 2.6.0
WP Super Cache: by Automattic – 1.7.1
Yoast SEO: by Team Yoast – 15.7

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: NW
Version: 1.0
Author URL: https://neowraps.shop
Child Theme: ✔
Parent Theme Name: Twenty Twenty
Parent Theme Version: 1.6
Parent Theme Author URL: https://wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: nw/woocommerce/archive-product.php
nw/woocommerce/emails/admin-cancelled-order.php
nw/woocommerce/emails/admin-failed-order.php
nw/woocommerce/emails/admin-new-order.php
nw/woocommerce/emails/customer-completed-order.php
nw/woocommerce/emails/customer-invoice.php
nw/woocommerce/emails/customer-new-account.php
nw/woocommerce/emails/customer-note.php
nw/woocommerce/emails/customer-on-hold-order.php
nw/woocommerce/emails/customer-processing-order.php
nw/woocommerce/emails/customer-refunded-order.php
nw/woocommerce/emails/customer-reset-password.php
nw/woocommerce/single-product.php

### Action Scheduler ###

</details>

**Comment by tammullen** [comment]
Hi @apollolux 

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end for the **Twenty Twenty** theme. 
​
![Screenshot 2021-02-11 at 17 30 09](https://user-images.githubusercontent.com/24649833/107676846-81487800-6c91-11eb-8226-5de4a8005011.png)
Populated Footer

When I use Twenty Twenty theme I don't see the footer.
![screencapture-firm-corncrake-jurassic-ninja-shop-2021-02-11-17_52_25](https://user-images.githubusercontent.com/24649833/107677599-5c083980-6c92-11eb-81d6-a40fc5cbd6a7.png)


However I do see the Footer with **Twenty Twenty One, Twenty Nineteen** and **Storefront** themes

![screencapture-firm-corncrake-jurassic-ninja-shop-2021-02-11-17_46_07](https://user-images.githubusercontent.com/24649833/107677681-72ae9080-6c92-11eb-9628-5850d0d7b02d.png)
![screencapture-firm-corncrake-jurassic-ninja-shop-2021-02-11-17_47_23](https://user-images.githubusercontent.com/24649833/107677697-76daae00-6c92-11eb-88af-92d5f65c4898.png)
![screencapture-firm-corncrake-jurassic-ninja-shop-2021-02-11-17_54_14](https://user-images.githubusercontent.com/24649833/107677711-79d59e80-6c92-11eb-808d-f510f9afc4bf.png)

​
We’re going to solve this bug as soon as possible. Stay tuned for updates.

**Comment by hsingyuc** [comment]
The sidebar got removed and couldn't find out why through the PR, is there any reason? Do we delete the `remove_action`?
https://github.com/woocommerce/woocommerce/blob/6fae8ca40b6e89ed97b3c55583e12273e8a0cdc7/includes/theme-support/class-wc-twenty-twenty.php#L31

**Comment by tomalec** [comment]
This issue affects also some WC extensions, as well as the merchants who cloned the templates (like suggested in [extension's docs](https://woocommerce.com/document/automated-follow-up-emails-docs/faq/#section-22)), it would be nice to have a migration guide for those as well.

**Comment by nerrad** [comment]
I'm going to close this now that WooCommerce ships with block templates. The reported issues should no longer apply. However, if there are still issues, please create a new issue. Thanks!
