### ISSUE TITLE
PHP8 Uncaught TypeError: Unsupported operand types: string + string

### ISSUE THREAD

**Issue by Spreeuw** [woocommerce/woocommerce#29087]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When trying to save an order in PHP 8.0 (in WC5.0) I get the following error:

Fatal error: Uncaught TypeError: Unsupported operand types: string + string in wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php:1588

> Stack trace:
> 0 wp-content/plugins/woocommerce/includes/admin/wc-admin-functions.php(414): WC_Abstract_Order->update_taxes()
> 1 wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-items.php(54): wc_save_order_items(1146, Array)
> 2 wp-includes/class-wp-hook.php(289): WC_Meta_Box_Order_Items::save(1146)
> 3 wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
> 4 wp-includes/plugin.php(484): WP_Hook->do_action(Array)
> 5 wp-content/plugins/woocommerce/includes/admin/class-wc-admin-meta-boxes.php(220): do_action('woocommerce_pro...', 1146, Object(WP_Post))
> 6 wp-includes/class-wp-hook.php(289): WC_Admin_Meta_Boxes->save_meta_boxes(1146, Object(WP_Post))
> 7 wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
> 8 wp-includes/plugin.php(484): WP_Hook->do_action(Array)
> 9 wp-includes/post.php(4309): do_action('save_post', 1146, Object(WP_Post), true)
> 10 wp-includes/post.php(4411): wp_insert_post(Array, false, true)
> 11 wp-admin/includes/post.php(419): wp_update_post(Array)
> 12 wp-admin/post.php(227): edit_post()
> 13 {main} thrown in wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php on line 1588

https://github.com/woocommerce/woocommerce/blob/66a1c169f749a03e090cf66c6ee032580dcdf424/includes/abstracts/abstract-wc-order.php#L1588

**Expected behavior**
tax calculatiosn should not use strings
value should be cast/converted to float here:
https://github.com/woocommerce/woocommerce/blob/c15488d8402d149a1a6551d73057d31a0730bddb/includes/traits/trait-wc-item-totals.php#L84-L89

**Actual behavior**
see error

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Enable the Tax option Rounding - Round tax at subtotal level, instead of rounding per line
2. Go to order
3. Save order

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by roykho** [comment]
Hi @Spreeuw - thanks for reporting this. I can confirm I was able to reproduce this. We will fix this by the next release.

**Comment by Spreeuw** [comment]
@roykho Since this breaks saving orders, maybe prioritize for 5.0.1?
