### ISSUE TITLE
Allow theme JS to override the default empty variation error function

### ISSUE THREAD

**Issue by pojke** [woocommerce/woocommerce#29080]
Unless I'm missing something there's no way of overriding in your own theme this prototype since VariationForm is a local variable:
https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/add-to-cart-variation.js#L125

Is it viable to create jQuery prototype $.fn to access that local prototype so theme creator can replace alert with something else? 
Happy to create a patch (again unless I missed how to access it?!)

**Comment by pcfreak30** [comment]
I just hit a similar issue thats forcing me to fork the file as I need to change behavior and I cannot modify the prototype.

The "class" should be exposed.

**Comment by vedanshujain** [comment]
@pojke @pcfreak30 Are you able to use the `wc_variation_form` trigger which is [somewhat above the line you linked](https://github.com/woocommerce/woocommerce/blob/master/assets/js/frontend/add-to-cart-variation.js#L46)? It should give you access to the form object and modify the function prop. 

If it's not usable, then we would be happy to review PR towards making it easier in modifying this behavior.

**Comment by pcfreak30** [comment]
@vedanshujain I would consider that a hack as I feel it is a bad practice to modify an object's prototype after creating the object if there's a better way. Plus that jquery hook is inside a timer which I also think would be problematic.
