### ISSUE TITLE
Fatal error on the Reports page after 5.0.0 update

### ISSUE THREAD

**Issue by ospiotr** [woocommerce/woocommerce#29096]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

Caused by #28799

I am using an [official WooCommerce filter](https://woocommerce.wp-a2z.org/oik_hook/woocommerce_admin_disabled/) to disable WooCommerce Admin in my site:
`add_filter( 'woocommerce_admin_disabled', '__return_true' );`

After updating to WooCommerce 5.0, there is a fatal error on Reports page (the classic old reports):

`Uncaught Error: Call to undefined function wc_admin_url() in /wp-content/plugins/woocommerce/includes/admin/views/html-admin-page-reports.php:17`

**Steps to reproduce the bug**
1. Use fresh WooCommerce 5.0 installation
2. Disable WC Admin using an [official WooCommerce filter](https://woocommerce.wp-a2z.org/oik_hook/woocommerce_admin_disabled/) 
3. Go to old Reports page
4. Fatal error happens

**Screenshots**
![image](https://user-images.githubusercontent.com/27012265/107584638-1baaac00-6bfd-11eb-9ecc-84f23c56aac7.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

WC Version: 5.0.0
WP Version: 5.6.1
PHP Version: 7.4.12

**Comment by roykho** [comment]
Thanks for reporting. Fixed here https://github.com/woocommerce/woocommerce/commit/315c4de5c3270cfeea9cb2bf6da9d58e09d4250d

**Comment by kanlukasz** [comment]
When will you release this patch?

**Comment by dcx15** [comment]
Fixed 17 days ago, but still not available. Any news on when 5.0.1 might be pushed live?

**Comment by superbmario** [comment]
I'm guessing this won't make it into a 5.0.1 and we should expect a fix in 5.1.0 on 8th March?

**Comment by roykho** [comment]
Yes so the fix will be apart of the 5.1 version release slated to go out on March 9th. Sorry for the inconvenience.
