### ISSUE TITLE
[Spike] Analyze the database operations on orders and the way they might fail

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#29090]
As raised in https://github.com/woocommerce/woocommerce/issues/29027, there are gaps in how WC handles database operations. Lots of times, the return value from the db operation is not checked. 

We've decided to dedicate 4 days to a research spike on this topic. The main focus is on operations with _orders_ (and _refunds_) and the desired outcome is a _proposal on how to approach the implementation of a fix_ that spans multiple layers of the application (from the CRUD layer to UX when the operation fails). 

We need to take into account also WC Blocks, WC Admin and REST API and their use cases. 

Timebox: 4 days

**Comment by barryhughes** [comment]
Internal ref: p7bje6-3gZ-p2 | Summary:

- We'll tackle the specific cases in the linked issue
- We've identified a number of other locations needing review
- We're discussing tooling changes, etc, to mitigate this going forward
