### ISSUE TITLE
Request to /wc/store/cart blocked by CORS due to "Request header field x-wc-store-api-nonce is not allowed by Access-Control-Allow-Headers in preflight response."

### ISSUE THREAD

**Issue by joaojuicee** [woocommerce/woocommerce#29116]
I'm building a vue app that will connect to the woocommerce API which is hosted in a different domain than the WP application.
The wordpress application is using https with a valid certificate and ist running under the `lemon-wp.test` domain while the vue app is running on `localhost`.

I'm making a request to `/wp-json/wc/store/cart/add-item` with the requested `X-WC-Store-API-Nonce` header which has a valid token that I have generated via a custom endpoint using `wp_create_nonce('wc_store_api')`, however I keep getting blocked by CORS, here's the network error:

`Access to XMLHttpRequest at 'https://lemon-wp.test/wp-json/wc/store/cart/add-item' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field x-wc-store-api-nonce is not allowed by Access-Control-Allow-Headers in preflight response.`

The preflight request goes through but seems to be coming back with some errors from woocommerce, here's a dump of the response headers to the request sent by woocommerce:

```
access-control-allow-credentials: true
access-control-allow-headers: Authorization, X-WP-Nonce, Content-Disposition, Content-MD5, Content-Type
access-control-allow-methods: OPTIONS, GET, POST, PUT, PATCH, DELETE
access-control-allow-origin: http://localhost:3000
access-control-expose-headers: X-WP-Total, X-WP-TotalPages, Link
allow: POST
content-encoding: gzip
content-type: application/json; charset=UTF-8
date: Tue, 09 Feb 2021 00:23:52 GMT
link: <https://lemon-wp.test/wp-json/>; rel="https://api.w.org/"
server: nginx/1.19.6
vary: Accept-Encoding
vary: Origin
x-content-type-options: nosniff
x-powered-by: PHP/7.3.27
x-robots-tag: noindex
x-wp-doingitwrong: register_rest_route (since 5.5.0; The REST API route definition for <code>api/wc-nonce</code> is missing the required <code>permission_callback</code> argument. For REST API routes that are intended to be public, use <code>__return_true</code> as the permission callback.)
```

## To reproduce

1.  Install latest WP and Woocommerce
2. on your theme's functions.php file add the following code:
```
add_action('rest_api_init', function () {
	register_rest_route('api/', 'wc-nonce', array(
		'methods'  => 'GET',
		'callback' => 'generate_wc_nonce'
	));
});

function generate_wc_nonce($request)
{

	$response = new WP_REST_Response(wp_create_nonce('wc_store_api'));
	$response->set_status(200);

	return $response;
}
```
3. On any application make an axios request to: `https://<your_wp_domain>/api/wc-nonce`
4. Save the response somewhere in your code
5. Make a post request to woocommerce and make sure you include the `X-WC-Store-API-Nonce` header

## Expected behavior
I should be able to make the request being that I'm providing the required header, it doesn't make sense that the API doesn't accept the header if you're able to hit the endpoint.

## Screenshots
[Request headers and data](https://ibb.co/3NYP0Vx)
[CORS error](https://ibb.co/McnV4Vc)
[Woocommerce reponse to preflight](https://ibb.co/LtmB6Wc)

### WordPress (please complete the following information):
* Core version: 5.7-beta1-50232
* WooCommerce version: Version 4.9.2
* Any other plugins installed: 

- Jetpack by WordPress.com (Ver. 9.4)
- Hello Dolly (Ver. 1.7.2)
- WooCommerce Shipping & Tax (1.25.6)

### Desktop (please complete the following information):
* OS: macOS
* Browser: chrome
* Version 88.0.4324.146 (Official Build) (x86_64)

## Additional context
Was able to make the same request via Postman

**Comment by seb86** [comment]
The store API is designed for internal use. Your better of using CoCart which is designed for headless applications and supports CORS. No need for passing a NONCE header either.

**Comment by joaojuicee** [comment]
CoCart is payed, and why the hell would you expose an API and leave out one of the main features of an e-commerce... the cart? just baffles me.
I was able to create an express app within the same domain as my WP website, the purpose of this node app is be the middleman between my client and the Woocommerce API, thus far I was able to successfully make the request above by doing:

Client -> Node endpoint -> WC

The issue that I'm facing is that the endpoint `/wp-json/wc/store/cart/` seems to return a `Set-Cookie` header which I cannot capture with axios, therefore rendering it useless because I can't keep track of the cart.

Someone reference the ability to set my own cart session Id, but I find 0 references to this anywhere

**Comment by seb86** [comment]
@joaojuicee If you bothered to research you would see that the core of CoCart which has the cart API feature is in the [WordPress plugin directory](https://wordpress.org/plugins/cart-rest-api-for-woocommerce/).

I also have a [JS Library](https://github.com/co-cart/cocart-js-lib) that supports the use of Axios.

If you have any further questions you can [contact me](https://cocart.xyz/contact/) via the CoCart website.

**Comment by joaojuicee** [comment]
> JS Library

I did research lol https://cocart.xyz/pro/#pricing and as I said, makes no sense to not expose the cart on the API and instead force you to use a 3rd party plugin

**Comment by seb86** [comment]
🤦‍♂️ Not lol. That is CoCart Pro price page. I said the core of CoCart is on the WP.org plugin directory. Meaning FREE!!! https://wordpress.org/plugins/cart-rest-api-for-woocommerce/

Never mind. If you don't want to use third party that's fine. Just trying to provide you a working solution.

**Comment by jonathansadowski** [comment]
@joaojuicee, it looks like you may have found another solution that works, but I also wanted to point you towards [rest_allowed_cors_headers](https://developer.wordpress.org/reference/hooks/rest_allowed_cors_headers/). Adding `X-WC-Store-API-Nonce` to the allowed headers provided by that filter should get you past the issue you were having.

I'm going to close this issue, please let us know if you think there's some other bug that we are missing.

**Comment by hellobrunao** [comment]
Hey @joaojuicee I have walked on the same path that you have, until getting stuck on not being able to read and send the woocommerce cookies related to the cart. I am also doing the request via axios.

Did you manage to get the cookies and send it along with the request? Could you explain me the solution you got?

Thank you.

**Comment by balindenberg** [comment]
Also facing the same issue. Grabbing products works fine and adding works fine from local API client with the nonce header, but can't get it to work on frontend. Same CORS issue. Any luck?
