### ISSUE TITLE
CSS variables contain scss variables instead of real values

### ISSUE THREAD

**Issue by stodorovic** [woocommerce/woocommerce#29119]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

The **:root** CSS pseudo-class still contains SCSS code. I've checked _woocommerce-smallscreen.css_, _woocommerce-layout.css_, _woocommerce.css_.
Example:
```
$ curl -s https://woocommerce.com/wp-content/plugins/woocommerce/assets/css/woocommerce-layout.css |head -c 400
@charset "UTF-8";:root{--woocommerce:$woocommerce;--wc-green:$green;--wc-red:$red;--wc-orange:$orange;--wc-blue:$blue;--wc-primary:$primary;--wc-primary-text:$primarytext;--wc-secondary:$secondary;--wc-secondary-text:$secondarytext;--wc-highlight:$highlight;--wc-highligh-text:$highlightext;--wc-content-bg:$contentbg;--wc-subtext:$subtext}.woocommerce .woocommerce-error .button,.woocommerce .woocom
```
I've tried to compile scss files (CentOS 7.9). It works correctly:
```
[sasa@server css]$ sassc -t compressed woocommerce.scss |head -c 350
:root{--woocommerce:#a46497;--wc-green:#7ad03a;--wc-red:#a00;--wc-orange:#ffba00;--wc-blue:#2ea2cc;--wc-primary:#a46497;--wc-primary-text:#fff;--wc-secondary:#ebe9eb;--wc-secondary-text:#515151;--wc-highlight:#77a464;--wc-highligh-text:#fff;--wc-content-bg:#fff;--wc-subtext:#767676}@keyframes spin{100%{transform:rotate(360deg)}}@font-face{font-f
```
**Expected behavior**
Correct CSS files without errors.

**Screenshots**
![wc5-css-errors](https://user-images.githubusercontent.com/15647032/107829930-05325b00-6d8b-11eb-9321-1724ef022916.png)

Related: #28707

**Comment by roykho** [comment]
Yeah apparently it's because of the SASS versions as documented here https://sass-lang.com/documentation/breaking-changes/css-vars

We need to wrap it in this `--accent-color-right: #{$accent-color};` PR incoming.
