### ISSUE TITLE
Incorrect func_get_arg() request in get_product_data()

### ISSUE THREAD

**Issue by fabregas4** [woocommerce/woocommerce#29124]
In woocommerce/includes/rest-api/Controllers/Version2/class-wc-rest-products-v2-controller.php
Line 643

The code is:
` $request = func_num_args() >= 2 ? func_get_arg( 2 ) : new WP_REST_Request( '', '', array( 'context' => $context ) );`

If the function has 2 arguments, you need to use func_get_arg(0) to get the first one, and func_get_arg(1) to get the second one.

func_get_arg(2) fails with "Warning</b>:  func_get_arg():  Argument 2 not passed to function"

Seeing this error in a WC Bookings request such as:
/wp-json/wc-bookings/v1/products/4421

The error is in WC though, not WC Bookings. It shouldn't check for 2 or more args then set the value of $request to the 3rd argument. I believe the code should be changed to func_get_arg(1).

**Comment by barryhughes** [comment]
Thanks for this report!

> The error is in WC though, not WC Bookings. It shouldn't check for 2 or more args then set the value of $request to the 3rd argument. I believe the code should be changed to func_get_arg(1).

Almost, though I think that call is correct and the change we need is in the comparison (we should change from `func_num_args() >= 2` to `func_num_args() >= 3`).

:memo: This also surfaced this week via 3963288-zd-woothemes (internal ref).

**Comment by fabregas4** [comment]
That makes sense. I didn't dig that deep into it at the time, but I can see now that the function can accept a request object silently, which is the reason for the line of code in question.
