### ISSUE TITLE
Make held stock inventory more visible to merchant.

### ISSUE THREAD

**Issue by vedanshujain** [woocommerce/woocommerce#29132]
**Is your feature request related to a problem? Please describe.**
We held stock for when user check out with product and payment is not yet completed. The stock is held and cannot be used unless payment is completed (which reduces the stock), or if the order is cancelled (which increases the stock).

A small enhancement, like adding in order note that "Stock is held for X minutes for payment" will go a long way and make it transparent for merchant. Most likely, this notes addition will make sense inside `wc_reserve_stock_for_order` function after stock reserve operation is successful.

In the product edit window, a non editable meta box displaying held stock quantity will also be very helpful, but optional. 

**Additional context**
See issue https://github.com/woocommerce/woocommerce/issues/26652

**Comment by floyedxman** [comment]
is it solved yet ?

**Comment by nerrad** [comment]
Will be good to implement in a way that can be consumed by the new Cart and Checkout Blocks flow as well.

**Comment by Abdalsalaam** [comment]
@vedanshujain I would like to work on this

**Comment by vedanshujain** [comment]
@Abdalsalaam sure, feel free to take it up. let us know if you need any help
