### ISSUE TITLE
Question about the latest update available

### ISSUE THREAD

**Issue by stefanos82** [woocommerce/woocommerce#29144]
I haven't worked on any website for a couple of months now and today I decided to check for updates.

When I started the procedure, `Debug Bar` complained about slowness on my system while updating WooCommerce to its latest version: `https://plugins.svn.wordpress.org/woocommerce/trunk/readme.txt`.

Should not it point to `https://plugins.svn.wordpress.org/woocommerce/tags/5.0.0/readme.txt` instead?

Is this the expected behavior?

**Comment by claudiosanches** [comment]
Hello @stefanos82 

Trunk and `tags/5.0.0` share the same code now, so this is the expected behavior, also is WordPress that manages it.

I'm closing this this questions isn't related to WooCommerce.
