### ISSUE TITLE
[GlobalStep - WooCommerce 5.1 Beta 1] Widgets header are overlapping under Appearance > Widgets Screen.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#29157]
## Bug Description:
Widgets header are overlapping under Appearance > Widgets Screen.

## Environment:
Windows 10, macOS High Sierra v10.13.6
Browser: Chrome(Version 88.0.4324.104) (64-bit)
                Firefox(Version 83.0)(64-bit)
                Safari: v13.1.2(13609.3.5.1.5)

## Steps To Reproduce:
1. Create any test site using Jurassic Ninja.
1. Install and activate all the required plugins
1. Complete the Onboarding setup wizard.
1. Install and activate "Gutenberg" feature plugin.
1. Go to Appearance > Widgets.
1. Observe that widgets header are overlapping under Appearance > Widgets page

## Actual Result:
Widgets header are overlapping under Appearance > Widgets page

## Expected Result:
Widgets header should display correctly under Appearance > Widgets page

## Screenshot:

![#29157](https://user-images.githubusercontent.com/41110392/108237056-89128b80-716d-11eb-8c8c-cdbf24144395.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by nerrad** [comment]
This is a GB issue and [reported here](https://github.com/WordPress/gutenberg/issues/26221). I recommend closing.

**Comment by zhongruige** [comment]
Thank you for reporting the issue @gglobalstep. However, this issue had been reported previously as noted by @nerrad above. We are closing this issue in favor of the previously reported issue. Please continue sharing your feedback there if needed. Thank you!
