### ISSUE TITLE
Replace float-based CSS layouts with Flexbox

### ISSUE THREAD

**Issue by mrleemon** [woocommerce/woocommerce#29152]
**Is your feature request related to a problem? Please describe.**

Float-based layouts are outdated and a pain to work with

**Describe the solution you'd like**

Any components in WooCommerce using floats for creating layouts should be updated to use CSS Flexbox instead. Flexbox is now widely supported. The Flexbox module aims at providing a more efficient way to layout, align and distribute space among items in a container, even when their size is unknown and/or dynamic.

**Comment by ObliviousHarmony** [comment]
Hi @mrleemon,

Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the `votes needed` label and evaluate over time if this issue collects more feedback. 

Don’t be alarmed if you don’t see any activity on this issue for a while.

**Comment by perrelet** [comment]
Wow.
