### ISSUE TITLE
WP 5.6.1 Select2 issue

### ISSUE THREAD

**Issue by wayheming** [woocommerce/woocommerce#29163]
Hello,
Clean WP without plugins and with storefront theme.

**Describe the bug**
With wp 5.6.1 select2 in widget does not work correctly

**Expected behavior**
https://gyazo.com/8b60e22b1d0025767e4838c701c5cba4 WP 4.5.0

**Actual behavior**
https://gyazo.com/3756abc6c8649153cf273bd522d2e0c4 WP 5.6.1

**Comment by rajeshsingh520** [comment]
Hi,

We have also faced this issue it started when Wordpress shifted to jquery 3.5.1

The issue happens when there is margin-top persent on the root html element

which generally happens when you have Admin bar on the page

we where able to temporary fix the issue by putting 

```
html {
    margin-top: 0 !important;
}
```

**Comment by roykho** [comment]
Possibly related to https://github.com/woocommerce/woocommerce/issues/28996

**Comment by roykho** [comment]
Hi @wayheming - thanks for reporting. I am able to reproduce this issue. When navigating to the frontend as an admin with the toolbar enabled, I am unable to select the second item on the dropdown of the Product Filter widget which uses Select2 dropdowns.

![](https://d.pr/i/50OhXo+)

**Comment by wayheming** [comment]
@roykho Thank you
