### ISSUE TITLE
Actionscheduler Problem with Old Websites

### ISSUE THREAD

**Issue by Dealazer** [woocommerce/woocommerce#29176]
If you get actionscheduler error when using woocomerce 3 or lower and upgrade to 4+

You will have to create 1 new wordpress and install any version woocommerce 4+.

All 4 actionsheduler_ tables that are needed are not available. Because of some error as telling woocommerce they exist or already are. For some giving permission to the database user might work. For those unable to fix this, do this:

You will have to do it manually by creating a new WordPress page, and then copy the same tables in phpMyAdmin into the webpage you use.

There is need of 4 typical actionscheduler tables to be copied.

You might need to use the wp_ table prefix name for your old website. Unless other is specified.

There is no easy way around and most have this problem with woocommerce-admin plugin no longer in use.

There is no plugin yet, to solve the problem to inject new tables but let's hope this will become additional plugin to use for old users of wordpress. Just calling the action to initiate will cost dearly making woocommerce slow.

**Comment by jonathansadowski** [comment]
Hi @Dealazer, thanks for your report! It looks like this might be related to the issue described in https://github.com/woocommerce/action-scheduler/issues/653, so I'm going to close this in favor of that issue. If it is related, and you have any more information to add, please add it in the comments of that issue, or if you think it's a separate issue, feel free to reply again here.
