### ISSUE TITLE
Reduce the number of environment differences of discrepancy between local setup and CI. 

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#29180]
Explore the possibility of running another Docker container with npm env within the existing Docker container to reduce the number of environment differences between local setup and Travis CI. 

This should help to make sure that testing environments are identical locally and on CI which in turn should help to eliminate test flakiness as much as possible.

**Comment by rrennick** [comment]
I'm going to have a look at TeamCity as an alternative to a local environment.

**Comment by tammullen** [comment]
Closing as we use same commands and setup locally and in CI
