### ISSUE TITLE
Fatal Error when marketing hub and woocommerce admin dashboard disabled

### ISSUE THREAD

**Issue by hamidrezayazdani** [woocommerce/woocommerce#29188]
Hi, I updated Woocommerce last night, while viewing sales reports, a fatal error is displayed because I have disabled the **Marketing hub** and **Woocommerce Admin Dashboard** with the following code by `mu-plugins`:

```
add_filter( 'woocommerce_marketing_menu_items', '__return_empty_array' );
add_filter( 'woocommerce_admin_disabled', '__return_true' );
```

**Error log:**

> [22-Feb-2021 09:12:47 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function wc_admin_url() in /home/my-domain/public_html/wp-content/plugins/woocommerce/includes/admin/views/html-admin-page-reports.php:17
> Stack trace:
> #0 /home/my-domain/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-reports.php(36): include_once()
> #1 /home/my-domain/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-menus.php(264): WC_Admin_Reports::output()
> #2 /home/my-domain/public_html/wp-includes/class-wp-hook.php(287): WC_Admin_Menus->reports_page('')
> #3 /home/my-domain/public_html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
> #4 /home/my-domain/public_html/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
> #5 /home/my-domain/public_html/wp-admin/admin.php(259): do_action('%d9%88%d9%88%da...')
> #6 {main}
>   thrown in /home/my-domain/public_html/wp-content/plugins/woocommerce/includes/admin/views/html-admin-page-reports.php on line 17
> 

**Reason for error:**
The `wc_admin_url `variable is not defined when the Woocommerce admin dashboard is disabled.

**Screenshots**
![Screenshot_2021-02-22](https://user-images.githubusercontent.com/40775953/108695445-8de09200-7515-11eb-8f2b-c0dfdefa3c2a.png)

**WordPress Environment**
Wordpress version: 5.6.1
Woocommerce version: 5.0.0

**Comment by roykho** [comment]
Hi @hamidrezayazdani - Yes we're aware of this issue. It affects people who have WC Admin disabled with a code snippet filter or with a plugin. This has already been fixed and will be going out in the next release.

In the meantime a work around solution is to either re-enable WC Admin or you can use this code snippet temporarily.

```
if ( ! function_exists( 'wc_admin_url') ) {
	function wc_admin_url( $path ) {
		return '#';
	}

        class WC_Notes_Run_Db_Update {}
}
```

I will be closing this for now as it is already fixed but feel free to comment on it if anything related that is still not working correctly.
