### ISSUE TITLE
5.0.0: after 4.8.2 upgrade, WC_REST_Orders_V2_Controller::get_formatted_item_data() crashes in `$order->get_refunds()` loop

### ISSUE THREAD

**Issue by lkraav** [woocommerce/woocommerce#29193]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

https://github.com/woocommerce/woocommerce/issues?q=is%3Aissue+get_refunds does not return any recent results.

**Describe the bug**
There are no other obviously related changes in the system, crashing started immediately after updating WC 4.8.2 -> 5.0.0 today.

Incident occurs during building WC Webhook payload in a WP CLI cron session.

Sentry traceback https://sentry.io/share/issue/e345ba9d76c0460c8cf7e3fdd1a2b99b/

It does look like this method had a recent refactor `git diff 4.8.0..5.0.0 -- includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php`

**Expected behavior**
Not crash.

**Actual behavior**
See bug description.

I'm currently trying to workaround Fatal with `is_callable $refund 'get_id'`.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Not entirely sure (yet) what data structure have to be set up.

**Screenshots**
N/A

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

N/A this platform is live, cannot disable anything.

**WordPress Environment**
<details>
WP 5.6.1
WC 5.0.0
</details>

Sentry traceback should be enough proof that no other plugin codepath is involved here.

**Comment by lkraav** [comment]
Some refund display thing also crashes in templates, very similar `foreach()` loop signature.

Traceback https://sentry.io/share/issue/e36df3fe9a1c488f9c33384177122d7e/

**Comment by lkraav** [comment]
And crashes also in `WC_Order::add_order_item_totals_refund_rows()`

Traceback https://sentry.io/share/issue/a35b25fae495450484bb768b3086ad51/

This makes me thing `WC_Order::get_refunds()` is broken.

**Comment by lkraav** [comment]
> This makes me think `WC_Order::get_refunds()` is broken.

It's still my primary hypothesis, but it seems to be connected to object caching.

Today, I had a crash in Orders list, where `WC_Order::get_refunds()` returned `false` again https://sentry.io/share/issue/53434b17f6324b9a9032cdc6b8477c77/

But then, on simple page reload, it magically worked.

**Comment by vedanshujain** [comment]
We did have a recent change and are [setting refund caches in another data store](https://github.com/woocommerce/woocommerce/blob/trunk/includes/data-stores/class-wc-order-data-store-cpt.php#L975), perhaps that could be related.

We tried reproducing this a bit but were not able to. Can you look if you can find something in this new code path as well? Seems like `get_refunds` is returning `array( false )` for some reason? Maybe a cache plugin is interfering?

**Comment by lkraav** [comment]
I monkey-patched all `get_refunds()` calls on live server with an extra sanity check, and managed to eliminate crashes.

I'll find out what values are returned next.
