### ISSUE TITLE
is_product() should operate similar to is_page()

### ISSUE THREAD

**Issue by adampatterson** [woocommerce/woocommerce#29192]
**Is your feature request related to a problem? Please describe.**
I needed to enqueue a script on a specific single product, my instinct was to use `is_product('product')` as you would `is_page('page')` but `is_product()` only returns `bool`.

**Describe the solution you'd like**
```
is_product() // True or False
is_product('product') // True or False
```

**Describe alternatives you've considered**
Short of reading the URL and attempting to determine if the URL contains the product slug I was not able to find a clean way of enqueuing my script.

I could find the post ID and hard code them into my theme, but the slug wont change in by local, staging, and live environments.

**Comment by StSaens** [comment]
I do the same. 
If you do is_page(product-id) it should work. I use this to enqueue certain scripts on specific product pages. Where the product-id is the same as the page of the product (when editing the product-page)

is_product = woo function
is_page = wordpress function

**Comment by rrennick** [comment]
@adampatterson You can use `is_single( {product-id} )` to determine if it's a particular product. Like `is_page`, `is_single` supports an array of values.

**Comment by vedanshujain** [comment]
I am closing this issue as the workaround suggested would work. But feel free to reply back if that is not the case.

**Comment by adampatterson** [comment]
It does work, but it also requires creating the product on a live, staging, or local environment before testing the code.

It's not ideal for anything that might be distributed.
