### ISSUE TITLE
Deprecated Reports notice gives the wrong message to an entire ecosystem

### ISSUE THREAD

**Issue by franticpsyx** [woocommerce/woocommerce#29197]
Not a bug -- please let me know if this should be posted somewhere else :)

Since WooCommerce 5.0, users who enter the Reports section are greeted with this message:

> With the release of WooCommerce 4.0, these reports are being replaced. There is a new and better Analytics section available for users running WordPress 5.3+. Head on over to the WooCommerce Analytics or learn more about the new experience in the WooCommerce Analytics documentation.

Showing this message on the entire Reports section misses the fact that third parties have been adding tabs/reports there for a long time now: Some of the reports added by third parties may not necessary fit well into the "Analytics" description, and would have no reason to move from where they are now.

Additionally, those developers who want to move their old reports under the Analytics section currently have a huge barrier of entry, as:

* There are no examples of official WooCommerce plugins that have transitioned from the "legacy" Reports to the new Analytics section. To my knowledge, flagship products such as WC Subscriptions still use the old Reports. In ecosystems like ours, it is vital that new coding paradigms and features based on new code/technology are evaluated from an extensibility perspective. A good way to do this is to migrate existing features from the plugins ecosystem to utilize the new codebase, pretty much like what was done in time for WooCommerce 3.0 (data stores) a few years ago. This is especially helpful when introducing new tech :)
* The existing documentation is not as empowering as it could be, considering the higher barrier of entry that new technology comes with. Lack of detailed documentation and examples means that even developers with previous experience in React are having a hard time figuring out how to extend core.

Summing up:

* The current notice suggests that Reports will be removed completely in the future. It might have been better to either remove those core Reports pages/tabs that are mirrored in the Analytics section, or to show that notice when viewing those Reports only.
* The Reports section could perhaps stay in core for those who have no better alternatives for showing "report-related" content, and/or all those developers who are not able to migrate their own report-related features under the Analytics section (?).
* Currently, the notice causes confusion to users who enter that section to view third party reports. The deprecation notice could have come with a post that provides third parties who extend that section with a clear path moving forward. Should they keep their own reports there? Should they move them wherever it makes sense to them?
* Please dedicate some resources (I know, tough when lacking resources) to moving the Reports built into WooCommerce extensions to the new Analytics screen, and document the process. Empowering an entire ecosystem to deliver value through the work we do increases the impact of our work by orders of magnitude.

**Comment by loranallensmith** [comment]
Howdy @franticpsyx!  :wave:  Just following up here with some next steps based on our conversation in the [Woo Community Slack](https://woocommerce.com/community-slack).  

I totally hear you on the gaps in documentation and the signal that particular notice might send.  We’re putting some guidance and documentation together for developers, but I wanted to get some direct input from you and your team on the parts of that guidance related to transitioning from the original reporting system to the new analytics system.

I'd like to get a better idea of what we can include in documentation, tutorials, developer guides going forward to set as many folks up for success as possible, so we're going to connect 1:1 next week to chat through obstacles an hammer out some specifics.

In the meantime, I'm going to close this out this issue, but I am tracking the issue on our internal Advocacy project board.

**Comment by sean-mystyle** [comment]
Can we update this thread with the link to the updated documentation and/or dates on when the old reports section will go away?  This thread is top of google for me for searches related to this issue.
