### ISSUE TITLE
ZIP code validation based on ZIP code format - more than one acceptable format?

### ISSUE THREAD

**Issue by grig-23** [woocommerce/woocommerce#29212]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Most ZIP codes in European countries are just digits, e.g. 6020 in Austria, 10115 in Germany or 10309 in Lithuania. Sometimes though, an additional letter (or two) + hyphen is used, e.g. A-6020 or LT-10309. The ZIP code verification isn't consistent in that regard though - for Germany and Austria, a "Billing Postcode / ZIP is not a valid postcode / ZIP." error message is returned if zip codes like A-6020 or DE-10115 are used, however, that is not the case for Lithuania. Not sure if that is intentional?

**Expected behavior**
I'd expect both formats to be accepted in European countries, e.g. 10309 and LT-10309 for Lithuania, or 10115 and DE-10115 in Germany. In regards to Austria, I'm a bit confused though.
 
Officially in Lithuania the LT- part (as per ISO 3166-1 standard) is optional and A- for Austria doesn't even use the same ISO 3166-1 standard (it would be AT-6020 I guess)?

I wasn't able to find any official documents pointing to such ZIP format in Austria, so not 100% sure if this is the right decision, however, I think that both formats should be accepted. 

Reported in 3763748-zen.

**Actual behavior**
In Germany and Austria (and probably a bunch of other European countries) format like A-6020, AT-6020 or DE-10115 is not accepted), while in some others (LT-10309) it is accepted. Not sure if that is by design?

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Add a product to cart.
2. Attempt to purchase with an address in Austria and zip code A-6020 and AT-6020
3. Attempt to purchase with an address in Germany and zip code DE-10115
4. Attempt to purchase with an address in Lithuania and zip code LT-10309.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @grig-23,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end using WooCommerce 5.0. 

**Case 1 - Attempt to purchase with an address in Austria and zip code A-6020 - received a message that the zip code is invalid:**

![austria](https://user-images.githubusercontent.com/19143190/109365354-fb1a5d00-785e-11eb-8dab-d2f2b162afba.png)

**Case 2 - Attempt to purchase with an address in Germany and zip code DE-10115 - received a message that the zip code is invalid:**

![germany](https://user-images.githubusercontent.com/19143190/109365362-ff467a80-785e-11eb-97d6-73d25192c7bb.png)

**Case 3 - Attempt to purchase with an address in Lithuania and zip code LT-10309 - order went through:**

![](http://g.recordit.co/WtUCHqiTeo.gif)

If this is a bug, it seems a `low` priority for fixing it to me. Please let me know if you think othervise. I am also adding a label `needs developer feedback` to see if the behavior is as expected.

**Comment by barryhughes** [comment]
Interesting. I'll try to come back with a more substantive answer soon, but regarding the examples of Germany, Austria and Lithuania I will just quickly note the following, taken from resources made available via the [Universal Postal Union](https://www.upu.int) website:

* [Germany](https://www.upu.int/UPU/media/upu/PostalEntitiesFiles/addressingUnit/deuEn.pdf) is noted as using 5 digit codes, and there is a specific note that _"on no account should a country code (D-or DE-) be written in front of the postcode."_
* [Austria](https://www.upu.int/UPU/media/upu/PostalEntitiesFiles/addressingUnit/autEn.pdf) is noted as using a 4 digit code, and while there is no explicit rule that country codes should _not_ be used as a prefix, it also doesn't suggest they _should_ be used.
* [Lithuania](https://www.upu.int/UPU/media/upu/PostalEntitiesFiles/addressingUnit/ltuEn.pdf) is noted as using a 5 digit code, to prefixed with `LT-` if the mail is coming from outside the country but not requiring it for domestic mail.

Given those things the current behaviour doesn't seem unreasonable and, especially in light of the German example, I'd be a little reluctant to push forward with a change to always allow a country-code prefix. It would _probably_ be easier to deal with specific changes on a country-by-country basis, backed by supporting evidence of some kind.

**Comment by barryhughes** [comment]
Went ahead and closed this issue but, again, if there are individual cases where we need to revise how we handle postcodes, we're definitely open to that—let's just keep it specific to individual countries and evidence-based where possible :+1:
