### ISSUE TITLE
Importing large batch of products is slow due to `recount_terms` method

### ISSUE THREAD

**Issue by ovidiul** [woocommerce/woocommerce#29231]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
We are trying to import around 50K products inside the database in a batch import, with about 3K related taxonomy terms.

The problem we are having is that after each product Save, the import script waits around 5 seconds to finish, and we have tracked the behaviour to this [commit](https://github.com/woocommerce/woocommerce/commit/8b0915c4e090082d348cdd5985a0db0cb78146e8) which adds a term recounting method on each product update.

Would it be possible to add an option to disable that, as it creates a high latency for the products import, we have tried setting the `wp_defer_term_counting(true)` with no positive output. 

**Expected behavior**
It would be ideal that on product save, we could choose if we want to terms to be recounted programmatically, as we could do that after at the end of the batch import.

**Actual behavior**
Currently, the import process recounts the terms on each product save, which is not ideal for when importing a large batch of products.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. This can only be tracked down on a website with large number of numbers, so prepare around 50K unique products
2. Create an import script that updates each of the 50K products one at a time, and check the response time before and after save.
3. With XDebug we could easily trace this route at always hanging around this [line](https://github.com/woocommerce/woocommerce/blob/8b0915c4e090082d348cdd5985a0db0cb78146e8/includes/admin/settings/class-wc-settings-products.php#L69) 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
### WordPress Environment ###

WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.1

WP Version: 5.6.2
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: –
Language: en_US
External object cache: ✔

**Comment by roykho** [comment]
@ovidiul - Thanks for the report. Since this is so close to release, we prefer not to rush a solution for this. So in that respect, I will revert the change https://github.com/woocommerce/woocommerce/commit/8b0915c4e090082d348cdd5985a0db0cb78146e8

And provide a different solution for https://github.com/woocommerce/woocommerce/issues/25375 so I will be closing this issue.

**Comment by roykho** [comment]
Hi @ovidiul - I am circling back here and wanted to ask. Are you using a custom import script or just using the WC built in import tool?

**Comment by ovidiul** [comment]
Hi @roykho 

It's a custom script that does something like this

```
$this->wc_product = new WC_Product();
$this->wc_product->set_sku( $this->sku );
$this->wc_product->set_date_created( \time() );
...
$this->get_wc_product()->update_meta_data( '...', $... );
...
$this->get_wc_product()->save(); //this is where the product hangs and tries to update the term count
```

Let me know if you need further info.

**Comment by roykho** [comment]
@ovidiul - thanks for the additional information. So I am wondering what if we only updated the term count based on that product's term only? So instead of recounting all terms of all the products, just recount the terms that are assigned to that specific product at the time.

In addition, we could add a filter something like `woocommerce_product_update_recount_terms` so this could still be turned off if you wish to defer recounts until after your script is finished with a new function `wc_recount_all_terms`.

Would that work for you?

**Comment by ovidiul** [comment]
The first option makes sense, to only recount the terms for that specific product.

In addition to that, the proposed filter would work very well since, for large import batches, we might want to turn that off and maybe do a full-term recount in the end as a separate job using the proposed `wc_recount_all_terms` function.

The idea here is to try and be as efficient as possible when doing large imports, so any saved second counts, the proposed solution sounds great from my point.

Thank you @roykho .
