### ISSUE TITLE
Refund and return policy page

### ISSUE THREAD

**Issue by pmcpinto** [woocommerce/woocommerce#29235]
**Is your feature request related to a problem? Please describe.**
Having a refund and return policy page helps to increase the credibility of a store in the eyes of shoppers and distribution channels. As an example, in order to use Google free product listings, it's required to include the return policy information.

WooCommerce should provide a simple way to set up a refund and return policy page with minimal effort.

The policy should include:
Policies: How you handle returns and refunds, including what the customer is required to do, the returns time frame, and when a customer can expect a refund.
Return addresses: Include where the return should be mailed to.
Rules: Provide any rules for refund and return rules.

**Describe the solution you'd like**
Ideally, we should follow the same approach that we have for the Privacy Policy page: we automatically create a Refund and Return policy draft page when the user activates WooCommerce. Then we can trigger an inbox notification informing the user that we created the draft page that can be used as the Refund and Return policy.

**Additional context**
Post with more context about this topic: p7bje6-300-p2

**Comment by pmcpinto** [comment]
cc @timmyc @elizaan36

**Comment by juliaamosova** [comment]
Thanks for bringing this up @pmcpinto! I am cc'ying other WC Core leads to put it on their radar as well @peterfabian @ObliviousHarmony @vedanshujain.

**Comment by garymurray** [comment]
Is there any progress on this? What would be the next steps needed here to get this moving?

cc @jconroy @j111q

**Comment by vedanshujain** [comment]
@garymurray We will need help with the default contents of this page, or should this be kept empty for now?

**Comment by j111q** [comment]
@vedanshujain Hey there 👋 So sorry it took us a while to circle back! I've put the draft content of the page in this [Google doc](https://docs.google.com/document/d/1221DXE8I2ANb99VhsLqGjEOrI0fmshvb3B28w-5Y900/edit#heading=h.670b5br6xy7u). 

I'm awaiting copy review from Product Marketing and Legal teams by the end of this week, but I don't expect there will be drastic changes. You can use the draft copy first (if you want to work on it now) and I will update again here once the copy is final! Thank you so much. 😊

**Comment by j111q** [comment]
@vedanshujain Copy is confirmed 👍 Do let me know if you have any other questions here! Thank you!
