### ISSUE TITLE
WordPress admin bar "View store" menu is not "View shop" on UK language installations

### ISSUE THREAD

**Issue by ninetyninew** [woocommerce/woocommerce#29247]
**Describe the bug**
When using English (UK) language references to store are changed to shop, however the WordPress admin bar site hover menu still shows the text as "View store" and not "View shop".

**Expected behavior**
Use "View shop" as all other store references are shop.

**Actual behavior**
Shows "View store" (the default string)

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go WordPress dashboard
2. Hover over store name in admin bar
3. See "View store" link

**Comment by tammullen** [comment]
Hi @ninetyninew,

Thanks for your issue, translations are created and handled by local communities, you are free to update and send suggestions on https://translate.wordpress.org/projects/wp-plugins/woocommerce/

For the example you gave you can see the current translation for "View Store" in English (UK) here
https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/en-gb/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=577740&filters%5Btranslation_id%5D=28078393

I'm closing this for now as it is not WooCommerce Core bug.
