### ISSUE TITLE
On cart page, under Shipping, post code field reappears for countries where it isn't required

### ISSUE THREAD

**Issue by theabhig** [woocommerce/woocommerce#29261]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

With "Enable the shipping calculator on the cart page" enabled under **WooCommerce > Settings > Shipping > Shipping Options**:

On the cart page, when the address is changed to a country which doesn't require a post code, such as Bahamas, the post code field disappears. However when 'Update' is pressed, the post code field appears when you click on 'Change Address' even though it didn't appear in the first place.

This doesn't stop users from proceeding to checkout but can be confusing for users who think they may still need to put something in the check out field.

**Expected behavior**

I'd expect the post code field to stay hidden for countries that don't require it.

**Actual behavior**

As above:

With "Enable the shipping calculator on the cart page" enabled under **WooCommerce > Settings > Shipping > Shipping Options**:

On the cart page, when the address is changed to a country which doesn't require a post code, such as Bahamas, the post code field disappears. However when 'Update' is pressed, the post code field appears when you click on 'Change Address' even though it didn't appear in the first place.

**On the checkout page**, if the Bahamas is selected as the address, it hides the post code field so this appears to be only happening on the cart page.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

1. Make sure shipping calculator on the cart page is enabled
2. Add a product to cart
3. On the cart page, under Shipping, change address to Bahamas. This will make the post code field disappear. 
4. Press 'Update'. 
5. Click on 'Change address' again and the post code field appears again.

Can be recreated on my [test site](https://theabhigwooship.mystagingwebsite.com/)

First reported in 3767029-zen

**Screenshots**

[Screen recording](https://d.pr/v/iGXFGL)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

### WordPress Environment ###

WordPress address (URL): https://theabhigwooship.mystagingwebsite.com
Site address (URL): https://theabhigwooship.mystagingwebsite.com
WC Version: 5.0.0
REST API Version: ✔ 5.0.0
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.9.0
Log Directory Writable: ✔
WP Version: 5.6.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.15
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.75.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.21-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.0.0
WC Database Prefix: wp_
Total Database Size: 2.52MB
Database Data Size: 1.14MB
Database Index Size: 1.38MB
wp_woocommerce_sessions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 0.25MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
page: 6
post: 1
product: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Akismet Anti-Spam: by Automattic – 4.1.8
Jetpack by WordPress.com: by Automattic – 9.4.1
WooCommerce Shipping & Tax: by Automattic – 1.25.7
WooCommerce USPS Shipping: by WooCommerce – 4.4.49
WooCommerce Table Rate Shipping: by WooCommerce – 3.0.30
WooCommerce: by Automattic – 5.0.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.5.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 3
Oldest: 2021-03-02 09:02:11 +0000
Newest: 2021-03-02 09:04:37 +0000

`

**Comment by hsingyuc** [comment]
I'll try to fix this one

**Comment by tammullen** [comment]
Thank you for taking the time to report this bug @theabhig, we really appreciate your help. I can reproduce it on my end. 
​
![Screenshot_2021-03-07_at_23_57_44](https://user-images.githubusercontent.com/24649833/110259841-9dde8400-7fa1-11eb-9ea1-89d7a00e8790.png)
Field displayed for UK as expected

![Screenshot_2021-03-07_at_23_57_59](https://user-images.githubusercontent.com/24649833/110259833-99b26680-7fa1-11eb-80e6-eb10e70f5eae.png)
Changed to BS and field not displayed as expected 
Confirmed here that Postal Code not required for BS https://github.com/woocommerce/woocommerce/blob/30d7b2ce9d4ae732d1b036bd221328e5b7e870b8/includes/class-wc-countries.php#L896

![Screenshot_2021-03-07_at_23_58_54](https://user-images.githubusercontent.com/24649833/110259827-93bc8580-7fa1-11eb-80a5-2e6de95cfe01.png)

![Screenshot_2021-03-07_at_23_58_41](https://user-images.githubusercontent.com/24649833/110259819-8dc6a480-7fa1-11eb-97bb-2bbb23dd16ed.png)
Field appears when pressing change address however is not a required field but is confusing to have it displayed.
​
We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.
