### ISSUE TITLE
'Add to cart' button name should match between single and variation

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce#29288]
'add to cart' button for variation product doesnt have name. as seen in this line:
https://github.com/woocommerce/woocommerce/blob/23710744c01ded649d6a94a4eaea8745e543159f/templates/single-product/add-to-cart/variation-add-to-cart-button.php#L31

but 'add to cart' but for simple product has a name. as seen here:
https://github.com/woocommerce/woocommerce/blob/23710744c01ded649d6a94a4eaea8745e543159f/templates/single-product/add-to-cart/simple.php#L49

It will be hard to do element query for ATC button, if this not match.

**Comment by roykho** [comment]
Hi there @erikdemarco - Why not just query by class name?
