### ISSUE TITLE
wc_admin_url is used when woocommerce-admin is disabled

### ISSUE THREAD

**Issue by dz0ny** [woocommerce/woocommerce#29301]
**Describe the bug**
Error: Call to undefined function wc_admin_url()

Location: woocommerce/includes/admin/views/html-admin-page-reports.php in include_once at line 17
```
12. 	<div id="message" class="error inline" style="margin-top:30px">
13. 		<p>
14. 			<strong>
15. 			<?php
16. 			/* translators: 1: Link URL */
17. 			echo wp_kses_post( sprintf( __( 'With the release of WooCommerce 4.0, these reports are being replaced. There is a new and better Analytics section available for users running WordPress 5.3+. Head on over to the <a href="%1$s">WooCommerce Analytics</a> or learn more about the new experience in the <a href="https://docs.woocommerce.com/document/woocommerce-analytics/" target="_blank">WooCommerce Analytics documentation</a>.', 'woocommerce' ), esc_url( wc_admin_url( '&path=/analytics/overview' ) ) ) );
18. 			?>
19. 			</strong>
20. 		</p>
21. 	</div>
22. 	<nav class="nav-tab-wrapper woo-nav-tab-wrapper">
23.
 ```
Stacktrace:
admin.php:259 in 
/var/www/public_html/wp-includes/plugin.php:484 in do_action
/var/www/public_html/wp-includes/class-wp-hook.php:311 in do_action
/var/www/public_html/wp-includes/class-wp-hook.php:287 in apply_filters
/var/www/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-menus.php:264 in reports_page
/var/www/public_html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-reports.php:36 in output
/var/www/public_html/wp-content/plugins/woocommerce/includes/admin/views/html-admin-page-reports.php:17 in include_once

**To Reproduce**
- Install or upgrade to WooCommerce 5.0
- When WooCommerce admin is disabled via filter `add_filter( ‘woocommerce_admin_disabled’, ‘__return_true’ );` the WooCommerce itself uses the function defined in woocommerce-admin.

**Expected behavior**
Don't use the function that's not defined.

**Comment by roykho** [comment]
Thanks for reporting. It has already been reported and fixed here https://github.com/woocommerce/woocommerce/commit/315c4de5c3270cfeea9cb2bf6da9d58e09d4250d It will be out with the next release 5.1 which is on track for tomorrow.
