### ISSUE TITLE
Taxes report not changing amount when refunding order

### ISSUE THREAD

**Issue by giacogiaco** [woocommerce/woocommerce#29300]
Could you please reopen this issue: https://github.com/woocommerce/woocommerce/issues/24029 
It still exists with the new Admin Reports section. Thank you!

**Comment by tammullen** [comment]
Hi @giacogiaco 

Analytics is part of WooCommerce Admin which is being developed in another repository: https://github.com/woocommerce/woocommerce-admin.

Please raise a new issue in that repository and to make sure the team can evaluate the issue please make sure to fill out all sections of their bug report.
