### ISSUE TITLE
Add e2e test that clicks and opens links in the side bar and verifies the page loads

### ISSUE THREAD

**Issue by zhongruige** [woocommerce/woocommerce#29319]
We should look into adding tests that click links in the side bar for various top-level menu items and verify the pages load.

This could be broken down into:
* WooCommerce
  * Skip Customers & Coupons
* Products
* Marketing

In each, we would click a menu link and verify the page loads. For example:
* Open Analytics > Overview
* Verify title ("Overview" text exists) and perhaps at least one chart is loaded

**Comment by rrennick** [comment]
> Open Analytics > Overview

I think we should check all the screens under Analytics and WooCommerce -> Customers. The markup on the WCA pages is consistent so adding additional screens should not take a great deal of time.
