### ISSUE TITLE
Get products with sorted categories - Woocommerce API

### ISSUE THREAD

**Issue by probance-antoine** [woocommerce/woocommerce#29320]
Hello,

I have a problem with the woocommerce API. When I list a product I would like to have the categories in order (main category, sub category, sub sub category) :
* On the production site of one of my customers the result is a bit random…
* If I list a product with 2 categories with IDs less than 200 the result is OK
* If I list a product with 2 categories, the first one < 200, the second one > 200 OK on my test site, KO on the customer site (sub category –> Main category)
* If I list a product with 3 categories, the first < 200, the second < 200, the third > 200, OK on my test site, KO on the client site (sub sub category –> Main category –> Sub category)

Here is a link where you can see the problem : https://www.loom.com/share/06d242a665c04d6084bbfdac81bf0830

We tried by disabling all plugins (except the woocommerce one of course), unfortunately it doesn’t change anything. Is there a parameter that could influence the sorting of categories ? The categories are well sorted in the “category” tab of the woocommerce interface (as you can see on the loom video).

**Comment by probance-antoine** [comment]
Hello,

Any update on this issue please ?

**Comment by vedanshujain** [comment]
Hi, we discussed this internally, and as of now we don't support internal sort order within categories page. Note that, parent ids can be higher than their children (for egs, when they are added or modified manually), so this sort will not solve the use case.

> I would like to have the categories in order (main category, sub category, sub sub category)

This is possible using the [product category](https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-product-categories endpoint), we recommend that you fetch these categories in the client, and match them while parsing the product API response. this endpoint also has the `parent` attribute that you can use. 
You can also use the `woocommerce_rest_prepare_product_object` filter to modify the response and sort the categories if you want. I am closing the issue for repo maintenance, but feel free to respond back if you have more questions.
