### ISSUE TITLE
[GlobalStep] "Reset Password" button appears misaligned for "Twenty Twenty One" and "Twenty Twenty" themes. 

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#29325]
## Bug Description:
"Reset Password" button appears misaligned for Twenty Twenty One and Twenty Twenty themes.

## Environment:
Woocommerce Version : WooCommerce 5.1 and 5.0
WordPress version: (v5.7)

PC:
Windows 10, Mac 10.14.6
Chrome(Version 88.0.4324.104) 
Firefox(Version 86.0)
Safari: v13.1.2(13609.3.5.1.5)

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins
1. Complete the onboarding setup wizard.
1. Select Twenty Twenty One or Twenty Twenty theme.
1. Go to frontend.
1. Click on My account page.
1. Click on "Lost your Password" option.
1. Observe that "Reset Password" button appears misaligned.

## Actual Result:
"Reset Password" button appears misaligned for Twenty Twenty One and Twenty Twenty themes.

## Expected Result:
"Reset Password" button should be properly aligned for Twenty Twenty One and Twenty Twenty themes.

## ScreenShot:
![#29325_1](https://user-images.githubusercontent.com/41110392/110657051-87753a00-81e6-11eb-9226-ca83cff85e01.png)

![#29325_2](https://user-images.githubusercontent.com/41110392/110658134-70831780-81e7-11eb-84cf-0e0162e787d8.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @gglobalstep,

Thank you for taking the time to report this bug, we really appreciate your help. 

We’re going to work on this bug as soon as possible.

**Comment by jonathansadowski** [comment]
Note from planning:

We're going to shift the priority of this to low and focus on addressing this in 2020, leaving 2021 as-is.

For 2020, we're going to make the input align with the button the same way it does as the search box that appears below:

![image.png](https://images.zenhubusercontent.com/5e7912a264525528179004a5/528e9775-0541-4c91-8dc4-2a0af1f8638f)
