### ISSUE TITLE
Using GitHub Actions against various e2e environments

### ISSUE THREAD

**Issue by zhongruige** [woocommerce/woocommerce#29327]
Using GitHub Actions against various e2e environments. This job will have multiple steps that set different environment variables. Specify that this is being tested in Chrome.

* Beta test next version of WordPress daily
* Test against the existing WordPress version (l -2)
* PHP versions (l -2)
* Nice to have: Puppeteer supports FireFox, can add tests here

**Comment by adimoldovan** [comment]
This is obsolete, I will close it. A new CI workflow is in place, covering most if not all that's described in this issue.
