### ISSUE TITLE
[GlobalStep] For Twenty Twenty One theme, when dark mode is enabled "Dropdown" option within the website are only visible when we hovered over it

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#29323]
## Bug Description:
For Twenty Twenty One theme, when dark mode is enabled "Dropdown" option within the website are only visible when we hovered over it

## Environment:
Woocommerce Version : WooCommerce 5.1 and 5.0
WordPress version: (v5.7)

PC:
Windows 10, Mac 10.14.6
Chrome(Version 88.0.4324.104) 
Firefox(Version 86.0)
Safari: v13.1.2(13609.3.5.1.5)

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins
1. Complete the onboarding setup wizard.
1. Add some products.
1. Complete the payment setup from WooCommerce-Settings-Payments and select any one of the options say "Cash on Delivery"
1. Go to Appearance-Customize
1. Select "Colors & dark Mode" option
1. Select a light color and then enable the "Dark Mode" checkbox
1. Go to frontend and place an order
1. During checkout note that dark mode is enabled when scrolled it is displayed at the right side bottom corner with "Dark Mode:ON"
1. Now click on State or Country or any other dropdown options and hover mouse over it
1. Observe that "Dropdown" option within the website are only visible when hovered over it via mouse

## Actual Result:
For Twenty Twenty One theme, when dark mode is enabled "Dropdown" option within the website are only visible when we hovered over it

## Expected Result:
On Frontend, when dark mode is enabled "Dropdown" option within the website should always be visible.

## Video and ScreenShot:
![#29323](https://user-images.githubusercontent.com/41110392/110655485-1b460680-81e5-11eb-9bc0-8145e68dc124.png)

https://user-images.githubusercontent.com/41110392/110655560-29942280-81e5-11eb-8e49-4a6289e8c513.mp4

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @gglobalstep,

Thank you for taking the time to report this bug, we really appreciate your help. 

We’re going to work on this bug as soon as possible.
