### ISSUE TITLE
WooCommerce Reporting

### ISSUE THREAD

**Issue by PetrusVermaak** [woocommerce/woocommerce#29338]
**Describe the bug**
WooCommerce Reporting does not report multi currency for a product correctly.

**Expected behavior**
It should convert the different currencies to one single currency before counting the total together.

**Actual behavior**
It counts different currencies together, resulting in a skewed total.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Install multi currency, sell product in two different currencies.

**Screenshots**
Here is a view of my orders:
https://prnt.sc/10imyt5

WooCommerce Reporting reports a correct gross sales price 
https://prnt.sc/10inao7

WooCommerce Reporting reports an incorrect total product sales price 
https://prnt.sc/10ince7

**Comment by zhongruige** [comment]
Hi @PetrusVermaak,

Thank you for reporting this issue! Unfortunately, as we are deprecating this reporting section, we won't be making any more fixes, so I will be closing this issue.

<img width="1669" alt="Screen Shot 2021-03-11 at 3 39 10 PM" src="https://user-images.githubusercontent.com/71906536/110864941-0e2a2580-8280-11eb-85ce-eb11332a5e60.png">
