### ISSUE TITLE
Shop prices entered "including tax" with "including tax" set displays price without tax

### ISSUE THREAD

**Issue by AccuPixel** [woocommerce/woocommerce#29339]
**Describe the bug**
Setting the following:
* Yes, I will enter prices inclusive of tax
"Display prices in the shop" set "Including tax"
"Display prices during cart and checkout" set "including tax"

Displays prices in shop without tax applied.

**Expected behavior**
Setting "Display prices in the shop - including tax" should display the price including tax.

**Actual behavior**
Setting "Display prices in the shop - including tax" displays the price without tax

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Please see screenshots detailing the settings applied.

**Screenshots**

![Screenshot 2021-03-11 at 08 45 28](https://user-images.githubusercontent.com/80451005/110760182-59274700-8246-11eb-9d9c-8d0ac5b59dca.png)
![Screenshot 2021-03-11 at 08 45 23](https://user-images.githubusercontent.com/80451005/110760185-5af10a80-8246-11eb-9d55-9683c85e4ecb.png)
<img width="1152" alt="Screenshot 2021-03-11 at 08 44 54" src="https://user-images.githubusercontent.com/80451005/110760187-5b89a100-8246-11eb-89cb-11c76f4cee76.png">
<img width="1049" alt="Screenshot 2021-03-11 at 08 44 25" src="https://user-images.githubusercontent.com/80451005/110760191-5c223780-8246-11eb-8c7f-9100345d2ba2.png">

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
[WooCommerce status ‹ AccuPixel Ltd — WordPress.pdf](https://github.com/woocommerce/woocommerce/files/6121674/WooCommerce.status.AccuPixel.Ltd.WordPress.pdf)

</details>

**Comment by Bossman1337** [comment]
This is the expected behaviour.

You're entering the product prices **inclusive of tax** so no further calculation is done. If you want to enter them without the tax then the tax calculation will be done. Tested and working fine for me.

If you set **display prices during cart and checkout** to excluding tax, you will see whats happening.

**Comment by AccuPixel** [comment]
Hi – not sure I follow or agree.

 

Gross figures are entered (including tax) and gross figures (including tax) are set to display in shop and checkout.

 

But nett figures are displayed in shop – not gross as entered and contrary display settings.

 

If gross figures are to be displayed at all times (until cart sets tax rate based on territory) what are the correct settings?

 

Regards,

 

Simon Brown

Director - AccuPixel Ltd

+44 (0)1252 653 759

+44 (0)7910 243 499

 

Out now –  Online Metashape Standard Course endorsed by Agisoft:

https://accupixel.co.uk/courses/metashape-standard-edition/

 

AccuPixel Ltd is a limited company registered in England and Wales. Registered number 12671879. Registered office:- 94 Tavistock Road, Fleet, Hants. GU51 4EZ

 

 

 

 

From: Bossman1337 ***@***.***>
Reply to: woocommerce/woocommerce ***@***.***>
Date: Thursday, 11 March 2021 at 13:43
To: woocommerce/woocommerce ***@***.***>
Cc: AccuPixel ***@***.***>, Author ***@***.***>
Subject: Re: [woocommerce/woocommerce] Shop prices entered "including tax"with "including tax" set displays price without tax (#29339)

 

This is the expected behaviour.

You're entering the product prices inclusive of tax so no further calculation is done. If you want to enter them without the tax then the tax calculation will be done. Tested and working fine for me.

If you set display prices during cart and checkout to excluding tax, you will see whats happening.

**Comment by Bossman1337** [comment]
Hmmm, okay.. I think i follow. What are you product settings for tax? Maybe that's the issue?

![image](https://user-images.githubusercontent.com/39673000/110797844-78879980-8271-11eb-8762-34c5e353e3c2.png)

**Comment by AccuPixel** [comment]
All products as per the above.

 

Regards,

 

Simon Brown

Director - AccuPixel Ltd

+44 (0)1252 653 759

+44 (0)7910 243 499

 

Out now –  Online Metashape Standard Course endorsed by Agisoft:

https://accupixel.co.uk/courses/metashape-standard-edition/

 

AccuPixel Ltd is a limited company registered in England and Wales. Registered number 12671879. Registered office:- 94 Tavistock Road, Fleet, Hants. GU51 4EZ

 

 

 

 

From: Bossman1337 ***@***.***>
Reply to: woocommerce/woocommerce ***@***.***>
Date: Thursday, 11 March 2021 at 13:56
To: woocommerce/woocommerce ***@***.***>
Cc: AccuPixel ***@***.***>, Author ***@***.***>
Subject: Re: [woocommerce/woocommerce] Shop prices entered "including tax"with "including tax" set displays price without tax (#29339)

 

Hmmm, okay.. I think i follow. What are you product settings for tax? Maybe that's the issue?

**Comment by Bossman1337** [comment]
Yes but on the edit product screen. **Product data > general tab**

**Comment by AccuPixel** [comment]
Yup – this one?

 

 

Regards,

 

Simon Brown

Director - AccuPixel Ltd

+44 (0)1252 653 759

+44 (0)7910 243 499

 

Out now –  Online Metashape Standard Course endorsed by Agisoft:

https://accupixel.co.uk/courses/metashape-standard-edition/

 

AccuPixel Ltd is a limited company registered in England and Wales. Registered number 12671879. Registered office:- 94 Tavistock Road, Fleet, Hants. GU51 4EZ

 

 

 

 

From: Bossman1337 ***@***.***>
Reply to: woocommerce/woocommerce ***@***.***>
Date: Thursday, 11 March 2021 at 14:04
To: woocommerce/woocommerce ***@***.***>
Cc: AccuPixel ***@***.***>, Author ***@***.***>
Subject: Re: [woocommerce/woocommerce] Shop prices entered "including tax"with "including tax" set displays price without tax (#29339)

 

Yes but on the edit product screen. Product data > general tab

**Comment by Bossman1337** [comment]
I think whatever you are using to post to GitHub isn't showing correctly. I just see this.. Are you attaching images?

![image](https://user-images.githubusercontent.com/39673000/110799690-598a0700-8273-11eb-8e8d-d61db63a027b.png)

**Comment by AccuPixel** [comment]
Ah…embedding…my apologies…

 

Now attached.

 

 

 

Regards,

 

Simon Brown

Director - AccuPixel Ltd

+44 (0)1252 653 759

+44 (0)7910 243 499

 

Out now –  Online Metashape Standard Course endorsed by Agisoft:

https://accupixel.co.uk/courses/metashape-standard-edition/

 

AccuPixel Ltd is a limited company registered in England and Wales. Registered number 12671879. Registered office:- 94 Tavistock Road, Fleet, Hants. GU51 4EZ

 

 

 

 

From: Bossman1337 ***@***.***>
Reply to: woocommerce/woocommerce ***@***.***>
Date: Thursday, 11 March 2021 at 14:10
To: woocommerce/woocommerce ***@***.***>
Cc: AccuPixel ***@***.***>, Author ***@***.***>
Subject: Re: [woocommerce/woocommerce] Shop prices entered "including tax"with "including tax" set displays price without tax (#29339)

 

I think whatever you are using to post to GitHub isn't showing correctly. I just see this.. Are you attaching images?

**Comment by AccuPixel** [comment]
<img width="819" alt="Screenshot 2021-03-11 at 14 05 55" src="https://user-images.githubusercontent.com/80451005/110800165-d74e1280-8273-11eb-94c3-9e8c3adcefa9.png">

(note to self - replying via email does not attach!)

**Comment by Bossman1337** [comment]
I can't reproduce this unfortunately. The only thing i can think of is a plugin/theme causing it, even though you said you have eliminated these.

**Comment by zhongruige** [comment]
Thank you for helping to troubleshoot this issue @Bossman1337! I have also tried to follow the steps outlined by @AccuPixel and haven't been able to reproduce the issue. Everything is working as expected on my end. 

I tested the following on:
* WooCommerce 5.1
* WordPress 5.7
* Storefront theme
* WooCommerce Shipping & Tax 1.25.8

### Replication steps

* I enabled tax in my account and set the following options:
 
<img width="703" alt="Screen Shot 2021-03-11 at 2 41 39 PM" src="https://user-images.githubusercontent.com/71906536/110859876-56921500-8279-11eb-9c74-e4ddd91f59b7.png">

* I also made sure I have a standard tax rate set:

<img width="1504" alt="Screen Shot 2021-03-11 at 2 48 57 PM" src="https://user-images.githubusercontent.com/71906536/110859921-64479a80-8279-11eb-90f5-579fed4e6fdf.png">

* I configured the product as `Taxable` and set the tax class to `Standard`. Additionally I set the price to 45.

<img width="1202" alt="Screen Shot 2021-03-11 at 2 47 37 PM" src="https://user-images.githubusercontent.com/71906536/110860006-7b868800-8279-11eb-902a-b78c6d251767.png">

* I opened the product page and verified the price still showed as 45 as expected:

<img width="754" alt="Screen Shot 2021-03-11 at 2 47 49 PM" src="https://user-images.githubusercontent.com/71906536/110860095-948f3900-8279-11eb-9c3d-4844171552df.png">

Please let me know if I missed something or if there's any other information

**Comment by AccuPixel** [comment]
@zhongruige & @Bossman1337 - many thanks for looking into this. Its the worst kind of "issue" and I will keep walking the path in search of its cause...
Strange thing is when I first enter the prices everything displays correctly...then "at some point" shortly afterwards it reverts to displaying nett values...

**Comment by Bossman1337** [comment]
@AccuPixel "Strange thing is when I first enter the prices everything displays correctly"

So you're saying if you save the product then refresh the front end, it displays correctly (inc tax)? Then a short period of time it reverts (ex tax)?

**Comment by AccuPixel** [comment]
@Bossman1337 - let me prove out the behaviour in our test environment first.

**Comment by AccuPixel** [comment]
@Bossman1337 & @zhongruige - I do not know if this helps or guides us to the source of the issue, but...

Price Display Suffix - no matter what the field contains - is no longer displaying in the shop or product pages.

This seems curious? I will continue to investigate, but does this help?

**Comment by Bossman1337** [comment]
@AccuPixel Something seems to be overwriting the pricing if the display suffix doesn't show at all.

What theme are you using? Or is it custom?

**Comment by AccuPixel** [comment]
Theme is Ascension Version: 1.1.5

Config only. No customisation. We do not like customisation...

**Comment by zhongruige** [comment]
@AccuPixel

Thank you for clarifying! You mentioned you had a tests site you can use. I was curious if you were able to verify the same behavior is happening on the test site, and if so, if it is possible to switch theme theme from Ascension to Storefront [https://woocommerce.com/storefront/](https://woocommerce.com/storefront/) and see if that helps fix the issue? This will narrow down if it's the theme causing the problem or not.

> Price Display Suffix - no matter what the field contains - is no longer displaying in the shop or product pages.

I also did test adding in the Price Display Suffix (I used VAT) and it showed up as expected:

<img width="760" alt="Screen Shot 2021-03-12 at 8 18 22 AM" src="https://user-images.githubusercontent.com/71906536/110961419-06649280-830d-11eb-9fd1-05a2414304bd.png">

**Comment by Bossman1337** [comment]
@AccuPixel I installed the Ascension theme and is working as expected on my end.

I suspect this is pointing towards a plugin causing this. Can you list the plugins you have installed?

**Comment by AccuPixel** [comment]
List of plugins - those marked * have been disabled and tested. Either because they are most likely to be involved (cache, woocommerce related) or because they were added recently (easy updates).

*Easy Updates Manager
Version 9.0.8 | By Easy Updates Manager Team | View details
	
Export User Data
Version 2.1.3 | By Q Studio | View details

LearnDash LMS
Version 3.3.0.3 | By LearnDash | Visit plugin site | Changelog

LearnDash LMS - Course Grid
Version 1.7.0 | By LearnDash | Visit plugin site
	
LearnDash LMS - Notifications
Version 1.5.2 | By LearnDash | Visit plugin site
	
*LearnDash LMS - WooCommerce Integration
Version 1.9.1.1 | By LearnDash | Visit plugin site
	
*LiteSpeed Cache
Version 3.6.3 | By LiteSpeed Technologies | View details

Loginizer
Version 1.6.6 | By Softaculous | View details
	
Loginizer Security
Version 1.6.6 | By Softaculous | Visit plugin site | Check for updates

Resend Welcome Email
Version 1.1.9 | By Hudson Atwell | View details

Stop User Enumeration
Version 1.3.29 | By Fullworks | View details

Tuxedo Big File Uploads
Version 1.2 | By Trevor Anderson | View details

UpdraftPlus - Backup/Restore
Version 1.16.49 | By UpdraftPlus.Com, DavidAnderson | View details

User Role Editor
Version 4.58.3 | By Vladimir Garagulya | View details | Changelog

WooCommerce
Version 5.1.0 | By Automattic | View details | Docs | API docs | Community support

WooCommerce Shipping & Tax
Version 1.25.8 | By Automattic | View details
	
WooCommerce Stripe Gateway
Version 4.9.0 | By WooCommerce | View details | Docs | Support

WordPress Importer
Version 0.7 | By wordpressdotorg | View details
	
WP Mail SMTP Pro
Version 2.6.0 | By WPForms | Visit plugin site

WP Upload Size
Version 1.0.1 | By Husain Ahmed | View details

WPForms Lite
Version 1.6.5 | By WPForms | View details
	
Yoast SEO
Version 15.9.2 | By Team Yoast | View details

**Comment by Bossman1337** [comment]
@AccuPixel thanks for that. The only thing that stands out to me is the **WooCommerce Shipping & Tax** i believe this automates taxes. Try and deactivate it and see if that works?

Docs here for that plugin: https://docs.woocommerce.com/document/woocommerce-shipping-and-tax/woocommerce-tax/

**Comment by AccuPixel** [comment]
@Bossman1337 - disabled WooCommerce Shipping & Tax and we still see nett price appearing in the shop.

**Comment by shirin1268-french** [comment]
Hi AccuPixel, 
Do you find any solution? I have also the same issue, but I enter the prices "excluding taxes" and want them to be shown "include taxes" but after a while, they are shown without taxes. I deactivated also "Woocommerce-shipping-and-taxes" but it didn´t help.

**Comment by Bossman1337** [comment]
@AccuPixel and @shirin1268-french - What is your **default customer location** set to? You can find this here: **WooCommerce > Settings > General**

**Comment by AccuPixel** [comment]
@shirin1268-french - not resolved it yet...still looking.

@Bossman1337 - "No location by default" is set.

**Comment by shirin1268-french** [comment]
Hi, 
default location is "Copenhagen". I change the language for the next picture. 
![default costumer location](https://user-images.githubusercontent.com/80815690/111457138-1e2a8500-8718-11eb-9f3d-d7efa2d72c68.JPG)
![woocommerce general setting](https://user-images.githubusercontent.com/80815690/111457142-1ec31b80-8718-11eb-8b0f-de37c0588e8b.JPG)

**Comment by shirin1268-french** [comment]
we are located in Denmark and sell just in Denmark.

**Comment by Bossman1337** [comment]
@AccuPixel Have you tried setting it to **shop base address**? That might be why..

**Comment by AccuPixel** [comment]
@Bossman1337 - Now I have set it...we may have found the source...I will monitor, but it looks like we may have a solution.

Thank you for your assistance with this - much appreciated.

**Comment by Bossman1337** [comment]
@AccuPixel I think that would have been it. I tested locally and logged out and reproduced it. If there is no location set then it can't calculate the tax (It doesn't know where the person is).

If set to your shop address then it calculates from that for everyone.

**Comment by shirin1268-french** [comment]
Thank you so much for your assistance. 
I treid it both with " shop base address" "customer billing/ shipping Address". but it doesn't work.  so the price in the catalog is without tax. what must be with tax. 
http://frenchpharmacy.dk.linux206.dandomainserver.dk/

**Comment by shirin1268-french** [comment]
@Bossman1337 , How can I check wp-cron?? :)

**Comment by Bossman1337** [comment]
@shirin1268-french If you can post a new issue (following the instructions on what is needed) then it will save any confusion with this post. It is a similar problem but might be something different causing your issue.

**Comment by AccuPixel** [comment]
Monitored...working as intended.

Big thank you to @Bossman1337 for getting to the bottom of this one.
