### ISSUE TITLE
Creation of WC_Product_External is not being created as external products.

### ISSUE THREAD

**Issue by jimmitjoo** [woocommerce/woocommerce#29340]
**Describe the bug**
So when creating a product programmatically, using the WC_Product_External, the product is still created as a "simple" product.

```
$extProd = new WC_Product_External();
$extProd->set_name('This should be an external product');
$extProd->set_description('But hey, it is not...');
$extProd->set_product_url('https://example.com');
$extProd->set_sku('1122334455');
$extProd->set_regular_price(150);
$extProd->set_price(125);
$extProd->save();
```

**Expected behavior**
The product should have product type of "external".

**Actual behavior**
As stated above.

**Steps to reproduce the bug**
Steps to reproduce the bug:
1. Create a new external product programmatically using the WC_Product_External class.
2. Check in admin what product type the created product has.
3. Rage

**Comment by Bossman1337** [comment]
Seems to work fine for me..

![image](https://user-images.githubusercontent.com/39673000/110793131-3019ad00-826c-11eb-87f4-4da28eceb009.png)

Maybe you have another plugin active that might be conflicting maybe?

**Comment by jimmitjoo** [comment]
I have deactivated all the other plugins but still gets the same product. I have also tried to install a pure installation with only Woocommerce activated and same problem.

I am using the roots/bedrock composer installation. So I am giving it a last try tonight with downloading the old fashion wordpress zip-file.

**Comment by jimmitjoo** [comment]
Seems like that was the problem, still don't understand though.
