### ISSUE TITLE
[GlobalStep] For Twenty Twenty One theme, "Sale" badge appears misaligned if "Products per row" is set to "1".

### ISSUE THREAD

**Issue by opr** [woocommerce/woocommerce#29343]
@gglobalstep commented on [Wed Mar 10 2021](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3949)

## Bug Description:
For Twenty Twenty One theme, "Sale" badge appears misaligned if  "Products per row" is set to "1".

## Environment:
Woocommerce Version : WooCommerce 5.1 and 5.0
WordPress version: (v5.7)

PC:
Windows 10, Mac 10.14.6
Chrome(Version 88.0.4324.104) 
Firefox(Version 86.0)
Safari: v13.1.2(13609.3.5.1.5)

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins
1. Complete the onboarding setup wizard.
1. Select Twenty Twenty One theme.
1. Add some products.
1. Go to Appearances->Customize.
1. Select WooCommerce->Product catalog option.
1. Set the Products per row value to "1".
1. Observe that "Sale" badge appears misaligned.

## Actual Result:
For Twenty Twenty One theme, "Sale" badge appears misaligned if "Products per row" is set to "1".

## Expected Result:
For Twenty Twenty One theme, "Sale" badge should be aligned if "Products per row" is set to "1".

## ScreenShot:

![#3949](https://user-images.githubusercontent.com/41110392/110654742-6ad80280-81e4-11eb-9c67-61273f38f92a.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

---

@opr commented on [Thu Mar 11 2021](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/3949#issuecomment-796765734)

Hi, thank you for reporting this. This is not controlled by WooCommerce Blocks, it is actually WooCommerce core that is responsible for this.

I will move the issue to the WooCommerce repository.

**Comment by zhongruige** [comment]
Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. I tested on:

* WooCommerce 5.1
* WordPress 5.7

### Replication steps:

* I set up a new WooCommerce store and imported the sample products as part of the setup checklist.
* I enabled the Twenty Twenty-one theme and navigated to `Appearance > Customize` and in the customizer, to ` WooCommerce > Product catalog` where I set Products per row to 1:

<img width="301" alt="Screen Shot 2021-03-12 at 2 28 04 PM" src="https://user-images.githubusercontent.com/71906536/111000376-2dd45300-833f-11eb-8e33-6512090632ff.png">

* After doing so, the "Sale" badge became misaligned, which also showed after publishing:

<img width="1139" alt="Screen Shot 2021-03-12 at 10 34 21 AM" src="https://user-images.githubusercontent.com/71906536/111000450-50ff0280-833f-11eb-8039-b45141659f41.png">

We’re going to solve this bug as soon as possible. Stay tuned for updates.
