### ISSUE TITLE
Expand the Debugging tests section in WooCommerce Core e2e README

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#29353]
Expand the [Debugging tests](https://github.com/woocommerce/woocommerce/tree/trunk/tests/e2e#debugging-tests) section in WooCommerce Core e2e README and provide real-life examples of how we debug e2e tests currently.

**Comment by lanej0** [comment]
Closing this out because docs to the Playwright-based tests cover this.
