### ISSUE TITLE
For woocommerce_new_order_email_allows_resend hook, argument should be set to true

### ISSUE THREAD

**Issue by lomars** [woocommerce/woocommerce#29367]
There seems to be a mistake with this newly added filter hook where main argument should be set as true as stipulated in the comment bloc.

https://github.com/woocommerce/woocommerce/blob/c2262ee3eff765f81d957a10f1cf08c7b4df4d46/includes/emails/class-wc-email-new-order.php#L99-L107

**Comment by roykho** [comment]
Hi @lomars - The behavior of this filter by default is actually correct. It is the docblock that is wrong. A PR has been submitted to fix this issue. Thanks for reporting.

**Comment by lomars** [comment]
Fine, good.

Note that this new filter behavior a lot of people think that there is a bug with new order notification, as before it was possible to send this notification multiple times. 
Thanks.

**Comment by WiredWonder** [comment]
There are scenarios where the customer enters their email wrong and the store owner needs to correct it and re-send the new order confirmation. Can this be reconsidered?
