### ISSUE TITLE
sync store to different sites

### ISSUE THREAD

**Issue by DeanForde** [woocommerce/woocommerce#29361]
ive been shopping around for a plugin that can sync my existing store to another wordpress site i have created, wholesale & retail i want to copy my store contents from my existing store to my new retail one, i want to maintain products, stock levels etc, it would be great to have a multistore and be able to mark up prices etc

**Comment by zhongruige** [comment]
Hi again @DeanForde! Hope you've been well recently :)

Unfortunately this is a bit out of the scope of what we work on in GitHub (primarily focusing on bug reports, feature requests etc.), so I'll be closing this issue. That said, I did do a quick search and there seems to be a few plugins out there that may fit your needs. One of which is [WooMultistore]( https://woomultistore.com/). It might be worth checking with them to see if they have the feature-set you're looking for. Additionally you can try asking in the support forums to see other recommendations from the community, which can be found [here](https://wordpress.org/support/plugin/woocommerce/).

Thanks!

**Comment by DeanForde** [comment]
sorry I meant this as a feature request haha the plugin you suggested does work very well also as I had already purchased it, I managed to resolve it however, thank you, would you remind removing this issue from the logs if you wouldnt mind?

**Comment by zhongruige** [comment]
Oh gotcha, thanks for following up @DeanForde! 

> would you remind removing this issue from the logs if you wouldnt mind

Glad you were able to get it resolved 😄 I can go ahead and delete this issue if that works!

**Comment by DeanForde** [comment]
I would really appreciate it, keeps my activity clean 😅😂

**Comment by zhongruige** [comment]
@DeanForde got it! Deleting it now :)
