### ISSUE TITLE
City is not a required field in Japan in Chrome - Payment Request API

### ISSUE THREAD

**Issue by ricardo** [woocommerce/woocommerce#29373]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

This isn't necessarily a bug, and is not a problem with WooCommerce specifically, but I think the only way to fix this is by changing WooCommerce.

In the [Stripe gateway extension](https://github.com/woocommerce/woocommerce-gateway-stripe) and other payment plugins that implement the Payment Request API, there's an issue with Japan in Chrome:

For some reason, Chrome doesn't support a city field if the country is Japan (see screenshot below), making it impossible to pay with the Payment Request API, because in WooCommerce the city is required.

![image](https://user-images.githubusercontent.com/5509901/111019443-03fe4900-839e-11eb-8ed6-c424857da635.png)

See 568-gh-woocommerce/woocommerce-gateway-stripe for more context.

**Possible solution**

Not really sure what could be done here, but perhaps a filter that doesn't make the city required would suffice.

**Expected behavior**

Trying to make a purchase using the Payment Request API with a shipping address in Japan should work.

**Actual behavior**

Trying to checkout will always result in the following error:

<img src="https://user-images.githubusercontent.com/5509901/111019473-3c058c00-839e-11eb-881e-cdef8addf48c.png" width="400px" />

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**

Steps to reproduce the bug:
1. Install the [Stripe gateway extension](https://wordpress.org/plugins/woocommerce-gateway-stripe/).
2. Make sure you have your test publishable and secret keys set in Stripe settings. The Payment Request Button option should also be enabled.
3. Make sure you have an HTTPS connection. (You may use [Ngrok](https://ngrok.io/)).
4. Add Stripe's test card as a payment method in chrome://settings/payments.
    CC number: `4242 4242 4242 4242`, Name: `STRIPE TEST CARD`, CVV: `123`, Expiration date: `12/25`.
4. Go to a simple product page with shipping and click the "Buy now" button.
5. Try to fill shipping address details and notice there's no city field in Japan.
6. Try to Pay using Stripe's test card.

**Isolating the problem (mark completed items with an [x]):**

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @ricardo,

Thanks for reporting the issue and sorry for the delayed response! I am adding the `needs developer feedback` label here so that one of the engineers on the WooCommerce Core team could take a look further.

**Comment by vedanshujain** [comment]
Looks like city is not a required field as per [Google's business API](https://developers.google.com/my-business/content/japan-address-format-spec) and prefecture is. We can add a `required => false` prop in `class-wc-countries as well for city field in JP.

**Comment by ricardo** [comment]
@vedanshujain, thanks for digging into this.

Other than Japan, I noticed there are several inconsistencies between the available fields in the address registration form in Safari and Chrome, and the required fields in WooCommerce.

I've done some digging here for the Payment Request feature in WooCommerce Payments, and there are inconsistencies between different browsers too (Safari and Chromium based browsers, from what I've noticed):
- 161/249 countries do not have a state field in Chrome.
- 60/249 countries do not have a zip/postal code field in Chrome.
- 6/249 countries do not provide a city field in Chrome (Japan is one case).

The required fields are a bit different in Safari.

Would a `required => false` fix still be applicable for all these instances, considering it can vary depending on browser? Or should we think about a more generic fix?

One idea could be passing a parameter to WooCommerce to check if the request came from the Payment Request API, and in that case, if certain fields are null (zip code, state or city), then that means they're not available or required from the Payment Request address form. The Payment Request address form already handles some validation of required fields, so we could delegate this validation to it in case that parameter is present.

**Comment by ricardo** [comment]
I did some more research into each specific country for the Payment Request address dialog in Chrome, and I found that Chrome does not provide a city field for these countries, while WC expects it:
- JP (Japan)
- MO (Macao)
- TN (Tunisia)
- KY (Cayman Islands)
- GI (Gibraltar).

To test it, simply go to chrome://settings/addresses.

**Comment by vedanshujain** [comment]
This was discussed internally, and we will be going with proper support for payment gateway APIs instead of modifying the list in the core. That progress will be tracked in #29795
