### ISSUE TITLE
Update docs for e2e package to no longer refer to Travis

### ISSUE THREAD

**Issue by peterfabian** [woocommerce/woocommerce#29381]
We've migrated from Travis to GH actions, but the e2e test package still refers to Travis in some places, e.g. the docs on the setup in CI and makes use of Travis environment variables. It should be updated to our latest CI tooling.

**Comment by rrennick** [comment]
@peterfabian Thanks for reporting this. Because our E2E tooling is distributed as npm packages we will continue to support the Travis environment variables. However, we should add more generic support for other CI environments.
