### ISSUE TITLE
Make the ReST API list all products independent from the option to not show out of stock products

### ISSUE THREAD

**Issue by d3v3lop3rDE** [woocommerce/woocommerce#29402]
**Is your feature request related to a problem? Please describe.**
I want to list all of my products via the rest API, but they are filtered when the option to not show out of stock products is active

**Describe the solution you'd like**
Please make it independent from this option, as the endpoint doesnt deliveres what it promises

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ObliviousHarmony** [comment]
Hello @d3v3lop3rDE,

From our testing, both the `/wc/v2/products` and `/wc/v3/products` API endpoints return out of stock products when the option is enabled. We managed to replicate your problem in the `/wc/v1/products` endpoint, but this is a deprecated endpoint.
