### ISSUE TITLE
Refund api using Woocommerce rest api gives server error (500)

### ISSUE THREAD

**Issue by usama-govsoft** [woocommerce/woocommerce#29407]
This is the documentation provided by the Woocommerce. 

https://woocommerce.github.io/woocommerce-rest-api-docs/?javascript#create-a-refund

Whenever i hit refund, it gives me code error of 500.

The Code :

export const addRefundAmountInOrder = (orderId) => async (dispatch) => {
  let data = {
    amount: "10.00",
  };
  try {
    const res = await api.post(`orders/${orderId}/refunds`, data);
    console.log(res.data, "refund response.....");
  } catch (error) {
   console.log(error)
  }
};

**Comment by roykho** [comment]
Hi @usama-govsoft - could you please provide the exact code you're using?
