### ISSUE TITLE
PLEASE CLOSE THIS TICKET AS THE ISSUE HAS BEEN RESOLVED IN CURRENT VERSION

### ISSUE THREAD

**Issue by ecottles** [woocommerce/woocommerce#29401]
**Prerequisites (mark completed items with an [x]):**
- [X] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [X] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

PLEASE CLOSE THIS TICKET AS THE ISSUE HAS BEEN RESOLVED IN CURRENT VERSION

Hello,

Woo v_5.1.0

When editing a order line item the inventory is not reduced when the order item quantity is changed from 1(one) to 0(zero)

The product inventory count is not reduced when quantity is set at 0(zero) from 1(one).

NOTE: When reducing inventory from 2(two) to 1(one) the product inventory count is reduced as expected.

This behavior occurs only when order line item quantity is 1(one) then changed to 0(zero).

Reproduce behavior:

1. Set the quantity of an order item to 2(two) then save.
2.  Make a note of the product inventory count.
3. Set the quantity of an order item to 1(one) then save.
4.  Make a note of the product inventory count.
5. Set the quantity of an order item to 0(zero) then save.
6.  Make a note of the product inventory count.

You will see that the product inventory is not reduced when the quantity of an order item is set to 0(zero) from 1(one).

Good Day

**Comment by juliaamosova** [comment]
Hi @ecottles,

Thanks for raising the issue! Glad to hear it's been resolved for you. 

>PLEASE CLOSE THIS TICKET AS THE ISSUE HAS BEEN RESOLVED IN CURRENT VERSION

Thanks! I'll go ahead and close this thread. Please feel free to comment back in case you'd like us to take a look further.
