### ISSUE TITLE
GH Action for automatically milestoning PRs when they are merged

### ISSUE THREAD

**Issue by vedanshujain** [woocommerce/woocommerce#29423]
**Is your feature request related to a problem? Please describe.**
It's very important to track what PRs are included with what release for transparency and easier look back. Right now this process is manual and is therefore subjected to manual mistakes.

**Describe the solution you'd like**
A GH action which automates this, and assign PR with newest milestone when they get merged.

**Comment by jeherve** [comment]
> A GH action which automates this, and assign PR with newest milestone when they get merged.

Dropping by to note that we're currently working on making Jetpack's take on this issue publicly available as an action. This is happening here, and should be merged soon:
https://github.com/Automattic/jetpack/pull/19239

The action includes a few different tasks that may be interesting for y'all for project management, and automattic milestone management is one of those things.

**Comment by claudiosanches** [comment]
@jeherve Thank you for sharing it. I'm following Jetpack GH actions and you all are doing a great work!

**Comment by vedanshujain** [comment]
Completed in #29699
