### ISSUE TITLE
Aggressive `set_time_limit()` use lowers maximum execution time and leads to unexpected behavior in CLI

### ISSUE THREAD

**Issue by jeremyfelt** [woocommerce/woocommerce#29428]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

This exists in a few parts that have all come together to help my confusion. Sorry for the detail. 😄 

With WooCommerce activated, whenever a `WP_CLI` command is run, whether or not it is a WC command, [WC fires](https://github.com/woocommerce/woocommerce/blob/87a17aed5e425534dce2263fb885d2a050da68ae/includes/cli/class-wc-cli-runner.php#L59) the `rest_api_init` hook, which causes all (most?) endpoints to register.

Among the endpoints registered is the store checkout, which provides [gateway information as part of its schema](https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/7639d1f8242342801c326ba16dc06827c49224b4/src/StoreApi/Schemas/CheckoutSchema.php#L117).

This causes each registered gateway to initialize. In my case, the [Stripe gateway loads](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4d0841cb0f26297eff88a90700735303585517f4/includes/class-wc-gateway-stripe.php#L208) its `stripe-settings.php` file, and because I'm working locally and am not yet connected to Stripe, makes an HTTP request to woocommerce.com to gather more information.

That HTTP request is configured to have a timeout of 60 seconds. To ensure that PHP does not timeout before HTTP, WC uses `wc_set_time_limit( $http_timeout + 10 )` to [override the existing PHP maximum execution time](https://github.com/woocommerce/woocommerce-gateway-stripe/blob/4d0841cb0f26297eff88a90700735303585517f4/includes/connect/class-wc-stripe-connect-api.php#L115-L116) with a value of `70`.

And at about 70 seconds or so into my long-ish running WP-CLI script, I get a fatal error.

I can correct this by setting `set_time_limit()` inside my WP-CLI command, but I should generally be able to rely on PHP's default of `0` (unlimited) when in the CLI context OR on a value I set elsewhere.

WooCommerce [handles this somewhat better](https://github.com/woocommerce/action-scheduler/blob/c899c34a06a987c5143218672c6c9e544c73fed4/classes/ActionScheduler_Compatibility.php#L88) in the action scheduler's `raise_time_limit` method, which checks to see if the new limit is less than the existing limit before overwriting it. However, that also fails to account for a `0` value.

**Proposed approach:** Refactor `wc_set_time_limit()` OR introduce a `wc_raise_time_limit()` that uses the logic from the action scheduler's `raise_time_limit` and only sets the time limit higher, never lower. Apply this everywhere that that the time limit is updated now.

```
function raise_time_limit( $new_limit ) {
    $limit = (int) ini_get( 'max_execution_time' );

    // If the existing limit is already 0, or the new limit is less than the old limit (and not 0), bail.
    if ( 0 === $limit || ( 0 !== $new_limit && $new_limit <= $limit ) ) {
        return;
    }

    if ( function_exists( 'set_time_limit' ) && false === strpos( ini_get( 'disable_functions' ), 'set_time_limit' ) && ! ini_get( 'safe_mode' ) ) {
        @set_time_limit( $limit );
    }
}
```
**Expected behavior**

If my environment's `ini_get( 'max_execution_time' )` is `0` when I first run a WP-CLI script, the command should not timeout.

**Actual behavior**

WooCommerce lowers the maximum execution time when initializing gateways and my command times out.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Activate WooCommerce
2. Activate WooCommerce Stripe Payment Gateway
3. Don't fully connect the Stripe Payment Gateway
4. Write a long-running WP-CLI command
5. Run the long-running WP-CLI command
6. See error

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>

### WordPress Environment ###

WordPress address (URL): N/A
Site address (URL): N/A
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.1.2
Log Directory Writable: ❌ To allow logging
make [N/a] writable or define a custom WC_LOG_DIR.

WP Version: 5.7
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.19.6
PHP Version: 7.4.13
PHP Post Max Size: 512 MB
PHP Time Limit: 70
PHP Max Input Vars: 1000
cURL Version: 7.74.0
(SecureTransport) OpenSSL/1.1.1i

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.8-MariaDB
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.1.0
WC Database Prefix: wp_
N/A

### Post Type Counts ###

N/A

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

WooCommerce Admin: by WooCommerce – 2.1.2
WooCommerce Stripe Gateway: by WooCommerce – 5.0.0
WooCommerce Shipping & Tax: by Automattic – 1.25.9
WooCommerce: by Automattic – 5.1.0
// extra, non-applicable plugins removed

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5 - /shop/
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: NA
Version: 1.0
Author URL: http://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 3
Oldest: 2021-02-18 11:14:01 +0000
Newest: 2021-03-18 23:41:51 +0000

### Status report information ###

Generated at: 2021-03-18 23:55:37 +00:00
</details>

**Comment by ObliviousHarmony** [comment]
Hi @jeremyfelt,

Thank you for taking the time to report this bug, we really appreciate your help. I have verified that `WP_CLI` commands excessively load REST endpoints. I haven't looked deeply at the gateway-specific consequence, but I don't think it makes a difference in my assessment.

When we peel away the layers of this bug I see two different concerns:

1. There is no support in WooCommerce Core for an extension to raise the timeout instead of setting it. I don't really see this as a problem, as I'm not sure manipulating the PHP environment is something WooCommerce should do. While it's true that there's a `wc_set_time_limit` wrapper, I would rather discourage the use than support more cases.
2. WooCommerce should not be initializing the REST API for CLI commands that aren't going to use it. This seems very heavy-handed and likely results in some interesting situations.

**Comment by jeremyfelt** [comment]
> I'm not sure manipulating the PHP environment is something WooCommerce should do

Agreed! :)

> WooCommerce should not be initializing the REST API for CLI commands that aren't going to use it.

And agreed!

**Comment by ObliviousHarmony** [comment]
@jeremyfelt I've created a new issue for tracking that specific defect.
