### ISSUE TITLE
Upgrading from 4.9 or lower version - Cannot update db version to 5.1.0

### ISSUE THREAD

**Issue by AashikP** [woocommerce/woocommerce#29430]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

If you're upgrading from WooCommerce 4.9 or lower, your DB version stays at 5.0.0 and does not reach 5.1.0

**Expected behavior**

DB version should always match the WooCommerce version:

![https://d.pr/i/Q7Bnjt+](https://d.pr/i/Q7Bnjt+)

**Actual behavior**

If you're upgrading from 5.0.0 to 5.1.0, the db version matches, but if you're upgrading from 4.9 or lower (tested 4.7), the db version stays at 5.0.0 even after a successful DB update notification

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Upgrade your WooCommerce installation from 4.9.0 to 5.1.0
2. Click on the db update notification 
3. Notice the scheduled actions:
    ![https://d.pr/i/QhonHw+](https://d.pr/i/QhonHw+)
4. Check the database version in System Status Report to confirm that it is 5.0.0 even if WooCommerce is 5.1.0
5. Try the database update too from **WooCommerce > Status > Tools > Update database > Click - Update (Button on right)**
6. Notice that there are no actions scheduled for DB update **WooCommerce > Status > Scheduled Actions > Pending**

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
Any. WC Version: 4.9.0 and lower

**Comment by roykho** [comment]
So we've discussed this before and we're still in need to come up with a long term solution to this. But meanwhile if the DB version doesn't match, it is quite normal. So for an interim "fix" for this -- we will update the tooltip to note that the version may not be the same and it is normal.

**Comment by AashikP** [comment]
Thank you for the fix @roykho  and @vedanshujain. 

I think this arises a question about how to identify the latest version of the WooCommerce database if it no longer matches the WooCommerce version?
