### ISSUE TITLE
Importing cross-sell variable products using built-in Product CSV Importer and Exporter: First imported cross-sell product shows `Import placeholder`

### ISSUE THREAD

**Issue by wpniall** [woocommerce/woocommerce#29434]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Importing cross-sell variable products using the WooCommerce built-in Product CSV Importer and Exporter results in the first imported cross-sell showing with the following format on the backend and frontend: `Import placeholder [SKU]`. The subsequent cross-sells do not have the same problem and import correctly.

**Expected behavior**
I expected that all cross-sell variable products imported via CSV would be imported into each product correctly.

**Actual behavior**
I managed to reproduce the bug by importing variable products as cross-sells. I also tried to import the cross-sell products using the `id:27` format as well as using SKUs, but the same issue happens. The same behavior does not happen when importing simple products. And it does not matter whether the cross-sell was set up on a product or not.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to **Tools > Import**, and select the **WooCommerce products (CSV)** option
2. Select the **Update existing products** checkbox: https://d.pr/i/kHaWY5
2. Import a CSV file containing one or more cross-sell products, whether using the `ids` or `skus` following the Product CSV Import Schema: https://github.com/woocommerce/woocommerce/wiki/Product-CSV-Import-Schema#csv-columns-and-formatting
3. Go to the product edit page for the product that was updated to reflect the cross-sells
4. An `Import placeholder for [SKU]` product shows on both the backend edit product page and frontend cart page, but only for the first cross-sell product

**Screenshots**

**Importing 1 cross-sell variable product to a product that has the same variable product set up as a cross-sell:**

* Backend showing 1 existing cross-sell product **before** importing: https://d.pr/i/h9Cx2r
* Frontend showing the 1 cross-sell product **before** importing: https://d.pr/i/7lbgAX
* Backend showing 1 existing cross-sell product **after** importing: https://d.pr/i/DrXHWB
* Frontend showing the 1 cross-sell product **after** importing: https://d.pr/i/PPZyeS

**Here's what happens with 2 existing cross-sells:**

* Backend showing 2 existing cross-sell products **before** importing: https://d.pr/i/IZ0zmS
* Backend showing 2 existing cross-sell products **after** importing: https://d.pr/i/G7oR1D
* Frontend showing the 2 cross-sell products **after** importing: https://d.pr/i/qX9Kvq

The same behavior happens when importing 1 or more cross-sells that were **not** already set up on a product.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

Reported in 3832666-zen

**WordPress Environment**

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://woodefaulttest.mystagingwebsite.com
Site address (URL): https://woodefaulttest.mystagingwebsite.com
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.2
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.4.16
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.75.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.25-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.1.0
WC Database Prefix: wp_
Total Database Size: 5.87MB
Database Data Size: 3.90MB
Database Index Size: 1.97MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.11MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.05MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.42MB + Index: 0.31MB + Engine InnoDB
wp_posts: Data: 0.17MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_bookings_availabilitymeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_booking_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_points_rewards_user_points_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_warranty_products: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_mywhishlist: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 78
customize_changeset: 1
nav_menu_item: 5
page: 16
post: 2
product: 45
product_variation: 38
revision: 18
shop_coupon: 9
shop_order: 12
shop_order_refund: 3
wc_booking: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 5.1.0

### Inactive Plugins (32) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Braintree for WooCommerce Payment Gateway: by WooCommerce – 2.5.0
Code Snippets: by Code Snippets Pro – 2.14.1
Creative Mail by Constant Contact: by Constant Contact – 1.3.4
Facebook for WooCommerce: by Facebook – 2.3.2
FME Addons: Shop as a Customer for WooCommerce: by fmeaddons – 1.0.7
Google Ads & Marketing by Kliken: by Kliken – 1.0.7
Jetpack by WordPress.com: by Automattic – 9.5.2
Klarna Payments for WooCommerce: by krokedil
klarna
automattic – 2.4.1

Mailchimp for WooCommerce: by Mailchimp – 2.5.1
My Wish List for WooCommerce: by WP1 – 1.0.7
Rapyd Payments: by Rapyd – 1.0.5
Storefront Parallax Hero: by WooCommerce – 1.5.7
Storefront Powerpack: by WooCommerce – 1.5.0
Storefront Pricing Tables: by WooCommerce – 1.1.0
WooCommerce Account Funds: by Themesquad – 2.3.9 (update to version 2.3.10 is available)
WooCommerce Additional Variation Images: by WooCommerce – 1.9.0
WooCommerce AvaTax: by SkyVerge – 1.11.2
WooCommerce Bookings: by WooCommerce – 1.15.35 (update to version 1.15.37 is available)
WooCommerce Bulk Stock Management: by WooCommerce – 2.2.31
WooCommerce Customer/Order/Coupon CSV Import Suite: by SkyVerge – 3.10.0 (update to version 3.10.1 is available)
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.3.0 (update to version 5.3.2 is available)
WooCommerce EU VAT Number: by WooCommerce – 2.3.25
WooCommerce Payments: by Automattic – 2.1.0
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.1
WooCommerce Points and Rewards: by WooCommerce – 1.6.43
WooCommerce Product CSV Import Suite: by WooCommerce – 1.10.39
WooCommerce Purchase Order Payment Gateway: by WooCommerce – 1.2.12
WooCommerce Shipping & Tax: by Automattic – 1.25.9
WooCommerce Stripe Gateway: by WooCommerce – 5.0.0
WooCommerce Warranty Requests: by WooCommerce – 1.9.21 (update to version 1.9.22 is available)
WordPress Importer: by wordpressdotorg – 0.7

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
exclude_from_catalog (exclude_from_catalog)
exclude_from_search (exclude_from_search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: ❌ Page visibility should be public
Cart: #6 - /cart/
Checkout: #7 - /checkout/
My account: #8 - /my-account/
Terms and conditions: #198 - /terms-and-conditions/

### Theme ###

Name: Storefront
Version: 3.5.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 272
Oldest: 2021-02-26 00:53:05 +0000
Newest: 2021-03-19 10:42:35 +0000

Pending: 2
Oldest: 2021-03-20 00:55:13 +0000
Newest: 2021-03-20 00:55:13 +0000


### Status report information ###

Generated at: 2021-03-19 10:43:01 +00:00
`
```
</details>

**Comment by juliaamosova** [comment]
Hi @wpniall,

Thank you for submitting the issue. However, I can’t reproduce it. Everything is working as expected on my end. However, I believe some of the steps to reproduce the issue are missing.

Please see the screen recording below that shows the steps that I am taking. What I am doing there is exporting products from one site to another brand new site with no products. I can't select the `Update existing products` checkbox because there is also a condition in that option that `Products that do not exist will be skipped.` - given that the site where I am importing products to had no products, I can't select that option:


https://user-images.githubusercontent.com/19143190/111919472-8c48b200-8a60-11eb-8292-a469c3bf0f14.mov

With that in mind, can you please let me know what steps am I missing? Do I need to update existing products on the existing site? If so, what edits do I need to do to the product after I first import it?

**Comment by wpniall** [comment]
Hi @juliaamosova Thanks for your feedback. I'll need some time respond and try to explain things a bit better, as I found the issue a little hard to explain.

**Comment by wpniall** [comment]
@juliaamosova I've updated the report to hopefully make it easier to understand and replicate, as I do think I missed out a few key points here. Please let me know if you have any further questions or issues.

**Comment by swatipawarGS** [comment]
Hi @wpniall,

Thank you for taking the time to report this bug, we really appreciate your help. I can't reproduce it on my end using WooCommerce 5.9.0 version.





Below are the screenshots documenting my experience:



Backend showing 1 existing cross-sell product before and after  importing :

![#29434(backend(1))](https://user-images.githubusercontent.com/94531721/142611117-3b0eb804-4cb0-4ec3-9930-3e8783caa681.jpg)

Backend showing 2 existing cross-sell products before and after importing :

![#29434(backend(2))](https://user-images.githubusercontent.com/94531721/142611207-44d55f75-fe74-493a-b79c-62ab77e85f0d.jpg)


Frontend showing the 1 cross-sell product before and after  importing :

![#29434(Forntend(1))](https://user-images.githubusercontent.com/94531721/142611294-f5deaaeb-2434-40ff-b4b2-fde067a035d6.jpg)


Frontend showing the 2 cross-sell products before and after importing :

![#29434(Forntend(2))](https://user-images.githubusercontent.com/94531721/142611359-1f4a55f9-6c55-459e-88c6-24ced6244191.jpg)

**Comment by swatipawarGS** [comment]
Hi @wpniall  ,

We retested this issue again using WooCommerce 5.9.0  version but we are unable to reproduce this issue at our end.

Please find below screencast documenting for reference :

https://user-images.githubusercontent.com/94531721/143464120-1217a12e-8e6a-4156-8f1a-4721dea69803.mp4

Please provide us with more details and any additional steps required to repro this issue which may help us to evaluate it further.

**Comment by wpniall** [comment]
Hi @swatipawarGS, sorry for the delayed response. I can't seem to reproduce the problem either even after following my steps above.
