### ISSUE TITLE
Ditching jQuery?

### ISSUE THREAD

**Issue by wayheming** [woocommerce/woocommerce#29433]
Hello WooCommerce team,
Can you please tell me if you ever plan to abandon jQuery? At least on the frontend so that we can also abandon it and stop connecting it on the page.
Thank you.

**Comment by chyvak1831** [comment]
@wayheming here another task about jquery dropping, but unclear why is became closed...
#18395

**Comment by wayheming** [comment]
@chyvak1831 yes, I saw it, but since it is closed, I decided to find out what they are planning

**Comment by ObliviousHarmony** [comment]
Hello @wayheming,

There are currently no plans to remove the jQuery dependency from our existing JavaScript. We are currently developing [WooCommerce Blocks for the customer experience](https://wordpress.org/plugins/woo-gutenberg-products-block/), as well as [WooCommerce Admin for the merchant experience](https://wordpress.org/plugins/woocommerce-admin/)

**Comment by wayheming** [comment]
@ObliviousHarmony thank you

**Comment by chyvak1831** [comment]
@ObliviousHarmony could you please explain how "woocommerce blocks" related to jquery dependencies?
is this means that in future, when all will be rebuild into block - it already will be without jquery?

**Comment by wayheming** [comment]
@chyvak1831 I think he meant that the company has other priorities now

**Comment by 1ucay** [comment]
Yes please, more bloatware and ads in admin over speed improvement of client browsers.

**Comment by ObliviousHarmony** [comment]
What I meant is that it seems wasteful to rewrite all of WooCommerce Core's JavaScript to remove the jQuery dependency when we're also creating blocks for the frontend. Given how significant an undertaking removing it is, especially given some of the plugins we use, there are likely better avenues for modernization and performance enhancement. This is not an immediate solution, but removing jQuery wouldn't be either.
