### ISSUE TITLE
postalcode are hidden for Guatemala

### ISSUE THREAD

**Issue by queoferton** [woocommerce/woocommerce#29446]
We updated woocommerce to version: 5.1 in Guatemala and we cannot se the postalcode during checkout. Please solve ASAP.

**Comment by tammullen** [comment]
Hi @queoferton,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/29123. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
