### ISSUE TITLE
Product Not Synced with Square

### ISSUE THREAD

**Issue by blessedhealthynatural** [woocommerce/woocommerce#29449]
I have 321 products in my website inventory.  In February, I believe, I added a category called Gemstones & Crystals.  Since then, non of the products in that category have been syncing with Square.
Additionally, some items that were added from other categories since February are not fully updating in Square.  For example, the pictures for the products have not updated or are completely missing.
I have moved items from one category to another and the only way they update in Square is if I manually go into each item and change the category.
I have Bulk selected the items that do not appear in Square and Edit them to sync with Square.  I have actually done this two or three times, and still I do not see the item update in Square.
I have added the category in Square, and STILL none of the products have updated.
I have added individual items in Square being sure to include the SKU, and STILL none of the products has updated.  I took a screenshot of this in WordPress to show the error and where I was in the individual item.
I changed categories for products on the website, and the only way I could get them to update in Square was to go into my Square and change the item.

I don't have time to do double work.  This is ridiculous.  And I have seen on the forum how this is an ongoing problem for well over 1 year.

Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by tammullen** [comment]
Hi @blessedhealthynatural 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce Core bugs only. 

The issue you are having seems to be caused by the WooCommerce Square plugin which is one of the products on our marketplace. To get further technical support for it, please contact WooCommerce helpdesk by [opening a ticket](https://woocommerce.com/contact-us/).

**Comment by blessedhealthynatural** [comment]
Thank you for your response.
