### ISSUE TITLE
Order line item adjust stock is limited to statuses processing, completed & on-hold.

### ISSUE THREAD

**Issue by ecottles** [woocommerce/woocommerce#29448]
Hello,

Adjust line item stock is limited to statuses processing, completed & on-hold. 

Stock can no longer be adjusted with custom order statuses as a result of the change.

The following fix as described in 4.9

Stock management fixes:

3. Only adjust line item stock when order is in `processing`, `completed` or `on-hold` status state, because we need to reduce stocks on these status only. Stock adjustments in refunds or when changing statuses is already taken care of by their specific hooks.

Please add filter here as we use custom order statuses.

Good Day

_Originally posted by @ecottles in https://github.com/woocommerce/woocommerce/issues/27504#issuecomment-803396693_

**Comment by roykho** [comment]
Hi @ecottles - thanks for bringing this up however I believe you can already achieve this. If you have already added your custom order statuses you can use this action `add_action( 'woocommerce_order_status_YOUR_CUSTOM_STATUS', 'wc_maybe_reduce_stock_levels' );`

With this work around available, I will be closing this issue.

**Comment by ecottles** [comment]
Hello,

This issue was closed, however the issue persists.
**roykho** responded to the issue with the following:
Hi @ecottles - thanks for bringing this up however I believe you can already achieve this. If you have already added your custom order statuses you can use this action add_action( 'woocommerce_order_status_YOUR_CUSTOM_STATUS', 'wc_maybe_reduce_stock_levels' );

Then Closed the Issue.

The filter you describe is fine for cart transactions. but not when the admin a saving an order.

This change affects admins ability to maybe reduce stock when saving an order with a status other than >>> processing', 'completed', 'on-hold'. <<< **There is no filter to change this behavior.

If you look at the code you will see, function wc_maybe_adjust_line_item_product_stock( $item ); has been wrapped with an if statement limiting to three statuses. >>> processing', 'completed', 'on-hold'. <<< If the admin saves an order with any other status than one of the three, function wc_maybe_adjust_line_item_product_stock( $item ); **WILL  NEVER FIRE.**

There is no filter to change this behavior.
Should have never been done in the first place. Why the limitation?

**Within function wc_save_order_items:**
Line 345;
if ( in_array( $order->get_status(), array( 'processing', 'completed', 'on-hold' ) ) ) {
    $changed_stock = wc_maybe_adjust_line_item_product_stock( $item );
    if ( $changed_stock && ! is_wp_error( $changed_stock ) ) {
        $qty_change_order_notes[] = $item->get_name() . ' (' . $changed_stock['from'] . '&rarr;' . $changed_stock['to'] . ')';
     }
}

There is no filter to change this behavior.

A filter is absolutely necessary or remove the if statement.

Good Day

Originally posted by @ecottles in #27504 (comment) @

**Comment by roykho** [comment]
@ecottles - can you please document detailed steps you're wanting to do and what custom code you have?

**Comment by ecottles** [comment]
Hello,

I have custom statuses that no longer can use fuction **wc_maybe_adjust_line_item_product_stock** when saving an order with a status other than >>> processing', 'completed', 'on-hold'. This change happened in v_4.9.

**This change affects ADMINS ability to maybe reduce stock when saving an order with a status other than >>> processing', 'completed', 'on-hold'.** <<< **There is no filter to change this behavior.

If you look at the code you will see, function wc_maybe_adjust_line_item_product_stock( $item ); has been wrapped with an if statement limiting to three statuses. >>> processing', 'completed', 'on-hold'. <<< If the admin saves an order with any other status than one of the three, function wc_maybe_adjust_line_item_product_stock( $item ); WILL NEVER FIRE.

There is no filter to change this behavior.
Should have never been done in the first place. Why the limitation?

Within function wc_save_order_items:
Line 345;
if ( in_array( $order->get_status(), array( 'processing', 'completed', 'on-hold' ) ) ) {
$changed_stock = wc_maybe_adjust_line_item_product_stock( $item );
if ( $changed_stock && ! is_wp_error( $changed_stock ) ) {
$qty_change_order_notes[] = $item->get_name() . ' (' . $changed_stock['from'] . '→' . $changed_stock['to'] . ')';
}
}

There is no filter to change this behavior.

A filter is absolutely necessary or remove the if statement.

Furthermore within function wc_maybe_adjust_line_item_product_stock there is a useful filter woocommerce_prevent_adjust_line_item_product_stock  that a custom status can no longer use because 'processing', 'completed', 'on-hold are the only status allowed a result of the change. If you study the issue that that caused the change you will learn that the wrapping function wc_maybe_adjust_line_item_product_stock in the if statement limiting the status to 'processing', 'completed', 'on-hold had nothing to do with the issue. It was arbitrarily changed by the code author.


Good Day

**Comment by roykho** [comment]
Hi there,

So I've tested different ways and all of them works as I expected. So requires more code than others but nevertheless it works. Here is an example snippet of how you can get that to work on admin side as you're wanting.

```
function mycustom_register_post_statuses() {
register_post_status( 'wc-mycustom-status', array(
'label' => _x( 'My Custom Status', 'WooCommerce Order status', 'text_domain' ),
'public' => true,
'exclude_from_search' => false,
'show_in_admin_all_list' => true,
'show_in_admin_status_list' => true,
'label_count' => _n_noop( 'Order (%s)', 'Order (%s)', 'text_domain' )
) );
}
add_filter( 'init', 'mycustom_register_post_statuses' );

function mycustom_add_order_statuses( $order_statuses ) {
$order_statuses['wc-mycustom-status'] = _x( 'My Custom Status', 'WooCommerce Order status', 'text_domain' );
return $order_statuses;
}
add_filter( 'wc_order_statuses', 'mycustom_add_order_statuses' );

add_action( 'woocommerce_order_status_mycustom-status', 'wc_maybe_reduce_stock_levels' );
```

And I understand you stated it was changed in 4.9 and we'll look into that but for the interim, this solution should work for you.

**Comment by calyweb** [comment]
Hi,
This is not solved at all, ecottles is right, your solution don't work when we adjust a line item directly on an admin order
If the order is in a custom status while we are adjusting a line, nothing is deducted, and it's because of your code in wc_save_order_items() :
if ( in_array( $order->get_status(), array( 'processing', 'completed', 'on-hold' ), true ) ) {
				$changed_stock = wc_maybe_adjust_line_item_product_stock( $item );
				if ( $changed_stock && ! is_wp_error( $changed_stock ) ) {
					$qty_change_order_notes[] = $item->get_name() . ' (' . $changed_stock['from'] . '&rarr;' . $changed_stock['to'] . ')';
				}
			}

So if i add a position (or adjust if) in a custom status, nothing happen, no stock is reduced ...
