### ISSUE TITLE
woocommerce title templates having issues override with child themes

### ISSUE THREAD

**Issue by iamarpitpatidar** [woocommerce/woocommerce#29451]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Woocommerce templates are working great. except the title template. Its not overriding, to check I tried changing the classes, title tag (H1 -> H2), removed classes. nothing got override.

**Steps to reproduce the bug**
Steps to reproduce the bug:
1. Copy `wp-content/plugins/woocommerce/templates/single-product/title.php` to `wp-content/themes/child-theme/woocommerce/single-product/title.php`
2. Try editing anything.
3. Now go to single product page.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

WordPress address (URL): https://www.bestescort.dk
Site address (URL): https://www.bestescort.dk
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.2
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 205 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.16
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.28-MariaDB-1:10.3.28+maria~focal
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.1.0
WC Database Prefix: www0_
Total Database Size: 10.33MB
Database Data Size: 8.30MB
Database Index Size: 2.03MB
www0_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
www0_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
www0_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
arpit: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
www0_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
www0_duplicator_pro_entities: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_duplicator_pro_packages: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_nf3_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_nf3_action_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_nf3_chunks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_nf3_field_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
www0_nf3_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_nf3_form_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_nf3_objects: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_nf3_object_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_nf3_upgrades: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_options: Data: 4.02MB + Index: 0.08MB + Engine InnoDB
www0_postmeta: Data: 1.36MB + Index: 0.34MB + Engine InnoDB
www0_posts: Data: 1.17MB + Index: 0.14MB + Engine InnoDB
www0_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
www0_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_revslider_sliders: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
www0_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_revslider_slides: Data: 0.03MB + Index: 0.00MB + Engine InnoDB
www0_revslider_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
www0_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_um_metadata: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
www0_usermeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
www0_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
www0_user_registration_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
www0_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
www0_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
www0_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
www0_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
www0_wpuf_subscribers: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
www0_wpuf_transaction: Data: 0.02MB + Index: 0.06MB + Engine InnoDB

### Post Type Counts ###

attachment: 467
custom_css: 1
customize_changeset: 9
nav_menu_item: 9
page: 14
polylang_mo: 2
post: 1
product: 87
product_variation: 1
revision: 110
shop_order: 14
testimonial: 3
um_directory: 1
um_form: 3
user_registration: 1
vc_grid_item: 2
wpforms: 1
wpuf_forms: 2
wpuf_input: 12

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

One.com Analytics and Online Marketing: by  – 2.12.u
Classic Editor: by WordPress Contributors – 1.6
Drag and Drop Multiple File Upload - Contact Form 7: by Glen Don L. Mongaya – 1.3.5.9
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.16.2
GTranslate: by Translate AI Multilingual Solutions – 2.8.61
WPBakery Page Builder: by Michael M - WPBakery.com – 6.5.0
Kirki Customizer Framework: by David Vongries – 3.1.6
Performance Cache: by one.com – 0.2.11
Slider Revolution: by ThemePunch – 6.3.6
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.50

User Registration Advanced Fields: by WPEverest – 1.3.5.1
User Registration Extras: by WPEverest – 1.0.3
User Registration File Upload: by WPEverest – 1.2.1
User Registration: by WPEverest – 1.9.5
WooCommerce: by Automattic – 5.1.0
WP phpMyAdmin: by Puvox.software – 5.0.4.1
WPForms Lite: by WPForms – 1.6.5

### Settings ###

API Enabled: –
Force SSL: –
Currency: DKK (DKK)
Currency Position: right
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: booking (booking)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #2035 - /annoncer/
Basket: ❌ Page ID is set
but the page does not exist

Checkout: ❌ Page ID is set
but the page does not exist

My account: ❌ Page ID is set
but the page does not exist

Terms and conditions: ❌ Page not set

### Theme ###

Name: Modellic Child
Version: 1.0
Author URL: http://themeforest.net/user/coffeecream
Child Theme: ✔
Parent Theme Name: Modellic
Parent Theme Version: 3.4.5
Parent Theme Author URL: http://themeforest.net/user/coffeecream
WooCommerce Support: ✔

### Templates ###

Overrides: modellic-child/woocommerce/content-single-product.php
modellic/woocommerce/loop/loop-end.php
modellic/woocommerce/loop/loop-start.php
modellic-child/woocommerce/single-product/meta.php
modellic/woocommerce/single-product/product-attributes.php
modellic-child/woocommerce/single-product/title.php

### Action Scheduler ###

Complete: 61
Oldest: 2021-03-20 16:18:57 +0100
Newest: 2021-03-20 19:26:19 +0100

Pending: 3
Oldest: 2021-03-21 01:00:00 +0100
Newest: 2021-03-27 16:18:57 +0100

### Status report information ###

Generated at: 2021-03-20 20:11:56 +01:00
```
</details>

**Comment by tammullen** [comment]
Hi @iamarpitpatidar 

Thanks for raising this issue.

Can you provide more details of the error you are seeing, can you copy it into this issue?

In addition to that, I just want to double check if you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate **all** plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by iamarpitpatidar** [comment]
well I did, checked but lemme do it again for you and I'll report back

**Comment by juliaamosova** [comment]
Hi @iamarpitpatidar! 

Please let us know if you have any further findings to report on this issue?
