### ISSUE TITLE
Unable to load Analytics settings.

### ISSUE THREAD

**Issue by priya-webkul** [woocommerce/woocommerce#29463]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Under Analytics-> The settings submenu in the Analytics menu is not loading and if the user goes to any other submenu after visiting it, then other submenus are also not showing any content.
Testing Environment
WooCommerce version: Version 5.1.0
**Expected behavior**
The settings page should load if the user directly visits by clicking the settings sub-menu from the Analytics menu. And, other menu pages should work if the user switches from settings to other sub-menu.

**Actual behavior**
Settings submenu in the Analytics menu is not loading any content and if the user goes to any other submenu switching from the settings sub-menu, then other submenus are also not showing any content.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to ' Hover on the Analytics menu'
2. Click on ' settings submenu directly by hovering Analytics menu'
3. See error ' no content displayed'
4. Now visit other submenus by clicking them, no content displayed there as well.

**Screenshots**
![analytics-settings](https://user-images.githubusercontent.com/81230387/112135747-23923e80-8bf4-11eb-9b13-c6003f9734e5.png)
![analutics-other-menu](https://user-images.githubusercontent.com/81230387/112135963-5fc59f00-8bf4-11eb-8e76-c7f5eab49362.png)

Screenshot link : https://prnt.sc/10tdic3
https://prnt.sc/10tdj4i

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by tammullen** [comment]
Hi @priya-webkul 

Thanks for raising this issue, Analytics is part of WooCommerce Admin which is being developed in another repository: https://github.com/woocommerce/woocommerce-admin.
This issue has already been raised there and a fix should be available in WooCommerce 5.2.
https://github.com/woocommerce/woocommerce-admin/issues/6549
