### ISSUE TITLE
XDebug error with Woocommerce 5

### ISSUE THREAD

**Issue by mikdid** [woocommerce/woocommerce#29465]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

I have a problem with Woocommerce 5.
On local mode, when i start Xdebug and load a page, debugger stop direct in a Exception error in function reflect_class_or_callable( string $class_name, $concrete) in file AbstractServiceProvider.php – debugger stop in line 100

error message 
```
Exception has occurred.
ReflectionException: Method Automattic\WooCommerce\Proxies\LegacyProxy::init() does not exist
```

This is a fresh install, only wordrpress 5.7 + WooCommerce 5 + storefront  installed (any other plugin installed) 
With WooCommerce 4.x, no error

**Expected behavior**

**Actual behavior**
On local mode, when i start Xdebug and load a page, debugger stop direct in a Exception error in function reflect_class_or_callable( string $class_name, $concrete) in file AbstractServiceProvider.php – debugger stop in line 100

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

only install wp 5.7 + woocommerce 5 + storefront 
this is fresh install, any other plugin
Debbuger:  XDebug
ide : VsCode
Xampp

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://127.0.0.1:8001
Site address (URL): http://127.0.0.1:8001
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.2
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 1 Go
WP Debug Mode: –
WP Cron: ✔
Language: fr_FR
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.43 (Win64) OpenSSL/1.1.1g PHP/7.4.8
PHP Version: 7.4.8
PHP Post Max Size: 64 Mo
PHP Time Limit: 500
PHP Max Input Vars: 1000
cURL Version: 7.70.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.13-MariaDB
Max Upload Size: 64 Mo
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Votre serveur n’a pas la classe SoapClient activée - certaines extensions de passerelle utilisant SOAP peuvent ne pas fonctionner correctement.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.1.0
WC Database Prefix: wp_
Taille totale de la base de données: 3.78MB
Taille de la base de données: 2.32MB
Taille de l’index: 1.46MB
wp_woocommerce_sessions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_api_keys: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_attribute_taxonomies: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_downloadable_product_permissions: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_order_items: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_order_itemmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_tax_rates: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_woocommerce_tax_rate_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zones: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_shipping_zone_locations: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_shipping_zone_methods: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_woocommerce_payment_tokens: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_woocommerce_payment_tokenmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_woocommerce_log: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_actions: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
wp_actionscheduler_claims: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_groups: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_actionscheduler_logs: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_commentmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_comments: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_links: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_options: Données : 1.48MB + Index : 0.03MB + Moteur InnoDB
wp_postmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_posts: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_termmeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_terms: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_term_relationships: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_term_taxonomy: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_usermeta: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_users: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wc_admin_notes: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_admin_note_actions: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_category_lookup: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_customer_lookup: Données : 0.02MB + Index : 0.05MB + Moteur InnoDB
wp_wc_download_log: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_coupon_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_order_product_lookup: Données : 0.02MB + Index : 0.11MB + Moteur InnoDB
wp_wc_order_stats: Données : 0.02MB + Index : 0.06MB + Moteur InnoDB
wp_wc_order_tax_lookup: Données : 0.02MB + Index : 0.03MB + Moteur InnoDB
wp_wc_product_meta_lookup: Données : 0.02MB + Index : 0.09MB + Moteur InnoDB
wp_wc_reserved_stock: Données : 0.02MB + Index : 0.00MB + Moteur InnoDB
wp_wc_tax_rate_classes: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB
wp_wc_webhooks: Données : 0.02MB + Index : 0.02MB + Moteur InnoDB

### Post Type Counts ###

attachment: 1
page: 6
post: 2

### Security ###

Secure connection (HTTPS): ❌
					Votre boutique n’utilise pas HTTPS. En savoir plus sur HTTPS et les certificats SSL.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: par Automattic – 5.1.0

### Inactive Plugins (2) ###

Akismet Anti-Spam: par Automattic – 4.1.9
Hello Dolly: par Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la boutique: #6 - /boutique/
Panier: #7 - /panier/
Commander: #8 - /commander/
Mon compte: #9 - /mon-compte/
Conditions générales de vente et d’utilisation: ❌ Page non définie

### Theme ###

Name: Storefront
Version: 3.5.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – Si vous modifiez WooCommerce sur un thème parent que vous n’avez pas construit personnellement
nous vous recommandons d’utiliser un thème enfant. Voir : Comment créer un thème enfant

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Terminé: 1
Oldest: 2021-03-23 14:54:21 +0100
Newest: 2021-03-23 14:54:21 +0100


### Status report information ###

Generated at: 2021-03-23 14:59:30 +01:00
`
![bug-wp57-woo](https://user-images.githubusercontent.com/46753210/112158586-9b5a6c00-8be8-11eb-91b9-8099ac78cf98.png)

```
</details>

**Comment by roykho** [comment]
Hi @mikdid - so you mention this only happens locally? Have you tried running `composer dump-autoload` command within the woocommerce folder of your local site?

**Comment by mikdid** [comment]
I have install plugin with add->extension in Wordpress Admin Panel

**Comment by roykho** [comment]
Ok thanks for the additional information, I was able to reproduce this after setting debug to `everything`. We will look into this as soon as possible.

**Comment by mikdid** [comment]
Ok Thanks very much for your time 👍

**Comment by cereneto** [comment]
Same problem here.

**Comment by Mderob** [comment]
same problem also for me.
thanks for you support

**Comment by dudarevnikita** [comment]
Have the same problem.

WC version: 5.2.2
WP version: 5.7.1
PHP: 7.3

**Comment by sakralbar** [comment]
Have the same problem.

WC version: 5.4.1
WP version: 5.7.2
PHP: 7.4.3

**Comment by tinsilver** [comment]
I also have this problem - fresh install, only woocommerce + storefront
Plugin managed by Composer
WC: 5.4.1
WP: 5.7.2
PHP: 7.4.21

**Comment by NomanTee** [comment]
Hi 
Same issue. When is this likely to be resolved?

**Comment by peterfabian** [comment]
Hi, I think this is expected and is the way we implemented reflection with our dependency injection. The exception is caught later on by `catch ( \ReflectionException $ex )`... 

What do you think, @Konamiman / @ObliviousHarmony ? This seems pretty standard to me, so I'd be inclined to close this issue, but I agree it doesn't make debugging very easy and is rather annoying when using xdebug.

**Comment by peterfabian** [comment]
reping @Konamiman / @ObliviousHarmony maybe you folks have any ideas?

Side note: I googled a bit last week and the conclusion was that xdebug doesn't support breaking on unhandled exceptions only, so it's rather inconvenient. Some other languages support this.

So at the moment, I think the best way is to disable brakpoints on exceptions and monitor PHP log.

**Comment by ObliviousHarmony** [comment]
There's a potential solution [linked to this issue](https://github.com/titantwentyone/woocommerce/pull/1/files) that may be worth looking at implementing. Ideologically, exceptions should probably only be used in exceptional cases, while the case presented here is a common occurrence for many classes that would be instantiated by the container. It should be fine to check `method_exists()` before using the reflection method, and I don't imagine it changes the performance of the container in any meaningful way.

**Comment by peterfabian** [comment]
That sounds like a good idea 👍 . I also think that the cost of creating the object might be larger than calling a function, so we might be getting a tiny performance gain, too, right? WDYT @Konamiman ?

**Comment by Konamiman** [comment]
Yep, I agree: checking if the method exists beforehand is cleaner than trying to use it and catching the exception, and we could also get a small performance gain as a bonus (for what @peterfabian mentions but also for avoiding the exception in the first place).

**Comment by AleWin32** [comment]
Same problem here:
ReflectionException: Method Automattic\WooCommerce\Proxies\LegacyProxy::init() does not exist

on line 100 of wp-content/plugins/woocommerce/src/Internal/DependencyManagement/AbstractServiceProvider.php

I have:
- MAMP 6.6 (1211)
- PHP 7.4.21
- WP 5.8.2
- WC 5.9.0
- Xdebug 2.9.8
- Visual Studio Code 1.62.3 with plugin PHP Debug 1.22.0 installed
- I don't have Storefront plugin installed so it's not necessary to reproduce the bug

It makes my xdebug completely unusable, i cannot debug anything with WordPress + WooCommerce.

**Comment by AleWin32** [comment]
I have tried the solution of:
https://github.com/titantwentyone/woocommerce/pull/1

manually patching my file (as the patch suggests):
wp-content/plugins/woocommerce/src/Internal/DependencyManagement/AbstractServiceProvider.php

changing:
$method = new \ReflectionMethod( $class, Definition::INJECTION_METHOD );

to:
$method = method_exists($class, Definition::INJECTION_METHOD) ? new \ReflectionMethod( $class, Definition::INJECTION_METHOD ) : null;

but xdebug still does not work (it successfully stop at my first breakpoint, i click on Continue button (play icon, the triangle), but then the next line that is also breakpointed never get reached, very strange, i don't know why)

EDIT: If i enable xdebug on VSCode and now i access an admin page, my code does not execute 100%, only my first breakpointed code line is reached and then when i press "Continue" button on the debugger the code execution flow stops, but now if i disable xdebug in VSCode (stoping it) and i access the same admin page again, my code is executed 100% until the end. Looks like the problem is with xdebug or with PHP Debug plugin support for xdebug version 2.

EDIT 2: I successfully solved the problem with xdebug (now it reaches all the lines with breakpoints on my code without stoping abruptly) changing my PHP version on MAMP from PHP 7.4.21 (that includes xdebug 2.9.8) to PHP 8.0.8 (that includes xdebug 3.0.3)

**Comment by peterfabian** [comment]
Thanks for reporting back, @AleWin32 ! Useful info!

**Comment by jasonpierson** [comment]
We're also having this error.

Wordpress 5.9
Woocommerce 6.1.1

But it's happening on the server. Pantheon is our host. It started when we upgraded PHP from 7.3 to 8.0.

I was also able to fix it with the [titantwentyone#1](https://github.com/titantwentyone/woocommerce/pull/1) solution.

**Comment by peterfabian** [comment]
@titantwentyone would you like to create a PR against the WC repository so that we can merge it and you get the fame and recognition that comes with contributing to WC core? :)

**Comment by traed** [comment]
@peterfabian Any update on when this may be merged?

**Comment by Konamiman** [comment]
While I haven't been able to reproduce the issue myself (probably because of my XDebug configuration) I have created a fix, it'll go into WooCommerce as soon as it's reviewed: https://github.com/woocommerce/woocommerce/pull/33960
