### ISSUE TITLE
The woocommerce quick-setup wizard does not appear

### ISSUE THREAD

**Issue by umbrossino95** [woocommerce/woocommerce#29478]
I clicked on the woocommerce settings plugin, clicked '' help '' and '' setup wizard '' but a blank page appeared.

**Comment by rodel-calasagsag** [comment]
Hi @umbrossino95. If you could please elaborate more on the steps you took for us to be able to recreate this issue?

I tried to follow your steps but I didn't encounter the issue you mentioned, as you can see from the file I attached here:
https://user-images.githubusercontent.com/4509348/113477162-a5b31a80-94b2-11eb-92e0-17943fba9498.mp4

The steps I did were:

1. Go to 'WooCommerce > Settings' page.
2. Click on the 'Help' sliding menu at the top right portion of the page.
3. Click on the 'Setup wizard' link at the left portion of the sliding pane.
4. Click on the 'Setup wizard' button at the right pane.

I was correctly taken to the Setup Wizard after completing these steps.

Please use our bug reports template when elaborating the steps. You would see this template when you start a new issue like so:
<img width="477" alt="oPz0PWmnzI" src="https://user-images.githubusercontent.com/4509348/113477523-de53f380-94b4-11eb-9c1c-dfd1b590dea6.png">

Our template has an **Isolating the problem** section that could help guide you in specifying the recreation steps.
Also, please don't forget to attach your System Status Report.

Let us know if you need more info. Thanks!
