### ISSUE TITLE
New order needs_shipping method

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#29475]
Products have a method called `needs_shipping` that returns false when the product is virtual.
The cart has the same method that returns false when all products on it also return false to the `needs_shipping` method.

I think we need that same method on orders.
We currently have the `needs_shipping_address` method that looks into the order for shipping methods and doesn't use the same logic used in the cart: look into the products being virtual.

We could loop the order line items and check if each product `needs_shipping` or not but this is not very trustable because products might have been changed or even deleted after the order was placed.

Does it make sense that needing a shipping address or needing shipping might be different things?
Even the way the `needs_shipping_address` method works seem odd to me. For example, a locker drop-off service will be a shipping method and that order needs shipping but ultimately it might not need a customer shipping address.

**Comment by roykho** [comment]
Hi @webdados - I think in either case you would still need to loop through the items in the order to know if the order needs shipping right? Because as you said, things could have changed after the order. So needs shipping condition needs most up to date information by looping through the items.

> Does it make sense that needing a shipping address or needing shipping might be different things?

Yes I would agree they can be different things.

Do you have a specific example (use case) as to how you would use this?

**Comment by webdados** [comment]
> I think in either case you would still need to loop through the items in the order to know if the order needs shipping right? Because as you said, things could have changed after the order. So needs shipping condition needs most up to date information by looping through the items.

Maybe we need to go as far as storing that `needs_shipping` information on the order item meta.
I don't think going to the original product to check that is a good idea because of what I mentioned before: 
> products might have been changed or even deleted after the order was placed

> Do you have a specific example (use case) as to how you would use this?
As stated before:
> For example, a locker drop-off service will be a shipping method and that order needs shipping but ultimately it might not need a customer shipping address.
For example, I can use the proposed `needs_shipping` order method to check if I need to show a metabox to issue shipping labels for the carrier that delivers on the locker drop-off, but still, I haven't got a shipping address so `needs_shipping_address` returns false.

I can't think of a use case where the `needs_shipping` would be false and `needs_shipping_address` would be true, tho.
