### ISSUE TITLE
[Globalstep-WooCommerce 5.2 Beta] Steps fails to update on "WooCommerce setup" widget on dashboard as per the finished onboarding tasks.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#29483]
## Bug Description:
Steps fails to update on "WooCommerce setup" widget on dashboard as per the finished onboarding tasks.

## Test Instructions:
https://github.com/woocommerce/woocommerce/wiki/Release-Testing-Instructions-WooCommerce-5.2#add28568-dashboard-widget---setup-29174

## Environment:
Woocommerce Version : WooCommerce 5.2 beta
WordPress version: (v5.7)

PC:
Windows 10, Mac 10.14.6
Chrome(Version 88.0.4324.104) 
Firefox(Version 86.0)
Safari: v13.1.

## Steps To Reproduce:
1. Create any test site using JN site.
1. Go to Plugins->Add new.
1. Upload a WooCommerce 5.2 beta plugin.
1. Go to Dashboard->Home screen.
1. Note that "WooCommerce setup" widget appears.
1. Now go to OBW and finish some steps.
1. Go to Dashboard->Home and check the "WooCommerce setup" widget.
1. Observe that steps fails to update on "WooCommerce setup" widget as per the finished onboarding tasks.

## Actual Result:
Steps fails to update on "WooCommerce setup" widget on dashboard as per the finished onboarding tasks.

## Expected Result:
Steps should get update on "WooCommerce setup" widget on dashboard as per the finished onboarding tasks.

## Video:

https://user-images.githubusercontent.com/41110392/112513268-28a0ea80-8dba-11eb-812e-76335cbd1b03.mp4

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://positive-milkweed.jurassic.ninja
Site address (URL): https://positive-milkweed.jurassic.ninja
WC Version: 5.2.0
REST API Version: ✔ 5.2.0
WC Blocks Version: ✔ 4.7.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.1.3
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.16
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.2.0
WC Database Prefix: wp_
Total Database Size: 5.56MB
Database Data Size: 4.08MB
Database Index Size: 1.48MB
wp_woocommerce_sessions: Data: 0.03MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ce4wp_abandoned_checkout: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.02MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
customize_changeset: 1
nav_menu_item: 5
page: 6
post: 2
product: 19
product_variation: 7
shop_order: 2
shop_order_refund: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (9) ###

Companion Plugin: by Osk – 1.18
Creative Mail by Constant Contact: by Constant Contact – 1.3.5
Facebook for WooCommerce: by Facebook – 2.3.3
Jetpack by WordPress.com: by Automattic – 9.5
Google Ads & Marketing by Kliken: by Kliken – 1.0.7
Mailchimp for WooCommerce: by Mailchimp – 2.5.1
WooCommerce Beta Tester: by WooCommerce – 2.0.2
WooCommerce Shipping & Tax: by Automattic – 1.25.10
WooCommerce: by Automattic – 5.2.0-beta

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 10
Oldest: 2021-03-24 14:32:52 +0000
Newest: 2021-03-25 15:58:03 +0000


### Status report information ###

Generated at: 2021-03-25 16:52:09 +00:00
`
```
</details>

**Comment by zhongruige** [comment]
Hi @gglobalstep,

Thank you for reporting this issue! I was able to reproduce it with the steps provided.

The "WooCommerce Setup Widget" appears to be highly dependent on the order (and the steps) that are completed to update the count correctly. Please find two exampl flows below:

**Following the steps provided by @gglobalstep** 

* Setup a new WooCommerce install with the 5.2 beta
* Proceed through the onboarding wizard
* Start following through the checklist steps in order: Store details -> Add products -> Choose payment methods -> Add tax rates -> Set up shipping costs
* Note that once you hit "Choose payment methods" the count is off:

<img width="972" alt="Screen Shot 2021-03-26 at 11 13 06 AM" src="https://user-images.githubusercontent.com/71906536/112669359-40fa1f00-8e25-11eb-9eaf-b982c275c154.png">

* This continues as you go through the rest of the steps:

<img width="1027" alt="Screen Shot 2021-03-26 at 11 13 27 AM" src="https://user-images.githubusercontent.com/71906536/112669462-5bcc9380-8e25-11eb-9767-a95e2430c15c.png">

<img width="1170" alt="Screen Shot 2021-03-26 at 11 20 47 AM" src="https://user-images.githubusercontent.com/71906536/112669470-5ec78400-8e25-11eb-8b3c-db3d0465cc70.png">

**Following a different checklist order**

This is the order I usually follow when setting up a WooCommerce site for testing:

* Setup a new WooCommerce install with the 5.2 beta
* Proceed through the onboarding wizard
* Complete the following steps: Store details, Add products, Personalize your store
* Note the count is correct at this point:

<img width="451" alt="Screen Shot 2021-03-26 at 10 47 47 AM" src="https://user-images.githubusercontent.com/71906536/112669616-8ae30500-8e25-11eb-9e35-e28010641455.png">

* Continue, this time set up shipping costs:

<img width="710" alt="Screen Shot 2021-03-26 at 10 48 24 AM" src="https://user-images.githubusercontent.com/71906536/112669655-97675d80-8e25-11eb-9a1d-37d3b827ab42.png">

* Note the count:

<img width="454" alt="Screen Shot 2021-03-26 at 10 48 32 AM" src="https://user-images.githubusercontent.com/71906536/112669672-9cc4a800-8e25-11eb-9603-9fc75cfd0660.png">

* Continuing on, complete the "Add tax rate" step. Note now the widget shows blank:

<img width="453" alt="Screen Shot 2021-03-26 at 10 49 02 AM" src="https://user-images.githubusercontent.com/71906536/112669777-b36aff00-8e25-11eb-8b40-9911501b8497.png">

* Once everything is completed the widget disappears, as expected.
