### ISSUE TITLE
Set default base country as detected location until manually changed

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce#29499]
## Problem to solve
As part of our focus on WC Pay, we noticed an issue with the default base country in WooCommerce. Currently the default base country is set to the UK if the user skips onboarding, and/or doesn't update their location in General Settings. This is problematic since US-based users will have no way of discovering WC Pay when their base country is set to an unsupported country. We're concerned that this has had a negative impact on WC Pay adoption to date and are proposing the following solution.

<img width="1389" alt="Screen Shot 2021-03-25 at 11 06 02 AM" src="https://user-images.githubusercontent.com/5121465/112505033-62420900-8d5a-11eb-8546-43a9d38d52b4.png">

## Solution
Set the base country as the location where the user's computer is detected, unless or until this is manually changed by the user either in Settings or during onboarding. This should at least be accurate at the country level.

The location-based default will ensure that all users who are in a supported country will have the opportunity to discover WC Pay. We're currently working on various entrypoints to discover the extension in core and this will ensure that everyone who could see the WC Pay prompts is seeing it. Also, it prevents the frustration of thinking you can use WC Pay only to find out that you're in an unsupported country (since we're soon going to provide WC Pay in the UK.)

Pinging WooCommerce Core leads here for feedback - @peterfabian @ObliviousHarmony @vedanshujain.

cc @pmcpinto @laurendavissmith @LevinMedia

**Comment by ObliviousHarmony** [comment]
Howdy @elizaan36,

Unfortunately there's probably not a good way for us to accurately detect a merchant's location before they interact with one of our services. The geolocation we offer in WooCommerce requires merchant configuration to utilize. There are some free services that it falls back to but I don't know if we can geolocate the merchant without their consent?

I wonder if we could alternatively use the merchant's WordPress language selection to guess a most-likely base country? There are a bunch of country-specific options for English, and if folks actually use those, that would at least be better than defaulting to the UK.

Let's see what @vedanshujain has to say too 😀

**Comment by elizaan36** [comment]
> I don't know if we can geolocate the merchant without their consent?

**Comment by vedanshujain** [comment]
It's fine to change the default country to the US from the UK for a new installation, whose actual location we do not know and cannot figure out. At the moment the UK is [just a placeholder](https://github.com/woocommerce/woocommerce/blob/23710744c01ded649d6a94a4eaea8745e543159f/includes/admin/settings/class-wc-settings-general.php#L84) since several functionalities need a non-null country field to initialize properly. Users will change this anyway based on their actual store location.

I am marking this as high prio so that we take it up soon.

**Comment by beaulebens** [comment]
We could also use [browser-based location detection](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API) (although it will trigger a prompt, asking the user if the consent).

**Comment by elizaan36** [comment]
@vedanshujain Thanks, changing the default to the US sounds good for better discovery in the interim until WCPay is expanded to the UK. 

That means we should make sure the location check is implemented - @LevinMedia, do you know if there's an issue for that up yet?

@beaulebens Do you think it's possible to use geolocation without an additional prompt if users have opted into data tracking? This data tracking opt-in modal appears when you choose to skip onboarding, so the thinking is that once you agree, we'd be able to use geolocation to set the default base country correctly.

**Comment by beaulebens** [comment]
> @beaulebens Do you think it's possible to use geolocation without an additional prompt if users have opted into data tracking? This data tracking opt-in modal appears when you choose to skip onboarding, so the thinking is that once you agree, we'd be able to use geolocation to set the default base country correctly.

Unfortunately no (not the way I was suggesting at least), since using browser-based location requires interaction with the browser-level APIs, which require their own consent before we can actually access the data. It's this thing, which you've probably seen;

<img width="339" alt="Screen Shot 2021-03-29 at 6 03 09 PM" src="https://user-images.githubusercontent.com/108942/112914360-08727380-90b9-11eb-84ff-4feaee1cc00b.png">

**Comment by elizaan36** [comment]
Once users have opted into data usage tracking, that's consent to use their [WordPress locale](https://woocommerce.com/usage-tracking/). If it's possible to use something like that as a location, it would be a matter of setting the default base country after they agree to usage tracking in this modal in onboarding.

![Screen Recording 2021-03-30 at 10 20 30 AM](https://user-images.githubusercontent.com/5121465/113013896-bcb7dc80-9141-11eb-9dd1-f4c7961032a1.gif)

**Comment by beaulebens** [comment]
Fun example of this confusion -- I just saw a request in our Slack community:

> We would like people from overseas to be able to add their address from different countries in checkout page. Now it is only for UK.

**Comment by vedanshujain** [comment]
Noting here that we discussed in the team and we will implement based on inferring the country based on the locale set in WordPress (instead of from browser or anything more complicated like this). If no locale is set, we will default to the US.

**Comment by jonathansadowski** [comment]
I just wanted to drop a note here that we approached this by setting the default store location to US:CA, as the original approach we were going to take (inferring based on WordPress location) was more complicated than first thought. There's more context here: p1618236185450400-slack-C0E1AV8T0
