### ISSUE TITLE
WooCommerce pages do not get created on ECOMMERCE plan

### ISSUE THREAD

**Issue by moon0326** [woocommerce/woocommerce#29491]
**Prerequisites (mark completed items with an [x]):**
- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

The expected WooCommerce pages (shop, cart, checkout , and my account) do not get created on a new installation if you choose ECOMMERCE plan on wordpress.com. 

Related issue: https://github.com/Automattic/wc-calypso-bridge/issues/637

I've tried to fix it by updating wc-calypso-bridge repository (PR [here](https://github.com/Automattic/wc-calypso-bridge/pull/662)), but it did not work. The action (woocommerce_admin_newly_installed) does not get fired for some reason.

I've also noticed that the following options are created with an incorrect post ID when the actual pages are not created (screenshot attached).

woocommerce_checkout_page_id
woocommerce_shop_page_id
woocommerce_cart_page_id
woocommerce_myaccount_page_id

I think [create_pages()](https://github.com/woocommerce/woocommerce/blob/trunk/includes/class-wc-install.php#L555) executed just fine since the `woocommerce_*_page_id` options are created.

I figured it's best to investigate and fix it in WooCommerce repository.

**Expected behavior**
WooCommerce pages should be created.

**Actual behavior**
No pages created.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

1. Go to wordpress.com
2. Add a new site (https://wordpress.com/new?ref=calypso-selector)
3. Choose "ECOMMERCE" plan on the "Select a plan" page.
4. Finish the wizard.
5. Navigate to Pages.
6. Notice that the expected page are not created.

**Screenshots**

![Screen Shot 2021-03-25 at 1 42 26 AM](https://user-images.githubusercontent.com/4723145/112449678-e40d4480-8d10-11eb-8524-110e4b480644.jpg)

Update 1: One more thing I noticed is that those post IDs linked to the `woocommerce_*_page_id` options are social link posts. It looks like we only create those social link posts on ecommerce plan.

**Comment by moon0326** [comment]
Closing this for now as it needs more investigation. The code itself works just fine. I will reopen it.

**Comment by pmcpinto** [comment]
@moon0326 do you know when this fix is going to be released?
