### ISSUE TITLE
Unchecked "Restock refunded items" restocks on "Update"

### ISSUE THREAD

**Issue by joelgraham** [woocommerce/woocommerce#29502]
Hello,

This is my first issue, so I hope I've followed all the rules!

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Partially refunded an order with the "Restock refunded items:" checkbox _unchecked_ (defaulted to unchecked). When "Update" is pressed on the order, or the order is bulk edited to "Complete" the items are restocked.
--

**Expected behavior**
The items shouldn't be restocked.

**Actual behavior**
The items are restocked.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Place an order (frontend or admin) with a item quantity of more than 1
2. Edit the order in the admin
3. Click "Refund" and partially refund an item
4. Uncheck "Restock refunded items"
4. Click "Refund X Manually" and click "OK"
5. _Stock is not restocked_
6. Click "Update"
7. _Stock is restocked_

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
### WordPress Environment ###

WordPress address (URL): http://www.worfieldplants.local/wp
Site address (URL): http://www.worfieldplants.local
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.2
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2u mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_wsgi/3.5 Python/2.7.13 mod_perl/2.0.11 Perl/v5.30.1
PHP Version: 7.3.24
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 5.7.32
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ❌ wp_remote_get() failed. Contact your hosting provider.

### Database ###

WC Database Version: 5.1.0
WC Database Prefix: wp_
Total Database Size: 56.54MB
Database Data Size: 39.35MB
Database Index Size: 17.19MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 1.22MB + Index: 0.77MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 1.33MB + Index: 0.52MB + Engine InnoDB
wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.16MB + Index: 0.17MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_dlm_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dlm_order_customer: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_dlm_order_item: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_dlm_order_transaction: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_dlm_session: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_download_log: Data: 7.52MB + Index: 1.52MB + Engine InnoDB
wp_et_bloom_stats: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
wp_frm_fields: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_frm_forms: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_frm_items: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
wp_frm_item_metas: Data: 0.14MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 5.48MB + Index: 0.45MB + Engine InnoDB
wp_postmeta: Data: 12.52MB + Index: 10.03MB + Engine InnoDB
wp_posts: Data: 2.52MB + Index: 0.53MB + Engine InnoDB
wp_redirection_404: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.23MB + Index: 0.06MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.23MB + Index: 0.22MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 1.52MB + Index: 0.77MB + Engine InnoDB
wp_wc_order_stats: Data: 0.27MB + Index: 0.28MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.17MB + Index: 0.17MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.11MB + Index: 0.20MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpf_filters: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.20MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 2
acf-field-group: 3
attachment: 943
custom_css: 1
dlm_download: 29
dlm_download_version: 43
et_header_layout: 4
et_pb_layout: 25
et_template: 3
et_theme_builder: 1
frm_form_actions: 2
frm_styles: 2
nav_menu_item: 14
page: 17
post: 8
product: 414
revision: 432
shop_coupon: 2
shop_order: 2
shop_order_refund: 89
wc_product_table: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (22) ###

Advanced Custom Fields PRO: by Elliot Condon – 5.9.5
Autocomplete Google Address: by Md Nishath Khandakar – 1.8
Business WorldPay Gateway for Woocommerce: by MDSDev – 1.4.0
Classic Editor: by WordPress Contributors – 1.6
GDPR Cookie Consent: by WebToffee – 2.0.0
Facebook for WooCommerce: by Facebook – 2.3.2
Formidable Forms Pro: by Strategy11 – 4.09.07
Formidable Forms: by Strategy11 – 4.09.07
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.16.2
Hide WooCommerce Categories On Shop Page: by Matix Web Designers – 1.1.0
CF Page or Post Duplicator: by Carlos Fazenda – 1.1
Redirection: by John Godley – 5.0.1
W3 Total Cache: by BoldGrid – 2.1.1
Product Feed PRO for WooCommerce: by AdTribes.io – 9.7.7
WooCommerce Dynamic Pricing: by Lucas Stark – 3.1.22
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.1
WP WooCommerce Mailchimp: by Saint Systems – 2.3.13
Advanced Order Export For WooCommerce (Pro): by AlgolPlus – 3.1.6
WooCommerce PDF Invoices: by Bas Elbers – 3.1.4
WooCommerce: by Automattic – 5.1.0
Yoast SEO: by Team Yoast – 15.9.1
WP Search with Algolia: by WebDevStudios – 1.7.0

### Inactive Plugins (4) ###

Office 365 for Post SMTP Extension: by Yehuda Hassine – 1.2
Post SMTP: by Yehuda Hassine – 2.0.22
Preorders for WooCommerce PRO: by Bright Plugins – 1.4.1
SMNTCS Quantity Increment Buttons for WooCommerce: by Niels Lange <info@nielslange.de> – 1.23

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Must Use Plugins (3) ###

Bedrock Autoloader: by Roots – 1.0.3
Disallow Indexing: by Roots – 1.0.0
Register Theme Directory: by Roots – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: ❌ Page not set
Cart: #4260 - /shopping-cart/
Checkout: #4500 - /checkout/
My account: ❌ Page not set
Terms and conditions: ❌ Page not set

### Theme ###

Name: Worfield Plants 2020
Version: (update to version 0 is available)
Author URL: 
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: worfield-plants/woocommerce/archive-product.php
worfield-plants/woocommerce/cart/cart.php
worfield-plants/woocommerce/cart/mini-cart.php
worfield-plants/global/quantity-input.php version 3.3.0 is out of date. The core version is 4.0.0
worfield-plants/woocommerce/loop/orderby.php
worfield-plants/woocommerce/loop/pagination.php
worfield-plants/woocommerce/single-product/add-to-cart/variable.php
worfield-plants/woocommerce/single-product/product-image.php
worfield-plants/woocommerce/single-product/tabs/tabs.php
worfield-plants/woocommerce/single-product.php

Outdated Templates: ❌

### Action Scheduler ###

Complete: 2,632
Oldest: 2021-02-22 20:33:19 +0000
Newest: 2021-03-25 19:25:09 +0000

Pending: 1
Oldest: 2021-03-26 18:50:51 +0000
Newest: 2021-03-26 18:50:51 +0000

### Status report information ###

Generated at: 2021-03-25 19:53:50 +00:00
</details>

**Comment by tammullen** [comment]
Hi @joelgraham 

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

![Screenshot_2021-03-26_at_15_46_53](https://user-images.githubusercontent.com/24649833/112658590-74e83b00-8e4b-11eb-99dc-c332241c78b9.png)
![Screenshot_2021-03-26_at_15_47_26](https://user-images.githubusercontent.com/24649833/112658606-787bc200-8e4b-11eb-8564-b61ff786b727.png)
![Screenshot_2021-03-26_at_15_47_53](https://user-images.githubusercontent.com/24649833/112658616-7b76b280-8e4b-11eb-9b19-c535b3b59bcc.png)
![Screenshot_2021-03-26_at_15_48_19](https://user-images.githubusercontent.com/24649833/112658631-7dd90c80-8e4b-11eb-9644-2139a1e5ff92.png)
![Screenshot_2021-03-26_at_15_48_55](https://user-images.githubusercontent.com/24649833/112658642-803b6680-8e4b-11eb-80fc-0aa7a219a3b2.png)


We’re going to solve this bug as soon as possible. Stay tuned for updates.

Noting this was also observed in https://github.com/woocommerce/woocommerce/issues/27504#issuecomment-712484345

**Comment by joelgraham** [comment]
Hi @tammullen,

It would be great to get a fix — causing lots of headaches for my client currently. Let me know if I can do anything to help assist.

**Comment by joel-graham** [comment]
Hi @tammullen,

Could you please give a time indication when this might be ready? I see there's a PR [#29762] — how long does this usually take before it's released?

Thanks.

**Comment by joelgraham** [comment]
Hi @tammullen,

Could you please give a time indication when this might be ready? I see there's a PR [#29762] — how long does this usually take before it's released?

Thanks.

**Comment by tammullen** [comment]
Hi @joelgraham 

Once the PR has been reviewed it will be assigned to a release (usually the soonest available next release depending on the code freeze dates for a release). At our monthly release cadence, the core team aims to release a new version of WooCommerce every second Tuesday of each month, you can learn more about this at these links.

https://developer.woocommerce.com/2021/04/27/improving-releases-with-automation/
https://developer.woocommerce.com/2020/07/22/woocommerce-core-release-calendar/
