### ISSUE TITLE
Issue with low stock inventory notification for shared inventory products in woocommerce

### ISSUE THREAD

**Issue by Heatherarts** [woocommerce/woocommerce#29514]
I'm not sure if this is a good place to post this or not and I really don't know who to ask for help with our issue.

I was told by someone at woocommerce support that there was a new update coming out with the release of version 5.2 saying it was fixing a low stock notification but I am wondering if this update will help with fixing the issue of not being able to set a low stock notification for shared variation inventory items?

I currently use https://woocommerce.com/products/variation-shared-inventory-for-woocommerce/

We use this plugin to help link our products we sell in different quantities as separate variations (example product: Alcohol prep pads has 4 variations: Each, 6 pack, Box of 200, and Case of 3000) but want the stock for each variation to be easily linked so it can be counted all together and when orders are placed we need it to deduct the correct number from inventory based on the variation(quantity) of the product being purchased. 

The problem I am seeing is that the low stock notification number we set is in the inventory tab not the variation tab and I believe is only working if we are managing stock at the product level instead of the variation level. 

I am still new to woo commerce and would appreciate any help.
Thank you in advance!

_Originally posted by @Heatherarts in https://github.com/woocommerce/woocommerce/issues/29345#issuecomment-808449066_

**Comment by juliaamosova** [comment]
Hi @Heatherarts,

Thank you for opening this issue! By your description, it sounds like the issue should indeed be resolved for you in WooCommerce 5.2 release (scheduled for April 13th).

If you like, you can test the pre-release version of WooCommerce 5.2. To do that, you can use the [WooCommerce Beta Tester](https://wordpress.org/plugins/woocommerce-beta-tester/) plugin. Once activated, you can select to install WooCommerce 5.2 RC1 on your site from the list of options available and test further. 

If you end up testing, would you please report back here with your findings? Thanks in advance!
