### ISSUE TITLE
Feature Request:: Shipping Date

### ISSUE THREAD

**Issue by williamgh2019** [woocommerce/woocommerce#29511]
Hello,

It is better if WC has shipping date rate.

1. If customer want their product on Saturday and Sunday we will provide free shipping cost.
2. If customer want their product with two day after order has placed they will charge 5$
3. If customer want next day after their product order they will charge for shipping cost 10$.

Thanks

**Comment by glagonikas** [comment]
I'm not sure core changes are actually required for this. Sounds like you can do these using shipping methods

1. Enable Free shipping and call it "Saturday and Sunday".
2. Create one called "Two day delivery" (or whatever) and set prices to $5
3. Create one called "Next day delivery" (or express) and set prices to $10
(No need for code changes on the above)

You can then write some custom code or purchase [Order Status Manager](https://woocommerce.com/products/woocommerce-order-status-manager/) to create the following statuses
1. Free Shipping
2. Standard Shipping
3. Express Shipping
Those will be identical to processing.

Finally, using some custom code, you can change the status of any orders that land into Processing and move them to one of those new statuses, based on the shipping class the customer has selected.

**Comment by juliaamosova** [comment]
Hi @williamgh2019,

Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the `votes needed` label and evaluate over time if this issue collects more feedback. 

Don’t be alarmed if you don’t see any activity on this issue for a while.

In the meantime, there are several workarounds available such as the one proposed by @glagonikas. 

We also have a plugin available called [Order Delivery](https://woocommerce.com/products/woocommerce-order-delivery/) that can help with the setup you are looking for.
