### ISSUE TITLE
TwentyTwenty Notice styles are inconsistent

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#29529]
**Is your feature request related to a problem? Please describe.**
I find the notice styles for the TwentyTwenty theme to be inconsistent. The success notice has no color distinction. The error notice has a red background. And the info notice has a red border. 

![image](https://user-images.githubusercontent.com/507025/112887426-68085900-9090-11eb-87d9-6e9f99c58d0e.png)

**Describe the solution you'd like**
At a minimum, I would like to see the success notice get a border color like the info notice, except with a success color (perhaps green like in WooCommerce defaults?). 

Additionally, I think the info should not have a red border since red is typically associated with error states (perhaps blue like in the WooCommerce defaults?)

**Comment by juliaamosova** [comment]
Hi @helgatheviking!

Thanks for this suggestion on how the visuals of the Twenty Twenty theme notices can be improved. Marking this one as an enhancement for now.

**Comment by helgatheviking** [comment]
Hi @juliaamosova I am happy to take a crack at this one... just need a little point in the right direction as far as color schemes. Does twenty twenty even _need_ custom notice styles? Why don't the default themes inherit the default Woo notice styling? This style is arguably much worse than the ones in Woo core.
