### ISSUE TITLE
Photoswipe close button iOS/Safari redirect bug

### ISSUE THREAD

**Issue by canguroenglish** [woocommerce/woocommerce#29521]
**Description of bug**
On the single product page when photoswipe fullscreen/zoom is engaged, pressing the X (close) button redirects to home instead of closing the fullscreen/zoom window.

**Steps to recreate**
1) Create theme template for Woocommerce single product page using Elementor
2) View site on iOS device/Safari
3) Click zoom icon on image to open fullscreen
4) Click X to close fullscreen- ERROR - on my site this redirects to homepage and not single product page - seems to activate logo click.
5) You can see this bug in action at https://canguroenglish.com/shop

**Comment by juliaamosova** [comment]
Hi @canguroenglish,

Thank you for reporting the issue. However, it is not isolated enough for us to confirm it is an issue with WooCommerce. Is there a way to encounter the issue without using Elementor?

**Comment by canguroenglish** [comment]
I have already spoken to Elementor support and they have confirmed that this is a WooCommerce problem. Even if it is a compatibility issue I suspect it's still something you want to look at given that Elementor is installed on millions of site with WooCommerce.

**Comment by rrennick** [comment]
> I have already spoken to Elementor support and they have confirmed that this is a WooCommerce problem.

@canguroenglish We still need to be able to reproduce this issue without Elementor. Can you confirm you still see the issue with either StoreFront of one of the default WP themes?

**Comment by canguroenglish** [comment]
I'm sorry but I am not a developer and I am using a live installation so I can't experiment with different themes and plugins.

**Comment by tammullen** [comment]
Hi @canguroenglish, 

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report WooCommerce bugs only. 

I'm closing this for now, if you are able to recreate this issue with only WooCommerce active and a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/) please raise a new issue using our bug reporting template. Without these details requested in the template we can’t fully evaluate this issue.
