### ISSUE TITLE
WooCommerce Customize not publishing changes

### ISSUE THREAD

**Issue by studiojpeg** [woocommerce/woocommerce#29523]
**Describe the bug**

Unable to save and publish changes to settings inside WP customizer for WooCommerce plugin specifically. For other settings, there's no problem (I'm using a live environment).

**Expected behavior**

Publish and save changes that are visible in the front-end.

**Actual behavior**

When I go to Appearance > Customize > WooCommerce > Product Catalog > Products per row > Change it to a different number > Publish > Close the customizer

Though I can click Publish and it seems to save the changes, **nothing is published and no changes are visible in the front-end.** When I return to the customizer, I see that all _changes were reverted_.

**Steps to reproduce the bug**

Steps to reproduce the bug are described above.
You can reproduce it with every single setting for woocommerce. 
With other settings outside WooCommerce it saves and publishes without any problem.

All plugins are deactivated except WooCommerce (latest version).
Using Storefront theme (latest version).
Using latest wordpress version.
Disabled and purged CloudFlare and no other caching plugins are active. 
Tested on browser incognito mode.

**Isolating the problem (mark completed items with an [x]):**
- [ x ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
`
### WordPress Environment ###

WordPress address (URL): https://www.sparqled.com/staging
Site address (URL): https://www.sparqled.com/staging
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.2
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.3.27
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.24-MariaDB-cll-lve
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.1.0
WC Database Prefix: wp4g_
Total Database Size: 67.35MB
Database Data Size: 59.36MB
Database Index Size: 7.99MB
wp4g_woocommerce_sessions: Data: 0.39MB + Index: 0.02MB + Engine InnoDB
wp4g_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp4g_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp4g_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp4g_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp4g_woocommerce_order_itemmeta: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp4g_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp4g_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp4g_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp4g_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp4g_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp4g_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp4g_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp4g_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp4g_actionscheduler_actions: Data: 2.39MB + Index: 0.97MB + Engine InnoDB
wp4g_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp4g_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp4g_actionscheduler_logs: Data: 1.45MB + Index: 0.64MB + Engine InnoDB
wp4g_adsw_activities: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp4g_adsw_ali_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp4g_adsw_comments_hash: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp4g_adsw_search_analytics: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp4g_adsw_task_upload_images: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp4g_aepc_custom_audiences: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp4g_aepc_logs: Data: 0.54MB + Index: 0.00MB + Engine MyISAM
wp4g_commentmeta: Data: 0.11MB + Index: 0.14MB + Engine InnoDB
wp4g_comments: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp4g_ewwwio_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp4g_ewwwio_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp4g_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp4g_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp4g_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp4g_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp4g_ms_snippets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp4g_options: Data: 8.06MB + Index: 0.45MB + Engine InnoDB
wp4g_postmeta: Data: 32.52MB + Index: 3.02MB + Engine InnoDB
wp4g_posts: Data: 3.50MB + Index: 0.22MB + Engine InnoDB
wp4g_po_plugins: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp4g_rank_math_404_logs: Data: 0.11MB + Index: 0.09MB + Engine InnoDB
wp4g_rank_math_analytics_adsense: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp4g_rank_math_analytics_ga: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp4g_rank_math_analytics_gsc: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp4g_rank_math_analytics_keyword_manager: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp4g_rank_math_analytics_objects: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp4g_rank_math_internal_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp4g_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp4g_rank_math_redirections: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp4g_rank_math_redirections_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp4g_smush_dir_images: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp4g_snippets: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp4g_termmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp4g_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp4g_term_relationships: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp4g_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp4g_usermeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp4g_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp4g_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp4g_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp4g_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp4g_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp4g_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp4g_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp4g_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp4g_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp4g_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp4g_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp4g_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp4g_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp4g_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp4g_wdp_orders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp4g_wdp_order_items: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp4g_wdp_rules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp4g_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp4g_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp4g_wfconfig: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp4g_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp4g_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp4g_wffilemods: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp4g_wfhits: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp4g_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp4g_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp4g_wfknownfilelist: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp4g_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp4g_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp4g_wflogins: Data: 0.23MB + Index: 0.08MB + Engine InnoDB
wp4g_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp4g_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp4g_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp4g_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp4g_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp4g_wfsnipcache: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp4g_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp4g_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp4g_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp4g_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp4g_wpml_mails: Data: 0.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 309
custom_css: 2
customize_changeset: 102
elementor_lead: 27
elementor_library: 19
mc4wp-form: 1
nav_menu_item: 21
page: 14
plugin_filter: 1
post: 4
product: 53
product_variation: 166
revision: 63
rey-global-sections: 4
shop_coupon: 3
shop_order: 46
shop_order_refund: 3
wbcr-snippets: 4
wp_block: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (1) ###

WooCommerce: by Automattic – 5.1.0

### Inactive Plugins (28) ###

Admin Menu Editor: by Janis Elsts – 1.9.9
Advanced Dynamic Pricing for WooCommerce: by AlgolPlus – 3.2.2
Ajax Cart AutoUpdate for WooCommerce: by taisho – 1.5.4
Aliexpress Dropship for Woocommerce: by MA-Group – 1.14.4
Astra Customizer Reset: by Brainstorm Force – 1.0.4
Astra Pro: by Brainstorm Force – 3.2.0
Block Specific Spam Woo Orders: by guwii – 0.53
Code Snippets: by Code Snippets Pro – 2.14.1
Custom Login Page Customizer: by Hardeep Asrani – 2.1.2
Duplicate Page: by mndpsingh287 – 4.4
Elementor: by Elementor.com – 3.1.4
Elementor Pro: by Elementor.com – 3.2.1
Enable Media Replace: by ShortPixel – 3.5.0
Lenix Elementor Leads addon: by Lenix – 1.8.1
OoohBoi Steroids for Elementor: by OoohBoi – 1.6.6
Plugin Organizer: by Jeff Sterup – 10.1.4
Rank Math SEO: by Rank Math – 1.0.60.1
Rank Math SEO PRO: by Rank Math – 2.4.2
Temporary Login Without Password: by StoreApps – 1.6.10
Variation Swatches for WooCommerce: by Emran Ahmed – 1.1.13
WooCommerce Admin: by WooCommerce – 2.1.3
WooCommerce Multi Currency Premium: by VillaTheme – 2.1.11
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.1
WooCommerce Stripe Gateway: by WooCommerce – 5.0.0
WPC Fly Cart for WooCommerce: by WPClever.net – 2.5.0
WP Mail Logging: by MailPoet – 1.9.7
WP Mail SMTP: by WPForms – 2.7.0
WPS Hide Login: by WPServeur
NicolasKulka
wpformation – 1.8.5

### Must Use Plugins (1) ###

Plugin Organizer MU: by Jeff Sterup – 10.1.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #2180 - /shop/
Cart: #32 - /cart/
Checkout: #33 - /checkout/
My account: ❌ Page not set
Terms and conditions: #2421 - /terms-conditions/

### Theme ###

Name: Storefront
Version: 3.5.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 3,977
Oldest: 2021-02-27 12:37:52 +0000
Newest: 2021-03-29 13:48:19 +0000

Pending: 4
Oldest: 2021-03-29 14:03:19 +0000
Newest: 2021-04-01 10:47:32 +0000

### Status report information ###

Generated at: 2021-03-29 14:48:37 +01:00
`
</details>

**Comment by juliaamosova** [comment]
Hi @studiojpeg,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. I tested using WooCommerce 5.1 with Twenty Twenty theme. 

See screencast below:

![](http://g.recordit.co/Y9Acfo6kWN.gif)

It's hard to tell what could be going on on your site. Can you please check if there are any errors in the browser console?

**Comment by studiojpeg** [comment]
Solved. It had to do with my **php.ini** file being fetched.

**Comment by juliaamosova** [comment]
Thanks for your quick follow-up @studiojpeg! Glad to hear the issue had been resolved. I am closing this issue. Please feel free to open a new one in case you'd need further help.
