### ISSUE TITLE
wc_get_low_stock_amount() returns a string if not set at product level

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#29525]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When the low stock amount is pulled from the global settings via `$low_stock_amount = get_option( 'woocommerce_notify_low_stock_amount', 2 );` 

the value returned is a string and not an integer like the doc-block suggests.

**Expected behavior**
Always return an integer.

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to product data metabox
2. select "manage stock" checkbox
3. leave "low stock" threshold empty/null
![image](https://user-images.githubusercontent.com/507025/112854251-e6520480-906a-11eb-8fff-fe0629ce7724.png)

4. Add snippet:
```
function kia_test_low_stock_amount() {
	global $product;
	var_dump( wc_get_low_stock_amount( $product ) );
}
add_action( 'woocommerce_before_add_to_cart', 'kia_test_low_stock_amount' );
```
5. Visit product page.
6. See the threshold is a string
![image](https://user-images.githubusercontent.com/507025/112854489-24e7bf00-906b-11eb-86ba-0acf16a29da3.png)

7. Optionally, you can edit the product's low-stock threshold, save, and refresh the page to confirm it's an integer when set at the product-level.

**Comment by juliaamosova** [comment]
Thanks for reporting @helgatheviking! I'll mark this one as a `high` priority for us to fix.

**Comment by helgatheviking** [comment]
I'd think a little `intval()` before returning would probably resolve it
