### ISSUE TITLE
The E2E failure reporter for Slack fails with `channel_not_found`

### ISSUE THREAD

**Issue by samueljseay** [woocommerce/woocommerce#29532]
I have set up the slack reporter as specified in the `@woocommerce/e2e-environment` package with the correct permissions and environment secrets etc, but when an e2e test fails the slack reporter fails to report it with error `channel_not_found`. 

I think this issue exists for you in WooCommerce as well. I looked at some recent PRs and when they fail e2e tests the slack reporter also fails with `channel_not_found`.

I'm using version 0.2.0 of `@woocommerce/e2e-environment`.

Here's an example of the failure in woocommerce: https://github.com/woocommerce/woocommerce/pull/29441/checks?check_run_id=2150546265#step:9:61

Here's an example of the failure in woocommerce-admin: https://github.com/woocommerce/woocommerce-admin/pull/6682/checks?check_run_id=2224275584#step:7:1376

Let me know if I can add any more detail. Thanks!

**Comment by rrennick** [comment]
> but when an e2e test fails the slack reporter fails to report it with error channel_not_found.

@samueljseay That's an error on the call that joins the channel that we trap but log the error message.

> I think this issue exists for you in WooCommerce as well.

The error is being logged in core but it doesn't prevent the messages or screenshots being posted to the channel. I wasn't able to find a method to check whether the bot was currently joined to the channel. I hope to do some more investigation over the next couple sprints for a way to detect that.

The way we got our channel set up was testing locally first with

```
WC_E2E_SCREENSHOTS=1 E2E_SLACK_TOKEN='{token}' E2E_SLACK_CHANNEL='{channel-name}' npx wc-e2e test:e2e /.../broken-test.js
```

**Comment by rrennick** [comment]
Re-opening this issue as the message should be silenced until it can be investigated further.
