### ISSUE TITLE
Cannot Place Order: '' is not a valid country code error when on latest version

### ISSUE THREAD

**Issue by adeelejaz** [woocommerce/woocommerce#29545]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I recently updated to latest version of woocommerce and the PayPal Express plugin. Since the update, no one can checkout. We do not use any other payment method. Pressing the "Place Order" button on the checkout screen shows the following error: `'' is not a valid country code.`

**Expected behavior**
Place the order successfully

**Actual behavior**
When using PayPal plugin, the customer bypasses woocommerce checkout by going to PayPal from cart page, and is brought back to the final checkout page. Clicking Place Order shows the error.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Hit the PayPal button on the Cart page.
1. Login to PayPal and authorise the transaction
1. Come back to the checkout page, accept terms and conditions, and click "Place Order" button

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

I have also downgraded to older version of PayPal plugin, and it still doesn't work.

**WordPress Environment**
<details>
```
<summary>System status</summary>

`
### WordPress Environment ###

WordPress address (URL): <snipped>
Site address (URL): <snipped>
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.7.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.1.2
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: nginx/1.18.0
PHP Version: 7.4.15
PHP Post Max Size: 8 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.0.2k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.13-MariaDB-log
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ❌ Your server does not support the mbstring functions - this is required for better character encoding. Some fallbacks will be used instead for it.
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.0.0
WC Database Prefix: wp_xxx_
Total Database Size: 25.37MB
Database Data Size: 15.28MB
Database Index Size: 10.09MB
### Post Type Counts ###

attachment: 6
br_notice: 3
custom_css: 1
et_pb_layout: 1
nav_menu_item: 21
page: 14
post: 1
product: 22
revision: 146
shop_order: 789
shop_order_refund: 109

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (10) ###

Cart Notices for WooCommerce: by BeRocket – 3.5.2.2
Classic Editor: by WordPress Contributors – 1.6
Feed Them Social - for Twitter feed, Youtube, and more: by SlickRemix – 2.9.4
WooCommerce Blocks: by Automattic – 4.7.0
WooCommerce Admin: by WooCommerce – 2.1.2
WooCommerce Conversion Tracking: by weDevs – 2.0.8
WooCommerce Easy Booking: by @_Ashanna – 3.0.2
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.1
WooCommerce: by Automattic – 5.1.0
WP Mail Logging: by MailPoet – 1.9.7

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Feed Them Premium: by Joe – 1.0.0
Hello Dolly: by Matt Mullenweg – 1.7.2

### Must Use Plugins (1) ###

ET Support Center :: Must-Use Plugins Autoloader: by Elegant Themes –

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #82 - /book-online/
Basket: #83 - /cart/
Checkout: #84 - /checkout/
My account: #85 - /my-account/
Terms and conditions: #124 - /terms-conditions/

### Theme ###

Name: Divi Child Theme
Version: 1.0.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 4.9.2
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: Divi-Child/woocommerce/emails/customer-processing-order.php

### Action Scheduler ###

Complete: 53
Oldest: 2021-02-16 06:31:52 +0000
Newest: 2021-03-18 19:15:30 +0000

Pending: 1
Oldest: 2021-03-19 07:25:27 +0000
Newest: 2021-03-19 07:25:27 +0000


### Status report information ###

Generated at: 2021-03-19 04:11:06 +00:00
`
```
</details>

**Comment by adeelejaz** [comment]
Related bug open in PayPal Repo: https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/858

**Comment by juliaamosova** [comment]
Hi @adeelejaz,

Thank you for raising the issue. However, the bug seems to be on the PayPal Express Checkout side of things. I see that you already opened an issue there https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/858. The team that maintains that plugin will get back to you soon. Thanks for your patience!

I am closing this issue here since this is not a WooCommerce Core issue. If I missed something, please comment back and we'd take another look.

**Comment by adeelejaz** [comment]
Hi @juliaamosova ,

The only way to fix so far as has been to revert to older version of WooCommerce (https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/issues/858#issuecomment-810103052). Downgrading the PayPal plugin doesn't fix the issue. Does that still mean it is not a core issue?
