### ISSUE TITLE
E2E Tests: Provide support for using nightly build from WP_VERSION env variable

### ISSUE THREAD

**Issue by adrianduffell** [woocommerce/woocommerce#29547]
**Is your feature request related to a problem? Please describe.**

My use-case is to run the E2E tests against the nightly build of WordPress. I followed the documentation to create a custom init routine, using the example in https://github.com/woocommerce/woocommerce/blob/trunk/tests/e2e/docker/init-wp-beta.sh as a base.

However I found it had some shortcomings:

1. It's not simple to switch between different init routines, since these gets built into the Docker image and remain between uses.
2. The process requires updating WordPress using the Wordpress Beta Tester plugin. However this can result in full-size screens which the E2E tests don't expect. For example I saw "What’s New" and "Database Update Required" screens.

**Describe the solution you'd like**

It would be nice to be able to specify the WordPress version using the environment variable. For example: `WP_VERSION=nightly` . This would then cause the docker image to use the nightly build directly without the need for the the Wordpress Beta Tester plugin

**Describe alternatives you've considered**

Alternatively perhaps those full-size screens could be automatically detected and dismissed by the E2E tests.

**Additional context**

I ended up using an external container, which I built using wp-env. Thanks for providing support for external containers!

**Comment by rrennick** [comment]
@adrianduffell Thanks for the suggestion. The issue is that there isn't docker-compose support for WP nightlys, betas, etc. The docker-wordpress development team only release the libraries for released WP versions.

> I ended up using an external container, which I built using wp-env.

Thanks for the tip. wp-env works around the docker-compose limitation by downloading WP with node. I wasn't aware that it bypassed the splash screens. I can look to see how wp-env does that and we may be able to do the same.

**Comment by adrianduffell** [comment]
@rrennick Much thanks for taking a look at this.

I think `wp-env` works by overwriting `/var/www/html`  with a bind mount containing the downloaded version.

https://github.com/WordPress/gutenberg/blob/3da717b8d0ac7d7821fc6d0475695ccf3ae2829f/packages/env/lib/build-docker-compose-config.js#L28-L49

**Comment by rrennick** [comment]
> I think wp-env works by overwriting /var/www/html with a bind mount containing the downloaded version.

It does. But, I don't think replacing the files turns off the splash screens. At least, when I do that on a regular site I still get the DB update screen.

**Comment by adrianduffell** [comment]
I see what you mean. I think, on first use at least, wp-env replaces the files and is actually installing WP for the first time. The splash screens then don't appear because an upgrade wasn't involved.

**Comment by rrennick** [comment]
> The splash screens then don't appear because an upgrade wasn't involved.

That makes sense. I think there may be a way to silence the WP splash screen with WP CLI but it's been a few years. I'm hoping to be able to look at this this week.

**Comment by rrennick** [comment]
@adrianduffell This looks like it will have to wait until the 5.8 beta is released so we have a splash screen to work with. The beta tester plugin won't update in CLI from 5.6.X to 5.7.
