### ISSUE TITLE
Limiting areas an item is shipped to with free shipping

### ISSUE THREAD

**Issue by sumitparkash** [woocommerce/woocommerce#29552]
We have 2 types of products in our store.

One is Local Juices which are available locally and has a shipping cost of £5.
Another is Supplement US which is available nationally and has a shipping cost of £10.

We’ve set it up basically the same way:

– Two shipping classes: **“Local US”** and **“National US”**

Two shipping zones.
The first is **“Local Delivery US”** (US with Zone regions Florida), Flat rate, Cost left blank “Local US” shipping class cost £5”, “National US” shipping class cost left blank”, “no shipping class cost” left blank (so showing “N/A”).
The second is **“US”** (US with no further restrictions), Flat rate, Cost left blank, “Local US” shipping class cost left blank, “National US” shipping class cost £10, “no shipping class cost” left blank.

Calculation type is “per class” for both shipping zones.

Everything is working fine except for 2 problems.
One is already been reported https://github.com/woocommerce/woocommerce/issues/27030.

Second, we have a problem with the local delivery products  when we enable free shipping

We want to give free shipping on orders over £100. So we added a new shipping method “Free Shipping” to both the shipping Zones.

After adding this “Free Shipping” method”, the local delivery product is available nationally when the order total is over £100. ie. It's showing the option **Free shipping** instead of showing **No shipping options were found** when it's outside of the **Local Delivery US** zone.
We can’t deliver those products everywhere.

So, Even when the order total is over £100 We want that product under local delivery should show the option **“No shipping options were found”** when the shipping address is other than the “Local delivery Us” i.e. when the state is not Florida ( **Local Delivery US** zone).

I am testing this on a standalone WordPress project with only the WooCommerce plugin installed

**Expected behavior**
After adding this “Free Shipping” method”, in case of only **Local Juices product** with order total over £100.
it should show the option **No shipping options were found** when the shipping address is other than Florida ( **Local Delivery US** zone )

**Actual behavior**
After adding this “Free Shipping” method”, in case of only **Local Juices product** with order total over £100. It's showing the option **Free shipping**

**Screenshots**

![Shipping_Classes](https://user-images.githubusercontent.com/24988527/113170522-42cc4400-9264-11eb-854e-f68882bc2a29.png)
![Product_with_Local_US_shipping_class](https://user-images.githubusercontent.com/24988527/113170555-48c22500-9264-11eb-8d35-4c9eb3399eae.png)
![Shipping_Zones](https://user-images.githubusercontent.com/24988527/113170584-5081c980-9264-11eb-9051-5eb444fa33da.png)
![Local_Delivery_US_Shipping_Zone](https://user-images.githubusercontent.com/24988527/113170596-52e42380-9264-11eb-814f-2451628dcdbe.png)
![Local_Delivery_US_Shipping_Zone_Free_Shipping](https://user-images.githubusercontent.com/24988527/113170617-5a0b3180-9264-11eb-84cf-7a1437a2bed5.png)
![Local_Delivery_US_Shipping_Zone_Flat_Rate](https://user-images.githubusercontent.com/24988527/113170606-5677aa80-9264-11eb-826a-62784b8fc516.png)
![US_Shipping_Zone](https://user-images.githubusercontent.com/24988527/113170656-655e5d00-9264-11eb-8bdf-ec7733ea3818.png)
![US_Shipping_Zone_Free_Shipping](https://user-images.githubusercontent.com/24988527/113170666-67282080-9264-11eb-91ea-ad99804a7033.png)
![US_Shipping_Zone_Flat_Rate](https://user-images.githubusercontent.com/24988527/113170680-68f1e400-9264-11eb-9931-382df884e252.png)

![checkout_page_no_issue](https://user-images.githubusercontent.com/24988527/113170689-6b543e00-9264-11eb-8d02-0fc54130c77e.png)
![checkout_page_with_issue](https://user-images.githubusercontent.com/24988527/113170695-6d1e0180-9264-11eb-9cb1-e2c4c5892986.png)

**Comment by Mtarnuhal** [comment]
That's indeed a issue. I also think that we should be able to set the free shipping per class.
Example you have 2 shipping classes one is normal parcel and the second is pallet shipping.
Pallet shipping is more expensive than a normal parcel so you would like the free shipping of the parcel to be lower than for the pallet.

**Comment by juliaamosova** [comment]
Hi @sumitparkash,

Thank you for opening the issue and providing very clear details of your setup. I tested your use case by setting up the same (a few key screenshots below):

<img width="1433" alt="Screen Shot 2021-04-03 at 11 36 48 AM" src="https://user-images.githubusercontent.com/19143190/113483353-fc980000-9470-11eb-87cc-36854f8e4447.png">

<img width="1104" alt="Screen Shot 2021-04-03 at 11 37 01 AM" src="https://user-images.githubusercontent.com/19143190/113483358-ff92f080-9470-11eb-9ee6-00a24b91baac.png">

Everything is working as expected, however. 

The fact that you have set up a `Local US` shipping class doesn't have much effect on the shipping setup you have. 

The thing is that you still added `Flat Rate` to the `US` shipping zone. Even if the price for the `Local US` shipping class in the `US` shipping zone is left blank, `Flat Rate` will still be offered for orders under £100. 

The same goes for `Free Shipping` - it had been added to both shipping zones with the same requirement. There are not enough restrictions in the `Local Delivery US` shipping zone to not allow `Free Shipping` to be offered when the `Local Juices` product is added to the cart. 

The basic shipping functionality of WooCommerce is not suitable for the conditional type of shipping you are looking to set up. We have a plugin however that will help you accomplish exactly what you are looking for - [Conditional Shipping and Payments](https://woocommerce.com/products/conditional-shipping-and-payments/). 

I hope that helps you move forward with setting up the shipping the way you need. I'll keep this thread open for some time in case you have any other questions.

**Comment by juliaamosova** [comment]
>That's indeed a issue. I also think that we should be able to set the free shipping per class.

@Mtarnuhal we have a plugin however that will help you accomplish exactly that - [Conditional Shipping and Payments](https://woocommerce.com/products/conditional-shipping-and-payments/).
