### ISSUE TITLE
Order line item adjust stock is limited to statuses processing, completed & on-hold.

### ISSUE THREAD

**Issue by ecottles** [woocommerce/woocommerce#29566]
Hello,

This issue was closed, however the issue persists.

**roykho** responded to the issue with the following:
Hi @ecottles - thanks for bringing this up however I believe you can already achieve this. If you have already added your custom order statuses you can use this action add_action( 'woocommerce_order_status_YOUR_CUSTOM_STATUS', 'wc_maybe_reduce_stock_levels' );

Then Closed the Issue.

The filter you describe is fine for cart transactions. But not when the admin a saving an order.

This change affects admins ability to maybe reduce stock when saving an order with a status other than >>> processing', 'completed', 'on-hold'. <<< **There is no filter to change this behavior.

If you look at the code you will see, function wc_maybe_adjust_line_item_product_stock( $item ); has been wrapped with an if statement limiting to three statuses. >>> processing', 'completed', 'on-hold'. <<< If the admin saves an order with any other status than one of the three, function wc_maybe_adjust_line_item_product_stock( $item ); **WILL  NEVER FIRE.**

There is no filter to change this behavior.
Should have never been done in the first place. Why the limitation?

**Within function wc_save_order_items:**
Line 345;
if ( in_array( $order->get_status(), array( 'processing', 'completed', 'on-hold' ) ) ) {
    $changed_stock = wc_maybe_adjust_line_item_product_stock( $item );
    if ( $changed_stock && ! is_wp_error( $changed_stock ) ) {
        $qty_change_order_notes[] = $item->get_name() . ' (' . $changed_stock['from'] . '&rarr;' . $changed_stock['to'] . ')';
     }
}

There is no filter to change this behavior.

A filter is absolutely necessary or remove the if statement.

Good Day

Originally posted by @ecottles in #27504 (comment) @

_Originally posted by @ecottles in https://github.com/woocommerce/woocommerce/issues/29448#issuecomment-811935550_

**Comment by roykho** [comment]
Hi @ecottles - so there is no need to open up another issue for this. You can comment on closed issue as well. Thanks. 

Ref back to here https://github.com/woocommerce/woocommerce/issues/29448
