### ISSUE TITLE
wc_admin_url called from dashboard setup

### ISSUE THREAD

**Issue by vendidero** [woocommerce/woocommerce#29567]
**Describe the bug**
Error: Call to undefined function wc_admin_url() in `woocommerce/includes/admin/class-wc-admin-dashboard-setup.php` line 116

**Expected behavior**
Do not call functions defined within wc-admin package only from the core or at least add a function_exists wrapper.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Disable wc-admin via filter
2. Open WP-Admin dashboard

**Comment by juliaamosova** [comment]
Hi @vendidero,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

I used the `add_filter( 'woocommerce_admin_disabled', '__return_true' );` filter to disable WooCommerce Admin but did not experience the error. Tested using WooCommerce 5.1. 

Can you please confirm what version of WooCommerce are you using?

**Comment by vendidero** [comment]
Hi there,

this was tested with the latest RC. The file is being conditionally included as a dashboard widget from within:
https://github.com/woocommerce/woocommerce/blob/trunk/includes/admin/class-wc-admin.php#L87

To reproduce you'll need to make sure that this method returns true (check the options):
https://github.com/woocommerce/woocommerce/blob/trunk/includes/admin/class-wc-admin-dashboard-setup.php#L111

In case the method returns true, the `wc_admin_url` function is being called from:
https://github.com/woocommerce/woocommerce/blob/trunk/includes/admin/class-wc-admin-dashboard-setup.php#L111

Cheers

**Comment by rrennick** [comment]
@vendidero Can you clarify where you added the filter?

**Comment by vendidero** [comment]
Hi there,

via a Plugin:

`add_filter( 'woocommerce_admin_disabled', '__return_true' );`

But as I've already stated - it doesn't actually matter as the code (missing functions) is called anyway.

Cheers

**Comment by rrennick** [comment]
@vendidero Can you confirm you still encounter the issue with the latest RC? If so, could you submit a system status report?

**Comment by vendidero** [comment]
Hi,

yep, the error is triggered right after updating to RC2. Could you please check the actual code? It is obvious that the non-defined function (in Woo Core `wc_admin_url` is not defined) `wc_admin_url` is called without an additional check. I've actually explained that above already. You might need to make sure that the `woocommerce_task_list_tracked_completed_tasks` has already been populated with some tasks.

Cheers

**Comment by roykho** [comment]
I am able to replicate this issue. This has to return true to reproduce https://github.com/woocommerce/woocommerce/blob/trunk/includes/admin/class-wc-admin-dashboard-setup.php#L164

`wc_admin_url` was added in this commit https://github.com/woocommerce/woocommerce/pull/29174 so I think we need to wrap it with `is_wc_admin_active()`
