### ISSUE TITLE
TwentyTwentyOne info and message styles are the same

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#29560]
**Is your feature request related to a problem? Please describe.**
In the TwentyTwentyOne theme stylesheet, the current styles for the `.woocommerce-info` and `.woocommerce-message` classes are the same:
```
.woocommerce-info,
.woocommerce-message {
 background:#eee;
 color:#000;
 border-top:2px solid #88a171
}
```

This means there's no distinction between info and success (as there's no separate class for success).

**Describe the solution you'd like**
Separate these two style rules and provide distinct color styles

**Comment by juliaamosova** [comment]
Hi @helgatheviking,

Thank you for taking the time to share this idea, we really appreciate your help. 

While this is clearly a great improvement/idea we won’t be able to tackle it in the upcoming weeks. We’re going to add it to our backlog where it will be considered for future releases.

**Comment by helgatheviking** [comment]
I don't really know how you arrived at the colors from the core Woo colors, but happy to send a PR that just separates the two styles and picks some colors.

**Comment by juliaamosova** [comment]
Adding the `needs developer feedback` label here so that the Core team could take a look further and provide further feedback. Thanks for your patience @helgatheviking!

**Comment by vedanshujain** [comment]
@helgatheviking looks like we did not have separate colors in twenty-nineteen and twenty-twenty either, so if we change we should change in all these themes. I am marking this as a low priority for now, since it does not affect functional WC behavior, and also marking for feedback from design to get some color picked.

**Comment by helgatheviking** [comment]
@vedanshujain Yes, I think I opened an issue about Twenty Twenty at least. I think they should all use distinct colors (doesn't WC core?), but agree it isn't urgent since it's not breaking things..
