### ISSUE TITLE
.wc-product-search multiple select is sorting alphabetically and there is not filter to change this

### ISSUE THREAD

**Issue by hamza-wpbrigade** [woocommerce/woocommerce#29573]
I was trying to change the default upsells products sort order.

The `woocommerce_upsells_orderby` and `woocommerce_upsells_order` filter allow me to do that. But I cannot change the sorting order for Upsells in the admin.

`.wc-product-search` for not-sortable multiple select is set to be ordered alphabetically via JS.

Please add a filter to override this.

JS File: wc-enhanced-select.js

**Comment by hamza-wpbrigade** [comment]
@mikejolley

**Comment by vedanshujain** [comment]
@hamza-wpbrigade hi, while it does not looks like a filter like this will be useful for everyone, you can already customize using a snippet like so in frontend:

```
$( ':input.wc-product-search' ).on('change, function () { 
.. your custom sort code...
});
```

You would have to take care that this code executes after the sort code in `wc-enhanced-select.js` is already executed, so this definitely would need some custom work.

Note that we generally won't support custom code requests, we use GH to track bugs and feature requests.
