### ISSUE TITLE
Quick View on Product Page

### ISSUE THREAD

**Issue by yoshi4444** [woocommerce/woocommerce#29578]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ x ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
 
When Click on the Quick View button it goes to a blank white screen. with the following console errors:

Uncaught TypeError: Cannot read property 'contains' of null
    at r.nodeType.r.documentElement.y (jquery.min.js?ver=3.5.1:2)
    at Function.se.contains (jquery.min.js?ver=3.5.1:2)
    at Pe (jquery.min.js?ver=3.5.1:2)
    at s.fn.init.append (jquery.min.js?ver=3.5.1:2)
    at s.fn.init.<anonymous> (jquery.min.js?ver=3.5.1:2)
    at $ (jquery.min.js?ver=3.5.1:2)
    at s.fn.init.html (jquery.min.js?ver=3.5.1:2)
    at Object.success (astra-addon-606767590231c0-05209237.js?ver=3.2.0:1)
    at c (jquery.min.js?ver=3.5.1:2)
    at Object.fireWith [as resolveWith] (jquery.min.js?ver=3.5.1:2)

jquery.min.js?ver=3.5.1:2 Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at HTMLDocument.<anonymous> (<anonymous>:6:21)
    at e (jquery.min.js?ver=3.5.1:2)
    at t (jquery.min.js?ver=3.5.1:2)

**Expected behavior**
Quick View should pull up a quick view of the product on the products page without leaving the products page.

**Actual behavior**
When clicking on the Quick View button for a specific item on the products page it starts to spin like it will pull it up then it goes to a blank white page. It does not redirect as intended for the quick view however it looks like it redirects.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Make sure Quick View is enabled in the customized portion of wordpress.
2. Go to products page
3. Click on Quick View on a Single Product

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by yoshi4444** [comment]
this is on https://www.famcomfg.com/products/wall-vents/dryer-vents/

**Comment by juliaamosova** [comment]
Hi @yoshi4444,

Thank you for raising the issue. However, it doesn't have enough details for us to reproduce it.

>Make sure Quick View is enabled in the customized portion of wordpress.

Are you using any plugin to enable Quick View on the product?

**Comment by yoshi4444** [comment]
Closing issue.
