### ISSUE TITLE
"By Category" filter does not count private products

### ISSUE THREAD

**Issue by alessandrofrancesconi** [woocommerce/woocommerce#29580]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
In Products page, the "By Category" selector has a counter for how many items are part of each category. This counter does not consider Private products.

**Expected behavior**
I have 9 products set to "Private", all of them belongs to category named "Parts". In the "By Category" filter I expect the item for this category to be "Parts (9)".

**Actual behavior**
In the filter combobox, the menu item for this category is "Parts (0)" instead.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create 1 Product with Category "AAA" set to "Public"
2. Create 1 Product with Category "BBB" set to "Private"
3. Go to Products page and check the "By Category" filter
4. Counter for "AAA" is 1 (correct), while for "BBB" is still 0.
5. If you turn the product "BBB" to "Public", then the counter shows 1 correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/1595223/113472917-770f5280-9466-11eb-87d9-90d51f1f4f65.png)
![image](https://user-images.githubusercontent.com/1595223/113472994-0288e380-9467-11eb-895c-b22db474b78f.png)

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): https://sparkevo.racing
Site address (URL): https://sparkevo.racing
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.2
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.16
PHP Post Max Size: 20 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.61.1
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.27-MariaDB
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.1.0
WC Database Prefix: wp_
Total Database Size: 13.36MB
Database Data Size: 9.14MB
Database Index Size: 4.22MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 3.45MB + Index: 0.08MB + Engine InnoDB
wp_postmeta: Data: 0.39MB + Index: 0.27MB + Engine InnoDB
wp_posts: Data: 1.09MB + Index: 0.06MB + Engine InnoDB
wp_redirection_404: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_sfa_abandoned_carts: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_statistics_exclusions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_statistics_historical: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_statistics_pages: Data: 0.06MB + Index: 0.20MB + Engine InnoDB
wp_statistics_search: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_statistics_useronline: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_statistics_visit: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_statistics_visitor: Data: 1.52MB + Index: 1.03MB + Engine InnoDB
wp_statistics_visitor_relationships: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_trp_dictionary_en_us_it_it: Data: 0.16MB + Index: 0.13MB + Engine InnoDB
wp_trp_gettext_en_us: Data: 0.42MB + Index: 0.30MB + Engine InnoDB
wp_trp_gettext_it_it: Data: 0.44MB + Index: 0.25MB + Engine InnoDB
wp_trp_original_meta: Data: 0.08MB + Index: 0.11MB + Engine InnoDB
wp_trp_original_strings: Data: 0.13MB + Index: 0.08MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

amz_configurator: 1
attachment: 53
custom_css: 3
customize_changeset: 2
decision_tree: 1
docs: 9
elementor_library: 1
language_switcher: 3
ml-slide: 10
ml-slider: 2
nav_menu_item: 5
page: 9
polylang_mo: 2
popup: 2
popup_theme: 9
post: 1
product: 14
product_variation: 51
revision: 22
sa_slider: 2
shop_coupon: 6
shop_order: 13
wpcf7_contact_form: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

Async JavaScript: by Frank Goossens (futtta) – 2.20.12.09
Change wp-admin login: by Nuno Morais Sarmento – 1.0.6
Contact Form 7: by Takayuki Miyoshi – 5.4
Cookie Notice & Compliance for GDPR / CCPA: by Hu-manity.co – 2.0.3
The Official Facebook Chat Plugin: by Facebook – 2.0
MetaSlider: by MetaSlider – 3.20.3
OG: by Marcin Pietrzak – 2.9.0
Popup Maker: by Popup Maker – 1.16.1
Redirection: by John Godley – 5.0.1
Title Remover: by WPGurus – 1.2.1
TranslatePress - Multilingual: by Cozmoslabs
Razvan Mocanu
Madalin Ungureanu
Cristophor Hurduban – 1.9.7

Use Any Font: by Dnesscarkey – 6.0.5
Abandoned Cart Reports For WooCommerce: by Small Fish Analytics – 2.6.2
WooCommerce Order Test: by WP Fix It – 1.6
WPC Product Bundles for WooCommerce (Premium): by WPClever – 5.5.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.1
WooCommerce: by Automattic – 5.1.0
Bootstrap Blocks: by Liip AG – 3.1.3
WP Mail SMTP: by WPForms – 2.7.0
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.1.8

WP Statistics: by VeronaLabs – 13.0.8

### Inactive Plugins (1) ###

Mailchimp for WooCommerce: by Mailchimp – 2.5.1

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
woosb (woosb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #96 - /shop/
Cart: #97 - /cart/
Checkout: #98 - /checkout/
My account: #99 - /account/
Terms and conditions: #18 - /policy/

### Theme ###

Name: Twenty Twenty Child
Version: 1.0.0
Author URL: http://sparkevo.racing/
Child Theme: ✔
Parent Theme Name: Twenty Twenty
Parent Theme Version: 1.7
Parent Theme Author URL: https://wordpress.org/
WooCommerce Support: ✔

### Templates ###

Overrides: twentytwenty-child/woocommerce/single-product/add-to-cart/variable.php
twentytwenty-child/woocommerce/single-product/short-description.php

### Action Scheduler ###

Complete: 56
Oldest: 2021-03-06 11:25:33 +0100
Newest: 2021-04-02 12:39:43 +0200

### Status report information ###

Generated at: 2021-04-03 10:27:00 +02:00
`
</details>

**Comment by zhongruige** [comment]
Hi @alessandrofrancesconi,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. I tested on the following:

* WordPress 5.7
* WooCommerce 5.1

**Replication Steps**

1. I set up a new WooCommerce site and added in the sample products
2. Using the default categories, I selected a product that was the only one in a category (WordPress Pennant in the Decor category)
3. I updated the product to be "Private"
4. Clicking on the category filter dropdown, I noted that the count was zero

<img width="929" alt="Screen Shot 2021-04-06 at 8 17 21 AM" src="https://user-images.githubusercontent.com/71906536/113744520-03698180-96c2-11eb-822f-80727d45dfb9.png">

5. I did double check to make sure the filter still allowed filtering on the product, despite the inaccurate count displayed and verified it continued to filter on the category as expected:

<img width="1372" alt="Screen Shot 2021-04-06 at 8 25 07 AM" src="https://user-images.githubusercontent.com/71906536/113744723-31e75c80-96c2-11eb-9aca-884c934e4ecf.png"> 

We’re going to solve this bug as soon as possible. Stay tuned for updates.

**Comment by roykho** [comment]
So I had a look at this however it seems this is the default behavior of WordPress. You can see the same thing happens with posts and post categories.
![](https://d.pr/i/reRbWp+)

In WooCommerce, we're using the same function `wp_dropdown_categories()`. I don't believe it supports showing counts for private posts.

**Comment by roykho** [comment]
Hi @alessandrofrancesconi - thanks for reporting this however after discussing with the team, we decided not to take any action on this because it is functioning/behaving as it does in WordPress core.
