### ISSUE TITLE
grouped.php version not updated on last change in WC 4.8.0

### ISSUE THREAD

**Issue by hjoelr** [woocommerce/woocommerce#29595]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
My theme overrides the grouped.php file. [WC 4.8.0 updated this file](https://github.com/woocommerce/woocommerce/pull/28169) but the file version was not changed. This means that the Template Overrides section of the WC Status page was not showing that my overridden template is out of date.

**Expected behavior**
When a template is changed, the version should be updated so it's easy to know which theme templates need to be updated.

**Actual behavior**
The file version was left at `4.0.0`.

**Screenshots**
![image](https://user-images.githubusercontent.com/221971/113624769-0c107800-962e-11eb-9db7-09ed7561f532.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by roykho** [comment]
Yes, you're correct @hjoelr - thanks for reporting!
