### ISSUE TITLE
Extensive unit tests for variation filter using lookup tables

### ISSUE THREAD

**Issue by vedanshujain** [woocommerce/woocommerce#29607]
We should add extensive unit tests as we implement variation filtering using a lookup table to:
1. Properly spec it.
2. As protection against future regressions.

Note that many unit tests may fail till we actually implement the solution, so we won't merge it to the trunk initially, but keep it in a PR which may act as a base PR for all the enhancements.

**Comment by Konamiman** [comment]
Closing because each of the pull requests that implement the feature are already including its own suite of unit tests.
