### ISSUE TITLE
Actualice la página web con lo último de Woocomerce.. luego me pidieron que actualizará la base de datos y que era obligatorio. Como resultado ahora no puedo ingresar al Shipping de Woocommerce y tampoco se muestra ahora los calculos del shipping en la web.

### ISSUE THREAD

**Issue by annier4** [woocommerce/woocommerce#29604]
He logrado encontrar el error, en ajustes se había puesto como deshabilitar las opciones de envío, ya lo habilite nuevamente. Gracias de todas formas.

**Comment by zhongruige** [comment]
Please note that we reply to bug reports in English language only. I used [Google Translate](https://translate.google.com/) to translate your message. You can use the same to translate my reply back. 

> I have managed to find the error, in settings it had been set to disable the shipping options, I already enabled it again. Thank you anyway. 

Just to confirm, it sounds like this issue may be resolved. If not, please let us know and we will take a look.

Thanks!
