### ISSUE TITLE
Bulk updating products to Sale [Price] Change to 'blank' actually sets sale price to 0 (free)

### ISSUE THREAD

**Issue by dcelsey** [woocommerce/woocommerce#29617]
**Prerequisites (mark completed items with an [x]):**
- [x ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Updating the sale price of products to blank using bulk update actually sets the sale price to zero. 

This is how I have always turned my sales off. i.e. I would select all products and set sale price to regular price -30% to start the sale. Then at the end of the sale I would set the sale price to blank. This worked fine up to my last sale - when I came to turn if off I bulk updated all the sale prices to blank. But when I check the site all products were FREE. In the back end the sale price showed as zero. I had to put my site in maintenance mode while I figured out how to remove the sale price without editing 100+ products by hand. 

Obviously sale price = blank and sale price = 0 are very different things, and interpreting blank as zero in this case is not correct, and not what used to happen.

I am not sure what version of Woo this changed in. It was fine when we ran our Cyber sale at the end of 2020, but I have updated all plugins since then.

I have also tested this with all plugins disabled and using the storefront theme.

**Expected behavior**
Bulk updating products using Sale Price Change to Blank removes the sale price and leaves products at the regular price.

**Actual behavior**
Bulk updating products using Sale Price Change to Blank sets sale price to 0 resulting in products being free

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

1. Go to Woocommerce products
2. Select (check) one or more products
3. Select Bulk Actions, Edit
4. Select Sale, Set to Regular price decreased by 30% (for example)
5. Select Update
6. Product prices(s) are now sale price
7. Select (check) one or more products on sale
3. Select Bulk Actions, Edit
4. Select Sale, Change To
5. Leave the Sale Price box blank
5. Select Update
6. Product prices(s) are now 0 and products are free

**Screenshots**
Here's a video from my test site. All plug ins deactivated and storefront theme. I am just doing one product for speed - when this happened on my live site I did all 100+ paid products and made my whole site free!

https://duncan-gmail.tinytake.com/tt/NTI2MzgzMV8xNjQ2OTUyMA

**Isolating the problem (mark completed items with an [x]):**
- [ X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.

`
### WordPress Environment ###

WordPress address (URL): https://tctcstaging.com
Site address (URL): https://tctcstaging.com
WC Version: 5.1.0
REST API Version: ✔ 5.1.0
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.2
Log Directory Writable: ✔
WP Version: ❌ 5.6.2 - There is a newer version of WordPress available (5.7)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.17.5
PHP Version: 7.4.9
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.25-MariaDB-10.2.25+maria~xenial
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.0.0
WC Database Prefix: wp_
Total Database Size: 474.57MB
Database Data Size: 270.12MB
Database Index Size: 204.45MB
wp_woocommerce_sessions: Data: 0.30MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 5.52MB + Index: 10.95MB + Engine InnoDB
wp_woocommerce_order_items: Data: 3.52MB + Index: 1.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 31.55MB + Index: 15.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.45MB + Index: 0.50MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.30MB + Index: 0.27MB + Engine InnoDB
wp_bad_behavior: Data: 0.48MB + Index: 0.03MB + Engine InnoDB
wp_cli_scripts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 2.03MB + Index: 0.11MB + Engine InnoDB
wp_comments: Data: 12.52MB + Index: 9.81MB + Engine InnoDB
wp_enmask_hits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_enmask_keywords: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_facetwp_index: Data: 1.42MB + Index: 0.69MB + Engine InnoDB
wp_gf_addon_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_draft_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_gf_entry: Data: 4.16MB + Index: 0.53MB + Engine InnoDB
wp_gf_entry_meta: Data: 8.50MB + Index: 13.61MB + Engine InnoDB
wp_gf_entry_notes: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_gf_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_meta: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_gf_form_revisions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_gf_form_view: Data: 1.52MB + Index: 0.42MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_magictoolbox_store: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_myo_ip: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 4.11MB + Index: 0.16MB + Engine InnoDB
wp_p2p: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_p2pmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_hash: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_imports: Data: 0.22MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxi_templates: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 92.63MB + Index: 67.75MB + Engine InnoDB
wp_posts: Data: 24.42MB + Index: 5.91MB + Engine InnoDB
wp_relevanssi: Data: 32.58MB + Index: 60.53MB + Engine InnoDB
wp_relevanssi_log: Data: 7.25MB + Index: 0.00MB + Engine InnoDB
wp_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_meta: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
wp_rg_form_view: Data: 0.36MB + Index: 0.25MB + Engine InnoDB
wp_rg_incomplete_submissions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_rg_lead: Data: 0.31MB + Index: 0.06MB + Engine InnoDB
wp_rg_lead_detail: Data: 1.52MB + Index: 0.77MB + Engine InnoDB
wp_rg_lead_detail_long: Data: 0.23MB + Index: 0.00MB + Engine InnoDB
wp_rg_lead_meta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_rg_lead_notes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ssbp_email_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_swp_analytics: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 1.52MB + Index: 1.00MB + Engine InnoDB
wp_term_relationships: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wp_term_taxonomy: Data: 1.52MB + Index: 2.00MB + Engine InnoDB
wp_usermeta: Data: 0.19MB + Index: 0.17MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 2.52MB + Index: 3.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_exported_csv_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpam_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_affiliates: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wpam_affiliates_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_creatives: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_impressions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_paypal_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_tracking_tokens: Data: 7.52MB + Index: 0.00MB + Engine InnoDB
wp_wpam_tracking_tokens_purchase_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_transactions: Data: 0.11MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 7.52MB + Index: 4.03MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.08MB + Index: 0.14MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_yoast_prominent_words: Data: 1.52MB + Index: 0.52MB + Engine InnoDB
wp_yoast_seo_links: Data: 3.50MB + Index: 1.92MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.34MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 3902
contentblock: 43
customize_changeset: 7
custom_css: 1
event: 47
myo_polling: 1
nav_menu_item: 60
oembed_cache: 172
option-tree: 1
page: 136
post: 937
product: 250
revision: 208
shop_coupon: 86
shop_order: 17940
shop_order_refund: 343
testimonial: 87
tribe_events: 1
tribe_organizer: 1
vc_grid_item: 3
wck-meta-box: 9

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 5.1.0

### Inactive Plugins (52) ###

ActiveCampaign for WooCommerce: by ActiveCampaign – 1.2.14
Akismet Anti-Spam: by Automattic – 4.1.8
Autoptimize: by Frank Goossens (futtta) – 2.8.1
CDN Enabler: by KeyCDN – 1.0.9
Collapsing Categories: by Robert Felty – 2.2.7
Crazy Egg: by Crazy Egg – 2.2
Disable Embeds: by Pascal Birchler – 1.4.0
Disable User Registration: by Andrei Gheorghiu – 1.0.1
Disable WooCommerce Bloat: by ospiotr – 2.4
FacetWP: by FacetWP
LLC – 3.7

FacetWP - Relevanssi integration: by FacetWP
LLC – 0.7.1

GDPR Cookie Consent: by WebToffee – 1.9.5
Gravity Forms: by Gravity Forms – 2.4.22
Gravity Forms ActiveCampaign Add-On: by Gravity Forms – 1.8
Gravity Forms Advanced Post Creation Add-On: by Gravity Forms – 1.0-beta-7
Image Widget: by Modern Tribe
Inc. – 4.4.7

Limit Login Attempts: by Johan Eenfeldt – 1.7.1
Magic Thumb for WooCommerce: by Magic Toolbox – 6.8.30
Maintenance: by WebFactory Ltd – 4.02
ManageWP - Worker: by GoDaddy – 4.9.8
Post Duplicator: by Metaphor Creations – 2.22
Posts 2 Posts: by scribu – 1.6.6
Regenerate Thumbnails: by Stifen – 2.0.5
Relevanssi: by Mikko Saari – 4.10.2
Social Media Widget: by Noah Kagan – 4.0.6
Social Warfare: by Warfare Plugins – 4.2.1
Social Warfare - Pro: by Warfare Plugins – 4.2.1
Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.24
Two Factor: by Plugin Contributors – 0.7.0
User Switching: by John Blackbourn & contributors – 1.5.6
WCK - Import Export Add-On: by Cozmoslabs
Cristophor Hurduban – 1.0.1

WooCommerce - Display Products by Custom Tax: by Elvis Morales – 2.2
WooCommerce Customer/Order/Coupon Export: by SkyVerge – 5.2.0 (update to version 5.3.2 is available)
WooCommerce Extended Coupon Features FREE: by Soft79 – 3.2.1
WooCommerce Filter Orders by Product: by Md. Kowsar Hossain – 3.2
WooCommerce Google Analytics Pro: by SkyVerge – 1.10.0
WooCommerce Grid / List toggle: by jameskoster – 1.2.1
WooCommerce PayPal Pro (Classic and PayFlow Editions) Gateway: by WooCommerce – 4.5.1
WordPress Creation Kit Hobbyist: by Cozmoslabs
Madalin Ungureanu
Cristian Antohe – 2.6.1

WordPress Importer: by wordpressdotorg – 0.7
WP-Sweep: by Lester 'GaMerZ' Chan – 1.1.3
WP Affiliate Manager: by wp.insider
wpaffiliatemgr – 2.8.0

WP All Import Pro: by Soflyy – 4.6.5
WPBakery Page Builder: by Michael M - WPBakery.com – 6.5.0
WP Crontrol: by John Blackbourn & crontributors – 1.9.0
WP Edit: by Josh Lobe – 4.0.4
wpMandrill: by Mandrill – 1.33
WP Menu Cart Pro: by Jeremiah Prummer
Ewout Fernhout – 3.5.0

WP Overnight Sidekick: by Jeremiah Prummer
Ewout Fernhout
Michael Kluver – 2.3.0

YITH WooCommerce Added to Cart Popup Premium: by YITH – 1.6.5
Yoast SEO: WooCommerce: by Team Yoast – 13.8
Yoast SEO Premium: by Team Yoast – 15.6.2

### Must Use Plugins (1) ###

Kinsta Must-use Plugins: by Kinsta Team – 2.3.1

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #1171 - /coaching-tools-catalogue/
Cart: #12776 - /cart/
Checkout: #12777 - /checkout/
My account: ❌ Page does not contain the [woocommerce_my_account] shortcode.
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.5.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1,203
Oldest: 2021-03-07 14:10:01 -0800
Newest: 2021-04-06 14:05:14 -0700

Pending: 2
Oldest: 2021-04-07 14:05:14 -0700
Newest: 2021-04-07 14:05:14 -0700

### Status report information ###

Generated at: 2021-04-07 09:46:28 -07:00
`

**Comment by zhongruige** [comment]
Hi @dcelsey,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. I tested this on the following:

* WordPress 5.7
* WooCommerce 5.1
* Using imported products

**Replication Steps**

* After setting up my store and importing products, I selected a few from the list and selected Bulk Actions > Edit

<img width="662" alt="Screen Shot 2021-04-08 at 10 12 57 AM" src="https://user-images.githubusercontent.com/71906536/114060938-1a8ba900-9853-11eb-87f1-5e225e89f50c.png">

* The the "Price" field, I selected "Change to" from the dropdown and left the field empty:

<img width="516" alt="Screen Shot 2021-04-08 at 10 13 10 AM" src="https://user-images.githubusercontent.com/71906536/114061136-5292ec00-9853-11eb-8a32-253c2b039259.png">

* I then clicked "Updated" and noted that the price for ever product selected was set to zero:

<img width="199" alt="Screen Shot 2021-04-08 at 10 16 45 AM" src="https://user-images.githubusercontent.com/71906536/114061335-90901000-9853-11eb-9523-58c516d85348.png">

* Note, too, this also occurs for the "Sale" category

I believe what we can do in this case is to make the field throw an error if it is empty to prevent accidental bulk updates to zero.

We won’t be able to include this fix in the upcoming release due to the lower priority of this issue compared to others reported. We’re going to add it to our backlog so we can include it in our planning for one of our future releases.

**Comment by dcelsey** [comment]
"I believe what we can do in this case is to make the field throw an error if it is empty to prevent accidental bulk updates to zero."

That is not the correct solution. Updating the Sale Price to blank is a valid action - it takes the product(s) off sale and sets it back to the regular price. This is exactly what you would do on an individual product to take it off sale.

It used to be possible to set the sale price to blank in bulk using the steps described - I have done this many times before. At some point this has changed to interpret blank as zero. I am wondering if somewhere this field is now being cast to a numeric value so blank gets changed to zero.

The use case is as I have described above - I set up a major sale by selecting all products and bulk update to set the sale price to regular less 30%. I turn the sale off by bulk updating the products to set sale price to blank.

The correct fix is to allow blank in the sale price field for bulk updates, and to set the sale price to blank if that is what is entered.

Thanks.

**Comment by sverleis** [comment]
Customer experiencing this issue - 7339427-zen

**Comment by Erbenda** [comment]
Il problema è ancora presente anche dopo tutte le versione aggiornate

**Comment by shameemreza** [comment]
Another report here: https://wordpress.org/support/topic/problema-con-sconti-in-percentuale

7340103-zen

**Comment by Erbenda** [comment]
> Another report here: https://wordpress.org/support/topic/problema-con-sconti-in-percentuale
> 
> 7340103-zen

esatto ma sembra che dopo tali aggiornamenti il problema vada nel dimenticatoio

**Comment by Uzwername** [comment]
To whoever it might concern: in case of the sale price you can pick

> Set to regular price decreased by (fixed amount or %)

option, then input `0%` and this will produce the desired result (the product will not be on sale anymore).

**Comment by Erbenda** [comment]
> A chiunque possa interessare: in caso di prezzo di vendita si può scegliere
> 
> > Impostato sul prezzo normale diminuito di (importo fisso o %)
> 
> opzione, quindi inserisci e questo produrrà il risultato desiderato (il prodotto non sarà più in vendita).`0%`

si ma questo non corrisponde al problema segnalato
