### ISSUE TITLE
REST API - woocommerce_product_invalid_image_id error with long src urls

### ISSUE THREAD

**Issue by databuzz** [woocommerce/woocommerce#29621]
I am using v2 of the REST API (have also tested with v3) and WooCommerce 5.1.0.

Uploading Products with images with long src url's results in the following error:

{
  "code": "woocommerce_product_invalid_image_id", 
  "data": {
    "status": 400
  }, 
  "message": "#0 is an invalid image ID."
}

If I shorten the src url to something shorter the Product is created/updated successfully.

Here's an example of one that fails:

`	"images" : 
	[
		{
			"alt" : "",
			"name" : "testImage",
			"src" : "https://myserver.com/41921PPP_MAJOR_HEALEY_WEARING_RABY_HUNT_UNIFORM_RIDING_THE_SEDGEFIELD_HUNT_BY_JOHN_FERNELEY__REPRODUCTION_PAINTING_PRINT_CANVAS__HORSE__ANIMAL__LEAPING_JUMPING__SPORTING_ART__WALL_ART__DECOR__EQUESTRIAN_SchoonerBayCo_Com-0.jpg"
		}
	],`

and the modified version that is successful:

`	"images" : 
	[
		{
			"alt" : "",
			"name" : "testImage",
			"src" : "https://myserver.com/41921PPP.jpg"
		}
	],`

I'm wondering if there is a limit to the length of the URLs here that can be submitted (the REST API docs don't mention anything here)?

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Comment by roykho** [comment]
Hi @databuzz - I don't recall imposing any hard limits to this ( having dug into it yet ). Could this be limited on the server level with the filesystem? Have you checked that first?
