### ISSUE TITLE
[GlobalStep] "Shipping Address" gets replaced with "Billing Address" under  "My Account->Addresses" when "Ship to a different address?"  is toggled off/unchecked during checkout

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#29628]
## Bug Description:
"Shipping Address" gets replaced with "Billing Address" under  "My Account->Addresses" when "Ship to a different address?"  is toggled off/unchecked during checkout

## Test Instructions:
Critical Flow (Shopper->My Account->Update Addresses) : https://github.com/woocommerce/woocommerce/wiki/Critical-Flows

## Environment:
Woocommerce Version: WooCommerce 5.2 RC2 and 5.1
WordPress version: (v5.7)

## PC:
Windows 10, Mac 10.14.6
Chrome(Version 89.0.4389.90) 
Firefox(Version 87.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins 
1. Complete OBW setup
1. Add/Import some products by clicking on "Products->Add New" 
1. Set up Payment method by clicking on "WooCommerce->Settings->Payments"
1. Enable all the Menus for easier navigation at the frontend by going to WooCommerce->Appearance->Customize->Menus->Create New Menu->give menu name->Select primary checkbox-> Add Home, My account, Checkout, Cart, and Shop
1. Click on "Publish" button
1. Go to frontend 
1. Go to My account->Addresses and set Shipping Address to India and Billing Address be US
1. Add a product to cart by clicking on "Add to Cart" button
1. Click on "View Cart" button
1. Click on "Proceed to Checkout" button
1. Note that Billing address will be prefilled to US by default and keep "Ship to a different address?" checkbox unchecked 
1. Click on "Place Order" button 
1. Note that Billing and Shipping Address is set to US
1. Go to "My Account->Addresses", Note that Shipping Address is also set to US 
1. Observe that  "Shipping Address" under "My Account->Addresses" changes to same as "Billing Address" if user does not select the "Ship to a different address?" option during checkout

## Actual Result:
"Shipping Address" gets replaced with "Billing Address" under  "My Account->Addresses" when "Ship to a different address?"  is toggled off/unchecked during checkout

## Expected Result:
"My Account->Addresses" should not change as per the user's preferences selected for individual orders.

## Video:

https://user-images.githubusercontent.com/41110392/114056207-0d9ca300-98af-11eb-9962-db1901f93108.mp4

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by zhongruige** [comment]
Hi @gglobalstep,

Thank you for reporting the issue. However, this issue had been reported previously [here](https://github.com/woocommerce/woocommerce/issues/28759#issuecomment-815295121). We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed. Thanks!

**Comment by fesarlis** [comment]
I can confirm that as of today this issue is still present. Perhaps the changes were not committed?
