### ISSUE TITLE
[GlobalStep] "Hidden" and "Shop only" options for Product Catalog visibility fails to work correctly 

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#29627]
## Bug Description:
"Hidden" and "Shop only" options for Product Catalog visibility fails to work correctly at frontend when products searched via Search bar

## Test Instructions:
Critical Flow (Merchant->Products->Edit Product details) : https://github.com/woocommerce/woocommerce/wiki/Critical-Flows

## Environment:
Woocommerce Version: WooCommerce 5.2 RC2 and 5.1
WordPress version: (v5.7)

## PC:
Windows 10, Mac 10.14.6
Chrome(Version 89.0.4389.90) 
Firefox(Version 87.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins 
1. Complete OBW setup
1. Go to Products->Add New
1. Edit product "Catalog Visibility"
1. Select "Shop only/Hidden" option 
1. Click on "Ok" button for catalog visibility
1. Click on "Publish" button
1. Go to frontend 
1. Search for the product just created 
1. Observe that the product is still seen in search results instead of saying "Product not found" as per the catalog visibility setting set.

## Actual Result:
"Hidden" and "Shop only" options for Product Catalog visibility fails to work correctly 

## Expected Result:
"Hidden" and "Shop only" options for Product Catalog visibility should work correctly 

## Video:

https://user-images.githubusercontent.com/41110392/114054245-4fc4e500-98ad-11eb-8ca7-0c08887a6bac.mov

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by zhongruige** [comment]
Hi @gglobalstep,

Thank you for reporting the issue. However, this issue had been reported previously [here](https://github.com/woocommerce/woocommerce/issues/28693) and there is [a PR for it as well](https://github.com/woocommerce/woocommerce/pull/28702). We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed. Thanks!
