### ISSUE TITLE
  POST?wc-ajax=get_refreshed_fragments | (canceled)  

### ISSUE THREAD

**Issue by fradaspa** [woocommerce/woocommerce#29620]
Hello guys. somebody can help me out?

POST?wc-ajax=get_refreshed_fragments | (canceled)

I got this call from all the pages and most of I heard come from the minicart even if that i don t have a cart in the site, and it let me lose 5 sec. 
What can I do? There is any code to add in the functions.php?

**Comment by roykho** [comment]
Hi @fradaspa - So this is not something we support here however you can try the following:

```
function wc_fragments_dequeue_script() {
	wp_dequeue_script( 'wc-cart-fragments' );
}
add_action( 'wp_print_scripts', 'wc_fragments_dequeue_script', 100 );
```

**Comment by fradaspa** [comment]
Thank you. It worked good :D
