### ISSUE TITLE
I need help with WooCommerce Plugin

### ISSUE THREAD

**Issue by douglasbentley** [woocommerce/woocommerce#29629]
**Prerequisites (mark completed items with an [x]):**
- [ x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

Hi family, I am looking for a plugin for WooCommerce that can do this: We sell an herbal essence to people who work with others. We call these people "Practitioners". Each practitioner has an account on our Wordpress site, which gives them discounts on the products.

What we are looking to do, is when a customer learns about our products from a Practioner, and they come to our site and purchase and create an account, we want to be able to associate the customers account and their sales to this Practioner. We want to be able to see a report of sales and who the customer's Prationer is so we can give a percentage of sales to them.

Hope this makes since, i have been searching a lot and haven;t found anything yet.

Thanks so much!

Doug

**Comment by zhongruige** [comment]
Hi @douglasbentley,

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only. I did, however, do a quick search and came across these two plugins which might fit your needs:

* [WooCommerce B2B](https://woocommerce-b2b.com/sales-agents/)
* [AffiliateWP](https://affiliatewp.com/)

Please contact the author of the plugin directly for further help or questions on their feature sets and if it meets your needs.

I am closing this issue for now. If I missed something, please leave a comment and we will take a second look.
