### ISSUE TITLE
 Error: An error occurred in the request and at the time were unable to send the consumer data.

### ISSUE THREAD

**Issue by iamashishk** [woocommerce/woocommerce#29622]
**Prerequisites (mark completed items with an [x]):**
- [ x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

![image](https://user-images.githubusercontent.com/22693536/113951441-33836280-9831-11eb-9a00-355d5e2cdd98.png)

After my user click approve button in api oauth screen. it gets this screen. and i am unable to find the solution till now,

**Comment by subtain-haider** [comment]
am facing this same issue, any solution for this????
