### ISSUE TITLE
Batch update entities

### ISSUE THREAD

**Issue by zdratoz** [woocommerce/woocommerce#29635]
It would be a nice idea to upgrade the batch update ,adding the "per_page" parameter. 

Woocomerece limit by default is 100. In this case you should update a script into the wordpress folders.
According to my solution , you could just have the ability to add a per_page param into the call.
That means that you could update a banch of 10 or 100000 in one line of code

**Comment by zhongruige** [comment]
Hi @zdratoz,

Thank you for taking the time to share this idea, we really appreciate your help. 

While this is clearly a great improvement/idea we won’t be able to tackle it in the upcoming weeks. We’re going to add it to our backlog where it will be considered for future releases.

Stay tuned for updates.

**Comment by barryhughes** [comment]
So for example, when [batch updating products](https://woocommerce.github.io/woocommerce-rest-api-docs/#batch-update-products), we should support:

```http
POST /wp-json/wc/v3/products/batch?per_page=1000
```

If so, I don't think it's likely we will support this (letting the client dictate this feels problematic). Instead, the upper limit can be set server side using the `woocommerce_rest_batch_items_limit` hook.

I'll go ahead and close this, but if you believe I've misunderstood please feel free to reply or open a fresh issue.
