### ISSUE TITLE
Low / min stock quantity doesn't allow decimal values

### ISSUE THREAD

**Issue by strarsis** [woocommerce/woocommerce#29643]
**Is your feature request related to a problem? Please describe.**
Currently the low / min stock quantity options are converted to absolute integer values, which makes the usage of decimal values impossible. However, these are important for some applications, e.g. using the [WooCommerce Measurement plugin](https://woocommerce.com/products/measurement-price-calculator/) where quantity (elegantly) represents the available length/dimension in stock.

**Describe the solution you'd like**
It should be sufficient to rewrite the parts so the options values are not ensured to be absolute integer values but rather absolute decimal values, including the placeholders used in the query that are prepared by [wpdb->prepare](https://developer.wordpress.org/reference/classes/wpdb/prepare/).

**Describe alternatives you've considered**
Filters like [woocommerce_report_low_in_stock_query_from](https://github.com/woocommerce/woocommerce/blob/5.1.0/includes/admin/reports/class-wc-report-low-in-stock.php#L38-L39) can be used to build the query with the option values that are not retrieved as integers. But this has to track changes of the query in the WooCommerce plugin. A more sophisticated alternative would use a SQL query parser to change the expected field values - but this may also require adjusting to new WooCommerce releases.

**Comment by tammullen** [comment]
Hi @strarsis 

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/27375. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
