### ISSUE TITLE
Fatal error: WooCommerce 5.2 and Elementor

### ISSUE THREAD

**Issue by NenadObradovic** [woocommerce/woocommerce#29656]
Hello guys,

I updated the latest version of the WooCommerce plugin and when I try to edit any page with Elementor page builder I get a fatal error. Errors only appear when you enabled any Payment methods, in my case I enabled Direct bank transfer.

Error log file:

Warning: Undefined array key "wc-cart-block" in /public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Payments/Api.php on line 221

Warning: Undefined array key "wc-cart-block-frontend" in /public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Payments/Api.php on line 221

Warning: Undefined array key "wc-checkout-block" in /public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Payments/Api.php on line 221

Warning: Undefined array key "wc-checkout-block-frontend" in /public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Payments/Api.php on line 221

Warning: Attempt to read property "deps" on null in /public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Payments/Api.php on line 221

Fatal error: Uncaught TypeError: array_diff(): Argument #1 ($array) must be of type array, null given in /public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Payments/Api.php:222 Stack trace: #0 /public_html/wp-content/plugins/woocommerce/packages/woocommerce-blocks/src/Payments/Api.php(222): array_diff(NULL, Array)...

Best regards,
Nenad

**Comment by tammullen** [comment]
Thanks @NenadObradovic 

To help us evaluate this it would will be great if you could share your current System Status Report. You can get it by navigating to the WooCommerce / Status section of your site. Once there, click on the Get system report button and then copy it by clicking on the Copy for support button. Then paste it here in a comment.

**Comment by NenadObradovic** [comment]
Hello @tammullen 

Sure, I think this is happened because of the PHP version, if you used PHP 8.x (like in my case) you will get a fatal error and otherwise, you will get only notices (I also tested with PHP 7.4).

`
### WordPress Environment ###

WordPress address (URL): http://framework.local
Site address (URL): http://framework.local
WC Version: 5.2.0
REST API Version: ✔ 5.2.0
WC Blocks Version: ✔ 4.7.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.1.5
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Win64) OpenSSL/1.1.1h PHP/8.0.0
PHP Version: 8.0.0
PHP Post Max Size: 40 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.73.0
OpenSSL/1.1.1h

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.17-MariaDB
Max Upload Size: 40 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.2.0
WC Database Prefix: wp_
Total Database Size: 9.26MB
Database Data Size: 7.11MB
Database Index Size: 2.15MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.17MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.30MB + Index: 0.22MB + Engine InnoDB
wp_posts: Data: 1.50MB + Index: 0.06MB + Engine InnoDB
wp_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_sbi_instagram_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.19MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 23
elementor_library: 1
nav_menu_item: 52
page: 35
portfolio-item: 8
post: 14
product: 18
product_variation: 7
revision: 44
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (8) ###

Debug Bar: by wordpressdotorg – 1.1.2
Elementor: by Elementor.com – 3.1.4
Log Deprecated Notices: by Andrew Nacin – 0.4.1
Monster Widget: by Automattic – 0.3
Theme Sniffer: by WPTRT – 1.1.2
Woocommerce Monster Widget: by Alispx – 1.0.2
WooCommerce: by Automattic – 5.2.0
WordPress Importer: by wordpressdotorg – 0.7

### Inactive Plugins (6) ###

Contact Form 7: by Takayuki Miyoshi – 5.4
Custom Twitter Feeds: by Smash Balloon – 1.8
Elementor Pro: by Elementor.com – 3.0.10
Qode Framework: by Qode Interactive – 1.1.5
Query Monitor: by John Blackbourn – 3.6.7
Test jQuery Updates: by The WordPress Team – 2.0.0

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 7
Oldest: 2021-04-07 10:44:53 +0000
Newest: 2021-04-13 11:00:17 +0000


### Status report information ###

Generated at: 2021-04-13 11:00:27 +00:00
`

Best regards,
Nenad

**Comment by tammullen** [comment]
Re-opening just until we have the corresponding Blocks PR in Core
