### ISSUE TITLE
Prices are rounded per line not per item

### ISSUE THREAD

**Issue by malinajirka** [woocommerce/woocommerce#29657]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When I add a product priced at 12.974 three times into the cart, the total is 38.92 (rounding happens per line not per item)
However, when I add three different products all priced at 12.974 the total is 38.91.

**Expected behavior**
When I add a product priced at 12.974 three times into the cart, I'd expect the total to be 38.91.

**Actual behavior**
When I add a product priced at 12.974 three times into the cart, the total is 38.92 (rounding happens per line not per item)

Steps to reproduce the bug:
1. Add a product to your store priced at 12.974
2. Add this product 3 times into the cart
3. Open the cart
4. Notice the total price is 38.92 instead of 38.91

#zen-3894170

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): https://site-for-woocommerce12a3fasdf45dfs6789.mystagingwebsite.com
Site address (URL): https://site-for-woocommerce12a3fasdf45dfs6789.mystagingwebsite.com
WC Version: 5.0.0
REST API Version: ✔ 5.0.0
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.9.0
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.3.27
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.75.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.21-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.0.0
WC Database Prefix: wp_
Total Database Size: 3.09MB
Database Data Size: 1.58MB
Database Index Size: 1.51MB
wp_woocommerce_sessions: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 0.31MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.13MB + Index: 0.13MB + Engine InnoDB
wp_posts: Data: 0.13MB + Index: 0.06MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 20
jetpack_migration: 2
jp_img_sitemap: 3
jp_sitemap: 3
jp_sitemap_master: 3
nav_menu_item: 4
oembed_cache: 2
page: 8
post: 3
product: 19
revision: 4
shop_order: 13
shop_order_refund: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (5) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Health Check & Troubleshooting: by The WordPress.org community – 1.4.5
Jetpack by WordPress.com: by Automattic – 9.6
Mailchimp for WooCommerce: by Mailchimp – 2.5.1
WooCommerce: by Automattic – 5.0.0 (update to version 5.2.0 is available)

### Inactive Plugins (7) ###

Gutenberg: by Gutenberg Team – 10.3.2
Robot Ninja Helper: by Prospress Inc. – 1.13.1
WooCommerce Payments: by Automattic – 2.0.0 (update to version 2.2.0 is available)
WooCommerce Payments Dev Tools: by Automattic –
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.1
WooCommerce Shipping & Tax: by Automattic – 1.25.11
WooCommerce Smooth Generator: by Automattic – 1.0.1

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (1) ###

Health Check Troubleshooting Mode: by  – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #4 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 2.3.5 (update to version 3.5.1 is available)
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 15
Oldest: 2021-03-15 18:18:41 +0000
Newest: 2021-04-13 13:52:34 +0000

````
</details>

**Comment by helgatheviking** [comment]
What's your setting for rounding taxes?

Settings > Taxes
"Round tax at subtotal level, instead of rounding per line"
![image](https://user-images.githubusercontent.com/507025/114902323-f3912200-9dd2-11eb-82cd-254073557b5c.png)

As far as I know, that's the only setting Woo has for controlling rounding. Which means it's not even an option if taxes are disabled. Perhaps Woo could use a separate setting for how to round.

**Comment by malinajirka** [comment]
I have the "Round tax at subtotal level, instead of rounding per line" disabled.
<img width="515" alt="Screenshot 2021-04-15 at 10 21 12" src="https://user-images.githubusercontent.com/2261188/114903791-618a1900-9dd4-11eb-8e73-c680b2a2c9a1.png">

I find it a bit unexpected that the default is "round per line" and not "round per item". I'm not sure if rounding per line is ever the desired behavior - with my very limited accounting knowledge, I'd say either "rounding at the subtotal level or per item" would be the desired options. Having said that I think that changing the behavior to existing customers might be worse than adding one more option into the settings. 🤷  Wdyt?

**Comment by EdithAllison** [comment]
From a customer perspective, 12.974 displays as 12.97, so the expected price for 3 items would be 12.97 x 3 = 38.91. Whilst I don't expect customers to complain over 0.01 it does look like an error as the actual full price of 12.974 isn't visible to the customer in the shop. I agree that rounding per item would be better. I'd see it as bug, so I'd expect the current setting to be changed from "per line" to "per item".

**Comment by rafsuntaskin** [comment]
@malinajirka @EdithAllison Have you tried setting the Decimal separator settings to `3`?
<img width="897" alt="Screen Shot 2021-07-01 at 8 58 47 PM" src="https://user-images.githubusercontent.com/7523321/124146004-23d18e00-daaf-11eb-8833-38d9e2d8d139.png">

If you want to use 3 decimal points for product pricing and then you should also display the same amount of decimals to your customers. This should avoid the error that you are facing.

**Comment by malinajirka** [comment]
> Have you tried setting the Number of decimals settings to 3?

This doesn't solve the core of this issue, it just moves it one decimal point away, right? It might work for some use cases but doesn't work for others. Furthermore, I'm a bit concerned that merchants might not want to increase a user-facing number of decimals because of a bug in the way we round prices, wdyt?

> Whilst I don't expect customers to complain over 0.01 

Imho it might cause troubles in accounting where every cent matters. Moreover, 0.01 is almost nothing in USD but might not be the case in other currencies. Wdyt?

**Comment by rrennick** [comment]
> When I add a product priced at 12.974 three times into the cart, the total is 38.92 (rounding happens per line not per item)
However, when I add three different products all priced at 12.974 the total is 38.91.

@malinajirka In both cases the prices are being rounded per line. In the second scenario each product is a separate line. I'll add the developer feedback label.

**Comment by barryhughes** [comment]
Thanks, all! 

It feels most appropriate to leave the current behavior in place (on discussing this, it's not obvious that the suggested change is what all merchants would expect—and, as I believe was already mentioned, changing the existing behavior has backward compatibility implications). However, there is definitely merit in *optionally* supporting the stated expectations that have been laid out here.

Marking as a future enhancement.

**Comment by AdsDawson** [comment]
Hi,

Is there any time frame when this "enhancement" will be rolled out as this is a bug to us and is causing huge problems for our customers - it especially shows up when you are syncing with accountancy software and causes errors across books everywhere.

**Comment by barryhughes** [comment]
We don't have a timeline for this just yet.

Thanks for leaving the comment, though, as knowing that others would benefit is potentially useful information that will help us to prioritize it. If others are similarly keen on seeing this change, do feel free to leave an emoji reaction (you don't necessarily have to leave a comment, unless you wish to add an observation about expectations or a use-case, etc).

**Comment by peterfabian** [comment]
We're writing documentation to explain this.

**Comment by vedanshujain** [comment]
> When I add a product priced at 12.974 three times into the cart, the total is 38.92 (rounding happens per line not per item)
However, when I add three different products all priced at 12.974 the total is 38.91.

@malinajirka We currently don't support rounding per line item because (among other reasons) it leads it to more in-accurate totals. If we round per item then we will carry forward some in-accuracy to tax and subtotal calculation. So let's say in your case, if this is taxed at 19%, then with unit-level rounding, users will see a total of 46.30, instead of 46.32 for three products (since individual gross price should be now 15.44).

Generally, these inaccuracies exist for line-level rounding as well, but it’s accepted and accommodated well by invoicing and accountancy softwares, as line-level rounding tends to be a bit more accurate than unit-level rounding.

That said, I am curious as to why you are entering prices of triple-digit precision but then displaying and expecting calculations for only 2 digits? Is this total because of a certain tax percentage, or is there some other use case?

I am closing it as `won't fix`, for now, i.e. we do not plan to add support for unit-level rounding for now. Although will re-open based on further comments and feedback.

**Comment by pwsonline** [comment]
We in Hungary for example have no decimals at all, but still have to handle them in net-gross calculations. 
I recently run into an issue where a customer ordered 10 pcs of a 1550 HUF gross item. It translates to 1220.4724409449 HUF net (27% VAT). 
If I round by item, 10 of these will cost 12200 net and 15494 gross.
If I round by line, 10 of these will cost 12204.72, rounded to 12205 net and 15500 gross. 

6 HUF difference. It's not much, but totally screws the books, as the invoicing software rounds per item. As it should be, because the user wants to pay 10 times the displayed item price, not 10 times plus some. 

So no, this topic should not be closed and the users should be able to decide, which rounding mode best suits them.
