### ISSUE TITLE
REST API: consider updating the API to support non-integer stock quantities

### ISSUE THREAD

**Issue by designsimply** [woocommerce/woocommerce#29664]
The WooCommerce Core API only supports stock quantities with `Int` or `nil` values. However, certain third-party extensions can enable decimal (non-integer) stock quantities and this caused the Products screen to break in the mobile apps.

#### Bug Description & Current Workaround

In the WooCommerce mobile apps, we found that if any product had a decimal stock quantity then none of the products would load (see https://github.com/woocommerce/woocommerce-ios/issues/3494 and https://github.com/woocommerce/woocommerce-android/issues/3611) and we temporarily worked around the problem by disabling the ability to edit quantity for inventory using decimal stock quantities (see https://github.com/woocommerce/woocommerce-ios/pull/3717 and https://github.com/woocommerce/woocommerce-android/pull/3782). It was found that we would need API changes to fully support editing decimal stock quantities in the app.

#### Core API vs Web Behavior

The Core API expects the [product `stock_quantity`](https://woocommerce.github.io/woocommerce-rest-api-docs/#product-properties) property to be an integer. If we try to send a decimal stock quantity, we receive a `rest_invalid_param` error from the API. Core web handles decimal quantity input differently. Instead of rejecting non-integer stock quantities outright, it [accepts both integers and floats](https://github.com/woocommerce/woocommerce/blob/0f4ccb836ed55031d8a0b7a7476b906461c2d2c4/includes/wc-formatting-functions.php#L470) and [uses a filter to return the integer value](https://github.com/woocommerce/woocommerce/blob/b36a06ca080567bc6c863260267e62f65a2200d5/includes/wc-core-functions.php#L42) of the input.

#### Ideal Solution

The optimal solution would be to make it possible to send decimal stock quantities back to core, so all stock levels are editable in a consistent way. It's worth noting that such a change could break other plugins and such a tradeoff  should be discussed/considered.

#### Alternatives Considered

WooCommerce mobile developers implemented a workaround to make a product or variation's inventory settings read-only if it has decimal stock quantities, since the API currently doesn't accept decimal stock quantities. Other settings (and all settings for products or variations without decimal stock quantities) can still be edited as usual.

#### Additional context

<sup>(internal reference: p91TBi-4iF-p2)</sup>

cc @rachelmcr @hafizrahman @shiki (since I paraphrased you from your blog posts and PRs in order to create this issue and I wanted to make sure you are credited, thank you for the past discussions and for working to solve this problem in our apps!)

**Comment by tammullen** [comment]
Thanks @designsimply !

Can you post this as a comment in the other issue you found  https://github.com/woocommerce/woocommerce/issues/27375 as I think this recent context would be very helpful. I will also label it for more attention.

Closing for the duplicate
