### ISSUE TITLE
Incorrect "Your theme contains outdated copies of some WooCommerce template files" message

### ISSUE THREAD

**Issue by kb6673** [woocommerce/woocommerce#29668]
The "Your theme contains outdated copies of some WooCommerce template files" message appears to be showing incorrectly.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

We have a custom theme that overwrites `woocommerce/checkout/review-order.php`

It is showing 

> woocommerce/checkout/review-order.php version 3.8.0 is out of date. The core version is 5.2.0, 

Looking at https://github.com/woocommerce/woocommerce/blob/master/templates/checkout/review-order.php it shows `* @version 3.8.0`

The `The core version is 5.2.0, ` is coincidently the same version of WooCommerce we have

**Expected behavior**
I'd expect no message to be shown as the theme override version matches the latest core version

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Override `woocommerce/checkout/review-order.php` with the latest version
2. Click on WooCommerce -> Status
3. Scroll down to Templates

**Screenshots**
![image](https://user-images.githubusercontent.com/1001484/114703749-98512800-9d1d-11eb-8454-0708dadfaf67.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment]
Hi @kb6673 

> Looking at https://github.com/woocommerce/woocommerce/blob/master/templates/checkout/review-order.php it shows * @version 3.8.0

The latest version is actually here
https://github.com/woocommerce/woocommerce/blob/trunk/templates/checkout/review-order.php

Can you try again with that version?

**Comment by isaklafleur** [comment]
I verified what code has been updated and I can only see this part.

5.2.0
`<?php echo wp_kses_post(apply_filters('woocommerce_cart_item_name', $_product->get_name(), $cart_item, $cart_item_key)) . '&nbsp;';`

`<?php echo wp_kses_post(apply_filters('woocommerce_cart_item_name', $_product->get_name(), $cart_item, $cart_item_key)) . '&nbsp;'; ?>`

3.8.0
`<?php echo apply_filters('woocommerce_cart_item_name', $_product->get_name(), $cart_item, $cart_item_key) . '&nbsp;'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped 
`
and 

<?php echo apply_filters('woocommerce_cart_item_name', $_product->get_name(), $cart_item, $cart_item_key) . '&nbsp;'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped 
?>

**Comment by tammullen** [comment]
Thanks @isaklafleur, just to confirm does this solve your issue and there doesn't appear to be a bug?

**Comment by kb6673** [comment]
This looks like my error. My apologises - I was looking in the wrong branch.
