### ISSUE TITLE
Implement describe.each where appropriate

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce#29678]
There are several tests that repeat the same test steps with different data (eg. order search). We should update these tests to use `describe.each()` to reduce the code size and ensure consistency among each set of tests.

**Comment by lsinger** [comment]
To be estimated once Rodel has looked at how many tests will be affected by this.

**Comment by rodelgc** [comment]
These are the tests where we can implement `describe.each` and `it.each`:

1. tests/e2e/core-tests/specs/activate-and-setup/onboarding-tasklist.test.js [3]
    - can reset to default settings
2. tests/e2e/core-tests/specs/keep/onboarding-tasklist.test.js [3]
    - can reset to default settings
3. tests/e2e/core-tests/specs/merchant/wp-admin-analytics-page-loads.test.js [11]
4. tests/e2e/core-tests/specs/merchant/wp-admin-order-status-filters.test.js [8]
5. tests/e2e/core-tests/specs/merchant/wp-admin-product-new.test.js [2]
6. tests/e2e/core-tests/specs/shopper/front-end-cart-coupons.test.js [3]
    - allows cart to apply fixed cart coupon
    - allows cart to apply percentage coupon
    - allows cart to apply fixed product coupon
7. tests/e2e/core-tests/specs/shopper/front-end-checkout-coupons.test.js [3]
    - allows checkout to apply fixed cart coupon
    - allows checkout to apply percentage coupon
    - allows checkout to apply fixed product coupon
8. tests/e2e/core-tests/specs/shopper/front-end-my-account.test.js [4]
    - allows customer to see orders
    - allows customer to see downloads
    - allows customer to see addresses
    - allows customer to see account details

Setting the estimate to 2 points.

**Comment by rodelgc** [comment]
Done implementing `each()` on the tests I listed above. PR is ready for review.
