### ISSUE TITLE
Payment method not saving Georgian language characters.

### ISSUE THREAD

**Issue by givik** [woocommerce/woocommerce#29670]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
I want to set the Title and Description of the payment method in the Georgian language but it does not work.

**Expected behavior**
To change and save the Title in the Georgian language.

**Actual behavior**
After saving changes it is showing these characters. (**áá¤**)

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to Woocommerce > Settings > Payments
2. Click on Direct bank transfer or (any payment method). 
3. Enter in Title Georgian or Russian characters
4. Hit the save.

**Screenshots**
![Screenshot 2021-04-13 at 19 56 44](https://user-images.githubusercontent.com/2458760/114709671-f2fa7c00-9d3d-11eb-974a-60611df644d3.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>

`
### WordPress Environment ###

WordPress address (URL): https://example.ge
Site address (URL): https://example.ge
WC Version: 5.2.0
REST API Version: ✔ 5.2.0
WC Blocks Version: ✔ 4.7.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.1.5
Log Directory Writable: ✔
WP Version: 5.7
WP Multisite: –
WP Memory Limit: 256 მბაიტი
WP Debug Mode: –
WP Cron: ✔
Language: ka_GE
External object cache: –

### Server Environment ###

Server Info: nginx/1.18.0
PHP Version: 7.4.3
PHP Post Max Size: 64 მბაიტი
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 8.0.23-0ubuntu0.20.04.1
Max Upload Size: 64 მბაიტი
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.2.0
WC Database Prefix: wp_
Total Database Size: 24.94MB
Database Data Size: 22.89MB
Database Index Size: 2.05MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.09MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_dokan_announcement: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_orders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_dokan_refund: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_vendor_balance: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_withdraw: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mstore_checkout: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 18.23MB + Index: 0.14MB + Engine InnoDB
wp_postmeta: Data: 0.44MB + Index: 0.23MB + Engine InnoDB
wp_posts: Data: 1.52MB + Index: 0.06MB + Engine InnoDB
wp_revslider_css: Data: 0.13MB + Index: 0.00MB + Engine InnoDB
wp_revslider_css_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_sliders_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_revslider_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_say_what_strings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcfm_daily_analysis: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcfm_detailed_analysis: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_enquiries: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_enquiries_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_enquiries_response: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_enquiries_response_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_fbc_chat_rows: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_fbc_chat_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcfm_fbc_chat_visitors: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_fbc_offline_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_following_followers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_orders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcfm_marketplace_orders_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_product_multivendor: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcfm_marketplace_refund_request: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_refund_request_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_reverse_withdrawal: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_reverse_withdrawal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_review_rating_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_reviews: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_reviews_response: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_reviews_response_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_shipping_zone_locations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_store_taxonomies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_vendor_ledger: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_withdraw_request: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_marketplace_withdraw_request_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_membership_subscription: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcfm_messages: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_messages_modifier: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_messages_stat: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_support: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_support_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_support_response: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcfm_support_response_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woodmart_wishlist_products: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woodmart_wishlists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.13MB + Index: 0.08MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.05MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

attachment: 116
cms_block: 5
elementor_library: 1
mc4wp-form: 1
nav_menu_item: 24
page: 17
post: 1
product: 17
product_variation: 8
revision: 116
rvp: 1
shop_order: 8
woodmart_sidebar: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 5.2.0

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: GEL (₾)
Currency Position: right
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #11 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.5.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 136
Oldest: 2021-03-24 18:37:18 +0400
Newest: 2021-04-14 14:37:26 +0400

Pending: 5
Oldest: 2021-04-15 08:41:06 +0400
Newest: 2021-04-16 15:30:00 +0400

### Status report information ###

Generated at: 2021-04-14 16:31:52 +04:00
`

</details>

**Comment by tammullen** [comment]
Hi @givik 

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

I entered the following string of Georgian characters as well as other charsets and unicode characters.

`ამ სფეროს ტესტირება Lorem ipsum dolor sit amet, Римский император Константин I Великий, 北京位於華北平原的西北边缘 Iñtërnâtiônàlizætiøn☃💪`

They saved as expected

![Screenshot 2021-04-18 at 11 13 42](https://user-images.githubusercontent.com/24649833/115142024-5d116a80-a037-11eb-9d75-dcf6ed2a7475.png)

Please provide us with more details about the issue which may help us to evaluate it further.

**Comment by givik** [comment]
Hi @tammullen,

I don't know what happened, but it worked a while ago. You can also see this in the main settings.

[https://youtu.be/pkak-EFceUk](https://youtu.be/pkak-EFceUk)

**Comment by givik** [comment]
any news?

**Comment by givik** [comment]
Finally, I have fixed the bug. After removing **php7.4-mbbstring** extension everything works fine.
