### ISSUE TITLE
Existing download permissions get lost after updating products via CSV import

### ISSUE THREAD

**Issue by guicmazeredo** [woocommerce/woocommerce#29686]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
After updating a downloadable product via CSV import as per these instructions, customers that had already purchased the existing downloadable product lose the download permission. 

**Expected behavior**
I'd expect existing download permissions to remain active. 

**Actual behavior**
The download permissions get removed from past orders and from **My Account > Downloads** on the customer view. 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create a `downloadable` and `virtual` product and set up the basic things (name, price, SKU)
2. Place an order with this product. Notice that the download permission will be granted and the product will appear under **My Account > Downloads**
3. Export the product using the built-in export tool in **Products > Export**. 
4. Import the exported CSV via **Products > Import** and make sure to click **Update existing products** as [per these instructions](https://docs.woocommerce.com/document/product-csv-importer-exporter/#section-6). 
5. Notice the product will be removed from the download permissions section in the order created in step 2 and will not show up in **My Account > Downloads** anymore. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by zhongruige** [comment]
Hi @guicmazeredo,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end.

* I created a downloadable product:

<img width="1062" alt="Screen Shot 2021-04-14 at 4 23 16 PM" src="https://user-images.githubusercontent.com/71906536/114787900-bdee2980-9d3d-11eb-9478-50391b921c82.png">

* I purchased the product as a test customer and verified it showed in the `My account > Downloads` section
* I exported all of the products and imported them back with `Update existing products` selected
* I reloaded the page in `My account > Downloads` and noted that no downloads could now be found:

<img width="838" alt="Screen Shot 2021-04-14 at 4 24 34 PM" src="https://user-images.githubusercontent.com/71906536/114787974-ed9d3180-9d3d-11eb-8a53-affb2149cecf.png">

We’re going to solve this bug as soon as possible. Stay tuned for updates.
