### ISSUE TITLE
Putting the schema file in the plugin directory will improve security and performance

### ISSUE THREAD

**Issue by ACronwerk** [woocommerce/woocommerce#29689]
WooCommerce uses an insecure protocol to access the schema file dozens of times at http://json-schema.org/draft-04/schema#. This badly slows down the site and makes it vulnerable to a man-in-the-middle attack.
Maybe it’s better to put the schema file in the plugin directory?
I did this on my site by changing the WooCommerce code, and the product pages started opening much faster.
And so does Rank Math SEO with it's schema and works quickly.

**Comment by vedanshujain** [comment]
@ACronwerk would you be open to send in a PR with the changes you did? We use that defination to describe the JSON structure we adhere to in our APIs, and I was under the impression that we don't actually ever call that file. If we are accessing that file and slowing down the site because of it, then yeah we really need to  store it locally.

**Comment by ACronwerk** [comment]
Hi!

In 92 (!) woocommerce files I changed the address 
http://json-schema.org/draft-04/schema# 
to the address 
/wp-content/uploads/api/schema.

I changed them in Debian application regexxer. I found all theese files
with Mate Search tool.

I have downloaded file schema from 
http://json-schema.org/draft-04/schema# 
and put it in 
/wp-content/uploads/api/schema.

Foe example, in class-wc-rest-shipping-zones-v2-controller.php:

public function get_item_schema() {
		$schema = array(
			'$schema'    => '
http://json-schema.org/draft-04/schema#',
			'title'      => 'shipping_zone',
			'type'       => 'object',
			'properties' => array(
				'id'    => array(
					'description' => __( 'Unique
identifier for the resource.', 'woocommerce' ),
					'type'        => 'integer',
					'context'     => array( 'view',
'edit' ),
					'readonly'    => true,
				),
				'name'  => array(
					'description' => __( 'Shipping
zone name.', 'woocommerce' ),
					'type'        => 'string',
					'context'     => array( 'view',
'edit' ),
					'arg_options' => array(
						'sanitize_callback' =>
'sanitize_text_field',
					),
				),
				'order' => array(
					'description' => __( 'Shipping
zone order.', 'woocommerce' ),
					'type'        => 'integer',
					'context'     => array( 'view',
'edit' ),
				),
			),
		);

		return $this->add_additional_fields_schema( $schema );
	}
}

Regards

**Comment by ACronwerk** [comment]
> @ACronwerk would you be open to send in a PR with the changes you did? We use that defination to describe the JSON structure we adhere to in our APIs, and I was under the impression that we don't actually ever call that file. If we are accessing that file and slowing down the site because of it, then yeah we really need to store it locally.

May be I am wrong, I am not a programmer. But my site greatly accelerated after my changes.
To make PR for 92 files is too time-consuming. I gave 1 example and a method for finding all the other files. (see below)

**Comment by vedanshujain** [comment]
> To make PR for 92 files is too time-consuming

@ACronwerk no worries and thanks for your help, we are looking into this
