### ISSUE TITLE
[GlobalStep] "Close icon/Checkbox" is non-functional for "Filter Products By Attribute" widget with "List" display style.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#29695]
## Bug Description:
"Close icon/Checkbox" is non-functional for "Filter Products By Attribute" widget with "List" display style.

## Environment:
Woocommerce Version: WooCommerce 5.2.2 and 5.1
WordPress version: (v5.7)

**PC:**
Windows 10, Mac 10.14.6
Chrome(Version 89.0.4389.90) 
Firefox(Version 87.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins 
1. Complete OBW setup
1. Go to Products->Add New and add multiple attributes as well
1. Add "Filter Product by Attribute" widget from Appearance->Theme->Customize->Widgets".
1. Set the "Display Type" as List and Query can be set "And/OR". 
1. Click on "Save" button and "Publish" button.
1. Go to "Shop" at front end.
1. Try to uncheck/click on close icon or checkbox to add/remove the attribute.
1. Observe that "Close icon/Checkbox" is non-functional for "Filter Products By Attribute" Widget.

## Actual Result:
"Close icon/Checkbox" is non-functional for "Filter Products By Attribute" widget with "List" display style.

## Expected Result:
"Close icon/Checkbox" should be functional for "Filter Products By Attribute" widget.

## Video:

https://user-images.githubusercontent.com/41110392/114889812-113ca680-9e28-11eb-8167-ae614f79c1d4.mp4

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by tammullen** [comment]
Hi @gglobalstep 

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/27801. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
