### ISSUE TITLE
The setup script for unit testing fails to install WordPress libraries if Subversion is not pre-installed

### ISSUE THREAD

**Issue by loranallensmith** [woocommerce/woocommerce#29705]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
If you run the [`install.sh`](https://github.com/woocommerce/woocommerce/blob/d79e86932be840e135113f8e2cbb3f6a9e60bab2/tests/bin/install.sh) script for setting up unit testing without having Subversion installed, the script will fail to properly set up the environment on subsequent runs.

**Expected behavior**
When I run the setup script in my local environment, if I don't have all of the necessary prerequisites installed, it would be great to have it bail out and tell me what I'm missing.  Once I have installed the missing software, I would run the script again and the script would complete the setup.  I think it would also be worth mentioning in the setup docs somewhere that Subversion is a requirement for setting up the unit test suite.

**Actual behavior**
When I run the setup script, if I don't have Subversion installed, the script will error out with the standard `command not found: svn` output.  If I install Subversion and run the setup script again, the `$WP_TESTS_DIR/includes` and `$WP_TESTS_DIR/data` directories never get checked out from subversion repository on wordpress.org.  The setup script completes, but because the necessary libraries aren't present, the unit tests won't run.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**

1. Uninstall Subversion (if you have it installed).
2. Clone a fresh copy of this repository to your machine and set it up according to [the instructions in the wiki](https://github.com/woocommerce/woocommerce/wiki/How-to-set-up-WooCommerce-development-environment).
3. Follow the [setup instructions](https://github.com/woocommerce/woocommerce/tree/trunk/tests#initial-setup) listed in the unit testing `README.md`.
4. The script should fail with a `command not found: svn` message.
5. Install Subversion (and load a fresh shell session if necessary).
6. Run the setup script on your cloned copy of the repository again.
7. Follow the instructions for [running tests](https://github.com/woocommerce/woocommerce/tree/trunk/tests#running-tests) in the unit testing `README.md`

The script's `wordpress-tests-lib/` directory should be missing the `data/` and `includes/` directories.

**Screenshots**

Here's a snippet of the terminal output that I receive when I run the script without subversion:
```bash
[woocommerce] ./tests/bin/install.sh woocommerce_test_db wp wp vvv.test
+ install_wp
+ '[' -d /var/folders/66/2md_p6qn0ms9h099gdw1l4kc0000gn/T/wordpress/ ']'
+ return
+ install_test_suite
++ uname -s
+ [[ Darwin == \D\a\r\w\i\n ]]
+ local 'ioption=-i .bak'
+ '[' '!' -d /var/folders/66/2md_p6qn0ms9h099gdw1l4kc0000gn/T/wordpress-tests-lib ']'
+ mkdir -p /var/folders/66/2md_p6qn0ms9h099gdw1l4kc0000gn/T/wordpress-tests-lib
+ svn co --quiet https://develop.svn.wordpress.org/tags/5.7.1/tests/phpunit/includes/ /var/folders/66/2md_p6qn0ms9h099gdw1l4kc0000gn/T/wordpress-tests-lib/includes
./tests/bin/install.sh: line 108: svn: command not found
```

Here's a link to the conditional that seems to be causing the trouble for me:  https://github.com/woocommerce/woocommerce/blob/d79e86932be840e135113f8e2cbb3f6a9e60bab2/tests/bin/install.sh#L104-L110

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

This doesn't seem to be tied to a particular WP version or environment.  I'm running PHP 7.4.16 in my shell, in case that's helpful for troubleshooting or reproducing the issue. :smiley:

**Comment by barryhughes** [comment]
Sounds like a reasonable and straightforward enhancement—thank you :-)

**Comment by geektzu** [comment]
The install script has many temp files created. Any issue will require removing all the temp files created under /tmp/. Otherwise, the installation script cannot finish running. 

I also encountered another issue than subversion. MySQL for php also needs to be installed before the unit tests can be run. In Ubuntu, sudo apt install php-mysql solved the issue. With mysql for php installed, there is an error when running unit tests:

 vendor/bin/phpunit
PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /tmp/wordpress/wp-includes/wp-db.php:1685
Stack trace:
#0 /tmp/wordpress/wp-includes/wp-db.php(632): wpdb->db_connect()
#1 /tmp/wordpress/wp-includes/load.php(545): wpdb->__construct()

**Comment by Franklin110120** [comment]
@geektzu Thank you for providing the solution for that error. That solution really helps. I also encountered an error running vendor/bin/phpunit:

Fatal error: require_once(): Failed opening required '/home/ubuntu/woocommerce/plugins/woocommerce//includes/react-admin/feature-config.php' (include_path='.:/usr/share/php') in /home/ubuntu/woocommerce/plugins/woocommerce/src/Internal/Admin/FeaturePlugin.php on line 76

I should have installed all the prerequisites and also svn as this issue suggested.  I haven't found any solution online.
