### ISSUE TITLE
New filter to permanently delete tax classes

### ISSUE THREAD

**Issue by HiroHopper** [woocommerce/woocommerce#29708]
Dear Woocommerce professionals,

after every major Woocommerce update the usual tax classes “Zero Rate”, “Reduced Rate” etc. are set again in admin backend. So far I have always removed them manually in the settings. It would be great if you could add a feature or filter to permanently remove the unwanted tax classes.

**Steps to reproduce the "problem":**

1. install an older version of woocommerce
2. delete all additional tax classes
3. perform an update of woocommerce
4. look at the tax class settings

I already asked in the wordpress woocommerce support forum for a solution and was referred here by a moderator.

Below you can see a picture that illustrates the situation. The tax classes marked in yellow should not be found here.

![woocommerce](https://user-images.githubusercontent.com/82687941/115098593-23563c00-9f31-11eb-9b18-a9d31549478f.jpg)

Kind regards and thank you for the support

**Comment by DavidAnderson684** [comment]
I wouldn't recommend removing the 'zero rate' class. Some extensions use it as the way of removing taxes (e.g. VAT exemption). Why is its existence considered a problem? ~20 bytes wasted compared to a theoretical perfect efficiency in the database? Something else?

**Comment by HiroHopper** [comment]
Thank you for your feedback. I understand your point. I set up the online store for a bookstore and we have to pay taxes on every kind of products. So zero tax or using such plugin is out of question. Also, I think of the employees who have to add the new products to the online store. That a removal of the tax class can lead to problems, I can understand. But a filter for tax classes of the dropdown field in the view "Add new product" would help these technically less talented employees by hiding the unused tax classes.
Thank you for your input and I hope you will continue to consider my suggestion at least for tax classes like "Reduced Price" and "Virtual Rate" which not everyone needs to use.

Best regards

**Comment by juliaamosova** [comment]
Hi @HiroHopper,

Thank you for highlighting the issue! It feels odd to me that previously deleted default tax calsses get restored after the WooCommerce update. I tested this by updating from WooCommerce 5.2 RC1 to 5.3 beta and could reproduce it:

https://user-images.githubusercontent.com/19143190/115624291-6e24da80-a2c8-11eb-96c0-c47d1c3b8826.mov

I don't know if there is a reason behind it in Core or if this is a bug. I also can't make the call on adding a new filter myself here. 

This issue requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by vedanshujain** [comment]
Agreed here that if we have deleted a tax class, it should not pop up again. Seems like this is happening in `create_options` method in file `class-wc-install.php`. Ideally, the calls for creating those classes should be behind an `if` condition with `is_new_install` method.

**Comment by geektzu** [comment]
Hi @vedanshujain ,

   I attempted to fix the issue as per your suggestion and tested it on my own WP setup. Below is a screen record by uploading the fixed 5.3.0 plugin by replacing an old version with no Zero or Reduced tax class rate being re-introduced.

   https://drive.google.com/file/d/1L9G4aXmtDo4PM8ueUJbeDr-4nCHuOHIB/view
   
   Would like to check what is the best way to submit a PL for the fix. I created a branch "fix/29708" locally and realized I have no write access.  Shall I follow GH Desktop's suggestion to create a fork instead?

    
![image](https://user-images.githubusercontent.com/7579242/118564972-75ef7600-b7c5-11eb-9839-cc5dbabd6d85.png)

**Comment by vedanshujain** [comment]
@geektzu thanks for working on this issue. Yes please create a PR via a fork.

**Comment by geektzu** [comment]
@vedanshujain Thank you Vendan Shu. Forked and created a PR for reviewing: https://github.com/woocommerce/woocommerce/pull/29938

**Comment by vedanshujain** [comment]
Done in #29938
