### ISSUE TITLE
WooCommerce's shop/store translatable strings/pages/condition name inconsistencies

### ISSUE THREAD

**Issue by ninetyninew** [woocommerce/woocommerce#29713]
AFAIK WooCommerce always uses a shop page at the URL: /shop and it has a conditional named is_shop().

At one point I assumed the URL /shop was being created on installation based off the site language so I figured mine was /shop because the WP language settings are English (UK) - but it appears this is not the case and every store gets a /shop URL - correct me if wrong?

However outside the shop page and looking through the translatable strings, WooCommerce generally refers to "store" a lot more than "shop". Therefore there seems to be an inconsistency here, so just to raise a few questions here (and I'm not saying any of the below is correct but just wanted others opinions on this)

For consistency should:

- The store/shop page be created as /store by default - as WooCommerce refers to a store more than shop
- The is_shop() conditional be renamed to is_store() - with some way to ensure is_shop() still works

Or

- All WooCommerce 'store' based strings updated to 'shop' - so consistent with the default 'shop' page and conditionals

Also:

- When WooCommerce is installed should the shop URL be created as specified in the translations? (appreciate a language might not have this translation)

Or maybe I am just really really over thinking this?!

**Comment by juliaamosova** [comment]
Hi @ninetyninew,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by vedanshujain** [comment]
@ninetyninew thanks for the suggestion. However, I don't think that we can make this change, irrespective of whether it's a bit more consistent or not:
1. Many extensions and themes may be relying on `/shop` page being present by default. Changing this to store may break those themes, so we cannot do it unless for a very strong reason.
2. We have [options to configure whatever page you want into a shop page](https://docs.woocommerce.com/document/woocommerce-pages/), so change like this will become disruptive for very less benefits.

I am closing this issue marking as won't fix, but feel free to write back if you have more questions.
