### ISSUE TITLE
Failed to apply coupons when the email field does not exist

### ISSUE THREAD

**Issue by hamidrezayazdani** [woocommerce/woocommerce#29724]
Hi folk,

There is a problem applying coupons. I used the following snippet to disable the email address in the checkout:

```
add_filter( 'woocommerce_checkout_fields', 'ywp_override_checkout_fields' );
function ywp_override_checkout_fields( $fields ) {
	unset( $fields['billing']['billing_company'] );
	unset( $fields['shipping']['shipping_company'] );
	unset( $fields['billing']['billing_address_2'] );
	unset( $fields['shipping']['shipping_address_2'] );
	unset( $fields['billing']['billing_email'] );
	unset( $fields['shipping']['shipping_email'] );

	unset($fields['billing']['billing_postcode']['validate']);
	unset($fields['shipping']['shipping_postcode']['validate']);

	return $fields;
}

```

In the above code, the line `unset( $fields['billing']['billing_email'] );`  remove the email field in the checkout, now when I want to complete the payment, the following error is displayed if I have not used this coupon at all before:

> you have used this coupon XYZ in another transaction during this checkout, and coupon usage limit is reached. Please remove the coupon and try again.

**WHY?!**
I checked the error log and found this:

> [20-Apr-2021 12:31:46 UTC] PHP Notice:  Undefined index: billing_email in /home/mydomain/public_html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php on line 369

The code for this section is:
```
			$order->hold_applied_coupons( $data['billing_email'] );
			$order->set_created_via( 'checkout' );
			$order->set_cart_hash( $cart_hash );
			$order->set_customer_id( apply_filters( 'woocommerce_checkout_customer_id', get_current_user_id() ) );
			$order->set_currency( get_woocommerce_currency() );
			$order->set_prices_include_tax( 'yes' === get_option( 'woocommerce_prices_include_tax' ) );
			$order->set_customer_ip_address( WC_Geolocation::get_ip_address() );
			$order->set_customer_user_agent( wc_get_user_agent() );
			$order->set_customer_note( isset( $data['order_comments'] ) ? $data['order_comments'] : '' );
			$order->set_payment_method( isset( $available_gateways[ $data['payment_method'] ] ) ? $available_gateways[ $data['payment_method'] ] : $data['payment_method'] );
			$this->set_data_from_cart( $order );
```

Well, obviously the email field is not available and the process of checking the coupons is an error. We have two problems here:

1.  The output of the following function will not be zero and as a result, an error will occur:

**woocommerce/includes/abstracts/abstract-wc-order.php LINE: 1069**
```
	private function hold_coupon_for_users( $coupon, $user_ids_and_emails, $user_alias ) {
		$result = $coupon->get_data_store()->check_and_hold_coupon_for_user( $coupon, $user_ids_and_emails, $user_alias );
		if ( false === $result ) {
			// translators: Actual coupon code.
			throw new Exception( sprintf( __( 'An unexpected error happened while applying the Coupon %s.', 'woocommerce' ), esc_html( $coupon->get_code() ) ) );
		} elseif ( 0 === $result ) {
			// translators: Actual coupon code.
			throw new Exception( sprintf( __( 'You have used this coupon %s in another transaction during this checkout, and coupon usage limit is reached. Please remove the coupon and try again.', 'woocommerce' ), esc_html( $coupon->get_code() ) ) );
		}
		return $result;
	}
```

2. The error message that is displayed, no filter is applied to it so that the `woocommerce_coupon_message` filter affects it

**WordPress Environment**
Wordpress version: 5.7.1
WooCommerce version: 5.2.2

**Comment by juliaamosova** [comment]
Hi @hamidrezayazdani,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by vedanshujain** [comment]
@hamidrezayazdani This check does rely on the email being present, but will only be active if a [per-user coupon usage limit](https://docs.woocommerce.com/document/coupon-management/) is also set. You can still set the global usage limit, but not the per-user usage limit. Can you try disabling it and see if the issue persists? I think you will still see the PHP notice, but checkout should work.

Also, billing_email is actually considered a core field and it's not advised to disable it because many extensions, the payment gateway will assume it to be present.
