### ISSUE TITLE
Anchor link to reviews below product title is broken

### ISSUE THREAD

**Issue by andrejcremoznik** [woocommerce/woocommerce#29736]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

In `woocommerce/templates/single-product/rating.php:38` is a link to `#reviews`.

The correct anchor is `#tab-reviews` as per `woocommerce/templates/single-product/tabs/tabs.php:44`

**Expected behavior**

Click on `(X customer reviews)` scrolls the page down to reviews.

**Actual behavior**

Click on `(X customer reviews)` does nothing because the id is wrong.

**Steps to reproduce the bug**

1. Go to a single product that has at least 1 review
2. Click link

![Screenshot_20210422_142726](https://user-images.githubusercontent.com/761287/115713967-e21dbc00-a376-11eb-888d-f8d759e40086.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
  **Probably. Any theme that doesn't override the problematic WC files is affected.**
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

WooCommerce 5.2.2

**Comment by zhongruige** [comment]
Hi @andrejcremoznik,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

I tested the this on both Storefront and Twenty Twenty-one themes, running WooCommerce 5.2.2 and WordPress 5.7.1, and in both cases the anchor link works as expected.

**Twenty Twenty-one**

https://user-images.githubusercontent.com/71906536/116151009-4f945a00-a6a1-11eb-8d68-feab7451e457.mov

**Storefront**

https://user-images.githubusercontent.com/71906536/116151043-5ae78580-a6a1-11eb-85af-cecfda9fca46.mov

Can you test if you still see this issue with the one of the default themes ([Twenty Twenty-one](https://wordpress.org/themes/twentytwentyone/) or [Storefront](https://woocommerce.com/storefront/), for example) and let us know if you're still seeing this issue, and if so, provide the full system report? You can get it by navigating to the `WooCommerce / Status` section of your site. Once there, click on the `Get system report` button and then copy it by clicking on the `Copy for support` button. Then paste it here in a comment.

**Comment by andrejcremoznik** [comment]
Never mind, I've found some unexpected interfering JS. Sorry, closing.

**Comment by zhongruige** [comment]
> Never mind, I've found some unexpected interfering JS. Sorry, closing.

No worries at all! Glad you were able to find the issue, and thank you for following up!
