### ISSUE TITLE
[GlobalStep] The refund label gets replaced by "Reason for Refund" when the refunded email is sent to the respective customer.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#29742]
## Bug Description:
The refund label gets replaced by "Reason for Refund" when the refunded email is sent to the respective customer.

## Environment:
Woocommerce Version : WooCommerce 5.2.2 and 5.3.0 Beta
WordPress version: (v5.7)

**PC:**
Windows 10, Mac 10.14.6
Chrome(Version 89.0.4389.90) 
Firefox(Version 87.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins 
1. Complete the onboarding setup wizard setup 
1. Complete "Get ready to start selling" section on WooCommerce->Home Page
1. Go to frontend and add some products to cart from shop by clicking on "Add to Cart" button
1. Click on "View Cart" button say that you have added "t-shirt"
1. Click on "Proceed to Checkout" 
1. Click on "Place Order" after entering the address and selecting a payment method 
1. Go to backend, WooCommerce->Orders and "Edit" the order you had just placed (t-shirt)
1. Click on "Refund" button
1. Select the quantity and refund amount will be updated, mention the "Reason for Refund" say bad quality or size dosen't fit
1. Click on "Refund Manually" button
1. Click on "OK" button when "Are you sure?" popup is displayed
1. Click on "Update" button, Status changes from processing to refunded 
1. Go to email you had set while purchasing the order, refund notification mail will be recieved 
1. Open the mail and Note that instead of refund label beside the refund amount , reason has been mentioned
1. Observe that refund label gets replaced by "Reason for Refund" when the refunded email is sent to the respective customer.

## Actual Result:
The refund label gets replaced by "Reason for Refund" when the refunded email is sent to the respective customer.

## Expected Result:
The refund label should not get replaced by "Reason for Refund" when the refunded email is sent to the respective customer.
The reason should be displayed separately below the refund amount

## ScreenShot:
![#29742](https://user-images.githubusercontent.com/41110392/115746723-309c7c00-a3b2-11eb-9cb5-974b37e3bfa6.png)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @gglobalstep,

Thank you for reporting the issue! 

I agree that it is strange that we are replacing the `Refund` label with the refund reason. Instead, the formatting should be something along the lines of:
```
Refund:                                     |    Refund amount
Refund reason (under the `Refund` label)    | 
```

Since this issue is not specific to WooCommerce 5.3 and happens in previous versions of WooCommerce, I am not going to assign a milestone to it. 

I also think that it has a `low` priority compared to other issues reported. We can bump it if we'd get more reports.

**Comment by rrennick** [comment]
This doesn't occur in WC 7.9-dev
