### ISSUE TITLE
Need the equivalent of woocommerce_applied_coupon when applying a coupon to an order

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#29745]
The cart class has a `woocommerce_applied_coupon` action hook that is fired when a coupon is added to the cart. There isn't anything like that (as far as I can tell) for detecting when a coupon is added to an order.

**Is your feature request related to a problem? Please describe.**
My free gift coupons plugin adds a free product to the cart when a coupon is applied. When a free gift type coupon is added to the order, it's not possible to detect that and add the free gift to the order.

**Describe the solution you'd like**
there's explicit handling of the core coupon types [in the WC_Discounts class](https://github.com/woocommerce/woocommerce/blob/b19500728b4b292562afb65eb3a0c0f50d5859de/includes/class-wc-discounts.php#L264-L278) but there's no way to handle the addition of a custom coupon type.

**Describe alternatives you've considered**
Perhaps an action hook in the discount's `apply_coupon()` method? something like:

```
do_action( 'woocommerce_applied_coupon_discount', $coupon, $this );
```

just prior to [returning `true`](https://github.com/woocommerce/woocommerce/blob/b19500728b4b292562afb65eb3a0c0f50d5859de/includes/class-wc-discounts.php#L280)

**Comment by juliaamosova** [comment]
Hi @helgatheviking,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by vedanshujain** [comment]
@helgatheviking I am assuming you are talking about when applying coupons to order from the backend? If correct, then for this use case, filter `woocommerce_order_recalculate_coupons_coupon_object` can be used. This is called everytime a new coupon is added to the order, and it also passed `$order` object to the filter function. Let us know if this works.

**Comment by helgatheviking** [comment]
@vedanshujain that might work! thank you. Not sure what I when I will get to test that, but will make a note that it's there.

**Comment by AashikP** [comment]
Closing as this one looks resolved. Please feel free to reach out if the recommended filter doesn't meet the expectations from the original post.
