### ISSUE TITLE
Batch products export memory issue

### ISSUE THREAD

**Issue by ovidiul** [woocommerce/woocommerce#29748]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
We have a client at VIP that is trying to export around 700 products from their database using the batch export limit hook `woocommerce_product_export_batch_limit`, limit set to 150. The problem is that they don't get the column titles written to the file as expected(in the first row), and we have found the possible culprit related to the distributed filesystem and the use of the `file_put_contents` function.

Upon checking the code, at this [line](https://github.com/woocommerce/woocommerce/blob/trunk/includes/export/abstract-wc-csv-batch-exporter.php#L98), that also has a potential memory leaking issues, where the content of the CSV file is fully loaded in memory so CSV headers can be prepended, which might run into memory exceptions and unexpected behaviors.

I am proposing a solution that would fix both the memory leak issue as well as having to deal with distributed filesystems, please find my proposed PR [here](https://github.com/woocommerce/woocommerce/pull/29749).

Hope you can consider this change.

**Expected behavior**
We would expect to get the full CSV column titles at the top of the file.

**Actual behavior**
The exported file is missing the CSV column titles and data seems to be missing from it.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. The issue is specific to the VIP distributed filesystem due to its networking layer, we can provide further details on the request

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only the WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Hi @ovidiul,

Thank you for reporting the issue and submitting PR! Since the PR is already in place, I'll let the PR reviewer asses the situation further here.
