### ISSUE TITLE
[RestAPI] List all customer by username

### ISSUE THREAD

**Issue by hiagodotme** [woocommerce/woocommerce#29757]
I did an integration of my system with WooCommerce. The only way to identify a user without storing his ID is by email. I did an integration where I create my user in woocommerce as "partner.**$MY_SYSTEM_ID**", however the only way currently to locate this user is through his email in my system. If my user changes the email I can no longer retrieve his history and I end up creating a new user. I could easily resolve this if I could search for the user by username.

**Comment by hiagodotme** [comment]
Moved to https://github.com/woocommerce/woocommerce-rest-api/issues/260

**Comment by hiagodotme** [comment]
I edited my local file and it was simple to add this feature. But I didn't find the "./packages/woocommerce-admin/src/API/Customers.php" file in that repository to make the change. Does anyone know to inform me where is the correct repository for this change?

**Comment by vedanshujain** [comment]
@hiagodotme That file is in [WooCommerce Admin](https://github.com/woocommerce/woocommerce-admin) repo.

**Comment by hiagodotme** [comment]
@vedanshujain thanks!!

**Comment by hiagodotme** [comment]
Issue moved to https://github.com/woocommerce/woocommerce-admin/issues/6881
