### ISSUE TITLE
add Email Class to Abstract Settings API Class documention

### ISSUE THREAD

**Issue by mohammadYousefiDev** [woocommerce/woocommerce#29759]
In top of setting api abstract defined:

_Admin Settings API used by Integrations, Shipping Methods, and Payment Gateways._

But also used by WC_Email class.
You can add it.

**Comment by zhongruige** [comment]
Hi @mohammadYousefiDev,

Thank you for taking the time to share this idea, we really appreciate your help. 

While this is clearly a great improvement/idea we won’t be able to tackle it in the upcoming weeks. We’re going to add it to our backlog where it will be considered for future releases.

Stay tuned for updates.

**Comment by barryhughes** [comment]
Closing, as this hasn't been a priority on our side (modern IDE tooling makes it easy to see which classes implement an interface, etc) and doesn't seem all that vital. If anyone feels strongly that they'd like to see this added to the place, feel free to raise a PR and we'll happily review it.
