### ISSUE TITLE
Automate process for creating milestones of new releases and creating the release branch

### ISSUE THREAD

**Issue by vedanshujain** [woocommerce/woocommerce#29760]
We would like to automate the release process of WooCommerce to reduce the scope of manual errors (and hence less fix releases).

@claudiosanches suggested that we can take up automating creating the new release milestone and the release branch for the next release, ideally in the same action. We can trigger this action, once available using the workflow dispatch event.

**Comment by rrennick** [comment]
This is being addressed in other processes.
