### ISSUE TITLE
Uncaught TypeError: Unsupported operand types: int / string

### ISSUE THREAD

**Issue by hansmiller75** [woocommerce/woocommerce#29768]
**Issue Description:**
Activating WooCommerce results in WordPress crashing, see error log below.

Downgrading back to PHP 7.4 solves this issue.

PHP version: 8.0.3
WordPress version: 5.7.1
WooCommerce version: 5.2.2

```FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Unsupported operand types: int / string in /usr/share/webapps/wordpress/wp-content/plugins/woocommerce/includes/wc-core-functions.php:987```

Stack trace:

```#0 /usr/share/webapps/wordpress/wp-content/plugins/woocommerce/includes/class-woocommerce.php(670): wc_get_image_size()
#1 /usr/share/webapps/wordpress/wp-includes/class-wp-hook.php(292): WooCommerce->add_image_sizes()
#2 /usr/share/webapps/wordpress/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#3 /usr/share/webapps/wordpress/wp-includes/plugin.php(484): WP_Hook->do_action()                                                       #4 /usr/share/webapps/wordpress/wp-settings.php(560): do_action()
#5 /usr/share/webapps/wordpress/wp-config.php(90): require_once('...')
#6 /usr/share/webapps/wordpress/wp-load.php(37): require_once('...')
#7 /usr/share/webapps/wordpress/wp-blog-header.php(13): require_once('...')
#8 /usr/share/webapps/wordpress/index.php(17): require('...')```

**Comment by zhongruige** [comment]
Hi @hansmiller75,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by jonathansadowski** [comment]
Hi @hansmiller75,

Thanks for your report. I was able to reproduce the issue that you've mentioned. It looks like in this case, [this line specifically](https://github.com/woocommerce/woocommerce/blob/fc991ac418b262a85e88f2bb76996da1b4d76574/includes/wc-core-functions.php#L987) is causing the issue, as `$width` is being passed to the utility function as a string, when it expects an integer.

We'll fix this bug as soon as possible. Thanks again for the report, and stay tuned for updates.

**Comment by hansmiller75** [comment]
Hi @jonathansadowski,

thanks for your speedy reply and taking the time to reproduce the issue. May I advise that while this line is fixed to be campatible with PHP 8, the same code appears 6 lines before that and should probably be adjusted in the same manner.

**Comment by jonathansadowski** [comment]
@hansmiller75 agreed, thanks for noting that as well!

**Comment by roykho** [comment]
Hi there @hansmiller75 - Thanks for reporting and your patience. I tried to replicate this with latest WC 5.4.1 and PHP 8.0.3 but I was unable to. I was able to deactivate and activate WC without issues.

Can you please re-test this with WC 5.4.1 and see if you're still having this issue?  Thanks!

**Comment by SiR-DanieL** [comment]
@roykho a user reported a similar issue:

```
2021-06-24T04:06:58+00:00 CRITICAL Uncaught TypeError: Unsupported operand types: string * int in /home/dh_aipfwr/xxx/wp-content/plugins/woocommerce/includes/class-wc-discounts.php:87
Stack trace:
#0 /home/dh_aipfwr/xxx/wp-content/plugins/woocommerce/includes/class-wc-discounts.php(47): WC_Discounts->set_items_from_cart(Object(WC_Cart))
#1 /home/dh_aipfwr/xxx/wp-content/plugins/woocommerce/includes/class-wc-coupon.php(842): WC_Discounts->__construct(Object(WC_Cart))
#2 /home/dh_aipfwr/xxx/wp-content/plugins/woocommerce/includes/class-wc-cart.php(1731): WC_Coupon->is_valid()
#3 /home/dh_aipfwr/xxx/wp-content/plugins/woocommerce/includes/legacy/class-wc-legacy-cart.php(306): WC_Cart->apply_coupon('doghealthsoluti...')
#4 /home/dh_aipfwr/xxx/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(213): WC_Legacy_Cart->add_discount('doghealthsoluti...')
#5 /home/dh_aipfwr/xxx/wp-includes/class-wp-hook.php(292): WC_AJAX::apply_coupon('')
#6 /home/dh_aipfwr/xxx/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#7 /home/dh_aipfwr/xxx/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#8 /home/dh_aipfwr/xxx/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(90): do_action('wc_ajax_apply_c...')
#9 /home/dh_aipfwr/xxx/wp-includes/class-wp-hook.php(292): WC_AJAX::do_wc_ajax('')
#10 /home/dh_aipfwr/xxx/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(false, Array)
#11 /home/dh_aipfwr/xxx/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#12 /home/dh_aipfwr/xxx/wp-includes/template-loader.php(13): do_action('template_redire...')
#13 /home/dh_aipfwr/xxx/wp-blog-header.php(19): require_once('/home/dh_aipfwr...')
#14 /home/dh_aipfwr/xxx/index.php(17): require('/home/dh_aipfwr...')
#15 {main}
  thrown in /home/dh_aipfwr/plentipets.com/wp-content/plugins/woocommerce/includes/class-wc-discounts.php on line 87
```

They are on PHP 8.0.1 and WC 5.4.1

**Comment by roykho** [comment]
Hey @SiR-DanieL - if you don't mind, please create a separate issue for that.
