### ISSUE TITLE
E2E Checkout create account test fails when order of tests changed

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce#29785]
This test fails in #29761:

```
FAIL ../specs/front-end/checkout-create-account.test.js (48.226s)
  Shopper Checkout Create Account
    ✕ can create an account during checkout (30009ms)
    ✕ can verify that the customer has been created (5918ms)
```

I stopped the tests on that failure and tried the tests steps manually. I used `California` and `90210` for the address. The only shipping zones in the settings are European

<img width="1433" alt="Screen Shot 2021-04-28 at 3 52 36 PM" src="https://user-images.githubusercontent.com/343847/116457417-c5cbc480-a839-11eb-8d24-dc3c9a1cac9b.png">

And, no payment methods are enabled

<img width="1420" alt="Screen Shot 2021-04-28 at 3 53 08 PM" src="https://user-images.githubusercontent.com/343847/116457528-e3009300-a839-11eb-9db2-178560de61cd.png">

Both block submitting the order

<img width="876" alt="Screen Shot 2021-04-28 at 3 36 48 PM" src="https://user-images.githubusercontent.com/343847/116457562-eeec5500-a839-11eb-8094-6111a1d8db10.png">

**Comment by veljkho** [comment]
Test fixed in a linked pull request @rrennick
