### ISSUE TITLE
Refunds via REST doesn't refund line_item and don't show them in the invoice

### ISSUE THREAD

**Issue by monodisco** [woocommerce/woocommerce#29798]
I'm trying to make a refund vía API with this data:

This is the line_items object:

![Captura de pantalla 2021-04-29 a las 19 41 43](https://user-images.githubusercontent.com/12752411/116595303-79f54a00-a923-11eb-9215-c809065243ba.png)

And this is the request:

![Captura de pantalla 2021-04-29 a las 19 42 02](https://user-images.githubusercontent.com/12752411/116595432-98f3dc00-a923-11eb-9792-bf75d0814dd6.png)

Everything seems to be fine, but when I check the order at woocommerce the result is this:

![Captura de pantalla 2021-04-29 a las 19 48 20](https://user-images.githubusercontent.com/12752411/116595721-e5d7b280-a923-11eb-9db7-f715c30244ce.png)

If I send the amount...

```
        const data = {
          reason: "test",
          amount: orden.compra.total_iva.toString(),
          line_items: lineItemsArr,
          api_refund: false
        };
```

![Captura de pantalla 2021-04-29 a las 19 51 09](https://user-images.githubusercontent.com/12752411/116596053-46ff8600-a924-11eb-86f0-7328df50e233.png)

again, the query seems to work fine and in this case the status is refunded, but it doesn't refund line_items:

![Captura de pantalla 2021-04-29 a las 19 57 30](https://user-images.githubusercontent.com/12752411/116596890-3e5b7f80-a925-11eb-87e2-da883043e87e.png)

Doing a manual refund from woocommerce I can see the difference in the line items, notice the red numbers:

![Captura de pantalla 2021-04-29 a las 19 59 57](https://user-images.githubusercontent.com/12752411/116597203-9a260880-a925-11eb-9b67-be7723a2e2ea.png)

Also, I'm using an invoice plugin and the line items doesn't appear if i do the refund thru the API. They only appear if I do the refund in woocommerce.

![Captura de pantalla 2021-04-29 a las 20 01 29](https://user-images.githubusercontent.com/12752411/116597471-effab080-a925-11eb-85da-ecbd5b7bcd94.png)

**There is something wrong with my request?** I followed the example in the docs and checked this pull request https://github.com/woocommerce/woocommerce/pull/29099

**Comment by zhongruige** [comment]
Hi @monodisco,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by vedanshujain** [comment]
@monodisco Your request does seem correct. To troubleshoot, I would recommend following steps:
1. Make sure you are at least on WooCommerce version 5.2 when support for this feature is added.
2. ID for line_items should be `integer` and not string like in your request. Although I don't think if this will cause a problem.
3. Make sure all the IDs for line item are correct.
4. Start from a small request, for example, remove the tax lines for now, and try just with a single line item like:
```json
{
	"reason": "api test1",
	"amount": "10",
	"line_items": [
		{
			"id": 662,
			"quantity": 1,
			"refund_total": "1"
		}
	]
}
```

Let us know how it goes, and if you are still facing problems.

**Comment by monodisco** [comment]
Hi @vedanshujain 

Thanks for your fast response!

I updated woocommerce to 5.2 and that solved the problem. 

Thanks!
