### ISSUE TITLE
Update product gallery lightbox Photoswipe to 5.0

### ISSUE THREAD

**Issue by markfinst** [woocommerce/woocommerce#29800]
Creating this issue, as there seems to be new activity on Photoswipe repo and developers posted [an update](https://github.com/dimsemenov/PhotoSwipe/issues/1749), it would be nice to update the woocommerce lightbox, it should fix: #29521 #25458 #24988 #28330 #27804.

- `templates/single-product/photoswipe.php` should no longer be required
- `assets/js/frontend/single-product.js` can be simplified
- `assets/css/photoswipe/` png, gif and svg assets can be removed

(tagging @jameskoster, @mikejolley)

**Comment by jonathansadowski** [comment]
Hi @markfinst,

Thanks for pointing out the new activity in Photoswipe, and taking the time to create this issue. We have some customizations to Photoswipe in place, and updating the library would require significant effort on our part to ensure that we retain backwards compatibility. This doesn't fit into our priorities at the moment, so I'm going to close this issue.
