### ISSUE TITLE
Product: Not possible to change the product quantity with the up/down buttons on Firefox 88

### ISSUE THREAD

**Issue by felipelousantos** [woocommerce/woocommerce#29808]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

It seems that we are not able to change the product quantity on Firefox 88 because the up/down buttons are too small: https://d.pr/i/qbiDnw/YdedxrQ7BA

**Expected behavior**

You should be able to change it the same way that you change on Chrome and other browsers increasing/decreasing the quantity as expected.

**Actual behavior**

You are not able to change the quantity amount with the up/down buttons.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**

Steps to reproduce the bug:
1. Make sure that you are using Firefox 88 (it doesn't seem to be an issue with previous versions).
2. Go to a product that allows you to change the quantity on WooCommerce.
3. You shouldn't be able to change its quantity with the up/down buttons.

**Screenshots**

Chrome (works as expected): https://d.pr/i/TnnLmL/S3z2Ucag7y
Firefox (you can't change the value): https://d.pr/i/qbiDnw/YdedxrQ7BA

**Isolating the problem (mark completed items with an [x]):**

- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Additional details**

A8C Ref: 3952862-zen

**Comment by felipelousantos** [comment]
A8C Ref: 3952862-zen

**Comment by tammullen** [comment]
Hi @felipelousantos ,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 

![Screenshot 2021-05-06 at 11 32 22](https://user-images.githubusercontent.com/24649833/117285291-c549b400-ae5f-11eb-83f7-d79aca06ac91.png)
Chrome v90 macOS quantity picker buttons work in Storefront


![Screenshot 2021-05-06 at 11 32 52](https://user-images.githubusercontent.com/24649833/117285441-f0340800-ae5f-11eb-80f8-c1323d1d2180.png)
Firefox v81 macOS quantity picker buttons work in Storefront

![Screenshot 2021-05-06 at 11 35 22](https://user-images.githubusercontent.com/24649833/117285557-122d8a80-ae60-11eb-8d52-c5f91701ec40.png)
Firefox v88 macOS quantity picker buttons don't work in Storefront, however can overwrite the text input

![Screenshot 2021-05-06 at 11 36 41](https://user-images.githubusercontent.com/24649833/117285634-26718780-ae60-11eb-9aba-9f74a70839b4.png)
![Screenshot 2021-05-06 at 11 37 02](https://user-images.githubusercontent.com/24649833/117285648-283b4b00-ae60-11eb-8662-52caff8bf5b7.png)
Also confirmed same behaviour in Firefox v88 Twenty Twenty One and Twenty Twenty

We’re going to solve this bug as soon as possible. Stay tuned for updates.

**Comment by dougaitken** [comment]
I'd like to recommend not fixing the bug but rather encouraging customers to update Firefox.

Firefox `89.0.2` on Storefront with latest WC Core for https://doug.press/product/coffee-single-product/

![firefox_8902_quantity_buttons](https://user-images.githubusercontent.com/52214/124353853-f09f1400-dc00-11eb-8532-59df2cea5198.gif)

**Comment by roykho** [comment]
Closing this as it works with later versions of Firefox like 90, 91 and 92
