### ISSUE TITLE
We need to be able to log errors better

### ISSUE THREAD

**Issue by WebMedic-X** [woocommerce/woocommerce#29810]
Hi WooCommerce,

Online stores using WooCommerce have issues with payments due to many reasons.

The problem? 

WooCommerce does not store the error message / reason for failed orders.

The current solution?

Enable logging for that specific payment gateway and hope that the plugin has enough information there.

What do we need to help online stores using WooCommerce grow better?

WooCommerce needs to log the errors internally, without having to depending on other plugins.

Ideally the log is accessible from the API along with the failed transactions.

If there is anything like this now, please share and if not, what do we need to do to make it happen?

Thank you

**Comment by yehudah** [comment]
WooCommerce can't be responsible for each payment plugin that will be developed or trying 
to catch the errors of the developer.
Every API is built differently in how he responds to different scenarios, it's simply not possible or practical.
