### ISSUE TITLE
Allow to set external taxes from REST API

### ISSUE THREAD

**Issue by fidel-ruiz** [woocommerce/woocommerce#29815]
**Is your feature request related to a problem? Please describe.**
Currently taxes on resources are read-only and the calculation for that is done iternally by WooCommerce, however this have the caveat of not allowing external systems that can handle this step separately and send the order creation with all totals and taxes precalculated removing the need for woocommerce intervention on that.

**Describe the solution you'd like**
Remove the read-only constraint from order items, shipping, etc. Instead it should check for a taxMode with values like Platform, External, Disabled. 
There are precedents of this in other ECommerce APIs like https://docs.commercetools.com/api/projects/carts#taxmode

**Describe alternatives you've considered**
I can bypass the restriction by using the `woocommerce_rest_pre_insert_shop_order_object`, set up the taxes and save the order inside that same filter however that makes the endpoint slower because the order of operations, it follows by the api also execute the calculate totals -> taxes and save the object. Ideally wouldn't have to do any of that and save the order directly without adjusting the totals and taxes.

**Comment by tammullen** [comment]
Hi @fidel-ruiz ,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.
