### ISSUE TITLE
Emails getting screwed up

### ISSUE THREAD

**Issue by mrleemon** [woocommerce/woocommerce#29826]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Since the latest update, some parts of the notification emails (Shipping and Subtotal) are getting screwed up when I check them on Gmail.

**Expected behavior**
The "Shipping" field should appear below the "Subtotal" field.

**Actual behavior**
The "Shipping" field disappears and its value is concatenated in the "Subtotal" field.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to the Orders screen
2. Click one order
3. In the "Orders actions" dropdown, select "Resend email"
4. Check your email

**Screenshots**

![email](https://user-images.githubusercontent.com/2060659/117114313-f8bb0e80-ad8b-11eb-99b1-e68c20377ae3.jpg)

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): https://www.edicionesanomalas.com
Site address (URL): https://www.edicionesanomalas.com
WC Version: 5.2.2
REST API Version: ✔ 5.2.2
WC Blocks Version: ✔ 4.7.2
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.1.5
Log Directory Writable: ✔
WP Version: 5.7.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.5
PHP Post Max Size: 32 MB
PHP Time Limit: 60
PHP Max Input Vars: 5000
cURL Version: 7.61.1
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.6.40
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.2.2
WC Database Prefix: ea_
Tamaño total de la base de datos: 51.93MB
Tamaño de los datos de la base de datos: 31.58MB
Tamaño del índice de la base de datos: 20.35MB
ea_woocommerce_sessions: Datos: 8.02MB + Índice: 0.14MB + Motor InnoDB
ea_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ea_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ea_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
ea_woocommerce_order_items: Datos: 0.31MB + Índice: 0.11MB + Motor InnoDB
ea_woocommerce_order_itemmeta: Datos: 2.52MB + Índice: 3.03MB + Motor InnoDB
ea_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
ea_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
ea_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
ea_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
ea_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
ea_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ea_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ea_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ea_actionscheduler_actions: Datos: 0.06MB + Índice: 0.11MB + Motor InnoDB
ea_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ea_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ea_actionscheduler_logs: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ea_commentmeta: Datos: 0.08MB + Índice: 0.11MB + Motor InnoDB
ea_comments: Datos: 1.52MB + Índice: 1.05MB + Motor InnoDB
ea_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ea_options: Datos: 2.16MB + Índice: 0.14MB + Motor InnoDB
ea_pimwick_gift_card: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ea_pimwick_gift_card_activity: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ea_postmeta: Datos: 12.52MB + Índice: 13.03MB + Motor InnoDB
ea_posts: Datos: 2.52MB + Índice: 0.72MB + Motor InnoDB
ea_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ea_terms: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
ea_term_relationships: Datos: 0.23MB + Índice: 0.17MB + Motor InnoDB
ea_term_taxonomy: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
ea_usermeta: Datos: 0.06MB + Índice: 0.03MB + Motor InnoDB
ea_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
ea_wc_admin_notes: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
ea_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ea_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
ea_wc_customer_lookup: Datos: 0.17MB + Índice: 0.13MB + Motor InnoDB
ea_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ea_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ea_wc_order_product_lookup: Datos: 0.38MB + Índice: 0.42MB + Motor InnoDB
ea_wc_order_stats: Datos: 0.30MB + Índice: 0.31MB + Motor InnoDB
ea_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
ea_wc_product_meta_lookup: Datos: 0.06MB + Índice: 0.09MB + Motor InnoDB
ea_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
ea_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
ea_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB

### Post Type Counts ###

attachment: 649
nav_menu_item: 30
options: 5
page: 40
polylang_mo: 3
popup: 1
popup_theme: 8
post: 64
product: 174
product_variation: 99
revision: 1
shop_coupon: 170
shop_order: 2828
shop_order_refund: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

Polylang: por WP SYNTEX – 3.0.4
The SEO Framework: por El equipo de The SEO Framework – 4.1.3
BBQ Firewall: por Jeff Starr – 20210211
Classic Editor: por WordPress Contributors – 1.6
Imsanity: por Exactly WWW – 2.7.1
Limit Login Attempts Reloaded: por Limit Login Attempts Reloaded – 2.21.1
PDF Embedder: por Lever Technology LLC – 4.6.2
Rather Simple Mailchimp: por Oscar Ciutat – v1.0
Rather Simple WooCommerce Alternate Product Categories: por Oscar Ciutat – 1.0
Hyyan WooCommerce Polylang Integration: por Hyyan Abo Fakher – 1.5.0
WooCommerce Extended Coupon Features FREE: por Soft79 – 3.2.7
WooCommerce Redsys payment gateway: por Jesús Ángel del Pozo Domínguez – 1.2.10
WooCommerce: por Automattic – 5.2.2
YITH WooCommerce Gift Cards: por YITH – 2.0.13

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
gift-card (gift-card)
grouped (grouped)
pw gift card (pw-gift-card)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la tienda: #4191 - /tienda/
Carrito: #12 - /carro/
Finalizar compra: #13 - /realizar-pedido/
Mi cuenta: #14 - /mi-cuenta/
Términos y condiciones: #5218 - /terminos-y-condiciones/

### Theme ###

Name: Ediciones Anómalas
Version: 1.0.0
Author URL: http://oscarciutat.com/code/
Child Theme: ✔
Parent Theme Name: Horizontalee
Parent Theme Version: 2.0
Parent Theme Author URL: https://oscarciutat.com/code/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Completo: 105
Oldest: 2021-04-07 07:37:43 +0200
Newest: 2021-05-05 10:16:34 +0200

### WooCommerce Polylang Integration ###

Language Locale: es_ES
Polylang Language Locale: es_ES
Polylang Available Languages: es_ES (WooCommerce translation file found OK at /srv/vhost/edicionesanomalas.com/home/html/wp-content/languages/plugins/woocommerce-es_ES.mo) ca (WooCommerce translation file found OK at /srv/vhost/edicionesanomalas.com/home/html/wp-content/languages/plugins/woocommerce-ca.mo) en_US Warning - missing WooCommerce translation file NOT found at /srv/vhost/edicionesanomalas.com/home/html/wp-content/languages/plugins/woocommerce-en_US.mo

### Status report information ###

Generated at: 2021-05-05 10:24:28 +02:00
`
</details>

**Comment by mrleemon** [comment]
Checking the email HTML code, I get:

```
<tr>
    <th class="td" scope="row" colspan="2" style="color: #737373; border: 1px solid #e4e4e4; vertical-align: middle; padding: 12px; text-align: left; border-top-width: 4px;">Subtotal:</th>
    <td class="td" style="color: #737373; border: 1px solid #e4e4e4; vertical-align: middle; padding: 12px; text-align: left; border-top-width: 4px;">
        <span class="woocommerce-Price-amount amount">
            <span class="wo
                <span class="woocommerce-Price-amount amount">
                <span class="woocommerce-Price-currencySymbol">€</span>13.00
                </span>
                <small class="shipped_via">vía Standard Shipping 13€</small>
    </td>
</tr>
```

As you can see, the `<span class="wo` part is cut off. I don't understand why.

**Comment by mrleemon** [comment]
It seems this issue is only happening under PHP 8.
I returned to PHP 7.4 and the mails appear correctly.

**Comment by tammullen** [comment]
Hi @mrleemon ,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

I used a site with PHP 8
![Screenshot 2021-05-06 at 12 36 05](https://user-images.githubusercontent.com/24649833/117292140-bcf57700-ae67-11eb-8eb5-94270410b023.png)

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
​
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by mrleemon** [comment]
I tested my site deactivating all plugins except for WooCommerce and switching to Storefront and the issue persists.
The problem is found in my hosting's PHP 8 config. There must be something wrong with it.
Switching to PHP 7.4 resolves the issue.
