### ISSUE TITLE
WC->is_rest_api_request() showing different behavior according to the permalink settings.

### ISSUE THREAD

**Issue by mskapusuz** [woocommerce/woocommerce#29822]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
WC()->is_rest_api_request() method is returning different values according to the Wordpress Permalink setting choices.

**Expected behavior**
[is_rest_api_request() method of WooCommerce](https://github.com/woocommerce/woocommerce/blob/9347c728e9cb0bcfde201cd708a34b2d0715326f/includes/class-woocommerce.php#L301-L319) class should return TRUE for all REST requests.

**Actual behavior**
[is_rest_api_request() method of WooCommerce](https://github.com/woocommerce/woocommerce/blob/9347c728e9cb0bcfde201cd708a34b2d0715326f/includes/class-woocommerce.php#L301-L319) class is returning FALSE when WP Permalink is set as **Plain**

[is_rest_api_request() method of WooCommerce](https://github.com/woocommerce/woocommerce/blob/9347c728e9cb0bcfde201cd708a34b2d0715326f/includes/class-woocommerce.php#L301-L319) class is returning TRUE when WP Permalink is set as **different from Plain**

Depends on this, WC()->is_request( 'frontend' ) returns TRUE if permalink option selected as Plain. Thus, WC is loading frontend classes (Session etc.) on REST API requests if WP permalink option is Plain.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

I have wrote a snippet to test it.

```
add_action( 'rest_api_init', function(){
	register_rest_route(
		'test',
		'/rest-api-permalink-behavior-test/',
		array(
			'methods'             => \WP_REST_Server::READABLE,
			'callback'            => function(){ 
				return new \WP_REST_Response(
					array(
						'code'   => 'success',
						'markup' => sprintf( 'the value of is_rest_api_request is: %s', json_encode( WC()->is_rest_api_request() ) ),
					),
					200
				);
			},
			'permission_callback' => '__return_true',
			'args'                => array(
				'product_id' => array(
					'validate_callback' => 'is_numeric',
				),
			),
		)
	);
} );
```

1. As a first Place the snippet to WP.

**Test Case for Permalink: _Plain_:**
2.a - Go To Settings->Permalinks In WP Admin and set the Common Settings as **Plain**.
2.b - . **{yourdomain}/index.php?rest_route=/test/rest-api-permalink-behavior-test** in your browser.  It will write to screen :`{"code":"success","markup":"the value of is_rest_api_request is: false"}`

**Test Case for Permalink: _Different from Plain_:**
3.a - Go To Settings->Permalinks In WP Admin and set the Common Settings as **different from the Plain.**
3.b - . **{yourdomain}/wp-json/test/rest-api-permalink-behavior-test** in your browser.  It will write to screen: `{"code":"success","markup":"the value of is_rest_api_request is: false"}`

**Screenshots**
No

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): http://neve.localhost
Site address (URL): http://neve.localhost
WC Version: 5.2.2
REST API Version: ✔ 5.2.2
WC Blocks Version: ✔ 4.7.2
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.1.5
Log Directory Writable: ✔
WP Version: 5.7.1
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.1.1d
PHP Version: 7.4.16
PHP Post Max Size: 25 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.2.37-MariaDB-1:10.2.37+maria~bionic
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.2.2
WC Database Prefix: wp_
Total Database Size: 4.73MB
Database Data Size: 3.24MB
Database Index Size: 1.49MB
wp_woocommerce_sessions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 2.02MB + Index: 0.06MB + Engine InnoDB
wp_postmeta: Data: 0.14MB + Index: 0.11MB + Engine InnoDB
wp_posts: Data: 0.20MB + Index: 0.06MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 34
custom_css: 1
customize_changeset: 1
nav_menu_item: 9
page: 19
post: 5
product: 18
wishlist: 22
wp_block: 6

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (2) ###

Code Snippets: by Code Snippets Pro – 2.14.1
WooCommerce: by Automattic – 5.2.2

### Inactive Plugins (7) ###

Akismet Anti-Spam: by Automattic – 4.1.8
Debug Info: by Scott DeLuzio – 1.3.9
Gutenberg Blocks and Template Library by Otter: by ThemeIsle – 1.6.3
Hello Dolly: by Matt Mullenweg – 1.7.2
Neve Pro Addon: by ThemeIsle – 1.5.2
Templates Patterns Collection: by ThemeIsle – 1.1.4
WooCommerce WishLists: by Element Stark – 2.2.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #207 - /?page_id=207
Cart: #14 - /?page_id=14
Checkout: #15 - /?page_id=15
My account: #16 - /?page_id=16
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.5.1
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Pending: 1
Oldest: 2021-05-01 16:29:05 +0000
Newest: 2021-05-01 16:29:05 +0000

### Status report information ###

Generated at: 2021-05-04 11:01:47 +00:00
`
</details>

**Comment by mskapusuz** [comment]
A related issue: https://github.com/woocommerce/woocommerce/issues/27160

**Comment by mskapusuz** [comment]
> Hi @mskapusuz ,
> 
> Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look.
> 
> Please note it may take a few days for them to get to this issue. Thank you for your patience.

Thanks!

**Comment by vedanshujain** [comment]
@mskapusuz because of technical limitations (basically an ambiguity in identifying request) with plain permalinks, we currently don't support it with REST API, (see the 3rd point in [our requirement document](http://woocommerce.github.io/woocommerce-rest-api-docs/#requirements)). A fix for this is [under discussion in the WordPress project](https://core.trac.wordpress.org/ticket/42061), which we are hoping to use when it gets available instead of rolling out our solution at this point.

I am closing the issue marking it as upstream, but feel free to reply back if you have more questions.
