### ISSUE TITLE
Anyone can give a instruction to copy the WC setting from one site to another?

### ISSUE THREAD

**Issue by Neal86** [woocommerce/woocommerce#29825]
I want to recreate my site because of some reason, and I'm facing a problem copying the WC setting because there are some settings that I don't want to do it again(payment, shipping, etc…… Anyone can give a detailed instruction to copy the WC setting from one site to another site？

**Comment by lukecav** [comment]
You could use either of these plugins.
https://wordpress.org/plugins/options-importer/
https://wordpress.org/plugins/wp-cfm/

**Comment by tammullen** [comment]
Thank you for your issue. 

However, as noted this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/13089. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
