### ISSUE TITLE
Customer invoice email should check for "needs_payment" and not "has_status( 'pending' )"

### ISSUE THREAD

**Issue by webdados** [woocommerce/woocommerce#29832]
Hi guys,

When using the `woocommerce_order_needs_payment` or the `woocommerce_valid_order_statuses_for_payment` filters to return true for certain circumstances, for example, a payment method that needs the "On hold" status, one would expect when sending the "Customer invoice" email ([not that I agree with this naming](https://github.com/woocommerce/woocommerce/issues/26692)), that the payment lin is added to it.

Yet on [customer-invoice.php line 32](https://github.com/woocommerce/woocommerce/blob/trunk/templates/emails/customer-invoice.php#L32) we're checking for the specific pending order status and not for the fact that the order needs or doesn't need payment which is, IMHO, incorrect.

I suggest that we change that validation to `$order->needs_payment()`

**Comment by tammullen** [comment]
Hi @webdados ,

Thank you for opening the issue and PR! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by webdados** [comment]
Good @tammullen

**Comment by vedanshujain** [comment]
@webdados  thanks for the issue and patch. this suggestion does make sense, and we anyway use `order->needs_payment` everywhere else when we need to check whether is payment is required or not (for example, in the payment form). Going to ask a review from the team to move this forward.
