### ISSUE TITLE
GitHub action to set labels when a pull request is merged (replacing existing 3rd party webhook)

### ISSUE THREAD

**Issue by Konamiman** [woocommerce/woocommerce#29852]
Right now the `status: needs changelog` and `status: needs testing instructions` labels are automatically added when a pull request is merged, however this is done via [an external webhook](https://github.com/woocommerce/woocommerce/settings/hooks/109928852). We should develop a GitHub action that does the same thing and then remove the webhook.

Of note:

* We have already [an existing action that auto-milestones merged pull requests](https://github.com/woocommerce/woocommerce/actions/workflows/pull-request-post-merge-processing.yml), so it's probably appropriate to extend it instead of creating a new one.
* We should be selective on the pull requests to which the labels are applied, for example the ones related to E2E tests don't need them.

**Comment by vedanshujain** [comment]
Changing the scope of this issue to add a comment instead when PR is merged, which should have a checklist for adding those labels.
