### ISSUE TITLE
Can't complete initial setup due to error: "There was a problem updating your business details"

### ISSUE THREAD

**Issue by cfinke** [woocommerce/woocommerce#29857]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When in the setup wizard, the Business Details step fails with the error "There was a problem updating your business details" accompanied by a separate box showing [object Object]

**Expected behavior**
I expected this to not happen.

**Actual behavior**

A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**

On a clean WordPress 5.7.1 install with no plugins installed, I installed WooCommerce and began the setup wizard. I filled out each screen with testing date:

Address: 123 Fake Street, Beverly Hills, CA 90210
Industry: Electronics and Computers
Product types: physical products, downloads
Number of products: 1-10
Currently selling elsewhere? No

This error appeared in my logs:

```
PHP Fatal error:  Uncaught Error: Call to undefined method Automattic\\Jetpack\\Connection\\Manager::is_connected() in wp-content/plugins/jetpack/class.jetpack.php:1756, referer: /wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard&step=business-features
Stack trace:, referer: /wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard&step=business-features
#0 wp-content/plugins/jetpack/class.jetpack.php(2003): Jetpack::is_connection_ready(), referer: /wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard&step=business-features
#1 wp-content/plugins/jetpack/class.jetpack.php(3445): Jetpack::load_modules(), referer: /wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard&step=business-features
#2 wp-content/plugins/jetpack/class.jetpack.php(3338): Jetpack::plugin_initialize(), referer: /wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard&step=business-features
#3 wp-includes/class-wp-hook.php(292): Jetpack::plugin_activation(false), referer: /wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard&step=business-features
#4 wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array), referer: /wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard&step=business-features
#5 wp-includes/plugin.php(484): WP_Hook->do_action(Array), referer: /wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard&step=business-features
#6 wp-admin/includes/plugin.php(701): do_action('activate_jetpac...', false), referer: /wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard&step=business-features
#7 in wp-content/plugins/jetpack/class.jetpack.php on line 1756, referer: /wp-admin/admin.php?page=wc-admin&path=%2Fsetup-wizard&step=business-features
```

**Screenshots**

<img width="470" alt="Screen Shot 2021-05-07 at 8 29 03 AM" src="https://user-images.githubusercontent.com/435369/117479122-ca1c6f80-af14-11eb-840a-b87be1dc9894.png">

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>

### WordPress Environment ###

WordPress address (URL): https://woocommercetest.efinke.com
Site address (URL): https://woocommercetest.efinke.com
WC Version: 5.2.2
REST API Version: ✔ 5.2.2
WC Blocks Version: ✔ 4.7.2
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.1.5
Log Directory Writable: ✔
WP Version: 5.7.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.15
PHP Post Max Size: 512 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.28-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.2.2
WC Database Prefix: wp_jvjsdw_
Total Database Size: 3.25MB
Database Data Size: 1.87MB
Database Index Size: 1.38MB
wp_jvjsdw_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jvjsdw_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jvjsdw_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jvjsdw_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_jvjsdw_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jvjsdw_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jvjsdw_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_jvjsdw_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jvjsdw_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jvjsdw_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jvjsdw_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jvjsdw_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jvjsdw_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jvjsdw_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jvjsdw_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_jvjsdw_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jvjsdw_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jvjsdw_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jvjsdw_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jvjsdw_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_jvjsdw_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jvjsdw_options: Data: 1.03MB + Index: 0.03MB + Engine InnoDB
wp_jvjsdw_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jvjsdw_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_jvjsdw_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jvjsdw_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jvjsdw_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jvjsdw_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jvjsdw_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jvjsdw_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_jvjsdw_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jvjsdw_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jvjsdw_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jvjsdw_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jvjsdw_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jvjsdw_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jvjsdw_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_jvjsdw_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_jvjsdw_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_jvjsdw_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_jvjsdw_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_jvjsdw_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_jvjsdw_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 3
page: 6
post: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

DreamHost Panel Login: by DreamHost
danielbachhuber – 1.0.0

WooCommerce Payments: by Automattic – 2.3.3
WooCommerce Shipping & Tax: by WooCommerce – 1.25.12
WooCommerce: by Automattic – 5.2.2

### Inactive Plugins (5) ###

Creative Mail by Constant Contact: by Constant Contact – 1.3.5
Facebook for WooCommerce: by Facebook – 2.4.1
Google Ads & Marketing by Kliken: by Kliken – 1.0.7
Jetpack by WordPress.com: by Automattic – 9.7
Mailchimp for WooCommerce: by Mailchimp – 2.5.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 1
Oldest: 2021-05-07 15:59:22 +0000
Newest: 2021-05-07 15:59:22 +0000

### Status report information ###

Generated at: 2021-05-07 16:12:04 +00:00
</details>

**Comment by tammullen** [comment]
Hi @cfinke 

Thanks for raising this. It is due to this Jetpack issue https://github.com/Automattic/jetpack/issues/19624
Closing for now as this is being already looked at outside of WooCommerce core.
