### ISSUE TITLE
WooCommerce Docs error

### ISSUE THREAD

**Issue by colmtroy** [woocommerce/woocommerce#29858]
Correct me if I'm wrong, but I think the docs are incorrect here
https://docs.woocommerce.com/document/image-sizes-theme-developers/

![](https://i.imgur.com/D5v1syU.png)

Isn't the default 300px? https://github.com/woocommerce/woocommerce/blob/b19500728b4b292562afb65eb3a0c0f50d5859de/includes/class-wc-install.php#L618

**Comment by tammullen** [comment]
Hi @colmtroy 

Thanks for reporting this.

Raised internally to docs team at p1620557967119700-slack-CSP74N77C

We will look into this and respond back.

**Comment by solstudioim** [comment]
Thanks for the report @colmtroy it's now been fixed.

Fyi @tammullen

**Comment by tammullen** [comment]
Thanks @solstudioim!

I'm closing this issue now @colmtroy, thanks again!
