### ISSUE TITLE
package.json cannot be processed (Error at if [ -z "$SKIP_LERNA_BOOTSTRAP" ])

### ISSUE THREAD

**Issue by leonrenner** [woocommerce/woocommerce#29868]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When cloning WooCommerce as writting in this instruction: https://developer.woocommerce.com/extension-developer-guide/getting-started/ and running the command "npm install" with using node v12.21.0, an error gets thrown at the line 

"if [ -z "$SKIP_LERNA_BOOTSTRAP" ]; then npx lerna bootstrap --hoist; fi". 

The response is that "-z" can syntactically not be processed at this spot. This is the full error:

"-z" kann syntaktisch an dieser Stelle nicht verarbeitet werden.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! woocommerce@5.3.0 install: ` if [ -z "$SKIP_LERNA_BOOTSTRAP" ]; then npx lerna bootstrap --hoist; fi`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the woocommerce@5.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Expected behavior**
I expected the installation to run through without any errors.

**Actual behavior**
The error occurs.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Download WordPress and unzip it
2. Inside the plugins folder clone "https://github.com/woocommerce/woocommerce.git"
3. While inside the woocommerce folder set node v12.21.0
4. run npm install

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rrennick** [comment]
@leonrenner Thanks for reporting the issue. Can you provide us with the details of the computer/server where you have this issue?

**Comment by leonrenner** [comment]
> @leonrenner Thanks for reporting the issue. Can you provide us with the details of the computer/server where you have this issue?

Hi rrennick, I'll gladly do that.

I'm trying to create a dev environment on my local computer. So here are the details:
System: Windows 10 Pro
Architecture: x64
RAM: 16GB

WordPress has been downloaded and extracted and WooCommerce has been cloned from GitHub right into the plugin folder. nvm and npm is installed.

**Comment by rrennick** [comment]
@leonrenner Thanks for the quick response.

@Konamiman Do you have access to Win 10 Pro to see if you can reproduce this?

**Comment by leonrenner** [comment]
@rrennick which system do you usually use for development purpose? I would really like to continue on Windows 10 but if it doesn't work, I might have to switch to another system in the meantime.

**Comment by Konamiman** [comment]
Hi @leonrenner. Are you directly using the Windows command processor or PowerShell? If so it's not going to work as all the WooCommerce development related scripts are intended to be run in Linux or Mac.

That said, if you want to develop in Windows I recommend you to use [WSL](https://docs.microsoft.com/en-us/windows/wsl/about), that's what I use myself (yes, I'm one of the very few Automatticians using Windows) and it works pretty well.

**Comment by helgatheviking** [comment]
@leonrenner Unfortunately, my experience is that WSL solves some problems and introduces some problems. The performance gains are sweet!and it runs the build scripts _better_ than Powershell (though there's nary a day where I am not fighting the build scripts). but I find it means I can't use apps like Local or Sourcetree which I really like (especially Sourcetree). It's still not a perfect solution. GUI support is coming to WSL (already in the windows dev builds) which may open up some options too.

**Comment by Konamiman** [comment]
@helgatheviking GUI Linux apps can already be used in WSL with a 3rd party X11 server running on Windows.

**Comment by helgatheviking** [comment]
@Konamiman I was never able to get a 3rd party X11 server up and running but the latest dev build of Windows includes native WSL support for GUI apps which is pretty cool. I may have to switch to GitKraken pro if I am still stuck for a a git client for the WSL files.
