### ISSUE TITLE
Lots of rate limit autoloaded options

### ISSUE THREAD

**Issue by abhishek-pokhriyal** [woocommerce/woocommerce#29869]
**Is your feature request related to a problem? Please describe.**
The `wp_options` table of my WooCommerce store has a lot of **autoloaded** options with the name `woocommerce_rate_limit_*`.

![image](https://user-images.githubusercontent.com/11808845/117624003-0f99a080-b192-11eb-9bf1-c5011c63ce2f.png)

On digging further, I found that these are being added when a user adds a payment method: https://github.com/woocommerce/woocommerce/blob/e1bc077ae374a766f22dbc3f38b42d47caf98726/includes/class-wc-form-handler.php#L506

**Describe the solution you'd like**
I would like to know from the WooCommercce team if the following two changes can happen:

1. Any option added via Rate Limiter should not be autoloaded.
1. Rate limit options should be cleaned up via a cron job (if not already).

**Describe alternatives you've considered**
I've not taken any alternative so far.

**Additional context**
It's generally important to keep a check on the amount of autoloaded for your WordPress site. Additionally, the object caching feature provided by hostings (like WP Engine) works when the size of autoloaded data is less than 8 MB.

**Comment by DavidAnderson684** [comment]
Since these options are all tied to specific users, it's also arguable that they should be stored as usermeta, not options.

**Comment by DavidAnderson684** [comment]
As a temporary mitigation, it is harmless to simply delete all these rows, since they are only relevant for 20 seconds - after which they clutter the database until the end of time.... which is itself poor design. A single transient that listed only user IDs from the last 20 seconds would have sufficed.

**Comment by juliaamosova** [comment]
Hi @abhishek-pokhriyal,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by claudiosanches** [comment]
Hello @abhishek-pokhriyal,

Thanks for starting this issue, I can confirm it on WooCommerce side, it's a bug indeed, we shouldn't store it forever and I agree that there's no reason to set to `autoload`.
While we are working in a fix you can remove those from time to time, I wrote a snippet to help on it, you can enable it as a plugin and use the "Status" > "Tools" page to trigger it: https://gist.github.com/claudiosanches/0623c3ba253efb9a98c552e646ee7116
I hope it helps for now.

We’re going to solve this bug as soon as possible. Stay tuned for updates.

**Comment by abhishek-pokhriyal** [comment]
Thanks, @claudiosanches. I downloaded and ran the snippet on the affected store and it worked – deleted 1234 entries.

**Comment by claudiosanches** [comment]
Thanks for letting me know about it. For this issue I think we'll introduce a new database for the `WC_Rate_Limiter` class, so we don't end up having issues with a large `wp_options` table, and also to include a routine to clean it.

**Comment by claudiosanches** [comment]
Duplicated of https://github.com/woocommerce/woocommerce/issues/27103
