### ISSUE TITLE
WooCommerce Exporter: Wrong handling of variable product drafts and their variations

### ISSUE THREAD

**Issue by laundy** [woocommerce/woocommerce#29865]
**Prerequisites (mark completed items with an [x]):**
- [X] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
The WooCommerce CSV exporter is exporting variations of variable products which are in state `draft` (`-1`) also in draft state. Using the WooCommerce CSV importer will lead to these variations to be "hidden" as they are imported in draft state. 
![image](https://user-images.githubusercontent.com/15380131/117549875-27abdb80-b03d-11eb-8c35-9c4a988caf5d.png)

As mentioned in https://github.com/woocommerce/woocommerce/issues/26860#issuecomment-653883479, Variations don't have a `draft` state. Hence I consider this behavior probably introduced with https://github.com/woocommerce/woocommerce/pull/27046 as erroneous behavior.

**Expected behavior**
To my best knowledge, this requires a more general design decision. Should variations for which the parent product is a `draft` be `private` or `published` (but also not visible as the parent is a draft)?

**Actual behavior**
The WooCommerce CSV exporter is exporting variations of variable products which are in state `draft` (`-1`) also in draft state although this state does not exist for variations.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create a `variable` product without publishing it (= `draft`)
2. Create some variations for this product
3. Run the WooCommerce product exporter with a selection that includes the product created in step 1.
4. Open the exported CSV in a viewer of your choice and inspect the `Type` and `Published` columns.

**Screenshots**
![image](https://user-images.githubusercontent.com/15380131/117549875-27abdb80-b03d-11eb-8c35-9c4a988caf5d.png)

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): http://localhost/woocommerce
Site address (URL): http://localhost/woocommerce
WC Version: 5.0.0
REST API Version: ✔ 5.0.0
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.9.0
Log Directory Writable: ✔
WP Version: ❌ 5.6.3 - Es ist eine neuere Version von WordPress verfügbar (5.7.1)
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_DE_formal
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Win64) OpenSSL/1.1.1g PHP/7.4.11
PHP Version: 7.4.11
PHP Post Max Size: 64 MB
PHP Time Limit: 240
PHP Max Input Vars: 1000
cURL Version: 7.70.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.14-MariaDB
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.9.1
WC Database Prefix: woo_
Datenbank-Gesamtgröße: 129.99MB
Datenbank-Datengröße: 55.93MB
Datenbank-Indexgröße: 74.06MB
woo_woocommerce_sessions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
woo_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
woo_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
woo_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.17MB + Engine InnoDB
woo_woocommerce_order_items: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
woo_woocommerce_order_itemmeta: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
woo_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
woo_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
woo_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
woo_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
woo_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
woo_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
woo_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
woo_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
woo_actionscheduler_actions: Daten: 0.34MB + Index: 0.36MB + Engine InnoDB
woo_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
woo_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
woo_actionscheduler_logs: Daten: 0.28MB + Index: 0.23MB + Engine InnoDB
woo_aws_cache: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
woo_aws_index: Daten: 3.30MB + Index: 2.66MB + Engine InnoDB
woo_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
woo_comments: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
woo_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
woo_options: Daten: 2.17MB + Index: 0.34MB + Engine InnoDB
woo_postmeta: Daten: 14.52MB + Index: 13.03MB + Engine InnoDB
woo_posts: Daten: 3.52MB + Index: 1.34MB + Engine InnoDB
woo_termmeta: Daten: 0.08MB + Index: 0.09MB + Engine InnoDB
woo_terms: Daten: 0.05MB + Index: 0.03MB + Engine InnoDB
woo_term_relationships: Daten: 1.48MB + Index: 0.41MB + Engine InnoDB
woo_term_taxonomy: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
woo_usermeta: Daten: 0.08MB + Index: 0.03MB + Engine InnoDB
woo_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
woo_wcpdf_invoice_number: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
woo_wc_admin_notes: Daten: 0.05MB + Index: 0.00MB + Engine InnoDB
woo_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
woo_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
woo_wc_customer_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
woo_wc_download_log: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
woo_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
woo_wc_order_product_lookup: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
woo_wc_order_stats: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
woo_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
woo_wc_product_meta_lookup: Daten: 1.52MB + Index: 1.06MB + Engine InnoDB
woo_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
woo_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
woo_wc_webhooks: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
woo_woobe_history: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
woo_woobe_history_bulk: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
woo_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
woo_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
woo_woocommerce_gzd_dhl_labelmeta: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
woo_woocommerce_gzd_dhl_labels: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
woo_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
woo_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
woo_woocommerce_gzd_shipmentmeta: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
woo_woocommerce_gzd_shipments: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
woo_woocommerce_gzd_shipment_itemmeta: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
woo_woocommerce_gzd_shipment_items: Daten: 0.02MB + Index: 0.13MB + Engine InnoDB
woo_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
woo_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
woo_wpmailsmtp_tasks_meta: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
woo_wps_hit: Daten: 0.02MB + Index: 0.14MB + Engine InnoDB
woo_wps_index: Daten: 22.39MB + Index: 40.20MB + Engine InnoDB
woo_wps_key: Daten: 0.52MB + Index: 0.44MB + Engine InnoDB
woo_wps_object_term: Daten: 4.48MB + Index: 11.61MB + Engine InnoDB
woo_wps_object_type: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
woo_wps_query: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
woo_wps_uri: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
woo_wps_user_agent: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

acf-field: 21
acf-field-group: 7
attachment: 2376
custom_css: 1
global_product_addon: 1
nav_menu_item: 82
page: 15
post: 2
product: 1105
product_variation: 4213
revision: 14
shop_coupon: 2
shop_order: 9
shop_order_refund: 1
wcpf_item: 5
wcpf_project: 1

### Security ###

Secure connection (HTTPS): ❌
					Ihr Shop benutzt kein HTTPS. Erfahren Sie mehr über HTTPS und SSL-Zertifikate.
Hide errors from visitors: ✔

### Active Plugins (2) ###
WooCommerce: von Automattic – 5.0.0 (Update auf Version 5.2.2 ist verfügbar)

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: ❌ Seite nicht festgelegt
Warenkorb: #9 - /warenkorb/
Kasse: #573 - /kasse/
Mein Konto: #11 - /mein-konto/
Allgemeine Geschäftsbedingungen: #51 - /allgemeine-geschaeftsbedingungen/

### Theme ###

Name: Storefront Child
Version: 2.5.5
Author URL: https://woocommerce.com/
Child Theme: ✔
Parent Theme Name: Storefront
Parent Theme Version: 3.5.0 – 3.5.1 ist verfügbar
Parent Theme Author URL: https://woocommerce.com/
WooCommerce Support: ✔

### Templates ###

Overrides: storefront-child/woocommerce/emails\customer-invoice.php
storefront-child/woocommerce/single-product\meta.php
storefront-child/woocommerce/single-product\tabs\description.php

### Action Scheduler ###

Abgeschlossen: 1.136
Oldest: 2021-04-11 19:31:32 +0200
Newest: 2021-05-08 20:35:05 +0200

Fehlgeschlagen: 20
Oldest: 2021-04-11 20:48:07 +0200
Newest: 2021-04-18 18:48:26 +0200

Ausstehend: 2
Oldest: 2021-05-08 21:02:25 +0200
Newest: 2021-05-08 21:18:37 +0200
`
</details>

**Comment by dphyled** [comment]
Similar to https://github.com/woocommerce/woocommerce/issues/29700

**Comment by juliaamosova** [comment]
Hi @laundy,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/29700. Thank you @dphyled for noting! 

We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
