### ISSUE TITLE
Hi. The ajax add to cart button doesn't work.

### ISSUE THREAD

**Issue by kazarin0v** [woocommerce/woocommerce#29875]
![wc](https://user-images.githubusercontent.com/76615266/117762218-b26e1f80-b263-11eb-87fa-8a401db871ea.png)

The "click" event doesn't work on phones.

You need to set "click touchstart" or " click touchend"

Thank you.

**Comment by juliaamosova** [comment]
Hi @kazarin0v,

Thank you for providing additional details! However, I am unable to reproduce the issue. The add-to-cart ajax button is working as expected. I tested using WooCommerce 5.3 using iPhone 12 Pro. 

Please see the screencast below:

https://user-images.githubusercontent.com/19143190/118420565-2312a300-b68d-11eb-9c14-1f91eed7b061.MP4

The `Enable AJAX add to cart buttons on archives` setting is enabled on my test site:

<img width="1044" alt="ajax" src="https://user-images.githubusercontent.com/19143190/118420710-90263880-b68d-11eb-9102-480779b1a617.png">

What version of WooCommerce, WordPress, and PHP are you using on your site? And also what device are you testing on?
