### ISSUE TITLE
Cant add additional download permissions on 5.3

### ISSUE THREAD

**Issue by ciesielskil** [woocommerce/woocommerce#29884]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

**Comment by tammullen** [comment]
Hi @ciesielskil 

Thank you for submitting the issue. Can you confirm if this is the behaviour you are seeing?

- Create an order from either within the dashboard or normal checkout **that does not include the product we are going to manually grant access to later**
- Make sure you've fully saved the order
- Enter the downloadable product name into the 'Downloadable product permissions' input
- Click 'Grant access' - you'll see the notice `Could not grant access`. This notice does not occur in 5.1 or 5.2.2

![Screenshot 2021-05-12 at 11 37 03](https://user-images.githubusercontent.com/24649833/117961885-86f83d00-b316-11eb-97d6-af2f1a7c8e8b.png)
![Screenshot 2021-05-12 at 11 37 35](https://user-images.githubusercontent.com/24649833/117961892-88c20080-b316-11eb-9042-2a9ad81b62c9.png)

Marking this a high priority bug for now as this behaviour was not in 5.1 or 5.2.2 however I am also adding the `needs developer feedback` label to this issue so that the Core team could take a look in case this is the new expected behaviour after the introduction of https://github.com/woocommerce/woocommerce/pull/23188 in 5.3.

Stay tuned for updates.

**Comment by tammullen** [comment]
For anyone encountering this issue a workaround for now that might be helpful

1) Add the product as an additional Order item (no need to update the order)
2) Add the product to Downloadable permissions and Grant access
3) Remove the product from the Order

See gif below for an example of thia

![Screen Recording 2021-05-13 at 09 49 20 2021-05-13 09_53_42](https://user-images.githubusercontent.com/24649833/118103185-883a7000-b3d1-11eb-9a71-5e166ba9cfe5.gif)

**Comment by claudiosanches** [comment]
It's also possible to include the product to the order, added a discount for the whole product amount and then include the downloadable product permissions, this way it's nice even to keep track of those products and discounts in the reports/analytics pages.

**Comment by jessy-p** [comment]
**Ticket**: 3985316-zen

**Comment by battouly** [comment]
**Reported in tickets:** 

- 3985604-zen
- 3985750-zen
- 3986309-zen
- 3988714-zen

**Comment by claudiosanches** [comment]
Hello @jessy-p @battouly,

Please note that we don't intent to implement the previous behavior again, so probably could be nice to indicate the correct way of setting a product like that as I indicated in https://github.com/woocommerce/woocommerce/issues/29884#issuecomment-840603914

**Comment by dougaitken** [comment]
@claudiosanches @tammullen 

Can you both please provide more details and steps to do this, please? It isn't possible to add a downloadable product or permission to a Completed or Processing order. 

The order needs to be edited to on-hold or pending payment then back to Processing or Completed, which in turns sends order related emails to customers and store admin and changes the costs which may not be intended.

Any further details about your workarounds that you can provide including order statuses and such, would really help here. Thanks.

**Comment by theabhig** [comment]
Reported in 3990921-zen as well

**Comment by sammy3d** [comment]
Was asked to report this issue here. I am having the same error when granting access to downloadable products. I am applying the workaround described above for now until this is resolved.

Note this is new behavior since updating to v5.3.

**Comment by neoseo1300** [comment]
Same here. I was asked to report the same issue here. Bug appeared with the new version of Woocommerce (5.3). It was working just fine before.

**Comment by phioe** [comment]
Hi – I’d like to add an “I’m also affected” notification.

WordPress 5.7.2
Woocommerce 5.3.0

Problem as described in description: Manually adding permissions to an order yields this error message (in German, but same content). Reproducable with any orders, any customers. The mentioned workaround with adding the item to the order beforehand also works but is of course unhandy.

Can you give any hints or forecasts regarding the cause or the resolution of the problem?

**Comment by claudiosanches** [comment]
@dougaitken yes, both requires to change the order back to some status that's possible to edit, but note that including a download after a order is completed like before 5.3 as impossible to track how many free downloads someone is giving in any store.

**Comment by apmwebdev** [comment]
Another report in 3997384-zen

**Comment by stephhjacq** [comment]
also 4005540-zen

**Comment by Raquel1515** [comment]
Me either. I was unable to grant access to customers.
Version 5.3.0
This tip helps a lot, but it doesn't solve it. There are 3 more actions to perform one, to grant access.

**Comment by shabnam611** [comment]
Here as well 24874635-hc

**Comment by Nic-Sevic** [comment]
also here: 4032921-zen
user able to use workaround here: https://github.com/woocommerce/woocommerce/issues/29884#issuecomment-840421600

**Comment by jrick1229** [comment]
Also seen in the forums: https://wordpress.org/support/topic/erro-ao-conceder-acesso-a-produtos-no-pedido/

**Comment by n9yty** [comment]
> @dougaitken yes, both requires to change the order back to some status that's possible to edit, but note that including a download after a order is completed like before 5.3 as impossible to track how many free downloads someone is giving in any store.

But if a store owner doesn't care about this, the previous behavior was perfectly acceptable and widely used. I am not sure this should not be reverted to make the previous behavior work again.

**Comment by squilib** [comment]
The bug was fixed in Woocommerce 5.2.2
It appeared again in 5.3.0

The above solution doesn't work for me (I don't have "Add Item" under the total, I just have "Refund". All my orders are no longer editable.)

I was promised a high priority bug fix in the next version.
Today in the new version 5.4.0 the bug has not been fixed yet.

**Comment by dynit** [comment]
We need this function too, it is very much missed. The workaround generates extra unwanted status changes (and emails).

**Comment by jakewhiteley** [comment]
Another vote for adding this back in here!

[This workaround](https://github.com/woocommerce/woocommerce/issues/29884#issuecomment-840421600) is fine, but shouldn't really need to happen in the first place ideally.

**Comment by Jonasss28** [comment]
I'm having issues with this issue too.
 
The workaround works, but there are many steps to do, this should be as before, simpler and more practical.

The previous version is much better with just 1 step my client can release the file for download.

**Comment by Jonasss28** [comment]
I'm having issues with this issue too.
 
The workaround works, but there are many steps to do, this should be as before, simpler and more practical.

The previous version is much better with just 1 step my client can release the file for download.

**Comment by phioe** [comment]
I also give strong support for reenabling the former behavior. Very obviously this is a very common and welcome usecase. The people who don't use it won't see a difference and the people who do are missing it dearly.

Best
\phi

**Comment by Robertght** [comment]
Another report in 24201172-hc. Workaround did the trick

**Comment by plassard** [comment]
Please enable possibililty to add download permissions. The workaround does not work for me once the order goes back to completed the download permission disapears?

**Comment by plassard** [comment]
> For anyone encountering this issue a workaround for now that might be helpful
> 
> 1. Add the product as an additional Order item (no need to update the order)
> 2. Add the product to Downloadable permissions and Grant access
> 3. Remove the product from the Order
> 
> See gif below for an example of thia
> 
> ![Screen Recording 2021-05-13 at 09 49 20 2021-05-13 09_53_42](https://user-images.githubusercontent.com/24649833/118103185-883a7000-b3d1-11eb-9a71-5e166ba9cfe5.gif)

This does not work for me download permission vanishes after setting the order to complete.

**Comment by Jonasss28** [comment]
Hi
This situation is very uncomfortable. See the problem caused
The payment plugin automatically changes the order status to processing and when this happens the add item to order button disappears, which leads me to change the order status again to awaiting payment and this creates confusion for users, for please give more priority to problem solving

**Comment by centurygirl** [comment]
Hi,
I have encountered the same issue after update of woocommerce to 5.4.1 version. The workaround you propose is not possible for processed orders. I support the demand to assign to this problem a higher priority. 
Thank you in advance!

**Comment by beatfarm7** [comment]
Makes no sense why this was removed. Please add this back...right meow.

**Comment by claudiosanches** [comment]
Here the fix to make this unsafe again: https://github.com/woocommerce/woocommerce/pull/29901

**Comment by BonnieBeeman** [comment]
Please make this feature available again, it is extremely important to our e-commerce store.  "Allows set downloadable permissions to any downloadable product in any order #29901"  Error in WooCommerce 5.5.0 is: "Could not grant access - the user may already have permission for this file or billing email is not set. Ensure the billing email is set, and the order has been saved"

**Comment by Shishir47** [comment]
None of the above solutions works for me. I tried adding the product at the first place then tried to grant access but it still shows an error.

![image](https://user-images.githubusercontent.com/44887399/125705234-28c09a57-2c2f-4cca-9bae-30dfdd5eb33a.png)

**Comment by johndcoy** [comment]
To add a downloadable product to an order:

1. Make sure the order has an editable status of **Pending Payment** or **Oh Hold**. 
2. Within the Items section, click **Add item(s)** > **Add product(s)** and add the downloadable product.
3. Scroll to the **Download product permissions** section and then add the same downloadable product.

**Comment by mzpack** [comment]
**WooCommerce 5.5.1**

This happened after the 'security' update.
I see "File not found Go to shop" after a user click on the link to download a product. 

The Download Permission is attached to the order automatically, but it doesn't work!
Nothing works for all my hundreds of previous orders too!!!

Also, I can't add permission manually:
"Could not grant access - the user may already have permission for this file or billing email is not set. Ensure the billing email is set, and the order has been saved"

Provide a solution ASAP!

**Comment by BonnieBeeman** [comment]
notifications@github.com - woocommerce@noreply.github.com

The alternative solutions for granting download permission to a product from within an order are not acceptable for the following reasons: 

1.  Completed Orders must have their status changed to Pending or On Hold.  This automatically sends an unwanted and unnecessary email to all Admins and fulfillment.   
2. Adding a product that is in BETA testing to an existing COMMERCIAL paid order is inaccurate accounting
3. The only way to grant the user permission is to COMPLETE the order, which unnecessarily sends email notification to the user, admins and fulfillment which is confusing.   

The feature for granting download permission to a product was available until just recently, and then removed by someone who doesn't think it's secure.  That is not true.  Granting permission is only available through strict admin access to specific accounts that must also have a License Key for authorization.   

Please re-instate granting download permission back into WooCommerce and Wordpress ASAP.

**Comment by BonnieBeeman** [comment]
These alternative solutions for granting download permission to a product from within an order are not acceptable for the following reasons: 
 
1.  Completed Orders must have their status changed to Pending or On Hold.  This automatically sends an unwanted and unnecessary email to all Admins and fulfillment.   
2. Adding a product that is in BETA testing to an existing COMMERCIAL paid order is inaccurate accounting
3. The only way to grant the user permission is to COMPLETE the order, which unnecessarily sends email notification to the user, admins and fulfillment which is confusing.   
 
The feature for granting download permission to a product was available until just recently, and then removed by someone who doesn't think it's secure.  That is not true.  Granting permission is only available through strict admin access to specific accounts that must also have a License Key for authorization.   
 
Please re-instate granting download permission back into WooCommerce and Wordpress ASAP.

**Comment by mzpack** [comment]
That works. Thank you.
Another issue is that It downloads nothing if a link is set to a site page, but not to a file. I can see 'File not found. Go to shop' text after clicking download link.

**Comment by BonnieBeeman** [comment]
The fix is twelve key strokes, vs. three to simply grant access, but it seems to work.  
So far I don't see another email sent if if the Order was already completed, which is good. 
The ability to grant downloads to more than one user at a time would be great.

**Comment by BonnieBeeman** [comment]
No, this is not fixed.  User receives a secondary "Order Complete" once the Order is saved as Complete. 

Order status is essential for fulfillment to be managed correctly.  

Orders On Hold or Pending vs. Complete have different meaning and we don't want users getting confusing email

**Comment by maddentim** [comment]
I applied the patch from https://github.com/woocommerce/woocommerce/issues/29884#issuecomment-874227090 to our site and the downloadables functionality has been restored. Thank you. Looking forward to this commit getting released.

**Comment by pitchpublications** [comment]
So is there plans to restore this to the native WooCommerce?

**Comment by BonnieBeeman** [comment]
maddentim, where is the patch?  I see new code has been tested and approved for WooCommerce 5.6.

**Comment by maddentim** [comment]
@BonnieBeeman I made it from the https://github.com/woocommerce/woocommerce/issues/29884#issuecomment-874227090 commit. You will have to roll your own or wait for it to get released I guess.

**Comment by BonnieBeeman** [comment]
New code from 

> Here the fix to make this unsafe again: #29901

Thanks, this works as-expected and is very greatly appreciated.

**Comment by madnanbashir** [comment]
Same issue happening here. Need a solution

**Comment by maddentim** [comment]
> Same issue happening here. Need a solution

I am seeing the patch included in the Woocommerce 5.6.0 release. If you upgrade to it, you should be good to go. If you can upgrade for some reason, there is a patch in this thread that you could manually apply...
