### ISSUE TITLE
[GlobalStep] Incorrect Popup is displayed when user removes tax/Shipping/fee added on "Orders->Add Order" Page

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#29890]
## Bug Description:
Incorrect Popup saying "Are you sure you want to remove the selected items? You may need to manually restore the item's stock" is displayed when user removes tax/Shipping/fee added on "Orders->Add Orders" Page

## Test Instructions:
Critical Flow: Merchant->Orders->Can add new Order basic
https://href.li/?https://github.com/woocommerce/woocommerce/wiki/Critical-Flows

## Environment:
Woocommerce Version : WooCommerce 5.2.2 and 5.3
WooCommerce Admin: v2.2.6
WordPress version: (v5.7)

**PC:**
Windows 10, Mac 10.14.6
Chrome(Version 90.0.4430.93) 
Firefox(Version 88.0.1)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins 
1. Complete the onboarding setup wizard setup 
1. Complete "Get ready to start selling" section on WooCommerce->Home Page
1. Go to "Orders->Add Order" page
1. Click on "Add item (s)" button
1. Click on either one "Add fee/ Add shipping/ Add tax" button say you have added "Add fee"
1. Entered some fee amount say 10 and click on "Save" button
1. Click on "x" icon besides the fee you have just added to remove the added fee
1. Observe that incorrect popup stating "Are you sure you want to remove the selected items? You may need to manually restore the item's stock" is displayed when user removes added fee on "Orders->Add Order" Page

**Note:**
 "Are you sure you want to remove the selected items? You may need to manually restore the item's stock" popup is correct and meaningful when user removes a product that he just added via "Add item(s)-> Add Product(s)-><Product Name>->Add" 
 
## Actual Result:
Incorrect Popup is displayed when user removes tax/Shipping/fee added on "Orders->Add Order" Page

## Expected Result:
Correct Popup with meaningful message should be displayed when user removes tax/Shipping/fee added on "Orders->Add Order" Page

## Video:

https://user-images.githubusercontent.com/41110392/117998705-c6984680-b361-11eb-9b7a-d5903c585084.mov

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by claudiosanches** [comment]
Hello @gglobalstep,

Thanks for logging this issue, I can confirm that only one message is used to confirm before deleting any item, we need to insert sometime new to also make sense for taxes, shipping and fees.
