### ISSUE TITLE
Rest API: No way to find shipping zone based on an order

### ISSUE THREAD

**Issue by johnknoop** [woocommerce/woocommerce#29898]
Our customer is using table rate shipping.

Under the "Sweden" shipping zone, there are a bunch of methods with different `instance_id`s.

For any given order, the `instance_id` is present in the `shipping_lines`. But these instances live under a specific shipping zone, and there's no way to know which one from the information in the order alone.

The shipping address does contain the country code (SE in this case), but the shipping zone has no country code, it only has the name of the country--and not even in English but translated to whatever language the shop is using.

Is there a way to actually figure out the shipping zone from the order info, so that we can look up the instance (which contains the info we need about the actual shipping method)?

**Comment by juliaamosova** [comment]
Hi @johnknoop,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by roykho** [comment]
Hi there @johnknoop , unfortunately there is no shipping zone information on the return. As a work around, you can retrieve many different shipping information from the shipping REST end points. You can then compare the instance ID to what you get from the shipping list to know which shipping zones they are.  I hope that helps.
