### ISSUE TITLE
Need to add Meta in Product category properties

### ISSUE THREAD

**Issue by yusufhay** [woocommerce/woocommerce#29897]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by juliaamosova** [comment]
Hi @yusufhay,

Thank you for opening this feature request. However, it has very few details. Please provide us with a more comprehensive report that includes your expectations for the feature as well as the reason why you think it is important to add it. Thank you!
