### ISSUE TITLE
REST API : Querying Orders by meta_data key value

### ISSUE THREAD

**Issue by stousmand** [woocommerce/woocommerce#29899]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

I'm attempting to import WooCommerce Orders to my application (.Net) through invoking the `/orders` endpoint . I need to flag the order that I've already imported and to do so I thought of updating the order at the end by adding a meta_data to the order . Could I use something similar to `/order?status=processing&meta_data_field=is_imported&metadata_field_value=false` to query? Is there an alternative for something like this?

**Comment by juliaamosova** [comment]
Hi @stousmand,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by roykho** [comment]
Hi @stousmand - what you can do is use the WordPress core REST API such as the one here https://developer.wordpress.org/rest-api/reference/posts/#update-a-post

I hope that helps!

**Comment by stousmand** [comment]
@roykho Thanks for the response, updating the post is not the issue I have. Querying it as shown in the example. 

I found out that there are PHP wrappers to do that from the Wordpress/Woocommerce plugin end. I wanted to know if there is a way to query it via provided WooCommerce REST API because I couldn't find any documentation and thought I missed something.

**Comment by roykho** [comment]
Hi @stousmand - I see. We don't have any documented way for you to retrieve an order by a custom meta. However you can try using WP core REST endpoints which may work.

**Comment by stousmand** [comment]
Thanks @roykho , I'll check and see where it leads me to.
