### ISSUE TITLE
Feature request: REST API to include product attribute slug in products endpoint

### ISSUE THREAD

**Issue by stgoos** [woocommerce/woocommerce#29905]
**Is your feature request related to a problem? Please describe.**
When listing all products, the product attributes come without the product attribute slug (pa_...). This make is needlessly inconvenient to work with the right attribute as you now either need to know the attribute ID or use the name which could easily be changed by a shop manager over time while leaving the slug in tact.

**Describe the solution you'd like**
I like to see the product attribute slug included as well:
```
"attributes": [
      {
        "id": 6,
        "name": "Color",
        "slug": "pa_color",
```
Just like they are included when you list all the product attributes via that endpoint.

**Describe alternatives you've considered**
At the moment I maintain an extra array in my code which basically translates the product attribute slugs (37 and counting) into the respective ID. It works, but I prefer to be able to directly code against the slugs as that makes it much more friendly to maintain the code :)

**Additional context**
https://woocommerce.github.io/woocommerce-rest-api-docs/?php#list-all-products
https://woocommerce.github.io/woocommerce-rest-api-docs/?php#list-all-product-attributes

**Comment by juliaamosova** [comment]
Hi @stgoos,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by roykho** [comment]
Hi @stgoos - That information is unfortunately not available. However some work around as a suggestion is that you can assume the attributes are `pa_*`. Or you can make another REST call to the product attributes endpoint to match the ID you see.

I hope that helps!
