### ISSUE TITLE
Functionality bug in "Postcode / Zip Code" and "City" fields on Standard Tax rates page

### ISSUE THREAD

**Issue by Hugo-90** [woocommerce/woocommerce#29904]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
The "Postcode / ZIP" and "city" fields in the Standard Tax rates page do not work, I am trying to add taxes for California cities and adding specific values like SANTA ROSA, 95405, 95405, 94505 ... 95405, 94505; 95405 etc. in their respective field they do not reflect results in the calculation of the tax in any product. the only functionality they have is through the * symbol that generalizes the tax for all cities, so I cannot add different taxes for each city.

**Expected behavior**
I need to add the tax rate for each of the California cities in the United States due to it varies from city to city

**Actual behavior**
The tax calculation in the shopping cart shows $ 0 when a specific city or postcode is selected, but leaving the mentioned fields with * symbol (both) the rate is applied equally to all cities, but this does not help.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

1. Create any test site using Dokan plugin.
2. Install and activate all the required plugins
3. Complete the Onboarding setup wizard.
4. Go to WooCommerce->Settings->Tax.
5. Click on Standard rates.
6. Enter a specific value in the "postcode / Zip" and "City" fields (try with real values within the state of California, United States).
7. Click on "Save changes" button.
8. Create a vendor within Dokan by assigning the address established in the previous tax fields.
9. Create some products for this vendor
10. Enter the store as a customer, add products to the cart validating that the taxes are assigned according to the established places.
11. The problem is that these taxes have no effect

**Screenshots**

https://user-images.githubusercontent.com/58959891/118200983-0e7ba400-b41c-11eb-8258-171b20f2e352.mov

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
`
### WordPress Environment ###

WordPress address (URL): https://caniseethemenu.com
Site address (URL): https://caniseethemenu.com
WC Version: 5.3.0
REST API Version: ✔ 5.3.0
WC Blocks Version: ✔ 4.9.1
Action Scheduler Version: ✔ 3.1.6

WC Admin Version: ✔ 2.2.6
Log Directory Writable: ✔
WP Version: ❌ 5.6.4 - There is a newer version of WordPress available (5.7.2)
(❌*NOTE: I just downgraded the wordpress version for testing purposes, the error was and is reproduced in the version 5.5.2, 5.6.4 and 5.7.2 of Wordpress)
<img width="1252" alt="Screen Shot 2021-05-13 at 18 45 46" src="https://user-images.githubusercontent.com/58959891/118200742-78e01480-b41b-11eb-92c7-b7743f17ede8.png">
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.11
PHP Post Max Size: 32 MB
PHP Time Limit: 60
PHP Max Input Vars: 1000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.6.49-cll-lve
Max Upload Size: 32 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.0.0
WC Database Prefix: wp_
Total Database Size: 21.70MB
Database Data Size: 15.29MB
Database Index Size: 6.41MB
wp_woocommerce_sessions: Data: 0.04MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.09MB + Index: 0.05MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.04MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_comments: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_dokan_announcement: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_follow_store_followers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_dokan_orders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_dokan_product_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_refund: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_report_abuse_reports: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_dokan_rma_conversations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_rma_request: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_rma_request_product: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_shipping_zone_locations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_vendor_balance: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_dokan_withdraw: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_mobile_builder: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_mobile_builder_carts: Data: 2.09MB + Index: 0.11MB + Engine MyISAM
wp_options: Data: 2.78MB + Index: 0.30MB + Engine MyISAM
wp_postmeta: Data: 4.70MB + Index: 3.03MB + Engine MyISAM
wp_posts: Data: 3.00MB + Index: 0.54MB + Engine MyISAM
wp_pv_commission: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_rnlab_template_mobile: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_social_users: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_termmeta: Data: 0.12MB + Index: 0.11MB + Engine MyISAM
wp_terms: Data: 0.04MB + Index: 0.07MB + Engine MyISAM
wp_term_relationships: Data: 0.29MB + Index: 0.60MB + Engine MyISAM
wp_term_taxonomy: Data: 0.04MB + Index: 0.04MB + Engine MyISAM
wp_usermeta: Data: 0.11MB + Index: 0.05MB + Engine MyISAM
wp_users: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_user_registration_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.03MB + Index: 0.06MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.20MB + Index: 0.30MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_indexable: Data: 1.10MB + Index: 0.45MB + Engine MyISAM
wp_yoast_indexable_hierarchy: Data: 0.10MB + Index: 0.32MB + Engine MyISAM
wp_yoast_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_yoast_primary_term: Data: 0.15MB + Index: 0.17MB + Engine MyISAM
wp_yoast_seo_links: Data: 0.06MB + Index: 0.02MB + Engine MyISAM

### Post Type Counts ###

attachment: 256
blocks: 8
custom-css-js: 1
customize_changeset: 10
dokan_announcement: 1
dokan_store_reviews: 2
featured_item: 8
nav_menu_item: 10
page: 34
post: 4
product: 2947
product_variation: 694
revision: 439
shop_coupon: 1
shop_order: 14
user_registration: 2
wpcf7_contact_form: 6

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (21) ###

All-in-One WP Migration: by ServMask – 6.76
Classic Editor: by WordPress Contributors – 1.6
Contact Form 7: by Takayuki Miyoshi – 5.4
Delete Me: by Clinton Caldwell – 3.0
Dokan: by weDevs – 3.2.4
Dokan Pro: by weDevs – 3.2.2
GTranslate: by Translate AI Multilingual Solutions – 2.8.60
Jetpack by WordPress.com: by Automattic – 9.7
Loco Translate: by Tim Whitlock – 2.5.0
Mobile Builder: by Rnlab.io – 1.3.2
Nav Menu Roles: by Kathy Darling – 2.0.1
Nextend Social Login: by Nextendweb – 3.0.26
Really Simple SSL: by Really Simple Plugins – 4.0.13
Super Socializer: by Team Heateor – 7.13.16
Google Analytics and Google Tag Manager by WebKinder: by WebKinder – 1.9.3
WooCommerce Clover Payment Gateway by Zaytech: by Zaytech – 1.2.3
WooCommerce Shipping & Tax: by WooCommerce – 1.25.12
WooCommerce: by Automattic – 5.3.0
WooSidebars: by WooCommerce – 1.4.5
Yoast SEO: by Team Yoast – 15.9.1
WP Downgrade | Specific Core Version: by Reisetiger – 1.2.2

### Inactive Plugins (1) ###

Rnlap - App Control: by RNLAB – 1.2.3

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #64 - /productos/
Cart: #63 - /cart/
Checkout: #62 - /checkout/
My account: #61 - /my-account/
Terms and conditions: #893 - /terminos-y-condiciones/

### Theme ###

Name: Flatsome Child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.13.1
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product-cat.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
flatsome/woocommerce/single-product/product-image.php
flatsome/woocommerce/single-product/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome/woocommerce/single-product-reviews.php
flatsome/woocommerce/single-product.php
flatsome/woocommerce/content-product_cat.php

### Action Scheduler ###

Complete: 311
Oldest: 2021-04-13 18:10:50 +0000
Newest: 2021-05-13 19:31:54 +0000

### Status report information ###

Generated at: 2021-05-13 16:40:11 -07:00
`
</details>

**Comment by zhongruige** [comment]
Hi @Hugo-90,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. I tested on:

* WooCommerce 5.3.0
* WordPress 5.7.2
* Twenty Twenty-one theme

### Replication steps

* I setup a new WooCommerce installation and imported the default products
* I navigated to `WooCommerce > Settings > Tax` and configured the following taxes with specific zip codes and cities:

<img width="1548" alt="Screen Shot 2021-05-19 at 8 42 36 AM" src="https://user-images.githubusercontent.com/71906536/118834977-d642ee00-b87f-11eb-94c0-0df4b46539b0.png">

* I proceeded to the store a tried a variety of combinations, and in each case, the tax was applied as expected:

<img width="627" alt="Screen Shot 2021-05-18 at 4 01 32 PM" src="https://user-images.githubusercontent.com/71906536/118847140-a9e09f00-b88a-11eb-96b3-1e9838198266.png">
<img width="662" alt="Screen Shot 2021-05-18 at 4 01 44 PM" src="https://user-images.githubusercontent.com/71906536/118847143-a9e09f00-b88a-11eb-9390-d090e14568e7.png">
<img width="655" alt="Screen Shot 2021-05-18 at 4 02 05 PM" src="https://user-images.githubusercontent.com/71906536/118847144-aa793580-b88a-11eb-96bb-17ad76f9751c.png">

* I then added in a new location and refresh the page with the city/state zip that matched:

https://user-images.githubusercontent.com/71906536/118847297-d4325c80-b88a-11eb-86fa-30d1c0d1f22c.mov

Please provide us with more details about the issue, or if I missed a step above, which may help us to evaluate it further. For example, does this behavior also occur when not using Dokan? Most likely the issue you are having is could be related to Dokan. I would recommend contacting the author of the plugin directly for further help.

**Comment by Hugo-90** [comment]
Hi,
In fact, I was able to evaluate that the problem is not due to the "PostCode" and "City" fields. I realized that requesting to send to any part of the United States the tax is calculated correctly and I found that the problem is only for the calculation in the state of California, even when typing * in the fields of "country code" and "code of State".


https://user-images.githubusercontent.com/58959891/119034268-cc9ab280-b973-11eb-8527-35d4e3013ea5.mov


I think that if you try to test with the state of California you will be able to reproduce the error.

Greetings and thanks for responding.

**Comment by Hugo-90** [comment]
Hello,
Of course these are my current settings:

<img width="1278" alt="Screen Shot 2021-05-21 at 9 36 50" src="https://user-images.githubusercontent.com/58959891/119155105-716ecb80-ba18-11eb-9855-1b237ea4dedd.png">

<img width="1278" alt="Screen Shot 2021-05-21 at 9 38 46" src="https://user-images.githubusercontent.com/58959891/119155023-5bf9a180-ba18-11eb-9d98-7d38105a10a8.png">

**Comment by Hugo-90** [comment]
I think I found something useful,
The tax is not calculated in local pickups, but if delivery option is enabled it works, would you know how to include taxes in local pickups?

local:
<img width="596" alt="Screen Shot 2021-05-21 at 11 37 25" src="https://user-images.githubusercontent.com/58959891/119170502-ec3fe280-ba28-11eb-9ace-43538f6c0767.png">

flat rate:
<img width="596" alt="Screen Shot 2021-05-21 at 11 42 06" src="https://user-images.githubusercontent.com/58959891/119170970-94ee4200-ba29-11eb-9b70-f23eb5d416c3.png">

**Comment by zhongruige** [comment]
Ah good find @Hugo-90! That helped a lot :)

> The tax is not calculated in local pickups, but if delivery option is enabled it works, would you know how to include taxes in local pickups?

Yes! So, for a little background on what is happening here:

* By default, taxes are based off of the store base taxes:

<img width="1292" alt="Screen Shot 2021-05-21 at 1 32 38 PM" src="https://user-images.githubusercontent.com/71906536/119189364-37fa8800-ba39-11eb-80a5-79d658bb5782.png">

So, what this means in practice is you need a tax zone set up for where you store is located. Once doing so, the taxes will be calculated properly based on that. Here's how I have it set up, for example:

* Standard rate taxes:

<img width="1551" alt="Screen Shot 2021-05-21 at 1 36 39 PM" src="https://user-images.githubusercontent.com/71906536/119189786-b5be9380-ba39-11eb-97f5-32dd5b4e02d8.png">

* Store address:

<img width="684" alt="Screen Shot 2021-05-21 at 1 37 02 PM" src="https://user-images.githubusercontent.com/71906536/119189796-b9521a80-ba39-11eb-9262-e31c68519076.png">

* Tax costs are calculated correctly, here, when the city/zip (thus "local") are selected matching the store's:

<img width="861" alt="Screen Shot 2021-05-21 at 1 37 10 PM" src="https://user-images.githubusercontent.com/71906536/119189918-e56d9b80-ba39-11eb-91e1-4328ceb278ad.png">

Based on the above, I would guess that you don't have taxes set for the city and zip for where your store is based. So, going off of the example, your store address would need to be something like:

123 Main Street
Santa Rosa, CA, 95405

Then, at checkout, the taxes would be calculated properly.

If this is not the desired behavior, this can be overridden by following [these instructions](https://docs.woocommerce.com/document/local-pickup/). Let me know if this helps or if you have any further questions!

**Comment by Hugo-90** [comment]
It has been solved!

As you said, by default taxes are based off of the store base taxes, so I realized that when you are using dokan you should not use the worpress address, instead you should use the address of each of your vendors (I have not configured an address for wordpress - woocommerce, this makes the tax $ 0). Therefore, within the vendor dashboard in dokan a new shipping rate has to be configured, but this time assigning a cost of $ 0 for local pickup, in this way wordpress will take the vendor's address and not that of woocommerce - configuration - general .

<img width="842" alt="Screen Shot 2021-05-26 at 18 44 13" src="https://user-images.githubusercontent.com/58959891/119744795-5f46c000-be52-11eb-95f1-5942fac0832b.png">

<img width="842" alt="Screen Shot 2021-05-26 at 18 46 12" src="https://user-images.githubusercontent.com/58959891/119744916-a634b580-be52-11eb-9549-5672f1a4b663.png">

<img width="842" alt="Screen Shot 2021-05-26 at 18 43 46" src="https://user-images.githubusercontent.com/58959891/119744770-50f8a400-be52-11eb-93fa-af71cb6bac93.png">


Thank you a lot for your support.

Best regards!!

**Comment by zhongruige** [comment]
Very happy to help @Hugo-90!

I will go ahead and close this issue for now, but please feel free to leave a comment if there's anything else we missed or can further look into.

Have a great rest of your day!
