### ISSUE TITLE
Missing address field error at the checkout.

### ISSUE THREAD

**Issue by negapo** [woocommerce/woocommerce#29925]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Hi, we only sell to one country, "Portugal", so we have:

WooCommerce -> Settings -> General -> Sell To Specific Countries
And on the Option below that we have selected "Portugal"

We also have on the "Default Customer Address" selected the option "Store Base Address". At the checkout, because we only sell to Portugal we have unset the two fields for country on the "woocommerce_checkout_fields" hook:

	unset($fields['billing']['billing_country']);
	unset($fields['shipping']['shipping_country']);

This always worked fine, although when a registered user made a purchase the Billing and Shipping address would be registered in the "User" section without a country, but this posed no problem, the next time they made a purchase, on the checkout, Woo would assume Portugal as the country, following the "Default Customer Address" rule for the country.

This has changed on the last update, if we do unset the country field, for registered users who have checkout previously and have no country set on their accounts, Woo would not let them checkout saying that the address is incomplete, also, the shipping rate is the default shipping rate and not the one for Portugal.
If we comment out the unset and show the form field for the country everything works fine.
We cannot understand what has changed and if this is the excpected behavior. 

Any help if much appreciated. Thanks

**Comment by rodelgc** [comment]
Hi @negapo,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by rodelgc** [comment]
Hi @negapo,

Also if you're comfortable sharing with us your hook to help us replicate the issue more accurately, that would be nice.

**Comment by Konamiman** [comment]
Hi @negapo. Unsetting default checkout fields is not recommended, it could have adverse effects since plugins like payment gateways will be expecting it. Is there any reason why you want to unset those once you have set the "Sell To Specific Countries" setting?

**Comment by negapo** [comment]
Hi,
Thanks for taking a look @Konamiman and sorry @rodelgc i didn't saw your edit.
I'm using the  'woocommerce_checkout_fields' filter

Example:
`function custom_function( $fields ) {	
    unset($fields['billing']['billing_country']);
    unset($fields['shipping']['shipping_country']);
    return $fields;
}
add_filter( 'woocommerce_checkout_fields' , 'custom_function' );`

It's just a matter of UX, having a ComboBox (a mean to select from multiple fields) with just one field looks unnecessary.
I was also curious because this worked and something changed in the way Woo fills this field.

I do understand that unchecking default fields in the checkout may cause problems with payment gateways and shipping plug-ins but some flexibility is great, like for example, some stores would use just a field for "Name" instead of "First Name" and "Last Name", some wouldn't want the two fields for address and would be happy in just using one, in some cases the email address field would not be needed like when using POS plug-ins, and so on, but i know its difficult to accommodate this.

Just a question, what are the default and optional fields? For example, is the "Last Name" an optional field?
Thanks

**Comment by jeffstieler** [comment]
@negapo instead of using the `woocommerce_checkout_fields` filter and `unset()` to remove checkout fields, you should be able to use CSS to hide the fields. This should avoid the missing field errors. (Use the `#shipping_country` and `#billing_country` selectors to hide the fields with `display: none;`)

If that's not a feasible approach, you'll need to pair your existing filter with another on `woocommerce_checkout_posted_data` to ensure there are values for `$fields['billing']['billing_country']` and `$fields['shipping']['shipping_country']`.
