### ISSUE TITLE
woocommerce-blocks package

### ISSUE THREAD

**Issue by dwd010** [woocommerce/woocommerce#29922]
Yo, I downloaded your plugin with a theme on Wordpress. I want to change my frontpage, but it is saying this:

Missing the WooCommerce woocommerce-blocks package
Your installation of WooCommerce is incomplete. If you installed WooCommerce from GitHub, please refer to this document to set up your development environment.

How can i fix it? 

Here the photo: 
![image](https://user-images.githubusercontent.com/82138099/118409500-06756b80-b68b-11eb-84b5-64a985eeefe7.png)

CodingTopia

**Comment by Johnny99211** [comment]
Have you followed the instructions from the link in the message?

**Comment by juliaamosova** [comment]
Hi @dwd010,

Thank you for submitting the issue. Can you please provide us with details of how exactly did you install the plugin? Have you downloaded it from GitHub? Or some other place?

Please provide us with more details about the issue which may help us to evaluate it further.
