### ISSUE TITLE
"Create variations from all attributes" for >50 variations creates the same first 50 variations again and again

### ISSUE THREAD

**Issue by Holzhauer** [woocommerce/woocommerce#29932]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
After upgrading to woocommerce 5.3.0, choosing "Create variations from all attributes" and pressing "Go" button /under Products > Product data > Variations) for a variable product with more than 50 combinations of attributes results in creating the same first 50 variations again when pressing "Add variation" again.

**Expected behavior**
Choosing "Create variations from all attributes" and pressing "Go" button a second time should create variations 51 to 100, a third time 101 to 150 and so on.

**Actual behavior**
Choosing "Create variations from all attributes" and pressing "Go" button a second time creates variations 1 to 50, a third time 1 to 50 and so on.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Add two attributes with both more than seven terms.
2. For a variable product, add these two attributes and save.
3. Choose "Create variations from all attributes" and press "Go" button once. Confirm.
4. After variations 1 to 50 have been created, choose "Create variations from all attributes" and press "Go" button again. Confirm.

**Screenshots**
-

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): http://www.dirtychurchrun.de
Site address (URL): http://www.dirtychurchrun.de
WC Version: 5.3.0
REST API Version: ✔ 5.3.0
WC Blocks Version: ✔ 4.9.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.2.6
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 384 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.14
PHP Post Max Size: 128 MB
PHP Time Limit: 180
PHP Max Input Vars: 2000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.3.0
WC Database Prefix: wp_
Total Database Size: 12.25MB
Database Data Size: 9.60MB
Database Index Size: 2.65MB
wp_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_blc_filters: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_blc_instances: Data: 0.03MB + Index: 0.01MB + Engine MyISAM
wp_blc_links: Data: 0.25MB + Index: 0.03MB + Engine MyISAM
wp_blc_synch: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_booking: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_bookingdates: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_downloadstats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_downloadtracking: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 0.96MB + Index: 0.09MB + Engine MyISAM
wp_postmeta: Data: 3.66MB + Index: 1.18MB + Engine MyISAM
wp_posts: Data: 3.92MB + Index: 0.37MB + Engine MyISAM
wp_sendpress_autoresponders: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_sendpress_connections: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_sendpress_customfields: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_sendpress_list_subscribers: Data: 0.03MB + Index: 0.11MB + Engine MyISAM
wp_sendpress_queue: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wp_sendpress_schedules: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_sendpress_subscribers: Data: 0.06MB + Index: 0.06MB + Engine MyISAM
wp_sendpress_subscribers_meta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_sendpress_subscribers_status: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_sendpress_subscribers_tracker: Data: 0.07MB + Index: 0.06MB + Engine MyISAM
wp_sendpress_subscribers_url: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_sendpress_url: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.03MB + Index: 0.06MB + Engine MyISAM
wp_term_taxonomy: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_usermeta: Data: 0.03MB + Index: 0.03MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.03MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wonderplugin_slider: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 239
customize_changeset: 1
custom_css: 1
efbl_skins: 9
flamingo_contact: 953
flamingo_inbound: 1111
foogallery: 8
mif_skins: 3
nav_menu_item: 27
page: 59
post: 15
product: 5
product_variation: 165
revision: 482
sendpress_list: 11
shop_coupon: 1
shop_order: 35
sptemplates: 3
sp_newsletters: 13
sp_report: 33
sp_settings: 3
sp_template: 16
wpcf7_contact_form: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (28) ###

Antispam Bee: by pluginkollektiv – 2.9.4
Better Search Replace: by Delicious Brains – 1.3.4
Booking Calendar: by wpdevelop
oplugins – 8.8.1

Broken Link Checker: by WPMU DEV – 1.11.15
Checkout Files Upload for WooCommerce: by WP Wham – 2.1.0
Contact Form 7: by Takayuki Miyoshi – 5.4.1
dbr3 Race Result include: by Dittberner & Strokosch GbR – 1.0.1
Disable Comments: by WPDeveloper – 2.1.1
DNUI: by Nicearma – 2.5.7
Easy Social Feed: by Easy Social Feed – 6.2.3
Flamingo: by Takayuki Miyoshi – 2.2.1
FooBox Image Lightbox: by FooPlugins – 2.7.16
FooGallery: by FooPlugins – 2.0.30
GDPR Tools: by Vladimir Radnaev – 1.0.2
jQuery T(-) Countdown Widget: by twinpictures
baden03 – 2.3.22.1

NS Featured Posts: by Nilambar Sharma – 2.0.2
PDF Thumbnails: by Stian Liknes – 2.2.0
Posts in Page: by IvyCat
Inc. – 1.4.4

Redirector: by Ralf Hortt – 3.0.1
Simple Revisions Delete by bweb: by Brice CAPOBIANCO – 1.5.1
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.16.56

Advanced Order Export For WooCommerce: by AlgolPlus – 3.1.8
WooCommerce Stripe Gateway: by WooCommerce – 5.1.0
WooCommerce Simply Order Export: by Ankit Gade – 3.0.13
WooCommerce: by Automattic – 5.3.0
WordPress HTTPS: by Mike Ems – 3.4.0
WP Mail SMTP: by WPForms – 2.8.0
WP-Sweep: by Lester 'GaMerZ' Chan – 1.1.3

### Inactive Plugins (1) ###

SendPress Newsletters: by SendPress – 1.21.4.5

### Settings ###

API Enabled: ✔
Force SSL: ✔
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #3726 - /2021-2/24hr/
Cart: #578 - /service/shop/reservierungen/
Checkout: #579 - /service/shop/auschecken/
My account: #580 - /service/shop/mein-konto/
Terms and conditions: #4386 - /24h-cr-teilnahmebedingungen/

### Theme ###

Name: Modern
Version: 2.4.3 (update to version 2.4.4 is available)
Author URL: https://www.webmandesign.eu/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Checkout Files Upload Settings ###

WooCommerce Checkout Files Upload: yes
Total file uploaders: 1
Form extras: yes
Enable alert on successful file upload: yes
Enable alert on successful file remove: no
Max file size: 1
alg_checkout_files_upload_max_file_size_exceeded_message: Zulässige Dateigröße überschritten (maximal %max_file_size% MB).
Attach files to admin's new order emails: yes
Attach files to customer's processing order emails: no
Send additional email to admin on user actions: Array
(
)
Attach file on upload action: yes
Recipient(s): (set)
Subject: [{site_title}] Checkout files upload action in customer order ({order_number}) - {order_date}
Email heading: {action}: File #{file_num}
Email content: File name: {file_name}
Action: File removed: File removed
Action: File uploaded: File uploaded
Before: Label:
					 
					%field_label%%required_html%
				
												
					Field Container:
					 
					%button_html% %field_html%
				
												
					Uploaded File:
					 
					%image% %file_name% %remove_button%
				
												
					After:
Label: 
%field_label%%required_html%: 
Field Container: 
%button_html% %field_html%: 
Uploaded File: %image% %file_name% %remove_button%
After: 
"Delete" button style: color:red;
Image style: width:64px;
Enable/disable: yes
Required: yes
Accepted file types: .ods,.xls.,xlsx,.csv
Validate image dimensions: 
Width: 1
Height: 1
Checkout page: woocommerce_after_checkout_form
Position order (i.e. priority): 20
"Thank You" page: no
"My Account" page: no
Label: Bitte wähle die Tabelle mit Staffelmitgliedern.
Upload button (single): Datei wählen
Wrong file type: Falsche Datentyp: "%s"
Wrong image dimensions: Wrong image dimensions for "%s". Current: %current_width% x %current_height%. Required: %required_width% x %required_height%.
Couldn't get image dimensions: Couldn't get image dimensions: "%s"
File is required: File is required.
File was successfully uploaded: File "%s" was successfully uploaded.
File was successfully removed: File "%s" was successfully removed.
Require products: Array
(
    [0] => 3773
)
Require product categories: Array
(
)
Require product tags: Array
(
)
Label: 
%field_label%%required_html%: 
Field Container: 
%button_html% %field_html%: 
Uploaded File: %image% %file_name% %remove_button%
After: 

### Action Scheduler ###

Complete: 86
Oldest: 2021-04-19 20:22:32 +0200
Newest: 2021-05-17 16:55:21 +0200

### Status report information ###

Generated at: 2021-05-18 08:17:13 +02:00
`
</details>

**Comment by zhongruige** [comment]
Hi @Holzhauer,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. I tested this on:

* WooCommerce 5.3.0
* WordPress 5.7.2

### Replication steps

* I set up a new WooCommerce site and imported the sample products
* For the two Attributes, I made sure there were at least 7 terms for each:

<img width="889" alt="Screen Shot 2021-05-18 at 11 05 59 AM" src="https://user-images.githubusercontent.com/71906536/118698072-39c01380-b7cd-11eb-9b13-6dd81f909624.png">

* Next, I created a new variable product and added the two Attributes and checked the box to use them for variations
* In the dropdown I clicked "Create variations from all attributes" and verified 50 were added:

<img width="1236" alt="Screen Shot 2021-05-18 at 11 22 16 AM" src="https://user-images.githubusercontent.com/71906536/118698337-80ae0900-b7cd-11eb-9a77-25812909bb8c.png">

<img width="979" alt="Screen Shot 2021-05-18 at 11 22 26 AM" src="https://user-images.githubusercontent.com/71906536/118698350-84419000-b7cd-11eb-8666-cd86303987d1.png">

* Next, I followed the same steps and in the dropdown I clicked "Create variations from all attributes". This time, 6 more were added as expected:

<img width="447" alt="Screen Shot 2021-05-18 at 11 17 39 AM" src="https://user-images.githubusercontent.com/71906536/118698421-9a4f5080-b7cd-11eb-9480-ffc2bb84c9e5.png">

I ran through the steps above a few times and in each case 56 variations were created.

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
﻿
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Please provide us with more details about the issue which may help us to evaluate it further. Thank you!

**Comment by Holzhauer** [comment]
Thanks, Greg!
I tried again and realised it works when I remove the attributes from the product and add them again. I'm sorry for the effort I caused. However, after the upgrade to woocommerce 5.3.0 the generation with the same attributes that had worked before didn't work anymore without this work-around... Of course, it might be related to my specific context...

**Comment by zhongruige** [comment]
Thank you for following up @Holzhauer!

No worries at all, I'm very happy to help take a look :)

I wanted to check to see if it was a problem deleting all of the attributes then re-adding them:

<img width="554" alt="Screen Shot 2021-05-19 at 2 18 52 PM" src="https://user-images.githubusercontent.com/71906536/118878787-2e441980-b8ad-11eb-872d-0268cd9f8822.png">

Similarly they didn't duplicate when re-adding them. However, if there's anything else we can help look into feel free to reply in a comment and let us know. Thanks!
