### ISSUE TITLE
Custom Order Statuses break if IDs over 20 characters in length

### ISSUE THREAD

**Issue by MichaelPote** [woocommerce/woocommerce#29934]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Custom order statuses with an id length of more than 20 characters are unable to be set by orders. They show up in the list of available statuses but when trying to change an order's status to one, the order will be saved, the order note "Status changed from x to y" is generated, but the order's status remains on the old status. 

**Expected behavior**
Setting the status of an order should always result in the order's status changing, or an error message. Neither of these happen.

**Actual behavior**
When trying to change an order's status to a custom created status with an id of more than 20 characters, the order will be saved successfully and the order note "Status changed from x to y" is generated, but the order's status remains on the old status. 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
1. On the 'init' action, register a new custom post status of more than 20 characters. For example:

``` 
  add_action('init', function(){
   register_post_status('wc-abcdefghijklmnopqr', array(
			'label' => 'A very long post status',
			'public' => false,
			'publicly_queryable' => false,
			'show_in_admin_status_list' => true,
			'internal' => true,
			'label_count' => _n_noop( 'Very long status <span class="count">(%s)</span>',  'Very long status <span class="count">(%s)</span>' ),
			));
			
   register_post_status('wc-abcdefghijklmnopq', array(
			'label' => 'An okay post status',
			'public' => false,
			'publicly_queryable' => false,
			'show_in_admin_status_list' => true,
			'internal' => true,
			'label_count' => _n_noop( 'Okay status <span class="count">(%s)</span>',  'Okay status <span class="count">(%s)</span>' ),
			));
    });
```

2. Edit any order on the backend
3. Set the order's post status to "A very long post status"
4. You will see the order will not change statuses but the order will be saved successfully and the post transition order note is created.
5. Set the order's post status to "An okay post status"
6. You will see the order status will be correctly changed.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>

`
### WordPress Environment ###

WordPress address (URL): https://***
Site address (URL): https://***
WC Version: 4.7.0
REST API Version: ✔ 4.7.0
WC Blocks Version: ✔ 3.6.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.6.3
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.18
PHP Post Max Size: 512 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 7.58.0
OpenSSL/1.1.1

SUHOSIN Installed: –
MySQL Version: 5.7.34-0ubuntu0.18.04.1
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.7.0
WC Database Prefix: wp_
Total Database Size: 688.46MB
Database Data Size: 404.51MB
Database Index Size: 283.95MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 11.52MB + Index: 6.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 79.63MB + Index: 77.20MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 13.52MB + Index: 12.48MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 6.52MB + Index: 5.28MB + Engine InnoDB
wp_brave_importer_items: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 13.52MB + Index: 10.09MB + Engine InnoDB
wp_failed_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 6.52MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 8.48MB + Index: 1.58MB + Engine InnoDB
wp_postmeta: Data: 119.64MB + Index: 78.25MB + Engine InnoDB
wp_posts: Data: 32.52MB + Index: 5.02MB + Engine InnoDB
wp_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_redirection_404: Data: 1.02MB + Index: 0.16MB + Engine InnoDB
wp_redirection_groups: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_redirection_items: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_redirection_logs: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_relevanssi: Data: 0.20MB + Index: 0.41MB + Engine InnoDB
wp_relevanssi_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sbi_instagram_feeds_posts: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_feed_locator: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_sbi_instagram_posts: Data: 0.17MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
wp_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 49.58MB + Index: 48.16MB + Engine InnoDB
wp_users: Data: 4.52MB + Index: 4.55MB + Engine InnoDB
wp_vendsync: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_vendsync_cache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 3.52MB + Index: 3.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 8.52MB + Index: 11.06MB + Engine InnoDB
wp_wc_order_stats: Data: 2.52MB + Index: 3.47MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 1.52MB + Index: 0.77MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.06MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wdap_backups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wdap_collection: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblockediplog: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfblocks7: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wfconfig: Data: 1.33MB + Index: 0.00MB + Engine InnoDB
wp_wfcrawlers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilechanges: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wffilemods: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_wfhits: Data: 1.52MB + Index: 0.22MB + Engine InnoDB
wp_wfhoover: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfknownfilelist: Data: 2.52MB + Index: 0.00MB + Engine InnoDB
wp_wflivetraffichuman: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wflocs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wflogins: Data: 0.45MB + Index: 0.17MB + Engine InnoDB
wp_wfls_2fa_secrets: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wfls_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfnotifications: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfpendingissues: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wfreversecache: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wfsnipcache: Data: 0.13MB + Index: 0.17MB + Engine InnoDB
wp_wfstatus: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
wp_wftrafficrates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 16.55MB + Index: 12.58MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.42MB + Index: 0.58MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 1.52MB + Index: 0.77MB + Engine InnoDB
wp_yoast_seo_meta: Data: 5.52MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 13
acf-field-group: 3
attachment: 390
carousels: 68
delivery-area: 12
gift_card: 296
karens-list: 15
nav_menu_item: 34
oembed_cache: 15
page: 21
portfolio-item: 33
post: 11
product: 125
product_variation: 168
revision: 1005
shop_coupon: 88
shop_order: 33063
shop_order_refund: 18
slides: 3
store: 12
testimonials: 15
warehouse: 4
woo_mb_template: 13
wpcf7_contact_form: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (28) ###

Advanced Custom Fields: by Elliot Condon – 5.9.5
Brave External Plugins: by Brave Digital –
Classic Editor: by WordPress Contributors – 1.6
Contact Form 7: by Takayuki Miyoshi – 5.4.1
Yoast Duplicate Post: by Enrico Battocchi & Team Yoast – 4.1.2
Members: by MemberPress – 3.1.5
Metrilo for WooCommerce: by Metrilo – 1.7.21 – Installed version not tested with active version of WooCommerce 4.7.0
Relevanssi: by Mikko Saari – 4.13.1
reSmush.it Image Optimizer: by reSmush.it – 0.4.1
Safe SVG: by Daryll Doyle – 1.9.9
SearchWP Live Ajax Search: by SearchWP
LLC – 1.6.1

Page Builder by SiteOrigin: by SiteOrigin – 2.12.1
SiteOrigin Widgets Bundle: by SiteOrigin – 1.18.2
Brave Vend Sync: by Brave Digital – 1.0.0
WooCommerce Peach Payments Gateway: by Peach Payments – 2.0.2 – Installed version not tested with active version of WooCommerce 4.7.0
Advanced Order Export For WooCommerce: by AlgolPlus – 3.1.8
WooCommerce SnapScan Gateway: by WooCommerce – 1.1.10 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce Twilio SMS Notifications: by SkyVerge – 1.15.1 – Installed version not tested with active version of WooCommerce 4.7.0
WooCommerce: by Automattic – 4.7.0 (update to version 5.3.0 is available)
WooCommerce Email Customizer with Drag and Drop Email Builder: by Flycart Technologies LLP – 1.5.12 – Installed version not tested with active version of WooCommerce 4.7.0
Wordfence Security: by Wordfence – 7.5.3
Yoast SEO: by Team Yoast – 16.2
WP Mail SMTP: by WPForms – 2.8.0
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.1.9

ReCaptcha v2 for Contact Form 7: by IQComputing – 1.3.3
YITH WooCommerce Gift Cards Premium: by YITH – 3.1.13
YITH WooCommerce Multi-step Checkout Premium: by YITH – 2.0.6
Zapper Payments for WooCommerce: by Zapper Development – 2.1.3 – Installed version not tested with active version of WooCommerce 4.7.0

### Inactive Plugins (10) ###

Action Scheduler High Volume: by Prospress Inc. – 1.1.0
BackupBuddy: by iThemes – 8.7.2.0
Better Search Replace: by Delicious Brains – 1.3.4
Facebook for WooCommerce: by Facebook – 2.4.1
Mailchimp for WooCommerce: by Mailchimp – 2.5.1
PW WooCommerce Bulk Edit: by Pimwick
LLC – 2.87

Redirection: by John Godley – 5.1.1
Smash Balloon Instagram Feed: by Smash Balloon – 2.9.1
WP All Import - WooCommerce Add-On Pro: by Soflyy – 3.2.4 – Installed version not tested with active version of WooCommerce 4.7.0
WP All Import Pro: by Soflyy – 4.6.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: ZAR (R)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: bundle (bundle)
external (external)
gift-card (gift-card)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #11 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: ***
Version: 1.0.0
Author URL: https://www.bravedigital.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: ***/woocommerce/archive-product.php
***/woocommerce/cart/cart-shipping.php
***/woocommerce/cart/cart-totals.php
***/woocommerce/cart/cart.php
***/woocommerce/cart/proceed-to-checkout-button.php
***/woocommerce/cart/shipping-calculator.php
***/woocommerce/checkout/form-billing.php
***/woocommerce/checkout/form-pay.php
***/woocommerce/checkout/form-shipping.php
***/woocommerce/checkout/payment.php
***/woocommerce/checkout/review-order.php
***/woocommerce/content-product.php
***/woocommerce/global/breadcrumb.php
***/woocommerce/global/form-login.php
***/woocommerce/global/quantity-input.php
***/woocommerce/global/sidebar.php
***/woocommerce/global/wrapper-end.php
***/woocommerce/global/wrapper-start.php
***/woocommerce/loop/loop-end.php
***/woocommerce/loop/loop-start.php
***/woocommerce/loop/no-products-found.php
***/woocommerce/loop/orderby.php
***/woocommerce/myaccount/dashboard.php
***/woocommerce/myaccount/form-edit-account.php
***/woocommerce/myaccount/form-edit-address.php
***/woocommerce/myaccount/form-login.php
***/woocommerce/myaccount/form-lost-password.php
***/woocommerce/myaccount/form-reset-password.php
***/woocommerce/myaccount/lost-password-confirmation.php
***/woocommerce/myaccount/my-address.php
***/woocommerce/myaccount/orders.php
***/woocommerce/myaccount/view-order.php
***/woocommerce/order/order-details-customer.php
***/woocommerce/order/order-details-item.php
***/woocommerce/order/order-details.php
***/woocommerce/single-product.php

### Action Scheduler ###

Complete: 36,332
Oldest: 2021-05-17 09:38:38 +0200
Newest: 2021-05-18 15:00:33 +0200

Failed: 2,136
Oldest: 2020-05-17 08:57:56 +0200
Newest: 2021-05-13 09:57:00 +0200

Pending: 5
Oldest: 2021-05-18 15:42:11 +0200
Newest: 2021-05-19 01:08:24 +0200

`

</details>

**Comment by rrennick** [comment]
@MichaelPote The field length for a post status in WordPress is 20 characters. See https://codex.wordpress.org/File:WP4.4.2-ERD.png

Closing this as it is a limitation of the WordPress database schema.
