### ISSUE TITLE
Export function "get_percent_complete"

### ISSUE THREAD

**Issue by Elidone** [woocommerce/woocommerce#29954]
woocommerce\includes\export\abstract-wc-csv-batch-exporter.php:145
> 	/**
	 * Get total % complete.
	 *
	 * @since 3.1.0
	 * @return int
	 */
	public function get_percent_complete() {
		     return $this->total_rows ? floor( ( $this->get_total_exported() / $this->total_rows ) * 100 ) : 100;
	}

must return int, but `floor` return float.

woocommerce\includes\export\abstract-wc-csv-batch-exporter.php:101

> 		if ( 100 === $this->get_percent_complete() ) {
if integer 100 identical with float 100. identical and they are of the same type. its impossible. 

So, 146 line must be

> return $this->total_rows ? (int)floor( ( $this->get_total_exported() / $this->total_rows ) * 100 ) : 100;

     or

> return $this->total_rows ? intval(floor( ( $this->get_total_exported() / $this->total_rows ) * 100 )) : 100;

**Comment by zhongruige** [comment]
Hi @Elidone,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by roykho** [comment]
Hi @Elidone

Would you perhaps like to submit a PR for this for us to review?

**Comment by rabbihossain** [comment]
Since OP is not active or not answering this thread. I thought I could send a PR.

**Comment by Elidone** [comment]
> Since OP is not active or not answering this thread. I thought I could send a PR.

Thx
