### ISSUE TITLE
wp-options database table bloated due to transients!

### ISSUE THREAD

**Issue by Kan1221** [woocommerce/woocommerce#29975]
As I'm facing database table bloated due to transients, it's almost 40GB wp-options table. 
As my suggestion can save transients in a file instead of saving in wp-options in a readable format. as it impacts site speed and other server things too. 
https://www.awesomescreenshot.com/image/8568769?key=b9e838b73721b40e0cffebcf6a12f5d5

Thank you!!

**Comment by DavidAnderson684** [comment]
See: https://github.com/woocommerce/woocommerce/issues/29869

**Comment by rrennick** [comment]
> See: #29869

@DavidAnderson684 Transients are not autoloaded options.

@Kan1221 WordPress has a daily cron job to clear expired transients. If most of the records in your options table are transient records then it is most likely that the cron job is failing. I'll leave this open for follow up, but based on the info provided this does not look to be a WC specific issue.

**Comment by claudiosanches** [comment]
@rrennick note that #29869 is a confirmed bug that will fill the `wp_options` with many autoloaded options. Both could be related, since a large `wp_options` table will cause issues for other things as well.

**Comment by Kan1221** [comment]
@claudiosanches Yes its impacts the whole site, by the way, I am working on a custom function for delete transition.

**Comment by claudiosanches** [comment]
@Kan1221 I have done one already as I mentioned https://gist.github.com/claudiosanches/0623c3ba253efb9a98c552e646ee7116

Could you share more details about what are the entries, like what transients and how many? Note that `woocommerce_rate_limit_*` isn't a transient, and we are going to patch it soon.
