### ISSUE TITLE
JS console error when adding a new shipping zone

### ISSUE THREAD

**Issue by roykho** [woocommerce/woocommerce#29984]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When trying to add a shipping zone, I see a JS console error.

**Expected behavior**
There shouldn't be any JS console errors. 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create a new site on Jurassic Ninja.
2. Install WC and go through the OBW setup.
3.  Go to /wp-admin/admin.php?page=wc-settings&tab=shipping&section
4. Open your browser's JS console.
5. Click on the purple `Add Shipping Zone` button as seen below.
6. Witness a JS error is logged `Uncaught TypeError: ((S.event.special[o.origType] || {}).handle || o.handler).apply is not a function`

**Screenshots**
![](https://d.pr/i/G0IiHJ+)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WP 5.7
WC 5.4-rc.1 and Trunk
PHP 7.4

**Comment by vedanshujain** [comment]
Closed in #30015
