### ISSUE TITLE
Allow access to raw tracker snapshot via CLI or UI for debugging and transparency on what data is included

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce#29982]
**Is your feature request related to a problem? Please describe.**
I often work on adding extra data to the WooCommerce Tracker snapshot (in Woo extensions). It's hard to confirm the values are correct, because there's no easy way to view the tracker data for a store. Typically I'll hack in (temporary) code to log the snapshot before it's sent.

Also, it would be nice for merchants, admins or curious folks to see exactly what information is included in the tracker snapshot, for their store. This is [documented](https://woocommerce.com/usage-tracking/), but it would be more transparent to provide a way to simply see what's included (without having to hack code).

Because the snapshot can include data from multiple extensions as well as WooCommerce core, the exact list of fields depends on the site setup. So it would be nice to make it easy to confirm exactly what's sent for a specific store. 

**Describe the solution you'd like**
One or more of the following:

- A button on `WooCommerce > Status` page, which generates and shows a snapshot, or shows the last snapshot.
- A link/button on `WooCommerce > Settings > Advanced > WooCommerce.com` which shows a recent snapshot or freshly-generated snapshot. 
- A CLI command to generate and dump a snapshot to screen or to a file.

All snapshot fields should be shown in flattened key-value format.

**Describe alternatives you've considered**
- Continue hacking the core code as needed to log the snapshot when it's generated.

**Comment by haszari** [comment]
Happy to whip up a PR for this - logging an issue first to gauge interest. cc wc-tracker extraordiniare @deltaWhiskey

**Comment by deltaWhiskey** [comment]
I'm all for it! Both for the transparency and ease-of-testing reasons.

**Comment by haszari** [comment]
Opened a PR for the most basic version of this: `wc tracker-snapshot` `print_r`s it to terminal.

#30010
