### ISSUE TITLE
[GlobalStep] "Price entered with tax" option is not working as per the test instructions.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#29992]
## Bug Description:
For Case 1: The Prices are displayed 36.99 on checkout page if you select the "No, I will enter prices exclusive of tax" option for Prices entered with tax. But in instructions step 1 it is mentioned that Set the rounding to subtotal level, and price entered inclusive taxes.
For Case 2: The Prices are displayed 302 on checkout page if you select "Yes, I will enter prices inclusive of tax" option for Prices entered with tax. But in instructions step 1 it is mentioned that Set the rounding to subtotal level, and price entered exclusive taxes.

## Test Instructions:
https://github.com/woocommerce/woocommerce/wiki/Release-Testing-Instructions-WooCommerce-5.4#make-rounding-more-accurate-when-prices-are-entered-more-than-2dp-closes-24184-and-28292

## Environment:
Woocommerce Version : WooCommerce 5.4 RC1
WordPress version: (v5.7)

## PC:
Windows 10, Mac 10.14.6
Chrome(Version 90.0.4430.93) 
Firefox(Version 88.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Complete the onboarding setup wizard.
1. Add a Tax rate of 20%.
1. Go to WooCommerce > Settings > Tax.
1. Select "Yes, I will enter prices inclusive of tax" option for Price entered with tax as per mentioned in the test instructions.
1. Enable the "Rounding" option.
1. Add a product for price 30.825. Add it to cart.
1. Checkout the cart and note that the prices are displayed as 30.83.
1. Now change the Price entered with tax settings to "No, I will enter prices exclusive of tax".
1. Go to Checkout page and note that prices are displayed as 36.99.
1. Observe that "Price entered with tax" option is not working as per the test instructions.

## Note:
The same issue is observed for Case:2 mentioned in the Test instructions.

## Actual Result:
"Price entered with tax" option is not working as per the test instructions

## Expected Result:
"Price entered with tax" option should work as per the settings. 

## Video:

https://user-images.githubusercontent.com/41110392/119690453-54e2f100-be67-11eb-80d4-6cad851226fe.mp4

https://user-images.githubusercontent.com/41110392/119690464-57dde180-be67-11eb-93ba-da545f969389.mp4

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by juliaamosova** [comment]
Thank you for filing the issue @gglobalstep!

It seems that there is a mistake in the [testing instructions](https://github.com/woocommerce/woocommerce/wiki/Release-Testing-Instructions-WooCommerce-5.4#make-rounding-more-accurate-when-prices-are-entered-more-than-2dp-closes-24184-and-28292). It should be as follows vs how it is right now:

![taxes](https://user-images.githubusercontent.com/19143190/120037728-14eb4d80-bfd0-11eb-9536-75a112557f7d.png)

If the testing instructions corrected with my suggestions above, everything is working as expected. Tested using WC 5.4 RC1:

## Case 1:

**Tax Settings:**

![Screen Shot 2021-05-28 at 4 07 39 PM](https://user-images.githubusercontent.com/19143190/120037949-790e1180-bfd0-11eb-97ff-36dc42249c55.png)

**Outcome - as expected:**

![Screen Shot 2021-05-28 at 4 07 25 PM](https://user-images.githubusercontent.com/19143190/120037966-81664c80-bfd0-11eb-9cbb-e35ab32ac863.png)

---

## Case 2:

**Tax Settings:**

![Screen Shot 2021-05-28 at 4 19 53 PM](https://user-images.githubusercontent.com/19143190/120037992-8f1bd200-bfd0-11eb-852e-1d79572fe6be.png)

**Outcome - as expected:**

![Screen Shot 2021-05-28 at 4 13 19 PM](https://user-images.githubusercontent.com/19143190/120038054-a9ee4680-bfd0-11eb-818a-38b76455887f.png)

We took the testing instructions directly from https://github.com/woocommerce/woocommerce/pull/29318. @vedanshujain do you think you could have made a typo in the PR testing instructions?

**Comment by vedanshujain** [comment]
@juliaamosova You are right, it was a typo on my part. @jonathansadowski [also pointed it out](https://github.com/woocommerce/woocommerce/pull/29318#pullrequestreview-658440347), my bad for not correcting it then and there. Correcting it now in PR and in testing instructions.

**Comment by vedanshujain** [comment]
Updated in both release and pr testing instructions. Closing the issue!
