### ISSUE TITLE
WooCommerce Analytics > Stock showing stock in long decimalisation when using the Measurement Price Calculator.

### ISSUE THREAD

**Issue by stuartduff** [woocommerce/woocommerce#29990]
**Reported in ticket:** 4020182-zen

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When using the Measurement Price Calculator plugin for WooCommerce to sell products ( Fabric ) in meters Analytics > Stock can show stock quantities like this example below.

![Screen Shot on 2021-05-26 at 15:10:16](https://user-images.githubusercontent.com/1190565/119674904-7f678680-be34-11eb-8b5f-163a9ef2fce8.png)

**Expected behavior**

We would expect to see the remaining stock quantity rounded up as is displayed on the product itself.

![Screen Shot on 2021-05-26 at 15:11:27](https://user-images.githubusercontent.com/1190565/119675141-b0e05200-be34-11eb-9657-5434a6c7f8c9.png)

**Actual behavior**
Instead, we see a long unrounded number when viewing Analytics > Stock like this below.

![Screen Shot on 2021-05-26 at 15:10:16](https://user-images.githubusercontent.com/1190565/119674904-7f678680-be34-11eb-8b5f-163a9ef2fce8.png)

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Install the [Measurement Price Calculator](https://woocommerce.com/products/measurement-price-calculator/) plugin.
2. Configure a product like within the screenshots provided below.
3. Purchase the product using a length of 3.35 Meters or similar.
4. View Analytics > Stock to see the issue.

**Screenshots**

Product > Measurement configuration. Make sure to enable the **Calculate inventory** checkbox.

![Screen Shot on 2021-05-26 at 15:15:45](https://user-images.githubusercontent.com/1190565/119675832-48de3b80-be35-11eb-8bb6-c70a3e3070b3.png)

Inventory tab configuration.

![Screen Shot on 2021-05-26 at 15:16:47](https://user-images.githubusercontent.com/1190565/119676010-6dd2ae80-be35-11eb-8e6f-a39a9a26df9e.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

The latest version of WordPress, WooCommerce, Measurement Price Calculator and Storefront.

**Comment by rodelgc** [comment]
Hi @stuartduff,

Thank you for reporting the issue. Seems like this issue only happens in `Analytics > Stock` and not in `WP Admin > Products` page and customer pages. 

`Analytics` is being developed in another repository: [woocommerce-admin](https://github.com/woocommerce/woocommerce-admin).

I am going to move your bug report there so that the right team could take a look further.

**Comment by juliaamosova** [comment]
Issue moved to [woocommerce/woocommerce-admin #7078](https://github.com/woocommerce/woocommerce-admin/issues/7078) via [**ZenHub**](https://www.zenhub.com/)
