### ISSUE TITLE
Add Docker Environment for Development

### ISSUE THREAD

**Issue by adrianduffell** [woocommerce/woocommerce#29997]
**Is your feature request related to a problem? Please describe.**
WooCommerce doesn't provide an environment for Docker users to spin up a site or run PHP tests.

**Describe the solution you'd like**
Use [wp-env](https://make.wordpress.org/core/2020/03/03/wp-env-simple-local-environments-for-wordpress/) to provide the environment. This involves adding a simple configuration file to the repo root.

wp-env also provides a PHPUnit service to run tests with Docker. This requires [`wp-phpunit`](https://packagist.org/packages/wp-phpunit/wp-phpunit) to be installed via composer and possibly some other tweaks to the PHPUnit bootstrap. [Setup instructions are here](https://github.com/WordPress/gutenberg/pull/22365#issuecomment-712445838).

**Describe alternatives you've considered**
A more complex approach is to roll our own environment. On WC Admin, I contributed a [standalone](https://github.com/woocommerce/woocommerce-admin/tree/main/docker/wc-admin-php-test-suite) environment to run tests in PHPUnit. An advantage of this is more flexibility and customization opportunities, however it obviously comes with a maintenance and support cost which distracts from other work.

**Additional context**
If there is interest, I'm keen to create a PR for this using wp-env 🙂

**Comment by jonathansadowski** [comment]
Thanks for bringing this up, @adrianduffell. We'd welcome any effort here, in fact, there has been discussion of such in relation to the merging of WPA back into core (see p7bje6-3kP-p2), and while `wp-env` hasn't necessarily been settled on, I think that thread would be a welcome place to continue the conversation. See also p1624551839047500-slack-C0E1AV8T0.

**Comment by peterfabian** [comment]
Is this something that @ObliviousHarmony plans to do with his team?

**Comment by ObliviousHarmony** [comment]
This was added in #30892 and is now available in the repo!
