### ISSUE TITLE
New hook for items removed after cart hash change

### ISSUE THREAD

**Issue by azygis** [woocommerce/woocommerce#30006]
**Is your feature request related to a problem? Please describe.**
Currently we are using `Woocommerce Product Bundles` plugin in our store. We noticed an issue caused by wp_woocommerce_session_* cookie staying even after browser is closed (without remember me checked). That caused notices getting flooded with names of both product bundle "container" and all it's included products. We solved the actual problem by clearing the cart with `woocommerce_load_cart_from_session` hook - clear the cart and forget the session if user is logged out and customer id is different.

After much digging I did realize we're actually able to filter out messages when [product is not purchasable](https://github.com/woocommerce/woocommerce/blob/trunk/includes/class-wc-cart-session.php#L142) (although having someone else's session was a bigger issue than flood of notices, so we rather fixed that). But the next if for when the cart hash has changed [does not contain any hooks](https://github.com/woocommerce/woocommerce/blob/trunk/includes/class-wc-cart-session.php#L149) to filter these notices.

**Describe the solution you'd like**
Solution would seem to be quite easy, I think - just add a filter like for non purchasable items.

**Describe alternatives you've considered**
We'd be able to filter using hooks from notice itself, but... That only gives us the text, and not the product data.

**Additional context**
It's really not fully related to this ticket, but... Is the session cookie really supposed to stay when you login without remember-me, and you close the browser? That sounds very unsafe.

**Comment by tammullen** [comment]
Hi @azygis 

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by jonathansadowski** [comment]
Thanks for the request @azygis. We chatted this over, and tried to reproduce the problem you were experiencing that resulted in the request for the new filter, but we weren't quite able to follow. Would you be able to provide us with a step-by-step instructions for reproducing the issue you're running into that is causing you to request this filter?

**Comment by azygis** [comment]
The point of this request is for us as consumers to be able to modify the message at runtime, be it a modification to the string (not an actual change of translation but rather modify based on some params from db or something), or plain clearing it (so the message is not put to notice list at all).

The reproduction part needs a plugin "Woocommerce Product Bundles". Hard to write a step-by-step on mobile. In a nutshell:
1. Login as admin (without remember me)
2. Create a product bundle with items that are private
3. Go to the store page and add the item to your cart.
4. Close the browser.
5. Open the browser and login again to the store page.
6. You get all the notices about your items being removed because they are not purchasable.

The problem here is that the woocommerce session cookie has an expiration of 3 days if remember me is not selected. After reopening the browser, we are anonymous, but still have the cart session. The cart is invalidated as it should, but all the notices are shown the next time you go to the page which is able to view the notices. In our case such page was visible only after logging in, so the notices of cart invalidation would seem like it was done for the actual user that logged in, yet the cart stays intact, which at the time seemed like there was instead a bug in non-purchasable items still staying in the cart.

Having this filter would allow changing or removing the notice for specific type of products. We do not want to show variable/simple products in the notices as our store functions only with bundle products, and items in bundles are not sold separately.

**Comment by simplysaru** [comment]
Hi @azygis, 

Are we able to reproduce this without the WooCommerce Product Bundles plugin? Are you able to share the steps for that?

**Comment by azygis** [comment]
I can't really think of a way to reproduce it without the plugin, sorry. When the product is not visible on the store page, we can't add it to the cart properly instead of hacking via code. The plugin allows us to hide items from store and still purchase them in a form of product bundle.

**Comment by vedanshujain** [comment]
Just to confirm, do you think we should have a filter [right above line 149](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-cart-session.php#L149) like the [one we have for block above](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/class-wc-cart-session.php#L142), although with a different name. This request makes sense, but unfortunately, we wont be able to take this up any time soon. That said, if you'd like, feel free to send us a PR to include this filter.

Another thing is, you mention that WC cart session cookie is not cleared when a user logs in who is different than the user whose session created the cookie. If correct, this looks like a bug as well, can you please open GH issue for this as well with steps to repro? Maybe that will fix the issue you are currently facing without using any filter.

**Comment by azygis** [comment]
Created a pull request #31193 for the filter.

Will try to find a reliable reproduction for the session cookie, but cannot promise it'll be soon, might take a week or few, depending on my own load.

Edit: to make it clearer - the actual session issue is about configuring cart while logged in, closing the browser, and then opening the browser again. You are anonymous from wordpress point of view, but the wc session cookie is still there and I can still possibly see the cart.
