### ISSUE TITLE
As tags e as Categorias não estão sendo inclusas. 

### ISSUE THREAD

**Issue by jotabatista1505** [woocommerce/woocommerce#30004]
As tags e as categorias não podem ser incluídas, ao clicar em adicionar tag/categoria o processo fica carregando infinitamente. 
![image](https://user-images.githubusercontent.com/85023546/120072029-1ec08f80-c068-11eb-844a-abc32cf6fe53.png)

Ao tentar excluir uma tag/categoria aparece o seguinte erro (algo deu errado):
![image](https://user-images.githubusercontent.com/85023546/120072120-81b22680-c068-11eb-84bc-009899de6255.png)

Relatório do sistema:

`
### WordPress Environment ###

WordPress address (URL): http://bananabipolar.com
Site address (URL): http://bananabipolar.com
WC Version: 5.3.0
REST API Version: ✔ 5.3.0
WC Blocks Version: ✔ 4.9.1
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.2.6
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: pt_BR
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.14
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 5000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.4.17-MariaDB-cll-lve
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.3.0
WC Database Prefix: wp_
Tamanho total do banco de dados: 78.56MB
Tamanho dos dados do banco de dados: 70.99MB
Tamanho do índice do banco de dado: 7.57MB
wp_woocommerce_sessions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_api_keys: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_attribute_taxonomies: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_woocommerce_downloadable_product_permissions: Dados: 0.02MB + Índex: 0.17MB + mecanismo InnoDB
wp_woocommerce_order_items: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_order_itemmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_tax_rates: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wp_woocommerce_tax_rate_locations: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_woocommerce_shipping_zones: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_woocommerce_shipping_zone_locations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_shipping_zone_methods: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_woocommerce_payment_tokens: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_payment_tokenmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_woocommerce_log: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_actions: Dados: 1.52MB + Índex: 0.69MB + mecanismo InnoDB
wp_actionscheduler_claims: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_groups: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_actionscheduler_logs: Dados: 1.52MB + Índex: 0.39MB + mecanismo InnoDB
wp_adtribes_my_conversions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_aioseo_notifications: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_aioseo_posts: Dados: 0.31MB + Índex: 0.02MB + mecanismo InnoDB
wp_anc_6310_counter: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_anc_6310_icons: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_anc_6310_style: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_aws_cache: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_aws_index: Dados: 1.31MB + Índex: 0.30MB + mecanismo InnoDB
wp_ce4wp_abandoned_checkout: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_commentmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_comments: Dados: 0.05MB + Índex: 0.09MB + mecanismo InnoDB
wp_egoi_email_order_billets: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_egoi_email_order_reminders: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_egoi_form_subscribers: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_egoi_map_fields: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_egoi_sms_abandoned_carts: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_egoi_sms_follow_price: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_egoi_sms_order_billets: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_egoi_sms_order_reminders: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_bills: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_bill_account_details: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_bill_details: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_cash_at_banks: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_chart_of_accounts: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_currency_info: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_expenses: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_expense_checks: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_expense_details: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_financial_years: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_invoices: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_invoice_account_details: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_invoice_details: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_invoice_details_tax: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_invoice_receipts: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_invoice_receipts_details: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_journals: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_journal_details: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_ledgers: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_ledger_categories: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_ledger_details: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_ledger_settings: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_opening_balances: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_payment_methods: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_pay_bill: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_pay_bill_details: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_pay_purchase: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_pay_purchase_details: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_people_account_details: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_people_trn: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_people_trn_details: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_products: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_product_categories: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_product_details: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_product_types: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_purchase: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_purchase_account_details: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_purchase_details: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_purchase_details_tax: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_taxes: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_tax_agencies: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_tax_agency_details: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_tax_categories: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_tax_cat_agency: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_tax_pay: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_transfer_voucher: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_trn_status_types: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_acct_voucher_no: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_audit_log: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_erp_company_locations: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_erp_crm_activities_task: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_erp_crm_contact_group: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_crm_contact_subscriber: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_erp_crm_customer_activities: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_erp_crm_customer_companies: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_erp_crm_save_email_replies: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_crm_save_search: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_holidays_indv: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_hr_announcement: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_erp_hr_dependents: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_erp_hr_depts: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_hr_designations: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_hr_education: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_erp_hr_employees: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wp_erp_hr_employee_history: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_erp_hr_employee_notes: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_hr_employee_performance: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_erp_hr_financial_years: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_erp_hr_holiday: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_hr_leaves: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_erp_hr_leaves_unpaid: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wp_erp_hr_leave_approval_status: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_erp_hr_leave_encashment_requests: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_erp_hr_leave_entitlements: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_erp_hr_leave_policies: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_erp_hr_leave_policies_segregation: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_erp_hr_leave_requests: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wp_erp_hr_leave_request_details: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_erp_hr_work_exp: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_erp_peoplemeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_erp_peoples: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_erp_people_types: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_erp_people_type_relations: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_erp_user_leaves: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_ff_scheduled_actions: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_fluentform_entry_details: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_fluentform_forms: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_fluentform_form_analytics: Dados: 0.05MB + Índex: 0.00MB + mecanismo InnoDB
wp_fluentform_form_meta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_fluentform_logs: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_fluentform_submissions: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_fluentform_submission_meta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_links: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_mailchimp_carts: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mailchimp_jobs: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_mclean_refs: Dados: 0.09MB + Índex: 0.00MB + mecanismo InnoDB
wp_mclean_scan: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_options: Dados: 6.52MB + Índex: 0.33MB + mecanismo InnoDB
wp_pmpro_discount_codes: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_pmpro_discount_codes_levels: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_pmpro_discount_codes_uses: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_pmpro_memberships_categories: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_pmpro_memberships_pages: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_pmpro_memberships_users: Dados: 0.02MB + Índex: 0.09MB + mecanismo InnoDB
wp_pmpro_membership_levelmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_pmpro_membership_levels: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_pmpro_membership_ordermeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_pmpro_membership_orders: Dados: 0.02MB + Índex: 0.20MB + mecanismo InnoDB
wp_pm_activities: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_pm_assignees: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_pm_boardables: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_pm_boards: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_pm_capabilities: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_pm_categories: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_pm_category_project: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_pm_comments: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_pm_files: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_pm_imports: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_pm_meta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_pm_projects: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_pm_roles: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_pm_role_project: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_pm_role_project_capabilities: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_pm_role_project_users: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_pm_role_user: Dados: 0.02MB + Índex: 0.06MB + mecanismo InnoDB
wp_pm_settings: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_pm_tasks: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_pm_task_types: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_pm_task_type_task: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_postmeta: Dados: 44.52MB + Índex: 1.88MB + mecanismo InnoDB
wp_posts: Dados: 10.52MB + Índex: 0.31MB + mecanismo InnoDB
wp_promag_email_templates: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_promag_fields: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_promag_friends: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_promag_groups: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_promag_group_requests: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_promag_msg_conversation: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_promag_msg_threads: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_promag_notification: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_promag_paypal_log: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_promag_sections: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_rmp_analytics: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_rm_fields: Dados: 0.13MB + Índex: 0.00MB + mecanismo InnoDB
wp_rm_forms: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_rm_front_users: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_rm_login: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_rm_login_log: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_rm_notes: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_rm_paypal_fields: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_rm_paypal_logs: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_rm_rules: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_rm_sent_mails: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_rm_sessions: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_rm_stats: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_rm_submissions: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_rm_submission_fields: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_rm_tasks: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_rm_task_exe_log: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_termmeta: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_terms: Dados: 0.05MB + Índex: 0.03MB + mecanismo InnoDB
wp_term_relationships: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_term_taxonomy: Dados: 0.06MB + Índex: 0.06MB + mecanismo InnoDB
wp_tinvwl_analytics: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_tinvwl_items: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_tinvwl_lists: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_usermeta: Dados: 0.05MB + Índex: 0.03MB + mecanismo InnoDB
wp_users: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_vi_wad_ali_orders_info: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_vi_wad_error_product_images: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_admin_notes: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_admin_note_actions: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_category_lookup: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_customer_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_download_log: Dados: 0.02MB + Índex: 0.05MB + mecanismo InnoDB
wp_wc_order_coupon_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_order_product_lookup: Dados: 0.02MB + Índex: 0.11MB + mecanismo InnoDB
wp_wc_order_stats: Dados: 0.02MB + Índex: 0.08MB + mecanismo InnoDB
wp_wc_order_tax_lookup: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wc_product_meta_lookup: Dados: 0.05MB + Índex: 0.09MB + mecanismo InnoDB
wp_wc_reserved_stock: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wc_tax_rate_classes: Dados: 0.02MB + Índex: 0.02MB + mecanismo InnoDB
wp_wc_webhooks: Dados: 0.02MB + Índex: 0.03MB + mecanismo InnoDB
wp_wdr_order_discounts: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wdr_order_item_discounts: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wdr_rules: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wemail_forms: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_woocommerce_b2w_skyhub_log: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_woocommerce_b2w_skyhub_queue: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wpforms_tasks_meta: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB
wp_wpf_filters: Dados: 0.02MB + Índex: 0.00MB + mecanismo InnoDB

### Post Type Counts ###

al_product: 19
attachment: 259
counter_numbers: 1
custom_css: 2
customize_changeset: 102
elementor_library: 6
is_search_form: 1
nav_menu_item: 12
omapi: 1
page: 31
post: 3
product: 35
product_variation: 166
profilegrid_blogs: 2
revision: 1243
shop_coupon: 4
shop_order: 9
shop_order_refund: 2
sp_wcslider: 1
tf_stats: 1
wpforms: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

Advanced Woo Search: por ILLID – 2.28
FiboSearch - AJAX Search for WooCommerce: por FiboSearch Team – 1.11.0
All in One SEO: por Equipe All in One SEO – 4.1.1.1
Clear Cache For Me: por Webhead LLC – 1.6
Easy Auto SKU Generator for WooCommerce: por Dan Zakirov – 1.0.5
Elementor: por Elementor.com – 3.2.4
Facebook para WooCommerce: por Facebook – 2.5.1
Fluent Forms: por Contact Form - WPManageNinja LLC – 3.6.74
Site Kit by Google: por Google – 1.33.0
HT Mega - Absolute Addons for Elementor Page Builder: por HasThemes – 1.5.9
JetWidgets For Elementor: por Crocoblock – 1.0.10
JetWoo Widgets For Elementor: por Crocoblock – 1.1.2
Google Ads & Marketing da Kliken: por Kliken – 1.0.7
LiteSpeed Cache: por LiteSpeed Technologies – 3.6.4
Media Cleaner: por Jordy Meow – 6.1.7
Media Library File Download: por Gennady Kovshenin
Andy Abelow – 1.0

Product Categories Designs for WooCommerce: por WP OnlineSupport – 1.2.3
ProfileGrid: por profilegrid – 4.4.2
Simple product counter: por WebArea – 2.1.0
TI WooCommerce Wishlist: por TemplateInvaders – 1.25.5
Toolbar Extras: por David Decker - DECKERWEB – 1.4.9
Social Media and Share Icons (Ultimate Social Media): por UltimatelySocial – 2.6.7
Woo Ajax Cart Count: por AceWebx Team – 1.3.5
Integração do Google Analytics com o WooCommerce: por WooCommerce – 1.5.1
Mercado Pago payments for WooCommerce: por Mercado Pago – 5.1.1
Discounts Per Payment Method on WooCommerce: por Claudio Sanches – 3.1.0
WooCommerce Shipping & Tax: por WooCommerce – 1.25.13
WooCommerce: por Automattic – 5.3.0
WooLentor - WooCommerce Elementor Addons + Builder: por HasThemes – 1.8.9
WPForms Lite: por WPForms – 1.6.7

### Inactive Plugins (1) ###

Product CSV Import Export (BASIC): por WebToffee – 1.9.3

### Settings ###

API Enabled: –
Force SSL: –
Currency: BRL (R$)
Currency Position: left
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base da loja: #2896 - /loja/
Carrinho: #1136 - /carrinho/
Finalizar compra: #1137 - /checkout/
Minha conta: #1138 - /minha-conta/
Termos e condições: #3205 - /termos-e-condicoes/

### Theme ###

Name: Zigcy Lite
Version: 2.0.7
Author URL: http://accesspressthemes.com
Child Theme: ❌ – Recomendamos você utilizar um tema filho no caso de você estiver personalizando o WooCommerce em um tema ascendente. Veja como criar um tema filho
WooCommerce Support: ✔

### Templates ###

Overrides: zigcy-lite/woocommerce/cart/mini-cart.php
zigcy-lite/woocommerce/single-product/add-to-cart/variable.php

### Modelos TI WooCommerce Wishlist ###

Substituições: –

### Action Scheduler ###

Complete: 2.962
Oldest: 2021-04-30 15:38:32 -0300
Newest: 2021-05-29 10:18:58 -0300

Failed: 2
Oldest: –
Newest: –

Pending: 7
Oldest: 2021-05-29 10:33:58 -0300
Newest: 2021-06-05 08:54:22 -0300

### Status report information ###

Generated at: 2021-05-29 10:27:58 -03:00
`

**Prerequisites (mark completed items with an [x]):**
- [ ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by tammullen** [comment]
Hi @jotabatista1505 

Please note that we reply to bug reports in English language only. I used [Google Translate](https://translate.google.com/) to translate your message. You can use the same to translate my reply back. 

> Tags and categories cannot be included, when clicking add tag

> When trying to delete a tag

I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

I can add and delete tags

![Screenshot 2021-06-02 at 11 27 09](https://user-images.githubusercontent.com/24649833/120465205-9f97c800-c395-11eb-8d55-2cdf919eb480.png)
![Screenshot 2021-06-02 at 11 27 24](https://user-images.githubusercontent.com/24649833/120465207-a0c8f500-c395-11eb-82eb-859ac575dea2.png)
![Screenshot 2021-06-02 at 11 27 31](https://user-images.githubusercontent.com/24649833/120465214-a292b880-c395-11eb-93d7-aaf7908820b7.png)

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
​
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.
