### ISSUE TITLE
Variable products custom stock status not entirely supported?

### ISSUE THREAD

**Issue by alessandrotesoro** [woocommerce/woocommerce#30016]
**Scenario:**

- New stock status option is registered via the `woocommerce_product_stock_status_options` filter.
- Created a variable product with variations "small, medium, large".
- All variations have been assigned the newly registered stock status.
- Variable product (the parent product only) is forced back to the "out of stocks" automatically by WooCommerce.

It seems that each time the stock status of a variation is updated, the following function is called https://github.com/woocommerce/woocommerce/blob/b19500728b4b292562afb65eb3a0c0f50d5859de/includes/data-stores/class-wc-product-variable-data-store-cpt.php#L624 and forces back the "out of stock" status.

Is there any way to tap into the sync process so that the custom status can be properly assigned to the "parent" product?

**Describe the solution you'd like**
An action or filter so that the custom status can be assigned to the parent product.

**Describe alternatives you've considered**

1. Tried setting up a stock quantity to variations with the custom stock status but the stock quantity does not persist.

**Comment by tammullen** [comment]
Hi @alessandrotesoro 

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by alessandrotesoro** [comment]
Hi @tammullen 

Any idea when we'd be able to get a feedback on this?

Thank you.

**Comment by barryhughes** [comment]
Hi @alessandrotesoro,

There's not really any way for the `sync_stock_status` method to know how/when to apply any custom statuses that are registered, so it's something that would need to be handled as part of your overall solution.

Perhaps by taking advantage of the [`woocommerce_variable_product_sync_data`](https://woocommerce.github.io/code-reference/files/woocommerce-includes-class-wc-product-variable.html#source-view.621) action (just an example, there may be other or more suitable hooks) you could override the decision made by that method and set it according to your needs?
