### ISSUE TITLE
WooCommerce build from source fails due to missing `puppeteer-utils` dependency (?)

### ISSUE THREAD

**Issue by haszari** [woocommerce/woocommerce#30011]
Note this is a dev-tooling bug that's been bugging me - not sure if there's something weird about my setup.

**Describe the bug**
When I build WooCommerce core from source, it fails with this error:

```

Running "eslint:src" (eslint) task
Warning: Cannot read config file: /Users/rua/_automattic/ventures-repos/woocommerce/.eslintrc.js
Error: Cannot find module '@automattic/puppeteer-utils'
Require stack:
- /Users/rua/_automattic/ventures-repos/woocommerce/tests/e2e/env/config/jest.config.js
- /Users/rua/_automattic/ventures-repos/woocommerce/tests/e2e/env/config/use-config.js
- /Users/rua/_automattic/ventures-repos/woocommerce/.eslintrc.js
- /Users/rua/_automattic/ventures-repos/woocommerce/node_modules/gruntify-eslint/node_modules/eslint/lib/config/config-file.js
- /Users/rua/_automattic/ventures-repos/woocommerce/node_modules/gruntify-eslint/node_modules/eslint/lib/config.js
- /Users/rua/_automattic/ventures-repos/woocommerce/node_modules/gruntify-eslint/node_modules/eslint/lib/cli-engine.js
- /Users/rua/_automattic/ventures-repos/woocommerce/node_modules/gruntify-eslint/node_modules/eslint/lib/api.js
- /Users/rua/_automattic/ventures-repos/woocommerce/node_modules/gruntify-eslint/tasks/eslint.js
- /Users/rua/_automattic/ventures-repos/woocommerce/node_modules/grunt/lib/grunt/task.js
- /Users/rua/_automattic/ventures-repos/woocommerce/node_modules/grunt/lib/grunt.js
- /Users/rua/_automattic/ventures-repos/woocommerce/node_modules/grunt/node_modules/grunt-cli/bin/grunt
- /Users/rua/_automattic/ventures-repos/woocommerce/node_modules/grunt/bin/grunt Use --force to continue.

Aborted due to warnings.
```

Currently I work around this by commenting out the `eslint` task in `Gruntfile.js`. But I'm guessing I'm missing a setup step, or need to install something globally on my dev machine.

**Expected behavior**
- Clone repo.
- Install dependencies e.g. `npm install && composer install`.
- Build with `npm run build` succeeds.

**Comment by haszari** [comment]
#29091 may be related?

**Comment by barryhughes** [comment]
I think a number of us have experienced this and it deserves some attention. I'm not sure if #29091 is directly related but it's quite possible it could be part of an overall solution.

**Comment by Aljullu** [comment]
@rrennick @vedanshujain I see this issue has been closed, but I'm still encountering this error when building WooCommerce. Can you confirm? Is it ok if I reopen it or am I missing something?

**Comment by vedanshujain** [comment]
reopening based on above comment

**Comment by helgatheviking** [comment]
+1 I am also experiencing this issue when running `npm run build:dev` 

Result:
```
Running "eslint:src" (eslint) task
Warning: Cannot read config file: /app/wp-content/plugins/woocommerce/.eslintrc.js
Error: Cannot find module '@automattic/puppeteer-utils'
```

**Comment by roykho** [comment]
Hey @helgatheviking  - try this branch https://github.com/woocommerce/woocommerce/pull/30206 and let us know if it fixes your issue.

**Comment by helgatheviking** [comment]
Thanks @roykho So far it's a no go. unsure if it's something to do with the `lando` development environment. trying with WSL ubuntu too but it seems to hang and move painfully slowly through some `reify` things before ultimately failing here... which looks like it's a bit later in the process than before.


```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @automattic/puppeteer-utils@0.0.1 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @automattic/puppeteer-utils@0.0.1 postinstall script.
```
