### ISSUE TITLE
Webhook 'order.updated' is not triggered when order refund deleted

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce#30022]
Currently 'order.updated' is only triggered only for this two hooks: 'woocommerce_update_order', 'woocommerce_order_refunded'.
See: https://github.com/woocommerce/woocommerce/blob/b19500728b4b292562afb65eb3a0c0f50d5859de/includes/class-wc-webhook.php#L989

We should also add 'woocommerce_refund_deleted'. Because if order refund is deleted from admin edit-order page. And order total is updated. But it will not trigger 'order.updated' webhook.

**Comment by tammullen** [comment]
Hi @erikdemarco ,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/26532. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
