### ISSUE TITLE
Package cannot be installed on PHP 8

### ISSUE THREAD

**Issue by XedinUnknown** [woocommerce/woocommerce#30027]
### Prerequisites
- [x] I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug
The `pelago/emogrifier` package cannot be installed on PHP 8.

### Expected behavior
Composer installs `woocommerce/woocommerce` and all of its dependencies, including `pelago/emogrifier`, successfully.

### Actual behavior
Installation fails with the following message:

```
Problem 1
    - woocommerce/woocommerce[4.8.0-beta.1, ..., 4.9.2, 5.0.0-beta.1, ..., 5.4.0-rc.1] require pelago/emogrifier 3.1.0 -> satisfiable by pelago/emogrifier[v3.1.0].
    - woocommerce/woocommerce[3.9.0-beta.1, ..., 3.9.3, 4.0.0-beta.1, ..., 4.6.2] require composer/installers 1.7.0 -> satisfiable by composer/installers[v1.7.0].
    - inpsyde/product-woocommerce-logging dev-task/php72 conflicts with woocommerce/woocommerce 4.7.1.
    - inpsyde/product-woocommerce-logging dev-task/php72 conflicts with woocommerce/woocommerce 4.7.1-beta.1.
    - inpsyde/product-woocommerce-logging dev-task/php72 conflicts with woocommerce/woocommerce 4.7.0.
    - inpsyde/product-woocommerce-logging dev-task/php72 conflicts with woocommerce/woocommerce 4.7.0-rc.1.
    - inpsyde/product-woocommerce-logging dev-task/php72 conflicts with woocommerce/woocommerce 4.7.0-beta.2.
    - inpsyde/product-woocommerce-logging dev-task/php72 conflicts with woocommerce/woocommerce 4.7.0-beta.1.
    - pelago/emogrifier v3.1.0 requires php ^5.6 || ~7.0 || ~7.1 || ~7.2 || ~7.3 || ~7.4 -> your php version (8.0.5) does not satisfy that requirement.
    - composer/installers v1.7.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - inpsyde/product-woocommerce-logging is present at version dev-task/php72 and cannot be modified by Composer
    - Root composer.json requires woocommerce/woocommerce ^3.9 || ^4.0 || ^5.0 -> satisfiable by woocommerce/woocommerce[3.9.0-beta.1, ..., 3.9.3, 4.0.0-beta.1, ..., 4.9.2, 5.0.0-beta.1, ..., 5.4.0-rc.1].
```

I actually allow `^3.9 | ^4.0 | ^5.0`, and conflict with `4.7` due to #28320.

### Steps to reproduce the bug
1. In any Composer package, require `woocommerce/woocommerce:5.4.0-rc.1`;
2. Ensure PHP 8.x;
2. Attempt `composer update`;
3. Observe symptom (actual behaviour).

### Isolating the problem
- [x] I can reproduce this bug consistently using the steps above.

## Remarks
`pelago/emogrifier` actually adds support for PHP 8 in [`5.0.0`][], but _this_ package only [allows][1] the specific version `3.1.0`.

⚠️ For some reason, this is not visible in the [build][], as the `pelago/emogrifier` doesn't seem to be attempted by Composer at all. I'm not sure why this is exactly, but perhaps it has something to do with the fact that you are [pretending][2] to be on PHP 7.0 regardless of what version you are on actually. That way the builds do not prove that this package is _actually installable_ on any version of PHP besides 7.0. Consider removing that: I understand that this is probably done in order to build the actual plugin, and this needs deps to be installed on the minimal supported version (7.0), but this isn't really a great way to do that, as this issue shows. What I would do is remove the platform override, and simply set it _only_ during the actual building of the distributable plugin archive. That way the the tests will actually prove that stuff is installable, and you get to ship your plugin with deps that are guaranteed to run on your lowest required PHP version.

[`5.0.0`]: https://github.com/MyIntervals/emogrifier/releases/tag/v5.0.0
[1]: https://github.com/woocommerce/woocommerce/blob/0507f06508a448995ae6ebec903115e670cc5ee4/composer.json#L21
[2]: https://github.com/woocommerce/woocommerce/blob/0507f06508a448995ae6ebec903115e670cc5ee4/composer.json#L33
[build]: https://github.com/woocommerce/woocommerce/runs/2728814440

**Comment by tammullen** [comment]
Hi @XedinUnknown,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
Thanks for flagging this, @XedinUnknown.

> pelago/emogrifier actually adds support for PHP 8 in 5.0.0, but this package only allows the specific version 3.1.0.

An issue from our perspective is that if we update `pelago/emogrifier` to `5.0.0` we will [lose compatibility with PHP 7.0](https://github.com/MyIntervals/emogrifier/blob/v5.0.0/composer.json#L39-L40) ... but perhaps we can make the version constraint `4.0 - 5.0` (we'll need to do some testing, though, to make sure that Composer still fetches 4.0.x when installing on PHP 7.0. 

We'll discuss this and see what we can do, but in the meantime if you look at WooCommerce's own `composer.json` file [we set `config.platform.php` to `7.0`](https://github.com/woocommerce/woocommerce/blob/5.5.0/composer.json#L33) ... is that a viable solution in your case (as an immediate but short-term fix)?

**Comment by barryhughes** [comment]
Let's investigate changes to our Composer config necessary to resolve this.

**Comment by mattias-pa-vistrom** [comment]
Are there any update on this?
Do you have a roadmap for when you plan to support PHP 8.0?

**Comment by clintonb** [comment]
This is blocking me from installing and using WooCommerce. I am not comfortable with the change proposed by @barryhughes as it seems like an incident waiting to happen, given emogrifier 3.1.0 does not officially support PHP 8.x. Is there any update on a fix for this? Is it really the case that ~no WooCommerce users are safely using the package with PHP 8.x?

**Comment by mattias-pa-vistrom** [comment]
> This is blocking me from installing and using WooCommerce. I am not comfortable with the change proposed by @barryhughes as it seems like an incident waiting to happen, given emogrifier 3.1.0 does not officially support PHP 8.x. Is there any update on a fix for this? Is it really the case that ~no WooCommerce users are safely using the package with PHP 8.x?

If you check https://wordpress.org/plugins/woocommerce/ it clearly says PHP 7.0 and above. Installing WooCommerce via FTP or via the plugins installer works perfectly well with PHP 8. So I can only imagine how many stores there are out there using WooCommerce unsupported on PHP 8.

**Comment by clintonb** [comment]
Okay…we are asking for official support so we don’t have to implement hacks to install with Composer for PHP 8. If a downstream dependency doesn’t officially support PHP 8, WooCommerce cannot be said to support PHP 8.

**Comment by mattias-pa-vistrom** [comment]
> Okay…we are asking for official support so we don’t have to implement hacks to install with Composer for PHP 8. If a downstream dependency doesn’t officially support PHP 8, WooCommerce cannot be said to support PHP 8.

I agree with you. This should have a higher priority.

**Comment by peterfabian** [comment]
We agree, bumping the priority to high and we plan to look into it in the next planning session. Thanks for your input, folks.

**Comment by peterfabian** [comment]
Timeboxed to look for a solution for 2-3 days max. There is no easy fix if we want to be compatible with both PHP 7 and 8, we can either fork Emogrifier, find some hack/workaround, or find some other clever solution.

**Comment by szepeviktor** [comment]
@peterfabian You need [Emogrifier v5.0.0](https://packagist.org/packages/pelago/emogrifier#v5.0.0) which is PHP 7-8 compatible.
The change in WC source code is minimal.

**Comment by barryhughes** [comment]
Noting Emogrifier 5.0 only goes back as far as PHP 7.1, whereas WooCommerce still supports PHP 7.0.

> `php: ~7.1.0 || ~7.2.0 || ~7.3.0 || ~7.4.0 || ~8.0.0`

**Comment by mattias-pa-vistrom** [comment]
Any news on this?

**Comment by peterfabian** [comment]
Sadly, no, as we were looking into some higher priority bugs. Realistically speaking, I don't think this will be done this year due to the number of things in progress now (bugs, preps for WP 5.9, holiday season). Probably in January.

We can have a look at what makes the new Emogrifier incompatible with PHP 7.0 and see if we can change it, but rolling our fork always comes with a lot of overhead of tracking changes, backward compatibility support burden, etc. If you think there's some clever solution we're not seeing, would be happy to hear from you folks. Thanks.

**Comment by szepeviktor** [comment]
Emogrifier uses
- constant visibility
- array destructor
- `void` return type

I think all of them could be backported to PHP 7.0 with Rector. (automatically)

**Comment by anant1811** [comment]
Also reported in 4654399-zen

**Comment by peterfabian** [comment]
We're [bumping PHP to 7.2 with WC 6.5](https://developer.woocommerce.com/2022/01/05/new-requirement-for-woocommerce-6-5-php-7-2/) which will allow us to update Emogrifier and finally make this work without incurring technical debt.

**Comment by szepeviktor** [comment]
Hello Peter! Why do you encourage users to run on a several years old **and unsupported** PHP version?

Is this why?
![kép](https://user-images.githubusercontent.com/952007/149754674-dcb6fe6e-ebf7-482b-b37a-36094818503f.png)

**Comment by peterfabian** [comment]
Hi @szepeviktor . I hope this doesn't come across as encouraging it. We're just changing the **minimum** from 7.0 to 7.2 Otherwise, [we encourage people to use at least 7.4](https://woocommerce.com/document/server-requirements/#section-2), and have done so for quite some time already. Otherwise, @Konamiman explained our rationale in the [linked post](https://developer.woocommerce.com/2022/01/05/new-requirement-for-woocommerce-6-5-php-7-2/). TL;DR is that generally, we don't want to cut users off unless it's causing us issues. In this case, it has become difficult to support the whole range of PHP versions, so we're dropping the old ones. Hope it makes sense.

**Comment by joonya77** [comment]
Can I please get an update on when compatibility with PHP 8.0 will be ready? Automatewoo has stopped working for us and we're keen not to downgrade to PHP 7.4 as this may cause issues. Really hoping this can be done soon. Thankyou

**Comment by peterfabian** [comment]
With WC 6.5 in May, we'll drop support for older PHP versions (https://developer.woocommerce.com/2022/01/05/new-requirement-for-woocommerce-6-5-php-7-2/), so that's when we can update the Emogrifier package and be compatible with PHP 8.0. Apologies for the delay.

**Comment by szepeviktor** [comment]
For Composer users:

```json
{
    "name": "vendor-name/package-name",
    "description": "WooCommerce webshop",
    "license": "proprietary",
    "require": {
        "woocommerce/woocommerce": "dev-release/6.5"
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/woocommerce/woocommerce-production.git"
        }
    ],
    "config": {
        "allow-plugins": {
            "composer/installers": true,
            "automattic/jetpack-autoloader": true
        }
    }
}
```

Although some packages are installed **4 times**.
