### ISSUE TITLE
Status page: Time-out error when there are thousands database tables

### ISSUE THREAD

**Issue by chris-vas** [woocommerce/woocommerce#30045]
**Describe the bug**
On a multisite installation with more than 5,000 subsites and more than 100,000 database tables WooCommerce is activated on main site only.  The issue is when we are trying to access the Status page we get a time-out error.

**Expected behavior**
WooCommerce > Status page should be accessible on databases with thousands tables.

**Actual behavior**
Time-out error because of thousands database tables.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. On a multisite installation with more than 100,000 database tables try to visit the WooCommerce > Status page.

**WordPress Environment**
WordPress version: 5.7.2
WooCommerce version: 5.3

**Comment by tammullen** [comment]
Hi @chris-vas ,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/27014. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
