### ISSUE TITLE
New classes in body tag - for dashboard page and with custom endpoint name

### ISSUE THREAD

**Issue by welmartins** [woocommerce/woocommerce#30050]
**Prerequisites (mark completed items with an [x]):**
- [X] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

Hi,
when we browse my account pages all endpoints have specific classes in the body tag as in the examples below:

.woocommerce-account.woocommerce-orders

.woocommerce-account.woocommerce-downloads

but when we are on the my account panel page the class placed in the body tag is just .woocommerce-account
there is no other more specific, so to select elements on this page it ends up being by exclusion as in the example below:

.woocommerce-account:not(.woocommerce-orders):not(.woocommerce-downloads)

you could introduce the **.woocommerce-panel** or **.woocommerce-dashboard** class

**Comment by welmartins** [comment]
Another thing, when creating custom endpoints, the endpoint name could be inserted as a class in the body tag too, as in the example below:


   add_action( 'init', 'my_account_custom_endpoints' );
   function my_account_custom_endpoints() {
       add_rewrite_endpoint( 'my-endpoint', EP_ROOT | EP_PAGES );
   }

< body class="woocommerce-account woocommerce-my-endpoint">

**Comment by zhongruige** [comment]
Hi @welmartins,

Thank you for taking the time to share this idea, we really appreciate your help. 

While this is clearly a great improvement/idea we won’t be able to tackle it in the upcoming weeks. We’re going to add it to our backlog where it will be considered for future releases.

Stay tuned for updates.
