### ISSUE TITLE
Security Issues - SQL Injection , External Service Interaction, Cross site request forgery, Session token in URL

### ISSUE THREAD

**Issue by DonDi1989** [woocommerce/woocommerce#30061]
Hello,

We are integrating WooCommerce for our eCommerce website and we want to integrate a local bank payment gateway.
Before the integration we have tested the website using the Burpsuite Professional application and we have received the results and we have four security issues that we need to take a look at and resolve:

**Removed**

**Comment by ObliviousHarmony** [comment]
Hello @DonDi1989,

Thank you for your report. As per [our security policy](https://github.com/woocommerce/woocommerce/security/policy), please take care to report security issues using the appropriate channels. I have removed any sensitive content from this issue and forwarded it internally.
