### ISSUE TITLE
Changes to jquery.payment.js in 5.4 may cause several gateways to break (fix proposed)

### ISSUE THREAD

**Issue by unfulvio** [woocommerce/woocommerce#30069]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

Version 5.4 recently released issued a change in jquery.payment.js:

https://github.com/woocommerce/woocommerce/commit/ef572483d8c71732018d11d00a03b103c9167fa1

However this may break payment gateways, such as the SkyVerge payment gateways that may send an integer to the payment.js script methods rather than a string. 

The change in WC 5.4 assumes the type received will always be string, but this is not documented in the script JSDoc and  may be assumed to be of integer type, given that it is dealing with months, years and CVC numbers, which can clearly be valid integers. 

I suggest to issue a bugfix to check the type of the affected variables first; if they are integers, parse them to string first before validating as it's currently. If values are neither a string or integer type, it'd be fine to retain the behavior in 5.4 and turn the invalid values into empty string to parse in the regex.

**Expected behavior**
Payment.js should evaluate the value type before defaulting card expiry month/year or CVC numbers to empty string

**Actual behavior**
Payment.js will turn valid integers for expiry dates and CVC data to empty strings

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Configure a SkyVerge gateway like Authorize.Net and go to checkout to process a payment
2. Result:
   - With WC 5.3, checkout can be processed successfully
   - With WC 5.4 will result in invalid expiry date or CVC
3. Fix: 
   - Reverting the change in https://github.com/woocommerce/woocommerce/commit/ef572483d8c71732018d11d00a03b103c9167fa1 will have the checkout form work again
   
**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by unfulvio** [comment]
Proposed change:

`L558:`

```js
     if ( 'number' === typeof month ) {
        month = month.toString();
    }
    if ( 'number' === typeof year ) {
        year = year.toString();
    }
```

`L597`

```js
    if ( 'number' === typeof cvc ) {
        cvc = cvc.toString();
    }
```

**Comment by vanbo** [comment]
I can confirm the breaking change. When a number is passed for the month and year ("cardExpiryVal" returns each field as int) then the fields are nullified to '' instead of being converted to strings. This will break every gateway that offers browser validation. 

`month = 'string' === typeof month ? month.trim() : month.toString();`
`year = 'string' === typeof year ? year.trim() : year.toString();`
`cvc = 'string' === typeof cvc ? cvc.trim() : cvc.toString();`

**Comment by ObliviousHarmony** [comment]
Hello,

Thank you for reporting this issue. We are now working on a patch release to resolve it.

**Comment by acastro1-godaddy** [comment]
@ObliviousHarmony Thanks for your update.

I've also placed a PR with @unfulvio suggestions above per my team's request: https://github.com/woocommerce/woocommerce/pull/30072.

**Comment by ouija** [comment]
I can confirm that this change broke support with the latest version of the [Elavon Converge Payment Gateway](https://woocommerce.com/products/elavon-vm-payment-gateway/) and was resulting in a _"Card expiration date is invalid"_ at checkout, however, this only affected **guest checkout** and not when logged in to an (administrator) account.

**Comment by XenonofArcticus** [comment]
I'd like to second @ouija's situation. Spent hours tracking down and mitigating this one.

A secondary issue is that jquery.payment ( https://github.com/stripe-archive/jquery.payment ) is deprecated and retired by the author

>This repository has been archived by the owner. It is now read-only.
>Project status
>jquery.payment is deprecated. We recommend that you use either Stripe Checkout or Stripe Elements to collect card information.
>We will patch jquery.payment for major critical/security issues, but we won't be adding new features.

 and probably should be deprecated, replaced and eventually removed in WooCommerce and WooCommerce plugins.
