### ISSUE TITLE
Some article numbers disappearing

### ISSUE THREAD

**Issue by jeroenicks** [woocommerce/woocommerce#30079]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [ ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
WooCommerce some article numbers disappearing after a while form imported products.

**Expected behavior**
WooCommerce article numbers don't disappear. 

**Actual behavior**
After a while, the owner of the website who is managing the products sees that the article numbers of some imported products are gone. He is sure that he filled them in right a few months ago.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to 'products' on https://scorpione.nl
2. See error (error = imported products from March 1st with empty article numbers)

**Screenshots**
<img src="https://icks.eu/wp-content/uploads/2021/06/Screenshot-2021-06-10-at-15.54.05.png">

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</details>

**Comment by zhongruige** [comment]
Hi @jeroenicks,

Thank you for taking the time to report this issue! Unfortunately I cannot access your site, for that I would recommend bringing this issue through the WooCommerce support teams. If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/).

In the meantime, we can see if this is something we can reproduce in my environment. To help us further investigate this issue, it would be great if I get some more details to help us try and reproduce this error:

* In the report it was mentioned `imported products from March 1st`, were these products imported by CSV? And does this only affect products imported after March 1st, or even products that were in the store before March 1st as well?
* Is this happening with specific products or does it appear to be occurring on a variety of product types (simple, variable, etc.)?
* Which WooCommerce version is this occurring on? This can also be supplied through the `WordPress Environment` section below.

Additionally, if you can help fill out the following details that will help us to further investigate, too.

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>

Thank you in advance!
