### ISSUE TITLE
The Load Shipping adress and Copy billing adress links are no longer shown when editing the shipping address in the order in woocommerce admin

### ISSUE THREAD

**Issue by RichardFerlow** [woocommerce/woocommerce#30075]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Inside the order, when editing the billing and shipping addresses, the links - Load Shipping adress and Copy billing adress - do not appear as they did in version 5.3.0 and earlier. The bug appeared after updating to version 5.4.0

**Expected behavior**
It was expected that when clicking - edit shipping address, the load and copy adress links would appear

**Actual behavior**
links do not appear

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to any order in woocommerce admin
2. Click on 'edit shipping adress'
3. try to find Load shipping adress and Copy billing adress link

**Screenshots**
![Screenshot 2021-06-10 at 00 42 29](https://user-images.githubusercontent.com/12494003/121403132-d157f280-c984-11eb-8d4d-03a692f5feb6.png)
![Screenshot 2021-06-10 at 00 42 11](https://user-images.githubusercontent.com/12494003/121403136-d2891f80-c984-11eb-8c30-f4976d8e6a1d.png)

**Comment by zhongruige** [comment]
Hi @RichardFerlow,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. For this, I tested on the following:

* WordPress 5.7.2
* WooCommerce 5.3
* WooCommerce 5.4

**Replication steps**

* I navigated to `WooCommerce > Orders` and clicked on the `Add order` button at the top
* I compared the `Billing` and `Shipping` sections and noted the "load / copy" address actions are now missing from the Billing and Shipping sections
* I compared this to WooCommerce 5.3 and they showed as expected

<img width="1117" alt="Screen Shot 2021-06-09 at 12 07 26 PM" src="https://user-images.githubusercontent.com/71906536/121413340-d1270b00-c922-11eb-85ce-82dfbb800a42.png">

<img width="1112" alt="Screen Shot 2021-06-09 at 12 10 18 PM" src="https://user-images.githubusercontent.com/71906536/121413358-d4ba9200-c922-11eb-8b0a-8db039f8e09a.png">

We’re going to solve this bug as soon as possible. Stay tuned for updates.
