### ISSUE TITLE
 Refresh fragments infinite loop with multi cart session...

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce#30092]
Please add a hook to disable refresh fragments

Currently I'm developing a plugin to allow customer to choose which product to checkout based on vendor. (see screenshot)

https://i.stack.imgur.com/1dvHL.png

The basic idea is, when customer inside checkout page we will save 'real cart' into other session storage. Then start a fresh cart and include only items they choose to checkout.

When they go outside from checkout page, 'real cart' will be restored with previously saved data.

Now the problem is. If we open multiple cart and checkout page. It will cause infinite loop and crashing the server. Because get_refreshed_fragments think there is an updated cart and it will do refresh_cart_fragment.

**Comment by juliaamosova** [comment]
Hi @erikdemarco,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
@erikdemarco—just curious, is dequeueing `cart-fragments.js` something you've looked at as a solution? Or does not solve this/introduce other issues?

**Comment by simplysaru** [comment]
@erikdemarco Are you able to clarify the question from Barray above?

**Comment by erikdemarco** [comment]
Hi, I just unhooking it via js after the first refresh_cart_fragment call. I'm afraid dequeueing cart-fragments.js will have bad side effects.
