### ISSUE TITLE
5.4.1: add/remove order coupon should be logged in order notes

### ISSUE THREAD

**Issue by lkraav** [woocommerce/woocommerce#30104]
> Search tip: You can filter issues using our enhancement label https://github.com/woocommerce/woocommerce/issues?q=is%3Aissue+label%3Aenhancement

No matching issues found https://github.com/woocommerce/woocommerce/issues?q=is%3Aissue+coupon+%22order+notes

**Is your feature request related to a problem? Please describe.**
Some admin in a multi-admin stores incorrectly removes a coupon from a pending payment customer order.
Superviser looking into the matter has no idea if a coupon was ever applied to this order, because coupon add/remove operation leaves no trace of its action anywhere.

**Describe the solution you'd like**
All coupon operations logged in order notes.

**Describe alternatives you've considered**
Store admins manually write an order note for all coupon operations, but we all know that's a process broken by design.

**Additional context**
None.

**Comment by juliaamosova** [comment]
Hi @lkraav,

Thank you for taking the time to share this idea, we really appreciate your help. 

While this is clearly a great improvement/idea we won’t be able to tackle it in the upcoming weeks. We’re going to add it to our backlog where it will be considered for future releases.

**Comment by lkraav** [comment]
> While this is clearly a great improvement/idea we won’t be able to tackle it in the upcoming weeks. We’re going to add it to our backlog where it will be considered for future releases.

If WC team agrees this should be in core, my team can help create and file a PR towards this target.

**Comment by vedanshujain** [comment]
@lkraav This enhancement does make sense, we will prioritize the PR review if your team sends it. Feel free to tag me as well!

**Comment by lkraav** [comment]
@vedanshujain we have a PR now for 4 months here. Anything stopping this from moving forward?
