### ISSUE TITLE
Integrate with JetPack changelogger to support better changelogs and their compilation

### ISSUE THREAD

**Issue by vedanshujain** [woocommerce/woocommerce#30134]
**Is your feature request related to a problem? Please describe.**
[Jetpack changelogger](https://github.com/Automattic/jetpack-changelogger) allows specifying changelogs for each PR in a specified file, which can be compiled and merge easily at the time of release. It also encourages better changelog entries by using a configurable set of fields.

**Describe the solution you'd like**
- [ ] Add JP Changelogger as a dev only dependency.
- [ ] Configure it to comply WC's set of changes (dev, tweak, enhancement, performance, fix). Preferably add more for filters, actions and DB migrations.
- [ ] Add a GH Action that runs `changelogger validate` to verify that changelogger entry is added and is correctly formatted for every PR.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rrennick** [comment]
Addressed in https://github.com/woocommerce/woocommerce/pull/31136
