### ISSUE TITLE
Account page Addresses menu item translations bug

### ISSUE THREAD

**Issue by starypop** [woocommerce/woocommerce#30145]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When shipping in store is disabled, the Account page Addresses menu item has wrong translation as of Polish language rules. 

The bug is caused by passing values **0** or **1** as a value of the `$number` parameter to a `_n()` function here:

https://github.com/woocommerce/woocommerce/blob/b19500728b4b292562afb65eb3a0c0f50d5859de/includes/wc-account-functions.php#L102

Polish language has 3 plural forms: 
- 1
- 2, 3, 4
- 0, 5, 6, …

```
nplurals=3; plural=(n == 1) ? 0 : ((n % 10 >= 2 && n % 10 <= 4 && (n % 100 < 12 || n % 100 > 14)) ? 1 : 2);
```

It means that **0** and **2** values are in two different forms. 

Correct translation is:
- 1 - **Adres**
- 2, 3, 4 - **Adresy**
- 0, 5, 6, … - **Adresów**

But the current code expects the Polish translation to be wrong to meet its requirements and now it is like this:
- 1 - **Adresy**
- 2, 3, 4 - **Adres**
- 0, 5, 6, … - **Adres**

It is temporary fixed by providing wrong translations of plural forms but this translation could be used in the future in other components:
https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/pl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=2963977&filters%5Btranslation_id%5D=84948699 

**Expected behavior**
There should be a `_nx()` function instead of `_n()` used with a specific context to avoid possible bugs in the future. 

But passing an actual number of addresses as a value of the `$number` parameter to a `_n()` function and switching the `$single` and `$plural` parameters order to the correct one could be even better fix. In this case adding `+1` to the `(int) wc_shipping_enabled()` result could do the trick, but this could make possible difficulties for other languages.

As a result it should be translatable like this:
- shipping disabled, one address: **Adres** (form for 1 address) 
- shipping enabled, two addresses: **Adresy** (form for 2 addresses) 

**Actual behavior**
Now it is translatable like this:
- passed **0** as a value, but the current translation is singular, as for **1**. It is now translated as **Adres** (form for 1 address), but should be **Adresów** (form for 0 addresses).
- passed **1** as a value, but the current translation is plural, as for **2**. It is now translated as **Adresy** (form for 2 addresses), but should be **Adres** (form for 1 address).

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to WooCoomerce Settings.
2. Disable Shipping locations.
3. Go to Account page and take a look at the navigation.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://localhost:8888/test
Site address (URL): http://localhost:8888/test
WC Version: 5.4.1
REST API Version: ✔ 5.4.1
WC Blocks Version: ✔ 5.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.3.1
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: pl_PL
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Unix) OpenSSL/1.0.2u PHP/7.4.12 mod_wsgi/3.5 Python/2.7.13 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.11 Perl/v5.30.1
PHP Version: 7.4.12
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.0.2u

SUHOSIN Installed: –
MySQL Version: 5.7.32
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.4.1
WC Database Prefix: wp_
Całkowity rozmiar bazy danych: 3.63MB
Rozmiar bazy danych: 2.22MB
Rozmiar indeksu bazy danych: 1.41MB
wp_woocommerce_sessions: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_woocommerce_api_keys: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_woocommerce_attribute_taxonomies: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_woocommerce_downloadable_product_permissions: Dane: 0.02MB + Indeks: 0.06MB + Silnik InnoDB
wp_woocommerce_order_items: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_woocommerce_order_itemmeta: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_woocommerce_tax_rates: Dane: 0.02MB + Indeks: 0.06MB + Silnik InnoDB
wp_woocommerce_tax_rate_locations: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_woocommerce_shipping_zones: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_woocommerce_shipping_zone_locations: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_woocommerce_shipping_zone_methods: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_woocommerce_payment_tokens: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_woocommerce_payment_tokenmeta: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_woocommerce_log: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_actionscheduler_actions: Dane: 0.02MB + Indeks: 0.11MB + Silnik InnoDB
wp_actionscheduler_claims: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_actionscheduler_groups: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_actionscheduler_logs: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_commentmeta: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_comments: Dane: 0.02MB + Indeks: 0.09MB + Silnik InnoDB
wp_links: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_options: Dane: 1.38MB + Indeks: 0.06MB + Silnik InnoDB
wp_postmeta: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_posts: Dane: 0.02MB + Indeks: 0.06MB + Silnik InnoDB
wp_termmeta: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_terms: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_term_relationships: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_term_taxonomy: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_usermeta: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_users: Dane: 0.02MB + Indeks: 0.05MB + Silnik InnoDB
wp_wc_admin_notes: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_wc_admin_note_actions: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_wc_category_lookup: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_wc_customer_lookup: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_wc_download_log: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_wc_order_coupon_lookup: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_wc_order_product_lookup: Dane: 0.02MB + Indeks: 0.06MB + Silnik InnoDB
wp_wc_order_stats: Dane: 0.02MB + Indeks: 0.05MB + Silnik InnoDB
wp_wc_order_tax_lookup: Dane: 0.02MB + Indeks: 0.03MB + Silnik InnoDB
wp_wc_product_meta_lookup: Dane: 0.02MB + Indeks: 0.09MB + Silnik InnoDB
wp_wc_reserved_stock: Dane: 0.02MB + Indeks: 0.00MB + Silnik InnoDB
wp_wc_tax_rate_classes: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB
wp_wc_webhooks: Dane: 0.02MB + Indeks: 0.02MB + Silnik InnoDB

### Post Type Counts ###

attachment: 1
page: 6
post: 3
product: 1

### Security ###

Secure connection (HTTPS): ❌
					Twój sklep nie używa protokołu HTTPS. Dowiedz się więcej o HTTPS i certyfikatach SSL .
Hide errors from visitors: ❌Komunikaty o błędach nie powinny być widoczne dla użytkowników.

### Active Plugins (1) ###

WooCommerce: przez Automattic – 5.4.1

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: PLN (zł)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Strona sklepu: #6 - /sklep/
Koszyk: #7 - /koszyk/
Zamówienie: #8 - /zamowienie/
Moje konto: #9 - /moje-konto/
Regulamin: ❌ Strona nie ustawiona

### Theme ###

Name: Twenty Twenty-One
Version: 1.3
Author URL: https://pl.wordpress.org/
Child Theme: ❌ – Jeśli modyfikujesz WooCommerce lub motyw nadrzędny
którego nie jesteś autorem
polecamy używanie motywu potomnego. Zobacz: Jak tworzyć motywy potomne

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Zrealizowane: 3
Oldest: 2021-06-21 14:52:55 +0200
Newest: 2021-06-22 11:47:22 +0200


### Status report information ###

Generated at: 2021-06-22 12:27:24 +02:00
`
```
</details>

**Comment by rodelgc** [comment]
Hi @starypop,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
- The relevant code has been updated, and we now [+1 to the value](https://github.com/woocommerce/woocommerce/blob/8.6.1/plugins/woocommerce/includes/wc-account-functions.php#L102).
- This change was made via https://github.com/woocommerce/woocommerce/pull/32026
- If there are further problems, please do create a fresh issue (or upvote any other existing issues that are relevant).

```php
'edit-address'    => _n( 'Address', 'Addresses', ( 1 + (int) wc_shipping_enabled() ), 'woocommerce' )
```
