### ISSUE TITLE
Email Verification During Registration...

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce#30146]
When user register via my-account page, with random email and password. Woocommerce will just create an account and make that user logged in automatically.

This is very wrong. And woocommerce can be easily spammed by sending fake registration data thousand of times per minute. And our site will gets down easily.

Please make a email verification a default. Its already implemented in core wordpress. So we dont need to make huge changes to woocommerce code.

**Comment by rodelgc** [comment]
Hi @erikdemarco,

Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project.

For the meantime, you could use plugins like https://wordpress.org/plugins/emails-verification-for-woocommerce/ to enable email verification prior to customer login.

If you or anyone in the community would be willing to submit a PR for this, we'd be very happy to consider it as long as it is implemented as an additional setting and doesn't modify the default behavior.

At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the `votes needed` label and evaluate over time if this issue collects more feedback.

Don’t be alarmed if you don’t see any activity on this issue for a while.
