### ISSUE TITLE
[GlobalStep] User should not be able to hide "Order", "Order actions" and "Order data" columns on Order and Edit Order screens. 

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#30158]
## Bug Description:
User is able to hide "Order", "Order actions" and "Order data" columns on Order and Edit Order screens.

## Environment:
Woocommerce Version : WooCommerce 5.5.0 Beta and 5.4.1
WordPress version: v5.8-beta3-51218

PC:
Windows 10, Mac 10.14.6
Chrome(Version 91.0.4472.77) 
Firefox(Version 88.0)
Safari: v13.1.1

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Complete the OBW setup.
1. Add some products.
1. Create some orders.
1. Go to WooCommerce->Orders.
1. Click on Screen options button.
1. Now hide the order column.
1. Observe that user is able to hide the order column.

## Note:
The same behaviour is observed for "Order actions" and "Order data" columns on Edit order screen.

## Actual Result:
User is able to hide "Order", "Order actions" and "Order data" columns on Order and Edit Order screens.

## Expected Result:
User should not be able to hide "Order", "Order actions" and "Order data" columns on Order and Edit Order screens.

## Screenshot:

![#30158_1](https://user-images.githubusercontent.com/41110392/123288988-ab5a5280-d52d-11eb-90a4-2726ac640781.png)
![#30158_2](https://user-images.githubusercontent.com/41110392/123289007-af867000-d52d-11eb-9d38-e8e948cc416a.png)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment]
Hi @gglobalstep ,

Thank you for taking the time to share this idea, we really appreciate your help. 

As discussed over on Slack, we will mark it as an enhancement.

It doesn’t fit in with our current priorities for the project. But at some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the `votes needed` label and evaluate over time if this issue collects more feedback. 

Don’t be alarmed if you don’t see any activity on this issue for a while.
