### ISSUE TITLE
Negative fees can't cover the 100% of the user cart

### ISSUE THREAD

**Issue by Epizefiri** [woocommerce/woocommerce#30162]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
The negative fees are not covering the 100% of the user cart. If the user have a cart of 60€ ( 22% of VAT included ) and I assign to the user a negative fee of 60€ Woocommerce changes the fee to 49.18€ 

**Expected behavior**
I expect that the negative fees can cover the 100% of the cart ( and not just the cart before taxes ), or at least i expect a filter in the wc-cart-totals class to change this behavior.

**Actual behavior**
In WC_Cart_Totals->get_fees_from_cart() if we have in the cart a negative fee, the negative fee can't be bigger than the total amount of the cart Before taxes. That makes impossible to create a negative fee of the 100% of the cart.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

</details>

**Comment by simplysaru** [comment]
Hi @Epizefiri ,

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
