### ISSUE TITLE
Tax Settings: '*' placeholder in Tax Rate fields is unclear

### ISSUE THREAD

**Issue by jordesign** [woocommerce/woocommerce#30161]
**Is your feature request related to a problem? Please describe.**

When adding Tax rates - the placeholder values for the fields is currently an asterix. This seems a little unclear as to if this makes it a required field, or if it is somekind of regex 'wildcard' value in those fields.

The confusion is amplified by the fact the 'help' tooltip mentions those fields can be left blank - but when they *are* left blank the `*` is shown anyway.

**Describe the solution you'd like**
Could the placeholder be updated to something like 'All' or 'Any' which better matched the functionality of the field when there is no custom value?

**Describe alternatives you've considered**

It would also be possible to just leave the field blank with no placeholder.

**Additional context**

<img width="1157" alt="Screen Shot 2021-06-24 at 1 36 50 pm" src="https://user-images.githubusercontent.com/1842363/123334408-657da880-d586-11eb-8121-af9bc76fbe2f.png">

**Comment by rodelgc** [comment]
Hi @jordesign,

Thank you for taking the time to share this idea, we really appreciate your help. 

> This seems a little unclear... ...if it is somekind of regex 'wildcard'

The tooltip says we can "Leave it blank _**to apply to all**"_. The _"...to apply to all"_ part clarifies that the asterisk placeholder is indeed a wildcard.

> ...the 'help' tooltip mentions those fields can be left blank

True, although we should consider that this is just half of what the tooltip mentioned. It also has a  _"...to apply to all"_ part:
<img width="309" alt="Screen Shot 2021-06-25 at 3 31 23 PM" src="https://user-images.githubusercontent.com/4509348/123388707-ac41c180-d5cb-11eb-9f99-3c588c30f9a6.png">
Therefore, having an asterisk (wildcard) as a placeholder when it is blank would be very much consistent with what the tooltip mentioned.

However, I agree that your suggestion to instead have an "All" or "Any" placeholder will be a better user experience to users who may not be familiar with wildcards, or haven't had the chance to read the tooltip or were still confused by it.

It doesn’t fit in with our current priorities for the project, though. But at some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the `votes needed` label and evaluate over time if this issue collects more feedback. 

Don’t be alarmed if you don’t see any activity on this issue for a while.

**Comment by jordesign** [comment]
Thanks for the explanation @rodelgc - appreciate it.
