### ISSUE TITLE
Add description field for shipping methods

### ISSUE THREAD

**Issue by vallter2** [woocommerce/woocommerce#30160]
It will be nice to add new field in shipping methods for description of method, and display it on cart and checkout page below shipping method...

**Comment by rodelgc** [comment]
Hi @vallter2,

Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the `votes needed` label and evaluate over time if this issue collects more feedback. 

Don’t be alarmed if you don’t see any activity on this issue for a while.
