### ISSUE TITLE
defaults for salutation/gender in customer form

### ISSUE THREAD

**Issue by OtherSystems** [woocommerce/woocommerce#30170]
EDIT: This issue was filed based on incorrect information. My sincere apologies for wasting everyone's time. 

By default woocommerce asks customers for their salutations/gender (aanhef in dutch) and provides only two options and makes the choice mandatory. This is adjustable, but few webshops will do that.

While this already excludes intersex and non-binary people from correctly filling in the form, it also discloses the sex/gender of the customer even if this is irrelevant for the transaction (which it is most of the time), forcing them to disclose personal information for which they may get discriminated on. 

As excluding customers by default seems to be a bug for an selling platform, I would propose the following fixes to be in the default setup:

* Remove the field all together
* Make it optional
* Add more options if it really is needed.

**Comment by DavidAnderson684** [comment]
> By default woocommerce asks customers for their salutations/gende

This is not the case.

**Comment by OtherSystems** [comment]
That is good to hear, this would be about the dutch version. This is what is claimed by the reseller mpluswebshops.nl. 

Sorry if I have been mis-informed, but I found it on this website, and the reseller claims it's default in woocommerce.

![image](https://user-images.githubusercontent.com/25455376/123681954-b45b6480-d84a-11eb-8596-49840ab06dcc.png)

Is there a way to verify this without having to setup a server + woocommerce + wordpress enviroment?

**Comment by OtherSystems** [comment]
Looks like I have been misinformed. My apologies for wasting your time and thank you for making such a great product!
