### ISSUE TITLE
Woocommerce home page is blank 

### ISSUE THREAD

**Issue by tripathimarut** [woocommerce/woocommerce#30171]
woocommerce dashboard/admin area is blank 

**Expected behavior**
Admin Dashboard has to be there so I can setup my Woocommerce 

**Actual behavior**
It's Just shows blank white page only in dashboard section of woocommerce orders section are available

`
### WordPress Environment ###

WordPress address (URL): https://travjo.com
Site address (URL): https://travjo.com
WC Version: 5.4.1
REST API Version: ✔ 5.4.1
WC Blocks Version: ✔ 5.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.3.1
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.20
PHP Post Max Size: 256 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.34-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.4.1
WC Database Prefix: wpqk_
Total Database Size: 5.35MB
Database Data Size: 3.87MB
Database Index Size: 1.48MB
wpqk_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqk_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqk_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqk_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpqk_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqk_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqk_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpqk_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqk_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqk_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqk_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqk_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqk_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wpqk_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqk_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqk_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqk_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqk_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpqk_hotel_room: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqk_options: Data: 2.47MB + Index: 0.03MB + Engine InnoDB
wpqk_postmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqk_posts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpqk_st_activity: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_st_activity_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqk_st_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqk_st_cars: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_st_cronjob_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_st_flights: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_st_flight_airport: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_st_flight_availability: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_st_flight_location: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_st_form_builder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_st_hotel: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_st_inbox: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_st_journey_car: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_st_location_nested: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_st_location_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_st_member_packages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_st_member_packages_order: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_st_order_item_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_st_price: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_st_properties: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_st_rental: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_st_rental_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqk_st_room_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqk_st_tours: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_st_tour_availability: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqk_st_user_online: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_st_withdrawal: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqk_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqk_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqk_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqk_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqk_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqk_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqk_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqk_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqk_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqk_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpqk_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpqk_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpqk_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wpqk_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpqk_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpqk_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 1
option-tree: 1
page: 6
post: 2
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (6) ###

Contact Form 7: by Takayuki Miyoshi – 5.4.1
WPBakery Page Builder: by Michael M - WPBakery.com – 6.6.0
MC4WP: Mailchimp for WordPress: by ibericode – 4.8.6
OptionTree: by Derek Herman – 2.7.4
Traveler-code: by Shinetheme – 2.8.9
WooCommerce: by Automattic – 5.4.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.9
Hello Dolly: by Matt Mullenweg – 1.7.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: ()
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #8 - /shop/
Cart: #9 - /cart/
Checkout: #10 - /checkout/
My account: #11 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Traveler
Version: 2.9.3
Author URL: http://www.shinetheme.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: traveler/woocommerce/archive-product.php
traveler/woocommerce/cart/cart-empty.php
traveler/woocommerce/cart/cart.php
traveler/woocommerce/checkout/form-checkout.php
traveler/woocommerce/checkout/form-coupon.php
traveler/woocommerce/checkout/review-order.php
traveler/woocommerce/checkout/thankyou.php
traveler/woocommerce/content-product.php
traveler/woocommerce/content-single-product.php
traveler/woocommerce/content-widget-product.php
traveler/woocommerce/global/breadcrumb.php
traveler/woocommerce/global/sidebar.php
traveler/woocommerce/loop/orderby.php
traveler/woocommerce/loop/pagination.php
traveler/woocommerce/loop/result-count.php
traveler/woocommerce/loop/sale-flash.php
traveler/woocommerce/order/order-details.php
traveler/woocommerce/product-searchform.php
traveler/woocommerce/single-product/product-attributes.php
traveler/woocommerce/single-product/sale-flash.php
traveler/woocommerce/single-product/tabs/additional-information.php
traveler/woocommerce/single-product/tabs/description.php
traveler/woocommerce/single-product-reviews.php

### Action Scheduler ###

Complete: 1
Oldest: 2021-06-28 17:05:10 +0000
Newest: 2021-06-28 17:05:10 +0000

### Status report information ###

Generated at: 2021-06-28 17:17:14 +00:00
`

```
</details>
![Screenshot (104)](https://user-images.githubusercontent.com/86621192/123677412-b7fae580-d862-11eb-8848-a3f00e76b1ca.png)

**Comment by tripathimarut** [comment]
![Screenshot (107)](https://user-images.githubusercontent.com/86621192/123728933-c3c1c880-d8b1-11eb-9b0d-7e7bd3185896.png)
![Screenshot (108)](https://user-images.githubusercontent.com/86621192/123728953-cae8d680-d8b1-11eb-93f1-59e10899c979.png)

**Comment by tammullen** [comment]
Hi @tripathimarut ,

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.
