### ISSUE TITLE
view_woocommerce_reports capability adds Analytics and Marketing to admin menu, but no access to these pages

### ISSUE THREAD

**Issue by mootunes** [woocommerce/woocommerce#30182]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Adding the view_woocommerce_reports capbility adds buttons to the admin menu for Analytics and Marketing, but clicking on them gives a "you don't have access to this page" error. The issue appears to first appear in version 5.2. In version 5.1, users have access to these sections.

**Expected behavior**
I would expect either the menu options not to appear, or the user to have access. As the capability is to access reports, I would expect to have access to the Analytics section at minimum.

**Actual behavior**
The user is presented with buttons to sections they can not access.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Add the view_woocommerce_reports capability to a user role, and ensure they do not have the manage_woocommerce capability.
2. Log in as a user with that role.
3. Click on the 'Analytics' or 'Marketing' buttons in the admin menu.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): http://test2.mootunes.local
Site address (URL): http://test2.mootunes.local
WC Version: 5.4.1
REST API Version: ✔ 5.4.1
WC Blocks Version: ✔ 5.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.3.1
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_AU
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.46 (Win64) PHP/7.3.21
PHP Version: 7.3.21
PHP Post Max Size: 8 MB
PHP Time Limit: 120
PHP Max Input Vars: 2500
cURL Version: 7.70.0
OpenSSL/1.1.1g

SUHOSIN Installed: –
MySQL Version: 5.7.31
Max Upload Size: 1 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.5.0
WC Database Prefix: wp_4_
Total Database Size: 1.73MB
Database Data Size: 1.40MB
Database Index Size: 0.33MB
wp_4_woocommerce_sessions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_4_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_4_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_4_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_4_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_4_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_4_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_4_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_4_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_4_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_4_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_4_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_4_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_4_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_4_actionscheduler_actions: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
wp_4_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_4_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_4_actionscheduler_logs: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_4_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_4_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_4_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_4_options: Data: 1.10MB + Index: 0.05MB + Engine MyISAM
wp_4_postmeta: Data: 0.09MB + Index: 0.07MB + Engine MyISAM
wp_4_posts: Data: 0.08MB + Index: 0.03MB + Engine MyISAM
wp_4_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_4_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_4_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_4_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_4_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_4_wc_admin_note_actions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_4_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_4_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_4_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_4_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_4_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_4_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_4_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_4_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_4_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_4_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_4_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_4_wpmailsmtp_tasks_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_4_yikes_easy_mc_forms: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_blogmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_blogs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_registration_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_signups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_site: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_sitemeta: Data: 0.06MB + Index: 0.01MB + Engine MyISAM
wp_usermeta: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM

### Post Type Counts ###

attachment: 6
custom_css: 1
customize_changeset: 2
et_body_layout: 2
et_footer_layout: 1
et_pb_layout: 12
et_template: 3
et_theme_builder: 1
mootunes_album: 11
mootunes_payment: 6
nav_menu_item: 3
page: 12
post: 19
product: 5
revision: 8
shop_coupon: 101
shop_order: 3

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

WooCommerce: by Automattic – 5.4.1
Role Adjust: by  –

### Inactive Plugins (9) ###

Controlled Admin Access: by WPRuby – 1.5.12
Divi Module Builder: by DiviPlugins – 2.2
Divi Module Builder - Plugin Creator: by DiviPlugins – 2.1
Easy Forms for Mailchimp: by YIKES
Inc. – 6.8.4

MooTunes Plugin: by MooTunes – 2
Songkick Concerts and Festivals: by Sabrina Leandro – 0.9.4.9
WooCommerce Conditional Shipping and Payments: by SomewhereWarm – 1.7.3
WooCommerce Stripe Gateway: by WooCommerce – 5.2.3
WP Mail SMTP: by WPForms – 2.8.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: AUD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #8 - /shop/
Cart: #4 - /cart/
Checkout: #5 - /checkout/
My account: #6 - /my-account/
Terms and conditions: #9 - /terms-and-conditions/

### Theme ###

Name: Twenty Twenty-One
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 44
Oldest: 2021-06-24 01:26:48 +0000
Newest: 2021-06-30 03:27:03 +0000

### Status report information ###

Generated at: 2021-06-30 11:36:46 +08:00
`
</details>

**Comment by tammullen** [comment]
Hi @mootunes 

Thank you for reporting the issue. This is part of WooCommerce Admin which is being developed in another repository: https://github.com/woocommerce/woocommerce-admin.
This issue had been reported previously here https://github.com/woocommerce/woocommerce-admin/issues/7061. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
