### ISSUE TITLE
Add has_options() to REST API response for products

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce#30187]
**Is your feature request related to a problem? Please describe.**
When 3rd party social sites display products (in Facebook, shopify, peepso) they typically use a "Buy now" button. However, some product types require configuration before they can be added to the cart (ex: Mix and Match products, products with Name Your Price, products with required Product Addons, etc). Currently there is no uniform way for the 3rd party to know if the products requires configuration.

Related: https://github.com/woocommerce/facebook-for-woocommerce/issues/1192

**Describe the solution you'd like**
Add the result of `has_options()` to the REST API response for products. I think this could be a relatively painless way to give 3rd parties the information they need about how to correctly display the product's "buy now" button. 

**Describe alternatives you've considered**
Currently, I think the only option is each service writes custom handlers for each product type or plugin. For example, I'd expect most handle variable and grouped products by showing a "select options" (or similar) type of button in lieu of "buy now" since those are core types.

**Comment by helgatheviking** [comment]
https://woocommerce.com/products/google-listings-and-ads might also benefit

**Comment by tammullen** [comment]
Hi @helgatheviking!

Thank you for taking the time to share this idea, we really appreciate your help! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 
​
Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by roykho** [comment]
Hi @helgatheviking - thanks for raising this. I see you pointed out several examples of 3rd party plugins that could benefit from this however could you please give us a more concrete idea on how you foresee this to work? Perhaps you would like to submit a PR so we can better see the technical side of it?

**Comment by helgatheviking** [comment]
Hi @roykho been away at training camp... on the woo side, I'm asking for `has_options` to be added as an additional property in the REST product response.

Currently, a 3rd party platform (such as Facebook of Google) that is displaying products in places _not_ on the store's site. will display products as "Cool Product $99: Buy now button". That's fine for default simple products. 

But there's no way for the 3rd party to know if a product _can_ be added to the cart directly. What if it's a Name Your Price product and needs a price? Or Mix and Match and needs a configuration? Or Product Addons with a required addon? 

what happens now when a (for example) Name your price product is displayed with a "buy now" button at facebook... is that a customer clicks on that and that brings them to the Woo checkout. Woo tries to add it to the cart, but the NYP validation fails since there's no product. so the customer gets to the checkout but there's an error message... and probably an empty cart. the only current solution is to disable the "buy now" buttons entirely, but why should they have to disable that for products that support it?

currently I assume the 3rd parties are already handling variable products with custom code. to then handle compat with different plugins becomes a game of whack-a-mole. Each 3rd party would need to do it for an infinite number of plugins. it's impossible.

Instead, I'm envisioning...

1. plugins that require options can filter `has_options`. I already do this to improve compat with NYP and the product block. 
2. On the Woo side, you'll include `has_options` in the REST result. 
3. Then the 3rd party can check for the REST property.... they can correctly (and universally) determine whether they should display a "buy now" button _or_ a "view product" button. Ideally it would incorporate any custom add to cart text, but I don't know if that's in the REST response. In cases where products have options that require configuration, the 3rd parties can update their display to account for this and direct the customer to the page where they can make their selections. This way they don't end up in the checkout with error messages.

**Comment by roykho** [comment]
Hi @helgatheviking - so I think I see what you're saying however does 3rd party even interact with WC at all? Aren't they just showing whatever they get back as a response and spitting that out directly?

**Comment by helgatheviking** [comment]
>Aren't they just showing whatever they get back as a response and spitting that out directly?

Tbh, I am not sure how the 3rd parties decide what to display. I don't have any access to the Facebook side of things.

I've been working from the assumption that they hit the REST API product endpoint and use that info to generate an output. That's why I wanted to give them the info about whether the item had options or not so they can adjust their display accordingly.

**Comment by barryhughes** [comment]
Taking a fresh look, this seems reasonable and we'd be happy to look at a PR if you wished to submit one (@helgatheviking)?

**Comment by helgatheviking** [comment]
Hi @barryhughes I took a stab at it... let me know what needs changing.
