### ISSUE TITLE
Variable product download displaying HTML when adding to Order Downloadable product permissions

### ISSUE THREAD

**Issue by stuartduff** [woocommerce/woocommerce#30198]
Support: 4108222-zen

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When on the order edit screen and you grant access to a downloadable file from a variable product the HTML of `<span class=description"></span>` is displaying after selecting the download.

![Screen Capture on 2021-07-01 at 13-07-30](https://user-images.githubusercontent.com/1190565/124121925-62465900-da6d-11eb-83af-d89d318e8ff3.gif) 

**Expected behavior**
We would expect the download to not display `<span class=description"></span>` after the title.

**Actual behavior**
A clear and concise description of what actually happens. Please be as descriptive as possible; 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create a variable product with a downloadable file attached.
2. Visit the order edit screen.
3. Search for that downloadable file in Downloadable product permissions
4. See error.

**Screenshots**

**Variable Product Download**
![Screen Shot on 2021-07-01 at 13:12:55](https://user-images.githubusercontent.com/1190565/124122528-16e07a80-da6e-11eb-9485-3c51b82acc3e.png)

**Order Downloadable product permissions**

![Screen Capture on 2021-07-01 at 13-07-30](https://user-images.githubusercontent.com/1190565/124122589-2790f080-da6e-11eb-85d9-f7abf47217a5.gif)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**

I was able to replicate the behaviour with only these products activated.

WordPress: v5.7.2
WooCommerce: v5.4.1
Storefront & Twenty Twenty-One themes activated.

**Comment by tammullen** [comment]
Hi @stuartduff ,

Thank you for taking the time to report this bug, we really appreciate your help. I can reproduce it on my end. 
![Screenshot 2021-07-02 at 13 04 34](https://user-images.githubusercontent.com/24649833/124272768-18c24080-db37-11eb-9a58-e5ec88e16fa2.png)


Related: This had been previously happening elsewhere https://github.com/woocommerce/woocommerce/issues/27154 but was fixed for those others areas.
