### ISSUE TITLE
Revise docblock for wc_format_decimal()

### ISSUE THREAD

**Issue by barryhughes** [woocommerce/woocommerce#30192]
It was flagged that the [existing description for `wc_format_decimal()`](https://github.com/woocommerce/woocommerce/blob/5.4.1/includes/wc-formatting-functions.php#L281) is causing some confusion, because it reads as if decimals are always stripped.

**Describe the solution you'd like**

We could change:

> Sanitize, remove decimals, and optionally round + trim off zeros.

To:

> Sanitize, **optionally** remove decimals, and optionally round + trim off zeros.

**Additional context**

Internal links:

- p1625003311174800-slack-CSP74N77C
- p1625076165130100-slack-C0E1AV8T0

**Comment by RhnSharma** [comment]
I would like to take this one. Is this up for grabs?

**Comment by vedanshujain** [comment]
@RhnSharma feel free to take it up

**Comment by helgatheviking** [comment]
Yes! I was just asking about `wc_format_decimal()` and trying to verify the format of the values it returns. My current understanding of this [`preg_replace`](https://github.com/woocommerce/woocommerce/blob/5.4.1/includes/wc-formatting-functions.php#L296) is that it should always return a number with a period decimal. 

Probably a bigger lift, but is there a reason `wc_format_decimal()` does _not_ remove the thousands separator?
