### ISSUE TITLE
Order status resets itself when refreshing order-received page

### ISSUE THREAD

**Issue by lensbreak** [woocommerce/woocommerce#30202]
**Describe the bug**
Order status resets itself when refreshing order-received page

**Expected behavior**
Refreshing the order complete page after checkout should not affect changes made on the order status that has been made meanwhile in the backend by a shop manager. Also if the customer clicks the back button and then forward button in browser it should not affect anything regarding the already made order.

**Actual behavior**
Refreshing order-received page changes the order status to "processing" regardless what status it had before. Even worse, the customer receives multiple same emails everytime this page is refreshed if the status had changed again by a shop manager (the latter is expected behaviour of course but makes the situation bad because customers are getting confused).

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
1. Go to any product in Browser A
2. Click on checkout and buy the product as a guest in Browser A
3. On a different browser B: Login to wordpress backend and change the order status from "processing" to "on hold"
4. Refresh the order-received page or click back and forward in Browser A
5. Refresh the shop_order page in the backend in Browser B and see the status macigally chaning back to "processing"

### WordPress Environment ###

WC Version: 5.4.1
REST API Version: ✔ 5.4.1
WC Blocks Version: ✔ 5.1.0
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.3.1
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_CH
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.16
PHP Post Max Size: 50 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 7.71.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.26-log-cll-lve
Max Upload Size: 50 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.4.1
WC Database Prefix: cms_

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Settings ###

API Enabled: –
Force SSL: –
Currency: CHF (CHF)
Currency Position: left_space
Thousand Separator: '
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)
variation (variation)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: #9 - /shop/
Warenkorb: #10 - /warenkorb/
Kasse: #11 - /kasse/
Mein Konto: #12 - /mein-konto/
Allgemeine Geschäftsbedingungen: #169 - /unternehmen/agb/

### Theme ###

Name: Porto Child
Version: 1.1
Author URL: https://www.portotheme.com/
Child Theme: ✔
Parent Theme Name: Porto
Parent Theme Version: 6.1.2
Parent Theme Author URL: http://www.portotheme.com/
WooCommerce Support: ✔

### Templates ###

Overrides: porto/woocommerce/archive-product.php
porto/woocommerce/cart/cart-empty.php
porto/woocommerce/cart/cart-shipping.php
porto/woocommerce/cart/cart-totals.php
porto/woocommerce/cart/cart.php
porto/woocommerce/cart/cross-sells.php
porto/woocommerce/cart/mini-cart.php
porto/woocommerce/cart/proceed-to-checkout-button.php
porto/woocommerce/cart/shipping-calculator.php
porto/woocommerce/checkout/form-billing.php
porto/woocommerce/checkout/form-checkout.php
porto/woocommerce/checkout/form-coupon.php
porto/woocommerce/checkout/form-login.php
porto/woocommerce/checkout/form-pay.php
porto/woocommerce/checkout/form-shipping.php
porto/woocommerce/checkout/payment-method.php
porto/woocommerce/checkout/payment.php
porto/woocommerce/checkout/review-order.php
porto/woocommerce/checkout/thankyou.php
porto/woocommerce/content-product-cat.php
porto/woocommerce/content-product.php
porto/woocommerce/content-single-product.php
porto/woocommerce/content-widget-product.php
porto/woocommerce/global/form-login.php
porto/woocommerce/global/quantity-input.php
porto/woocommerce/global/wrapper-start.php
porto/woocommerce/loop/add-to-cart.php
porto/woocommerce/loop/loop-end.php
porto/woocommerce/loop/loop-start.php
porto/woocommerce/loop/no-products-found.php
porto/woocommerce/loop/orderby.php
porto/woocommerce/loop/pagination.php
porto/woocommerce/loop/rating.php
porto/woocommerce/loop/sale-flash.php
porto/woocommerce/myaccount/dashboard.php
porto/woocommerce/myaccount/downloads.php
porto/woocommerce/myaccount/form-add-payment-method.php
porto/woocommerce/myaccount/form-edit-account.php
porto/woocommerce/myaccount/form-edit-address.php
porto/woocommerce/myaccount/form-login.php
porto/woocommerce/myaccount/form-lost-password.php
porto/woocommerce/myaccount/form-reset-password.php
porto/woocommerce/myaccount/lost-password-confirmation.php
porto/woocommerce/myaccount/my-account.php
porto/woocommerce/myaccount/my-address.php
porto/woocommerce/myaccount/my-downloads.php
porto/woocommerce/myaccount/my-orders.php
porto/woocommerce/myaccount/navigation.php
porto/woocommerce/myaccount/orders.php
porto/woocommerce/myaccount/payment-methods.php
porto/woocommerce/myaccount/view-order.php
porto/woocommerce/order/form-tracking.php
porto/woocommerce/order/order-details-customer.php
porto/woocommerce/order/order-details.php
porto/woocommerce/order/order-downloads.php
porto/woocommerce/order/tracking.php
porto/woocommerce/single-product/add-to-cart/simple.php
porto/woocommerce/single-product/add-to-cart/variable.php
porto/woocommerce/single-product/meta.php
porto/woocommerce/single-product/product-attributes.php
porto/woocommerce/single-product/product-image.php
porto/woocommerce/single-product/product-thumbnails.php
porto/woocommerce/single-product/rating.php
porto/woocommerce/single-product/related.php
porto/woocommerce/single-product/review-meta.php
porto/woocommerce/single-product/review-rating.php
porto/woocommerce/single-product/review.php
porto/woocommerce/single-product/sale-flash.php
porto/woocommerce/single-product/short-description.php
porto/woocommerce/single-product/tabs/tabs.php
porto/woocommerce/single-product/title.php
porto/woocommerce/single-product/up-sells.php
porto/woocommerce/single-product-reviews.php

### Action Scheduler ###

Complete: 502
Oldest: 2021-06-01 03:44:38 +0200
Newest: 2021-07-02 02:20:38 +0200

Pending: 6
Oldest: 2021-07-02 04:16:58 +0200
Newest: 2021-07-09 01:19:08 +0200

### Status report information ###

Generated at: 2021-07-02 02:36:47 +02:00

**Comment by tammullen** [comment]
Hi @lensbreak 

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

Refreshing the Order received page of a guest order did not update the order status in WooCommerce > Orders.

Please confirm if you performed initial troubleshooting such as testing for theme and plugins conflict on your site? To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as Storefront. Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

**Comment by lkraav** [comment]
I agree, this sounds very much like some other plugin or the theme is doing something wrong.

**Comment by 4bshalom** [comment]
have you resolved it, i'm facing the same issue
