### ISSUE TITLE
Postal code labels are partially incorrect for US & India

### ISSUE THREAD

**Issue by getsnoopy** [woocommerce/woocommerce#30203]
**Prerequisites:**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
The label shown for postal codes during checkout are partially incorrect for the US and India.

**Expected behaviour**
For the US, it should read as "ZIP Code". For India, it should read as "PIN".

**Actual behaviour**
For the US, it reads as "ZIP". For India, it reads as "Pin code".

**Steps to reproduce the bug**
1. Go to any checkout page that has at least the US & India enabled in the zone.
2. See that the postal code label reads "ZIP" by default or if the US is selected as the country.
3. Change the country to "India".
4. See that the postal code label reads "Pin code".

**Screenshots**

![Screenshot 2021-07-01 235850](https://user-images.githubusercontent.com/2997884/124223094-a4e94f00-dac8-11eb-91f6-031c8fef0e23.png)

![Screenshot 2021-07-01 235922](https://user-images.githubusercontent.com/2997884/124223126-b7fc1f00-dac8-11eb-8e75-8fe297f04e13.png)

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>

### WordPress Environment ###

WC Version: 5.4.1
REST API Version: ✔ 5.4.1
WC Blocks Version: ✔ 5.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.3.1
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.20
PHP Post Max Size: 516 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.77.0
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 5.6.41-84.1
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.4.1
WC Database Prefix: qayry_
Total Database Size: 9.63MB
Database Data Size: 7.51MB
Database Index Size: 2.12MB
qayry_woocommerce_sessions: Data: 0.29MB + Index: 0.01MB + Engine MyISAM
qayry_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
qayry_woocommerce_tax_rates: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
qayry_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
qayry_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_actionscheduler_actions: Data: 0.39MB + Index: 0.08MB + Engine MyISAM
qayry_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
qayry_actionscheduler_logs: Data: 0.12MB + Index: 0.10MB + Engine MyISAM
qayry_aiowps_events: Data: 0.49MB + Index: 0.08MB + Engine MyISAM
qayry_aiowps_failed_logins: Data: 0.08MB + Index: 0.03MB + Engine MyISAM
qayry_aiowps_global_meta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_aiowps_login_activity: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
qayry_aiowps_login_lockdown: Data: 0.08MB + Index: 0.02MB + Engine MyISAM
qayry_aiowps_permanent_block: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_comments: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
qayry_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_options: Data: 1.92MB + Index: 1.41MB + Engine MyISAM
qayry_postmeta: Data: 1.06MB + Index: 0.13MB + Engine MyISAM
qayry_posts: Data: 3.01MB + Index: 0.12MB + Engine MyISAM
qayry_ps_groups: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_ps_group_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_ps_security: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_termmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
qayry_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_usermeta: Data: 0.01MB + Index: 0.02MB + Engine MyISAM
qayry_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
qayry_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
qayry_wc_admin_note_actions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
qayry_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_wc_customer_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
qayry_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_wc_order_product_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
qayry_wc_order_stats: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
qayry_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
qayry_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
qayry_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
qayry_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
qayry_woocommerce_termmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 834
custom_css: 1
nav_menu_item: 16
page: 174
product: 14
revision: 52
shop_order: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (14) ###

All In One WP Security: by Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.4.8

Classic Editor: by WordPress Contributors – 1.6
Genesis Connect for WooCommerce: by StudioPress – 1.1.1
Jetpack: by Automattic – 9.8.1
Safe SVG: by Daryll Doyle – 1.9.9
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com

W3 Total Cache: by BoldGrid – 2.1.5
WooCommerce Admin: by WooCommerce – 2.3.1
WooCommerce Stripe Gateway: by WooCommerce – 5.2.3
WooCommerce Shipping & Tax: by WooCommerce – 1.25.15
WooCommerce: by Automattic – 5.4.1
WP Last Modified Info: by Sayan Datta – 1.7.7
WP Migrate DB: by Delicious Brains – 2.0.2

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
install.php: install.php

### Must Use Plugins (2) ###

SSO: by Garth Mortensen
Mike Hansen – 0.3

WP Migrate DB Compatibility: by Delicious Brains – 1.2

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: ❌ Page visibility should be public
Cart: ❌ Page visibility should be public
Checkout: ❌ Page visibility should be public
My account: ❌ Page visibility should be public
Terms and conditions: ❌ Page not set

### Theme ###

Name: Executive Pro
Version: 3.2.3
Author URL: http://www.studiopress.com/
Child Theme: ✔
Parent Theme Name: Genesis
Parent Theme Version: 3.3.3
Parent Theme Author URL: https://www.studiopress.com/
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 247
Oldest: 2021-06-21 19:51:33 -0600
Newest: 2021-07-01 22:57:02 -0600

Pending: 1
Oldest: 2021-07-01 23:57:02 -0600
Newest: 2021-07-01 23:57:02 -0600

### Status report information ###

Generated at: 2021-07-01 22:59:37 -06:00
</details>

**Comment by tammullen** [comment]
Thanks @getsnoopy for raising this issue and PR.

> For the US, it reads as "ZIP"
> For the US, it should read as "ZIP Code"

Looking at United States Postal Service site https://tools.usps.com/go/ZipLookupAction_input it looks like you are correct, they use `ZIP Code`


> For India, it reads as "Pin code".
> For India, it should read as "PIN".

Looking at the India Post site https://www.indiapost.gov.in/VAS/Pages/findpincode.aspx it looks like they use `Pincode` do you have any other sources to support using a label of `PIN`?

Marking as a Bug as it looks like we should use `ZIP Code` instead of `ZIP` for `US`, and `Pincode` instead of `Pin code` for  `IN`.

**Comment by getsnoopy** [comment]
@tammullen Yeah, the India Post website is not well maintained. You can see that it's inconsistent even within the same website, where it reads as "Pin code" in some places, "PIN code" in other places, and just "PIN" in others. [The proper term is simply *PIN*](https://en.wikipedia.org/wiki/Postal_Index_Number), as it's an acronym for *Postal Index Number*. The term "PIN code" is redundant, just like how "ATM machine" or "LCD display" is redundant.
