### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ajonlineshopetp** [woocommerce/woocommerce#30213]
**Prerequisites (mark completed items with an [x]):**
- [ ] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [ ] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

**Comment by juliaamosova** [comment]
Hi @ajonlineshopetp,

I am closing this issue as there are no bug details provided. If you'd like to report an issue, please open a new one and fill out the bug report template that we provide.
