### ISSUE TITLE
4 Clicks to Delete 1 Variation, how painful

### ISSUE THREAD

**Issue by mitchellkrogza** [woocommerce/woocommerce#30214]
This was never like this before, recent versions have now made deleting 1 variation require 4 clicks.
This is absolutely painful to say the least. 

Please introduce a better way to deal with variations.

https://user-images.githubusercontent.com/9961541/124380397-b5621b00-dcbc-11eb-8bf0-7dcdc98da17a.mp4

**Comment by lkraav** [comment]
> This was never like this before, recent versions have now made deleting 1 variation require 4 clicks.

This is not how core WooCommerce behaves. It must be something to do with another plugin or your theme.

**Comment by mitchellkrogza** [comment]
> > This was never like this before, recent versions have now made deleting 1 variation require 4 clicks.
> 
> This is not how core WooCommerce behaves. Everything works fine with a single click here. It must be something to do with another plugin or your theme.

Thanks @lkraav I will have to check on my staging site what is causing this.
