### ISSUE TITLE
Tax not adding correctly 

### ISSUE THREAD

**Issue by NoahPerez** [woocommerce/woocommerce#30210]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**
woocommerce is not adding  correctly the 21% it is adding approximately a 17% 

The price of the product with taxes is 29.95€ 

29.95% - 21% = 6.2895 iva 

23.6605 + 6.2895 = 29.95€

Woocommerce is giving me 

28,63€ (IVA incl.)

Here are some screenshot 

https://ibb.co/f1sVKbJ
https://ibb.co/9pPz9mV
https://ibb.co/jHg4XFC
https://ibb.co/WFb4Tpk

**Comment by juliaamosova** [comment]
Hi @NoahPerez,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. I tested using WooCommerce 5.5 RC2. 

**My product:**

![Screen Shot 2021-07-09 at 4 19 59 PM](https://user-images.githubusercontent.com/19143190/125132145-e930ac80-e0d1-11eb-93b1-8d1edd2b8841.png)

**My tax settings:**

![Screen Shot 2021-07-09 at 4 20 21 PM](https://user-images.githubusercontent.com/19143190/125132153-ed5cca00-e0d1-11eb-98a9-f9b21f0539ad.png)

![Screen Shot 2021-07-09 at 4 23 11 PM](https://user-images.githubusercontent.com/19143190/125132179-f64d9b80-e0d1-11eb-91d9-3855ec59afb7.png)

**Cart page where I am getting a product price of $28.6292 (tax included):**

![Screen Shot 2021-07-09 at 4 23 50 PM](https://user-images.githubusercontent.com/19143190/125132384-3f055480-e0d2-11eb-9926-531a91a51abf.png)

**Google calculations:**

![Screen Shot 2021-07-09 at 4 25 45 PM](https://user-images.githubusercontent.com/19143190/125132444-53495180-e0d2-11eb-82ec-d2ef45663d27.png)

I believe everything is working as expected. Can you please check if I am missing anything to reproduce your case?

**Comment by NoahPerez** [comment]
Thank you for your response but was my miss calculation.

I do have another quesition

where i uploading a product, can insert expiration date but without the
customer seeing it? ( Is there an  internal use? ).

**Comment by AashikP** [comment]
Hello @NoahPerez 

> where i uploading a product, can insert expiration date but without the customer seeing it? ( Is there an  internal use? ).

While our goal is to address all the issues reported in this repository, GitHub should be treated as a place to report confirmed bugs only.

The most recent comment you submitted looks like a support request. For further assistance, please follow the steps below:

- Review [WooCommerce Self-Service Guide](https://docs.woocommerce.com/document/woocommerce-self-service-guide/) to see if the solutions listed there apply to your case;
- If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/);
- Make a post on [WooCommerce community forum](https://wordpress.org/support/plugin/woocommerce/)

If you confirm the originally reported bug, please provide us with clear steps to reproduce it.

I am closing this issue for now as it seems to be a support request and not a bug. If I missed something, please leave a comment and we will take a second look.
