### ISSUE TITLE
WooCommerce.Products.index - multiEdit save not working

### ISSUE THREAD

**Issue by brniwllnr** [woocommerce/woocommerce#30220]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When multi-editing some products and for example the price is wanted to get higher by 1 €, after pressing "Update", nothing happens.

**Expected behavior**
When multi-editing some products and setting the price from 290€ to 292€, after pressing "Update", every selected product should be updated with the new value.
**Actual behavior**
When multi-editing some products and setting the price from 290€ to 292€, after pressing "Update", nothing happens.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to 'Products'
2. Select at least one product, select in the actions-dropdown "edit" and execute that
3. Scroll down to the expanded "Multi-Edit-View"
4. See

**Screenshots**
Select Product(s)
![WooCommerce_Products_index_selected](https://user-images.githubusercontent.com/86970204/124544572-9df37100-de27-11eb-8ad1-981edbe8578a.png)

Force "Edit"-action on all selected products
![WooCommerce_Products_multiEdit_nothingselected](https://user-images.githubusercontent.com/86970204/124544577-9f249e00-de27-11eb-9eb6-ac3f634b2035.png)

In this View the bug happens, i think. (THIS HAPPENS FOR EVERY FIELD I TRY TO CHANGE THE VALUE)
In this case I just wanted to do $ACTUAL_PRICE + 10 EUR 
![WooCommerce_Products_multiEdit_plus_ten](https://user-images.githubusercontent.com/86970204/124544579-9fbd3480-de27-11eb-914a-a68878f6088b.png)

after pressing the Save button below, and after the "Save-Redirect", there are flash-messages which tells me that the save was successful. But the values do not even change. I tried everthing. 
![WooCommerce_Products_multiEdit_afterSave_no_change](https://user-images.githubusercontent.com/86970204/124544575-9e8c0780-de27-11eb-8bd1-2b7d4d52b375.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
`
### WordPress Environment ###

WordPress address (URL): https://training.wolfgangmoetz.at
Site address (URL): https://training.wolfgangmoetz.at
WC Version: 4.9.0
REST API Version: ✔ 4.9.0
WC Blocks Version: ✔ 4.0.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 1.8.3
Log Directory Writable: ✔
WP Version: ❌ 5.6.4 - Es ist eine neuere Version von WordPress verfügbar (5.7.2)
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: de_DE
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.18
PHP Post Max Size: 128 MB
PHP Time Limit: 180
PHP Max Input Vars: 4000
cURL Version: 7.64.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.7.33
Max Upload Size: 128 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 4.9.0
WC Database Prefix: U4ZR4o_
Datenbank-Gesamtgröße: 11.82MB
Datenbank-Datengröße: 8.73MB
Datenbank-Indexgröße: 3.09MB
U4ZR4o_woocommerce_sessions: Daten: 0.05MB + Index: 0.02MB + Engine InnoDB
U4ZR4o_woocommerce_api_keys: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_woocommerce_attribute_taxonomies: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
U4ZR4o_woocommerce_downloadable_product_permissions: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
U4ZR4o_woocommerce_order_items: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
U4ZR4o_woocommerce_order_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_woocommerce_tax_rates: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
U4ZR4o_woocommerce_tax_rate_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_woocommerce_shipping_zones: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
U4ZR4o_woocommerce_shipping_zone_locations: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_woocommerce_shipping_zone_methods: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
U4ZR4o_woocommerce_payment_tokens: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
U4ZR4o_woocommerce_payment_tokenmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_woocommerce_log: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
U4ZR4o_actionscheduler_actions: Daten: 0.02MB + Index: 0.11MB + Engine InnoDB
U4ZR4o_actionscheduler_claims: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
U4ZR4o_actionscheduler_groups: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
U4ZR4o_actionscheduler_logs: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_commentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_comments: Daten: 0.05MB + Index: 0.09MB + Engine InnoDB
U4ZR4o_frm_fields: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_frm_forms: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
U4ZR4o_frm_items: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
U4ZR4o_frm_item_metas: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_groups_capability: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_groups_group: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
U4ZR4o_groups_group_capability: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
U4ZR4o_groups_user_capability: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
U4ZR4o_groups_user_group: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
U4ZR4o_ld_notifications_delayed_emails: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
U4ZR4o_learndash_pro_quiz_category: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
U4ZR4o_learndash_pro_quiz_form: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
U4ZR4o_learndash_pro_quiz_lock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
U4ZR4o_learndash_pro_quiz_master: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
U4ZR4o_learndash_pro_quiz_prerequisite: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
U4ZR4o_learndash_pro_quiz_question: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_learndash_pro_quiz_statistic: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
U4ZR4o_learndash_pro_quiz_statistic_ref: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_learndash_pro_quiz_template: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
U4ZR4o_learndash_pro_quiz_toplist: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
U4ZR4o_learndash_user_activity: Daten: 0.02MB + Index: 0.13MB + Engine InnoDB
U4ZR4o_learndash_user_activity_meta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_links: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
U4ZR4o_options: Daten: 4.08MB + Index: 0.16MB + Engine InnoDB
U4ZR4o_postmeta: Daten: 0.39MB + Index: 0.20MB + Engine InnoDB
U4ZR4o_posts: Daten: 2.52MB + Index: 0.20MB + Engine InnoDB
U4ZR4o_rmp_analytics: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
U4ZR4o_termmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_terms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_term_relationships: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
U4ZR4o_term_taxonomy: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_usermeta: Daten: 0.06MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_users: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
U4ZR4o_wc_admin_notes: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
U4ZR4o_wc_admin_note_actions: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
U4ZR4o_wc_avatars_cache: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
U4ZR4o_wc_category_lookup: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
U4ZR4o_wc_comments_subscription: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
U4ZR4o_wc_customer_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_wc_download_log: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_wc_feedback_forms: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_wc_follow_users: Daten: 0.02MB + Index: 0.13MB + Engine InnoDB
U4ZR4o_wc_order_coupon_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_wc_order_product_lookup: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
U4ZR4o_wc_order_stats: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
U4ZR4o_wc_order_tax_lookup: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_wc_phrases: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
U4ZR4o_wc_product_meta_lookup: Daten: 0.02MB + Index: 0.09MB + Engine InnoDB
U4ZR4o_wc_reserved_stock: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
U4ZR4o_wc_tax_rate_classes: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
U4ZR4o_wc_users_rated: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_wc_users_voted: Daten: 0.02MB + Index: 0.08MB + Engine InnoDB
U4ZR4o_wc_webhooks: Daten: 0.02MB + Index: 0.02MB + Engine InnoDB
U4ZR4o_woocommerce_gzd_dhl_im_products: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_woocommerce_gzd_dhl_im_product_services: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_woocommerce_gzd_packaging: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
U4ZR4o_woocommerce_gzd_packagingmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_woocommerce_gzd_shipmentmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_woocommerce_gzd_shipments: Daten: 0.02MB + Index: 0.05MB + Engine InnoDB
U4ZR4o_woocommerce_gzd_shipment_itemmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_woocommerce_gzd_shipment_items: Daten: 0.02MB + Index: 0.06MB + Engine InnoDB
U4ZR4o_woocommerce_gzd_shipment_labelmeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_woocommerce_gzd_shipment_labels: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB
U4ZR4o_woocommerce_gzd_shipping_provider: Daten: 0.02MB + Index: 0.00MB + Engine InnoDB
U4ZR4o_woocommerce_gzd_shipping_providermeta: Daten: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

acf-field: 3
acf-field-group: 2
advgb_profiles: 1
attachment: 23
custom_css: 2
customize_changeset: 90
frm_form_actions: 3
frm_styles: 1
groups: 11
nav_menu_item: 17
page: 30
post: 6
product: 2
revision: 505
sfwd-courses: 15
sfwd-lessons: 38
sfwd-question: 1
sfwd-quiz: 1
sfwd-topic: 46
shop_coupon: 1
shop_order: 9
ufaq: 4
wp_block: 7
wpdiscuz_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

WordPress Persistent Login: von Luke Seager – 1.3.23
Accordion Blocks: von Phil Buchanan – 1.3.4
Direct checkout, WooCommerce Single page checkout , WooCommerce One page checkout: von PI Websolution – 2.1.2
Advanced Custom Fields: von Elliot Condon – 5.9.5
PublishPress Blocks: von PublishPress – 2.6.2
BackWPup: von Inpsyde GmbH – 3.8.0
Better Search Replace: von Delicious Brains – 1.3.4
Colorlib Login Customizer: von Colorlib – 1.2.99
Comments Like Dislike: von WP Happy Coders – 1.1.4
Folders: von Premio – 2.6.9
Formidable Forms: von Strategy11 – 4.11.02
Groups: von itthinx – 2.13.0
LearnDash LMS - Course Grid: von LearnDash – 1.7.0
LearnDash LMS - Notifications: von LearnDash – 1.5.2
LearnDash ProPanel: von LearnDash – 2.1.4
LearnDash LMS - Stripe Integration: von LearnDash – 1.8.0
LearnDash LMS - WooCommerce Integration: von LearnDash – 1.9.1
Loco Translate: von Tim Whitlock – 2.5.2
Post Duplicator: von Metaphor Creations – 2.22
Reveal IDs: von Oliver Schlöbe – 1.5.4
LearnDash LMS: von LearnDash – 3.3.0.3
WooCommerce Stripe-Gateway: von WooCommerce – 5.2.3
Germanized für WooCommerce: von vendidero – 3.4.8
WooCommerce: von Automattic – 4.9.0 (Update auf Version 5.4.1 ist verfügbar)
Nested Pages: von Kyle Phillips – 3.1.13

### Inactive Plugins (4) ###

Deeper Comments: von Webnus – 2.0.2
Force Login: von Kevin Vess – 5.5
Loggedin - Limit Active Logins: von Joel James – 1.3.1
Rate my Post - WP Rating System: von Blaz K. – 3.3.2

### Dropin Plugins (1) ###

maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: course (course)
external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop-Basis: #262 - /shop/
Warenkorb: #263 - /warenkorb/
Kasse: #264 - /kasse/
Mein Konto: #265 - /benutzerprofil/
Allgemeine Geschäftsbedingungen: ❌ Seite nicht festgelegt

### Theme ###

Name: Training Wolfgang Moetz
Version: 1.0
Author URL: https://www.linert.at
Child Theme: ✔
Parent Theme Name: Chaplin
Parent Theme Version: 2.6.1 – 2.6.7 ist verfügbar
Parent Theme Author URL: https://www.andersnoren.se
WooCommerce Support: ❌ Nicht deklariert

### Templates ###

Overrides: training/woocommerce/myaccount/form-edit-account.php
training/woocommerce/myaccount/navigation.php

### Action Scheduler ###

Abgeschlossen: 14
Oldest: 2021-01-15 22:11:24 +0100
Newest: 2021-01-15 22:20:36 +0100

Ausstehend: 14
Oldest: 2021-03-16 09:06:30 +0100
Newest: 2021-06-29 12:14:08 +0200

`
</details>

**Comment by juliaamosova** [comment]
Hi @brniwllnr,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. I tested using WooCommerce 5.4.1 (the latest version). 

Please see the screencast below showing that bulk-editing works as expected (increasing the price by $10):

https://user-images.githubusercontent.com/19143190/125127236-390b7580-e0ca-11eb-9135-121fcff53554.mov

I see in your System Status Report that you are using an older version of WooCommerce. You are using 4.9.0 which is about 6 months old (it was released on January 11, 2021). The current version is 5.4.1. I recommend you updating WooCommerce as we have introduced many improvements in the last 6 months including bug fixes. 

Please let us know how it goes after an update.
