### ISSUE TITLE
`applied_coupon_in_checkout` JavaScript event triggered regardless of status when applying coupons

### ISSUE THREAD

**Issue by mbabker** [woocommerce/woocommerce#30225]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When applying coupons to the cart during checkout, the success handler for the JavaScript `wc_checkout_coupons.submit` function's AJAX call will always be triggered because the PHP `WC_AJAX::apply_coupon()` method will always trigger a 200 response with a rendered notice element.  This makes it impossible for sites to listen for the `applied_coupon_in_checkout` event in JavaScript and conditionally do something based on whether a coupon was successfully applied as the event is triggered so long as there is a notice in the response and the event data only contains the user-supplied coupon code.

**Expected behavior**
One of:

- The `applied_coupon_in_checkout` JavaScript event (and probably other JavaScript events) include enough context for developers to work out whether an action succeeded or failed, or the event to only be triggered contextually based on success or fail state
- The `WC_AJAX::apply_coupon()` PHP method configure the HTTP response in a way to indicate whether coupons were successfully applied to the cart (whether it be by including additional data beyond a HTML snippet or changing the status code, doesn't necessarily matter here)

**Actual behavior**
The `applied_coupon_in_checkout` JavaScript event is always triggered as long as the server emits a 200 response (which, it should short of a fatal error it appears) and the server response and JavaScript event lack context to decide whether a coupon was actually applied.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Create a coupon in the WooCommerce plugin admin
2. From the WordPress frontend, add any product to your cart and go to the checkout screen
3. Open your browser's developer console to be able to inspect the responses from the upcoming AJAX calls
4. Click the "Have a coupon? Click here to enter your code" message to show the coupon code form
5. Enter in your coupon and apply it, note that the AJAX call to the `?wc-ajax=apply_coupon` endpoint returns a 200 response with the HTML for the notice shown on the screen
6. Try to apply the same coupon again, note that the AJAX call to the `?wc-ajax=apply_coupon` endpoint returns a 200 response with the HTML for the notice shown on the screen
7. Now enter a non-existing coupon code and try to apply it, note that the AJAX call to the `?wc-ajax=apply_coupon` endpoint returns a 200 response with the HTML for the notice shown on the screen

**Screenshots**
N/A

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
WP Version: 5.7.2
WC Version: 5.4.1
PHP Version: 7.4.16

**Comment by juliaamosova** [comment]
Hi @mbabker,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by vedanshujain** [comment]
Hi @mbabker, we discussed this internally, and along with adding more context to `applied_coupon_in_checkout` I think we should add another event that can be fired when coupon apply request failed.

I am marking this as a low priority for now in the context of all the high-priority issues we have already open. Given the time investment you have already made here, I'd also encourage you to send in a PR fixing this issue.

**Comment by mbabker** [comment]
I'm going to close this out as a won't fix.  I doubt bigger changes to the legacy JavaScript frontend are going to be accepted at this point, and given the current behaviors of the legacy frontend and related backend handler, the scope for unexpected B/C breaks is too wide to account for.

This does appear to work as expected when using the store API at a minimum, and the `woocommerce-blocks` package does make use of it, so it behaves correctly in the scope of "modern" development.
