### ISSUE TITLE
Issue with block-based Widget.

### ISSUE THREAD

**Issue by bhrugesh-linksture** [woocommerce/woocommerce#30236]
In my theme addon plugin i extended Woocommerce mini cart Widget.
-> I tested with WP version 5.8 CR2.
-> When i go to Appereance -> Widget then i can see error like you can see in below link:
Error:
1) **The "text" block was affected by errors and may not function properly. Check the developer tools for more details.**
2) **The "woocommerce_widget_cart" block was affected by errors and may not function properly. Check the developer tools for more details.**
![download](https://user-images.githubusercontent.com/82364940/125023195-f763d600-e09b-11eb-9dac-6da2716b260a.png)

--> Here is my code file which i extended in my plugin:
`<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Shopping Cart Widget
 *
 * Displays shopping cart widget
 *
 * @author   WooThemes
 * @category Widgets
 * @package  WooCommerce/Widgets
 * @version  2.3.0
 * @extends  WC_Widget
 */
if ( !class_exists('Hcode_Widget_Cart') ) {
	class Hcode_Widget_Cart extends WC_Widget {

		/**
		 * Constructor
		 */
		public function __construct() {

			$this->widget_cssclass    = 'woocommerce widget_shopping_cart';
			$this->widget_description = esc_html__( "Display the user's Cart in the sidebar.", 'hcode-addons' );
			$this->widget_id          = 'woocommerce_widget_cart';
			$this->widget_name        = esc_html__( 'WooCommerce Cart', 'hcode-addons' );
			$this->settings           = array(
				'title'  => array(
					'type'  => 'text',
					'std'   => esc_html__( 'Cart', 'hcode-addons' ),
					'label' => esc_html__( 'Title', 'hcode-addons' )
				),
				'hide_if_empty' => array(
					'type'  => 'checkbox',
					'std'   => 0,
					'label' => esc_html__( 'Hide if cart is empty', 'hcode-addons' )
				)
			);

			parent::__construct();
		}

		//public $show_instance_in_rest = true;

		/**
		 * widget function.
		 *
		 * @see WP_Widget
		 *
		 * @param array $args
		 * @param array $instance
		 *
		 * @return void
		 */
		public function widget( $args, $instance ) {

			$hide_if_empty = empty( $instance['hide_if_empty'] ) ? 0 : 1;

			$this->widget_start( $args, $instance );

			if ( $hide_if_empty ) {
				echo '<div class="hide_cart_widget_if_empty">';
			}
			// Insert cart widget placeholder - code in woocommerce.js will update this on page load
			echo '<div class="hcode_shopping_cart_content">';
				wc_get_template( 'cart/mini-cart.php');
			echo '</div>';

			if ( $hide_if_empty ) {
				echo '</div>';
			}

			$this->widget_end( $args );
		}
	}
}`

**Comment by vedanshujain** [comment]
Hi @bhrugesh-linksture , you are seeing this error because in template `wc_get_template( 'cart/mini-cart.php');` we call the function `WC()->cart->is_empty`. To fix, you may add a check before `WC()->cart` to make sure its set.

Note that there are few more issues with the code, like conflicting widget_id and title that you may want to fix.

I am closing this issue as GitHub is only for reporting bugs, and we won't be able to provide custom code support here.
