### ISSUE TITLE
Stránka neobsahuje [woocommerce_checkout] zkrácený kód nebo blok woocommerce/checkout.

### ISSUE THREAD

**Issue by Cocakoala12** [woocommerce/woocommerce#30242]
`
### WordPress Environment ###

WordPress address (URL): https://phenomenal.cz
Site address (URL): https://phenomenal.cz
WC Version: 5.4.1
REST API Version: ✔ 5.4.1
WC Blocks Version: ✔ 5.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.3.1
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: cs_CZ
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.8
PHP Post Max Size: 256 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.21 Basic ECC

SUHOSIN Installed: –
MySQL Version: 5.6.45-86.1
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.4.1
WC Database Prefix: wp_
Celková velikost databáze: 97.55MB
Velikost dat databáze: 91.40MB
Velikost indexu databáze: 6.15MB
wp_woocommerce_sessions: Data: 0.16MB + Index: 0.01MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.10MB + Index: 0.05MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 1.43MB + Index: 0.82MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.13MB + Index: 0.06MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.09MB + Index: 0.07MB + Engine MyISAM
wp_aioseo_notifications: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_aioseo_posts: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_bulkgate_module: Data: 0.03MB + Index: 0.00MB + Engine MyISAM
wp_cmplz_cookiebanners: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_cmplz_cookies: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_cmplz_services: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.26MB + Index: 0.12MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 1.87MB + Index: 0.08MB + Engine MyISAM
wp_pantheon_sessions: Data: 0.02MB + Index: 0.02MB + Engine MyISAM
wp_postmeta: Data: 62.00MB + Index: 3.12MB + Engine MyISAM
wp_posts: Data: 20.16MB + Index: 0.48MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.02MB + Index: 0.04MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Data: 0.04MB + Index: 0.02MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.11MB + Index: 0.04MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.17MB + Index: 0.13MB + Engine MyISAM
wp_wc_order_stats: Data: 0.11MB + Index: 0.08MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfblockediplog: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfblocks7: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfconfig: Data: 0.40MB + Index: 0.01MB + Engine MyISAM
wp_wfcrawlers: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wffilechanges: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wffilemods: Data: 1.97MB + Index: 0.29MB + Engine MyISAM
wp_wfhits: Data: 0.04MB + Index: 0.01MB + Engine MyISAM
wp_wfhoover: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfissues: Data: 0.01MB + Index: 0.01MB + Engine MyISAM
wp_wfknownfilelist: Data: 1.04MB + Index: 0.12MB + Engine MyISAM
wp_wflivetraffichuman: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wflocs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wflogins: Data: 0.14MB + Index: 0.03MB + Engine MyISAM
wp_wfls_2fa_secrets: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfls_settings: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wfnotifications: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wfpendingissues: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfreversecache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfsnipcache: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wfstatus: Data: 0.08MB + Index: 0.03MB + Engine MyISAM
wp_wftrafficrates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wpify_woo_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_indexable: Data: 0.73MB + Index: 0.26MB + Engine MyISAM
wp_yoast_indexable_hierarchy: Data: 0.04MB + Index: 0.09MB + Engine MyISAM
wp_yoast_migrations: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_yoast_primary_term: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_yoast_seo_links: Data: 0.18MB + Index: 0.07MB + Engine MyISAM

### Post Type Counts ###

attachment: 78
booked_appointments: 2172
elementor_font: 1
elementor_library: 7
nav_menu_item: 44
o-discount: 1
o-list: 1
oembed_cache: 2
page: 25
post: 1
product: 18
product_variation: 26
revision: 1519
shop_order: 2205
sl-insta-account: 3
sl-insta-feed: 3
sl-insta-media: 43

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Actignite: o Actignite – 0.0.1
Akismet Anti-Spam: o Automattic – 4.1.9
Booked: o Boxy Studio – 2.3.5
Complianz | GDPR/CCPA Cookie Souhlas: o Really Simple Plugins – 5.2.2
Duplikovat stránku: o mndpsingh287 – 4.4
Elementor Pro: o Elementor.com – 3.1.0
Elementor: o Elementor.com – 3.2.5
Google Analytics for WordPress by MonsterInsights: o MonsterInsights – 7.17.0
Site Kit by Google: o Google – 1.35.0
Nginx Cache: o Till Krüss – 1.0.5
Really Simple SSL: o Really Simple Plugins – 4.0.15
Spotlight - Social Media Feeds: o RebelCode – 0.8.2
UpdraftPlus - Backup/Restore: o UpdraftPlus.Com
DavidAnderson – 1.16.56

WooCommerce Stripe Gateway: o WooCommerce – 5.2.3
WooCommerce: o Automattic – 5.4.1
Yoast SEO: o Tým Yoast – 16.6.1
WPify Woo: o WPify s.r.o. – 3.3.7

### Inactive Plugins (1) ###

All in One SEO: o All in One SEO Team – 4.1.2.1

### Must Use Plugins (1) ###

Elementor Safe Mode: o Elementor.com – 1.0.0

### Settings ###

API Enabled: –
Force SSL: –
Currency: CZK (Kč)
Currency Position: right
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Obchod: ❌ Stránka není zvolena
Košík: #2297 - /kosik/
Pokladna: ❌ Stránka neobsahuje [woocommerce_checkout] zkrácený kód nebo blok woocommerce/checkout.
Můj účet: #4923 - /muj-ucet/
Obchodní podmínky: #193 - /obchodni-podminky/

### Theme ###

Name: Hello Elementor
Version: 2.3.1 (aktualizace na verzi 2.4.1 je dostupná)
Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
Child Theme: ❌ – Pokud upravujete WooCommerce šablonu
kterou jste nevytvořili
doporučujeme použít odvozenou šablonu. Viz Jak vytvořit odvozenou šablonu (anglicky)

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Dokončeno: 521
Oldest: 2021-06-08 04:17:42 +0200
Newest: 2021-07-08 20:35:23 +0200

Čekající: 2
Oldest: 2021-07-08 22:10:20 +0200
Newest: 2021-07-09 00:29:51 +0200

### Status report information ###

Generated at: 2021-07-08 21:18:11 +02:00
`

**Comment by juliaamosova** [comment]
Hi @Cocakoala12,

Please note that we reply to bug reports in the English language only. I used [Google Translate](https://translate.google.com/) to translate your message. You can use the same to translate my reply back. 

Issue title translation:

> The page does not contain a [woocommerce_checkout] abbreviated code or woocommerce / checkout block.

Thank you for submitting the issue. However, you didn’t fill out the details of the bug report template that we ask for. Without these details, we can’t fully evaluate this issue. Please provide us with the information requested so we could take a look further.

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Isolating the problem (mark completed items with an [x]):**
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [ ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Copy and paste the system status report from **WooCommerce > System Status** in WordPress admin.
```
</details>
