### ISSUE TITLE
The modification times displayed in log files dropdown provide incorrect time

### ISSUE THREAD

**Issue by kravco** [woocommerce/woocommerce#30251]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Context: WooCommerce status page > section logs (using log handler file)
The modification times displayed in log files dropdown provide incorrect time in relation to timezone specified in WordPress settings.

**Expected behavior**
The modification times would be displayed in configured timezone and include timezone abbreviation for clarity.

**Actual behavior**
The modification times in dropdown lack timezone information and are in UTC time

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Configure WordPress installation to use timezone that has different time than UTC (e.g. UK timezones might not show defect when their time matches UTC)
2. Configure WooCommerce to log into files (this is the default)
2. Do some action to trigger writing a message into log file (e.g. fatal error)
3. Open WooCommerce > Status > Logs page
4. Look into dropdown, compare displayed modification time of file that you triggered write into and current time in configured timezone.

**Comment by rodelgc** [comment]
Hi @kravco,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.
