### ISSUE TITLE
Payment method "Other" stores its raw value as `_payment_method_title` instead of its localized name

### ISSUE THREAD

**Issue by YordanSoares** [woocommerce/woocommerce#30255]
**Prerequisites (mark completed items with an [x]):**
- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When you choose **Other** as payment method option, under the order editing view, the `_payment_method_title` meta store the raw value (`other`) instead of the localized string **Other**. E.g. **Otro** in Spanish, **Autre** in French, etc.

**Steps to reproduce the bug**

1. Go to WooCommerce > Orders > Edit an existent order > Edit the billing address and change the payment method to **Other**.

![image](https://user-images.githubusercontent.com/38109855/125225203-e209ca00-e29c-11eb-979c-c42e027ac8c7.png)
2. Query the `_payment_method_title` of the order and you'll see that the payment method title is the raw value:

![image](https://user-images.githubusercontent.com/38109855/125225678-ae7b6f80-e29d-11eb-9296-b82fdba51d07.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by rodelgc** [comment]
Hi @YordanSoares,

Thank you for opening the issue, as well as submitting a PR! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
Hi @YordanSoares,

I don't believe there is a problem here (and will also close the PR you submitted).

The value you see in `_payment_method_title` is not intended to be translatable—it's used internally, and needs to be consistent regardless of the current user language. On the other hand, the label itself (ie, what you or other users see in the _Payment Method_ dropdown itself) is already translatable—so this doesn't impact the user experience.

If I'm mistaken, please do let me know and provide a set of steps to replicate the problem you are experiencing with this but, again, I believe everything here is functioning as expected.

**Comment by barryhughes** [comment]
Apologies, I was somewhat mistaken in my last reply. However, with a translation in place the 'Other' label in the dropdown is indeed translated as expected, so it doesn't seem that further action is needed.

**Comment by YordanSoares** [comment]
@barryhughes the label in the single order editing view is indeed translated, but the issue here is that the value stored in `_payment_method_title` isn't. 

When you said _"The value you see in `_payment_method_title` is not intended to be translatable"_, I think you're referring to `_payment_method`, instead `_payment_method_title`, that it's indeed intended to be localized. You can try selecting any other default payment method to see that the value stored in`_payment_method_title` is indeed translated.

**Here is an actual case of use:**
One of our French customer print the payment method in their PDF invoices (generated with our [WooCommerce PDF Invoices & Packing Slips](https://wordpress.org/plugins/woocommerce-pdf-invoices-packing-slips/)), but when they choose "Other", the title remains in English (since it takes the raw value, as explained above):

![image](https://user-images.githubusercontent.com/38109855/127244964-d4f531cb-d39b-44b9-a457-31b5bf2ecf07.png)

**Comment by barryhughes** [comment]
That use case is helpful: re-opening, and will take another look—thank you.
