### ISSUE TITLE
products on sale display bug on shop page.

### ISSUE THREAD

**Issue by TBAIKamine** [woocommerce/woocommerce#30261]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
products on sale are not displayed correctly in shop page

**Expected behavior**
to have the "add to basket" aligned with the others in the same row in shop page

**Actual behavior**
the "add to basket" is not aligned with the others

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. create 16 test products
2. give them regular price only
3. give one of them a sale price
4. goto shop page and look at the peoduct on sale. see if "add to basket" is aligned with the others.

**Screenshots**
n/a.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://localhost/wordpress
Site address (URL): http://localhost/wordpress
WC Version: 5.4.1
REST API Version: ✔ 5.4.1
WC Blocks Version: ✔ 5.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.3.1
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Win64) PHP/7.4.0
PHP Version: 7.4.0
PHP Post Max Size: 98 GB
PHP Time Limit: 3600
PHP Max Input Vars: 2500
cURL Version: 7.67.0
OpenSSL/1.1.1c

SUHOSIN Installed: –
MySQL Version: 5.7.28
Max Upload Size: 98 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.4.1
WC Database Prefix: wp_
Total Database Size: 1.20MB
Database Data Size: 1.03MB
Database Index Size: 0.17MB
wp_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 0.91MB + Index: 0.03MB + Engine MyISAM
wp_postmeta: Data: 0.08MB + Index: 0.03MB + Engine MyISAM
wp_posts: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 30
customize_changeset: 6
page: 7
post: 1
product: 29
revision: 8

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 5.4.1

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #11 - /shop/
Basket: #12 - /basket/
Checkout: #13 - /checkout/
My account: #14 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.7.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 3
Oldest: 2021-07-11 16:40:55 +0100
Newest: 2021-07-12 12:21:46 +0100


### Status report information ###

Generated at: 2021-07-12 12:54:14 +01:00
````
</details>

**Comment by rodelgc** [comment]
Hi @TBAIKamine,

Thank you for submitting the issue. I believe that you're referring to the 'Add to cart' button of an on-sale item (marked with an orange arrow) being at a lower position compared to the other 'Add to cart' buttons of other products that are not on-sale (marked with the purple arrows)?

<img width="872" alt="Screen Shot 2021-07-14 at 4 50 01 PM" src="https://user-images.githubusercontent.com/4509348/125593844-01b0f3a1-7b17-4432-ae95-188b70689250.png">

If so, that is the expected design for Storefront. 

If not, please provide screenshots and a more detailed explanation of the problem you saw. Screenshots would be very helpful especially in visual issues like this. Thanks!

**Comment by TBAIKamine** [comment]
that's exactly what I mean. you understood me perfectly
however you're saying it's "expected" from storefron to show a clumpsy grid and to have that behavior ?
am shocked.
if the developped "expected" that product to behave that way. the developper needs to see it more from the user's eye

**Comment by rodelgc** [comment]
Hi @TBAIKamine,

Thank you for confirming. I believe this is more of a user preference rather than a bug. 

In web design, it's not always possible to have all similar items aligned. Especially in this case where there is an extra "Sale" badge that the design needs to accommodate. 

But even though the "Add to cart" button of an item on sale is not in line with the other "Add to cart" buttons, it is still aligned with everything else. For example, it is still perfectly center-aligned with the rest of the elements within its group:
<img width="245" alt="Screen Shot 2021-07-28 at 6 13 54 PM" src="https://user-images.githubusercontent.com/4509348/127314115-7cfa4698-b2de-484a-8136-bac11603d553.png">

And that it did not cause its surrounding products to go out of alignment. As you can see from below, the alignment of each "cell" in the grid is still even. No cell got misaligned.
<img width="438" alt="Screen Shot 2021-07-28 at 5 44 41 PM" src="https://user-images.githubusercontent.com/4509348/127314318-e4fc726b-442e-45d2-9003-297fc978fa2c.png">

Sometimes it's fine to have an element with a different alignment as long as it's aligned with everything else, and the spacing around it is reasonable, and as long as it doesn't push its neighboring elements off of their own alignment.

Since this is a very subjective topic, and that it does not fit in with our current priorities, I will close this issue for the meantime with the `type: enhancement` label and evaluate over time if this issue collects more feedback.
