### ISSUE TITLE
image crop in shop page bug

### ISSUE THREAD

**Issue by TBAIKamine** [woocommerce/woocommerce#30260]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this **Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
considering woocommerce is the only plugin installed with the official storefront theme active.
in shop page, images are cropped (if customizer settings are default) to have a neat grid.
images with one dimension only (width OR height) that is below the target are skipped.
leaving the other dimension exceeding the target
resulting in a clumsy grid.
thanks

**Expected behavior**
to have a neat grid in shop page (meaning all product images have same height and width)

**Actual behavior**
clumsy displayed grid in shop page.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. add 16 products for the test
2. give 15 of the products test images above 500x500 px
while one image with 50x500 px.
3. leave customizer settings on default, or make sure: appearance->customise->woocommerce->product catalogue, has 4 columns/products per row and 4 rows per page.
4. goto shop page on the website on a large none touche screen (a computer, not handheld device like a cellphone/tablet)
5. look at the offset product with different dimensions, and see if "add to basket" looks aligned with the others

**Screenshots**
n/a

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
`
### WordPress Environment ###

WordPress address (URL): http://localhost/wordpress
Site address (URL): http://localhost/wordpress
WC Version: 5.4.1
REST API Version: ✔ 5.4.1
WC Blocks Version: ✔ 5.1.0
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.3.1
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.41 (Win64) PHP/7.4.0
PHP Version: 7.4.0
PHP Post Max Size: 98 GB
PHP Time Limit: 3600
PHP Max Input Vars: 2500
cURL Version: 7.67.0
OpenSSL/1.1.1c

SUHOSIN Installed: –
MySQL Version: 5.7.28
Max Upload Size: 98 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.4.1
WC Database Prefix: wp_
Total Database Size: 1.20MB
Database Data Size: 1.03MB
Database Index Size: 0.17MB
wp_woocommerce_sessions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_api_keys: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_attribute_taxonomies: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_downloadable_product_permissions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_items: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_order_itemmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rates: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_tax_rate_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zones: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_locations: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_shipping_zone_methods: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokens: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_payment_tokenmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_woocommerce_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_actions: Data: 0.00MB + Index: 0.02MB + Engine MyISAM
wp_actionscheduler_claims: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_actionscheduler_groups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_actionscheduler_logs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_commentmeta: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_comments: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_links: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_options: Data: 0.91MB + Index: 0.03MB + Engine MyISAM
wp_postmeta: Data: 0.08MB + Index: 0.03MB + Engine MyISAM
wp_posts: Data: 0.03MB + Index: 0.02MB + Engine MyISAM
wp_termmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_terms: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_term_relationships: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_term_taxonomy: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_usermeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_admin_notes: Data: 0.01MB + Index: 0.00MB + Engine MyISAM
wp_wc_admin_note_actions: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_category_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_customer_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_download_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_coupon_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_product_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_stats: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_order_tax_lookup: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_product_meta_lookup: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_reserved_stock: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_wc_tax_rate_classes: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_wc_webhooks: Data: 0.00MB + Index: 0.00MB + Engine MyISAM

### Post Type Counts ###

attachment: 30
customize_changeset: 6
page: 7
post: 1
product: 29
revision: 8

### Security ###

Secure connection (HTTPS): ❌
					Your store is not using HTTPS. Learn more about HTTPS and SSL Certificates.
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 5.4.1

### Inactive Plugins (0) ###


### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #11 - /shop/
Basket: #12 - /basket/
Checkout: #13 - /checkout/
My account: #14 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Storefront
Version: 3.7.0
Author URL: https://woocommerce.com/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build
personally we recommend using a child theme. See: How to create a child theme

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 3
Oldest: 2021-07-11 16:40:55 +0100
Newest: 2021-07-12 12:21:46 +0100


### Status report information ###

Generated at: 2021-07-12 12:54:14 +01:00
`
```
</details>

**Comment by rodelgc** [comment]
Hi {username},

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

As you can see from my screenshot below, the alignment of the buttons are still consistent even though I used a product image with different dimensions (others are 800 x 800 pixels, while the odd one is at 800 x 400 px):

<img width="1172" alt="Screen Shot 2021-07-14 at 5 19 04 PM" src="https://user-images.githubusercontent.com/4509348/125597965-cda89383-0921-492f-963c-3d85f0dcee86.png">


Please provide us with more details about the issue which may help us to evaluate it further. It would also be a big help if you could include screenshots especially in visual issues like this.

**Comment by TBAIKamine** [comment]
please have the odd one use a product image of 800x100 (or the opposit: 100x800) thank you

**Comment by rodelgc** [comment]
Hi @TBAIKamine,

Thanks for the feedback. I am now able to reproduce the issue with the "Add to cart" button being out of alignment when the image thumbnail is 100 x 800.

<img width="823" alt="Screen Shot 2021-07-28 at 8 14 49 PM" src="https://user-images.githubusercontent.com/4509348/127320768-673cb6d0-8b45-4b57-8995-560ccacb4249.png">

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the `type: enhancement` label and evaluate over time if this issue collects more feedback. 
﻿
Don’t be alarmed if you don’t see any activity on this issue for a while.
