### ISSUE TITLE
Anonymize Customer IP Address (in Download Reports)

### ISSUE THREAD

**Issue by ouun** [woocommerce/woocommerce#30268]
Hi there,

WooCommerce saves a downloaders IP-Adress and displays it on the reports. This is quite critical for GDPR and requires a shop owner to take care of it in the privacy policy, while it is not something that a shop owner needs to know.
I can understand if this is related to the downloads credentials system, however wouldn't it be possible to anonymize the IP at least by truncating the last part?

I was searching for a hook that allows me to anonymize the IP before saving it to the DB but wasn't able to finde one. Shouldn't be something possible with a hook such as `'woocommerce_customer-download-log_get_user_ip_address'`?
Or better a hook I can use to filter what is saved to the DB?
 
Thanks a lot for your feedback!

**Comment by rodelgc** [comment]
Hi @ouun,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by kkmuffme** [comment]
Please read up on what GDPR actually says. This is a non-issue and can be closed.

>“Processing shall be lawful only if and to the extent that at least one of the following applies: […] (f) processing is necessary for the purposes of the legitimate interests pursued by the controller or by a third party, except where such interests are overridden by the interests or fundamental rights and freedoms of the data subject which require protection of personal data, in particular where the data subject is a child.”

-- Article 6, Paragraph 1, Point F

>“The processing of personal data to the extent strictly necessary and proportionate for the purposes of ensuring network and information security, i.e. the ability of a network or an information system to resist, at a given level of confidence, accidental events or unlawful or malicious actions that compromise the availability, authenticity, integrity and confidentiality of stored or transmitted personal data, and the security of the related services offered by, or accessible via, those networks and systems, […] by providers of electronic communications networks and services and by providers of security technologies and services, constitutes a legitimate interest of the data controller concerned. This could, for example, include preventing unauthorised access to electronic communications networks and malicious code distribution and stopping ‘denial of service’ attacks and damage to computer and electronic communication systems.”

-- Recital 49 (excerpt)

**Comment by ouun** [comment]
Thanks for your feedback @kkmuffme. I understand that saving the IP is compliant as it is required by WooCommerce to grant access to downloads only to specific IPs? Is that correct?

Don't you agree that in various scenarios saving the full IP address is _not neccessary_ and therefore _not compliant_. In my case for example I do not need to know the IPs of the downloaders. It simply does not matter to me who downloaded it, I just want to know that it was downloaded. As it is _not neccessary_ storing the full IPs makes WooCommerce incompliant in my case. Even when it would be OK I have a privacy focused attitude and just want to collect as less data as possible.

That is why I asked for a hook that allows me to adjust (truncate) the IPs before they are saved to the DB. Is there one available? 

Thanks again for your time and patience,

Philipp

**Comment by kkmuffme** [comment]
Partial IPs are useless.

If you dont want to have any IP information, you can just unset the following parameters on an early hook, to ensure they are not passed/used anywhere.

```
$_SERVER['HTTP_X_REAL_IP']
$_SERVER['HTTP_X_FORWARDED_FOR']
$_SERVER['REMOTE_ADDR']
```

If you are really about that GDPR thing, then it's best to already not set them/unset them in your nginx config or with a php prepend file, so it happens before any code/application can use the IP information from these headers.

**Comment by jonathansadowski** [comment]
Hi @ouun,

You should be able to filter this value using the `woocommerce_before_customer_download_log_object_save` hook. Before the log is saved, you can filter the value as needed. I'm going to close this issue, as that hook should provide what you're asking for, but please let me know if there's something I've missed.
