### ISSUE TITLE
[WC5.5] Site crashes: Call to undefined function as_next_scheduled_action()

### ISSUE THREAD

**Issue by olegabr** [woocommerce/woocommerce#30273]
See https://github.com/woocommerce/action-scheduler/issues/730 please

**Comment by rodelgc** [comment]
Hi @olegabr,

> See woocommerce/action-scheduler#730 please

That issue is already queued in the `woocommerce/action-scheduler` repository and will be picked up by their team soon. Kindly wait for their response on that repository instead.

I'll close this duplicate issue.
