### ISSUE TITLE
`WC_Customer` class has no `$object_type` property specified

### ISSUE THREAD

**Issue by danielbitzer** [woocommerce/woocommerce#30272]
**Prerequisites (mark completed items with an [x]):**
- [x] I have checked that my issue type is not listed here https://github.com/woocommerce/woocommerce/issues/new/choose
- [x] My issue is not a security issue, support request, bug report, enhancement or feature request (Please use the link above if it is).

**Issue Description:**

In order to [integrate AutomateWoo with the new block checkout](https://github.com/woocommerce/woocommerce-gutenberg-products-block/issues/4252) we need to be able to hook in to the `WC_Customer::save()` method. We would expect do this with the following hook in the `WC_Data` class:

https://github.com/woocommerce/woocommerce/blob/6ed8ffe8509e2047154aeed6304d7d5ee283d677/includes/abstracts/abstract-wc-data.php#L207-L213

One issue here is that the `$object_type` for the `WC_Customer` class is not set so it inherits the value of `'data'`. Should we be setting the object type to `'customer'` here?

**Comment by vedanshujain** [comment]
Yeah we should, would you be open to sending in a PR for this?
