### ISSUE TITLE
Error: undefined is not an object (evaluating 'e[t].call')

### ISSUE THREAD

**Issue by bkroll27** [woocommerce/woocommerce#30289]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x ] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Receiving Error: undefined is not an object (evaluating 'e[t].call') on the shop page for Safari users. 

**Expected behavior**
When visiting shop page, products should be loading.

**Actual behavior**
Previewed shop page on Safari and received this error. Content will not load.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Open 14.1.1 version of Safari and Chrome 91.0.4472.114.
2. Visit https://walkrightin.org/shop/
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/20175187/125704913-31481d12-0965-4d13-8e61-17b29f126e77.png)

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
`
### WordPress Environment ###

WordPress address (URL): https://walkrightin.org
Site address (URL): https://walkrightin.org
WC Version: 5.5.1
REST API Version: ✔ 5.5.1
WC Blocks Version: ✔ 5.3.2
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.4.1
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: ✔

### Server Environment ###

Server Info: nginx
PHP Version: 7.3.29
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 7.77.0
OpenSSL/1.1.0l

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.21-MariaDB-log
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.5.1
WC Database Prefix: wp_
Total Database Size: 121.34MB
Database Data Size: 113.57MB
Database Index Size: 7.77MB
wp_woocommerce_sessions: Data: 0.11MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_actionscheduler_actions: Data: 0.06MB + Index: 0.11MB + Engine InnoDB
vp_backup_wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_commentmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_comments: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
vp_backup_wp_email_log: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_gglcptch_allowlist: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mo_campaign_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_mo_campaign_logmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_mo_conversions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_mo_email_campaignmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_mo_email_campaigns: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_mo_optin_campaignmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_mo_optin_campaigns: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_options: Data: 1.47MB + Index: 0.08MB + Engine InnoDB
vp_backup_wp_postmeta: Data: 1.52MB + Index: 0.34MB + Engine InnoDB
vp_backup_wp_posts: Data: 27.52MB + Index: 0.52MB + Engine InnoDB
vp_backup_wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_term_relationships: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
vp_backup_wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_usermeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_wpforms_entries: Data: 0.23MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wpforms_entry_fields: Data: 0.14MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_wpforms_entry_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
vp_backup_wp_yoast_indexable: Data: 0.39MB + Index: 0.31MB + Engine InnoDB
vp_backup_wp_yoast_indexable_hierarchy: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
vp_backup_wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
vp_backup_wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
vp_backup_wp_yoast_seo_links: Data: 0.25MB + Index: 0.19MB + Engine InnoDB
vp_backup_wp_yoast_seo_meta: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.06MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.14MB + Index: 0.09MB + Engine InnoDB
wp_email_log: Data: 4.52MB + Index: 0.00MB + Engine InnoDB
wp_gglcptch_allowlist: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_give_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_comments: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_donationmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_donormeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_donors: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_formmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_give_log: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_give_migrations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_revenue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_sequential_ordering: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_give_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mo_campaign_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mo_campaign_logmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mo_conversions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mo_email_campaignmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mo_email_campaigns: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mo_optin_campaignmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mo_optin_campaigns: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ms_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 1.23MB + Index: 0.08MB + Engine InnoDB
wp_pimwick_gift_card: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_pimwick_gift_card_activity: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_postmeta: Data: 1.52MB + Index: 0.38MB + Engine InnoDB
wp_posts: Data: 30.39MB + Index: 0.45MB + Engine InnoDB
wp_snippets: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_usermeta: Data: 0.09MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_square_customers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_entries: Data: 0.23MB + Index: 0.02MB + Engine InnoDB
wp_wpforms_entry_fields: Data: 0.14MB + Index: 0.05MB + Engine InnoDB
wp_wpforms_entry_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 0.45MB + Index: 0.33MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.30MB + Index: 0.14MB + Engine InnoDB
wp_yoast_seo_meta: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
__wp_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
__wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_commentmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
__wp_comments: Data: 0.13MB + Index: 0.09MB + Engine InnoDB
__wp_email_log: Data: 3.52MB + Index: 0.00MB + Engine InnoDB
__wp_gglcptch_allowlist: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mo_campaign_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_mo_campaign_logmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_mo_conversions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_mo_email_campaignmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_mo_email_campaigns: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_mo_optin_campaignmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_mo_optin_campaigns: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_options: Data: 1.36MB + Index: 0.08MB + Engine InnoDB
__wp_postmeta: Data: 1.52MB + Index: 0.33MB + Engine InnoDB
__wp_posts: Data: 27.41MB + Index: 0.45MB + Engine InnoDB
__wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_term_relationships: Data: 0.08MB + Index: 0.05MB + Engine InnoDB
__wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_tm_taskmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_tm_tasks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_usermeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
__wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
__wp_wpforms_entries: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
__wp_wpforms_entry_fields: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
__wp_wpforms_entry_meta: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_wpmm_subscribers: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
__wp_yoast_indexable: Data: 0.39MB + Index: 0.30MB + Engine InnoDB
__wp_yoast_indexable_hierarchy: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
__wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
__wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
__wp_yoast_seo_links: Data: 0.28MB + Index: 0.16MB + Engine InnoDB
__wp_yoast_seo_meta: Data: 0.08MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

attachment: 489
customize_changeset: 123
custom_css: 1
feedback: 3
give_forms: 1
give_payment: 8
jetpack_migration: 2
jp_img_sitemap: 2
jp_sitemap: 2
jp_sitemap_master: 2
jp_vid_sitemap: 2
nav_menu_item: 34
oembed_cache: 2
page: 35
post: 330
postman_sent_mail: 7
product: 7
product_variation: 10
revision: 1533
rttpg: 1
shop_order: 6
wpforms: 3
wpplugin_don_button: 2
wpplugin_don_order: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (27) ###

Akismet Anti-Spam: by Automattic – 4.1.10
AMP: by AMP Project Contributors – 2.1.3
Blog Designer Pack: by InfornWeb – 2.2.7
Blogger Importer: by wordpressdotorg – 0.9
Code Snippets: by Code Snippets Pro – 2.14.1
PayPal Donation: by Scott Paterson – 1.3
Easy WP SMTP: by wpecommerce
alexanderfoxc – 1.4.7

Email Log: by Sudar – 2.4.5
Exclude Pages From Menu: by Vinod Dalvi – 3.0
Give - Donation Plugin: by GiveWP – 2.11.3
reCaptcha by BestWebSoft: by BestWebSoft – 1.62
Gutenberg: by Gutenberg Team – 11.0.0
Insert Headers and Footers: by WPBeginner – 1.6.0
Jetpack: by Automattic – 9.9
PW WooCommerce Gift Cards: by Pimwick
LLC – 1.183

Sucuri Security - Auditing, Malware Scanner and Hardening: by Sucuri Inc. – 1.8.26
TC Custom JavaScript: by Tiny Code – 1.2.3
WooCommerce Menu Cart: by Jeremiah Prummer
Ewout Fernhout – 2.9.8

WooCommerce Name Your Price: by Kathy Darling – 3.3.1
WooCommerce Shipping & Tax: by WooCommerce – 1.25.17
WooCommerce Square: by WooCommerce – 2.5.1
WooCommerce: by Automattic – 5.5.1
Yoast SEO: by Team Yoast – 16.7
WP 2FA - Two-factor authentication for WordPress: by WP White Security – 1.6.2
WP Mail SMTP: by WPForms – 2.9.0
WPExperts Square For GiveWP: by wpexpertsio – 1.0
WPForms: by WPForms – 1.6.8

### Inactive Plugins (10) ###

Classic Editor: by WordPress Contributors – 1.6
CoBlocks: by GoDaddy – 2.14.0
Enable jQuery Migrate Helper: by The WordPress Team – 1.3.0
Health Check & Troubleshooting: by The WordPress.org community – 1.4.5
Layout Grid: by Automattic – 1.7
MailOptin - Lite: by MailOptin Team – 1.2.38.0
Page Optimize: by Automattic – 0.5.1
Shortcodes Anywhere or Everywhere: by David Gewirtz – 1.4.2
WordPress.com Editing Toolkit: by Automattic – 3.10777
WP Maintenance Mode: by Designmodo – 2.4.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Must Use Plugins (2) ###

Health Check Troubleshooting Mode: by  – 1.7.2
WP.com Site Helper: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
pw gift card (pw-gift-card)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #3696 - /shop/
Cart: #3589 - /cart/
Checkout: #3591 - /checkout/
My account: #3593 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Maisha
Version: 2.0.8
Author URL: http://theme.wordpress.com/themes/by/anariel-design/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Square ###

Environment: Production
Tokenization Enabled: –
Debug Mode: Off

### Action Scheduler ###

Complete: 100
Oldest: 2021-06-14 18:06:15 +0000
Newest: 2021-07-14 18:49:26 +0000

Pending: 7
Oldest: 2021-07-15 00:15:00 +0000
Newest: 2021-07-21 05:52:04 +0000

### Name Your Price ###

Version: 
Template overrides: –

### Status report information ###

Generated at: 2021-07-14 23:13:50 +00:00
`

**Comment by rodelgc** [comment]
Hi @bkroll27 ,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. 

I did not get the error message when I visited your site using my Chrome v.91.0.4472.164 and Safari v.14.1.1:
<img width="1635" alt="Screen Shot 2021-07-16 at 1 54 30 PM" src="https://user-images.githubusercontent.com/4509348/125899250-12c7df65-b018-4fff-b768-d57f9742d2ed.png">
<img width="1321" alt="Screen Shot 2021-07-16 at 1 52 42 PM" src="https://user-images.githubusercontent.com/4509348/125899270-1ee8a4df-23f9-475d-8273-8b03d35cf0a5.png">

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.
﻿
If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.
