### ISSUE TITLE
Install Basic Auth plugin during E2E initialization

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce#30280]
> It would be nice to have the Basic Auth plugin installed by default. createSimpleProduct() doesn't work until it is installed, and I assume other functions too.

- From https://github.com/woocommerce/woocommerce-e2e-boilerplate/issues/9

We can move this plugin install from our local configuration to the environment package. `external.md` will need an update for this.

**Comment by lanej0** [comment]
(I didn't do it, but this looks like it's done)

In testing, Basic Auth is installed and active when you spin up an environment.  It's part of the base image we're using, and then [this line](https://github.com/woocommerce/woocommerce/blob/aa8b7a4a6b7d21ccddaac360766c4daa396b9a98/plugins/woocommerce/tests/e2e/docker/initialize.sh#L6) activates it.
