### ISSUE TITLE
admin_styles() in class-wc-admin-assets.php throws a fatal error if no screen is available.

### ISSUE THREAD

**Issue by patrick-leb** [woocommerce/woocommerce#30281]
**New since 5.5.0** --

**Prerequisites (mark completed items with an [x]):**
- [ x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [ x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Commit https://github.com/woocommerce/woocommerce/commit/ee08d2d110ad2f5aef30dbe90b25b2acb0e49974 introduced 
```php
if ( $screen->is_block_editor() ) {
 				wp_register_style( 'woocommerce-general', WC()->plugin_url() . '/assets/css/woocommerce.css', array(), $version );
 				wp_style_add_data( 'woocommerce-general', 'rtl', 'replace' );
 			}
```

However, $screen can be null, as checked per the function definition:
```php
/**
 * Get the current screen object
 *
 * @since 3.1.0
 *
 * @global WP_Screen $current_screen WordPress current screen object.
 *
 * @return WP_Screen|null Current screen object or null when screen not defined.
 */
function get_current_screen() {
	global $current_screen;

	if ( ! isset( $current_screen ) ) {
		return null;
	}

	return $current_screen;
}
```

This is handled just above in the file, 
https://github.com/woocommerce/woocommerce/blob/d06cfc38e8872239450e8f4e220a3ff019dfe132/includes/admin/class-wc-admin-assets.php#L38
but not for this call.

Suggested fix:

```php

			if ( ! is_null( $screen) && $screen->is_block_editor() ) {
				wp_register_style( 'woocommerce-general', WC()->plugin_url() . '/assets/css/woocommerce.css', array(), $version );
				wp_style_add_data( 'woocommerce-general', 'rtl', 'replace' );
			}
```

**Comment by patrick-leb** [comment]
Actually, there is PR open without an issue for it: here:
https://github.com/woocommerce/woocommerce/pull/30277

**Comment by rodelgc** [comment]
Hi @patrick-leb,
﻿
Thank you for taking the time to report this bug and searching through the open PR's related to this. We really appreciate your help. Priority of this issue will be assigned shortly.

**Comment by vedanshujain** [comment]
Hi everyone, please note that while this issue is closed and merged a patch to the trunk, it may take a while before this patch is available in a release (although it will be no later than 5.6 which is scheduled for August 10), because of [ongoing security patch rollout](https://woocommerce.com/posts/critical-vulnerability-detected-july-2021/).
