### ISSUE TITLE
Extra Tax added to order created via Rest Api

### ISSUE THREAD

**Issue by daizyDalisay** [woocommerce/woocommerce#30299]
Observed an issue with order total where order is created using woo api (/wp-json/wc/v3/orders). My tax setting says "Yes, I will enter prices inclusive of tax". But when an order is created via api, tax is added on top of total amount passed for line item. Please note I don't have any issue with tax where order is directly created on my website. I am not sure why tax is applied on line items total ? Anyone please help. Is there a filter/hook i can use to avoid this happening with orders created via api ?
![Screen Shot 2021-07-16 at 8 50 26 pm](https://user-images.githubusercontent.com/87478566/125936846-af7b8385-7cf2-40d2-8807-61294eaad102.png)
![Screen Shot 2021-07-15 at 10 00 09 pm](https://user-images.githubusercontent.com/87478566/125936859-b52026da-ab54-400b-a025-4d2f1fa08110.png)
![Screen Shot 2021-07-15 at 9 59 50 pm](https://user-images.githubusercontent.com/87478566/125936899-0d477eb9-e580-4e96-97b8-87f55d7228bc.png)

**Comment by rodelgc** [comment]
Hi @daizyDalisay,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by llampwall** [comment]
I'm having this issue as well. This is a major bug that is creating a discrepancy between the total purchase price being represented in the cart session vs the price that is represented in the final order. It is not clear at all that the tax will default to the shop base address even if you tell it that there is no default address.

**Comment by jonathansadowski** [comment]
Hi @daizyDalisay and @llampwall,

It looks like if you omit the total from the individual `line_items`, that the price is pulled from the item, and that taxes are handled appropriately. Could you give that a try and let me know if that works for you?
