### ISSUE TITLE
possible to update this asap?

### ISSUE THREAD

**Issue by hiqsociety** [woocommerce/woocommerce#30295]
https://patchstack.com/woocommerce-sql-injection-vulnerability/

**Comment by rodelgc** [comment]
Hello @hiqsociety,

There is already a WooCommerce patch available to address this issue (version 5.5.1). We have already started deploying auto-updates to affected stores a couple of days ago, and we're strongly recommending our users to upgrade to this version.

You can see more details about the issue [here](https://woocommerce.com/posts/critical-vulnerability-detected-july-2021/) and the developer advisory [here](https://developer.woocommerce.com/2021/07/15/developer-advisory-critical-vulnerability-in-multiple-versions-of-woocommerce/).

If you need further assistance, you may reach out to our Happiness Engineers by creating a support ticket here - https://woocommerce.com/my-account/create-a-ticket/

If you are a paying customer of WooCommerce, contact WooCommerce support by [opening a ticket or starting a live chat](https://woocommerce.com/contact-us/)
