### ISSUE TITLE
Preserve hierarchy taxonomy displaying on the "exclude category" field from coupon menu

### ISSUE THREAD

**Issue by maawco** [woocommerce/woocommerce#30306]
Hi,

I manage a big e-commerce with a lot of product (more than 5000) with WooCommerce. And i would like to prevent coupon from some specific category. 

The problem is that i have a lots of child category who have the same name. There is the screenshot for exemple https://d.pr/i/d3uc41/59q7kKRCmo and it's impossible to know from wich parent taxonomy the child come from. 

If you want i can provide you a little plugin that i use this sometimes for preserve the hierarchy taxonomy for the Core WordPress > menu editing (because there is the same problem).

It would be great i think to add this Enhancement for WooCommerce and would help people to use WooCommerce for big shop. 

Thx a lot !
[hierarchy-taxonomy-box.zip](https://github.com/woocommerce/woocommerce/files/6836667/hierarchy-taxonomy-box.zip)

**Comment by tammullen** [comment]
Hi @maawco 

Thank you for taking the time to share this idea, we really appreciate your help. 
​
While this is clearly a great improvement/idea we won’t be able to tackle it in the upcoming weeks. We’re going to add it to our backlog where it will be considered for future releases.

**Comment by maawco** [comment]
Hi @tammullen and thank you for your reply and considering our request. 
We really appreciate it. No problem for waiting a bit this improvement !

Thanks again !
