### ISSUE TITLE
MySQL usage too high after WooComemrce update

### ISSUE THREAD

**Issue by Sapkotaanish** [woocommerce/woocommerce#30317]
After I updated the WooCommerce to version 5.5.1, MySQL (AWS RDS) usage went towards 100%. But the site was working normally and fine. After some research, I found out that this happens when I visit the 'orders' page in WooCommerce (from wp-admin). 
I checked the process list in MySQL and saw this query running: 

```
SELECT SQL_CALC_FOUND_ROWS  hbm_posts.*, low_stock_amount_meta.meta_value AS low_stock_amount, MAX( product_lookup.date_created ) AS last_order_date FROM hbm_posts  LEFT JOIN hbm_wc_product_meta_lookup wc_product_meta_lookup ON hbm_posts.ID = wc_product_meta_lookup.product_id  LEFT JOIN hbm_postmeta AS low_stock_amount_meta ON hbm_posts.ID = low_stock_amount_meta.post_id AND low_stock_amount_meta.meta_key = '_low_stock_amount'  LEFT JOIN hbm_wc_order_product_lookup product_lookup ON hbm_posts.ID = CASE
                WHEN hbm_posts.post_type = 'product' THEN product_lookup.product_id
                WHEN hbm_posts.post_type = 'product_variation' THEN product_lookup.variation_id
            END WHERE 1=1  AND hbm_posts.post_type IN ('product', 'product_variation') AND ((hbm_posts.post_status = 'publish'))
            AND wc_product_meta_lookup.stock_quantity IS NOT NULL
            AND wc_product_meta_lookup.stock_status IN('instock','outofstock')
            AND (
                (
                    low_stock_amount_meta.meta_value > ''
                    AND wc_product_meta_lookup.stock_quantity <= CAST(low_stock_amount_meta.meta_value AS SIGNED)
                )
                OR (
                    (
                        low_stock_amount_meta.meta_value IS NULL OR low_stock_amount_meta.meta_value <= ''
                    )
                    AND wc_product_meta_lookup.stock_quantity <= 2
                )
            ) GROUP BY hbmSELECT SQL_CALC_FOUND_ROWS  hbm_posts.*, low_stock_amount_meta.meta_value AS low_stock_amount, MAX( product_lookup.date_created ) AS last_order_date FROM hbm_posts  LEFT JOIN hbm_wc_product_meta_lookup wc_product_meta_lookup ON hbm_posts.ID = wc_product_meta_lookup.product_id  LEFT JOIN hbm_postmeta AS low_stock_amount_meta ON hbm_posts.ID = low_stock_amount_meta.post_id AND low_stock_amount_meta.meta_key = '_low_stock_amount'  LEFT JOIN hbm_wc_order_product_lookup product_lookup ON hbm_posts.ID = CASE
            WHEN hbm_posts.post_type = 'product' THEN product_lookup.product_id
            WHEN hbm_posts.post_type = 'product_variation' THEN product_lookup.variation_id
        END WHERE 1=1  AND hbm_posts.post_type IN ('product', 'product_variation') AND ((hbm_posts.post_status = 'publish'))
        AND wc_product_meta_lookup.stock_quantity IS NOT NULL
        AND wc_product_meta_lookup.stock_status IN('instock','outofstock')
        AND (
            (
                low_stock_amount_meta.meta_value > ''
                AND wc_product_meta_lookup.stock_quantity <= CAST(low_stock_amount_meta.meta_value AS SIGNED)
            )
            OR (
                (
                    low_stock_amount_meta.meta_value IS NULL OR low_stock_amount_meta.meta_value <= ''
                )
                AND wc_product_meta_lookup.stock_quantity <= 2
            )
        ) GROUP BY hbm_posts.ID ORDER BY hbm_posts.post_date DESC, hbm_posts.ID DESC LIMIT 0, 1_posts.ID ORDER BY hbm_posts.post_date DESC, hbm_posts.ID DESC LIMIT 0, 1
```

Each time I visit orders page, one query adds up in the queue. Its status is `sending data`. 
I tried deactivating all plugins (except WooCommerce) and themes (except default theme) but no luck. But the most interesting part was that everything was running fine (orders, site, etc). 

I reverted the plugin to older version (5.4.2) and the database usage fell down.

Note: I have about 26,500 orders in total and the database class is db.t3.large (1 core, 2vCPUs, 8GB memory). The traffic in the site is also fairly small (about 1000 per day). 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Install WooCommerce version 5.5.1.
2. Use AWS RDS of class db.t3.large.
3. Add more than 26,000 orders.
4. Visit orders page.
5. See CPU usage in RDS.

**Isolating the problem**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**Comment by hcw-rohan** [comment]
Experiencing the similar issues on two client sites, the larger one intermittently unusable. Orders would time out on the front end on submit and on the backend we couldn't access product details or in some cases order details. Reverted to 5.4.2 and problem was fixed.

**Comment by tammullen** [comment]
Hi @Sapkotaanish and @hcw-rohan 

Thank you for reporting the issue. However, I believe this is related to this issue which had been reported previously here https://github.com/woocommerce/woocommerce-admin/issues/7358. We are closing your issue in favor of the previously submitted. The latest information will appear there and please continue sharing your feedback there if needed.
