### ISSUE TITLE
Make a simple, printable option for the Edit Order screen

### ISSUE THREAD

**Issue by Farallon5** [woocommerce/woocommerce#30312]
When an admin is fulfilling orders, it should be a normal thing to be able to print an order. 

One click should get a print dialog with a few options for printer, page size, fit to one page and print preview. That's basically it. 

I know there are several good plugins that provide this functionality and more, but the basic print ability should be part of core Woo without needing a plugin.

If there is already something I could add my vote to on this, please let me know.  Thanks!

**Comment by tammullen** [comment]
Hi @Farallon5 

Thank you for taking the time to share this idea, we really appreciate your help. As you noted there are extensions which provide this functionality but not in core. I also couldn't find an existing enhancement issue to vote on so we will use your issue for others to provide feedback on.
​
While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. 

In the meantime, we are going to close this issue with the `votes needed` label and evaluate over time if this issue collects more feedback. 
​
Don’t be alarmed if you don’t see any activity on this issue for a while.
