### ISSUE TITLE
Downloads no longer supporting URLs

### ISSUE THREAD

**Issue by streamworksaudio** [woocommerce/woocommerce#30322]
This is has been working for me in the up till today, I have a custom post type to handle downloads, we were placing the URL (permalink) into the product download field and it was working.  However, today we have had a couple customers contact us and say that they are getting an error 'File not found, go to shop.'.

If I recall we did update WooCommerce to 5.5.1 the other day, is this something that has changed with what can be put into the download 'File URL'?  

The custom post type is used to run a couple security check to make sure the person purchased the video then generates an AWS signed url and redirects then to that URL - so I am hoping we can still do that.

**Comment by tammullen** [comment]
Hi @streamworksaudio ,

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/30288. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
