### ISSUE TITLE
When I try to load a file of products, apears that The file can´t be open by security

### ISSUE THREAD

**Issue by Pablo4372** [woocommerce/woocommerce#30323]
At the begining I export a file from the products in CSV format, without change anything, I cant upload ( import ) the same file because appears "The file can´t be open by security" in spanish.

`
### WordPress Environment ###

WordPress address (URL): http://eutectic-store.com
Site address (URL): http://eutectic-store.com
WC Version: 5.5.1
REST API Version: ✔ 5.5.1
WC Blocks Version: ✔ 5.3.2
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.4.1
Log Directory Writable: ✔
WP Version: 5.7.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.21
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1k-fips

SUHOSIN Installed: –
MySQL Version: 5.7.32-35-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.5.1
WC Database Prefix: lmi_
Tamaño total de la base de datos: 14.46MB
Tamaño de los datos de la base de datos: 11.35MB
Tamaño del índice de la base de datos: 3.11MB
lmi_woocommerce_sessions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lmi_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
lmi_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_woocommerce_order_itemmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lmi_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
lmi_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lmi_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
lmi_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lmi_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
lmi_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lmi_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_actionscheduler_actions: Datos: 0.09MB + Índice: 0.13MB + Motor InnoDB
lmi_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_actionscheduler_logs: Datos: 0.05MB + Índice: 0.03MB + Motor InnoDB
lmi_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lmi_comments: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
lmi_e_submissions: Datos: 0.02MB + Índice: 0.27MB + Motor InnoDB
lmi_e_submissions_actions_log: Datos: 0.02MB + Índice: 0.11MB + Motor InnoDB
lmi_e_submissions_values: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lmi_gla_budget_recommendations: Datos: 0.22MB + Índice: 0.14MB + Motor InnoDB
lmi_gla_merchant_issues: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_gla_shipping_rates: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lmi_gla_shipping_times: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_mailchimp_carts: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
lmi_mailchimp_jobs: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
lmi_mailpoet_custom_fields: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_mailpoet_dynamic_segment_filters: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_mailpoet_feature_flags: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_mailpoet_forms: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
lmi_mailpoet_log: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
lmi_mailpoet_mapping_to_external_entities: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_mailpoet_newsletters: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lmi_mailpoet_newsletter_links: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
lmi_mailpoet_newsletter_option: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_mailpoet_newsletter_option_fields: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_mailpoet_newsletter_posts: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_mailpoet_newsletter_segment: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_mailpoet_newsletter_templates: Datos: 2.52MB + Índice: 0.00MB + Motor InnoDB
lmi_mailpoet_scheduled_tasks: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lmi_mailpoet_scheduled_task_subscribers: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_mailpoet_segments: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lmi_mailpoet_sending_queues: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lmi_mailpoet_settings: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_mailpoet_statistics_clicks: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
lmi_mailpoet_statistics_forms: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_mailpoet_statistics_newsletters: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lmi_mailpoet_statistics_opens: Datos: 0.02MB + Índice: 0.08MB + Motor InnoDB
lmi_mailpoet_statistics_unsubscribes: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
lmi_mailpoet_statistics_woocommerce_purchases: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
lmi_mailpoet_stats_notifications: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lmi_mailpoet_subscribers: Datos: 0.02MB + Índice: 0.13MB + Motor InnoDB
lmi_mailpoet_subscriber_custom_field: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_mailpoet_subscriber_ips: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_mailpoet_subscriber_segment: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lmi_mailpoet_user_flags: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_options: Datos: 3.03MB + Índice: 0.08MB + Motor InnoDB
lmi_postmeta: Datos: 3.38MB + Índice: 0.16MB + Motor InnoDB
lmi_posts: Datos: 0.42MB + Índice: 0.06MB + Motor InnoDB
lmi_sgs_log_events: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
lmi_sgs_log_visitors: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
lmi_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lmi_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lmi_term_relationships: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lmi_usermeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lmi_users: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
lmi_wc_admin_notes: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
lmi_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
lmi_wc_customer_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lmi_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lmi_wc_order_coupon_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lmi_wc_order_product_lookup: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
lmi_wc_order_stats: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
lmi_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
lmi_wc_product_meta_lookup: Datos: 0.02MB + Índice: 0.09MB + Motor InnoDB
lmi_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
lmi_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
lmi_wpforms_tasks_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB

### Post Type Counts ###

attachment: 21
customize_changeset: 30
elementor_library: 1
mailpoet_page: 1
nav_menu_item: 14
page: 10
post: 3
product: 1
product_variation: 4
revision: 227
shop_order: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (20) ###

Akismet Anti-Spam: por Automattic – 4.1.10
Astra Pro: por Brainstorm Force – 3.5.5
Elementor Pro: por Elementor.com – 3.3.2
Elementor: por Elementor.com – 3.3.1
Facebook for WooCommerce: por Facebook – 2.6.1
Google Listings and Ads: por WooCommerce – 1.2.1
Mailchimp for WooCommerce: por Mailchimp – 2.5.1
MailPoet 3 (Nuevo): por MailPoet – 3.65.1
SiteGround Optimizer: por SiteGround – 5.8.2
SG Security: por SiteGround – 1.0.4
TablePress: por Tobias Bäthge – 1.14
Variation Swatches for WooCommerce: por Emran Ahmed – 1.1.17
WooCommerce Stripe Gateway: por WooCommerce – 5.2.3
WooCommerce Menu Cart: por Jeremiah Prummer
Ewout Fernhout – 2.9.8

WooCommerce PDF Invoices & Packing Slips: por Ewout Fernhout – 2.9.0
WooCommerce Shipping & Tax: por WooCommerce – 1.25.17
WooCommerce: por Automattic – 5.5.1
WordPress Importer: por wordpressdotorg – 0.7
WordPress Starter: por SiteGround – 1.1.7
WPForms Lite: por WPForms – 1.6.8

### Inactive Plugins (1) ###

Jetpack: por Automattic – 9.9

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: 
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Base de la tienda: ❌ La visibilidad de la página debe ser pública
Carrito: #2134 - /woocommerce_cart/
Finalizar compra: #2135 - /proceed-to-checkout/
Mi cuenta: #2168 - /my-account/
Términos y condiciones: #2166 - /privacy-policies/

### Theme ###

Name: Astra
Version: 3.6.5
Author URL: https://wpastra.com/about/
Child Theme: ❌ – Si estás modificando WooCommerce en un tema padre que no has creado personalmente
te recomendamos utilizar un tema hijo. Ver: Cómo crear un tema hijo

WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Completo: 261
Oldest: 2021-06-21 17:01:49 +0000
Newest: 2021-07-20 16:10:00 +0000

Pendiente: 4
Oldest: 2021-07-21 13:56:55 +0000
Newest: 2021-07-27 09:28:35 +0000

### Status report information ###

Generated at: 2021-07-20 16:38:02 +00:00
`

**Comment by Pablo4372** [comment]
Lo siento, este tipo de archivo no está permitido por motivos de seguridad.

**Comment by tammullen** [comment]
Hi @Pablo4372 ,

Thank you for raising the issue. 

> "Lo siento, este tipo de archivo no está permitido por motivos de seguridad."

I do not see this string in WooCommerce
https://translate.wordpress.org/projects/wp-plugins/woocommerce/stable/es/default/?filters%5Bterm%5D=seguridad&filters%5Bterm_scope%5D=scope_translations&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

Can you confirm if the issue exists after doing the above plugin conflict test?
