### ISSUE TITLE
Mini cart cache problem

### ISSUE THREAD

**Issue by erikdemarco** [woocommerce/woocommerce#30329]
I use cloudflare and set to cache my site. The cart contents show other people's cart before updated to current visitor cart contents. The updating takes split seconds, but still it looks unprofessional. Why other people can see other people contents?
I think it not just cloudflare, it will be the same with other cache plugin.

To recreate the problem:
-) use any cache plugin. For my case I use "WP Cloudflare Super Page Cache"
-) Browse couple pages of the shop as loggedout user
-) Add many different products to cart. Let say '3' products.
-) Purge cache
-) Wait 30seconds for all cache to be purged.
-) Load homepage and couple product page you can remember
-) Remove all your carts
-) Browse using other browser or device (To simulate other people browsing)
-) Now when you load page as a completely new user, And open pages that you remember previously. For split second you will see the cart total is '3' before it gets updated with 0

To fix:
Cart widget (storefront_cart_link), on first load the contents of the cart should be empty, before ajax takes care of showing the updated contents. We should only show real cart value if its requested by ajax.

**Comment by erikdemarco** [comment]
Fixed. Case Closed

**Comment by samlangdon** [comment]
> Fixed. Case Closed

Hi - sorry, I realise it's 3 years later, but I'm having exactly the same issue. Can I ask how you fixed this?

Many thanks,
Sam
