### ISSUE TITLE
Broken Store Link in House Icon Menu

### ISSUE THREAD

**Issue by akissz** [woocommerce/woocommerce#30333]
In network multisite mode. To reproduce bug, activate a "homepage" in wordpress settings > reading page. Now go into woocommerce settings > products tab. Set the store page to be the same "homepage" and now see the store link in the house icon menu is now missing from the wordpress top header menu. See screen shots here.
![image](https://user-images.githubusercontent.com/23090286/126588911-83e5a061-ae77-44d1-8c55-7c10d765831f.png)
![image](https://user-images.githubusercontent.com/23090286/126588923-25fc1de9-e121-46ec-9cb9-40284187f2b4.png)

**Comment by tammullen** [comment]
Hi @akissz 
I think this is expected behaviour as the store is no longer a different page to the site homepage so there is only one link.
A broken link would normally be described as linking to a URL that doesn't exist. In this case the "Visit Site" link brings us to the homepage which is now the store.

Is there a scenario that requires the site admin to need a separate store menu item when it is the same as the site?

**Comment by akissz** [comment]
I was thinking rapidly when I wrote the report. And seconds later I thought what you wrote in your reply. But still it is still slightly all wrong. Perhaps there is a better way to make this all function. I don't want to say remove ' visit site ' all together but that is the only option I can imagine. So maybe if store enabled, remove ' visit site ' ....... or another idea... Its not good as it is now!

**Comment by tammullen** [comment]
Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the `votes needed` label and evaluate over time if this issue collects more feedback. 

Don’t be alarmed if you don’t see any activity on this issue for a while
