### ISSUE TITLE
 [GlobalStep] "PHP errors in Ajax response" gets triggered on browser console while importing Sample Products CSV.

### ISSUE THREAD

**Issue by gglobalstep** [woocommerce/woocommerce#30339]
## Bug Description:
"PHP errors in Ajax response" gets triggered on browser console while importing Sample Products CSV.

## Environment:
Woocommerce Version : WooCommerce 5.5.1
WordPress version: v5.8

PC:
Windows 10, Mac 10.14.6
Chrome(Version 91.0.4472.77) 
Firefox(Version 89.0.2)
Safari: v14.0

## Steps To Reproduce:
1. Create any test site using JN site.
1. Install and activate all the required plugins.
1. Complete the onboarding setup wizard.
1. Visit to Products screen.
1. Click on "Start Import" button.
1. Import the products CSV and click on "Run the importer" button.
1. Observe that "PHP errors in Ajax response" error flashes.

## Actual Result:
"PHP errors in Ajax response" gets triggered on browser console while importing Sample Products CSV.

## Expected Result:
Sample Products CSV should get import without any error message.

## Screenshot:

![#30339](https://user-images.githubusercontent.com/41110392/126665720-ec882dc4-27ee-43a1-a4b0-1743111a426f.png)

*Isolating the problem (mark completed items with an [x]):*
- [ ] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ ] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

<details>

`
### WordPress Environment ###

WC Version: 5.5.1
REST API Version: ✔ 5.5.1
WC Blocks Version: ✔ 5.3.2
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.4.1
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.48 (Unix) OpenSSL/1.0.2g
PHP Version: 7.4.21
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.7.33-0ubuntu0.16.04.1-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.5.1
WC Database Prefix: wp_
Total Database Size: 3.73MB
Database Data Size: 2.30MB
Database Index Size: 1.43MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 1.31MB + Index: 0.03MB + Engine InnoDB
wp_postmeta: Data: 0.11MB + Index: 0.06MB + Engine InnoDB
wp_posts: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB

### Post Type Counts ###

attachment: 24
page: 6
post: 2
product: 18
product_variation: 7

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (4) ###

Query Monitor: by John Blackbourn – 3.7.1
Companion Plugin: by Osk – 1.18
Jetpack: by Automattic – 9.9.1
WooCommerce: by Automattic – 5.5.1

### Inactive Plugins (2) ###

Akismet Anti-Spam: by Automattic – 4.1.10
Hello Dolly: by Matt Mullenweg – 1.7.2

### Dropin Plugins (1) ###

db.php: Query Monitor Database Class

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #6 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-One
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 23
Oldest: 2021-07-22 14:47:10 +0000
Newest: 2021-07-22 14:47:23 +0000

### Status report information ###

Generated at: 2021-07-22 14:58:25 +00:00
`

</details>

**Comment by zhongruige** [comment]
Hi @gglobalstep,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. 

* On WP 5.8 and WC 5.5.1, I created WC site but didn't import sample products as part of the setup checklist
* I went to `Products > All products` and clicked to `Start Import`
* I uploaded the sample products (sourced following [these instructions](https://docs.woocommerce.com/document/importing-woocommerce-sample-data/))
* The products imported successfully:

<img width="1534" alt="Screen Shot 2021-07-22 at 10 24 46" src="https://user-images.githubusercontent.com/71906536/126674274-51d8fe62-3661-4096-b25c-f77f68d2eb9c.png">

Please provide us with more details about the issue which may help us to evaluate it further. 

Can you let us know if you're still seeing this error on a fresh site? Thanks!

**Comment by gglobalstep** [comment]
> Please provide us with more details about the issue which may help us to evaluate it further.
> 
> Can you let us know if you're still seeing this error on a fresh site? Thanks!

We are still able to reproduce this issue on WooCommerce 5.6 Beta 1. Actually, the error flashes for few seconds while the products are importing on the Query monitor. Could you please check with the Query Monitor plugin?
Please refer to the video:

https://user-images.githubusercontent.com/41110392/127483084-72d72462-bd20-4ef9-be72-98b178287bda.mp4

**Comment by zhongruige** [comment]
Thank you for the clarification @gglobalstep! I was able to see the error with that. The products still successfully imported, and tagging I am tagging this with the `needs developer feedback` label for further feedback from the WooCommerce Core team so they can take a look

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
Thanks, all!

So, first of all, this doesn't look like a problem in our code:

* Noting first of all we're using Query Monitor and that `WP_DEBUG` is enabled (this is true by default when using sites spun up on JN).
* Relevant WP code [can be seen here](https://github.com/WordPress/wordpress-develop/blob/5.8.0/src/wp-admin/includes/image.php#L801-L809): if `WP_DEBUG` is disabled, then any exif errors are suppressed (and, contrariwise, if it is enabled they are not suppressed).
* In *this* situation, if the error is encountered then we don't expect it to be suppressed: the error/warning is useful information to have.

That to say, in cases where there is a problem with the image file (specifically, with the Exif meta data it contains), and where we've decided to turn on debug mode and use a tool like Query Monitor to find issues, we'd *want* these warnings to surface.

On the other hand, there does seem to be a problem with a number of the images referenced in [ample-data/sample_products.csv](https://github.com/woocommerce/woocommerce/blob/5.6.0/sample-data/sample_products.csv). 

* If I save [vnech-tee-green-1.jpg](https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/vnech-tee-green-1.jpg) to my local filesystem and pass it through `exif_read_data()` then I get the same error re an incorrect APP1 Exif Identifier Code.
* Other images such as [beanie-with-logo-1.jpg](https://woocommercecore.mystagingwebsite.com/wp-content/uploads/2017/12/beanie-with-logo-1.jpg) seem fine.

We *could* update the problematic images on [woocommercecore.mystagingwebsite.com](https://woocommercecore.mystagingwebsite.com) to avoid this, if that's helpful, but I also think we can simply ignore it. To that end, I'll close the issue...but please do leave a note if you disagree.
