### ISSUE TITLE
The ability of attributes to modify the price

### ISSUE THREAD

**Issue by PlatonB** [woocommerce/woocommerce#30342]
**Is your feature request related to a problem? Please describe.**
Woocommerce allows to set a fixed price for each combination of attributes (variation). But each attribute cannot modify the price.

**Real case**
I have a catalog of bonsai pots. There are many attributes with pot sizes. But there is a universal service for all products to drill drainage holes. It makes sense to set the original price for each size, but modify it based on the number of holes.

**Describe the solution you'd like**
I think there should be a column in the attribute table with added or subtracted in-place price values.
![Woo_price_modifiers_edited](https://user-images.githubusercontent.com/25541767/126824619-60c028d5-4829-498c-8326-4b5d401d49fe.png)

**Describe alternatives you've considered**
Something similar is [implemented](https://help.tilda.cc/online-store-payments/parameters/) in Tilda website builder. See "Additional options" section.

**Comment by tammullen** [comment]
Hi @PlatonB ,

Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the `votes needed` label and evaluate over time if this issue collects more feedback. 

Don’t be alarmed if you don’t see any activity on this issue for a while.

**Comment by ArchitectOfRuin** [comment]
I agree with this proposal. If we want to compete with Tilda, this option is required for implementation.
