### ISSUE TITLE
Create acceptance tests for querying orders via API.

### ISSUE THREAD

**Issue by jonathansadowski** [woocommerce/woocommerce#30353]
Prior to updating the [mappings for the orders endpoint](https://github.com/woocommerce/woocommerce/blob/b19500728b4b292562afb65eb3a0c0f50d5859de/includes/rest-api/Controllers/Version3/class-wc-rest-orders-controller.php#L102) to use the data store, we should create some acceptance tests, so that we can ensure that the response doesn't change as part of that process.

Note: There is a spike that will occur exploring API testing further. We may want to await that outcome. See p1627326740059500-slack-C01BWDDTGKX.

**Comment by zhongruige** [comment]
We can also consider adding the following CRUD tests on the orders API:

* Create an order: https://woocommerce.github.io/woocommerce-rest-api-docs/#create-an-order
* Get an order: https://woocommerce.github.io/woocommerce-rest-api-docs/#retrieve-an-order
* Update an order: https://woocommerce.github.io/woocommerce-rest-api-docs/#update-an-order
* Delete an order: https://woocommerce.github.io/woocommerce-rest-api-docs/#delete-an-order
