### ISSUE TITLE
Specify in the email settings what is adding an email

### ISSUE THREAD

**Issue by SiR-DanieL** [woocommerce/woocommerce#30357]
**Is your feature request related to a problem? Please describe.**

A customer was looking to edit the template of a specific email and we could not find where it was coming from since they had 3 different plugins that could add that email.

**Describe the solution you'd like**

In WooCommerce > Settings > Emails > Edit screen, it would be nice to have somewhere mentioned what plugin is adding the email so that it's easy to track down and make changes as needed.

**Describe alternatives you've considered**

None.

**Comment by rodelgc** [comment]
Hi @SiR-DanieL,

Thank you for taking the time to forward our customer's concern to us, we really appreciate your help. 

While this is clearly a great improvement/idea we won’t be able to tackle it in the upcoming weeks. We’re going to add it to our backlog where it will be considered for future releases.

For the meantime, I'll label this with `type: enhancement`.

Stay tuned for updates.

**Comment by vedanshujain** [comment]
@SiR-DanieL You can find the source of the template by clicking on the Mail name, template source will be at the bottom, see:

![email-settings](https://user-images.githubusercontent.com/7571618/127521081-8674db84-8014-4e8a-ab1f-6b27daa5e88a.png)

I am closing the issue assuming this is what you are looking for, but let me know if this is not the case and we will reopen.
