### ISSUE TITLE
Disabling of alerts in variation products

### ISSUE THREAD

**Issue by ut4utc** [woocommerce/woocommerce#30362]
Hi folks,

I would like to add to the store settings the disabling of alerts, which are very, very annoying. With a large number of products, when you need to recreate many attributes of variable products, alerts are so annoying that you want to throw your computer out the window)

Look at this video - I make short movie https://www.dropbox.com/s/36b9ifhgp5gt8wp/woocommerce-bugs.mov?dl=0

And there is a small problem / bug 0:09 - 0:11 in video we have a twice update data (reloading): repeated firing of the update of all variations. It is also quite annoying, since you start to select the desired value from the list and at this moment your screen refreshes and all that you tried to select - it clear and you have to click on the drop-down list again. This is an unnecessary reboot trigger, since when switching tabs, they cannot be switched without saving page 0:04. It turns out that the data is updated twice, which is not cost-effective and creates both a load on the server and simply strains.

Such a large number of actions have to be performed, and if you have hundreds of products, then it turns into a nightmare in which you have to click on different buttons flying out in different parts of the screen. And this is despite the fact that this video does not contain another alert from the browser itself - which pops up with the checkbox "Prevent this dialog from generating messages". I blocked this dialog box by specifying 0 in the about:config of browser so that it no longer existed.
I would like you to remove these terrible messages, as they make it impossible to quickly work with the store. Try yourself to do the same operations with 100 items or more.

If you need to show such messages (alerts) to the user, then you can simply add them above variations of plain text, without any buttons, just update some block/div, which is always under the 'Default form values' and at the right time the text in which is updated via javascript on 'The number of added variations and that no more than 50 values' ...

Please, if you cannot delete these alerts, then at least add a checkbox to the woocommerce store settings to disable them and remove duplicate trigger.

**Comment by rodelgc** [comment]
Hi @ut4utc,

Thank you for taking the time to share this idea, we really appreciate your help. 

While we appreciate you sharing your ideas with us, it doesn’t fit in with our current priorities for the project. At some point, we may revisit our priorities and look through the list of suggestions like this one to see if it warrants a second look. In the meantime, we are going to close this issue with the `type: enhancement` label and evaluate over time if this issue collects more feedback. 

Don’t be alarmed if you don’t see any activity on this issue for a while.

For the meantime, you may use WooCommerce's [Product CSV Import](https://docs.woocommerce.com/document/product-csv-importer-exporter/) feature which is a more preferred way of setting up products and variations in bulk.
