### ISSUE TITLE
Cleanup orders and coupons left in the trash after the tests run

### ISSUE THREAD

**Issue by zhongruige** [woocommerce/woocommerce#30371]
We need to cleanup the coupons and orders that have been left in the trash after the tests complete.

**Comment by zhongruige** [comment]
Looking into this one more @rrennick, the issue is that we don't get any coupons back with a status of `trash`, only the active and published ones. The Coupons API route also doesn't allow for passing in a status filter to get different coupons. 

So, as a result, I am wondering if we should just update the various coupon tests to do cleanup in an `afterAll() {}` statement instead, and keep using the existing deletion with the  `deleteAllRepositoryObjects()` as part of the setup. Since we seem to trash each coupon  in the tests, we can also potentially look into grabbing the coupon ID to put it into the DELETE route to make it faster.

For the orders, I ended up needing to write the logic below, as we needed to filter on status to get any/all orders that might have been created in the tests:

```javascript
deleteAllOrders: async () => {
	// We need to specfically filter on order status here to make sure we catch ever order to delete.
	const orderStatuses = ['pending', 'processing', 'on-hold', 'completed', 'cancelled', 'refunded', 'failed', 'trash'];
	for (let s = 0; s < orderStatuses.length; s++) {
		const orders = await client.get( ordersEndpoint + `?status=${orderStatuses[s]}` );
		if ( orders.data && orders.data.length ) {
			for ( let o = 0; o < orders.data.length; o++ ) {
				const response = await client.delete( ordersEndpoint + `/${orders.data[o].id}?force=true` );
				expect( response.statusCode ).toBe( 200 );
			}
		}
	}
},
```

**Comment by rrennick** [comment]
> I am wondering if we should just update the various coupon tests to do cleanup in an afterAll() {} statement instead

Some of the coupon tests currently trash the coupons at the end of the tests. We need to delete them instead of trashing. If we are going to update the tests to run in parallel then we can only use beforeAll() and afterAll() inside the describe tests. 

Standardizing on using beforeAll & afterAll for creating & deleting objects except where we are explicitly testing create/delete functionality will be a step toward cleaning up our code base.

**Comment by zhongruige** [comment]
>  Standardizing on using beforeAll & afterAll for creating & deleting objects except where we are explicitly testing create/delete functionality will be a step toward cleaning up our code base.

I agree, and it will make the Jest setup / retest flows a lot cleaner so we'll have less extra cleanup methods for shipping zones/classes, products, orders, etc. We can just use these cleanup API helper methods we've built (and add new ones in the future as needed) as part of the afterAll() statements, for example.

**Comment by zhongruige** [comment]
I ended up splitting out this work, so I submitted a PR for the order flow to start: https://github.com/woocommerce/woocommerce/pull/30398
