### ISSUE TITLE
Scroll bar disappears in New Product

### ISSUE THREAD

**Issue by Francof16** [woocommerce/woocommerce#30376]
In the section "New product" of Woocommerce, after several seconds the vertical scroll bar disappears. This only happens with the user role "Manager Shop". It does not happen with the "Administrator" user. I tried disabling the plugins and the error persists.

![image](https://user-images.githubusercontent.com/88121239/127418582-83fb3f18-7fb1-450c-9cdb-685246da7c18.png)

**Comment by rodelgc** [comment]
Hi @Francof16,

Thank you for submitting the issue. However, I can’t reproduce it on my end. I logged in as a Shop Manager and I can see the vertical scroll bar inside the "Product short description" text area:


https://user-images.githubusercontent.com/4509348/127449171-600dcb3a-412b-45a0-8be3-c030e055b2e0.mov



Please provide us with more details about the issue which may help us to evaluate it further.

**Comment by Francof16** [comment]
Hello.
I mean the general scroll bar.
Thanks for your reply

![image](https://user-images.githubusercontent.com/88121239/127570001-d9cc9fa4-ec2e-442b-9517-fe8db0c67c4e.png)

**Comment by AashikP** [comment]
Hello @Francof16 

Thank you for raising the issue. However, I can’t reproduce it on my as well when logged in as [Shop Manager](https://docs.woocommerce.com/document/roles-capabilities/#section-2): 

![https://d.pr/i/y8PLKD+](https://d.pr/i/y8PLKD+)

Recording: https://d.pr/i/1DAijt

The bar disappears if there's no movement, which is expected, but as soon as you use Keyboard / Mouse to scroll, it re-appears again.

From the screenshot you shared, I see that the Appearance and Tools sections are missing. Is it likely that you've assigned a custom user role called manager?

If not, and if you can get back to us with the browser and version you're using where this can be replicated successfully, we're happy to test this further.
