### ISSUE TITLE
Product images with large dimensions break WooCommerce blocks on WordPress.com Atomic sites

### ISSUE THREAD

**Issue by lakellie** [woocommerce/woocommerce#30379]
**Prerequisites (mark completed items with an [x]):**
- [x] I have have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
When a product using an image with large dimensions is added to a WooCommerce block, the editor crashes with a critical error the next time you try to open it: `There has been a critical error on this website`. 

We have received numerous user reports dating back to around December 2020 and as recently as this week. 

**Expected behavior**
The editor to load successfully.

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Open a WordPress.com Atomic site
2. Add a product and upload a product image with large dimensions. (Examples of user images that have triggered this error: 2MB and 9000 x 7000; 40MB and 6000 x 7000. So it seems to be more related to the dimensions rather than the file size.)
3. On any page, add a WooCommerce block, like the Hand-Picked Products block, and then add the test product to the block. 
4. Publish, then try to open the page in the editor again, and see a critical error.

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
This issue can be replicated on any WordPress.com Atomic site. I was not able to replicate this on a self-hosted site.

**Comment by rodelgc** [comment]
Adding a `needs developer feedback` label on this issue so Woo Core could take a look.

**Comment by jonathansadowski** [comment]
Thanks @rodelgc, I agree with the next-steps that @mikejolley laid out in his last comment... we need to do further investigation. I'm going to up the priority of this as well.

**Comment by peterfabian** [comment]
~Let's make `Add Product Image` handling consistent with WP if possible, then.~

**Comment by namiokuzono** [comment]
Also reported in p9F6qB-9VL-p2

**Comment by peterfabian** [comment]
As this has been raised again in p9F6qB-9VL-p2, I had a closer look at this again. 

I tried to upload a large image via `Set product image` or `Add product gallery images`, but it would either upload the file correctly, generate thumbnails and then work in the editor, or it would fail with the error message mentioned above (`The server cannot process the image. This can happen if the server is busy or does not have enough resources to complete the task. Uploading a smaller image may help. Suggested maximum size is 2560 pixels`).

Based on this, I'm inclined to say that the theory that Photon takes over the initial image upload and WC core then attempts to generate the thumbnails and fails seems like the most probable one.

As for Photon, the docs says it handles `make_subsize()` and `multi_resize()`, but the way we call it from WC doesn't actually go through either of those functions, but fails via `imagecreatefromstring` called when loading the image editor. The interesting bit here is that it's the same exact way the WP core crashes when uploading a large image via Media Upload, so might be worth handling it in Photon somehow as well?

Anyway, after reproducing it on wordpress.com, I created the above PR that seems to fix the problem. Please test if possible.

**Comment by peterfabian** [comment]
I think this would also help: https://core.trac.wordpress.org/ticket/23127

**Comment by thracefulton** [comment]
Another reported instance in 5609057-zen. Using WooCommerce Blocks along with Kadence WP Blocks, and images of approximately 8000 x 5000 px across the board.

**Comment by imanish003** [comment]
As highlighted by @peterfabian, there's an existing [track ticket](https://core.trac.wordpress.org/ticket/23127) in the WordPress core that directly relates to this.

Given that the resolution of this issue is dependent on developments within the WordPress core, we will be closing this issue on our end. I encourage all of you to keep an eye on the progress of the WordPress track ticket for further updates and insights.
