### ISSUE TITLE
Spike: Research a way to make wp-admin ajax endpoints available via REST API

### ISSUE THREAD

**Issue by jonathansadowski** [woocommerce/woocommerce#30395]
Desired outcome of the spike: a post detailing a possible approach for surfacing wp-admin ajax endpoints from the REST API.

Considerations:
* Proper handling of request variables.
* Authentication via cookie.
* Handling of nonces.
* CORS handling.
* Security concerns.

**Comment by coreymckrill** [comment]
This spike is no longer planned (or perhaps it already happened?). We can spin up a new issue if/when we decide to revisit this research.
