### ISSUE TITLE
Subtotal tax not rounded in order via API

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce#30424]
The `subtotal` in the `line_items.taxes` array on an order in the REST API is not rounded while the `subtotal_tax` of the line item is. All of the other amounts in the response are rounded so one would expect this to be rounded as well. Create an order with

Product price: 634.15 x 1
Tax rate: 20%
Coupon: 7% discount

produces the following:

```
  "line_items": [
    {
      "id": 11518,
      "name": "Awesome Silk Wallet",
      "product_id": 12002,
      "variation_id": 0,
      "quantity": 1,
      "tax_class": "",
      "subtotal": "681.88",
      "subtotal_tax": "136.38",
      "total": "634.15",
      "total_tax": "126.83",
      "taxes": [
        {
          "id": 11,
          "total": "126.83",
          "subtotal": "136.376"
        }
      ],
      "meta_data": [],
      "sku": "awesome-silk-wallet-88154343",
      "price": 634.15,
      "parent_name": null
    }
  ],
```

The relevant code is likely https://github.com/woocommerce/woocommerce/blob/trunk/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php#L160:L167 (being rounded) and https://github.com/woocommerce/woocommerce/blob/trunk/includes/rest-api/Controllers/Version2/class-wc-rest-orders-v2-controller.php#L190:L196 (no rounding).

**Comment by vedanshujain** [comment]
Closing in favor of #25720
