### ISSUE TITLE
Alterations to SKU number isn't saving

### ISSUE THREAD

**Issue by BazaarVelvet** [woocommerce/woocommerce#30420]
Please provide us with the information requested in this bug report. Without these details, we won't be able to fully evaluate this issue. 
Bug reports lacking detail, or for any other reason than to report a bug, may be closed without action.

**Prerequisites (mark completed items with an [x]):**
- [x ] I have carried out troubleshooting steps and I believe I have found a bug.
- [x ] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

**Describe the bug**
Changes I make to a product SKU do not save (when trying to overwrite an existing product SKU that is incorrect)

**Expected behavior**
I expected editing the SKU to result in a permanent change. (I expected it to save this new information)

**Actual behavior**
When I try to edit an SKU number, my changes do not save. I have tried this from 'quick edit' on the 'products' page, and also when on the full edit product page. I also tried from the stock manager page. In all these three cases, I am able to type in the amended SKU, but once I click save, and re-enter the page, the SKU field returns to the original SKU number. 

**Steps to reproduce the bug (We need to be able to reproduce the bug in order to fix it.)**
Steps to reproduce the bug:
1. Go to 'products'
2. click 'all products'
3. select an existing product
4. click 'quick edit'
5. delete existing SKU
6. type in new SKU
7. click update
8. ERROR when you see this product listed it still has old SKU
NOTE: This also happens when you access the product data from the product page and from the stock manager.

**Screenshots**

**Isolating the problem (mark completed items with an [x]):**
- [ x] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [ x] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [x ] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
We use the [WooCommerce System Status Report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/) to help us evaluate the issue. 
Without this report we won't be able to fully evaluate this issue.
<details>
```
The System Status Report is found in your WordPress admin under **WooCommerce > Status**. 
Please select “Get system report”, then “Copy for support”, and then paste it here.
```
</`
### WordPress Environment ###

WordPress address (URL): https://bazaarvelvet.com
Site address (URL): https://bazaarvelvet.com
WC Version: 5.5.2
REST API Version: ✔ 5.5.2
WC Blocks Version: ✔ 5.3.3
Action Scheduler Version: ✔ 3.2.1
WC Admin Version: ✔ 2.4.4
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_GB
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.4.21
PHP Post Max Size: 256 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
cURL Version: 7.66.0
OpenSSL/1.1.1k-fips

SUHOSIN Installed: –
MySQL Version: 5.7.32-35-log
Max Upload Size: 256 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.5.2
WC Database Prefix: wp_xarnhrbu_
Total Database Size: 69.47MB
Database Data Size: 54.48MB
Database Index Size: 14.99MB
wp_xarnhrbu_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_xarnhrbu_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_xarnhrbu_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_xarnhrbu_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_xarnhrbu_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_xarnhrbu_woocommerce_order_itemmeta: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_xarnhrbu_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_xarnhrbu_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_xarnhrbu_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_xarnhrbu_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_xarnhrbu_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_xarnhrbu_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_xarnhrbu_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_xarnhrbu_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_xarnhrbu_actionscheduler_actions: Data: 0.08MB + Index: 0.13MB + Engine InnoDB
wp_xarnhrbu_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_xarnhrbu_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_xarnhrbu_actionscheduler_logs: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_xarnhrbu_atum_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_xarnhrbu_atum_product_data: Data: 0.27MB + Index: 0.19MB + Engine InnoDB
wp_xarnhrbu_berocket_termmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_xarnhrbu_braapf_product_stock_status_parent: Data: 0.13MB + Index: 0.08MB + Engine InnoDB
wp_xarnhrbu_braapf_product_variation_attributes: Data: 0.17MB + Index: 0.39MB + Engine InnoDB
wp_xarnhrbu_braapf_term_taxonomy_hierarchical: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_xarnhrbu_braapf_variation_attributes: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_xarnhrbu_bv_activities_store: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_xarnhrbu_bv_dynamic_sync: Data: 0.09MB + Index: 0.00MB + Engine InnoDB
wp_xarnhrbu_bv_fw_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_xarnhrbu_bv_ip_store: Data: 0.17MB + Index: 0.13MB + Engine InnoDB
wp_xarnhrbu_bv_lp_requests: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_xarnhrbu_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_xarnhrbu_comments: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_xarnhrbu_e_submissions: Data: 0.02MB + Index: 0.27MB + Engine InnoDB
wp_xarnhrbu_e_submissions_actions_log: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_xarnhrbu_e_submissions_values: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_xarnhrbu_jet_smart_filters_indexer: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_xarnhrbu_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_xarnhrbu_nf3_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_xarnhrbu_nf3_object_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_xarnhrbu_nf3_relationships: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_xarnhrbu_options: Data: 6.03MB + Index: 0.39MB + Engine InnoDB
wp_xarnhrbu_postmeta: Data: 29.55MB + Index: 9.69MB + Engine InnoDB
wp_xarnhrbu_posts: Data: 13.50MB + Index: 1.11MB + Engine InnoDB
wp_xarnhrbu_rank_math_404_logs: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_xarnhrbu_rank_math_analytics_gsc: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_xarnhrbu_rank_math_analytics_objects: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
wp_xarnhrbu_rank_math_internal_links: Data: 0.16MB + Index: 0.06MB + Engine InnoDB
wp_xarnhrbu_rank_math_internal_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_xarnhrbu_rank_math_redirections: Data: 0.23MB + Index: 0.05MB + Engine InnoDB
wp_xarnhrbu_rank_math_redirections_cache: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_xarnhrbu_stock_log: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_xarnhrbu_termmeta: Data: 0.06MB + Index: 0.06MB + Engine InnoDB
wp_xarnhrbu_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_xarnhrbu_term_relationships: Data: 0.25MB + Index: 0.14MB + Engine InnoDB
wp_xarnhrbu_term_taxonomy: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wp_xarnhrbu_usermeta: Data: 0.33MB + Index: 0.27MB + Engine InnoDB
wp_xarnhrbu_users: Data: 0.06MB + Index: 0.05MB + Engine InnoDB
wp_xarnhrbu_wc_admin_notes: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_xarnhrbu_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_xarnhrbu_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_xarnhrbu_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_xarnhrbu_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_xarnhrbu_wc_gpf_render_cache: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_xarnhrbu_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_xarnhrbu_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_xarnhrbu_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_xarnhrbu_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_xarnhrbu_wc_product_meta_lookup: Data: 0.30MB + Index: 0.63MB + Engine InnoDB
wp_xarnhrbu_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_xarnhrbu_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_xarnhrbu_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_xarnhrbu_woocommerce_gpf_google_taxonomy: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_xarnhrbu_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_xarnhrbu_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB

### Post Type Counts ###

acf-field: 9
acf-field-group: 1
attachment: 3098
bnfw_notification: 1
br_filters_group: 2
br_product_filter: 14
e-landing-page: 1
elementor_library: 22
jet-smart-filters: 5
nav_menu_item: 45
nf_sub: 1
page: 30
post: 92
product: 406
product_variation: 2393
revision: 808
shop_order: 17
shop_order_refund: 1
wpforms: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (25) ###

WooCommerce Rms: by Rms – 1.3
Advanced Custom Fields: by Delicious Brains – 5.9.9
WordPress Backup & Security Plugin - BlogVault: by Backup by BlogVault – 4.63
Better Notifications for WP: by Made with Fuel – 1.8.6
PublishPress Capabilities: by PublishPress – 2.1
Custom Post Type UI: by WebDevStudios – 1.9.2
Elementor Pro: by Elementor.com – 3.3.5
Elementor: by Elementor.com – 3.3.1
Login No Captcha reCAPTCHA (Google): by Robert Peake and Contributors – 1.6.11
Really Simple SSL: by Really Simple Plugins – 5.0.6
Safe SVG: by Daryll Doyle – 1.9.9
Rank Math SEO: by Rank Math – 1.0.69.1
Sticky Header Effects for Elementor: by Rwattner – 1.4.3
Category Order and Taxonomy Terms Order: by Nsp-Code – 1.5.7.5
WooCommerce No Shipping Message: by dangoodman – 2.0.11
WooCommerce AJAX Products Filter: by BeRocket – 3.0.4
WooCommerce Google Analytics Integration: by WooCommerce – 1.5.2
WooCommerce Lead Time: by Barn2 Plugins – 1.5.4
WooCommerce Google Product Feed: by Ademti Software Ltd. – 9.4.0
WooCommerce Stock Manager: by StoreApps – 2.6.0
WooCommerce Wholesale Prices Premium: by Rymera Web Co – 1.25
WooCommerce Wholesale Prices: by Rymera Web Co – 1.14.2
WooCommerce: by Automattic – 5.5.2
WP Mail SMTP: by WPForms – 2.9.0
WP-Sweep: by Lester 'GaMerZ' Chan – 1.1.5

### Inactive Plugins (1) ###

WP Fastest Cache: by Emre Vona – 0.9.2

### Settings ###

API Enabled: –
Force SSL: –
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: simple (simple)
variable (variable)
grouped (grouped)
external (external)

Taxonomies: Product Visibility: outofstock (outofstock)
exclude-from-search (exclude-from-search)
exclude-from-catalog (exclude-from-catalog)
featured (featured)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #7 - /catalogue
Basket: #4837 - /cart
Checkout: #4838 - /checkout
My account: #4839 - /my-account
Terms and conditions: #10469 - /terms-conditions

### Theme ###

Name: Hello Child
Version: 1.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Hello Elementor
Parent Theme Version: 2.4.1
Parent Theme Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash
WooCommerce Support: ✔

### Templates ###

Overrides: –

### WooCommerce Google Product Feed options ###

Google merchant centre product feed: Enabled
Google merchant centre product review feed: -
Bing merchant centre feed: -
Google merchant centre local product inventory feed: -
Google merchant centre local products feed (legacy): -
Google merchant centre product inventory feed (legacy): -
Include variations in feed: Enabled
Send "item group ID": No
Debug key: d95fc629-1c51-4829-a99d-ae51468b7f6d

### WooCommerce Google Product Feed fields ###

Title: Pre-populates from product product_title.
Availability: Defaults to "in stock".
Brand: 
Manufacturer Part Number (MPN): 
Product Type: 
Google Product Category: 
Size system: 

### Action Scheduler ###

Complete: 204
Oldest: 2021-07-05 13:31:46 +0000
Newest: 2021-08-04 12:17:59 +0000

Pending: 2
Oldest: 2021-08-04 12:59:17 +0000
Newest: 2021-08-06 11:34:27 +0000

### Status report information ###

Generated at: 2021-08-04 12:21:03 +00:00
`>

**Comment by BazaarVelvet** [comment]
These are the three ways of editing the SKU that I have tried. The changes do not save on any of these.

![image](https://user-images.githubusercontent.com/88436999/128190108-153dd18a-f5d8-4654-862f-08f622cfc050.png)
![image](https://user-images.githubusercontent.com/88436999/128190207-811d3c07-c576-40f9-b70c-8bedaa733f62.png)
![image](https://user-images.githubusercontent.com/88436999/128190366-20397ef7-2048-4da9-9976-6e5cd2b0a49d.png)

**Comment by BazaarVelvet** [comment]
sorry closed by accident

**Comment by juliaamosova** [comment]
Hi @BazaarVelvet,

Thank you for submitting the issue. However, I can’t reproduce it using the steps you provided. Everything is working as expected on my end. I tested the full SKU edit via the product page as well as the quick edit using the WooCommerce 5.5.2 version (latest stable). 

Below are the quick screengrabs I made testing 2 scenarios.

### Case 1 - editing SKU via product page:

http://g.recordit.co/czxSo91q6p.gif

### Case 2 - editing SKU via "quick edit":

http://g.recordit.co/WDbum3H4kq.gif

There are a few things I can recommend doing here:

- Test your site for a theme and plugins conflict
- Contact your hosting company to check server configuration

More details on each are below.

### Test your site for a theme and plugins conflict

I see that you have several plugins installed and that you don’t use one of our default themes which could cause an issue. Please test your site for theme and plugins conflict. To do that, you’d need to deactivate all plugins except for WooCommerce and switch the default theme such as [Storefront](https://en-gb.wordpress.org/themes/storefront/). Then test again.

If the issue is resolved with the default theme and all plugins deactivated, it means that one of your plugins or a theme is causing the issue. You will then need to enable it one by one and test every time you do that in order to figure out which plugin is causing the issue.

### Contact your hosting company to check server configuration

If you notice product variations, tax rates, and other data sets not saving, Suhosin (a security module in PHP) may be preventing the POST data from being saved. This issue can also be caused by servers with version PHP 5.3.9+ and servers running `mod_security`. Please see more details in [Problems with large amounts of data not saving (variations, rates etc)](https://docs.woocommerce.com/document/problems-with-large-amounts-of-data-not-saving-variations-rates-etc/) that contains the steps you can take to resolve it. 

Please let us know how it goes.
