### ISSUE TITLE
Remove Refunded article in Shipping/packing PDF

### ISSUE THREAD

**Issue by Z3TA** [woocommerce/woocommerce#30425]
problem: When an article/item has been refunded, it still shows up when you generate the Shipping/packing PDF label

suggestion: Don't  include refunded articles when generating the shipping/packing PDF label.
suggestion: Automatically strike-though/cross off the refunded articles in the shipping/packing PDF label

**Comment by juliaamosova** [comment]
Hi @Z3TA,

Thank you for submitting the issue! 

WooCommerce Core doesn't generate shipping and packing pdf labels by default therefore, it will likely need to be addressed by the plugin that does it. Do you know what do you use to generate those shipping and packing pdf files?

**Comment by Z3TA** [comment]
Thanks @juliaamosova it's a plugin: https://wordpress.org/support/plugin/woocommerce-pdf-invoices-packing-slips/
