### ISSUE TITLE
Sorting grouped product

### ISSUE THREAD

**Issue by AdriaanPruyssers** [woocommerce/woocommerce#30428]
I have posted this issue in de wordpress.org forum and have been asked to report the issue here.
In grouped product I cannot  change the product order anymore. The order reverts back to what it was before and new products remain at the bottom.
Woocommerce 5 5 2 Theme Plum wordpress 5.6.4
Someone else with the latest versions and theme storefront has replicated the issue

https://wordpress.org/support/topic/grouped-product-order/

**Comment by tammullen** [comment]
Hi @AdriaanPruyssers 

Thank you for reporting the issue. However, this issue had been reported previously here https://github.com/woocommerce/woocommerce/issues/30107 with a fix included in the upcoming WooCommerce 5.6 release. We are closing your issue in favor of the previously submitted. Please continue sharing your feedback there if needed.
