### ISSUE TITLE
Get variations by sku

### ISSUE THREAD

**Issue by maxim-skuvault** [woocommerce/woocommerce#31370]
It would be very useful to have an endpoint to get variations by sku, without having so supply the productId.

We use the sku to look up variations in WooCommerce and then update the stock quantity. Currently, to get a variation from the api, the only option is to pass the parent productId, which we don't have nor do we want to keep track of outside wooCommerce. This severely limits the usefulness of the api for the purpose of updating quantities. We're having to get **all** products and then all variations for each product and then filter variations by sku, which is a huge performance hit

**Comment by juliaamosova** [comment]
Hi @maxim-skuvault,

Thank you for opening the issue! It requires further feedback from the WooCommerce Core team. I am adding the `needs developer feedback` label to this issue so that the Core team could take a look. 

Please note it may take a few days for them to get to this issue. Thank you for your patience.

**Comment by barryhughes** [comment]
Thanks for the further discussion of this issue.

Supporting `/wp-json/wc/v3/products?sku=<VARIATION|PRODUCT_SKU>` seems like a reasonable enhancement (ie, we can also return variable products in cases where one of its variants has the requested SKU). Marking this as a future enhancement; in the meantime if there are any concerns with this solution please just add a fresh comment.

**Comment by maxim-skuvault** [comment]
>

**Comment by maxim-skuvault** [comment]
@barryhughes 
> Supporting `/wp-json/wc/v3/products?sku=<VARIATION|PRODUCT_SKU>` seems like a reasonable enhancement (ie, we can also return variable products in cases where one of its variants has the requested SKU). Marking this as a future enhancement; in the meantime if there are any concerns with this solution please just add a fresh comment.

Thanks. Yes, this would work for our purposes.

**Comment by yordivd** [comment]
Is there any progress or feedback on this?

**Comment by barryhughes** [comment]
Hi! This is not something we are actively working on at present, as it is a low priority from our perspective. However, we are always interested in contributions from the community—and would be receptive to a pull request.

**Comment by hoangtu92** [comment]
Came here for a solution and got none. Such a life :D. I'll leave my solution here to make someone else's life easier. You're welcome


`
// Modify the rest api to search both product and product variation
add_filter("woocommerce_rest_product_object_query", function (array $args){
			$args["post_type"] = array( 'product', 'product_variation' );
			return $args;
		}, 10, 1);`

**Comment by jorgeatorres** [comment]
Hi everyone! 👋 

Filtering the results of `/wc/v3/products` by SKU (`?sku=...`) works with product variations too, as [indicated above](https://github.com/woocommerce/woocommerce/issues/31370#issuecomment-915264935) and is supported on v1, v2 and v3. The suggested "fix" above makes me think there's something else going on for those that haven't been able to use this functionality.

I'm going to close this issue as it seemsthis can't be reproduced on a recent version, but feel free to re-open or add any other details if you think we've missed something.
