### ISSUE TITLE
Notice: Function add_menu_page was called incorrectly. The seventh parameter passed to add_menu_page() should be an integer representing menu position. Please see Debugging in WordPress for more information

### ISSUE THREAD

**Issue by BackuPs** [woocommerce/woocommerce#31781]
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

In wordpress 6.0 i get this notification error on the latest woocommerce beta running

Notice: Function add_menu_page was called incorrectly. The seventh parameter passed to add_menu_page() should be an integer representing menu position. Please see Debugging in WordPress for more information

Version 6.2.0-rc.1

class-wc-admin-menus.php is not using a integer but a float on line 64 & 76

![afbeelding](https://user-images.githubusercontent.com/6078370/151950165-2174a777-aadd-4c0d-b7f4-15e39e752ff1.png)

also in wp-content/plugins/woocommerce/packages/woocommerce-admin/src.WcPayWelcomePage.php line 51 & 75

![afbeelding](https://user-images.githubusercontent.com/6078370/151947740-880f57c3-2704-4dee-b5af-5540839b4c25.png)

also in/wp-content/plugins/woocommerce/packages/woocommerce-admin/src/PageController.php line 441  should be intval($options['position'])

![afbeelding](https://user-images.githubusercontent.com/6078370/151949748-dc0fa6df-669e-4604-bc51-25d0a9db1f4e.png)

Please fix

### Expected behavior

change the float to a integer

### Actual behavior

just turn on debug mode and visit any admin page.

### Steps to reproduce

Just update to latest beta wp 6.0

### WordPress Environment

not needed

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by BackuPs** [comment]
found a similar post. I was looking at the issue titles only. Anyway the solution is easy to apply.

**Comment by ObliviousHarmony** [comment]
Hi @BackuPs,

Thank you for reporting the issue. WooCommerce Admin is being developed in another repository: http://github.com/woocommerce/woocommerce-admin. 

I am going to move your bug report there so that the right team could take a look further.
