### ISSUE TITLE
Add support for updating to nightly

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce#32118]
WooCommerce core now generates a [nightly build](https://github.com/woocommerce/woocommerce/archive/nightly.zip). We should add support for updating to the nightly build.

**Comment by webdados** [comment]
PLEASE!! Do this.

![image](https://user-images.githubusercontent.com/6853605/153609897-5dc00928-cae8-4f31-baaa-7553335f96d1.png)

We could at least have a "last available nightly build". We don't need the list of all available.

**Comment by rrennick** [comment]
This is covered by the live branches feature.
