### ISSUE TITLE
Collapsible items with collapsible list not animating

### ISSUE THREAD

**Issue by louwie17** [woocommerce/woocommerce#32245]
### Describe the bug
The collapsible items within the collapsible list are not animated when being dismissed, while the items that are displayed by default are being animated correctly.

### To Reproduce
1. Go to **WooCommerce > Home**
2. Run `npm run example -- --ext=add-task` and enable the plugin, you will have to add a couple more tasks to this demo, having the tasks be dismissable.
3. Collapse the extended task list
4. Dismiss one of the items (notice how there is no animation)
5. Dismiss the top item (notice how it is animated).

### Expected behavior
Should animate correctly, just like the top items.

### Additional context
The collapsible list uses the experimental list, which adds a CSSTransition to each child. The collapsible items are nested within there own parent component, and thus are not being wrapped with a CSSTransition.
Replacing `{ displayedChildren.hidden }` with this should fix it:
```
<TransitionGroup>
		{
			Children.map(
				displayedChildren.hidden,
				( child ) => {
					const {
						onExited,
						in: inTransition,
						enter,
						exit,
						...remainingProps
					} = child.props;
					const animationProp =
						remainingProps.animation ||
						listProps.animation;
					return (
						<CSSTransition
							timeout={ 500 }
							onExited={ onExited }
							in={ inTransition }
							enter={ enter }
							exit={ exit }
							classNames="woocommerce-list__item"
						>
							{ cloneElement( child, {
								animation: animationProp,
								...remainingProps,
							} ) }
						</CSSTransition>
					);

					// TODO - create a less restrictive type definition for children of react-transition-group. React.Children.map seems incompatible with the type expected by `children`.
				}
			) as React.ReactElement[]
		}
		{ /* { displayedChildren.hidden } */ }
	</TransitionGroup>
```

**Comment by ilyasfoo** [comment]
Hey, @louwie17! I've mistakenly change labels/project for this issue. Since the issue is quite old, perhaps you could take a look if the issue is still relevant?

**Comment by louwie17** [comment]
I will close this one, as we are not using this in our task list anymore, and things seems to work well in storybook.
