### ISSUE TITLE
Continue without Jetpack account redirects to Jetpack site

### ISSUE THREAD

**Issue by elizaan36** [woocommerce/woocommerce#32243]
### Describe the bug
When a WordPress.com account doesn't exist, during WooCommerce onboarding you land on this create account screen with a confusing bit of text at the bottom including "Continue without a user account"
<img width="895" alt="Screen Shot 2021-07-27 at 9 59 10 AM" src="https://user-images.githubusercontent.com/5121465/127198956-2a3c0b36-fba2-424e-b09d-65c8dd6456df.png">

Since recent updates to the Jetpack onboarding flow, the "Continue without a user account" link directs to the Jetpack site with all plan options.
<img width="1093" alt="Screen Shot 2021-07-27 at 9 59 23 AM" src="https://user-images.githubusercontent.com/5121465/127200368-eb11ce9e-807a-4c47-b67e-8eebc8ad6b7a.png">

The new WooCommerce user is stuck at this point if they don't want to create an account or choose a Jetpack product.

### To Reproduce
I tested this in a private window on a Jurassic Ninja site.

1. Install and activate WooCommerce
2. Complete the store profiler and install free business features
3. In the last step on the create account screen, click on the link "Continue without a user account"

### Proposed solution
The link "Continue without a user account" should redirect to WooCommerce home with the free version of Jetpack selected by default.
Here's an updated layout for the text on this screen.

![Jetpack create account screen](https://user-images.githubusercontent.com/5121465/127200909-b0daad00-152d-4e99-88b6-ed0160ce0a74.png)

cc @pmcpinto since we chatted about this on Slack

**Comment by chihsuan** [comment]
Looks like this bug is over 6 months old. @pmcpinto Can we close this? (according to p90Yrv-2Bc-p2)

**Comment by pmcpinto** [comment]
Thanks for the ping. Unfortunately this problem went unnoticed during the last cycle planning sessions. We don't have tracking on that button, but this is one of the main flows of new users, so I think we should fix it. I will add to cycle 22

**Comment by chihsuan** [comment]
I think we can close this when we release the new Core profiler since the Jetpack Connect screen will be changed.

**Comment by chihsuan** [comment]
Closing this since we've removed that button from the connection screen for core profiler.
