### ISSUE TITLE
DropZoneProvider deprecated in WP 5.8

### ISSUE THREAD

**Issue by rrennick** [woocommerce/woocommerce#32248]
**Describe the bug**
I'm running E2E tests against the WP nightly and seeing 

```
console.warn
    wp.components.DropZoneProvider is deprecated. Note: wp.component.DropZone no longer needs a provider. wp.components.DropZoneProvider is safe to remove from your code.
```

I searched and the only instance appears to be https://github.com/woocommerce/woocommerce-admin/blob/38fbb4aedd0f21cf21ddaa6af93e48564fd35324/client/profile-wizard/steps/theme/uploader.js#L11

**To Reproduce**

1. Clone the `woocommerce` repo & `npm install`
2. Create `tests/e2e/docker/nightly.sh`
```
#!/bin/bash

echo "Initializing WooCommerce E2E"

wp plugin activate woocommerce
wp theme install twentynineteen --activate
wp user create customer customer@woocommercecoree2etestsuite.com --user_pass=password --role=customer --path=/var/www/html

# we cannot create API keys for the API, so we using basic auth, this plugin allows that.
wp plugin install https://github.com/WP-API/Basic-Auth/archive/master.zip --activate

# install the WP Mail Logging plugin to test emails
wp plugin install wp-mail-logging --activate

echo "Updating to WordPress Nightly Point Release"
wp core update https://wordpress.org/nightly-builds/wordpress-latest.zip

echo "Updating the database"
wp core update-db
```
3. Run `npx wc-e2e docker:up tests/e2e/docker/nightly.sh`
4. Run `npx wc-e2e test:e2e`
5. Message is logged on the second test

**Comment by rrennick** [comment]
Removed the stale.

**Comment by mattsherman** [comment]
This is a warning. The code handles the deprecation and indicates that `DropZoneProvider` can't be removed until WP 6.0. I don't see anything we can do at this point. Keeping this open.

**Comment by rrennick** [comment]
Reopened. We missed the stale warning due to the holiday break.

**Comment by rrennick** [comment]
Closing this as it has been addressed.
