### ISSUE TITLE
TableCard component: Support more Pagination props

### ISSUE THREAD

**Issue by ecgan** [woocommerce/woocommerce#32255]
**Is your feature request related to a problem? Please describe.**

I would like to use the TableCard component and hide the "per page" picker in the Pagination using `showPerPagePicker={ false }`, but there isn't a way to do that, or to pass other Pagination props.

https://github.com/woocommerce/woocommerce-admin/blob/dde6b184ed6d14985402dc76f7078bf03b7985d7/packages/components/src/table/index.js#L246-L253

**Describe the solution you'd like**

Allow the TableCard component to accept more Pagination props and pass it down to Pagination.

A third-party reference example: [Ant Design Table](https://ant.design/components/table/#API)'s `pagination` props. You can pass any [Ant Design Pagination](https://ant.design/components/pagination/) props via `<Table pagination={ /* pagination config here */ }>`

**Describe alternatives you've considered**

Build my own TableCard component by using Table and Card components.

**Should this be prioritized? Why?**

**Additional context**

**Comment by nerrad** [comment]
I'm closing this. This is unlikely something that will be prioritized anytime soon and it's possible the new DataViews component(s) from WordPress will be used for this type of view in the future.
