### ISSUE TITLE
Write dev blog post on new task list features

### ISSUE THREAD

**Issue by louwie17** [woocommerce/woocommerce#32253]
We have several new task list features coming down the line ([task hierarchy](https://github.com/woocommerce/woocommerce-admin/pull/6916), [remind me later support](https://github.com/woocommerce/woocommerce-admin/pull/6923), and potentially changing the structure using slot fill).

This issue will be a reminder to write a developer blog post covering the above features, once things have settled a bit, and all the kinks have been worked out (if there were any).

**Comment by ilyasfoo** [comment]
Hey, @louwie17. Do you think this is still relevant?

**Comment by louwie17** [comment]
> Hey, @louwie17. Do you think this is still relevant?

@ilyasfoo potentially? depending on how active the task list is being worked on now?
I know when I created this issue we have gone through several iterations after that, but things should be more settled now, so writing something now might not be a bad idea.

**Comment by ilyasfoo** [comment]
Agreed, @louwie17. This would be a good task for porter

**Comment by adrianduffell** [comment]
I'll close this out due to age
