### ISSUE TITLE
Pagination component: support custom per_page_options

### ISSUE THREAD

**Issue by ecgan** [woocommerce/woocommerce#32256]
**Is your feature request related to a problem? Please describe.**

Currently the Pagination component has [hardcoded `PER_PAGE_OPTIONS`](https://github.com/woocommerce/woocommerce-admin/blob/dde6b184ed6d14985402dc76f7078bf03b7985d7/packages/components/src/pagination/index.js#L12), i.e. 25, 50, 75, 100.

It would be great for it to be customizable. For my project's use case, we would like to have a small table with a default page size of 5.

**Describe the solution you'd like**

Make the per page options customizable via props.

**Describe alternatives you've considered**

Current workaround that I'm using is to hide the page size picker by specifying `showPerPagePicker={ false }`.

**Should this be prioritized? Why?**

**Additional context**

An example / reference of other third party Pagination component: [Ant Design Pagination](https://ant.design/components/pagination/) (See `pageSizeOptions`)

**Comment by nerrad** [comment]
This will likely be replaced with pagination components/styles coming from the DataViews components in WordPress (as a part of the WP Phase 3 design).
