### ISSUE TITLE
Remote Payment Recommendations: Update third party plugins

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce#32258]
Instead of including items like `fields`, `connection` and `manageUrl` in the remote specs, we can include these in the payment gateways and as part of the `WC_Payment_Gateway` abstract class - https://github.com/woocommerce/woocommerce/blob/master/includes/abstracts/abstract-wc-payment-gateway.php

This will require updates to the abstract class in `woocommerce` as well as updates to all third party payment provider plugins.

| Gateway     | Pull Request                                                        | Status      | Owner     |
| ----------- | ------------------------------------------------------------------- | ----------- | --------- |
| bacs        |  https://github.com/woocommerce/woocommerce-admin/pull/7073 | merged | @joshuatf |
| eway        | 112-gh-woocommerce/woocommerce-gateway-eway | merged   | @joshuatf   |
| klarna      |                                                                     | ?         | @samueljseay         |
| mercadopago | https://github.com/mercadopago/cart-woocommerce/pull/281            | need external help | @joshuatf |
| mollie      |                                                                     |      ?       |      @samueljseay      |
| paypal      | https://github.com/woocommerce/woocommerce-paypal-payments/pull/164 | ready to merge | @joshuatf |
| paystack      | https://github.com/tubiz/woo-paystack/pull/64 | need external help | @joshuatf |
| payu-india  |                                                                     |      ?     |           |
| razorpay    | https://github.com/razorpay/razorpay-woocommerce/pull/195 | need external help|  @joshuatf    |
| square      | 627-gh-woocommerce/woocommerce-square | needs review | @joshuatf  |
| stripe      | https://github.com/woocommerce/woocommerce-gateway-stripe/pull/1569 | needs review | @joshuatf |
| payfast     | https://github.com/woocommerce/woocommerce-gateway-payfast/pull/43  | ready to merge | @joshuatf |
| wcpay     | https://github.com/Automattic/woocommerce-payments/pull/2014| ready to merge | @joelclimbsthings  |

### Status descriptions
**ready to merge:** We can merge ourselves, and the PR seems to be ready (with potential merge conflicts.
**needs review:** Waiting on PR review.
**need external help:** PR is ready, but we lack the permissions to merge.
**needs feedback:** Changes required.
**merged**: Already merged.
**?**: Uncertain what the status is here.

**Comment by joelclimbsthings** [comment]
Just jumping in on this before it meets its demise by stalebot. Is there a reason why the WCPay PR hasn't been merged, much less the others? @joshuatf @mattsherman . Is this considered out of our hands?

**Comment by joelclimbsthings** [comment]
@joshuatf @mattsherman 

Pedro [has expressed interest](https://github.com/woocommerce/woocommerce-admin/issues/7836#issuecomment-961195546) in getting these PRs moving/merged. As mentioned on my last comment, I'm just wondering if these PRs are considered out of our hands? If not, is this as simple as reaching out to responsible parties and/or merging ourselves if possible?

**Comment by pmcpinto** [comment]
Hey @laurendavissmith we need help on the Transact side to review/merge a couple of PRs and publish a new version of some extensions owned by Transact: Wcpay, Stripe, PayPal and Square

To summarize, this work will allow us to render the API Keys inputs as a step in the payments task after the user installs the extension:

![138977503-7b87b633-47d8-4d16-b921-9e858fa4f0ac](https://user-images.githubusercontent.com/3380168/141102707-d90e7501-b9d3-4266-91ec-99d761d87859.png)

Can you check with the Transact teams when it's possible to move forward with this?

@Roslynlavery we also need your help to unblock this regarding the extensions owned by our partners: eWay, Klarna, Mollie, Mercado Pago, Paystack, PayU, Razorpay and Payfast. Some of the PRs are ready to merge.

Let me know if you have any questions. Thanks!

**Comment by laurendavissmith** [comment]
@pmcpinto @joshuatf  We'll get it taken care of, can they be released as soon as they are merged, or does it need to wait to coincide with the wc-admin release?

**Comment by joelclimbsthings** [comment]
Thanks @laurendavissmith ! The relevant changes in wc-admin were already released, so no need to delay. 

Looking again at he PRs listed above, it seems Stripe and Paypal are a bit out of date. I'll look into getting those updated. The PRs for WCPay and Square should still be good to go 👍🏻 . Let me know what else we can do to help get those merged as well.

**Comment by haszari** [comment]
> We'll get it taken care of, can they be released as soon as they are merged, or does it need to wait to coincide with the wc-admin release?

@pmcpinto Clarifying this further - when do we need to release these extensions by, is it urgent? We just released Square this week, happy to do another release soon if needed (nothing scheduled right now).

**Comment by pmcpinto** [comment]
> @pmcpinto Clarifying this further - when do we need to release these extensions by, is it urgent? We just released Square this week, happy to do another release soon if needed (nothing scheduled right now).

This update will remove friction from the setup flow, but I'm not sure if doing another release is going to disrupt the current sprint of your team. I think it's ok to wait 2-3 weeks to do another release.

**Comment by Roslynlavery** [comment]
> @Roslynlavery we also need your help to unblock this regarding the extensions owned by our partners: eWay, Klarna, Mollie, Mercado Pago, Paystack, PayU, Razorpay and Payfast. Some of the PRs are ready to merge.

@pmcpinto could you clarify what you mean by unblock here? What do we need from our partners to move this forward? Seems like an easy one to motivate, definitely an improved flow.

**Comment by pmcpinto** [comment]
@Roslynlavery our partners need to update their extensions to improve the step after installing the extension in the Payments task. Our team is improving the documentation, and it will create an example to facilitate the implementation by the partners. We count on having this ready to be shared during the 1st week of December. I'll let you know as soon as we have the documentation ready.

**Comment by mattsherman** [comment]
Keeping this open as I need to make sure there are not loose ends to tidy-up.

**Comment by pmcpinto** [comment]
> @Roslynlavery our partners need to update their extensions to improve the step after installing the extension in the Payments task. Our team is improving the documentation, and it will create an example to facilitate the implementation by the partners. 

Hey @Roslynlavery here's the [link](https://github.com/woocommerce/woocommerce-admin/blob/main/docs/features/payment-gateway-suggestions.md) to the documentation created by @joshuatf with all the instructions required for getting started.
Feel free to reach out in case you have any questions. Thanks!

**Comment by becdetat** [comment]
@pmcpinto Can we close this issue?

**Comment by pmcpinto** [comment]
> @pmcpinto Can we close this issue?

Sorry, I missed this ping. Yes, I'll close it. Thanks!
