### ISSUE TITLE
Refunds / Returns not shown in order history

### ISSUE THREAD

**Issue by giacogiaco** [woocommerce/woocommerce#32263]
**Describe the bug**
Refunded orders are not listed in the order history for that day. 

**To Reproduce**
1. Go to Analytics > Revenue
2. Click on the section 'RETURNS'
3. In the graph, find a day on which a return happened
4. Then, in the table below, find that day and (in column two) click on the orders of that day
5. You'll be lead to a page that shows you all orders of that specific day – unfortunately, it doesn't show the order that was refunded. Why not?

**Expected behavior**
There should be some indication of a refund that happened on that day. Maybe link to the day on which the order that was later refunded was placed.

**Additional context**
Is **returns** the same as **refunds**?

**Comment by joshuatf** [comment]
@LevinMedia Do you have a preferred way of handling this?

**Comment by mattsherman** [comment]
@LevinMedia Cycling back on this one to see if you have any input to provide.

**Comment by LevinMedia** [comment]
@joshuatf @mattsherman can we proceed with the plan I detailed in my most recent [comment](woocommerce/woocommerce#32263)?

**Comment by joshuatf** [comment]
Sounds like a good plan to me.  Thanks for confirming, @LevinMedia!
