### ISSUE TITLE
Add default variation to variable product template

### ISSUE THREAD

**Issue by louwie17** [woocommerce/woocommerce#32269]
This ticket is an addition to woocommerce/woocommerce-admin#5296

When creating a variable template through the onboarding steps **Add my products > Start with a template > Variable product** we want to have a default variation added [#76 from the sample data](https://github.com/woocommerce/woocommerce/blob/master/sample-data/sample_products.csv).

Currently we use the [product importer class](https://github.com/woocommerce/woocommerce-admin/blob/main/src/API/OnboardingTasks.php#L195) to create these templates and pass a csv, see the [variable csv](https://github.com/woocommerce/woocommerce-admin/blob/main/src/API/Templates/variable_product.csv). We can add a variation to the same csv (like [sample data](https://github.com/woocommerce/woocommerce/blob/master/sample-data/sample_products.csv#L2)), which would add one if you include the SKU column.
The only problem with the SKU is, that if a user creates a product template with the original SKU, and then tries to create another product template, it will fail, as the SKU already exists.

**Describe the solution you'd like (feel free to do something different)**
Add the SKU column, and variation data to the variable csv template.
Add auto update SKU option to the current [import sample products function](https://github.com/woocommerce/woocommerce-admin/blob/main/src/API/OnboardingTasks.php#L150) and create a unique sku if one already exists (you should be able to update the `parsed_data` in the `$importer_class`.

The variation sku would need updating to match the format of the new variable product.

**Describe alternatives you've considered**
I have tried without the SKU, or only adding a SKU to the variable product, both of these options didn't work.

One option could be to separate the variation in another file, and just run the importer on the variation after the variable has been created, with the matching SKU.

**Acceptance criteria**
- When creating a variable product template (**Add my products > Start with a template > Variable product**) a variation should be added, similar to the sample-data:
<img width="1435" alt="Screen Shot 2021-01-25 at 1 21 23 PM" src="https://user-images.githubusercontent.com/2240960/105741042-3ea44300-5f10-11eb-8ece-1fb1822c8ddb.png">

**Comment by adrianduffell** [comment]
@chihsuan did this get resolved?

**Comment by chihsuan** [comment]
> @chihsuan did this get resolved?

Thanks for the ping! @adrianduffell  Actually, I'm not sure if we still need this because we have removed sample data from the product task in https://github.com/woocommerce/woocommerce/issues/38136. I think we can close this one. What do you think? cc @ilyasfoo

**Comment by ilyasfoo** [comment]
Yes we should close this one out since sample data is removed 👍
