### ISSUE TITLE
Documentation: Update Activity Panel Docs & Home Screen

### ISSUE THREAD

**Issue by timmyc** [woocommerce/woocommerce#32268]
With the recent migration of Activity Panels to the Home Screen, the documentation that is published at https://docs.woocommerce.com/document/activity-panels/ is a wee bit out of date.

Currently the documentation still has sections for

![image](https://user-images.githubusercontent.com/22080/107993684-e355f580-6f8f-11eb-9e32-515dc1c963cd.png)

Tasks:

- [ ] Migrate the content for the Reviews and Stock panel to https://docs.woocommerce.com/document/home-screen/ - might need some screen shot updates too.
- [ ] Add a section to the Activity Panel page about the contextual Help Menu that appears in this area

**Comment by rjchow** [comment]
The page at https://docs.woocommerce.com/document/activity-panels/ is no longer published, and leads to a 404

However, the screenshot at https://docs.woocommerce.com/document/home-screen/ still shows the older version without the activity panel, and is also missing reviews and stock.

I had trouble accessing the relevant pages on docs.woocommerce.com to make the necessary modifications, so I'm just removing the needs-triage label as it is something that we should get around to.

**Comment by chihsuan** [comment]
> I had trouble accessing the relevant pages on docs.woocommerce.com to make the necessary modifications

Hey @rjchow What's the trouble you had? It seems that we can edit the page using WordPress editor because `docs.woocommerce.com` is a WordPress site.

@adrianduffell Can we update the document page directly or do we need to request approval?

**Comment by rjchow** [comment]
I think there was a server load issue at that time and listing the pages took >10 minutes per page so it was impossible to find the pages in a reasonable amount of time 😓 

That could be resolved by now maybe? I remember it coinciding with the entire woocommerce.com going down

**Comment by chihsuan** [comment]
Looks like the page is really out of date. We'll need to do the following task.

- [x] Update/add screenshots
- [x] Add Reviews panel section
- [x] Add Stock panel section
- [x] Add Help Menu section
- [x] Update Store Management to indicate that they are not shown when the setup checklist is being shown
- [x] Update Store Setup Checklist to point out how to enable them on the setting page when they're hidden

**Comment by chihsuan** [comment]
@woocommerce/ghidorah  This is not urgent. I just updated the [Home Screen Documentation](https://woocommerce.com/document/home-screen/). Could I get a review on this today or next week? Thanks.

**Comment by adrianduffell** [comment]
The Home Screen documentation looks terrific, thank you @chihsuan 🏅

**Comment by chihsuan** [comment]
Looks like https://woocommerce.com/document/activity-panels/ is no longer published again...

I'm closing this for now.
