### ISSUE TITLE
Jetpack installation during profile wizard will fail without a useful error in older WP versions

### ISSUE THREAD

**Issue by samueljseay** [woocommerce/woocommerce#32267]
Jetpack's minimum version requirement is quite strict, requiring users to be on Wordpress 5.6. But WC min version is 5.4.

If the user's WP version doesn't meet requirements when they tick "install Jetpack" during OBW it will fail without a good explanation of the issue, which is gonna be frustrating for users.

I think this also makes the whole experience of installing plugins during OBW more frustrating, because in the code Jetpack is usually the first one we attempt to install. When it fails it stops the OBW moving on.

This is tough to fix but my suggestion is that we should (if possible) check WP version requirements for the plugins against the user's WP version before recommending installing plugins (and also inform them of how to fix the issue). I could imagine fixing this will increase the effectiveness of any plugin partnership we do in the OBW in future so it could be quite important to fix.

cc @pmcpinto @elizaan36

**Comment by chihsuan** [comment]
Since this affects the OBW, I think we should fix this soon, though it has been here for a while.

**Comment by pmcpinto** [comment]
> Since this affects the OBW, I think we should fix this soon, though it has been here for a while

Agreed. I added this issue to the cycle 22 report for scoping and prioritization

**Comment by elizaan36** [comment]
@verofasulo Not sure if this is still an issue but could be part of the NUX work you're doing if so!

**Comment by chihsuan** [comment]
> I think a good next step can be adding a prop identifying the WP version to the wcadmin_storeprofiler_store_business_details_continue, so we identify the % of users affected by this

I've add `wp_version` prop to `storeprofiler_store_business_details_continue` in https://github.com/woocommerce/woocommerce/pull/34439. Will check % of users affected by this when it's released.

**Comment by chihsuan** [comment]
I've checked the `wcadmin_storeprofiler_store_business_details_continue_variant` track and confirmed all users use > WP 6.0.2 now so users are not affected by this.
