### ISSUE TITLE
WCPay task should show further setup required

### ISSUE THREAD

**Issue by joshuatf** [woocommerce/woocommerce#32277]
In https://github.com/woocommerce/woocommerce-admin/pull/4145 the check for whether wcpay is configured or not was updated to check if a Stripe connection has been established.

This issue will involve adding a note to the task if the payment has been configured, but still requires further setup (pending account or other error) using the `needs_setup()` method.

![](https://user-images.githubusercontent.com/4500952/82101205-bf901700-96c0-11ea-94ee-2e0f8c7d6e2c.png)

**Comment by chihsuan** [comment]
Closing this. We've revamped the WCPay task
