### ISSUE TITLE
[WC 4.4 beta1] Stats overview: no data shown after the order had been placed and completed

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#32273]
**Describe the bug**

`Stats overview` widget shows no data after the order had been placed and completed. The data is, however, shown in the Analytics section if I click on `View detailed stats` at the bottom of the `Stats overview` widget. 

**To Reproduce**

1. Complete OBW.
2. Complete all tasks on the task list on the Home screen. 
3. Place an order on the site. 

I have an order in `Processing` status at this point but the `Stats overview` widget shows no orders:

![sale](https://user-images.githubusercontent.com/19143190/88851356-a9bbc980-d1ba-11ea-85b1-65cee16b344b.jpg)

4. Proceed with fulfilling the order and marking it as `Completed`. 
5. Check the `Stats overview` widget - still shows that no orders or sales had been made today:

![sale2](https://user-images.githubusercontent.com/19143190/88851542-e4bdfd00-d1ba-11ea-9e66-bcd888ef075f.jpg)

6. Click on `View detailed stats` at the bottom of the `Stats overview` widget - you should be taken to the `Analytics` section and see that the order was recorded there in the `Charts` section but not in the `Performance`: 

![sale3](https://user-images.githubusercontent.com/19143190/88851872-6ca40700-d1bb-11ea-83bb-706deb81efc6.jpg)

**Expected behavior**

Not sure if it takes some time for the data to be available but it is odd to me that `Charts` already showing some data but the `Stats overview` widget and the `Performance` section don't. 

**Screenshots**

See above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.5
* Browser: Chrome
* Version: 84.0.4147.89 (Official Build) (64-bit)

**Additional context**

N/A.

**Comment by mattsherman** [comment]
This issue still exists as of WCA 2.8.0-rc.2. I'm going to add this to our backlog to take a look at this in an upcoming cycle.

**Comment by chihsuan** [comment]
@mattsherman This bug is over 6 months old. But if Mothra can handle this, can I move this into "Mothra backlog"?

**Comment by chihsuan** [comment]
@mattsherman I just moved it to the Mothra backlog.

**Comment by louwie17** [comment]
I can't reproduce this anymore on a fresh JN site, when making sure the scheduled actions are all run.

I am closing this issue for now given the lack of activity over the last two years.
Feel free to re-open.
