### ISSUE TITLE
[WC 4.1 beta.2] `Set store location details` section doesn't work after completing "Tax set up step" 

### ISSUE THREAD

**Issue by juliaamosova** [woocommerce/woocommerce#32282]
**Describe the bug**

After the user is able to set up tax by enabling automated tax calculation and connecting their WordPress.com account, they see the option to connect Jetpack and WC Services:

![Screen Shot 2020-04-20 at 3 23 50 PM](https://user-images.githubusercontent.com/19143190/79791285-105b5c80-831b-11ea-93a8-21b15fee3a77.png)

If the user clicks on `No thanks, I'll configure manually`, they get the `Set up tax` task is completed:

![completed](https://user-images.githubusercontent.com/19143190/79790860-67acfd00-831a-11ea-8482-576d48a4d8ea.jpg)

The user, however, can still click on the `Set up tax` task and presented with the store details form to fill out. I can't always reproduce it. Only sometimes. Note that before the `Good News!` window is shown, there is a quick "loading" of the store location section:

![](http://g.recordit.co/a0mmMDcyCr.gif)

![Screen Shot 2020-04-20 at 3 26 57 PM](https://user-images.githubusercontent.com/19143190/79791552-8364d300-831b-11ea-9265-6ece35fedeb6.png)

Sometimes it doesn't go through and the user sees the actual form to fill out store location details. After doing it, the `Continue` button doesn't work:

![](http://g.recordit.co/W0LguyGC1E.gif)

I thought this was one-time flakiness but it was also reported by one of our testers - see Ref: pb22l9-8V-p2#comment-395 - which is why I decided to report it. 

**To Reproduce**

1. After new OBW is done, click on `Set up tax` task and select for the taxes to be set up automatically. You will be asked to connect your WP.com account - do that. 
2. When presented with `Good News!` window, don't continue and instead select `No thanks, I'll configure manually`. 
3. The `Set up tax` task should be completed at this point. Try clicking on it again to see if you'd get the store location details section instead of the expected `Good News!` section. 

**Expected behavior**

If the store details section appears, the user should be able to proceed without any issues. 

**Screenshots**

See above. 

**Desktop (please complete the following information):**

* OS: macOS Catalina 10.15.4
* Browser: Chrome
* Version: 81.0.4044.92 (Official Build) (64-bit)

**Additional context**

Tested on the JN site.

**Comment by joelclimbsthings** [comment]
Looks like this is overdue to be closed, doing so in preparation for the merge.
