### ISSUE TITLE
Problem in Persian Calendar displayed in WooCommerce – Shamsi/Jalali

### ISSUE THREAD

**Issue by clonerdev** [woocommerce/woocommerce#37462]
### Prerequisites

- [X] I have carried out troubleshooting steps and I believe I have found a bug.
- [X] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

Hello WooCommerce team
For stores operating in Farsi (persian), the dates entered in WooCommerce are translated incorrectly. On the other hand, there are no dates such as July, May, February, etc. in the translation section of the plugin in the repository and in the WooCommerce po file. modify the po file.
The dates must be available in the po file and also be in shamsi/jelali format for Farsi (persian) language.
 Please add the dates and names of the months used in the po file of the WooCommerce language
To solve this problem, I don't want to use a third-party plugin or the code in the theme's function file, because it's not the right way for a big store site.
Thank you

### Expected behavior

Adding month names and dates to the po file
Correction of Persian dates (shamsi / jalali)

### Actual behavior

Adding month names and dates to the po file
Correction of Persian dates (shamsi / jalali)

### Steps to reproduce

![1](https://user-images.githubusercontent.com/107908907/228066047-6173dc3b-c532-45e9-8dd1-ee3b55559187.png)

### WordPress Environment

woocommerce > orders > Date

### Isolating the problem

- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by lsinger** [comment]
Hello @clonerdev,

Thank you for submitting this issue. It seems the screenshot you provide might contain some personally identifiable information of your customers. I'll therefore close and delete this issue.
