### ISSUE TITLE
[CLI] Additional commands

### ISSUE THREAD

**Issue by claudiosanches** [woocommerce/woocommerce#9853]
- [ ] Create Category
- [ ] Edit Category
- [ ] Delete Categories
- [ ] Create Tag
- [ ] Get Tag
- [ ] List Tags
- [ ] Edit Tag
- [ ] Delete Tags
- [ ] Create Attribute
- [ ] Edit Attribute
- [ ] Get Attribute
- [ ] List Attributes
- [ ] Delete Attributes
- [ ] Create Attribute Term
- [ ] Edit Attribute Term
- [ ] Get Attribute Term
- [ ] List Attribute Terms
- [ ] Delete Attribute Terms
- [ ] Create Shipping Class
- [ ] Edit Shipping Class
- [ ] Get Shipping Class
- [ ] List Shipping Classes
- [ ] Delete Shipping Classes

**Comment by entr** [comment]
Consider adding `update-db` command like built-in `wp core updated-db'

**Comment by warrenseine** [comment]
I suggest an `install` command which would install the WooCommerce pages (calling `WC_Install::create_pages()`). That'd be very useful to automate the installation of a WooCommerce site.

I've done that in a very rough `wp-cli` custom command and it works as expected.

**Comment by mikejolley** [comment]
@claudiosmweb could we redo the CLI to mirror the rest api entirely - so we don't need to develop them separately.

**Comment by mikejolley** [comment]
Replaced with #11611
